### ISSUE TITLE
Driver comes into "traffic" with it's combine by turning behind it from "wrong" side

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#1003]
Maybe it's related to solution for #977 ?

When the driver arrives from front at the side of the unload pipe all goes well.
When the driver arrives from the front at the wrong side ti goes into turn as usually but then takes the turn too tight and gets into traffic with his combine.

I think the solution for #977 was to remove the virtual "waitingpoint" behind the combine.
Imho this virtual waitingpoint should have been only offset the amount of the actual "side offset" in "Settings combi mode".
I assume that way the driver would turn to that waypoint and from there on going straight to unload position without a inclined trailer.

got a video of it if necessary, have to cut and upload it though, will take some time.

**Comment by ThomasGaertner** [comment]
can you post the video ? thanks

**Comment by AndyK70** [comment]
what a shame, lost that video. Only got another one a couple of minutes later showing the same situation, but instead of claiming to have traffic it cuts straight through the combine:
[▶ LS15 CP0055 Driving behind Combine from "wrong" side - YouTube](https://www.youtube.com/watch?v=0hD4dwiiLdQ)

**Comment by AndyK70** [comment]
tested with v0069 and not occurred again.
I think it can be closed.
