### ISSUE TITLE
Sugar Beet Havester Telling Tipper to Stop V4.01.043dev

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1005]
Sugar Beet Harvester(Roster 260) telling the tipper to stop even though it has not unloaded the the Harvester. The harvester stopped at the edge of the field. This happened 4 times. First time I just stooped the tipper and got the harvester going again. Second time it seemed to fix it self. I was alt tabbed at the time. Third time I just removed the combine assignment. Just thought you would like to know. Pathfinding was deactivated. On the fourth time I activated pathfinding while it was being told to stop and it started right up. Shown below is what happened 
![fsscreen_2015_01_25_19_58_32](https://cloud.githubusercontent.com/assets/10678220/5894195/7416ede8-a4cd-11e4-97f6-13400f2d6407.png)

**Comment by Satissis** [comment]
First try updating to the latest version, since there might have been something that fixed that.

If you still are having the problem, then test again with debug channel 4 active and then post the log on gist and add the link here.

**Comment by pops64** [comment]
Might not be the same cause but the issuse is pretty close. This time with the SE260 and instead of being told to stop. It wouldn't move even though it was trying to drive behind the combine but was not doing anything. I fixed this by driving it to a different postion and stoping the driver did not allow the combine to resume. This was v4.01.067dev. I will try to see if the sugar beet havester is still bugged.

https://gist.github.com/pops64/217764e4e2e5e34d3300


![fsscreen_2015_01_27_15_02_25](https://cloud.githubusercontent.com/assets/10678220/5926104/91d49172-a636-11e4-898c-199a852c94be.png)
