### ISSUE TITLE
Request: Transfer mode - Default to "Stop at last point", add separate option to stop at trigger.

### ISSUE THREAD

**Issue by TommyC81** [Courseplay/courseplay#1007]
It seems counter intuitive that Transfer mode by default tries to return to the first point and re-run the track. I suggest splitting the option "Stop at last point or at next trigger": One for "Stop at last point" which should default to "Activated" and a second option "Stop at next trigger" which should default to "Deactivated".

Not sure if this would have any downside that I've missed, when would you want a Transfer mode to repeat? It seems that if you want to Transfer mode to repeat that your doing the interaction less often than when you simply want to transfer equipment conveniently, ie. the total number of clicks would in most cases be reduced.

Obviously this is a personal preference as I use Transfer mode to get equipment from point A to B and then handle them a bit more individually. Forgetting to "Deactivate" the rerun of the Transfer mode course is a bit of pain as vehicles end up at random spots.

**Comment by gui7545** [comment]
Personally, I use transfer mode to woodchooper to work at a define position.
I start register a course and stop it at the same point. My course have only 2 points at the same place and the vehicle do it in loop.

**Comment by TommyC81** [comment]
Good point! I guess my strongest case would really be "the total number of clicks would in most cases be reduced" by having "Stop at last point" activated by default.

In your case it's likely something that is setup once and then runs for quite some time (ie not an action that is repeated many times), whereas sending 5 vehicles to Field XX (or merging a return and transfer to the next field etc.) would require the option to be activated repeatedly. It would seem more intuitive to have it Activated by default  (however, not an empirical fact).

Another thought I had is that the downside of forgetting to Deactivate the option to Stop at last point (if indeed Activated would be the default) would in most cases have less of a side effect than the opposite, but this is just my gut feeling.

In either case, the option is not available until you actually start the drive, maybe make it visible before the drive starts as well?

**Comment by AndyK70** [comment]
#917

**Comment by AlterSack1966** [comment]
I like this idea but for all modes. My courses always start at a parking position for the device and end up there again. As yet the refuel trigger or a refill trigger occurs prior to the Park position the devices remain after field work not at the Park position are available but are in places where other vehicles blocked. With this function I could force that the device goes to the Park position.

I wanted to formulate this idea already but thought I'm the only one of such problems, apparently, but also other people have this need.

**Comment by AndyK70** [comment]
me2 and @JakobTischler already added #917 to the tracker. :wink:

**Comment by JakobTischler** [comment]
1. We've discussed separating them and decided against it.
2. The default value will stay "deactivated", as otherwise this would have fatal consequences for modes other than mode 5.

**Comment by AndyK70** [comment]
Would you explain which arguments were against separating them?
Maybe I'm missing an important point I don't see at this time.

**Comment by ThomasGaertner** [comment]
I'm pretty sure that we don't  need to explain all our decisions. 
In this case it would be a huge amount of changes for a change we are not convinced of. I our eyes it would lead to more problems than to advantages. In all modes except mode 5 it would lead to trouble to have this option active , in field work mode the tractor would stop at the end of the unloading / refilling course , in mode 2 and 3 it would stop at the field edge and so on...

**Comment by AndyK70** [comment]
> I'm pretty sure that we don't need to explain all our decisions. 

Of course you don't have to. I was just asking if you would for this particular decision.
Thank you for doing it and now I see your points and agree with you.
