### ISSUE TITLE
Tipper loves doing donuts V4.01.64dev

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1009]
For some reason when the Tipper approaches the combine from the non fruit side it cant make the u-turn. It just keeps doing donuts. The combine is the axial-flow 9230 and the tipper and the big body 930s. The combine cant be moving in order to create this bug ie it is stopped because it is full, also the tractor must come in parallel with the harvester if it comes in at an angle it is able to make the turn. I adjusted it to below the auto value of 13m and it broke out of the loop on one occasion, the other time I tried it did not work.. Debug channels 3 and 4 are on. If you want another channel let me know. Thanks

https://gist.github.com/pops64/68de650cc7deae1a3411

![fsscreen_2015_01_26_16_37_38](https://cloud.githubusercontent.com/assets/10678220/5909006/7adb4392-a57a-11e4-8f26-5acdad280e39.png)
![fsscreen_2015_01_26_16_34_08](https://cloud.githubusercontent.com/assets/10678220/5909011/84b87088-a57a-11e4-98ed-d02dd1ccebc4.png)

**Comment by ThomasGaertner** [comment]
which value do you mean with " auto value of 13m " ? if its the turn diameter, then please try to increase the value till it works fine and post the log with debug 6 active . Thanks

**Comment by ThomasGaertner** [comment]
closed due to inactivity...
