### ISSUE TITLE
v0063 script error while offloading Grimme Rootster 604 to trailer

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#1011]
I was harvesting sugar beets manually using GPS Mod with:
* Deutz Aggrostar 6.61
* Suer SB 1000 (front)
* Grimme Rootster 604

I have a Driver controlled by courseplay who is assigned manually to the Grimme Rootster 604.
Pathfinding deactivated, Start at 50%, Drive on at 90%
* NH T6
* NH 750TL
* Stoll Pallet fork HS 1500
* Kroeger Agroliner HKD 302

Logfile: [FS15 logfile (2015-01-26 23:35)](https://gist.github.com/AndyK70/53294b825d8cbb5c2a15#file-fs15-logfile-2015-01-26-23-35)

Tested twice just to confirm.
Driver comes to the Grimme, alignes under the pipe and offloads the Grimme.
When finished and he should turn to waitingpoint the script error comes out and can't stop my vehicle nor the driver.

**Comment by JakobTischler** [comment]
Just for testing, replace [line 632](https://github.com/Courseplay/courseplay/blob/9e2bc53fbbb36bcda3594890bbc062611b1934ac/mode2.lua#L632) in `mode2.lua` with
```lua
local backupDistance = worldToLocal(combine.cp.DirectionNode or combine.rootNode, tx,ty,tz);
```

**Comment by AndyK70** [comment]
replaced and works fine, no errors detected.
