### ISSUE TITLE
Forage Wagon not unloading - CP 0064

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1012]
https://gist.github.com/sootysax/14b0f768c0e7e8797f75/
log: driving forward through silage area with debug 1 active

CP Version 0064
Holzhausen15 Map
Using a Deutz 6.61 with a Euroboss 330 forage wagon. 

Generated course will fill wagon to 100% and tractor will proceed to the unloading route, but beacon will not come on.  'Drive now' button is still visible.

Reaching the silage area, the tractor will drive straight through and not unload and return to the field.
Tip Trigger reached is displayed and the unload icon lights up.  This is driving forward thru the dump area.

If I stop and restart the course on the unload section and hit the 'drive now' button, the trailer will unload 5% of the load and then drive through without unloading the rest.

If I record a course that reverses into the silage area, the tractor will start dumping at the back of the pit and pull forward and reverse again, back and forth, dumping in sections 2&3 and then pulling out, leaving the wagon 28% full.

https://gist.github.com/sootysax/3861de344be005afaec2/
log: reverse with debug 1 

ALSO:

CP does not seem to realize that the wagon is full..   If, on the way to the last waypoint to start the unload route, the tractor gets hung up on a tree or a fence, and you have to resume the course from the nearest waypoint, the trailer will proceed along the fieldwork course and not to the unload route even though the wagon is at 100%.   Hitting the Drive Now button has no effect.   The only way to get the tractor to proceed to the unload route is to cancel and reload a saved route.   

I think this is the reason that it is not unloading at the silage area, it doesn't realize it is on the unload route.

**Comment by Satissis** [comment]
Thomas and I, have been having a bit of a talk about this today and it might be the map it self that is the problem.
If you are doing exact the same with the default map in the BGA it should work without any problem, regarding the BGA.
I have a theory that the way the BGA sections are added are not directly right next of each other but rather mixed together. If that's the case, then yeah it's definitely the map's fault.
I haven't downloaded the map it self, since I don't wanna use uploaded.net to download it (Simply takes too long and don't wanna pay for it)

**Comment by Satissis** [comment]
@sootysax any updated on this ?

**Comment by sootysax** [comment]
oh sorry.. ive moved on to a different map that defaults to a larger forager..  i know that little forager has been problematic though.

**Comment by Satissis** [comment]
so we can close this then ??

**Comment by sootysax** [comment]
if it comes up again ill reopen

**Comment by bertfarm** [comment]
courseplay (developer
