### ISSUE TITLE
Compliment: course overview on pda map is a great feature!

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#1013]
This one is such a useful feature, I use it very often.

Thank you for implementing this.
Great!

(no issue at all)

**Comment by TommyC81** [comment]
Can only agree, well done!

(Fingers crossed for an in-game node editor as well...)

**Comment by Maxcdr** [comment]
Very nice feature ! +1

**Comment by pops64** [comment]
Same. A++ One suggestion if we could include the course width in the diagram for field work or have it someplace  would be great if possible :D

**Comment by Satissis** [comment]
@pops64 The course width is not saved in the course........ yet, so that will not be possible.
When I say yet, that means that we have started to save the width for the course if they are generated. Something I'm going to use on the new turning maneuvers I'm working on.
If we are going to add it when the new turn maneuver is added is not sure.

**Comment by PromGames** [comment]
Very good job. A+++

We will see big differences in the representations depending on the ability of Map creators to introduce good projections and enough RATIO through size in the PDA_MAP to get a good view and better accuracy.

Some comparison pictures:

GOOD PDA_MAP (1x)
Bjornholm Standard Maps,big pda_map size (2048x2048) compare with real world size 1024x1024
 RATIO= 2/1 . Very good results

![2015-01-28_0-03-11](https://cloud.githubusercontent.com/assets/9979168/5929278/a293baa0-a682-11e4-8624-99ac4f2a43fd.jpg)

Same Image
![2015-01-28_0-07-14](https://cloud.githubusercontent.com/assets/9979168/5929280/a9af47c8-a682-11e4-8624-bd1379335e49.jpg)


MIG Map 4x Map. 
Small size pda_map.dds  (1024x1024) compare with real world size (4096x4096)  
RATIO= 1/4 Biggest deformations

First Photo CP Frame on standard PDA_MAP.dds (1024x1024)

![2015-01-27_23-34-38](https://cloud.githubusercontent.com/assets/9979168/5929527/db35f632-a684-11e4-9958-68ae99028b98.jpg)

Second photo on picture taken with giants editor highlighting roads and bmp image at 4096x4096

![2015-01-27_23-43-28](https://cloud.githubusercontent.com/assets/9979168/5929593/617b616e-a685-11e4-82b4-27442038ab28.jpg)
