### ISSUE TITLE
Bigx1100 selceting wrong side for tipper 4.01.67dev

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1017]
Chaff Harvester Big x1100 is having issues playing friendly with his tippers. Sometimes the tippers will be on the fruit side when in automatic pipe side selection. Pathfinding is active. This causes numerous traffic issues. The tippers seem to flip flop the correct side. One will be on the correct side going west direction but fruit side going in the east direction. I don't believe that it is dectecting the fruit side or somthing. Because I forced it to set on the right side and the tipper went left. I found this in the log

[dbg4 lp167177] combine.workWidth: 13.60,vehicle.cp.combineOffset: 11.50, calculated offset: 11.50, fruitSide: 404notFound  

https://gist.github.com/pops64/0c36efea06c22845b617

![fsscreen_2015_01_28_11_56_52](https://cloud.githubusercontent.com/assets/10678220/5942325/c7d7d9ec-a6e4-11e4-8e63-e69041ff40f0.png)

**Comment by ThomasGaertner** [comment]
please try v 0070 or higher and report....

**Comment by Llogeyr** [comment]
Thomas,
Thankyou. I was having same issue. With a lower version, .0054 I think. Updated to .0072 now and works great. Thanks again.
