### ISSUE TITLE
Amazon Pantera

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#1018]
Hello Course Play team
My problem is that if I want the fields syringes with Amazon Pantera syringe, the syringe they can always expanded at the return fares to the trigger!

Thanks Paul

**Comment by JakobTischler** [comment]
Please confirm that I understand you correctly: the Pantera is always unfolded (its arms extended) while driving to the refilling trigger.

None of us has the Pantera so there's no way to find out what's going on.

**Comment by Paul2510** [comment]
If the Amazon Pantera goes to refill it does not always work together! The Pantera was a Christmas present from Giants!

**Comment by Paul2510** [comment]
http://www.farming-simulator.com/downloads/FXUU7O83ZU00GH782213KBBI23O078/FS15_amazonePantera.exe

**Comment by Paul2510** [comment]
I'm sorry I did not wanted it to you deliberate evil only therefore provide a way to test it did

**Comment by Maxcdr** [comment]
I used two Pantera at the same time on the same field with lane offset and with a refilling course (as explained here http://courseplay.github.io/courseplay/en/manual/index.html#driveMode4).

Everything went fine...

Here is the link from Giants to download Pantera: http://www.farming-simulator.com/downloads/FXUU7O83ZU00GH782213KBBI23O078/FS15_amazonePantera.exe

**Comment by Paul2510** [comment]
The error only occurs rarely on the times he forgets to close

**Comment by JakobTischler** [comment]
I could not confirm your problem. The Pantera opens and closes its arms as it should.

**Comment by Paul2510** [comment]
Thanks for your help! It's just a rare mistake!
  Another concern I would have! The GARANT VTR 25,000 aluminum light always work on the trigger ride!

**Comment by Paul2510** [comment]
It happens only very rarely! Probably there is an error of MOD! One problem I would have! When I try to delete a course then crashes the game! Have a lot of courses to part with over 10,000 waypoints!

**Comment by JakobTischler** [comment]
Please don't mix problems and issues - check for existing issues or create a new one.
