### ISSUE TITLE
Suggestion: make "show crossing points" separate from "show waypoints"

### ISSUE THREAD

**Issue by OldFisher** [Courseplay/courseplay#1022]
Let me be honest with you: there are some times when I don't need to see crossing points. Most of the time, actually. Even when I'm in "show all waypoints" mode. They can be somewhat distracting too.
So maybe the option to show crossing points could be extracted into a separate settings? The "show waypoints" then would have "none", "begin/end" and "all" modes.

**Comment by JakobTischler** [comment]
I like the idea of adding more control over what is shown. I've decided to stray away from the "click-thru-options" and rather use direct buttons:

![cpvisualwaypointsignsoptions](https://cloud.githubusercontent.com/assets/748857/5992128/3d447694-aa1a-11e4-9c68-b4900ba7874d.png)

**Comment by OldFisher** [comment]
That's even better. More direct control, less clicks.

**Comment by OldFisher** [comment]
Works as intended. The link between work course and refill/unload course is now hidden which is a good thing too.
