### ISSUE TITLE
Mode 4 and 6: using a course to get to field first, leads to missbehavior with unloading course

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#1023]
Was about to post this in #1014, but now I think it should be an own issue.

I used to have one course to get to the working "field" as first, then the begin of working field marked with a waitingpoint, then driving the work course, marking the end of working course with a second waitingpoint and driving off the "field" to the next crossing point to the unload course where recording stops.
The second course is a course to the BGA (if greenfield is not right the neighborhood like at field 15), third is unloading at the BGA and fourth would be from BGA back to field.

@Developer:
When the trailer has unloaded and finished the combined course it drives to the first waypoint of all and not to the first waypoint where the field (first waitingpoint set) begins.
Is this intended? 
When recording my first courses I was assuming CP would drive to the waypoint where the field course begins (waitingpoint) before resuming the work and not to the very first waypoint of the course. 

Or another example where I'm not very happy with that behavior: When the driver has finished to pick the grass on a mowed greenfield I stop the driver, clear the course and give him a new combination:
1. from here, drive to next greenfield
2. working course
3. unloading course
4. back to greenfield course

When the driver has done his first unloading and returned to the field he wants to drive to the first waypoint of the first course, which only was to get him from the last field to this one...
Would operate way better, if CP would drive from unloading course directly to the begin of the field where the waitingpoint is set and from there on continue to it's saved waypoint to collect/work/seed more.

**Comment by JakobTischler** [comment]
> Is this intended? 

Yes. Why would we assume that part of the course that's loaded isn't supposed to be driven? If you want that part to be a one time thing, load it once, let it drive, then load the real field work and unloading course.

**Comment by AndyK70** [comment]
> Why would we assume that part of the course that's loaded isn't supposed to be driven?
Ok, if #917 will be established we can use the course to drive to next field at the end of work, but that's not a solution if a unloading course has to be driven. It's only for simple working courses like mowing, cultivating, etc.

Of course we have to drive once from one work to another and for that we have change to mode 5 and after that back to mode 4 or 6. 
All that steps wouldn't be necessary if CP would drive from end of all merged courses to first waitingpoint, where the work begins. And we could have a course to drive to field before the real working and unloading course begins.

**Comment by ThomasGaertner** [comment]
can you please confirm your intension? I understood:
you are recording a course from somewhere to the field, set a wait point e.g. waypoint 26 and a second one for ending the work e.g.  258.  then you record a second course to unload (173 waypoints)
so your complete course has 431  waypoints . your intension is to let it go till waypoint 431 and then skip to 26 to start work ? or do you want to go from 431 to 1 and then follow the route till 26 and start work ?

**Comment by AndyK70** [comment]
> your intention is to let it go till waypoint 431 and then skip to 26 to start work ?
This one, yes.

**Comment by ThomasGaertner** [comment]
can you tell me the reason for that ? you could record the course from this point beginning with a wait and record the second course till there stopping right before the wait point...

**Comment by AndyK70** [comment]
Example on Bjornholm:
1. Do work on a field i.E. pick up grass on field 40 with unloading course attached.
2. work is done, traktor is stopping with "finished work", needs attention.
3. stop cp, clean courses
4. select new courses:
  * load course to drive to field 15
  * append working course to pick up the grass, which has the two waitingpoints marking start and end of work.
  * append unloading course to BGA which ends in front of field 15

At the moment CP does drive the unloading course, at the end it drives to the first waypoint of all courses and that's the waypoint starting at field 40 (driving to field 15).
My intention is having cp to drive from the last point (end of unloading course) to beginning of work.
Or describing it in other words, having a transfer course prior just to drive to the actual courses doing the work.
If fields are near by like 36 and 37, it is no problem driving manually, but if paths get longer (especially 4x maps) it is very time consuming. And if you're into threshing/mowing/picking up multiple fields and managing various cp drivers at the same time it would be very handy to "*set and forget*" transfer and work courses for a driver.
Not to have to assign transfer course, switch mode, start cp and when it arrives, stop driver, switch mode again, clear course, set working course and evtl. unloading course.

It would save a lot of actions done manually.

**Comment by ThomasGaertner** [comment]
please test v0077 or higher and report...

**Comment by AndyK70** [comment]
v0078 with picking up straw works as intended. thank you.

have to test with grass and mode 4 fertilizer still. i think I can get it done tomorrow.
But I don't expect any anomalies.
