### ISSUE TITLE
Harvester will not start course.

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1029]
Version 070
map - coldbourough farm 2015

https://gist.github.com/sootysax/c16e413c5aa9db4dc054/download

harvester in mode 6 will not start up - hangs on the 'New Holland TC5.90 is starting up' but will not move on the course.

if I put it in 'transfer mode' with the header running and lowered, it will harvest at 16mph.  something is very off.

update:  it will sit indefinitely until you tab switch to another vehicle, then the harvester will start driving the course.

**Comment by Maxcdr** [comment]
Tested on my side (same map, harvester and mode 6, v.069 and 071): it works fine...

**Comment by ThomasGaertner** [comment]
hmm, same for me...

**Comment by sootysax** [comment]
ill reset some vehicles and retest then.
