### ISSUE TITLE
v0067 "is in traffic"... not really

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#1030]
As you can see on the screenshot, the course is on the street, but courseplay looks too early around the corner and sees traffic where in reality there is none.

![intrafficnotreally.jpg](http://www11.pic-upload.de/03.02.15/8wcc4y5uukfo.jpg)

**Comment by ThomasGaertner** [comment]
would you please post the course to gist and tell me the map ? i want to do some tests....

**Comment by AndyK70** [comment]
Map is standard Bjornholm.

the relevant courses are two attached ones.
The first is to that crossroads, the second is from there to field 40
copied these two in the gist.
[courseplay courses](https://gist.github.com/AndyK70/ec84413269fe07b7472f#file-courseplay-courses)

If you need more, please let me know.

**Comment by ThomasGaertner** [comment]
please try v0081 or higher and report...

**Comment by AndyK70** [comment]
Seems to work, no problems anymore, thank you
