### ISSUE TITLE
Courseplay Crashes Game

### ISSUE THREAD

**Issue by BEN32** [Courseplay/courseplay#1033]
When I load up my game It will work for about 30 seconds then it will crash.

Please Help

**Comment by Maxcdr** [comment]
Does it also crash like this when you remove Courseplay from your mod folder?
Also please be more specific: http://courseplay.github.io/courseplay/en/faq/index.html

**Comment by BEN32** [comment]
When I take it out the game works fine

**Comment by ThomasGaertner** [comment]
a log would be nice....

**Comment by BEN32** [comment]
OK I'll get that to you later today... I'm at school at the moment:-)

**Comment by BEN32** [comment]
Here is my game log.

**Comment by BEN32** [comment]
​
 log.txt
<https://docs.google.com/file/d/0B_LANsCqg3O1dlE2QngwbjZKTW8/edit?usp=drive_web>
​

**Comment by AndyK70** [comment]
I would suggest to remove all mods, that causes error in your log, then retry

**Comment by BEN32** [comment]
How do I know what causes error?

**Comment by AndyK70** [comment]
look at the errors:
 Error: Unsupported mod description version in mod **Aguas_Tenias_CCA46L**
 Error: Unsupported mod description version in mod **AmericanMap_T22**
 Error: Unsupported mod description version in mod **B_Haecksler_Krone_Beastpack_byBullgore1**
 Error: Invalid mod name 'CZMOD_VOLVO_L120H (1)'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
 Error: Failed to open xml file 'C:/Users/Benjamin/Documents/My Games/FarmingSimulator2015/mods//**FlieglBoss**/modDesc.xml'.
 Error: Missing descVersion attribute in mod **FlieglBoss**
 Error: Unsupported mod description version in mod **Krone_Big_X_1000_Pack_by_Ifko**
 Error: Not all prerequisites of specialization honk are fulfilled
  Register vehicle type: CanAM_1000XT.ATV
  Register vehicle type: CaseIHPuma200.Zoppo200
  Register vehicle type: ConveyorPack1.NewConveyor
  Register vehicle type: ConveyorPack1.FConveyor
  Register vehicle type: ConveyorPack1.TConveyor
  Register vehicle type: JohnDeere_9870sts_Harvester.CaseIHAxialFlow7130
 Warning: Not enough number meshes in 'C:/Users/Benjamin/Documents/My Games/FarmingSimulator2015/mods//**Bobcat_S160_v1/Bobcat_S160.xml**'
 ## Courseplay: **Bobcat S160**: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
 
all these mentioned mods causes errors or at least a warning like the Bobcat_S160_v1.
They are poorly build, or badly converted mods. Don't use those mods.

**Comment by BEN32** [comment]
Thank you so much for telling me, I will get them out.  After this it
should work?

**Comment by Satissis** [comment]
There is a high chance it will :)

**Comment by mereman** [comment]
Well it works very well for most of us users :)

Bad mods are a real pain and there are too many of them.

**Comment by BEN32** [comment]
it worked thank you so much!!!
