### ISSUE TITLE
Harvester and overloader in traffic at end of lane

### ISSUE THREAD

**Issue by Maxcdr** [Courseplay/courseplay#1037]
v.4.01.0071dev | Map Poebene15 | Standard vehicles

Overloader drives next to combine and when both arrives at the end of the lane, harvester gets in traffic with overloader.

Note: I'm running 2 harvesters with lane offset.

![fsscreen_2015_02_06_08_48_02](https://cloud.githubusercontent.com/assets/10348839/6076116/db11e84e-adde-11e4-9791-a31b2e6690c2.png)

**Comment by MPSBandit** [comment]
Maybe the same here.

CP 4.01.0067.dev
Two Rivers - Field 26
Two-Rivers Kroeger Trailer
standard vehicles

the screens are showing some issues turning of the driver after getting filled.


![fsscreen_2015_02_07_08_02_25](https://cloud.githubusercontent.com/assets/10454932/6091856/42f86050-aec0-11e4-8b34-b325e510e39e.png)
![fsscreen_2015_02_07_08_02_38](https://cloud.githubusercontent.com/assets/10454932/6091858/531d0968-aec0-11e4-8ff5-66342041e562.png)
![fsscreen_2015_02_07_08_03_14](https://cloud.githubusercontent.com/assets/10454932/6091860/5e9e4824-aec0-11e4-86e4-0c8bfb2862d6.png)

**Comment by ThomasGaertner** [comment]
I can not replicate one of your two cases, is it possible to make a video of it ?

**Comment by MPSBandit** [comment]
sure.  give me some time

**Comment by MPSBandit** [comment]
which perspective (driver / harvester) with wich information are useful to you?

**Comment by ThomasGaertner** [comment]
driver with HUD open please

**Comment by MPSBandit** [comment]
ok. Here it is. at the end you can see the settings of autocombine.
standard vehicles; Two Rivers - Field 19
https://dl.dropboxusercontent.com/u/41155700/ls15.mp4

sorry for the bad fps. it was running on my notebook

**Comment by Karlshoj** [comment]
I would use right turns for the combine???

**Comment by ThomasGaertner** [comment]
yea would be better, I think its something with bypassing. would you B able to test it again with the pipe outside the fruit ?

**Comment by MPSBandit** [comment]
sure. it will take some time

**Comment by Maxcdr** [comment]
Hopefully the issue I started is no mixed with the one from MPSBandit.
I tested on Westbridge Hills, field 11 and it works fine. So it seems to come from the map (Poebene15) but I wonder what...

**Comment by ThomasGaertner** [comment]
@Maxcdr: maybe the field borders are not set correctly 
@MPSBandit : can I count on some info in the near future ?

**Comment by MPSBandit** [comment]
Sorry, i should inform you about delay. a very busy week.
here are my different videos. i'm not sure if they really remain to the same issue...

https://dl.dropboxusercontent.com/u/41155700/LS15_Crash.mp4
https://dl.dropboxusercontent.com/u/41155700/LS15_Crash2.mp4
https://dl.dropboxusercontent.com/u/41155700/LS15_1-stuck-corner.mp4
https://dl.dropboxusercontent.com/u/41155700/LS15_close-to-collision.mp4

**Comment by ThomasGaertner** [comment]
yea it seems that the collision prevention finds something on the field,. you can see the white dots on the red lines, every dot is a hit, so we have to investigate that....

**Comment by MPSBandit** [comment]
is there a point where i can help you?

**Comment by ThomasGaertner** [comment]
test again with debug channel 3 active and post the log 
Thanks

**Comment by MPSBandit** [comment]
ok. no more videos needed? only let cp do its work and if there is a problem post the log?!

**Comment by ThomasGaertner** [comment]
affirmative, if there is the same problem as in the videos , post the log

**Comment by MPSBandit** [comment]
I think it might take a week again. at the moment i don't play very much. so give me some time....

**Comment by MPSBandit** [comment]
ok, i was faster than expected... i hope this works for you

https://dl.dropboxusercontent.com/u/41155700/log_crash-endoffield-tree.txt

**Comment by ThomasGaertner** [comment]
so, after a long time of thinking and testing it should work better now, I've also activated the bale recognition again. please test v0101 or higher and report.
Thanks

**Comment by jhomer** [comment]
K, I'll check out the bale recognition and get back....

**Comment by jhomer** [comment]
Checked the bale recognition and it does as follows...
Set it up so that the start of the field course was on the other side of the field from the start of the unload course (to make it drive through bales)
When the stacker gets full it DOES NOT seem to recognize the bales on the way to the unload course.
But when it comes back into the field it DOES drive around bales on its way to where it left off.
Now if the start of the unload course started by the start of the field course this would not be an issue, but just to fill you in on what it does do.

**Comment by MPSBandit** [comment]
actually i dont have much time. I ll try it if its possible and will give you some response. please be patient.

a question in general: at the first test with the new version (it seems to work better. i harvested 3 fields with not really an impact) i saw a different behaviour than before. the driver waited till the combine was gone away, took the same line like the combine and drove a little bit more straight (while the combine tooks a corner via autocombine). Does the driver recognize the boarders of the field (fieldscanning at the start of the game) or is this nothing the driver cares about?

**Comment by MPSBandit** [comment]
ok. it went faster in "trouble" than expected.

the same behaviour it had on the same place one line before (so it crashed into the woods). at the first line it acted like in MAN TGS turn ok and there was no problem.
New Holland CR10.90 (original)
MAN TGS18.440 (Mod), Krampe SB30 (Mod)
New Holland T8 (original), Kroeger HKD 302 (original), Kupplung für Magnum (Mod)

Two Rivers Field 18
https://dl.dropboxusercontent.com/u/41155700/LS15_T8.320.mp4
https://dl.dropboxusercontent.com/u/41155700/LS15_T8.320_log.txt

Two Rivers Field 19
crashed into woods
https://dl.dropboxusercontent.com/u/41155700/LS1_MAN_TGS18.440_turn-not-ok.log.mp4
https://dl.dropboxusercontent.com/u/41155700/LS1_MAN_TGS18.440_turn-not-ok.log.txt

worked fine
https://dl.dropboxusercontent.com/u/41155700/LS15_MAN_TGS18.440_Turn_ok.mp4
https://dl.dropboxusercontent.com/u/41155700/LS15_MAN_TGS18.440_Turn_ok_log

**Comment by ThomasGaertner** [comment]
is it still valid or can we close here ?

**Comment by MPSBandit** [comment]
not sure. should i test it with the ls17 and the new cp-version?

**Comment by tjb8907** [comment]
I have actually noticed this happening a few times, when the harvester is stopped waiting at the end, the unloader sometimes doesn't get the trailer under the pipe right. I may need to adjust settings slightly, but it does cause them both to get stuck. The harvester is waiting to unload and the unloader is being to told to stop by the harvester. Maybe approaching from straight behind the pipe farther back when the Harvester is stopped. Seems like it doesn't get straightened out from going from behind combine to next to combine.

**Comment by Blackmankot** [comment]
@ThomasGaertner Can this issue be closed? To cleanse the topic.

**Comment by pops64** [comment]
@tjb8907 you have a different known issues and it is on our todo list to fix before the release of CP. Otherwise close due to inactivity.
