### ISSUE TITLE
CP ignores Driver priority

### ISSUE THREAD

**Issue by MPSBandit** [Courseplay/courseplay#1039]
CP 4.01.0067.dev
Two Rivers - Field 26

I have some issues during harvesting. The harvester is controlled by AutoCombine 3.2.

i told the harvester to request the driver by filllevel. But it allways chooses the "Ursus" first. I use the default Ursus and Same (rent) with the Two-Rivers Kroeger Trailer. It doesn't matter if the harvester is selected automatically or manually.
I had the same issues with the MAN and NewHolland working with a NewHolland Harvester.

Issue or my mistake?

Let me know if i should provide more information to you.

![fsscreen_2015_02_07_08_46_50](https://cloud.githubusercontent.com/assets/10454932/6091854/1e20a738-aec0-11e4-96fb-3a86ee445aff.png)

**Comment by ThomasGaertner** [comment]
what about path finding , is it active or not ?

**Comment by MPSBandit** [comment]
It seems to be my bad. In both vehicles which function not proberly it was acitvated.  I'll test it right now!

**Comment by MPSBandit** [comment]
What a basic-mistake. Sorry for disturbing!
