### ISSUE TITLE
Falha no CoursePlay

### ISSUE THREAD

**Issue by erksartori** [Courseplay/courseplay#1042]
Hello people, I noticed a problem when I'm with the activated courseplay in any tractor, truck, etc ... that has a connected emplemento.

In the video I'm showing a truck that is waiting to be filled with corn, and discover what acantece the cart, starts to walk to the top of the truck, when I turn off courseplay, the walks advances forward.

http://youtu.be/W-9Rpi53stM

Detail that has occurred since 3 versions to behind the I am today.

I use all the original game equipment. courseplay V.4.01.0072

LOG:
GIANTS Engine Runtime 6.0.2 64bit (Build Date: Dec  9 2014)
Copyright (c) 2008-2014, GIANTS Software GmbH (giants-software.com), All Rights Reserved.
Copyright (c) 2003-2014, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: FarmingSimulator2015
Main System
  CPU: Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz
  Memory: 8155 MB
  OS: Windows NT 6.1 64-bit
Physics System
  Version: 5.9.4
  Thread(s): 2
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick enabled
  Force Feedback disabled
  Name: F430 Force Feedback
Sound System
  Driver: OpenAL
  Version: 1.1
  Device:  Generic Software
  Max. sources: 256
Render System
  Driver: OpenGL
  Card Vendor: NVIDIA Corporation
  Renderer: GeForce 8400GS/PCIe/SSE2
  Version: 3.3.0
  Shader Version: 3.30 NVIDIA via Cg compiler
    max_texture_layers: 16
    OpenGL initialization successful
Hardware Profile
  Level: Medium (forced)
  View Distance Factor: 1.000000
  Shadow Quality: 1.000000
  Skip Mipmaps: 1
  LOD Distance Factor: 1.000000
  Terrain LOD Distance Factor: 1.000000
  Foliage View Distance Factor: 1.000000
  Volume Mesh Tessellation Factor: 1.000000
  Tyre Tracks Segments Factor: 1.000000
Farming Simulator 15 INT
  Version: 1.2.0.0 1.2RC6
  Available Languages: en de fr es it pl cz hu nl ru jp pt cs ct br tr ro kr
  Language: br
Game vehicle types loaded
Mod directory: C:/Users/Eduardo/Documents/My Games/FarmingSimulator2015/mods/
Load mod: Geldcheat
Load mod: Gras_Halle
Error: Failed to open xml file 'C:/Users/Eduardo/Documents/My Games/FarmingSimulator2015/mods//Gras_Halle/modDesc.xml'.
Error: Missing descVersion attribute in mod Gras_Halle
Load mod: Inspector2
Load mod: MischStation
Load mod: placeable_fertilizerTank_LS15
Load mod: placeable_floodlight_LS15
Load mod: placeable_gasTank_LS15
Load mod: placeable_seedPallets_LS15
Load mod: zzz_courseplay
Error: Running LUA method 'update'.
D:/Code/Giants/lsim2015/build/finalbin/dataS/scripts/gui/MainScreen.lua(309) : bad argument #2 to 'format' (number expected, got string)

**Comment by ThomasGaertner** [comment]
please check the other issues before posting a new one  Thanks
#895
