### ISSUE TITLE
Driver stopping in crop when near field edge

### ISSUE THREAD

**Issue by Voidheartd** [Courseplay/courseplay#1043]
CP 4.01.0078.dev on Bjornholm with standard vehicles

I've noticed that the combi mode driver will choose a waiting point in the crop when near the field edge.  It consistently does this whenever there is only a small line of crop left.

This is more frustrating since now when the driver finishes unloading the combine before reaching the field edge, it doesn't stop where it is, but chooses a new spot (why?). This spot also often ends up being even closer to the wrong end of the field requiring a longer drive to get to the combine for the next unload.

![fsscreen_2015_02_08_23_32_21](https://cloud.githubusercontent.com/assets/3398909/6101267/275a0ac6-afef-11e4-9311-1b123920a31a.png)

**Comment by ThomasGaertner** [comment]
how did the combine drive ? via helper or courseplay or auto combine ? can you replicate it  with debug channel 4 active and post the log and a screenshot of the situation from the log ? Thanks

**Comment by Voidheartd** [comment]
via helper, I will get the log this weekend

**Comment by Voidheartd** [comment]
I can confirm the fix. I forced this situation several times and the tractor did not stop in the crop.
