### ISSUE TITLE
Combine stopping at beginning of row to wait for tractor

### ISSUE THREAD

**Issue by Voidheartd** [Courseplay/courseplay#1044]
CP 4.01.0078.dev on Bjornholm with standard vehicles, combine in hired worker

I've been noticing that sometimes the combine stops before going into a row or just into the crop, when the combi mode driver is coming to unload it. It waits until the tractor is near before it starts back to harvesting. This is without the combine being even close to full.

This behavior is similar to how the combine waits at the end of a row when unloading occurred there (did not finish unload in the middle of the row), until the combi mode driver gets to his wait point.

This is very clear in the below imagine where the combi mode driver has gotten stuck. The combine simply sits forever waiting for the tractor, when it has no reason to do so. As soon as I stopped the combi mode driver, the combine resumed. 
![fsscreen_2015_02_09_03_16_32](https://cloud.githubusercontent.com/assets/3398909/6102848/d6164a14-b00a-11e4-9a6e-1183ceabd9de.png)

**Comment by ThomasGaertner** [comment]
can you confirm , that the combine turned , when the tractor was on the way to the combine and after the turn it stopped  ?

**Comment by Voidheartd** [comment]
I will work to confirm this but I believe this is the way it goes:

Combine is harvesting and reaches the unload threshold while the pipe is over crop.
Tractor starts waiting for combine to reach end of row.
Combine reaches end of row and begins turning.
Tractor starts driving to combine.
Combine completes turn and either stops before hitting the crop at all, or stops not long after beginning the new row as in the screenshots.
Tractor moves into unload position.
Combine begins harvesting again.

**Comment by ThomasGaertner** [comment]
please test v0085 or higher and report...

**Comment by Voidheartd** [comment]
This appears to have resolved the issue. I think this also helped with the tractor driving out into obstacles as mentioned in #1045, since the combine is now further into the row when the tractor gets to it.
