### ISSUE TITLE
Combi mode driver goes too far behind combine

### ISSUE THREAD

**Issue by Voidheartd** [Courseplay/courseplay#1045]
CP 4.01.0078.dev on Bjornholm with standard vehicles, combine in hired worker

I remember this being an issue a long time ago in fs13 and it appears to be still here or back. The combi mode driver is going much too far before turning around to drive besides the combine.  I can understand that it needs a good distance to prevent traffic issues but it's hitting things which are a bit far from the field. The turn radius was set to 10 manually (auto is 6) because the driver sometimes would go in circles several times when trying to get to a wait point and I was seeing if that helped.

The combine normally would already be into the field before the tractor got to it so part of this is because the combine was waiting for some reason which I've posted in #1044. This would still be an issue with the big x though since it does have to wait.

 I didn't think to grab a shot from the tractor's perspective but here is from the combine.

![fsscreen_2015_02_09_03_16_32](https://cloud.githubusercontent.com/assets/3398909/6102848/d6164a14-b00a-11e4-9a6e-1183ceabd9de.png)

I took this shot to show how far the yellow house it got stuck on is from the field.

![fsscreen_2015_02_09_03_36_14](https://cloud.githubusercontent.com/assets/3398909/6103059/a4501afc-b00d-11e4-975a-bd88c6d98dce.png)

Also, here is an overhead view with the combine positioned where it would be starting a row to show how much free space there is.

![fsscreen_2015_02_09_03_45_15](https://cloud.githubusercontent.com/assets/3398909/6103130/6eed53d8-b00e-11e4-90a0-beeede3e4b9e.png)

**Comment by ThomasGaertner** [comment]
the formula to calculate the way behind the combine is -(turnDiameter + safetyDistance) where safetyDistance for combines 10 . if you increase the turn diameter manually, you also increase the distance behind the combine.

**Comment by ThomasGaertner** [comment]
at the moment we don't want to change something in the approach but I included a timeout . if the approach takes too long , the combine will turn and resume working . the tractor will be stopped for this time .... please test v0080 or higher and report

**Comment by Voidheartd** [comment]
I think this issue is completely avoided now (for combines at least) with the change made for #1044, since the tractor won't try to go to the combine until the combine is already working on the new row.

It will probably still be an issue with the big x though because of how it works. Trying to use anything with a large turning circle on combi mode with the big x will not go well I think. I know it was an issue in 2013 but I haven't tried it in 2015 yet.

**Comment by ThomasGaertner** [comment]
this manoeuvre has nothing to do with the bigX . I will close here, if you have an issue with the chopper, please make a new issue to prevent mixing issues...
