### ISSUE TITLE
No waiting time setting in mode 4

### ISSUE THREAD

**Issue by maddavo** [Courseplay/courseplay#1048]
(v.0078) There is a waiting time setting in modes 1, 2, 5, 6, 8 .  It is not in mode 4.  Is this by design?  I need it in mode 4.

**Comment by gui7545** [comment]
No, it is not possible, waiting point are used to create the work-area.
http://courseplay.github.io/courseplay/en/manual/index.html#driveMode4

**Comment by maddavo** [comment]
Ah.  Can't have an override setting 0sec/1sec/etc.?

**Comment by Satissis** [comment]
nop it's not possible, since the wait points are used for other things in mode 4 and 6.
Can't remember what it was in mode 4 but mode 6, then 3. wait point is used for autostackers to know where it needs to unload on the unloading route.

**Comment by Karlshoj** [comment]
I guess that in mode 4 it´s where to load the manure spreder

**Comment by maddavo** [comment]
OK, tks.
