### ISSUE TITLE
Mode 4/6 miss start of lane with lane offset & symmetric lane change

### ISSUE THREAD

**Issue by maddavo** [Courseplay/courseplay#1049]
(v0078) When in mode 4/6, using lane offset and symmetric lane change, when performing a turn, tractor does turn and lines up to start new lane at lane start rather than (lane start+offset).  Offset seems to get applied after starting lane so there is a little zig-zag as it gets going (bigger with bigger offset).  This leaves a bit of field unworked at the start of lanes.  I think the turn needs to aim at (lane start+offset).

**Comment by gui7545** [comment]
What is your tool's width ? What is your lane offset ?

**Comment by maddavo** [comment]
6m tool, 3m left/right offset

**Comment by Satissis** [comment]
I'm working on a new turn maneuver system for mode 4 and 6 and this is fixed in that.
So just wait until it's done and your problem should be gone.

**Comment by maddavo** [comment]
Cool, tks.

**Comment by ThomasGaertner** [comment]
I will close here to keep the issues area clean....
