### ISSUE TITLE
question: what type of turns are you working on?

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#1050]
as already mentioned in #950 and now again in #1049 you are working on new turn calculations.

If turn width is less or equal width between lines I assume it won't change as of now.
But if turn width is greater than width between line it's going to be interesting.

What type of turns, T turns, or bubble turns?
![Turntypes](http://www11.pic-upload.de/10.02.15/dljm3fujmkk.png)

Both have pros and cons.
T-turns don't need much space before and after the line, but to the side, especially when on the first and last lane.
Bubble-turns don't need much lateral space, but lot more longitudinal.

Or will you implement bot and decide whether there is enough space (no obstacles) for one method or the other, or will there be an option selectable by user?

just curious... a lot :grinning:

**Comment by ThomasGaertner** [comment]
surprise ....

**Comment by Satissis** [comment]
as Thomas said..... surprice :P
Will say one thing thou. There will be more than 1 turn maneuver.

**Comment by ThomasGaertner** [comment]
I will close here to keep the issues area clean....
