### ISSUE TITLE
krone forager

### ISSUE THREAD

**Issue by FS-UK-TheMan1988** [Courseplay/courseplay#1052]
when i do silage the with the krone forager. cp only wants to drive on the left side of the forager. no matter what. left, right, auto. same

**Comment by ThomasGaertner** [comment]
would you please describe a little more detailed maybe with a screenshot ?

**Comment by ThomasGaertner** [comment]
@FS-UK-TheMan1988 : any news?

**Comment by ThomasGaertner** [comment]
closed due to inactivity
