### ISSUE TITLE
Panien_PW_18_10E_FraBel_Ls_Modding_FS15

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#1053]
Panien_PW_18_10E_FraBel_Ls_Modding_FS15 invites not on fertilizers trigger! Hope you can make it! Thank you for your great work and your great support! I play Mig Map made in Celle! Tractor MP 1600 Forbidden mods and placeable fertilizer Tank MOD HUB!

**Comment by Satissis** [comment]
https://github.com/Courseplay/courseplay/wiki
