### ISSUE TITLE
Combine Self Unloading - Cruise Control Problem

### ISSUE THREAD

**Issue by lavenki** [Courseplay/courseplay#1054]
After the combine finishes the unload on a trailer and goes back to the previous spot where the Helper Mode last thrashed, the cruise control speed goes down to 3kph. Is there any possibility of increasing / fixing it?

Note: When i start the helper mode, the speed is the default relative to the specific combine, yet all combines i use, vanilla or modded goes down to 3kph after the unload even though their default thrashing speed isn't 3kph.

**Comment by ThomasGaertner** [comment]
hmm could not replicate it . is it possible to make a screenshot of the situation with HUD open on the speed settings page and debug channel 21 active ? Thanks

**Comment by lavenki** [comment]
Here you go~

Here's my Big X unloading chaff into a waiting trailer:
![fsscreen_2015_02_18_03_05_37](https://cloud.githubusercontent.com/assets/8536809/6235224/dd476800-b71b-11e4-8cca-328861e726b2.png)
Note that its Cruise Control speed is 15kph because i set the unloading BGA to 15kph (trying to fix the speed problem)

Here it is going back to where it last threshed:
![fsscreen_2015_02_18_03_07_19](https://cloud.githubusercontent.com/assets/8536809/6235272/32ef132a-b71c-11e4-884c-909eee831bc5.png)
Field Speed set to 30kph (again trying to fix the problem)

Hired worker mode starts and note the speed dropped to 6kph:
![fsscreen_2015_02_18_03_08_35](https://cloud.githubusercontent.com/assets/8536809/6235304/82763cd4-b71c-11e4-9800-074a4d85e175.png)
(sometimes 3kph, 9kph and 15kph if im lucky)

Now, here it is after i stopped CP, stopped the previous worker & manually set the Cruise Speed to max and turned everything on again:
![fsscreen_2015_02_18_03_09_02](https://cloud.githubusercontent.com/assets/8536809/6235336/bacfc1ea-b71c-11e4-83f4-682a74902758.png)
The combine threshes at its normal pace of 18kph.

Side Note: Also, that CP icon for the Combine never disappears even after i put it back into the Garage. CP is off and its still there. And if i hire a worker, turn off CP, and let that worker finish, the Combine remains on and can't be turned off, i used Drive Control's engine off feature and it doesn't work. I need to restart my game in order for the combine to not run out of fuel.

Thanks for the reply!

**Comment by ThomasGaertner** [comment]
could you give me the link to this mod ? Thanks

**Comment by lavenki** [comment]
Uhh, i don't know how to post the log and what's a gist? Lol. Sorry, im very new to FS. 

But here's the link though, this may not be the exact site i got it from but its the same one.

http://www.ls15mod.com/farming-simulator-15-mods/krone-big-x-1100-green-pack-dynamic-twin-front-wheels/

Also, that problem also occurs with Vanilla Combines, not exactly with that specific modded Big X. Been having that problem ever since i learned how to use that combine feature.

Thanks!

**Comment by Raints** [comment]
Actually there is so many changes in dev version. If i look in your pictures i can see your version v4.01.0000. Maybe you should download latest dev version and see if your problem still exists.

**Comment by ThomasGaertner** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by ThomasGaertner** [comment]
@lavenki :  I've fixed it. if you want to take part, please update to developer version 0086 or higher, test again and report.

**Comment by lavenki** [comment]
Okay, here be my log:

https://gist.github.com/34cfb011d82acb6879b5.git

And the dev version is the courseplay-master in the homepage right? And i just need to download the zip right?

I'll be testing it now.

Thanks guys!

**Comment by AndyK70** [comment]
* download the zip
* extract it to desktop or another temporary location. It will extract a folder **courseplay-master**
* everything inside that folder compress to a zip file named ZZZ_courseplay
* move that new zip to your mod folder of FS15
* you can now delete the folder courseplay-master on your desktop and the old zip courseplay-master

**Comment by lavenki** [comment]
So that's why it ain't working. Thanks!

**Comment by ThomasGaertner** [comment]
@lavenki : is it ok now ?

**Comment by ThomasGaertner** [comment]
closed due to inactivity

**Comment by lavenki** [comment]
After a week of testing, no more bugs of any sort. Thanks!
