### ISSUE TITLE
driver collides with combine while approach from front

### ISSUE THREAD

**Issue by Brzzl** [Courseplay/courseplay#1055]
Hi, 
habe mit einem Mod-Traktor bzw Stock-Traktoren folgende Problematik:
Wie im Screenshot zu erkennen, hält der Abfahrer vor dem Häcksler und bekommt das Signal zum anhalten. Dies passiert sowohl mit Mods als auch mit Stock-Traktoren.
Ebenfalls lässt sich das Problem beim Stock-Überladewagen und einem beliebigen Drescher reproduzieren.
Ausgangssituation ist immer(!) Anfahrt von vorn. Der Traktor hält auf den Drescher/Häcksler zu und sobald er in seiner Nähe ist, schlägt er ein und stellt sich vor das Fahrzeug.
Meines Erachtens wird die Länge des Dreschers/Häckslers bzw Front/Heck nicht erkannt und es kommt zu dem beschriebenen Problem.

![fsscreen_2015_02_14_23_43_32](https://cloud.githubusercontent.com/assets/3459971/6201348/212c337c-b4a4-11e4-90b2-e26ffc99a060.png)

**Comment by Satissis** [comment]
Ja ja og jeg forstår meget lidt Tysk
(Translated to English)
Yeah yeah and I understand very little German.

Now could you please post it in English and follow the wiki on how to provide a nice bug report.
Linky: https://github.com/Courseplay/courseplay/wiki

**Comment by ThomasGaertner** [comment]
I think I know what's the problem, but in respect to our non german speaking developers and users we ask you , as Satissis said, to post in English. btw , can you confirm that you are using two drivers to unload the chopper ?

**Comment by Brzzl** [comment]
@Satissis  
Oh, I'm sorry! So here in english now:
as u can see in the screenshot the driver is stopping in front of the combine and stops. this happens with both stock and mod tractors.
starting situation is always(!) approaching from the front. if the driver gets next to the chopper, it turns its wheels and stops because of the collision-message.
IMO the driver doesn't detect the front/rear or the length of the combine/combine.

This situation is reproducable with an overloader trailer and a random combine. if the driver starts and heads towards the combine, it stops at the cutting unit.

@ThomasGaertner 
I can confirm that I'm working here with two or more drivers.
Workaround so far is that i set the starting percentage down to 45 - 50 % so that a 2nd driver is following the active driver and heads to the chopper from behind.

**Comment by ThomasGaertner** [comment]
please test v0082 or higher and report...

**Comment by Brzzl** [comment]
Hi again, 
problem seems solved. 
tested 2 fields with 3 drivers and got no collisions.
