### ISSUE TITLE
Suggestion: When re-generating fieldwork, keep field edge path

### ISSUE THREAD

**Issue by lansalot** [Courseplay/courseplay#1056]
Sometimes, on maps like Coldborough or Knuston, it's hard to work out what CP will decide is the NE/NW/SE/SW corner etc (it's not as simple as it looks), so I'll frequently generate a fieldwork map, realise it's probably not optimal, so change the corners and direction and generate again, till I get one I like the look of.

But when I hit the X to discard the generated course, the currently loaded field edge path is also discarded. Which can be a pain if you're regenerating field 27 etc over and over again, as you have to click up all the way up to that path before going through the whole process again.

As a suggestion, how about an X on the fieldwork tab doesn't reset the Field Edge Path, just erases the loaded course?

**Comment by sootysax** [comment]
or perhaps a default to selecting the edge of the field that the vehicle is sitting in..

**Comment by OldFisher** [comment]
Sometimes you just have to have several attempts at course generation, so keeping edge path is needed even with corner/direction autoselect (which would be a good thing too).
The tricky thing is when you generate from loaded course, not edge path. The system would have to remember what course was loaded before the route is generated and fall back to it if you don't like what was generated.

**Comment by Satissis** [comment]
#1346
