### ISSUE TITLE
Error: Running LUA method 'update'. drive.lua:746: Commit .0081.dev

### ISSUE THREAD

**Issue by yopys** [Courseplay/courseplay#1057]
Hi there. I get a "drive.lua:746: attempt to index a nil value" and the end of every course since Commit .0081.dev.

**Comment by eddiem54** [comment]
I am getting the same multiple times and game crash using standard Westbridge map, no mods.4.01.0083 and in previous few versions. [Log]
(https://gist.github.com/anonymous/652d83ebb9ee5b134658)
