### ISSUE TITLE
Suggestion:  Save courses per map

### ISSUE THREAD

**Issue by Jameshook** [Courseplay/courseplay#1058]
When I switch maps,  I notice that the course I saved on one map are deleted when I play on another map.  This happened when I was expoloring a new map to see if I wanted to play it.  Is there a way index the saved courses to say the savegame of the map?

**Comment by AndyK70** [comment]
courses are saved in the savegame folder in the courseplay.xml
just copy it over to your new savegame folder and you are set.

**Comment by ThomasGaertner** [comment]
yea I think that will be the solution for your issue...
