### ISSUE TITLE
Return of #52? Combine waiting for tractor to stop moving after unloading at field edge

### ISSUE THREAD

**Issue by Voidheartd** [Courseplay/courseplay#1059]
CP 4.01.0085.dev on Bjornholm with standard vehicles (rosenlew and agrostar 6.61)

Is there some reason this problem that was fixed in #52 has returned? If it was a necessary change that is fine, I am just curious why it's back.

As before, when a combi mode tractor finishes unloading a hired worker combine and the combine is already at the field edge, the combine continues to sit until the tractor has moved back onto the field and stopped at its chosen waypoint.

**Comment by ThomasGaertner** [comment]
it's not a bug, it's a feature :-) 
It came out, that some people are using very large trucks and tractors with a lot of trailers. So the only solution to prevent crashes in this situation is to let the combine wait, till the tractor is in a save position.
It looked better and smoother with the "old" version, but we have to take care of all possible situations and that's the price we have to pay for that.

**Comment by Voidheartd** [comment]
Is it possible to override the waiting? As in an edit I could make after downloading.

**Comment by ThomasGaertner** [comment]
sorry , no its not possible, we will discuss this issue and decide, what to do. maybe we will find a solution  for both cases. I will close here but not forget.
