### ISSUE TITLE
ZZZ_courseplay/mode4.lua(136) : attempt to call method 'setAIImplementsMoveDown' (a nil value)

### ISSUE THREAD

**Issue by dphinton2003** [Courseplay/courseplay#1060]
Hi, I've been trying to use a John Deere Self propelled dry box spreader with courseplay developer version for FS 13.  Here are the specializations, from what it seems it uses ingame scripts.
<vehicleTypes>
        <type name="JohnDeere4920" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
			<specialization name="motorized" />
            <specialization name="steerable" />
			 <specialization name="honk" />
			
			<specialization name="animatedVehicle" />
			<specialization name="fillable" />
			<specialization name="sprayer" />
		    <specialization name="drivingParticleSystem" />
			<specialization name="hirable" />
			<specialization name="aiTractor" />
        </type>
    </vehicleTypes>

When I try to start the driver in courseplay, the machine gets to the start point and just drives straight very slowly.  I get a call Stack with this error.
Error: LUA running function 'update'
C:/Users/...../mods/ZZZ_courseplay/mode4.lua(136) : attempt to call method 'setAIImplementsMoveDown' (a nil value)

Any help would be appreciated.

**Comment by ThomasGaertner** [comment]
I hove , you mean developer version for FS15... 
anyway, if the mod doesn't have this function , it will not work ...
if you need a confirmation , tell us the link to the mod and your CP version.
if you understood, please close this issue
Thanks

**Comment by ThomasGaertner** [comment]
closed due to inactivity
