### ISSUE TITLE
[Question] CP availability for Dedicated-Server

### ISSUE THREAD

**Issue by hurr1k4ne** [Courseplay/courseplay#1061]
First of all: I read a lot about CP-Multiplayer here and on Modhoster.
**I understand Multiplayer in general is deactivated** because of major issues and your decision to give it a rewrite.
I read a lot of info found here in issues and others. And think i've read that between MP and MP-on-DS is a difference because of Giants "poor" implementation of DS. (no path to mods directory on DS, and similar)

My question: After you have released a stable CP-FS15 release and did a rewrite for multiplayer functionality. Is it likely that MP-on-DS is supported or will it need extra time to get it going?

I'm very interested in breaking my thoughts and do debugging and "light programming" on software i'm interested in.
I already worked on TrinityCore (MMO-Server framework)(C++) and an Battlefield2 Web statistics System (pyton, C#, php). 
I'm desperate to help you guys where i can.

**Comment by djz3r0** [comment]
would be really nice to know when and if cp is comming out for deidcated servers

**Comment by hurr1k4ne** [comment]
hehe, i think you know the courseplay guys don't like to tell dates when anything will be ready.

I have read that they deactivated multiplayer functionality because of gamebraking errors in multiplayer. 
They focus on getting the "features" to work and release a full and stable release.
After that they have planned to completely rewrite multiplayer code.
Maybe they keep their eyes open to get even dedicated Server to work. I'm ready to support them when it comes to multiplayer and dedicated server.

Personally i think you won't get a "multiplayer will be released on 25. April " from them ;-)

*written with no official background or official information"

**Comment by Satissis** [comment]
MP will be available for DS.
We have already tested it and it seams to work fine, but we still have some issue that needs to be fixed.
@djz3r0 as @hurr1k4ne said, then don't give any estimated time on releases.
