### ISSUE TITLE
Silage to trailer

### ISSUE THREAD

**Issue by Tnarg100** [Courseplay/courseplay#1062]
Not sure if it is an issue or just me not setting correct. I have recorded a silage silo run to load a trailer, it does the first lot of runs and fills the trailer perfect, now my problem starts, which category do i use for the tractor that is deliverying? Do I need to put a wait point at the position of loading for the tractor?
Sorry if this is not for here but I can't find a tutorial for this?
Kind regards
Grant

**Comment by AndyK70** [comment]
use mode 1, grain transport.

i use it this way to load wood chips at the farm into the trailer (mode 9, silage run) and then transport it to the biomass heating plant.
The truck is in mode 1, starting point is where it is loaded with wood chips, then a round course to BHP, back to farm and stops a few meters before starting point.

**Comment by ThomasGaertner** [comment]
@Tnarg100 : did you try mode1 ?

**Comment by ThomasGaertner** [comment]
closed due to inactivity
