### ISSUE TITLE
Backing up Euroboss 330T

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1063]
I've tried recording a few different courses..    I'm trying to back up a EuroBoss 330T into a grass storage shed..   it doesn't seem to be steering the back of the trailer like it usually does when backing up a trailer..   it's a pretty straight drive back...  but the back of the trailer winds up veering off to the left...

I've tried recording with and without the trailer.

not sure if you want a video, pictures, log?

**Comment by AndyK70** [comment]
did you read #990 ?

**Comment by sootysax** [comment]
the euroboss is not a pivot trailer, nor am i working in transfer mode.. i am fieldwork mode on the unload portion of my course... so this doesnt really apply.

**Comment by AndyK70** [comment]
My comment for you was not ment about pivot trailer and not about the driving mode.
It's about of having enough straight line when beginning to haul the trailer straight and enough straight line to include hauler and trailer before reversing.

**Comment by sootysax** [comment]
I did record a straight backup from the reverse point..  as much as any other time Ive recorded a reverse trailer route..  and usually the back of the trailer is steered..  however this time the back of the tractor is being steered and not the back of the trailer

**Comment by Satissis** [comment]
Turn on debug channel 13, start the course, then stop again and post the log.

**Comment by Satissis** [comment]
Closed due to inactivity

**Comment by Hubcap-1** [comment]
Important suggestion in finding a solution to backing up. I think the programming of this mod lacks a serious portion of consideration. There is an important " geometry" consideration when backing any vehicle. This is known technically as a " Bridge rule". The " Bridge" is the distance from the attacher pivot point to the center of the rear axle ( Or the middle point between a dual or triple rear axle). This measurement is key to figuring out the input required from the " control vehicle" ,( the tractor) , for a successful reverse maneuver. I believe the formula incorporated at this time is only worked out ( oversimplified) for short wheel base rear attachments like the Horsch pronto or something similar
