### ISSUE TITLE
Waiting for new waypoint

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1065]
So this is happening when the combine is driving along while being unloaded and approaching the end of the row. There is not enough space for the trailer to pull behind the combine into the waiting point so this happens at the end of the row 

Driver unloads combine, pulls away and flashes 'waiting for new waypoint'.  Both combine and tractor sit and wait for each other to move.

![fsscreen_2015_02_22_17_13_02](https://cloud.githubusercontent.com/assets/6591048/6320813/88145fe8-bab6-11e4-9563-6ca18ff38ba5.png)
![fsscreen_2015_02_22_17_12_40](https://cloud.githubusercontent.com/assets/6591048/6320812/8812379a-bab6-11e4-8bcb-99a3ec8668f2.png)

**Comment by ThomasGaertner** [comment]
It looks like the tractor did not get more than one waypoint. can you confirm, that it just turned away and stopped ?
I couldn't get it , but I added some debugs. please try again with debug channel 4 active and if you got this fault again, please post the log. 
Thanks

**Comment by sootysax** [comment]
v087 so far, the tractor is proceeding to  the expected waiting waypoint..  and combine is continuing as normal

**Comment by ThomasGaertner** [comment]
I think its a random thing , I've heard it from other guys but nobody could replicate it ...
