### ISSUE TITLE
MigMap Soil Mod

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#1066]
Hi! Had a question about Mig Map made in Celle SoilMod! One question is the same problem the Course Play the Fertilizertrigger not recognize! 2. Whether it is possible as in the downhill, the man can aswählen in Meue the trigger man what the device wants (eg fertilizer sprayer) deploy! Because there are several possibilities when SoilMod are available!

**Comment by ThomasGaertner** [comment]
why do you close your issues all the time ?

**Comment by Paul2510** [comment]
Two questions have done it! The front loader was a mistake from the game 
itself! after reboot everything was great! And Pantera is also a mistake 
by Mod! In Mig Map I was not sure if I wrote it right to me! As I use 
google translator!

Am 24.02.2015 um 22:12 schrieb Thomas Gärtner:
> why do you close your issues all the time ?
