### ISSUE TITLE
Tracors sliding and missing start point

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#1069]
Wether this is down to the physics of the game or not i dont know, but ill have a tractor with a full trailer heading out of the field toward the course start but when it reaches it it cant turn because of the speed and just slides by. It then will circle round looking for the start waypoint. The same happens when a tractor approaches a combine to unload, more often than not it will slide straight into combine.I could slow the field speed down but thats not reslly the point. 
Is there anyway to counter the sliding?

**Comment by ThomasGaertner** [comment]
what is your setting for field speed ?

**Comment by kwguk** [comment]
My field speed is set to 50 kph as im using Losshugelland which has big fields. It was never a problem in FS13 the sliding.

**Comment by hurr1k4ne** [comment]
The problem was existing also in FS13. 
Unless the code is adjusted (like approach speed or sth) you might have to change the course or slow down ´.

**Comment by kwguk** [comment]
yeah i think youre right ill reduce the field speed.

**Comment by kwguk** [comment]
I've found that the sliding thing is worse when tractors are approaching the combine. A lot of times, even at low speed, to low to be practical, the tractor gets within striking distance of combine but cannot align itself to unload as its either slid into the header or combine which prompts the collision alert. 
Is there a way of extending the distance the tractor picks the combine up so it has more time to get on the correct unloading track?

**Comment by ThomasGaertner** [comment]
is it possible to make a video of the situation? is it still with 50kph ?

**Comment by kwguk** [comment]
My PC is away being upgraded at the mo, should be back midweek.

But I slowed the field speed down to 40kph and the tractor still slides as it brakes to try and acquire the combine unloading track.

I've never made a vid before but I'll give it ago!

**Comment by ThomasGaertner** [comment]
since we have no influence of the physics engine , we can only ask you to lower the speed till it works properly, btw in reality I wouldn't go on the field with > 40kph fully loaded. Its dangerous :-) 
I will close here, because I don't see a way to help you with changes in our script.

**Comment by kwguk** [comment]
In 'reality' Thomas I quite happily go at 50kph with a loaded trailer in the field as long as the field is suitable. 
I drive the combine and the golden rule we have is do not keep the combine waiting. 

But here hoping Giants release a patch to,sort the sliding out.

**Comment by ThomasGaertner** [comment]
Yea, but suitable means for Giants 20kph . It's like driving on ice on these fields 😀
