### ISSUE TITLE
Trailer not unloading at conveyor

### ISSUE THREAD

**Issue by CaptainRush** [Courseplay/courseplay#1070]
I set up a course with a silage trailer that leads to a conveyor to fill up the BGA. It passes by, the "unload" option appears but it will not stop and unload. I can unload the trailer manually, but courseplay doesnt...
working a lot with CP and i got every duty going fine but this has giving me nightmares...any idea? 
thank you

**Comment by ThomasGaertner** [comment]
maybe the tip trigger is not supported, which one is it ?

**Comment by CaptainRush** [comment]
i tried the following:
http://www.modhoster.com/mods/forder-band
http://www.modhoster.com/mods/forderband-pack--3

standard trailers...tried 3 different...none of them works.

i can always unload manually !

**Comment by ThomasGaertner** [comment]
two things: 
1.) the trigger is very small and there is a good chance to miss it with the raycast while passing it
2.)  we use a table called "acceptedFillTypes" to verify the trigger to be valid. In your case this table is empty. So you will have to ask the developer of this mod to implement this table in the trigger as it is done in all standard triggers. 
If this table is available and you hit the trigger with the raycast, it will work properly ....

**Comment by CaptainRush** [comment]
thanks for the info!

**Comment by ThomasGaertner** [comment]
not that simple, because the conveyor thinks, it is a shovel. sorry
