### ISSUE TITLE
Combine 80% full warning

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#1071]
When youre using a hired worker on a combine the beacons will come on when the tank level reaches 80%. When youre using a combine in CP the beacons dont come on.

Is there a way of making the beacons come on at 80% when using a CP combine?

**Comment by ThomasGaertner** [comment]
if you set it to "on street" or "allways" it should work....

**Comment by kwguk** [comment]
thanks ill give it ago

**Comment by kwguk** [comment]
Nope it doesnt. .'on street' doesnt work and 'all ways on', well theyre always on regardless of the tank level. Something in CP must be stopping them work at80% fill level

**Comment by ThomasGaertner** [comment]
yep there was a little bug , works now....

**Comment by kwguk** [comment]
how do i fix the bug Thomas?.

**Comment by ThomasGaertner** [comment]
download v0089...

**Comment by kwguk** [comment]
apologies for sounding like a dumb ass, but where do i download v0089 from?

The download fron fs-uk ive got is <version>4.01.0000</version>

**Comment by ThomasGaertner** [comment]
AndyK70  commented 6 days ago  : 
•download the zip  https://codeload.github.com/Courseplay/courseplay/zip/master
•extract it to desktop or another temporary location. It will extract a folder courseplay-master 
•everything inside that folder compress to a zip file named ZZZ_courseplay
•move that new zip to your mod folder of FS15
•you can now delete the folder courseplay-master on your desktop and the old zip courseplay-master

**Comment by kwguk** [comment]
Sorted now

thanks very much

keep up the good work, i love this mod, it makes FS more enjoyable!
