### ISSUE TITLE
Vehicles do not recognize tippers as traffic

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1072]
So I'm noticing that vechiles will only recognize other vehicles as traffic, but not tippers (not sure about other equipment or tools).

If I have multiple tractors and tippers lining up at a silo loadout, they will just ram into the back of the other tippers and spin its wheels until the other one pulls out of the way instead of waiting 'in traffic'.

**Comment by ThomasGaertner** [comment]
could you please describe the situation ( mode, tools ....) maybe with a screenshot ? I tested it in mode 5,2, and 1 on the street and it worked fine....

**Comment by sootysax** [comment]
It was in mode 1, getting either loaded at the silo, or waiting to unload at the sell point..   Fortis 190's pulling Bandit 750's.   I can screen cap the next time the situation comes up in my game..  but I have also had this happen while at a loading point getting filled by a front loader..

**Comment by ThomasGaertner** [comment]
and maybe debug channel 3 active thanks

**Comment by valdimellen** [comment]
i have the same problems. 

log Debug 3
[dbg3 lp422932] Deutz AgroStar 6.61 (#2):onEnter Trigger1: triggered collision with 82295 
[dbg3 lp422932] Deutz AgroStar 6.61 (#2): 	onEnter: 82295 is in other trigger -> ignore
[dbg3 lp422932] Deutz AgroStar 6.61 (#2):onEnter Trigger3: triggered collision with 82295 
[dbg3 lp422932] Deutz AgroStar 6.61 (#2): 	onEnter: 82295 is in other trigger -> ignore
[dbg3 lp422952] Deutz AgroStar 6.61 (#2):onEnter Trigger2: triggered collision with 82295 
[dbg3 lp422952] Deutz AgroStar 6.61 (#2): 	onEnter: 82295 is in other trigger -> ignore
[dbg3 lp422952] Deutz AgroStar 6.61 (#2):onEnter Trigger4: triggered collision with 82295 
[dbg3 lp422952] Deutz AgroStar 6.61 (#2): 	onEnter: 82295 is in other trigger -> ignore

**Comment by ThomasGaertner** [comment]
@valdimellen : would you please post the whole log ? Thanks

**Comment by valdimellen** [comment]
Sorry. I don't have the whole log anymore.. But i will make a new one.

**Comment by valdimellen** [comment]
log: https://www.dropbox.com/s/loi6dzyyqdikiq5/log.txt?dl=0
![skaermbillede 2015-02-28 kl 21 15 45](https://cloud.githubusercontent.com/assets/11229601/6427923/7088784a-bf8f-11e4-9cc7-71cb8d3b00d0.png)

**Comment by ThomasGaertner** [comment]
after some hours of trying and failing I'm pretty sure it is concerning the bad Giants physics sliding stuff.
as I can see on you screenshot, the trailer has moved into the tractor. (silly, isn't it ?)  my question is : did the second tractor arrive and went into the trailer or did it stop and after a while it started to drive into the trailer. I've tried a lot but couldn't catch it....

**Comment by valdimellen** [comment]
i think it went directly into the other trailer. 

this time i had the failure only one time during 12hr

**Comment by sootysax** [comment]
i will test this again today

**Comment by Maxcdr** [comment]
Got the same kind of issue but it happened randomly.

Here green Man is in traffic: OK, no problem.
![fsscreen_2014_12_31_10_46_25](https://cloud.githubusercontent.com/assets/10348839/6439953/9c107aa4-c0d8-11e4-87af-74ef8da2cd04.png)

Here blue Man is slipping and pushing yellow Man.
![fsscreen_2014_12_31_10_45_28](https://cloud.githubusercontent.com/assets/10348839/6439997/1ce673ea-c0d9-11e4-971e-65927c51b581.png)

**Comment by ThomasGaertner** [comment]
If you want to try something I would ask you to change in drive.lua (version 0090)  line 791 
"if tz <= halfLength + 4 then" to "if tz <= halfLength + 2 then"   
Its just an idea which may help, but doesn't have to.....
keep reporting . thanks

**Comment by sootysax** [comment]
I haven't tried adding the change yet, but this is the scenario that triggers this for me...

Harvesting a field with an overloader (tractor 3)

Two trailers in mode 1, tractor 2 waiting behind the tractor 1 (in traffic) at the overload point.  Tractor with the overloader approaches the overload point and comes close to tractor 2 and triggers tractor 2 to start driving.   tractor 2 then crashes into the back of trailer 1 and spins until trailer 1 is full, and drives on its unloading route..

Since the overloader needs to have a relatively straight angle of approach to the overload point (to avoid a traffic collision with the trailer waiting at the overload point, this is hard to avoid.

**Comment by ThomasGaertner** [comment]
would B nice if you would try the same situation with the little change.....

**Comment by ThomasGaertner** [comment]
@sootysax : some news ?

**Comment by sootysax** [comment]
Changing the value from 4 to 2 has no change in the situation...

![fsscreen_2015_03_06_16_16_17](https://cloud.githubusercontent.com/assets/6591048/6536549/770ed042-c41c-11e4-98bf-2f1d430f5c99.png)

**Comment by maddavo** [comment]
I get this in a different situation.  With a combine in mode 6 it will stop if a tractor with a tipper crosses its path or is stopped in its path, but when the tractor moves across its path the combine will start to move when the tractor has cleared the header but before the tipper has cleared the header.  This often results in the edge of the header hitting the tipper.  I have had this happen with Sambo and Case combines and various different tippers.

**Comment by ThomasGaertner** [comment]
after another hours of testing I want you to test with v0097 or higher  and debug channel 3 active...

**Comment by sootysax** [comment]
https://gist.github.com/sootysax/b09349355599eaf130df/download

![fsscreen_2015_03_17_13_18_22](https://cloud.githubusercontent.com/assets/6591048/6693288/39ca5b2c-cca8-11e4-8c59-cab23233a689.png)

**Comment by ThomasGaertner** [comment]
@sootysax , the log lead me into a new direction. please go on with 0098 or higher in the same manner 
Thanks

**Comment by sootysax** [comment]
preliminary testing seems like better traffic recognition with trailers passing in front of tractors..   I can confuse it into crashing into my trailer by moving back and forth in front of it..   but more testing will be needed to see if it happens during normal gameplay via silo loading and overloading.

**Comment by kwguk** [comment]
I have the same problem
[URL=http://s1181.photobucket.com/user/kennywasgod/media/2015-04-23_00001.png.html][IMG]http://i1181.photobucket.com/albums/x427/kennywasgod/2015-04-23_00001.png[/IMG][/URL]

Yet on same route

[URL=http://s1181.photobucket.com/user/kennywasgod/media/2015-04-23_00002.png.html][IMG]http://i1181.photobucket.com/albums/x427/kennywasgod/2015-04-23_00002.png[/IMG][/URL]

It seems to me that some mod tractors will recognise the trigger and others will not
I noted what you said about the speed potentially being an issue but ive slowed it right down.

Im using ver101

**Comment by kwguk** [comment]
Ive tried a little experiment in the same place as the screen shots above. I used 5 mod tractors and 1 default NH 8320.

3 of the mod tractors crashed into the trailer after recognising the tip trigger and 3 did not, including the default NH.

Im no modder, I have very little understanding of the technical side of the game but isn't the problem more to do with the individual mod tractor than it is with CP?

**Comment by Satissis** [comment]
#1346
