### ISSUE TITLE
Vehicles no longer maintaining straight course

### ISSUE THREAD

**Issue by Nebular64** [Courseplay/courseplay#1075]
I'm currently on v.0089 and I'm seeing problems with vehicles maintaining a straight line while on a road.  A tractor, be it with or without a trailer, will stay on course for about 5 seconds and then it starts to slightly wobble back and forth.  The course has no turns and is nothing more than a straight line.

The wobbling will get worse and then the tractor just runs off the run into a tree or ditch or fence, etc.  I have to constantly reset the course and get the tractor back inline only to have the wobble effect start back up.

The only way I've been able to prevent the wobbling is to set the road speed to under 25mph.  Any higher speed will cause the tractor to wobble off course.

I believe this problem was reported some time ago, but I can't find any closed requests about a fix.  I'm not sure if this is a Giants physic issue, but I don't recall having this problem as much as I do now.

**Comment by Maxcdr** [comment]
I experienced the same but I noticed that it happens only during game lag.

**Comment by ThomasGaertner** [comment]
which vehicles on which map and so on .... ?

**Comment by Satissis** [comment]
What's your fps when playing the game ?
If your fps is really low, it will happens just as @Maxcdr said, since an low fps will result in slow steering calculations and can go horrible wrong in high speed.

**Comment by Nebular64** [comment]
The map I'm currently running is Manchester from American Modders.
I turned on development mode to get my FPS, which varies from a high of 50fps to a low of 24fps depending on the area of this particular map.
Now, what's strange is that the tractor (New Holland T6.160) is now running a straight line.  I guess I'll close this out and just keep the game in development mode to monitor FPS.  Please let me know if there is a certain low fps number to look out for that would cause this issue.  For example, does it occur if the fps drops below, say 15fps?

Thanks...

**Comment by Nebular64** [comment]
-UPDATE-

I tried overloading the graphics and got the fps down to 14fps.  At that point the wobbling started, so it's definitely a lag issue on my end as noted by Maxcdr.

**Comment by Satissis** [comment]
I thought so :)
I have some similar experience my self, with my old PC when I was recording the old CP tutorials for FS13, but mostly it always worked if I had an recording fps on around 25-30 fps.
