### ISSUE TITLE
recording a course: second waypoint is at way longer distance to previous waypoint than following wps

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#1076]
I noticed a long time and don't know if it is a bug, or not.

When I start recording a course it sets the first waypoint, then I begin to drive and often it takes twice or more the distance to set the second waypoint, than it takes for the next waypoints to be set.

When you have to turn right after beginning a course the whole turn is missed sometimes.

Would it be possible to have the frequency of waypoints somehow related to the velocity you drive?
When going slower (turns, narrows, etc.) waypoints should be created more often and when going fast (e.g. over 40km/h) waypoints could be created less often, maybe half the frequency?

**Comment by JakobTischler** [comment]
1. It's on purpose. Mostly for mode 2/3, where the second waypoint will be targeted and approached to drive the course after unloading the combine. The distance between wp 1 and 2 is increased to reduce the danger of colliding with a vehicle waiting at wp 1.
2. The distance between waypoints is basically a hard number (5), but it also depends not on the velocity but on the current relative angle to the last waypoint's angle. Meaning: in a curve, there will be more waypoints because of angled directions.
3. You should never start a course with a turn. I'm not certain that this part is still in the manual, but we do advise, almost require, that the first three points are basically in a straight line.

**Comment by AndyK70** [comment]
Ok, understood and I see your points for mode 2 and 3.

My problems are with modes 1, 4, 6, and 9 :D 

Mode 1: Start has to be at the fill pipe. At Bjornholm there is not enough room for three waypoints in a straight line. When I stop the driver while filling the trailer (e.g. got to go to bed) and then I want to continue next day with default "start at nearest wapoint" the tractor is going in circles, because he wants to go to waypoint one, right in the back of it, because 2nd waypoint is too far away.

Mode 4/6: when not generating, but recording a course this behavior could led to overshoot into the field, not getting the first crops.

Mode 9: It's a bit tricky to get a decent turn, not to tight, and have enough room to start the course making that first waiting-point  before entering the silo. So I thought of why not using the straight line while coming from the bunker to the silo?
![2015_02_28_14_09_000_turn at bga](https://cloud.githubusercontent.com/assets/666825/6412974/becb26a2-be8a-11e4-84bb-b180017bd004.jpg)

You may notice it's not really easy to get enough space for those three straight lines.

**Comment by kwguk** [comment]
Is this a possible solution....from EricT43 on FS-UK


Thanks, that looks like a good solution.  I did find something a little less time-consuming that helped a lot, though.  I went into Courseplay.xml in my savegame folder and changed the "scanStep" parameter from 5 to 1.  This creates a lot more waypoints when scanning the edge of the field.  Still not perfect, but certainly much better.

**Comment by AndyK70** [comment]
didn't test it, but I don't think field edge recognition has something to do with recording a course manually.

**Comment by CaptainRush** [comment]
had this happen to me too. When recording a course that start aside a building and takes a 90degree turn resulted in the vehicles trying to shortcut through the building

**Comment by Karlshoj** [comment]
If you want an extra waypiont in the start of your course or in a courve you just hit the "cross point" button. It creates a waypoint for each hit. It´s very usefull in confined areas.

**Comment by AndyK70** [comment]
Addind crosspoints where I have no use for would lead me into trouble.
I'm using merging and attaching courses a lot and I take care crosspoints are only where I really need them. Merging courses with additional crosspoints somewhere along the course could have very strange results and bad merged courses.

**Comment by Karlshoj** [comment]
I fully agree about the extra crosspoint, but you just edit them away in the xml file. A little job to do, but result is very nice curves.

**Comment by Karlshoj** [comment]
Un-needed cross points removed in the xml file.
1 minuts work

![fsscreen_2015_03_16_22_18_16](https://cloud.githubusercontent.com/assets/7414065/6679696/8cd1afba-cc2a-11e4-826b-fac20cd57cd5.png)

**Comment by Satissis** [comment]
#1346
