### ISSUE TITLE
The game cant start with Courseplay

### ISSUE THREAD

**Issue by chipsy338** [Courseplay/courseplay#1078]
Hey,

first of all sry for my bad english but im from Germany :)

I´m playing FS15 on Bjornholm and had summoned / summond ( zusammengefasst) field 24 and 25.
If i want to join this savegame now, Courseplay stop scanning the fields by field 23.
Then the game crashes.
http://pastebin.com/bqFAFKwU

**Comment by AndyK70** [comment]
Don't use Loadstatus, it generates an error.

I suggest to use glance (http://fs-uk.com/mods/view/35659) which covers Loadstatus and Inspector, so you can remove inspector as well.

Please try again with glance and removed inspector and loadstatus.

**Comment by chipsy338** [comment]
Hey,
thanks for you answer.
But it also doesnt start.
Courseplay cant load field 23/24

**Comment by Satissis** [comment]
So this sounds like an mod map, where the field are not created correctly and the auto field scan are having some problems.
try going into your savegame folder for the savegame you are playing, then open up courseplay.xml in notepad or something similar. There is an line like this:
```
<courseplayFields automaticScan="true" onlyScanOwnedFields="true" debugScannedFields="false" debugCustomLoadedFields="false" scanStep="5" />
```

Change ```automaticScan="true"``` to ```automaticScan="false"``` in that line, to turn off field scanning.

Now I know that no fields will be scanned automatic anymore, but you can still do it manually, by driving into the field and then use the "Calculate current field's edge path" to scan the field you are located on.
If it finds all the edge, it will show as an blue line around the field, and below the calculate button, you can save the field manually, so you only need to scan it once.

Try it out and report back.

**Comment by valdimellen** [comment]
Log: https://www.dropbox.com/s/loi6dzyyqdikiq5/log.txt?dl=0
![skaermbillede 2015-02-28 kl 21 15 45](https://cloud.githubusercontent.com/assets/11229601/6427916/4857e5a4-bf8f-11e4-9bb1-49fe524c169f.png)

**Comment by ThomasGaertner** [comment]
@chipsy338 : some update ?
