### ISSUE TITLE
Reversing into a Composter

### ISSUE THREAD

**Issue by hackselgut** [Courseplay/courseplay#1079]
Can I get some Help on the best way to Build my course, I have built a course but when I get to the place I need to do a backup, up a Ramp , my Truck will back into the concrete walls. Should I be using the ( horseshoe or Pause options. )
![fsscreen_2015_02_27_05_09_53](https://cloud.githubusercontent.com/assets/10256656/6417772/daeb77ea-be7d-11e4-9bcd-5d9e87a58f3b.png)
![fsscreen_2015_02_27_05_10_21](https://cloud.githubusercontent.com/assets/10256656/6417771/daeb7d08-be7d-11e4-81b7-39c3c6292122.png)
![fsscreen_2015_02_27_05_10_42](https://cloud.githubusercontent.com/assets/10256656/6417773/daeb9a86-be7d-11e4-9b92-09dfc72e2351.png)
![fsscreen_2015_02_27_05_12_56](https://cloud.githubusercontent.com/assets/10256656/6417774/daebb4bc-be7d-11e4-8494-76ee86f04115.png)

This is what happens with my course.

**Comment by Satissis** [comment]
No you should not use the turn button (Horseshoe) or wait point for reversing, but only reverse as normal.
Could you make some screenshots of the route by turning them on in the hud ? that way we can see how they are made :)

**Comment by hackselgut** [comment]
Here are the Pics you would like to see. Should I be Straight on to the ramp as I get ready to reverse up the ramp?  I am asking because the one attempt to do the course, The truck just ignored the reverse point? and picked up the return line.
![fsscreen_2015_02_28_14_35_57](https://cloud.githubusercontent.com/assets/10256656/6427810/e87e784e-bf59-11e4-889b-4e0766ab1685.png)
![fsscreen_2015_02_28_14_37_39](https://cloud.githubusercontent.com/assets/10256656/6427808/e87e0710-bf59-11e4-8cca-9149e83c7703.png)
![fsscreen_2015_02_28_14_43_06](https://cloud.githubusercontent.com/assets/10256656/6427809/e87e0f30-bf59-11e4-83be-5bca347d795d.png)
![fsscreen_2015_02_28_14_43_45](https://cloud.githubusercontent.com/assets/10256656/6427805/e87ce4d4-bf59-11e4-8e6d-737dcf31a497.png)
![fsscreen_2015_02_28_14_43_57](https://cloud.githubusercontent.com/assets/10256656/6427806/e87d44b0-bf59-11e4-9532-2c9584c8ad2c.png)
![fsscreen_2015_02_28_14_44_17](https://cloud.githubusercontent.com/assets/10256656/6427807/e87d482a-bf59-11e4-9c08-404dddc64382.png)
![fsscreen_2015_02_28_14_45_50](https://cloud.githubusercontent.com/assets/10256656/6427813/e889021e-bf59-11e4-9bce-4017588c80b0.png)
![fsscreen_2015_02_28_14_45_59](https://cloud.githubusercontent.com/assets/10256656/6427812/e8888654-bf59-11e4-9459-97c9b120adf3.png)
![fsscreen_2015_02_28_14_46_08](https://cloud.githubusercontent.com/assets/10256656/6427811/e8879ce4-bf59-11e4-8732-11ca8034e02a.png)

**Comment by AndyK70** [comment]
When you go into turn in front of the composter you don't have enough straight line to haul the truck straight. It's stuck in the turn and struggles to get the truck on line when reversing.
Just straighten up a bit more before you reverse, so the whole length of the truck is covered with a straight line. After that you can go reverse even in turns, but not right at the beginning of the reversing.

**Comment by hackselgut** [comment]
Ok  That worked a lot better this time Thanks for the help, While I am here you`s state that if we use a tractor and trailer with reversing that we do it with no trailer attached, What do we do for the loading at the start, ( set the load position, then detach and record to the unload point, do a reverse and at this point guess what distance the trailer will have to make the Trigger for unloading, complete the recording back to the start point and re attach the trailer.? )
![fsscreen_2015_02_28_21_37_44](https://cloud.githubusercontent.com/assets/10256656/6429301/e504dcd4-bf96-11e4-8b82-a5a84f947e37.png)
![fsscreen_2015_02_28_21_37_53](https://cloud.githubusercontent.com/assets/10256656/6429302/e505f68c-bf96-11e4-86f5-81144d670cf5.png)
![fsscreen_2015_02_28_21_38_02](https://cloud.githubusercontent.com/assets/10256656/6429300/e504300e-bf96-11e4-9218-994207c73ce1.png)

**Comment by AndyK70** [comment]
When recording a course for Mode 1 (load at start, grain transport) you don't have to set any waiting-points, just record from where it should be filled, running over a tip trigger (even in reverse) and go back, line up and stop recording. Without any waiting points set.

When you record in reverse, the tractor is recording the waypoints for the trailer. That is, when CP is running that reverse section, the trailer and not the tractor is attached and lined up to the reverse waypoints. When driving forwards the waypoints are attached to the tractor again.

**Comment by ThomasGaertner** [comment]
@hackselgut : is it solved for you ?

**Comment by hackselgut** [comment]
Yes I am satisfied, Problem solved thanks . you can close the problem.
