### ISSUE TITLE
Trying to create modded placeable fertilizer tanks for Decker's SoilMod

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1080]
I have created separate placeable fertlilzer tanks for each of the fertilizer/herbicide/lime/water types for Decker's SoilMod for FS15.

I modded the 'Placeable Fertilizer Tank' found on the FarmingSimulator website found here:
http://www.farming-simulator.com/mod.php?lang=en&mod_id=7774&title=fs2015

I created new mods for each filltype, changing the filenames of each from waterTankPlaceable.i3d to fertTankPlaceableA.i3d for instance.  The same with each lua and xml file.

For each mod, in the xml I changed the <placeableType> from waterTankPlaceable to fertTankPlaceableA respectively for each fertlilzer.

In each .lua I changed any reference to "waterTankPlaceable" to its respective "fertTankPlaceableA"

In each .i3d I changed the filltype from 'fertilizer' to 'fertilizer2, herbicide2' etc... 

Everything is working well - they will fill with the respective fill type when I pull up to the correct tank  

except that Courseplay will not automatically fill when it gets to my modded tanks.

it will only automatically fill when it gets to the original fertilizer tank...

is courseplay setup only to recognize the "fertilizer" filltype?

do I have to register the fill type or placeable within course play somehow?

**Comment by JakobTischler** [comment]
Before starting the course, activate debug channel 1. This will print the map's triggers recognized by CP.
Then, when approaching the trigger, activate debug channel 19 to see if the trigger is caught by the vehicle.

If the trigger finding isn't the problem, it should refill (in theory) as long as the trigger's fillType is the same as the implement's fillType. It could be that at that moment the implement is empty and has the fillType `Fillable.FILLTYPE_UNKNOWN`, thus there would be no fillType match.

**Comment by sootysax** [comment]
Here are 3 logs - the first being a working standard placeable tank.  The next two are two different custom triggers.   also following are XML and LUA's of the standard and one of the custom triggers.

Working Standard Trigger Log
https://gist.github.com/sootysax/77d0add74404e12d5461/download

Non Filling Custom Trigger 1 - Fertilizer N
https://gist.github.com/sootysax/ec44956912789c9e325e/download

Non Filling Custom Trigger 2 - Fertilizer PK
https://gist.github.com/sootysax/d7abec3f75b58cf89cb3/download

Standard Tank - modDesc, XML, LUA & I3D
https://gist.github.com/sootysax/30c5fc1cfb9d30c1e0a5/download
https://gist.github.com/sootysax/be8bd800ff8904ca9df3/download
https://gist.github.com/sootysax/90da094bc6678b40e5a2/download
https://gist.github.com/sootysax/1297bf540b52c3128b0b/download


Custom Trigger Fertilzer PK - modDesc, lua, i3d, xml
https://gist.github.com/sootysax/35525c1420839f1638a0/download
https://gist.github.com/sootysax/ab74f6d10c3929df1022/download
https://gist.github.com/sootysax/f74da0abf7eb1cd94b7b/download
https://gist.github.com/sootysax/875eb24e5a1573c2e5b0/download

**Comment by sootysax** [comment]
any insight on why these will not fill?  vehicle slows down and recognizes that it's at a trigger, but just drives off without filling.

**Comment by Paul2510** [comment]
Is it possible that, for example, the syringe is not completely emptied but the 1-2% stay inside so that he remembers what's inside! Thus then it loads the right one!

**Comment by sootysax** [comment]
has anyone had a chance to look into this and why my tanks are not filling?

**Comment by Satissis** [comment]
Just an update: I know (from other sources) that Decker is trying not to get too much attention on Soil Mod until he releases it. On of the reasons not many knows the github for it, so please wait with this until he releases the first version.

Sorry for the late answer about this, but I just recently heard about it.

**Comment by sootysax** [comment]
fair enough

**Comment by ThomasGaertner** [comment]
I will close here but we will keep it in mind...

**Comment by sootysax** [comment]
update from Decker :

After some tests and added print()'s to Courseplay's script, I think the problem is due to how Courseplay determines what a fill-trigger is.

In triggers.lua function courseplay:updateAllTriggers() there is a check for:

...
  -- SprayerFillTriggers
  elseif trigger.fillType and trigger.fillType == Fillable.FILLTYPE_FERTILIZER then
      trigger.isSprayerFillTrigger = true;
      courseplay:cpAddTrigger(triggerId, trigger, 'sprayer', 'nonUpdateable');
      courseplay:debug('\t\tadd SprayerFillTrigger', 1);
...
So Courseplay will only recognize fill-triggers that has fill-type fertilizer as 'sprayer-fill-triggers'. But since your placeables have other fill-types (fertilizer2, fertilizer3, etc.), Courseplay will not take them into consideration.

I modified that if-statement in Courseplay, added SoilMod's fill-types, and ran an in-game test again. - Now Courseplay recognized the placeable PK fertilizer tank (i.e. fill-type fertilizer2.)

So the "solution" would be to somehow make Courseplay recognize the extra/new fill-types that 'sprayer-fill-triggers' could contain. Possibly SoilMod could call a "plugin"-method in Courseplay, to make Courseplay aware of the new fill-types.

**Comment by sootysax** [comment]
Edit from Decker:

Edit: Or maybe change the order of tests in Courseplay's courseplay:updateAllTriggers(), so anything that is not a 'GasStation', 'WaterTrailerFillTrigger' or has fill-type seeds, then set it as a 'SprayerFillTrigger'.

**Comment by sootysax** [comment]
Do you guys see the comments that are added after the issue is closed?

**Comment by ThomasGaertner** [comment]
We do

**Comment by ThomasGaertner** [comment]
Which map do you use for your tests ?

**Comment by sootysax** [comment]
i am using a few different maps..  Thistle Farm mostly and recently Statesv3.

**Comment by ThomasGaertner** [comment]
first of all, I changed the names for the tanks in the german version.
if you are interested, here is the link: 
https://www.dropbox.com/s/u1y1xfgpf58elrz/placeble%20soilmod%20tanks%20edited.zip?dl=0
maybe its useful , when the tanks are marked which is which. I had some trouble finding the right one while the first test....

**Comment by sootysax** [comment]
they are marked on the top of the tank on the white painted section.  N NPK PK etc...

**Comment by ThomasGaertner** [comment]
ok, didn't see it :-)
is there a reason, why the NPK is the only one, who has filltrigger.filltype ?

**Comment by ThomasGaertner** [comment]
https://gist.github.com/ThomasGaertner/38674d624bcad6812375

**Comment by sootysax** [comment]
the NPK is the original fertilizer tank and fill type.  aside from renaming and the graphics, it is unmodded.

**Comment by jmj486** [comment]
Is there any updates on the tanks vs courseplay?

**Comment by ThomasGaertner** [comment]
@sootysax : I'm playing around with soil mod atm. how is the status of your mod ? I would like to try to implement it again.....

**Comment by ThomasGaertner** [comment]
#1346
