### ISSUE TITLE
Problem with combinated course

### ISSUE THREAD

**Issue by Tonton1969** [Courseplay/courseplay#1081]
Hello,

I have with the newest version the problem that I connot combinate different courses.

Explenation:

1. Course to the field
2. field course with the two working points - with +
3. way back to the farm - with +
4. unloading course in the farm or load course for the fertilizer - with plus

There is always a problem when the course should go back again to the field from 4 to 1.....

And sometimes I have the problem that the game freeze when I do something on the coursepaly hud.

**Comment by Tonton1969** [comment]
Oh forgot with the old version the round course is no problem but still a problem with the game freeze.

**Comment by ThomasGaertner** [comment]
do you have a log of the freeze ?

**Comment by Tonton1969** [comment]
Here are the log of a freeze, sorry that it takes so long but in the last days it works without any problem.
The freeze occours when I sale some vehicle. (oh Ok one vehicle was running with courseplay could that be the problem?)

https://gist.github.com/Tonton1969/b56e1113a550ca781dd6

**Comment by ThomasGaertner** [comment]
please update to current version 0092 and try again, maybe its fixed already 
thanks

**Comment by Tonton1969** [comment]
Hello,

I tried the last version no program brakedown but I have then the problem with collectin gras or spary a field. Whencourseplay comes to the end of the course and should start at the start point it looses the course. With the old version no problem see log.
LUA call stack:
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/settings.lua(1388) : localToWorld
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/mode2.lua(521) : addNewTargetVector
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/mode2.lua(100) : unload_combine
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/drive.lua(245) : handle_mode2
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/base.lua(759) : drive
  D:/code/lsim2015/build/finalbin/dataS/scripts/vehicles/Vehicle.lua(2518) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/network/Server.lua(56) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/BaseMission.lua(1115) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/FSBaseMission.lua(1510) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/missions/mission00.lua(213) : update
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//Loesshuegelland_V3/SampleModMap.lua(114) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/main.lua(1401) : update
Warning (LUA): Unknown entity id 305013 in method name: localToWorld.
LUA call stack:
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/settings.lua(1388) : localToWorld
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/mode2.lua(522) : addNewTargetVector
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/mode2.lua(100) : unload_combine
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/drive.lua(245) : handle_mode2
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/base.lua(759) : drive
  D:/code/lsim2015/build/finalbin/dataS/scripts/vehicles/Vehicle.lua(2518) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/network/Server.lua(56) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/BaseMission.lua(1115) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/FSBaseMission.lua(1510) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/missions/mission00.lua(213) : update
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//Loesshuegelland_V3/SampleModMap.lua(114) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/main.lua(1401) : update
Warning (LUA): Unknown entity id 305013 in method name: localToWorld.
LUA call stack:
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/settings.lua(1388) : localToWorld
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/mode2.lua(523) : addNewTargetVector
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/mode2.lua(100) : unload_combine
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/drive.lua(245) : handle_mode2
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/base.lua(759) : drive
  D:/code/lsim2015/build/finalbin/dataS/scripts/vehicles/Vehicle.lua(2518) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/network/Server.lua(56) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/BaseMission.lua(1115) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/FSBaseMission.lua(1510) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/missions/mission00.lua(213) : update
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//Loesshuegelland_V3/SampleModMap.lua(114) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/main.lua(1401) : update
Warning (LUA): Unknown entity id 305013 in method name: localToWorld.
LUA call stack:
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/settings.lua(1388) : localToWorld
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/mode2.lua(521) : addNewTargetVector
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/mode2.lua(100) : unload_combine
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/drive.lua(245) : handle_mode2
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/base.lua(759) : drive
  D:/code/lsim2015/build/finalbin/dataS/scripts/vehicles/Vehicle.lua(2518) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/network/Server.lua(56) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/BaseMission.lua(1115) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/FSBaseMission.lua(1510) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/missions/mission00.lua(213) : update
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//Loesshuegelland_V3/SampleModMap.lua(114) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/main.lua(1401) : update
Warning (LUA): Unknown entity id 305013 in method name: localToWorld.
LUA call stack:
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/settings.lua(1388) : localToWorld
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/mode2.lua(522) : addNewTargetVector
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/mode2.lua(100) : unload_combine
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/drive.lua(245) : handle_mode2
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/base.lua(759) : drive
  D:/code/lsim2015/build/finalbin/dataS/scripts/vehicles/Vehicle.lua(2518) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/network/Server.lua(56) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/BaseMission.lua(1115) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/FSBaseMission.lua(1510) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/missions/mission00.lua(213) : update
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//Loesshuegelland_V3/SampleModMap.lua(114) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/main.lua(1401) : update
Warning (LUA): Unknown entity id 305013 in method name: localToWorld.
LUA call stack:
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/settings.lua(1388) : localToWorld
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/mode2.lua(523) : addNewTargetVector
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/mode2.lua(100) : unload_combine
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/drive.lua(245) : handle_mode2
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/base.lua(759) : drive
  D:/code/lsim2015/build/finalbin/dataS/scripts/vehicles/Vehicle.lua(2518) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/network/Server.lua(56) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/BaseMission.lua(1115) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/FSBaseMission.lua(1510) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/missions/mission00.lua(213) : update
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//Loesshuegelland_V3/SampleModMap.lua(114) : update
  D:/code/lsim2015/build/finalbin/dataS/scripts/main.lua(1401) : update
growthManager:: Saving to C:/Users/Privat/Documents/My Games/FarmingSimulator2015/savegame3/growthManager.xml
Warning: Deleting object 'sowingMachineTrigger' before all triggers are removed.
Warning: Deleting object 'fertilizerTrigger' before all triggers are removed.
Warning: Deleting object 'gasStationTrigger' before all triggers are removed.

**Comment by ThomasGaertner** [comment]
are you sure with the situation ? following the errors, you tried to unload a combine with a tractor in combined mode. The error occurred when the combine was empty . can you confirm that ?

**Comment by Tonton1969** [comment]
Hello,

like I explained before I combine my course like follow:

   1. Course to the field
   2.  field course with the two working points - with +
   3.  way back to the farm - with +
    4. unloading course in the farm or load course for the fertilizer - with plus

There is always a problem when the course should go back again to the field from 4 to 1.....
So I can confirm that the trailer is empty or the fertilizer full.

It works with the actual version one time and then the descibed behavior occours.

**Comment by AndyK70** [comment]
Try starting with the field course and add all courses after it. Then start with "Start at nearest waypoint"

Or if you are at a place far away from your next field and not even near to the transfer route, you can now define a first course to get to the field. Then add the field course for work, go back to farm, refill/unload, go back to field (not to first waypoint!).
The first course won't be driven anymore, because course now drives directly from the last waypoint of refill/unloading course to the first waypoint of field work course. 

See #1014

**Comment by Tonton1969** [comment]
Ok this works now well; but with the newest version I have another problem when I use the trailer (grimme for surarbeer) at the end of the field the tractor stopps becasue he send no waypoint to the trailer who bring the sugarbeer to the storage.

**Comment by AndyK70** [comment]
?
field course first, then unloading course (and back to field) should work.

**Comment by Tonton1969** [comment]
Hello,

the problem with the course are solved no problem. But with the newest version I have the problem when I use the Grimme (attached on a tractor) to harvest the sugarbeets the Grimme sends the tractor with the trailer not right away so the whole situation stops.

**Comment by ThomasGaertner** [comment]
test again with debug 4 active and post the log  thanks

**Comment by Satissis** [comment]
#1346
