### ISSUE TITLE
save position of 2D-Map in courseplay.xml and use it when starting next session

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#1084]
Would be very nice, if you could save the actual position of the 2D-map in courseplay.

I find myself dragging (very nice feature, btw.!) the 2D-map always to the same position every session i begin.
I think, every user has it's own preferred position for this map.

**Comment by ThomasGaertner** [comment]
@JakobTischler : by chance ;-)

**Comment by AndyK70** [comment]
just synched this morning.
was testing some stuff and noticed, it's already done. 
Many thanks :+1:
