### ISSUE TITLE
Warning (LUA): Argument to method 'worldToLocal' is nil

### ISSUE THREAD

**Issue by Mopar** [Courseplay/courseplay#1085]
Courseplay version: 4.01.0090
Map: Bjornholm (default)
Field: 37 (but will happen on any field)
Tools: Mex 5 attached to front of Same Fortis 190
Other Equipment: 2 Brantner E8041 Pulled by 2 Hiirlimann H488

The Same is set to mode 6 (fieldwork) and set to call the tractors based off of fill level and the H488's are set to mode 2 (Empty combine and offload) and the course leads to the BGA's at the biogas plant. The Mex 5 course start is set to South-east with starting direction set to North.

Starting out everything is fine. When the 1st trailer hits 50% the 2nd trailer is properly called but once the 1st trailer is full it starts to pull away from the Mex 5 to its course start to the BGA's then the game hangs and nothing becomes responsive (need to alt-tab out of game and force-close it).

In the log this error comes up and is spammed in the log until the game is exited.

Warning (LUA): Argument to method 'worldToLocal' is nil
-- from =C:/Users/Dan/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/mode2.lua:92
Error: Running LUA method 'update'.
C:/Users/Dan/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/mode2.lua:93: attempt to compare number with nil

**Comment by ThomasGaertner** [comment]
please test v0091 or higher and report....

**Comment by Mopar** [comment]
As of v0092 the issue is resolved and the log file is clean, thank you very much and keep up the good work!
