### ISSUE TITLE
Work lights and CP

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#1086]
I have this mod......http://fs-uk.com/mods/view/35779/drive-control-mod.....which allows me more control over the tractor including lighting. I can turn the work lights on and they will stay on even when I get out of the tractor or switch to another vehicle.

Yet when I engage CP on the vehicle and i either get out of said vehicle or switch to another and then return the work lights have been extinguished.

Is there a way of keeping work lights on a vehicle without CP turning them off?

**Comment by AndyK70** [comment]
Just enable them in courseplay general settings for that vehicle

**Comment by kwguk** [comment]
Unless I'm missing something there is no option that i know of to,make such an adjustment. There is a setting for beacons but not for any other lighting.

Unless I'm wrong......

**Comment by AndyK70** [comment]
Oh, sorry you meant work light (numpad 5) which is only available to some vehicles.

Mixed it up with hazard lights (numpad 2), as they can be configured in that option, too.

**Comment by kwguk** [comment]
Apologies for being a dullard but are you saying that I can do something about it or not?

Manual work lights tend to be KP_5 and KP_6. Which can easily be edited. It's the whole fake light/real light lighting that causes problems with CP

**Comment by AndyK70** [comment]
No, we (user) can't do anything about the worklight controlled by cp being on or not.

The option I mentioned is for beacon lights and hazard lights only.

**Comment by kwguk** [comment]
Ok mates no worries 

Thanks anyway
