### ISSUE TITLE
Reverse to load trailer: tractor turn at the end of course

### ISSUE THREAD

**Issue by Maxcdr** [Courseplay/courseplay#1087]
Searched in other submited issues but found nothing.

Map: Coldborough Farm 2015 / Standard vehicles + Marhu conveyor
CP v4.01.0090

I want to load my trailer at silo with Marhu conveyor. Course start and end under conveyor.
At the end of the course while driving reverse direction, tractor start to turn while recorded straight without trailer (see end of this video: http://youtu.be/Jv5dklfVEqI).

What am I doing wrong?

Courseplay.xml file available here: https://gist.github.com/Maxcdr/a83609c6ee6a7cb82d7e

**Comment by AndyK70** [comment]
I think it's because cp wants to continue to drive at first waypoint and tries to steer the tractor that way it could drive to waypoint 1.

Just guessing, but if you would record the beginning and end of the course, like it is described in the manual (lining up the end, that cp can continue to drive on to waypoint 1) this wouldn't happen.

**Comment by Maxcdr** [comment]
I hope I understand your suggestion. I tried to increase distance between start and end points by moving start point only (trial 2 picture below) and the issue still remain.

Trial 1:
![fsscreen_2015_03_02_13_01_21](https://cloud.githubusercontent.com/assets/10348839/6440447/3f3de44c-c0dd-11e4-8307-def844cd5fc7.png)

Trial 2:
![fsscreen_2015_03_02_12_58_48](https://cloud.githubusercontent.com/assets/10348839/6440456/53ef82ce-c0dd-11e4-8ecd-566a0ad3d641.png)

**Comment by AndyK70** [comment]
Not really, as for getting from last waypoint to first waypoint the vehicle has to do a 180° degree turn.
Line up the last waypoint in straight line to the first waypoint.
As for your scenario, I would suggest to begin and end at another place, where you can have the last and first waypoint in a straight line.

**Comment by Maxcdr** [comment]
Two new trials with same issue:

Trial 3: Start and end waypoint at same place:
![fsscreen_2015_03_03_17_58_34](https://cloud.githubusercontent.com/assets/10348839/6467622/cb73759c-c1cf-11e4-8d1d-3c2f93d76825.png)

Trial 4: Start and end waypoint in straight line but not at same place:
![fsscreen_2015_03_03_18_03_02](https://cloud.githubusercontent.com/assets/10348839/6467655/f48f202a-c1cf-11e4-869a-b13e7679925f.png)

**Comment by Satissis** [comment]
Did you change the direction to forward before stopping the recording ?

**Comment by Maxcdr** [comment]
No and that's what causes the issue. Now it works well with this configuration:
![fsscreen_2015_03_04_08_02_26](https://cloud.githubusercontent.com/assets/10348839/6479428/7101a31a-c245-11e4-864a-605575f3cb73.png)
