### ISSUE TITLE
second Tractor will not follow path/track

### ISSUE THREAD

**Issue by RedOhne** [Courseplay/courseplay#1088]
Hi, 

I figured out an issue with courseplay today. I had a course for grain transport from my silo to a selling point. The first tractor (Deutz AgroStar 6.61 with Marshall QM 16) follows without any issue. When I start the second one (Ursus 15014 with  Kröger Argoliner HKD 302) isn't able to follow his track. I just starts driving forward, the front tires start wiggling). It dosn't matter, if it's the same track, or another one, or if I start the the first or the next waypoint (the actual one does not work, also). 

I also had the issue earlier the day, with working mode. But some hours later this worked and the issue starts some tracks later. I already deinstalled the mods, which I installed, but had the same issue. My courseplay version is: v4.01.0090

I attached the log: https://gist.github.com/RedOhne/5ca7329946e2686741d4

Thanks
Tim

**Comment by ThomasGaertner** [comment]
I can not reproduce it, can you ? if yes, how

**Comment by RedOhne** [comment]
Hi Thomas, 

yesterday the error did not occur again. I will try to reproduce today. Once I have reproduced it, I will send another message.

Tim

**Comment by RedOhne** [comment]
Hi Thomas,

I tried to reproduce the issue. It seems that courseplay does not like the combination of Ursus tractor and any tipper. I tried the course the the ursus with two tipper (Kroeger HKD 302 and the Marschall QM16). The behavior is as described in the issue i reported. The Deuts AgroStar is able to follow the track with both tippers. When I setup the Ursus tractor together with the bale wrapper to follow the same course it's working without any issue.

Best regards

**Comment by ThomasGaertner** [comment]
works fine for me, does anyone else have this issue ?

**Comment by RedOhne** [comment]
Hi, I removed the ToggleTipSide Mod. After that, everything was working fine again.

**Comment by Satissis** [comment]
can we close this then ?

**Comment by RedOhne** [comment]
yes
