### ISSUE TITLE
About route

### ISSUE THREAD

**Issue by Admilson** [Courseplay/courseplay#1089]
- For each type of plant, a new route needs to be done if it is not possible to pass the trigger
- My question is a route starting and ending near the discharge area would be possible?
- To do this would require another point called Load to set in the field
- Thus a single route would be necessary in the field, and in the discharge area we would have additional routes.

**Comment by ThomasGaertner** [comment]
sorry , but I don't understand. 
could you please try again with other words ?
Thanks
