### ISSUE TITLE
total work

### ISSUE THREAD

**Issue by Darkanj0** [Courseplay/courseplay#1090]
Hello, I wonder if I have to create the following course.

The tractor leaves the garage goes to the field, joins planha and leads to the deposit, does this in any field, and then back to the garage.

problem:
"" I got to be part of this course. The problem is: after the tractor unload cargo for 1st time he goes to the garage and should work in any field and then go to garage "".

For this I created 4 courses.
1 leading from the garage to the field.
2 is the route in the field (attach straw)
3 takes the straw for the deposit
4 back to garage

This way I could have the gardados vaiculos in garages, would only choose the course, he would do the job and return to the garage.

Note. Sorry for the English'm using google translator.

Thank U

**Comment by ThomasGaertner** [comment]
that's not possible , because all waypoints behind the last field work point will be recognised as unloading course. so you have to leave out the last part, till the work is finished and change the courses manually

**Comment by Darkanj0** [comment]
Thanks for your help.
And if I used the following order.
1 back to garage
2 go from the garage to the field
3 route field
4 download

When starting the route rather than start from the first point, begin the next point. (As the the tractor'll be stopped at the end of the route "back garage" the next point would be the first point of the route "to go from the garage to the field."

When finished fieldwork send the tractor continue and stop at the next tigger (hence the tractor would stop at the last point of the route "back to the garage")

Does it work?

I will test.

**Comment by ThomasGaertner** [comment]
try out....
