### ISSUE TITLE
CP xml 13>15

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#1091]
Is it possible to use your Courseplay xml files from FS13 savegames and transfer them to the same map but the FS15 version?

**Comment by Satissis** [comment]
I'm not totally sure you can anymore, since we have changed a bit in the xml file.
You can always try it out, but no promises.

**Comment by kwguk** [comment]
No worries Satissis!

I only asking because I'm waiting for PC to be upgraded and I couldn't test it myself. When I get it back I'll test it out.
