### ISSUE TITLE
Game freezes due to large courseplay.xml

### ISSUE THREAD

**Issue by benjoglove** [Courseplay/courseplay#1093]
Has there been any development/improvement with courseplay and large maps i.e. STATESv2 ? I have half the fields under course play and even that is freezing/slowing the loading screen.

**Comment by AndyK70** [comment]
I made a suggestion (#908) to reduce waypoints for generated fields, but it wasn't accepted.
Read last statement from @JakobTischler 

Nevertheless I made a change for myself on my forked version of courseplay and it works very well. Haven't discovered any backlashes yet.

**Comment by sootysax** [comment]
This is why I use combined routes and only record routes for each road once.   I do not save generated courses and keep my courseplay.xml file pretty small.

**Comment by AndyK70** [comment]
I don't use only automatic working-width and single lane, so I use to save special courses for not forgetting/mixing up settings for those fields.
For example Westbridge Hill Field 17. Without my optimization routine for the Sampo C6 it would generate about 3171 waypoints, with my optimization only 777. After that some extra waypoints are added for start, end and turns, but the lanes have much less waypoints.

> [dbg7 lp2329] before optimize numPoints=3171
[dbg7 lp2329]  after optimize numPoints=777

**Comment by ThomasGaertner** [comment]
@AndyK70 :what happens on your field work course when the trailer is full , where does it return ?

**Comment by AndyK70** [comment]
It returns to some waypoints earlier where it stopped, as it does without my modification.
If I find the distance too long, I will investigate where the number of waypoints (indices in table) are reduced to start some earlier and shorten the reduction. ;)
If not, I will leave it that way.
Until now It didn't bother me.

**Comment by benjoglove** [comment]
Okay so general rule of thumb is to not save courses in course play got it.
