### ISSUE TITLE
Tractor follows not the course after refill/unload in mode4 or mode6

### ISSUE THREAD

**Issue by AlterSack1966** [Courseplay/courseplay#1096]
My courses are structured as follows:
Course Starting point -> Start point field -> Field endpoint -> Fill (mode4) or empty (mode 6) -> Course endpoint.

Up to version 4.01.0068 these courses have worked perfectly.

Since version 4.01.0086 we of course once worn correctly. After the fill or empty the course is executed prior to the course endpoint. After the course, the end point of the tractor changes direction, so that he motor closes exactly on the waypoint to which the sowing manure, or bale load is to be continued. This behavior is independent of the vehicle, equipment and price. 
Unfortunately, I have no versions between 4.01.0068 and 4.01.0086 to detect the changes that has led to this behavior.
The last tested version is 4.01.0092

Many thanks for your help!!

**Comment by ThomasGaertner** [comment]
I don't understand all of what you have written, it is possible that it is concerning #1014 . is it?

**Comment by AlterSack1966** [comment]
yes, I think you are right.

**Comment by AndyK70** [comment]
Which maps are you playing, that there are so many obstacles in the fields?
I placed the endpoint of my refill/unload courses accordingly. On non rectangular fields somewhere inside the field from where all waypoints are reachable without any problems.

**Comment by AlterSack1966** [comment]
I think I have to organize my courses in the future so that between refill trigger and field course no waiting points are present, then my courses could work again. I will test it next week and report back here.

**Comment by AlterSack1966** [comment]
Ok I sow, fertilize and unload bales tested, everything works fine when I notice the new rules. Would be helpful if this information would be included in your owners manual.

Thanks and regards

**Comment by ThomasGaertner** [comment]
It will be, for the next release. This is a developer version without support through manuals. Can we close then ?

**Comment by AlterSack1966** [comment]
This is what I mean. Yes you can close.
Thx
