### ISSUE TITLE
Courseplay trigger

### ISSUE THREAD

**Issue by EriX89** [Courseplay/courseplay#1097]
Hallo,

Ich habe bei dem JD S690i von Big Boss Modding das problem das der Abfahrer beim Abtanken einen Auto. Abstand von 8.8m setzt, dieser ist aber zu nah am Drescher sodass er nicht abtankt.

Nun meine Frage nach welchen Trigger richtet sich CP?

Wenn ich den Trailer Trigger im Mähdrescher versetze fährt der Abfahrer zwar anders an aber stellt immer wieder die 8.8m ein.

Da ich mit 2 verschiedenen Mähdreschern arbeite kommt ein manuelles einstellen nicht in Frage.

Mfg

EriX

**Comment by ThomasGaertner** [comment]
first of all: we have developers and supporters all over the world. It would be nice if you would respect our rules and write in English.
second, just tested quickly and 8.8. worked for me, which trailer did U use ?

**Comment by EriX89** [comment]
Hello,

My English is not so good.

I use an IFA L60 truck with HW 80 trailer.

Von meinem Windows Phone gesendet
________________________________
Von: Thomas Gärtner<mailto:notifications@github.com>
Gesendet: ‎08.‎03.‎2015 16:15
An: Courseplay/courseplay<mailto:courseplay@noreply.github.com>
Cc: EriX89<mailto:EriX89@live.de>
Betreff: Re: [courseplay] Courseplay trigger (#1097)

first of all: we have developers and supporters all over the world. It would be nice if you would respect our rules and write in English.
second, just tested quickly and 8.8. worked for me, which trailer did U use ?

---

**Comment by ThomasGaertner** [comment]
I ve checked it and the calculation is correct. If you want to change it , you have to move the 
pipeRaycastNode . Please close, if you understood
Thanks

**Comment by EriX89** [comment]
When I move the Piperaycastnote the changes while automatically set distance but he does always still not with the value off.
I had the problem been FS13 with lower trailer.

The Mod is http://uploaded.net/file/za5q8ojm

**Comment by ThomasGaertner** [comment]
ok there is a workaround for your issue:
the combine will save the offset once, when its been emptied to 0 for the first time.
so set the 9.6m manually , empty the combine and set back to auto mode, then the truck will take the saved offset from the combine. More I can't do for you ....

**Comment by EriX89** [comment]
OK it works so far.

Thank you for your help
