### ISSUE TITLE
Too many waiting points

### ISSUE THREAD

**Issue by cpoole2005** [Courseplay/courseplay#1100]
When I try to have a semi truck with 2 trailers and an overloarder empty into them I get an error of too many waiting points (see attached screen shot), why what am I doing wrong?
![fsscreen_2015_03_08_20_37_45](https://cloud.githubusercontent.com/assets/5596638/6548589/3807608a-c5d4-11e4-986f-d4a7af0543a6.png)

**Comment by sootysax** [comment]
You should be able to set up at one waiting point as the start point for your semi trailer route..  it should pull up to fill the second trailer when the first is full..

**Comment by Satissis** [comment]
exactly as @sootysax said. Set the truck and semitrailer in mode 1 with an recorded route to where it needs to be unloaded and start it. Once the first trailer is full it will automatic pull forward until the next trailer is in place.
