### ISSUE TITLE
Kirovets K701AP

### ISSUE THREAD

**Issue by Phantom742** [Courseplay/courseplay#1103]
Hi Gents,

first of all thx for the work you put into courseplay!!! 

I have an issue with my K701AP! It is a wheel loader but the shovel is already cinnected to the loader ( as the real maschine). That creates the issue that the shovel won't be detected. I think the tproblem is that i had to create a new vehicle claas which won't be recogniced correctly. What do I have to do to get it to work? (here the download link: http://www.modland.net/farming-simulator-2015/forklifts-excavators/kirovets-k701ap.html) .

Greets,

 Phantom742

**Comment by Maxcdr** [comment]
>That creates the issue that the shovel won't be detected.

What do you mean exactly by "detected"? I tested and managed to record all shovel positions.

**Comment by ThomasGaertner** [comment]
try v0093 and report...

**Comment by Phantom742** [comment]
Will do! Thx

Von meinem iPhone gesendet

**Comment by Phantom742** [comment]
Gents,

I tested it with version 96 and it works just fine. Thanks for the fast fix.

**Comment by Phantom742** [comment]
Recommend to close that issue.
