### ISSUE TITLE
Courses lost after game crash

### ISSUE THREAD

**Issue by Maxcdr** [Courseplay/courseplay#1104]
After a game crash I lost many of my recorded courses. I opened my courseplay.xml file and it is truncated. I must admit that there were a lot of courses and the file was quite big.

I'm pessimistic but I give a try: any chance to recover my xml file?

**Comment by Karlshoj** [comment]
If you compare a "good" xml to the crached one you may see that one of the last lines is missing. Then just copy that line from the "good" file and it may work.
I have succeded a few times.

**Comment by Maxcdr** [comment]
Thanks but this is what I did. The file was truncated in a middle of a course and I added
```
        </course>
    </courses>
</XML>
```
at the end. Then I saw that many courses were lost...

**Comment by Karlshoj** [comment]
Yeah- then no help from me. Enjoy the recording of courses ;-)

**Comment by gui7545** [comment]
there is a file: "courseplay_backup.xml" that can help you

**Comment by Maxcdr** [comment]
There is none in my savegame folder...
I've already seen this backup file but I thought it is made by Coursedrawer (Courseplay Editor)...

**Comment by gui7545** [comment]
And in your folder savegameBackup ? The game create it when you leave without saving

**Comment by Maxcdr** [comment]
@gui7545 : you're my hero! I totally forgot that. Everything recovered. Thanks a lot!
