### ISSUE TITLE
Collision detection bales

### ISSUE THREAD

**Issue by jhomer** [Courseplay/courseplay#1105]
I think back in FS 2013 courseplay had a collision detection for bales in the field and I noticed it does not seem to be working for FS 15.
Example: fieldwork and unload course for auto-stacker, after filled and heads to end of field course to start on unload course it doesn't drive around bales that are in the field.
Using all default equipment and square bales.
CP version: .0089.dev.

**Comment by jhomer** [comment]
I may be a bit out of the loop but after trying with an unload course the doesn't start at the field-end-point, once the stacker is filled CP heads straight to the unload course without going to end of field course.

**Comment by Karlshoj** [comment]
https://github.com/Courseplay/courseplay/issues/1014

**Comment by ThomasGaertner** [comment]
@jhomer : it's concerning #1037 . I'm on it but it takes some time....

**Comment by ThomasGaertner** [comment]
I will close it , to keep the issues area clean, please follow the referenced issue
Thanks

**Comment by jhomer** [comment]
Thanks @Karlshoj for the informative link! And @ThomasGaertner now that I see you guys re-routed to head straight to the unload or fill course instead of field end, it probably isn't a big deal anymore.
Thanks again for all the work with CP!!!
