### ISSUE TITLE
0094 hangs on loading screen

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1106]
CP 0094 will not load, hangs on the load screen..  reverting to 0092 works fine.

https://gist.github.com/sootysax/7b42bcb228a172cb7711
**Satis Edit Link** Removed /download so we don't download it but watch it on gist instead.

**Comment by ThomasGaertner** [comment]
try again v0095 or higher...

**Comment by sootysax** [comment]
working with 0095
