### ISSUE TITLE
Doesnt load ingame

### ISSUE THREAD

**Issue by CFMayhem** [Courseplay/courseplay#1107]
I download the zip file then put it into my FS15 mods folder. However when I load the game it does not appear in mods and is not active in game

**Comment by CFMayhem** [comment]
![courseplay in folder](https://cloud.githubusercontent.com/assets/11490333/6657208/795c1f68-cb3c-11e4-9229-23128adcd747.png)

This is my mods folder

**Comment by Raints** [comment]
http://courseplay.github.io/courseplay/en/installation/index.html

**Comment by CFMayhem** [comment]
I've tried that and its still not working

**Comment by Karlshoj** [comment]
That´s a bit strange, as it works for everybody else.
You unzip your downloaded file.
You mark all files in the unzipped folder.
You zip all the marked files as "zzz_courseplay" or just "courseplay".
You copy your new zip file into the mods folder.

**Comment by sootysax** [comment]
youre doing it wrong.  you need to zip the contents of the courseplay master folder into a new zip file and put that in your mods folder

**Comment by CFMayhem** [comment]
Ill tell you exactly what I do,  download the file, extract it to my desktop, take that new folder, archive the contents into a zip named ZZZ_courseplay.zip and put it into my mods folder. FYW: I not sure if it matters but I made a new folder called "mods" in my farming sim folder because there wasn't one before

**Comment by Karlshoj** [comment]
The mods folder must be a subfolder under FarmingSimulator2015

**Comment by CFMayhem** [comment]
It Is the mods folder is in this location:

C:\Program Files (x86)\Steam\SteamApps\common\Farming Simulator 15\mods

**Comment by Karlshoj** [comment]
I don´t when playing on Steam.
My path says: Documents/My games/FarmingSimulator2015/mods

**Comment by CFMayhem** [comment]
Ok dude, thanks for the help anyways

**Comment by sootysax** [comment]
your zzz_courseplay.zip file should contain all the files that are shown on the courseplay code page - 

https://github.com/Courseplay/courseplay

they should be in the root of that zip file, not in another folder.

your mods folder for a steam game should be in - Libraries/Documents/My Games/FarmingSimulator2015/mods

**Comment by CFMayhem** [comment]
Thank you so much, its working now :) :) :)

**Comment by gui7545** [comment]
You don't want to reopen it ?
