### ISSUE TITLE
Issue with Shovel/Fill

### ISSUE THREAD

**Issue by tmaleshafske** [Courseplay/courseplay#1109]
after dumping into truck or pit loader needs to go to pre-unloading position, then start to back up. for the next 1 or 2 waypoints then go to the transport position.  This eliminates any collision issues with what the loader is dumping into.   This is using the standard wheel loader and bucket.

**Comment by AndyK70** [comment]
That's how it already works, doesn't it?

**Comment by ThomasGaertner** [comment]
it is supposed to be so ....

**Comment by ThomasGaertner** [comment]
after reading you post twice, I understood your problem. please test v 0100 or higher and report...

**Comment by tmaleshafske** [comment]
Worked perfectly fine now. thanks you using version 4.01.0100

V/R
Thomas E Maleshafske
tmaleshafske@maleshafske.com
"Ne Desit Virtus" Let Valor Not Fail
"Semper Paratus" Always Ready
