### ISSUE TITLE
Record Cat 980H AWS 15 problems with quote

### ISSUE THREAD

**Issue by rmn18** [Courseplay/courseplay#1110]
Tried to take a course and stored for the blades from the silo, but the loader will not move and has written to me instead an error in the log file. Here is my log file.
http://pastebin.com/LkQuKj9s

**Comment by ThomasGaertner** [comment]
I've fixed the missing check to prevent the errors but be aware that the "Cat 980H AWS Loader v3" will never work properly, because it has no aiTrafficCollisionTrigger .
please test v 0099 or higher and report...

**Comment by rmn18** [comment]
The LUA error is gone, only the blade is not detected at CAT. See the picture, but the blade settings work.
![fsscreen_2015_03_19_20_30_09](https://cloud.githubusercontent.com/assets/3426782/6739142/17361f76-ce77-11e4-8eee-3263d44f419b.png)

**Comment by ThomasGaertner** [comment]
or give it the wheelLoader spec which would make more sense.....

**Comment by ThomasGaertner** [comment]
@rmn18 : can I close ?

**Comment by rmn18** [comment]
yes can cloesed thanks
