### ISSUE TITLE
[BUG?] Problems using courseplay: Deformation of the player's arm.

### ISSUE THREAD

**Issue by MoslessNeo** [Courseplay/courseplay#1113]
![farmingsimulator2015game 2015-03-21 20-37-47-01](https://cloud.githubusercontent.com/assets/6533809/6767375/3c152950-d00b-11e4-811c-25712133c645.jpg)

I have problems when I put my harvesters to work using the courseplay.
Not sure yet if it's bug CP or some other mod that is interfering.
I use the "Veicle Switch" to move from one vehicle to another.

After much playing time the arm further increases! (Glass passes).

Harvesters: New Holland CR1090 (6X)
Tractor: New Holland T9 (6x)
Jad 6x Horsh (edited)
2x MAM to grain transport

As you can see in the images, the driver's arm begins to deform. Every time I jump from one machine to another, go to other vehicles, back, arm starts to increase until you reach that point.

I'll do more tests to see if you can be a mod that is interfering.

Giants physics and CP's lockdown #895
https://github.com/Courseplay/courseplay/issues/895

**Comment by Satissis** [comment]
I have never seen this before while using CP, so I'm pretty sure CP is not the cause of this.
For me it looks more like a Giants Derp but hey I can be totally wrong here, since I never had the issue.

**Comment by Karlshoj** [comment]
I have seen the same behavior. I´m quite sure it was when driving the Same Fortis 190 Rowtrack that the driver got disabled.

**Comment by MoslessNeo** [comment]
![farmingsimulator2015game 2015-03-21 02-01-46-66](https://cloud.githubusercontent.com/assets/6533809/6783468/afa7ef94-d158-11e4-9a69-b06d3c4c3914.jpg)

**Comment by AndyK70** [comment]
loool, sry for Offtopic, but that's really the biggest "Manta-Arm" I've ever seen. :grin: 
What's a Manta-Arm: [Manni s Manta Arm](https://www.flickr.com/photos/10983301@N06/2682940533)

**Comment by MoslessNeo** [comment]
I removed all the mods, just let the courseplay and VeicleGroup Swither. 
Maybe this mod that is generating this problem and not the CP.
Only open this topic to clarify my question, which still stands!

**Comment by Karlshoj** [comment]
I´m also using the VehicleGroupSwitcher and have not seen this behavior for long time. I think I was playing "Region of Texas" when I saw it. Could be it´s related to some mod maps??

**Comment by Maxcdr** [comment]
Experienced the same on Poebene15 map without mods except CP and VGS.

![fsscreen_2015_01_16_11_23_16](https://cloud.githubusercontent.com/assets/10348839/6798684/f16d68ca-d20f-11e4-924f-5df1a0e271b8.png)

**Comment by MoslessNeo** [comment]
To take the course, I will test the version of CP which is available in ModHoster.
I used the CP much time in FS15 and it never happened.
The CP has evolved enough, is more intelligent, a perfect job that gives life to the game.
We may have to wait for the new patch 1.3, it may be that this is resolved.

**Comment by MoslessNeo** [comment]
IMPORTANT: 
After many tests and observations, found the possible cause of the error:
The problem occurs when it is done bedside maneuver (final fields), when there is the animation arm "actor" turning the steering wheel. Over time, no more than 2x the arm begins to deform.
Now I do not understand why it.
Tested in other maps with 4x size and the problem persists.
I wonder if this is caused by CP or bug in the game.

**Comment by MoslessNeo** [comment]
After a series of exhaustive tests, I came to the conclusion that what generates the problem is not the objects on the map, but the game itself using the courseplay.
The tests were done using only a map with the basic objects, persp, sun, terrain, careerStartPoint, loadPlaces.
This is the final report for review:
- The problem in the course of a few minutes. The deformation may occur in any vehicle.
- This is in large fields
- It happens in maps as Loesshuegelland_V3.
- Were used modes "Fieldwork" and "Fertilizer and Seeding".

This is the direct download link for the map test:
http://1drv.ms/1y9sHim

Just have changed the cultivator_density, fruit_density and map01_dem.

**Comment by MoslessNeo** [comment]
Talking to other users, this problem occurs because the animation of the player's arm.
If it were possible to CP development team disable the animation of the actor's arm, this problem would be solved.
Many users place the  FS13 player in the FS15 mods, so the arm is not deformed.
Maybe the game's development team should give more consideration to CP.
I do not play since I discovered this problem, in my case, it is not feasible to play for the bug are very disruptive.
Therefore, it is not bug the CP. But the game itself. More precisely, compatibility problems.

I hope to have attention or at least the staff response.
Excellent work, please come back soon.
![farmingsimulator2015game 2015-06-23 19-18-17-64](https://cloud.githubusercontent.com/assets/6533809/8526809/3b1e14bc-23df-11e5-9493-59570a7a9d23.jpg)
![Uploading FarmingSimulator2015Game 2015-06-23 19-18-23-72.jpg…]()

**Comment by Satissis** [comment]
#1346
