### ISSUE TITLE
CP not scanning some maps

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#1114]
So ive found some maps are not being scanned by CP

These 2 for example

http://gamesmods.net/farming-simulator-2015/fs15-maps/47461-map-fazenda-planalto.html

http://gamesmods.net/farming-simulator-2015/fs15-maps/46814-agro-pomorze-map-v45-oryginal-by-daro44.html

Is there  problem or will CP not scan every map?

**Comment by kwguk** [comment]
Correction on my part.

It does scan the first map but not the second. However I think they are both buggy maps

**Comment by kwguk** [comment]
An example from Losshugeland map. CP hasn't scanned the whole field.

[URL=http://s1181.photobucket.com/user/kennywasgod/media/cp.png.html][IMG]http://i1181.photobucket.com/albums/x427/kennywasgod/cp.png[/IMG][/URL]

**Comment by Satissis** [comment]
#1346
