### ISSUE TITLE
Waiting for new waypoint

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#1116]
Im using ver;4.01.0101 and since ive started using it im getting a lot of the tractor waiting for a new waypoint and the combine seemingly stuck as you can see below

![2015-03-27_00001](https://cloud.githubusercontent.com/assets/11178621/6876130/4ad0c520-d4bc-11e4-9747-53bbddc81016.png)

**Comment by kwguk** [comment]
and again

![2015-03-27_00002](https://cloud.githubusercontent.com/assets/11178621/6876591/c58df644-d4c0-11e4-8e88-edc4f7dd23b0.png)

**Comment by ThomasGaertner** [comment]
sounds like #1065 . if you can replicate it , please with debug channel 4 active and post the log 
Thanks

**Comment by sootysax** [comment]
This also still happens to me - it always happens at the end of the row, where there is no room behind the combine for the 'waiting point' to be free.   The combine waits for the tractor to reach it's waiting point to start moving, and both vehicles sit in a stalemate.

What was wrong with the tractor just waiting in place where it finished unloading the combine like it used to do, instead of needing a different waiting point?

**Comment by MGO63** [comment]
I have had the same issue. 
Are you using AUTO COMBINE and/or AUTO TRACTOR?
If so try to to change from standard helper to alternate helper this solved the problem for me.
I was not using the mods but the mods were loaded in the game.
Remove the mods will also fix the problem.
Give it a try.

**Comment by sootysax** [comment]
this is using courseplay driven combines, but i do have both autocombine and auto tractor installed..  will try removing - but use them often, so hopefully they are not the issue

**Comment by MGO63** [comment]
You may try the following:
Enter a combine 
- open AUTO COMBINE 
- chose the alternative helper 
- close AUTO COMBINE
- change to a tractor
- open AUTO TRACTOR
- chose the alternative helper 
- close AUTO TRACTOR

There is no need to use the mods actively 
only change to the alternative helpers

Now try CP 
This worked for me

**Comment by kwguk** [comment]
What makes the combine move for me is if I turn the tractor CP off and on again which seems to release the combine to carry on.

Im using CP on combines as AC cant run multiple combines up and down

**Comment by kwguk** [comment]
For some reason this seems to have stopped happening. I've had no issues for nearly a week now.

Have I changed anything or done anything different? If I have I cant remember, which is no help I'm afraid.

**Comment by kwguk** [comment]
AH now forget what I said in my previous comment, the problem is back with vengeance and worse than ever. There seems to be no logic to it at all. It can go for hours working fine and then will do it near enough everytime you unload at the end of a row.

Tried the autocombine thing,made no difference. Im using all CP for combines and tractors.

**Comment by ThomasGaertner** [comment]
as I said before: debug channel 4 please, I have no crystal ball. 
when the work width is wide enough it will turn directly...

**Comment by kwguk** [comment]
Apologies I forgot about your request.r

How do I post my log and ill do it later today?

**Comment by ThomasGaertner** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by kwguk** [comment]
I've tried for 4 hours this afternoon to get game to replicate the fault and guess what, not once did it do it, not once. I tried different fields, combines, tractors but each time I pressed the no.4 in the bug channel the tractor would very obediently follow to its designated waypoint.

I'll keep trying.....
