### ISSUE TITLE
Enhancement: Allow Better Control of Turning Behavior for All Modes

### ISSUE THREAD

**Issue by mikeloeven** [Courseplay/courseplay#1118]
I would like to see a detailed control panel for turning behavior that allows you to take into account width of plows and cultivators and specify variables that will allow smooth turning of any tractor without jack knifing and the generation of diagonal furrows at the edges of the fields. A few ideas i would like to implement for this would be 

Turning Radius

 this will be set manually or can be calculated automatically taking the angle of any attached machines into account 

Meters allowed past field edge 

This allows you to specifically set how far off the edge of the field the AI can go and should be used by the AI to avoid hitting trees and fences by forcing them to use multipoint turns for equipment with a large turning radius rather than simply going in a wide loop or simple two point turn and getting stuck.

Align Tool 

A simple check box but what this will do is force the AI to make small multipoint turns until the tool is aligned straight before lowering it and continuing down the next row eliminating the diagonal furrows or missing patches

**Comment by Mopar** [comment]
It has been brought up before, they are currently working on them, and to be honest, I can not wait, lol.

https://github.com/Courseplay/courseplay/issues/1050

**Comment by mikeloeven** [comment]
Though i think what is really needed is the ability to set how far apart the way points are placed and the frequency of said way points. especially when backing up with a trailer wish i could have it record more
precisely because after about 15 attempts to back in to the shed the script keeps missing changes between left and right and generally turning two shallow so the adjustments to the trailers alignment simple dont translate and it keeps jackknifing before it gets into the shed :/

**Comment by Satissis** [comment]
@mikeloeven don't mix issues.
About reversing with trailer, did you record the route without the trailer and described in the manual ?

**Comment by mikeloeven** [comment]
Not really sure its mixing issues as the way-point resolution idea was an idea i had to improve turning and allow more detailed recording of complex turning maneuvers and the trailer reversing issue is also related to how the AI handles turning.

but I have tried recording the trailer path multiple times both with and without the trailer attached the results are pretty much the same. The issue is that the path does not record very small turns like the kind you make to center said trailer 

I tried the same procedure using my programmable keyboard recording a key-press macro and when played back the trailer backed in perfectly so most of the turning issues seem to be related to the game trying to reduce the number of way-points by essentially smoothing the overall path

**Comment by Igi-PL** [comment]
@mikeloeven I also have problems with reversing, but now it is working for me - it was my fault.
Consider three things:
1. Record witout trailer.
2. Reverse do not work if trailer is empty.
3. Reverse do not work in all modes.

**Comment by mikeloeven** [comment]
Another addition to turning should be the addition of a two point turn when doing headlands essentially the combine should go into the corner than reverse before turning into the main row which would be a very simple procedure and eliminate corner crops

**Comment by Satissis** [comment]
Dude, we are already working on a totally new system, which is WP based and all the ideas you are having, is already either done or in my todo list :)

**Comment by Maxcdr** [comment]
@Igi-PL
>Reverse do not work if trailer is empty.

Works fine for me with full and empty trailer...

**Comment by mikeloeven** [comment]
I guess ill close this one two and just remember to use the DEV build in the future
