### ISSUE TITLE
Mode 3 Traffic Avoidance

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1119]
Trying to use an overloader on a large field with 3 combines running, and finding that it is sitting in traffic quite a lot.   Does the mode 3 employ the same traffic avoidance as mode 2 does?   I find that it will run directly into another combine, or the combine it just unloaded, especially on the way to the first waypoint to unload into the semitrailer.

**Comment by ThomasGaertner** [comment]
it should be active on the way to the combine, while turning after unloading and on the way to the unloading course... is it still valid ?

**Comment by ThomasGaertner** [comment]
closed to keep issues clean
