### ISSUE TITLE
Mode 2 or 3 - Traffic with combine

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1120]
Noticing that with most of the traffic with the combine when unloading, it's a situation where there is barely a collision with the combine trying to line up with the loading pipe..   90% of the time, all I have to do is stop and restart the route without steering and it will continue to move under the pipe, because there really wasn't a collision at all.   Perhaps in mode 2 or 3, when there is a traffic situation, CP could simply stop and restart the course - or perhaps reverse just 1 meter and retry moving forward.   It wouldn't work in all situations (#1119 where it drives straight into another combine on it's way to the unload route in mode 3), but it would help with most of the issues which I find happen when the unloading vehicle is caught in traffic trying to get beside the combine to unload.

**Comment by Satissis** [comment]
#1346
