### ISSUE TITLE
Not square fields

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#1121]
How do I stop the tractor ignoring the field boundary and just proceeding regardless?

![2015-03-29_00001](https://cloud.githubusercontent.com/assets/11178621/6887399/3c682654-d656-11e4-856e-e7494acea1b1.png)

**Comment by Satissis** [comment]
You can't right now.
We are currently working on a new field generating system, that should handle this allot bettter.

**Comment by kwguk** [comment]
Good to know mate thanks
