### ISSUE TITLE
Grain Transport Mode is not Loading From Silo

### ISSUE THREAD

**Issue by mikeloeven** [Courseplay/courseplay#1122]
I set up a grain transport path to sell my canola crop. the path runs from my silo to the windmill with the load option set to canola, i drove in a loop between the silo's loading pipe to the mill's unload trigger and than back to the silo's loading pipe i checked the path and the debug information and it appears to be configured properly. 

For some reason when load the path, The truck keeps driving in an endless loop and will not fill from the silo at the start

**Comment by Satissis** [comment]
Please read and follow this: [How to provide a nice and sexy bug report](https://github.com/Courseplay/courseplay/wiki), since it makes it easier for us to figure out what is wrong.

Without the above info, I'm guessing you don't use the developing version and if you do, then you are using an mod trailer that is poorly made.

**Comment by mikeloeven** [comment]
Version 4.01

log is here 
http://pastebin.com/BKNL9EcE

**Comment by gui7545** [comment]
Which trailer are you using ? ItRunner_Pack ? This pack is working only with developer version .
See the end of this page: http://courseplay.github.io/courseplay/en/installation/index.html

**Comment by mikeloeven** [comment]
Here is the list of mods that make up my trailer 

Super Man
http://www.2015mods.com/super-man-v1-1/

Krampe bss900 (Setter Frame Dolly)
http://www.modhub.us/farming-simulator-2015-mods/krampe-3achser-for-setting-frame-v1-0/

Brantner 3 Seitenkipper AR 5.4 (Setter Frame Tipper)
http://www.modhoster.de/mods/ar_kontainer_und_mulden

Semi Truck Ball Hitch Adapter
http://www.modhoster.com/mods/kupplung-fur-krone-big-x

**Comment by mikeloeven** [comment]
the Super Man has a Setter on it's chassis than the ball hitch adapter connects to the dolly which has another setter on it.

the thing is that in combi mode it works flawlessly emptying the combine and dumping at the silo. 
I also had the same issue when testing it with two other trucks one had with a built in tipper no trailers or anything. I am wondering if it might be a missing map trigger issue 

The map i am using is here
http://mods2015.com/frisian-march-map-v-1-8/

hoping that will be enough to reproduce

**Comment by mikeloeven** [comment]
Ok so i just tested the Dev build and now it stops at the loading pipe but it is off center with the trailer and still wont fill. The fix for this is pretty easy all you need to do is enable the vertical and horizontal offset settings you see in combi mode to grain transport mode so you can adjust this and have the same course run by multiple different trucks

**Comment by Satissis** [comment]
hmm that's actually not an bad idea, thou we would have to make some small changes to make it work, since normally the vertical and horizontal offset if only active while in field area. I have an idea for it, but I can't say when I'll be able to implement it.

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
