### ISSUE TITLE
Possible Integer Overflow in V4.01    .0101.dev

### ISSUE THREAD

**Issue by mikeloeven** [Courseplay/courseplay#1123]
Possible Integer Overflow in V4.01    .0101.dev

Using Borgault IAD600 v3.0 Courseplay will not automatically lower the implement however it will unfold and turn on. Additionally when set to run the course the tractor will sometimes just stop moving and the turn radius will be displayed as negative maxint 64.

this eventually causes the client to stop responding the only fix is to load the save make sure that the seeder is detached from the tractor and save the game before restarting. Issue recurs again intermittently

The Log File is Here
(Paste bin was giving me crap about filesize) 
ftp://BugReports:null@loevendesktop.dyndns.info/Borgault _Seeder_Issue.txt

The Seeder can be found here 
http://www.modhoster.de/mods/bourgault-iad600

**Comment by ThomasGaertner** [comment]
I just tested the mod. here the results:
1.) the  turn radius doesn't matter in mode 4 so we can ignore it
2.) the errors in the log are the result of a unlucky modding. There is a function setRidgeMarker() but no ridgemarker. There are wrong set indices for the component joints. This errors could be suppressed by setting the ridge marker setting to manual in the HUD
3.) the not lowering and raising is also a result of the modding, there is a function called setAIImplementsMoveDown() which we use and doesn't exist in this mod.
So its up to the modder to make it properly if it is supposed to be used be CP

**Comment by benjoglove** [comment]
Were would we place the setAIImplementsMoveDown() script. Have a seeder that wont lower in courseplay so looking for a solution and this may be it??

**Comment by benjoglove** [comment]
mikeloeven did you fix this issue?

**Comment by ThomasGaertner** [comment]
#1346
