### ISSUE TITLE
Feature Request: Perform Macro Waypoint 

### ISSUE THREAD

**Issue by mikeloeven** [Courseplay/courseplay#1124]
I would like to see a way point that allows the user to record a sequence of keystrokes or analogue input from a joystick and simply have those commands played back with little to no error checking when the way point is reached. 

This would be useful for precise operations that a way-point path does not have the sensitivity to perform such as more complicated loader operation where a simple series or preset hydraulics positions will not work, or for backing up and unloading trailers to peaceable heaps or other storage locations that may not have valid map triggers for dumping. Additionally, some harvesters require a keystroke to begin overloading which course-play sometimes misses but a macro added before the wait point could force it to trigger. 

but in all enabling the recording and playback of raw input macros would open course-play up to much more precise playback of manual operation.

**Comment by ThomasGaertner** [comment]
what ??

**Comment by mikeloeven** [comment]
Basically i am asking for the ability to record and playback a series of keystrokes when the machine reaches a specific way-point

**Comment by PromGames** [comment]
Keystroke recording in macro format? Too open.
Maybe will be better to choose from a few Proposed input bindings from CP. This will standardise the program and will give an easy approach.

**Comment by mikeloeven** [comment]
To be honest the reason i wanted this was mostly for the unloading of trailers that will only empty from the back currently all attempts to set reverse courses in the unloading loop result in the trailer ignoring the unload trigger or simply skipping the reverse path all together. a "dumb" macro would get the job done because it would not get hung up with the invalid path errors or missing triggers as long as you timed the keystrokes correctly

**Comment by Satissis** [comment]
#1346
