### ISSUE TITLE
Refueling

### ISSUE THREAD

**Issue by Baldrick101** [Courseplay/courseplay#1126]
Hi,

In FS2013 Courseplay used to refuel to 100% when passing a gasoline tank and below the "needs to refuel" threshold. 
Now, when I plot a course past a gasoline tank on my way back to the farm it only refuels to just above the "needs to refuel" threshold, then continues course. 
Is this intentional?

I find the FS2013 behavior preferable and also more logical - I always plotted a trip past a gas tank for trucks selling grain and seeders picking up seed for example. As it stands on larger maps I run out of fuel when seeding after refueling to just above threshold. 

Thanks!

**Comment by ian898** [comment]
I have not had this problem my tractors seem to refill to 100% once they pass a fuel tank and I am using the dev .0101

Regards

Ian

**Comment by Karlshoj** [comment]
I´m also seeing different fill levels. Could it be coursed by my installed zzz_VariableCapacity mod?

**Comment by Baldrick101** [comment]
I am on dev 0101 as well and I just ran out of gas seeding with a stock sower and tractor.

**Comment by Baldrick101** [comment]
In case it helps, just ran a fastrac with a 900 tipper past a fuel point. It was down to 96 fuel, started refueling as expected, stopped at 251 of 619 and carried on.

**Comment by Satissis** [comment]
#1346

**Comment by ThomasGaertner** [comment]
is fixed now isn't it ?

**Comment by lcc1211** [comment]
I think this should be closed now.  All my vehicles now refuel completely if they drive within range of the trigger for fueling.

**Comment by Satissis** [comment]
Will take that as an yes.
Closing the issue
