### ISSUE TITLE
New Holland TC5.90 stuck in loop

### ISSUE THREAD

**Issue by Deathnerd** [Courseplay/courseplay#1127]
Probably already been reported, but I couldn't find it. This bug is actually pretty amusing.

On the Bjornholm map, have a New Holland TC5.90 Equipped with a Varifeed 18ft header start field work on Field 28, starting in the North West corner, heading east, with one path of headland going clockwise. Proceed to do Calculus homework (not required but it's an interesting way to pass the time). Come back after a particularly frustrating bout with inverse trig derivatives and find that the tractor is making loops around waypoint 479. Chuckle and shake your head.

Edit: Then post issue to github in a witty format and forget you didn't follow the guidelines. I'll reformat when I have a bit more time

**Comment by staanla** [comment]
That is not necessarily a problem with courseplay per se. It could also be because of your route. Do you have this issue frequently on this particular rout and always on the same waypoint?
Then it might help to slow down the vehicle a bit.

**Comment by ThomasGaertner** [comment]
#1346
