### ISSUE TITLE
Tractor looping trying to drive behind harvester

### ISSUE THREAD

**Issue by Baldrick101** [Courseplay/courseplay#1128]
Hi,

It happens every now and then a tractor with a tipper gets stuck driving circles on the field while on its way to drive behind a harvester. It literally keeps doing donuts until I stop the course, drive it out a bit in a straight line any direction, then start the course with "nearest waypoint" selected. It will then proceed to turn correctly and head straight for the harvester as expected. I'm assuming this happens when the tractor somehow tries to get on a waypoint for which it's positioned in such a way that the turning circle to get there is too large.

**Comment by ThomasGaertner** [comment]
no, its when you set the turning circle lower than possible . did you change it manually ?

**Comment by Baldrick101** [comment]
Hmm, didn't think so but now I'm starting to doubt myself :) Will do some tests. Thanks!

**Comment by Baldrick101** [comment]
The issue just occurred again. Tractor is a Case Magnum 380, tipper a agroliner TAW 30 and the harvester the new holland CR10.90 with 45ft draper. 
Tractor is on his way to drive to harvester but is in fact very far out still, about 250 meters or so. It just keep turning donuts. 
Tractor settings:

Turning circle (auto) 8m
Vertical offset: auto
Start at 30% 
drive on at 90%
Side offset - manual 10.5m

Stopped the course, manually upped the turning circle to an arbitrary 11m and off it went.

**Comment by Karlshoj** [comment]
I would set the turning circle to 15m

**Comment by Baldrick101** [comment]
If that is the case, wouldn't it be better to set a more conservative turning circle automatically?

**Comment by Karlshoj** [comment]
I can´t be sure if thats the case just that it seems so to me.
If it´s the case CP could evaluate which one is the highest figure and use that one??

**Comment by kwguk** [comment]
I have the same issue occasionally when the trac and trailer have offloaded they turn away from the combine heading for the next waypoint, but it then gets stuck in a tight continuos circle.

I rectified it by manually increasing the turning circle. But I've had to do for all tractors every time I boot the game up.

**Comment by Baldrick101** [comment]
I just had a Case Magnum 380 pulling a TAW 30 doing donuts, with its turning circle set to 14. 

Stop course, start course took it out of the loop as it drove straight to offloading a harvester.

**Comment by ThomasGaertner** [comment]
#1346
