### ISSUE TITLE
[Question] : Not sure of a forum so figured ask here.

### ISSUE THREAD

**Issue by Malaras** [Courseplay/courseplay#1129]
Any Idea when MP version going to be reactivated? I started using courseplay maybe a week before i got a MP server so missing out on allot of fun with courseplay :)

Thanks,

**Comment by Satissis** [comment]
Nop there is no release date on when the MP will be activated again.

**Comment by Malaras** [comment]
Got another question, How does one transport to a silo and unload? I did it before but forgot how. Been like a month since i did it.

Unloading into semi , then want semi to take to farm and unload. and come back to wood cutting area. i thought it was transport, but that didn't work. It didn't unload and their is not option what to haul woodchips etc, and what % to leave and all that.

**Comment by Satissis** [comment]
There are plenty tutorials on YouTube about that ;) or look in the manual, which is linked on the main page.
