### ISSUE TITLE
Mode 2, Mode 3 Issue With Offloading Vehicle When Player Driving Combine

### ISSUE THREAD

**Issue by FSFiestel** [Courseplay/courseplay#1130]
This issue only seems to happen when the player drives the combine (I always drive the combine and rarely hire a worker to drive the combine).  The issue does not seem appear when there is a hired worker driving the combine.

The issue has been apparent for quite a few versions now that while using Mode 2 and Mode 3 and the player drives the combine, the offloading vehicle waits for the combine to clear the area and then drives straight for about 200 feet and then stops.  Unless you have offloaded in the middle of the field, this causes an issue the closer you are to the edge of the field.  If you are at the edge of the field, there always seems to be some obstacle within 200 feet - trees, fences, rocks, cliffs, etc., which means you have to stop get the worker unstuck.  This does not seem to happen if you hire a worker to drive the combine, if the offloading vehicle is at the edge of the field, it seems to make a 180 degree turn back into the field and stop.

I think the solution should be:
1) Once the offloading vehicle offloads the combine and is not parked in the fruit (ie. if pathfinding is on) that it should just stay where it is and not move until called to offload the combine again.
2) If the offloading vehicle is in the fruit (ie. pathfinding is off), then it should do a quick 180 out of the fruit and stop.
3) If the offloading vehicle is at the edge of the field after the offload, then it should do a 180 turn away from the fruit and stop inside the field border.

I'm surprised that no one else seems to have come across this, but I figured I better mention it.

Thanks.

**Comment by ThomasGaertner** [comment]
just tested and worked fine for me. please test again with debug channel 4 active and post the log

**Comment by FSFiestel** [comment]
Hi Thomas,

Here is my log file.  I couldn't figure out how to attach the file itself, sorry.  I was at the southeast edge of field 23 in Bjornholm facing south during the offload.  After the combine was unloaded and I moved away, the tractor drove south for about 100 feet or so and stopped.  If I had been further west, it would have driven straight into the fence.  If you wish, I can attach a couple screen shots of where it offloaded the combine and then where it drove to.

GIANTS Engine Runtime 6.0.2 64bit (Build Date: Dec  8 2014)
Copyright (c) 2008-2014, GIANTS Software GmbH (giants-software.com), All Rights Reserved.
Copyright (c) 2003-2014, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: FarmingSimulator2015
Main System
  CPU: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
  Memory: 16322 MB
  OS: Windows NT 6.1 64-bit
Physics System
  Version: 5.9.4
  Thread(s): 2
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick enabled
  Force Feedback disabled
  Name: Xbox 360 Controller
    Number of Axes: 5
    Number of Buttons: 14
Sound System
  Driver: OpenAL
  Version: 1.1
  Device:  Generic Software
  Max. sources: 256
Render System
  Driver: OpenGL
  Card Vendor: NVIDIA Corporation
  Renderer: GeForce GTX 780/PCIe/SSE2
  Version: 4.5.0 NVIDIA 347.88
  Shader Version: 4.50 NVIDIA
    max_texture_layers: 16
    OpenGL initialization successful
Hardware Profile
  Level: Very High (forced)
  View Distance Factor: 1.300000
  Shadow Quality: 2.000000
  Skip Mipmaps: 0
  LOD Distance Factor: 1.300000
  Terrain LOD Distance Factor: 2.000000
  Foliage View Distance Factor: 1.600000
  Volume Mesh Tessellation Factor: 0.750000
  Tyre Tracks Segments Factor: 4.000000
Farming Simulator 15
  Version: 1.2.0.0 1.2 RC6
  Available Languages: en fr es it nl pt
  Language: en
Game vehicle types loaded
Mod directory: C:/Users/Jim/Documents/My Games/FarmingSimulator2015/mods/
Load dlc: pdlc_jcbPack
Load mod: AnimalHUDv1_1
Load mod: Baler_add_grass
Load mod: BaleStorage_2K
Load mod: ballenlager_ModLandNet
Load mod: Bergziege_14280_Prototyp_A
Load mod: Bergziege_14280_Prototyp_A_Color
Load mod: Bergziege_16410_Prototyp_B
Load mod: Bergziege_16410_Prototyp_B_Color
Load mod: Bergziege_16540_Prototyp_C
Load mod: Bergziege_16540_Prototyp_C_Color
Load mod: Bergziege_Prototyp_2_Original_Interior
Load mod: BMWX5_15_ModLandNet
Load mod: BrantnerDPW18000
Load mod: Brantner_Seed
Load mod: Broger_Drift_Pickup
Load mod: CaseIH_Magnum_HighAttacher
Load mod: ChevroletC101966
Load mod: Conveyer2_1_5b
Load mod: ConveyorPackv3_3
Load mod: courseplay0101
Load mod: DDR_Tanke_Plazierbar
Load mod: DeutzAgroStar661_Forst
Load mod: Dodge_Ram_Service_v1_1
Load mod: Dodge_Ram_v1_1
Load mod: flatbedTrailer
Load mod: Fliegl_Semitrailer
Load mod: Fliegl_Semitrailer_Wide
Load mod: FL_Log_Skidder
Load mod: FollowMe3_0
Load mod: Forst_Deutz661Agrostar
Load mod: Forst_Deutz_TTV_7250_v1_0
Load mod: Frontloader_Straw_Grass_Tools
Load mod: FS15_amazonePantera
Load mod: FS15_brantnerE8041Rungen1
Load mod: FS15_flieglVFW10600
Load mod: FS15_JCBSkidsteerAdapter
Load mod: FS15_kirovetsK700A
Load mod: FS15_KRAZ_5133N
Load mod: FS15_kuhnSitera3000
Load mod: FS15_kuhnVB2190
Load mod: FS15_lamborghiniNitro120
Load mod: FS15_marshallBaleTrailerBC25
Load mod: FS15_marshallPack
Load mod: FS15_NewHollandBB1290
Load mod: FS15_newhollandT9565ST
Load mod: FS15_placeableSheds_MW_mailman
Load mod: FS15_poettingerVitasem302ADirectSeeding
Load mod: FS15_vaederstadPack
Load mod: Fuel_Proof
Load mod: G65_AMG_6x6
Load mod: Gekko_Utility_Vehicle
Load mod: GewichtliebherrTL432_71
Load mod: GrimmeKS75_4
Load mod: Grimme_Hen_245_Magnum
Load mod: HarvesterBirken
Load mod: HUD_Hider_v1_15b
Load mod: Inspector2
Load mod: Jenz_Crusher_Mammut_II_v1_0
Load mod: Jenz_Crusher_Mammut_V1
Load mod: Jenz_Crusher_Titan_V1
Load mod: Jenz_Hem_Back_v3_0
Load mod: Kirovez_AgroPack_V2_1_ModLandNet
Load mod: lamborghiniMach250VRT
Load mod: LizardPickupRemakeV2
Load mod: LS15SMuldeMAN_ModLandNet
Load mod: LS15_JD548_v1
Load mod: LS15_kroneBigM500_V1
Load mod: m1070APackage
Load mod: Mammut_FrontLoader_HLP240_V1_2_Coloredit
Load mod: Mammut_LogFork_V1_2_Coloredit
Load mod: Maxwell2KWeight
Load mod: Mercedes_E350_1_1
Load mod: Mobile_Ramp
Load mod: newHollandBB1290
Load mod: NewHolland_Frontloader_750TL
Load mod: OEB_BigM500
Load mod: OlbertSW300
Load mod: Pickup_5verV2
Load mod: placeableHalls
Load mod: placeable_fertilizerTank_LS15
Load mod: placeable_gasTank_LS15
Load mod: placeable_seedPallets_LS15
Load mod: placeable_strawPowerPlant
Load mod: QuickCamera2_1_0
Load mod: rampa
Load mod: SAN_KrAZ255B1
Load mod: SauterEquipment
Load mod: Sheriff_Pickup_v1_0
Load mod: Sheriff_Pickup_v2_0
Load mod: showtime15v2
Load mod: Stoll_Frontloader_FZ30
Load mod: TA77
Load mod: Tractor4_T_150K
Load mod: truck
Load mod: vd_Balefork_standard
Load mod: Verladerampe1
Load mod: Verladerampe2
Load mod: VWKaefer1966
Load mod: VWKaefer1973_ModLandNet
Load mod: ZZZ_autoOffTurnSignals
Load mod: ZZZ_BeaconLights
Load mod: ZZZ_CameraMod
Error: Not all prerequisites of specialization aiCombine are fulfilled
  Register vehicle type: BrantnerDPW18000.dpw18000
  Register vehicle type: CaseIH_Magnum_HighAttacher.CASE_Trailer_Attacher
  Register vehicle type: ChevroletC101966.ChevroletC101966
  Register vehicle type: Conveyer2_1_5b.FoerderBand
  Register vehicle type: ConveyorPackv3_3.NewConveyor
  Register vehicle type: ConveyorPackv3_3.FConveyor
  Register vehicle type: ConveyorPackv3_3.TConveyor
### Courseplay: initialized 38/38 files (v4.01.0101)
    ******************************************* WARNING *******************************************
    * You are using a development version of Courseplay, which may and will contain errors, bugs, *
    * mistakes and unfinished code. Chances are your computer will explode when using it. Twice.  *
    * If you have no idea what "beta", "alpha", or "developer" means and entails, remove this     *
    * version of Courseplay immediately. The Courseplay team will not take any responsibility for *
    * crop destroyed, savegames deleted or baby pandas killed.                                    *
    ***********************************************************************************************
### Courseplay: installed into 21 vehicles
  Register vehicle type: flatbedTrailer.flatbedTrailer
  Register vehicle type: FL_Log_Skidder.FL_Log_Skidder
Script loaded: FollowMe.lua (v2.1.0)
  Register vehicle type: FS15_amazonePantera.amzonePantera
  Register vehicle type: FS15_kirovetsK700A.KirovetsK700A
  Register vehicle type: FS15_kirovetsK700A.BuyableTwinWheels
  Register vehicle type: FS15_marshallPack.rotorManureSpreader
  Register vehicle type: FS15_marshallPack.manureSpreaderPlaneMover
  Register vehicle type: FS15_NewHollandBB1290.newHollandBB1290
  Register vehicle type: FS15_newhollandT9565ST.NHT9SMARTTRAX
  Register vehicle type: Fuel_Proof.fuelproof
HUD Hider by Clod-http://forum.tractor-italia.net loaded
  Register vehicle type: Jenz_Crusher_Mammut_II_v1_0.Jenz_Crusher_Mammut
  Register vehicle type: Jenz_Crusher_Mammut_V1.Jenz_Crusher_Mammut
  Register vehicle type: Jenz_Crusher_Titan_V1.Jenz_Crusher
  Register vehicle type: Kirovez_AgroPack_V2_1_ModLandNet.Kirovez
  Register vehicle type: LizardPickupRemakeV2.PickUpFire
  Register vehicle type: LS15_JD548_v1.JD548H
  Register vehicle type: LS15_kroneBigM500_V1.kronebig500m
  Register vehicle type: Mobile_Ramp.ramp
  Register vehicle type: Mobile_Ramp.drawbar
  Register vehicle type: OEB_BigM500.bigM_500
  Register vehicle type: OlbertSW300.OlbertSW300
  Register vehicle type: Pickup_5verV2.PickUpFire
Warning: missing category value in store item modDesc.storeItems.storeItem(0)
Warning: missing category value in store item modDesc.storeItems.storeItem(1)
Warning: missing category value in store item modDesc.storeItems.storeItem(2)
Warning: missing category value in store item modDesc.storeItems.storeItem(3)
Script loaded: QuickCamera.lua (v2.1.0)
  Register vehicle type: SAN_KrAZ255B1.KrAZ
  Register vehicle type: SauterEquipment.SauterFastCoupler
  Register vehicle type: SauterEquipment.SauterRailAttachment
  Register vehicle type: SauterEquipment.SauterBumper
  Register vehicle type: Sheriff_Pickup_v1_0.PickUpSheriff
  Register vehicle type: Sheriff_Pickup_v2_0.PickUpSheriff
Script loaded: showtime.lua (v2.0)
  Register vehicle type: TA77.transam
  Register vehicle type: Tractor4_T_150K.T150K
  Register vehicle type: truck.PickUpFire
  Register vehicle type: vd_Balefork_standard.baleFork
  Register vehicle type: VWKaefer1966.kaefer66
  Register vehicle type: VWKaefer1973_ModLandNet.kaefer73
--- faster Camera movement Mod loaded --- (by upsidedown)
data/sky/sky_day_night.i3d (2.71 ms)
data/sky/rain.i3d (0.47 ms)
data/sky/hail.i3d (0.41 ms)
data/sky/dust.i3d (0.38 ms)
data/maps/map01.i3d (5817.94 ms)
## Courseplay: setting up signs
C:/Users/Jim/Documents/My Games/FarmingSimulator2015/mods//courseplay0101/img/signs/normal.i3d (0.35 ms)
C:/Users/Jim/Documents/My Games/FarmingSimulator2015/mods//courseplay0101/img/signs/cross.i3d (0.46 ms)
C:/Users/Jim/Documents/My Games/FarmingSimulator2015/mods//courseplay0101/img/signs/wait.i3d (0.62 ms)
C:/Users/Jim/Documents/My Games/FarmingSimulator2015/mods//courseplay0101/img/signs/start.i3d (0.59 ms)
C:/Users/Jim/Documents/My Games/FarmingSimulator2015/mods//courseplay0101/img/signs/stop.i3d (0.57 ms)
## Courseplay: setting up fields (basic)
## Courseplay: loading settings from "courseplay.xml"
## Courseplay: setting up hud
## Courseplay: setting up debug channels
## Courseplay: setting up globalInfoText
## Courseplay: loading courses and folders from "courseplay.xml"
--- loading Gasstation_Placable --- (by LS-Pitstop)
--- loading PickUpFire mod V1.0 --- (by Dream aka RC-Devil)
--- loading PickUpFire mod V1.0 --- (by Dream aka RC-Devil)
--- loading PickUp Sheriff mod V1.0 --- (by 112TEC|schwaki)
--- loading PickUp Sheriff mod V2 --- (by 112TEC|schwaki)
--- loading PickUpFire mod V1.0 --- (by Dream aka RC-Devil)
--- loading autoOffTurnSignals mod V1.0 (by mLine)---
data/vehicles/tools/koeckerling/koeckerlingTrio300M.i3d (15.34 ms)
data/vehicles/particleAnimations/koeckerling/koeckerlingTrio300M.i3d (4.64 ms)
data/vehicles/steerable/deutz/deutzAgroStar661.i3d (25.00 ms)
dataS2/character/player/player.i3d (175.51 ms)
data/vehicles/tools/poettinger/poettingerVitasem302A.i3d (14.25 ms)
data/vehicles/particleAnimations/poettinger/poettingerVitasem302A.i3d (0.61 ms)
data/vehicles/tools/amazone/amazoneZAM1501.i3d (12.80 ms)
data/vehicles/tools/suer/suerSB1000.i3d (2.45 ms)
data/vehicles/tools/damcon/damconPL75.i3d (11.37 ms)
data/vehicles/particleAnimations/damcon/damconPL75.i3d (0.57 ms)
data/vehicles/tools/fsi/fsiST65T.i3d (3.76 ms)
data/vehicles/trailers/brantner/brantnerE8041.i3d (5.57 ms)
C:/Users/Jim/Documents/My Games/FarmingSimulator2015/mods//FS15_kuhnSitera3000/kuhnSitera3000.i3d (87.70 ms)
data/vehicles/tools/suer/suerSB1600.i3d (0.45 ms)
data/vehicles/tools/kuhn/kuhnVariMaster153.i3d (13.36 ms)
data/vehicles/particleAnimations/kuhn/kuhnVariMaster153.i3d (0.62 ms)
data/vehicles/tools/kuhn/kuhnFC3525F.i3d (11.50 ms)
data/vehicles/frontLoaders/stoll/stollFrontLoaderFZ.i3d (7.32 ms)
data/vehicles/frontLoaders/stoll/stollToolShovel.i3d (9.92 ms)
data/vehicles/trailers/stepa/stepaFHL13AK.i3d (15.25 ms)
data/vehicles/balers/newHolland/newHollandBB1290.i3d (13.59 ms)
data/maps/models/objects/squarebales/baleHay240.i3d (1.28 ms)
data/vehicles/frontLoaders/stoll/stollToolPalletFork.i3d (0.82 ms)
data/vehicles/balers/newHolland/newHollandRollBelt150.i3d (15.05 ms)
data/vehicles/steerable/man/man22s.i3d (38.89 ms)
data/vehicles/trailers/krampe/krampeSB3060.i3d (14.03 ms)
data/vehicles/tools/poettinger/poettingerHit1214T.i3d (13.70 ms)
data/vehicles/tools/poettinger/poettingerTop1252.i3d (17.10 ms)
data/vehicles/trailers/kuhn/kuhnPrimor3570.i3d (6.59 ms)
data/vehicles/trailers/kuhn/kuhnProfile1880.i3d (6.39 ms)
data/vehicles/frontLoaders/stoll/stollToolBaleFork.i3d (0.60 ms)
C:/Users/Jim/Documents/My Games/FarmingSimulator2015/mods//BrantnerDPW18000/dpw18000.i3d (68.40 ms)
C:/Users/Jim/Documents/My Games/FarmingSimulator2015/mods//FS15_marshallBaleTrailerBC25/BC25.i3d (48.63 ms)
data/vehicles/steerable/newHolland/newHollandT6160.i3d (27.33 ms)
data/vehicles/tools/kuhn/kuhnFC10030.i3d (12.19 ms)
data/vehicles/steerable/huerlimann/huerlimannXM4Ti.i3d (25.02 ms)
data/vehicles/steerable/cars/piQup.i3d (9.30 ms)
data/vehicles/trailers/fuelTrailer/fuelTrailer.i3d (9.13 ms)
data/vehicles/trailers/waterTrailer/waterTrailer.i3d (9.12 ms)
data/vehicles/steerable/lamborghini/Mach230VRT.i3d (24.57 ms)
data/vehicles/frontLoaders/stoll/stollToolManureFork.i3d (0.62 ms)
data/vehicles/frontLoaders/stoll/stollToolRoundBaleFork.i3d (0.57 ms)
data/vehicles/tools/vaederstad/vaederstadRapidA600S.i3d (24.10 ms)
data/vehicles/particleAnimations/vaederstad/vaederstadRapidA600S.i3d (0.69 ms)
data/vehicles/trailers/fliegl/flieglASS2101.i3d (12.93 ms)
data/vehicles/trailers/horsch/horschTitan34UW.i3d (10.30 ms)
data/vehicles/trailers/fliegl/flieglDolly.i3d (3.37 ms)
data/vehicles/trailers/bergmann/bergmannCarex38S.i3d (13.40 ms)
data/vehicles/tools/vogelNoot/vogelNootTerraDisc600.i3d (13.57 ms)
data/vehicles/particleAnimations/vogelNoot/vogelNootTerraDisc600.i3d (0.68 ms)
data/vehicles/tools/horsch/horschMaestro12SW.i3d (14.15 ms)
data/vehicles/particleAnimations/horsch/horschMaestro12SW.i3d (0.40 ms)
data/vehicles/trailers/jenz/jenzHem583.i3d (22.42 ms)
data/vehicles/frontLoaders/stoll/stollToolLogFork.i3d (0.74 ms)
data/vehicles/cutters/poettinger/poettingerMex5.i3d (11.55 ms)
C:/Users/Jim/Documents/My Games/FarmingSimulator2015/mods//FS15_kirovetsK700A/kirovets/KirovetsK700A.i3d (103.87 ms)
C:/Users/Jim/Documents/My Games/FarmingSimulator2015/mods//FS15_kirovetsK700A/kirovets/KirovetsK700A_TwinWheels.i3d (6.87 ms)
data/vehicles/steerable/caseIH/caseIH7130.i3d (38.66 ms)
data/vehicles/cutters/caseIH/caseIH3020Cutter.i3d (14.02 ms)
data/vehicles/trailers/thueringerAgrar/thueringerAgrarLeguan40.i3d (5.27 ms)
C:/Users/Jim/Documents/My Games/FarmingSimulator2015/pdlc//jcbPack/jcb/jcbShovel.i3d (98.14 ms)
C:/Users/Jim/Documents/My Games/FarmingSimulator2015/pdlc//jcbPack/jcb/jcbManureFork.i3d (1.75 ms)
C:/Users/Jim/Documents/My Games/FarmingSimulator2015/pdlc//jcbPack/jcb/jcb260.i3d (211.28 ms)
## Courseplay: JCB 260 eco: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
data/maps/models/objects/squarebales/baleStraw240.i3d (0.67 ms)
data/maps/models/objects/roundbales/roundbaleStraw_w112_d130.i3d (2.59 ms)
data/placeables/beehive/beehive.i3d (8.30 ms)
C:/Users/Jim/Documents/My Games/FarmingSimulator2015/mods//placeable_gasTank_LS15/gasTankPlaceable.i3d (4.33 ms)
data/maps/models/objects/pallets/woolPallet.i3d (0.90 ms)
data/placeables/greenhouses/greenhouse02.i3d (26.31 ms)
data/placeables/highPressureWasher/kaercher/kaercherHDS918-4M.i3d (11.65 ms)
data/placeables/greenhouses/greenhouse01.i3d (13.01 ms)
data/placeables/solarCollector/solarCollector.i3d (8.80 ms)
data/maps/models/natural/trees/treePine17m.i3d (0.90 ms)
data/maps/models/natural/trees/treePine33m.i3d (1.01 ms)
data/maps/models/natural/trees/treePine27m.i3d (1.04 ms)
dataS/character/player/playerCCT.i3d (4.43 ms)
data/firstPerson/chainsaws/mcCulloch/mcCullochCS410.i3d (10.65 ms)
[dbg4 lp3485] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp3485] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp3786] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp3786] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp4087] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp4087] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp5592] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp5592] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp5893] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp5893] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp6194] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp6194] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp6492] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp6492] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp6794] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp6794] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp7096] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp7096] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp7398] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp7398] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp7699] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp7699] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp8000] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp8000] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp8301] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp8301] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp8602] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp8602] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp8903] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp8903] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp9204] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp9204] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp9504] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp9504] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp9805] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp9805] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp10106] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp10106] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp10407] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp10407] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp10708] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp10708] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp11009] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp11009] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp11310] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp11310] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp11611] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp11611] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp11912] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp11912] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp12120] Deutz AgroStar 6.61 (#1) (528): call combine: 585
[dbg4 lp12121] Deutz AgroStar 6.61 (#1) (528): request check-in @ 585
[dbg4 lp12121] Deutz AgroStar 6.61 (#1): registering at combine Case IH Axial Flow 7130
[dbg4 lp12121] Case IH Axial Flow 7130:courseplay:sideToDrive: threshWidth: 9.60
[dbg4 lp12121] Case IH Axial Flow 7130:courseplay:sideToDrive: fruit: left 0.000000, right 728.000000
[dbg4 lp12121] Case IH Axial Flow 7130:courseplay:sideToDrive: fruit after check: left 0.000000, right 728.000000
[dbg4 lp12121] Case IH Axial Flow 7130:courseplay:sideToDrive: return fruitside right
[dbg4 lp12121] Deutz AgroStar 6.61 (#1): courseplay:sideToDrive = right
[dbg4 lp12121] Deutz AgroStar 6.61 (#1): path finding active and pipe(pipeSide 1) is not in fruit -> register tractor
[dbg4 lp12121] Deutz AgroStar 6.61 (#1) (528): distanceToCombine=130.61856302578 for combine.id 585
[dbg4 lp12121] Deutz AgroStar 6.61 (#1) (id 528): it's my turn
[dbg4 lp12121] Deutz AgroStar 6.61 (#1) is being checked in with Case IH Axial Flow 7130
[dbg4 lp14700] Deutz AgroStar 6.61 (#1): combine.workWidth: 9.60,vehicle.cp.combineOffset: 8.00, calculated offset: 8.00, fruitSide: 404notFound  
[dbg4 lp14700] Deutz AgroStar 6.61 (#1): combine is empty 
[dbg4 lp14700] Deutz AgroStar 6.61 (#1): vehicle.cp.nextTargets: 1 
[dbg4 lp16426] Deutz AgroStar 6.61 (#1): unregistering from combine id(585)
[dbg4 lp16428] Deutz AgroStar 6.61 (#1) (528): last combine = nil
[dbg4 lp16428] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp16428] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp16728] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp16728] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp17029] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp17029] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp17330] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp17330] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp17632] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp17632] Deutz AgroStar 6.61 (#1): combine (id585) is manually set
[dbg4 lp17931] Deutz AgroStar 6.61 (#1): updateReachableCombines()
[dbg4 lp17931] Deutz AgroStar 6.61 (#1): combine (id585) is manually set

**Comment by Satissis** [comment]
#1346
