### ISSUE TITLE
learn how to drive

### ISSUE THREAD

**Issue by theborg72** [Courseplay/courseplay#1131]
Hi
as it is now so when it goes out from the field, it will always choose the shortest route, which is through the trees and houses. I wish it could recognize paths like dirt, asphalt, stone, so we do not need have to remove it from the gates, trees and houses along the road.

**Comment by sootysax** [comment]
thats what combined routes are for...  you record paths starting and ending from the field entrance to the road.

**Comment by theborg72** [comment]
I have it at the beginning of the field, but sometimes so empty it in the end. Then will usually it derailed and go over the forest and all that is in the way

**Comment by Satissis** [comment]
#1346
