### ISSUE TITLE
MAC: Error

### ISSUE THREAD

**Issue by Clutchz01** [Courseplay/courseplay#1134]
Hello,
   everytime i download, do all the steps, and think i do everything right. I turn on my game to see there has been no changes. Remember, I have a mac. I downloaded it 5 separate times, never works. I have compressed and tryed every last thing but nothing works. Please help me by taking me step by step through the process after downloading. Thanks!

**Comment by Karlshoj** [comment]
First, does you other mods work? - just to be sure you know where to store your mods

**Comment by gui7545** [comment]
Try with the Official Version : http://courseplay.github.io/courseplay/res/download/ZZZ_courseplay.zip
If it is still not working, post your log into a gist: https://gist.github.com/
(How to provide a nice and sexy bug report)[https://github.com/Courseplay/courseplay/wiki]

**Comment by sootysax** [comment]
you unzip the courseplay download file

open the courseplay-master folder

zip the contents of the courseplay-master folder into a new zip file named zzz_courseplay.zip (it has to be the contents of the folder, not the folder itself or it will not work)

place the zzz_courseplay.zip into your mods folder

**Comment by Karlshoj** [comment]
On a Mac you don´t need all that zipping.
You just rename your downloaded "courseplay-master" folder to "courseplay".
Then you copy the renamed folder to your mods folder and all works fine - at least for me.
Be aware that it´s a bit tricky to find the mods folder on the MAC

**Comment by Karlshoj** [comment]
To find the mods folder you open Finder.
You click the "Go" meny.
You press the alt key, and in the Go menu you will see "Library" being added to the menu list.
You click "Library".
Now you dubble click "Aplication Support".
Dubble click "FarmingSimulator 2015", and you will see the "mods" folder where you place your mods.

If you better like the zip method as sootysax suggests you can do that and place the courseplay.zip file in the above mentioned folder. Both ways works

Hope it helps

**Comment by Satissis** [comment]
#1346
