### ISSUE TITLE
Feature Request: Dragable Waypoints

### ISSUE THREAD

**Issue by mikeloeven** [Courseplay/courseplay#1135]
This might be completely impossible however I would like to put it out there in case it might be added at a future date. Currently if you mess up while recording a path you have to start from the beginning with no way to edit or continue the course. I would like to see a system where you can click on the symbols or orange markers and drag them into a new position. 

For example you load an existing path and are running it with a slightly different truck that has a wider turn radius and it keeps getting stuck. in the new system you would be tell the driver to stop at the location where the truck gets stuck and simply drag the orange markers into a slightly new position so that the truck tries to turn earlier. 

Dragable waypoints seem like a natural method of editing per-recorded or improperly recorded paths without requiring the player to drive the whole thing again

**Comment by sootysax** [comment]
there is a program call coursedrawer that edits couseplay courses.

**Comment by mikeloeven** [comment]
do you have a link ?

**Comment by sootysax** [comment]
https://github.com/PromGames/Coursedrawer

**Comment by Satissis** [comment]
#1346
