### ISSUE TITLE
Feature request: Releasing from stuck

### ISSUE THREAD

**Issue by fudoido** [Courseplay/courseplay#1136]
hello all, i just read about your break time, but would still like to leave an idea, if possible to acomplish, so people can at least discuss it even if not made in the near future.
we all know tractors or others get stuck in the environment, specially now on FS15 that physics make machines drift alot when braking.
what if when CP detects that machine is not moving due getting stuck, pauses the machine, makes a reverse  path to get far from the obstacle, tryes to drive a bit front and sideways to evade the obstacle, and then resumes the recorded path......
doent need to move too back i believe, and dont know how or if this can be acomplished, but since we can record backward paths, thought it could also be made as a "option" for other modes, just like machines slowing down in traffic....
so, what you guys think?
and hope giants solve this physics issue, dont know about other people, but i think that farming equipment shouldnt drift/slide that much, they have tires with lot more "grip" than a common car or truck.

**Comment by mikeloeven** [comment]
actually the AI does try to reverse after being stuck the problem is that the timeout for a stuck vehicle is ridiculous the script for reversing away from an obstacle should trigger within a few seconds of "Slipping" not after several minutes of sitting up against a tree

**Comment by fudoido** [comment]
thanks for the reply mate, despite the time i wrote the coment. :)
any possible way to make it wait less time? or maybe a way to detect colidable objects same way it detects other viatures (and drive away from it if possible)? 


     El Martes 26 de Mayo de 2015 16:57, MikeLoeven <notifications@github.com> escribió:
   

 actually the AI does try to reverse after being stuck the problem is that the timeout for a stuck vehicle is ridiculous the script for reversing away from an obstacle should trigger within a few seconds of "Slipping" not after several minutes of sitting up against a tree —

**Comment by Satissis** [comment]
#1346
