### ISSUE TITLE
Suggestion: add option to manually define action triggers to courses

### ISSUE THREAD

**Issue by CGJ75** [Courseplay/courseplay#1137]
Hi, my first ever post here so please bear with me... 

I'm new to FS 15 and Courseplay, been using it for about 2 weeks... The main reason I'm still playing FS 15 actually is courseplay and my desire to work out a fully automated farm.

Okay, here's the issue:
I found that several of the modded objects I came to grow fond of (or rather their action triggers) are not properly detected by Courseplay. 
Examples: 
- On Volksholm 1.5.1 there's a huge central slurry pool in the fenced-in area, it's slurry pump however isn't detected as fill trigger by Courseplay in "Liquid manure transporter" mode while the one in front of the cow stable works fine with the same tractor/trailer combination.
- there's a seed delivery vehicle by gnescher http://www.modhoster.de/mods/ar-zubringer-3-7-m which you can fill at the seed trigger and carry 12000 l seeds out to the fields (would've given up planting taters long ago if it wasn't for this thing). Placing this thing near the field and letting the planter pass by to refill doesn't work automatically, either.
- I got a Slurry container to place at the field's edge modded from the original Kotte to work with a MAN hook-lift truck, if I try to have a Slurry spreader refill there it will just drive by it, in a second attempt I placed a pause sign in the "service" part of the course which led to the Slurry spreader sitting calmly next to the tank without any action or message (no "XX has reached waiting point" either) however, once I manually start the filling process, it'll drive on to continue work once refilled. 

just to name a few, there's more and I'm well aware there's no possibility to include the wealth of mods that are around, nor would I ask you to...
Here's what I think could be a viable solution:
When recording a course add the option to manually define and record "Action Triggers" so that Courseplay when later driving the course automatically will do exactly the same thing you did while recording the course...
- Stop
- Initiate whatever action necessary to refill/dump/whatever at that point (maybe activate a keystroke logger that'll record the next key pressed after activation)
- wait for XX seconds (a waiting period that can be independently defined from the one in the general options menu, one could possibly add other conditions like "until filled to XX%" or "until empty")
- proceed with course  
  This I think would broaden the usage of Courseplay tremendously while at the same time allow to incorporate all sorts of tools modders can possibly think of in the future. Plus the modes you guys programmed in no longer would be the limit for usage but rather what people can think of to use it for. I'd use the Liquid manure transporter mode for the seed carrier to make it dash off and fetch more seeds once emptied for example... actually I already tried that and it sat in the right place until emptied past the threshold, but of course wouldn't refill itself at a seed sales point, another thing you could manually add as an action trigger.
  Having to tell my Potato planter manually to reload from that container may not be as smoothly as the auto-refill when driving by a seed sale trigger but sure beats chugging across half the map with that wide-arse trailer to the next seed dealer.
  Hope you're getting the idea, it's a bit difficult to put on paper in a foreign language, thanks for listening.

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
