### ISSUE TITLE
slow to store big routes

### ISSUE THREAD

**Issue by Jebadiah04** [Courseplay/courseplay#1141]
I know the more way points you have the slower the route saving is. However it appears that the more routes I have the slower it saves.  Sometimes with a fresh map and a few big field work courses it will make me wait 5-10 minutes.  Is this normal and is there anything I can do about it?

Thanks

**Comment by sootysax** [comment]
yes, dont save generated courses

**Comment by mereman** [comment]
As sootysax says don't bother to save field courses they only take a few seconds to make each time. Just save your travel courses.

**Comment by Satissis** [comment]
#1346
