### ISSUE TITLE
Question: refilling sed drill

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#1142]
Its not an issue I don't think more im after some help
H
Im playing Losshugelland map using a Quadtrac and the Horsch Pronto 12 SW drill

I like to think I know what im doing setting up courses for CP but I can not get the drill to return to the starting point to trigger the refill route. When its empty I just folds up and says drill must be refilled.

So I calculate the drill course first, return to first point activated, then add my previously made refill course which starts from the start point of the drill course.

I add the refill course by pressing the first of the 2 folder icons. 

what am I doing wrong??

**Comment by Raints** [comment]
Use this tutorial to set up course. http://courseplay.github.io/courseplay/en/manual/#driveMode4

**Comment by kwguk** [comment]
Sorted.
