### ISSUE TITLE
Vertex Design Maunal Ignition

### ISSUE THREAD

**Issue by Tanglewolf** [Courseplay/courseplay#1144]
The Manual Ignition mod from vertex design was released today but doesnt work alongside courseplay if CP is left to stat the machine. 

While the guys are having a well deserved holiday and we are fending for ourselves i have found that if you add the lines from the last version of fs13 courseplay it seems to enable it.

open courseplay.zip and at line 1338 in the settings.lua there is the engine state function
:
function courseplay:setEngineState(vehicle, on) 

in this block below the drive control section i added: 

	--Manual ignition v3.01/3.04 (self-installing)
	if vehicle.setManualIgnitionMode ~= nil and vehicle.ignitionMode ~= nil then
		vehicle:setManualIgnitionMode(on and 2 or 0);
 
	--Manual ignition v3.x (in steerable as lua)
	elseif vehicle.ignitionKey ~= nil and vehicle.allowedIgnition ~= nil then
		vehicle.ignitionKey = on;
        vehicle.allowedIgnition = on;
	end;

a direct copy and paste from courseplay fs13. Now courseplay starts the vehicle and preliminary testing i have not crashed the game... yet :)

**Comment by Galwaygrass** [comment]
Use drive control instead its manual ignityion works with cp

On Fri, Apr 17, 2015 at 5:34 PM, David Oldfield <notifications@github.com>
wrote:

> The Manual Ignition mod from vertex design was released today but doesnt
> work alongside courseplay if CP is left to stat the machine.
>
> While the guys are having a well deserved holiday and we are fending for
> ourselves i have found that if you add the lines from the last version of
> fs13 courseplay it seems to enable it.
>
> open courseplay.zip and at line 1338 in the settings.lua there is the
> engine state function
> :
> function courseplay:setEngineState(vehicle, on)
>
> in this block below the drive control section i added:
>
> --Manual ignition v3.01/3.04 (self-installing)
> if vehicle.setManualIgnitionMode ~= nil and vehicle.ignitionMode ~= nil then
>     vehicle:setManualIgnitionMode(on and 2 or 0);
>
> --Manual ignition v3.x (in steerable as lua)
> elseif vehicle.ignitionKey ~= nil and vehicle.allowedIgnition ~= nil then
>     vehicle.ignitionKey = on;
>     vehicle.allowedIgnition = on;
> end;
>
> a direct copy and paste from courseplay fs13. Now courseplay starts the
> vehicle and preliminary testing i have not crashed the game... yet :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Courseplay/courseplay/issues/1144>.
>



-- 
Regards,

Mark

**Comment by Tanglewolf** [comment]
That's what I have been using from 5 minutes after it was first released Lol This is a fix to provide options to people. For instance drive control doesn't work with the light add on mod, but this manual ignition does work along side drive controls other features.

**Comment by Satissis** [comment]
#1346
