### ISSUE TITLE
UBT scipt

### ISSUE THREAD

**Issue by JanZacher** [Courseplay/courseplay#1147]
Hi guys
on Modhoster
there is a mod pack the bale exerts script
Who cool if you could do that with a tie again
it was extremely well in LS13
here is the link to the mod
http://www.modhoster.de/mods/cat-fleet-15-a

Mfg BananaJoe

**Comment by goelmc2** [comment]
The released Cat Flatbed did not have filLevels. A new version is getting ready for release and has been overhauled. It now supports fillLevels and mass when the trailer is loaded. Currently is supports, normal bales, round bales, wool pallets, board pallets, sapling pallets, pig, beef, and chicken... when loading livestock the trailer morphs automatically if the fill type isn't already selected. Maybe supporting  the in game fillLevels will help.

Cheers

**Comment by JanZacher** [comment]
ok where do I get when the new version of the supports
sorry if my english is not good

**Comment by goelmc2** [comment]
the 980 is holding up the update atm.... courseplay doesn't see the shovel, as the typeName is not wheelloader. We do have a fix that works, but it involves adding the 980 to the tippers.lua... Currently I am working to sort this out with the courseplay crew.

**Comment by Satissis** [comment]
#1346
