### ISSUE TITLE
Vareas areas to the plow

### ISSUE THREAD

**Issue by erksartori** [Courseplay/courseplay#1148]
Hello everyone! Well I do not know the perfect English, however if repedito sorry.

I tried to do something but not worked, so I'm here to help.

in my standard game map, quiz pass the plow in 4 planting areas, created the points where, pass the plow, and the routes of an area to another, put the finishing an area he simply for not going to the other, who could help me to do this correctly.

graciously

**Comment by gui7545** [comment]
You can make coursework just for one field, you can't chain all the field in only one course.
If you have 4 fields, you need 4 courses

**Comment by erksartori** [comment]
Exactly, each field has a course. Now think with me. I have the fields 24, 25, 29 and 30. Mando tractor plowing the field 24 and as soon as he finished it already goes to the next field, 25 for example, then it goes to 29 then 30. But remembering each field has its course, and to connect between them a course to get to the next field. would be something. Its? If I had something like that, we could think of something more extensive, how to put the planter and the adubadera. however in this case also still enter the course for supplying them. It would be a difficult project, but would be more realistic.

**Comment by AndyK70** [comment]
reread what @gui7545 said: you can't chain work courses. Means: you can't put more than one work course together. courseplay will do only the first work and after that only drives by the other courses without doing any work.

**Comment by erksartori** [comment]
É amigo, uma grande fazenda, tem varios campos para plantio, eles começa fazendo um, assim que termina, vao para o outro, e assim por diante. Pois uma fazenda se tiver mais de tres se torna bilionarios, mas se o jogo começa com simples tratores, deveria ter esse recurso, de vc programar varios campos, e o trator iria fazendo cada um deles. assim vc teria tempo de ir fazendo outras coisas, como cuidar dos animais por exemplo. Mas valeu, obrigado a todos.
