### ISSUE TITLE
Suggestion on filling the carts

### ISSUE THREAD

**Issue by erksartori** [Courseplay/courseplay#1149]
Taking advantage of the time off, you guys could try to make something a little more realistic, something that came to my head and that can be cool, clear is something a little more difficult, but who knows right.

The FS15 had a change relating to fill the carts, right. Well then we could try to do something in this case, know it's hard, of course if you guys talk has not as I understand, but could try.
exise three types of trucks, one small, one medium and one large. small, we could divider it into two parts, and the media and the great in 3 parts.

So speaking of small. to get close to the combine, she left carrying the first part up to 50% complete and forward a bit to fill the other 50%. this advance, it would be like this: Currently, the cart she is in the middle half of the trailer to load. then reaching 50% at this point, he avansaria to the other half of the half. to fill the other 50%.

In the case of large that it is divided into 3 parts would be as follows in the first part would be 30% in the central part was 40% and the back would be 30% to 100%.

If it becomes difficult to separate the carts could be done all divided into 3 parts, the harder it is part of their size.

Good is my suggestion to you is more cool, and a little more realistic.

Thank you

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
