### ISSUE TITLE
Courseplay won't work with the Liebherr TL 436

### ISSUE THREAD

**Issue by CaptainRush** [Courseplay/courseplay#1150]
With the Liebherr 538 and the new JCB courseplay works just fine.

But with the TL 436 it wont save my shovel positions. 

Any ideas? 

thank you!

**Comment by AndyK70** [comment]
I got no problems with the standard liebherr teleloader 436.
It's filling one shovel into the bga after another.

**Comment by renschi81** [comment]
I don't have problems with the Liebherr, but with the JCB. I can't start a transfer. Is this normal?

**Comment by Satissis** [comment]
#1346
