### ISSUE TITLE
Error vehicles.lua 1077

### ISSUE THREAD

**Issue by Vanquish081** [Courseplay/courseplay#1151]
F:\My Documents\My Games\FarmingSimulator2015\mods//samplemod/samplemod.i3d (602.27 ms)
Error: Running LUA method 'loadSharedI3DFileFinished'.
F:\My Documents\My Games\FarmingSimulator2015\mods//ZZZ_courseplay/vehicles.lua:1077: attempt to index a nil value

**Comment by Satissis** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Vanquish081** [comment]
Solve it and changing the values of rotCenterWheel1 and rotCenterWheel 2

thanks :)
