### ISSUE TITLE
Cat Fleet 15 on mod hoster

### ISSUE THREAD

**Issue by goelmc2** [Courseplay/courseplay#1152]
I work with getsome2030 on the Cat Fleet 15 and we have the Cat 980H models with the shovel attached in model. Courseplay 4.01 looks for the shovel and cannot find it. I added the following filter to the wheelLoader conditional in tippers.lua. This allows the 980H shovel to be recognized.

function courseplay:isWheelloader(workTool)
	return workTool.typeName:match("Cat980H_AWS") or workTool.typeName:match("Cat980H_ART") or workTool.typeName:match("wheelLoader");
end;

We would like to add the fix to the fleet so users may add the modified tippers.lua to their courseplay 4.01. I understand the project may be on break. we...(john and I) would like your approval for this fix. The 980H performs 100% with this. 

Highest respect to the courseplay crew 

Mike

**Comment by ThomasGaertner** [comment]
is it concerning  #1110 ?

**Comment by goelmc2** [comment]
yes.... I do the scripting for the author... getsome 2030

**Comment by ThomasGaertner** [comment]
then it would be handy, if you would give it the wheelloader spec because it is  a wheelloader :-).
then it must be recognised by CP. btw don't forget to add the AiTrafficCollisionTrigger :-) 
I'm sorry but we can not allow you to  publish this fix in the way you said.
When you added the spec and it still doesn't work , tell us here ...

**Comment by goelmc2** [comment]
ai collision has been added. if I change the typeName to WheelLoader the GE ignores the declared scripts in the modDesc. although it is wheelLoader function in the ModDesc the type needs to be non game type so that the scripts are used. hence the catch 22...

**Comment by goelmc2** [comment]
It still breaks the models design....
I fail to understand why the wheelloader spec has to do with the tippers.lua. The code I referenced is looking at the type not the spec. Changing the type to wheelLoader does not work.. Why is the fix not acceptable?
 I also noticed that line 209 has double entry? snip>>
if not isImplement and (courseplay:isWheelloader(workTool) or workTool.typeName == 'frontloader' or workTool.typeName == 'frontloader' or courseplay:isMixer(workTool)) then
<<end snip

**Comment by ThomasGaertner** [comment]
you are right, there is no spec. 
tippers.lua is not the right place for special cases.  
I can offer you to tell me the mods .xml file name and I will add it to the developer version.
we don't want to make changes in the released version.
is it possible to give me the mod to test it (traffic collision trigger and so on )?

**Comment by goelmc2** [comment]
Did you receive the email for the fleet pack? Just curious if I got it right.

**Comment by ThomasGaertner** [comment]
nope, got no e-mail from you...

**Comment by goelmc2** [comment]
Hopefully I get this right. :) Below is the link to the latest Cat Fleet.

https://drive.googlehttps://
drive.google.com/open?id=0B-WDnuxBhFZjflRBN1NZS3owc19zREdURlUxbkk1LS1YZ3JkWmstbmo4VXEzTkFKZHlKNFU&authuser=0

Cheers

**Comment by Satissis** [comment]
#1346
