### ISSUE TITLE
Argument to method 'worldToLocal' is not a string, and not nil

### ISSUE THREAD

**Issue by RedOhne** [Courseplay/courseplay#1153]
Hi,

when I start chaff cutter like Mex or Krone BigX 1100 and have a course set in combi mode for a tractor I get the following error:

Warning (LUA): Argument to method 'worldToLocal' is not a string, and not nil
-- from =E:/Benutzer/Tim/Documents/my games/FarmingSimulator2015/mods//ZZZ_courseplay/mode2.lua:228
Error: Running LUA method 'update'.
E:/Benutzer/Tim/Documents/my games/FarmingSimulator2015/mods//ZZZ_courseplay/mode2.lua:235: attempt to compare nil with number

The error occurs aswell when I have the course set on the field with out select, as when I have set a course parallel to the field with manual choose of the cutter. I had this error with CP Beta 91 and the actual one v4.01.0101

Do you know this error?

**Comment by Satissis** [comment]
#1346
