### ISSUE TITLE
After a certain amount of play time, Courseplay crashes. Screen shot included. 

### ISSUE THREAD

**Issue by greenscag** [Courseplay/courseplay#1154]
According to the bug fix logs I have the latest build. After playing for so long eventually courseplay crashes and gives a yellow arrow in the middle of the of user GUI. Here is a link to a screenshot http://i.imgur.com/bBVpXZA.png. 

Just want to thank the mod team again for this great mod. Your hard work is greatly appreciated.

**Comment by Satissis** [comment]
#1346
