### ISSUE TITLE
Automatic loading/unloading doesn't work anymore

### ISSUE THREAD

**Issue by anonieme** [Courseplay/courseplay#1156]
Installed the game about a month ago, updated to version 1.2 and installed courseplay. 
At the beginning it worked fine and I increased the amount of MODS installed.

Now I face the following problem; automatic loading and unloading doesn't seem to work anymore. If I make a new route for sowing a field and add a second route to refill the sowing machine it goes wrong.
If I start the course with a empty sowing machine it will execute the first refill route without a problem. After that it will execute the sowing route as well until the seeder is empty. Once the seeder is empty it says "refill sowing machine" and it will not perform the task automatically.

Same story for collecting bales and delivering them to a silage plant (Unna2015 Map). Once the bale collector is full it gives a message to unload the bale collector.

I removed all mods (except three) to test if that gave a problem. But the problem exists even with just the three mods.
Currently it happens in all maps.

At the moment I have the following mods installed:
- Courseplay v4.01.0000
- Fendt900erpackgruen (has worked a while with CP)
- brix_twinpack (not sure if it has worked with CP)

https://gist.githubusercontent.com/anonymous/d48cbcc160d450c2e3b4/raw/2413085121bc93a22fbe10516adbcab811949f41/log-file

**Comment by Raints** [comment]
Maybe at first you download latest developer version and then try again.
http://courseplay.github.io/courseplay/en/installation/index.html

**Comment by anonieme** [comment]
Ok, will do.

Did test some things too. Just removed the BRIX mod and tried the same saved game, now it performs both tasks as planned. Installed the BRIX mod again and it still performs the task?!?

**Comment by anonieme** [comment]
I have downloaded the latest version but it still give problems. quite logic because I already used the latest version.
I started a new game and at first everything went perfect. The farm expanded and suddenly one of the sowing machines gave a message that it needs to be refilled, while this should go automatically.

Currently 4 machines are active with CP and another 7 are in standy (route is "off" at the moment).

**Comment by Raints** [comment]
From log ### Courseplay: initialized 38/38 files (v4.01.0000) ----- This is not latest dev version.
From my log ### Courseplay: initialized 38/38 files (v4.01.0101)------ This is latest version

What you mean by this should go automatically? For seeding you need two courses, 1st for work on field and 2nd for refill. Maybe this will help you http://courseplay.github.io/courseplay/en/manual/index.html#driveMode4

Not related to courseplay but in your log i see some errors. Maybe you should check your mods. I saw you have 2 guellemistmods, Try use one instead.

**Comment by anonieme** [comment]
Strange, apparently something did go wrong by updating courseplay. I deleted all downloaded courseplay files and the one in the mod folder. Will download the latest version and install it. See if that make a difference.

By automatically I mean that I have two courses just as you describe. When I want to sow a field I load that course and a refill course. It first goes to the refill station and then starts the sowing course. If it is empty during the sowing course it should refill again but then it give a message that the implement should be filled. So the first time it works but the second time (is it has sowed already) it doesn't function anymore.

Thanks for your advice regarding the mods. I made the suggested changes and will have a closer look to the log file to see if there are more of these cases.

First I will install the latest CP and see if it install correctly. After that I will try it out and post the results here. Thanks.

**Comment by anonieme** [comment]
I now see why I still have the 4.01 instead of the 4.01.01 version. I have downloaded the normal version while you advised to download the developers version, will do that in a few minutes. 
I have played the game a few times since the last comment and the problem just occurred again.

At first all the CP icons in the map disapeared. The icons which show the location of all machines with a CP course loaded. Few moments later one of the seeders gave a refill message while it had a refill course loaded.

https://gist.githubusercontent.com/anonieme/9e77c7f12ee918fd4681/raw/ccb4267b53b66ecec9aa2d801c053cfd9ed7e8b4/gistfile1.txt

**Comment by Raints** [comment]
Are you using ingame seeder? I'm asking only because i'm using courseplay latest dev version and with ingame seeders i dont have any problems at all. 

My only thoughts about your problem is you have some mod conflict.

**Comment by anonieme** [comment]
No, it is the Horsch Pronto DC 18. Will try a in game seeder to see what it does. I also tried to find the developer version you mentioned but I can not find it. Do you have link to it?

**Comment by tryst46** [comment]
I have the same problem with an earlier version of CP (v3.40). Sometimes, the combine helper just refuses to detect the unload trigger at the silo and just keeps going. It doesn't happen very often but when it does, it continues the script as if it has unloaded, drives up to the combine but won't offload any more from it, it just drives straight past and goes back to the silo where it fails to recognise the trigger again. Ultimately, the combine stops when it is full and the tractor keeps going round and round the course until the player intervenes.

So far, it seems the only cure is to manually stop the script, unload the trailer and restart the script again. It seems to work fine after that. Is there a flag that tells CP that the trailer is full that's failing to set properly? I use the default "drive on at 90%" and from lots of testing, I found that the unload fails when the combine has fully unloaded to the trailer and the trailer is exactly 90% full.

**Comment by Roktaal** [comment]
On first load of the course everything works fine but when I clear it and then create new one or load any existing one, it stops auto loading/unloading/refilling on all vehicles. It happens in all modes.

**Comment by anonieme** [comment]
I still encounter the problem. The same problem as Roktaal. I'm not sure what the problem is however it only seems to happen if you have quite a lot of courses saved.

**Comment by anonieme** [comment]
Went trough the LOG file and removed all mods that gave an error. Restarted the game and viewed the LOG again. Now other MODS were giving an error so I repeated the procedure. It keeps creating errors even if you remove all MODS which creates an error. 
Once you restart the game MODS which were fine at first suddenly give an error.

**Comment by Satissis** [comment]
#1346
