### ISSUE TITLE
Failure Code

### ISSUE THREAD

**Issue by Tonton1969** [Courseplay/courseplay#1157]
C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/triggers.lua:688: bad argument #1 to 'tostring' (value expected)
Warning (LUA): Unknown entity id 243080 in method name: getName.
LUA call stack:
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/triggers.lua(688) : getName
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/start_stop.lua(305) : updateAllTriggers
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/input.lua(266) : start
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/input.lua(199) : executeFunction
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/input.lua(185) : setCourseplayFunc
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/input.lua(64) : handleMouseClick
  D:/code/lsim2015/build/finalbin/dataS/scripts/vehicles/Vehicle.lua(2196) : mouseEvent
  D:/code/lsim2015/build/finalbin/dataS/scripts/BaseMission.lua(1036) : mouseEvent
  D:/code/lsim2015/build/finalbin/dataS/scripts/FSBaseMission.lua(1452) : mouseEvent
  D:/code/lsim2015/build/finalbin/dataS/scripts/missions/mission00.lua(204) : mouseEvent
  =C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//Loesshuegelland_V3/SampleModMap.lua(106) : mouseEvent
  D:/code/lsim2015/build/finalbin/dataS/scripts/main.lua(1350) : mouseEvent
Error: Running LUA method 'mouseEvent'.

**Comment by Satissis** [comment]
https://github.com/Courseplay/courseplay/wiki
