### ISSUE TITLE
trailer branter 8,500 liters is not discharged

### ISSUE THREAD

**Issue by Partizanin** [Courseplay/courseplay#1158]
trailer branter 8500 liters are not unloaded because it does not arrives a couple of meters

**Comment by Partizanin** [comment]
just checked with trailer Kagroline HKD302 same story at the unloading arrives a couple of meters to feed the trailer was a place of discharge

the impression that the problem is with all the trailers

**Comment by Satissis** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Partizanin** [comment]
1. Courseplay version : v4.01.0000
2. Earlier discussion of this problem is not found
3. In modes of transportation and selling, working with kombain not working unloaded, that is when the trailer arrives to the place of unloading not enough a couple of meters that it was unloaded, and the screen displays a [warning](https://cloud.githubusercontent.com/assets/5072597/7667388/3f873d6a-fc0e-11e4-88f9-d10641a6a95a.png)
4. Log file Gits on Github  [log.txt](https://gist.github.com/anonymous/9636904a0a5464c03392) 
5. Map of games [Bornholm](https://www.google.com/search?q=farming+simulator+15+Bornholm&newwindow=1&tbm=isch&tbo=u&source=univ&sa=X&ei=uYhXVZboM6LW7AbT3YHADw&ved=0CC0QsAQ&biw=1366&bih=643)
6. mods list:
        
        1. BrantnerDPW18000
        2. EuroJabelmannEJT53000
        3. FS15_BaleCounter
        4. FS15_flieglVFW10600
        5. FS15_kirovetsK700A
        6. FS15_kuhnMowerPack
        7. FS15_kuhnSitera3000
        8. FS15_kuhnVB2190
        9. FS15_marshallPack
        10. FS15_PoettingerJumboCombiline6610
        11. FS15_vaederstadPack
        12. FS15_WeightWorklight_MW_mailman
        13. fuqsbow_500kg_weight
        14.  Kotte_FRP_145
        15. krassortBaletrailer
        16. LemkenAchatZ8
        17. MachineryRental
        18. placeable_fertilizerTank_LS15
        19. placeable_floodlight_LS15
        20. placeable_gasTank_LS15
        21. placeable_seedPallets_LS15
        22. placeable_strawPowerPlant
        23. SauterEquipment
        24. SelfmadeConcreteWeights
        25. SelfmadeCultivator
        26. ToggleTipSide
        27. VeenhuisW400
        28. VehicleGroupsSwitcher
        29. ZZZ_courseplay
        30. ZZZ_GPS

**Comment by sootysax** [comment]
start with using the latest developer version.

**Comment by gui7545** [comment]
Hi,
I think it come from the "26. ToggleTipSide" mod. The warning on the screen don't come from coursplay.
It is maybe a compatibility problem between this mod and courseplay. For example, courseplay try and calculated to unload from one side but the mod doesn't allow him to unload from this side.

**Comment by Partizanin** [comment]
sootysax gui7545, thanks for the suggestion, I'll try

**Comment by Partizanin** [comment]
@gui7545, You were right, the problem was compatibility "26. ToggleTipSide" mod and courseplay, I fixed the problem by removing "ToggleTipSide", thank you all for your help!
There is this proposal to make and amend the list of incompatible mods with courseplay
