### ISSUE TITLE
Support for Front Mounted Cultivators on seeding course 

### ISSUE THREAD

**Issue by mikeloeven** [Courseplay/courseplay#1159]
Can you add support for front mounted cultivator rollers on seeding paths currently if you have both a seeder and cultivator attached to your tractor you still have to run the course twice because while the front roller will be lowered it only lowers once the seeder reaches the edge of the field leaving a large gap of uncultivated space the length of the tractor at the turning points

**Comment by tryst46** [comment]
This is where the old system of driving around the field was better in that respect. It then treated the grass edge as part of the field for overrun/underrun operations at your discretion. If the new field detection allowed you to add a a specified number of extra feet NSEW at your request on a specific field, you could create the start and end points more suited to the equipment you are using.

**Comment by Satissis** [comment]
#1346
