### ISSUE TITLE
fs 2013 no field scanning

### ISSUE THREAD

**Issue by Sebzepp** [Courseplay/courseplay#1160]
Hello, first I'm sorry for my english, I'm french.
CP doesn't scan fields in the map. I play with "ferme limousine low".
No scan when I buy a field. No scanning map when I start a new game.
I tried to play on the original map, it doesn't work.
Could you help me please ? Thanks.

**Comment by gui7545** [comment]
Salut,
Peux tu verifier si tu as bien ces valeurs dans ton fichier courseplay.xml : ```<courseplayFields automaticScan="true" onlyScanOwnedFields="true"``` Ce fichier est içi : C:\Users\Sebzepp\Documents\My Games\FarmingSimulator2013\savegame1\
Si oui, peux tu alors fournir un exemplaire de ton log ?
Si cela ne marche toujours pas, j'ai peur que cela provienne de la façon dont la map a été créée.

Can you check if you have this value in your file xourseplay.xml ?
If yes, can you seend us your log ?
If it's still don't work, i'm afraid that it can come from the map.

**Comment by Sebzepp** [comment]
Cool, une reponse en français ! Merci de t'intéresser à mon cas. Je regarde ça ce soir et je te tiens au courant.
De mémoire, j'ai déjà cherché ces valeurs, il en est question dans le mode d'emploi que j'ai lu, mais je n'avais rien trouvé.
Je te redis tout à l'heure.
Merci a+

gui7545 <notifications@github.com> a écrit :

**Comment by Sebzepp** [comment]
Alors, j'ai regardé et je n'ai pas trouvé ce fichier... Bizarre ! Je me suis dit qu'il y avait peut-être un conflit, j'ai vérifié mon log, j'y ai trouvé qq warning et error. J'ai enlevé tous les mod à erreur et j'ai réessayé. Ca ne marchait toujours pas.
Et là je me suis dit que la version du cp que j'avais était foireuse... J'ai donc téléchargé un autre zip, que j'ai réinstallé proprement... Et ça marche ! Ouverture de carte et hop, CP scan mes champs ! Trop bien. Quel bonheur de finir de rentrer ma paille pendant que mon ouvrier commence de dechaumer ! 
En plus, les contours de champs de cette Map sont vraiment anarchiques, mais il calcule avec justesse, c'est impressionnant ! Je m'en veux de ne pas avoir pensé à ça avant et d'avoir tant galéré pour rien !
En tout cas, merci de m'avoir répondu et de m'avoir mis sur la bonne piste.

Question subsidiaire, sur le soil mod, je n'arrive pas à trouver l'info : quand vaut-il mieux epandre la chaux ? Avant de semer ? En même temps que le fumier ? Juste après avoir labouré ?
Merci encore et bravo pour ce super mod.
A+

gui7545 <notifications@github.com> a écrit :

**Comment by gui7545** [comment]
Je ne sais pas du tout par rapport a ce mod Soil. Je ne l'utilise pas !
Bon jeu

This is the final point in english for other people.
He was using a wrong version of Courseplay. He try an other one and everything works fine.
He thanks for this mod

**Comment by Satissis** [comment]
This info might help:
If the buy icon for the field is outside of the field, the auto scan fields can't find the fields, so you will have to manually scan the field by driving the vehicle inside the field and press the scan button on the recording page.

**Comment by JakesL** [comment]
Im having a problem here. I have copied and pasted the file into mods but when i open my fs15 my courseplay is not there i have presed every botton an the mouse and keyboard and still no courseplay im new to it PLEAS HELP

**Comment by Satissis** [comment]
@JakesL Do not mix issues, this issue is about field scanning and not about not able to open CP.
Please search if any issues is already open and if not, then create a new one and follow these guidelines:
https://github.com/Courseplay/courseplay/wiki
