### ISSUE TITLE
Combine V Overloader. Auto unload forage wagon

### ISSUE THREAD

**Issue by Loros** [Courseplay/courseplay#1162]
I have 2 problem with courseplay. 

1. I just Bought New Holland Cr.1090 combine. but when i get the overloader to collect from it, it drives in the back of the combine. so it wont unload.

2. after the forage wagon picked up the grass, and should drive to the biogas facility, it wont drive on, it says that its full. I tried follow the tutorials for this.

**Comment by Satissis** [comment]
#1346
