### ISSUE TITLE
course play v4.01 issues 

### ISSUE THREAD

**Issue by markyboy711** [Courseplay/courseplay#1164]
this is my log please sort this 

GIANTS Engine Runtime 6.0.2 (Build Date: Oct 29 2014)
Copyright (c) 2008-2014, GIANTS Software GmbH (giants-software.com), All Rights Reserved.
Copyright (c) 2003-2014, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: FarmingSimulator2015
Main System
  CPU: Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz
  Memory: 3067 MB
  OS: Windows NT 6.1 32-bit
Physics System
  Version: 5.9.4
  Thread(s): 1
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick disabled
  Force Feedback disabled
Sound System
  Driver: OpenAL
  Version: 1.1
  Device:  Generic Software Compatibility Mode
  Max. sources: 256
Render System
  Driver: OpenGL
  Card Vendor: NVIDIA Corporation
  Renderer: GeForce 210/PCIe/SSE2
  Version: 3.3.0
  Shader Version: 3.30 NVIDIA via Cg compiler
    max_texture_layers: 16
    OpenGL initialization successful
Hardware Profile
  Level: Very High (forced)
  View Distance Factor: 1.300000
  Shadow Quality: 2.000000
  Skip Mipmaps: 0
  LOD Distance Factor: 1.300000
  Terrain LOD Distance Factor: 2.000000
  Foliage View Distance Factor: 1.600000
  Volume Mesh Tessellation Factor: 0.750000
  Tyre Tracks Segments Factor: 4.000000
Farming Simulator 15 INT
  Version: 1.1.0.0 RC12
  Available Languages: en de fr es it pl cz hu nl ru jp pt cs ct br tr ro kr
  Language: en
Game vehicle types loaded
Mod directory: C:/Users/user/Documents/My Games/FarmingSimulator2015/mods/
Load mod: AAA_UniversalProcessKit
Load mod: BCS_127
Load mod: Case_1455xl_FS15_ModSchuppen
Warning: Missing l10n for button INTERACTIVE_CONTROL_SWITCH in Case_1455xl_FS15_ModSchuppen
Load mod: Caterpillar_Dura_Shield
Load mod: Cat_980H_AWS_15
Load mod: Cat_Bulk_Liquids_15
Load mod: Cat_DollySig_15
Load mod: Cat_Flatbed_15
Load mod: Cat_Kenworth_15
Load mod: Cat_SemiTrailer_A_15
Load mod: Cat_SemiTrailer_B_15
Load mod: crasherv2
Load mod: DEUTZCOMBINE
Warning: Missing l10n for button SEND_CHAT_MESSAGE in DEUTZCOMBINE
Load mod: EagerBeaver_15pack
Load mod: f4000
Load mod: FendtFarmer310LSA
Load mod: FordF150
Load mod: FS15JohnDeere7810FullFH
Load mod: FS15JohnDeere7810FullWeight
Load mod: FS15JohnDeere7810V2FullFH_Washable
Load mod: FS15_claasLexion550
Load mod: FS15_JD6170M
Load mod: FS15_JD6RPack
Load mod: FS15_JD8530MOFixed
Load mod: FS15_JD_6930Premium
Load mod: FS15_JD_6930P_Fixed
Load mod: FS15_JohnDeere8430
Load mod: FS15_marshallPack
Error: Unsupported mod description version in mod FS15_marshallPack
Load mod: GreenhouseInfo11
Load mod: handyMan
Load mod: Inspector
Load mod: JD900KG
Load mod: JD_4850
Load mod: JD_BY_FM
Warning: Missing l10n for button ESLimiter_PLUS in JD_BY_FM
Warning: Missing l10n for button ESLimiter_MINUS in JD_BY_FM
Warning: Missing l10n for button SameHurliLambo_START in JD_BY_FM
Warning: Missing l10n for button SameHurliLambo_STOP in JD_BY_FM
Warning: Missing l10n for button RamieTura in JD_BY_FM
Warning: Missing l10n for button Oslona in JD_BY_FM
Warning: Missing l10n for button starfire in JD_BY_FM
Warning: Missing l10n for button Konsola in JD_BY_FM
Warning: Missing l10n for button heckfenster818 in JD_BY_FM
Warning: Missing l10n for button Fl in JD_BY_FM
Warning: Missing l10n for button tuerLinks818 in JD_BY_FM
Warning: Missing l10n for button tuerRechts818 in JD_BY_FM
Warning: Missing l10n for button ATTACHERTTV_UP in JD_BY_FM
Warning: Missing l10n for button ATTACHERTTV_DOWN in JD_BY_FM
Load mod: Jenz_Crusher_Titan_V1
Load mod: JohnDeere7930FullScript
Load mod: JohnDeere8330FHV2
Load mod: JohnDeere8330WeightV2
Load mod: JohnDeere_FrontLoader
Load mod: John_Deere_7200R
Load mod: k744P3
Load mod: Lagerhalle_V1
Load mod: MANTGSMobilhackerv1
Load mod: MehrzweckaufliegerV2
Error: Unsupported mod description version in mod MehrzweckaufliegerV2
Load mod: mrJD8400T
Load mod: NewHollandT6160BV
Load mod: peterbilt_379_daycab_FS2015
Load mod: PonsseBuffalo_Chipper
Load mod: PonsseBuffalo_Rental
Load mod: PonsseScorpion_Rental
Load mod: scaniaR730forest_v1__2
Load mod: seed_fertilizer
Load mod: wooltrailerV3_FS2015
Load mod: ZZZ_courseplay
Error: Unsupported mod description version in mod ZZZ_courseplay
Load mod: ZZZ_driveControl

**Comment by sootysax** [comment]
sort what?!

**Comment by markyboy711** [comment]
The problem with the modDesc please

**Comment by Raints** [comment]
Did you download it here?  http://courseplay.github.io/courseplay/

**Comment by markyboy711** [comment]
Yeah

**Comment by gui7545** [comment]
You have to update the game to 1.2.
We appreciate more details with bug report, like "hello", "thanks" ...

**Comment by markyboy711** [comment]
How do i do that thanks

**Comment by Raints** [comment]
http://www.farming-simulator.com/updates.php

**Comment by horoman** [comment]
Did the update of the game fix your problem?

**Comment by markyboy711** [comment]
YES
