### ISSUE TITLE
Issues with course generation

### ISSUE THREAD

**Issue by benjoglove** [Courseplay/courseplay#1165]
Hi,

Have current 4.01 course play.

I am playing the AGRO_POMORZE_V4_5 and having an issue with the field generation. As you can see in the pics course play scans the surrounding field okay (photo 2). However, when I generate a course the way points are on the outside of the field (photo 1). I have also tried to manually drive around the field and record my own route but the way points do the same thing. Any idea?

![fsscreen_2015_06_04_08_31_38](https://cloud.githubusercontent.com/assets/7673205/7973515/4c4a95c0-0a95-11e5-89ad-75b9e49c54bd.png)
![fsscreen_2015_06_04_08_32_24](https://cloud.githubusercontent.com/assets/7673205/7973516/50546e5c-0a95-11e5-9bb9-b482978b20c8.png)

**Comment by benjoglove** [comment]
Anyone please?

**Comment by horoman** [comment]
The developers, which have the knowledge to help you take a deserved break (they develop this great mod in their free time...).
https://github.com/Courseplay/courseplay/issues/1133
