### ISSUE TITLE
HeapTipTrigger

### ISSUE THREAD

**Issue by JanZacher** [Courseplay/courseplay#1166]
Hey guys got a question how can you teach new unloading trigger the cours play
because he does not recognize the HeapTipTrigger
or what I have to some because he recognizes

**Comment by ThomasGaertner** [comment]
which Version of HeapTipTrigger do U use?

**Comment by JanZacher** [comment]
13.2

**Comment by ThomasGaertner** [comment]
it for FS13 so it can't work....

**Comment by JanZacher** [comment]
LS15 which is up and running can gladly give the download link

**Comment by ThomasGaertner** [comment]
yes please

**Comment by JanZacher** [comment]
http://tsl.iphpbb3.com/forum/71996029nx54259/nuetzliches-f222/heaptiptrigger-ls15-t7099.html

**Comment by ThomasGaertner** [comment]
sorry but I can't download it because of necessary login. is it an official version ?

**Comment by ThomasGaertner** [comment]
@JanZacher : any news ?

**Comment by ian898** [comment]
I think this can be closed because HeapTipTrigger 15.0.2 works completely fine with latest courseplay version.
