### ISSUE TITLE
Courserecording, turn maneuver

### ISSUE THREAD

**Issue by MrTobbsta** [Courseplay/courseplay#1168]
Hello!
So I was trying to record a good fieldcourse whit a headland (just found the turn maneuver button) but quicklly realised that I coundent switch to reverse mode when I started a turn maneuver. This would be really hand for recording your own 3-point turns, whlie the implement is turned off.
Is there a quick fix for this or alot of coding to be done?

Thanks in advance

**Comment by Satissis** [comment]
No it's not something we have planed to do, since we are still working on a totally new turn maneuver system.
It will just do the normal turn maneuver until then.
