### ISSUE TITLE
displaced tractor

### ISSUE THREAD

**Issue by horoman** [Courseplay/courseplay#1170]
I noticed in different modes (unload combine, transfer, shovel mode), that when I dismiss the CP-driver, the tractor (but not the attached tools) will jump to an other position.
Here an example:
![fsscreen_2015_06_12_16_38_14](https://cloud.githubusercontent.com/assets/3987442/8160472/2aefa45e-1370-11e5-931c-ddb479f0024d.png)
![fsscreen_2015_06_12_16_38_25](https://cloud.githubusercontent.com/assets/3987442/8160474/32d65dac-1370-11e5-99f6-2ffffdfd5893.png)
It happens often, but so far I cannot see a certain pattern behind it.

**Comment by ThomasGaertner** [comment]
should be fixed with patch 1.3 but we didn't push the 1.3-ready version yet....

**Comment by ThomasGaertner** [comment]
please test v105 intensely whether there are still issues with slowly sliding vehicles...

**Comment by horoman** [comment]
Hi Thomas
Thanks for the quick response. I will update you here again as soon as I had time to play again a few hours ;-)
Best regards

**Comment by benjoglove** [comment]
ThomasGaertner, are we saying that slowly moving vehicles and trailers moving around at waiting points is fixed with latest download?

**Comment by ThomasGaertner** [comment]
Should be ...

**Comment by benjoglove** [comment]
Okay will try now and let you know.

**Comment by benjoglove** [comment]
Well done!!!! This has been my biggest bug bear since fs2015 came out. Not sure how you fixed it but b-double trailers attached to semi at waiting point for 25 minutes and hasn't moved an inch!!

**Comment by Satissis** [comment]
#1346
