### ISSUE TITLE
multiplayer@ Courseplay

### ISSUE THREAD

**Issue by milksnake** [Courseplay/courseplay#1171]
Hello! Excuse - I write through the translator. I from Russia.
I saw your message on tests of the new version mod, and whether there support of a multiplayer will be realized? I play with the girlfriend on a network, and without Courseplay it is impossible to play. In the latest version which supported the network mode, Courseplay slowed down game. There were breakthroughs.
When there is a new version and whether there will be a support of a multiplayer there?

p.s. spread a pozhluyst fashions somewhat quicker, and that we from inaction will attach still any territory to Russia))))

Thanks in advance!

**Comment by ThomasGaertner** [comment]
sorry , no active plans at the moment.....

**Comment by Satissis** [comment]
#1346
