### ISSUE TITLE
Feature Request: Decrease and Increase waypoints.

### ISSUE THREAD

**Issue by karmamuscle** [Courseplay/courseplay#1172]
Hi,
it would be really nice to have a Decrease Speed and Increase Speed way point.
For when you have selling routes with fast trucks, once they reach a turn and they are driving fast 70+ they slide all over the place.
You can work around it by placing a Wait Waypoint just before the turn, this does put them at a complete, or close to, halt.

**Comment by sootysax** [comment]
coursedrawer lets you change speed for each waypoint

**Comment by karmamuscle** [comment]
True, but then it's just easier to edit the .xml myself.
I just thought it would neat to have integrated into CoursePlay itself.

**Comment by ThomasGaertner** [comment]
can we close ?

**Comment by AndyK70** [comment]
Record your course at reasonable speeds for straights and corners, when CP drives have the speed setting not to "max speed", but "**recorded speed**". Additionally you can set a max speed limit, so you can go faster on straights when recording but keep it safe when CP drives.

**Comment by Satissis** [comment]
#1346
