### ISSUE TITLE
slurry tanker, water trailer, livestock trailer disappearing when loading

### ISSUE THREAD

**Issue by okky84** [Courseplay/courseplay#1173]
I have found out that slurry transporter, livestock trailers, milk trailers and few other mods are disappearing as soon as you start loading them. collisions are still there, and at certain percentages they reappear. when the trailer is "invisible" tractor get stuck and cannot pull the trailer. no problems without courseplay in mods folder. while looking on log file there were few errors with recognizing unloading points. does anyone else have experienced this issue?

**Comment by Satissis** [comment]
Never seen this issue before

**Comment by mngrazy** [comment]
this is not courseplay , this is a problem with ZZZ_advancedFillAutoAimTargetNode.zip
update the mod @ModHoster and the problem is gone ,,, or delete the mod

regards grazy

**Comment by okky84** [comment]
Thank you! Sorted!


Inviato dal mio dispositivo Samsung

-------- Messaggio originale --------
Da: mngrazy <notifications@github.com> 
Data: 18/06/2015  12:44  (GMT+00:00) 
A: Courseplay/courseplay <courseplay@noreply.github.com> 
Cc: okky84 <okky_84@hotmail.it> 
Oggetto: Re: [courseplay] slurry tanker, water trailer, livestock trailer
  disappearing when loading (#1173) 

this is not courseplay , this is a problem with ZZZ_advancedFillAutoAimTargetNode.zip

update the mod @ModHoster and the problem is gone ,,, or delete the mod

regards grazy
