### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by benjaminpegrisch** [Courseplay/courseplay#1174]

**Comment by benjaminpegrisch** [comment]
Can it be programmed that you can choose the speed in a curve? I think the cp drives in 90 degree curves too fast/ breakes too late so with heavy trailers he crashes or drives in vehikles in the other side. Will this be fixed or can i Do that simply self without changing luas?

Thanks

**Comment by Satissis** [comment]
Well there is actually an function for that already, which is: while recording, it records the speed you are driving, so if you have recorded an route where you break in good time and go slowly in the turn AND the road speed settings is set to "From Recording" it should work nicely.

**Comment by benjaminpegrisch** [comment]
No because i cant record the whole course perfekt including max speed. I record the course carefully and slowly so that the waypoints are placed perfekt. And when i finished recording i set to max speed so he drives always fast and perfect. Only the curves are the breaking pionts too late...

Please help...

**Comment by benjaminpegrisch** [comment]
When you record a course with 900 points or more you cant drive max speed AND perfekt because of looking in card or other things

**Comment by sootysax** [comment]
you should just use coursedrawer to edit speeds after the fact...


this is what i do when creating combined routes, recording the entire length of each road in either direction, then using coursedrawer to add crossing points and slow down at each intersection.

**Comment by benjaminpegrisch** [comment]
Thx first.
But where can i get Software and a instruction how to work with cd? Because i have never heard before

**Comment by ThomasGaertner** [comment]
#1135

**Comment by Satissis** [comment]
#1346
