### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Transporter2** [Courseplay/courseplay#1175]
When i copy the zip and i start the game the mod is not loaded. i can see only the chose tip side mod that i installed.

**Comment by Transporter2** [comment]
Main System
  CPU: Intel(R) Pentium(R) 4 CPU 3.20GHz
  Memory: 4095 MB
  OS: Windows NT 6.1 64-bit
Physics System
  Version: 5.9.4
  Thread(s): 1
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick disabled
  Force Feedback disabled
Sound System
  Driver: OpenAL
  Version: 1.1
  Device:  Generic Software
  Max. sources: 256
Render System
  Driver: OpenGL
  Card Vendor: ATI Technologies Inc.
  Renderer: AMD Radeon HD 7700 Series
  Version: 4.4.13283 Compatibility Profile Context 14.501.1003.0
  Shader Version: 4.40
    GL_NV_texture_compression_vtc not supported
    max_texture_layers: 16
    GL_NV_vertex_program2_option not supported
    GL_NV_vertex_program3 not supported
    OpenGL initialization successful
Hardware Profile
  Level: Medium (auto)
  View Distance Factor: 1.000000
  Shadow Quality: 1.000000
  Skip Mipmaps: 1
  LOD Distance Factor: 1.000000
  Terrain LOD Distance Factor: 1.000000
  Foliage View Distance Factor: 1.000000
  Volume Mesh Tessellation Factor: 1.000000
  Tyre Tracks Segments Factor: 1.000000
Farming Simulator 15 INT
  Version: 1.1.0.0 RC12
  Available Languages: en de fr es it pl cz hu nl ru jp pt cs ct br tr ro kr
  Language: en
Game vehicle types loaded
Mod directory: C:/Users/EDI/Documents/My Games/FarmingSimulator2015/mods/
Load mod: ToggleTipSide
Load mod: ZZZ_courseplay
Error: Unsupported mod description version in mod ZZZ_courseplay
Warning: Character '9' not found in texture font (

).

**Comment by Transporter2** [comment]
GIANTS Engine Runtime 6.0.2 64bit (Build Date: Oct 29 2014)
Copyright (c) 2008-2014, GIANTS Software GmbH (giants-software.com), All Rights Reserved.
Copyright (c) 2003-2014, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: FarmingSimulator2015
Main System
  CPU: Intel(R) Pentium(R) 4 CPU 3.20GHz
  Memory: 4095 MB
  OS: Windows NT 6.1 64-bit
Physics System
  Version: 5.9.4
  Thread(s): 1
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick disabled
  Force Feedback disabled
Sound System
  Driver: OpenAL
  Version: 1.1
  Device:  Generic Software
  Max. sources: 256
Render System
  Driver: OpenGL
  Card Vendor: ATI Technologies Inc.
  Renderer: AMD Radeon HD 7700 Series
  Version: 4.4.13283 Compatibility Profile Context 14.501.1003.0
  Shader Version: 4.40
    GL_NV_texture_compression_vtc not supported
    max_texture_layers: 16
    GL_NV_vertex_program2_option not supported
    GL_NV_vertex_program3 not supported
    OpenGL initialization successful
Hardware Profile
  Level: Medium (auto)
  View Distance Factor: 1.000000
  Shadow Quality: 1.000000
  Skip Mipmaps: 1
  LOD Distance Factor: 1.000000
  Terrain LOD Distance Factor: 1.000000
  Foliage View Distance Factor: 1.000000
  Volume Mesh Tessellation Factor: 1.000000
  Tyre Tracks Segments Factor: 1.000000
Farming Simulator 15 INT
  Version: 1.1.0.0 RC12
  Available Languages: en de fr es it pl cz hu nl ru jp pt cs ct br tr ro kr
  Language: en
Game vehicle types loaded
Mod directory: C:/Users/EDI/Documents/My Games/FarmingSimulator2015/mods/
Load mod: courseplay
Error: Failed to open xml file 'C:/Users/EDI/Documents/My Games/FarmingSimulator2015/mods//courseplay/modDesc.xml'.
Error: Missing descVersion attribute in mod courseplay
Load mod: ToggleTipSide
Load mod: ZZZ_courseplay
Error: Unsupported mod description version in mod ZZZ_courseplay
Warning: Character '9' not found in texture font (

).

**Comment by ThomasGaertner** [comment]
update to FS15 to Patch 1.3 and all is fine :-)

**Comment by Transporter2** [comment]
Ty but how i update becose i run the non steam skidrow version ;) I want to try out the game and if evreything is worthed

**Comment by mngrazy** [comment]
skidrow or the codex release = cracked , go home brother

**Comment by mereman** [comment]
I'm always amazed how many people will admit to using stolen* copies of games.

*Yes it is stealing.

**Comment by sootysax** [comment]
wow - wasting everyones time asking for support of a cracked game...

**Comment by Transporter2** [comment]
oh god i knew if i say that i try the game evreyone will go mad :(

**Comment by sootysax** [comment]
thats fine, try the game... but dont waste peoples time asking for support when you are using a cracked, probably out of date, buggy piece of software.

**Comment by Transporter2** [comment]
Ok.. Thanks anyway for the support!
And now the mod works after i updated it!
