### ISSUE TITLE
Setting exact working widths

### ISSUE THREAD

**Issue by IHguy712** [Courseplay/courseplay#1176]
I am wondering if anyone has a suggestion or would know how to be able to set (for example) a tractor to collect straw windrows behind a combine that has a header width of 13.7m. Closest is 13.5m and by the time he makes a few passes, he's off the windrow.

**Comment by Thielenm** [comment]
I found it after you set up your course for your combine, you can select your tractor go to the Driving Settings (Tractor icon) and then down on the bottom click on the copy course to your combine and it will follow that path.  Hope it works for you.

**Comment by IHguy712** [comment]
I'll give it a try, Thanks!

**Comment by bojanh66** [comment]
I have saved that course as harvest/baling 13.7m, so i load that course on both harvester and tractor+baler :)
A lot of implements have same working width or can follow same course, so i make few same course under 1 name , saves some space.
I have cultivator 9m, horsch pronto 9m and header 9m under the same course. (in my case culti/seeder/harvest 9m)
Ive seen this trick few years ago on youtube, before that i was having each course saved separately, which increased loading time i think.

Same when you want to mow and bale grass/hay or if you want to windrow mowed grass, then let another tractor follow the same course as windrow course.
