### ISSUE TITLE
Offloading Vehicle stops after first complete unload.

### ISSUE THREAD

**Issue by LordNighthawk** [Courseplay/courseplay#1177]
Hello there,

i regulary drive my harvesters myself and only let the offloading vehicle get used by courseplay.
This problem seems to only occur if i drive the harvester, not if i let courseplay drive it.

Generally i set the unloading vehicle to start when the harvesters capacity reaches 65% load (i don´t like it if he always drives around me). If he then comes up to me and i unload completly the unloader stops....and never starts again for a second unload. He keeps stuck at "harvester tells to stop" (auf deutsch: Drescher sagt ich soll anhalten). I only get him to move again if i unassign him from the tresher manually.

If i stop him remote from inside the harvester and then don´t unload to 0% (keep a small rest in the grain tank) and then restart him later he immediatly comes up to me.

The log shows this (debug 2+4 active):

[dbg2 lp196162] Puma 160 (#2): distanceToTrigger=0, bestTipReferencePoint=1 -> trailerInTipRange=true
[dbg4 lp198436] Puma 160 (#2) (163): last combine = nil
[dbg4 lp198436] Puma 160 (#2): updateReachableCombines()
[dbg4 lp198436] Puma 160 (#2): combine (id165) is manually set
[dbg4 lp198436] Puma 160 (#2) (163): call combine: 165
[dbg4 lp198437] Puma 160 (#2) (163): request check-in @ 165
[dbg4 lp198437] Puma 160 (#2): registering at combine CR10.90
[dbg4 lp198437] Puma 160 (#2): path finding inactive
[dbg4 lp198437] 163 : cp.callCombineFillLevel:0 for combine.id:165
[dbg4 lp198437] Puma 160 (#2) (id 163): it's my turn
[dbg4 lp198437] Puma 160 (#2) is being checked in with CR10.90
[dbg4 lp205434] combine.workWidth: 13.20,vehicle.cp.combineOffset: 9.60, calculated offset: 9.60, fruitSide: 404notFound  
[dbg4 lp216907] Puma 160 (#2): unregistering from combine id(165)
[dbg4 lp217146] Puma 160 (#2): updateReachableCombines()
[dbg4 lp217146] Puma 160 (#2): combine (id165) is manually set
[dbg4 lp217146] Puma 160 (#2) (163): call combine: 165
[dbg4 lp217147] Puma 160 (#2) (163): request check-in @ 165
[dbg4 lp217147] Puma 160 (#2): registering at combine CR10.90
[dbg4 lp217147] Puma 160 (#2): path finding inactive
[dbg4 lp217147] 163 : cp.callCombineFillLevel:51.471386477351 for combine.id:165
[dbg4 lp217147] Puma 160 (#2) (id 163): it's my turn
[dbg4 lp217147] Puma 160 (#2) is being checked in with CR10.90

Situation here was that the harvester came back from unloading at the silo and registered that my harvesters load was over 65%. He drove up to me and i unloaded to 0% and continued working while he got stuck again thinking that he still was told to stop. As you see, i removed the registration and then he started again.

### Courseplay: installed into 35 vehicles

I can for sure post the complete log if required. If you tell me to download the developer version ( i already read you stopped to work at the project actually) - then please give me a direct link cause i always everywhere read to download it but then only find a link to the normal 4.01 version :-/

thx for reading
nighty

**Comment by FarmingFrank** [comment]
I have the same problems.
First time goes well and then it's over. And i setup the tractors to drive at 50% but they are driving at 100%. That is after the first unload. It completely ignores the percentage to start driving.
My log looks almost exactly as from "nighty".

Gr. Frank

**Comment by Satissis** [comment]
#1346
