### ISSUE TITLE
course across BGA

### ISSUE THREAD

**Issue by Siniy-lom** [Courseplay/courseplay#1178]
I have such а question: whether there is an ability to make such addition to courseplay, so that the tractor itself chose in what the segment to go?
For example, if the silo is full of silage, the tractor doesn't go, but if the silo is emty or partially full, the tractor goes to the silo.
see img corses bga https://yadi.sk/i/K49IR06ohSPEb

**Comment by gui7545** [comment]
no, it is not possible to make test in courseplay.
But we can make a road that go to the all BGA's silo.
The tractor will unload to the first available silo ( emty or partially full)

**Comment by ThomasGaertner** [comment]
yea its the only solution ....can we close ?
