### ISSUE TITLE
Automatic Bale loader

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#1179]
Hello! I have a request! Can you make a car support for automatic bale transport! He loads and unloads itself with Play Course?
Many Thanks!

**Comment by gui7545** [comment]
Which tool are you thinking about ?
Courseplay already accept bale transport that unload and load itself.
Can you give more information ?

**Comment by Paul2510** [comment]
SOrry! I mean the  Fliegl DPW 180 with Automatic charging function

**Comment by ThomasGaertner** [comment]
do you have a DL link ?

**Comment by mngrazy** [comment]
http://www.modhoster.de/mods/fliegl-dpw-180-mit-automatischer-ladefunktion

this mod , i think

regards grazy

**Comment by Paul2510** [comment]
Yes it is! Thanks grazy!

**Comment by ThomasGaertner** [comment]
will be supported in the  version 2.0 of the Trailer.....

**Comment by Paul2510** [comment]
Hi! The Version 2.0 is here! http://www.modhoster.de/mods/fliegl-dpw-180-mit-automatischer-ladefunktion! Thanks for your great work!

Paul!
