### ISSUE TITLE
FS15 field scanning

### ISSUE THREAD

**Issue by amonbonfills** [Courseplay/courseplay#1180]
Since I have installed the latest patch 1.3 I cannot scan any field, even if the map is 1.2 or 1.3 ready. Everything else is running ok. All mods installed at this moment are the same that I've used with patch 1.2 or 1.3 and I'm playing only one map, here's my log.

GIANTS Engine Runtime 6.0.2 (Build Date: Jun 12 2015)
Copyright (c) 2008-2015, GIANTS Software GmbH (giants-software.com), All Rights Reserved.
Copyright (c) 2003-2015, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: FarmingSimulator2015
Main System
  CPU: Intel(R) Core(TM) i3-2348M CPU @ 2.30GHz
  Memory: 2982 MB
  OS: Windows NT 6.1 32-bit
Physics System
  Version: 5.9.4
  Thread(s): 2
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick disabled
  Force Feedback disabled
Sound System
  Driver: OpenAL
  Version: 1.1
  Device:  Generic Software
  Max. sources: 256
Render System
  Driver: OpenGL
  Card Vendor: NVIDIA Corporation
  Renderer: GeForce GT 635M/PCIe/SSE2
  Version: 4.5.0 NVIDIA 353.06
  Shader Version: 4.50 NVIDIA
    max_texture_layers: 16
    OpenGL initialization successful
Hardware Profile
  Level: Medium (auto)
  View Distance Factor: 1.000000
  Shadow Quality: 1.000000
  Skip Mipmaps: 1
  LOD Distance Factor: 1.000000
  Terrain LOD Distance Factor: 1.000000
  Foliage View Distance Factor: 1.000000
  Volume Mesh Tessellation Factor: 1.000000
  Tyre Tracks Segments Factor: 1.000000
Farming Simulator 15
  Version: 1.3.0.1 1.3RC1
  Available Languages: hu ro
  Language: ro
Game vehicle types loaded
Mod directory: C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/mods/
Load mod: addFillTypes
Load mod: AnimationMapTrigger
Load mod: Compass
Load mod: FollowMe
Load mod: FS15_CutterTrailer_Attachable
Load mod: FS15_flieglDPW180
Load mod: GuelleMistMod
Load mod: JohnDeere_7180_set_FS15
Load mod: LS15_Fraese
Load mod: MB3D_JohnDeere6810
Load mod: OBE_Livestock_Trailer
Load mod: showtime15
Load mod: supportpickup11pack
Load mod: TwoRivers_Einachs_Milchfass_V_1_1
Load mod: TwoRivers_Kroeger_HKD302
Load mod: TwoRivers_LS15_V1_3
Load mod: TwoRivers_Stoll_ManureGrabFork
Load mod: vehicleSort
Load mod: WaterMilkZunhammer
Load mod: zzzAutoCombine
Load mod: ZZZ_ChoppedStraw
Load mod: ZZZ_courseplay
Load mod: ZZZ_cutterAttacher
Load mod: ZZZ_driveControl
Load mod: ZZZ_fastForward
Load mod: ZZZ_fieldSell
Load mod: ZZZ_greenDirectCut
Load mod: ZZZ_greenFertilizer
Load mod: ZZZ_improvedSilageBunker
Load mod: ZZZ_multiFruit
Load mod: ZZZ_multiFruitModule_Standard
Load mod: ZZZ_multiMowing
Load mod: ZZZ_nightGrowth
Load mod: ZZZ_SharperTurning
### addFillTypes Script by Ifko[nator] in der Version 1.5 erfolgreich geladen!
Script loaded: Compass.LUA (v2.0.6)
Script loaded: FollowMe.lua (v2.0.6)
  Register vehicle type: FS15_CutterTrailer_Attachable.CutterTrailer
  Register vehicle type: FS15_flieglDPW180.Fliegl_DPW_180_MW_Edition
  Register vehicle type: LS15_Fraese.fraese
  Register vehicle type: OBE_Livestock_Trailer.OBE_Livestock_Trailer
loading showtime15
  Register vehicle type: TwoRivers_Einachs_Milchfass_V_1_1.Milchfass
*** ChoppedStraw fruittypes registered!
Script WaterMod v3.2.4 by Marhu loaded! Support on http://marhu.net
Script SchweineZucht v4.1.0-69 by Marhu loaded! Support on http://marhu.net
Register filltype: washedPotato a part of potatoWasher placeable
VehicleSort loaded
  Register vehicle type: WaterMilkZunhammer.MilkTrailer
### Courseplay: installed into 20 vehicles
--- installing driveControl by upsidedown into Drivable and Steerable...
--- loading greenDirectCut mod V2.0 --- (by upsidedown)
loading AdditionalFruitTypes
AdditionalFruitTypes v0.5 by Jakob Tischler+upsidedown loaded
\__ Register fruitType: Lucerna (luzerne) [key 16]
\____ Register windrowType: luzerne_windrow (luzerne_windrow)
\______ ForageWagonConversion registered: luzerne_windrow -> grass
\__ Register fruitType: Trifoi (klee) [key 17]
\____ Register windrowType: klee_windrow (klee_windrow)
\______ ForageWagonConversion registered: klee_windrow -> grass
\__ Register fruitType: Ovaz (oat) [key 18]
\____ Register windrowType: oat_windrow (oat_windrow)
\______ ForageWagonConversion registered: oat_windrow -> wheat
\__ Register fruitType: Secara (rye) [key 19]
\____ Register windrowType: rye_windrow (rye_windrow)
\______ ForageWagonConversion registered: rye_windrow -> wheat
\__ Register fruitType: Floarea soarelui (sunflower) [key 20]
data/cameraPath01.i3d (12.63 ms)
data/cameraPath02.i3d (6.70 ms)
data/cameraPath03.i3d (9.06 ms)
data/sky/sky_day_night.i3d (200.43 ms)
data/sky/rain.i3d (39.06 ms)
data/sky/hail.i3d (30.30 ms)
data/sky/dust.i3d (42.72 ms)
Two Rivers LS 15: Register Fill type: Porci, Oxid de calciu, Carne de vita, 
C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/mods//TwoRivers_LS15_V1_3/map/TwoRivers.i3d (39008.68 ms)
--- loading AutoCombine v4.01 by mogli ---
  AutoCombine was inserted on combine_animated
  AutoCombine was inserted on combine_animated_crawler
  AutoCombine was inserted on combine_cylindered
  AutoCombine was inserted on combine
  AutoCombine was inserted on selfPropelledPotatoHarvester
*** ChoppedStraw v15.0.03 specialization loading ***
## Courseplay: setting up signs
C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/normal.i3d (14.22 ms)
C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/cross.i3d (1.17 ms)
C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/wait.i3d (43.21 ms)
C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/start.i3d (13.28 ms)
C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/stop.i3d (1.44 ms)
## Courseplay: loading courses and folders from "courseplay.xml"
--- loading cutter height control v1.0 by mogli ---
  CutterAttacherHeight was inserted on cutter_animated
  CutterAttacherHeight was inserted on cutter_builtInCutterTrailer
  CutterAttacherHeight was inserted on attachableCombine
  CutterAttacherHeight was inserted on attachableCombine_mouseControlled
  CutterAttacherHeight was inserted on selfPropelledPotatoHarvester
  CutterAttacherHeight was inserted on cutter_mouseControlled
  CutterAttacherHeight was inserted on cutter
--- loading driveControl mod V3.76 (by upsidedown)---
--- fast Forward Mod V1.3 loaded --- (by upsidedown)
--- loading fieldSell mod V1.0 (by upsidedown) ---
--- loading greenFertilizer mod V2.1--- (by upsidedown)
--- loading siloExtension mod V2.0 --- (by upsidedown)
--- loading addMultiFruit mod V3.0 --- (by upsidedown)
--- loading multiFruit Module: C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/mods//ZZZ_multiFruitModule_Standard/multiFruit_config.xml --- (by upsidedown)
--- loading multiMowing mod V3.1 --- (by upsidedown)
--- loading nightGrowth mod V1.1 --- (by upsidedown)
loading C:/Users/Alexia/Documents/My Games/FarmingSimulator2015//nightGrowth_config.xml for nightGrowth-Mod configuration
nightGrowth: growth shifted into night hours
--- loading SharperTurning Version 1.0 by mjk ---
data/vehicles/steerable/sampoRosenlew/sampoRosenlewC6.i3d (704.23 ms)
dataS2/character/player/player.i3d (808.79 ms)
C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/mods//zzzAutoCombine/AutoCombine.i3d (0.79 ms)
loading C:/Users/Alexia/Documents/My Games/FarmingSimulator2015//driveControl_config.xml for driveControl-Mod configuration
driveControl module shuttle started
driveControl module manMotorStart started
driveControl module manMotorKeepTurnedOn started
driveControl module gasAndGearLimiter started
driveControl module hourCounter started
driveControl module sensibleSteering started
driveControl module handBrake started
driveControl module fourWDandDifferentials started
driveControl module inDoorSound started
driveControl module dirtModule started
driveControl module camera started
driveControl module cruiseControl started
driveControl module showNearestFillLevel not started
driveControl module pipeCam not started
driveControl module implementControl started
driveControl sensibleSteering deadZone set to 14%
driveControl inDoorSound set to 45%
driveControl analog control for gas/gear limiter set to false
driveControl dirtModule speed set to 100%
driveControl global camera speed set to 100%
driveControl analog controller x-axis camera speed set to 100%
driveControl analog controller y-axis camera speed set to 100%
driveControl mouse x-axis camera speed set to 100%
driveControl mouse y-axis camera speed set to 100%
driveControl standard camera reset ENABLED
driveControl keep last Camera DISABLED
\______ Bale registered: BALETYPE_FORAGE_112_130 -> BALETYPE_SILAGE_112_130
\______ Bale registered: BALETYPE_OAT_WINDROW_120_90_240 -> BALETYPE_WHEAT_WINDROW_120_90_240
\______ Bale registered: BALETYPE_OAT_WINDROW_112_130 -> BALETYPE_WHEAT_WINDROW_112_130
\______ Bale registered: BALETYPE_RYE_WINDROW_120_90_240 -> BALETYPE_WHEAT_WINDROW_120_90_240
\______ Bale registered: BALETYPE_RYE_WINDROW_112_130 -> BALETYPE_WHEAT_WINDROW_112_130
\______ Bale registered: BALETYPE_GRASS_112_130 -> BALETYPE_SILAGE_112_130
\______ Bale registered: BALETYPE_DRYGRASS_112_130 -> BALETYPE_SILAGE_112_130
\______ Bale registered: BALETYPE_GRASS_WINDROW_112_130 -> BALETYPE_GRASS_112_130
\______ Bale registered: BALETYPE_LUZERNE_WINDROW_112_130 -> BALETYPE_GRASS_WINDROW_112_130
\______ Bale registered: BALETYPE_KLEE_WINDROW_112_130 -> BALETYPE_GRASS_WINDROW_112_130
data/vehicles/tools/koeckerling/koeckerlingTrio300M.i3d (227.88 ms)
data/vehicles/particleAnimations/koeckerling/koeckerlingTrio300M.i3d (162.72 ms)
data/vehicles/cutters/sampoRosenlew/sampoRosenlewC6.i3d (206.53 ms)
data/vehicles/trailers/brantner/brantnerE8041.i3d (183.39 ms)
data/vehicles/tools/poettinger/poettingerVitasem302A.i3d (294.94 ms)
data/vehicles/particleAnimations/poettinger/poettingerVitasem302A.i3d (38.10 ms)
\______ Bale registered: BALETYPE_LUZERNE_112_130 -> BALETYPE_GRASS_112_130
\______ Bale registered: BALETYPE_KLEE_112_130 -> BALETYPE_GRASS_112_130
data/vehicles/trailers/thueringerAgrar/thueringerAgrarLeguan.i3d (163.97 ms)
data/vehicles/tools/amazone/amazoneZAM1501.i3d (247.01 ms)
data/vehicles/tools/kuhn/kuhnVariMaster153.i3d (219.53 ms)
data/vehicles/particleAnimations/kuhn/kuhnVariMaster153.i3d (37.77 ms)
data/vehicles/tools/suer/suerSB700.i3d (144.12 ms)
data/vehicles/trailers/poettinger/poettingerEuroboss330T.i3d (327.96 ms)
data/vehicles/tools/poettinger/poettingerNovacat302ED.i3d (188.33 ms)
data/vehicles/steerable/deutz/deutzAgroStar661.i3d (426.56 ms)
dataS/character/player/playerCCT.i3d (14.43 ms)
VehicleSort initialized
adding fruits to green fertilizer mod...
wheat
barley
rape
maize
potato
sugarBeet
luzerne
klee
oat
rye
sunflower
11 fruits added to cultivator, plough and direct seeder for fertilizer use
data/vehicles/trailers/kroeger/kroegerHKD302.i3d (324.97 ms)
data/vehicles/steerable/same/sameFortis190.i3d (569.77 ms)
Saving screenshot: C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/screenshots/fsScreen_2015_06_24_21_09_51.png
Saving screenshot: C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/screenshots/fsScreen_2015_06_24_21_10_04.png
Saving screenshot: C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/screenshots/fsScreen_2015_06_24_22_21_39.png
Saving screenshot: C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/screenshots/fsScreen_2015_06_24_22_21_50.png
C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/mods//MB3D_JohnDeere6810/JohnDeere6810.i3d (1918.66 ms)
Warning: Deleting object 'woodSellTrigger' before all triggers are removed.
Warning: Deleting object 'woodSellTrigger' before all triggers are removed.

**Comment by ThomasGaertner** [comment]
inn the courseplay.xml of your savegame , set debugScannedFields="false"  to debugScannedFields="true" , try again and post the log to gist and deliver the link....

**Comment by amonbonfills** [comment]
I did as you told me and in plus I removed all mods except courseplay. I did the test on default Westbridge map. Here's the log and a copy of courseplay xml.

Farming Simulator 15
  Version: 1.3.0.1 1.3RC1
  Available Languages: hu ro
  Language: ro
Game vehicle types loaded
Mod directory: C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/mods/
Load mod: ZZZ_courseplay
### Courseplay: initialized 38/38 files (v4.01.0000)
### Courseplay: installed into 20 vehicles
data/cameraPath01.i3d (0.90 ms)
data/cameraPath02.i3d (0.57 ms)
data/cameraPath03.i3d (0.57 ms)
data/sky/sky_day_night.i3d (11.35 ms)
data/sky/rain.i3d (2.92 ms)
data/sky/hail.i3d (1.62 ms)
data/sky/dust.i3d (1.44 ms)
data/maps/map02.i3d (6429.86 ms)
## Courseplay: setting up signs
C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/normal.i3d (1.07 ms)
C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/cross.i3d (1.26 ms)
C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/wait.i3d (1.71 ms)
C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/start.i3d (1.68 ms)
C:/Users/Alexia/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/stop.i3d (1.55 ms)
## Courseplay: setting up fields (basic)
## Courseplay: loading settings from "courseplay.xml"
## Courseplay: setting up hud
## Courseplay: setting up debug channels
## Courseplay: setting up globalInfoText
## Courseplay: loading courses and folders from "courseplay.xml"
data/vehicles/steerable/deutz/deutzAgroStar661.i3d (75.26 ms)
dataS2/character/player/player.i3d (545.97 ms)
data/vehicles/steerable/huerlimann/huerlimannH488.i3d (70.29 ms)
data/vehicles/steerable/sampoRosenlew/sampoRosenlewC6.i3d (98.82 ms)
data/vehicles/steerable/buehrer/buehrer6135A.i3d (31.28 ms)
data/vehicles/tools/koeckerling/koeckerlingTrio300M.i3d (31.67 ms)
data/vehicles/particleAnimations/koeckerling/koeckerlingTrio300M.i3d (9.70 ms)
data/vehicles/tools/poettinger/poettingerVitasem302A.i3d (44.37 ms)
data/vehicles/particleAnimations/poettinger/poettingerVitasem302A.i3d (2.26 ms)
data/vehicles/trailers/brantner/brantnerE8041.i3d (22.13 ms)
data/vehicles/cutters/sampoRosenlew/sampoRosenlewC6.i3d (30.12 ms)
data/vehicles/tools/suer/suerSB700.i3d (8.73 ms)
dataS/character/player/playerCCT.i3d (20.31 ms)
call setUpIngameData()

courseplay xml:

<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<XML>
    <courseplayHud posX="0.472139" posY="0.007813" />
    <courseplayFields automaticScan="false" onlyScanOwnedFields="true" debugScannedFields="true" debugCustomLoadedFields="false" scanStep="5" />
    <courseplayWages active="false" wagePerHour="1500" />
    <courseplayIngameMap active="true" showName="true" showCourse="true" />
    <courseManagement batchWriteSize="4096" />

**Comment by ThomasGaertner** [comment]
please post the complete log to https://gist.github.com/ and deliver the link here...

**Comment by amonbonfills** [comment]
https://gist.github.com/amonbonfills/dd985a58c2ee2b154274

**Comment by amonbonfills** [comment]
https://gist.github.com/amonbonfills/80deb643fc8f75184a16

**Comment by Satissis** [comment]
#1346
