### ISSUE TITLE
Course play not working

### ISSUE THREAD

**Issue by JakesL** [Courseplay/courseplay#1181]
Im having a problem here with cp I have copied and pasted the file into mods but when i open my fs15 my courseplay is not there i have presed every botton on the mouse and keyboard and still no courseplay. I have removed all my mods and left cp but yet no cp how do i get it to run with my fs15 in game.? im new to it PLEAS HELP

**Comment by ThomasGaertner** [comment]
please post the log to https://gist.github.com/ and deliver the link ....

**Comment by JakesL** [comment]
Hi Thomas dont worry got it sorted out its working now.. tell me is there a course play for multiplayer

**Comment by ThomasGaertner** [comment]
not yet
