### ISSUE TITLE
Mode viewing and loading

### ISSUE THREAD

**Issue by ricksq** [Courseplay/courseplay#1182]
Hello,

Is it possible that you can see in what mode courseplay drives and what type of loading is selected to load?

example: When you selected MODE1 and drive the course.. all info is disappeared.

Best regards,

Rick

**Comment by Satissis** [comment]
As of right now, you can see the mode on the bottom together with the course name, it's marked as it's mode icon.
The grain type is not shown thou.

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
