### ISSUE TITLE
courseplay freezes FS2015 

### ISSUE THREAD

**Issue by errandboy** [Courseplay/courseplay#1185]
i have been using courseplay for about 100 hrs and haven't had any real issues or problems with it.  

the last few days i have had problems where it will freeze the game.  i have tried different scenarios ie: tractors, combines, trailers etc... with no luck of isolating the problem.  i have deleted all of the recent mods, and others that i wasn't using.  

after playing for about 5 minutes 1 of two things will happen.  

#1 after selecting "drive course" button in the CP menu the game will freeze after the 3rd vehicle is given instructions to drive using courseplay.   the previous two vehicles work fine, its always the 3rd vehicle that triggers the problem.

however there have been times when the game was frozen but my mouse cursor still worked, and after telling the driver to "stop" in the courseplay menu everything within game would go back to normal, until i then selected "drive course" again.  During this time that the game was non responsive, other combines that were already running under courseplay would drive erratically, evidenced by the trails through various fields.  it seems during this period when game is "frozen"  & non responsive other combines working under courseplay will begin to drive erratically.  

#2 the game would totally freeze and the only way to exit it to go to the desktop and close the game from there.  I've enclsoe the most recent log file.  i know very little how to read this, but notice a lot of errors for the fruit mod... i've been using it for some time along with courseplay with no problems.

thanks in advance for your help!  lease let me know if  there is anything else i can do to assist.

**Comment by errandboy** [comment]
PS i tried to add my log file, but it said it was too long...

**Comment by ThomasGaertner** [comment]
paste your complete log to https://gist.github.com/ and post the link here, then we will see...

**Comment by errandboy** [comment]
https://gist.github.com/78a74cd25e81d49924e3.git

thank you!

**Comment by errandboy** [comment]
https://gist.github.com/78a74cd25e81d49924e3.git

thanks!

**Comment by ThomasGaertner** [comment]
you have a lot of errors in your log, please clean up your mods and try again. 
if it still occurs, then activate Debug Channels 4 and 6 and post the log again ....

**Comment by errandboy** [comment]
ok, i'll do that now and let you know - thanks.

**Comment by errandboy** [comment]
https://gist.github.com/37bb00be07ef826dc1c7.git

**Comment by ThomasGaertner** [comment]
I'm sorry, but I can't help you until your log is clean. please remove all the faulty mods from your mods folder and try again and report the log again ....

**Comment by errandboy** [comment]
ok, i'll go back and delete them all.  some that i have already deleted still give an error message regarding the name.

**Comment by errandboy** [comment]
deleted all but a few mods and not surprisingly your fine piece of software is performing marvelously.  I will get a few more tractors going and see how it goes and post the log here in an hour.  
thanks so much for your help!  its greatly appreciated.

**Comment by errandboy** [comment]
ok here it is.  seems to be working flawlessly now.  

https://gist.github.com/7a19a67abc44bd1fa9ac.git
