### ISSUE TITLE
not working courseplay

### ISSUE THREAD

**Issue by lomar2006** [Courseplay/courseplay#1187]
courseplay

log

GIANTS Engine Runtime 5.0.1 (build date: Mar 31 2014)
Copyright (c) 2008-2012, GIANTS Software GmbH (www.giants-software.com), All Rights Reserved.
Copyright (c) 2003-2012, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: FarmingSimulator2013
Main System
  Cpu Name: Intel(R) Core(TM)2 Quad  CPU   Q9450  @ 2.66GHz
  Cpu Core(s): 4 @ 2.7 GHZ
  OS: Windows NT 6.2 64-bit
Physics System
  Driver: NVIDIA PhysX Runtime
  Version: 2.8.4
  Thread(s): 2
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick disabled
  Force Feedback disabled
Sound System
  Driver: OpenAL
  Version: 1.1
  Device:  Generic Software
  Max. sources: 256
Render System
  Driver: OpenGL
  Card Vendor: ATI Technologies Inc.
  Renderer: AMD Radeon HD 7800 Series
  Version: 4.4.12874 Compatibility Profile Context 14.100.0.0
    GL_NV_texture_compression_vtc not supported
    GL_NV_vertex_program2_option not supported
    GL_NV_vertex_program3 not supported
    max_texture_layers: 8
  OpenGL initialization successful
Hardware Profile
  Level: Medium (auto)
  View Distance Coeff: 1.000000
  Shadow Quality: 1.000000
  Skip Mipmaps: 1
  LOD Distance Coeff: 1.000000
  Terrain LOD Distance Coeff: 1.000000
  Foliage View Distance Coeff: 1.000000
Farming Simulator 2013 INT
  Version: 2.1.0.2 RC3
  Available Languages: en de fr es it ru jp
  Language: ru
Game vehicle types loaded
Mod directory: C:/Users/Alex/Documents/My Games/FarmingSimulator2013/mods
Load mod: FarmingSimulator2013ClassicsPack
Load dlc: pdlc_titaniumAddon
Load mod: ZZZ_courseplay
Error: Unsupported mod description version in mod ZZZ_courseplay

What could be the reason?

**Comment by Raints** [comment]
First try to update your game and then try again.

**Comment by lomar2006** [comment]
and what version it is now urgent?

**Comment by lomar2006** [comment]
I have steam a license

**Comment by lomar2006** [comment]
2.1.0.2

**Comment by Raints** [comment]
Sorry, didnt know at first you talking about Farming Simulator 2013.

**Comment by lomar2006** [comment]
Thanks mod works, but now the question is how to put the Russian language?

**Comment by lomar2006** [comment]
I know that there is a Russian version of 4 in it and there is no (

**Comment by Raints** [comment]
http://www.fs-modbox.com/load/scripts_programs_ls13/scripts/courseplay_v_3_41_rus/70-1-0-3488

**Comment by ThomasGaertner** [comment]
@lomar2006 : is it solved for you ? may I close ?

**Comment by lomar2006** [comment]
Thank you very much. Everything works. All the best to you. You can close the topic.
