### ISSUE TITLE
Fertilizing and seeding driving mode with Soilmod

### ISSUE THREAD

**Issue by Azthek** [Courseplay/courseplay#1188]
First i would like to say hello and thank you for this fantastic mod. It makes the game so much more enjoyable.
My issue or rather question is regarding using this mod with Soilmod and more importantly Soilmodtanks mod, which adds separate filltriggers to filltypes implemented by Soilmod.

As per Soilmodtanks mod instructions, I have already modified Courseplay Triggers.lua file to include the new filltriggers and it works fine. The idea is that you create a special refill course for each trigger so that a specific filltype is refilled into your implement.

However I didnt want an extra 11 tanks on my map so I modified the mod a little. I removed the original
fertilizer trigger (from the original map) and I overlapped the new triggers from Soilmodtanks mod at the original fertilizer tank.

And now finally my question - can I modify Courseplay so that during fertilizing and seeding mode it wont fully empty the implement but rather leave something in the tank? This way even if Courseplay drives on overlapped triggers, it will automatically refill the correct type since it is already present in the tank.
Thank you for your answer.

**Comment by Satissis** [comment]
#1346
