### ISSUE TITLE
Problem with attachableCombines mods / "there's a closer tractor that's trying to register:0 "

### ISSUE THREAD

**Issue by THEBIGLL** [Courseplay/courseplay#1190]
Hello, the Kemper Champion 3000 and Mengele Maisblitz 300 doesn't work with courseplay (v4.01.0000). They are both mods and attachable combines like the original Poettinger MEX 5 from GIants. The tractor which should drive to them with the trailer (Deutz 7250TTV) only stands at the beginning of the course. The log is spammed with the same messages about both Harvesters: 
[dbg4 lp10135] 7250 TTV (#1) (176): request check-in @ 0
[dbg4 lp10135] 7250 TTV (#1): registering at combine Kemper Champion 3000
[dbg4 lp10135] 7250 TTV (#1): combine.cp.wantsCourseplayer(nil) or combine.fillLevel == combine.capacity (true)
[dbg4 lp10135] 7250 TTV (#1) (id 176): there's a closer tractor that's trying to register: 0
The full log is here: https://gist.githubusercontent.com/THEBIGLL/2a2fa05823fb72ed6124/raw/log.txt

**Comment by Satissis** [comment]
#1346
