### ISSUE TITLE
Traffic Collision Question

### ISSUE THREAD

**Issue by jhomer** [Courseplay/courseplay#1191]
Working on a mod and couldn't figure out why the traffic collision was not working.
So tried it in develop mode and the triggers seem to move upward for some reason and don't have a clue why, so thought I'd ask. Any thoughts?

Thanks for any help!

![screen](https://cloud.githubusercontent.com/assets/7943994/8665948/ac422e00-29af-11e5-8566-8e135c9fa04a.jpg)

**Comment by ThomasGaertner** [comment]
Plz check the height of your model . The trigger will be set to the highest point of the model ....

**Comment by jhomer** [comment]
Thank you Thomas!!
I understand now.
I increased the scale of the trigger and moved it down further so in-game it looks proper.
Probably not the right fix but it was the best of my little knowledge.
As long as no tractors are buried in the ground around the farm all should be good!

**Comment by ThomasGaertner** [comment]
Be careful , maybe you will get in trouble at traffic lights while running cp
