### ISSUE TITLE
Fill and empty shovel, can't save the positions by mod tractor with original frontloader and shovel.

### ISSUE THREAD

**Issue by D3ltorohd** [Courseplay/courseplay#1192]
Hello,

i have noticed a problem, i use an mod tractor (Eicher_2090) on this i have an original stoll frontloader + the original shovel. Now i will Fill and empty my storage but i can't save the shovel positions. When i look at my log there are the following entries when i use the save buttons for the positions.

Error: Running LUA method 'mouseEvent'.
C:/Users/D3ltoro/Documents/My Games/FarmingSimulator2015/mods//zzz_courseplay/mode9.lua:352: attempt to index a nil value
Error: Running LUA method 'mouseEvent'.
C:/Users/D3ltoro/Documents/My Games/FarmingSimulator2015/mods//zzz_courseplay/mode9.lua:352: attempt to index a nil value
Error: Running LUA method 'mouseEvent'.
C:/Users/D3ltoro/Documents/My Games/FarmingSimulator2015/mods//zzz_courseplay/mode9.lua:352: attempt to index a nil value
Error: Running LUA method 'mouseEvent'.
C:/Users/D3ltoro/Documents/My Games/FarmingSimulator2015/mods//zzz_courseplay/mode9.lua:352: attempt to index a nil value
Error: Running LUA method 'mouseEvent'.
C:/Users/D3ltoro/Documents/My Games/FarmingSimulator2015/mods//zzz_courseplay/mode9.lua:352: attempt to index a nil value

Here the link to pastebin logfile... http://pastebin.com/peMFYTnb

I have test it with original Liebherr Wheel Loader and it works fine.

EDIT:: I have test it with Steyr Standard Tractor + Standard Frontloader from Stoll, and i have the same issue, i think its a problem when it used with frontloader...

**Comment by ThomasGaertner** [comment]
would you please test again with debug channel 10 active and post the log ? thanks

**Comment by D3ltorohd** [comment]
Hm what should i say, i would test it again to record the log with debug 10 but now it works ? I don#t know why. I will test it with the Mod tractor too, but with the orignial it works fine now. But in the past it was the problem, because i post this issue. But i test the other tractor and give feedback.

**Comment by Satissis** [comment]
#1346
