### ISSUE TITLE
Idea: Mode 1 Load at start- # of trips

### ISSUE THREAD

**Issue by jhomer** [Courseplay/courseplay#1194]
Had a thought about the mode 1- load at start course to be able to select a number of trips to make.
The default value being infinite.
To have CP make example: 2 trips then stop at course end.
I have no clue about how much work this would be or how possible it is.
Just a thought, so I'd mention it....
I won't be offended either way so feel free to file this suggestion in the garbage if you wish.

**Comment by ThomasGaertner** [comment]
Can you tell us a situation, where it would be useful? At the moment I can't imagine any ...

**Comment by jhomer** [comment]
My thinking was:
-If one wanted to haul and certain amount of grain to sell place, (save some for animals).
-Hauling feed for animals or moving a certain amount of a grain or forage from one place to the next.
Example: when a trigger is full (animals feed or straw) CP will keep driving the route full until you stop the route. 
Thought if you could start a route and assign CP to make a certain number of trips then stop on their own after the trips number is reached.

If you think it's worth while, or if not, I'm good with that too.

**Comment by tryst46** [comment]
Selling produce. Because the price drops as you sell more, you may only want to run a certain number of trips before stopping and waiting until the price increases again.

**Comment by TenroNamikaze** [comment]
It would also be useful for completing transport missions. Adding to the idea would it be possible to add an option to delivered a specified amount I.e. If you have a shipping mission to supply 52tons of grain you could select to keep going until the amount is met.

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
