### ISSUE TITLE
Combine helpers in tandem.

### ISSUE THREAD

**Issue by tryst46** [Courseplay/courseplay#1195]
When we have maps that require a lot of travel between the field and the dump off site, we could use overloaders but there is another way if it can be coded into Courseplay.

Two or more combine helpers working in tandem. While one is empty, it will unload the combine and act as normal. The second one assigned to that combine will sit and wait. When the first is full, it starts the journey to the silo or wherever it need to dump it's load. The second helper then takes over to keep the harvester going and the first one waits for him to become full up and start the journey to dump his load.

If both helpers have the same course loaded, it only requires a boolean flag to be attached to the combine they are both assigned to in order to tell the waiting helper that the combine is being tended to at present. The waiting helper waits at the end point of the course for the first helper to finish before activating the "waiting for fill level" state. The one that is working keeps the boolean flag active until he is fully loaded when he then resets the flag before going off to unload his trailer. The waiting one then sets the flag to notify the other one that he is still active, forcing the other one to wait until the flag is reset again.

Not really sure how easy it would be to add this into the courseplay script but it would be helpful for those with multiple tractors and trailers who don't want to pay out extra for overloaders.

Because I want the best price for my produce, I prefer to store it in my silos etc and wait until the price is right to sell it. I have several fields that, when the tractor has unloaded the combine and is full, it takes so long to get to the silo that the combine is standing idle for some time. I have too many fields to have combines standing idle, I need them to finish and move on to the next field to get all the fields harvested before they spoil.

Another minor point would be to allow a driver helper script to run X number of times. That means we can sell X loads of produce and then the driver will stop running the course.

**Comment by ThomasGaertner** [comment]
try to set the driver priority to " fill level"  instead of distance . If I understood right, this is what you asked for ....

**Comment by Satissis** [comment]
#1346
