### ISSUE TITLE
 CP drivers do what they want

### ISSUE THREAD

**Issue by shriek1977** [Courseplay/courseplay#1196]
Course Play Version: 4.01.0000

CP driver hangs
when I get out, he goes out only just; no vehicle can go into more
log:
http://uploaded.net/file/qgd4icpd

pictures say more than words:
http://uploaded.net/file/ze8hd1rq

hope to hear from you soon
sorry me english is not well

**Comment by ThomasGaertner** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by shriek1977** [comment]
LOG
https://gist.github.com/shriek1977/1414822bdda14da5400b

**Comment by Satissis** [comment]
#1346
