### ISSUE TITLE
Combi mode field select instead of harvester

### ISSUE THREAD

**Issue by Gieke85** [Courseplay/courseplay#1198]
Can it be made so combi mode tippers dont manual select a specific harvester but a specific (edge calculated) field?

Keep up the good work :)

**Comment by gui7545** [comment]
hey,
you have to set the automatic detection: http://courseplay.github.io/courseplay/en/manual/index.html#hud_manageCombine

**Comment by Gieke85** [comment]
But that only works if the end point of the combi route is inside the field and therefor blocks a certain area of the field from being worked by other vehicles.
I prefer to have the waiting point of the combi tipper on the grassland next to the field so it doesnt block anything but still be able to assign it that specific field

**Comment by Satissis** [comment]
#1346
