### ISSUE TITLE
Work stops on switching vehicle (tab)

### ISSUE THREAD

**Issue by Roktaal** [Courseplay/courseplay#1200]
Whenever I press tab to switch vehicle, the vehicle I was on, that was mid course (with refill), stops the job and goes around refill route and then goes back to the start of course, follows main course for few seconds and then goes to refill again and so on. If I stay on the vehicle it follows course without problems. At moment I press tab debug shows [dbg17 lp5179] Amazone ZAM 1501: turn off order.
Same thing happens with combine unloading, vehicle stops whatever it is doing, goes to the start of the course, follows the route once, comes to the waiting point and waits for few seconds than goes around again.
For silos unloading same thing. Vehicle stops whatever it was doing, goes to the start and does full round (without loading goods)
* Courseplay v4.01.0000
* Courseplay v4.01.0109dev

**Comment by ThomasGaertner** [comment]
Did you change the input bindings ? Pleas post the whole log to gist and deliver the link . Thanks

**Comment by Roktaal** [comment]
Never mind. Found out that the problem was caused by Separate Fill Level v1.0 http://www.ls15mods.com/separate-filllevel-v-1-0/
Guess I'll write my own separate fill level script :)
