### ISSUE TITLE
LS 15 locks up when you play with courseplay

### ISSUE THREAD

**Issue by Teimo** [Courseplay/courseplay#1201]
hello
I'm new here come from Germany I hope google überstzt the whole good.
I have a problem with courseplay every time I saw or hächseln or Mechen work other wants than going with courseplay the ne minute well and then hangs I play see only can drive the downhill when I sit in choppers send him everything works just me can not intervene lets choppers are at once everything and brings nevertheless what on the trailer I can do the Helfter resist out hohre as I return value and forward drive but can not see where go I go because the choppers is always at the same place and my keyboard reagiet no in the game used more ESC key does not work anymore, I can only on the Windows key to get out and so the game is nothing else close.

Here my Log.txt
http://cloud.directupload.net/16dM
Teimo

**Comment by Satissis** [comment]
#1346
