### ISSUE TITLE
Seeding + Fertilizing refill problem

### ISSUE THREAD

**Issue by Roktaal** [Courseplay/courseplay#1202]
I'm using Amazone ZAM 1501 (Front) together with Vaderstad Rapid A 600S (Rear) to seed and fertilize at the same time. The problem is with refilling course. Because the in-game fill amount is not separate for each implement, Courseplay doesn't recognize when my ZAM 1501 runs out of fertilizer. so it refills only when both implements are completely empty.
This combo works fine using built-in autopilot because the game automatically deducts cash from my account for the fertilizer.

**Comment by benjoglove** [comment]
I had the same issue a while ago. You need to change your fertiliser level in your mod to equal or geeater than seed. That way they will refill at same time.

**Comment by Satissis** [comment]
#1346
