### ISSUE TITLE
sugestion: why Headland BEFORE doing Fieldwork? Make it avialable after done the field

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/courseplay#1203]
In Real Life headland is done after you prepared the field, 

and if you have machines which don´t get directly close to the last working areas you can smooth out this mistakes by doing  the Headland.

As the headland is, in my opinion it makes only sense for combines or corn-cutters, but the corners are not calculated very good.

Just for discussion it.

BR

Neo

**Comment by gui7545** [comment]
Hello,
It is currently possible to do what you want, this spec is already in courseplay.
 See below : https://courseplay.github.io/courseplay/en/manual/index.html#hud_courseGeneration
See the part : " Headland"

**Comment by RealNeo80** [comment]
ok, found it, thanks.

should we discuss here about the calculation of the headland, or is another place better for it?

e.g. the Corners should not be driven "round" they should be done straight, set 90 degree back and than straight forward, so you get sharp edges.

the field work should go about 1/3 into the first headland lane, so that it is covered completely with the headland turns

**Comment by Satissis** [comment]
#1346
