### ISSUE TITLE
Abfahrer fährt Zick Zack

### ISSUE THREAD

**Issue by Haraldeh** [Courseplay/courseplay#1207]
Sorry, mein Englisch ist miserabel,
ich hoffe das jemand von Euch Deutsch kann
Folgendes Problem:

Ich habe einen Abfahrer Kurs angelegt.

Beim ersten Abfahren oder wenn der Abfahrer vom Silo zurückkommt, funktioniert noch alles. 

Aber wenn der Abfahrer irgendwo auf dem Feld steht, der  Drescher bei eingestellten 80 % Füllstand ist, fährt mein Abfahrer los, aber nicht Richtung Drescher sondern Zick Zack gerade aus. 

Das gleiche passiert, wenn der Abfahrer Füllstant 100 % hat und eigentlich den Kurs zum Silo anfahren soll, fährt er vom Drescher zick zack weg, aber nicht Richtung Startpunkt zum Silo.

Liegt das am CP oder Giants ?

**Comment by Satissis** [comment]
#1346
