### ISSUE TITLE
Fieldworkmode addition  beet

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#1209]
Hello guys,
I wan't to ask if it is possible to implement a beet work mode (don't know if its called so in english; its when the working vehicle starts from the ends or the middle of the field, face always with the same side to the already worked area).
This would be great for harvesting large fields, so the combine always faces pipe towards threshed area so the drivers dont need to drive into the fruit if the combine gets full.

Look at the image, I've tried to visualize my plan as good as i can...

![beet workmode](https://cloud.githubusercontent.com/assets/9157835/9150195/322c5cc2-3dcc-11e5-9eaa-1514beb946d4.png)

So, first the headland is worked, then according to the numbers the strips downfield...

hope I could explain my thoughts good enough...
Greets JD_TIger

**Comment by Satissis** [comment]
With the current system it will not be able to do that. Cant say if there will be an option for that in an later version, when we get around to finish the new field generation script.
#1346
