### ISSUE TITLE
Forage Wogan wont drive the unloading course in Fieldwork mode

### ISSUE THREAD

**Issue by emwedk** [Courseplay/courseplay#1210]
I have seen this work in earlier version. it even states it in the manual.
I simply get an indication that the forage wagon is full, and needs to be emptied.

Have tried these following things to make it work.
- make the start point of the Unloading Course, drive over the trigger, drive back to field, save, load generated field course and load the Unloading course

- also tried to set a waiting point on the trigger (now the wagon don't wanna pick up from the field)

- tried with several kinds of forage wagons

**Comment by Flextt** [comment]
Forage Wagons seem to ignore tip triggers in Fieldwork mode, when they are not a 100% full. Did you try that?

Ladewagon ignorieren anscheinend Ablade-Trigger im Feldarbeitsmodus, wenn sie nicht 100% gefüllt sind. Hast du es dann mal probiert?

**Comment by Satissis** [comment]
#1346
