### ISSUE TITLE
FS15 freeze with Seeder & Fertilizer

### ISSUE THREAD

**Issue by santo80** [Courseplay/courseplay#1211]
Hi, i play with P.Valley Map 1.3.2 , i generate the recorder on field 78 for Amazone 40m seeder, and for   Amazone 40m fertilizer. When i start both tractors goes, but when i switch on other tractors or escape from a tractor ..the game freeze and i must kill fs15 from TaskManager.

i try with default seed and fertilizer and it's all ok.  It's a log to activate for monitoring the problem?
it's a incompatibility between cp 4.01 and mods ?

Ideas?

**Comment by Marv63** [comment]
its on my one 2 but i have the bourgalt v 5

**Comment by Marv63** [comment]
FIXED it on the bourgalt the modder has build in markers.... which not existing :D 
U unpack ur mod on the desktop than you open the ModDesc.xml and if u use notepad++ u can search with the search funktion Marker and than u delete every line where marker is in it. 
After that u open the other .xml in my case bourgalt.xml there u search for Marker do up until there is a  or  <!-- line than delet this put those both back into the .zip and it should be done :D hope I helped u

**Comment by Satissis** [comment]
#1346
