### ISSUE TITLE
 tractor runs in to fence that is around the field

### ISSUE THREAD

**Issue by bigb5134** [Courseplay/courseplay#1212]
i am playing the nebraskaland map and there is fences around all of the fields i have activated the headland option and it still runs in to the fence

**Comment by gui7545** [comment]
How close the fences are close to the field ? Do you have screenshot ? you know that you can do more than one turn of headland. Maybe 2 turns will solve your problem.

**Comment by bigb5134** [comment]
Ok I will have to try that

**Comment by sootysax** [comment]
I would plant a few headlands of grass around the edges of the field and re-define the field edges.

**Comment by chaskuchar** [comment]
I am playing Nebraskaland map also.  if you are going in circles with courseplay, plant maybe 12m headlands of grass.  I just plant grass headlands on two sides and then let the combine and planter go back and forth between the two.  bigger machines need more headland.  chas

**Comment by Satissis** [comment]
#1346
