### ISSUE TITLE
LS13 MoreRealistic Tractors will not work with CoursePlay 3.41

### ISSUE THREAD

**Issue by Hawk141198** [Courseplay/courseplay#1213]
Standart HagenstedMap - CoursePlay v3.41 - MoreRealistc v1.3

I installed 3 mods:
1. moreRealistic
2. moreRealisticGenuineMap
3. moreRealisticVehicles
4. ZZZ_courseplay

Started a new gameslot and recorded a path for a MoreRealistic Tractor. After finishing the recording, I wanted to start the tractor driving but he won't! After a time a errorframe popped up which is saying "Not enough motorpower! Please inspect power and devices"!

![2015-08-16_00002](https://cloud.githubusercontent.com/assets/10948073/9294956/eda5f7e6-445d-11e5-99e3-475eaa275469.jpg)

I searched for the reason, found an issue with the same problem and installed the dev version from GitHub(Date:8.6.2015) but then courseplay was totaly unuseable.

Log: http://pastebin.com/w3juZBNc

**Comment by Hawk141198** [comment]
Forgot the log.txt:
https://gist.github.com/20f19b0ac761833c7afd.git

**Comment by gui7545** [comment]
When you take the dev version from github, i think you took he dev version for FS2015.
Here is the link for the la dev version for FS2013: https://github.com/Courseplay/courseplay/tree/FS13_finalish
Here is the way how to install the dev version : http://courseplay.github.io/courseplay/en/installation/index.html

**Comment by Hawk141198** [comment]
Perfect! Now it's running! Thanks a lot!
