### ISSUE TITLE
tractor driving in circles or in the ditch

### ISSUE THREAD

**Issue by Farmingstories** [Courseplay/courseplay#1214]
when the tractor behind the combine drive then at each corner a big first lap before which the trigger again engaged. if there is a ditch or a fence nearby is riding in it there. this can be solved in a way and vandere. because'm not really good

**Comment by chaskuchar** [comment]
I solved the tractor going in circles by increasing the turning radius

**Comment by Farmingstories** [comment]
I hope its working for me

**Comment by Satissis** [comment]
#1346
