### ISSUE TITLE
tractor/tipper is parking right where the corn is after unloading the combine.  combi mode.

### ISSUE THREAD

**Issue by chaskuchar** [Courseplay/courseplay#1215]
once in a while the tractor stays outside the corn but normally it parks with end row of corn in the middle of the tractor.  if the combine has a long way to go, then it will request the tractor before it comes to it standing in the field.  however if the combine unloads and then has a short path to turn around, the tractor is right in the way.  then I request tractor and it moves out of the way.  combine is c6 combo and tractor is h488.  other problem is when the tractor drives up to unload the moving combine, the h488 gets right to the pipe and then slows down to 3kph.  the combine is moving faster than that so the tractor never catches up to the combine until the combine is full and stops.  don't know what to do on that.  chas

**Comment by OSSammler** [comment]
Das erste Problem hab ich auch. Besonders auffällig ist es, wenn der Drescher mit Autocombine im Kreismodus fährt. Der Traktor fährt nach dem Abtanken zu dicht an den Drescher heran, so dass dieser nicht genug Platz für sein Wendemanöver hat.

Könnte das mal bitte jemand übersetzen. Mein englisch ist nicht so gut und mit googletranslate versteht das wohl auch niemand. DANKE

**Comment by chaskuchar** [comment]
finally I translated your response.  you seem to have the same problem I am doing.  sometimes different tractors have different results on different combines.  still experimenting with courseplay and the combi mode.  thanks, chas

**Comment by Satissis** [comment]
#1346
