### ISSUE TITLE
Krone Big L500 (Mower with integrated Tipper) not able to unload into Biogas Plant Bunkers in Fieldwork Mode

### ISSUE THREAD

**Issue by Flextt** [Courseplay/courseplay#1217]
Hello Courseplay-Team,

I am using the Krone Big L500 mod. It is a truck with a front-attached foldable mower and an integrated tipper. None of the available versions work in Courseplay, however I copied a Traffic Collision Trigger from the Deutz 6.61 into the model and modified the mod's xml to include the correct index path. 
TL;DR: Courseplay didnt work with that mod before (see numerous forum entries on any mod site), now it does.

edit: The map is a modified version of Bjornholm. However, I only changed elevations at a few points to ease field work.

I want to fully automize the mowing process with that single vehicle. I want him to mow a field and at 100% fill status, drive to a Biogas Plant (BGA) silo I specified to unload and resume working seamlessly. Unfortunately, the BGA triggers seem to be ignored in Fieldwork Mode. The truck does not slow down to the specified BGA speed level upon entering the premises and fully ignores the trigger. 

What I tried so far:
Using Mode 3 (Overloader), which is unfortunately not accepted due to the Mower not being an Augur Wagon.
Using Mode 2. Mode 2 causes him to recognize that he enters the BGA and causes him to tip his load into the bunker, but for obvious reasons he ignores his own fill status and will drive the full course regardless of fill status.

Interestingly, this issue does not seem to affect Loading Wagons. 

Log Link: http://pastebin.com/vt7ZmUw5

Thanks in advance

**Comment by gui7545** [comment]
Hello
You have to use mode 6 : Field work : http://courseplay.github.io/courseplay/en/manual/index.html#driveMode6
You have to record/create two different courses: One for the work on the Field, and the second one is the unload course

**Comment by Flextt** [comment]
I have tried this with a saved field course and one run through the BGA. The mower fully ignored the BGA triggers and drove at street speed. I tried it with both a small percentage of fill status and 100% fill status. The loading wagon however successfully unloaded with 100% fill status.

**Comment by gui7545** [comment]
You can use the Krone Big M500 Attach instead. You have to add the trailer This mod is working with courseplay.

**Comment by Flextt** [comment]
Thank you, gui7545. Works like a charm. I avoided the Krone Big M500, since I didnt need another mower, but with an attached loading wagon, this is a completely different thing.

Since the Big L500 is both no longer being actively supported nor well documented, it is maybe for the best to avoid this mod.
 
This issue can be closed, since it is most likely related to the mod itself.
