### ISSUE TITLE
Tractors Driving Funky

### ISSUE THREAD

**Issue by christianxxgames** [Courseplay/courseplay#1218]
i have been a fan of course play since fs 2013 and now in fs 15. i play on bjornholm and whenever i create a course to sell crops and the tractors/semi's always swerve around causing them to crash into something.

Please help ASAP

**Comment by sootysax** [comment]
slow down

**Comment by Flextt** [comment]
A good speed to record courses is 30 kmh. Vehicles or trailers with high weight or too many flexible axles can cause further problems.

**Comment by Satissis** [comment]
#1346
