### ISSUE TITLE
small pop up display

### ISSUE THREAD

**Issue by hackselgut** [Courseplay/courseplay#1219]
I would like to know what button I happened to hit to get a small Visual display of a course I just made for my farm. I like the display, but I do not know how to Deactivate it for now, and re activate at a later time. Picture attached.. Bob..
![fsscreen_2015_08_27_20_19_37](https://cloud.githubusercontent.com/assets/10256656/9536673/a889a3fe-4cfc-11e5-8b61-4ce3476a7032.png)

**Comment by gui7545** [comment]
This one :
![fsscreen_2015_03_16_11_04_10](https://cloud.githubusercontent.com/assets/2854643/9539173/4c7667b2-4d4e-11e5-8afc-7322af4eb51d.png)

**Comment by hackselgut** [comment]
Thank you very much  Bob
