### ISSUE TITLE
 Animation of the player's arm.[Solved!]

### ISSUE THREAD

**Issue by MoslessNeo** [Courseplay/courseplay#1224]
Hello everyone.
There is the possibility to disable the animation of the player's arm in the script CP?
Or to cancel the animation?

Although the team did not admit that there is this problem, I confirmed with many of my friends from other forums.
We make use of large maps.
About 7 months, since the team does not implement anything in the code, I do not play.

Jakob Tischler, Thomas Gärtner and Satis did a great job. I am very sad to know that the team "stopped" indefinitely. To the point that the PC has come, it is essential in the game.

I hope someone can give me feedback on the possible cause of this grotesque bug.

There seems to be an incompatibility with the CP.
I do not have most of the problems that the staff speaks here. It all depends on how you work with the CP in the game.
But the problem I'm having, I'm really bug.

![01](https://cloud.githubusercontent.com/assets/6533809/9646456/37408d40-51aa-11e5-8b5d-9a7cd02446f9.jpg)

My temporary solution was "off" the animation arm.
![02](https://cloud.githubusercontent.com/assets/6533809/9646457/3743dc7a-51aa-11e5-8662-3401c00648d3.png)

![03](https://cloud.githubusercontent.com/assets/6533809/9646458/3745af1e-51aa-11e5-9b35-0f02e01f56ef.jpg)

![farmingsimulator2015game 2015-09-02 19-48-25-42](https://cloud.githubusercontent.com/assets/6533809/9646606/ae859db8-51ab-11e5-9c81-96b88e531b79.jpg)

With time, the deformation will increase...

**Comment by MoslessNeo** [comment]
Found a possible solution is to turn off the animation arm:
1. Go to the directory:
C: \ Program Files (x86) \ Steam \ steamapps \ common \ Farming Simulator 15 \ data \ vehicles \ steerable
2. Select the make of your vehicle
3. In this example:
C: \ Program Files (x86) \ Steam \ steamapps \ common \ Farming Simulator 15 \ data \ vehicles \ steerable \ NewHolland
4. Open the file .i3D
newHollandCR1090
5. Scroll to transform the group called "steeringBase"
6. Look for player_leftHand
There may be two, namely player_leftHand and player_rightHand
7. Place an X at the end of the object name
player_leftHandX

8. Open the .xml file
In this example, I will open the file newHollandCR1090.xml
9. Go to characterNode
Look for leftArm and rightArm, put an X in the end.

![01](https://cloud.githubusercontent.com/assets/6533809/9786211/a53ea0a4-578e-11e5-888c-7747f90caf7a.png)
![02](https://cloud.githubusercontent.com/assets/6533809/9786212/a543cc46-578e-11e5-899c-158aa49b29e6.png)

**Comment by Satissis** [comment]
#1346
