### ISSUE TITLE
ropa big bear

### ISSUE THREAD

**Issue by KAAG101** [Courseplay/courseplay#1225]
hey i have a problem with ropa big bear. when reqestet the game freeze, and i get tihs in the log file
Warning (LUA): Argument to method 'worldToLocal' is not a string, and not nil
C:/Users/Thomas-stor/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/mode2.lua:247: attempt to compare nil with number
-- from =C:/Users/Thomas-stor/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/mode2.lua:240
Error: Running LUA method 'update'.
hope you can help

**Comment by KAAG101** [comment]
i have fixed it, i add some lines  the specialTools.lua. dont know if it is the best solution but it works. here is whot i added 
	elseif workTool.cp.hasSpecializationrBigBearFSM then
		workTool.cp.isAugerWagon = true;
		workTool.cp.isRopaBigBear = true;
		workTool.cp.foldPipeAtWaitPoint = true;
		workTool.cp.hasSpecializationBigBearV2 = workTool.setUnloading ~= nil and workTool.setWorkMode~= nil and workTool.setActiveWorkMode ~= nil;
	elseif workTool.animationParts ~= nil and workTool.animationParts[2] ~= nil and workTool.toggleUnloadingState ~= nil and workTool.setUnloadingState ~= nil then
		workTool.cp.isAugerWagon = true;
		workTool.cp.isTaarupShuttle = true;

**Comment by Marv63** [comment]
THank u :dancer:

**Comment by Satissis** [comment]
#1346
