### ISSUE TITLE
Wrong waypoint after reverse tip

### ISSUE THREAD

**Issue by davidhunt135** [Courseplay/courseplay#1227]
After running a course that includes a reverse tip the tractor tries to go to a much later waypoint. Once it has reveresed and tipped, rather than follow the waypoints that were recorded it seems to try and go to the nearest waypoint further down the course. This means the tractor is trying to crash into things between the tip trigger and another part of the course.

**Comment by benjoglove** [comment]
David can you place some pics with your way points showing and hud open and I should be able to help you out.

**Comment by Satissis** [comment]
This is fully intentional, since if it didn't find the closed waypoint ahead of the tractor, it would try turn around and head to the place you reversed to, which would be bad.
You will have to plan ahead and give it a couple of waypoints forwards again before turning.

#1346
