### ISSUE TITLE
Courseplay: Bale offloading

### ISSUE THREAD

**Issue by jffouche** [Courseplay/courseplay#1228]
Hi

When I load course to load bales and second course to offload, after it offloaded the farmer in the
tractor disapear and the tractor drives of in that direction.

The wheels of the tractor stand still but the tractor keeps going.
Allso when I load the course to load the bales then it does the same thing, tractor goes in same direction with farmer gone, after I load one bale on the trailer and select drive course it does the work untill it offload the bales, then the same thing happens over again.

Please help!!

**Comment by jffouche** [comment]
Hi

So after my first post, I went back to game and found that it happens with overloaders allso.

When it offloaded and is empty the tractor just goes untill it hits the end of the map or a object.
When it does that I go to combine load a little bit of grain and then click the drive course icon and then it works as it should untill it offloads again, then the hole problem starts over again.

Same with the Bale trailer.

**Comment by davidhunt135** [comment]
Looks like no one is doing anything on courseplay for now. Is the tip point being done in reverse? I have a problem where after reversing to tip it will then just drive off in a straight line

**Comment by jffouche** [comment]
No, its not done in reverse. Looked at some videos on youtube to see how the best way is to create the 
course. But still doing the same thing.

**Comment by jffouche** [comment]
Ok so found the problem!
It is Autotractor that causes the problem, just deleted it now everything is fine!!!!
