### ISSUE TITLE
courses lost after i put them in a folder 

### ISSUE THREAD

**Issue by bigb5134** [Courseplay/courseplay#1229]
i made some courses up using lane change and i put them in a folder to organize them and when to use them again and the tractor just drives in circles. i deleted the courses thinking they were bad and tried to make new ones and the tractor still drives in circles. i have the newest version of courseplay i now that its not a mod conflict because i haven't put any new mods in my mod folder i have tried to move the tractor seeing if it was trying to find a way point but it drives back to the same point and drives in circles i am going to try to delete the courseplay mod and reinstall the mod

**Comment by Satissis** [comment]
#1346
