### ISSUE TITLE
Reversing and wait points

### ISSUE THREAD

**Issue by benjoglove** [Courseplay/courseplay#1232]
Hi,

I'm playing BigFarm15 and reverse a breeding trailer up to a ramp to load cattle on. The trailer reverses fine, collects a certain percentage of cattle and then drives on. I am trying to place a waiting point so it only drives on once full. Can this be achieved?

Problem I am having is that I place the waiting point were the trailer stops however the semi of course wants to keep reversing until it reaches the waiting point, so unsure on were the waiting point should be placed whilst doing the reverse course. Hope this makes sense, if not, I'll add some pics. Thanks in advance.

**Comment by gui7545** [comment]
Hello,
You need to use mode 1 as explain here : https://courseplay.github.io/courseplay/en/manual/index.html#driveMode1

**Comment by benjoglove** [comment]
Hi Gui7545, thanks and I use that mode. How can we make it stay there to the full 100% loading? Is it a setting in the waitpoint? At the moment it touches waitpoint then goes again onto the next route to the abattoir.

**Comment by gui7545** [comment]
As explain on the wiki, you have to set the setting "drive on at" at 100%

**Comment by Satissis** [comment]
#1346
