### ISSUE TITLE
Survey: I would pay for multiplayer

### ISSUE THREAD

**Issue by elpatron68** [Courseplay/courseplay#1233]
Courseplay has kicked Farmingsimulator 2015 to a whole new level of gameplay. I would be excited to see a version of CP supporting Multiplayer Gameplay. And I´m sure I´m not the only one.

I know that it´s probably no question of money but of time to be spent on this project. But if you agree with me in the question that some money may help: Fill out this survey and spread the word!

Follow this [link to Google Forms](http://goo.gl/forms/IvpTqzxyxf) to support the further development of Courseplay!

Post this survey to any related website/forum/modhoster/social media to help the development!

Share the survey on
[Facebook](https://goo.gl/dm9LRl)
[Google+](https://goo.gl/ppyxaW)
[Twitter](https://goo.gl/18nZ6R)

@dev: This is no ticket, so close it immediately if you like to.

**Comment by SpaceShot** [comment]
Is there an issue that highlights the problems with Courseplay multiplayer?  I was just curious what the obstacles were.  This seems to be a mod that highlights just how far you can go with FS15 modding.  I'm not sure I can pull it apart but I'm sure going to look at it.

**Comment by Kickbub** [comment]
It used to support multiplayer. They are currently rewriting the code from the ground up. All we can do now is wait.

**Comment by johnelder** [comment]
I'm a software developer and would be interested in forking and looking at multiplayer.  Are there any notes on what the multiplayer issues are?

Thanks
John Elder
