### ISSUE TITLE
Any chance of Making AI Leave the Lights on at Night??

### ISSUE THREAD

**Issue by mikeloeven** [Courseplay/courseplay#1235]
It always annoyed me how as soon as you get out of a tractor being driven by course play all the headlights are turned off by the AI driver this seems kind of stupid and the AI should either leave the lights as they were when the player was driving or have a script that makes them turn on headlight and work lights when operating at night

**Comment by Satissis** [comment]
I believe this has something to do with with Giants, since that's the normal behavior with the hired worker as well
Anyway: #1346
