### ISSUE TITLE
Krone Ultima

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#1237]
Hi Guys!

Will there be a Course Play support for the Krone Ultima ??

LG

**Comment by Galwaygrass** [comment]
Is the McHale Fusion also supported?

On Wed, Sep 23, 2015 at 3:00 PM, Paul2510 <notifications@github.com> wrote:

> Hi Guys!
>
> Will there be a Course Play support for the Krone Ultima ??
>
> LG
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Courseplay/courseplay/issues/1237>.
>



-- 
Regards,

Mark

**Comment by Tanglewolf** [comment]
iv managed to adjust the specialTools.lua to work with the fusion 3 mod, but i dont know if it would work with the Ultima. Open the specialTools.lua and search for 'ursusZ586', this is giants wrapper and has special needs that courseplay caters for. Below is the script entry for the ursus followed by the entry i added for the fusion. Do Not replace the ursus entry with the fusion entry as then that wont work. I may have this wrong but currently its working for me

`-- Ursus Z586 bale wrapper [Giants]
	elseif workTool.cp.xmlFileName == 'ursusZ586.xml' then
		workTool.cp.isUrsusZ586 = true;
		
		-- fusion 3 combi
	elseif workTool.cp.xmlFileName == 'mchaleFusion3.xml' then
		workTool.cp.isMchaleFusion3 = true;`

`--Ursus Z586 BaleWrapper
	if workTool.cp.isUrsusZ586 then
		if workTool.baleWrapperState == 4 then
			workTool:doStateChange(5)
		end
		if workTool.baleWrapperState ~= 0 then 
			allowedToDrive = false
		end

		return false ,allowedToDrive,forceSpeedLimit;
		
	--fusion 3 combi baler
	elseif workTool.cp.isMchaleFusion3 then
		if workTool.baleWrapperState == 4 then
			workTool:doStateChange(5)
		end
		if workTool.baleWrapperState ~= 0 then 
			allowedToDrive = false
		end

		return false ,allowedToDrive,forceSpeedLimit;`

`elseif object.cp.isUrsusZ586 then
		self.cp.aiTurnNoBackward = true
		self.cp.noStopOnEdge = true
		self.cp.noStopOnTurn = true
		automaticToolOffsetX = -2.5;
	elseif object.cp.isMchaleFusion3 then
		self.cp.aiTurnNoBackward = true
		self.cp.noStopOnEdge = true
		self.cp.noStopOnTurn = true
	end;`

**Comment by Satissis** [comment]
#1346
