### ISSUE TITLE
Some things that need to change for silage Processing

### ISSUE THREAD

**Issue by mikeloeven** [Courseplay/courseplay#1238]
I ran into a bit of an issue using course-play with a front mounted silage cutter that basically allows you to drive through the silo throwing the silage into trailing wagons similar to a forage harvester 

The issue is that in order to function properly the tractor needs to be going under 1 km/h. any faster and the tractor will overwhelm the implements transfer rate at which point the tractor will climb on top of the silage and not empty the silo completely. 

the problems are that 
A: Courseplay seems to have a lower limit of 3 km/h 
B: when making a course that is just a straight line you cannot override street speed 
C: the silo is considered street speed so whatever speed you record the path is the speed the tractor goes and i would rather not have to drive 1 km/h down the entire length wasting my time when i should be able to override street speed in the settings.

**Comment by AlphaXray** [comment]
Have you tested to increase the overloadning rate of the tool instead?

look for values
    <capacity>100</capacity>
	<overloadingCapacity>1250</overloadingCapacity>

**Comment by AlphaXray** [comment]
Abit late but I did some tests on the front mounted silage cutter - fraese 2.0. 
In the Fraese.xml file I edited the values of:
<shovel fillLitersPerSecond="3000" (was 1250 or something)

<capacity>1000</capacity> (was 100)

<overloadingCapacity>5000</overloadingCapacity> (dont remember what it was.)

Values are not final and may need some tuning depending on application.

**Comment by mikeloeven** [comment]
ill try editing the tool with your values and see if it will keep up

**Comment by gui7545** [comment]
The unloading speed is a calculated value.
It depends on the load of the trailer, the lenght of the silo and the unloaded rate.
As said before, the easiest way is to modify the unloading rate

**Comment by Satissis** [comment]
#1346
