### ISSUE TITLE
Course xml updates

### ISSUE THREAD

**Issue by malcom2073** [Courseplay/courseplay#1240]
Hello, I have a question.

If the XML file is modified outside of FS2015, does Courseplay pick up the changes when you load/merge the modified course into currently loaded course? What happens if a currently loaded course is modified, are the changes ignored until the course is reloaded?

Thanks!

**Comment by gui7545** [comment]
Hello
The file is load at the start of the game, during the loading.
it will be save when you save your game

**Comment by malcom2073** [comment]
Excellent, that answers my question, I'll edit it only when the game isn't running. Thanks!
