### ISSUE TITLE
Courseplay HUD "turn off"

### ISSUE THREAD

**Issue by GermanMilkaKuh** [Courseplay/courseplay#1241]
Hey Guys When i start my Map go to my Tractor and press Rightclick, click on Manage Courses: My HUD from the Game and Courseplay "turn off" anybody can Help me sry for my bad English ;)

My LOG: http://pastebin.com/zmrPjRbZ   Line 712 - 1114   -.-

**Comment by Vanquish081** [comment]
Use you the last version?

**Comment by GermanMilkaKuh** [comment]
Yes haha

**Comment by Raints** [comment]
Sry but you dont have latest dev version. line 320 ### Courseplay: initialized 38/38 files (v4.01.0000)

**Comment by GermanMilkaKuh** [comment]
And whats the newest version where can i findt it on modhoster ist only this version

**Comment by Raints** [comment]
http://courseplay.github.io/courseplay/en/installation/index.html  Read here

https://github.com/Courseplay/courseplay

**Comment by GermanMilkaKuh** [comment]
I done this and get the same version

**Comment by Raints** [comment]
Installing the developer version

Unpack the downloaded the zip file to a folder of your choosing. Inside, you will find a folder named courseplay-master. Archive the content of that folder to a new zip file named ZZZ_courseplay.zip. Then proceed installing it as described for the released version (see above).

**Comment by Raints** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3618060/10557792/77cdf9ca-74c2-11e5-879d-1f68c31189eb.png)

**Comment by Satissis** [comment]
#1346
