### ISSUE TITLE
Mowers issue

### ISSUE THREAD

**Issue by Sythos** [Courseplay/courseplay#1242]
Mowers work fine if the vehicle is a tractor, with a mower as tools (or integrated like krone M500) and a trailer. 
Courseplay fail to stop the vehicle once the mower have no trailers *BUT* have internal capacity, i've got this issue with:
- Krone BigL500 (last release V2.0 april 2015)
- CaseIH Mower L3200 (V1.0 july 2015)
- Amazone hopper or other small/garden tools (tried just to test)

Seem like the "stop" work getting capacity only from trailer and if no trailer attached CoursePlay assume is "just a mower", I suppose as standard HUD in FS15 can read che internal capacity somewhere the value is stored and can be detected the "100%"

**Comment by ThomasGaertner** [comment]
tested it and worked fine...
