### ISSUE TITLE
ide of obstacles avoiding 

### ISSUE THREAD

**Issue by SMDSY** [Courseplay/courseplay#1245]
i whould really love to see courseplay  manage whit obsticals like trees and fences and sutch..
i know this means loots of more work but it might not be to hard since course play allredy have the function of detecting the feilds ( shouldent it be kinda eazy to have it detect trees busshes and bildings aswell? )
then the hard bit might be how course play will handle the tractoor  and the equipment when facing this obstical ( maybe make a avoiding aura around eatch obstical of 1 meter)

an outher ide that just poped up in my mind when think about the feild detection tool..  could that work for roads aswell? dirt roads or gravle roads and tarmac roads .. just an ide...

**Comment by fudoido** [comment]
i asked about this feature before, creators mentioned that courseplay is set to do a backward drive when its found to be sliping in an obstacle after some time, but for some reason the game makes that detection take too long, what was suposed to be seconds, takes many minutes.
with larger obstacles like fences, walls and other big sizes, it seems that latest developer versions have that kind of detection and seems to avoid those obstacles, but smaller obstacles like trees, light posts and others, it isnt detecting so good, or not detecting at all.
would love to see the obstacle avoidance work with every colidable object.

**Comment by davidhunt135** [comment]
There is some code in there that detects bales and I think trees but it does take a wide berth when avoiding them so can cause crashes into other objects that are near by.

**Comment by ThomasGaertner** [comment]
we have it on our list , but close here to keep the issues area clean
