### ISSUE TITLE
Help with Combining 2 courses or ?

### ISSUE THREAD

**Issue by snupple** [Courseplay/courseplay#1246]
At the moment I am using this type of course to have a tractor work a combine:

![normal path](https://cloud.githubusercontent.com/assets/851790/10564195/ee0df2d2-75dc-11e5-8300-f9879b962c4d.png)

But I really would like to have 2 courses:

A) Firstly one that runs around the farm to the silo and back to the entrance of the farm.

B) Secondly the field combine working course that goes from the field to close to the  A) course and and somehow crosses over to that at X.

Cant for the life of me work out how to do with with combining, using crossovers etc:

![normal path plus](https://cloud.githubusercontent.com/assets/851790/10564196/ee1116c4-75dc-11e5-992a-1fb277e8d7de.png)

Anyone got any ideas?

**Comment by Raints** [comment]
Just try with 3 courses. Hope it helps.
![untitled](https://cloud.githubusercontent.com/assets/3618060/10564574/bd947f6a-75c1-11e5-95bf-3e0f769bf749.png)

**Comment by gui7545** [comment]
I think the blue on your scheme is the combine ?
So the combine must work in this mode : http://courseplay.github.io/courseplay/en/manual/index.html#driveMode7
And the pink course is the tractor course. So it need to work in this mode : http://courseplay.github.io/courseplay/en/manual/index.html#driveMode1

**Comment by MartinGrisotto** [comment]
Why don't you just use an overloader? What are you trying to gain?
