### ISSUE TITLE
new mode proposal

### ISSUE THREAD

**Issue by fudoido** [Courseplay/courseplay#1247]
any chance we can have a mode simmilar to the combine self unload, but for seeding and fertilizing tractors (or other functions) that when using hired workers it starts the course when seed/fertilizing gets empty (oposite to combine that do that when full) and goes to last position after refiling?
such mode would be very helpful to use along auto-tractor, wich i prefer to use more than fieldwork and i believe others would like it also.

**Comment by davidhunt135** [comment]
The fertiliser mode already does this

**Comment by fudoido** [comment]
it works with regular worker instead of using the fieldwork? would be nice if seeders do it also, and manure spreaders.

**Comment by davidhunt135** [comment]
Ah, sorry. No, I didn't realise you meant specifically with the hired worker. Interacting with other mods and game AI code become a lot more difficult than using fieldwork in courseplay so the amount of work it would take probably far outweighs the benefit that you would get from it. Besides, There is nothing wrong with the current version that uses fieldwork on the field and then goes to fill up.

**Comment by fudoido** [comment]
it would be just one less saved course, thats all. by using auto-tractor instead, and just create a mode to make them fill up seeder/fertilizer when worker gets empty, would clear more fieldwork courses, since creating 1 per field sometimes isnt enough due diferent implement sizes.
fieldwork could, that way, only be created to line-up straw/grass, create and pickup bales, wich could use the same fieldwork course since it would be in the same width between lanes..... while seeding and ferting most of the times have diferent widths of implements.
since code was made for the combine self unload already, i believe it could be done easyly by just changin the "full" value to an "empty" value of sorts..... i dont know much of coding, or else i would try to do it myself.

**Comment by davidhunt135** [comment]
Ah, I just generate the field course every time since they are always different widths then use the copy from feature when I want several following the same course

**Comment by fudoido** [comment]
also, i would prefer that king of mode than the combine self unload, since we already have the combi mode (wich makes trailer go to combine to unload it) and the overloader mode) wich is almost the same, but with the auger trailer), dont see much of a point to have a mode to make combine waste time out of the field to unload itself into a trailer, when trailers can go to it while it keeps harvesting.
