### ISSUE TITLE
Nachgewende ?

### ISSUE THREAD

**Issue by paeppchen** [Courseplay/courseplay#1248]
Hallo, ich hab keinen Fehler, sondern eigentlich eine Anregung. Im cp ist ein vorgehende das erste aussenrum ein paar bahnen fahren lässt und dann das feldinnere bearbeitet. Das ist ja gut fürs ernte einfahren, aber beim säen und so so ist es (zumindest hier in Schottland) üblich ein "Nachgehende" (ob das wirklich so heist weis ich nicht) einzusetzen. Ich fände es schön wenn ihr das in cp integrieren könntet (falls das überhaupt möglich ist).
Ansonsten vielen dank für diesen super mod
Rolf aka paeppchen

**Comment by JDTiger** [comment]
the feature you request is already in, just click on the icon which counts the circles and you will see the arrow changed direction, from circle-> Field to Circle<- Field and now courseplay will first work the lanes and then the Headland
