### ISSUE TITLE
combine multiple fields

### ISSUE THREAD

**Issue by dakar2008** [Courseplay/courseplay#1249]
Hi There

First let me thank you all for a great job you have done with Courseplay through the last couple of years and still are doing, great work guys.

Well my question is just about, would it ever be possible or is it allready possible to combine multiple fields to one course, let me give you an example:

Let's say you auto-generate a course for Field 1 and make a manual transfer course to get seed and fuel for your machinery, after the tractor has done seeding field 1 it drives on to field 2 and continue seeding that and drives off to refill seeder and refuel and so on, it would be awsome.

Another thing is, is it just me or does your tractor not drive off to refuel if it's low on fuel, it comes with a warning when it's time to refuel, but it's continue to seed the field instead of driving off and refuel, and i  have maid the refill course drive around the refuel station ?

Best Regards
Daniel Andersen
Denmark

**Comment by dough29** [comment]
Good idea.

I think that would be possible if we can type courses like "get fuel", " get seed" si we can save courses like :
- get seed from field 1
- get fuel from field 1
...

Nice idea !

**Comment by Satissis** [comment]
I'm afraid that's not possible, since that would require allot of rewriting to get multi field work planing to work.
Regarding the refilling, it will only refill when you are on the route to refill and not when it's need to

**Comment by fudoido** [comment]
like satissis said, it will refill only when driving by the station and warning is on, it will not cancel the current work to go refuel.
one thing that i usually do, if the route doesnt have any reversing manouver, is to attach a service trailer in the back of the loading trailer, and even if i dont pass through a station, theres allways the chance that machinery refills when crossing by the trailer, even if moving (of course on this case it wont refill much)
