### ISSUE TITLE
JCB Skidster weird turning 

### ISSUE THREAD

**Issue by Wojimus** [Courseplay/courseplay#1251]
Hi,

I just tried to setup a JCB Skidster for picking up Silage from the silo and selling it at the drop off point. It worked perfectly picking up the silage and reversing but when I start turning the JCB starts going over the top in its turning (The Skidster was basically skidding all over the place). I am on version 4.01.0000.

The course works perfectly fine on a normal tractor which is what I'm using right now until I figure out what's wrong

**Comment by ThomasGaertner** [comment]
#1346
