### ISSUE TITLE
key binding issues

### ISSUE THREAD

**Issue by g1899** [Courseplay/courseplay#1252]
how come the right Mouse button bind to open the hub and the Extend and contract front loader arm,open and close front loader tool key==right y,right x ......
can anyone help me on this even though i don't have game log 
u can look this up in the options/controls ......
if there is a way to rebind the key's tell me please

**Comment by gui7545** [comment]
You can set up the opening control : CTRL + SUPPR for front lodder or other tools
http://courseplay.github.io/courseplay/en/manual/index.html#hud_generalSettings

**Comment by g1899** [comment]
okay thanks
