### ISSUE TITLE
Mode3 gamefreeze

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#1253]
Hey CP DevTeam,
I have some lua errors in my log, when i use Courseplay in Overloader mode to deliverver the yield from 2-3 Combine on one field to a trailer.
the problem occurs after the tractor has emptyed on combine and waits starts to head to anoother to empty it.
the error is:
Error: Running LUA method 'update'.
C:\Users\Julian\Documents\My Games\FarmingSimulator2015\mod//zzz_courseplay/mode2.lua:306: attempt to compare number with nil

Hope you find an answer for this problem,
Greets JD_Tiger

**Comment by gui7545** [comment]
Hello,
Can you post your full log to gist ?
It is maybe a problem with other mod.
https://gist.github.com/

**Comment by JDTiger** [comment]
jep, was a mod...
just need to find out wich :D
Can be closed

**Comment by JDTiger** [comment]
Mod that screwed CP up was the Bergmann Overloader wagon
http://www.modhoster.de/mods/bergmann-gtw430
