### ISSUE TITLE
Not placing first 3 waypoints close enough together / Skipping to waypoint 3 when using 'first waypoint'

### ISSUE THREAD

**Issue by MDBenson** [Courseplay/courseplay#1254]
I'd like to start by saying this is a great mod and as I've got the hang of using it it's been invaluable. Keep up the good work :)

I have had several related issues with Courseplay which arise from the same 2 issues:

*The first 3 waypoints are too far apart in time and/or space, so critical parts of the course like turniung after filling from a silo or turning correctly from a field gate when exiting are not refined enough leading to crashing into scenery or the AI losin the waypoint track and tryint to make a turn (often badly)o rejoin it.

*Especially when in unload combine mode, using 'first waypoint' when I select 'Drive course' is skipping to waypoint 3, not starting at 1. This, coimbines with the issue above, leads to the machine driving off towards a point that often is blocked by scenery.

Now, I know you are likely to tell me I'm recording my courses poorly or something like that, but after using Courseplay a lot pn maps with tight conditions, I have identified the above issues something that's a problem repeatedly, many times over, not just one thing in one place. I'd appreciate at least an explanation why you have it set the way you do, if not some tweaks to fix it :)

**Comment by Karlshoj** [comment]
I think we all have the problem of the first points being too far apart from each other.
To overcome this issue I start the course with two crossing points even before I start driving.
At stand still I press start record and two times crossing point, and then start driving/recording.
Hope it will help you.
