### ISSUE TITLE
Sosnovka + Cow Silage to BGA Silage Bunker

### ISSUE THREAD

**Issue by paullaverick** [Courseplay/courseplay#1260]
Hi.
Having a bit of trouble with Courseplay....
I have a loader at the cow silage bunker which is set to load trailors - works fine!
I have a loader at the bga which is set to sell the silage - works fine!
I have a route for my trailor, from cow to bga - the route is fine, but when the tractor/trailor passes through the BGA Tip trigger, it doesn't tip.
The bunker does have some silage in and will tip manually, but when running courseplay, it will not...
I am in grain mode.
I originally thought that when I recorded the route, the BGA was fermenting, and not giving the trigger, so I re-recorded it, but no difference. There is nothing specific in the XML file that states a trigger, so it must detect it..
Any ideas please?
Thanks

**Comment by ThomasGaertner** [comment]
#1346
