### ISSUE TITLE
Sosnovka - Unloading at the SugarBeat SILO

### ISSUE THREAD

**Issue by Beebtrek** [Courseplay/courseplay#1261]
I have tried this problem with both main release and MASTER release of courseplay. Also used 5 diffent tractors and 4 different trailers. I set a course up to load from Harvesting Grimme (Sugarbeat) the drive to farm and the reverse into the bay the TIP Trigger is tripped the UNLOAD symbol appears, but the tractor just carries on to complete the course without unloading. Tried the same route tatics with the other two game maps i.e Europe and USA all fine. So it is to do with latest update and the GOLD Edition. Can you help?
Regards Stephen.

**Comment by gui7545** [comment]
Hey,
Have a look to the reverse driving.
https://courseplay.github.io/courseplay/en/manual/index.html#reverseDriving
You have to record the course without trailer

**Comment by Beebtrek** [comment]
Without wishing to get silly. I do no how to set up reverse driving as I said in the 1st message it WORKS FINE IN THE OTHER MAPS.
QUOTE:
Tried the same route tatics with the other two game maps i.e Europe and USA all fine.
UNQUOTE.

**Comment by Beebtrek** [comment]
Futher investagation shows no errors in the logs. Also the mods are all taken out except courseplay 4.01 or current Master versions. Now if you set a course to dump Sugarbeat into the silo THROUGH the chamber it works and unloads. But as the heap Grows it becomes not practical. So use the REVERSING method is preferable. But as stated in the 1st message that does not function. As also stated the TIP trigger does activate and the TIPPING Symbol does appear. But trailer does not tip. I hop this makes it clearer. Regards Stephen.

**Comment by gui7545** [comment]
So, it seems that it is not a issue with courseplay but more with the map.
Maybe the modder used an incompatible silo in this map.

**Comment by Beebtrek** [comment]
yes i came to same conclusion. Except the modder is GIANTS! So is there a new SILO rule that the Courseplay DEVS are not aware of ?
Regards Stephen.

**Comment by AlphaXray** [comment]
Have the same issue on sosnovka map, unloadning beet with cp does not work.

**Comment by arkydave** [comment]
I have the same issue trying to sell straw at the sell point at main farm on sosnovka. The other sell point, near the village grain elevator, works fine with CP. Was using only in-game vehicles.

**Comment by ThomasGaertner** [comment]
please try v .111 and report back

**Comment by arkydave** [comment]
Problem with straw sell trigger is fixed. Thank you.

**Comment by Beebtrek** [comment]
yes it now is OK with latest version. Thanks very much. Sugarbeat that is it unloads as it should now.
Regards Lankspeed.

**Comment by floodo1** [comment]
You already know this, but this does indeed fix sugarbeet unloading on Sosnovka with all the tippers that i've tried. I can also confirm that it works well because i saved a few different routes prior to finding the patch/fixed version of courseplay from github. I tested those routes with various tippers using the patch and they all work correctly now!
