### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by Mopar** [Courseplay/courseplay#1262]
Last committed change to the github was back on July 18th. Devs stated that they were going to take a break on the project and put the project on 'break' status.

Now, I know that people suffer from burn-out and need to take a step away from things, but being the last change made was 6 months ago, and no recent news from any of the developers, has this mod been abandoned?

Sorry if this is not actually an issue, but more of a plea to see if they are actually coming back or has it been abandoned?

**Comment by JanZacher** [comment]
yes that is a good question whether there is something else

**Comment by xno** [comment]
This is GitHub.
You can fork repository and try to develope your self.

**Comment by ThomasGaertner** [comment]
#1346
