### ISSUE TITLE
Issue with AGO's Fendt 700 Vario SCR

### ISSUE THREAD

**Issue by therealcrow999** [Courseplay/courseplay#1264]
http://www.modhoster.com/mods/fendt-700-vario-scr-series-v-4-ls15-profi-plus-pack

There is a issue when using this tractor with the latest Dev of CP. I can set the tractor to a course I made but if I am in the tractor, the tractor won't follow the course. If I jump out of tractor or tab to another one, the tractor will follow course as normal. CP only acts strange only when I am in the tractor at the time. 

The tractor won't follow course, but when I am in the tractor I can take half control of the steering of the tractor, it will only turn left and not right. But like I said once I jump out of tractor, when it's set to unload a combine it will work fine. I am not only person having issue, my Youtube buddy tried it out and he removed all mods except the AGO's Fendt and CP and issue was still there. So it's either a CP fix or AGO's fix.

Thanks!

**Comment by SnoopBok** [comment]
Same problem here. I also tried to delete all mods except courseplay and the tractor: still the same problem. I think AGO won't fix it.

**Comment by Acrylic84** [comment]
It is sortable if you want to comment 2 lines of code out. The self.steeringEnabled confilts with courseplay so they are both turning it on and off. You do lose a bit of realism but it just means you can move the steering while the engine is off.
