### ISSUE TITLE
Error in fields.lua

### ISSUE THREAD

**Issue by SchorschiBW** [Courseplay/courseplay#1265]
Hello there,
I saw by chance that an error with the Fendt AGO has been fixed. Therefore, I have charged me the developer version and updated my Course Play.
Unfortunately I get now following errors:

Error: Running LUA method 'update'.
E:\Dokumente\My Games\FarmingSimulator2015\Modsammlung\profiles\Tunx//ZZZ_courseplay/fields.lua:615: bad argument #1 to 'ipairs' (table expected, got nil)

My log: [log.txt](https://github.com/Courseplay/courseplay/files/70565/log.txt)

EDIT: It's only when I start a savegame. When I start a new game, i don't have this issue

**Comment by Stolli1996** [comment]
I have the same problem on the Löshügelland Map. it appears when courseplay generate the fields and if the generation is finish then the error stops

**Comment by gui7545** [comment]
This erreur seems to be connected to the Seed Usage Calculator.
Courseplay can't get the different fruit on your field.
Can you confirm that ?

**Comment by SchorschiBW** [comment]
Possible. But why it works for a new game?

**Comment by Friendlyx** [comment]
i have that error, too but on the Holzhausen map

**Comment by LU-Klaas** [comment]
I have this problem on the default map now, too. Has anyone any idea how to fix it?

**Comment by sydneysina** [comment]
I have the same Problem of all my maps so that giants hang up After 5 minutes to half an hour. 

My pc is a few days old amd a10-7890k  (4.4 Ghz) with 8 gb of ram (2133 Mhz) an asus Mainboard a88x pro and a radeon r7 200 graficcard used for crossfire.   My hardware should work!

**Comment by Satissis** [comment]
Closing Since we moved over to FS17 converting and might not be an problem there.
#1346
