### ISSUE TITLE
Error in mode 6

### ISSUE THREAD

**Issue by Stolli1996** [Courseplay/courseplay#1266]
Hi

My log file has the error 
-- from =C:/Users/...../Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/mode6.lua:44
Warning (LUA): Argument to method 'isSamplePlaying' is nil

it's only happen when i sit in the combine when i'm out off the error stops
what can i do 

mfg

**Comment by gui7545** [comment]
Hello,
Can you post your full log here https://gist.github.com/ ?
Thanks

**Comment by Stolli1996** [comment]
i have fixed the problem there was something wrong in the xml of the harvester
