### ISSUE TITLE
Error: Running LUA

### ISSUE THREAD

**Issue by MisterMojoAT** [Courseplay/courseplay#1269]
Hi guys

I've got a problem on the Map Ackendorf you can look at the times?

My log
[log.txt](https://github.com/Courseplay/courseplay/files/73782/log.txt)

**Comment by Raints** [comment]
The only thing I can suggest to you is remove all mods from your mods folder, keep only courseplay mod. If you still have problems then post log again and we try to help you. Why I said that is most problems came from bad mods what has nothing to do with courseplay at all. Im playing with more then 300 mods in my mods folder and I dont have any problems with courseplay.

**Comment by ThomasGaertner** [comment]
#1346
