### ISSUE TITLE
game crashes when I adjust working width

### ISSUE THREAD

**Issue by Ausbeaver** [Courseplay/courseplay#1270]
I'm just using the standard hagenstedt map. I have a few machine mods but it seems to crash on all the machines not just mod machines, courselay works for everything else it only courses the game to crash when I adjust working width.

GIANTS Engine Runtime 5.0.1 (build date: Mar 28 2014)
Copyright (c) 2008-2012, GIANTS Software GmbH (www.giants-software.com), All Rights Reserved.
Copyright (c) 2003-2012, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: FarmingSimulator2013
Main System
  Cpu Name: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
  Cpu Core(s): 4 @ 2.6 GHZ
  OS: Windows NT 6.2 64-bit
Physics System
  Driver: NVIDIA PhysX Runtime
  Version: 2.8.4
  Thread(s): 2
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick disabled
  Force Feedback disabled
Sound System
  Driver: OpenAL
  Version: 1.1
  Device:  Generic Software
  Max. sources: 256
Render System
  Driver: OpenGL
  Card Vendor: Intel
  Renderer: Intel(R) HD Graphics 4400
  Version: 4.3.0 - Build 10.18.14.4170
    GL_NV_texture_compression_vtc not supported
    GL_NV_vertex_program2_option not supported
    GL_NV_vertex_program3 not supported
    max_texture_layers: 8
    GL_ATI_texture_float not supported
  OpenGL initialization successful
Hardware Profile
  Level: Low (auto)
  View Distance Coeff: 0.750000
  Shadow Quality: 0.000000
  Skip Mipmaps: 1
  LOD Distance Coeff: 0.750000
  Terrain LOD Distance Coeff: 0.750000
  Foliage View Distance Coeff: 1.000000
Farming Simulator 2013
  Version: 2.1.0.2 RC3
  Available Languages: en fr es it
  Language: en
Game vehicle types loaded
Mod directory: C:/Users/Lenovo/Documents/My Games/FarmingSimulator2013/mods
Load mod: A_Schlepper_Claas_Xerion_3800VC
Load mod: ClaasLexion780
Warning: Duplicate l10n entry 'frontwork' in mod 'ClaasLexion780'. Ignoring this defintion.
Warning: Duplicate l10n entry 'rearworkx' in mod 'ClaasLexion780'. Ignoring this defintion.
Load mod: C_Pflug_Kverneland_Packomat_Pack
Load mod: Fendt_936
Load mod: kenworth
Load mod: RWT_TRI350BT
Load mod: Trufab25Tcase
Load mod: Trufab25TNHB
Load mod: ZZZ_courseplay
specialization beleuchtung v3 by Sven777b
  Register vehicle type: A_Schlepper_Claas_Xerion_3800VC.xerion3800v3
  Register vehicle type: A_Schlepper_Claas_Xerion_3800VC.ClaasXerion3800Silageschild
  Register vehicle type: A_Schlepper_Claas_Xerion_3800VC.ClaasXerion3800Gewicht
  Register vehicle type: ClaasLexion780.claasLexion780TT
  Register vehicle type: ClaasLexion780.claasVario1200
  Register vehicle type: ClaasLexion780.claasConspeed
  Register vehicle type: ClaasLexion780.TamLeguan
  Register vehicle type: C_Pflug_Kverneland_Packomat_Pack.RWPackomat
  Register vehicle type: C_Pflug_Kverneland_Packomat_Pack.PWPackomat
specialization Real internal sound by Clod loaded
  Register vehicle type: Fendt_936.Fendt936Vario
  Register vehicle type: kenworth.T908
  Register vehicle type: RWT_TRI350BT.RWT
  Register vehicle type: Trufab25Tcase.trufab25T
  Register vehicle type: Trufab25TNHB.trufab25T
### Initialized 27 Courseplay files (v3.41.0000)
Loading shader WAD 'C:/Users/Lenovo/Documents/My Games/FarmingSimulator2013/shader_cache/shader_1_1_256_256_OGL_UK_8.wad' ... 120 hashes, 169 shaders, 183734 bytes compressed
data/sky/sky_day_night.i3d (0.00mb in 20.07 ms)
data/sky/rain.i3d (0.00mb in 2.78 ms)
data/sky/hail.i3d (0.00mb in 1.41 ms)
data/maps/map01.i3d (3.36mb in 4450.75 ms)
dataS2/character/pedestrians/executive03.i3d (0.27mb in 38.90 ms)
dataS2/character/pedestrians/casual08.i3d (0.53mb in 66.18 ms)
dataS2/character/pedestrians/casual02.i3d (0.31mb in 46.56 ms)
dataS2/character/pedestrians/casual15.i3d (0.40mb in 56.39 ms)
dataS2/character/pedestrians/casual03.i3d (0.33mb in 46.24 ms)
dataS2/character/pedestrians/casual07.i3d (0.32mb in 43.30 ms)
data/vehicles/steerable/same/sameArgon3-75.i3d (0.02mb in 101.95 ms)
data/vehicles/steerable/powerTakeoff.i3d (0.00mb in 2.97 ms)
data/vehicles/steerable/upperLinkMedium.i3d (0.04mb in 3.96 ms)
data/vehicles/steerable/upperLinkSmall.i3d (0.04mb in 1.75 ms)
C:/Program Files (x86)/Farming Simulator 2013/data/maps/models/objects/egg/egg.i3d (0.01mb in 1.36 ms)
C:/Users/Lenovo/Documents/My Games/FarmingSimulator2013/mods/ZZZ_courseplay/img/NurGerade/NurGerade.i3d (0.01mb in 3.68 ms)
C:/Users/Lenovo/Documents/My Games/FarmingSimulator2013/mods/ZZZ_courseplay/img/STOP/STOP.i3d (0.00mb in 3.69 ms)
C:/Users/Lenovo/Documents/My Games/FarmingSimulator2013/mods/ZZZ_courseplay/img/VorfahrtAnDieserKreuzung/VorfahrtAnDieserKreuzung.i3d (0.01mb in 4.11 ms)
C:/Users/Lenovo/Documents/My Games/FarmingSimulator2013/mods/ZZZ_courseplay/img/Parkplatz/Parkplatz.i3d (0.01mb in 2.85 ms)
data/vehicles/steerable/kramer/kramerKL200.i3d (0.01mb in 44.50 ms)
data/vehicles/steerable/buehrer/buehrer6135A.i3d (0.02mb in 47.68 ms)
data/vehicles/steerable/fahr/fahrM66.i3d (0.01mb in 40.38 ms)
data/vehicles/tools/poettinger/poettingerServo35.i3d (0.00mb in 13.74 ms)
data/vehicles/tools/lemken/lemkenKristall9.i3d (0.75mb in 33.13 ms)
data/vehicles/tools/amazone/amazoneD1.i3d (0.00mb in 15.63 ms)
data/vehicles/trailers/krone/kroneEmsland.i3d (1.11mb in 85.45 ms)
data/vehicles/steerable/fahr/fahrM66Cutter.i3d (0.00mb in 15.12 ms)
data/vehicles/tools/extraWeight01.i3d (0.07mb in 4.18 ms)
data/vehicles/steerable/lizard/golfCart.i3d (0.01mb in 7.68 ms)
data/character/farmer/farmer_player.i3d (1.75mb in 38.07 ms)
data/vehicles/trucks/milktruck.i3d (1.19mb in 119.14 ms)
data/vehicles/cars/car7.i3d (0.47mb in 29.21 ms)
data/vehicles/cars/car4.i3d (0.33mb in 18.76 ms)
data/vehicles/cars/car2.i3d (0.42mb in 24.15 ms)
data/vehicles/cars/car1.i3d (0.43mb in 27.51 ms)
data/vehicles/cars/car6.i3d (0.38mb in 26.16 ms)
data/vehicles/cars/car5.i3d (0.37mb in 26.20 ms)
data/vehicles/cars/car3.i3d (0.39mb in 31.24 ms)

**Comment by ThomasGaertner** [comment]
#1346
