### ISSUE TITLE
Suggestion: more direction

### ISSUE THREAD

**Issue by Piallator78** [Courseplay/courseplay#1271]
Hello, if it's possible to add more direction point to start and move with 45° rotation.
Now we have Nort-West, North-East, South-East and South-West start point with North, South, West and East direction.
For map with irregular field and/or rotate field we need to start at North, South, East and West point and move to Nort-West, North-East, South-East, South-West direction.
How about this?
Thx

**Comment by Stolli1996** [comment]
yes this idea woulld be great

**Comment by Satissis** [comment]
With the current system we have, this is not possible.
Thou before we went on an break for unknown time, we was working on a totally new system which is allot better than the current one and can be in any degree.
This will however not be available until we actually get back working on CP again and frankly, I don't think this will be in FS15 unless some one of us really got the drive back for modding CP again.

**Comment by ThomasGaertner** [comment]
#1346
