### ISSUE TITLE
Shovel won't empty BGA

### ISSUE THREAD

**Issue by robert2116** [Courseplay/courseplay#1272]
I'm using a Liebherr TL-436-7, I've looked at so many tutorials. I've set the bucket angles. I've done the course correctly. The program runs fine , scoops up silage and transports it right over the bin perfectly, then nothing happens. It won't empty the bucket. I can manually do it, afterwards it raises the bucket back up and then drives backwards and continues just fine. I've reset the game over and over, I've redone the bucket angles and the course close to ten times, I can't get anything to work. Please help me this is exhausting.

**Comment by 23johnw** [comment]
Hi, this happened to me, mine was because I set the 3rd P (one near the bin) to close, drive up to the bin and the back away a bit before placing the p, you can always extend the arm in the telehandler for the unload position. That's what I did and it OK for me now

**Comment by LimEJET** [comment]
I've got this issue too, so I activated all debug channels and took some screenshots. [Here's my log file.](https://github.com/Courseplay/courseplay/files/85216/log.txt)

I think this is the same issue, but mine looks a bit different as the loader skips the last three waypoints before the unload waiting point and then just stops, even if it's not even close.

I tried it with two different paths, one optimized and one exactly following the spec.
![First path](https://cloud.githubusercontent.com/assets/4407285/12224641/cdda5ca6-b7f6-11e5-8a0a-25fef998c729.jpg)
The first path is a bit crumpled up, so I thought it was just the waypoints interacting in a weird way.

![Second path](https://cloud.githubusercontent.com/assets/4407285/12224651/fccb7450-b7f6-11e5-8d71-8fe5cbf8d21b.jpg)
This second path disproved that though, it fails to move completely.

**Comment by feinetwo** [comment]
So, I'm new to courseplay. Just got it downloaded it yesterday and I too am having the same issue where it stops about three way points short of getting to the unloading point[P]. I guess I'm just confused as to how you fixed it. I always thought it was cause I wasn't in a straight enough line. Please help!

**Comment by ThomasGaertner** [comment]
#1346
