### ISSUE TITLE
Ridge maker write errors

### ISSUE THREAD

**Issue by Stolli1996** [Courseplay/courseplay#1273]
Hi
I have a problem with the ridge maker on mod seetmaschines. because they havent ridge makers a so coursplay writes error i dont have the error right now because im not on seeding at the moment. but maybye someone have the same problem and know how it is to fix

mfg

**Comment by Raints** [comment]
Just turn ridge marker from auto to manual and then check for error.

**Comment by Stolli1996** [comment]
then the error appears only when the tank is empty. so it is not fixed its only aqt a later point

**Comment by Raints** [comment]
Ok, did you try with ingame seeders? If it works then you probably have badly modded seeder. Courseplay works just fine with ingame stuff.

**Comment by Stolli1996** [comment]
yes  the orginal seeeders work fine but i will take mod seeders like a amazone condor.

**Comment by ThomasGaertner** [comment]
#1346
