### ISSUE TITLE
How to change language in courseplay?

### ISSUE THREAD

**Issue by BrazilianArmy** [Courseplay/courseplay#1279]
How can I change the language in courseplay ? I searched but did not find anything here , what to do to change ?

by the way, I have changed there by modesc.xml and did not change in the game...

Sorry my bad english.

**Comment by Satissis** [comment]
The language is changed when you change the language for the game it self, so if you play the game in German, it will be in German and so forth.
Not all languages is translated yet, so if you are using one of the languages that is not translated, you will get the default English language.

**Comment by ThomasGaertner** [comment]
#1346
