### ISSUE TITLE
courseplayBackupSavegame

### ISSUE THREAD

**Issue by Viper525** [Courseplay/courseplay#1280]
I have the issue, that courseplay does not move the courseplay.xml back into the backup folder on my notebook. I'm pretty sure, that it does at my pcs, but cannot check atm.
I'm getting this lines attached to my logfile ehwn saving the game:

Error: Running LUA method 'update'.
D:/Documents/My Games/FarmingSimulator2015/mods//BergUndTal/Map/scripts/WeightStation.lua:655: bad argument #1 to 'getn' (table expected, got nil)

LS15 is at 1.4.2
Courseplay is at: 4.01.0111

**Comment by Satissis** [comment]
looks like an problem with the map it self. At least that's what the error is referring to and not CP.

**Comment by ThomasGaertner** [comment]
#1346
