### ISSUE TITLE
Mod installation issues

### ISSUE THREAD

**Issue by TextualMetal** [Courseplay/courseplay#1282]
i put the ZZZ_courseplay.zip file into the mods folder but when i go into the game it says it is not installed and i am unable to use the mod. if anyone knows what i am doing wrong i would greatly appreciate your help. thank you

**Comment by gui7545** [comment]
Hello,
Can you past your log file here and copy the url ?
https://gist.github.com/

**Comment by ThomasGaertner** [comment]
#1346
