### ISSUE TITLE
Weight between tractor and trailer causes problems in Combi mode

### ISSUE THREAD

**Issue by gec100** [Courseplay/courseplay#1285]
Not sure if this is a bug or not.
Im using Agrostar 6.61, Agroliner HKD 302 and 1000kg weight in between for stability. Without it HKD tends to rise tractors rear end in corners and braking.
Using this combination in Combi mode makes tractor acting funky around Combine. After Combine finishes emptying, tractor turns directly to it causing both to stop. If I move tractor and hit Drive again tractor goes back to the field parallel to the crops as it should except it stops with the trailer still in the crops. So Combine can not pass.
If i remove the weight in between, everything works fine.

btw.: great mod!

CP v.: 4.01
Steam FS15 game 
GIST: https://gist.github.com/gec100/b4addc5e3041b383d746

**Comment by ThomasGaertner** [comment]
#1346
