### ISSUE TITLE
lua error in the feilds file line 615

### ISSUE THREAD

**Issue by shivachirr** [Courseplay/courseplay#1286]
i thought you should see this i get a lua error in my logs when ever i try farming a feild with both a auto combine and auto tractor for the combine. and it pops up 3 times when it happends

' Error: Running LUA method 'update'.
C:/Users/mathewsdesk/Documents/my games/FarmingSimulator2015/mods//ZZZ_courseplay/fields.lua:615: bad argument #1 to 'ipairs' (table expected, got nil)
Error: Running LUA method 'update'.
C:/Users/mathewsdesk/Documents/my games/FarmingSimulator2015/mods//ZZZ_courseplay/fields.lua:615: bad argument #1 to 'ipairs' (table expected, got nil)
Error: Running LUA method 'update'.
C:/Users/mathewsdesk/Documents/my games/FarmingSimulator2015/mods//ZZZ_courseplay/fields.lua:615: bad argument #1 to 'ipairs' (table expected, got nil) '

**Comment by ThomasGaertner** [comment]
#1265
