### ISSUE TITLE
Turn Circle bug.

### ISSUE THREAD

**Issue by luczimm** [Courseplay/courseplay#1287]
When i use the tipper (Lizzard Graintrailer 4500l from the Giant mod: Farming Classics Expansion)  in Combi mode the turning circle number goes out of control.
With the standard tippers i cant see to get the same problem.
Here are 2 photos of the same scenario but 2 different outcomes.
1. All normal: 
![2016-02-14_00003](https://cloud.githubusercontent.com/assets/17233573/13033901/c5f05d88-d326-11e5-831e-68782be614bc.jpg)
2. Bug: 
![2016-02-14_00004](https://cloud.githubusercontent.com/assets/17233573/13033903/d6b12030-d326-11e5-9bdc-9fabe0eeaf60.jpg)

Coursplay Version: 4.01
Steam Game.
Log:
GIANTS Engine Runtime 6.0.2 64bit (Build Date: Jan 14 2016)
Copyright (c) 2008-2015, GIANTS Software GmbH (giants-software.com), All Rights Reserved.
Copyright (c) 2003-2015, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: FarmingSimulator2015
Main System
  CPU: Intel(R) Core(TM)2 Duo CPU     E8500  @ 3.16GHz
  Memory: 6142 MB
  OS: Windows NT 6.1 64-bit
Physics System
  Version: 5.9.4
  Thread(s): 1
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick enabled
  Force Feedback disabled
  Name: Xbox 360 Controller
    Number of Axes: 5
    Number of Buttons: 14
Sound System
  Driver: OpenAL
  Version: 1.1
  Device:  Generic Software
  Max. sources: 256
Render System
  Driver: OpenGL
  Card Vendor: ATI Technologies Inc.
  Renderer: AMD Radeon HD 5700 Series
  Version: 3.2.13399 Compatibility Profile Context 15.200.1062.1004
  Shader Version: 4.40
    GL_NV_texture_compression_vtc not supported
    max_texture_layers: 16
    OpenGL initialization successful
Hardware Profile
  Level: High (forced)
  View Distance Factor: 1.100000
  Shadow Quality: 1.000000
  Skip Mipmaps: 0
  LOD Distance Factor: 1.100000
  Terrain LOD Distance Factor: 1.500000
  Foliage View Distance Factor: 1.400000
  Volume Mesh Tessellation Factor: 0.850000
  Tyre Tracks Segments Factor: 2.000000
Farming Simulator 15 INT
  Version: 1.4.2.0 1.4.2RC1
  Available Languages: en de fr es it pl cz hu nl ru jp pt cs ct br tr ro kr
  Language: en
Game vehicle types loaded
Mod directory: C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods/
Load mod: FS15_newHollandLoaderPack
Load mod: FS15_rostselmashNiva
Load dlc: pdlc_goldPack
Load dlc: pdlc_itRunnerPack
Load dlc: pdlc_jcbPack
Load dlc: pdlc_newHollandPack
Load mod: aaa_IncreaseRPMWhileTipping
Load mod: AAA_UniversalProcessKit
Load mod: Andy
Error: Failed to open xml file 'C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//Andy/modDesc.xml'.
Error: Missing descVersion attribute in mod Andy
Load mod: Big_Farm_2015
Load mod: BjornholmRemixed_byMastice
Load mod: BunkerSilosHud
Load mod: BuyManyAnimals
Load mod: DeutzFahrCondiMaster8331
Error: Invalid mod name 'FarmingSimulator2015_DrawDistanceUpdater v1.1'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Load mod: FillTypeMassAdjustment
Load mod: firewood
Load mod: FS15_amazoneCenius3002
Load mod: FS15_amazonePantera
Load mod: FS15_amazoneUX5200
Load mod: FS15_BaleCounter
Load mod: FS15_ClassicsPack
Load mod: FS15_flieglTDK160
Load mod: FS15_flieglVFW10600
Load mod: FS15_kuhnMowerPack
Load mod: FS15_kuhnSitera3000
Load mod: FS15_kuhnVB2190
Load mod: FS15_marshallPack
Load mod: FS15_oldtimer_pack_FS11
Load mod: FS15_placeableSheds_MW_mailman
Load mod: FS15_vaederstadPack
Load mod: LemkenAchatZ8
Load mod: lemkenVarioPackFEP_300_90
Load mod: Milktruck
Load mod: MilkTruckTriggerP
Load mod: MischStation
Load mod: MurrayMachineryOctaQuadSystem
Load mod: OEB_realTerrain
Load mod: placeable_fertilizerTank_LS15
Load mod: placeable_gasTank_LS15
Load mod: placeable_seedPallets_LS15
Load mod: Saegewerk_placeable
Load mod: SelfmadeCultivator
Load mod: SESpallet
Load mod: StopMilkSale_1_2
Load mod: TSL_Schubkarren_LS15clean
Load mod: TSL_UniMixertrailer_LS15clean
Load mod: US_Trailer_10
Load mod: US_Trailer_9
Load mod: vehicleSort
Load mod: Verladerampe
Load mod: WaterMilkTrailer
Load mod: WaterMilkZunhammer
Load mod: WestbridgeHillsRemixed_V2_byMastice
Load mod: zzz_brakeLightExtension
Load mod: ZZZ_courseplay
Load mod: ZZZ_Date_and_Time
Load mod: ZZZ_driveControl
Load mod: ZZZ_FeedBales
Load mod: ZZZ_FuelAdjust
Load mod: ZZZ_growthManager
Load mod: ZZZ_NoModView
Load mod: zzz_setBackLinkageUp
Load mod: ZZZ_silenceAISounds
Load mod: zzz_WoodHarversterSaveCuttingLength
Load mod: Z_enginebrakingeffect
Load mod: Z_Sonstiges_Abschleppkette
  Register vehicle type: pdlc_goldPack.tatra
  Register vehicle type: pdlc_goldPack.sowingMachine_animated_randomMove
  Register vehicle type: pdlc_itRunnerPack.hookLiftTrailer
  Register vehicle type: pdlc_itRunnerPack.hookLiftContainer
  Register vehicle type: pdlc_itRunnerPack.hookLiftContainerTrailer
  Register vehicle type: pdlc_itRunnerPack.hookLiftContainerDynamicMountAttacher
  Register vehicle type: pdlc_itRunnerPack.hookLiftContainerManureBarrel
  Register vehicle type: pdlc_itRunnerPack.hookLiftContainerManureSpreader
  Register vehicle type: DeutzFahrCondiMaster8331.DeutzFahrCondimaster8331
Script loaded: firewood.lua (v1.1.0)
  Register vehicle type: FS15_amazonePantera.amzonePantera
  Register vehicle type: FS15_ClassicsPack.GueldnerG40FL
  Register vehicle type: FS15_ClassicsPack.tractor_animatedSteering
  Register vehicle type: FS15_ClassicsPack.selfPropelledForageWagon
  Register vehicle type: FS15_ClassicsPack.ManureSpreaderPlaneMover
  Register vehicle type: FS15_ClassicsPack.DLCBaleloader
  Register vehicle type: FS15_ClassicsPack.FahrAPNBaler
  Register vehicle type: FS15_ClassicsPack.attachableCombine_fix
  Register vehicle type: FS15_marshallPack.rotorManureSpreader
  Register vehicle type: FS15_marshallPack.manureSpreaderPlaneMover
  Register vehicle type: LemkenAchatZ8.LemkenAchatZ8
  Register vehicle type: lemkenVarioPackFEP_300_90.LemkenVarioPackFEP_300_90
  Register vehicle type: Milktruck.Milktruck1
  Register vehicle type: MurrayMachineryOctaQuadSystem.OctaQuad_back
  Register vehicle type: MurrayMachineryOctaQuadSystem.OctaQuad_front
  Register vehicle type: SelfmadeCultivator.SelfmadeCultivator
  Register vehicle type: SESpallet.palletSES
  Register vehicle type: TSL_Schubkarren_LS15clean.schub
  Register vehicle type: TSL_UniMixertrailer_LS15clean.flat
  Register vehicle type: US_Trailer_10.Milk Trailer
  Register vehicle type: US_Trailer_9.Milk Trailer
VehicleSort loaded
  Register vehicle type: WaterMilkTrailer.MilkTrailer
  Register vehicle type: WaterMilkZunhammer.MilkTrailer
Script WaterMod v3.1.5 by Marhu loaded! Support on http://marhu.net
### Courseplay: installed into 27 vehicles
loading Date/Time Mod by adcrafter27
--- installing driveControl by upsidedown into Drivable and Steerable...
--- loading BaleFeed-Mod V2.0 (by upsidedown) ---
  Register vehicle type: Z_Sonstiges_Abschleppkette.abschleppstange
dataS/cameraPath01.i3d (0.19 ms)
dataS/cameraPath02.i3d (0.17 ms)
dataS/cameraPath03.i3d (0.11 ms)
data/sky/sky_day_night.i3d (281.78 ms)
data/sky/rain.i3d (65.77 ms)
data/sky/hail.i3d (42.35 ms)
data/sky/dust.i3d (25.00 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//BjornholmRemixed_byMastice/map/map01.i3d (12095.57 ms)

---------------Info from the IncreaseRPMWhileTipping_Register script start--------------------

	---!!! ATTENTION !!!--- Installing now the 'IncreaseRPMWhileTipping' Script in Version 1.9 by Ifko[nator].
	Installing the Script from Mod: 'aaa_IncreaseRPMWhileTipping' to ANY vehicle witch is 'drivable' or 'attachable', this should happen only once!

---------------Info from the IncreaseRPMWhileTipping_Register script end----------------------

## BunkerSilosHud v2.1 by Jakob Tischler loaded
FillType Mass Adjustment Mod by modelleicher loaded
Fillable mass of Filltype barley_windrow changed to 4e-005 tons per Liter (according to real mass table)
Fillable mass of Filltype woodChips changed to 0.00036 tons per Liter (according to real mass table)
Fillable mass of Filltype rape changed to 0.00072 tons per Liter (according to real mass table)
Fillable mass of Filltype forage changed to 0.00032 tons per Liter (according to real mass table)
Fillable mass of Filltype milk changed to 0.00103 tons per Liter (according to real mass table)
Fillable mass of Filltype wheat_windrow changed to 4e-005 tons per Liter (according to real mass table)
Fillable mass of Filltype maize changed to 0.0008 tons per Liter (according to real mass table)
Fillable mass of Filltype grass changed to 0.00035 tons per Liter (according to real mass table)
Fillable mass of Filltype fuel changed to 0.00084 tons per Liter (according to real mass table)
Fillable mass of Filltype water changed to 0.001 tons per Liter (according to real mass table)
Fillable mass of Filltype liquidManure changed to 0.00098 tons per Liter (according to real mass table)
Fillable mass of Filltype potato changed to 0.00073 tons per Liter (according to real mass table)
Fillable mass of Filltype barley changed to 0.00063 tons per Liter (according to real mass table)
Fillable mass of Filltype wheat changed to 0.00079 tons per Liter (according to real mass table)
Fillable mass of Filltype seeds changed to 0.00035 tons per Liter (according to real mass table)
Fillable mass of Filltype grass_windrow changed to 0.00035 tons per Liter (according to real mass table)
Fillable mass of Filltype manure changed to 0.00079 tons per Liter (according to real mass table)
Fillable mass of Filltype dryGrass_windrow changed to 7e-005 tons per Liter (according to real mass table)
Fillable mass of Filltype fertilizer changed to 0.0011 tons per Liter (according to real mass table)
Fillable mass of Filltype treeSaplings changed to 0.0002 tons per Liter (according to real mass table)
Fillable mass of Filltype egg changed to 0.0001 tons per Liter (according to real mass table)
Fillable mass of Filltype forage_mixing changed to 0.00031 tons per Liter (according to real mass table)
Fillable mass of Filltype silage changed to 0.0007 tons per Liter (according to real mass table)
Fillable mass of Filltype wool changed to 0.0002 tons per Liter (according to real mass table)
Fillable mass of Filltype dryGrass changed to 7e-005 tons per Liter (according to real mass table)
Fillable mass of Filltype chaff changed to 0.00046 tons per Liter (according to real mass table)
Fillable mass of Filltype sugarBeet changed to 0.00074 tons per Liter (according to real mass table)
FillTypeMassAdjustment all fillType mass values have been updated. Note: This Log entry should only exist once, if you have several of these please check to make sure you don't have several FillTypeMassAdjustment Versions in your Modfolder.
-- registering bale counter specialization
adding bale counter to FS15_ClassicsPack.FahrAPNBaler
adding bale counter to baler
realTerrain: Not inserting on sowingMachine_animated as it has the specialization (sowingMachine)
realTerrain: Not inserting on sowingMachine as it has the specialization (sowingMachine)
realTerrain: Not inserting on pdlc_goldPack.sowingMachine_animated_randomMove as it has the specialization (sowingMachine)
## Courseplay: setting up signs
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/normal.i3d (1.02 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/cross.i3d (0.85 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/wait.i3d (1.92 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/start.i3d (1.56 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/stop.i3d (0.99 ms)
## Courseplay: loading courses and folders from "courseplay.xml"
--- loading driveControl mod V3.91 (by upsidedown)---
--- loading growthManager mod V1.0 --- (by upsidedown+JakobT)
growthManager:: loading C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/savegame3/growthManager.xml
growthManager:: growth is shifted to midnight
Disabled withering for: wheat, barley, rape, maize, sugarBeet
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/krone/kroneOptimat.i3d (94.87 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/trailer/trailer_01.i3d (33.22 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/fahr/fahrMH650.i3d (36.17 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/gueldner/gueldnerG40FrontloaderFork.i3d (55.00 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/lemken/lemkenD27_55K.i3d (68.60 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/lemken/particleAnimation/lemkenD27_55K.i3d (33.53 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/baler/fahrAPN.i3d (26.73 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/baleloader/baleloader.i3d (87.51 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/trailer/woodenSlurryTanker.i3d (38.00 ms)
E:/Games/Steam/steamapps/common/Farming Simulator 15/pdlc/FS15_rostselmashNiva/rostselmash/rsmNiva.i3d (618.26 ms)
dataS2/character/player/player.i3d (948.87 ms)
loading C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015//driveControl_config.xml for driveControl-Mod configuration
driveControl module shuttle not started
driveControl module manMotorStart not started
driveControl module manMotorKeepTurnedOn started
driveControl module gasAndGearLimiter not started
driveControl module hourCounter started
driveControl module sensibleSteering started
driveControl module handBrake not started
driveControl module fourWDandDifferentials not started
driveControl module inDoorSound started
driveControl module dirtModule started
driveControl module camera started
driveControl module cruiseControl not started
driveControl module showNearestFillLevel started
driveControl module pipeCam not started
driveControl module implementControl started
driveControl module groundResponse started
driveControl module freeSteering started
driveControl module fruitDestruction not started
driveControl module softGas started
driveControl sensibleSteering deadZone set to 14%
driveControl inDoorSound set to 45%
driveControl dirtModule speed set to 100%
driveControl groundResponse forceFactor speed set to 100%
driveControl softGas maxGasOnModifier set to 30%
driveControl freeSteering analog input ENABLED
driveControl freeSteering analog deadzone set to 10%
driveControl global camera speed set to 100%
driveControl analog controller x-axis camera speed set to 100%
driveControl analog controller y-axis camera speed set to 100%
driveControl mouse x-axis camera speed set to 100%
driveControl mouse y-axis camera speed set to 100%
driveControl standard camera reset DISABLED
driveControl keep last Camera ENABLED
E:/Games/Steam/steamapps/common/Farming Simulator 15/pdlc/FS15_rostselmashNiva/rostselmash/rsmGks5.i3d (170.60 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/hassia/hassiaFS.i3d (28.41 ms)
data/vehicles/tools/suer/suerSB700.i3d (121.41 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/poettinger/poettinger300.i3d (36.95 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//WaterMilkTrailer/waterTrailer.i3d (80.56 ms)
data/vehicles/tools/suer/suerSB1000.i3d (62.11 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/bavarianPloughFactory/bpfCultivator.i3d (29.35 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/bavarianPloughFactory/particleAnimation/particleAnimation.i3d (2.41 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/fahr/fahrKH4S.i3d (33.86 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/kuhn/kuhnFA367.i3d (29.79 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//Z_Sonstiges_Abschleppkette/Abschleppkette.i3d (1.48 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/bucher/bucherTRL2600.i3d (124.42 ms)
Warning (physics): Add trigger callback failed, object trafficCollisionTrigger is not a physics trigger.
Warning (physics): Add trigger callback failed, object trafficCollisionTrigger is not a physics trigger.
Warning (physics): Add trigger callback failed, object trafficCollisionTrigger is not a physics trigger.
Warning (physics): Add trigger callback failed, object trafficCollisionTrigger is not a physics trigger.
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/trailer/oldWaterTrailer.i3d (43.14 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/gueldner/gueldnerG40Frontloader.i3d (99.37 ms)
data/vehicles/frontLoaders/stoll/stollToolBaleFork.i3d (313.62 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/deutz/deutzD80.i3d (100.62 ms)
INFO: The hydraulic sound is in: 'C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/deutz/deutzD80.xml' missing! The 'SetBackLinkageUp' Script will load the hydraulic sound now for this vehicle! Thanks to the Modder of this tractor for this Bug!!
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/buehrer/buehrerRP21.i3d (60.16 ms)
INFO: The hydraulic sound is in: 'C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/buehrer/buehrerRP21.xml' missing! The 'SetBackLinkageUp' Script will load the hydraulic sound now for this vehicle! Thanks to the Modder of this tractor for this Bug!!
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_oldtimer_pack_FS11/tools/lizard/plough01.i3d (7.56 ms)
data/vehicles/particleAnimations/kuhn/kuhnVariMaster153.i3d (172.56 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/gueldner/gueldnerG40FrontloaderShovel.i3d (0.77 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/schlueter/schlueter1500TVL.i3d (128.67 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/gueldner/gueldnerG40.i3d (9.27 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//FS15_ClassicsPack/baler/bales/baleStraw70.i3d (15.47 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//StopMilkSale_1_2/StopMilkSale.i3d (2.16 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//MilkTruckTriggerP/MTStartTrigger.i3d (2.95 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//Verladerampe/Verladerampe.i3d (51.38 ms)
data/placeables/greenhouses/greenhouse01.i3d (607.22 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//placeable_gasTank_LS15/gasTankPlaceable.i3d (9.37 ms)
C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/mods//MilkTruckTriggerP/MTFillTrigger.i3d (2.70 ms)
data/maps/models/objects/pallets/woolPallet.i3d (137.16 ms)
firewood mod in esecuzione... player non ancora disponibile
dataS/character/player/playerCCT.i3d (14.80 ms)
driveControl module manMotorKeepTurnedOn externally turned off for this vehicle
driveControl module toggleActive externally turned off for this vehicle
driveControl module manMotorKeepTurnedOn externally turned off for this vehicle
driveControl module toggleActive externally turned off for this vehicle
driveControl module manMotorKeepTurnedOn externally turned off for this vehicle
driveControl module toggleActive externally turned off for this vehicle
driveControl module manMotorKeepTurnedOn externally turned off for this vehicle
driveControl module toggleActive externally turned off for this vehicle
driveControl module manMotorKeepTurnedOn externally turned off for this vehicle
driveControl module toggleActive externally turned off for this vehicle
driveControl module manMotorKeepTurnedOn externally turned off for this vehicle
driveControl module toggleActive externally turned off for this vehicle
driveControl module manMotorKeepTurnedOn externally turned off for this vehicle
driveControl module toggleActive externally turned off for this vehicle
Error: Failed to open xml file 'C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/vehicleSort/savegame3/v_order.xml'.
VehicleSort: No Save-File found - using standard vehicle order!
VehicleSort initialized
growthManager:: stepSize: 124.62158203125
growthManager:: registering fruit wheat growthTime: 6h
growthManager:: registering fruit barley growthTime: 6h
growthManager:: registering fruit rape growthTime: 6h
growthManager:: registering fruit maize growthTime: 6h
growthManager:: registering fruit potato growthTime: 6h
growthManager:: registering fruit sugarBeet growthTime: 6h
growthManager:: registering fruit grass growthTime: 10h
realTerrain: Disabling driveControl module groundResponse.
growthManager:: Saving to C:/Users/HAL 9000/Documents/My Games/FarmingSimulator2015/savegame3/growthManager.xml

**Comment by Satissis** [comment]
When I get the time for it, I'll take a look, since I might have forgot to set an min value to it.
The only thing you can do is set the turning circle manually, but that will however take long time to do, since that's a very big number.

**Comment by luczimm** [comment]
I got the same issue fore some of the other equipment from the Classics Expansion mod.
Btw, this is the best mod!

**Comment by Satissis** [comment]
First off, now that I sees this, it's the 4.01 version and not the latest developing version, so that's the first thing to get and retest.
Beside that, I'm going to close this due to this post: #1346
