### ISSUE TITLE
Error message in log

### ISSUE THREAD

**Issue by Naterz98** [Courseplay/courseplay#1288]
This error message is filling up my log. Just wondering what I may be doing wrong.

C:\Users\Nathen\Desktop\PV Game//ZZZ_courseplay/fields.lua:615: bad argument #1 to 'ipairs' (table expected, got nil)
Error: Running LUA method 'update'.

It doesn't matter what map I use it in.

**Comment by gui7545** [comment]
Helo,
Can you post your full log here https://gist.github.com/ and post the link.
Thanks

**Comment by Naterz98** [comment]
Here is the link. Any help is greatly appreciated.

https://gist.github.com/Naterz98/eb8475a2dff5bc5f997e

**Comment by Naterz98** [comment]
Still getting the error. I don't get it when I start a new game. Only after resuming a saved game. Any ideas?

**Comment by SchorschiBW** [comment]
Same as this one: https://github.com/Courseplay/courseplay/issues/1265

**Comment by Naterz98** [comment]
SchorshiBW did they ever get back to you with a fix? I am wondering if the seed usage calculator can be turned off. I never use it anyone. I am trying to play a 4x map in single player. Courseplay would be a huge help if I could get all the errors cleared up.

**Comment by SchorschiBW** [comment]
no, there is no fix for this and i didn`t get any response.

**Comment by Kanuvani** [comment]
I have been able to eliminate the error, but unfortunately it requires a restart and NOT having courseplay scan the fields on startup. Hope it helps.

**Comment by Naterz98** [comment]
That actually helps a lot. I don't mind the restart. Was beginning to wonder if I would ever figure it out. Thanks for posting!

**Comment by Kanuvani** [comment]
There maybe another way without a restart, but i haven't tested it. It would consist of opening the courseplay.xml in your save folder and changing the courseplayFields automaticScan="true" to courseplayFields automaticScan="false".

**Comment by ThomasGaertner** [comment]
#1265
