### ISSUE TITLE
game won't load map with courseplay

### ISSUE THREAD

**Issue by Linrox** [Courseplay/courseplay#1289]
FS15 version:1.4.2
Courseplay version: 4.00.0007 downloaded from [fs-uk](http://fs-uk.com/mods/view/35661)
Log file [pastebin](http://pastebin.com/embed_js/Xgkhnezf)
With only Courseplay installed in the mods folder. i get this error on any map i try to open if courseplay is active. i have also tried saving the map first without CP and then reloading the save with CP active and same issue occurs. the end result after the error is the game freezes after this issue.

I have download several versions from all the main mod communities, same issue

also when i try the git hub version the mod does not show up at all in the add mods list. and yes i have renamed it to ZZZ_courseplay and also followed the installation instructions from [courseplay.git_hub](http://courseplay.github.io/courseplay/en/installation/index.html) several times in case i messed it up the first 5 times.

Linrox

**Comment by Linrox** [comment]
I found the cause of my issue. If the key bind for "courseplay:modifier" under options is blank, then courseplay can not load. I have reproduced this several times deliberately to make sure.

**Comment by ThomasGaertner** [comment]
#1346
