### ISSUE TITLE
Weird turning issues in Fieldwork mode using Rostselmash Acros 595 Plus

### ISSUE THREAD

**Issue by Raezzor** [Courseplay/courseplay#1292]
Hi all, first thanks for all the work on this mod. Really enjoying using it. But I've run into an issue using the harvester stated in topic. Only tried it with a wheat field using the Powerstream 700 head. Basically, CP is leaving a lot of unharvested wheat scattered all over the field due to taking turns very wide and overcorrecting alot. When I get a chance I'll make a video and post that as well as some pics but I wanted to get this up at first so others could chime in as well. Tested on the basic Westbridge map in field 16. First noticed it because I used to use a NH TC5.90 and it never did this but kept having issues with the unload arm hitting my tipper when first trying out combi mode so i swapped to using the Rostselmah. Tried using headland and not. Any other things you can suggest to help it turn more accurately I'm open. Here is a copy of my log btw.: http://pastebin.com/gi69GqV2

This is with V4.01.0000 btw

**Comment by Raezzor** [comment]
https://www.youtube.com/watch?v=RsmJnXZSBy4

Me doing field 16 in Westbridge in a New Holland TC5.90

https://www.youtube.com/watch?v=xEMVssg1zec

Me doing the same field in the Rosts Acros. Same settings, CP calculated width for the head.

**Comment by ThomasGaertner** [comment]
#1346
