### ISSUE TITLE
Niva harvester & Classics DLC Grain Trailer

### ISSUE THREAD

**Issue by SquareCloud506** [Courseplay/courseplay#1293]
If I use courseplay to run both the Niva harvester (bonus with Gold) and Grain trailer (Classic's DLC) with any tractor, the Giant's engine stops working. This bug is repeatable, and specifically happens when the trailer unloads the harvester. It's also specific to courseplay running BOTH the harvester and the tipper, if courseplay is only running one of them, the game doesn't crash. I discovered this on a modded map, but can duplicate it on Westbridge Hills, with a new save game, no saved courses, and nothing else running. I've also tried this with both v4.01.0000 and v4.01.0111 dev with the same results.

**Comment by BufordMapping** [comment]
Hello I know that this is a old post but this should be fixed now due to a conversion issue with the DLC both the Niva and Classics have had updates recently.. It works fine for me now as I did have the same issue for a while..

**Comment by ThomasGaertner** [comment]
#1346
