### ISSUE TITLE
Failure message in log game freeze in

### ISSUE THREAD

**Issue by Tonton1969** [Courseplay/courseplay#1299]
Hello, 

I get this failure message in the log and the game freeze in.

Error: Running LUA method 'update'.
C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/mode2.lua:517: attempt to index a nil value
Error: Running LUA method 'update'.
C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/mode2.lua:517: attempt to index a nil value
Error: Running LUA method 'update'.
C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/mode2.lua:517: attempt to index a nil value
Error: Running LUA method 'update'.
C:/Users/Privat/Documents/My Games/FarmingSimulator2015/mods//courseplay_FS15/mode2.lua:517: attempt to index a nil value

**Comment by mngrazy** [comment]
the zip filename must be called ZZZ_courseplay.zip

**Comment by Tonton1969** [comment]
Ok thanks
