### ISSUE TITLE
Mode 1 Route Fails

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1300]
I am playing a map that has the fill trigger right on top of the unload trigger..    My Mode 1 unload route from the field will work for the first few minutes, but will quickly fail.   The truck will roll right through the load point at the start of the course at the field, and when it gets to the unload trigger will unload what is in the trailer and at the same time start filling from the silo.

If it is set to a different filltype than what is available at the silo (or it is empty) it will show at the start of the course that the filltype is not available at the silo, or that the silo is empty..   if the truck stops at all at the start point, it will roll as soon as an over loader approaches, but it will also just roll through the start point without loading.

help

**Comment by ThomasGaertner** [comment]
#1346
