### ISSUE TITLE
Steering stops Working after 15 min & deleting all vehicles and devices

### ISSUE THREAD

**Issue by KekseLP** [Courseplay/courseplay#1301]
Hi there,

my first problem is, that every Vehicle stops after 15-20 min after starting. Load a course, let the vehicle drive, change vehicle and drive along. After 15-20 min the vehicle doesn't react anymore. No steering, no acceleration or braking. i can extend the attached device (like a seeder) but i even cannot leave the vehicle, change the vehicle or  go to a Menu. 

my second problem is, when i saved and load the savegame again than there is no vehicle or device (like seeder or trailer) on the map. I can't choose a vehicle or see them on the map or in the menu.

Hope u can help.

Grettings

Log: https://gist.github.com/KekseLP/6b1ec89884f63b69a753
Version: V4.01.0000
Map: Volksholm_V2x https://www.modhoster.de/mods/volksholm

**Comment by Raints** [comment]
First I would recomend to use dev version of courseplay. You are using Courseplay: initialized 38/38 files (v4.01.0000) Then remove all mods exept courseplay and try again. If no errors, then just faulty mod.

Latest version is v4.01.0116

**Comment by Commissar0617** [comment]
i had the same problem, until i reinstalled the mod.

**Comment by ThomasGaertner** [comment]
#1346
