### ISSUE TITLE
incompatability with Alö-Frontloader

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#1303]
Stefan Maurus has published his second openBeta of the Alö-Frontloader pack.
it is quite nice, especially, becaus it enables every tractor to use a frontloader, without modifying it.
http://stefanmaurus.de/mods.php?id=10

sadly, CP-shovelmode doesn't work with those implements.
following error is shown in the log when trying to record shovel positions:

`Error: Running LUA method 'mouseEvent'.`
`C:\Users\nitro\Documents\My Games\FarmingSimulator2015\mods2//Courseplay/mode9.lua:352: attempt to index a nil value`

**Comment by ThomasGaertner** [comment]
#1346
