### ISSUE TITLE
Fieldwork not working or user derp

### ISSUE THREAD

**Issue by grizzlyatoms** [Courseplay/courseplay#1305]
I am completely out of ideas at this point. I've spent almost 4 hours now trying to get unloading to work with no luck what so ever. Heres the deal...
I've got CP mowing a field with a windrow. Its all good and works great. I then take a new tractor and forage wagon and copy the same route as the mower. That works great as well. Now when the forager is full, the tractor stops and says cannot complete until unloaded ect ect.. So i then make a new course (fieldwork) at the entrance to the BGA, run the course thru and back out and stop. Simple course, no waits or crossings or stops ect.. CP should know that when the tractor hits a trigger it's supposed to unload correct? Anyway, this does not happen. The tractor stays at fullspeed and blast thru the bunkers and hits the end waypoint. Nothing i've done seems to make this damn tractor unload. I've tried different tractors, different wagons, different maps. I've deleted CP, downloaded a fresh copy of the released version since i can't find the dev version anywhere. I've deleted all my CP settings and started fresh and still never unloads.
At this point i figure i've either borked something or didn't do a setting correctly. My combines and loaders work fine running to silo and then i have another truck loading at silo to sell grain. I just can't get fieldwork unloading to work. Thanks in advance

**Comment by Raints** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3618060/13995587/6f8a32fa-f132-11e5-9beb-0b65fddc1cd2.png)

How to install http://courseplay.github.io/courseplay/en/installation/index.html

**Comment by LordKena** [comment]
Are you sure it should be Fieldwork and not Combine to unload

**Comment by gui7545** [comment]
I think that fieldwork sould work.
But you need to merge you 2 courses : the mower one + the unload courses.
Courseplay will reconise the second course as the unloading one and it going to the BGA automatically.
http://courseplay.github.io/courseplay/en/manual/index.html#driveMode6
