### ISSUE TITLE
Problems with the bgashovel script and courseplay

### ISSUE THREAD

**Issue by Stolli1996** [Courseplay/courseplay#1306]
Hi

I have the problem that the unloading course with the shovel doesn't work when the mod bga shovel by heady is in the game. I don't know if the fix must be in the courseplay mod or in the bgashovel mod.
Here is an other thread with the same topic and maybye it helps. 
http://planet-ls.de/board/index.php?page=Thread&postID=282221&highlight=bga+shovel#post282221

MFG
Stolli

**Comment by ThomasGaertner** [comment]
#1346
