### ISSUE TITLE
Combine, Tractor issue

### ISSUE THREAD

**Issue by LordKena** [Courseplay/courseplay#1308]
I have a Combine that is harvesting and a Tractor picking it up and empty it in a silo. My problem is that the tractor doesnt drive all the way up beside the Combine. Everything works with the other similiar courses but not this one. The settings is the same as the other ones. Ive tried to reset it and redone the course but nothing helps.
Any suggestions.

**Comment by BufordMapping** [comment]
When you say settings does that mean you adjusted the offset of the tractor? If not try that sometimes the tractor looks at where the combine auger is pointed not where the unload trigger is facing.

**Comment by ThomasGaertner** [comment]
#1346
