### ISSUE TITLE
won't recognize silo

### ISSUE THREAD

**Issue by freshrebel** [Courseplay/courseplay#1309]
so i start recording a route with type combi. i start driving towards the silo, i stop at the silo. after that i drive to just before my start waypoint and i stop the route. the problem is the pickup won't unload at the silo it just slows down and drives through.
can someone help me?

**Comment by Stolli1996** [comment]
the silos are the orginal or the silos from heady?

**Comment by freshrebel** [comment]
the original

**Comment by freshrebel** [comment]
anyone a solution?

**Comment by ThomasGaertner** [comment]
#1346
