### ISSUE TITLE
Problem in mode6 

### ISSUE THREAD

**Issue by Stolli1996** [Courseplay/courseplay#1310]
Hi 

When I start the combine it works but when i get out and after i get in courseplay writes errors:

-- from =C:/Users/Sören/Documents/MyGames/FarmingSimulator2015/mods//ZZZ_courseplay/mode6.lua:44
Warning (LUA): Argument to method 'isSamplePlaying' is nil

i have look in the script and its about the drive of the combine but where is the fail

	-- Wait until we have fully started up Threshing
	if vehicle.sampleThreshingStart and isSamplePlaying(vehicle.sampleThreshingStart.sample) then
		-- Only allow us to drive if we are moving backwards.
		if not vehicle.cp.isReverseBackToPoint then
			allowedToDrive = false;

**Comment by ThomasGaertner** [comment]
#1346
