### ISSUE TITLE
Aimless weaving, but not through speed...

### ISSUE THREAD

**Issue by lansalot** [Courseplay/courseplay#1311]
So... map is Hobbs Farm V5. I've noticed on quite a few fields that my tractors carting grain will suddenly lose all sense of direction, pick some random vector and weave along it, forever - until it runs off the map, if possible. To try and demonstrate this, I set these two Fendt up to manually assign to the Krone in field 6. They should be exiting to north-west of the field, but as you can see, when the trailer finishes and should be heading in that direction, he heads aimlessly for SW instead until (if left) he runs off the map. The speed they travel at when doing this suggests CP thinks they're in a turn?

I made a video to demonstrate all this - given the size of Hobbs Farm, perhaps the fact it's heading to a negative co-ordinate (-74,255 in this case) is confusing the maths somewhere?

On top of that, the second tractor, he followed the full tractor away (see "following tractor" - until I stopped the first guy manually, then he returned to the harvester).

Earlier, I had CP driving four trucks in field 12 all at the same time, and they tracked the combines beautifully (hey - I like challenging it... ;-))

Any ideas or debugging you need turned on to help with this? Am on latest version, .119.

Video: https://vimeo.com/161383634
More: https://vimeo.com/161387843

**Comment by Satissis** [comment]
Closing Since we moved over to FS17 converting. This should hopefully not be an issue in FS17
#1346
