### ISSUE TITLE
Is it possible to have too many temporary courses at one time? 

### ISSUE THREAD

**Issue by greenscag** [Courseplay/courseplay#1313]
My game has been running out of memory lately and I have been trying to track the problem down. I am playing on a 4X map, and it always seems to happen after I have started a good number of temporary field work courses on the large fields. The save file becomes corrupted but thankfully CoursePlay automatically backs itself up when a crash from running out of memory occurs.

**Comment by Stolli1996** [comment]
how much courses do you have? i play on a 4x map, too. usually i have the same problems

**Comment by greenscag** [comment]
Well I am running 4 harvesters  each on a different temporary route, with 8 trucks with trailers running on 4 different saved routs to unload them. all at once.  If I start trying to add much more than this, that is when I start getting the error of running out of memory, and corrupted saves. It is usually when I try to come in after a harvester has finished a field, and start generating more temporary routes for field work to get the field ready for planting again.

**Comment by JDTiger** [comment]
well, your PC has a defined amount of RAM, every CP-Course needs ram to be saved in temporary...
have you ever saved all routes running and took a look at the size of the Coureplay.xml in the savegame?

the size of that xml is waht coureplay demands for RAM space...

**Comment by greenscag** [comment]
I will have to try doing that. I have 12 gigs of ram, I cant imagine using all of it, but maybe I am. I hope my thread does not come across as critical of CoursePlay. I think it is the best and most essential mod for Farming Sim, and without it I would not play. I cant begin to tell you how much I appreciate the modders work on it.

**Comment by MoslessNeo** [comment]
The CP does not demand only memory, but processor to process what is saved.
I have an i7 2600k @ 4.6ghz, GTX680 and 8GB ddr3 1600mhz.
6 harvesters
8 tractors
3 trucks
Map 4x private.

**Comment by ThomasGaertner** [comment]
can we close here ?

**Comment by ThomasGaertner** [comment]
closed to keep issues clean
