### ISSUE TITLE
Overloading Issues with Some Mods

### ISSUE THREAD

**Issue by therealcrow999** [Courseplay/courseplay#1314]
I have some issues with a few overloading functions with CP and some mods. 

The ZDT GiGant when I set it up to do the overload into a truck trailer it gives me the message "wrong trailer for this mode." I have everything setup right, so I think CP doesn't recognize that overloader. 

Here is link to the mod: http://www.farming-simulator.com/mod.php?lang=en&mod_id=27769&title=fs2015

Now with these two, the Kinze 1050 Trac and these newer mods, Bergmann GTW, when I set them up and load the overload CP they run the course fine, but their pipes never come out. Sometimes they get stuck at the "P" position on the course because their pipes never come out and unload the grains into the trailer.

Here is link to those mods above:
Kinze
http://americaneaglesmodding.com/index.php?action=downloads;sa=view;down=1170

Bergmanns
https://www.modhoster.com/mods/bergmann-gtw430
https://www.modhoster.com/mods/bergmann-gtw-tracks--2

I am using the latest CP v4.01-.0119 and I tried v4.01-.0111 and still no go. I felt like some of those modes worked in the past.

I thought maybe it was a mod conflict so I removed all my mods but those overloaders, CP and the latest Drive Control and still issues.

**Comment by ThomasGaertner** [comment]
#1346
