### ISSUE TITLE
Courseplay making turns early

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1315]
![fsscreen_2016_04_14_19_12_50](https://cloud.githubusercontent.com/assets/10678220/14546678/2ab62888-0275-11e6-87f0-d497a71d85a8.png)

For some reason course play is now starting the turns before the end of the field. But has you can see from the picture the way points go all the way to the end. Some of these turns that are short will go the opposite direction of the turn.(Making a left even tho the lane is on the right) Which debug channel would you like. This log is from debug 17 different field same issue 
[log.txt](https://github.com/Courseplay/courseplay/files/220113/log.txt)

![fsscreen_2016_04_14_19_23_16](https://cloud.githubusercontent.com/assets/10678220/14546926/d6e79b68-0276-11e6-95a8-cfc794318f11.png)

While reproducing the bug. It turns on waypoint 21 and the proceeds through 22-24 very quickly. As if courseplay thinks the turn is suppose to be on waypoint 21 and not a latter waypoint. Thanks a bunch for your time reading this

**Comment by pops64** [comment]
Update. I do not think it is a problem with course generation. I encountered the same problem with a field course that was generated in version 114(Everything worked fine there just updated to 119 yesterday)

**Comment by pops64** [comment]
It seems this bug only shows  only on the first turn after the start button is pressed if the tractor is not moving when this happens or the drive course button is pressed to close to the the next turn(does not matter if tractor is moving or not in this case)

**Comment by aviator64** [comment]
I had the exact same issue. It only started happening with the update of March 17 2016. Reverting to the previous version corrected this issue for me.

**Comment by RealNeo80** [comment]
i also have this issue with 3-point-mounted machines. (does CP makes a difference here?) Normally with 3-point linking the tractor can lift up the machine and drive back and forward to go into the new direction. Now it drives curves and not all parts of the field will be prepared well.

**Comment by Mopar** [comment]
I also have the exact same issue with the latest dev version (0119).

**Comment by ThomasGaertner** [comment]
yea it's because of an unlucky fix of an holmerDLC issue and will be good again in the next version
and btw #1346
