### ISSUE TITLE
Courseplay Multiplayer?

### ISSUE THREAD

**Issue by Wojimus** [Courseplay/courseplay#1317]
Hi, I love courseplay it is an absolutely amazing mod, I was just wondering if multiplayer is going to be released any time soon? I play with friends mostly so I really miss the functionality it gives you.
Thanks for developing such a great mod.

**Comment by Stolli1996** [comment]
i miss it too

**Comment by Wifi87** [comment]
Yeah i would like Courseplay Multiplayer to

**Comment by ThomasGaertner** [comment]
#1346
