### ISSUE TITLE
Vehicles driving round in circles.

### ISSUE THREAD

**Issue by Symbob** [Courseplay/courseplay#1318]
I've recently started getting a problem where everything works fine for a while then for no reason vehicles running a courseplay course go bananas and just try to drive round in circles.  When this happens you can't tab out of vehicles or get out of the game without forcing it to close.  The log shows this repeatedly:

Warning (LUA): Argument to method 'worldToLocal' is nil
-- from =C:/Users/Ian/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/drive.lua:777
Error: Running LUA method 'update'.
C:/Users/Ian/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/drive.lua:785: bad argument #1 to 'abs' (number expected, got nil)

What does this mean and how can I resolve it?

Thanks

**Comment by ThomasGaertner** [comment]
#1346
