### ISSUE TITLE
No filling at MilkMaxV2 placeable V1.0 

### ISSUE THREAD

**Issue by FreelancerTrent** [Courseplay/courseplay#1319]
Hi @ all,

it isn't possible to fill a trailer at the MilkMaxV2 placeable V1.0 (http://marhu.net/phpBB3/viewtopic.php?f=140&t=4369)

After creating a course and starting, the trailer is waiting to be filled. It doesn't fill autmaticaly. When you press the "R"-Button, filling begins and when the trailer ist full, it drives like the normal way.

The milkmax based on the "FabrikScript".

mfg Trent

**Comment by ThomasGaertner** [comment]
#1346
