### ISSUE TITLE
Krone BigX 1100 BeastPack Mod

### ISSUE THREAD

**Issue by SbSh-DNA-ModDing** [Courseplay/courseplay#132]
so I could fix the error log, the CP works great so far. I mostly use only original equipment and vehicles with the Cours play, but now I wanted to chaff corn with the Krone Beast pack and had to find the Abfahrer only moves to the chopper, not to ÜLW .. no matter how I adjust lateral and vertical distances, from time to time is emptied by accident. Otherwise, there is always a traffic jam on the field or even crash.

so den log fehler konnte ich beheben, 
der CP funktioniert soweit super.
Ich verwende meistens nur originale Fahrzeuge und Geräte mit dem Coursplay, doch jetzt wollte ich Mais häckseln mit dem Krone Beastpack und mußte feststellen, der Abfahrer fährt nur zum Häcksler, nicht zum ÜLW.. egal wie ich seitliche und vertikale Abstände einstelle, ab und zu wird durch Zufall entleert. Ansonsten gibt es immer Stau auf dem Feld oder sogar Crash.

**Comment by gui7545** [comment]
What about now ?
Any update ?
http://www.modhoster.de/mods/krone-bigx-1100-beastpack--10
