### ISSUE TITLE
Graintrucks not operating right in grain transport

### ISSUE THREAD

**Issue by broncfan03** [Courseplay/courseplay#1320]
I'm using the Pete379 grain truck to carry grain from the field to the silo, being filled using grain carts (overloaders), but when the course is run, the truck doesn't stop to get loaded, it just keeps going in loops.  There's no problems with the course since it works fine with tractors pulling tippers, but the grain trucks are having problems.  The truck also doesn't recognize vehicles in the way; it just plows into them and keeps going.  Thanks for any help!

**Comment by ThomasGaertner** [comment]
#1346
