### ISSUE TITLE
Ropa Euro Maus

### ISSUE THREAD

**Issue by Ibizahansi** [Courseplay/courseplay#1321]
Hello Boys,
One question, 
What do you think is it possible that Coursplay also accept the Euro Maus like a normal combine?
I tryed the hole night to change the Euro in a combine but nothing works....

Sorry for my Bad english

**Comment by Marv63** [comment]
Hi
What have you tried ? 
I would simply ad in the mod desc under vehicleTypes:
<specialization name="fillable" />
<specialization name="overloading" />
<specialization name="combine" />
Should work don´t know what u have done LOL:DD 
A whole night :laughing: 
Hope I helped u and yes I´m late 
MFG Marv

**Comment by Ibizahansi** [comment]
Thx for your Mail
Now i stop playing LS 15
I Start in Oktober with LS 17

Am 06.08.2016 11:36 vorm. schrieb "Marv63" <notifications@github.com>:

**Comment by Marv63** [comment]
haha what ? np :DDD

**Comment by ThomasGaertner** [comment]
#1346
