### ISSUE TITLE
Farming Simulator 17

### ISSUE THREAD

**Issue by erksartori** [Courseplay/courseplay#1325]
Good Morning!!!
I wonder if you will continue this wonderful project in Farming Simulator 17?
For I too adimiro the work of you, and would like to know that.

My thanks.

**Comment by gammelgaard52** [comment]
I really hope that as well, since this mod is one of the reasons why I play FS15 :)

**Comment by SGFITZY** [comment]
I think That so many love this MOD and use it would be happy to pay for it as well maybe a go fund me page for them to help them be motivated to build a new one for FS17 or we could all donate $5.00 to the paypal link they have on their webpage

**Comment by ThomasGaertner** [comment]
#1346
