### ISSUE TITLE
Will not start with strg keypad 7 with newest version

### ISSUE THREAD

**Issue by D3ltorohd** [Courseplay/courseplay#1330]
Hi,

i have updatet to the newest version i can get, its from github. Now i can't no longer start or stop the CP Driver with strgL + keypad 7. Bevor i upgrade it works perfectly.

**Comment by ThomasGaertner** [comment]
works fine for me, did you check the input bindings ?

**Comment by D3ltorohd** [comment]
Yes, normaly it should the right button's on input bindings. Hm but now i have delet LS15 make room for LS 17 ;-)
