### ISSUE TITLE
Tipper blocks combi during harvest

### ISSUE THREAD

**Issue by abehnke** [Courseplay/courseplay#1331]
When harvesting potatoes on field 24+25 using the SE 260, sometimes the tractor+tipper parks too close to the fruit thus the combi (tractor+SE 260) is stopped.  I found that the prior workingWidth of the combi tractor was being used instead of doing a fresh calc using the current SE 260.  For example, say earlier I was using the generate field for a 6m wide implement.  So in mode2.lua the "if workWidth < offset then" results in something like 6 < 4.2 therefore the correct offset is not determined.  A work around is to always press the work width calc button on the combi before doing the harvest operation.

info:
CP: v4.01.0119  FS15: 1.4.2.0 1.4.2RC1  Bjorn default map, using default equip: Same Fortis 190, SE 260

**Comment by Satissis** [comment]
Closing Since we moved over to FS17 converting. This should hopefully not be an issue in FS17
#1346
