### ISSUE TITLE
4wd suggestions: permanence and differentials

### ISSUE THREAD

**Issue by elektronemulo** [Courseplay/courseplay#1334]
4wd mode resets to deactivated when I re-launch the game; suggestion: maintain 4wd save status between sessions. Alternative: allow users to set a course:play-wide setting of 4wd on by default

Differentials (with DriveControl): allow management of differentials (or automatically turn on front and rear differential lock with 4wd mode).

(Alternative to first suggestion) 4wd mode saved as part of course: perhaps add a waypoint type to activate & deactivate 4wd mode on the move (much like the reverser button).

(Keep up the awesome work, y'all; FS15 is much more tedious without CP and I doubt that I'd play FS15 as much without this mod).

**Comment by ThomasGaertner** [comment]
you can activate 4WD allways on in the settings. 
moved to the tracker to keep the issues area clean
