### ISSUE TITLE
Suggestions: Force Refuel & Automated driver stop

### ISSUE THREAD

**Issue by elektronemulo** [Courseplay/courseplay#1335]
Could y'all add a course type (or a function to the Transfer mode) to force a full refill and refuel? I want to create a course that will fill completely the fuel tank, seed tanks, etc. I will only run this course at the end of the day before I put my vehicles away so that they are full and ready to go for the next day.

Also, could you add a waypoint type (like the pause point) to tell the vehicle to "power down, apply the parking brake, and stop driving the courseplay course (quit the course)." This will be useful for refuel runs and farm-to-field transfers.

**Comment by fudoido** [comment]
if i recall, fs15 version would auto refuel if tank was below 20%, when passing nearby a fuel trigger. i think that keeps true in fs17 version. 
thats why on fs15 i would usually use a tipper with rear attachment and attach a fuel trailer in the back..... sort of constant refuelling while traveling, altho it wouldnt be enough for a big refueling :P

**Comment by fudoido** [comment]
nvm comment, just looked at date, it was ment for fs15 not fs17 lol ^^

**Comment by ThomasGaertner** [comment]
refueling is done, quit course is won't do ...
