### ISSUE TITLE
mchale 998 support

### ISSUE THREAD

**Issue by tsikows** [Courseplay/courseplay#1337]
Is the mchale 998 square bale wrapper no longer supported? issue #167 https://github.com/Courseplay/courseplay/issues/167 looks to have fixed it but it does not work in my current version (4.01.0000)

**Comment by Karlshoj** [comment]
Try n 4.01.0119

**Comment by tsikows** [comment]
how do i go about downloading that most recent patch?

**Comment by ThomasGaertner** [comment]
#1346
