### ISSUE TITLE
Courseplay stürzt nach wenigen Minuten ab

### ISSUE THREAD

**Issue by bamyentm** [Courseplay/courseplay#1341]
CP-Version: 4.01
 Spiel stürzt nach wenigen Minuten ab auch wenn kein Fahrzeuge benutzt werden, also auch wenn ,man rumsteht und nichts macht!
 Wie oben gesagt stürzt das Spiel immer ab ob im Fahrzeug oder nicht..
 Normal gespielt nach wenigen Minuten stürzt das Spiel ab. Ziel: Weiterspeieln ;D
 [log.txt](https://github.com/Courseplay/courseplay/files/411841/log.txt)

**Comment by Marv63** [comment]
Hi Beniamin
Bist du dir sicher das das die ganze log ist? Weil da müsste noch irgendwas kommen nach der nachricht das du den khn gekauft hast:
Aber insgesamt werfen deine Mods ziemlich viele errors...
Aber es ist wahrscheinlich die map die einen error zusammen mit der fields.lua aufwürft.
Ich kenn die map zwar nicht aber bei den bewertuingen auf modhoster werden keine ähnlichen vorfälle gemeldet... hast du vlt was verändert ? 
Ich denk des problem lässt sich aufjeden fall beheben ;D
MFG Marv

**Comment by bamyentm** [comment]
Hi Marv,
danke für deine Antwort!
Es ist die ganze log mehr kam nicht habe es auch getestet und sie gelöscht und als das Problem wiederkam sah die Log auch so aus da kam nicht mehr.
Die Errors da muss ich mal drum kümmer habe aus versehen minecraft mods rein kopiert :DDDDD.
Ja ich habe die Map geändert bloß ich hoffe nicht das es daran liegt D:.

**Comment by Marv63** [comment]
HI 
ok ja haha passiert des sind aber nicht die ursachen es ist des das du was an der map verändert hast ...
Ich kenn mich leider garnicht mit maps aus also was modden angeht die sind für mich unbegreiflich ich scheitere sogar an trigger vergrößern / gebäude hinzufügen klappt manchmal ...
^^

**Comment by ThomasGaertner** [comment]
#1346
