### ISSUE TITLE
Multiusesilo.oncreate

### ISSUE THREAD

**Issue by bdbssb** [Courseplay/courseplay#1342]
I'm playing on a map called pv rivers. I installed a silo that used a fill trigger multiusesilo.oncreate. In grain transport mode my tippers are driving up to the trigger slowing down then stopping after the trigger. The status shows filling but nothing happens. I have tried with in game truck/tipper and in game fruit (canola) and I have the same result.

**Comment by ThomasGaertner** [comment]
#1346
