### ISSUE TITLE
Joskin tippers

### ISSUE THREAD

**Issue by SnoopBok** [Courseplay/courseplay#1343]
I'm encountering issues when using the Joskin trailers from BlackSheep0521, like: https://www.modhoster.com/mods/joskin-trans-ktp-22-50-variablebody--2

When I'm using courseplay and when chopping maize it won't fill the trailer. It's working with courseplay when I'm driving really close to the harvester, but when taking a corner it's not working. The tractor stops and so does the forage harvester, until rebooting the game. 
Sometimes I'm getting  errors too: 
Error: Running LUA method 'mouseEvent'. 
D:/code/lsim2015/build/finalbin/dataS/scripts/gui/elements/GuiElement.lua(1026) : bad argument #1 to 'gsub' (string expected, got table) 

I'm also getting this warning on all of the trailers: 
Warning: 'D:[name]/My documents/My Games/FarmingSimulator2015/mods//Joskin_Trans8_fs2015/Joskin_Trans.xml' has invalid fillType 'seeds2'.

I asked the mod maker for help but he doesn't answer, I really like these trailers. Can somebody help me? Maybe there  is a way to adjust the trailer it something like that, let me know!

**Comment by ThomasGaertner** [comment]
#1346
