### ISSUE TITLE
Does not register CompostMaster Modpack 2016 V1.1 trigger

### ISSUE THREAD

**Issue by KRoover** [Courseplay/courseplay#1344]
Trying to set a course to fill the Compost Master with straw in Lakeside USA V4 Map but courseplay isn't registering the tip trigger in the ramp.
The tractor comes to the tip trigger in reverse mode, the unloading icon appears in the hud, but the tractor passes right through it without unloading.
For a temporary solution, I've set a waiting point in the tip trigger and I'm unloading manually, but it would be nice to have this mod incorporated in the tip trigger registration.

Thanks in advance.

**Comment by ThomasGaertner** [comment]
#1346
