### ISSUE TITLE
Don't save courses

### ISSUE THREAD

**Issue by OkPatinhos** [Courseplay/courseplay#1345]
Hello. I've been using courseplay and I try to save the courses it works, they actually save and work, but when I exit the game they disappear.. 

Can anyone help me? This mod save me a lot of time and I use it on my let's play YouTube series. Thank you a lot to who can help me!

**Comment by Satissis** [comment]
Are you using the developing version or the released version ? (The released version is the one you get from Modhoster or FS-UK)

**Comment by Satissis** [comment]
Save system have been redone ans mentioned in #1346 
This should fix this problem as well.
Note that this is still in our not released beta version for FS17, so you can first get it when we releases the beta.
Closing this to clean up the issue list.
