### ISSUE TITLE
Pack Balestacker and baler attacher

### ISSUE THREAD

**Issue by cpoole2005** [Courseplay/courseplay#1352]
Can you would you please make it so when the bale stacker is full the tractor stops and the stacker unloads. My thinking is it would be nice to be able to collect a few stacks of 8 bales rather than 100 individual bales.
[https://www.modhoster.com/mods/pack-balestacker-and-baler-attacher#description](url)

**Comment by ThomasGaertner** [comment]
It works as you said: field work mode without transport course. Then you can select when the trailer is full , it will stop or unload

**Comment by Satissis** [comment]
Closing Since we moved over to FS17 converting.
#1346

**Comment by lxfTTjek** [comment]
yes
