### ISSUE TITLE
Autostart CP LS17

### ISSUE THREAD

**Issue by Andii1980** [Courseplay/courseplay#1356]
Hallo,

ist es Möglich in der LS17 version auch die Funktion mit einzubauen das nach einem Game Start die Fahrer Automatisch die Arbeit wieder aufnehmen. Zumind. alle die vor dem Beenden (mit einem Spielstand Speichern) gearbeitet haben?

PS: ich freue mich schon auf CP für LS17

mit bestem Dank
Andii

**Comment by Simba76** [comment]
我期待CP 能支持 LS17

**Comment by Commissar0617** [comment]
there is no official courseplay for fs17

**Comment by ThomasGaertner** [comment]
OK we ve checked it and decided not to make it beacause of the unclear situations which can happen then... sorry
