### ISSUE TITLE
Multiplayer Support?

### ISSUE THREAD

**Issue by yaitsbilly** [Courseplay/courseplay#1358]
Will this support online?

**Comment by Satissis** [comment]
No at least not in the first release

**Comment by yaitsbilly** [comment]
Any news on when first release is coming?

**Comment by Phantum** [comment]
When it comes! ;P

**Comment by Satissis** [comment]
> Any news on when first release is coming?
Nop ;)

**Comment by Satissis** [comment]
#1375 Without MP
