### ISSUE TITLE
Suggestion for FS17

### ISSUE THREAD

**Issue by Vanquish081** [Courseplay/courseplay#1361]
Is it possible that the Courseplay for the FS17 when creating a route takes as reference the longest side of the field?

**Comment by knoxville73** [comment]
@Vanquish081 

it's exactly my best wish for the next CP

**Comment by ThomasGaertner** [comment]
what do you mean ? would you please describe more detailed ?

**Comment by Fogest** [comment]
Are you referring to the starting direction? Using the longest side as the side to start from as the default kind of idea?

**Comment by Vanquish081** [comment]
Correct line the longest side..

[http://i.imgur.com/FJUwvNo.jpg](url)

I don't know insert image, sorry.

**Comment by Fogest** [comment]
I see what you're saying, slightly different than what I was assuming. So in this case you're saying the starting direction may not be a cardinal direction but would instead be using an angle on the field based on the longest side? 

I can't comment on if this is possible as I'm not really a programmer for this, but just making sure it is clear what you're asking 😄

**Comment by Satissis** [comment]
I know that upsideDown and @fck54 were working on a new generation system for FS15, but how far they got, I'm unsure off. I haven't been able to get in contact with @fck54 so far.

Anyway, the first beta and release, I don't think this will be implemented in, but we might be able to add in an start direction later on that can be set to an specific angle, after the new turn system have been implemented.

**Comment by Galwaygrass** [comment]
Have you guys managed to make the new version work on dual direct tractors
such as the gemstone 900 and the Valtra, so that mowing silage harvesting
etc can be done?

**Comment by Galwaygrass** [comment]
Sorry auto correct should read fendt 900 and Valtra

**Comment by Micha23071982** [comment]
C:/Users/etwas/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/CpManager.lua:42: attempt to index field 'signs' (a nil value)

**Comment by Satissis** [comment]
@Galwaygrass I know that we have something in the code related to reverse driving and I believe in FS15 it worked, but again, it's one of the things that we actually haven't tested out. well at least i haven't heard Thomas have either

**Comment by Satissis** [comment]
#1375 Please test it for us :P
