### ISSUE TITLE
Unloading Chaff Havesters

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1362]
Sorry to bug you guys but would it be possible to have chaff harvesters unload themselves if they have an attached trailer and an unload course? Thanks. Hope FS17 conversion is going good.

**Comment by Satissis** [comment]
Hmm I actually thought that this was already implemented ?!? It was in the old days I believe, but maybe it's broken or I'm just remembering wrong :)
Will have to check it once we get the time for it.

**Comment by pops64** [comment]
I know the poettingerMex5 will self unload. But I can't seem to find the code in cp that performs this behavior.

**Comment by pops64** [comment]
Just to give you an update. I looked through the code and on line 90  in mode 6. I think the mex 5 returns true for this if statement and drives as a implement that can be unloaded. Now when you change this to get a chaff harvester to register(I just added 

if workTool ~= nil and (tool.attachedCutters == nil or vehicle.cp.tipperCapacity ~= nil ) then

). It does everything correctly(mostly but works) but I believe the tiptrigger ray cast(The three purple lines do not show in debug channel one) are not generated for combines which doesn't let it detect tip tiggers.(I think the problem is in the setMarkers fuction in tippers but I am not sure. That part of the code goes beyond my understanding) So it just drives back to the course with out unloading. Thanks for reading. I know your busy just trying to help for whenever you get a chance to look into this.

**Comment by ThomasGaertner** [comment]
it should work with the mex5. to let an self propelled chopper go in this manner is not and will not be implemented

**Comment by pops64** [comment]
May I ask why? I got it implemented by moving it into the forage wagons if statement. If I remember there was one issue(I think allowedtodrive became false some where) and some fine tuning to do. Everything worked fine I just needed a better variable for how I did this. Even FS supports this behavior. I know you guys are busy. Was just wondering

**Comment by ThomasGaertner** [comment]
then send me your mode6.lua I will have a look on it ...

**Comment by pops64** [comment]
This is my [mode 6 lua](https://www.dropbox.com/s/rv3nlci9zz11tgq/mode6.lua?dl=0) from FS15 which works 99% there was  fine tuning I had to do which was it resuming work to early though  I included something to fix that. Also the pipe did not fold during unloading course but was not a big deal. The other thing you do not see is that I had to force ray cast generation but when I was messing with FS17 I noticed that no longer had to be done. I guess some change you have made to 17 CP makes running a combine in the forage wagon IF statement not work at the moment. Once I get 17 working I will post it.(I can't remember how I did it but I did have it working 75%)  Thanks for replying and reading.

**Comment by pops64** [comment]
https://github.com/pops64/courseplay/blob/master/mode6.lua just posted it to my fork of courseplay. I am running into no bugs expect the harvester folds at end of course with still have fruit stored. Not sure if its related and the pipe doesn't fold during unload courses but that is because I haven't written code to support this.
