### ISSUE TITLE
Courseplay Dups?

### ISSUE THREAD

**Issue by mB-PiBox** [Courseplay/courseplay#1366]
So I'm seeing videos popping up with Courseplay in action on FS17. And I see a v4.01 available on several Mod sites available for download. However I see no updates to any of the github repo files.

Are these just dups of the official courseplay? Is this v4.01 a beta/alpha/bs version of the official release?

Most of the videos on this version are not in English, so I'm not able to watch them to hear if they mention what form of release it is, or if its even an official one.

I personally will not download any mods from these sites, as I'm not going to risk any malicious things happening to my system. And I don't have time to scan through all of the code to check for things that could do harm. When it comes to FS I only install official Giant Mods/DLCs and courseplay. 

Would be nice to get some clarification on this, or some sorta update here on GitHub or the Courseplay site if there is a beta/alpha release for FS17. I've got this game sitting waiting to play upon CP release.

**Comment by Fogest** [comment]
There is no official release of CP. They are either fake or ones from FS15 hacked to work in FS17 and may be pretty buggy or broken.

**Comment by sootysax** [comment]
you may want to peruse the closed issues before posting
