### ISSUE TITLE
bug work

### ISSUE THREAD

**Issue by sixtys666** [Courseplay/courseplay#1368]
Hello, I have a problem .... courseplay nastavim fertilization / sejen and he sows. Add to the end of the first row and the Bugno, you can not overeat or to another vehicle, you can not prep mod, I can max Alt + F4 to put it vybol will have come into it .... in my log writes
Running LUA error method .... Another problem I had when I bought the machine for packages (round) pick up the travel / straw accumulates up to 100% and the spill ...
[log.txt](https://github.com/Courseplay/courseplay/files/607923/log.txt)

In log: 
Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/RidgeMarker.lua:0: attempt to index a nil value
Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/RidgeMarker.lua:0: attempt to index a nil value
Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/RidgeMarker.lua:0: attempt to index a nil value
Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/RidgeMarker.lua:0: attempt to index a nil value
Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/RidgeMarker.lua:0: attempt to index a nil value
Error: Running LUA method 'update'. 
.....
.....
....
Do you know a show how to fix it?
Thank you for your answers.

**Comment by sixtys666** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/607928/log.txt)

**Comment by Satissis** [comment]
Simple answer.
Wait until we release our first beta. The version you are using is an wrong version, due to someone uploading an broken mod we are still working on converting over and we don't accept bug reports until our first beta is released.

**Comment by sootysax** [comment]
i hope that posts like this dont cause you guys to not want to work the real version..  i know it must be frustrating.

**Comment by skjatala** [comment]
The worst thing in the world is waiting for a particular object

**Comment by Satissis** [comment]
@sootysax no it will not.
We will normally just ignore messages like this while we are doing convert, but it's also polit to answere some times :) if we feal we want to do so ;)

**Comment by Micha23071982** [comment]
C:/Users/etwas/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/CpManager.lua:42: attempt to index field 'signs' (a nil value)

**Comment by Satissis** [comment]
#1375
