### ISSUE TITLE
Courseplay Beta shared in webs mods

### ISSUE THREAD

**Issue by Vanquish081** [Courseplay/courseplay#1369]
Hi, other version is shared in webs mods, this is different to the firts, credit is Dev Team, v0.00.00000

www.farmingmods2015.com/courseplay-beta-fs-17/

delete this post if is need.

**Comment by LordKena** [comment]
Is this a real Beta or is it a fraud

**Comment by JDTiger** [comment]
fraud... im pretty sure of that :P 
If they release a beta it would be here...

**Comment by LordKena** [comment]
Yeah, I thougt so too

**Comment by Vanquish081** [comment]
Is fraud, fake, how would you like ....

`Error: Running LUA method 'draw'.
E:/Mis Documentos/My Games/FarmingSimulator2017/mods/courseplay_beta/CpManager.lua:527: attempt to perform arithmetic on local 'xLeft' (a nil value)
Error: Running LUA method 'draw'.
E:/Mis Documentos/My Games/FarmingSimulator2017/mods/courseplay_beta/CpManager.lua:527: attempt to perform arithmetic on local 'xLeft' (a nil value)
Error: Running LUA method 'draw'.
E:/Mis Documentos/My Games/FarmingSimulator2017/mods/courseplay_beta/CpManager.lua:527: attempt to perform arithmetic on local 'xLeft' (a nil value)
Error: Running LUA method 'draw'.
E:/Mis Documentos/My Games/FarmingSimulator2017/mods/courseplay_beta/CpManager.lua:527: attempt to perform arithmetic on local 'xLeft' (a nil value)
Error: Running LUA method 'draw'.
E:/Mis Documentos/My Games/FarmingSimulator2017/mods/courseplay_beta/CpManager.lua:527: attempt to perform arithmetic on local 'xLeft' (a nil value)
Error: Running LUA method 'draw'.
E:/Mis Documentos/My Games/FarmingSimulator2017/mods/courseplay_beta/CpManager.lua:527: attempt to perform arithmetic on local 'xLeft' (a nil value)
Error: Running LUA method 'draw'.
E:/Mis Documentos/My Games/FarmingSimulator2017/mods/courseplay_beta/CpManager.lua:527: attempt to perform arithmetic on local 'xLeft' (a nil value)
Error: Running LUA method 'draw'.
E:/Mis Documentos/My Games/FarmingSimulator2017/mods/courseplay_beta/CpManager.lua:527: attempt to perform arithmetic on local 'xLeft' (a nil value)
Error: Running LUA method 'draw'.
E:/Mis Documentos/My Games/FarmingSimulator2017/mods/courseplay_beta/CpManager.lua:527: attempt to perform arithmetic on local 'xLeft' (a nil value)
Error: Running LUA method 'draw'.
E:/Mis Documentos/My Games/FarmingSimulator2017/mods/courseplay_beta/CpManager.lua:527: attempt to perform arithmetic on local 'xLeft' (a nil value)
Error: Running LUA method 'draw'.
E:/Mis Documentos/My Games/FarmingSimulator2017/mods/courseplay_beta/CpManager.lua:527: attempt to perform arithmetic on local 'xLeft' (a nil value)
Error: Running LUA method 'draw'.
E:/Mis Documentos/My Games/FarmingSimulator2017/mods/courseplay_beta/CpManager.lua:527: attempt to perform arithmetic on local 'xLeft' (a nil value)
Error: Running LUA method 'draw'.
E:/Mis Documentos/My Games/FarmingSimulator2017/mods/courseplay_beta/CpManager.lua:527: attempt to perform arithmetic on local 'xLeft' (a nil value)
Error: Running LUA method 'draw'.
E:/Mis Documentos/My Games/FarmingSimulator2017/mods/courseplay_beta/CpManager.lua:527: attempt to perform arithmetic on local 'xLeft' (a nil value)
..............`

**Comment by Micha23071982** [comment]
C:/Users/etwas/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/CpManager.lua:42: attempt to index field 'signs' (a nil value)

**Comment by Satissis** [comment]
@Micha23071982 that's because you are trying to use our not released beta version. that will happen to everyone that is not an developer.
Also no need for posting that in multiply issues. I have deleted the rest of the same messages
