### ISSUE TITLE
 Tractors with IC panel no open hud.

### ISSUE THREAD

**Issue by CarteretT** [Courseplay/courseplay#1374]
All tractors that have "IC Panel" or interactive controls dont open the courseplay hud. I changed controls to open IC panel but still can not open. The problem is that by default before changing the controls to open courseplay you need to enter the hud pressing the right mouse, but I can not. 
On other tractors with mods and without, it works without problem. I'm sure it's for IC panel, help me please

**Comment by skjatala** [comment]
Are you talking about Fake courseplay for Farming simulator 17?  Original is not out yet. I wondered  why Sensible people complaint if they are using a fake program (MOD).

**Comment by CarteretT** [comment]
I downloaded a beta from github, but I'm not sure it was yours. I'm sorry, I did not know there was a fake version. So courseplay is still in development for Fs17?

For me it is a joy because I will not worry then, I will wait until the official version comes out. If I can help with anything, here I am.

Thanks greetings!

**Comment by skjatala** [comment]
@CarteretT
https://github.com/Courseplay/courseplay/issues/1346#issuecomment-263827869

**Comment by Satissis** [comment]
#1375
@CarteretT you can assign another key for the courseplay hud in the keybindings. it's the secondary button
