### ISSUE TITLE
Beta is released !!!!! :D

### ISSUE THREAD

**Issue by Satissis** [Courseplay/courseplay#1375]
So after some sweaty, hefty and long hours/days/weeks, we have finally decided to give you the Beta.

We have been testing, we just didn't have the time to test everything, so what we would like you (beta testers) to do, is check all the vanilla equipments as an start and see how they are working.
There might allot of tweaking that needs to be done.

One bug we do know is if you have 4 or more CP drivers active and then exit to the menu, it will fill the log with an error. (We are working on fixing that one)

**Adding mods will wait until an later date!**

The beta is now in the master branch (Default code page) and can be downloaded from there.

## New features:
- **New Turn System**: for mode 4 and 6 (Stage 1: Turn system for lanes only. Headlands will come in stage 2)
- **New Save System**; Each course is saved in there own files now and is not linked to the savegame it self anymore, but to the map id in it's own CoursePlay_Courses folder.
- **Mode 7: Combine self unloading** -> can now create heaps as well. This is done by adding 2 waiting point instead of 1 (which is used to unload into an trailer). One for the heap start and one for the end of the heap. The combine will adjust the unload speed by it self while doing that.
- **Mode 9: Shovel Fill and Empty** -> This is now adapted to the new bunker type.
- **Lights:** Now switch on an off based on it's situation. When working on the field all lights are turned on. When driving on an recorded route or unload/refill route, it will use normal street light without the work lights.

Happy testing.
Kind regards
Thomas and Claus (Satis)

**Comment by BenB78** [comment]
Can't wait to get home from work and start testing! Thanks. :)

**Comment by knoxville73** [comment]
I would first like to thank you for your enormous work.
This mod is the most important for Farming Simulator !

First problem: The plow does not turn (Amazone Cayron)

**Comment by Homskiy** [comment]
Can i set <multiplayer supported="true" />? :)

**Comment by Satissis** [comment]
@Homskiy you can, but it will not work

**Comment by Nebular64** [comment]
Great job guys!!

**Comment by tjb8907** [comment]
Looking forward to testing it as well. One question, that I and probably many have. Do you prefer that we open a separate issue for anything we find?

**Comment by ThomasGaertner** [comment]
yea that would be handy to work the issues out and close them as well....

**Comment by pops64** [comment]
Question about the new save system. Does it have the same limitation has the old one. I know if 15 if you had to many saved course it would take ages for it to load the game(My recored was 5MB on the CP save file, took about 3 to 5 mins to load :D).  Will this still happen or will it behave differently now? Thanks for reading

**Comment by gibson89** [comment]
Great Job guys its good to have a solid release, did you solve the weaving problem? (I love cookies and MD5)

**Comment by ThomasGaertner** [comment]
What we forgot to mention is the automatic buy function from Giants. It also works for CP driven fertilizer sprayer, slurry sprayer, manure spreader and sowing machines....

**Comment by willie2016** [comment]
finally its here even if only beta testing ,can i ask will we be still able to use it for carting silage away from from forager to silage pits and will it tip automatically once it hits the triggers on the pits ? iv just recorded a course to try but it freezes the game once it hits the triggers

**Comment by krzysiexx04** [comment]
Hello,

Is it possible to become a beta tester of CP? I do appreciate your work, and thus I want to help you to make the CP even better. :)

Kind regards,
Krzysztof

**Comment by cabmac** [comment]
???? you can dl it....
https://github.com/Courseplay/courseplay

**Comment by krzysiexx04** [comment]
Hmmm... I thought it is more formalized. 
Besides, thank you for you reply.

**Comment by cabmac** [comment]
we are all beta testers... :)

**Comment by Tradeaux** [comment]
Hi total noob here, where do i find the download :P

**Comment by ThomasGaertner** [comment]
@willie2016 : please open a new issue, and  describe the situation as dedailed as possible. If its Silage in the BunkerSilo, activate Debug channel 1 and 2 and post the log into the issue
Thanks

**Comment by Tradeaux** [comment]
>download don't work
Tried both this and this none of them show up in game

Oh fail by me i guess, fixed my problem it was in a folder inside the .zip

**Comment by Satissis** [comment]
@TinMen6 yes just as an normal mod :)

**Comment by TinMen6** [comment]
i have a problem my game doesn't detect the mod - Cp

**Comment by petper** [comment]
Rename the folder so it doesn't contain - in it.

/Peter

Den 1 dec. 2016 5:49 em skrev "TinMen6" <notifications@github.com>:

**Comment by rmn18** [comment]
Under which version of LS 17 runs the beta of CP ?? 1.2.1 or 1.3.1 ??

**Comment by Andreas115** [comment]
I have the same problem. Courseplay does not appear in the modlist.

**Comment by rmn18** [comment]
Same her Error: Unsupported mod description version in mod ZZZ_courseplay ,Version of LS 17 is Version: 1.2.0.0 1.2RC6

**Comment by Tradeaux** [comment]
ok so this is how i fixed it... game version 1.3.1

1. download the .zip from the code section
2. open that .zip in it there will be a folder
3. extract that folder
4. open folder and re-zip what's in it
5. name it ZZZ_courseplay

**Comment by Nebular64** [comment]
@rmn18 The beta runs on v1.3.1 with a modDesc number of '34'.  If you're still on an older version, just change the modDesc number to '33' in the modDesc.xml file and it will show up in the game.

**Comment by rmn18** [comment]
Ok thanks ,have not updated ,my Game runs under 1.2 lol

**Comment by Satissis** [comment]
btw: just an side note. you don't need to name it ZZZ_ anymore :)
An sugestion to the name would be FS17_CoursePlay5.zip ;)

**Comment by Nebular64** [comment]
Good point ;-)

**Comment by Satissis** [comment]
oh and @Nebular64 changing the modDesc version back to 33 could break it as well, since there might be changes that requires patch 1.3.1 for it to work funny ;)

**Comment by rmn18** [comment]
Modesc 33 works perfect :-)

**Comment by Satissis** [comment]
@rmn18 Still there could be something that don't work :) there is an reason we adds the new modDesc version to it. so you should go update your game instead ;)

**Comment by Nebular64** [comment]
@Satissis Yeah, I tested it out on an older version with '33' and sometimes it would "hiccup", but thought I would just put it out there for those who are not on v1.3.1 yet.  I definitely would not recommend just anyone to change the modDesc all the time, but I know a lot of people were biting their nails on waiting for the No. 1 mod to come out ;)

**Comment by Andreas115** [comment]
So either I'm stupid or just on the wrong track.
I have installed the update 1.3.1 and inserted the zip as @ Tradeaux .....
Nevertheless, it does not appear in the modlist ....

**Comment by AgroWillem** [comment]
The mod is not showing up in FS17.
I DL the code.zip
Inside there is a 2nd map called courseplay-master
When i copy that 2nd map to the mods folder, nothing shows up.
When i zip that 2nd map and placeit in the mods folder nothing shows up.
?????

**Comment by TinMen6** [comment]
it didn't worked in zip for me then i just pasted a folder in my mods and it works ok now

tnx for the help and keep up the good work. I will make a donation to you guys in the next week or so right now i am a bit tight with cash ;)

**Comment by tjb8907** [comment]
> The mod is not showing up in FS17.
V1.3.1
I DL the code.zip
Inside there is a 2nd map called courseplay-master
When i copy that 2nd map to the mods folder, nothing shows up.
When i zip that 2nd map and placeit in the mods folder nothing shows up.
?????

You need to rename it. I don't think FS accepts the "-" in the name. 

You should either have a regular folder, or a zipped folder, and either way the files (and the 3 subfolders) should be just inside of that, not in a 2nd folder.

**Comment by AgroWillem** [comment]
It works as follows:

Make a new folder in mods f.i. ZZZ_courseplay
Copy the entire contents of the folder courseplay-master to this folder.

**Comment by Andreas115** [comment]
@AgroWillem 
thank you! now it  finally works.

**Comment by Satissis** [comment]
how to install is also in our manual at the bottom of that page :)
http://courseplay.github.io/courseplay/en/installation/index.html

**Comment by willie2016** [comment]
i just used cp to record a course in a grass field , i went around like im
supposed to , then went to fieldwork mode and generated my mower width and
all that stuff and set the directions to start/finish and then generated
the course , it shows where to start from but when i click drive now it
folds up the mowers and doesnt do anything after that

On Thu, Dec 1, 2016 at 10:50 PM, Claus G. Pedersen <notifications@github.com

**Comment by Andreas115** [comment]
Drive the first meters yourself with the mower and then continue at the next waypoint. This problem I had already with the LS15. Sometimes it worked, sometimes not.

**Comment by willie2016** [comment]
cp for 2015 worked correctly for me all the time to be fair , but thanks
for responce andreas

**Comment by Andreas115** [comment]
I have applied manure with the Zunhammer 18500 and the cultivator.
Each time Courseplay's assistant arrives at the end of the route, the game crashes. As soon as the message "The helper has done the task" appears, the game hangs up and nothing works.
The Zunhammer I drive with the New Holland T7.315

Otherwise, Courseplay works as usual. Thanks again for this mod. The best mod for the LS!

translated with Google

**Comment by Satissis** [comment]
Please post bugs/issues in there own new issue. This post it not for that :)

**Comment by RicolaRules** [comment]
Was pleased to see how well the new shovel mode worked in the BGA! Fantastic sir. I appreciate all you do. I'll be donating for your hard work, I hope everyone else that is able will also. These projects are very time consuming!

**Comment by Zeraphine** [comment]
Just a question cause i think i´m stupid :) how to set a course for a tractor with forage trailer to unload into a bga silo? i did it the old way but isn´t unloading the grass. so i have to do it like for the heaps for harvesters?

**Comment by mB-PiBox** [comment]
Are there any plans for a multiplayer/server beta release? Would like to test this out on my private dedicated server.

**Comment by gibson89** [comment]
I was also pondering wether CP will ever make it onto console I heard they
have mods now but I'm scared to buy it in case it doesn't

**Comment by mB-PiBox** [comment]
@gibson89 not possible; consoles don't allow user created scripts.. which courseplay is one big script(s)

**Comment by gibson89** [comment]
I thought as much I had heard similar limitations with fallout.

**Comment by ThomasGaertner** [comment]
hi guys,  these two links are to short videos of our new bunkersilo mode....

https://youtu.be/iClUiDUoKWc

https://youtu.be/LX1nKtz3WiE


#1516

**Comment by tjb8907** [comment]
Looks awesome! Was just trying to fill a bunker and thought about trying to make a mod that would keep the blade at a certain height above the ground, but this will be way better!

**Comment by Andreas115** [comment]
@tjb8907 
is it a lot of work to create the mod keeping the blade at a certain height???? that would be awesome!!!!!!

**Comment by Nebular64** [comment]
Nice!  Can't wait to give it a tryout.

**Comment by tjb8907** [comment]
@Andreas115 It was never more than a thought, so I'm not sure. with this new Silo Mode coming I don't know if it would be work the work. Excited to try it out!

**Comment by ThomasGaertner** [comment]
could anyone tell me the correct english term  for the blade/shield/dunno

**Comment by tjb8907** [comment]
I would call it a Blade, but shield works too. most farmers in the Midwest US that I deal with it would call a blade I think.

**Comment by Nebular64** [comment]
Same with Southeast US.  Farmers here would call it a blade.

**Comment by tjb8907** [comment]
Hoepfully the naming is the final touches before release! ;)

**Comment by Andreas115** [comment]
Maize leveller 

Homepage of Holaras in the Netherlands :-)

**Comment by AgroWillem** [comment]
Wow awesome mode! Would be a very nice extension of CP. :D

**Comment by AgroWillem** [comment]
Great it's there! Is there somewhere a manual how to use the new mode?

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
