### ISSUE TITLE
New Turn System doesn't works properly

### ISSUE THREAD

**Issue by diegopol** [Courseplay/courseplay#1376]
Hi Guys.
I have been using mode 4 (CoursePlay v5.0.00001 Beta), but, when the tractor goes at the end of the boundary, it's stopped a few meters before, causing a bad seeding as you see in the attached picture.

![screen shot 2016-11-30 at 4 34 39 pm](https://cloud.githubusercontent.com/assets/428129/20772310/0c07f41a-b71b-11e6-99e3-ec9f90a95c25.png)

**Comment by Satissis** [comment]
Right. one of the seeders we haven't tested :)
I'll look into it right away ;)

**Comment by Satissis** [comment]
Should work fine now ;)

**Comment by diegopol** [comment]
Yes! it's works very well. thanks
