### ISSUE TITLE
Great Plains Seeder 3P1006NT

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1379]
Mode 6 does not lower this implement on course start(You can manually lower it and it drives just fine. The turn maneuvers is raising and lowering properly(Does not stop at field edge on turn finish). Couldn't test the refill course Drive Now button does nothing. No errors in log). Also if you leave the ridge markers on auto it spits out . 

Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/RidgeMarker.lua(263) : attempt to index a nil value

And requires a game restart to clear. This seeder has no ridge markers

Debug channel 17 at [pastebin](http://pastebin.com/fM2nZQcE)

Sorry for breaking CP so quickly.  I have this mod do just about everything for me in FS. Keep up the good work :D

**Comment by Nicksil** [comment]
Want to say thanks to the CoursePlay team -- you folks are excellent.

Came here to post this issue as well.

**New** game/save, no additional mods, on **normal** mode and using the **stock** equipment you start off with.

When starting course, turns on machine, but **does not lower**.

Will then **freeze** and log reveals (in a seemingly infinite loop)
```
Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/RidgeMarker.lua(263) : attempt to index a nil value
```

Must manually exit application.

No sweat, though! Thanks again!

**Comment by ThomasGaertner** [comment]
try again with 5.00.0003 and report ....

**Comment by ILfarmer** [comment]
just tried with version 5.00.0006 and everything seems to be working fine.  Helper lowers seeder and no error in log.  Thanks for quick fix:)

**Comment by pops64** [comment]
Just got this with 006 

C:/Users/Ryan/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/mode4.lua:229: attempt to get length of field 'ridgeMarkers' (a nil value)
Error: Running LUA method 'update'.

I will test with 007

**Comment by pops64** [comment]
So Far Everything seems good. I will go ahead and close this for now. Will let you know if I run into anything else. Thanks
