### ISSUE TITLE
Invalid Mod Description version

### ISSUE THREAD

**Issue by delawarehunter** [Courseplay/courseplay#1381]
I hope I'm doing this right... downloaded the master branch, created a zip file, and placed the zip file in my mod folder.  Opened FS17 but Courseplay wasn't in my mod list after selecting a career game.  Checked the log and it says "Error: Unsupported mod description version in mod ourseplay".  

Checked the ModDesc.xml and the version says 34.  Other mods are using a version 32.  I changed it to 32 and it seems to be working...

**Comment by delawarehunter** [comment]
Nevermind.. closing this issue.  It's because I wasn't updated to 1.3.1... I didn't realize there was an update out.  Version 34 works ok if you are on the most recent FS2017 update.

**Comment by pops64** [comment]
It should be version 5.002

**Comment by delawarehunter** [comment]
I wasn't talking about the Courseplay version.. I was talking about Line 2 in the ModDesc.xml file.  It should read: <modDesc descVersion="34"> as long as you are using FS2017 Version 1.3.1.  If you are still on 1.3 that line has to be set to 32 or lower (I think).  Once I updated FS2017 to the latest version, I was able to use descVersion 34.
