### ISSUE TITLE
CoursePlay Route editor

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1382]
I know this is certainly not on your priortity list, but the new savegame system will probably negate the use of Coursedrawer (which has remained unchanged since FS13).  Are the course .xml files formatted at all the same as in fs15?

I personally like to create a network of combined routes to get around the map.. and without Coursedrawer to be able to place and tweak crossing points on multiple courses at once, there is no way I would ever be able to get combined courses to work.

I'm wondering if you have a Courseplay editor anywhere at all on your radar.. and if you were able to use the old Coursedrawer editor with the new savegame system.

**Comment by pops64** [comment]
You could do it the oldway.  Edit the file directly. The format still appears the same. But now it looks like the courses are broken into there own file now. And it looks like the manger file associates that number file with a corresponding course in game. Have fun :D

**Comment by sootysax** [comment]
all in good time..  i know Satis was involved somewhat in a course editor..  not sure what his thoughts are

**Comment by PromGames** [comment]
The courseplayEditor for FS17 based on courseplayEditor for FS15 will be available in beta soon. It will published in ModdingCentral and notified in FSUk when ready.

**Comment by sootysax** [comment]
great news!

**Comment by Satissis** [comment]
Yep @PromGames made an new one for FS15 and as he said, he is working on the FS17 version now.
( @PromGames  Sorry for not giving you an heads up on this ;) )

I'll close this since the questions have been answered and to clean up the issue list a bit ;)
