### ISSUE TITLE
Helper will not turn

### ISSUE THREAD

**Issue by tjBerlin** [Courseplay/courseplay#1383]
Hallo guys! 

Thank you for CP 17!!! It makes the gameplay much more interesting! 

Just a little thing: By powing with the Salford MODELL 8312 (6,2 meter) the helper didn't get the turn at the end of the field. He ist just circling around, not finding his way back to the line. 

I uses the course generator with 2 headlands. The field is square. 

Best regards, tj

**Comment by sootysax** [comment]
I am also getting circling around a point on turns..  

it's usually happening on some of the sharpest turns on the lanes following a headland route..  the ones that result in a very pointy lane turn rather than a nice square one.   I do dig the reverse turn manuever that sometime happens in that situation though ;)

**Comment by sootysax** [comment]
this always always seems to happen on the first or second lane after the headlanes are finished

**Comment by tjBerlin** [comment]
Hmmmh... I do my headlanes after (or even better: let do). But it happens always. But until now, only with the pows.

**Comment by Satissis** [comment]
hmm plough.... is that the big pivoted one ?
Lol I haven't tested any ploughs in FS17 :P

**Comment by pops64** [comment]
Yes. Its the big one. It has two pivots points(One where it attaches to the tractor, another in the tool itself) and tries taking turns to tight.

**Comment by Satissis** [comment]
Might be one of those things what we cant reverse with at all. which means that I can fix it, but it will take an bigger turn maneuver and headland will be an must or else it will be an big one outside the field :)
We will see when I get to it ;)

**Comment by Satissis** [comment]
Try 010 and report back :)

@sootysax yeah that's because those points are not sett as turn points. We will first look into that when we do the headland face of the new turn maneuvers :)

**Comment by gec100** [comment]
I've tested it with Salford MODELL 8312 and with enough headlands turns OK. 
With Lemken Titan 11 is a different story. It tries to do three point turn but it does not calculate the tool behind. This plow is not pivoted so turning should be similar as with trailer.
![fsscreen_2016_12_02_07_33_02](https://cloud.githubusercontent.com/assets/8178773/20825205/d52a381a-b862-11e6-9fdd-bdc4c3c36f8a.jpg)
This is with Turn on field deactivated.

**Comment by tjBerlin** [comment]
Hi! Tryed Version 13 and it worked fine! The helper turns forward. Perfekt. 

Thank you very much! 

CU tj

**Comment by pops64** [comment]
@gec100 #1406 Statissis is working on the lemken. And the 8312 was a pain to test for Statissis's fix for it with out any head lands. That thing turns like a ship

**Comment by Satissis** [comment]
As the Lemkem is also mentioned in #1406, I'll close this one, to clear up the issues :)
