### ISSUE TITLE
silos operation

### ISSUE THREAD

**Issue by fudoido** [Courseplay/courseplay#1384]
Hey team, thanks for the fair fast time you had converted the mod to fs17, i really thought it would take much longer.

after trying it for silage colect and unload, which was all working fine with combi mode and unloading combine, however when unloading to silo it warns about trigger detection but doesnt unload in the silo area.
me considering this was due to silos now having to be downloaded with "tip anywhere" new feature of fs17, i created a small chaff heap in the middle of the silo and went back to initial course point. again, when passing through silo, it would detect trigger but doesnt unload in the newly created heap the same......
so, am i doing something wrong? are there any changes to silo unloading? is it a bug? using only vanilla equipment.

**Comment by ThomasGaertner** [comment]
the concept is that you can unload in the BunkerSilo in two ways: forwards and backwards. Forwards it will concider the length of the BunkerSilo and calculate the speed to unload completely within this range. If you create a route backing up into the silo, the trailer will be unloaded on the "entrance" of the bunkersilo an leave the Bunker forwards when empty. ihas Gives you the chance to create your own silo setup with a shield or a shovel. later on, maybe I can get the automaticSiloCreation system running properly, we will maybe include it as a new mode (as seen on the pic )
![fsscreen_2016_11_20_12_44_32](https://cloud.githubusercontent.com/assets/3279913/20784419/7abc249c-b79a-11e6-9f4f-281b2031ddbd.png)

if there are still difficultys, please do it again with Debug 1 and 2 active and post the log....

**Comment by sootysax** [comment]
can a bunker be totally empty and CP will trigger unloading?

does it need to be established with chaff already in it?   

do I need to set waiting points at the beginning and end of the bunker?

**Comment by ThomasGaertner** [comment]
@sootysax : you mean the shovel mode right ? for the user its the same as in FS15, the changes are internal...

**Comment by sootysax** [comment]
no i was talking about backing a loading wagon into an empty silage bunker...

here is debug 1 and 2, backing into and pulling out of the bunker, but never unloading.

https://gist.github.com/sootysax/108317779633866524e0a916352e4642

**Comment by Satissis** [comment]
From what I can see in the log, then the filltype is not accepted.
`trigger (23060): inputFillType=25 -> fillTypeIsValid=false`

Something to look into @ThomasGaertner ;)

@sootysax could you provide and savegame with the setup and the course for it?
It would make it easier for Thomas to test it when he get around to it :)

**Comment by sootysax** [comment]
https://dl.dropboxusercontent.com/u/36294746/%231384_SAVEGAME.zip

**Comment by ThomasGaertner** [comment]
try again with v009 or higher and report....

**Comment by crazyprsn** [comment]
I tried with v012 and the loading wagon still doesn't dump into the bunker. I'm wondering if it has to do with what @sootysax mentioned earlier - in FS17 you have to "force unload" in the bunker (ctrl+I) rather than a triggered unload ( I ).

**Comment by homerbucket4001** [comment]
i'm having the same issue with the loading wagon not dumping in the bunker. once it enters the bunker it runs into the wall and stops.

**Comment by ThomasGaertner** [comment]
give me the logs with debug 1 and 2 active please....

**Comment by sootysax** [comment]
backing into trailer with 5.00013 - trailer hits trigger and reversing line disapears and CP reverse control goes dead

https://gist.github.com/sootysax/33c0945141e646ac5710bd2349567b6a

**Comment by ThomasGaertner** [comment]
yea ,there was something wrong since the BunkerSilo is not a native TipTrigger ...
try v.014 and report....

**Comment by sootysax** [comment]
driving foward through the bunker worked properly, starting at the back and dumping the lenght of the silo.

backing into the silo dumps the entire load at the first possible place backing into the bunker..

video: https://www.dropbox.com/s/vbb7tb5t7zeabz4/2016-12-02_195448311.mp4

https://gist.github.com/sootysax/b79be4e4a2f415042c98672dd3b8bce6

**Comment by homerbucket4001** [comment]
Unloading going forward seems to be working now with v014. Thank you!

**Comment by ThomasGaertner** [comment]
@sootysax its on purpose, its prepared to fill the silo with the shield or shovels. Btw: backing into a half full silo went terribly wrong so we disabled this function to prevent issues with that. Our plan is, to create a new mode which will let the tractor make the silo from the heaps tipped into the first part of the silo.
I want to close here since the issue seems to be resolved ...

**Comment by sootysax** [comment]
this is happening on Old Streams Farm v 1.0.2

video: https://dl.dropboxusercontent.com/u/36294746/2016-12-03_101233737.mp4

https://gist.github.com/sootysax/3025dcf7a54e90b60a4b5e6279289ed3

**Comment by ThomasGaertner** [comment]
![image](https://cloud.githubusercontent.com/assets/3279913/20860735/b30494ec-b97f-11e6-9aac-ae19e965ba69.png)

as you can see on the pic , the markers for the bunkersilo area are set wrong, we consider the area between start, width and height as BunkerSilo area. So it does, what it has to do: tip into the BnkerSilo area...
