### ISSUE TITLE
Turn Maneuver - Sprayers

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1387]
Noticing that the lane turn maneuver for the fieldwork (1 Headland) seems to be based on the width of the vehicle.   driving the tires of the vehicle close to the edge (sometime over) the edge of the field..   however there are still 6m of sprayer arm on either side, and they collide with trees or whatever else is on the edge of the field.

another good reason to have the internal lanes of fieldwork be based on the edges of the working width of the tool rather than the center line of the headland course ;)

**Comment by Satissis** [comment]
What sprayer is it ? It's one of those that needs to be added into our special tools section for it to know it needs to take the boom width into account :)

**Comment by sootysax** [comment]
it was the Amazone UF 1201 and Stilla 406

**Comment by Satissis** [comment]
alright. I'll have an look into it tonight :)

**Comment by Satissis** [comment]
Try with v.022 or higher and report back

**Comment by gec100** [comment]
Tried Stilla 460 and it works beautifully :) 
NH SP400F still has problems. Makes also a wonderful turn, then backs to start from the beginning of the lane, but instead of finishing reverse maneuver she continues making reverse donuts.

**Comment by Satissis** [comment]
Arh it's the self propelled sprayer. I haven't tested it my self, just added so it would account for it's bom while turning. I'll have to try that one out to see what funny stuff it's doing :)

**Comment by Satissis** [comment]
Try out v.030 or later and report back.

**Comment by Satissis** [comment]
Try v.034 or later and report back

**Comment by Satissis** [comment]
Since no respond to this, I'm guessing it's working.

Closing issue (Reopen it, if it's still an problem)
