### ISSUE TITLE
sugar beet madness Terra Dos T4-40 not triggering driver

### ISSUE THREAD

**Issue by joshthegrate** [Courseplay/courseplay#1388]
courseplay seems to not recognize the Terra Dos T4-40. it shows in the list of combines but i get "No combine in reach" even tho i have it selected manually.

**Comment by ThomasGaertner** [comment]
try again with v5.00.00005 or higher and report .....

**Comment by joshthegrate** [comment]
thanks it now works . the offsets are a bit off but i can manually change that.

**Comment by ThomasGaertner** [comment]
should be 4.9 m can we close here ?

**Comment by joshthegrate** [comment]
yes
