### ISSUE TITLE
Combi/ Mode 2 Issues

### ISSUE THREAD

**Issue by tjb8907** [Courseplay/courseplay#1389]
First off, thanks for the hard work in getting a working version together! I am happy to have it back, and excited to see what kind of improvements you guys can make! Your programming skills are top notch. 

Couple problems I noticed so far using mode 2.

1. With the AI Helper running the combine, when the tractor is unloading the combine, and they both stop at the end, and then the tractor gets full before it is done unloading, the combine just sits there and doesn't continue on. This only seems to happen when the tipper gets full, AND they are stopped at the end of the pass.  I have not tried to see if it works when the combine in using Mode 6, as I usually like to use the AI Helper when I only have 1 combine running. EDIT: I tried running the combine in Mode 6 and so far it hasn't done it. 

2. I also came across an issue when the silo reaches its capacity. The tractor will stop unloading with some left in the tipper, and drive back to the field, but it doesn't go back to unloading the combine. It displays a message saying it is done transporting grain. I have to stop and restart it to get it to continue looking for combines to unload. 

Is there debug data I can collect to help?

**Comment by ThomasGaertner** [comment]
try again with v 5.00.00006 or higher and report ....

**Comment by tjb8907** [comment]
Updated to 006 and was going to test it but had issues with my sprayer in mode 4 ( was running at same time as harvest.

Error: Running LUA method 'update'.
C:/Users/Tom/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/mode4.lua:229: attempt to get length of field 'ridgeMarkers' (a nil value)

Guessing that a change in 003 (i went from 002 to 006) needs to ignore implements that don't have ridgemarkers.

**Comment by Satissis** [comment]
@tjb8907 That last push I did should fix the ridge marker error

**Comment by tjb8907** [comment]
Ok I will test again later today.

**Comment by ThomasGaertner** [comment]
what about the mode2 issue?

**Comment by tjb8907** [comment]
Have not had a chance to test it yet. Should be able to look at both tonight after work.  :)

**Comment by ThomasGaertner** [comment]
K then, for tests please use the concerned tools only ...

**Comment by tjb8907** [comment]
Right, sorry about that I kind of got 2 issue into 1 when I did that. 

Anyway here is what I found.  The combine continues on after filling up the tipper to 100% like it should. That part is fixed. 

The tractor in mode2 goes back to the last point with the remaining grain that didn't fit in the silo, but when it hits the last point it throw this error once. 

`Error: Running LUA method 'update'.
C:/Users/Tom/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/tippers.lua:768: attempt to index field 'cp' (a nil value)
`

It does continue to wait for the combine to reach the set fill level, and when it does the tractor drives forward and says "drive behind combine, but it just keeps driving in the wrong direction. Not sure if its going to a specific point (maybe 0,0)? or it is just drives in what ever direction it was pointed.

**Comment by ThomasGaertner** [comment]
try again with v .013 or higher please...

**Comment by tjb8907** [comment]
The error is gone now, but the tractor still just drives straight ahead sometimes. I can stop the driver, and restart and it will then drive to the combine. It registers like it should, but just doesn't get the right coordinates.  Doesn't seem to happen every time, and I have had it do it a couple times when the silo wasn't full too. I'll keep testing and seeing if I can isolate the issue. Is there anything in the log/debug that would help?

**Comment by ThomasGaertner** [comment]
please have a look on the calculated turn circle, which value has it ?

**Comment by tjb8907** [comment]
It seems to be working now. combined a few fields tonight with no issue. Thanks!
