### ISSUE TITLE
Slurry transport will not trigger at BGA digestate tank.

### ISSUE THREAD

**Issue by crazyprsn** [Courseplay/courseplay#1390]
I've been trying several ways, and used old FS15 instructions to get manure transport mode to work for the digestate tank in the BGA to a field container. It will overload digestate into the field container, but will not trigger at the digestate tank in the BGA. 

One thought - could it be the fact that FS17 identifies digestate as a different product than slurry, and might be confusing CP in manure transport mode?

I don't have any pigs or cows to try real slurry on.

**Comment by ThomasGaertner** [comment]
try again with v008 or higher and report...

**Comment by crazyprsn** [comment]
Downloaded and tested the same situation with v012, and the BGA digestate tank now triggers as fillable in manure transport mode.

However I was having an issue with the tanker only staying at the field container for a few seconds and then moving on without completely filling or emptying its contents. 

I found in the settings tab, that the default wait time is "5 sec", I lowered it to "0 sec", and the transport then stayed at the FRC to fill completely, then behaved as expected afterward. I'm wondering if the "5 sec" "waiting time" for manure transport mode is intended, or if it should be defaulted to "0 sec". (would you like for me to submit a separate issue for that?)

Otherwise, I see this current issue as resolved. Excellent work fellas!

**Comment by ThomasGaertner** [comment]
I've checked the code: the default waitTime is 0 . would you please try with an new savegame to replicate this or check in the vehicles.xml of the savegame and look for "waitTime=" of the vehicle concerned

**Comment by crazyprsn** [comment]
v012

"waitTime=0" is default in both old save, and a fresh save in vehicles.xml, and testing a playthrough.

I must have been at fault for changing settings by mistake before generating the course. Issue resolved.
