### ISSUE TITLE
vehicle does not stop

### ISSUE THREAD

**Issue by Nentorro** [Courseplay/courseplay#1400]
First many thanks for the beta. I am directly at the test of a transfer course that at the end of the stretchers the vehicle does not stop, but slowly continues to drive. And sorry for my bad english. Google can not do it better ;-) If you can German, tell me that would be easier for me

**Comment by skydanc3r** [comment]
hast du am letzten trigger /wegpunkt warten angemacht ?
![fsscreen_2016_12_01_18_25_25](https://cloud.githubusercontent.com/assets/1697521/20804610/d7b6b014-b7f3-11e6-8f0e-7eb4e5263f2f.png)

**Comment by Nentorro** [comment]
Owei.  Muss ich das jetzt extra aktivieren? Okay das erklärt es. Bin anscheinend ls15 verwöhnt. Lol. Danke dir. Ich werde es nachher mal probieren

**Comment by skydanc3r** [comment]
NP :)

**Comment by Satissis** [comment]
yeah you need an wait point at each stop you want to do in Transport Mode or it will just continue in an circle :)

**Comment by Nentorro** [comment]
Thanks for help.

**Comment by skydanc3r** [comment]
kann ich es schlissen ?

**Comment by Nentorro** [comment]
Ja klar. Danke dir nochmal.
