### ISSUE TITLE
CP not showing on some mod vehicles 

### ISSUE THREAD

**Issue by gec100** [Courseplay/courseplay#1401]
To start i'll just copy/paste what Zibbl said:
"First of all... a big big thank you for courseplay. You guys are awesome and I appreciate your work. !!" :) 👍 

Just came from work and I just wanted to look at some news here and what did my eyes see?! CP beta is out, awww yeah !! (some more copy/paste from Zibbl :)

I know it is early stage and i know this will happen a lot but here is what i've found so far;
CP window is not showing on
- John Deere 8530 by Sotillo/Rysiu77
- John Deere 8R by TechMod a.s.

**Comment by gec100** [comment]
forget this. just sow that no mods would be looked in too.

**Comment by Satissis** [comment]
yeah right now mods have to wait. that way it will be easier to fix all the vanilla vehicles :)

We will work on mod support later on thou ;)

**Comment by gec100** [comment]
thx m8 for the hard work!
