### ISSUE TITLE
Crop destruction! 

### ISSUE THREAD

**Issue by p4r4d0xs** [Courseplay/courseplay#1402]
Will be the crop destruction implemented? I play with the Mod, and Courseplay is driving thru my field and destroy my crops! But Bypassing the Crops is activated (dont know if its right translated?)

https://abload.de/img/fsscreen_2016_12_01_1iebum.png

So the new WorkerAI from FS17 is now 1000% better than the CP Worker, maybe you can use some work from GIANTS and maybe detect some collisions like the Worker from FS17 and turn auto. back

**Comment by gec100** [comment]
deactivate the Turn on field option. Maybe that'll fix your AI problem.

**Comment by pops64** [comment]
#1367 If the tipper is called at the end of a lane that it can unload on will still do it even if it drives through the field

**Comment by Satissis** [comment]
Crop avoidance is something Thomas are working on implementing again.

Regarding WorkerAI from FS17 is now 1000% better than the CP Worker, well it's not just as simple as that.
I did had an talk with fruktor from giants about it before and it's not just something we can just do.
That's also why we have headlands generating. There is still tweaks that needs to be done for the new turn system.

**Comment by p4r4d0xs** [comment]
its great to hear Satissis! :)

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
