### ISSUE TITLE
Lely Splendimo 900MC stock not folding

### ISSUE THREAD

**Issue by gec100** [Courseplay/courseplay#1403]
hi again!
did I mention how happy I am to see this beta out? :D

As mentioned in the subject 900MC will not finish folding when playing the course from the beginning. If I unfold it and start from nearest point, works fine.

keep up with a good work!!

**Comment by knoxville73** [comment]
It's the same with the Lemken Gigant 10

**Comment by gec100** [comment]
+ Novacat X8 and Novacat 302

**Comment by gec100** [comment]
I did not mention that this folding problem is preventing tractor to start the course. Cause it waits for tool to fold.

**Comment by tjb8907** [comment]
I was having problems with the AllRounder Cultivator last night as well. If I started the course (mode 6) going to the 1st waypoint, it would just stop where it was (not at waypoint 1) and sit there. You can hear the folding sound but it doesn't move. If drove manually to waypoint 2 are resumed from there it would work.

**Comment by Siniy-lom** [comment]
in this configuration, categorically refuses to work, regardless of waypoint
http://i.piccy.info/i9/cb22120ef3acd17844822a0fc73a6cd7/1480631650/351047/1086988/fsScreen_2016_11_26_03_12_04.jpg

**Comment by Satissis** [comment]
@Siniy-lom dude!!! :P you would never really do that configuration in real life and courseplay is not build to do that kind either :) it might work, but since there could be an problem in one of the tools, I would really suggest not to do that in beta + some of them are mods (at least the windrower is) which we are waiting to support until the vanilla equipment is working alright :)

but it's an funny and interesting configuration :)

**Comment by ThomasGaertner** [comment]
try again with v.012 and report.....

**Comment by tjb8907** [comment]
The Allrounder Cultivator works like it should now. Thanks

**Comment by gec100** [comment]
Folding is now working fine. There ate couple new problems with mowers, not sure if this is for a new issue;

- Discbine 313 has a turning problem similar to the Titan 11 plow,
- Novacat 302 offset is not recognized.

**Comment by ThomasGaertner** [comment]
the novocat offset must be set manually, for the turn problem please refer to the issue concerned...
I will close here.

**Comment by Siniy-lom** [comment]
@Satissis I check today evening
