### ISSUE TITLE
Key commands

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1404]
1. It doesn't seem like the (Left Ctrl - Keypad 8) 'Stop at last point, next trigger' key command is working.

2. I would very very much like to have a key command to toggle 'Start course at; nearest, current, first waypoint' - it is very sorely missed

**Comment by Satissis** [comment]
1. Something we will have to check.
2. are you meaning an key command for each of the 3 choices ? like 3 new key bindings ?

**Comment by sootysax** [comment]
no just a toggle switch so i can trigger it from a controller without using the mouse

**Comment by sootysax** [comment]
while we're talking about it, I would sure love to be able to assign key bindings for each of the 'move to shovel positions'

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean

**Comment by sootysax** [comment]
any further thought about adding some key bindings for other CP commands that I constantly need to use my mouse for?

what I feel are very needed are:

'next and previous' for the top row of displays (combi controls, courseplay control, manage courses, settings combi mode, manage combines, speed limits, settings, driving settings, course generation, shovel controls, leveller controls)

a button that toggles 'start course at:' (first, nearest, current)

'clear current course'

'search for courses and folders / search for first waypoint'

**Comment by Satissis** [comment]
Not sure if we will have an look at this before the release. It's still on out suggestion list
