### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by Nentorro** [Courseplay/courseplay#1405]
Error: Running LUA method 'draw'.
C:/Users/nento/Documents/My Games/FarmingSimulator2017/mods/courseplay_master/CpManager.lua:527: attempt to perform arithmetic on local 'xLeft' (a nil value)
Error: Running LUA method 'draw'.

**Comment by ThomasGaertner** [comment]
sorry, crystal ball is broken,, When does it happen, with which tools in which situation ?????

**Comment by Nentorro** [comment]
I can think imr nu, this is connected with the help menu F1. Since when I activate it only motor start. That in very many lines. My log is full with exactly this one message

**Comment by pluto1980** [comment]
Hi, i have the same Issue. But i found out when i disable The Mod "MultiOverOverlayV2 Hud LS17 Convert" from HappyLooser then the error is away

**Comment by pluto1980** [comment]
It is also a pity, but the developers i hope will come up with a solution, be it by happylooser or the courseplay team

**Comment by Nentorro** [comment]
Even if there was no solution, I would then decide for the courseplay. Since it is a very good and powerful tool for the Farming Simulator

**Comment by pluto1980** [comment]
I think you're right. But have already written on modhoster.de the developer already. Times wait, maybe he can achieve what or exclude it to his scripts.

**Comment by Satissis** [comment]
try v011 and report back.

the problem was values that was renamed from Giants side. should work now.

**Comment by Nentorro** [comment]
Damned since you quickly to fix problems :-) For that you have my respect. I try it but morning only from :-)

**Comment by Vanquish081** [comment]
![Example](http://i.imgur.com/KrLbgPr.jpg)
![Example](http://i.imgur.com/ADc80Pt.jpg)

**Comment by Satissis** [comment]
@Vanquish081 I'm pretty sure you haven't updated to v.011 or greater.
Past your log as well, which will tell it

**Comment by Vanquish081** [comment]
@Satissis 5.00.00007

**Comment by Nentorro** [comment]
Version 0.13 its okay. No LUA error

**Comment by Satissis** [comment]
@Vanquish081 this was fixed in v.011 :) the version you wrote is v.007 so update and try again ;)

@Nentorro Alright. I think we can close this then :)
