### ISSUE TITLE
Trailer Silo

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#1409]
Hi! Thanks for the great conversion of Courseplay! Is there a possibility in the Ls17 silo to unload? Maybe on the basis as with the potato harvesters! thank you

Lg

**Comment by ThomasGaertner** [comment]
sorry, I dont understand, what's the issue

**Comment by Satissis** [comment]
if it's easier for you, white in german, thou it will mostly be Thomas that can answer you then, since I will have to use google translate to see what you say and that don't translate that well all the time :)

**Comment by Paul2510** [comment]
HI! Meine Frage wäre nur ob es eine Möglichkeit gibt im LS17 Silo mit Courseplay zu entleeren! Z.B So wie das mit dem Mode 7: Combine self unloading funktioniert! Das mann im Silo 2 wartepunkte setzt! 

lg

**Comment by ThomasGaertner** [comment]
hmm, ich habe es immer noch nicht ganz verstanden, Welches Silo möchtest Du  mit welcher Frucht in welchem Modus entleeren/befüllen ?

**Comment by Paul2510** [comment]
Guten Morgen! Ich meine den Cow Silo wo kein Trigger ist sondern ein Haufen erstellt werden muss!

**Comment by ThomasGaertner** [comment]
hast Du denn mal ausprobiert, mit dem vollen Hänger durchzufahren ? eigentlich sollte der abladen ....
Wenn der nicht ablädt dann hänge ich das hier an #1384 und mache zu

**Comment by Paul2510** [comment]
Habs mit vollen Hänger getestet ging leider nicht! Map Westbridge_Hills_Map Traktor Orginal 700 Fendt und Mengele Garant von Maurus!

**Comment by ThomasGaertner** [comment]
Ok dann mach ich hier zu, Momentan müssen wir uns um die standart- Tools kümmern, der Mod-Support kommt dann später...
