### ISSUE TITLE
Reverse driving with chaff chopper

### ISSUE THREAD

**Issue by SnoopBok** [Courseplay/courseplay#1410]
First of all, thanks for the great mod, without courseplay farming simulator isn't much fun 👍😄

I'm using the tractor chaff chopper with the Valtra S series. I use the reverse driving in field mode, but the tractor will go left, right, left, right etc. It won't follow a straight line. Does courseplay support reverse driving?

**Comment by Satissis** [comment]
we haven't really tested the reverse driving, so I'm guessing not :)
Something we need to look into when we clear out the bugs from the bottom up :)

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean

**Comment by Satissis** [comment]
Implemented in v01.0052. 24307941250a161a9763b633170fb724719864fd
Try it out and report back.

**Comment by Satissis** [comment]
Closed Due to inactivity
