### ISSUE TITLE
field work : back mowers stuck folding

### ISSUE THREAD

**Issue by santaranger** [Courseplay/courseplay#1411]
Some back mowers get always stuck in the folding animation, when trying to return to first point / start at first waypoint. They fold up and then their tips get in a folding/unfolding loop.
Those parts do not usually fold/unfold separately on the back mowers - only on the front mowers (at least I haven't found out how to do it)

Test case: Start driver with mower installed on the back. Generated field course, set to  "Start course at first waypoint"
Tested with:
- Novacat 302 ED (yellow tip wiggles up and down)
- Discbine 313 (no issue)
- Novacat X8 ED (both yellow tips wiggle up and down)
- Splendimo 900 MC (no visible wiggling, but folding  sound audible)

**Comment by ThomasGaertner** [comment]
#1403 closed due to double posting
