### ISSUE TITLE
Error: Running LUA method 'update'

### ISSUE THREAD

**Issue by Nicksil** [Courseplay/courseplay#1413]
CoursePlay version: **5.00.00011** (latest at time of writing)
Game Difficulty: **Normal**
Other mods: **None**

Error:

```
Error: Running LUA method 'update'.
dataS/scripts/utils/Utils.lua(124) : attempt to perform arithmetic on local 'x' (a nil value)
Warning (Script): Unknown entity id 69959 in method 'worldToLocal'.
LUA call stack:
  =C:/Users/[username]/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/distance.lua (31) : worldToLocal
  =C:/Users/[username]/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/mode2.lua (131) : distanceToObject
  =C:/Users/[username]/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/drive.lua (299) : handle_mode2
  =C:/Users/[username]/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/base.lua (792) : drive
  dataS/scripts/vehicles/Vehicle.lua (2579) : update
  dataS/scripts/network/Server.lua (56) : update
  dataS/scripts/BaseMission.lua (1509) : update
  dataS/scripts/FSBaseMission.lua (2159) : update
  dataS/scripts/missions/mission00.lua (333) : update
  dataS/scripts/main.lua (1862) : update
```

I was actually just standing in the middle of a field when it began, so I can't say for-sure what caused this. I had 3 CP workers running:

- Seeding/Fert w/stock starting machine
- Cultivating w/stock starting machine

The third worker may be the culprit as it was the one doing something "different" at the time the error began. This one was on a run to dump wheat. It was in **combi mode** and I had just dispatched it while in a combine (using **send driver home** command)

I had just parked the combine and was checking finances, I **clicked save game** and it was at around this time the error began. It brought the FPS to just about a standstill; I checked the log and exited the application.

If there's more info/details you need, don't hesitate to ask.

And **thanks** again for all the work put into this excellent mod -- I've been a fan for years!

**Comment by Satissis** [comment]
just to be sure you are still able to reproduce this, then update to v.025 or newer (b59673bb1b72d86bbaf9b47b2a9107b3e4ed9a67)

**Comment by Nicksil** [comment]
I've been keeping up with the updates and have yet to run in to the same issue. It was kind of obscure to begin with, anyway.

Great work, and thanks again!
