### ISSUE TITLE
Great Plains Seeder will not turn on or lower

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1414]
Great Plains Seeder 3P1006NT. Started an empty seeder at beginning of a lane. Ran the load course fine, Went back to the lane before were i started it. Performed the turn but doesn't turn on or lower. Manually doing these things for it CP will then turn it off and raise it and start driving the course. Log at [Pastebin](http://pastebin.com/p0fLii0f). Only way to fix was to clear the course and load it again. Don't think its related to my other issue regarding this seeder otherwise I would just post it there (if it is sorry for the double post). Thanks for reading and fixing.

As side note: It doesn't stop on field edge for lowering after finishing a turn

**Comment by ThomasGaertner** [comment]
mybe it's related to #1416 we will wait for that fix and ask you to try again then....

**Comment by Satissis** [comment]
Please try again with v.019 and report back

**Comment by pops64** [comment]
As best as I could test it. Seems to work fine.  I will go and close this thanks
