### ISSUE TITLE
Potatos, Beets making heaps and some other stuff. Suggestions

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1415]
I know you guys are real busy fixing CP for release and thanks for taking the time to read this. So I was messing around in FS17(Didn't play 17 until CP beta came out can't play this game with out it). I was wondering if you were working on extending mode 7 new capabilities to mode 1-3 .(Mabye an option in the hud to unload on waitpoint when reversing instead of waiting),Eg. Making piles of potato and sugar beets for storage or other stuff for conveyor or bucket loader use.) Also if it would be possible to include conveyors into CP. As in tipper unloads a combine and then takes it to the conveyor and the conveyor unloads to a different tipper(or train and getting the CP to play with trains :) ) for transport to silo sort of like mode 3 but not using augur wagons. I know you guys are busy just putting it out there for future thought. And great work on the beta keep it up :D.

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
