### ISSUE TITLE
Key Binding

### ISSUE THREAD

**Issue by BenB78** [Courseplay/courseplay#1417]
I'm trying to change the HUD activation to the middle mouse button, and/or to a gamepad button combo, but changing the key binding in the options menu doesn't seem to affect anything. It still opens the HUD with the right mouse button and does not recognize the joystick buttons. If I exit to menu and go back to the options, the settings are still where I put them, but they don't seem to be recognized in game.

**Comment by SnoopBok** [comment]
Same issue here, using a Thrustmaster T16000m and Logitech G29.

**Comment by sootysax** [comment]
I am also having this issue:  with my Logitech G13 keypad.   I can assign different keys one for 'Left Ctrl' and the other for 'keypad 7' and when I press them both, it works.  

if I assign a combined assignment 'Left Ctrl + Delete' it will not  work

**Comment by cabmac** [comment]
had the same problem ti asign a macro the center mouse button on G700.. you have to save your macro NOT with combination ctrl+delete together but  ctrl, retard (in my case 0.8msec) and delete.... so the macro is "pressing"  ctrl first and then delete

**Comment by Satissis** [comment]
keybindings is nothing we really can do anything about then self, like how they are setup and so one.
The only thing we do with it is checking if you are pressing the key/s and doing stuff based on that.
So basic we using Giants own functions and keybindings and we cant change anything regarding that.

**Comment by sootysax** [comment]
i find it odd that other mods are using combined key commands without a problem, but CP is not.  I think the macro with the slight delay is a great idea though

**Comment by BenB78** [comment]
Satissis, thanks for the reply. I'm trying to understand. You say that the mod checks the keys and then does stuff, but it seems like it's stuck on the default button and is not checking correctly. I looked in the game's inputBinding.xml and everything is correct there. Even the default "Delete" key doesn't bring up the HUD. Only the right mouse button works, and it can't be changed to anything else. I'm not trying to run macros or scripts or anything, just switch the mouse button OR use a button on the gamepad - neither of those work at all.

I tested more after you replied, trying to make it work. None of the default keys work (such as start/stop driver). Do they work for other people? I can't map any functions from CP to any keys, mouse buttons, or gamepad buttons. Can anyone else? Only the right mouse button works. Nothing else is recognized, but all of them report correctly in settings and in the inputBinding.xml file. I tested two other mods, and they remapped the keys with no problem. Are you saying this is a bug with Giants, where all other key bindings work correctly in base game and mods, but this mod alone does not? If that's really the case, I'll bring it to them. 

All this worked in FS15. Unless I'm the only person having this problem, could you double check that there wasn't something that changed?

**Comment by RicolaRules** [comment]
It's left shift + delete to open the console. All key bindings are working for me. Including that.

**Comment by BenB78** [comment]
OK we're getting somewhere. Not shift, but left-control delete works - and if I hold left-control, all the keybindings work - including middle button and gamepad buttons.

SO- it looks like the issue is that the mod is adding left-control as a requirement for any key.

**Comment by RicolaRules** [comment]
It may be left control by default. I walked away from the game an hour ago, and my memory isn't what it used to be haha. Hope all is well for you now! Goodnight!

**Comment by cabmac** [comment]
Key Binding (creating macro) with Logitech profiler:
![sin titulo](https://cloud.githubusercontent.com/assets/16596142/20866617/4dd7b6dc-ba31-11e6-8be1-0ec977bc520b.png)

**Comment by Satissis** [comment]
You should be able to change the modifier in the key settings. It's named: "CoursePlays: Moddifier" and is default leftCtrl

**Comment by BenB78** [comment]
Yes! That worked. I can't remove the modifier, but I can remap it so that as long as I press that button, the others will work. Thanks much!

**Comment by Satissis** [comment]
Closing to clean up issues
