### ISSUE TITLE
FieldWork Mode with Pottinger Novcat Mowers

### ISSUE THREAD

**Issue by cfarrar1** [Courseplay/courseplay#1419]
When using the Pottinger Novcat Mowers attached to Fendt 700 on Fieldwork Mode with a generated course (Field 19 Goldcrest Valley) upon stating the course with start at First Waypoint selected and close to the first marker the mowers just folded and unfolded but did not start course.

I moved closer to the mark each time but did not work until I change to start at Nearest Waypoint and had the tractor positioned below the first waypoint.

No error on the log, once started it was working perfectly.

I'll link a video of the issue asap

**Comment by ThomasGaertner** [comment]
try with 5.00.00013 , should be fixed then....

**Comment by iceman4** [comment]
When working with the pottinger cutting machine 302ed, he makes no turn at the end of the field, he drives only in a circle. 
at 5.00.00014

**Comment by ThomasGaertner** [comment]
then it's #1416 I will close here....

**Comment by Satissis** [comment]
Please try again with v.019 or higher and report back
