### ISSUE TITLE
Not squarred field

### ISSUE THREAD

**Issue by knoxville73** [Courseplay/courseplay#1421]
If the field is not a squarre, the manuver does not work properly
![fsscreen_2016_12_02_19_56_52](https://cloud.githubusercontent.com/assets/23388102/20846494/31c58d9c-b8ca-11e6-945a-99ab6b74a1eb.png)

**Comment by Satissis** [comment]
is this on the default map or an mod map ?

**Comment by knoxville73** [comment]
This is on a modded map.
This morning, I have tried on the Sosnovka map, in the field 18.  The problem is the same.

**Comment by Satissis** [comment]
I was just curious about the map, since I haven't seen a an field with that steep angle before :)
I'll have an look into it.
Could you do me an favor and do the same again, with debug 12 and 14 active and take a screenshot like the one above ?

**Comment by knoxville73** [comment]
See below the print screen with debug 12 and 14.  The way seems to be correct, but the tractor starts with a reverse that is problematic.
![fsscreen_2016_12_03_15_06_57](https://cloud.githubusercontent.com/assets/23388102/20859846/d9c03452-b96a-11e6-8996-5005f7aab0bf.png)

**Comment by Satissis** [comment]
Hmm yeah, I'll have an look into that :)

**Comment by Satissis** [comment]
Try again with v.037 or later and report back.
I have been doing extensive testing and fixing + optimizing this turn type ;)

**Comment by knoxville73** [comment]
Hello,
I have tested this morning, and I think all is perfect !
One more time a good job.

I wish you an all your team a merry Christmas,

Manu

**Comment by rmn18** [comment]
thanks Satis and Marry Chrismas from Center North germany :-)
