### ISSUE TITLE
Shovel mode

### ISSUE THREAD

**Issue by Laciterado** [Courseplay/courseplay#1422]
Hi :)
Sometimes, after a bit of game playing, the wheel loader drives while shovel mode right or left into the silo walls. I tried to restart the vehicle, the course, but the only way to get the bug away, is to restart the game. 

I think it happens because right or left are more silage in other silos or maybe in the walls, but i dont know :/ 

My Version is 5.0.00013

**Comment by ThomasGaertner** [comment]
which equipment did you  use in which silo ?

**Comment by Laciterado** [comment]
![bildschirmfoto 2016-12-03 um 17 55 54](https://cloud.githubusercontent.com/assets/24322633/20860822/e0fd44fa-b981-11e6-9666-3646945a2bba.png)
![bildschirmfoto 2016-12-03 um 17 56 09](https://cloud.githubusercontent.com/assets/24322633/20860823/e0ff9c3c-b981-11e6-9782-a8ffdf4ebe1b.png)
![bildschirmfoto 2016-12-03 um 17 56 15](https://cloud.githubusercontent.com/assets/24322633/20860824/e104b6c2-b981-11e6-938b-c90be88d3a47.png)
I hope these pictures can help.

**Comment by ThomasGaertner** [comment]
one of the things on our TODO-list is to set the correct workWidth of the shovels . the script already considers the workWidth but it must be set manually at the moment. I've added a hardcoded value for this shovel. please try again with v.018 or higher and report ...

**Comment by Laciterado** [comment]
Thank you for your great work and time you spend in this support and mod! 
It is a bit better now, but one problem still exists. 

If the wheel loader unloads the course, like the course above and gets stuck and i restarted it, it focus sometimes the silos right or left of the course. I tried many start points, also from the first waypoint, but i think it focus the fullest silo and not the silo right in the course, the result, the wheel loader tries to drive through the wall and gets stuck again, then it is a time loop.

if you need, i can take more pictures. Thank you!

**Comment by sootysax** [comment]
So this is happening to me in .021

video:  https://dl.dropboxusercontent.com/u/36294746/2016-12-04_155527379.mp4

https://gist.github.com/sootysax/8af42b9058d7249135af0e1c17f7cb9a

**Comment by ThomasGaertner** [comment]
@sootysax : we recommend that the first wait point is in front of the Silo, because thats the point where the shovel will be lowered.... in you case the shovel has no chance to get the first parts.
if it tries to get the same part the second time and the fillLevel didn't change , the fillLevel will be automatic transfered into the shovel. But as I said, behind the first wait point

**Comment by sootysax** [comment]
I get what was happening..  I guess there are several different lanes the shovel takes, and there were two little pieces of uncovered silage in the corner which pulled the shovel to the right when entering the bunker.

 don't love the way GIANTS covers the bunker with tiny little pieces of blanket for any dropped spots of chaff..   that will hopefully get fixed.

Shovelling from the other side, I did experience the shovel getting caught up on the high walls of the bunker after filling the shovel though, trying to back out when it was taking the left or the right lane.

**Comment by Blackmankot** [comment]
@pops64   I suggest also close it for cleaning.

**Comment by pops64** [comment]
Closed #2909
