### ISSUE TITLE
Unload Course and Resume Bug

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1423]
After running a load or unload course in mode 4 or 6.(Straw unloader did this once did not caputre it though, this bug is in mode 4 with a seeder) When it gets back to the field if the waypoint for abortwork is to close to the field edge CP will start doing donuts. Video with debug 14 and 12 and all waypoints on. 35 secs for the abort work and drive to refill course. 1:30 for End of refill course resume work.

[Video](https://www.dropbox.com/s/93ad8nwtjwdnidh/Farming%20Simulator%2017%2012_2_2016%202_36_25%20PM.mp4?dl=0)

[Log](http://pastebin.com/D4QPJkS2)

**Comment by ThomasGaertner** [comment]
#1416

**Comment by pops64** [comment]
I read that issue, That sounds like the turn maneuver does donuts. This is when returning back to the field sets the way-point 2 from the edge. Reaches that point sets the next one like it is suppose but the next point is on the next lane. Performs the turn manuver thinking that the waypoint is on the same lane(which I guess it wasn't designed to handle). That is just my 2 cents not to argue. I have that saved stored seperately, will test when that bug gets fixed

**Comment by Satissis** [comment]
Please try again with v.019 or higher and report back

**Comment by pops64** [comment]
Yes. That commit fixed this issue as well. Thanks for looking into it
