### ISSUE TITLE
Wrapping grass bales

### ISSUE THREAD

**Issue by Sxpress** [Courseplay/courseplay#1424]
trying to wrap some bales on field 11 14 15 on goldcrest map with a Massey Ferguson MF 7700 and the ursus z-586 bale wraper. When the tractor comes to the end of the field and starts to turn it just turns in a cirkle all the time nothing more happens. if I then make it go the next line by moving the tractor there the same thing happens at the end of that line. Im using the 5.00.00013.dev version.

Regards and keep up the super work u do, love courseplay since farm sim 13 ... :)

**Comment by ThomasGaertner** [comment]
#1416

**Comment by Satissis** [comment]
Please try again with v.019 or higher and report back
