### ISSUE TITLE
Unload combine and off load to silo

### ISSUE THREAD

**Issue by edjon2000** [Courseplay/courseplay#1425]
Hi, I'm not sure how this works but I hope I am posting in the correct place,

I am running Courseplay 5.00.00013 and have come across an issue repeatedly.

If I set up a course to unload a combine and then when tipper is full unload at the farm silo everything seems to work fine for that game session, however, If I then quit the game and reload and then try to use the same course on the same field with the same default vehicles harvesting the same crop the horizontal offset seems to be screwed up, so, when the tipper goes up to the harvester to unload it the horizontal offset is altered so that the tractor/tipper combination almost collides with the area between the harvester and the end of the header instead of offsetting to the correct distance, so lets say that the offset for that particular harvester is 6.4m when the save is reloaded it seems to change to maybe half that offset.

I hope that makes sense.

This is using all default equipment  Tractor: Case Magnum CVX, Tipper: Joskin Drakkar 8600, Harvester Case Axial Flow 9230, Header: Case 3162 Draper 45FT 

This is the same on all fields

**Comment by Satissis** [comment]
yeah I don't think the auto calculate first time pipe offset is working correctly atm. Some thing we need to look into.

**Comment by edjon2000** [comment]
Thanks Satissis,
I hope my post made sense to you

**Comment by Satissis** [comment]
I'm going to postpone this for the moment, since it can be fixed by changing the offset again.
We will have an look into it when we have more time ;)

**Comment by edjon2000** [comment]
That's fine, Obviously you are very busy at the moment, I just wanted to make sure that you knew about it

**Comment by ThomasGaertner** [comment]
please test again with 01.0015 or higher and report...

**Comment by edjon2000** [comment]
Hi Thomas, my apologies for the late response, it took me a while to get some fields into a harvestable state, everything seems to be working well, the initial offset calculation was 9.1m but that was corrected to 11.0m almost immediately which is accurate for the caseih 9230 harvester with the 3162 draper 45ft header and these settings were retained over to the next game session, so I would say that it has completely fixed the issue, thank you, I will try this with some other harvesters and headers just to confirm but it definitely seems to be resolved.

Jon
