### ISSUE TITLE
Not compatible with 4Real Module Crop Destruction

### ISSUE THREAD

**Issue by Tuddley3** [Courseplay/courseplay#1426]
CP is not compatible with the 4Real Module Crop Destruction mod. I tried the CP beta and I love the new features and all, but the Driver cuts across the field to unload the harvester and damages my crops. Am I asking too much to have them both compatible?

**Comment by RicolaRules** [comment]
Did you turn on pathfinding?

**Comment by sootysax** [comment]
its very much all about how you setup the harvest..  its up to the user to plan out how the combine is going to harvest the field.. in relation to where the trailer will have access in and out of the field and how you set up your unloading route

**Comment by pops64** [comment]
#1402 . Corp Avoidance is turned off until the CP team gets time to implement it.
