### ISSUE TITLE
Cicular field Creation opption {headlands, spiral course] instead of the back and forth.

### ISSUE THREAD

**Issue by SirAlbertL** [Courseplay/courseplay#1427]
I am from the Pacific Northwest and we have LARGE, hilly, not square fields. I mean they are so hilly that they require Hilco Combines. 
My question, request is if it is possible to add a second type of Field path creation.
One that circles  in from the field edges.

Affectedly I would want to create my headlands that would turn with my field as the current headlands do.
But instead of creating a back and forth path from there, The ai would instead incorporate a circular turn that cleans up any missed ground on the headland pass.

To give you a idea of the ground we work and the maps I use....

Spring Work in Colfax www.josephsgrainery.com 
https://youtu.be/qUq_PA0Jqxg

Caterpiller Challenger 75E plowing on the Palouse
https://youtu.be/EQBYfKkRuOY?list=PLQVnvUaqbn3f4FK_siIbRQdK_VboWvu4e

Thank you all for your great work in creating the scripts for this mod.

**Comment by Satissis** [comment]
At the current time, then no but I have added it as an suggestion, so that we might have an talk about internally later on but don't expect it ;)

**Comment by genen** [comment]
Since the author of AutoCombine has indicated he will NOT be converting to 17, I think this should be added to a future release of CP. Using AutoCombine was crucial on non-US square fields in FS15. Without his mod, neither courseplay nor helpers would do an adequate job. His method relied on reading the field state just in front of the combine to sense the 'edge' of the fruit. which allowed combines to be sent spiraling clockwise (like RL for easy unloading on the go) and never hitting each other because their paths didn't cross. Would love for CP to pick up where he left off. In fact will volunteer my time (I'm more unreal 4 modder than anything) to help if there is interest in that feature.

**Comment by Satissis** [comment]
@genen There is just one problem in it.
The reason auto combine will not be ported over is that Giants have removed some functions that was crucial for auto combine to work the way it did, so basically we cant do it either. I believe the author also said that people would have to rely on cp further on.

**Comment by SirAlbertL** [comment]
Well then stop restricting the "head lands" to only 6 rounds. Make it go up to 150.... There, work already done.

**Comment by Satissis** [comment]
I know that there is a restriction on headlands. the simple answer to that is that our current headland calculator is not build to do so and would act weirdly when 2 headland get in contact with eachother. @fck54 was working on a new Headland generator which would allow you to do what you were asking for, but it's not finished and @fck54 told me that he don't know if he will ever get back to it again, because of family stuff (Which is more impotent for all of us).

**Comment by SirAlbertL** [comment]
You happen to know where I can get a free .LUC File editor?

**Comment by AgroWillem** [comment]
@SirAlbertL 
I wonder wat happens if you are circling closer and closer to the middlepoint? Isn't the combination going to jam when the circles are getting smaller and smaller?
Looks a programming difficulty to me for CP.

**Comment by sootysax** [comment]
I dunno...  I think CP does a great job with non-square fields

![2016-12-04_200024672](https://cloud.githubusercontent.com/assets/6591048/20870819/6a51b440-ba5c-11e6-8b91-58d4c5d25bfd.PNG)

**Comment by genen** [comment]
It's better than the helpers for sure... BUT, look at your screenshot.... there is so much wasted turning. If it was all headlands, or mostly anyway, you would have much less wasted time - and be more realistic. Plus if you play with crop destruction, doing mostly headlands clockwise means your pick up carts will never damage crops. If you go back and forth, you can only pick up fruit 50% of the time without damaging crops.
Either way some headlands is better than helpers, but autocombine was awesome for multiple combine unusual shape fields.

Which BTW, why did you not go the long way and instead did a direction with a bunch of turns?

**Comment by sootysax** [comment]
I did wind up using more headlands and changing direction..  

there are some issues with the super tight turns around the tip..   Satis, is there any possibility of incorporating turn maneuvers into the headland routes if the angle exceeds a certain threshold?

![2016-12-04_20331427](https://cloud.githubusercontent.com/assets/6591048/20871180/ef74d73e-ba60-11e6-8cc8-c6c56f949231.PNG)

**Comment by genen** [comment]
I guess it may be hard to replicate, but the beauty of autocombine was that it 'sensed' the crop just in front, so any shape could be followed, no matter how tight a turn. I would think that if CP tries to avoid crops to prevent crop destruction in the future, the groundwork for sensing crops will be implemented for that, and could be repurposed for a 'follow crop outline' method of driving, rather than creating the map like it does now. A side issue with this method is that on headlands corners are always missed - since the FS15 days - so if you do 5 headlands, you end up with 5 corners that are unplanted/unharvested... again minor, but annoying.

**Comment by sootysax** [comment]
you need to record better field edge routes and use them when you generate your harvest courses..  then your headland corner missage will be insignificant

and if you record the correct 'unload combine and offload routes' with the optimal beginning and end points, you will never have helpers drive over the crop

**Comment by genen** [comment]
Not looking for advice how to play :) just providing feedback on improvements.

**Comment by SirAlbertL** [comment]
After you clear three headland passes, you would use what we call a "looping turn". IE: no slow down, just lift header/tool or leave it lowers to clean up your first corners that have missed ground. an "loop" in the Opposite  direction of the field turn and require your track.

This is a plow making the turn as described above.
https://youtu.be/EQBYfKkRuOY

**Comment by Satissis** [comment]
@sootysax Turn maneuvers on Headland are planed. it will come in the new turn system phase 2

**Comment by AgroWillem** [comment]
Maybe a litte off-topic but how do you get those nice map with all the courselines in the upper left corner?

**Comment by MIZTigerForLife** [comment]
To turn on the map, click the eye symbol in the upper left corner of the HUD when you have a course open.

**Comment by SquareCloud506** [comment]
@AgroWillem In the course generating section, there's an 'eye' icon you can click to show/hide the generated route in a second window.

**Comment by Satissis** [comment]
@AgroWillem that's an build in function. In the courseplay hud, you will see an eye in the top left corner. click that one and it will show your current course. You should also be able to drag and drop the window where you want it

Lol 2 answered while I was writing this :P

**Comment by AgroWillem** [comment]
Wow great!

**Comment by genen** [comment]
This is a field from the default map on FS17 using standard Courseplay 5 beta and 5 headlands. You can see how much crop is left uncut. This was the problem that AutoCombiune addressed in FS15. Right now in odd shaped fields you have wastage using either Helpers or CP... 

![20161205192010_1](https://cloud.githubusercontent.com/assets/332206/20944086/bfe37972-bbc7-11e6-9500-d33f187e2dd1.jpg)

**Comment by genen** [comment]
Same field 23 on Goldcrest this time planting with 3 headlands - all setting default
![20161206235521_1](https://cloud.githubusercontent.com/assets/332206/20956475/bd8a5d24-bc0f-11e6-8dda-5801c48bdf7b.jpg)

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean

**Comment by genen** [comment]
Well apparently AutoCombine/Autotractor is back. The author has started redoing it for FS17 and the beta is out. So no need for CP to have that functionality now.

**Comment by SirAlbertL** [comment]
sootysax, 
I know this was done a long while ago, but this is why we always farm in sproles., the whole field......


I thank all of you that have worked so hard to build these scripts for our enoyment.
I know that not every issue can be worked out. 

I am just providing informating about the kind of farnibg in my neack of the world.
Some of the most dangerouse ground in the world.

Enjoy.

These Fields due to the steepness {Required auto-levaling combines to harvest] as well as the od shapes. are problems for both course play and AutoCombine, 
I know that the only way I could from a in game map in the exact ways we do in real, I would have to "record" my own field maps.... 
See we have to fallow not only the boundaries, but also the train.....

IE, you just CAN not squire off and climb these kills..... 

So nether CP or AC/At are realistic to us, auto C/T is the most realistic.

Images, maps not EVEN  Video's can give you a true understanding of the challenges with farming this terrain. 


Google Maps Location.
https://www.google.com/maps/dir/Palouse,+Washington/46.9096068,-117.0990825/@46.9094602,-117.1004128,1164m/data=!3m1!1e3!4m8!4m7!1m5!1m1!1s0x549f924066a2238f:0x3866777e065381c!2m2!1d-117.0757252!2d46.9101688!1m0

To Till a Field: Man and Machine in the Palouse
https://youtu.be/dyYbpW4Unn0

A wheat harvest not for the faint of heart 
https://youtu.be/CCcrIT6dhc8

Caterpiller Challenger 75E plowing on the Palouse 
https://youtu.be/EQBYfKkRuOY

Spring Work in Colfax www.josephsgrainery.com 
https://youtu.be/qUq_PA0Jqxg

Harvest on the Palouse near Rosalia- 2016- by Palouse-Rock Lake Conservation District
https://youtu.be/wsfV6yqy9iU



Image
https://youtu.be/CCcrIT6dhc8
https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Farming_on_the_Palouse.jpg/1280px-Farming_on_the_Palouse.jpg
https://www.bing.com/images/search?view=detailV2&ccid=KlnLZcEa&id=83E99CB3CF9DF26A0578705244EF5EBE2F1C1664&thid=OIP.KlnLZcEaBvDZ1H8EOnJCQwErDQ&q=Farming+The+Palouse+&simid=608036133668588243&selectedIndex=6&ajaxhist=0


Dropbox uploads.
Here is a rough edit of MIG_Map_MadeInGermany that I was working on for 2015.
https://www.dropbox.com/s/z6xpa3f39ebwyae/MIG_Map_MadeInGermany_Celle.zip?dl=0

auto-levaling combine
NewHollandAL59_4x4
https://www.dropbox.com/s/gna6m936y6a3q0g/NewHollandAL59_4x4.zip?dl=0

FS15_NewHollandTF78 for cutter
https://www.dropbox.com/s/v61m8ovlns8exdz/FS15_NewHollandTF78.zip?dl=0

**Comment by Krahazik** [comment]
I too would love to see a circular harvesting path option. One of the main reasons I used to use ExtendedAI was it had that feature whch meant I could always have my harvester's unloading pipe over harvested field and not over crop when it came time to unload.

Perhaps one way to figure out a circular path, is to use a similar method to how it already uses the field edge and tool width to figure out a back-and-forth path.

**Comment by pvajko** [comment]
If you select auto headland direction you can have 20 headlands at this moment, have you tried that? I can increase that, the algorithm will stop creating headlands once the field is covered anyway.
