### ISSUE TITLE
Donate

### ISSUE THREAD

**Issue by Karlshoj** [Courseplay/courseplay#1428]
Guess its time for a donation. Thanks a lot for your great work.
https://courseplay.github.io/courseplay/

**Comment by gec100** [comment]
You are absolutely right. 
Thx for a hard work guys 👍

**Comment by Zibbl** [comment]
Very good idea!

**Comment by Poppei** [comment]
Danke für die schöne Arbeit,spende ist unterwegs weiter so

**Comment by hsiverts** [comment]
I perfectly agree. If you like this mod please send a small donation to the developers! They put a lot of work into this, and if you are like me you will spend hundreds of hours enjoying their work. What is an hour of entertainment worth? I guess an euro at least. I have clocked 3217 hours on FS15 with Courseplay...a small donation is on the way :)
