### ISSUE TITLE
New feature suggestion for Unloading Courses

### ISSUE THREAD

**Issue by MIZTigerForLife** [Courseplay/courseplay#1429]
I would like to suggest an idea for a new feature for the unloading courses. This would obviously come after the beta, but I thought I would see what you guys thought about it, and whether it's even possible. Now that maintenance on vehicles increases as the hours increases, unloading courses seem inefficient in courseplay. The tractor sits waiting on defined levels in the combine, while the engine is running. This increases the running time, and uses fuel. I would like to see a feature that would allow us to have the tractor turn off the engine while waiting on it's next task. This would use significantly less fuel, and hopefully be able to not increase the running time. I know that currently in game the running time increases as long as you are in the vehicle, not just when the engine is running. Personally I don't like this, but we'll see if that even gets fixed in the game itself. Anyway, this is just an idea. Thanks for all you have done to get out the beta quickly after the release of the game. Courseplay makes FS an even better game than it already is.

**Comment by Satissis** [comment]
I do have thought of something like this my self.
We might look into it late on :)
I'll add it to our Pivotal tracker so we don't forget it ;)

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
