### ISSUE TITLE
Question about driver side selection.

### ISSUE THREAD

**Issue by Raints** [Courseplay/courseplay#1433]
Hey, is driver side selection for forage harvester disabled? Did work fine in FS15, now cant to change sides anymore.
![untitled](https://cloud.githubusercontent.com/assets/3618060/20859637/9e1f4f9e-b96c-11e6-8cf9-1b55342f6139.png)

**Comment by AgroWillem** [comment]
Good question, was looking for it myself yesterday and couldn't find it on a Krone Big X.
