### ISSUE TITLE
Combine crop destruction suggestion

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1434]
This turn seems like a no-win situation for the new turning system..  he is going to drive on the crop however the turning circle or field turning is set.

is there a way to at least keep the header lowered on turns like this so it harvests the crop instead of destroying it?

![2016-12-03_090157768](https://cloud.githubusercontent.com/assets/6591048/20859795/740ff1f2-b937-11e6-9560-5e0fa9adf958.PNG)

**Comment by Satissis** [comment]
That should be fixed when I do the fine tuning for the other issue of yours #1386.
