### ISSUE TITLE
Waypoint Addition Suggestion

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1436]
I propose adding an additional button to the HUD & Input binding that allows you to create waypoints without making them Crossing Points.

I find that it is needed when recording courses, especially when creating combined courses, that I be able to make more controlled turns in the farm, to hit the 'SET CROSSING POINT' in order to add additional waypoints to a turn...  i also use this when recording field edges, to plop many crossing points around the corners of a field to make the waypoints closer together get nice tight headlands when I generate courses.

However, I don't really want them to be crossing points, especially when creating certain farm courses in/out of the farm entrance/exit, since if there are extra crossing points, sometimes the whole course can be bypassed when combining courses.

It would be great to pop off additional waypoints without them being designated 'crossing points'

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
