### ISSUE TITLE
can't open the hud with certain tractora

### ISSUE THREAD

**Issue by Quintto** [Courseplay/courseplay#1437]
like it says in the title I can't open the hud while using the fendt 300 LSA pack  (http://www.farming-simulator.com/mod.php?lang=en&country=nl&mod_id=53286&title=fs2017) neither the right mouse button or alt+delete works, log is clean

**Comment by gec100** [comment]
mods are not going to be considered until stock works as it should.

**Comment by PatrickWende** [comment]
It might have something to do with the loading order of mods. You could try to change the name of courseplay to something like ZZZ_Courseplay. This way courseplay will be loaded last and added to all the mods that has been loaded before courseplay was loaded.

**Comment by Quintto** [comment]
thanks that fixed, overlooked the loading order thing 👍
