### ISSUE TITLE
Courseplay install/update script

### ISSUE THREAD

**Issue by elpatron68** [Courseplay/courseplay#1438]
For everyone who´s struggeling with installing/updating Courseplay from Github, I made a batch file which backups the current version and copies a fresh clone from the Github repository to your mod folder if there is a newer version. The script can also be used for a 1-step installation of Courseplay.

Update: The script is now capable of creating a zipped version (default) or a subdirectory.

https://github.com/elpatron68/cpupdate (Updated to v1.1)

**Comment by cythux** [comment]
nice

**Comment by Satissis** [comment]
@elpatron68 good work :) Thou I would also mention that it requires that you have git installed on your computer ;)

**Comment by anderzxb** [comment]
hard for a complete noob for me to understand :P

**Comment by elpatron68** [comment]
@anderzxb I have packaged an installable version which contains all needed files (Git and 7-Zip) as well as a README with some instructions. You can find it at https://github.com/elpatron68/cpupdate if you want to give it a try.

**Comment by PromGames** [comment]
I wil include this bat in the Modmanager pro courseplay editor for fs17. It is almost finished.

**Comment by anderzxb** [comment]
@elpatron68 seems to work thank you!

**Comment by tjb8907** [comment]
Very cool! nice way to keep up with the versions. I added a pause to the end of the script so the command window stays open, that way you can see if it was successful.

**Comment by hsiverts** [comment]
Not very cool. The people who are struggling to install courseplay are not the people you want to do beta testing.

**Comment by anderzxb** [comment]
problem with installing courseplay? no thats was not the problem it was the update script.. why so mad?

**Comment by tjb8907** [comment]
While I agree that beginners should not be beta testing, This is a very handy tool for everyone. I know very well how to install it and update it, but this makes it much quicker to stay up to date!

**Comment by gec100** [comment]
there is a small typo in the code where in line 40 autoclose is set to "NO", while at the end, script checks for "No", So window always closes when script is finished. changing the line 40 from "NO" to "No" fixes the problem and no need for additional pauses.

i've posted a issue on the original page to.

**Comment by shadow250** [comment]
it places it in the 2017 mod folder now though. to make it work in 2019: open the cpupdate_portable.bat in notepad and change lines:
:: Setting Mod directory
SETLOCAL
for /f "delims=" %%i in ('cscript %TEMP%\moddir.vbs "%UserDocs%\My Games\FarmingSimulator2017\gameSettings.xml" //Nologo') do set moddir=%%i

rem Setting Courseplay mod folder or file
if defined moddir (
set _dest=%moddir%\ZZZ_courseplay
) else (
set _dest=%UserDocs%\my games\FarmingSimulator2017\mods\ZZZ_courseplay

to :

:: Setting Mod directory
SETLOCAL
for /f "delims=" %%i in ('cscript %TEMP%\moddir.vbs "%UserDocs%\My Games\FarmingSimulator2019\gameSettings.xml" //Nologo') do set moddir=%%i

rem Setting Courseplay mod folder or file
if defined moddir (
set _dest=%moddir%\ZZZ_courseplay
) else (
set _dest=%UserDocs%\my games\FarmingSimulator2019\mods\ZZZ_courseplay
