### ISSUE TITLE
guide to use CP in 17 

### ISSUE THREAD

**Issue by Buchhave1** [Courseplay/courseplay#1443]
Hello 

Is there a guide how to use the new things in ls17 ? 

Buchhave 

And thanks for yours big work in 15 and 17

**Comment by Satissis** [comment]
The only thing we have right now is our Manual.
It's not fully updated yet with all the new stuff, but that should be dealt with later.
here is the link: http://courseplay.github.io/courseplay/en/index.html

**Comment by Buchhave1** [comment]
Thanks :-)

**Comment by Buchhave1** [comment]
you got a mail ;-)

**Comment by johnetegtmeier** [comment]
Hi just wanted to say I LOVE this mod. and I wanted to let you know I experienced a problem... I tested it out in a test game I have going and when I started my regular game the course I saved in the test game showed up in my regular game. please don't take me wrong, I'm NOT complaining, I just wanted to let you know Keep up the Awesome work .... a true fan, John
