### ISSUE TITLE
Courseplay doesn't show up in mods list

### ISSUE THREAD

**Issue by Tompompier** [Courseplay/courseplay#1448]
Courseplay doesn't show up in ingame mods list. 
System: Mac OS

**Comment by AgroWillem** [comment]
http://courseplay.github.io/courseplay/en/installation/index.html

**Comment by RicolaRules** [comment]
Needs to be named ZZZ_Courseplay.zip also make sure it's not a zip inside a zip.

**Comment by Yoshiwhore** [comment]
"Load mod: ZZZ_Courseplay
Error: Unsupported mod description version in mod ZZZ_Courseplay"

[log.txt](https://github.com/Courseplay/courseplay/files/629895/log.txt)

**Comment by Rasip** [comment]
I followed the instructions. Courseplay doesn't show up ingame. No error message. I tried ZZZ_Courseplay.zip and ZZZ_courseplay.zip. I even tried adding "FarmingSimulator2015\mods" and putting it there since that is what the directions say for win7.

Is 5.00.00022 broken?

**Comment by rmn18** [comment]
no ,chance in the modesc.xml line 2  descVersion to 33 ,not 34

**Comment by sootysax** [comment]
update your game to 1.3.1.0

**Comment by Tompompier** [comment]
Same log as Yoshiwhore for me, and game is up to date.

**Comment by rmn18** [comment]
In the modesc.xml is certainly descVersion = "34" change times to 33, with me it worked

**Comment by Tompompier** [comment]
Doesn't work for me, rmn18

**Comment by Poppei** [comment]
try this for monet it work fine.  https://github.com/elpatron68/cpupdate/releases

**Comment by sootysax** [comment]
yoshi is using 1.2.0 - current FS17 is 1.3.1.0

**Comment by Tompompier** [comment]
That cpupdate exe doesn't work on Mac OS... Guess I'll need to be patient until a final version will be there.

**Comment by elpatron68** [comment]
Sorry, there won´t be a version for MacOS because the script is based on 
Windows functions.


Am 05.12.2016 um 16:25 schrieb Tompompier:

**Comment by Satissis** [comment]
@Tompompier or use this guilde to get it from here ;)
http://courseplay.github.io/courseplay/en/installation/index.html

**Comment by Tompompier** [comment]
It took a few attempts: but all working fine now. Must've lost track somewhere :-) Thanks for assistance!

**Comment by Yoshiwhore** [comment]
The update fixes the error: D Thanks for the help / support    :D
