### ISSUE TITLE
For the Future, The Dolly EA

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1449]
I know your busy fixing default equipment. And has you can't get this bug with out a mod. Just putting it out there for the future fix when you get more time. If you have any tool(ex Fliegl Stf 25000 VC, now a mod, it or something like it was default in FS15) that requires the use of the fliegl dolly EA in mode 4 or 6. CP breaks when you hit drive. The log spits out 

C:/Users/Ryan/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/toolManager.lua:491: attempt to perform arithmetic on a nil value

As always thanks for reading and doing great work

**Comment by Satissis** [comment]
Hmm that sounds weird, but as you said, it will wait until the mod phase :)

**Comment by pops64** [comment]
Moved to the tracker

**Comment by pops64** [comment]
Closing this out has I believe I fixed this int he Big Bud DLC versions
