### ISSUE TITLE
Drive off % in mode 2.

### ISSUE THREAD

**Issue by Raints** [Courseplay/courseplay#1450]
![untitled](https://cloud.githubusercontent.com/assets/3618060/20878193/27f1de0c-bad6-11e6-9e05-ac74184cd17e.png)
If i remember correctly in fs13 we had option for driver in mode 2 in the end of the line it will drive off at certain % to unload and not making turn maneuver to fill it to 100%. Seems its not working in fs 17. I did check fs15, its not working either.

Its nothing game breaking, but was a nice addon.

Edit. Just realised I didnt mention I was talking about forage harvester. For combine it did worked perfectly in FS15

**Comment by Asghan86** [comment]
Thats wrong.
For me this worked perfect in FS15.

**Comment by ThomasGaertner** [comment]
just checked, the code. its not included at the moment . I will take it as suggestion...

**Comment by ThomasGaertner** [comment]
we decided, not to include it because it could cause difficulties when the tractor is outside the fiel and should aim to the unloading course
