### ISSUE TITLE
Holmer Test

### ISSUE THREAD

**Issue by cronuss64** [Courseplay/courseplay#1453]
Just thought i would post results of last test. Started mission on f26 Goldcerst Valley using Holmer beet harvester. Started NE corner heading W, 3 headlands. Mission was 138 mins, finished with 56 mins left. Everything was going great until mission ended when game broke. I have uploaded log file but had to crop it because the last error was duplicated 49 thousand times.
[log.txt](https://github.com/Courseplay/courseplay/files/631284/log.txt)

**Comment by SquareCloud506** [comment]
In FS15 using the equipment rental mod, the game would ‘ break’ if a rented tractor vanished while CP was using it. I imagine the same thing would happen if using CP on a field mission in FS17 as the equipment will vanish when the mission is complete.

**Comment by ThomasGaertner** [comment]
yep, possible, try again with v .023 or higher ...

**Comment by cronuss64** [comment]
Just downloaded .024 used different harvester on f30, Axial Flow 9230 with 12.2m corn header and it worked perfect. Don't know if it was issue with Beet Harvester or not though. When Beets are ready i will try again and let you know.

**Comment by Zeraphine** [comment]
I had the same problem with both Holmer (sugarbeet and potatoe), haven´t yet tried the pulled harvesters for these. All is fine with the Combines for wheat.

**Comment by cronuss64** [comment]
Update Test... Used same equipment but on different field f27, wanted to see how it acted on non square fields. This time it did not break game, but found issue with turning. Harvester would go outside field before turning, even after 3 headlands. CP set turning circle to 14m, but when i changed to 7m it worked perfect.
