### ISSUE TITLE
Terra Variant augur tanks

### ISSUE THREAD

**Issue by 37cee** [Courseplay/courseplay#1454]
While this might be my fault i have troubles using the augur tanks of the Terra variant. When trying to use the augur tanks, both grain and beet, courseplay notifies that the wrong trailer is used  (so the course wont work). I know there was a similar issue with FS15 when the DLC was release. I'm aware that this is technically a mod, but i wanted to point it out non the less. Sorry if this has been mentionened before, i havent seen any Issue about this.

In addition using augur wagons seems to be a bit more complex than it was before, at least with trailers that have adjustable unloading systems (Bergmann GTW 430 especially)

**Comment by ThomasGaertner** [comment]
atm we are still in the no mods phase, the dlc in on our list and we wil consider it when we are ready for it .... I will close here to kee the issues as cleen as possible.
