### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KT60** [Courseplay/courseplay#1455]
Just want to say it seems to working for the most part but when I try to drive the course the game freezes and when I look in my fs17 log this is what it shows...C:/Users/keith/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/mode2.lua:231: attempt to index local 'combine' (a nil value)
Error: Running LUA method 'update'.

This is with one CP driver

**Comment by ThomasGaertner** [comment]
are you sure, you have the latest version? should have been fixed in v.017 ...

**Comment by KT60** [comment]
This is the version I downloaded 5.00.00016

**Comment by ThomasGaertner** [comment]
So please update and try again...

**Comment by SquareCloud506** [comment]
@KT60 at this moment, the current version is 5.00.00024

**Comment by KT60** [comment]
Ok I downoaded the newest one and now it says in the log...Error: Unsupported mod description version in mod. Do I need to rename the courseplay-master zip I created?

**Comment by Satissis** [comment]
no need to rename, but you will need to update your FS17 game to patch 1.3.1 ;)

**Comment by KT60** [comment]
I have the update. What was strange is I had to change the <modDesc descVersion to 31 in order for it to work. Its working now

**Comment by Satissis** [comment]
no if you had to change the descVersion to 31, then you have not updated your game. Check your log, it shows in the start what version of the game you are running. the latest v1.3.1 is descVersion 34

**Comment by SquareCloud506** [comment]
Update to current version of FS17 here.
https://www.farming-simulator.com/updates.php?lang=en&country=us

**Comment by KT60** [comment]
Thank you for your help. I think I got it

**Comment by Satissis** [comment]
I'm guessing that this is fine now. Closing
