### ISSUE TITLE
Integration of "Follow Me" & Field circumnavigation to not drive across crop - Suggestion

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1456]
In asmuch as the hired helper is used in conjunction with Combine Self-Unload mode, where you set the hired helper to work, then start the unload course:

Would it be possible to integrate Follow Me on a unload trailer which would follow the harvester around the headlanes (offset and under the unload pipe), then when it was full,  breaking off of follow me to drive the unload route, then returning to the field to trigger Follow Me again?

Another possiblility would be to have the tractor follow the combine directly behind and wait for the combine to reach desired fill level, then break away from Follow Me and run the CP course to unload the harvester, then stop, wait for the combine to drive away and then trigger follow me again?

I understand that it would probably cause the driver to drive across the crops on the way back to the start point of the unload route...  but I had an idea that you could perhaps implement first driving to the nearest point of the edge of the field and using the field edge to circumnavigate the field until the start of the unload course is crossed, then run the unload route..

**Comment by SquareCloud506** [comment]
Set the start level of the tipper to 0% and pathfinding turned on, and the tipper should stay under the pipe when it's not in the crops. Just a thought.

**Comment by ThomasGaertner** [comment]
#1402
