### ISSUE TITLE
Tractor not unloading into Grain Silo (Old Streams Map)

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1457]
This trigger, which was previously working, is no longer dumping into this grain silo..  
Old Streams Map v 1.2.0.1

https://gist.github.com/sootysax/45c16dbfc3f726399f9dbf26b28e7fdd

video: https://dl.dropboxusercontent.com/u/36294746/2016-12-05_142830286.mp4

**Comment by ThomasGaertner** [comment]
can U give me the savegame please

**Comment by sootysax** [comment]
https://dl.dropboxusercontent.com/u/36294746/%231457.zip

**Comment by sootysax** [comment]
I resolved this issue..  the issue was approaching the trigger straighton ..  hitting it from a 45 degree angle activates the tip trigger (as the shape of the zone markers suggest).  Live and Learn

**Comment by ThomasGaertner** [comment]
yea I tested it, its been a question of millieters....

**Comment by Satissis** [comment]
hmm an idea would be to continue reversing back until the tip reference point is in the center of the tip trigger, which should fix this :)

**Comment by pops64** [comment]
Can confirm this as well on Gold Crest Valley and I have the last way point in the middle of the barn
![farming simulator 17 12_18_2016 11_04_54 pm](https://cloud.githubusercontent.com/assets/10678220/21300929/8caf76f6-c576-11e6-9bce-061dcf45c6c1.png)

**Comment by pops64** [comment]
I can confirm this, I think it is a bug cause in the my log and sootysax's log it has.  This happend to me on Goldcrest valley at the barn
```
[dbg2 lp5543] 8340 (#1): distanceToTrigger=0.044292449951172, bestTipReferencePoint=1 -> trailerInTipRange=true
[dbg2 lp5543] 8340 (#1): goForTipping = true [trigger accepts fruit (30)]
[dbg2 lp5544] 8340 (#1): distanceToTrigger=0, bestTipReferencePoint=1 -> trailerInTipRange=true
[dbg2 lp5544] 8340 (#1): goForTipping = true [trigger accepts fruit (30)]
[dbg2 lp5544] 8340 (#1): toggleTipState: 1  /unloadingTipper= EUROBOSS 330 T
[dbg2 lp5545] 8340 (#1): distanceToTrigger=0, bestTipReferencePoint=1 -> trailerInTipRange=true
```
And if you stop the CP where it stops to unload you can indeed unload it your self with out moving,  I think it is toggling the tip state but for some reason the forage wagon doesn't respond to the command, maybe cause its not in far enough but I don't think so cause you can do it manually from the same spot as CP tries to do it.

**Comment by pops64** [comment]
That shouldn't fix the problem tho. Cause in the debug statement. `[dbg2 lp5544] 8340 (#1): toggleTipState: 1  /unloadingTipper= EUROBOSS 330 T` is printed and the code for that is on line 959 which is the if statement that you fixed. The problem isn't there but in the code that handles the tool commands. Have to find the command that actually tips the tipper line 958 is probably the variable for it.

**Comment by ThomasGaertner** [comment]
please test with 01.0018 or higher . Should be working now,  It was a question of millimeters: distance to trigger was 0 , trailerInTipRange was true  but the trailer was not in the trigger...

**Comment by pops64** [comment]
Nope no go. The problem is `tipper:toggleTipState(ctt, bestTipReferencePoint);`. I think it doesn't recognize it is in the tip trigger even though it is. And like you said its a question of millimeters. Tested with v01.019

**Comment by ThomasGaertner** [comment]
can you give me you course or savegame ? I tested this version 20 times and worked fine.  thanks

**Comment by pops64** [comment]
[Savegame](https://www.dropbox.com/sh/6hlog7n5cg60chm/AADQjTYTTV2khvGPcpCq3doga?dl=0)

[Courses](https://www.dropbox.com/sh/iy16diqp5rbgg42/AACo9jr0aKyEL6r_YunZGECYa?dl=0) The one I am using is under F19 folder. F19 Straw 7.6m. 

Thanks for looking

**Comment by DavidFONTAINE** [comment]
An other attempt.  #1615 
Perform toggleTipState before to stop driving, and to be sure the trailer is in the trigger, only stop driving if trailer.TIPSTATE_OPENING or Trailer.TIPSTATE_OPEN.
works in farm trigger and bale trigger.
@ThomasGaertner  Your previous solution worked only 1 time on 10.

**Comment by ThomasGaertner** [comment]
ok next version is 0020: try and report
@DavidFONTAINE : i followed your approach but not your code :-) 
 thanks for the  support

**Comment by DavidFONTAINE** [comment]
Version 0020 works fine.
Thanks

**Comment by pops64** [comment]
3/3 works. thanks for the update.

**Comment by ThomasGaertner** [comment]
@sootysax : what about you ?

**Comment by ThomasGaertner** [comment]
closed to keep issues clean
