### ISSUE TITLE
Traffic detection

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1458]
I think the traffic detection is a little too sensitive..   I can screenshot many examples, but this one sums it up.

https://gist.github.com/sootysax/5ea58395e09f4ec287df436e8b573d3e

![2016-12-06_093652841](https://cloud.githubusercontent.com/assets/6591048/20929345/b4688ee6-bb97-11e6-805f-b25ef569e3f7.PNG)

**Comment by Vanquish081** [comment]
Yes, when job tractor with combine, the tractor stop for traffic detection when aproximate to combine.

**Comment by Satissis** [comment]
@sootysax an image where you have the F5 debug turned on would be nice, since it shows how the traffic collision triggers are places

**Comment by sootysax** [comment]
![2016-12-06_16165301](https://cloud.githubusercontent.com/assets/6591048/20943935/8d265e3e-bbcf-11e6-99f7-2e9068f50b58.PNG)
![2016-12-06_161656388](https://cloud.githubusercontent.com/assets/6591048/20943936/8e725a7c-bbcf-11e6-9bd1-f776f9b515a7.PNG)
![2016-12-06_151247666](https://cloud.githubusercontent.com/assets/6591048/20943969/a92e9c40-bbcf-11e6-8dc0-29e2e0f81cb3.PNG)
![2016-12-06_151346335](https://cloud.githubusercontent.com/assets/6591048/20943973/aa7cfda8-bbcf-11e6-871b-11709101cf6f.PNG)

**Comment by Vanquish081** [comment]
![Example](http://i.imgur.com/NEVrCuz.jpg)

**Comment by Josephbones** [comment]
I get the same problem with my combine ( a case 7130 i think, with 9.2m header)... weird thing.. it never happen with the Torum 760

**Comment by pops64** [comment]
Picture with F5 on and debug channel 3

**Comment by Josephbones** [comment]
what do i need to do to activate F5.. I know about debug channel 3, it activate red lines in front of the tractor, but F5 do nothing...

**Comment by pops64** [comment]
Do you have the picture with Just channel 3 active plus log

**Comment by Josephbones** [comment]
I will tonight when i come back from work, it happen often taht debug channel 3 simply show nothing, but slow down the fps when i approache something.. but i can;t see any lines, box or red line.. only when i go straight with tractor...

I'll get logs screenshots tonight

**Comment by Blackmankot** [comment]
@pops64 Can this issue be closed? To cleanse the topic.

**Comment by pops64** [comment]
Closing this out for inactivity
