### ISSUE TITLE
cp and trains?

### ISSUE THREAD

**Issue by fudoido** [Courseplay/courseplay#1459]
Is a feature to make courseplay work with trains planned after beta?
since trains dont have issues to swerve and traffic jams or obstacles, it would be nice to have a train mode to load/unload them, or just run them automatically to give a bit more animation to the maps, watching them pass by the crossings.
maybe add a sort of waiting point to make them slow down before reaching a trigger, so they can brake on time at the trigger and/or end of course.
overload function would be nice also, in case we wish to place conveyors in other section of the tracks without regular triggers.
whats is peoples though on this?

**Comment by NateDawgCC** [comment]
I was wondering the same thing. I'd like to just be able to record a loop and have the trains just drive around the map

**Comment by Satissis** [comment]
I have that on an todo list in my head already ;)

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
