### ISSUE TITLE
CoursePlay and Komatsu = </3

### ISSUE THREAD

**Issue by MrPinkDrifter** [Courseplay/courseplay#1460]
Seems that I can't buy the Komatsu EX50 When I have CoursePlay enable in my savegame.

Get this from the log (When I have bought the forklift before restarting the game and enable CP):
C:/Users/Marcus/Documents/My Games/FarmingSimulator2017/mods/Komatsu_EX_50_17/Komatsu.i3d (69.16) ms
Error: Running LUA method 'loadSharedI3DFileFinished'.
[builtin:deg]:0: attempt to perform arithmetic on a nil value

And this from the log (When I try to buy the forklift wile already having CP enable):
C:/Users/Marcus/Documents/My Games/FarmingSimulator2017/mods/Komatsu_EX_50_17/Komatsu.i3d (68.96) ms
Error: Running LUA method 'update'.
[builtin:deg]:0: attempt to perform arithmetic on a nil value

on both occasions the game just holds in loading. First example I need to alt+tab and shut it down, and on second it just loads in the "fetching tab"

Link to the Komatsu:
https://www.modhoster.com/mods/komatsu-ex-50--5#description

I thought the issue might be in CP becouse i could not find any .Lua
 files in the Komatsu.

CP ver:5.00.00021

**Comment by ThomasGaertner** [comment]
no mods at the moment.....

**Comment by MrPinkDrifter** [comment]
Oh yea. Forgot.
Well, its here until its time. 
I'll comment if you guys manage  to fix it without knowing. (Y)

**Comment by Anonymous-any** [comment]
Hi there, maybe can we have information's about how parts is linked to the vehicles or other information's please? cause for sure we have some mods that won't interact with the code issue and some yes :/ unbuyable or unloadable at start.
Best regards

**Comment by Anonymous-any** [comment]
I think it's good for this too?
https://github.com/Courseplay/courseplay/issues/1739

**Comment by ThomasGaertner** [comment]
try with 0067 or higher and report...

**Comment by Anonymous-any** [comment]
My Games/FarmingSimulator2017/mods/Komatsu_EX_50_17/Komatsu.i3d (86.29) ms
 It's ok for this one too can be buy.
Cause he not ask something I tried for you.
Regards
