### ISSUE TITLE
Plough Suggestion

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1461]
Know you busy fixing CP but for later on, would it be possible if the back marker on the plough be the turn trigger on lane finish. And front marker for plough on lane start. To get rid of the triangle that develops, though this would be bad on field creation. Maybe an option in the hud for this behavior or CP auto detects if field creation is on or off. Thanks, and as always keep up the great work

**Comment by bigdigger** [comment]
this is would make the ploughing much better.
on last run with plough not to flip her over

**Comment by Satissis** [comment]
yeah, well if it was going to be implemented, it would be as an option, for the pure reason that we don't want to go further out of the field that needed, in case there is obstacles outside. We are already moving to far out of the field in my opinions, but that's what headlands are for ;)

Also this is postponed until after the release.

**Comment by TheRealRolandDeschain** [comment]
Hi, I wanted to add a suggestion to the suggestion ;)

Another way to avoid the triangles would be to make an option to drive into the headland lanes while driving back and forth. AFAIK this is also how it's done in real life.

**Comment by pops64** [comment]
Also, when the plough first starts in stead of defaulting to rotating left. Could you pick whether the plough is right or left based on cardinal direction. So it avoids this
![farming simulator 17 12_17_2016 12_49_42 pm](https://cloud.githubusercontent.com/assets/10678220/21288675/516dae0c-c457-11e6-8cd3-2fcfe13d0649.png)

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
