### ISSUE TITLE
Turning radius

### ISSUE THREAD

**Issue by genen** [Courseplay/courseplay#1462]
I did some tests having forage harvester empty into CP controled holmer 600 as well as a truck and found that the turning radius of the CP controled machines was very large when the combine turned around for the next row. They seem to do a figure 8 turn that took it a good 40-60m away from the combine. This of course resulting in hitting trees or trying to climb steep hills during the turnaround.

Also in general the pick up vehicles seem to do a lot of figure 8 maneuvering when they get to the field to get behind the combine - much more so than I recall in FS 15... Reducing the turn radius manually did not reduce their turns.

**Comment by Satissis** [comment]
I don't think this have anything to do with the turn radius.
I think it's an problem in the turn it self, and hopefully should be fixed once I'm starting to fine tune the turns and finding bug in them

**Comment by genen** [comment]
Did more testing... it seems to be over 50m out that it decides to make a turn when combine changes directions. Ended up in water several times.

Also seems to pick the wrong side to go next to combine (damaging crops) about 50% of the time.
Should I submit that as a separate bug?

**Comment by Satissis** [comment]
yes please :)

**Comment by Satissis** [comment]
Could you take en picture of this with debug 12 and 14 active ? I wanna see what it's doing, since the lines I have added indicate exactly what it's trying to do :)

**Comment by genen** [comment]
Ok will try the latest download of CP source and try this today.

**Comment by Satissis** [comment]
Try again with v.037 or later and see if this fixes your problem.

**Comment by genen** [comment]
Will try... been busy with RL :)

Happy Christmas!

**Comment by Satissis** [comment]
Any update on this ? Just so I know if I have to look further into it :P

**Comment by genen** [comment]
Tried a test today for a batch of past bugs (wrong side on chaff harvester, etc) and all are fixed. This one I'm not sure about. While I did not see a figure 8 in a tractor with a trailer, I did have the chaff trailer make fairly wide turns that destroyed crops in the field next to the field I was harvesting. I should have taken a picture - didn't. It appeared that the pick up tractor was making turns around 2-3 lengths of itself away from the combine each time.. If there was not a field there it may be ok, but this felt like it was a bit overly excessive turns. Not sure if I turned down the turn radius if it would be reduced.

Another question from that test - the tractor seemed to be ahead and to the right of the combine at 'default'. Where do you get the default position from? It looked like the 'best' position for the tractor and trailer was actually 7M back from the default. Just wondering how the default position is calculated.

**Comment by genen** [comment]
Maybe... did a test today and noticed that while there were no figure 8s the movement of the tractor and trailer at the end of the field were fairly large. Maybe 2-3 times the length of tractor plus trailer. Forgot to take a photo - sorry. What would you say is 'normal' for how far back from the combine the tractor/trailer should go making a circle at end of field?

**Comment by Satissis** [comment]
hmm for me to test this out, I would like to have an compleat setup list of all the cp controlled vehicles, so I know in what combination they are made, just so I can test it my self.
ex: (this vehicle connected to this trailer in this mode, with default setting.)

Also, I said before that I thought it's related to the new turn stuff, but that is me not reading your post correctly :P It's the turn radius calculation that not working correctly on some trailers, which I have to figure out what's causing this.

**Comment by genen** [comment]
I'll try to make some time today to do this and take pictures.

**Comment by genen** [comment]
Ok have a quick video of the wide turns (and wrong side driving) - was night in game so had to crank up brightness a bit but you get the idea of how it's driving https://www.youtube.com/watch?v=UCj41NhCMvM

**Comment by Satissis** [comment]
okay so first off. I thought it was the chopper that had the turn issue, but it's the truck or tractor and trailer that's the issue.
Secondly, that truck you are using is an mod and we are not in the mod face yet.

When that's said, this is actually an issue that Thomas need to look at, since he knows how the turns are done for that and might be able to tell what the reason is.

I still do have an finger in it, since it might be related to the turn radius calculation as well.
I'll have @ThomasGaertner take an look at this as well :)

**Comment by genen** [comment]
I can record a bit with no mods. It acts the same way with a tractor pulling a tipper last I did it with built in stuff.

**Comment by genen** [comment]
This was done with this mornings version. So not sure if that was before his fix or not.

**Comment by genen** [comment]
New video... all stock equipment, same result, overly large turns, and then wrong side 50% of time.

https://youtu.be/q9vLIvtZ79I

just now uploading also https://youtu.be/EZiT86YVd1k with more examples

**Comment by ThomasGaertner** [comment]
@genen : wathts the status here ? would you plesa test again with .0056 or higher and report ? the wrong side issue should be fixed .and maybe also the turns ...

**Comment by genen** [comment]
Not tried since last message. Will download update tomorrow.

**Comment by pops64** [comment]
Closed due to inactivity. Assumed fixed

**Comment by genen** [comment]
Yup looks fixed... honestly not seeing any bugs anymore.
