### ISSUE TITLE
Issue with mode 2

### ISSUE THREAD

**Issue by ElThreep** [Courseplay/courseplay#1463]
Hi,

I'm French, so excuse my English.

When I start the game, load my save, and load a CP, my offset is automatically set to 9,3m.
![farming1](https://cloud.githubusercontent.com/assets/24420922/20946528/61d65c66-bc0b-11e6-85fb-6ce8b0550de9.png)

Then, I switch my "Start at %" to 0 to force my tractor to go to the harvester, and the offset automatically switch to 6,3m. I'm stuck behind the harvester, and need to change it manualy.
I have the same problem if I let the "Start at %" the same (70% or 80%), without changing it.

![farming3](https://cloud.githubusercontent.com/assets/24420922/20946877/eb6e0a04-bc0c-11e6-8d98-319aaaa049c8.png)

Finally, if my tractor reach my harvester, I have an other problem : 
https://vimeo.com/194577290
On this video, it's ok, but sometime, i'm stuck on trees, and constantly need to stop/reload my CP.

**Comment by Satissis** [comment]
First problem is related to this issue: #1425
The second problem, is the turn radius calculated wrong for the trailers, which is on our todo list ;)

**Comment by ThomasGaertner** [comment]
please test again with 01.0015 or higher and report...

**Comment by ElThreep** [comment]
Ok for me, issue is fixed. Thanks !
