### ISSUE TITLE
Four Wheel Drive doesn't work for new FS17 bunker mechanic

### ISSUE THREAD

**Issue by genen** [Courseplay/courseplay#1464]
The method of only temporarily turning on 4wheel hub locks if not moving does not work well with the changed bunkers in FS17. Bunkers don't smooth themselves out, so if you dump a large pile in one place, it stays there unless you manually move it.

Right now when going through a bunker and dumping chaff, the tractor often gets stuck without 4wheel locks. It keeps dumping chaff while stuck until it gets locks turned on and starts going again. Next time it comes back it gets stuck in the pile it created the last pass, and this time can not get out of it at all.

Purposed solution, change function of 'always use 4WD' in CP now, to not only permanently turn on 4WD but also both locks. Otherwise it is useless for dumping chaff in bunkers more than 10% full.

**Comment by Satissis** [comment]
I'm guessing you are using Drive control for the 4WD. As we have mentioned a couple of times, then mod support is on hold for now until all vanilla stuff is working

**Comment by SquareCloud506** [comment]
Plus, 4WD function of Drive Control mod can be disabled, allowing the game to default to the all wheel drive that every vehicle has when not changed by the Drive Control mod

**Comment by genen** [comment]
I'll disable drive control and test again, but from my experience without drive control the built in 4wd does not lock difs, and still let's wheels spin if one is off the ground or stuck. So drive control improves traction when loaded.  But I'll test and post results without it.

**Comment by ThomasGaertner** [comment]
@genen : is it still an issue for you ? did you try the new mode, therefor you dont need to go throught a half full silo...

**Comment by genen** [comment]
I have had drive control turned off for now. I think this issue is ok
