### ISSUE TITLE
Deactivate mod 'Crop destruction' if drive Courseplay

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Courseplay/courseplay#1465]
Deactivate mod 'Crop destruction' if drive Courseplay.

**Comment by Satissis** [comment]
mod support are on hold until all vanilla stuff are working.

**Comment by mereman** [comment]
Or follow Disco's Monday Modding video on how to turn off crop destruction for hired hands. It also works for CP. https://www.youtube.com/watch?v=e-YH-LC-2yo&t=127s

**Comment by Gonimy-Vetrom** [comment]
mereman, Thank you so much, friend.
Hired workers have a lot of harvest destroyed. I thought I did not solve this problem.
