### ISSUE TITLE
_grimmeAL8022_QuantumAutoload und Ual  autoloadballentransporter

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#1466]
PRoblem ist erledigt! Eine Frage noch Wird es die unterstützung für den autoload für UAL Ballenwagen auch wieder geben?

LG

**Comment by Satissis** [comment]
mod support are on hold until all vanilla stuff are working.

**Comment by Paul2510** [comment]
Wird es die unterstützung für den autoload für UAL Ballenwagen auch wieder geben?

LG
