### ISSUE TITLE
Wrong side of chaff harvester

### ISSUE THREAD

**Issue by genen** [Courseplay/courseplay#1467]
Driver of cart seems to pick the wrong side to go next to combine (damaging crops) about 50% of the time.
It seems to be random which side of the combine it will drive next to when doing chaff.

**Comment by ThomasGaertner** [comment]
please post the log with debug channel 4 active...

**Comment by genen** [comment]
Will do. not done chaff for couple days.

**Comment by genen** [comment]
I think this is working ok joe

**Comment by genen** [comment]
Still getting this 50% of time https://www.youtube.com/watch?v=q9vLIvtZ79I

**Comment by Raints** [comment]
Not sure but it looks like tractor didnt even start turn maneuver. What x580 is that and how did that bigX turned so fast?

**Comment by genen** [comment]
All I standard fs17 equipment. I might try this on a more open field and record it so you can see how far the tractors go without trees in the way.

**Comment by ThomasGaertner** [comment]
please try with v 0056 or higher and report ...

**Comment by lcc1211** [comment]
I will give this a go.  I was unaware anyone had reported it.  I was trying to figure out why my tipper was on the crop side.  I'll try it with vanilla equipment with debug 4.

**Comment by lcc1211** [comment]
I gave it a try, but the forage harvester stopped halfway down the lane, so I took over for a few meters and started it again, but at the end of the lane it refused to go any further.

**Comment by pops64** [comment]
log? has this might be related to another issuse

**Comment by lcc1211** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/755950/log.txt)

**Comment by pops64** [comment]
@lcc1211 is it like #1732

@genen Has your issue been fixed is the tipper wagon still selecting the wrong side?

**Comment by genen** [comment]
Guys Ive been traveling and have not had time to play... if no one else is reporting this issue I guess it can be closed. If something is not working by the time I have time to update and play the game I'll post :)

**Comment by lcc1211** [comment]
Yes just like #1732.  I tried all the vanilla forage harvesters, but all of them behave the same.

**Comment by pops64** [comment]
@genen thanks for the update I will close here to keep the issues area clean. Thanks for the reply

@lcc1211 if you could post there about your issue with that bug that would be appreciated. Thanks

**Comment by pops64** [comment]
Sorry didn't know you talking that this was driving on the wrong side I will repopen. But according to your log. The tipper should have been on the left side of the harvester. Then switched to the right side of the havester

**Comment by lcc1211** [comment]
It did find the correct lane the last time, but after having to manually force it to force it to move to a new lane several times, I stopped testing. I figured the more important thing it to figure out why it won't forage the entire field.

**Comment by lcc1211** [comment]
I have been whole crop harvesting for several days now with the tractor only hitting the wrong side one time, but I was in the last lane of the field. Now the only problem I have is with the tractors driving way outside the field during the turn maneuver and getting caught in a strand of trees.  But I think this issue is solved.  As @genen wrote earlier, I think it is OK to close this issue.

**Comment by pops64** [comment]
Thanks Closed
