### ISSUE TITLE
reverse unloading in 1 point of the bunker. 

### ISSUE THREAD

**Issue by YunexKr** [Courseplay/courseplay#1468]
Hello, 
since the new Bunker technic in FS 2017 i wanted to unload my silage in the first part of the bunker, so that i can push it deeper into the bunker with the shield. The problem is the tractors wont unload. if they drove reverse to a sertain point they just drove back to the startpoint without unloading.

**Comment by ThomasGaertner** [comment]
Post the log with debug channel 1 and 2 active ..

**Comment by evybart** [comment]
how we  use the debug channels ?

**Comment by rmn18** [comment]
looks here for Debug 
![unbenannt](https://cloud.githubusercontent.com/assets/3426782/20991619/bc318062-bcdf-11e6-8104-8a6606a7bf91.jpg)

**Comment by evybart** [comment]
ah ok thanks but how do we know what channel for what is now is it 1 and 2 but the rest off the channels  is their also a tut for grtz

**Comment by rmn18** [comment]
In the debug level, information is written to the developer in a log file which they can then evaluate what does not work under certain conditions.

**Comment by evybart** [comment]
thanks  again grtz

**Comment by YunexKr** [comment]
Here's my log file

[log.txt](https://github.com/Courseplay/courseplay/files/639445/log.txt)

**Comment by YunexKr** [comment]
Here's the new log file and a screenshot
![fsscreen_2016_12_08_16_21_26](https://cloud.githubusercontent.com/assets/23239122/21015495/7af3cbc2-bd62-11e6-96e2-d78689ce17fb.png)
[log.txt](https://github.com/Courseplay/courseplay/files/639811/log.txt)

**Comment by SnoopBok** [comment]
When I reverse into the bunker, the tractor stops and starts unloading, all acting right like it should. But before the trailer is empty it stops unloading and won't drive any further. I'm using the latest version. Any suggestions, am I doing something wrong?

**Comment by ThomasGaertner** [comment]
yep, you did :-) we are still in the no mod phase and you used a mod. We know that we will implement all the holmer stuff in the future but its not done yet....

**Comment by pops64** [comment]
#1781 Closed to keep the issues area clean and mergeing two issues together
