### ISSUE TITLE
On field turning for trailers following foragers?

### ISSUE THREAD

**Issue by adamp1986** [Courseplay/courseplay#1469]
Hi, firstly thank you for all you hard work, I play a lot of FS in single player and course play makes this a much better experience! The only thing I wish it did better was the turning of tractors and trailers that are following a forager, it would be great it it was possible for them to stay in the same field as is being harvested, especially helpful if there are lots of trees surrounding the fields. 

Thanks, Adam

**Comment by anderzxb** [comment]
yeah that would be nice. almost impossible now if you have trees sourrounding the field

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
