### ISSUE TITLE
waiting tractor to be loaded crashes into trailer being loaded

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1473]
so this is behaviour that was in the FS15 version, not sure if anyone ever reported it:

Two drivers on transport routes, being loaded by a front loader..   second driver waiting (in-traffic) behind the first driver waiting to be full.   As soon as the front loader dumps a shovel into the trailer, the second driver hits the gas and crashes into the trailer in front of him.. slipping until the first driver pulls away.

This also happens when loading trailers on the field with the overloader..  

https://dl.dropboxusercontent.com/u/36294746/2016-12-08_140920696.mp4

**Comment by SquareCloud506** [comment]
In FS15, I never used two tippers at a loading point from a shovel, altho I did use the setup with one tipper, usually a manure spreader on a refill route from a field. However I have used two tippers loading from an overloader working with a combine in a field, and never had the second truck run into the first like in your video. My observation is, the second tractor waiting is not in a straight line behind the first. Could this be a problem with the turn in the route before the loading point?

**Comment by sootysax** [comment]
you may be right, if the loading wait point were after a more straight section, maybe the second tractor wouldnt "see" the front loader collision..  however in my experience with overloaders and tippers on the field, i would have to make sure that my overloader route immediately hard turned back into the field after the unloading point as to not approach the second waiting tractor.   If i drove too close to it, it would drive into the back of the first trailer,

**Comment by ThomasGaertner** [comment]
hmm strange thing , if you can replicate it in this savegame, would you send it to me ?

**Comment by sootysax** [comment]
this is also the same scenario where #1474 is happening

https://dl.dropboxusercontent.com/u/36294746/%231473_1474.zip

**Comment by sootysax** [comment]
so this issue is still happening...

**Comment by sootysax** [comment]
i guess i never included my courseplay course folder for this...  here it is..

https://dl.dropboxusercontent.com/u/36294746/FS17_Old_Streams_Map_BsM.zip

**Comment by sootysax** [comment]
i was able to rectify this by straigtening out my approach to the loading point..

**Comment by ThomasGaertner** [comment]
so do we need to take action or not ?
