### ISSUE TITLE
unknown fill type in bucket...

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1474]
I have no idea if this is CP related, but as my shovel course is running, periodically the shovel will fill up with an 'unknown' fill type, and then just sit at the trailer and not dump...  the only thing I can do is save and restart and the bucket is empty.

It's only happening during CP route, and it's always when I am off doing something else...

confounding...

**Comment by ThomasGaertner** [comment]
yea the filltype is tarp :-)
I'm just making some changes in shovel mode, maybe i can prevent it ...

**Comment by ThomasGaertner** [comment]
is it still a issue or can I  close here ?

**Comment by bigjoker76** [comment]
Hello All,
today with actual code 18 it´s still there. I had the feeling that it was gone for a while and is back now

Regards Jochen

**Comment by sootysax** [comment]
I haven't experienced this issue again
