### ISSUE TITLE
Spielabsturz!

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#1475]
Guten Morgen! Hab folgendes Problem das während des SPiels es immer zu Absturz kommt und in der Log folgender Fehler auftritt 
[log.txt](https://github.com/Courseplay/courseplay/files/641340/log.txt)

Dieser Fehler tritt nach meinen Test her nur im zusammenhang mit dem Mengele Garant auf im Feldarbeitsmodus!

LG

**Comment by Poppei** [comment]
Probiere es mal ohne alle anderen Mods und wenn es dann noch nicht geht ,dann benutze nur die Standart Geräte weil Mengele Garant ist eine Mod und wir sind hier in der Beta da werden Mod noch nicht berücksichtigt.

**Comment by Paul2510** [comment]
Danke! Hab vergessen das der Mengele eine Mod ist! :-)
