### ISSUE TITLE
Work Width not saving

### ISSUE THREAD

**Issue by SvnRex** [Courseplay/courseplay#1476]
Work width doesn't seem to save it's settings between jobs.
For example i'll set my harvester to 13.0m instead of 13.2m and as soon as that job is finished and I move to the next field i'll have to change the work width back to 13.0m.

As a side note it would be nice to have finer control over the worth width in the +10m ranges instead of only having 0.5m increments.

Version of course play is 5.00.00026

**Comment by gibson89** [comment]
Hold the alt button while changing the width for smaller increments

**Comment by SvnRex** [comment]
Good to know about the Alt button, thank you.

**Comment by ThomasGaertner** [comment]
please test again wih v01.0016 or higher and report....

**Comment by ThomasGaertner** [comment]
closed to keep issues clean
