### ISSUE TITLE
Mode 6 question

### ISSUE THREAD

**Issue by HsHCoder** [Courseplay/courseplay#1477]
Hello everybody,

I have a request. Is there a chance to combine the Mode 6 with the Mode 7. I mean I want to harvesting in the Mode 6 and when the tank is full the harvester shoud drive to an overloadpoint (set a waitpoint). 

Da ich meinem Englisch nicht so sehr vertraue nun das ganze noch einmal auf Deutsch.

Hallo zusammen,

Ich habe eine Bitte. Gibt es die Möglichkeit bzw. ist es in Planung den Modus 6 & / zu kombinieren? Ich meine damit, das ich den Drescher im Modus 6 auf dem Feld fahren lasse. Wenn der Drescher irgendwann voll ist soll er Automatisch zum Trecker mit den Kippern fahren (Vielleicht mit Wartepunkt markiert).

Viele Grüße

**Comment by SquareCloud506** [comment]
Ah, yeah, Combine self unloading. Create an overload route that the combine follows to offload when full, then return to the field and continue harvesting. If I recall with CP for FS15, this option could not be used with a combine in Fieldwork mode. To have the combine self unload, you set up the route, then hired a standard worker for the field.

I'm inclined to agree with this suggestion. If a combine doing field work has a secondary route attached to the field work route, have it follow the route for a self unload point, and perhaps make the combine self unload button (mode 7) become obsolete. If there is no secondary route attached to the fieldwork (mode 6) route, then the combine waits for a tipper as normal.

Is this possible? :)

**Comment by HsHCoder** [comment]
Yes exactly what i mean;) The Mode 7 is nice but i don't like the Standard worker.

**Comment by ThomasGaertner** [comment]
I've implemented it in v.031 . please test it and test also the other tools using this mode, like baleloaders, forage wagons and so on. I want to know whether this change  can cause trouble with other tools.

**Comment by HsHCoder** [comment]
I will try tomorow;) Tank you for this;)

**Comment by pops64** [comment]
Had a forage wagon run off the field when it was full but it filled at the edge, So i am not sure if this issue is related or not to your change. Will update if I can reproduce

**Comment by HsHCoder** [comment]
Hello,

now i played two hours. I had one bug. The Bug was in Mode 4 I don't know if this came with this changings. 

I used a manure distributor (F2WS4000 and K165) it doesn't turn around at the end of the Field. I also tested a seeder (Rapid A 600 S) there wasn't this bug.

I also tested a forage wagon (Repex 343), a baler (BigBaler 1290), a field cultivator (TerraDisc 600) and a baleloader (FSX 63.72). I did't found a bug with all of this equipment.

The issue solved well. But I think it will be much better, when the combine drives backwards befor it go to the endpoint (fieldwork route) / startpoint (unloading route). Like it does in mode 7. (because of crop destruction)

Best regards

**Comment by pops64** [comment]
The not turning at the end of field is documented here #1492

**Comment by HsHCoder** [comment]
Ah ok sorry for that;) Then every thing is right;)

**Comment by pops64** [comment]
Deleted early comment not related to your change.

**Comment by svent75** [comment]
Do I make something wrong? I created a field course for the combine (TC5.90) and added in mode 6 the separate unload course which contains a waiting point at the point where the trailer will be parked.
I start the combine in mode 6. It is working fine until the 90% out of the setting for "start unloading" is reached. The combine stopps working and is not entering the unload course.
I use version 36.

Thanks 
Sven

**Comment by ThomasGaertner** [comment]
@svent75 : try again with the latest version 
@HsHCoder : can we close here ?

**Comment by HansJDen** [comment]
If i make a Combine unload course (mode7) and use a normal hired helper, it works fine, but the combine keep remember that course. And when i get on to the next field, both courses shows on the map. eg. (comb. 24) and (comb. 23) and it keeps going. When there are more than 2 my game starts to lag, and crash in the end. 
Used ver. 5.01.0001

**Comment by ThomasGaertner** [comment]
closed to keep the issues clean
