### ISSUE TITLE
Combine at 80%

### ISSUE THREAD

**Issue by SquareCloud506** [Courseplay/courseplay#1478]
Currently, when a combine reaches 80%, the beacon lights come on and the pipe goes out, indicating it needs to be unloaded soon. This normally is fine, and is how it worked in FS15 as well.

However, there were at times in FS15, and I'm sure at some point will happen in FS17, where a combine will reach 80% while doing the first headland of a field that happens to be on the edge of some trees, or forest, or something that the pipe will hit.

So my question/request is, at 80% turn on the beacon lights, but don't put out the pipe until the tipper arrives behind or next to it, the same way the pipe goes out when a tipper comes close when it's less than 80%.

Not a game breaker, won't make me stop using CP, not even a bug. Just a suggestion. :)

**Comment by raxtor** [comment]
+1

**Comment by bigdigger** [comment]
also could you get the combines to stay on field, like any of the tools now rev to make turn

**Comment by Satissis** [comment]
This suggestion will first be considered after the release.

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
