### ISSUE TITLE
Horsch Tiger 10 LT fine tuning and bug

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1479]
With the case mangum cvx tractor the horsch tiger 10 lt cultivator spits out a 34m turn radius.  Have not tested it enough but I think 18m seems good with this combination. Also it doesn't seem to back correctly if have turn on field enabled. Doesn't take corrective action to straighten if the cultivator kinks out.  [Video ](https://www.dropbox.com/s/12gkn669l2pkiqq/Farming%20Simulator%2017%2012_9_2016%208_23_38%20PM.mp4?dl=0)with 13 and 14 active. In the [log](http://pastebin.com/AiSQCVVD) states Magnum CVX (# 5): reverse course is not valid :O Thanks for reading

**Comment by Satissis** [comment]
Try again with v.037 or later and report back.
I did a small change to how it check for turn radius, so maybe that fixes it as well :)

**Comment by pops64** [comment]
Nope, still 34m :(. Thanks for the update tho

**Comment by Satissis** [comment]
what about reversing with it ?

**Comment by pops64** [comment]
Nope here is the [log](http://pastebin.com/wQTyNeVA). Still states Reverse course is not vaild.

**Comment by Satissis** [comment]
Try again with v.01.0011 or later and report back.

**Comment by pops64** [comment]
Seems to work great in my short test. I will close this out. 2 side notes the T9 does the wiggle dance when reversing. This may be CP trying to hard to keep it straight(Or not hard enough). Also on some tractors the tires will colide with cultivator. But neither are worthy of a bug report. Thanks for the great update

**Comment by Satissis** [comment]
The T9 wiggle dancing while reversing is something I haven't found any solution on and I should mark those articulated tractors asn not reverse able tractors, when in mode 4 or 6, which means it will always use the Wide turn or the Ohm turn.

Regarding the colliding of tractor and cultivator, you will have to manually raise the turn circle, so it does not make that sharp of an turn, which should avoid the colliding. Not something we really can predict on each and every tool and vehicles ;)

**Comment by pops64** [comment]
I kinda figured both things. Maybe there is a way to dampen the T9 steering because when the T9 turns it is instantly translated to the tool it is pushing, where as a normal tractor there is a delay.
