### ISSUE TITLE
Auto seed / fertilizer purchase

### ISSUE THREAD

**Issue by hmatt4036** [Courseplay/courseplay#1480]
Is there a way to turn off auto purchase of seed &/ fertilizer so Courseplay uses implement capacity?

**Comment by SquareCloud506** [comment]
I thought I read that CP uses the same settings as hired workers. While in your game, press ESC and go to the settings page, there you can choose if hired workers will buy more seed or not, etc. I think CP also uses those settings.

**Comment by Satissis** [comment]
yep that's correct. Auto buy is based on the game settings for hired workers ;)

**Comment by hmatt4036** [comment]
Thanks! :)
