### ISSUE TITLE
Drive through water

### ISSUE THREAD

**Issue by TheRealRolandDeschain** [Courseplay/courseplay#1482]
Hi, 
I'm new here, so don't be mad at me if this issue was posted already, but I couldn't find it in a short search. 
The issue/suggestion is the following:
I play Sosnovka and there a places where you can drive through water, however CP stops the driver and sends the message "XY wants to go swimming". 
Maybe you can add some kind of recognition for these places, so it's possible to make courses through the water (e.g. to fill up water tanks). 

Sry, I haven't made screen shots or log, but as you can see, it's pretty easy to reproduce.

**Comment by Satissis** [comment]
I'm not totally sure if that's possible to do, but we would have to research it a bit to tell, but since this is an suggestion, it will first be looked into after the release.

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
