### ISSUE TITLE
Lift Tools

### ISSUE THREAD

**Issue by iceman4** [Courseplay/courseplay#1483]
Hi
It is possible to lift the devices separately from each other, as they drive out of the field, first at the front and then at the rear

**Comment by bigdigger** [comment]
this would be good, as many times we have to go round and collect what has been cut off field

**Comment by Satissis** [comment]
This suggestion will first be considered after the release.

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
