### ISSUE TITLE
suggestion: waypoint numbers

### ISSUE THREAD

**Issue by gec100** [Courseplay/courseplay#1485]
Not sure if this is logical or maybe all ready implemented, but for purpose of easier manual inserting of crossing points directly in the sourseStorage file, would be great if we could have a option to enable/disable showing of waypoint numbers next too/instead of little pyramids. Similar to enabling view of crossing points.

**Comment by pops64** [comment]
#1382 PromGames is in the process of making a beta courseplay editor for 17

**Comment by Satissis** [comment]
Sorry not going to happen.
I would use the courseplay editor when that's available ;)
Closing to clean up issues
