### ISSUE TITLE
Überladewagen Problem!

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#1486]
Hab die letzte Version mit der Überladewagen Rohr speicherung geladen! Hab jetzt leider das Problem das er wenn er um Kipper fährt folgenden Fehler hat 
C:/Users/Nemesis/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/mode9.lua:319: attempt to index local 'targetPositions' (a nil value)
Error: Running LUA method 'update'.

Gefährt Fendt 700 Orginal UL bergmann!

Tut mir leid hab ´vergessen die Position zu speichern :-)

Vieleicht kann mann so machen das das Ende des Rohres auf die vorher eingestellte positio ausklappt!

LG

**Comment by ThomasGaertner** [comment]
try again with v.029 or higher . please consider, that you are now able to move the pipe of the overloader into a proper position and save this position. As of v .029 this position will also be saved in the savegame.

**Comment by Paul2510** [comment]
Hi! Die Rohrstellung wird  gespeichert nur beim ausklappen zum Überrladen bleib er auf der Fahrt zum überladen in der standart einstellung

**Comment by ThomasGaertner** [comment]
try again with v.031 should work now....

**Comment by Paul2510** [comment]
Hi! Es funktioniert wieder! Vielen Dank!
