### ISSUE TITLE
Courseplay 5 Fertilize problem 

### ISSUE THREAD

**Issue by Boregepco** [Courseplay/courseplay#1487]
It is not working... I make a course, but tractor don't move... 
I am with a mac FS 17 version...

**Comment by Satissis** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Boregepco** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/644071/log.txt)
 The problem is when i want to start from the first waypoint. If i drive and start from the near waypoint - it is ok.

**Comment by ThomasGaertner** [comment]
## Courseplay: initialized 38/38 files (v5.00.001)    ?????

**Comment by SquareCloud506** [comment]
@Boregepco You'll need to update to the current version. As of now the current version is v5.00.029.

**Comment by Boregepco** [comment]
I will update, but I can't find the current version... Can you help me, pls.
