### ISSUE TITLE
BGA Unloading Bug (v5.00.00030)

### ISSUE THREAD

**Issue by TheRealRolandDeschain** [Courseplay/courseplay#1491]
Hi, 
I unload forage into the BGA going backwards. Everything seems to work fine, except for this:
After unloading the current waypoint jumps from #67 to #92 and the tractor is driving against the next wall. 
Map: Sosnovka. 
log: https://gist.github.com/anonymous/6f70344a3ccb027ccdbad74a24d79790
course: https://gist.github.com/TheRealRolandDeschain/7742348c9fbab6c058d3c683ec2747ba

By the way: Really appreciate your work, this mod is awesome and for me mandatory to play in single player! :)

**Comment by Satissis** [comment]
could you take an screenshot of your course from ingame?

**Comment by TheRealRolandDeschain** [comment]
![screenshot_01](https://cloud.githubusercontent.com/assets/24492076/21081025/d877612a-bfbd-11e6-9efa-5dec08ba7be6.png)
![screenshot_02](https://cloud.githubusercontent.com/assets/24492076/21081026/d878f670-bfbd-11e6-90f8-5f53c3f834ab.png)
![screenshot_03](https://cloud.githubusercontent.com/assets/24492076/21081027/d87a1780-bfbd-11e6-99c7-19c4cb738755.png)

**Comment by ThomasGaertner** [comment]
you need to go out of the BunkerSilo more straight, if the trailer is empty, it takes the first waypoint, which is in front of the tractor, please try again again and report

**Comment by TheRealRolandDeschain** [comment]
OK, will do, thx!

**Comment by TheRealRolandDeschain** [comment]
OK, I tried it and it works fine. Thanks again!

**Comment by ThomasGaertner** [comment]
so we can close ?

**Comment by TheRealRolandDeschain** [comment]
Yep, it was as you described. I made a new course where the tractor exits the bunker in a more straight way, and now it works. So yes, you can close the issue.
