### ISSUE TITLE
[suggestion] Pallet forks being usable in Shovel mode

### ISSUE THREAD

**Issue by van-dell** [Courseplay/courseplay#1493]
Hi guys,

great work so far! I just tried to set up a "Fill and empty shovel" course to move seeds onto an auger wagon out of the BigBags with a pallet fork. I think this would work great - I managed to set up loading and unloading positions attaching a shovel instead of the fork, but those positions of course can't be replayed with a pallet fork because it's not a shovel ("No shovel could be found"). I dug around in "toolManager.lua" a little, but couldn't find a way to quickly let the fork be counted as a shovel to test it.

Would be nice if you enabled that function for pallet forks after release so I don't have to move 45 pallets of seeds manually. Thanks!

**Comment by ThomasGaertner** [comment]
I think its gonna be hard to implement, because it must be very precise, get the positions of each single palett and move to the trailer. For the moment its a no, but i will write it on our Suggestions list..

**Comment by pops64** [comment]
In the mean time here is a really nice mod on [FS-UK](http://fs-uk.com/mods/view/38340/pallet-extension) because I hate moving 45 pallets too. Only thing is the 2000L pig big bag is priced wrong. But that is an easy fix in the xml should be 2800 not 1800.

**Comment by ThomasGaertner** [comment]
I dont know if you know, but if you set the automatic buy function for seeds in the FS17 menu it will not take seeds from the tool, it will buy it instanteniously ....

**Comment by van-dell** [comment]
I have the feeling that buying stuff directly is more expensive than if I buy it manually. I haven't been able to think of an exact method to test this, however. If I time how many liters of seeds or fertilizer per second it use and compare it to what that amount should cost, I have the impression that it ticks down faster than I'd expect.

I just thought with the pallet fork that if I knew how, I could test if C:P is already precise enough for it to work despite you expecting it not to be precise enough. Seed bags spawn in an exact row, after all.

Thanks for the tip with that mod.

**Comment by ThomasGaertner** [comment]
it is *1.5

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
