### ISSUE TITLE
Strautmann  PS3401 Mistreuer Orginal

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#1494]
Hi! Ein kleiner "Fehler"! Wenn mann nur Einen Feldkurs generiert und am Anfang starten lässt schaltet sich der Mistreuer nicht ein! Die anderen schon! Bei den wendemanöver geht wieder alles normal! Eben nur nur am Anfang des Feldkurses!

LG

**Comment by ThomasGaertner** [comment]
test again with v01.0018 and report ...

**Comment by Paul2510** [comment]
HI! Danke klappt super!
