### ISSUE TITLE
Alone combines harvester runs to unload on trailer

### ISSUE THREAD

**Issue by iwan4672** [Courseplay/courseplay#1496]
Combines harvester goes to pour out on trailer, and tractor takes back on farm cereal. It after end of work and was can not the tests the ie of exit with game with her go out, and some machines disappear from farm.

Sorry for my English

**Comment by Satissis** [comment]
Not sure what you mean by it.
also, follow this ;)
https://github.com/Courseplay/courseplay/wiki

**Comment by iwan4672** [comment]
Sorry that I copy now, but I had not before holidays for a lot of time.
Here log from mods courseplay:
https://gist.github.com/iwan4672/7d58de3fcf8a296b546e53602587f738

To comparison log without mods:
https://gist.github.com/iwan4672/5232ae356211ef587330ba19c7d4b944

**Comment by ThomasGaertner** [comment]
would you please test again with the latest version? should be fixed....

**Comment by iwan4672** [comment]
OK. But I will send on maila every attentions (file log and some screeny
can)
To be such way maybe?

2017-01-04 14:01 GMT+01:00 Thomas Gärtner <notifications@github.com>:

**Comment by iwan4672** [comment]
Coming back to Combine self unloading, I inform that mistakes in game do
not step out. Game was has switched off normally. In file log shows steam
mistakes:

https://gist.github.com/iwan4672/c5571bd1de4eee5a032152d7440837d0

Beyond this all in order.
I greet.

Sorry for my English

2017-01-04 14:14 GMT+01:00 Jan Moskal <ivan4672@gmail.com>:

**Comment by iwan4672** [comment]
Sorry, I forgot adding that this concerns werji 5.01.00025

2017-01-10 14:32 GMT+01:00 Jan Moskal <ivan4672@gmail.com>:

**Comment by pops64** [comment]
What is the status of this? Is this still occurring in the most current version of CP? Can we close here?

**Comment by iwan4672** [comment]
Yes, all is already in order

2017-03-16 19:51 GMT+01:00 pops64 <notifications@github.com>:

**Comment by pops64** [comment]
Closed to keep issues are clean
