### ISSUE TITLE
Suggestion Display text save setting

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1498]
The display text setting is not saved. Would be very nice if this could be saved. As now text is shown in the mini map which gets annoying when there is 5 CP courses running in the same area. Cause I am assuming  the change in how the map now works it is no longer possible to remove text from just the mini map. Thanks for reading

**Comment by ThomasGaertner** [comment]
funny, I thought, it would work in this manner for a long time :-) 
try v.033 or higher and report...

**Comment by pops64** [comment]
Works great thanks for such a quick reply. The English version has the German word for deactivated but other than that. We can close this out
