### ISSUE TITLE
Tip trigger causing tractor to stop

### ISSUE THREAD

**Issue by Supermillhouse** [Courseplay/courseplay#1507]
Unloading into Biomass Heating Plant in this fashion causes the tractor to just stop well in advance of the tipping point. I have also tried reversing in and it does a similar thing. This is using Combi mode. I don't know if this is a thing with this map or just this style of drop off point.
![untitled](https://cloud.githubusercontent.com/assets/5963597/21155843/a17ced7a-c16b-11e6-81d7-5da32330f2a9.jpg)

**Comment by rmn18** [comment]
Is this a converted map? Mod vehicles are not yet supported. The developers are concentrating on fixing the bugs. There are already enough bugs in the standard game.

**Comment by Supermillhouse** [comment]
No mod vehicles but I understand the map is probably to blame. :)

**Comment by Supermillhouse** [comment]
I fixed it. There is an extra trip trigger left over from FS15 map, deleted it and now it works. :D
