### ISSUE TITLE
Wrong descVersion in v035

### ISSUE THREAD

**Issue by mawie** [Courseplay/courseplay#1508]
In version 035 you accidentally changed the descVersion (instead of version) from 34 to 35 so CP won't load (Error: Unsupported mod description version in mod ZZZ_courseplay).

**Comment by Vanquish081** [comment]
Correct, 35 in descVersion, the game no load.

**Comment by Satissis** [comment]
no it's 34 :P

**Comment by Satissis** [comment]
Fixed in v.036
