### ISSUE TITLE
crashes game when turning

### ISSUE THREAD

**Issue by nbhubbard96** [Courseplay/courseplay#1509]
whenever the tractor gets ready to make turn, the game freezes. it worked fine till a couple days ago. i tried downloading the newest version but it didnt help any.

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by nbhubbard96** [comment]
here is my log file. i just downloaded the newest version and it still crashed. using several mods. could be a mod conflict. ill try on a stock map and see what happens
http://pastebin.com/inisHavL

**Comment by nbhubbard96** [comment]
must be a mod conflict because i tried it on stock goldcrest map with stock cultivator and it worked fine. then i tried it with a mod john deere 630 disc and it crashed when preparing to turn. anyone know why it does this because i really like this disc.

**Comment by pops64** [comment]
Yea, mods are unsupported until CP is out of beta. I  have heard mention that you can try renaming you CP zip to ZZZ_Courseplay, which supposedly loads CP first and the files CP needs to handle mods

**Comment by sootysax** [comment]
because mods are not supported in beta?

**Comment by SquareCloud506** [comment]
@nbhubbard96 CP for FS17 is still in Beta testing. The splendid people who give countless hours of time writing the code for CP are still working out the bugs with Vanilla Maps and Vanilla Equipment. Any potential mod conflicts will be address AFTER they're satisfied with the debugging of Beta and officially release CP as working mod for FS17. 

If you could do some groundwork and identify the particular mod conflict in question, I'm sure the fine people who are developing this great mod for us to enjoy will add it to their post release todo list. 

Cheers :)

**Comment by nbhubbard96** [comment]
I figured out which mod crashes it. I got it off of American style modding

**Comment by nbhubbard96** [comment]
It's a John Deere 630 disc

**Comment by Satissis** [comment]
Closing due to mod fault and not in the mod phase yet. Once we are, then retest and if you still have this issue, either reopen it or post an new one and also with an new log ;)

**Comment by nbhubbard96** [comment]
ok
