### ISSUE TITLE
Futtermischer Pack and Fabrikscript issues

### ISSUE THREAD

**Issue by Xmen81** [Courseplay/courseplay#1510]
Hallo,

habe das Problem das wenn ich auf der MAP NorgeCrest 17 die Mod Futtermischer Pack Platzierbar  und siese mit Courseplay befüllen (Beladen am Startpunkt) will stürztz das Game ab und ist nur über die Console mehr mit Quit das austeigen aus dem Spiel möglich.

Bitte um Hilfe

CP V5.000.034

MfG

**Comment by rmn18** [comment]
Zum ersten ,Mods usw werden noch nicht unterstützt ,zum 2. in englisch posten hier ,weil nicht alle Devs hier deutsch verstehen. Modmaps irgend welche Mods kommen später dran weil hier versucht wird CP stabil zu bekommen auf den Standarts weil es immer noch Bugs im Vanilla Game gibt .Immer mit Standarts testen und nicht mit ModMaps oder Mods.

**Comment by lcc1211** [comment]
I hope this will be revisited after the beta testing is finished as I would like to use this mod.

**Comment by pseudex** [comment]
this looks like a fabrikscript issue
have a look here: #1573

**Comment by lcc1211** [comment]
I don't anything about fbrik?  Would it have come automatically with a mod I may have added?  If not, then I have never added it intentionally.

**Comment by pseudex** [comment]
This mod is based on Fabrikscript. Unload trigger don't work with CP.
can you try this version of the mod: https://goo.gl/eKJ5kU
I've replaced the function mentioned in #1573

**Comment by lcc1211** [comment]
Thank you.  I'll d/l and test it out.

**Comment by pops64** [comment]
Updated title for clarity

**Comment by pops64** [comment]
Closed Duplicate #1573
