### ISSUE TITLE
Reverse driving to silo?

### ISSUE THREAD

**Issue by anderzxb** [Courseplay/courseplay#1511]
Unloading in silage silos can also be done in reverse. When recording the route, reverse to the backend of the silage bin and change to forward again and continue the route. Unloading will be done from the rear end of the silage silo. For better handling, unloading will start a couple of silo sections before to build up and ramp. This dosent work in courseplay 5? i have ver 5.00.00036. 

have tried multiple times and no sucess.. i know i did it on FS15 .. 

Thanks for help

Edit the tractor unload as fast it reach tiptrigger in the silo

Edit 2 : no mods is using. Tractor is the Fendt 939 and tipper Krone

**Comment by anderzxb** [comment]
No one has an answer? or im just stupid? :)

**Comment by Karlshoj** [comment]
Same for me

**Comment by Satissis** [comment]
nop that feature have been removed since the new tip anywhere was implemented by Giants. (Note: The user manual have not been updated to v5 yet) and Thomas have other plans for it

**Comment by anderzxb** [comment]
ok thanks for answer. yeah i just copy and pasted couse im bad at english (im swedish). i really starting to get annoying about FS17 maybe time to go back to FS15 =)

**Comment by Satissis** [comment]
I'll close this, due to we have other plans for the reverse unloading into the bunker siloes ;)
So stay tuned until that is implemented.
