### ISSUE TITLE
Using trailer cultivator, AI start going backward and stay stuck until the end of time

### ISSUE THREAD

**Issue by Josephbones** [Courseplay/courseplay#1512]
HI, will add Pictures tonight - and a video when i am back home

I plan, with courseplay 5, in farming simulator 2017, a cultivating course, using field work mode. 
Tractor is not important as any tractor i used had the problem, and all cultivator(trailer mode) have also the issue.

Step to reproduce:
1-Generate a course on a field using field work mode
2- Have tractor with cultivator ready to go ( using FENDT 900 vario and Kokerling cultivator )
3- it start cultivating
4- at the end of the field, it goes backward and turning..
5- continue to go backward
6- continue to go backward

Map tested,
Goldcrest- starting fields
Sosnovka - starting field
Chellington - mega huge field at the exit of the farm, can;t remember the number
Lossberg

**Comment by PavelMoo** [comment]
Та же проблема.

**Comment by Satissis** [comment]
Try again with v.037 or later and report back.

**Comment by Satissis** [comment]
@Josephbones any update on this ? and can we close it again ?

**Comment by Josephbones** [comment]
Was not at home since a long time, will update to latest version tonight
and validate if it is fixed

**Comment by Josephbones** [comment]
Tested, Tractor FENDT VARIO 900 with Kokerling cultivator, on field 19 Sosnovka, Work like a charm.. also tested turn on field = on and turn on field = off ( two different ways to turn and place for next line )

The two function as they should

Thanks a lot for the quick fix and sorry for the late response :)
