### ISSUE TITLE
Suggestion; Fine tuning. change manually unloading speed for MODE 7

### ISSUE THREAD

**Issue by Raints** [Courseplay/courseplay#1513]
Not sure whether it can be done, but in mode 7 combine unloading I did create unloading point like this:

Mode 7: Combine self unloading -> can now create heaps as well. This is done by adding 2 waiting point instead of 1 (which is used to unload into an trailer). One for the heap start and one for the end of the heap. The combine will adjust the unload speed by it self while doing that.

Problem is when it starts to unload I think the speed is too fast, harvester create heap in the end of the line and if the heap is full it just stops and wont continue harvest. Maybe should change formula for speed calculating.

**Comment by Satissis** [comment]
what speed does it go at ? if it's 3kmh then that's the slowest we allow it to drive, so if it needs to go slower, we would have to make some changes to the code, which in some cases are not good.
To increase the unloading speed, just make an bigger distance between the 2 unloading wait points and it set the speed higher sine it have to travel a bigger distance.

**Comment by Raints** [comment]
Since I had big field, did make very long distance. The speed was 18 km/h if I remember correctly. Problem was at the end at last waiting point. Harvester did hold 4000- 5000 L of sugarbeets and finally the heap was full. Is there a possibility to change manually unloading speed?

**Comment by Satissis** [comment]
No there is not. At least not that I know of, since it's Thomas that did this function.

**Comment by Raints** [comment]
Maybe adding possibility to change unload speed will fix this. Would be great if I can unload with speed 5 to 10 km/h and it will create higher heap at the start. Then loads the rest of the heap.

[https://youtu.be/MU-yDVomySs](url)

Here is a video

**Comment by ThomasGaertner** [comment]
we decided not to implement a manual unloading speed but to check the calculation of the unloading to prevent these heaps at the end...

**Comment by Blackmankot** [comment]
@pops64  This question has already been resolved?

**Comment by pops64** [comment]
@Raints I know we didn't implement your suggestion and probably won't but I did make improvements to the calculations so you should no longer have this behavior unless you 2 unload points are too close together which case there is nothing we can do about that. Could you please report back with the current version and let us know if the better calculation is working for you. Thanks

**Comment by pops64** [comment]
Closing this out due to inactivity.
