### ISSUE TITLE
Spielabsturz

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#1514]
Guten Morgen! Hab zur zeit das Problem das das SPiel immer wiedr abstürtzt und folgender Fehler kommt

C:/Users/Nemesis/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/drive.lua:604: attempt to index a nil value
Error: Running LUA method 'update'.
C:/Users/Nemesis/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/drive.lua:82: attempt to index a nil value
Error: Running LUA method 'update'.

vers 36

**Comment by Poppei** [comment]
Spielversion???oder bei was stürtz es ab

**Comment by Paul2510** [comment]
Map ist die Wetbridge Hills! Coursplay version ist 00036! Wes wegen er gnau abstürtzt weis ich nicht! Arbeiten mit Courseplay sind mit Liberherr Radlader und SIlage gabel Bga Silo in Bunker leeren! Pappeln häckseln und Abfahrn mit Krone Häcksler und Schneidwerk! Und John Deer 8er und Orginal Silieranhänger! Und Steyr Orginal mir Krampe big body 3 Axler (Mod)! 
[log.txt](https://github.com/Courseplay/courseplay/files/654529/log.txt)

**Comment by rmn18** [comment]
mods mal wech lassen ,so nach und nach die Mods dann einsetzen ,CP unterstützt im Moment keine Mods oder Modmaps ,erst wird CP stabil aufs Vanilla Game getestet .
