### ISSUE TITLE
Vorschlag für "Abkippstelle setzen" Funktion

### ISSUE THREAD

**Issue by Lars200027** [Courseplay/courseplay#1516]
(!!!Bitte nicht wundern, dass dieser Vorschlag als Frage formuliert ist (habe diese Frage bereits vorher in einem anderen Forum gestellt), aber ich denke, man kann mein Anliegen auch so verstehen)

Moin,
weiß zufällig jemand, ob es bei CP (benutze die neuste Beta-Version) eine Art "Abkippstelle setzen" Funktion gibt? So wie die anderen Funktion (z.B. "Wartepunkt setzen") in dem "Abfahrhelfer Steuerung" Menü. Ich benötige so eine Funktion, da es ja beim (Silage-)Silo bzw. davor keinen Abkipptrigger gibt. Momentan habe ich es so gelöst, dass ich vor dem Silo einen Wartepunkt gesetzt habe. Aber es wäre ja viel schöner, wenn der Abfahrer an einer bestimmten Stelle abkippen und dann weiterfahren würde, da ich ja so jedes Mal aus meinem Walz-Schlepper aussteigen muss, den Hänger vom CP-Fahrer akippen und ihn dann wieder losschicken muss.  Würde mich sehr freuen, falls so eine Funktion umgesetzt werden könnte :)
mfg Lars 200027

**Comment by HsHCoder** [comment]
Du kannst mit deinen CP-Fahrer Rückwärts ins Silo fahren lassen und dann Vorwärts wieder raus. Dann sollte er direkt am Anfang, aber innerhalb des Silos abkippen. Selber habe ich es noch nicht getestet sollte aber Funktionieren. Eventuell noch einen Wartepunkt setzten und eine Zeitlang warten lassen (bis er fertig abgetippt hat).

Habs selber noch nicht Probiert sollte aber funktionieren.

**Comment by ThomasGaertner** [comment]
can we close here ?

**Comment by Lars200027** [comment]
@HsHCoder vielen Dank
@ThomasGaertner yes, sorry for the late answer, I haven´t looked if somebody answered my question since  two days after I put it in here (sorry for my englisch)
