### ISSUE TITLE
Question/Suggestion Chain courses/fields

### ISSUE THREAD

**Issue by SunkenL** [Courseplay/courseplay#1517]
Hello there! 
Just have to say amazing work you guys have done. Over 200h in the game with courseplay and still loving it!

I have a wonder though!
I want to chain together several courses and its not working as i want!
For example:
Course 1: go from garage to field 1!
Course 2: seed field 1!
Course 3: go from field 1 to field 2!
Course 4: Seed field 2!
Course 5: go from field 2 to garage!
Course 6: A well placed fillseed course!

I have chosen the "Append course at the end" on the transferroutes.
I cant get this to work. Either with just one field either!
Anyhow i would love if this was possible..

MVH
Sunken

**Comment by raxtor** [comment]
+1

**Comment by sootysax** [comment]
CP has never done that

**Comment by raxtor** [comment]
its suggestion.. and its sounds good to me.  Its trouble sometimes that CP cant do 2 field works in row... aslo I would like to have something like vehicle course history, because sometimes I have composite course and I use 1 tractor with 2 or 3 diferent tools. Than I have to make settings for fieldwork again and again including tools offset etc.

**Comment by Satissis** [comment]
@SunkenL yeah as @sootysax said, CP have never been able to connect 2 fields together like the way you want.
The simple reason is that we mark each field with 2 waiting points (Done internally) Those are used to define the field start and end point.
Now if you add another field to it, it will then have 4 wait points, but sine in some cases we uses the wait point 3 and/or 4 for other stuff, like refilling or selling courses that can be linked to the first generated field course, you will start see why this will not be able to do so.

For it to work, we would have to rewrite the whole base system for it, so I don't think that will be something we want to look into.

**Comment by PromGames** [comment]
@Satissis, @sootysax I do not know if I am doing something wromg, but the conecction of courses in merge format seems to not work properly

![image](https://cloud.githubusercontent.com/assets/9979168/21285860/b882223e-c444-11e6-8078-a27fab507256.png)

I am just trying to merge two courses with crossing points, system recognize the first group of two close enough to be set a s merge point but not in the second.

This the debug information

`[dbg8 lp9792] CR10.90: loadCourse(..., id=3, useRealId=true, addCourseAtEnd=false)
[dbg8 lp9792] course_management 135: CR10.90: no course was loaded -> new course = course -> currentCourseName="Field6 unloadTrain", numCourses=1
[dbg8 lp10005] CR10.90: loadCourse(..., id=2, useRealId=true, addCourseAtEnd=false)
[dbg8 lp10005] course_management 141: CR10.90: currentCourseName="Field6 unloadTrain", numCourses=1 -> add new course "field 1 unloadTrain"
[dbg8 lp10005] course1 wp 29: add to crossingPoints[1]
[dbg8 lp10005] course1 wp 35: add to crossingPoints[1]
[dbg8 lp10005] course1 wp 80: add to crossingPoints[1]
[dbg8 lp10005] course2 wp 1: add to crossingPoints[2]
[dbg8 lp10005] course2 wp 23: add to crossingPoints[2]
[dbg8 lp10005] course2 wp 344: add to crossingPoints[2]
[dbg8 lp10005] course2 wp 345: add to crossingPoints[2]
[dbg8 lp10005] course 1 has 3 crossing points (excluding first point), course 2 has 4 crossing points (excluding last point), useFirstMatch=false
[dbg8 lp10005] course1 wp 29, course2 wp 1, dist=172.66554172735
[dbg8 lp10005] course1 wp 29, course2 wp 23, dist=1.404599587071
[dbg8 lp10005] 	useFirstMatch=false -> 2 valid crossing points found: (1)=#29, (2)=#23, dist=1.4 -> lastMergedWP=29, set "merged" for both to "true", continue
[dbg8 lp10005] course1 wp 29, course2 wp 344, dist=12.808735300567
[dbg8 lp10005] course1 wp 29, course2 wp 345, dist=16.408930495313
[dbg8 lp10005] course1 wp 35, course2 wp 1, dist=165.40959978187
[dbg8 lp10005] course1 wp 35, course2 wp 23, dist=15.366538321951
[dbg8 lp10005] course1 wp 35, course2 wp 344, dist=1.6692812824686
[dbg8 lp10005] course1 wp 35, course2 wp 345, dist=2.0080836635957
[dbg8 lp10005] course1 wp 80, course2 wp 1, dist=264.16155094941
[dbg8 lp10005] course1 wp 80, course2 wp 23, dist=250.96297615385
[dbg8 lp10005] course1 wp 80, course2 wp 344, dist=237.61498479683
[dbg8 lp10005] course1 wp 80, course2 wp 345, dist=234.38280589668
[dbg8 lp10005] CR10.90: merge points found: course 1: #29, course 2: #23
[dbg8 lp10005] CR10.90: adding course done -> numWaypoints=382, numCourses=2, currentCourseName="2 combined courses"
Warning: Character '9' not found in texture font ([dbg8 lp10005] course1 wp 29: add to crossingPoints[1]
[dbg8 lp10005] course1 wp 35: add to crossingPoints[1]
[dbg8 lp10005] course1 wp 80: add to crossingPoints[1]
[dbg8 lp10005] course2 wp 1: add to crossingPoints[2]
[dbg8 lp10005] course2 wp 23: add to crossingPoints[2]
[dbg8 lp10005] course2 wp 344: add to crossingPoints[2]
[dbg8 lp10005] course2 wp 345: add to crossingPoints[2]
`
I do not understand why course1 wp 35, is not getting merged with course2 wp 344, where the distance is just dist=1.6692812824686. I just also created wp 345 that also is enough closed

**Comment by ThomasGaertner** [comment]
we have dicussed it and decided not to do it at the moment.
