### ISSUE TITLE
error on update dated from stream

### ISSUE THREAD

**Issue by bigdigger** [Courseplay/courseplay#1519]
<modDesc descVersion="34">
	<version>5.00.00036</version>
Load mod: zzz_courseplay
Error: Unsupported mod description version in mod zzz_courseplay
Load mod: ZZZ_GPS
Load mod: ZZZ_GrowthControl

<modDesc descVersion="31">
	<version>5.00.00036</version>

Load mod: zzz_courseplay
Load mod: ZZZ_GPS
Load mod: ZZZ_GrowthControl
  Register vehicle type: FS17_Joskin_Wago_Loader_Auto_BsM.transportTrailerUAL
  Register vehicle type: FS17_landrover109.landrover109
  Register vehicle type: FS17_lizardFloodLightTrailer.lizardFloodLightTrailer
  MapAutosave V2 by derSchreiner
  Register vehicle type: timber_runner_autoload_FS17.AutoLoadWoodTrailer
Error: C:/Users/Shaun/Documents/my games/FarmingSimulator2017/mods/zzz_courseplay/courseplay.lua:40: attempt to index global 'g_gameSettings' (a nil value)
Error: C:/Users/Shaun/Documents/my games/FarmingSimulator2017/mods/zzz_courseplay/register.lua:162: attempt to index field 'table' (a nil value)
dataS/cameraPath01.i3d (0.14) ms
dataS/cameraPath02.i3d (0.11) ms
dataS/cameraPath03.i3d (0.07) ms
data/sky/skyUS_day_night.i3d (8.45) ms
data/sky/rain.i3d (0.89) ms
data/sky/hail.i3d (0.96) ms
data/sky/dust.i3d (0.41) ms
data/maps/map01.i3d (1565.92) ms
data/objects/basketball/basketball.i3d (1.28) ms
Error: Running LUA method 'loadMapFinished'.
C:/Users/Shaun/Documents/my games/FarmingSimulator2017/mods/zzz_courseplay/CpManager.lua:42: attempt to index field 'signs' (a nil value)
Application exit request forced.
Application exit request forced.

any help

**Comment by Satissis** [comment]
you need to update your game to patch v1.3.1.
You will see in the log what version you are running right now and CP will not work on any version below that.

**Comment by SquareCloud506** [comment]
If you didn't buy the game from Steam, you can get the latest update here.

https://www.farming-simulator.com/updates.php?lang=en&country=us

**Comment by bigdigger** [comment]
its the new update of steam just downloaded yesterday

**Comment by Satissis** [comment]
we would still need the full log ;)

**Comment by Satissis** [comment]
@bigdigger any update on this ?

**Comment by ThomasGaertner** [comment]
closed to keep issues clean
