### ISSUE TITLE
Question/Suggestion Filling at the starting point Fruit plants

### ISSUE THREAD

**Issue by Xmen81** [Courseplay/courseplay#1520]
Hello Guys, at the first i will say nice job for courseplay.

My question is, I have three courses at the same loading point with three different fruit varieties, it is possible to select different types of fruit for each course.

Best regards.

**Comment by Satissis** [comment]
nop. only one type is able to be selected.
Adding such feature is not something I want to do either, since I think it will need some extra hud stuff, that I really don't like playing with.

**Comment by pops64** [comment]
Though it would be nice if mode 1 only ran start to stop now(Yes the stop at next trigger sort of works, but you got to hit after you sell). Seeing how prices change once you sell fruit, instead of hourly
