### ISSUE TITLE
When using CP for field mission, the money for fuel, seed as well as fertilizer gets removed from my money

### ISSUE THREAD

**Issue by LordNighthawk** [Courseplay/courseplay#1521]
Hi there,

i know that for sure cp is NOT for doing the field missions, but i tested it for the really big and long missions i nearly never have the complete time available for to finish them (i start the mission and when i run out of time i let cp finish it), but i just realized that the complete fuel, seed and fertilizer costs get removed from my personal account.

**Comment by Satissis** [comment]
As you said your self, CP was never meant to be used for Missions (That's a bit cheaty :P) so I don't think we will be doing anything about this, thou I still need to talk with Thomas about it first ;)

**Comment by SquareCloud506** [comment]
I like to use CP for tending to the fields I own while I go do missions to make some extra money. :)

**Comment by LordNighthawk** [comment]
As i said, i just tried it for a time-help with the big field missions (as they partially can take around 3 hours), recognized the problem and just reported it. If you say the problem is uninteresting or unimportant then...it´s absolute ok ;)

**Comment by pops64** [comment]
I think if you turn off the option to turn auto buy seed/ fert. CP will no longer purchases these. As I run CP for missions as well with theses options off and have never noticed my money go down.

**Comment by LordNighthawk** [comment]
Ah, you are right, that did the trick. Wondering why that was turned on as i turned it off last time i started the new savegame.

**Comment by pops64** [comment]
The seed and fert and a few other options are linked to the difficulty of the game on start. Really annoying that giants didn't do a global setting for theses

**Comment by ZZenon** [comment]
How can you run out of time? you would have to be extremly slow...fir the biggest fields where they give u 100+ minuts...i usualy have 30min spare time

**Comment by LordNighthawk** [comment]
Field 5 with sugar beet as worst case scenarios. And i have 2 children that love to shout for their dad frequently so........cp is a nice addition to keep the machine running ;)

**Comment by sootysax** [comment]
youre playing on easy

**Comment by SquareCloud506** [comment]
I play on hard. True CP is handy when used for field missions, but I find it a bit more effective with GPS and auto turn at the edge of field. If it skips a row, then I just hit the missing rows on the way back. As for time on hard using GPS, I tend to have more time left when performing tasks on larger fields with bigger equipment, and only see the RED 2 minute warning on smaller fields with smaller equipment.

However, even though you can't leave the field during a mission, having a CP driver handle the task while you 'ride along' is a great way to get a mission done while you multi-task other parts of life.

**Comment by ThomasGaertner** [comment]
whats the staus here, can we close ?

**Comment by ThomasGaertner** [comment]
closed to keep the issues clean...
