### ISSUE TITLE
No Courseplay for the Holmer Terra?

### ISSUE THREAD

**Issue by JM-AS-NB** [Courseplay/courseplay#1525]
Hello,

Courseplay do not show up for the Holmer Terra Variant mod.

**Comment by pops64** [comment]
Mods are unsupported until CP is out of beta

**Comment by JM-AS-NB** [comment]
ow ok, thank you.
i will wait with patience. ;)

keep up the good work lads.

**Comment by ThomasGaertner** [comment]
rename the coureplay.zip to ZZZ.courseplay.zip and try again ...

**Comment by pops64** [comment]
This worked for me.

**Comment by JM-AS-NB** [comment]
Works fine!!!
Thanks a lot!
