### ISSUE TITLE
Support for Multiplayer?

### ISSUE THREAD

**Issue by LSmaggo** [Courseplay/courseplay#1526]
Hello Guys,

will courseplay support multiplayer in FS17?

Thanks

**Comment by Siniy-lom** [comment]
don`t work
server start and work normal
client dont`load map - error written steam (what he forgot? and why the client is generally something to write? enough control administrator only)

**Comment by Satissis** [comment]
It might get implemented or not. We haven't really decided yet, but one thing is for sure, we want to have other things done before we even start considering implementing MP and it will first be after the first release.

Please close this issue if the answer suffice you

**Comment by Siniy-lom** [comment]
@Satissis please read mail

**Comment by Satissis** [comment]
I have not seen it in my inbox, so either I deleted it by an mistake or it never got to me.

Further more, please write here instead of sending emails directly to me.

**Comment by LSmaggo** [comment]
Ok thanks Satissis for the information
