### ISSUE TITLE
Merging Courses with crossing Points

### ISSUE THREAD

**Issue by PromGames** [Courseplay/courseplay#1528]
When merging courses ingame, is not recognizing all crossing waypoints.

 I do not know if I am doing something wrong, but the connection of courses in merge format seems to not work properly

![image](https://cloud.githubusercontent.com/assets/9979168/21285860/b882223e-c444-11e6-8078-a27fab507256.png)

I am just trying to merge two courses with crossing points, system recognize the first group of two close enough to be set a s merge point but not in the second.

This the debug information

´´´[dbg8 lp9792] CR10.90: loadCourse(..., id=3, useRealId=true, addCourseAtEnd=false)
[dbg8 lp9792] course_management 135: CR10.90: no course was loaded -> new course = course -> currentCourseName="Field6 unloadTrain", numCourses=1
[dbg8 lp10005] CR10.90: loadCourse(..., id=2, useRealId=true, addCourseAtEnd=false)
[dbg8 lp10005] course_management 141: CR10.90: currentCourseName="Field6 unloadTrain", numCourses=1 -> add new course "field 1 unloadTrain"
[dbg8 lp10005] course1 wp 29: add to crossingPoints[1]
[dbg8 lp10005] course1 wp 35: add to crossingPoints[1]
[dbg8 lp10005] course1 wp 80: add to crossingPoints[1]
[dbg8 lp10005] course2 wp 1: add to crossingPoints[2]
[dbg8 lp10005] course2 wp 23: add to crossingPoints[2]
[dbg8 lp10005] course2 wp 344: add to crossingPoints[2]
[dbg8 lp10005] course2 wp 345: add to crossingPoints[2]
[dbg8 lp10005] course 1 has 3 crossing points (excluding first point), course 2 has 4 crossing points (excluding last point), useFirstMatch=false
[dbg8 lp10005] course1 wp 29, course2 wp 1, dist=172.66554172735
[dbg8 lp10005] course1 wp 29, course2 wp 23, dist=1.404599587071 -->OK
[dbg8 lp10005] useFirstMatch=false -> 2 valid crossing points found: (1)=#29, (2)=#23, dist=1.4 -> lastMergedWP=29, set "merged" for both to "true", continue
[dbg8 lp10005] course1 wp 29, course2 wp 344, dist=12.808735300567
[dbg8 lp10005] course1 wp 29, course2 wp 345, dist=16.408930495313
[dbg8 lp10005] course1 wp 35, course2 wp 1, dist=165.40959978187
[dbg8 lp10005] course1 wp 35, course2 wp 23, dist=15.366538321951
[dbg8 lp10005] course1 wp 35, course2 wp 344, dist=1.6692812824686 --> should be merged
[dbg8 lp10005] course1 wp 35, course2 wp 345, dist=2.0080836635957
[dbg8 lp10005] course1 wp 80, course2 wp 1, dist=264.16155094941
[dbg8 lp10005] course1 wp 80, course2 wp 23, dist=250.96297615385
[dbg8 lp10005] course1 wp 80, course2 wp 344, dist=237.61498479683
[dbg8 lp10005] course1 wp 80, course2 wp 345, dist=234.38280589668
[dbg8 lp10005] CR10.90: merge points found: course 1: #29, course 2: #23
[dbg8 lp10005] CR10.90: adding course done -> numWaypoints=382, numCourses=2, currentCourseName="2 combined courses"
Warning: Character '9' not found in texture font ([dbg8 lp10005] course1 wp 29: add to crossingPoints[1]
[dbg8 lp10005] course1 wp 35: add to crossingPoints[1]
[dbg8 lp10005] course1 wp 80: add to crossingPoints[1]
[dbg8 lp10005] course2 wp 1: add to crossingPoints[2]
[dbg8 lp10005] course2 wp 23: add to crossingPoints[2]
[dbg8 lp10005] course2 wp 344: add to crossingPoints[2]
[dbg8 lp10005] course2 wp 345: add to crossingPoints[2]
´´´
I do not understand why course1 wp 35, is not getting merged with course2 wp 344, where the distance is just dist=1.6692812824686. I just also created wp 345 that also is enough closed.

![image](https://cloud.githubusercontent.com/assets/9979168/21286504/2148328e-c456-11e6-8989-9f89c53dcd80.png)

Edit: I temporary solved it because if you merge again the course1, then is creating the final course as desired, But I remember that in FS15 works with just one merge. Maybe I am wrong

![image](https://cloud.githubusercontent.com/assets/9979168/21286586/c98c1fda-c458-11e6-8baf-b59c7351daaa.png)

**Comment by pops64** [comment]
I remember from 15 that you load A, merge B, merge A for something like changing silo bays,
http://courseplay.github.io/courseplay/en/manual/index.html#hud_driverControls but Thomas or Satis could say for sure

**Comment by SunkenL** [comment]
This seems interesting. Anyone knows about a tutorial for this handling? Cant find any on youtube..

**Comment by PromGames** [comment]
@pops64  Quote: Hope courseplay editor is coming along nicely.
We are now under Beta testing with SOB Modding Team. We expect to release it by next week.

**Comment by sootysax** [comment]
i always setup my crossing points in a kind of a triangle at the crossroads.  two on one side of the road, and another in the middle of those two point on the otherside of the road.  I could certainly help beta test if you need

**Comment by ZZenon** [comment]
I used to have a small course for selecting silos in fs 2015 and then the actual course to diner/train etc....so just pick the course/grain u want to sell and then add the actual seling course (the silo course needs to end near the starting point of the selling course) But in fs2017 there is only 1 silo so its easyer, but i prefer to end the course just a few meters before the silo....so when i start a course i can select what i want to sell and when the tractor starts and hits the silo it will load what i want

**Comment by Anonymous-any** [comment]
I got an similar issue too when try to build multi-fields when it go to another field it try to change to load or unload course something like that. 

PromGames please continue your build dev for courseplay editor we NEED IT !!! please please i'm not know anything about programming. :/ Best regard to all

**Comment by pops64** [comment]
Closed to keep the issues area clean
