### ISSUE TITLE
Bug: tabbing to a tractor thats unloading

### ISSUE THREAD

**Issue by SunkenL** [Courseplay/courseplay#1529]
Hello there again!

Think this is a bug in courseplay..
When a tractor unloads the fruit/straw to a trigger and i happen to tab into there when the unloading happens then the tractor stops unloading and just sit there..
Then i need to start at nearest waypoint again..

Cheers!

**Comment by Satissis** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by SunkenL** [comment]
Sorry for delayed response.
[log.txt](https://github.com/Courseplay/courseplay/files/690385/log.txt)
Just tried it with v.5.01.00018 and the problem remains
No mods  but plays on hobbs farm

**Comment by ThomasGaertner** [comment]
what about the error of Inspect17 ??

**Comment by SunkenL** [comment]
Ah so that can be the problem. With "no mods" i meant  the tractor and tipper.. Good to know.! Didnt thought of that!

**Comment by SunkenL** [comment]
I will test it without the mod Inspect17 when i have time later today.

**Comment by ThomasGaertner** [comment]
what about the same situation on a other (vanilla) map ?

**Comment by SunkenL** [comment]
It seems that the problem has stopped. May me a update from courseplay or from another mod..
You can close this! Thank you for the help!
