### ISSUE TITLE
Mode 6 self unloading combine

### ISSUE THREAD

**Issue by svent75** [Courseplay/courseplay#1530]
Hello,

Do I make something wrong? 
I created a field course for the combine (TC5.90) and added in mode 6 the separate unload course which contains a waiting point at the point where the trailer will be parked.
I start the combine in mode 6. It is working fine until the 90% out of the setting for "start unloading" is reached. The combine stopps working and is not entering the unload course.
I use version 36.

Thanks
Sven

**Comment by ThomasGaertner** [comment]
just checked it and worked fine , would you test again with the latest version 01.0007 and report ? 
thanks

**Comment by ThomasGaertner** [comment]
should be finally fixed in v.0064 . I will close here to keep issues clean
