### ISSUE TITLE
Can't set baler working width to match largest windrower

### ISSUE THREAD

**Issue by Jimather** [Courseplay/courseplay#1531]
When generating a fieldwork course for a baler, I only have the option for 14.5m or 15m working width. This doesn't match the working width of 14.8m for the largest windrower and the course slowly drifts off the lines of straw etc

**Comment by ElThreep** [comment]
Click add or remove 0.5m.
Ctrl + Click add or remove 2m.
Alt + Click add or remove 0.1m.

**Comment by Jimather** [comment]
Awesome stuff, thanks!
