### ISSUE TITLE
Tractor turns in front of Harvester

### ISSUE THREAD

**Issue by Nebular64** [Courseplay/courseplay#1532]
The issue started when I updated to v.036.  When using Mode 2 and a harvester is full with the pipe on the fruit side, the tractor will pull up and fill.  Once the harvester starts moving, the tractor attempts to make a right turn (instead of waiting for the harvester to pass as it did on v.034), thus running into and blocking the harvester.

It might be an issue with v.035 and the turn.lua, but I haven't looked.

-UPDATE-
Just FYI.  The issue cleared when I reverted to v.033

**Comment by Satissis** [comment]
turn.lua have nothing to do with mode 2. it's only activated in mode 4 and 6

**Comment by Nebular64** [comment]
Thanks for the info.  It must be something on my end then, so I'll close this and wait for the next update.  I greatly appreciate all of your hard work.
