### ISSUE TITLE
Suggestion Straw Swath

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1533]
If remember in FS15 early versions of CP wasn't there an option to turn straw swath on automatically. If there wasn't this would be a great feature now because in 17 if you harvest something other than wheat or barely it turns off straw swath and doesn't turn it back on when your done like in 15(Won't even let you until you have started to harvest wheat or barley). So my suggest would be to have option in the hud to turn on straw swath automatically if it detects that the harvester can do so. Thanks for reading as always keep up the great work

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
