### ISSUE TITLE
Combine doesn't turn end of field

### ISSUE THREAD

**Issue by AgroWillem** [Courseplay/courseplay#1537]
I reopen issue #1492  because i have have the problem back.
At the end of the 2nd row the combine doesn't turn but runs into the woods.
CP.0036
Map: GoldCrest Valley (standard)
Combine: CASEII AF-9230 (standard)
Field: 31
When i install V.0033 the problem is gone.

EDIT:
Under V.0033 i have the same problem with a grassmower.
After 1 row it won't turn anymore.
tractor: MF 7700
mowers: Lely Splendid 320FC + 900MC
field: 28
When i go back to V.0036 the mowers work again but then the combine (see above) have the issue.
What could be the problem???

[log](https://gist.github.com/AgroWillem/3fc8c5adf3211a1f44f02182992db2a9)

**Comment by pops64** [comment]
Satis will most likely ask you turn off all your mods but CP and try again with debug 12 and 14 active and post that log. Cause I looked through you log and one of your mods is throwing out an error. My guess is it is the FS17_SeedAndFertSilo_1 mod. If it starts working without your mods on turn them on one by one until CP stops working

**Comment by AgroWillem** [comment]
Ok. Will do. I'll let it know.

**Comment by pops64** [comment]
How full is the harvester when making turn? Picture would be nice as well

**Comment by AgroWillem** [comment]
This issue can be closed.
After starting a new game, the problem was gone.
I don't know what happened.

Happy Christmas from the Netherlands.

**Comment by Satissis** [comment]
Try again with v.037 or later and check if it fixes you issue on your old game ;).

**Comment by Retsamikit** [comment]
For me 0..37 does not turn at the end of any row. Tried two different Tractors at three fields in Sosnovka. Tried to use a fresh Game. Same.

**Comment by tjb8907** [comment]
I am having the same issue with my seeder. Have had the problem with 036 and 037, went back to 028 and it works again. It drives the headlands and first lane, but then continues on straight. I can stop it and resume it on the second lane, but does the same thing when it gets to the end. 

It doesn't even stop it just goes straight and speeds up.  No errors in the log.

**Comment by gec100** [comment]
i can confirm this. 
![fsscreen_2016_12_26_11_59_36](https://cloud.githubusercontent.com/assets/8178773/21480990/1c4470d6-cb63-11e6-80e4-b77f4d93f80f.jpg)
![fsscreen_2016_12_26_11_57_42](https://cloud.githubusercontent.com/assets/8178773/21481001/2cb2371e-cb63-11e6-8001-d69b498116b6.jpg)
both cultivator and seeder just continue forward after stopping and lifting the tool.
Harvesters work fine. Could be front/back attached tools problem

**Comment by pops64** [comment]
Add fertilizer Excata EL 700 to the list. With turn on field disabled. The turn around maneuver is behind the tractor and no reverse course is generated. v0.10

**Comment by rkaerner** [comment]
Can confirm the issue for all versions up to 01.00011. Haven't tried with 01.00018 until now, but give it a try. The Combine always doesn't turn until 01.00011 but keeps forwarding until the first collision object and straight try to going forward. No chance to get a combine working like it should. At this moment, please remember my suggestion about combine behaviour (u-turn in-field) because the normal helper will solve it better that cp does it in the past (and now just doesn't do it in any way on any standard map on any field)

Will give it another try with 01.00018 to inform you about the bevahiour soon.

**Comment by Satissis** [comment]
Note: I have not worked on the 3 point turn yet, so the latest updates I have done should not have fixed anything related to those.

**Comment by Satissis** [comment]
Try again with v01.0022 or later and report back

**Comment by AgroWillem** [comment]
Yep, here it's working now fine. Great job! :D
