### ISSUE TITLE
Courseplay not recognizing vehicles that is not using the core game scripts. 

### ISSUE THREAD

**Issue by MikeLowery1974** [Courseplay/courseplay#1538]
Maybe it is me or something I just notice this today. when i use a mod that is not using core game scripts courseplay menu will not show up. I can tab in a in game tractor or truck  and it will show up. Nothing in the log file to tell me anything to give but what i just said. Maybe i am missing something. Sir if you have some info on this i am all ears to hear what you have to say. It could be on my end but i took out all mods, switched mods to see if it was a mod conflict and the same results. Maybe the new patch update threw something off. Thanks in advance.

v/r
Mikelowey

**Comment by Satissis** [comment]
Mods are not supported until it's stable with the vanilla vehicles.

**Comment by MikeLowery1974** [comment]
ah ok thanks for the info... no worries take your time...

v/r
mikelowery
