### ISSUE TITLE
Combine go to waypoint 1 after 2-3 passes

### ISSUE THREAD

**Issue by valdimellen** [Courseplay/courseplay#1539]
Hi.

First Thanks for this great mod..

i have made my own field and used course generation to make a course, i start my FR850 and for som reason it make 2-3 passes and go to waypoint #1 
Log file:
[log.txt](https://github.com/Courseplay/courseplay/files/661779/log.txt)

**Comment by valdimellen** [comment]
![skaermbillede 2016-12-19 kl 19 16 26](https://cloud.githubusercontent.com/assets/11229601/21323881/b20f5142-c61f-11e6-83dd-383ce457e6b7.png)

**Comment by ThomasGaertner** [comment]
did it happen once or can you replicate it ? if yes, would you give me your savegame ?

**Comment by valdimellen** [comment]
it only did it 3 times. i think we can close it here, unless somebody else have seen it.
