### ISSUE TITLE
Question Livestock trailer

### ISSUE THREAD

**Issue by Vanquish081** [Courseplay/courseplay#1541]
Hi, this type trailer no work with mode 1 (load and transport), show issue "this tippers is invalid for this mode"

![Example](http://i.imgur.com/T5GVGDW.png)

**Comment by pops64** [comment]
CP does not support loading pig, sheep or cows. I don't know if its even possible to support this behavior. I would suggest using transfer mode with wait points and loading/unloading manually.

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
