### ISSUE TITLE
Translation to spanish ES

### ISSUE THREAD

**Issue by Vanquish081** [Courseplay/courseplay#1543]
Hi, I look the file translation and see four line without translation, to next write the translation to spanish (Spain ES):

`<text name="COURSEPLAY_SAVE_PIPE_POSITION" 					     text="Guardar Posición Tubería" />`
`<text name="COURSEPLAY_MOVE_PIPE_TO_POSITION"					 text="Mover Posición Tubería" />`
`<text name="COURSEPLAY_NAME_ONLY" 								 text="Solo Nombre" />`
`<text name="COURSEPLAY_NAME_AND_COURSE" 						 text="Nombre y Ruta" />`

**Comment by Satissis** [comment]
@Vanquish081 could you make an fork of courseplay so you have it on your account and then edit the file on your end. Once that is done, make an pull request, so we can merge it in to courseplay on our end.

if you can't figure out how that is done, I'll do it manually but would prefer if we could do it the other way around ;)

**Comment by Vanquish081** [comment]
Complete.

**Comment by Satissis** [comment]
Just remember to make the pull request for us, or else we cant put the changes into our master branch and only you have the changes ;)

**Comment by Vanquish081** [comment]
and now?¿

**Comment by Satissis** [comment]
yep now it's there :). I'll pull it now ;)
