### ISSUE TITLE
Harvest Potates with Grimme SE 260

### ISSUE THREAD

**Issue by pseudex** [Courseplay/courseplay#1546]
I can't get the Potato Harvest to work.
If you use a tractor and the Grimme SE 260 the tractor will start the Maschine but it will not start on the field.

I've recorded this on video: https://youtu.be/pO2lWj4gPkE
If I can supply any more data (logs...) let me know

On youtube I found someone doing this on LS15 and it worked the way I did it in that video.

**Comment by pops64** [comment]
Can confirm log spits out 
```
C:/Users/Ryan/Documents/My Games/FarmingSimulator2017/mods/FS17_Courseplay5/mode6.lua:450: bad argument #1 to 'min' (number expected, got nil)
Error: Running LUA method 'update'.
```

**Comment by pseudex** [comment]
thanks for the hint.
`**if tool.cp.driveOnAtFillLevel ~= nil then**
							if tool.cp.totalFillLevelPercent >= min(tool.cp.driveOnAtFillLevel,99) and tool.cp.hasUnloadingRefillingCourse then
								if courseplay:timerIsThrough(tool, 'emptyStrawBox', false) then
									if tool.cp.abortWork == nil then
										courseplay:setAbortWorkWaypoint(tool);
										courseplay:resetCustomTimer(tool, 'emptyStrawBox', true);
									end
								else
									allowedToDrive = false;	
								end
								if tool.isStrawEnabled and courseplay:timerIsThrough(tool, 'emptyStrawBox', true) and tool.cp.abortWork == nil then
									local strawTimer = tool.strawToggleTime or 3500;
									strawTimer = strawTimer / 1000
									courseplay:setCustomTimer(tool, 'emptyStrawBox', strawTimer);
								end
							end						
						**end**	`

I put an if for NULL around the if in the line 450. now my harvester ist starting and collecting potatoes.
If this is the right fix? I can't tell. I'm a PLC Programmer. Never touched lua before.

**Comment by pops64** [comment]
Or even less complaciated but still down and dirty fix would change line 450 to this
`if tool.cp.driveOnAtFillLevel and tool.cp.totalFillLevelPercent >= min(tool.cp.driveOnAtFillLevel,99) and tool.cp.hasUnloadingRefillingCourse then` Also this is related to #1477

**Comment by pseudex** [comment]
ok. but this only works if the if is not further processed if it is impossible to get the true path.

now I have another problem. The game didn't respond to most of the inputs. I could get out of the tractor but couldn't load the menue (for saving) or anything else. I'm not sure if this is CP related or this is caused by another mod.
But in the logs I have a lot of these entries
`C:/Users/Hermann/Documents/my games/FarmingSimulator2017/mods/ZZZ_courseplay/mode2.lua:231: attempt to index local 'combine' (a nil value)`

in this case I'm not so sure who to dirty fix this :(

**Comment by pops64** [comment]
How did you get your other problem? Same setup because I am not running into any issues with testing just the potato harvester haven't tried anything else. If the game stops responding always try hitting stop driver that sometimes will clear the error and let the game run so you can save and quit propely

**Comment by pseudex** [comment]
If this "input"-Problem occurs I can click in the CP menu. But there is no effect. Seems like most of the inputs are ignored. Had this before. this is not really related to the harvester problem. I just mentioned it, because there were so many log entrys from CP and there seem to be linked to the unloader which should get the potatoes from the harvester.
Now I use the auto-save mod. A least I won't lose to much.

**Comment by pops64** [comment]
The second problem is something to do with mode 2, I am not very familiar with that you would have to wait until Satis or Thomas reads this issue. I would suggest if you can figure out how to reproduce it to create a new issue about it

**Comment by ThomasGaertner** [comment]
please try again with 01.0007 and report. 
@pseudex : I did it thei way to have the possibility to use the self unloading mode, which would have been blocked ....

**Comment by pseudex** [comment]
looks even better than I fixed it. Unloading the machine I had problems with the unloader driving into "traffic" when it was to close. but the unloader needs to drive very close. with your solution this works better
https://www.youtube.com/playlist?list=PLJ4ouFR9OyOQi3WkjCRDHNSsDlvszUJ5A
here are to videos where you can see it in action.
in the second one the unloader is driving into the machine. maybe this is something about the turnsystem. I try to test it with different turn radius.
But this issue can be closed I guess!

**Comment by pops64** [comment]
No both the cheap potato and sugar beet harvester have always been finicky about traffic collisions, The potato more so cause of the way it unfolds when running.. Increase t side offset if you have lots of issues. No more that 0.2m beyond that it wont unload. I find it best if your using the smallest tractor and smallish tipper. The biggest tipper that will work is the fiegel TMK 226 Bull which is now a mod. Not sure about the Joskin trans space.
