### ISSUE TITLE
Suggestion: extended lanes (course generation)

### ISSUE THREAD

**Issue by OldFisher** [Courseplay/courseplay#1549]
Sometimes it is a good idea to make vehicles drive further from field borders. With new turn system (fantastic, superb work, by the way) the need for that is reduced, but not eliminated completely.

It is possible to create custom field borders to achieve that, but having an option in course generator to extend generated lanes by X meters would be so much better. In fact, I created a custom hack-in for CP that takes X from vertical tool offset (it happens when course is generated, not worked on), but it is not good enough for a PR.

On a related matter, I would like to remind another suggestion of mine (which was taken into "suggestion list" and closed). When lanes are generated, path points are probed whether they belong to the field. What I suggested then was probing at lane's left and right sides rather than lane's center, so lanes on fields with oblique edges cover it fully.

**Comment by Satissis** [comment]
With our current system, then no.

Regarding your second question, I'm not following what you mean ?!?

**Comment by SquareCloud506** [comment]
I believe the second question is, when you have a field with a angle edge, and the vehicle moves from the longer row to the shorter row, if the vehicle could start at a point that is adjacent to the longer row end. This would avoid missing sections of a field with an angle edge. 

For me, a single headland cleans up those missed points nicely. The trade off is I end up with rounded corners, but I've learned to live with that, as that's probably more natural than truly right angles on a field.

**Comment by OldFisher** [comment]
One picture is better than thousand words, so here's what I meant:
![cp-lanes-now](https://cloud.githubusercontent.com/assets/4444728/21476303/dbb31626-cb3f-11e6-8070-93979d3f6eca.png)
Currently the lane ends where its centerpoint goes outside of the field.
![cp-lanes-proposed](https://cloud.githubusercontent.com/assets/4444728/21476306/ed0ffc18-cb3f-11e6-9e4e-2de1589d9a4e.png)
I propose that it ends where both lane's sides go outside of the field.

**Comment by gec100** [comment]
that's fine as long as one does not have to stay inside the field.

**Comment by SquareCloud506** [comment]
A single headland will catch the missed spots. The trade off is the corners are rounded.

**Comment by pops64** [comment]
Has said above the A single headland will catch these comers. Closed to keep issues are clean
