### ISSUE TITLE
Control Window

### ISSUE THREAD

**Issue by GroundedOwl** [Courseplay/courseplay#1550]
I have installed Courseplay following the instructions, all apears to have worked it scans the fields on loading the game.

the only issue i have and its abog one is i cant see the window in the top left showing the controls

**Comment by GroundedOwl** [comment]
just in case anyone else is having this issue after fiddling with settings and nothing working i activate a buy field dialogue and that seems to have fixed it

**Comment by Satissis** [comment]
never heard about it, but it sounds more like an Giants bug to me, but cant really tell.
