### ISSUE TITLE
courseplay updater

### ISSUE THREAD

**Issue by fudoido** [Courseplay/courseplay#1551]
so, i was looking for the topic about the updater and couldnt find it.
however, there was an updater working for fs13/15 already, and i decided to give it a try.
with a litle editing, i managed to get it working for fs17 cp v5.

get the updater from fs-uk site: http://fs-uk.com/mods/view/33107
run it once and do as prompted by the updater, pointing fs17 mod file instead if requested. (1st run needed to create necessary files for updater).
if not requested, open the file on updater folder named Courseplay_Updater_Settings.cfg
edit the line with previous fs game mod folder with the path to the fs17 mod folder
something like this: C:\Users\YOURuserNAME\Documents\My Games\FarmingSimulator2017\mods
save, close and run updater again, courseplay mod should be downloaded into the BACKUP folder inside updater folder, already zipped to be moved into mod folder.

**Comment by lcc1211** [comment]
I've used it several times. It has worked perfectly each time. As you would expect, don't run it while playing the game.  Thank you for the work.

**Comment by pops64** [comment]
#1438

**Comment by ian898** [comment]
This is my mod and does work perfectly still in fs17 but as mentioned above it no longer detects if game is running so please run the updater closed I do have a new version available on my website www.cbmoddingteam.weebly.com I am aware of broken links of version on there but as mentioned above download on fs-uk still works perfectly. Thanks

**Comment by fudoido** [comment]
thanks for the update @ian898 i will try to share the new download source among facebook groups. :)

**Comment by ThomasGaertner** [comment]
can we close here ?

**Comment by ThomasGaertner** [comment]
closed to keep the issues clean...
