### ISSUE TITLE
Course generation goes out of control when to much headlands are planned

### ISSUE THREAD

**Issue by breadje** [Courseplay/courseplay#1554]
When you set the number of headlands to high the automatic course generator starts adding strange routes at the end of the course. This is the course of field 22 at Couldborough park with 4 headlands. 
![course generation2](https://cloud.githubusercontent.com/assets/24768303/21473226/f857042a-cb00-11e6-9e2c-efa5854b3328.jpg)
underneath is with 3 headlands
![course generation](https://cloud.githubusercontent.com/assets/24768303/21473223/b4b39256-cb00-11e6-8a98-08cefcc06f3a.jpg)

**Comment by pops64** [comment]
There was another issue about changing the limit on headlands allowed. I believe the above bug is why the headland limit is set at 6. The CP team is currently in the process of updating the headlands generation if you read the beta release issue #1375

**Comment by sootysax** [comment]
you will do better if you record a new edge around the field, with the reverse option checked (so you get closer waypoints when you record), and clicking additional crossing points around the corners (to get even tighter waypoints on the curves) and keeping your corners as gently rounded as possible.   then use that field edge route to generate your fieldwork route with headlands, you will be able to get tighter headlands without big gaps..   but you are still going to be limited to how many headlands you will be able to generate depending on the width of your worktool, the direction of your generated courses and starting point.   you just have to try different combinations of headlands and directions to get the best fieldwork course

**Comment by breadje** [comment]
Yes, I do know how to use courseplay, but thanks for the explanation. I was only reporting the bug, as that is why we are using a beta.

**Comment by sootysax** [comment]
i dont know if its a bug as much as a limitation of the course generator.  Usually it will not allow you to create a course with too many headlands for the field/tool you are using, just returning to "no course loaded" when you try.

**Comment by Satissis** [comment]
Yeah headlands are limited because of that reason. It was limited all the way down to 2 at some point, but was raised to 6 in FS15 I believe.

I'll close this, since it's not something we can do anything about atm, without an whole new headland generator, which is not something I can do I think.
