### ISSUE TITLE
stop during unloading

### ISSUE THREAD

**Issue by gec100** [Courseplay/courseplay#1558]
not working. don't see any errors in the log.

**Comment by SquareCloud506** [comment]
'What' isn't stopping when unloading? A tipper at a silo or sell point? An overloader not stopping when unloading into a tipper? A combine not stopping while unloading on an overload route? A combine not stopping until empty while unloading into a tipper at the end of a row? 

A little more detail would be helpful. :)

**Comment by gec100** [comment]
yes. sry about that. it is a Stop during unloading option for combine to stop, well, when unloading 🗡

**Comment by Tonton1969** [comment]
Hello, I have the same probem when I use courseplay with a combine on a field the unloading activity to a trailer stop in the most cases. With old version this behavior not appear.

**Comment by Beebtrek** [comment]
I clarify this When I have a Harvester unload route stored and in operation, the Tractor unloads harvester then when it gets to 90 - 100 % then proceeds to the silo to unload. But at some random point half way through the unload process it just drives back to the field. Leaving usually about 10 - 30 % in the trailer.

Does this with no mods loaded other than Courseplay. Log seems to show no errors.

Hope this helps. 
Regards Lankspeed.

**Comment by gec100** [comment]
actually, I thought about combine not stopping when tractor with trailer comes to it's side when  stop during unloading option is activated.

**Comment by ThomasGaertner** [comment]
try 014 or higher and report....

**Comment by gec100** [comment]
working fine now. thx :) 
this can be closed now.
