### ISSUE TITLE
Suggestion: u-turn within field borders also for harvesters and combines

### ISSUE THREAD

**Issue by rkaerner** [Courseplay/courseplay#1559]
On some fields of the standard maps (and also of some mod maps) there is not much room between field border and the first building, tree or any other object with collision activated. If I use a combine with a 45 ft cutting unit it happens often, that the u-turn fails because of the fact that the cutting unit hungs on a building, tree or any other object with collision activated.
I would suggest to use the same u-turn behavior used for grubbers, fertilizers or planters: in field. Until now (0037) the switch for u-turn behavior doesn't work for harvesters and combines.

**Comment by ThomasGaertner** [comment]
#1575
