### ISSUE TITLE
shovel the bga

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#1576]
Hey guys
Ladt time i was making silage in the sosnovka bga and cowsilo cp was able to shovel the silage completely out of the silo.
My shovelcourse was in the middle from the silo.
I mean the teleloader drives and load a shovel full from the middle, in the second the TL take silage from the right side near the wall the third time silage was token from the left side near the wall.
And so also: mittle right left mittle right left .......
Yesterday i had also an ready silage and want them shovel from the silo in the bga.
But the TL take the silage only from the middle trom the silage.
He dont take the left and right rest.
Now i have the v 5.01.0001.
I dont know the versionsnumber i had als it went right.
With the v 00036 and 00037 it works also not.
Is this feature out from cp and i need 3 cp courses for one silo (middle left right) 
Or is this a bad configuration myself?

Answer also in german possible

Glg
Andreas

**Comment by rmn18** [comment]
die ´Silos haben alle ne ganz andere funktion bekommen ,das wird noch ne weile dauern das richtig funktioniert.Schaufel Modus wird noch denk ich überarbeitet ,lass mal die Neujahr vorbei sein Satis oder Thomas kucken sich die Baustellen bestimmt noch an .Ist erst mal wichtig das CP auf Vanilla Game stabil wird ,weil Mod Maps oder Mods kommt meist erst später dran wenn CP auf Vanilla stabil funktioniert.

**Comment by andreasthu** [comment]
Naja sosnovka ist ja keine modmap
Der manitu TL und die TL schaufel auch nicht.
Also quasi eh vanilla.
Und vor zwei wochen hat es noch tatellos funktioniert.
Hab da schon öfters silage aus dem kuhstallsilo und dem bgasilo schaufeln lassen.
Der tl ist zum startpunkt dann zum ersten haltepunkt und dann dorthin im silo wo die silage am nähesten zum ersten haltepunkt war.
Hab da leider kein video davon gemacht aber es klappte astrein.
Und nun. D.h. seit gestern fährt der cp schaufler den kurs wieder wegpunkt für wegpunkt ab.
Quasi wie zu ls15 zeiten.
Ev hab ich im hub ja nur ne falsche einstellung drinnen. 
Hab leider keine zeit (bin seit 4wochen nurmehr günstige-gelegenheits-ls17spieler, 2.tocher ist 4wochen alt) und hab auch die alten cp-dev versionen nichtmehr um nachzusehen mit welcher es noch klappte. 
Lg
Andreas

**Comment by andreasthu** [comment]
Hab grade den thread unter pull requests gefunden.
https://github.com/Courseplay/courseplay/pull/1562
Sogar mit video. Da funktionierts genauso wie bei mir früher
Lg
Andreas

**Comment by ThomasGaertner** [comment]
schau mal, ob der wegpunkt nach dem ersten wartepunkt in dem interaction trigger von dem Silo liegt, damit entscheide ich, ob es ein Haufen ist, (den ich auch noch machen werde) oder ein Bunkersilo .
oder teste noch einmal mit debug channel 10 an und poste die log

**Comment by andreasthu** [comment]
super danke, das wars
der haltepunkt war zuweit vom Silo weg.
hab das extra so gemacht, weil der manitu den arm so langsam senkt.
aber war kein problem das zu ändern.
hab einfach in der xml das wait vom wp3 zum wp5 geändert:
`<course>
    <waypoint1 angle="-90.13" speed="0" pos="-630.32 -297.00" crossing="1"/>
    <waypoint2 angle="-90.13" speed="11" pos="-640.33 -297.02"/>
    <waypoint3 angle="-65.91" speed="0" pos="-645.55 -297.04"/>
    <waypoint4 angle="-11.39" speed="9" pos="-650.15 -294.98"/>
    <waypoint5 angle="2.98" speed="9" pos="-651.14 -290.07" wait="1"/>
    <waypoint6 angle="-0.11" speed="12" pos="-650.62 -280.07"/>
    <waypoint7 angle="-0.11" speed="22" pos="-650.64 -270.04"/>
    <waypoint8 angle="-0.12" speed="23" pos="-650.66 -260.00"/>
    <waypoint9 angle="-0.12" speed="25" pos="-650.68 -249.97"/>
    <waypoint10 angle="-0.12" speed="21" pos="-650.70 -239.92"/>
    <waypoint11 angle="-0.13" speed="18" pos="-650.72 -229.85"/>
    <waypoint12 angle="-0.07" speed="5" pos="-650.74 -219.83"/>
    <waypoint13 angle="-0.07" speed="0" pos="-650.74 -219.46" wait="1"/>
    <waypoint14 angle="179.86" speed="0" pos="-650.74 -219.46"/>
    <waypoint15 angle="179.84" speed="24" pos="-650.72 -229.48" rev="1"/>
    <waypoint16 angle="179.83" speed="22" pos="-650.69 -239.51" rev="1"/>
    <waypoint17 angle="179.81" speed="18" pos="-650.66 -249.54" rev="1"/>
    <waypoint18 angle="-179.95" speed="10" pos="-650.62 -259.56" rev="1"/>
    <waypoint19 angle="-179.95" speed="14" pos="-650.63 -269.61" rev="1"/>
    <waypoint20 angle="-179.98" speed="11" pos="-650.64 -279.63" rev="1"/>
    <waypoint21 angle="176.68" speed="3" pos="-650.64 -289.64" rev="1"/>
    <waypoint22 angle="153.49" speed="8" pos="-650.53 -291.64" rev="1"/>
    <waypoint23 angle="120.81" speed="10" pos="-649.63 -293.44" rev="1"/>
    <waypoint24 angle="106.73" speed="8" pos="-647.88 -294.48" rev="1"/>
    <waypoint25 angle="92.66" speed="11" pos="-645.96 -295.06" rev="1"/>
    <waypoint26 angle="78.50" speed="10" pos="-643.93 -295.16" rev="1"/>
    <waypoint27 angle="38.11" speed="9" pos="-641.96 -294.75" rev="1"/>
    <waypoint28 angle="9.36" speed="4" pos="-640.72 -293.18" rev="1"/>
    <waypoint29 angle="0.20" speed="4" pos="-640.40 -291.20" rev="1"/>
    <waypoint30 angle="-1.27" speed="5" pos="-640.39 -289.19" rev="1"/>
    <waypoint31 angle="179.35" speed="0" pos="-640.50 -284.24" rev="1"/>
    <waypoint32 angle="179.36" speed="11" pos="-640.39 -294.24"/>
    <waypoint33 angle="179.36" speed="0" pos="-640.34 -298.42" wait="1"/>
    <waypoint34 angle="-0.46" speed="0" pos="-640.34 -298.42"/>
    <waypoint35 angle="7.88" speed="6" pos="-640.36 -296.41" rev="1"/>
    <waypoint36 angle="31.81" speed="9" pos="-640.08 -294.39" rev="1"/>
    <waypoint37 angle="56.63" speed="10" pos="-639.02 -292.69" rev="1"/>
    <waypoint38 angle="74.28" speed="10" pos="-637.32 -291.57" rev="1"/>
    <waypoint39 angle="93.99" speed="10" pos="-635.39 -291.03" rev="1"/>
    <waypoint40 angle="104.78" speed="10" pos="-633.36 -291.17" rev="1"/>
    <waypoint41 angle="120.51" speed="13" pos="-631.39 -291.69" rev="1"/>
    <waypoint42 angle="121.78" speed="10" pos="-629.64 -292.72" rev="1"/>
    <waypoint43 angle="115.49" speed="13" pos="-626.15 -294.88" rev="1"/>
    <waypoint44 angle="99.14" speed="12" pos="-624.31 -295.76" rev="1"/>
    <waypoint45 angle="82.83" speed="8" pos="-622.31 -296.08" rev="1"/>
    <waypoint46 angle="-97.62" speed="0" pos="-620.75 -295.89" rev="1"/>
    <waypoint47 angle="-97.62" speed="1" pos="-625.94 -296.58" crossing="1"/>
</course>
` 
hier noch ein bild dazu:
![cp_bga](https://cloud.githubusercontent.com/assets/24860501/21582479/872b8e02-d059-11e6-86da-2ae570499eb1.png)

dank für die schnelle und tolle hilfe auch am Feiertag
und btw, Frohes neues Jahr
und macht weiter so, top job,
ohne euch hätte ich ls15+17 nicht so lange und gerne gespielt
lg
andreas

**Comment by pseudex** [comment]
I have modified the getMode9TargetBunkerSilo function so that it will search for more than one point to find the silo. You might want to have a look at it @ThomasGaertner 

[getMode9TargetBunkerSilo.txt](https://github.com/Courseplay/courseplay/files/681218/getMode9TargetBunkerSilo.txt)

**Comment by ThomasGaertner** [comment]
yea the  reason why I did that is, that when the tractor goes backwards, it doesn't follow the waypoints but takes  wait 1 as target. if this point is too far away or not alligned with the silo, then we will get in trouble ....

**Comment by ThomasGaertner** [comment]
what's the status here ? can we close ?

**Comment by andreasthu** [comment]
Von meiner Seite aus schon. 
K.a. wie es bei pseudex aussieht.
Lg
Andread

**Comment by pseudex** [comment]
im prinzip ist das thema klar. der erste punkt nach dem [P] muss im Silo sein.
Das Problem was ich damit aktuell noch habe ist, dass ich das [P] gerne 5-10m Weit vom Silo weg mache, damit auch die vorderen Ecken erreicht werden. Das birgt aber die Gefahr, dass der erste Punkt nicht im Silo ist. (Obwohl mit CourseDrawer zu ändern)
In meinem Zweig werde ich daran fest halten, auch in den weiteren Punkten nach dem Silo zu suchen.
Zum Zurückfahren könnte man vielleicht erst zum virtuellen Mittelpunkt vom Silostart fahren und dann auf [P]

**Comment by ThomasGaertner** [comment]
#1422
