### ISSUE TITLE
Course generation

### ISSUE THREAD

**Issue by redrummed1** [Courseplay/courseplay#1579]
would it be possible to have the course follow the direction of the fields longest edge when you course generate, looks like way too many turns the way it is now,

![fsscreen_2017_01_02_15_50_24](https://cloud.githubusercontent.com/assets/23707135/21593423/d521d8ea-d10e-11e6-88c7-c6a80e5dbfef.png)

The map is Coldborough Park Farm by Bullit Bill

**Comment by SquareCloud506** [comment]
I think somebody already suggested this before.

I don't know how well courseplay could find the longest edge on mod map fields like this, but instead perhaps an option in the course generator that allows a starting direction between 0 and 359, where 0 is North, 180 is South, etc. It could include some presets for eight standard directions, N S E W NW SW NE SE. I think this could make CP field course generation more versatile.

**Comment by redrummed1** [comment]
good idea, hopefully it will be implemented at some stage,

 Another question off topic but when I am using combi mode where there is no trigger,Example: like dumping chaff near a silo and push it in with a loader because there is not enough room for a combi mode tractor to make a turn coming out of the silo, is there a work around this?

**Comment by pops64** [comment]
Are you talking make heaps any where. That has also been suggested. You could just drive through the silo and level it when your done filling

**Comment by redrummed1** [comment]
yes heaps anywhere, on Coldborough Park Farm the silo has a back wall and the turn is too tight  when the tractor is reversing into the silo, it hits the trigger early and the turn out of the silo is tight, so heaps anywhere would be good,
Or maybe a option could be put in on a waypoint where it empties until it reaches  0%, like when filling a manure trailer when it drives off at 100%

**Comment by pops64** [comment]
Closed has the first suggestion has been suggested. Second suggestion has been implemented.
