### ISSUE TITLE
shovel mode crash after barricade hit

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#1580]
hey, found another bug :P 
So, when i am shoveling out of a full silo, the wheelloader sometimes drives himself into the wall of the silo and after a short period of spinning the wheels, he reverses out of the silo, shortly after the game hangs up and the log is full of the following error:

```
Error: Running LUA method 'update'.
C:/Users/nitro/Documents/My Games/FarmingSimulator2017/mods/zzz_Courseplay/drive.lua:636: attempt to index a nil value
Error: Running LUA method 'update'.
C:/Users/nitro/Documents/My Games/FarmingSimulator2017/mods/zzz_Courseplay/drive.lua:81: attempt to index a nil value
Error: Running LUA method 'update'.
C:/Users/nitro/Documents/My Games/FarmingSimulator2017/mods/zzz_Courseplay/drive.lua:81: attempt to index a nil value
Error: Running LUA method 'update'.
C:/Users/nitro/Documents/My Games/FarmingSimulator2017/mods/zzz_Courseplay/drive.lua:81: attempt to index a nil value
Error: Running LUA method 'update'.
C:/Users/nitro/Documents/My Games/FarmingSimulator2017/mods/zzz_Courseplay/drive.lua:81: attempt to index a nil value
Error: Running LUA method 'update'.
C:/Users/nitro/Documents/My Games/FarmingSimulator2017/mods/zzz_Courseplay/drive.lua:81: attempt to index a nil value
Error: Running LUA method 'update'.
C:/Users/nitro/Documents/My Games/FarmingSimulator2017/mods/zzz_Courseplay/drive.lua:81: attempt to index a nil value
Error: Running LUA method 'update'.
C:/Users/nitro/Documents/My Games/FarmingSimulator2017/mods/zzz_Courseplay/drive.lua:81: attempt to index a nil value
Error: Running LUA method 'update'.
C:/Users/nitro/Documents/My Games/FarmingSimulator2017/mods/zzz_Courseplay/drive.lua:81: attempt to index a nil value
Error: Running LUA method 'update'.
C:/Users/nitro/Documents/My Games/FarmingSimulator2017/mods/zzz_Courseplay/drive.lua:81: attempt to index a nil value
Error: Running LUA method 'update'.
C:/Users/nitro/Documents/My Games/FarmingSimulator2017/mods/zzz_Courseplay/drive.lua:81: attempt to index a nil value
Error: Running LUA method 'update'.
C:/Users/nitro/Documents/My Games/FarmingSimulator2017/mods/zzz_Courseplay/drive.lua:81: attempt to index a nil value
Error: Running LUA method 'update'.
C:/Users/nitro/Documents/My Games/FarmingSimulator2017/mods/zzz_Courseplay/drive.lua:81: attempt to index a nil value
Error: Running LUA method 'update'.
```

**Comment by piratqwert** [comment]
Strange, becouse I use this mode 10 hours and I don`t have any problem

**Comment by piratqwert** [comment]
only
the width of the shovel is 6.3 6.4....

**Comment by JDTiger** [comment]
it happens when the silo is completely filled... i think the loader tries to get to silage on the very edge and compensates too much, therefore hitting the wall...
But it shouldn't lock up the game beacause the driver hit the silowall...

**Comment by kizzard** [comment]
I also experienced this lock up several times yesterday. After manually emptying the first few meters of the silo, it stopped happening, so I would agree that indeed having a full silo is a possible precondition for it. Immediately before the lock up I saw 'Front loader is slipping', indicating that it was colliding with the bunker wall. I was not able to gather logs though.

**Comment by pseudex** [comment]
can you tell us the version number @JDTiger 
ThomasGaertner has changed the file lately because of the new mode 10.

you can also test a version I've made to improve the shovel mode. #1562
full zip: https://github.com/pseudex/courseplay/archive/master.zip
mode9.lua: https://raw.githubusercontent.com/pseudex/courseplay/master/mode9.lua

you can either use the full zip file like on the main git repo or download mode9.lua and zip it into your couresplay mod zip file

**Comment by kizzard** [comment]
This happened again today a few times and my logs show the same as JDTiger. The following is repeated many times:

drive.lua:81: attempt to index a nil value
Error: Running LUA method 'update'.

I experienced the lockup with both versions 5.00.00036 and 5.01.00003

I will try your test version when possible. thank you.

**Comment by JDTiger** [comment]
will try your version, version in wich the problem occurs is the newest available... (5.01.00004)

**Comment by JDTiger** [comment]
tried and got the same error

**Comment by ThomasGaertner** [comment]
could U give me a savegame to test it I don't have one atm

**Comment by JDTiger** [comment]
[savegame1.zip](https://github.com/Courseplay/courseplay/files/683081/savegame1.zip)

Here is the savegame, the easternmost silo is the one creating the problem, also included is my course to empty it...

**Comment by ThomasGaertner** [comment]
thanks, would you please check the course, it's the wrong one

**Comment by JDTiger** [comment]
will do...sry, read the index file wrong :P 
here is the correct one:

[courseStorage0009.zip](https://github.com/Courseplay/courseplay/files/683151/courseStorage0009.zip)

**Comment by ThomasGaertner** [comment]
I fixed it and added the work width setting to the shovel settings screen. if the shovel is too close to the wall, increase the work width a bit and it should work better

**Comment by JDTiger** [comment]
ok, thanks

**Comment by JDTiger** [comment]
works perfectly now...

**Comment by rmn18** [comment]
thank alot for your hard work ,perfekt :)
