### ISSUE TITLE
iconSprite.dds is blurred since 5.01.00001

### ISSUE THREAD

**Issue by rkaerner** [Courseplay/courseplay#1581]
I do not know what happened to that nice sharp one which had worked very fine until .00037, but the one you've inserted since .01.00001 is absolutely fuzzy. Please replace it with the old, sharp one.

**Comment by ThomasGaertner** [comment]
I know why, I changed the .dds in the wrong manner. I will as Satis to make it nice and clean, and also to fix the too small hud extension for the page buttons....

**Comment by rkaerner** [comment]
thank a lot in advance.

**Comment by ThomasGaertner** [comment]
could you make a screenshot , it looks good for us....

**Comment by jhomer** [comment]
I have noticed this as well in the past. All the little square icons are a bit blurry. Everything else looks crisp. Think it will be hard to see in the picture, everything seems to look blurry!!!
### Courseplay: initialized 39/39 files (v5.01.00011)

![fsscreen_2017_01_04_21_27_24](https://cloud.githubusercontent.com/assets/7943994/21668214/4a74893c-d2c5-11e6-930f-928406b8f15d.png)

**Comment by jhomer** [comment]
Just a trial, I opened the iconSprite with paint.net and turned up contrast 100% then resaved DXT5 with no mip maps which seemed to come out nice and sharp.
Here's a pic of that.

![fsscreen_2017_01_04_21_42_00](https://cloud.githubusercontent.com/assets/7943994/21668444/7b09ecc0-d2c7-11e6-8f00-135368f4a7d1.png)

**Comment by ThomasGaertner** [comment]
i've done the same. hmm . can you give me your .dds ?

**Comment by jhomer** [comment]
Don't know if this works for file upload but here is the edited one.

[iconSprite.zip](https://github.com/Courseplay/courseplay/files/688643/iconSprite.zip)

**Comment by ThomasGaertner** [comment]
I'm very sorry, but i can't see any difference there
![comparision](https://cloud.githubusercontent.com/assets/3279913/21711095/23cea1e0-d3ed-11e6-8869-e0570db93456.png)

could anyone else test it?

**Comment by jhomer** [comment]
Your right, I seen no difference with your image either.
I thought I'd try it one more time to make sure I didn't flub anything up.
- I downloaded most recent version
- took screenshot
- did same paint.net edit and took another screenshot
and still get blurry/sharp images
I have not a clue but unless it has something to do with aspect ratio?

Here is this test. . . . . . . . .
![iconsprite](https://cloud.githubusercontent.com/assets/7943994/21737436/3ee102c4-d43e-11e6-9655-b2582b0b9ae0.png)

**Comment by rkaerner** [comment]
Thomas, please visit the ottico of your fiducia. The icons are still blurry (01.00018) on 1920x1200 (yes, 16 to 10 monitor here) There is a really remarkable difference between the version where it had been sharp and the version I am claiming about. It is really impossible to see no difference between the named versions.

**Comment by ThomasGaertner** [comment]
OK i pushed your file, please test again now ....

**Comment by jhomer** [comment]
Looks good on my end.

![untitled](https://cloud.githubusercontent.com/assets/7943994/21745063/3feedc4a-d4e8-11e6-9504-e36783c31a42.png)

**Comment by rkaerner** [comment]
Great job! Thank you very much for the work on that.

**Comment by ThomasGaertner** [comment]
would you be so kind to try with 0032 or higher ? we changed something there....

**Comment by jhomer** [comment]
Hud looks good for me. I see you added the dump waypoint. Nice!!
