### ISSUE TITLE
v01.0011 - Error: Running LUA method 'mouseEvent' in mode 4

### ISSUE THREAD

**Issue by mawie** [Courseplay/courseplay#1593]
Since updating CP from v01.00010 to v01.0011 I'm getting the following error when starting a CP driver (mode 4 - NH T7 with Horsch Pronto 9 DC):

`Error: Running LUA method 'mouseEvent'.
C:/Users/Username/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/toolManager.lua:510: attempt to perform arithmetic on field 'attacherJointToPivot' (a nil value)`

**Comment by InCuBuS77** [comment]
Hey CP Team,

same Problem for me. But with Amazone Condor.

great work so far... keep it up :)

**Comment by Pitufo306** [comment]
Is it corrected in version v01.0014 ??

**Comment by Satissis** [comment]
no. it will be corrected in my  next push. it will most likely be v01.0016

**Comment by Satissis** [comment]
try v01.0016 or later and report back
