### ISSUE TITLE
Horch Pronto 9 DC not working in v 0011 and 0012

### ISSUE THREAD

**Issue by Karlshoj** [Courseplay/courseplay#1596]
I have updated from v 006 to v0011 and v 0012, however in 11 and 12 I am not able to start the Horch Pronto 9 DC seeder. In v 006 it worked fine. I have not tried the versions between 6 and 11.

**Comment by pops64** [comment]
#1593

**Comment by Satissis** [comment]
try v01.0016 or later and report back

**Comment by Karlshoj** [comment]
Now running v0016. All good thanks
