### ISSUE TITLE
Failed to open xml file version 5.01.00012

### ISSUE THREAD

**Issue by Ragnaroek1848** [Courseplay/courseplay#1598]
Hi CP-Team,

i have this error in my log 

Error: Failed to open xml file 'C:/Users/Ragnaroek/Documents/my games/FarmingSimulator2017/mods/ZZZ_courseplay/modDesc.xml'.
Error: Missing descVersion attribute in mod ZZZ_courseplay

can anyone help me please?

Ragnaroek

**Comment by badfly** [comment]
in modDesc.xml,  2 line:
<modDesc descVersion="34">
change it to 
<modDesc descVersion="32">
it helped me)

**Comment by pops64** [comment]
update your game to 1.3.1 https://www.farming-simulator.com/updates.php?lang=en&country=us

**Comment by Satissis** [comment]
beside the above, I believe you are missing the modDesc.xml in your ZZZ_courseplay folder or zip.
This can be due to not extracting the zip file from here and reziping the files correctly.
take a look at this guide: http://courseplay.github.io/courseplay/en/installation/index.html

**Comment by Ragnaroek1848** [comment]
@badfly i have not change the modDesc to lower version i have downloaded the the 00012 version the 00016 version come 4h later

@pops64 my game is already on the latest version i look 2 times in the week for new LS17 updates

@Satissis the modDesc wars not failing i have make a fail i have forgot to change in the zipsetting from rar to zip sry for this litle mistake from me thanks for you nice help you can close this issue
