### ISSUE TITLE
2x and 4x buttons suggestion

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1602]
Sorry for making another issue cause I know you guys are busy. But it would be really nice if the working width in course generator page would have a 2x and 4x button to make multiple vehicles a little bit easier to setup up. This also leads to my other suggestion a 1/2 and 1/4 button using the automatic workwidth calculator(or if the course workwidth is stored some were accessible using that instead) for lane offset but that is a little more complicated cause you also need a left or right button or toggle(mabye if you hit 1/2 the first time it goes right and if you hit again it goes left. 1/4 could have 4 options 2 for the left lanes and 2 for the right). Also a zeroing button for lane offeset. It would also be cool if you had a suggestion box too :D Thanks for reading. Keep up the great work

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
