### ISSUE TITLE
5.01.00016 does not work with the seeder Horsch Pronto15m, version 5.00.00036 works.

### ISSUE THREAD

**Issue by badfly** [Courseplay/courseplay#1604]
Sorry for my English, I use google translate.
In mode 4 (fertilizer and seed), when "turn on the field - off", It does not takes place in the end of the field, and going straight.. When "turn on the field - on", its works correctly.
seeder https://www.modhoster.com/mods/horsch-pronto15m

**Comment by krookoo** [comment]
Mods are not supported yet.

**Comment by Satissis** [comment]
As @krookoo said, mod is not supported until vanilla stuff is working.

Going to close this to clean the issue list
