### ISSUE TITLE
Problem with Mode 6 and Terra Dos

### ISSUE THREAD

**Issue by bigjoker76** [Courseplay/courseplay#1611]
Good morning gentlemen,
I currently testing the mode 7 (CP Version 18) with the TerraDos harvesting sugarbeet with a heap at the field.
1st setup: Harvester working with helper, driving to heap with coursplay mode 7. 
Problem 1: harvester drives with turning speed (adjusted to 10 km/h) to the point where the unload course starts, after unload he drives back to the point to restart with fieldwork speed.
Problem 2: After unloading and driving back the harvester lowers the tool too early, helper sees no sugarbeet to harvest and turns direction like at the field border

2nd setup: Harvester working with courseplay mode 6 combined with unload course
Problem 1: Harvester works with 4 km/h.  CP speed fieldwork set to whatever doesn´t change. Seems to be caused by drive control mod, when removing, speed goes to 12.
When reaching first waitingpoint (of two) on unloading course he stops with message "overloading point reached".

Sometimes it happens, that the harvesters when he reaches full bunker starts driving backwards circles and don´t stop. he is trying to reach a point which he don´t reach.

Best regards Jochen

https://www.dropbox.com/s/gcnlq3a3573dy6y/log.txt?dl=0

log attached

**Comment by pops64** [comment]
Heaps any where are only implemented in mode 7 at this time. Drive control support will wait until after CP is out of beta. Everything else you will have to wait until Thomas or Satis responds

**Comment by ThomasGaertner** [comment]
in v. 0021 I've fixed the cricling backwards and hopefully the turning on too early. For the speed issue, try again with debug channel 21 active and make a screenshot of the situation when it happens.
the mode 6 self unloading making heaps is on ur TODO list and will be implemented anytime...

**Comment by bigjoker76** [comment]
Ok...circling backward looks ok now. Turning on too early is still there when field speed (going from heap to working point) is too low. I think, the look ahead area for the helper should be bigger.
Driving speed to and from the heap depends on, if the starting point for the unload course is within the field or not. Within, everything is ok. Outside, slow speed driving to heap.

Thank you for the quick response and help

**Comment by ThomasGaertner** [comment]
hmm , could you make the screenshot with debug channel 21 active ?

**Comment by bigjoker76** [comment]
When exactly should I take the screenshot?

**Comment by bigjoker76** [comment]
New tests...
Pic 1 : Slower speed leaving field to heap
https://www.dropbox.com/s/94u7mxvher00roh/fsScreen_2017_01_15_16_15_15.png?dl=0

Pic 2: Faster (normal?) speed back from heap to resume fieldwork
https://www.dropbox.com/s/jr6wx9hy47d6pw6/fsScreen_2017_01_15_16_17_06.png?dl=0

Unload course starts and ends within fieldborder

Right now harvesters turns again direction when resuming fieldwork as on an fieldborder :-(

**Comment by pops64** [comment]
Closed #2909
