### ISSUE TITLE
Sapling planter

### ISSUE THREAD

**Issue by AlphaXray** [Courseplay/courseplay#1612]
Anyone else seen issues with the sapling planter Damcon pl-75? 

CP does not recognize when it's empty and continues to run the course without planting anything. Implement still on thou. 
I assume it should work as a normal seeder? 

Also get an notification by the game: "Helper H has stopped work unexpectedly - tank is empty!" 
You get this notification as soon you start the worker, even with loaded pallet in the planter. 

Using cp 5,01,XXX6 

Tested with v.XX19

Almost the same issue. Worker does not stop/run refill course when tool is empty.

**Comment by SunkenL** [comment]
Can confim this! happend to me a few days ago. Dont remember what version i was on though..
I planted poplars and made a route for filling from a trailer with pallets on. I enabled "helper buy seeds" to plant the field fully..
Had the same problem with the largest sprayer also but havent tested it on later versions.

**Comment by Satissis** [comment]
The sapling planter not working is on our todo/tracker list, so we are aware of it :)

**Comment by lcc1211** [comment]
I get that same error message when using the New Holland SP400f sprayer except it does keep spraying, but won't follow CP settings to go to a refill point.  Has anyone else experienced it?

**Comment by ThomasGaertner** [comment]
test .0053 and report...

**Comment by pops64** [comment]
Can we close here?

**Comment by Flitch49** [comment]
Tested this as this seems to be hanging about waiting for an answer. Set up a plant and refill course with vanilla equipment and map. Planted trees and refilled with fresh pallet of saplings as expected with no problems.

So my guess is ... Yes we can close.
