### ISSUE TITLE
Oh, come on, what happened to the seed mode?

### ISSUE THREAD

**Issue by rkaerner** [Courseplay/courseplay#1614]
Until 01.00011, everything had been fine when spaling with Amazone Condor.  From 01.00011 on, the seeding with Amazone vondor leaves HOLES in seeding. And I am not talking abaout "a little bit of the field not seeding". I have reduced the former used speed (20 km/h when utirning, 10 km/h backwards) to the orginal values. But I have massive hole when seeding with amazone condor. Before 01.00011 everything had been fine, so please take a look about what you've changed. I would be very thankful for seeding behavior before 01.00011

Ralph

**Comment by pops64** [comment]
Picture, log?

**Comment by holbe** [comment]
It`s happened to me to, but only with mod traktor and not with `game` tractor.

**Comment by holbe** [comment]
I know courseplay not ready for mod, just testing out some different things. Great job guys

**Comment by ThomasGaertner** [comment]
Oh, come on, can't you post a proper description ?
https://github.com/Courseplay/courseplay/wiki

**Comment by Satissis** [comment]
Try again with v01.0022 or later and report back

**Comment by rkaerner** [comment]
Okay, it seems that you demand more details. So let's give it a second try.

Map: Goldcrest Valley (standard)
Vehicle: Case IH Magnum CVX with Amazone Condor 150001 (standard)
behavior before 01.00011: stop at field border, straight backwards, uturn in field with moving a way forward, then going backwards direct to field border in snake line but reaching the field border exactly in 90 degree.
behavior since 01.00011 (even with the version I pulled just a few minutes before: 01.00021): stop at field border, straight backwards, uturn in field with moving a way forward, then going backwards direct to field border in snake line and unable to fit the field border in 90 degree. Because of that it wents forward seeding in a snake line until it reaches the track.
I guess that you've shortened the way forward after uturn and therefor the way backwards to the field border is just way to short for the Amazone Condor. I guess that because with the same tractor using a Maestro 12 SW everything is absolutely fine.
![stop_after_backwards](https://cloud.githubusercontent.com/assets/8012047/21752703/84d8a08e-d5dd-11e6-9260-863e32429f55.png)
![coming_back](https://cloud.githubusercontent.com/assets/8012047/21752706/897461d2-d5dd-11e6-9e1d-7b33c08176e8.png)
I hope it is now clearer for you, what my little problem is and I apologize for not to be that detailed in my first try.

**Comment by Satissis** [comment]
Try 01.0023 or later and report back
I cant reproduce this. I have the exact same equipment as you do, but it could be due to the latest change I did.

**Comment by rkaerner** [comment]
"or later" is a funny thing for someone who is only able to do a "git pull" ;-) Just pulled the .00023 and will give it a try today in the evening (0:02 here now). I will edit this post after trying, so keep the "waitingForUserAnswer" till that, please.

**Comment by Satissis** [comment]
we always say or later/newer if some one made a new push before you were reading it :)
