### ISSUE TITLE
Ploblem with mode 7

### ISSUE THREAD

**Issue by Lupo36** [Courseplay/courseplay#1616]
Hello, when i unload the combine in mode 7, then i can't exit the game.

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Lupo36** [comment]
[https://1drv.ms/t/s!AsCJ7cYOQ2RdkhkC9mzRD0NYaVGk](url)

log attached

**Comment by Lupo36** [comment]
https://1drv.ms/t/s!AsCJ7cYOQ2RdkhkC9mzRD0NYaVGk

log attached

**Comment by ThomasGaertner** [comment]
try again with v01.0021 or higher , should be fixed there....

**Comment by Lupo36** [comment]
Thank you, now works perfectly.
