### ISSUE TITLE
UPK Triggers

### ISSUE THREAD

**Issue by WMModding** [Courseplay/courseplay#1617]
Are UPK Trigger supported? If not will they be supported in the future? If yes can you guys tell me how to setup the trigger to be used with CP.

Looking forward to your answer,
W&M Modding

**Comment by pops64** [comment]
#889. They were though I do not know though if they made the transition to FS17

**Comment by ThomasGaertner** [comment]
I did a quick and dirty test  with version 17.0.9 and it worked likely. There where issues while tipping but it can be the placeable which i used for the test. So the trigger was in our TipTrigger table , had been recognised and the tractor tipped at the right place...

**Comment by WMModding** [comment]
The problem i have is not recognizing a filltrigger, i made a placeable UPK silo thats keeps creating random chaff out of nothing( works better when testing maps) but courseplay doesnt know that the trigger is there.

it would be awesome if you guys would know what the problem is ? 

Looking forward to your asnwer,
W&M Modding

**Comment by ThomasGaertner** [comment]
for which mode do you want to have this filltrigger ? we are looking for filltriggers for fuel, seed, manure, liquidmanue and fertilizer but not for chaff, could you describe your intension ?

**Comment by pseudex** [comment]
Before I managed to make silage with the bunkers I used an UPK Silage Silo mod (http://modho.st/32X7).
Unloading gras was no problem at all. Worked like any other unload trigger. Loading silage was a bit harder. If your trailer is under the pipe it only unloads if you jumped into the tractor. I solved the issue with conveyors. Once every savegame load you need to jump into the first one. But from then on it will push what ever is in the silo.
I think it is a problem with the (UPK) mod. I have a barn mod where both filling and emptying trigger are working properly.

**Comment by WMModding** [comment]
im building a placeable chaff silo thats creates chaff out of nothing sort of like the buy all fruit silo but then just for chaff. if you guys think its easier i can upload for you guys.

**Comment by ThomasGaertner** [comment]
yea , send it if you want. But for the first Idea it would see it in loading at start point mode. doesnt it overload automaticly if there is a trailer under the pipe ?

**Comment by WMModding** [comment]
it does load the trailer if you drive it under the pipe yourself. as CP transport mode seems to not see the trigger there it just stops and doesnt load, it starts loading when you stop driver let it load and put the driver back on. Download link : https://mega.nz/#!jhsWAASK!3X4Iy_eM4-Zp36hxUSqND5maVNCluuubbW9BLWpO_bs    link works for 24 hours.

**Comment by WMModding** [comment]
Download link : https://mega.nz/#!jhsWAASK!3X4Iy_eM4-Zp36hxUSqND5maVNCluuubbW9BLWpO_bs 

it loads if you drive the trailer under the pipe yourself.

**Comment by WMModding** [comment]
i closed it by accident btw little bit of a fight with my internetbrowser

**Comment by Raints** [comment]
Not sure which version did change it, but in version 026, 027 it tractor wont stop for loading. Just tips the trailer and keep driving. Will go back to version 023, since this latest version I have and all worked with this one. 

Mod I have problem with: http://www.fsmods17.com/silage-silo-upk-v-0-4-fs-17/

**Comment by Frodo65** [comment]
J

Am 14.01.2017 11:30 vorm. schrieb "Raints" <notifications@github.com>:

**Comment by ThomasGaertner** [comment]
@WMModding : I tried your mod but couldnt get it running ingame : 
Error: Failed to open xml file 'C:/Users/Tommi/Documents/My Games/FarmingSimulator2017/mods/buyable_chaff_silo/silo_fertilizer.xml'.
Error: No storeData found in 'C:/Users/Tommi/Documents/My Games/FarmingSimulator2017/mods/buyable_chaff_silo/silo_fertilizer.xml'. StoreItem will be ignored!
Error: Failed to open xml file 'C:/Users/Tommi/Documents/My Games/FarmingSimulator2017/mods/buyable_chaff_silo/silo_seeds.xml'.
Error: No storeData found in 'C:/Users/Tommi/Documents/My Games/FarmingSimulator2017/mods/buyable_chaff_silo/silo_seeds.xml'. StoreItem will be ignored!
Warning: Invalid category 'placeable' in store data C:/Users/Tommi/Documents/My Games/FarmingSimulator2017/mods/buyable_chaff_silo/silo_chaff.xml! Using 'misc' instead! (C:/Users/Tommi/Documents/My Games/FarmingSimulator2017/mods/buyable_chaff_silo/silo_chaff.xml)
Error: Failed to open xml file 'C:/Users/Tommi/Documents/My Games/FarmingSimulator2017/mods/buyable_chaff_silo/silo_maize.xml'.
Error: No storeData found in 'C:/Users/Tommi/Documents/My Games/FarmingSimulator2017/mods/buyable_chaff_silo/silo_maize.xml'. StoreItem will be ignored!
Error: Failed to open xml file 'C:/Users/Tommi/Documents/My Games/FarmingSimulator2017/mods/buyable_chaff_silo/silo_silage.xml'.
Error: No storeData found in 'C:/Users/Tommi/Documents/My Games/FarmingSimulator2017/mods/buyable_chaff_silo/silo_silage.xml'. StoreItem will be ignored!
Error: Failed to open xml file 'C:/Users/Tommi/Documents/My Games/FarmingSimulator2017/mods/buyable_chaff_silo/silo_tmr.xml'.
Error: No storeData found in 'C:/Users/Tommi/Documents/My Games/FarmingSimulator2017/mods/buyable_chaff_silo/silo_tmr.xml'. StoreItem will be ignored!
Error: Failed to open xml file 'C:/Users/Tommi/Documents/My Games/FarmingSimulator2017/mods/buyable_chaff_silo/liquidFertilizer.xml'.
Error: No storeData found in 'C:/Users/Tommi/Documents/My Games/FarmingSimulator2017/mods/buyable_chaff_silo/liquidFertilizer.xml'. StoreItem will be ignored!

**Comment by pseudex** [comment]
Did you install the UniversalProcessKit?
http://wiki.universalprocesskit.de/index.php?title=UniversalProcessKit

**Comment by ThomasGaertner** [comment]
as posted above , yes

**Comment by WMModding** [comment]
i have it running fine in my own game, i will reupload one i guess i uploaded the wrong one.

**Comment by WMModding** [comment]
https://mega.nz/#!mgVXHRbK!3X4Iy_eM4-Zp36hxUSqND5maVNCluuubbW9BLWpO_bs  here you go the one from my mods folder this one schould work

**Comment by Blackmankot** [comment]
@pops64 I suggest also close it for cleaning.

**Comment by pops64** [comment]
Collapsing mod issues into one thread. #2231
