### ISSUE TITLE
Suggestions for Mode 10

### ISSUE THREAD

**Issue by bigjoker76** [Courseplay/courseplay#1619]
Gentlemen,
some thinking about improvements for mode 10
- Stop for vehicles approaching only for vehicles driving in mode 1,2 or 6. Because a loader emptying a silo nearby will also be influenced
- Tractor with shield slipping 100% when pushing chaff. Is it possible to raise the shield by 10...20...30 cm when detection of slipping?

Regards Jochen

**Comment by ThomasGaertner** [comment]
yea , this has been dicussed in #1568 . If I get the time I will make improvements on this mode ...
I will close here to keep the issues clean ....
