### ISSUE TITLE
Issue/Suggestion: Start course at first/nearest point

### ISSUE THREAD

**Issue by Numenor65** [Courseplay/courseplay#1620]
When starting a course at the first (or nearest) point, very often the tractor reaches the starting point and then starts running in circle, because reaching the 2nd point would require too sharp a turn for it to perform.
It would be nice if the tractor could reach the starting point from the right direction, or maybe it could head toward the starting point and gradually turn to the second point (without actually reaching the first).
To explain better my problem (and the suggested solutions), pleas look at [THIS IMAGE](http://s25.postimg.org/o15fyk9wf/Immagine1.jpg), where the red line is the actual (endless) course, the green line is a good solution for the "Start at first point" courses, and the blue line is more suitable for the "Start at nearest point" courses.

**Comment by pops64** [comment]
I know your picture the blue line was the behavior most of the time in FS15 because the 3rd waitpoint is placed far enough away to allow most tractors to make the turn to the 3rd way point with out doing doughnuts. I think there was some change to FS17 that makes CP pick there first way point more often.

**Comment by Numenor65** [comment]
Thank you for your prompt reply. Actually, this happened to me quite frequently in FS15, too. In both FS15 and FS17 the problem occurs several times per game session.
Here is a [SCREENSHOT](http://s25.postimg.org/cf8rdimfz/Immagine2.jpg) that shows the tractor behaviour: in green, the starting position of the tractor; in red the "doughnut" (also clearly visible on the ground) and in blue the path that I would expect the tractor to follow.

**Comment by lcc1211** [comment]
I second Numenor65 on that.  I spent a lot of time manually lining up the vehicle to help it avoid doing the never ending circle.

**Comment by pops64** [comment]
Mergeing this into #2327
