### ISSUE TITLE
[solved - implemented in 01.0027] Water delivery on Sosnovka.

### ISSUE THREAD

**Issue by einnet** [Courseplay/courseplay#1621]
Hello group.

Does somebody has any luck with transporting water in current version of courseplay? In my case courseplay stops tractor near water tower, but never fill it in. It correctly detects unload point though.

Thank you for your work and time. FS is unplayable without it. :)

**Comment by pops64** [comment]
My guess is that the water tiggers changed in FS17 and the CP team has yet to updated this portion of CP

**Comment by einnet** [comment]
It may seem that way, in gigants editor I do not see any sort of trigger like on unload site.

**Comment by pops64** [comment]
I miss spoke. The water fill trigger didn't change the unload triggers are new and CP is not scripted for animal water triggers it was scripted for the green house and mod triggers. In the short term this fix will fill from a water trigger but will wait to unload at the unload point. Comment out lines 459,460 and 461 in start_stop.lua
```
--elseif vehicle.cp.workTools[1].cp.isWaterTrailer and courseplay.triggers.waterReceiversCount == 0 then
				--courseplay:setInfoText(vehicle, 'There are no water triggers on this map'); -- TODO i18n
				--return false;
```

**Comment by einnet** [comment]
Indeed, commenting those lines fixes loading problem, but in manure mode course play doesn't want to unload it now. To sum it up: problem exist in "grain transport" mode, in that case unloading works, loading not (tractor just waits). In "manure transporter" mode, after commenting above lines loading works, but tractor stops on unloading point and doesn't unload water.

![unload_problem](https://cloud.githubusercontent.com/assets/25014569/21782333/58d37fbe-d6b3-11e6-8fa2-dc844b2744cb.jpg)
![unload_problem1](https://cloud.githubusercontent.com/assets/25014569/21782367/75f78f9a-d6b3-11e6-9430-3727333c2c40.jpg)

**Comment by pops64** [comment]
Yea. I edited mine just as you comment. Its up to Thomas if he wants to add the water fill trigger to mode 1 or edit mode 8 for the unload trigger

**Comment by einnet** [comment]
Thank you for your time.

**Comment by lcc1211** [comment]
I hope Thomas will do this.  I would very much like to automate the water delivery since it has been made a part of the game by giants.

**Comment by ThomasGaertner** [comment]
I decided to make it in mode8. I also allowed up to 10 unloading points for water trailers to make a "water delivery chain" possible. the setup for the husbandries and the placeables is different, but I set them up to the same behavior: you need to set a wait point to every unloding point you want to unload, even if it's a husbandry trigger... test v 0027 or higher and report

**Comment by lcc1211** [comment]
I'll test it tonight after I get back home from work.  Thank you very much, Thomas.

**Comment by lcc1211** [comment]
I ran this course through several maps (custom and standard) and it works very well. I only ran across one error on a modded map where I can see the trigger for a water trough, but CP ignored it.  I may have put the way point too far forward, though.  It worked just find on the in game maps, though.  I used the standard tractors and the standard water tank.

**Comment by einnet** [comment]
It works perfectly in 01.0027 @ Sosnovka. Thank you Thomas. I don't know if it's intended, but it does not work in  01.0029. Thanks you once more. :)

**Comment by lcc1211** [comment]
I'm going over to my Sosnovka map and give it a go.

**Comment by lcc1211** [comment]
I just tried it on Sosnovka with .0029 and it it working for me.  Here's the video:  https://gaming.youtube.com/watch?v=w_N_nS8KUUo&feature=share

**Comment by ThomasGaertner** [comment]
So does it work with 0029 or not ? Downgrading the version is not an option . If not , please describe the situation...

**Comment by lcc1211** [comment]
My video link above is with it working in 0029.  Maybe einnet could post a log from the game?

**Comment by einnet** [comment]
Hmm, maybe I messed something up, I'll test it again, thank you Icc1211.

**Comment by pops64** [comment]
I know the water trigger is really narrow and if you miss CP will just skip the wait point. Make sure the unload is showing in the help menu when you place the waitpoint otherwise your not in the trigger
