### ISSUE TITLE
Mysterious holes in chaff heaps.

### ISSUE THREAD

**Issue by AgroWillem** [Courseplay/courseplay#1623]
During Filling silos with the WIP-method in GCV the following occures.
During filling/levelling "holes" form in the chaff-heap.
See attached pictures. You can see 2 holes.
Seeing from above you can see a square empty concrete spot where NO chaff can be deposed. **Not even manually with a shovel.**
It keeps empty.
This cause naughty bumps from the tractor and sometimes it leaves the track or stops.
Every time i fill the silo, the empty space occurs at the same spot.
Is this an error in the trigger or in CP? 
The map is the standard FS17 GCV-map.

![2017-01-11 13_55_18-greenshot](https://cloud.githubusercontent.com/assets/23076511/21849701/6d36bf16-d807-11e6-81f3-5d571ef11645.png)
![2017-01-11 13_56_29-greenshot](https://cloud.githubusercontent.com/assets/23076511/21849702/6d38aa7e-d807-11e6-9512-5a23224dd978.png)

**Comment by JDTiger** [comment]
Its a problem, that the trigger/ heap has...
also occurs without CP afaik...

The interesting thing is, that the hole has a different position for every player...

**Comment by KalasKonrad** [comment]
I got that  problem after using conveyor. and to fix it  i used the roller for removing feilds. i can't say if its a base game bug or a mod. but i had the problem Before CP

**Comment by AgroWillem** [comment]
Thx for the tips. I'll try out.

**Comment by AgroWillem** [comment]
@KalasKonrad 
Are you using the roller at the same time with the blade or instead of the blade?
I how it works? Just drive a couple of times over it?

**Comment by Shotgunface** [comment]
AgroWillem he may be refering to the RABAUD Supernet 2200A which removes fields, loose material, tire tracks, or the R5000 which removes fields, They would be used without the blade and preferably with a emptier silo.

**Comment by AgroWillem** [comment]
Ok thanks! ;)

**Comment by KalasKonrad** [comment]
I was using the Lizard R5000 roller in an empty silo. but i have just seen that i did not get them all. i was lazy so i was using conveyor through the wall . and i Think i got a sink hole in the wall :(
![20170112215303_1](https://cloud.githubusercontent.com/assets/25062046/21907853/a551cdc2-d911-11e6-9932-3326efdb61ad.jpg)

**Comment by ntrrlz** [comment]
I have had the same problem. It is not a courseplay bug, but a Farm sim bug. I fixed it by going over that spot with the Rabaud sweeper. What I do now is when I have emptied a silo is run trough it with the sweeper to make sure this doesn't happen. I have never had this problem since.

**Comment by AgroWillem** [comment]
This topic can be closed.
After sweeping all looks fine.

**Comment by Satissis** [comment]
I'll close it then.
I can give you an info directly from Giants as well.
Thomas asked them about it, and they said they knew about it and should be fixed in v1.4 patch, when that gets out.
