### ISSUE TITLE
Dump at Waiting Point

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1624]
At some point I think you're going to have to create an option to trigger unloading of a trailer at a waiting point..  I want to deliver silage to the BGA from my main farm and have a conveyor belt setup to load the silage into the sell point.   The best I can do with Courseplay at this point is create a waiting point at the conveyor belt and have the tractor wait indefinately at that point, stop CP and manually unload the silage and then restart my course back to the main farm.  With 800,000l of silage to sell, I would love to have CP run unattended.  (unless there is another way to what I am trying to do?)

**Comment by ThomasGaertner** [comment]
we will discuss it by chance... 
btw: what about the other issues, we are waiting for your answer ?

**Comment by ThomasGaertner** [comment]
#1137 

![fsscreen_2017_01_14_21_51_15](https://cloud.githubusercontent.com/assets/3279913/21958016/2955ad26-daa4-11e6-9b77-fd501169cb94.png)

**Comment by sootysax** [comment]
you guys are the best...

im in the middle of renovating my rental property, but i'll try and get on to test some of the other issues soon

**Comment by pops64** [comment]
Can't wait :D only thing keeping me from doing potatoes and sugar beets.(that and I am lazy don't like doing things manually :D)

**Comment by sootysax** [comment]
did this get removed from later versions?  not seeing it in .0031

**Comment by Satissis** [comment]
It's still an WIP so it's not on github yet ;) Thomas was just showing what we are planing visually :P

**Comment by ThomasGaertner** [comment]
OK so it's online with v .0032. 
 record the course, set a unload point where the tipper should tip:.  
- while reversing it will tip exactly at this place, 
- while driving forward, it will tip on the height of the unload point.
- free tipping is possible in mode 1 and 2 in this version, other uses must be tested.....

**Comment by sootysax** [comment]
will dump silage on a point driving fowards, but when reversing to the point just sits and does not dump..

https://gist.github.com/sootysax/f53a61b8818e1c9c3bbf0a82fb031dc5

**Comment by ThomasGaertner** [comment]
could you do it  again with debug 13 on ?

**Comment by sootysax** [comment]
https://gist.github.com/sootysax/9b4cf881cd7ca36089c11cbf25b8de46  DEBUG 13

**Comment by ThomasGaertner** [comment]
yea, epic fail :-(  0034....

**Comment by pops64** [comment]
Would it be possible to include the unload point as part of the stop at last point or next trigger function? Thx for this great update :D

**Comment by sootysax** [comment]
working great now
