### ISSUE TITLE
Removed Courseplay from MOD Vehicles

### ISSUE THREAD

**Issue by PlumbersCrack** [Courseplay/courseplay#1627]
Updated to the latest version of courseplay and now the Krone Big M cannot be operated with courseplay.  It was working perfectly fine before and now when I right click or Ctrl+Del it won't even open the Courseplay console.  Anyway I can reactive it if it was deactivated or just something going wrong on my end?  Thanks.

**Comment by pops64** [comment]
Rename courseplay folder to ZZZ_Courseplay5 this works for the holmer terra #1525 but other than that CP mod support is on hold until CP is released

**Comment by Satissis** [comment]
@pops64 mod support is not on hold until release, but until we go into the mod phase of the beta, so mods should be supported on release.

**Comment by pops64** [comment]
Alright, sorry about that. Just remembering what you CP beta release post stated.

**Comment by SquareCloud506** [comment]
Interestingly, I forgot to change 'courseplay-master' to 'ZZZ_Courseplay', and CP wasn't loading with any map. Simply changing the name fixed the problem, but I was surprised that not changing the name would effect the loading of the mod in that way.

**Comment by ThomasGaertner** [comment]
closed to keep issues clean ...
