### ISSUE TITLE
DRIVINGLINE SPEC in FS17_ProSeed

### ISSUE THREAD

**Issue by gotchTOM** [Courseplay/courseplay#1628]
Hi,

i would like to tell you that there has been a name change of a variable:

> self.currentDrive

 has been renamed to 

> self.currentLane

Greets gotchTOM

**Comment by ThomasGaertner** [comment]
???

**Comment by gotchTOM** [comment]
mode 4 of courseplay doesn't supports "drivingline" specialization of ProSeed.
Please change the name of the variable "currentDrive" to "currentLane" in your script. Thanks

**Comment by SquareCloud506** [comment]
I'm confused. Is this a request to change the variables of CP so they match this mod? 
http://farming-simulator.com/mod.php?lang=en&country=us&mod_id=64561&title=fs2017

**Comment by Viper525** [comment]
I read this the same way. It's a little bold, isn't it?

**Comment by gotchTOM** [comment]
You are right. 
CP supports the drivingline spec in FS 2013. 
At this time one of the CP developers asked me to report any changes in the future. That is what i have done.
So, why should that be bold?

I can´t remember the name of the developer... obviously it wasn´t ThomasGaertner.

**Comment by Satissis** [comment]
It might either have been @JakobTischler or @horoman but never mind that, I had an look in the code and yes it's there, so I'll update it when I'm home tomorrow ;)

**Comment by ThomasGaertner** [comment]
yea I agree , there's no reason for bad mood . its in the script explicit for this mod since jan 2014. 
I changend it and ready.....

**Comment by Viper525** [comment]
Sorry, I didn't meant to bother anybody. I think I didn't understand the details here. I thought it's a parameter that change would have more consequenses in the courseplay system. My fault!

**Comment by gotchTOM** [comment]
No problem, all good. I should have given some more information. I think it was Jakob Tischler, so you could know nothing about it. And Jakob is probably no longer involved in the development.

Thank you very much for the change! I hope everything is working as it should
