### ISSUE TITLE
Lemkin Gigant Plowing Error

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#1638]
On the Sosnovka map, field 18 using the Gigant and the JCB Fastrac 8000, CP is skipping sections at the end of each lane.  
[log.txt](https://github.com/Courseplay/courseplay/files/705721/log.txt)
Log attached and link to the video is here:  https://youtu.be/WmrEX3yvB1I 

I reported this earlier, but it started working again. This is the first time I've used it for the last several version of CP.

**Comment by kyfarmer** [comment]
I have the same issue on GCV using that cultivator.
I have found a work around is to start it, then when it gets a few meters into the field, stop it, then start it from the nearest waypoint then it will do the rest of the field correctly.
Video using the workaround: https://youtu.be/6bjLhWWA2_I?t=33m49s
This part of the video, I forget to do the workaround: https://youtu.be/6bjLhWWA2_I?t=39m30s 
Here is the point that I realized I forgot to use the workaround: https://youtu.be/6bjLhWWA2_I?t=42m6s 
In the video, I’m using 5.00.00036 but today I updated to V5.01.00025 and I have the same issue.

**Comment by Satissis** [comment]
I can reproduce this, So I'll have an look into it :)
Looks like the initialized start and end markers are not calculated correctly the first time around.

**Comment by Satissis** [comment]
try with v01.0029 or newer and report back

**Comment by lcc1211** [comment]
That worked very well this time. Thank you for the quick turnaround time on this.  I tested with several tractors and got the same great results. I only tested it on the Sosnovka map though.  If you like I can do it on GCV as well, if you think it is necessary.

**Comment by Satissis** [comment]
no that's not necessary since it's not map related but an setup problem, which is fixed :)

I'll close here.
