### ISSUE TITLE
Field-less maps cause error loop at map start if you choose auto scan.

### ISSUE THREAD

**Issue by Shotgunface** [Courseplay/courseplay#1640]
I by mistake had courseplay scan a FDR logging map with no fields and had to force quit because I could not bring up the in game menu. 
Courseplay v5.01.00025
I was on FDR Arctic map.
 I moved all my other mods to another folder, only courseplay and the map were enabled.
![20170115031531_1](https://cloud.githubusercontent.com/assets/25081828/21961192/5c86b352-dad1-11e6-9e22-3e1cc127b74f.jpg)
[fs 17log.txt](https://github.com/Courseplay/courseplay/files/706473/fs.17log.txt)

**Comment by Satissis** [comment]
try v01.0030 or later and report back

**Comment by Shotgunface** [comment]
v5.01.00031
Similar reaction, can bring up menus and quit now without forcing, but can not get the progress window to close.
[log.txt](https://github.com/Courseplay/courseplay/files/711310/log.txt)

**Comment by Raints** [comment]
Maybe best solution for you is in savegame folder/courseplaySettings file <courseplayFields automaticScan="**true**" onlyScanOwnedFields="**true**".  Turn **true** to false.

**Comment by Shotgunface** [comment]
I'm not having a issue where it scans everytime without my request Raints I'm just pointing out a bug for the devs. Now that you can go back to the main menu without force quitting it isn't as big of a issue as I was having in 5.00025.

**Comment by Satissis** [comment]
arh I thought I forgot something :P I'll disable the scan window as well :)

**Comment by Satissis** [comment]
Should be fixed in v01.0037.
I haven't tested it, since I am not using mod maps atm but it should work :)

**Comment by pops64** [comment]
Question. Would it be possible to add a button into the hud to trigger auto scan? just wondering not super important save and quit achieves the same effect. Just annoying when you expand the field to have to do this.(I don't want to use the calculate field tool has this saves the field which if I am not mistaken makes the field size permanent unless you calculate the field again and save it)

**Comment by Shotgunface** [comment]
You are correct the progress window closes now and I had no problems continuing. I'd say bug squashed!

**Comment by Satissis** [comment]
@pops64 if you only calculates the current field, it should not save anywhere unless you specific tels it to save it/overwrite and existing field, so it should still have the standard field definition if not saved and you select it in the generation tab.
