### ISSUE TITLE
Frontmähwerk und Ladewagen - Wende

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#1642]
HAllo liebe CP-Entwickler

mir ist grade aufgefallen, nachdem ich Gras mähe mit frontmähwerk und direkt angehängtem Ladewagen, das wenn ein kurs generiert wurde (mit kombiniertem abfahrkurs), nur hinundher, ohne vorgewende, das frontmähwerk erst ausgehoben wird wenn der ladewagen am wendepunkt ist.
d.h. das mähwerk mäht ca 10-15m lange schwaden außerhalb des definierten feldbereiches, die liegenbleiben und nicht aufgesammelt werden.
könnte man dasso machen das das frontmähwerk schon aushebt sobald der wendepunkt erreicht ist?

lg
andreas

**Comment by lcc1211** [comment]
Kannst du das bitte auf Englisch schreiben, weil nicht alle kann Deutsch sprechen oder lesen.

**Comment by andreasthu** [comment]
Hello dear CP developer

I have just noticed, after m grass mowing with front mower and directly attached wagon, which when a course was generated (with combined departure), only to and fro, without Vorwende, the front mower is only lifted when the loading truck is at the turning point.
I. The mower mows about 10-15m long winds outside the defined field area, the remaining and not accumulated.
Could one make that the front mower already as soon as the turning point is reached?

Lg
Andreas
(Google translator)

**Comment by ThomasGaertner** [comment]
#1483
