### ISSUE TITLE
Tip Triggers

### ISSUE THREAD

**Issue by jiggin** [Courseplay/courseplay#1645]
Hi Guys, Firstly, Courseplay is the BEST!! you guys ROCK!!

I have been trying out the new Bunker Mode, but have come across a little issue.

the leveller is awesome and works fine, but my tractors with the chaff in pull up to the silo, as recorded, set to reverse. they back up to the silo, hit the tip trigger, stop, unload a little and stop. I'm guessing it's because the unload area is full. my course is recorded much further back into the silo, and it still stops at the entrance. 

I'm thinking I am doing something wrong, and looking for advise!!

many thanks

James

**Comment by Raints** [comment]
I think it really depends what trailer you use and what is its capacity. Because capacity of the silage is limited. I'm using in game equipment and have no problems. Or you should set blade height lower to have more room for chaff.

**Comment by lcc1211** [comment]
Raints, what level are you setting your blade height?

**Comment by Raints** [comment]
@lcc1211  Since I use reverse filling, blade height is 0,3 or 0,2.

**Comment by lcc1211** [comment]
Thank you. I had mine set a bit higher, but maybe your settings will work better.

**Comment by jiggin** [comment]
please disregard my original. we have found an issue with the build of the bunker silo's.
