### ISSUE TITLE
Feature request: Countdown timer

### ISSUE THREAD

**Issue by flattopc** [Courseplay/courseplay#1646]
Hello,

I apologize if I put request this in the wrong place. I am unfamiliar with Github and its terminology. I am also not a programmer, and have respect for those of you who build Courseplay!

I have a feature request - is it possible to create a countdown timer for a given course? For example, if I am going to be plowing a large field, it would be nice to know about how long I had to go get a cup of coffee. I would think this would be relatively easy to calculate based on the known driving speed and course length, but perhaps it is more difficult than I imagine.

Realistically, it wouldn't have to be super-accurate. Just a "less than a minute" left would be helpful.

And when a course was set to repeat, you could say something like "3:37 until end point" or something.

Thanks again to everyone who works on this mod! You make Farming Simulator much more enjoyable for me!

**Comment by aBerek** [comment]
Hello Guys,

I would like to suggest another feature:
Would it be possible to create another countdown which let us to set how many times should the equipment do its course.
For example: planning to sell wheat for a mill, but dont want to sell the whole amount. So I give an order for the truck to follow the route only 3 times, then it stops?

Max respect for your work. CP makes FS a real management simulator. Without it FS would be quite annoying.
Thx

**Comment by ThomasGaertner** [comment]
@flattopc : I liked the Idea. I implemented it into the HUD in v 01.0040

![fsscreen_2017_01_20_21_50_21_a](https://cloud.githubusercontent.com/assets/3279913/22165751/b5cc89b0-df5d-11e6-98a8-2e62b0fae2ea.png)

test and report , note that the correct time will be calibrated to the turn times after the first turn. 

@aBerek : your idea is already in our suggestions box

**Comment by pops64** [comment]
One thing that would be nice is for it to clear out when the work is done or stop driver button is hit or a change of mode
![farming simulator 17 1_20_2017 8_41_31 pm](https://cloud.githubusercontent.com/assets/10678220/22170825/df488e5e-df50-11e6-81e1-a95c032a4227.png)

**Comment by ThomasGaertner** [comment]
you are right.  0041....

**Comment by saku05** [comment]
https://www.youtube.com/watch?v=iu02s0LZl8E

**Comment by pops64** [comment]
Closed to keep the issue area clean
