### ISSUE TITLE
bale wrapper won't turn at north end of field

### ISSUE THREAD

**Issue by kyfarmer** [Courseplay/courseplay#1648]
I've been having an issue where when I'm using Courseplay to control the bail wrapper, it won't make the turn at the north end of the field. It will just keep driving until it gets stuck on something. I'm using stock equipment on field 11 on Goldcrest Valley.  
I have a video where I encounter the issue: https://youtu.be/HT39M8czpD8?t=32m15s
RDAllen was having the same issue in this video: https://www.youtube.com/watch?v=Kj7dlv33i3Q

**Comment by pops64** [comment]
Log? Debug 12 and 14 with only the bail wrapper driving. Picture of the turn

**Comment by kyfarmer** [comment]
Okay, I made a new video in a fresh test game on the stock map with stock equipment the only mod I had running was Courseplay. With debug 12 and 14 running, I noticed something interesting, I was running the wrapper with turn on field enabled, at the north end of the field, you would see the path show up but the tractor would ignore it and just drive off. Then on the south side of the field it would do a "turn off field".

When I disabled turn on field, it started to do the turns at the north end correctly.

Here is a video, with direct links to each "event"

Here is where I set up the course for the wrapper: https://youtu.be/-Q_u2KDINcE?t=15m59s
Here is where I start the wrapper: https://youtu.be/-Q_u2KDINcE?t=24m24s
First trip into the drink: https://youtu.be/-Q_u2KDINcE?t=29m14s
First turn at south end of field: https://youtu.be/-Q_u2KDINcE?t=37m50s
Second failed turn: https://youtu.be/-Q_u2KDINcE?t=37m50s
Second turn at the south end of field: https://youtu.be/-Q_u2KDINcE?t=37m50s
Good turn at north end with turn on field deactivated: https://youtu.be/-Q_u2KDINcE?t=37m50s

**Comment by Satissis** [comment]
I believe I know what the problem is, so I'll look into it tomorrow I think :)

**Comment by kyfarmer** [comment]
Thanks, after watching the two turns, it seems like turn on field would be a bad idea, because you don't know if the baler dropped a bale right at the edge of the field. In general, I think I'll just always opt to disable turn on field for both the baler, wrapper and collector.

**Comment by pops64** [comment]
Turn on field is disabled in the CP's code for the bale wrapper(Bale wrapper is offset so it would be interesting to watch CP try to back the bale wrapper). So it shouldn't even be trying to do it.

**Comment by kyfarmer** [comment]
Kinda like watching a Fendt 900 mow in reverse drive? :-)

**Comment by saku05** [comment]
https://www.youtube.com/watch?v=iu02s0LZl8E

**Comment by Satissis** [comment]
It was easy to reproduce, so it should be fixed now in v01.0042

Try it out and report back :)

**Comment by kyfarmer** [comment]
Fix works! Cheers.
