### ISSUE TITLE
Problems with fabrikscript triggers

### ISSUE THREAD

**Issue by Nielsen362** [Courseplay/courseplay#1651]
I have a storage with fabrikscript there is no errors but when i use courseplay for unloading, i get this error scripts/FabrikScript.lua:1326: attempt to compare number with table and everything stops, i have tryed with different trailers with out luck. I have asked hte creator of fabrikscript, but when everything is working without courseplay the problem is not on there side.
thank in advance
Nielsen

**Comment by Akoasma** [comment]
#1573

**Comment by Nielsen362** [comment]
Thanks now it works :+1:

**Comment by lcc1211** [comment]
Looks good on my end as well. My fix was getting the latest mod with the updated script.

**Comment by Satissis** [comment]
Closing to clean up Issues
