### ISSUE TITLE
Mode 5 - Transfer and Reverse driving

### ISSUE THREAD

**Issue by Akoasma** [Courseplay/courseplay#1652]
Hello.
Is it possible to enable the reverse driving ability in Mode 5?

**Comment by Satissis** [comment]
Done :)

**Comment by Akoasma** [comment]
WOW! Thank you very much :)

**Comment by Akoasma** [comment]
Oh, in Mode now LIA call stack and it did not match the last Waypoint. Mode 1 no problem.
`LUA call stack:
  =C:/Users/Ralf/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/drive.lua (1533) : printCallstack
  =C:/Users/Ralf/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/drive.lua (922) : setCollisionDirection
  =C:/Users/Ralf/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/drive.lua (847)
=C:/Users/Ralf/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/base.lua (840) : drive

https://gist.github.com/Akoasma/d3f42050401ce137ff1b694b71967685`

Thanks in advance. Or should i open a new Issue? Hmm :\

**Comment by Satissis** [comment]
hmm what were you doing when that happened ? what setup did you have (tracto, trailer, tool and so on)

**Comment by Akoasma** [comment]
Setup is on a Custom-Map. Tractor is a Series 7, Trailer a Trans-Space 8000, both vanilla.
Course has 34 WP,  from Start a straight, simple Line, than reverse and turn.

Course: https://gist.github.com/Akoasma/5e50fae2da09f6afa8d9080ef9093330
Log; https://gist.github.com/Akoasma/ee8d2a4202dfa23894d4df5f94a1fd6d

Line 2 - 12
Mode 6, drives ok, Result COURSEPLAY_REACHED_END_POINT / COURSEPLAY_WORK_END

Line 14 . 49
Mode 5, at last WP did not stop,  COURSEPLAY_SLIPPING_WARNING

Line 51 - 79
Mode 1, at last WP did not stop,  COURSEPLAY_SLIPPING_WARNING

Without Trailer, in Mode 5, the Tractor stops before last WP and the Error appears in the Log.

**Comment by Akoasma** [comment]
Mode 6, with Trailer, other Tractor (Valtra T), are ok
![fsscreen_2017_01_19_02_48_15](https://cloud.githubusercontent.com/assets/25203292/22090467/169a4df8-ddf2-11e6-80a2-a27eb732b534.png)

Mode 5 with Deutz-Fahr Series 9 + Trans-Space 8000, slipping
![fsscreen_2017_01_19_02_58_39](https://cloud.githubusercontent.com/assets/25203292/22090653/6aff00ae-ddf3-11e6-8e84-2e850fd72477.png)

same in Mode 6, ok
![fsscreen_2017_01_19_03_02_45](https://cloud.githubusercontent.com/assets/25203292/22090716/d6e3595a-ddf3-11e6-985e-65ec3f3c2bb3.png)

Mode 5, solo Tractor
![fsscreen_2017_01_19_03_06_29](https://cloud.githubusercontent.com/assets/25203292/22090919/5f16e530-ddf4-11e6-9ca2-48849c442738.png)

**Comment by Satissis** [comment]
I'll check it out a bit later :)

**Comment by Satissis** [comment]
I just had a extra look at the images you posted.

You are using the mode 5 incorrectly, since it will go from the stop point to the start point, which is why it continuing reversing further back and causing the slipping. The only real thing you can do in that situation is reverse back and then place an waiting point, then change the direction to forward again and drive a bit forward again before stopping the course. The best place to stop the course if right behind the starting point.


Now a question regarding the errors in the log, were they from when you were reversing with the trailer or with the tractor only in mode 5 ?

**Comment by Akoasma** [comment]
Thanks for explaining Mode 5. I had make a mistake there.
The Errors in the log are in both cases, but nowaday i can not reproduce it. It occurs or not.
When it occurs and i make the same thing again, it doesnt. I have no Idea ir Clue, how to reproduce the error. Version was .40.

Thanks fpr your Time and work, I close here and if i find a way to reproduce it reliable i make a new Issue.
Greetings.
