### ISSUE TITLE
Fermenter Tip Trigger

### ISSUE THREAD

**Issue by cpoole2005** [Courseplay/courseplay#1655]
Using the large in game krone TX 560 D when it comes up to the tip trigger of [http://www.modhub.us/farming-simulator-2017-mods/fermentieren-silo-v2-0/](url) the back gate will open and the game will sound like the trailer is emptying, but nothing comes out some times I can stop driver and manually empty the trailer other times the game crashes.

**Comment by Akoasma** [comment]
This Mod is using the "FabrikScript". See #1651

**Comment by cpoole2005** [comment]
Thank you Akoasma
