### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Lupo36** [Courseplay/courseplay#1658]
Hello, here is an improvement suggestion:
It would be nice if there was a key combination for "driving further".

**Comment by pops64** [comment]
? by driving further you mean what

**Comment by Lupo36** [comment]
mode 1 and mode 4 driver drive further (driving continue).

**Comment by pops64** [comment]
Left Ctrl Num Pad 8. Mislabeled or bugged in the key description #1664

**Comment by Lupo36** [comment]
Thanks for info.

**Comment by Satissis** [comment]
Already fixed as shown in #1664
