### ISSUE TITLE
Chaff unloading question

### ISSUE THREAD

**Issue by Shotgunface** [Courseplay/courseplay#1661]
I've noticed that if the trailer doesn't finish unloading by the time the workers at the end of the bunker the worker will continue on his way while continuing to dump . I solved this by adding a waiting point. Is there a way to change the unloading drive speed that I may have overlooked? Another solution might be adding a wait until empty option for the wait point so you dont have to guess around with the timing. I thought I remember it back in v4.01 as "BGA unload speed"

**Comment by pops64** [comment]
Discussed in #1568 when driving through silo you had two modes. Drive while unloading. And stop and go unloading(which if i remember would dump a little move forward a bit and dump again. Then repeat until done)

**Comment by pops64** [comment]
Could we get a picture or video of this and log with debug channel 1,2 and 19 thanks

**Comment by pops64** [comment]
Closed due to inactivity
