### ISSUE TITLE
Loading courses Undo

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1663]
So when I settle into a certain map, I create course segments and do most of my Courseplay using combined routes..

This winds up needing to combine several segments for each journey, and inevitably I make a mistake and need to delete the whole thing and start over again from the beginning..

it sure would be handy to be able to undo loading the last course segment I loaded and being able to correct my mistake.

**Comment by Satissis** [comment]
not sure if it's possible with the current system, since I haven't really seen how this is done when loading multi courses.
I'll have a look at it at some point.

**Comment by pops64** [comment]
Added to tracker. Closed to keep issues area clean
