### ISSUE TITLE
Left Ctrl num pad 8 bug

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1664]
Unless I am doing something wrong. Left Ctrl num pad 8 which is supposed to activate stop at next point or trigger(according to the description) doesn't seem to do anything. 7 and 9 both work. Log is clean. Thanks for reading

P.S I was looking through the key controls and was wondering what num pad enter does it says in the description secondary menu accept.

**Comment by tjb8907** [comment]
Left Ctrl + Num Pad 8 is for the continue button that shows up when the vehicle is stopped at a waitpoint. 

Also I think the secondary menu accept is for the save course window.

**Comment by pops64** [comment]
The second one would make sense(but why does it specify num pad enter because rl enter works just as well). If the first one is true then why does the key description say activate next stop?
![farmingsimulator2017 64bit 1_19_2017 4_41_48 pm](https://cloud.githubusercontent.com/assets/10678220/22127371/a79b28fa-de69-11e6-8828-e9c708d82614.png)

**Comment by sootysax** [comment]
i brought this up months ago in #1404

**Comment by pops64** [comment]
Yea. Ill close this out then. I didn't look hard enough I knew someone brought it up just couldn't remeber. Thanks

**Comment by Satissis** [comment]
I just had an quick look at it and the description is incorect, since after what i can read in the code, that keybinding is only for continuing from a wait point. there is actually no keybinding for stopping at last point or trigger.

I'll have an look into this and maybe change it to an multi button, so if it's used to set to stop at last point or next trigger, it will be changed to drive now instead. that way we only need one button and keybinding for the same function :)

**Comment by Satissis** [comment]
So in v01.0045 I have made some small changes to the keybindings.
The default ctrl + numpad8 is still doing what it was setup to do, which is continue a course if it's at a waiting point and just waiting.
I have then added a new keybinding to toggle the stop at last point or next trigger. It's not mapped to any keys, so you will have to do that your self.

### NOTE: the way giants have done there code, the new key binding option will not show unless you do one of the following:
1. **Not Recomented:** Reset all you keybinding (Meaning you will lose all your current setup.)
2. **Recomented:** Go into your key setup, chose a key and remap it to something else. Save the keys and reload the game. Now the new keybinding is showing in your list. Remember to go back and remap the key you remaped before, back to what it was at. (This way you won't lose any of your current key setup)

**Comment by pops64** [comment]
Works great thanks.

**Comment by pops64** [comment]
I forgot to mention. You didn't change the behavior of the stop at next trigger? Cause know if your in the trigger and you double click to deactivate it by accident. It won't move forward any more. If my memory isn't failing me you could activate this function inside a trigger and deactivate it and it would still move forward. Doesn't do this anymore(Or mabye there is a timer I have to wait on). Thanks
