### ISSUE TITLE
Mod Support Fase!!

### ISSUE THREAD

**Issue by Satissis** [Courseplay/courseplay#1667]
Thomas and I had an chat the other day and we decided that once the major fixes for the new turn maneuvers are fixed, we would start slowly opening up for mod support again.

Well most of the turning bugs are now fixed, there is new implementations and cool stuff that don't really have any bugs in them, it's time.

Do note that even that we now have opened up for mod support, anything that regarding the vanilla equipments will be first priority.

Also if you find an bug with an mod, try see if you can replicate it with vanilla equipment as well, so we would be able to see if it an mod related bug or both vanilla and mod.

**Comment by lcc1211** [comment]
Outstanding!  Perfect timing I would say.

**Comment by mB-PiBox** [comment]
How about instead of supporting 3rd Party mods, you work on making CoursePlay available for multiplayer/servers. I would think this would more of a priority over mods.

**Comment by staanla** [comment]
As there's no real "comment" section:

Thanks a lot for your continuous work on the mod. It is a very nice thing to see commited people getting together to help.

--May be removed after reading--

**Comment by pops64** [comment]
Closed to keep the issues area clean.
