### ISSUE TITLE
Grime Rooster 604 Issuses

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1669]
I remember reading some where that this was problem but couldn't find it or is listed under another issues or was marked closed. Sorry for the double post. But for the Grimme Rooster it seems that initial calculation sends out 3.1m should be 4.4m which it does calculate but seems random if it gets it right. Thanks for reading.

Also it seems this same havester no longer moves the tipper over by 3 or 4 lanes when the tipper goes to park like it did in 15

**Comment by pops64** [comment]
Close this out its related to #1425

**Comment by Satissis** [comment]
hmm maybe, but that issue is closed, so it might be an idea to leave it here

**Comment by ThomasGaertner** [comment]
try v.0070 or higher and report for the parking position , check log with channel 4 active, there should be a line with "harvesterAttachable bla" ...

**Comment by pops64** [comment]
Ok the offset is fixed thanks for that :D I thinking the parking spot is fine. But now I have different. With Giants AI the pipe isn't unfolded until the tipper is in range which causes a traffic collision some times it clears out works fine some times it doesn't and the tipper wont unload. Which makes testing this other issue harder to do. @Satissis the reason I am using giants AI is the the turn maneuver is way to big and turn on field is disabled for this.(I even tried with 6 headlands on field 1 and still ran into stuff I tired turning it off but I think it goes beyond specialtools) [Log](http://pastebin.com/UZeKgxbR)
![farmingsimulator2017 64bit 2_9_2017 3_31_31 pm](https://cloud.githubusercontent.com/assets/10678220/22802146/b6d7bda4-eedd-11e6-90ea-7630189bb428.png)

**Comment by pops64** [comment]
Closed #2909
