### ISSUE TITLE
Suggestion/Issue with new unload point

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1670]
Edit. For the forward unload point would be possible for the tipper to do a left or right side tip of our choosing if the tipper support such kind of tipping and maybe if the side tip is full drive forward until it can tip again(or tip before it reaches the full heap)?

So I finally got to testing your new unload point. Thanks :D. I have a suggestion/issuse. I am reversing into the unload point would it be possible to detect the edge of the heap if its full and dump there instead of going all the way to the unload point(unless there is no heap). The reason this is an issue is when the heap no longer allows dumping the trailer CP keeps trying to dump even tho it can't and does not abort and CP gives you no error message about it either. Thanks for reading thanks for this great feature. I would give you a video but it wouldn't change
![farming simulator 17 1_22_2017 12_03_17 am](https://cloud.githubusercontent.com/assets/10678220/22180171/bdf75686-e036-11e6-9937-d14a003b7f2e.png)

**Comment by DFlame69** [comment]
I had similar unloading issues so I wrote in my own timeout code for it.
[toolManager.zip](https://github.com/Courseplay/courseplay/files/735319/toolManager.zip)

**Comment by pops64** [comment]
Added to tracker closed to keep issues area clean
