### ISSUE TITLE
Mode 2 Chaff Silos Unloading Issue

### ISSUE THREAD

**Issue by VENAAAA** [Courseplay/courseplay#1671]
Bei der Boxenstopp nähern und Spill aber erst richtig los und leert während der Fahrt. Ich weiß nicht, wo, was ich falsch mache. Danke für den Rat.
`http://www.jpeg.cz/images/2017/01/22/3QV5c.png`

**Comment by Satissis** [comment]
Hi Venaaaa

There is no need to add an dump point when reversing into the bunker silo.
Remake the course and just reverse a bit further inside the bunker silo and without the dump waypoint.

Google translate to German:
Beim Umkehren in das Bunker-Silo muss kein Dumppunkt hinzugefügt werden.
Machen Sie den Kurs neu und kehren Sie ein bisschen weiter im Bunker-Silo um und ohne den Dump-Wegpunkt.

**Comment by VENAAAA** [comment]
Also ich verstehe, dass Halt auf dieser Seite der Grube und verschütten nicht?

sorry für Übersetzer

**Comment by nyfarmboy07** [comment]
GCV - cp-5.01.00040

I have been having issues with getting the course to correctly dump into silos also.  When I generate the course I back the T6 and Agroliner tandem wagon fully into the silo so that the front axle is just inside the edge of the silo.  When I run the course, the tractors often back up to just inside the edge and dump.  This is not an issue as long as you back in the silo far enough.  I added a larger trailer (Bergmann REPEX 345) and run on the same course.  The larger trailer will then start dumping inside the silo and then pull out of the silo still unloading all over the ground. It can be as simple as restarting the game and it will work fine.

**Comment by VENAAAA** [comment]
https://youtu.be/FSxPbuqc1RA?t=274

Hier tritt Punkt P (Parken)
Ich habe es nicht?

**Comment by Satissis** [comment]
@nyfarmboy07 you should record the reversing without the trailer and place the reactor inside the bunker before changing it to forward and drive out again.

@VENAAAA no there is no need for an parking point or dump point at all, just reverse inside the bunker without the trailer and change it to forward and drive out again. that's all.
@VENAAAA nein gibt es keine Notwendigkeit für einen Parkplatz oder Dump-Punkt, nur umzukehren innerhalb des Bunkers ohne Anhänger und ändern Sie es nach vorne und fahren wieder aus. das ist alles.

**Comment by VENAAAA** [comment]
http://www.jpeg.cz/images/2017/01/22/jmBJY.png

Kein Punkt hinzugefügt noch gut beim Entladen rollen. :-(

**Comment by IvoryBalboa** [comment]
I had the same problem. Try to drive a little further in a straight line when you drive out of the silo after dumping. And drive a little deeper into the silo while driving backwards. The waypoint has to be inside the silo. These two things fixed the issue for me.

**Comment by rkaerner** [comment]
As teached in a lot of tutorials for cp 3 and cp 4: always record the courses without any trailer. After uturning, drive far enough forward to give the trailer (which you don't have with you at this moment) a chance to come in a straight line with the tractor. Then switch to backward driving (in the cp window) and drive backwards until the tractor is standing in the trigger. Switch back to forward driving (in the cp window) and continue your course up to its end point.
If you this for all your courses it will work like a charm. Done that with cp 5 a lot of times now without any problems.

**Comment by nyfarmboy07** [comment]
![fsscreen_2017_01_22_12_56_54](https://cloud.githubusercontent.com/assets/24856526/22271808/836217a6-e264-11e6-8f1f-7e4f75b0761a.png)

This is the issue I find.  It worked flawless for quite awhile, but there's an issue once the bunker silo gets about 50% of height.  I think this is more to do with mode 10 than 2.

**Comment by rjjurjens** [comment]
I am having same issues, read all these responses, did exactly what Satissis said, Everytime it backs into the bunker is starts unloading right away.
I have tried coming in straight, back further in bunker before changing direction, every time it does the same thing.

**Comment by nyfarmboy07** [comment]
The main issue I've found is when the silo reaches about 50% or so, mode 10 appears to increase the incline slope of the front of the silo to the point where the trailer can not fully unload, or the silage pushing tractor can not push (in auto blade height + leveling & packing settings) the silage past the slope.  You can notice I have a half filled silo next to my near full silo to see how the incline becomes too steep and the tipper can not fully unload.
![fsscreen_2017_01_30_10_35_53](https://cloud.githubusercontent.com/assets/24856526/22573946/bf4a90a6-e979-11e6-89d4-db95c81bb549.png)
![fsscreen_2017_01_30_10_25_27](https://cloud.githubusercontent.com/assets/24856526/22573957/cc9e8ffa-e979-11e6-8d42-30dffbcb9bfa.png)

**Comment by JDTiger** [comment]
I have a sketch of my issue (trailer dumping at silo entry, not end), hope you can help me...
Black is driving forward, red beckwards...
![courseplay issue](https://cloud.githubusercontent.com/assets/9157835/24082499/e3ade950-0cc6-11e7-9ec2-ef619850a570.png)

**Comment by dkfiremann** [comment]
I don't think that is the way CP is programmed to do. 
It will tip at the start, as soon as it reaches a tip trigger. There is no way to tell it what is start and end of a trigger.

**Comment by JDTiger** [comment]
To quote the manual:

> Unloading in silage silos can also be done in reverse. When recording the route, reverse to the backend of the silage bin and change to forward again and continue the route. Unloading will be done from the rear end of the silage silo.

**Comment by pops64** [comment]
@dkfiremann With BGA silos triggers act differently. In reverse it suppose to go x distance from the edge of the trigger and then dump. In forward it suppose to evenly dump the chaff along the entire length of the trigger. 

@JDTiger have you followed all the steps that are listed here to try to correct your issue. If the BGA course is not setup 100% correctly you will run into issues. Make sure your backing into the silo without a trailer. Make sure you reverse at least halfway or more into the silo. Make sure you drive pretty straight out of the silo and then some.(Good rule to follow is drive forward till the last possible moment before turning)

**Comment by JDTiger** [comment]
@pops64 Drove back till like 2m from the back wall, straight in, straight out... here is a screenshot from that part of the course
![fsscreen_2017_03_19_20_15_24](https://cloud.githubusercontent.com/assets/9157835/24083928/daa9ffa0-0ce0-11e7-99ac-018aedbfc937.png)

**Comment by dkfiremann** [comment]
@pops64 Sure, I know. And is it not doing that? reversing some meters into the bunker and then dump?
The OP will like it to reverse ALL the way back, not only a few meters. I haven't seen that working before.

**Comment by pops64** [comment]
@JDTiger now that we know your not using a standard BGA trigger. Could we get that same picture with F5 active has this shows the true boundary of the trigger. It may be going the correct distance back it just may appear it is not since you have a larger than normal trigger. Also could we could a log with debug channel 2 running? Thanks

**Comment by Satissis** [comment]
@JDTiger The old way to reverse into the backend of the silo do not work anymore due to the new tip anyware feature Giants implemented.
The thing you were refering to from the Manual have not bee updated yet to show that this feature don't work anymore.

**Comment by pops64** [comment]
What is the status of this? I know thomas made some changes a while ago. Did these have any impact?

**Comment by pops64** [comment]
This is assumed fix due to the changes thomas made. Closed to keep issues area clean
