### ISSUE TITLE
Plow Moves too Far Over On 2nd Lane

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#1674]
Map:  Westbridge (ported to 17)
Fields 15, 16 & 17
Equipment used:  Fendt 724 tractor, Amazone Cayron 200 plow (both vanilla)
CP Version:  .00042 (Happened several previous versions, but I can't remember how far back).
CP starts the plow out correctly, but leaves a portion unplowed of the new lane from beginning to end, and then leaves a longer than usual strip for all the other lanes.
[log.txt](https://github.com/Courseplay/courseplay/files/721958/log.txt)
Log attached and here is a video of the error:  https://gaming.youtube.com/watch?v=6KRI1RvetTg&feature=share

**Comment by Satissis** [comment]
hmm Just tested it and it looks like in the first lane it does not change the tool offset when reaching the first turn. I'll have a look at it.

**Comment by Satissis** [comment]
Should be fixed in v01.0044.
Try it out and report back.

**Comment by lcc1211** [comment]
This corrected the issue. Thank you.
