### ISSUE TITLE
map overlook showing more tractors

### ISSUE THREAD

**Issue by Gepardo** [Courseplay/courseplay#1676]
Hi,
I couldn't find any ussue about this. But when I am using courseplay at one
tractor and open mapoverlook it shows me 2 of them instead of one. 
I don't know if it could  come to bugs cause of this, but it would be maybe better to avoid
such troubles. 

Does it something to do with helpers.lua?

**Comment by Gepardo** [comment]
![20170122155023_1](https://cloud.githubusercontent.com/assets/25281664/22183298/dc8fe6d8-e0ba-11e6-88c8-30ff3974c164.jpg)

**Comment by ThomasGaertner** [comment]
what I see is a MF7700 running in transfer mode and a T6 in Fertilizing/Seeding mode 
which one is the ghost ?

**Comment by Gepardo** [comment]
T6 is the ghost. If you don't use any helper then everything is allright - no any ghost. But if  you use courseplay and there is a helper on your tractor you will have a ghost - one more tractor on mapoverlook picture.

**Comment by pops64** [comment]
So your saying the T6 has no couseplayer in it at all(Should not even be displayed on the map) or are you talking the green circle around the T6? If you have a log of when this happens that would be great has well

**Comment by Gepardo** [comment]
Thomas Gärtner klang auch Deutsch aber ich war mir nicht sicher. Es passiert mir nur wenn ich mit CP einen Helper einstelle. Dann habe ich eine Kopie von dem Traktor bei der Übersicht. 2 T6 z.B. obwohl ich eigentlich nur Einen habe. Sobald ich den Helper für CP ausschalte, dann ist wieder nur Einer da. 
Kann man zwar nicht unbedingt als bug einstufen aber ist schon nervig und täuscht, wenn man den Fehler natürlich nicht kennt.

**Comment by ThomasGaertner** [comment]
test with v.0071 or higher and report....

**Comment by Gepardo** [comment]
Ich habe die neuen Veränderungen getestet und die Geistervehicles habe ich immer noch. Habe auch ein neues Spiel gestartet. Das gleiche Ergebnis. 
![20170208202356_1](https://cloud.githubusercontent.com/assets/25281664/22753642/1c4c7f68-ee3d-11e6-8297-05c92173a102.jpg)

**Comment by Blackmankot** [comment]
@pops64 I suggest also close it for cleaning.

**Comment by pops64** [comment]
Closed #2909
