### ISSUE TITLE
waiting tractor moving

### ISSUE THREAD

**Issue by Sythos** [Courseplay/courseplay#1677]
i've a tractor doing the travel from overload loading point to farm, while wait it still move flipping speed from 0,0km/h to 0,1km/h, the result is the tractor lose the proper position and overloader cannot match the tipping unloading point.

as suggestion, is there a way to turn off engine & brake while a tractor wait?

**Comment by Satissis** [comment]
[How to provide a nice and sexy bug report](https://github.com/Courseplay/courseplay/wiki)

Also is this mod or vanilla equipments?

**Comment by Sythos** [comment]
It a standard T7, with a standard 2axes Krampe and custom mod as front weigth (blacksheep 1800kg). This not happen if the waiting point is a perfect plane, i'm out home now, i'll supply more infos and LOG.txt as soon as possible (and try also other tractors)

**Comment by ThomasGaertner** [comment]
please make a screeshot of the situation with debug channel 21 active

**Comment by Sythos** [comment]
with version .0058 still suffer, but after lot of checks i've noticed is dependent by the weigth attached in front of tractor, is not CP related, so i think this issue can be closed.

**Comment by Sythos** [comment]
btw, "turn off engine" if tractor is waiting is anyway a wishlist :)

**Comment by Sythos** [comment]
![20170131100422_1](https://cloud.githubusercontent.com/assets/15103522/22458429/c817c5c0-e79c-11e6-864f-e162b4a97223.jpg)

this is anyway the screenshot requested

**Comment by Sythos** [comment]
![20170131100710_1](https://cloud.githubusercontent.com/assets/15103522/22458485/07e8fe26-e79d-11e6-8226-ca02ddb0a415.jpg)

this is after 2-3 minutes the tractor wait, it is already turning shifting on a side
