### ISSUE TITLE
Mode 9 to tipper bug(pre-unloading position)

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1679]
Has seen in the picture it is clearly over the tipper and should dump but does not. If you hit the play button in the shovel settings for unload it does dump and will continue like normal. [Log](http://pastebin.com/5wrM4Nvp) with channel 10 and [video](https://www.dropbox.com/s/0kk784ea52cm6nb/Farming%20Simulator%2017%201_22_2017%202_37_34%20PM.mp4?dl=0)with channel 10. I also noticed that it does not wait at a distance like it did in 15 for the tipper to show(so you don't have traffic detection issues). Seems to be related to how I have my pre unloading postion setup up. I have changed it and works as normal Thanks for reading. Keep up the great work
![farming simulator 17 1_22_2017 2_31_09 pm](https://cloud.githubusercontent.com/assets/10678220/22185307/2f88a974-e0b1-11e6-8871-c418d1533210.png)

**Comment by ThomasGaertner** [comment]
could you send me your savegame ? I can not replicate it ...

**Comment by Satissis** [comment]
If I remember correctly you can not have the front loader lifted all the way up. you need to lower it a tiny bit.
I had that issue in fs13 or fs15 (cant remember which) and I was told to try lower it a bit since it would not always work when it's at max position.

**Comment by pops64** [comment]
Yea. That is the issue. So if you want we can close this out.(I thought raising it to max would cause graphic glitches and not this behavior tho. Cause I do this same in the front loaders and they work fine)
