### ISSUE TITLE
Mode1 Improvment Feeding Troughs 

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1680]
Would like to see CP support feeding troughs in mode 1 has right now there is no check to see if the receiving troughs is full and to let the tipper carry on if so.(Grain silos are coded to work)

**Comment by lcc1211** [comment]
I had a similar experience with dropping off grass to sheep and cows.  Except my drop off wasn't in reverse but rather by the side.  I found that if the amount of grass I was carrying was larger than what I could leave in the trough, it would not continue.

**Comment by pops64** [comment]
Yea but I had a similar route driving forward for the corn and barley and Canola and it worked just fine. It sounds like its based on the crop

**Comment by lcc1211** [comment]
Like it is expecting a grain drop and no other type of crop?

**Comment by pops64** [comment]
Sorry see edit. My bad for not look at the code. CP doesn't support unloading into troughs completely(It expects the tipper fill level to be 0 in order to drive on.) I had a traffic collision which caused me to think that forward worked.

**Comment by lcc1211** [comment]
Although it wouldn't be a bad feature.  I have 300 cows, 400+ sheep, and I would like to have it drop off as much grass as possible as I have a mower on the front and a pick up wagon on the back while mowing a huge field. If it could work the way my water route works where I have a small tractor with a small water tank making a non-ending route between them and the pigs.

**Comment by DynamicXYZ** [comment]
This also happens on mode 9. The driver just sits there when the trough is full and food stuff in still in the bucket.

**Comment by pops64** [comment]
Sorry I must have been having a issue that night. I looked through the code again and it does look to me that this behavior should be support(I was looking at the wrong unloading function :()

**Comment by ThomasGaertner** [comment]
test with v.0062 or higher and report

**Comment by pops64** [comment]
Love it. Thanks for making it stop when its done so I don't have to worry about it looping continuously. And having it side tip if your driving straight through. Only now have to move the tip point to the center of the trigger like it was way back in early 15 but that is a different suggestion for another day. Thanks again. I will close this out to keep the issue's area clean
