### ISSUE TITLE
Suggestions: Field Routing

### ISSUE THREAD

**Issue by Dajoor** [Courseplay/courseplay#1684]
Hi

Currently the field path uses only 2 types: circular and/or zigzag, or a combo thereof. This is not always optimal depending on the type of equipment, and it can sometimes cause issues on certain irregular fields. Turning and route point hunting can waste a huge amount of time.

I suggest you add 2 more modes: 1.) Spirals (like a diminishing oval) where it starts on the outsides and works towards the inside. This will reduce most turning problems (reduce most turns to simple 90 deg) with large/long equipment, and only the last few turns to the center of the field may be problematic. This would also speed up the field processing time.  2) Alternate lanes in any field mode. This makes a vehicle skip every odd or even lane. The benefit again is to reduce sharp turns and field time. This will also allow 2 vehicles per field. Simply setup route, export, then load in the 2nd vehicle and pick odd or even lanes.

A third suggestion is to reduce babysitting: When a block or slip is detected, reverse, and try a different route. One can assume that offsetting the vehicle (or route points) by half it's width on either side will clear the obstacle. One can also assume that reversing and passing are each the full length of the vehicle.

Also perhaps consider being able to provide offsets for headlands and center field work separately.

Thanks for Courseplay. I can't play FS without it.

**Comment by pops64** [comment]
Your 2nd sugestion is already possible http://courseplay.github.io/courseplay/en/faq/index.html under How to use the offset? — a.k.a. how do I let multiple vehicles drive a fieldwork course? I use it all the time cause I don't have enough money to afford larger equipment but I can buy 2 of the smaller ones(I have 2 3m cultivators and sowing machines) One tip make sure they are the same equipment or expect overlap I know the 2m ploughs have issues playing nice with each other.(One is 2.1m the other is 2.2m according to CP). You can even have higher numbers than 2 equipment as descried in that section. 

Your 3rd suggestions is sorted of implemented in mode 2 and 3 the tippers do occasionally try to drive around trees and poles. I know someone suggested that when following chaff harvesters that they turn only on field which would be a huge benefit if its possible

Your first suggestions. There were plans to overhaul the headlands generation system. If it could include a spiral mode? You would have to wait to hear back from Thomas or Satis. Cause in the current system it is not possible that is why we are limited to only 6 headlands. There is no coding protect the system if the headlands interfere with each other has you can see on some of the smaller field.(This design flaw is described here #1554)

Your last bit which offset are you talking about? Lane offset? 

I hope the manual helps you out if. If need more help using lane offset just ask I might be able to do a video. Thanks for reading

**Comment by Dajoor** [comment]
Thank you. I am aware of the existing lane offsets. However my suggestion is to reduce all that calculation and setup to a simple one click. You can just pick odd/even/none and that's it. The primary idea is to make large equipment work/turn easier and faster, not just to allow 2 machines - although it would make this possible. (I use Followme for chaff harvesters, it is simpler to use.)

The existing block detection/evasion does not work well. And it is not implemented for field work where most of it seems to happen.

**Comment by pops64** [comment]
Added to the tracker to clean up issues area

**Comment by pvajko** [comment]
Both 1 and 2 are possible with the new course generator just need to enable it on the HUD somehow.
