### ISSUE TITLE
Courseplay Kurs und Fabrikscript

### ISSUE THREAD

**Issue by Chris-KB** [Courseplay/courseplay#1685]
Hallo, 

Es tritt ein Probem mit CP auf, wenn man damit ein Objekt, welches das Fabrikscript verwendet, befüllt. Dabei friert das Spiel ein und es tritt folgende Fehlermeldung in der Log auf

/FabrikScript.lua:1314: attempt to compare number with table
Error: Running LUA method 'update'.

**Comment by Chris-KB** [comment]
Lösung gefunden.. Liegt an dem Fabrikscript nicht an CP!

**Comment by Akoasma** [comment]
#1655 #1651 #1573

**Comment by Satissis** [comment]
just as @Akoasma linked.
I have also seen that some got it to work by updating the Fabrikscript to the latest release.

**Comment by hoefti10** [comment]
New Fabrikscript is released today...should fix the issue
