### ISSUE TITLE
Suggestion: Mode 2-3

### ISSUE THREAD

**Issue by SMDSY** [Courseplay/courseplay#1689]
Hi its just a suggestion for mode 2 and 3..
If possible!

Its been bugging me that when u have a tracktor+trailer/overloader trying to turn around after unloading the combine to ither park behind where the combine tells it to stop or going back to the start point to then go and unload, andmakes a turn ang det stuck in a tree, fence, bush or what ever gets in its way..

whould it be possible to restrict the tracktors movment to be on the feild exept when its gets close enuf to the combine to move out side the feild to empty the combines silo.. 

this could also help on feilds that have ilands of grass or could have feilds that have shapes that makes the tractor go thrue forests and houses to get to the combine after it have unloaded the tipper...

let me know if u need more/bether explenation.. English inst my first language..

**Comment by pops64** [comment]
Already been suggested #1469
