### ISSUE TITLE
Harvesters Mode 6 Finsh Work Bug

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1690]
I have discovered that if you let a Havester sit to long when finished work in mode 6 he then gets bored and can't make up his mind if he is done with work or not. He will flip back and forth between turning off and on, folding and unfolding. He will eventually drive a few meters forward and commits to not working but will remove the message about being done. Which channel would you like? I will post a video and time it takes. Is this even possible to fix? And do not know if this occurs with anything else.

P.S would it be possible if the harvester is in the last lane for the tipper to park 2 lanes over has this picture has occurred since FS15
![farming simulator 17 1_23_2017 4_21_15 pm](https://cloud.githubusercontent.com/assets/10678220/22223237/28577b58-e188-11e6-9837-bfbd3ddd150b.png)

**Comment by ThomasGaertner** [comment]
I have no idea, how long did it take till it began ?

**Comment by pops64** [comment]
I would say 3 to 5 mins(give you an update in a bit). I was thinking maybe if we had a crtl left click to icon that lets you switch to the tractor/harvester directly that stops CP this problem could be avoided if it is possible.

**Comment by ThomasGaertner** [comment]
test v .0063 or higher and report....

**Comment by pops64** [comment]
Let it sit for 5 mins no issue. Thanks I'll close this out
