### ISSUE TITLE
Terra Felis not recognised

### ISSUE THREAD

**Issue by Raints** [Courseplay/courseplay#1697]
Dont know when it did change, but in some earlier version I got to choose from combine list Terra Felis. Now with version 051 wont show up anymore. Everything worked perfectly, the driver drove to the place, got the load and then continued his course. 

![untitled](https://cloud.githubusercontent.com/assets/3618060/22263218/5b438ba2-e27c-11e6-9972-b44212271041.png)

Latest working version I found was 006

**Comment by Satissis** [comment]
so did you find it or is it still missing from your end ?

**Comment by Raints** [comment]
Still missing.

**Comment by ThomasGaertner** [comment]
is it possible that you are working with a modded one ?
when I set it up it looks like this:
![fsscreen_2017_02_07_20_56_27](https://cloud.githubusercontent.com/assets/3279913/22708839/12c5b038-ed78-11e6-85e8-ba72954d292c.png)

so try again with the latest version or tell me which mod it is ....

**Comment by pops64** [comment]
I know I could have sworn that this was not in the list.(Cause I checked before adding this as a bug) Maybe when you changed how mods were loaded this was impacted?

**Comment by Raints** [comment]
Yea, its moded one. No time to test anymore, will close it.
