### ISSUE TITLE
Incorrect width for Tiger 10 LT cultivator

### ISSUE THREAD

**Issue by DynamicXYZ** [Courseplay/courseplay#1700]
The Tiger 10 LT cultivator width is supposed to be 10.2m but when I click the auto-calculate it sets it to 10m instead. Tested it folded and unfolded.

**Comment by jhomer** [comment]
This is a mistake by Giants.
The store data does in fact show 10.2m but ...
Looking at the i3d it does shows working width of 10m for both the working width and AI.

**Comment by pops64** [comment]
@jhomer So for the amazone  ED3000 the AI area is 2.66 across but the AI size is 3.142 which is the correct value? for this sorry I have very limited experience with i3d files. Just wondering cause CP always spits out 2.7m and I use 3.0 and don't have issues. Thanks

**Comment by jhomer** [comment]
I'm not a 100% on this all here but there is 3 dimensions, workArea, aiArea, and aiSize.
 
-workArea of 2.66 which updates the field 
-aiArea of 2.66 which tells ai size of work area (not sure why they need this too as I think it's always the same as workArea. 
-aiSize of 3.142 which tells ai the actual physical width of the implement

The workArea is the number that you would want to follow.
I'm ~assuming~ CP gets it's information from the workArea (2.66) then rounds to nearest whole number.

**Comment by Satissis** [comment]
yes exactly. it uses the workarea to find the width, so yes there will not always be the same value presented in the shop info and the real width.

I'm going to close this to keep the issues clean also since we can do anything about it.
