### ISSUE TITLE
Error-Mode2 Courseplay(Auto Combine Support & AIVehicleExtension mod)

### ISSUE THREAD

**Issue by Spaxer** [Courseplay/courseplay#1701]
Hey Guys Ive got one Error which spawns my log .... 

C:/Users/domi/Documents/My Games/FarmingSimulator2017/mods/ZZZ_Courseplay/mode2.lua:529: attempt to index field 'acDirectionBeforeTurn' (a nil value)
Error: Running LUA method 'update'.

this Comes so often that the game laggs und crashes .. can some one help me pls ? 

[log.txt](https://github.com/Courseplay/courseplay/files/730008/log.txt)

**Comment by rkaerner** [comment]
At first clean up your mods folder. A mode throwing errors is a mod throwing errors. And in your log.txt are massive errors thrown by other mods than cp.

**Comment by Spaxer** [comment]
Hey ralph i hope you are german:) because my english is bad... 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 26.01.17, 09:12, Ralph <notifications@github.com> schrieb:

  
    
      At first clean up your mods folder. A mode throwing errors is a mod throwing errors. And in your log.txt are massive errors thrown by other mods than cp.

**Comment by rkaerner** [comment]
Sure, I am german. But if we two start to speak in german, all the other interested people are not longer able to follow us. So if your english is bad, try to become better. Hint: write in german AND in english language and noone will hang up you on the next tree ;-)

**Comment by ThomasGaertner** [comment]
the support for the new autocombine is not yet implemented ...

**Comment by Spaxer** [comment]
I find out the problem .... The errors doent come from courseplay they come from autocombine .... I disconnected the mod and the gane runs with out any errors .... :) but why the new autocombine doesnt run with courseplay together? 
Greets 
Spaxer
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 28.01.17, 10:57, "Thomas Gärtner" <notifications@github.com> schrieb:

  
    
      the support for the new autocombine is not yet implemented ...

**Comment by pops64** [comment]
Edited Title for clarity

**Comment by Satissis** [comment]
@Spaxer The new Autocombine have some changes in it's code that were used by CP before, so until we are going to look into fixing this, it will not work. It's not our highest priority atm.

**Comment by Spaxer** [comment]
Yeha thats oke :)  thank you :)
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 06.02.17, 16:53, "Claus G. Pedersen" <notifications@github.com> schrieb:

  
    
      @Spaxer The new Autocombine have some changes in it's code that were used by CP before, so until we are going to look into fixing this, it will not work. It's not our highest priority atm.

**Comment by Satissis** [comment]
v01.00107 should fix all the nil values errors you are getting.
Implementing of AIVehicleExtension will have to wait until after release.

**Comment by pops64** [comment]
Alright AIVE Compatibility is back in version 139 or higher and  **Requires AIVE Version 1.1 b3 or higher** Download from Mogli12's Git Hub at https://github.com/Mogli12/AIVehicleExtension Try it out a report back. Also if you use AIVE with a chaff harvester in circular mode it will only allow you to use the one turn maneuver. The other two aren't compatible with CP.

**Comment by pops64** [comment]
Assuming no one is having issues with AIVE compatibility going to close this out.
