### ISSUE TITLE
Reverse driving support

### ISSUE THREAD

**Issue by SnoopBok** [Courseplay/courseplay#1704]
Thanks for this great feature. I noticed one issue. I'm using a Fendt 930 combined with a Pottinger Mex 5 chaff chopper. Another Fendt 724 is in mode 2, bringing it to the BGA. However the Fendt 724 won't find the Fendt 930, even when I manually choose it?

**Comment by ThomasGaertner** [comment]
test v 0057 or higher and report...

**Comment by SnoopBok** [comment]
It's working, thanks!
