### ISSUE TITLE
New Holland Sprayer Error

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#1705]
Using the New Holland sprayer on GCV field number 5.  Sprays until empty and starts an error message saying it unexpectedly is empty, but keeps going up and down the field.  Even though I have a course set up for it to drive past the fertilizer station, it never leaves the field.  2 CP courses. One to fertilize and one to refill.  Log attached. I tried to get a video but my video recorder wouldn't start.
[log.txt](https://github.com/Courseplay/courseplay/files/731002/log.txt)

Should I open a new issue for the sprayer moving into the field before it starts spraying thus missing a few meters of the field?

**Comment by PromGames** [comment]
No much to say with the posted log. Could you please recreate the error but having the corresponding debug mode in courseplay hud and upload your log, this could give you a better view what is happening

**Comment by lcc1211** [comment]
Would you be able to tell me which debug channel(s) to choose?

**Comment by pops64** [comment]
I think the problem with it driving when empty is CP uses self.cp.totalSprayerFillLevelPercent to detect sprayer fill level which my guess is it looks to see what the tool level is and since there is no tool its a vehicle it needs to include the vehicle level percent. Same problem as the tree planter. The variables used in the thing that makes it drive the unloading courses don't detect the levels of the tool/vehicle. As for the few meters are you turning off field on field? Debugs 12 and 14 for that issue with picture. Cause I just ran turn on the field and had to issuses

**Comment by lcc1211** [comment]
The 1st few meters are from the beginning with the vehicle lined up with the start point a few meters from the start of the field.  The sprayer moves onto the field, unfolds the boom and sprays from that position.  It is as if it thinks the boom is in the rear of the vehicle like the other 2 default sprayers.

**Comment by pops64** [comment]
So when you first start. That is the way CP has been since i have'd used it in 15. The harvesters do that has well. Check out https://github.com/pops64/courseplay/commit/dfdef63f2363d8808fbca4781f8ddaf02ea0ba57 for a temp fix I have tested it only with the SP400F so far.

**Comment by lcc1211** [comment]
OK. I will give that a try until a more permanent fix is available.

**Comment by pops64** [comment]
Did the helper saying it was empty before or after my fix? Cause I got the tree planter working and that is the only bug I have seen from it

**Comment by lcc1211** [comment]
I was not able to get it to work with your fix. I will have to check again to see if I added it correctly.

**Comment by pops64** [comment]
Either fix should work but with a warning. It is a very rough fix. The AI will still yell at you about being empty and I can't seem to figure out how CP suppresses this or it is not an issue. And doesn't stop until you quit the game

**Comment by Satissis** [comment]
Don't close it yet until we have an fix for it.

**Comment by rkaerner** [comment]
AFAIR this is a doublette of an issue opened a time before. Couldn't find it, but that may have its cause in my bad eyes.

**Comment by rkaerner** [comment]
#1612

**Comment by pops64** [comment]
They have the same cause but the same fix can not be applied to both of them. For some reason the AI is very upset when you apply the same fix to the tree planter. And I still can't figure out how CP avoids this with all the other tools

**Comment by ThomasGaertner** [comment]
test .0053 and report...

**Comment by lcc1211** [comment]
Thank you.  It now is able to follow the refill route and returns to the field with zero error messages flashing on the screen.  One minor thing, though, that may not even be worth looking at:  When returning to the field the sprayer moves about 1/2 meter ahead of where it stopped so there a bit left unsprayed.  This is not a concern for me. So it can be closed as far as I am concerned unless you want to alter that and then I can test again.

**Comment by pops64** [comment]
this is because mode 4 the return to waypoint is one behind where it was last left off mode 6 is 2 waypoints
line 57 `if self.cp.previousWaypointIndex < self.cp.stopWork and self.cp.previousWaypointIndex > self.cp.abortWork + 9 + self.cp.abortWorkExtraMoveBack then` should be + 8 not + 9 because in mode 6 this same line is + 8

**Comment by ThomasGaertner** [comment]
yea its because in mode6 its not that issue that the tools are starting earlier, but for sprayers we had claims that turning the toolson earlier  would be a waste of fertilizer...  so won't fix
