### ISSUE TITLE
Stop during unloading error

### ISSUE THREAD

**Issue by iw-shawn** [Courseplay/courseplay#1708]
When having the combine set to stop during unloading, if the tipper gets to 100% full before the combine is empty the combine will not continue on it's course.  

A similar issue, if the tipper get's stuck before finishing it's turn manoeuvre the combine also won't continue.

Problem was found using MF Activa 7347

**Comment by rkaerner** [comment]
Same here, on a friend's game play. If combine stops and unloads after arriving vehicle with trailor, both will not move in any more. Me, myself and I doesn't have this problem on any map until now, because I don't change the normal behaviour (driving while unloading)

**Comment by ThomasGaertner** [comment]
test v.0061 or higher and report...

**Comment by Flitch49** [comment]
Tested on v.0066 with vanilla equipment and map. The problem seems to be cured. 
Partially emptied combines will now resume after the trailer is filled and leaves.

**Comment by Paul2510** [comment]
Have it also tested and it works great! Many Thanks!

**Comment by rkaerner** [comment]
A friend of mine also tested it and it works for him like he expected. Just FYI
