### ISSUE TITLE
Drescher fährt mit Tankinhalt nicht weiter im Feldarbeitsmodus!

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#1710]
Hi! Das ist nur eine Frage! Und zwar hab ich auf einen Feld zwei Drescher Laufen mit CPund einen Trekker mit UL! Ich hab bei den Drescher am liebsten die Funktion beim Abtanken anhalten! Jetzt ist nur das Problem das der Drescher wenn er nicht ganz abtankt nicht mehr weiter drischt! Vieleicht kann es so geregelt werden das er mit dieser funktion(beim Abtanken anhalten) sobald der Abfahrer vom Drescher sich trennt CP technisch der Drescher weiter arbeitet! 

LG

**Comment by rkaerner** [comment]
Ich bin sicher, dass Du mehr Reaktionen erhältst, wenn Du, wie gefordert, in englischer Sprache schreibst. Alles andere ist schlicht unsozial denen gegenüber die der deutschen Sprache nicht mächtig sind. Und das wäre dann wenigstens einer der Entwickler.

Reprimand in german language. For the non-german-speaking people: just ignore it.

**Comment by Akoasma** [comment]
@rkaerner 
Also als "unsozial" würde ich genau eine Person hier bezeichenen. Und das ist nicht Paul2510 ...

@Paul2510 
Wenn der Drescher nicht anhält zum abtanken, klappt alles? Dann lass ihn halt weiterfahren beim abtanken ;)

**Comment by Paul2510** [comment]
Hi! That's just a question! And I have on a field two threshing with CP and a Trekker with UL! I have the dresters most likely to stop the function when you stop! Now is only the problem that the thresher, if he does not completely refuse no longer drischt! Maybe it can be regulated so that he stops with this function (stop) as soon as the runner separates from the thresher CP Technically the thresher continues to work!

LG

Google translate

**Comment by ThomasGaertner** [comment]
#1708
