### ISSUE TITLE
Course Play Only Recognizes Part of the Current Lane

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#1711]
Map:  Westbridge port to FS17
Field:  17
Harvester:  Vanilla Case IH 1660 Axialflow with default header.
In the first lane CP harvests about 3/4 of the way up the lane and then begins moving to the next lane.
![20170127211109_1](https://cloud.githubusercontent.com/assets/24764870/22393546/6c23bd6e-e4d6-11e6-93cd-f454cc3aed21.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/736646/log.txt)

**Comment by pops64** [comment]
What do you field boundaries look like? Picture  of the course overview. Debug channel 7. My best guess is that you field boundary is kinked some where. Straighten the field and try again.
![farming simulator 17 1_27_2017 10_15_24 pm](https://cloud.githubusercontent.com/assets/10678220/22393864/7fecf740-e4de-11e6-9bc8-2553d86afb98.png)
![farming simulator 17 1_27_2017 10_16_04 pm](https://cloud.githubusercontent.com/assets/10678220/22393865/83236188-e4de-11e6-8936-93a6ca8b89b2.png)

**Comment by lcc1211** [comment]
Yes it is and I did expand the field. Please explain how you expand the field using course play as I have no idea how do but would love to do.

**Comment by pops64** [comment]
So drive a box around the bit you want to expand manually. Then when you go to generate course instead of selecting a field you can use the course you have loaded. And will generate a nice fieldwork course for you.(You may run into the same issue has here because driving does put kinks in it but if you overlap your field your expanding. And let CP expand the field by one or two lanes this will make your field edge straight. Just watch the last lane cp does has this may be shorted because of kinks) I also do this for mowing meadows that aren't field. I may upload a video on how to do this

**Comment by lcc1211** [comment]
A video would be great if you get the time and would be most appreciated.

**Comment by pops64** [comment]
Yep. I am rendering an autodrive tutorial atm. Probably later tonight or tomorrow I will upload a video on this.

**Comment by pops64** [comment]
Link to video https://youtu.be/2QbNAoNXEQ4 hope you enjoy. Sorry for the delay

**Comment by lcc1211** [comment]
Thank you. I never thought to try it this way before.

**Comment by pops64** [comment]
Yea no problem. You can use it for just about anything that works for mode 4 or 6. I hope that fixes you lane issue. If you saw in the video the plough bit at the end that last lane was cut short which is what I was talking about with watching the edge lanes. But this should get your field edge nice and straight which should solve this issue.

**Comment by pops64** [comment]
Did this fix your issue or are you still having problems?

**Comment by lcc1211** [comment]
I got it to work on a different field. I think I just need to practice it a couple more times so I can get better at it.  So I think I will close this one.  Thank you again for the video demo.
