### ISSUE TITLE
automatic field course generation

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#1713]
Hello guys
cp generates, when i let a field-work course generating, a course with waipoints all 5-10meters
what is this:
![unbenannt](https://cloud.githubusercontent.com/assets/24860501/22408756/68a05c52-e67e-11e6-8c7a-30d5c57c810e.png)
in the edge btw on the fase of a field there are the points more than 40meters an there is a lot of non-working place
lg
andreas

**Comment by Satissis** [comment]
yeah the Headland generation is not always working too well, which we hope to improve on at a later state.

This means that there is nothing we really can do about it right now.

**Comment by andreasthu** [comment]
Ok
I think the problem is, that the distance beetween the two points on corner is longer every round.
You can see this on the both nord corners of my pic.
If the distance were each round the same i think then there were no such problems on the south.
I post later a pic what i mean.
Lg andreas

**Comment by andreasthu** [comment]
Here is what i mean:
![edit](https://cloud.githubusercontent.com/assets/24860501/22470229/e27e398a-e7ce-11e6-9958-af4ee49220be.png)
you see the top right corner was generatet by courseplay,
each round the corner distance os longer from point to point

the left top corner i have editet on my idea,
the distances have in each round the same lenght, so the field course is not so like an egg, round.
the are more straight

lg
andreas

**Comment by andreasthu** [comment]
if the corners were same lenght, maybe the south of the field looks like so:
![eventuell](https://cloud.githubusercontent.com/assets/24860501/22470775/a14ffa00-e7d0-11e6-9000-711186406dae.png)
lg
andreas

**Comment by pops64** [comment]
Has @Satissis said this wll be worked on at a later date. Closing to keep the issues area clean
