### ISSUE TITLE
Mod Conflict

### ISSUE THREAD

**Issue by KevinMn** [Courseplay/courseplay#1715]
Hi, I'm having trouble using a truck with CP installed. It's error free, has no custom scripts, pretty much like the ingame stuff. If I try to buy it, it gives me this error:

Error: Running LUA method 'update'.
[builtin:rad]:0: attempt to perform arithmetic on a nil value

I just tried loading a game without CP, purchase the truck, then save. If I try to enter the save with CP enabled I get another error:

Error: Running LUA method 'loadSharedI3DFileFinished'.
[builtin:deg]:0: attempt to perform arithmetic on a nil value

What could be the issue here? Is it my truck, or?

**Comment by Satissis** [comment]
A full log would be nice as a start

**Comment by KevinMn** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/740028/log.txt)

**Comment by rkaerner** [comment]
Throw out the CT660 until it's fixed by its author.

**Comment by KevinMn** [comment]
But the non-binary error isn't the issue, I could get rid of the error, but some shapes exceed the max size, so I unfortunately can't use it like that.

**Comment by rkaerner** [comment]
An Error is an Error and a Warning is a Warning. I don't want to discuss that. Noone of us (and maybe noone of ginats) knows what a warning or an error from mod a can or will cause an error in mod b.

**Comment by KevinMn** [comment]
https://github.com/Courseplay/courseplay/issues/1460

I can see that this guy has the exact same issue.

**Comment by rkaerner** [comment]
It's that simple. Throw out all mods but your Caterpillar and CP. If the problem occurs again, it is your Truck. Full stop.

**Comment by KevinMn** [comment]
I did, look in the log, only those 2 mods. But thanks for the help, I'll try and see if it has some strange thing in the xml that might cause this.

**Comment by rkaerner** [comment]
There is definitely a problem in the i3d, as your logfile told you.

**Comment by KevinMn** [comment]
I just tried converting another truck, exactly the same issue. And this one doesn't have the binary i3d error. They're both from the same author, but he doesn't mod anymore, so he's not going to fix them. However this does goes to show that it is something he did to the trucks, so maybe someone knows what it can be. Yesterday I tried to go through everything in the xml, even copy over some sections (like camera, attacher etc) and reindex things, so I know it was working. I'm 90% sure it's not in the xml, could it be in the i3d? The error suggests something with a radian degree something, but that doesn't help me tbh.

**Comment by pops64** [comment]
Can we close here? Seeing how this looks like a mod issue not CP

**Comment by KevinMn** [comment]
Well it is a mod issue, but I don't know how to fix it, which was why I made the issue. I don't know all the code of cp, but perhaps it doesn't like of a mod has this or that. That was what I was hoping 👍

Den 4. feb. 2017 03.06 skrev pops64 <notifications@github.com>:

Can we close here? Seeing how this looks like a mod issue not CP

**Comment by pops64** [comment]
This isn't the place to get your mods fixed. Head over to FS-UK or moddingcentral and get help there. Once your mod works in game and you still have an issue with CP working with your mod create a new issue thanks. Closed to clean issues area.

**Comment by ThomasGaertner** [comment]
should be fixed in 0067 or higher ...
