### ISSUE TITLE
Harvesters Not Finding Complete Start of Lane

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#1718]
Map:  Mod Hobbs Farm v1.6
All vanilla equipment
Any combine using a header 9M in width or longer are turning too tightly and leave portions of the new lane's fruit behind.
![20170130180459_1](https://cloud.githubusercontent.com/assets/24764870/22446217/8427df90-e719-11e6-908d-f6ba5ea397f2.jpg)
![20170130180654_1](https://cloud.githubusercontent.com/assets/24764870/22446228/8d0394d8-e719-11e6-97a5-d4e46363fba1.jpg)
![20170130181910_1](https://cloud.githubusercontent.com/assets/24764870/22446231/91e8bf28-e719-11e6-82a4-8faeb5653f73.jpg)

It doesn't matter what the field size or crop on the field is.
[log.txt](https://github.com/Courseplay/courseplay/files/740744/log.txt)

**Comment by lcc1211** [comment]
Here's the same on a different PC with far few mods and a cleaner log.
![20170130185219_1](https://cloud.githubusercontent.com/assets/24764870/22446938/61294f5c-e71d-11e6-80fd-6a435b137981.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/740786/log.txt)

**Comment by pops64** [comment]
Has to do with the change for #1386. Already left a comment there about this

**Comment by ThomasGaertner** [comment]
as @pops64  said : #1386

**Comment by lcc1211** [comment]
The #1386 was closed, but my larger headers are still behaving as in the photos above.

**Comment by Satissis** [comment]
it's already on my todo list

**Comment by lcc1211** [comment]
Thank you, Satissis. My confusion. I thought the wrong one had been closed.
