### ISSUE TITLE
Mod Support / Kotte Universal Mode 8 BGA digestate

### ISSUE THREAD

**Issue by debejerry** [Courseplay/courseplay#1720]
Hi devs! 
First let me say:  "Thank You, for your great work on courseplay!"  :+1: 

Version: Courseplay 5.01.00058
Mod: Kotte Universal Pack 1.0.0.6 by Farmer_Andy from marhu.net
CP Mode: Mode 8 (Liquid Transport)

Problem/Room for improvement/Mod Support:
If I run the Kotte Universal Semi trailer (made by Farmer_Andy) on a known to work "liquid manure Transport" course in mode 8, that was successfully tested with the ingame Kotte slurry transport trailer,
CP does not stop at the BGA digestate trigger to refill which it does with with ingame trailer.
This happens to me with all the trailers within the Kotte Universal Pack.

I'm unsure if this might be related to #1350 or  #1390 or a combination of both.
Today in the evening I'll be able to post the logs with debug Level 13? (Trigger debug) enabled.

My first Impression was that CP wasn't detecting the Trigger correctly if the KotteUniversal was attached, but I might be completly wrong.

Regarding the log which exact debug channels would you need to dig into this?

Thank you

**Comment by debejerry** [comment]
[<script src="https://gist.github.com/debejerry/5b6b81f8794f21b53435a4ad6c618ae1.js"></script>](url)

**Comment by pops64** [comment]
Appears to have the same issue has it does in FS15 at first look did you try my fix for FS17. Cause I really hate uploaded.net which is what marhau uses.

**Comment by debejerry** [comment]
@pops64 thanks for giving hint to the right direction. :+1: 
Which I had to correct slightly during debugging. :smile: 
I ended up with a working solution in that CP is able to use all trailer to refill and transport digestate, liquid_manure and water.
Even the fuel tank works (also I don't really get why) :confused: 

Only change to original source that I've done is: modified line 70 in specialTools.lua to:
`if workTool.typeName == 'augerWagon' or workTool.typeName == 'FS17_kotteUniversalPack.kotteUniversal' or workTool.typeName == 'FS17_kotteUniversalPack.kotteUniversal_man' or workTool.typeName ==  'FS17_kotteUniversalPack.kotteUniversal_hookLift' then`

I tested your mentioned changes for line 263 and ongoing with the elseif statements testing on workTool XmlFile 
This section does  (following my tests) never get reached so these lines seem 
not to be able to do anything, as far as I can see. 

@Satissis @pops64  What would have to be done (pull request?) to get this (or maybe a more elegant solution) into the code? because I think that many people would like to see this pack working with CP. Thanks

**Comment by pops64** [comment]
Only added line 263 because there is only that one that uses that typeName. That would be a question for Satis on the pull request. Good catch on the have to add the mod name to the type name didn't know that

**Comment by debejerry** [comment]
Thank you.
had a hard time trying untill I got it... :confused:  :sweat_smile: 
My thought also was that it would be better to detect the trailers by their xml files, but, as I wrote, I never got the script to reach this section...

But for now I/or we do have a workaound for this one.

**Comment by RKI91** [comment]
I have also problem with this pack and more specifically with FCR container. In fertilization mode my manure wagon dosen't simply doesen't refill. I tested the repacing lines above but no effect at all. I would ask sincerely for help. :(

**Comment by debejerry** [comment]
@RKI91 would you mind posting your log file?
Which "manure wagon" did you use? 
Mod? 
if yes which exactly? 
These information would enable me to have a look into it and try later today,

**Comment by RKI91** [comment]
So

Here is my log (DB channels: 1, 2, 6, 12, 19) -> http://wklej.to/Af1dT
Here is a detail video with problem, step by step -> https://youtu.be/fWlhZ42q_MQ
And i used Fliegl STF 25000 VC from Giants as in game mod.

**Comment by pops64** [comment]
It is like I thought CP isn't detecting the slurry containers trigger probably because it is not in the list of triggers. I can't say for sure as I have no clue on how that part of CP works.

P.S there is additional debug printed in CP in game so leave that open when you record videos. Thanks

**Comment by RKI91** [comment]
In response to the previous question.
Vanilla slurry sprayer also doesen't refill with container from kottepack, but with vanilla container does it well.

**Comment by Raints** [comment]
Just watched the video and are you sure you set up course correctly. I never used Load/Merge
![untitled1](https://cloud.githubusercontent.com/assets/3618060/22607690/a5a7e48a-ea61-11e6-8742-676496809733.png)
 button for refill. Always used Append
![untitled2](https://cloud.githubusercontent.com/assets/3618060/22607709/aeddcdbc-ea61-11e6-9a53-8ca3eae5ce08.png)

I might be completely wrong to.

**Comment by pops64** [comment]
Its not that but you are correct. Merge may cause funny behaviors in mode 4 and 6 for refill course but not this(there is an exception when you can use merge in theses modes). This is the trigger not being in the list so CP doesn't know that it can refill there.

**Comment by RKI91** [comment]
@Raints I have done so more than once and usually had no major problems with button "Load/merge". 
I checked also the button "Append", but the effect was the same as before.

**Comment by pops64** [comment]
So I have got it fix for the MST have not tired anything else. building upon debejerry solution. Replace line 70 in specialtools.lua to
`if workTool.typeName == 'augerWagon' or workTool.typeName == 'FS17_kotteUniversalPack.kotteUniversal' or workTool.typeName == 'FS17_kotteUniversalPack.kotteUniversal_man' or workTool.typeName == 'FS17_kotteUniversalPack.kotteUniversal_hookLift' or workTool.typeName == 'FS17_kotteUniversalPack.kotteUniversal_mst' then`

There might be a way to get this line a little shorter but I do not know. I have discovered two bugs. Vanilla FRC if empty will not let the slurry sprayer to carry on will stay stuck trying to fill will post this separately.  Second bug is on the giants side with their IT runner mod. Their slurry container for that mod only accepts slurry it does not allow tools to refill from it(aka its a black hole of death for slurry).

Hopes this helps.

P.S the difference between append and merge is append adds the the course to the end of the currently loaded once.(this is what mode 4 and 6 are expecting) Merge will connect anything within 50m of the first crossing point of the currently loaded course(which is the stop point for field generated courses and usually the end but unless CP has changed the 50m thing if your stop point isn't near the first point of your refill course I am not sure what would happen probably nothing)

**Comment by ThomasGaertner** [comment]
can you give me clean download link ? I cant find it on the "clean" platforms ....

**Comment by ThomasGaertner** [comment]
try v.065 or higher and report ....

**Comment by hoefti10** [comment]
Hi, I have also a Problem with the Kotte Pack. I dont really sure, maybe i'll do something wrong.
I will sold my Manure with a Trailer from the Kotte Pack. I Start the Course on the Trigger in the near of my Pigs but Courseplay didn't fill the Trailer.
If you need Something in a .txt please tell me how and i will try to give u some more information.
BTW: The same issue i had when i will fill the Trailer with fuel.

**Comment by RKI91** [comment]
@pops64 Seems your changes works well, FRC will fill fine right now.
@ThomasGaertner I also tested changes with 0.65 but its doesen't work. I se them type "FS17_kotteUniversalPack.kotteUniversal" this type is used only for some trailers from this pack, not with all i think. Another bug is discovered by @hoefti10 seems fuel trailer doesen't refill on fuel triggers i tested this also.

**Comment by ThomasGaertner** [comment]
strange, works fine here
the types are :   
  Register vehicle type: FS17_kotteUniversalPack.kotteUniversal
  Register vehicle type: FS17_kotteUniversalPack.kotteUniversal_mst
  Register vehicle type: FS17_kotteUniversalPack.kotteUniFuel
  Register vehicle type: FS17_kotteUniversalPack.kotteUniversal_hookLift
  Register vehicle type: FS17_kotteUniversalPack.kotteUniversal_man
so string.match() should work except the fuel trailer

which changes by pops64 do you mean ?

**Comment by RKI91** [comment]
I mean changes in line 70 but my ignorance about the script does not come to that your changes are doing the same. Sorry about that I had an old version of cp v.064 -,-

After PROPER update to v.065 seems all works fine but the fuel trailer won't work fine although I think it is the fault of another mod called "Bio Diesel Raffinery" which uses fuel triggers from "FabrikScript" It seems that they do not cooperate with CP because in the standard fuel triggers on gas stations everything is ok.

**Comment by hoefti10** [comment]
I tested it with the universal_mini pendant on südhemmern... i will test it on a other map and maybe with athor pendants...

**Comment by debejerry** [comment]
@RKI91 sorry for beeing late, but as 
@pops64 said I missed to add the "kotteUniversal_mst" (which is in fact the FRC ["FeldRandContainer"])
I tried yesterday and as that one got added refilling a liquidmanure spreader at the FRC from the pack is no problem.

@ThomasGaertner  I didn't know the about the string.match function which is great here. :+1: 
But wouldn't it be better to just match to "kotteUniversal" instead of the whole name, 
because if someones going to edit the mod file name or it gets edited in the future the match wouldn't work anymore.

**Comment by hoefti10** [comment]
Other Map other Pendant, same issue.Unfortunately the same issue...

**Comment by pops64** [comment]
Solid manure has to be loaded by shovel in mode 1 and should sell at trigger. Use Mode 8 for liquid manure. What CP version are you using? Picture or video of how you have your course setup will help.

**Comment by debejerry** [comment]
@hoefti10 @pops64 @ThomasGaertner 
I think that @hoefti10 meant that the liquid manure transport mode doesn't work reliable.

Indeed I oberserved some strange behaviour that I can not fully understand.
@ThomasGaertner in commit "01.0067: bigfix for missing maxRotation in mods" you added
` and not vehicle.cp.isLoaded`
to line 1159 in toolManager.lua.


If I remove this addition in last version 01.0069 liquid manure transport works. :confused: 
Honestly I think that the evaluation ` and not vehicle.cp.isLoaded` is a good one, because nobody wants to refill a already fully filled trailer/barrel whatever.

During debugging once I was able to run Mode 8 for exactly 1 time, only the first run worked,
 after that even though all percentages (fillLevel and so on) were set so cp should refill, but it didn't.
But I wasn't able to get cp behave this way once again. :cry: 

It seems to me that once `vehicle.cp.isLoaded` is set to true it never gets reset to false.

So everytime the above mentioned line runs it evaluates `canRefill` to `false` (I think, I have no evidence on this) which then gives 

> [bg19 lp7659] %s: vehicle.cp.isLoaded or workToolSprayerFillLevelPct >= driveOn -> set vehicle.cp.fillTrigger to nil

in the log
I think that seems to be the bug thats causing this.


All of this are only suggestions as I've just startet looking at lua and scripting with FS.
Till now I was only doing some powershell and vbscript during workhours. :blush:

**Comment by pops64** [comment]
the not vehcile.cp.isLoaded was inserted into it to make the drive now button work if you were refilling mode 8 from something that empties otherwise it would stay stuck refilling or if the refill until percent was lowered.

**Comment by debejerry** [comment]
Not on the video side yet, :grin: 
As I said, to me there seems nothing wrong with evaluating if a tool "isLoaded" thats a good evaluation and i think it is indeed at the right place. :+1: 

but one thing is reproducable:
If said addition in toolManager.lua is present Mode 8 does not work reliable in that way that CP drives straight through the refill trigger without filling up. This is independant from the Kotte Universal Pack it also happens to the ingame Kotte TSA 30000. 

After I noticed that something kind of "broke" mode 8 I tried my known to work mode 8 route with every commit from 01.0069 to 01.0067 from @ThomasGaertner where I found the addition.
Commented it out and gave it a try: whoops mode 8 works again. 

And at a last resort and verification I took 01.0069, commented out `and not vehicle.cp.isLoaded` at line 1159 in toolsManager.lua and Mode 8 worked.

If I may help anyhow with additional debug logs, or if my explaination were insufficient, please let me know.

**Comment by pops64** [comment]
Just a video of how you are breaking mode 8. Cause the only way I was able to do it was the change the refill percentage to something lower than what was already in the slurry tank which this is the way it is intended to work.

**Comment by pops64** [comment]
I have been able only to produce it randomly. And its the fill level that is causing the issue imo. For me I noticed if it filled to a level below 3010 it wouldn't stop and above it would(I had mine only refill to 10%)

**Comment by pops64** [comment]
I have done further testing. And it seems completely random if it will stop or not

**Comment by hoefti10** [comment]
Hi,
Probably we spook Not from the Same Mode 😂
Sorry for this.  i would Sell the manure. For this Operation i choose the Mode 1 ?! Please Tell me if completly wrong ;)

**Comment by pops64** [comment]
@debejerry and @hoefti10 are you trying to deliver to sell triggers or an FRC. Sell triggers are net yet supported #1760 for that discussion. If that is not the bug you are talking about. I need a video of what is exactly occurring cause I have only found one bug and it wasn't related to this issue.

**Comment by hoefti10** [comment]
Whoops, for sure we can close , on the course is a sell trigger. Otherwise is Not the sell trigger the problem... he didnt fill up. Sell trigger works fine when i fill in hand mode. I try to upload a video tomorrow

**Comment by debejerry** [comment]
@pops64 I always tried mode 8 with BGA digestate as the fillTrigger and FRC as unloading/overloading point. (a "classical" liquid manure transport route)
I also didn't realize that @hoefti10 tried to sell liquid manure at i.e the gardencentre sell trigger.

As for your suggested fix. I had no time to test it yet but will probably give it a try this evening.

**Comment by pops64** [comment]
OK I will try with the digesate trigger. I was using the pig trigger. This may be where your bug is.

**Comment by pops64** [comment]
I hate to double post but. I have refined my previous fix. Here is the branch for it
https://github.com/pops64/courseplay/tree/Mode8Fixv2

It adds `vehicle.cp.isUnloading = false;` to line 173 and line 179. This is needed so mode8 can clear out previous runs of mode8 which is what is causing this bug

**Comment by pops64** [comment]
Please test with the latest commit and report back. Thanks

**Comment by pops64** [comment]
Assumed fixed due to inactivity.
