### ISSUE TITLE
Problem with new update

### ISSUE THREAD

**Issue by Tonton1969** [Courseplay/courseplay#1721]
Hello with the newest version I have the following problem:

LUA call stack:
  =C:/Users/Tonton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/signs.lua (40) : getChildAt
  =C:/Users/Tonton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/CpManager.lua (42) : setup
  dataS/scripts/BaseMission.lua (548) : loadMap
  dataS/scripts/FSBaseMission.lua (1699) : loadMapFinished
Warning (LUA): 'link': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (630): expectedType == Value::VoidType
LUA call stack:
  =C:/Users/Tonton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/signs.lua (41) : link
  =C:/Users/Tonton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/CpManager.lua (42) : setup
  dataS/scripts/BaseMission.lua (548) : loadMap
  dataS/scripts/FSBaseMission.lua (1699) : loadMapFinished
Warning (LUA): 'setRigidBodyType': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (630): expectedType == Value::VoidType
LUA call stack:
  =C:/Users/Tonton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/signs.lua (42) : setRigidBodyType
  =C:/Users/Tonton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/CpManager.lua (42) : setup
  dataS/scripts/BaseMission.lua (548) : loadMap
  dataS/scripts/FSBaseMission.lua (1699) : loadMapFinished
Warning (LUA): 'setTranslation': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (630): expectedType == Value::VoidType
LUA call stack:
  =C:/Users/Tonton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/signs.lua (43) : setTranslation
  =C:/Users/Tonton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/CpManager.lua (42) : setup
  dataS/scripts/BaseMission.lua (548) : loadMap
  dataS/scripts/FSBaseMission.lua (1699) : loadMapFinished
Warning (LUA): 'setVisibility': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (630): expectedType == Value::VoidType
LUA call stack:
  =C:/Users/Tonton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/signs.lua (44) : setVisibility
  =C:/Users/Tonton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/CpManager.lua (42) : setup
  dataS/scripts/BaseMission.lua (548) : loadMap
  dataS/scripts/FSBaseMission.lua (1699) : loadMapFinished
Warning (Script): Unknown entity id 0 in method 'delete'.
LUA call stack:
  =C:/Users/Tonton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/signs.lua (45) : delete
  =C:/Users/Tonton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/CpManager.lua (42) : setup
  dataS/scripts/BaseMission.lua (548) : loadMap
  dataS/scripts/FSBaseMission.lua (1699) : loadMapFinished
Error: failed to load i3d file 'C:/Users/Tonton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/img/signs/cross.i3d'
Warning (Script): Unknown entity id 0 in me

**Comment by ThomasGaertner** [comment]
please post the whole log to gist and deliver the link...

**Comment by Tonton1969** [comment]
Not more necessary with the last version it works without any problem
