### ISSUE TITLE
Game Freez

### ISSUE THREAD

**Issue by hoefti10** [Courseplay/courseplay#1725]
Hi Guys, 
at first, great work. Really nice Mod.
My problem is, if ja start a course to fill , for example, the compmaster on the Suedhemmern map( the issue is on every map) my game freez when i reched the upload trigger. every time, doesnt matter which car or map or which pendant. at least i will show u my log and a little screen...
log:http://workupload.com/file/KMPccK3
Screen:http://www.directupload.net/file/d/4619/fh2ocsta_jpg.htm

Thanks for ur time and hard work.

**Comment by ThomasGaertner** [comment]
#1685
