### ISSUE TITLE
Tipper Not Empting again?

### ISSUE THREAD

**Issue by Beebtrek** [Courseplay/courseplay#1726]
Hi Guys I thought this one was Fixed. But this is still there when the Harvester gets unloaded by tipper run and Tipper is Full and it proceeds to Unload point. It only Dumps part of the load. Then carries on with the route ? Sorry being away from here for a bit so this is the version I am using.

5.01.00058.dev

Regards Lankspeed.

**Comment by ThomasGaertner** [comment]
which unload point was it and which fruit ?

**Comment by Beebtrek** [comment]
Barley. The Main Silo at Goldcrest Farm. Just tried to get it to do it again and it was Fine.
Sorry Thomas, I am Confused?

**Comment by pops64** [comment]
Is your grain silo full? Not sure how mode 2 works will full silos but it looks like it display a message for a set time then carries on.

**Comment by Beebtrek** [comment]
No the silo is only 20% full. So not that sorry.

**Comment by ThomasGaertner** [comment]
can you replicate it ? I can't . please test with v 0064 or higher , I did some changes in the scipt since 0058..

**Comment by Beebtrek** [comment]
Since the error I have only seen it once I have updated to 0064 and have not seen it again. So I will continue to test with the latest version in a few minites. Will be testing for rest of today and all weekend at least. So leave it open will report on Monday if that is ok Thomas.

Regards Lankspeed (Stephen).

**Comment by Beebtrek** [comment]
Ok It did it again. Out of 12 Trips approximatly. Gear in use is as follows:
Unloaded from a New holland Combine programmed route to Farm Silo.
Using a Fendt 900 Vario tractor.
Joskin Drakkar 8600 trailer, fully loaded with 47000L of Wheat.
But it left 6585 in the trailer before moving off ramp.

Using Version 5.01.00064.dev

Regards Lankspeed.

**Comment by Beebtrek** [comment]
Also It has done the same thing dumping loads at the Rail Depot i.e. From the Silo to rail. Using same trailer and Tractor combo.
Regards Lankspeed.

**Comment by pops64** [comment]
Could we possible get a video/log of what is occurring with 1, 2 and 19 active? Thanks

**Comment by Beebtrek** [comment]
Video would be a problem due to the fact I cannot duplicate it on a regular basis. But Log yes Do my best. You mean the FS17 log, after enabling the debug options in Courseplay. I am seeding fields at the moment. But a few hours will start harvesting and unloading as this is when the fault happens most of the time.

Thanks.

**Comment by pops64** [comment]
Yes the FS 17 log. And try to get it with only the tipper running

**Comment by Beebtrek** [comment]
Another thing I have seen this with several maps and with all my mods loaded and also as a bear game with just courseplay. At this time I am using modded map and all mods loaded. But we will do the best we can.

Thanks for all your help.

**Comment by MartinGrisotto** [comment]
Same here, it's shoot and miss. It dumps the load in like 9/10 situations, but that one time tractor drives off the ramp with grain still being in the trailer.

**Comment by Beebtrek** [comment]
> Same here, it's shoot and miss. It dumps the load in like 9/10 situations, but that one time tractor drives off the ramp with grain still being in the trailer.

Ah Great a confirmation I am not waffling, thanks Martin.

Yes that is about the same Ratio I am getting 9/10. Also it happens on delevery runs to other sites. So it seems to be in the UNLOAD Code. If that helps.

Regards Lankspeed.

**Comment by Beebtrek** [comment]
Nailed IT. Ok fault appears when you switch to another vehicle like Harvester it the abarts the dump. At least that is how I simulated it. Log is attached to this message. Also I will edit this post with a link to video to demo the Bug / Feature.

Regards Lankspeed.
[log-01.txt](https://github.com/Courseplay/courseplay/files/752324/log-01.txt)

**Comment by Beebtrek** [comment]
Ok this is of course using switcher mod to select harvester. But it also works if you use TAB. That seems to simulate the fault. But it does also occur randomly I just could net get it to do it this morning. Hope all this helps.

Regards Lankspeed.

**Comment by ThomasGaertner** [comment]
I will try to figure out what happens there....

**Comment by Beebtrek** [comment]
Well at least we can duplicate this bit of the Error. That is if it is an error. I think so, due to the random ones. They only occur about 1 in 10 or more times so is this a priority?
As it is, I do and all the Users thank you for your efforts. As an Assembler programmer and some 4th gen stuff I know how bug chasing can be a pain. BLIND Alleys do not help.

Thanks.

**Comment by MartinGrisotto** [comment]
It's happening regardless if i swith from harvester or other tractor, or even from standing outside. And i can replicate it every time.

And i confirm - using TAB doesn't brake unloading.

**Comment by ThomasGaertner** [comment]
yea I've made some tests and its a can'tFix. its a Giants function which throws us out of the trigger 
Trailer.lua(369)( if somebody is interested) .... so sorry Guys

**Comment by Beebtrek** [comment]
Thanks for Trying. That does show the system sometimes can not be fixed.

Regards Lankspeed.
