### ISSUE TITLE
No unloading in Driving-Silo/Crashing into the wall

### ISSUE THREAD

**Issue by Tragger** [Courseplay/courseplay#1728]
First of all, thank you for this great project. I realy enjoy courseplay.

But now, I have a problem. I tried it with different trailers on map Goldcrest Valley (standard-no mod).

I use the combined mode but the trailer didn't get unload in the driving-silo. My truck or my tractor are driving into the wall on the side or they drive straight into the building behind the driving-silo without unloading. (at Biogas plant)

I have no idea how can I fix. I maked everything like in courseplay 4 in faming simulator 15. I stopped all mods and I tried it again with the courseplay 5.01.00062.

A second thing. If I leave my tractor while the tractor is driving into the wall, my game crashes. I can't tab into another tractor. The game is going into a freeze.

**Comment by pops64** [comment]
pictures or video?
log?

**Comment by bigjoker76** [comment]
I have the same problem while reversing in a BGA silo
![fsscreen_2017_02_02_07_22_42](https://cloud.githubusercontent.com/assets/6426554/22539252/09ff6bfa-e919-11e6-9d2f-ac967aaef306.png)

https://www.dropbox.com/s/gcnlq3a3573dy6y/log.txt?dl=0

**Comment by Tragger** [comment]
This morning I tested again.

Here my log and some pictures.

Log: http://www.filedropper.com/log_47
Pict 1-3: http://www.filedropper.com/1_603
http://www.filedropper.com/2_301
http://www.filedropper.com/3_134

Sry, I havn't an other filehoster.

**Comment by dkfiremann** [comment]
Why not add them to your message? 
You can drag the image and log file to the message box, and they will be uploaded to Github. 
No need for external file host.

**Comment by Tragger** [comment]
Thx dkfiremann.

I didn't found this option this morning.

**Comment by pops64** [comment]
it looks like this is the error causing both your issues
```
Error: Running LUA method 'update'.
dataS/scripts/triggers/TipTrigger.lua(943) : attempt to compare number with nil
```

**Comment by Tragger** [comment]
Does it is my fault in the courses? Or does it is a problem with the script?

What can I do to solve my problem?

**Comment by AgroMeester** [comment]
Greetings holy masters of CoursePlay,

I can confirm this issue an have added my log for reference.


Keep up the great work guys, this is truly the mod that rules them all!


[log.txt](https://github.com/Courseplay/courseplay/files/749946/log.txt)

**Comment by Andreas115** [comment]
Ich habe dasselbe Problem. Sobald der Traktor rückwärts in das Silo fahren soll, friert das ganze Spiel ein. Das passiert jetzt ständig wobei nur Courseplay der einzige Mod ist.

I have the same problem. As soon as the tractor moves backwards into the silo, the whole game is freezing. This is happening all the time, only courseplay is the only mod.

Courseplay V5.01.00063

**Comment by ThomasGaertner** [comment]
try v .0064 or higher and report....

**Comment by JD1020** [comment]
Hey guys, 

great job, is working now without any issues. Test without any other mods on Sosnovka and Golcrest Valley.

Thx a lot for this mod. Keep up your great work.

**Comment by Andreas115** [comment]
Thanks!
it works fine with V5.01.00064

**Comment by lcc1211** [comment]
I had this issue on a mod map, but now it seems to have cleared up as of yesterday.  Thank you for the fix.

**Comment by Tragger** [comment]
It's fixed. Thx for this fast service. I like your job with this mod!!!

**Comment by pops64** [comment]
Thanks for the reply. Closed to keep the issues area clean
