### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by DuckTape325** [Courseplay/courseplay#1729]
Hey!
I was trying to upload a courseplay mod to FS17 web server so I could use it in my server. Unfortunetly it said: "Uploaded mod file not supported. Only Farming Simulator 17 mods are supported."
What should or could I do to get it to my FS17 server?
Sry for bad English!

**Comment by Satissis** [comment]
well CP is not MP ready, so MP is turned off for it, which also means that the dedicated server looks for that and tell you that the mod is not supported.

**Comment by pops64** [comment]
Closed to keep the issues area clean.

**Comment by Quintto** [comment]
is MP support coming or are you guys just nog going to work on it?

**Comment by Satissis** [comment]
Only time will tell
