### ISSUE TITLE
Courseplay does not support the Krone Swadro 2000

### ISSUE THREAD

**Issue by DynamicXYZ** [Courseplay/courseplay#1731]
Please add support for Krone Swadro 2000 so my game doesn't crash when I hitch onto it and move.

The mod can be downloaded from Giants server (in-game or mod hub).

**EDIT:** The log file is [here](https://gist.github.com/374124efe2bb0e332c60eb3d9146d894.git). I don't recommend trying this out for yourself since the Courseplay logging dropped my fps by 30.

**Comment by pops64** [comment]
Here is the [Link](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=61688&title=fs2017)to mod

**Comment by pops64** [comment]
Closed to keep the issues area clean. This is a problem with the Krone Swadro not CP
