### ISSUE TITLE
Fieldwork course harvesting Chaff issue

### ISSUE THREAD

**Issue by DynamicXYZ** [Courseplay/courseplay#1732]
I'm trying to harvest chaff with a forage harvester but it just stops at the beginning or at the end of the field lane and sits there. It may turn around at the end of a field lane but it won't continue after that.

Here's a snippet from the log file:
```[dbg6 lp255215] BiG X 1100 (#5): updateWorkTools(BiG X 1100, "BiG X 1100 (#5)", isImplement=false) (mode=6)
[dbg6 lp255215] BiG X 1100 (#5): askForSpecialSettings(..., "BiG X 1100 (#5)")
--------------------------------------------------
[dbg6 lp255215] BiG X 1100 (#5): updateWorkTools(BiG X 1100, "XDisc 620", isImplement=true)
--------------------------------------------------
[dbg6 lp255215] BiG X 1100 (#5): frontWheelToDirectionNodeOffset=-0.00, frontWheelToRearWheel=3.47
[dbg6 lp255215] BiG X 1100 (#5): frontWheelToRearTrailerAttacherJoints[12]=0.66
[dbg6 lp255215] BiG X 1100 (#5): frontWheelToRearTrailerAttacherJoints[2]=4.87
[dbg6 lp255215] BiG X 1100 (#5): frontWheelToRearTrailerAttacherJoints[3]=4.87
[dbg6 lp255215] BiG X 1100 (#5): turningNodeToRearTrailerAttacherJoints[12]=0.66
[dbg6 lp255215] BiG X 1100 (#5): turningNodeToRearTrailerAttacherJoints[2]=4.87
[dbg6 lp255215] BiG X 1100 (#5): turningNodeToRearTrailerAttacherJoints[3]=4.87
--------------------------------------------------
[dbg6 lp255215] BiG X 1100 (#5): XDisc 620 Vehicle Point(1) width: ztt = 2.6376342773438
[dbg6 lp255215] BiG X 1100 (#5): XDisc 620 Vehicle Point(1) height: ztt = 1.5899658203125
[dbg6 lp255215] BiG X 1100 (#5): XDisc 620 Vehicle Point(1) start: ztt = 2.6375732421875
[dbg6 lp255215] BiG X 1100 (#5): setMarkers(): cp.backMarkerOffset = 1.6376342773438, cp.aiFrontMarker = 2.3399658203125
[dbg6 lp255215] BiG X 1100 (#5): workTool "XDisc 620" added to workTools (index 1)
[dbg6 lp255215] BiG X 1100 (#5): askForSpecialSettings(..., "XDisc 620")
[dbg6 lp255215] BiG X 1100 backMarkerOffset set to 1.6m
##################################################
[dbg6 lp255215] BiG X 1100 (#5): Set turnDiameterAuto to 10.48m (2 x vehicleTurnRadius)
[dbg6 lp255215] BiG X 1100 (#5): getHighestToolTurnDiameter(BiG X 1100)
[dbg6 lp255215] BiG X 1100 (#5): turnDiameterAutoMode is active: turnDiameter set to 10.48m
--------------------------------------------------
--------------------------------------------------
[dbg6 lp255215] BiG X 1100 (#5): workTools:
[dbg6 lp255215] \___ [1] = XDisc 620
##################################################
[dbg6 lp255215] BiG X 1100 (#5): getTotalLengthOnWheels()
[dbg6 lp255215] BiG X 1100 (#5): Using frontWheelToRearWheel=3.47
--------------------------------------------------
[dbg6 lp255215] BiG X 1100 (#5): totalLength=3.47, totalLengthOffset=-0.00
--------------------------------------------------
[dbg2 lp256802] nil: SiloTrigger Added! (onEnter)
[dbg2 lp256831] nil: SiloTrigger Removed! (onLeave)
[dbg2 lp256851] nil: SiloTrigger Added! (onEnter)
[dbg2 lp256869] nil: SiloTrigger Removed! (onLeave)
[dbg2 lp264540] nil: SiloTrigger Added! (onEnter)
[dbg2 lp264569] nil: SiloTrigger Removed! (onLeave)
[dbg2 lp264589] nil: SiloTrigger Added! (onEnter)
[dbg2 lp264608] nil: SiloTrigger Removed! (onLeave)
[dbg2 lp264901] nil: SiloTrigger Added! (onEnter)
data/vehicles/steerable/krone/kroneBiGX580.i3d (155.94) ms
C1ZOffset = -1.08m, C2ZOffset = -1.10m```

**Comment by pops64** [comment]
Chaff Harvesters wait at the end of a lane for the following tipper to move. Then sits at the beginning for the following tipper to show up. So with out a picture or a video its hard to tell what is happening. I know if 15 if your following tipper was under powered it would causes issues with the chaff harvester accelerating faster than the tipper.

**Comment by DynamicXYZ** [comment]
@pops64 

I've tried to use Debug channel 4 but it didn't log anything.
You can watch [here](https://www.dropbox.com/s/do4a4er8ye70gup/Farming%20Simulator%202017%2002.02.2017%20-%2018.20.47.01.mp4?dl=0).

**Comment by pops64** [comment]
Yea. The combine isn't telling the driver that it has finished with the lane it is just telling it to stop has seen at the 3:40 mark. Did you try it with a different tipper? Most likely related to the changes to fix the issue I listed ealier

**Comment by DynamicXYZ** [comment]
Yeah, I tried a different tipper, several. All of them had the same problem. Every time I changed the tipper and went back to the harvester it would continue but then stop again at the end of the field. 

But when I tried an auger wagon it continued again and again flawlessly. So it just has really poor support of tippers I would guess.

**Comment by ThomasGaertner** [comment]
hmm works fine here...
I think, its not the tippers, it's related to the chopper.
could you tell me , which chopper is this exactly ? is it the one from modHub ? 
would you please try following: 
- use the vanilla BigX580 with the same cutter
- if the cutter is also a mod, try with the vanilla cutter
-activate debug 4 and 6 before starting up the tools and post the log...

**Comment by DynamicXYZ** [comment]
@ThomasGaertner 

I have used the Vanilla equipment in the video I linked in my first comment.
Here's another log. https://gist.github.com/62815cdc20d3dda0dec8938e4eae00c4.git

**Comment by lcc1211** [comment]
For the most part my tractor drove on the non-crop side of the forage harvester; however, at the end of each lane the harvester would come to a halt all while still running.  Tabbing over to the tractor shows the line "harvester is telling me to stop." The only way to get it going again is to stop CP on the harvester, do the manual turn and drive right up to the fruit and restart the course.  Even when the tipper is full the tractor won't take it to the silage clamp.

**Comment by ThomasGaertner** [comment]
can you give me the savegame from the video and a link to the map ? is there a reason why the chopper goes with offset ?

**Comment by DynamicXYZ** [comment]
I don't have the savegame from the video anymore but I do have a new savegame I'll slide towards you.
Um I don't think I've set any offset but if you're talking about the field not lining up with my tool it's because I was switching tools with different width's.

**Comment by ThomasGaertner** [comment]
K I will check it ,

concerning the offset: 

![image](https://cloud.githubusercontent.com/assets/3279913/23095800/586b08d6-f610-11e6-98a3-a76fcc241c45.png)

**Comment by DynamicXYZ** [comment]
Oh, I did have a lane offset. To be honest I don't remember why but maybe because I was trying to figure a way around the problem.

**Comment by ThomasGaertner** [comment]
OK, now I have it : the chopper does his job and goes over the field and converts crop to chaff. So in the trailer is chaff. Now we are reaching the field edge and the chopper gets some gras and converts it to grass.
If he wants to try to put the grass to the trailer, the trailer says "Stop, its the wrong fillType" so all stop and  have no clue what to do. I can't change anything in the script to solve it without causing other issues instead.
My recommendation is to use one line of headland around the field and all is fine.

please test and report..... thanks

**Comment by lcc1211** [comment]
@ThomasGaertner Since I no longer use CP to drive the forage harvester it mostly works out OK - but only as long as I have a standard square/rectangle shaped field. Thank you for looking into this. I think the header row will solve my issue if I want to do this using an odd shaped field.

**Comment by ThomasGaertner** [comment]
@DynamicXYZ : is it Ok for you ?

**Comment by DynamicXYZ** [comment]
@ThomasGaertner It will have to do. The only concern I have now is that sometimes the header lane will cut outside the field. Is there any way to force the calculation for the header to stay inside the field even if there is an overlap?

Also as you explained the problem is it at all possible to toggle the thing that shoots the chaff out off until the tool header takes something else?
