### ISSUE TITLE
A small problem..... 

### ISSUE THREAD

**Issue by Buchhave1** [Courseplay/courseplay#1734]
Hey

I am playing on the standard map from giants (Gold Crest Valley) 

CP version  (v5.01.00063)

And ever time the CP going to unload chaff in the silo on the dairy farm i get this lua error 

I have use this video as a guide.....  https://www.youtube.com/watch?v=40FDWBvFqKo 

i use only standard machinery.... 

Only mod is CP.... 

log: http://pastebin.com/EPgMgUGD

The course: http://pastebin.com/8YtPJxF7

I dont know if i have get right to set up the course ot not 

Buchhave

**Comment by pops64** [comment]
#1728 same error

**Comment by ThomasGaertner** [comment]
as @pops64 said ...
