### ISSUE TITLE
Game save not loading after latest update

### ISSUE THREAD

**Issue by Landykid** [Courseplay/courseplay#1735]
after updating. my game save will not load at all if I create a new one it will load no problem at all. I have tried with and without all my mods still have the same issue.

[log.txt](https://github.com/Courseplay/courseplay/files/751999/log.txt)

**Comment by pops64** [comment]
Try loading a backup save and see if that fixes the issue. Also try loading CP with out another mods enabled. I am running v64 with out any issues. So you have either a mod conflict or a corrupted save.

**Comment by Landykid** [comment]
I have tried on two current game saves both of them do not load on the current version of CP but they will load up perfectly fine on an old version courseplay-5.01.00032.

and I have also created a new game save with every single mod activated and it worked perfectly fine with the new version of CP

**Comment by pops64** [comment]
Could you upload one of the save games that aren't working? Thanks

**Comment by Landykid** [comment]
after quite a bit of testing and trial-and-error last night. I have found the issue to be vehicles that CP does not work with as soon as I remove vehicles I knew CP did not work with the game save loaded up no problem. as soon as I bought them again and save to the game. I was back to square one.

before the recent updates, it was just a case of CP did not open on those tractors.

**Comment by pops64** [comment]
Which ones. CP recently updated in 64 to how it is loaded into mods. Thanks

**Comment by Raints** [comment]
I did look your log and try to rename your Courseplay to ZZZ_Corseplay instead of just courseplay. And some problems should be gone.

**Comment by Landykid** [comment]
setting the name to  ZZZ_Corseplay fixed the issue thank you guys

**Comment by pops64** [comment]
Did you test it with v65 and above? that version should fix it having CP to be renamed to ZZZ_Courseplay. FS17_Courseplay should work now with all mods

**Comment by Landykid** [comment]
it was on yesterday's version which was v64  either way if the issue seems to have been fixed when I changed the name

**Comment by pops64** [comment]
Ok I will close this out has you seem to have it fixed
