### ISSUE TITLE
Copy Course BGA Silo Bug

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1738]
When you copy a course from a tipper and use that course in mode 2 for BGA silos you receive this error
```
Error: Running LUA method 'update'.
dataS/scripts/triggers/TipTrigger.lua(937) : attempt to index a nil value
```

**Comment by Raints** [comment]
Same error for me at BGA silo. Didnt copy course, just used previous course. 
`Error: Running LUA method 'update'.
dataS/scripts/triggers/TipTrigger.lua(937) : attempt to index a nil value`

This silo: http://fs-uk.com/mods/view/38494/fs17-silage-bunker

**Comment by ThomasGaertner** [comment]
could you do me favour and replace  in toolManager.lua (867) 
local distanceToTrigger, bestTipReferencePoint = 0,0;
by
local distanceToTrigger, bestTipReferencePoint = 0,1;
and try again

**Comment by Raints** [comment]
> could you do me favour and replace in toolManager.lua (867)
local distanceToTrigger, bestTipReferencePoint = 0,0;
by
local distanceToTrigger, bestTipReferencePoint = 0,1;
and try again

For me it worked, no error's and log is clean. Thanks!

**Comment by ThomasGaertner** [comment]
just for my interest: which trailer did you use ?

**Comment by Raints** [comment]
> just for my interest: which trailer did you use ?

First I thought its ingame KRONE TX 560 D, but then I found out its not. 
Its TX 560 D from this pack: https://gamesmods.net/farming-simulator-2017/mods-packs-fs17/69324-krone-pack-by-stevie-v10.html

You think its a bad mod?

**Comment by ThomasGaertner** [comment]
maybe there is something other than expected , but if it works now, I will close here ...
