### ISSUE TITLE
Clark C80D From ModHub  not working with CP any ideas

### ISSUE THREAD

**Issue by Landykid** [Courseplay/courseplay#1739]
Thank you for those who've helped me with the previous issue I had.
I was just curious if there is a way of fixing this issue with one Pacific mod on the CP its the 

From The Mod hub  http://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=60659&title=fs2017

The Error.
C:/Users/Matt/Documents/My Games/FarmingSimulator2017/mods/FS17_ClarkForklift/StaplerLS17.i3d (145.54) ms
FS17_GearboxAddon: looking for default configuration (defaultTractors)
Error: Running LUA method 'update'.
[builtin:deg]:0: attempt to perform arithmetic on a nil value

**Comment by ThomasGaertner** [comment]
try v .0067 or higher and report  ...

**Comment by Landykid** [comment]
you guys are absolute Legends thanks working no problem at all

**Comment by Anonymous-any** [comment]
I love you ! solved for all's my buy mod's :) problem but it's not about the Clark C80D concerned. Consequently some ticket's can be closed I think. Best regards !

**Comment by pops64** [comment]
Closed to keep issues area clean
