### ISSUE TITLE
Courseplay menu too small to read in 4k

### ISSUE THREAD

**Issue by Rbk3** [Courseplay/courseplay#1740]
Hello,

I am not sure this is the correct place to add this, but the menu is much too small for me to read in 4k, as it is 4x smaller than when playing at 1080p.  Is there any way to adjust the size of the menu? Perhaps a setting could be added, as 4K is becoming much more common.

**Comment by Satissis** [comment]
Nop that's not possible, at least not with the current hud setup.

**Comment by Satissis** [comment]
Thomas and I had an talk about this yesterday and we might give it a go to see how much we would have to change in our hud code to take the game hud scale into account.

This don't mean that we will do it, but if it's not that much of time consuming to do, then we might get it done before v5.02 release. Only time till tell.

**Comment by Beebtrek** [comment]
Oh yes please I use a 3440x1440 34 inch screen and the text some times i resort to a magnifier.
Cheers.

**Comment by Satissis** [comment]
Btw: could you take a screenshot of it, so we have something to reference with ?

**Comment by Beebtrek** [comment]
Ok here it is sorry for the size.
![fsscreen_2017_02_08_12_52_39](https://cloud.githubusercontent.com/assets/5612136/22738070/c7a3cbcc-edfd-11e6-9254-893e11a3db82.png)

**Comment by Beebtrek** [comment]
Hope that is what you want.

**Comment by Rbk3** [comment]
I really appreciate you seriously looking into this :)

I will send a screen Friday when I get a chance. Currently away from home for work.  At 4k it is even smaller than the above users screen shot, about half the size.

**Comment by Rbk3** [comment]
![20170211032148_1](https://cloud.githubusercontent.com/assets/25557740/22852395/5e14e11a-f009-11e6-8977-8e964ad309e0.jpg)

Here is what my HUD looks like in 4K.

**Comment by turbostar190** [comment]
@Satissis Maybe you can make an external xml config file like GPSMod where we can define hud size.
Example:
```
<GPS>
    <GPShud>
        <HUDsize>0.750000</HUDsize>
    </GPShud>
</GPS>
```

**Comment by Satissis** [comment]
Try again with v01.0076 or higher and report back.

I found something that might had been wrong in the code, since it was already being scaled based on the screen size.

I have commented it out for now for testing purpose, so could you make an screenshot in 4k and in 1080p again to compare it.

**Comment by Beebtrek** [comment]
Well I like that it is great. on the 3440x1440 34"
![fsscreen_2017_02_12_23_46_45](https://cloud.githubusercontent.com/assets/5612136/22867303/ab2afc26-f17d-11e6-89c8-ba0b82677873.png)

**Comment by Beebtrek** [comment]
What will the 4k look like i wonder. I should think ok. 1080p emm lets hope the scaling does not make it too big.

**Comment by Rbk3** [comment]
Here is 4k and 1080p now. Also, is having the menu off center intentional or is that an issue on my end?  In 4k it was in the center before, but 1080p was slightly to the right, now 4k is the same, slightly to the right. I notice while watching video's on youtube that all theirs are centered. 


![20170213023239_1](https://cloud.githubusercontent.com/assets/25557740/22874622/15f92390-f195-11e6-8277-6bdf25afd27a.jpg)
![20170213023112_1](https://cloud.githubusercontent.com/assets/25557740/22874623/15f9872c-f195-11e6-85f3-303e57b89acb.jpg)


Also, do you guys have a donation link? I would like to show some appreciation for addressing this.

**Comment by Beebtrek** [comment]
The main home page. link at bottom.
http://courseplay.github.io/courseplay/

**Comment by Satissis** [comment]
The offcenter is because the hud position is already saved.
To fix it, go into your savegameX folder and locate and open courseplaySettings.xml in a text editor like notepad++
There should be a line looking something similar to this one:
`<courseplayHud posX="0.335938" posY="0.026667"/>`
Delete that line and save the file.
Now once you start up fs again, it will recalculate the center position and save that value once you save your savegame.

**Comment by Satissis** [comment]
Btw: you you guys want me to add in a scale value to the settings as well, so you can scale it to your likings? + working with giants hud scale value as well ?

**Comment by Rbk3** [comment]
Perfect, that was a simple fix, back in the center now. Thanks!


I think giving the user the ability to choose the size of the HUD would be a great option. I play with the Giants HUD scale at 70% and I think if the courseplay HUD was 70% of its new size it would be perfect for me and my seating distance.  Every user is different I am sure, so more choice the better. 

I am not picky though, I am just happy I am able to read it now with out having to move closer to my TV to make changes. 👍  Thanks again for all your hard work on this issue and on courseplay in general.

**Comment by Beebtrek** [comment]
Yes I would like to beable to size the Hud too please. As to donations well have done in the past and will do now. Well when I get paid in a few days. I like so many others really feel this mod is worth donating to.

Thank You.

**Comment by Satissis** [comment]
Implemented in v01.0082.
Hud now follows the ui scale set in the game options.
You can also manually change the hud scale in the courseplaySettings.xml inside your save folder.
There is an guide lines to follow in the courseplaySettings.xml as well for that.
Try it out and report back.

**Comment by Rbk3** [comment]
It's perfect! Thanks so much. The scaling matching my HUD at 70% couldn't be a more perfect size. 👍

**Comment by Satissis** [comment]
Nice :) glad you liked it ;)
I'll close here then :)
