### ISSUE TITLE
Giving water to cattle

### ISSUE THREAD

**Issue by saku05** [Courseplay/courseplay#1741]
Hello
Does the mod 8 work properly? I put a P towards the cows, the pigs and the sheeps. Loading water is normal, but unloading is not done properly.
Joskin Trailer

**Comment by ArthurCueio** [comment]
if you put on transfer grain mode (mode 1) it will unload properly, but sometimes it don't leave the loading point when full

**Comment by lcc1211** [comment]
Create your course using the Manure transfer mode.  Here is how I do mine:  Start at a water source. If the water bowser is empty it will fill to full.  Drive the vehicle to the cow's water trough.  Place a waypoint there.  It should start filling the water and continue until the trough is full or until the bowser is empty.  I have a video of the entire route here:  https://www.youtube.com/watch?v=w_N_nS8KUUo

**Comment by saku05** [comment]
thanks guys
With the manure mod, it work ok.
I started at the farm and not at the water source

**Comment by lcc1211** [comment]
Glad it is working for you.
