### ISSUE TITLE
Suggestion: Turn manuver

### ISSUE THREAD

**Issue by jmj486** [Courseplay/courseplay#1742]
When i try to record a fieldwork route and come to a corner i hit "Start turn manuver" , go to the spot where I wise to start again, hit "stop turn manver".

When it try to run the course, CP use its own way to turn around and thereby hit an obstacle and get stock.

Can you give us the option to record how the tractor should make the turn?

**Comment by Admilson** [comment]
I have always had this situation at some point when it ends up hitting an obstacle when it is maneuvering, maybe it would be interesting if the tractor entered the field and perform the maneuver going to the tractor or at the start of the route without having to make the curve out of the field.

**Comment by Satissis** [comment]
@jmj486 That will not be possible atm. All the turn maneuvers are based on 180 degree turns, so if you make an 90 degree turn, then it wont work as intended. If you are trying to record an manual headland, you have to do that without using the turn button.
An option to record the turn is also not possible/ that easily to make and would require allot of time on our end to do. More than I want to do atm.

@Admilson That's what we have headlands for, even that I know that they are not that perfect in corners, but it's the only option atm.

I'm going to close here to keep the issues clean.
