### ISSUE TITLE
Silage slide

### ISSUE THREAD

**Issue by xerion8300** [Courseplay/courseplay#1743]
Hello,

If I push silage into the BGA silo, my tractor does not drive off the course.
He drives from the park position to the silo, and then he only drives in the circle

**Comment by Satissis** [comment]
[How to provide a nice and sexy bug report](https://github.com/Courseplay/courseplay/wiki)

**Comment by xerion8300** [comment]
Here are a link.
https://gist.github.com/xerion8300/f56fdc8e9a3438d6f50811b3a2bddc5f
The Map is the Papenburg_meets_Ammerland
The version is the <version>5.01.00066</version>
Here a few pictures of driving in the circle

<a href="http://abload.de/image.php?img=fsscreen_2017_02_06_176szd.png"><img src="https://abload.de/thumb/fsscreen_2017_02_06_176szd.png" /></a> <a href="http://abload.de/image.php?img=fsscreen_2017_02_06_133sgm.png"><img src="https://abload.de/thumb/fsscreen_2017_02_06_133sgm.png" /></a> <a href="http://abload.de/image.php?img=fsscreen_2017_02_06_1iismv.png"><img src="https://abload.de/thumb/fsscreen_2017_02_06_1iismv.png" /></a> <a href="http://abload.de/image.php?img=fsscreen_2017_02_06_11rsp6.png"><img src="https://abload.de/thumb/fsscreen_2017_02_06_11rsp6.png" /></a> <a href="http://abload.de/image.php?img=fsscreen_2017_02_06_1etsd5.png"><img src="https://abload.de/thumb/fsscreen_2017_02_06_1etsd5.png" /></a> 

And now 
Here a few pictures where it works on the same Map
<a href="http://abload.de/image.php?img=fsscreen_2017_02_06_1a3s26.png"><img src="https://abload.de/thumb/fsscreen_2017_02_06_1a3s26.png" /></a> <a href="http://abload.de/image.php?img=fsscreen_2017_02_06_1nqsng.png"><img src="https://abload.de/thumb/fsscreen_2017_02_06_1nqsng.png" /></a>

**Comment by xerion8300** [comment]
Sorry for cloos
