### ISSUE TITLE
record course .. question for first waypoints

### ISSUE THREAD

**Issue by DerLaechler** [Courseplay/courseplay#1744]
hello, thanks for developing this for fs17.
do you change something in the recording of the first waypoints, specially between the second and the third waypoint, it seems very far away the point 2 to 3.
is there a way to "reduce" the distance between the second/third and fourth qaypoint?

![fsscreen_2017_02_05_13_23_00](https://cloud.githubusercontent.com/assets/25566205/22626929/1bca22de-ebb8-11e6-94b7-6d138cc14098.png)

i´m using:
Courseplay: initialized 39/39 files (v5.01.00064)

Dirk

**Comment by ThomasGaertner** [comment]
nope, it's been this way all the time and we don't want to change it for some reasons. If it bothers you too much, you can set a crossing point on the concerned place. Adding a way point manually is in discussion, but it's not without risk...

**Comment by DerLaechler** [comment]
thanks for your answer

**Comment by pops64** [comment]
Can we close here? The suggestion for making waypoints is here #1436
