### ISSUE TITLE
Course generator, more directions?

### ISSUE THREAD

**Issue by PatrickLyngholm** [Courseplay/courseplay#1746]
Hello.
I'm not 100% sure that this is the right place for improvement ideas, but here goes.

The course generator is a very useful tool, on maps with fields going north-south og east-west. But on maps with fields in more directions (Südthüringen) it is not working that good.
![fsscreen_2017_02_05_21_09_21](https://cloud.githubusercontent.com/assets/25570628/22629527/0ab2ac5c-ebe8-11e6-838c-583055c92e51.png)
![fsscreen_2017_02_05_21_09_37](https://cloud.githubusercontent.com/assets/25570628/22629528/0ab320ec-ebe8-11e6-8474-32a75424bc20.png)

As you can see it makes a course that is not that good.
So I was thinking maybe it was possible to add a function where it calculates the course with the fewest lanes, or the course with the longest lanes possible? I hope you understand ;)

I made a picture to explain:
![fsscreen_2017_02_05_21_09_37](https://cloud.githubusercontent.com/assets/25570628/22629562/b4881aa0-ebe8-11e6-9def-d3636241fca7.png)

So the big red lines is the course with the fewest headland turns, the one with the fewest and longest lanes.

Other than that you guys are doing a fantastic job!! I'm so impressed with all the time and effort you put into this!

Patrick.

**Comment by pops64** [comment]
This has been suggested. #523 Closed to keep the issues area clean
