### ISSUE TITLE
Problem with Courseplay

### ISSUE THREAD

**Issue by Tonton1969** [Courseplay/courseplay#1747]
Hi I have a problems with the actual version:

First: When a combine is turning and the truck is beside the combine start to runs in circle

Secound I get this message in the log:

C:/Users/Tonton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/mode2.lua:538: attempt to index field 'acDirectionBeforeTurn' (a nil value)
Error: Running LUA method 'update'.
C:/Users/Tonton/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/mode2.lua:538: attempt to index field 'acDirectionBeforeTurn' (a nil value)
Error: Running LUA method 'update'.

**Comment by pops64** [comment]
Could we get a full log and a picture of when it is occurring? Thanks

**Comment by ThomasGaertner** [comment]
autocombine is not supported yet....

**Comment by pops64** [comment]
#1701 Closed to keep issues area clean
