### ISSUE TITLE
Minor: Wide Turn Fendt Vario 300+Extaca EL 700

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1748]
Appears when it is doing this turn type it skips over the last few alignment way points and does drive onto the field not straight. Not a huge deal. Just thought you would like to know. Thanks [Log](http://pastebin.com/S6CTpbbR) [Video](https://www.dropbox.com/s/kzycr8tyw8sd060/Farming%20Simulator%2017%202_5_2017%205_11_08%20PM.mp4?dl=0)
![farming simulator 17 2_5_2017 5_17_39 pm](https://cloud.githubusercontent.com/assets/10678220/22630372/065d257c-ebc7-11e6-9c07-33c5e780a702.png)

**Comment by Satissis** [comment]
Try again with v01.0069 or higher and report back.
Note: Version number is wrong in the commit text.

**Comment by pops64** [comment]
Works Great thanks :D
