### ISSUE TITLE
Drive-Through Problem

### ISSUE THREAD

**Issue by Th301** [Courseplay/courseplay#1749]
Hey there,

at first I wanna say thank you for the great work at CP for fs !!

I'm playing fs17 with CP 5 for some days. Unfortunately I have a problem with the Mode 2. (Unloading Chaff cutter and driving the chaff into a bunker). The course is recorded and driving next to the cutter works fine. All the way to the farm works fine too but direktly in front of the bunker, the driver turns left und don't drive through the bunker. He drives some meters straight ahead, turns 180° and drives straight forward and looses completely the course. Bringing it back to the course manually it continiues the way back to the field  but again without driving through the bunker and unloading.
What am I doing worng? Any ideas? Tractor and trailer are standards from the game.
Hopefully it is my own fault and the solution is easy.

I used CP already in fs15 and it worked allways fine in mode 2.

Thanks for your help :)

**Comment by Raints** [comment]
First you should tell what version of Courseplay you use, what map, what tractor's? Log would be nice also.

**Comment by Th301** [comment]
Thanks for your reaction.

I think I solved the problem on my own. The angle in which the tractor came towards the bunker was too big. (had to remove a tree)

I was using Version 5.01.00062. The tractor then drove throught the bunker but than the game crashed and only task manager could stop it.
Now I am using the version 5.01.00068. Seems to work fine now ! Log is clean now.

Thanks again.

**Comment by Satissis** [comment]
I'll close here then to keep the issues clean
