### ISSUE TITLE
work wide saving?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#1750]
Is it possible to save the work wide?
Every time we start the game we must change the workwide from the traktor and loadingwagon (deutsch Ladewagen) to the wide from the cutter from the dresher.
In normal cp set the workwide to the wide from the loadingwagon, but we need the wide from the cutter to harvest straw windrow.
Lg
Andreas

**Comment by Satissis** [comment]
just to clarify this suggestion, you want the workwidth to be saved when you save the game and then reload it once you load the map again, so you don't have to set it manually on each game session ?

**Comment by ThomasGaertner** [comment]
this is already implemented and worked fine... #1476

**Comment by andreasthu** [comment]
ok, here is a pic report
1. generate field course, workwide set to 13,7m
![1](https://cloud.githubusercontent.com/assets/24860501/22662001/bd97c824-eca7-11e6-8430-ac20ea92a6d9.png)

2. attach an drive away course (combined course)
![2](https://cloud.githubusercontent.com/assets/24860501/22662053/f3c319c6-eca7-11e6-96dd-987ba6a1fb62.png)

3. when he is ready, i klick on "abfahrer entlassen"
![3](https://cloud.githubusercontent.com/assets/24860501/22662080/0b2679fa-eca8-11e6-9b3f-214fe067ae91.png)

4. and on "wegpunkte löschen" (the x in the circle)
![4](https://cloud.githubusercontent.com/assets/24860501/22662116/291e1364-eca8-11e6-95ba-18ff45b352fe.png)

5. here you see, the working wide is still 13,7m
![5](https://cloud.githubusercontent.com/assets/24860501/22662147/45da68ae-eca8-11e6-851b-056cc9e2cac1.png)

6. now i save the game, abort the game, start the game, load the game - and the workwide is not the same:
![6](https://cloud.githubusercontent.com/assets/24860501/22662180/6aa37518-eca8-11e6-9316-1647e0c738cb.png)

i remember, in LS15 <version>4.01.0109</version>
it was saved

lg
andreas

**Comment by pops64** [comment]
Its probably related to the one attach function overwriting the saved variables. Not sure 100% has I haven't look at that function.

**Comment by rkaerner** [comment]
Let me just ask a question for understanding the situation: You grab the straw or mowed grass with a loading trailer and have to set the working width every time new for getting the lanes, right?
If that is your problem, I might have a solution for you: create a course for the combine and save it. Use the saved course for the combine to load it to your tractor with the loading trailer. It works like a charm and the not kept rest is really negligible, trust me.

**Comment by pops64** [comment]
The problem with the saving theses kinds of courses at least in 15 was your loading time would increase. I have yet to encounter this with 17. You can also use copy course instead of saving. And you only have to set the working width on game load(bugged) or on attach the way it was designed.

**Comment by ThomasGaertner** [comment]
try v.0070 or higher and report

**Comment by andreasthu** [comment]
works perfekt, thanks
lg
andreas
