### ISSUE TITLE
Courseplay and graincarts

### ISSUE THREAD

**Issue by Nielsen362** [Courseplay/courseplay#1751]
Hi first a big thanks for this great mod 
I hobe it is the rigth place for this.
I use a kinze graincart with tracks and when i try to use it on courseplay, it say wrong trailer for this mode, in 15 was there a script overloader.lua, so we could use it with courseplay, is that possible to make that for 17 also
Thanks in advance
Nielsen

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Nielsen362** [comment]
I converted from 15 the kinze1500, there is no log errors, yes it is in mode 3, if i make the kinze like the ingame carts the terratracs wont work. I now Satis made the overloader.lua for 15, that fixed the problem then, hope this make sence

**Comment by pops64** [comment]
Could you post your conversion to drop box or like? So we can take a look at what is going wrong with it thanks?

**Comment by Nielsen362** [comment]
I send it to you by mail, hope thats ok

**Comment by Nielsen362** [comment]
I will try to put it in drop box https://www.dropbox.com/s/0wi088fnhe4355a/FS17_Kinze1500.zip?dl=0
hope it works havent tryed before :-)

**Comment by pops64** [comment]
Change line 70 in specialTools.lua to this
`if workTool.typeName == 'augerWagon' or string.match( workTool.typeName, "FS17_kotteUniversalPack.kotteUniversal") or workTool.typeName == 'FS17_Kinze1500.Kinze1500' then`

Line 76 through 81 change to this
```
if workTool.cp.xmlFileName == 'horschTitan34UW.xml' then
			workTool.cp.isHorschTitan34UW = true;
			workTool.cp.foldPipeAtWaitPoint = true;
		elseif workTool.cp.xmlFileName == '1500.xml'then
			workTool.cp.foldPipeAtWaitPoint = true;
		end;
```

That should get everything work but saving the pipe position. Has I haven't looked into how that works.

**Comment by Nielsen362** [comment]
Super it works BIG THANKS TO YOU
