### ISSUE TITLE
Debug channel 10 breaks hud in shovel mode

### ISSUE THREAD

**Issue by Jestar342** [Courseplay/courseplay#1753]
Hello,

When using the shovel loading mode, CP is always skipping many waypoints once the bucket reaches capacity.

In the video/log file you will observe that as soon as the bucket passes fill threshold at around WP 5, the JCB jumps to WP 38, and then upon reaching around WP 42 it skips back to WP 1.

I am using whatever version Courseplay is at commit [068ad1a](https://github.com/Courseplay/courseplay/commit/068ad1a19331ac46b51dda2295a90079ad057bb4) (which is the latest at the time of posting this issue.)

[log.txt](https://gist.github.com/Jestar342/cc287853b501f1b6d74d187c251c89fd) (gist)

[Video](https://www.youtube.com/watch?v=-3Oq1bs4Rjc) (youtube)

The "bonus" bug is when enabling debug channel 10 during the loading phase, the HUD mostly disappears and the log fills very quickly with the following error:

`Error: Running LUA method 'draw'.
C:/Users/John/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/base.lua:580: attempt to perform arithmetic on field 'height' (a nil value)`

but that could easily be one of the other mods, I guess?

Anyway, thanks for the great mod. I hope this has been helpful. :)

**Comment by pops64** [comment]
The First wait point needs to be close to the entrance of the silo.Could you rerecord your route for mode 9 and do a video. I have encounter the debug channel 10 breaking hud bug

**Comment by Jestar342** [comment]
That was it. I recreated the route with the first wait point at the very edge/start of the silo and it works ok. However, two things: I created the wait point as per the video so that the shovel has time to get into the loading position before the start of the silo, and secondly, I have seen other vehicles skip many waypoints - notably tractors that are reverse unloading in a silo. Usually I just re-record the route until I get a working route - I will endeavour to report with a video when/if I see it happen again.

**Comment by pops64** [comment]
Reverse unloading into a silo. Is a different issue. Usually that is because when it finishes unloading it looks for the next forward way point that is in front of the tractor.  And if your course driving out of the silo is not straight enough it will cause this bug. You can move your way point back a few yards to get this part of the silo and shouldn't have issues but were you had it before was way to far back.

**Comment by Jestar342** [comment]
Just further to add, I figured out the problem with giving enough room for the shovel to reach loading position - the wait point can be right inside the silo if need be, providing the previous (normal) waypoint and/or start point is sufficiently far enough away. [this screenshot](http://i.imgur.com/Yf2Fekw.jpg) shows a perfectly working route. 

Thanks again.
