### ISSUE TITLE
Unload Here

### ISSUE THREAD

**Issue by huseyinsayar** [Courseplay/courseplay#1755]
There is a new "Unload Here" command you know, I wonder if the courseplay mode supports this command.
If it does not exist;
Is it possible to make arrangements that are possible, especially when the field is being harvested or after the straw is collected and then poured onto the edge of the field or into the belt system instead of going silos?
Maybe like "P" Wait Point, "U" Unload Point can be put.
Good luck.

(Bildiğiniz üere yeni gelen "Unload Here" komutu var, Courseplay modunun bu komutu destekleyip desteklemediğini merak ediyorum.
Eğer yok ise;
Özellikle tarla hasat edilirken ya da saman toplandıktan sonra silolara gitmek yerine tarla kenarına boşaltma ya da kayış sistemine dökülmesini mümkün kılan bir düzenleme yapılabilir mi?
Belki "P" Wait Point gibi, "U" Unload Point noktası konabilir.
Başarılar dilerim.)

**Comment by pops64** [comment]
It already is. #1624 Closed to keep the issues area clean. I think mode 6 is also include now expect for harvesters. Mode 7 can handle harvesters by using two wait point to indicate where your heap is
