### ISSUE TITLE
Error when trying to use the Krone Swadro with Courseplay...

### ISSUE THREAD

**Issue by tirrera921** [Courseplay/courseplay#1756]
When loading and starting a course with the Krone Swadrow windrower, the character in the seat of the tractor scrolls through all of the different people and logs this error each time you click any of the starting links, (first waypoint, current, etc.)

This is the error:  
Error: Running LUA method 'mouseEvent'.
dataS/scripts/vehicles/ai/AIVehicleUtil.lua(299) : bad argument #1 to 'cos' (number expected, got nil)

**Comment by pops64** [comment]
There is something wrong with the mod. Giants AI won't even use this mod with out error #1731. Contact the mod aurthor to see if he can fix on his end. Closed to keep issue area clean
