### ISSUE TITLE
Large no of LUA errors noticed in version 5.01.0070 causing game to partially lock up 

### ISSUE THREAD

**Issue by edjon2000** [Courseplay/courseplay#1757]
Hi guys, 
I appreciate that you are very busy but I have been noticing an error since update 0070, I was running two harvesters on a large field with two tractor/tipper combinations the harvesters were using standard hired workers, while the tractor/tippers were under courseplay control,  for no apparent reason the game just locks up after anything from a few minutes to an hour or so, I looked at the log (attached) and could see a large no of LUA errors associated with mode 2.LUA Im not sure whether this is the cause of the issue or not, please could you have a look at it when you get the chance, 
Thanks in advance
[log.txt](https://github.com/Courseplay/courseplay/files/759518/log.txt)

**Comment by pops64** [comment]
Auto Combine Support is not yet implemented at this time. Closed to keep the issues area clear. #1701
