### ISSUE TITLE
ZZZ_Courseplay Still Needed for some mods

### ISSUE THREAD

**Issue by Paxol** [Courseplay/courseplay#1758]
While I'm loading my savegame I have a black screen, but if I load a new savegame it works.
Log error:
Error: Running LUA method 'update'.
C:/Users/Mirko/Documents/My Games/FarmingSimulator2017/mods/courseplay/base.lua:901: attempt to index field 'hud' (a nil value)

**Comment by pops64** [comment]
Full log? has this probably a mod problem.

**Comment by Paxol** [comment]
I attached the log file
[log.txt](https://github.com/Courseplay/courseplay/files/764842/log.txt)

**Comment by pops64** [comment]
I would recondmend turning off your vehcile mods one by one until you find which one is causing this issue. Then turning off your other mods one by one. Or you could start with running only CP with no mods and turning them back on one by one. I would start with the autoload timber runner I am not sure if it uses baleautoload script #1736

**Comment by Paxol** [comment]
Ok, but when I start a new game with ALL mods it works... It doesn't work only with my savegame

**Comment by pops64** [comment]
It is defiantly one of your vehicle mods then #1735.  Cause CP wont run into issuses until that mod is bought and loaded into the game

**Comment by Kiggins1** [comment]
I had the exakt same problem with the Lua error after loading a savegame.
After i renamed my courseplay folder to zzz_courseplay, the savegame load without any problems.

Maybe it helps you too Paxol

**Comment by Paxol** [comment]
Thanks, I haven't rename the file, I'll try it when I return to home

**Comment by Paxol** [comment]
Ok, I've renamed the file and now it works, thanks!

**Comment by pops64** [comment]
@Paxol What version of cp are running. Running name to zzz_courseplay should be fixed in the current issue.

**Comment by Paxol** [comment]
I tested it on v. 5.01.00071

**Comment by ThomasGaertner** [comment]
please try again with v.0077 or higher and report ...

**Comment by Paxol** [comment]
Fixed!
