### ISSUE TITLE
How can I install course play to FS17(Mac) 

### ISSUE THREAD

**Issue by OhihoO** [Courseplay/courseplay#1759]
I read guide than following up.
but I could look at it in FS17 mods.
I put into /Users/XXXXXXXXX/Library/Application Support/FarmingSimulator2017/mods/ZZZ_courseplay.zip

plz help me..

PS: Load mod: FS17_Courseplay
Error: Unsupported mod description version in mod FS17_Courseplay

**Comment by pops64** [comment]
Install it were all your other mods are at. Need to remove the files inside the folder inside the zip you download. If you loading an already saved game you need to ensure it is already enabled. https://www.youtube.com/watch?v=ADBl6BmGNYE for windows but its the same principles just different key commands for select all, cut and paste and file locations.

**Comment by pops64** [comment]
Update your game to version 1.3 or higher. Closed to keep the issues area clean.

**Comment by OhihoO** [comment]
my bad.. my version was 1.2 sorry
