### ISSUE TITLE
Mode8 Support for Slurry(Liquid Manure) Sell triggers + River Water Fill Triggers

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1760]
Has of right now Mode8 does not support unloading to slurry sell triggers. v71. Also discovered river water fill triggers are unsported v75 Tried with the wait point at the sell trigger and just driving by it. And reverseing into trigger support(The BGA sell trigger needs this). Has I don't think mode 8 handles that. Thanks for reading :D

**Comment by DogfaceKSP** [comment]
I also spent a while trying to fill from river. River water fill triggers would be a welcome addition. 
FIGHT BIG WATER!  jk
Those animal water trough triggers in mode8 are torture.  :(

**Comment by pops64** [comment]
I think part of the problem with the animal water trough triggers. Is have noticed that the trigger on the tool it self is dead center at the rear of the tanker on vanilla slurry equipment(Haven't checked water tanks yet). I found this out when trying to sell to the bga trigger. Which is why I included reversing support for triggers in mode8

**Comment by lcc1211** [comment]
I'm noticing on certain maps the water trigger is no longer working for troughs.  The Westbridge import is one. I can manually pull up and add water but CP drives on by.  However, Hobbs v6 FS17 still recognized them.  Sosnovko and GCV have no problems.  I think this happened about 3 updates ago.

**Comment by pops64** [comment]
I think it is how the water trigger is declared on your game map. Not 100% sure because I really don't understand the trigger code. My guess would be on your moded maps that they are declared in the same way as a river water trigger which isn't recognized. Once again I am only guessing because triggers are a little out of my understanding.

**Comment by lcc1211** [comment]
I guess this particular map's water trigger is different from other maps then.

**Comment by pops64** [comment]
Test with v01.0115 and report back
