### ISSUE TITLE
not loading

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/courseplay#1761]
just downloaded it today, but the mod does not seem to be loading, at all. i've put it in my my games/farmingsimulator17, with all the others...

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Commissar0617** [comment]
https://www.dropbox.com/s/k8761ce0or1z9dr/log.txt?dl=0

**Comment by Raints** [comment]
Load mod: ZZZ_courseplay (Version: 4.01.0000)
Your version of courseplay is not the latest. Check this video to get latest version.

https://www.youtube.com/watch?v=ADBl6BmGNYE

**Comment by Commissar0617** [comment]
yeeeup... silly me, thinking the github.io download was the latest...
