### ISSUE TITLE
Great Plains Seeder, Amazone ED3000 and Optima V no stop on edge :(

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1762]
With the above pieces of equipment. They do not stop on the edge on lane start and they need to be has there are chunks of unseeded field left behind because the tractor accelerates faster than the lowering occurs.(End of lane does not need a pause but lane start does) Tested all sowing machine expect for the lemken which is broken in v1.4 and only the above 3 do not stop for lowering on edge
![farming simulator 17 2_9_2017 9_37_01 pm](https://cloud.githubusercontent.com/assets/10678220/22811943/f29fd31c-ef0f-11e6-9d09-f064d170b800.png)

**Comment by Satissis** [comment]
Try again with v01.0074 or higher and report back.

**Comment by pops64** [comment]
All good thanks
