### ISSUE TITLE
Multiple task fields fusion or adding at end

### ISSUE THREAD

**Issue by Anonymous-any** [Courseplay/courseplay#1763]
When I try to join courses or add at end (different tasks like fields, spreader, seed etc etc) that finish 1st field and but problem to start at 2nd field ...
Regards

**Comment by pops64** [comment]
CP isn't designed to support this kind of function. It has been talked about in the past and it is just not possible it would involve a lot of redesign. Closed to keep the issues area clean

**Comment by pops64** [comment]
#1249 is where here suggestion has been suggested
