### ISSUE TITLE
water route problem

### ISSUE THREAD

**Issue by DogfaceKSP** [Courseplay/courseplay#1764]
I was trying to create a route with CoursePlay to get water to all my locations requiring water. I experimented for several hours and it seems grain transport mode works for cows and manure transfer mode works for greenhouses. Is that correct or am I doing something wrong? 

If that is correct, then I would like to suggest that all water locations use the same mode, so we can hit them all with one route.

**Comment by pops64** [comment]
Mode 8 is for a liquids. Mode 1 is for all solids. Mode 8 now supports water triggers. Mode 8 does not yet support. With mode 8 the water triggers are very sensitive and the wait point has to be placed correctly. #1741 and #1621. Can we close here?

**Comment by DogfaceKSP** [comment]
grain transport (mode 1?) lists "water" as one of the options. 

It must be VERY sensitive! I set the wait point when the F1 menu read "Unload". I tried for an hour to get it to work.

**Comment by pops64** [comment]
I think mode 1 lists any thing that the trailer can hold even if the mode is not designed for it. It is all good mode8 wasn't really used in 15 so that part of the manual is out of date. Closed here to keep the issues area clean.
