### ISSUE TITLE
Merge/Append Function

### ISSUE THREAD

**Issue by Anonymous-any** [Courseplay/courseplay#1765]
https://github.com/Courseplay/courseplay/issues/1763

My english is sad I know sorry  but maybe I not good explain then why there function button in it for joint courses or add at end courses? I think you have not really understand what I want to say and explain before close POPS64 ...
also when I google translate my text it seem comprehensive it seem :/

**Comment by pops64** [comment]
You can't combine to fields together into one course. Has I mentioned in my response to your first issue and has mentioned here #1249. If you have a bug https://github.com/Courseplay/courseplay/wiki . If you want to know how to use append or merge functions http://courseplay.github.io/courseplay/en/manual/index.html#hud_manageCourses

**Comment by Anonymous-any** [comment]
Well close if you want but it's weird, yes it's about merge/append function and I was used it in old version like fs11, 13, 15 with crossing point you know all was fine, and with this version I thinking I was report a problem cause if you try to append or merge multi courses filed that cause a problem where the tractor change his mode I think it want to unload or load or refill I don't know you know you have to test it's better :/
Theses options to merge/append and cross was good functionally in old versions were you can work multi field's in same time to do same work with same tool you know, but not at time in 17 it seem. And then if you say CP run fine, why the tractor stop his work at end field to do a thing who it not programmed to do in course for do when it try to start the 2nd field to work? (i'm sorry my english bad)... i'm french for specify.
but if my request is already asked then close POPS64 it's ok I was thinking I contrib for a bug report.

**Comment by pops64** [comment]
Closed due to inactivity
