### ISSUE TITLE
Turn problem on angled field edges

### ISSUE THREAD

**Issue by Flitch49** [Courseplay/courseplay#1766]
Not sure if this is a bug or intentional.
When a tractor approaches a turn on an angled field edge it is not recognizing the next turn and is reversing until it hits something and then gets stuck.  In the picture (debug 12 & 14 active) the planned turn can be seen, but a second or so after this pic the tractor will go into an infinite reverse until it crashes. 

After some experimentation with turning circles I found that reducing the turning circle to a very low figure (50 - 60 % of standard) the turn would be made. ( second and third pics)

![fsscreen_2017_02_11_08_37_27](https://cloud.githubusercontent.com/assets/25412195/22852613/6217dd5c-f037-11e6-8e03-10341ef82a72.png)
![fsscreen_2017_02_11_08_59_56](https://cloud.githubusercontent.com/assets/25412195/22852662/cb25f80a-f038-11e6-9a40-49085ab43d55.png)
![fsscreen_2017_02_11_09_00_29](https://cloud.githubusercontent.com/assets/25412195/22852667/e20a7d84-f038-11e6-9625-be925df51ca4.png)

Map; Goldcrest Valley
[log.txt](https://github.com/Courseplay/courseplay/files/768299/log.txt)
<version>5.01.00071

**Comment by Satissis** [comment]
Try again with v01.0075 or higher and report back.

**Comment by pops64** [comment]
Seems that the 3 point turns have been broken. It looks like in the log it wants to change to fwd direction but doesn't. Only seems to occur in certain spots and even those sports are random if it will work. [Log](http://pastebin.com/5LW3X88q). [Video](https://www.dropbox.com/s/s8a0am23xnywr0u/Farming%20Simulator%2017%202_12_2017%202_16_21%20PM.mp4?dl=0)

**Comment by Satissis** [comment]
Funny... I had that problem as well and thought I already sorted it. Back to the drawing board

**Comment by pops64** [comment]
It only seems to occur in some spots and only seems to be the ploughs that are affected. If you want I can upload that save game.

**Comment by Flitch49** [comment]
<version>5.01.00076</version> 
Map : Goldcrest Valley.

Tested with a mower(3.1m) a tedder(6.2m) and a plough(3.6m), both on and off field turning enabled, and on a straight field edge and an angled field edge,   all worked perfectly well, with none of the problems shown in pops64 video manifesting themselves. I can rerun the tests and post log if required.

**Comment by pull2play** [comment]
Has this build affected combines in any way? They seem to be leaving a lot more fruit behind on their turns than they did in previous builds.

**Comment by Satissis** [comment]
Should be fixed in v01.0078.
Try it out and report back.

@pull2play No it was in a previous commit the behavior changed. However this commit should help a bit on is as well.

**Comment by Flitch49** [comment]
Seems to be working for me now. :-)
