### ISSUE TITLE
Beet harvesting

### ISSUE THREAD

**Issue by kacsaminator** [Courseplay/courseplay#1767]
Hello,

My problem occurs when the beet harvester (Terra Dos T4-40) reaches the tractor (with combi mode, any type of tractor) threshold. The tractor's courseplay says "no combine in reach" instead of moving there and unloading it. The tractor only starts moving when the harvester reaches the 100%.

Sorry for my bad English :)

(I tried with JCB Fastrack 8000 and Valtra T Series with Dolly EA and Bandit SB 30/60 tipper)

**Comment by pops64** [comment]
Debug channel 4. is it in auto or manual when search for combine? if in auto is it completely on the field?

**Comment by kacsaminator** [comment]
Good news it seems it is working, but since the last update (or two) the beet harvester can't reverse it is reversing in circles and can you make the harvester turning to require less space next to the field (maybe on field). I don't like the headland because it leaves some in the corners :(

Thank you for your help :)

**Comment by pops64** [comment]
#1727 for turning issues regarding the beet harvester. Yea you have to be completely on the field in automatic. Closed to keep the issues area clean
