### ISSUE TITLE
First lane after headland, tractor reverses forever

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1768]
Not sure if this is a 1.4 issue, but I've seen issues with the first lane after a headland before, just not quite like this.   Tractor will reverse forever until it hits an obsticle.  This only happens when turn on field is activated.   From the debug 14, it seems that the turn is being called up from the next lane, not the current one.

log (debug 1)
https://gist.github.com/sootysax/9a44e3d8c2f3d9790e00258cfb1954cb

video (debug 14)
https://www.dropbox.com/s/ovnoduz4zsg97ji/2017-02-11_115652161.mp4?dl=0

**Comment by sootysax** [comment]
ah - it appears that this is the same issue as #1766

**Comment by Satissis** [comment]
Try again with v01.0075 or higher and report back.

**Comment by sootysax** [comment]
problem fixed testing with .76

**Comment by Satissis** [comment]
Alright. I'll close here then
