### ISSUE TITLE
Mode8 Slurry Storage Mod

### ISSUE THREAD

**Issue by Chris-KB** [Courseplay/courseplay#1770]
Im Mode 8 Gülleüberladen habe ich ein Problem. Wenn ich mit diesem Mode einen Kurs eingefahren habe und die Gülle vom Kuhstall mit dem Kotte Universal Pack v. 1.0.0.6 in das Güllelager v.1.2 vom Kevink98 überlagern möchte, fährt der Fahrer normal zum Aufladen und dann weiter zum Parkpunkt, welcher direkt neben dem Güllelager sich befindet. Danach passiert nichts mehr. Ohne CP kann ich normal die Gülle dort abladen.

**Comment by pops64** [comment]
Link to the slurry storage mod. If I am understing you correctly the Kotte Universal is not overloading to your the slurry storage mod? If you can could also provide a translation to english. Thanks

Google Translate to German

Link zum Aufbewahrungsmod. Wenn ich dich richtig unterfütze, ist die Kotte Universal nicht überladen zu deinem Slurry-Speicher-Mod? Wenn Sie eine Übersetzung auch auf Englisch stellen können. Vielen Dank

**Comment by Chris-KB** [comment]
It is the "Güllelager V.1.2" from KevinK98 which you can find on http://marhu.net/phpBB3/viewtopic.php?f=203&t=5440 or http://ul.to/isck354c

If I have entered a course with this fashion and want to overlay the manure from the cow shed with the Kotte Universal Pack v. 1.0.0.6 into the slurry storage v.1.2 of the Kevink98, the driver drives normally to the charge and then to the parking spot, which is next to The slurry storage. After that nothing happens. Without CP I can normally discharge the manure there.

**Comment by ThomasGaertner** [comment]
We have checked it and it s not really suitable for us to implement. starts with the missing (at least) english translations and ends with basic functions we need to get it running well which are not running properly. So we can't do much on this side , sorry

**Comment by pops64** [comment]
Can we close here? Thanks

**Comment by Chris-KB** [comment]
Okay
