### ISSUE TITLE
course generation on U shape fields

### ISSUE THREAD

**Issue by Sythos** [Courseplay/courseplay#1771]
Courseplay 5.01.0076
FS17 1.4.2

Tools involved:
- Standard NH T7.420 tractor (no mod)
- Standard DC9 seeder (no mod)

Event: Generating courses on U shaped fields (seed or generic) cause some lanes go outside the field, hitting what's outside (trees, rocks, buildings, etc.).

Expected: calculated paths should never go outside the edge of the field, maybe should just follow the edge with tool turned of and lifted

![ushape](https://cloud.githubusercontent.com/assets/15103522/22905958/a39343cc-f242-11e6-9b96-e9e7d3c34558.png)

**Comment by pops64** [comment]
Already reported. #1377 Postponed for now. Closed to keep the issues area clean
