### ISSUE TITLE
Kuhn DLC

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#1773]
Good Morning!
I would have a please if you the unloading function for the SW4014 baler and FBP3135 bales wrap combi from the Kuhn DLC pack could make!

Many Thanks!

**Comment by pops64** [comment]
Also the DiscoLander xm52 doesn't drive completely to field edge. I think it is using front marker for lane stop and back marker for lane start. Also with this equipment it is possible to run this has a cultivator with out it being turned(No seeding just cultivating). Would it possible for CP to recognize that if it is in mode 6 to cultivate and not seed. And if in mode 4 to seed as well? This also applies to the weeder Einbock 900. Thanks

**Comment by garo73** [comment]
Agree with @Paul2510

**Comment by ThomasGaertner** [comment]
closed to keep issues clean
