### ISSUE TITLE
Seeder Covers Patch 1.4.2

### ISSUE THREAD

**Issue by RKI91** [Courseplay/courseplay#1774]
First issue is assigned to seeders - In game patch 1.4.2 we have got one change eg. "Seeds and fertilizer trigger now don't close the tool covers automatically" Which results in that the seeders during the course of filling, do not close the covers.

Second issue is a issue with polish translation. This is about information on the combined courses. Not "2 kursy kombajnu" (Just bad variety) but "2 połączone kursy". "Kombajn" in polish language is a harvester machine so this looks strange at this place. (And yea im guy from Poland :))

Here i attach the video with cover problem.
https://youtu.be/IqXshaww_cE

**Comment by KITT3000** [comment]
Każdy znaleziony błąd tłumaczenia proszę zgłaszać do mnie, niestety nie byłem w stanie sprawdzić wszystkiego co było tłumaczone (często przydałby się opis danego wyrażenia) dlatego słowo "combine" zostało przetłumaczone jako kombajny a nie jako połączone :P Dzięki za zwrócenie na to uwagi, zaraz dodam poprawkę.

**Comment by RKI91** [comment]
@KITT3000 Na przyszłość będę pamiętał, ale i tak dzięki za szybką reakcję. :)

**Comment by ThomasGaertner** [comment]
test v.0080 or higher and report...

**Comment by lcc1211** [comment]
For me as of today with v.0080, the seeder covers are still staying open on both custom and standard game maps.

**Comment by RKI91** [comment]
I'm sorry that so late I give the answer but i do no have time to test it before.
So i tested it with standard amazone condor seeder on refill siloses from video and all works fine for me. Covers are close normally by CP AI player. :)
