### ISSUE TITLE
slurry and digestive mode1?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#1776]
Hey guys.
A question is it possible to sale slurry from cow and pig or digestive from bga with farmer andys kotte universal pack automatically?
In this time i made a course in mode 1, start by the slurry tank, drive to the gardencenter, through the sell trigger and back to the slurry tank.
End the course record a few meters before the beginning.

When i then start the cp helper, he drives to the startpoint, stop and wait.
I must fire the ch helper, fill the kotte with R key and hire the helper.
When the kotte is full the cp helper drive the course stopp at the sale station unload and sale the slurry and drive back to the startpoint.
And the he also stopp.  I must fire the helper manually start the loading and hire the helper .......
Btw in the cp hud appears, when he stops, "wird beladen 0 von 300000"
Also the cp helper knows that he must load but he didnt.

Lg
Andreas

**Comment by pops64** [comment]
Already been suggested. #1760 All liquids are handled in mode 8. Closed to keep the issues area clean
