### ISSUE TITLE
Suggestion: Manual "call for helper" in combine mode

### ISSUE THREAD

**Issue by CyberAgro** [Courseplay/courseplay#1779]
Just a suggestion. Would be nice to be able to "call the guy" driving the trailer, when you drive the combine. That way, you can unload without him driving in the crops beside the combine. Is it possible?

Kind regards
CA

**Comment by Sythos** [comment]
I'm afraid to not understand, you already can call the guy, just select in the hud the first icon top left and select "call driver" (or play the combine horn), can you specify better what you mean?

**Comment by Raints** [comment]
http://courseplay.github.io/courseplay/en/manual/index.html#hud_combineSettings

@CyberAgro You mean this?

**Comment by CyberAgro** [comment]
Yeah it sounds like that :-) Sorry about that then. Wasn't aware that was
possible already. I'll try it, and get back if it's not what i had in mind.

Kind regards
CA

Den 15/02/2017 16.04 skrev "Raints" <notifications@github.com>:

**Comment by CyberAgro** [comment]
Yup! That was what i missed. Thanks for enlightening me :)

Kind regards
CA
