### ISSUE TITLE
Terra Variant backwards

### ISSUE THREAD

**Issue by ChristianH181** [Courseplay/courseplay#1781]
Good Morning,

The Terra Variant does not detect any triggers (load or unload) when reversing. Forward no problems. Be it Holmer-Pack standard or HT-50-Mod, backwards the Terra Variant is blind.  

Subject: Court camp, BGA bunkers-silo, slurry-trigger and sales-trigger

HT-50 [https://www.modhoster.de/mods/ht-50-holmer](https://www.modhoster.de/mods/ht-50-holmer
)
Sorry for the english google translator.

**Comment by pops64** [comment]
Your first two issues are already discussed in #1760. Your mod is that even a slurry tanker? Does the Holmer terra have issues in mode 1 selling to a manure sell trigger in reverse or is it just mode 8?

**Comment by ChristianH181** [comment]
The HT-50-Mod is a tipper

**Comment by pops64** [comment]
So the holmer terra doesn't unload to any sell triggers in any mode or is it just mode 8 has this mode doesn't support reversing into triggers?

**Comment by ChristianH181** [comment]
Mode 1 & 2 it recognizes backwards at all no trigger. Mode 8 is the slurry feeder mode, the slurry tank from the terra variant does not support overload, you can only grubber with it. Thus the mode 8 is irrelevant for the terra variant.

**Comment by pops64** [comment]
Thanks for the video. It is hard to tell but I am assuming you were running running debug 1 in that video? If not could you redo it and post the log for that as well.

**Comment by ChristianH181** [comment]
yes, is debug-channel 1

**Comment by pops64** [comment]
Yea I believe that when it reverses the ray cast is suppose to flip pointing in the direction of travel. Which is why it isn't unloading. Could be something else but with out a log can't say for sure. Do you have the log from that video?

**Comment by ChristianH181** [comment]
I would have to do again. Debug 1 and then upload LS-log?
Both trigger again or a trigger, result should be equal or?

**Comment by pops64** [comment]
Do channels 1 and 2 like you did in the video. And post that log. Thanks

**Comment by ChristianH181** [comment]
Sorry it took a little longer (dinner time). Debug channels 1,2 & 13 are on. Have inserted into the log comments (for backwards or end of the unloaded).

Video section 1
[Farm backward.txt](https://github.com/Courseplay/courseplay/files/781489/Farm.backward.txt)

Video section 2
[BGA backward.txt](https://github.com/Courseplay/courseplay/files/781485/BGA.backward.txt)

Video section 3
[Farm forward.txt](https://github.com/Courseplay/courseplay/files/781490/Farm.forward.txt)

Video section 4
[BGA forward.txt](https://github.com/Courseplay/courseplay/files/781492/BGA.forward.txt)

**Comment by ChristianH181** [comment]
Have tried to fix itself, but courseplay is then too complex for me :D 
Courseplay arranges the superstructures of the Terra Variant as normal attacher-tools, but can find no wheels and therefore cannot set a reverse target.
The new attcher to integrate (jointType = "terraVariant") I did not succeed. I look at because extensive code of couseplay not through. Big respect for the CP-Team und thanks for this Job.

**Comment by ChristianH181** [comment]
Sorry was on vacation. Therefore I can not unfortunately say the version be it works. In any case, the Terra Variant can now unload backwards and also load liquid manure. Can Close. Thanks you Guys.

**Comment by pops64** [comment]
Yea there was a different mod that was having reversing issues I guess this got fixed when that did thanks for the response.
