### ISSUE TITLE
KUHN DLC DC 401, HR 4004 and BTF 4000

### ISSUE THREAD

**Issue by remis1989** [Courseplay/courseplay#1784]
Hi. Can anybody make a kuhn DC 401, HR 4004 and BTF 4000 work together in mode 4? Because it just seeding not cultivating, cultivator dont turning on. Thx

**Comment by ThomasGaertner** [comment]
try latest version and report....

**Comment by remis1989** [comment]
in mode 4, click drive course button, doesnt work, just stay in one place and dont move, something wrong..

**Comment by gammelgaard52** [comment]
I have downloaded the newest version and can confirm, that the mode4 is working now - where is puts Down the seed tank, turning on cultivator, turning on seeder og driving, doing plow, cultivate, seed in one move.
Thanks!

**Comment by gammelgaard52** [comment]
Not sure if it should be here, buts its about the same implement - the ridge markers seems not to work in automatic mode or manual. They simply not go down.

**Comment by remis1989** [comment]
when i starting from first point my tractor staying dont mowing, when i move forward a little bit, and lower every equipment and turning on, so it is working. Its very anoying, sorry for my english guys:)

**Comment by remis1989** [comment]
Actualy when i set my start course on first waypoint tractor dont mowing, when i start sourse from nearest waypoint and move a little bit far from first point forward working good. Anybody have this problem?

**Comment by mawie** [comment]
I can confirm what remis1989 reported. For me it is also not working, if I start the CP driver at the first waypoint. No matter if I choose first, nearest or current waypoint. If I start CP at the fourth waypoint for example it works fine.

**Comment by pops64** [comment]
Try again with v00081 or higher and report. Thanks

**Comment by gammelgaard52** [comment]
So far looking good - I can now start from "nearst waypoint" and ridge markers seems to be working :)
You are the best!

**Comment by mawie** [comment]
Starting at the first waypoint works now. Thanks!
