### ISSUE TITLE
Leveling and compacting

### ISSUE THREAD

**Issue by esmajor72** [Courseplay/courseplay#1787]
After recording a course with a default Fendt 900 and a K Agrosliner tipper to unload chaff into the cow farm, it will back into the bunker, trigger to tip, but then start driving out of the bunker the instant it starts to unload, continuing on it's recorded course, leaving a trail of material from the bunker tip trigger towards the road.

**Comment by ntrrlz** [comment]
When you record the course try driving back further into the bunker. I have had the same problem and this fixed it for me.

**Comment by esmajor72** [comment]
I meant to also report in this issue that after the initial run through of the bunker with a leveler, it will wait till the 1st load is dumped in then go to level it and make a sidden sjrp turn into the bunker wall. (seperate tractor with leveler used)

**Comment by Peppobrasil** [comment]
How to activate the leveling and compacting icon: should specific vehicles be used? Help please

**Comment by pseikoNL** [comment]
At this moment lots of modes in the CP-HUD are disabled because the CoursePlay dev team is reworking al of these modes to fs19 code. Until then you can’t use these modes, so please be patient.

Kind regards,
PseikO
