### ISSUE TITLE
Allow bucket mode to use forks

### ISSUE THREAD

**Issue by morphout** [Courseplay/courseplay#1790]
Possible to change the setting in "bucket mode" which detects if a bucket is attached to also allow the mode to work if forks are attached?

Reason: I'd like to be able to use the bucket mode to load pallets purchased from the shop.  It's already convenient that the shop lines them all up in a nice straight line when you buy them!

When you scoop up a pallet, it immediately shows at being 100% full, and empties much like a bucket does.

I just thought it might be an easy 2-minute fix... thanks a ton guys!! Donated when 4.0 was usable for FS15 and heading back to make another contribution now!! Great mod!!

**Comment by pops64** [comment]
On our todo list #1493.  Closed to keep the issues area clean.
