### ISSUE TITLE
Combined routes not choosing optimal crossing points

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1791]
I have always stuggled with 4 way intersections when combining courses..   The only arrangement that has worked for me when trying to place crossing points so that all 8 turns will work is to place them stacked on top of each other, where they cross both courses.  So there are 8 crossing points in this photo.

![image](https://cloud.githubusercontent.com/assets/6591048/23141587/7978bde0-f785-11e6-8f3b-2e74b5b57df9.png)

This results in very wide turns however..  though if the intersection is wide enough, will not result in a crash.

just wondering what everyone else is doing, without having to resort to recording a seperate course for each turn.

**Comment by gammelgaard52** [comment]
Current I am doing like this: (the red lines and red dots)
[http://puu.sh/ueHpe/7d474fd6d2.jpg](url)
So I do make a turn in each section and if i need to be more specific, I add a temp route (the black) in between like this:
[http://puu.sh/ueHze/a20b73ea0d.jpg](url)

But my last idea, is to use the time needed and make a map outside of the game, with road names and then, go in the game and create a template for each road, in every direction, where I have a more granular control. The problem is the CrossPoints being to close, which would be solved be making a template of all the roads needed in both directions.

**Comment by sootysax** [comment]
![2017-02-22_155749994](https://cloud.githubusercontent.com/assets/6591048/23232163/42b9ecc2-f918-11e6-83d1-472ef49f784e.PNG)
![2017-02-22_155840998](https://cloud.githubusercontent.com/assets/6591048/23232167/4818e6aa-f918-11e6-867d-39dd65706762.PNG)
![2017-02-22_155819853](https://cloud.githubusercontent.com/assets/6591048/23232173/4e6f8522-f918-11e6-97c1-92b06a931571.PNG)
![2017-02-22_15590401](https://cloud.githubusercontent.com/assets/6591048/23232197/5f685084-f918-11e6-9414-6979aff3bec4.PNG)

**Comment by jmj486** [comment]
@sootysax What tool do you use to edit courses?

**Comment by dkfiremann** [comment]
The CourseDrawer can be found here: 
https://github.com/pseudex/Coursedrawer

**Comment by jmj486** [comment]
thanks @dkfiremann

**Comment by gammelgaard52** [comment]
@dkfiremann Will have a look at that when I get home - looks interesting.

**Comment by sootysax** [comment]
Just know.. that is an unauthorized edit of coursedrawer.. it's buggy..   the official relase from PromGames won't be released until CP is released

**Comment by dkfiremann** [comment]
But can one get a link to a beta then? 

I just did a google search on CourseDrawer, and that link was the only one able to work with CoursePlay v. 5

**Comment by sootysax** [comment]
thats the only coursedrawer that is available right now..  PromGames' official version is not available yet

**Comment by Satissis** [comment]
I know this is an old one, but I will answere anyway.
The way crossings works, is it's trying to find the crossing on the next route that is closest to the one you want to merge it with, so it's not always good in crossings.

It have been like that in all the time I know, and frankly not sure when or if we are going to try improve it.

I will add it to our suggestion list and close here again, so we can clear the issue list a bit from the suggestions.
