### ISSUE TITLE
Tipping problem with IT Runner truck

### ISSUE THREAD

**Issue by SavageMkII** [Courseplay/courseplay#1792]
When I'm running my IT Runner truck(it's custom, but there are a few on Giants ModHub), I get this error when I try to get Courseplay to dump into a tip trigger:

Error: Running LUA method 'update'.
C:/Users/Adam/Documents/My Games/FarmingSimulator2017/mods/Courseplay_5_BETA/toolManager.lua:124: attempt to index local 'workTool' (a nil value)

Now, I'm not very good with .lua scripting, but looking in the toolManager.lua file, at line 124, looks to me like it's expecting the attached IT Runner module(skip, grain container, etc) to be something it's not. 

Courseplay works fine with the IT Runner trailer and one of these containers, and dumps in the tip trigger like any other trailer would, but with the IT Runner arm mounted on a truck, it seems like it's not reading the tool properly.

**Comment by pops64** [comment]
Do you have link to the IT runner truck your using? What is weird is you shouldn't be getting an error because the only place I could find this function call it is protected from being passed a nil value. Are you reversing into the tip trigger? Does it work fine if you drive forward through the tip trigger? Not much we can do with out a link to mod that is causing you issues.

**Comment by SavageMkII** [comment]
My apologies, but I should have done some more testing before opening this issue, so I could answer questions like that. I will do some more testing in the morning(I'm in Canada), and get back to you.

**Comment by SavageMkII** [comment]
Ok, so I tested this some more, and have determined that it it not the tip trigger, or the fact that i am trying to get CP to tip into a trigger at all. It throws the error any time one of the IT Runner trucks tries to reverse under CP control. As soon as the truck hits the reversing waypoint, it starts throwing the error, and CP seems to freeze. I can still stop the driver, and everything recovers. 

Here are links to the IT Runner trucks on Giants ModHub:

Tatra truck pack has an IT Runner truck in it:
http://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=66206&title=fs2017

Lizard SX 210 IT Runner:
http://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=67509&title=fs2017

Lizard Barrelcore IT Runner:
http://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=67375&title=fs2017

and of course the IT Runner pack:

http://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=49828&title=fs2017

I tested all of these, as well as my own custom made truck, and they all throw the error when trying to reverse. Everything works fine when running a forward driving course through a tip trigger. I also tested the IT Runner trailer again, with a standard game tractor pulling it, and it works fine, no errors at all, so I know it is only a problem with the IT Runner arm mounted directly on a truck, and only when reversing.

Thanks guys!

**Comment by SavageMkII** [comment]
Now that I realize what the problem is, I should mention that I encountered this error once before. I was using a different IT Runner truck(a bit of a dodgy mod, which is why I didn't think the problem was CP), and using the IT Runner manure spreader with it on a fieldwork course. It would throw that same error any time it would try to back up while turning around. So, it seems that CP freezes with that error any time it tries to back up an IT Runner truck.

**Comment by pops64** [comment]
Could you run this with debug channel 6 (turned on before CP start) and post that log. This is the list that populates workTools

**Comment by Satissis** [comment]
I have an test truck already with the hook lift arm, so I'll do some tests and I'm sure I would be able to find an solution for it, since I believe it just a simple check we forgot to add in. (We had something similar with the module attachment at some point, so I just need to check that and see if we can reuse that for the hooklift :) )

**Comment by SavageMkII** [comment]
Sounds good. Thanks for looking into this guys, and for all the hard work you've put into this awesome mod!

**Comment by Satissis** [comment]
Should be fixed in v01.00102.
Try it out and report back.

**Comment by SavageMkII** [comment]
Ok, I will test as soon as I can. Thanks Satissis!

**Comment by SavageMkII** [comment]
My truck works beautifully with CP now! No problems loading or unloading, recording and following courses works perfectly! Thanks guys!
