### ISSUE TITLE
"drive on" limit not working in Combi mode

### ISSUE THREAD

**Issue by gentfarmer** [Courseplay/courseplay#1794]
I have set the tractor to "start at" 80% so when the harvester reaches 80% full the tractor drives to unload the harvester.
I have set "drive on" to 85% but the tractor does not "drive on" until it is 100%
Harvester is the Case 9230 with the 3162 Draper 45' header or the Capello Diamant HS8.
Tractor/trailer is the Case Puma CVX & Joskin Trans-space 8000.
Map is Lawfolds but the problem happens in other maps.
Courseplay is v5.01.00080

Log file link
https://gist.github.com/gentfarmer/4452a6631d766117c785e8a1259ca83a

**Comment by pops64** [comment]
The drive On % only works if the the tipper is waiting for the harvesters. If it is say at 84% it will sit and wait until the harvester is above the start at % and unload the harvester. It won't drive away from the harvester until the harvester is empty or it reaches 100%. Is this what is occurring. Or is it waiting for the harvester above your drive on percent? Post a log with debug channel 2 active. Thanks

**Comment by jmj486** [comment]
Also remember that the pipe should be away from the crop... If not, it will only unload at 100%

**Comment by pops64** [comment]
@jmj486 you have the option to turn that off. with the pathfinding setting in the settings tab.

**Comment by gentfarmer** [comment]
@pops64 let's say the tipper is at 78% full, when the harvester reaches 80% full the tipper sets off to unload the harvester. During unloading the tipper waits until the harvester is empty or the tipper is 100% full.
My understanding is that the "drive on" setting tells the tipper to leave the harvester when it reaches the "drive on" fill level, in my case 85% but it's not doing that, it will stay unloading the harvester until the tipper is 100% full.
Hopefully I can do a channel 2 debug later.
jmj486 I thought pathfinding wasn't working? Certainly in my case the tipper will drive over crops to get to the harvester whether the pipe is in or away from the crop. Pathfinder is active.
Thanks

**Comment by pops64** [comment]
The drive on percentage was only implemented for chaff harvesters(Or suppose to be). At this time the drive on percentage doesn't work for combine harvesters only when the tipper has finished unloading the combine and it is parked and waiting for the combine to fill again does the drive on percent work.

**Comment by gentfarmer** [comment]
@pops64  Thanks for that. I was going off how it worked in FS15, or at least how I thought it worked then.
I won't bother sending the log file then.

**Comment by Zoochase** [comment]
From my experience, the "Drive on" fill level was for the tipper to unload.  If the harvester is empty and your tipper is at or above that percentage, it will go unload.

**Comment by gentfarmer** [comment]
@Zoochase Not according to the manual for v4
"If the trailer isn't full yet (Drive on at %), the tractor turns around and waits in the field for his next unloading operation. As soon as the trailer's fill level is above the Drive on at % percentage, the driver will drive to the course's second waypoint, and from there continue the course, unloading the trailer and returning to the field."
I'm sure that's what I've seen in the various Youtube videos as well.
However it's not a big deal

**Comment by Zoochase** [comment]
@gentfarmer I feel like you just said the same thing I did only with a lot more words.  I honestly don't understand what you are asking and I'm not a dev so I am going to bow out now.

**Comment by pops64** [comment]
#1927 Closed due to inactivity. And a suggestion thread started about this
