### ISSUE TITLE
KRONE BIGM500 WIDE V 2.1 BETA wont buy when using course play version 5

### ISSUE THREAD

**Issue by mike1852** [Courseplay/courseplay#1798]
KRONE BIGM500 WIDE V 2.1 BETA wont buy when using course play version 5. will buy with version 4

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by mike1852** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/794618/log.txt)

**Comment by pops64** [comment]
try again with the current version of CP. Were at version 81 now. Things have changed since version 23

**Comment by mike1852** [comment]
i am on gold creast using only the krone bigm500 wide v2.1 beta and the other mod is course play version 5.001.00023

**Comment by pops64** [comment]
try again with the current version of CP. Were at version 81 now. Things have changed since version 23

**Comment by mike1852** [comment]
were do i download it from as the version from course play site wont reconize as course play mod even though i put it in the mod folder and overwrite the old version

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/archive/master.zip

**Comment by mike1852** [comment]
yes that worked and has fixed the problem thanks very much for your help
