### ISSUE TITLE
Seeder over shooting after refill

### ISSUE THREAD

**Issue by Zoochase** [Courseplay/courseplay#1799]
I've noticed recently my seeder over shoots where it left off when it returns from refilling.
![20170221212201_1](https://cloud.githubusercontent.com/assets/25461823/23198431/57dd794e-f87c-11e6-89d9-992d8038d65b.jpg)

**Comment by sootysax** [comment]
what is your turn and field speed set at? maybe slow it down

**Comment by Zoochase** [comment]
20 and 8.  Always been that.  Could this be from Giant update?

**Comment by pops64** [comment]
This was disscused in #1705 Quote from Thomas
>  yea its because in mode6 its not that issue that the tools are starting earlier, but for sprayers we had claims that turning the tools on earlier would be a waste of fertilizer... so won't fix

If this really becomes an issue for you. Line 56 change the 9 to an 8 and should fix your problem.

**Comment by Zoochase** [comment]
Thank you for the response.

**Comment by Satissis** [comment]
Try again with v01.0083 or higher and report back.
Fix was made by @pops64.

**Comment by Zoochase** [comment]
Good fix.  Thank you.
