### ISSUE TITLE
Mode 3 error. (Overloading)

### ISSUE THREAD

**Issue by Raints** [Courseplay/courseplay#1801]
Log full of this:

C:/Users/Rainer/Documents/My Games/FarmingSimulator2017/mods/ZZZ_Courseplay/mode2.lua:538: attempt to index field 'acDirectionBeforeTurn' (a nil value)
Error: Running LUA method 'update'.

Most equipment are mod's. Using 3 overloader's and 3 harvester's in same field. Game just hangs.

Is this might be related to AIVehicleExtension mod or something else?

**Comment by pops64** [comment]
Autocombine support is not yet implemented at this time. #1701
