### ISSUE TITLE
Question about mode2.

### ISSUE THREAD

**Issue by Raints** [Courseplay/courseplay#1802]
Not sure why but with forage harvester driver's act weird. When first driver reaches "Start at 20%" what is set in CP. Second driver not moving at all, it states following tractor but its not. I know CP in test period, but it did worked before (not sure which version). There's been so many changes and allways something breaks.

**Comment by pops64** [comment]
What is the 2nd drivers start at %? Has this is what the 2nd driver follows. And the first driver follows the start at 20% while waiting for the 2nd driver

**Comment by Raints** [comment]
All 4 driver's have "Start at 20%"

**Comment by pops64** [comment]
Log with debug channel 4.

**Comment by Raints** [comment]
Using manual mode. Hope this log help's.

[log.txt](https://github.com/Courseplay/courseplay/files/797528/log.txt)

**Comment by Raints** [comment]
Think I had bad mod or something. Using now V2 of JD 8000 forage harvester for couple of hours and no problem anymore. Will close it for now. If something change will open again.
