### ISSUE TITLE
Field turning

### ISSUE THREAD

**Issue by DynamicXYZ** [Courseplay/courseplay#1807]
I have this problem where my tractor would jackknife when reversing on the last part of the turn. Sometimes its really bad and other times its just bad... it might be the set up of the tractor and tool.

[Log](https://gist.github.com/DynamicXYZ/ad751112c936a56b182fa1e69f2b0c2d)
https://youtu.be/1T-XGZCNix8

**Comment by Satissis** [comment]
Yeah I can see on the video what is going wrong.
The way it's build is that once it's turned around and aligning up, it checks if the tool is less than 3 degrees aligned to the next lane direction. That part do work fine, but it also have an failsafe, so if the tractor reaches the end of the aligning line before it starts to reverse, it don't care about the implement alignment anymore.
All it need to do is add more length to that line to it, so it can align the tool better before reversing.

I'll look into this today and push an fix ;)

**Comment by RKI91** [comment]
Just set 20m turning angle, for me that setting works fine. :)

**Comment by Satissis** [comment]
@RKI91 yeah that will work, since it changes to another turn type, that overturning it and makes it align up allot better for the distance it have.
But that still don't fix the other problem ;)

**Comment by Satissis** [comment]
Try again with v01.0087 or higher and report back.

**Comment by Commissar0617** [comment]
I have same problem when using the longest plow, the turn radius of the tractor is much less than the implement

**Comment by Satissis** [comment]
@Commissar0617 is that the vanilla plough or an modded one ?
The vanilla one should not reverse if I remember correctly.

**Comment by Commissar0617** [comment]
sry, it's only slightly related to this one
 

    On Friday, February 24, 2017 5:47 PM, Claus G. Pedersen <notifications@github.com> wrote:
 

 @Commissar0617 is that the vanilla plough or an modded one ?
The vanilla one should not reverse if I remember correctly.—

**Comment by Satissis** [comment]
@Commissar0617 alright, well you should make an new issue about it then and take screenshots of it with debug mode 12 and 14 active and also add your full log to gist and post a link for it in that issue.
Just so we can keep them separate.

**Comment by Commissar0617** [comment]
#1812 is the issue i was talking. seems to be the same.

**Comment by Satissis** [comment]
@Commissar0617 This was fixed in v01.00089

@DynamicXYZ Did this fix it for you ?

**Comment by DynamicXYZ** [comment]
Sorry I didn't get to try it since I had to reinstall Windows and among other things. I'll test it to see if it works within 32 hours of past this post time stamp.

**Comment by Satissis** [comment]
@DynamicXYZ yeah no problem :)

**Comment by DynamicXYZ** [comment]
I can confirm this update fixed the issue. Thank you.
