### ISSUE TITLE
Question about harvester in mode6.

### ISSUE THREAD

**Issue by Raints** [Courseplay/courseplay#1808]
I just want to know why combine at 80% turn's pipe out and not act as normal hired worker? Would be great if pipe turn's out only when driver is near harvester. 
Why it would be great? I use headland mostly and if I have tree's close to field edge, pipe will get stuck.

**Comment by jmj486** [comment]
Then go the other way around the field, that way you wont hit the trees

**Comment by Raints** [comment]
@jmj486  I'm talking about simulator game. I know I can do that.

**Comment by Zoochase** [comment]
I have a suggestion for the Dev's on this same subject.  I know the harvester will not call for a tipper when the unload is still on the unharvested crop side.  Can you make it so when the harvester reaches 80%, it will call in the tipper regardless?

**Comment by Karlshoj** [comment]
You just have to deactivate pathfinding for the tractor

**Comment by Satissis** [comment]
yep just as @Karlshoj said, meaning it's already implemented ;)

**Comment by Zoochase** [comment]
Thank you.  Still learning about a lot of these settings.

**Comment by HansJDen** [comment]
@Satissis is there any description of these features? I din't know that one with Pathfinding. 

Thanks again for a great script.

**Comment by Satissis** [comment]
@HansJDen yes there is.
http://courseplay.github.io/courseplay/en/manual/index.html#hud_generalSettings

The manual it not fully up to date yet, but most of the things that are already in there, should be fine.

**Comment by pops64** [comment]
#1478 Closed to keep the issues area clean
