### ISSUE TITLE
(Suggestion) Switched off the engine while waiting.

### ISSUE THREAD

**Issue by RKI91** [Courseplay/courseplay#1811]
Like in name of topic.

In the CP we have many modes by which whether a tractor or some other machine stay and waits for the outher machine / Get specific fill limit. I thought that was a good idea to give the machines the ability to turn off the engine at that time. Eg. Tractor in the combine mode waiting for a specific fill limit. This is just one example of where you could use it to but it certainly will be more of this. The advantages flowing from this solution? No unnecessary punching moto hours and, above all, fuel economy, which was particularly noticeable that in the case of large machines.

**Comment by Satissis** [comment]
This have already been suggested in #1429
