### ISSUE TITLE
Valtra T series turning problem

### ISSUE THREAD

**Issue by remis1989** [Courseplay/courseplay#1812]
Hi, i use valtra T series for moving grass, i use 8.4m poetinger mower and driving mode is backward. when tractot is turning on the end of the line driving round and dont stop. Cant find second line or something. i use fichtelberg map. i use 1 line headland and turn on field option.
![fsscreen_2017_02_25_00_20_49](https://cloud.githubusercontent.com/assets/25843387/23323361/ed52d62e-faf0-11e6-96fd-15bd1c25b28f.png)

[log.txt](https://github.com/Courseplay/courseplay/files/800598/log.txt)

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki pictures? Debug 12 and 14

**Comment by Commissar0617** [comment]
i've got the same excact issue, intermittently, with both the CAT challenger (tracked) and the Magnum, using the plow. i think it was also present with the challenger in FS15. probably something to do with the tight turn radius of the tractot being restricted by the implement

**Comment by Satissis** [comment]
Yeah I can reproduce that... Don't know what version I broke it, but I know where it's breaking. I'll have a look at it tomorrow.

**Comment by Commissar0617** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/800873/log.txt)
http://imgur.com/a/3KBIX

**Comment by Satissis** [comment]
Should work again in v01.0088
try it out and report back.

**Comment by remis1989** [comment]
latest version cp dont work on fs17 v1.4. i cant find cp in mod list

**Comment by Raints** [comment]
@remis1989  All good here. Maybe you post your log.

**Comment by sootysax** [comment]
fine for me too..  latest FS17 version is 1.4.4.0

**Comment by Satissis** [comment]
@remis1989 yeah the v01.0089 there were an change, which only works with patch 1.4.4 of the game, so CP was changes to require patch 1.4.4

**Comment by remis1989** [comment]
or it is possible to run on 1.4?

**Comment by Satissis** [comment]
yes, change back to v01.0088 as 89 is where that changes.
here is a link for it: https://github.com/Courseplay/courseplay/tree/8dcacc6d33b83d40933a34dace1eb0d850bb68de

But I don't see why you would not want to update your game to 1.4.4, since that fixes some other good stuff as well.

**Comment by remis1989** [comment]
thx a lot

**Comment by Satissis** [comment]
Can we close here then ?

**Comment by remis1989** [comment]
yes sure, everything is working, thx mate

**Comment by pops64** [comment]
Closed to keep issues area clean

**Comment by Hubcap-1** [comment]
Important suggestion in finding a solution to backing up. I think the programming of this mod lacks a serious portion of consideration. There is an important " geometry" consideration when backing any vehicle. This is known technically as a " Bridge rule". The " Bridge" is the distance from the attacher pivot point to the center of the rear axle ( Or the middle point between a dual or triple rear axle). This measurement is key to figuring out the input required from the " control vehicle" ,( the tractor) , for a successful reverse maneuver. I believe the formula incorporated at this time is only worked out ( oversimplified) for short wheel base rear attachments like the Horsch pronto or something similar

**Comment by pops64** [comment]
It depends on the configuration of the tool and the vehicle. And in 19 if it was converted correctly because there is a lot of black magic that goes on behind the scenes and with the way Giants changed things it broke all of it. Some of the really old stuff hasn't been touched since it was put there along time ago. So as you can tell by the issue count the CP Dev team is slowly working through things that didn't get converted correctly or at all.
