### ISSUE TITLE
combine turning

### ISSUE THREAD

**Issue by remis1989** [Courseplay/courseplay#1813]
hi, have a problem, i use combine with 13m header, 1 line of headland and turn on field option. problem is my combine bad turning on the end of line, he dont drive backward just turning and hit the wall, how solve this problem without 2 or more headlands lines?

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki pictures? Debug 12 and 14

**Comment by Satissis** [comment]
Combines don't reverse inside the fields without headlands.
The simple reason for this is if you have crop destruction on, the turn will ruin some of your crops.

If you don't have enough space at the ends of the fields for the turn, then you should generate the field route with 2 headlands before doing the lanes, which should clean up enough space to turn on.
if 2 headlands is not enough, then increase it and test again.

This is just a matter of getting the know how on how many headlands you would need.

**Comment by remis1989** [comment]
ok, thx man

**Comment by pops64** [comment]
Closed to keep issues area clean
