### ISSUE TITLE
Swicth to forward when reversing unloading

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1818]
Some times CP doesn't switch to forward driving direction when finished unloading. Which causes traffic collision issues.
![farmingsimulator2017 64bit 2_25_2017 11_30_36 am](https://cloud.githubusercontent.com/assets/10678220/23332934/243f5e28-fb50-11e6-8140-4e266188487d.png)

Savegame and courses https://www.dropbox.com/sh/bxma5xu8cx6ff7v/AAAlOadV4J3DTSiFN7wHZM_ra?dl=0

**Comment by Satissis** [comment]
Should work fine now.
