### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by scubasteve89** [Courseplay/courseplay#1821]
i attempted to solve this issue myself before creating an issue log but i was unsuccessful. the problem is that i downloaded Courseplay for fs17, installed it into my mod folder, and when i go to select it for the game it is not in the mod page before the game starts. so far this is what i have done to try and resolve the problem: my game is up to date on versions (1.4.4) it is the steam version, the file downloads as just ZZZ_courseplay so i addded .zip to the end, i tried putting it in as ZZZ_Courseplay.zip and ZZZ_courseplay.zip. there were two issues that i could find like my issue but one was due to a not up to date game version and the other was solved somewhere else. if anyone has a fix for this i would be very grateful!
thank you for your time

**Comment by Raints** [comment]
Where did you download CP version. File you get should be first named courseplay-master.zip
![1](https://cloud.githubusercontent.com/assets/3618060/23337844/246da5cc-fc03-11e6-9a01-9e52911459ac.png)

Then just unzip it
![2](https://cloud.githubusercontent.com/assets/3618060/23337846/34de46a0-fc03-11e6-9204-89819277ba00.png)

and you should have folder called courseplay-master

Now just zip it up
![3](https://cloud.githubusercontent.com/assets/3618060/23337849/5a10e5fe-fc03-11e6-8540-27e854834c16.png)

After that just name it ZZZ_Courseplay 
![4](https://cloud.githubusercontent.com/assets/3618060/23337851/6ed4ad7c-fc03-11e6-9294-17909fdd449b.png)

Place that in your mod folder and you good to go.

**Comment by Alpris** [comment]
Hi, 
I have the exact same problem here. I downloaded all of your versions since 2k13 from this page. Today I thought I download the new version, because I throw many mods out of my mods folder. Pls check that out, I need CP so much.

**Comment by gec100** [comment]
the latest CP version has a bug in modDesc.xml
<modDesc descVersion="37"> should be <modDesc descVersion="34">

**Comment by Raints** [comment]
@gec100  37 is correct version. You should update your game first.

**Comment by scubasteve89** [comment]
thank you for your help! i downloaded the version i thought was the correct version from your site, the one that has a pot of tea for english and a mug of beer for german (atleast i thought that was your site). thank you again for your help i was able to fix this issue! you can close this ticket

**Comment by dkfiremann** [comment]
That is the correct site, but it has only released versions. 
There are no release of CP for fs17 yet.
Therefor You will not find a version for fs17 there.

**Comment by pops64** [comment]
Also you no longer need to name your CP folder ZZZ_Courseplay. FS17_Courseplay5 should work just fine

**Comment by Satissis** [comment]
or use the manual :)
The install guide have been updated.
http://courseplay.github.io/courseplay/en/installation/index.html

**Comment by pizman** [comment]
Hello.  This is my first Posting here. Hope this is right section......
You say in manual the released version is LS17_Courseplay5.zip......  But where can i get it ??
Youre Downloadlink on Homepage bring me to Modhoster but there is V4 for LS15 only.

**Please tell me where i can download release Version ( Not the Developer Master.zip ).**

And maby a request for future....  Can you put the download link additional in the Manual/Instalation Guide ?  I think 99% of the users who read this page wan´t to install it at this moment....  Would be cool if we not need to search for link if it´s already there in this manual section.
Thank you for youre work guys !

**Comment by dkfiremann** [comment]
@pizman There is no release version yet for FS17/LS17.

If you do not want the developer version, then you need to wait until Courseplay has been released for FS17/LS17.
I agree that the manual should make it more clear that Courseplay has not been released.

**Comment by MOOOOs** [comment]
same here not working anymore after Feb 26, 2017 commits Feb 24, 2017 commits worked fine now courseplay not showing up in mod selection menu please solve this problem i love this avesome mod :)

**Comment by dkfiremann** [comment]
What version of FS17 are you running? 
You have to be on version 1.4.4 to be able to use Courseplay as of the latest commit.

**Comment by MOOOOs** [comment]
oh im on 1.4.2 :D

**Comment by pops64** [comment]
Closed Has everybody should be updatd to 1.4.4 by now.

**Comment by Visso79** [comment]
Hello.
I was same problem - not load a game when selected a courseplay. I can wait 5, 10, 15 minutes and more.
If not a select that all loading.
In log file see a error with lua:94
Thanks wait for answer.
P.S. Downloaded all latest versions. 
[log.txt](https://github.com/Courseplay/courseplay/files/871053/log.txt)

**Comment by Satissis** [comment]
@Visso79 from the log, it looks like it's either missing the vehicles.lua file in CP. This could be due to an bad download or that you didn't rezip all the files from the extracted zip file downloaded here.
