### ISSUE TITLE
Transfer mode

### ISSUE THREAD

**Issue by jmj486** [Courseplay/courseplay#1825]
Is it possible to Change Transfer mode so it as default is "stop at the end of the line"

I hate, when I have sent a tractor on the way to the shop, suddenly get a message that says that it is stuck some where because i have forgot to hit the button :(

**Comment by Satissis** [comment]
I'm afraid not.
It's meant to be used with wait point at those places it needs to stop, so you can create one continues route in a loop where you have more than 1 stop. It would simply just disable most of the point of it

**Comment by jmj486** [comment]
ok thx
