### ISSUE TITLE
Unable to install CP for FS17 on my MacBook

### ISSUE THREAD

**Issue by moserartz** [Courseplay/courseplay#1827]
Hi Guys

i have a problem with installing the latest Version of Courseplay in FS17.

What i have/did:
-I have a MacBook Pro (Sierra 10.12.3)
-I've downloaded the game with Steam
-The game should be up to date --> no updates available
-I downloaded the latest version of courseplay via GitHub
-i putted the archive ZZZ_courseplay.zip in the Folder .../Libary/Application Support/FarminSimulator2017/mods/
-i restartet the Notebook, Steam and the Game about three times
-another mod, which i loaded is working without any problem

what is happening:
-well, nothing. no error prompt, no messages, nothing. it is like i've never put the zip in the folder.

[log file](https://gist.github.com/anonymous/bcf678dbcc457af6a52a11eb5677f772)

thank you for all ideas to solve this problem. 

cheers
verumverso

**Comment by dkfiremann** [comment]
You need to install the right version for fs17. 
You have installer the release version for fs15. 

Take a look at #1821 on how to get the right version.

**Comment by pops64** [comment]
Has dkfiremann said. #1821 closed to keep the issues area clean

**Comment by moserartz** [comment]
sorry, my fault.

i was thinking that the download link on http://courseplay.github.io/courseplay/ is from the actual version.

thanks for the fast support! it works now
