### ISSUE TITLE
BGA Unload in Traffic

### ISSUE THREAD

**Issue by mike3112** [Courseplay/courseplay#1830]
ive set a course to unload bga but just before it reaches the tip wait point it says its in traffic.
also when i set a leveler course on the pit the tractor would detect something unless i turned down the distance to 10m despite there being no tractors in the area. is it picking up the bunker as a vehicle?

**Comment by dkfiremann** [comment]
First of we need to see a picture of what you are seeing. 

Next, to be able to unload to a bunker, you do not need a tip wait point, just drive into the bunker, forward or reverse.

**Comment by pops64** [comment]
Log with debug channel 3 and 10 active. As well has a picture with F5 active.

**Comment by mike3112** [comment]
https://github.com/Courseplay/courseplay/issues/1830

**Comment by mike3112** [comment]
https://gist.github.com/mike3112/a98cce26a14c1eac4efd14353cd6ab22

**Comment by mike3112** [comment]
![fsscreen_2017_02_28_17_00_50](https://cloud.githubusercontent.com/assets/26089471/23415818/5005272e-fdd8-11e6-959e-b46ecdf0b0da.png)

**Comment by mike3112** [comment]
F5 didnt do anything to my knowledge :/

**Comment by mike3112** [comment]
![fsscreen_2017_02_28_16_56_04](https://cloud.githubusercontent.com/assets/26089471/23416464/cdeababc-fdda-11e6-9287-c7c096d018e7.png)

tried again with the jcb

**Comment by pops64** [comment]
You have to enable developer mode first. In your farming simulator 17 folder(The parent directory of the mods folder). Open the game.xml file 
```
    <development>
        <controls>true</controls>
    </development>
```

Change the above to true. And hit F5 once. And upload those pictures. BTW github did not accept your pictures.  Also dkfiremann  is right and mode2 or 1 does not need any unload or waitpoints it automatically detects where to unload.

**Comment by mike3112** [comment]
What do you suggest I upload pics with? I posted them via PC and now I'm on my phone and I can see the pictures. 

I'll enable developer mode in the morning and upload new pics

**Comment by pops64** [comment]
Never Mind. Github I think was having issues today.

**Comment by mike3112** [comment]
![fsscreen_2017_03_01_07_55_23](https://cloud.githubusercontent.com/assets/26089471/23450736/93cc4a2e-fe54-11e6-9e15-719d5dbbae76.png)

**Comment by AgroWillem** [comment]
I had a somewhat same issue with the following:
When my Liebherr L538 was waiting (with no script) IN the bunker, my tractor (who was filling up the near bunker) ran to the waiting point and kept waiting.
After driving the Liebherr OUT of the bunker to another point, the tractor started working again.
Not just your problem, but it looks a little.

**Comment by pops64** [comment]
Collapsing mod issues into one thread. #2231. This one won't make the list because no name is given for mod in conflict. The JCB not working is because of improper setup.
