### ISSUE TITLE
Overlaoder Mode, Crop destruction,  Disable or Avoid Crops

### ISSUE THREAD

**Issue by SirAlbertL** [Courseplay/courseplay#1835]
I am using AIVehicleExtension found here,
https://github.com/Mogli12/AIVehicleExtension

And am asking about the possibility of a fix for the CP Overloader mode to ether fallow the Crop path to combine, or to disable the Crop destruction,
http://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=50271&title=fs2017
 while under CP control.

Currently I just remove the 4Real Module 01 - Crop destruction from my mods folder...

Thank you all for the great work you do, and the time you put into it.......

**Comment by DynamicXYZ** [comment]
I don't think you can disable crop destruction for a specific vehicle. You need actually disable the entire crop destruction mod.

In the future there could be an option for the overloader to work with the harvester to avoid crops.

**Comment by SirAlbertL** [comment]
AIVehicleExtension Dose it some how for the Combine when under hire, and works great when not under hire.. ....That could be a glitch or deliberate I have no idea...

Crop avoidance would be optimal, but god only knows how many hours that would require to script..

**Comment by pops64** [comment]
#1465(Link there on how to disable how crop destruction for hired workers) and #1402(Crop Avoidance) Closed to keep the issues area clean.

**Comment by Satissis** [comment]
I'll reopen here again, since I have an suggestion for this and want to get your opinions about it.

I can add in so once an cp driver is active, it will deactivate crop destruction and reactivate it once stopped again.
Would that be something you would like to see until we get to work on the crop avoidance system ?

**Comment by DynamicXYZ** [comment]
@Satissis I like that idea. There should be an option to disable this temporary feature though and possibly only available to those who have crop destruction installed.

**Comment by Satissis** [comment]
I'm not sure I will make an option for it, since the option pages are starting to get cramped a bit and we have already some planes for most of the spaces left.
but yes it will only work if you have the crop destruction mod.

**Comment by DynamicXYZ** [comment]
Would it be reasonable to make scrollbar so you can add more items on each of these pages? But yes you're absolutely correct that it's getting cramped, in fact it looks terribly messy. I think the settings should be reorganized into better categories. Not to mention half of the English text is all lowercase letters among which have every letter of the beginning of the word capitalized though it doesn't bother much as it used to.

**Comment by HansJDen** [comment]
I think that's a great idea for now.

**Comment by SirAlbertL** [comment]
That would be assume Satissis, Thank you very much...

**Comment by lcc1211** [comment]
I like that idea.  It is the only reason I'm not using crop destruction at the moment.

**Comment by Dzi4d3k** [comment]
4Real Module 01 - Crop destruction with update 1.0.2.1 has no crop destruction for AI vehicles. Does it won't work with CP?

**Comment by pops64** [comment]
Look at the code for it or try it on a field. CP uses the same flag that gaints does to tell FS that it is ai controlled. self.hired if I remember correctly

**Comment by Satissis** [comment]
Implemented in v01.00109.
Try it out and report back.

**Comment by HansJDen** [comment]
It's working just fine...
