### ISSUE TITLE
forstacker

### ISSUE THREAD

**Issue by jmj486** [Courseplay/courseplay#1836]
Will the forstacker be supportet?

**Comment by DynamicXYZ** [comment]
What is the link to the mod?

**Comment by pops64** [comment]
Clean Link to the mod in question. And what specifically is the problem that is occurring with the mod and CP interaction

**Comment by Satissis** [comment]
I believe the Forstacker is the default new square bale stacker, which can stack 3 high and then drop them of somewhere and then use an telehandler to load them unto an flatbed trailer.

If that's correct, then I don't believe that one will be supported, since you would still have to stack everything manually onto an fladbed and can't automate it all.

If you can give an really good description and suggestion to why it should be implemented, then we might reconsider it.

**Comment by Anstonio** [comment]
You cant automate the whole thing indeed, but now you can use CP for the making of the bales, and do not need to stack them 4 high by telehandler or sort. I hate the stacking of the bales, and with that 4 stacker i only need to load up the bales manual and drive the truck to the drop off point.

**Comment by Satissis** [comment]
well it should not be that big an problem making it work like the auto stacker, so once it's full, it will either follow an unloading route with an unload point or if there is no unloading route, then just drop the stack where it is and continue if the option is turned on for that.

**Comment by jmj486** [comment]
Right now the only problem with an unload route will be that you have remove the first stack before it return.
Unless CP can detect the stack in front and turn a few meter to the right or left and then unload

**Comment by Anstonio** [comment]
Is it then still possible to use it towed behind the baler itself? So you dont need another tractor. Like they are doing here?
http://www.farming17mods.com/tst-quadro-pac-v-mod/

Is it possible to make these option of eather drop Them on the field when youre full of drive Them home?

**Comment by pops64** [comment]
@jmj486 this is on our to do list to fix for stackers in reverse driving unloading

@Anstonio if you want a separate mod supported please make an new issue describing what the conflict is and a clean link to the mod in question. The link you provided is not a clean one.

Closed to keep the issues are clean
