### ISSUE TITLE
Problem with Water Transport to a factory

### ISSUE THREAD

**Issue by pizman** [Courseplay/courseplay#1837]
Hi Guys.  I´m new. Hope this is right section and you can help.

I use modMap  "Volksvalley" and there is a Water-decalcifaction Factory there.
I try to use CP to bring Water load from the Farm (Pump) to bring it to factory and load out there.

First i try Mode1 (Transport- Load on Start Point) .  I Can choose "Water" as Type.... But CP not start loading the water on the pump.
THEN
I Use Mode "Liquid Trasport" and CP starts to get the water (without Holding Point there... it stops already if Pump is near the route)   BUT Problem....   I can´t make it working that it load out the water on the factory. I Try to set a Hold point there and a LoadOut Point, too.  Nothing work.

Look like the problem is the load out technic.  I ´can´t use the standard "i" Button there. To load out i have to use the "r" Button for this mod Factory if i drive manual.    Is this the issue ??
( I don´t test alreade but maby same problem is with other liquids like milk or fuel at Mod Factorys) 

Please tell me if i do an mistake and THIS is still posible with CP.... OR please tell me if this feature is planed next time ! 

Thank You !

**Comment by lcc1211** [comment]
If you've used liquid transport and CP is filling the container, and you've placed a wait point at the tip trigger, then CP is not recognizing the tip point or you are not in the exact spot where the tip point requires.  Perhaps reply back with a copy of your log attached and maybe a video of the course as well.

**Comment by pizman** [comment]
Thanks for reply.
I´m sorry to say i got no experience with logfiles and where it located.  additional i never make a video before.  So i can´t send you this stuff.
Maby the follow information helps you, too  ....

-When CP reach the Factory it stops and NOT loadout the Water.   It stay there forever.  If i get into vehicle and stop CP Helper  (not moving the vehicle) i see it´s already in the upload zone.... So i can now use "R" Button to start overloading myself if i want.  ( Position looks good i think)

- I try for testing to use a 100k water Tank from my "Kotte Pack" instead of the Factory Tip point .....
I make a test Route.   Here it workes with Liquid Transport Mode.... CP get the Water on Pump ( No Holding Point there)....  drives to the Tank.... Stops on the Holdingpoint i set near the Tank.... And then load out the water in the tank and start new round....  As i see in Videos the automatic Load Out on a Animal Water sport workes too.

So i think problem is the **kind of Tip Point**, that is used in this Mod-decalcifaction Building.

Maby someone got information if CP will work with those things in a futured version.

Thanks for youre Help guys !

**Comment by dkfiremann** [comment]
You need to supply a link to the mode you are using. 
I think it is your mode that is configured incorrectly. 
If it do not use the normal key for unload, then I suspect that the problem not with courseplay.

**Comment by Akoasma** [comment]
I think, it is this Mod https://www.modhoster.com/mods/slow-sojamilch-produktion
And the mod use the "FabrikScript" http://ls-modcompany.com/forum/filebase/index.php?file/21-fabrikscript-v2-1-71-13-02-2017-additionaltriggers-v1-0-4-13-01-2017/

**Comment by pizman** [comment]
Hi again.
I just search for the mod but i can´t find it as a single downlaod....
I use the Map Volksvalley ...  [https://www.modhoster.de/mods/volksvalley](url)
the decalcifaction is a part of it.....  I wrote a request for info to the modder of the map already....
Maby dkfiremann  you got this map (or download it quickly ) and can check this .
Thanks for youre greate support !!

**Comment by pops64** [comment]
Try with version 01.00116 or higher has the kotte universal was bugged with water triggers and report back

**Comment by SavageMkII** [comment]
Hi Pops. I have been trying to make this work on the mining_construction_economy V0.3 map. I have been trying to use CP to haul water from the fill trigger to the GoldMaster. The GoldMaster runs on the latest fabrikscript version, but CP will not unload water at the trigger. I am using mode 8, and using the Kotte Universal semi trailer with a dolly and tractor. I have the latest version(01.00116) of CP, but cannot get this to work, no matter what I try. I checked the collisionmask of the trigger itself, and even changed it to match the default animal water triggers (800000). The trigger works fine when I unload manually, but CP just seems to ignore it.

**Comment by pops64** [comment]
When you manfully unload it what does it say? Overload or Unload?  Did you place a waitpoint at the water trigger? Cause it should work with any tip trigger. Unless CP thinks it is like a greenhouse trigger.

**Comment by SavageMkII** [comment]
When I manually drive into the trigger it says "LiquideTriggerName_start" and then I can press "r" to unload. I did set a wait point at the trigger, and if I have waiting time set to 0sec, the driver will stay there until I override. If the waiting time is anything else, it will wait for that set amount of time, then just drive on, without unloading.

I am doing some more investigation into other Fabrikscript mods with liquid unloading triggers.

**Comment by SavageMkII** [comment]
I tried the HOT seeds and fertilizer production placeable mod, which uses Fabrikscript. The liquid fertilizer production building accepts water as an input filltype. CP will not unload at that trigger either.

I changed the trigger for the Goldmaster in the mining_construction_economy map to a tip trigger instead of a liquide trigger, and I can get CP to unload it in mode 8, but only if I position the vehicle in the trigger, at the wait point, then hit "start driver". Otherwise, if I let it run the course as normal, when it gets to the trigger and wait point, the driver seems to completely ignore the wait point. I can see in the CP control panel that the "continue" command pops up as if the driver is going to stop, but then it just continues on without stopping or unloading, regardless of the wait time setting.

I'm lost here. Is there a debug mode I can run to get more info? My log shows no errors or warnings.

**Comment by pops64** [comment]
You have to be in the trigger just right for the water to work other wise it will just skip it. And yea water only works if it is of the tip trigger class.

**Comment by jordyboytjuh** [comment]
Have the same issue with the kotte universal pack. With the liquid load mode it will load up at the BGA with  gülle, but it won't unload on the P spot. It says that it reaches the "overload point", but it won't empty. When i stop the courseplay, I can manually empty the tank with "R".

**Comment by pops64** [comment]
Collapsing mod issues into one thread. #2231

**Comment by Blackmankot** [comment]
@pops64  As far as I understand, the problem of loading in Kotte because of a narrow trigger. And this is the fault of the mod itself. And if you look for compatibility with the course Fortune pack? He is no less popular.

**Comment by pops64** [comment]
Kotte Pack Actually has a bigger trigger than vanilla tankers. The problem is that most don't realize is when you can manually do it is a little bit larger of an area than what CP can automatically do. Either way the mod that is on the main list is somewhere in this issue and was reported not to work. Most non Giants liquid triggers don't work with out additional support on CP's end
