### ISSUE TITLE
Loading courses

### ISSUE THREAD

**Issue by sesmo** [Courseplay/courseplay#1838]
I  play on a big map, so i generate big courses in fieldwork mode.

After 5 big fieldwork courses, the time for loading a game increases a lot.

I wonder if is possible a solution to load the courses only when we use them on the game, and leave as "ghost" when we dont need them.

I'm Not a programer, but I´m developing a new map, so if you need help in testing, feel fre to ask.

**Comment by DynamicXYZ** [comment]
Are you talking about the saved courses or those courses that are left on a vehicle after you exit the game?

**Comment by Satissis** [comment]
well saving big courses, can have an impact on the loading time, since it needs to load all the waypoints on game start. It's something we have in our todo list, so it don't load any courses until it's needed, which should speed up the loading time for the game.

Can we close here again ?

**Comment by sesmo** [comment]
Thank's guys for the response....

I will work on a solution to optimise the field courses...
RP
