### ISSUE TITLE
HUD opening key

### ISSUE THREAD

**Issue by snupple** [Courseplay/courseplay#1839]
Hi,  the HUD opening key options,   presumably thats supposed to be saved per course or vehicle?

I always thought it was odd that it wasnt global for the whole profile you're playing

**Comment by Satissis** [comment]
That's saved pr. Vehicle.
The reason for it is that if you are used to use the right mouse to open the hud, but are using an vehicle that are using the right mouse button for an action as well, then you can change it to something else (based on what you set the key to in the keybindings) so it's only changed for that specific vehicle and you can then still use the default one for the rest.

**Comment by DynamicXYZ** [comment]
Speaking about the HUD control keys I believe that they should be renamed. I forgot what the two names are now but it definitely confused me when I was trying to change the default control.

**Comment by snupple** [comment]
Thanks
