### ISSUE TITLE
FS17 says latest Courseplay is not installed when I load the savegame.

### ISSUE THREAD

**Issue by auddie2015** [Courseplay/courseplay#1840]
<version>5.01.00090</version>

It is also not showing up in the installed mods list. 

I am long familiar with how to turn master into the mod zipfile. I rezipped it a couple of times just to make sure.

**Comment by auddie2015** [comment]
Load mod: zzz_courseplay (Version: 5.01.00090)
Error: Unsupported mod description version in mod zzz_courseplay

**Comment by Raints** [comment]
@auddie2015 Just update your game.

**Comment by pops64** [comment]
#1821 Closed to keep issues area clean
