### ISSUE TITLE
Mode 10 with front loader?

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1841]
Do we setup the course the same with mode 10 with a leveller on a front loader?  it would be driving forward and not in reverse for the blading..

**Comment by dkfiremann** [comment]
I dont think that the frontloader is supported by mode 10 yet.

**Comment by pops64** [comment]
Mode 10 doesn't support frontloader atm. It has been suggested somewhere but I can't seem to find. I will close this to keep issues area clean
