### ISSUE TITLE
Help with Lights

### ISSUE THREAD

**Issue by p4r4d0xs** [Courseplay/courseplay#1842]
Hello, 
can someone help me maybe? I want to keep off the Lights when the Courseplay helper is working. So maybe somone know which value i have to change  to keep the lights off?

**Comment by pops64** [comment]
http://courseplay.github.io/courseplay/en/manual/index.html#hud_generalSettings . Under the general settings tab

**Comment by p4r4d0xs** [comment]
there i can only put off the bacons!

**Comment by Satissis** [comment]
They should only turn on in evening and night times, which is where you would normally use them anyway.

**Comment by p4r4d0xs** [comment]
yeah, but i had a problem with a mod that Courseplay have all time the lights on

**Comment by pops64** [comment]
Could we get a clean link to the mod in question that is keeping the lights on?

**Comment by pops64** [comment]
Closed due to no response
