### ISSUE TITLE
Suggestion for calcuting workcourses on non-Standart field

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#1844]
Hey,
So as you all might know, CP has a problem with non-standardized fields, ie. fields that are not rectangular and/or orinented north-sout/east-west...
I'd suggest, to include a button in the coursegenerator, to choose wheter to use the standart calculation, or if the headlandcalcutions should be used for the rest of the field, because.
as of now, i never really had problems with those, even when calculating the max amount of headland at workwiths of about 48m... so i think, that having the possibility to use these calculations for the lines across the fields might be what me and a lot of other players need.
This would make it much better to play on nice maps, which have those kind of fields...

Greets JD_Tiger

**Comment by pvajko** [comment]
You may want to take a look at #1793 and https://github.com/pvajko/course-generator

**Comment by JDTiger** [comment]
Oh, nice, didn't saw that earlyer... quite a nice idea... I'll close this suggestion, seems like we already have a solution :P
