### ISSUE TITLE
Bunkerfillup mode problem after update 1.4 and higher

### ISSUE THREAD

**Issue by evybart** [Courseplay/courseplay#1852]
After i update to 1.4 the Fillupmode dont work so good anymore .the tractor with Holaras Blade must run now 10 of 15 time for 1 trailer load of chaff in 1.3.1  5 of 6 times and everthing was Pullt up maybe any one new What the do sorry for the english . First i set the 1.3.1 back and everthing was back fine.  
Thanks for the great job whitout cp no fs  
V5.01.94 version of cp 
Fs 17 version 1.4.4

**Comment by evybart** [comment]
IT likes that the Blade dont push to the ground when the tractor hits the pile with chaff and drives over the pile and nothing pusht forward for the first coupple off times you can now use one driver for transporting chaff to the bunkersilo  before 2 off 3 and the Pusher was always ready with is work thanks for this great work grtz

**Comment by ThomasGaertner** [comment]
try 104 or higher and report

**Comment by evybart** [comment]
sorry bud the update works not good the driver drives now out off the silo when he is on the top of chaff  and is slower then before and when unload backwards he drives anymore into the silo bud unload almost out off the silo the only thing that wass changed with the patch between 1.3.1 and 1.4 is that the filling  tractor now takes 750l to 2500l chaff end before between 2000 and 5000 l and more chaff every time he droves into the silo filling the silo i use only the filling mode  thanks for the great work that the team do fore us the players

**Comment by evybart** [comment]
i tried the update bud have now back 1.101

**Comment by evybart** [comment]
I have now tried the latest update and everthing is ok now and works smooth one little thing maybe the fill tractor fills the bunker not 100 % more Bud a minor problem for me thanks Guys for the great job can closed this item
