### ISSUE TITLE
Vehicles not responding after CP

### ISSUE THREAD

**Issue by Ntone107** [Courseplay/courseplay#1853]
All my tractors doing transport use CP
All my combines use a hired worker.

I noticed several times that a transport-tractor on CP was stuck behind a combine. Disengaging CP I try to manoeuvre them underneath the discharge auger.  After disengaging CP I try to manually drive the tractors, but they do not respond. Engaging and disengaging again while pushing the forward-button (z) results in movement after about 5 seconds.

FS2017 V1.3.1
CP V5.01.00093

**Comment by pops64** [comment]
Log? Your game should be updated to v1.4.4 or above as the current version of cp has code that doesn't support previous versions of FS

**Comment by Ntone107** [comment]
Oh ok, let me first take care of that!

**Comment by pops64** [comment]
Did this fix your problem or are still having issues?

**Comment by Ntone107** [comment]
Didn't have the time to check, downloading patch 1.4.4 now and giving it a go!

**Comment by Ntone107** [comment]
Problem solved!
