### ISSUE TITLE
Mode1 Silo Fuel Save Bug

### ISSUE THREAD

**Issue by RedOhne** [Courseplay/courseplay#1856]
Hi,

I tried to use the new run counter to transport wheat to the selling point on the "The Old Stream Farm v2". I used a course, which I created some days ago. Without run counter it was fine. 

The new situation is, that the tractor drives to waypoint 1 and the trailer is filled. The front of the tractor is a little bit in front of waypoint one at this point in time. Once the trailer is full the tractor is not going for waypoint 2 but tries to reach waypoint 1 again. This means: The tractor crashes into the silo. 

When I'm able to make some screenshots today I will post them here, to. Do you need any debugging on any level? 

This new feature is really great since no waitpoints are needed any longer for the selling routes. 

Thanks Tim

**Comment by RedOhne** [comment]
I forgot the version infos: 
CP: 01.0094
LS: 1.4.4.

**Comment by dkfiremann** [comment]
Can you show a picture of what you are seeing? 

Normally I let the truck/tractor start a little before the start point, and set the mode to Start at first point.

**Comment by RedOhne** [comment]
I will post a picture tomorrow. I think I will not be able to check ingame today.

**Comment by RedOhne** [comment]
Hit the wrong button ;-).

**Comment by pops64** [comment]
Lets just start with a regular log and some pictures.

**Comment by pops64** [comment]
I was able to produce this once with the fill level percent being greater than the drive on. Then this error occurred after the timer ran out. Will try to reproduce

**Comment by RedOhne** [comment]
Do you need some more information like logs or screenshots, or will you be able to work on a fix with the infos pops64 found out. I can send some in the late afternoon.

**Comment by RedOhne** [comment]
I tried to reproduce the error, but wasn't able with the latest version (01.0095) maybe because there was not enough grain in the silo, or any other circumstances. Or was it fixed already?

**Comment by pops64** [comment]
Wait until the engine has shut off automatically and then hit the drive now button and this error will occur.

**Comment by ThomasGaertner** [comment]
please try v .0097 or higher and try whether it occurs again...

**Comment by Raints** [comment]
I know its a wrong issue but in mode 6 forage harvester should not stop the engine all the time during work. Its fine in end point. 
After all, CP is a mod for simulator game, so in my opinion there is no way in real life you stop the engine so often. This is just my opinion. If there was a option to choose fuel save on/off then it should stay.

**Comment by RedOhne** [comment]
Hi,

I run a test, and it seems, that it's working fine now. The tractor is approaching waypoint 2. Also when the engine was shutdown.

Thanks for this quick fix.

Red

**Comment by pops64** [comment]
Closed to keep the issues area clean. Thanks for the replie
