### ISSUE TITLE
Overloader not unloading into trailer

### ISSUE THREAD

**Issue by maznio** [Courseplay/courseplay#1858]
Having a problem with my grain cart not unloading onto a trailer when it gets to it. And yes I do have CP set to overloader mode when I record the course

**Comment by DynamicXYZ** [comment]
1. You have to be using an Auger wagon
2. You have to place a wait point beside the trailer you want to load to
3. Make sure the position of the arm of the Auger wagon is set

**Comment by maznio** [comment]
This is not my first time using courseplay but I did just get it for fs17. I am using an auger wagon (grain cart), I did set a wait point, and I had the pipe position set and still nothing. Wouldn't work with a modded auger wagon or an in game auger wagon. I am on a modded map though and I do have a manual unload mod although I did try it without the manual unload mod. 

Zach

**Comment by pops64** [comment]
#1797 Closed to keep issues are clean. Please post a viedo and log with 15 and 21 active in that issue. Thanks
