### ISSUE TITLE
sell guelle and digestate in mode8?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#1861]
Hello
i tried to sell guelle and digestate, with mode8 in sosnovka (modmap)
in the map02.xml i addet liquid manure and digestate:
```

        <tipTrigger index="GARDENCENTER" stationName="station_gardenCenter" appearsOnPDA="true" isAreaTrigger="true" isSellingPoint="true" triggerWidth="6" litersForFullPriceDrop="2000000" fullPriceRecoverHours="48">
            <fillType name="woodChips" 		priceScale="3.51" 	supportsGreatDemand="true" 		disablePriceDrop="false" />
            <fillType name="liquidManure" 	priceScale="1.45" 	supportsGreatDemand="false" 	disablePriceDrop="false" />
            <fillType name="manure"       	priceScale="1.47" 	supportsGreatDemand="false" 	disablePriceDrop="false" />
            <fillType name="digestate" 		priceScale="1.49" 	supportsGreatDemand="false" 	disablePriceDrop="false" />
			</tipTrigger>

```

and then i generatet a course, start and stop on the guelle-station and a stop point in the trigger,
when i now use the course in mode 8, the guelle was filled in startpoint by cp automatically, then the driver drive to the sellpoint and stop on the stoppoint but dont sell the guelle.
only i dismissed the cp-driver i cansell the guelle, when he is empty i hired the driver,...
what must the sell point have for spezifications?
can i addet this,or what must i chanced on the sellpoint?
here is apic from the sellpoint in GE:
![trigger](https://cloud.githubusercontent.com/assets/24860501/23679271/b41cf8e0-0387-11e7-9a54-3fd15e2cce1d.jpg)

lg
andreas

**Comment by pizman** [comment]
Hi.   Maby this is the same basic problem like in my situation....
[https://github.com/Courseplay/courseplay/issues/1837](url)

**Comment by pops64** [comment]
Say guelle instead of liquid manaure or slurry through me off. #1760 Closed to Keep the issues area clean. @pizman it is the same problem yours is a mod related trigger. This issue is because in 15 slurry didn't have a sell trigger so there was no need to CP to support it.
