### ISSUE TITLE
Pflügen und Dreiecke

### ISSUE THREAD

**Issue by VENAAAA** [Courseplay/courseplay#1864]
Ich würde nicht bitte tun Sie etwas, dass sie nicht diese Dreiecke ?
sry, translator
<a href="http://www.jpeg.cz/obrazek/g6IH">JPG<img src="http://www.jpeg.cz/images/2017/03/08/tLaF.png" border="0" /></a>

**Comment by pops64** [comment]
This has been suggested to fix. #1461 Only problem with bigger ploughs like this is it would take up a lot more room to turn. No need to translate to german. Closed to keep the issues are clean
