### ISSUE TITLE
Bale Collection

### ISSUE THREAD

**Issue by Zoochase** [Courseplay/courseplay#1871]
This is a "Question/Suggestion".
When I collect bales, I have a course set up to back the bale collector into a area.  When I get close to the stack, I stop CP, tilt the collector, back up and unload.  I then resume collection.  Is it possible for CP to detect the bale stacks, stop, tilt, drop and resume automatically?  Thanks for your time.  Zoo.
![fsscreen_2017_03_08_22_01_02](https://cloud.githubusercontent.com/assets/25461823/23738119/ff320fb8-044b-11e7-94dd-653a25340100.png)

**Comment by krambc** [comment]
This would be awesome

**Comment by Satissis** [comment]
This is already in our todo list ;) but will first be looked at after the release.

I'll close here again to try keep the issues clean ;)
