### ISSUE TITLE
Engine shuts off during mode 10 levelleing and compacting

### ISSUE THREAD

**Issue by Symbob** [Courseplay/courseplay#1874]
While levelling and compacting, the engine of the levelling tractor shuts off after doing one pass of the bunker.  The tractor continues to work properly and continues levelling and compacting but the engine is silent.  Using v5.01.00096

*EDIT*
In fact it's causing more problems than I first thought.  When a trailer is waiting to tip, the levelling tractor's engine will restart when it makes it's way to the waiting point.  The trailer will start to unload and while the leveller is waiting the engine shuts off again.  After the trailer has tipped and driven away the leveller engine starts again but instead of the tractor reversing to the course end point ready to start levelling it attempts to drive forward and turn around, usually resulting in it crashing in to obstacles and buildings.

I'm assuming this is as a result of the fuel save feature.  Is that feature really necessary as it appears it could be the cause of a few bugs.

**Comment by ThomasGaertner** [comment]
try v 0097 or higher and report...

**Comment by Symbob** [comment]
Thank you.  That's fixed the problem.
