### ISSUE TITLE
Turning on fieldwork when using loaded course as field edge

### ISSUE THREAD

**Issue by blaz62746** [Courseplay/courseplay#1880]
I have problem when generating a course and then starting course in fieldwork mode. First 3 picture are made with debugging modes 12 and 14 and this is with currently loaded course as field edge.
![farmingsimulator2017game 2017-03-12 20-09-05-71](https://cloud.githubusercontent.com/assets/26365587/23835025/4780ba82-0760-11e7-80d2-0870ce890213.jpg)
![farmingsimulator2017game 2017-03-12 20-09-46-12](https://cloud.githubusercontent.com/assets/26365587/23835026/4781fbe0-0760-11e7-8ca1-7039adc8a8f8.jpg)
![farmingsimulator2017game 2017-03-12 20-09-53-10](https://cloud.githubusercontent.com/assets/26365587/23835027/47837cb8-0760-11e7-8987-059b590924a4.jpg)

This is the same but using field edge as calculated by Courseplay. All settings are the same.
![farmingsimulator2017game 2017-03-12 20-10-32-33](https://cloud.githubusercontent.com/assets/26365587/23835035/6fd983a6-0760-11e7-9c02-75542766b6ad.jpg)

**Comment by pops64** [comment]
Do you have the log associated with these pictures?

**Comment by blaz62746** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/836934/log.txt)
I hope this will help.

**Comment by blaz62746** [comment]
I think that one of the previous versions didn't have that problem.

**Comment by pops64** [comment]
This isn't like the other turn issue. If you look through the log. CP thinks that the next lane is only 90° turn.

**Comment by Satissis** [comment]
I cant really reproduce this, which means I would need more info on how to reproduce it.
Also, is that loaded course one that have been run through pvajko's course-generator to recalculate the field with lanes? If you don't know what that is, then that's fine an just mean that it's not an issue from there.

**Comment by pops64** [comment]
Could we get a link to your mod map? As well has download for your save game and CP courses

**Comment by blaz62746** [comment]
Here it is. Link for map:
https://www.modhoster.com/mods/los-grandes-terrenos-2017
And I don't know why but I can't upload zip with savegame and courses. I put it in zip file but it says "we don't support that file type".

**Comment by blaz62746** [comment]
I tried the latest version of courseplay and all works as I want now. So you can remove this from the list of issues.

**Comment by pvajko** [comment]
Thanks.
