### ISSUE TITLE
Waiting Points

### ISSUE THREAD

**Issue by hoefti10** [Courseplay/courseplay#1881]
Hello,
anyone else has a problem with the Waiting Points by unloading the Harvester? The Departue hold everytime in the Cereals area.
![20170312210554_1](https://cloud.githubusercontent.com/assets/25055083/23835473/2f4b294a-0768-11e7-85f7-15ce7ede5d9d.jpg)

And when he drives not in the Cerals Area he drives funny ways and stop everwhere
![20170312211345_1](https://cloud.githubusercontent.com/assets/25055083/23835515/fcf983dc-0768-11e7-8219-dd7549d78358.jpg)
 In the past i have never problems with this mode, it is since the last 2 Versions.

FS : 1.4.4
CP .097
BTW:
Sometimes is this happened
![20170312213216_1](https://cloud.githubusercontent.com/assets/25055083/23835650/7565455c-076b-11e7-91aa-4e3b30a072f3.jpg)

**Comment by pops64** [comment]
Please post a log with just debug channel 4 active. Also turn on F5 and see if there are any collosion boxes that the unloading tipper may be running into. E.X
![farmingsimulator2017 64bit 3_12_2017 9_05_06 pm](https://cloud.githubusercontent.com/assets/10678220/23838049/c54b2aa4-0767-11e7-82a8-cdfcab54e007.png)

The ones on the right always cause me problems with this field

**Comment by nyfarmboy07** [comment]
This also happens when harvesting potatoes I've found.  The tipper will turn into the fruit just enough so the harvester will have to stop when on the next pass.

**Comment by pops64** [comment]
Closed due to no response.
