### ISSUE TITLE
Unloading point problem with self unloading marker and wheelloader problem 

### ISSUE THREAD

**Issue by evybart** [Courseplay/courseplay#1882]
I make a course with the fendt 900 tractor and the Krone silage trailer for unloading silage in the bga with the belt system the tractor i make the course with self unloading point symbol works wonderfull then i give also just the same tractor and trailer the same course that i saved and Bud these unload not at the unloading point Bud drives further backwards And also when the wheelloader loads trailers he dont wait annymore when the are not at the waiting point trailers for loading grtz

**Comment by pops64** [comment]
Well. With regards to your first issue waypoints(this includes unloadpoints) are generate at the center of the tractor. When CP runs uses different points of the tractor depending on what it is doing then the center so it is always best practice when setting up routes to set them up and run them to see how they behave. So for unloading to belts remember that in reverse it uses the back end of the trailer to stop so setup your course first then adjust your belts to where CP unloads. Or rerecord and just go further back with the unload point. 

In regards to your second suggestion. Are your saved movements maxed out? As you can't travel any further with the bucket? See #1679 for a better explanation.

**Comment by evybart** [comment]
For the second i use this course already Three Months and never didend does this and use unloading ramp because i now the problem with the maxed out problems for the first i gonna try record the course again ant try grtz

**Comment by pops64** [comment]
Could we get a log with debug 10 on and a picture or video. Also could we get your save game and CP courses as well? Thanks

**Comment by evybart** [comment]
The course with the trailers works perfect now when i start to play today and with different trailers and tractors and i think with the wheelloader the ramp is too far from the trailer and shoot over the ramp thanks already for the support grtz

**Comment by pops64** [comment]
I will go ahead close this then. Thanks for the response
