### ISSUE TITLE
Overloader blocks combine during turn on headland

### ISSUE THREAD

**Issue by nyfarmboy07** [Courseplay/courseplay#1883]
Originally I was having issues with the overloader not unloading the combine, but this was caused by a traffic collision issue with a modded grain cart.  This test was done with vanilla equipment on GCV.  I run counterclockwise so the overloader and combine will not get stuck on trees or obstacles while attempting to unload.  Basically what happens is when the overloader reaches the combine it will attempt to go straight and the combine will be turning left.  With forage harvesting its not an issue after the initial first pass because then the tipper will move to the outside of the forager and turn as the forage turns.   

5.01.00090

[combine bug report-master.zip](https://github.com/Courseplay/courseplay/files/837229/combine.bug.report-master.zip)

**Comment by pops64** [comment]
Could we get a picture or video of what is occurring? And only debug channel 4 active. Thanks

**Comment by nyfarmboy07** [comment]
Just an update, I havent forgotten about this post.  Im working on a video, hopefully will be uploaded in the next couple of days.

**Comment by nyfarmboy07** [comment]
https://youtu.be/cDfsqkigy5E

This is the best I can do to show the issue.  It normally will only happen on the headlands.  In the video, the overloader does move out of the way, but this happens to be at the exact time when the combine finishes unloading.  Normally, the combine will try to push the overloader out of the way, and I have to stop both machines, move the auger wagon, and then continue both courses.  

In the same video, during headlands the overloader will not start until the combine is completely full in automatic search, yet will for manual.  Once the headlands are complete, everything appears to work as normal. 
My apologies for such a delay, but it appears if you are recording, CP players behave themselves.

**Comment by dkfiremann** [comment]
> In the same video, during headlands the overloader will not start until the combine is completely full in automatic search, yet will for manual. Once the headlands are complete, everything appears to work as normal.


That is because the Combines pipe is over crops when you drive the headland. 
When you have Pathfinding activated for the tractor, then the tractor will only empty the combine on 2 options._

1. If the pipe is over crops, then the combine needs to be 100% full. 
2. Once the pipe is no longer over crops, and the combine has reached to Drive on procent. 

If you change your headland direction to be Clockwise then you will have a lot less problems, as the tractor will be on the outside of the combine, and the pipe will not be over the crops.

**Comment by pops64** [comment]
Yea I would never have the tipper on the inside of the turn while unloading has this can cause problems which I am not sure CP could ever handle with out a lot reworking of mode2

**Comment by gec100** [comment]
as a added help to always set the combine headland to be Clockwise, maybe combine could be set to stop while unloading when it comes to turn that that goes to the side where the pipe is (left side for combines and, pipe side dependent on forage harvesters)

**Comment by nyfarmboy07** [comment]
The problem with clockwise is the auger will swing out and contact trees.  I think I have found a good solution to harvesting.  
1. Set up the field with a headland.
2. Use combine self unload into trailer
3. Make overloader course to keep out of the path of self unloading combine and set drive on percent so the overloader usually reaches the combines before they reach 100%.  

I will try to capure a video of this process.

Thank you for the assistance.

**Comment by pops64** [comment]
There is an option to stop the combine when unloading. So if you don't have an option of keeping the tipper out of the way I would recommend this.

**Comment by pops64** [comment]
Closed to keep issuses area clean
