### ISSUE TITLE
Ai Vehicle Extension combine and cp tipper lua error.

### ISSUE THREAD

**Issue by turbostar190** [Courseplay/courseplay#1885]
Hello,
Every time I hire combine with AI Vehicle Extension and I set CoursePlay on tractor with tippers on mode 2 when the combine reach the end of the field and tractor is following the combine, the game freeze as long as I write cpStopAll in console and all vehicles slide on terrain.

![fsscreen_2017_03_13_19_59_27](https://cloud.githubusercontent.com/assets/24813315/23871403/7dc1d80e-082a-11e7-83a6-7f157fac11f6.png)

[https://gist.github.com/turbostar190/d04b1d6e70aa74e823ebfac58ef972ab](url)

**Comment by pops64** [comment]
#1701 Closed to keep the issues area clean.
