### ISSUE TITLE
Mex5 Issues with following tipper(Fuel Save & Reverse driving)

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1886]
So I have two bugs associated with the above equipment. When in fuel save mode occasionaly the following tipper does not restart to get out of the way of the currently unloading tipper ex
![farmingsimulator2017 64bit 3_13_2017 5_36_51 pm](https://cloud.githubusercontent.com/assets/10678220/23876398/b133a738-0813-11e7-8faa-64ba716fa14b.png)

Also associated with reverse driving support in regards to this equipment the tipper that is currently unloading the mex5 does not turn around properly and runs into the mex 5. [Video](https://www.dropbox.com/s/pbo3z4dnqyro35y/FarmingSimulator2017%2064bit%203_13_2017%205_43_40%20PM.mp4?dl=0) 
![farmingsimulator2017 64bit 3_13_2017 5_44_42 pm](https://cloud.githubusercontent.com/assets/10678220/23876631/ccf9159c-0814-11e7-8223-cc8405f33662.png)

[Log](https://www.dropbox.com/s/w91cdm4rkdc1h64/log.txt?dl=0)

**Comment by ThomasGaertner** [comment]
try 0127 or higher and report

**Comment by pops64** [comment]
It works great. Some how the drive behind combine and drive to next combine disagree on which side to do it

**Comment by Blackmankot** [comment]
@pops64 In the latest versions of the course, I did not get into such a problem. I suggest also close it for cleaning.

**Comment by pops64** [comment]
Closed #2909
