### ISSUE TITLE
Salford 8312 Incorrect Turing Radius and Front and Back Markers

### ISSUE THREAD

**Issue by Evilmutt** [Courseplay/courseplay#1888]
Hi, I did email Satis about this issue and he says I could be using an Outdated beta of courseplay as this Issue is supposedly Fixed. Okay I Have to admit that I have been getting my courseplay directly from the Clone or Download Button which then downloads courseplay-master, I then unzip and then re-zip just the files as instructed into a New ZZZ_courseplay.zip file. now I had to ask someone (my cousin actually) about where to find the Log. He directed me to the log.TXT in the Farming Simulator 17 folder in "My Games" and in the log I have this version Number of Courseplay  "Load mod: ZZZ_courseplay (Version: 5.01.00094)". (Now it Does tell me that I am using the developer version of it and they are not responsible for Baby pandas getting killed) DO I have a right version number or can someone direct me to the Proper (non Beta/Non Developer) File that I am supposed to download. Please, as this is Bugging me to hell and Back

**Comment by pops64** [comment]
http://courseplay.github.io/courseplay/en/installation/index.html for install and https://github.com/Courseplay/courseplay/wiki for bug reports because we can't fix what we don't know about

**Comment by Evilmutt** [comment]
Thanks for getting back to me on this Pops I have had this Constant Urge to not quit my game in frustration at times due to this Plough not working. I found this on both the Vanilla Map (with No Mods Other than courseplay active) and Pine Cove Farm Map By Stevie, I was Using the Default Lemkin Titan 11 AND the Salford 8312, BOth coupled behind a Challenger MT900E. The Tractor will get to the end of the First row, Then start its turn and Then Just continue to go round and round in circles as if doing Donuts. Thanks for your time gentlemen and thanks for a Wonderful Mod (although currently Frustrating :S)
I have Made a Gist of the log file and here is the Link https://gist.github.com/Evilmutt/b5f4a33bd28726f715c96c1d3f5d185a I Hope you can tell me how to get this right as I have seen some
[log.txt](https://github.com/Courseplay/courseplay/files/842821/log.txt)

**Comment by pops64** [comment]
What is your turning circle set at? Is it on auto your have you changed this value?. If we could get a picture and log with debug channel 12 and 14 active of the failed turn maneuver this would help. Thanks

**Comment by Evilmutt** [comment]
Thank You Pops, This greatly reduces my stress levels, Now I Just need to get it to where it is not leaving the V shapes at the beginning and ending of the Row and Just play a little with the offset that I found was leaving a row out when it makes some turns on the Salford. Please see enclosed Pics as it leaves behind Half the field on F19 of Sosnovka which I was doing as a Test
![2017-03-14 1](https://cloud.githubusercontent.com/assets/26417002/23926824/63eee1bc-090e-11e7-8488-0536442e367d.png)
![2017-03-14 2](https://cloud.githubusercontent.com/assets/26417002/23926825/63f06f82-090e-11e7-84ef-17f8d7469684.png)
![2017-03-14](https://cloud.githubusercontent.com/assets/26417002/23926826/63fb0dca-090e-11e7-8076-e94150e7e2d0.png)

**Comment by pops64** [comment]
This will also be fixed. If you see the horizontal red lines in my picture. This shows where the salford 8312 thinks the edges of the plough are. For some reason these changed in 1.4. Also if you update to version 96 or above there is a feature that allows you to remove this V from all ploughs(Expect the salford 8312 atm)

**Comment by pops64** [comment]
Please test again with v01.0098 or above and report back. Thanks

**Comment by Evilmutt** [comment]
I will do this first thing in the morning when I get on. I shall Update now and test in the morning. Many thanks Pops and Satis

**Comment by Evilmutt** [comment]
Courseplay Now correctly Identifying edge of field and Not Missing Rows with Salford. I had to manually turn turn radius down to 14 to Evade trees on Sosnovka due to Auto 18m But this I feel is More than Amazingly done. Thank You gentlemen
![2017-03-18](https://cloud.githubusercontent.com/assets/26417002/24072148/1808af8e-0bda-11e7-8723-30a865345b3d.png)
