### ISSUE TITLE
 Problems with Harvesting

### ISSUE THREAD

**Issue by NarvenEugen** [Courseplay/courseplay#1890]
There is a problem from the version to the version. When you start the harvester at the rate of harvesting, he goes to the starting point, which is on the field. At the same time, it combines it with the center of the combine itself and only then starts the car and starts harvesting. But since the combine is a big machine, before he starts harvesting, he tramples the crops a little while he goes to the starting point. Can you take out a little starting point for the field or combine it not with the center of the machine, but with the beginning or center of the front equipment (header)?

**Comment by dkfiremann** [comment]
I normally just start the combine my self before I start ask it to start the course. 
Then it will harvest that little part before the starting point.

**Comment by NarvenEugen** [comment]
Yes, I do it too. But I would like a full machine. Not always courses start with the angle of the field

**Comment by pops64** [comment]
What has already been suggested or #1772

**Comment by lcc1211** [comment]
@dkfiremann is correct about that.  If you start the course without having the header already down and powered, it will miss the first few meters of the fruit.  Would it not be a good idea to have the harvest either immediately power & lower the header before moving into the fruit, or have the harvester stop just shy of the field and do it?

**Comment by huseyinsayar** [comment]
For example;
With the TransferMode you will follow the Home-Tarla1 route;
Completion of Harvest with FieldWorkMod
Transfermode will follow Tarla1-Home route
A planning would be perfect.

**Comment by pops64** [comment]
Closed to clean up issuea area

**Comment by lcc1211** [comment]
I don't feel like the issue raised by @dkfiremann and myself was addressed.  We both stated how you have to already have the combine header powered and activated for the combine would move several meters into the field.  Most importantly, though, the issue was not resolved for @NarvenEugen who opened it originally.  You asked if it was like the issue raised in #1772, but it isn't.  Please reopen and assign to someone to see if they can fix.

**Comment by pops64** [comment]
@lcc1211 Sorry for the delayed response. I some how didn't get notified that there was a reply. I closed it because of the inactivity. And at the very least this is a suggestion or enhancement not a bug. We will look into further but that will far into the future.
