### ISSUE TITLE
Error Issue Fields.lua:619: bad argument #1 to 'ipairs' (table expected, got nil)

### ISSUE THREAD

**Issue by Rbk3** [Courseplay/courseplay#1891]
I am getting the following Error on my Saved Game. However, if I start a new saved game on the same map, the error doesn't occur. I tried deleting my saved courses and the 2 courseplay files in my saved game but it did not solve the issue. Thanks

Error: Running LUA method 'update'.
C:/Users/Brad/Documents/My Games/FarmingSimulator2017/mods/zzz_Courseplay/fields.lua:619: bad argument #1 to 'ipairs' (table expected, got nil)

Error: Running LUA method 'update'.
C:/Users/Brad/Documents/My Games/FarmingSimulator2017/mods/zzz_Courseplay/fields.lua:619: bad argument #1 to 'ipairs' (table expected, got nil)

**Comment by pops64** [comment]
Full log? Are you running the most up to date CP and game? This is most likely a mod conflict which should have been resolved. If you are running the most up to date CP and game try renaming your CP folder to ZZZ_Courseplay

**Comment by mngrazy** [comment]
this problem is when you using the Bank of Hagenstedt Mod from MX11

http://farming-simulator.com/mod.php?lang=de&country=de&mod_id=68500&title=fs2017

i write this in giants forum...
https://forum.giants-software.com/viewtopic.php?f=884&t=96716&start=300#p850928

best regards grazy

**Comment by Satissis** [comment]
Can we close here then ? since this related to Bank of Hagenstedt mod

**Comment by Rbk3** [comment]
Yeah good to close on my end

**Comment by Satissis** [comment]
@mngrazy I did read the topic you posted on Giants forum and the respond he did.
I don't know it Jakob or Thomas have spoken with him about it to make an fix for CP, but I never heard of it.

Anyway try out v01.00099 and see if that fixes it.

**Comment by mngrazy** [comment]
working fine with your fix Satis , THANK YOU 

now can here closed again ;)
