### ISSUE TITLE
start_stop fuel save function

### ISSUE THREAD

**Issue by ontot** [Courseplay/courseplay#1892]
Good evening to all. I would like to know if I can disable the new application of the start-stop for fuel save function. If it is possible I would like to know how to turn it off. Infite thanks to everyone for their kind answer

**Comment by Lupo36** [comment]
I would also like to know.

**Comment by Satissis** [comment]
No not yet, but it is planed to be implemented.

**Comment by ontot** [comment]
good... thank you so much, satissis!...
