### ISSUE TITLE
Curseplay and Drive control

### ISSUE THREAD

**Issue by NarvenEugen** [Courseplay/courseplay#1893]
I noticed such a thing that if the driver of the tractor, for example, when plowing starts to slip (option always use 4x4 included), then the driver does not include the differential lock provided by Drive control, as it was in the version of the farming simulator 2015. And if the locking differentials include the Then start the driver, then he turns them off himself. It would be convenient for the driver himself to include blocking of differentials or at least not to disconnect them

**Comment by Satissis** [comment]
Added as an suggestion for now as we are busy working on other stuff (The list is long)

**Comment by NarvenEugen** [comment]
Thank you

**Comment by pops64** [comment]
I looked through the code and if the red slipping messeage(The second one slipping message) Then the difflocks should engage if present. Please post a log with debug channel 14 active. Thanks

**Comment by Satissis** [comment]
We had an talk about this one a day or 2 ago, and the diff lock is already implemented.
It's automatic thou and works like this:
If 4wd is turned on and the tractor is slipping for 6 sec, it will turn the difflock on as well and turn it off again once it's not slipping again for a time.

Can we close here again then ?

**Comment by genen** [comment]
I don't understand why can't you leave the dif lock on if it is triggered by slippage... I am constantly having to hit ctr  7, turn on all 3 locks, manually hit gas, then hit ctr 7 again... this happens 10-20 times per play period as tractors have some wheels with less traction on turns. Literally, all it would take to prevent having to manually take control is for you to REMOVE some code (which turn the diff off again) so should be super simple.

**Comment by Satissis** [comment]
I don't use DC my self, since I want to test without too many mods on, but Thomas have been using DC since day 0 of that mod and he don't really have any problems with it.

What vehicle and tool setup are you using since you lose so much traction on turns ?

**Comment by genen** [comment]
Happens pretty regularly... I'll record a few instances in the video for you... Any map that is not flat will result in a tractor changing direction on a hill usually, the uphill wheels will spin slowing or stopping it. Usually the tractor pulling a tipper

**Comment by pops64** [comment]
They should be hitting 20% of the max work speed of the tool before they disengage.

**Comment by NarvenEugen** [comment]
I have not noticed this yet, but if it is implemented, then thanks a lot

**Comment by NarvenEugen** [comment]
Just checked. Does not include differential locks. Specially put the tractor on the pole and made it slip ... 20 seconds slipped and there was not even an attempt to engage the differential lock

**Comment by pops64** [comment]
Seems to work fine for me.

![farmingsimulator2017 64bit 4_1_2017 12_04_00 pm](https://cloud.githubusercontent.com/assets/10678220/24580281/5b776bd0-16d3-11e7-8f89-d157037b4412.png)

**Comment by genen** [comment]
https://youtu.be/TyhCmh6mJEk

**Comment by pops64** [comment]
Need a log. with just debug channel 14

**Comment by NarvenEugen** [comment]
I do not speak English, so you can tell me how to make the report I need?

**Comment by genen** [comment]
video at https://youtu.be/as1silhFHcs
log - Copy (2).txt
dataS2/character/pedestrians/woman06.i3d (52.60) ms
dataS2/character/pedestrians/man06.i3d (2.71) ms
dataS2/character/pedestrians/man01.i3d (2.50) ms
dataS2/character/pedestrians/man02.i3d (3.21) ms
[dbg14 lp29434] GTXM Big M (#1): curStage=2, refSpeed=10.00, curSpeed=2.33 -> setSlippingStage 1
[dbg14 lp29434] GTXM Big M (#1): setSlippingStage(..., 1)
[dbg14 lp29440] GTXM Big M (#1): setCustomTimer(..., "slippingStage2", 3)
[dbg14 lp29446] GTXM Big M (#1): curStage=1, refSpeed=10.00, curSpeed=2.55 -> resetCustomTimer(..., "slippingStage2")
[dbg14 lp29463] GTXM Big M (#1): setCustomTimer(..., "slippingStage2", 3)
[dbg14 lp29573] GTXM Big M (#1): timerIsThrough(..., "slippingStage2") -> setSlippingStage 2, reset timer
[dbg14 lp29573] GTXM Big M (#1): setSlippingStage(..., 2)
[dbg14 lp29598] GTXM Big M (#1): curStage=2, refSpeed=10.00, curSpeed=2.31 -> setSlippingStage 1
[dbg14 lp29598] GTXM Big M (#1): setSlippingStage(..., 1)
[dbg14 lp29605] GTXM Big M (#1): curStage=1, refSpeed=10.00, curSpeed=3.70 -> setSlippingStage 0
[dbg14 lp29605] GTXM Big M (#1): setSlippingStage(..., 0)
[dbg14 lp29654] GTXM Big M (#1): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp29745] GTXM Big M (#1): timerIsThrough(..., "slippingStage1") -> setSlippingStage 1, reset timer
[dbg14 lp29745] GTXM Big M (#1): setSlippingStage(..., 1)
[dbg14 lp29746] GTXM Big M (#1): setCustomTimer(..., "slippingStage2", 3)
[dbg14 lp29836] GTXM Big M (#1): timerIsThrough(..., "slippingStage2") -> setSlippingStage 2, reset timer
[dbg14 lp29836] GTXM Big M (#1): setSlippingStage(..., 2)
[dbg14 lp29852] GTXM Big M (#1): curStage=2, refSpeed=10.00, curSpeed=2.13 -> setSlippingStage 1
[dbg14 lp29852] GTXM Big M (#1): setSlippingStage(..., 1)
[dbg14 lp29860] GTXM Big M (#1): curStage=1, refSpeed=10.00, curSpeed=3.63 -> setSlippingStage 0
[dbg14 lp29860] GTXM Big M (#1): setSlippingStage(..., 0)
[dbg14 lp29928] Terra Variant 600 eco (#3): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp29939] Terra Variant 600 eco (#3): curStage=0, refSpeed=10.00, curSpeed=3.82 -> resetCustomTimer(..., "slippingStage1")
[dbg14 lp30165] TORUM 760 (#2): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp30216] GTXM Big M (#1): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp30248] TORUM 760 (#2): curStage=0, refSpeed=3.00, curSpeed=1.11 -> resetCustomTimer(..., "slippingStage1")
[dbg14 lp30306] GTXM Big M (#1): timerIsThrough(..., "slippingStage1") -> setSlippingStage 1, reset timer
[dbg14 lp30306] GTXM Big M (#1): setSlippingStage(..., 1)
[dbg14 lp30307] GTXM Big M (#1): setCustomTimer(..., "slippingStage2", 3)
[dbg14 lp30373] TORUM 760 (#2): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp30386] TORUM 760 (#2): curStage=0, refSpeed=10.00, curSpeed=3.60 -> resetCustomTimer(..., "slippingStage1")
[dbg14 lp30397] GTXM Big M (#1): timerIsThrough(..., "slippingStage2") -> setSlippingStage 2, reset timer
[dbg14 lp30397] GTXM Big M (#1): setSlippingStage(..., 2)
[dbg14 lp31041] GTXM Big M (#1): curStage=2, refSpeed=10.00, curSpeed=3.36 -> setSlippingStage 1
[dbg14 lp31041] GTXM Big M (#1): setSlippingStage(..., 1)
[dbg14 lp31042] GTXM Big M (#1): curStage=1, refSpeed=10.00, curSpeed=4.40 -> setSlippingStage 0
[dbg14 lp31042] GTXM Big M (#1): setSlippingStage(..., 0)
[dbg14 lp31121] GTXM Big M (#1): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp31211] GTXM Big M (#1): timerIsThrough(..., "slippingStage1") -> setSlippingStage 1, reset timer
[dbg14 lp31211] GTXM Big M (#1): setSlippingStage(..., 1)
[dbg14 lp31212] GTXM Big M (#1): setCustomTimer(..., "slippingStage2", 3)
[dbg14 lp31316] GTXM Big M (#1): timerIsThrough(..., "slippingStage2") -> setSlippingStage 2, reset timer
[dbg14 lp31316] GTXM Big M (#1): setSlippingStage(..., 2)
[dbg14 lp32960] Terra Variant 600 eco (#3): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp33054] Terra Variant 600 eco (#3): timerIsThrough(..., "slippingStage1") -> setSlippingStage 1, reset timer
[dbg14 lp33054] Terra Variant 600 eco (#3): setSlippingStage(..., 1)
[dbg14 lp33054] Terra Variant 600 eco (#3): set fourWheel to true
[dbg14 lp33055] Terra Variant 600 eco (#3): setCustomTimer(..., "slippingStage2", 3)
[dbg14 lp33066] Terra Variant 600 eco (#3): curStage=1, refSpeed=29.00, curSpeed=6.18 -> resetCustomTimer(..., "slippingStage2")
[dbg14 lp33071] Terra Variant 600 eco (#3): curStage=1, refSpeed=29.00, curSpeed=10.56 -> setSlippingStage 0
[dbg14 lp33071] Terra Variant 600 eco (#3): setSlippingStage(..., 0)
[dbg14 lp33165] GTXM Big M (#1): setSlippingStage(..., 0)
[dbg14 lp33204] Terra Variant 600 eco (#3): set fourWheel to false
[dbg14 lp33347] Terra Variant 600 eco (#3): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp33366] Terra Variant 600 eco (#3): curStage=0, refSpeed=24.00, curSpeed=8.52 -> resetCustomTimer(..., "slippingStage1")
dataS2/character/pedestrians/woman04.i3d (3.33) ms
[dbg14 lp33416] GTXM Big M (#1): set diffLockFront to false
[dbg14 lp33416] GTXM Big M (#1): set diffLockBack to false
[dbg14 lp34163] GTXM Big M (#1): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp34193] GTXM Big M (#1): curStage=0, refSpeed=20.00, curSpeed=7.05 -> resetCustomTimer(..., "slippingStage1")

**Comment by genen** [comment]
My easy fix suggestion is to get rid of the timer 2, and and just leave all diffs locked if it EVER slips...

**Comment by pops64** [comment]
No that would not do a single thing because looking through you log for what ever reason CP is not engaging drive control with GTXM Big M. If you didn't have the fuel flow mod enabled you would see CP not engaging drivecontrol for this mod vehicle.

**Comment by NarvenEugen** [comment]
In beta version 5.01.00115 the problem is gone

**Comment by genen** [comment]
Watch the video... dif locks were NOT engaged untill I stopped CP manually enables and then could drive.

I'll try v 4.01.00115 and let you know

**Comment by pops64** [comment]
Try disabling mods as this is probably a mod conflict with something else. Start with anything that mods the speed values of your vehicle. As I saw a non standard speed display in your video. Because  it works when only CP + drive control and your mod vehicle are involved.

**Comment by pops64** [comment]
I will close tthis out since I can not reproduce this and in my tests works. Post here if you have steps on how to produce this.
