### ISSUE TITLE
[Suggestion] More/better headlands

### ISSUE THREAD

**Issue by Kattebakke** [Courseplay/courseplay#1894]
I have a suggestion; More than 6 avalible headlands. 6 headlands is not enough if you're using a tool that is only 2-3 meters wide (Poettinger Mex, ploughs, smaller seeders, mover/pickup wagon combo) because that can give you a maximum headland of 15-18 meters. A tractor/trailer combo driving next to a forager takes over 40 meter to turn around with CP and often exits the field, getting into traffic or getting stuck in strees and rivers

How about an option on doing the whole field in a spiral? Making the vehicle drive round and round towards the middle?

And it is possible to make the 'unworked' space in headlands smaller? The cutting corners leave a lot of crop or field untouched

**Comment by pops64** [comment]
This has been discussed multiple times #1427 #1522 #844 #1547 and it is on our very very long todo list to get after the release of CP.

**Comment by pvajko** [comment]
In the meanwhile you can check out https://github.com/pvajko/course-generator, it has no limitation on the number headland tracks, makes probably smoother corners and can overlap headlands.
