### ISSUE TITLE
Mode 1 detects front loader bucket as tiptrigger

### ISSUE THREAD

**Issue by vixky** [Courseplay/courseplay#1896]
Description as title.

![vlcsnap-2017-03-17-00h32m17s996](https://cloud.githubusercontent.com/assets/25203532/24024217/88646688-0aa9-11e7-93c8-ef11edac6835.png)

![vlcsnap-2017-03-17-00h33m42s365](https://cloud.githubusercontent.com/assets/25203532/24024219/8afea4c6-0aa9-11e7-991f-0c10fde53a1e.png)

webm@
[https://webmshare.com/0rDKj](https://webmshare.com/0rDKj)

have fun with that one, took me ages to figure out what the @#!? was going on.

[dbg1 lp333945] 	check tipTriggers
[dbg1 lp333945] 		add tipTrigger: id=7013, name="woolSellTrigger", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=10316, name="triggerPos", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=19983, name="sheepWaterTrigger", className="FeedingTroughTipTrigger", is FeedingTroughTipTrigger
[dbg1 lp333945] 		add tipTrigger: id=8746, name="triggerPos", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=8492, name="windrowTrigger", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=10833, name="siloTrainTriggerIn", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=77301, name="tipTrigger", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=8507, name="triggerPos", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=8770, name="liquidManureTrigger", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=20116, name="cowStableStrawTrigger", className="FeedingTroughTipTrigger", is FeedingTroughTipTrigger
[dbg1 lp333945] 		add tipTrigger: id=10508, name="triggerPos", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=20104, name="feedingTroughTrigger", className="FeedingTroughTipTrigger", is FeedingTroughTipTrigger
[dbg1 lp333945] 		add tipTrigger: id=20092, name="feedingTroughTrigger", className="FeedingTroughTipTrigger", is FeedingTroughTipTrigger
[dbg1 lp333945] 		add tipTrigger: id=20061, name="pigStrawTrigger", className="FeedingTroughTipTrigger", is FeedingTroughTipTrigger
[dbg1 lp333945] 		add tipTrigger: id=9980, name="siloTrainTriggerIn", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=9501, name="tipTrigger1", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=9976, name="siloTrailerTriggerIn", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=8339, name="woodChipsSellTrigger", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=10114, name="siloTrailerTriggerIn", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=20056, name="pigWaterTrigger", className="FeedingTroughTipTrigger", is FeedingTroughTipTrigger
[dbg1 lp333945] 		add tipTrigger: id=20047, name="feedingTroughTrigger", className="FeedingTroughTipTrigger", is FeedingTroughTipTrigger
[dbg1 lp333945] 		add tipTrigger: id=10118, name="siloTrainTriggerIn1", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=8918, name="triggerPos", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=10121, name="siloTrainTriggerIn2", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=19973, name="feedingTroughTrigger", className="FeedingTroughTipTrigger", is FeedingTroughTipTrigger
[dbg1 lp333945] 		add tipTrigger: id=20122, name="cowWaterTrigger", className="FeedingTroughTipTrigger", is FeedingTroughTipTrigger
[dbg1 lp333945] 		add tipTrigger: id=10829, name="siloTrailerTriggerIn", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=10592, name="liquidManureTrigger", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=6974, name="triggerPos", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333945] 		add tipTrigger: id=10361, name="triggerPos", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp333946] Mach VRT (#1): call tipTrigger raycast (fwd) #1
[dbg1 lp333946] Mach VRT (#1): found tipTrigger
[dbg1 lp333946] Mach VRT (#1): transformId=77301: tipTrigger
[dbg1 lp333946] Mach VRT (#1): transformId 77301 is in tipTriggers (#36) (triggerId=77301)
[dbg1 lp333946]     trailerFillType=3 rape
[dbg1 lp333946]     trigger (77301) accepts trailerFillType
[dbg1 lp333946] Mach VRT (#1): self.cp.currentTipTrigger=77301 , cpActualLength=12.619958516669`

**Comment by pops64** [comment]
Closed #2909
