### ISSUE TITLE
 problem with unloading in the chaff bunker /Problem mit Häckselgut Silos

### ISSUE THREAD

**Issue by Autobosl** [Courseplay/courseplay#1897]
Hallo, 
bei mir auf meiner Mod-Map füllt Courseplay (aktuelle oder auch ältere Version) sämtliche Häckselgutsilos
nur bis zu einem Füllstand von 544000 Litern. was dann noch im Hänger ist wird ausserhalb des Silos abgekippt. Ab da wird dann nicht mehr in diesem Silo automatisch abgeladen. Abfahrer entlassen und manuell abladen funktioniert. Ich habe schon sämtliche mods entfernt, Alle Scripte die in der Map verbaut sind entfernt. Immer das selbe Ergebnis. Über Abladepunkt setzen geht, aber dann nur auf einem Punkt.
Es ist eine vierfach Map. Im nächsten Silo daneben kann problemlos wieder bis zu diesem Füllstand abgeladen werden.
Wäre dankbar für eine Lösung.

Hello, I will try it in english.
In my pivate mod map (4x)  i let courseplay fill the bunker silos. It works all fine until the silo has 544000 liters in. When there is chaff in the tipper too, then the driver  unload out of the silo.
The next courseplay driver drives through the silo without unloading. Manuell unloading in the silo is no problem. I have all mods and scripts deleted in the modfolder and the map too. 
Unloading in the silo next is no problem if it is empty. At the named filling point, the same problem.

What can produce this problem?
it is with new and older courseplay versions the same.

**Comment by pops64** [comment]
#1671 Closed to keep the issues are clean
