### ISSUE TITLE
Mode6 Unloading Forage Do not works 

### ISSUE THREAD

**Issue by bibifr** [Courseplay/courseplay#1900]
Hello everyone 
Better than explanation i puckup some screen shoot! 
While Charging Grass or whatever The Foragewagon never Going to unload. 
Both script are made Field and unloading point but that seem to block when Full

![fsscreen_2017_03_17_22_11_30](https://cloud.githubusercontent.com/assets/9522188/24063221/15cc73de-0b5f-11e7-8d16-cae9707120e1.png)

**Comment by dkfiremann** [comment]
What is the mode selected, map you are on, and how does the route look like?

**Comment by ThomasGaertner** [comment]
activate debug channel 12 before starting the tractor and post the log

**Comment by bibifr** [comment]
This is the log Whit Debug12

[dbg12 lp28846] JD7930 (#1): numWaitPoints=1, waitPoints[1]=56, numCrossingPoints=4
[dbg12 lp28846] JD7930 (#1): numWaypoints=672, stopWork=672, finishWork=672, hasUnloadingRefillingCourse=false,hasTransferCourse=true, waypointIndex=1
[dbg12 lp28846] JD7930 (#1): validateCanSwitchMode(): isDriving=true, isRecording=false, recordingIsPaused=false, customField.isCreated=false ==> canSwitchMode=false

Doesn't matter I have to Stop and Start road at first point always to Using Road to Unload Trailer :(

**Comment by ThomasGaertner** [comment]
there is a problem in your route setup: hasUnloadingRefillingCourse must be true if it should work properly.
you have to attach the unloading course to the end of the field course, you attached the field course to the unloading course.. try again and report

**Comment by bibifr** [comment]
Hello

I Loading First the Script road i mate For Cutting Grass, Then im Loading the Script of Road to Silo. 
I get exactly same!

The Script of The cutted Grass is not Inside A first it's arround a empty grass place That could be The issue maybe?

**Comment by dkfiremann** [comment]
With your course to the silo, can it Tip? 
Have you tried that course only with a full tipper?

**Comment by pops64** [comment]
Are you using the merge or append function to load your course? Make sure you always use the append function has this garentees that the course is at the end of of the field work

**Comment by bibifr** [comment]
@dkfiremann Yes THey do it If i do only this script whitout any issue

@pops64 I use always Merge Since FS13 And never got any issue and I just got FS17 tested it and look like i cannot make it works

I also just tested whit append and exactly same Issue Tractor seem to not want to unload
The silo it's not a specified silo in game it's one FOrm a mod maybe it's the problem ? 
But i can unload it whitout any problem if i just use it like a road so ...

No idea

**Comment by dkfiremann** [comment]
If it is a mod, then you need to tell us what mod that is.

**Comment by bibifr** [comment]
It's This mod 

https://www.modland.net/farming-simulator-2017-mods/implements-tools/pigfood-forage-storage-v-2.0.html

I don't think that come form the mod but let's check it

**Comment by pops64** [comment]
It is not a mod issue. How long is your unloading course? It must be at least 8 waypoints long otherwise CP will just ignore the unloading course.

**Comment by bibifr** [comment]
The entire Road to go to silo or just the Unloading point?

**Comment by pops64** [comment]
Try this first generate or your course first. Then hit the append button to load your unload course. Has I looked at your log again and CP thinks your unload course is a transfer course. This can only happen if your using the merge function. If that still doesn't work then a link to your map and a download for your savegame as well has your CP courses. See #1772 for a better explanation of why I say to use the append button

**Comment by bibifr** [comment]
Hello,

Ok i have got time to play today, I have remade all road and that looks like works perfectly now. 
Not sure what going on before but seem to be fine now :)

Sorry for wasting your time dear ;)
