### ISSUE TITLE
ChoosCombine Add Vehicle ID

### ISSUE THREAD

**Issue by huseyinsayar** [Courseplay/courseplay#1901]
Known on the "ManageCombines" tab;
The line "ChooseCombine:" that appears if "FindCombine: SelectManualy"
It appears as "CombineName (X m.)".

However, because of the confusion between vehicles with the same name,
Would it be possible to edit "VehicleID-CombineName (X m.)"?

**Comment by Satissis** [comment]
We cant always rely on that, since if the combine is in normal hired worker mode, it do not have an courseplay vehicle id. The X meter should be enough to tell if it's the correct combine based on the distance away from the combine.

**Comment by huseyinsayar** [comment]
On a field;
Same brand / model 3 pieces Combine, 3 pieces "Overloader" work is a confusion when I want to pair each other.
At least it would be nice to be able to show the "VehicleId" value for information.
In fact, in the FS series, I think that the publisher should make a license plate when purchasing / renting all their own running (truck, tractor, combine harvester etc.) and equipment (trailer, pull type harvester).
Thank you.

**Comment by Satissis** [comment]
hehe yeah that would be nice :) or at least auto generate one ;)

I'll close here again to keep issues clean as possible :)
