### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by huseyinsayar** [Courseplay/courseplay#1902]
For example;
With the TransferMode you will follow the Home-Tarla1 route;
Completion of Harvest with FieldWorkMod
Transfermode will follow Tarla1-Home route
A planning would be perfect.

**Comment by pops64** [comment]
? This has been discussed in multiple issues. It would require a lot of work for CP to be changed to this functionality. Can we close here?

**Comment by pops64** [comment]
Closed due to no response
