### ISSUE TITLE
CP course name length

### ISSUE THREAD

**Issue by pseikoNL** [Courseplay/courseplay#1906]
Hi,
Is it possible to change the course name length, who is 24 characters at the moment, to 36 characters or something? Now I've to encrypt my saved course names to much and it would be handsome if I can give more details to my course descriptions.

**Comment by Satissis** [comment]
The biggest problem I see with this, is that if you have multiply folders in folders, then at some point the sext will start going on top of the buttons on the right side to load the course.
It was shorter in the old days and we actually raised it to 25 characters in FS15.
I'm not sure if we are willing to raise it further. Need to have a chat with the others about it first.

**Comment by DynamicXYZ** [comment]
@Satissis 

What if you change the text that overlaps with dots? "What a great world to be in" "What a great wor.."
And hovering over it will hide the buttons and rename text to full, then change back once the mouse moves again.

**Comment by Symbob** [comment]
In all the years I've used CP I've never found the length of the course name to be an issue.  Being able to create separate folders to manage your courses means that  you don't really need long names to describe a course.  I just organise my courses in to different folders for different tasks so the actual course names aren't that big at all.  But everybody has their own way of doing things I guess.

**Comment by brnl** [comment]
Yeah, I did notice the limit a few times. I'm not really sure why you should limit this. If it's too long for the listing, the user will learn this the hard way. Another idea is to show the full name in the 'hint bar' (what do you call it?) where also the mode descriptions are shown.

**Comment by Satissis** [comment]
@DynamicXYZ the way we get the length on a string is not that accurate for us to actually do that, which is kinda sad.

@brnl Renaming course..... hmm yeah I'll put that on our suggestion list :)

I'll close here again to keep the issues clean
