### ISSUE TITLE
Reverse dumping in silo

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#1908]
Hey,
i have a problem, when i want to have my trailers drive backwards inro a silo to unload, they stop at the first contact with the silotrigger and do not drive as far backwards as possible.
This is problematic, because the heaps are too far forward for the leveler.

Greets JD_Tiger

**Comment by lcc1211** [comment]
I had a similar situation, but I found I was not backing far enough into the drop point.  I corrected by reversing about 1/2 into the sell point and then moving in a very straight line directly out.  I moved out of the sell point far enough to account for the length of the tractor plus the trailer.

**Comment by JDTiger** [comment]
i drive completely through the silo,so that ain't the solution for my problem :D

**Comment by pops64** [comment]
#1671 Closed to keep the issues area clean
