### ISSUE TITLE
Trailers not filling

### ISSUE THREAD

**Issue by SnoopBok** [Courseplay/courseplay#1909]
Hello, 

When chopping maize, the Krampe trailers made by Kyosho (from the modhub, like https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=66309&title=fs2017), are not filling. The tractor is driving next to the Krone Big x650 but it's not filling up. 

Can it be fixed, I really like these trailers :-)

**Comment by pops64** [comment]
This is a problem with the mod itself and not CP has I could not load it doing it manually

**Comment by pops64** [comment]
Closed due to no response
