### ISSUE TITLE
T9 + Condor 15001 Lane change problem

### ISSUE THREAD

**Issue by DynamicXYZ** [Courseplay/courseplay#1910]
When I'm trying to seed with the combination of T9 and Condor 15001 I'm always getting lanes that start late when the T9 backs up after lane changing and there's still about 3-4 meters of unseeded soil. It doesn't have any problems when finishing the lane though.

https://youtu.be/qe-ucZIhj5Q

**Comment by pops64** [comment]
Try again with out using the T9 if you have to reverse. Has the T9 doesn't work corrcetly in reverse it is something on our todo list to fix or prohibit. If your still getting this issue run with only debug channel 6 and a picture after it has done one turn

**Comment by DynamicXYZ** [comment]
@pops64 This only happens with articulated vehicles. All other non-articulated vehicles work fine.

The image below is a screenshot of what was done with another articulated vehicle, same results.

![fsscreen_2017_03_19_19_19_26](https://cloud.githubusercontent.com/assets/16375855/24085860/d0a213f0-0cd9-11e7-9299-7cd85aee6c86.png)

https://gist.github.com/DynamicXYZ/e8e20a641cdd6a215df55bc8a56ed963

**Comment by DynamicXYZ** [comment]
@Satissis Yeah non articulated tractors work.

I've been studying the behavior of the articulated tractors when they reverse with Courseplay and every time it wants to turn in a different direction the turning radius becomes sharper than what it should be, hence the wiggling behavior that it creates. But looking at what you put in reverse.lua, that math is beyond me.

**Comment by pops64** [comment]
Can we close here? Has no solution is present at the moment.
