### ISSUE TITLE
Find Harvester

### ISSUE THREAD

**Issue by hoefti10** [Courseplay/courseplay#1911]
Hi,
It is possible you changes somethin on the Harvester finding? Since the latest Version , i never noticed this before,the Departure didnt find any Harvester on the field in Automatic Mode.When i helped him a little bit to assign him the harvester he does nothing until the havester is full with grain and stop. After this he drive to unload the Harvester and all works fine.
![20170320091552_1](https://cloud.githubusercontent.com/assets/25055083/24092568/4c840e54-0d4f-11e7-943d-31dff2e7d5e9.jpg)

**Comment by dkfiremann** [comment]
Be sure that the tractor is on the field for it to be able to find the combine. 
And for it to empty the combine, the pipe of the combine should not be over the crops, if you have pathfinding enabled.

**Comment by sootysax** [comment]
this is the same problem i described in #1904

**Comment by pops64** [comment]
Has sootysax said
