### ISSUE TITLE
Dump truck is not unloaded

### ISSUE THREAD

**Issue by fckorolev** [Courseplay/courseplay#1912]
Not fully unloaded dump truck in a silo pit, tried many dump trucks and all have the same problem. I'm sending a snapshot of the problem
![farmingsimulator2017game 2017-03-21 09-29-47-86](https://cloud.githubusercontent.com/assets/13048250/24135269/167e5e74-0e1a-11e7-9d8b-a6ebd6b52356.png)

**Comment by NarvenEugen** [comment]
Hey. Sorry for the off-top. What's the mod on the clock on the right at the top? Let's write to the VC, or where?

**Comment by pops64** [comment]
Is it the same amount every time? If you unload manually does it leave the same amount? Does it drive after unloading?

**Comment by fckorolev** [comment]
pops64 
Remainder at unloading, different, but not less than 1/3 ... accordingly it does not go anywhere, because it is not unloaded

**Comment by fckorolev** [comment]
NarvenEugen
MultiOverlayV2__1_

**Comment by pops64** [comment]
Well when you unload it manually does this same behavior occur if you don't move the tractor?

**Comment by fckorolev** [comment]
When I start the dump truck manually it is unloaded as it should, but when I start Courseplay it is not completely unloaded

**Comment by fckorolev** [comment]
When I start the dump truck manually it is unloaded as it should, but when I start Courseplay it is not completely unloaded


>Вторник, 21 марта 2017, 18:49 +03:00 от pops64 <notifications@github.com>:
>
>Is it the same amount every time? If you unload manually does it leave the same amount? Does it drive after unloading?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Николай

**Comment by pops64** [comment]
The reason I asked this. Is that on giants side of things you can only unload x amount before the heap is to large and the trailer needs to be moved. CP doesn't support if the unload spot no longer accepts fruit because of heap size atm.

**Comment by fckorolev** [comment]
You want to say that the CP does not support its own function of "unloading in this place" ??? Then why is it in the CP.


>Среда, 22 марта 2017, 6:05 +03:00 от pops64 <notifications@github.com>:
>
>The reason I asked this. Is that on giants side of things you can only unload x amount before the heap is to large and the trailer needs to be moved. CP doesn't support if the unload spot no longer accepts fruit because of heap size atm.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Николай

**Comment by jmj486** [comment]
Have you made a "unloadpoint" there?
Because that is no need for that

**Comment by fckorolev** [comment]
You want to say that when unloading in a silo pit, you do not need to put the "unloading point" mark in reverse in the back?


>Среда, 22 марта 2017, 8:12 +03:00 от jmj486 <notifications@github.com>:
>
>Have you made a "unloadpoint" there?
>Because that is no need for that
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Николай

**Comment by jmj486** [comment]
yes that is what i am saying.... Just back all the way back in the silo. shift to "forward" and drive out. thats is all

**Comment by fckorolev** [comment]
And why should I have a CP, I saw a video, from CP 064, when everything was working ... you are doing a great job ... I can not work without the CP ... it's really hard to do what you're talking about, "Unloading Point ", And there to foresee that the dump truck must automatically pass forward or backward to unload ... this is logical, so in life it happens ...

>Среда, 22 марта 2017, 12:17 +03:00 от jmj486 <notifications@github.com>:
>
>yes that is what i am saying.... Just back all the way back in the silo. shift to "forward" and drive out. thats is all
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Николай

**Comment by pops64** [comment]
@jmj486 in reverse unloading to BGA silos CP stays in one stop during unloading unless you encounter the 50% full BGA silo spot, Only driving forward does CP attempt to unload evenly.

@fckorolev there is no need for a unload point in any trigger. All triggers are handled automatically expect for a few of them. And those need a wait point not an unload point. Please try again with out the unload point and report back. To answer your first question. CP does support tipping to ground. You just miss understood what I said. There are occasion when the heap that CP tries to tip is full(This is because of the way giants designed things) If you read the issue I linked I have suggested for it to detect where the edge of the heap is if the heap is full and stop to unload there.

**Comment by fckorolev** [comment]
Sorry, but tried in different ways ... Unloading backwards in "point discharge" does not work, I tried many BHA


>Среда, 22 марта 2017, 17:36 +03:00 от pops64 <notifications@github.com>:
>
>@jmj486 in reverse unloading to BGA silos CP stays in one stop during unloading unless you encounter the 50% full BGA silo spot, Only driving forward does CP attempt to unload evenly.
>@fckorolev there is no need for a unload point in any trigger. All triggers are handled automatically expect for a few of them. And those need a wait point not an unload point. Please try again with out the unload point and report back. To answer your first question. CP does support tipping to ground. You just miss understood what I said. There are occasion when the heap that CP tries to tip is full(This is because of the way giants designed things) If you read the issue I linked I have suggested for it to detect where the edge of the heap is if the heap is full and stop to unload there.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Николай

**Comment by fckorolev** [comment]
Watch this video, we'll see that before it could be done ... I mean unloading backing to the CP

https://youtu.be/jLduKDwIonQ  


>Среда, 22 марта 2017, 17:36 +03:00 от pops64 <notifications@github.com>:
>
>@jmj486 in reverse unloading to BGA silos CP stays in one stop during unloading unless you encounter the 50% full BGA silo spot, Only driving forward does CP attempt to unload evenly.
>@fckorolev there is no need for a unload point in any trigger. All triggers are handled automatically expect for a few of them. And those need a wait point not an unload point. Please try again with out the unload point and report back. To answer your first question. CP does support tipping to ground. You just miss understood what I said. There are occasion when the heap that CP tries to tip is full(This is because of the way giants designed things) If you read the issue I linked I have suggested for it to detect where the edge of the heap is if the heap is full and stop to unload there.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Николай

**Comment by pops64** [comment]
Has I said you should never use a unload point inside a trigger. If it doesn't work using the way CP was setup to do it(No Unload point) we will look into has Giants changed BGA silo triggers in 1.4

**Comment by fckorolev** [comment]
In general, in the early versions you all worked, but with the arrival of version 1.4 ceased ?? ))) It's a pity, I realized that your CP for version 1.4 is not good enough


>Среда, 22 марта 2017, 22:34 +03:00 от pops64 <notifications@github.com>:
>
>Has I said you should never use a unload point inside a trigger. If it doesn't work using the way CP was setup to do it(No Unload point) we will look into has Giants changed BGA silo triggers in 1.4
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Николай

**Comment by fckorolev** [comment]
Problems solved, rolling back the game to version 1.3.1

**Comment by Blackmankot** [comment]
@fckorolev Добрый день. Вы так и играете на версии 1.3.1?

**Comment by fckorolev** [comment]
Не,уже не играю,Курсплей поправили и нет необходимости уже


>Вторник, 18 апреля 2017, 7:59 +03:00 от Aleksandr <notifications@github.com>:
>
>@fckorolev Добрый день. Вы так и играете на версии 1.3.1?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Николай

**Comment by Blackmankot** [comment]
@fckorolev я так и подумал, но все же спросил. Удачи на полях!

**Comment by fckorolev** [comment]
Спасибо и тебе большого урожая


>Вторник, 18 апреля 2017, 10:47 +03:00 от Aleksandr <notifications@github.com>:
>
>@fckorolev я так и подумал, но все же спросил. Удачи на полях!
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Николай

**Comment by ThomasGaertner** [comment]
try v 01.0122 or higher and report....

**Comment by fckorolev** [comment]
Well, I download and try, write to this address ??


>Вторник, 18 апреля 2017, 17:19 +03:00 от Thomas Gärtner <notifications@github.com>:
>
>try v 01.0122 or higher and report....
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Николай

**Comment by pops64** [comment]
Yea if v 01.0122 or higher doesn't work respond here

**Comment by Blackmankot** [comment]
@pops64 Can this issue be closed? To cleanse the topic.

**Comment by pops64** [comment]
@Blackmankot we allow up to 14 days for users to test fixes to their issues before closing

**Comment by Blackmankot** [comment]
@pops64 I did not know.

**Comment by pops64** [comment]
Closed to keep issues area clean
