### ISSUE TITLE
Game breaking down after connect dolly with slurry sprayer

### ISSUE THREAD

**Issue by RKI91** [Courseplay/courseplay#1916]
Like in issue tittle. After that, the game stops responding and responds to any commands.

Courseplay version 5.01.00101
The tractor I use is Fendt black beauty from official pre-order dlc
Standard dolly semi-trailer attacher
My slurry sprayer Fliegl STF 25000 VC from modhub (https://www.farming-simulator.com/mod.php?lang=pl&country=pl&mod_id=50220&title=fs2017)

My log.txt
http://pastebin.com/ycMLrEAu

and in download version
https://mega.nz/#!a1wTERIY!L5lnGswL9i1xy94vMWTW1cSmftG0kIV2aNV3_wuVJv0

**Comment by pops64** [comment]
#1449 Closed to keep issues area clean
