### ISSUE TITLE
Problem with combinded triggers (tipping point & scale)

### ISSUE THREAD

**Issue by 37cee** [Courseplay/courseplay#1918]
Sorry if this has been brought up, but i havent seen any similar issues. I might have done something wrong as well. 
I recorded a to load at the farm and sell at a silo (Load at Start Point). At the sell trigger there is a scale trigger as well, the scale trigger kind of envelops the tipping trigger (like a small box in a large box). With a recent update courseplay stops at the scale and dispalys "xyz is beeing weighted", then it drives out of the scale trigger without unloading (in the tipping trigger).
The course worked before i noticed the weighing notice, since it shows, the vehicles dont unload. I tried adding a tipping point, but it wont notice that as well, if its inside the scale trigger.

I tried to make a usable screenshot but the the are alot of buildings, so the trigger areas dont really show well.  So just sketched the situation.

![skizze](https://cloud.githubusercontent.com/assets/24392251/24194300/dacf7c64-0ef5-11e7-9e64-98558ea664ab.png)
black = CP Route (Grain Transport, load at start) 
red box = trigger for scale
blue = trigger to unload

**Comment by pops64** [comment]
I am assuming your using a modded map?

**Comment by 37cee** [comment]
Yes it is (i dont know if there are any overlaping triggers on the offical maps). While i haven't thought of removing the trigger, it's something i would prefer to avoid. 
Still it seems odd, that CP seems to be ignoring a trigger, that worked before (because it didnt have any use for the scale trigger). But again i dont have taken a look into the code to understand how CP recognizes the triggers, to see if this could be fixed.

**Comment by pops64** [comment]
It is not that is ignoring the trigger. It is how trigger recognition works. I don't think it was ever setup to recognize a trigger inside a trigger unless the outside trigger is ignored. Which weigh stations were prior to the latest releases. Cause my understanding is if it is in a trigger it will no longer look for triggers until it clears that trigger. Unless that trigger has been set to be ignored.

**Comment by lcc1211** [comment]
Were you perhaps trying to tip a very very large load?  I had this issue with a mod Krampe Bandit 980 holding 52K liters.  It did not tip until I lowered it down below 40K liters.  I think also a part of the issue was the rocking back & forth of the tractor while sitting on the scale.

**Comment by 37cee** [comment]
Ok, (re)moving the trigger will be the only way then. If this would be sovled via course play the only option might be to add an option to ignore certain trigger, but again this will most likely add more potential problems further on.

Why was the scale added as a trigger - i'm just asking out of interest?

The size of the tipper doesnt matter, i tried different sizes.

**Comment by Satissis** [comment]
Adding an scale trigger on top of an tip trigger, is in my mind an horrible example on what not to do in a map. It makes no cense to do that and I have never seen that in real life as well. Scales are meant to be placed some where so multi vehicle can stand in ques wo be weighed and then have to drive to unload and then get weighed again to tell how much they have delivered in tons.
That's the way I have seen it work, but if you could give an example where it's used in real life, I have something to reference to.

**Comment by lcc1211** [comment]
@Satissis What is odd is this stopping on the scale didn't start for me until .101 of CP, so I thought you had added it.  There is even an information window displayed where CP puts messages saying the vehicle is being weighed.  I am using a modded map that hasn't been updated since January.

**Comment by Satissis** [comment]
@lcc1211 Yeah the stop at weight station was broken before v101 and was re-implemented in v101 which is why it's doing that now.

**Comment by Satissis** [comment]
Can we close here again ?

**Comment by 37cee** [comment]
yes.

**Comment by pops64** [comment]
Thanks. Closed to keep issues are clean
