### ISSUE TITLE
Can't open the HUD

### ISSUE THREAD

**Issue by rwsender** [Courseplay/courseplay#1920]
- Game recognises the mod
- Game loads the mod
- Game scans the fields
- Game refuses to open, tried delete, tried rebinding

I am running standalone version of the game, updated to 1.44 release and the latest github release of courseplay.

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by rwsender** [comment]
http://pastebin.com/UjVjBQxT

Here is log, i checked it but found no issues.

**Comment by rwsender** [comment]
Well, guess I wasn't fully holding down left CTL. Sorry about that.
