### ISSUE TITLE
courseplay and AI VehicleExtension

### ISSUE THREAD

**Issue by mngrazy** [Courseplay/courseplay#1921]
hi guys

i have some trouble with cp 5.01.00101 and ai VehicleExtension v1.0 Beta 8 ( https://github.com/Mogli12/AIVehicleExtension )

FS17_courseplay/mode2.lua:540: attempt to index field 'acDirectionBeforeTurn' (a nil value)
Error: Running LUA method 'update'.

i think this is a leftover from FS15 and AutoCombine , but not working in FS17 

best regards grazy

**Comment by pops64** [comment]
#1701 Closed to keep issues are clean
