### ISSUE TITLE
Disable "Spurreißer" during seeding course with multiple seeders working in "Versatz"

### ISSUE THREAD

**Issue by schuetze** [Courseplay/courseplay#1925]
During a seeding course with multiple seeders working in "Versatz", the chances are very high that sooner or later one of the later seeders is destroying already seeded field with his "Spurreißer".
I would prefer the "Spurreißer" to be deactivated during a seeding course with multiple seeders. Maybe even permanently if working with courseplay? Courseplay would not need it at all I guess. Maybe make an option to allow to disable the "Spurreißer" so the immersion is not destroyed.
Cheers.
![fsscreen_2017_03_24_09_06_58](https://cloud.githubusercontent.com/assets/5966850/24285920/d4538c9e-1072-11e7-94b2-4eaf8075997a.png)

**Comment by jmj486** [comment]
that option is already there???

**Comment by pops64** [comment]
Yes. With the automatic ridgemarker setting by default it is set to automatic. Change this to manual and at the end of the current lane it will fold and not use them any longer

**Comment by Satissis** [comment]
as @pops64 said.
The options is on the first page where you start and stop CP.
The option will only show while you are in mode 4(Seeding and Fertilizing), have an seeder attached and CP is driving. If set to manually, and one of the sides is down, just use the key to change it to the right position and you should be good to go.

Will close here to keep issues cleared

**Comment by schuetze** [comment]
Awesome! I will try it asap. Thanks for the quick support.

**Comment by schuetze** [comment]
Found it! :)
![fsscreen_2017_03_25_08_52_30](https://cloud.githubusercontent.com/assets/5966850/24320589/a15ce7a6-1138-11e7-8691-47fdadc39582.png)

**Comment by Satissis** [comment]
@pops64 fixed so once you deactivate it from the menu, then it should lift the ridge markers right away.
It should have been implemented in v01.00103 if I remember correctly.
