### ISSUE TITLE
CP misinterprets some (custom?) triggers as traffic

### ISSUE THREAD

**Issue by Nordvarg** [Courseplay/courseplay#1926]
Hi. First let me say how impressed I am with your work so far. Your efforts alone increase the game’s longevity tenfolds.

_Sorry if this is something that has been posted earlier._

When backing up, to empty into silo, trailer, or truck, or both, seem to hit a trigger, unrelated to the course’s mission.

**Truck stops. CP tells it’s in traffic.**

![cp_collision_problem](https://cloud.githubusercontent.com/assets/26651159/24294787/3647a7f8-1098-11e7-93a5-99750d29cdf4.jpg)

The map is Pine Cove by [Stevie](https://www.facebook.com/StevieFSMods/posts/1273688002727482).

The trigger is called ‘autmaticTrigger’ and is part of Marhu’s manureseperator. But I’ve also had the same thing happen with other, custom triggers on the map.

This is what I found in the log _(sorry if I've used wrong debug channels)_:

`[dbg3 lp8523] SX 210 Twinstar (#1): 	onEnter, g_currentMission.nodeToVehicle[44163] == nil -> setting automaticTrigger as aPath vehicle`
`[dbg3 lp8523] SX 210 Twinstar (#1):onEnter Trigger2: triggered collision with 44163` 
`[dbg3 lp8523] SX 210 Twinstar (#1): 	onEnter, checking CollisionIgnoreList`
`[dbg3 lp8523] SX 210 Twinstar (#1):		ASS 298 vs "PathVehicle"`
`[dbg3 lp8523] SX 210 Twinstar (#1):		SX 210 Twinstar vs "PathVehicle"`
`[dbg3 lp8523] SX 210 Twinstar (#1): 	"PathVehicle" is not on list, setting "self.cp.collidingVehicleId"`
`SX 210 Twinstar (#1): 	added 44163 to self.cp.collidingObjects[2]`
`SX 210 Twinstar (#1): 	self.cp.collidingObjects[1]:`
`SX 210 Twinstar (#1): 	self.cp.collidingObjects[2]:`
`SX 210 Twinstar (#1): 	                             44163 automaticTrigger`
`SX 210 Twinstar (#1): 	self.cp.collidingObjects[3]:`
`SX 210 Twinstar (#1): 	self.cp.collidingObjects[4]:`
`[dbg19 lp8524] SX 210 Twinstar (#1): call specialTrigger raycast (fwd) #1`
`[dbg3 lp8524] SX 210 Twinstar (#1): checkTraffic:	stop`

All the best :)

**Comment by Satissis** [comment]
I'll have en look at it at some point. I also noticed this issues with one of the auger wagons, which also have an trigger that a vehicle sometimes also say that's in traffic with when it hits it, so I will look into that sa well at the same time.

**Comment by Nordvarg** [comment]
Great :)

**Comment by pops64** [comment]
Collapsing mod issues into one thread. #2231. This one won't make the list because. A) It has fixed it self(A number of changes have been made to traffic collisions) or B) No name provided for the auger wagon.
