### ISSUE TITLE
Mode 2 suggestion

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1927]
Is there any way you can adjust mode 2 to check to see if the drive-now fill level has been reached before heading to the waiting point?   This way the tractor can proceed directly to the unload route from the loading point when it is full enough to unload.

I thought this was previously how it worked in FS15?

**Comment by HansJDen** [comment]
Is there a way, to let the combine telling the tractor, it's making a left-hand turn (making headland counter clockwise) My Mode2 tractor often get stuck with the combine. 
I don't know if this is a Mode2 or Mode6 problem.

Thanks fore the great work....

**Comment by pops64** [comment]
Not going to fix. I haven't seen this problem. Unless you can show us what you think is differnt from 15 we are closing this out.
