### ISSUE TITLE
New NIL return issue

### ISSUE THREAD

**Issue by genen** [Courseplay/courseplay#1930]
Not see this issue before, sorry if repeat. Today I tried using the Holmer Overload wagon. After setting up the course it drives to combine fine, but then it never starts moving after the combine is done unloading. Looks like a NIL return in log.

Error: Running LUA method 'update'.
C:/Users/gene/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/mode2.lua:540: attempt to index field 'acDirectionBeforeTurn' (a nil value)
Error: Running LUA method 'update'.
C:/Users/gene/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/mode2.lua:540: attempt to index field 'acDirectionBeforeTurn' (a nil value)
Error: Running LUA method 'update'.
C:/Users/gene/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/mode2.lua:540: attempt to index field 'acDirectionBeforeTurn' (a nil value)
Error: Running LUA method 'update'.
C:/Users/gene/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/mode2.lua:540: attempt to index field 'acDirectionBeforeTurn' (a nil value)
Error: Running LUA method 'update'.
C:/Users/gene/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/mode2.lua:540: attempt to index field 'acDirectionBeforeTurn' (a nil value)
Error: Running LUA method 'update'.
C:/Users/gene/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/mode2.lua:540: attempt to index field 'acDirectionBeforeTurn' (a nil value)
Error: Running LUA method 'update'.
C:/Users/gene/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/mode2.lua:540: attempt to index field 'acDirectionBeforeTurn' (a nil value)
Error: Running LUA method 'update'.
C:/Users/gene/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/mode2.lua:540: attempt to index field 'acDirectionBeforeTurn' (a nil value)
Error: Running LUA method 'update'.

and 

Error: Running LUA method 'update'.
C:/Users/gene/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/mode2.lua:540: attempt to index field 'acDirectionBeforeTurn' (a nil value)
[dbg15 lp17817] handleMode3(vehicle, allowedToDrive=true, dt)
Terra Variant 600 eco (#1): changed Variable: firstWaitPoint: 9
Terra Variant 600 eco (#1): changed Variable: numWaypoints: 27
Terra Variant 600 eco (#1): changed Variable: backPointsUnfoldPipe: 8
Terra Variant 600 eco (#1): changed Variable: forwardPointsFoldPipe: 2
Terra Variant 600 eco (#1): changed Variable: previousWaypointIndex: 10
Terra Variant 600 eco (#1): changed Variable: isUnloaded: true
Terra Variant 600 eco (#1): changed Variable: wait: true

and 

-------------------------
[dbg15 lp17818] handleMode3(vehicle, allowedToDrive=true, dt)
-------------------------
[dbg15 lp17819] handleMode3(vehicle, allowedToDrive=true, dt)
-------------------------
[dbg15 lp17820] handleMode3(vehicle, allowedToDrive=true, dt)
-------------------------
[dbg15 lp17821] handleMode3(vehicle, allowedToDrive=true, dt)
-------------------------
[dbg15 lp17822] handleMode3(vehicle, allowedToDrive=true, dt)
-------------------------
[dbg15 lp17823] handleMode3(vehicle, allowedToDrive=true, dt)
-------------------------
[dbg15 lp17824] handleMode3(vehicle, allowedToDrive=true, dt)
-------------------------
[dbg15 lp17825] handleMode3(vehicle, allowedToDrive=true, dt)
-------------------------
[dbg15 lp17826] handleMode3(vehicle, allowedToDrive=true, dt)
-------------------------

and

Terra Variant 600 eco (#1): changed Variable: previousWaypointIndex: 11
-------------------------
[dbg15 lp17845] 	handleAugerWagon(vehicle, $l10n_holmerGrainTank, unfold=false, unload=false, orderName=foldAfter)
[dbg15 lp17845] 		pipeIsFolding=false, pipeIsFolded=false, pipeIsUnfolded=true
[dbg15 lp17845] 			setPipeState(1) (fold)
[dbg15 lp17846] handleMode3(vehicle, allowedToDrive=true, dt)
-------------------------
[dbg15 lp17846] 	handleAugerWagon(vehicle, $l10n_holmerGrainTank, unfold=false, unload=false, orderName=foldAfter)
[dbg15 lp17846] 		pipeIsFolding=true, pipeIsFolded=false, pipeIsUnfolded=false
[dbg15 lp17847] handleMode3(vehicle, allowedToDrive=true, dt)
-------------------------
[dbg15 lp17847] 	handleAugerWagon(vehicle, $l10n_holmerGrainTank, unfold=false, unload=false, orderName=foldAfter)
[dbg15 lp17847] 		pipeIsFolding=true, pipeIsFolded=false, pipeIsUnfolded=false
[dbg15 lp17848] handleMode3(vehicle, allowedToDrive=true, dt)
-------------------------
[dbg15 lp17848] 	handleAugerWagon(vehicle, $l10n_holmerGrainTank, unfold=false, unload=false, orderName=foldAfter)
[dbg15 lp17848] 		pipeIsFolding=true, pipeIsFolded=false, pipeIsUnfolded=false
[dbg15 lp17849] handleMode3(vehicle, allowedToDrive=true, dt)

and 

Error: Running LUA method 'update'.
C:/Users/gene/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/mode2.lua:540: attempt to index field 'acDirectionBeforeTurn' (a nil value)
[dbg4 lp21832] Terra Variant 600 eco (#1): combine.workWidth: 13.20,vehicle.cp.combineOffset: 10.20, calculated offset: 10.20, fruitSide: 404notFound  
[dbg4 lp21832] Terra Variant 600 eco (#1): combine is empty and turning
Error: Running LUA method 'update'.
C:/Users/gene/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/mode2.lua:540: attempt to index field 'acDirectionBeforeTurn' (a nil value)
[dbg4 lp21833] Terra Variant 600 eco (#1): combine.workWidth: 13.20,vehicle.cp.combineOffset: 10.20, calculated offset: 10.20, fruitSide: 404notFound  
[dbg4 lp21833] Terra Variant 600 eco (#1): combine is empty and turning
Error: Running LUA method 'update'.
C:/Users/gene/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/mode2.lua:540: attempt to index field 'acDirectionBeforeTurn' (a nil value)
[dbg4 lp21834] Terra Variant 600 eco (#1): combine.workWidth: 13.20,vehicle.cp.combineOffset: 10.20, calculated offset: 10.20, fruitSide: 404notFound  
[dbg4 lp21834] Terra Variant 600 eco (#1): combine is empty and turning
Error: Running LUA method 'update'.
C:/Users/gene/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/mode2.lua:540: attempt to index field 'acDirectionBeforeTurn' (a nil value)
[dbg4 lp21835] Terra Variant 600 eco (#1): combine.workWidth: 13.20,vehicle.cp.combineOffset: 10.20, calculated offset: 10.20, fruitSide: 404notFound  
[dbg4 lp21835] Terra Variant 600 eco (#1): combine is empty and turning

**Comment by Satissis** [comment]
Yeah I believe some one already posted about it.
I've added it to my todo list just to be sure.

**Comment by pops64** [comment]
#1701 Closed duplicate
