### ISSUE TITLE
Tractor in mod 2 not moving while browsing Shop or in the Menu

### ISSUE THREAD

**Issue by gec100** [Courseplay/courseplay#1931]
As the title says plus, but not necessary related, tractor aborts unloading and continues it's course when switched to while switching between vehicles .

the map is sudehammer if relevant

**Comment by Satissis** [comment]
In single player this is the default behavior from Giants.
Once you are in a menu, it will pause the game.
Nothing we can do about it.

Closed to keep issues cleared

**Comment by gec100** [comment]
That's actually not the case. cause all other vehicles, that where on the move before i enter menu or the shop, are still moving while i'm in it. Just the tractors waiting the fill level would not move if the fill level is reached while i'm in the menu or shop.

not sure if this is clear or not.

**Comment by Satissis** [comment]
> As the title says plus, but not necessary related, tractor aborts unloading and continues it's course when switched to while switching between vehicles .
That's related to VGS. Modder of VGS have been notified about it.

Regarding the tractor being filled, are you in that tractor while doing that? if so then it's still basic behavior from Giants. If you drive an tractor and open the menu or shop while in speed, that vehicle will grind to an stop and could also effect the CP driver of the vehicle if you are in it.

**Comment by gec100** [comment]
no. the tractor is controlled by the CP.  so technically i'm not in the vehicle. But will test it again now.

**Comment by Satissis** [comment]
hmm I just tested this and I'm wrong about the way I explained it.
The vehicle do indeed continue driving while I'm in it, but I don't have your problem. I also didn't run in mode 2, so that's might why I could not reproduce it.

Is this only occurring while it's driving in the field to service an combine or does this also happens when it's driving the unload route ?

**Comment by gec100** [comment]
i'm testing this only in the field right now. what i know is that when the tractor is on the move it will not stop if i enter the menu. only when  it is waiting for fill level it will not start moving ti'll i exit the menu. 

But you are right this happens only if i'm on the tractor.

**Comment by Satissis** [comment]
alright, well this is such an small thing and no game breaking at all, so I don't think we will be doing anything about it.

**Comment by pops64** [comment]
Has @Satissis  said we probably wont do anything about this closed to keep issues area clean
