### ISSUE TITLE
start_stop.lua:21: attempt to index field 'currentHelper' (a nil value)

### ISSUE THREAD

**Issue by Miketeg** [Courseplay/courseplay#1933]
Randomly get this error while using truck(or tractor) + trailer to unload combine and drive to a silo

Error: Running LUA method 'mouseEvent'.
C:/Users/marqu/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/start_stop.lua:21: attempt to index field 'currentHelper' (a nil value)

It happens when I tried to "drive the course" and it totally crash the equipment..I mean, I can't reuse it after the issue happen, even without courseplay.

If I quit and restart a game, same issue will happen, I need to use another vehicule and it won't happen...for the moment, but will rehappen later..randomly.

**Comment by Satissis** [comment]
What version if Cp are you using?
also post your full log to Gist and add an link here for it.

**Comment by Miketeg** [comment]
I'm using the latest developper version. 5.01 if memory serve.

I made a little cleanup of my mod folder, I had 2 or 3 mods with error and I was not able to reproduce the error yesterday.

But, it worked fine for the first 30 hours on this specific savegame, than it started to crash. After the mod cleanup, I played around 2 hours without issue. It's very random, so i'm sure that it will happen again. If so ,I will come and post my log.file.

**Comment by pops64** [comment]
There are 107 versions of version 5.01 which one specifically because this sounds like a mod conflict which was fixed around version 70. I will close this out for now as it seems to be fix just post back here if you discover the error again and have a log. And we will open it back up
