### ISSUE TITLE
Mode 10 not working right after 104

### ISSUE THREAD

**Issue by Liquid515** [Courseplay/courseplay#1934]
when in mode 10  courseplay never lowers the blade and I have it set to auto..seems to stay all the way up and I'm using the Field Python also have it set to compact and leveling

**Comment by Satissis** [comment]
[How to provide a nice and sexy bug report](https://github.com/Courseplay/courseplay/wiki)

**Comment by Liquid515** [comment]
my course in inline with bunker and when it starts it raises the blade all the way up and never lowers it...don't have a way to make a video of the problem

**Comment by pops64** [comment]
It doesn't lower all the way to the ground it stays x distance off the ground while it filled an changes height as it does so

**Comment by Liquid515** [comment]
doesent lower at all....maybe i should try to debug it and sent log file...witch debug mode do i use

**Comment by pops64** [comment]
Debug channel 10 with a picture or video.

**Comment by Liquid515** [comment]
![20170328_184857](https://cloud.githubusercontent.com/assets/26668377/24431052/cad97c8c-13e7-11e7-9b79-cd2de9353f87.jpg)

![20170328_184903](https://cloud.githubusercontent.com/assets/26668377/24431053/cd74505c-13e7-11e7-9081-e9c30bb98e13.jpg)
![20170328_184910](https://cloud.githubusercontent.com/assets/26668377/24431056/d039e1c6-13e7-11e7-9bc6-5ee0bfec2ca8.jpg)
![20170328_184859](https://cloud.githubusercontent.com/assets/26668377/24431058/d476937e-13e7-11e7-8c67-e7c6ed30c565.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/877309/log.txt)

**Comment by pops64** [comment]
Try again with a fresh silo. The changes made in 104 probably made the partially filled silo bugged.

**Comment by Liquid515** [comment]
ok ill try that   it sure made a mess with that bunker

**Comment by Liquid515** [comment]
ok that is fixed I deleated all my courses and started a new game...new problem tho  now it only stays to the right of bunker

**Comment by Liquid515** [comment]
ill debug again and resend new pics

**Comment by Liquid515** [comment]
![20170328_212704](https://cloud.githubusercontent.com/assets/26668377/24434512/06a4efe2-13fe-11e7-84f8-cbcf5ef97bb9.jpg)
![20170328_212717](https://cloud.githubusercontent.com/assets/26668377/24434517/0af9c81a-13fe-11e7-9a7b-6fa36f6dd7b4.jpg)
![20170328_212655](https://cloud.githubusercontent.com/assets/26668377/24434521/0f39694e-13fe-11e7-9183-d13de4d8b1f6.jpg)
![20170328_212555](https://cloud.githubusercontent.com/assets/26668377/24434525/14f846b6-13fe-11e7-9f89-8b7af6f427dc.jpg)
![20170328_212615](https://cloud.githubusercontent.com/assets/26668377/24434526/1872674a-13fe-11e7-9aef-9222da4b3e16.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/877505/log.txt)

**Comment by pops64** [comment]
Keep letting it run and it should even out or center out where the trailer enters the silo

**Comment by Liquid515** [comment]
ok it started worker after about ten runs...thanks for all your help  and you guys  keep up the awesome work   look forward to new releases....you can close this thread

**Comment by Liquid515** [comment]
thanks
