### ISSUE TITLE
CP No Longer Recognizes Total Mix Ration From Mod

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#1935]
After recent updates CP no longer recognized Total Mix Ration in the Mischstation mod & the silage and slurry triggers for the GTX Ferminting silo
[log.txt](https://github.com/Courseplay/courseplay/files/870215/log.txt)
, and displays  an error message saying it doesn't have the selected fill type.  This worked prior to .101.
I've always used this on mode 1.  The mods to include the Hobbs Farm map have not been updated since January, so I don't think they are the reason.  I can't confirm that the slurry trigger ever worked, but the silage trigger worked on the silo.

![20170325102855_1](https://cloud.githubusercontent.com/assets/24764870/24324504/19b99062-115e-11e7-89be-78800a634f72.jpg)

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by lcc1211** [comment]
Fermenting silo v1.2 came from modhub:  http://www.modhub.us/farming-simulator-2017-mods/fermentingsilo-fs17-placeable-v1-2/

Mischstation came from http://uploadfiles.eu/humsczcmc87m/FuttermischerPack_bitte_entpacken.rar.html

**Comment by scaniafreak** [comment]
I have also an issue with the FutterMischerPack. Just thought i would post it here.
I have made some routes with CP to tip in the different tip bins. Like a route to tip straw in the right bin, as you see in the above picture.

the trailer backs up to the tip trigger, and starts tipping. However the straw keeps inside the trailer. None is falling into the bin. With none intervention, the trailer stays like that. 
Also when tipping like that, the driver in the tractor is flickering. like CP really fast starts and stops  the driver. Also when hovering the mouse over CP controls, the controls are change, like if the scroll button hangs. For Example if i move the mouse over the turn radius, it is increased.

I don't know if this behaviour was there before in old versions. I use FS17 1.4.4 with CP 5.01.00109.dev

**Comment by sootysax** [comment]
'i am experiencing this issue on the Suedhemmern 6.0 map.   It seems as the game progresses and you run multiple courses with different fill types, CP will get confused and say the silo does not have the selected fill type.  This is happening with the straw/grass storage silo, as well as the conveyor belts loading compost, TMR, Pig Rations.

Saving the game and reloading will fix the issue.

**Comment by lcc1211** [comment]
The triggers for offloading grass & hay are working on the ferment silo, but CP doesn't recognize the slurry trigger.  Also, restarting did change one thing on the mischstation-CP will now drive under the trigger but keep going with the error message displayed. I have not tried it with the feed mixer for pigs, though, but it has never had a problem recognizing pig feed.

**Comment by pops64** [comment]
The slurry trigger should be handled by mode8

**Comment by lcc1211** [comment]
Mode8 by itself just says wrong trailer for this (Zunhammer Gulle Technik 30000). When I create a course to spray slurry and apend or merge the slurry refill run, it drives by the trigger and keeps going.  It will refill at the pig slurry and at the cow slurry though, so I know I've created the course correctly.

**Comment by pops64** [comment]
I thought you were unloading slurry. Not refilling slurry

**Comment by lcc1211** [comment]
I found a work around.  For the cow feed mixer, I told CP it was picking up pig feed and it will pick it up, however it sometimes doesn't deliver the feed. CP shows a message saying tip trigger reached, but it doesn't unload.  This happens randomly, but once it starts happening only a game restart fixes the issue.

**Comment by lcc1211** [comment]
I've just updated to the latest version of CP and the latest of this Fermenting silo off Modhum (v1.5).  The author says "additional triggers" added and that it is compatible with CP.  Mode 1 has an option for digestate, but the slurry spreaders (mod and vanilla) just return an error message saying "wrong trailer", but using mode 8 will do nothing except drive right by the triggers.  The game recognizes the triggers, but CP doesn't.

**Comment by lcc1211** [comment]
Closing since nothing is being done with it. I've either explained it poorly or it isn't something that is wrong for anyone else.

**Comment by pops64** [comment]
No there were a few people that have to appear to have this issue. So unless it fixed itself I am going to reopen this. We will look into it when we can you just have to be patient.

**Comment by pops64** [comment]
Collapsing mod issues into one thread. #2231
