### ISSUE TITLE
Parking Spot Bug SomeTimes & Mode2 Circling

### ISSUE THREAD

**Issue by Blackjack155** [Courseplay/courseplay#1941]
1. Problem wenn er auf der warteposition steht  dann steht er meinstens in der frucht und blockiert denn Drescher 
2. wenn er die ladung weg fahren soll dann will er zu wartepunk x y und dreht sich dann nur im kreis  
ich habe eineges probiert um denn fehler zu beheben aber ohne erfolg 
musste leider mit übersetzer arbeiten bitte dies zu entschuldigen 

One. Problem when he stands on the waiting position then he stands at first in the fruit and blocks because Drescher
two. if he is to drive the charge away then he wants to waitpunk x y and then turns only in the circle
I have tried ages to correct errors but without success
Had unfortunately to work with translator please excuse this

**Comment by pops64** [comment]
![image](https://cloud.githubusercontent.com/assets/10678220/24358117/0d2ba7ec-12ce-11e7-9088-d3c2b611f50f.png)

Is this your first problem? 

![image](https://cloud.githubusercontent.com/assets/10678220/24358245/90c8eef2-12ce-11e7-8cc8-cdd3f5472ea3.png)

Is the yellow circle on the far right where it is circling? 

If so please see #1881 Or at least post some pictures and start debug channel 4 before start Courseplay and post that log

**Comment by Blackjack155** [comment]
Yes the first problem is synonymous

Log: 
dbg4 lp15338] 1255/1455 XL (#2): updateReachableCombines()
[dbg4 lp15338] 1255/1455 XL (#2): combine (id222) is manually set
[dbg4 lp15338] 1255/1455 XL (#2) (233): call combine: 222
[dbg4 lp15339] 1255/1455 XL (#2) (233): request check-in @ 222
[dbg4 lp15339] 1255/1455 XL (#2): registering at combine Lexion 700 small
[dbg4 lp15339] 1255/1455 XL (#2): path finding inactive
[dbg4 lp15339] 1255/1455 XL (#2) (233): distanceToCombine=381.83937888967 for combine.id 222
[dbg4 lp15339] 1255/1455 XL (#2) (id 233): it's my turn
[dbg4 lp15339] 1255/1455 XL (#2) is being checked in with Lexion 700 small
[dbg4 lp27682] 1255/1455 XL (#2): combine.workWidth: 9.00,vehicle.cp.combineOffset: 8.00, calculated offset: 8.00, fruitSide: 404notFound  
[dbg4 lp27682] 1255/1455 XL (#2): combine is empty 
[dbg4 lp27682] 1255/1455 XL (#2): vehicle.cp.nextTargets: 1 
[dbg4 lp29494] 1255/1455 XL (#2): unregistering from combine id(222)


What is encircled there I see not as said the trailer is full then he wants to waypoint x y and turns only in the circle

I have not found where I can upload pictures

**Comment by pops64** [comment]
You can just drag the image file to to comment box and github will automatically upload them

**Comment by Blackjack155** [comment]
![fsscreen_2017_03_28_18_21_31](https://cloud.githubusercontent.com/assets/26688591/24415992/882915f4-13e3-11e7-91f0-585336f0a8c5.png)
![Uploading fsScreen_2017_03_28_18_21_42.png…]()
![Uploading fsScreen_2017_03_28_18_21_50.png…]()
![Uploading fsScreen_2017_03_28_18_21_55.png…]()

**Comment by Blackjack155** [comment]
![fsscreen_2017_03_28_18_21_31](https://cloud.githubusercontent.com/assets/26688591/24416023/a3243f78-13e3-11e7-9d15-488351eb5447.png)

![fsscreen_2017_03_28_18_21_42](https://cloud.githubusercontent.com/assets/26688591/24416034/acdb6ece-13e3-11e7-89c7-d067fc6e6a88.png)

![fsscreen_2017_03_28_18_21_50](https://cloud.githubusercontent.com/assets/26688591/24416036/afa25f14-13e3-11e7-8697-bc8c46b59130.png)

![fsscreen_2017_03_28_18_21_55](https://cloud.githubusercontent.com/assets/26688591/24416040/b1ba45d2-13e3-11e7-81d6-95895f5ff081.png)

**Comment by Blackjack155** [comment]
Another mistake that I am on the falls is that he does not drive vehicles 
![fsscreen_2017_03_28_18_30_51](https://cloud.githubusercontent.com/assets/26688591/24416374/d9cfcff0-13e4-11e7-9e3f-3e1d412fe714.png)

**Comment by pops64** [comment]
Edited title for clarity

**Comment by pvajko** [comment]
#2175 has a fix for this.

**Comment by pvajko** [comment]
The recent changes in mode2 must have fixed problem 2.

**Comment by pvajko** [comment]
Both problems should now be fixed.
