### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by Visso79** [Courseplay/courseplay#1942]
Hello.
I have a problem - use a latest game patch, courseplay also too. But not load I can still wait a 5, 10, 15, 20 minutes - not load. When look up a log file- shows a problem with lua:94
Adding a log.txt file.

Thanks for replies.
[log.txt](https://github.com/Courseplay/courseplay/files/873735/log.txt)

**Comment by pops64** [comment]
Are sure all files are in your CP directory. Your log says it is missing the vehicles.lua

**Comment by Visso79** [comment]
Thanks for look. I have a mising file - vehicles.lua. I was reinstall and now all work.
