### ISSUE TITLE
Mode 10 causes call stack error

### ISSUE THREAD

**Issue by bigjoker76** [Courseplay/courseplay#1945]
Hello,
I´m running version 01.00109. When starting mode 10 I get an error
![fsscreen_2017_03_29_20_55_59](https://cloud.githubusercontent.com/assets/6426554/24471568/bd4b22f6-14c2-11e7-884b-d38fbe3a09e2.png)

**Comment by pops64** [comment]
The whole log please. https://github.com/Courseplay/courseplay/wiki

**Comment by bigjoker76** [comment]
Ah...yes....sorry


[log.txt](https://github.com/Courseplay/courseplay/files/880921/log.txt)

**Comment by pops64** [comment]
You have a mod that both throws a call stacks before CP does. AIVehicleExtension which is unsupported at this time but shouldn't interfere with CP any more and you also have FabrikScript which last I heard was unsupported and did conflict with CP. I would start by turning theses two mods off and seeing if you can reproduce this. Also did you do anything abnormal when generating the course? CP threw out 
`C:/Users/Jochen/Documents/My Games/FarmingSimulator2017/mods/zzz_courseplay/generateCourse.lua:736: attempt to index a nil value` when you clicked the mouse before this all started

**Comment by bigjoker76** [comment]
You were right...AI was the bad guy. Thank you for your help
