### ISSUE TITLE
Horsch Maestro 12SW 

### ISSUE THREAD

**Issue by Toys7505** [Courseplay/courseplay#1946]
I'm having a slight issue with this seeder (Horsch Maestro 12SW). This seeder is capable of seeding and fertilizing at the same time. My issue happens when I just want Courseplay to seed only and not use the fertilizer function. When I generate my course and get everything set and tell the tractor to start. I get a RED popup stating the seeder needs to be refilled. Mind you, the seed capacity is 100% full. How do I get Courseplay to use it as a seeder only? Is there a button I'm missing to toggle on/off?

Appreciate your efforts - this MOD RIPS!!!
Toys

**Comment by sootysax** [comment]
Thats what the ProSeed mod is for

**Comment by pops64** [comment]
Your not missing a button it is hard coded that if there is no fertilizer present but the fill level exist for fertilizer it must be filled.

**Comment by Toys7505** [comment]
Ahhhhh - ok, I'll have to check out this ProSeed mod you speak of sootysax
and thanks for the clarification pops64 - appreciate it
Thanks,
Toys
