### ISSUE TITLE
Can't stop drivers

### ISSUE THREAD

**Issue by SteelAnxiety** [Courseplay/courseplay#1947]
After telling the driver to drive the course, pressing stop driver does nothing and gives this error message

Error: Running LUA method 'mouseEvent'.
C:/Users/steve/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/start_stop.lua:650: attempt to index global 'vehicle' (a nil value)

Version: 5.01.00110 downloaded today

Issue replicated on several different maps

[log.txt](https://github.com/Courseplay/courseplay/files/884429/log.txt)

**Comment by yan24** [comment]
Hello, 
I have the same problem since I installed the version 5.01.00110. 
Thank you for your work.

**Comment by Satissis** [comment]
Fixed in v01.00111.
