### ISSUE TITLE
index local ids nil

### ISSUE THREAD

**Issue by genen** [Courseplay/courseplay#1948]
getting a bunch of these 
Error: Running LUA method 'update'.
dataS/scripts/utils/FSUtils.lua(844) : attempt to index local 'ids' (a nil value)
Error: Running LUA method 'update'.
dataS/scripts/utils/FSUtils.lua(844) : attempt to index local 'ids' (a nil value)
Error: Running LUA method 'update'.

when running for 5-10 min on plow created scanned fields 
map was kleinhau using stock Case Puma

**Comment by Satissis** [comment]
Hi @genen 
are you sure this is related to CP ?
Those errors are Giants own script that throws out an error, but it do not tell where is origin from.
An full log would also be nice. either post the log file on gist or drag it into the text editor here to upload it.

**Comment by genen** [comment]
video at https://youtu.be/as1silhFHcs
[log - Copy (2).txt](https://github.com/Courseplay/courseplay/files/894957/log.-.Copy.2.txt)
dataS2/character/pedestrians/woman06.i3d (52.60) ms
dataS2/character/pedestrians/man06.i3d (2.71) ms
dataS2/character/pedestrians/man01.i3d (2.50) ms
dataS2/character/pedestrians/man02.i3d (3.21) ms
[dbg14 lp29434] GTXM Big M (#1): curStage=2, refSpeed=10.00, curSpeed=2.33 -> setSlippingStage 1
[dbg14 lp29434] GTXM Big M (#1): setSlippingStage(..., 1)
[dbg14 lp29440] GTXM Big M (#1): setCustomTimer(..., "slippingStage2", 3)
[dbg14 lp29446] GTXM Big M (#1): curStage=1, refSpeed=10.00, curSpeed=2.55 -> resetCustomTimer(..., "slippingStage2")
[dbg14 lp29463] GTXM Big M (#1): setCustomTimer(..., "slippingStage2", 3)
[dbg14 lp29573] GTXM Big M (#1): timerIsThrough(..., "slippingStage2") -> setSlippingStage 2, reset timer
[dbg14 lp29573] GTXM Big M (#1): setSlippingStage(..., 2)
[dbg14 lp29598] GTXM Big M (#1): curStage=2, refSpeed=10.00, curSpeed=2.31 -> setSlippingStage 1
[dbg14 lp29598] GTXM Big M (#1): setSlippingStage(..., 1)
[dbg14 lp29605] GTXM Big M (#1): curStage=1, refSpeed=10.00, curSpeed=3.70 -> setSlippingStage 0
[dbg14 lp29605] GTXM Big M (#1): setSlippingStage(..., 0)
[dbg14 lp29654] GTXM Big M (#1): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp29745] GTXM Big M (#1): timerIsThrough(..., "slippingStage1") -> setSlippingStage 1, reset timer
[dbg14 lp29745] GTXM Big M (#1): setSlippingStage(..., 1)
[dbg14 lp29746] GTXM Big M (#1): setCustomTimer(..., "slippingStage2", 3)
[dbg14 lp29836] GTXM Big M (#1): timerIsThrough(..., "slippingStage2") -> setSlippingStage 2, reset timer
[dbg14 lp29836] GTXM Big M (#1): setSlippingStage(..., 2)
[dbg14 lp29852] GTXM Big M (#1): curStage=2, refSpeed=10.00, curSpeed=2.13 -> setSlippingStage 1
[dbg14 lp29852] GTXM Big M (#1): setSlippingStage(..., 1)
[dbg14 lp29860] GTXM Big M (#1): curStage=1, refSpeed=10.00, curSpeed=3.63 -> setSlippingStage 0
[dbg14 lp29860] GTXM Big M (#1): setSlippingStage(..., 0)
[dbg14 lp29928] Terra Variant 600 eco (#3): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp29939] Terra Variant 600 eco (#3): curStage=0, refSpeed=10.00, curSpeed=3.82 -> resetCustomTimer(..., "slippingStage1")
[dbg14 lp30165] TORUM 760 (#2): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp30216] GTXM Big M (#1): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp30248] TORUM 760 (#2): curStage=0, refSpeed=3.00, curSpeed=1.11 -> resetCustomTimer(..., "slippingStage1")
[dbg14 lp30306] GTXM Big M (#1): timerIsThrough(..., "slippingStage1") -> setSlippingStage 1, reset timer
[dbg14 lp30306] GTXM Big M (#1): setSlippingStage(..., 1)
[dbg14 lp30307] GTXM Big M (#1): setCustomTimer(..., "slippingStage2", 3)
[dbg14 lp30373] TORUM 760 (#2): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp30386] TORUM 760 (#2): curStage=0, refSpeed=10.00, curSpeed=3.60 -> resetCustomTimer(..., "slippingStage1")
[dbg14 lp30397] GTXM Big M (#1): timerIsThrough(..., "slippingStage2") -> setSlippingStage 2, reset timer
[dbg14 lp30397] GTXM Big M (#1): setSlippingStage(..., 2)
[dbg14 lp31041] GTXM Big M (#1): curStage=2, refSpeed=10.00, curSpeed=3.36 -> setSlippingStage 1
[dbg14 lp31041] GTXM Big M (#1): setSlippingStage(..., 1)
[dbg14 lp31042] GTXM Big M (#1): curStage=1, refSpeed=10.00, curSpeed=4.40 -> setSlippingStage 0
[dbg14 lp31042] GTXM Big M (#1): setSlippingStage(..., 0)
[dbg14 lp31121] GTXM Big M (#1): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp31211] GTXM Big M (#1): timerIsThrough(..., "slippingStage1") -> setSlippingStage 1, reset timer
[dbg14 lp31211] GTXM Big M (#1): setSlippingStage(..., 1)
[dbg14 lp31212] GTXM Big M (#1): setCustomTimer(..., "slippingStage2", 3)
[dbg14 lp31316] GTXM Big M (#1): timerIsThrough(..., "slippingStage2") -> setSlippingStage 2, reset timer
[dbg14 lp31316] GTXM Big M (#1): setSlippingStage(..., 2)
[dbg14 lp32960] Terra Variant 600 eco (#3): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp33054] Terra Variant 600 eco (#3): timerIsThrough(..., "slippingStage1") -> setSlippingStage 1, reset timer
[dbg14 lp33054] Terra Variant 600 eco (#3): setSlippingStage(..., 1)
[dbg14 lp33054] Terra Variant 600 eco (#3): set fourWheel to true
[dbg14 lp33055] Terra Variant 600 eco (#3): setCustomTimer(..., "slippingStage2", 3)
[dbg14 lp33066] Terra Variant 600 eco (#3): curStage=1, refSpeed=29.00, curSpeed=6.18 -> resetCustomTimer(..., "slippingStage2")
[dbg14 lp33071] Terra Variant 600 eco (#3): curStage=1, refSpeed=29.00, curSpeed=10.56 -> setSlippingStage 0
[dbg14 lp33071] Terra Variant 600 eco (#3): setSlippingStage(..., 0)
[dbg14 lp33165] GTXM Big M (#1): setSlippingStage(..., 0)
[dbg14 lp33204] Terra Variant 600 eco (#3): set fourWheel to false
[dbg14 lp33347] Terra Variant 600 eco (#3): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp33366] Terra Variant 600 eco (#3): curStage=0, refSpeed=24.00, curSpeed=8.52 -> resetCustomTimer(..., "slippingStage1")
dataS2/character/pedestrians/woman04.i3d (3.33) ms
[dbg14 lp33416] GTXM Big M (#1): set diffLockFront to false
[dbg14 lp33416] GTXM Big M (#1): set diffLockBack to false
[dbg14 lp34163] GTXM Big M (#1): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp34193] GTXM Big M (#1): curStage=0, refSpeed=20.00, curSpeed=7.05 -> resetCustomTimer(..., "slippingStage1")

**Comment by genen** [comment]
Hey I think I added this to the wrong incident... This was meant to be sample of 4WD not activating and getting stuck
