### ISSUE TITLE
Mod8 liquid Manure and Water Never Unload at waiting point

### ISSUE THREAD

**Issue by bibifr** [Courseplay/courseplay#1951]
Hello dear,

Before post i tried multiple solution but nothing worked.

Im using The Mod FS17_kotteUniversalPack To Transfert or Sell Liquide manure and Water to Animal

But for a Unknow reason They Stop at Waiting Point Made on Tigger and they never unload. 
I have To stop Course Push I key to unload and Start again to Do it myself 

Some Picture

Water To Animal
![fsscreen_2017_04_01_20_45_19](https://cloud.githubusercontent.com/assets/9522188/24581468/29fe369e-171c-11e7-9787-fa4e5119e552.png)

Liquide Manure
Arrived at Waypoint
![fsscreen_2017_04_01_20_47_25](https://cloud.githubusercontent.com/assets/9522188/24581482/7032c904-171c-11e7-83ae-997c921e4c58.png)
At same Spot Stop and pressing I to Unload
![fsscreen_2017_04_01_20_47_31](https://cloud.githubusercontent.com/assets/9522188/24581483/70361f1e-171c-11e7-9bcb-1065d571f753.png)

Thanks you for any help :)

**Comment by pops64** [comment]
Selling Liquid manure is unsupported at this time see #1760. As for the water we will look into it when we get the time

**Comment by bibifr** [comment]
Thanks you I will look at this :)

**Comment by pops64** [comment]
Test with v01.0115 and report back for liquid manure sell trigger. Filling water with this mod might not be possible has it may break the liquid manure function of this mod when using it with CP

**Comment by bibifr** [comment]
Hello Mate, 

Liquid Manure Works perfectly They Fill and Unload Whitout any issue for me. 

Well Done :)

**Comment by pops64** [comment]
For the water it should unload automatically I would suggest moving your wait point a little more forward. It has to be the in the trigger just right or it won't do anything

**Comment by bibifr** [comment]
My Main issue was related to Liquid Manure Trigger. But Water Was not unloading too so i asked it too! But as i noticed Water working whit Zunha...(something name) Trailer That works like a charm. 
I will try maybe Milk to check :)

**Comment by pops64** [comment]
Test with v01.00116 and report back. Water troughs should now work with this mod

**Comment by bibifr** [comment]
Everything Working Like a charm mate :)

Thanks you and Awesome works ;)
