### ISSUE TITLE
Manual work width increment

### ISSUE THREAD

**Issue by Xandoria** [Courseplay/courseplay#1953]
I want to bale straw from the field. My combine's work width is 13.2 m. When I come with the tractor and the baler, it is not possible to set 13.2 m manually for the work width (only 13.0 m or 13.5 m)
Could you please modify the work width increment?

**Comment by Zoochase** [comment]
Reduce the combine to 13.  More coverage with lower possibility of missing anything and that makes it the ideal width for the baler.  My suggestion.

**Comment by pops64** [comment]
hold the alt key down to change by .1m when above 10
