### ISSUE TITLE
Error: Running LUA method 'update

### ISSUE THREAD

**Issue by Liquid515** [Courseplay/courseplay#1954]
D:/Mods/ZZZ_CoursePlay/drive.lua:13: attempt to index field 'currentHelper' (a nil value)
Error: Running LUA method 'update'.

**Comment by Liquid515** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/888489/log.txt)

**Comment by Liquid515** [comment]
also when I download the new courseplay master should I make a new zip or is it ok to update  the one I have made

**Comment by pops64** [comment]
I would start by disabling all mods beside course play and your map. My guess is that consoleExtension is the mod that is breaking CP has it throws a call stack on load. You should also always start with a new zip http://courseplay.github.io/courseplay/en/installation/index.html

**Comment by Liquid515** [comment]
might have solved that I created new courseplay zip and also changed my mods folder back to  the original place ..and ben running it since I posted and no errors came up

**Comment by pops64** [comment]
I go and close this. Post here if you run into the issue again and I will reopen
