### ISSUE TITLE
Overloader will not unload

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1955]
https://www.dropbox.com/s/75sb1qrc4g0bj79/2017-04-02_144031771.mp4?dl=0

https://gist.github.com/sootysax/369baef729146a2863c359886a2043bc

Overloader stopping at waiting point next to trailer and shuts off engine and goes to sleep...

Stopping CP and hitting R to unload reveals correct positioning..

**Comment by pops64** [comment]
I would say try getting your pipe closer has it may not be close enough for it to automatically do it.

**Comment by sootysax** [comment]
https://www.dropbox.com/s/3oz4xh3eanbzwzd/2017-04-02_150657352.mp4?dl=0

**Comment by sootysax** [comment]
It is a conflict with the CombineAddOn mod which has a "manual pipe unload" toggle on/off that also affects auger wagons... it seems to get reset when CP runs a course.
