### ISSUE TITLE
Turn issue sprayer (NH SP400F)

### ISSUE THREAD

**Issue by SkiiBlock** [Courseplay/courseplay#1957]
When the sprayer reach the end of the field, he is not turning fine and continue on a random way in the field. I don't see if this was reported before so I decide to do it. Maybe it's a bug or maybe it's my game, I don't know so I prefer post it :)

Here is the video : https://www.dropbox.com/s/7crioihgnrlpwdq/Farming%20Simulator%202017%2004.03.2017%20-%2021.08.57.41.mp4?dl=0

Here is the log : https://pastebin.com/KbJbp5tF

**Comment by Satissis** [comment]
Looks like it missed an turn waypoint when it did that. I'll need to see if I can reproduce it, to be able to fix it

**Comment by Thomasovo** [comment]
Same problem. CP 5.01.00089 is last version which works correctly.

**Comment by Blackmankot** [comment]
@pops64 I suggest also close it for cleaning.

**Comment by pops64** [comment]
Closed #2909
