### ISSUE TITLE
Mode1 - Liquid manure load not working

### ISSUE THREAD

**Issue by Brzzl** [Courseplay/courseplay#1958]
Hi Guys!

First let me say thanks for your great work! w/o CP FS wouldn't be the same!

Unfortunately I have to report a bug, concerning mode1 and liquid manure loading, which isn't working.

In my video you can see, that I have about 3k LM in the slurry pit, but CP won't load (though it says, it is loading). When pressing "R" it fills up the tank. Using only stock equipment. 

https://www.youtube.com/watch?v=YMHzj7GKkB8

Any suggestions? :)

**Comment by jbellfarmer687** [comment]
You are using the wrong made. You are using the grain transport mode. You need to use the 3rd to last mode (I can't remember the name off the top of my head, it's something like manure transport or something like that) and that is specifically designed for hauling manure. Unless if something changed in later updates, it is that third to last mode.

**Comment by pops64** [comment]
Has @jbellfarmer687 said you need to be in mode8 which is now called Liquid Transport Mode, Mode 1 is grain/solids transport. If your having issues with mode8 selling liquid manure and your in v00115 or above please post your issues in either #1760 #1951. Closed to keep issues are clean
