### ISSUE TITLE
Mode 9 Maybe Issue

### ISSUE THREAD

**Issue by bibifr** [Courseplay/courseplay#1961]
Hello Dear, 

Im not sure if it's a bug or something bad i do but i noticed some week ago while doing Silage sell whit Mode9, The loaderwheel going left and rigth to remove every silage form silo. 

Today i do a silage and i noticed they never going left and rigth of silo 

2 Little pic to explain it more :)

![fsscreen_2017_04_05_09_49_41](https://cloud.githubusercontent.com/assets/9522188/24695935/09192154-19e8-11e7-8111-122603e6c8b0.png)
![fsscreen_2017_04_05_10_09_58](https://cloud.githubusercontent.com/assets/9522188/24695936/091cd6d2-19e8-11e7-9731-296431fd9f9a.png)

Maybe i have been done Something bad but in case i prefer to post for nothing.

Best regard

**Comment by Symbob** [comment]
When recording your course, try setting the first wait point closer to the bunker.

**Comment by bibifr** [comment]
That exactly The problem Here :P 
Thanks you it's better now ;)

Closed
