### ISSUE TITLE
Bug in Game Causing Freezing

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#1964]
im getting this message in game and it causes the game to freeze causing the game to close please help .....C:/Users/matty/OneDrive/Documents/My Games/FarmingSimulator2017/mods/courseplaymaster/toolManager.lua:1245: attempt to index local 'trigger' (a nil value)
Error: Running LUA method 'update'.

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki full log. what were doing to cause this?

**Comment by matty2123** [comment]
I'll gather log when I'm next on pc. I was about to sow a field when the tractor zoomed off and the game crashed checked log had loads of them errors.

**Comment by Blackmankot** [comment]
@pops64 Can this issue be closed? To cleanse the topic.

**Comment by matty2123** [comment]
Yes sure

Sent from my iPhone

On 29 Apr 2017, at 02:04, Aleksandr <notifications@github.com<mailto:notifications@github.com>> wrote:


@pops64<https://github.com/pops64> Can this issue be closed? To cleanse the topic.

**Comment by pops64** [comment]
Alright. Thanks for the response
