### ISSUE TITLE
Fertilizer and seeding by colsplay

### ISSUE THREAD

**Issue by Blackmankot** [Courseplay/courseplay#1966]
I suggest you add a paragraph - seeding without fertilizer. Often the fields are fertilized and only requires sowing. And all seeders with the function of fertilizer. Thank you very much for Your work! Sincerely, Alexander.

**Comment by pops64** [comment]
The proseed mod will let you disable fertilizer with sowing machines

**Comment by Blackmankot** [comment]
@pops64 For a long time I want to ask you! It's true that you are involved in creating a game Cattle and Crops?

**Comment by pops64** [comment]
Nope. I do not who is involved in that project.

**Comment by Blackmankot** [comment]
I understand you, thank you! If the authors implement everything that they said, then the game Cattle and Crops will be a serious competitor to the farm.
