### ISSUE TITLE
Download from the conveyors.

### ISSUE THREAD

**Issue by Blackmankot** [Courseplay/courseplay#1967]
Good afternoon! There was a problem. Starting from version 5.01.00114 the transport stopped loading on the approaching course from the conveyors. And it was very convenient, you can write courses to download each culture, and go one course at a time. Less courses with this scheme are required. I apologize for the translation of Google.

![2017-04-11_09-22-05](https://cloud.githubusercontent.com/assets/26131714/24889870/33421164-1e9f-11e7-9451-452b9c293571.jpg)
![2017-04-11_09-19-00](https://cloud.githubusercontent.com/assets/26131714/24889883/43065632-1e9f-11e7-8d84-cad3b3517fc6.jpg)
![2017-04-11_09-26-20](https://cloud.githubusercontent.com/assets/26131714/24889894/4f0a4b8c-1e9f-11e7-9c81-f6caf4624cba.jpg)

**Comment by Blackmankot** [comment]
@Satissis I wonder your opinion.

**Comment by pops64** [comment]
I would have to say that the fill type of one of the two converyors in front of the truck is does not match what was inputted into mode 1 on start up

**Comment by Blackmankot** [comment]
@pops64 I attach detailed photos so that you do not think that I'm not correctly creating courses. Courses are written in version 5.01.00090. Works great!
![2017-04-15_12-50-10](https://cloud.githubusercontent.com/assets/26131714/25061037/9b1acea0-21df-11e7-8e84-6900472cbe6c.jpg)
![2017-04-15_12-52-54](https://cloud.githubusercontent.com/assets/26131714/25061040/b34d4048-21df-11e7-9086-e253a47d42c3.jpg)

In version 5.01.00094 it works fine.
![2017-04-15_13-04-54](https://cloud.githubusercontent.com/assets/26131714/25061062/3739e230-21e0-11e7-831c-e266031e70e3.jpg)
![2017-04-15_13-05-31](https://cloud.githubusercontent.com/assets/26131714/25061063/3dcdd2d2-21e0-11e7-89b2-bf6ded58ebf6.jpg)

And in version 5.01.00097 it works fine.
![2017-04-15_13-12-15](https://cloud.githubusercontent.com/assets/26131714/25061079/7e1ce1ac-21e0-11e7-929b-057b7e6628f1.jpg)
![2017-04-15_13-14-01](https://cloud.githubusercontent.com/assets/26131714/25061080/836636b8-21e0-11e7-98d5-a5c909c17459.jpg)

And in version 5.01.00101 it works fine.
![2017-04-15_10-14-32](https://cloud.githubusercontent.com/assets/26131714/25061103/fbf085d4-21e0-11e7-92dd-db03e3b1cab8.jpg)
![2017-04-15_10-16-57](https://cloud.githubusercontent.com/assets/26131714/25061105/0159fa78-21e1-11e7-8a8c-e197f5879b2a.jpg)

In version 5.01.00114 with the same courses does not work.
![2017-04-15_10-22-49](https://cloud.githubusercontent.com/assets/26131714/25061169/e160ff80-21e2-11e7-95d0-cab2d536ab4a.jpg)
![2017-04-15_10-25-20](https://cloud.githubusercontent.com/assets/26131714/25061172/e7675c76-21e2-11e7-8d95-f67780d10f77.jpg)

In version 5.01.00116 with the same courses does not work.
![2017-04-15_10-30-54](https://cloud.githubusercontent.com/assets/26131714/25061177/04dfc2f2-21e3-11e7-8f24-7b963ec3b9bc.jpg)
![2017-04-15_10-33-43](https://cloud.githubusercontent.com/assets/26131714/25061180/0b99f0a4-21e3-11e7-841a-bc42cd3e9432.jpg)

What are the reasons for such changes? Now I will have to write new courses ... And there are a lot of courses ...

**Comment by Satissis** [comment]
The reason it's doing that now, is that the trailer still have the fill trigger of the conveyor at the back, when it changed to waypoint 1, so it thinks that it's the conveyor behind it needs to use and since that one is behind the middle of the trailer, it will stop and wait.

I might be able to add an code in so it will continue moving forward, if the fill type is the wrong one if it's possible, since it could easily break how other things works.

**Comment by Blackmankot** [comment]
@Satissis Excellent! Thank you!

**Comment by Blackmankot** [comment]
@Satissis Excellent! Thank you!

**Comment by Blackmankot** [comment]
@Satissis Good afternoon. On this issue have already been made changes or not.

**Comment by pops64** [comment]
There have been non changes to this yet. Satissis will post here when he makes a push concerning this issue.

**Comment by Blackmankot** [comment]
@pops64 Thank you.

**Comment by Blackmankot** [comment]
@pops64 I wanted to help with questions for the purity of the topic.

**Comment by Blackmankot** [comment]
@pops64  @Satissis When to expect changes on this issue?
