### ISSUE TITLE
Overloading Mode

### ISSUE THREAD

**Issue by meisterjk** [Courseplay/courseplay#1969]
Hi i'm use your latest Version (5.01.0116) with the AIVehicleExtension.

The issue is, that cp in Overloading Mode after some drives to the Combines don't allow to drive foward again. 

I'm use the two Claas Lexion 700 STAGE IV Pack with one MF7726 + Bergmann GTW430
After serveral time drive the tractor to the combine but when the combine is empty he doesn't drive forward again. i have to send them manually away to empty the GTW. My helper is the actual Version of the AIVehicleExtension.

My other little issue is, when a combine self drive to a trailer. The light doesn't work. at night the light is off.

thanks and greetings

**Comment by pops64** [comment]
See #1701. Aivehicle is not supported at this time
