### ISSUE TITLE
Forklift Trailer

### ISSUE THREAD

**Issue by Blackmankot** [Courseplay/courseplay#1970]
Good afternoon. Another problem with the trailer is an overloader. When the vehicle approaches the waiting point and has a pipe above the trailer, unloading does not take place and the transport does not move, waiting for unloading. If you stop the execution of the program on the course, the download will not start until the R key is pressed. All trailers defaulted from the game. Versions 5.01.00116 and 5.01.00097.

![2017-04-11_15-58-26](https://cloud.githubusercontent.com/assets/26131714/24899500/13812534-1ed3-11e7-8caa-faa027fc24d2.jpg)

![2017-04-11_15-59-25](https://cloud.githubusercontent.com/assets/26131714/24899580/66f042f4-1ed3-11e7-9c26-cfe8284b30da.jpg)

![2017-04-11_16-03-25](https://cloud.githubusercontent.com/assets/26131714/24899591/6c4d8504-1ed3-11e7-97cf-45f03be38113.jpg)

![2017-04-11_16-02-43](https://cloud.githubusercontent.com/assets/26131714/24899598/7245a428-1ed3-11e7-9414-d9adb90ceedc.jpg)

**Comment by pops64** [comment]
See #1955 are you using the same mod. Has this is unsupported

**Comment by Blackmankot** [comment]
@pops64 Good afternoon! Thanks for the information, unloading on courseplay is performed! Thank you for your work!
![2017-04-12_15-24-55](https://cloud.githubusercontent.com/assets/26131714/24946629/1bd02334-1f96-11e7-8740-e149a83d120d.jpg)

**Comment by pops64** [comment]
Closed to keep issues area clean
