### ISSUE TITLE
scrolling with mousewheel in cp zoom the view

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#1973]
Hey guys
i use cp in v 01.0116 and now i see that, when i scroll the mousewheel in cp (workwide or fieldnumber),
also the zoom the view (to or from the tractor)
in further versions this was not so

hallo leute
ich verwende cp in derversion 01.0116 und habe nun bemerkt, das das benutzen des mausrades in cp (arbeitsbreite verändern, feldnummern durchscrollen,..)gleichzeitig auch den Fahrzeugzoom verändert.
das war in den vorherigen versionen nicht so.

lg
andreas

**Comment by pops64** [comment]
Is the mouse cousrer showing when you zoom?

**Comment by andreasthu** [comment]
ok, i tried the cp version 01.0111 - the same here
and i have no new mods in last time installed.
only what i have the last two weeks.
and yes, i see the mouse coursor from cp
only what is, my mouse (logitech G700s) updatet the driver
now i have the logitech gamingsoftware 8.91.48
can this be the problem?
and should i reinstalling an older version
(i dont know what version number i used the last time but i can trie this)
lg
andreas

**Comment by andreasthu** [comment]
i testet in now with 2 older versions from LogitechGamingSoftware
LGS_8.89.68_x64_Logitech
and
LGS_8.88.30_x64_Logitech

the vehicle zoom when i scroll the mousewheel in CP is always here.
i attach two pics, first with smal workwide(yellow arrow)  and far zoom, than with widerworkwide with mouseweel scrolling and the vehiklezoom is too near now
you can see the cp-mousesymbol on both pics (red arrow)
![wide](https://cloud.githubusercontent.com/assets/24860501/24995042/95ce408e-202d-11e7-879a-163a8c10bc54.png)
![near](https://cloud.githubusercontent.com/assets/24860501/24995047/97ae9ea8-202d-11e7-891d-99fc695b513f.png)

any suggestion?

lg
andreas

**Comment by pops64** [comment]
Do you have any mods that require a mouse cousrer? Try disabling them has they tend to interfere because of keybindings

**Comment by andreasthu** [comment]
hi
now i startet the game, only with the modmap (dreisternhof v1.4 plus) and courseplay.
the same, vehiclezoom when use mousewheel in cp.
then i tried  a other map, my sosnovka mod map and the dreisternhof v1.2, and what should i say,
there i hadn´t this problem - the vehicle zoom is not existant when i scroll the mousewheel in cp.
with other mods or only the modmaps and courseplay
but when i startthedreisternhof plus 1.4 map then i have the vehicle zoom problem with and without other mods
here the link:
https://www.modhoster.de/mods/dreistern-hof
any idea, what is in this map to use mouse?
lg
andreas

**Comment by andreasthu** [comment]
ok, i have detect the reason
it is, when i built in the "schlamm" (english: mud) in the map
http://marhu.net/phpBB3/viewtopic.php?p=82499#p82499
i have load a backup from the map before buit in the "schlamm" and there cp works normal.
i understand this not.
in this schlamm is no mouseaction in.
i will now play the backup version from the map before the schlamm.
even i find a solution for this

lg
andreas

**Comment by Satissis** [comment]
Thanks for letting us know.

Also, let us know what the modder on Marhu says about it when they reply to your problem.

**Comment by andreasthu** [comment]
ok, i think there come nothing
they said that the russion script is saved.
i build out the mud and play now without mud 
cp is for me absolutly the first choice of mods
lg
andreas

**Comment by Blackmankot** [comment]
@Satissis Can this issue be closed? To cleanse the topic.

**Comment by andreasthu** [comment]
oh yes, you can close it.
no answer from the mud-modder.
i deleted the mud mod from my map and now cp works still fine as it should

lg
andreas

**Comment by andreasthu** [comment]
sorry, for reopening
played LS17 with cp now i while
but since a pair weeks i play the gorzkowa map
https://www.modhoster.de/mods/gorzkowa_v3_2k17
it is a old style dirty map, and here is the mod essenciell for feeling
but the zoom is always not safe, every time i scroll the mousewheel, in workingwide, fieldnumbers,...
the vehiclezoom is disguised
is there a chance in comming cp versions that this is fixed?
i realise that this is not a cp problem, but ths comes only when cp is used in a map who mas dirt inbuild.
have some other people the same problem, or i am alone with?

lg
andreas

**Comment by andreasthu** [comment]
Hey  pops64.
Need you more info about?
Or only forgottten to delete the label waiting for user answer?
Lg
Andreas

**Comment by pops64** [comment]
No just forgot

**Comment by pops64** [comment]
Closing this out merged it into #2231
