### ISSUE TITLE
funny "unterstützt produkttyp nicht"

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#1974]
Hello guys
i had a funny Situation now.
first, i edited the giants placeable hayloft, to fill in straw, gras, chaff, woodchips and drygras.
i bunkered so 500000 lt woodchis i nthe hayloft.
now i drive in a selling course (mode1) from the hayloft to the heatingpowerplant.
i sell over 350000liters in my last savegame.
i startet the savegame new, there was 150000lt in the hayloft.
i start the course, Chose woodchips as loadet fruit and the Traktor drive under the loadingpipe and the message apears that the Station the selectet fruit not supports.

what is wrong (cp 01.0116)

lg
andreas

**Comment by andreasthu** [comment]
Ok sorry.
Problem is no longer.
A new gamestart and cp runs  now normal and load the woodchipsl
Lg
Andreas

**Comment by pops64** [comment]
Closed to keep issues area clean
