### ISSUE TITLE
Sowing

### ISSUE THREAD

**Issue by Blackmankot** [Courseplay/courseplay#1977]
Good day! I have a proposal - Make a switchable fertilizer control in thе seeder. Here is an example: the field is already fertilized and you only need to sow the wheat. I seed the seeder, turn off the fertilizer control level in the menu of the course and start it. Kursplay will only report that the seeds have run out and stop the course. A fertilizer bunker during the sowing will all the time empty. I wonder your opinion.

**Comment by pops64** [comment]
Has I mentioned in your other post the proseed mod will allow you to do this. It is available through Giants official mod website. Closed to keep issues area clean

**Comment by Blackmankot** [comment]
@pops64 Thank you, downloaded mod-Proseed, he disappointed me, he works only with a mercenary ... The mercenary is very stupid, does not say that the bunker is empty, will not replenish the bunker at an additional route and will not prolong the work. On the courseplay this is all implemented better. It is a pity that you do not want to add to the courseplay my offer...

**Comment by pops64** [comment]
I will add this to our tracker and when we get free time we will look into adding this. Part the problem is were running out of space on the hud

**Comment by Blackmankot** [comment]
@pops64  Thank you!!! I am very happy! Sorry for perseverance, I really like the course! And I want this mod to get even better! Thank you for attention!

**Comment by Blackmankot** [comment]
@pops64 Thank you very much! I am very glad that you realized my request!
![2017-10-08_23-35-07](https://user-images.githubusercontent.com/26131714/31318328-fb9c0f2c-ac82-11e7-9d27-86b4b666d2a5.jpg)
