### ISSUE TITLE
Courseplay not showing up in mods list

### ISSUE THREAD

**Issue by Darkseiders** [Courseplay/courseplay#1978]
I downloaded the mod from here: [ModHoster](https://www.modhoster.com/mods/courseplay--32) and it didn't show up in my select mods list when I load a savegame. I also tried using the developer version, which didn't work either. [Log](https://github.com/Courseplay/courseplay/files/922973/log.txt)

**Comment by sootysax** [comment]
you're trying to use Courseplay for FS15 in FS17

**Comment by pops64** [comment]
http://courseplay.github.io/courseplay/en/installation/index.html closed to keep issues area clean
