### ISSUE TITLE
The problem with the item is the position of the pipe.

### ISSUE THREAD

**Issue by Blackmankot** [Courseplay/courseplay#1979]
Good afternoon.
1 . If I understand correctly, then the point of the pipe position should appear only with point 3 (work with the trailer overloader). Should he be present with point 1? On the picture.
![2017-04-16_00-00-09](https://cloud.githubusercontent.com/assets/26131714/25065535/4aaa6330-2244-11e7-8fa4-5cfe2a624b69.jpg)
![2017-04-16_00-02-02](https://cloud.githubusercontent.com/assets/26131714/25065537/4eb846c2-2244-11e7-95b7-3a0845179eb9.jpg)
2 . From the version of course 5.01.00101 this item appears in trailers that do not have a pipe. Here is an example - in version 5.01.00097 the trailer and Ural on point 1 work perfectly.
![2017-04-15_19-22-38](https://cloud.githubusercontent.com/assets/26131714/25065625/9960bd48-2245-11e7-8a95-c903ed29db48.jpg)
![2017-04-15_19-41-40](https://cloud.githubusercontent.com/assets/26131714/25065632/a56799b8-2245-11e7-8bfb-5793090a545f.jpg)
![2017-04-15_21-14-32](https://cloud.githubusercontent.com/assets/26131714/25065640/b7d34f70-2245-11e7-8a7d-c2a4984594a7.jpg)
![2017-04-15_21-16-10](https://cloud.githubusercontent.com/assets/26131714/25065644/c1ed9768-2245-11e7-93fd-92afb4816c30.jpg)
![2017-04-15_21-21-16](https://cloud.githubusercontent.com/assets/26131714/25065658/dd0aa518-2245-11e7-999b-0747b077d345.jpg)
![2017-04-15_21-25-40](https://cloud.githubusercontent.com/assets/26131714/25065659/e64a192e-2245-11e7-9cd0-5afbc9961372.jpg)
Here is the result with the version 5.01.00101, 5.01.00114, 5.01.00116 in the photo.
The first trailer continues to work without problems.
![2017-04-15_22-55-43](https://cloud.githubusercontent.com/assets/26131714/25065724/edf8ea3c-2246-11e7-90ee-8d51a1aa5678.jpg)
![2017-04-15_22-58-05](https://cloud.githubusercontent.com/assets/26131714/25065725/f30d0a6c-2246-11e7-9799-ebd5b341e244.jpg)
 These trailers and the Urals are no longer moving on the course.
![2017-04-15_22-31-31](https://cloud.githubusercontent.com/assets/26131714/25065742/836bffdc-2247-11e7-8629-1b6e19af6ca5.jpg)
![2017-04-15_22-49-54](https://cloud.githubusercontent.com/assets/26131714/25065746/8db6da0c-2247-11e7-98c3-a605e987870c.jpg)
![2017-04-15_21-41-07](https://cloud.githubusercontent.com/assets/26131714/25065752/98e7f96a-2247-11e7-898d-73b6d46951dc.jpg)
![2017-04-15_22-29-30](https://cloud.githubusercontent.com/assets/26131714/25065756/9fa93b7e-2247-11e7-95d9-08bd26f6bad3.jpg)
![2017-04-15_18-30-49](https://cloud.githubusercontent.com/assets/26131714/25065766/cc7bb0fa-2247-11e7-87c5-b5b1b0cfdf9c.jpg)
![2017-04-15_18-49-27](https://cloud.githubusercontent.com/assets/26131714/25065769/cff97302-2247-11e7-96af-82200222255e.jpg)
Here is the log. 
[log.txt](https://github.com/Courseplay/courseplay/files/923782/log.txt)
  All presented trailers transport these products: sugar, packed_seed_oil, konditer, sweetmilk, beer, canning, wool, bread, wheatflour, ryeflour, maizeflour, packed_milk, furniture.

**Comment by Satissis** [comment]
in v01.00101 allot of small changes was made.
which made you able to use an overloader in mode 1.
however that line to save the pipe position should only if the vehicle or trailer have the vehicle type name: `augerWagon` or have the type name: `FS17_kotteUniversalPack.kotteUniversal` or has the `Overloading` specialization, so I'm guessing that those mods have one of those 3 set, which I believe might be wrong, when they ingamed the mod.

Can you confirm that ?

**Comment by Blackmankot** [comment]
@Satissis Good afternoon. In order not to mislead you, download the link: Ural, Ural with trailer, food trailer, cistern. You know better where to look. Thank you for attention.
https://yadi.sk/d/3hBdC7_w3H35mb

**Comment by Satissis** [comment]
I had an look at the 4 zip files you send me.
all of those mods are using the overloading specialization in them, except the Bochka.zip

**Comment by Blackmankot** [comment]
Tell me please how to fix it? What and where to change? So I told the authors.

**Comment by Blackmankot** [comment]
@Satissis Tell me please how to fix it? What and where to change? So I told the authors.

**Comment by Satissis** [comment]
in the 3 zip files, that I found it in, the `Overloading` specialization is found in the modDesc.xml
I didn't find any reference for them to be used in the mods, so he should be able just to disable that line.

I didn't take an deep look thou, so not sure if one of them should have it.

**Comment by Blackmankot** [comment]
@Satissis Thank you very much! Everything works fine! :)) The issue is resolved. Question close.
