### ISSUE TITLE
Freezing after setting up course v5.01.00116

### ISSUE THREAD

**Issue by eddiem54** [Courseplay/courseplay#1980]
https://gist.github.com/anonymous/f3938659b76cad47888a3e5e3686297d
Showing a distance in metres at bottom left corner of HUD.
Tabbing through vehicles shows the CP one as having a Helper although course is deleted.
Tried with 3 different maps.

**Comment by pops64** [comment]
What were you doing when you produced this error? How did you setup your course https://github.com/Courseplay/courseplay/wiki

**Comment by Satissis** [comment]
I just had an look at what that line was in the error.
It's because an liquid manure overloader are missing the unloadTrigger on it.

I'll add in a check for it and if it's missing, just skip it.

Update coming in less than 5 min.

**Comment by Satissis** [comment]
Try again with v01.00119 or higher and report back.

**Comment by eddiem54** [comment]
Using v5.01.00119, seems OK using same maps and eqpt. 
Thank You.

**Comment by pops64** [comment]
closed to keep issues area clean
