### ISSUE TITLE
Lelly 150 with courseplay 

### ISSUE THREAD

**Issue by criss20ster** [Courseplay/courseplay#1984]
Hey. I have such a question for you. Would you be able to infuse this mess with the lellum 150 under the courseplay?

http://screenshot.sh/oAE55pdqNYH4y

D: /ModyFS17/mods/FS17_lelyJuno150/lelyJuno150.i3d (64.44) ms
## Courseplay: Juno 150: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!

**Comment by pops64** [comment]
The above error is with the mod vehicle. This is something the mod arthor has to fix. There is nothing CP can do about it. You can edit that mod your self but this is not the place for that help. Closed to keep issues area clean.
