### ISSUE TITLE
Drive lua  trouble

### ISSUE THREAD

**Issue by criss20ster** [Courseplay/courseplay#1992]
Is there anyone who can tell me why now suddenly in Cp these errors appear I have 5.1.116 versions. And now as I have recorded the courses suddenly turn on log such errors.

Error: Running LUA method 'update'.
D:/ModyFS17/mods/ZZZ_CoursePlay_5_01_00116/drive.lua:13: attempt to index field 'currentHelper' (a nil value)

[log.txt](https://github.com/Courseplay/courseplay/files/933807/log.txt)

**Comment by pops64** [comment]
See #2037
