### ISSUE TITLE
LUAcallstack v 01.0125

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#1995]
Hello guys
have cp v 01.0125 now and a massive lua call stack problem with stockingframes in game when i unload at the hayloft:
```
set isTipping
Warning (LUA): 'getWorldTranslation': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
LUA call stack:
  =C:/Users/anthu/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/toolManager.lua (1508) : getWorldTranslation
  =C:/Users/anthu/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/toolManager.lua (1076) : manageCompleteTipping
  =C:/Users/anthu/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/mode6.lua (371) : unload_tippers
  =C:/Users/anthu/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/drive.lua (623) : handle_mode6
  =C:/Users/anthu/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/base.lua (888) : drive
  dataS/scripts/vehicles/Vehicle.lua (2598) : update
  dataS/scripts/network/Server.lua (56) : update
  dataS/scripts/BaseMission.lua (1508) : update
  dataS/scripts/FSBaseMission.lua (2171) : update
  dataS/scripts/missions/mission00.lua (333) : update
  dataS/scripts/main.lua (1876) : update
Warning (LUA): 'worldToLocal': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
LUA call stack:
```

i made a grass mower and nloading course with the profihopper mower, he mowe normale then he drive to the hayloft and when he stops to unlaoding the game has massive frametrops 1 or 2 per sec
here the complete log an attach
[log.txt](https://github.com/Courseplay/courseplay/files/940567/log.txt)

greets
andreas

lg
andreas

**Comment by andreasthu** [comment]
ok,have my latest version 01.0116 reinstalled
with this version the problems are not present
the profihopper unloads normal.
btw, the tractor with tippers unloads also in the version01.0125 without problems - only the profihopper
https://www.modhoster.de/mods/amazone-profihopper-2017-edition

lg
andreas

**Comment by ThomasGaertner** [comment]
try 132 or higher and report

**Comment by andreasthu** [comment]
thanks
works fine now with 01.0133

lg
andreas

**Comment by pops64** [comment]
Closed
