### ISSUE TITLE
reverse harvesting with mex5 with trailer

### ISSUE THREAD

**Issue by aBerek** [Courseplay/courseplay#1999]
Dear Developers,

Maybe its not an issue but I would like to find a solution to my problem:
I'm using a mex5 on a narrow, small field with a Schlüter 1500 in reverse driving mode. Actually helper in mode2 needs too much space to collect chaff so I attached a trailer to the tractor and using fieldwork mode with a transport route (2 combined route) to unload the chaff,

This is working fine until the first end of the first row. The tractor doesn't sense the trailer and doesn't make an 'omega turn' but after a 90 degree turn it starts reversing and runs into the trailer.

My question: Do you have any idea to handle this problem? (I've tried to increase the turning diameter but It didn't help)
Or if there's no proper solution I would like to suggest to put a button where the turning manouver could be changed from normal to omega turn.

Thanks Much!
BR,

**Comment by pops64** [comment]
Are you using a mod trailer? Have you tried with a different trailer. With standard trailers the Mex 5 should automatically use the omgea turn

**Comment by aBerek** [comment]
I'm using the standard metaltech db8.
The only mod is the tractor.

**Comment by pops64** [comment]
Try it with a standard tractor then.

**Comment by aBerek** [comment]
With a vanilla tractor, it works properly!
Thank you Guys!

**Comment by Blackmankot** [comment]
@pops64  I suggest closing it for order.

**Comment by pops64** [comment]
Collapsing mod issues into one thread. #2231 This mod isn't included because no mod name was given.  Post here if you would like this mod to be added to the list.
