### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jd6910s** [Courseplay/courseplay#2000]
Unable to  find mac osx installation link for regular version please help. Am a huge admirer of your work and have been using courseplay for years but i cant seem to download the fs2017 version. Would be very thankful if u could guide me through the installation process for v.5.01. Many thanks!

**Comment by Symbob** [comment]
Installation instructions for the Developer Version are available here https://courseplay.github.io/courseplay/en/installation/index.html

**Comment by pops64** [comment]
Has symbob said. Closed to keep issues area clean
