### ISSUE TITLE
Game freezes when tipping into Refinery (mods)

### ISSUE THREAD

**Issue by NataSpawN** [Courseplay/courseplay#2002]
Map: **Pine Cove Valley** (final 1.4)
Mods: **Krampe Bandit SB 30/60 + Attacher** (V1.0.0.0), **Refinery with Sales Trigger** (V2.0.0)

Issue:
Manually driving over the tip area and unloading works with no problems, allowing a course to drive over tip area and tip freezes the game (you can look around but no response from any type of input other than to look around - and it happens as soon as the tipper begins the tipping process)

Trigger for Error:
set isTipping

Error from Log:
Error: Running LUA method 'update'.
D:/FS17 Mods/Active Mods/NataSpawN Game Mods/LS17_Raffinerie_placeable_ModLandNet_2/Scripts/FabrikScript.lua:1326: attempt to compare number with table

This can be reproduced any time.  I had a similar issue with a private mod and ended up removing that mod and using the vanilla version.  I have no problem doing that with this one too, but wanted to let you know for troubleshooting reasons.  Let me know if you need anything else =)  And thanks for everything!  Definitely appreciate what you all do!

**Comment by pops64** [comment]
Well as you see from the tiny bit of log you provide. the set isTipping is just a regular print that wasn't turned off. The error that is breaking your game is with FabrikScript not CP. I know in the past FabrikScript and CP aren't compatible. I thought the author of FabrikScript had fixed this. Can we close here?

**Comment by NataSpawN** [comment]
Sure, it can be closed.  I didn't know which one was the cause.  Thanks for the quick reply =)

On a side note, just did a quick test with vanilla version of the tipper and CP didn't register a tip trigger at the Refinery.  Quick solve for that would be just create a manual tip point there (I would guess).

Anyway, thanks again!
