### ISSUE TITLE
New forager turn system is very good! (Not an issue)

### ISSUE THREAD

**Issue by Nordvarg** [Courseplay/courseplay#2003]
_(Not an issue, I know. Admin, just delete if you have to.)_

Have just done a short test of the new forager turn system. So far it’s revolutionary compared to the old system. Tractor backing up to harvester is really clever. Great work!

**Comment by Symbob** [comment]
I wouldn't say it's revolutionary as I've had a couple of occasions in odd shaped fields where the Tractor and trailer have crashed in to the forager while the forager is reversing to it's next start point (where the field boundary is at an angle and the next run is behind the forager).  If I can recreate the problem I'll post a picture.  I do think the new system is a step in the right direction though.  Maybe needs a bit of fine tuning, and I'm sure that will come in time.

**Comment by pops64** [comment]
Closed to keep issues area clean
