### ISSUE TITLE
Error: Running LUA method 'update'.

### ISSUE THREAD

**Issue by Symbob** [Courseplay/courseplay#2011]
While trying to take a few pictures of the collision between the tractor in Combi mode and the forager  that I mentioned in https://github.com/Courseplay/courseplay/issues/2003 I had another problem occur with the new turning system.  While attempting to turn the active tractor's path was taken in to the path of the waiting tractor that had moved from the course end point on to the field as it's Start at % had been reached (it was set at 80%).  I then stopped the active tractor, moved it away from waiting tractor then started it again.  At this point I was unable tab out of the active tractor and the game stopped responding.  The waiting tractor then moved to the forager but the forager wouldn't continue cutting.  I've included my log and you will see that it has this error repeated many times:

Error: Running LUA method 'update'.
C:/Users/Ian/Documents/My Games/FarmingSimulator2017/mods/zzz_courseplay/mode2.lua:238: attempt to index local 'combine' (a nil value)

If I stop the first tractor the forager and next trailer appear to continue working but will stop as soon as I try to start the first tractor again.  I also don't seem to be able to activate any debug channels.  I'm using v5.01.00129 on Goldcrest Valley using ingame equipment or Giants bonus content (Fendt 900 Black, Valtra T Series Cow Edition, Krone BigX 1100).

In the picture you will see that the Fendt's turn manoeuvre has been blocked by the waiting Valtra.  It was at this point that the problems started.  Unfortunately I couldn't take any further screenshots.

![fsscreen_2017_04_25_11_24_40](https://cloud.githubusercontent.com/assets/18528850/25382021/d28ec5dc-29ad-11e7-8f86-2aac53061f18.jpg)

[log.txt](https://github.com/Courseplay/courseplay/files/954721/log.txt)

Hope I've given enough detail.

**Comment by ThomasGaertner** [comment]
try again with v. 0133 or higher and report

**Comment by Symbob** [comment]
It's difficult to tell for certain, because it was a particular set of circumstances that caused this error originally, but I have now tried to replicate the issue using v.0133 and it appears to be working without problem.  Thanks for the fix!

**Comment by pops64** [comment]
Alright. Closed to keep the issues area clean
