### ISSUE TITLE
KUHN TF-1500

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#2012]
When the Kuhn TF-1500 additional capacity seed is attached, CP incorrectly changes the working width to 15m.  ver 1.00129

**Comment by sootysax** [comment]
this is still not quite right...  now it sets the working width to 4m...  not the 9m of the actual tool I am using..

The TF-1500 should have no working width of its own, as it's just an additional capacity tank!

**Comment by pops64** [comment]
I believe it is a problem with the way course width is calculated. There is no coding to check to see what is the smallest work width. It just checks all implements and the last to be checked is the one CP goes with.

**Comment by ThomasGaertner** [comment]
try 132 or higher and report

**Comment by sootysax** [comment]
This is resolved
