### ISSUE TITLE
Issue using forage harvester 

### ISSUE THREAD

**Issue by Silentpanther7** [Courseplay/courseplay#2013]
Hello, 

I have set the forage harvester course for corn. I have set a transport route for a tractor and trailer to a bunker. I have manually set the harvester in use for the transport trailer. The tractor isn't moving to the combine it remains sat at the stop location. Unsure if this is an issue or a user issue

**Comment by pops64** [comment]
Is pathfinding activated?

**Comment by Silentpanther7** [comment]
https://pastebin.com/YGdhbcxA

![image](https://cloud.githubusercontent.com/assets/28028178/25436407/19c5911e-2a8b-11e7-845e-c49c0a253c18.png)

![image](https://cloud.githubusercontent.com/assets/28028178/25436423/23383c10-2a8b-11e7-8e7d-3c13de26a3df.png)

v5.01. 00129.dev 
Pine cove farm, 

GPS, Drive control, money tool, lower animal prices, 4 real tire dirt, 4 real ground response, follow me.

**Comment by pops64** [comment]
Ok CP is probably breaking because you have placed a waitpoint at the stop. Waitpoints are not needed in mode 2. See http://courseplay.github.io/courseplay/en/index.html for proper usage of all modes. It mostly up to date with the rest still on our Todo list

**Comment by pops64** [comment]
Did this fix your issue?

**Comment by pops64** [comment]
Closed to keep issues area clean
