### ISSUE TITLE
Pottinger Novacat 301 ED Error

### ISSUE THREAD

**Issue by Blackjack155** [Courseplay/courseplay#2015]
And the problem is that he sinks but as soon as he starts driving starts and stops the drive in the seconds clock he wants it start but also turn off again the caused flicker the display down in the hut

[log.txt](https://github.com/Courseplay/courseplay/files/958631/log.txt)

**Comment by pops64** [comment]
? https://github.com/Courseplay/courseplay/wiki I have no clue what your problem is. Thanks for the log tho

**Comment by Blackjack155** [comment]
https://www.youtube.com/watch?v=gsBEWI-8_fQ&feature=youtu.be

**Comment by pops64** [comment]
Video is unavailable. If you speak German you can go ahead a report your issue that way.

**Comment by Blackjack155** [comment]
geht es jetzt`?

**Comment by pops64** [comment]
Yea that worked. You probably have a mod conflict. First try a giants default vehicle or a different one. Then trying turning off all scripted based mods besides CP and what your map needs to run.

**Comment by Blackjack155** [comment]
Where did it work and now no more ?

**Comment by pops64** [comment]
I was talking about the video.

**Comment by Blackjack155** [comment]
ich meine CP ;)

**Comment by Blackjack155** [comment]
Bug fixed trand can be deleted

**Comment by pops64** [comment]
How did you fix it? Was a mod conflict or did it just resolve it self?

**Comment by Blackjack155** [comment]
A mod conflict ;)

**Comment by pops64** [comment]
Alright Closed. Thanks
