### ISSUE TITLE
seed and  fertilize

### ISSUE THREAD

**Issue by oliverminic7** [Courseplay/courseplay#2018]
Hello,

I am playing Hofland map and having problem with seeding and fertilizeing refill.
I have created the path for refill. It dosent have auto trigger becouse I want to refill with shovel "fill and empty shovel".
when I run the path from coursplay the tractor starts moveing corectly the problem is when the seeder or trailer is empty it dosent stop and go for refill but keep seeding along the path,

What I do is:
-create path for refill
-load the field path for seeding
-load the refill path
-choose seed and  fertilize option and run the path

any sugesstion why the refill dosent work

Thank you in advance for your help.

**Comment by pops64** [comment]
Have you turned the option of buying seed for helpers off?

**Comment by oliverminic7** [comment]
where is that option?
also I have this mod FS17_AAA_HiredWorkerConsumesFuelSeeds.zip

**Comment by oliverminic7** [comment]
ok resolved

**Comment by pops64** [comment]
I was about to say that mod is no longer needed as those options exists. Closed to keep issues area clean
