### ISSUE TITLE
suggestion for chance in the translation_de.xml 

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#2021]
Hey guys

kombined courses was shown in the F1-map as long text
since a pair of weeks i chance one word in the translation_de.xml:
line 121 from:
`	<text name="COURSEPLAY_COMBINED_COURSES" text="kombinierte Kurse" />`
to:
`	<text name="COURSEPLAY_COMBINED_COURSES" text="kombiKurse" />`
 so it shows not so long in the F1-map sight

lg
andreas

**Comment by pops64** [comment]
Not going to change. Thanks for the input tho.
