### ISSUE TITLE
Mode 3 Nil Vaule Line 10

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#2023]
Map:  Hobbs Farm 1.6.0.6
Equipment:  Skipping Sewing - Case IH Quadtrack (Vanilla) & Sower:  Horsch Pronto 9DC (Vanilla) See photo.
Equipment:  Skipping Harvest - Rostelmash Acros 595 Plus with Capello 6M Corn Header
![20170429123642_1](https://cloud.githubusercontent.com/assets/24764870/25557141/560fc1bc-2cd9-11e7-9116-175c7617d060.jpg)
![20170429123701_1](https://cloud.githubusercontent.com/assets/24764870/25557143/58fb240c-2cd9-11e7-85f8-46a4e408e224.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/966275/log.txt)
Latest v of CP.

**Comment by pops64** [comment]
I would have to say your mode 3 worker is doing something. Mostly likely running a courses with no wait points.  Your log is spewing 
`C:/Users/Loushon/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/mode3.lua:10: attempt to perform arithmetic on a nil value`

**Comment by lcc1211** [comment]
Its behavior started acting up.  Not moving to the combine when it reached the desired fill level.  It would only move to the combine once it reached 100%, but then sometimes the combine would start moving with its header moving but not lowered.  As for the sower, it was down and sowing, but the ground texture wasn't changing in spots.

**Comment by pops64** [comment]
What your seeing is the effects of what happens when CP runs into a nil vaule error that doesn't freeze the game. Which is why I asked about your mode 3 worker cause he is the cause of all this

**Comment by lcc1211** [comment]
Even though the mode 3 worker is on another field?

**Comment by pops64** [comment]
Yea. What your seeing is FS is still running but all functions are stuck.. Lucky what ever is causing this error is cleared because what ever caused it is dependent on location. Which is why you are getting the gaps in the field. Theses functions get shut off when this kinda of error happens.

**Comment by pops64** [comment]
I looked the code. Make sure you have no unload points in use in mode3 only wait points. Has this is the most likely cause of this error

**Comment by lcc1211** [comment]
There aren't any wait points for the sowing course. It is an appended course with a the first one being the sowing course and the 2nd one being the refill course.  The tractor drives by the seed, fertilizer and fuel refill points.  The harvester doesn't have any wait points either.  Its attendant tractor drives to the silo when full and then back to the field.  However, I was running a course one field over that was using a chaser to move grain over to a waiting tipper.  That one does have a wait point at the tipper, but that shouldn't be affecting the vehicles on the other 2 fields.

**Comment by pops64** [comment]
What ever the cause. It has to do with a mode 3 worker. If you run a worker on mode 3 that course must have **no** unload points what so ever. There is no protection atm for mode 3 if it gets passed a unload point. If there is a nil error that happens you could get random behavior. Which is what you are seeing. So if get this weird behavior switch over to the mode 3 worker and stop him and this behavior will go away. And make sure the course he is driving has **no** unload points in it what so ever.

**Comment by pops64** [comment]
Avoid using Mode 1 with augur wagons

**Comment by pops64** [comment]
try again with version 138 or higher and report back

**Comment by lcc1211** [comment]
OK. I set things up like I had them before.  One field with CP harvesting and a tractor attending and hauling to a silo, Field 2 had the appended course sowing/refilling and the 3rd field had the chaser course.  This seems to be cleared up now.  FYI.  All 3 of these courses would work fine, but if I ran the chaser course on field 3 the other 2 course on the other fields would start acting up.

**Comment by pops64** [comment]
Yea. I looked at the code again. Mode 1 was setup to use augur wagons by calling upon the mode 3 functionality. But Mode 3 was never re-coded for that kind use. So it was your mode 1 driver that was causing the issues. I have disabled that functionality of mode 1 until mode 3 can be re-coded. Thanks for the reply closed to keep issues area clear
