### ISSUE TITLE
Fehler beim Schieben

### ISSUE THREAD

**Issue by Andreas115** [Courseplay/courseplay#2025]
![fsscreen_2017_04_30_09_38_38](https://cloud.githubusercontent.com/assets/24195152/25562930/791af2f2-2d89-11e7-8bde-432d7e29fa46.png)
Moin Moin!,
also ich habe jetzt seit neuestem den Fehler, das der Traktor das Schild beim Schieben per Courseplay-Kurs nicht mehr herunter lässt. Das Silo ist noch nicht mal zu 100% Verdichtet.
Liegt es an meiner Einstellung oder weiß jemand Rat?
Vlg und besten Dank schonmal!
Andreas

Good Morning!,
So I have now the error that the tractor does not lower the shield when pushing by Courseplay. The silo is not even 100% compacted.
Is it my attitude or does someone know advice?
Vlg and best thanks!
Andreas

LS 17 Update 1.4.4.0
CP V5.01.00131

![fsscreen_2017_04_30_10_06_47](https://cloud.githubusercontent.com/assets/24195152/25563131/0c0d5502-2d8d-11e7-8605-c543b196e1c2.png)

**Comment by Andreas115** [comment]
![fsscreen_2017_04_30_17_25_45](https://cloud.githubusercontent.com/assets/24195152/25566059/94d83c66-2dca-11e7-9cb1-7302ae0aeceb.png)
ich habe mehrere Traktoren ausprobiert und auch einmal alle mods entfernt...trotzdem lässt er das schild nicht herunter...
I have tried several tractors and also once removed all mods ... nevertheless, he does not let the blade down ...

**Comment by pops64** [comment]
See #1997 Closed to keep issues are clean
