### ISSUE TITLE
Harvester turn Problem!

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#2028]
Hi! My Problem is the Harvester not turn on the end of the line! 
![unbenannt](https://cloud.githubusercontent.com/assets/10115244/25567557/adb4f82a-2df0-11e7-9d27-9c854f906e2b.gif)

[log.txt](https://github.com/Courseplay/courseplay/files/966969/log.txt)

**Comment by pops64** [comment]
See #1732 And let us know if this is your problem

**Comment by Paul2510** [comment]
YES! Have again tested and have found that the problem only occurs when the harvester has no fruit! If he has no fruit yet! If one reaps what eg Grass works!
LG

**Comment by Paul2510** [comment]
The last version was a Problem withe the Silobunker mod! The Game Freze and many Logs
[log.txt](https://github.com/Courseplay/courseplay/files/967812/log.txt)

**Comment by Blackmankot** [comment]
@pops64  And I propose to close this issue for cleaning.

**Comment by pops64** [comment]
Closing this has a duplicate
