### ISSUE TITLE
Holmer Terra Variant with Holmer RB 35 coupled

### ISSUE THREAD

**Issue by Pitufo306** [Courseplay/courseplay#2030]
I would like to know if an exception to this implement could be incorporated with transfer function. The exception would be that you could unload on the ground from mode 3, just like you can do in mode 7 with the potato and beet harvesters. Well that's its true function, do not dump it on a trailer as do the grain overload checks.

Currently if you create 2 waiting points to indicate the place of unloading on the ground, it indicates that the route has more than one waiting point. Thank you

**Comment by pops64** [comment]
You should be able to use mode 2 and have your unload point as where you want the pile.

**Comment by Pitufo306** [comment]
Mode 2, creating the route with the 2 holding points, the Holmer Terra Variant with the Holmer RB 35 attached, indicates: "wrong trailer for this mode"

**Comment by SweClark** [comment]
I had the similar problem whit the graintank when overloading.. I had to change the xml-file for it..
I change this line (<allowTipDischarge value="false" />) to true.. Then it worked..

**Comment by Pitufo306** [comment]
@SweClark What line do you modify? I raise the subject because I still do not find how to do it.

**Comment by SweClark** [comment]
Just wait a minute.. i will check..

2017-06-28 19:01 GMT+02:00 Pitufo306 <notifications@github.com>:

**Comment by Pitufo306** [comment]
@SweClark I imagine that with the xml file you mean the .lua file in mode 3

**Comment by SweClark** [comment]
For an example it sas in the holmerGraintank.xml <vehicle
type="augerWagon_foldable"> change that to <vehicle type="augerWagon">
And do that to the sugarbeettank too.. works great :)

2017-06-28 19:01 GMT+02:00 Pitufo306 <notifications@github.com>:

**Comment by SweClark** [comment]
Its the vehicletype thats wrong in the mod :(

**Comment by SweClark** [comment]
And change this too.. <allowTipDischarge value="true" />

**Comment by SweClark** [comment]
when i changed all this it works great whit courseplay

**Comment by SweClark** [comment]
[holmerGrainTank.txt](https://github.com/Courseplay/courseplay/files/1109619/holmerGrainTank.txt)

**Comment by Pitufo306** [comment]
@SweClark Thank you very much for your help, I hope nonetheless, add it soon as an exception in the courseplay.

**Comment by SweClark** [comment]
So it worked out great for you? I can otherwise send you the modded files..


Den 28 juni 2017 20:00 skrev "Pitufo306" <notifications@github.com>:

**Comment by pops64** [comment]
Collapsing mod issues into one thread. #2231
