### ISSUE TITLE
Problem with plows mod which do not turn at the end of line.

### ISSUE THREAD

**Issue by TheoGaming86** [Courseplay/courseplay#2032]
Hello guys,
I have a problem with plows  do not turn at the end on line. When I puts the worker worked the latter when he arrives at the end of line do not turn the plow. I use the plows mod. The name of this mod is Maschio XXL 12 ( https://ls2017.com/farming-simulator-2017-mods/implements-and-tools/maschio-xxl-12-v-1-0/#more-4108 ). 
By making tests with this plow, I would ask you to inform me about it and if you could, you could update the code of a way has that this mod works.
If you want others information of this problem, I can help you at the level of the game but on the other hand I would not be capable of answering you in the field of the code or which it of other one.

Thank you for your understanding. Hold I informed in the most brief deadlines if it evolves.

Cordially
TheoGaming86

**Comment by pops64** [comment]
We are going to need a clean link to even begin looking at the mod. So it would have to come from Modhoster, FS-UK, Giants ModHub and the like.

**Comment by TheoGaming86** [comment]
Hello,
I have find this mod on LS2017. Here is the link of the same mod on mod
hoster: https://www.modhoster.com/mods/maschio-xxl-12

Cordialy
TheoGaming86

2017-05-02 18:52 GMT+02:00 pops64 <notifications@github.com>:

**Comment by pops64** [comment]
Collapsing mod issues into one thread. #2231

**Comment by TheoGaming86** [comment]
I think tour idea it's good but for resolved thé problem I use an oter
plows the courseplay supported this endest.

Excuse me for my bad english.
Thank you so much for your help.

Theo Gaming 86

**Comment by pops64** [comment]
Full name of mod having this same issue and a clean link would be preferable

**Comment by TheoGaming86** [comment]
Hello,
Could explain me how to delete the issues because I do not find the button to close the latter.

Thank you anyway for yours help and can be for a next time

PS: Can you come visit my YouTube Channel: GlutWood 
on the link: https://www.youtube.com/channel/UCV4ONMANZbZRrKMhySDiuPQ
