### ISSUE TITLE
Multiplayer support

### ISSUE THREAD

**Issue by And-V** [Courseplay/courseplay#2033]
Hello.
Do you plan make a courseplay support for Multiplayer? I have tried replace the multiplayer supported="false" parameter in moddesc on multiplayer supported="true". But with other mods this operation is not work - session owner can create session and enter the game, but other players can't joined - on synchronization an errors appears in log. I think this errors appear due to mods with passenger script - BeihaferV3. Is it possible fix this errors and play multiplayer with courseplay and mods with passenger script?
Thank you for answer.

**Comment by Blackmankot** [comment]
Hello. The answer to the question. #1729

**Comment by pops64** [comment]
Has Blackmankot said. Closed to keep issues area clean
