### ISSUE TITLE
Courseplay and More Realistic Problems

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#2034]
Just wondering what the conditions are for CP to apply turn speed vs. street or field speed?

Some times CP slows down to the turn speed around turns on road routes, and sometimes it does not.   Is there an angle cutoff that decides if it will just use the recorded speed or the turn speed?

Reason being, I am using the More Realistic beta, and no longer have the glue like grip on the wheels I had before, and all my tractors are sliding off some of the turns or tipping over on my recorded routes at the speeds I was able to make the turns before.   I have lowered the turn speed on my road routes, but is not being applied on some turns.  

I'm trying to avoid having to re-record my network of road routes for my game..

**Comment by turbostar190** [comment]
To CoursePlay dev from MR developer: https://fs-uk.com/forum/index.php?topic=195659.msg1273853#msg1273853

**Comment by sootysax** [comment]
Is there any more thought to this?  I'm finding it pretty difficult to do any field work with More Realistic and Courseplay.   Mode 2 or 3 is not working well at all..  the tractor overshoots the turns for the waiting points, because the vehicle is too heavy... then snakes trying to find the point, and winds up in the crop, blocking the harvester every time.  Also overshooting the harvester when unloading.

I think having CP disable the MR transmission whenever a course is being run is the easiest solution, as CP doesn't seem to be handling the weight of the vehicles very well..

**Comment by MoslessNeo** [comment]
Try to download the MoreRealistic version v0.2.18 from the folder number 2.

**Comment by sootysax** [comment]
I download the latest version of MR daily

**Comment by pops64** [comment]
It is a problem. Of Giants braking force. with default values CP has the opposite problem your having. It brakes to hard and CP has issues. I am not 100% sure were the braking force is in the code. I will look for it and try something out. I know we use about half the braking force normal applied.  Do you a link to the mod in question?

**Comment by turbostar190** [comment]
This is the mod: https://fs-uk.com/forum/index.php?topic=195659.0
This post explain why use version 2: https://fs-uk.com/forum/index.php?topic=195659.msg1275106#msg1275106
And this is the last post to cp dev: https://fs-uk.com/forum/index.php?topic=195659.msg1275188#msg1275188

**Comment by pops64** [comment]
Try with version 141. And Report back. I will talk with Satis and Thomas about either making this the permanent fix for the mod or adjusting the braking parameters if the mod is enabled.

**Comment by sootysax** [comment]
There is an issue with this..  here is my report to Dural on FS-UK:

So the temp fix works...  sort of...   until you stop the Courseplay course from running - when the MR trans kicks back in, 1000's of pounds of pent up exhaust shoot out of the pipe, and the vehicle is disabled until you shut down the engine and start it back up again. 

This is also happening when the Gearbox Addon disables / re-enables the MR transmission. Technically, you cannot turn the Gearbox Addon on/off when the engine is running... but there is a bug that does allow it when CP or Follow Me is running... also the latest version of Game Extension allows you to activate the Gearbox when you enter/exit a vehicle.

Either way..   if you re-enable the MR transmission with the engine running and revved up.. bad things happen :p  If the vehicle is stopped or in traffic, its fine.. 

VIDEO:

https://www.dropbox.com/s/qsle8rl8l5g2p28/2017-05-16_180608760.mp4?dl=0

https://www.dropbox.com/s/bn8qm2hkjlnh818/2017-05-16_184843555.mp4?dl=0

**Comment by webalizer-gt** [comment]
I don´t know if you noticed my comment on the original commit. There´s problem with re-enabling mr transmission in start_stop.lua (line 677):
self.mrUseMrTransmission is "false" in this state; therefore mr transmission is never re-enabled.
Line must read:
`if self.mrUseMrTransmission~=nil and self.cp.changedMRMod == true then`
or just don´t check self.mrUseMrTransmission because self.cp.changedMRMod can only be true if it exists.

**Comment by pops64** [comment]
Collapsing mod issues into one thread. #2231

**Comment by pops64** [comment]
This will temp fix will become permanent. CP tells FS what speed we want to drive at by setting the cruise control. It is up to FS on how quickly we get to that speed. If you have any input form the mod author on how to fix the rev problem I am open to hearing it but I think it is a problem with their mod and not CP.

**Comment by KITT3000** [comment]
@pops64 So would it be possible to add compatibility with 'Realistic Fill Type Mass Adjustment'?

**Comment by pops64** [comment]
I would need to know how that mod is active(g_currentmission or a unique tractor installed variable) and I can just include the braking function in with.

**Comment by KITT3000** [comment]
@pops64 You have the whole script here because unfortunately there is not what you require, but maybe you will be able to detect if it is active otherwise: https://gist.github.com/KITT3000/94fcb1193be50c039d84f57bc0885dfc

**Comment by pops64** [comment]
Yea there is no way we would be able to detect your script running you would have to add a
g_currentMission variable. I know we did it for CP I just can't remeber how

**Comment by KITT3000** [comment]
@pops64 And this Giants way to disable the camera collision of their mod?
`instance.isCollisionEnabled = not g_modIsLoaded["disableVehicleCameraCollision"]`
to
`g_modIsLoaded["FS17_fillTypeMassAdjustment_realistic"]`

**Comment by pops64** [comment]
#2823 sorry wrong variable

```
local globalEnvironment = getfenv (0);
globalEnvironment["g_courseplay"] = globalEnvironment[g_currentModName];
```

still not quit sure how it works

**Comment by pops64** [comment]
I am checking to see if print(g_modIsLoaded["FS17_fillTypeMassAdjustment_realistic"]) will work

**Comment by pops64** [comment]
Alright @KITT3000 if you want to test it out, It is under the branch pops64NextPush. Mostly stable there are changes to the mode2 chopper that haven't been tested but if you want to go ahead

**Comment by KITT3000** [comment]
@pops64 From initial tests it looks like it works correctly, but I will check tomorrow more accurately.

**Comment by pops64** [comment]
alright. I know with MR it is getting stuck very rarely with a plough on direction change and I can't seem to figure out why

**Comment by pops64** [comment]
Version 44 or higher will work now or better than before. Still take turns easy has CP doesn't know any better than recored speed but it will now reach recored speed alot quicker than before. There may or may not be a problem with switching direction during fieldwork. I have seen it but I couldn't figure out the cause and it only occurred on one field 6 or 7 turns(1.5 ha field) and only once on another field. CP will tell you that the tractor is slipping so you know that it has field just finish the turn for CP and resume CP

**Comment by pops64** [comment]
Fixed
