### ISSUE TITLE
level and compact

### ISSUE THREAD

**Issue by Admilson** [Courseplay/courseplay#2036]
Would it be possible to level and compact the silo after one or two discharged? After 3 or 4 discharged the tractor slips, making it more difficult for him to continue.

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki Don't understand what your issue is. It continuously levels and compacts unless there is nothing to level and compact.

**Comment by Admilson** [comment]
I have 4 tips unload, there are 2 or more tips in the queue to unload, the tractor with blade waits all unload before going to the silo, with that the tractor is skidding because there is a lot of silage, I ask if it is possible the tractor with blade to go to Or silo every 2 unload

**Comment by Admilson** [comment]
At the moment I created another route by pausing the route near the BGA and this made the tractor with blade could work more in the silo avoiding a lot of silage, I think this is the ideal solution. thank you so much.

**Comment by Blackmankot** [comment]
@pops64 And I propose to close this issue for cleaning.

**Comment by pops64** [comment]
Close this out. We will revisit this in the future after the release if we have time.
