### ISSUE TITLE
Bunker unload with trailer problem

### ISSUE THREAD

**Issue by Tonton1969** [Courseplay/courseplay#2038]
Hi when I did unload a trailer reverse in a bunker (Lösshügelmap) the trailer will be unload always at thge beginningof the bunker will not start with filling the bunker at the end.

Can someone explain what is my mistake?

**Comment by pops64** [comment]
Never ever use a unload point inside of a tip trigger. And there is no mistake if you reverse into a BGA silo it will always drive back at little from the front and empty there. It no longer goes all the way to the back like in 15

**Comment by Tonton1969** [comment]
I not use a unload point problem is really that the unload is direktly at the begin of the bunker....

**Comment by pops64** [comment]
See #1671 Closed to Keep issues area clean
