### ISSUE TITLE
More realistic mod is back, but...

### ISSUE THREAD

**Issue by bigjoker76** [Courseplay/courseplay#2040]
...there seem to be some problems...
I started the Optum with the Amazone condor seeder on the field course for sowing.
The following error shows up. What could be the reason for that? I tested with MR traktor+MR seeder and Non-MR Traktor with MR seeder
![fsscreen_2017_05_06_17_30_52](https://cloud.githubusercontent.com/assets/6426554/25773670/ec0e49b0-3281-11e7-825f-2e5dc66d7523.png)
[log.txt](https://github.com/Courseplay/courseplay/files/981006/log.txt)

Thank you for your help

Jochen

**Comment by bigjoker76** [comment]
Gentlemen...I found the error...sorry for waisting your time :-)
In the MR - XML of the condor was the error.

Please close this issue

**Comment by pops64** [comment]
Alright thanks

**Comment by sootysax** [comment]
bigjoker, what was the error and how did you fix it?
