### ISSUE TITLE
Reverse unloading in BGA

### ISSUE THREAD

**Issue by E7O** [Courseplay/courseplay#2041]
Hey,

When i use a tractor to reverse unload in a bga silo i often encounter the problem that my tractor won't move forward after backing up and unloading.

It seems to be a problem when the trailer has a little amount of grass left (it says 0% but actually there is like 8 grass of chaff left in the trailer)
Sometimes when the trailer is successful fully unloaded the tractor is moving out of the bga like he should, only when he is got some small leftovers he isn't moving.

Its not like he is at half or 20%, it really says 7 grass left in the trailer. And when i try to unload it manually it still stays in the trailer.
Is there something i can do about it?

Gets

**Comment by SweClark** [comment]
Same problem me too.. Just installed 5.00133

**Comment by Blackmankot** [comment]
@E7O  Good afternoon. Is this the situation with all the trailers? Or with one trailer?

**Comment by SweClark** [comment]
At the moment i have courseplay  00140. And it works most times. But at random times its starts again. When it happens i have to drive it out of the BGA and empty it manually and restart the course.
And at random times i mean at most once in an 12 hour game. So at the moment its not a big issue. Thanks for asking :)

**Comment by Blackmankot** [comment]
@SweClark Good afternoon! Has the situation changed with the new versions of the course? :)

**Comment by SweClark** [comment]
Havent updated the courseplay version. I will do that in the end of this week. This weekend it didnt happend at all.. Same trailer.. Same Tractor.. Same course.. Same courseplay.. Weird :)

**Comment by pops64** [comment]
When it is left with that little bit is it still trying to unload? Or has the tipper stopped unloading and closes the tipper?

**Comment by SweClark** [comment]
When the problem occurs the tractor moves front/back in a loop. And the trailer open/close in a loop..
But it occurs very seldom in the later Devs. And when it happens you have only close the coursplayroute for the tractor and manually empty it outside the compound. Its only around 8kg grass.

**Comment by BenB78** [comment]
I came looking for an answer on this same problem. Same thing for me - the trailer stops unloading into the bunker with 2-8 grass left. When this happens, I notice Courseplay stops working on random vehicles (including the unloading grass trailer). If I have some harvesters going, a few of them (but not all) will just start driving in a straight line. I can deactivate the course and reactivate it, change course, set to start at first or nearest point, but none of that changes anything. They drive forward in a straight line every time I click Drive Now, until they hit something. The only way to fix it is to restart the game. It's hard to debug as it only happens every few days or so, and I haven't figured out exactly the conditions needed to make it happen. It seems random. I currently have version 5.01.00145. I'll grab 00146 in a moment.

**Comment by pops64** [comment]
This sounds like an actually bug. Follow https://github.com/Courseplay/courseplay/wiki on how to report it. Please post it here since it sounds like the same issue.

**Comment by BenB78** [comment]
Will do. I should have a chance to play over the next couple days and will post logs when it happens next. Did you want any debug channels turned on?

**Comment by pops64** [comment]
No, it sounds like your game is producing a nil error which shows in the log automactilly. Which causes other side effects like you described

**Comment by pops64** [comment]
try again with version 147 or higher

**Comment by BenB78** [comment]
OK. The error didn't happen last night. I'll go to 147 and try again tonight. I'll post the log when it happens again.

**Comment by BenB78** [comment]
The error didn't happen last week and I haven't had time to play since. Hopefully my work schedule will lighten up a bit here and I'll be able to test again soon.

**Comment by BenB78** [comment]
OK it happened again. There was 11 left in the trailer when it stopped tipping, and would not drive on or empty the rest. What I had done just before this happened was jump in the leveling tractor and turned off CP in there to take manual control while the tipper was approaching the bunker. It had done the course dozens of times perfectly before I did that.

Here is the log.  https://gist.github.com/BenB78/8a23bd2963881a53d738c66883c55c03#file-log-txt

**Comment by Karlshoj** [comment]
The same happens to me, but only when tipping a not completely full load

**Comment by pops64** [comment]
Try with version 161 or higher. Sorry, I forgot to add the version number in the push. And report back. Thanks

**Comment by BenB78** [comment]
So far, so good. I haven't been able to duplicate the problem in the new version. I did notice that there was a time the leveler kept 15 permanent chaff "on" it, even when lifted. I don't know if that's related, and eventually it went away. I didn't see the tipper problem at all.

I'll let you know if it comes back again. It was quite intermittent so even though it looks like you got it, I don't know for sure! :)

**Comment by webalizer-gt** [comment]
This problem is still there as described above in v168.
[https://gist.github.com/webalizer-gt/00ab7c3e0a14869da1f5bc3ff3e87444]

**Comment by Blackmankot** [comment]
@pops64 And I propose to close this issue for cleaning.

**Comment by BenB78** [comment]
It's been months and the problem I saw has not happened again, where before it was happening several times per game. My opinion: bug squashed and issue can be closed.

**Comment by pops64** [comment]
Alright. Thanks. Closed. Create a new post if it comes back
