### ISSUE TITLE
Manual Offset with forage harvester is always set automatically.

### ISSUE THREAD

**Issue by codiemorgan** [Courseplay/courseplay#2042]
Hi. When running a forage harvester counter clockwise around a field I set manual offset on the tipper tractors to -7.0 in order to make them run on the "right" side of the harvester (New Holland). 

However, every time the tractors arrive at the harvester it automatically switches it's offset in combi mode to (positive)+7.0 and put's itself on the left side. This causes problems as it implies "manual" configuration of the offset for tippers does not work correctly. 
Manual offset seems to work with normal field harvesters though, this behavior is one I have only noticed with forage harvesters so far. 

When using a very large trailer on my tractors and a forage harvester CCW direction around a field, It is important to try force tractors to run on the right side of the harvester instead of the left side to avoid collisions - especially with large trailers (otherwise they collide every time the harvester reaches a turning point).

**Reproduce:**
 - Set a forage harvester to start a field with a CCW headfields direction.
 - Set a tractor's combi mode offset to _manual -7.0_ or relevant offset to collect on **_right_** side of the forage harvester, instead of the left.

 **Result (With New Holland FR):**
 - When tractor arrives at Forage Harvester, it automatically switches to +7.0 instead. Always running on only the _left side_ of the harvester. This implies manual configuration is always overridden when not in auto mode, thus making user's manual input useless, and also make's CCW headfields unusable with very long tippers. 

Every attempt to get my tippers to run on the right side of a forage harvester has failed.

**Comment by Symbob** [comment]
Manually setting a side for the trailer can be done on the first tab "Combine Controls" for the harvester you are using.  Once a tractor and trailer has been assigned to the harvester (I'm using the Krone BigX 1100) you will see that the Driver Side can be set manually in the Combine Controls tab.  Default setting is Automatic (which I find works well most of the time) but just select the side you want your tractors to drive.

**Comment by pops64** [comment]
Can we close here?

**Comment by codiemorgan** [comment]
Will test this on my next corn harvest.

**Comment by Blackmankot** [comment]
@codiemorgan What did the test show at the next corn crop?

**Comment by pops64** [comment]
Closed due to inactivity.
