### ISSUE TITLE
Automatic overwriting manual turn radius

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#2045]
Hello Guys,
first let me say i am happy that you built in a reload course button - i must trie when i am at home

my request is the turning radius in the Settings-hud (the 4. from left)
is it able to set a manuel turn radius and this one was saved?
as example i have the valtra-cow (with loading wagon bergmann repex34s)
the turning radius is automatically 12m (out of Brian dont know here the precise radius)
when i Change this to 9m (mnl) the tractor drives the course normal.
when i generate a new field working course, and i hire a worker then is the radius 12m again and i must change them  once more to 9 m.
secend example, the Amazone profihopper always have a turning radius from 4m automatically, 
i can drive them without Problems with a turning radius from 1m - but each time i generate a new course the turning radius is again automatic (4m)

it is not the Problem hire / fire / hire a worker - here is the radius the same
only when generating a new course the radius set to automatic

lg
andreas

**Comment by pops64** [comment]
I know Thomas did something to this in version 155 could you try with that and report back thanks.

**Comment by andreasthu** [comment]
hey pops64
i tried it with 0162
it seems to work
lg
andreas

**Comment by pops64** [comment]
Closed to keep issues area clean.
