### ISSUE TITLE
Tractor goes straight into bushes instead of following track

### ISSUE THREAD

**Issue by brnl** [Courseplay/courseplay#2047]
I hope it's not double, hard to find the right keywords here.

I have a problem with a generated course: The course is generated based on a self-recorded field limit. It has two headlands.

After the headlands, the tractor will start the first lane. At the end of the lane, the tractor stops and lifts the tools. But instead of making the turn to follow the track, the tractor wanders off into the bushes (and crashes into the trees).

Here is the log. It's always hard to tell what debug channels you need, so I have enabled the ones that sounded interesting. Hope it helps. In the log I have tried it two times. Once before I saved the course as 'broken' and once afterwards.

[log.txt](https://github.com/Courseplay/courseplay/files/984978/log.txt)

![image](https://cloud.githubusercontent.com/assets/3243133/25827543/0bce44dc-344c-11e7-9811-0717614b4293.png)

**Comment by brnl** [comment]
Here another attempt, with a normal generated course and some different logging enabled that you might like.

[log.txt](https://github.com/Courseplay/courseplay/files/985001/log.txt)

Now it's also visually what's going wrong here. It misses the turn point?

![image](https://cloud.githubusercontent.com/assets/3243133/25827950/f347f8ca-344d-11e7-9260-e45cc86ae319.png)

**Comment by pops64** [comment]
what are your turn settings?

**Comment by pops64** [comment]
See #1878
