### ISSUE TITLE
Call Stack Error in Function handleUnloading

### ISSUE THREAD

**Issue by scaniafreak** [Courseplay/courseplay#2050]
I play on hobbs farm. I have made leverling course for one of the bunkers. The leveling itself goes OK. After a while the tractor goes to the waiting point, even when no truck or tractor is near. When i click now drive, the leveler goes 1 round, and then back to the waiting point.

On the other side i have made a course for the truck to unload in the bunker.
When the leveler is waiting, and the truck approaches, both keep waiting for eachother.
the truck waits for the leveler (which is already waiting), and the leveler waits for the truck,...
See the attached picture.
![fsscreen_2017_05_09_18_47_29](https://cloud.githubusercontent.com/assets/3944298/25862616/fb9130e6-34e8-11e7-95fc-7424eca5e5ba.png)
![fsscreen_2017_05_09_18_55_27
![fsscreen_2017_05_09_18_56_29](https://cloud.githubusercontent.com/assets/3944298/25862684/3dff6182-34e9-11e7-8dac-9d00aa3356b3.png)

Any idea?

**Comment by dkfiremann** [comment]
Are you leveller parked outside the bunker?
Make sure that the Leveler tractor is parked inside the walls of the bunker.

**Comment by scaniafreak** [comment]
The leveler is indeed parked outside of the bunker. That's how it's explained in tutorials

**Comment by dkfiremann** [comment]
Okay, I haven't looked in the manual. 
But for every youtube video that explain how leveling works, and in my tests, the tractor needs to be parked inside the bunker frame. 
Now, what is the bunker frame? That is the area in front of the bunker, so that if you extend the walls of the bunker the tractor is still inside. 
As I see it, your tractor is on the wrong side of the bunker wall. 

Take a look at: [https://www.youtube.com/watch?v=40FDWBvFqKo&t=1477s](https://www.youtube.com/watch?v=40FDWBvFqKo&t=1477s)

**Comment by pops64** [comment]
I haven't look at the code but it doesn't matter where the waitpoint it just as long it doesn't interfere in unloading. My only concern is the second way point is inside of the trigger. According to the PDF the second way point is supposed to be outside of the trigger in line with the first. Try moving the second waypoint outside of the trigger

**Comment by Beevster** [comment]
Also make sure no other Vehicles in the area are not close by the pits, Even if they are supposedly "turned OFF" they can still interfere with the pit leveller which controls traffic. As i think he can control more then one vehicle to stop Hence stopping your load being tipped or even driving away as i found out.

**Comment by scaniafreak** [comment]
Thanks for the suggestions. I modified the leveler course with coursedrawer, and put the second waypoint outside the bunker. It seems to help, but it got me another problem which is far more strange...

At the moment when the truck starts tipping, the FPS drops to 3 FPS, and stays that way. I waited 1 to 2 hours, but the games stays at 3 fps, and the truck is still tipping. It happens with and without the leveler course active.

Then i re-recorded the leveler and tipping course brandnew, and made the leveler course simpler, just as Beevster suggest. But also then the FPS drops to 3 fps, already when the truck starts to drive backwards towards the bunker.

The PDF you mentioned, were can i find it. Maybe it contains more helpfull information for other drive modes:)

Any suggestions regarding the FPS drop. Any logging i can provide?

**Comment by pops64** [comment]
Yea the FPS drop is definitely a nil error of some kind.  Just post your game log to paste bin or gist and I will see what the error is. https://github.com/Courseplay/courseplay/wiki   The PDF is only for mode 10 has not been put into the manual yet.Link to the [manual ](http://courseplay.github.io/courseplay/en/index.html) still a WIP for conversion to FS17 mostly correct tho.

**Comment by scaniafreak** [comment]
Thanks for the quick reply. Here is my log:
https://gist.github.com/scaniafreak/75658907780f1f5ca6a1bf7c7dd67bd0

Just to mention, i just downloaded the latest CP (.138) and the FPs drop occurs also with that version. I also have started only that particular route. No other CP's were running.

**Comment by Anonymous-any** [comment]
https://github.com/Courseplay/courseplay/issues/2066
It's ok :) I just forgot to say I use HKL with wood IT to unload in water meaning the unload process maybe is not appropriate to courseplay with HKL arms I don't know.
Br CP

**Comment by pops64** [comment]
Try again with version 147 or higher

**Comment by Anonymous-any** [comment]
Hi, tried today seem not solved issue:

Warning (LUA): 'getWorldTranslation': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
LUA call stack:
  =C:/Blabla/path/FarmingSimulator2017/mods/ZZZ_Courseplay_beta/toolManager.lua (1402) : getWorldTranslation
  =C:/Blabla/path/FarmingSimulator2017/mods/ZZZ_Courseplay_beta/drive.lua (286) : handleUnloading
  =C:/Blabla/path/FarmingSimulator2017/mods/ZZZ_Courseplay_beta/base.lua (894) : drive
  dataS/scripts/vehicles/Vehicle.lua (2598) : update
  dataS/scripts/network/Server.lua (56) : update
  dataS/scripts/BaseMission.lua (1508) : update
  dataS/scripts/FSBaseMission.lua (2171) : update
  dataS/scripts/missions/mission00.lua (333) : update
  dataS/scripts/main.lua (1876) : update

![fsscreen](https://user-images.githubusercontent.com/25174503/27517348-4cfbc7d2-59cb-11e7-9860-d232288069c7.png)
Br

**Comment by scaniafreak** [comment]
i agree with anonymous-any.

Yesterday it went fine, but for some reason, today i got FPS drop again, like before...

**Comment by pops64** [comment]
Try again with version 152 or higher. And report back

**Comment by Anonymous-any** [comment]
I'm sorry for me always the same nothing better.
Br

**Comment by pops64** [comment]
Are sure you updated your CP to version 152 or higher. Because in 152 if the line before this is working then the line after it should work as well. Could we get a full log no deubug channels. Thanks

**Comment by Anonymous-any** [comment]
Hello I would want to send you that but you do not have something better except all vehicle I use !!
All spam error is post above

**Comment by pops64** [comment]
We don't care about start up spam. Only if excess debug channels are on or if you have mod that generates ongoing errors. In which case we ask to test without the broken mod if possible. We ask because 90% of the time when users copy a part of the log usually a section that is relevant is skipped over. For this issue the full error is this
```
LUA call stack:
  =C:/Users/mijzelf/Documents/My Games/FarmingSimulator2017/mods/ZZZ_Courseplay/toolManager.lua (1379) : getWorldTranslation
  =C:/Users/mijzelf/Documents/My Games/FarmingSimulator2017/mods/ZZZ_Courseplay/drive.lua (286) : handleUnloading
  =C:/Users/mijzelf/Documents/My Games/FarmingSimulator2017/mods/ZZZ_Courseplay/base.lua (891) : drive
  dataS/scripts/vehicles/Vehicle.lua (2598) : update
  dataS/scripts/network/Server.lua (56) : update
  dataS/scripts/BaseMission.lua (1508) : update
  dataS/scripts/FSBaseMission.lua (2171) : update
  dataS/scripts/missions/mission00.lua (333) : update
  dataS/scripts/main.lua (1876) : update
Warning (LUA): 'worldToLocal': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
LUA call stack:
  =C:/Users/mijzelf/Documents/My Games/FarmingSimulator2017/mods/ZZZ_Courseplay/toolManager.lua (1380) : worldToLocal
  =C:/Users/mijzelf/Documents/My Games/FarmingSimulator2017/mods/ZZZ_Courseplay/drive.lua (286) : handleUnloading
  =C:/Users/mijzelf/Documents/My Games/FarmingSimulator2017/mods/ZZZ_Courseplay/base.lua (891) : drive
  dataS/scripts/vehicles/Vehicle.lua (2598) : update
  dataS/scripts/network/Server.lua (56) : update
  dataS/scripts/BaseMission.lua (1508) : update
  dataS/scripts/FSBaseMission.lua (2171) : update
  dataS/scripts/missions/mission00.lua (333) : update
  dataS/scripts/main.lua (1876) : update
```

If you look closely you can see that it is _two_ different call stacks.  Which is why I asked for the full log. So if you could post it on gist or pastbin. Thanks

**Comment by Anonymous-any** [comment]
Here you get what you want I rebuild an unload course with your latest CP like you can see:
https://gist.github.com/anonymous/10d8ef497d12da86fee519e8b6b32462
And a screen with the final operand stack where I never put a wait point ;)
![fsscreen](https://user-images.githubusercontent.com/25174503/27772030-1866a1dc-5f5b-11e7-83d4-e830aa4d9f83.png)
Br

**Comment by pops64** [comment]
try again with version 166 or higher.

**Comment by Anonymous-any** [comment]
It's ok now but stay wait point in mode1 other mode say wrong trailer also HKL arm never move to unload:)
Br

**Comment by pops64** [comment]
It is the mod vehicle is classified has an auger wagon it now needs wait point for where to unload. Have you setup the pipe position for the arm? Moving the arm only works in mode 1 or 3

**Comment by Anonymous-any** [comment]
Sorry I say wrong mode I was say 1 but it's 5 I use. The mod I have seem not like you say "classified has an auger wagon" cause when I try the mode 1 or 3 I have nowhere for set the arm "pipe" position it's not a overloader trailer !.
Also I tested mode6 cause I've no restriction about the trailer and the crash hang can happen again.

**Comment by pops64** [comment]
Could we get a link to the mod in question?

**Comment by Anonymous-any** [comment]
Yes investigate the web this is composed by 2 mods (trailer and truck)
The trailer as default: http://uploadfiles.eu/4kinn1a82dvz/IT_Wood.zip.html , where my own is just altered for increase the logs size.
The truck: http://uploadfiles.eu/qlg3oddz0nv5/PackManHKL.zip.html ,this one contain 3 truck and the one I use FS17_MAN_TGS_HKL_8x4_2.zip, I compared to the download version everywhere I found the pack I was download cause of not same hash file, it seem you have to remove the line 315 in DAF.xml I was do to make a fix       <movingPart index="0>0|3|0|1" referencePoint="0>0|2|0|1" referenceFrame="0>" isActiveDirty="true" playSound="false" scaleZ="true"/>so sorry for that if I remember good some wheels was bad reference also convert store.png file to dds due to warning but its not major fix. I not use the other HKL's in pack at this time.
Hope this help and not be a constraint.

**Comment by pops64** [comment]
Collapsing mod issues into one thread. #2231
