### ISSUE TITLE
Request: show work area

### ISSUE THREAD

**Issue by zed636** [Courseplay/courseplay#2058]
Hi, I ask if it is possibile to create a button for show/non show the work area of a implement. I refer to the red rectanglue that CP show when you move COURSEPLAY_TOOL_OFFSET for few seconds: can you create a button to show everytime the work area on the screen? It would be helpful for plows or liquid manure spreaders to view where the CP will work.
Thanks for your help!
regards
Marco

**Comment by pops64** [comment]
Unfortunately at this time. Our suggestion list is way to long at the moment and we are only working on releasing CP. Closed to keep the issues area clean.

**Comment by zed636** [comment]
ok thanks
