### ISSUE TITLE
Machine center is misrecognized

### ISSUE THREAD

**Issue by JHP36** [Courseplay/courseplay#2059]
In many machines, the machine center is misrecognized. That's why the Coursplay helper is useless for the fieldwork.
Map:Volksvalley v2.2
Please respond quickly.
JHP36

Ps: Sorry for the bad English (Google translator;))                 

https://pastebin.com/hsk9LMRQ Moved to pastebin because all logs should be in pastebin or gist -- pops64

**Comment by pops64** [comment]
http://courseplay.github.io/courseplay/en/manual/index.html#hud_drivingSettings making sure those are zeroed out. https://github.com/Courseplay/courseplay/wiki

**Comment by JHP36** [comment]
Good Morning,
The problem has been fixed for me by the reset of the machines for the first time. Nevertheless, it sometimes comes before the device thinks its center would be 5m next to it for example a baler. The problem is with me, however, only since one of the last patches.

**Comment by pops64** [comment]
Most tools have the center of the course go through the tool. These are automatically​ set and have to be reset to zero manually​ on course finish. Closed to keep issues area clean
