### ISSUE TITLE
DLC Big Bud and GRÉGOIRE-BESSON SPSL 9

### ISSUE THREAD

**Issue by MoslessNeo** [Courseplay/courseplay#2062]
The GRÉGOIRE-BESSON SPSL 9 from the DLC Big Bud does not work properly.
Routes are generated with a horizontal distance from the field.

<img src="https://rmctgw-ch3302.files.1drv.com/y4mLLxsfA3tooDCwjcWjQL_hTO8g5DrWVkZkc4UrC5COxeH6pOq-D9_f1KWiClLV5db0W8I5HH6ghtMRnHcXbEx7DajynZqRfApAlRetQZOsnLYP_Ds_IL_2pQeUNwOxiWq6BpYgrdNRwzQk1GA6vRC9Mb8XLl55WqiaxQwtmQlCGbvuIu1sn0ssAzLboWOaZRP7usHVTW803OM-Yeo6G1-g43E7f2lbbYFzb6JRY4qL5Y?width=1920&height=1080&cropmode=none" width="1920" height="1080" />

**Comment by pops64** [comment]
#2052
