### ISSUE TITLE
Mode 8 Callstack HUD.lua Line 783

### ISSUE THREAD

**Issue by ryboth** [Courseplay/courseplay#2063]
If i activate Mode 8 via HUD this callstack

Error: Running LUA method 'draw'.
C:/Users/Ryboth/Documents/My Games/FarmingSimulator2017/mods/zzz_courseplay/hud.lua:783: attempt to get length of field 'easyFillTypeList' (a nil value)
Error: Running LUA method 'draw'.
C:/Users/Ryboth/Documents/My Games/FarmingSimulator2017/mods/zzz_courseplay/hud.lua:783: attempt to get length of field 'easyFillTypeList' (a nil value)

I played a Custom Map with many Custom Mods on a NEW Savegame

Error occured after i installed Vers 0131
Log.txt attached....
[log.txt](https://github.com/Courseplay/courseplay/files/994483/log.txt)

**Comment by pops64** [comment]
try again with version 138 or higher and report back

**Comment by ryboth** [comment]
First Report: Mod Issue.... MB MP4 Truck caused the Callstack... Vanilla Trucks worked fine

**Comment by pops64** [comment]
Can We close here?

**Comment by pops64** [comment]
Closed assumed fixed.
