### ISSUE TITLE
No Hud on vehicle specific

### ISSUE THREAD

**Issue by Anonymous-any** [Courseplay/courseplay#2064]
Hi like the tittle say I only have no HUD on this vehicle
adding Courseplay to "NLD_aHelmerBV_HKL.MAN"
and no log error all my other vehicle can show HUD I tried to change the name to be sure it's 1st loaded but same issue have you anyway?

Best regards to CP

**Comment by pops64** [comment]
It has to have the drivable vehicle spec. Does it work with giants AI? Did you try left ctrl + delete

**Comment by Anonymous-any** [comment]
Omg i'm so sorry to disturb you can delete my request yes I was change how to open Hud in this vehicle like Ctrl+del back to right+clic so sorry Br :)
