### ISSUE TITLE
Unload point at reverse crash

### ISSUE THREAD

**Issue by Anonymous-any** [Courseplay/courseplay#2066]
I don't know if already reported I try to make multiple cross points merge simple way to go and unload at reverse then crash courseplay with:
`
Warning (LUA): 'getWorldTranslation': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
LUA call stack:
  =blablapath/Downloads/My Games/FarmingSimulator2017/mods/ZZZ_Courseplay_beta/toolManager.lua (1379) : getWorldTranslation
  =blablapath/Downloads/My Games/FarmingSimulator2017/mods/ZZZ_Courseplay_beta/drive.lua (286) : handleUnloading
  =blablapath/Downloads/My Games/FarmingSimulator2017/mods/ZZZ_Courseplay_beta/base.lua (890) : drive
  dataS/scripts/vehicles/Vehicle.lua (2598) : update
  dataS/scripts/network/Server.lua (56) : update
  dataS/scripts/BaseMission.lua (1508) : update
  dataS/scripts/FSBaseMission.lua (2171) : update
  dataS/scripts/missions/mission00.lua (333) : update
  dataS/scripts/main.lua (1876) : update
Warning (LUA): 'worldToLocal': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
LUA call stack:
  =blablapath/Downloads/My Games/FarmingSimulator2017/mods/ZZZ_Courseplay_beta/toolManager.lua (1380) : worldToLocal
  =blablapath/Downloads/My Games/FarmingSimulator2017/mods/ZZZ_Courseplay_beta/drive.lua (286) : handleUnloading
  =blablapath/Downloads/My Games/FarmingSimulator2017/mods/ZZZ_Courseplay_beta/base.lua (890) : drive
  dataS/scripts/vehicles/Vehicle.lua (2598) : update
  dataS/scripts/network/Server.lua (56) : update
  dataS/scripts/BaseMission.lua (1508) : update
  dataS/scripts/FSBaseMission.lua (2171) : update
  dataS/scripts/missions/mission00.lua (333) : update
  dataS/scripts/main.lua (1876) : update
Warning (LUA): 'getWorldTranslation': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType`

![1](https://cloud.githubusercontent.com/assets/25174503/25984156/433c6b5c-36e9-11e7-9386-bbd289eec85b.jpg)
Br CP

**Comment by pops64** [comment]
See #2050
