### ISSUE TITLE
Unable to find download for v5.01 (FS17)

### ISSUE THREAD

**Issue by Svish** [Courseplay/courseplay#2068]
I can't find a download for **v5.01 (FS17)** anywhere? At [courseplay.github.io/courseplay](https://courseplay.github.io/courseplay/en/index.html) I can't seem to find any downloads at all (except for an FS15 one on the front page), and here on github the latest release I can see is **v4.01 (FS15)**. 😕

Have I gone blind, am I missing something super obvious, or is the download actually missing? 🤔

**Comment by pops64** [comment]
http://courseplay.github.io/courseplay/en/installation/index.html closed

**Comment by Svish** [comment]
Yeah, but where is the download? It says "Copy the archive file ...", but where do I get that file?

I see a link to "Farming Simulator 17 Update" and to "Developer Version", but no "v5.01", which is the latest mentioned in [the changelog](http://courseplay.github.io/courseplay/en/changelog/index.html) 😟

**Comment by pops64** [comment]
If you read all the way down the page about half way down is

>  Get the latest developer version here: Developer Version

 CP has yet to release you only have the dev version atm.

**Comment by Svish** [comment]
Oooh, I see. Should be a note about that on the installation page 😃
