### ISSUE TITLE
Machine center is misrecognized (NEW)

### ISSUE THREAD

**Issue by JHP36** [Courseplay/courseplay#2070]
Since my last attempt to get an answer is not taken very seriously is here a new;)
Just look at the pictures and tell me what I can do against it.
![fsscreen_2017_05_13_08_30_06](https://cloud.githubusercontent.com/assets/28629332/26023192/0f5c1840-37b7-11e7-8190-edb8b7b4af79.png)
![fsscreen_2017_05_13_08_30_16](https://cloud.githubusercontent.com/assets/28629332/26023195/158e96b6-37b7-11e7-8106-47ee9eae4a43.png)

**Comment by dkfiremann** [comment]
What is the settings under the Tractor symbol?

**Comment by JHP36** [comment]
what do you mean?

**Comment by dkfiremann** [comment]
The settings under the tab next to the one you have selected.

**Comment by JHP36** [comment]
Das erscheint wenn ich mein Mausrad drücke

**Comment by JHP36** [comment]
This appears when I press my mouse wheel

**Comment by andreasthu** [comment]
you missunderstand, open the tab in the tractor icon and have an ey on the third row.
there should stand no number, only ---
see the pic:
![bild1](https://cloud.githubusercontent.com/assets/24860501/26023619/da661262-37c0-11e7-904a-31286c68fc94.png)

lg
andreas

**Comment by JHP36** [comment]
I'm just dumb haha ​​thank you thank you thank you

**Comment by pops64** [comment]
If I close an issue you can always post there if your not satisfied with the answer. No need to make a new issue. This seems solved closed to keep issues area clean.
