### ISSUE TITLE
Profi Class Sprayer Errors

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#2072]
[log.txt](https://github.com/Courseplay/courseplay/files/999097/log.txt)
The Profi Class Sprayer Mods (available from within the game's mods selection) are registering as 26M width instead of 36.
Vanilla and mod maps
Profi Class 5036 & Profi Class 7500.

**Comment by lcc1211** [comment]
Does "Vehicle Adjustment" mean the mod maker has to change something or are we waiting for CP changes?

**Comment by pops64** [comment]
It means that we have to adjust something. It just for our internal use letting us know the level of involvement that is required. Do you have a clean link to the mod in question?

**Comment by lcc1211** [comment]
These come from within the game when you are on the options page choose mods and you can find under sprayers.

**Comment by pops64** [comment]
If this is your mod https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=73532&title=fs2017

Then replace your specialtools.lua with the file in this zip.
[specialTools.zip](https://github.com/Courseplay/courseplay/files/1151109/specialTools.zip)

In the future, if we update special tools then the lines I added were on 183 to 186, 754 and 755

**Comment by lcc1211** [comment]
This didn't fix it. Latest version of CP does however register 36.2 meters, but the game says it is 36. Close enough I suppose.

**Comment by pops64** [comment]
Yea what the game says it is it not a 100 precent correct CP ussally calculates the correct number. Close this has you say it has been fix

**Comment by pops64** [comment]
Collapsing mod issues into one thread. #2231
