### ISSUE TITLE
Unloading problem

### ISSUE THREAD

**Issue by Blackmankot** [Courseplay/courseplay#2077]
Good afternoon! Since version 5.01.00101, vehicles with trailers have stopped loading. Here's a video.
https://youtu.be/9Xw_di3l_oo

P.S. The same sad situation (loading), described by me in a post of  #1967  April 11, 2017.

**Comment by cronuss64** [comment]
I was having a similar issue when using GTX Mods Custom Road Train Pack... I use 3 trailers with dollys to load at field to silo in grain transport mode, but it drives to silo and goes straight past without unloading anything... It works with a single trailer but not with any more than 1... I have tried with various trucks and trailers but it is still the same... I have downgraded to 5.01.00125 for the time being as this version works...

**Comment by Blackmankot** [comment]
@cronuss64  Simply very sad, when in the early versions of the course the unloading worked. And in the latter does not work ...

**Comment by pops64** [comment]
@blackmankot your issue is most likely the code wasn't designed for unloading that modded truck. @cronuss64 your issue sounds completely different. Please make a separate issue with debug channel 2 running and post that log. If you're using modded trailers try with Giants trailers and let's us know about if that worked.

**Comment by Blackmankot** [comment]
@pops64 In version 5.01.00097 and in earlier versions, everything worked fine! Mods has not changed! The version of the course has changed and since 5.01.00101 mods have not started to unload correctly. Video.
https://youtu.be/b3Twt6yBaGI

**Comment by pops64** [comment]
Could you run with debug channel two. Thanks. It maybe related to cronuss issue now that I have seen the debug from his issue. Just would like to confirm.

**Comment by Blackmankot** [comment]
I correctly understood - to include a mode of debugging 2 and to test? And attach a log.

**Comment by pops64** [comment]
Yea

**Comment by pops64** [comment]
Try with version 143 or higher and report back

**Comment by theSeb1979** [comment]
I am not the OP, but I can confirm that I was having this issue with a version from about ten ago. With this latest version it is working.

**Comment by pops64** [comment]
@Blackmankot What is the status of this?

**Comment by Blackmankot** [comment]
@pops64  Past days I was busy. Today I will test.

**Comment by Blackmankot** [comment]
@pops64  I conducted the test with the debugging mode 2. I want to pay attention to the fact. When you are in the transport during unloading, the unloading is not complete. And if not in the transport, then the unloading is complete, but the process itself occurs simultaneously from two bodies.
[log.txt](https://github.com/Courseplay/courseplay/files/1029453/log.txt)
https://youtu.be/MzjIsNF4cng

**Comment by pops64** [comment]
Yea I would need a log for each test case. Has debug channel 2 prints alot of information. And Mode 5 can't handle unloading. Only mode 1 and 2. There is a known problem in 2 that it will start to unload but not stop driving until it reaches the center.

**Comment by Blackmankot** [comment]
On which debug channels do I have to perform separate tests for more clarity?

**Comment by pops64** [comment]
Just channel two. That channel spits a lot of information which why I asked.

**Comment by Blackmankot** [comment]
Good! I only test on the second channel each mod separately. Tomorrow.

**Comment by Blackmankot** [comment]
Here is a separate, single test. I am in transport.
![2017-05-29_13-27-04](https://cloud.githubusercontent.com/assets/26131714/26537516/d4316306-4472-11e7-81d8-37a198b3b7ed.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/1034939/log.txt)

The next test, I'm not in the transport at the time of unloading.
![2017-05-29_13-32-08](https://cloud.githubusercontent.com/assets/26131714/26537616/96f67cc8-4473-11e7-98e1-775135308d66.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/1034944/log.txt)

Next transport.
![2017-05-29_13-37-47](https://cloud.githubusercontent.com/assets/26131714/26537751/6fa6429c-4474-11e7-8e6e-016f2dc83276.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/1034954/log.txt)

![2017-05-29_14-11-19](https://cloud.githubusercontent.com/assets/26131714/26538360/e69f4e1c-4478-11e7-86dc-9407f22aa04b.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/1034962/log.txt)

**Comment by Blackmankot** [comment]
@pops64 Good afternoon! Here is my personal mail - blackmankot@gmail.com . If you do not mind, I have questions not related to the course.

**Comment by MoslessNeo** [comment]
The CP has many problems in the grain transport part, even using a single trailer the load is not completely discharged.
I do not know what was implemented but before he recognized several trailers.

**Comment by Blackmankot** [comment]
At me with the semitrailer it is completely unloaded.

**Comment by pops64** [comment]
@MoslessNeo Are sure you are using the most current version of CP. That problem should have been fixed along time ago.

**Comment by Blackmankot** [comment]
@pops64  I use the latest version of the course, the problem of unloading vehicles with a trailer remains ...

**Comment by pops64** [comment]
Well, I am not too sure what the issue is because it is properly detecting both the trailer and the dump truck. And why being in the truck and not makes a difference. There had to be something else you did differently. I will look into it again this weekend.

**Comment by Blackmankot** [comment]
Unfortunately I do not remember where I shook them. Here are the links from the disk.
https://yadi.sk/d/w8i2B9SO3LYC8d
But please do not distribute this mod.
https://yadi.sk/d/du0CuBn-3LYCA5

**Comment by Blackmankot** [comment]
@pops64  I am glad to help.

**Comment by pops64** [comment]
Collapsing mod issues into one thread. #2231
