### ISSUE TITLE
looking for help (not an issue)

### ISSUE THREAD

**Issue by tsikows** [Courseplay/courseplay#2080]
im attempting to make a minor change to my cp file and was wondering if pops or someone would be able to give me a minute of their time to assist. i would like to make certain modes like mode 1 (grain transport) where it starts the course over after completing it. any help would be great

**Comment by pops64** [comment]
What do you mean start over after completing it? If your using the run counter if you hit continue it will reset the run counter to zero and if your not it will run contentiously

**Comment by tsikows** [comment]
using a custom recoreded course. im trying to get a seeding course to run continuously without having to click that continue button.

**Comment by pops64** [comment]
So in mode 4? When it is finished with seeding your want it to run the fill course then go back to seeding that same field?

**Comment by tsikows** [comment]
Yes. In mode 4 rather than cp running the seeding course and stopping when finished, I would like for it to "continue" on its own and run the course over and over again. I know it sounds pointless and counter productive but there is a method to my madness.

**Comment by pops64** [comment]
change line77-79 to 
```
-- allowedToDrive = false;
-- CpManager:setGlobalInfoText(self, 'WORK_END');
-- hasFinishedWork = true;
```

It may work also if you report any bugs make sure you can reproduce them using the official beta version of CP before you report them. If this doesn't work I am not sure how else to help you

**Comment by tsikows** [comment]
thats exactly what is in those lines already. ill keep working on it and see if i cant make things work. thanks for taking a look.

**Comment by pops64** [comment]
the `--` is not in those lines. Add them in at the beginning of each line

**Comment by tsikows** [comment]
ahhh thanks for pointing that out. IT WORKED!!! thank you so much!

**Comment by tsikows** [comment]
only other thing im curious about is if we can make changing wait time just like changing work width. where after you get past a certain width (time) it will increase in larger increments. so say after a wait time of 5 minutes the time will increase by one minute rather than one second. 

i could see that being benificial in general for any course, not just my current situation. 

thank you again for the assistance pops

**Comment by pops64** [comment]
It may be possible to add a toggle switch change from secs to mins. I would have to look at the code when I get some time but for now I will mark this a suggestion and close this out.

**Comment by tsikows** [comment]
If someone has time again, I'm looking to get this same principle working for fieldwork mode as well. I tried adding the -- to the same lines in mode 6 but it didn't have the same result. Thanks for any help you can provide.

**Comment by pops64** [comment]
It should be lines 40-42
```
--allowedToDrive = false
--CpManager:setGlobalInfoText(vehicle, 'WORK_END');
--hasFinishedWork = true
```

**Comment by tsikows** [comment]
yep actually 38-40 for my version, but regardless, tractors work, but oddly dont follow their assigned wait time. if set at 30 sec he was sitting for 18. when set at 60 sec he waited for 28. kind of odd but i guess i can deal with that. 

with those 3 lines changed combines wont continue on though, they just stop at my "end working area" wait point and stay there forever. 

if you dont have time to look into it right now, its not a problem

**Comment by tsikows** [comment]
got it, had to change 2 lines in drive lua to true as well as 1 in mode 6 under combines. thanks for the help again. i should be done with my random comments and questions now :)

**Comment by pops64** [comment]
Yea combines are sort of separate from other work tools in mode 6.

**Comment by tsikows** [comment]
Im  back with a new abnormal change I would like to make. Fields on my current (16x) map are massive. like half the length of the map big. so when in combi and overload mode combine is full and waiting for about a minute before the tipper makes its way to the combine to unload. what i would like to do is make tippers follow tractor in front of them as if the combine is a chopper. that way i always have another tipper there ready to unload so he is never waiting. is this possible? thanks for taking a look.

**Comment by pops64** [comment]
That would involve a lot more and would require a big change. We may look into this after 19 is out but in the short time 17 has left I doubt we will have time to look into this

**Comment by tsikows** [comment]
my code is actually still for 15. doubt that makes it any easier. i was hoping it would be as simple as changing a couple numbers.

**Comment by pops64** [comment]
No, It would involve a lot more. Off the top of my head you would have to create code for it know how far back it is to follow, how to follow etc. Might be possible to fool CP into thinking it is a chaff harvester but that would require looking at out how chaff harvesters work and adjusting it for combines which would also involve changing the distance at which it follows etc. Also we no longer support 15 so any code changing like this would only be made to 17.
