### ISSUE TITLE
Nil Error line 1008

### ISSUE THREAD

**Issue by Liquid515** [Courseplay/courseplay#2082]
Error: Running LUA method 'update'.
C:/Users/Liqui/Documents/My Games/FarmingSimulator2017/mods/ZZZ_CoursePlay/toolManager.lua:1008: bad argument #4 to 'format' (number expected, got nil)
[log.txt](https://github.com/Courseplay/courseplay/files/1016389/log.txt)

**Comment by Liquid515** [comment]
that is the latest version 143

**Comment by dkfiremann** [comment]
When  are you getting this error? 
Model of vehicle, implement, map and what you are trying to do.

**Comment by pops64** [comment]
Leave off debug channel two for now. I will have a fix for it in a bit

**Comment by pops64** [comment]
Fixed Closed

**Comment by Liquid515** [comment]
thanks pops
