### ISSUE TITLE
game keeps freezing on me 

### ISSUE THREAD

**Issue by willie2016** [Courseplay/courseplay#2084]
im currently using version v01.0144  and after 2 minutes ingame my machinary start to go a little crazy and my game freezes , see in photo below 
![farmingsimulator2017game 2017-05-21 00-36-49-637](https://cloud.githubusercontent.com/assets/24280974/26280038/f4909998-3dbd-11e7-9cd4-bc0ef4d092ca.jpg)

**Comment by pops64** [comment]
Your using version 143 try again with 144 closed to keep the issues area clean
