### ISSUE TITLE
Multiplayer/Server Support still not Enabled?

### ISSUE THREAD

**Issue by UberSlackr** [Courseplay/courseplay#2085]
I personally have put off playing FS17, waiting for Courseplay to be enabled for MP/Dedi Servers.
FS17 imo is boring in single player mode.

Could you please just enable multiplayer support. Adding supports for other mods before supporting the CORE functions of the game (yes MP is a core function) is a little ridiculous in my opinion.

**Comment by Blackmankot** [comment]
At the moment this is not possible. Here is the answer of the authors. #2033 #1729
If there are no additional questions, close the question.

**Comment by pops64** [comment]
Yea. Supporting multiplayer is a little more than just turning it on. But won't happen until CP is officially out of beta and if we find the time to debug multiplayer. Closed to keep issues area clean.
