### ISSUE TITLE
Game Freez

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#2086]
Hello! I have the following problem! In the game at the maize harvest With Original New Holland FR Orginal Steyr Tarrus and Orginal pushers! Map Losshügelland! The following error occurs and the game freezes!

C: / Users / Nemesis / Documents / MyGames / FarmingSimulator2017 / mods / ZZZ_courseplay / toolManager.lua: 1008: bad argument # 4 to 'format' (number expected, got nil)
Error: Running LUA method 'update'.

**Comment by pops64** [comment]
Before reporting any bugs make sure you are running the most current version. closed this was fixed in 144
