### ISSUE TITLE
level and compact

### ISSUE THREAD

**Issue by willie2016** [Courseplay/courseplay#2087]
i am using the latest version of CP and i recorded my course with the fendt 939 and the blade for levelling and compacting and click drive now ( from first way point) so after few seconds it realised there was no grass to level and compact and it went to pause point and stayed there , so i then recorded the course with tractor and trailer and tipped the load well inside the bunker and drove back to field , i then set up 3 more tractors to run the same course , but when the first tractor came back to unload everything was fine untill the tractor and trailer began to reverse back in the bunker then the fendt 939 with blade decided it would also reverse back and they get caught in collision , this is happening everytime when i record a course

**Comment by dkfiremann** [comment]
So how does you courses look like?

**Comment by willie2016** [comment]
what do you mean what do my courses look like ? i started maybe less than half way inside bunker and started course recording , i drove outside bunker then slightly off to the left but stayed in line with bunker did not go outside the walls , set my waitpoint then selected reverse mode and reversed back just outisde the bunker and stopped recording course and saved it , then i set up the settings stop all on courseplay , automatic speed and height , mode levelling and compacting , reverse unload , blade width 6 meters , is that what you mean ?

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki Pictures log, debug channel 10

**Comment by dkfiremann** [comment]
Have you seen and may followed some of the youtube videos on how to use this courseplay function? 
https://www.youtube.com/watch?v=40FDWBvFqKo&t

**Comment by Symbob** [comment]
I think this is the same problem I was having here https://github.com/Courseplay/courseplay/issues/1832 .

Record the levelling and compacting course again but make sure the first waypoint is just inside the bunker and the second waypoint is just outside the bunker.  That fixed the problem for me.

**Comment by willie2016** [comment]
Thats more or less the way i recorded it but thanks Symbob , and yes dkfiremann iv watched them tutorials

**Comment by pops64** [comment]
Still can't fix or solve the problem with out https://github.com/Courseplay/courseplay/wiki Pictures, log, debug channel 10

**Comment by willie2016** [comment]
[dbg10 lp104036] GTXM Big M (#1): getSaveAttributesAndNodes(): nodes
        <courseplay aiMode="6" courses="" openHudWithMouse="true" lights="1" visualWaypointsStartEnd="true" visualWaypointsAll="false" visualWaypointsCrossing="false" waitTime="0" siloSelectedFillType="nil" runNumber="11" runCounter="0" runCounterBool="false" saveFuelOption="true" >
           <speeds useRecordingSpeed="true" reverse="6" turn="10" field="24" max="45" />
           <combi tipperOffset="0.0" combineOffset="0.0" combineOffsetAutoMode="true" fillFollow="50" fillDriveOn="90" turnDiameter="7" realisticDriving="true" allwaysSearchFuel="false" />
           <fieldWork workWidth="14.0" ridgeMarkersAutomatic="true" offsetData="0.0;0.0;0.0;false;0.0;0.0" abortWork="0" refillUntilPct="100" turnOnField="true" oppositeTurnMode="false" manualWorkWidth="0.0" ploughFieldEdge="false" />
           <mode10 leveling="true"  CourseplayersOnly="false" searchRadius="50" maxSiloSpeed="20" shieldHeight="0.3" automaticSpeed="true"  automaticHeight="true" bladeOffset="0.0"/>
        </courseplay>
[dbg10 lp104036] FR850 (#7): getSaveAttributesAndNodes(): nodes
        <courseplay aiMode="6" courses="1" openHudWithMouse="true" lights="1" visualWaypointsStartEnd="true" visualWaypointsAll="false" visualWaypointsCrossing="false" waitTime="0" siloSelectedFillType="nil" runNumber="11" runCounter="0" runCounterBool="false" saveFuelOption="true" >
           <speeds useRecordingSpeed="true" reverse="6" turn="10" field="24" max="43" />
           <combi tipperOffset="0.0" combineOffset="0.0" combineOffsetAutoMode="true" fillFollow="50" fillDriveOn="90" turnDiameter="11" realisticDriving="true" allwaysSearchFuel="false" />
           <fieldWork workWidth="3.0" ridgeMarkersAutomatic="true" offsetData="0.0;0.0;0.0;false;5.6;0.0" abortWork="0" refillUntilPct="100" turnOnField="true" oppositeTurnMode="false" manualWorkWidth="0.0" ploughFieldEdge="false" />
           <mode10 leveling="true"  CourseplayersOnly="false" searchRadius="50" maxSiloSpeed="20" shieldHeight="0.3" automaticSpeed="true"  automaticHeight="true" bladeOffset="0.0"/>
        </courseplay>
[dbg10 lp104036] John Deere 6R MW: getSaveAttributesAndNodes(): nodes
        <courseplay aiMode="5" courses="" openHudWithMouse="true" lights="1" visualWaypointsStartEnd="true" visualWaypointsAll="false" visualWaypointsCrossing="false" waitTime="0" siloSelectedFillType="nil" runNumber="11" runCounter="0" runCounterBool="false" saveFuelOption="true" >
           <speeds useRecordingSpeed="true" reverse="6" turn="10" field="24" max="53" />
           <combi tipperOffset="0.0" combineOffset="0.0" combineOffsetAutoMode="true" fillFollow="50" fillDriveOn="90" turnDiameter="7" realisticDriving="true" allwaysSearchFuel="false" />
           <fieldWork workWidth="3.0" ridgeMarkersAutomatic="true" offsetData="0.0;0.0;0.0;false;0.0;0.0" abortWork="0" refillUntilPct="100" turnOnField="true" oppositeTurnMode="false" manualWorkWidth="0.0" ploughFieldEdge="false" />
           <mode10 leveling="true"  CourseplayersOnly="false" searchRadius="50" maxSiloSpeed="20" shieldHeight="0.3" automaticSpeed="true"  automaticHeight="true" bladeOffset="0.0"/>
        </courseplay>
[dbg10 lp104036] John Deere 6R MW (#2): getSaveAttributesAndNodes(): nodes
        <courseplay aiMode="2" courses="" openHudWithMouse="true" lights="3" visualWaypointsStartEnd="false" visualWaypointsAll="false" visualWaypointsCrossing="false" waitTime="0" siloSelectedFillType="wheat" runNumber="11" runCounter="0" runCounterBool="false" saveFuelOption="true" >
           <speeds useRecordingSpeed="true" reverse="6" turn="17" field="30" max="53" />
           <combi tipperOffset="0.0" combineOffset="5.1" combineOffsetAutoMode="false" fillFollow="10" fillDriveOn="100" turnDiameter="16" realisticDriving="true" allwaysSearchFuel="false" />
           <fieldWork workWidth="3.0" ridgeMarkersAutomatic="true" offsetData="0.0;0.0;0.0;false;0.0;0.0" abortWork="0" refillUntilPct="100" turnOnField="true" oppositeTurnMode="false" manualWorkWidth="0.0" ploughFieldEdge="false" />
           <mode10 leveling="true"  CourseplayersOnly="false" searchRadius="50" maxSiloSpeed="20" shieldHeight="0.3" automaticSpeed="true"  automaticHeight="true" bladeOffset="0.0"/>
        </courseplay>
[dbg10 lp104036] Landini Legend 160 (#3): getSaveAttributesAndNodes(): nodes
        <courseplay aiMode="2" courses="2" openHudWithMouse="true" lights="3" visualWaypointsStartEnd="false" visualWaypointsAll="false" visualWaypointsCrossing="false" waitTime="0" siloSelectedFillType="wheat" runNumber="11" runCounter="0" runCounterBool="false" saveFuelOption="true" >
           <speeds useRecordingSpeed="true" reverse="6" turn="22" field="33" max="52" />
           <combi tipperOffset="0.0" combineOffset="5.2" combineOffsetAutoMode="false" fillFollow="10" fillDriveOn="100" turnDiameter="12" realisticDriving="true" allwaysSearchFuel="false" />
           <fieldWork workWidth="3.0" ridgeMarkersAutomatic="true" offsetData="0.0;0.0;0.0;false;0.0;0.0" abortWork="0" refillUntilPct="100" turnOnField="true" oppositeTurnMode="false" manualWorkWidth="0.0" ploughFieldEdge="false" />
           <mode10 leveling="true"  CourseplayersOnly="false" searchRadius="50" maxSiloSpeed="20" shieldHeight="0.3" automaticSpeed="true"  automaticHeight="true" bladeOffset="0.0"/>
        </courseplay>
[dbg10 lp104036] 6030 (#4): getSaveAttributesAndNodes(): nodes
        <courseplay aiMode="2" courses="2" openHudWithMouse="true" lights="3" visualWaypointsStartEnd="false" visualWaypointsAll="false" visualWaypointsCrossing="false" waitTime="0" siloSelectedFillType="wheat" runNumber="11" runCounter="0" runCounterBool="false" saveFuelOption="true" >
           <speeds useRecordingSpeed="true" reverse="6" turn="21" field="27" max="50" />
           <combi tipperOffset="0.0" combineOffset="5.2" combineOffsetAutoMode="false" fillFollow="10" fillDriveOn="100" turnDiameter="17" realisticDriving="true" allwaysSearchFuel="false" />
           <fieldWork workWidth="3.0" ridgeMarkersAutomatic="true" offsetData="0.0;0.0;0.0;false;0.0;0.0" abortWork="0" refillUntilPct="100" turnOnField="true" oppositeTurnMode="false" manualWorkWidth="0.0" ploughFieldEdge="false" />
           <mode10 leveling="true"  CourseplayersOnly="false" searchRadius="50" maxSiloSpeed="20" shieldHeight="0.3" automaticSpeed="true"  automaticHeight="true" bladeOffset="0.0"/>
        </courseplay>
[dbg10 lp104036] Valtra Valmet 8950 (#5): getSaveAttributesAndNodes(): nodes
        <courseplay aiMode="2" courses="2" openHudWithMouse="true" lights="3" visualWaypointsStartEnd="false" visualWaypointsAll="false" visualWaypointsCrossing="false" waitTime="0" siloSelectedFillType="wheat" runNumber="11" runCounter="0" runCounterBool="false" saveFuelOption="true" >
           <speeds useRecordingSpeed="true" reverse="6" turn="22" field="24" max="43" />
           <combi tipperOffset="0.0" combineOffset="5.1" combineOffsetAutoMode="false" fillFollow="10" fillDriveOn="100" turnDiameter="15" realisticDriving="true" allwaysSearchFuel="false" />
           <fieldWork workWidth="3.0" ridgeMarkersAutomatic="true" offsetData="0.0;0.0;0.0;false;0.0;0.0" abortWork="0" refillUntilPct="100" turnOnField="true" oppositeTurnMode="false" manualWorkWidth="0.0" ploughFieldEdge="false" />
           <mode10 leveling="true"  CourseplayersOnly="false" searchRadius="50" maxSiloSpeed="20" shieldHeight="0.3" automaticSpeed="true"  automaticHeight="true" bladeOffset="0.0"/>
        </courseplay>
[dbg10 lp104036] 900 Vario (#6): getSaveAttributesAndNodes(): nodes
        <courseplay aiMode="10" courses="" openHudWithMouse="true" lights="1" visualWaypointsStartEnd="true" visualWaypointsAll="false" visualWaypointsCrossing="false" waitTime="0" siloSelectedFillType="wheat" runNumber="11" runCounter="0" runCounterBool="false" saveFuelOption="true" >
           <speeds useRecordingSpeed="true" reverse="6" turn="10" field="24" max="63" />
           <combi tipperOffset="0.0" combineOffset="0.0" combineOffsetAutoMode="true" fillFollow="50" fillDriveOn="90" turnDiameter="9" realisticDriving="true" allwaysSearchFuel="false" />
           <fieldWork workWidth="4.0" ridgeMarkersAutomatic="true" offsetData="0.0;0.0;0.0;false;0.0;0.0" abortWork="0" refillUntilPct="100" turnOnField="true" oppositeTurnMode="false" manualWorkWidth="4.0" ploughFieldEdge="false" />
           <mode10 leveling="true"  CourseplayersOnly="true" searchRadius="50" maxSiloSpeed="9" shieldHeight="0.3" automaticSpeed="false"  automaticHeight="true" bladeOffset="0.1"/>
        </courseplay>

**Comment by dkfiremann** [comment]
So you added a very small part of a log? 
Have you looked at the wiki, that explain what to do, to give correct information? 
What about pictures?

**Comment by pops64** [comment]
Closed due to inactivity and no response to requested information
