### ISSUE TITLE
Steering doesn't center after CP hands back vehicle

### ISSUE THREAD

**Issue by ceemosp** [Courseplay/courseplay#2088]
I am using keyboardsteer and dc and experienced the following issue:
After using CP the steering doesn't return to center when in manual mode - meaning, the last set steering angle is maintained - thus rendering the vehicle very much non-driveable. 
The only solution (so far) is to save the game and reload it, as then, all is back to "normal".
This happens both on "vanilla" vehicles as well as on mods.
Unfortunately it is NOT happening all the time, so it is hard to see a pattern for me as to when it happens.

_> I assume a connection/conflict with the autoRotateBackFx values of keyboardsteer. It seems as if CP somehow alters values for the steering as it takes over and "forgets" to hand those back to the game when ending the task.
I will try to see if disabling keyboardsteer will prevent this from happening, although it is kind of "essential" for me, as it makes "driving" with a keyboard much more acceptable._
EDIT: False assumption, as **I disabled keyboardsteer and the issue occurred again**
Back to square one it is :/

**Comment by pops64** [comment]
From my understanding CP doesn't even touch the steering angle. We just pass to giants the point on the map where we would like to go and Giants preforms the action. I would have to say you computer hardware and Giants software is conflict. We might in reverse but not 100 I think we still use drive to point but have to take into account that it doesn't support reverse so we have to measure angle of the tool and correct by adjusting the point. I would try with just CP running no mods and a different computer.

**Comment by Ridlerr** [comment]
I think your problem is DriveControl, it has the function of blocking the direction, which I can not remember in FS2015, the problem is that the default key for this is M, it is often when writing routes, if you use the letter M activates this function and then the vehicle loses the steering return.
This function is signaled by a red steering wheel on the HUD, and it is active simply press the M again to return to normal.

Sorry for the bad english

**Comment by pops64** [comment]
Yea that sounds like the problem. That why we ask for a log.  https://github.com/Courseplay/courseplay/wiki

**Comment by ceemosp** [comment]
See, that is how easily one can be led into the wrong direction ;)
Ridlerr was spot on with his assumption. 
*irony mode ON* 
I dearly love undocumented functions in scripts/mods 
*irony mode OFF*
Case can be closed - thank you all for your swift responses.
Cheers
