### ISSUE TITLE
Harvester is active while returning to the starting point of field

### ISSUE THREAD

**Issue by pajajezek** [Courseplay/courseplay#2089]
Once the harvester completes work in the field and returns to the starting point, it is still on (still harvests). This causes its slow speed and removes the fertilizer from the already set field. Version 5.01.00144.

**Comment by pops64** [comment]
? https://github.com/Courseplay/courseplay/wiki

**Comment by pajajezek** [comment]
Sorry for my bad english. I hope, this image will help.
Map is basic Goldcrest Valley with only 1 mod - courseplay.
![fs17](https://cloud.githubusercontent.com/assets/18664071/26397870/f784b0f0-4077-11e7-9ef4-bc7366bba223.png)
Do you need any kind of game log?

**Comment by pops64** [comment]
Well removing the ungrown part of the field sounds like a giants bug or you hve a deeper issuse with your game.

**Comment by pops64** [comment]
Try again with 145 or higher and report back

**Comment by pajajezek** [comment]
With 145.dev is everything all right. Thank you!

**Comment by pops64** [comment]
Yea if you could just test it and tell us if that fixed your problem then you or us can go ahead a close this issues. Thanks
