### ISSUE TITLE
For some reason, courseplay crash my game.

### ISSUE THREAD

**Issue by Bufley** [Courseplay/courseplay#2090]
[log.txt](https://github.com/Courseplay/courseplay/files/1024120/log.txt)
![fsscreen_2017_05_21_06_45_00](https://cloud.githubusercontent.com/assets/28911742/26382382/8686716a-4034-11e7-9363-f04ed77f0671.png)
![fsscreen_2017_05_21_06_45_14](https://cloud.githubusercontent.com/assets/28911742/26382393/966f65b4-4034-11e7-8df0-3ee867bcb377.png)
![fsscreen_2017_05_21_07_52_28](https://cloud.githubusercontent.com/assets/28911742/26382409/a60ff60a-4034-11e7-8199-6b157c7c9549.png)
![fsscreen_2017_05_21_07_52_38](https://cloud.githubusercontent.com/assets/28911742/26382431/c06d7df6-4034-11e7-9971-8559df600ffe.png)

**Comment by pops64** [comment]
Start by using a Giants overloader non dlc. If that doesn't work start by turning off all mods. AIVE is probably the conflict if it isn't the dlc. CP requires version 1.1 B3 or higher of AIVE to work properly.

**Comment by Bufley** [comment]
thanks for answer !!

**Comment by pops64** [comment]
So did these fix your problem? If so, which one? Because if it is the dlc I will have to look into it. Thanks

**Comment by Bufley** [comment]
Now I will restart the game again without DLC and without mode I will test it, many thanks!

**Comment by pops64** [comment]
Closed due to inactivity
