### ISSUE TITLE
CP and CombineAddon

### ISSUE THREAD

**Issue by Brzzl** [Courseplay/courseplay#2096]
Hi guys!

Don't know, if this issue popped up the other day, but is there any chance to get an auger wagon work with CombineAddon and CP? (https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=70368)

Driver waits at overloading (waiting) point and has to be emptied manually. (using stock vehicles only!)

![fsscreen_2017_05_28_14_54_14](https://cloud.githubusercontent.com/assets/3459971/26528942/be4fd34a-43b6-11e7-8a32-562891ef30d8.png)

Thanks for your help and great work! :)

**Comment by pops64** [comment]
Collapsing mod issues into one thread. #2231
