### ISSUE TITLE
Feature request: 50% Turn on field

### ISSUE THREAD

**Issue by brnl** [Courseplay/courseplay#2097]
I just thought of a neat feature update for the "Turn on field" option. Some fields have trees/obstacles on only one side of the field. For these fields it would be great to be able to specify for which side of the field should Turn on field should be activated.

How I would imagine this, is looking from the starting position as the 'start' and the other side of the field the 'end'. So the four options for the Turn on field could be:
- never
- start side
- end side
- both ends

How are your opinions on this?

**Comment by pops64** [comment]
At this time we are working getting CP ready for release and not accepting any more suggestions at this time. We will come back and look at this at a later date. Closed for now.
