### ISSUE TITLE
Combi mode and new turning system with foragers

### ISSUE THREAD

**Issue by Symbob** [Courseplay/courseplay#2098]
Hi guys, sorry to bother you with another little issue.  The new way the tractors turn when working with the foragers is excellent but there's a slight problem when working in fields where the field boundary is at an angle.  When the tractor turns and then reverses in to position beside the forager it stops before the forager detects the trailer so the forager just sits there waiting for the trailer.  
v5.01.00145 on Goldcrest Valley map.  Let me know if you need any further info.
![fsscreen_2017_05_30_21_34_03](https://cloud.githubusercontent.com/assets/18528850/26604387/1b955a58-4582-11e7-9da7-7963889f155f.jpg)

**Comment by ThomasGaertner** [comment]
is the forager  driven by CP or helper or manual ? for my opinion it should go more forward till it reaches the fruit. then it would be OK.

**Comment by Symbob** [comment]
The forager is driven by CP.  Yes, I think you're right, if it went more forward it would probably work fine.

**Comment by ThomasGaertner** [comment]
please try again with .157 or higher and report. it should be better now, maybe you can try out the new course generation : drive the chopper to the starting corner of the field course and select "vehicle position" as starting corner and create the course. the position will be saved and for the next time you can select 
"last used vehicle position" so you don't need to go to the edge again after reloading the game...

**Comment by Symbob** [comment]
Thanks for this.  Unfortunately I've not been able to test this due to another issue https://github.com/Courseplay/courseplay/issues/2107 which stops the Forager at the end of the field run and stops it from turning because it thinks it's stuck in traffic.

**Comment by Symbob** [comment]
Now tested with v.158 and still get the same problem when the course has been generated the old way.  The forager now appears to move closer to the crop but the tractor and trailer stop just before the forager can detect it.  This only seems to happen in one area of the field presumably because of the angle of the boundary is slightly different there.  Is it possible to make the trailer reverse a few meters further back rather than have the forager moving further forward perhaps?
I've also tried the new course generation and this appears to work much better and doesn't suffer from this same problem.  The only small issue I find with this new method of course generation is that after the forager has completed the headland passes around the field it turns and starts the first straight run without initiating a turn manoeuvre for the tractor and trailer.  This means that the tractor follows the forager as it turns so that it is then driving through the uncut crop instead of changing sides to travel on the harvested side.  I'm not sure if that is easy to understand so I will do a few screenshots later to demonstrate what I mean.

**Comment by ThomasGaertner** [comment]
try again with 171 and report

**Comment by Symbob** [comment]
This works.  The trailer now reverses right back to the forager resolving the problem.  The only thing I've noticed is that the trailer now waits until the forager has completed it's turn manoeuvre before it starts it's own turn manoeuvre on these not equal field edges.  Both trailer and forager turn at the same time on an equal field edge.  Is this by design?

**Comment by pops64** [comment]
Yes. Closed to keep issues area clean.
