### ISSUE TITLE
Turn on field doesn't work for harvester

### ISSUE THREAD

**Issue by pajajezek** [Courseplay/courseplay#2099]
The harvester always leaves the field and then turns. Regardless of settings (turn on field - active / inactive). If there is no place at the end of the field, the combine is stuck.

![turning](https://cloud.githubusercontent.com/assets/18664071/26675618/ec75ac34-46c4-11e7-9548-5c79cfbaf171.png)

**Comment by pops64** [comment]
This is by design. If you don't have enough room on the end add in a headland pass. Closed has this is by design
