### ISSUE TITLE
Unable to see

### ISSUE THREAD

**Issue by Mathew92Gaming** [Courseplay/courseplay#2101]
the letters are too big and cant tell what mods i'm in or what direction and starting corner 
it just says courseplay corner 1-4 and courseplay direction 1-4 which depends on what corner I pick

**Comment by pops64** [comment]
You have either adjusted your game UI scale or your courseplaysettings file got changed. Try deleting courseplaySettings.xml in your savegame folder.

**Comment by Mathew92Gaming** [comment]
Tryed that did not work 
How do I get the drivers to stop driving in a circle 
P.s I did not see this box till my screen changed

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by pops64** [comment]
Closed due to inactivity and no response to requested information
