### ISSUE TITLE
Tractors collide with eachother in combi mode

### ISSUE THREAD

**Issue by scaniafreak** [Courseplay/courseplay#2103]
Hi,

Often when i have a course in combi mode, which requires multiple tractors, they collide with eachother, like in the attached screenshot. Or for example one tractor is on its way back from the forager, and the other tractor is on its way to the forager. It often happens they have a head on collision.

What can be done about this, or is CP not so smart to detect collisions, or reverse from a collision?

![fsscreen_2017_06_03_17_40_13](https://cloud.githubusercontent.com/assets/3944298/26754943/3ae52320-4884-11e7-86da-c2d4128ce4d2.png)

**Comment by scaniafreak** [comment]
Like this...
![fsscreen_2017_06_03_18_02_30](https://cloud.githubusercontent.com/assets/3944298/26755102/de0b905a-4886-11e7-877a-485952dedae0.png)

**Comment by Symbob** [comment]
I've had this problem too https://github.com/Courseplay/courseplay/issues/1994 
I've tried to work around this by keeping some distance between the start and end points of the course. At least by doing that the full trailer heads off in a slightly different direction to the approaching empty trailer.

**Comment by Pacrat** [comment]
Symbob has the right idea.  I try to keep the start and end points around 10-12 tractor lengths (depending on field size, I play 4x maps) apart and moving in opposite directions from the second unloader as well as the harvester.  Went from creating NY style traffic jams with 4-5 tractors and attachments to the Indy 500 where crashes sometimes still happen (depending on the field shape) but are far fewer and quickly cleaned up.

**Comment by Blackmankot** [comment]
@pops64 And I propose to close this issue for cleaning.

**Comment by pops64** [comment]
This may have been fixed in the latest push. Other wise this isn't reproducible so closing this out.
