### ISSUE TITLE
Skipping waypoints while unloading (mode 1)

### ISSUE THREAD

**Issue by brnl** [Courseplay/courseplay#2104]
Hi there,

**First of all, my love for you guys! I don't know if you realize how awesome Courseplay is. Without it, FS 17 would be very boring to play. Thank you so much!!** (So, I've donated 👍 )

I discovered a problem. While unloading in mode 1 grain transport, courseplay skips a few waypoints. This causes the tractor to crash into walls if it should drive around a corner after unloading.

Here is the log. The last run is the one I 'monitored': 
[log - Copy.txt](https://github.com/Courseplay/courseplay/files/1049996/log.-.Copy.txt)

And some screenshots in chronological order:
![20170604003939_1](https://cloud.githubusercontent.com/assets/3243133/26757543/ad69930a-48bf-11e7-99c8-497e3a7f6f6a.jpg)

![20170604003940_1](https://cloud.githubusercontent.com/assets/3243133/26757544/b2401be2-48bf-11e7-93ba-8558143f41fe.jpg)

![20170604003941_1](https://cloud.githubusercontent.com/assets/3243133/26757546/b5b546a8-48bf-11e7-9160-63aa66a89827.jpg)

**Comment by pops64** [comment]
My guess is that it is the tiptrigger that is causing your issue. Drive more straight after leaving the trigger before turning.

**Comment by brnl** [comment]
I've done some more testing. The issue has been introduced in version 136. Version 135 works fine.

Logging for 135: 
[log-135.txt](https://github.com/Courseplay/courseplay/files/1050318/log-135.txt)

Logging for 136: 
[log-136.txt](https://github.com/Courseplay/courseplay/files/1050319/log-136.txt)

Savegame:
[savegame3.zip](https://github.com/Courseplay/courseplay/files/1050321/savegame3.zip)

Courses: 
[CoursePlay_Courses.zip](https://github.com/Courseplay/courseplay/files/1050322/CoursePlay_Courses.zip)

**Comment by brnl** [comment]
What exactly did 135 fix? Can it be undone? Because this skipping is kinda annoying.

**Comment by pops64** [comment]
136 fixed the issue of it not wanting to stop at the unloading point to unload if the courses had a sharp turn through the tip trigger. Tho it should not have affected which way point it is selecting.

**Comment by brnl** [comment]
Do you have an idea how to fix it? I have tried to have a look, but Lua is unknown to me and your code is waay too advanced for me! :-(

**Comment by pops64** [comment]
I haven't yet looked at this in depth. Honestly my 136 fixed shouldn't have changed how CP updates to the next way point.

**Comment by pops64** [comment]
Try again with version 156 or higher

**Comment by brnl** [comment]
Yes! This seems to have fixed it. Thank you very much!

**Comment by pops64** [comment]
Your welcome. Closed to keep the issue area clean.
