### ISSUE TITLE
Courseplay: attempt to perform arithmeticon field

### ISSUE THREAD

**Issue by MarcoHertle** [Courseplay/courseplay#2105]
Hello, 
i started courseplay and wanted to mow but my courseplay said: problem in the picture
![courseplay fehler](https://cloud.githubusercontent.com/assets/29207338/26793569/bad07f58-4a1e-11e7-8023-68c20a7439ba.PNG)

I used in the background an Fendt Vario 820 TMS, Pöttinger Jumbo Combiline6610, Claas Mega 208
Every time when my Fendt wants to turn, my game is freezing and i cant move and cant use my keyboard.

I hope you can help me

Good evening!

**Comment by pops64** [comment]
Turn off all mod vehicles. And turn them back on one by one. You have a poorly made mod some were. Also make sure your using the latest version which is why we ask for the full log.

**Comment by pops64** [comment]
Have you tried this can we close here thanks

**Comment by pops64** [comment]
Closed due to inactivity. And this issues looks like the mod vehicle is missing a component CP needs to work
