### ISSUE TITLE
Will CP load and unload Milk?

### ISSUE THREAD

**Issue by nyfarmboy07** [Courseplay/courseplay#2106]
version 5.01.00145
I noticed milk is one of the options under mode 1 for CP now.  I've been trying to make a milk course using mode 1 with no success.  I am using the Kotte Universal pack, which appears to work perfectly, except it stops at the beginning of the course, and will not load the trailer, and does not stop at the sell trigger, yet will stop when "stop at next trigger" is selected, but still will not unload.  I am wondering if this is a mod issue, or an issue with these types of triggers.

**Comment by Blackmankot** [comment]
@nyfarmboy07  To transport all liquids, use only 8 points.
![2017-06-06_11-31-41](https://cloud.githubusercontent.com/assets/26131714/26812718/f9997388-4aab-11e7-9009-b32fb9438f31.jpg)

**Comment by pops64** [comment]
Has @Blackmankot said mode1 is only for soilds. Mode 8 is for liquids. It may or may not support milk unloading

**Comment by nyfarmboy07** [comment]
![fsscreen_2017_06_06_06_45_31](https://cloud.githubusercontent.com/assets/24856526/26825798/685097ac-4a84-11e7-9e4d-54e0cd43ac79.png)

As you can see, under mode 8 it says "wrong trailer connected".  This trailer only can hold milk.  Under mode 1 however, it will list milk as the product.

**Comment by pops64** [comment]
You just changed your issue. You said you were trying with the kotte please continue using that for this issue. The not working in mode 8 is a separate issue. Try again with the kotte and report back

**Comment by Blackmankot** [comment]
@pops64  Checked, the pack Kotte does not work at all.

**Comment by pops64** [comment]
Ok. Because I know only the universal tanks in the kotte pack work in mode8. I think the fuel tank works as well but that is because that tanks is declared identically to a giants fuel tank. If it was specific milk trailer it would have to be handled differently. Do you have a clean link with the milk mod

**Comment by nyfarmboy07** [comment]
I am using the North West Texas map on mod hub, as well as the Kotte tanker from there as well.

http://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=75238&title=fs2017

http://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=66241&title=fs2017

**Comment by Blackmankot** [comment]
@pops64  I did not understand this phrase - Do you have a clean link with the milk mod
Write more please

**Comment by einnet** [comment]
@Blackmankot a place from where he can download mod that you use.

**Comment by Blackmankot** [comment]
Mod Kotte or map?

**Comment by pops64** [comment]
The milk mod. I have the kotte but haven't ran across any maps or mods that allow for milk unloading and loading

**Comment by Blackmankot** [comment]
Here is the map.
http://farming-mods.ru/fs17/russkie-karty/19445-mod-karta-dary-kavkaza-dlya-farming-simulator-2017.html

**Comment by Blackmankot** [comment]
@pops64  I have great respect for your work on improving the Course. But I think, after the introduction of changes to the transportation of all liquids on item 8, there were many problems with different types of load triggers. When there was a transportation on the first item with indication of the type of product - everything worked perfectly. Can return back !?
Thank you for your work !.

**Comment by pops64** [comment]
Collapsing mod issues into one thread. #2231

**Comment by pops64** [comment]
Alright I am reopening this so I can discover some more information. For those of you with Milk triggers which Milk Trigger are you all specifically using? FrabickScript? If so does the FrabickScript Seed n Fertilizer triggers not work as well? Well I am currently working getting the Seed and Fertilizer portion working if I can figure what Fill Type number milk is I am may be able to include that.

**Comment by pops64** [comment]
Closed #2909
