### ISSUE TITLE
Tractors stop waiting in traffic

### ISSUE THREAD

**Issue by Symbob** [Courseplay/courseplay#2107]
Here's another little problem I've found for you guys to look at.  I'm on Goldcrest Valley map and I've set up a course to carry silage from the BGA bunkers to sell it at the Barn (bale sell point) on the farm.  I have 2 tractors running in "Grain Transport (load at start)" mode, they are being filled with silage by a wheel loader at the BGA.  When a tractor finishes the course and comes up behind the tractor that is being loaded it stops as normal with the message saying that it is in traffic.
![fsscreen_2017_06_06_19_48_48](https://user-images.githubusercontent.com/18528850/26847845-611dbad8-4af6-11e7-8558-4ae5b46156ea.jpg)

The wheel loader then comes in and dumps silage in the trailer.  
![fsscreen_2017_06_06_19_48_56](https://user-images.githubusercontent.com/18528850/26848037-09b0f566-4af7-11e7-9818-31bfbae1422f.jpg)

The wheel loader then moves away and the "in traffic" warning disappears and the tractor starts to move forward.
![fsscreen_2017_06_06_19_49_01](https://user-images.githubusercontent.com/18528850/26848094-358b565e-4af7-11e7-8402-734175a8c4b9.jpg)

It then collides with the tractor and trailer being filled and pushes it out of the way.
![fsscreen_2017_06_06_19_49_07](https://user-images.githubusercontent.com/18528850/26848170-6f1cf616-4af7-11e7-944f-a40b42968ee2.jpg)

It's seems to me that if a second traffic item is detected by the tractor, it forgets about the first traffic item.   When the second vehicle moves away the tractor tries to continue it's course forgetting that the original traffic item is still in it's path.

I hope this makes sense as it's a difficult problem to try and describe.  I've seen similar problems occur but this is the first time I've been able to recreate the problem in a way that I could describe.  Let me know if you need any further info or debug info.  v5.01.00145

**Comment by Bigtonytomato** [comment]
You should add a wait point on the course i think to have the other tractor wait til the area is clear.. Put it back a bit, say at the start of that silo maybe. anywhere really

**Comment by pops64** [comment]
Don't use a wait point has this will interfere with other functions. This might have something to do with changes made for engine shut off to the traffic system

**Comment by ThomasGaertner** [comment]
can you give me your savegame and the Courseplay_Courses folder ? thanks

**Comment by Symbob** [comment]
[CoursePlay_Courses.zip](https://github.com/Courseplay/courseplay/files/1117302/CoursePlay_Courses.zip)
[savegame2.zip](https://github.com/Courseplay/courseplay/files/1117303/savegame2.zip)
This isn't the exact savegame as pictured above because I've now emptied the bunkers in that original game.  So I've replicated the problem using another almost identical savegame using only default equipment.  The map is Goldcrest Valley.  The trailer course is called "BGA to Barn" and can be found in the sub folders Haulage/Transport.  You can easily replicate the problem on any course though, by simply making a vehicle become stuck in traffic and then driving another vehicle up to the front of the vehicle then moving away again.  When you move away the vehicle that was in traffic will start driving again even though the original obstruction is still in its path.  In this particular savegame you will see that the second tractor and trailer is detecting the first tractor and trailer and stops "in traffic".  If you then drive the loader to the trailer to be filled then drive away again the second trailer will then startup and start driving in to the first trailer that is still in it's way, waiting to be filled.  I hope that all makes sense.  Let me know if you need any further help or info.

**Comment by ThomasGaertner** [comment]
thanks for the save game, I could catch the bug :-D 
please try again with v.157 or higher and report

**Comment by Symbob** [comment]
That seems to have fixed the original problem but I'm wondering if this has now caused another problem.  While testing the new fieldwork course generation, as mention in another issue https://github.com/Courseplay/courseplay/issues/2098#issuecomment-312481501 , I've noticed that if some vehicles are stopped "in traffic" they don't resume driving after the obstruction has gone.  They just sit there with the "in traffic" notification up and you have to Stop Driver then Start Driver again in order for the vehicle to resume the course.  It doesn't do it with all vehicles though.  It certainly happens with Giants BigX1100 Forager and the in game New Holland FR850 forager.  Also some tractors are affected too.  Giants Valtra T Series Cow Edition has this problem but the MF8700 appears to work as it should do.  Looks like we may have solved one problem but caused another perhaps.

**Comment by brnl** [comment]
I seccond this regression. It seems to have been introduced in 157. It took me a while to reproduce, so the 157 log is a bit long. It happened again after I reloaded the course for the tree tractors (1 truck and 2 tractors, actually). So what happens is the 'is in traffic' detection stays triggered even though the blocking vehicle drove away. This happens especially at the end of the courses, I have noticed.

[log-156.txt](https://github.com/Courseplay/courseplay/files/1117890/log-156.txt)
[log-157.txt](https://github.com/Courseplay/courseplay/files/1117891/log-157.txt)

Courses + safe: It's about the trip from the Fermenter 5000 (mod) to the barn. The course is called "Temp Silage".
[CoursePlay_Courses.zip](https://github.com/Courseplay/courseplay/files/1117892/CoursePlay_Courses.zip)
[savegame3.zip](https://github.com/Courseplay/courseplay/files/1117893/savegame3.zip)
[FermentingSilo_FS17_placeable.zip](https://github.com/Courseplay/courseplay/files/1117895/FermentingSilo_FS17_placeable.zip)

**Comment by pops64** [comment]
Could we get a log during this FPS drop thanks.

**Comment by brnl** [comment]
Do you need a special debug level for that? It's in the same 156 and 157 logs as the previous post.

**Comment by pops64** [comment]
Ok. If the the logs you posted were during the FPS drop that is fine. Usually an FPS drops indicates a nil error.

**Comment by ThomasGaertner** [comment]
try again with v.158 or higher ...  stupid bug ... :-(

**Comment by Symbob** [comment]
Excellent!! v.158 has fixed it for me.  I didn't notice the FPS drop that @brnl reported so can't comment on whether it has fixed his problem.

**Comment by brnl** [comment]
Yes, it's fixed! Thanks for the quick response again, guys!
The FPS drop was due to having debug channel 3 enabled. When I disable it, the FPS is fine.

Thanks!
