### ISSUE TITLE
problem when i get off the tractor

### ISSUE THREAD

**Issue by luca996** [Courseplay/courseplay#2108]
if get off the tractor when courseplay is on when i get on again the driver get a lot of arms and if i active the internal view i only see the head of the driver

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by rayrizal** [comment]
I believe this is what @luca996 mean, the driver figure still remain even the CP is off. It happen to me also but only in harvester not in tractor.

![20170513211625_1](https://user-images.githubusercontent.com/28395955/26888085-1f7832dc-4bd4-11e7-9b25-f9bd0c069120.jpg)
![20170514134910_1](https://user-images.githubusercontent.com/28395955/26888084-1f726e4c-4bd4-11e7-8eaf-9ac9598cba23.jpg)

**Comment by pops64** [comment]
Could we get a log for this? It may be something simple that will show up in the log. No channels

**Comment by pops64** [comment]
Closed due to inactivity. Unable to reproduce. If you get a log please post here and I will reopen this.
