### ISSUE TITLE
not an issue looking for help only

### ISSUE THREAD

**Issue by willie2016** [Courseplay/courseplay#2110]
Hi , is it possible to downlaod/install an older version of the beta release for fs 17 ? i remember there was one back near the beginning of 2017 which worked for tractors and trailers on courseplay while doing grass silage

**Comment by dkfiremann** [comment]
You can do that by finding the commit from the commit list that fits your needs, then click on the <> button. Now you see the trunk from when that commit happend. Now click on the green download/clone button and you should be able to get the code from the point of time your wanted. 

Now the real question is why do you want that? 
You have an open question,  #2087 , that you are missing to reply on, and you are describing a problem that only you have right now. Wouldn't it be better to fix your problem?

**Comment by pops64** [comment]
We would need more information about your other issues to begin fixing it. Follow https://github.com/Courseplay/courseplay/wiki for posting a proper log. And with the debug channel mentioned we need pictures or video associated with that. Closed to clean up issues area
