### ISSUE TITLE
Looking for advice or help

### ISSUE THREAD

**Issue by Pacrat** [Courseplay/courseplay#2111]
First time posting a question here and still pretty new to courseplay as I've only been using it for a month.  My question is on beet and potato harvesters (game versions and not mods.)  Is there a way to set the parking location of the unloading vehicle further away from the harvester after initial unload?  I set my course to enter and exit the field in areas that the harvester has already run, so that part isn't the problem.  It is when it goes to unload the harvester, backs off, then parks in the just cleared lane to wait for the next unload.  When the harvester comes back on the next row, the conveyor catches on the trailer (or unfolds into it for the beets) and end up having to separate them. 

Only solution I've been able to run at the moment is to use smaller trailers that do not fully unload the harvester so it goes on it's unloading run or set larger trailers unload percentage low enough that it sends the trailer off.  Is there a way to set it so it either goes fully back to the first point to wait or park 2 harvest lanes over?

**Comment by TheRealRolandDeschain** [comment]
A possible solution (as far as I understood your problem) would be to start and end the course outside of the field. 
This way you would have to select the harvester manually, but tractor and trailer wouldn't wait on the field.

**Comment by Pacrat** [comment]
That's what it does.  The field is number 7 (I believe) on Rattlesnake that is a long north/south aligned field.  The entry is on the northeast corner at the edge and the exit is at the southwest corner to the transport run.  Due to the length of the field, you usually have to empty every run and a half (for unfertilized as I had bought it when it was already ripe.)  If I use the standard 50 or 59k trailers, the tractor/trailer will unload the harvester fully (with a proper offset and turn) but still have room left in the trailer.  So the tractor/trailer stops, waits for the harvester to pass (plus a little further,) then pulls into the lane behind the harvester and parks there until the harvester is ready to be unloaded again.  Due to the position and the small footprint of the harvester head, the next time the harvester passes- the trailer is in the way (for the potato) or will unfold into it (beet.)  So either I have to manually reset the trailer run to return to the first point (your solution,) use smaller trailers that do not take the full load so it auto-starts on it's unloading run, or set the percentage on larger trailers low enough that one unload starts the run.  

Setting lane offsets works for setting up for the trailer to be unloaded but it seems to want to park directly where the harvester drove if it doesn't receive a load large enough to trip the unload portion of the run.  As to setting the harvester manually, on Rattlesnake (due to the size of the fields,) many courses have to be set manually as it seems that they are too far for automatic detection unless your route is designed just right.

Sorry if I'm not too clear.

**Comment by TheRealRolandDeschain** [comment]
OK, you could just set your tractor to drive earlier to do the unloading. (Drive on at XX%)
This means more driving, but why would you care ;)

**Comment by Pacrat** [comment]
Congestion at the loading zone, extremely tight roads on the map, tight and hairpin turns to get into and out of, as non-destructible fences and signs make tight turns worse,  fields and loading zones, as well as multiple other reasons.  You can pick one or all of the above for the reasons to determine why I cared enough to ask.   :)   I have been using overload with small trailers to bypass it at the moment, but figured I'd ask to see if there was another method to get the tractor trailer to park one more row over that I had missed in my newness to courseplay.  Using a larger trailer would cut down on the congestion to keep rush hour from turning into a traffic jam.

Lol, it would help if I chose a normal or easier map but I like the challenge of this one.  Even setting up courseplay to automate certain portions (I really hate self-driving beet and potato harvesters on large fields) requires a lot of forethought and planning.  If the road signs were destructible or field access easier, I'd probably get bored of it pretty quick.

**Comment by pops64** [comment]
This is a known issue see #1669. Post there if you have if issues with the potato one as well. It is the same cause has the beet harvester. Closed
