### ISSUE TITLE
Question: Mode8 - Liquid Transport

### ISSUE THREAD

**Issue by TheRealRolandDeschain** [Courseplay/courseplay#2112]
I have a question concerning the number of runs. 
I have the following course to bring water to the sheeps at sosnovka:
Start at main farm  --> Watertower (fill) --> sheep (unload) --> End at main farm. 

If I set the number of runs, transport is made the correct number of times, however at the last run the transport isn't stopped at the farm, but at the watertower. 
Is that the correct/intended way for this mode to work? Wouldn't it be a more practical way to and the last run at the endpoint of the course?

greetz!

**Comment by pops64** [comment]
Yes. This is how it was designed. Originally I had it set to stop at the last way point but this caused issues for another user. If you want to stop at last waypoint. Hitting the stop at next trigger or last way point should work on the last run. It won't stop at the unload with this active but it make stop at the load tho.

**Comment by TheRealRolandDeschain** [comment]
OK, thx for the fast reply!

**Comment by pops64** [comment]
Can we close here? Thanks

**Comment by TheRealRolandDeschain** [comment]
Yes, thx!

**Comment by pops64** [comment]
Thanks. Isssues are starting to pile up. Closed to keep issues area clean
