### ISSUE TITLE
Interface bug using silo mode

### ISSUE THREAD

**Issue by fudoido** [Courseplay/courseplay#2113]
hello team.
been using the new mode to compact and level the silos, amazing job adding it.
however, after some time playing, at random times, if i stop the course, it does stop, however the interface simply goes fully transparent but acts like if it was still active (right-click will lock camera or show cursor, as normal) and by having this behaviour i cant click anywhere to restart course, modify, remove, anything at all.
courseplay interface still works fine on other machines and modes when this occurs, this is only happening while doing the silo leveling mode on the specific vehicle doing the course. have to save the game, exit map and open save again to get the interface and its functionality back.
are you aware of any mods that can conflict with the courseplay gui?

**Comment by pops64** [comment]
Alot of mods can interfere with CP especially when they use the right mouse button has the key binding. https://github.com/Courseplay/courseplay/wiki full log pleaase

**Comment by pops64** [comment]
Closed due to inactivity so we can keep issues area clean
