### ISSUE TITLE
Scaling course speed per vehicle

### ISSUE THREAD

**Issue by Timmiej93** [Courseplay/courseplay#2116]
First of all, this is not a bug report, it's more of a suggestion. If this is the wrong place for a suggestion, I'm sorry about that, I couldn't find another location.

I love using the "automatic street speed, from recording" function, but I do have a small gripe with it: When the course is recorded with a slow vehicle, all vehicles driving that course, will not go any faster. Makes sense obviously, but wouldn't it be possible to add a scaling factor, that can be set per vehicle? So for example, a course is recorded at 25 km/h, you set the scaling factor to 2 for a vehicle, and that specific vehicle will drive the course at 50 km/h instead of 25.

Another thing that I thought of that might be handy, to avoid uncontrollable corner taking: Maybe only apply the scaling factor to any speed above 20 km/h (for example). That way you'd get the original speed in corners, which might be a bit smoother, but still can make them drive faster on the straights.
Implementation example: 
```
if (originalSpeed > 20) {
    newSpeed = ((originalSpeed-20)*scalingFactor)+20;
}
```
The 20 could obviously be replaced by another value, or even a variable, available for the player.

**Comment by ollydoyle** [comment]
I have noticed something similar, if i record a coarse with a empty trailer, and the run it, sometimes with the momentum of the full load is can over shoot the corners.

**Comment by Timmiej93** [comment]
I don't think that has any overlap with what I mentioned. My post is specifically about speeding up vehicles on a course that have been recorded with a slower vehicle. Your issue is simply a case of proper course recording. Either record the course with a full trailer, or with some common sense. If the course is already recorded, simply limit the maximum speed. It's all possible.
