### ISSUE TITLE
Vertical offset has no effect

### ISSUE THREAD

**Issue by Mantikor83** [Courseplay/courseplay#2117]
While ploughing the vertical offset has no effect, tractor drives till calculated end of the course-lane and then turns. Even when a vertical offset of 20+ meters is set (front/back tested).  Horizontal offset works well, tractor adjusts course to right/left side, as expected. Used Vanilla tractor and plough for testing. Other implements were not tested yet.

Installed Version is the actual developer Version from today.

Expected result of vertical offset: Tractor stops on the course lane x meters before/after the implement reaches the calculated end of the actual course lane and starts turning, like he would do if he reaches the end with vertical offset zero.

**Comment by pops64** [comment]
Sorry for the delayed response. The vertical offset is currently only used for mode 2 and 3 when unloading a harvester. I don't think it was ever implemented in FS17 and I am not sure if it was ever used for your behavior in FS15. The plough past field option on combi settings page should fix this issue for you.

**Comment by pops64** [comment]
So have tried this functionality? It should achieve what you are trying to do thanks.

**Comment by pops64** [comment]
I am going to close this out due to inactivity.
