### ISSUE TITLE
Vehicle in traffic jam on edge of field with harvester

### ISSUE THREAD

**Issue by pajajezek** [Courseplay/courseplay#2118]
This issue is only with mod [TATRA Phoenix 460 Agritruck v 1.0](https://www.modland.net/farming-simulator-2017-mods/trucks/tatra-phoenix-460-agritruck-v-1.0.html) and other truck without attached trailer. Once the harvester is empty, Phoenix is going to traffic jam and harvester waiting for its move.

![traffic jam](https://user-images.githubusercontent.com/18664071/27042445-3fefe7a0-4f97-11e7-8fbf-307748a2ea29.png)

**Comment by pops64** [comment]
Collapsing mod issues into one thread. #2231
