### ISSUE TITLE
issue with grass pickup and delivery

### ISSUE THREAD

**Issue by joshthegrate** [Courseplay/courseplay#2119]
what am i trying to achieve:

I am trying to collect the already rowed up grass and then deliver to ether a silo for storage or deliver to a silage bunker.

how am i setting up the courses: 

I am setting up the 2 courses separately the gathering of the grass and the delivery to ether the silage bunker or silo. then i clear both courses and select the gathering course first then i append at the end the second course. i then select field work and press drive course.

what is going wrong:

once the foraging wagon is full the course stops with a tool is full message.

attached is a video of what im doing: https://www.youtube.com/watch?v=1tLDzTVrbOk&feature=youtu.be

**Comment by Symbob** [comment]
Your video doesn't show you recording the fieldwork section (for gathering the grass).  Did you set a "P" waiting point at the start and end of the course?  I think CP needs this to define the working area.
https://courseplay.github.io/courseplay/en/manual/index.html#driveMode6

**Comment by joshthegrate** [comment]
I was unaware of needing to use the "p" as I was going by this tutorial https://youtu.be/kV9C1bFQQR8

**Comment by joshthegrate** [comment]
When I get home from work I'll create fresh new courses and update with the results.

**Comment by Symbob** [comment]
In his video he doesn't show how he created the fieldwork course either but judging by the name he's given it it's possible he got CP to generate the course.  Basically, if you get CP to generate the course it will automatically insert a wait point at the start and end of the course, but if you record the course yourself you need to set the wait points manually.

**Comment by dkfiremann** [comment]
The issue is not with your course, but that you are not clicking the right button when you select the second course. 
You need to use the first button, Merge, not the second button, Append. 
Merge your two courses and you should be good to go.

**Comment by Blackmankot** [comment]
@dkfiremann @Symbob You are wrong, he correctly composes the course, his mistake is that the beginning of the work is not from the first point.

**Comment by joshthegrate** [comment]
doing what Symbob said got it working thanks. issue can now be closed.
