### ISSUE TITLE
Game Freezes when stopping CP course.  CP + More Realistic + Gearbox Addon

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#2120]
From the FS-UK MR Beta thread:

**sootysax:** 

My game is freezing when stopping Courseplay from running a course (sometimes starting as well).

It seems to be a conflict between GearboxAddon 2.1.1.9 and MR when stopping a CP course.

When I take either MR or Gearbox Addon out of the mods folder, it works fine.

https://gist.github.com/sootysax/431e4f130fbb471d8d02b677bcdb8622

**Dural:**

same problem as here : 
https://fs-uk.com/forum/index.php?topic=195659.msg1277653#msg1277653

I don't want to "fix" it on my side (at the motorized.lua level) because this is not the real problem. this error should not happen (self.mrUseMrTransmission is set to true and then, self.motor.maxMotorPower is nil => can't exist. It means there is another problem hidden - example : calling this function for an "unmotorized" vehicle ? very strange, indeed)

EDIT : I added a "check" in V0.3.07   => sootysax: can you give it another shot ?
I can see only 2 scenario to get this error =
1. calling the "mrUpdateFuelUsage" for a vehicle that is not motorized
2. calling the "mrUpdateFuelUsage" for a vehicle that is not "mr"

**sootysax:**

Same freezing as before with the latest version....

https://gist.github.com/sootysax/98bca35799e41480db20375eb5ab1183

**Dural:**

problem comes from the gearbox_addon which switch the default "vehicleMotor" by another one. But the "motor.maxMotorPower" is lost in the process.
Please report back to Mogli

EDIT : maybe a little more complex than that.
Example : CP set the "mrUseMrTransmission" to true, then the "updateFuelUsage" is called before Mogli gearbox could notice it.

EDIT2: finally, this is not the gearbox addon (sorry Mogli  for having pointed out your mod first).
The real source of this problem = CP. 
Indeed, whatever the settings before using CP, when you stop the CP worker, CP set the value of "self.mrUseMrTransmission" to true
And so, I can reproduce the problem without GearBox addon too, and even by putting a 'check' in the "updateFuelUsage" function, this would not be sufficient (a lot of others problems then since the "mr engine" think this wehicle does use the "mr transmission" whereas nothing is initialize for that in the first place)

So, fix = CP has to set back the "self.mrUseMrTransmission" to whatever it was once not controlling the vehicle
=> please report back to CP

**Comment by pops64** [comment]
Yea we will look into.

**Comment by pops64** [comment]
Try again with version 146 or higher

**Comment by sootysax** [comment]
since mogli also added a workaround to gearbox, im not sure how this fix effected the problem
