### ISSUE TITLE
Krone Ultima compatibility?

### ISSUE THREAD

**Issue by RKI91** [Courseplay/courseplay#2121]
Hey, i have one small question. Could you add compatibility for Krone Ultima and Courseplay?
At the moment it does not work well, basically it does not work at all, In field work mode always says "wrong type of machine" when other ballers works fine. I think that compatibility with this modification would have pleased a large part of the community. Regards! :)

Link for the official download of mod: https://www.farming-simulator.com/mod.php?lang=pl&country=pl&mod_id=80039&title=fs2017

**Comment by redrummed** [comment]
This worked for the Fs15 krone, haven't had a chance to do it yet but worth a go. 

Ok I got it to work it's not perfect but it helps !
Step 1 : go and select field work 
2 : import your wind rower course !(that you used to create windrows
2.1 : create course
3 :select transport mode (a-b)
4:turn baler on select size and wrapping and auto drop mode)
5: start the course off a couple of waypoints and select (nearest waypoint)
6: drive course

IMPORTENT: keep eye on baler if wrapping or foil runs out
It will keep going and you loose the windrow!

**Comment by RKI91** [comment]
I'll check it for sure and thank you for this tips! 
Anyway, this is probably a temporary solution. Full compatibility with CP would be so welcome. I mean something like FBP3135 baller from KUHN DLC which works great with CP.

**Comment by pops64** [comment]
But if we have to take into account the level of theses to items. It would require more work than the kuhn dlc. I will download it later and have a look.

**Comment by pops64** [comment]
Collapsing mod issues into one thread. #2231
