### ISSUE TITLE
Improvments: Name the machine

### ISSUE THREAD

**Issue by pajajezek** [Courseplay/courseplay#2122]
Hello, is it possible to add my own name to each machine? I have 10+ harvestors of each type and when I assigning harvestor to vehicle, the list is too large and I must go with vehicle to harvestor and assign it according to distance. If there is own name, it will be easy. 

Will be fine, if the name of vehicle is also displayed over the map.

![fsscreen_2017_06_16_20_10_11](https://user-images.githubusercontent.com/18664071/27239388-fc691b4a-52d0-11e7-9a69-0aa5de8ba466.png)

**Comment by ollydoyle** [comment]
Maybe have the field number included in the text, maybe with the mode it was in, would be a simpler solution without having to add a new dialog screen.

**Comment by pajajezek** [comment]
Not always. If I have 5 potatoes harvesters on some field, is there a same problem... The name i unique.

**Comment by pops64** [comment]
We are going to put this way on the back burner for know and revisit this suggestion in the future. As for now we are currently working on getting CP released. Closed to keep issues area clean
