### ISSUE TITLE
Improvments: Concave shaped fields, and field work paths

### ISSUE THREAD

**Issue by ollydoyle** [Courseplay/courseplay#2124]
![20170617041131_1](https://user-images.githubusercontent.com/6239276/27249892-7c1a3766-5317-11e7-8c81-3b14dcc1173b.jpg)

I was thinking about this as i had a few fields which have this problem, but mostly because i thought it would add more robustness to the course generation. I can't program, so this is just me talking out loud, and if something happens with my ideas, all well and good, and if not, so be it.

So i thought originally it would be easiest to catch these areas that are occluded from each other, by using the massive straight lines used as filler in each row, seen below
![20170617055909_1](https://user-images.githubusercontent.com/6239276/27250266-27684914-5322-11e7-84e7-24bf93215c4c.jpg)
And if these line sections can be identified, maybe they have some code associated with them, but that they could be replaced with the section of perimeter(or better a section of headland) that they intersect, which would cause a tractor to circumnavigate the inaccessible area and continue working the remainder of the row.

I feel this would be the easiest for a programmer to do and would have the affect of preventing the tractor from driving into a river or forest that is in the way

The problem is that this would mean driving around the inaccessible area for each row, and the time driving around it would increase each time around, eventually spending more time driving than working.

So it would be better to work each side fully first then move to the next.

I'm not sure how rows are connected on the back-end of the program in it current state, but if the rows are generated first, and the end of one is joined the the start of the next based on the number sequence for the points at the ends, this could be changed to join to the next closest endpoint instead, which should only leave one long line intersecting the inaccessible area, to be replaced with a perimeter section as explained above. But this would possible cause a problem where the endpoint of rows end near the transition to headlands.

**Comment by pvajko** [comment]
There's an improvement in the works for the course generator, you can try a test version, see #1793,. Also, see https://github.com/pvajko/course-generator/issues/12 for a discussion of the problem.

The field in your example seems to be an 'easy' case as it most likely has a convex solution.

**Comment by ollydoyle** [comment]
I have had a thorough read though both topics you linked to, and its remarkable the amount work work that happened since I was last on the forum.

I do remember the first mention of have n-degree paths in field and its great that it is coming to fruition.
And it was something that I wanted to site in my next post. 

I see in the now closed topic #1793, that the idea of subdividing a field into more manageable areas has been floated already. Trying the emulated the optimization of actually real world GPS guided farm implements may be slight overkill in my view, and I would like to share something I found online while doing some research for an 'easier' solution

[https://mathoverflow.net/questions/60212/partitioning-a-polygon-into-convex-parts](url)

This simply reduces a polygon into smaller polygons based on reflex vertices, that is vertices that have and inside(side facing the interior of the field) angle greater than 180 degrees, as the start of a new convex hull.
Now unchecked this could create convex hull in numbers near the total number of vertices in the perimeter. But the only are on concern are to the sides of the current land direction as areas ahead or behind on the current rows would be filled in by the end-sections of the lanes.

Where multiple reflex vertices are in sequence, they could be collected as one, and analysed, where if the indentation depth into the field was less than the working width*number of headland rings, they could also be ignored as the machinery would pass harmlessly over a previously harvested section of headland

And as for islands of inaccessible area in a field, i think the solution in the first post might be of use in those situations.

**Comment by willie2016** [comment]
sorry for asking this here , how do i get this mod to work? do i simply download and install in mods folder or do i need change something after downloading

**Comment by brnl** [comment]
@willie2016 Have you read the instructions on the homepage? http://courseplay.github.io/courseplay/en/installation/index.html

**Comment by pvajko** [comment]
@ollydoyle Thanks for the link, interesting. The new algorithm can also split the field into convex polygons, and can generate a course for those fields, not pretty, but ok. One of the bigger difficulties is how to connect those polygons, I have a solution for that which uses the headland tracks but I'm not happy with it.

Have no solutions for the islands yet, that's not trivial either, for example, as far as I can tell, Courseplay doesn't even know that there are islands in the field.

BTW, #1793 is not closed.

**Comment by ollydoyle** [comment]
Cool, I'll close this and move the conversation over there then :)
