### ISSUE TITLE
Camera + Controls freezing, simulation still running

### ISSUE THREAD

**Issue by MysticDaedra** [Courseplay/courseplay#2126]
Issue is exactly as described in the title, seems to hit most commonly when switching from Steam Overlay. Took a look in the log.txt, and I found a bunch of Courseplay .lua errors:

[log.txt](https://github.com/Courseplay/courseplay/files/1085033/log.txt)

TL;DR of the log.txt, here is the specific error that repeats several hundred times:

```
Error: Running LUA method 'update'.
C:/Users/Joshua/Documents/My Games/FarmingSimulator2017/mods/ZZZ_CoursePlay/mode2.lua:540: attempt to index field 'acDirectionBeforeTurn' (a nil value)
```

Obviously this is making the game unplayable, the freezes are unpredictable, and lock me out of everything including the escape menu, which means I can't save etc... If this is a mod conflict, I'm not knowledgeable to figure out what the problem mod is.

EDIT: I'm not familiar with lua code, but it appears this method is associated with combines and AutoCombine. I am using the AIVehicleExtension mod from their github; perhaps I should post there as well?

**Comment by Tensuko** [comment]
I got both Mods Running, AIVE (not the one from Mod-Hub) and CP (.145) and both runs well without any issue.
You got the latest CP Version ?
AIVE too ? Remember to NOT Update AIVE in Mod-Hub, when you got the Beta from github.

**Comment by pops64** [comment]
Follow https://github.com/Courseplay/courseplay/wiki before posting any issues. It says to make sure your CP is up to date before posting any issues.

> ### Courseplay: initialized 39/39 files (v5.01.00100)

Closed because that version does not support AIVE. Also make sure your running the latest version of AIVE has older version do not support CP.
