### ISSUE TITLE
Ovlerloader bug while driving away after unloading

### ISSUE THREAD

**Issue by cpoole2005** [Courseplay/courseplay#2127]
On every overloader/Auger wagon in game or mod I have tried after it has unloaded and is driving away it wants to do a hard right turn  right back into what ever it unloaded into (see attached pictures).

![fsscreen_2017_06_19_12_25_35](https://user-images.githubusercontent.com/5596638/27295552-4f01a590-54eb-11e7-8e47-6722ff3bb7cd.png)
![fsscreen_2017_06_19_12_25_55](https://user-images.githubusercontent.com/5596638/27295554-4f0abf86-54eb-11e7-87bb-fb5d65bd10b3.png)
![fsscreen_2017_06_19_12_26_09](https://user-images.githubusercontent.com/5596638/27295553-4f05fa6e-54eb-11e7-963e-0199c233bd99.png)
![fsscreen_2017_06_19_12_26_12](https://user-images.githubusercontent.com/5596638/27295555-4f0e27f2-54eb-11e7-8647-7c2eaa472b0a.png)

**Comment by pops64** [comment]
Try it with only a wait point. Mode 3 does not support unload points.

**Comment by pops64** [comment]
Closing this as I have prevented mode 3 from using unload points.
