### ISSUE TITLE
FS15 - Driver dissapears when leaving tractor

### ISSUE THREAD

**Issue by W0ND3RWEASEL** [Courseplay/courseplay#2128]
Running courseplay on fs15, had this issue a couple of times the only fix I found is to delete the save file and start again. Not ideal. Basically every time I set the driver up to drive the course he will drive in a straight line and will only steer if I press a key on the keyboard. The driver also dissapears when I leave the tractor and the tractor stops. On the minimap my character is highlighted as the courseplay driver as if he has got out of the vehicle.

**Comment by W0ND3RWEASEL** [comment]
It appears to have fixed itself after the 4th reinstall of courseplay, no idea why

**Comment by W0ND3RWEASEL** [comment]
The point where the courseplay breaks is when the trailor starts tipping

**Comment by W0ND3RWEASEL** [comment]
https://pastebin.com/VXApT6mD

**Comment by W0ND3RWEASEL** [comment]
figured out that it breaks the trailor, I'm using manual ignition and the tractor turns off as soon as I exit the vehicle when the trailor is attatched but stays on if I detach it and move forward a little bit.

**Comment by W0ND3RWEASEL** [comment]
removing auto tractor and auto combine fixed issue

**Comment by pops64** [comment]
Unfortunately, FS15 is no longer supported by us any more. The latest beta version was stable with a few minor isssues
