### ISSUE TITLE
Courseplay Not Loading When Loading Game

### ISSUE THREAD

**Issue by Kassys** [Courseplay/courseplay#2132]
Downloaded new update of courseplay and doesn't work.
Have reloaded older version and works fine.
Just like to let everyone know.

file looks to be too small.

PS: the courseplay internet page doesn't have a like for the released version and new comers are forced to download the developers version and its not working at present.

**Comment by BenB78** [comment]
I'm using 147 and it's working for me.

I do seem to have one file that's not listed on the code page: "tippers.lua". Was that supposed to be removed? I've just been overwriting files in the ZIP, so it might have been removed a while ago. It says last updated on that file was 1 Dec 2016. All others are last updated 22 Jun 2017.

**Comment by dkfiremann** [comment]
Have you zipped the files correctly? 
Without knowing what you have done to get the newest version, and how the zip file looks on your PC it is hard to tell why it is not loading. 

And for your information, there are no released version of CoursePlay to FS17 yet. That is why, if you want to try CoursePlay, you need to use the developer version. 
But then you also have the option to help making CoursePlay better.

**Comment by Kassys** [comment]
![2017-06-25 2](https://user-images.githubusercontent.com/25412451/27515781-f49bf980-59ee-11e7-8303-5007471923f7.png)

**Comment by Kassys** [comment]
still not working.

**Comment by chuck-171** [comment]
Try this!! 
https://youtu.be/o3-M66b5vN0
I hope help you.

**Comment by pops64** [comment]
Follow https://github.com/Courseplay/courseplay/wiki if you are having any issues

**Comment by Kassys** [comment]
Hi Guys, still didn't work so I redownloaded that patch and all seams to be working now. Patch was up to date but must of had file corruption.
