### ISSUE TITLE
Shovel is not loading.  

### ISSUE THREAD

**Issue by chuck-171** [Courseplay/courseplay#2133]
I'm uploading a short video on youtube. Please help me

https://www.youtube.com/watch?v=SqnDbPPJ5l8

**Comment by dkfiremann** [comment]
First: what are you loading? 
It could be that CoursePlay is not design/made to fill this kind. 

The second, you need to have your 2 P's on each end of the bunker/filling area.

**Comment by chuck-171** [comment]
@dkfiremann 
1º I'm loading soil from the map Mining & construction
2º I have 2 waiting point. The first start filling, and second end filling. But my problem is, dont loading.
Maybe  this courseplay is not design for soil. i dont no.

**Comment by chuck-171** [comment]
@pops64 
Do I have to do anything? Maybe I can talk to the map editor for some support.

**Comment by pops64** [comment]
There is nothing to do. This would involve reworking CP code in order to enable this kind of functionality. And we just don't have the time to do this for just one mod. Closed to keep issues area clean
