### ISSUE TITLE
After saved course and reload savegame, my savegame isn`t loading

### ISSUE THREAD

**Issue by Spydermike** [Courseplay/courseplay#2134]
Hello,

if i save a course and save and exit the game and reload the savegame, my game crashed.
This happens of all savegame , even i create a new game to try this. As soon as save the course and reload the game....crash! With mods or without mods, Always the same.
What can i do? :(

**Comment by pops64** [comment]
Follow this https://github.com/Courseplay/courseplay/wiki

**Comment by pops64** [comment]
Closed due to no response for more information.
