### ISSUE TITLE
[Question] Container loading and drop off possible with CP?

### ISSUE THREAD

**Issue by scaniafreak** [Courseplay/courseplay#2139]
Hi,

I use the HKL trucks a lot for transporting goods. I wonder, is it possible to make a CP course where the HKL truck drops off the container at a certain point, and picks up the container at a certain point? Is that functionality already available in CP?

Thanks in advance.

**Comment by pops64** [comment]
It is not possible at the moment. And I don't think we would ever include this functionality has it would require a lot of work and reworking of CP.
