### ISSUE TITLE
Drive Control Diff Lock?

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#2140]
Is there a reason that you havent added the ability to keep the Drive Control Front and Back Differential Locks activated all the time??

I know that CP will pop them on for a second once in a while if the tractor is at a standstill slipping, but i often check on a vehicle plowing uphill with CP and the tractor is not quite stopped, but plowing at 1 mph, because one of the wheels is spinning..   not slipping enough for CP to activate the diff lock.

As soon as I stop the CP course, and lock the front and back diff, I can plow full speed, no slipping.,.  but with CP, its really slow going because it wont allow me to keep them locked.

I really dig the new course generation, would be awesome to be able to use it for fieldwork all the time.

**Comment by pops64** [comment]
Try driving the tractor into a wall and see if it engages the diff locks. There is something out there that is conflicting with CP engaging diff lock.

**Comment by alpha117** [comment]
Hi, newbie here to FS17.  This is a 'killer' to be honest, especially when using seasons and it starts to rain

Thanks for a great MOD

**Comment by pops64** [comment]
Try with version 161 or higher. Sorry, I forgot to add the version number in the push. And report back. Thanks

**Comment by alpha117** [comment]
Hi
Fantastic, works perfect when selecting diff locks.
Many thanks

Also CP seems to have an issue with Dusty Cove (field #40), when ploughing. CP keeps going into the hedges and gets stuck.  Even when setting 4 headlands

Once again many thanks

Loving it.

**Comment by alpha117** [comment]
the issue seems to be the turning around at the end of a 'run'.  CP seems not to use the headlands to turn around in, but turn 90 then reverses over the field edge and into the hedges, hence gets stuck.

Also, could there be a way of selecting how much the worker gets paid, seems a lot. 
Perhaps have a selection on the GUI, the more you pay the worker the better the job, lower paid ones might miss parts of the field or not line up correctly with a harvester.  Just a thought.

Thanks

**Comment by alpha117** [comment]
On the main GUI, the is a 'square' with a 'P' in it and a number 2 beside it. Also a 'triangle' with an 'x' in it and a number 2 beside it.
What do these mean?

thanks

**Comment by sootysax** [comment]
seems to be working great!  awesome

**Comment by pops64** [comment]
Good to hear this works for you. Thanks for closing this out

@alpha117 Make sure turn on field option is enabled. Make sure plow past field edge is disabled. If this doesn't work for you add more headlands. The P and the X are the numbers of wait points and the number of crossing points respectively.

**Comment by alpha117** [comment]
Thanks

 

Got it sorted now

 

Ploughed field #40 at Dusty Cove no issues at all.  CP did all the work 

 

Many thanks

**Comment by sootysax** [comment]
I'm reopening this to request that it also use the locked front and back diff's on mode 2 and 3 combi unloading and overloader..    i'm playing on CPFv3 with More Realistic and field 7 is extremely steep heading into the farm.   my strongest default tractor is struggling to come back with 50% load and having more traction would help

**Comment by pops64** [comment]
Try again with 164. It will now wait until it reaches the 3rd waypoint before turning off diff lock. As I assume this is the point on where it is off the field or on a road by know.
