### ISSUE TITLE
Suggestion for Seasons

### ISSUE THREAD

**Issue by Friendlyx** [Courseplay/courseplay#2143]
With Seasons mod enabled the wages of courseplay drivers will make you bankrupt. So wouldn't it be great to make the salary adjustable when it is asked for at first start?

**Comment by pops64** [comment]
You can go into the save game file you are using for season and open course play settings. And there is a line that sets the wages per hour. You should be able to adjust that to a more reasonable level.

**Comment by pops64** [comment]
This is something we aren't going to fix. We are super busy with other stuff. And you can alway go in and edit the wages being paid either through the way I mentioned above or in your careergame.xml file you can edit the rates at which seasons changes the default value too.
