### ISSUE TITLE
Harvester Tender out of position

### ISSUE THREAD

**Issue by ollydoyle** [Courseplay/courseplay#2151]
I was using symmetrical lane change and a lane offset of 4.5, because the swats were created using a merger [here](https://github.com/pvajko/courseplay/issues/6)

I noticed that when harvester was not able to continue because the turn maneuvers were not that into account either the offset or the symmetrical change.

![20170701130037_1](https://user-images.githubusercontent.com/6239276/27761935-182aedd8-5e5f-11e7-9bb7-72d4c11ff1aa.jpg)
![20170701130053_1](https://user-images.githubusercontent.com/6239276/27761938-2001acc2-5e5f-11e7-96ce-94a24766aebe.jpg)
![20170701130107_1](https://user-images.githubusercontent.com/6239276/27761940-233c1a80-5e5f-11e7-87e9-549c5a251b7a.jpg)

After it gets to this position the tractor try to adjust but never really find a correct spot, often driving into the side of the harvest and becoming [in traffic]

the pictures above show what happens when the space is wider than the lane width, but its worse when its narrower than the lane

![20170701125912_1](https://user-images.githubusercontent.com/6239276/27761982-db5cd2e4-5e5f-11e7-885e-b00cfafb858a.jpg)
![20170701125917_1](https://user-images.githubusercontent.com/6239276/27761985-e3381a14-5e5f-11e7-870d-114eea1f91e5.jpg)
![20170701125926_1](https://user-images.githubusercontent.com/6239276/27761986-ea052de6-5e5f-11e7-92cb-1d38355dfb91.jpg)
![20170701125950_1](https://user-images.githubusercontent.com/6239276/27761987-ecc3cac4-5e5f-11e7-85a4-5fe2f9777e68.jpg)

**Comment by pops64** [comment]
You shouldn't be using lane offset anyways unless you have two harvesters on the field. Find the work width of your swaths and use that value. See #2039 for problems regrading swaths.
