### ISSUE TITLE
Fs17 Game freezing when truck reaches tip trigger

### ISSUE THREAD

**Issue by CaptainCockerels** [Courseplay/courseplay#2152]
Hi when I use the empty combine and offload mode I am experiencing a game lock up and freeze. I have a forage truck (http://fsasmc.com/index.php?/files/file/704-t880-hs-forage-truck/) on the empty and offload mode. When the truck reaches the tip point it freezes the game and I need to end the process. I am including the log and three photos. Thanks. 
[log.txt](https://github.com/Courseplay/courseplay/files/1117347/log.txt)
![1](https://user-images.githubusercontent.com/29821897/27764621-85d0b712-5e6b-11e7-90ce-d6fa30bdcd9a.png)
![2](https://user-images.githubusercontent.com/29821897/27764622-8997d38a-5e6b-11e7-9907-176f3f4c7db9.png)
![3](https://user-images.githubusercontent.com/29821897/27764623-8bea70a2-5e6b-11e7-857b-c413df7f44a1.png)

**Comment by pops64** [comment]
See #2050. You shouldn't have to use a unload point inside of a tip trigger. Closed to keep issues are clean
