### ISSUE TITLE
selecting side for tipper to follow forager

### ISSUE THREAD

**Issue by willie2016** [Courseplay/courseplay#2154]
using the current version of CP , i have tippers selected to always go on left side of forager while in field harvesting silage but sometimes the tractor and tipper comes to the right and the forager starts to move then the tractor and tipper cuts right into side of forager as its trying to get to the left of forager

**Comment by pops64** [comment]
Could we get a video of the tipper approaching the harvester? Or a log with debug channel 3 active on approach on the harvester. I think I know what is going on but I need one of theses things to confirm.

**Comment by ThomasGaertner** [comment]
if U use the new course generation for the forage harvester, then its a known bug and will be solved soon.
otherwise debug channel 4 would be fine ....

**Comment by willie2016** [comment]
you want log with debug channell 4 is it ?

**Comment by pops64** [comment]
Yea debug channel 4 is fine

**Comment by willie2016** [comment]
![farmingsimulator2017game 2017-07-04 00-01-00-109](https://user-images.githubusercontent.com/24280974/27810008-2ffafdaa-604d-11e7-8d72-b2011b506df7.jpg)
![farmingsimulator2017game 2017-07-04 00-01-02-103](https://user-images.githubusercontent.com/24280974/27810006-2ffa3258-604d-11e7-89f4-c6d29df7bd03.jpg)
![farmingsimulator2017game 2017-07-04 00-01-39-717](https://user-images.githubusercontent.com/24280974/27810009-2ffb2fdc-604d-11e7-9647-1cb35378d245.jpg)
![farmingsimulator2017game 2017-07-04 00-02-17-056](https://user-images.githubusercontent.com/24280974/27810010-2ffb94a4-604d-11e7-8376-00c5b8590dcd.jpg)
![farmingsimulator2017game 2017-07-04 00-02-22-015](https://user-images.githubusercontent.com/24280974/27810007-2ffaf81e-604d-11e7-9669-adcdc4402a67.jpg)
![farmingsimulator2017game 2017-07-04 00-03-45-425](https://user-images.githubusercontent.com/24280974/27810011-2ffdc22e-604d-11e7-8f96-026658f54a12.jpg)
![farmingsimulator2017game 2017-07-04 00-03-50-089](https://user-images.githubusercontent.com/24280974/27810012-30122142-604d-11e7-9a70-fae8b0070c6f.jpg)
![farmingsimulator2017game 2017-07-04 00-03-51-715](https://user-images.githubusercontent.com/24280974/27810013-3014f6ec-604d-11e7-834a-2dffb9092a21.jpg)

**Comment by willie2016** [comment]
as can be seen above the tractor and tipper goes to the right and then tries to cut back to the left , iv left selected with harvester , also shows harvester in a collision? theres nothing blocking it

**Comment by willie2016** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/1120703/log.txt)

**Comment by pops64** [comment]
Are you sure that your work width on the harvester is set correctly to your field work course. You just can't copy and paste the course into the harvester. The tipper needs the work width setting from the harvester to turn correctly.

**Comment by willie2016** [comment]
yes the mowers i use are 8.4 work width , so i set the harvester to same course and i put the work width value of the forager up to 8.4

**Comment by willie2016** [comment]
i can link you to mowers and harvester if that would help ??

**Comment by pops64** [comment]
#2031 duplicating merging into one
