### ISSUE TITLE
forager not working in fieldmode

### ISSUE THREAD

**Issue by willie2016** [Courseplay/courseplay#2155]
Hello im using this version , im sure its the latest version of CP. i recorded a course for the mower to mow grass into swaths , i saved the course and once i finished mowing i brought down the ingame new holland forager to the field and set it up the exact way i had the mower set up , i also set the swaths width to 8.2 which is what the mower width was , i click start at first point so forager drives to that waypoint and waits for tractor and trailer to come up alongside it but when it does the forager tries to go off in different direction and then shows its in a collision , but my tractor and trailer is well away from it at this stage 
![farmingsimulator2017game 2017-07-02 16-26-26-278](https://user-images.githubusercontent.com/24280974/27771300-f1b09b4a-5f43-11e7-83ee-2724a91c7bca.jpg)
![farmingsimulator2017game 2017-07-02 16-27-18-832](https://user-images.githubusercontent.com/24280974/27771299-f1aca9cc-5f43-11e7-8961-ae0991cc3ac8.jpg)

**Comment by pops64** [comment]
I would have to guess you started to close to the first way point. Make sure you are in a straight line and back away before starting the harvester on the first way point. If we could get a video of the whole issue or a picture of where you are starting the harvester. That would be great. Thanks

**Comment by willie2016** [comment]
i started  the harvester at the blue mark (waypoint) facing left in picture , i think it was like you explained and too close to it , seems working now , sorry for wasting your time

**Comment by pops64** [comment]
It is all good. Closed to keep issues are clean.
