### ISSUE TITLE
Vehicle in traffic in combined courses. 

### ISSUE THREAD

**Issue by dkfiremann** [Courseplay/courseplay#2156]
Using version 158, when using combined courses to pick up grass, once the vehicle should start on the transport part of the course, the tractor gets into a traffic that it not there. 

Later on the transport route, the tractor gets into traffic again, without any cars near the tractor. 

![20170703152424_1](https://user-images.githubusercontent.com/25283454/27795002-b9e30e8e-6004-11e7-94b4-d53098a9baba.jpg)

Log does not have any errors, but let me know what channel to add to log.

**Comment by pvajko** [comment]
I saw something similar yesterday. It looked to me that there **was** traffic, but then vehicle did not start moving again after the other vehicle left.

**Comment by dkfiremann** [comment]
So it gets stuck in traffic. Could be, I didn't follow the tractor to see if a car has been there.

**Comment by ThomasGaertner** [comment]
debug 3 please but please activate it , before starting the tractors...

**Comment by dkfiremann** [comment]
Yep, got that for you :-) 
(Looked at the code to get the channel number)
[log.txt](https://github.com/Courseplay/courseplay/files/1119866/log.txt)

In this case the tractor catch up with a car, and follows it for a while, then the tractor stop with "in traffic".

**Comment by ThomasGaertner** [comment]
please try the same setup with 159 and debug 3 active and report, thanks

**Comment by dkfiremann** [comment]
That seems to have fixed the bug, the tractor can now go in and out of traffic 

[log.txt](https://github.com/Courseplay/courseplay/files/1120279/log.txt)

**Comment by Anonymous-any** [comment]
@dkfiremann how you show courseplay information up'n left please?
br

**Comment by dkfiremann** [comment]
That is the Glance mod that you can get from the Mod hub.

**Comment by pops64** [comment]
Thanks. Closed to keep issues area clean.

**Comment by Anonymous-any** [comment]
Many thx
