### ISSUE TITLE
mode1

### ISSUE THREAD

**Issue by JanZacher** [Courseplay/courseplay#2157]
Hi have times a question can one make that one in the mode1 animals buy or sell and can bring to the yard or from the yard for sale

**Comment by pops64** [comment]
This has already been suggested. If it happens it won't be until after the release of CP. For now transport mode(5) works just have to do manual loading and unloading

**Comment by JanZacher** [comment]
Yes, but I do not always always load manually and that is why my question whether that goes

**Comment by pops64** [comment]
? The way I do it is I have a waitpoint at the unloading place and the course ends and begins at the load point. Mode 5 automatically stops at a waitpoint. And if I remember to tell it to stop at the last way point. It will stop there. All I have to do is stop CP, load/unload the trailer, and start CP again.

**Comment by JanZacher** [comment]
Yes is correct but my question is whether you can not do with the mode 1 because if you work on others you do not always have to hitch on the vehicle

**Comment by pops64** [comment]
No it is not currently possible in mode 1 and has I originally said it has been suggested to be included but right now we are busy working on getting CP stable for release and haven't had time to look into whether or not it is possible to do.
