### ISSUE TITLE
Tipper turns into wrong lane when forage harvester is symmetric lane changing

### ISSUE THREAD

**Issue by maddavo** [Courseplay/courseplay#2158]
Situation:
Forage harvester (BigX-500) on the field using symmetric lane changing.  The course width is set at double the width of the harvester tool, and the lane offset is set at 1/4 the width of the tool.  This sets up two paths on the field for two harvesters (as per usual symmetric lane changing).  At the end of a non-header lane the harvester turns to line up with the next lane - skipping a lane correctly.  The tipper turns the other direction and does the loop but turns back into the lane that was just harvested to reverse back into a position which is now two lanes adjacent from the harvester rather than the next adjacent lane.

The result is that the tipper is now too far away from the harvester and the tipper/harvester stop.

**Comment by maddavo** [comment]
Additional information:
After further testing, the problem only occurs with the first harvester on the field - where the tipper should drive onto the fruit.  The tipper for the second harvester turns OK as the adjacent lane where the tipper drives has already been harvested.  So the issue seems to be to do with the tipper not wanting to drive on fruit.

**Comment by pops64** [comment]
Make sure both harvester are set to the same work width when originally generated.  If you are copying the course into the same harvester. The tipper turn maneuver relies on the work width setting. I would also avoid non symmetrical lane changes has this has a variable work width.

**Comment by maddavo** [comment]
Copy that.  Working width on first harvester was auto 6.2m (tool).  Course was generated on 2nd harvester (working width 12.5m) and saved - opened course on 1st harvester.
I have tested now a harvester in 'advance' lane with loaded course and working width set to 12.5m - the tipper now turns OK and drives on the fruit next to the harvester.  THANK YOU for pointing this out - I never used to go to the course generation tab unless I am generating a course!
