### ISSUE TITLE
Question about new course generation

### ISSUE THREAD

**Issue by Symbob** [Courseplay/courseplay#2161]
Hi guys.  Not an important issue but just a question and an observation about the new course generation.  The feature works well when you want to work the headland first then start the straight runs, but if you want to do the straight runs first then finish off doing the headland last, like you would if you were seeding, cultivating or ploughing, it generates the course backwards.  So you choose the starting corner as "current vehicle position" then choose the number of headlands you want then choose to work the headland after the straight runs.  When you click the "Generate Course" button instead of the start point being your current position (as you would expect) it generates the course backwards so your current position is the end point not the start.  On a square shaped field it's not difficult to work out where the start point will be or where you need to be in order to get the course to generate with the start point being where you want it, but on irregular shaped fields it can be very difficult to know where to drive to generate the course so it starts in the right place.   Is this how it's designed to work?  Kind of defeats the point of generating the course with the start point being the vehicles current position when it then puts the start point somewhere completely different.

**Comment by pvajko** [comment]
This is how it is designed to work, the text is definitely confusing, you are right. 
The purpose is to use on irregularly shaped fields which are also often surrounded by trees or fences and there's usually a gate where you can enter the field. The idea was that if you work from the inside out, this is where you want to end up and this is what you want to define. 

Not sure why would you want to start at a specific location when working from inside out. It would also be very difficult to implement.

**Comment by Symbob** [comment]
That makes sense when you explain the reason behind it.  With the old way of generating a course you selected your Start Corner, generate your course and start in your selected location.  But with this new way you finish where you would expect to start.  Like you say, it's the wording that's confusing not the necessarily the way it works. 

To answer your question about why you would want to start in a specific location when working inside out, I would answer that in a real life if you were ploughing (as I was doing in game when I discovered this issue) you would plough the field depending on a number of factors. So when I went to generate the course I wanted my current location to be where I started ploughing so that I was playing the game as realistically as possible.  In real life it's extremely unlikely in most circumstance that you would plough a field and finish exactly by the gate.  So there are occasions where you would need to choose where you start and not where you finish.

Now you have explained the logic behind it I can see why it works the way it does.  I'm only now getting used to this new way of generating courses.  Until now I'd been playing on Goldcrest Valley with it's mostly square fields but I've just started another UK style map with irregular fields just so that I can test how well this new system works.  Thanks for the great work.

**Comment by pvajko** [comment]
Thanks @Symbob , do you have any suggestions on how to change the HUD to make it less confusing?

**Comment by JDTiger** [comment]
Starting corner:  Current vehicle position as start/end point
![screenhunter_35 jul 07 01 01](https://user-images.githubusercontent.com/9157835/27936221-00b8f352-62b0-11e7-9bbb-cc9941450d43.jpg)

**Comment by Symbob** [comment]
I think JDTiger has come up with some good suggestions there, although this still doesn't make it clear to someone unfamiliar with CP whether the current position will be the start or the end point.  Would it be possible to have the wording change depending on the selection.  

So using JDTiger's example, if you want to work the headland first then the straight rounds it will read
![hud start](https://user-images.githubusercontent.com/18528850/27952514-710caf54-6300-11e7-9a75-b62c9377334c.jpg)

and then if you click the button to do the straight runs first and headland last this wording would change to
![hud end](https://user-images.githubusercontent.com/18528850/27952548-94bd6b96-6300-11e7-9ad0-8f253c726474.jpg)

Would this be achievable perhaps?

**Comment by ollydoyle** [comment]
I try my hand at programming for the first time in near 15 year so if my solution is possible conflicting with something else I'm sorry.
