### ISSUE TITLE
Combine turning behavior when in harvest convoi of three

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#2162]
Hey Dev-team,
encountered some wierd turning behavior of my combines in harvest mode when driving in a staggered line of three combines.
the combine with the shortest distance between lanes always has this kind of behavior...

It comes to the field edge, turns and then, after beeing set up nearly perfectly, it drives to the middle of the next lane and then to its suppost lane... just look at the video [https://youtu.be/tEwD3kxet44](url)
If more info is needed, i'll happily provide it.

Greets JD_Tiger

PS: will make a better vid once the ingame night is over...
PPS: well that was quicker then expected, thanks to rain... here the better version, you can see the first two combines turning perfectly well and number three derping out...  https://youtu.be/RqUUdvjBKGw

**Comment by pops64** [comment]
Without a log with debug channels 12 and 14 active it is very hard to tell what specifically is going on. But the best guess is that the claus mod needs adjustment for the turn maneuver. Try the claus mod with just 1 harvester running a normal course.

**Comment by JDTiger** [comment]
Yes, it is a mod problem, just verified with the NH 10.90...

here the log generated by the debug channels:
`dataS2/character/pedestrians/man05.i3d (102.19) ms
[dbg12 lp4419] Lexion 700 very big (helper): bool = false vehicle.cp.runCounterBool = false (called from [2] changeSiloFillType() (toolManager.lua:48) -> [1] changeRunCounter() (toolManager.lua:77))
[dbg12 lp4419] Lexion 700 very big (#1): numWaitPoints=2, waitPoints[1]=1, numCrossingPoints=2
[dbg12 lp4419] Lexion 700 very big (#1): numWaypoints=7812, stopWork=7812, finishWork=7812, hasUnloadingRefillingCourse=false,hasTransferCourse=false, waypointIndex=4838
[dbg12 lp4419] Lexion 700 very big (#1): validateCanSwitchMode(): isDriving=true, isRecording=false, recordingIsPaused=false, customField.isCreated=false ==> canSwitchMode=false
[dbg14 lp4420] Lexion 700 very big (#1): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp4625] Lexion 700 very big (#1): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp4633] Lexion 700 very big (#1): curStage=0, refSpeed=6.00, curSpeed=2.36 -> resetCustomTimer(..., "slippingStage1")
[dbg14 lp6450] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-893.08, posZ=-337.92, turnEnd=false, turnReverse=false, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn) courseplay:getLaneInfo(), On Lane Nummber = 20, Number of Lanes = 33
[dbg14 lp6499] Lexion 700 very big (#1):(Turn) turnWithOffset = true
[dbg14 lp6499] Lexion 700 very big (#1):(Turn) wp4861=-90.1°, wp4860=0.0°, directionDifferentce = -90.1°
[dbg14 lp6499] Lexion 700 very big (#1):(Turn) targetDeltaX=-11.00, targetDeltaZ=4.06
[dbg14 lp6499] Lexion 700 very big (#1):(Turn Data) frontMarker="5.2269287109375", halfVehicleWidth="2.5", directionNodeToTurnNodeLength="0.5", wpChangeDistance="3"
[dbg14 lp6499] Lexion 700 very big (#1):(Turn Data) reverseWPChangeDistance="3", direction="-1", haveHeadlands="nil", headlandHeight="0"
[dbg14 lp6499] Lexion 700 very big (#1):(Turn Data) numLanes="33", onLaneNum="20", turnOnField="false", reverseOffset="-9.3013610839844"
[dbg14 lp6499] Lexion 700 very big (#1):(Turn Data) haveWheeledImplement="false", reversingWorkTool="nil", turnRadius="6.0043773684478", turnDiameter="12.008754736896"
[dbg14 lp6499] Lexion 700 very big (#1):(Turn Data) targetNode="240519", targetDeltaX="-10.99658203125", targetDeltaZ="-0.009613037109375", zOffset="4.0744323730469"
[dbg14 lp6499] Lexion 700 very big (#1):(Turn Data) reverseOffset="-9.3013610839844", isHarvester="true"
##################################################
[dbg14 lp6499] Lexion 700 very big (#1):(Turn) Using Forward 3 Point Turn
##################################################
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) startRot=90, endRot=0, degreeStep=-9, degreeToTurn=89, clockWice=-1
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) numberOfWaypoints=11, newDegreeStep=-8
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 1 curentRotation=90
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 2 curentRotation=81
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 3 curentRotation=72
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 4 curentRotation=63
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 5 curentRotation=54
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 6 curentRotation=45
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 7 curentRotation=36
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 8 curentRotation=27
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 9 curentRotation=18
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 10 curentRotation=9
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 11 curentRotation=0
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-899.03, posZ=-339.79, turnEnd=false, turnReverse=false, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-900.03, posZ=-339.78, turnEnd=false, turnReverse=false, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-901.03, posZ=-339.77, turnEnd=false, turnReverse=false, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-902.03, posZ=-339.77, turnEnd=false, turnReverse=false, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-902.03, posZ=-339.77, turnEnd=false, turnReverse=false, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-897.03, posZ=-339.81, turnEnd=false, turnReverse=true, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-895.69, posZ=-339.83, turnEnd=false, turnReverse=true, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-894.36, posZ=-339.84, turnEnd=false, turnReverse=true, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-893.02, posZ=-339.85, turnEnd=false, turnReverse=true, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-893.02, posZ=-339.85, turnEnd=false, turnReverse=true, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) startRot=0, endRot=-90, degreeStep=-9, degreeToTurn=90, clockWice=-1
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) numberOfWaypoints=11, newDegreeStep=-9
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 1 curentRotation=0
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 2 curentRotation=-8
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 3 curentRotation=-17
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 4 curentRotation=-26
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 5 curentRotation=-35
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 6 curentRotation=-44
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 7 curentRotation=-53
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 8 curentRotation=-62
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 9 curentRotation=-71
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 10 curentRotation=-80
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:generateTurnCircle) waypoint 11 curentRotation=-90
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-904.08, posZ=-345.81, turnEnd=true, turnReverse=false, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-904.08, posZ=-347.18, turnEnd=true, turnReverse=false, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-904.08, posZ=-348.56, turnEnd=true, turnReverse=false, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-904.08, posZ=-349.93, turnEnd=true, turnReverse=false, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-904.08, posZ=-351.31, turnEnd=true, turnReverse=false, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-904.08, posZ=-352.68, turnEnd=true, turnReverse=false, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-904.08, posZ=-354.06, turnEnd=true, turnReverse=false, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-904.08, posZ=-355.44, turnEnd=true, turnReverse=false, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-904.08, posZ=-356.81, turnEnd=true, turnReverse=false, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-904.08, posZ=-358.19, turnEnd=true, turnReverse=false, changeWhenPosible=false
[dbg14 lp6499] Lexion 700 very big (#1):(Turn:addTurnTarget) posX=-904.08, posZ=-358.19, turnEnd=true, turnReverse=false, changeWhenPosible=false
--------------------------------------------------
[dbg14 lp6499] Lexion 700 very big (#1):(Turn) Generated 43 Turn Waypoints
##################################################
[dbg14 lp6763] Lexion 700 very big (#1): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp6767] Lexion 700 very big (#1): curStage=0, refSpeed=6.00, curSpeed=2.24 -> resetCustomTimer(..., "slippingStage1")
[dbg14 lp6875] Lexion 700 very big (#1): setCustomTimer(..., "slippingStage1", 3)
[dbg14 lp6885] Lexion 700 very big (#1): curStage=0, refSpeed=10.00, curSpeed=3.50 -> resetCustomTimer(..., "slippingStage1")
[dbg14 lp7092] Lexion 700 very big (#1): getNextFwdPoint()
[dbg14 lp7092] --> return (4862) as waypointIndex
[dbg12 lp7952] Lexion 700 very big (#1): validateCanSwitchMode(): isDriving=false, isRecording=false, recordingIsPaused=false, customField.isCreated=false ==> canSwitchMode=true
[dbg12 lp8030] Lexion 700 very big (#1): validateCanSwitchMode(): isDriving=false, isRecording=false, recordingIsPaused=false, customField.isCreated=false ==> canSwitchMode=true
[dbg12 lp8030] Lexion 700 very big (#1): bool = false vehicle.cp.runCounterBool = false (called from [2] clearCurrentLoadedCourse() (setfenv(1,zzz_Courseplay); courseplay:clearCurrentLoadedCourse(...):1) -> [1] changeRunCounter() (recording.lua:298))
[dbg12 lp8659] Lexion 700 very big (#1): validateCanSwitchMode(): isDriving=false, isRecording=false, recordingIsPaused=false, customField.isCreated=false ==> canSwitchMode=true
[dbg12 lp8659] Lexion 700 very big (#1): bool = false vehicle.cp.runCounterBool = false (called from [2] clearCurrentLoadedCourse() (generateCourse.lua:50) -> [1] changeRunCounter() (recording.lua:298))
[dbg12 lp8659] Lexion 700 very big (#1): validateCanSwitchMode(): isDriving=false, isRecording=false, recordingIsPaused=false, customField.isCreated=false ==> canSwitchMode=true
dataS2/character/pedestrians/man06.i3d (101.46) ms
[dbg12 lp9133] Lexion 700 very big (#1): bool = false vehicle.cp.runCounterBool = false (called from [2] changeSiloFillType() (toolManager.lua:48) -> [1] changeRunCounter() (toolManager.lua:77))
[dbg12 lp9133] Lexion 700 very big (#1): numWaitPoints=2, waitPoints[1]=1, numCrossingPoints=2
[dbg12 lp9133] Lexion 700 very big (#1): numWaypoints=20813, stopWork=20813, finishWork=20813, hasUnloadingRefillingCourse=false,hasTransferCourse=false, waypointIndex=12601
[dbg12 lp9133] Lexion 700 very big (#1): validateCanSwitchMode(): isDriving=true, isRecording=false, recordingIsPaused=false, customField.isCreated=false ==> canSwitchMode=false
[dbg12 lp9221] Lexion 700 very big (#1): validateCanSwitchMode(): isDriving=false, isRecording=false, recordingIsPaused=false, customField.isCreated=false ==> canSwitchMode=true`

**Comment by pops64** [comment]
Do you have a picture associated with this? Thanks

**Comment by JDTiger** [comment]
Well, i knew i forgot something... here is the vid with the debug options:
https://youtu.be/jcvk0qENGOk

**Comment by pops64** [comment]
Collapsing mod issues into a single thread. #2231
