### ISSUE TITLE
Shovel Mode Game Crash When Switching Shovels

### ISSUE THREAD

**Issue by BenB78** [Courseplay/courseplay#2163]
I had the four shovel heights set with a silage shovel on a wheelloader (JCB 435S). I dropped off the silage shovel and went to pick up a leveler. Upon attaching the leveler, I clicked the "play" button to go to transport height. It contorted the leveler into a mass of twisted steel and locked up the game. The only button that worked was getting out of the tractor, and once I did that, nothing worked, not even the menu. I had to end task to exit the game.

I didn't know if shovel positions would work with the leveler - but perhaps an error message could be put in, rather than crashing the game?

https://gist.github.com/BenB78/493b564d2a58f40071dbb6c85886319a#file-log-txt
v 5.01.00160 on Goldcrest Valley
There are mods running, but wheelloader and implements used here were not mods.

**Comment by pops64** [comment]
Closed #2909
