### ISSUE TITLE
What would cause CP to drive past unload triggers?

### ISSUE THREAD

**Issue by MrScsi** [Courseplay/courseplay#2164]
I have noticed lately that when using the built in  man truck and krampe trailer when I use CP to take from the combine to an unloading trigger it SOMETIMES will unload but most often just slow down, say tip trigger reached and then crack the back gate and keep on rolling 

Now I have TRIED setting the triggers FLUSH, Sunken slightly and ABOVE the ground or pit and just can not seem to get it to stop and unload anymore. Now a silo to sell point the first load works but then since it does not unload just keeps looping with a full trailer....

IF there is some trick to setting up triggers I am all ears ;)

**Comment by MrScsi** [comment]
NEVER MIND it may have to do with speed and mass of a loaded trailer....

**Comment by gec100** [comment]
mass adjustment mod will do that.

**Comment by pops64** [comment]
See #2001. Closed to keep issues area clean. If you aren't using that mod then I will reopen this.

**Comment by Sokonomi** [comment]
Ive got the same problem, it drives over and begins to tip but it seems to overshoot.
Doing it with a Case Puma and an ITR with a skip. No mass mod involved.

**Comment by pops64** [comment]
When you record the course don't go driving into the tip trigger at flank speed. It should still slow down to 6 mph when a trigger is detected. Under my test, it was able to stop no matter how fast I was going using giants standard size of triggers. Sounds like you got a separate issue.  Problay mod related.

**Comment by Sokonomi** [comment]
Even at walking pace it seems to scoot past the trigger because the massive trailer just pushes through.
I tried it with the little green vanilla starter tipper you get on that map, it still did it.
It doesn't seem to like the slopes on the triggers in sosnovka?

**Comment by pops64** [comment]
Sounds like you have an issue of some sort. What version are you using https://github.com/Courseplay/courseplay/wiki follow that debug channel 2. Please if you would start a new issue thanks.

**Comment by gec100** [comment]
It is The Filltype mass adjustment mod that's causing this problem.
https://www.modhoster.com/mods/filltypemassadjustment-fur-ls17-realistische-ladegewichte

**Comment by pops64** [comment]
This original issue. yes, but @Sokonomi said he wasn't using any kind of those mods.

**Comment by Sokonomi** [comment]
I will make a video of it happening and report it in a new ticket.
But for what its worth; it seems to be most prominent on tippers that let you select which side to tip from. Courseplay seems to keep setting the trailer to tip from the rear, and then it gets confused as to which part needs to be over the grate to start tipping, resulting in an overshoot (it actually does tip for a split second as it chugs over the grate).

I did a test recording with it moving over the grate at 5 km\h and it still slowly cheesed right over, briefly farting some of its cargo at it, but not stopping.

The thing is, with my road truck (MAN + big red trailer) seems to have no problem. Could it be specific to whatever a Case Puma is pulling? My little Forte HD tractor didn't skip unloading either.

**Comment by pops64** [comment]
I know some mod vehicles are having issue. Mostly the dump trucks.

**Comment by Sokonomi** [comment]
I just had a Case Puma CVX (240 engine, wheelweights, frontloader attacher), and a Farmtech TDK 1600 tipper doing it again. On the soskova map, recorded while moving 6km\h over the farm grate, playing back with speeds "as recorded". So everything is completely vanilla, and (presumably) set up properly.

Its been flipping out with automatically figuring out side distances to combines, too. I had to manually bump it out almost an extra meter to get it to stop slamming into the combine. I think the tractor somehow is running with the wrong instruction set or something.

**Comment by pops64** [comment]
The combine side issue is known. What speed is turn speed set to ?

**Comment by Sokonomi** [comment]
Ive got turn speed cranked up to 30kph., does that also affect tipping speed?
That would explain the problems ive been having.
