### ISSUE TITLE
Mode 5 default change

### ISSUE THREAD

**Issue by Zoochase** [Courseplay/courseplay#2167]
In Mode 5, can the " Stop at last point or next trigger" default on "Active"?  I can't count the number of times I have had to recover a vehicle from a ditch or water because I forgot to change it.
Just a suggestion.
Thanks, Zoo

**Comment by pops64** [comment]
This has been discussed in the past. We aren't going to changing this. It would break mode 5 if you were to use mode 5 has a loop. I would suggest you place a wait point where you want mode 5 to stop and place the stop 3 or more waypoints away. Closed to keep issues area clean.
