### ISSUE TITLE
Krone BigM500 won't turn on field edge

### ISSUE THREAD

**Issue by scaniafreak** [Courseplay/courseplay#2172]
Hi,

I just installed the Krone bigM500 mod in FS17:
http://www.modhub.us/farming-simulator-2017-mods/kronebigm500-v3-pack-3-0/

When i generate a course, and let the mower drive the course, it won't turn on the edge of the field.
When the mower reaches the end of the field, it will reverse a bit to make the turn, but then stops and keeps waiting...

It seems that the mod together with courseplay, will crash the game. The game doesn't respond to key presses anymore, and such. I tested this with only the mod and CP .000160 enabled.

Any idea?

**Comment by pops64** [comment]
Follow https://github.com/Courseplay/courseplay/wiki Could be anything under the sun.

**Comment by scaniafreak** [comment]
I talked to the creator of the mod. This is what he said:

Scaniafreak
2017-07-10 12:18 
Any chance to make this mod compatible with courseplay? I need a Krone BigM which works with coursplay :P 

Eagle355th
2017-07-10 12:42 
I don't know how to do that I would if I new how to Sorry! It has something to do with the beleuchtungV31.lua that makes it not compatablewith alot of mods.. There is someone I know been trying to address this and fix it..I don't know when tho.. Once they fix the beleuchtungV31.lua right it will be compatable with any add on. Hang in there Have A Nice Day! 

So i guess this is a mod issue and has nothing to do with CP.
Anyone has suggestions for the modder to make it compatible with CP?

**Comment by echerost** [comment]
Try to increase turning circle to 16m. I solved this problem in this way.

**Comment by pops64** [comment]
See my earlier comment. Debug channel 12 and 14 for turning

**Comment by 3lronMcBong** [comment]
https://www.modhoster.de/mods/das-big-m-von-krone#description
den musst nehmen der geht gut mit courseplay :-D

**Comment by pops64** [comment]
Closed due to lack of information.
