### ISSUE TITLE
Suggestion for Course Generator/Field Scanner

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/courseplay#2178]
Hi,

I don't know how complicated that is to implement, but is there a way to cut a Field in half with the fieldscanner or when create a course on the loaded field border ?
Like upper/lower half seperation or left/right seperation.

That way you can create 2 courses for the same field for faster work or to seed differen fruits on same field.
Ofc makes only sence on big fields.

**Comment by pops64** [comment]
You would have to manually break the field up into to parts with field removing tool
