### ISSUE TITLE
Courseplay issue multiplayer not dedicated

### ISSUE THREAD

**Issue by Natasmi** [Courseplay/courseplay#2179]
i am trying to host and play a multiplayer server for me and a friend and use courseplay.Courseplay is working fine for me when i create the game but for some reason my friend cannot connect unless i restart the server and disable courseplay.  can someone help again it loads and works fine for me when i host a server but it will not let anyone connect if i have it enabled.

**Comment by dkfiremann** [comment]
I don't think CoursePlay is supported in multiplayer. There was a plan once to get it done, but it has never been finished.

**Comment by Natasmi** [comment]
i have seen posts from many sites saying you can use it on a hosted multiplayer just not a dedicated and when i create a server i am able to use it but people cannot join my server because courseplay is enabled if i disable the mod they have no problem joining.what i need to have figured out is why when the mod is enabled noone can join my server.

courseplay works fine when i host multiplayer but noone can join so i need answer as to why they cannot join.

**Comment by pops64** [comment]
Courseplay is not supported at the moment in any multiplayer. It won't even be thought about until after CP is released. Closed to keep issues area clean.

**Comment by Natasmi** [comment]
i thank you for the reply and understand you want to keep the issues area clean but i was just trying to find out why if someone knew what was causing coursplay not to allow players to connect to a hosted game.i am a programmer myself and have worked on 2 Battlefield titles and multiple Delta Force titles.i am just looking to be pointed in the right direction instead of having to blindly search which i am willing to do if i have to.i will be sharing my findings of my progress and testing as they progress but if i have to start from scratch i will just wait until it is completed.

**Comment by pops64** [comment]
You're are going to find if you can get it working there will be a lot of game breaking bugs. One of these might even be causing the disconnect. Multiplayer was never supported in 15. So it will require a huge amount of debuging to get it to work again.

**Comment by Natasmi** [comment]
i was able to get CP to work fine in FS15.where does debug output as i have already located most of the code and enabled debug in CP but didnt see how debug outputs

**Comment by pops64** [comment]
Game breaking bugs will automatically show up in the log usually as nil errors and sometimes as call stacks. Other debug depends on what is not working. Which involves testing all of CP in multiplayer and see what is not working correctly.

**Comment by Natasmi** [comment]
thank you i have been comparing my cp for fs15 to this one to see how it works without probs on 15 once i make some progress i will gladly share my results with you.

**Comment by Pizmonster** [comment]
remember that when you change a mod your friends will need your copy of the mod since it's not the same as the released one (different hash)
