### ISSUE TITLE
combine feature addition suggestions

### ISSUE THREAD

**Issue by shadow2501** [Courseplay/courseplay#2180]
in the combine controls  menu where it says driver priority. it currently has distance and fill level. the fill level being the trailer with the least in it. i would find it handy if the combine had the option to pick the fullest one 
so there are not a bunch of partially filled trailers on the field. also an option to ignore which side the fruit is on. it doesnt call a tractor when the fruit is on the offload side of the combine. a feature to ignore this and call a driver to the fruit side could prevent the combine from stopping and having to wait.
making both suggestion user selectable would be great as well.

note: this is nothing more than a suggestion.
i love courseplay its the best mod ever.

**Comment by dkfiremann** [comment]
Regarding the drive on fruit side, that option is already there. 
In courseplay it is called Pathfinding. Under the settings tab you can deactived the Pathfinding, and the tractor will then empty the combine even if the pipe is over fruits.

**Comment by pops64** [comment]
We currently aren't taking any suggestions until CP has officially released. Closed for now.
