### ISSUE TITLE
Game crash in Mode 2 

### ISSUE THREAD

**Issue by Kingkaes96** [Courseplay/courseplay#2181]
Hello Guys, 

the game crashes in Mode 2 after serveral Minutes. In all other Modes the game run over Hours without
a Problem. 
[log.txt](https://github.com/Courseplay/courseplay/files/1150267/log.txt)

**Comment by pvajko** [comment]
Could you run it with the debug channels 3, 4, 7 and 9 and send the log?

**Comment by Kingkaes96** [comment]
Here is a another Log File and I test it with the Debug channels. 
[log.txt](https://github.com/Courseplay/courseplay/files/1150275/log.txt)

**Comment by pvajko** [comment]
Can you try with v1.0168?

**Comment by Kingkaes96** [comment]
I played 1 hour with the v1.0168. I have no crash but the game freeze when a mode 2 Tractor search for a 
Route to the chipper for example.
The Log is with debug channel 3,4,7,9
[log.txt](https://github.com/Courseplay/courseplay/files/1150353/log.txt)

**Comment by pvajko** [comment]
Thanks. That's something Thomas wanted to take a look. In the meanwhile, if you turn Pathfinding off it should not happen.

**Comment by Kingkaes96** [comment]
ok, thank you for the fast support.

**Comment by ThomasGaertner** [comment]
try again with 169 or higher and report ....

**Comment by Biker23** [comment]
Sorry. It's still doing it even with the combine stopped and no helper in it. Thanks!

**Comment by pvajko** [comment]
Can you post a log file with debug channels 3, 4, 7 and 9 active?

**Comment by Biker23** [comment]
Hope this is what you asked for. At the end nieuwholland BB1290 was just driving around in a circle instead of going to another lane, it was using CP. Fasttrack 3000 were the ones causing a small freeze in this game.
Also, there is a freeze when I save a course.
I have attached a second log, but that is from when I was trying to get the tractors to another field using Follow me and the image was just freezing every second.
Thanks!
[logCP.txt](https://github.com/Courseplay/courseplay/files/1151252/logCP.txt)
[logFollow.txt](https://github.com/Courseplay/courseplay/files/1151253/logFollow.txt)

**Comment by ThomasGaertner** [comment]
can you describe the situation please, can you post a video of it ?

**Comment by Biker23** [comment]
afraid I can't post a video, here's a paint drawing! I also have a tractor that is following the same course and there is no issue.
THX
![cp circle](https://user-images.githubusercontent.com/30208621/28283724-8eb8288e-6b26-11e7-96ca-2a0356228af9.jpg)

**Comment by pops64** [comment]
The circling issue is completely separate from this. A short freeze on course save is dependent on the number of way points and computer specs. Has for fasttrack causing a freeze Thomas or pvajkao will look into that.

**Comment by pvajko** [comment]
I won't be able to, looking at the logs that seems to be a collision issue, it is using the old course generation and no pathfinding so it is probably not my fault :)

**Comment by ThomasGaertner** [comment]
why are you going in mode2 with a baler ?

**Comment by Ridlerr** [comment]
The  problem is AIVE, AIVE and courseplay are again incompatible, i update from 0155 to 0169 and now my game crashes every time a tractor starts to drive to a combine that is run by AIVE,if the combine is run by courseplayer and the pipe open to crops the game lags, but doenst crash.

**Comment by Biker23** [comment]
"I won't be able to, looking at the logs that seems to be a collision issue, it is using the old course generation and no pathfinding so it is probably not my fault :)" Can you please explain, is it my fault?
I do not know what mode 2 is and I can't find any explanation for it. The baller was just following the course of a windrower.
Hope this helps. Thank you!

**Comment by pvajko** [comment]
No, it's not your fault of course, sorry, I just made quite a few changes in the course generation and pathfinding and was concerned that those changes caused the problems you see but to my relief it seems to be something else. Sorry for the confusion.

**Comment by pops64** [comment]
Closing this out has no single issue is present in this thread. If you have an issue that isn't reported please make a clear and concise issue about it. https://github.com/Courseplay/courseplay/wiki
