### ISSUE TITLE
Error: Running LUA method 'update'.

### ISSUE THREAD

**Issue by Liquid515** [Courseplay/courseplay#2184]
Error: Running LUA method 'update'.
C:/Users/Liqui/Documents/My Games/FarmingSimulator2017/Maxfarm/ZZZ_CoursePlay/mode2.lua:1372: 
[log.txt](https://github.com/Courseplay/courseplay/files/1150584/log.txt)
bad argument #4 to 'format' (number expected, got nil     version number 167

**Comment by pvajko** [comment]
This has been fixed in v1.0168, see #2181

**Comment by Liquid515** [comment]
thanks guys
