### ISSUE TITLE
Number of runs to perform issues.. 

### ISSUE THREAD

**Issue by valdimellen** [Courseplay/courseplay#2186]
Hi.. 

i am having some issues ved mode 1.

i am transporting Chaff from a silo to BGA (reverse unloading)
Video Link: https://www.dropbox.com/s/vahwre4pe6b5qba/test.mp4?dl=0

The Silo is http://www.fsmods17.com/futter-lager-fs17/
[log.txt](https://github.com/Courseplay/courseplay/files/1153450/log.txt)
Debug Channel: 1, 2, 19
 
The Number of runs to perform is not working for me with this silo. :-( 
Cp Version 5.01.00169

Mark

**Comment by valdimellen** [comment]
To Info

Standart tractor and tipper.

**Comment by pops64** [comment]
Short answer is the wait point you have placed is way to close to the stop point. I would recommend having any wait point placed more than 3 waypoints from the end or beginning. In mode 1.

**Comment by valdimellen** [comment]
pops64 

Thanks ill try that. ;-)

**Comment by valdimellen** [comment]
The wait point was the reason..

ill close the topic. 

Thanks pops64 for the advice..
