### ISSUE TITLE
No mode for fluids with Annaburger MT75?

### ISSUE THREAD

**Issue by jordyboytjuh** [Courseplay/courseplay#2187]
Hello, is it right that courseplay is not working with my Annaburger MT75 for fluids?

I'm playing the "Borchersee" map from fsm-team right now, and I can't get the courseplay working for my "Gärreste" in the BGA as well as the "BioGas" from the "Klärwerk". 

I've tried the Graintransport mode and the Liquid product transport and i'm using the courseplay version: 5.01.00162.

Keep up the good work, love Courseplay!

**Comment by pops64** [comment]
Have you tried giants fuilds has this may be the case of CP not recognize those fill types?

**Comment by pops64** [comment]
Closed won't make it on the list till response is given.
