### ISSUE TITLE
All Harvesters

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#2189]
If CP is capable of seeing the edges of fields, why is it that when you start a course at the 1st way point or even the nearest, CP rushes into the field several meters and then lowers the header?  At least in earlier versions of CP I could start the header and lower it to not miss a portion of the fruit, but no matter how far away or how near I am it zooms to beyond the start point then lowers the header.

**Comment by Blackmankot** [comment]
Yes, I agree. I also do not like this principle of starting work.

**Comment by pops64** [comment]
If you start at waypoint one or if nearest select waypoint one it will raise the header and the lower it upon reaching waypoint 1. Ethier way this is something we aren't going to fix at this time. Closed to keep issues area clean
