### ISSUE TITLE
Error: Running LUA method 'update'.

### ISSUE THREAD

**Issue by jeremy3112** [Courseplay/courseplay#2190]
My game freeze during game after few minutes.
On the log.txt I have this messages
Error: Running LUA method 'draw'.
dataS/scripts/triggers/SiloTrigger.lua(366) : attempt to index field 'siloTrailer' (a nil value)
Warning (LUA): 'setVisibility': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
Error: Running LUA method 'update'.
C:/Users/Jeremy/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/distance.lua:31: attempt to index local 'object' (a nil value)

**Comment by pops64** [comment]
follow https://github.com/Courseplay/courseplay/wiki .  a partial log does not help us.

**Comment by pops64** [comment]
Closed due to not enough information
