### ISSUE TITLE
Mode 10 - Pause when there is nothing to do?

### ISSUE THREAD

**Issue by JordyvA** [Courseplay/courseplay#2191]
Hi guys,

I've set up my BGA with the push shield for "aufschütten", the guy keeps driving back and forward, even if there is no heap anymore. Is it possible to recognize that everything is pushed back in de silo, and just drive to the waiting point, waiting for some heap? 

Keep up the good work!

**Comment by pops64** [comment]
Yea there is a system. It may need some fine tuning.

**Comment by jordyboytjuh** [comment]
Ok thanks! I've also noticed that sometimes the shield is not going down on the "stop" sign, but it's going down and immediately up again. So the tractor is driving with the shield up into the silo.

**Comment by pops64** [comment]
That's a different known issue

**Comment by jordyboytjuh** [comment]
Okay thanks for the quick response!

**Comment by pops64** [comment]
Closed #2909
