### ISSUE TITLE
levelling and compact

### ISSUE THREAD

**Issue by willie2016** [Courseplay/courseplay#2194]
Not sure if this was reported before , i recorded the course for the tractor and blade to reverse drive level and compact the silage clamp , its reversing but around in circles and every few minutes iv to switch back to it and stop it and select drive course again

**Comment by pops64** [comment]
Make sure your course is 100% correctly setup up. Follow https://github.com/Courseplay/courseplay/issues/1568 . Other wise follow https://github.com/Courseplay/courseplay/wiki pictures or video of how you have your course setup and what it is doing.

**Comment by willie2016** [comment]
i dont see in there how to set up properly ? iv followed a tutorial on youtube, i start recording course inside the clamp and drive out maybe 7 or 8 waypoints and leave a waitpoint , then reverse back near enough to the middle of the clamp as i can get and set course to level and compact , stop all courseplayers only , autmatic blade height and auto speed , 50 meters detecting other vehicles on courseplayer and generate the course then save it , but when i click drive now it just goes straight for a minute then goes around in circles

**Comment by dkfiremann** [comment]
Can you show a pictures of what you are seeing?

**Comment by pops64** [comment]
You have to make sure your starting it in the right place. Starting it near the wait point sometimes works. Try with only vanilla equipment as well

**Comment by willie2016** [comment]
How do i post video here , i tried recording with bandicam and sending but it doesnt accept file type , i dont wanna put it on youtube as its my personal channel i would have to put it on

**Comment by willie2016** [comment]
![farmingsimulator2017game 2017-07-28 18-29-50-074](https://user-images.githubusercontent.com/24280974/28729188-7729e4fa-73c3-11e7-8f61-457db2d51165.jpg)
![farmingsimulator2017game 2017-07-28 18-29-58-224](https://user-images.githubusercontent.com/24280974/28729184-77237a3e-73c3-11e7-985c-b1b5a2ab98d5.jpg)
![farmingsimulator2017game 2017-07-28 18-30-22-492](https://user-images.githubusercontent.com/24280974/28729187-7728f84c-73c3-11e7-919c-bb42781440ac.jpg)
![farmingsimulator2017game 2017-07-28 18-29-56-481](https://user-images.githubusercontent.com/24280974/28729186-77265b14-73c3-11e7-8a95-f940497bb1ac.jpg)
![farmingsimulator2017game 2017-07-28 18-30-06-118](https://user-images.githubusercontent.com/24280974/28729189-77305cea-73c3-11e7-9533-0aaa33e1c6c4.jpg)
![farmingsimulator2017game 2017-07-28 18-29-54-088](https://user-images.githubusercontent.com/24280974/28729185-77266e9c-73c3-11e7-8002-4f61fd9f86ac.jpg)
![farmingsimulator2017game 2017-07-28 18-30-11-841](https://user-images.githubusercontent.com/24280974/28729190-773b010e-73c3-11e7-9633-a60209159134.jpg)
![farmingsimulator2017game 2017-07-28 18-30-24-154](https://user-images.githubusercontent.com/24280974/28729191-77401f86-73c3-11e7-9de9-cf4e419285ec.jpg)
![farmingsimulator2017game 2017-07-28 18-30-09-282](https://user-images.githubusercontent.com/24280974/28729192-7746f81a-73c3-11e7-8494-859cebfdc4ea.jpg)

**Comment by pops64** [comment]
You didn't listen to my earlier post follow #1568. If you set up your course as in the directions linked in post which has a diagram of were 1,2 and last waypoint should be placed. You shouldn't have issues.

**Comment by willie2016** [comment]
im looking at the pots in #1568 and i dont see where it shows how to set up the course correctly , all i see are old posts from end of 2016 untill january 2017

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/files/679279/setup_mode10_course.pdf very first post ...

**Comment by pops64** [comment]
Closed due to inactivity.
