### ISSUE TITLE
Selling equipment while its run by CP crashes the game

### ISSUE THREAD

**Issue by 2korda2** [Courseplay/courseplay#2195]
Game crashed. Log has "endless" entries:
Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/Attachable.lua(869) : attempt to index field 'attacherVehicle' (a nil value)

I think I sold a plow and then the tractor itself.
(v5.01.00169)

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki. Need a full log. Did you sell this while CP was running on that equipment that was sold?

**Comment by 2korda2** [comment]
Yes, CP was running. Log attached. Yes, I have quite a lot of mods but it was a new savegame with just a few of them selected.
[log.txt](https://github.com/Courseplay/courseplay/files/1171760/log.txt)

**Comment by 2korda2** [comment]
Removed most of the mods. Started game. New savegame. Coldcrest Valley. Just CP selected from modlist.
Tractor by field 14. Attached cultivator. Created route. Started it. Went to Shop Menu->Garage. Sold cultivator, then tractor. Crashed. Forced game shutdown. New log attached.
[log.txt](https://github.com/Courseplay/courseplay/files/1171797/log.txt)

**Comment by Brzzl** [comment]
There must be a change from 171 to 173 which causes all the errors. many of my youtube followers are having the same problems and are reporting that their game crashes while CP is running.

**Comment by pvajko** [comment]
Are you sure it is the same problem? Is it not #2198? Never thought so many people selling their equipment while working with it...
Would be good to know about those other problems, what causes them and see a log.

**Comment by sootysax** [comment]
this has been happening with CP for a long time...  not so much a bug as a player goof I think

**Comment by pops64** [comment]
Closing this out. We are super busy and this is something avoidable. May come in the future when we have time.
