### ISSUE TITLE
CP + Combine Addon => issue with auger wagons

### ISSUE THREAD

**Issue by RedOhne** [Courseplay/courseplay#2197]
Hi,

yesterday I wanted to test the combine addon (modhub) with courseplay using a auger wagon to fill a trailer. CP works fine with the combine and combine addon. Overloading is working and everything works as expected. 

But the overloading from the auger wagon into a standard trailer does not work. The tractor reaches the overloading point, but does not start. I uses the Horsch UW 160 from Modhub, too. This is working perfectly with CP without the combine addon. 

Since I don't find a previous issue with this, i opened this one. Maybe you already tested it, or have additional infos. I also posted something in the ModHub Forum to check the combine addon

https://forum.giants-software.com/viewtopic.php?f=939&t=114968&p=897546#p897546

Maybe this can be sorted out, since using both mods would be really great.

Thanks Tim

**Comment by Brzzl** [comment]
opened a ticket with same problem the other day... https://github.com/Courseplay/courseplay/issues/2096

**Comment by RedOhne** [comment]
Hi, I close this issue, since there is the the issue #2096 from Brzzl. Sorry, haven't found it before.
