### ISSUE TITLE
Error: Running LUA method 'update'.

### ISSUE THREAD

**Issue by Broklyn11** [Courseplay/courseplay#2198]
C:/Users/silve/OneDrive/Dokumente/My Games/FarmingSimulator2017/mods/FS17_courseplay/img/signs/stop.i3d (0.64) ms
## Courseplay: register later loaded mods
Disabled withering
data/vehicles/steerable/caseIH/caseIH1660.i3d (44.78) ms
data/vehicles/cutters/caseIH/caseIH1030Cutter.i3d (37.12) ms
data/vehicles/steerable/newHolland/newHolland8340.i3d (39.67) ms
data/vehicles/tools/kuhn/kuhnCultimerL300.i3d (20.80) ms
data/vehicles/steerable/caseIH/caseIH1455.i3d (54.58) ms
data/vehicles/tools/greatPlains/gp3P1006NT.i3d (23.82) ms
data/vehicles/trailers/metaltech/db8000.i3d (32.44) ms
data/vehicles/steerable/lizard/lizardPickupRodeo.i3d (29.08) ms
data/placeables/shelters/storageShelter02.i3d (2.74) ms
data/placeables/shelters/storageShelter01.i3d (5.03) ms
data/placeables/shelters/vehicleShelter.i3d (1.50) ms
data/objects/bigBagContainer/bigBagContainerSeeds.i3d (3.38) ms
data/objects/pallets/fertilizerTank.i3d (2.01) ms
data/objects/bigBagContainer/bigBagContainerFertilizer.i3d (1.86) ms
data/vehicles/train/locomotive.i3d (19.21) ms
data/vehicles/train/wagonTimber.i3d (9.28) ms
data/vehicles/train/wagonWoodChips.i3d (9.85) ms
data/vehicles/train/wagonGrain.i3d (9.47) ms
data/vehicles/train/wagonSugarbeets.i3d (10.01) ms
dataS2/character/player/player01.i3d (287.43) ms
dataS2/character/pedestrians/man03.i3d (4.88) ms
dataS2/character/pedestrians/woman04.i3d (4.68) ms
dataS2/character/pedestrians/man05.i3d (4.86) ms
Error: Running LUA method 'update'.
C:/Users/silve/OneDrive/Dokumente/My Games/FarmingSimulator2017/mods/FS17_courseplay/mode2.lua:1001: bad argument #1 to 'abs' (number expected, got nil)
=============================
error repeat 1000 times

it beginns if the drecher finich loading 53l in tank than running and running

in different Version of courseplay

**Comment by pvajko** [comment]
Try with 173 and report back. And smaller fonts are ok, too :)

**Comment by Broklyn11** [comment]
The vehicels there are liste are not in this score i used only courseplay mod and a new score

**Comment by Broklyn11** [comment]
I install new the game and have no mods only courseplay. i dont understand how this vehichles are listet

**Comment by pvajko** [comment]
May have a misunderstanding here. All was trying to say is that you should try with the latest (1.0173) Courseplay version, it has this issue fixed.

**Comment by Broklyn11** [comment]
how find i version number i used version from 23.7.2017

**Comment by pvajko** [comment]
Just download the latest one and try it.
(the version is in modDesc.xml and in the log file)

**Comment by Broklyn11** [comment]
Funktion
Manny thanks for your fastley Help
PS.: but i dont understand how this vehicles listet without i have it.
the are vehicles till the first crash wy fs17 dont kill them 
But not your problem

Resolved
