### ISSUE TITLE
moving liquid to sell trigger 

### ISSUE THREAD

**Issue by shadow2501** [Courseplay/courseplay#2199]
ok so i did look at the manual and saw that the liquid transport mode doesnt quite work the way i wanted, so i tried the grain transport mode and the trailer wont fill.
it stops at the fill point and says 0 of 70k
what i was trying to do was to fill a tanker at the slurry tank and transport it to a sell trigger.
i picked slurry as fill type and unlimited runs.
im not even sure if it can do this.

**Comment by Blackmankot** [comment]
To transport all liquids, use the 8 mode.

**Comment by pops64** [comment]
Has blackmankot said mode 8 is for liquids. It supports all vanilla liquids minus filling water from a river. Which it may never support. Make sure you use a wait point to designate the unload point. Also the manual is not a 100% up to date. Closed to keep issues area clean.
