### ISSUE TITLE
Mode 10 improvement - Mode for only trailers?

### ISSUE THREAD

**Issue by jordyboytjuh** [Courseplay/courseplay#2202]
Is it possible to introduce a new option for mode 10 too look only for vehicles with trailers? So that my course for empty bunker (mode 9) can operate together with my shield (mode 10)? Only the trailers has to stop for the shield too move for the pause stop.

**Comment by pops64** [comment]
Currently, at this time we no longer taking any suggestions until CP has officially released. We will revisit this in the future.  Closed for now

**Comment by jordyboytjuh** [comment]
Okay, no problem. I will look into it myself. Thanks for the response!
