### ISSUE TITLE
clear install

### ISSUE THREAD

**Issue by Broklyn11** [Courseplay/courseplay#2203]
I reinstall the farming ordner (delete all) in dokument
But courseplay still have all the vehicle befor the crash.

My Traktor dont stop at last waypoint ...drive slowly to the first and beginn the course new

**Comment by pops64** [comment]
If you are using the new course generator this is a known issue

**Comment by Broklyn11** [comment]
help reinstall game.
i see after reinstall fs 17 still have old datas

**Comment by pops64** [comment]
You have to make sure your FS 17 folder in your documents folder is deleted. This is not the place to get that kind of help. Closed this issue is being looked into
