### ISSUE TITLE
Tractor in field work starts over again at end of field work new course generator

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#2204]
If using new course generator. Tractor will occasionally start at the beginning again. Cause last row has to few waypoints and turn manuver sets it back to waypoint one

**Comment by Broklyn11** [comment]
By me,
This begin after copie a Savegame 2 to Savegame 3
I Used Steam for Reinstall. And delete all dokument farming folder
 Older Version make now the same mistake

**Comment by pops64** [comment]
Reinstalling won't work if you generate the course in the same manner. The only fix is to use the old system.

**Comment by Broklyn11** [comment]
But before i copy all looks fine
maybe here the point to find the issue

**Comment by Broklyn11** [comment]
did i need delete the coureplaycourse folder?

**Comment by pops64** [comment]
What ever course you are using was generated with the new system if you delete that course or not use that course and use the old system it will work just fine. Other wise just keep an eye on those courses. It usually happens when the lanes aren't parallel to an edge.

**Comment by Broklyn11** [comment]
<?xml version="1.0" encoding="UTF-8"?>

-<modDesc descVersion="37">

<version>5.01.00173</version>

make same mistake
didnt have more older vision

**Comment by Broklyn11** [comment]
sorry 5.01.001.171
course delete same effect

**Comment by Broklyn11** [comment]
mode 5 
 Stop at last point or at next trigger    stop the Traktor
other mode and combines i now testet

**Comment by pops64** [comment]
Well if you read the manual. Only a few modes stop at the last waypoint ...

**Comment by Broklyn11** [comment]
well. I said this to help narrow the problem
The bug started when I copied a game savegame2 to savegame3.
Strangely, he now makes the mistake not only in Vers 173, but also 171.
older Version i didnt have.

**Comment by pops64** [comment]
Copying savgame does nothing. Courses are shared based on the map alone

**Comment by pvajko** [comment]
Please post your courses and savegame, see the last point in https://github.com/Courseplay/courseplay/wiki for instructions.

**Comment by pops64** [comment]
https://www.dropbox.com/s/1sh7dk5tnmxwehp/badendofcourse.zip?dl=0 this was done on lossburg. Use the tractor on field 26. In that spot with two headlands and your course generator it creates this bug. The course I made for you is the result

**Comment by pvajko** [comment]
@pops64 , btw the savegame/course named "peter this is it" upload worked great, I was able to reproduce it in a minute.

**Comment by pops64** [comment]
Lol. Your welcome :P
