### ISSUE TITLE
Combi mode - freeze.

### ISSUE THREAD

**Issue by CaseFan** [Courseplay/courseplay#2206]
Hello everybody!

Problem: In combi mode, when tractor needs to go to combine or go to unload its trailers in farm, game freezes. Also if tractor needs to go further into field (plowed manually to have bigger field), game also freezes. "Freezing" lasts for about 5 minutes. After that it goes again for 2-4 seconds and freezes again (for me it looks like that courseplay tries to calculate waypoints or something like that) . Everythings else works perfectly, exept this mode. Any ideas?

Courseplay version 00173. I also tried with 00159 - runs very well, without any issues, but then AI become not so smart like in 173.

Log shows LUA Callstack error - setVisibillity 

Warning (LUA): 'setVisibility': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
LUA call stack:
  dataS/scripts/effects/CutterEffect.lua (74) : setVisibility
  dataS/scripts/effects/Effect.lua (49) : transformEffectNode
  dataS/scripts/effects/CutterEffect.lua (21) : load
  dataS/scripts/vehicles/specializations/Cutter.lua (272) : load
  dataS/scripts/vehicles/Vehicle.lua (627)
  dataS/scripts/utils/Utils.lua (1858) : oldFunc
  dataS/scripts/BaseMission.lua (767) : load
  dataS/scripts/BaseMission.lua (800) : loadVehicle
  dataS/scripts/events/ResetVehicleEvent.lua (58) : loadVehicleFromXML
  dataS/scripts/network/Connection.lua (77) : run
  dataS/scripts/gui/InGameMenu.lua (3454) : sendEvent
  dataS/scripts/gui/dialogs/YesNoDialog.lua (62) : callbackFunc
  dataS/scripts/gui/dialogs/YesNoDialog.lua (50) : sendCallback
  dataS/scripts/gui/elements/ButtonElement.lua (191) : raiseCallback
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/GuiElement.lua (279) : mouseEvent
  dataS/scripts/gui/elements/Gui.lua (270) : mouseEvent
  dataS/scripts/main.lua (1811) : mouseEvent

**Comment by pvajko** [comment]
Could you try with debug channels 4, 7 and 9 active? And post the entire log file please.

**Comment by pops64** [comment]
In gist or pastebin thanks directions here https://github.com/Courseplay/courseplay/wiki

**Comment by CaseFan** [comment]
Sorry for mistakes. Log file.

https://pastebin.com/yh41dgBp

**Comment by pvajko** [comment]
Thanks, this seems to be a huge field. Which map is this? And how much fruit is on the field?

Looks like we need to check the field size before generating the pathfinding grid. I'll have some time next week to fix this. Until then, you can turn off pathfinding and it won't freeze.

**Comment by pvajko** [comment]
Also, if you could post a savegame that would be great.

**Comment by CaseFan** [comment]
I'm playing on "River Valley XXL" map, and yes it's a 4x map. That field has almost 40ha size. 

Thank you for replys!

**Comment by pvajko** [comment]
@CaseFan , I'm not able to reproduce this, even with a field twice the size. It takes a few seconds, but it does generate a path. You wrote that it freezes for minutes then it runs a few seconds again. The log you posted on pastebin does not look like it ran again, have you waited until it ran a again after the freeze before taking the log?
Also, I can't download big files from where I am now and the River Valley map I found does not seem to contain field 100 what your log indicates you were using. 
Are you familiar with using the console in the game? Could you do a 'cpSaveAllFields' command? That will create a cpFields.xml file under CoursePlay_Courses/FlusstalXXL_BetaSampleModmap  or similar in your game folder, I'd need that file.

**Comment by CaseFan** [comment]
@pvajko Yes, that map doesn't have field number 100, because i have saved it by my self. I edited that map a little bit, to have more space near farm, and that field is made on the river near farm. Okay, i will try to upload new log, screenshot of that field and cpFields.xml

**Comment by CaseFan** [comment]
I have everything now putted in this zip file, hope it helps. And after cpSaveAllFields command to reproduce freezing, was harder than before.
[freeze.zip](https://github.com/Courseplay/courseplay/files/1185510/freeze.zip)

**Comment by pvajko** [comment]
Thanks, this helps. Two questions:
1. from the log it seems like it was frozen for about 13 seconds, not the 5 minutes you wrote, how long was it frozen this time?
2. The other weird thing is that it did find a path around the fruit several times before, but not this last time. Can you tell me were approximately was the fruit harvested at that time?

**Comment by CaseFan** [comment]
@pvajko I'm feeling a little embarrassing, because now i don't now why, it become kinda hard to freeze the game. I have managed to freeze, but as I understand the log, it doesn't show that the game was freezed for about 2 mins. Here's the log -> https://pastebin.com/PeibqNJD 

Answer to question 2: I was trying to freeze the game, and skiped to course 2 lines, so combine was 2 lines into field, and made like a fruit obstacle for tractor. Tractor was going for combine through treshed area.

**Comment by pops64** [comment]
The only other thing I can think is your computer is hanging up. You do have a crap ton of non-CP warnings and errors and call stacks in your log. I would suggest running only running the map and CP and see if you can get it to freeze then.

**Comment by pvajko** [comment]
@CaseFan, no worries, first of all, there seems to be a bug in the pathfinding which can't handle some cases a the combine is outside the field. Can you confirm that your combine is turning outside the field?

As for the freezing time, the important thing for me is to know if our debug time output is correct or not, in this last log I see 2 seconds delay for the pathfinding and no freezing, since the tractor seems to be driving afterwards. What exactly happened in this last case? Was it frozen and you had to kill it? Or it started moving again? If yes, when?

When I reproduce this problem in my laptop (out of the game), my slow laptop needs 16 seconds for the worst case for this specific field, that's why we think there may be some other things going on there too.

**Comment by CaseFan** [comment]
Yes, combine is turning outside the field if there are no headlanes. 
Yesterday, i tried as pops64 offered map + courseplay, and i have encountered a freeze. I just left it and after 2-3mins everything was going again (sorry, haven't saved the log).

Today, I have created new courses on new field, a little bit smaller, but without square corners, and it was going without gliches, freezes or something like that. Later today, i will try to create new courses on that field i was having freeze, maybe i have made somekind of mistake in course creation.

**Comment by CaseFan** [comment]
Working perfectly with 177. Thank you for help developers!
