### ISSUE TITLE
Mode 2: behavior after unload

### ISSUE THREAD

**Issue by webalizer-gt** [Courseplay/courseplay#2208]
After unloading from combine into trailer (not full, not in fruit) the tractor should just keep waiting where it is. Instead after a few seconds it drives for about 20 meters straight and then stops.
This seems to be very unnecessary (at least that much) and causes blocking of the vehicle if that happens  near field edges where obstacles can be.

**Comment by pops64** [comment]
If it is close enough to the field edge it should make a u turn to park. And if you're field is long enough it should wait till the combine moves out of the way then parks behind the combine. There is a rare bug that has it park in the fruit this case.

**Comment by pops64** [comment]
Closed due to inactivity and not reproducible.
