### ISSUE TITLE
Bug in all Version

### ISSUE THREAD

**Issue by Broklyn11** [Courseplay/courseplay#2209]
I didnt understand this issue

First time the Bug by copy Savegame 2 to savegame 3 and install
RM_session.zip mod

Traktor on Mode 5 (or Butten 5)
Dont stop on Last waypoint drive slowly to the first and Loop
Ignored unload trigger
Stop only if i used    Stop at last point or at next trigger active and set waypoints on unload trigger
and make by manuell.

Now i reinstall by Stean and on a other Computer used only Courseplay vers. 5...171,5 ...100
and the same mistake.

Dont now 

Only constand is Steam for Install. perhaps i need to by the cd?
Steam inpossible to install a clear version?

What data can shoot all courseplay versions so?

I have no idea synonymous with allten courseplay versions to eliminate this error.

Hope your find a reselution

sorry if bad endlish
Translate by Googel from german

Many Thanks
Broklyn11

**Comment by pops64** [comment]
Like I said in all the post you have reported in this issue. Mode 5 is designed to loop unless you hit the stop at end button. We aren't fixing this. Mode 5 isn't designed for anything other than transporting tractors from A to B. The Manual for [Mode 5](http://courseplay.github.io/courseplay/de/manual/index.html#driveMode5) This manual has been partially translated to German, mode 5 has not. You should be able to find German Youtube tutorials out there as well. Closed not an issue.

Translated into German by Google


Wie ich schon sagte in der ganzen Post haben Sie in dieser Ausgabe berichtet. Modus 5 ist entworfen, um zu schleifen, wenn Sie den Anschlag am Endeknopf schlagen. Wir reparieren das nicht. Modus 5 ist nicht für irgendetwas anderes als das Trappen von Traktoren von A nach B ausgelegt. Das Handbuch für [Modus 5 ](http://courseplay.github.io/courseplay/de/manual/index.html#driveMode5) Dieses Handbuch hat Wurde teilweise ins Deutsche übersetzt, Modus 5 hat nicht. Du solltest auch deutsche Youtube-Tutorials da draußen finden. Geschlossen kein Problem.

Übersetzt ins Deutsche von Google
