### ISSUE TITLE
Mode 2 with Forage Harvester Problems 

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#2211]
Very much struggling to have Mode 2 work correctly with the Big X 580 harvester.

The pathfinding is doing a great job of routing the tractor/trailer around the crops..   however after it gets to the waiting point, instead of following the harvester, it makes a 360 degree circle before following the harvester, usually crashing right into the fence or the hedges (even though it was perfectly lined up to get next to it) .   This is also happening when driving to the unload route..  pathfinding working perfectly, until it reaches the first waypoint, then it has to circle again before driving the route, undoubtedly crashing into a hedge or fence.

The other problem I'm having is when the forager turns around..   the tractor does a nice circle and lines up with the forager for the next row, but half of the time, it does not back up enough for the harvester to engage (usually just a few meters short), and they both sit there, waiting for each other forever..

https://www.dropbox.com/s/65r3aqiv4hfvi5v/2017-08-02_131302932.mp4?dl=0

https://www.dropbox.com/s/vqj4f03b1vxz2ho/2017-08-02_131337268.mp4?dl=0

**Comment by pvajko** [comment]
Can you post a full log with debug channels 3, 4, 7 and 9 active? And which field on which map is this?

**Comment by pvajko** [comment]
Also, is this only the Big X or other harvesters, combines?

**Comment by sootysax** [comment]
https://gist.github.com/sootysax/b8648c7774e3d66900cf24946b014545

Field 6 on CPFv3.   There are similar issues with crop harvesters, mostly around attaching to the unload route..   taking a nice and neat path around the crop and driving directly into the hedges :p

**Comment by pvajko** [comment]
This log seems to have only channel 14 activated. What I need is 3, 4, 7 and 9. 

I guess CPFv3 is Coldborough Park Farm. That's my favorite map, but those hedges really confuse the collision avoidance. I think I have fix for that (see also #2200), I just need the logs to make sure that this is the same issue.

**Comment by sootysax** [comment]
https://gist.github.com/sootysax/852297c2761931770dc6a761cfa1b0b4

**Comment by pvajko** [comment]
Looks like this is the case when the tractor does a 360 when reaching the harvester, right? Can you tell approximately how far is the tractor from the harvester when it starts circling?

If you happen to have log for the other one for the unload case that would be great.

**Comment by sootysax** [comment]
it circles as soon as it reaches the last purple line on the pathfinding course..  which also happens on the unload route, which overshoots the first waypoint of the unload route

**Comment by pvajko** [comment]
Thanks. Could you check out 1.0178, I hope it fixes the transition to the unload route. I'll have to work on the rest.

**Comment by pvajko** [comment]
The turn problem is a completely different issue therefore moved to #2212
