### ISSUE TITLE
Forager waits for tractor after turn forever

### ISSUE THREAD

**Issue by pvajko** [Courseplay/courseplay#2212]
On behalf of @sootysax, splitting #2211:

The other problem I'm having is when the forager turns around.. the tractor does a nice circle and lines up with the forager for the next row, but half of the time, it does not back up enough for the harvester to engage (usually just a few meters short), and they both sit there, waiting for each other forever..

https://gist.github.com/sootysax/b8648c7774e3d66900cf24946b014545
https://www.dropbox.com/s/vqj4f03b1vxz2ho/2017-08-02_131337268.mp4?dl=0

**Comment by pvajko** [comment]
@ThomasGaertner said: "I know the problem of #2212: its the difference of height . I don't take the height difference into account while setting the way points"

**Comment by pops64** [comment]
@sootysax try again version 199 or higher

**Comment by pops64** [comment]
Assumed fixed
