### ISSUE TITLE
Silo Fill/Empty Mode ; Telehandler wont complete circuit.

### ISSUE THREAD

**Issue by Sokonomi** [Courseplay/courseplay#2213]
Ive been having issues with my telehandler freezing up while trying to unload a silage silo. It will do the whole dance right up until the last node before waitingpoint 3 (unload point), where it then promptly stops with a bucket full of silage and the biogas hopper a meter ahead. Ive observed the same behavior with one of my wheel loaders as well.

What am I doing wrong?

Map : Sosnovka, Biogas Plant
Telehandler : Manitou MLT 840 + Magsi Shovel

**Comment by pops64** [comment]
Make sure your save positions for loading unloading pre unloading and transport aren't at Max travel of the movement arms this is a known issue that won't be fixed.

**Comment by Sokonomi** [comment]
Ive checked off the things you've mentioned; None of the positions are maxed out, the wait point is pretty much hugging the hopper (backed off until not literally touching though). The shovel is full of silage, and the unload position is clear of touching anything, though it stops in pre-unloading position.

http://i.imgur.com/DuF6FKQ.jpg

Heres a picture of where it stops. Its not on the unload point. It just randomly stops.

**Comment by pops64** [comment]
Follow http://courseplay.github.io/courseplay/en/manual/index.html#driveMode9 especially step 5 which I think that is the problem you are having. I think in the code if it hasn't detected the hopper by that point it will just stop and start looking for a tipper.

**Comment by Sokonomi** [comment]
It was indeed a user error. Having two nodes before waitpoint 3 aligned straight to the hopper is essential for it to function. Tightening the last turn has fixed my problem.

It seems courseplay has been improved a lot concerning recording of tight turns. From what I recall back in FS13, making turns too tight would cause it to start circling. Now I can make it as tight as I want and it still works great.
