### ISSUE TITLE
Tractor doesn't turn at the end of a straight pass

### ISSUE THREAD

**Issue by Timmiej93** [Courseplay/courseplay#2214]
Log: https://pastebin.com/CRSyEpzs
Enabled mods: https://pastebin.com/YpfTKMSy
Version: v5.01.00177
Map: LössHügelland v4.1

Issue:
On fieldwork mode, a tractor with a trailed implement (I noticed it with the Väderstad Rapid A 600S and the Vogel&Noot Terra Disc 600), the tractor sometimes just wanders off at the end of a straight lane. Instead of lifting and turning, it lifts the implement, and drives off straight, until it hits a tree or the map edge. This doesn't always happen, usually it happens after 3 or 4 passes, which worked correctly. No errors or messages.

**Comment by pops64** [comment]
Picture of where it is occurring with all waypoints on. How are you generating the course?

**Comment by pvajko** [comment]
I think this is a duplicate of #1878

**Comment by Timmiej93** [comment]
This is indeed a duplicate, my apologies. I didn't find the other tread in my search.
