### ISSUE TITLE
Combine offload mode : Delayed after filling 100%

### ISSUE THREAD

**Issue by Sokonomi** [Courseplay/courseplay#2216]
Whenever I set up a trailer to empty my combine, it goes to get filled up, and then it just sits at the start of the unload route with "No combine in reach / Waiting for fill point to be reached" until the combine requests a driver again, only then will it actually start moving to the unload area.

Shouldn't it just go unload immediately once it gets filled past its "drive on at" percentage (90% in my case)?

**Comment by pvajko** [comment]
Do you have pathfinding turned on? Could you check if it is the same with pathfinding turned off?

**Comment by Sokonomi** [comment]
That indeed fixed it, but I had to turn off the crop destruction mod (not your problem obviously).
 
Would be cool if those guys could script it so it recognizes courseplay drivers, so that they wont wreck the crop, only the player themselves would.

**Comment by pops64** [comment]
CP automatically turns off crop destruction if it is running.

**Comment by pvajko** [comment]
Original problem seems to be fixed.
