### ISSUE TITLE
Suggestion: seeding without fertilizer

### ISSUE THREAD

**Issue by arkydave** [Courseplay/courseplay#2217]
Allow me to select whether or not I want to check for fertilizer empty when seeding. I would sometimes like to use my fertilizer-capable seeder without fertilizer, but CP insists that I fill the fertilizer.

**Comment by pops64** [comment]
Use pro seed mod has this allows you to do just that. You still have to put a little bit of fertilizer in it but it won't use it. Closed to keep the issues area clean and we aren't currently taking suggestions until CP is released.

**Comment by kbrandwijk** [comment]
Could this be reopened, as this is still an issue in the latest version? It's not a suggestion imho, I can seed without fertilizer manually, and using the helper, but CP insists on filling (and using) the fertilizer. I really shouldn't need another mod to care of that.
