### ISSUE TITLE
Unload several trailers truck

### ISSUE THREAD

**Issue by o0Kyoshou0o** [Courseplay/courseplay#2219]
hi everyone,
i have a problem with the Mode 1 "load at start" with one truck and several trailers. when the truck go to unload trigger,  the secondary trailer do not clear and CP stay on trigger reached (see the last picture with the red square).
i have do debug mode on 1,2 and 19, see the attached log
there are several pictures that showed the problem.
[log.txt](https://github.com/Courseplay/courseplay/files/1202701/log.txt)
![20170805233226_1](https://user-images.githubusercontent.com/30392058/28998988-d4305456-7a38-11e7-9fb4-9011e7ce7191.jpg)
![20170805233229_1](https://user-images.githubusercontent.com/30392058/28998989-d6f681ba-7a38-11e7-85c7-0da616abace5.jpg)
![20170805233305_1](https://user-images.githubusercontent.com/30392058/28998991-dd007e80-7a38-11e7-908e-a054aebe3a59.jpg)
![2017-08-05_23-53-18](https://user-images.githubusercontent.com/30392058/28999006-60e2456c-7a39-11e7-97c5-c52497c46bf7.png)

Regards,
Kyoshou

**Comment by Blackmankot** [comment]
@o0Kyoshou0o  I have long described this problem. # 2077 I have everything the same way. And if you are not in the transport during unloading, the unloading will be completed correctly.

**Comment by Blackmankot** [comment]
@pops64  The duplicating question.

**Comment by pops64** [comment]
It's is different from yours in that the second trailer never unloads. Unless yours is doing this as well

**Comment by o0Kyoshou0o** [comment]
hi,
thx @Blackmankot, i did not see this issue. i have tested and you are right. 
sorry @pops64 for this useless issue. i will search more effectively in the future.
kyoshou

**Comment by Blackmankot** [comment]
@o0Kyoshou0o  Hey. It happens. Thank you for participating!
