### ISSUE TITLE
switching sides 

### ISSUE THREAD

**Issue by willie2016** [Courseplay/courseplay#2220]
![farmingsimulator2017game 2017-08-07 00-57-21-187](https://user-images.githubusercontent.com/24280974/29048323-e14d1026-7bc7-11e7-8af9-9485f9d7c535.jpg)
is there anyway i can get the tractor and trailer to stay at the left side of forager all the time while picking grass swaths like they do it in ireland in real life ? if i select left on forager then the tractor and trailer will go to the right at the start of the swath but then it will try cutting across the front of the forager too get to the left side

**Comment by pops64** [comment]
You already reported this bug ... We will fix it when we get to it. #2154
