### ISSUE TITLE
issue with the installing

### ISSUE THREAD

**Issue by dontreallyknow** [Courseplay/courseplay#2221]
Hi I downloaded courseplay from here and followed the steps but the mod shows as installed into the game but when i have the start screen of a savegame where you can choose your mods it doesn't shows there what can i do?

**Comment by Blackmankot** [comment]
Good day. You did not properly pack the archive.

**Comment by lcc1211** [comment]
There is a simple tool I've been using for months that not only checks for an updated version, but also installs it for me.  Just don't run it while FS17 is playing.  https://github.com/elpatron68/cpupdate/releases

**Comment by pops64** [comment]
Yes re-follow the steps to install. Find a you tube video out there as well closed to keep issues area clean
