### ISSUE TITLE
Suggestion for crop destruction when fertilizing (create tram lines)

### ISSUE THREAD

**Issue by pseikoNL** [Courseplay/courseplay#2222]
I know that at this point you're busy with finishing the beta, but is it possible that after beta is released, you integrate an option to enable & disable crop destruction at growth level 3 and higher for vehicles who do fertilizing spreading & liquid fert. spraying on the fields, this then create wheellanes/tramlines and make it more realistic.

Take a look at https://github.com/DeckerMMIV/FarmSim_Mod_WheelLanes , maybe you can/may use his code for it to implement such an option in CP.

**Comment by pops64** [comment]
It is currently hard coded to turn off Corp dustruction if the mod is present when CP  is driving but for now closed until we release
