### ISSUE TITLE
Reverse driving

### ISSUE THREAD

**Issue by OldFamous** [Courseplay/courseplay#2223]
Hello,

I play on the "belgique profonde map".  (http://www.fsmods17.com/belgique-profonde-map-fs17/)
Iam now harvesting my grain's and I used to bring the grain to my farm.
The thrick is that I need to drive backwards to the tip trigger.
Normally its working great, but since a while I had problems with the "gillibert pro tipper" (http://www.fsmods17.com/gilibert-1800-pro-v-0-9-fs17/) 
But I discoverd that courseplay "see's" the tipper as an overloader.
It's not a big problem cause I allready found a new tipper wich I like more.

Now Im talking about the "Rolland rollspeed tipper" (https://fs17.lt/rolland-rollspeed-tippers-pack-v-1-1/)
But now the tractor with the tipper will not back up nice and steady anymore?
It looks like that courseplay see's more trigger's? (I took a look in Giants editor, but there's just one trigger). First the tractor back up's straight but then it makes a 90 degree's turn? 

I tried to make a few "new" course's. I now got a course that's working almost, just maybe 0.2 m before the trigger courseplay makes the 90 degree's turn, so the tipper is tipping beside's the trigger but my silo ammount is counting so Im almost happy. :P

If you need more information I will try to give you as much you need:)
I'm using V5.01.00178.dev

Kindly regards,

Hendrik Ernst

**Comment by pops64** [comment]
This sounds like the mod has a node that CP uses not in the way it is expecting. May or may not be fixable

**Comment by OldFamous** [comment]
Goodmorning,

I tried to find out my self what is going wrong,
Now when I Enable debug channel 13 my log is telling me that's a pivot trailer, Im very sure it isn't 🤣 
I also discoverd a few weeks back that Pivot trailer's not backing up straight in bfp2, thats not a problem cause I don't use pivot trailers normally.

Now is my question how does courseplay reconize if the trailer is a normal trailer or a pivot trailer?
Maybe if I can change something to my trailer so courseplay isnt thinking thats a pivot trailer?

Thank you for your help.

Hendrik Ernst

**Comment by pops64** [comment]
Yea that is the problem then. If I remember correctly it is fixable but will have to look into it.

**Comment by pops64** [comment]
Collapsing mod issues into a single thread. #2231
