### ISSUE TITLE
Not an issue - looking for information

### ISSUE THREAD

**Issue by willie2016** [Courseplay/courseplay#2224]
i made a post lastnight about having tractor and trailer stay on the left side of forager while picking grass swaths , it seems to be gone now im just wondering who removed it and did you leave a responce because i didnt see reponce , sorry for any inconvenience

**Comment by pops64** [comment]
Yes, I did. And I told you that you had already reported it we don't need duplicate issues. We will fix it when we can. There is no way around it until we do. Closed to keep issues area clean

**Comment by willie2016** [comment]
ok i just didnt see why it was removed , thanks for responce
