### ISSUE TITLE
Holmer Terra Felis 2 eco

### ISSUE THREAD

**Issue by saku05** [Courseplay/courseplay#2225]
Hello everyone
Question
Does the Holmer Terra felis 2 work with Courseplay?
If ok, how to do it.
Thank you

**Comment by Blackmankot** [comment]
Is it a harvester for beet harvesting?

**Comment by dkfiremann** [comment]
That is the one for picking up beets from a heap on the ground. 

I have used it, but never with CoursePlay. 
Don't think it will work, as it is a very special mashine.

**Comment by Blackmankot** [comment]
I agree, I also do not represent his work with the course.

**Comment by saku05** [comment]
Probably with a start at the beginning of the course, a P at the beginning of the heap and a stop at the end of the heap
A tractor with mode 2 for unloading.

**Comment by Blackmankot** [comment]
Check and we will tell!

**Comment by saku05** [comment]
#
