### ISSUE TITLE
Game Freeze when Harvester is select

### ISSUE THREAD

**Issue by Stolli1996** [Courseplay/courseplay#2226]
Hi

I have the problem that my game freeze when a Driver will drive to a harvester. Its only by the holmer terra dos t4_30 Its in mode 2 and 3. In the moment where the homer appears in the hud as selected combine the game freeze. 
the newest version of Courseplay is installed.

I need please help. I will finish my sugarbeet harvest

**Comment by pvajko** [comment]
Can you post a full log with debug channels 3, 4, 7 and 9 active?

**Comment by Stolli1996** [comment]
here the log with the debugg channels.
i have test it with orginal tractors and harvesters and there is the same.
But its only with this savegame when i start a new one there i haven't this problem.

[log.txt](https://github.com/Courseplay/courseplay/files/1212721/log.txt)

**Comment by pvajko** [comment]
Seems to be similar to #2206, the weird thing is that the version you are using has a limit in the algorithm so it should actually stop searching for a path after a short while. Is it really hanging forever? How long have you been waiting?

Also, which map is this? 

Are you familiar with using the console in the game? Could you do a 'cpSaveAllFields' command? That will create a cpFields.xml file under CoursePlay_Courses/<name depending on whatever map you are using>, I would need that file.

**Comment by Stolli1996** [comment]
Hello
Sorry for the late answer, But im on holyday now.
I give You a netter discription on tuesday. Thema im back. 
But the map is the südthüringen 4x Fach 
The first time in have wait 5 min and the Harvester is drive for Show time sometimes But no gaming 
This with the XML ist will Do on tuesday

**Comment by Walpe** [comment]
hi,

Sorry for the double post, it was not intentional, I did not want to interfere with the information transmitted in another post.

Here are the logs with the channel 3,4,7 and 9 active as well as the file cpFields.xml.

[log.txt](https://github.com/Courseplay/courseplay/files/1220115/log.txt)
[cpFields.zip](https://github.com/Courseplay/courseplay/files/1220118/cpFields.zip)

This is the first time I use the runplay debug system, so tell me if you miss something.

**Comment by pvajko** [comment]
Great, thanks, one more question: how much fruit was on the field when this happened? Like first few headland lanes harvested? Or working on up/down lanes already?

**Comment by Stolli1996** [comment]
My Harvester were on the headland lanes 
But then I have test it with the Normal heller with up down lanes and There is the same problem

**Comment by Walpe** [comment]
Yes my forage harvester is on the first two headland lanes of the field.

**Comment by AgroWillem** [comment]
Somewhat same problem here. CP .0180
Game (and Windows) freezes when the harvestes reaches its turning point.
Using a big map also: MavericksV2Seasons Field 2
[log.txt](https://github.com/Courseplay/courseplay/files/1224448/log.txt)

I am mowing at relative high speed (25km/h). When i reduce mowing speed to say 10km/h it the freezing sometimes does not happen. But this takes lots of time for the big fields.

**Comment by pops64** [comment]
Try with and without pathfinding. If it doesn't go away with pathfinding off then you have a completely separate issue

**Comment by pvajko** [comment]
I have a fix for it but there's not much internet where I am right now so it may take a day or two.

-------- Original message --------

**Comment by AgroWillem** [comment]
@pops64 I use the modded mower as long as FS17 is out now and with CP from the beginning. On very big US-maps i was racing with it at 30km/h with no problems at all. 
But i am gonna try the standard one and let you know.

How do i switch off and on pathfinding in CP?

@pvajko a fix for what?

**Comment by Stolli1996** [comment]
Hello 

here is my cpfields.xml

[cpFields.txt](https://github.com/Courseplay/courseplay/files/1225960/cpFields.txt)

**Comment by Stolli1996** [comment]
Tank you very much @pvajko 
I have test it and the problem is fixed. 
so closed

**Comment by Walpe** [comment]
Thank's so much, it's work perfectly.

**Comment by AgroWillem** [comment]
Yep. Problem solved! Great work. ;)
