### ISSUE TITLE
Online

### ISSUE THREAD

**Issue by HardCoreBoy** [Courseplay/courseplay#2228]
ist es möglich den CoursePlay auch MP fähig und vorallem DEDI-Server fähig machen zu können ?

MFG =)

**Comment by pops64** [comment]
Been stated multiple times. Multiplayer won't even be considered until after CP has been released.

**Comment by HardCoreBoy** [comment]
Darf man wissen warum es kein MP und DEDI geeigneten coursePlay geben wird ??

MFG
________________________________
Von: pops64 <notifications@github.com>
Gesendet: Freitag, 11. August 2017 20:50
An: Courseplay/courseplay
Cc: HardCoreBoy; Author
Betreff: Re: [Courseplay/courseplay] Online (#2228)


Been stated multiple times. Multiplayer won't even be considered until after CP has been released.
