### ISSUE TITLE
Sauzahn 500

### ISSUE THREAD

**Issue by Fendtfan84** [Courseplay/courseplay#2229]
It was very nice when this mod plow became a CP support.
This is a link for the Mod on Modhoster:
https://www.modhoster.de/mods/fieldstar-sauzahn-500

**Comment by pops64** [comment]
What is wrong with it?

**Comment by Fendtfan84** [comment]
CP recognizes this mod not as plow.
The CP helper drive at the Start point around and unfold the plow.
Best regards 
Fendt Fan

**Comment by pops64** [comment]
That makes no sense. Has that is what CP I suppose todo

**Comment by Fendtfan84** [comment]
Thats a link for my log [https://gist.github.com/Fendtfan84/045e648d21c66175cf5fb6dc7864203c](url)
That is the link for the Scrennshot [https://abload.de/img/fsscreen_2017_08_13_1myjqs.png](url)
Tha Problem with this Plow is CP recognizes this not as plow and dont unfold the plow.

**Comment by pops64** [comment]
Collapsing mod issues into one thread #2231
