### ISSUE TITLE
Mode 2: freezes when the forage harvester is selected

### ISSUE THREAD

**Issue by Walpe** [Courseplay/courseplay#2230]
Hi,

I have a problem with mode 2 when the tractor goes to the forage harvester and when the tractor leaves to go to empty his trailer. Indeed the game freezes for about ten seconds each time and for the three tractors that I use.

I tried different version of the raceplay: the .169, the .177 and the .178 currently.
I play on the Loesshuegelland card in version 4.1 which is an x4 card.
The forage harvester is a ROSTSELMASH RSM 1403.
I also tried with the Krone Big X 580 and tried with a new small course for the tractors, but it didn't solve anything.

I tried the 'cpSaveAllFields' command because I saw, on the previous problems, that another person had less freezing thanks to this command but this didn't solve my problem.

Can you help me ?

Best regards, Walpe

**Comment by pops64** [comment]
#2226.

**Comment by pvajko** [comment]
The cpSaveAllFields is not to solve the problem, it is to create an XML file containing the fields for debugging purposes. Follow the instructions in #2226 and post the full log and cpFields.xml in #2226.
