### ISSUE TITLE
tractor blocked

### ISSUE THREAD

**Issue by thomasglavesb** [Courseplay/courseplay#2245]
Dear Friends,

I have a problem with courseplay. If for some reason if I stop a route, when starting it again the tractor is blocked. The driver disappears and I can not do anything else with the tractor. Please help.

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Blackmankot** [comment]
The problem is in modes, look for the wrong mod.

**Comment by pops64** [comment]
Closed due to incomplete bug report will reopen if a response is given
