### ISSUE TITLE
Tipper doesn't add enough straight distance when turning with forager.(Long Tipper)

### ISSUE THREAD

**Issue by Nielsen362** [Courseplay/courseplay#2246]
Hi 
When i use the forageharvester, i use trucks and trailers to drive beside it, but with this new turn you made, it is going all wrong when the truck try to reverse back to the forage harvester on the headland.
Hope there is a fix for this
Thanks in advance
Nielsen

![fsscreen_2017_08_19_12_44_07](https://user-images.githubusercontent.com/25202637/29485986-6e02a748-84dc-11e7-86a8-96b496b8a468.png)
![fsscreen_2017_08_19_12_44_14](https://user-images.githubusercontent.com/25202637/29485990-6e05df08-84dc-11e7-8f44-4ac76e9e9f73.png)
![fsscreen_2017_08_19_12_44_19](https://user-images.githubusercontent.com/25202637/29485988-6e056cf8-84dc-11e7-81bc-9c07474c7782.png)
![fsscreen_2017_08_19_12_44_21](https://user-images.githubusercontent.com/25202637/29485989-6e05b3f2-84dc-11e7-800b-36bd181b1eb4.png)
Here it starts reversing, but it is not lined op
![fsscreen_2017_08_19_12_44_25](https://user-images.githubusercontent.com/25202637/29485987-6e051cda-84dc-11e7-9164-7513f03c106d.png)
![fsscreen_2017_08_19_12_44_27](https://user-images.githubusercontent.com/25202637/29485991-6e071f8a-84dc-11e7-910e-482407ffcf45.png)
![fsscreen_2017_08_19_12_44_29](https://user-images.githubusercontent.com/25202637/29485996-6e1d9346-84dc-11e7-9f3c-2821ceb652be.png)
![fsscreen_2017_08_19_12_44_30](https://user-images.githubusercontent.com/25202637/29485992-6e1a9d44-84dc-11e7-81ca-cba9f02d7e09.png)
![fsscreen_2017_08_19_12_44_33](https://user-images.githubusercontent.com/25202637/29485993-6e1ae81c-84dc-11e7-8b2f-9c5322264e26.png)
![fsscreen_2017_08_19_12_44_36](https://user-images.githubusercontent.com/25202637/29485995-6e1c657a-84dc-11e7-987f-b6eefcdbd164.png)
![fsscreen_2017_08_19_12_44_38](https://user-images.githubusercontent.com/25202637/29485994-6e1b7db8-84dc-11e7-845c-c2c96785c649.png)
![fsscreen_2017_08_19_12_44_41](https://user-images.githubusercontent.com/25202637/29485997-6e1e14ce-84dc-11e7-9d66-96ff515bcf9a.png)
![fsscreen_2017_08_19_12_44_45](https://user-images.githubusercontent.com/25202637/29485998-6e3188b0-84dc-11e7-84a9-04191a22363f.png)
![fsscreen_2017_08_19_12_44_49](https://user-images.githubusercontent.com/25202637/29485999-6e33c3f0-84dc-11e7-895d-732e74f35df6.png)

 
[log.txt](https://github.com/Courseplay/courseplay/files/1236268/log.txt)

**Comment by pops64** [comment]
Did try this with similar length vanilla truck and trailer?

**Comment by Nielsen362** [comment]
No i did not, but i can do it. I tryed with 2 different mod trucks same result

**Comment by Nielsen362** [comment]
I have now tried with vanilla truck and trailer, it is with the same result

**Comment by pops64** [comment]
Just wanted to double check it wasn't something related to a mod incompatibly

**Comment by pvajko** [comment]
TX 415 Barrelcore (#1): reverse course is not valid message in the log.

**Comment by pops64** [comment]
That would cause this but the fine tunning is still a valid point it should be more straight than  what it is in picture 3

**Comment by nyfarmboy07** [comment]
I'm just wondering if there could be a menu choice for circle type turn maneuver or straight line reversing? 
It seems to be in the older versions where the tippers performed a circle to line up to the harvester was much more reliable.

**Comment by pops64** [comment]
They didn't perform a circle turn. They went to point x and waited for harvester to turn then when to harvester. And it was horribly unreliable it took the space of two football fields for it to work correctly 100% of the time.

**Comment by pops64** [comment]
Try again with version 199 or higher

**Comment by Nielsen362** [comment]
Working just perfect, nice work

**Comment by pops64** [comment]
Thanks. Closed
