### ISSUE TITLE
Bunker mode not selecting leveler height correctly

### ISSUE THREAD

**Issue by Daerkannon** [Courseplay/courseplay#2247]
Issue: Tractor always chooses the highest possible setting for the leveling blade.  I have seen this behaviour other times, but restarting the course usually works.  In this case with this tractor it's 100% of the time.  I have run this same course without issue with a Puma & Valtra S and with T9 and Case Quadtrac with only the usual issues with articulated tractors.

Tractor: MT800E
Leveler: MES 500
Map: Mustang Valley Ranch
Bunker mode settings:
filling up
just courseplayers
60m
6.5m
20kph

**Comment by pops64** [comment]
#1997
