### ISSUE TITLE
Courseplay stops before my headland,lifts disc and turns

### ISSUE THREAD

**Issue by KJ145** [Courseplay/courseplay#2248]
I do 2 rounds of headland first the tractor switches to cross ways,it stops a tractor length for the headland picks up disc and turns.....itll back up to meet headland and drop disc only to stop short again. I have turn on field shut off and a turn radius of 12 meter

**Comment by pops64** [comment]
Name of mods being used

**Comment by KJ145** [comment]
john deere 9r kmn moddings beta aem and linbergs 2623 pack off modhoster

**Comment by pops64** [comment]
Link thanks

**Comment by KJ145** [comment]
http://americaneaglesmodding.com/index.php?action=downloads;sa=view;id=1575

https://www.modhoster.de/mods/john-deere-2623-disc-pack

**Comment by KJ145** [comment]
tank u pops64 for the reply

**Comment by KJ145** [comment]
http://americaneaglesmodding.com/index.php?action=downloads;sa=view;id=1575

https://www.modhoster.de/mods/john-deere-2623-disc-pack

**Comment by pops64** [comment]
Closed collapsing mod issues into one thread #2231
