### ISSUE TITLE
ITS Lemken Dolomit

### ISSUE THREAD

**Issue by Fendtfan84** [Courseplay/courseplay#2249]
I Have with this Mod log errors with CP.
This is a link for the mod:
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=63185&title=fs2017
This is a link for my log:
https://gist.github.com/Fendtfan84/7325fc7d02cbe8a70ea811b7819a1e3f

**Comment by pops64** [comment]
#2236
