### ISSUE TITLE
Bug causing CP freeze

### ISSUE THREAD

**Issue by ghettohawk17** [Courseplay/courseplay#2250]
When you stop the course for a overloader and start it again,it doenst say waiting til fill level,its blank, the tractor starts driving and then the game crashes.

The game still works, but you cant tab, Esc, you can exit the tractor, but you cant move, It needs to be fix, it sucks

**Comment by ghettohawk17** [comment]
The game still works, but you cant tab, Esc, you can exit the tractor, but you cant move, It needs to be fix, it sucks

**Comment by pops64** [comment]
Please make proper and complete bug reports. https://github.com/Courseplay/courseplay/wiki

**Comment by pops64** [comment]
Closed improper bug repot
