### ISSUE TITLE
Missing Pop Up on refill course Holding Point

### ISSUE THREAD

**Issue by pizman** [Courseplay/courseplay#2251]
Hi.
This is not realy a issue.... more a missing feature thats verry usefull i think.
Sorry for long text.. i just try to explane exactly !

Basicly the Refill Function ( Combine 2nd course)  on Seed and Fertilize Courses workes fine....  But Only if the Trigger of the Refilling Point is seen by CP....   Like Big packs nearby the Course....   CP will stop there and refill the machine !  Same with the placed Seeds/Fertilizer Buy Stations. thats work fine, too.

But if we use a MOD as filling Point ( For example a Seed Silo with factory script) then CP in most Mods not "see" the trigger and drive by....    BUT Here you still help us and give us the "Holding Point" in the Course... So CP can handle this too. ( Only  if the trigger got a Automatic Filling.... If we need to start it with a button, or choose from a menue list then we got again the Problem i explane below)

Realy problematic is a Seeding machine that include fertilizer, too like the big Amazone !   If i use 2  different loading points i would need to make 2 Stop Points but thats not possible i think.
**NOTE.   I NOT ask you to fix THIS!  Current Logic is ok, i think !**

_I still like 100% Full automatic CP Courses....  But it´s ok for me to controll for example the filling trigger by myself, or  if i use a overloader (manualy) that fill the machine.....  So aslong CP drive to the Loading Area and back to the field its ok for me to do the "loading work" by myself"_

**MY PROBLEM !!**
I NOT get informed by CP when this happens.....    
For Example:
I generate a seeding Course for field x and combine it with a refilling course that drive my machine from field to Refilling area with a HOLD Point there.....  and back to the field. ( No Automatic filling at the hold point so i will fill my machine by hand) 
When i now start CP  then the CP Helper will work until the seed is empty....  Then he drives to the Refill Area and hold on the holding Point. 
AND NOW:   He will stand there forever....  Until i load him again.    BUT.  I get no notification that he is waiting there !    If i work on another spot for example it can take long time until i see that field X never been finished and i realise the helper is still waiting on the Refill Area since 2 Hours of playing time .

My Request.

Can you add here a simply notification in Green, Blue or Red like you already use for other situations ?
If a course is finished we get in green " Vehicle Xy has finsihed work"
Or like Red Notification if a vehicle is low of fuel.

So i think we need a Infobox like "  vehicle xyz Waiting at Loading Point"   

If Possible you can think about a internal "timer", too.    When the Notification comes direct at reaching the holding Point then it will shown even if there is still a automatic refilling in progress, too.
If possible the Aleart should only come active  if the CP Helper is waiting for example longer then 2 Minutes on the holding point or maby if CP see that the fill level not increase since 2 Minutes.
( Additional to my situation this information will be helpfull, too when on a full automatic course a refill is not possible cause the filling poiont itself is empty )

Thank you guys for this nice Mod.  Without CP  FS17 is not playable.     
I Hope this idea is usefull for you !

**Comment by pops64** [comment]
I know a work around that I haven't tried is to use a augur wagon in mode 1. Which should be able to load seed or fertilizer and then stop at a unload point using a waitpoint. At which time the mode 4 driver comes up and stops at a different waitpoint for loading. Sort of like how mode 3 works. This should run until the silo is empty which you should receive a notification for that

**Comment by pizman** [comment]
Hi Pops64
Thanks for Reply.
I still know the technic with the augur wagon....   But the Problem is the same...   CP not "see" the Augur wagon.   If i use a Holdpoint int the Mode 4 Course then the CP Helper stops THERE and need to be filed with Seed AND Fertilizer .   In that way on the Mode 1 Augur Wagon there must be TWO Wagons (one with Fertilizer and one with Seed) ....    Even not Possible !

ADDITIONAL INFO.
Maby the Bug in my version is another....   I See i get no notifiction for Combines, too.
In Standard FS17 Helper Mode i get a Info when Corntank is full !    In CP Helper Mode "Fieldwork" my Combine stop working when tank is 100%  BUT i get no notificaton !

If possible please check this !

**Comment by pops64** [comment]
There is no notification for that. You can download proseed mod which will let you turn off the fertilizer function so if you leave it full of fertilizer you won't need a second waypoint or aurgur wagon

**Comment by pizman** [comment]
Again Thank you To "pops64" for your Email
THIS was the final solution,
With the AddOn ProSeed it is possible to disable the Fertilizer Mode of the machine.   Without using fertilizer it is never empty and the machine is usable like a Seed Only Machine.
( I don´t like the Dual Seeding Machines at all,  but i used them cause they are the largest width)
So.... Not a perfect solution... But 100% Working for me !

**Finaly my request is still actual.**    Please if possible implement "Notes" for this two situations.   If a user (like me) make a Refilling Course for example with a manure wagon that should be filled manual with a tractor (I Drive myself ) then a INFO of Coursplay that Vehicle reach filling Point is HIGHLY needed.
Same with the full Corn Tank..    If I Not use Mode 2, 3 or 7 and i like to reload the Combine manualy i need a INFO if Tank is full, too. 

Thank You !

**Comment by pops64** [comment]
Yea I think the grain tank full message is bugged.  The message popups are doable. The 2 wait points in mode 4 will require more investigation which won't be until after release.

**Comment by pops64** [comment]
Closed #2909
