### ISSUE TITLE
Mode 2 Wait Infinitely when selecting side forage havester

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#2253]
When changing which side the currently assigned tipper uses the currently assigned tipper just stops and says it is awaiting a new way point. Both path finding on and off.
![farming simulator 17 8_25_2017 19_39_03](https://user-images.githubusercontent.com/10678220/29737583-fa01ebde-89d5-11e7-9b58-3d3e5c14e942.png)

**Comment by pvajko** [comment]
Please post your courses and savegame, see the last point in https://github.com/Courseplay/courseplay/wiki for instructions.

**Comment by pops64** [comment]
Easily Reproducible. Just need forage harvester and tipper and then select which side you want will cause the desired bug
