### ISSUE TITLE
AIvehicle extension

### ISSUE THREAD

**Issue by willie2016** [Courseplay/courseplay#2255]
Does anybody have issues with AIvehicle extension and courseplay ? mine goes crazy sometimes the tractors just go around in circles

**Comment by pops64** [comment]
You have make sure you are running the latest beta version of AIVE. I know the release version of AIVE does not support CP

**Comment by pops64** [comment]
Just ran a few test a no problems detected see #2231

**Comment by willie2016** [comment]
so where can i get the latest version of AIVE ?

**Comment by pops64** [comment]
See #2231
