### ISSUE TITLE
Issue with course generator

### ISSUE THREAD

**Issue by kylemeyer13** [Courseplay/courseplay#2256]
not sure if this has been addressed but i am having issues generating courses in odd shaped fields. When i generate the course it generates the headlands ok but when the straight passes are generated they leave the field. 
![fsscreen_2017_08_26_18_40_02](https://user-images.githubusercontent.com/26012725/29746021-e7ce1c14-8a91-11e7-84f1-8af9d9f55681.png)
![fsscreen_2017_08_26_18_41_19](https://user-images.githubusercontent.com/26012725/29746022-e7d1a550-8a91-11e7-9b8e-d8b2ead47194.png)

**Comment by pvajko** [comment]
Select 'Current vehicle location' as the starting location, that will use the new course generator algorithm which can handle these fields.
