### ISSUE TITLE
Stopping CP Course causes engine to rev up to 10,000 RPM since 'MR FIX'

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#2257]
This is an old issue that has now come up again since the latest update of the 'more realistic fix'.   Stopping a CP course causes the engine to rev up to crazy rpms and exhaust shoots out of the pipe for 30 seconds or so until the engine winds down.

**Comment by pops64** [comment]
#2231 It is not something we can fix cause I honestly don't know what would cause that. Sounds like something wrong with MR when the transmission re-engages
