### ISSUE TITLE
Upper Mississippi River Valley

### ISSUE THREAD

**Issue by wijba** [Courseplay/courseplay#2258]
In UMRV I got the following error:

Warning (LUA): 'getWorldTranslation': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
LUA call stack:
  =E:/Downloads/FS17/Playing Maps/modsUMRV/ZZZ_CoursePlay/distance.lua (43) : getWorldTranslation
  =E:/Downloads/FS17/Playing Maps/modsUMRV/ZZZ_CoursePlay/triggers.lua (970) : nodeToNodeDistance
  dataS/scripts/objects/BunkerSilo.lua (24) : load
Warning (LUA): 'getWorldTranslation': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
LUA call stack:
  =E:/Downloads/FS17/Playing Maps/modsUMRV/ZZZ_CoursePlay/distance.lua (44) : getWorldTranslation
  =E:/Downloads/FS17/Playing Maps/modsUMRV/ZZZ_CoursePlay/triggers.lua (970) : nodeToNodeDistance
  dataS/scripts/objects/BunkerSilo.lua (24) : load
Error: Running LUA method 'BunkerSilo.onCreate'.
E:/Downloads/FS17/Playing Maps/modsUMRV/ZZZ_CoursePlay/distance.lua:45: attempt to perform arithmetic on local 'x2' (a nil value)
Warning: BunkerSilo, could not resolve attribute 'bunkerSiloArea' into a valid node!
Warning (LUA): 'getWorldTranslation': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
LUA call stack:
  =E:/Downloads/FS17/Playing Maps/modsUMRV/ZZZ_CoursePlay/distance.lua (43) : getWorldTranslation
  =E:/Downloads/FS17/Playing Maps/modsUMRV/ZZZ_CoursePlay/triggers.lua (970) : nodeToNodeDistance
  dataS/scripts/objects/BunkerSilo.lua (24) : load
Warning (LUA): 'getWorldTranslation': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
LUA call stack:
  =E:/Downloads/FS17/Playing Maps/modsUMRV/ZZZ_CoursePlay/distance.lua (44) : getWorldTranslation
  =E:/Downloads/FS17/Playing Maps/modsUMRV/ZZZ_CoursePlay/triggers.lua (970) : nodeToNodeDistance
  dataS/scripts/objects/BunkerSilo.lua (24) : load
Error: Running LUA method 'BunkerSilo.onCreate'.
E:/Downloads/FS17/Playing Maps/modsUMRV/ZZZ_CoursePlay/distance.lua:45: attempt to perform arithmetic on local 'x2' (a nil value)

Any idea what can cause this error?

GTZ Wijnand

**Comment by pops64** [comment]
E:/Downloads/FS17/Playing Maps/modsUMRV/ZZZ_CoursePlay really?  Should be C:/Users/****/Documents/My Games/FarmingSimulator2017/mods/FS17_Courseplay5 https://courseplay.github.io/courseplay/en/installation/index.html
