### ISSUE TITLE
BGA leveling/compacting mode detecting vehicles with engine stopped as running

### ISSUE THREAD

**Issue by dieselfuelonly** [Courseplay/courseplay#2263]
Version 5.01.00185

Tractors working the BGA silo seem to be detecting vehicles with stopped engines within their detection range as running.  Issue appeared with a front end loader parked nearby with the engine off - tractor would proceed to waiting location and wait indefinitely.  Also reproduced with a road tractor driving into the detection range with a loaded trailer, unloading, and then parking within the detection range and shutting down the engine - same behavior as with the FEL.

**Comment by pops64** [comment]
Inactivity. If still occurring please post new issue
