### ISSUE TITLE
Overloaders Fail to Unload

### ISSUE THREAD

**Issue by SJSMinnesota** [Courseplay/courseplay#2264]
Hello,
No matter the Overloader nor the trailor the overload arrives but wukk not unload, I must stop the driver and use the manual "R" unload button and the fruit is transfered. One the is done I send the overloader on its way awaiting it retun.
I have used both mod and non modded equipment.
I hope you can help.
Thanks

**Comment by pops64** [comment]
Follow https://courseplay.github.io/courseplay/en/manual/index.html#driveMode3 it is 90% correct. The other 10% is you have to make sure to have a pipe potion saved before using mode 3. If that doesn't work then follow https://github.com/Courseplay/courseplay/wiki

**Comment by Willykeen** [comment]
i can second this.
when using the "Manual Unloading" mod, overloaders, trucks, trailers etc will not unload.

**Comment by JDTiger** [comment]
Courseplay currently doesn't work with any manual unloading mods, wich do not turn themselves off if the tractor is courseplay-driven.

**Comment by pops64** [comment]
Assumed using this mod. closed out due to inactivity

**Comment by SJSMinnesota** [comment]
I am not using the Manual Unloading mod. Never have used it.

**Comment by SJSMinnesota** [comment]
I hope my help request will remain open.

**Comment by JDTiger** [comment]
Are you using the combine-addon mod from modhub? ->same function with manual unload

FS17 standart does not have a option to unload manually from chaserbins into trailers, it unloads as soon as the trailer is under the pipe.

**Comment by SJSMinnesota** [comment]
Yes I do have that mod. Is that the issue?

**Comment by JDTiger** [comment]
it HAS a manual overload function wich does not work with courseplay, disable it and courseplay will empty your overloaders

**Comment by SJSMinnesota** [comment]
I had no idea. I am disabling it now. 
I want to thank you very much for your help.
Take care.

**Comment by pops64** [comment]
#2231
