### ISSUE TITLE
Helper in fieldmode loses turnpoint when tractor has front and back implements

### ISSUE THREAD

**Issue by pvajko** [Courseplay/courseplay#2265]
Splitting #1878 : 

Thanks for referring to this one. I have tried again, with channels 12 and 14: [log.txt](https://github.com/Courseplay/courseplay/files/988148/log.txt)
This logfile contains two runs: One with 1 headland. This works fine. The second run is with 2 headlands and that one fails. 

Course generation settings:
![image](https://cloud.githubusercontent.com/assets/3243133/25874968/5c3730a4-3515-11e7-9987-6cdb13a050f8.png)

The Turn settings are: 
![image](https://cloud.githubusercontent.com/assets/3243133/25874982/707395b2-3515-11e7-981b-430f1e780acc.png)

I am playing the stock map Sosnovka and the field is nr 14.
Save: [savegame3.zip](https://github.com/Courseplay/courseplay/files/988163/savegame3.zip)
Courses: [CoursePlay_Courses.zip](https://github.com/Courseplay/courseplay/files/988165/CoursePlay_Courses.zip)

**Comment by pops64** [comment]
Closed #2909
