### ISSUE TITLE
MaxTurningRadius ModConflict

### ISSUE THREAD

**Issue by Willykeen** [Courseplay/courseplay#2266]
Game Keeps freezing after 5 or so minutes.
[log.txt](https://github.com/Courseplay/courseplay/files/1276548/log.txt)

**Comment by pvajko** [comment]
This looks like another vehicle mod missing the maxTurningRadius.

**Comment by Willykeen** [comment]
Could it be the windrower im using? Any way to fix?

**Comment by Willykeen** [comment]
I think its the windrower

**Comment by pops64** [comment]
There is any easy way to check disable the windrower and if you game stops freezing then it is your windrower. Full name of mod please and a clean link if you have it. The is no way to fix it that is way the Won't Fix tag is attached. It did not follow standard giants design methods when the mod was built.

**Comment by pops64** [comment]
Closed due to inactivity
