### ISSUE TITLE
course play 16x map and other 4x map

### ISSUE THREAD

**Issue by spectrum69** [Courseplay/courseplay#2267]
remember to remove all sub-folders from the file-play folder in the blibiotheque of fs17 otherwise the game will not be able to create a folder of the name of your map, if the latter requires a backup of the backup from 
screen under

https://image.noelshack.com/fichiers/2017/36/2/1504606640-bandicam-2017-09-04-10-41-31-909.jpg

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki
