### ISSUE TITLE
Unsuccessful translation.

### ISSUE THREAD

**Issue by Blackmankot** [Courseplay/courseplay#2268]
Hey. Unsuccessful translation. There was a "starting angle". In version 5.01.00186 "initial location". And now one text is superimposed on the following text.
![2017-09-07_11-50-07](https://user-images.githubusercontent.com/26131714/30146441-b4922894-93ca-11e7-9cd9-5e3e413af43a.jpg)
![2017-09-07_11-46-08](https://user-images.githubusercontent.com/26131714/30146449-c1c24490-93ca-11e7-9382-f21319819de8.jpg)

**Comment by pops64** [comment]
If you want you can edit the ru translation file. And fix and the make a push for it. Otherwise we don't handle tranlastion bugs our selves unless it is English or German

**Comment by Blackmankot** [comment]
I propose to change this wording to " Начальное расположение ". Understanding does not change.

**Comment by pops64** [comment]
Follow my original post. CP developers only support English and German translation files. Either talk to the person that manages the translation or do it yourself and then push it to us and we will fix it.

**Comment by Blackmankot** [comment]
Explain in more detail how to do this?
