### ISSUE TITLE
MF Pack by Blacksheep. Mode 2 bug

### ISSUE THREAD

**Issue by Blackmankot** [Courseplay/courseplay#2269]
This mod (any version of the CP) can not be found by any transport to go and start downloading.
![2017-09-07_12-59-39](https://user-images.githubusercontent.com/26131714/30147033-65453f84-93ce-11e7-9ef1-eb5e3dd2e880.jpg)
Link to mod: https://www.farming-simulator.com/mod.php?lang=en&country=ru&mod_id=81066&title=fs2017
![2017-09-07_12-57-24](https://user-images.githubusercontent.com/26131714/30147065-b79181c6-93ce-11e7-9c6c-46034baa5cf6.jpg)
![2017-09-07_13-06-12](https://user-images.githubusercontent.com/26131714/30147068-bd630b74-93ce-11e7-94b1-c90f0d11d554.jpg)

**Comment by pops64** [comment]
Please make titles clear when it is a known mod issue

**Comment by Blackmankot** [comment]
@pops64  Well, I'll try.

**Comment by Andy-Vertlib** [comment]
I noticed this problem too. But more - all attachable combines not work with truck\trailer in mode 2. I specially create my own attachable pickup from poettinger loader to check. My resulsts is interesting - transport don't work with all attachable combines. But I look for info about default poettinger Mex 5 in Courseplay scripts, and found it in "spetialTools". Then for check I rename xml on my combine to "poettingerMex5" and transport is start to work! 
I think this info is useful for this problem.
![fsscreen_2017_09_08_19_59_25](https://user-images.githubusercontent.com/31775370/30223368-46006ec2-94d3-11e7-989b-b7bf0626216f.png)

**Comment by pops64** [comment]
Merged into #2231
