### ISSUE TITLE
Size HUD СР.

### ISSUE THREAD

**Issue by Blackmankot** [Courseplay/courseplay#2270]
Sentence. This size of the windows in the game is convenient for everyone who has good eyesight. But it is not convenient proportionally small size of the HUD of the СP itself. Make choices in the settings: 1) The size of the HUD CP is proportional to the game windows; 2) The size of the HUD is large.
And everyone will be able to put a convenient HUD size for themselves.
![2017-09-07_14-31-22](https://user-images.githubusercontent.com/26131714/30149641-faf1bdf8-93da-11e7-9d46-f500aaa95222.jpg)
![2017-09-07_14-37-43](https://user-images.githubusercontent.com/26131714/30149658-05c9d65c-93db-11e7-8c1a-8dfa5acdaab5.jpg)

**Comment by pops64** [comment]
Delete your CP settings file this will reset any scalling that may have happen. Also you can adjust your in-game ui setting which will make your ui a bigger. And a belive there is a setting inside the CP setting file that lets you adjust just CP scales.

**Comment by Blackmankot** [comment]
@pops64  As I said before, I do not need a large interface in the game. But HUD CP is more convenient when it is large. But with each new version of the CP, changing the program code is not entirely convenient. And honestly, I do not know how to do it unfortunately. I hope for your understanding.

**Comment by pops64** [comment]
Settings file is in your save game file. It says CPsettings if I remeber correctly.

**Comment by Blackmankot** [comment]
I do not understand what is required of me. I did not find in my save file CPsettings.
You do not want to make my amendment?

**Comment by pops64** [comment]
In your savegame folder is a file called courseplaySettings.xml in there you will find a hudscale value. Follow the directions in there to adjust it. I believe it works but it is untested.

**Comment by Blackmankot** [comment]
Please enter the full path to the file - courseplaySettings.xml. 
What instructions are you talking about? Where are they?

**Comment by Blackmankot** [comment]
@pops64  Waiting for an answer from you.

**Comment by Gonimy-Vetrom** [comment]
c:\Users\xxx\Documents\My Games\FarmingSimulator2017\savegameX\courseplaySettings.xml
<courseplayHud posX="0.355729" posY="0.026852" **hudScale**="1.000000" **uiScale**="0.900000">

**Comment by Blackmankot** [comment]
@Gonimy-Vetrom Спасибо большое за помощь! я правильно понял, размеры самого Hud определяют  вот эти параметры hudScale="1.000000" uiScale="0.900000">. Первый размер по ширине, второй по высоте! Правильно!?

**Comment by pops64** [comment]
Closed. Has Gonimy-Vetrom answered the question Also try to keep things in English so other can follow along or help. If this setting does work for you and we will reopen this has a bug
