### ISSUE TITLE
Mode 10 - Abfahrhelfer schiebt die Silage nur auf eine Höhe weg

### ISSUE THREAD

**Issue by Lars-LS17** [Courseplay/courseplay#2274]
Hallo Zusammen,

ich bräuchte mal eure Hilfe. Aktuell habe ich das Problem, wenn ich den Kurs eingefahren habe, dass der Abfahrer immer nur ein paar Meter ins das Fahrsilo rein fährt und dann ablädt. Das Problem ist dann, dass die Silage bis am Rand liegt, sodass ich eine gerade Linie beim Fahrsilo habe. Wenn dies der Fall ist, dann bekommt der Abfahrhelfer im Modus 10 das Problem, dass der immer nur die selbe Richtung fährt um die Silage aufzuschütten. Er fährt nie mal ein paar Meter nach Links oder Rechts. Somit kriege ich Probleme, weil die Silage nicht mehr komplett weggeschoben wird. 

![fsscreen_2017_09_08_17_32_05](https://user-images.githubusercontent.com/31773176/30219679-19f19aa6-94bd-11e7-8d06-c5dadc431d9a.png)
![fsscreen_2017_09_08_17_31_17](https://user-images.githubusercontent.com/31773176/30219689-1ec2a1f6-94bd-11e7-938a-ec1f08702b5c.png)

**Comment by pops64** [comment]
Please try to post in English. Our support will be limited if this isn't possible.

**Comment by Lars-LS17** [comment]
I need your help. Actually I have the problem, when I have entered the course, that the CP driver always only a few meters into the drive silo goes in and then discharges. The problem is then that the silage is up to the edge, so I have a straight line at the driving silo. If this is the case, then the CP driver gets the problem in mode 10 that always runs the same direction to fill the silage. He never even drive a few meters to the left or right. So I get problems, because the silage is not pushed away completely.

Today i will send you my Log with debug Channel 2.

**Comment by Lars-LS17** [comment]
It was a Problem with the map.
