### ISSUE TITLE
combi mode dumps chaff outside BGA silo

### ISSUE THREAD

**Issue by aviator64** [Courseplay/courseplay#2276]
v5.01.00187

I have a course that transports chaff from the field to the BGA. When it arrives at the BGA, the tractor reverses into the silo and begins to unload as it should.

However, the tractor does not wait for the tipper to finish unloading, but immediately starts moving forward while unloading, this results in a long pile of chaff outside the silo.

The courses I have set up for other silos work correctly.

I have deleted and re-recorded the course a couple of times with no improvement.

This is the Westbridge Hills map. I have too many mods to list.

[log.txt](https://github.com/Courseplay/courseplay/files/1289467/log.txt)

**Comment by pops64** [comment]
You have to try with only vanilla equipment. On the same course. What is your distance to unload point set to? it should always be set to zero when first starting a course unless there is a pile already present. I can't rember if this was having a bug after unloading on reseting when it was a chaff harvester going to BGA. Picture of how you have your course setup

**Comment by aviator64** [comment]
I am using only non-mod equipment on this course.

Sorry, I don't know where to find or set "distance to unload point"

Here is a screen shot of course at BGA. Thank you!

![bga_course](https://user-images.githubusercontent.com/19857526/30239532-7cc3e1b0-952c-11e7-8341-7c9b16ee9c7b.jpeg)

**Comment by pops64** [comment]
Your last way point inside the bunker is to close to the edge. Please ensure you reverse at least half way into the bunker before switching back to forward.

**Comment by aviator64** [comment]
Thank you - the tip about reversing further into the bunker seems to have corrected the issue. I thought you only had to go back until you saw the "tip trigger reached" message.

Interestingly, that "Dist 2 unload point" option does not appear in the menu until the tractor has made at least one successful unload.

**Comment by pops64** [comment]
Yea bunkers need to be middle because CP doesn't tip at the edge of the trigger it goes in about 20 percent of the length of the bunker. If your dump point is short of that you will run into weird issues.

 Yea the value for dist 2 unload point if it is nil(reset state). It won't show. This value tells CP how far short to stop if it is tip anywhere so you don't run into the problem of dumping into a full heap. I can't remember how reliably it resets itself.

**Comment by aviator64** [comment]
Is there any documentation that explains the best way of setting up various types of courses? Just little things like reversing halfway into a bunker when recording a course would be helpful. Thanks!

**Comment by pops64** [comment]
http://courseplay.github.com/courseplay. It is 80% accurate. You tube is your friend in this case tho.
