### ISSUE TITLE
Tractor selects incorrect waypoint after turn

### ISSUE THREAD

**Issue by Nordvarg** [Courseplay/courseplay#2278]
Hi guys - First, let me tell you how impressed I am with all your hard work so far. Thanks 👍 

_Some facts:_
CP Version: 5.01.00187
Map: [Cherry Hills](https://drive.google.com/file/d/0B47G8R7CYpJ0OEhKbHlmY0pEODA/view) by Stevie
Equipment: In-game Quadtrac and Hatzenbichler sowing machine
Log: Posted [here](https://gist.github.com/Nordvarg/c49f5d12532e6a6a4f651e53632000c7)

I’m using multiple Hatzenbichlers to sow one field. I’m also using headlands. The course was created with an **earlier** version of CP.

The problem seems to occur when the tractor is starting sowing in a new, opposite direction, and when the last waypoint in the old direction is not on parallel with the first waypoint in the new direction.

1. It finishes the last waypoint in the old direction fine.
2. It finds the first waypoint – in the new direction (opposite) – without problem.
3. Now it is supposed to drive straight in the new direction. But…
4. Instead it makes a 360 degree turn before going where it supposed to.

Here’s a video:

[![CP Turning issue](https://img.youtube.com/vi/oM93KLzQ9vo/0.jpg)](https://youtu.be/oM93KLzQ9vo "CP Turning issue")

_When the last waypoint of a line is parallel with the first waypoint of the next line (in the opposite direction, the tractor drives as expected.)_

Thanks

**Comment by pops64** [comment]
Thanks for the video I see exactly what the problem is. When it finishes turning it select a way point behind the tractor instead of looking in front like it suppose to.  Could we get a save game and course for this? I don't think this would be reproducible.

**Comment by Nordvarg** [comment]
Thanks, **pops64** 👍 

You can download the files from [here](https://www.dropbox.com/s/o8wccbceqk5heen/Gamesave_CPCourses.zip?dl=0).

The course is: _F06/07 Sow 64m (4xHA)_  in folder _F06/F07_

Cheers

**Comment by pvajko** [comment]
Do you have a link for that Hatzenbichler mod?

**Comment by pops64** [comment]
It come from the big bud dlc. It should be reproducible with the course and same settings with out that tool

**Comment by pvajko** [comment]
Not so sure about that. @Nordvarg is it reproducible with a vanilla tool?

**Comment by Nordvarg** [comment]
I'll do a test :)

**Comment by Nordvarg** [comment]
Hi Guys

So, I’ve done some testing. First I tested the _Lemken Solitaire 12_, the _Amazone Condor 15001_ and the _Seed Hawk_ from the Big Bud DLC. All of them made the turn without issues.

Then, I tested the _Horsch Pronto 9SW_ mod (a FS15 convert on [Modhub](https://cdn11.giants-software.com/modHub/storage/00081470/iconBig.jpg)). This seeder also makes the tractor do an extra 360 turn.

Makes me wonder if the distance between the tractor and the actual sowing implement is a factor? Both the Hatzenbichler and the Pronto has the seed cart closest to the tractor.

Thanks :)

**Comment by pops64** [comment]
It is tool independent you just need to substitute in something of greater or equal length.

**Comment by pvajko** [comment]
@Nordvarg , excellent, can you upload a savegame with the tractor and that seeder on the field so we can easily reproduce this? Thx.

**Comment by Nordvarg** [comment]
Thanks, both @pops64 and @pvajko 

I’ve made a new gamesave, with Stevies map _(link is in first comment)_ and the Horsch Pronot as the only mods. You can download both the gamesave and the updated CP courses from [here](https://www.dropbox.com/s/4kdeppu7ptg02y6/CPCourses_gamesave_horsch.zip?dl=0).

The Courseplay course is named “**F07 Sow 64m**”.

_The tractor is driving as expected until leg 4, starting the 4th leg with an 360 turn._

Cheers

**Comment by pvajko** [comment]
Awesome. I can reproduce it now and see what the problem is.
