### ISSUE TITLE
Game freezing when harvesting chaff.

### ISSUE THREAD

**Issue by st33lman** [Courseplay/courseplay#2279]
Hello,
I´m harvesting chaff with the krone big x and 3 tractors, when one of them is full and have to make a turn to go to the first point of route to silo the game freezes for some minutes but when  he leaves the harvester straight whithout the turn, no freezes. Sometimes the next tractor will go in infinite loops and the game freezes. I leave you the log with this error D:/FS17ModsMR/ZZZ_courseplay/distance.lua:31: attempt to index local 'object' (a nil value)
Error: Running LUA method 'update'.

[log.txt](https://github.com/Courseplay/courseplay/files/1290385/log.txt)

**Comment by pops64** [comment]
Try with all mods off. Expect CP and the map your running. Post a log with debug channel 4 active before starting CP.

**Comment by st33lman** [comment]
I´ve started a new vanilla savegame, only the mod map and course play, same in game 
tractors only the forage harvester is different is the in game New Holland, the freezing on the turn and loops continue. I save the log with the debug channel 4 on. 
[log.txt](https://github.com/Courseplay/courseplay/files/1291025/log.txt)

**Comment by pvajko** [comment]
This is the same message as we see in #2236 and may have to do with the collision detection. What we can definitely do is to check for nil objects everywhere before calling distanceToObject to at least gracefully handle it.

**Comment by st33lman** [comment]
After some more testing i managed to stop the freezing by disabling the pathfinder feature for all the three tractors.

**Comment by pvajko** [comment]
Can you post the savegame and courses for a freeze scenario as described in section 9 in https://github.com/Courseplay/courseplay/wiki ?

**Comment by pvajko** [comment]
Front tractor unregisters from combine:

Error: Running LUA method 'draw'.
dataS/scripts/triggers/SiloTrigger.lua(366) : attempt to index field 'siloTrailer' (a nil value)
Warning (LUA): 'setVisibility': Argument 1 has wrong type. Expected: Int. Actual: Nil
......\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
Error: Running LUA method 'update'.
C:/Users/Jeremy/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/distance.lua:31: attempt to index local 'object' (a nil value)

**Comment by st33lman** [comment]
I leave you the savegave and courses if you need it. The map is a mod map, you can find it in this link http://www.modhub.us/farming-simulator-2017-mods/parkers-prairie-v1-4/

[SavegameAndCourses.zip](https://github.com/Courseplay/courseplay/files/1300455/SavegameAndCourses.zip)

**Comment by pvajko** [comment]
Try with the latest version v1.00190 and report back.

**Comment by st33lman** [comment]
For the time being it´s working no freezes and no errors in the log but when the second tractor begins to follow the first there is a litle lag from time to time. It´s playble but some more refinement is needed. Thank you.

**Comment by pvajko** [comment]
That lag you are seeing may be because of the pathfinding takes longer on huge fields with lots of fruit between the tractor and the combine. If that's the reason, it should go away once you have 2-3 headlands done and tractors can find their way around the fruit.
