### ISSUE TITLE
Mode10 not detecting Mode 2 drivers

### ISSUE THREAD

**Issue by thomasglavesb** [Courseplay/courseplay#2280]
Dear Friends, 

I have problems with leveling mode. The tractor that compacts the silo works normally, but when the other tractor that transports the product arrives the tractor that compacts does not wait for it to do the process of emptying. Help Please!!
I tried with the new version of CP17. Version .00187

**Comment by pops64** [comment]
Increase the range detection for CP drivers.

**Comment by spidypiet** [comment]
turn off traffic on the map

**Comment by pops64** [comment]
Closed due to inactivity
