### ISSUE TITLE
Mode 2 First Start Weird Behavior

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#2281]
When you first start mode 2 with grain in the trailer. When it is first called by the harvester instead of driving to the harvester it runs the unload course not really a bug just annoying and its behavior has changed from earlier versions thanks. Should note that the tipper is waiting at waypoint 1. When it waits at the last waypoint this doesn't occur.

**Comment by pvajko** [comment]
What did you select when starting it, nearest/current/first waypoint? And then it did wait a while until the combine was full, and when it reached the fill level, it ran the unload course instead of driving to the combine? 
Can you confirm this?

**Comment by pops64** [comment]
Current waypoint. First will send it straight to unload course(Not a bug). Nearest is a mixed bag depends on the point it selects. Using current waypoint. It will sit there an wait for it to be called and then it will start driving towards the x, y waypoint given to it from CP and then it will change its mind and switch to the 3rd or second waypoint recored waypoint

**Comment by pvajko** [comment]
Get me a savegame then I believe it :)

**Comment by evybart** [comment]
also here  drives first to the unload course en then to the harvester .

**Comment by pvajko** [comment]
Please follow the instructions in https://github.com/Courseplay/courseplay/wiki, under number 9 to post a savegame and courses to reproduce.

**Comment by pops64** [comment]
I am going to close this out has it no longer reproducible in 194. I think you change something that it no longer enters follow way-point mode when going to the harvester now. I jumps straight to drive behind combine mode. Unless @evybart can produce a save game file I will close this for now and reopen this if a save game is produce
