### ISSUE TITLE
Mode 2 Leaving Havester Broken with AIVE

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#2282]
May be related to #2279 but mine isn't frezzing. When it leaves the havester it just can't seem to make up its mind has where it wants to go. [Video](https://youtu.be/x6xEWGevibI) [Log](https://gist.github.com/pops64/4c4cd403313fb38abc472ba7de3cde3f) I can produce a savegame if you need it. Using old course gen. No headlands. Pathfinding was off in the above video but it didn't matter cause the 3 times this harvester unloaded it produce this 100%

**Comment by nyfarmboy07** [comment]
![fsscreen_2017_08_27_13_14_47](https://user-images.githubusercontent.com/24856526/30250828-3c3a8408-9623-11e7-847b-aca5ff0f4183.png)
![fsscreen_2017_08_27_13_14_52](https://user-images.githubusercontent.com/24856526/30250829-3d822ce4-9623-11e7-9139-38adbe05ad4b.png)
I get this issue with mode 2 when using forager. I am unsure if this is related or not

**Comment by pops64** [comment]
You have to be way more descriptive that just give me two pictures. https://github.com/Courseplay/courseplay/wiki

**Comment by pops64** [comment]
Did some more testing. It appears CP is no longer ignoring the additional collision triggers added by the AIVE mod.
