### ISSUE TITLE
Problem with CP and Claas Xerion

### ISSUE THREAD

**Issue by Maogami** [Courseplay/courseplay#2283]
Hey, to be honest i dont know if it's problem with tractor itself or an implement. Problem is when my Xerion tries to perform reverse maneuver he stucks in something what we can see at the included video.

https://youtu.be/grrGEhuDAQM

I haven't tested other tractors cuz I'm only using this one.

**Comment by pops64** [comment]
What implement are you using? Is it Giants or Giant's DLC or is a mod?

**Comment by Maogami** [comment]
Implement - Giants (stock) VADERSTAD Carrier XL 825
Tractor - https://www.modland.net/farming-simulator-2017-mods/tractors/claas-xerion-with-kaweco-double-twin-shift-v-1.1.7.html

**Comment by pops64** [comment]
The error your encoutnering is usally a tool specfic error but if your using a vanilla or dlc tool that it has to be your tractor. Could you try again with a different tractor?

**Comment by Maogami** [comment]
Yeah, tried with different one (Claas Axion 900 from in-game mod browser) and it's working as it should work. Wouldn't it be Xerion's specific steering? I mean by default Xerion has double axis steering ON.

**Comment by pops64** [comment]
Possibly. Closed merged into #2231

**Comment by Maogami** [comment]
I found out what was causing this bug. It was this attachable back-weight included in the mod. When it's detached CP recognize turn maneuver properly, and when it's here sitting at the back of a cab, CP somehow detect bad implement. [Look at video](https://youtu.be/CzaVpiQYZMs) I made while testing and tell me please if there can be done something to make CP recognize real implement instead of this back-weight? To be honest I love this weight so much that I can't play without it (T_T)

**Comment by pops64** [comment]
Yea. I will post instructions on how to do this a little later

**Comment by pops64** [comment]
What is the name of the back weight? 
One line 183 insert
```
elseif workTool.cp.xmlFileName == 'nameofxmlfile.xml' then
		workTool.cp.implementWheelAlwaysOnGround = true;
```
replace nameofxmlfile with the name of the XML file for the mod. Make sure the '' and .xml and still present. It will make all tools attached to this weight do circle turns instead of 3 points. I think the system that checks this only looks at the first tool and not all of them.

**Comment by Maogami** [comment]
elseif workTool.cp.xmlFileName == 'Claas_Xerion_rearWeight.xml' then
		workTool.cp.implementWheelAlwaysOnGround = true;

So it should looks like this? And then, where should i add/replace it?

**Comment by pops64** [comment]
Sry line 183 of special tools.lua and it is a insert that looks right
