### ISSUE TITLE
mode10 with reverse-drive system

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#2284]
Hello
is it possible to get cp mode 10 levelling with tractors with reverse-drive system?
i mean normal i attachet in front a heavyweight and in the back the holaras leveler shield.
now my poor tractor driver became a stiff neck while he drive always in back in the silo to leveling.
but the valtras and fendts have a reverse driving system.
but when i attachet in front a heavyweight and in the back the holaras leveler shield and turn the driver from forward looking to backward looking - so he see the shield in front - i cant work so.
the traktor will always turn back while he will drive backwards, bu in this fall this is forward.

lg
andreas

**Comment by pops64** [comment]
This won't be looked into until after CP is released.
