### ISSUE TITLE
Not an issue, simply a question.

### ISSUE THREAD

**Issue by acsjoe** [Courseplay/courseplay#2285]
Is there any way to make the combines and harvesters operate in a fashion so that after they open a field they break the center of the field open and work there way to the outer edges so unloading auger is always on the same side?

**Comment by jbellfarmer687** [comment]
That is a very good point. For higher yielding crops (such as corn, some varieties of wheat, grain sorghum, soybeans, and other crops) that would be very realistic. It would also be easier for CP's pathfinding. It would also make it easier for a grain cart course on larger maps.

**Comment by Tensuko** [comment]
For this I use AIVE, it even works with 3 Harvesters, just start one after the other with some distance for the turning points. Then I have 3 Overload Tracktors running, wich fills up my road train (sadly only one overload position, so I have to move the roadtrain forward manually)

**Comment by pops64** [comment]
The mode 1 driver should automatically move to the next trailer if the current one is full. I  don't remember if the mode 3 driver waits while this happens tho

**Comment by acsjoe** [comment]
Not only that but if tillage and mowers could skip every other path when going back and forth the path should be easier with no backing up required or little.

I'm not trying to pick apart courseplay, I just like giving suggestions as I am a horrible modder and you all that do this are excellent people that make FS so much better, I could not imagine the time that goes into this stuff.

**Comment by pops64** [comment]
Tillage and  mower can already skip paths. Use the lane offset with turn with symmetry. It doesn't work so great with the new course system(having headlands throws this off) but the old this would meet your second question. Regarding your first post. We have looked into it but it won't be something we would implement until after the release. Closed for now.

**Comment by pvajko** [comment]
Actually, both modes (spiral, aka headlands only) and skipping lanes is implemented in the new course generator, only it isn't hooked up to the HUD yet.
