### ISSUE TITLE
More info and field test to the closed issue #2283

### ISSUE THREAD

**Issue by Maogami** [Courseplay/courseplay#2287]
First of all I have created this new issue because you have closed earlier one.

I found out what was causing this bug. It was this attachable back-weight included in the mod. When it's detached CP recognize turn maneuver properly, and when it's here sitting at the back of a cab, CP somehow detect bad implement. [Look at video](https://youtu.be/CzaVpiQYZMs) I made while testing and tell me please if there can be done something to make CP recognize real implement instead of this back-weight?

**Comment by pops64** [comment]
Please post all simliar issues to mod theards in there respective thread. Has stated #2231. Even if it is closed I still will see a notification. Merged into #2231. Will update that with this information later
