### ISSUE TITLE
Feature Request: Additional Continue Option "next"

### ISSUE THREAD

**Issue by eire1130** [Courseplay/courseplay#2289]
Right now, there are three options when continuing a stopped course:

1. First
2. Current
3. Nearest.

Sometimes, what I really want is "next". Occasionally, tractors, when running multiple get stuck and need manual intervention. When restarting, sometimes courses are close by, or the nearest waypoint is not the one you want. Really, what you want is "next".

My experience with "current" is it will go back and touch the previous waypoint (probably "current") and then continue course. This can lead to wierd behavior, like circling or reversing a course at 3mph for a long period of time.

So, the proposal is to extend the options to:

1. First
2. Current
3. Next.
4. Nearest

(A kinda cool option might also be "arbitrary" as well, but maybe that's more advanced and would require manual input)

**Comment by pvajko** [comment]
Yes, this is one of the most annoying issues with CP, I was going to add this once we finished fixing the critical issues.

**Comment by pvajko** [comment]
Give it a try and report back.

**Comment by pops64** [comment]
Closed due to inactivity
