### ISSUE TITLE
Game freeze by saving the pipe position from the auger wagon

### ISSUE THREAD

**Issue by s1100** [Courseplay/courseplay#2306]
Hello,

my game freeze by save the pipe position from the auger wagon (bergmann gtw 430 Mod), befor it runs perfect.
 It´s i think since the second latest update from courseplay.

Here is my log:
[log.txt](https://github.com/Courseplay/courseplay/files/1299938/log.txt)

**Comment by pops64** [comment]
We will look into when get a chance but for now unless this breaks on a vanilla equipment. We will close this and merge into #2231
