### ISSUE TITLE
Tractors are driving circles 

### ISSUE THREAD

**Issue by luppes88** [Courseplay/courseplay#2307]
Hello guys, 

I have a problem with courseplay witch I don't understand. I tried, so far I know everything, you guys are my last hope :p 

When I set courseplay in harvesting mode and I the tractor beside the harvester is full, the next tractor (he is following already) should go to drive next to the harvester.

But then completely out of nothing he starts to drive in circles. When I am doing something else like compares the bunker, and my computer stutters for a second I know he is driving circles. Before I have no problems with fs17. I downloaded the developers edition. I deleted al other mods except courseplay and played with the original tractors etc. 

I deleted the hole game en start al over. I did a virus scan (maleware and defender). I tried to set the turning wider. I tried to reduce the field speed and turn speed, Uhm o yeah I set the start and stop point in the field. I set the first 3 waypoints in field. I set start before stop. I tried everything. And yes the computer and keyboard are still alive :p 

This is the best example the bug does the same with cultivating, seeding or ploughing a field.

Could you help me with this? Sorry for the English, I'm Dutch. Greets Ruben.

**Comment by pvajko** [comment]
What you can do is to set up a scenario as simple as possible, as few vehicles as possible (like one tractor cultivating), set the debug channels 4, 7, 9 and 17 and post the log. If you are really nice you help us to reproduce it by sending savegame, courses, see https://github.com/Courseplay/courseplay/wiki.

**Comment by luppes88** [comment]
Okej Peter. Thanks for your quick  answer.

I uploaded the log file. I hope it works and so you could do something for me.

Regards Ruben Luchtenberg.


Op 14 sep. 2017 om 16:28 heeft Peter Vajko <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


What you can do is to set up a scenario as simple as possible, as few vehicles as possible (like one tractor cultivating), set the debug channels 4, 7, 9 and 17 and post the log. If you are really nice you help us to reproduce it by sending savegame, courses, see https://github.com/Courseplay/courseplay/wiki.

**Comment by pvajko** [comment]
I'm sorry, where exactly did you upload the log file? Link?

**Comment by luppes88** [comment]
In the github 'how to provide a nice and sexy bug report'

Or do I need to do something else? Please let me know.

Regards  Ruben.


Op 14 sep. 2017 om 23:14 heeft Peter Vajko <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I'm sorry, where exactly did you upload the log file? Link?

**Comment by pvajko** [comment]
Have you uploaded the log file to Gist or Pastebin? If yes, you need to **post the link** to your log file here so we can find it.

**Comment by luppes88** [comment]
Gist. Ok. I will take a look. If it's done I will let you know.

Greets.

Op 14 sep. 2017 om 23:48 heeft Peter Vajko <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Have you uploaded the log file to Gist or Pastebin? If yes, you need to post the link to your log file here so we can find it.

**Comment by luppes88** [comment]
https://gist.github.com/luppes88/4e3a99418e32d1cac8d6e1c2ef4598f7
 Like this?

Op 14 sep. 2017 om 23:48 heeft Peter Vajko <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Have you uploaded the log file to Gist or Pastebin? If yes, you need to post the link to your log file here so we can find it.

**Comment by pvajko** [comment]
Yes, I can see that. I also see the log file has mods (Claas Orbis, etc.) in there, you said you can reproduce this with the in game vehicles, cultivating or sowing. So can you post a log with an in game vehicle cultivating or sowing?

**Comment by luppes88** [comment]
Oke, I'm sorry oke. Yes I will do that. Do I have to wait till the problem is showing up and then send the file log?

Regards Ruben.

Op 15 sep. 2017 om 00:10 heeft Peter Vajko <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Yes, I can see that. I also see the log file has mods (Claas Orbis, etc.) in there, you said you can reproduce this with the in game vehicles, cultivating or sowing. So can you post a log with an in game vehicle cultivating or sowing?

**Comment by pvajko** [comment]
Yes. And please use the latest version.

**Comment by luppes88** [comment]
Hello peter. I hope you can do something with this log.

The tractors are not driving circles this time. I didn't harvest this time.

https://gist.github.com/luppes88/28a28b2c89ae4592375df9940efa96a7#file-log-txt
________________________________
Van: Peter Vajko <notifications@github.com>
Verzonden: vrijdag 15 september 2017 00:09:40
Aan: Courseplay/courseplay
CC: luppes88; Author
Onderwerp: Re: [Courseplay/courseplay] Tractors are driving circles (#2307)


Yes, I can see that. I also see the log file has mods (Claas Orbis, etc.) in there, you said you can reproduce this with the in game vehicles, cultivating or sowing. So can you post a log with an in game vehicle cultivating or sowing?

**Comment by pvajko** [comment]
Ruben, I'm sorry I'm confused. Did you see any problems while recording this log?

**Comment by luppes88** [comment]
I'm sorry. I did what you said. I had tractors ploughing cultivating and seeding. I did not saw the problem this time. But I thought I send you the log any way maybe you could see something. I'm gonna play the game like before and when I notice the problem I'll send you de log.

You want only the log when they are ploughing seeding and cultivating?

I appreciate you're help and patience.

Greets Ruben

Op 17 sep. 2017 om 16:11 heeft Peter Vajko <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Ruben, I'm sorry I'm confused. Did you see any problems while recording this log?

**Comment by pops64** [comment]
We need the debug channels on just before the problem occurs and only the equipment that is causing the problem running. Other wise the log just becomes to large to see anything

**Comment by luppes88** [comment]
Oke. I got know a courseplay when te tractors are harvesting.

 I play yesterday for a long time. When I was seeding and cultivating with the bug channels on. When channel 17 was on the game was very slow. But the problem about the circles was gone.

So I tried the same with the harvesting mode. That was a success. After a few minutes one tractor is drive circles and driving an eight.

I hope you can help me

https://gist.github.com/luppes88/59d774e461abe7bb746717f8d2654ad0#file-log-txt

Greets Ruben


Op 17 sep. 2017 om 20:13 heeft pops64 <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


We need the debug channels on just before the problem occurs and only the equipment that is causing the problem running. Other wise the log just becomes to large to see anything

**Comment by pvajko** [comment]
This has been fixed in v1.00190 (commit 11d49b026982e72759ebc9f239d779ab767167ba), you are using the outdated version 187. Please make sure you update to the latest version of Courseplay.
