### ISSUE TITLE
Refill Seeders uncover trigger 

### ISSUE THREAD

**Issue by bruteman** [Courseplay/courseplay#2309]
So i'm playing with the new Khun DLC pack (specifically the Plough +Cult + Seeder with frontend fill seed tank)  and noticed something unusual with the refill seed functions. 

The Setup: 

Using Augur / overloader wagons for dry fertilizer and seed as a mobile seed/fert refill point (Note: works fine with a tanker of liquid fert for sprayers) but because CP will not auto uncover the seeders / dry fertilizers as they never detect the overloader full of seed / fert there ready to fill them up.

Possible idea options to fix:

It would be nice to just add the auto covers option on / off for this mode which is a quick fix so we can force them to stay uncovered always (ugly but would work) or uncover the seeders soon as they are detected 0% and are leaving the field so they will fill when they get under the overloader not sure if this will still stop the script from driving by but right now i can't test it with the covers stuck "on" the machines in that mode.

Also not really sure if it was just the equipment i am using but this setup is really picky about overloader pipes being detected as traffic get in the overloader and tap the pipe retract on and off clears the path

**Comment by pops64** [comment]
I look into it but I know if mode 4 is setup correctly is should automatically uncover the tools. This may not work for for Kuhn seeders bin

**Comment by bruteman** [comment]
oh it will uncover for trigger points like a auto seed refill or a pallet of seed it just wont work with overloaders or other methods of filling the seed bins (i.e. pause point for manual hand feeding seed etc.) this is where if we can tell the CP to just leave the covers on manual or off mode it might be enough for these other methods.

**Comment by pops64** [comment]
I was added into the code for it remove the covers when it arrives at the waitpoint. So unless you're using an old version it should be working. I'll look into it this weekend

**Comment by bruteman** [comment]
that might be a scenario i didn't try i'm out of town for the weekend i'll
try a wait point in the refill perfectly under a overloader see if the
cover pops off but i thought i did try that in my many attempts to get it
to fill.

**Comment by bruteman** [comment]
you are correct placing a wait trigger works now if i could just get cp to stop thinking all the stevie's maps siloking output pipes were other vehicles in the way i'd be golden .... issue not needing resolve you can close.

**Comment by pops64** [comment]
That may be the traffic system screwing up. It doesn't differentiate between solid and none solid. I think Mode 4,6,8 should ignore standard giants triggers tho but obviously stevies pipes aren't being detected correctly.
