### ISSUE TITLE
Just a question about a known and "solved" problem.

### ISSUE THREAD

**Issue by MoslessNeo** [Courseplay/courseplay#2310]
I would like to know how can I change the time to reset the helper? I found in the driver file the value 300 (5 min). but even changing to 120 the helper does not reset at the set time. Would there be another place where I can change the time?

After long hours of playing on difefent maps, including my normal size, 4x and 16x I came to the following conclusion:
In FS15 I was able to solve the situation of the helper by disabling the animation of the player's arm in the .xml file of the game base file.
In version FS17 it is not possible to change this.

About the problem:
The helper problem gets distorted when using CP occurs for different reasons or the combination of two or more factors.
When the field to be worked is very large and you use few vehicles in the same field. Example: 256ha for 1 helper (16x map)
Many waypoints for few helpers in the same field.
As you use more helpers in the same field the distortion effect is less aggressive.
Whether the field is medium or large and the equipment is small. Example 64ha for 1 helper with equilament of 4m width.

**Comment by pops64** [comment]
That is the only place to adjust the time of the reset.

**Comment by pvajko** [comment]
Question answered.
