### ISSUE TITLE
Boundaries in stappenbach fields map

### ISSUE THREAD

**Issue by PromGames** [Courseplay/courseplay#2317]
Hi Satis, 

Ls mod company has released two days ago the stappenbach map.

There are many users having problems with the field boundaries and the time that the map takes to load when all fields are acquired.

Why this delay? Scan process is getting crazy. This map has special script for joining fields. This is the reason I think, but maybe you can take a look. 

The courious thing is that creating custom fields with a tractor on the field, is doing the scan correctly, but depends on the position of the tractor, is scan ok or not. Also if you press more than one time the get the boundaries button, it change it get two fields or three or if you are lucky, just one.

You can find the map in Modhub and maybe you can run a debug on the scanning to see why is doing this. We would like to solve it for next version.

For the time being, I am preparing a set of custom files to share including all fields as custom fields. I think the system will not scan if he finds custom field? Is that right?

Also, there is a limit of number of fields to 150 when you want to set the field scanned, can be increased to 200. This map has 185 fields.

Thanks

**Comment by pops64** [comment]
You can always change it to manually scanning. A user defined field boundary will not be overwritten by the auto scan. The fact that there are 185 fields may be the reason why the scanner is running so slow.

**Comment by pops64** [comment]
Sorry to double post but could you please provide a save game with the long load times? Thanks I have just downloaded and ran into no issues. The scanner was moving along at a normal rate it just takes a little extra cause of the # fields and the load times was even faster than some other mod maps have but this is just a blank install only CP and chopped straw

**Comment by pops64** [comment]
I should put a shoe in my mouth till I have throughly tested this. It seems to be a differnt mod conflict causing the loading times. With nothing but CP enable it loads respectably. The field scanner may not be possible to fix tho.

**Comment by PromGames** [comment]
Did you check to scan on fields , take a look at filed 4 5 6, is where this join fields appears

**Comment by PromGames** [comment]
maybe is related to the gras object is using or the type of grass that confuse to Courseplay as continuity of the terrain detail

**Comment by pops64** [comment]
I think CP sees the two field close enough together when using the scan on field tool that it joins them. I think the auto handles it differently though I am waiting for Claus input

**Comment by pops64** [comment]
I looked through fields.lua if you want to take a look your self. My quick understanding of it is that it probes along the field. If the probe lands in a field it keeps going in that direction until it doesn't. Than it rotates a certain amount and repeats until if finds the field again. So I think on this map the field are way to close together and this probing is always finding a field. The probe step length I believe it is 1m step so if it is possible to have the map author set field apart by this much it would help. The other option is maybe step this down step but I believe that would increase scan time.

**Comment by PromGames** [comment]
I have got now scan times correct with a set a custom fields. I will upload the set to stappenbach and people can get it from there. I think is the best solution that we can provide.

The giants helper is also getting confused and maybe to increase to 1 mts the space could help. 
I have changed the code and it works changing the max custom files to 200 in fields.Lua This will help with maps with over 150 fields like this.

**Comment by pops64** [comment]
What line did you adjust to fix this? I was messing around with that file and couldn't seem to get the correct variable. I know it will be a pain to fix the field to greater than 1 meter but how much did deceasing the scan distance due to your scan time?

**Comment by pops64** [comment]
What was wrong with the scan times I didn't notice any delay other than it taking the standard time to do 185 fields? I know with my old dev version of season it killed the load time. How is the load times with custom fields? I think this would move the scanning to a pre instead a post load process.

**Comment by PromGames** [comment]
You can find the custom field file here. 

[https://ls-modcompany.com/filebase/file/57-stappenbach-fix-for-courseplay/](url)

**Comment by pops64** [comment]
Alright @Satissis had this to say about scanner load times 

> but the auto field scan uses the field info from the game it self, so if those are not placed in the correct locations, like outside the field, then it's trying to scan the whole map instead of the field it self, and that is what can take a really long time to do and it can even hang the game fully. Also if that mod he is using to join fields together, is changing the standard values of the giants data, then that could be an problem as well.

The only deference between manual and auto is were it starts.

**Comment by PromGames** [comment]
Then, I think we can close this issue and wait if the new version of the map has better field boundaries definition. Because it will have missions. For the time being, people using courseplay with the current published map and my set of custom fields will work ok.

**Comment by pops64** [comment]
So I have a few answers now that I got the debug to work. 1. the debug needs dubuging :P for what ever reason the variable to turn it off and on turns it self off. 2 When you own all 185 fields it scans every single one of them. When you own less it only scans the ones you own and skips over the ones you don't so this obviously would increase scan time the more fields you would own. 3. I am in the process of looking of the debug dump and I will see if I can give you a better answer why it is doing what it is. I will update this comment has I read more into it.
