### ISSUE TITLE
Trees in Fields and Courseplay

### ISSUE THREAD

**Issue by BROADACRES16xFS17MAP** [Courseplay/courseplay#2319]
Just seeing if the FS17 CP version has the ability to detect trees in fields and thus map a course around them? I have moved the terrain detail from around the trees but CP isn't picking it up and is still having straight way points through the non terrain area. Cheers.

**Comment by pops64** [comment]
CP still can't handle island in fields. I do not what the status of this implementation I know @pvajko was working on something. Closed for now
