### ISSUE TITLE
Grain transport mode, vehicle don´t stop to load.

### ISSUE THREAD

**Issue by Elgroo** [Courseplay/courseplay#2321]
Hi there, I'm having this issue:
In grain transport mode, the tractor or truck don't stop at the first point (fill point) to load, on filed to wait for a overload or in silo to fill and transport the grains.

Thanks.

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Elgroo** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/1326785/log.txt)
[FS17_LincolnCreek.SampleModMap.zip](https://github.com/Courseplay/courseplay/files/1326786/FS17_LincolnCreek.SampleModMap.zip)

All courses for grain transpor have the same issue. 
Corrent "Unload F48"

**Comment by Elgroo** [comment]
Courseplay version:  .00187Dev

**Comment by pops64** [comment]
Could we get a picture of how you have your courses setup. And please update to version 195 and check #2231 if you are running any unsupported mods.

**Comment by Elgroo** [comment]
Problem solved, with 196 version. Thanks.
