### ISSUE TITLE
Question: Is it possible to make overloader always drive next to combine?

### ISSUE THREAD

**Issue by blaz62746** [Courseplay/courseplay#2322]
Is it possible to make tractor with overloader always drive under combine pipe and disable the feature when overloader stops, finds his waitpoint behind combine and waits for combine to fill over set percentage?

**Comment by Tensuko** [comment]
I think you can do it with the option 'Start on X%'. Set it to 0% or 5% and try it out.

**Comment by blaz62746** [comment]
Setting 'Start on X%' on 0% or 5% doesn't work. I know it works for silage combine but I want it for regular combine harvesting wheat, barley, canola, etc.

**Comment by pops64** [comment]
No it is not possible. As the turn maneuvers for for following a harvester are specific to forage harvesters. Regular harvesters have no method for turning the tipper around when the harvester turns. And we won't add the compatibility to CP.
