### ISSUE TITLE
Field boundaries Issue

### ISSUE THREAD

**Issue by cpoole2005** [Courseplay/courseplay#2323]
![great fields field 1 boundries wide](https://user-images.githubusercontent.com/5596638/30813688-1721caea-a1dc-11e7-8ff1-809a5ae53bbd.PNG)
![great fields field 1 boundries zoomed in on problem](https://user-images.githubusercontent.com/5596638/30813687-17021fb0-a1dc-11e7-8ff2-ee9fb38d34c8.PNG)

![fsscreen_2017_09_25_10_22_23](https://user-images.githubusercontent.com/5596638/30814168-6aef9264-a1dd-11e7-8405-86960d106f19.png)
![fsscreen_2017_09_25_10_33_48](https://user-images.githubusercontent.com/5596638/30814167-6aea7a5e-a1dd-11e7-99dd-006c4b0ad056.png)
![fsscreen_2017_09_25_10_35_57](https://user-images.githubusercontent.com/5596638/30814169-6aefa362-a1dd-11e7-8645-aa939f67437d.png)

I'm Playing on Great Fields, field 1 in the south west corner there is something going on with the boundaries I would like to fix for my self but am not sure what the problem is. Field 1 does not show up in the list of fields, when I Calculate current field's edge path the line that represents the south and the line that represents the west edges do not meet.

**Comment by pops64** [comment]
I can't tell what the problem is. Please take pictures during the day time.

**Comment by cpoole2005** [comment]
Here are some better pictures during the day time. Pops64 increasing to 10 once I understood what you meant was the fix THANK YOU for your help

![boundries zoomed in](https://user-images.githubusercontent.com/5596638/30872913-9bb24270-a2b9-11e7-89a4-7602c1305f4c.png)
![fsscreen_2017_09_26_12_39_53](https://user-images.githubusercontent.com/5596638/30872917-9bc26646-a2b9-11e7-8d3c-0882c50aa9fa.png)
![fsscreen_2017_09_26_12_42_00](https://user-images.githubusercontent.com/5596638/30872915-9bbc2f24-a2b9-11e7-8242-9e8aeadda011.png)
![fsscreen_2017_09_26_12_43_26](https://user-images.githubusercontent.com/5596638/30872914-9bb82848-a2b9-11e7-8121-af0a41e80574.png)
![fsscreen_2017_09_26_12_44_19](https://user-images.githubusercontent.com/5596638/30872916-9bbd377a-a2b9-11e7-8c21-b5fcffd80c6e.png)
![fsscreen_2017_09_26_12_45_22](https://user-images.githubusercontent.com/5596638/30872920-9c027e98-a2b9-11e7-9d30-d5e5e0b7a36e.png)
![fsscreen_2017_09_26_12_46_28](https://user-images.githubusercontent.com/5596638/30872919-9bcab968-a2b9-11e7-9a5a-de01bb869f5f.png)
![fsscreen_2017_09_26_12_46_36](https://user-images.githubusercontent.com/5596638/30872918-9bc65472-a2b9-11e7-9503-972fcc6e9510.png)

**Comment by pops64** [comment]
Alright if increasing it to 10 work for that's great. If you put it to high you will run into the issue linked above. Closed. Pictures indicate that what I mentioned is the issue. I think the limit is 10km border
