### ISSUE TITLE
Courseplay freeze

### ISSUE THREAD

**Issue by Mrsidders** [Courseplay/courseplay#2324]
Everytime I run a course in courseplay when a combine or harvester is on tempory course and the tractors are on recorded course the combine calls to be unloaded and then the courseplay sends everything on freeze it's asthough everything is getting lag..... I have removed every mod and loaded back in one by one and its still the same. I am currently playing Cherry Hills made by Stevie and downloaded from Stevie's own google drive. Can some one please have a look into this

**Comment by pops64** [comment]
Please follow https://github.com/Courseplay/courseplay/wiki

**Comment by Mrsidders** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/1347108/log.txt)

**Comment by Mrsidders** [comment]
here is the log you have requested You can see I have even tried debug 3 and still the same

**Comment by pops64** [comment]
We didn't ask for any debug channels. Please don't turn any on when submitting logs. Try turning path-finding off and see if that improves the game performance. Also leaving debug channels on will slow down you game

**Comment by pvajko** [comment]
@Mrsidders can you upload your courses and savegame as described in the wiki (https://github.com/Courseplay/courseplay/wiki), section 9?
