### ISSUE TITLE
Distance.lua31: Error v196

### ISSUE THREAD

**Issue by Fendtfan84** [Courseplay/courseplay#2325]
i play with seasons mod of the OldStreams Map.
when the season change from spring to summer  coming this log error:
Error: Running LUA method 'cpOnTrafficCollisionTrigger'.
C:/Users/Johh J Rambo/Documents/My Games/FarmingSimulator2017/mods/FS17_Courseplay5/distance.lua:31: attempt to index local 'object' (a nil value)
Error: Running LUA method 'cpOnTrafficCollisionTrigger'.

This is a link from my log.
https://gist.github.com/Fendtfan84/9984d704062430aa7ab046aaaf812713

**Comment by pops64** [comment]
Seasons has nothing to do with what equipment where you running with CP? Does it freeze your game? https://github.com/Courseplay/courseplay/wiki

**Comment by pvajko** [comment]
This is from courseplay:deleteCollisionVehicle in cpOnTrafficCollisionTrigger calling distanceToObject with nil. I missed band aiding that location last time.

**Comment by Fendtfan84** [comment]
My Game freeze wheen the info from summer mesage from the season mod coming. 
To this time is no equipment running with CP.

**Comment by pvajko** [comment]
Seems really unlikely this is caused by CP when it is not even running any vehicles.

**Comment by pvajko** [comment]
Can you check if this message is coming when the game freezes? It would be really weird to have a collision triggered while CP is not even driving. It may have reported earlier. Also, typically, if this was the cause of the freeze you'd see it million times in the log.

**Comment by Fendtfan84** [comment]
Yeap when this message came from season mod:
the crops preparation for harvesting and fertilizing
freezes the game when i stand near a equipment (tractor).
the mouse then does not appear for you can klick of ok in the message box from the season .
i hope you can understand this.

**Comment by pops64** [comment]
Maybe one of the tippers in mode 2 didn't unregister for the combine. I know there is a way you can make that occur
