### ISSUE TITLE
Overloader waits for combine on grains and blocking it

### ISSUE THREAD

**Issue by blaz62746** [Courseplay/courseplay#2326]
![2017-09-26](https://user-images.githubusercontent.com/26365587/30865088-ecf55750-a2d5-11e7-8484-47b53cafa936.png)
This is how overloader stops after unloading combine and after going to its waypoint and waiting for fill percentage of combine to be reached. I have pathfinding disabled because then combine can't be unloaded when pipe is on the same side grains are growing. This is causing me big problems because I have to move overloader further approximately every 5 minutes. Have I set some settings wrong?

**Comment by pops64** [comment]
Log with debug channel 3 please.

**Comment by blaz62746** [comment]
Okay. I did as you said. I tried with vannilla auger wagon and it doesn't make the problem. Out of two vannilla trailers, I used Metaltech PP20 because Bergmann has issue with saving pipe position (read it in unsupported mods issue).
Here are log files for both vannilla trailer (Metaltech PP20) and Big Bud trailer (Brent Avalanche).
[log [brent_avalanche].txt](https://github.com/Courseplay/courseplay/files/1334381/log.brent_avalanche.txt)
[log [metaltech_pp20].txt](https://github.com/Courseplay/courseplay/files/1334383/log.metaltech_pp20.txt)
I was wondering if this issue can be fixed because Metaltech trailer has lower capacity?

**Comment by pops64** [comment]
Yea has I guess for what ever reason when the mode 2/3 tipper enters bypassing mode it doesn't correctly receive the parking spot location. Your seeing it on the dlc augur because if I remeber correctly is longer than the pp20

**Comment by blaz62746** [comment]
Yes, I'm running Auto combine (the one activated with "H" button). At first, I thought that's the problem and I tried running combine with courseplay, but same thing happens.

**Comment by pops64** [comment]
I am talking about Mogils Mode. Not the standards Giants Helpsers

**Comment by blaz62746** [comment]
Oh, sorry. I'm not using that one.
