### ISSUE TITLE
Question/Suggestion: first waypoint on fieldwork

### ISSUE THREAD

**Issue by TheRealRolandDeschain** [Courseplay/courseplay#2327]
Hello, 

In a short search I couldn't find anything similar so I hope this is no duplicate: 

After auto-generating a course in fieldwork it would be nice if, when setting the drive to start at the first waypoint, it would align automatically with the course before starting the work. At the moment it drives in a direct line to the first waypoint, which results in a hard turn after starting and leaving a few areas. 

This means one has to drive to the first waypoint manually to align correctly. With a fix you could send the drive directly from the edge of the field. 

As always you are doing a awesome job, thx for that!

greez

**Comment by pops64** [comment]
Unfortunately this just won't be doable in our current system. Has we use the waypoints has the alignment. You can make a coruse with more than 7 waypoints and append the field work course to that. Closed not something we will impelement

**Comment by pvajko** [comment]
Not something we'll implement before the release, but I think we'll definitely address this.

**Comment by pops64** [comment]
See #1772. For a better explanation on how to automate the alignment of the harvester to the field.

**Comment by pvajko** [comment]
This is implemented on the alignWp branch if anyone is interested. That branch also has an improved course recording and aligns to the combi course waypoint when starting back to the silo.

**Comment by lcc1211** [comment]
@pvajko Would this include address the issue of the combine moving several meters into the fruit before beginning the harvest?

**Comment by pvajko** [comment]
Yes as I'll have to tweak the speed setting anyway, currently it is using the field speed all the way to the alignment wp which is too slow.

**Comment by pvajko** [comment]
v5.2.00005 2bcc86e5073f6d2d70be84d3691f7625066dd4a3 attempts to address the original problem. You'll have to turn on Align w/first waypoint in the HUD settings.

**Comment by lcc1211** [comment]
I'm going to try it out in a bit.

**Comment by lcc1211** [comment]
My results are very good as long as the vehicle isn't at some extreme angle, but even then it seems to get about 99% of the way there.  I had about maybe 1/10 of a meter of crop left undone.
