### ISSUE TITLE
Parts of field ignored by cp driver

### ISSUE THREAD

**Issue by Antaiir** [Courseplay/courseplay#2329]
Hi there,

since version 5.01.00189dev i noticed pretty often, that parts of the fields are not processed. Mostly these are parts within a processed straightforward lane, that were just left out for several meters.

I noticed that behavior while cp is plowing, seedig and cultivating. Till now i didn't notice this while harvesting.

Edit: version is **198** (not 189), sorry for the typo above

regards
Antaiir

**Comment by Antaiir** [comment]
@pvajko : Map is vanilla "Goldcrest Valley". I noticed the behavior on every field i used with cp since update to 198 (sorry for typo in opening post). For example i have a driver on field 5 at the moment, he is plowing. The generator settings are:

- Top setting set for field 5 of course
- work width: 8m, corresponding to my plow
- start position: south west
- start direction: east
- end at start position: disabled
- Vorgewende (sorry, i don't know the english term for this): none
- headland corners: not available

I uploaded [my log to pastebin](https://pastebin.com/8ktYh2bV), just in case.

**Comment by pvajko** [comment]
So, you seem to be using the old course generator. That has not changed in 198. Are you sure this was not happening in 197?

**Comment by Antaiir** [comment]
Mh, i'm pretty sure. I also never used 197, i updated to 198 from 187. The generated course seems to be ok (if i look at the plotted lines over the field) and the driver follows this course over the entire field. It's just like he's lifting or disabling the plow, seeder or cultivator for a few meters while driving further and then he enable/lower it again and continue as normal.... until it happens a few lanes later again. The bigger the field is, the more likely those "hickups" occur.

Because i always had to rectify cp drivers work after he "finished", mostly the corners or the end of the lanes, i definitely would have noticed this earlier.

**Comment by pvajko** [comment]
Oh, I see, it is raising the implements. Then it is probably because of 192, and I pass this on to @pops64

**Comment by pops64** [comment]
Try disabling all mods expect CP. I would have to guess it is conflict with another mod. Save the course that is causing issue. Then up load your courses file. See wiki for instructions. Is it always occurring in the same spot?

**Comment by Antaiir** [comment]
Well... without any other mods active, the above behavior won't occur. So i have to find out now, what other mod is causing this. I have not installed any new mods after updating cp to 198, and i am absolutely sure, before 198 there was not such a problem. 

Maybe you can help me with a hint, what mods i should disable for testing? I gues you know best, what has changed in the last cp versions, what can collide with another mod. Any helpful advise is appreciated.

If i had to make a guess, i would say it could be "ai vehicle extension", but this mod and cp were installed together for months, without any trouble so far. For real life reasons i have no time to test this now, i will test during weekend.

thanks

**Comment by pops64** [comment]
No it is not AIVE we do have a bug with it but it is not this. I saw a GroundResponse Mod? I would try the script mods the vehicle ones shouldn't cause an issue to other vehicles. It is probably something that is interfering with the functioning of CP like Combine Addon which requires manual activation of the pipe. Did you update or install any other mods recently I would start there.

**Comment by Symbob** [comment]
I'm fairly certain that it's the Ground modification mod causing this and it has nothing to do with CP at all.  I've had the same problem after installing Ground Modification mod and the problem persists even if you remove CP from your mod folder so we know from that that it's not a conflict with CP.  In my experience the problem occurs on Goldcrest Valley when you tab in to the trains.  All the time you are in the trains the hired workers (CP and ingame workers) stop working even though they continue to drive the course.  Try removing Ground modification and then see if you still have a problem.  Looking at your log it looks like you're using v1.0.0.5 of the mod.  There's an updated version available on Giants Modhub http://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=75812&title=fs2017 which I believe should resolve the problem although I've not tried it.

**Comment by Antaiir** [comment]
I disabled GroundResponse (stopped vehicles "dancing" while trailer is attached) and updated GroundModification tp 1.0.0.6. For now it seems, my above described issue doesn't accur anymore. I will test this further of course, but i see CoursePlay was not the source of this issue. :-)

If there are no other questions, remarks, comments etc. from your side, i think we can close here.

Thanks for your help! :)

**Comment by pops64** [comment]
Alright thanks for the response.
