### ISSUE TITLE
issues with countyline and courseplay

### ISSUE THREAD

**Issue by hombuilder** [Courseplay/courseplay#2332]
Game won't load 
using latest version 198
[log.txt](https://github.com/Courseplay/courseplay/files/1346577/log.txt)

mods/FS17_CoursePlay5/CpManager.lua:42: attempt to index field 'signs' (a nil value)

**Comment by pops64** [comment]
COURSEPLAY ERROR: could not load file C:/Users/wayne/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/reverse.lua https://github.com/Courseplay/courseplay/wiki https://courseplay.github.io/courseplay/en/installation/index.html
