### ISSUE TITLE
Suggestion:  Coursegeneration for pulled potatoe harvesters

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#2333]
Hey,
I'd like to suggest an additional Coursegeneration mode, mainly for extremely long fields or pulled potato harvesters.

In Germany we call this driving style "Beetbearbeitung", but i haven't found a good translation.
It is used, when the same side of the machine is supposed to always be in the direction of the fruit, for example in potoatoe harvesting, driving from the inside of the field outwards.

To show what i would like to see as course, i have attached a badly drawn image.
![beet](https://user-images.githubusercontent.com/9157835/31048602-b5462eb2-a620-11e7-9098-515a93004f2c.png)
And here is a video link for this farmingstyle in action.  
https://www.youtube.com/watch?v=dWyJbOWJF4c

Greets JDTiger

**Comment by pops64** [comment]
Going to close this out and we will revisit this in the future.

**Comment by pvajko** [comment]
No worries, I'll work on this...

**Comment by JDTiger** [comment]
thanks, looking forward to it
