### ISSUE TITLE
Trouble Course play transport fuel 

### ISSUE THREAD

**Issue by criss20ster** [Courseplay/courseplay#2339]
Hello. Do you know anyone on Courseplay? I have one problem with one thing  I have one problem with one thing. The point is I am on the map of Norgeholm 2.1 and there is a refinery from which I would like to pass fuel and farm to those red tanks. Robie Cp using this mode, bring liquid cargo and tanks and click point (waypoint) but nothing happens.  https://i.imgur.com/azG3DDy.jpg

**Comment by pops64** [comment]
Mode 8 only supports standard giants triggers and a very few others theses are not apart of that group. If the fuel trigger is of standard giants you must use a waitpoint to unload and no waitpoint to load. If this doesn't work then those triggers aren't recognized by CP. Closed
