### ISSUE TITLE
LUA errors causing game to "freeze"

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/courseplay#2340]
by freeze, i mean that it stop responding to all input. the game stilla ppears to be running, asd the graphics works, but no key, nor the mouse, work. 
```
D:/Documents/My Games/FarmingSimulator2017/mods/ZZZ_Courseplay/mode2.lua:538: attempt to index field 'acDirectionBeforeTurn' (a nil value)
Error: Running LUA method 'update'.
```

got about 20 pages of that in the log: 
https://drive.google.com/file/d/0B6wl084zbNzmRDBnczNleENld3M/view?usp=sharing
(github said was too big)

**Comment by pvajko** [comment]
First of all, you are using version 71, we are at 205 now. 
Second, there may be 20 pages of CP errors, but there are another 20000 pages of other errors in that log from various mods.
Try disabling all mods, update to the latest Courseplay version and report back if you still have problems.

**Comment by Commissar0617** [comment]
yeah,t hat fixed the freezing. just had no idea there was a new version, as there is no way to find such out, version numbers are nto listed anywhere
errors are related to some trailer or such mode, where modder did not impelent tension belts properly. my problem, not yours.
