### ISSUE TITLE
why is "Wende auf dem Feld" so wide away from the filed-border?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#2341]
why is "Wende auf dem Feld" so wide away from the filed-border?
as you can see on the pic, when i harvest straw with the loadingwagon and i set "Wende auf dem Feld" the traktor drive backwards a long time ago, more than i must, and than he drive the circle many meters away from the border.
![wendeaufdemfeld](https://user-images.githubusercontent.com/24860501/31114236-555360ca-a81d-11e7-80ee-5bbc27e22083.jpg)
i have version 01.0205
lg
andreas

**Comment by andreasthu** [comment]
Sry, filed-border means field-border.
Is there ev a offset chancing to the border?
Or maybe in future we became an offset to chancing?
Lg
Andreas

**Comment by andreasthu** [comment]
Sry closed not will

**Comment by pops64** [comment]
This is so to ensure that the entire tractor stays with the field. Because the tractor is not has skinny has the line. If you want the maneuver to perform faster increase reverse speed. Other wise there is nothing here that we will fix or adjust. Closed

**Comment by andreasthu** [comment]
This is a pity, but not an armageddon :-)
I had this question, while in earlyer versions the loaderwagon driver drived not so long backwards and in the turnmanover he reached the fieldborder or near by this.
As i saw this yesterday that the turn was so wide away i thought this was a new feature and is to setting.
Lg
Andreas
