### ISSUE TITLE
Leveling and compacting Problem

### ISSUE THREAD

**Issue by Madgamer1022** [Courseplay/courseplay#2342]
I have a problem with Leveling and compacting mode on Courseplay. I watched several videos on how to use the Leveling and compacting mode but every time the tractor reaches the Pause point it waits for me to select continue driving on the HUD. How do I solve this? Also I tested It with no other tractors on the map and it still waits for me to continue driving? 

Help please?

**Comment by Madgamer1022** [comment]
I have been trying to figure this out for the past four hours and I am ready to pull the hair out of my head!
Is this a bug or am I missing something?

**Comment by spidypiet** [comment]
is there already chaff or grass in the bunker

**Comment by Madgamer1022** [comment]
Yes I also tested it without silage.

**Comment by spidypiet** [comment]
try to disable traffic on the map

**Comment by Madgamer1022** [comment]
Nope. It worked the first time around the course but the second time it stopped.

**Comment by pops64** [comment]
Pictures of how you have your course setup. And or video of it running

**Comment by Madgamer1022** [comment]
Ironically while taking pictures i figured it out. You have to have traffic off while the bunker has chaff in it. 
Thanks spidypiet!
