### ISSUE TITLE
fieldwork pathing with plows

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/courseplay#2343]
it seems my age-old nemesis issue persists.. the turning circle. seems that when you have a tractor, with a tight tuning circle (i.e. cat challenger or an articulated tracts), hooked up to an implement, couseplay seems to have issues pathing, if i set the turning circle larger, courseplay backs up, and jackknifes. ... too small, and it spins
https://steamuserimages-a.akamaihd.net/ugc/889882349880931159/F6A9804B798A06174459243F6D8705934F717224/
https://steamuserimages-a.akamaihd.net/ugc/889882349880945242/2C3E925B4F911669D6689F629811A0F4F8B8FCF4/
https://steamuserimages-a.akamaihd.net/ugc/889882349880945242/2C3E925B4F911669D6689F629811A0F4F8B8FCF4/

**Comment by Commissar0617** [comment]
perhaps course generation needs to take into account turn radius, and do an every-other arrangement, and go down, and come back up?

**Comment by pops64** [comment]
With the turning radius is to set a specific number. All Giants tools and dlc work most mod tools work with the radius set small adjust are fine any large adjustments probably will break CP. If it is not working please provide the mod name. Also look at #2231 I believe there is another mod that behaves like this and instructions for fixing are included on that issue

**Comment by Commissar0617** [comment]
well, the tractor is a slightly modded version of a stock tractor... and the plow is the JD_2720 disk ripper... 
 it navigates okay, if i tell it to stop,a nd then go to the next point. honestly, im surprised, it should behave just like a cultivator... or any jointed tool
i'll try the fix for the claas

**Comment by Commissar0617** [comment]
okay, i tried the fix for the lua file... still want to do a three point turn. i set turn on field to deactivated... now it turns better.... idk

**Comment by pops64** [comment]
You have the apply fix to the tool and not the tractor. If it doesn't reverse properly there is another variable that have you to use has well. It is listed in the comments of that lua
 It is notToBeReveresed or something like that

**Comment by Commissar0617** [comment]
doesn't do a three point turn when i set turn on fiel to deactivated... 
but still ahs occasional spinning..
anmd I applied it to the tool
https://www.youtube.com/watch?v=cpQ29dxyusM
[log.txt](https://github.com/Courseplay/courseplay/files/1354202/log.txt)

**Comment by Commissar0617** [comment]
that fixed it. here's the link, if you want to add it to your list: https://www.modhoster.com/mods/john-deere-2720--2
