### ISSUE TITLE
Hide/disable pop ups

### ISSUE THREAD

**Issue by krambc** [Courseplay/courseplay#2344]
Hello everyone.
I do not know if this issue has already been addressed, if there is a solution or if it is simply not possible.

My query is in relation to Pop-ups. Is it possible to disable Pop-ups? or at least not visible with the hidden HUD?

Thank you very much.

**Comment by pops64** [comment]
If you are talking the messages above the mini map. Then no there is no option. We will review this request again when we have released CP.
