### ISSUE TITLE
filling at 'Buy all Fruits Silo'

### ISSUE THREAD

**Issue by nibukfabi** [Courseplay/courseplay#2345]
Is it possible to fill a trailer with the 'Buy all Fruits Silo' (https://www.modhoster.de/mods/buy-all-fruits-silo#description) in a courseplay course?

I want to fill the biogas plant automatically and at my test the tractor stopped at the starting point but doesn't start to fill the trailer. Unloading works fine. I tested it with a standard trailer.

Or does course play have a problem with the function 'press R to fill'?

**Comment by wakka79** [comment]
So I had this problem too after updating today. 

I have a 'transfer course'. I move from one silo to another. 

I set up this course to fill at the start of the course at one trigger, and then unload automatically at the next trigger. Now I have to manually fill the trailer at the silo when I start the course. This was working fine until a couple of days ago and has only recently changed.

Do I have to redo the courses post the updates that you guys have done? I dont think that I have any errors in my log. 

Thank you in advance.

**Comment by pops64** [comment]
@nibukfabi If it isn't working then I guess CP doesn't support this trigger. @wakka79 Please don't post issuse on someone else's issuse thread unless it is the same bug. So unless you are also using this mod please create a new issue. Sumbit a viedo of what mode1 is doing incorrectly or pictures.
