### ISSUE TITLE
Naming course: "C" closes dialog 

### ISSUE THREAD

**Issue by davidhunt135** [Courseplay/courseplay#2346]
Hi,

I am running the latest version of FS & courseplay. When I save a course if I try to have a "c" in the name it closes the dialog and saves the course. If there is only 1 "c" i can get it to work by typing the rest of the name first then the c last which will then save with the correct name but more than one c isn't possible. 

Nothing shows in my log file as an error.

Thanks

**Comment by pops64** [comment]
Merging this into #1829
