### ISSUE TITLE
Download location

### ISSUE THREAD

**Issue by Extarys** [Courseplay/courseplay#2347]
Hey there!

Where can I get the official zip file for the v5?

I can't seem to find it, thanks!

PS awesome work!

**Comment by pops64** [comment]
https://courseplay.github.io/courseplay/en/installation/index.html. CP still hasn't released it is only the dev version

**Comment by Extarys** [comment]
Sot he `FS17_CoursePlay5.zip` file doesn't exist? :P

**Comment by pops64** [comment]
We do not have a zip already made for the dev version

**Comment by Extarys** [comment]
I see, the doc just made the confusion. Thx.
