### ISSUE TITLE
Game lags while pathfinding

### ISSUE THREAD

**Issue by Kogehame** [Courseplay/courseplay#2350]
Log: https://gist.github.com/Kogehame/1a64592ae00cfd4855e0998cc74ae673

When finding a path to the combine, it lags for about 5 secs, I tried it with no mods, it does it too. I tried turning off automatic pathfinding, didn't help.

**Comment by pvajko** [comment]
You are using the outdated version 185. This should have been fixed in 1.00206.

**Comment by Kogehame** [comment]
Thanks, I'll update.
