### ISSUE TITLE
Milk trigger placeable problem with courseplay

### ISSUE THREAD

**Issue by Xmen81** [Courseplay/courseplay#2353]
Hello

If I drive with a Kotte Barrel (Mod) or truck to the milk trigger is not filled up simply continues (Courseplay liquid transport)

If I drive with a Kotte Barrel (Mod) or truck to the milk trigger is not filled remains (Courseplay loading at the starting point)

Water transport works perfectly also all other things run well (Fabrikscript etc.)

Thank you !!! Would look for an answer.

**Comment by pops64** [comment]
Please follow https://github.com/Courseplay/courseplay/wiki pay attention to step two
