### ISSUE TITLE
Getting Splines from Courseplay Courses

### ISSUE THREAD

**Issue by PromGames** [Courseplay/courseplay#2356]
Hello,
I have got splines to import from customdefinitionfields and it is no problem because the (Y) terrain height is defined in the XML.

I also have got splines to import from courseplay courses, however this is more complex as the file doesn't have the (Y) only two dimensions. 

Will be difficult to add also the terrain height (Y) to the course or get the course in  customdefinitionfields format, means with the Y pos?

I can not remember if we can continue doing custom fields borders without scan. Just driving. Then I get directly the height.

Thanks

**Comment by pvajko** [comment]
No, it wouldn't be difficult, it's just work. I see you have quite a few forks, don't you want to add this and create a pull request?

**Comment by PromGames** [comment]
I am not as experienced as you in LUA scripting and courseplay mechanism. I can try but I am sure I will need help.
My big knowledge and my forks are in windows applications and XML files management.

**Comment by pvajko** [comment]
Sure, if you know any programming language it's not a big deal. I think the easiest would be to find the y coordinate with the getTerrainHeightAtWorldPos() when saving the course, then add it to the XML when writing/reading.
