### ISSUE TITLE
Mode 3 needs separate variable for start at %

### ISSUE THREAD

**Issue by Mithories** [Courseplay/courseplay#2357]
Hello
I am using courseplay in FS17 with all vanilla vehicles, on the Parkers Prairie map.  I am trying to set up an overloader course.  I recorded the course in overloader mode, but when I run it with the auger wagon full or with very little (enough that it must stop to unload but not much more) it does the same thing - it slows down and unfolds the auger close to the trailer, but will not stop at the wait point to unload.  I have tried recording with debug channels 2 and 15, both alone and at the same time.  I have also tried a mixture of driving out of the field boundaries to unload, and staying inside of the boundaries to unload.  Every time, my course starts and ends in the field.  I have also tried running the course with no trailer present.  In this situation, it should stop and wait for a trailer, but still ignores the wait point.  
My start at is set to 100%, because I am running the combine and calling the overloader at specific points when I want it (to help eliminate driving in the crop).  I have tried setting the drive on % in many different places.  

This seems to be showing up in my log. A lot.
[dbg15 lp48913] 	handleAugerWagon(vehicle, PP 20, unfold=false, unload=false, 
orderName=foldBefore)
[dbg15 lp48913] 		pipeIsFolding=true, pipeIsFolded=false, pipeIsUnfolded=false
[dbg15 lp48914] handleMode3(vehicle, allowedToDrive=true, dt)

The format is different obviously...it didn't paste how it looks but im sure you get it.
Thanks!

EDIT:
I have tried 1 more time, setting up everything how I wanted.  Right after I recorded the course, I ran the overloader and it stopped to unload.  So, I kept going.  I ran a combine hopper load in to the auger wagon and sent it "home".  It did not stop to unload.

**Comment by Mithories** [comment]
That was it.  Thank you so much!

**Comment by pops64** [comment]
Leaving this open until theses two variables are separated. Has you may want to have a lower unload percent than start at % or what ever other situations you could come up with.

**Comment by Mithories** [comment]
I thought that was it anyway.  That worked for a while, but now it has started driving past the waitpoint again.  I tried reversing the numbers, setting them lower, setting them identical...

**Comment by pops64** [comment]
Give me a video please. Make your using the current version of CP. Make sure start at % is below the current fill percent to stop.(Drive on doesn't effect offloading in mode3) I know in earlier version mode 3 did have issues.

**Comment by Mithories** [comment]
How can I upload the video here for you?  10MB is pretty small for a video...

**Comment by pops64** [comment]
Dropbox or YouTube. GitHub can't do viedo

**Comment by Mithories** [comment]
https://www.dropbox.com/s/xcog7rqgtg4dnmc/Farming%20Simulator%202017%2010.15.2017%20-%2010.11.25.01.mp4?dl=0

**Comment by pops64** [comment]
If your using version 01.075 that is your problem. That I believe was before the fix to mode3. Sry it has hard to tell. Please update to the most current version

**Comment by Mithories** [comment]
Where can I get the current version?  On the bottom of my courseplay window it says V5.01 .00076.dev

**Comment by pops64** [comment]
That is the version you are using. http://courseplay.github.io/courseplay/en/installation/index.html

**Comment by Mithories** [comment]
The only version available at that link is the developer version.  Is that all that is available right now?  I have not been able to find a real answer about that yet.

Also, here is the second video.
https://www.dropbox.com/s/pip6n2evzcmxmdp/Farming%20Simulator%202017%2010.15.2017%20-%2013.04.54.01.mp4?dl=0

**Comment by pops64** [comment]
Yes there is no release version for CP

**Comment by Mithories** [comment]
Well, I downloaded the dev version from the courseplay site.  That seems to have solved my problem.
Sorry about that - I was under the impression I had the latest version.  
I will update if something goes wrong again.
Thanks pops!

**Comment by pops64** [comment]
Closed #2909
