### ISSUE TITLE
course generation with oddly-shaped fields

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/courseplay#2358]
https://steamuserimages-a.akamaihd.net/ugc/876372572830287948/C8E1C56BB2A6DEADD19E115A2FE7E258373EA027/
https://steamuserimages-a.akamaihd.net/ugc/876372572830287630/FBCC33C13BB0895C7B5261923D540C641ED2B144/
 basically, when you have a field, that has a non-field area in the middle, courseplay tries to route straight through the middle section, albeit, with no work. would work far better if course-play routed around the section, rather than driving straight through it. might also occur on unusually fields, but i'm not sure. 

in any case, should be simple, from a coding logic perspective, to take the coordinates, and add a detection when creating courses.

**Comment by pvajko** [comment]
1. if you are talking  about an island within the field, then yes we are working on it.
2. looking at your screenshots though, it looks like it is just a 'peninsula', not completely surrounded by the field. The new course gen (select vehicle position or last position as starting location) can handle that situation.
3. it is probably more complicated than you think but hey, this is an open source project and  contributions are welcome ;)

**Comment by Commissar0617** [comment]
> it is probably more complicated than you think but hey, this is an open source project and contributions are welcome ;)

would love to, i just don't ahve all that much experience. i can run servers, but i only took a couple semesters of CS,a nd that was all java. :)

>looking at your screenshots though, it looks like it is just a 'peninsula', not completely surrounded by the field. The new course gen (select vehicle position or last position as starting location) can handle that situation.

more or less. ill try that then.

**Comment by Commissar0617** [comment]
aand... it sure does. thanks.
