### ISSUE TITLE
Mode 1 (Grain Transport) doesn't stop to load at start

### ISSUE THREAD

**Issue by Mithories** [Courseplay/courseplay#2361]
Hello,
I feel like I'm clogging up your issues forum here since I just posted something about another issue, but I know that its better to start a new issue than post there and I have looked at several posts with similar problems to no avail...

I am trying to run my overloader course to and from the combine (which now is working wonderfully) and dump in to a tipper.  I have tried placing the tipper at the edge of the field, in the field, and outside of the field completely, and it does the same thing.
It will not stop at the beginning to be loaded.  For a while, it was going to waypoint 4 and waiting, and now it is moving on at turn speed all the way to the silo and loading there (My dump pit is located underneath the silo loading point.  I thought this was the problem but it was working fine for quite a while.).  

Like I said...this is very strange as it was working just fine before and I didn't change anything on purpose.
I am using all vanilla vehicles on the Parker's Prairie map.
[log.txt](https://github.com/Courseplay/courseplay/files/1377648/log.txt)

**Comment by pops64** [comment]
#2051

**Comment by Mithories** [comment]
So this issue has not been resolved yet, or am I misunderstanding?

**Comment by pops64** [comment]
if you click on #2051 you will see that you produced a duplicate has stated in https://github.com/Courseplay/courseplay/wiki which you should check before producing any bug reports

**Comment by Mithories** [comment]
Ah, I see now.  I had started a new one because that one had been inactive for a while.

I see now that there is new activity on it.  I apologize for the spam.

**Comment by pops64** [comment]
Yea always post on the original thread even if it looks inactive. We are super busy and working on things when we have time
