### ISSUE TITLE
Manure Shop Placeable and Filltrigger Tools mods support

### ISSUE THREAD

**Issue by SuBerPL** [Courseplay/courseplay#2363]
Can you add support for 'manure shop placeable' and 'filltrigger tools' in mode 9? It will be work like this mode in FS 15. Manure is filling up by press R with using 'filltrigger tools'. I hope you understand me, my English isn't very good :)

**Comment by pops64** [comment]
Mode9 is only for heap filling. So if it involves hitting the R the answer would be no. If you are talking about mode 8. Yes when we get time we will start including other non giants trigger support to this.
