### ISSUE TITLE
Obstacles in fields

### ISSUE THREAD

**Issue by A-Rimmer** [Courseplay/courseplay#2370]
Is it possible to add a "driven circle" around an obstacle in a field to the user made boundary of a field, then get the course generator to generate a fieldwork path that doesn't drive withing the circle to avoid collisions?

**Comment by pvajko** [comment]
This one of the most wanted features and we are working on it (see also #2319). 
Be patient, it'll come.

**Comment by pops64** [comment]
On out Todo list Closed
