### ISSUE TITLE
long loading save

### ISSUE THREAD

**Issue by magicmana** [Courseplay/courseplay#2376]
Hello thanks for your great work.
I have a suggestion.
I'm playing on a big map  (CHERRY HILLS SEASONS 2017 FOR ALAN JONES). 
the  fields area is near 30 to 130 hectares ,
when i  create courses  for  plow , courseplay make  less than 5 seconds for generate.
but when i save it  i have some  coursestoragexxx.xml with 10000 waypoints.
when i start a fs17 savegame , the game make near 10mn to load savegame.
when i remove all big  generated coursestoragexxx.xml  the game make 1mn to load. 
I think  it's should  be fine to  have a "quick save"  option who  save  only parameter and generate  course on the fly.
regards

**Comment by pops64** [comment]
This is something already on our list to look into. Closed
