### ISSUE TITLE
Align Waypoint Feature. Nil Error

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#2377]
I suspect a bug in the new options for plowing.  I set up the course first without "plow past the field" and when I started it the tractor would not move.  I could not tab to other vehicles. The only thing that worked was to save and exit. Once the game was back up I tabbed through the other vehicles and all the courseplay vehicles and all the hired worker vehicles had started making odd movements. Combines started skipping whole sections of the fruit.  Sowing machines started circling etc.  I tried creating another plowing course only to have it all happen again.  Please tell me how to debug this.  I have attached my log.
[log.txt](https://github.com/Courseplay/courseplay/files/1385093/log.txt)

**Comment by pvajko** [comment]
Turn off the align first waypoint option and see if that helps.

**Comment by lcc1211** [comment]
That seem's to have been the issue.  Too bad I can't use the align feature, though.

**Comment by pvajko** [comment]
Will make it work, no worries.

**Comment by pvajko** [comment]
If you can run it with debug channel 14 and post the log that would help.

**Comment by lcc1211** [comment]
I hope you don't need it to run for long, because as soon as I start it the game freezes.
[log.txt](https://github.com/Courseplay/courseplay/files/1385124/log.txt)

**Comment by pops64** [comment]
Edited title for clarity. You may also want to clean up your mods. I think the class is producing a call stack error. Not related to the CP error

**Comment by pvajko** [comment]
Try with 2.0010 or later and report back.

**Comment by lcc1211** [comment]
Looks lilke I'm back in business. No more freezing up.

**Comment by pops64** [comment]
Alright. Closed
