### ISSUE TITLE
Courseplay doesn't show owend field

### ISSUE THREAD

**Issue by Aramet01** [Courseplay/courseplay#2379]
I just startet on the conrbelt map an courseplay doesn't show field 35, why is that? Field 35, 49 and 50 are owend by start up!

**Comment by pops64** [comment]
Pic of the map zoomed in on 35. Is the sport on the field that can't be worked? Is this spot under the number for 35?

**Comment by Aramet01** [comment]
i checked the map earlyer today and i found out that field 32 is a bit in to field 35 so that clould be the issue ! i will check tomorrow.

**Comment by Aramet01** [comment]
there  is no spor ore something the problem is that i don't see field 35 i the fiel list in the courseplay hud so i cant use courseplay on 35. 
![field 35](https://user-images.githubusercontent.com/30658556/31660151-caf8abea-b336-11e7-8b7e-bb9a5301f358.png)

**Comment by Maxcdr** [comment]
There is a workaround:
1. Record a course which drives around the field borders
2. Save this course (e.g. "Field 35 border")
3. In "Field work" mode, you can use this recorded course to use field 35

**Comment by Aramet01** [comment]
sure thats the other option :-)  i think that it is strange that the field dosen't show up in the list!

**Comment by Maxcdr** [comment]
I think the issue comes from the map mod, not Courseplay...

**Comment by pops64** [comment]
Is there a gap in between the two fields? There is a way to get CP to still to it

**Comment by Aramet01** [comment]
yes between field 32 and 35 is a gap/way

**Comment by pops64** [comment]
#2317 Follow that end part of that issue. Don't reduce it to much. And on larger fields the smaller the scan size the longer it will take. Turn off auto scan while doing this. Custom scan 32 and 35 so you won't have issuse in the future
