### ISSUE TITLE
mode1 stops loading while fieldmissions

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#2380]
hello guys
i play cp in version 5.02.00010, and hat seen, that an courseplay driver who drive with mode1 (fill at the grain silo and sell fruit, stops filling, bzw was not filled when i drive a fieldmission.
the trailer stops under the loadpipe but no grain was loaded and the tractor stops.
when i endet the fieldmission i must restart the mode1 coures new
lg
andreas

**Comment by pops64** [comment]
CP doesn't support running during field missions. Yes it works but there are other bugs that may pop up. These can't be fixed.  Has they are Giants side of programming

**Comment by andreasthu** [comment]
ok, thanks for the info
