### ISSUE TITLE
Strange algorithm of work of light on combines

### ISSUE THREAD

**Issue by Satelis250** [Courseplay/courseplay#2381]
When the combine collects 80% of the bunker, it exposes the pipe, turns on the orange flashing beacon, and for some reason turns off all auxiliary light. Headlamps are the only headlights on. As the bunker is emptied, at a residual of less than 80%, the working lights turn on again.
Is this a bug, or so conceived?

**Comment by pops64** [comment]
What auxiliary lights are you talking?  Are you using a mod? Pic would help

**Comment by Satelis250** [comment]
There are conventional headlights.
There are additional working lights (shine on the sides and back)
There is a headlight on the pipe for grain unloading.
Here is additional lighting and goes out, at a time when the harvester wants to unload it.

**Comment by MartinGrisotto** [comment]
I observed the same. Pure aestethic thing, but i admit it is happening.

**Comment by Satelis250** [comment]
Now, I'm not the only one who noticed this! :) I agree that the bug is not critical, but it looks like this during the night work is not beautiful.

**Comment by BenB78** [comment]
I've noticed too - not just on combines, but on tractors also. If I turn on the "beacons on always", the work lights turn off. Every tractor, every time. I haven't said anything because I figured you were busy with bugs that were more important.

**Comment by ThomasGaertner** [comment]
try with 00011 or higher and report....

**Comment by s1100** [comment]
Yes, it works by me now

**Comment by BenB78** [comment]
Well that was easier than I thought it would be. :) Looks fixed to me. Good work!

**Comment by pops64** [comment]
Closed. Thanks
