### ISSUE TITLE
Few ideas

### ISSUE THREAD

**Issue by MartinGrisotto** [Courseplay/courseplay#2382]
1. Is there a possible way to better handle corners when using headlands? When taking sharp turn, tool or combine leaves a bit in the corner. Tractor/combine should go a bit wider, and then compensate with back/forth, as is goes over done part of the field anyways.

![1](https://user-images.githubusercontent.com/10392883/31633266-17870082-b2c0-11e7-9c38-ac26e27fd659.jpg)

Would it be possible by detecting the difference in angle when taking a corner and applying offset opposite to the direction of driving, i.e. when taking left curve, add offset to the right? 

Or make tractor/combine turn later?

What is vital and important to notice is that only curve that goes  towards the field is the problem. If tool/combine takes curve that goes outwards, it cuts into the corner and doesn't leave ny part of the field.

2. When using overloader, and set some high field speed, the overloader tractor tend to overshoot standing combine. Is there a way, the overloader will detect if combine is standing still and reduce speede earlier than approaching to the combine?

**Comment by pops64** [comment]
Use the new course generator to fix suggestion. We look into the second when we have more time.  Closed for now

**Comment by pvajko** [comment]
If you select current vehicle position or last position as the starting location for the course then you can select Turn maneuver for the headland corners. Works for combines at the moment but we are working on extending it tractors with implements.
