### ISSUE TITLE
Headland-Tractor move infront of combine and park

### ISSUE THREAD

**Issue by JLConradie** [Courseplay/courseplay#2385]
Hello....

Thanks for a GREAT mod.
Just 2 issues.

1. While Combine is doing headland and finished offloading onto trailer, the tractor moves right in front of the combine and blocks it. This only happens if Combine empty's first before Trailer fills. If trailer fills before combine empty's the tractor does the correct turn to the left and off to dump.

2. On end of field if combine finish offloading and only if tractor/trailer is full, the tractor moves into combine. If combine empty's first before trailer reaches fill level the tractor does the right move and turn to the left and park at the back of combine. I must add that this only happens if crops to the left of combine still needs to be cut/harvested. 

Request:
Can't there be just one turn, always to the left away of combine, park at the back, then decide what to do stay or dump, depends on fill level, instead of multiple turn procedures.

Regards
Louis Conradie

**Comment by JLConradie** [comment]
Thanks for the quick reply. 
I'll put some photo's together. 
Courseplay downloaded yesterday. 
Version 5.02.00010
Farmsim 2017 Version 1.4.4.0 Big But

Log file Clean. courseplay fine. Its an issue with combine and tractor/tipper turn procedures.
I reinstall version 5.01.00201 and it worked fine. 
Conclusion: changes made since 1 Oct upto 17 Oct went wrong.

Regards Louis
Nice Evening.

**Comment by Aramet01** [comment]
there is also the problem when i use the potato harvester the tractor parks to close to the potatos so the harvester on his way back stops on the tractor and does nothing.

**Comment by JLConradie** [comment]
![turn the correct way](https://user-images.githubusercontent.com/32715611/31862077-71c3f4fc-b738-11e7-893b-c88803cf9629.png)

The top picture shows you the correct turn. Crops to the right. Tractor turns left.

The bottom picture is the wrong turn into combine. Tractor turns right.
=> Using the same turning procedures in two different scenario's
Switching state 3,1,0

Changing the beginning of the dump route defeats the object. 
Thank You! Hope it make sense.

PS.  Its the Deutz Fahr Series 9 Log.
       But any tractor reacts the same way.

![turn the wrong way](https://user-images.githubusercontent.com/32715611/31862076-70d4fe38-b738-11e7-9bed-df84173f5786.png)

**Comment by pops64** [comment]
Yea the 2nd pic the tractor isn't parking but is heading towards the unload course. Ill look at the logic but I remember the tipper is suppose to wait until the combine is out of the way before proceeding to unload when it hits 100%. For now try to avoid situations where the tipper fills to 100%

**Comment by JLConradie** [comment]
I looked into the code  "Mode2.lua" as well and saw that the tractor suppose to wait but it does not.With parthfinding ON I saw that the tractor on its way to the combine runs along the uncut crops till it reaches the combine "Message - In Traffic". mmmm You just cant leave this workers alone. lol
Thank You

**Comment by pops64** [comment]
Yea path finding has introduce some bugs into mode2 that we are constantly trying find. Mode2 is a beast compared to the rest of CP. Does this occur with pathfinding off?
