### ISSUE TITLE
multiple equipment lane based course generation add refill course

### ISSUE THREAD

**Issue by mdbguy** [Courseplay/courseplay#2386]
Thank you all for continuing to develop Courseplay.

Fantastic addition of lane based course generation.  Enhancement request - scenario is using multiple seeders with lane based course, would like to be able to add seed refill course.
So far when I attempt to add the refill course it appears to remove the lane based offset option (center, left, right) and am required to manually scroll the offset value in meters.

**Comment by pops64** [comment]
Make sure the multiple tools option is still on the number of tools. I think the way it is code it will reset this number on adding courses. Just set it back to the number your using without generating a new course it should work normal

**Comment by mdbguy** [comment]
Tested and confirmed it does reset when merging/appending a second course.  Just re-select number of equipment again and works great.
Using Courseplay v5.02.00010
Just a note for others that may read later - lane based options work with older generated courses as well for same width and number of equipment.
Closing issue.

**Comment by pops64** [comment]
Leaving this open until this is improved. I'll look into this weekend.
