### ISSUE TITLE
Saved course is not kept through game sessions

### ISSUE THREAD

**Issue by manierim** [Courseplay/courseplay#2389]
This is minor but...

If you load an existing course into a vehicle and then save and exit the game, that vehicle will keep the selected route on following game session.

If you just create/record a course and save it, it will not be memorized in following game session.

Currently you have to reload it. Or save the course, delete it as current and reload...

Adding on this: any temporary course is lost between game sessions. Would be a huge benefit to also somehow retain temporary courses between sessions!

**Comment by pops64** [comment]
Yea it is on our Todo list look into temp course. It probably will impact the first suggestion at the same time. I think you have to start the CP driver in order for it to keep courses between saves. Closed for now
