### ISSUE TITLE
Reverse turning BigBud DLC Corn planter

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#2396]
CP does not turn correctly with the cornplanter of the BigBud-DLC

For more info, watch video linked below

https://youtu.be/mH9sGlqexSo

First part is with 50m Turning circle,
Part two with the automatic 11m

**Comment by pops64** [comment]
Well for one the headland turn feature is only for self propelled combines at the moment. We will mark it down that this option should be hidden for non combines

**Comment by JDTiger** [comment]
@pvajko
v2.00012 Headland turns not just for combines  …

**Comment by pops64** [comment]
Sorry about that he must have pushed it overnight.

**Comment by pvajko** [comment]
I have not implemented it with offset. Can you try without offset, just to make sure it is the problem?

**Comment by JDTiger** [comment]
yip, still the same problem...

Will upload a vid of that test now

**Comment by pvajko** [comment]
More specifically, I think it is the multi tool setting. You can clearly see that it is using the non-offset turn points. 

Can we also have the log with channel 14?

**Comment by JDTiger** [comment]
Video: https://youtu.be/tLLai77QkCo (may take a couple more min to upload)

Log with Debug channels 1 12 14 in attachment
[log.txt](https://github.com/Courseplay/courseplay/files/1404119/log.txt)

**Comment by pvajko** [comment]
Thanks. This is actually two different issues:
1. The offset must be calculated differently for headland turns (actually, for any turn which is not approximately 180 degrees), so I'll have to change that. 
2. There's something specifically with that sower that is causing problems and that I can only fix if I have that tool.

**Comment by JDTiger** [comment]
Wich planter do you mean? the one from the DLC or the one wich does not reverse enough?
The second one works fine, if its used on it own...

**Comment by pops64** [comment]
The DLC one should work fine. Minus problem number 1. Unless pvajko is using a new distance calculation. But all the required stuff for the 180 turn maneuver works

**Comment by pvajko** [comment]
My understanding is that the DLC sower won't turn correctly even with the offset turned off. If that's the case, I'd need that mod to fix it.

**Comment by pvajko** [comment]
Number 1 should now be fixed.

**Comment by pvajko** [comment]
And I know, we need some more fine tuning on how far we drive forward and back but I don't fully understand what @Satissis is doing with reversing and that directionNodeToTurnNodeLength, too bad he has been too busy lately.

Thanks for testing it though.

**Comment by JDTiger** [comment]
Thanks for your help so far, i will test the headlands with two planter after breakfast.
For the DLC-Planter: main problem os, that the thing has a turningradius larger then a containership, wich courseplay does not notice/take into consideration.

**Comment by JDTiger** [comment]
The first result is in:
Yes, CP does now calculate offsets for turn with multiple implements, but the angle between the reverse direction and the forward direction is too large, so the tractor is stuck in a circle.

Video: https://youtu.be/h4WBDIs074E
Log:
[log.txt](https://github.com/Courseplay/courseplay/files/1404710/log.txt)

**Comment by pvajko** [comment]
I see. Does the other sower work now correctly with offset?

@pops64 or @ThomasGaertner, can someone explain what is the expected behavior on headland corners if I have multiple tractors? A sketch would really help what are we trying to do here.

**Comment by JDTiger** [comment]
the other one is the one from Big-Bud DLC and does not even reverse straight...

**Comment by pops64** [comment]
All DLC should work fine for 180 turn maneuver or has been made to avoid issues. Try with a vanilla tractor as well.  @pvajko The headland math will get really complicated for lane offsets.(The outside should drive further past the corner. Inside should stop short of the corner) I think headland turns should be disable for when multitools is > 1 for now. 
![untitled2](https://user-images.githubusercontent.com/10678220/31864887-18d1f5ea-b72b-11e7-8084-a3485c4ee1af.png)

**Comment by pvajko** [comment]
This is not complicated, this is actually what I implemented. And does exactly this for me.

But looking at the video @JDTiger  made, there seem to be something else going on there, it seems to want to switch from the red lane to the yellow at the corner.

**Comment by JDTiger** [comment]
Because it is a turn and symmetric lane change was activated, CP automatically switched the lanes...
Just noticed it...

If symmetric lane change is deactivated, it works just fine

**Comment by pvajko** [comment]
Well, that makes sense for the up/down lanes but for the headlands? What would be the realistic behavior here?

**Comment by JDTiger** [comment]
ignoring the symetric lane change setting... at least it would make the turns work :P

**Comment by pvajko** [comment]
So I pass this on to @ThomasGaertner , I don't want to touch that fragile stuff, I may break something...

**Comment by pops64** [comment]
The symmetric lane change in handled in turn. I'll look at where the function is called to perform this. We need some way to know if it is 90 or 180 has I think when turn is first called this function is swapped.

**Comment by pvajko** [comment]
turnInfo.isHeadlandCorner tells if it is a headland turn or not.

**Comment by pvajko** [comment]
@JDTiger can you remind me which sowing machine was stuck in a circle, with a link if it is a mod? (Only free mods please)

**Comment by pops64** [comment]
Try again with version 15 and report back

**Comment by JDTiger** [comment]
@pvajko sorry, for inactivity, i was busy irl photogrphing corn silage...
 it was the cornplanter from the BigBud DLC.

**Comment by pvajko** [comment]
Looks like this is not related to the headland turn, I think the realTurningNode of the sowing machine is calculated incorrectly and is off to the left (not centered). This problem hasn't surfaced before as the 180 degree turns at the up/down tracks don't require reversing with this very big implements as they are so wide that a U turn is always possible.
So far the theory...

**Comment by pops64** [comment]
That would make sense has the cultivators for big bug have this same issues. I believe when the tool is folded that node is in the correct place has this is the case for the cultivators it was something @Satissis was going to look into because I only put a band-aid on for the cultivators by disabling the possibility of the reverse turn maneuver.

**Comment by pvajko** [comment]
I think this is a problem with getRealTurningNode, somehow it finds only one of the 6 wheels (wheel 5) of the implement. @Satissis seems to be the one who could fix this.

**Comment by pvajko** [comment]
True, when folded, we use four wheels to find real turning node, when unfolded we only find wheel 5 on the left side for whatever reason.

**Comment by pops64** [comment]
What we could do is apply my band-aid to theses implements until @Satissis has time to look at this. I know using the rootNode works but I was not 100% sure if this was in the right spot 100% of the time. Maybe we can look at recalculating the getRealTurningNode after is unfolded but I think this is the way it works to begin with anyways.

**Comment by pvajko** [comment]
So, instead of disabling reversing why don't we just configure these to use the rootNode as the real turning node?

**Comment by pops64** [comment]
I wasn't 100% sure if the rootNode was a viable alternative for the Real TurningNode when I implemented the changes to fix the big bud dlc has this is @Satissis area of the code and I didn't want to perform major alterations with out his opinion and testing on the matter.

**Comment by pvajko** [comment]
@JDTiger could you try something for me and report is there any difference between these:
1. fold the sower still attached to the tractor, save and quit the game, restart game and test
2. fold the sower, detach, save and quit the game, restart game, attach sower and test.
3. unfold the sower still attached to the tractor, save and quit the game, restart game and test

**Comment by xDeterminatorx** [comment]
Since I am also interested in a solution to this problem, I tested all combinations of loading the game with/without the seeder attached and the seeder folded/unfolded. There is no difference.

**Comment by pops64** [comment]
Yeah it is one of the nodes that up until big bud was reliably being placed correctly. What ever is different in the big bud dlc when it is foldedbl screws up the placement. I forget excatly which node it has been very long time since this has been looked at for now just disable turn on field and other than headlands it will work fine

**Comment by pops64** [comment]
Try with version 05.03.025 or higher and report back

**Comment by pops64** [comment]
Closed #2909
