### ISSUE TITLE
Problem with 'max Turning radius'

### ISSUE THREAD

**Issue by Kitersguru** [Courseplay/courseplay#2397]
Hello,

I play CorsePlay in the Version 5.02.00012

I start the Map start amd I start the first cars and the game hangs up. in the LOG I then find the following entry:
C: / User /.../ zzz_Corseplay / register.lua: 183: track to perform arithmetic on field 'maxTurningRadius' (a nil value)

What can I do to fix the issue?

**Comment by Kitersguru** [comment]
I load up by Pastebin under dthe name "'maxTurningRadius'"

**Comment by pops64** [comment]
This is a mod conflict that can't be fixed. The mod author must install this variable into there mods in order to be Giants and CP AI compatible
