### ISSUE TITLE
New and wonderful things

### ISSUE THREAD

**Issue by Zoochase** [Courseplay/courseplay#2400]
You guys are hard at work as usual and have made quit a few additions/selections to the modes.  Do you have a thread or link explaining them?  Some are obvious, but those few....
Great work as usual.
Zoo

**Comment by pops64** [comment]
Which ones specifically?

**Comment by Zoochase** [comment]
Combine convoy
Headland corners
Align to first waypoint

**Comment by Zoochase** [comment]
And what's the difference between current Waypoint, next closest Waypoint,
and nearest Waypoint?

**Comment by pops64** [comment]
next closest selects takes into account the direction your pointing when selecting the nearest waypoint. Nearest just selects the nearest.  Current doesn't select any and uses the last waypoint it was when CP was stoped.(This waypoint one if CP hasn't ran). Combine convoy prevents Combines on the same field running mode 6 from running into each other. headland corners either will do a smooth corner or preform a 90 degree turn. Align to first waypoint tries to align the tractor or combine with the first waypoint or 2nd if in mode 2 and departing the combine for unload course.

**Comment by Zoochase** [comment]
Thank you.  Thats been helpful.  Will there be an updated manual in the
near future ?

**Comment by pvajko** [comment]
Thanks @Zoochase, yes we are not doing a great work with updating the manual or explaining new features, sometimes you can see in the git commit comments, sometimes not, I added the very basics about the new course generator but needs a lot more...

Best would be if someone in the community volunteered to update the manuals just like the translations.

**Comment by pseikoNL** [comment]
@pvajko , if you guys need some help with the manual update I can help you with that for the English part (& maybe Dutch in future if manual would be multi-langual).

**Comment by pvajko** [comment]
@pseikoNL thanks, that would be awesome, before you do anything let me coordinate this with the other devs.

**Comment by pvajko** [comment]
@pseikoNL if you like to please go ahead with the English manual update, it will be a great help for the CP community.

The easiest for now would be if you created a fork of the Courseplay repository (if you haven't done so) and check out the gh-pages branch, that's were the manual is, make your changes and then create a pull request. If you need help with the github workflow PM me.

If you need help with explaining how CP works, please open a new issue for manual questions and the devs will try to answer them there.

Thanks!
