### ISSUE TITLE
tractor unable to move pile with leveling and compacting

### ISSUE THREAD

**Issue by gerardtt1998** [Courseplay/courseplay#2401]
I have filled up many bunkers with succes using courseplay, up to 1.5 million liters, but lately i've been having problems with the leveling and compacting function. I'm using reverse unloading. The tractor drives up to the pile that's just been unloaded, tries to push the chaff but then quickly moves the blade all the way down, stopping the tractor altogether (normally this would happen at the end of the bunker). Then it drives forward and tries it again and again. Instead of 1.5 million liters, i can put in only around 200.000 liters before the pile is too much to handle for my leveling tractor. Below are some screenshots.
Mods:
Westbridge Hills
Krone big x 1100
floodlight trailer
inspect17
cp version: 5.02.00013.dev
![fsscreen_2017_10_22_20_55_50](https://user-images.githubusercontent.com/32765051/31865297-1dddaa74-b76d-11e7-82df-cabb776a9b79.png)

![fsscreen_2017_10_22_20_55_56](https://user-images.githubusercontent.com/32765051/31865301-2d878dc8-b76d-11e7-8da5-4f663f5a6ff1.png)

**Comment by gerardtt1998** [comment]
I used 47000 liter tippers when the problem occured, and switching back to 31000 liter tippers has solved the problem for now. Strange thing is, it used to work with 47000 liter tippers, so i don't know what went wrong.

**Comment by pops64** [comment]
It is not prefect system. It is really hard for CP to perform the task. Try one of the other modes. Leveling and Compacting, Through mode

**Comment by evybart** [comment]
1 tip drive not too fast into the silo when he push up  the chaff mine tractor drives 16km/h when he push the chaff upo grtz

**Comment by Symbob** [comment]
I've found the Filling Up mode works much better and faster than the levelling and compacting mode.  This will fill the bunker to its full capacity.  All you need to do when it's full is just spend a little time compacting before you blanket the silo.

**Comment by pops64** [comment]
inactivity
