### ISSUE TITLE
SUGGESTION:  New Headlands Maneuvers

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#2402]
@pvajko I really like the results I am getting using the headlands generator while using a a cultivator or a sower.  They work well on both right and left turns around corners.  May I suggest, though, that making a left turn with a combine and a large header be adjusted?  Could it not turn sooner?  It is missing fruit roughly 5 to 10 meters in length.  Could it maybe make the left turn, reverse several meters and then continue on?

**Comment by pvajko** [comment]
Thanks, glad you like it.

There's nothing in the algorithm that would prefer right turns over the left, could you post a screenshot or video to show where exactly is the fruit missed? Is this vanilla equipment or a mod?

**Comment by lcc1211** [comment]
The map is the Westbridge Hills mod from Modhub, but the combine is the same if you're using vanilla or mod.  The fields where I use the maneuvers are 1, 3, 4, 13 14 & 18.  Also 13, but I expanded that myself and made so there are no left turns necessary.  Attached are screen shots
![20171023220515_1](https://user-images.githubusercontent.com/24764870/31921799-3386fa56-b83f-11e7-94d5-061da2671a7d.jpg)
![20171023220813_1](https://user-images.githubusercontent.com/24764870/31921800-33983514-b83f-11e7-9ba2-122aad39a23a.jpg)
![20171023221055_1](https://user-images.githubusercontent.com/24764870/31921801-33a9fdb2-b83f-11e7-8546-c8c7261e8f57.jpg)


 of what I mean.

**Comment by pvajko** [comment]
I don't think it is the left turns, it is more like some fruit is left on the _inside_ of the turn but that is covered when the combine does the up/down tracks so you don't notice it. 

I'll think about the best way to solve this.

**Comment by pvajko** [comment]
Actually, I have this implemented too:
https://user-images.githubusercontent.com/2379521/29592638-a4fc3158-87a5-11e7-892d-7285fb95db6d.PNG

This drives off the field a bit but I think it'd not leave fruit.

It's just not hooked up at the moment. I could add a setting somewhere in the HUD to select 'Corner turn maneuver reversing straight/curve'

**Comment by gec100** [comment]
Hi pvajko and thx for a hard work m8 👍  
If you have found a way how to detect edge of the field, than when combine reaches edge, it should go strait back enough to make a turn and stay in the field. Of course in the really sharp corner it would still leave some grain.

**Comment by pvajko** [comment]
@gec100 well, that's exactly what is already in there and @lcc1211 is having problems with.

Also, for nerds only: https://www.geogebra.org/m/aZmqNbW3

**Comment by lcc1211** [comment]
I think that maneuver would be great to include.  I discovered some of the larger cultivators also leave a bit uncultivated, but not as much area as is left by the combines.  I tested on several fields on Westbridge using both mod tractors with mod cultivators and with vanilla.  All the  trailed ones from 6 meters on up didn't do a good enough turn.  The exception was the Gigant 12 meter cultivator which worked with both vanilla and mod tractors.

The Amazone sprayer also ignored the turn option and left corners both left turn and right turn untouched.

**Comment by pvajko** [comment]
What do you mean by 'ignored the turn option'? It did not perform a turn maneuver? And why also? What else did not perform the turn maneuver?

**Comment by lcc1211** [comment]
It was like it did the smooth option instead of the turn option.

**Comment by lcc1211** [comment]
Working fine with combines now. I don't know if it can be done so that 6 meter cultivators and sowers will not miss parts of the field during left turns on corners.

**Comment by pvajko** [comment]
This is good enough for now. I still haven't given up on interfacing AIVE for the corners.
