### ISSUE TITLE
Only a little note for german translation

### ISSUE THREAD

**Issue by Jaguar95** [Courseplay/courseplay#2403]
With the new option to turn off the fertilizer function in seeding machines there is a little error in the german translation

Wrong: Sähmaschine
Right: Sämaschine

;)

**Comment by andreasthu** [comment]
I thini both versions are right.
Here in austria we know it as Sähmaschine.
A google search with Sähmaschine and Sämaschine find both versions.

Lg
Andreas

Ps here in austria we had in the last years a pair of writing reforms. 
Also it can bee that more versions are right.
