### ISSUE TITLE
I'm unable to make mode 9 work after upgrade to 1.4.4 and seasons.

### ISSUE THREAD

**Issue by klippert** [Courseplay/courseplay#2405]
Hello, 

I have a feeling there is a solution that i've not been able to find. 
I'm on  1.4.4.0 1.4.4RC8
with courseplay 5.02.00014 
and my bunker emptying courses has stopped working. the shovel fills to 99% and then gets stuck in the bunker. before the upgrade it would start reversing out of the bunker. 
I found that the 99% is a bug in 1.4.4, but I can't seem to find a solution anywhere.

Any clues would be greatly appreciated.

thanks,
Kris

**Comment by lcc1211** [comment]
99% full in buckets in not a bug, but rather a feature of FS17.

**Comment by klippert** [comment]
Ok. But Shouldn’t the unloading of a bunker silo still be possible with
courseplay? Ie. Shouldn’t the 99% trigger the bucket to be recognised as
full and start reversing like it did before the updates?



fre. 27. okt. 2017 kl. 00.15 skrev lcc1211 <notifications@github.com>:

**Comment by pops64** [comment]
Picture of your course. If you don't have this setup 100% correctly it will do this.

**Comment by klippert** [comment]
![fsscreen_2017_10_27_19_48_20](https://user-images.githubusercontent.com/11135710/32120341-13e75510-bb50-11e7-9d92-70b437b0b163.png)
![fsscreen_2017_10_27_19_48_36](https://user-images.githubusercontent.com/11135710/32120342-14068912-bb50-11e7-99d2-dc9dcad184df.png)

This is the course - i'm quite certain it worked before i did the 1.4.4 upgrade. i tried creating a new one like it, and it seems to have exactly the same problem. 

Any clues would be most helpful.

**Comment by pops64** [comment]
Did you update you workwidth setting?

**Comment by klippert** [comment]
Yes. I did Update the workwidth setting. I know in the picture it's all over against the wall but that doesn't seem to be the problem. If I restart the course and it drives down the middle it still does not start reversing. 

I know it's the developed version. I'll try the 5.2 stable that you just released, and see if I get the same result. 


Regards 
Kristoffer Lippert
@iPhone

**Comment by klippert** [comment]
Works like a charm! thanks and apologies for mixing the reverse driving and the turn manouver buttons... i guess i simply confused the icons.
sorry for wasting your  time, and thanks a million for the help :-)

**Comment by pops64** [comment]
No problem.
