### ISSUE TITLE
Congrats on release

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#2407]
Just saw courseplay is finally released on modhub, such hard work and dedication, thank you for all the time you have put in!

**Comment by pops64** [comment]
And for all of those intersted in the release version you can find it here https://farming-simulator.com/mod.php?mod_id=92045

**Comment by Tensuko** [comment]
So, whats better, get the newest version on GitHub or just get the one on ModHub and wait longer for updates ?

**Comment by klippert** [comment]
yep - congratulations on the release! 👍

**Comment by pops64** [comment]
@Tensuko from the readme.md file

> Please be aware you're using a developer version, which may and will contain errors, bugs, mistakes and unfinished code. Chances are you computer will explode when using it. Twice. If you have no idea what "beta", "alpha", or "developer" means and entails, steer clear. The Courseplay team will not take any responsibility for crop destroyed, savegames deleted or baby pandas killed.
> 
> You have been warned.
> 
> If you're still ok with this, please remember to post possible issues that you find in the developer version. That's the only way we can find sources of error and fix them. Be as specific as possible:

If you want a stable version download the release version. If you want bugs and new features that maybe unstable download beta version

**Comment by pvajko** [comment]
@sootysax , @klippert  Thank you for your support and patience.

**Comment by Nordvarg** [comment]
Yes, congratulations on the release :) Courseplay has come a long way since I started using it couple of years ago. Really great work everybody 👍

**Comment by Blackmankot** [comment]
Thank you for the great work! Congratulations!
