### ISSUE TITLE
[question] calculate field sice in a existing savegame?

### ISSUE THREAD

**Issue by p4r4d0xs** [Courseplay/courseplay#2411]
Hello,
as in the top written it is possible to recalculate the field sice new in a existing savegame?
I started a map 2 months Ago, but there where some fields to big. So i edited it myself with the Giants Editor. But now i CP wont accept the new size of the fields in my existing savegame. When i start a new game CP correctly recognizes the new field sice. 
So its possible to calcute the field sice again in an existing savegame?

**Comment by Brzzl** [comment]
you can try to start your savegame with disabled CP, save and exit your savegame.
load your savegame again with enabled CP and let CP recalculate the field sizes.

**Comment by p4r4d0xs** [comment]
thanks but this doesnt work!

**Comment by p4r4d0xs** [comment]
i tried aswell:
start new savegame open console and use this: CpSaveAllFields, but when i and use my savegame but with every start they load the fields new and use the old field size :(

**Comment by pops64** [comment]
Try with the manual field scanning tool. I remeber there was a internal discussion about this. And I don't think this is something we can fix. You can only edit your fields in an existing saved game with the field removal tool or a plough

**Comment by p4r4d0xs** [comment]
Where i can find the field scannig tool?

**Comment by andreasthu** [comment]
Da schau:
https://courseplay.github.io/courseplay/de/manual/index.html#hud_driverControls

Aktuellen Feldrandkurs berechnen

Siehe auch: Feldscanner

Wenn man auf einem Feld steht kann die Feldgrenze gescannt werden. Sie wird dann als blaue Linie mit gelben Punkten angezeigt (kann per an- und ausgeschaltet werden).

Wenn du diese Feldgrenze speichern möchtest, wähle eine Feldnummer für sie per /. Wenn eine Feldgrenze mit dieser Nummer schon existiert, kann sie überschrieben werden. Ansonsten kann die neue Feldgrenze der Liste hinzugefügt werden.

Jedes manuell gescannte und abgespeicherte Feld wird in der courseplayFields.xml Datei gespeichert und mit dem Savegame wieder geladen.

Lg
Andreas

**Comment by p4r4d0xs** [comment]
oh okay thanks! But with the field scannig tool they still calculate with the old sice of the field.

**Comment by p4r4d0xs** [comment]
but i found a solution for my problem! 
I start a new savegame, saved it. Than from my old savegame with the wrong sice of the field i copy all .xml files and paste them in the new savegame and now it works! 
I think the problem is in one of these files:
cultivator_density.gdm
fruit_density.gdm
splitShapes.gmss
terrain.lod.type.cache
terrainDetailHeight_density.gdm
tipColMap.grle

**Comment by pops64** [comment]
I would still use the roller to remove the field in the existing save game. You may be deleting the field from the map in GE but that may not actually be deleting the field in an existing save game. This is something we can't fix either way. Closed
