### ISSUE TITLE
Suggestion for Mode 2.

### ISSUE THREAD

**Issue by krambc** [Courseplay/courseplay#2415]
Good morning everyone.
I do not know if the subject has already been dealt with, but I'll put it up again as a suggestion.

First I explain the case and then the suggestion.

In mode 2 with two harvesters and a tractor / truck with trailer for the grain (or an overloader) working in a field, if the tractor / truck travel ends inside the field, it will detect both combine harvesters. You can set whether to empty the harvester depending on the level of filling or distance.

But if the tractor / truck route ends outside the field, I must manually assign the combine, so that with only one tractor / truck, I will not be able to service the two harvesters.

Would it be possible that apart from (or in place of) the manual harvester asign could be assigned the field in which the tractor / truck is working?

In this way, with a route that ended outside a field, could serve two or more harvesters with a single tractor / truck.

Thank you very much and apologies for my english.

**Comment by Blackmankot** [comment]
Good afternoon.
Another option is to add an item - so for transport choose manually to select two harvester.
