### ISSUE TITLE
Problem with the first mode

### ISSUE THREAD

**Issue by FlameTech-Entertainment** [Courseplay/courseplay#2417]
Sorry if this has already been written here, but there is still the error that in the first mode with the Universal Transport Pack and the Hof Bergmann Reloaded map the driver does not recognize the triggers of the individual liquids.
Both milk and liquid manure do not work with refilling or unloading.

Otherwise, as always a great job and thank you very much for it!

Analyzed with debug mode:
`[dbg2 lp96878 2976.970 s] TGS 18.480 (#2): Stop the tipper unloadDistance = 15.4 vehicle.cp.trailerFillDistance = 16.5 waypointindex = 2`

`[dbg2 lp96879 2977.001 s] TGS 18.480 (#2): Non Silo unloadDistance = 15.43 vehicle.cp.trailerFillDistance = 16.5`

**Comment by pops64** [comment]
Mode 8 always for liquids. #2231 closed

**Comment by FlameTech-Entertainment** [comment]
Ok, but also mode 8 does not recognize the triggers....

**Comment by pops64** [comment]
#2231
