### ISSUE TITLE
Won't unload into silos on Goldcrest Hills map

### ISSUE THREAD

**Issue by KClaps** [Courseplay/courseplay#2423]
Every time I attempt to have the AI unload into the silos, it moves ahead and tries to dump my grain on the ground. Is there a setting I have to adjust to stop that from happening?

**Comment by pops64** [comment]
Are using unload points? No unload points are needed for silos

**Comment by KClaps** [comment]
really? how do you make it so it unloads into the silos?

**Comment by pops64** [comment]
It knows we're the silos are if you're placing unload points this is overriding this

**Comment by KClaps** [comment]
ok. thanks for the help. do i just drive over the unload point or do i have to stop over it?

**Comment by pops64** [comment]
It doesn't matter when CP is within a certain distance it takes over speed control
