### ISSUE TITLE
Finishing the job

### ISSUE THREAD

**Issue by 53w3r** [Courseplay/courseplay#2424]
Hi, i realy like courseplay and i always thought that there is mising only one small thing. If the sugestion was already open i apolagize. 

The sugestion is that after the worker finish the job on the field, instead of him staying there he would drive to the yard.  For all of the fields i have recorded route that goes throu my yard ( pass fuel tank, seed tank, fertilazer, ... ), so after finishing the job he could just drive this route again and maybe you could implement some kind of waiting point that we could put on this route that would only activate after the job was finished on the filed.

I think that would make controling large farm eaven easier. 

Thank you very much

**Comment by pops64** [comment]
This has been discussed in the past and it isn't something we can implement
