### ISSUE TITLE
Mode 9: gets in conflict when another tool is attached at the rear.

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#2425]
CP V5.02.00018.dev
Works fine, until you have a tool attached at the rear of the tractor.
I had a fertilizer still attached from the last field work and CP always wanted the working with to be 24m instead of 3m of the shovel. Had to set it manually to 3m.

But even then it wasn't doing it's job right until I let the fertilizer to the ground some meters away and only the shovel as a tool attached to the tractor.

Would it be possible to ignore all other tools then shovels in mode 9?

**Comment by ThomasGaertner** [comment]
for me it makes no sense to use it in this way, but anyway, try v 022 or higher and report....

**Comment by AndyK70** [comment]
> for me it makes no sense to use it in this way, ...
It's only a thing of lazyness. Instead of dropping of the fertilizer/sprayer and getting a weight, just leave the fertilizer/sprayer where it is and act as a counterweight.

Just got to test v022 and it worked properly, thank you very much.
