### ISSUE TITLE
mode 2: won't unload if a shovel is attached at the front

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#2426]
CP 5.02.00018.dev
I had the shovel attached at the front of the tractor and every time the worker had to drive to tipping point at the 2nd waypoint it said "tipping point reached" and would only drive with the headland-turn-speed. 
the worker continued to drive, went through the tipping point, didn't unload, went back to the field at the same speed and stopped. 

At the time, I removed the shovel/frontloader console it went all right.

Is it possible either CP could just ignore attachments at the front, or check if it is a shovel and has something to unload, too?

**Comment by pops64** [comment]
#1896
