### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#2428]
How to use the function thresher bandage (Drescher Verband) 

LG

**Comment by pops64** [comment]
http://courseplay.github.com/courseplay which equipment are you talking? pic would be helpful

**Comment by Paul2510** [comment]
My question is how to use this feature?

**Comment by pseikoNL** [comment]
@Paul2510, what pops mean is that we don't have a ball of glass to see what you exactly mean. Take a look at http://courseplay.github.io/courseplay/en/faq/index.html and provide us with more info.

**Comment by pvajko** [comment]
@Paul2510 you can also search for tutorials on YouTube, for example https://www.youtube.com/watch?v=N_P6v2azzB4&t=37s

**Comment by Paul2510** [comment]
Many Thanks!

**Comment by Paul2510** [comment]
My problem was that I did not know how to use the function properly but the video explains the perfect

Thanks a lot again!
