### ISSUE TITLE
Mes courses ne ce sauvegardes pas

### ISSUE THREAD

**Issue by DhulFa** [Courseplay/courseplay#2431]
Mes courses ne ce sauvegarde pas, pourquoi?

**Comment by Maxcdr** [comment]
C'est en anglais qu'il faut écrire ici si tu veux de l'aide.

You have to write in English here if you want help. Please provide informations according to this page: https://github.com/Courseplay/courseplay/wiki

**Comment by pvajko** [comment]
Closed due to inactivity.
