### ISSUE TITLE
Courseplay freeze when ITRunner truck approaches unload point(Patch 1.5.1)

### ISSUE THREAD

**Issue by SavageMkII** [Courseplay/courseplay#2432]
Hello. I have found a problem that's new with game patch 1.5.1. I have my IT Runner truck with container, dolly and trailer hauling manure to a conveyor to stockpile. I have an unload point set up right beside the conveyor for the truck to unload. Until 2 days ago, when steam updated my game, it ran perfectly. Now, when the truck approaches the unload point, CP freezes, and if I still have my cursor up, I can stop the driver and everything recovers. If I don't have the cursor up, I have to force exit the game. The problem must be with the container, because the truck pulling the dolly and trailer alone works fine, while the truck and container alone cause the freeze. I don't have time right now to test with some of the standard IT Runner pack containers, but I can do that if it will help you. I have tested with the latest(5.2.0002) and with the modhub 5.02 versions of CP. Same result. I hope this is a simple fix, but will do whatever I can to help solve it! I will attach my log and links to the truck/container mods.

![fsscreen_2017_11_04_06_11_23](https://user-images.githubusercontent.com/25916123/32405284-20c4e062-c128-11e7-860b-fe9c3bd59877.png)

![fsscreen_2017_11_04_06_11_43](https://user-images.githubusercontent.com/25916123/32405285-20e30fec-c128-11e7-9d18-7feb21e95f2f.png)

![fsscreen_2017_11_04_06_13_56](https://user-images.githubusercontent.com/25916123/32405286-210521c2-c128-11e7-9122-9563011c4f36.png)

I hope the screenshots work. They show my truck and conveyor setup, if that matters. The last one shows errors in the console from previous attempts to get CP to unload with the container on the truck, not with the unit shown on the screen.

[log-01.txt](https://github.com/Courseplay/courseplay/files/1443184/log-01.txt)

Container- http://www.farming-simulator.com/mod.php?lang=en&country=ca&mod_id=88406&title=fs2017

IT Runner truck is in this private pack- https://drive.google.com/file/d/0B4y9L6qOqyOJc3k0Wm43ZjAzaW8/view?usp=sharing

**Comment by JLConradie** [comment]
Hello 
I might be wrong... and just commenting.
Question - Is the belt system default, or a mod?
Some triggers if not default does not get reorganise by CoursePlay, and then you will get the update error, freezes and so on...
Try to get a work around.. Put a Pause way in front of trigger. Do the tipping manually and activate couseplay again after tipping. That you need to do every time, unfortunately.
Not all the third party triggers are covered by/in couseplay.
Maybe one of the programmers of Courseplay can give a YouTube demonstration on how to add Triggers Manually in the code. I use to do it in FS15 like the Kalk add-on for fertilizer...  
That would be very much appreciated.

Regards Louis

**Comment by JLConradie** [comment]
Sorry I just had a look again.. The IT runner is a mod.
courseplay does not cover that trigger.
I know.. Its a bummer.

**Comment by SavageMkII** [comment]
@JLConradie - Maybe I should clarify, there is no trigger involved with the issue, I simply set an unload point(to tell CP to tip on ground) near the conveyor (The conveyor really has nothing to do with it).

**Comment by JLConradie** [comment]
Press F5 to see the outline of the triggers. If there are any triggers overlapping the courseplay course then an only then there could be an updating error otherwise it must work. If there are no triggers try to replace the Tip Stop in the rouse/route with a Pause. Sometimes I find it works. But.. Now you sit with a heap in the middle with the next round the tipper needs to cross or go over the heap. by the fourth or six round you have a collision. So for me the tipping in/on heaps does not work or the reverse tipping in coursplay does not work. It still needs cleaning up. Or I just don't understand it. I have given you the options. You decide.  I see you work with manure. What I did was I edited a Over loader and modify it so it can take manure. Problem solved.

**Comment by JLConradie** [comment]
It you replace the Tip Stop with a Pause make sure you activate or use Type:Grain transport(Load at start). 
It will work.

**Comment by SavageMkII** [comment]
@JLConradie, here are some screenshots to show you that there is no trigger. Now, thank you for trying to help, but you are not seeing the real problem here.

![fsscreen_2017_11_05_06_23_19](https://user-images.githubusercontent.com/25916123/32415305-1778d522-c1f5-11e7-95b9-a67b9ef40244.png)
![fsscreen_2017_11_05_06_23_34](https://user-images.githubusercontent.com/25916123/32415306-1793deee-c1f5-11e7-952c-e74c5cfccadd.png)

**Comment by SavageMkII** [comment]
I have done more testing, and can report that running a mode 1 course with an unload point(tip anywhere) does NOT work with any IT Runner units since Patch 1.5.1. I tested with the "standard" IT Runner trailer and containers, pulled by a standard tractor, and same errors occur.

I tested running a mode 1 course through the farm silo tip trigger, and that unloaded perfectly with standard and mod IT Runner units.

Then, to eliminate as many possibilities as I could, I tested on the standard map, with only CP and the IT Runner pack in the mod folder, and got the same errors.

I hope this information helps, and let me know if there's anything more I can do to help!

**Comment by pops64** [comment]
Does this same course work fine for vanilla trailer and truck. Also try a trailer train with just vanilla trailer s

**Comment by SavageMkII** [comment]
Ok I tested the same kind of simple grain load/unload course with an Unload Point for tip on ground, with everything as vanilla as possible. I had only CP in my mod folder. Everything worked perfectly.

![fsscreen_2017_11_05_10_42_00](https://user-images.githubusercontent.com/25916123/32417605-3aeaf20a-c219-11e7-8bb8-185a30d03fd5.png)
![fsscreen_2017_11_05_10_42_05](https://user-images.githubusercontent.com/25916123/32417606-3b028032-c219-11e7-84bd-b8e0e6d428a4.png)
![fsscreen_2017_11_05_10_42_22](https://user-images.githubusercontent.com/25916123/32417607-3b1c1588-c219-11e7-9e1a-7e20c2b1895a.png)
![fsscreen_2017_11_05_10_59_29](https://user-images.githubusercontent.com/25916123/32417608-3b34cc40-c219-11e7-8d60-4f0d12d94247.png)
![fsscreen_2017_11_05_10_59_36](https://user-images.githubusercontent.com/25916123/32417609-3b542888-c219-11e7-9097-1a624ea0fabb.png)
![fsscreen_2017_11_05_10_59_44](https://user-images.githubusercontent.com/25916123/32417610-3b6dc46e-c219-11e7-9f9e-dd5ac180134c.png)
![fsscreen_2017_11_05_11_00_05](https://user-images.githubusercontent.com/25916123/32417611-3b87c5ee-c219-11e7-80e1-3fac0cf7322e.png)

As you can see, the vanilla truck and trailer approach the unload point and unload properly. Then you can see I set up a conveyor to clear the unload point, and then the vanilla tractor with vanilla trailer train approached and unloaded the first, then the second trailer as it should. It was even pulling forward as it unloaded to keep unloading as the heap grew.

So it seems to be a problem only with IT Runner units. We've run into issues with IT Runner vehicles before (#1792), and solved them, so I hope this can have the same outcome. As I said before, this issue only started after my game was updated to 1.5.1. Prior to that, this course with IT Runner vehicles worked flawlessly.

**Comment by JLConradie** [comment]
@SavageMkII 

There you got it.. CP does not support IT runners .
If IT runners are included as a DLC in the game, maybe then Thomas will add it in CP.
Otherwise I think they will keep it pretty standard.

Interesting how CP works with Heaps. Basically the heap is a trigger. as Soon as you tip , it gets updated in your Savegame folder file vehicles.xml  You just cant see it with F5.
Its a transfer and destroy of the offloading crop. CP does that function as if the player is driving the vehicle. If you are driving an unsupported vehicle well... then the update cant happen and you will see update errors.

Sorry about the IT Runners.. 
Glad you found the course of the error.

Regards Louis.

**Comment by pops64** [comment]
Will still look into it. Has 1.5.1 according to the change log shouldn't have affected this

**Comment by pops64** [comment]
Closed #2909
