### ISSUE TITLE
Cirle

### ISSUE THREAD

**Issue by JLConradie** [Courseplay/courseplay#2433]
Thank you for the new update 020.  
You have done a great job. One headache less.

But now.. this happens more frequently.

![circle](https://user-images.githubusercontent.com/32715611/32406850-604461d0-c188-11e7-9c94-ace77c6da20a.png)

Changing the turn circle smaller or bigger/greater does not seem to work.
If I use a smaller tractor with tipper trailer the problem persist less.
Any other suggestions.  

Regards Louis

**Comment by ThomasGaertner** [comment]
do yo have a savegame for me to test ?

**Comment by Blackmankot** [comment]
A similar situation began to occur with tractors.

**Comment by JLConradie** [comment]
Thanks Thomas for the interest.
Somehow I cant upload zip Files. "for the save game you requested"

I'v made a study of this issue.
CP way points may still be too close to each other. behind the combine and larger tippers or tractors may miss the last way point before heading for the pipe and start to circle. "Not the case if Combine is still moving""or if tractor/tipper and combine is moving in same direction.
I know that you and your team worked on this issue not too long ago.

Discovered:
Downloaded MODS that's not set-up properly in their XML files.
CP reacts differently on different types of tippers and not the same for all.
I don't know if CP does it calculations (Turn Circle) on the Tractor or its tool.
What I can gather from the code.. its from the tool. I may be wrong.

I don't know the turn circle of the tractor or the tool. If I set it to high or too low it will miss the way point. Rather stay with the default. Small adjustments from there.

Unsupported MODS
Most Dump Truck Mods #2077, #2050 - CP has issues unloading them correctly. Also, breaks mode 9 and 10.

There you have it. I Found the culprit.

Thanks a MILLION!
Have a good one...

Regard Louis

**Comment by pops64** [comment]
This shouldn't be an issue with the dump truck mod . The error you are getting is a traffic error correct? #2177 is probably related

**Comment by JLConradie** [comment]
#pops64
I'll do.. I'll do some test with dump trucks again. I'v contested some changes Thomas made.
I'll report back. Just give me a bit of time to do the tests.
Regards Louis

**Comment by JLConradie** [comment]
Sorry must be Noticed.. changes made by Thomas.

**Comment by JLConradie** [comment]
Hi Thomas.
You may close this. No more an issue.

Thank You.
Regards
Louis
