### ISSUE TITLE
Current vechicle position: Return 1st point

### ISSUE THREAD

**Issue by Kraiu** [Courseplay/courseplay#2435]
The course generation with current vechicle position and automatic direction does not support return to first point? No matter how I do it, headland first or second the activate to 1st point doesn't do anything.

**Comment by pvajko** [comment]
Looks like I missed that. (The new course generation has been in Courseplay for quite a while, you are the first one complaining about this.)

**Comment by Kraiu** [comment]
You did excellent work with the new course generation, with the return to 1st point it will be truly amazing.I haven't played the game in a while.

**Comment by pvajko** [comment]
Is returning to the first point with headland second even a valid use case?
