### ISSUE TITLE
Mode 2 turn/reverse maneuver with x2 tools-forage.

### ISSUE THREAD

**Issue by ZeroJhd** [Courseplay/courseplay#2436]
Hi, love the mod! Have issues with chaser bin in mode 2 when using more than 1 forage harvester with new multiply tools mode. See video below.

https://www.youtube.com/watch?v=ppk1EE-JPPg

Recorded with v2.00018, also happends with  v2.00023 Havent tried 024 yet.
Game version 1.5 something (steam auto update)

**Comment by s1100** [comment]
Hello,

i think, your problem is, you have pathfinding(Fruchtumfahrung) activated.

General Settings->Pathfinding->de-activate

**Comment by ZeroJhd** [comment]
Hi,

I have tried it again with Pathfinding deactivated and saw no changes to the problem.
I have tried with x3 tools and x5 and chaser bin lined up for wrong lane each time.
Still v018, recorded 21min video with different setups if needed,

**Comment by pops64** [comment]
No this is a problem with how Multi Tools was implemented. We didn't touch the value for the workWidth which is what the tipper relies off of for turning. Could you try increasing the harvester workWidth to what the multiTool states it is using and see if that works.
