### ISSUE TITLE
Mod 10.  Very large volume of blade

### ISSUE THREAD

**Issue by BowenMayn** [Courseplay/courseplay#2440]
Hey. I'm having a problem with mod10. At work the mod blade rakes 18000l, and when the mod10 is off, 6000l. I tried with different tractors, the stock blade.

**Comment by pops64** [comment]
This isn't a issue. This is a fix that was implemented in version 1.4 of the game. Giants changed how silage worked and one of our fixes was to increase the volume of the blade while CP was running to assist CP in perform the mode 10 task.
