### ISSUE TITLE
Leveling tractor is not waiting untill the Silage tractor is unloaded

### ISSUE THREAD

**Issue by CriminallyInsane86** [Courseplay/courseplay#2444]
When the tractor comes from the field to unload in to the bga the leveling tractor goes to the waiting point and waits only for a few seconds, so he starts reversing to the BGA to start leveling and compacting even befor the loaded tractor has a chance to get to the unload trigger point, haven't set a waiting time in, everything was working fine on the previous version of CP now i'm on the 5.02 .00027.dev version

**Comment by pops64** [comment]
Try increasing the range at which CP detects the unloading tipper.

**Comment by dkfiremann** [comment]
And just for information, the detection range is calculated from the first point of the leveller course. 
I have currently made a change, so that the unload tractor is removed from the waiting list when it is 2x of the detecting range. 
This helps with this kind of problem. Kind of hysteresis for the detection.

**Comment by CriminallyInsane86** [comment]
i've tried increasing the range and its still the same problem i've re recorded all courses involved still the same problem (even made courses for the leveling tractor with a waiting point set to an other place (closer to the unload point/trigger for the loaded tractors) still the same problem

**Comment by dkfiremann** [comment]
So what is your setting? 
add some pictures of your courses. 
How far awsay does the unloadíng tractor drives from the bunker before backing up to it?

**Comment by CriminallyInsane86** [comment]
This is the route the leveling/ compacting tractor does (and its standing at its waitingpoint
![20171111203112_1](https://user-images.githubusercontent.com/31863751/32692921-34240c10-c721-11e7-8669-d97e43796af4.jpg)

This is where the loaded trailer starts to back up (this is the point where the trailer and tractor is about straightened out)(note there is abviously no waitingpoint set for the loaded trailer)
![20171111203143_1](https://user-images.githubusercontent.com/31863751/32692922-34461c38-c721-11e7-822c-32731edd9e6f.jpg)

This is where the loaded trailer stops and waits untill the leveling/compacting tractor stops at his waiting point
![20171111203810_1](https://user-images.githubusercontent.com/31863751/32692923-3469d632-c721-11e7-9e4c-c3f637ebe5f2.jpg)

this is the point when the leveling/compatcing tractor starts backing up (when the other tractor/trailer just started to back up to dump in the Bunker)
![20171111203834_1](https://user-images.githubusercontent.com/31863751/32692924-34bfeb12-c721-11e7-9e4a-6aa8f66e576d.jpg)

as you can see i've been able to do this with the same points for the 1st bunker it worked with out any problems but it was done with an older version of CP

the distance set for all tractors (using CP) to wait was set ad default on 40 meters,
i've tried setting it at 50 meters and more and setting it at 25 meters or less (you'll see on pic 2 i've had it set at 20 meters at that time) it had the same problem

**Comment by pops64** [comment]
Please setup your course correctly #1568

**Comment by dkfiremann** [comment]
I'm more interested in the unload tractor. How far is that tractor from the starting point in level course. 
I looks like your starting point for the level course is far far back in the bunker.  
I'm betting it is more than 75 meter from that point to the point where the unload tractor changes from forward to reverse driving.

**Comment by dkfiremann** [comment]
And use the eye to show us the route of the course, then we can see the whole course.

**Comment by CriminallyInsane86** [comment]
i have used this course all the time (like you can see bunker 1 was filled and bunker 2 was filling) then i downloaded the newer version of CP and it started and like i mentioned before i've tried to set the waypoint closer (as close as i could get it so i didn't cause a tractor to be in the way), i'm more then happy to try it again but i'm afraid it won't solve the problem

**Comment by lcc1211** [comment]
I had trouble following the guide. This guy shows how to do a good set up  https://www.youtube.com/watch?v=txpAfMgglCU

**Comment by fudoido** [comment]
i am also having this issue. my leveling course starts very close to bunker exit, leveler goes to waiting point when trailer comes near, trailer starts to run when leveler is waiting, but after a couple seconds leveler starts to run before trailer gets into the bunker and makes it stop (as if it was waiting for leveler to go at waiting point again). waiting point is not very far from bunker start point, i try both reverse unload and pass through options, increase/decrease detection range, all running machines or courseplay only, at it allways ends up doing this, leveler will not wait for trailer to go through bunker to unload. 
it wouldnt be a bad option if the trailer kept going and leveler right behind it, problem is that CP makes trailer stop waiting for leveler to go back to waiting point again, making leveler crash into trailer and even drag it out of its course, which will make trailer go outside of bunker walls when (and if) it gets able to run again after leveler go back to waiting point.

**Comment by CriminallyInsane86** [comment]
I was able to fix it just set the waiting distance for the loaded tractor trailet to the standerd setting don't change that and be sure to have the waiting point for the leveling tractor not to far away from the bunker and the point of reversing of thz loaded tractor (in my previous pics is ok haven't changed anything apart from tje distance for detecting the loaded tractors

Ps srry for the previous helpers that i didn't rzply earlier im in the hospital atm

**Comment by pops64** [comment]
Closed #2909
