### ISSUE TITLE
What about a mod is set up wrong if CP tries a 3pt turn with a trailed implement?

### ISSUE THREAD

**Issue by Timmiej93** [Courseplay/courseplay#2452]
I've tried using the [Vogel & Noot Heros 1000](http://farming-simulator.com/mod.php?lang=en&country=us&mod_id=81366&title=fs2017) from ModHub with CP, but when reversing, the tractor tries a 3 point turn, as if the implement could be raised off the ground (like a smaller plow for example). Since it is a trailed implement, this obviously fails. I've been going through the code that (I think) determines if CP will reverse with an implement, and I don't see anything that jumps out in that mod that could cause it to not behave properly. 

Are there some general things that could be causing a trailed implement to not be recognized as one that I could check?

**Comment by pops64** [comment]
Add implementWheelAlwaysOnGround in special tools. If you know how to code there just follow the format in there. I think there is in the unsupported mods issuse a tool that does this and directions are included with that.
