### ISSUE TITLE
Why is trailer not filling correctly?

### ISSUE THREAD

**Issue by SnoopBok** [Courseplay/courseplay#2453]
Hello, 

I'm using the following mod package: http://www.fsmods17.com/kaweco-radium-pack-v1-0-fs17/ 
When the tractor and trailer is driving next to the harvester, it's not filling. Although the tractor and harvester don't stop. See this picture: 
![farmingsimulator2017game 2017-11-15 19-57-49-95](https://user-images.githubusercontent.com/16392323/32854837-380631e2-ca40-11e7-8d8d-58385da382af.jpg)

But when I manually move the tractor vertically about -4.0m backwards, it's filling again. See this picture: 
![farmingsimulator2017game 2017-11-15 19-58-07-91](https://user-images.githubusercontent.com/16392323/32854919-7901c922-ca40-11e7-8bde-beb631933536.jpg)

After a while the vertically alignment doesn't matter anymore. How is this possible? Obviously it's a mod issue, but can somebody point me in the right direction to fix it? I already tried to move the _fillVolumeLoadNode_, but it doesn't matter. 

Thanks in advance :-)

**Comment by evybart** [comment]
its a silage trailer can only load silage and nothing else change the xml file and change it in bulk and load everthing

**Comment by pops64** [comment]
Yes you have to make sure the fill type of the trailer expects the fill type output by the havester. There is no check in CP for this so it will have this behavior occur. The only thing CP checks is when the tipper is in range and if the fill type doesn't match the fill type already in the tipper.

**Comment by SnoopBok** [comment]
Thanks for the help. I changed the fill type to bulk, but somehow the Radium 50 model is still having the same issue. Can somebody point me in the right direction?

**Comment by pops64** [comment]
There is no fill type bulk. You have to name every fill type a trailer accepts.

**Comment by SnoopBok** [comment]
I changed it to `    <fillUnits>
        <fillUnit unit="$l10n_unit_literShort" fillTypes="wheat barley rape sunflower soybean maize seeds fertilizer silage forage grass_windrow straw dryGrass_windrow woodChips chaff" capacity="38500" />
    </fillUnits>`

I also tried: 
`    <fillUnits>
        <fillUnit unit="$l10n_unit_literShort" fillTypes="wheat barley rape sunflower soybean maize seeds fertilizer silage forage grass_windrow straw dryGrass_windrow woodChips chaff" fillTypeCategories="silageTrailer" capacity="38500" />
    </fillUnits>`

But the problem still occurs? The trailer is filling, but when the tractors is next to the harvester at a certain point, it stops filling. It starts filling again if I set the vertical offset to -3.5m.

**Comment by evybart** [comment]
sorry when i have that sort of problem i change the fillTypeCategories in bulk and it works for my problem with the trailer himself i think

**Comment by pops64** [comment]
Then you have a different problem. It sounds like the harvest pipe can't reach all of the tipper. Has heaps are created in tippers now and if the front heap is full CP doesn't know this because the fill level is below 100. And all CP checks for is if the tipper is in range so it doesn't know to move closer to allow the pipe to reach the back. I am not to sure what CP uses for vertical offset but it should be placing the center of the trailer next to the pipe root node
