### ISSUE TITLE
suger cane overload mode or combi mode dont work

### ISSUE THREAD

**Issue by binkleystephen** [Courseplay/courseplay#2455]
the new suger cane trailers and regular trailers dont work with courseplay i am useing the modhub version

**Comment by SuBerPL** [comment]
I'm using last dev version and these trailers aren't working, too. Can you make these trailers as reloading and ordinary?

**Comment by Vanquish081** [comment]
Same problem, I suppose they will have to include the vehicleType of the A8800 as if it were a chopper.

**Comment by DevilCreator** [comment]
The A8800 works already, it works with normal trailers just fine. the only problem is that the new trailers don't work.

**Comment by pops64** [comment]
Is it only the sugarcane trailers that are not work? Trans 600 Colossus 10.000 and MF 3012 This will take some doing has they unload in a new fashion

**Comment by DevilCreator** [comment]
I have tried with every new trailer which are made to haul sugarcane, All these trailers do not work with the driving modes of Courseplay except one, Drive mode 5 doesn't have an issue with them. Which is drive mode Transfer. 

Yes true. As they don't have the same tipping mechanic as all the other trailers do. but instead use a manual unload method it sure will take a while to set it up. For now anyone wanting to use Courseplay with the sugarcane harvest. just go and use the standard non platinum trailers. These standard grain trailers do support sugarcane too and do not cause an issue with unloading or anything.  

Fyi, sugarcane wont go into the grain silo's, it's not accepted. But that's not Courseplay which handles that.

**Comment by Vanquish081** [comment]
Is true, this trailers show message "incorrect trailers for this mode".

**Comment by pops64** [comment]
Update: Version 30 works for sugarcane trailers. The transport trailers are still WIP

**Comment by binkleystephen** [comment]
minor bug i guess the defualt distance away from the harvester is 7 m i found 5 m to be perfect for normal trailers and cane trailers

**Comment by p4r4d0xs** [comment]
still dont work with Version 30. Mode 1 & 2

**Comment by binkleystephen** [comment]
yes it works

**Comment by p4r4d0xs** [comment]
how? i got everytime the message: trailer is not compatible with this mode

**Comment by ThomasGaertner** [comment]
@p4r4d0xs : its because these trailers are overloaders, use mode3 instead and they are working...

**Comment by p4r4d0xs** [comment]
but in mode 3 i cant setup drive to the sugar mill, so i need a second trailer. 
Like in real you drive with the sugar trailer to the sugarmill. 
Is it possible to setup the sugarcane trailer for mode 2?

**Comment by p4r4d0xs** [comment]
ok thanks! I found antoher problem, is the trailer is full, the rest of the sugarcane will be tip on the ground, where can be this disabeld?
https://abload.de/img/fsscreen_2017_11_19_2tzjwi.png

**Comment by Maxcdr** [comment]
Also in this case, at the end of the row when combine turns, then it is stuck:

![untitled](https://user-images.githubusercontent.com/10348839/33006696-a722536a-cdcb-11e7-9764-11c51cf4d1b8.png)

**Comment by SuBerPL** [comment]
When turning the tractor with a trailer on the field (as in the silage) it does not go straight back to the harvester. Turning goes on indefinitely.

**Comment by SuBerPL** [comment]
Screenshots for my last post:
![fsscreen_2017_11_20_15_45_40](https://user-images.githubusercontent.com/32776608/33024307-0707643e-ce0b-11e7-8609-1614672eb27a.png)
![fsscreen_2017_11_20_15_48_31](https://user-images.githubusercontent.com/32776608/33024308-07217ce8-ce0b-11e7-9859-26e9f6b5449b.png)

**Comment by ThomasGaertner** [comment]
@Maxcdr : use the latest version , it should be fixed there
@SuBerPL : for the sugarCaneOverloaders not reversing properly we are working on it ....

**Comment by Vanquish081** [comment]
Test with the last version 33 is improved, but no work fine, goes crazy when going back:

'https://i.imgur.com/2iGglgU.jpg'

**Comment by Vanquish081** [comment]
Is possible indicate that no turn in the field?

**Comment by pops64** [comment]
Were working on this.

**Comment by p4r4d0xs** [comment]
guys what did you do with Version 39?!?!? Its unplayable now.

https://abload.de/img/fsscreen_2017_12_07_2f8s3j.png
and
https://abload.de/img/fsscreen_2017_12_07_2gqsuq.png

**Comment by pops64** [comment]
@p4r4d0xs please make a sperate issue regaruding this. And follow https://github.com/Courseplay/courseplay/wiki. Unless your issue is related to Sugar Canes not working correctly.

**Comment by p4r4d0xs** [comment]
Check the second image.
The driver drives everytime at the high of the sugar harvester and ignore the pipeline

**Comment by pops64** [comment]
You produce 2 picture with a problem. And one was with a non sugarcane havester and tipper. This is not a related issuse please post in a new thread and follow the wiki

**Comment by pops64** [comment]
Just a status update. Currently I can't get CP to not reverse with theses trailers(This would be a bandaid so it would work) nor can I get the reversing function working correctly(This is the end goal because it should work but for what ever reason reverse isn't liking the course mode2 gives it once I fix the initial reason for it to not work)

**Comment by pops64** [comment]
closing this out. all issues have been fix or have a related issue that are waiting on replies to version 38
