### ISSUE TITLE
Tip anywhere function

### ISSUE THREAD

**Issue by willie2016** [Courseplay/courseplay#2457]
i cant seem to get the unload anywhere function to work right , iv  recorded course from maize field into my yard that iv name contractors yard so it has the vehicle shop and all and iv a space made with tip collisions around the outside painted down but when i reverse back while recording and unload and set unload point when i set up the tractors to follow that course they do not unload where i have the marker set

**Comment by pops64** [comment]
You have to hit the unload button before hitting the switching recording back into forward mode. Also if there is tip trigger near your unload point this will also confuse CP

**Comment by pops64** [comment]
Closed due to inactivity
