### ISSUE TITLE
Clark forklift from modhub causing Error: Running LUA method 'update maxTurningRadius 

### ISSUE THREAD

**Issue by Landykid** [Courseplay/courseplay#2458]
this issue has been fixed once before but I'm guessing there was a recent change and has made a comeback all I did was I switched on that follow me and you can see what I was present it with 

The mod https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=60659&title=fs2017

Error: Running LUA method 'update'.
C:/Users/Matt/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/register.lua:183: attempt to perform arithmetic on field 'maxTurningRadius' (a nil value)
Error: Running LUA method 'update'.
C:/Users/Matt/Documents/My Games/FarmingSimulator2017/mods/ZZZ_courseplay/register.lua:183: attempt to perform arithmetic on field 'maxTurningRadius' (a nil value)

**Comment by pops64** [comment]
This as never been fixed and can never be fixed. This is variable CP relies on and it has to be supplied by the mod

**Comment by Landykid** [comment]
yes it was it you yourself closed the conversation on the 5th of February 
where ThomasGaertner added fix Max rotation

https://github.com/Courseplay/courseplay/issues/1739

**Comment by pops64** [comment]
If you look that was a fix for max rotation this is max radius.  This can't be fixed because radius is required by Giants for all AI helpers
