### ISSUE TITLE
Mode2 doesn't work for trailed forage havesters

### ISSUE THREAD

**Issue by NexX0** [Courseplay/courseplay#2462]
Hey there,

so my problem is im using a trailed forage harvester and my tractors (mode2/3) wont drive to it.
It is recognized as a harvester but the tractors just sit at the end of the unloading course.

My workaround is that i let an chaser bin running with FollowMe right next to the Harvester.

My suggestion would be that you can set a chaser bin to always follow the Harvester and/or make it so you can tell a tractor (mode 2) to go to chaser bins.

This would really help with trailed forage harvesters, i can just attach a chaser bin to the Harvester and then let a tractor run in mode 2/3.

**Comment by zocke1r** [comment]
i have the same issue with the trailed sugar cane harvester

**Comment by Maxcdr** [comment]
@zocke1r Sugar cane issie is already know here: https://github.com/Courseplay/courseplay/issues/2455

**Comment by zocke1r** [comment]
@Maxcdr no that issue is about the trailers not working with courseplay, this is about the fact that courseplay apperantly cant deal with trailed harvesters

**Comment by pops64** [comment]
Trailed harvesters sometimes have to be coded into CP so it recognizes that it has a havester name of mod you are using

**Comment by NexX0** [comment]
ill tried it with this one 

> https://ls-portal.eu/de/poettinger-mex-6

 and with the smal form MF pack

> https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=81066&title=fs2017

**Comment by pops64** [comment]
Te sugar cane trailered harvester is another example of thiis

**Comment by pops64** [comment]
I am going to close this out. To fix mods with this problem please use the follow code. And insert it around line 159 in specialTools.lua
```
elseif workTool.cp.xmlFileName == 'thenameofyourmod.xml' then
		workTool.cp.isTraileredChopper = true;
```

Replace thenameofyourmod with the xml file name of your chosen mod file make sure the ` .xml ` is present and only one. We may start including some of the more popular ones into the master branch

**Comment by zocke1r** [comment]
@pops64  where do i find the download for that version the release in this git is for 2.016 the modhub has version 2.0

**Comment by Crinouche** [comment]
Thanks NexX0
It works for me.
