### ISSUE TITLE
Mode 2: After unloading, the pickup turns always into the combine causing a collision

### ISSUE THREAD

**Issue by Phantom742** [Courseplay/courseplay#2463]
![mode 2](https://user-images.githubusercontent.com/11431031/32979977-e183e7bc-cc5e-11e7-826b-2d6f3ea964fc.jpg)
After the combine has unloaded, the tractor in which the combine unloaded always turns into the combine instead of turning away. This causes a collision.

**Comment by Sythos** [comment]
Happen also to me, but only if combine is close to field head, during normal run che tractor wait the combine go along and "park" behind

**Comment by pops64** [comment]
#2456 . Please the wiki
