### ISSUE TITLE
Shovel mode - drills a path

### ISSUE THREAD

**Issue by abehnke** [Courseplay/courseplay#2465]
It appears shovel mode does not like lumpy, uneven silage in the silo. If I fill a silo at the BGP to 10% to 20% and don't bother leveling it. When using the Liebherr TL 436-7 with the Magsi Manure Fork (after silo fermenting and uncovered), sometimes it just drills a path straight down the silo - leaving silage on either side that would be easier to get.  Other times it skims over the top of the silage to the end. Sometimes it gets stuck, partially fills the bucket then backs into the wall.  I have tried different speeds and different widths etc.  Sometimes clearing shovel mode and restoring seems to help.  The load position is set fine since if I see this happening and take manual control - I have no problem getting a full bucket.

This also happens using a front end loader with a bucket.

What I do now is after uncovering the silo, I use the leveler to push the silage from both ends into as high a pile as possible.  This seems to make the shovel mode happy.

Sorry I don't have a log file for this.  But if you really want one, the next time I have a lumpy silo - I will try to get it to happen.

Using GIANTS Engine Runtime 7.0.0 (15417) 64bit (Build Date: Oct 12 2017) Courseplay: initialized 48/48 files (v5.02.00027)

**Comment by pops64** [comment]
Need to see pic of how you have your course setup with all waypoints on

**Comment by abehnke** [comment]
I used the leveler to "unlevel" the silage in one of my silos and make it lumpy.  But the shovel mode seems OK now with this.  I think most of my shovel problems happened before I had the leveler.  Silos were just loaded by the forager in a random lumpy mess (I drove them not Courseplay).  I wonder if the leveler does something to the piles of silage so that shovel mode works better?  So, it might be a couple of days before I have a fresh bunch of grass to try an unleveled silo. I will get some images of it with WPs as requested.

**Comment by abehnke** [comment]
Here is an example of a drilling a path through the silage.  As it makes trips to the far end, it struggles at times, gives up and backs up with a small load of silage.  This exact same course works fine if I bank up the silage first with the leveler. In other words, squeeze if from both ends so it is piled up in the middle of the silo.  Under this condition, shovel mode will unload the whole bunker except for maybe the last 4 scoops with no problem.  So this problem is probably only of interest to somebody just starting game with minimum equipment (no leveler).
[log.txt](https://github.com/Courseplay/courseplay/files/1491387/log.txt)
![fsscreen_2017_11_21_07_28_58x](https://user-images.githubusercontent.com/3346683/33073901-4e5a2a24-ce92-11e7-8386-e992de7b4410.png)
![fsscreen_2017_11_21_07_32_19x](https://user-images.githubusercontent.com/3346683/33073913-55bb7dfe-ce92-11e7-816a-681569f3ffe6.png)

**Comment by pops64** [comment]
Did you adjust the blade width setting on this?

**Comment by abehnke** [comment]
Yes, for the telehandler, I use a value around 3.5 to 4.0m.  Since I reported this, I have had many more weeks of experience.  I can prevent the problem by keeping any strips  of silage away from the walls.  What appears to happen is CP notices some silage near the wall and attempts to go for it but instead the bucket binds against the wall.  And as you mentioned, having the first WP too close causes an even more acute angle.  Once I arrange a good perpendicular silage pile front for the telehandler - CP can clear the entire silo with no faults. (except maybe the last bucket full).

**Comment by pops64** [comment]
due to inactivty
