### ISSUE TITLE
Game semi freeze with error 

### ISSUE THREAD

**Issue by OmniTitan** [Courseplay/courseplay#2472]
Getting this error:
Documents/My Games/FarmingSimulator2017/mods/FS17_Courseplay/register.lua:183: attempt to perform arithmetic on field 'maxTurningRadius' (a nil value)
Error: Running LUA method 'update'.

Causes the game to become unresponsive except for CoursePlay, animations still work with Vehicles moving but cannot interact with game at all. Cannot save game either.

Log file is attached.
[log.txt](https://github.com/Courseplay/courseplay/files/1487245/log.txt)

**Comment by pops64** [comment]
You have mod that is not compatible with disable this mod. And your game will run normally.

**Comment by OmniTitan** [comment]
How can I find out which mod?

**Comment by pops64** [comment]
Disable them one by one until the error goes away.
