### ISSUE TITLE
Courseplay Drivers minimap

### ISSUE THREAD

**Issue by Kodiak437** [Courseplay/courseplay#2474]
Hello,

Is there a way to have the Courseplay drivers show on the minimap?

**Comment by s1100** [comment]
![fsscreen_2017_11_21_20_41_56](https://user-images.githubusercontent.com/30638928/33093256-cfe0e00a-cefc-11e7-8edf-00aef1b0ae4e.png)
Like this?

**Comment by Kodiak437** [comment]
Yes Exactly.  Im assuming its in the menu from the screenshot but i must have missed it.

**Comment by s1100** [comment]
you can read here more

https://courseplay.github.io/courseplay/de/manual/index.html#hud_generalSettings

**Comment by Kodiak437** [comment]
Thanks Found it now.. New to the mod.
