### ISSUE TITLE
problem with mode 1

### ISSUE THREAD

**Issue by Django215** [Courseplay/courseplay#2475]
Hello.
At first, sorry for my bad english.
I have a question, or maybe a problem. 
In mode 1, my Ai-Driver is on the way to sell my wheat, or anything else. With 2 Trailers. He arrives the sellpoint, unload 1 Trailer an drive back to the Farm, with the full second Trailer. I test with mod trailer, stock stuff. with waitpoint. in 90% of all my tests the Ai-Driver unload not both Trailer. Make i a misstake? or is the trigger to smal? Or ? 

Greatz.

PS: I use the cp version from github.

**Comment by pops64** [comment]
Follow https://github.com/Courseplay/courseplay/wiki Picture of the trigger size. Also check #2231 to ensure you aren't using a mod that could cause this problem. Honestly sounds like your using a very early version of cp. Please update to CP available on mod hub. Unless you are using version 02.0001 or higher

**Comment by Blackmankot** [comment]
#2077 I described this problem in May. At the moment nothing has changed ... A new problem has been added. If the transport is unloaded with one semitrailer and at that moment to get into the transport, unloading does not end and part of the cargo remains in the body, the traffic continues.

**Comment by pops64** [comment]
Your problem has to deal with the use of dump trucks. I haven't been able to figure out why CP skips over the first one. This appears to be a different issue but I am still lacking information

**Comment by Blackmankot** [comment]
@pops64 Here is a link to the map - https://yadi.sk/d/ZNN0ZonE3Q3jzS

**Comment by aviator64** [comment]
His second issue is one I have seen consistently as well.

When you tab into a tractor while it is in the middle of unloading, it will immediately stop unloading and continue the course.

**Comment by pops64** [comment]
I am going to close this out. Due to inactivity from original author. @aviator64 could you please make a new issue with steps on how to produce your error as well has a log with just debug channel 1 and 2 active
