### ISSUE TITLE
Circle issue on new map. 

### ISSUE THREAD

**Issue by Rman88** [Courseplay/courseplay#2477]
Ya, i know their was another post on this. but this is specific to the new map on the platinum edition. as i have seen it happen with both the combine and a seeder. where it would hit this spot and then run in circles endlessly. 
![20171124193524_1](https://user-images.githubusercontent.com/33971169/33226240-ca77f988-d14e-11e7-8364-bb049da5adf3.jpg)
![20171124193530_1](https://user-images.githubusercontent.com/33971169/33226241-cedd8844-d14e-11e7-9975-2d658a7b17ed.jpg)
![20171124193537_1](https://user-images.githubusercontent.com/33971169/33226242-d0baa322-d14e-11e7-92a4-bfda4c8705c9.jpg)
![20171124193543_1](https://user-images.githubusercontent.com/33971169/33226243-d2882314-d14e-11e7-96d6-34dce2195c78.jpg)
![20171124193553_1](https://user-images.githubusercontent.com/33971169/33226244-d4255e80-d14e-11e7-883d-39a1e20b261f.jpg)

it only seem to affect this one spot. and i have no idea how to fix it. any thoughts?

**Comment by pops64** [comment]
Please post a log and picture with debug 12 and 14 active. I have seen it as well but it appeared to me has random

**Comment by Rman88** [comment]
well i don't quite know how to do that. thou this is my save game. 

https://www.dropbox.com/sh/ub8mqbebfc9egaz/AABe-TWf0qZt6OQi1y3f4rk6a?dl=0

and i hope you can view it.

**Comment by Rman88** [comment]
ok figured it out. 
![20171124195824_1](https://user-images.githubusercontent.com/33971169/33226398-2334b4d2-d152-11e7-8e73-9009ef5603e5.jpg)
![20171124195834_1](https://user-images.githubusercontent.com/33971169/33226400-24c14068-d152-11e7-875a-5c7e0c32a657.jpg)
![20171124195852_1](https://user-images.githubusercontent.com/33971169/33226401-25f6bb16-d152-11e7-896a-e612a41ffcba.jpg)

**Comment by pops64** [comment]
Could we get the log with debug channel 12 and 14 active during the failed turning maneuver

**Comment by pvajko** [comment]
We also need this course, see the Wiki. And all course generator settings.

**Comment by pops64** [comment]
Not a course gen issue(Unless the way points placed are wonky). I have witnessed this on the old one. I think it is something internal to the turn code and how it interacts with the map. My guess is giants has changed something on this map

**Comment by Rman88** [comment]
welp, not sure how exactly that will help. but i ran into a few problems trying to locate the saved data. thou it doesn't help that the wiki is very bear bones and missing a few things. that said hears another log i took after saving the game with 12 and 14 going. 

https://www.dropbox.com/s/gatc8tw36dalg74/log.txt?dl=0

that said to recreate it. is fairly simple. what your going to want to do is first scan the field. note i combined 1 and 2 into a larger field. j then hitch up the seeder or use the combine. they both seem to safer this issue. thou if you ask me it is just because it hit this specific point on the field within the course it takes. 

that said depending on the tool you pick. your going to want to start from south west going east. with at least 1 click down on the working with. so 5.9 m for seeder and 6.9 m for the combine should be the right size. other then that their is 0 alterations beyond the base course generation. 

just a note this is not an infinite loop. it will sooner or later go back onto the course.

**Comment by Rman88** [comment]
ok just an update on this. Seems like making the field a little bit larger fixed the issue. as i have yet to see the circle bug. So in short their is just 1 spot on the map that causes course play to bug out. No clue why

**Comment by pops64** [comment]
Closed #2909
