### ISSUE TITLE
Refusal to scanned automatically

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Courseplay/courseplay#2479]
If I refused at the beginning of the game from scanned automatically fields, then I can never again choose a field for work.

**Comment by Jimmy-the-Geek** [comment]
Not an issue. When you open the courseplay HUD, choose the scan this field option and add it to the field list.
--

**Comment by Gonimy-Vetrom** [comment]
Thank you. But sometimes it does not help either.

**Comment by Gonimy-Vetrom** [comment]
I found my mistake. It is necessary to drive in front and rear wheels on the field, and then scan it. I drove only the front wheels (I did not want to destruction the crop)

**Comment by pops64** [comment]
You can also open the CP settings file found inside your savegame folder and re enable auto scanning on game load.
