### ISSUE TITLE
CoursePlay Overloader Not unloading from auger

### ISSUE THREAD

**Issue by mathat121** [Courseplay/courseplay#2481]
Im unloading from the combi into an auger trailer (have tried mods and non mods) to then unload into a semi, other trailer or large it runner tipper. Everything is working correctly apart from unloading from the auger trailer. Please help

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki #2231

**Comment by Blackmankot** [comment]
Do you use this mod - CombineAddOn?

**Comment by mathat121** [comment]
Map gold crest valley
Version 5.2 of course play
And yes I have combine Add on mod running

GIANTS Engine Runtime 7.0.0 (15417) 64bit (Build Date: Oct 12 2017)
Copyright (c) 2008-2017, GIANTS Software GmbH (giants-software.com), All Rights Reserved.
Copyright (c) 2003-2017, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: FarmingSimulator2017
Main System
  CPU: Intel(R) Core(TM) i3-6100H CPU @ 2.70GHz
  Memory: 8082 MB
  OS: Windows NT 10.0 64-bit
Physics System
  Version: 5.9.5
  Thread(s): 2
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick enabled
  Force Feedback disabled
Audio System
  Driver: OpenAL
  Version: 1.1
  Device: Generic Software
Render System
  Driver: Direct 3D 11
  Card Vendor: NVIDIA Corporation
  Renderer: NVIDIA GeForce GTX 950M
  Version: 22.20.16.4749 (24.7.2017)
  Revision: 162
  Feature level: DirectX 11 ON
Info: Effective window resolution 1920 x 1080
Started 2 threads for threadpool 'Render threadpool'
Hardware Profile
  Level: Custom Very High
  View Distance Factor: 1.300000
  Shadow Quality: 2.000000 Size: 4096 Filter-Size: 16
  Shader Quality: 3
  Skip Mipmaps: 0
  LOD Distance Factor: 1.300000
  Terrain LOD Distance Factor: 2.000000
  Terrain Normal Mapping: Yes
  Foliage View Distance Factor: 1.600000
  Max dynamic foliage View Distance Factor: 1.600000
  Foliage Density: 0.500000
  Volume Mesh Tessellation Factor: 0.750000
  Tyre Tracks Segments Factor: 1.000000
  Max. Number of Shadow Lights: 5
  Max. Number of Lights: 512
  Max. Number of Lights Per Cluster: 32
  MSAA: 4
Farming Simulator 17
  Version: 1.5.1.0 b1583
  Available Languages: en jp fr es ru it pt nl cs ct br tr ro kr
  Language: en
  Time: 2017-11-26 10:42:48
  Register configuration 'inputAttacherJoint'
  Register configuration 'attacherJoint'
  Register configuration 'frontloader'
  Register configuration 'motor'
  Register configuration 'baseColor'
  Register configuration 'wheel'
  Register configuration 'rimColor'
  Register configuration 'design'
  Register configuration 'designColor'
  Register configuration 'vehicleType'
Game vehicle types loaded
Load dlc: pdlc_kuhnPack (Version: 1.0.0.0)
Error: Invalid mod name 'AIVehicleExtension-master'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Error: Hidden files are not allowed 'modDesc.xml'
.Error: Failed to open xml file 'C:/Users/mathat8910/Documents/My Games/FarmingSimulator2017/mods/Arcusin_Autostack/modDesc.xml'.
Load mod: Arcusin_Autostack
Error: Missing descVersion attribute in mod Arcusin_Autostack
Load mod: ARM_TEAM_EXB1V11 (Version: 1.0)
Load mod: FS17Contest_Annaburger_HTS_22_79_MultiLand (Version: 1.0.1.0)
Error: Hidden files are not allowed 'modDesc.xml'
.Load mod: FS17Contest_BALLYMOON_CASTLE_V_2_ModLandNet (Version: 1.0.0.0)
Load mod: FS17Contest_DustyCove (Version: 1.0.0.0)
Load mod: FS17Contest_Landsberg_Kombination (Version: 1.0.0)
Load mod: FS17Contest_Sicma_Multigrind200_v1 (Version: 1.0.0.0)
Load mod: FS17_Agram_HydroGriffe_BsM (Version: 1.0.0.0)
Load mod: FS17_AnimalNotifications (Version: 1.0)
Load mod: FS17_Annaburger_HT_24_05_Bale_Trailer (Version: 1.0.0.0)
Load mod: FS17_ArtMechanic_LS540 (Version: 1.0.0.1)
Load mod: FS17_BaleFork_Desvoys (Version: 1.1.0.1)
Load mod: FS17_ballenboy (Version: 1.0.1.0)
Load mod: FS17_BetterGroundScales (Version: 1.0.0)
Load mod: FS17_Biobeltz_LF180 (Version: 1)
Load mod: FS17_Biobeltz_TR750 (Version: 1.1)
Load mod: FS17_bmaSH (Version: 1.0.0.0)
Load mod: FS17_Brimont_bb18b (Version: 1.0.0.0)
Load mod: FS17_Brimont_bb18b_console (Version: 1.0.0.0)
Load mod: FS17_BroughanCattleGreen (Version: 1.0.0.0)
Load mod: FS17_Broughan_Silage (Version: 1.1.0.0)
Load mod: FS17_BuyBales (Version: 1.0.0.0)
Load mod: FS17_CaseIHPumaCVXOld (Version: 1.0.0.1)
Load mod: FS17_choppedStraw (Version: 1.0.0.7)
Load mod: FS17_claasDisco3450Plus (Version: 1.0.0.0)
Load mod: FS17_ClaasDominator88s (Version: 1.0.0.3)
Load mod: FS17_coldboroughParkFarm (Version: 2.0.0.0)
Load mod: FS17_CombineAddOn (Version: 1.0.3)
Load mod: FS17_CombineSignals (Version: 1.0.1)
Load mod: FS17_CotechFE108 (Version: 1.0.0.0)
Load mod: FS17_Cotech_BXXL (Version: 1.0.0.0)
Load mod: FS17_Courseplay (Version: 5.2.0.0)
Load mod: FS17_DCK_FollowMe (Version: 1.2.1.40)
Load mod: FS17_DCK_RoundBalerAutoUnload (Version: 1.1.0.24)
Load mod: FS17_DeutzAgrostar471 (Version: 1.0)
Load mod: FS17_deutzFahrCondimaster8331 (Version: 1.0.1.0)
Load mod: FS17_dogfaceRootStorage (Version: 1.0.0.1)
Load mod: FS17_DrawMixerWagon (Version: 17.0.1)
Load mod: FS17_Drumard (Version: 1.0.0.3)
Load mod: FS17_FarmtechTDK900_50k (Version: 1.1)
Load mod: FS17_FlieglFlatbed_UAL (Version: 5.0.0.0)
Load mod: FS17_ForRealModule02_TireDirt (Version: 1.0.2.0)
Load mod: FS17_ForRealModule03_GroundResponse (Version: 1.0.4.0)
Load mod: FS17_FuelUsageDisplay (Version: 3.8.0.0)
Load mod: FS17_Goweil_RBA_BsM (Version: 1.0.0.0)
Load mod: FS17_Ground_Modification (Version: 1.0.0.6)
Load mod: FS17_Gyrax_EBMX155_BsM (Version: 1.0.0.1)
Load mod: FS17_HauerBaleFork (Version: 1.1.0.1)
Load mod: FS17_HiSpec2300G (Version: 1.0.0.0)
Load mod: FS17_holmerTerraDosT4_30 (Version: 1.0.0.1)
Load mod: FS17_horschTitan34UW (Version: 1.0.0.0)
Load mod: FS17_itRunnerManureContainer (Version: 1.0.0.5)
Load mod: FS17_itRunnerPack (Version: 1.0.0.3)
Load mod: FS17_ITS_Lemken_Heliodor9 (Version: 2.5.6.0)
Load mod: FS17_ITS_Lemken_Kompaktor_S (Version: 2.5.6.0)
Load mod: FS17_JohnDeere690 (Version: 2.0.0.0)
Load mod: FS17_JohnDeere6R_FBM (Version: 1.0.0.1)
Load mod: fs17_JohnDeerePremiumBalers (Version: 3.0)
Load mod: FS17_Joskin_KTP_2250_BsM (Version: 1.0.0.0)
Load mod: FS17_Joskin_Trans_5000_BsM (Version: 1.0.0.1)
Load mod: FS17_Joskin_Wago_Loader_BsM_ModLandNet_2 (Version: 1.1.0.0)
Load mod: FS17_KeenanFeeder (Version: 1.1.0.0)
Load mod: FS17_kotteUniversalPack (Version: 1.0.0.6)
Load mod: FS17_krampeBigBody900 (Version: 1.0.0.0)
Load mod: FS17_Krampe_Bandit_Sattel (Version: 1.0.0.0)
Load mod: FS17_kroneBigXPack (Version: 1.0.0.1)
Load mod: FS17_KroneKWT11x22 (Version: 1.0)
Load mod: FS17_KroneSwadro2000 (Version: 1.0.0.1)
Load mod: FS17_KroneSwadroTC930 (Version: 1.0.0.0)
Load mod: FS17_kuhnPrimor3570 (Version: 1.0.0.0)
Load mod: FS17_kuhnVB2190 (Version: 1.0.0.1)
Load mod: FS17_lelyJuno150 (Version: 1.0.2.0)
Load mod: FS17_LelyStorm (Version: 1.1.0.0)
Load mod: FS17_LiquidFertilizerTanks (Version: 1.0.0.0)
Load mod: FS17_LowerAnimalPrices (Version: 1.0.1)
Load mod: FS17_MajorMuckout750 (Version: 1.0.0.0)
Load mod: FS17_marshallBC32 (Version: 1.0.0.0)
Load mod: FS17_marshallQM16 (Version: 1.0.0.0)
Load mod: FS17_MasseyFerguson6600 (Version: 1.0.0.0)
Load mod: FS17_MB3D_ClaasJaguar800 (Version: 1.1.0.0)
Load mod: FS17_MB3D_JohnDeere7030 (Version: 2.0.0.0)
Load mod: FS17_McHale991 (Version: 1.0.0.0)
Load mod: FS17_mengeleGarant5402 (Version: 1.0.1.1)
Load mod: FS17_MF5600 (Version: 1.0.0.0)
Load mod: FS17_MoneyTool (Version: 1.0.1.0)
Load mod: FS17_MZH (Version: 1.0.1.0)
Load mod: FS17_newHollandBalerPack (Version: 1.0.0.1)
Load mod: FS17_newHollandLM742 (Version: 1.0.1.0)
Load mod: FS17_newHollandT6Tier4a (Version: 1.1.0.0)
Load mod: FS17_newhollandT9SmartTrax (Version: 1.0.0.0)
Load mod: FS17_oekoPlusRBG_Double (Version: 2.0.1.0)
Load mod: FS17_Pack_Joskin_Wago_AUTO_BsM (Version: 1.0.0.4)
Load mod: FS17_PeeconBiga (Version: 1.1.0.0)
Load mod: FS17_pentaDB50 (Version: 1.0.0.0)
Load mod: FS17_placeablefireHydrant (Version: 1.0)
Load mod: FS17_placeableliquidFertilizer (Version: 1.0.0.0)
Load mod: FS17_placeableRefillStation (Version: 1.0.0.1)
Load mod: FS17_placeableSeedRefillContainer (Version: 1.0.0.0)
Load mod: FS17_Placeable_Ramp (Version: 1.0.0.0)
Load mod: FS17_Placeable_Silo_Beiser (Version: 1.0.0.1)
Load mod: FS17_Platak (Version: 1.0.0.0)
Load mod: FS17_poettingerMex6 (Version: 1.0.0.0)
Load mod: FS17_Redrock (Version: 1.0.0.0)
Load mod: FS17_ROCRT1000 (Version: 1.0.0.0)
Load mod: FS17_Rolland_rp10006ch (Version: 1.1.1.0)
Load mod: FS17_RoundBaleForksPack (Version: 1.0.1.0)
Load mod: FS17_Saegewerk_placeable (Version: 1.3)
Load mod: FS17_sawdust (Version: 1.2.0.0)
Load mod: FS17_slowerRefueling (Version: 1.0.0.0)
Load mod: FS17_stollLargeBaleForkH (Version: 1.0.0.2)
Load mod: FS17_TancoD80 (Version: 1.0.0.0)
Load mod: FS17_TatraPack (Version: 2.0)
Load mod: FS17_TGS_18_ITR (Version: 1.0.0.0)
Load mod: FS17_Tieflader (Version: 1.1.0.2)
Load mod: FS17_TST_Quadro_Pac_V_BsM (Version: 1.0.0.0)
Load mod: FS17_vaederstadFronttiller (Version: 1.0.0.0)
Load mod: FS17_vaederstadRapid300 (Version: 1.0.0.0)
Load mod: FS17_ViconHaybob (Version: 1.0.0.0)
Load mod: FS17_webermtdsc18 (Version: 1.0.0.0)
Load mod: FS17_West_grain12t (Version: 1.0.0.0)
Load mod: FS17_West_silage10t (Version: 1.0.0.0)
Load mod: FS17_Woodshed_placeble (Version: 1.0.0.0)
Load mod: Goldcrest_Productions (Version: 2.0)
Load mod: JD8350GrainDrill (Version: 1.0)
Load mod: JohnDeere7030P (Version: 1.0.0.0)
Load mod: Mchale998 (Version: 1.0)
Error: Unsupported mod description version in mod Mchale998
Load mod: Quad_POLARIS_6x6 (Version: 1.0)
Load mod: smallUtilityTrailer (Version: 1.0.0.0)
Load mod: STEYR_8110aTurbo_SK2 (Version: 1)
Load mod: Tandem_Livestock_Trailer (Version: 1.0.0.0)
Load mod: Torpedo_9006A (Version: 1.0.0.0)
Load mod: WelgerAP730 (Version: 1.0)

**Comment by Blackmankot** [comment]
That's because of this mode the unloading does not work! Remove it!
![2017-11-26_21-02-54](https://user-images.githubusercontent.com/26131714/33240212-6b9bb03a-d2ed-11e7-89aa-4572b7e5c090.jpg)

**Comment by pops64** [comment]
#2231 Step 2 of wiki. Please post logs in a file for download and not copy and paste. Thanks
