### ISSUE TITLE
Courseplay 3.x?

### ISSUE THREAD

**Issue by sibaz** [Courseplay/courseplay#2482]
I just bought FS15, and discovered courseplay, so want to install it on FarmSimulator 2013, so I can use it on my very developed existing game.  The internet seems to suggest 3.41 and 3.44 are the latest releases for that, but I don't trust them, and you only seem to have 2.22 and >=4 and no docs explaining what to do for FS13.  

Can you put a page on the wiki explaining or something, please

Thanks,
Si

**Comment by pops64** [comment]
This is the only version of FS13 we would have on github https://github.com/Courseplay/courseplay/tree/FS13_finalish
