### ISSUE TITLE
Tractor Does Not Wait at Unload Point

### ISSUE THREAD

**Issue by lsjohnson2** [Courseplay/courseplay#2483]
I have been unable to unload any trailer successfully, using any mode. The screenshot below shows a very simple route that does a circle around the unload grate at my silo for demonstration purposes. If I drive the route once, no problem the trailer unloads into the silo successfully. 

However, on the second time around, the tractor continues to pull forward, which results in the crop being dumped onto the ground next to the unload grate (as seen in the screenshot below).

![20171127092952_1](https://user-images.githubusercontent.com/34034310/33274393-90ec54d0-d355-11e7-8d99-87b0cfad450a.jpg)

Misc Info.

Lastest FS17 (Steam Client)
Lastest CoursePlay (5.2)
Tractor 1455XL
Tipper HKD 302
Modes tested: Combi and Grain Transport

Please advise and let me know if you need any further information.

**Comment by pops64** [comment]
You can't use unload points with tip triggers. Unload points are tipping to the ground only. CP automatically recgonoizes tip triggers. Rerecord the course with out any unload points
