### ISSUE TITLE
Mode 2: Tipper gets stuck behind combine

### ISSUE THREAD

**Issue by Phantom742** [Courseplay/courseplay#2486]
Hi

i frequently experience a problem with mode 2. This happens so far on all maps. Mods are not an issue because it happens also when courseplay is the only mod installed. The problem is the following:
The combine unloads to the tipper an the tipper wait's for the parking position the be clear. The combine continues with his work. Now here is the problem when the combine is at the edge of the field. While the tipper starts to drive to the parking position, the combine reaches the end of the field. The combine waits until the tipper reached his parking position but the tipper cant reach the parking position because he is stuck behind the waiting combine.

![image](https://user-images.githubusercontent.com/11431031/33374330-fd6dc880-d505-11e7-9a61-d1480031fa23.png)

A possible solution: 
1. check the distance to the edge od the field, if it is to close the have the tipper turn away from the combine or 
2. the tipper uses 2 waypoints which he creates to drive to the parking position (as far as i can see it). The tipper starts to drive when the first position is cleared by the combine. The tipper should wait until the second position is clear before he starts moving again.

Thx gents.

**Comment by Phantom742** [comment]
any updates?

**Comment by ThrustVector** [comment]
Having a similar problem. If I'm using mode 2 with tractor and tipper and the combine is almost at the edge of the field, then the tractor and tipper will start unload the combine. The combine stops at the end of the field until empty but then just sits there. The tractor starts to reverse but stop sudenly and complains about beeing in traffic.
Got a savefile prepared if needed!

**Comment by pops64** [comment]
This is on our to do list to improve. It always has been kinda finicky

**Comment by pops64** [comment]
Closed #2909
