### ISSUE TITLE
Mode 3 - Tractor Stuck in Traffic

### ISSUE THREAD

**Issue by rbneville** [Courseplay/courseplay#2489]
![fs17](https://user-images.githubusercontent.com/7034766/33463450-c946b470-d60b-11e7-9cba-f32d24cebeea.png)
Perhaps if a vehicle is in mode 2 or 3 and if it is stuck in traffic for more than a few seconds have it reverse then resume as stopping CP on the Tractor, reversing straight back about 10 meters, then starting CP again makes the tractor pull into the correct position next to the combine. Thank you to everyone on the courseplay team for releasing this awesome mod. Cheers.

**Comment by lcc1211** [comment]
I tried reporting this one before. The advice I got was **"You can either bump up the horizontal offset to give the tractor more room. Decrease your field speed, Or just wait until the harvester moves further down field has this will fix itself, or use a smaller tractor."**

**Comment by pops64** [comment]
Going on our postponed todo list. until we clear out our current todo list
