### ISSUE TITLE
Straw DLC support

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#2491]
Hey guys,
currently it sadly is not possible to use the Premos from Aerosofts Straw-DLC with courseplay. CP always says its the wrong tool for the mode.

**Comment by Paul2510** [comment]
The Krone comprima dont unload Bale! LG

**Comment by alpha117** [comment]
Creative Mesh are aware of this issue from day 1.

_We know that. Since the Premos is a new class of tool (pelletizer), courseplay does not recognize it. Its on the courseplay developers to change that._

**Comment by pops64** [comment]
Please give us a **clean link** to the mod in question.

**Comment by alpha117** [comment]
https://www.creative-mesh.com/

**Comment by p4r4d0xs** [comment]
Some news?

**Comment by alpha117** [comment]
@pops64  I need to send you a PM from Creative Mesh
How do I do that on here?

Thanks

**Comment by pops64** [comment]
I put this tag for contact to remind us to get into touch with them. We won't be able to support this until we have a copy of the mod that is not behaving correctly. Especially when it deals with baling.

**Comment by p4r4d0xs** [comment]
This isnt a mod. Thats a DLC.

**Comment by pops64** [comment]
For me DLC only comes from Giants. This a paid mod download. It still doesn't change the fact that we can't support it until we have a copy

**Comment by alpha117** [comment]
Standby.....I'll see what I can do

**Comment by pops64** [comment]
Alright, We will eventually reach out to the mod author but we are busy. So it will take some time

**Comment by Raints** [comment]
I can donate that money for it, least I can do for that great mod.

**Comment by Blackmankot** [comment]
@pops64 Here is a link to the mod itself. Download. https://yadi.sk/d/RM2CtgZm3QTbXd

**Comment by pops64** [comment]
@Blackmankot please only post official links to download locations. I removed your link because of this

@Raints Thanks for doing that.

**Comment by Blackmankot** [comment]
@pops64  I understand you.

**Comment by alpha117** [comment]
He has also been reported to here:
https://www.fast.org/Report/Software-Piracy%E2%80%8E

and will get a visit within 28days

Thanks

**Comment by ThomasGaertner** [comment]
test v41 or higher and report.....

**Comment by alpha117** [comment]
Thanks, let you know

**Comment by alpha117** [comment]
With the Premos 5000, gives a working width of 2.3m  and generates a course no problems.

Great work

Thanks

Have you let the guys at Creative -mesh know its done?

If not I'll let them know via messenger

**Comment by alpha117** [comment]
Will CP know when the Premos 5000 runs out of either water or molasses?

**Comment by s1100** [comment]
![fsscreen_2017_12_17_16_46_49](https://user-images.githubusercontent.com/30638928/34081194-0e77a11c-e34a-11e7-8255-60250b1a5267.png)
works fine 👍

**Comment by pops64** [comment]
Alright thanks. Closed

**Comment by huseyinsayar** [comment]
Was "Course Play" updated for "Premeos 5000" in "Straw Harvest" package?
What is the version number if it is done?
Would you give youtoube video link?

**Comment by pops64** [comment]
Always download the latest version of the dev release for new features and can tolerate a beta version. If your mod isn't working then it isn't supported. Other wise stick with the official release which this mod is not supported in the official release. #2231
