### ISSUE TITLE
Water animals course Setup Question

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#2494]
Hi All

How do you set this up.

I record a course that goes over :

1. Water refill trigger
2. Animal  trough triggers

When I drive the course the tractor/water trailer just drives around the course from start to finish and never stops anywhere

What am I missing, MODE maybe

Thanks

**Comment by pops64** [comment]
Mode 8. And place a waitpoint at where the unload action occurs. No waitpoint is needed for filling. The water unload trigger is very small on standard maps and equipment. Make sure it says you can unload before placing a waitpoint. Your aiming for the middle of this zone where it says to unload to the trough
