### ISSUE TITLE
shovel.mode cow manure heap

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#2498]
Hey guys
I drive in a manure shovel course.
The first waitpoint is a litte bit before the manure area.
The 2nd is at the end of the manure area.
The 3rd is an untipping in a manure heap store.
I drive in the course with v 02 0039 also the newest.
The problem is the teleloader drive straight from the first waitpoint to the 2nd waitpoint.
No left or right to load all manure.
A pair weeks ago on the same map i drived in unlaod bga and cowsilo shovelcourses.
In the same way and the teleloader drive left and right the course to shovel all the silage.
Whats wrong?

edit: pics:
![fsscreen_2017_12_08_14_30_14](https://user-images.githubusercontent.com/24860501/33767969-7bbb85fe-dc24-11e7-8bcc-a0b3d9a13f34.png)
here you see left and right the manure

they on the silos work fine a pair days ago
![fsscreen_2017_12_08_14_32_20](https://user-images.githubusercontent.com/24860501/33767993-9dcf9e96-dc24-11e7-8d89-d41913327fd3.png)
but, i dont testet it with the v 02 0039

Lg
Andreas

**Comment by andreasthu** [comment]
ok, testet now with one tipper silage, it works
![fsscreen_2017_12_08_14_43_34](https://user-images.githubusercontent.com/24860501/33768432-4bf7a814-dc26-11e7-8050-f8850f3b4dcb.png)
why does it not work on manureheaps?
lg
andreas

**Comment by andreasthu** [comment]
3rd thread: i have a workaround:
# i installed the v02.0033, 
# drive in the shovel course
# test it - it works
# install the v02.0039 version
# start the shovel course - it works
as example, than i also drive in an shovel course with v02.0039 - this work not

lg
andreas

**Comment by ThomasGaertner** [comment]
log with debug 9 please

**Comment by andreasthu** [comment]
seems to work nice with 02.0040
i have drive in 2 courses and now it works
lg
andreas

**Comment by pvajko** [comment]
I know I screwed up 39 but did not expect shovel mode to be broken. Anyway, closing this then.
