### ISSUE TITLE
Mode1

### ISSUE THREAD

**Issue by MrScsi** [Courseplay/courseplay#2500]
Ok I have reported this before and was told it was realistic mass mod EVEN though I have never used that mod but I was using mod trailers so I started using stock built in trailers and the issue went away for the most part.

Now it seems to be back, On every trigger I have a course play running to to unload it will detect the trigger and just slide through at 6mph without unloading...

Here is a video of the issue with debug 19 turned on

https://www.youtube.com/watch?v=4UayvJFTmuw&feature=youtu.be

Here is the link to the course
https://drive.google.com/file/d/1dAXeZrYyVa1giB6dsfldfHh1Ra7NsUWJ/view?usp=sharing

Here is a link to the map

https://drive.google.com/file/d/11BgZQ9D0RZs_KRXi80-cYaSky3VhXsJ3/view?usp=sharing

I mean IF it is something I am doing wrong with the triggers I would LOVE to know so I can avoid it 

Also I noticed something looking at the course in notepad++ there is NO speed less than 24 being recorded and that just is NOT right cause I freakin stopped on the trigger when recording the course. I never blow through a trigger ALWAYS drop to 3 or less

**Comment by MrScsi** [comment]
Just looked at the course again and saw that it is waypoints 83 through 88 that cover the tirgger and I know when it was recorded it was at 3mph or less through that zone and the course reports...

<waypoint83 angle="-179.83" speed="14" pos="1904.37 -684.66"/>
    <waypoint84 angle="-179.85" speed="11" pos="1904.34 -694.67"/>
    <waypoint85 angle="-179.83" speed="24" pos="1904.32 -704.69"/>
    <waypoint86 angle="-179.82" speed="25" pos="1904.29 -714.71"/>
    <waypoint87 angle="-179.83" speed="29" pos="1904.26 -724.78"/>
    <waypoint88 angle="-179.83" speed="32" pos="1904.23 -734.80"/>

So something just aint right cause even kph is only 4,8 not 11 or higher at 3mph

**Comment by pops64** [comment]
I need a complete log with *just* debug channel 1 and 2

**Comment by MrScsi** [comment]
OK by log you mean giants log or CP log and if CP log where does it write it?

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki it all prints to the giants logs

**Comment by MrScsi** [comment]
Ok doing it now

**Comment by MrScsi** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/1553294/log.txt)

There ya go

**Comment by MrScsi** [comment]
Ok I posted the log do you need it  linked I can put it on my google drive as well

**Comment by MrScsi** [comment]
https://drive.google.com/file/d/1KAViFysRB2QKbHMtH4Ky7AMHrMAjsnNg/view?usp=sharing

**Comment by Aoxmodeus** [comment]
I ran into an issue yesterday that took me a bit to figure out, perhaps it is affecting you as well.

If you run a trailer on mode1, and during it's course returning from the unload location, it crosses another loading location that doesn't have the fruit you've selected, the next go-round it will not load fruit from your loading location, but will just drive through it, then drive the course really slowly.  

Are you possibly driving through another tip trigger on the way to your destination tip trigger?  It would be a similar issue to mine, though not exactly the same.  Just something to check out.   

Good luck, man.

**Comment by MrScsi** [comment]
I have some like that BUT the video above is just a simple single trigger

**Comment by pops64** [comment]
@Aoxmodeus that is already documented bug

**Comment by Aoxmodeus** [comment]
@pops64 Roger that.  I wasn't going to bring it up as a separate issue, since it's "workaroundable", but thought it may have some impact on MrScsi's issue.  That issue did preclude me from using a type of modded silo, as it had the filling spout and emptying point on the same location, but I chose a different one with separate loading/unloading and it's fine.  I just figured it was "how it worked", and not necessarily a bug.

**Comment by MrScsi** [comment]
Well to throw a monkey wrench in the mix even further...

I took a copy of the GCV map and removed the trigger of Goldcrest pacific grain and replaced it with the EXACT same trigger that it is driving through....

Well it works fine in the GCV map so go figure

**Comment by pops64** [comment]
The problem is that the trailer according to giants functions is no longer in reach of the trigger but according to my function that I use to place the tip point in the center of the trigger it still hasn't reached the center so this may not be fixable has it may be a problem with either the modded trigger or bug on giants side

**Comment by MrScsi** [comment]
I may have solved the issue. I am gonna do some more testing but what it is I THINK anyway is I have always put trigger start and end AT the trigger start and end. In other words running the SAME way I would run the trailer through if it were from left to right it would be start and end.

Well seems CP likes that 180 degrees opposite. if the trailer goes into the trigger and sees end then start it seems to work fine...
