### ISSUE TITLE
Multiplayer enabled

### ISSUE THREAD

**Issue by ThomasGaertner** [Courseplay/courseplay#2502]
Please test in MP and report errors with logs from server and client , ideally with debug channel 5 active
#2228 #2179 #2085 #2033 #1963 #1606

**Comment by turbostar190** [comment]
Tried on dedicated server.
1) Can't start field work neither combine nor sowing or similar --> machine blocked and can't turn on the engine and turn the wheels anymore 
2) information on maps not visible, neither the "cp worker" sign, only the default dot (signed dot was a running cp course)
![inkedfsscreen_2017_12_17_18_25_37_li](https://user-images.githubusercontent.com/24813315/34082108-ad26ab6a-e358-11e7-8460-057ec206c2d2.jpg)
3) Vehicles don't see combine --> message "No combine available" ^^
4) Alt + d doesn't work --> lua error (line 3884 client)
5) toggleFuelSaveOption -> value nil

Client: [log.txt](https://github.com/Courseplay/courseplay/files/1565866/log.txt)
Server: [logserver.txt](https://github.com/Courseplay/courseplay/files/1565867/logserver.txt)

**Comment by ThomasGaertner** [comment]
concerning 4: please test v44 or higher.
concerning 2: I disabled it till I get a proper solution for it, its not that easy , but on my list...
the rest : you need to make a little workaround : whether you create a new savegame in SP mode , save it once and upload it to the dedi or you create a new savegame on the dedi, save it once and restart the server. Then it should work... please give feedback  thanks

**Comment by turbostar190** [comment]
Creating a new savegame, save it and restart seems working. I've got again lua error on alt+d (line 5184 client)
[log.txt](https://github.com/Courseplay/courseplay/files/1568702/log.txt)

**Comment by ThomasGaertner** [comment]
yea , I'm stupid, didn't fix it properly , will be fixed in next update ....

**Comment by okaufmann** [comment]
I've used it yesterday on our multiplayer server and it worked very welll (We cut some corn and used it for longer transport ways). 

One Bug I noticed was: When one player load and start a vehicle with a course and then I get into the same vehicle, the course is displayed rotated by 90° but the course will be executed correctly. Funny to watch.

Thanks for this great mod!

**Comment by ThomasGaertner** [comment]
ok, was it a generated course ? didi you join the game, when the course was generated or didi you generate it and the steped into this tractor ? seems the the directtion will no be broadcasted properly , can you confim ? please check the starting directiions with you two players in the same tractor and report .
And thanks for the donation :-) 
Frohes Fest !!!

**Comment by AlexStephenLytton** [comment]
It's a minor problem but - if you're using the "shovel mode" in MP the movement of the arm is not shown ingame 

![2017-12-26](https://user-images.githubusercontent.com/5282456/34352745-99a3ab88-ea24-11e7-9387-4f08378a69da.png)

Only the shovel itself is moving...

**Comment by debejerry** [comment]
We're using  Version 5.02.00051 o. our dedi server.
The server doesn't restart on schedule so it often runs for more than a week before the game gets manually.
One thing I've noticed is that when a tracor had course loaded or generated (course1) before and I (or any other player) joins the game and i want the tractor to drive another course (course2) that is newly created or loaded and the cp helper gets hired course2 ia displayed but the tractor wants to drive course1.
Things that help to workaround this behaviour is to reset the tractor or restart the gane on..dedi server.

For the moment i do not have logs but will provide them asap.

Regards
Stefan

**Comment by Brzzl** [comment]
Hi! Am I the only one who has problems with combine assignment, respectively combine auto search in mode2 on a dedi-server? Running .0051dev
The driver won't start unloading the combine, no matter which percentage I choose to start unloading.

**Comment by debejerry** [comment]
Another thing I've found and thats's reproducable is when CP get's stuck in traffic, and the blocking traffic/vehicel moves out of the way the "stuck in traffic" state seems not to get reset and so CP doesn't continue driving even though it should. 
Rehiring CP in that case helps.

**Comment by kiwirobert** [comment]
i have had the same problem where it wont move

**Comment by debejerry** [comment]
I've also had that problem as you describe @Brzzl @kiwirobert 
In that case what helped me as a workaround again was restarting the dedi server.
All of these things seem to me as problems regarding MP sync but to be honest I have no clue where and how to help out, as I couldn't yet figure qut what is causing this behaviour.

**Comment by kiwirobert** [comment]
debejerry i have tried that

**Comment by ThomasGaertner** [comment]
@debejerry : I've checked it on a dedi server and it worked. for better understanding I changed the local info text that you can see, why the tractro is not going to the combine. I most of the cases it's pathfinding active and pipe in fruit V.00052 ...

**Comment by pops64** [comment]
LOG:

CourseplayMultiplayer: reading 2 couses

### CourseplayMultiplayer: reading 0 folders 
### CourseplayMultiplayer: reading 0 custom fields 
### CourseplayMultiplayer: courses/folders reading end
Error: Running LUA method 'mouseEvent'.
C:/Users/Kille/Documents/My Games/FarmingSimulator2017/mods/FS17_Courseplay/CpManager.lua:177: bad argument #1 to 'pairs' (table expected, got nil)

Hello, I play with my friend on local multiplayer.
When I join for first time everything is fine, but when i would like to join again after buying machines, the game stop loading at this point: """ ### CourseplayMultiplayer: courses/folders reading end """, when I
synchronize with him. When i try to disconnect the game crashes.
Maybe you can look at it or fix it or something, Thank you :D

**Comment by Biermann790** [comment]
Hey, I tried to deactivate the automatic field scan on server. I downloaded the file courseplay settings from savegame and edited the field scan from true to false and uploaded it again. But if I join the game field scan is still active. My problem is it takes more than 10 minutes of time. How can I deactivate it?

**Comment by Steaktered** [comment]
Hello, i have a problem with cp on my server all courses was lost after restart

**Comment by KITT3000** [comment]
When a player generates a course, but "COURSEPLAY_COURSE_SUBOPTIMAL" appears, the window is displayed to all players.

**Comment by elrancho420** [comment]
when i try to use course play in multiplayer it works fine for me but when others try to join they get stuck in the loading screen and cant join

**Comment by pops64** [comment]
Closing this out if you still have a MP issues please post a proper bug ticket(https://github.com/Courseplay/courseplay/wiki) and Thomas will look into it when he has time
