### ISSUE TITLE
Gui focus on savegame start not set

### ISSUE THREAD

**Issue by turbostar190** [Courseplay/courseplay#2504]
After the savegame loading, "Start" button isn't selected automatically and it's impossible to click it with controller and without a mouse.

Realismus Modding team resolved putting `FocusManager:setGui("MPLoadingScreen")` just after g_gui:loadGui.

https://github.com/RealismusModding/FS17_seasons/blob/521b1231c25f5b0c748bfc9f230d92403f4b4f5c/src/ssMain.lua#L129

**Comment by pops64** [comment]
Is this a MAP issue?

**Comment by turbostar190** [comment]
No, it happens always, also on GCV or Sosnovka. Of course it happens if the map has additional gui and `FocusManager:setGui("MPLoadingScreen")` isn't applied

**Comment by pops64** [comment]
Is it a MP issue is what I meant to say. https://github.com/Courseplay/courseplay/wiki

**Comment by turbostar190** [comment]
Nope, mploadingscreen doesn't refer to specific mp GUI but it's a common name for savegame loading GUI.

**Comment by pops64** [comment]
what start button are you talking of? https://github.com/Courseplay/courseplay/wiki Picture please.

**Comment by turbostar190** [comment]
FS17 v1.5.3.1
CP 5.02.00045
Only cp activated on a new career

![fsscreen_2017_12_19_16_35_51](https://user-images.githubusercontent.com/24813315/34164964-49bd69cc-e4db-11e7-8d08-c745652b53c1.png)
"Start" button (Inizia) isn't automatically highlighted and this makes impossible start the game without a mouse.
Adding `FocusManager:setGui("MPLoadingScreen")`  at line 306 just after `g_gui:loadGui` in `inputCourseNameDialogue.lua` makes the trick and it solves the problem.

**Comment by turbostar190** [comment]
Solved!
