### ISSUE TITLE
pause button cannot be used

### ISSUE THREAD

**Issue by Scaracuila** [Courseplay/courseplay#2505]
Hello,

First of all, thank you very much for your great work!

In version 5.02.00045 I noticed, that the "Pause" button is no longer available when recording courses! Last time, I used the button in the version... 41!

I didn't upload a log, because there were no error entries for this.

Many thanks and best wishes
Scaracuila

**Comment by Brzzl** [comment]
Hi all!
Can confirm this.

**Comment by Scaracuila** [comment]
Hi!

Interesting, I didn't try that! I had set a lot of unloading points, crossing points and also waiting points - but the pause button did not become active again! But yes, with the reverse mode this becomes active!

 as a temporary solution, I'll use that!
