### ISSUE TITLE
Tractor turn and reverse too far from Forage Harvester

### ISSUE THREAD

**Issue by JLConradie** [Courseplay/courseplay#2507]
Hello.. 
Thomas,
Am I doing something wrong?.....

![turn3](https://user-images.githubusercontent.com/32715611/34163588-c5802a5a-e4df-11e7-86f6-aee06e5df922.png)

![turn4](https://user-images.githubusercontent.com/32715611/34163673-0969c708-e4e0-11e7-9be5-757f35ce93ad.png)

Courseplay generate course outside of the trailer trigger of Forage Harvester. (Too far from Forage Harvester.) (First Picture)
I have change the turning circle and Offset bigger and smaller but it seems that the generated turning course is fixed. Due to this the forage Harvester does not know that the tractor or support vehicle is close by or has finished the turn. (Second Picture)

I have tested it with mods and game vehicles. All the same.

How can I let courseplay generate the course closer to the combine. Or what am I doing wrong?

It looks like switching state 5->7 or 7->3

Farmsim ver. 1.5.3.0
Courseplay ver. 5.02.00045 (But I have tested it with 39 38 and 37)
Map: Estancia Lapacho
Field: 29

**Comment by JLConradie** [comment]
Hi Thomas
I tested it again. If the work width is bigger than the trailer trigger of the combine then the there is trouble.

The support tractor is taking the place of the combine at turns now if the work width is bigger than 10m or bigger than the the trailer trigger of the forage harvester then you find yourself in trouble.

You can't use headers bigger than 10m and use the forage harvester afterwords to pick-up. Anything less than 10m works fine.

Regards

**Comment by eddiem54** [comment]
I think you are using the wrong mode. Combine and forage harvester usually unload into trailers on field using "Mode 2" [Courseplay manual Mode 2](http://courseplay.github.io/courseplay/en/manual/index.html#driveMode2)

**Comment by JLConradie** [comment]
I'm using that mode.
I'v edit the model and add around 3m to the width of the trailer trigger so that the combine/forage harvester can pick-up the trailer. Now everything is working fine the way it should be.

**Comment by ThomasGaertner** [comment]
in your case , you don't need to edit the model, just set the workwidth of the harvester to the native workwidth of the course manually ( e.g. the combine had a 13,2m cutter so you need to set it to 13,2m for the harvester manually)
