### ISSUE TITLE
Wheat chopping with Courseplay

### ISSUE THREAD

**Issue by MoslessNeo** [Courseplay/courseplay#2510]
I'm having trouble already several versions.
I generate the route in "fielwork" mode for the Krone harvester and the route for transport to the Fendt.
Mods are unique from the game.
I already tested with the map and the CP.

The problem is that the harvester loses the tractor....
https://1drv.ms/i/s!AlW6BjVQKGAY9dhGpjB2yFSdPWH1Rw

**Comment by pops64** [comment]
You ethier adjusted your vertical offset in which case set it back to zero. Or you need to adjust your vertical offset until it lines back up

**Comment by pops64** [comment]
Closed due to inactivity
