### ISSUE TITLE
Combine Hours speed up when stopping the unload course

### ISSUE THREAD

**Issue by deathheart14** [Courseplay/courseplay#2514]
I have noticed that if you have the auto unload on the combine and turn it off before the field is  and load the next fields unload spot it will make the game unresponsive, the ours on the combine will start increasing fast, and the only way to stop it is to exit the game by either ctrl alt delete or click the x from the tray.

I have noticed this when also just canceling the course before the field is finished.

**Comment by pops64** [comment]
Auto unload? https://github.com/Courseplay/courseplay/wiki

**Comment by deathheart14** [comment]
Combine self-unloading is what I am referring to

**Comment by ThomasGaertner** [comment]
I can't reproduce your issue. Are you able to make a video or some screenshots of the situation . or can you give me your save game with an detailed description what you have done ?
Thanks

**Comment by deathheart14** [comment]
It just so happened it did it while I was streaming. The link below has it in the video.
If you look at 00:11:40 - 00:12:30 you will see what I have been experiencing.

At 11:40 time frame I stop the driving and then load the new course. I have the in game helper tending to the field during this. 

At 21:04 you will see that the field is done being cut and then the Combine hours start increasing. While this is happening I am unable to turn the combine this is why i stop and try backing up and even clearing the course I loaded.

The only way I fix this is to close the game out by clicking the X on the window in my task bar or pressing Ctrl Alt Delete and killing the game. I am unable to escape out of the game like you normally would.

https://www.twitch.tv/videos/211965709

**Comment by pops64** [comment]
Log please. This is probably a nil error when firing the worker while CP is currently active or vis versa

**Comment by deathheart14** [comment]
Would you be able to direct me to where the log file you are looking for may be?

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by ThomasGaertner** [comment]
please test v .00049 or higher and report....

**Comment by deathheart14** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/1589361/log.txt)

Attached is the log file

I will try the newer version of this and let you know if it still does this

**Comment by deathheart14** [comment]
Version .00050 works and i am unable to reproduce it
