### ISSUE TITLE
Clarification:  Bypass Island Feature

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#2515]
Can someone explain how to use the Bypass Island feature?  I thought it would cause the vehicle to drive around objects in a field such as utility poles, trees, rocks etc.  However, even with this feature on I have noticed my combine, my tractor hauling a sower, windrower, plough etc.  will still drive right into these poles.  I used the Lizard R 5000 ground mod to delete the field around the poles and add grass, but it still drove over them.  I then used it to lay down various other types of ground such as concrete, asphalt and so on.  Is there a minimum radius required before CP will navigate around it?

**Comment by pvajko** [comment]
Bypass works only with the new course generator, that is, you have to select 'current vehicle position' or 'last used position' as starting location to make it work. I forgot to disable it for the other starting location options.

I'll push an updated version soon where there's also an option to drive a full circle around these islands.

**Comment by lcc1211** [comment]
@pvajko Thank you.  I think that will be great to have as a feature for each way of creating a course.

**Comment by lcc1211** [comment]
I see you implemented the simple & circle bypass.  Is it activated so that is should be working?  If so, it is ignoring the same spots on my fields.
![20171226211303_1](https://user-images.githubusercontent.com/24764870/34370320-03f5998a-ea91-11e7-9f4c-54b933ae5037.jpg)
![20171226214140_1](https://user-images.githubusercontent.com/24764870/34370321-05f91338-ea91-11e7-9cce-f3e704153dfa.jpg)

**Comment by pvajko** [comment]
Not sure where the island is on your first picture, I see two little grey spots, probably rocks, if you mean those, then they may or may not be found at all as the island detection works with a 1 m grid. 

Your second screenshot shows a case where the island is at the end of a row and both the turn start and end waypoints seem to be on the island. I did not implement that case yet as it leads to a million complications because the island is in the way of the turn maneuver. For this specific island, you can probably use one headland so the turn waypoints are on the field behind island. Also, that other island in the distance seems to be far enough from the headland so bypass should work there.

Here is how it looks at Coldborough:
![island](https://user-images.githubusercontent.com/2379521/34373570-2af78bc4-eadc-11e7-8683-e109dc9b88ad.PNG)

**Comment by lcc1211** [comment]
The map is County Line and that particular field just had the poles with no grass or concrete, so I used the Giant's ground mod tool to add grass, but it ignored the grass.  As you can see from the 2nd photo, I put concrete over top of the grass with a diameter much larger than the one in your photo, so I am thinking I need to have only one headland.

**Comment by pvajko** [comment]
I'm using the [getDensityAtWorldPos](https://gdn.giants-software.com/documentation_scripting.php?version=engine&category=19&function=282) function to find islands, that seems to work on the maps I tried. Not sure what your map does but that it is ignoring the grass may indicate that they probably just placed a pole on the field and did not actually defined an island on the field in fruit_density map.

If you know how to use the  in game console you can run the cpSaveAllFields command which will write a cpFields.xml file in your map's course folder. If you open that file and see islandNode in there, then CP did find islands on that map and bypass should work.

**Comment by lcc1211** [comment]
OK.  I do see this:  islandNode1 pos="-54.10 440"/>

<islandNode2 pos="-51.10 438"/>

<islandNode3 pos="-50.10 438"/>

<islandNode4 pos="-49.10 437"/>

<islandNode5 pos="-48.10 437"/>

<islandNode6 pos="-46.10 435"/>

<islandNode7 pos="-44.10 434"/>

<islandNode8 pos="-43.10 433"/>

<islandNode9 pos="-41.10 432"/>

<islandNode10 pos="-30.10 426"/>

**Comment by pvajko** [comment]
That's a really small island :) CP found one single node, not much bypassing is going to happen there. Which field it is, if you scroll up you'll see a fieldNum, is that the field you changed?

**Comment by lcc1211** [comment]
No. Unfortunately my field is number 21, so it isn't recognizing anything there.  Field 17 is showing the islands in the report above, but there are none in it.  it is a nearly rectangular field with no objects of any sort in the field.

**Comment by pvajko** [comment]
FYI, just tested this with two other maps: Gemeinde Rade and On the Hills, both work fine, CP detects all islands.

**Comment by lcc1211** [comment]
I think there may be errors on the map.  I will see if I can contact the author.

**Comment by pops64** [comment]
Yeah I know county line map in the editor has some interesting desgin  choices. I can't remember if the whole field is a field including the power poles. I would use the roller to delete the field around the power pole and see if that works
