### ISSUE TITLE
Course to Sell point (question)

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#2516]
I must be missing something as I cannot get this to work.

Example

Course from Farm (milk collection) to Milk sell point.

I've tried 'P' and 'Tip', when the vehicle get to the sell point  it just waits and does not unload.
I make sure that the F1 menu says unload. I've even tried with just driving slowly over the sell point when recording the course, but still no luck

Must be the same process for  Butchers to meat sell point or any sell point?

Many thanks

Happy Christmas

**Comment by pops64** [comment]
Milk is not a supported sell point atm. See #2231

**Comment by alpha117** [comment]
Ok thanks
