### ISSUE TITLE
Sparyer Volume??

### ISSUE THREAD

**Issue by scalpskinner** [Courseplay/courseplay#2518]
As I fertilize the field with CP5 the sprayer is not loosing fertilizer volume.  When I turn off CP5 the volume in the sprayer is then used as I fertilize the field.

Tractor: Magnum CVX
Sprayer: PF 1500 
               Deltis 1302 Mea3

ps: I listed the implements I am currently using but I have tried it with all sprayers in game and all are acting the same.

**Comment by pops64** [comment]
If hired worker does auto refill CP will as well. Change your game settings
