### ISSUE TITLE
Tractor/Tipper takes long to reach Combine on big fields

### ISSUE THREAD

**Issue by JLConradie** [Courseplay/courseplay#2523]
I Don't have an issue ----- Its a Suggestion

Hello Thomas ?
Compliments for the seasons. And all the best for 2018!

I would like to thank you and your team for what has been accomplished over the past 3 months and year with Courseplay.

Courseplay is working very fine with the harvester and Forage Harvester as it is.

My Suggestion:

On huge fields say 80 Hectares or more it can take the support tractor or tipper a very long time to reach the combine.
Regardless the fill level setting and can be set at 5% and still take a while to reach the combine.
If the Combines pipe is in the crops then the support tractor only start driving from the 
Dump route end point at fill level 100% regardless the fill level % setting.

With the great pathfinder function available.. Why cant the same function that apply for the forest harvester apply to the harvester as well.
 
That would save time and clear the dump route for other tractors working on the same field.
The support tractor drive up to the combine stops at say 30m start driving again at 50% stops
at 30 again and so on until the combine reaches the fill level setting %. and drive up to combine to empty.

That would shortened the distance between combine and support tractor regardless the size of the field.
The combine could then harvest the field without reaches 100% fill level or without stopping even once.. Regardless the size of the map. It can work for large and small/smaller fields.

Yes I know there are other functions like fill level and distance which is nice but sometimes it happens that three or 4 or all the support tractors are say 70% the combine reaches 100%. It fills all 3 and say is left with still 80% to empty and reaches 100% while all 3 are away to the dump and then the combine is standing still for a very long time.

As time progresses People can afford bigger and stronger computers and so are their Farm Sim maps. 4X 8X and even 16 times.

Its just a suggestion.. Courseplay is already great as it is.
If other users are reading this.. please leave a comment.
If I'm far-fetched silly or even upside down.. let me know. 

Regards
Louis Conradie

**Comment by Blackmankot** [comment]
Hi I support the offer! I myself often encounter this problem. Good idea!

**Comment by JLConradie** [comment]
Thank You... Blackmankot
I think it would just straitened out allot  of issues.

1) Combines will not stand still for long or not at all.. The tipper will reach
the combine much sooner.
2) It will clear the dump route for other tractors using the same route working and doing something else
on the same field.
3) You only need one route for dumping and not 2 or 3 as the field getting smaller at harvest time.
That's what I'm doing now on big fields, so that the tractor reaches the combine sooner.

So if the tractor/tipper reaches the end point of the dump route.. let it drive to the combine and say stop at 30m and follow the combine as it go's... That would shorten the distance and just speed up the process.  regardless where the combine's pipe is. in or out of the crops. (Down or up run)

And the most useful ---- It will work on big and small fields... The size of the field will not matter. 
 
The code is already there. I think just add it to the combine procedure.

Maybe Thomas will see this and hopefully it would let his thoughts go.
If its not possible or would course some other problems.., then I respect it.

Thanks for the reply.

**Comment by pvajko** [comment]
Sounds like a good idea, I think it would be easy to make the tipper drive to the combine instead of waiting at the last course waypoint. 

But I'd let Thomas do it, I don't want to mess with mode 2 :)

**Comment by JLConradie** [comment]
Thank You!
Very much appreciated.
Thomas fixed a lot of issues with Mode 2 and its really working very well.
Regards
Louis

**Comment by ThomasGaertner** [comment]
ok so we need to make some decisions: what if we have more than one combine on the field and they are not together in one area as it is possible with AIVehicleExtension . which combine should be selected then ? the closest, the farthest , the fullest ? it's not that easy to figure out the best possible one , so I decided in the past to wait on start point for the next calling combine . So I'm looking forward to hear your suggestions...

**Comment by pvajko** [comment]
@ThomasGaertner how about first implementing it for one combine only? 

Also, I'm not sure how it works but I'd expect that on a big field multiple combines will be close to each other so picking any of those, for example the fullest will bring the tractor close to the others too.

**Comment by Blackmankot** [comment]
Happy New Year everyone! My suggestion. When the transport arrived at the rate of transportation of the crop to the field. He finds a harvester and does not lose it until it is fully loaded! The second transport can only find the second harvester, free and also does not lose it until the full load of its own body. After full loading, the vehicle completely leaves the field and only when it begins to move at the rate of transportation of the crop loses the combine. And another transport can already find a fresh harvester. This will exclude the accident on the field of two transports - when one only picks up from the combine, and the second is already going to it.

**Comment by ThomasGaertner** [comment]
@Blackmankot : unfortunately it's not possible because we use the same script for mode3 overloader as well. If you want to fix a tractor to a combine , you can do it with selecting manually, but I don't want to make it fix in the script... sorry
 @pvajko : I do my tests on Cherry Hills with at least 3 combines and with AIVE in circle mode they can be everywhere... :-)
I will think about the topic next year :-) 
maybe we can calculate which time the next combine has left till full  and how long it takes to go there and make the right decision then...

**Comment by JLConradie** [comment]
Hello Thomas
Sorry about the late reply.. away for a couple of days. Summer time and holidays here in South Africa.
your comment --- 
"maybe we can calculate which time the next combine has left till full and how long it takes to go there and make the right decision then..."

I think that would work fine.. the tractor/tipper will then leave for the combine much sooner.
OK Thomas... you do what you think is the right thing... I'll wait patiently.

Thank You so much.
Regards

**Comment by ThomasGaertner** [comment]
@JLConradie : i've made a little script for that . please test it since I will be abroad for the rest of the week and have no possibility to test. please test also with more than one tractors and more than one combines and report 
thanks

**Comment by Blackmankot** [comment]
@ThomasGaertner  Hello! I always specify transport machines manually. And when the first transport works with the specified combine, while waiting for the filling of the bunker, the combine is lost, at this time the second transport, to which I also indicated this combine, may be lost. He also goes to the field and works with him. As a result, on the field just two vehicles work with one harvester. And what happens is described JLConradie -
Yes I know there are other functions like fill level and distance which is nice but sometimes it happens that three or 4 or all the support tractors are say 70% the combine reaches 100%. It fills all 3 and say is left with still 80% to empty and reaches 100% while all 3 are away to the dump and then the combine is standing still for a very long time.

**Comment by JLConradie** [comment]
@Thomas and @Blackmankot  I'll give it a try in more ways than one and report back.

**Comment by Blackmankot** [comment]
@JLConradie Good.

**Comment by JLConradie** [comment]
@ThomasGaertner 
Hello Thomas
Hope your trip was satisfactory.

My Review/Report Back:

I have thoroughly tested the new function on big,large small and smaller fields.
With MODS, MODDED maps, in-game, maps and equipment.

Search for combine on filed.. function.
Great if you have 2/3/4 combines working the same field with 1, 2 or 6 support tractors or tippers supporting.... Trust me I tested it with 3 Harvester and 12 tippers on the same time. There was only a 5 FPS drop throughout my 7 hour gameplay.

One dump route for 2 fields next to each other.  Works Great..!!
For instance... 2 tractors/tippers support 4 combines.. two on each field using the same tip/dump route.. etc. Works very nice!.

Unfortunately, not meant for outline fields. There you just have to go back and assign a combine to a tipper. 

Personally I don't use the convoy function that much because collisions are unavoidable.
For me it kind of defeat the object. 
Scenario: If you have 2 or 3 Combines and 2 fields to harvest.. rather put one combine on each field instead of 2 in convoy mode.  It will take the same time to finish.

I will definitely use the new function from now onwards on bigger or larger fields.

Conclusion:
It still takes a while for the support tractor/tipper to start driving to the very much needed/stuffed combine if the pipe is in the crops/fruit regardless fill % or distance. Whichever comes first. But I must add.. Its already a huge improvement.
The trick.. Larger fields larger or more equipment..

If all Tractors/Tippers are on their way to dump and combine is full and standing still. Just get more tractors to support.

I respect your comments and understand the difficulty level to change this due to the nature of mode2 and courseplay. 

So Thomas.. There you have it.. Sorry for the long message..
Anything to make courseplay better than it already is.
Thanks for the great work done.
Regards.

**Comment by Blackmankot** [comment]
@JLConradie Hi. It's interesting to see your tests! Please write down the video in detail. How to launch a transport on the course, how to tie the harvester!

**Comment by JLConradie** [comment]
@Blackmankot 
Hello..
I'm afraid I don't fully understand your question.. But I'll give it a try.
You have your dump route from the field set-up.
Mode 2 Selected.
Click  the top combine tab. That's called "Manage Combines"
There you have choices.
Click or select "Automatic Search"
Select Manually.. will appear
Choose your combine. You can scroll trough the list of Courseplay registered combines. 
Choose one
That's how you link a tipper to a combine. Then that tipper will only work for that one combine.

But... I think you already know it.

**Comment by JLConradie** [comment]
My Suggestion originality was to shorten the distance between tipper and combine on big fields.

Today I found out how to do it.
The tipper will immediately start to drive for the combine when it reaches the end point of the dump route. Regardless the combine's pipe state. Inside the crops/fruit or outside.. Up or down run.

What to do..
Unfortunately you have to disable or deactivate  pathfinding in the settings tab of each tiper. Set the fill % to 0. Thats it..
If Pathfinding is acrivated and the pipe of the combinde is inside or on the crop/fruit side then the tipper will wait for a 100 % fill level before it will start to drive to empty the combine.

Now.. With the new function and Convoy mode its a total different concept.
On big fields where you can run 2/3 or even 6 combines together with tippers the tippers stay close to the combine's at all times. Thomas did a tremendous job with it. All the planning involved boggles my mind. the tippers are running around supporting the closest combine and off to the next one again.
Where did you ever see that a tipper can think for itself.. Well Thomas solved it.

**Comment by Blackmankot** [comment]
@JLConradie  Clear! I just wanted to know if the harvester is selected automatically or manually. Thank you, you answered my question!

**Comment by ThomasGaertner** [comment]
@JLConradie :so you can't see any better behavior than before my change concerning your initial issue ?

**Comment by JLConradie** [comment]
@ThomasGaertner 
Hello Thomas

Most Definitely YES!..

Yes.. Thomas.. I am seeing really a lot of new futures and changes what you have done to improve mode 2... Well done. you have done good work.

The new future --  Searches for combine on filed.. function. Ver: 51
Works very well and now on a singe combine on filed as well. in Ver: 52.

The Tippers are leaving the end point of the dump route verry much sooner for the combine as it was in previous versions. A HUGE improvement! and a advantage to the game. (Distance and time to travel before combine reaches 100%)

What I have seen is that if the combine is at the end of the field(Field Edge) and the tipper is still on its way to the combine then it does not stop any more to wait for the combine to finish turning and only stops a couple of meters away if the combine is still turning. 
Distance to travel before combine reaches 100% fill level. That must be a very complicated Formula.

A Huge plus point again. Less time is waisted.  

I can carry on... You done a lot in a short time.

What I have noticed is that there is a message that says 
cp.fill litres per second.
The number various. 

Well.. I don't know if it is like this.. 
Maybe CP is already doing it.. 
If CP can control the overloading capacity while overloading onto tipper.. Like for instance.. it empties the combine to say 10% Then keeps it at 10%, so what the combine is harvesting go's into the tipper.
That will keep the tipper driving next to the combine for longer till the tipper reach 100% fill level after that the tipper drives off to dump route, or at the end of the field the normal turn state or stages apply .
The combine is then low enough for the second tipper to reach the combine before it reaches 100%.
Maybe Courseplay is already doing it. I don't know.

Well Thomas.. You have done wonders so far. Its been noticed..
Thank You..

PS.. O Yes.. The traffic avoidance on field is a huge improvement..
Especially in Convoy mode.  Its quite fun to look at and how thy think for themself and the way you have constructed it on how the tippers support multiple combines. And of course.. Pathfinding..

Regards.

**Comment by MoslessNeo** [comment]
In my tests with multiple harvesters:
MAP: XLFarms X3
Harvest with 5 combine in same field with 3 overloaders. 1 with patchfinding desactivate and find combine set to combine #1. The other 2 oveeloaders with patchfinding activated and find combine auto to harvester #2 #3 #4 and #5. Testing....

https://www.facebook.com/xlfarms/photos/a.689965851214362.1073741834.208922122652073/789014694642810/?type=3

With this "formula":
Harvesters in the same field: 1 - 2 --- required 1 overloader
Harvesters in the same field: 3 - 4 --- required 2 overloader
Harvesters in the same field: 5 - 6 --- required 3 overloader
Harvesters in the same field: 7 - 8 --- required 4 overloader

The scheme of combine convoy is amazing, works very well. This way you can avoid collisions between harvesters.
A better system for overloaders is welcome.

**Comment by JLConradie** [comment]
@MoslessNeo
@ThomasGaertner
I had a look at your Fasebook page.. Wow.. You are quit into it..
I wanted to answer you long time ago.. Sorry about that.

You know.. Look at courseplay... now and only 6 weeks ago... What a remarkable difference 
Thomas and his teem did to courseplay.

This is why Farmsim is so popular and a HUGE success. You can play it the way you want it and make it your own.. 
Now Thomas and his teem needed to find a way to even make it simpler. And what a job he did. Solution for every possible thinking scenario. Odd shaped fields with islands ect... What a headache..

The way you play with 3 or more combines in Convoy mode.. Now its no problem for Courseplay.
And must add that, it is quit satisfying to watch the workers do the job..

Thanks for replying on my request and for Thomas what he did to improve Courseplay and for way he did it. 

Thank You
Regards
Louis Conradie
PS.. Happy harvesting.
