### ISSUE TITLE
Combi mode: Tractor will not drive off

### ISSUE THREAD

**Issue by Skojern** [Courseplay/courseplay#2528]
Tractor and tipper starts as it should on the set "start at %". It then drives beside the combine and the combine will empty its tank as tractor drives along. So far so good. 

But when the combine's tank is empty the tractor just keeps following along, not driving to the waitpoint as it should.

What could cause this problem?

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki picutres, logs with debug channel 4

**Comment by pops64** [comment]
Closed due to inactivity
