### ISSUE TITLE
biogas plant movable silo

### ISSUE THREAD

**Issue by STW0701** [Courseplay/courseplay#2529]
Hello. My english is not veryx good. I have a problem with the movable silo at the biogas plant on the map "Nordfriesische Marsch 4fach map v1.3".  I use Courseplay5.02.00050 to filling the silo, by a quarter of filling the silo coursplay show me that the silo is full! Is this a courseplay fault or a map fault? When it is a map fault how can it be repaired?
[log.txt](https://github.com/Courseplay/courseplay/files/1598311/log.txt)
![fsscreen_2018_01_02_19_09_59](https://user-images.githubusercontent.com/34966988/34494557-66c90924-eff1-11e7-9feb-f9a7c5ff58d4.png)
![fsscreen_2018_01_02_19_10_20](https://user-images.githubusercontent.com/34966988/34494561-6f30c192-eff1-11e7-9d61-00f676199b6a.png)
![fsscreen_2018_01_02_19_10_50](https://user-images.githubusercontent.com/34966988/34494569-752195cc-eff1-11e7-9d6c-63046698d945.png)

**Comment by pops64** [comment]
There is an offset setting under the combi mode settings page. Make sure that is zeroed out when you start your course. Has I believe your issue here is the being caused by not enough room left where the chaff is being dumped and it doesn't have any room left to pulled forward because it is at the edge of the silo to begin with.

**Comment by STW0701** [comment]
I tried it with a smaller tipper and i have cleaned the dump area, but it doesn't work. I get the massage that the silo is full.
I tried also with a new course.

**Comment by pops64** [comment]
It may be a map issuse. If remeber correctly theres still a code maximum for the amount chaff that can be placed. Can you manually add more chaff. Could I get a top down view of your unloading course at the bunker

**Comment by STW0701** [comment]
I can manually fill it up to 2 million of chaff. With the map update from 1.2 to 1.3 there was a changing from the tipcolmap and the terrainDetailHeight_density.

**Comment by pops64** [comment]
Can you manually add more chaff at the location CP is trying? Could I get a top down view of your unloading course at the bunker

**Comment by STW0701** [comment]
I can manually add more chaff at the location CP ist trying

![fsscreen_2018_01_25_19_59_49](https://user-images.githubusercontent.com/34966988/35406932-87b4146e-020a-11e8-8d53-c3b24b152900.png)

**Comment by pops64** [comment]
Your course probably isn't far enough back into the bunker. Ensure the last way point is more than half way into the bunker

**Comment by STW0701** [comment]
Now i have tested it by driving through the silo with the same effect. At the same fill level. It only works by setting a tipping point.
![fsscreen_2018_01_28_18_25_24](https://user-images.githubusercontent.com/34966988/35484993-06e625ec-0459-11e8-817f-915609261ec5.png)
![fsscreen_2018_01_28_18_25_29](https://user-images.githubusercontent.com/34966988/35484994-099b749a-0459-11e8-81e2-83224c212b2e.png)

**Comment by evybart** [comment]
i have the same problem with the same map when  cp says the bunkersilo is full then can you not unload anny trailer anny more with cp only when you make a course  with a tipping point he drive in the silo and do nothing and drives back forward with the first course without tipping point these courses Always works with these map thanks no cp no farming

**Comment by STW0701** [comment]
Now i tried it again with backwards tipping with the same effect.
![fsscreen_2018_01_31_19_33_17](https://user-images.githubusercontent.com/34966988/35641390-639b3c14-06c0-11e8-8d20-8400afbaa49a.png)
![fsscreen_2018_01_31_19_48_28](https://user-images.githubusercontent.com/34966988/35641393-65bd70fc-06c0-11e8-8b74-f7d651d6d5eb.png)

**Comment by pops64** [comment]
I am combineing all duplicate threads about tip triggers not working into #2661
