### ISSUE TITLE
Gearbox 4wd supported

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#2534]
Good Morning! My question is whether there will be a support for the gearbox mod! Especially for the four-wheel drive!
LG

**Comment by pops64** [comment]
Drive control is currently supported and has 4wd if you are looking for that kind of feature.

**Comment by Anonymous-any** [comment]
4wd is good but GearboxAddon is a must have !! don't you think ? also 4wd is managed too by gearbox for few times now that mean "drivecontrol" is deprecated to my view.

Best regard

**Comment by Mogli12** [comment]
If vehicle is driven by hired worker or courseplay the standard differentials are used.

**Comment by Anonymous-any** [comment]
As it is explain in incompatibles list mods of Courseplay they say CP is not coded for use gearboxAddon but I'm pretty sure it can be why not? the time for code?
