### ISSUE TITLE
Unable to generate unscanned field

### ISSUE THREAD

**Issue by Anonymous-any** [Courseplay/courseplay#2536]
Hello got that when trying to generate a field where it is not scanned and then not appear in the map field list:
`stack traceback:
	mods/FS17_Courseplay/course-generator/cp.lua:80: in function <mods/FS17_Courseplay/course-generator/cp.lua:80>
	[C]: in function 'ipairs'
	mods/FS17_Courseplay/course-generator/geo.lua:48: in function 'getClosestPointIndex'
	mods/FS17_Courseplay/course-generator/headland.lua:100: in function 'linkHeadlandTracks'
	mods/FS17_Courseplay/course-generator/track.lua:134: in function <mods/FS17_Courseplay/course-generator/track.lua:83>
	[C]: in function 'xpcall'
	mods/FS17_Courseplay/course-generator/cp.lua:80: in function 'generate'
	mods/FS17_Courseplay/generateCourse.lua:85: in function 'generateCourse'
	[string "setfenv(1,FS17_Courseplay); courseplay:generateCourse(...)"]:1: in main chunk
	mods/FS17_Courseplay/input.lua:223: in function 'executeFunction'
	mods/FS17_Courseplay/input.lua:199: in function 'setCourseplayFunc'
	mods/FS17_Courseplay/input.lua:185: in function 'handleMouseClick'
	mods/FS17_Courseplay/input.lua:64: in function 'mouseEvent'
	[string "dataS/scripts/vehicles/Vehicle.lua"]:2239: in function 'mouseEvent'
	[string "dataS/scripts/BaseMission.lua"]:1424: in function 'mouseEvent'
	[string "dataS/scripts/FSBaseMission.lua"]:2137: in function 'mouseEvent'
	[string "dataS/scripts/missions/mission00.lua"]:333: in function 'mouseEvent'
	[string "dataS/scripts/main.lua"]:1861: in function <[string "dataS/scripts/main.lua"]:1845>
`
Best regard

**Comment by pops64** [comment]
What were you doing? I am not sure if the new course gen supports using current course has your field boundary. I would use the old one to plough the field and use the field scanning tool and save that has a field.  https://github.com/Courseplay/courseplay/wiki

**Comment by pops64** [comment]
Closed due to inactivity
