### ISSUE TITLE
Question: Multiple Helpers on one Field (Mode 6)

### ISSUE THREAD

**Issue by matticus9473** [Courseplay/courseplay#2539]
I'm currently using two loading wagons on one large field to collect straw. I have them set up with an unload course but I'm looking for a way to make the second one pick up where the first one left off.

At the moment when one helper is full it goes and empties and when it comes back it begins back where it left off but the second helper has already been through and collected to a point further along the course. This means the first one has to drive a portion of the course picking up nothing until it gets to the point where the second one became full and began its unload course.

Is there a way for one helper to mark where they have left so that the next helper can begin from that spot?

**Comment by pops64** [comment]
You can't do what your trying to do. You have to use the mutli tool function in order to use more than 1 tool on the same field.  https://youtu.be/yoxvpB4dg9M use the same workwidth has the combine workwidth.  This feature does work with manual input of the workwidth
