### ISSUE TITLE
CP doesn't follow path

### ISSUE THREAD

**Issue by lepaul26** [Courseplay/courseplay#2540]
CP doesn't follow path at headlands
See Youtube:  https://www.youtube.com/watch?v=jSUO1qqwWVA

The line to the next "round" is there but the tractor clearly doesn't follow it
This happened with "turn on the field" on and off

**Comment by pops64** [comment]
And the problem is? CP is doing exactly what is being told to do. Which is perform up/down field work. And from the video you still had two more lanes before any kind of headland assuming this was how you had your course generated.

**Comment by lepaul26** [comment]
No because it should follow the headland instead it goes into the field and then comes out again to go into the correct lane

Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________

**Comment by pops64** [comment]
That is the way CP handles that specific turn situation it is because of the steepness of the angle between the two lanes and the work width

**Comment by pvajko** [comment]
See also https://github.com/pvajko/course-generator/issues/26
