### ISSUE TITLE
Add side select when dumping mode 1-3

### ISSUE THREAD

**Issue by franky-bb** [Courseplay/courseplay#2541]
Liebes GITHUB Team.
Ich habe immer wieder Probleme mit den Drehschemel Anhängern, wenn ich an den Entladestellen ablade. Gerne möchte ich 2 HKD 302 an einen Traktor anhängen und mit CP die Früchte verkaufen fahren. Es gelingt mir einfach nicht, den Anhängern eine Abkippseite vorzugeben. Nicht schön ist es, wenn CP versucht den 1. Anhänger hinten abzukippen. Das geht meist schief und der Anhänger wird nicht vollständig geleert. Im GIANTS Forum habe ich das auch diskutiert.
[https://forum.giants-software.com/viewtopic.php?f=885&t=122416](url)
Gibt es eine Möglichkeit, im CP Menü die Abkippseite vor einzustellen.

Bitte nicht schimpfen, dass ich nicht in englisch schreibe.

**Comment by pops64** [comment]
English Please. Support will be limited if this isn't possible https://github.com/Courseplay/courseplay/wiki

**Comment by andreasthu** [comment]
Hy pops64
I think franky-bb means, that the dump down side, who we can set in the game F1menü, tipping left, right, back or the cornwindow, is not be able to used in cp.
When franky-bb set the tipside to left, courseplay tip back or right.
That is not good when the sellstation is on the left side of the trailer.
Sometimes by backtipping the trailer also is  not really empty, there is e few rest of corn left inside the trailer and can only be restless untipped when new corn filled in and than tip it a second time.
Right so the translation?
Lg
Andreas

**Comment by lcc1211** [comment]
I believe he is having an issue with dual trailers on the same tractor.  CP seems to be dumping the fruit from trailer one into the 2nd trailer and thus one of the trailers is not completely emptied.  @franky-bb Du solltest ein paar Fotos geben, besonders weil @pops64 und andere Leute hier koennen Deutsch nicht verstehen.

**Comment by ThomasGaertner** [comment]
I disabled the fix assignment because we had several issues with trailers not tipping because the manually selected side was not in the trigger. @franky-bb : can you make screenshot of the situation , when the trailer is not completely empty. I've never seen it before and 2 HKD is my standard setup for multi trailer tests. thanks

**Comment by franky-bb** [comment]
Have now go through 2 trailers several times. The trailers were always unloaded on the left side. So always without mistakes.

Post can be closed.
