### ISSUE TITLE
Game loading issue

### ISSUE THREAD

**Issue by Phantom742** [Courseplay/courseplay#2545]
Hi,

i've got a issue while loading the game with courseplay. When I load the game without Courseplay it takes a minute to load the game. When I load the game with just a couple of courses, loading will take a bit longer. But sine I play cornbelt map and use a lot of courses, loading takes up to 25 minutes. Genarally, the more courses I use the longer it takes. I tested it with other vanilla maps as well, same issue. Anybody having the same issues?

Greets

**Comment by pops64** [comment]
Sounds like you have a separate issue from CP or your computer is barely meeting the minimum requirements. If it is a x16 map stay away from savings auto generated course. Has these have high number of waypoints which hads to load time

**Comment by Phantom742** [comment]
I ia a brand new Ryzen 7 1700 amd a MX580 running on SSD disk. It has nothing to do with the computer. Like i said, it takes barely a minute when i load the game without CP. I only have the issues with courseplay. Are there any settings maybe?

**Comment by pops64** [comment]
If it is a x16 map stay away from savings auto generated course. Has these have high number of waypoints which adds to load time. You would have to have super computer in order to load x16 auto generated courses.

**Comment by pops64** [comment]
Closed due to inactivity
