### ISSUE TITLE
jacknifing

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/courseplay#2546]
CP tries to back up an implement... with a quadtrac... leading to jackknifing

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by lcc1211** [comment]
@Commissar0617 Does this issue sound like the same one you're experiencing?   #2396

**Comment by pops64** [comment]
Could be any thing which is why everyone needs to follow https://github.com/Courseplay/courseplay/wiki. Although if your using the quadtrac why are you backing up a implement? Most implements for this tractor can't backup any ways

**Comment by pops64** [comment]
Closed. Will reopen if https://github.com/Courseplay/courseplay/wiki is followed
