### ISSUE TITLE
Multiplayer-CP- game crash

### ISSUE THREAD

**Issue by DrDoofenshmirts** [Courseplay/courseplay#2550]
-----------------------------------------------------------------------------------------------------------
LOG:
### CourseplayMultiplayer: reading 0 custom fields 
	### CourseplayMultiplayer: courses/folders reading end
Error: Running LUA method 'mouseEvent'.
C:/Users/Kille/Documents/My Games/FarmingSimulator2017/mods/FS17_Courseplay/CpManager.lua:177: bad argument #1 to 'pairs' (table expected, got nil)
-----------------------------------------------------------------------------------------------------------
Hello, I play with my friend on local multiplayer. 
When I join for first time everything is fine, but when i would like to join again after buying machines, the game stop loading at this point: """ ### CourseplayMultiplayer: courses/folders reading end """, when I 
synchronize with him. When i try to disconnect the game crashes.
Maybe you can look at it or fix it or something, Thank you :D

**Comment by pops64** [comment]
moved #2502
