### ISSUE TITLE
Suggestion for Headland turns

### ISSUE THREAD

**Issue by NexX0** [Courseplay/courseplay#2552]
So i am playing on the Nordfriesischen Marsch x4 map and as a lot of fields got trenches around them some Tractors get stuck in them if they pull a manure spreader or something similar like that.

So i recognised that in my case the Manure Spreader

1. - Goes over the field boundary until the field behind him is covered.
2. - Backs up until he can turn.
3. - Turns and straighten up itself.
4. - Backs up again to field boundary. 
5. - Drives forward and continuous work.

![farmingsimulator2017game_2018-01-17_18-58-09](https://user-images.githubusercontent.com/30878460/35071009-989bb60a-fbdf-11e7-829d-94276bffcdc3.jpg)

So i would suggest that the Manure Spreader should skip step 1. and 2. and start with the turn, straighten up itself, backs up and then continuous normally. It could be determined by turning inside the field or outside.
As for the work coverage it should make no difference as he basically is doing the corner twice.
This would actually help with fields where there is a wall or fence nearby.

But I don't know if it would be possible as i don't know how you guys handle the tools in general and whether they can be reversed or not.

**Comment by pvajko** [comment]
As a workaround you could just use the 'smooth' turns, at least for a manure spreader it should be ok to miss a small area in the corner.
