### ISSUE TITLE
Issues with AI Vehicle Extension

### ISSUE THREAD

**Issue by FendoRichter** [Courseplay/courseplay#2553]
Hey,
i use coursePlay together with the AI Vehicle Extension an i got some issues with the Combi Mode.
After empty the harvester it looks like the coursePlay helper takes the next waypoint from the AI Vehicle Extension helper and drives arround this point. He also blocks the AIVE helper with this.

For me the AIVE helper works much better for the harvester than coursePlay because my fields are not realy square.

Versions:
AIVE: 1.1 b26
CP: 5.01

**Comment by pvajko** [comment]
Please note that if you select 'current vehicle position' as the course start location when generating then CP generates decent courses for odd shaped fields as well.

**Comment by pops64** [comment]
Are you really running version 5.01? It should be 5.02(release) or 5.02.055(beta) https://github.com/Courseplay/courseplay/wiki

**Comment by FendoRichter** [comment]
Ok. The readme says 5.2.0.0
Then the changelogs from the homepage are not up to date.
Sry

**Comment by pops64** [comment]
I know the readme for the beta is not correct is says 4.01. The release readme is correct. I always look in the moddesc anyways has this what giants looks at. If you posted a log I could tell you what version your running. Also a picture of how it is miss behaving.

**Comment by pops64** [comment]
Closed due to inactivity
