### ISSUE TITLE
Problem setting up mode 10

### ISSUE THREAD

**Issue by Iemand999** [Courseplay/courseplay#2554]
Hello I wanted to set a course for clamping a silage pit in the Estencia lapacio map but every time I set up a course the tractor get stuck on the left side with te blade. I used different tractors and different blades but the issue keeps accuring. Is this a bug or is this a known issue, I set up the courseplay just as it is described in this youtube video https://www.youtube.com/watch?v=5EG59jbEtkg.

https://ibb.co/gTQ0Ww  <picture

**Comment by pops64** [comment]
Did you adjust your blade width setting? Full Picture of your course

**Comment by Iemand999** [comment]
The blade with is automaticly 3m, should I adjust smaller of wider?

**Comment by pops64** [comment]
in mode 10 the blade width must always be manually set. There should be a red line that apperas when you increase/decrease this. Increase the setting until it matches the width of the blade. 4.5m for the smaller one and 5.0m for the large if I remember correctly. Increase it to prevent it hitting the wall, decrease it to get closer to the wall. If it is too large of a number it wont get the sides, if it is to small a number you will run into the above issue.
