### ISSUE TITLE
Maximum Worker Problem

### ISSUE THREAD

**Issue by Ultronkalaver** [Courseplay/courseplay#2556]
[log.txt](https://github.com/Courseplay/courseplay/files/1665581/log.txt)
Lets try to explain in english:

Courseplay Version 5.02.00055
Game Version 1.5.3.1
Map Mustang Valley Ranch

I have 16 activ workers with the course. They do there jobs.
I have 8 workers from the game and they do there jobs too.
But after I activate another one in the courseplay these one doesnt work. I can click, nothing happend 
except the tractor is blocked. Cant use it anymore. If I am then deactivate or activate another worker over the courseplay menu these one doenst work too.
I can restart the game and the 16 workers will do there job but then the "game" starts again.

Hope you can understand my problem.

DebugMode 12+14 activ for you. Maybe helps
[log.txt](https://github.com/Courseplay/courseplay/files/1665582/log.txt)

**Comment by pops64** [comment]
http://modcentral.co.uk/resources/game-extension.102/ . There is a upper limit set by giants with how many workers you can have. Use this mod to change that number

**Comment by Ultronkalaver** [comment]
Thank you very much. But the problem is still there. no change.

**Comment by pops64** [comment]
There is nothing we can do then. Has the CP code is relying on a Giants function to provide certain AI attributes when it starts. So if it is not providing any more AI there is nothing we can. At a later time we might add a better handling of this error but it isn't a priority 24 workers is a lot to begin with any ways.
