### ISSUE TITLE
Course Generator - Big Islands and Manual Direction

### ISSUE THREAD

**Issue by pvajko** [Courseplay/courseplay#2560]
Quick update on some new course generator functions in v5.02.00056:

**Big Islands**

When any of the island bypass modes is selected, the generator will now handle really big islands (wider than 6 * working width) too. Instead of simply bypassing them, big islands will have their own headland rows and the up/down rows will turn at the headland just like at the field boundary.
![island2](https://user-images.githubusercontent.com/2379521/35488133-56dbb496-0449-11e8-9ca4-8e1af023bd05.PNG)

You'll see a longer generation time and a bit more driving on the field as the generator will have to split the field into blocks in such cases:
![info1](https://user-images.githubusercontent.com/2379521/35488148-8ac05f0a-0449-11e8-9a9b-f203c858a98a.PNG)

 In this example, it starts above the island, then to the right, then below the island and at last the left part of the field. Before it starts with the left, it works the headlands around the island.

** Starting Direction **

This can be Automatic, Longest edge and Manual. You know the automatic already, it'll pick the best angle to work at resulting in the minimum number of turns and idle driving around:
![info2](https://user-images.githubusercontent.com/2379521/35488200-38c5bef6-044a-11e8-8cec-5ff155c71500.PNG)
I recommend using the Automatic mode as it will most likely result in a course that your vehicles will be able to drive nicely.

Longest edge mode tries to align the rows with the direction of the longest edge of the field. In most cases this will be the same what the Automatic mode comes up with but sometimes slightly different, like here:
![info3](https://user-images.githubusercontent.com/2379521/35488216-93fbe0d4-044a-11e8-992b-b19f1c9fc1d1.PNG)
In this last case the course generator will warn you that the generated course is not optimal and may cause issues but lets you continue anyway. Here, note fractional rows in the northwest and northeast corners of the field due to the northern edge of the field bulging in. This means the field can't be work in a single pass and has to be divided into blocks and that's the reason the automatic mode did not select this solution.

Finally, you now have the possibility the set the angle manually, currently in 22.5 degree steps but if folks want a higher resolution I can change that easily.

There are a two known bugs I'm working on: 1. the ridge markers on the island headland are not turned off, 2. there'll be some hickups when the island headlands cross the field outer headlands

**Comment by frm274** [comment]
Great improvement, thanks!
Ive set the steps to 5.6 degree and i think i will do 2.8 for perfect courses. 
But as an example:
Old course with hardcoded angle, new one with 5.6 degree step.
<a href="https://www.pic-upload.de/view-34757945/bestAngle.png.html"><img src="https://www2.pic-upload.de/thumb/34757945/bestAngle.png" title="Bild hochladen" /></a>
Btw, new one cuts the island!

**Comment by pvajko** [comment]
That sucks. Which field on which map is that?

**Comment by frm274** [comment]
Selfmade fieldborder on "Gemeine Rade".

Your new scrollable 1 degree step is perferct!

But, generating an automatic track with "actual Vehicle position", i can only choose "Endposition:" not "Startposition"!?

**Comment by pvajko** [comment]
If you work on the center of the field first and finish with the headland (for example when sowing) then it'll finish it at the current position. 
If you select working on headland first (harvesting) then the course will start at the current vehicle position.
