### ISSUE TITLE
Moro Raptor EXA mod problem

### ISSUE THREAD

**Issue by SuBerPL** [Courseplay/courseplay#2563]
Hello I found some problem with plow Maro Raptor EXA.  Courseplay worker is not rotates plow. 
Link to mod: https://www.modhoster.com/mods/moro-raptor-exa#description
It is the same plow like original in game.

**Comment by dicktimmerman** [comment]
Noticed the same Issue, The moro raptor ploughs are not rotating with courseplay. If you use the std helper in FS17 it is turning correctly

**Comment by pops64** [comment]
added to the list
