### ISSUE TITLE
Amazone Sprayer Leaves Large Portions of Field Untreated

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#2567]
Playing on Hobbs Farm v4.5
Using Vanilla Massey Ferguson 8700 with MOD Amazone UX 5200M 40.
The sprayer will not move all the way to the end of the lane. I have a single headland set.  This mod is available in the MODs section from within the game.
[log.txt](https://github.com/Courseplay/courseplay/files/1691351/log.txt)
![20180202220256_1](https://user-images.githubusercontent.com/24764870/35762512-9291195c-0865-11e8-84cc-4bcbfe2b57ff.jpg)
![20180202220301_1](https://user-images.githubusercontent.com/24764870/35762513-929eda24-0865-11e8-81d5-3b289a008100.jpg)

**Comment by pvajko** [comment]
Please follow https://github.com/Courseplay/courseplay/wiki#how-to-post-your-field-definitions

**Comment by lcc1211** [comment]
Nothing happens when I press the tilde key.

**Comment by pvajko** [comment]
See #1 at https://github.com/Courseplay/courseplay/wiki#how-to-post-your-field-definitions. Don't know how to make this clearer.

**Comment by pops64** [comment]
This is most likely an issue with the back and front marker offset. Take a picture with debug channel 6 active after the first turn. Top Down please

**Comment by lcc1211** [comment]
@pops64 Sorry I haven't responded. I have not been receiving notices. I have found them in my junk mail instead. I will go back in the game soon and do this and then attach the game log.

**Comment by lcc1211** [comment]
Today it isn't leaving quite as much undone, but I just updated to the latest dev version as well.
[log.txt](https://github.com/Courseplay/courseplay/files/1745231/log.txt)

![20180221131057_1](https://user-images.githubusercontent.com/24764870/36497854-83706e1a-170a-11e8-9fef-7f8aab606467.jpg)
![20180221131057_1](https://user-images.githubusercontent.com/24764870/36497861-87b0d938-170a-11e8-8b6c-3d8a27aa4446.jpg)

**Comment by lcc1211** [comment]
![20180221132224_1](https://user-images.githubusercontent.com/24764870/36497916-c1501028-170a-11e8-9281-8c7d8ea14a63.jpg)
![20180221132345_1](https://user-images.githubusercontent.com/24764870/36497920-c3c9446e-170a-11e8-9a85-532fdc7ac1e6.jpg)

**Comment by pops64** [comment]
What do your waypoints look like. Has this probably is a cousegen issuse. Try with the old one as well. The parallel red lines show we're the stop and end markers are for your tool. And they look right ethier way there not far enough apart to cause this issue

**Comment by lcc1211** [comment]
The waypoints are where I would expect them to be. The tractor appears to be centered on them.  This particular mod used to be set at 24 meters by CP, but after a few updated dev versions it counts it as 36.2.  Giants and the mod maker say it is only 36.

**Comment by pops64** [comment]
The width wouldn't effect this. And it is 36.2 because CP ussally detects correctly what nodes are used to change the field area into the next stage. I would still need to see the waypoints relative to where is stopping short
