### ISSUE TITLE
Svapa Agro no load/unload

### ISSUE THREAD

**Issue by gentfarmer** [Courseplay/courseplay#2569]
Set up a liquid transport mode to transfer oil from the oil wells on Svapa Agro but the tanker does not load any oil. If I manually load oil and run the course the tanker will not unload at the unload point.
I have a similar problem on this map trying to load/unload sand and gravel using the grain transport mode and I am selecting the correct "fruit" i.e. sand or gravel.

Can you offer any help, please?

**Comment by gentfarmer** [comment]
Just tried the combie mode to unload a sugar beet harvester and tip to a storage bin. When the trailer gets to the unload point it stops and does nothing, I have to "stop the driver" and then manually unload.
I suspect the problem is caused by an incorrect tip trigger (and possibly an incorrect fill trigger for the oil wells) because "I" key tips instead of the usual "R" key.
What do I need to look for in the map triggers?

**Comment by pops64** [comment]
Well if there is a tip trigger no unload point is needed. If it the tip trigger accepts the loaded fill type it will unload. Has for mode 8 see #2231
