### ISSUE TITLE
Trailer not unloaded completely in BGA silo

### ISSUE THREAD

**Issue by bigjoker76** [Courseplay/courseplay#2570]
Gentlemen,
I´m playing the Cherry Hills map and having problems while reverse unloading into bga silo. The trailer (vanilla) will keep a small rest of chaff (31l) and then starts driving forth and back all the time. When I stop CP and restart it, CP drives away from the silo until the next unload procedure. I tried it with all mods switched off, but no change. On other maps it seems to work normal
[log.txt](https://github.com/Courseplay/courseplay/files/1697749/log.txt)

I´m also not sure if it belongs to the definition of the silo in GE, like "interactionTrigger" and "bunkersiloarea", but when I compare to other maps, it looks the same for me.

Is it possible, as a workaround, to allow a little rest (maybe 100 l) in the trailer until CP starts again?

Thank you for your help!

Regards Jochen

**Comment by pops64** [comment]
Sorry for the delay in responding. If i remeber correctly it should already be set to ignore a small amount left. And if it get it to work in other maps that it shouldn't be a course setup incorrectly. It may be the way the trigger is set up in that map. Could we get a video or pictures of how you have your course and what it is doing thanks.

**Comment by bigjoker76** [comment]
![2018-02-28](https://user-images.githubusercontent.com/6426554/36785643-d3a8b8e6-1c83-11e8-851e-1c9ae685af65.png)

**Comment by pops64** [comment]
Try pulling straight out and turning at the last possible sec. I know if leaving isn't straight until it is done you run into issues. I can't remember if reverse is the same way.

**Comment by pops64** [comment]
I am combineing all duplicate threads about tip triggers not working into #2661
