### ISSUE TITLE
plowing

### ISSUE THREAD

**Issue by RolnikHades** [Courseplay/courseplay#2572]
What is the plug not rotating when plowing?
![fsscreen_2018_02_11_08_26_33](https://user-images.githubusercontent.com/36358018/36070921-b60ce98c-0f05-11e8-9aea-77b7004cbcbb.png)

**Comment by pops64** [comment]
Mod that is supported. https://github.com/Courseplay/courseplay/wiki

**Comment by RolnikHades** [comment]
It's good that I do not see anything about AgroMasz. I checked with a clean game and the same happens only with original machines

**Comment by pops64** [comment]
Are you only checking after the first turn? You have to wait at least 2 turns to check to see if the plough rotates correctly. You may be on a lane where the next one is the at the same rotation has what you started with. Has CP currently doesn't set plough rotation correctly on course start it takes at least 2 turns for it to catch up

**Comment by RolnikHades** [comment]
I tested it with a clean game without any mods and still the same zero reaction to rotation

**Comment by KITT3000** [comment]
I also have the same problem with this plow. The whole field did not turn the plow at all, I tested the same on the basic plows Kuhn VariMaster 153 and Amazone Cayron 200 and operate correctly. Unfortunately, the channel 17 does not provide any information about the state of rotation of the plow.

**Comment by KITT3000** [comment]
@pops64 *beep*

**Comment by UserB4D** [comment]
@pops64, I checked. I sent him and watched all the time, how he works, every time the plow was in the same position (he did not turn it). 
Regards ;)

**Comment by pops64** [comment]
Closed #2909
