### ISSUE TITLE
Mode 2: Turn Maneuver

### ISSUE THREAD

**Issue by frm274** [Courseplay/courseplay#2573]
<a href="https://www.pic-upload.de/view-34823187/TurnBug.png.html"><img src="https://www2.pic-upload.de/thumb/34823187/TurnBug.png" title="Bild hochladen" /></a>

-Automatic generated field course, 14,5m lanes. 
-Chopper turns fine (blue line)
-Tractor does a wide turn, an heads in the last chopper lane, reverses, but is too far away from chopper (chopper waiting for trailer), heads forward turns left an crashes into chopper. (red lane)
-> Maybe tractor should get the horizontal distatnce from chopper for reversing!?

**Comment by Raints** [comment]
Is your working width set 14,5m in forage harvester?

**Comment by pops64** [comment]
Closed due to inactivity. And the post by Raints should fix this issuse
