### ISSUE TITLE
Moveable Course field overview

### ISSUE THREAD

**Issue by JuicedEagle** [Courseplay/courseplay#2574]
Hi guys!

Would It be possible to make the generated Course field overview moveable? (when you press the eye button on the Course control) Just moveable like the main hud, in the xml generated file in your savegame.

Here's a picture of my current problem, playing 5760x1080 resolution.
![27990437_10216077275470395_117153374_o](https://user-images.githubusercontent.com/18746053/36071778-3e9d0e5e-0f14-11e8-8b54-0885b15dcb02.jpg)

**Comment by pvajko** [comment]
Have you tried to just drag it with the mouse? Should be working.

BTW, what course generator settings are you using, it should not cut through that wooded area on the northwest.

**Comment by pops64** [comment]
It looks like the release version and the old generator

**Comment by JuicedEagle** [comment]
@pvajko Thanks alot! I really didn't know you could that. That helped alot!
I'm using the version that's on modhub.

@pops64 you're right. 

on the particular field, I ploughed some more of that corner, so the field edge path isn't updated. haven't got that fixed yet.

Should I go for the latest dev version to get generator of the field course?
![unavngivet](https://user-images.githubusercontent.com/18746053/36086079-59ed6076-0fca-11e8-9733-405d05c7bf52.jpg)

**Comment by JuicedEagle** [comment]
So, I just tried the latest version on here.
Tried with my newly purchased field (Field 64 on Lossberg map) 
This is the generated field for seeding.
![fsscreen_2018_02_12_08_13_03](https://user-images.githubusercontent.com/18746053/36086444-b4a4879a-0fcc-11e8-80e1-fa23f9b86bf3.png)

**Comment by TinyCrocodile** [comment]
This is normal because only the Course from tractors position and last used position will use the new Coursegenarator. 
The other settings still use the old Coursegenerator wich has no island avoiding.

**Comment by JuicedEagle** [comment]
@TinyCrocodile Well I really didn't know that. :)
