### ISSUE TITLE
Ploughing and going round in circles 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#2576]
hello im currently plowing and im having troubles with tractor going to next row it gets to the end and does endless circles very frustrating  please help
![fsscreen_2018_02_11_16_43_04](https://user-images.githubusercontent.com/27097241/36075715-a7f26562-0f4a-11e8-95c4-71f37c470724.png)

[log.txt](https://github.com/Courseplay/courseplay/files/1714598/log.txt)

**Comment by pvajko** [comment]
https://github.com/Courseplay/courseplay/wiki#how-to-post-your-field-definitions

**Comment by matty2123** [comment]
[cpFields PLEASE READ.txt](https://github.com/Courseplay/courseplay/files/1714675/cpFields.PLEASE.READ.txt)

**Comment by matty2123** [comment]
Ive posted it ive just been doing Field 7 and it did it with field 55

**Comment by pvajko** [comment]
Awesome. Now we only need your course generator settings.

**Comment by matty2123** [comment]
its also field 9

**Comment by matty2123** [comment]
how do i do that

**Comment by pvajko** [comment]
Write down here whatever you set in the course generator tab. Width, turns, islands, etc.

**Comment by matty2123** [comment]
![fsscreen_2018_02_11_18_23_56](https://user-images.githubusercontent.com/27097241/36076778-c1dd23d2-0f58-11e8-820c-5c50027bbce6.png) 

Thats the setting ive been using on the pic

**Comment by pvajko** [comment]
Don't think so because island bypass seems to be on when looking at the map.
Also, where exactly does it circle? Just at that specific spot or everywhere?
What kind of plow is this exactly?

**Comment by pvajko** [comment]
Or maybe you can post a video with debug channel 14 turned on and the course made visible so we see where exactly this happens.

**Comment by matty2123** [comment]
ok ill try that the plow is salford 8312

**Comment by matty2123** [comment]
whats the best way to upload a video on here

**Comment by matty2123** [comment]
couldn't get a video on here but cultivator is now doing it got a photo
![fsscreen_2018_02_11_19_25_13](https://user-images.githubusercontent.com/27097241/36077330-6d4bdb02-0f61-11e8-8299-c698d89a5141.png)

**Comment by pvajko** [comment]
We'll need some kind of hint when exactly this happens and if it is a problem with vanilla equipment too or just with mods.

**Comment by matty2123** [comment]
When it’s finished a row and starting to turn for next row it’s gets confused and does circles I then have to stop it and get it back on course. I’m using vanilla equipment with MR installed

**Comment by pvajko** [comment]
Ok, all rows, random rows or some specific ones?

Happens without multiple tools as well?

**Comment by matty2123** [comment]
Random ones and I’ve not tried it on there own there big fields so like to setup multiple plows

**Comment by pvajko** [comment]
Please post a savegame: https://github.com/Courseplay/courseplay/wiki#how-to-post-a-savegame

**Comment by shadow250** [comment]
just throwing this out there. did you try with turn on field deactivated? worked for my but it does it only with large plows.

**Comment by matty2123** [comment]
It’s doing it on on the tedder cultivator also I’ve just learnt to live with it but will try what you said Shadow250

**Comment by pops64** [comment]
Have you adjusted the the turning radius?

**Comment by matty2123** [comment]
No I haven’t

**Comment by pops64** [comment]
What is it setting the turn radius to? Picutres and log with debug 12 and 14 active

**Comment by matty2123** [comment]
is that the turning circle? if so its 12m auto and ive got a picture of cultivator doing circles tonight 
![fsscreen_2018_02_18_20_52_42](https://user-images.githubusercontent.com/27097241/36356735-0df0f790-14ee-11e8-8ff7-d562773511e1.png)
[log.txt](https://github.com/Courseplay/courseplay/files/1735109/log.txt)
log with 12 and 14 active

**Comment by pvajko** [comment]
Try with 5.02.00059 or later. Tried to make long turns better in 5bc76e37b6db8f0f2c93930b8b51d0608230aa29 but looks like our turn system can't handle that.
Sorry.

**Comment by matty2123** [comment]
No need to apologise. It’s sorted the problem keep up the good work.
