### ISSUE TITLE
Course Generator Wishlist

### ISSUE THREAD

**Issue by pvajko** [Courseplay/courseplay#2577]
I may have some creative energies left so was just wondering what are the most wanted course generator enhancements or fixes folks would like to see in Courseplay?

**Comment by TinyCrocodile** [comment]
Hi
Good Question. 
Thank you verry much for the new Coursegenerator it is an awsome tool!
I was thinking about this .
Here are my ideas:

1. More starting/ending Positions  for example:
- Starting form N,W,S,E Points with the new Course generator 
- Starting form a predefined Startingpoint wich can be saved for every field 

2. Mor information why the course-generating from a loaded course fails. 
- Sometimes it works to create a Fieldcourse from a recorded course with the new generator 
- When it doesent work it would be great to have som information why it did not work so one can change it and retry 
- If i have more time i will provide some more information on this...

3. Option to change the overlap of up/down-tracks with the headland
- In some cases Sprayers and other tools leave some holes when between up/down-tracks and headland
- Not on every tool it is possible to get this working with the vertical tool offset so a overlapp setting in coursegenerator can fix it.

**Comment by pvajko** [comment]
1. N/W/S/E: noted, that shouldn't be a problem. Regarding the predefined one, CP saves the last position used with the vehicle, I understand that this is not what you want, you'd like to be able to save a position for the field itself?

2 Honestly I barely tested it with loaded courses. What you see is most likely a bug, feel free to open an issue just make sure you attach the course.

3. The course generator logic can do that already and it only needs to be hooked up to the HUD. Which may be a challenge, there's not much room left on the course gen page. Will see what we can do.

**Comment by TinyCrocodile** [comment]
> you'd like to be able to save a position for the field itself?

Yes exactly so i can use the same starting/endpoint for every workwith wich i may use. Even if i change between fields and tools and so on. 
Would it be possible to save it to the custom field xml ? Or somthing like this.

>feel free to open an issue  
ok i will  do it this evening.

Thank you!

**Comment by abehnke** [comment]
An option to generated the course with no turn maneuvers. I am probably the only one that is not too concerned about missed spots when working a field.  But am annoyed with all the back and forth driving some equipment does to get lined up for the next row of the up/down.  For example, a 8.3m tractor with mowers has a turn radius that can just go directly from one row to the next with  little missed parts left behind.  

Thanks for all the fine work on the course generator!  The last fix for the overlap looks good.  The courses are beautiful.

**Comment by TinyCrocodile** [comment]
For Number 2 
I have not been able to reproduce this with newest dev version

**Comment by pvajko** [comment]
> An option to generated the course with no turn maneuvers. 
That'd probably be better as a drive setting so course would always have them but you could override when starting the vehicle on the course?

**Comment by mdbguy** [comment]
![image](https://user-images.githubusercontent.com/32879507/36149762-624c1b4a-1097-11e8-8368-56ca6233514d.png)

Not specific to course generation but a tool to edit existing course would be very handy.  In a case such as this the course generated is almost perfect except a few waypoints and turns cause collision and ability to manipulate the course would be very nice.  Anyone have suggestions for up to date existing editor?  I have tried coursedrawer and ycourse but they seem to be out of date and /or tricky to work with.

**Comment by zed636** [comment]
Hello, thanks for the new Coursegenerator, great tool!
I was thinking about this: could you genereate the headland manouvres only for the short field edge and for the rest of the field use the up/down manouvres like the image here? It would be useful because CP don't have to calculate the turn from the longest edge of the field to the short that causes much unworked zone in my test...

![cattura](https://user-images.githubusercontent.com/19471664/36207358-e4aa293e-1195-11e8-93ec-ec476b2a946f.PNG)

if it is possible to select when the machine make the headlands, before or after up/down course and number of them

**Comment by pvajko** [comment]
Looks great on a rectangular field, could be a challenge on irregularly shaped ones. Added to my [project](https://github.com/pvajko/course-generator/projects/1)

**Comment by JDTiger** [comment]
I'd like to see a feature to create courses, where the pipe of a combine always points to the outside of the field...

so the combine would drive a row, pick up the header, got over to the other side of the field and combine the row on the other side of the field.

this would be advantageous for long fields, where the combine can't hold the harvest of one row in its graintank

**Comment by pvajko** [comment]
This is what you suggested in #2333, correct?

**Comment by JDTiger** [comment]
yep, and one other time before :P just thought i'd post it in this thread again...

**Comment by lcc1211** [comment]
I would love to have my combines start at the beginning of the first lane instead of driving several meters into the field then lowering the header.  I can get around this only by doing a headland row.

**Comment by pvajko** [comment]
@lcc1211 yeah, that's annoying. But it's not a course gen problem. We'll see what we can do.

**Comment by pops64** [comment]
@lcc1211 I don't think it will be possible because it would require a major revamp of certain things that have been set that way before most of the current team joined the project. Basically waypoint 2 is the official start of the fieldwork. Which is why you get that gap with tools on the front of the vehicle and no gap if it attached the rear

**Comment by Haiya-Dragon** [comment]
I'd love a solution to the situation where a combine is harvesting a field, followed by vehicles to bale and collect straw (via FollowMe mod), and a tractor is collecting the crop from the harvester in mode 3. What generally happens is that the vehicle in mode 3 wants to park right behind the combine, resulting in a deadlock with the FollowMe vehicles.

Since a picture speaks volumes: 
![untitled](https://user-images.githubusercontent.com/27687164/36402692-9c8a5080-15e0-11e8-82a4-9d328e19fd84.png)

**Comment by Crytiv** [comment]
The ability for the tractor to detect not only the machines, but the other objects as well and try to avoid/drive around them. In example - a   tractor pulling a fully loaded trailer across the field, which has a single pole or a tree in the middle, the tractor doesnt recognise its an obstacle and tries to drive past it and ofcourse gets stuck. Also, the ability for the tractor to see the boundaries of a field that the harvester is working in and limit them to not cross these boundaries, would be a nice addition too.

**Comment by pvajko** [comment]
@Crytiv I fully agree, unfortunately most of these are mode2 issues where other CP developers are much knowledgeable than I am. 

However,  there are a few cases where we use pathfinding when driving on the field and there I will add island avoidance:
- in mode2 the tractor drives to the combine to unload across the field
- in mode2 when the trailer is full 
- returning to the starting point in fieldwork mode with the new course generator
- driving to the first waypoint across the field with the align waypoint mode on.

**Comment by pops64** [comment]
I know for me I setup CP to collect straw left by the havester. So I can wait until the havester is at least 4 to 5 lanes ahead. So I rarely run into this conflict. It also lets me use the forgage wagon with unloading course so I don't I have to deal with bale storage. Eventually we will improve the bale collector but atm you have to clear the bales manually so the next unload doesn't run into them

**Comment by pvajko** [comment]
@JDTiger 

> so the combine would drive a row, pick up the header, got over to the other side of the field and combine the row on the other side of the field.

This is actually easy to implement but I have a few questions.

> this would be advantageous for long fields, where the combine can't hold the harvest of one row in its graintank

 This can also be achieved by increasing the number of headlands until there is no room for the up/down rows. Is there any reason that wouldn't work?

Now, if I implement this what would be the direction of the rows? Would you expect using the same direction you select (either manually or automatically) as the starting direction?

**Comment by Haiya-Dragon** [comment]
In mode 4, it would be nice to have the seeder/fertilizer open the cover in case it's empty and there's no refill course set. This way, the vehicle doesn't need to be manually stopped just to open the cover in this situation. Thanks :)

**Comment by JDTiger** [comment]
@pvajko 1. yes, it would be possible, but the combine would always have to make the 90°Headland turns, or leave cornes of fruit, both of wich i don't particularry like...

2. if possible it should be like "left side out"/"right side out" since the auger could be on both sides... if that isn't what you meant, please explain further :P

**Comment by pvajko** [comment]
@JDTiger 

> both of wich i don't particularry like
There'll be the exact same number of 90 degree turns in this pattern too, so how do you envision the combine taking those? 

> that isn't what you meant, please explain further 
Left/right side can be handled with clockwise/counterclockwise. What I meant is the geographical direction of the rows, basically the direction of the long edge of the field which is obvious as long as it is a rectangular field. But never mind, I decided to take the starting direction setting.

**Comment by JDTiger** [comment]
1. just turn 90° to the left, run down the headland at full speed, then 90°left and into the next lane, as opposed to end of the row, backing up, 90°turn, backing up, working headland, end of headland backing up, 90°turn, backing up next lane...

2. ok, if you meant that, then i wanted what you do now

**Comment by pvajko** [comment]
> just turn 90° to the left, run down the headland at full speed, then 90°left and into the next lane
Sounds great on paper. It may not work out so nice in reality, depending on the turn radius and work width there may be some fruit left...

**Comment by JDTiger** [comment]
the behaviour schould be jus as it ios now if CP does a 90° run down headland,90° turn, as it does with slurry tanker of workwidths of about 30m...

**Comment by pvajko** [comment]
Any idea how to switch to this long/narrow field mode on the HUD?

**Comment by JDTiger** [comment]
1. thanks for the work
2. is it possible to switch to the mode via the starting direction button?
3. i have not tested it yet, but will do so today, but if it works like i think it works now, i may have had a different idea of implementation... I'll look and give input about that later

**Comment by pvajko** [comment]
You can't test it with the game as there's no way to switch that mode on from the game. It works only in the standalone course generator.

**Comment by pvajko** [comment]
@JDTiger pushed it on the headland branch. Hooked it up to the number of headlands, now you can decrease it from 0 when the new course gen is selected, it 'll show 'narrow fields'. You can still adjust headland turns, clockwise and order and also the direction if you wish.

Haven't tested yet but give it a try if you want.

**Comment by JDTiger** [comment]
1. It looks good
2. can't test this weekend, sadly
3. You implemented it in another way than what i thought, my idea was to end a row with a turn start point and the next waypoint would be the turn end point on the other side of the field... that way the Vehicle would drive down the Headland with its implement up... I don't know if its possible to program it this way, but it would lead to smoother turns, i think
4. it would be good to have more space in the Headland (have a couple of headland rows)

**Comment by pvajko** [comment]
3: it **does** lift the implement except on the first headland.
4: I was thinking about that and theoretically I could do any number of headlands on the short edge, I may change it later.

**Comment by JDTiger** [comment]
3: ok, looked like normal Headlands, sorry, couldn't really test
4: would be nice, but no immedeate concern

**Comment by Hairy-bob** [comment]
I'd like to have an option to skip rows to allow better turns with long equipment like trailed cultivators and seeders.
IRL you wouldn't leave a massive headland and do a tight turn to get back down the next row. If you have GPS (or "The Gift") then you miss a row or two to make an easy, sweeping turn, then when you reach the other side of the field you work back the way you came filling in the missed bits, repeat until finished.
Alternatively I know people who work rows 1, 3, 5, 2, 4 repeatedly across the field.
I don't know how hard this would be to code, but it would be great to see.

**Comment by pvajko** [comment]
It is actually implemented since ages (see https://github.com/pvajko/course-generator/releases/tag/v0.3) it is just not hooked up to the HUD yet.

I'll put this on my list.

My biggest problem is the lack of space on HUD and I think I won't be able to add any new functions until I come up with something for that.

**Comment by Hairy-bob** [comment]
Could you create an extra tab for advanced course generator settings?
I can certainly see where you're coming from, you've managed to cram so much into such a small window it's becoming a barrier to adding new features!
Thanks for all the hard work you guys put into courseplay. I don't think FS would have kept my interest for so long without a way to have machinery work for me. It really brings a map to life when I can drive around passing all my workers busying away!

**Comment by pvajko** [comment]
> Could you create an extra tab for advanced course generator settings?

That's one way to do it but it is a lot of work. I'd like to create a new screen, something like the settings screen, it is a lot easier to maintain.

**Comment by sootysax** [comment]
island avoidance doesnt seem to work on user recorded field edges, such as grass fields

**Comment by pvajko** [comment]
The question is what makes that island an island? The generator uses the built-in game function to figure out if a given coordinate is on a field or not, which in turn I think is using the cultivator_density map.

If we know how to figure out on that specific map if a point is on the island or not then this is easy to implement.

**Comment by pvajko** [comment]
@Hairy-bob just pushed the skip row feature.

**Comment by Hairy-bob** [comment]
Loving the new features, just had an hour playing with them so far but I like what I see!
I like the way you've implemented the advanced settings, I find it much more user friendly to tweak a course, to get the first and last points where I want them.
Thanks again, keep up the good work!

**Comment by pops64** [comment]
When we pick the starting direction could we have a third option of using the shortest edge? Instead of just longest and auto. Has this is the last remain feature that the old one still lets you do. Thanks a bunch

**Comment by pvajko** [comment]
Right angle to longest edge is easy to implement. I can do that.

(Once I finished the 'two side headlands' recommended by @zed636 .)

**Comment by pops64** [comment]
Alright delete my old suggestion new and improved idea, could we have scroll wheel included in the new GUI with scroll being 5 degrees, ctrl+scroll being 25 and alt+scroll being 1. Not sure where you could stick 0.5 degree maybe alt+left click the arrow is 0.5 and crtl+left click is 1. Also since I haven't really messed around with the new gui(square fields don't need fancy course gen :() is there a print out of what angle of auto/longest edge is chosen? which leads to my second question could we get this or maybe a button to use the last used angle so forage wagons can follow wind-rowers in grass mowing thanks :D

**Comment by pvajko** [comment]
Just pushed 6adc53aecf352267153d7e8c25ff44c4375df1c2 which implements the headland only on the short edges of the field feature requested by @zed636. 
![shortedge](https://user-images.githubusercontent.com/2379521/42117336-91631d44-7bc1-11e8-9484-2f6a58f9e631.jpg)

This issue is now closed, if you have any problems or suggestions regarding these new features please open a new issue.
