### ISSUE TITLE
Suggestion for field work mode.

### ISSUE THREAD

**Issue by Raints** [Courseplay/courseplay#2579]
Is it possible to add convoy option for field work mode? What I mean is for cultivator, just not only for combine.

**Comment by TheAdventist** [comment]
Might DeckerMMIV's (also on Github!) FollowMe an option? Set distance to follow, set offset if needed and farm away. Or is this not wat you mean?

**Comment by Raints** [comment]
@TheAdventist  If I use 10+ helper's in one field, then setting up FollowMe not an option.

**Comment by pops64** [comment]
We will look into this further but I doubt it has our current system relies on the course between the two vehicles being the same. Added to the list
