### ISSUE TITLE
Coursegenerator headland arrow wrong way

### ISSUE THREAD

**Issue by TinyCrocodile** [Courseplay/courseplay#2580]
A verry small thing concerning the Coursegenerator 

The arrow of Headland direction is pointing the wrong way arround.  When the arrow points clockwise then the headland is generated counterclockwise and vice versa.

![20180212210735_1](https://user-images.githubusercontent.com/34377785/36117150-e8224c80-1038-11e8-9eb3-c0d51f8803fc.jpg)

Not a big issue but i do it allways wrong the first time ;-)

**Comment by Steaktered** [comment]
this is not the error that comes up with me the stored courses disappear after rebooting the server


Von meinem Samsung Galaxy Smartphone gesendet.

-------- Ursprüngliche Nachricht --------
Von: TinyCrocodile <notifications@github.com>
Datum: 12.02.18 21:30 (GMT+01:00)
An: Courseplay/courseplay <courseplay@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [Courseplay/courseplay] Coursegenerator headland arrow wrong way (#2580)


A verry small thing concerning the Coursegenerator

The arrow of Headland direction is pointing the wrong way arround. When the arrow points clockwise then the headland is generated counterclockwise and vice versa.

[20180212210735_1]<https://user-images.githubusercontent.com/34377785/36117150-e8224c80-1038-11e8-9eb3-c0d51f8803fc.jpg>

Not a big issue but i do it allways wrong the first time ;-)
