### ISSUE TITLE
suggestion for tractor/trailer headland edge with forage harvester

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#2581]
Hello Guys,
Great work with your courseplay
but one thing, i hat some problems,
since @pvajko had createt the new turn manoevers with sharp edges - super - i had problems with the traktor/trailer to follow the forage harvester in this edges
the tractor needs a lot of space between the field for turning:
so it is:
![soitis](https://user-images.githubusercontent.com/24860501/36129095-c1dd0cf4-1065-11e8-89c2-f795fa6da444.jpg)

now my issues:
the forage harvester must drive backwards at the end of the field
is it possible to let the tractor/trailer do the same?
![newstep1](https://user-images.githubusercontent.com/24860501/36129120-e3ed28e2-1065-11e8-93e1-e93438c25b92.jpg)

and then next, when the forage harvester beginn to drive forward and beginn to turn the 90degree,
the tractor trailer does also the same?
![newstep2](https://user-images.githubusercontent.com/24860501/36129151-0a680820-1066-11e8-8027-37b5ad4d30d9.jpg)

lg
andreas

**Comment by andreasthu** [comment]
sorry, a secound issue, for the turn on up/down rows:
so it is, the trailer beginns tu turn outside, the he came back, turn in line with the harvester and drive long away (in short fields maybe to the other end)
then he push backward to the forage harvester
![turnsoitis](https://user-images.githubusercontent.com/24860501/36129587-3e5a9cfe-1068-11e8-827a-93626d90ed6a.jpg)

my idea, the tractor push back a little bit,
maybe calculated for the turn radius from him and the numbers from the frontlanes,
then drive forward, a little away from the fruit, and then turn in the line to the harvester
![turnmaybe](https://user-images.githubusercontent.com/24860501/36129688-b671fbf6-1068-11e8-9605-9c540ce7e82b.jpg)

only my ideas
lg
andreas

**Comment by frm274** [comment]
And, if the chopper could mirror his pipe to the other side while turning would be nice. So the tractor doesnt need to stop and wait for the pipe

**Comment by pops64** [comment]
@frm274 if your talking about waiting for the pipe on the harvester to swivel over to the other side. This won't be possible we don't control that. It is a internal Giants function we have no input to. Just output of when it is in range of tipper
