### ISSUE TITLE
island bypass feature:  avoidance area not wide enough.

### ISSUE THREAD

**Issue by shadow250** [Courseplay/courseplay#2582]
i tried using this on the estancia lapazza (sp)  south american map.  there is a little pavillion on the edge of the woods which i cut down and made it a field.  courseplay sees the pavillion and makes a circle around it but tools still hit it.  seems like its needs to be wider. i cant seem to find any info for this feature. advice would be appreciated.

**Comment by pvajko** [comment]
Follow the steps in https://github.com/Courseplay/courseplay/wiki#how-to-post-your-field-definitions to post your field definitions here and I'll take a look.

**Comment by shadow250** [comment]
here is the file you requested
[cpFields.zip](https://github.com/Courseplay/courseplay/files/1724396/cpFields.zip)
the working width is 13.7m
i also included the save game file in case you want to see the modified field. its about 47 hectares/116 acres
[savegame6.zip](https://github.com/Courseplay/courseplay/files/1724402/savegame6.zip)

i am currently trying to use a lexion 780 which probably wont be in the save with the stock case 45ft draper. i also tried the nh 11.90 with the same. and the horch pronto 9 dc 9m work width  and a modded version of the 9dc which is 15m work width. the modded 9dc will work but the modded segments do not clip and pass through the pavillion. i also used that roller mod to put a concrete circle around the pavillion  
and had courseplay recalc the field. the circle remained the same size after redoing the course.

the settings i used were field 1 (user)
width  15.3 modded dc9 or 13.7 for the combine
starting  current vehicle position
ive tried a combination of all the settings but the circle size remains the same.

thanks for taking a look.  :D

**Comment by pops64** [comment]
If use the field delete tool around that shack to make the avodince area bigger may work

**Comment by shadow250** [comment]
thank you for your suggestion pop64 but it did not work. it seems like it treats the shack like a telephone pole. i wish i could just remove (burn) it. if it comes to it ill make it 2 fields omitting the shack completely.

**Comment by pvajko** [comment]
Your first screenshot shows a course generated with the circle island setting but your second one is with the simple bypass. 
Do you have a screenshot of the collision when driving the circle bypass mode?

**Comment by pvajko** [comment]
So, looking at your cpFields.xml (great bug report by the way, has all the information) all the concrete area is a field for CP (has fruit density), only the shack is non-field, about a 5x7 meters area. The circle bypass mode should be able to steer around it unless the shack is on the very edge of the island which may well be the case here. The island detection works with a 1m resolution and that works fine as usually the obstacles are not right on the edge of the island.

In your case this may be a problem, the easiest would have been to leave a bit more (at least a meter) buffer around the shack.

I could also change the generator to stay further away from the island but then others will complain about missing fruit around the islands :)

**Comment by shadow250** [comment]
here is a screenshot of the collision in circle mode. there is slightly less collision on the sides of the building than the pictured end. also in this pic i did pops64's suggestion to delete the field but the thing courseplay looks for seems unmodified. i wondered if there is a way to make the island bigger somehow or maybe add a variable radius around islands?
![circle collision](https://user-images.githubusercontent.com/17964517/36238795-e6ddde20-11d2-11e8-8c4d-509af0da58bf.jpg)

**Comment by pvajko** [comment]
I gave you 50 centimeters as that make sense because of the 1m precision of the island detection. Won't do more for now unless others complain.
