### ISSUE TITLE
Courseplay and Premos 5000 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#2583]
Hello is the Premos 5000 supported by courseplay If so I’ve setup my course and let the courseplay do the work if I leave the machine it comes up with machine slipping and when I press e and watch it it simply stops.

**Comment by MoslessNeo** [comment]
CoursePlay is compatible with the unofficial DLC.
However, it is not supported if you are using the MR (More Realistic) mod.

**Comment by matty2123** [comment]
Is it the MR engine or will it work if I use an non mr tractor

**Comment by MoslessNeo** [comment]
You need to remove the PREMOS 5000 from vehicle database of MR;

https://www.fs-uk.com/forum/index.php?topic=199879.2085
Dural:
"Quote from: Tiago Pilonetp on February 11, 2018, 04:42:08 pm
With the mod Krone Premos 5000 from the DLC StrawHarvest, when I use the CP it does not move if I'm not inside the vehicle.

Using in manual mode, the NH T8 435 and can not work, the tractor reaches 0 km / h in a few meters. Even using a more powerful tractor I can not use the Premos 5000 (the tractor reaches 0 km / h in a few meters).

Is there any adjustment I can make in MR to be able to use Premos?

Krone Premos = very "special" tool IRL and in the game with MR.
Max output IRL = about 5T per hour only.
=> about 1 hour to fully fill the tank with a 400Hp tractor
If the field straw yield = 5T per Hectare and the combine header/cutter width = 6m, that also means the working speed of the Premos is between 1 and 2kph !!!

solutions (IRL) : 
- small combines (4m cutting width)
- field with not so much straw (low yield or raise the cutter when harvesting to get less straw)

in the game with MR, the max output is not really limited.
The speed is limited to 6kph though
The working speed is limited by the tractor HorsePower and the "size" of the windrow (heavy windrow = less speed. Seems logical)

Worst idea both IRL and in the game = trying to use the premos after the New Holland CR10.90 and the 3162 header.
IRL = tractor can't handle even at crawling speed or the Premos is "stuck" (overfilled with straw = jammed)
In game = you need a really powerful tractor (600+ HP)

EDIT : MR premos is already set to be about twice easier than IRL to work with (with 400Hp, you can bet on 9-10T per hour)
If this is really a problem, this is of course possible to "tune" that by using the "databank" mod and overriding the xml of the MR premos."

**Comment by pvajko** [comment]
@MoslessNeo thanks for the information. This is mod issue we have no time to fix.
