### ISSUE TITLE
Using combine convoy on other machines

### ISSUE THREAD

**Issue by kobra60** [Courseplay/courseplay#2587]
I am wondering what CP looks for in a machine to assign the combine convoy mode to it.  I am running 5 Krone Big M's on a field and if they run too close together, they tend to tangle up in the corners.  This mode has been a godsend with the harvesters.  My thought for a work around would be to change something in the mod's xml file or i3d file so CP thinks it's a combine and allows the convoy function.  Then it would all run smooth until the end where the lanes end up close due to the size of field and machine width calculations.  That's unavoidable and not a big deal since they are almost done by then.

My compliments to the team for all your wonderful work on this!  I would've quit playing farm sim a long time ago without this addition.

Thank you!

**Comment by pops64** [comment]
I am pretty sure Thomas didn't set it up for chaff harvesters only combine harvesters so this wouldn't work in this case. Closing this out because there is a suggestion to add additional equipment to this feature
