### ISSUE TITLE
Turning and crashing into trees 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#2588]
Hello I need assistance when I’m poughing fields why is it the tractor takes massive turns or proceeds to drive into trees on the edge even with a headland of 5 I have turn as soon as possible on but it’s annoying

**Comment by pops64** [comment]
Add more headlands. Most of the bigger ploughs require a lot of turn space because they have a 20+ m turn radius. Or remove the trees that your running into. There is nothing we can do to fix because we are constrained by the physics of the game in this case
