### ISSUE TITLE
Oakfield map: Not detecting island in field 13

### ISSUE THREAD

**Issue by killakanz** [Courseplay/courseplay#2590]
As titled... Courseplay is not detecting the island of trees in field 13. The island patch is definitely not showing as part of the field, so rolling it isn't making a difference...

**Comment by killakanz** [comment]
![20180218170126_1](https://user-images.githubusercontent.com/36604065/36354505-798e90be-14cd-11e8-9731-2ea6fa155953.jpg)
Screenshot for clarification...

**Comment by Crytiv** [comment]
For me, the CP doesnt even scan this field. I had to manually do it.

**Comment by killakanz** [comment]
Yeah, my first game on Oakfield it didn't scan them and clicking the calculate edge path for current field didn't work. Then after a re-load today it is calculating the edge paths but, as you can see, isn't detecting the islands.

**Comment by pvajko** [comment]
That's a problem with the map, should be fixed in the next version, see here: https://www.fs-uk.com/forum/index.php?topic=197330.msg1308705#msg1308705

**Comment by pvajko** [comment]
And here https://www.fs-uk.com/forum/index.php?topic=197330.msg1308735#msg1308735

**Comment by pvajko** [comment]
The other problem is that based on the screenshot you are using the 5.2 release and not the development version.
Only the development version has the island bypass feature.

**Comment by killakanz** [comment]
Just want to update on this in case any google searches hit here. I've now installed the dev version. CP is only detecting Field 13 if there's a crop planted or growing in it (and even bypasses the island).
If field 13 is in a harvested, plowed or cultivated state with nothing planted, CP is not detecting the field at all.

**Comment by pops64** [comment]
That sounds like a map creator bug. Has CP relies on a Giants function to tell it if there is field or not. You could try plough the field with the field create option enabled. The manually scan the field and save that field definitions has field 13 or anon used number. Has I am not sure if pvajkao island bypass feature works with user created definitions

**Comment by pvajko** [comment]
The exact problem with the maps is described on the above links. Executive summary: CP starts the field detection on the island and that fails.

**Comment by pops64** [comment]
Sorry couldn't remember which issue that there was a known map bug :P
