### ISSUE TITLE
Addition of some mods

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/courseplay#2593]
Hello,

Above all, I want to tell you that your work is remarkable.
I would like to know if it is possible to add some very useful mods.

As for example, the lely storm 300. For my part, when I use it, tractors with trailers do not detect it
![lely-p300-silage-harvester-fs17](https://user-images.githubusercontent.com/36656729/36412540-027e670c-161b-11e8-911b-28a808dacc8b.jpg)
Similarly, for the TST Quadro Pac V. this one does not work with the courseplay.
![tst-quadro-pac-v-fs17](https://user-images.githubusercontent.com/36656729/36412554-102ad6ec-161b-11e8-8327-5e6fa32cc414.jpg)
And if it is possible to add the joskin autoload, it would be perfect!
![pack-joskin-wago-baletrailer-autoload](https://user-images.githubusercontent.com/36656729/36412567-19b40512-161b-11e8-8be0-6bb892a21f49.jpg)

Thank you in advance and sorry for my very bad english

**Comment by Crinouche** [comment]
Hello,

Is it possible to add this mod:
http://www.modhub.us/farming-simulator-2017-mods/mchale-998-squarebalewrapper-v1-0/

Similarly, I suppose it is not possible to add the mods I had to notify in my first message?
Here is the link for the lely storm:
https://www.farming-simulator.com/mod.php?lang=fr&country=fr&mod_id=93504&title=fs2017

thank you in advance

**Comment by pops64** [comment]
#2462 for the first one The 2nd one was added to the list I doubt the autoloader will be included to work with CP
