### ISSUE TITLE
Harvesting Sugar Cane

### ISSUE THREAD

**Issue by erksartori** [Courseplay/courseplay#2599]
Hello everyone, I'm bringing a problem or even a suggestion.

As shown in the attached video, when the sugar cane is harvested, the tractor that comes with the bucket does not reach the discharge arm of the cane. They would know if I have a correction for this, because I do not know how to solve this problem, and if it does not, I can give a suggestion.

https://youtu.be/0E5i7rpSAGQ

In the configurations, it could have a field for you to define how much, in meters, it should go beyond the standard, so we can have how to configure for several types of carts.

Appreciate!!!

**Comment by TinyCrocodile** [comment]
I once had the same issue but with the forage harvester i coud then solve is by changing the vertical offset of the loader wagon.  But i guess this will not work for the suger cane wagon because the pipe is at the very back. Its really a pity i can not support you better.  Btw thx for your work for the Coursedrawer.
I appreciate it very much

**Comment by erksartori** [comment]
Thanks. I have already done this test changing the vertical distance, and it did not work, because in order to change the vertical, I also have to change the horizontal, where I have to get closer to the cogwheel, and then the traffic in the reverse gear. I am not a programmer, and I do not understand much of this process. But for those who will develop and those who can assist in development, please take a look at this process, please.

**Comment by pops64** [comment]
The problem with haversting sugar cane is the pipe on the havester is dynamically positioned depending in fill lvls in the receiving tipper. The problem CP is that our position is static when compared to the havester. So has the havester trys to fill the back or front of a receiving tipper the horizontal offset needs to decrease or the vertical offset needs to change to keep the pipe at 90 relative to the harvester. This is something that has been on our to do list long before sugar cane came out. The problem with sugar cane it doesn't have the reach of chaff havester. So this is were our system is failing. When have the time we implement a dynamic vertical offset system but for I'll close this out

**Comment by erksartori** [comment]
OK, TKS
