### ISSUE TITLE
sugestion: COURSEPLAY_TURN_ON_FIELD

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#2601]
Hello guys
let me give you a suggestion about COURSEPLAY_TURN_ON_FIELD activate/deactivate
with deactivate, it looks so:
![fsscreen_2018_02_24_09_45_45](https://user-images.githubusercontent.com/24860501/36627770-fc85010a-1947-11e8-9912-b65ac499e88e.png)
is this option activate, it looks so:
![fsscreen_2018_02_24_09_46_13](https://user-images.githubusercontent.com/24860501/36627776-18587aa6-1948-11e8-80c7-d4265fdbfba7.png)

my suggestion:
![fsscreen_2018_02_24_09_46_13 - kopie](https://user-images.githubusercontent.com/24860501/36627880-ca8e9678-1949-11e8-9679-aabac30f2fb5.png)

i find inthe turn.lua in line 285

`turnInfo.reverseOffset = max((turnInfo.turnRadius + turnInfo.halfVehicleWidth - turnInfo.headlandHeight), offset);`

this is the option for 1. push the long way back

but, 2. drive the long way forward i am not sure maybe line 326

` if (-turnInfo.zOffset + centerHeight + turnInfo.turnRadius + turnInfo.halfVehicleWidth) < turnInfo.headlandHeight then
`

the variable
 `+ turnInfo.halfVehicleWidth`
is it possible th change this?

lg
andreas

**Comment by pvajko** [comment]
Andreas, a few comments:

- When you look at the first screenshot you see a red and a yellow line, that is the front and the end of the work area of the tool (frontMarker and backMarker). The turn is generated to make sure that the tool covers the field, meaning the back marker must reach the edge of the field. That is why pulling forward in case of the deactivated on field turn is necessary.

- I think you are right with turn on field activated: I also noticed that those turns could be pushed forward, closer to the the field edge.

Don't you want to give it a try? We could really use someone who has the skills, time and motivation to fix/improve turn maneuvers :)

**Comment by TinyCrocodile** [comment]
Very interesting sugestion. The inner circle of last image looks great on a tool like this manure spayer but if you use a veenhuis premium integral II for example then more distance to the fieldedge is needed. Please be aware of this.

**Comment by andreasthu** [comment]
oh yes, jou are right.
there are two types of machines.
one type hast the same machine width as the workwidth
as example there are combines or sprayers
the other type has a wider workwidth as the machine or tool itself
here are the fetilizerspreaders, the loadingwagons or manurespreader.
from the liquidmanure tools are some first, someone second types.

i mean, maybe it was possible to set an self adjust option to set the distance from fieldborder automatik to the half workwide - so is it now - or maybe we can adjust the distance manually from half workwide to the fieldborder in settings 1m steps, or maybe beyound the border a few meters above.

@pvajko 
sorry, i am not your man for this job
i guess and trie, sometimes it is ok, sometimes it is a horrible error
i dont really understand scripts an lua

lg
andreas

**Comment by pvajko** [comment]
Closing to keep the issue area clean.

**Comment by andreasthu** [comment]
ok, guys.
i have e solution, works for me, but i am only use fieldwork with machines or tools they are smaler then the workwide. loaderwagon and fertilizersprayer.
here my settings:
in the turn.lua i changed the line 285 in:
`				turnInfo.reverseOffset = max((turnInfo.turnRadius - ( turnInfo.halfVehicleWidth * 6 )- turnInfo.headlandHeight), offset);	-- geändert anthu`
changed + turnInfo.halfVehicleWidth  in - ( turnInfo.halfVehicleWidth * 6 )
and line 326/327 in
```
			        if (-turnInfo.zOffset + centerHeight + turnInfo.turnRadius - ( turnInfo.halfVehicleWidth * 3 ) ) < turnInfo.headlandHeight then
				        useOhmTurn = true;													-- geändert anthu
```

looks now so:
the cp driver drives to the end of the field:
![fsscreen_2018_02_26_08_21_49](https://user-images.githubusercontent.com/24860501/36658081-4e8ccc02-1acf-11e8-9025-0a650310b545.png)

then he push a litte way back:
![fsscreen_2018_02_26_08_21_52](https://user-images.githubusercontent.com/24860501/36658099-5f11f138-1acf-11e8-9a7a-4fd885058b9d.png)

turn to the next line, a littel bit outside the field:
![fsscreen_2018_02_26_08_21_56](https://user-images.githubusercontent.com/24860501/36658107-68501aae-1acf-11e8-8129-52b6402c5593.png)

drive in the field:
![fsscreen_2018_02_26_08_22_01](https://user-images.githubusercontent.com/24860501/36658122-793bcc32-1acf-11e8-9996-bc50cf7627a4.png)

and then push back to beginn at the fieldborder:
![fsscreen_2018_02_26_08_22_06](https://user-images.githubusercontent.com/24860501/36658136-888288c0-1acf-11e8-8ded-85a457c99e45.png)


for me is this solution ok,
warning, not testet maybe can be errors with other machines.
i am testing this later with other multiplikators, the second must be half of the first, other it will not be work

lg
andreas

**Comment by pops64** [comment]
Yea Claus spent a lot of time getting the turn maneuvers to work with 99% of all machines. so tinkering with the turn maneuvers with out is input will be a challenge. (He fixed one thing which broke another)
