### ISSUE TITLE
Suggestion: Add Turn modes for pulled immplements

### ISSUE THREAD

**Issue by dicktimmerman** [Courseplay/courseplay#2603]
Hi, 
I've noticed that turning with in 3-point hich attached implements like Lemken Azurit etc, the turning is Ok, however If I turn with a "semi-mounted" plough as the Lemken Diamant 12 the turning isn't working the way it should. I real life the driver would steer away from the ploughed portion of his land, start rotating the plough, turn 180°, drive back to the last pass and turn 90° back onto the land and lower the plough. If you see for instance in the AI Vehicle extention, it has several "Turn Modes". For Semi mounted ploughs, this is the solution.

**Comment by pvajko** [comment]
AIVE is very good a turns and CP does not currently have the resources to implement new turn maneuvers.

This is why I tried to reuse AIVE for turns in CP , see my attempt from last year to interface CP with AIVE: https://github.com/Mogli12/AIVehicleExtension/issues/102
The AIVE developers don't seem to be supporting this idea however.
