### ISSUE TITLE
Mode 1 endless loop without loading

### ISSUE THREAD

**Issue by ceemosp** [Courseplay/courseplay#2606]
**Scenario:**

- Tractor 1 as overloader for combine on field (mode 3)

- Tractor 2 to be filled by overloader with route to farmsilo when full (mode 1 / load at starting point)

**Expected behavior:**
Tractor 2 waits at starting point (waypoint 1) until filled by tractor 1 and defined fill-level is reached and then starts its course to farmsilo, unloads and returns to starting point.

**Actual behavior**
Tractor 2 starts its run empty and goes onto an endless loop at a maximum speed of 10 km/h. (Why on earth 10 km/h??)

**CP settings**
Fill-level for tractor 1 is set to start at 70% and go to overloading point at 90%.
Fill-level for tractor 2 has the same settings.
Waypoint setting did not affect the result (start at first/nearest/most suitable wp)
Speeds were set to "as during recording of course" 
_Pls note: Translations may be slightly inaccurate since my game language is German - but you get the idea_
**Game info**

- CP version: 5.02.00060dev

- Map: FS17_The_Valley_The_Old_Farm_BsM **AND** Goldcrest -no change in behavor

- Vehicles: Various - vanilla and/or mods - no change in behavior (on Goldcrest only mods were Kuhn DLC and Strawharvest - together with CP)

**Additional observations**

- Sometimes the first run does work when "forcing" tractor 2 onto point 1 using "start at first waypoint"
- Overloader (tractor 1) "anticipates" the set fill-level (in my case 70%) and starts its run towards the combine at around 60% - not nice as I dislike programs trying to do MY thinking but I can work around it by "anticipating the anticipation" xD

I did not have this issue in previous versions of CP AT ALL - no clue what goes wrong here at this moment -^o^-
The same applies to other issue of today's date with two tractors in mode 2

**Comment by ceemosp** [comment]
I "think" I found the reason for this behavior ;)
If the course to the unloading station runs through a silo_trigger, CP seems to get entirely confused and ignores the loading at start-point (expected behavior) and instead picks up the silo_trigger as its loading point (hence the maneuvering speed of 10 km/h). The map's setup is exatly such (see picture).
On Goldcrest one of my course also passed too closely to the silo_trigger, hence the same issue there.
The question is **IF**  anything can be done about it or whether it is an unsolvable situation.
I can change the map to avoid this issue but assume many user won't be able to do this. 
![2606_mode1 issue_silotrigger](https://user-images.githubusercontent.com/5932768/36651191-cd52869e-1aa7-11e8-844e-7440a11aa166.jpg)

**Comment by TinyCrocodile** [comment]
Is this the same problem wich was documented in #2051 ? 
There is a Silotriger over the Unloadtriger?
or did i understand wrong?

**Comment by pops64** [comment]
Yea. This is a duplicate
