### ISSUE TITLE
Mode 2 with two tractors / ignoring settings of combine (fill level)

### ISSUE THREAD

**Issue by ceemosp** [Courseplay/courseplay#2607]
**Scenario:**

- Tractor 1 to empty combine on field (mode 2)

- Tractor 1 to empty combine on field (mode 2)

- Trattor 2 is positioned behind trator 1 on the course in front of WP1

**Expected behavior:**
Tractor 2 waits at starting point (waypoint 1) until it is its turn - meaning combine sends signal that it "wants to be emptied" **AND** after tractor 1 was filled to its "departure fill-level".

**Actual behavior**

- Tractor 1 responds to the combine's call and gets loaded on field but has **NOT YET** reached its departure fill level - in this case 90%.
- Tractor 2 initially waits at WP1 but then starts to move to be filled by combine when the latter has harvested around 1600 ltrs - which is **WAY BELOW** (approx. 15%) the level the combine should call for a tractor (70%). 
- After that the sequence of which tractor gets loaded seems to be pretty random but "could" be based on the distance to the combine. 
- This behavior replicates itself after one (or both) tractors have been emptied at the silo.

The above creates pretty "interesting" traffic situations on the field since the chance of collision drastically increases 

**CP settings**
Fill-level for tractor 1 is set to start at 70% and go to overloading point at 90%.
Fill-level for tractor 2 has the same settings.
Priority of combine is set to "fill-level" - double- and triple checked that part.
Waypoint setting did not affect the result (start at first/nearest/most suitable wp)
Speeds were set to "as during recording of course" 
Pls note: Translations may be slightly inaccurate since my game language is German - but you get the idea_
**Game info**

- CP version: 5.02.00060dev

- Map: FS17_The_Valley_The_Old_Farm_BsM **AND** Goldcrest -no change in behavor

- Vehicles: Various - vanilla and/or mods - no change in behavior (on Goldcrest only mods were Kuhn DLC and Strawharvest - together with CP)

**Additional observations**

- Tractors "anticipate" the set fill-level (in my case 70%) and start their runs towards the combine at around 60% - not nice as I dislike programs trying to do MY thinking but I can work around it by "anticipating the anticipation" xD

I did not have this issue in previous versions of CP AT ALL - no clue what goes wrong here at this moment -^o^-

**Comment by pops64** [comment]
I would just set both tippers manually assigned to that combine. I would have to guess that the tipper is losing it's connection to tipper 1 at the moment it is calling for a tipper. Please post a log with debug channel 4 running

**Comment by ceemosp** [comment]
I forgot to mention that I did assign both tippers manually to the combine, my bad. Log will follow as soon as there is a field ready for harvest.

**Comment by ThomasGaertner** [comment]
i have created an calculation, that the tractor will be there on time when the fill level is reached.
means it starts earlier than the set fill level. maybe this is the case. I will check it by chance....

**Comment by pops64** [comment]
Didn't know you changed this

**Comment by ThomasGaertner** [comment]
#2523

**Comment by ThomasGaertner** [comment]
try v.067 and report....

**Comment by pops64** [comment]
Due to inactivity
