### ISSUE TITLE
Grain transport of Water

### ISSUE THREAD

**Issue by Corran1327** [Courseplay/courseplay#2610]
I'm using CP on all my maps.... have not done any testing but want to know if this is
1. not yet a feature
2. a trigger issue in the map.
3. an actual bug

so I'm on the map Mavericks Multifruit v2< i think for all these I thinks  I'm willing to figure it out and nail it down I just need to get the info out and see what happens> loading a Joskins water trailer in a pond and attempting to off load it to the orchards down the street using the Grain transport mode<also tried other modes> setup the course and the trailer fills at start sometimes<got it to finish filling a trailer once> then drives to the first orchard thats full and keeps driving but then just keeps going does not stop at the second orchard....

helppppp

**Comment by pops64** [comment]
Never use Grain Transport(mode 1) for liquids. Always use Mode 8(Manuare Transport I think). Also pond filling atm is not supported with mode 8. You can try it and see if it works but on standard giants map I have no clue how to register the trigger associated with rivers and it is not of the standard type.

**Comment by Corran1327** [comment]
thanks
