### ISSUE TITLE
Drivers failing

### ISSUE THREAD

**Issue by Doxster** [Courseplay/courseplay#2614]
Hi,

I'm at a loss here. I redid my BGA route for the drivers since the route didn't work properly. After every "dump" they got thrown off track so I had to reset them. Now I can't get it to work any more and I can't find the problem. Two tractors run the course perfectly, but the Fendt 1050 did not. So I sold that one and got another Fendt 939, wich I had one running perfect. As soon as I added the new 939 (the third one on the same course) it won't work.

It drives on the roads as it should, but when it gets to the BGA's it recognizes the tip trigger and then just floors it full speed, missing the turn and sometimes tries to back up sometimes not.

I've redone the course many times but no success. Any help please?

**Comment by pops64** [comment]
I need a picture of the course is done with all waypoints on

**Comment by Doxster** [comment]
Hmm, how do I zoom out enough for it to show all of the waypoints? It's a big map.

It worked for a few runs yesterday, I thought it had self fixed it. But after a few runs one of the tractors just floored it after unloading in to a fence. The good part is that they are all unloading now though.

**Comment by pops64** [comment]
I just need the part that is failing

**Comment by pops64** [comment]
Due to inactivity
