### ISSUE TITLE
Some problems still in the sugar cane

### ISSUE THREAD

**Issue by erksartori** [Courseplay/courseplay#2615]
Hi, I'm here again, but this time with several problems in this video.

https://youtu.be/sIXLIpgLJ_0

First, notice at the beginning, that the tractor that is accompanying the harvester, is on the left side until it is right there. but on the way back it continues on the left side, passing over the plantation. and there is an option that is activated, to avoid planting, and as I show in the course of the video, there is no way to define the side that the tractor gets from the cogwheel.
Second, the first problem, when it arrives at the end of the plantation, its curve is opposite to the one of the harvester, occurring there, a traffic.
Third, a second course, because it makes the curve different as it approaches the hopper, it opens beyond what has been set for it to continue causing the cart to stay a greater distance from the discharge pipe.
Fourth, in this case, you can not show in this video, but only to be registered, at the beginning of the video, when the cart is full, it goes to the second point at the beginning of the route to unload. Even the beauty, but the initial points, are very close, causing the tractor to turn around until getting an angle to go to the third point and continue its journey, this occurs in different carts, especially the longer ones, where the tractor also has no way to make a more closed curve due to the angle between the tractor and the exo of the cart. In this case you could increase the distance from points 1, 2 and 3.

Thank you for your attention, and thank you for creating a very, very cool, and good system.

**Comment by pops64** [comment]
So CP  by default always goes to the 2nd waypiont. 2nd which sloves all your problems if you go to the sugar cane havester under the first page of settings there is a side seltect change it back to auto and most of the time it will stay out of the fruit. Also the pathfinding option is only for approaching and leaveing the combine. It doest do anything when already at the combine

**Comment by erksartori** [comment]
Hi, I found the automatic right and left, but I could not make the tractor work correctly on the right sides, see the video, I think it correctly shows what I'm trying to explain.

https://youtu.be/UF26wQHufY4

About the points. I'll explain in a better way. Example: start of route, point 1, to point 2 the distance is 10 meters, between point 2 and point 3 also the distance of 10 meters, but depending on the carriage the tractor is using the turning distance is 15 meter, so the tractor is turning until you find the point 3, I would like to know if you can leave a distance greater than points 2 and 3 in advance so that the curve can be correctly made.

Thank you

**Comment by pops64** [comment]
There should be an option to align to first waypoint. Somewhere. I don't remember where pvajkao put it. As for your video CP has always had issuse if change the side when it already been called. This is more of use it while the tractor is on the unloading course feature. Or drive the tipper far enough away it can do it's thing

**Comment by pvajko** [comment]
Here it is:

![capture](https://user-images.githubusercontent.com/2379521/36939651-1122bdde-1efa-11e8-9e9c-ca85fc05112f.PNG)

**Comment by erksartori** [comment]
I will try to explain it again, no matter what point it is going, if the distance between the points is less than the radius of rotation of the tractor with the cart, it will turn until the next point

On the sugar cane harvester, there is a bug, in the automatic he does not, well he does not, he goes to the opposite side of the plantation, it will be that I was clear. Is the video I posted not clear?

Excuse me ignorance, but for God's sake. if this is not clear.

**Comment by pops64** [comment]
Use the new experimental drive mode and should solve all your alignment issues. Has for your other issue post a log with channel 4 active

**Comment by pops64** [comment]
Closed #2909
