### ISSUE TITLE
need info for modding

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#2616]
Hello guys
i need infos about which attribute from the vehicle xml catch or search the teleloader or wheelloader to unload in a trailer?
ist his the
<fillRootNode 
<exactFillRootNode
<fillAutoAimTargetNode
<fillMassNod
<trailerTrigger
or a other?

background is, i have make a shovelcourse from the cow-silo shovel the silage out and load this on a truck, but i have two different trucks, a zil130 ans a mercedes actros
when the start point (from mode1) is right for the zil, the mercedes stands a little bit wrong (he can drive 1m or 0,5m forward to stand right)
when i set the start point forward 1m or 0,5m with the texteditor, the mercedes stands right,
and the zil also, but the teleloder unloads only in the mercedes
when i trie to unload in the zil, the teleloader stops before he unlaods.
so i want push back the tg in the zil i3d 1m or 0,5m back  so that the teleloader found also the right trigger in the zil

lg
andreas

**Comment by andreasthu** [comment]
i will introduce this with pics and the course.xml
[courseStorage0067.txt](https://github.com/Courseplay/courseplay/files/1776301/courseStorage0067.txt)

first, so it is now, i have the ZIL130 in mode1 drive, the teleoader unload in the ZIL130 normal:
![pic1](https://user-images.githubusercontent.com/24860501/36917199-7614a6b6-1e56-11e8-9a29-1424709b5137.png)

with the same course the teleloader unlaod in the MB Zetros:
![pic2](https://user-images.githubusercontent.com/24860501/36917237-993f073a-1e56-11e8-803d-c2824fa906a7.png)
BUT .... it looks very "ugly"

so i tried to let drive both truks an halb meter forwad before stop.
i changed the z-coordinates from the first waypoint from:
    <waypoint1 angle="30.09" speed="0" pos="-55.00 282.50" crossing="1"/>
    <waypoint2 angle="6.41" speed="22" pos="-51.90 288.12"/>
to
    <waypoint1 angle="30.09" speed="0" pos="-55.00 283.00" crossing="1"/>
    <waypoint2 angle="6.41" speed="22" pos="-51.90 288.12"/>
also
from 282,50 to 283,00 a half meter closer to WP2

now it looks good with the MB Zetros
![pic3](https://user-images.githubusercontent.com/24860501/36917399-ff3e113e-1e56-11e8-9dc5-e56192d36770.png)

but the teleloader stops before, when he tried to fill up the ZIL130
![pic4](https://user-images.githubusercontent.com/24860501/36917413-1159e230-1e57-11e8-8c11-5fd6cfbfc49e.png)

here is a pic from the teleloader with the shovel course:
![pic5](https://user-images.githubusercontent.com/24860501/36917450-262d8b12-1e57-11e8-8602-98a68cf41558.png)

so i thought i can move the fillpoint - that use cp to find the trigger - in the truck ( in the zil i3d) a half meter back, that the teleloader can find him and wont stop.
but i cant find him.
i tried now a long time and move many tg´s in the i3d 0.5 or 1.0 m back,,
but i have no sucess with it.
is there a point or tg which use the cp-shovel - i think there is one - but i cant find him.

have you the answer?

lg
andreas

**Comment by pops64** [comment]
This isn't the place to get help with mods. Unless you need help with making it compatible with CP once it is already stable in game with the standard Giants help(few expections to this). Try FS uk for modding support

**Comment by andreasthu** [comment]
read this before?
i dont need help with modding.
i need info, which point courseplay search in trailers for untipping.
when i know which point courseplay need or search, than can i move them self.

lg
andreas

**Comment by pvajko** [comment]
A quick search through the sources reveals that the exactFillRootNode seems to be used, however, the height may be adjusted to be on the same level as the real turning node. Not sure anyone here understands how the real turning node is calculated in CP, but for a truck is probably just the steering center node.

**Comment by pops64** [comment]
Looking at your issue. It is the way mode 9 is built. It has raycasting about 3 to 4 waypoints directly in front of the vehicle at all times. As soon as it detects a tipper or trigger to unload in. CP will no longer follow the course and just go straight until it is in range. So adjust your course to have at least 4 waypoints that are straight before the unloading action occurs. You can see this raycast with debug channel for mode 9 active while CP is running

**Comment by andreasthu** [comment]
thanks for your help
4 poins in row was the solution
i drived in an new shovelcourse straight ahead in line and now it works

![fsscreen_2018_03_05_10_51_28](https://user-images.githubusercontent.com/24860501/36968660-81884cdc-2063-11e8-8461-4b02c93bc511.png)
![fsscreen_2018_03_05_10_51_06](https://user-images.githubusercontent.com/24860501/36968664-85c13714-2063-11e8-8699-836595683462.png)
the teleloader loads out in both trucks, and the shovel dont collide with the boardwall

lg
andreas
