### ISSUE TITLE
Grain transport mode not stopping for loading

### ISSUE THREAD

**Issue by manchedepelle** [Courseplay/courseplay#2618]
I set up 2 overloaders to dump at a field side truck set on grain transport mode to the silo, everything worked fine until the next harvest where the truck did not wanted to stop at the begining of the course where ity should be loaded by the auger wagon. I tried setting new courses and loading when the overloader is there ready to unload but the truck always goes straight and very slowly continues the course to point 52 and then stops. 
Please help me guys i cant play my game and ive put a lot of time into it.
ty
map is cornbelt haha
courseplays is v5.02.00011
the tipper is the semi-tipper 70000/6 v1.0.0.3

**Comment by pops64** [comment]
#2051 long standing bug
