### ISSUE TITLE
Problem on a Dedicated Server ...

### ISSUE THREAD

**Issue by BauerDieterFischer** [Courseplay/courseplay#2620]
We have the problem we want to use courseplay on a Dedi server but have the problem even though we had switched off that he should always deduct cost from the account balance. Is that supposed to be so or is this a bug?

Thank you for a quick reply

(This text translated by Google I apologize for mistakes)

**Comment by ThomasGaertner** [comment]
Which costs do you mean , the loan for the CpHelper ? what do you mean with switch off ?? would you make it more clear , thanks 
Schreib in Deutsch und mach den Googletranslater - Text hinten dran

**Comment by pops64** [comment]
Closed #2909
