### ISSUE TITLE
Holmer Variant 595 Pack v1.0 traffic issue

### ISSUE THREAD

**Issue by cpoole2005** [Courseplay/courseplay#2621]
Links to mods: [http://www.modhub.us/farming-simulator-2017-mods/holmer-variant-595-pack/](url), [http://www.modhub.us/farming-simulator-2017-mods/holmer-pack-rm-modding/](url)
Mod author's Facebook [https://www.facebook.com/RM-Modding-471222612939582/](url) 

When approaching a harvester or a tipper for grain transfer it seams as if it is overly sensitive and gets stuck in traffic
![fsscreen_2018_03_06_10_09_00](https://user-images.githubusercontent.com/5596638/37040528-fbb8387a-2151-11e8-9965-f5af77071ccb.png)

**Comment by pops64** [comment]
It is a shared problem across most of CP when using mode3. Other than extending the pipe has far as it can go. And ensuring your course is parrel with the unload vehicle. Which by your picture it has a slight angle. There is nothing we can do until we improve the system in general
