### ISSUE TITLE
Fieldwork with Holmer Terra Dos T4-40

### ISSUE THREAD

**Issue by TheRealRolandDeschain** [Courseplay/courseplay#2623]
Hello, 

there seems a problem with the Holmer Terra Dos T4-40. After overloading the harvester is turned of but continue to drive its course. 
This seems to occur ONLY after the tipper is completely filled up. 
Here is a video showing the problem:
https://youtu.be/FTn5tFSiGpI?t=32s

**Comment by TheRealRolandDeschain** [comment]
Should I reproduce the problem with debug channels on (which ones?)?. Or is the standard log enough?

**Comment by pops64** [comment]
Just the standard. Can't remember if this action is covered by any debug channels any ways

**Comment by TheRealRolandDeschain** [comment]
Here is the log. 
https://gist.github.com/TheRealRolandDeschain/1cd3b935640270f8bf06685480e4849e.js

The weird thing I can't wrap my head around: 
I have made a new savegame with the same map and all mods loaded. I gave myself a huge amount of money and tried buy the holmer and all needed tools and reproduce the issue. Thing is, on the new savegame I can't reproduce it. On my regular savegame it happens all of the time. 

I'll continue testing...

**Comment by pops64** [comment]
It may be a setting you changed on CP that doesn't work correctly for the Holmer. Has these revert to default. See if your broken save the stop n go load option is enabled or disabled. Has this is the only time the tool should raise in the middle of a field

**Comment by TheRealRolandDeschain** [comment]
Damn it, I've made a mistake...
After I have made the new savegame for testing I kept on playing on my regular save and sold the Holmer. 
After your last post I bought it back and now I can't reproduce the problem on this save either. 

As you say clearly there was a setting that caused the issue. I will keep on testing...

BTW: What do you mean by stop n go load option? The option to wait during overload from the AI Vehicle Extension? Or some setting from CP?

**Comment by pops64** [comment]
![farming simulator 17 3_10_2018 07_30_21](https://user-images.githubusercontent.com/10678220/37242305-0f88b72c-2435-11e8-92d1-685a48859f31.png)

**Comment by TheRealRolandDeschain** [comment]
OK, tested that, definitely not the cause of the problem.

**Comment by pops64** [comment]
Problem still priesting?

**Comment by pops64** [comment]
Yea just post here if problem presents again with instructions on how
