### ISSUE TITLE
Mod question!

### ISSUE THREAD

**Issue by Blackmankot** [Courseplay/courseplay#2627]
Hello! With pleasure I use this mod - http://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=80039&title=fs2017
It is possible to fix two errors:
1. When the transport stops while waiting for the charging of consumable materials and turns off the engine. Krone Ultima CF 155 KSK continues to work.
Video - https://yadi.sk/i/6nJuYU4c3TCqy5

2. After the grid roll is loaded, the covers close very quickly. And the basket has not yet managed to get to the starting position. Is it possible to close the covers and start moving with a delay of a few seconds?
Video - https://yadi.sk/i/M0J1UMCE3TCrXW

**Comment by pops64** [comment]
Added to the list
