### ISSUE TITLE
LUA that freezes my game

### ISSUE THREAD

**Issue by Tradeaux** [Courseplay/courseplay#2628]
this line is what I get when I run empty combine then offload mode

D:/Farming/Solo/FS17_Courseplay/mode3.lua:10: attempt to perform arithmetic on a nil value
Error: Running LUA method 'update'.

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki we need full log

**Comment by Tradeaux** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/1799342/log.txt)

**Comment by pops64** [comment]
What exaclty are you trying to do. Mode 3(overloader mode) is only for augur wagons not combines. Mode 6 supports this action with combines and Mode 7 does has well using the standard helper to drive the field work

**Comment by Tradeaux** [comment]
I have a temp course where an auger is unloading the combine into another trailer

**Comment by pops64** [comment]
Are you using a mod. Please follow all steps in https://github.com/Courseplay/courseplay/wiki

**Comment by Tradeaux** [comment]
here is the list of mods i'm running on this save, but for the course i'm not running any modded vehicles och equipment, the save is on Green River map.
[mods.txt](https://github.com/Courseplay/courseplay/files/1799360/mods.txt)

**Comment by pops64** [comment]
Could you take a picture of your unloading course could also up date to the dev version.https://courseplay.github.io/courseplay/en/installation/index.html

**Comment by Tradeaux** [comment]
http://prntscr.com/ipa9p9 that's the course and running dev version now

**Comment by pops64** [comment]
I need to see where it is unloading. And looks like you are using a moded augur wagon. Could we get the name of it please and clean download location

**Comment by Tradeaux** [comment]
it's part of the plat DLC and this is the unloading point http://prntscr.com/ipabj1

**Comment by pops64** [comment]
I need it with all waypoints and it looks to be working in that picutre

**Comment by Tradeaux** [comment]
yes with a fresh load i can run the game for between 10sec and 5min before it freezes again, http://prntscr.com/ipafwy

**Comment by pops64** [comment]
https://courseplay.github.io/courseplay/en/manual/index.html#driveMode3 please setup your course correctly

**Comment by Tradeaux** [comment]
so not having a waiting point caused the problem? well, it's time for me to go over all the modes again then, thanks for the help

**Comment by pops64** [comment]
yea no problem. no it is only mode3 that has issues with out the waitpoint. The code is setup that you shouldn't have been able to run it with out one.
