### ISSUE TITLE
Shovel Mode does not tip in BGA tip trigger

### ISSUE THREAD

**Issue by Friendlyx** [Courseplay/courseplay#2630]
I can't get the shovel mode to unload in the tip trigger of the BGA feeder.
is it normal? in ls15 i used this and it worked. this is the first try in LS17. Its on Lossberg Map

**Comment by Friendlyx** [comment]
Ok I unloaded a Trailer near the BGA Feeder (thats where you put silage in and money). Then I made a course for shovel mode and the tractor starts and does all what it should but then waits in front of BGA feeder as if there is no unload trigger recocnized. This is all on the Lossberg map

**Comment by TinyCrocodile** [comment]
It is maybe the way you did setup the course. I learned from a recent issue that mode 9 works with raycasting to find a trigger and then drives straight from that point to unload but when it misses the feeder from this position it will not work.

@pops64  said:
> It is the way mode 9 is built. It has raycasting about 3 to 4 waypoints directly in front of the vehicle at all times. As soon as it detects a tipper or trigger to unload in. CP will no longer follow the course and just go straight until it is in range. So adjust your course to have at least 4 waypoints that are straight before the unloading action occurs. 

In this issue you can find the original information.  #2616

**Comment by pops64** [comment]
Yes please go ahead and setup your course as described in the manual. There needs to be more straight line into the trigger

**Comment by Friendlyx** [comment]
works now thx for the raycasting info
