### ISSUE TITLE
Mode 1 and mode 6

### ISSUE THREAD

**Issue by Tradeaux** [Courseplay/courseplay#2632]
ran into these bugs last night

1. Tractors don't wait at starting point when running mode 1 (Grain Transport), for me they just keep driving at low speed

2. Combines don't follow the "turn on field" rule when harvesting with mode 6 (Fieldwork)

[log.txt](https://github.com/Courseplay/courseplay/files/1800220/log.txt)

**Comment by ThomasGaertner** [comment]
could it be related to #2051  ?

**Comment by Tradeaux** [comment]
for the first on yes it could actually be that, I'll try and offload elsewhere, strange that the thread did not pop up when i searched for mode 1

**Comment by pops64** [comment]
Yea your running the release version please update to the dev version if you want to have this fixed. Point 2 combines can't turn on field with CP
