### ISSUE TITLE
Question to all : do traffic lights exist for FS17

### ISSUE THREAD

**Issue by ThomasGaertner** [Courseplay/courseplay#2633]
I am busy making some changes on the traffic recognition system and found parts of FS15 Traffic lights.
Do they exist for FS17 or can I delete it ?

**Comment by pops64** [comment]
Mabye for Rail Crossing but it might be a completely different set of variables

**Comment by TinyCrocodile** [comment]
I never used it so far. But i managed to find 3 mod maps using traffic lights. 

https://forbidden-mods.de/wcf/filebase/file/3051-mecklenburg-vorpommern/

https://www.farming-simulator.com/mod.php?lang=en&country=au&mod_id=99906

https://ls-portal.eu/de/sudhemmern/

This guy i found is using cp and traffic lights:
https://m.youtube.com/watch?v=xQDTQp9t8nk seems to work good.
Maybe not a lot of using but still if it is working i suggest to let it in.
