### ISSUE TITLE
Problems with Cursor

### ISSUE THREAD

**Issue by haldir21** [Courseplay/courseplay#2634]
Hello, 
first of  all Thank you for this mod. I like it very much.

Since 2 weeks i´ve had a problem with courseplay. 
After a while in the game (sometimes after minutes somtimes after an hour) when i open Courseplay, the Coursor starts to flicker and i have no control over the mouse. 
When i´m  trying to move the mouse, the cursor jumps into an another corner of the screen.
After restart the game i can play normal until this problem comes again.

I´ve tried different mouses and different USB Hubs, and its allwas the same.

It would be great if somone could help me.

Thanks for all

Salma

**Comment by JLConradie** [comment]
@haldir21 

Hi have the same Problem.. It could be a conflict with some other mods.
Mine does don't flicker but the cursor  jumps and never on the same place. So I have to search for the mouse.
I thought I'm just getting old.. and cant see the mouse clearly. Well over 50 you lose some functions of your body trust me..     But you have the same problem. Thank Goodness I'm not alone... My wife does not believe me.. Now I can show her.  
So it must be a courseplay issue then and not my EYES. LOL....

**Comment by haldir21** [comment]
@JLConradie 
=)
It denfently  a Courserplay Problem/ or conflict with a mod maybe.
So now i try to sort out some mods, that i dont need a t the Moment i hope it helps.

Have anybody else thes kind of Problem? 
Is there a Solution for it?

**Comment by Tensuko** [comment]
Got a Courserproblem too. After a while, the Courser moves (more jumps) and somehow make me tab out of the game.

**Comment by pops64** [comment]
Disable CP and see if it still is a problem. Or disable all mods but CP and see if the problem occurs. If not starting renabling them one by one till the problem returns

**Comment by JLConradie** [comment]
Suggestion ---  to Courseplay Coders

If you move around with the mouse the screen moves and so does the invisible cursor.
Now if you call up Courseplay HUD the invisible cursor become visible.. as we all know... 
BUT.. never on the same place.

Suggestion -- If Courseplay HUD has focus or if you call up the HUD let the mouse move to the middle
of the HUD from where ever it was. 

Conclusion : Just a nice future and you won't have to look or trying to locate the mouse.

Regards
Louis

**Comment by haldir21** [comment]
I think i have a Idea what Mod is making the Troubles with the coursor. 
I sorted out some Mods that i dont use.
But the mod i see relults is the Taurus 2803.
https://ls-portal.eu/de/kotte-garant-taurus-2803/
I take this Mod out, and since hours i don´t have this problems with the cursor jumping.

Maybe it helpd other with the same Problems.
Regards
Daniel

**Comment by pops64** [comment]
Mereged
