### ISSUE TITLE
ROPA DLC Support

### ISSUE THREAD

**Issue by ian898** [Courseplay/courseplay#2638]
I am sure this is already on the todo list but I thought I would add it just in case it wasn't basically just needs supporting in the special tools like the holmer was because at the minute its unusable. 👍

**Comment by ThomasGaertner** [comment]
yea I'm on it...

**Comment by ian898** [comment]
Its wasn't to bad I have already added myself earlier was surprised no one else mentioned it though.

**Comment by ThomasGaertner** [comment]
yea I know,when I see the script it is a miracle that it works at all :-)

**Comment by SuBerPL** [comment]
Is courseplay working with kind of machine like maus 5 or nawaro maus or holmer terra felis 2 eco? How to generate a course for this?

**Comment by ThomasGaertner** [comment]
@SuBerPL : youhave to Drive them Manuale but they will be considered as sugarbeet loaders that you loaders your Mode 2 driven   tractors on it

**Comment by ian898** [comment]
@ThomasGaertner Yes your right the script could use a little care here to add to what I originally said and after a little testing the main things I notice with Maus is the above the auto pipe position and also if Maus empties the trailer just goes straight away it never allows you chance to move forward back into your heap. 👍

**Comment by ThomasGaertner** [comment]
try v.066 or higher and report...

**Comment by Frosties82** [comment]
A question regarding ROPA DLC, it works fine with waypoint and all, but when its suppose to turn it just get stuck in a reverse turn and just go around and around and around...  
Is there a setting i need to configure to make it work or is this a bug?

**Comment by pops64** [comment]
Which tool where? Follow the wiki for proper bug report

**Comment by Frosties82** [comment]
sorry for the lack of information!

It was the ROPA Tiger 6 XL harvesting sugar beets on Oregon Springs. Wasnt sure it was a bug, or something i did wrong so i didnt put up a bug report.

**Comment by pops64** [comment]
Which waitpoint was it stuck on? There lots of things it could reverse on https://github.com/Courseplay/courseplay/wiki

**Comment by Frosties82** [comment]
it runs without any problems during the straight run on the field, and when reaching the end it starts to turn to start on the next straight run and its during that turn it get stuck.
Dont have a field i can reproduce on right now

EDIT:
Was able to reproduce.
After finish the straight, the vehicle turns left, then reverse right, and instead of driving straight into the field it just keeps reversing.
Can try and get a video of it to explain better

**Comment by pops64** [comment]
That would be best. With debug 12 n 14 active

**Comment by eddiem54** [comment]
Hi,
I'm getting an issue with Keiler 2 as shown in screenshot:
![fsscreen_2018_04_01_18_59_00](https://user-images.githubusercontent.com/2765885/38176172-062968de-35e2-11e8-9ecc-d02075307507.png)
 Trailer is in waiting position but is detected by harvester which then stops.
[Log.](https://gist.github.com/eddiem54/e0e3971030c4f6388c5cb40f26f0f15c)
Thanks for Courseplay.

**Comment by pops64** [comment]
Yea. I think it is a problem with all harvesters but with this one the harvester must stop to unload.

**Comment by pops64** [comment]
inactivity
