### ISSUE TITLE
Traffic : Ver 5.02.00064

### ISSUE THREAD

**Issue by JLConradie** [Courseplay/courseplay#2639]
Hello..

message : is in traffic

Message and vehicle remains stuck in traffic even if all traffic cleared.

Happens on field or on course.  Log clean. No errors

![traffic](https://user-images.githubusercontent.com/32715611/37393349-82b92d3e-2779-11e8-9146-1efb9e6c5e03.png)

Regards
Louis

**Comment by ThomasGaertner** [comment]
log with debug 3 please

**Comment by JLConradie** [comment]
Thanks for reply... Thomas
I'll do..

1)As soon as Combine reach fill level % the support tractor or tipper on field waiting for combine to reach fill level % gets this message and don't move without any traffic close-by . I have to disable the dump route and load it again but then obviously  he starts again at the closest point of route. 

2)The same apply for tractor/tipper that are waiting at the end of dump route waiting for combine to reach fill level %  

No.2 only happens at random.

I'll send you the log.

**Comment by JLConradie** [comment]
Log File : Hope you can Download it. I am Limited only to 512k on Pastbin and GIST
https://mega.nz/#!7Ho1xT6L!NafjRU-d-A1z3ZnbCP6lRvkOwGyRCjRN_Iq8RZqKUIU

**Comment by JLConradie** [comment]
Hello Thomas 
Sorry for late reply...

As you can see in the far distance the two Messy's the one to the right is in traffic Far distance from the other one. 

The Combine reached fill level and message appear  :  in traffic.

Hopefully you can make something out of the huge log file.

![beweeg](https://user-images.githubusercontent.com/32715611/37436319-0a41eeb4-27f0-11e8-9526-bb4b43bb90d0.png)

Thank  You
Louis

**Comment by lcc1211** [comment]
I've had this happen a time or two when a vehicle actually blocks for a few seconds, but the waiting vehicle won't start up again. Happens mostly when one vehicle is at a sell point and another comes up behind but also happens when a combine gets temporarily blocked by the tending tractor.  Happens so rarely I just never bothered to report it.

**Comment by JLConradie** [comment]
@lcc1211
True.. It happens.. but then after the traffic are cleared then the vehicle with message : in traffic 
should continue. 
In Ver 5.02.00064 the latest one, they don't. the tipper/Support tractor is not even neat any vehicle or object that could course "In traffic"

Last night I really tested it and harvested 200 hectares to get behind this.
Its something to do with the new traffic function.  I Think.

This morning I tested it again.. Could be a MAP conflict or a mod.

I harvested a 50 hectar field with Ver 64.  Within the first 10 Hectares  3 In Traffic messages. Vehicle stuck not even close to combine or any other tractor.

Then I loaded Ver 63.. Did a roll-back.  The remaining 40 Hectares got harvested without any incident.  
 
But, I believe and trust that Thomas would come up with an answer.

Thanks for replying..

**Comment by JLConradie** [comment]
hmm.. Thomas.. I'll do anything to help..
As long as I'm not the only one with this problem.
It works very well with ver 63.. It only happens with ver 64
The Trailer is one of mine... and its not a dolly. Its with me for a long time. Courseplay can even reverse with it.. BUT good Idea.. I'll do it with in game equipment and start the Mode 3 debug sooner.

Regards

**Comment by haldir21** [comment]
Hi Thomas

I have the same Problem.

But not with the harvesting ( at the Moment i have no Field that is ready fro harversting).
![grafik](https://user-images.githubusercontent.com/37243382/37474366-75b9e144-2870-11e8-9cdb-91fedad80472.png)
I have the Problem with windrow gras.

Maybe it helps you.
When you need any log from me Pelase contact me.

Regardas haldir

**Comment by ThomasGaertner** [comment]
I compare the found objects in the collision trigger with an ignore list. If its not on the ignore list its traffic.

This list will be created on every time you start cp. In this list are all parts of me and my trailers, tools and so on .

@JLConradie : in your case its definately part of the trailer which causes the traffic ( 207721 (Deichsel) )

@haldir21 : in your case I suppose its the front mower

I need to find out now whether these parts are not on the ignore list. therefore it would be great if you could give me the tools to test it. and activate  debug 3 before starting the tractor.

**Comment by JLConradie** [comment]
Hello @ThomasGaertner

I have attached  the complete log file as requested.
https://mega.nz/#!nTYDnApD!saFdSM_lBpDIoJh6EcuFrMCia5TuBGBwpz-wIsw-phg

**You are absolutely correct.** 
Its modded trailers. I have this 4 excel trailer now for a long time no problems up-to now. I used other mod trailers as well and some of them does not  stop at tip triggers as you know of some reported issues and some give this message

Error: Running LUA method 'update'.
C:/Users/Louis/Documents/My Games/FarmingSimulator2017/mods/courseplay/drive.lua:1250: attempt to index field 'fillTriggers' (a nil value).,
(Well I thing this one was fixed in Ver 63)

You can link the two issues. #2639 and #2636 

I have harvested a field with vanilla.. The headlands turns are correct does not course any collisions. Tip and  load correctly at silo's.

As soon as I use the mod trailer the tractor behave differently and move in front of combine into the crops. 
3/4 down harvesting the field, and around 3 or 4 " in traffic message" and stuck and does not move, does not tip at silo or give error loading at silo. Well in different modes..

What's the next step. Do we have to put something in the ModDesc File under typeDesc of vehicle or something. 

Regards Louis

**Comment by JLConradie** [comment]
@ThomasGaertner 

The link of the trailer. It is a fliegl 4 axis. It is a standard trailer setup without scripts.
https://mega.nz/#!6ThE0SxD!69tF-fmKdZI1KSWCGo8nmrjCAn2Hup3P4VteBSR51CY

**Comment by ThomasGaertner** [comment]
i got it, try with v.65 or higher and report. You can force it , if you locate the tractor so, that the target waypoint is behind your tractor ...

**Comment by haldir21** [comment]
@ThomasGaertner 
This the Log for Version 64.
[log.txt](https://github.com/Courseplay/courseplay/files/1817307/log.txt)
I have read it that there is a new Verion after i have try it.

So and in the  version 65 it works normal.
[log.txt](https://github.com/Courseplay/courseplay/files/1817309/log.txt)

I don´t now if this log is needed.

Thank you very much.
Regards
Daniel
