### ISSUE TITLE
Log errors after latest download  

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#2640]
ive downloaded the lastest version tonight and its throwing out lots of errors see log for more info.
[log.txt](https://github.com/Courseplay/courseplay/files/1820637/log.txt)

**Comment by SavageMkII** [comment]
I am also getting these errors with 2.00066. I was running various mods doing fieldwork(cutting, windrowing, and baling grass). Doesn't seem to effect operation of CP, but causes a bit of lag in the game.
[log.txt](https://github.com/Courseplay/courseplay/files/1821165/log.txt)

**Comment by matty2123** [comment]
Same mine causes lag issues

**Comment by ThomasGaertner** [comment]
test v.68 or higher and report....

**Comment by matty2123** [comment]
So far so good no errors
