### ISSUE TITLE
Fill and Empty Shovel

### ISSUE THREAD

**Issue by EQRuges** [Courseplay/courseplay#2641]
So I thought I would be clever and setup some greenhouses that courseplay would keep filled up:
https://steamuserimages-a.akamaihd.net/ugc/916919262112555230/5D24D7377F4BDA1766FD718A0101C1B33160AFA3/

I created a fill and empty shovel route for each greenhouse with the 3 waypoints for each one. Then I added the course for the next green house to the end of the course. Of course this meant courseplay was seeing more then 3 waypoints for the course which threw up the error only 3 waypoints allowed. even thow each individual course only had the 3 waypoints. Would be nice to see the ability to link course for fill and empty shovel. Thanks.

**Comment by pops64** [comment]
This won't ever happen. Linking fieldwork course would require major investment this is even more complicated than fieldwork courses. Thanks for the suggestion tho.
