### ISSUE TITLE
suggestion for new notification & headland turn issue

### ISSUE THREAD

**Issue by Tritura2** [Courseplay/courseplay#2645]
![screenshot](https://user-images.githubusercontent.com/37582657/37665663-0d68c618-2c5e-11e8-900d-c7dd719a37f1.jpg)

Hey guys,
sometimes it happens, that the driver can't reach the next waypoint for different reasons and start turning round and round.

Would it be possible to add a new notification when the driver could not get to the next waypoint within the last minute?

**Comment by Tritura2** [comment]
![screenshot 7](https://user-images.githubusercontent.com/37582657/37715064-520a9996-2d1b-11e8-9035-8dcc4656f256.png)
![screenshot 8](https://user-images.githubusercontent.com/37582657/37715065-523a6edc-2d1b-11e8-9c29-21c02c2b0326.png)
![screenshot 10](https://user-images.githubusercontent.com/37582657/37715066-525a64d0-2d1b-11e8-8e55-d5e24e0cc471.jpg)
![screenshot 11](https://user-images.githubusercontent.com/37582657/37715067-527fa22c-2d1b-11e8-865a-e9e063c996b2.png)
![screenshot 12](https://user-images.githubusercontent.com/37582657/37715069-5308130a-2d1b-11e8-9867-6ab89fb4dc78.png)
![screenshot 14](https://user-images.githubusercontent.com/37582657/37715171-a4c4d1c4-2d1b-11e8-8f93-ac5a90736e34.png)



He starts to drive laps to try to get to the next waypoint. First I thought he would not stop but this time I didn't stop him and after 5-7 minutes he hit the right position to continue.

Working Wide: 17.5m
offset: 5.1m left
pre-turn: 2 sharp
FreeFlow 25ft + MF Activa 7347 S
Map: Lösshügelland [https://www.modhoster.de/mods/losshugelland--3](url)
Field: 30
Version: 5.02.00069

**Comment by Tritura2** [comment]
at the second position I stoped him after 10min

**Comment by pvajko** [comment]
These actually aren't the headland turns I implemented, these are from the regular turn system which assumes that the turn start and turn end are always 180 degrees apart. 

I'll look into this, I think my headland turns are actually could handle these situations.

Also, we need to come up with a solution for these circling, I already have code that can tell if a vehicle can actually reach the next waypoint given the turning radius and the direction of the current waypoint. The easiest would be to check this before switching waypoints.

**Comment by pAnFarmer** [comment]
I wanted to psot an issue conerning tihs circle problems. They come irregularly on field work (ploughing/seed) and regularly on one  mode 2 course, where the overloader does not get the first waypoint of his overload course properly and turns round after round. 
![cp overlaoder f25 turns around 1](https://user-images.githubusercontent.com/35901206/37830279-36eb33a4-2ea2-11e8-9f02-e078c9a22e0e.jpg)
![cp overlaoder f25 turns around 2](https://user-images.githubusercontent.com/35901206/37830280-370ab5f8-2ea2-11e8-831b-bfb93c2627fd.jpg)
![cp overlaoder f25 turns around 3](https://user-images.githubusercontent.com/35901206/37830281-37260fe2-2ea2-11e8-8018-4fe6ba5f85eb.jpg)
![cp overlaoder f25 turns around 4](https://user-images.githubusercontent.com/35901206/37830282-373f6bd6-2ea2-11e8-9d5f-9f4f30972f50.jpg)
![cp overlaoder f25 turns around 5](https://user-images.githubusercontent.com/35901206/37830283-37596fd6-2ea2-11e8-844b-5904e5b3cccd.jpg)
![cp overlaoder f25 turns around 6](https://user-images.githubusercontent.com/35901206/37830285-3774768c-2ea2-11e8-985e-13b83a16ee09.jpg)

Indeed it would be a good idea to implement a notification.

**Comment by pops64** [comment]
@pAnFarmer Please post a new issue about that has that is separate issues from this

**Comment by pAnFarmer** [comment]
I tried the first point option as well, no better. I will see if I can open an new issue. thx

**Comment by pops64** [comment]
Closed #2909
