### ISSUE TITLE
Auger w/ Overload circling waypoint 3

### ISSUE THREAD

**Issue by Murbayn** [Courseplay/courseplay#2646]
Hey folks!

In the developer version when I set up an overload path the 2nd to 3rd waypoint are close together, forcing the tractor to circle around trying to find waypoint 3 (unless coming straight at it).

I tested with the released version and I noticed that in overload mode the 3rd waypoint is about twice as far from the 2nd, then waypoints after that go back to a "normal" separation.

Not sure if this is an overall issue or something I'm missing.

Included screen shot of the developer version waypoints.

![augeroverload](https://user-images.githubusercontent.com/37638208/37737870-7e70e3a4-2d2b-11e8-922c-f5a1b5c375aa.jpg)

**Comment by pvajko** [comment]
Did you try with the align with waypoint enabled?
![image](https://user-images.githubusercontent.com/2379521/37738777-1606d8d2-2d26-11e8-8203-ff012ec89c44.png)

**Comment by Murbayn** [comment]
Sorry for not getting back sooner. That did it!  Overlooked it so thank you very much.
