### ISSUE TITLE
Implement a free to define and then absolute speed limit

### ISSUE THREAD

**Issue by pAnFarmer** [Courseplay/courseplay#2648]
Hi all. Since I use the gearbox addon and read about the issues the addon and resulting breaking problems due to heavy trailers, I´d like to suggest: could you implement another speed definition in the speed tab. Now you can chosse some speeds on fields, but I think it was nice if we could also define a max speed for the road instead of just "like recorded" or  "full speed". I and certaily many others have recorded some 400 courses and it is very annoying to reset all the trucks and such if they come to difficult waypoints at a speed much too high. And considering the number of courses it is too much work to review an coursedraw them all.
Thx for your work
pan

**Comment by pops64** [comment]
Will look into this at a later date when we have more free time

**Comment by pops64** [comment]
If you switch to max speed then adjust the max speed and set it back to auto. This new max speed will be the highest speed it will go to. Not sure if this is a bug or was intentional
