### ISSUE TITLE
Courseplay doesn't detecte bunker trigger after certern amount

### ISSUE THREAD

**Issue by Big-Bambino** [Courseplay/courseplay#2650]
Hey Guys,

I've got a issue when i'm using CP in any tipper mode (combi or just tipping). My problem is that after around about 1/3 filling my silo with CP, the AI stops detecting the trigger of the silo that i was filling.
So i've tried finding the problem in many situations:
- Different tractor and trailer (Same problem)
- Taking out the amount of the last trailer from the bunker (CP empty's the next trailer like normal, then on the next trailer doesn't detect the trigger)
- Taking out all of my mods and trying in vanilla with just the map that i'm using (Same problem)
- Scale the trigger higher in GE, so that the trigger is half in the ground and at least 10 meters high out of the ground (Same problem)
- And so far tried in two different bunkers (Similar problem)

The only thing that i'm thinking of is that it's a map issue, but i can't find any solution in the i3d nor the xml
It's been a while that i've used CP (Since FS11), and never encountered a problem like this one.

MAP : Gemeinde Rade Reloaded (A really nice map)
SILO : The two in the middle of the main farm
CP : 5.02.00069

👍 Keep up with the nice work 👍

**Comment by evybart** [comment]
same problem like this #2529

**Comment by Big-Bambino** [comment]
Yes exactly, I see that the issue is still present. 
Do we know is there's any solution to this ?

**Comment by Big-Bambino** [comment]
More testing today, i deleted the colMap.grle from my map and setup a new savegame. Still the same.
Next thing I'll be trying is testing on a other map.

**Comment by evybart** [comment]
do the same with me in nf march map bud first he say the silo is full and then detect he the triggers not more one solution make the same route bud put a unloadingpoint to the course first he see the tiptrigger en when he say he is full the unloadingpoint take over works fine for me

**Comment by Big-Bambino** [comment]
Yeah i see, i came up with the same solution. But the feature what make the trailer go forwards when the trailer can't empty causes me a minor issue #2660

**Comment by pops64** [comment]
I am combineing all duplicate threads about tip triggers not working into this issue
