### ISSUE TITLE
kuhn sprayer metris 4102 wanting to refill

### ISSUE THREAD

**Issue by wackoamd1** [Courseplay/courseplay#2651]
courseplay keeps complaining that it needs to refill even though the sprayer is already full , it just does not want to spray the course.

**Comment by pops64** [comment]
Yea it is a weird bug iv seen once but couldn't reproduce. Just restart the game or attach a different tool. I'm going to close this out unless you have steps to reproduce

**Comment by pops64** [comment]
#2555
