### ISSUE TITLE
Unload speed

### ISSUE THREAD

**Issue by MrTobbsta** [Courseplay/courseplay#2652]
Hello!

Map: West Coast
Latest dev. version of CP is being used.

Can't for my life get the unloading to work (the picture is my latest test).  Have tried doing it without waitpoints as well, still same result.

Am I just being stupid and missing something or is this some kind of bug?
Mayby a way of chaning the unload speed is needed?

Thanks in advance and keep up the good work!

![20180324160127_1](https://user-images.githubusercontent.com/5129627/37865572-abdb192c-2f7e-11e8-931f-c7bb2b47842d.jpg)

**Comment by TinyCrocodile** [comment]
As you can see in the guide for mode 1 & 2 no waitpoints are needed for unloading into bunker silo. 
Some problems with unloading in the past came from having multiple triggers on the same route. Make shure you only use the bunkersilo trigger.
Try also to drive the other way around. If i remember correctly the direction of a mod map trigger was a issue one time.
Here you find the guide for mode 2:
http://courseplay.github.io/courseplay/en/manual/index.html#driveMode2

**Comment by MrTobbsta** [comment]
Tried the ohter way, no waitpoints and only one trigger in the course, still no luck. 
Reverse unlouding works fine tho, but it's a drive through bunker so it would be nice to get it working.

![20180326171516_1](https://user-images.githubusercontent.com/5129627/37915525-03e31808-311a-11e8-9ea4-3cba38d527fb.jpg)

**Comment by TinyCrocodile** [comment]
I did try to reproduce this yesterday on the same map and i had the same issue. It put exactly 50% of the trailer into the silo and 50% outside the silo. On default map it stops to unload at the end of the silo. I an not shure where the problem is. The map, cp or both.

**Comment by pops64** [comment]
I am combineing all duplicate threads about tip triggers not working into #2661
