### ISSUE TITLE
Course combination

### ISSUE THREAD

**Issue by Maogami** [Courseplay/courseplay#2653]
Hello community, I have a problem with merge/load after courses. I have generated three courses for grass mowing and then two transport courses from A to B to drive from f1 to f2 from f2 to f3. The problem is that the tractor stops at the last waypoint in the first field, when I click continue the tractor drives to the next field and then, without lowering mowers it starts to drive about 1kmph on the generated route. I tried both add after a course and merge courses.

So, how to get it to work? What can I do to get my CP to work? (Mow F1 drive to F2, mow F2, drive to F3 mow F3, stop), a worker have to pass through 3 gates between fields if it matters.

**Comment by pops64** [comment]
Got the order wrong. Drive to f1 mow f1, drive to f2 mow f2. Etc. And theses all have to be separate courses. Had CP can't combine field work courses together and it won't be something we will change
