### ISSUE TITLE
Multiple Tractors Ploughing 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#2654]
Hello i've done this before but i'm trying to setup three tractors to plough same field but when i set the second tractor off its says its stuck in traffic ive included a pic 
![fsscreen_2018_03_25_17_55_13](https://user-images.githubusercontent.com/27097241/37877645-2a001b4a-3056-11e8-8a8f-63ef7561ce12.png)

**Comment by ThomasGaertner** [comment]
which weight did U use ? can send me the log with debug 3 active , tanks

**Comment by matty2123** [comment]
Close the problem for now I tried last night and there was no problems will report if this changes
