### ISSUE TITLE
Turns on field w/ mower after headland

### ISSUE THREAD

**Issue by kobra60** [Courseplay/courseplay#2655]
I've been having a problem with getting a mower to turn when it's going up and down the field after it's done with the headlands.  (I finally caught it as it happened and localized it.)  It gets to the green marker to turn and fails.  If I'm not watching that mod when it happens, it freezes up the game and I have to Ctrl Alt Del to get out and shut down the game.  The self propelled mowers seem to be the big issue.  I've tried many with the same result.  I've changed the turn radius, the number of machines on the course to widen the turn required. Turned off the turn on field function. Tried an older version of CP too as I had the dev version. Changed starting points.  All to no avail.  I have run the BigM before with no problems but now there is.  Is there something else I can try?  I'll include some screenshots as well.

![20180326004829_1](https://user-images.githubusercontent.com/36580296/37889898-12224b68-3094-11e8-9e2a-396195bf56f1.jpg)
![20180326004842_1](https://user-images.githubusercontent.com/36580296/37889922-284ad55e-3094-11e8-83e6-17a0eb124917.jpg)
![20180326004929_1](https://user-images.githubusercontent.com/36580296/37889923-285f5628-3094-11e8-9998-b90d51819bdf.jpg)
![20180326004934_1](https://user-images.githubusercontent.com/36580296/37889924-286e7a5e-3094-11e8-8166-8839c89936fa.jpg)
![20180326004939_1](https://user-images.githubusercontent.com/36580296/37889925-2884ad7e-3094-11e8-9860-1e93e22c92c4.jpg)

**Comment by kobra60** [comment]
In that first pic, it had to make a very tight turn to start the non headland part.  It took that with no trouble.  It's in the fourth pic that it's approaching the problem spot.  I tried it at different spot across the course too with the same result.

**Comment by pvajko** [comment]
This is a mod problem, see #2397 and many others.
