### ISSUE TITLE
Courseplay schaltet kein Licht ein

### ISSUE THREAD

**Issue by DM0503** [Courseplay/courseplay#2656]
Hallo erstmal,

bei mir besteht das Problem das Courseplay irgendwann anfängt bei den Fahrzeugen kein Licht mehr anzuschalten. Mittlerweile ist es die 3. Map auf der das passiert. Das passiert sporadisch, bei der ersten Map dauerte es recht lange bis das Phänomen einsetzte, bei der 2. Map dauert es ca. 300 Spielstunden bis Courseplay kein Licht mehr anschaltete. Hab jetzt ne neue Map gestartet und hier hab ich es schon nach 10 Spielstunden das Courseplay kein Licht mehr anschaltet.

Bin langsam am verzweifeln da ich nicht mehr weiß wo ich noch suchen soll. Hab es mit und ohne Mods probiert. Hab sämtliche Einstellungen überprüft, alles in Ordnung. Der Standart-Helfer macht das Licht korrekt an nur Courseplay verweigert irgendwann den Dienst.

Gruß Dirk

**Comment by pops64** [comment]
English please as support will be limited https://github.com/Courseplay/courseplay/wiki

**Comment by ThomasGaertner** [comment]
Ich habe jetzt alles durchgeschaut, Keine Ahnung wie das gehen soll.
Wir holen uns die Bedingungen direkt aus dem Spiel, die der Helfer auch benutzt. 
Ich mach hier mal zu ... sorry
