### ISSUE TITLE
Abfahrer und Traktor mit Schiebeschild bleiben stehen.

### ISSUE THREAD

**Issue by FreelancerTrent** [Courseplay/courseplay#2657]
Hallo zusammen,

ich habe das Problem, dass sich der Abfahrer und der Traktor mit dem Schiebeschild gegenseitig ausbremsen.

Der Traktor mit dem Schiebeschild steht auf seiner Parkposition und der Abfahrer kommt und bleibt ebenfalls stehen. Danach ist Stillstand(siehe angehängte Bilder).

Es geht nichts mehr vorwärts und nichts mehr rückwärts.
![fsscreen_2018_03_26_21_57_11](https://user-images.githubusercontent.com/18641585/37930008-c7ad3760-3141-11e8-96b8-142bf81de21d.png)
![fsscreen_2018_03_26_21_56_51](https://user-images.githubusercontent.com/18641585/37930021-cd6d9ae6-3141-11e8-95d6-eee4f4ea8b38.png)

Eventuell hat jemand einen Rat.

Danke!

Trent

**Comment by pops64** [comment]
English please as support will be limited https://github.com/Courseplay/courseplay/wiki

**Comment by FreelancerTrent** [comment]
english version:


Hello everybody,

I have the problem that the tractor with the maize chaff and the tractor with the shield mutually braked.

The tractor with the shield is standing in its parking position and the driver comes and stops as well. After that is a deadlock (see attached pictures).

There is nothing moving forward and nothing backwards.

**Comment by FreelancerTrent** [comment]
One possible reason for the blockage could have been the use of a mod. I used a Fendt 1050 for compacting.

**Comment by andreasthu** [comment]
Stands in the near another tractor/trailer with someone load?
Gras or forage?
Or is someone in the whealloader shovel?
I had a while ago the same.
A lkw with gras stands i  the near, the leveler stands still, waits for the trailer, the trailer stands still, wait for the lkw.
When i drive the lkw away the work goes on.
When i empty the lkw and drive also in the near it was ok while empty.
Lg
Andreas

**Comment by ThomasGaertner** [comment]
if the problem still exists , please give me your save game and your courses folder thanks

**Comment by pops64** [comment]
inactivity
