### ISSUE TITLE
2017 Big M500 Plane nicht senkbar

### ISSUE THREAD

**Issue by TheRealMrToasT** [Courseplay/courseplay#2658]
Hallo,

Ich wollte mit dem Big M500 (aus dem FS Mod-Hub) über CP Gras mähen. Bei dem Fahrzeug gibt es die Option "Plane öffnen/schließen" bei geschlossener Plane entsteht eine Schwade und bei geöffneter wird nur gemäht. Bei CP habe ich nun auch die Option die Plane zu "deaktiviert" oder "automatisch" zu stellen, allerdings ist sie in beiden Fällen offen. 

(Bild 1: Ohne CP ist die Klappe bzw. Plane hinten geschlossen)
![ohnecp](https://user-images.githubusercontent.com/37816810/37935637-991919e4-3152-11e8-8c59-6f3e3a1dd9fb.png)

(Bild 2: Mit CP, obwohl im fester deaktiviert ist die Plane offen)
![mitcp](https://user-images.githubusercontent.com/37816810/37935642-9f93d34a-3152-11e8-86be-78f566e3bd93.png)

Vielleicht kann mir ja jemand helfen.

Danke schon mal!

**Comment by Blackmankot** [comment]
Hallo.
Laden Sie eine andere Version dieses Mods herunter. Zum Beispiel von hier -
https://www.modsgaming.us/load/farming_simulator_2017/fs_17_mowers/the_big_m_by_krone_v_1_3/23-1-0-428#

**Comment by pops64** [comment]
English please as support will be limited https://github.com/Courseplay/courseplay/wiki

**Comment by pops64** [comment]
Inactivity mod issuse
