### ISSUE TITLE
Trailer empty's further and further away from tip point

### ISSUE THREAD

**Issue by Big-Bambino** [Courseplay/courseplay#2660]
Hey Guys,

With my previous issue, I've changed my way of empting my trailer's in CP, so now in reverse empty in to the bunker, but now I've got a other issue "ish". 
When the trailer reverse's in to the bunker he empty fine, so i clear away what he empted whit a blade, but when he come's back, he empty further away from the last trailer, like if he thinks that the previous trailer is still there on the floor. So i end up by 0 the value that concerns this issue and wanted to know if there is a permanent fix to this.
![inked20180327192657_1_li](https://user-images.githubusercontent.com/37718956/37984850-ae48771a-31f7-11e8-84ea-3b97f601295c.jpg)

Thank's for the great work

**Comment by ThomasGaertner** [comment]
its not a bug its a feature, why do you set a unload point into the bunker ?

**Comment by Big-Bambino** [comment]
Oh i see. I placed a tip trigger because after a certern amount in the bunker (Around about 30%), the CP trailer stop's detecting the trigger of the bunker, so instead i placed a CP tip trigger. And to be honest I prefer using it this way, because the CP tip triggers seem's more reliable. I didn't know that this was a feature of the tip point.

**Comment by pops64** [comment]
I wouldn't recommend placing any wait points inside of triggers has this will confuse CP. Im surprised it didn't break anything

**Comment by pops64** [comment]
I am combineing all duplicate threads about tip triggers not working into #2661
