### ISSUE TITLE
Tip Triggers not working. 

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#2661]
I am combining all duplicate threads about tip triggers not working into this issue. Has we now seem to have a lot. Please post any further conversations here. Please download this version of CP and see if problems persist https://github.com/Courseplay/courseplay/tree/80afc4980589958968c8e4e0fb525464ceb84375

**Comment by pops64** [comment]
Alright for those of you that have tip trigger issues please post a log with debug channel 1 and 2 active. Only do this if you are running version 70 or higher. Anything less is of no help

**Comment by STW0701** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/1859733/log.txt)
Manually i can unload more at the same silo, similarly if i set an unload point it works

**Comment by pops64** [comment]
@stw0701 your problem. Is that CP thinks fillLevel > capacity and which case it should stop tipping. I can't remember if the same values are used for CP and manual map side. They should be so unless you're using the tip to ground instead of tip to trigger after CP stops. Then this is a map isse. I'll look at our code but I think this resides in a map bug

**Comment by Big-Bambino** [comment]
Good idea to fusion the posts.
STW0701 are you emptying in a bunker or a silo ?

**Comment by pops64** [comment]
@big-bambino have you purchased additional silo capacity? 
@Srw0701 your issue is definitely a map bug. If I remember correctly users can only dump to ground in bgas in 17. Our function is a hold over from 15 when it was a tip trigger. Unfortunately the command for theses are different and are handled differently both on our side and Giants.  I think in GE you can change the capacity vaule for the trigger or contact the mod arthor to fix

**Comment by Big-Bambino** [comment]
@pops64 No, it's standard on the map

**Comment by Big-Bambino** [comment]
No harm, i'm talking about emptying in the bunkers of the map, without adding any kind of placeable BGA mods or silo, just the normal bunker to stock silage. It must have something to do with the map because, I tried in a other bunker that is bigger in size, and the max capacity was at 752000. So i'm guessing there's something that is calculating this number from the "start" "end " "whith" points of the bunker in the i3d.

**Comment by pops64** [comment]
This is our calculation on free capacity line 857 in toolManager

`freeCapacity = ctt.capacity - ctt.fillLevel`

Both theses variable should giants all our internal variables are xxx.cp.xxx there are some exceptions to this but most post load stuff is setup that way

**Comment by Big-Bambino** [comment]
Nice explanation on this, the line look's a lot like the calculation that would of being used in FS 15 due to the major difference between FS17 and FS15, on the bunker side. In FS15, the bunker was a simple Fillplane that would have a max capacity defined in Giants, in the user attributes of the trigger. If this is the reason, a simple adjustment should probably, what do you think ? And why before it was working I don't know, mayby a FS 17 update ?

**Comment by pops64** [comment]
Yes FS17 really broke CP in regards to bunkers. I believe that capacity vaule still exists just not known because you tip to ground in a bunker if remember correctly when not using CP. I think if you go into GE and edit the trigger table for the bunker and set it 2 mil you shouldn't have an issue. The problem with our side is tip to ground and tip to trigger are coded two different ways and has there own variables and limits. It would be a overhaul of that function which also handles rl triggers as well

**Comment by pops64** [comment]
The same ones listed at the beginning

**Comment by MrTobbsta** [comment]
@STW0701 tried without drive controll, still no luck.
@pops64 heres the log for you
https://gist.github.com/MrTobbsta/d4d40327a9b418fc93a59f5e35ea2e9f

**Comment by pops64** [comment]
Follow all instructions listed at the beginning

**Comment by MrTobbsta** [comment]
My apologies, I totally forgot too update. This one is hopefully right.
https://gist.github.com/MrTobbsta/93038d3eeb6058390c8bca02c453b991

**Comment by pops64** [comment]
@MrTobbsta which issue # was your original? Has yours is a problem with the actual trigger I believe. I have to look at what the standard debug print out is. But best guess is that it thinks that is out of range of the trigger while a different part of the code says it still has 5.6m to go. This 5.6 should get down to around 0 then start climbing up. It only hits 5.6. This distance number is what tells CP to stop tipping while. The other part is what Giants uses to prevent tipping out side of the trigger. And since it is bunker and tip anywhere is possible you get the effect I think you described in your issue which is to continue dumping out side the bunker. Did you try this on a standard giants bunker?  I think that model of a bunker was improperly implemented in GE. Which isn't a surprise has I think it is only used by us and Giants to define what should be converted to silage. Id still have to take a look at what the standard print out is because it has been a while so this is only best guess and probably will change

**Comment by MrTobbsta** [comment]
#2652 was my original issue. I tried with the bunker on Goldcrest valley but that specific bunker is so long the the Bergmann trailer I use dosent cover the whole length of the bunkar even when full.

What parts looks for the trigger? Is it the tractor and the trailer or just the trailer? 

Thoughts from someone that dosen't know anything about programing: The Giants part that prevent tipping out side the bunker, could it be used in some way to tell the tractor to stop if the fillevel of the trailer is more that 1% or not empty?

**Comment by pops64** [comment]
@MrTobbsta How fast is it driving in your issue?  It should be doing 2kph Have you tried with a standard Giants trailer?

**Comment by MrTobbsta** [comment]
@pops64 It slows down to about 10kph for a couple of seconds then speeds back up to max speed. The Bergmann is a standard Giants trailer.

**Comment by pops64** [comment]
It should go to turn speed 6mph by default for us Americans. Then speed up to a speed that should allow it to empty in the distance of the bunker. I'll take a look at your log again. Cause it shouldn't have so much left over that it doing what was picture. I know in 15 it would stop at the end of bunker if not finshed. I'm pretty sure that made it to 17

**Comment by Bazzek** [comment]
I keep running into these problems as well with version 5.2, so i installed the version mentioned in the start post. I just ran the route and ran into my tipper offloading next to the silo dropoff point, even with the tractor fully in the center http://prntscr.com/j6isp8 (screenshot)

The log is of a newly made route, field 19 of Goldcrest Valley, with a unload trigger point at the top of the ramp up to the unload spot. Upon first attempt it seemed to work, the second attempt resulted in the below log file a huge trail of soybeans on the floor, next to and after the unload point.

[log.txt](https://github.com/Courseplay/courseplay/files/1920902/log.txt)

**Comment by pops64** [comment]
@Bazzek sorry for the long delay in reply. Never ever place an unload point near a tip trigger has this will always cause issues. Removed the unload point and CP should unload into the tip trigger just fine

**Comment by Bazzek** [comment]
@pops64 No worries about the delay, i doubt it is your full time job, so any response is a good response ;)

Anyways, i did the route without the unload point now, i guess i completely misunderstood that part before. It seems to work now (from silo to train), will experiment some more with the various fields during harvest.

I will let you know sometime later if this stopped it from dumping it beside the silo drop off :)

**Comment by Bazzek** [comment]
@pops64 i can now confirm it works as intended if you don't use the unload point near the tipper area. Not sure who keeps the faq/manual site up to date, but it may be something to specifically mention there (unless i am sort of special ed, in which case, ignore me :)

**Comment by MrTobbsta** [comment]
@pops64  Tried both CCW and CW with dev version 89, still no luck I'm afraid.

**Comment by pops64** [comment]
Could I get a pic of F5 active if you know how to enable it. If not don't worry

**Comment by MrTobbsta** [comment]
@pops64 I don't know how too do that.

**Comment by pops64** [comment]
Closed #2909
