### ISSUE TITLE
Lua call stacks

### ISSUE THREAD

**Issue by FreelancerTrent** [Courseplay/courseplay#2663]
When compacting the silo I got many of theese lua call stack:
llll
[log(courseplay call stacks).txt](https://github.com/Courseplay/courseplay/files/1865935/log.courseplay.call.stacks.txt)

Warning (Script): Unknown entity id 278097 in method 'getWorldTranslation'.
LUA call stack:
  =C:/Users/Daniel Kalenda/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/mode10.lua (13) : getWorldTranslation
  =C:/Users/Daniel Kalenda/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/drive.lua (673) : handleMode10
  =C:/Users/Daniel Kalenda/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/base.lua (974) : drive
  dataS/scripts/vehicles/Vehicle.lua (2642) : update
  dataS/scripts/network/Server.lua (56) : update
  dataS/scripts/BaseMission.lua (1518) : update
  dataS/scripts/FSBaseMission.lua (2187) : update
  dataS/scripts/missions/mission00.lua (346) : update
  dataS/scripts/main.lua (1922) : update
Warning (LUA): 'getTerrainHeightAtWorldPos': Argument 1 has wrong type. Expected: Float. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
LUA call stack:
  =C:/Users/Daniel Kalenda/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/mode10.lua (15) : getTerrainHeightAtWorldPos
  =C:/Users/Daniel Kalenda/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/drive.lua (673) : handleMode10
  =C:/Users/Daniel Kalenda/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/base.lua (974) : drive
  dataS/scripts/vehicles/Vehicle.lua (2642) : update
  dataS/scripts/network/Server.lua (56) : update
  dataS/scripts/BaseMission.lua (1518) : update
  dataS/scripts/FSBaseMission.lua (2187) : update
  dataS/scripts/missions/mission00.lua (346) : update
  dataS/scripts/main.lua (1922) : update

**Comment by ThomasGaertner** [comment]
can you give more info ? which shield did you use ? which tractor , map and so on ?

**Comment by pops64** [comment]
inactivity
