### ISSUE TITLE
Setting to make vehicles overshoot the field edge slightly?

### ISSUE THREAD

**Issue by chrisbitz** [Courseplay/courseplay#2664]
Is it possible to enlarge the ends of the fields in some way by about 1m or so, so that when the harvester turns to a new row, it's already square with the edge, and doesn't miss a tiny bit of crop?

**Comment by pvajko** [comment]
The course generator has this functionality there's just no way to set it on the HUD ad the moment. I'm in the process of implementing a new UI for the course gen setting which at some point will include this one as well.

**Comment by pops64** [comment]
There already is an option but I'm not sure how much of it is still working. I know Claus a while back made changes to this setting. It is the vertical offset when in mode 4 or 6

**Comment by chrisbitz** [comment]
Ahh thanks for the great replies - So the vertical refers to the Z or X axis, rather than the actual Y (up/down) axis?

**Comment by Zoochase** [comment]
As a suggestion, I increased all my fields with a plow and the "create field" option.  Did a User Override to save the larger field in CS.  Then used the restoring roller, R5000 to decrease the field edges by a couple meters.  Problem solved.

**Comment by pops64** [comment]
Closed #2909
