### ISSUE TITLE
CP causes FS to crash

### ISSUE THREAD

**Issue by Ntone107** [Courseplay/courseplay#2665]
I use several CP courses on Hobbs Farm, apparently CP causes the game to crash.
CP Version: 5.02.00070 (Downloaded & installed 2 days ago)
FS Version: 1.5.3.1
Hobbs version: 2.1

Eacht time same error in log:
Error: Running LUA method 'update'.
dataS/scripts/utils/Utils.lua(124) : attempt to perform arithmetic on local 'x' (a nil value)

https://pastebin.com/7RHEdJa0

**Comment by pops64** [comment]
Need the entire log cause ussally it is mod missing something CP can't work around

**Comment by Ntone107** [comment]
I exited my last game in a normal way, so log is clean. As soon as I have another crash, I'll post the log.

**Comment by ThomasGaertner** [comment]
with debug channel 4 active please

**Comment by Ntone107** [comment]
Had it happen again.
This time, I was resetting a machine (combine) when i happened. 2 times in a row.

[log.txt](https://github.com/Courseplay/courseplay/files/1914481/log.txt)

**Comment by ThomasGaertner** [comment]
try with v82 or higher and report....

**Comment by pops64** [comment]
due to inactivity
