### ISSUE TITLE
Configuration crash

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#2667]
Good Morning!
Have the problem when I play, e.g. configure a machine that always comes this error
LUA call stack:
   = C: / Users / Nemesis / Documents / My Games / Farming Simulator2017 / mods / ZZZ_courseplay / traffic.lua (114): getName
   = C: / Users / Nemesis / Documents / My Games / Farming Simulator2017 / mods / ZZZ_courseplay / traffic.lua (75): updateCollisionVehicle
Warning (Script): Unknown entity id 174193 in method 'getCollisionMask'.

Map Lösshügelland and Alststäd an der Elsaa! 
[log.txt](https://github.com/Courseplay/courseplay/files/1867433/log.txt)

**Comment by ThomasGaertner** [comment]
#2668 double
