### ISSUE TITLE
Traffic.lua CallStack error

### ISSUE THREAD

**Issue by ShermyPermy** [Courseplay/courseplay#2668]
Im running the dev courseplay V 5.02.00069.
I have a combine running a course on a field.
when the combine is getting close to the road and turns around it sometimes see's some cars drive by.
At that moment the game starts to stutter and the call stack starts rolling.
after a few seconds its gone again until the next car.

I have attached my log for extra info.

best regards,

Shermy

[log with CP error for Dev to look at.txt](https://github.com/Courseplay/courseplay/files/1867718/log.with.CP.error.for.Dev.to.look.at.txt)

**Comment by ThomasGaertner** [comment]
test v.73 or higher and report...

**Comment by ShermyPermy** [comment]
Good evening Thomas,

I have run the same Courseplay course on the same map and same savegame and the error is gone.
I also have done this on a new map and savegame and the error also is gone.
So thank you for fixing it.
[log.txt](https://github.com/Courseplay/courseplay/files/1895919/log.txt)
