### ISSUE TITLE
Auger wagon not unloading 

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#2669]
Hi

Ive used CP since FS13 and love it. Im having a problem using the overloader mode. Ive tried vanilla wagons and mod wagons but none will unload when they reach the wait point. I recorded the course in oveloader mode and the pipe is positioned correctly as it unloads manually in that position.

I havent got the 'manual unload' mod installed yet that is an option when CP is not being used. In the info box it says 'manaul pipe unloading:OFF'. If i press R the auger wagon unloads. I have set to OFF before i start CP

Any help be much appreciated

**Comment by pops64** [comment]
The mod needs to be disabled completely before game start

**Comment by kwguk** [comment]
I appreciate the reply
I haven’t got the manual unloading mod installed yet I still get the option. I assume that’s what’s stopping CP overloader working.
So if I haven’t got manual unloading installed what do it have to disable then??

**Comment by kwguk** [comment]
Apologies, its the 'combine addon' mod has manual unloading included in it, something i hadnt picked up on

**Comment by pops64** [comment]
You have to disble combine add-on before starting the game

**Comment by kwguk** [comment]
Done it and all working well now👍

Many thanks for the best mod for FS
