### ISSUE TITLE
tractor speed before combine overloading mode2

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#2671]
Hello guys.
I had seen, that when the tractor drives to the combine (in mode 2) the last meters he is 2 km/h faster at the combine. When he is under the overloading pipe he drives same speed as the combine.
Another fall is when the combine is at the end of the field and waits for the tractor:
Here come the tractor to the combine with 2km/h speed.
This "take ages".
Is there a way to make this speed faster? 
To 8, 10 or so km/h?
On smaler fields is this tje most overloading situation.
Lg
Andreas

**Comment by ThomasGaertner** [comment]
this speed is to prevent the tactor from overshooting if it approaches too fast.
I want you to make some tests : change the values behind "lz<" for the two situations combineStopped and CombineTurning  . these are the distances of the unloading point of the trailer to the pipe. Try to lower the values and watch , what happens. When you have satisfying values, tell me and we will discuss it. But please consider also fast moving tractors on large fields , which are overshooting sometimes with the current values...

**Comment by andreasthu** [comment]
thanks for info
i changed the row814 in the mode2.lua from
`				refSpeed = vehicle.cp.speeds.crawl		`
to
`				refSpeed = vehicle.cp.speeds.crawl + 8	`

a little test with drive to the combine, the traktor drive the last meters with 8km/h to the drescher	
i will test it later, the next days on a longer field when the combine unlaod in the middle while driving

lg
andreas

**Comment by pops64** [comment]
Closed #2909
