### ISSUE TITLE
Tip Triggers for Grain Carts in Combi Mode

### ISSUE THREAD

**Issue by specialt123** [Courseplay/courseplay#2672]
Hi All - 

I'm relatively new to the mod, but have watched several videos of people setting this up. All the ones I've seen thus far talk about setting up a grain cart by having them drive across the grain silo dump spot and it automatically recognizes it as a trigger to stop the cart and dump there. From my version, 5.2.0 of the mod, this doesn't appear to be true as my cart, an Agroliner TAW30, doesn't recognize the tip point no matter what I do. During my course setup, it operates fine gathering from the combine (most of the time), but ultimately runs the route to the grain silo and drives on by the grates without stopping to drop the grain.

I have tried as well to manually set the unload there, but it doesn't seem to work either and instead causes it to unload much past the unload section at the silo, even with a wait time of 15 sec too.

Is there something I am missing here?

Thanks,

Brandon

**Comment by specialt123** [comment]
An update here... I wasn't able to get it to work with the Agroliner TAW30 trailer/cart, but I was able to get it working with smaller trailers that can actually tip to the side. Happy to see I got it working, but it wouldn't be a bad thing either if the Agroliner TAW30 was supported as well. It functions a tad differently, pushing the grain out the back.

Thanks All - 

Brandon

**Comment by pops64** [comment]
#2661 with pictures please
