### ISSUE TITLE
New GUI for course gen headland bug

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#2679]
New course gen generates a headland pass even though none are specficed
![fsscreen_2018_04_11_12_47_36](https://user-images.githubusercontent.com/10678220/38631225-221a50b0-3d87-11e8-8f92-b2a1dd3baabe.png)

![farming simulator 17 4_11_2018 12_47_48](https://user-images.githubusercontent.com/10678220/38631184-0aae84dc-3d87-11e8-984c-3eadfe7a2ac7.png)

![fsscreen_2018_04_11_12_52_16](https://user-images.githubusercontent.com/10678220/38631241-33e4a926-3d87-11e8-8652-9bab356467ae.png)

Also is there any sort of order to the field number selection has it seemed random. Great work on the gui. now to clean up the old one :D

**Comment by pvajko** [comment]
@pops64  told you I never work without headlands ;) 

The sort order is fixed already just haven't pushed yet.
