### ISSUE TITLE
Save problem related to pipeposition

### ISSUE THREAD

**Issue by Fendt105** [Courseplay/courseplay#2681]
Hi guys,

I have a problem with my savegame, that I think is courseplay related.

I'm playing on Candian Ultimate 10.1, using courseplay version 5.02.00073.

The game won't save anymore and all the savegame files are deleted, except the courseplaycustomfields and courseplaysettings. The vehicles.xml also remains but is empty.

From my opinion the problem starts as soon as I use the overloaders and save their pipe position. From that moment on I can't save anymore, and the game freezes when I try to. I'm using the vanilla GTW 430 and Fendt 724. I can't however figure out what the exact problem is. Could you guys help out?

https://gist.github.com/Fendt105/812da85388527320cb82d73aa7f3018d#file-gistfile1-txt

**Comment by s1100** [comment]
it´s the vanilla gtw or the gtw which can all loaded?
the gtw which can all loaded makes this problem

**Comment by Fendt105** [comment]
I don't have a modified GTW 430, so yes it is the vanilla one.

**Comment by ThomasGaertner** [comment]
unfortunately I can't replicate it here. Can you give me a step by step instruction how to replicate it . Did you try on a vanilla map, whether it works there ??

**Comment by Fendt105** [comment]
I don't have a step by step instruction yet. I'll try it on a vanilla map and see if I can pinpoint the exact error. I'll post it here if I find something.

**Comment by Fendt105** [comment]
Hi Thomas,

I've found a way to replicate the problem, using just vanilla equipment and maps.

Mods folder cotains only the Kuhn Pack and courseplay.
Start a savegame on GCV
Sell all the sheds and equipment, except the New Holland tractor.
Buy a GTW 430 and a 2300kg weight
Attach the overloader first, so you end up with the weight highlighted in your machine selection (the one you change with "g".
Record a course without unfolding the pipe.
Then hit "g" to select the overloader and hit "o" to unfold the pipe.
Save the pipe position in courseplay.

If you try to save your savegame now the game will freeze.

The problem does not occur when you have the overloader selected when you record the course. With this I do have a workaround for it but i can imagine more people running into trouble with this one.

https://gist.github.com/Fendt105/262220d42f8fc91e0adf74b4f40ac437
