### ISSUE TITLE
Course generation GUI manual starting direction issue

### ISSUE THREAD

**Issue by aviator64** [Courseplay/courseplay#2683]
It is not possible to choose a starting direction in the south hemisphere - when scrolling through the possible directions, the GUI jumps from 90 to 270 so not possible to select south.

**Comment by pvajko** [comment]
What you actually select there is the direction of the up/down rows. Meaning N and S will result in the exact same course., so for South, just select 0.  I'll probably change the label or just add the full 360 so there's no confusion.

**Comment by aviator64** [comment]
OK that make sense. It's just that in the old course generation dialog, you can choose any compass direction which is what made me think it was a glitch in the new GUI.
