### ISSUE TITLE
Feature Request - have tractors in combi mode stay on field

### ISSUE THREAD

**Issue by aviator64** [Courseplay/courseplay#2684]
Many fields, especially those on European maps, are closely surrounded by obstacles such as fences, stone walls, etc. 

When a tractor is working in combi mode, it often leaves the field in order to turn at the end of a row, and then hits the obstacle, resulting in a "tractor X is slipping" message and requiring it to be manually re-positioned.

Would it be possible to add a setting to force the tractor to always stay within the boundaries of the field, even if that means driving over the crops?

This would allow CP to be used with many more maps and fields.

**Comment by aviator64** [comment]
I'm not talking about the combine, but rather the tractor/tipper that follows it. Even on a headland, if the trailer fills up it will turn off the field before heading towards the delivery course.

**Comment by hpmc13** [comment]
I am not remotely a programmer so I have no idea if this is possible, but, can the harvestor "see" the end of the row? If so, and it's not done offloading into the tipper, could it stop or slow down so that the tractor has space to turn?

**Comment by ThomasGaertner** [comment]
should be Ok since v.76 .....

**Comment by Zoochase** [comment]
Can we make this staying on the field thing an option?  As of late, when harvesting potatoes with the Grimme, my tractor will back up if at the end of a field but not far enough to clear the harvester.  This then turns into a stand off with the tractor saying it is blocked.  Also noticed when it does pull in behind the harvester, it is too close to the fruit and blocks the harvester on its return pass.

**Comment by pops64** [comment]
Closed #2909
