### ISSUE TITLE
Kollisionen erkennen und handeln

### ISSUE THREAD

**Issue by fritzix** [Courseplay/courseplay#2691]
Hi Coursplay Team,
ich schreibe hier jetzt mal auf Deutsch, ich hoffe es stört nicht.
Der Courseplay gefällt mir sehr gut aber, was mich immer stört, ist wenn der Traktor beim Pflügen,Säen,Wenden etc. pp. auf kleinen Feldern oder auf eingezäunten Feldern gegen den Zaun fährt.
Kann man den Coursplay nicht so programmieren das der Traktor oder Selbstfahrer nach der Meldung das er feststeckt dann einfach etwas weiter zurückt fährt, wendet und die nächste Spur weiter bearbeitet.
Ich glaube sogar das der Courseplay diese Funktion schon mal in einer früheren Version hatte wenn ich mich nicht täusche. 
MfG fritzix

**Comment by ThomasGaertner** [comment]
du kannst in den Einstellungen wählen, dass der Traktor auf dem Feld wendet und es nicht mehr verlässt. probier es aus....

**Comment by fritzix** [comment]
Die Funktion ist doch Standardmäßig aktiviert ?

**Comment by pops64** [comment]
Inactivity and not in English
