### ISSUE TITLE
CP entering field before and exiting field after fieldwork

### ISSUE THREAD

**Issue by cpoole2005** [Courseplay/courseplay#2694]
Is there a way to make it so when sowing, fertilizing or harvesting to have your equipment's start and end point off the field? What I want to do is have my machine(s) "standing by" off the field hit Drive Course the machine drive from where it is onto the field up to the field works actual start position do the field work then drive off the field and back to it's "standby" position.

**Comment by pops64** [comment]
You can have transfer course before field to take it from a parking spot to the field. But you can't place anything but a refill course at the end. And this is something we aren't going to change has it would require a major rework of how CP does field work in mode 4 and 6
