### ISSUE TITLE
horizontal tool offset set automatically only first time ever attached

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#2697]
I started a complete new game with CP (5.02.0083) as only mod activated.

I saved it, cheated some money into the careerSavegame.xml and started again.
Then I bought some stuff: Case IH Puma, NH T9, **all plows** and the Horsch Pronto 9 DC.

I took the Puma and attached the first plow "Salford 4204". CP showed me a tool offset of 0.2 left
![farmingsimulator2017game_2018_04_21_21_10_57_869](https://user-images.githubusercontent.com/666825/39088074-3fa2ab5a-45ac-11e8-9b73-245c9e560b4a.png)

After detaching the plow the tool offset didn't went back to 0
![farmingsimulator2017game_2018_04_21_21_11_29_978](https://user-images.githubusercontent.com/666825/39088085-6539e02c-45ac-11e8-9a44-ad3cf7013bb0.png)

When attaching an other tool after that, the tool offset won't change automatically I always have to set it manually. Only the first ever tool offset to a vehicle other than 0 will get set automatically.

To verify that I took the NH T9 and attached the Horsch Pronto 9 DC first. Of course there was no change in tool offset only in working witdh:
![farmingsimulator2017game_2018_04_21_21_27_18_003](https://user-images.githubusercontent.com/666825/39088143-382ec60a-45ad-11e8-9986-285b92d4195c.png)
![farmingsimulator2017game_2018_04_21_21_27_30_071](https://user-images.githubusercontent.com/666825/39088146-3d749a36-45ad-11e8-9b32-791164d303ed.png)

After detaching the working width changed to 3.0m again
Then I attached the plow Salford 8312, the tool offset changed to 0.4 right and the working width to 6.2m
![farmingsimulator2017game_2018_04_21_21_28_11_007](https://user-images.githubusercontent.com/666825/39088158-74ea9826-45ad-11e8-8891-c698b4b6d5e7.png)
![farmingsimulator2017game_2018_04_21_21_28_15_275](https://user-images.githubusercontent.com/666825/39088174-a3f202f8-45ad-11e8-85b9-43e9cb6a047a.png)

After detaching the working width went back to 3.0m but the too offset stayed at 0.4 right even when I attached the first plow Salford 4204 again instead of changing to 0.2 left. 
![farmingsimulator2017game_2018_04_21_21_29_22_748](https://user-images.githubusercontent.com/666825/39088185-e501d9e4-45ad-11e8-9202-dfa47fd51217.png)

No matter if the next attached tool is a plow or any other tool. The tool offset won't change automatically anymore.

**Comment by pops64** [comment]
Yea this is already on my list of things to improve

**Comment by pops64** [comment]
Closed #2909
