### ISSUE TITLE
Courseplay dont load 

### ISSUE THREAD

**Issue by Gentlemen1988** [Courseplay/courseplay#2699]
I downloaded the Courseplay version that was fixed a few minutes ago and now i have this error 

Load mod: FS17_ClarkForklift (Version: 1.0.0.0)
Error: Failed to open xml file 'C:/Users/DerPr/Documents/My Games/FarmingSimulator2017/mods/FS17_Courseplay/modDesc.xml'.
Load mod: FS17_Courseplay
Error: Missing descVersion attribute in mod FS17_Courseplay
Load mod: FS17_DammannProfiClaasTandem (Version: 1.0.0.1)
Load mod: FS17_DCK_Glance (Version: 1.0.3.40)

I hope you can fix it ^^

**Comment by pops64** [comment]
Please reinstall and ensure all files have been copied successfuly
