### ISSUE TITLE
Question about startingposition

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/courseplay#2703]
Hi,

there has been many updates and many new features for CP witch I rly rly like.
But as more things come in, as more confusing something gets, specialy if got some things twice.

So:
What is the actual difference between (for example) 'southwest' and 'south-west'.
I know it came with the new coursgenerator and in the new GUI got only the 'south-west' one left.
Is the old 'southwest' going to be removed, or is there an actual difference?
If so, an explination on the Website would be good.

Newest Version runs rly great so far btw, just a feedback.
Greetings,
Tensuko

**Comment by pvajko** [comment]
Thanks,

well, the original English text is probably less confusing: 'South-West' vs. 'South-West (new)', indicating a little more clearly that the (new) is using the new course generator, that is the only difference.

We just haven't made up our minds yet to get rid of the old course generator completely, in fact we had plans to replace the course gen HUD page completely with the new GUI.

I agree that the current situation is confusing with the two GUIs and both old and new active and we'll eventually clean that up, it is just a lot of work and not much fun.

And we are still looking for volunteers to maintain the webpage :)

**Comment by Tensuko** [comment]
I could try to create some explanations for the Website in eng and ger, but you would have to read it and check if I did it right xD
As long no PHP or other script knowledge needed, I can even try bring that into the website.
Maybe Create some new style of explanations, since I find some still confusing xD

**Comment by pvajko** [comment]
That would be awesome. There are no scripts, all you have to do is clone the Courseplay repository, check out the gh-pages branch, make your changes and create a pull request. We could then easily review the changes and merge them.

**Comment by Tensuko** [comment]
Can you provide me a link where to get and where to make push request ? All I see so far is just CP itself in the Code Section.

**Comment by pvajko** [comment]
It's the same repository as the code: https://github.com/Courseplay/courseplay you only have to check out the **gh-pages** branch and that branch has the webpage.
Not sure how familiar are you with the github workflow, there are some good guides at https://guides.github.com/ especially https://guides.github.com/activities/forking/

**Comment by Tensuko** [comment]
ok thank you I will take a look at it. Since nothing to do at work...
