### ISSUE TITLE
Unable to load into saved game

### ISSUE THREAD

**Issue by hellewellth** [Courseplay/courseplay#2705]
My game stops loading and the log has errors. 

Error: D:/My Documents/My Games/FarmingSimulator2017/mods/FS17_Courseplay/courseplay.lua:109: 	COURSEPLAY ERROR: could not load file D:/My Documents/My Games/FarmingSimulator2017/mods/FS17_Courseplay/course-generator/CourseGeneratorScreen.lua

and

Error: Running LUA method 'loadMapFinished'.
D:/My Documents/My Games/FarmingSimulator2017/mods/FS17_Courseplay/hud.lua:96: table index is nil

full log.. https://pastebin.com/W2PhpBV1

**Comment by pvajko** [comment]
See #2677 for the solution.
