### ISSUE TITLE
Saving Unloader Pipe Position Deletes Save Files

### ISSUE THREAD

**Issue by SilentTrouble** [Courseplay/courseplay#2708]
I have been burned so bad by this, finally found it. I think... Still trying to duplicate more than 3 times.

**Comment by Fendt105** [comment]
#2681 Sounds like the same problem I reported a few days back. Are you using the most recent version of courseplay?

**Comment by SilentTrouble** [comment]
Yrs

**Comment by SilentTrouble** [comment]
I say yes but I'm using the version that came off the website that linked
to get hub and said it was from 10.27 5.2.0 so maybe not? I see a lot of
sub relases here where should I be getting the latest version if not the
official site link?

**Comment by Fendt105** [comment]
Looks like that is not the most recent version. Here on Github on the "code" page you'll find a green download button. If you download it there, you'll have the most recent version.

**Comment by pops64** [comment]
Duplicate
