### ISSUE TITLE
courseplay  bad drive

### ISSUE THREAD

**Issue by sixtys666** [Courseplay/courseplay#2709]
Hello, I want to ask how to set up workstations through corseplay to not go through fields that are already seated or what is not picked up ..? they will destroy my crop, if it is possible for the dev to try to add the property of the workers to watch somewhere where they are seated or where they are not picked up to carry then if possible if it is in fs 19 corseplay ... :)

**Comment by pops64** [comment]
? If talking mode 2 or 3 use the pathfinding option. This works pretty well at avoiding fruit. Has for the other modes. Planning where your courses are usually can get CP from driving over fruit.

**Comment by AndyK70** [comment]
Are you talking about the Mod [4Real Module 01 - Crop Destruction](https://farming-simulator.com/mod.php?mod_id=50271&title=fs2017) from the ModHub?
Hired workers like stock helper and also CP worker do not destroy fruit!?

**Comment by pops64** [comment]
Inactivity
