### ISSUE TITLE
2 questions about entries in a course (courseplay.xml file)

### ISSUE THREAD

**Issue by Opa-Andre** [Courseplay/courseplay#2710]
Hi all,
I've got 2 questions about the entries in a Courseplay file.
Q1: The waypoint "lines" consist of entries like angle, speed, pos and additional properties, like for example unload. When recording a course those entries will be recorded in specific order - for example the unload parameter (when used) is stated before the speed and pos parameters. Question is: When courseplay is interpreting the waypoint entry, is this entry parsed sequentially - means, that the parameters need be defined in the exact order, or can the parameters be in different order? 
Example: Recorded entry is:
`<waypoint5 angle="180.00" unload="1" speed="0" pos="804.71 279.76"/>`
Would courseplay also work the same way with the entry:
`<waypoint5 angle="180.00" speed="0" pos="804.71 279.76" unload="1"/>`

Question2: specific question about the "angle" parameter in a courseplay file:
Assume 3 lines in a courseplay file:

```
<waypoint1 angle="90.00".......(further parameters like pos)/>
<waypoint2 angle="80.00" ......(further parameters like pos)/>
<waypoint3 angle="70.00" ......(further parameters like pos)/>
```

The question is about the "angle" parameter in waypoint2: 
Is the angle="80.00" parameter defining the angle which is needed to reach the waypoint 2 position (from waypoint1 -> waypoint2) or is it defining the angle which needs to be set at waypoint2 in order to reach waypoint3?

Reason for the questions is that sometimes while recording courses with keyboard you make light changes to stay on streets and I want to use Excel to cleanup those mistakes. So it would be great if it is possible to change the order of the parameters to for example always have same structure (WP number, then angle, then speed, pos and finally have the possible additional parameters at the end of the line (Q1) and that I will be able to correctly recalculate the angles based on changes in the position parameters (Q2).

Thank you very much in advance for your answer as I couldn't find any documentation about those details.

Andre

**Comment by AndyK70** [comment]
As for Q1: The order of the parameters is irrelevant. 
Q2: sorry, I don't know that

**Comment by pvajko** [comment]
Angle at wp1 is the angle of the vector from wp1 to wp2.

You may also want to check https://github.com/TinyCrocodile/Coursedrawer

**Comment by Opa-Andre** [comment]
Thanks to both of you for your answers! This helped alot. 
Also tried Coursedrawer. Unfortunately it does have a bug / glitch when recalculating angle values, which I just reported there.
