### ISSUE TITLE
Suggestion for Mode3 (Overloading)

### ISSUE THREAD

**Issue by Opa-Andre** [Courseplay/courseplay#2711]
Hi all,

I'm playing on maps where some of the fields to have an "island" within. When generating a course for the combine and detecting those islands this works fine. However when using mode3 for an overloader, they calculate their way from and to the combine as a straight / shortest path. So, independent of the recorded path - start-overloading point-end, they might drive straight through the island and get stuck within. So it would be nice if they also could detect an island to drive around instead of just using the shortest path for unloading the combine. Would this be possible?

Thx
Andre

**Comment by pvajko** [comment]
If @ThomasGaertner helps me with the mode3 code then we can add this.

**Comment by Opa-Andre** [comment]
Thx much for considering to implement this feature!
Andre

**Comment by pops64** [comment]
Closed for now added to the list
