### ISSUE TITLE
Saved Game and Reloaded Courses are now Gone

### ISSUE THREAD

**Issue by whitakerboy8** [Courseplay/courseplay#2712]
I was playing a game and wanted to download a mod so I saved the game and closed out of FS15. I put the mod into the mod folder, then reloaded the game and my courseplay courses were deleted. How do I get courseplay to start saving my courses even if I save the game and quit?

**Comment by pops64** [comment]
We no longer provide support for FS15. Unless all your courses are temporary they should be saved  when you hit the save button in the CP hud

**Comment by whitakerboy8** [comment]
They aren’t saving. 

Best Regards

Whit Whitaker

**Comment by pops64** [comment]
Short of trying common debug steps, turn off anti virus, running as administrator etc. We don't provide support for FS 15 bugs any longer. Sorry.

**Comment by whitakerboy8** [comment]
Who does then?

Best Regards

Whit Whitaker

**Comment by pops64** [comment]
Anyone can. I have never heard of your issuse before when FS15 was the current version. So make sure you have the official last version of the dev copy .https://github.com/Courseplay/courseplay/tree/FS15_Legacy?files=1 And you could try deleteing the saved course file has it may have gotten corrupted

**Comment by AndyK70** [comment]
If files aren't saved at all and every time you start a your game new all courses are gone, then you have an issue in the access rights (no write access) of the file system.

**Comment by whitakerboy8** [comment]
ok. So how do I fix the issue?

**Comment by AndyK70** [comment]
> whitakerboy8 wrote:
> ok. So how do I fix the issue?

The quick'n'dirty way would be launching FS17 explicit as admin (_right click icon, and select "Run as admin" from context menu_)
The proper way would be investigating on which account FS17 is running and then looking up the access rights starting from root folder each folder until you reach your FS17 Settings folder, e.g. **"c:\users\whitaker\documents\My Games\FarmSimulator2017\"** and on each folder where the full access rights are missing granting them. (_right click folder, select properties, change to security tab, select the right account, grant full access rights, click ok_)

**Comment by pops64** [comment]
Your anit virus could also be preventing creation of new files. Has I first posted has theses are the two most common causes of your issue
