### ISSUE TITLE
Overloader Course

### ISSUE THREAD

**Issue by kobra60** [Courseplay/courseplay#2713]
I've been doing extensive testing on overloader courses both with tractors and trucks or non trailer overloaders.  I have many problems with the vehicle lining up on the course and running in circles at the start.  This was discussed in issue #2646 but I've needed to go farther with it.  When I'm using a truck, and I select align with first waypoint, it usually aligns with the third one.  Using the tractor it almost always aligns with point 2.  Never with the first one and with what I want to test, that's better.  I thought I had it licked when I was consistently getting the trucks to start on point 3.  When making my course, I would pause it at the 3rd point and run out farther before unpausing creating a large gap.  This allowed the vehicle more space to correct its course and it would work perfectly.  The problem I'm having is that for some reason they still want to line up on point 2 sometimes.  Is there someplace in the LUA that I can mess with these settings?  I would like to see if I can get them to always line up on point 3 or the other solution would be to allow pausing after the first point so I can create larger gaps as I see fit.

I should say too that the main reason for this happening is the high speeds that I use in the fields.  It's overshooting the course when it's coming in from the side of it.  Easily remedied with more space to maneuver at the start.  3 or 4 vehicle lengths would probably work.

Thank you.

**Comment by kobra60** [comment]
From pops64's comment, should I take it that I should select "Align with first waypoint" while creating the course?  I've only been creating it and later when running it I selected that.  I'll mess with that a little tonight.

**Comment by pvajko** [comment]
Align wp has no affect on course creation.

**Comment by Yasp0** [comment]
Any update on this? My overloader keeps running in circles for almost 1 ouf of 3 times. I recorded a quite long route but no success.

**Comment by pops64** [comment]
It should be working better now that pvajko switched aling waypoint to a turn maneuver it should line with the first point. I know it not perfectly algined but if you put about 2 vehicle lengths between you and the waitpoint for unloading it should work with out getting in traffic issuses. You could also turn off physics altering mods has CP isn't compatiable with them when trying to break at highspeeds

**Comment by pops64** [comment]
Closed #2909
