### ISSUE TITLE
Sower Not getting to the end 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#2714]
Ive downloaded the lastest update of cp and currently sowing a field but ive noticed its not reaching the end its missing bits at the end of the row see pics to see what i mean 
![fsscreen_2018_04_28_12_31_17](https://user-images.githubusercontent.com/27097241/39396135-99b9c608-4ae0-11e8-8794-3e49443df597.png)

**Comment by pvajko** [comment]
Not a very useful screenshot, maybe if you had one showing the course generator settings and the course itself, like the new Advanced Course Generator Settings screen?

**Comment by matty2123** [comment]
Please ignore this I’ll close it my mistake
