### ISSUE TITLE
Question about new course generator.

### ISSUE THREAD

**Issue by Raints** [Courseplay/courseplay#2717]
Is it possible that if I generate course for forage harvester with new course generator, all my mode 2 driver's start acting weird. At start they work just fine with headland's, but sometime they start driving in the fruit side and then they just collide in turn maneuver. I would use the old generator but my field shape's are not so perfect for it.

![nimetu](https://user-images.githubusercontent.com/3618060/39471783-c214af9a-4d4d-11e8-9d63-f456c47f4876.png)

Added a picture. The black line is where mode2 driver's start the driving in fruit side.

**Comment by pvajko** [comment]
When you say the start driving in the fruit side, you mean they keep consistently doing it until the harvester reaches the western edge of the field? Or do it only around the black line?

**Comment by Raints** [comment]
![nimetu](https://user-images.githubusercontent.com/3618060/39476541-f7d493a4-4d64-11e8-94b5-8b802a383fd0.png)


Sorry, my english not so good. When forage harvester start's, then all good with headland's and section marked in red, but when harvester start's long line (blue) then mode2 driver's start's to drive on fruit. Did try to change the driving side, so I clicked left-right-auto and driver did stay on the correct side, but next driver did go back to fruit side. Weird thing is if the mode2 driver making is turn maneuver, they will stay and backing up in the correct position, but when harvester start's to move, then they cut back to fruit side.

**Comment by pops64** [comment]
This has nothing to do with the course generator. Please make sure you have the latest version of CP. And post log with debug channel 4 active

**Comment by Raints** [comment]
@pops64 I do have latest dev version and this was a question since I have no that kind of issues if I make course with old generator. Will try to get log with channel 4 active.

**Comment by pvajko** [comment]
@pops64 I do think it is related to the course generation due to the misuse of the ridge markers when deciding which side to go.

**Comment by pvajko** [comment]
This is a field which the course gen must split into multiple blocks and somewhere there the ridge markers aren't calculated correctly.

Honestly, no idea why are we using the ridge markers for this, the log clearly shows that we get it right first and then screw it up based on the (obviously wrong) ridge markers.  

[dbg4 lp28628 18:34:42] FR850 (#1):courseplay:sideToDrive: threshWidth: 6.00
[dbg4 lp28628 18:34:42] FR850 (#1):courseplay:sideToDrive: fruit(21): left 378.000000, right 36.000000
[dbg4 lp28628 18:34:42] FR850 (#1):courseplay:sideToDrive: is Courseplayer
[dbg4 lp28628 18:34:42] FR850 (#1):courseplay:sideToDrive: fruit after check: left 0.000000, right 100.000000
[dbg4 lp28628 18:34:42] FR850 (#1):courseplay:sideToDrive: return fruitside right
[dbg4 lp28628 18:34:42] mode2.lua(968): 900 Vario (#3) @ FR850: combine turns right, I'm left. Turning the new way
[dbg4 lp39031 18:37:39] FR850 (#1):courseplay:sideToDrive: threshWidth: 6.00
[dbg4 lp39031 18:37:39] FR850 (#1):courseplay:sideToDrive: fruit(21): left 0.000000, right 378.000000
[dbg4 lp39031 18:37:39] FR850 (#1):courseplay:sideToDrive: is Courseplayer
[dbg4 lp39031 18:37:39] FR850 (#1):courseplay:sideToDrive: fruit after check: left 100.000000, right 0.000000
[dbg4 lp39031 18:37:39] FR850 (#1):courseplay:sideToDrive: return fruitside left

**Comment by Raints** [comment]
Thanks for answer.

**Comment by pvajko** [comment]
Can you post the saved course file so I can verify my theory?

**Comment by Raints** [comment]
Hey, sorry about late respond. It's not exactly same course. Hope it help's.

[courseStorage0001.zip](https://github.com/Courseplay/courseplay/files/1976320/courseStorage0001.zip)
