### ISSUE TITLE
manage courses button fail

### ISSUE THREAD

**Issue by texfsu99** [Courseplay/courseplay#2718]
I was able to use it perfectly, one time, and that one time was amazing. However, now any time I hit "manage courses" the hud disappears and will not come back up. I've tried right clicking, left ctrl del, I dont have a keypad. I can use my keyboard commands to run whatever course was loaded but the HUD will not come back up. So basically I can create new courses and save them but I can't pull them back up without clicking the "manage courses" button.

**Comment by pops64** [comment]
Log please

**Comment by pops64** [comment]
Inacitivity
