### ISSUE TITLE
Mode 2: Path finding when chopping corn

### ISSUE THREAD

**Issue by krambc** [Courseplay/courseplay#2720]
Good afternoon everyone. a few days ago update CP and I was pleasantly surprised to see that in the latest version the path finding worked very well. Harvesting a field, the tractor circles the entire field to find the harvester without stepping on parts of the unharvested field. My surprise came when I programmed CP for chopping corn. Should not avoid the parts of the field not harvested? Is it a problem when configuring the route or is it normal to do so?

Thanks, and excuse my English level.

**Comment by pvajko** [comment]
A little more information would certainly help, please post a full log with debug channels 7 and 9 active. 

As the pathfinding works with a finite resolution it can happen (for example when only one headland pass was made) that it can't find a path. In that case it reverts to dumb mode and just drives through everything. 

I can't imagine why this would be specific to corn, after you have enough harvested area it should definitely find a path as long as you are using mode 2.

**Comment by krambc** [comment]
Hi, i'm not able to get the log now, but i can explain a little better.

I usually use AIVehicle to manage the Combine harvester or forage
harvester. I do 3 headlands and then the rest of "field work".

For both kind of harvesting, i use CP to manage the tractors/truck to cart
grain to silo/chaff to bunker.

So, this last weekend i update CP (i've been a long time without updating).
I start harvesting a canola field and i realized that the tractor goes
araound all the field to unload de combine harvester when i vas harvesting
the headlands. I was very surprised, so before i've updated the tractor
would have crossed the field over the unharvested area to reach the combine.

After combining the canaloa field i've tried to chopp a corn field. I set
de forrage harvester with AIvehicle, as i've mentioned above, and set a
route with CP to unload chaff in a bunker. I've asigned to tractors for
carting chaff. I start and all seems to work well. When the first tractor
became full, cross the unharvested field to reach the first point in the
course.

After unloading the chaff, when reaches the last point of the route, the
tractor stops for a couple of seconds till detects de forrager. In this
moment apears a message that says something like (following the tractor)
and it cross another time the unharvested field to follow the other tractor.

I thought that the problem is using 2 or more tractors because when the
forrager have "selected" one of these, the other tractor "don't follow the
forrager". Instead they "follow the selected tractor".

I tried again, only whith one tractor carting chaff, trusting that when
arriving at the field and detecting the harvester, it would drive around
the field  how it happened in the canola harvest. But again the tractor
drive through the unharvested field....

I do not know if I have clarified or complicated things further.

As soon as i can i'll  post a full log with debug channels 7 and 9 active.



2018-05-08 0:34 GMT+02:00 Peter Vajko <notifications@github.com>:

**Comment by krambc** [comment]
Well, after a couple of hours trying different things i've realized where is the problem.

First of all i've to apologize. The main problem was that, after downloading and installing the las dev version, for some reason i update CP from the mod section of the game. This install back an older version.

I've downloaded and instaled again the las dev version and the problem "was solved". Not in the first headland, but runs well from the second headland onwards.

Please apologize me and close this issue.

P.S.: I've noticed that in the manage combines section is now the option to look for combine in field XX. That was an old suggestion that i've done (#2415).

Thank you all very much for your work. FS17 would not be the same without CP.
