### ISSUE TITLE
suggestion: shortcuts for shovel positions (not preselected)

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#2721]
I know CP is for automatic use by helpers and the shovel positions are read by the script, but I really like it using the saved shovel positions when I have to feed the pigs. No fiddling around to get the right height and inclination loading the shovel, just a click to get the shovel in transport position and then at the trough another click to unload the shovel.

Just a minor annoyance is the open hud I have to have in order to click the arrow to get the shovel in the appropriate position. The hud hides a rather important portion of the screen when positioning the vehicle.

Therefor I would greatly appreciate if it was possible to have the possibility to assign keyboard shortcuts for each shovel position in order to get the shovel moved to that position (read the saved position and move the shovel to it). For setting a shovel position I don't see any need for a shortcut.

I don't think it is even necessary to have predefined shortcuts, just the possibility to set your own shortcuts.

**Comment by AndyK70** [comment]
I tried myself adding it, but I still get an error:
Error: Running LUA method 'update'.
D:/user_andyk/Dokumente/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/mode9.lua:358: attempt to get length of local 'movingTools' (a nil value)

somebody may have a look and tell me, what I am doing wrong?
[https://github.com/AndyK70/courseplay](https://github.com/AndyK70/courseplay)
and here the commit: [https://github.com/AndyK70/courseplay/commit/60571028d805822c3dd1bc16a9c6a9afb82ffa38](https://github.com/AndyK70/courseplay/commit/60571028d805822c3dd1bc16a9c6a9afb82ffa38)

**Comment by AndyK70** [comment]
yep, will work on it.
thank you very much.

**Comment by pops64** [comment]
When thomas gets a chance he will look at your pull request I will close this out has you have a pull request for this
