### ISSUE TITLE
Newly added - Option for turn Circle / Radius

### ISSUE THREAD

**Issue by JLConradie** [Courseplay/courseplay#2722]
@pvajko  

Hello

Its a question / suggestion.

Its a great addition to course-play that you have a choice of different headland corners to choose from.
Thank You.

My problem:
Currently its a guessing situation, what the default turning circle might be for the current vehicle/tools.
You have to go through various trial and errors to find the correct tuning circle.

**If you go to low** by the setting of the turning circle then it would result in Circling. Due to that, the vehicle just can't reach the way point and starts to circle or shoots into a direction and never stops. 
**If you go to high** then you might overshoot the field edge and into a river or tree.

If you somehow would know, what the turning circle might be of the vehicle and equipment/tools then you would know how many headlands you have to add.. for that vehicle and tool to do a turn successfully... The circling would certainly be less and I can leave my workers to do the job while I'm making some coffee.

I noticed that if you jump into a vehicle for the first time after game start, you would get a number in the field of the turning circle. So, somehow Course-play mathematically calculates the turning circle. 

But now.. Same vehicle different tools different turning circles. Mmm OOO..
If you can place a text field somewhere to display the turn circle of vehicle or tool or reset button, then you have something to work with. 
- Then you know how many headlands to choose
- Then you know the turning setting to choose so that the turn don't result in circling or overshoot the field.  

It would be nice to know.. Wouldn't it?

Have a nice ONE!

Regards Louis.

**Comment by JLConradie** [comment]
Yes..
That would be great.
Or change the colour. It turns red if the user change the turning circle too small or too big.. something.
If you can add this then the circling would be less. then you know you should add more headlands if you work with big or bigger tractors or tools and then the way points will be reachable. 
Or (The possibilities are endless..)
If the user change the tool then the choice of turning circle will change to default for that tool.
So what you see is the best choice according to the course generator and for the tractor/tool to be able to make the turns.
Thanks for the reply.

**Comment by AndyK70** [comment]
@JLConradie  The turning radius is not only specific to a vehicle but every tool can vary that turning circle.
Let's make an example. 
Hop into a Fendt Vario 900 and in the CP hud at page 'combine settings' you can see the known turn radius is 10m.
Now attach a tool, like the Horsch Maestro 12SW and look again, it changed to 24m (@pvajko : Wow, why so much? Even with this tool attached the real turn radius is not more than 12m).
And when you attach another tool it may differ again.

But it would be interesting to know in which way does CP gets that turn value. Are there some defined values CP reads out, or does CP calculate the turning radius on its own, by the values of the wheel base and possible angle of the vehicles front tires and optionally the maximum angle the tool can take to the vehicle?

**Comment by JLConradie** [comment]
@AndyK70 
Hi Andy..
Now that's my hole argument.
Frankly the user should not change the turning radius or circle. That's default to that vehicle or tool.
Now.. The course generator should calculate the course or turn on the end of the filed according to the default turning circle of the vehicle/tractor or tool and not the other way around. 

The Big Bud.. Needs a big circle and surely you can't expect it to turn in 7m

Currently I'm guessing and that's why it is so difficult to get the correct turning radius or circle for the tractor to make the turn properly.
  
On the end - Wrong turning circle leads to circling and run-a-way tractors. LOL 
But not all the mods and their settings in XML file are correct. that's why you get unreal values in course-play.  Then the trouble starts.
Conclusion - If course-play can give you an idea of what the circle should be.. Then you the user has something to work with on course generation. How lovely it would be if there are no Circling.

**Comment by JLConradie** [comment]
Maybe I should add that the distance between way points at turns should not be less than the length of the tractor. If it is, then the tractor should use every second way-point, or so.
Thanks for the reply.

**Comment by pvajko** [comment]
@AndyK70 I'm not sure how exactly the turn radius is calculated, I'm the course generator guy, I only added the headland turns, wish I had the time to look more into the other turn calculations.

@JLConradie "distance between way points at turns should not be less than the length of the tractor" don't get this, it **is** way below the tractor length, sometimes 0.25 cm, otherwise we could not follow an arc due to the way we drive the tractor (setting the drive direction to the next waypoint). 

As to circling, it is an entirely different problem and should be addressed in a generic way while driving, to check if we can reach the next waypoint **in the correct direction**. The course generator does this offline when the 'Round' mode is selected, but this should be calculated online.

Also, there's some protection/fallback for circling which we should improve as sometimes it does not get triggered.

**Comment by pops64** [comment]
I know 90% of the time the auto generate turn circle is the right one. 9% of the time is a forced value because it doesn't calculate correctly. the last 1% are just mods that don't calculate correctly and no one has added a forced value. The reason there is an option to change it because the TR given by CP or forced tends to be on the higher side. Has the only problem with a large turning radius is running into stuff. The problem with smalls is not being able to make the turn and you lead to circling behavior. Has to where we get the turning radius is based off nodes that the mod provides if theses are in the incorrect position leads to bad values. Also on the larger tools what isn't taken into account is the width of the tool which is why most of the larger tools have a force value. It could turn the calculated value but it physical can't with out hitting the tool

**Comment by pops64** [comment]
Yea I also forget to include that it use the max rotation angle of the joint between the tool and the tractor. So for larger tools the rotation angle is not right when width is taken into account for 180 turns

**Comment by JLConradie** [comment]
@pops64 
Yes.. I gathered that one.
What I have done..
Ever since I changed the settings below the turning circle became smaller so that the tractor or combine can reach course-play way-points at turns. Ever since I have done this I have basically no Circling or runaway vehicles.  You have to play with these settings to make it right. Its not that you take away the realism of the vehicle instead you make it more realistic. Tractors has turning brakes. Right and Left. That's why there are two pedals at your feet.
But I think you know this. Its for people/users that don't know and what they can do to change turning circles of vehicles..   
What I have done is as follows.. or what you can do...
MOD xml File
<ackermannSteering rotSpeed="80" **rotMax="42"** rotCenterWheel1="2" rotCenterWheel2="3" />

Change rotMax to say 52 or even 62
So it will look like this (The bigger the value the smaller the circle)
<ackermannSteering rotSpeed="80" **rotMax="62**" rotCenterWheel1="2" rotCenterWheel2="3" />

You can even go as far as change the attacher Joint lowerRotLimit Y position.
But be careful not too much otherwise it will touch the wheels.

<attacherJoint index="0>5|1|0" jointType="trailerLow" lowerRotLimit="10 50 50" upperRotationOffset="0" allowsJointLimitMovement="false" canTurnOnImplement="false" comboTime="1" >

Change  lowerRotLimit="10 50 50" to  lowerRotLimit="10 60 50"
So it will look like this..
<attacherJoint index="0>5|1|0" jointType="trailerLow" lowerRotLimit="10 60 50" upperRotationOffset="0" allowsJointLimitMovement="false" canTurnOnImplement="false" comboTime="1" >

Regards.

**Comment by JLConradie** [comment]
Sorry It cut my TEXT..

Change  lowerRotLimit="10 50 50" to  lowerRotLimit="10 60 50"
So it will look like this.
<attacherJoint index="0>5|1|0" jointType="trailerLow" lowerRotLimit="10 60 50" upperRotationOffset="0" allowsJointLimitMovement="false" canTurnOnImplement="false" comboTime="1" >

**Comment by pops64** [comment]
I know it is on my to-do list has we do calculate the total distance need on the field to make circle turn. If with the smaller tools if you have enough headlands it will ingore the turn on field setting. This is were that calc is used at. So it should be pretty easy to had a simple button for that

**Comment by JLConradie** [comment]
@pops64 

Thank You.. That would be very much appreciated.
Looking forward..
Course Play is getting better and better.
Regards.

**Comment by pops64** [comment]
Closed #2909
