### ISSUE TITLE
Workers still being paid after job ends.

### ISSUE THREAD

**Issue by jenxy** [Courseplay/courseplay#2723]
Version 5.02.00090 dev.
When the job has ended, the worker is still getting paid. Happens with tractor, combine and job type (plow, fertilize, seed etc).
This has been reported before https://github.com/Courseplay/courseplay/issues/2647 but problem still exists.

**Comment by ThomasGaertner** [comment]
do you mean the situation, when the message, has finished work is shown or in general even after releasing the courseplayer ?

**Comment by jenxy** [comment]
The message is 'has finished work', white text on green background. So I have to go and manually 'stop driver' and then the payments stop.

**Comment by jenxy** [comment]
Fair enough.
