### ISSUE TITLE
tractor doesn't drive backwards correctly with shifted tools

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#2724]
CP: 5.02.00090
With the Lemken Titan 11 going backwards when it is expanded you can't go in a straight line as the plow is shifted to the side and will go in a curve which messes up the drive backwards.

I was on Goldcrest Valley, Field 5, with a Fendt Vario 900 and the Titan 11. I was using the new GUI for calculating a course with 2 rows of headland counterwise with sharp turns and beginning on the field rows.
The tractor couldn't drive backwards correctly and entangled itself with the plow and even after stopping the worker I couldn't get the plow straight again. I had to detach the plow and then drive around to get to the attacher and reattach it again.

My suggestion to overcome this situation is, instead calculating a complete new way of driving backwards with shifted tools retract it (Key_x), then drive backwards and expand it again (Key_x) before going forwards again.

**Comment by pops64** [comment]
It probably was an oversight not including the check to see if the tool could be reversed. Has I'm 99 % sure this tool is flagged for that

**Comment by pops64** [comment]
Closed #2909
