### ISSUE TITLE
Silo Speed

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#2732]
Hello! There was the possibility to adjust the speed when driving through the silo! If you could do that again with some harvesters it would be very handy that they are either too fast or too slow! 
Lg

**Comment by pops64** [comment]
Havesters technical can't unload into a silo. If I remember correctly. And using two unload points the speed is not adjustable. Using one it will stop where that point is and unload.

**Comment by Paul2510** [comment]
I'm sorry I meant the silage silo!  If you could adjust the speed in the silo!

**Comment by pops64** [comment]
That speed is set automatically to allow it to unload completely in the distance of the silo if driving through it. If reversing into it this would be the reverse speed setting

**Comment by Paul2510** [comment]
Ok! With some trailers the problem is that the trailer is already half empty!  e.g. FBMKirchner silo trailer! That's why the questions!

**Comment by pops64** [comment]
It adjusts it for how much is in the trailer, how quickly it unloads, and the length of the silo. If it isn't working for your mod then it doesn't have the correct unload time variable or it is picking up a incorrect length but that would show across all trailers

**Comment by Paul2510** [comment]
The FS17_Poettinger_JumboCombilineSeries is no problem! Maybe man could re-activate the function! Lg
