### ISSUE TITLE
Sp400F

### ISSUE THREAD

**Issue by Evilmutt** [Courseplay/courseplay#2735]
Hi Guys, I have noticed 2 different issuse so will do 2 Requests. sadly I have no images as I just remembered now to do the requests. Anyway, this one deals with the New Holland SP.400F. When you have turn on feild Activated it starts to reverse and then starts swinging from right to left. once again Sorry but no pictures as I am not using it right at this minute. and on some rather severe cases of it reversing it can get stuck in the Circle Loop of just going round and round in reverse. I will Attempt to get pictures of it (or if I can work out how to do some recordings in game I will record it and then let you see. once again SOrry about the lack of Pictures.

**Comment by pops64** [comment]
Make sure your game is updated to the latest release for both issues.

**Comment by Evilmutt** [comment]
Pops I am currently running 092 I think. and it was the latest At the time of doing the Bug reports

**Comment by pops64** [comment]
Yea this documented some where else closing it for now
