### ISSUE TITLE
Signs of CP

### ISSUE THREAD

**Issue by saku05** [Courseplay/courseplay#2738]
Hello everyone

Suggestion: The panels doubled at 90 ° (see photos)

Visible 360 °

![photos 1](https://user-images.githubusercontent.com/4406385/40854744-ac280fea-65d2-11e8-9557-19d87a56767b.jpg)
![photos 2](https://user-images.githubusercontent.com/4406385/40854754-afaf8e4a-65d2-11e8-9478-4990f933caf9.jpg)
![photos 3](https://user-images.githubusercontent.com/4406385/40854760-b27e21a4-65d2-11e8-902f-57ee7567654a.jpg)

Thank You for your work

Greetings
Sam

**Comment by pops64** [comment]
Closed for now will revisit in the future has this is a major bug or glitch that causes CP to crash
