### ISSUE TITLE
Trigger von der stappenbach

### ISSUE THREAD

**Issue by Derbayernbauer** [Courseplay/courseplay#2739]
Hallo,

Ich hab ein problem und zwar wollte ich mir einen kurs einfahren für den milchverkauf.

jetzt ist mein problem :

Kurs eingefahren:

Milchtrigger am stall -pause gesetzt

weiter gefahren bis zum verkaufspunkt-da am trigger auch pause gesetzt

Zurück bis zum stall kurz vor dem kurs start ,den kurs bendet.

dann umgestellt auf flüssigkeitsmodus....

Jetzt fährt er mir den kurs leer ab in dauerschleife?

Kann ich da was an den Trigger machen?

**Comment by pops64** [comment]
#2231 3rd one on the list
