### ISSUE TITLE
Option to set courseplay to never reverse

### ISSUE THREAD

**Issue by hhinde** [Courseplay/courseplay#2742]
When you use seeders with tow-behind seed carts or any articulated tractor, courseplay is terrible at reversing. I believe that it should either detect the use of such an implement, or allow us to disable reversing all together.

**Comment by pops64** [comment]
Leave turn on field off and you won't this issue. All the standard tools CP knows if there is an issuse reversing and will avoid reversing turns that are 180
 If it is a mod let us know and we can fix it or give you directions on how to do it
