### ISSUE TITLE
Tractor stuck in circle in Combi mode

### ISSUE THREAD

**Issue by Thrall7734** [Courseplay/courseplay#2743]
Hi,

if i tell a tractor to unload a combine in combi mode, almost all of the time, the tractor gets stuck in driving a circle between waypoint 2 and 3 when trying to go unload the trailer.

It seems the waypoints are to close together to make the turn and he tries to reach waypoint 3 for infinity. 

Am i doing something wrong?

**Comment by AndyK70** [comment]
Turn down the speed on field.
If the vehicle is to fast when reaching the second point shooting past cp will not be able to get to 3rd waypoint and circle...

**Comment by pops64** [comment]
Also turning on algin with first waypoint will fix this. If I find the time I will improve the compability between using this and not. Closing this out has it is mentioned elsewhere. Will link later
