### ISSUE TITLE
Suggestion for tractors with multiple steering modes

### ISSUE THREAD

**Issue by Phalanx380** [Courseplay/courseplay#2748]
I have suggestion for tractors with multiple steering modes in the speed limits tab it would be nice to set what steering mode for field and street as with tractors like the [ http://www.fsmods17.com/jcb-fastrac-4000er-series-v1-0-0-fs17/ ] going at high speeds in All wheel steering mode even slight turns can tip or make the tractor slide out this is made even worse with trailers full of grain and it would be nice to set it to Front wheel steering for high speeds on the streets and All wheel steering in field for slow tight turns.

**Comment by pops64** [comment]
We're really busy ATM with RL and such we will add to the list to discuss at a later time

**Comment by pops64** [comment]
Closed for now will revisit in the future
