### ISSUE TITLE
trailed forage harvesters do not work with courseplay

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/courseplay#2750]
Hello,

Do you know why trailed forage harvesters do not work with courseplay?

- lely storm 300 (https://www.farming-simulator.com/mod.php?lang=en&country=en&mod_id=93504&title=fs2017)
- pottinger MEX 6 (http://www.fsmods17.com/poettinger-mex-6-v-1-0-fs-17/)
- John deere 3765 (http://www.fsmods17.com/john-deere-3765-forage-harvester-v1-2-fs17/)
- Lacotec (http://www.fsmods17.com/lacotec-fs17/)

Is it not possible to make it work like the pottinger MEX 5?
Thank you in advance,
Kings Regards,

Crinouche

**Comment by NexX0** [comment]
Hey, 
have a look in here #2462 i had the same problem, now it's working for me.

**Comment by pops64** [comment]
@NexX0 thanks for finding that. That issuse would be the fix for this
