### ISSUE TITLE
Suggestion: tramlines during sowing

### ISSUE THREAD

**Issue by LMCZE** [Courseplay/courseplay#2751]
Hello,

I would like to ask if it would be possible to add tramlines feature into CP in future. Now I do tramlines with the ProSeed mod it would be nice to have also this feature build in CP. It would be nice o have a possibility to chose the width of the tramlines depending on the width of sprayer or fertilizer machine. Thanks for your consideration.

**Comment by pops64** [comment]
Currently we are way to busy and I doubt we will ever implement this has a separate mod covers this fuctionality
