### ISSUE TITLE
courseplay does not lower fwd implement

### ISSUE THREAD

**Issue by Friendlyx** [Courseplay/courseplay#2755]
courseplay does not lower frontpacker with the back-seed-drill. Is their a way to let courseplay check what kind of implement is at the front?

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Friendlyx** [comment]
its this mod https://farming-simulator.com/mod.php?lang=de&country=de&mod_id=58306&title=fs2017 on the FBM JD6R with the latest dev version of courseplay

**Comment by pops64** [comment]
Mode 4 isn't designed to work with that tool so it ignores it. This is something we probably won't fix
