### ISSUE TITLE
strange cp notification in mode 1

### ISSUE THREAD

**Issue by evybart** [Courseplay/courseplay#2756]
I make course for mode 1 the first route do he perfect but when the tractor comes for the second time too the loadplace he says silo is empty wait for more bud there is no silo its a route just for a bunkersilo unloading with the wheelloader i do this all the time and works perfect just a view days he begon this error have the latest dev version off cp 
![cp fault](https://user-images.githubusercontent.com/10274098/41501294-1387e6bc-71a2-11e8-9339-59e2c1f13c2e.PNG)

**Comment by pops64** [comment]
Do you drive under or near a silo fill trigher on your course

**Comment by evybart** [comment]
no he drives from the bga silobunker (foto) to a silo storage elders on the map bud commes not in the near of a fill trigger in these course the first trip do he perfect and when he must load for the second time he stops and gives the message thanks al ready for the help grtz

**Comment by pops64** [comment]
I still think your coming across a silo fill trigger of some kind that can dispense the fruit currently selected and it happens to be zero at the silo. So if your not already selecting the fruit you are filling with I would try that. Has I belive it is the same cause just different result as #2051

**Comment by evybart** [comment]
yes indead the unloading triggen and the fill trigger is on the same place thanks for the tip this can be closed grtz

**Comment by pops64** [comment]
Yea I'll looking at fixing this and few other things closed for now as is duplicated
