### ISSUE TITLE
Suggestion: BGA silo shovel work

### ISSUE THREAD

**Issue by TheRealRolandDeschain** [Courseplay/courseplay#2757]
Hi, 
I have the following (hopefully easy) suggestion for emptying silos with the shovel mode:
On the map I play, if you press F5, you can see, that the actual Silo-Area (the orange wireframe) extends into the silo walls left and right. Because of this, the wheel loader constantly driving against the wall, even though the mode works as designed. 
Would it be possible to implement an option to setoffsets to the area borders? 

cheers!

**Comment by pops64** [comment]
If you adjust the workwidth of the tool you can avoid this. Has I think mode 9 look at silo triggers differently than the other modes

**Comment by TheRealRolandDeschain** [comment]
OK, gonna test around a bit. Also, the modder for the map told me, he plans to fix the issue...

**Comment by pops64** [comment]
inacitivity
