### ISSUE TITLE
missalignment of text on panel

### ISSUE THREAD

**Issue by Friendlyx** [Courseplay/courseplay#2758]
hi, I realized this missalignment in transit mode
![unbenannt100](https://user-images.githubusercontent.com/6493968/41552004-d2a53b12-732d-11e8-85c4-56fc4eb38b0d.jpg)

**Comment by pops64** [comment]
Not a misalignment the text on the left is to long

**Comment by Friendlyx** [comment]
ok so text is too long, it is German language
