### ISSUE TITLE
Plow not merging fields

### ISSUE THREAD

**Issue by Jackknife90** [Courseplay/courseplay#2761]
I made a field edge path manually, to plow in between fields, when i click drive now with a plow (vanilla) the driver just folds up the plow and stops, im on the fieldwork mode as usual for plowing but cant seem to make him start plowing

im using the Amazone Cayron 200 plow.

Thank you

P.s sorry if this has been solved i did a search but couldnt find anything

**Comment by pops64** [comment]
One why are you clicking drive now? Do you mean the button to start cp or did you already start cp then you hit drive now? Has theses are two very different things. https://youtu.be/2QbNAoNXEQ4

**Comment by Jackknife90** [comment]
sorry i got confused about what it was called, i meant the button to start CP

**Comment by pops64** [comment]
Give is a picture with CP HUD open after you start

**Comment by pops64** [comment]
Inactivity
