### ISSUE TITLE
tractor slowly creeps forward as tipping occurs

### ISSUE THREAD

**Issue by clif9710** [Courseplay/courseplay#2762]
I am using FS17 1.5.3.1 with CP 5.01.00125. I have set up a course to take grain to the silo. At the silo when the tipping point is reached, the tractor will stop and the tip will begin but the tractor will then start slowly moving forward resulting in part of the load being dumped beyond the grate. I put in a pause along with the tip point but that made no difference.

**Comment by pvajko** [comment]
Please try with the current version and report back if it still has this issue.
