### ISSUE TITLE
Recording a course and disconnecting from the server; Frontloader does not move

### ISSUE THREAD

**Issue by KITT3000** [Courseplay/courseplay#2763]
1. During recording the course disconnected me from the server (I am a client, buddy host) and there were such errors about this in LOG.
2. After recording a course with frontloader support, after setting the position of the shovel it changes the position correctly, but the frontloader does not move (problem only on the client side).

LOG: https://gist.github.com/KITT3000/cbd961964a736e013f5daafa38eaa63b

**Comment by pops64** [comment]
Closed #2909
