### ISSUE TITLE
tractor slowly creeps forward as tipping occurs (re-opened for latest version of CP)

### ISSUE THREAD

**Issue by clif9710** [Courseplay/courseplay#2765]
As requested, I downloaded and installed CP 5.02.00016 and the problem remains as described below. I built the tipping route from scratch with this version of CP.

I am using FS17 1.5.3.1 with CP 5.01.00125. I have set up a course to take grain to the silo. At the silo when the tipping point is reached, the tractor will stop and the tip will begin but the tractor will then start slowly moving forward resulting in part of the load being dumped beyond the grate. I put in a pause along with the tip point but that made no difference.

**Comment by pops64** [comment]
No additional points are needed CP auto recognizes where unload triggers are so remove both the tip and wait points and all will be fine. The tip point is only for unloading to heaps on the fields or ground
