### ISSUE TITLE
Reversing 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#2766]
i'm having trouble reversing ive detacted the trailer go on route then reverse but as tractor reverse it bends and starts slipping what am i doing wrong or is it a bug ?

**Comment by matty2123** [comment]
![fsscreen_2018_06_22_21_21_27](https://user-images.githubusercontent.com/27097241/41797631-b63498f0-7662-11e8-901e-60eeeb874f75.png)

**Comment by AndyK70** [comment]
When recording in reverse keep it straight until you traveled at least the combined length of tractor and trailer only then start turning. 

Keep in mind when you record the course your position (in the tractor) is recorded for the waypoints but when CP drives the trailer in revers it aligns the trailer to the waypoints. Therefor have to be enough waypoints from the starting position of reversing to the entrance of the turn to cover the tractor and the trailer. And even better if there are some more for CP to start the alignment before going into the turn.

**Comment by matty2123** [comment]
Yeah I’ve done that but when it starts reversing it jackknifes instead of going straight back

**Comment by pops64** [comment]
Modded trailer? Please post log with reverse debug channel on. I think it is 21 but I can't look it up atm

**Comment by matty2123** [comment]
I’ve done a little experiment and I used another trailer it’s the baileys tb20 silage trailer causing the problem

**Comment by pops64** [comment]
Yea this is something we probably can't fix. mod author has to make it cp compatible

**Comment by matty2123** [comment]
Ok least I found the problem another quick question so i don’t have to open another thread is there an option for 4wd on v5.03.0002 I don’t have drive control on so I can’t select it.

**Comment by pops64** [comment]
You have to have drive control for 4wd. Has this mod adds that feature to the game
