### ISSUE TITLE
Multiplayer - Nothing happens when clicking drive course.

### ISSUE THREAD

**Issue by 74656b** [Courseplay/courseplay#2768]
Generated a standard field work course, 1 headland, Clicked drive course and nothing happened, tractor seemed locked out, but wasn't moving.  Was able to regain control by hitting the hire/dismiss worker.

Version: v5.03.00002

https://gist.github.com/74656b/fc42699c1246509b5085a3e6e1dba9c1

**Comment by elpatron68** [comment]
I can confirm this behaviour. v5.03.00005

**Comment by pops64** [comment]
Try disabling all mods but CP has there are no errors in the log that would cause this

**Comment by elpatron68** [comment]
I tested this now again on my dedicated server with Courseplay v5.03.00005 as only mod enabled on Goldcrest Valley. Empty fresh savegame.

Debug log of all channels:
[2768.log](https://github.com/Courseplay/courseplay/files/2164051/2768.log)

**Comment by pops64** [comment]
This will have to wait for thomas to look into this. Has I haven't really manged to figure out how multiplayer works. Beyond doing basic debug steps I can't help.

**Comment by k4r3l01** [comment]
So problem happens only when i generate field work via advanced course generator when i create course via standart hud its working correctly

**Comment by elpatron68** [comment]
For me, this problem is solved. Tested today with 5.03.00016.

**Comment by k4r3l01** [comment]
dont create field work via advanced course generator andy everything works fine

**Comment by pops64** [comment]
Closed #2909
