### ISSUE TITLE
Properly setting up a vehicle for CP.

### ISSUE THREAD

**Issue by cpoole2005** [Courseplay/courseplay#2769]
I am having difficulties with a pack of mods I found where 2 of 3 are not tracking where they should when being overloaded from a combine they are to close to the combine and try to drive on the header. I truly believe it is due where the (for lack of better terms) CP trigger is located in the vehicle. I would like to fix this but only have limited map editing skills any help would be appreciated.

I have attached some pictures trying to show where the trigger is when you click start recording.
![fsscreen_2018_06_24_11_53_34](https://user-images.githubusercontent.com/5596638/41820872-1af9c8da-77c8-11e8-9df6-6315533c7ca5.png)
![fsscreen_2018_06_24_11_53_12](https://user-images.githubusercontent.com/5596638/41820873-1b10d976-77c8-11e8-8fbe-127efc79b516.png)
![fsscreen_2018_06_24_11_52_49](https://user-images.githubusercontent.com/5596638/41820874-1b32df4e-77c8-11e8-8dff-d7f99514b030.png)
![fsscreen_2018_06_24_11_52_48](https://user-images.githubusercontent.com/5596638/41820875-1b45b09c-77c8-11e8-8433-e437fa4deee9.png)
![fsscreen_2018_06_24_11_52_46](https://user-images.githubusercontent.com/5596638/41820876-1b5ef98a-77c8-11e8-9951-554b3fc0608d.png)

**Comment by pops64** [comment]
This can be fixed with the horizontal offset found under drive sittings after recording. Assuming it works it looks like the root node is not centered which is where almost all of CP code assumes it to be. Which means this probably won't be the only issue. This is somthing the mod author has to fix
