### ISSUE TITLE
Harvester not emptying into tipper

### ISSUE THREAD

**Issue by Sinomen** [Courseplay/courseplay#2770]
Issue with 5.03.00002, stock equipment:

A harvester and a tipper are set up as usual, tipper is ordered to unload harvester and empty itself to a farm silo. Works fine as usual.

When I start a mission though, the tipper goes to the correct overload position below the harvester's pipe, the unload animation starts, but the harvester does not unload at all. As soon as the mission ends, everything works again as normal. Switching (TAB) between vehicles does't change anything.

**Comment by pops64** [comment]
This has been discussed multiple times in the past. CP does not support being used during field missions. And all such bugs won't be fixed.
