### ISSUE TITLE
FarmSilo does not have the selected fruit

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#2771]
Hi! I have the problem that the driver in the deride mode on the field always writes that the FarmSilo does not have the selected Fruittype, although there is no trigger! 
What can I do?? (Mod1)
![picture](https://user-images.githubusercontent.com/10115244/41889694-2f93c4f4-790c-11e8-8c06-c59c6d3e4d95.jpg)

**Comment by AndyK70** [comment]
On the course it drives, it there anywhere a fill trigger it drives over?
You should avoid driving over fill triggers If you want to use drive mode 1 for filling at the edge of a field.

**Comment by pops64** [comment]
#2756
