### ISSUE TITLE
Multyplayer can't joint server

### ISSUE THREAD

**Issue by Ruudjhuu** [Courseplay/courseplay#2775]
Hi,

When my friend runs a server local, and i want to joint. It takes forever to load and eventualy it will fail. If i run the server it's the same storry. When coursplay is disabled, It works like a charm and it takes about 5 seconds to load. 

used version: 5.03.00002
log file: https://gist.github.com/Ruudjhuu/31b5d3b1a9b9fca7a2fde36ef5f6a160

**Comment by pops64** [comment]
Try disabling all mods but CP and try again

**Comment by pseikoNL** [comment]
Why do you have 2 versions of courseplay in it?
Try to disable one of them.

**Comment by Ruudjhuu** [comment]
Thanks for the fast responses, I didn't see this. I'll close the issue and try again.. When it's not working i'll reopen this.  Need to wait when my friend and i have some time to try.
