### ISSUE TITLE
Problem: Running Lua Method

### ISSUE THREAD

**Issue by NewBalance41** [Courseplay/courseplay#2779]
Hey Guys, i need your Help. My game crashes after becoming thousands of error files like these:
C:/Users/Admin/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/mode3.lua:7: attempt to compare number with nil
Error: Running LUA method 'update'.
Sometimes after 5 Minutes, sometimes after one Hour. I have the latest FS17 Update on my Computer and trie´d everything to Fix it. Anybody who can help me? :)

**Comment by pops64** [comment]
Full log file, has I believe your still running an outdated version has this error was corrected pre 5.2
