### ISSUE TITLE
Reverse turning in fieldwork mode

### ISSUE THREAD

**Issue by coldlandlord** [Courseplay/courseplay#2780]
When ploughing the tractor used to reverse turn at the end of the row into the next row whilst flipping the plough over. I reinstalled courseplay the other day when I noticed that pathfinding (drive around crops) function was not working. Since then I have started ploughing again and found that the tractor wont reverse turn any more, Instead it drives out of the row, goes across 4 - headland rows, turns and backs up into the hedge where it gets stuck on a tree.

**Comment by Karlshoj** [comment]
Same for me

**Comment by pops64** [comment]
Need alot more information with pictures or video. With all course waypoints on, also how are you setting up your fieldwork, course gen settings.

**Comment by pvajko** [comment]
Also, turn on debug channel 14 please.

**Comment by coldlandlord** [comment]
Sorry guys It's the old version on modhub. Downloaded Dev version and all is well again.
