### ISSUE TITLE
combined mode does not work in multiplayer.

### ISSUE THREAD

**Issue by kferrano** [Courseplay/courseplay#2781]
I have quite normal, as in the single player, created a course and assigned a combine, just like you leave normal. I have in multiplayer exactly the same mods and synonymous the same combine, etc. but in multiplayer, the tractor does not recognize the combine, but it works in single player.

Sorry for the bad English, I'm actually German

**Comment by pops64** [comment]
Log with debug channel 5

**Comment by brodzowski** [comment]
I just wanted to pop in an update that for whatever reason, after restarting the multiplayer server everything has been working perfectly, so I'm not sure why it didn't "take" after the first time. I just about jumped outta my chair when I came back in and off he went to unload the combine! Thanks for a great mod! (wish the obstacle avoidance was a little better, but amazing work!)
