### ISSUE TITLE
Mode 3 not compatiable with more than 1 wagon

### ISSUE THREAD

**Issue by MoslessNeo** [Courseplay/courseplay#2782]
Suggestion
In overloader mode, you can use two wagons MASSEY FERGUSON MF 3012?
It would be very complicated to adapt the code so that when it is unloaded in the truck the two wagons are recognized. When harvesting, the harvester recognizes the two, but when they begin the route to unload in the truck, only one of them is recognized. The other remained loaded.
Truck (TX 415 BARRELCORE + SUGARCANE SEMI-TRAILER + SUGARCANE HARVESTING)
With just one wagon, everything works perfectly. Thank you very much.

**Comment by pops64** [comment]
Yea this already on our to do list to fully support plantium expansion. It is a little harder to do then you would think cause of the outdated way mode 3 is coded. Closing this for now

**Comment by pops64** [comment]
Nope. We will close this out when we do

**Comment by pops64** [comment]
Alright to give an update on this topic. I have something working it has a few flaws in that will hold me up on pushing this to the master. This [branch](https://github.com/Courseplay/courseplay/tree/Multiple-Trailers-Mode3) is stable there may be weired behavior(flaws) but if your willing to risk it then have it. Currently the flaws are it dumps on the ground if the trailer leaves and is operated by a person. This can't be prevented limits of the game :(. If CP is running the trailer ensure that you don't have CP waiting until the trailer is more than 95% full has I set up mode3 to prevent filling a trailer more 95% full.  The only flaw keeping me from pushing this is that mode3 fills the first trailer it finds. So make sure mode 1 is driving in the opposite direction. If you don't do this then mode3 will only fill the back trailer if using more than 1 trailer in mode1 causing weired behavior(Most likely mode1 will never drive to unload) This is something I will be fixing. 

For those that are willing to try this out please post any issues you find here so I can get the fixed before I push to master as mode3 has brand new logic and I just want to make sure there are no loop holes. Thanks and have fun :D

**Comment by pops64** [comment]
Alright update. The tractor will now stop the trailer it is going to unloaded directly under the 1st wait point, if there is a trailer with in 2.3m it will unload into that trailer. This problay will be the final version that will be pushed to master. There are other sugarcane issues not related to this that I would like to fix before merging this

**Comment by Hrala** [comment]
Where can I download to test? Thank you

**Comment by pops64** [comment]
I am making some final tweaks and we be pushing this to master. https://github.com/Courseplay/courseplay/tree/Multiple-Trailers-Mode3

**Comment by pops64** [comment]
Alright try with version 38 or higher and report back

**Comment by pops64** [comment]
Post a log with channel 15 active

**Comment by Hrala** [comment]
here the LOG
https://i.imgur.com/pMtMyr7.jpg
https://i.imgur.com/JzINLhV.jpg

**Comment by pops64** [comment]
Try again with version 39 or higher

**Comment by Hrala** [comment]
the problem continues, I did a test and it seems that when the overloader arrives at the waiting point before the truck he does not unload any wagon, he only unloads when he arrives at the waiting point and the truck is already there

https://i.imgur.com/3qpXK38.jpg
https://i.imgur.com/k5s6CCc.jpg

**Comment by pops64** [comment]
I need the full log. Cause from what I gathered on your first set of pictures it was saying that the trailer was full. post it to gist or pastbin or upload the file directly here thanks

**Comment by Hrala** [comment]
How can I send you the complete log?

**Comment by pops64** [comment]
Try with version 40 or higher and report back https://github.com/Courseplay/courseplay/wiki

**Comment by pops64** [comment]
Ensure channel 15 is on when recording the video

**Comment by Hrala** [comment]
I went to record the video with version 40, and now it goes up to unload the first wagon and does not go down

https://i.imgur.com/bFsy5PV.jpg

**Comment by Hrala** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/2504221/log.txt)

here is my log

**Comment by pops64** [comment]
Try with version 42 or higher. The not going down was a change not related to this and forgot to change something with it

**Comment by Hrala** [comment]
version 42, now the problem has been solved !!
https://i.imgur.com/XULwyjY.jpg

a question, is it possible to change the speed with which it rises to unload and descend? if possible, slow down a bit because it is going up and down very fast

**Comment by pops64** [comment]
We can't do anything about that. We just tell GE where we want the bucket and then it moves it there

**Comment by pops64** [comment]
I don't know enough about the part of CP to mess around with that. Just as long has it is stable I am not going to change it

**Comment by pops64** [comment]
I am going to close this out for now. Please post here if any other issues related to this
