### ISSUE TITLE
mod isn't working.

### ISSUE THREAD

**Issue by Matej123456** [Courseplay/courseplay#2794]
I installed a mod and it didn't work. Help me pls.

**Comment by kferrano** [comment]
Which version did you take?
From the website (Developer Version) or from ModHub?

**Comment by pops64** [comment]
http://courseplay.github.io/courseplay/en/installation/index.html there are also plenty od yputibe viedos put there on thos subject. https://github.com/Courseplay/courseplay/wiki please follow when posting any future issues
