### ISSUE TITLE
Tractor stopping out of the field in combi mode

### ISSUE THREAD

**Issue by snoopdoggtg** [Courseplay/courseplay#2797]
This is where a tractor with 4 tippers stops after unloading a combine in the combi mode. It doesn't matter if I have the automatic or manual search, it always stops like that. I also tested the same course on this field with a tractor and 2 tippers and everything worked fine, the tractor stopped in the field after each combine unload.
![clipboard02](https://user-images.githubusercontent.com/41340882/42831846-b9705d38-89ef-11e8-8048-ab1dcf1a1892.jpg)

**Comment by pops64** [comment]
I pretty sure mode isnt set up to handle paeking that many tippers. 2 you don't really notice bit with that many ... Problay will be a wont fix unless it is an easy change. Closed for now
