### ISSUE TITLE
Shovel Mode

### ISSUE THREAD

**Issue by rozhen450** [Courseplay/courseplay#2798]
I created a shovel course, and it worked for a few trailer loads. Suddenly the tractor decided to just sit and idle, then shut off. Anytime I start this course now, the tractor fills up the shovel and stops at same spot waiting.

**Comment by pops64** [comment]
When you set the shovel postions did you go to the extermes of movment? Where does it stop exactly has there 3 waiting points. Do you have trlr waiting to take product?

**Comment by rozhen450** [comment]
![cpissue1](https://user-images.githubusercontent.com/41344701/42846555-4496a0c4-89e7-11e8-9929-97bc806fefcc.png)


Shovel movements are not maximum postions exact shovel empty manueve

**Comment by pops64** [comment]
http://courseplay.github.io/courseplay/en/manual/index.html#driveMode9 please set you course as described in the manual has I m surrpised it is even worked to begin with. Also your course is to tight, mode 9 does not work well when the course is overlapping like you have

**Comment by pops64** [comment]
Inactivity
