### ISSUE TITLE
sugarcane overloader trailer

### ISSUE THREAD

**Issue by Hrala** [Courseplay/courseplay#2799]
[https://imgur.com/NK4d9Ky](url)
[https://imgur.com/a/j0wweXR](url)

Why do not you unload the second trailer for sugar cane? he unloads the first and the second passes straight from the waiting point, is there any way to unload the two?

Sorry for my english, google translator

**Comment by pops64** [comment]
No not atm, something on our todo list. Please check existing open topics for duplicates before posting thanks. #2782
