### ISSUE TITLE
Problems turning over with A8800 Multi-Row

### ISSUE THREAD

**Issue by kferrano** [Courseplay/courseplay#2800]
In the photo I am sitting in the tractor and he waits until the combine harvester turns.

[Photo](https://steamuserimages-a.akamaihd.net/ugc/930441531076385902/3F07C3645723BCCBCB74DE80CC79BD8A5843A721/)
In the photo I am sitting in the tractor (1) and he waits until the combine harvester turns (2). At the same time, however, the Mäghdrescher can not turn, because when he reverses to get back on his course on the tractor gets stuck and thus his tires / chains spin (3).

If desired, I can also take this in a video to better illustrate this  (Multiplayer)

**Comment by pops64** [comment]
If your running multilayer I know there is some kinda of issue with it detecting the harvester but I would need a log with debug channel 5 to know what is wrong
