### ISSUE TITLE
Mode 1 Vehicle stopping at the End point to load instead of start point

### ISSUE THREAD

**Issue by Elmruik** [Courseplay/courseplay#2801]
Im using the most recent build available through the games mod section but for some reason this bug keeps coming back where im using a vanilla tractor and vanilla tipper to transport grain from a auger wagon next to my field to my silo. Every now and then it will bug out sometimes after mayber 4 or five trips sometimes after just the first trip. the only way for my to fix it is to save and reload the game reseting the tractor and trailer havent fixed the  issue.

**Comment by pops64** [comment]
Do you have run counter set? It could also be detecting the silo first. 99% of the time if CP stops it will give a reason. Especially if it is stopping at the last waypoint and not the first

**Comment by pops64** [comment]
Are you runnong the release version 5.03 or the dev version 5.03.10?

**Comment by Elmruik** [comment]
5.3.0 is the version im currently using

**Comment by pops64** [comment]
Please use the dev version from here on out if you want this bug to be fix. has I didn't get this fixed before the release of version 5.3, I think I fixed it in 5.3.04 or 6 don't remeber

**Comment by Elmruik** [comment]
how do i download the dev version?

**Comment by pops64** [comment]
https://courseplay.github.io/courseplay/en/installation/index.html

**Comment by Elmruik** [comment]
thank you this seems to have completely fixed the issue.
