### ISSUE TITLE
Issues regarding Potato Harvester

### ISSUE THREAD

**Issue by Evilmutt** [Courseplay/courseplay#2802]
Hi Pops. Now I have some images and a video for you to peruse with regards to the Potato Harvester and it's Issues. firstly I farm doing turn Headlands so the tractors pull up on the right hand side of the harvester as they should. However sometimes it gets close and says tractor X is stuck in traffic Or it unloads the Harvester and then reverses and then tries to turn left when the Harvester is in the way, check out the video in this link [https://youtu.be/G8rWuc1-GMw](url) I am also Attatching a few Pics of the harvester getting in the way of the tractor on the Up and downs on the field
![20180722123545_1](https://user-images.githubusercontent.com/26417002/43048533-1265ef62-8de1-11e8-887d-6c240827ca20.jpg)
![20180722114308_1](https://user-images.githubusercontent.com/26417002/43048545-2d2d7478-8de1-11e8-8de6-8a60f3fc4108.jpg)
![20180722131134_1](https://user-images.githubusercontent.com/26417002/43048550-44e760d8-8de1-11e8-9e63-61c83b81ba6c.jpg)
Regards
Michael

**Comment by pops64** [comment]
Judging by ypur 2nd pic your running skip row in advanced course gen. Mode 2 is not compatiable with that. Or if it is the last row of field work mode 2 has never been able to handle that. For the other two there is another post for the best havesters same problems. You can use the standard gianta helper has that causes a stuck in traffic issuse with the pipe. 3rd is it approaching or parking?

**Comment by Evilmutt** [comment]
Hi Pops. Firstly thanks for getting back to me so quick. First pic was same as the video I gave you the link for, It ha djust taken on some Potatos, then reversed and then Tries to turn to the left. Like it would for a Normal Harvester. Second one I am Not using the Advanced course generator at all but yes that Pic appeared to be from me finishing off a field and as for Pic 3 that was the tractor Trying to park. might I suggest that it does not park directly behind where the Harvester has Just been?
I have another Pic where the Boom of the Harvester catches the tractor when the tractor is stationary (that was the intended Pic for 2 actually) once again this was not near end of field work
![20180722112127_1](https://user-images.githubusercontent.com/26417002/43049544-6f648f88-8df1-11e8-85e0-98b48d2f486b.jpg)

**Comment by pops64** [comment]
Yea Mode2 has never really played nice with the not grain harvesters(AKA somebody changes something and non grain harvesters usually get neglected to be tested) If I have the time I will look into maybe a force that if it is a non grain harvester to use the old way of turning has I remember this working 90% of the time

**Comment by pops64** [comment]
Should be greatly improved in v21 or higher. The stuck behind it there is nothing we could do about that

**Comment by pops64** [comment]
Inactivity
