### ISSUE TITLE
drivers not tipping load

### ISSUE THREAD

**Issue by Quintto** [Courseplay/courseplay#2804]
I'm playing on the map Frisian March ( https://www.modhoster.com/mods/nordfriesische-marsch--2 ) and I've set up a courseplay course to load op silage at the southern BGA from a conveyer and unload it in the tip trigger on the northern BGA. the problem however is that the drivers recognize the trigger (courseplay does say tip trigger reached) but they don't empty their trailers on it ( when i stop the driver on the tipping point it can tip without moving, so I am hitting the trigger) is there a solution to this problem or is it a bug?

ps when the trailers are tipped the money shows up under harvest income not BGA income so it is setup as a normal selling point.
courseplay version v5.03.00008 dev

**Comment by pops64** [comment]
I tried hitting it closer. Has there is a .25 m difference between were humans and were CP can tip  are going fowards or reverse tipping? I think log with channel 1 and 2 are correct, I am away from my laptop and I don't remember the channels for this.

**Comment by pops64** [comment]
Yea it really only shows up in the BGA Sell Point, Water Troughs has theses tend be very small to begin with.
