### ISSUE TITLE
Sugarcane turn reverse problem

### ISSUE THREAD

**Issue by redkiil** [Courseplay/courseplay#2805]
Guys, i am stuck with this problem . I try change some parameters but no really happen.
I think is change a little the reverse distance will be fine, i try to change some values in turn.lua but idk how the specific code i need to change. https://i.imgur.com/ZdCl67q.jpg

**Comment by pops64** [comment]
Well it would be in fixing mode2 and how it handles sugar cane which version of CP are you using? I would stay away from using more that two trailers in mode 3 for the moment #2782

**Comment by redkiil** [comment]
The last version, i think we need to change the manuever of the tractor. because the manuever of the harvester is ok, in real life the tractor usually do the manuever in field, https://i.imgur.com/wuUVfRt.png

**Comment by pops64** [comment]
Try with version 19 or higher with turn on field disabled. This is a temp fix and will require lots of room to maneuver successfully

**Comment by pops64** [comment]
I have a fix for this. I made the turn maneuver turn it like the potato harvester(The fancy one). Which makes a different kind of turn that works way better.

**Comment by pops64** [comment]
Try again with version 38 or higher and report back
