### ISSUE TITLE
Vehicle leaves straight after reverse-unloading silage

### ISSUE THREAD

**Issue by Tisdan** [Courseplay/courseplay#2807]
My tractor Magnum CVX isn't able to leave the bunker after reverse-unloading. The vehicle leaves straight and bumbs into the fence. 
I am using the latest version from the hub.

**Comment by pops64** [comment]
If yo have to make sure when you recored your cpurse you have to leave straight for a bit before turning has it selects the next foward waypoint that is in front of it. So if you turn has spoon has you leave thw BGA random effects will happen
