### ISSUE TITLE
Tractor won't deliver to BGA

### ISSUE THREAD

**Issue by Tisdan** [Courseplay/courseplay#2808]
I have a course for collecting grass and another course from the same field to deliver it to the BGA.
However sometimes my tractor is stuck at 100%, stands and does nothing. 

Saving the game, re-entering the world and hiring the worker again usually fixes it.

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by lcc1211** [comment]
@pops64 I have the same issue with loading wagons on a single field in the Modhub map for Westbridge Hills (field 12). Once full the thing just stops and sits there. I no longer have the capability to capture a usable screenshot or video as I am on a triple screen set up, but I will add my log here.
[log.txt](https://github.com/Courseplay/courseplay/files/2259925/log.txt)

Is there something else I can add to assist in troubleshooting this?

**Comment by pops64** [comment]
#2818
