### ISSUE TITLE
Worker won't turn on loading weagon after returning from BGA

### ISSUE THREAD

**Issue by Tisdan** [Courseplay/courseplay#2809]
Sometimes my worker doesn't turn on the tools after returning from the BGA to the field. He just drives the course.

The course is made for the rake, also using headlands. Combined with a course to the BGA.

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
Same for me. What Debug Channels for the log ? I am using Version .00013.
My log is full of stuff so Idon't see a reason to upload it like this.

**Comment by pops64** [comment]
#2818
