### ISSUE TITLE
Lift/turn off tool in manual Fieldcourse

### ISSUE THREAD

**Issue by dominiczeth** [Courseplay/courseplay#2812]
Is there an option to turn off or lift a Tool when generating a Field Work course manually? I thought it works with Waiting points but it just stops at the second waiting point (Sure - it's for the end of working area). Is there (or can it be added) and option to Lift or turn off a Tool for Tranportation on a field? 

It does that in automatic generated courses when he finished a part of a Field and drives to another Part. I needed this yesterday and wondered why there isn't an option for that. Cheers!

I'm using the Modhub Version.

**Comment by AndyK70** [comment]
Nope not waiting points but turning points.
When you are manually recording a fiels work course, you are at the end of a row and want CP to lift the tool at this point you should add a _start turning point_
![grafik](https://user-images.githubusercontent.com/666825/43479853-c27e8d24-9501-11e8-8ec7-6bd0d950f43e.png)

When you reached the begin of the next row click that icon again to add a _end turning point_, that's where CP will lower the tool.

**Comment by dominiczeth** [comment]
I know, but the problem with this is that it generates courses between the start and stop point which can collide with obstacles beside the field. At least it was the case in mod hub version. Will try again with actual Dec version tomorrow.

**Comment by pops64** [comment]
Turn points are only to be used when turning 180 degrees there currently is no option to do what course generator does when moving from headland to up down or vice versa

**Comment by dominiczeth** [comment]
Yeah i already thought that. Maybe it would be a nice addition for the future.
