### ISSUE TITLE
Problems mode 4

### ISSUE THREAD

**Issue by MattAndersson** [Courseplay/courseplay#2813]
Hello, got an issue that i noticed when having a tractor doing the seeding, using the HORSCH EVO 12.375. When it needs to be refilled, and i show up and start to refill it, The tractor starts, unfolds the seeeder and takes off before reaching whatever percentage i set it to . Using a truck and HORSCH seed Tender 10T to refill, is this mode only supposed to work with a static filltrigger that the tractor drives through? or is it a compability issue maybe....Anyways Thanks for one awesome mod, would not play fs17 without it.. 

/Mattias

**Comment by pops64** [comment]
Are you filling it while on the field? If true then this is expected behavior has the mode4 isn't build to do that. You would have to create an unload route and fill it while on the unload route(or load in this case)

**Comment by MattAndersson** [comment]
Ahhh,, yes i was filling it on the field.  Thanks for the quick reply..I'd say we can close this thread then..
