### ISSUE TITLE
General question on course recording/driving

### ISSUE THREAD

**Issue by MrTobbsta** [Courseplay/courseplay#2816]
Hello, I'm trying to record a unloadcourse to the biogas station on the West Coast map from field 23. No problem during recording, but when the driver comes back after unloading it hits the gateposts at the entrance to the field.

So to my question, I don't hit the post during recording, what determines what part off the carriage follows the waypoints? Is it the pickup on the forage wagon or just a random point somewhere in the middle of the carriage?

**Comment by pops64** [comment]
The waypoints are always placed above the direction node of the driving vehicle 90% sure. The center of the driving vehicle. As for following them in fwd direction it is the direction node of the vehicle, in reverse mode it is different(I believe it is the direction node of the trailer) Has for it hitting the gate I would recommend either ensuring you using follow record speed and not max speed. And slow down has this is a map problem and something we can't fix
