### ISSUE TITLE
re-seed with  own  seed

### ISSUE THREAD

**Issue by magicmana** [Courseplay/courseplay#2818]
on map   we have often  seed factory  like fs17 seedmaster 2k17 
when we make re-seed course the only for use it  go to "something with an arm"  like a silo, a  trailer with arm etc...
it's mot easy to make course because area to transbording  on the seeder  is very small . 
and coursplay  did  not detect  the  seeder  is filling up.
on my seeder mod,  i  increase the  reseed  from 200 liter/s to 2000 liter/s
but  when I go under the arm at 3km/h , it's the lottery,  seeder can be at 50% to 90% full
![fsscreen_2018_08_03_15_41_08](https://user-images.githubusercontent.com/32802279/43648720-841f8704-973b-11e8-98f2-48571036cbb6.png)
![fsscreen_2018_08_03_15_41_19](https://user-images.githubusercontent.com/32802279/43648725-86bcbefa-973b-11e8-8c2f-7dd0fb300a00.png)
![fsscreen_2018_08_03_15_41_28](https://user-images.githubusercontent.com/32802279/43648732-882756a6-973b-11e8-9c4a-8ea1c1fa7991.png)

should be fine  in seed and  fertilize mode , when the volume of the seed increases the vehicle stop , and wait the volume stop to change.
or   if not possible , can we have an indicator in creation mode  like a line  from  the sky to the ground , or a symbol like an arrow who fly over the seeder reseed position , for know where put a "P" point precisely.
regards

**Comment by pops64** [comment]
Enable dev mode F5 will show the triggers. Or record the course with seeder and when it is in spot to refill then place the waitpoint.

**Comment by pops64** [comment]
Your confusing CP by placing both triggers on top of each other. Seed and fertlizer must be far enough apart that CP is able to delete the previous trigger from its memory

**Comment by pops64** [comment]
Closed due to inactivity
