### ISSUE TITLE
Issues with refill courses.

### ISSUE THREAD

**Issue by Evilmutt** [Courseplay/courseplay#2819]
Hi Pops and co
For some Unknown reason When I updated  from 010 to 012 and then 013 The Tractors are having an Issue with linking between my planting Course and the Refill course I have told it to follow for refills. Tractors just decided to go and do their own thing. so as I am not in the habit of holding onto older courseplays Had to get the version my cousin was using which was 003 and that reads my courses fine. I redid the course in 013 and same issue. I will Make up a video of it so You can see what is going on.

**Comment by pseikoNL** [comment]
Hi @evilmutt, see issue #2786 about this problem.

**Comment by pops64** [comment]
Just turn pathfinding off it should work like before

**Comment by pops64** [comment]
I havent forgot about this I have been afk form my gaming machine and won't be back for a while more. This will be the first thing that I look into when I get back

**Comment by pops64** [comment]
Try with version 18 and report back

**Comment by Evilmutt** [comment]
is working nicely Now thanks mate. Will try it as well with 21
