### ISSUE TITLE
Creates only 19 courses, 20 course rewrites on any up to 19 courses

### ISSUE THREAD

**Issue by fckorolev** [Courseplay/courseplay#2822]
Creates only 19 courses, 20 course rewrites on any up to 19 courses

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki version multiplayer?

**Comment by Blackmankot** [comment]
Это как? По подробнее опишите ситуацию.

**Comment by pops64** [comment]
Closed no response
