### ISSUE TITLE
Global environment

### ISSUE THREAD

**Issue by Blackmankot** [Courseplay/courseplay#2823]
Good afternoon! Question. Is it possible to create a global mode table "Courseplay", for example, with the name g_courseplay, visible for other mods? I know that "Courseplay" as any mod creates its own table in a global environment, but its name changes along with the change of the name of the mod, and it's extremely inconvenient. And it's very important that the global table g_courseplay exists in the global environment only when the player selects the "Courseplay" mod to go through a career in the mods list, as often it is necessary to demarcate the behavior of another mode according to the presence or absence of the "Courseplay" mod. Here is an example of the "Seasons" mode, which creates a global g_seasons table only when the mod is selected by the player.

**Comment by pops64** [comment]
? What are you trying to do. If you need acess to a specific varaible. It will most of the time be self.cp.xxxx. Where self is the vehicle or tool and xXxX is the variable your looking to access. It all depends on what variable you want to know the vaule of

**Comment by Blackmankot** [comment]
The author of all scripts Igor Lymar asks you. It is very convenient to prescribe the interaction of scripts on the map with the course, when it is possible to divide the behavior of the scripts in the map, depending on the presence or absence of the "Courseplay" mod in the mods list. Is it possible for authors to create a g_courseplay table in a global environment only if the player has chosen the "Courseplay" mod for a career?

**Comment by AndyK70** [comment]
In other words, you would like a consistent and convenient way to determine if Courseplay is an active mod?

**Comment by Blackmankot** [comment]
No, this is so that you do not have to delete the course from the mods folder every time. When it is necessary, that he would not interfere with the script of the map. And as it would be very convenient, that would not change the name of the created course global environment.

**Comment by pops64** [comment]
? Why are you deleting your course folder in the first place? This shouldn't have any impact on map scripts. They shouldn't even be accessing them has there is nothing internally that would be understood by anything but CP and a few external programs designed to read and change them

**Comment by pvajko** [comment]
So why does not Igor add what he needs and creates a pull request?

**Comment by Blackmankot** [comment]
Igor is a shy person. An example - the author of the fashion "Seasons" immediately did so, so it's very nice to work with his scripts, own scripts are very easy to adjust for the seasons. If you do not mind, we will be very happy if you make these changes.

**Comment by pvajko** [comment]
This has nothing to do with shyness, if he is not shy to create and publish mods, he should not be shy to create a pull request.

Creating a pull request instead of asking the devs to implement something it is a courtesy to the devs, especially when the person asking for something knows exactly what he wants.

Or, at the minimum should post a link to the Seasons commit or a patch of what they did.

**Comment by Blackmankot** [comment]
I agree with you! But in life, all people are different ... If a person hesitates to ask you a question, please do not take it like not respecting you.

Here is a link to the fashion season - https://www.farming-simulator.com/mod.php?lang=en&country=ru&mod_id=79288&title=fs2017

here are 2 lines that are enough to add to any KP script, for example in courseplay.lua

local globalEnvironment = getfenv (0);
globalEnvironment ["g_courseplay"] = globalEnvironment [g_currentModName];

this is enough to have access to a table with a permanent name (it does not depend on the name of the mod mode) that exists in the global environment when the CP is activated in the mods list.

**Comment by pops64** [comment]
I still don't understand what end goal your trying to accomplish. Has I can't think of anything in CP that needs or should be interacted with on the outside. So if you could tell us what your trying to accomplish by this change. I don't understand why you just can't check to see if self.cp exists had it should revert to nil when CP is active. Tho I may be wronge and I could give you different varaible to check to see if CP is actively driving a veichle

**Comment by AndyK70** [comment]
imho @Blackmankot wants a global variable so even mods that don't install themselves into vehicles have an easy way to tell if CP is an active mod in that savegame to act accordingly and don't mess with CP.

If it is just that two lines of code I don't see any drawbacks from doing so?

**Comment by pvajko** [comment]
Don't see any issue with it other than that someone needs to actually make that change :) I'll do it next week unless someone else does it by that time. We already spent way too much time discussing this trivial change, that's what pull requests are there for....

**Comment by Blackmankot** [comment]
@pops64 @AndyK70 @pvajko Good afternoon! I am very grateful that you agreed to make a proposal to the course! Thank you! :+1:
