### ISSUE TITLE
Course Play Will not Open

### ISSUE THREAD

**Issue by garrett484** [Courseplay/courseplay#2824]
I have downloaded courseplay and it shows up in my installed list inside the main menu under "installed mods", but does not show up in the pre-game mods selection list, and I can not open courseplay in the game when I right click. Any idea what would cause this?

**Comment by pops64** [comment]
You have downloaded a very old version. Please only install giants modhub version or the dev version. Downloads from anywhere else are unsupported. http://courseplay.github.io/courseplay/en/installation/index.html
Also follow https://github.com/Courseplay/courseplay/wiki when posting bugs
