### ISSUE TITLE
Suggestion: In CombiMode; save fieldnumber wher th

### ISSUE THREAD

**Issue by pAnFarmer** [Courseplay/courseplay#2826]
Hi all. Thx for the later improvements and certainly the implementation of the max speed option on the road.
Here comes another suggestion: Since it is possible to assign a field to a tractor where to look for a combine in mode combi (mode 2?), would it be possible to save that number while quitting the game so that it would  stay assigned on restarting FS? I have running combines on 10 fields at the same time...
Then I have a question: sometimes my tactors reverse in combi mode after being loaded. Is this function intended or a bug?
Thx for your work.

**Comment by pops64** [comment]
Intended on the reverse. If there isnt enough room on the headland for it to stay on the field it will do this. Add more headland if you don't want this to happen atm tho there is no override function for this. Has for your suggestion it may be possible. Will be looked into at a later date

**Comment by AndyK70** [comment]
@pAnFarmer Headland = Vorgewende

**Comment by mdart83** [comment]
I am also having the same kind of issue.  Any ideas on this??? On a wheat field i saved the fieldwork course for combining grain (45ft head) with straw row.  I use that same course to run a forage harvester over the windrow using the same exact course.  Where i run into trouble is the combi course (mode 2) that the tipper runs.  I have three headlands which load with no trouble, when switching from one straight row to another the tipper will turn around and return to the same row drive fwd and then back up.  At this point the tipper is to far away from the harvester. i tried turning off path finding with no luck. I tried tractor and and semi running the tipper.  The tractor and tipper will actually turn around and back up on the same row but then head towards the harvester and pull in front of it blocking the machine.

**Comment by pops64** [comment]
Actually, I think has to do with the way the advanced course gen handles the the one lane that has to over lap another. In the old course gen it would always be the last lane. In my recent play through it appears to be the first lane instead. So where the tipper is parking is fine. It just the the two lanes over lap each other. There currently is nothing to fix this other than moving the blocking tipper out of the way. This as always been an inconvenience for as long has I been playing FS

**Comment by pvajko** [comment]
@pops64 what specific lanes are we talking about? What is overlapping what?

**Comment by pops64** [comment]
@mdart83 No use the old thing just makes the problem occur on the last lane
@pvajko when workwidth / fieldwidth doesn't come out to a whole number what happens with the remainder? I know in the old system it just made the last lane fit on the field. I was observing that in your system it makes the first lane lane fit the field. Unless I am mistaken

This is what causes the one of the collisions. The other with headlands is when it has parked in the connecting track course but that didn't sound like what he was describing. To me it sound like the tipper parked successfully then the combine ran into the tipper. I have only seen this occur in the overlap situation I described 

See Pic
![fsscreen_2018_09_24_17_47_55](https://user-images.githubusercontent.com/10678220/45981194-29f2d000-c022-11e8-944c-002e1e1c2dd8.png)
The tipper parks in the last lane used by the combine in the last lane happens to be in the workwidth of the next lane then your get a collison

**Comment by pvajko** [comment]
Oh, I see what you mean. It can be the first or the last one depending the orientation of the field and the selected direction of the up/down lanes and the starting position.

Would overlapping with the headland instead of the next up/down row help?

**Comment by pops64** [comment]
That would be one way to fix it. The up down collision that occurs most is when the lanes overlap. But that would move this collision to the headland portion. Which would be fine if the headland overlap occur on the last lane of work. Has the tipper shouldn't be parked on the headland assuming headlands were done first. Vice Versa for the first lane. But the headland parking could use a ton of improvement

**Comment by mdart83** [comment]
![fsscreen_2018_09_24_20_10_34](https://user-images.githubusercontent.com/32818073/45987333-69c3b280-c036-11e8-8090-a882abdbc3b3.png)
![fsscreen_2018_09_24_20_09_00](https://user-images.githubusercontent.com/32818073/45987334-69c3b280-c036-11e8-84aa-cccd0abc3a4b.png)
![fsscreen_2018_09_24_20_09_04](https://user-images.githubusercontent.com/32818073/45987335-6a5c4900-c036-11e8-8e74-a146ecd352d2.png)
![fsscreen_2018_09_24_20_09_16](https://user-images.githubusercontent.com/32818073/45987336-6a5c4900-c036-11e8-919e-ab343f050498.png)
![fsscreen_2018_09_24_20_09_23](https://user-images.githubusercontent.com/32818073/45987337-6af4df80-c036-11e8-8f90-b77e72f1539f.png)
![fsscreen_2018_09_24_20_09_52](https://user-images.githubusercontent.com/32818073/45987338-6af4df80-c036-11e8-8347-68c071e1145a.png)

**Comment by mdart83** [comment]
i attached some screen shots of my issues.  i'm not sure if overlap is the problem.  The last image is the image with the course play map. hopefully you can make sense of the images

**Comment by pops64** [comment]
No I see what your talking about. Try with a smaller tipper. This is something that mode2 really never gets tested for. The problem your running into there is a limited range on the chaff harvester this combined with the workwidth and the trailer length make it so CP needs to be 100% accurate to even have a chance at working. mode2 has never been 100% and IMO never been above 90%. So with out us programing mode2 to handle this extreme case it chances of it working a slim. 

Please make a new issue about this has we are no longer on the same topic as the OP

**Comment by pAnFarmer** [comment]
Hi all. I see my issue is still discussed. I think the best way to handle these kind of reparking issues of the tipper, would be to let the tipper stand while where he got filled. After my observations, there wouldn't be anymore problems with all these collisions. Except the case when the tipper has to be filled in the fruit area. If the tipper was filled while standing on harvested areas, why should it repark?

**Comment by mdart83** [comment]
So disabling the turn on field command shod correct my issue?

**Comment by pops64** [comment]
Not at the moment. It will be something I'll be looking at doing in the future

**Comment by pops64** [comment]
Try with version 19. TurnOn Field in mode2 or 3 will either select the old method or the new method and report back/ This should also fix your issue mdart83. Until I can make the new turn maneuver compatible with straw chaff havester

**Comment by mdart83** [comment]
@pops64 i'm sorry im a newbie at this how do i access version 19?

**Comment by pops64** [comment]
@mdart83 I forgot it has been a while since I look at this code. You need to make sure the workwidth is set to the course workwidth otherwise you will run into your issue

**Comment by mdart83** [comment]
@pops64 i hope to have a report for you soon!  Working width should have to be corrected to the straw harvestor(10ft) from the previous grain harvestor width (45ft)?

**Comment by pops64** [comment]
No the working width needs to be set to the grain harvester. If it is set to the straw harvester width then it thinks that the harvester only mode 10ft away and not 45ft

**Comment by mdart83** [comment]
Ok, i did all the suggested and it is working correctly.  Turning on/off field option on or off did not make a difference.

**Comment by pops64** [comment]
Turn off field if disabled before the tipper turn will cause it to drive away then turn around to come back. Turn on field will cause it to perform the circle turn then reverse back to the havester

**Comment by pops64** [comment]
Alright closing this out. Implemented in version 24

 @mdart83 if you continue having issue please contribute to an existing issue with the same problem or if you don't see one start a new issue, Thanks
