### ISSUE TITLE
Reversing into bga 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#2827]
I’ve tried to reverse in to a bga but two issues I’m facing the tip trigger is at the front of the bunker can I override this so it goes into the bunker to empty and sometimes where the reverse starts it just dumps the load there I’ve set the course with no trailer and set unload point In the bunker but it won’t work

**Comment by AndyK70** [comment]
I don't know if it is a mod map or a standard map. If it is a standard map or at least a map with standard BGA drive-through-silos then you just have to enter from the other side and it will dump from that side...

**Comment by matty2123** [comment]
It’s a mod map with reverse only

**Comment by Blackmankot** [comment]
@pops64 I correctly understood when the transport is moving backwards, the unloading point should be put up to the silo pit, so that the unloading point is not in the triggre?

**Comment by pops64** [comment]
No unloading point. drive in reverse to half way into the bga and then switch to fwd and drive out straight until the last possible moment or until the end of you tipper is at least half of you total vehicle lengthy away from the edge of the BGA silo. More straight distance the better chance it will work right

**Comment by matty2123** [comment]
I’ve tried what pops64 said but as it starts it’s reverse it hits the tip trigger on the edge of the bunker and unloads which I suppose Is normal I just want it to unload in the bunker but can cope with it dumping on the edge

**Comment by pops64** [comment]
It should be going 20% of the length of the trigger into the bunker. Ensure the tip anywhere offset is 0. This is found under the combi settings page at the bottom. It resets after leaving the BGA but if it is the first unload it may not be 0

**Comment by matty2123** [comment]
Is that called unload point distance

**Comment by pops64** [comment]
Yea that one. Never really figured out a good name
