### ISSUE TITLE
Tip Triggers - Not working

### ISSUE THREAD

**Issue by Clipless** [Courseplay/courseplay#2833]
Had several courses setup in various maps relying on tip triggers these were primarily grain dumps (no BGA). When I upgraded to 5.03.0 they almost all stopped working. I thought perhaps I needed to rerecord or indicate with unload trigger or pause or something else, but none of that works. So a few notes about what does/ doesn't work. 
1. I have the same issues regardless of whether on mod map or not and regardless of whether using mod tractor or trailer or not. 
2. In recordings I slow down to 3 mph or less well before crossing a trigger and keep that speed until well after the tip. When I run the course (with use recording speed enabled) the recording will sometimes slow down at the right time, but then speed back up. 
3. I thought perhaps adding a pause point would stop them on the tip and they would then dump, but that doesn't work either.
4. CoursePlay is detecting the tip triggers - I have watched them run through and it says tip trigger detected. I have also clicked stop at next trigger and it will stop.
5. There is a tip trigger on Elkhorn Valley that works - it is a very long trigger.
6. This doesn't happen always and don't know if part of the issue or totally seperate, but it has happened several times - I set up the course and when I have CoursePlay run the course the first time the trailer doesn't tip, but it also turns off the HUD in the upper left corner (F1) for the trailer only (if you switch to the tractor shows up fine) and you can't turn it back on even when out of CoursePlay. It also doesn't show the tip icon on the HUD in lower left corner. Both of these stay with the trailer even if you change the tractor that is pulling it and are operating it manually. I have had this happen with both in game and mod trailers.

**Comment by magicmana** [comment]
have you try to add more points near the trigger area when recording course ? 
(make  pause move 50 cm ahead an use the "...x" button , move 50cm ahead and use the "...x"  again)
sample : 
![fsscreen_2018_08_17_16_43_00](https://user-images.githubusercontent.com/32802279/44272395-037c9080-a23d-11e8-9611-1bd52ec29e2d.png)

**Comment by pops64** [comment]
It sounds like the fill type in the trlr doesn't match the trigger. Reset the trlr to the store and make sure you are selecting the proper fruit if using mode1

**Comment by pops64** [comment]
Inactivity
