### ISSUE TITLE
courseplay and  big map

### ISSUE THREAD

**Issue by magicmana** [Courseplay/courseplay#2834]
hello  ,  
actually  i play  often to fs17 , now  i don't like  map  like goldcrest valley ,with small square fields.
i use more realistic and  big map  like  : 
http://www.farming2015mods.com/farming-simulator-2017-mods/fs-17-maps/fs17-loess-hill-country-4-1-0-0/
with 60 fields and file size  from 10 ha  to 60h. 
but on this type of map ,  i have 2  problems  with courseplay.
the first is when you have a lot of course  ,  fs17 make a lot of  time to load.
with  60 courses  plowing  course , load a savegame  in fs17 make near 15 minutes to  open.

the second problem   is that on  big map  with courseplay ,  it's that i pass a lot a time to make  waypath ,  for sample  when i  need a  make a reseed course  to the farm ,  which is at the opposite position on the map.

As I am familiar with the html / php / mysql.
i have already   resolved  my  first problem   ;
l has install a free wamp server on my windows game computer's  (https://www.uwamp.com) 
 i has create a web interface  (very very basic  for the moment , no image,  no style) , to have the possibility for save  courses with the web interface , and restore file  and re-create  courses and courseplay folders  in the  coursemanager.xml .

With  the seasons mode  , if  you plow all yours fields  the first year ,   you don't use courses before 108 (fs17)days.
9 days * 4 seasons * 3  years.

Actually   im working  on the second problem , i  try to create a  " high speed road's  trajet creator"  from an image  web  interface. 

i already  the  first step    :   the registering of the road .
how  it's work : 
first , I spotted, where exactly is the  recording point on the  tractor  i use for recording course
![fsscreen_2018_08_16_22_46_10](https://user-images.githubusercontent.com/32802279/44281868-785dc380-a259-11e8-8142-1ee0f64ed612.png)
I use a tool that is exactly 3m wide , for stay the more as i can on middle on the left way when recording.
you can use for sample the lizard tool for remove fields  , provided with the game.

now  it's time to register my road ,  i  start at a border's map  , and i follow the road at the end. 
Each time i see a field entrance or a factory entrance  i stop , and i put a "P" point on the middle of the entrance 
![fsscreen_2018_08_17_19_49_20](https://user-images.githubusercontent.com/32802279/44283104-9a594500-a25d-11e8-84ad-c8aa138f2dcc.png)
![fsscreen_2018_08_17_19_49_26](https://user-images.githubusercontent.com/32802279/44283109-9fb68f80-a25d-11e8-8422-a6f7ded352c1.png)
each time i see a  cross road ,  i  put a "unload" point at the middle.
![fsscreen_2018_08_17_19_53_24](https://user-images.githubusercontent.com/32802279/44283194-e1dfd100-a25d-11e8-9355-74eb936bf74c.png)
![fsscreen_2018_08_17_19_53_27](https://user-images.githubusercontent.com/32802279/44283214-f4f2a100-a25d-11e8-84d1-628221cfe94e.png)

at the end  , i have a course with 
- 500 waypoints 
- 6 "unload" points
-near  30 "P" points 

now it's time time tu use php ;-)
- the  first modification  i make ,  it's  to modify waipoints near all "P" and "unload" points
(delete , or move some points) for  do that : 
![001](https://user-images.githubusercontent.com/32802279/44287070-bbc12d80-a26b-11e8-9935-6ebe232d1443.png)
- the second modification i make  is to cloned  file.
On  the cloned file  i modify all waipoint like that : 
![002](https://user-images.githubusercontent.com/32802279/44287197-34c08500-a26c-11e8-8081-50d239789406.png)

- step 3  i replace wait="1"  by  crossing="1"
(i use the entrance points  in the futur , but for the moment , i haven't make , the scripts yet)

- step 4   for the 2 files to "sub-courses" and create  some folders (i explain after in the post )

- step  5 speed modification
 for all  "sub-courses"  created i set  the  speed parameter   to  "70" , and i  increase and decrease at the beginning and end of all  files like that :
![003](https://user-images.githubusercontent.com/32802279/44288899-4442cc80-a272-11e8-8ec5-5902fb8659c3.png)

- step 6  second modification  speed 
for each waypoint i take  the "angle" value , and the "waypoint +2"  "angle" value and i  determine the "delta"  value.
sample    for the waypoint33  i create  a delta with the waypoint35.
and  i change speed  using  that : 
![004](https://user-images.githubusercontent.com/32802279/44291282-b10f9400-a27d-11e8-97ee-6bca672649f9.png)
(near a road turn  speed decrease)

 

import an test 
 for  create  all the split  course ,  it's not not really complicated   
i call my "save page" on my web server local : 
![009](https://user-images.githubusercontent.com/32802279/44292239-d0a9bb00-a283-11e8-824e-b17aaa4d15f1.png)

now  i  go on my "split page" and select  the map ; the folder in courseplay ; and the files  i want  to split
![008](https://user-images.githubusercontent.com/32802279/44292346-36964280-a284-11e8-9f47-698fa3805a5b.png)

after i'm use my page "re-inject in courseplay" for select the folder  i want re-inject.
![010](https://user-images.githubusercontent.com/32802279/44292426-ca680e80-a284-11e8-82bb-db42ea686c2d.png)

an finally  i go  on courseplay and  reload  the  courses.
after than  now  in courseplay  i have 
![005](https://user-images.githubusercontent.com/32802279/44292527-701b7d80-a285-11e8-8045-b7d9266ce046.png)

![006](https://user-images.githubusercontent.com/32802279/44292538-7c9fd600-a285-11e8-806a-6dbb6beb5e1a.png)

![007](https://user-images.githubusercontent.com/32802279/44292541-832e4d80-a285-11e8-835e-6eede807e77c.png)

on this  picture  i show  the 2 road  i have recorded manually 
![fsscreen_2018_08_16_19_51_49](https://user-images.githubusercontent.com/32802279/44293441-672daa80-a28b-11e8-91f4-daa344d868bd.png)
an on this picture  i show  an aggregate for some part of the 2 road

![fsscreen_2018_08_16_20_04_10](https://user-images.githubusercontent.com/32802279/44294359-d0b2b680-a295-11e8-8c9a-7e1039710052.png)

the  finality is : 
 - now  i can create  course to anywhere on the map quickly using part of road
 - i can create course a 70 km  on road for  truck
(i using the keyboard and mouse  for play   , it's  very difficult to record a course at that speed without  finish in a tree )
 - for the silage  course  who  need 2 or 3 truck  from the fields to the BGA.  truck can   use the same road for go and back to bga   

i make a video with my first test of crossing  at the road

https://www.youtube.com/watch?v=ihCZUmNf4AA
i have a lot of think  not   yet implemented  for the moment  but  i should make an installer for windows  if some people are interrested  in the future

**Comment by pops64** [comment]
Your free to make your own branch of CP if you would like. For the first problem. This has always been an issuse. The way to avoid is not to save auto generated course has these are easy to reproduce. Your 2nd thing http://courseplay.github.io/courseplay/en/manual/index.html#hud_driverControls look as crossing point has CP is already designed for for mergeing to courses together. If looking for a self navigation mod https://github.com/Stephan-S/AutoDrive tho I am not sure of compatibility with the current version of FS 17. It is resource hog when first generating all the routes. Closed has we have to many open issuses. If you have anything that you would like to incorperate into the main version of CP feel free to make a pull request amd we will discuss it at that time
