### ISSUE TITLE
Engine turning off when tipping 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#2838]
When I tip when the tractor has to go forward because the pile is to big it keeps juddering forwards and then turns the engine off I then have to stop driver and then turn engine back on

**Comment by pops64** [comment]
It should be turning the engine back on unless it can no longer move foward but still has chaff to tip. The movement is normal has the heap can only accept so much fruit before it no longer can empty. So if it has so much chaff that it has moved foward out of the bunker then this would be expected. Try with a smaller tipper

**Comment by pops64** [comment]
Is thia still an issuse?

**Comment by matty2123** [comment]
No can close now thanks

Sent from my iPhone

On 26 Aug 2018, at 15:35, pops64 <notifications@github.com<mailto:notifications@github.com>> wrote:


Is thia still an issuse?
