### ISSUE TITLE
Unload point and distance 

### ISSUE THREAD

**Issue by Karlshoj** [Courseplay/courseplay#2839]
Having selected an area of 100x10 meter for beet storage I do reverse unloading by reversing to the end of the area where a "unload point" is set.
My problem is that when the dumped heap reaches app 30 meter of lenght it won't get any longer.
Is there a way to extend the lenght of the tipping area?

**Comment by pops64** [comment]
Are you driving straight out of the unload area or are you turning half way through? Has I am pretty sure there was no limit placed on this feature.

**Comment by Karlshoj** [comment]
Thanks for your reply,
Im driving straight in and out.
I think the reason is that i use two tractors and the dist. seems not to be updated from one to the other.

I have made four different courses, but only on one of them i get the option to set the 2unload point dist"???


I will close it for now and do a little more work with only one tractor at each unloading point.

**Comment by pops64** [comment]
Yea the unload distance is currently not shared. I was thinking of fixing this but never got enough motivation to do this. Has figureing out which vehicles to share would be a little complicated and it only shows up in combine convoy

**Comment by Karlshoj** [comment]
Still wants to use two tractors, but will them make each their own heap.

**Comment by Karlshoj** [comment]
Im not a programmer at all, just thinking.
If instead of the distance to the unload point the tractor/trailer could cast a ray to see to where the heap has grown it would work with any tractor????

**Comment by ThomasGaertner** [comment]
try v 015 and report back

**Comment by Karlshoj** [comment]
Thanks Thomas.
Works perfect, I used three vehicles to the same point. Overlapping is 1.7 - 1.8 meters.

You can close the issue
Just hit the donate button.

**Comment by ThomasGaertner** [comment]
Thank you
