### ISSUE TITLE
global parameter  to CTRL+F10 , and transfer mode

### ISSUE THREAD

**Issue by magicmana** [Courseplay/courseplay#2840]
hello , 
Generally on  big map  i'm playing with  near 80 vehicles
actually   in need to disable  the  right  click on  all  when buy, and  each time  a vehicle  have  reset

 i'm  using a lot of   conveyors;   with  the map  i playing actually , i'm  using  near 30 conveyor.
for sample  for   silage's bunker where is difficult  to make courses : 
![fsscreen_2018_08_21_18_39_33](https://user-images.githubusercontent.com/32802279/44416381-03e59600-a573-11e8-8ed5-f5b85c1effe2.png)
i  need use  frequently  the right click  to ajust position , and each time  courseplay it opens when I do not need it .
In vehicle with  frontal  arm like   telehandler  , scorpion king tree cutter , etc ;  it's little boring  to have the coursplay  open generally a the position  where you see the  ground.
![fsscreen_2018_08_21_19_01_31](https://user-images.githubusercontent.com/32802279/44420578-99d2ee00-a57e-11e8-9df4-76dd8ba840ad.png)

now each time i  buy  a vehicle  i set the  open to  CTRL+F10.
but  first  time  i make  silage when  in need  to buy  20 conveyors at the same time , it's  little boring to set all to  CTRL+F10.

And  now  the transfer mode.
I think   you should  you change  the "stop at the next trigger"  to enable by default in transfer mode.
personally I use this mode a lot ,  to move  vehicle on the map. Like to move my "cleaning tractor",  each  morning and evening form  the cow farm  to the pig  farm;  and each  time  i need  to enable  it.
The only time I find a utility is that "stop a next trigger" stay on disable; it's to make a circle on silage bunker for compress it.
it's not really a problem for me now.  I have so much enable it  each time , now  i  enable  it automatically without thinking.

But   I remember   my  first experience  with Courseplay.
 it was : 
- i found  courseplay  and  install  from the mod menu  in FS17
- install it and  load my save game
- my  first reaction :  "wahoo  it's not easy all this mode and all this options" 
- after  20 mn to try to  understand  how  it's  work  ,  i  tried  to make  my first course  and I said to myself "the only mode i have an idea how  it's work  it's to move for A to B , i try that".
- i registered my first course with a short course  in my farm,  and  i tested in road mode.
 - first try :  the tractor  make the  course and go crash  in a wall a the end of course.
- second try  : same thing.
- try  number 3 :  same  thing .
(with an option we can only view when the  course  is started , and  not named "stop at the end of course",but named "stop at the next trigger"  i'm  sure 99% of the user ,who  had tried to make the first course in  road mode , haven't enabled this option  )

In my case there has never been a test number 4. the next action  was to remove courseplay this "bugged mod".

should be fine too;  to write somewhere  in courseplay interface , that an online documentation exist , and tell the address :-)

**Comment by pops64** [comment]
It has been discussed in the past to enable stop at last point by default and it is something we are not going to change(Other impacts to other modes that would not be beneficial). I usually place a waitpoint right before the end if I want it to stop so I don't have to remember to turn it on. For other problem change line 1352 in hud.lua to false and 1458 in base.lua to self.cp.hud.openWithMouse = Utils.getNoNil(  getXMLBool(xmlFile, curKey .. '#openHudWithMouse'), false);
