### ISSUE TITLE
lua error course generator

### ISSUE THREAD

**Issue by k4r3l01** [Courseplay/courseplay#2841]
hello i using github development version of Courseplay and i have error in server log
Error: Running LUA method 'packetReceived'.
d:/servers/service1792/home/games/FarmingSimulator17/mods/FS17_Courseplay/course-generator/CourseGeneratorScreen.lua:62: attempt to index field 'vehicle' (a nil value)
courseplay version v5.03.00014

**Comment by pvajko** [comment]
Are there any other issues or problems or just this message? When exactly is this coming? Is this multiplayer?

**Comment by k4r3l01** [comment]
yep its on multiplayer and i think its only this message but in annother issue i have more problems
