### ISSUE TITLE
courseplay not recognizing digestate fill trigger 

### ISSUE THREAD

**Issue by Quintto** [Courseplay/courseplay#2842]
I'm using the Fermenting silo to make silage on my current save using ( https://www.modhoster.com/mods/fermenter-5000-fermenting-silo#description ) and it's working fine for the filling the thing with chaff and taking out the silage, however i can't seem to get my manure tankers to draw the digestate from it, is it simply not supported or am I doing something wrong?
( what is does is just drive straight past the trigger like there is nothing there )

**Comment by pops64** [comment]
Are you placeing a waitpoint where it says to refill the tanker plus a half meter or so?

**Comment by pops64** [comment]
Sorry I thought you were doing something non fieldwork related. Make aure the tool is driving through the trigger as digesate are ussaly to small to begin with. The wait point is only to unload in mode 8

**Comment by lcc1211** [comment]
If you get this to work, I would love to know how you did it as I've had this same mod for some time now and have never got it to work no matter how far into, past, next to etc. I drive. I think it just isn't recognized by CP as a trigger. The mod maker does say it it CP ready. I can't figure out why he would make the chaff drop off point so easy as well as the silage pick up, but wouldn't be able to make the digestate so diffult to find.

**Comment by pops64** [comment]
There are two debug channels that need to be checked to see if this trigger is working right. Channel 1 and 4 i believe (ray cast channel and load/unload if I am off on these numbers)  please post this log and picuture with F5 active of where the trigger is

**Comment by pops64** [comment]
Yea for what ever reason the triggers on both the silo and the tanker are extermly small which makes CP working with this hard. Closed due to inactivity
