### ISSUE TITLE
Combine and unloading 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#2843]
Hi since update the offset on the tractor to unload is wrong one min it says it’s in traffic another I adjust it then it’s miles away from the pipe I can’t get it right it frustrating

**Comment by ThomasGaertner** [comment]
can you give me a screenshot or a video of the issue. or a detailed description ?

**Comment by matty2123** [comment]
I’ll get some pics. But basically when the tipper unloads the combine the pipe comes out the tractor has to line up but when it drives to the combine it’s comes to the rear and says”  Xx tractor is in traffic “ and after then after it then goes to empty combine again it’s along away from the pipe and efficiency not emptying it

**Comment by pops64** [comment]
Yea this doesn't sound like anything to do with update it sounds like you have mod with a low combine pipe or another issuse already listed here

**Comment by matty2123** [comment]
![fsscreen_2018_08_26_18_54_56](https://user-images.githubusercontent.com/27097241/44631273-a336ce80-a961-11e8-9d3f-db5434306acd.png)
![fsscreen_2018_08_26_18_54_47](https://user-images.githubusercontent.com/27097241/44631276-a9c54600-a961-11e8-9fcf-62325aabb08e.png)
![fsscreen_2018_08_26_18_54_38](https://user-images.githubusercontent.com/27097241/44631280-b053bd80-a961-11e8-85bc-4bf9c07fdef2.png)

**Comment by matty2123** [comment]
AS you can see the problem been using this setup for ages with no problem

**Comment by pops64** [comment]
Well my guess is the header is causing the collision. Have you tried increasing the side offset to 9.8 m? Is this what is jumping around

**Comment by pops64** [comment]
Sorry 16 is fine just make sure to have the latest version

**Comment by ThomasGaertner** [comment]
could you try again with debug channel 3 active and post the log ? have you tried without the front weight ?

**Comment by pops64** [comment]
Closed do to inactivity
