### ISSUE TITLE
[SUGGESTION] Create trace field work

### ISSUE THREAD

**Issue by k4r3l01** [Courseplay/courseplay#2844]
Hello please its will be possible to add option to generate trace on ingame created field so this field not have field number

**Comment by pops64** [comment]
? What

**Comment by k4r3l01** [comment]
sorry for my bad english but i mean on some maps are fields not selectable by CP so my question is if its will be possible to generate field trace on field where i now stand

**Comment by pops64** [comment]
Yes it is. If no course is currently loaded. on the startup page you will see an option to scan the current field

**Comment by k4r3l01** [comment]
ohh sorry my fault youre right thanks

**Comment by pops64** [comment]
No problem You can also save it has a field after you scan it

**Comment by k4r3l01** [comment]
so when i tried to generate area around field and generated trace on this field i activated courseplaz but tractor break and courseplay still activate vehicle but nothing happens but on server console i gave this error Error: Running LUA method 'update'.
d:/servers/service1792/home/games/FarmingSimulator17/mods/FS17_Courseplay/inputCourseNameDialogue.lua:165: attempt to index local 'vehicle' (a nil value)

a tried to make area on around meadow area is generated correctly

**Comment by k4r3l01** [comment]
so i found where is problem when i have front and back lawn mower its stuck and not move tractor but when i have only front its not problem

**Comment by pops64** [comment]
That is a separte issuse please post a new issuse about the error with a full log single player or multi etc https://github.com/Courseplay/courseplay/wiki
