### ISSUE TITLE
field work in mp

### ISSUE THREAD

**Issue by k4r3l01** [Courseplay/courseplay#2847]
Hello any field work not working in multiplayer 
`[dbg5 lp9916 16:01:31] send event
[dbg5 lp9916 16:01:31] 	id=290, function=changeDebugChannelSection, value=1, page=6
[dbg5 lp9916 16:01:31] 		writeStream
[dbg5 lp9916 16:01:31] 			id: 290/9  function: changeDebugChannelSection  value: 1  type: number  page: 6
[dbg5 lp10661 16:01:44] send event
[dbg5 lp10661 16:01:44] 	id=290, function=toggleDebugChannel, value=17, page=6
[dbg5 lp10661 16:01:44] 		writeStream
[dbg5 lp10661 16:01:44] 			id: 290/10  function: toggleDebugChannel  value: 17  type: number  page: 6
[dbg5 lp11144 16:01:52] send event
[dbg5 lp11144 16:01:52] 	id=290, function=toggleDebugChannel, value=22, page=6
[dbg5 lp11144 16:01:52] 		writeStream
[dbg5 lp11144 16:01:52] 			id: 290/11  function: toggleDebugChannel  value: 22  type: number  page: 6
[dbg5 lp11375 16:01:56] send event
[dbg5 lp11375 16:01:56] 	id=290, function=toggleShowVisualWaypointsAll, value=nil, page=6
[dbg5 lp11375 16:01:56] 		writeStream
[dbg5 lp11375 16:01:56] 			id: 290/12  function: toggleShowVisualWaypointsAll  value: nil  type: nil  page: 6
[dbg5 lp11427 16:01:57] send event
[dbg5 lp11427 16:01:57] 	id=290, function=setHudPage, value=8, page=global
[dbg5 lp11427 16:01:57] 		writeStream
[dbg5 lp11427 16:01:57] 			id: 290/13  function: setHudPage  value: 8  type: number  page: global
[dbg5 lp11638 16:02:00] send event
[dbg5 lp11638 16:02:00] 	id=290, function=openAdvancedCourseGeneratorSettings, value=nil, page=8
[dbg5 lp11638 16:02:00] 		writeStream
[dbg5 lp11638 16:02:00] 			id: 290/14  function: openAdvancedCourseGeneratorSettings  value: nil  type: nil  page: 8
1
2
2
2
[dbg5 lp12367 16:02:13] send event
[dbg5 lp12367 16:02:13] 	id=290, function=setHudPage, value=1, page=global
[dbg5 lp12367 16:02:13] 		writeStream
[dbg5 lp12367 16:02:13] 			id: 290/15  function: setHudPage  value: 1  type: number  page: global
[dbg5 lp12605 16:02:17] send event
[dbg5 lp12605 16:02:17] 	id=290, function=rowButton, value=3, page=1
[dbg5 lp12605 16:02:17] 		writeStream
[dbg5 lp12605 16:02:17] 			id: 290/16  function: rowButton  value: 3  type: number  page: 1
[dbg5 lp12637 16:02:18] send event
[dbg5 lp12637 16:02:18] 	id=290, function=rowButton, value=3, page=1
[dbg5 lp12637 16:02:18] 		writeStream
[dbg5 lp12637 16:02:18] 			id: 290/17  function: rowButton  value: 3  type: number  page: 1
[dbg5 lp12780 16:02:20] send event
[dbg5 lp12780 16:02:20] 	id=290, function=rowButton, value=1, page=1
[dbg5 lp12780 16:02:20] 		writeStream
[dbg5 lp12780 16:02:20] 			id: 290/18  function: rowButton  value: 1  type: number  page: 1
[dbg5 lp12788 16:02:20] recieve new event
[dbg5 lp12788 16:02:20] 	readStream
[dbg5 lp12788 16:02:20] 		id: 290/57  function: self.cp.canSwitchMode  self.value: false  self.page: 1  self.type: boolean
[dbg5 lp12788 16:02:20] 			run
[dbg5 lp12788 16:02:20] 				id=290, function=self.cp.canSwitchMode, value=false
[dbg5 lp12788 16:02:20] 					setting value
[dbg5 lp12788 16:02:20] 					self.cp.canSwitchMode = false`

**Comment by pops64** [comment]
Exactly what is not working

**Comment by k4r3l01** [comment]
this log is used with combine when i click start drive nothing happens and i tried with no mods on original map and its still same but i tried more its like this 
https://github.com/Courseplay/courseplay/issues/2835
its on dedicated server

**Comment by pops64** [comment]
#2768
