### ISSUE TITLE
"drunken" driver where reseed with middle size seeder

### ISSUE THREAD

**Issue by magicmana** [Courseplay/courseplay#2849]
hello , i have  a problem with the horsch promto 9DC and  headpass
when  the seed  is empty and  the tractor  try to  go to  the first  point of the reseed  course    the  tractor do this :
https://www.youtube.com/watch?v=TdRfjNYlMIM
i  make a test on goldcrest valley with  only   courseplay and  seasons mod,  for see  it's  a mod or map problem, but same result.
i take a  standard  tractor  puma cvx   and  the    horsch promto 9DC
i create a seed course  with 2 headland pass on a square field 
i create a reseed course for  nowhere (for test)  with a P point
![fsscreen_2018_08_26_23_57_57](https://user-images.githubusercontent.com/32802279/44633555-46510d80-a98d-11e8-82aa-e213b4809fc1.png)
and i have the same result . when the seeder  is empty    the driver go in "drunken mode" :-)
i have the  problem with some other middle seeder (horsch evo 12.3775  from the HORSCH AGROVATION dlc)
but  with bigger seeder (like amazone condor 15001  ) or smaller seeder (like grimme gl860) i haven't the problem 

i have the problem too when  the  tractor back from seed station and try to go to the point where he stop to seed

**Comment by pops64** [comment]
#2786
