### ISSUE TITLE
mouse pointer not showing

### ISSUE THREAD

**Issue by fudoido** [Courseplay/courseplay#2850]
hey team. just downloaded latest version of courseplay after a couple months without updating.
when doing right-click in a vehicle, it opens courseplay hud, but no mouse pointer shows up and after clicking right button again it doesnt show up,
it was working on the previous version i was using, no other mods have been added since then.
know what can be causing this? thanks in advance.

Edit. i was able to get it to show now by pressing left CTRL+DELETE while hud is displayed, but i cannot change that key combination on hud options to open it, from right-click to lctrl+del, so ill be stuck with only right-click to open courseplay hud.
also, am unable to make the cursor hide after doing this key combo, no way to change camera now with hud displaying.
unable to press some options, start the course and return to first position for example.
updated to modhub version, same errors, and dont remember which version i was using before that worked.

last edit: ok, seems the problem was on my side. been through all mods in the folder (instead the modhub panel) and found out i actually had 2 instalments of courseplay with diferent names. feel a real noob now lol. sorry team. dont know how to delete the issue or else i would.

**Comment by AndyK70** [comment]
You can close this issue, that will work just fine.

**Comment by fudoido** [comment]
thanks andy. ^^
