### ISSUE TITLE
Pivot irrigation fs17

### ISSUE THREAD

**Issue by regularguy1984** [Courseplay/courseplay#2853]
Hi i have converted the pivot irrigation mod to fs17 but courseplay for some reason work work with it. The starting point starts on the base instead of the last pivot to record a circle. Would you be able to add this into courseplay? 
Thank you

**Comment by pops64** [comment]
Link to the mod has I don't understand what is not working or what your trying to do. Only links to official sites please(Giants Mod Hub, FSUK etc or any other approved location by the author)

**Comment by regularguy1984** [comment]
This was converted by me with permission from author in fs15 to fs17 
http://www.modhub.us/farming-simulator-2017-mods/pivot-irrigation-v1-0-0/

Thank you again for helping

**Comment by pops64** [comment]
This probably won't be added in cause of the tool and CP having no coding what so ever to handle this tool type. If I were you and wanted to do it automatically I would figure out how the conveyor AI works with the angle and use the standard giants AI
