### ISSUE TITLE
Save DC Settings after Game Restart (Suggestion)

### ISSUE THREAD

**Issue by dominiczeth** [Courseplay/courseplay#2855]
Is it possible to also Save the Drive Control Settings per Vehicle? It's only saved for the Game Session, but when you restart the Game it's back to Automatic. For Field Work with MR it's a problem, you often need locked Diffs. 
It's not a big deal for me, but it would be nice if it would be saved like the Speed Settings. 

Courseplay Version 5.03.00016

**Comment by pops64** [comment]
Not entirely sure it is possible has it is one of these weried variables that only gets created if drive control exists
