### ISSUE TITLE
Courseplay detecting a maximum capacity of a bunker silo

### ISSUE THREAD

**Issue by THiamu** [Courseplay/courseplay#2857]
CP is detecting a "capacity" of a bunker, and stop's filling bunker once it thinks that it is full, when in real it is filled up about 15-20% ...
The log (Debug-Channel 1) says this: 
[dbg1 lp12310 09:22:33] 900 Vario (#3): call tipTrigger raycast (rev) #1
[dbg1 lp12310 09:22:33] 900 Vario (#3): found interactionTrigger
[dbg1 lp12310 09:22:33] 900 Vario (#3): transformId=60766: interactionTrigger
[dbg1 lp12310 09:22:33] 900 Vario (#3): transformId 60766 is in tipTriggers (#278) (triggerId=60766)
[dbg1 lp12310 09:22:33]     trailerFillType=26 chaff
[dbg1 lp12310 09:22:33]     trigger (60766) accepts trailerFillType
[dbg1 lp12310 09:22:33]     trigger (60766) fillLevel=1368444, capacity=1345600 -> abort
If you look into the .i3d of the map you can't find the value "1345600". I'm guessing CP is calculating this value of 1345600 somehow.
I'm not sure if it's a problem of CP or of the map which is "NF Marsch 4fach" in this case. But on my research on the web I found some others having the same issues with different maps!

**Comment by pops64** [comment]
It would be a map issue. Has CP doesn't calculate the max fill level. It asks the giants engine what the max fill level of the silo is.

**Comment by ThomasGaertner** [comment]
I would like to test but I don't like to download at ul.to

**Comment by pops64** [comment]
Where did we come up with that equation? Giants doesn't have a Max vaule associated with the trigger?

**Comment by pvajko** [comment]
(off topic, but you can add permalinks to the code here) https://github.com/Courseplay/courseplay/blob/ec633e5e708a3a310eeec4535a4a509ee5859ce6/triggers.lua#L575

**Comment by THiamu** [comment]
Sorry for my late answer, I've had a lot of work...

I found the "check bunkerSilos" on line 626 of my log:
check placeables
[dbg1 lp6667 09:39:50] 	0 found
[dbg1 lp6667 09:39:50] 	check bunkerSilos
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=16194, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=62089, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=62041, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=16215, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=62188, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=14682, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=62062, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=16208, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=62096, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=61952, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=62181, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=16222, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=16201, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=61966, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=59989, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=59996, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=62069, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=61959, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=62048, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=62055, name="interactionTrigger", className="BunkerSiloTipTrigger", is BunkerSiloTipTrigger 
[dbg1 lp6667 09:39:50] 	check tipTriggers
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=16255, name="triggerPos", className="TipTrigger", isAlternativeTipTrigger=nil
[dbg1 lp6667 09:39:50] 		add tipTrigger: id=104989, name="TipTrigger", className="TipTrigger", isAlternativeTipTrigger=nil
............
[dbg1 lp7051 09:40:10] 900 Vario (#1): call tipTrigger raycast (rev) #1
[dbg1 lp7051 09:40:10] 900 Vario (#1): found interactionTrigger
[dbg1 lp7051 09:40:10] 900 Vario (#1): transformId=62089: interactionTrigger
[dbg1 lp7051 09:40:10] 900 Vario (#1): transformId 62089 is in tipTriggers (#278) (triggerId=62089)
[dbg1 lp7051 09:40:10]     trailerFillType=26 chaff
[dbg1 lp7051 09:40:10]     trigger (62089) accepts trailerFillType
[dbg1 lp7051 09:40:10]     trigger (62089) fillLevel=2435190, capacity=1345600 -> abort

I also attached the complete log.

[log.txt](https://github.com/Courseplay/courseplay/files/2364053/log.txt)

**Comment by pops64** [comment]
We are looking into it. I was wrong thought we obtained a vaule from Giants in fact we use a formula to detect the max vaule. In the future please only post snippets from your logs(1 or 2 lines) Has to keep the issue clean and readable

**Comment by XPiRiJenZ** [comment]
@ThomasGaertner ul.to or not, there are other "alternative" links which are way faster than the original ;) (don't get me wrong! I always use the original link, if a new version comes out! maybe you'll try this one: https://ls2017.com/wp-content/uploads/2018/07/NF_Marsch_4fach_entpacken.rar)

@THiamu you can actually try a workaround for the silo by using a tip-point inside the silo for the driver.
This works with chaff and grass. But you have to keep an eye on the fill level of the silo. if it is full and the driver is still active, he will continue tipping his load at the point.

**Comment by pops64** [comment]
Closed #2909
