### ISSUE TITLE
call stack in combi mode

### ISSUE THREAD

**Issue by Liquid515** [Courseplay/courseplay#2859]
getting error running lua..call stack in combi mode
[log.txt](https://github.com/Courseplay/courseplay/files/2346656/log.txt)

**Comment by pops64** [comment]
It is your mode 3 driver. Ensure you don't have mod that is incompatible

**Comment by Liquid515** [comment]
yes its was a mod ...the colemen bins are not capatable ...thanks

**Comment by Liquid515** [comment]
I will close this subject
