### ISSUE TITLE
Assigning a silo Distributor

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#2860]
Good morning! Would it be possible to allocate a silo distributor to the hopper that could be filled with the silo? Like threshing?  For example, with the BGA if two distributors run the driver do not have to wait for both???
Lg

(Guten Morgen! Wäre des möglich beim Silo befüllen Abfahrer bestimmten Silo Verteiler zuzuweisen?? so wie beim dreschen??  damit z.b. bei der Bga wenn zwei Verteiler laufen das Abfahrer nicht auf beide warten müssen??
LG)

**Comment by pops64** [comment]
What?

**Comment by AndyK70** [comment]
In CP mode 10 there is the option to let the CP worker drive to parking position and wait until the tipper has left the surveillance area. 
He wants to have the possibility not only to select "all vehicles" or "cp driven vehicles" but a third option "selected vehicle" and then select one vehicle like you can do in mode 2 when selecting an explicit combine to watch for.

**Comment by pops64** [comment]
I think that may have already made it onto the list. Closed for now
