### ISSUE TITLE
about the silage combine , and  the island detection  in all mode working on field

### ISSUE THREAD

**Issue by magicmana** [Courseplay/courseplay#2863]
hello  , when i worked on my script  yesterday ,  i had an idea  you can include  in courseplay  with some minor change  an who can resolve a lot of  island detection  problem in all mode, reduce overload collision , and  , in some case reduce by more than 50%  the number of auger wagon needed ;-)

first  time  for understand , a little history  about why  i create initially  my script .

i played with "the pacific northwest" map.
![pda_map_h](https://user-images.githubusercontent.com/32802279/45380166-5e1dc800-b602-11e8-8508-a30314d5c7d0.png)

The firsts seasons  years i made silage with  silage bale ,  and for  harvest  i used 2 combines  (one small , one middle) , 2 auger wagon on Terra Variant  , and 3 truck with grain trailer (2 for middle combine and one for the small combine) 

after  some years  and some money  , i  bought a silage combine with 6m header cutter ,  and  gone to the field on the map with the silage combine  , my  two Terra  Variant  with silage trailer , and my  3 truck .
i made 2 courses like that : 
![pda_map_h2](https://user-images.githubusercontent.com/32802279/45380935-39c2eb00-b604-11e8-959e-c24798b127c9.png)
orange = overload
white = truck go to bga 
blue =  truck back to bga

I was too confiant.....

after 5mn, when all  auger , and  the truck are full...  the  combine stop and  wait 20 real  min that the truck goes to bga , unload , and back , and when the truck back  ,  the overload ,  make  time to go to combine at 24 km/h.
the combine waited near 90% at the time , and worked only  10% at the time

at  the  final   for make silage  with only one  combine ,on this field ;  i needed to  increase my stuff to : 
- 1 auger wagon attached to the silage combine 
- 3 > 11 truck
- 2 > 5 terra variant 
- a 150000L  motherbins trailer (who accept silage)   on  the field    for buffuring where all truck on the road 
-  12 conveyor  on the bga 
 (the trucks  dropped silage on  the floor outside  , and i used ,  3 conveyors chain for clear , the "drop zone"  faster , before the next truck arrive)
  

that the reason ; i created my road script.

What is all this to do with detection? it happens ;-)
After reducing the number of truck , with my's courses using the same road at 70 km/h ;  yesterday i worked to  modify my scripts to have the possibility  to  splitting/aggregate  overload courses too .
The idea  is to  do , an  original  course,  like that :
some points before the unload point , and some after
 
![002](https://user-images.githubusercontent.com/32802279/45383691-40edf700-b60c-11e8-97f0-95cd26133111.png)
this file make 60Ha , and  the goal i try to reach ,  is to make silage with 2 silage combine (header cutter 9m) without a buffuring trailer  ; and try to use "only" 6 tractor  with overload wagon , and "Path finding" disabled

now i  create a  course like that  : 
- the "blue P point"  is the exit circuit  
- the "red P point"  is the  entrance circuit 

on  each "red P point"  i create a "Bypass"  road   for make  parking  place: 

![004](https://user-images.githubusercontent.com/32802279/45384111-5ca5cd00-b60d-11e8-9438-342749b55602.png)

 

 - in the case  where  the  grass range  is near 3m  , i record  the course outside near 1,5m  to the border field ,  i,m use the original course  to park the trailer who  wait    outside ; and  the trailer who  moving  using a short  distance inside the  field .   ( like at  the picture)  
- in the case  where the grass range is more larger , i m record the course same as previously , and i   put the parking place and the bypass outside the field ; and  i invert the 2 waypass . a trailer  who  not use  this waypoint  cross at high speed. 
 
 - in the case where  have no place outside ,  i record inside file. and create bypass like the first case.

Now  i can create  6 courses like that  : 
(the pink arrow  is the way to go to combine and exit after)

![003](https://user-images.githubusercontent.com/32802279/45387972-ef4b6980-b617-11e8-8cbc-45d2aa7a128f.png)

my  idea is   to : 
- put 1 auger wagon  at each  red point 1 to end  point ,   during the  headland , 
- put  2 auger wagon at point 1 , 2 at point 2 , and 2 at point 3, when  combine start  the go and back .
- when  combine arrive near red point 4 ,  assign the  2 auger wagon  from red point 2  to this point etc...

the  next question  is "Is very complicated  , you  just need to  increase  speed  on  tractor with auger wagon".
But  the answer  with  silage combine  is :  is not working ;  because  the combine not moving.
If the tractor  arrive at 40km ,  he  haven't the time to brake and enter  in collision with the combine.

with a wheat combine ,not full,  not a problem  the combine continue to harvest, and  the  tractor continue his course  when the distance to increase enough.

with  a silage combine  ,  2 time of 3  , at  40 km/h need to stop the tractor course , moving near the  combine and restart the course.

After brainstorming , i think   i should  be  interesting to  include  that directly  in courseplay  for   field > at 20Ha , and field with island.

- the  idea  is to create a new method to manage the   trigger :  the conditional 
after start a course ,  we could choose  on "stop at the next trigger"  :  yes / no / conditionnal 

this method work  in mode 2,3,4,6  and perhaps in mode 1 and 7  (i,m not sure)

for working   this  new method need a  new type of point   ; the conditional point  , the icon should be a "?"

for working  the conditional method  need 1 to 5 "**? point**"  before one or more "**P-point**" or "**Unload point**" ; and 1 to 5 "**? point**" after 
like blue and red  point  on  previous picture.

in mode 2,3,4,6  when the  vehicule leave the  field , when seeder is empty in mode 4  , or where the  truck trailer is full  in mode  2 ,   courseplay  check  if the nearest exit point  not crossing    an island (exit points is "**? point**" before  trigger)  
testing from closest to farthest until the script  finds a valid output

in the  rare case  where all exit point not working ;   for sample near  the  purple point  on this picture
![005](https://user-images.githubusercontent.com/32802279/45398046-f76cce80-b642-11e8-8251-f24f1e4ee5b2.png)

the script try , END point , END-1 point (p5) ,END-2 point , etc..

when  the vehicule reach the exit point ,   he continue is course  considering  the other exit  point  he should to cross ; to  standard point ;  until  he haven't pass all  triggers point.

After the  trigger point  , each time  the vehicle pass a  standard point ,  the script check if  the point+10  is a "**? point**".

when  he found the first "entrance point"  : 
   - in mode  4 and 6  the script determine what  entrance point he use to go to the point where the            vehicule has previously stopped ; and continue the course  to this point. When he when he approaches  ,  he reduce speed gradualy and turn.

 - in mode 2,3  the truck with trailer  or the tractor  with auger wagon he reduce speed gradually and stop. when  he is called by the combine , like  in mode 4,6 , he chose a point  go at full speed  , and reduce speed when approching 

i think   it should  be  very interesting  to reduce collision and  time to go to the  combine ;-)

**Comment by pops64** [comment]
Very Interesting, we might look more into this after 19 comes out. Has we really don't want big changes in the short time that 17 has left. 

I know in mode 4 and 6 in the Dev version it will find the most direct path keeping it on the field to the start of the unload course if pathfiding is enabled (WIP). 

As for stopping at next trigger I don't like messing with that has there is a lot of CP conditionals based off that. So it would involve alot of checking to ensure you don't break anything unintentionally. It would be just easier to implement something specific for mode 2.

Also mode2 as always been kinda of finky with siliage we fix one problem and break another it is always on our todo list to improve

**Comment by magicmana** [comment]
hello , about fs19  i'm  on  the same case , actually ,  i,m  not working  to  create  an interface for simplify the course aggregation.
my first idea was  to extract the pda_map_H.dds directly from the map.zip ; convert  to an .PNG , and create  a clickable picture on a webpage using GD (a library in php for manipulate image)
but  , i read somewhere , that , in  FS19 we start with no farm and fields , and create completely .
Not sure the pda_map_H.dds exist again in fs19.

And now for back to the original subject  ,  i call  some  detail .

the idea is  to set "stop at  the next  trigger" always visible.
before starting course , you can  choose  "yes"/"no"/"conditional" 

after starting  the course  : 
 if  "yes" or "no" was selected  , you can change to  "yes" or "no" , like actually , but not change to "conditional"  
if "conditional"  was selected ,  you can not  change  to "yes" or "no".   for change to  "yes" or "no", need to stop the course.



when  you start  the course : 

since all points, which require conditional conduct, are at the end of the race.

in the case  or  "yes" or "no" was selected ; the  only change to do  it a set a value like "entrance_in_ 
conditional_driving_mode"  to  a  big value  never used in courseplay like "1000000000" 

in the case or "conditional"  was selected ;   you  just need to determine  , from which point he enters conditional mode.

during the driving course ,  you only need to add one "IF" at each point
like   IF "current_index_position" >=  "entrance_in_conditional_driving_mode"

**Comment by pops64** [comment]
Your free to try to implement this into CP and create a pull request and we will discuss then wether to include it or not. But the variable your trying to expand is a weried and very old variable that has a lot of interconnections. Has for using the point grading system. We do use it to find a path to the combine avoiding the fruit. Which turns out to be one of the heaviest CPU hits next to course gen

Just be warned if your messing with mode2. That mode is not to keen on playing nice with changes. It could almost be a stand alone mod. Has it doesn't interact with the rest of CP while on the field expect a few minor exceptions. It only behaves like the rest of CP when running the unload course. That is actually the difference between 2 and 3. It really is only mode 3 when unloading but when it hits the end of the unload course it hands itself back to mode 2

**Comment by pops64** [comment]
Closed #2909
