### ISSUE TITLE
CP erkennt falsche Drescher / CP detects wrong Harvester

### ISSUE THREAD

**Issue by Pitbull123** [Courseplay/courseplay#2866]
Moin moin zusammen,

wir spielen auf nem Dedi und haben seit kurzem das Problem dass CP die Drescher nicht richtig erkennt.

Heisst wenn ich dem Abfahrer  nen Drescher zuordnen will muss ich komischerweise den Drescher nehmen der am weitesten weg steht von mir obwohl er nur 10 m weg ist.manchmal ist es aber auch statt dem 10.90 einfach ein Terra Dos oder ein Hächsler

Irgendwas ist da komplett durcheinander

Kann mir einer sagen wie ich CP im Prinzip resetten kann ?

Ich hab schon auf dem Dedi CP gelöscht,dann spiel gestartet und ohne CP gespeichert.dann CP komplett neu runter geladen und neu aufgespielt.trotzdem sind dann die kurse wieder da und auch die Drescher zuordnung passt nicht

was muss ich alles auf dem Dedi löschen um CP auf Anfang zu setzen ?

Gruß

Patrick 

Hello together,

we play on his Dedi and have briefly the problem CP the Harvester not correctly recognized.

I'm told that the turner to take the thresher, which is the most away from me just 10 meters away. Sometimes, however, the 10.90 is simply a Terra Dos or a Hächsler

Something is complete

Can someone tell me how I can reset CP in principle?

I have already deleted on the Dedi CP, then the game is started and stored without CP. Then the CP is completely new, and it is no longer understandable

what do I have to do on the Dedi to get CP started?

greeting

Patrick

Translatet by Google :-)

**Comment by pops64** [comment]
Closed #2909
