### ISSUE TITLE
Drive 819 nil error

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/courseplay#2869]
Hello,

my problem is not solved
I assigned keys to the CP's functions and I downloaded the new version, but nothing helps. I still have the same problem.

My log:
https://pastebin.com/embed_js/5HszYkLA

Regards,
Crinouche

**Comment by pops64** [comment]
Please post in orginal issue if the same problem is occurring we will reopen them. Thanks

**Comment by Crinouche** [comment]
thank you for your reply

If I understand; if I create a race on a part 1 and I play with at a part 2 or 3, it can cause a problem ?!
I will do my courses again to avoid mistakes.

Thanks again

**Comment by AndyK70** [comment]
I would assume the problem exists with the Fendt 1000 Vario as this mod has some index errors looking at your log.
If CP wants to use this vehicle it runs into that index problem and crashes with index has nil value.

**Comment by pops64** [comment]
Na it shouldn't be mod related. Some how self.Waypoints doesn't exist. Which can't happen unless there is a corrupted course. If you could upload your course folder I can tell you which one specifically is the problem

**Comment by Crinouche** [comment]
[CoursePlay_Courses.zip](https://github.com/Courseplay/courseplay/files/2409182/CoursePlay_Courses.zip)

**Comment by pops64** [comment]
I would need to know which one is causing the problem has you have to many to look through manually. Or just try the replacing the file with the one I posted and let me know if that fixes your issue

**Comment by Crinouche** [comment]
Hello,

I replaced the file you sent me and it seems to work properly. I played about 2 hours on clover creek and I did not have any bug.
Thank you.

**Comment by pops64** [comment]
Alright. I will be making a push soon and this will get included

**Comment by pops64** [comment]
Fixed in version 19
