### ISSUE TITLE
Mode 3 - Too high approach speed

### ISSUE THREAD

**Issue by blaz62746** [Courseplay/courseplay#2872]
Overloader stops in front of combine pipe when it comes from behind. It just doesn't have enough time to make a stop on time. I have field speed at maximum because it's large field. If you could adjust that tractor slows down on turn speed if it is for example 30 meters from combine, that would be great.
![fsscreen_2018_09_26_17_44_34](https://user-images.githubusercontent.com/26365587/46096454-8808ea00-c1bf-11e8-966a-6c9291c5a96d.png)

**Comment by pops64** [comment]
As most users don't set the field speed to max and we would get people asking to decrease it on the smaller field so the tractors aren't spending all day on approach. Feel free to alter your own CP if you would like but the official version probably won't be adjusted. Also if your using MR this also probably is causing your problem has stated in the unsupported mod section

**Comment by blaz62746** [comment]
Thanks on response. It's my fault that I didn't check unsupported mods section. I checked it now and I'm using FillTypeMassAdjustment. I will try to disable it and try then. Anyway, thanks and sorry for your trouble.

**Comment by pops64** [comment]
You could change line 563 to `refSpeed = 30`  which will switch speeds to the default field speed when the combine reaches the point where it tries driving to the combine 50 meters or so

**Comment by blaz62746** [comment]
Thanks again for your response and help. I did what you said and it didn't work. Before I did any changes to the CP code, I tried disabling all mods except CP and I still had the same issue, most likely 'cause of high field speed which I don't want to reduce. But I did some trial and error editing to the mode 2 file and now I came to solution that works very good. I also brought back old chopper maneuver (from one of the older versoins of CP because new one doesn't work for trailers with dollys) and disabled reversing when auger wagon finishes unloading combine at the very end of field (infinite reversing with  tractor; my guess is that it can't get to the desired waypoint).
Now I would like to ask for some little more help. The following picture shows how tractor is positioned after it unloads combine, waits for combine to make free space and then gets to waypoints. However, if this happens at the end of the field, tractor is blocking combine when it comes back in the next row on the left. All I want to adjust is to make a tractor with auger wagon go a little more forward lined up with straw that combine left behind. I know I need to adjust some things in state 9 or state 5 in the mode2.lua, but I don't know which one. If you could help, I would appreciate it a lot.
![fsscreen_2018_09_28_22_39_42](https://user-images.githubusercontent.com/26365587/46234794-2d66be00-c378-11e8-88f2-91d309854f2f.png)

**Comment by pops64** [comment]
If you update to the latest version of CP of turn off turn on field this will use the old turn manuvers. I'll look where to adjust that tommorow if I got time and internet. Look for add target vector I think the 3rd variable is the length.

**Comment by blaz62746** [comment]
Thanks for the info. And you don't have to bother about my last adjustment. I figured it out and changed (totalLength*3) to (totalLength*5) in line 716 and now it all works as I would like to.
