### ISSUE TITLE
Add custom keypress to wait command

### ISSUE THREAD

**Issue by Elodrian** [Courseplay/courseplay#2875]
Hi there, is there a way or any Plan to add a predefined keypress to the waiting stop to be able to use CP on Maps with custom Trigger to load/unload
regards, Elo

**Comment by pops64** [comment]
Which custom triggers?  I just added the factory script mini store seed and fertilizer. And probably will work with other factory seed and fertilizer in mode 4 just has long has they are separate triggers. I haven't tested the silo seed n fertilizer

**Comment by Elodrian** [comment]
al lot of maps or factorys use the r key to unload and no "normal" unload icon appear so i cant deliver with cp

**Comment by Elodrian** [comment]
most times i need that keypress is with liquids like liquidManure Water etc. so i have to use normal drive mode and wait trigger to press that key myself
the maps are a mix of factory and mycompany scripts, the maps im currently on have its own system called Manuscript GT written by a russian, SibAgroCom and the Gifts of Caucasus (Kavkaz).
and sry i have no idea whats mode 1 or 4

**Comment by pops64** [comment]
Mode4 is seed and fertilizer. Mode1 is grain transportation. Mode numbers go left to right. I see what you're saying. I thought we had a key press for that. Will put it on the list to look at in the future or maybe @andy73 can do something

**Comment by pops64** [comment]
Closed #2909
