### ISSUE TITLE
Pre collision detection 

### ISSUE THREAD

**Issue by kahunas** [Courseplay/courseplay#2877]
Would it be feasable to have an arrray of tractors x,y locations updating so each tractor could check to see if a tractor is going to be in the same area ...then you can use the rules of big tractor gets right of way ..so the small tractor in question would get the allowedtodrive false until the big tractor is so far away from collision

**Comment by pops64** [comment]
I think this was attempted in the past and turned out to be CPU heavy. We may revisit this in the future

**Comment by kahunas** [comment]
I thought so thanks for the reply

**Comment by kahunas** [comment]
I havent done alot of game programming so forgive me im learning 
I have made android apps and mostly pc apps for myself so i find gaming a little confusing at times lol 
But i was thinking 
Trctorsrunning list {}
If self px py less than or equal to for each tractor running 
If self size < tractorrunning.size 
Stop moving 

So maybe instead of keeping track of tractors px py we instead keep track of moving ones and not thier locations 
And like i said some of game programming is alien to me but the game keeps track of this already right 
So maybe this will be less cpu intensive

**Comment by kahunas** [comment]
Oh and i would love to write something and check it i am a truck driver by day and programme at nights

**Comment by pops64** [comment]
We would probably set it up to only look at the field the tractor is on to cut down on cycles. And look at direction of travel and distance to each other. And only worry about the ones that are closing. Though none this will probably happen before 19 comes out

**Comment by pops64** [comment]
Closed #2909
