### ISSUE TITLE
mode2 unloads combine during turn

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#2878]
When mode2 is in follow waypoints mode it will stop the combine from turning if in the middle and attempt to unload it which causes bad behavior has the combine is aligned to the field which causes all the other code for mode2 to not work right. pathfinding is on
![fsscreen_2018_10_05_19_06_20](https://user-images.githubusercontent.com/10678220/46563851-d90c9280-c8d1-11e8-85e1-8fbce7d7689f.png)

**Comment by Randy1214** [comment]
Im having this issue also on mode3, then the tipper turns around to go park and wait and sometimes ends up in a totally different field because of how the combine is facing.

**Comment by pops64** [comment]
Yea mode2/3 are the same when on the field. Only when unloading is there any difference

**Comment by pops64** [comment]
Closed #2909
