### ISSUE TITLE
Driving forwards after driving backwards issue

### ISSUE THREAD

**Issue by JordyvA** [Courseplay/courseplay#2879]
Hi all, 
I'm using the reverse option to get the grain inside the tip trigger. The reversing works like a charm (I've drove the course without the trailer), but when it goes forwards, it drives straight into the compost. The course seems to be correct, which debug channel can help you guys? BTW, I'm using a combined course for it.

![image](https://user-images.githubusercontent.com/4558607/46569482-2c282900-c956-11e8-89b4-3073393734c0.png)

**Comment by pvajko** [comment]
12 and 13

**Comment by pops64** [comment]
No debug channel is necessary. Your course leaving the trigger is incorrect. You must drive straight out of the trigger till your at least the distance of the full vehicle(including the length of the an imanganary tipper) away from the trigger. It looks for the next waypoint in front of the vehicle after unloading. If there is none random behavior occurs

**Comment by JordyvA** [comment]
Thanks @pops64 It's working now! Sorry for your time.
