### ISSUE TITLE
Course Planning starting in wrong corner.

### ISSUE THREAD

**Issue by DoyleChris** [Courseplay/courseplay#2881]
When i go to make a Course i select the field like normal, then staring corner (NE,SE,SW,NW: New) and i select start direction.  With a Headland selected it dosent matter which direction i go for the headland.  The course planning puts my start point opposite where i want it.  

Example So i go to plow field 1, i select field 1, with it starting in the NE corner Heading south and creating  a headland after i do the lanes.

The course is created with me starting in the opposite corner.  Which is hard because i start all my fields from one corner for Plow, Cultivating, seeding, and harvesting. so i can start right away with the next process.
![course](https://user-images.githubusercontent.com/14863729/46585925-51479500-ca45-11e8-8894-11c5f7351e76.png)

**Comment by pops64** [comment]
Read next to the south west corner. It says Ending Location. When starting on up/down rows with headlands the location is the ending spot. It auto selects the starting spot based upon this.
