### ISSUE TITLE
Seeder missing bits

### ISSUE THREAD

**Issue by Randy1214** [Courseplay/courseplay#2882]
What would cause my seeding course to miss bits only when turn on field is deactivated. When turn on field is activated everything works well. Is it the seeder i'm using or a problem in the code?

![courseplay](https://user-images.githubusercontent.com/43734265/46617756-96260700-caeb-11e8-946e-782a812170c1.png)

**Comment by Randy1214** [comment]
Would adding some kind of of offset fix this?

**Comment by pops64** [comment]
Is that a modded tool? Do you have your turn speed maxed out? Is there a steep hill? Is the tractor underpowered for that tool?Any number of things could affect this

**Comment by Randy1214** [comment]
Base game tool, turn speed might be a little high, no hill, tractor barely underpowered. Ill try to adjust the turn speed next time i seed

**Comment by pops64** [comment]
Yea thats 9mph. If I remember correctly that tool doesn't wait to lower so at turn on field disabled it is chugging along at 9mph which will skip bits. I usually keep them at 6mph or 12kph and don't have any issues.

**Comment by Randy1214** [comment]
Ill try it at 12kph next time
