### ISSUE TITLE
Mode 2 doesnt unload completely

### ISSUE THREAD

**Issue by nuu5t1k** [Courseplay/courseplay#2885]
Hi. 
My problem is that silage trailer doesnt unload grass into silo completely. Always some tiny bit left in tipper. Some tippers work correctly. I was wondering what could be the issue. I cant manually unload at any silo. But i can tip it outside silo anywhere. It really pisses me off because the leveling tractor takes the grass bit and drives in silo for leveling. But chaff wont be loaded if grass is already on blade. So dead end. 

What can be done with that? Thanks.

**Comment by pops64** [comment]
#2570 #2661
