### ISSUE TITLE
Mode 4 - does not find an additional course.

### ISSUE THREAD

**Issue by Blackmankot** [Courseplay/courseplay#2886]
Good day! Refueling of seeds and fertilizers was performed perfectly up to version 5.03.00012. Sample video with version 5.03.00007.
https://yadi.sk/i/zin_uz91PqkHDQ
In version 5.03.00012 refueling does not work, transport does not find a course.
Video - https://yadi.sk/i/JrNdIdXshWYKTA
The same problem in version 5.03.00026
Video - https://yadi.sk/i/-ed2n3_Nh1obkA
This problem is present in version 05.03.0027
Video - https://yadi.sk/i/yAsb4WWWGeV0zA
Thank you so much for your work!

**Comment by pops64** [comment]
#2786
