### ISSUE TITLE
Lua error when Tank is empty

### ISSUE THREAD

**Issue by Friendlyx** [Courseplay/courseplay#2888]
Hi, I get a Lua error and a never disappearing message when Tank of Sowing mashine is empty or slurry tank is empty, but i have a refill course added and the tractor is going to refill.
![fsscreen_2018_10_15_15_21_52](https://user-images.githubusercontent.com/6493968/46953533-67310780-d08e-11e8-8721-03bd7cd551d2.png)

**Comment by pops64** [comment]
Full log please https://github.com/Courseplay/courseplay/wiki

**Comment by Friendlyx** [comment]
<script src="https://gist.github.com/Friendlyx/785409e28344cb6bfa5b459b0dba9815.js"></script>

**Comment by Friendlyx** [comment]
https://gist.github.com/Friendlyx/785409e28344cb6bfa5b459b0dba9815

**Comment by Friendlyx** [comment]
Now I have the again a slurry course with refill and no lua error but still never ending info messages on top right 
![fsscreen_2018_10_15_18_56_47](https://user-images.githubusercontent.com/6493968/46965860-4081c980-d0ac-11e8-9c37-4e7fae6c2899.png)

**Comment by Friendlyx** [comment]
Issue is there again with mode 4
