### ISSUE TITLE
Experimental Drive Mode

### ISSUE THREAD

**Issue by pvajko** [Courseplay/courseplay#2889]
In case you wondered what this experimental drive mode in 5.03.00034 (https://github.com/Courseplay/courseplay/commit/eb541548e06640699c61ac64d995c4707e763bd1) is:
![ppc](https://user-images.githubusercontent.com/2379521/46985579-c3a51e80-d0b0-11e8-9269-f751439fcb5b.png)
This a simplified implementation of the pure pursuit algorithm to follow a two dimensional path consisting of waypoints as described [in this paper](https://dspace.mit.edu/handle/1721.1/42301), the main motivation was to prevent the dreaded circling but is also part of our ongoing code cleanup effort.

I'd really appreciate if some of you would try this new experimental mode (normal mode reverts to the old algorithm) as I couldn't spend enough time testing it. 

Note that the new algorithm is **not active** during turn maneuvers, reversing with trailer, the pathfinding (mode2, 4, 6 on the field) and shovel mode (yet:).

If you do try it and find any issues, please report it here, if possible with debug channel 12 turned on.

Thanks, 
Peter

**Comment by Blackmankot** [comment]
@pvajko  Good day. Tell me, in what situations is it better to test?

**Comment by Friendlyx** [comment]
whats the meaning of  "too far"  and the "too far initializing" ?

**Comment by pvajko** [comment]
@Blackmankot it is *not* active during reversing with trailer, the pathfinding (mode2, 4, 6 on the field) and shovel mode. Other than that it should be telling which direction to drive and when to switch waypoints.

**Comment by pvajko** [comment]
@Friendlyx 'too far initializing' is case i _First Node Outside Virtual Circle_, 'too far' is case iv _No Intersection Points_ in the paper I linked. 

Basically the moving goal point can't be established so the vehicle is driving towards the next waypoint instead of the goal point.

**Comment by pvajko** [comment]
@Friendlyx oops. That was a mistake, I always have debug channel 12 on did not notice that. Thanks.

**Comment by Liquid515** [comment]
in both drive modes   with seeding and fertilizing ..it turns circles at the end

**Comment by pops64** [comment]
At the end of what? Normal drive shouldn't be doing this

**Comment by Liquid515** [comment]
well its doing it in both  for some reason.

**Comment by pvajko** [comment]
@Liquid515 ever thought about posting a log with debug channel 12 as I asked in the first comment?

**Comment by Liquid515** [comment]
ok  ill do that in both drive modes and then send the log file

**Comment by Liquid515** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/2484635/log.txt)

**Comment by Liquid515** [comment]
sorry about that...a lot going on around me lol...hope that helps

**Comment by pops64** [comment]
Could we get a picture or video of where and when the circling is occuring

**Comment by Liquid515** [comment]
[video.zip](https://github.com/Courseplay/courseplay/files/2485013/video.zip)

**Comment by Liquid515** [comment]
sorry if video wasent all that great all I have to use for it is my phone

**Comment by Liquid515** [comment]
last version I was using befor 34 was 26  and was working fine

**Comment by pvajko** [comment]
Thanks. This is not a problem with the experimental mode as it happens during a turn maneuver.

**Comment by Randy1214** [comment]
Does a new course have to be generated for the effects to work?

**Comment by Liquid515** [comment]
ok.. I know now how to send a better video  I can make one from start to finish if needed

**Comment by pops64** [comment]
No just enable it will work for all courses minus what pvajko said earlier

**Comment by pops64** [comment]
@Liquid515 you have a separate problem not related to this. Please make a separate issue about it. Video with debug channel 12 and 14 needs to be active in that video  and post a log. My guess is the turn speed is to high. https://github.com/Courseplay/courseplay/wiki

**Comment by Liquid515** [comment]
found it is not the turning speed but field speed...cant do 31mph any more  lol..the changes you guys have made effects that now..at 25 no problems

**Comment by pops64** [comment]
@pvajko there seems to be a HUD update problem with enable variable. It says normal and I click on it doesn't seem to change. Tho debug channel 12 says it is. Maybe missing a HUD refresh call 
![fsscreen_2018_10_16_21_12_57](https://user-images.githubusercontent.com/10678220/47055999-4f3dae80-d188-11e8-92bc-ca70afbec675.png)

**Comment by pops64** [comment]
Also seems to not handle the transition back to unload route after taking pathfinding off the field. I were to guess it is missing a `self.cp.ppc:initialize()`  in the abortWork function? 1356 to 1404 in vehicles
![fsscreen_2018_10_16_21_35_39](https://user-images.githubusercontent.com/10678220/47056671-8f526080-d18b-11e8-8b66-3c66dc24c952.png)

**Comment by Liquid515** [comment]
pops...I found the actual problem it was the turning circle it was on auto at 16m went up to 18m  now im back at my working speed...thanks for looking into it guys

**Comment by Friendlyx** [comment]
![fsscreen_2018_10_17_13_40_28](https://user-images.githubusercontent.com/6493968/47083880-47c2e780-d212-11e8-8beb-387d40b9880b.png)

The courseply driver stopps with endless messages in both normal and experimentel mode instead of going on to the reload course. No errors in Log ( as the endless messages might got fixed before the implementation of the experimental mode maybe this fix got lost )

**Comment by Friendlyx** [comment]
after game restart tractor tried to drive to refill course bvut got stuck going circles.
![fsscreen_2018_10_17_13_50_32](https://user-images.githubusercontent.com/6493968/47084491-e9970400-d213-11e8-8800-013fa4f06102.png)
log:
https://gist.github.com/Friendlyx/51ed4350eae355825bb4da86d5acb9c1

**Comment by Randy1214** [comment]
Im pretty sure they said the new algorythm is not active during pathfinding in mode4 yet

**Comment by Friendlyx** [comment]
ahh ok got it now

**Comment by pops64** [comment]
When merge courses together if waypoint is really far away it wiggles when reaching the next WP https://pastebin.com/8X134umn
![fsscreen_2018_10_17_13_35_38](https://user-images.githubusercontent.com/10678220/47105614-6de88780-d212-11e8-8d8d-cae0381a4784.png)
https://www.dropbox.com/s/w20dx2zq64ft4ex/Farming%20Simulator%2017%2010_17_2018%2013_39_27.mp4?dl=0

**Comment by andreasthu** [comment]
with the experimentqal mode i cant use my mode1 courses from my grain silo to the sellpoints.
the traktor (plus tipper) stands still before he reach waipoint1 (and also before he reach the pipe)
lg
andreas

**Comment by pvajko** [comment]
Danke Andreas, I'll take a look at that this weekend.

**Comment by andreasthu** [comment]
oh thanks,
here are two pics, one with normal mode, the trailer was loade correctly,
the other with experimental mode actice, the tractor stands under the pipe - not the trailer - and so it cant be loaded
[url=https://abload.de/image.php?img=fsscreen_2018_10_19_1hcidl.png][img]https://abload.de/thumb/fsscreen_2018_10_19_1hcidl.png[/img][/url]

[url=https://abload.de/image.php?img=fsscreen_2018_10_19_199cgk.png][img]https://abload.de/thumb/fsscreen_2018_10_19_199cgk.png[/img][/url]

greets
andreas

**Comment by pops64** [comment]
I think this problem is cause mode1 will stop when CP wants to advance to the 2nd waypoint thinking that you are loading with a front loader or such

**Comment by pops64** [comment]
Reverse doesn't switch to forward after unloading and continues backing up until end of reverse section in experimental mode. In normal it switch to fwd after unloading is complete

https://pastebin.com/dDaisiKU
https://www.dropbox.com/s/4f0im85etporlap/Farming%20Simulator%2017%2010_22_2018%2016_38_54.mp4?dl=0

**Comment by andreasthu** [comment]
> 
> 
> @andreasthu try with v5.003.00041 and report back.

testet with v5.03.00042 and it works
lg
andreas

**Comment by Randy1214** [comment]
Not sure if that was implemented with experimental drive but i noticed that now when a tractor heads for its unload cpurse it will start the unload course at the closest waypoint instead of of the first which is great! Only problem is that with irregular fields it still goes straight to the waypoint without considering the field border and can sometimes run into trees on the edge of the field.

**Comment by pops64** [comment]
It should always head to waypoint 1 then if align waypoint is enabled it will straighten out(enabled by default). if the course is going 180 in the other direction it will skip waypoints until it finds one that wont cause circling after arriving close to waypoint 1.  It shouldn't even be skipping the first one(or second depending on the mode)

**Comment by Randy1214** [comment]
I have seen it a few times head for the closest waypoint and sometimes thats like waypoint 80. But i cant seem to figure out in what conditions

**Comment by pops64** [comment]
Closed #2909
