### ISSUE TITLE
Courseplay crop destruction

### ISSUE THREAD

**Issue by Venzy123** [Courseplay/courseplay#2890]
Just wondering if there is a way to enable crop destruction when using courseplay?? 
Please help 
Thanks.

**Comment by Tensuko** [comment]
Crop Destruction is a Mod from ModHub. Got nothing to do with CP.
What you can activate in CP is Fruit bypass.

**Comment by pops64** [comment]
No, if you have the mod CP turns it off at user request to turn it off when CP is running. If you add `--` at the beginning of line 513 and 734 this will enable it for you. As we currently do not have a setting for this
