### ISSUE TITLE
Dedicated Server Tractor dont drive

### ISSUE THREAD

**Issue by TheKingOetzi** [Courseplay/courseplay#2893]
Hello
I play on dedicated server with courseplay 5.03.00037
When I start a vehicle with cp nothing happens and you can no longer control a vehicle

[log.txt](https://github.com/Courseplay/courseplay/files/2489002/log.txt)

**Comment by janhuddel** [comment]
Yes, I have the same problem. Is there a working CP-Version with multiplayer-support?

**Comment by pops64** [comment]
Closed #2909
