### ISSUE TITLE
mchale 998  Mod bale wrapper

### ISSUE THREAD

**Issue by Randy1214** [Courseplay/courseplay#2894]
Does anyone want to take a bit of time to take a look at the mchale 998 mod to see if it can be compatible with courseplay?

Right now it does not stop when the bale is loaded onto the wrapper and does not unload either so i have to wrap all my bales manually.

If its not too hard it would be very appreciated, thank you

**Comment by Randy1214** [comment]
Okay well does anyone know if the square bale wrapper in the kuhn dlc is compatible? I dont want to pay 20$ and then not have it work either

**Comment by pops64** [comment]
Before you do that. Do you have a clean link to the mod in question

**Comment by Randy1214** [comment]
https://farming-simulator.com/mod.php?mod_id=111224, ill be out of service for 4 days ill check the thread when i get back

**Comment by pops64** [comment]
[specialTools.zip](https://github.com/Courseplay/courseplay/files/2497028/specialTools.zip)

**Comment by Randy1214** [comment]
Ill test that out when i get back. Thanks alot

**Comment by Randy1214** [comment]
And did you test it?

**Comment by pops64** [comment]
Yes it works.  if special tools gets updated in the future lines 397-400 line 667 was changed to` if workTool.cp.isUrsusZ586 or workTool.cp.isKuhnSW4014 or workTool.cp.isMchale998 then`, and 969 to 972 was added just added those to the same location in the code and change the above line back to that. I probably wont merge this into the main branch as special tools was designed to be easy enough to alter to accommodate the sheer number of mods out there

**Comment by Randy1214** [comment]
Okay perfect
