### ISSUE TITLE
Field size limit?

### ISSUE THREAD

**Issue by Brille78** [Courseplay/courseplay#2895]
I´m in the process of making a X64 map, but every field larger than ~800ha isn`t detected correctly in the course generation part, this is a screenshot of a 1200ha field course (it´s a square field)
![map generation](https://user-images.githubusercontent.com/33186262/47237018-1d258a00-d3de-11e8-9728-187537b5bacf.jpg), it doesn´t matter if i use 1 or multiple tools in the generator.

**Comment by pops64** [comment]
That is most likely cause the field scanner tool will stop scanning when it reaches a certain size(To prevent memory leaks and other bad things that come from inf loops). If you manually scan that field you will see that there is a gap. I also know there is a block limit in the new course gen but if your using a square field that shouldn't be an issue
