### ISSUE TITLE
issus for better handling the startpoint of fieldwork

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#2900]
hey guys
i have an issue for better handling the starting point in fieldwork (mode  4 and 6)
there are many startingpoints to set
SE, SW, NE, NW, S-E, S-W, N-W, N-E, aktual point, automatic point,............
we can chose them to click with the mouse on it.
if i klick one time o much, then i must klick this many points also, to find the right.

is it possible, or my idea, to make set the staring points also we can set the fruits to fill in mode1?
with the mouse scroll wheel?
forward and return
(yes i know, there is also the new graphical screen, but here i am oldschool)

lg
andreas

**Comment by pops64** [comment]
I have made the switch to using the GUI one cause the GUI has this option. Two any new features added to the advance course gen will only be implemented through the new GUI. Making changes to the old HUD is a PITA. I will look into putting this change into the old HUD but I would highly recommended changing to the GUI.(I can select which field instantly, I can select the starting point with out having to be there, I can see the course on the map before leaving the GUI so I know if it won't work right then etc. Peter did a very good job on the new GUI)

**Comment by pops64** [comment]
Just looked it over. And has I suspected it not going to be an easy thing to change. Will mark this has a postponed may be something we will fix in 19.
