### ISSUE TITLE
Missing bits on headland

### ISSUE THREAD

**Issue by Randy1214** [Courseplay/courseplay#2903]
Is there a way to avoid the tractor from missing bits when doing a sharp turn in the headland. It seems like the corners are too sharp for the tractors turning circles and it misses some bits at every corner. Is there a way to add in the option to have a start and end turn at every turn to avoid this problem?

And its not just tractors, its also the combines

**Comment by pvajko** [comment]
You can set the headland (corners) in the HUD or in the Advanced Course Generation GUI to:
- 'round': this will make sure the innermost headland has no sharper turns than the turning radius of the vehicle, therefore, this will leave the corners of a field unworked, or,
- 'turn' which will make a turn maneuver on the headland corners.

**Comment by Randy1214** [comment]
Ive tried to set it on turn and it never once made a turn maneuver. The only thing it seems to change is when it finished the headland and starts the up and down. Thats when it puts a turn maneuver instead of a smooth transition

**Comment by Randy1214** [comment]
![image](https://user-images.githubusercontent.com/43734265/47625365-0d532780-dafb-11e8-88d3-72108e8a9ec2.jpg)
![image](https://user-images.githubusercontent.com/43734265/47625440-99fde580-dafb-11e8-8cab-e56e2f105a50.jpg)
![image](https://user-images.githubusercontent.com/43734265/47625483-d16c9200-dafb-11e8-8de3-c948188090ac.jpg)

This course was generated with turn selected and it does not have a single turn maneuver in the headland. And the sharpest corner in the field is butchered every time

**Comment by Randy1214** [comment]
I just tried another course with round selected and again it didnt change how the course was generated. I think it might be a bug

**Comment by pops64** [comment]
if hit the print screen button on you computer it will save a image of the game to `C:\Users\*usernamehere*\Documents\My Games\FarmingSimulator2017\screenshots`
In the picture you linked it appears that the one corner is not 90. I am not sure of the angle it has to be but the headland turn maneuver is designed for when it can't make the turn nice aka a square field edge. I would just recommend using the round(turn radius option). This does leave a bit unworked at the edge of the corner but you could always delete that part of the field or use less headland

**Comment by Randy1214** [comment]
On that specific field there is 3 90 degree corners and the one corner in the screenshots is more then 90 degrees so there should be a turn maneuver there. Even on perfectly square fields it does not put a turn maneuver.

**Comment by Randy1214** [comment]
Is it because the field corners are a tiny bit rounded off?

**Comment by pvajko** [comment]
Yes, that's a tricky corner, not just rounded off but also concave. The round option is the only one which should work without leaving crop (except in the very corners of the field). Our generator isn't intelligent enough yet to use different settings in different corners.

**Comment by Randy1214** [comment]
The generator should check to see if the radius is too small for the vehicle and if it is then put a turn maneuver. Just like it does with the round option but instead of changing the corner. Add a maneuver
