### ISSUE TITLE
problem with sugar cane planter

### ISSUE THREAD

**Issue by Hrala** [Courseplay/courseplay#2904]
Good Night, I have a problem with the sugar cane planters, when they arrive at the waiting point to load, they do not lower the bucket to be able to load and the loader can not carry with it raised
![fsscreen_2018_10_29_20_08_46](https://user-images.githubusercontent.com/41400636/47686004-bb240c00-dbb7-11e8-9e01-361fde3076d5.png)

Sorry for my bad english, google translate :(

**Comment by pops64** [comment]
This is actually nothing we have control over, It is a function of the hired worker. AKA when attached to a hired worker the position is determined by the fill level. The closer to zero the higher it gets. There actually is a Giants bug with the smallest one were the sugar cane is not accurately show in the planter. So it is not something we are going to be able to fix in the short time before 19 comes out.(Most likely have to fire the worker to release the planter back to normal control which might lower the bin then re higher the worker but this is something I do not know how to do as there are lots of CP functions that rely on  CP having a hired worker). Also it should still be able to fill it in the raised position you just need your wait point for fill not right before the stop point. I would recommend at least 5 before the stop
