### ISSUE TITLE
Steam fs17 COurseplay multiplayer

### ISSUE THREAD

**Issue by jpoblocki77** [Courseplay/courseplay#2905]
when i go to plant and to cultivate course play seems to skip rows leaving huge patches of untouched land

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by jpoblocki77** [comment]
How is the log from my local game going to help dont you want the log from the server?  I mean i would think a server log would tell you more then anything else would.

**Comment by pops64** [comment]
Both. This is most likely a nil or index error of some kind with out a log we can't tell

**Comment by jpoblocki77** [comment]
Server Log https://pastebin.com/5TQwQZrC

Clientside Log https://pastebin.com/c4GhN4dZ

**Comment by jpoblocki77** [comment]
When I do the cpsallfielfds or whatever it is nothing generates on my pc  and i do not have FTP access to the server so if you can tell me where on a server it generates ill see if they can send me the files

**Comment by pops64** [comment]
Closed #2909

**Comment by jpoblocki77** [comment]
And why did you close the thread?

**Comment by pops64** [comment]
#2909
