### ISSUE TITLE
Mode6 Auto Baler Stackers now work with multiple unloades 

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#2906]
Alright the Auto Baler Stacker will now place bale stacks 1.5 m apart center to center for the vanilla round stacker. and 3 m center to center on the middle of the drop point for the square stacker. Plus or minus a bit depending on reversing speed. All mod stacker will be placed 5m apart center to center unless a value is set in special tools. For unload course with stacks already placed the start distance from the wait point can be set with the unload point distance variable found on the combine page setting

See pictures below for clarification. Ensure you still are using wait point to indicate where the first stack is dropped. And ensure you have enough straight line distance to accommodate all the stacks planned to unload. 
![fsscreen_2018_11_06_00_20_58](https://user-images.githubusercontent.com/10678220/48044574-9cdf8280-e15a-11e8-90ef-b859122c8bff.png)
![fsscreen_2018_11_06_00_21_29](https://user-images.githubusercontent.com/10678220/48044577-9f41dc80-e15a-11e8-9665-bdc383139e79.png)

EDIT: So if I were to resume this hay unloading course above once everything was set up I would put in 3 meters into the variable circled in the first picture has this is the distance away from the initial drop point. If you have the square stacker don't forget it does double rows at once which is why it is 3m center to center each row is 1.5m for both square and round

**Comment by NexX0** [comment]
That's pretty nice but what happens if i remove the first Bale Stack will the next Stack still be placed in front of the first Stack ?

**Comment by Tensuko** [comment]
Guess so. Should work like a counter of unloads that adds +X Meter per count.

**Comment by pops64** [comment]
Yea, has @Tensuko said. I did a crude system just to get it working. Our future plans for it would be to detect were the bales are instead of relying on user input but I figured that most people aren't removing the bales will CP is placing bales. Maybe once 19 gets stable I will stick in a hud option some where that will do the old system

**Comment by pops64** [comment]
I will this open for a few more days before I close this for #2909
