### ISSUE TITLE
Low Combine Speed with MR

### ISSUE THREAD

**Issue by snoopdoggtg** [Courseplay/courseplay#2907]
What's going on with the low working speed of combines in fieldwork mode? They are just driving like crazy into the crops and then their speed just stays at 3kph which is about 50% of the speed they should go. It only happens while playing with MR, without it everything is fine. Is there any fix to this issue?

**Comment by pops64** [comment]
Type in debug if you have the dev console enabled you will see the combine speed limit on the right hand side which should be about 5 to 6 kph with matching combine/header per store. If you drive with out CP it will still be 3kph assuming you are taking the same swath has CP. This isn't our problem but MR. I have tested this numerous times. If you want you combine to go faster. Either go with a bigger combine and smaller header or reduce the fertilizer rate of the field or reduce the workwidth. The combine can only process so many tons at a time. The only difference you may notice is down hill. CP will stick to the speed limit. When your driving down hill the gravity will let you go beyond the speed limit but when you level out MR will cut you down to about 1kph until the combines caught up

From https://www.fs-uk.com/forum/index.php?topic=195659.0

> - engine power is now useful on combine (no more "smart" to use a bigger header on a smaller combine). The lesser the yield, the easier for the combine (limits are set by the combine "max capacity", the speed limit of the header and the engine power)
