### ISSUE TITLE
Closing All FS17 Issuses

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#2909]
We are closing all issues in preparation for FS 19. We will try to have a beta version as soon has we can but we all must have patience has the CP dev team does have real life stuff that takes precedented and we do not know yet what changes need to be made and time required to make those changes. We are also planing on refactoring major parts of the CP script which will take time. Thanks.

**Comment by Randy1214** [comment]
@pops64 if you need help with testing for fs19 id be happy to help

**Comment by pops64** [comment]
Now that FS19 is release we will no longer support FS17 has we are currently busy updating FS19 and then we will only have enough time to maintain FS19 after CP's release of v6. The community is free to update and/or fix bugs that never got fix and make pull requests to the FS17_Legacy Branch. Which we will review and possibly merge it into the legacy branch. Also if looking to download FS17 you may find it here https://github.com/Courseplay/courseplay/tree/FS17_Legacy
