### ISSUE TITLE
FS19 Course play

### ISSUE THREAD

**Issue by mdart83** [Courseplay/courseplay#2911]
Any known Versions of Course play that will work with FS19??

**Comment by pops64** [comment]
#2912

**Comment by Tommen72** [comment]
how do i download Beta 4 courseplay? its 4 FS19

**Comment by deeg427** [comment]
im also at a complete lose as to how to install or download this beta version :(

**Comment by aszechlicki** [comment]
you just need to download source files and put them in a zip archive inside your mods directory
