### ISSUE TITLE
Previous versions of CP

### ISSUE THREAD

**Issue by fudoido** [Courseplay/courseplay#2916]
Hello team. just wondering if you guys will delete all the previous posts from fs17 as you did with fs15 when fs17 was released. some people still play the older games and sometimes is hard to get the appropriate version for their game, and I would like to know, if possible, if there would be a way to make an "archive" kind of  with the latest version of CP for each previous game, or at least start doing it from fs17 (since the latest build isn't yet lost).

I am requesting this because when fs17 came out , I was still playing fs15 and with the advance of cp to fs17 I was unable to get the fs15 version. sure I could get it from 3rd party sites, but wouldn't be the latest version. I do now own fs19, but some people is still playing fs17 and will come check for the latest fs17 CP. even if they already had it downloaded, they might lose it and cant get it back afterwards, hence why I am requesting a "archive" folder so that people can still come and get the latest version for theyr game. I know it will be unavailable for fs15 and previous titles as those CP versions are lost, but there is still time to save the latest fs17 build into an archive. maybe just put a download link with the zip file on the main page, even if from a 3rd party hosting service (like sharemods or other) instead of GitHub repository?

Thanks in advance guys. cant wait to see CP19 working. I volunteer for tester if you need one. ^^

**Comment by Glaeydar** [comment]
Hey,

you have to go to [releases](https://github.com/Courseplay/courseplay/releases) and select the version you want. Afterwards you must unpack the archive and pack the files directly that e.g. the modDesc.xml is directly present when you open the archive. 
mod.zip
| - modDesc.xml
| - register.lua
...

Hopefully I could held you.

**Comment by pvajko** [comment]
https://github.com/Courseplay/courseplay/tree/v5.03.00050

**Comment by pvajko** [comment]
I'm sorry, wrong link. Here's the correct one:
https://github.com/Courseplay/courseplay/releases/tag/v5.03.00050

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/tree/FS17_Legacy for any future updates and #2909

**Comment by Blackmankot** [comment]
@pops64 @pvajko  Good day. Please excuse me, I know that you are currently working on the version for FS-19. But in versions 5.03.00047 and 5.03.00050 there was a problem when combining courses. Here is an example of combining two courses using version 5.03.00043 -
![2018-12-02_15-25-27](https://user-images.githubusercontent.com/26131714/49337087-a4eeed00-f648-11e8-9df0-18e13b2f1806.jpg)
![2018-12-02_15-26-59](https://user-images.githubusercontent.com/26131714/49337092-aae4ce00-f648-11e8-8b53-f7de52759d3b.jpg)
![2018-12-02_15-28-15](https://user-images.githubusercontent.com/26131714/49337094-ae785500-f648-11e8-88e8-63fe79b8ce93.jpg)
![2018-12-02_15-45-24](https://user-images.githubusercontent.com/26131714/49337130-542bc400-f649-11e8-8c0b-b27afdd19d7a.jpg)
![2018-12-02_15-50-09](https://user-images.githubusercontent.com/26131714/49337221-eb454b80-f64a-11e8-923d-31249f27d3ef.jpg)
![2018-12-02_15-56-06](https://user-images.githubusercontent.com/26131714/49337222-f1d3c300-f64a-11e8-8f87-e3c4cfe6652d.jpg)

Here are the same courses combined in versions 5.03.00047 and 5.03.00050 
![2018-12-02_15-52-38](https://user-images.githubusercontent.com/26131714/49337239-3eb79980-f64b-11e8-9fc1-1ab1e8b80c95.jpg)
![2018-12-02_15-50-34](https://user-images.githubusercontent.com/26131714/49337245-50993c80-f64b-11e8-9a62-bf19064ae097.jpg)
![2018-12-02_15-48-32](https://user-images.githubusercontent.com/26131714/49337247-5b53d180-f64b-11e8-9d45-351e5d907559.jpg)
