### ISSUE TITLE
hud

### ISSUE THREAD

**Issue by druber** [Courseplay/courseplay#2920]
Your latest changes are AWESOME!  One thing I would like to see is a way to relocate the HUD display on the screen. I find it to be in the way many times.  It would be great if you could drag it to a different location, bu in lieu of that, just a way to set x,y coordinates would be excellent.

**Comment by Satissis** [comment]
already implemented since FS15.
Look in your savegame folder for the file: courseplaySettings.xml
In there you have the option so set the x and y setting.

**Comment by druber** [comment]
Thank you VERY much.  Guess I looked everywhere but there!
