### ISSUE TITLE
Feature Request: "curves" detection

### ISSUE THREAD

**Issue by fudoido** [Courseplay/courseplay#2924]
hello guys, good to know that CP v6 is well underway. take your time to make it work in fs19 and im ready to test it when 1st beta comes out.
just passing by also to give a sugestion, not sure if it can be considered a new feature, or if you can kind of "upgrade" the code for it.
as we know, courseplay places several waypoints along the courses to record and then execute them, and most of us noticed that when the vehicle is doing curves, said waypoints come closer toghether to guide the vehicle better in the direction change.
with that in mind, would be possible for courseplay ,some how, to make the vehicle detect those waypoints when it comes closer to them, and force a speed reduction on the vehicle to a certain speed.
this would be helpfull to make the vehicles go full speed whilde driving the course, especially long haul courses. max speed while course is fairly straight, but slowing down to 30-20 km/h (as an example speed, enought slow to change direction without slipping, but not too slow also) when it detects the curve and execute the curve at that speed, then going max again when leaving the curve to a straight course once more.
i know we can record the course with the speed we want and the vehicle will execute it at the same speed we record, but sometimes, while in traffic, we are forced to record it at the AI speed, and then it executes it at that speed also.
if we could set the course for max speed, but having the ability to "slow down" on curves, it would be great and prevent alot of the skidding and going off-course while at max speed, a litle bit like it does when aproaching a waiting point, and we could have the courses always running max speed instead of the limited recorded speeds due the several factors (such as AI traffic as i mentioned above).

so, something to consider, or it would involve too much of code breaking to make it possible in the med/long future? (im not expecting it possible soon, as you already have too much to deal with to make the basics work for fs19).

Thanks in advance for reading and hopefully reply :)

**Comment by Senutyenool** [comment]
@fudoido

To get around the 'forced' recording of AI speed, when plotting/mapping/recording (pick one) a new course on road simply turn of traffic before hand.  Make your recording, make changes (if needed) and turn traffic back on.  Simple 'workaround'.

But I do still like your suggestion as it makes sense IRL to slow down on corners and not go flat out.

Cheers

Cheers

**Comment by pvajko** [comment]
The way we use the Giants API in FS19 already provides this function, we'll see how good that works.
