### ISSUE TITLE
small k turn issue

### ISSUE THREAD

**Issue by druber** [Courseplay/courseplay#2926]
Firstly, you guys have done an awesome job with the latest FS17 cp changes.  I am having a problem with the tool being lifted too early, and lowered to late such that a small area is not covered.  Also, in a k turn, the tractor backs up much further than is necessary which requires more headland rows than necessary so that you don't back into a fence or tree or something.  An example would be when using the Amazone Cayron 200 plow.  Many others must be having the same issues, but I could not find that these had been reported before.  Again, thanks for the best of mods!  @druber

**Comment by Satissis** [comment]
We stopped working on the FS17 version when we got FS19 and wont do anymore work on it.

**Comment by druber** [comment]
OK thanks.  It is so much better than it was that I can live with a few minor problems!

**Comment by druber** [comment]
Thanks much I can easily work around any small problems I have

**Comment by Satissis** [comment]
Np mate ;)
