### ISSUE TITLE
Seed Usage Calculator Broken

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#2928]
`2019-01-26 19:50 Error: Running LUA method 'draw'.
2019-01-26 19:50 C:/Users/Ryan/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/hud.lua:516: attempt to index field 'selectedFruit' (a nil value)`

Clicked on the auto workwidth. I think don't remember.

**Comment by pvajko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by pops64** [comment]
https://pastebin.com/xQ1GEwa2 :P

**Comment by pvajko** [comment]
Issues with no description of how to reproduce them will be ignored and deleted.

**Comment by PromGames** [comment]
![image](https://user-images.githubusercontent.com/9979168/51801407-81f24b00-223d-11e9-9846-bcf95ac315d6.png)

Thats the message that appears in the log and the screen remains green, no way to get out from there in the vehicle.

**Comment by ThomasGaertner** [comment]
try v00003 or higher and report

**Comment by PromGames** [comment]
Sorry @Satissis 

Here you can see that Area Unit (Hectáreas in Spanish is working for automatic scanned fields

![image](https://user-images.githubusercontent.com/9979168/51806224-b4b93500-2277-11e9-8a13-9ad17c73bd77.png)


But not working for custom fields

![image](https://user-images.githubusercontent.com/9979168/51805964-2b543380-2274-11e9-874f-c4242575c92c.png)


System is looking for unit_areaShort in   l10n_es.xml

**Comment by Satissis** [comment]
To be honest, we haven't really checked over the calculation in FS19 and it's not critical atm so might have to wait a bit

**Comment by PromGames** [comment]
Thanks my friend, you can close it as the important things are solved.

Prom
