### ISSUE TITLE
Error on Custom Vehicle Type

### ISSUE THREAD

**Issue by duffstone** [Courseplay/courseplay#2930]
Using the Current beta version (v6.00.00033), the game fails to load the map,  presumably because of a custom vehicle type I've created.  The game loads and appears (in limited testing) to work fine if I remove the custom mod in question.  Attached are 2 pastebin links to the log & vehicletype in moddesc.  if you need more please let me know.   Posting so you'd know,  I don't expect a fix necessarily,  at least in the short term. :-)
-Duff
https://pastebin.com/id1v5fPA  --Log
https://pastebin.com/JaFSDyc6 --VehicleType

**Comment by ThomasGaertner** [comment]
so please try to fix your mod. I presume you would have more issues with it if its not set correctly ..

**Comment by Satissis** [comment]
Thanks @DeckerMMIV
I have accepted your pull request.

@duffstone please chech now with the latest version (Unversioned commit)

**Comment by duffstone** [comment]
Ok, the fix allows the game to load,  generates no new errors (log is clean),  but the courseplay hud doesn't open for that vehicle.   

looking at that code section, courseplaySpecName returns  "FS19_CourseplayBeta1.courseplay".  so you're executing: g_vehicleTypeManager:addSpecialization("dumpOverload", "FS19_CourseplayBeta1.courseplay")

I'm no expert,  but is that what you're wanting to do there?  The original line was expecting something like dumpOverload, FS19_GMC_C70_Dump.courseplay.   By changing it to the courseplay mod name aren't you assigning the type to courseplay instead of the mod name?   Again, no expert but it still doesn't look quite right.

Anyway,  looks like for the time being that any custom vehicle types won't be recognized.  No rush on a fix, just following up.
-Duff

**Comment by Satissis** [comment]
Nah the courseplaySpecName is the correct way to do it, since it's the courseplay specialization we are putting into that vehicleType.

Anyway, it could simply be the way that mod is setup that is preventing CP from doing what it needs to do.
You could try use the keyboard binding (default Ctrl + Delete) for opening the hud (which works even if it's set to use right mouse button)
If that don't work, it will have to wait until we are going into more mod support.
Right not it's basically only the default vehicles we are looking into or vehicles that are only using Giants default scripts/specializations.

**Comment by duffstone** [comment]
CTRL+DEL doesn't work either.   You guys got the custom vehicle type (in the original pastebin link), that's the only thing that's different about the mod from the original carFillable type.  when the time comes, if you need more from me than that just let me know.  I'll help out where I can.  Until then GL with the beta!
-Duff

**Comment by duffstone** [comment]
wanna add another bit I found, that mod causes this save game error as well,  remove the mod,  and the error goes away.  Also,  replace deckers change with my work around to ignore the mod, and it saves just fine.   attaching log FYI, but don't expect you to jump on it till you get around to the custom vehicle type stuff.   Just more info:
https://pastebin.com/gv7bwiD5
