### ISSUE TITLE
Forage harvester don't work

### ISSUE THREAD

**Issue by sperrgebiet** [Courseplay/courseplay#2931]
CP 6.00.00033
Vanilla Felsbrunn
Krone Big X1180

After generating a mode 6 course and start, the harvester just doesn't move at all. No matter if a tractor with trailer is controlled manually or by CP. 
In some past tests I had the issue that the harvester started, but never unfolded the pipe, or it expanded it for a couple of seconds and then folded it again.

Btw, tried the same with the Bix X1180 with extended or normal pipe, as well as with the New Holland forage harvester.

Log & Screenshot attached
[log.txt](https://github.com/Courseplay/courseplay/files/2799869/log.txt)
![fsscreen_2019_01_27_09_39_12](https://user-images.githubusercontent.com/20586786/51798783-25c90000-2218-11e9-849a-fb2b8273e368.png)

**Comment by Paul2510** [comment]
Hi! Have the problem that the harvester stops during the work when there is no fruit!
And there's the message coming             No attacher Joints

**Comment by marcospms** [comment]
With me, the harvester starts and stops or does not start and you need to start harvesting and turn on the courseplay to continue, but when you get to the point of the field it stops again

**Comment by pvajko** [comment]
@sperrgebiet give it a try with v6.01.00002 or later. Have not tested it much, not perfect but should be better.

**Comment by sperrgebiet** [comment]
Running on 6.01.00004 right now, and so far it looks good. The harvester is moving, so it's definitely alive :D
Consider this as fixed for now. Will keep testing and let you know if I encounter any additional issues.

Thanks a lot so far!

Cheers
_Hans
