### ISSUE TITLE
Problem with unloading

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/courseplay#2933]
https://gist.github.com/StefanBraun2001/21836dec6c94d7c85326a4c507ac5af0 Log

![screenshot 12](https://user-images.githubusercontent.com/47073128/51799266-a8a18900-221f-11e9-8c4a-c8566392536b.png)

When the helper reaches the unload point i sethe says, that he reachs the point, but he do not onload. He drives forward a bit and then the game freezes. Courseplay cant be opend. 

Tested it with the Map Nordfriesische Marsch + Ursus Bale Collector and one time on ravenport without any mods, same issue at both maps

**Comment by ThomasGaertner** [comment]
try 06.01.00001 or higher and report

**Comment by StefanBraun2001** [comment]
https://gist.github.com/StefanBraun2001/9f34c2513f3eb6a263ce23929c5dedaa
Still not working.
The helper opens the cover, but don´t unload the corn. Or the unload animation is there, but no unloading.

**Comment by StefanBraun2001** [comment]
Sometimes, after generate the course, the first time the unloading works, but then it doesn´t work

**Comment by ThomasGaertner** [comment]
could you give me your savegame and the course to test it ?

**Comment by BjoernSchuermann** [comment]
I do face the same Problem. Even manually setting an Unload Point doesn't help.

**Comment by StefanBraun2001** [comment]
Yes, of course. It is on Ravenport. Take the "Feld24 nach Farmsilo" Course and you should see it. Mode is 2 (Combi mode). 
[FarmingSimulator2019.zip](https://github.com/Courseplay/courseplay/files/2807625/FarmingSimulator2019.zip) (Sorry i uploaded it there, but i can´t upload it to gist for unknown reason)

**Comment by Flacwby** [comment]
Same issue here. CP won't unload at the Railway East Silo. It just passes on through as if there were no trigger point.

**Comment by ThomasGaertner** [comment]
@Flacwby : this is a different issue: in you case the trigger will  not be recognise . in this case it will and there is something with the tipping....

**Comment by ThomasGaertner** [comment]
so guys, to make it clear: if you wish to unload into a object (silo, train whatever) you may not set an unload point. if you want to tip onto the blank ground somewhere, you have to set an unload point.
would you pleas consider this ,test again and report, whether there is still an issue.  @StefanBraun2001 : when I delete the unload point in you curse, everything works fine...

**Comment by BjoernSchuermann** [comment]
@ThomasGaertner: sry i think i didn't describe it specifically enough. The first course i recorded did not contain an Unload Point. It worked for me till i saved the game and failed after continuing with that savegame. I then tried a couple of things and one was to record a new Course with that Unload Point.

**Comment by StefanBraun2001** [comment]
Sorry, own guilty, it works now.
