### ISSUE TITLE
Black screen when tabbing to E-Locomotive, Felsbrunn

### ISSUE THREAD

**Issue by Jaiimez** [Courseplay/courseplay#2936]
Started new map on Felsbrunn, no mods active except CP, Start from Scratch difficulty, when tabbing to the E-Locomotive I get a black screen, if I press E to exit it goes back to normal, can repeat multiple times, however after 4/5 times it crashed entirely, screen froze (not black) and required a reboot of the PC.

CP version: v6.00.00033

Hardware Specs:
[DxDiag.txt](https://github.com/Courseplay/courseplay/files/2800005/DxDiag.txt)
FS19 Log:
[log.txt](https://github.com/Courseplay/courseplay/files/2800001/log.txt)

Further update, opened another game on Ravenport no issues, just reloaded another new game on Felsbrunn and it's fine now, the train in this save I entered was in the north east of the map, around 2 o'clock, the crash happened around the Field 8, Field 16 area of the track just before the bridge.

**Comment by Jaiimez** [comment]
Further update, just started a game on Ravenport, and tabbing to the Diesel Locomotive has NO issues.

**Comment by ThomasGaertner** [comment]
could you please try again with the current version and report ? we fixed something for that...

**Comment by Jaiimez** [comment]
> could you please try again with the current version and report ? we fixed something for that...

I have just downloaded the newest version will let you know if the issue reoccurs.

**Comment by pvajko** [comment]
Closed due to inactivity
