### ISSUE TITLE
Combine Issues

### ISSUE THREAD

**Issue by stangman04** [Courseplay/courseplay#2937]
I am having an issue that when the combine (using the New Holland TX32) reaches the end of the row and turns for the next pass, the combine does not re-engage the header and it just slowly creeps forward. I have to stop driver and restart for it to continue cutting.

I am playing on the Michigan map and was cutting corn if that makes any difference.

**Comment by INDEFITY** [comment]
Hello, thank you for your work. Yes, it is true, but it does not manifest itself. as described by this person, the error manifests itself in the conditions
Stage 1
combine harvests (any crop)
Stage 2
bunker is full. a tractor comes to him with a trailer to unload too
Stage 3
combine unloaded. and then mows down culture. reaches the end of the field and turns around.
and stops. engine of the combine is muffled. and the worker disappears from the cabin. He writes in the journal error "no connection attacking"
Sorry for my English)

**Comment by androno12** [comment]
yeahh, same problem. 

> the combine does not re-engage the header and it just slowly creeps forward

**Comment by pvajko** [comment]
Would you guys mind trying with v6.01.00002 or later? I think one of the changes in that version may fix this.

**Comment by stangman04** [comment]
Will test now that I am ready to harvest soybeans...will let you know..

**Comment by stangman04** [comment]
> Would you guys mind trying with v6.01.00002 or later? I think one of the changes in that version may fix this.

I am running v6.01.00006 and it is working so far. I am cutting soybeans instead of corn so different header but it seems to be working fine. Appreciate your work in fixing this so quickly. If this returns I will let you know but as of now it looks good.

**Comment by INDEFITY** [comment]
thanks, everything works fine! I will test further if there are errors I will inform you

**Comment by pvajko** [comment]
7c144182374894a7fc404d61cf135d634fc4802c was the commit with the fix, practically reverting d27add5d367aba85e87820c8cc013954e30e6318 which most likely broke it.
