### ISSUE TITLE
bredal k165 fertilizer spreader with 6m extension (stock implement)

### ISSUE THREAD

**Issue by shadow250** [Courseplay/courseplay#2942]
possible courseplay issue:
it works if you manually fill it.  if you want to use a refill course it doesnt work as i expected.  
when it runs out it doesnt fold the extended spreader arms allowing it to hit stuff.

courseplay or possible mod issue:
it wont fill from the tower type stations i think because they require the cover to be opened and courseplay doesn't lift the cover. maybe the fill station modders need to fix this? 
edit: the stock towers also require to manually open the cover

**Comment by sootysax** [comment]
I am also having issue with the smaller K105 fert spreader.   The spreader does not shut off at the end of the row, just keeps spraying through the turn.

**Comment by pvajko** [comment]
Folding should be fine with 6.01.0006 or later. Maybe Thomas knows what's wrong with the filling.

**Comment by sootysax** [comment]
1.00006 fixes the extension folding.   I am able to load at triggers if I leave the lid open before I start the course.

**Comment by shadow250** [comment]
6.01.0006 fixed the folding issue, thank you :D   @sootysax it does load if the cover is left open but looks odd.

**Comment by sootysax** [comment]
This is also happening with the Pronto 9 DC seeder.   It will not refill unless you leave the lid open

**Comment by ThomasGaertner** [comment]
try with v 0013 or higher and report....

**Comment by shadow250** [comment]
"try with v 0013 or higher and report...."

it is working as expected now. Thank you for fixing it.
