### ISSUE TITLE
How do I get the beta?

### ISSUE THREAD

**Issue by bartjeman11** [Courseplay/courseplay#2946]
I really wanna play with cp but where can i download the beta?

**Comment by shadow250** [comment]
click the code tab and download zip

**Comment by sootysax** [comment]
https://courseplay.github.io/courseplay/en/installation/index.html

**Comment by Satissis** [comment]
![image](https://user-images.githubusercontent.com/314597/51804749-0906e980-2265-11e9-908a-5a34fb9033ea.png)

**Comment by bartjeman11** [comment]
i did put the zip in my mods in farming but i t doest work

**Comment by shadow250** [comment]
you have to open the zip and use the folder inside

**Comment by duffstone** [comment]
the downloaded zip contains a folder, inside that folder is the mod.  so take the folder in the zip, and copy it to your mod folder and you should be good.  You don't have to zip it,  I would recommend against it so it's easy to update.

**Comment by sootysax** [comment]
if you can't follow the instructions in the link above, beta testing CP is probably not gonna work out for you.
