### ISSUE TITLE
Does not start the worker on the mod map courseplay 6.01.00002

### ISSUE THREAD

**Issue by Alex198602** [Courseplay/courseplay#2949]
[log.txt](https://github.com/Courseplay/courseplay/files/2800354/log.txt)
![default](https://user-images.githubusercontent.com/47087191/51805055-cc91b880-2279-11e9-8772-69920b3e8381.PNG)

**Comment by Alex198602** [comment]
Add. Field boundaries scans and sees, but when you start generiruemoi of course when starting, nothing happens. Log file error: 2019-01-27 21: 44 C:/Users/Aleksey/Documents/My games/FarmingSimulator2019/mods/FS19_Courseplay / triggers.lua: 527: table index is zero
2019-01-27 21: 44 error: running LUA method 'mouseEvent'.

**Comment by pvajko** [comment]
We don't have the time at this point to deal with errors related to other mods. 

If you can reproduce this on a standard map please open an other issue.
