### ISSUE TITLE
Problem when buying Goldhofer low loader

### ISSUE THREAD

**Issue by HGReaper** [Courseplay/courseplay#2953]
When I try to buy the Goldhofer low loader the Game freezes in the Screen "Your selection is being prchased"

Log Errors
Error: Running LUA method 'update'.
D:/FS 19 Mods/Mods/FS19_Courseplay/settings.lua:1746: attempt to index field 'cp' (a nil value)

CP Version v6.01.00005

**Comment by Satissis** [comment]
Try with v6.01.00007 or later.

**Comment by HGReaper** [comment]
Fixed!
