### ISSUE TITLE
Unsupported Bales for fs19 version 6.0

### ISSUE THREAD

**Issue by BandaidFarmer** [Courseplay/courseplay#2954]
The course play mod conflicts with bales. I had about 60 round bales of straw down and tried to pick them up with the ursus bale stacker. Kept getting a “bale not supported” error. Took out the CP mod and the bales disappeared. However I’m able to pick up any bales made without CP loaded.

**Comment by Satissis** [comment]
All mod conflicts are postponed for now until we get sorted most of the default game bugs

**Comment by Tensuko** [comment]
Outdated and actually was able to pick bales.
If got any specific balecollector, make new Issue.
Closed.
