### ISSUE TITLE
Horsch Pronto 9 DC will not run course without fertilizer

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#2955]
I had already fertilized my field, so I wanted to run the Pronto 9 seeder without fertilizer, but courseplay says that tank must be refilled.   Seeds are full, but no fertilizer.

**Comment by pvajko** [comment]
Can you remind me how did this work in FS17?

**Comment by sootysax** [comment]
I don't remember if there was an option to run a seeder without fertilizer or not.

**Comment by pvajko** [comment]
So is this a bug or a feature request? :)

**Comment by 51stHD** [comment]
This is a new feature in FS19, where you can run a seeder (that can also apply fertilizer) without fertilizer with the hired hand. All you have to do is make sure the fertilizer reservoir is empty.

You could not do this in FS17 with either the hired hand or Course Play.

It would be a very nice new feature to have though.

**Comment by evybart** [comment]
With  cp in fs 17 was a option  that the seeder  works but not use fertilizer function on the  seeder i use it allways in fs 17 CP

**Comment by 51stHD** [comment]
Ah, my mistake. I seemed to remember this in FS17 CP, so I tested it before I posted above and couldn't find the feature or how to set it.

Could you remind me please, it's a great and essential feature. Thanks.

**Comment by pvajko** [comment]
with v6.01.00016 you can now run the seeder without fertilizer.

**Comment by sootysax** [comment]
> with v6.01.00016 you can now run the seeder without fertilizer.

This is also a problem, because the seeder will not stop and go refill when it runs out of fertilizer.   You need to be able to select whether you want to use fertilizer or not.

**Comment by pvajko** [comment]
Finally found that option for the sowing machines with fertilizer. Test with 6.1.23 and let me know
