### ISSUE TITLE
hinders spawing of wool pallets at sheep husbandry

### ISSUE THREAD

**Issue by I3ronos** [Courseplay/courseplay#2957]
If there is/was an active Courseplay-Worker, new wool pallets wont spawn

Another thing i dicovered while using VehicleInspector by HappyLooser (V0.49 Beta) is, that when switching off the coursplay-worker, the helper-status doesnt get removed. I dont know if its intended or not.

im using V6.01.00003
Map Felsbrunn, no other mods (except of part 2)
Log: https://gist.github.com/I3ronos/fdd3a145845eb464ebab882fd66146d3
![2019-01-27 21_52_01-farming simulator 19](https://user-images.githubusercontent.com/9900070/51807110-e683c900-2282-11e9-961a-4e8d5ce521c4.png)

**Comment by smigly** [comment]
Same here. I'll get a log when i get a chance.

**Comment by I3ronos** [comment]
the pallet spawning is fixed with V6.01.00009, but the helper-status is still a thing (but is not game-breaking  atm)

**Comment by Tankieboy** [comment]
Ah that's good to know I3ronos as I was having the same issues on Sutton. I guess I need to update and start selling some pallets and boxes!
