### ISSUE TITLE
Courseplay causing the save game process to never complete

### ISSUE THREAD

**Issue by lightbulb751** [Courseplay/courseplay#2963]
When I enable course play mod on my save and I try to save it fails to complete.

**Comment by duffstone** [comment]
post your logs please,  and do you happen to be using mods that use custom vehicle types?

**Comment by lightbulb751** [comment]
> post your logs please, and do you happen to be using mods that use custom vehicle types?

LOG: [https://pastebin.com/6SsQaxGg]

Yes, I am using multiple custom vehicle types, which are listed in the log provided.

**Comment by pvajko** [comment]
Multiple mod vehicle errors in the log, most likely mod related, can't spend time on this now. 

Try to isolate the mod causing the problem.
