### ISSUE TITLE
Placeables show "The object collides with an object"

### ISSUE THREAD

**Issue by Rgreen192** [Courseplay/courseplay#2964]
Regardless of how clear/flat the area is, placeables (tested both grain silo large and farmhouse) show "The object collides with an object" error and shows the placeable as red. Although it WILL let you place the placeable in a valid area, just a visual error.

**Comment by shadow250** [comment]
why are you reporting this here? this is not a courseplay problem.

**Comment by ThomasGaertner** [comment]
could you please check v0011 or higher and report ?
