### ISSUE TITLE
Tractor speeds on last headland : Tractor stops at headland crossing

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#2966]
Whenever the vehicle reaches the end of the last headland, it speeds along the last headland lane again at the full speed of the vehicle to reach the first up/down row.  Changing any of the speed limits settings or the cruise control speed does not affect this issue.  it always goes the full speed of the vehicle.

**Comment by SirStranger1989** [comment]
I also noticed tools folding up when driving on the headland lane, causing it to miss small chunks when starting again on an up/down row.

**Comment by pvajko** [comment]
This should now be fixed in v6.01.00008 or later.

**Comment by sootysax** [comment]
The speeding around the headland has now stopped, and the vehicle proceeds around the headland to the first up/down row at a reasonable speed.   However, the CP course will stop and shut down at the last headland point where it is going to re-drive the last headland.   You need to start the engine, and then start driving (at the current waypoint) for it to resume down the headland to the up/down rows.

I believe this is the nature of the stopping in #2962.

**Comment by pvajko** [comment]
Closing this since we have #2962 to track the remaining problem.

**Comment by sootysax** [comment]
is it possible to have the vehicle travel at 'field speed' instead of tool working speed around the headland on this pass to the row?
