### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by KANE712** [Courseplay/courseplay#2967]
Error: Failed to open xml file 'C:/Users//Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/modDesc.xml'.

**Comment by Opa-Andre** [comment]
You probably downloaded the courseplay-master.zip and used it directly in the mod folder, which doesn't work. As with all DEV versions, you'll have to unzip the cp-master.zip file, go into the created "courseplay-master" directory and then ZIP the contents (files and folders ) again to have an own ZIP file with the modDesc.XML in the root. After zipping, name the ZIP file "FS19_Courseplay.zip" or alike and that's the one you can put in your mod directory.
