### ISSUE TITLE
Course recorded with an offset (with certain vehicles)

### ISSUE THREAD

**Issue by 37cee** [Courseplay/courseplay#2970]
I ran into this problem when driving the Tatra Truck in an modless game on the european map.  But there are some other vehicles that have the same issue (not all though), the affected vehicles all have the driver in a non centered position (so trucks, cars, etc.).  
So when recording a course with such a vehicle, the course will  be generated at the drivers position, so the resulting course will be offset to the left side from the centerline of the vehicle. When using the same vehicles to drive a course that is recorded by another vehicle (any that is working correctly), the course will be followed from the drivers position, but now this results with the vehicle driving further to the right. 

I tested all vehicles with left hand steering and i had the problem with the following vehicles:
Tatra Phoenix 6x6, Lizard Hulk

The rest of the vehicles like the MAN or the rest of the Lizard trucks worked fine.

**Comment by Satissis** [comment]
Don't know why I assigned my self, but I'm not sure what you are talking about either

**Comment by pops64** [comment]
The CP team probably needs a picture to assist you. But I gather that the placement of the course waypoints now about the drivers node and not the rootNode of the vehicle there by creating an offset in recording. This also appears to be the same node that CP uses to drive from is a location other than the rootNode of the vehicle leading to weird offset behavior. @Satissis I don't know who would fix this but sounds pretty important

**Comment by Penduras** [comment]
![image](https://user-images.githubusercontent.com/47228726/52087582-265fee80-25aa-11e9-912b-45c17f5bd02c.png)

**Comment by Penduras** [comment]
![image](https://user-images.githubusercontent.com/47228726/52087742-89518580-25aa-11e9-8539-5a532dd685e2.png)

**Comment by Morgan81** [comment]
Experienced a similiar bug. Created a course for Fastrac+Mowers and when I load its offset is 2.4m to the right.

**Comment by pops64** [comment]
That is different from the above issue from what I gathered about your short description.  This bug is when recording the course the waypoint is not being placed directly above the center of the vehicle. Your issue sounds like the tool has an inherent offset that the center of the tool work area doesn't match up with the center of the vehicle. That is user fixable by adding in horizontal offset measured from the center of the vehicle.

**Comment by pvaiko** [comment]
This is a Giants bug, for whatever reason these vehicles have their root node on the left side and not in the middle. Won't fix.
