### ISSUE TITLE
cant open hud on right click

### ISSUE THREAD

**Issue by FarmerNothing** [Courseplay/courseplay#2971]
when i click right click the hud dosent open,also i cant click on the hud

**Comment by Chris2996** [comment]
had the same issue after setting the opening keybind to ctrl + del.

**Comment by Gargy** [comment]
I had also the same issue. I also had an issue that left mouse click was not recognized in Courseplay window. I found out, that keybinding in settings is actual bind to Keyboard (LEFT, RIGHT under Keyboard Column). So I made it under Mouse column and voila - it is working

**Comment by FarmerNothing** [comment]
Gargy Thank you
