### ISSUE TITLE
Transport mode: wait points ignored

### ISSUE THREAD

**Issue by smigly** [Courseplay/courseplay#2973]
Ai drivers do not stop at wait points in transport mode. They recognize the wait point, slow down for it, but don't stop and wait at it. I tested all types of vehicles, on both vanilla maps. Does any one experience the same issue? I will upload a log asap. 
Thanks to the developers for amazing work. Keep it up 😉

**Comment by Jimmy-the-Geek** [comment]
I can confirm smigly's issue, though the in game CaseIH 9240 combine would
obey if I toggled stop at next trigger/wait point.

**Comment by ptfarms** [comment]
Hi smigly, I'm getting the same problem, though I haven't tried toggling between 'normal' and 'ai' modes yet so thanks for that. Devs have done a pretty good job though.

**Comment by homerbucket4001** [comment]
I've encountered this where my drivers not stopping at wait points during transport mode. I tried changing between "normal" and "ai driver" but can't seem to find how to change it manually. Seems to change by itself depending on what mode you're using.

**Comment by smigly** [comment]
You can't change between ai driver and normal. As homerbucket4001 said, it changes by it self. I'm not an expert here, and i dont know if the "ai driver" is in anyway connected to this issue. It just is what i have noticed during my testing. I'm going to upload a log next time I'm going to play.

**Comment by ThomasGaertner** [comment]
we took the chance of converting CP to FS19 to refactor some parts of the script. the old parts , as mode 2 are 'normal', the new parts are 'AIDriver'. Our target is to get all the functions to AIDriver but this is a huge task... in the meanwhile developers can change the mode, users can just watch the change by changing the CP-modes

**Comment by GeorgeEarslight** [comment]
Same problem. Set up a course for MAN and Krampe trailer transporting Silage to BGA. The trailer is supposed to be filled by Mouse. The MAN never stops either at load point (CP briefly prints "loading 0/59000" and then drives away) or at the BGA (either full or empty). Feel free to ask for logs, I'll try to be checking the git almost daily.

**Comment by GeorgeEarslight** [comment]
Thanks for the commit! Made a new course on 6.01.00019 but unfortunately, it still doesn't wait. 
Log is interesting after about line 500. [Gist log channel 2 enabled](https://gist.github.com/GeorgeEarslight/548a57417c036b629d3802b88e4cb332)

**Comment by GeorgeEarslight** [comment]
No probs, no rush. Just send a quote reply if you need logs, save etc so I can easily see it.

**Comment by GeorgeEarslight** [comment]
Still doesn't wait to be **manually** filled. 
Just to make sure I made another game (Felsbrunn beginner), FIAT+Tipper load at Silo offload at sell point, works perfectly.
Could be something to do when the course doesn't start at a silo/trigger.
Unloading at the BGA could be another matter having to do with the BGA trigger, so I'll stop reporting about it on this issue.

**Comment by pvajko** [comment]
@GeorgeEarslight not sure what are we talking about here, the function I implemented and was missing from the new AI Driver code is what the CP manual (https://courseplay.github.io/courseplay/en/manual/index.html#hud_driverControls) describes as:

> While recording, you have the possibility to set waiting points on the course. At those points, the driver, while driving the course, will stop and wait until either you tell him to continue, or the configured waiting time has passed. When a driver reaches a waiting point, a message will be displayed (XYZ has reached waiting point.).

You seem to be talking about fill triggers which is a completely different issue.

**Comment by GeorgeEarslight** [comment]
> You seem to be talking about fill triggers which is a completely different issue.

@pvajko I am talking about fill triggers. I used the term wait point and fill trigger interchangeably, sorry about the misunderstanding. Would you like me to create a new issue and link all my comments from here?

**Comment by pvajko** [comment]
@GeorgeEarslight yes, thanks, I'd like to keep this for the wait points. 

Before creating a new issue you probably want to check the existing ones as there are quite a few tip trigger related ones open already.

**Comment by GeorgeEarslight** [comment]
Will do later today. As for wait points, I have already tested them on Mode1 and seem to be working as expected.

**Comment by pvajko** [comment]
Thanks. I'm closing this now (knowing that the timers still don't work but that's a low prio problem atm.
