### ISSUE TITLE
harvester catching in the middle of the field and tractor with bug waiting

### ISSUE THREAD

**Issue by marcospms** [Courseplay/courseplay#2977]
Sorry for the English translation. The combine freezes in the field. At the end of the line, harvester freezes. She freezes. He says he's skating

**Comment by marcospms** [comment]
all harvesters ice no field and stop the work.

**Comment by pvajko** [comment]
No idea what are you talking about. 
https://github.com/Courseplay/courseplay/wiki

**Comment by marcospms** [comment]
Sorry for the English translation. The combine freezes in the field. At the end of the line, harvester freezes. She  freezes. He says he's skating

**Comment by AlphaXray** [comment]
I guess the user means the combine stops after 1 row and the message "Combine is slipping" shows. 
I have a similar issue. Combine does does the turn and does not activate the header again, drives to end of row and stops with error "slipping".
![combvine](https://user-images.githubusercontent.com/14280222/51895064-981d1a00-23a9-11e9-9842-b72e11013194.png)

**Comment by marcospms** [comment]
Yes, its is my problem talking up.

**Comment by AlphaXray** [comment]
[log2019-01-30.txt](https://github.com/Courseplay/courseplay/files/2813886/log2019-01-30.txt)
Here is the log as requested. 
Noticed if I was inside the combine while turning it would generate "slipping" error but immediately as I switch to next it will resume operation, but still forget to activate header.  Lastest cp as of today.

**Comment by pvajko** [comment]
This should have been fixed by fbcb1847ddfddaf967dbd27f68bcb8f06d5b012b. Reopen if not
