### ISSUE TITLE
Drescher continues to refuel

### ISSUE THREAD

**Issue by Berndie5** [Courseplay/courseplay#2978]
Drescher has full grain tank, a collector arrives, Drescher starts to refuel and starts to drive. Although in the settings: Stop on unloading "is activated.This is only slightly unloaded.

**Comment by pvajko** [comment]
Try with v6.01.00010 and report back

**Comment by Berndie5** [comment]
Hello, yes now it´s work :)
Another problem, the Drescher S790 from the "LS19_JohnDeerePack_OY" pack only works with the 14000 and 50000 tanks. However, CoursePlay seems to have problems with the 10000 l capacity Drescher. He just stops at the starting point, everything is rumbling but he does not move. On the first page in the CP menu is also nothing except "call driver" included. LG Bernhard
[log.txt](https://github.com/Courseplay/courseplay/files/2807859/log.txt)

**Comment by pvajko** [comment]
Sorry, mod related issues won't be fixed during the beta phase.

**Comment by Berndie5** [comment]
# @pvajko 

thx

**Comment by Berndie5** [comment]
P.S. I changed it in the mod of the "LS19_JohnDeerePack_OY": capacity = "99000" instead of 100000. Thus the Drescher works now also perfectly.
Best regards

**Comment by sootysax** [comment]
'Stop during unloading' is still not working for me...
![fsscreen_2019_01_30_11_41_25](https://user-images.githubusercontent.com/6591048/51997177-3da4bc00-2484-11e9-84a4-f99206cf5ce0.png)
