### ISSUE TITLE
Harvester Folding in Field when Full

### ISSUE THREAD

**Issue by jaguar27klt** [Courseplay/courseplay#2983]
So if I let the Harvester run with a tractor in unload mode if the tractor sticks or runs to dump it's load, when the Harvester fills up it folds up and then will not unload into the tipper.
![20190128103308_1](https://user-images.githubusercontent.com/47116011/51851272-2bdae180-22e9-11e9-87c9-856b47e97806.jpg)

**Comment by Satissis** [comment]
#2969
