### ISSUE TITLE
Fertilizer/Slurry/Digestate Does Not Stop To Refill

### ISSUE THREAD

**Issue by alec-a** [Courseplay/courseplay#2984]
Fertilizer/Slurry/Digestate Mode, Tractor does not stop to refill with wait point set. Tractor returns to field and stops work due to being empty and does not attempt to run the route to refill again

Edit:
Sidenote :-  Samson pg II 35 does not turn off and the Samson sbh4 36 doesn't fold up when leaving field on refill course
Veenhuis premium Integral II Does not fold up when leaving field on refill course

**Comment by alec-a** [comment]
Game Log: **https://pastebin.com/j9ZVB9Hw**
Version 6.01.00005.dev

**Comment by shadow250** [comment]
there is a liquid transport mode for this it is disabled atm i think.
