### ISSUE TITLE
How about Multiplayer?

### ISSUE THREAD

**Issue by NowackiBro** [Courseplay/courseplay#2985]
Im trying yesterday with friend on MP but when he join the CP stop working.

**Comment by Jimmy-the-Geek** [comment]
It's been stated that they are focusing only on getting it to work in SP right now, so they can work the bugs out more quickly. Be patient, it's coming.

**Comment by Chris2996** [comment]
You can enable it by changing the ModDesc.xml. On Line 41 there should be "multiplayer" set that false to true and there you go. But no Courseplay might not work.

**Comment by NowackiBro** [comment]
Yeah im trying this. Courselay dont work.
