### ISSUE TITLE
Harvester unloading

### ISSUE THREAD

**Issue by TheForgottenAvenger** [Courseplay/courseplay#2987]
I am using the Stock New Holland CR10.90 Harvester, and the BigBud 747 tractor and am playing on Estancia Lapacho and have a few mods installed. Pretty much all of the mods from the in-game mod hub, so I don't know if this has an effect due to currently un-supported mods but:

I set a course for my tractor to unload the harvester. I start on the field, go straight for about 4-5 waypoints, then drive down to where I want the grain unloaded. Set the unload waypoint, then drive back to the field. Turn onto the field, go straight for 4-5 waypoints then stop the course. I moved the tractor off the field, then set it to start the course from the nearest waypoint. It makes its way onto the field, but when it tries to go and find the harvester, it just drives round and round in a giant circle. The turning angle is the same, about 30 degrees off centre, but it stays that way, and depending where it first needed to go, is either stuck in a large right hand or left hand turn. 

I will try again tonight with a stock tractor to see if it is a potential issue with the bigbud, or tractors in general.

**Comment by Chris2996** [comment]
Did the worker find the harvester? I'm having problems assigning unload workers to combines etc..

**Comment by TheForgottenAvenger** [comment]
The worker in my tractor found that the harvester needed unloading, set off to him, but could never get there.

**Comment by ThomasGaertner** [comment]
#3311
