### ISSUE TITLE
Game hangs with course, LUA Error

### ISSUE THREAD

**Issue by Mannelig83** [Courseplay/courseplay#2988]
Hello,
i dont know whats the Problem here but ist a Course with driving backwards.
When it starts to drive backwards then the game hangs and the log gets flooded with a LUA Error.
Pastebin:
https://pastebin.com/5DxPf39N

I hope i can help with your great work!

Greets
Markus

**Comment by hoefti10** [comment]
I had the same Error here, also by driving backwards:-)
But first, thx for the best Mod :-)
https://pastebin.com/GB3MeBpn

**Comment by hoefti10** [comment]
Works pretty fine :-)
