### ISSUE TITLE
Grain transport - CP will not load

### ISSUE THREAD

**Issue by tjBerlin** [Courseplay/courseplay#2990]
Hello!

Just tried the new CP version. First of all: many thanx for that! 

Now the little problem: I just tried to transport a few sugar beets from the silo to the railway station on the map FELSBRUNN. Unfortunately, CP does not recognize the trigger for loading the sugar beets. Manual loading works. Discharging with CP also perfect.

However, I use a mod "Wurzellager". in fact, CP finds the trigger to unload the sugar beats into the "Wurzellager". Thats no problem. 

Log file attached.

So long, TJ 

[log.txt](https://github.com/Courseplay/courseplay/files/2804807/log.txt)

**Comment by ThomasGaertner** [comment]
could you show me a screenshot, where it is ?

**Comment by tjBerlin** [comment]
Of course! I just installed the latest version of cp. 

Here the screenshots:

![bildschirmfoto 2019-01-29 um 16 40 03](https://user-images.githubusercontent.com/24283753/51920091-ffa48b00-23e4-11e9-9dba-7885952120c4.png)

Then I decided to change the fruit filtype to "Mais", before it was sugar beats.

![bildschirmfoto 2019-01-29 um 16 41 44](https://user-images.githubusercontent.com/24283753/51920211-3aa6be80-23e5-11e9-85ae-73a191566894.png)

Then CP recognized, that the choosen filtype is not in the silo. So I guess the trigger must be found. 

![bildschirmfoto 2019-01-29 um 16 41 54](https://user-images.githubusercontent.com/24283753/51920314-75105b80-23e5-11e9-8ac7-0ee417b87833.png)

Maybe I made a mistake. Do I have to place a waiting-point?

CU TJ

**Comment by XPiRiJenZ** [comment]
maybe an issue because both triggers for filling and unloading are too close to each other. did you try to drive the course the other way round?

**Comment by saku05** [comment]
Hello
it works with a short distance between start and stop

**Comment by saku05** [comment]
Only with trailer TDK 302
![la remorque](https://user-images.githubusercontent.com/4406385/51933370-751e5480-2401-11e9-9578-5a025e95fabd.jpg)

**Comment by tjBerlin** [comment]
Hello! 

Thanks for the answers! Indeed, it works coming from the other side. I'm using latest version CP .00014. 

![bildschirmfoto 2019-01-29 um 21 28 52](https://user-images.githubusercontent.com/24283753/51939947-f5988180-2410-11e9-9e4d-bcff1c65e4b8.png)

But not at the first attempt. You have to hit the trigger quite hard and perfectly strait. I made it on the second attempt. 

(pls don't look at the course, I just made an extra drive to old course to hit the trigger from the other side, it might look a bit wired...)

**Comment by sootysax** [comment]
> maybe an issue because both triggers for filling and unloading are too close to each other. did you try to drive the course the other way round?

Silos that have the unload trigger directly on top of the tiptrigger have traditionally been an issue with previous versions of Courseplay.

**Comment by tjBerlin** [comment]
OK, didn't have the problem until now. 

Then this one can be closed, I guess! Thanks to all. CU TJ

**Comment by Satissis** [comment]
Yeah fill trigger and unload triggers on the same spot is not easy to handle since it's looking for both in that situation.
Closing issues pr. request.
