### ISSUE TITLE
Harvester didnt stop at field end

### ISSUE THREAD

**Issue by hoefti10** [Courseplay/courseplay#2991]
The Harvester didnt stop at the end of the field.
on the screenshot hopefully you see the problem. He didnt unload all the hay on the field...
![20190128213646_1](https://user-images.githubusercontent.com/25055083/51866278-dcc49900-2348-11e9-8a91-cf9ac6c171d9.jpg)

**Comment by ThomasGaertner** [comment]
I think what he's mentioning is that the combine is not stopping and waiting till the straw flow has ended  before turning

**Comment by pvajko** [comment]
Did it in CP5?

**Comment by evybart** [comment]
Yes he did he waits for the straw flow was ended in CP5

**Comment by pvaiko** [comment]
#3437

**Comment by Tensuko** [comment]
Fixed with V160. Closed.
