### ISSUE TITLE
Installing Beta

### ISSUE THREAD

**Issue by mdart83** [Courseplay/courseplay#2992]
I am having a problem installing the CP from git hub.  I have no issues with CP from third party mod sites.  I select the "code" tab and then download the zip file.  I have tried unpacking the file and re-zipping the file then dropping in the mods folder. Also have tried just dropping it in mods folder.  I would like the most current version of CP if possible.  I am prob just missing a step. Thanks

**Comment by alec-a** [comment]
Make sure the courseplay-master folder is extracted and then renamed to FS19_courseplay then either place into mods folder or re-zip the contents of the folder so the modDesc.xml and other files are in the 'first layer' of the zip file

**Comment by deeg427** [comment]
iv been trying this for 2 night and im damned if i can get it to work it shows up in my mods installed but when i go to load a save or a new game it doesnt show up in mods or dlc screen for ticking or unticking

**Comment by mdart83** [comment]
Yes, i just downloaded again and unzip and zip the file. Open the zip folder and i can find the moddesc folder

**Comment by deeg427** [comment]
well god damn it if didn't miss the _ in the name!!! just goes to show you must make sure you do it proper lol
