### ISSUE TITLE
Error method update on stop driver

### ISSUE THREAD

**Issue by alec-a** [Courseplay/courseplay#2993]
**Stopped Driver caused:**
2019-01-28 21:10 Error: Running LUA method 'update'.
2019-01-28 21:10 C:/Users/Alec/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay/fruit.lua:193: attempt to index a nil value

**Version:** 6.01.00009.dev
**Log:** https://pastebin.com/yrQjdLHn
**Map:** Sutton Farm

**Further Details:**
Had a combine offload and transport course running but the driver was sat still and the combine was not on a course

**Comment by pvajko** [comment]
If you can reproduce this on a standard map I'll reopen. Sorry but have no time for mods now.

**Comment by alec-a** [comment]
Turned out to be the grain cart driver, needed the fruit type from the combine but the combine lastValidFruitType was nill for some reason most likely a fs bug, after emptying manually it's now working
