### ISSUE TITLE
Problems Install New Version

### ISSUE THREAD

**Issue by haldir21** [Courseplay/courseplay#2994]
I have have trie to install the newest version of CP.
My Version that i have is 5.03.00050

I have trie it wit zip to FS17_CoursePlay5.zip ans ZZZ_Courseplay.zip but nothing works.

What can i do .
Tahns for help.
[log.txt](https://github.com/Courseplay/courseplay/files/2805212/log.txt)

Gretings haldir

**Comment by hoefti10** [comment]
The new Version is for the FS19...

**Comment by haldir21** [comment]
Is the Version 6.01.00009 that i have Downloaded not for F17? Have loaded over https://courseplay.github.io/courseplay/de/installation/index.html

**Comment by mightymaske** [comment]
Hi, no it’s not for fs17. It is for fs19 like the comment befördert ;)
I don’t know if this is ok, but here is a Downloadlink for fs17. (Not tested, im not at my pc)
https://www.farming-simulator.com/mod.php?lang=de&country=at&mod_id=92045
