### ISSUE TITLE
Info about xml attribute lane in CourseStorage file

### ISSUE THREAD

**Issue by TinyCrocodile** [Courseplay/courseplay#2995]
Hi guys,
i just did implementation of isconnectingtrack in my CourseDrawer app. 
when looking at the xml file of the course i saw another attribute "lane" is saved with all negative values. 
What is the purpose of this attribute? will all values allways be negative numbers?

For now i have not planned to edit this value but for shure i need to apply the same value, when the user is inserting a waypoint in a "lane" section. 

Are there some more changes in course storage files i need to know about?

thank you for the great work so far

**Comment by pvajko** [comment]
_lane_ is the number of the headland lane, starting at -1 for the outermost headland. Also used around islands.

There are two new ones, _mustreach_ which designates a waypoint at the end of the up/down row when the transition to the next row is not by a turn maneuver. And then there's _align_ where the driver will not only drive towards it but will try to get there in the correct direction.

These are currently only used in the new fieldwork patterns discussed in #2923

**Comment by TinyCrocodile** [comment]
Ok thank you for the information. 
I will look into supporting this features soon. 

I hope i found the source of information i was looking for...
is it true that all of the Attributes will be written in xml ar set in the function Waypoint:set  of line 78 in Waypoint.lua?
So in future i just need to check there and have the list of Attributes?

**Comment by pvajko** [comment]
That's a good point to look for what is used by CP, what actually goes to the XML is here: https://github.com/Courseplay/courseplay/blob/e02afc9fdfb9fa6edad54d1c0a2041b4b9f2e316/course_management.lua#L679

**Comment by TinyCrocodile** [comment]
Ok perfect i will have a look at this file in Future for not missing out on anything new. 
Thanks for good help!
