### ISSUE TITLE
game will not save on honey dew fields FS19

### ISSUE THREAD

**Issue by Firebaugh2014** [Courseplay/courseplay#2996]
cannot save game after buying fields and equipment on the honey dew farms xl map entire system keeps freezing up.

**Comment by Jimmy-the-Geek** [comment]
It's got to be a problem on your end. I'm playing on that map right now
with no issues.

**Comment by Firebaugh2014** [comment]
It’s working now jimmy I updated the mod but having issues getting my 3  combines to harvest field 8 they way they are supposed to do you have a video to help me out on that by chance

**Comment by Satissis** [comment]
Closing issue since it seams to be fixed.
