### ISSUE TITLE
Suggestion: Repair Run

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#2997]
Considering the amount of repair that needs to happen, repairs need to be done in the middle of a large harvest or seeding.  Would it be possible to add driving through a workshop trigger to repair a vehicle or header during a refill run like we do fuel?

**Comment by Tankieboy** [comment]
I do like this idea to simplify repair, however with the release of the toolbox addon I like doing field repairs as in real life.

**Comment by Incompertus** [comment]
if you press P and go to you're garage you can repair without going to the workshop

**Comment by Tankieboy** [comment]
I prefer to simulate rather than arcade gameplay

**Comment by Incompertus** [comment]
i see it as calling in a mechanic to fix it :)

**Comment by MicaelJarniac** [comment]
@Tankieboy
> I do like this idea to simplify repair, however with the release of the toolbox addon I like doing field repairs as in real life.

Mind linking which toolbox addon you're talking about?

I found those:

- https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=121225&title=fs2019 - this one seems to be just a small version of the workshop, doesn't seem to do what you mentioned

- http://www.fs19mods.com/lsfm-portable-toolbox-mod - seems to do what you mentioned, but is singleplayer only

- https://www.modhoster.com/mods/werkzeugkiste--2#description - not quite sure about this one, tiny description
