### ISSUE TITLE
issue with overloader ( most likely my fault tbh)

### ISSUE THREAD

**Issue by deeg427** [Courseplay/courseplay#3000]
i set a course up like last year and have a wait point (p) at the point of unloading but then the overloader wont continue unless i tell it to continue, am i doing something wrong? im using the reboke ninja 19000 overloader

**Comment by ThomasGaertner** [comment]
overloader mode3 is still not active

**Comment by deeg427** [comment]
ah i thought it was mode 2 that did the over-loader well it works to a point using mode 2 just have to press continue to get the over-loader back to the combine

**Comment by Satissis** [comment]
Nah that's mode 3 that is disabled for the time being.
Closing this since it's not an valid issue yet.
