### ISSUE TITLE
Q: Cpupdate

### ISSUE THREAD

**Issue by AgroWillem** [Courseplay/courseplay#3001]
No issue but a Question.

For FS17 we had that handy CPupdate-script. See #1438
Is it possible to have that too for FS19?

And thx a lot for the new CP!

**Comment by apache141** [comment]
This seems to be working as is i just tried it and it updated to the new version.

**Comment by shadow250** [comment]
it places it in the 2017 mod folder though

**Comment by Satissis** [comment]
I'll close this one since it's not an issue and it's not something we have provided.
