### ISSUE TITLE
List of minor bugs with Case 9240 with another tractor in combine offload

### ISSUE THREAD

**Issue by snwkill** [Courseplay/courseplay#3002]
1. The default left offset should be 10m
2. The default behavior doesn't put the trailer far enough forward to actually start dumping grain
3. The vertical offset function (which I assume would take care of point 2 doesn't actually take effect unless the combine starts unloading, then it applies the vertical offset, manual left offset works as expected
4. if the combine is 100% full and the tractor has to drive behind it (when the pipe is over fruit) ends up clipping the combine on the right rear

These issues were seen with a new holland T6.175 pulling a TKD 302 trailer

**Comment by ThomasGaertner** [comment]
#3311
