### ISSUE TITLE
Spreader turns on too early during turn

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3003]
The spreader starts spraying halfway into the turn, resulting in alot of over spray.

![fsscreen_2019_01_29_10_01_30](https://user-images.githubusercontent.com/6591048/51917458-981f1900-23ad-11e9-9bc3-097595b92eda.png)
![fsscreen_2019_01_29_10_01_40](https://user-images.githubusercontent.com/6591048/51917466-9d7c6380-23ad-11e9-8662-257444dbb6ba.png)

**Comment by shadow250** [comment]
i noticed this too but lime is cheap. lol

**Comment by Satissis** [comment]
Could you take a screenshot with debug 12 and 14 active.
Think the front and back marker might be wrong on it and the turn maneuver should show those lines.

**Comment by sootysax** [comment]
![fsscreen_2019_01_30_09_27_09](https://user-images.githubusercontent.com/6591048/51988211-21981f00-2472-11e9-89da-f1ef3bbf19e4.png)

**Comment by pvajko** [comment]
Try with 6.01.00037or later and report back

**Comment by sootysax** [comment]
you might want to back off the adjustment a tiny bit for seeders.. missing spots on the rows now
![fsscreen_2019_02_04_07_28_18](https://user-images.githubusercontent.com/6591048/52208477-d190d200-284e-11e9-8ca4-f8b9ee35cf4e.png)
![Uploading fsScreen_2019_02_04_07_28_53.png…]()

**Comment by pvajko** [comment]
Yeah, currently we have no generic way to find out when to start lowering an implement in order to have it in the working position just at the right spot and I don't want to stop the tractor at the start of the row waiting for it to lower.

**Comment by sootysax** [comment]
This seems to be resolved.. closing
