### ISSUE TITLE
Courseplay locks up when running out of lime during a turn

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3005]
same course as #3003; FS19 crashes when it runs out of lime when it should begin the refill route.

https://gist.github.com/sootysax/c9ce36988babeeb9725f03d8528b8c8a

2nd log debug 13/14/17

https://gist.github.com/sootysax/d6abdcfe04dfb48aa48e1cf147b7c798

**Comment by pvajko** [comment]
Try with 6.01.00014 or later.

**Comment by pvajko** [comment]
Well, at least it does not crash :) I know there's something funny going on when a turn maneuver is interrupted for whatever reason. Will fix that later.

**Comment by pvajko** [comment]
Actually, if you could send me a savegame/course on this that would save me a lot of time.

**Comment by sootysax** [comment]
Fixing #3003 would prevent lime from running out during a turn :)

**Comment by sootysax** [comment]
[#3005_SAVEGAME_COURSES.zip](https://github.com/Courseplay/courseplay/files/2808940/3005_SAVEGAME_COURSES.zip)

**Comment by pvajko** [comment]
v6.01.00015 or later should be much better. And, yes I know, #3003 ....

**Comment by sootysax** [comment]
workin like a champ..  I certainly do like the purple tractor beam that pulls you to the refill route..  

![fsscreen_2019_01_29_21_50_52](https://user-images.githubusercontent.com/6591048/51955024-52e00300-2410-11e9-9642-5df5b41af047.png)

**Comment by pvajko** [comment]
Isn't that cool? As a lot of discoveries, this was also accidental, the Giants engine expects RGB values between 0-1 but I forgot that and used 100 (think range 0-255), which turned out to be making this awesome glow...

**Comment by BolsaFamillia** [comment]
> workin like a champ.. I certainly do like the purple tractor beam that pulls you to the refill route..
> 
> ![fsscreen_2019_01_29_21_50_52](https://user-images.githubusercontent.com/6591048/51955024-52e00300-2410-11e9-9642-5df5b41af047.png)

Why does not my tractor load the spreader with lime and fertilizer? I have the refueling route but when it passes the silo it opens the lid and passes slowly straight and continues with 15km / h the rest of the route. Before he carried it, now he does not recharge anymore. Another problem I have is that the truck and the tractor goes through the silo of the farm to sell and does not load the grain, it passes straight and stays with the 15km / h. I know the map is not vanilla, but does anyone else also have these vanilla mistakes?
