### ISSUE TITLE
Speed to high when unloading in Bunkersilo

### ISSUE THREAD

**Issue by Mannelig83** [Courseplay/courseplay#3006]
Hi,
First of all:
Thanks a lot for the great work.

When you drive through the bunker silo (placeable, Giants original big double) and unloading starts then the tractor goes max Speed and overshoots.
it dosent even close when it leaves the silo.

**Comment by pvaiko** [comment]
Is this still a problem?

**Comment by panther5** [comment]
Was searching for an Post like this.
Had this problem yesterday, so its still in CP.
Was recording with 7km, but tractor going 30+ while unloading :D

will look for an clean Map without mods, send log when ready

**Comment by Tensuko** [comment]
Just tested this out today with version 103
![fsscreen_2019_03_02_20_44_38](https://user-images.githubusercontent.com/27344744/53686838-d2713280-3d2c-11e9-9700-99a463a2fc67.png)

Need anything to test it ?

**Comment by ThomasGaertner** [comment]
Is ok with a Version higher than 112?

**Comment by Tensuko** [comment]
Still to fast with Version 124.

Is there any specific option to tell wich speed to drive or record it with the right speed ?

I just remember in FS17 CP calculated its speed automatically with the fill level and unload speed of the wagon ?

![fsScreen_2019_03_10_11_19_30](https://user-images.githubusercontent.com/27344744/54083647-a9e9c980-4326-11e9-8696-e0cf5d82a279.png)

If need any debugchannels and log, let me know.

**Comment by ThomasGaertner** [comment]
@Tensuko : its the same here, but not on the fly but only one time at the start of the silo.
can you give me the savegame ?

**Comment by Tensuko** [comment]
You need the Map (FileHorst is a good and fast source https://www.modding-welt.com/mods/file/2204-ls-19-provence/  ) and the Mower from ModHub, other Mods not used yet on savegame.

[savegame1.zip](https://github.com/Courseplay/courseplay/files/2949434/savegame1.zip)

And here the Courses, you should easy understand them :)
[LS19_Provence.SampleModMap.zip](https://github.com/Courseplay/courseplay/files/2949437/LS19_Provence.SampleModMap.zip)

**Comment by ThomasGaertner** [comment]
Ok I think I got the problem. try v.127 or higher and report

**Comment by Tensuko** [comment]
Sadly with 127 nothing changed :(

![fsScreen_2019_03_10_21_25_34](https://user-images.githubusercontent.com/27344744/54091055-93219200-437b-11e9-8336-394940dd8086.png)

Ich versuchs mal auf deutsch:
Das hat aber nichts damit zu tun, dass der Kurs noch so dicht am Silo weiter läuft und CP ausrechnet, da ist noch das Silo, also kann ich weiter abladen ? Habe mir den Trigger vom Silo selber noch nicht angesehen.
Kann eventuell im laufe der nächste Woche mal auf Vanilla-Basis paar Silos vorbereiten und Kurse einbauen, fals das hilft. Weis aber nicht wann ich dazu komme.

**Comment by ThomasGaertner** [comment]
Strange, I used your savegame and it worked

**Comment by Tensuko** [comment]
Maybe some wrong settings in my CP ?
Or I try with some mods deaktivated to make sure that it is no Mod Conflict.... Tho I hope not since everything else works fine.

Anything I can turn on to see some triggers and debugchannels for that ?

**Comment by Mannelig83** [comment]
I tried today with different Trailers and it worked like a charm and changed the spee depending on Trailer capacity.
So fixed on my side!
Good Job and thank you man.

Greets
Markus

**Comment by Tensuko** [comment]
@Mannelig83 could you post a log here so I can see wich Mods you got activated ? So maybe I can see a Mod what I got wich maybe cause trouble.
Differen Trailer can't be since Thomas used my SaveGame with this setup.

**Comment by Mannelig83** [comment]
So i did go on and after the first 2 correct unloads the tractor did go just 18km/h on the street.
i set the Speed Control back to max and it ran with full Speed through the silo.

So it seems to have still a Problem with the Speed Setting...

![Screenshot 2019-03-11 14 00 26](https://user-images.githubusercontent.com/47121919/54125842-66ff2300-4406-11e9-9441-684cdeb192ac.png)

ist the Standard schuitemaker loading wagon in this case.

I hope this helps.

**Comment by Tensuko** [comment]
As you see, thats exactly my problem :)

If I find a bit time later at home I do a Vanilla try again see if that is any kind of a Mod Conflict... I hope not...

**Comment by Tensuko** [comment]
![fsScreen_2019_03_11_18_33_21](https://user-images.githubusercontent.com/27344744/54144544-38943e80-442c-11e9-82b8-3a8fe43abcd3.png)

That is with all my Mods just Felsbrunn Map and new Courses....
Will make more test with reload Course on my other Savegame or even Create new one.

**Comment by ThomasGaertner** [comment]
I've added some debug prints. test again with debug channel14 active and deliver the log in case of fail ....

**Comment by KenStumich** [comment]
V 128
map NF-Marsch 
debug channel 14
bga silo big size
mode 1 - beladung am startpunkt

kein abladen im silo

hier die log: [https://pastebin.com/aTEx63mW](url)

**Comment by KenStumich** [comment]
weil NF-Marsch keine offizielle map ist hier mal Ravenport

- V 128
- Map: Ravenport
- Debug Channel 14
- BGA Silo (big size)
- Mode 1 - beladung am startpunkt
- Log: https://pastebin.com/2TNpNS2f

geschwindigkeit im silo zu hoch

![fsScreen_2019_03_12_18_19_01](https://user-images.githubusercontent.com/28400454/54221949-bd4a8f80-44f4-11e9-80ab-cb55b6678473.png)
![fsScreen_2019_03_12_18_19_05](https://user-images.githubusercontent.com/28400454/54221976-c8052480-44f4-11e9-9b2a-090e25a92bec.png)
![fsScreen_2019_03_12_18_19_09](https://user-images.githubusercontent.com/28400454/54222017-db17f480-44f4-11e9-8e9f-dc7e04e48cab.png)

**Comment by Mannelig83** [comment]
i did some testing too and the results were really odd…
1 run failed which i attached a screenshot and it overshot…
But if i remember correctly it was one of the runs which were marked in the log with Speed 115kmh
I dont know anything About how that works but the values seem strange… 
one run it says 14kmh in the log which succeeded and the other ones say 115kmh but the last one was successfull too even with 115kmh in log...

if you Need more Input or testing let me know.

Log:
https://pastebin.com/S0pmxLEV

Screen:

![Screenshot 2019-03-12 18 34 27](https://user-images.githubusercontent.com/47121919/54222818-6e9df500-44f6-11e9-957b-520ad334beb1.png)


Greets
Markus

**Comment by ThomasGaertner** [comment]
my problem is: in your prints is the fillLevel 0, which should be 56000 for Ken\ 46000 for Mannelig in your cases. so could you explain how did you test ?

**Comment by Mannelig83** [comment]
i guess thats the Point what you Mention.
if you look at my log you see 3 passes… 1 pass the fillevel iss correct with 45k
all the others it dosent seem to "see" the actual fillevel.

I have a simple Course from my silo to fill with chaff and drive to bga and unload.

I just let it do ist Thing while im rolling the silo so i see when the tractor is unloading and Fails. thats the Point where i stop him or when i Need more time for compacting.

Im using a Standard tipper by the way. but i guess the check for the fillevel seems to be a Problem.

Greets Markus

**Comment by KenStumich** [comment]
i set a roundcourse  , mode 1 , loading on startpoint. 
set the tractor with tipper on the course an after he stopps at the 1 waypoint to fill  i open the console an use > gsFillUnitAdd 1 grass_windrow
this fills up the trailer with grass and also starts the drive, cause the trailer is full

but to confime this, i will fill up with something else , e.g. a frontloader to start the drive and post again

**Comment by ThomasGaertner** [comment]
can I have your savegames ? its working here ....

**Comment by Mannelig83** [comment]
im playing on a modmap (with a Standard BGA).
Do you want the modmapsavegame or should i reproduce one on a Standard map?
Where do you want it to be uploaded?

**Comment by KenStumich** [comment]
same result with a silo to fill up the trailer
speed to high

log file: [ravenport v128](https://pastebin.com/CVRvjks0)

![fsScreen_2019_03_12_21_01_59](https://user-images.githubusercontent.com/28400454/54232532-20dfb780-450b-11e9-8746-7eca330d1cc3.png)
![fsScreen_2019_03_12_21_02_47](https://user-images.githubusercontent.com/28400454/54232547-29d08900-450b-11e9-8cdf-f3c755dd9581.png)
![fsScreen_2019_03_12_21_02_55](https://user-images.githubusercontent.com/28400454/54232573-394fd200-450b-11e9-9593-ffdeebe52ddc.png)

i will post the save if you could tell me where to upload it

**Comment by KenStumich** [comment]
here is a link to my savegame

https://www.file-upload.net/download-13534896/savegame7.zip.html

**Comment by ThomasGaertner** [comment]
https://filehorst.de/

**Comment by Mannelig83** [comment]
So, i tried to set up a testing Scenario for this on felsbrun but what shall i say…
Here it dosent unload at all.

it says "unloadingpoint reched" but dosent start to tip.

Savegame:
https://filehorst.de/d/cizpcGld

**Comment by ThomasGaertner** [comment]
130 is the next try

**Comment by KenStumich** [comment]
the big size and med size silage silo are fine now. no problems at all on different maps.
but now i have a problem with the COURSEPLAY_NUMBER_OF_RUNS.
if i turn this down to 1 run  it dosnt stop at all. 
i will wait for confirmation of the other tester.

**Comment by ThomasGaertner** [comment]
@KenStumich : thats an other issue

**Comment by Mannelig83** [comment]
Seems fine for me.
I did a test with roundabout 1million Chaff and different Trailers and different set cruise Control and every pass it dropped fine in the bunkersilo.

So seems fixed. what do you think?
shall i clos or do you want to?

Thanks alot.
Greets
Markus

**Comment by KenStumich** [comment]
@ThomasGaertner ok. i post a new issue for the nuber of runs during the evening.

**Comment by Tensuko** [comment]
[Test01_Felsbrunn.txt](https://github.com/Courseplay/courseplay/files/2963028/Test01_Felsbrunn.txt)
[Test02_Provence.txt](https://github.com/Courseplay/courseplay/files/2963029/Test02_Provence.txt)
👍  Not even reloaded the Course.
But I must say I had just time for one unload. Nothing big prepared.
But the Issue I had before was fixed now.
It is still weird, that it was working on Felsbrunn and not on Provence with previous version.
Hope that this fix doesn't cause other problems now.

**Comment by Maunose** [comment]
I'm having this issue when using mode 2 on "The Pacific Northwest" map. I'm attaching the log here.
It looks like CP enter a loop trying to calculate the speed as soon as it detects the trigger and it shows a negative number on reverse speed (like -4958273758185).

[log.txt](https://github.com/Courseplay/courseplay/files/3316493/log.txt)
