### ISSUE TITLE
Adding Course did not recognize Crosspoints

### ISSUE THREAD

**Issue by KenStumich** [Courseplay/courseplay#3008]
if you add a course to another course it will allways connect the end of the first course to the start of the next one. 

exp. behavior: connect the first and the secound course with the nearest cosspoints from each course

edit:

FS19_CoursePlay6 (Version: 6.01.00009) (Hash: 9bae98ccfd65f032e4393035015a8598)
its a general bug, so no log file. if you need one tell me pls.

**Comment by sootysax** [comment]
did you use the second add course button (the one with the +)?  thats how you connect courses to crosspoints

**Comment by sootysax** [comment]
Did you perhaps use the second add course (the one with the + in it) instead of the first one?

**Comment by KenStumich** [comment]
you are totally right.
the + on the icon misleads me. 

first icon (select/connect course) is right and working. second icon (with the +) is adding (at the end)

thx sootysax.

this can be closed.
