### ISSUE TITLE
Combi- Tractor stops Combine at end of line to unload doesn't clear stop command

### ISSUE THREAD

**Issue by snwkill** [Courseplay/courseplay#3009]
When a Combine reaches the end of a row before it turns around and a tractor in combi offload mode is on its way it puts in a stop command for the combine (looking at the code it looks like this is done via allowedtodrive=false for the combine

If there is some kind of error, say the offset is off and needs to be adjusted and you click stop AI on the tractor unloading, the combine will now be infinitely stuck, even if you fire the helper and reload the helper on the combine. 

I went back to 2017 and this seems like a function even there, although in 2017 if you start the ai on the tractor unloading it has the ability to clear the stop command once it successfully makes another trip, in 19 that doesn't happen. 

My suggestion, have either another button on the start driving tab that says "clear combine stop override" which changes the flag to allowedtodrive=true for the combine or have it do it automatically when you click stop ai from the tractor.

**Comment by Flacwby** [comment]
This has been there since CP 5.??? for FS 17. The cruise speed gets turned to 0. If you hop in the Combi and increase cruise speed (2 key) then the AI combi will start moving again.

**Comment by pvajko** [comment]
Not sure I understand. 
1. the log does not have a single entry from the combine. Was CP driving at all at this point?
2. if you have the 'stop during unloading' enabled and it is not completely empty it'll stop and wait until it is unloaded or you stop the driver. But then it can be restarted and will continue until it is full again.

So don't quite get how to reproduce this and if it has something to do with the end of the row or not.

If you want you can post a savegame and your courses so I can reproduce it here. No mods please.

**Comment by pvajko** [comment]
Try with v6.01.00019 it may help https://github.com/Courseplay/courseplay/commit/5dcd4644f1b3b86db61218adddcac284c94c2f7d

**Comment by snwkill** [comment]
No, the combine was under a regular hired helper, it is about the only thing the default cpu is good at

**Comment by pvajko** [comment]
Combine is _not_ driven by CP, I can't help with that. Not sure if we were ever able to stop the Giants helper.

**Comment by ThomasGaertner** [comment]
I've added some debug prints, please try again with debug channel 4 active and report

**Comment by ThomasGaertner** [comment]
@snwkill : any news ?

**Comment by ThomasGaertner** [comment]
#3311
