### ISSUE TITLE
Trailers

### ISSUE THREAD

**Issue by BostonJohnny1226** [Courseplay/courseplay#3011]
Is there a capacity limit for trailers? The in game ones seem to be working ok so far. My mod trailers don't. I edited the capacity of an in game trailer to 150,000 and I get a "wrong trailer type" error

**Comment by Insanelycrazy14** [comment]
Yeah same for me modded trailers and modded harvesters not working

**Comment by Berndie5** [comment]
Yes, it is.... 
I changed it in the mod of the z.B. "LS19_JohnDeerePack_OY": capacity = "99000" instead of 100000. Thus the Drescher works now also perfectly.
Best regards

**Comment by Insanelycrazy14** [comment]
Well not sure the difference but i am using a Krampe mod and says wrong trailer for this mode everytime I try it

**Comment by Insanelycrazy14** [comment]
Ok nevermind i see now the max capacity is 99k anything more CP will kick it out. I got mine working
