### ISSUE TITLE
Multiple issues with CoursePlay 6.01.00013

### ISSUE THREAD

**Issue by edjon2000** [Courseplay/courseplay#3012]
I'm not sure how to report these, 
There are some issues with various vehicles and attachments as well as issues with the CoursePlay HUD not appearing unless multiple steps are taken, there are also some issues with combined courses, along with various other issues, what is the best way to report these?

**Comment by edjon2000** [comment]
Hi Maarten, thank you for your reply but the linked wiki and associated note are out of date whilst they are useful they are not really designed for FS 19, game logs and save games, no problem I can supply them, I could also upload various youtube videos to demonstrate these issues, the developers usually refer to various modes of operation but I do not know what these modes refer to I can understand things like grain transport, fieldwork, offload combine and unload etc but do not know how this relates to actual courseplay modes

**Comment by sootysax** [comment]
Everything in the 'how to submit a bug report' wiki still applies to this beta test.   Submit one issue at a time, use the latest dev version of CP, and attach your complete log etc..

**Comment by edjon2000** [comment]
Hi sootysax, thanks for your reply, I will do that
