### ISSUE TITLE
Straw Collect 

### ISSUE THREAD

**Issue by hoefti10** [Courseplay/courseplay#3014]
Hey Guys, just a small question, it is possible at the moment to collect straw and store that in a wrehouse?
I had to Courses one for the collector and the second to bring the straw in the warehouse. Put it to Courseplay and set the ' Fieldwork' mode.. in the past (CP 5) i  guess it was the right way in my mind.
Maybe someone can help me :-)

**Comment by Tankieboy** [comment]
I think it will work if you merge the two courses and save. I set up a loop from the edge of the field to wherever I want to unload (wait trigger) and back to the field edge. Then a fieldwork course and combine the two.

**Comment by hoefti10** [comment]
I‘ll guess i didnt Need a wait trigger. I will Test it later. Thx for your reply

**Comment by hoefti10** [comment]
Now he is able to get on the loader Course. But CP didnt Stop at the trigger from Haystorage. anyone has an idea?

**Comment by jhndrtxn** [comment]
you may have to add a tip point in the unload course

**Comment by pvaiko** [comment]
Should be working fine now.
