### ISSUE TITLE
traffic on the road stopps, when CP is closing in

### ISSUE THREAD

**Issue by tjBerlin** [Courseplay/courseplay#3015]
Hello!

I made a CP course driving sugar beats to mainstation south. When CP driver is closing in to ai traffic, the traffic goes on break. 

![bildschirmfoto 2019-01-29 um 21 51 52](https://user-images.githubusercontent.com/24283753/51940422-393fbb00-2412-11e9-8b21-ab3e389eea65.png)

![bildschirmfoto 2019-01-29 um 21 52 31](https://user-images.githubusercontent.com/24283753/51940626-d7cc1c00-2412-11e9-8069-79db3da1b541.png)

**Comment by godofgta42** [comment]
If you mean that the traffic stops on the road when a Vehicle with a CP-Helper closes in, thats a feature from FS19 i think.. They should start moving again when the Helper-Vehicle is further away..

If not a more detailed explanation would surely help the devs more..

**Comment by tjBerlin** [comment]
Sorry, hit to fast the enter-button, the explaning was missing. Hope, it's now there...

**Comment by Flacwby** [comment]
I can confirm this as well. Traffic in front of the CP driver is stopped when CP get's within a certain distance. The AI traffic never resumes until you turn off CP.

**Comment by zed636** [comment]
I can also confirm by specifying that the rear traffic instead respects the CP driver not impacting against it (blue car). some example screens:
CP course active
![fsscreen_2019_01_30_00_01_21](https://user-images.githubusercontent.com/19471664/51946808-03570280-2423-11e9-8422-ce32ea6a49c9.png)
CP course deactive
![fsscreen_2019_01_30_00_01_45](https://user-images.githubusercontent.com/19471664/51946827-1669d280-2423-11e9-83da-0716f52edae5.png)
CP course active
![fsscreen_2019_01_30_00_01_59](https://user-images.githubusercontent.com/19471664/51946831-1c5fb380-2423-11e9-8faa-1bb64eef8db3.png)

moreover, even traffic in the opposite direction stops at the passage of the CP driver (black car) in any case while driving on the road
CP version: 6.01.00014
No mods

**Comment by Satissis** [comment]
Yeah it's a known bug and something Thomas is working on.
