### ISSUE TITLE
Connecting tracks failure

### ISSUE THREAD

**Issue by Cassio38** [Courseplay/courseplay#3018]

**Comment by Cassio38** [comment]
problem with 6.01.00014

on this page
https://courseplay.github.io/courseplay/en/manual/index.html#generateCourse
on the second diagram, we can see how connection lane behaves.

however, when a field have weird shape, the connecting track between the inner headland and the "standard field work U shape" can lead through the entire field.
I have a field with > 2500 waypoints.
a connecting path exist between waypoints ~600-750 (inner headland) and ~1200-1350 (shared path between headland and the next step in the field). Entering this zone cause combines to stop. Exiting the 1350th waypoint leads combines to waypoint 1 instead of 1351.


also another problem : sharp turns (more than standard 90° manoeuvres) around a green-red manoeuver waypoint seems to cause combines to spin around a waypoint

thanks again guys ! cheers !

**Comment by Cassio38** [comment]
also
when you have two overloader on a path, the second one keep to bump the first one while waiting instead of keeping its distance behing it

**Comment by Cassio38** [comment]
when having two overloader, if one goes to combine 2 and drive along it, the second overloader will be blocked by the first if it aptemp to reach the first combine of the convoy

**Comment by Cassio38** [comment]
can we draw something easily here ? i would be so much easier and clearer to explain thing than spelling it =D

**Comment by Cassio38** [comment]
![image](https://user-images.githubusercontent.com/20385247/51944093-6f356d00-241b-11e9-9776-6563fcfb2905.png)

oh man ! i can do this ! 
so.
when the blue overloader try to overtake the red one, it will bump into it instead of avoiding it.

**Comment by Cassio38** [comment]
![image](https://user-images.githubusercontent.com/20385247/51944407-41045d00-241c-11e9-854d-38026439648a.png)

ohboy. i like it.
When a overloader go back to unloading, it go straigh to the waypoint without worrying about obstacle (or other combines)

**Comment by pvajko** [comment]
1. won't change how the connecting tracks are generated. Yes, sometimes you have to drive a lot on the headland. It is a lot more complicated than you think.
2. I'll address the stopping/continuing on the connection track issue and ignore all the others. Some of them are already reported, please check. For the others, open one issue for each and do not throw in a million problems in the same issue.

**Comment by pvajko** [comment]
Please post a log with debug channels 12 and 14 enabled for the connecting track problem.

**Comment by Messy71** [comment]
for the spin around in a loop problem try bumping up the turn circle value

**Comment by pvajko** [comment]
Closing due to inactiity
