### ISSUE TITLE
Headland turn not working as intended

### ISSUE THREAD

**Issue by TheAngryGamerTAG** [Courseplay/courseplay#3019]
im having and issue where if i set a tractor with a trailer on a field to do something the driver on turns ( so far i only noticed on 90 or small degree turns ) the tractor will jackknife and get stuck in an endless loop in reverse circles just wanted to see if there was anyone having similar issues. Thanks

**Comment by Messy71** [comment]
Try playing around with the turning circle value.
On Ravenport / Field 7/ Horsch 12 XL Cultivator/ Fend Vario 1050 double wheels, if the value is 18 or under it goes all the way at the and of the straight line and after turn it doesen’t hit the waypoint on the next line and get’s stuck in a circle loop. 
If set to 20m (19 m also works but bearly) does work either with turns on field or outside the field. Good luck.

**Comment by ftasch** [comment]
I'm having the same issue using Courseplay v6.01.00015. When using a tractor with the Pöttinger Hit 12.14T to make hay. Using a course with no headlands the driver will start to follow the course nicely. However on the first turn, with "turn on field" active it will start to reverse and then it starts to get crazy. 

It does not show the same behaviour everytime. Sometimes it will start to reverse and goes in never ending circles. And sometimes it will stop reversing after a short time and then start circling forwards for some time before returning to drive in the middle of the next lane, skipping one completely.

I tryed changing the turning circle value in a wide range, this didnt change anything in its behavior as far as i can tell.

![2](https://user-images.githubusercontent.com/47152600/51980070-33d48600-248f-11e9-902c-9ab0efb53a52.png)
![1](https://user-images.githubusercontent.com/47152600/51980071-33d48600-248f-11e9-8f7d-55e1c3b05f7f.png)

These two pictues (1: going forward, 2: going in reverse) show both situations, after moving along one lane and reaching the final point before turning.

Without "turning on field" everything works fine. So maybe some bug when reversing with trailers ?

**Comment by ftasch** [comment]
And here is the log from starting the course to some reverse circles ... it shows case 2.

https://www.dropbox.com/s/oz8givax6mjm3q7/log.txt?dl=0

**Comment by TheAngryGamerTAG** [comment]
Thank you lots ill let you know if it works i increased the turning radius from default to 20 Mnl or whatever it put it as im currently testing now ill let you know here if it fixed my issue!

**Comment by Satissis** [comment]
Try again with v6.01.00017 and report back.

**Comment by ftasch** [comment]
Tried again with v6.01.00018 and same as before. Still caught in permanent reversing.

Just in case it is still needed: 

[log_1.00018.txt](https://github.com/Courseplay/courseplay/files/2816961/log_1.00018.txt)

![1](https://user-images.githubusercontent.com/47152600/52051847-0f42e180-2555-11e9-8314-1025a3da4a89.png)

**Comment by GeorgeEarslight** [comment]
Did you try lowering the reverse speed? I've had problems reversing with more than 5km/h.

**Comment by ftasch** [comment]
Yes I tied from 3km/h up to 15km/h. Same behaviour only with different speed. Might have something to do with the elevation though, having more problem on those steep fields like 27 felsbrunn, less so on 20.

**Comment by Messy71** [comment]
**Courseplay v6°01°00019**
Ravenport - Field 8
Starting point NW  / driving direction 90° E (Manual) / No headland / Turn on field Activated
Tractor : _Fendt 1165 MT1 **by Stevie(#mod)**_
Cultivator : Horsch 12XL
Tool working width : 12 m
Tool offset : 2.9 m 
Turning circle (mnl) : 18 m
Turning speed : 20 kph
Reversing speed : 16 kph
I've noticed that **(when you're in the tractor and)** CP drives it , at the end of a straight line he goes all the way to the end, lifts cultivator, turns to the next line, starts reversing all the way at the first waypoint in the line puts cultivator down and drives straight for the next sequence.
**Whenever i'm not in the tractor** CP will drive all the way at the end of the straight line **_it doesn't lift cultivator_** , starts reversing , turns for the next line and aligns himself (**_doesn't reverse all the way to the edge of the field_**) with the nearest waypoint and keeps driving for the next sequence.

**_About the turning in circles maneuver_** i've found that by tweaking the last 3 settings : _Turning circle(mnl) **,** Turning speed **,** Reversing speed_ you can make things work **but** it also depends on the smoothness of the field /or incline. (I've done all the field all the way at the end where at last couple of lanes it changes the turning directions so he doesn't go outside the field. I've changed the Reversing speed to 15 kph and started working normally.)

**Comment by ftasch** [comment]
Well as far as i can tell it now works fine when making hay with the Pöttinger Hit... When using a modded plow it still seems to have some trouble, but that might well be a problem with the mod and thus currently not really important. Will have to test that with some other tools :)

Well that is as long as there is only one trailer. Those configurations with a seeder and a seed cart are still not reversing correctly. But looking at its behaviour im guessing this is just not implemented, yet ?

**Comment by Satissis** [comment]
Yeah plows.... the once from Giants we have hard coded some turn data into, like the width, tool offset and if they can be reversed with, that helps CP to decide about the correct turn maneuver.

The seeder and seed cart config will work fine if you turn off turn inside field.
Yes we haven't looked into them yet and we properly might make them do that anyway in the end, depending it the setup.

Headland corner is some @pvajko have made, so I'll have a chat with him regarding them and see who of us are going to try tackle it.

**Comment by Satissis** [comment]
Just referring this one to #3033 as it's might be the same problem and just to keep track of similar issues.
No update on when it will be fixed yet

**Comment by Fogest** [comment]
With the Cultiplow Platinum 8m I also see the same issue described in this issue. I see logs have already been attached, so here is a video helping to show the problem:

https://xboxdvr.com/gamer/duel-machinegun/video/69294898

**Comment by pvajko** [comment]
Try with v6.01.00073, reopen if it does not work.
