### ISSUE TITLE
Trailers not unloading all the way 

### ISSUE THREAD

**Issue by newride** [Courseplay/courseplay#3021]
When I do a grain transport the trailer only unloads one hopper

**Comment by Satissis** [comment]
Trailers with multiply hoppers are not implemented yet but are on our todo list.

**Comment by pvaiko** [comment]
@newride @ThomasGaertner  is this still a problem?

**Comment by ThomasGaertner** [comment]
still present . problem ? dunno,  would be a lot of work to implement these two trailers...
