### ISSUE TITLE
tip trigger reached

### ISSUE THREAD

**Issue by RayzerSharpe** [Courseplay/courseplay#3025]
Combined coures. 

I am on lifting straw from on felsbrunn field 18,19& 20 (combined) and i have a second course to sell it at the barn. The first load of straw runs super as it fill and sells it at the barn, but when the second loads fills and the tractors heads off for the second course to go to the barn, i get a tip trigger reached on the field (see atatched ). The tractors will go at a slow speed but will not empty when it get to the barn. If i stop the tractor and go again it resets itself an all is good

Btw keep up the great work. I know yous will log in to Github and cringe at the amount of new issues but keep at it. I know the feeling.

![image](https://user-images.githubusercontent.com/25461795/51949084-123db500-2423-11e9-865e-922c7d8aa9f5.png)

**Comment by RayzerSharpe** [comment]
Btw log is clean & i tried this with two different tractors..

**Comment by Knowen** [comment]
Morning,
i have the same issue. I tried diffrent modes and tractor + loading trolly combinations but nothing works as it should.

**Comment by Fogest** [comment]
I am seeing similar issues with unload triggers. I have a simple transport route where I am trying to get it to reverse a trailer of silage and dump it into the barn sell point. I have it reverse fine but it does not trigger to dump automatically when in the zone, and adding an unload point in my recorded route doesn't seem to make it dump either. Cannot seem to get the unload point to ever work.

**Comment by Knowen** [comment]
A tractor on grain transport or in mode2 works perfect with a tip trigger at a sale point or my silo. I have just this issue when I merge a working route, like collection straw with a loading trolly, and transport route to my silo.

**Comment by pvajko** [comment]
Can someone post a log with debug channels 1, 2, 12 and 14?

**Comment by Knowen** [comment]
Gonna do it tomorrow

**Comment by Fogest** [comment]
My issue is related to the unload point when unloading at the barn and I think is a totally different problem as it's not related to the tip trigger so I will create a new issue where I will put my log and video @pvajko

**Comment by Knowen** [comment]
Just driven a lap. Have the loading cart in the run to 95% filled. After a few meters he drove to the silo. Everything as it should. When the loader wagon was full for the second time, it displayed tip trigger reached directly at the start of the unloading route.

A log with Debug Channels 1, 2, 12 and 14 is attached.
[log.txt](https://github.com/Courseplay/courseplay/files/2823010/log.txt)

**Comment by pvajko** [comment]
@Knowen 
> it displayed tip trigger reached directly at the start of the unloading route
But it kept moving right? Is there any other problem here other than the display of the tip trigger message?

**Comment by Fogest** [comment]
From what I am reading it sounds like it is saying that the trigger is reached despite it not actually being reached, and it is not actually emptying when it gets to the barn.

**Comment by Knowen** [comment]
> 
> 
> From what I am reading it sounds like it is saying that the trigger is reached despite it not actually being reached, and it is not actually emptying when it gets to the barn.

That's right. And yes the tractor is moveing with 10km/h and not with 35km/h, as i setup as speed on streets.

**Comment by pvajko** [comment]
Ok, thanks, this goes to @ThomasGaertner then.

**Comment by ThomasGaertner** [comment]
try v 00035 or higher and report....

**Comment by Knowen** [comment]
Hey, gonna test it later this day. In case it doesn’t work, which debug channels should be activated for a helpful log?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Paajohtaja** [comment]
Straw collecting and selling to the barn course works now. But it has still a minor bug, loading wagon wont take full load. I use the Schuitemaker Rapide 8400W, load capacity is 53000. When the wagon has loaded little above 52000, it stops collecting and starts the sell course to the barn.

**Comment by ThomasGaertner** [comment]
@Paajohtaja : I will close here, if its very disturbing, please open a new issue for that...

**Comment by Knowen** [comment]
@ThomasGaertner i can confirm, that the tip trigger reached bug isn't there anymore. The transition from normal field work to transport to the silo resulted in an error. The team went right north and the starting point for the silo transport was in the south. At the turning direction starting point, it ended in endless circles. 
Here is a log with 12, 13 and 14 enabled.
[log.txt](https://github.com/Courseplay/courseplay/files/2828978/log.txt)

**Comment by pvajko** [comment]
@Knowen open a new one on that and make sure you have the debug channels turned on *before* it starts  circling.

**Comment by Knowen** [comment]
Nevermind. It’s working now. I made a mistake in setting the course up. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RayzerSharpe** [comment]
Working as expected now ..cheers all
