### ISSUE TITLE
Repeated attempt to call method 'getAITurnRadiusLimitation' when connecting to trailer

### ISSUE THREAD

**Issue by Altanzar79** [Courseplay/courseplay#3026]
Whenever I connect to a Modded Fliegl DPW 180 Roundbale autoload trailer the game slows down, is unable to save and/or disconnect from the trailer.  I can only quit the game and restart.  I have tried connecting to the trailer from a fresh start, before hiring any workers or starting any courses and still got the error.  I did remove courseplay and was able to use the autoload trailer without any issues.

Here is what is being spammed in the logs:

2019-01-29 18:04 Error: Running LUA method 'update'.
2019-01-29 18:04 dataS/scripts/vehicles/ai/AIVehicleUtil.lua(320) : attempt to call method 'getAITurnRadiusLimitation' (a nil value)

Log attached.
[log - Copy.txt](https://github.com/Courseplay/courseplay/files/2810288/log.-.Copy.txt)

**Comment by pvajko** [comment]
Sorry, have no time to deal with mods in the beta phase.
