### ISSUE TITLE
No longer recognized as a mod

### ISSUE THREAD

**Issue by Asylumm** [Courseplay/courseplay#3027]
Just updated to the newer version of CP that was released on 1-29-19, and the game no longer recognizes the mod. I've deleted and reinstalled about 10 times with no luck. Disabled and removed all mods as well to make sure they weren't the problem (even though they were working just fine the older version). Any help on this would be awesome as I'm having a great time testing and using this mod. Keep up the good work.

**Comment by Messy71** [comment]
try to un-zip the files in coursplay-master into a folder, select all of them and create a new archive named FS19_Courseplay.zip  and place it in the mods folder in FS19 , it worked for me, good luck.

**Comment by Asylumm** [comment]
I'm installing from the new version that was just released. Did you have to make a new zip file for that as well, even though there is a zip file in there now and not just a master file. Also, the install instructions were changed to just copy the zip file into the mods folder now instead of making a new zip file.

**Comment by Messy71** [comment]
i don’t know for sure if is still the folder inside ( courseplay-master ) last time i downloaded 2h ago it was. Devs move so fast, i love it doe.  Just try unziping the archive and create a new one with the file you find inside.

**Comment by Asylumm** [comment]
yeah I've tried downloading all the different versions I can find even the one I originally downloaded and dont see the master folder anymore. I know what youre talking about because I did that on my original install, but dont see it now. Oh well guess I'll wait a couple days and see if others have this problem or if something else updates. Thanks for trying.

**Comment by sootysax** [comment]
![fsscreen_2019_01_29_21_44_17](https://user-images.githubusercontent.com/6591048/51954727-5757ec00-240f-11e9-8792-10e287490c47.png)

**Comment by shadow250** [comment]
use the one on this site its the original but in beta. the courseplay master is still there

**Comment by Satissis** [comment]
Did you do it like this:
http://courseplay.github.io/courseplay/en/installation/index.html

**Comment by Asylumm** [comment]
> Did you do it like this:
> http://courseplay.github.io/courseplay/en/installation/index.html

When installing the very first version that came out on Farmingsimulator19mods.com I did the installation as it said. Coping the master folder into a new .zip folder and pasting into mods folder after that. Everything worked great. On 1-29-19 there was a new version that came out, and I just copied the zip file straight into the folder as the install instructions said. The game no longer recognized it as a mod. I uninstalled and re downloaded the courseplay master version and made a new .zip file and re-copied to mods folder, and it still doesn't recognize the mod in the list. I haven't downloaded any other mods since then. Not sure what's going on at this point

**Comment by Satissis** [comment]
hmm
did you recheck if it's active in your modlist when loading the savegame?
Some times if you change the zip name it's will turn off that mod and have to be reactivated.

If that's not the case, then upload the log here.
and just to be sure, upload the zip file you are using as well just so I can check it
