### ISSUE TITLE
Suggestion: EnhancedVehicle implementation

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3029]
It seems like EV is going to be the replacement for Drive Control, so it would be nice to be able to implement the front and rear axle locks and the 4WD like was done with DC in the past.

The only issue i'm having with the shuttle control on EnhancedVehicle so far is that if I am switched to reverse and start a course the vehicle will start in reverse.

**Comment by Tensuko** [comment]
Vehicle Control Addon (VCA) is doing a good job and works automatically for Vehicles even controlled by CP.
I recommend useing that one, as we don't have much time either to implement Enhanced Vehicle.
