### ISSUE TITLE
Driver AI

### ISSUE THREAD

**Issue by iwan4672** [Courseplay/courseplay#3031]
Driver AI does not stop before obstacles ( tractors, combine harvester, cars)

**Comment by Dennis10061983** [comment]
Moin weiß man schon woran es liegen könnte ?

**Comment by pvajko** [comment]
Ja. Zeitmangel.

**Comment by Dennis10061983** [comment]
Aso alles klar
trotzdem schon klasse was alles läuft 
Hut ab

**Comment by ThomasGaertner** [comment]
try again with v00062 or higher and report

**Comment by iwan4672** [comment]
Unfortunately how conflict was from vehicles, it is so still.
For I explanation I send from CP17 demonstrative films and CP19.
There is no conflict in CP17 from vehicles.
FS19
https://youtu.be/L2FPayrJtG4
FS17
https://youtu.be/kjdZTJ-_o6g

**Comment by ThomasGaertner** [comment]
#3193
