### ISSUE TITLE
Tools with additional tanks problems

### ISSUE THREAD

**Issue by sikor79** [Courseplay/courseplay#3034]
Perhaps I set something wrong, but I have problems with seeding or fertilizing using attachments which have additional tanks. I already used:
Vaderstad Tempo V8 + Vaderstad FH2200
Kuhn Deltis 1302 + Kuhn PF 1500
For Vaderstad I set work course + refill track. At the resupply point i put bags with fertilizer as this seeder don't take too much of it. Everything works perfect and CP refill fertilizer every time when seeder run out of it, but when seed level goes under 2200l which empty seeder (additional tank was full of seed), CP start sending tractor at the fertilizer point. As there wasn't  any seed to resupply it continuous until I didn't put there seed.
Similar situation happens with Kuhn sprayer. I just set a work course as there was more than enough fertilizer to spray whole field, however, when main sprayer was emptied, CP stop tractor even as additional fertilizer tank was full.

**Comment by pvajko** [comment]
Try with v6.01.00016 and report back

**Comment by sikor79** [comment]
Unfortunately it is even worse now. With Vaderstad my tractor continue seeding when fertilizer is empty, and still try to resupply it when sewing machine is out of seed but seed tank is full. Nothing changed in the spraying with Kuhn sprayer, CP stop work when sprayer becomes empty.
Tested with v6.01.00018

**Comment by pvajko** [comment]
Seeding without fertilizer was a requested in #2955 and as we have no option (or time to implement) at the moment to enable/disable this I decided to hardcode enable it (as the commit message also says) thinking this is better then always stopping when running out of fertilizer.

For the Kuhn, please post a log with debug channel 14 enabled.

**Comment by sikor79** [comment]
Ahhh kk I missed your explanation... Attached log from Kuhn ( I hope it is correct one)
[log.txt](https://github.com/Courseplay/courseplay/files/2818249/log.txt)

**Comment by pvajko** [comment]
Try with 6.1.21 or later and report back

**Comment by sikor79** [comment]
Works fine now, great work!
