### ISSUE TITLE
Game won't save

### ISSUE THREAD

**Issue by Casmas** [Courseplay/courseplay#3035]
[log.txt](https://github.com/Courseplay/courseplay/files/2812543/log.txt)
Game worked fine until I downloaded the Custom Modding 9R tractor today. With Courseplay disabled it saves the game but as soon as i enable courseplay the game won't save and get an error in the log.

So not sure if this is a mod error or a courseplay error.

**Comment by Wadeeb** [comment]
I have the same problem [https://gist.github.com/Wadeeb/65538b104d9bc2addf3e5724e897e3a5](url)

**Comment by Wadeeb** [comment]
I have the same problem
logfile https://gist.github.com/Wadeeb/65538b104d9bc2addf3e5724e897e3a5

**Comment by Wadeeb** [comment]
I think it is the 9R mod. I removed it and was able to save several times. I added it back in and bought it and could not save after a couple of times.

**Comment by Wadeeb** [comment]
I have read on a comment on Custom modding's FB page that this is due to them using a custom vehicle type but impossible to confirm since they have locked the zip file for the mod. Too bad since its a nice mod. large file size though.

**Comment by Casmas** [comment]
There is an unlocked version available now. I was looking into the issue but can't work it out. Someone posted about changing vehicle type to tractor but seems to be set at that currently.
