### ISSUE TITLE
Problem with mods that change fill capacity

### ISSUE THREAD

**Issue by DrTarr1962** [Courseplay/courseplay#3036]
This is probably a low priority issue, but I wanted to post it for your information.  For example I made a mode 1 route to transfer grain from one silo to another.  With a stock trailer it worked with no problems, but if I changed the capacity in the xml of the stock trailer then it wouldn't activate the triggers and just keep driving back and forth to each silo.  I also noticed that the options to pick what crop loaded, and how many trips were missing in the drive menu.  

Something I think might be related.  I was using the biggest combine in the John Deere Pack OY mod.  It would only work if I had a chaser trailer near it.  Kind of like a forage harvester.  So my best guess would be that when the fill capacity is changed, CoursePlay sees the trailer, or combine, as having no capacity.

This is with version 6.01.00015

Thank you, and hopefully I wasn't to confusing.

**Comment by BostonJohnny1226** [comment]
I was having problems with trailers with a capacity greater than 99,000. Something you may want to check.

**Comment by DrTarr1962** [comment]
I'll test that out.  I know the combine cap was 100,000 so that's what I set the trailer at.  Thanks.

**Comment by Berndie5** [comment]
is identisch with #3011 , CP Error...but Mod Issue....
