### ISSUE TITLE
seed and fert refill course

### ISSUE THREAD

**Issue by TheAngryGamerTAG** [Courseplay/courseplay#3037]
Okay so i made a refill course for a seeder fertilizer and the seeding course on the field, so i set the helper off and the helper ran out of seed as expected and the helper went thru the course to refill and my seed was out and the fert wasnt so it went past the seed fill point filled up then went past the fert point stopped and attempted to fill up which it didnt but it say there with a prompt to stop the refill but it took money anyway as if it was refilling a really large tank so i stopped it cause i figured it was doing nothing and it went on but charged this may have something to do with the mod i was using it but it worked just fine with the seed refill point

This is the mod link thru modhub  :    http://www.modhub.us/farming-simulator-2019-mods/placeable-filling-stations-all-in-one-v1-3/

**Comment by TheAngryGamerTAG** [comment]
also im on last two digits  14

**Comment by sootysax** [comment]
have you tried a different set of placeables?

**Comment by Satissis** [comment]
Not so sound rude or anything, but we don't want to have anything to do with mods from modhub.us
They steal other peoples mods and upload them there without anyone's permission.
Yes this include the version of CP that is there.

**Comment by pvajko** [comment]
Don't have time to spend on mod issues during beta.
