### ISSUE TITLE
Combine unload

### ISSUE THREAD

**Issue by BostonJohnny1226** [Courseplay/courseplay#3038]
The tractor is unloading the combine which is on his right and the trailer is now full. He now needs to go to the right to get to the start point of his unloading run. Instead of letting the combine pass him or backing up some, he tries to cut in front of the combine and they end up colliding.
Could it be made so either:
The combine waits until the tractor passes him.
The tractor waits until the combine is out of the way before turning right.
The tractor loops around to the left to get to his start point.

Thanks for CP! I wouldn't be playing FS without it

**Comment by Satissis** [comment]
This might be related to the traffic collision not working yet and it's being looked into.

**Comment by Insanelycrazy14** [comment]
All my regular harvester seem to work ok but the beet harvester is doing that not sure why the tractors wont just always turn away from harvester then find the route to start

**Comment by ThomasGaertner** [comment]
#3140
