### ISSUE TITLE
Game Crash (log) while spraying liquid manure

### ISSUE THREAD

**Issue by Mannelig83** [Courseplay/courseplay#3039]
Hello,
Had a Standard sprayer Course on Felsbrunn Field 17 and the Driver drove off the field. then i brought him back and started again the Course and after 1 row he drove off heading to the dealer (no Course) and game crashed.
i will attatch a log.

https://pastebin.com/nfmstgPR

Second Thing:
he dosent reload the manure Barrel (venhuis premium integral II) with stuff from modded silo (guess Maybe there is something with the silo).
just wanna let you know.

third:
The tractor stops still on the End of Headlands when not in tractor with Version .15

Closing i wanna thank you guys for your work.
is there a way to donate?

Greets Markus

**Comment by TinyCrocodile** [comment]
For donating see here

http://courseplay.github.io/courseplay/en/index.html

**Comment by pvaiko** [comment]
These should all have been fixed by now.
