### ISSUE TITLE
Refill course

### ISSUE THREAD

**Issue by Frodo65** [Courseplay/courseplay#3043]
Hi all,

I have a problem with refill of machines.

I have the placeable Fillstations on the map. So I create a refill course for the machines.
The fertilizer Kuhn Axis 40.2 stops and is filled. The seeder amazone d8 30, the bredal K105 and also the Kuhn Deltis 103 don't stop at the stations and won't be filles 

Frank

**Comment by n00el** [comment]
Bredal K165 not stopping to me, too, at lime refill station.

**Comment by Knowen** [comment]
At the refill station the trigger is detected, but it is not stopped and filled. At least not with seeds. When the fertilizer stops, wait until it is filled up and then continues. Even when he drives off to replenish seeds, he simply drives past the refill station.

**Comment by ThomasGaertner** [comment]
could you please check, that you selected fillType is the one, you want to load at the trigger ?
these are multiple choice trigger so we hav to tell them, which kind of FillType we want to load...

![image](https://user-images.githubusercontent.com/3279913/52174359-c4aea880-2792-11e9-9b55-8a85db1cc99c.png)

**Comment by sesmo** [comment]
Yes... I confirm... A have do the same for seeds and fertilizer... the result is the same. The tractor doesn´t stop...
 At least is possible for now make the tractor stop? we can do the fill manualy.... 

![2019-02-03](https://user-images.githubusercontent.com/25755540/52175861-29253400-27a2-11e9-98ee-b4dc7156110b.png)

**Comment by sesmo** [comment]
@Raints  In FS17 I use always waitpoint there and works fine... After read your comentary I made a refill course without wait point, and the tractor doesn´t stop again,

**Comment by Knowen** [comment]
@ThomasGaertner Gonna test it later with a log. Which Debug Channels do you need? 
But I'm pretty sure I have set this with every device. Whether lime, fertilizer or seed. 
@Raints @sesmo There is no need for a Waitpoint. CP detects the refill station by himself and should wait and refill. Sometimes it didn't stop but he starts to refill while he is driving foreward. Sometimes he just drives thru the station.

**Comment by ThomasGaertner** [comment]
what map is it ? do you have a savegame and courses for me ?

**Comment by Frodo65** [comment]
Hi

I'm playing the standard Felsbrunn. CP is the newest version (06.01.00036).

At the moments the only what is not ok is lime. The tractor recognize the trigger but drives through.

the course are here
https://drive.google.com/file/d/1p9z8YgprBEzvW9HIZcBq-CXldfoy9rJV/view?usp=sharing

teh savegame is here
https://drive.google.com/file/d/17aF0juscxm-yyrvZW4YrgNmqZ-6yfZ5M/view?usp=sharing

Frank

**Comment by Frodo65** [comment]
Another question to this problem.

This evening I started on a new map. (Don Diego Map).

Is it possible that the fillingstations that work on the Felsbrunn Map didn't work on the Don Diego Map?

Frank

**Comment by ThomasGaertner** [comment]
please try again with v00042 or higher and report

**Comment by tjBerlin** [comment]
hi, i have the maybe same problem: cp driver doesn't load at the trigger. 

I am using cp version .00044 on RAVENPORT, no mods. CP driver is mode 1 (Beladen am Startpunkt). Driver drives to waypoint 1, but doesn't stopp or load.

![bildschirmfoto 2019-02-06 um 06 28 18](https://user-images.githubusercontent.com/24283753/52322290-d6818d00-29d8-11e9-9ef1-8bf6bb75d546.png)

![bildschirmfoto 2019-02-06 um 06 28 28](https://user-images.githubusercontent.com/24283753/52322306-f31dc500-29d8-11e9-8862-36d8cb35df9f.png)

Here is the log with debug 1, 2, 12 and 14. 

[logRP.txt](https://github.com/Courseplay/courseplay/files/2834974/logRP.txt)

**Comment by ThomasGaertner** [comment]
@tjBerlin :which trailer is it ?

**Comment by tjBerlin** [comment]
It is the Aperion 3401, an in game trailer.

**Comment by tjBerlin** [comment]
> @tjBerlin :which trailer is it ?

@ThomasGaertner: Just as you asked for the trailer, I just tried it again with other combination. I used the JOSKIN and the KRÖGER HDK 302 with the KRÖGER TDK 302 and CP version .00046.

I didn't work. Both driver didn't load. For a second CP was telling me: "wird beladen. 00000 bis 42000", but the vehicle didn't stopp. 

Here is the log with dbg 1, 2, 3, 12 and 14. 

[log.txt](https://github.com/Courseplay/courseplay/files/2837188/log.txt)

**Comment by ThomasGaertner** [comment]
unfortunately I cannot replicate it. can you give me the savegame and courses ?

**Comment by sesmo** [comment]
@ThomasGaertner 

Only a suggestion of who is a noob of the subject: The problem will not be on the trigger ?. There are many different mods and made by different modders. I've seen mods with deleted command lines and others changed.

I did my warehouse mod. Each warehouse serves a unique type of product. And I may have accidentally deleted some command line in the file, and it is now being resolvable because the trigger is not recognized.

Just an idea ... !!!

**Comment by ThomasGaertner** [comment]
@Frodo65 : can we close here ? is it still valid with the latest version ?

**Comment by Frodo65** [comment]
Yes.  We can close it.

Am So., 17. Feb. 2019, 16:45 hat Thomas Gärtner <notifications@github.com>
geschrieben:
