### ISSUE TITLE
Combi Route Tractor-Trailer will not drive to harvester when tank is full and pipe is over fruit 

### ISSUE THREAD

**Issue by VergylTantor** [Courseplay/courseplay#3044]
When the harvester is full and it stops with the "pipe over fruit" the overloader will not leave it's start point to get the load.
CP v6.01.00015 edit; Also v6.01.00017 (I missed a couple of versions)
No Mods
Ravenport Field 8 (have seen on other maps)
Happens with CR10.90, John Deere 580, Tractors and Trucks.
Active CP paths: Combi for overloader and Field work for harvester
[log.txt](https://github.com/Courseplay/courseplay/files/2814765/log.txt)

**Comment by sirbum69** [comment]
i had this same issue, so i turned off path finding and it worked. being that it doesn't seem to cause crop damage when CP is running the tractors

**Comment by VergylTantor** [comment]
Thanks for the tip

**Comment by mdradek** [comment]
I can confirm, turning off path finding works.

**Comment by VergylTantor** [comment]
In CP17 If the harvester was full and the pipe was over the crop it would stop then the overloader would release to get the load. I would hope that this would return to CP19.

**Comment by ThomasGaertner** [comment]
#3140
