### ISSUE TITLE
Unloading on Street

### ISSUE THREAD

**Issue by tobiasw83** [Courseplay/courseplay#3045]
Hello, for a beta, the whole thing is really great. What I have found so far, if I send the driver away with "Immediate unloading", he always wants to drive to the first waypoint and not to the nearest to then continue the course to the silo.

Then he does not unload at the point where the silo is but starts behind it and distributes the cargo on the road.

greeting
Tobias

**Comment by tobiasw83** [comment]
HI, yes. Have the course redone, then it works a while and then he suddenly unloads again behind the unloading. Tobias

**Comment by ThomasGaertner** [comment]
Still valid for current version. ?
