### ISSUE TITLE
Railroad Silo East on Ravenport not tipping

### ISSUE THREAD

**Issue by Flacwby** [Courseplay/courseplay#3046]
When transporting anything to the Railroad Silo East CP does not stop and unload. It seems to occur only if the silo has any amount of that grain already stored. If 0 Soybeans, then the tipper will unload, but if there's just 1 Ton or more of Soybeans, then it won't unload (Soybean is just used for example).

**Comment by Danatru** [comment]
I'm having the same issue. Courseplay doesn't seem to recognize this as a tip trigger in Combi mode.

**Comment by mehdinasef** [comment]
same thing hapens in the trainstations's silos in the enstancia lapacho map

**Comment by ThomasGaertner** [comment]
could you give me an update, whether its still an issue with v00045 ?

**Comment by Danatru** [comment]
I'm already running v00046 so I don't know if v00045 would make a difference but as far as I can tell it's still not working. Fired up a test save, the only mod I loaded was courseplay, and when I try a combi mode run it just drives straight through the silo. 

Here's a link to the log https://gist.github.com/Danatru/b9b70722d8cc612dbe7b1fa5ecc72563
[Ravenport Railroad.zip](https://github.com/Courseplay/courseplay/files/2836939/Ravenport.Railroad.zip)

I tried adding my savegame and courses not sure if it works or if that helps, the course is "test"

**Comment by Flacwby** [comment]
I used v00045 last night and I did notice that the tipper was now triggering at the Train station silos. I ran 3 or 4 runs with it and all stopped and tipped.

**Comment by Danatru** [comment]
Saw Flacwby's comment so I tried again with another course and this time I did get it to tip on multiple occasions, I didn't update anything so I'm at a loss as to why it wouldn't do it earlier.

**Comment by Flacwby** [comment]
Well for me this stopped working again with v00049.

**Comment by roadrunnerR74** [comment]
same here

Den fre. 8. feb. 2019 kl. 22.40 skrev Flacwby <notifications@github.com>:

**Comment by Flacwby** [comment]
Well I think I'm going crazy. v00054 it's now working again.

**Comment by ThomasGaertner** [comment]
@Flacwby : can we close or not ?

**Comment by Flacwby** [comment]
Well it doesn't work now w/V00064. I don't know what to tell you. Bottom line it works sometimes, sometimes it doesn't.
