### ISSUE TITLE
While Combine is being unloaded CP says it's "Slipping"

### ISSUE THREAD

**Issue by Flacwby** [Courseplay/courseplay#3048]
While a combine is unloading it's grain, CP says its Slipping. As soon as it's unloaded the the tipper driver drives away and the combine starts moving, the slipping report goes away.

![image](https://user-images.githubusercontent.com/24375624/52066269-d4817f00-253d-11e9-93f3-1cfbf29f5e7a.png)

**Comment by Tensuko** [comment]
Just some Cleanup, this is part of mode2 rework #3311
