### ISSUE TITLE
Trailed harvesters not working with CP

### ISSUE THREAD

**Issue by 1234Eldo** [Courseplay/courseplay#3052]
Courseplay version: 6.01.00018
NO MODS
Link to log: [https://gist.github.com/1234Eldo/bfb1b565ea895882958dbf10dc7d5880]

No trailer harvesters can be unloaded via courseplay mode2.  "Combi" mode vehicles do not recognize the harvesters as "harvesters", so unsuccessfully scan indefinitely.  In the vehicle actually pulling the harvester, whether running a "fieldwork" course from CP or I'm driving it manually, the CP "combine control" button is grayed out (the CP icon furthest left, usually available when in a harvester).  I tested this with all the stock Giants trailed harvesters (potato, sugarbeet, and sugarcane), and also tested the Mex5 3-point tractor mounted forage harvester.  No "harvester" recognition on any of them.  

While using CP to run the harvester "fieldwork" course, the trailed potato and sugarbeet harvesters will proceed normally until their tanks are full, then stop and wait to be unloaded - normal behavior.  The trailed sugar cane harvester will proceed only if pulling a wagon itself, then stop when full, and if no trailer is attached, will not commence harvesting without a viable trailer in range to empty into - normal behavior.  The Mex5 3-point tractor mounted forage harvester, however, will proceed into the field with or without a viable trailer in range and harvest the entire field.  It also will NOT deploy the unloading pipe if in a folded state before activating the CP driver.

**Comment by pvajko** [comment]
opened #3056 for the Mex5 as that's a different issue.

**Comment by pops64** [comment]
The specialTools.lua file has to be updated to reflect the change in file names for the trailed harvesters. Also assuming CP still recognizes this special flag variable that is in specialTools. This was a issuse in 17 for mods that were trailed harvesters

**Comment by pops64** [comment]
Give me 10-15 mins and I will make a pull request has well has put the file here until the CP team can approve and merge it

**Comment by pops64** [comment]
So I have the specialTool file working but as I suspected the way CP recognized this variable as not been updated. I am still working on figuring out how it was done in 17 but to me it seems to me that it shouldn't have worked at all ... @pvajko this would go to Thomas as I am sure this is a 2 sec fix for him

**Comment by ThomasGaertner** [comment]
please test again with v 31 or higher and report

**Comment by 1234Eldo** [comment]
Courseplay version: v6.01.00069
NO MODS
Link to log: [https://gist.github.com/1234Eldo/5479777d7896d4e62c1e7b6c3bf39c08](url)

Set up new savegame on RavenPort with only courseplay in mod folder as before.  Obtained Rooster604 trailed beat harvester with JBC FastTrac 4220 to pull harvester, and the Lizard 1978 pickup with HW80 wagon to empty harvester.  Set up "Fieldwork" course on field10, starting SW corner heading north (no headland) for the JBC and harvester.  Set up "Combi" course for the pickup and wagon between south rail grain elevator and SW corner of field10.

-combine control tab (furthest left CP icon) is still unavailable (grey-ed out) on JBC pulling harvester while running harvesting/fieldwork course
-CP driver of JBC pulling harvester will not extend pipe to be unloaded. Have to stop course, manually extend pipe, then re-start course from current waypoint.  CP driver will not automatically retract pipe either after empty.
-Lizard pickup pulling wagon correctly heads for the harvester when set fill level is reached, but turns directly into JBC/harvester if approaching from the front of the JBC.  If approaching from the rear, will properly line up on the correct side and attempt to unload.  Since the CP driver of the JBC doesn't extend the pipe, the pickup follows in this position until the harvester is full, then both vehicles stop.
-Upon stopping the JBC CP driver, manually extending the harvester pipe and unloading, then resuming the course with the pipe left extended, the next time to pickup attempts to line up for another harvester empty, the game freezes spamming this error:

> /mods/ZZZ_courseplay/combines.lua:484: attempt to index field 'spec_drivable' (a nil value)
2019-02-13 19:09 Error: Running LUA method 'update'.

I must then force shutdown the game.  This exact same scenario repeated 3 out of 3 tests, crashing in the exact same spot each time.  Because this happens every time, I was unable to test further.

**Comment by Tensuko** [comment]
Very old Issue and not sure if this is actual with V232 or higher.
Reopen if that one is still actual or make a new Issue.
Closed.
