### ISSUE TITLE
Combi mode Truck/Tractor will not drive to Harvester with automatic engine start

### ISSUE THREAD

**Issue by VergylTantor** [Courseplay/courseplay#3058]
If the player is "riding along" with the CP Driver the overloader will stop moving and it will idle for about 30sec normally. But then it will start to sound like a machine gun or small boat motor and it will not move. 
If the player stands next to the truck all will work as expected.
Possible conflict with fuel saver mode?

**Comment by pops64** [comment]
Disable automatic engine start and it will work normally. See t#2912 Thomas mentioned this was not working
