### ISSUE TITLE
Courseplay6 not working on FS19 v1.1.000

### ISSUE THREAD

**Issue by khurrambaig007** [Courseplay/courseplay#3059]
Courseplay version: 6.01.00019
Hi 
i just download the courseplay files and put it into Game mod folder (FS19_CoursePlay6.zip)
C:\Users\Khurram\Documents\My Games\FarmingSimulator2019\mods

run the game, select the courseplay mod and start the game. Right click is not wokring
to open the couseplay hud.
When i press left ctrl+del. Courseplay hud is open. but no click event works in the hud. 

Please help me in this, and let me know if i am doing wrong in installing the mod.

Thanks.

**Comment by 37cee** [comment]
Did you unpack the zip file or did you just rename it?

If you just renamed it FS wont recognize the mod. When you downloaded the master file, right click it and unzip the files (right click and upack here). Go into the folder named "courseplay-master" , you should see a bunch of folders and files there. Mark all the files and repack them to a .zip file (name it zzz_courseplay6.zip). Move this new zip into the mods folder and courseplay should work (at least with recent version of FS installed). If you have older versions it might just not work, so download the patch in this case.

**Comment by Emzieh** [comment]
I have the update 1.2 from steam. I tried it with LS19_Courseplay19 and with zzz_courseplay     but nothing work. I see the hud with ctrl+del but i can´t click anything.

**Comment by khurrambaig007** [comment]
> 
> 
> I have the update 1.2 from steam. I tried it with LS19_Courseplay19 and with zzz_courseplay but nothing work. I see the hud with ctrl+del but i can´t click anything.

can you share the update 1.2 link. so i will download it an check.

Thanks

**Comment by pops64** [comment]
Try reseting your bindings

**Comment by Emzieh** [comment]
@khurrambaig007   I cant send you the update. Steam doing this automaticly

**Comment by snwkill** [comment]
My game is up to date and it is working fine for me

**Comment by Satissis** [comment]
@khurrambaig007 did resetting the bindings also work for you ?

**Comment by khurrambaig007** [comment]
No :(

**Comment by St0cki** [comment]
I had the same problem, it also didn't work to click anything in the hud.
A reset of all bindings solved the problem

**Comment by khurrambaig007** [comment]
@Satissis , i do five to six time reset the key binding, but its not working
after resetting nothing is changesd

![image](https://user-images.githubusercontent.com/5454894/52138216-5a044c80-266e-11e9-9c5a-78f2083b832c.png)

**Comment by kingcameron** [comment]
I had to mess about with key change and got it working try moving exit and enter mouse key I think it’s the right click you need to change then it will open it

**Comment by Satissis** [comment]
@khurrambaig007 one thing you might want to do is updating your game to v1.2.0.1
You can find the latest patch here for none steam version:
https://www.farming-simulator.com/updates.php?lang=en&country=us

**Comment by Satissis** [comment]
You are welcome. I'll close here then.

**Comment by nygage** [comment]
Hello, i have the same issue but with version 1.52, the hud does not open but when i enter on any vehicle it says: no loaded route. 
Can you help me?

Thanks
