### ISSUE TITLE
Support for Trailers with 2 Container, like Wilson trailer - also maybe tipside selection

### ISSUE THREAD

**Issue by PromGames** [Courseplay/courseplay#3060]
When in Cp mode 2, Wilson trailers with double bin offers to be filled the first bin.

When download at the silo, only unloads the bin at front. 

If you need son debug channels let me know.

Prom

**Comment by pops64** [comment]
I will answer for the CP team. This is a known issue to @Satissis . There was a quick and dirty solution implemented to get trailers working unfortunately it does not apply to trailers with more than two fill planes

**Comment by PromGames** [comment]
Thanks. I was looking at the code and the note from dev was there.

Maybe with a simple detection of two fill units could work for load and unload. At the end, is forcing to load units.unit 1 
			-- NORMAL FILLABLE TRAILERS WITH ALLOW TO BE FILLED FROM THE AIR
		elseif workTool.cp.hasSpecializationTrailer and workTool.cp.hasSpecializationFillable and #workTool.spec_fillUnit.fillUnits > 0 then
			-- Get the current exactFillRootNode.
			local exactFillRootNode = workTool.spec_fillUnit.fillUnits[1].exactFillRootNode; 

-- TODO: Handle multiply exactFillRootNode for trailers with more than 1 fill plane. (temp fix for now)

May this will also work with seeders that have also two units.

**Comment by SirAlbertL** [comment]
In the old system, when we pulled tandem trailers, the truck would pull foreword so the over loader, {in its trailer load/unload wait point] to fill the second trailer....... 

Could the scripts be done in such a way as to trick the game engine to "see" each  fillUnit , exactFillRootNode, fillVolume, and treat each one as a sepreat trailer and drive forwards until the next exactFillRootNode is under the overloader pipe, trailertigger.

Example, The Wilson Trailer and pup combination v1.0 link, http://modsfile.com/5dp680l68ige/WilsonPup.zip.html would see four fillrootnodes, and treat each one as if each was a attached trailer, with one collective fill capacity [total of all four fiullunits] that once filled, triggers the drive command to run transport course.


I know you guys have a 100 things to do, and not being a scriptwriter, I'm probably way off base, but I just thought it might be a temporary work around until a better method can be thought up.

God Bless and Thank you ALL for your hard work....
Many of use truly appreciate it very much.

**Comment by pigeth** [comment]
any news on this problem? installed latest update 04/09-19 and i will only unload the champer i have selctet with the tip side option

**Comment by revrr** [comment]
cant it recognize that the trailer is not filling and it's also not 100% full and pull the truck forward a bit until it starts to fill again?
