### ISSUE TITLE
CP selects All Wheel Steering by default

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3062]
CP will automatically switch to All Wheel Steering on vehicles that have it.

Using all wheel steering when pulling a seeder or cultivator causes all kinds of problems when turning, and front wheel steering makes it much easier to turn.

I'm having all kinds of turn radius and backing up issues with CP courses with All Wheel Steering selected.

**Comment by FarmerNothing** [comment]
hopefully they will add option of diffrent steering modes and crab steering for beet harvesters

**Comment by pops64** [comment]
I don't think this ever got inculded into CP has having tractors with all wheel steering is new to 19. Before it just was the best harvester so it was a special case

**Comment by sootysax** [comment]
I'm not sure of all the tractors that have alternative steering, but the JCB Fastrack 4220 is the one I'm using.  You Left Ctrl-Y and it toggles through All Wheel, Front Wheel, Crab Left and Crab Right modes

**Comment by pops64** [comment]
Yeah both the JCB tractors have it I think. I know in 17 they just forced the beet harvester to one setting

**Comment by FarmerNothing** [comment]
> Yeah both the JCB tractors have it I think. I know in 17 they just forced the beet harvester to one setting

yeah but why cp decided to force select the all wheel mode

**Comment by Hubcap-1** [comment]
Same issue is happening with the Terra dos potato harvester

**Comment by pops64** [comment]
I would guess it is the default mode for the standard Giants helper to run. Unless overridden

**Comment by sootysax** [comment]
@ThomasGaertner @pvaiko Any further insight on this?   It kind of makes the JCB 4220 kind of useless for any kind of trailed tool or trailer because the all-wheel steering screws up the field work.

**Comment by Hubcap-1** [comment]
I think all wheel steer vehicles are going to be something worked on
sometime in 2020 at the earliest

**Comment by pvaiko** [comment]
CP selects what the standard Giants CrabSteering:onAIImplementStart() returns, which is the all wheel steering. 

We won't change this. We probably need to check our math when driving four wheel steering vehicles but we don't directly control the steering angle so I don't think there's a problem there.

If you want front wheel steering then you can add the aiSteeringModeIndex attribute to the vehicle's crabSteering setting in the XML:

`<crabSteering aiSteeringModeIndex="2">`

**Comment by GeorgeEarslight** [comment]
@pvaiko 
I was looking into this on merit of the new DLC, as the Xerion is also 4W steered.
I've tried to comment out the code at [start_stop.lua:411](https://github.com/Courseplay/courseplay/blob/1087b39800118852277c8fe030f54d5faa2aac0c/start_stop.lua#L411-L415) but something else is overriding the crab setting (resetting to 4W) when the AIDriver starts.
Any idea about this?

**Comment by pvaiko** [comment]
It is the Giants code in onAIImplementStart event, see my comment above. And I made a ton of changes lately (on the beta branch) so not sure if this is still a problem, if it is, as I said, we have to fix our driving as I want to stick to the Giants solution.

**Comment by GeorgeEarslight** [comment]
I'm on the Beta branch anyway to test PPC and saw this. 
Thanks for the tip, I'll dig deeper myself.
