### ISSUE TITLE
Imperador 3.0 sprayer AI doesn't see fill levels correctly

### ISSUE THREAD

**Issue by snwkill** [Courseplay/courseplay#3063]
When using the Imperador 3.0 the AI doesn't see that the sprayer is full when the granular tank is empty 

I also noticed it always tries to default to the granuals instead of the sprayer

**Comment by Fogest** [comment]
I've noticed other issues as well with this sprayer/spreader. I see two options in CP, one for liquid fertilizer, and one for herbicide. When I have both liquid fertilizer filled and the spreader filled with fertilizer I see no change here and never seem to be able to get CP to realize there is a spreader on the machine it can use too. 

I haven't actually even been able to get it to work properly to use the sprayer to fertilize either though I'd prefer to use the spreader on it anyway as typically I carry herbicide in the liquid tank. That way I can carry both in one machine :).

**Comment by snwkill** [comment]
The only way I have gotten it to work is to have automatic buy for the AI turned on in the settings for whatever you want to use and the tank you don't want to use empty. If both tanks are full, I am not even sure how the default AI decides which one to use when they are both full.

**Comment by Fogest** [comment]
Interesting workaround that I can use in the meantime! Appreciate letting me know about that automatic buy. I was having to manually spread ;)

**Comment by sootysax** [comment]
This is a very handy sprayer..  Is it possible to add support for choosing solid fertilizer as well as liquid fertilzer/herbicide to the Courseplay Control menu?

**Comment by Fogest** [comment]
@sootysax I gotta agree the sprayer is quite useful and it would be great to have it supported! I am sure there are other sprayers (maybe more so in mods) that can do both as well so this fix should hopefully not just be specific to this sprayer. 

Even with the choices of herbicide and liquid that are currently there when using the sprayer it still doesn't seem to work properly unless using the workaround @snwkill mentioned of turning on the autobuy.

**Comment by pvaiko** [comment]
With 187c6fdefa06d33dc70e2240674b6352525e88b4 you should be able to use it at least for spreading when starting the course folded or spraying when manually unfolded before start. Refill courses don't work yet.

**Comment by Fogest** [comment]
Using v.00119 I finally got around to testing this.

![image](https://user-images.githubusercontent.com/1163628/53986010-0c568600-40eb-11e9-8af8-ea07a6bbfeb1.png)


Unfortunately it doesn't seem to be working. I have included the log in the pastebin below:

https://pastebin.com/yUnkjN9T

**Comment by Tensuko** [comment]
This is a very old Version and a lot have changed.
If this Issue is still valid, we reopen it.
Closed.
