### ISSUE TITLE
Tipper dosent unload in BGA silage trigger

### ISSUE THREAD

**Issue by Mannelig83** [Courseplay/courseplay#3070]
Hi,
driving through the Silage trigger on BGA (Felsbrunn) dosent unload.
Tried with the ingame Pathfinder Truck with tipper and with loading wagon and tractor aswell as in mode 1 asnd 2 and 5.
i own BGA and use it manually actually.

Greetings
Markus

**Comment by ThomasGaertner** [comment]
please be so kind to try with a new savegame and report back

**Comment by BI4LY** [comment]
I have the same problem but with sugar beets. Tatra truck with Krampe SB II 30/1070 doesnt unload sugar beets in Root Croop Strage mod

**Comment by Mannelig83** [comment]
Hi,
tried again with blank savegame on felsbrun with newest CP Version.
Simple Course just through the BGA unloading trigger and he drove Right through it.
so Nothing changed for me with new savegame.

Greets
Markus

**Comment by Verios44** [comment]
I am having similar issues with the krone tipper (vanilla version) and with hay silo, also vanilla. Set unload point and nada.

Also if I use a rear unloading tipper for normal grain and a silo, it triggers but after driving through the collection point.

**Comment by ThomasGaertner** [comment]
hmm strange, could you go there and make a screenshot after pressing F5 once (show me the Silo in the screenshot) . and make a log of the approach with debug channel 1 active.

**Comment by Mannelig83** [comment]
hello,
i hope this helps:
Log:
https://pastebin.com/Ewp8p0Gg

Ill take a wild guess and say ist lp23102.
The Course leads at ist end to the bunkersilo in case you wonder.

here are the screenshots:

https://imgur.com/a/mk8Uc5G

if you Need any further Information let me know

Greets Markus

**Comment by Mannelig83** [comment]
Hi, i hope i can help.

First of all here are the screenshots
https://imgur.com/a/dV480Fq

and there you have the Debug log:
https://pastebin.com/L7MVCNgY

If you Need any further Information, let me kno and ill try my best to make it happen.

Greets Markus

**Comment by GeorgeEarslight** [comment]
Can attest to this too. BGA is not listed on dbg1 fillTriggers list.

**Comment by kaykby1** [comment]
you need to buy the bga

**Comment by ThomasGaertner** [comment]
Is it still an issue with the current version ?

**Comment by iljarogoff** [comment]
Having the same problem on another map, still not fixed? Using mode2

**Comment by ThomasGaertner** [comment]
test with V140 or higher and report

**Comment by iljarogoff** [comment]
Works like a charm now! Thanks a lot!
