### ISSUE TITLE
CP crashes 

### ISSUE THREAD

**Issue by tjBerlin** [Courseplay/courseplay#3071]
Hello!

Using CP version .00020. No mods loaded. 

By harvesting and try to unfil the harvester CP crashes. The first crash took the ps off, by the second FS19 was still running.

Two logs: 
[log1.txt](https://github.com/Courseplay/courseplay/files/2821782/log1.txt)

[log2.txt](https://github.com/Courseplay/courseplay/files/2821784/log2.txt)

At both ends it says: 

2019-02-01 14:28 Error: Running LUA method 'update'.
2019-02-01 14:28 /Users/TjarkoS/Library/Containers/com.focus-home.farmingsim2019/Data/Library/Application Support/FarmingSimulator2019/mods/FS19_courseplay/mode3.lua:24: attempt to perform arithmetic on a nil value

**Comment by Verios44** [comment]
I have been haing this same issue on Honey Dew Xl. I do not have logs currently though.

**Comment by ThomasGaertner** [comment]
how did you get there? mode3 should have been disabled for now

**Comment by tjBerlin** [comment]
I just made the courses, it worked from the beginning.

**Comment by tjBerlin** [comment]
Just tried another round with CP version .00025. It worked fine. 

Only the harvester says: "Durchdrehende Reifen" when getting unfilled. 

![bildschirmfoto 2019-02-02 um 10 30 13](https://user-images.githubusercontent.com/24283753/52162562-599f9c00-26d6-11e9-8135-2f2f0fa33a25.png)
