### ISSUE TITLE
CP won't recognize additional tanks.

### ISSUE THREAD

**Issue by SavageMkII** [Courseplay/courseplay#3073]
It seems that with the seeders that have no fillVolume of their own, CP will not recognize the additional tank, and simply says "work tool needs to be refilled" when you start the driver. I had both the seed and fertilizer tanks full. 

I am referring to the Hatzenbichler seeder combo and the Vaderstad Seed Hawk combo.

I can post logs and screenshots if you require, but it is very easy to reproduce. 

Thank you all for your tireless efforts to bring this essential mod to the game!

**Comment by TinyCrocodile** [comment]
did you already try the version from #3034 ? 
for the issue #3050 this seemed to work
