### ISSUE TITLE
Better readability while saving a track

### ISSUE THREAD

**Issue by game455** [Courseplay/courseplay#3076]
Maybe its just a minor important request: When saving a track, there is a yellow field with white letters. It would be nice, when the letters are black. Any other (dark-bright) combinations are also welcome.

btw many thanks for great work to the dev team

**Comment by pvajko** [comment]
I don't like it either but we are using the standard Giants profile for text input fields to match the look and feel of the game, so won't change this.

**Comment by game455** [comment]
It ok. So lets concentrate onto the big things ;-)

 

Von: Peter Vajko [mailto:notifications@github.com] 
Gesendet: Samstag, 2. Februar 2019 00:11
An: Courseplay/courseplay
Cc: game455; Author
Betreff: Re: [Courseplay/courseplay] Better readability while saving a track (#3076)

 

I don't like it either but we are using the standard Giants profile for text input fields to match the look and feel of the game, so won't change this.
