### ISSUE TITLE
leveling and compacting mode is not avalable 

### ISSUE THREAD

**Issue by mehdinasef** [Courseplay/courseplay#3077]
I wanted to set a course to level and compact chaff in the silo bunker at the BGA in the Ravenport map but I could not because the levelling and compacting mode was not avalable ( it was in grey instead of white ). I tried to use another tractor and other leveller but nothing changed
![sin titulo](https://user-images.githubusercontent.com/47159754/52152168-b9198f80-2675-11e9-95e0-0b3655ac1775.png)

**Comment by pvajko** [comment]
_"We will be enabling functionality step by step so probably your favorite Courseplay feature may still be missing. "_ (see #2912)
