### ISSUE TITLE
Hud has problems displaying

### ISSUE THREAD

**Issue by Hubcap-1** [Courseplay/courseplay#3079]
Initially  when I start the Game I have no issue with getting the Hud to display ( using left control + del ). For some reason if I take it down ( same hot key)....sometimes it will not come back up. When it finishes the couse and is sitting there I get in....left control+Del....The Hud does not display and the machine just takes off going who knows where  I can not therefore stop worker and the machine takes off.can't stop it no matter what ....until it drives off a cliff or gets stuck. Inevitably the only thing I can do is save game and start over....it got worse with the January 1 edition of course play. Yes I have tried right click as well....nothing will bring the Hud back up except restarting the game. Update : I now find this version ( ending in 25) is unusable. Having freshly restarted the game 2x....some...not all the tractors make the click sound ( as if the Hud is now displayed)....and no hud. Once this happens no matter if you leave the tractor and come back some time later....it will not display ( or make the click sound). Seems to be device dependent..and not always the same device. 
[log.txt](https://github.com/Courseplay/courseplay/files/2824548/log.txt)

**Comment by Satissis** [comment]
This have already been reported.
Please post further finding in #3047

Closing due to duplicate issue
