### ISSUE TITLE
Idea: CP for Horses

### ISSUE THREAD

**Issue by dominiczeth** [Courseplay/courseplay#3081]
Hello, i just had an idea and wanted to ask if it's possible: 

What about Courseplay also is available for horses? So you can create a route for your horses and don't have to do the riding everyday by yourself. Now i don't know how the horses are handled ingame so is it possible, and if yes what do you think about that?

**Comment by Satissis** [comment]
The idea it self is good though the only problem is horses are not handle the same way as an vehicle, like they don't have wheels and we would have to adapt the code for it.
Also horses don't need all the work modes XD but only a training mode.
Could be done but is it worth it right now. No I'm afraid not. At least not until the whole rewrite of CP

**Comment by dominiczeth** [comment]
Understand that. Maybe someday, thank you for your answear!

**Comment by Tensuko** [comment]
If you don't want to do the riding every day, there is a Horse Helper Mod that sets all Horses to 100% @ 23:00 for 300€ per Horse per Day.
https://ls-modcompany.com/filebase/file/231-pferdehelfer/

**Comment by jiggin** [comment]
if this mode gets added, it could be called 'Horseplay' 😃 🐴

**Comment by Tensuko** [comment]
Closed.
