### ISSUE TITLE
1kph ?

### ISSUE THREAD

**Issue by NinjaDall** [Courseplay/courseplay#3082]
Hi,
When I let any modded combine harvest, it will only go 1 kph. All in-game combines will go the normal 10 kph. 
Also, all modded combines will start by "raising" the pipe, and don't move, unless I break the CP driver off, start normal AI-driver, then start CP-driver. (and THIS is what gives me the 1 kph - everything else gives me 0 kph).
Which log u need to analyze this?
NinjaDall

**Comment by Verios44** [comment]
which modded combine?

I have been using a modded JD s780 from "John Deere Pack OY MP" and its functioning as it should for me.

**Comment by NinjaDall** [comment]
Any modded combine.... Have tried 9 different now....
Again: Which log u need to analyze?
NinjaDall

**Comment by NinjaDall** [comment]
> which modded combine?
> 
> I have been using a modded JD s780 from "John Deere Pack OY MP" and its functioning as it should for me.

good 4 u

**Comment by sootysax** [comment]
which mode are you in?   in transfer mode, the cruise control speed is effecting CP speed..  you may need to increase the CC speed when starting a route

**Comment by pops64** [comment]
Mods are going to wait until the CP team gets CP in a better shape than what it is now

**Comment by NinjaDall** [comment]
> Mods are going to wait until the CP team gets CP in a better shape than what it is now

Ok - I'll wait ^^

NinjaDall
