### ISSUE TITLE
Error: Running LUA method 'update'

### ISSUE THREAD

**Issue by Django215** [Courseplay/courseplay#3084]
Hello,
i have a problem with Cp i don't know what is the reason. I'm on the way to the field with the Ropa 6xl. And a other driver in mode 2 come from sale point back to field. i become a lua error und must exit the game. maybe anyone an idea. 

my log
https://filehorst.de/d/cIJzClHC

**Comment by Satissis** [comment]
Looking at your log, it shows other errors from other mods, so would remove those mods for starter.

Now for the CP error I'm going to post the line here just so @ThomasGaertner can see the error without having to check the log.

Version:
`### Courseplay: initialized 61/61 files (v6.01.00025)`

Runtime error:
`2019-02-02 15:13 Error: Running LUA method 'update'.
2019-02-02 15:13 C:/Users/Stefa/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/combines.lua:52: attempt to index local 'fieldData' (a nil value)`

**Comment by ThomasGaertner** [comment]
as @Satissis said: please try again with an clean map and report...
