### ISSUE TITLE
Request: More Keybindings

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3085]
I would find very useful that more functions have key bindings.

In particular:

Start Course at (one key toggles through selections)

Next/Previous for CP Control, Manage Courses, Speed limits, settings combi mode, manage combines, driving settings, course gen

Clear current course

side offset up, side offset down

**Comment by sootysax** [comment]
that being said, since keybindings allow you to not have the display up when you switch things, maybe adding some audible alerts instead of just the 'clicks'..  for instance maybe a different tone when something is 'activated' and 'deactivated'

**Comment by Satissis** [comment]
Maybe, but I won't promise anything regarding that.

**Comment by sootysax** [comment]
@ThomasGaertner Now that keybindings are working, I'm very much wanting these to be added :) :)
