### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#3089]
Hi I have a Problem! When i harvest a field the comes in the log this 
FS19_CoursePlay6/combines.lua:52: attempt to index local 'fieldData' (a nil value)
2019-02-02 22:05 Error: Running LUA method 'update'.

is this a problem from the Map??

LG

**Comment by pops64** [comment]
#3084

**Comment by Paul2510** [comment]
Ok Thanks!
