### ISSUE TITLE
Warning (performance): Raw audio format...

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#3090]
warning in the log:
2019-02-02 21:14 Warning (performance): Raw audio format C:/Users/anthu/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay6010027/sounds/cpClickSound.wav.

chancing the audioformat from wav to ogg,
and change the line 403 in hud.lua from
	loadSample(self.clickSound, Utils.getFilename('sounds/cpClickSound.wav , courseplay.path), false);
in
	loadSample(self.clickSound, Utils.getFilename('sounds/cpClickSound.ogg', courseplay.path), false);
solvethe warning

sorry guys, i know you have a lot work for cp,
i am a fan from cp since ls15

lg
andreas

**Comment by pops64** [comment]
It has no impact other than the message in the log. According to Giants if the sound sample is used the warning doesn't show. I altered CP way back in early alpha to use the Giants sound and updated CP code to 19. The originals sound code is commented out. So the file could be deleted if you want to remove the message. Or turn the old code back on and the Giants code off. Very that they already knowno about

**Comment by andreasthu** [comment]
no problem
i will ignore the warning meanwhile.
if you want, here ia have the ogg file for your use:

[cpClickSound.zip](https://github.com/Courseplay/courseplay/files/2825435/cpClickSound.zip)


lg
andreas
