### ISSUE TITLE
Minor bug: reversing on headland turns

### ISSUE THREAD

**Issue by PirateAE** [Courseplay/courseplay#3091]
Case IH 7250 pro, working field 9 With the HIT 12.14, east to west, Dual head-lane after inside. Turn on field off; Did the Insides fine after setting turning radius to 25m(or there about), When it got to the outsides, it was trying to do back up turns as if the 12.14 wasn't a trailer. (Trailer dragging tractor in the backup) Turning on turn on field also same result.

CP version 6.01.00025 dev according to IG

**Comment by Messy71** [comment]
See also #3088

**Comment by tjBerlin** [comment]
Sounds to me like I have nearly the same problem: I am using CP version .00044 on FELSBRUNN. Course generated on field 20 with headland SHARP (scharf). When CP driver wants to trun and tries to drive reverse, he circulars. 

![bildschirmfoto 2019-02-06 um 12 23 12](https://user-images.githubusercontent.com/24283753/52342764-86292000-2a16-11e9-8830-ea3b18580351.png)

Here the log with dbg 12, 13 and 14. The issue starts 2019_02_06 12:23 :04.

[19_14_0051.4_TSVG_AEA Koa_Heilmittelversorgung_fachfremd.pdf](https://github.com/Courseplay/courseplay/files/2836380/19_14_0051.4_TSVG_AEA.Koa_Heilmittelversorgung_fachfremd.pdf)

**Comment by Messy71** [comment]
@PirateAE  should be fixed with v6°01°00073, try with the latest version.
@pvaiko this also should be closed.
