### ISSUE TITLE
Reversing in plant mode with tracked vehicle

### ISSUE THREAD

**Issue by SmartAg** [Courseplay/courseplay#3094]
CP vs .000025 
Planting with Amazon Condor and Deere 8RT turn mode does not work because the vehicle does not reverse properly on headlands. Jackknifes and gets stuck. Can only complete course in "smooth" setting. No mods except courseplay running. I will add more info if I get a chance to dig in further. 
Ok so I also tried with a wheeled tractor and it does not work either. Changed turning radius and it doesn't make a difference. BTW Love Courseplay and the work you are doing! keep it up

**Comment by Messy71** [comment]
See also [#3088](https://github.com/Courseplay/courseplay/issues/3088)

**Comment by Messy71** [comment]
@SmartAg should be fixed with v6°01°00073, try with the latest version.
@pvaiko this also should be closed.

**Comment by SmartAg** [comment]
@Messy71 Ok so it is much better I am now using v6.01.00076. It is only on the second part of the turn when it backs up for the second time that it messes up and jack knifes. I tried several turn radius settings but it still could not achieve the 2nd part of the turn. Based on standard steering in real life it seems like the PID gains need to be tuned to make it work not sure if that is how you do steering or not. I tried with a tracked vehicle and wheeled one the same course. Here is some videos on it. 
https://youtu.be/9S8c4TQEplE
https://youtu.be/W83eTzjpsXk
https://youtu.be/f8E0wh5kbuM

**Comment by Messy71** [comment]
judging by the movement of the tractor i think you should lower your turn speed and also set the turning circle to auto by lowering the value to 0, if it works with auto turning circle on the 180 degrees lane change it should also work in 90 degrees headland turn , if it doesen’t work increase the value by 1 m and test again ( keep in mind that the course doesn’t update on the fly, stop the driver change the value drive a couple waypoints before the turn and start from nearest waypoint).
