### ISSUE TITLE
WIP Courseplay editor for Fs19. New feature realheightatworld y coordinate

### ISSUE THREAD

**Issue by PromGames** [Courseplay/courseplay#3096]
Hello, after the short time that CP is in Beta, I was able to upgrade the fs17 CP editor to FS19. 

Normal maps and 4x maps are working fine and new XML data has been added. 
I am not clear about which XML attributes can be edited by the user and which can make errors if edited. I need some help with that list. 

I continue missing realworldterrainheight (y) at worldpos, to get also in the courses. I know is not needed for the cp working routine but This will help a lot if I can get the courses and customfieldscan points with the Y height. Maybe a small button to do it like you did with the update courses. Thank you again.

Then I can get the y info in the file and import in GE editor with real height.

New feature:

1.- Courseplay editor is able to export and import courses from splines and splines from courses. This feature can help mod makers to created splines and modify on the CP editor.

2.- Courseplay editor is able to modify customscan fields and save them, this will allow to edit the borders before creating the harvest course and be able to avoid possible obstacle, trees, hedges splines of the field, etc.. Remenber that CP editor runs at the same time with the game and is updating the courses a soon as you reload in the game.

3.- The system will export in different formats, depending of the needs and making corrections to adapt to to Maya, 3D max, blender or the GE editor to create roads, railways forest trees in conjunction with the placing object script in GE.

Would be nice to know from you all if this is a good feature and you see it useful.

Just an image from the editor in FS 17 

![image](https://user-images.githubusercontent.com/9979168/52175619-ace11f80-27a6-11e9-9638-f328688f1ba4.png)

And now in FS19

![image](https://user-images.githubusercontent.com/9979168/52175667-64763180-27a7-11e9-856d-eb4a51dc11cc.png)

Once imported, the spline in GE

![image](https://user-images.githubusercontent.com/9979168/52176188-6ba13d80-27af-11e9-8ce3-83eab4b93189.png)

Prom
LS Mod Company

**Comment by PromGames** [comment]
https://user-images.githubusercontent.com/9979168/51939227-3db6a480-240f-11e9-9d3c-694128e48ffd.png

**Comment by pvajko** [comment]
@PromGames I'll look into putting the y in the XML, in the meanwhile I was wondering if it makes sense to integrate your CP editor with my standalone course generator (https://github.com/pvajko/course-generator).

That project is just a GUI, and XML file interface and some automated testing around the course generator code in CP that allows me to develop and debug the course generator code outside of the game. It is using Love2D for the UI and is written in lua. Maybe it would make sense to use your Courseplay Editor as the frontend instead. Maybe it would make sense to have the CP course generator in the Courseplay Editor? Think about it. C (or C++) and Lua should integrate nicely.

**Comment by TinyCrocodile** [comment]
Ok this is very interesting i like the idea of having the coursegenerator inside this whole solution of course and field editor. In my opinion this makes perfectly sens.

**Comment by PromGames** [comment]
@pvajko, Yes, we can integrate in the editor, I will import into the project. I am working at private git in gitlab, do you have user there? Just send and you will access to see and commit. 

@TinyCrocodile, I am very interested in involving you in the project, we are old guys and we need fresh people to come. I have included some of your improvements from coursedrawer already in Hyde editor but emails to do many features.

I have also asked to Lisertan of the possibility of publishing in Giants Modhub as a new category in FS Windows apps for FS. Let's dream about it. Otherwise, we can distribute through windows store.

Prom

**Comment by TinyCrocodile** [comment]
@PromGames  Very good. I just saw your Post in Giants forum. I am looking forwart to the Project it involves a lot of the vision i had for coursedrawer. It is very encouraging to find other people that are interested in developing a Course Editor app.

**Comment by PromGames** [comment]
Warming up!!!


![image](https://user-images.githubusercontent.com/9979168/52184106-58be5580-280f-11e9-82ab-4c12d8459b5e.png)

**Comment by pvajko** [comment]
Awesome. Does not look like the latest version though.

**Comment by pvajko** [comment]
@PromGames gitlab username is pvaiko

**Comment by TinyCrocodile** [comment]
Just in case you missed my e-mails my gitlab user is TinyCrocodile

**Comment by sootysax** [comment]
im very glad to see this ball rolling.  I am a big fan of combined courses, and i find that courseplay editor is a must have for editing crossing points and speeds to make turns work.  looking forward to help test this

**Comment by PromGames** [comment]
We are dealing now to be able to show course generator in the editor, we are close to it. Signing certificate is also renewed to get a trusted Windows10 application. Also Tiny crocodile is on board on he will add some of his good ideas to improve the application.

We will send a pre release version to cp developers and cp contributors and translators for beta testing. In addition we will send of course, also to mvp's in cp like you sootysax

**Comment by sootysax** [comment]
I had been successfully using the previous version of CourseDrawer 5.1.0.21418 - but 6.01.00063 broke that for me :(  Oh well..  let me know when I can get in on the beta test :)

**Comment by PromGames** [comment]
@sootysax , Hi Scott, You have the program in you mail for beta testing. I expect you enjoy the program and can give some feedback to the community. Just follow this issue to report bugs, etc...

**Comment by pvaiko** [comment]
Looks like this can be closed.

**Comment by wilbertlandry** [comment]
Just a quick thank you to the real heroes of FS19. My OCD and I are anxiously awaiting the release of this little jewel so I can straighten out some courses and relax :-)

**Comment by yankee42** [comment]
Hi, I also wrote some utilities that help with editing courses: The [courseplay-osm-converter
](https://github.com/yankee42/courseplay-osm-converter). I stumbled accross the height coordinate, tried to figure out it's meaning and by following git blame and ended in this issue.

As far as I understand this ticket this coordinate only exists in XML so that it can be used by other tools. However if I do not need to do anything with the height, can I safely ignore it?

As it currently stands the height will be generated when saving the course:
https://github.com/Courseplay/courseplay/blob/fff31dff59a7a16cd49133aece88cfa4e8926980/course_management.lua#L760
https://github.com/Courseplay/courseplay/blob/fff31dff59a7a16cd49133aece88cfa4e8926980/course_management.lua#L764
Thus any value that was saved in the XML file will latest be overwritten when saving.

However I wonder why in this case the height value is even read while reading the XML:
https://github.com/Courseplay/courseplay/blob/fff31dff59a7a16cd49133aece88cfa4e8926980/course_management.lua#L1435

Currently of course I could just omit this value when writing to XML, as it is not required:
https://github.com/Courseplay/courseplay/blob/fff31dff59a7a16cd49133aece88cfa4e8926980/course_management.lua#L1399

However are there any plans to change this or does that have any effects I might miss right now or is it save to just skip this value? (currently I just copy this property, but the difficulties arise, if a user adds a new waypoint, because in this case I have no source for the height information).

**Comment by pvaiko** [comment]
It is ok to not include the y in your saved courses as it isn't used by Courseplay at the moment and we currently have no plans to do so, we'll calculate the height on the fly.

You can also include a 0 for y or just copy it from the adjacent waypoint.

**Comment by PromGames** [comment]
Hello @yankee42, the reason for having the height is because we are using it in courseplay editor to be able to export and import splines to a map.

I was working with your OSM Editor and is quite promising. I was making some test with our map team, Holzermap replica1:1, to see how accurate is compared with reality, and is very similar.

It's a pity that OSM is not managing also heights because could be and amazing tool for map makers. 

If we can get from OSM editor courses from real OSM areas with heights, we can convert to splines in my editor and we can set terrain sculpting by spline easily and accurate.

Just some thoughts, congrats for your work, pity is in Java and the cp editor is in .net

Prom

**Comment by pvaiko** [comment]
> pity is in Java

No, it's a blessing.

**Comment by labruja2275** [comment]
> 
> 
> I had been successfully using the previous version of CourseDrawer 5.1.0.21418 - but 6.01.00063 broke that for me :( Oh well.. let me know when I can get in on the beta test :)

Hi . One possible solution is to use the file course_management.lua from a previous version than the one in v6.01.00063. I use the course_management.lua of the version v6.01.00062 and it does not keep me the fist of the height, greetings from argentina. I do not speak English very much so use a translator

**Comment by tuzlo** [comment]
Is this still not public?

**Comment by Gibbanator** [comment]
this does not look like the integrated one? is there a difference?
