### ISSUE TITLE
Problems with Harvesting

### ISSUE THREAD

**Issue by JoergFra** [Courseplay/courseplay#3097]
Hi,
i have some issues with the harvesting and the combine.

1. The combine comes to the harvester, the harvester stops and the unloading begin. (works perfekt). But the combine will not start. When i fire the helper nothing happend. I have to close the pipe manually. Then start the CP Helper again an then it works.

2. If the Hervester passes the combine at his waiting point, the harvester stops and open the pipe. I have to stop the CP Helper an close the pipe manually. Then the harvester will start.

[log.txt](https://github.com/Courseplay/courseplay/files/2825456/log.txt)

and here ist a Video where you can see it:

https://youtu.be/YAmUI1kLGuo

Thank you very much for your hard work.

**Comment by JoergFra** [comment]
I made a Log with mode 12 and 14:

[log.txt](https://github.com/Courseplay/courseplay/files/2825483/log.txt)

I hope that will help

**Comment by pvajko** [comment]
Try with 6.01.00037or later and report back

**Comment by JoergFra** [comment]
Hello,

i tryed it with 6.01.00039 and it does not work

Video: https://youtu.be/RMdC905HpXY

And some other issius:

 (driver do not open plane):  https://youtu.be/QSlB3IW95rw

(driver crashed into harvester):  https://youtu.be/lv639bC6rTE

here ist the log:

[log.txt](https://github.com/Courseplay/courseplay/files/2829807/log.txt)

Thank you.

**Comment by pvajko** [comment]
The original issue is solved as the video also shows, this one is because of the way mode2 works at the moment. Will fix sometime later. 

As for your other problems open a new issue for them but please check if there is already one opened (I know there's a like a million tractor crashing into combine issues already)
