### ISSUE TITLE
FS crashes when combine reaches fill level to call driver with v6.01.00031

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3100]
When combine reaches the set 80% fill level and the tractor is called to come unload, FS crashes and must be forced to exit.

2019-02-03 07:01 Error: Running LUA method 'update'.
2019-02-03 07:01 C:/Users/ScottM/Documents/My Games/FarmingSimulator2019/mods/zzz_courseplay/CombineUnloadAIDriver.lua:248: attempt to call method 'getAttacherVehicle' (a nil value)

https://gist.github.com/sootysax/ec1112e215cdcbb8b541390424b61bb3

**Comment by Mannelig83** [comment]
Getting the same Error with NH FR780 and various tractors for unloading.

**Comment by ThomasGaertner** [comment]
classical 'just testing one situation error' is fixed in v.00032

**Comment by sootysax** [comment]
same issue with .00032

https://gist.github.com/sootysax/dc75612fea815ec0b529935160eb6b96

**Comment by ThomasGaertner** [comment]
try with 33 and maybe with an error free map...

**Comment by sootysax** [comment]
working well in .00034
