### ISSUE TITLE
Potato planter not refilling seed

### ISSUE THREAD

**Issue by Verios44** [Courseplay/courseplay#3103]
I am using: 
- Placable Refill Tanks mod available from the ingame modhub. 
- Fluustal XXL map field 1
- Grimme GL 860 Compacta using seed and liquid fert
- CP v 6.01.00029

issue, the course refills the liquid fertilizer first, then while moving to the seed refill point it does nothing and drives past. This does not make sense to me because both placables are from the same mod, but fertilizer loading is working but not seed. I have to manually stop, load seed, and resume.

**Comment by Verios44** [comment]
Images

https://i.imgur.com/GO3Ckz3.png < on field, empty
https://i.imgur.com/5LKAHdy.png < passing by refill stations, liquid fert refilled but not seed
https://i.imgur.com/CaP7dXU.png < manual refilling

**Comment by Verios44** [comment]
It just ran out again so I will attempt that, thanks.

**Comment by ThomasGaertner** [comment]
![image](https://user-images.githubusercontent.com/3279913/52178169-3d315b80-27cb-11e9-8ff9-54523f882ba4.png)
you have to set the selectedFillType to seeds, then it works fine...

**Comment by Verios44** [comment]
I found out my issue, was just too far away.
