### ISSUE TITLE
Automatic Covers Mode 1

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3104]
Automatic covers are not working in Mode 1

**Comment by ThomasGaertner** [comment]
should be implemented in v00036...

**Comment by sootysax** [comment]
not working again in .00037/.00038
![fsscreen_2019_02_04_08_06_05](https://user-images.githubusercontent.com/6591048/52210065-e6239900-2853-11e9-9784-457e522d5378.png)

**Comment by jhndrtxn** [comment]
Having the same issue

**Comment by BI4LY** [comment]
Just downloaded newest version CP, still same problem:

![fsscreen_2019_02_05_18_42_26](https://user-images.githubusercontent.com/47229171/52292913-00ee2e80-2976-11e9-9e49-0936dbd81f12.png)

**Comment by ThomasGaertner** [comment]
try again with 00043 or higher. Note that the last way point should be a bit in front of the fill point that we can calculate the right filling point between last and first point

**Comment by BI4LY** [comment]
Yep I know that about last point. Now it is ok! :) Thanks

**Comment by sootysax** [comment]
not quite working for me yet..   covers will automatically open when approaching a load trigger, but will not cover themselves when leaving the trigger.   if you stop the course they will be put on.   if you start the course, they will not be put on.  

Whenever CP is running a course, you can uncover or cover them with the N key.

**Comment by ThomasGaertner** [comment]
try again with 52 or higher

**Comment by sootysax** [comment]
seems to be working well..  i can still manually cover and uncover while the course is running, which is unusual, but not detrimental to gameplay, thanks!
