### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by Ravlie** [Courseplay/courseplay#3106]
Hello,

I'm not trying to rush you guys since I'm really grateful to you we will have Courseplay working in FS19 the question is I just do like to know when can we expect it to be working in multi as well? I'm not saying it's not working right now but the players have to leave the server so just when 1 person stays he/she can use it to generate fields etc.

I'm using it as a host not sure if it works different while the mod is on dedicated servers.

**Comment by TinyCrocodile** [comment]
The Courseplay team said multiplayer will only be fixed if singleplayer is fully funcional this may take a while. But they put already a lot of work into it as new version comes out nearly every few hours. Thanks @CourseplayTeam.
@CourseplayTeam did you know about pinning issues? I would sugest to make a pinned issue with Information about this at the top of the Issuepage.

**Comment by sootysax** [comment]
I don't remember Courseplay ever being a multiplayer mod.    Courseplay for FS17 wasn't 'released' out of beta until Fall 2017.   So I would give it some time.

**Comment by Roby1164** [comment]
> I don't remember Courseplay ever being a multiplayer mod. Just to give you some reference, Courseplay for FS17 wasn't 'released' out of beta until Fall 2017. So I would give it some time.

Nobody is putting a hurry to anyone ..... I just said it would be nice to have the multiplayer version, by the way, I think it is little different from multiplayer ....
