### ISSUE TITLE
Collecting Straw

### ISSUE THREAD

**Issue by JoergFra** [Courseplay/courseplay#3107]
I made a Collecting and a unloading route.

I start at the collecting route. Every thing works fine. At 100% the driver stopps collecting an drives to the unloading point. The the straw is unladed.

Video1 (starting unloading route): https://youtu.be/ESIyEyLKz8Y

Video2 (reaching unloading point): https://youtu.be/XUTGEdDrC9w

Then hi drives back to the field.

If the Truck is full for the second time, there ist the Message "Abladestelle erreicht" an starts his unloading route. The speed of the Truck is the "turning Speed -10 kmh".

Video4 (starting unloading route for the second time):  https://youtu.be/z4vLrCRNXYQ

He reaches the unlading point an it does not work.

Video 5 (reching unloading point for the second time): https://youtu.be/x_vNE8dz1cA

When i stop the driver an hire him again the "game" starts from beginning. The first unoading works fine, the second not.

Here ist the log:  
[log.txt](https://github.com/Courseplay/courseplay/files/2825758/log.txt)

Thank you.

**Comment by ThomasGaertner** [comment]
#3025
