### ISSUE TITLE
Tractor dosn't stop at End of the route

### ISSUE THREAD

**Issue by spiessphilipp** [Courseplay/courseplay#3108]
Hello,
i started a CaseIH 7250 to a route over the map to field 9 on Felsbrunn. When he reached the end he doesn't stop and drove straight ahead. i cannot open Courseplay to stop the helper and have to close the game and restart. the log doesn't show errors.

Best regards
Philipp

**Comment by Verios44** [comment]
did you select stop at last point to activate? default is deactivated

**Comment by Fogest** [comment]
To help out the devs I would still try and include the log file anyway just in case for this report. Is there any additional information for them on how you can reproduce the problem? Which mode are you using? This may be helpful to answer why it is not stopping.

**Comment by pvaiko** [comment]
Closed due to inactivity.
