### ISSUE TITLE
LUA Call Stack and Problems since today

### ISSUE THREAD

**Issue by Mannelig83** [Courseplay/courseplay#3109]
Hi,
i have a Call stack since todays update.getting potatoes with the varitron and unload with a Fendt 1000.
https://pastebin.com/ucraqDzZ

further i get "stuck in traffic" just every time i try to come to the harvester.
https://imgur.com/a/uu4LaxK

and the last Thing:
the last runs with harvested chaff when trying to unload in Bunker there was the message "unloadingpoint reached" for a short second and then the Tractor drove through without tipping.
Bunker was filled just over a Million volume.

Greets Markus

**Comment by ThomasGaertner** [comment]
could you make this picture again after pressing F5 once ? Thanks

**Comment by Mannelig83** [comment]
i already finished this Harvest but i can make it at the next Harvest.
the Problem i found was that the unloading pipe was too low for the tractor i used
