### ISSUE TITLE
Confirm unsupported Mod?

### ISSUE THREAD

**Issue by ShrekFS** [Courseplay/courseplay#3111]
Hi Course Play Devs

I've been trying to set a refill course with a Silo Seed Mod , However , the Tracker just drives straight past the Silo , I have tried another seed silo mod which works , Which makes me think The one i have linked to below is unsupported

https://www.dropbox.com/s/di6q1fgtccy0kbm/FS19_silostations.zip?dl=0

CoursePlay Version - 6.01.00036
[log.txt](https://github.com/Courseplay/courseplay/files/2825845/log.txt)

Thank's

**Comment by pops64** [comment]
The CP team has stated all mods are unsupported until a later date has they have enough issues with out adding in mod complications
