### ISSUE TITLE
ROPA Keiler 2 not recognized as harvester Mode2 

### ISSUE THREAD

**Issue by zed636** [Courseplay/courseplay#3116]
Hi devs,
CP version 6.01.00036
map: Felsbrun
field: 21
default vehicles
I create a fieldwork course with ROPA Keiler 2, but the other tractors in mode 2 don't recognize it as a harvester. 
When the white Valtra is full say COURSEPLAY_NEEDS_UNLOADING but either by starting the JCB in mode 2 or even approaching it manually, it does not open the unload belt.
No errors on Log.

![fsscreen_2019_02_04_02_50_19](https://user-images.githubusercontent.com/19471664/52186455-b9598c80-2827-11e9-9725-65cd2d58445a.png)

[log.txt](https://github.com/Courseplay/courseplay/files/2826267/log.txt)

**Comment by TinyCrocodile** [comment]
Duplicate #3052

**Comment by Tensuko** [comment]
#3311 
Closed.
