### ISSUE TITLE
Kuhn LSB 1290 D not raising tool during turns

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3119]
The Kuhn square baler is keeping the tool on and down during turns..  It raises it brifely at the end of the row, but drops it again and then goes into the turn maneuver.

https://gist.github.com/sootysax/2a7a6d5e09a4a2302c3ece85f4b785b3

![fsscreen_2019_02_03_23_14_16](https://user-images.githubusercontent.com/6591048/52190054-a71d2580-280a-11e9-9f62-9b43ce8744dc.png)

**Comment by Tensuko** [comment]
Same for TF 1512 wich makes the Tracktor unable to turn, couse tieres of TF 1512 can't handle reverse moving.

**Comment by pvajko** [comment]
Isn't this the same as #3003 and fixed by ff29eee9a7e25714cc4343f003be461d45a7ae9f?

**Comment by sootysax** [comment]
this was using .00037

**Comment by Tensuko** [comment]
TF 1512 don't get lifted for Turn, can cause problem with some Tracktors unable to turn.
Version .00054

Beside that, CP works already great even with several mods.

**Comment by pvajko** [comment]
Don't know what TF 1512 is, original issue seems to be solved.
