### ISSUE TITLE
Subsoiler, Agrisem Cultiplow Platinum 8m

### ISSUE THREAD

**Issue by ghost** [Courseplay/courseplay#3122]
Ends row as expected, but starts row too late. This means 1x manual headland
![cultiplow](https://user-images.githubusercontent.com/47278252/52222901-e304c900-28a4-11e9-8b23-0d1da6bc913b.jpg)

**Comment by TinyCrocodile** [comment]
Possible duplicate #3003

**Comment by pvajko** [comment]
Honestly, this is getting really boring: https://github.com/Courseplay/courseplay/wiki

**Comment by pvajko** [comment]
Reopen with full log and debug channels 12, 13 and 14 if still happening.
