### ISSUE TITLE
Using own vehicle on contracts

### ISSUE THREAD

**Issue by Orgalit** [Courseplay/courseplay#3125]
Hi!

Seems that when I use my own vehicle along with provided by contract to transfet fruits to contract silo, own tippet does not recognise tip trigger, while contract tipper recognises tiptriggers. Using modes 2 or 1, one route for both contract and owned tipper, two different routes and different silos - same thing.
Courseplay (Version: 6.01.00039)
[Log](https://gist.github.com/Orgalit/39d4c095c39a0fb755a8deddea13c52d)

**Comment by Symbob** [comment]
I'm getting a similar problem.  Tippers drive straight through some tip triggers.  On Ravenport it drives through Central Grain Elevator and Port Grain Elevator without tipping but seems to tip OK at the Ranch.  Could be to do with the size of the tip trigger.  It's almost as if CP detects the trigger too late so on a smaller trigger it has driven through before it starts to tip.  On a bigger trigger it just manages to start tipping before it has gone through the trigger.

**Comment by elektronemulo** [comment]
FYI, I have problems with tip triggers in this location when tipping manually. Tip trigger size could indeed be a factor here.

**Comment by ThomasGaertner** [comment]
Is this still an issue?

**Comment by Orgalit** [comment]
> Is this still an issue?

No, it's good now. Thanks! 
Some changes were made to the map I used - FLUSSTAL XXL, and it could be the point.
