### ISSUE TITLE
Loader wagon should drive the unload course when fieldwork finished and not empty

### ISSUE THREAD

**Issue by wwaayynn33** [Courseplay/courseplay#3127]
Loader wagon(doesn't matter which one) does not the correct operation in fieldwork mode 6. (if i remember it right from FS17, some years ago)
Generated course somewhere on the farm:
Start point -> wait point -> wait point -> unloading trigger in silo -> end point
Normally the implement behavior is:
Off -> turns on -> turns off -> off then unloads then off again -> and repeat.
So it should be on between the two wait points. What happens is:
Implement gets activated even before the start point and tractors drives with activated implement to the second wait point and stops there(if waiting at trigger is activated. If not tractor drives with activated implement to the start point and drives again to the second wait point and repeats it again.).
Actually it doesn't matter if there is a unloading trigger between second wait point and the first one.
This mode seems to work e.g. with the Kuhn rake.
Tested with version  06.01.00039 - let me know if you need a log

Thanks for your help and thanks for your work in general on this project - its really an improvement for this game!

**Comment by pvajko** [comment]
Should work fine with the combination of a generated field course and a recorded unload course. 

Are you using a recorded field course? May I ask why?

**Comment by Mannelig83** [comment]
i have similar issues.
loader wagon loads in mode Fieldwork but dosent Transition to the unloading Course.
if i Change to the mode 1 it unloads but dont use loader wagon.

![screenshot 2019-02-05 19 22 49](https://user-images.githubusercontent.com/47121919/52295292-bcfe2800-297b-11e9-87f6-9e259b0d7e6f.png)

**Comment by Mannelig83** [comment]
Hi,
https://pastebin.com/kvUJpL6g

thats part of the log with this Vehicle.

hope this helps.
i Keep the state of that field for now if you Need more Input

Thanks
Markus

**Comment by pvajko** [comment]
Looking at this message:
2019-02-05 19:42 :10 [dbg14 lp433035] 9340 TTV (#2): There seems to be no unload/refill course
I wonder how you created your course, it'll work if you generate or load a saved fieldwork course ***first*** and ***then*** load the unload course.

**Comment by Mannelig83** [comment]
im an idiot… sorry dude.. im new to CP so i didnt know About that order… Right now it works like it should…

again im sorry man...

Greets Markus

**Comment by sootysax** [comment]
https://courseplay.github.io/courseplay/en/manual/index.html#intro

all the instructions in the manual will still apply to Courseplay 6 - very useful info

**Comment by wwaayynn33** [comment]
To give you a precise log:
- Is it necessary that the tractor operates the implement during Recorder? I think not.
- Does the tractor need to drive in the work course on a field and on unloading course on the road? I think not.
- Does the loader wagon really need to get material in?

I always thought it would be enough that on your complete course is are two waitpoints(there order where the work starts and ends) and a trigger(is this one mandatory?). This worked in FS17.

I will record a log once the questions are clarified. The tried several combinations but i was no able to get it to work. Thanks

**Comment by pvajko** [comment]
@wwaayynn33 the answer to all your questions is no. 

Also, as of now, it won't work as it did in FS17. As I said, it'll work if you generate/load a fieldwork course and then unload/refill course (so you have two courses combined)

**Comment by wwaayynn33** [comment]
I recorded a field boundary and created automatically a field work course with the generator. Saved it, cleared it and created and saved a unloading course afterwards. Saved and cleared. Loaded workcourse an attached the unloading course. When it reaches the end of the workcourse(second wait) it drives back to the first wait point and starts again. If Wait is enabled i cant make it go to drive the unloading course.
Is it at the moment possible to record an own work track are should the generator be used for all cases atm?

Log:
https://pastebin.com/Uc3Cb3Zr

**Comment by pvajko** [comment]
Are you manually adding wait points somewhere? Why?

**Comment by Mannelig83** [comment]
As a Little Feedback:
i tested today like pvajko told to set up and it worked like a charm.
just Auto generate field Course, and attatch the Prior recorded Transfer Course.

**Comment by wwaayynn33** [comment]
No i don't. Just auto-generate the course and then load a unload course

**Comment by wwaayynn33** [comment]
https://pastebin.com/C9RY1e8B

Antoher Log. Loaded the field work course(only a U-Track) then attached(not combined) the unload course, which runs over a small silo. IN CP it shows two wait points and 4 cross points after the connecting the two courses.

Still does not behave correctly. Starting CP between the silo and the end point of the unloading course. When reaching this end point, CP engages the loader wagon(Why there? start of field course is still 10m away - is this correct?) The drives to along the work course to the end of it. At the end(second wait point) the tractors drives with activated implement to the first wait point(start of field course) and repeats the sequence.
Environment conditions:
- no mods
- V1.2.07??  Steam
- CP #51
- Wagon gets not loaded during work course, as no grass is mowed, so wagon is not full at the end!
- wagon is prefilled with 1000 when starting CP
- waiting at trigger is deactivated

**Comment by pvajko** [comment]
Can you save those two courses, zip your Couseplay_Courses folder and post it here?

**Comment by wwaayynn33** [comment]
See attached

<slot fileName="courseStorage0018.xml" isUsed="true" id="25" parent="0" name="_unload"/>
<slot fileName="courseStorage0019.xml" isUsed="true" id="24" parent="0" name="_fieldworkcourse"/>
<slot fileName="courseStorage0023.xml" isUsed="true" id="23" parent="0" name="_fieldboundary"/>

these are the courses i use: _fieldworkcourse + _unload

[CoursePlay_Courses.zip](https://github.com/Courseplay/courseplay/files/2852621/CoursePlay_Courses.zip)

**Comment by wwaayynn33** [comment]
Hello,
did you have time to take a look at it? Tried with the newest version of today and it still was working for some reason. If i run fieldwork mode and only the fieldworkcourse, all is good. drives to first wait point(first point of the course) activates implement until the second waitpoint(last point of course) is reached. Are there so restrictions how far away the start and end points of these two courses need to be?

**Comment by pvaiko** [comment]
I looked at it and not sure what exactly the problem is. If the end of the unload course is close to the start of the field course, it'll lower all implements the moment it switches to the fieldwork course. So in your case either you move those points closer or further away would help.

Also, the unload will only work correctly if there's something to unload and your loader wagon is full, then it'll abort the fieldwork course, drive the unload course and return and continue the fieldwork where it left off.

I don't see any issues here.

**Comment by wwaayynn33** [comment]
I got it to work. But still a behaviour at the end which is not correct(maybe not considered). When reaching the end of the field course with a wagon not fully loaded and "waiting at trigger deactivated" the tractor drivers to the start of the fieldcourse. Here the tractor should unload and then should wait at the unload trigger or wait at the start of the fieldcourse after unloading.

I also created a field course manually, as there is no difference to previous versions of LS17. When creating the field course i put the waiting points on the exact same position as the start and end point of the field course.

Used the 4-rotor rake on the test map and pretty amazing how good this already works. Thanks for your efforts !!

**Comment by wwaayynn33** [comment]
I tried a few courses now and it works fine, but on the unloading course it does not turn the implement off.

**Comment by Anonymous-any** [comment]
Hi I seem have an issue like that but I add my foragewagon is not completely full before the hang become, and of course it won't go to unload course and confirmed too the implement is not turned off.
log:
```
data/shared/assets/lights/lizard/sideMarker_03.i3d (0.83 ms)
Warning (script): 'localDirectionToWorld': Argument 1 has wrong type. Expected: Float. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (769): expectedType == Value::VoidType || expectedType == Value::ClassType
LUA call stack:
  =mods/Courseplay/vehicles.lua (1450) : localDirectionToWorld
  =mods/Courseplay/AIDriver.lua (899) : getTipTriggerRaycastDirection
  =mods/Courseplay/UnloadableFieldworkAIDriver.lua (77) : searchForTipTriggers
  =mods/Courseplay/FieldworkAIDriver.lua (111) : driveUnloadOrRefill
  =mods/Courseplay/UnloadableFieldworkAIDriver.lua (56) : drive
  =mods/Courseplay/drive.lua (11) : drive
  =mods/Courseplay/base.lua (1048) : drive
  dataS/scripts/vehicles/SpecializationUtil.lua (26)
  dataS/scripts/vehicles/Vehicle.lua (1281) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (98) : update
  dataS/scripts/network/Server.lua (58) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1495) : update
  dataS/scripts/FSBaseMission.lua (1990) : update
  dataS/scripts/missions/mission00.lua (462) : update
  dataS/scripts/main.lua (1857) : update
Error: Running LUA method 'update'.
mods/Courseplay/vehicles.lua:1454: attempt to perform arithmetic on local 'nx' (a nil value)
Warning (script): 'localDirectionToWorld': Argument 1 has wrong type. Expected: Float. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (769): expectedType == Value::VoidType || expectedType == Value::ClassType
LUA call stack:
  =mods/Courseplay/vehicles.lua (1450) : localDirectionToWorld
  =mods/Courseplay/AIDriver.lua (899) : getTipTriggerRaycastDirection
  =mods/Courseplay/UnloadableFieldworkAIDriver.lua (77) : searchForTipTriggers
  =mods/Courseplay/FieldworkAIDriver.lua (111) : driveUnloadOrRefill
  =mods/Courseplay/UnloadableFieldworkAIDriver.lua (56) : drive
  =mods/Courseplay/drive.lua (11) : drive
  =mods/Courseplay/base.lua (1048) : drive
  dataS/scripts/vehicles/SpecializationUtil.lua (26)
  dataS/scripts/vehicles/Vehicle.lua (1281) : raiseEvent
  dataS/scripts/network/NetworkNode.lua (98) : update
  dataS/scripts/network/Server.lua (58) : updateActiveObjects
  dataS/scripts/BaseMission.lua (1495) : update
  dataS/scripts/FSBaseMission.lua (1990) : update
  dataS/scripts/missions/mission00.lua (462) : update
  dataS/scripts/main.lua (1857) : update
Error: Running LUA method 'update'.
mods/Courseplay/vehicles.lua:1454: attempt to perform arithmetic on local 'nx' (a nil value)
Warning (script): 'localDirectionToWorld': Argument 1 has wrong type. Expected: Float. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (769): expectedType == Value::VoidType || expectedType == Value::ClassType
LUA call stack:
```
[courseStorage0002.xml.txt](https://github.com/Courseplay/courseplay/files/2937478/courseStorage0002.xml.txt)
[courseStorage0007.xml.txt](https://github.com/Courseplay/courseplay/files/2937480/courseStorage0007.xml.txt)
The courseStorage0007.xml is not the one I was used but I tried with this one too because it is the same destination and same call stack issue...The one I was used is deleted it because he annoyed me about it was not work with `dryGrass_windrow`
Br

**Comment by Tensuko** [comment]
Still a valid Issue ?

**Comment by pvaiko** [comment]
Won't implement this, in case you want to drive the unload course, just drive to the start of that course and start CP.
