### ISSUE TITLE
CP misses waypiont

### ISSUE THREAD

**Issue by tjBerlin** [Courseplay/courseplay#3128]
Hello!

I am using CP version .00039. 

When driving back from field to store, CP driver suddenly breaks out of the course. 

![bildschirmfoto 2019-02-04 um 22 43 25](https://user-images.githubusercontent.com/24283753/52240732-f67a5900-28d1-11e9-9101-42ba93a476b0.png)

[KOPIElog.docx](https://github.com/Courseplay/courseplay/files/2830001/KOPIElog.docx)

To create this course, I used the function "Kurse zusammenführen", wich means, I combined five course. At this spezial place was a crossing-point.

**Comment by pvajko** [comment]
No Word documents please. https://github.com/Courseplay/courseplay/wiki

**Comment by tjBerlin** [comment]
Sorry for that! Here is the txt-file.

[KOPIElog.txt](https://github.com/Courseplay/courseplay/files/2830224/KOPIElog.txt)

**Comment by pvajko** [comment]
Is this still happening?

**Comment by tjBerlin** [comment]
Will test it...

**Comment by tjBerlin** [comment]
It working perfectly! Thanks!
