### ISSUE TITLE
Closing cover

### ISSUE THREAD

**Issue by BI4LY** [Courseplay/courseplay#3129]
Hi
Yesterday I updated CP, I dont know what do you changed but now, when I start course "loading in silo and transport to sell point" truck stops and close cover on the trailer so there is no way to load it. Also every time when I clear the current course he closes the cover on trailer (it didn't happen earlier). On saturday it was ok but since yesterday something broke. 
[sorry for my english]

**Comment by sootysax** [comment]
Duplicate #3104

**Comment by BI4LY** [comment]
sorry I didn't noticed that
