### ISSUE TITLE
Horsch Maestro 12 SW

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3130]
The Horsch Maestro has a bug in it from Giants that opens the wrong cover when presented with a fertilizer or seed big bag..  therefore it requires that the opposite silo cover be open when refilling from seed or fertilizer silos.. 

So, the Maestro will refill seed but not fertlizer on a refill course..  I'm not sure if there is anything that you can do about this with the planter having a GIANTS bug in it..  

I don't know if Courseplay already has something to handle the need to open different covers on planters/seeders already or not

**Comment by ThomasGaertner** [comment]
test with v0045 and report...

**Comment by sootysax** [comment]
great success, thank you!
