### ISSUE TITLE
Automatic Covers not working in Mode 2

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3136]
Automatic covers are not working when approaching a combine in Mode 2.  

If either enabled or disabled in the courseplay menu, you can still manually uncover or cover the trailer with the "N" key command while a course is running.  

When the option is turned on, the covers are automatically coming on and off when starting a course, or approaching the tip trigger.

Using 6.01.00043

**Comment by ThomasGaertner** [comment]
#3140

**Comment by sootysax** [comment]
covers seem to be working well in mode 2 with .00052 as well
