### ISSUE TITLE
Overloader mode greyed out 

### ISSUE THREAD

**Issue by sirbum69** [Courseplay/courseplay#3138]
until i updated the other day my overload would work. now its greyed out no matter what i use. Only thing i can use is the combi unload. which doesnt seem to work very well with a auger wagon.
![image](https://user-images.githubusercontent.com/47197381/52315438-7fe66580-297c-11e9-9876-b49dccffc0fd.png)

**Comment by jobyrns72** [comment]
Same problem here

**Comment by sirbum69** [comment]
i am going to remove all mods and try on a test map just to be sure its not a mod, but i havnt installed any in a few weeks. just updated courseplay. i want to say the last time it worked was like 6100014

**Comment by sirbum69** [comment]
update: tested on felsbrun map with no mods other then courseplay and its still greyed out

**Comment by Jimmy-the-Geek** [comment]
It's been stated before that this feature is disabled for the time being.

**Comment by sirbum69** [comment]
oh sorry, when i made the title it didn't show anything.
