### ISSUE TITLE
Pronto DC will not open cover for fertilizer trigger

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3139]
This trigger was previously working - now the cover will not open for the fertilizer trigger, but will open for the seed trigger.  If the cover is left open, the implement will fill fertilzer..  however the cover will no longer stay open when starting/stopping a course as it did previously.

https://gist.github.com/sootysax/3150c379c49ada45739b6a436638bb95

![fsscreen_2019_02_05_21_51_46](https://user-images.githubusercontent.com/6591048/52318146-0ad15b00-2991-11e9-8c43-f624abf37d8c.png)
![fsscreen_2019_02_05_21_51_54](https://user-images.githubusercontent.com/6591048/52318150-0e64e200-2991-11e9-9f97-ffbf447e8919.png)

_Originally posted by @sootysax in https://github.com/Courseplay/courseplay/issues/2976#issuecomment-460884516_

**Comment by Martinnygaard** [comment]
I have the newest version (v6.01.00082) and this is still an issue for me (same seeder, excatly same setup)

Only difference, is that mine will accept Fertilizer, then close the lid and then drive right pass the seed tank without filling.

**Comment by Martinnygaard** [comment]
I have the newest version (v6.01.00082) and this is still an issue for me (same seeder, excatly same setup)

Only difference, is that mine will accept Fertilizer, then close the lid and then drive right pass the seed tank without filling.


On the picture here, i am manually refilling without moving the tractor, so the trigger is within the reach.
![courseplay1](https://user-images.githubusercontent.com/26490587/53107959-7a6d4b80-3536-11e9-9c16-bc891471cb05.png)
