### ISSUE TITLE
when full, overloader cut road to the combines

### ISSUE THREAD

**Issue by Cassio38** [Courseplay/courseplay#3140]
![image](https://user-images.githubusercontent.com/20385247/52331452-83b7cd80-29f8-11e9-8194-0a16e8115a81.png)

while when not full, overloader wait for waiting position to be free behind the combine, when they are full they go full throttle to the starting point of the overloading track, often interfering with the combine like in this case, running in front of it

**Comment by ThomasGaertner** [comment]
mode2 ist still not in process of refactoring. We are using the old code from CP5 at the moment.
As soon as we have mode 1,4 and 6 stable we will start to refactor mode 2,3, 8, 9 and 10.  Till then I wont fix any none game crashing issues for mode 2 . thanks for understanding.

**Comment by Tensuko** [comment]
Does the Combine still Push other Vehicles away or does the Colission-Detection work now so Combine stops when something is in the way ?

**Comment by pigeth** [comment]
the combine still pushes others away

**Comment by Cassio38** [comment]
yes it pushes others away. ok ThomasGaertner, thanks you :)

**Comment by ThomasGaertner** [comment]
#3311
