### ISSUE TITLE
Tool cutting position adjustment fore/aft needed

### ISSUE THREAD

**Issue by prjndigo** [Courseplay/courseplay#3142]
Equipment that has mildly non-standard configurations can result in CP thinking the tool position is behind the vehicle... this means that combines trample crops.  Same as the width adjust on tool we need fore/aft adjustment capacity.

**Comment by jhndrtxn** [comment]
This is already available in the Tractor tab

**Comment by Tensuko** [comment]
No more comments. So must be solved.
Closed.
