### ISSUE TITLE
LS17 / CoursePlay is not showing up in the game

### ISSUE THREAD

**Issue by tschamberger** [Courseplay/courseplay#3144]
i put 2 course play mods now in because if i put them in one by one it is also not working.

FS17_Courseplay - downloaded here - https://www.farming-simulator.com/mod.php?mod_id=92045
FS17_CoursePlay5 - developer Version from http://courseplay.github.io/courseplay/de/installation/index.html

See my logs below

GIANTS Engine Runtime 7.0.0 (14220) 64bit (Build Date: Feb 17 2017)
Copyright (c) 2008-2016, GIANTS Software GmbH (giants-software.com), All Rights Reserved.
Copyright (c) 2003-2016, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: FarmingSimulator2017
Main System
  CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Memory: 7800 MB
  OS: Windows NT 6.1 64-bit
Physics System
  Version: 5.9.5
  Thread(s): 2
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick enabled
  Force Feedback disabled
Audio System
  Driver: OpenAL
  Version: 1.1
  Device: Generic Software Compatibility Mode
Render System
  Driver: Direct 3D 11
  Card Vendor: Intel Corporation
  Renderer: Intel(R) HD Graphics 520
  Version: 10.18.15.4281 (31.8.2015)
  Revision: 7
  Feature level: DirectX 11 ON
Info: Effective window resolution 1280 x 720
Started 2 threads for threadpool 'Render threadpool'
Hardware Profile
  Level: Medium (forced)
  View Distance Factor: 1.000000
  Shadow Quality: 1.000000 Size: 2048 Filter-Size: 4
  Shader Quality: 1
  Skip Mipmaps: 1
  LOD Distance Factor: 1.000000
  Terrain LOD Distance Factor: 1.000000
  Terrain Normal Mapping: Yes
  Foliage View Distance Factor: 1.000000
  Foliage Density: 0.500000
  Volume Mesh Tessellation Factor: 1.000000
  Tyre Tracks Segments Factor: 1.000000
  Max. Number of Shadow Lights: 1
  Max. Number of Lights: 512
  Max. Number of Lights Per Cluster: 32
  MSAA: 0
Farming Simulator 17
  Version: 1.4.4.0 1.4.4RC8
  Available Languages: en de jp pl cz fr es ru it pt hu nl cs ct br tr ro kr
  Language: de
  Time: 2019-02-06 18:42:28
  Register configuration 'inputAttacherJoint'
  Register configuration 'attacherJoint'
  Register configuration 'frontloader'
  Register configuration 'motor'
  Register configuration 'baseColor'
  Register configuration 'wheel'
  Register configuration 'rimColor'
  Register configuration 'design'
  Register configuration 'designColor'
  Register configuration 'vehicleType'
Game vehicle types loaded
Load mod: FS17_Bankofhagenstedt (Version: 2.2.0.0)
Load mod: FS17_Courseplay (Version: 5.3.0.0)
Error: Unsupported mod description version in mod FS17_Courseplay
Error: Failed to open xml file 'C:/Users/tschamberger/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/modDesc.xml'.
Load mod: FS17_CoursePlay5
Error: Missing descVersion attribute in mod FS17_CoursePlay5
Load mod: FS17_Fichtelberg (Version: 1.1.0.0)
Load mod: FS17_Stappenbach17 (Version: 1.2.0.1)
Physics System
  Version: 5.9.5
  Thread(s): 2
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick enabled
  Force Feedback disabled
Audio System
  Driver: OpenAL
  Version: 1.1
  Device: Generic Software
Render System
  Driver: Direct 3D 11
  Card Vendor: Intel Corporation
  Renderer: Intel(R) HD Graphics 520
  Version: 10.18.15.4281 (31.8.2015)
  Revision: 7
  Feature level: DirectX 11 ON
Info: Effective window resolution 1280 x 720
Started 2 threads for threadpool 'Render threadpool'
Hardware Profile
  Level: Medium (forced)
  View Distance Factor: 1.000000
  Shadow Quality: 1.000000 Size: 2048 Filter-Size: 4
  Shader Quality: 1
  Skip Mipmaps: 1
  LOD Distance Factor: 1.000000
  Terrain LOD Distance Factor: 1.000000
  Terrain Normal Mapping: Yes
  Foliage View Distance Factor: 1.000000
  Foliage Density: 0.500000
  Volume Mesh Tessellation Factor: 1.000000
  Tyre Tracks Segments Factor: 1.000000
  Max. Number of Shadow Lights: 1
  Max. Number of Lights: 512
  Max. Number of Lights Per Cluster: 32
  MSAA: 0
Farming Simulator 17
  Version: 1.4.4.0 1.4.4RC8
  Available Languages: en de jp pl cz fr es ru it pt hu nl cs ct br tr ro kr
  Language: de
  Time: 2019-02-06 18:42:58
  Register configuration 'inputAttacherJoint'
  Register configuration 'attacherJoint'
  Register configuration 'frontloader'
  Register configuration 'motor'
  Register configuration 'baseColor'
  Register configuration 'wheel'
  Register configuration 'rimColor'
  Register configuration 'design'
  Register configuration 'designColor'
  Register configuration 'vehicleType'
Game vehicle types loaded
Load mod: FS17_Courseplay (Version: 5.3.0.0)
Error: Unsupported mod description version in mod FS17_Courseplay
Error: Failed to open xml file 'C:/Users/tschamberger/Documents/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/modDesc.xml'.
Load mod: FS17_CoursePlay5
Error: Missing descVersion attribute in mod FS17_CoursePlay5
Load mod: FS17_Fichtelberg (Version: 1.1.0.0)
Load mod: FS17_Stappenbach17 (Version: 1.2.0.1)

**Comment by Tensuko** [comment]
Both in ? Sure not Working. The one you can download from ModHub in FS17 should work without problems unless you got a Mod that causes a Conflict.

**Comment by Symbob** [comment]
Your FS17 is not updated with the latest patch 1.5.3.1.  You don't want duplicate versions of the mod either, so delete one of them.  Either should work once you've updated your FS17.
