### ISSUE TITLE
LUA call stack when attaching SEK802 Bale trailer

### ISSUE THREAD

**Issue by Django215** [Courseplay/courseplay#3145]
When I use the sek802 as a bale trailer comes at the trying to attach him a lua error. 

as a normal trailer everything is okay.

only with the bale configuration comes the error

https://filehorst.de/d/csrxfdFB

**Comment by pvaiko** [comment]
I see it does that but does actually cause any issues?

**Comment by Tensuko** [comment]
Closed cause of inactivity.
