### ISSUE TITLE
F1 Menu hides when Mouse over a scrollable Value

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/courseplay#3147]
When you Go with Mouse over a Value that can be changed with the Mousewheel, the F1 Menu hides.
Is it from fixing the Zoom in/out when scrolling ? Sry to ask this, but there is someone asking if it is a bug.

So close it when it is not a bug/problem. (Actually I think no, but I just ask anyway)

**Comment by Satissis** [comment]
Nah it's a normal behavior with the way we do it atm.
It might be something I'll see if I can do another way when we are going to refactor/rewrite most of CP

I'll close here ;)
