### ISSUE TITLE
Combine Lowers header to late

### ISSUE THREAD

**Issue by shasol** [Courseplay/courseplay#3148]
When combine turns to start next line, it lowers the header to late and miss about 2 to 3 meters at the start.
![20190206224102_1](https://user-images.githubusercontent.com/2841839/52375717-9d8cfb00-2a60-11e9-8194-53e4498dc8a4.jpg)
 just before the turn

![20190206224117_1](https://user-images.githubusercontent.com/2841839/52375744-abdb1700-2a60-11e9-93c8-19e9d08e1daf.jpg)
mid turn

![20190206224127_1](https://user-images.githubusercontent.com/2841839/52375760-b72e4280-2a60-11e9-9728-7d1db4a9020b.jpg)
and after the turn and as you can see, it misses the first bit

**Comment by sootysax** [comment]
what version are you using?

**Comment by shasol** [comment]
ah yeah sorry about that, i'm using version 6.01.00044

**Comment by Messy71** [comment]
did you try to change the “Tool vertical offset” (front or back) it changes the working are marked with a red rectangle or line.(If you can’t see the red thingy just change the tool horizontal offset to left or right 1m that will show it and then change it back to center.)
PS : When changing the tool vertical offset the visual marker for the working area isn’t displaying , it’s a problem but not a game braking one, for now we have a work-around solution so don’t post a new issue here, let the CP team some breathing space.

**Comment by crimso** [comment]
Hello, sometimes I have the same issue but reattaching the tools to the tractor or combine solves these problems.

**Comment by pvajko** [comment]
Just out of curiosity, can you reproduce this with standard non-mod combines?

**Comment by shasol** [comment]
After some testing, I can see that it is a problem with that particular corn header. using the "normal" header, does not reproduce the problem.
