### ISSUE TITLE
Constantly stuck in traffic on combi mode

### ISSUE THREAD

**Issue by rob230580** [Courseplay/courseplay#3149]
HI, apologies if already discussed, new here. I just downloaded latest beta and getting tractor and trailer stuck in traffic almost constantly in the field. On the road is ok. Harvesting beets and maize and in both it did the same, tried restart course and new course. Seems more likely when it is close to harvester but its mostly anywhere in the field. I also had a tractor hit a car on the road, next time in the same place the tractor stopped in the road and was very glitchy. Didn't get these problems in the first beta so thought id let you know.

**Comment by ThomasGaertner** [comment]
Which tools do you use ? Screenshot?

**Comment by rob230580** [comment]
Apologies, I loaded game tonight and its fixed, I think what caused it was the tractor and trailer got stuck behind traffic on the road when it stopped for a hired worker in a field. Somehow I think this caused the glitch.....? Thanks anyway, really like he new way the trailer turn at the end of fields for maize harvesting.
