### ISSUE TITLE
Tipper won't go to harvester while pipe is in fruit

### ISSUE THREAD

**Issue by Symbob** [Courseplay/courseplay#3151]
In combi mode the tractor and tipper won't drive to harvester while the pipe is in fruit, even when harvester is at 100%.  If you stop then restart the driver of the tipper he still will not go to harvester, and the message "Combines pipe is in fruit" is displayed in the CP hud.  Let me know if you need any further debug info.

**Comment by Symbob** [comment]
![fsscreen_2019_02_07_12_56_24](https://user-images.githubusercontent.com/18528850/52413431-82120680-2ad9-11e9-92e5-2360d8b55f65.png)

**Comment by sootysax** [comment]
turn off pathfinding

**Comment by AgroWillem** [comment]
Maybe a very dumb question: but where do i turn off pathfinding?

Thx ahead so far for you guys great work. FS is nothing without CP.

**Comment by Erwin1944** [comment]
Good Morning to everyone, you can find it in settings, first choice, greetings.

**Comment by AgroWillem** [comment]
Found it. Called in Dutch "Om gewas rijden". In English: Drive around crop

Thx!

**Comment by Symbob** [comment]
Is this by design?  I'd taken a break from FS for around 12 months, and only just come back to it with the release of FS19.  The last time I used courseplay in FS17 if the pipe was in fruit the tipper would still go to the combine when it reached 100%.  I can see much has changed in CP since then so has this change been made purposely?

**Comment by sootysax** [comment]
> I can see much has changed in CP since then so has this change been made purposely?

Mode 2 has all kinds of problems.   It is still the old version from CP5, and there simply as a filler until they can rework it for FS19.

**Comment by ThomasGaertner** [comment]
#3140
