### ISSUE TITLE
Trailer limit

### ISSUE THREAD

**Issue by mahoni1970** [Courseplay/courseplay#3152]
Hi
Did you set a Limit of <= 100.000  to Trailers or did it Giants? an how could i Change it to 250.000 or something else

regards

**Comment by Tensuko** [comment]
Easy to test: Put CP out of your Modfolder and try again.

**Comment by mahoni1970** [comment]
It is from CP

**Comment by Dajoor** [comment]
Drive.lua : 1830

**Comment by mahoni1970** [comment]
Thx

**Comment by ThomasGaertner** [comment]
fixed in V06.01.00054 ....

**Comment by ThomasGaertner** [comment]
@mahoni1970 : can we close here ?

**Comment by mahoni1970** [comment]
Yes perfekt  Thx
