### ISSUE TITLE
Suggestion - Call driver at end of field work

### ISSUE THREAD

**Issue by Knowen** [Courseplay/courseplay#3158]
Hello,

most of the time, the combine harvester still has grain in the tank at the end of the fieldwork. One has usually turned off a helper to unload the combine harvester. 
Is it possible that the combine will automatically call the helper when waiting at the last waypoint of fieldwork?

**Comment by ThomasGaertner** [comment]
@pvajko : it did it in CP5 allready...

**Comment by Knowen** [comment]
Has this already been implemented? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ThomasGaertner** [comment]
since there is no issues related push, nope ...

**Comment by Tensuko** [comment]
With the rework of Mode2, we will have to think about such cases too and see how we add this.
#3311 
Closed.
