### ISSUE TITLE
Vehicles do not resume course after fuel refill trigger

### ISSUE THREAD

**Issue by Symbob** [Courseplay/courseplay#3159]
Sorry guys, but I think I've found another little problem.  When a tractor goes through a fuel refill trigger it slows down to 6mph (or whatever speed is set as the turn speed).  After leaving the trigger the tractor does not resume the course at it's normal speed, but continues at 6mph for the rest of the course or until I stop and restart the driver.  If I change the setting for "Refill fuel at gas station" to ALWAYS the tractor will stop to refuel but won't continue the course at all after refilling. On Ravenport the fuel trigger for the gas station stretches out in to the road so every time the course goes past the gas station this problem occurs.  Using v6.01.00047

**Comment by sootysax** [comment]
duplicate #3154

**Comment by ThomasGaertner** [comment]
Yes, I need more info: which mode did you use ? which tools ?

**Comment by ThomasGaertner** [comment]
try with v54 or higher and report

**Comment by sootysax** [comment]
speed is recovering to max speed instead of turn speed for me..  v00054

**Comment by gabriel170603** [comment]
I have the same, when my seeder wants to refill. He goes to point, where to refill, refills but then didn't continue driving the course. 
v.00049

**Comment by ThomasGaertner** [comment]
@sootysax @Symbob : so its solved for you ?
@gabriel170603 : if you would have read the basic issue, you would have seen, that you not have the same issue. we are here about a frozen speed setting. don't mix issues

**Comment by Symbob** [comment]
Thank you.  This has solved the issue with fuel triggers   v00059

**Comment by sootysax** [comment]
yes solved for me
