### ISSUE TITLE
Gülle ausbringen

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#3160]
Wie muss ich den Courseplay für LS19 einstellen damit der Fahrer die Gülle vom Hof zum Feld bringt ?

Und wie kann der Fahrer das Hochsilo mit den Anhänger leeren und das Getreide zum Landhandel fahren ?

**Comment by KenStumich** [comment]
grunsätzlich steht alles in der Hompage [http://courseplay.github.io/courseplay/](url) da sich die funktionen von 17 auf 19 nicht geändert haben.
für die mehr audio/visuell veranlagten typen ist youtube mit der suche nach coursplay tutorial ggf deutsch dein freund. auch hier kann eine 17er version grunsätzlich helfen.

das hier ist übrigens ne beta, von daher geht noch nicht alles.

übrigens. ist es dir nicht komisch vorgekommen das hier alles in englisch schreibt.

he has his answer, close pls
