### ISSUE TITLE
Auger wagon crashes game at drive on value

### ISSUE THREAD

**Issue by Liftedandblown** [Courseplay/courseplay#3161]
Not sure If Ive got something wrong or not, this is my first foray into FS and courseplay.  Absolute MUST have by the way thanks so much for your work and effort.

Anyways, tested with all 4 in game auger wagons in comb mode, after the wagon reaches 100%.  Its almost instant and the graphics trail away,  No way to get it to refocus or change vehicles, I can access the menu, but the further into the menu's I get I cant back up any levels.  Thanks again for the hard work.
![lua error on mode 3](https://user-images.githubusercontent.com/47453746/52485644-f6eb4c00-2b7e-11e9-8f02-3357ba1ba7c3.gif)

**Comment by crimso** [comment]
Hello, as I know overloader mode is not working yet.
