### ISSUE TITLE
Harvester continuous locking at the beginning and opening the discharge pipe. Now locking FS19 when starting

### ISSUE THREAD

**Issue by marcospms** [Courseplay/courseplay#3162]
Harvester continues locking at the beginning and opening the discharge pipe. Now locking FS19 when starting. This time i use a first version courseplay to fs 19, because all others version have error with harvester.

**Comment by pvajko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by xjjohnsonx** [comment]
im also having this issue. im using a moded harvester and I have to run a trailer behind it. its almost like it thinks its full

**Comment by pvajko** [comment]
Closing due:
1. inactivity
2. mods
3. lack of a clear description and logs
