### ISSUE TITLE
No courses will start with 1.3.0 Beta on GIANTS or most ModHub maps

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3165]
CP will not start any course with FS19 1.3.0 Beta on Marwell Manor, Ravenport, Felsbrun, Alps or Grizzly Mountain, however courses ARE working on Estancia Lapacho and New Bartelshagen.

Courses are also working on several non-ModHub maps like Sutton Farms, Wesby Wisconsin, Flusstal XL.

it's only happening on these GIANTS and ModHub maps as far as I can tell.

To test all these maps, I simply recorded a circle in a tractor and tried to drive a 'transfer route'

Starting a course will bring up the arrow pointing toward the first waypoint but lock up the vehicle.

It does not actually start the course, it still says 'Drive Course', but the helper is hired, but paralysed.  The only thing you can do is unhire the helper, and that frees up the vehicle again.

![fsscreen_2019_02_08_12_28_37](https://user-images.githubusercontent.com/6591048/52494986-6f610580-2b9d-11e9-8ba6-2cd93ab187c2.png)

https://gist.github.com/sootysax/f19a3e2099f1ac24f655ea5da374f4da

v .000048 & 49

**Comment by joshvzeyl** [comment]
i have no issue with 1.3 beta and courseplay

**Comment by sootysax** [comment]
I reverted to .00044.dev, and it's still not working..  just locking up the worker..

This is on the new Marwell Manor map..   I will try again on the other map i was using.

**Comment by joshvzeyl** [comment]
i haven't tried marvell manor, but i'm on rolling hills

**Comment by hoefti10** [comment]
Same Issue, Patch 1.2 and cant load the Savegames with .00048
With .00046 its still working.

**Comment by sootysax** [comment]
this issue is not about not being able to load save games, its about courses not running.

**Comment by joshvzeyl** [comment]
i tried marvell manor myself and i get that arrow with patch 1.3, and version .00046 of courseplay, but don't get it on rolling hills

**Comment by Flacwby** [comment]
It's not just modhub maps. It won't work on Ravenport either. I turned off the 1.3 beta and all works just fine. v00049.

**Comment by gabriel170603** [comment]
On both of my Giant Maps everything is working, but not the course where the Tractor should load at the silo and unload at a point to sell. In the moment you turn on the helper for the course, nothing is happening, it is just showing loading, but it is not even under the silo. When you drive it manually under the silo, it is loading completely, but Courseplay shows loading 10000 of 10750 (not completely filled) although the trailer is completely full. v00049

**Comment by sootysax** [comment]
which GIANTS maps, and are you using the 1.3.0 beta?

**Comment by sootysax** [comment]
> On both of my Giant Maps everything is working, but not the course where the Tractor should load at the silo and unload at a point to sell. In the moment you turn on the helper for the course, nothing is happening, it is just showing loading, but it is not even under the silo. When you drive it manually under the silo, it is loading completely, but Courseplay shows loading 10000 of 10750 (not completely filled) although the trailer is completely full. v00049

This is happening to me with Mode 1 on my Westby Wisconsin map, a non GIANTS Modhub map..  so it's effecting all maps.   Mode 2, 4, 5and 6 are working normally.  Mode 1 will not move at all.

**Comment by sootysax** [comment]
> On both of my Giant Maps everything is working, but not the course where the Tractor should load at the silo and unload at a point to sell. In the moment you turn on the helper for the course, nothing is happening, it is just showing loading, but it is not even under the silo. When you drive it manually under the silo, it is loading completely, but Courseplay shows loading 10000 of 10750 (not completely filled) although the trailer is completely full. v00049

This too is a different issue... one that rolling back to .00046dev recovers from

**Comment by xman1971** [comment]
v00049 Mode 1 does not work v1.2

**Comment by sootysax** [comment]
> v00049 Mode 1 does not work v1.2

#3168

**Comment by alpha117** [comment]
same issue, course generated, but will not drive it. Also will not drive saved courses. Something must have changed in BETA 1.3, I was having no issues before the update

**Comment by xman1971** [comment]
v00046 works on 1.3 beta

**Comment by sootysax** [comment]
> v00046 works on 1.3 beta

um.. nothing about v00046 works in 1.3 beta..  not mode 1, 2, 4, 5 or 6.. what exactly is working for you?

**Comment by xman1971** [comment]
v00046 works only map am testing doesn't work on ravenport or michigan map

**Comment by sootysax** [comment]
![giphy](https://user-images.githubusercontent.com/6591048/52514398-55e0ad80-2bdf-11e9-94e3-1650ed47e559.gif)

**Comment by dominiczeth** [comment]
Same Problem with Version 049. 

That's what the game lock says when the yellow arrow appears:

`2019-02-09 07:18 Error: Running LUA method 'mouseEvent'.
2019-02-09 07:18 E:/Dominic/My Games/FarmingSimulator2019/mods/FS19_Courseplay/triggers.lua:576: table index is nil
2019-02-09 07:18 dataS2/character/humans/player/player02.i3d (223.93 ms)
2019-02-09 07:18 Error: Running LUA method 'mouseEvent'.
2019-02-09 07:18 E:/Dominic/My Games/FarmingSimulator2019/mods/FS19_Courseplay/triggers.lua:576: table index is nil
2019-02-09 07:18 Error: Running LUA method 'mouseEvent'.
2019-02-09 07:18 E:/Dominic/My Games/FarmingSimulator2019/mods/FS19_Courseplay/triggers.lua:576: table index is nil
2019-02-09 07:18 CourseGeneratorScreen:onCreate()
2019-02-09 07:18 Error: Running LUA method 'mouseEvent'.
2019-02-09 07:18 E:/Dominic/My Games/FarmingSimulator2019/mods/FS19_Courseplay/triggers.lua:576: table index is nil`

**Comment by alpha117** [comment]
Morning all,
#51 fixed this for me, all back to normal. great and quick work.  
Many thanks

**Comment by ThomasGaertner** [comment]
should work for both versions, beta and normal

**Comment by sootysax** [comment]
working well on Marwell in 1.3.0 for me!  you guys are the best
