### ISSUE TITLE
courseplay version 06.01.00048: doesn't let me load my savegame

### ISSUE THREAD

**Issue by joshvzeyl** [Courseplay/courseplay#3166]
version  06.01.00048:  doesn't let me load my savegame and throws the errors of  issue  #3164, but if i go back to version .0046 i have no issues i also run the 1.3 beta patch

**Comment by hoefti10** [comment]
Same Issue, Patch 1.2 and cant load the Savegames with .00048
With .00046 its still working.
.00047 is also not working.

**Comment by pvajko** [comment]
Duplicate
