### ISSUE TITLE
mal was anderes

### ISSUE THREAD

**Issue by DerMicha23** [Courseplay/courseplay#3167]
Mal ein dankeschön an den gesammten team für die arbeit und zeit die ihr für uns investiert

**Comment by TomBos** [comment]
Hear Hear!

**Comment by SavageMkII** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by ThomasGaertner** [comment]
Danke, ich mach hier zu sonst wird unübersichtlich
