### ISSUE TITLE
Mode 1 : Vehicle will not move or load grain from trigger

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3168]
On both of my Giant Maps everything is working, but not the course where the Tractor should load at the silo and unload at a point to sell. In the moment you turn on the helper for the course, nothing is happening, it is just showing loading, but it is not even under the silo. When you drive it manually under the silo, it is loading completely, but Courseplay shows loading 10000 of 10750 (not completely filled) although the trailer is completely full. v00049

_Originally posted by @gabriel170603 in https://github.com/Courseplay/courseplay/issues/3165#issuecomment-461939995_

**Comment by sootysax** [comment]
https://gist.github.com/sootysax/6507521272339a4277124c59a05c9201

![fsscreen_2019_02_07_21_27_40](https://user-images.githubusercontent.com/6591048/52507280-0f7b5680-2bbf-11e9-98b0-11c23a3c5ecc.png)

**Comment by summerfarmestates** [comment]
i was useing a ford 5640 and agoroliner cart to offload combine on michigan farming all was working fine untill patch 1.3 went back to patch 1.2 and starts to work again  issue between courseplay and new patch

**Comment by sootysax** [comment]
> i was useing a ford 5640 and agoroliner cart to offload combine on michigan farming all was working fine untill patch 1.3 went back to patch 1.2 and starts to work again issue between courseplay and new patch

completely different issue

**Comment by sootysax** [comment]
fixed, so fixed..  you guys are late night coding wizards

**Comment by pvajko** [comment]
@sootysax there are so many time zones...
