### ISSUE TITLE
Mode1 doesn't load

### ISSUE THREAD

**Issue by tjBerlin** [Courseplay/courseplay#3170]
CP version .00050, RAVENPORT, FENDT and trailer JOSKIN , no mods.

Steps to reproduce:

1. Record a course that does start on a SILO trigger. 
2. Go to Mode 1 and start the course.
3. The vehicle will drive through waypoint 1 ("wird bealden"), even if empty. No loadin.

![bildschirmfoto 2019-02-09 um 08 49 05](https://user-images.githubusercontent.com/24283753/52519034-7b100300-2c55-11e9-831f-893465fcecf1.png)

[log.txt](https://github.com/Courseplay/courseplay/files/2847679/log.txt)

if needed:
Course:
https://gist.github.com/tjBerlin/ed220405d5623e118288c676e9bc01d4

savegame: 
https://gist.github.com/tjBerlin/5723034dab42c144285dcc3624722d60

**Comment by tjBerlin** [comment]
> 3\. capacity

d bealden

**Comment by ThomasGaertner** [comment]
could you pleas update the whole files ?

**Comment by pvajko** [comment]
This is because the new mode 1 goes to filling mode only around waypoints 1-3 and this is a long tipper, and because I was not able to decrypt this condition in the original code: https://github.com/Courseplay/courseplay/blob/2aa2d7957da7870a1ed5f487ba04260ab799ddf7/mode1.lua#L12

**Comment by tjBerlin** [comment]
Yes, it is course 8 and 10.

[savegame4.zip](https://github.com/Courseplay/courseplay/files/2847769/savegame4.zip)

[MapUS.zip](https://github.com/Courseplay/courseplay/files/2847770/MapUS.zip)

**Comment by tjBerlin** [comment]
@pvajko So I have to start the recording course before the tipper?

**Comment by pvajko** [comment]
I can't see where your course starts but from what I see I believe that starting it a little further away from the silo (for instance so that the tipper is under the pipe) would help in this case.

**Comment by tjBerlin** [comment]
I will try it and report:).

**Comment by tjBerlin** [comment]
It is working perfectly! Thanks a lot! I will close it!
