### ISSUE TITLE
Course speed gets stuck to turning speed after first unload to silo.

### ISSUE THREAD

**Issue by AtlAntA118** [Courseplay/courseplay#3172]
Unloading a combine and transporting to silo works fine the first run but whenever the vehicle passes the unload trigger (succesfully) the first time the vehicle is stuck on turning speed the rest of the time until the worker is restarted. When its stuck on turning speed the next time it trys to unload not always succeeds.

I will try and add my savegame and courseplay courses. I am using a modded silo but the unload triggers are untouched. It just accepts just about everything. The bug does happen with the stock silo as well. For ease of testing i will add the modded silo as well.

I know i am using a lot of mods but this is happening on a fully stock fellsbrunn as well. Also it happens in 1.2 and in 1.3.

[FS19_MultiFarmSiloLarge.zip](https://github.com/Courseplay/courseplay/files/2847813/FS19_MultiFarmSiloLarge.zip)
[FS19_MultiFarmSiloExtension.zip](https://github.com/Courseplay/courseplay/files/2847814/FS19_MultiFarmSiloExtension.zip)
[CoursePlay_Courses.zip](https://github.com/Courseplay/courseplay/files/2847816/CoursePlay_Courses.zip)
[savegame1.zip](https://github.com/Courseplay/courseplay/files/2847817/savegame1.zip)
[FS19_Bandit800.zip](https://github.com/Courseplay/courseplay/files/2847835/FS19_Bandit800.zip)

Edit: Tab to the fendt 1050 and load course "courseStorage0013" named "F26F27 to Silo"
Let that run its course to the unloading point. You will see it will go there just fine and unload just fine but after that it gets stuck on the turning speed setting. 

edit2: i forgot i used a mod trailer. For ease of testing i added the trailer as well. Happens with stock trailer also so makes no difference.

**Comment by sootysax** [comment]
duplicate : #3159 #3154

**Comment by AtlAntA118** [comment]
Terribly sorry didn't see those.
