### ISSUE TITLE
Field Work Time to Completion...Question

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#3173]
I'm sure this was in CP(V5), there was a count down timer, telling you how long left for the field task to be completed; unless I was dreaming it!

Is this to be implemented in V6?

Thanks

**Comment by ThomasGaertner** [comment]
@pvajko :do you want me to do it ?

**Comment by pvajko** [comment]
@ThomasGaertner sure. Goes into FieldworkAIDriver.

**Comment by alpha117** [comment]
Thanks Guys

**Comment by devilboy123** [comment]
As anyone have trouble set a course with the miss island function I set up to go in a circle around the island it don't put in the course when it been generated thank you

**Comment by pvajko** [comment]
Should now be working, reopen if not.
