### ISSUE TITLE
Gülle zubringer

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#3175]
Wenn ich den Abfahrer einstellen möchte zum Gülle zubringen kommt unten links im Menü kein Bild zum Flüssigkeiten transportieren

**Comment by tjBerlin** [comment]
Courseplay ist noch in der Beta-Phase und unterstützt nur die Modi 1, 2, 4, 5 und 6. An Modus 3 (Flüssigkeitenzubringer) wird gearbeitet, wenn der Rest stabil läuft. 

Übrigens: Grundsprache ist hier ENGLISH, weil viele Programmierer über die Welt verteilt an diesem Projekt arbeiten. 

He has an answer. This can be closed.

**Comment by ThomasGaertner** [comment]
mode 3 ist der Überlader, mode8 (Flüssigkeitstransport) ist aber auch noch gesperrt stimmt :-)
