### ISSUE TITLE
Open & Close Hud Mac Keyboard

### ISSUE THREAD

**Issue by Velocity83** [Courseplay/courseplay#3176]
I don't like using the right mouse but to open or close the hud, however the Mac keyboard doesn't have a " delete Key " so I cant use that either, is there anything I can change so its what I would like it to be?

Thanks

**Comment by sootysax** [comment]
you can assign any key you want for any command..  however there are issues with key commands working intermittently

**Comment by Velocity83** [comment]
How would I go about assigning a different key? In an xml file?

**Comment by knarffenfarmer** [comment]
Go to key settings, scroll all the way to the bottom, there er courseplay keybinds there.
they are called CP.

**Comment by Hubcap-1** [comment]
Problem opening / closing  is universal...not just mac. We need to put this issue as # 1. All other issues need to take a back seat. If you can not turn the program on or off reliably....what problem should have a higher priority...Priorities are confused.

**Comment by ThomasGaertner** [comment]
try again with v.151 or higher
