### ISSUE TITLE
Pickup Tractor blocking Harvester

### ISSUE THREAD

**Issue by Beebtrek** [Courseplay/courseplay#3178]
Hello guy's Great work I am using the Beta at this time. 
I have noticed that with most of the Harvesters when Harvesting a field using a Helper. The Pickup Tractor and Trailer quite often greater than 40% blocks the path of the harvester after collection. Is there a way to get the tractor to park on an already harvested part of the field?

I also had this in the latest version for FS17.

**Comment by pvajko** [comment]
There are about a million duplicates of this already.
