### ISSUE TITLE
Mode 1 Still will not load as in #3170

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3179]
Same issue as #3170 

Start point is directly under load pipe.  Rolls right past first waypoint and gets 43l of grain in the tipper.

FS: 1.3.0.0
CP: v.00053
https://gist.github.com/sootysax/ac1cea5c175bd8812546ca8cec77dc15

![fsscreen_2019_02_09_11_25_47](https://user-images.githubusercontent.com/6591048/52523311-0392a180-2c5e-11e9-97a7-bab0fde7efb3.png)
![fsscreen_2019_02_09_11_25_56](https://user-images.githubusercontent.com/6591048/52523313-07bebf00-2c5e-11e9-9689-b27fad0fb87e.png)

**Comment by ThomasGaertner** [comment]
the pipe must be between  last and first waypoint !

**Comment by sootysax** [comment]
thatll do it
