### ISSUE TITLE
Support for filltriggers with menus?

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3180]
Any chance of writing in support of loading seed and fertilizer from silos that pull up menus when you access them?   There is only one option, but you still need to choose it.

I just spent an hour filling up these bastards, and CP wont load from them on a refill run 😡

https://ls-modcompany.com/filebase/file/299-forgotten-plants-farmpack/

https://gist.github.com/sootysax/0223dff13a7a9676d239efe3d0d340d7

![fsscreen_2019_02_09_15_09_52](https://user-images.githubusercontent.com/6591048/52525800-f76a0c80-2c7c-11e9-8bc9-8cfba2bd68c6.png)

![fsscreen_2019_02_09_15_09_35](https://user-images.githubusercontent.com/6591048/52525806-0e106380-2c7d-11e9-8fd5-f96286f84d3e.png)

**Comment by ThomasGaertner** [comment]
test with v56 or higher and report...

**Comment by sootysax** [comment]
untestable, since my vehicle is 'in traffic' anywhere I try to pick up the refill course

**Comment by sootysax** [comment]
Working great in .00059!  Thanks!
