### ISSUE TITLE
attempt to index local 'curTurnTarget'

### ISSUE THREAD

**Issue by RayzerSharpe** [Courseplay/courseplay#3182]
I am in Felstrom map. I have two tractors ploughing field 22. The course that is generated has no headland. 1 tractor starts at the first point and the other half way through., They get about one thiord of the field and then the log file fills up with

2019-02-09 21:30 Error: Running LUA method 'update'.
2019-02-09 21:30 D:/HOME/Documents/My Games/FarmingSimulator2019/mods/courseplay/turn.lua:572: attempt to index local 'curTurnTarget' (a nil value)

The game basically grinds to a halt after this. i will try and turn on some debug channels and see what i get. This happened earlier today while doing the same thing so i'm confident i can replicate it..

**Comment by sootysax** [comment]
you should post your entire log

**Comment by RayzerSharpe** [comment]
sry i didn't manage to replicate it

i'm using version 00036

**Comment by sootysax** [comment]
why are you reporting an issue from a version thats 23 versions old?

**Comment by RayzerSharpe** [comment]
just try to be help...they change so quickly. i have downloaded the last and will try it...

Otherwise you can close it if you want.

**Comment by Chris2996** [comment]
This should be fixed.
