### ISSUE TITLE
It's Dark out there...

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3184]
It's nearly 20:00 game time, and CP will not turn any headlights on...  i thought i remembered lights coming on sooner than that

FS 1.3.0.0
CP .00054

![fsscreen_2019_02_09_20_32_04](https://user-images.githubusercontent.com/6591048/52528322-2480e400-2caa-11e9-94a6-8e7c2fbdecd0.png)
![fsscreen_2019_02_09_20_31_56](https://user-images.githubusercontent.com/6591048/52528323-264aa780-2caa-11e9-89ab-245f1288ee3d.png)

https://gist.github.com/sootysax/a5f4d44b261603c6fc32c8f082e7fcfa

**Comment by sootysax** [comment]
So the lights eventually came on at 21:30h.  Placeable street lights did not come on until then as well?  

Is this a map setting?  it's awful dark by 21:30h?

**Comment by Flacwby** [comment]
Lights come on at 1900 for Ravenport. I believe it's a map issue, not a mod issue.

**Comment by alpha117** [comment]
It is map issue, fix is:
<nightStart="XX"> in the 'mapUS_environment.xml' file. Default value for Marwell Manor is set to 21.5, which means 21:30. 
Change it whatever you want. AFAIK standard maps and most other mod maps use 19.5.

**Comment by ThomasGaertner** [comment]
@sootysax : can we close here ?
