### ISSUE TITLE
Reverse silage bunker unload fail

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3185]
Trying to back into a silage bunker and either it will back all the way into the bunker and then right back out again and never unload, or it unloads as soon as it backs into the bunker and unloads about half its load and stops and sits there.

Log : Never Dumps
https://gist.github.com/sootysax/5c14b28732f8cf62e6a3831a73345825

It seems as if the Tip Trigger Reached gets triggered on the drive in before the reverse maneuver this time

![fsscreen_2019_02_09_23_05_08](https://user-images.githubusercontent.com/6591048/52529465-f0182280-2cbf-11e9-97ca-de2aaa34120e.png)
![fsscreen_2019_02_09_23_05_17](https://user-images.githubusercontent.com/6591048/52529468-f1494f80-2cbf-11e9-8247-227e2867e630.png)
![fsscreen_2019_02_09_23_05_28](https://user-images.githubusercontent.com/6591048/52529478-0de58780-2cc0-11e9-8656-0bbce316e749.png)

**Comment by sootysax** [comment]
Dumps at front of bunker:
https://gist.github.com/sootysax/503b46b195606250a97b3a1cb6e01051

This time the tip trigger reached doesnt appear until the reverse maneuver, but it all dumps at the front of the bunker

![fsscreen_2019_02_09_23_13_52](https://user-images.githubusercontent.com/6591048/52529542-0f637f80-2cc1-11e9-9562-afe38822b6d0.png)
![fsscreen_2019_02_09_23_14_05](https://user-images.githubusercontent.com/6591048/52529543-14c0ca00-2cc1-11e9-9a10-86ec02170213.png)
![fsscreen_2019_02_09_23_14_17](https://user-images.githubusercontent.com/6591048/52529545-17232400-2cc1-11e9-97f6-c2c9c964cf94.png)

**Comment by sootysax** [comment]
![fsscreen_2019_02_09_23_47_47](https://user-images.githubusercontent.com/6591048/52529789-87807400-2cc6-11e9-8a2d-0146db0ed136.png)
![fsscreen_2019_02_09_23_52_26](https://user-images.githubusercontent.com/6591048/52529790-8bac9180-2cc6-11e9-9996-af61e233f857.png)

**Comment by AtlAntA118** [comment]
I got forward  unload working by setting the turn speed to 6km/h. Ofcourse you will have to vary this depending on the trailer you use and how long the bunker is. Looks like CP isnt correctly detecting the length of the unload trigger?

**Comment by mennomanson** [comment]
If i drive forwart in the silo the reverse speed gos to 60 Km/h and the driver go full speed. if that happen can set the reverse speed lower the driver slows

**Comment by GeorgeEarslight** [comment]
I've tried the reverse unload at the same Marwell bunker and was able to fully unload at the bunker's entrance. I don't think this is an issue/bug since this is the expected behaviour.

**Comment by olavinto** [comment]
> I've tried the reverse unload at the same Marwell bunker and was able to fully unload at the bunker's entrance. I don't think this is an issue/bug since this is the expected behaviour.

I can confirm that this is, indeed, a problem. When reversing unloading should start at the deepest end of the bunker but currently it seems to start immediately at the front. If you have a small trailer it might get unloaded fully while standing still but with larger trailers it stops unloading when the heap gets large enough. The tractor should drive on while unloading a little to avoid this and to spread the chaff evenly (starting from the deep end of the bunker).

**Comment by Bubib5** [comment]
Can any of you explain how you got it to unload at all at the Marwell farm BGA at all, for me it happens as per the first post in this thread, it says tip trigger reached even before the bunker, and it never unloads.. Havent tried the BGA yet, will test that later!

**Comment by sootysax** [comment]
i do believe that they changed the behavior to unload at the opening of the bunker rather than the back when the level and shovel mode was developed.

Though the vehicle does not pull up at all during dumping, so it just stops at some point until you manually take over the vehicle

**Comment by GeorgeEarslight** [comment]
> i do believe that they changed the behavior to unload at the opening of the bunker rather than the back when the level and shovel mode was developed.

This

**Comment by Bubib5** [comment]
I tried a reversing course for Marwell manor, to dump grass into the clamp on the main farm, i get the tip trigger reached while in front of the clamp, then when it goes reversing in it never dumps, and just goes on, i cant get it to dump at all, no matter how i set up the course..

**Comment by olavinto** [comment]
> 
> 
> > i do believe that they changed the behavior to unload at the opening of the bunker rather than the back when the level and shovel mode was developed.
> 
> This
This leads to large trailers being unusable because the whole trailer can't be tipped to one position and then manual movement is required. The Fendt forage wagon for example is useless with Courseplay because it's max capacity is much more than what can be tipped into a single pile at once.

**Comment by ThomasGaertner** [comment]
Is this still an issue? Sorry i missed this Thread

**Comment by Ragworm** [comment]
Have Giants changed the angle of the heaps of chaff because i think the tipped chaff use to lift the trailor

**Comment by Elite82pt** [comment]
yes this is still a issue for me...same happens
