### ISSUE TITLE
mode2, tipper dont unload

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#3188]
Hey guys
I have the problem that my mode2 driver doesnt unload in the Farmsilo.
Map Felsbrunn, standart large silo from start with builldings,
Drive in from NorthWest, drive away to east.
In normal sellingpoints harvour,... in mode1 there are no such problems.
Traktor is the Deutz series9 and the taw30 tipper.
Drive in is a little tricky, s-drive before unloading.
Cp6, v 0100054
I testet same situation in ls17 with cp5 and there it works.
Lg
Andreas

**Comment by sootysax** [comment]
wheres your log

**Comment by ThomasGaertner** [comment]
#3140
