### ISSUE TITLE
Framerate drops from 60 to five a few minutes after setting up a combine unload course.

### ISSUE THREAD

**Issue by abcderic73** [Courseplay/courseplay#3191]
[log.txt](https://github.com/Courseplay/courseplay/files/2849045/log.txt)

Using just the combine is fine, but when I set a tractor up using combi mode, it's fine for a few minutes, but then after that the entire game runs at 5 fps.

Tools being used:

Rostselmash RSM 161
Draper Stream 900
Fendt Favorit 511C
Farmtech TDK 1600

**Comment by AtlAntA118** [comment]
Do you have the mod "Real Dirt Colour" installed? I had the same issue but i found out it was related to that mod. Worth a shot right?

**Comment by abcderic73** [comment]
I do not.

**Comment by abcderic73** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/2849603/log.txt)
https://youtu.be/4wPiF-EGHJk
@pvajko Here is an updated log and a screen recording of what's going on if it makes it easier for you.

**Comment by abcderic73** [comment]
@ThomasGaertner If you need to know, this doesn't happen when running two courses like having two tractors cultivate. Only happens on combi mode.

**Comment by galon007** [comment]
I have same issue with Combi Mod. I cant use it at all it does the same thing to me.
Its sad if combi mod is not working and freezing my computer and after couple of second its frozen and i have to alt-f4 :(.
But hey im glad im not the only one with this issue and maybe we can figure out whats going on.
I would love to provide some error log files but i have no idea how.
Is there any link for this how to do it ? .

**Comment by ThomasGaertner** [comment]
#3311
