### ISSUE TITLE
Driver get stuck before crossing railroad - no train. 

### ISSUE THREAD

**Issue by tjBerlin** [Courseplay/courseplay#3193]
Using cp .00057, RAVENPORT, no mods. CASE and Aprion 3401

Made a course bga to shop just driving. CP driver stops at railroad: 

![bildschirmfoto 2019-02-10 um 17 18 18](https://user-images.githubusercontent.com/24283753/52536275-88fa7c80-2d58-11e9-8dd6-0adda8ddab1d.png)

Here the log: 
[log.txt](https://github.com/Courseplay/courseplay/files/2849100/log.txt)

And just in case, you need it: savegame and course, it should be course 0008: 

[savegame4.zip](https://github.com/Courseplay/courseplay/files/2849105/savegame4.zip)

[MapUS.zip](https://github.com/Courseplay/courseplay/files/2849106/MapUS.zip)

**Comment by pvajko** [comment]
Since I have no more time this weekend for fixing (let alone testing) CP, stopping on traffic collision is now disabled by default, message will still display. 

If you want to play with it, turning debug channel 3 on will enable stopping on traffic again, if you then bump into problems please open an issue.

**Comment by Messy71** [comment]
@alpha117 / @pvajko i think it reacts different when you have two combined courses
same for @Mannelig83 in issue #3196

**Comment by tjBerlin** [comment]
:) I will try! But many, many thanks for the great work on CP! The FS won't be as cool as it is without it! Greetings from Germany!

**Comment by ThomasGaertner** [comment]
try again with v00062 or higher and report

**Comment by tjBerlin** [comment]
Sorry, did not work. 

![bildschirmfoto 2019-02-11 um 23 25 39](https://user-images.githubusercontent.com/24283753/52597908-83825c80-2e54-11e9-9158-d9e1e3404d8d.png)

[log.txt](https://github.com/Courseplay/courseplay/files/2853311/log.txt)

**Comment by ThomasGaertner** [comment]
@tjBerlin : can you send me your courses ? I could not replicate it

**Comment by tjBerlin** [comment]
Yes, of course. 

It is course "bga..händler", should be 0008. Same issue happens with course "händler..bga" (0001). 

[MapUS.zip](https://github.com/Courseplay/courseplay/files/2863606/MapUS.zip)

**Comment by ThomasGaertner** [comment]
try again with  v.75 or higher and report

**Comment by iljarogoff** [comment]
Still having this issue, updated right now on 06.01.00075
But only with my CaseIH 1455, my Deutz 7250 and my MAN Truck cross the railroad without problem, even did before update.

**Comment by tjBerlin** [comment]
It is working perfectly! Thank you!
