### ISSUE TITLE
LUA Call Stack with V.57

### ISSUE THREAD

**Issue by Mannelig83** [Courseplay/courseplay#3194]
Hello,
newest Version gives a LUA Error.
I Dont know whats up but if i dont activate CP the LUA Error disapears.

Log:
https://pastebin.com/vWbtP0uL

(see it at the End of the LOG file.)

Greets
Markus

**Comment by PromGames** [comment]
Maybe you can try with no mods just the cp and standard map. Otherwise, the map you are playing has some errors. It seems related to washing mod? Is looking for a shader and is not related to cp as far as I can see

**Comment by Mannelig83** [comment]
Thanks for that hint but the Error disapears without CP.
So for testing i started it just with CP.

I dont have that error Always but i did wanna post the log... Maybe i can narrow it down a bit more

**Comment by PromGames** [comment]
Well, it is normal that it appears with CP because CP is making a lot of checks of triggers, etc.. If the map or the mod is not setup correctly, errors appears in CP at the initial start check.

**Comment by josef19801** [comment]
With me the same in the log. But only if I attach some devices.

**Comment by Nielsen362** [comment]
I have the same, but when i use older version 6.01.00034 it is gone, the latest i have tried is 6.01.00063

**Comment by Mannelig83** [comment]
im trying to get in touch with mod author.
if i get any updates ill post them here

**Comment by ThomasGaertner** [comment]
@Mannelig83 : can we close here ?

**Comment by Nielsen362** [comment]
Yes you can, it is not a courseplay problem but mod issue, I have fixed mine yesterday.
Nielsen

**Comment by Mannelig83** [comment]
im sorry for not came back with my actual Research.
Actually i dont think it is courseplay too but i cant solve mine cause i found that Problem even with stock vehicles.

Im trying to get in touch with Giants but had no luck so far.
So Maybe gets never a fix but im not even sure if it is a Problem.

So. Thanks for your time and awsome work.

Greets
Markus
