### ISSUE TITLE
Helfer reduziert Geschwindigkeit

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#3198]
Helper repeatedly reduces the speed of 10 km / h to 1-2 km / h, why is that?
I have to adjust the speed again and again

**Comment by pvajko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Messy71** [comment]
**not enough information**
Post a picture with : 

- the course

- Speed limits menu

- repair state of header / implement
_Try to explain it a lil' better._

**Comment by ThomasGaertner** [comment]
Any news ? Is it still valid?
