### ISSUE TITLE
Courseplay FS 19

### ISSUE THREAD

**Issue by gunaopilas** [Courseplay/courseplay#3201]
When I use the course to do a job for me, whether to sow or to fertilize, it does everything right, except that the bar that shows the amount of (seeds or fertilizer) does not go down is always in the amount that I put

**Comment by sootysax** [comment]
not a courseplay issue : you are having the helper buy fertilizer and seeds - change the setting in the preferences

**Comment by gunaopilas** [comment]
Thanks for the tip, I'll try
