### ISSUE TITLE
Not unloading at dropped unload point

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3202]
I want to unload at the dropped unload point in front of the conveyor.   My tipper is set to tip left and I marked the unload point where I wanted it, but the vehicle just rolls right past it..

I also tried backing into the unload point, but it also just pulls out without dumping.

I am in Mode 1, with the load point / starting point at the other conveyor belt at the farm

https://gist.github.com/sootysax/538b58cfed44fa45d0fefc8f1bde9be5

![fsscreen_2019_02_10_21_38_49](https://user-images.githubusercontent.com/6591048/52544151-e99bb080-2d7c-11e9-89a6-48492039e457.png)

**Comment by sootysax** [comment]
Backing in:

https://gist.github.com/sootysax/0de5037249bba1d629e7577d122aa94f

![fsscreen_2019_02_10_22_00_23](https://user-images.githubusercontent.com/6591048/52544566-82333000-2d7f-11e9-9306-fa3de038a5b2.png)
![fsscreen_2019_02_10_22_00_29](https://user-images.githubusercontent.com/6591048/52544570-84958a00-2d7f-11e9-979c-8cdb2714eff6.png)

**Comment by sootysax** [comment]
While I didn't realize there was a tip point for silage to unload from trailers, so I really don't need to tip onto the conveyor belt, it still is not working at the dropped unload point.

Consequently, the tractor rolls right through the silage tip point as well, but that may be a duplicate of another issue.

**Comment by GeorgeEarslight** [comment]
@sootysax I'm not sure Mode1 ever worked with unloading points on previous versions. At least it's not documented in the manual, or "unloading trigger" actually means map trigger, not unloading point.

**Comment by ThomasGaertner** [comment]
try v100 or higher and report

**Comment by sootysax** [comment]
He stops and dumps, but its about 8 waypoints before it reaches the unload waypoint.

It says 'Tip Trigger reached' before it dumps on that spot..  and I don't know if its because of the unload point at the silage hopper there..  but if I remove the unload waypoint from the same course, it will not unload at all.

![fsscreen_2019_02_28_20_01_16](https://user-images.githubusercontent.com/6591048/53609240-f9483100-3b93-11e9-804f-bd9e2223f606.png)


https://gist.github.com/sootysax/14a197894d18b30fd83d852f73fcdc55

**Comment by sootysax** [comment]
Ultimately, what I'm trying to do, is deliver silage to the BGA, drive through the sell trigger and unload if there is room, and if not, dump on the unload waypoint where the conveyor will unload it into the sellpoint..   In this case, it senses the tip trigger (the sellpoint is empty), uncovers the load, but never dumps..   then rolls past the unload waypoint, still with covers off, but never unloads there either

https://gist.github.com/sootysax/0f1469d485c3ccd8dc7c79f7a66163ad

![fsscreen_2019_02_28_20_15_52](https://user-images.githubusercontent.com/6591048/53609646-e0d91600-3b95-11e9-9af0-ac39165a1f13.png)

![fsscreen_2019_02_28_20_16_03](https://user-images.githubusercontent.com/6591048/53609650-e46c9d00-3b95-11e9-8ae9-5cf3a7e634ed.png)

**Comment by Innallas** [comment]
He drop just in front of the trigger :D no problem here lol, in fact it's your path who is wrong xD you need to unload where it's shown , it is the trigger position. And if you come closer of the strip marks in  yellow i bet he will unload into, in bunkersilos he drop on the ground so it will be where your route bring him in front of the trigger.

**Comment by sootysax** [comment]
> He drop just in front of the trigger :D no problem here lol, in fact it's your path who is wrong xD you need to unload where it's shown , it is the trigger position. And if you come closer of the strip marks in yellow i bet he will unload into, in bunkersilos he drop on the ground so it will be where your route bring him in front of the trigger. Well i think its like that, in code it's this.
> 
> Just move your belt to be in same place of the unload and it should work (50% of my problems comes from a bad route created, have to remake or use shifts in case of different models used)

My path is not wrong..  I want it to dump where the unload icon is placed, not 8 waypoints away from it.

**Comment by Innallas** [comment]
Err in fact i used theses tippers HDK 302 & the other one, it look like that if you put the unload side on SIDES it really stop to work nicely but i don't know why , if you put the drop on behind it will work normally.

**Comment by ThomasGaertner** [comment]
@sootysax it's Marwell Manor right? can you give me the save and the courses ?

**Comment by sootysax** [comment]
@ThomasGaertner I got it to work by backing into the unload point without getting anywhere near it on the approach.  I think passing too close to it on the approach confused CP and made it dump prematurely.   So anyway, I'm able to unload onto the conveyor belt which feeds the BGA sellpoint.   

I still can't unload directly into the BGA sellpoint either backing in, driving through, or dropping an unload point directly on the sell trigger (it trys to dump, but nothing actually comes out of the trailer, and doesnt actually go into the BGA bin).  But that may be a separate issue (I don't think you were able to unload directly from a tipper into the BGA bin in FS17, only with a shovel).

I will close here.
