### ISSUE TITLE
beacon Lights (on the Street)  not working #58 and #60

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#3204]
With the good old farm to shop course CP does not switch on the vehicle beacon. Tried with all vehicle types

Thanks

**Comment by alpha117** [comment]
#70 beacons, perfect...great work 
Thanks
also some new course helper functions_......are these internal or user controlled?

**Comment by pvajko** [comment]
Internal. Also there are no beacons yet for unload/refill courses.

**Comment by alpha117** [comment]
cool, no problems
