### ISSUE TITLE
Courseplay FS 19

### ISSUE THREAD

**Issue by gunaopilas** [Courseplay/courseplay#3207]
The AI ​​driver you will be looking for -> harvesters -> unloads.
When you expect the filler to reach the level

Block and make a strange noise

**Comment by Symbob** [comment]
I think this is the same issue I have noticed.  When a tipper is waiting for the fill level of a harvester to be reached the tractor's engine is turned off, but then makes a strange clicking noise.

**Comment by gunaopilas** [comment]
Yes, it's exactly this problem that I have

Do you know of any solutions?

**Comment by ThomasGaertner** [comment]
#3205

**Comment by gunaopilas** [comment]
Good night people
I bring good news, tried a new way and until now is working

The solution is to go in the settings and turn off the "auto power on"
