### ISSUE TITLE
Unable to Save at all!

### ISSUE THREAD

**Issue by Jagsta2121** [Courseplay/courseplay#3209]
i have been unable to use courseplay with my mods. i get errors and have to quit the game and it deletes my save.  [LOG HERE](https://pastebin.com/raw/Yq27iqMR) i can save without mods.

**Comment by ThomasGaertner** [comment]
please try it again with just cp in it without other faulty mods and report
Thanks

**Comment by sootysax** [comment]
you should only ever have one map in your mods folder at a time

**Comment by FATTower19** [comment]
I had the same situation happen to me; I personally found the problem to be the FS19_CM_8R_Series (Bummer cause I liked that tractor).  The save game worked in previous versions with this mod in it but now will not.  I also did the beta update test for 1.3.   Thanks for all the hard work you guys are doing.
