### ISSUE TITLE
Road Traffic Accidents at Junctions with AI #63/#61

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#3210]
When CP comes to a road junction it just keeps going and will drive straight into the AI car that happens to be passing the junction at the time. This is a new issue or one that has comeback, in previous versions you got a warning message (bottom left of screen) CP would stop at junction until AI vehicle had passed by. Once on road no issues at all, just at junctions.
Don't think this issue was in #57/58
Great work so far.

**Comment by ThomasGaertner** [comment]
test with v00064 or higher and report ....

**Comment by alpha117** [comment]
will do...standby

**Comment by alpha117** [comment]
OK, its better, BUT still 'clips the AI vehicle at a junction, so its now not a 'full collision' and a 'reset'
Think it just wants a little more of a 'tweak' then it will be OK.  Before it stop at the junction and waited until the AI vehicle had passed, now #64 it still does not stop and it looks like CP see the AI right at the last moment and take evasive action. Hope this makes sense.

**Comment by alpha117** [comment]
This issue is fixed in #64, my last comment was due to incorrect auto throttle setting

Many thanks
