### ISSUE TITLE
Screen Message Change when Harvester is unloading..if possible?

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#3211]
When Harvester is ready to unload and CP triggers the tractor/trailer to come alongside to unload, whilst unloading the screen message you see(bottom left) is 'Harvester(#vehicle) is slipping', which it is not, as it just stopped to unload into trailer. This only happens if the Harvester is in the middle of a lane change(turning), when CP triggers the trailer. 
Would it be possible to either:
a. Not trigger calling the trailer until the harvester has completed its turn
b. Change screen message to perhaps something like 'Harvester(#vehicle) unloading

Many Thanks

**Comment by ThomasGaertner** [comment]
#3048
