### ISSUE TITLE
Not unload at Any sellpoint triggers 

### ISSUE THREAD

**Issue by bibifr** [Courseplay/courseplay#3213]
Hello dear, 

Im using  since yesterday Flustall XXL V2 Map v2.0.0.4 And i noticed this morning while trying to Sell at a sell point, the Game do not reconise the SellPoint! 
Im using courseplay 0063 Mode 2 

Using Debug 1-2-19 The only Thing i notice it's the Course running like any other road whitout seeing the Trigger

Thanks you for your works!

**Comment by Chris2996** [comment]
Might be a mod conflict. Does the seel trigger work when you try to unload manually?

**Comment by bibifr** [comment]
Hello chris, yes That works when i do it manualy ! it's just whit courseplay

**Comment by The-Terraformer** [comment]
This may be map specific as i was having the same issues with any sellpoint or placed silo. Works fine on other maps.

**Comment by bibifr** [comment]
It's same whit mode 3 They didn't sell it so it's probably a map issue :(

**Comment by sootysax** [comment]
Where is your log?

**Comment by Symbob** [comment]
Not sure if this is the same issue as you're having but from what I've seen CP attempts to stop at triggers too late, and if the trigger is small it will drive straight through it without emptying.  To work around this until it is fixed I've found that if you reduce your turn speed (this is the speed CP drives at when a trigger is detected) to a lower speed it gives CP a chance to start emptying before it leaves the trigger.   Some I've had to reduce to 6kph or even less.  Not sure if this will help with your problem.

**Comment by bibifr** [comment]
It's not related to this issue! Courseplay didn't Stop or not reconise the triggers it's just like a simply road nothing else.

@sootysax  log are not neccessary since he didn't show any error inside !

**Comment by sootysax** [comment]
https://courseplay.github.io/courseplay/en/faq/index.html

**Comment by sootysax** [comment]
Duplicate #3177

**Comment by bibifr** [comment]
No it's related to this map only ! i have no issue on 8 other map except this one! 
So seem to be just mod issue! 

Closed
