### ISSUE TITLE
Refill Course won´t work (wrong cover)

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/courseplay#3214]
Hello!
With patch beta 1.3.0GIants changed the covers of Horsch Maestro because it was wrong before. Big Cover is for fertilizer (was for seed in 1.2.0) and small for seeds (was for fertilizer in 1.2.0) On Refill COurses the helper opens the wrong cover and is not able to refill, because the triggers are wrong.

**Comment by sootysax** [comment]
#3130

**Comment by StefanBraun2001** [comment]
I know, but it don´t work, because the helper opens wrong cover. They changed it with the 1.3.0 Beta, now the big cover is for fertilizier, not for seeds, the small cover is for seeds. If you want to refill seeds the helper opens the big cover

**Comment by sootysax** [comment]
the reference is for the devs - who switched it around for the referenced issue..  now that giants fixed the implement, it needs to be switched back @ThomasGaertner

**Comment by ThomasGaertner** [comment]
test with 71 or higher and report...

**Comment by StefanBraun2001** [comment]
It works fine now, helper opens the correct cover now.
