### ISSUE TITLE
Mode 6 : Loading wagon does not unload at hayloft

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3215]
Unloading route connected to fieldwork route..   rolls through unload trigger on hayloft..  tried with pictured ModdingWelt.com hayloft as well as stock GIANTS hayloft..  same issue.

LOG:
https://gist.github.com/sootysax/755706b299642c596fb70dae3993ee26

SAVEGAME/COURSES:
https://drive.google.com/open?id=1a6KvUeH9beU6m3dU6lehoc7I7X9sybY2

HAYLOFT:
https://www.modding-welt.com/mods/file/2186-mw-platzierbarer-hof/

![fsscreen_2019_02_12_14_36_55](https://user-images.githubusercontent.com/6591048/52663203-17dfd400-2ed4-11e9-828c-5b82cc14f285.png)

![fsscreen_2019_02_12_14_37_02](https://user-images.githubusercontent.com/6591048/52663223-2332ff80-2ed4-11e9-953d-a85a488f5a0d.png)

**Comment by hoefti10** [comment]
same Problem here ,with different combines.

**Comment by sootysax** [comment]
update:  I attempted the approach from the other direction and it worked...  it seems that which direction you come at a trigger depends on if its gonna work or not.   Not sure if this is something you want to look into or not.

**Comment by valdimellen** [comment]
i changed the hight of the trigger on the vanila hayloft to make it work.

**Comment by limoman39** [comment]
Try slowing the tractor down or putting a pause point just before the trigger.  Worked for me.
