### ISSUE TITLE
Driving Speed on Transfer courses not being used by CP #64

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#3216]
Just noticed this issue. Using my 'Farm to Shop' recording as a test. CP sets auto throttle to 'on' as soon as you select drive now. It will drive the course to whatever the speed is set in the auto throttle. It does not use the CP options at all(Automatic, Max speed)

Before starting CP I set the auto throttle to 10KPH and CP drove the whole course from farm to shop at 10kph. If I change the auto throttle during the course then CP will adjust to that speed.

**Comment by sootysax** [comment]
duplicate #3067

**Comment by pvajko** [comment]
Thanks @sootysax

**Comment by alpha117** [comment]
yep, the issue was not setting auto throttle to max before starting course.  all good now, also fixes my other issue(AI at junctions)
many thanks all
