### ISSUE TITLE
Request: Allow user to disable timeCounter

### ISSUE THREAD

**Issue by The-Terraformer** [Courseplay/courseplay#3217]
Ever since the inclusion of the timecounter the mod destroys my FPS. I do not have the fastest PC but it was handling CP happily until the inclusion of this. Not sure if it the barrage of lua calls that it uses or some other 'issue'. The option to disable would be appreciated though.

4x map runs 50-60 fps with no issues. Each vehicle added by CP control reduces 15-20 fps.

Thank you.

**Comment by pvajko** [comment]
How many waypoints do you have in those courses?

**Comment by pvajko** [comment]
Did not think this is going to be a performance issue, anyway, this should be much better.

**Comment by The-Terraformer** [comment]
> How many waypoints do you have in those courses?

300ish. Large fields. Cleared out the log by mistake. 
Will check the new version. TY

**Comment by MoslessNeo** [comment]
The CP is not responsible for the drop in FPS. The collision engine itself may be the cause.
Even when using the "H" the FPS suffer when the number of workers is greater than 5 simultaneously.
If you join with a fair amount of parked vehicles and ride with them, the drop in FPS will be drastic.
