### ISSUE TITLE
Question Only

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#3220]
Morning all,

My issue, but how do you get CP courses to be parallel to the field side, mine always seem to be slightly at an angle.  I must be missing setting a setting somewhere

Thanks

![image](https://user-images.githubusercontent.com/30005040/52696226-68077680-2f66-11e9-83ff-d8ee791a0b9a.png)

**Comment by game455** [comment]
try with more headland to get rows out of corners

**Comment by alpha117** [comment]
thanks, thought I might have missed setting an option in CP

**Comment by AtlAntA118** [comment]
When creating course make sure to set "longest edge"

**Comment by alpha117** [comment]
will do

**Comment by Chris2996** [comment]
Got his answer. Can be closed.

**Comment by alpha117** [comment]
closed

**Comment by pvajko** [comment]
@Chris2996 yes sir.

But let me explain that the reason those are slightly at an angle is that the course generator tires to find the best course with the minimum number of up/down rows and minimum driving on the headland.

In case of this field you'll probably end up with more up/down rows with 'longest edge' setting.
