### ISSUE TITLE
Error: Running Lua method 'update'

### ISSUE THREAD

**Issue by blankmaster0** [Courseplay/courseplay#3221]
I tried to see if i could find any issues like this but couldn't find any. I get this error with no mods and on stock fresh map. When I pull up the Courseplay menu and set up the course when I run it it does nothing and if I try to get out of the tractor (or do anything other than sit there) it crashes the game and I have to force close.

Thank you for your time!
Blank

log:
https://pastebin.com/RUcCs3Qv

**Comment by pvajko** [comment]
You are running 6.01.00065, try with 6.01.00066 or later.

This problem has been fixed by 1c926e6e1e6390b7ead769d6eac0b3bfe67c784c. The error was introduced by 229322b00717a4c75f8425923ec4ed948e2142b5 which did not increase the version number.

**Comment by RayzerSharpe** [comment]
I may have some info on this. See the attached log file and i'm using 6.01.00069. 

Basically it happened to me too but i managed to get to save the game which seemed to reset it and the game went back to normal. I immediately turned on the debug channel (sry for so many) and then it happened again. It seems to be on the find course. I have 3 separate courses running when it happened. hopefully this is of some help 
[log.txt](https://github.com/Courseplay/courseplay/files/2862539/log.txt)

**Comment by blankmaster0** [comment]
I updated and it has been resolved in the update. Thank you very much for the speedy response and if i have issues in the future i will make sure to update before submitting tickets
