### ISSUE TITLE
2019-02-13 14:07 Error: Running LUA method 'update'.

### ISSUE THREAD

**Issue by LindavK1972** [Courseplay/courseplay#3222]
I have a LUA update error i can't seem to get rid of on any map i try. I have the latest version of CP installed.

The error will freeze up the game and crashes it.

Log included.
[log.txt](https://github.com/Courseplay/courseplay/files/2860474/log.txt)

**Comment by ThomasGaertner** [comment]
please clean your log with removing faulty mods and try again....

**Comment by LindavK1972** [comment]
I found the cullprit...Manual Attaching...

**Comment by sootysax** [comment]
just so you know... the Manual Attaching for FS19 is a hack job conversion.  Wopster has nothing to do with that.  He is still working on porting over the real Manual Attach for FS19

**Comment by LindavK1972** [comment]
It felt like that... Half of the attachers don't even work...so it's off...and i cleaned my mods...CP is working great!!!
