### ISSUE TITLE
Question: difference between the course recording

### ISSUE THREAD

**Issue by zed636** [Courseplay/courseplay#3223]
Sorry for the question, perhaps trivial, but there is some difference between record a connecting path between the field and the silos or bunker or point of sale in mode 2/5/6? 
explain why my question: from fs15 I register all the asphalt roads of the map in mode 5 with the various crossing points near the intersections or near the fields, so I can use only one route equal for all vehicles that travel on the same road, adding only the part that connects the road to the field or to the point of arrival;
I have just seen the video of Sam (https://www.youtube.com/watch?v=CQPRDzHlRnI&t=19s) which uses for example the mode 6 to record the path from the field to the barn.  Is it necessary to use this trick or does it work the same?
Not having found answers on the guide or in other questions I would like to have more info from you developers.
Thanks Marco

**Comment by pops64** [comment]
When you record a course the mode your in has no impact on anything. Only when CP is driving driving does the mode your in impact what CP does

**Comment by zed636** [comment]
it was what I supposed, but I wanted a confirmation from you. Thanks for the quick response
