### ISSUE TITLE
Minor Bug when " Stop harvester when unloading" selected

### ISSUE THREAD

**Issue by Hubcap-1** [Courseplay/courseplay#3226]
It is a minor bug when you have stop harvester when unloading selected. To fix the harvester should be stopped when the " Pipe" open is initiated ( triggered). This will allow the tractor the chance to come to a stop in time to be in position for the off loading. As it is I pull along side....put myself in position and not until the feed belt from the harvester starts ( potato harvester)....does the harvester stop ( suddenly)....and the loading trailer shoots past it...and you have to back up if the harvester hasn't already started closing the discharge node and begun moving again

**Comment by pvaiko** [comment]
Whatever this is, should now be fixed by f033a940238d01b561a4d2746576c802e0bc6a81
