### ISSUE TITLE
FS19 Courseplay 6.01.00069

### ISSUE THREAD

**Issue by Azorees** [Courseplay/courseplay#3227]
![untitled-1](https://user-images.githubusercontent.com/47617591/52757851-11e61200-2ffe-11e9-9604-39562f0dd96e.jpg)
1st of all let me thankyou for your great work that you have done and are doing.

I have only just started using courseplay so I am a total noob with it and only use the basics for now but even with the basic makes the game more fun.

Ok now to the issue, when I 1st downloaded and installed courseplay it was version 6.01.00054 ( I think, I know it was 5x  ) the issue I have with the previous version to 6.01.00069 is that for some reason after 5 - 15 mins of game play the game is not as smooth and suffers with what I would call a micro stutter like its missing a frame or 2.

On version 6.01.0005x it ran as smooth as butter with everything maxxed out, but now it seems like my pc can handle it and its as if my gfx are turned up 1 notch too high, I even tried the video settings at very low and it still did the same.

I have not installed any more mods or changed any settings when I updated to the latest version.
Has anyone else reported this issue or are you aware of it or is it something I have done ( maybe one of my mods conflicting that wasn't conflicting before ).

Also I have noticed that the 3rd icon ( Bottom icons starting from the left ) and the last 4 icons stay greyed out for me,
I don't know what the 3rd icon is for but I think the last 2 are for the leveller, are these going to be fixed or is there something i'm doing wrong to use these options. I uploaded a picture which is placed at the top to show you which icons i mean.

Thanks again and keep up the great work your doing.

**Comment by Azorees** [comment]
I mentioned in my comment about the frame drop / micro stutter , after I posted this I did some digging around just to see if any one else had the same issue.

I found 1 comment stating he dropped from 60fps to around 5fps ( mine wasn't that bad I would say probably dropped to around 25fps) which had a reply from a user who mentioned Real Dirt Colour Mod, I have this mod installed which is version 1.0.0.5 so I thought I would disable the mod and give that a try, removing the real Dirt Colour mod seem to fix the issue.

I find it strange how 6.01.0005x worked with no FPS drops with the same mod can you look into this issue because I like my lime trailer looking like its dirty as hell and lime dust all over it, just gives a more real feel to the game.

Thanks again.

**Comment by Gurrah71** [comment]
Yeah that real dirt mod is giving me issues also, think its conflicting with some other mods i was hoping they fixed that on the last update of it but still persist so i have to disable it.
But have not noticed any difference if i got courseplay on or off with it tho.

**Comment by BostonJohnny1226** [comment]
I noticed with version 63 of CP, in my log I would get a continuous run of "....distance to go" where it would continue until the worker completed it's task.
As for the stutter, I'm using the dirt mod too. I'll have to check it out.

**Comment by Tensuko** [comment]
The greyed Buttons we all got becouse not all Modes are activated for Version 6.
1st the Basic Modes should work well and Error free, before start with the other Modes.

**Comment by Azorees** [comment]
@Gurrah71 I noticed that it only did it while courseplay was active and it taken about 5 - 10 mins for my vehicles to get full of dirt so I figured it was only when they got dirty is when the problem started.

I disabled Real Dirt Colour and its not done it since, I don't know if it will conflict with any other mods out there but the ones I have installed ( a lot ) only Real Dirt Colour conflicted, but it didn't do it in CP 6.01.0005x only when I tried 000.6x.

**Comment by Azorees** [comment]
on another note I love the ( I think its a new addition but not sure ) stuck in traffic and your vehicle stops and waits until theres a free space for it to move.

I think the distance is set a little to high and I think could do with being shorter by a notch or 2.
Small and medium vehicles work flawless with it but I have a run where some of my larger vehicles need to refill  and I pass close to a shed with other vehicles in it when I say close I mean roughly 5 -10 meters, so my larger vehicles stop and throw up the " stuck in traffic " message.

is it possible to add an option in one of the tabs so you could fine tweak the traffic distance yourself, I think this would be a more helpful way for users as the default setting would be fine in most cases but when you have to pass close to a shed with vehicles in it then it can cause a headache meaning you have to find another route around it which is sometimes not possible.

I know there is a debug in the panel for the traffic but to be honest I don't want to disable it as I thin k its a great feature but could do with a little tweaking.

**Comment by pvaiko** [comment]
@Azorees you opened another issue for the traffic problem which seems to be specific to that sprayer, the traffic collision boxes remain in the unfolded size on the unload refill course. Closing this one.
