### ISSUE TITLE
Tip Triggers - Not working, Estancia Lapacho

### ISSUE THREAD

**Issue by djinsomnia90** [Courseplay/courseplay#3229]
I recently downloaded courseplay, The tractor - trailer combi, will drive the course collect from harvestor but will not unload in a train silo. Gets notification tip trigger reached, opens doors and then drives off with it open

**Comment by djinsomnia90** [comment]
Tried a new map with similar results, Tractor pulls up stops on trigger does the animations of unloading but doesn't unload the cargo from trailer.

**Comment by sootysax** [comment]
you'll get no help if you dont provide a log/screenshots/savegame

**Comment by sootysax** [comment]
If you want to help the developers troubleshoot this mod and help get it to it's release, you need to give them the information they need.  Otherwise, you just frustrate them by making them ask for more info.

https://github.com/Courseplay/courseplay/wiki

**Comment by djinsomnia90** [comment]
[savegame4.zip](https://github.com/Courseplay/courseplay/files/2866705/savegame4.zip)
The course is called 19/20 to tip.

**Comment by sootysax** [comment]
are you using CP v. 6.01.000071?

**Comment by djinsomnia90** [comment]
CP v. 6.01.000069 is version am using. 

[log.txt](https://github.com/Courseplay/courseplay/files/2866712/log.txt)

I could only download that version yesterday

**Comment by djinsomnia90** [comment]
Ok i am going to close this now because the newest version works, i didn't realize there was a new version available. Sorry for wasting everyone's time
