### ISSUE TITLE
CP does not recognise when implement is empty

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#3230]
Have course + refill loaded (Lime), implement is empty, but CP keeps going

![image](https://user-images.githubusercontent.com/30005040/52802019-f703b400-3076-11e9-862e-9d3985be6350.png)
[log.zip](https://github.com/Courseplay/courseplay/files/2865959/log.zip)

**Comment by alpha117** [comment]
User error, wrong 'Drive mode' selected....what a 'numphty', sorry about that guys!!

**Comment by Catfisherman1978** [comment]
v6.01.00103 dev
CP still doesn't recognize that the tool is empty. I have also noticed that it does not recognize the working width of the lime tool. Thanks
