### ISSUE TITLE
lua error when combine request driver mode2.lua (349) (356)

### ISSUE THREAD

**Issue by Ruudjhuu** [Courseplay/courseplay#3231]
When i manualy request for a driver when coursplay is running in a combine, The game gets stuck and the following error is given:

Warning (script): 'worldToLocal': Argument 1 has wrong type. Expected: Int. Actual: Bool

[log file](https://gist.github.com/Ruudjhuu/c1620519650dfc05fffb3cca4104f050)
version 6.01.00071 

Edit:
Also happens when it is not manualy requested.

**Comment by pvajko** [comment]
Possibly duplicate of #3191

**Comment by ThomasGaertner** [comment]
#3311
