### ISSUE TITLE
Mod team cannot read english submissions

### ISSUE THREAD

**Issue by prjndigo** [Courseplay/courseplay#3234]
Inbox | x
-- | --

-------------------------------------------------------------------------------------------------------

There is NO forward/backwards along line of travel adjustment for the cutter position on combine harvesters as indicated by original issue report.  It does not exist in any button in any way.   This results in all combine harvesters charging right into the crop.   This behavior occurred originally in FS17 courseplay and was *fixed* in FS17 courseplay.

**Comment by shasol** [comment]
This has to be the most unconstructive issue post on here, I have ever seen :( 👎

**Comment by pvajko** [comment]
@prjndigo I may be misunderstanding the title of this issue, can you explain in more detail what exactly are you trying to say with  "Mod team cannot read english submissions"?

**Comment by sootysax** [comment]
i think he miswrote "Poster cannot write a useful bug report"

**Comment by BostonJohnny1226** [comment]
The CP folks are THE last group of modders that I'd want to piss off. I won't play FS without CP.
I suggest you clarify whatever issue you might be having.

**Comment by ThomasGaertner** [comment]
I think he mentioned #3142 doing this in this way is a pure disgrace ...

**Comment by Azorees** [comment]
Mod team cannot read english submissions ? your comment has nothing to do with them reading English , its about harvesters.

I'm new to CP and to be honest I think they have done a great job so far, it makes the game more playable and less boring.

Ok yes there are some issues with the mod but at the end of the day its a mod and not a game, these people who make mods make them in their own time without getting paid.

Its a free addition to the game which imo think its a must have for any serious player it just adds so much more time for you to do other things while the bots take care of all the jobs you hate doing, have a bot plough a field and another harvest another field while you go and tend to the animals.

I think the authors deserve a little more respect for taking the time to create such a mod, bare in mind they can only add things or fix bugs when they have time to do it, they might be working at least 10 hours a day for all we know and only have a couple of hours to look at the mod.

As I said i'm new and played FS17 without CP, it was only when a friend mentioned it to me a couple of weeks ago that I decided to take a look at it , and tbh I would miss it if it disappeared as for now i'm used to using it and it would feel like half of the game is missing without it.

**Comment by GeorgeEarslight** [comment]
Please let's not turn this into FS-UK/OxygenDave scene.
@prjndigo You mistake a code repository issue tracker with a forum. Please clearly post an in-game mod issue following the guidelines.
@ThomasGaertner @pvajko let's close this and move on?

**Comment by prjndigo** [comment]
combine harvester's "cutting width" seems to be located either at the back
of the harvester or the "start mark" for entering a field is too close to
the actual cutter location and they are charging right past the first mark
of the field into the field to drop the cutter in and start at the second
mark unless you back them way up and sometimes they STILL skip the first
mark.  Manually setting to "nearest" instead of next resolves the issue

I was told by the person who "handled" the issue the first time that there
is a front-to-rear adjustment on the location of the tool/cutting position
and there is NOT.

**Comment by prjndigo** [comment]
the response from my prior ticket was to tell me there was a foreward/back
adjustment on tool position on combine harvesters.

which there is not

**Comment by pseikoNL** [comment]
If you just read the manual you had to know there is a tool offset setting for both horizontal and vertical offset. So RTFM, or go rant somewhere else.

http://courseplay.github.io/courseplay/en/manual/index.html#hud_drivingSettings
