### ISSUE TITLE
Game won't save.

### ISSUE THREAD

**Issue by duffstone** [Courseplay/courseplay#3235]
I think this has to do with the old issue [https://github.com/Courseplay/courseplay/issues/2930](2930), 

so what happens is this,  with only courseplay and my dump truck mod in the mod folder,  I can start a new game and save it just fine as long as I have NOT purchased the dump truck in question.  After I purchase the dump truck I get a save error and the game locks up.  

log:
https://pastebin.com/Qsd0nYBu

I had bypassed this issue in the early CP versions by adding a nifty bit of code (in the register.lua file) to bypass the error,  (detailed in issue 2930 above),  however,  CP has updated quite a bit since then,  and now the error has moved into the base.lua file,  which is different than before so my fix to bypass it doesn't work anymore.   

Is there anyway I could get one of you to look into why this happens so I can find a way around it?   I don't expect you to make it work with custom vehicle types at this time,  the previous issue was postponed for a reason,  but I'd sure like to find a way to bypass the issue so we can still use our custom vehicle types without CP.

Thanks guys!
-Duff

**Comment by sootysax** [comment]
use #2930 to link to other issues

**Comment by duffstone** [comment]
not sure how to link issues but thanks for the nod.    I think I found another work-around,   I trapped the "secondTime" variable in register.lua and stopped it from trying to register vehicles a second time.  Not sure why CP is trying to register vehicle types twice, but I covered that in 2930 I guess.   Anyway,  stopping the 2nd pass allows me to use the custom vehicle types until you guys get it figured out.

-Duff

**Comment by ThomasGaertner** [comment]
the second run is nessesary to register mod, which are loaded after courseplay has registered the vehicles, its not register twice, its register more....

**Comment by duffstone** [comment]
hmm...   Yeah, I don't mind sharing,  can I PM it too you,  or is there a secure way to share it?  it's a WIP,  that works,  I'm just not done with it, and TBH, I've not yet figured out who to give credits too for a good deal of the 3d mesh's...

**Comment by ThomasGaertner** [comment]
thanks, but its really WIP :-) try again if its ready Thanks
