### ISSUE TITLE
Kuhn SW4014 Mode6

### ISSUE THREAD

**Issue by GeorgeEarslight** [Courseplay/courseplay#3237]
Kuhn SW4014 picks up bales but does not wait to drop them after wrapping.
v00071 Marwell Farm F19. 

Edit: Will post logs later today (don't know which channels are useful for this, so I'll try some on my own).

**Comment by GeorgeEarslight** [comment]
New test game Felsbrunn F30 [log](https://gist.github.com/GeorgeEarslight/c7550b55ec2b85e20efe1e1d9dc7740d).

**Comment by Tensuko** [comment]
Test again with 159 and report.

**Comment by GeorgeEarslight** [comment]
Will test today or tomorrow.

**Comment by GeorgeEarslight** [comment]
Working as intended on v162. 
You can close this, please.
