### ISSUE TITLE
any bugs

### ISSUE THREAD

**Issue by SevenFifty1996** [Courseplay/courseplay#3238]
Hello. Unfortunately, my english is not that good. That's why I have to use a translator. If I use Coursepaly, and the truck or even the tractor stops, there are sound problems. When the driver is at the end of the field, the truck drives back too far and obstructs the thresher. When the Drescher has been refueled, which can happen in the middle of the field, the truck drives behind the Drescher and enters the Drescher, which can set backwards at the end of the field.

**Comment by pvajko** [comment]
I don't have time now but there are issues already for both of your problems so this is a duplicate. 

Also, in the future submit one problem only in one issue.
