### ISSUE TITLE
Driver stuck in traffic without traffic - Rubicon 9000

### ISSUE THREAD

**Issue by Azorees** [Courseplay/courseplay#3239]
As the title says, my driver will get stuck in traffic with more than one vehicle type.

I think the traffic scan radius is a little too high and could be turned down a touch.

I have a farm with the vehicle garage and filling silo's close together and when i go to refill fertiliser or seeds my driver will get stuck in traffic even though the route is clear.

i have uploaded a picture to show what its picking up in its scan which in the lawn mower if i remove the lawn mower vvehicles run that route perfect.

I think its a great feature but just a little too sensitive, i think making the scan radius 2 thirds of what it is would be perfect so that you can pass closer to vehicles while also giving them time to stop if one is in its path.

btw great job on this mod i love it :D 

![untitled-1](https://user-images.githubusercontent.com/47617591/52876681-d3f90300-314f-11e9-8028-b2ceb3d4558c.jpg)

**Comment by pvajko** [comment]
We should be removing all collision detector boxes when the vehicle is stopped. Try pressing F5 to see the collision boxes.

And as usual, post a full log with debug channels 3 and 14.

**Comment by Spatzekopp** [comment]
I have the exact same problem on my fertiliser refill route.
[log.txt](https://github.com/Courseplay/courseplay/files/2871554/log.txt)
![fsscreen_2019_02_16_03_53_56](https://user-images.githubusercontent.com/47681678/52893799-c5870780-31a0-11e9-8614-86c341caab48.png)

**Comment by ThomasGaertner** [comment]
@pvaiko : the system is ok, look at the shape of the triggers , they are huge. I will figure something out ...

**Comment by Martinnygaard** [comment]
I have the excact same problem - only with the Rubicon.

It gets "in traffic" at every 5 meters or so.

**Comment by Tensuko** [comment]
Nothing we can do here.
