### ISSUE TITLE
Not unloading at a silo trip trigger

### ISSUE THREAD

**Issue by Dutchest69** [Courseplay/courseplay#3240]
I made a course for unloading from the combines to a silo I placed and it recognizes the tip trigger but doesn't unload. I added a manual unload trigger over it but that just causes the trailer to drive ahead and unload on the ground
![farming sim bug](https://user-images.githubusercontent.com/47432351/52881613-3f2be080-3122-11e9-8083-8c4878aafb89.JPG)
![farming sim bug 2](https://user-images.githubusercontent.com/47432351/52881621-48b54880-3122-11e9-9bdf-e4a1ec7dae4b.JPG)
![farming sim bug 3](https://user-images.githubusercontent.com/47432351/52881627-4d79fc80-3122-11e9-89b1-009664c2046c.JPG)
[log.txt](https://github.com/Courseplay/courseplay/files/2870692/log.txt)

**Comment by squall39** [comment]
Ne pas remplir a 100% et passer sur le déclencheur à une vitesse entre 5 et 10 en attendant une mise à jour prochaine

**Comment by Messy71** [comment]
@Dutchest69 the french man is half right , the 100% has nothing to do with this problem , it’s the speed from the recording that you passed trough the sellpoint. 
@squall39 ça rien avoir là quantité c’est jusque là vitesse avec là qu’elle tu passes par la bas.

**Comment by squall39** [comment]
90% je vide il détecte le trigger 100% non

**Comment by sootysax** [comment]
@Messy71  "the 100% has nothing to do with this problem , it’s the speed from the recording that you passed trough the sellpoint."

you keep bringing up recorded speed in relation to loading and unloading triggers..   normal courseplay operation would take over the speed approaching triggers, and recorded speed should not matter.

**Comment by Dutchest69** [comment]
@sootysax This is what i was thinking because a unload point on a sell point will stop the wagon. Its just the mode for unloading an active combine and then trying to dump in a silo doesn't work

**Comment by Messy71** [comment]
@sootysax maybe you are right, but i don’t know how good/quick is courseplay at breaking before the triggers.  To give you an example i’ve recorded a course before 6.01.00072 from my silo field 8 (ravenport) to the barn at 35 kph ( for a smooth course ) it worked fine until ´´´72 but wit the trqfic detection it stops at the railroad. I’ve change it to max speed and the street speed to 55kph it brakes before the railroad but doesen’t fully stop and continues the course so i think it does have solething to do with the speed that you pass trough the sellpoint either recorded or changed max speed.

**Comment by adorhun** [comment]
still onthing on 76.
i even stopped on the unload point when i recorded the track.
just goes straight over.

**Comment by sootysax** [comment]
> still onthing on 76.
> i even stopped on the unload point when i recorded the track.
> just goes straight over.

This issue has not been addressed or assigned yet...

**Comment by Redline1969** [comment]
I have found the same issue using the unload point and what happens to me is the the trailer starts to unload but then drives right over the grates and keeps going very slowly. I then have to take back control, detach the trailer to get it to stop unloading (even though it is not actually dumping anything). If I do not take back control it just keeps driving extremely slowly looking like it is unloading indefinitely.

**Comment by Symbob** [comment]
When detecting a tip trigger I think CP drives through the trigger using the "Turn Speed".  Reducing the turn speed has solved this issue for me in most cases.

**Comment by Orgalit** [comment]
Same thing for me. Nothing helps, new cource, minimal speed. Hope for solving in future versions)

**Comment by Redline1969** [comment]
I tried setting the turn speed to 1 and it still happens. At this point I am forced to put a waypoint to have the tractor stop so I can manually unload. To me this is a critical bug.

**Comment by JMeinen69** [comment]
Same problem. Tried lowering speed, other trailers/trucks but without success . Looks like a bug. Now have to put a P in my route and manualy onload... Hoping it will be fixed soon. 
Otherwise, keep up your great work! Withoud CP FS is no game for me, it makes the game complete!

**Comment by ThomasGaertner** [comment]
can you give me the savegame and courses ?

**Comment by JMeinen69** [comment]
> can you give me the savegame and courses ?

i will when i have some time.

**Comment by JMeinen69** [comment]
> can you give me the savegame and courses ?

Done. Hope you can find the problem. Putted more info in mail.

**Comment by ThomasGaertner** [comment]
try with v.93 and report

**Comment by JMeinen69** [comment]
At this moment it works again! Great work!  @ThomasGaertner

**Comment by Manto82** [comment]
I have the same issue in .00094
Ravenport field 17 -> placed farmtrigger works
Field 9 and 11 dont work. The driver unloads a few meters behind the trigger on the ground.
Reducing the speed to 3mph didnt work
