### ISSUE TITLE
6.01.00072: trying to save a course kills courseplay and help panel

### ISSUE THREAD

**Issue by Iwan1803** [Courseplay/courseplay#3241]
I recorded a course and then i tried to save it. Then the panel of courseplay and also the help panel were closed. Then i switched to another tractor and tried to check if the save was done. Then also both panels disappeared.
After that i switched to the next tractor and could create a new course and then also after saving it the panel disappeared.
The only way to get them back for theses tractors is to restart the game.

Could this may an incompability with other mods?
Next restart i will disable all others.

*update*
Disabling all other mods doesn't solve the problem.

**Comment by Messy71** [comment]
you should post a log with debugg channels 7,18,19 ( my guessing ) maybe that will help the devs also try reseting the tractors to the store see if that restore’s the HUD by opening it with right click.

**Comment by Iwan1803** [comment]
Thx, i'll try to get that special log.
Only way to restart the HUD is to restart the game (or selling that tractor).

**Comment by Iwan1803** [comment]
after deleting all saved courses i could play ~3 hours without any problem
so maybe a corrupt file had caused this problems
