### ISSUE TITLE
Leaving small unworked patches at end of row when applying lime and fertilizers.

### ISSUE THREAD

**Issue by BolsaFamillia** [Courseplay/courseplay#3242]
Is it possible to correct this? The fertilizer sprayer leaves these faults at the end of the application lane.

![7815352b-c644-4b89-b98f-8beec289c573 png](https://user-images.githubusercontent.com/9952685/52890472-0add1200-316c-11e9-8bbd-bfe7a6401e06.jpg)

**Comment by Redline1969** [comment]
Not sure if this should be added to this, but I get the same thing with harvesters leaving small patches at the edge.

**Comment by cwattyeso** [comment]
Could be nice to have an option on seeders and fertilisers to seed/fertilise past edge of field, similar to how with Ploughs you have the option to enable "Plough past field edge". That would quickly and easily solve this issue.

**Comment by BolsaFamillia** [comment]
> Pode ser bom ter uma opção em fertilizantes e semeadoras de sementes/fecundar além da borda do campo, semelhante a como com arados, você tem a opção de habilitar "Plough além da borda do campo". Rapidamente e facilmente resolveria esse problema.

Excelent idea. Very good idea!

**Comment by BolsaFamillia** [comment]
> Could be nice to have an option on seeders and fertilisers to seed/fertilise past edge of field, similar to how with Ploughs you have the option to enable "Plough past field edge". That would quickly and easily solve this issue.

Excelent idea. Very good idea!

**Comment by Tensuko** [comment]
Fixed with V182.
Closed.
