### ISSUE TITLE
Manure, Slurry OR Digestate refill route - rolls past waiting point at conveyor belt/doesnt recognise slurry or digestate fill

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3243]
Manure refill route..  does not stop at waiting point..   Continue and drive now pop up approaching waypoint, and drive now stays on screen as vehicle rolls through waiting point

https://gist.github.com/sootysax/e56e44b30776e49adaa45bb9b9cc7c92

![fsscreen_2019_02_15_19_15_37](https://user-images.githubusercontent.com/6591048/52891070-7fa55180-3156-11e9-9038-a83b2ec6ca1c.png)

![fsscreen_2019_02_15_19_15_39](https://user-images.githubusercontent.com/6591048/52891041-410f9700-3156-11e9-83b2-1eb599e9c986.png)

**Comment by sootysax** [comment]
also ran the course trying to refill slurry tanker..  does not recognise fill trigger, backs in, and drives back out again.

https://gist.github.com/sootysax/53c424dbd8046f83138fb77a0461e04f

![fsscreen_2019_02_15_20_44_10](https://user-images.githubusercontent.com/6591048/52892694-ddd83180-3162-11e9-9b3e-12e026992bf5.png)
![fsscreen_2019_02_15_20_44_17](https://user-images.githubusercontent.com/6591048/52892696-dfa1f500-3162-11e9-80b8-5d8f316750d8.png)

**Comment by tuzlo** [comment]
I know this is of topic, where did you get that conveyor from?

**Comment by sootysax** [comment]
> I know this is of topic, where did you get that conveyor from?

It's stock GIANTS equipment

**Comment by sootysax** [comment]
Adding another log and screenshot trying to refill at the digestate fill trigger.  Same issue as other fertilizer triggers.   Rolls through trigger and doesnt access it.  I noticed that if I hit the R while CP vehicle is under the trigger, the menu comes up with Digestate as the only option.  

https://gist.github.com/sootysax/49051c3f52aa8dde0809db6ccfd773f5

**Comment by sootysax** [comment]
@ThomasGaertner Due to the very small coverage of manure and slurry and many refill trips are needed for any reasonable large field (and the 600,000L of digestate currently sitting at the BGA), I would love if you would prioritize this over mode 2&3

**Comment by sootysax** [comment]
did my issue get lost in the shuffle?

**Comment by Innallas** [comment]
Hello i got the same problem.
BUT i think i do know maybe the problem ! When we use "Load at Start" job he recognize ressources choices and load with, you see what i mean ?
But maybe this is not/bad implemented into "Seed & Fertilize" job ?? And if he have to choose between ressources (instead of having only 1 type of seed/fertilizer) then he fail to choose and keep going ?? 

To answer this i made a custom MoD with Stock vehicle just switched the ressource into tank (only liquidManure) i will try in the few hours i keep you update.

**Comment by Innallas** [comment]
IT WORK ! I updated the core code to add the "load places" from modules ingame (CoursePlay didn't knew there was load place in husbandries/ other placeables). I will try to modify the core code here but until there is a new version, here is a version who work :

http://modsfile.com/a2rgxzbymwh4/FS19_CoursePlay6_addedLoadPlaces.zip.html

I will modify code here , it is into the file i said

PS : i am a developper IRL ( have a license in computing :) )

**Comment by ThomasGaertner** [comment]
> did my issue get lost in the shuffle?

no, in real live :-)

**Comment by sootysax** [comment]
@Innallas I tried a refill route to the digestate trigger on Marwell Manor with the replaced triggers.lua, and it still didnt work

**Comment by Innallas** [comment]
Oh , shit yeah i saw the biogaz added with a modification about placeable silos, can you unload @ the biogaz ?? for loading i bet you can't , i'll edit to give you new trigger.lua

**Comment by sootysax** [comment]
refilling at digestate trigger is still not working..   its a refill route, so the trigger would need to be detected, since it does not load at the first waypoint.  I think it's a similar issue to #3180, in that when you hit R at the digestate a menu comes up and you need to hit enter to start loading.

**Comment by Innallas** [comment]
Yes i got same troubles with some loading stations but after putting well the waypoint & sometimes add a shift to the route or he wont load on it. I saw the biogaz trigger so now he is well loaded its sure, i will try today to go refill at biogaz. But yes i think there is a problem into the "getexactunloadorloadtrigger" function like that in CP. 
Because even at an unload point@my sheep pasture wasn't working, i had to remake the route, same for a milk-house with a truck who make laps for take & sell milk (i had to give him a shift like 1-2m at left)

**Comment by ThomasGaertner** [comment]
@Innallas : would you please make an pull request for the trigger thing? Which triggers are involved in your solution ?

**Comment by ThomasGaertner** [comment]
@sootysax : i assume, you want to use mode8 in your case, but it's not ready yet

**Comment by sootysax** [comment]
> @sootysax : i assume, you want to use mode8 in your case, but it's not ready yet

I just want the tractor to stop at the waiting point so I can frontloader manually.   Or refill from the slurry or digestate fill point

**Comment by Innallas** [comment]
Huh ? i was talking to you about the pipe of digestate in the biogaz who load a trailer or refill. Err for what you want it's propably because you have a silo near you so he goes in silo mode, switch the driving mode to try in "handleunloading" in toolManager to see ? But normally if you put a waypoint not too near of a silo it should work

**Comment by Innallas** [comment]
But @sootysax  For what you want to do you need a belt from manure to "road" (it create a "pipe" above the road) or the Manure Trading System in easy (which allow to fill Manure like any buying station, and you can sell & buy for same ratio ( like use it as storage :p )

**Comment by sootysax** [comment]
Perhaps I combined too many issues here..   but it's all the same thing really..  I'm trying to refill from either slurry pit, a manure pit (with a conveyor or a wait point for a shovel), or a digestate fill point.

**Comment by Innallas** [comment]
Mmmh weird, i really have to buy the biogaz on my map to try , but the Slurry refill at an husbandry so i don't see why it won't stop, did you try ?? You need to have a load trigger for the tractor to stop, with manure trading system i'm sure @80% it would work (its exactly same as slurry) but for the conveyor belt i'm not sure it work.

**Comment by Innallas** [comment]
Oh i found maybe something, in "settings.lua" > line 464 , add the condition "or vehicle.cp.mode == 4" in the function "getCanHaveWaitTime". It's not tested so maybe it can make trouble for other seeder/fert vehicle in mode 4. But not sure because for seeds & etc they come near a trigger.

**Comment by ThomasGaertner** [comment]
@sootysax :test the wait point stuff, the liquid manure stuff will be done soon....

**Comment by sootysax** [comment]
Manure refill route with the SP 14/17 spreader is working - stopping at the waitpoint, and getting refilled via conveyor belt at the cow manure pile.

**Comment by Innallas** [comment]
Sweet, but me i got a problem with recents Updates with liquid transports, now they just Do Not Stop at the unloading waypoint and the distance isn't calculated from tipper.prevTraillerDistance (also this one should be divided by 2 or they often miss the trigger). 
And workers are "forcing" the tipping of the tipper apparently now, i don't know where is it in the code but you should make a condition to don't force the tip_opening if they can unload (it's the case with liquid stuff so with just this it will be handled normally).

I'm trying with the official CP with little modification (it work) > but not with version here anymore now, which could be problematic to transport slurry & milk & etc.

Modif are just condition to drop on trigger (dont wait to be far) & reducing unload distance , all when tipper is in ctt.isAreaTrigger in function "unload_tipper" for unloads at objects (not bunker silo). ~line 1135.

**Comment by ThomasGaertner** [comment]
@sootysax : please test the refilling on the digestate Silo, should work now....
@Innallas : as long as you mix the issues I will not concider your comments.. And as I told you liquid transport is mode 8 and not availiable....

**Comment by Innallas** [comment]
Huh ? it is working with mode 1 & loading/unloading triggers for liquid -_- why another mode ?? it's just another filltype , i dont mix issues -_-

**Comment by Innallas** [comment]
Huh ? it is working with mode 1 & loading/unloading triggers for liquid since like ....err 2 months -__- why another mode ?? it's just another filltype , i dont mix issues -__-

In fact the big question is : Do you know what you do and do you all test what you make ? look like clearly not...

**Comment by sootysax** [comment]
@Innallas You might want to show a little respect to the devs..

**Comment by sootysax** [comment]
@ThomasGaertner Digestate also working now, very happy..   will check cow slurry tank again and report

**Comment by sootysax** [comment]
`
