### ISSUE TITLE
no titel

### ISSUE THREAD

**Issue by SevenFifty1996** [Courseplay/courseplay#3245]
What an unfriendly and rude forum. I will never post a mistake here again. As I said, unfortunately I can not read Enlisch and thus not scour the forum.

**Comment by Tensuko** [comment]
1) this is not a forum!
2) post the things right to help on issues
3) try in your mother language maybe someone can help translate

**Comment by pvaiko** [comment]
@SevenFifty1996 Die Fehler die du beschreiben hast sind schon gemeldet und werden irgendwann auch behoben.
