### ISSUE TITLE
Course generator: enable CW and CCW only when it makes sense

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/courseplay#3246]
<del>If I create a Course with this setting, CW and CCW are mixed up.
So CW the Path ended up CCW and vice versa.
Can someone confirm this or have I done a mistake ?
Also if I think about it, it depends on the starting point and the amount of pre-turns.
Is there a way to improve this, or like ignore the starting postion as in my example if I start on the other side, it could be alright (going to try it).</del>

Can't change the title, but I tried diff stuff and figured out whats wrong:

Suggestion: For the 'Short Edges' (all Mid Part Strategies), take away the option to set CW and CCW as it only depends on your starting position and if pre-turns before or after mid part, to make the tracktor/combine drives CW or CCW. Tested it in many ways.

**Comment by Tensuko** [comment]
![cw](https://user-images.githubusercontent.com/27344744/53290882-e2c46300-37aa-11e9-8dd4-595ac2d52663.png)
![ccw](https://user-images.githubusercontent.com/27344744/53290883-e48e2680-37aa-11e9-9938-9e1453be5200.png)

the CW and CCW issue at this field is like, preturn and mid part is doing the opposite way. So either preturn or mid part, the pipe is in the fruit. You can see the direction change at the lower part of the mid section. No Idea if that is suppost to work like this. Still testing arround with the new options tho

**Comment by Tensuko** [comment]
Today I managed to make the CW and CCW options work on easier field and it worked as it should.
I would close this, couse there seems to be many things coming together, to make a clear choice, when it works and when not. It is just the point, that the CW turns into CCW after headland makes it hard to see and check what is needed.

**Comment by pvaiko** [comment]
See also #3463, should make sure cross checking all settings and disable what does not make sense.
