### ISSUE TITLE
CP FPS Drop

### ISSUE THREAD

**Issue by Mik789** [Courseplay/courseplay#3247]
Hello, i'm using CP 6.01.00074. 
when I activate the courseplay and create a path or leave a worker to work in a field then the fps start to fall instead of remaining fixed at 60.
This is known when I return to my base, maybe when I have to change tractor or combine harvester or choose another tool to work the fields.
I have a stable for horses, a henhouse, three sheds, a silo and a workshop, about 10+ tools like a sowing machine, plow, fertilizer, blade etc ...
When the courseplayer is not working then I have no problems the moment I go through my base and everything runs smoothly.
I have these problems with every version of courseplay.
Main mods installed: Horse helper, multiple mission, placeable by welting mods (sheds, decoration, silo, etc) GPS mod by Wopster, fast night. I have not installed Real Dirt Color.
Sorry for my bad English, i'm using google translate from Italy.

**Comment by pops64** [comment]
Try turning off the other mods. Also post a log has it could be a debug left on. Make sure your debug channels are turned off. How low is the FPS is getting?

**Comment by Mik789** [comment]
> Try turning off the other mods. Also post a log has it could be a debug left on. Make sure your debug channels are turned off. How low is the FPS is getting?

Here my log. 
Fps are low like 50, like a stuttering...
[log.txt](https://github.com/Courseplay/courseplay/files/2872967/log.txt)

**Comment by pops64** [comment]
Judging by your log I would have to a say a debug is left on. Since I haven't been apart of FS19 development it would have go to @pvaiko it determine if it is CP populating the log

**Comment by roadrunnerR74** [comment]
I dont use Any mods in vheicals but a few other stuff and i have a lot of
frame drops with or without cp it has been the same problem try All the fs
games unfortenly

søn. 17. feb. 2019 kl. 14.06 skrev Mik789 <notifications@github.com>:

**Comment by KCHARRO** [comment]
The same thing happens to me, the FPS fall to 17, but only with combine harvesters ....

When loading the game, I put a course and work well, then if I eliminate that course and put another one starts doing it.

If the combine harvester does not move, the game flows well. But when starting the engine and moving it fall back to 17FPS. it only does it when the harvester moves, if it does not move, there are no falls of FPS

**Comment by Mik789** [comment]
> A giudicare dal tuo registro dovrei dire che è stato lasciato un debug. Dato che non sono stato separato dallo sviluppo di FS19, sarebbe passato a @pvaiko per determinare se si trattava di CP che popolava il log. Inoltre aggiorna spesso per vedere se sono stati riparati perché è stato un errore che è stato messo in atto che potrebbero realizzare prima di leggerlo

Hi and thanks for the reply. 
even with version 6.01.00079 I get the same "warning" on the log.
When you step into an area with many tools and the courseplay is doing any work (sowing, plowing or threshing) then the FPS start to fall and the game proceeds to stutter.
When I close the courseplay or just finish working, then even passing through the same area full of tools the game runs smoothly.
And this happens at the precise time of when a fatal "warning" appears in the log. (I can verify with accuracy).
Also how do I turn off the debug left open?

**Comment by pops64** [comment]
It is not a debug. Just a print stament somewhere in the code that is useful when figuring out how a Giants function works. Usually the are deleted or commented out so it no longer prints. So unless you know LUA or coding in general there isn't much you can do to turn it off except wait for CP team to read this.

**Comment by Tensuko** [comment]
Is it that he runs FS19 with V1.2 ?
Cause in #3262 he runs 1.2 too with same issue.
I run 1.3 and don't have any problem even with many mods.
Anyone else tested diff FS19 Version issue ? (1.2/1.3)

**Comment by Mik789** [comment]
Yes, I use 1.2 version and I have got same issue.
I also have FPS drop even though I'm using a gtx1070 and i7 7700k.
the drop of fps occur when I step into an area with many tools and sheds.

**Comment by pops64** [comment]
Make sure you are always using the latest version of both CP and FS. Has it could be an FS bug

**Comment by Mik789** [comment]
Yes i'm using the latest version of CP and FS (steam versione 1.2 not 1.3 beta).

**Comment by Tensuko** [comment]
Update to 1.3 Beta and try again.

**Comment by stone040** [comment]
I am also having issues with the FPS dropping more so when i attempt to have more than 1 implement on the course eg. baler following behind harvester
log.txt

**Comment by stone040** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/2921835/log.txt)

**Comment by pseikoNL** [comment]
@stone040 , Delete the RealDirtColor mod, that’s the mod who creates lots of problems

**Comment by stone040** [comment]
I'll make sure to do that thanks do you know how it drops the fps?

**Comment by Tensuko** [comment]
Outdated and unclear, what was the actual Issue, couse no report.
Closed.

**Comment by Bandesss** [comment]
Hallo auch wir spielen die Hot20 mit cp 40 FPS ohne 60fps
Bugt der real Dort Mod noch ?

**Comment by Tensuko** [comment]
Das können wir kaum beantworten...

**Comment by Bandesss** [comment]
Ja in der Log ist alles gut. 
OK danke
