### ISSUE TITLE
CP 6 Multiplayer

### ISSUE THREAD

**Issue by BlackRed26** [Courseplay/courseplay#3248]
ich wollte mall gerne Fragen ob CP auch für Multiplayer freigegeben Werden kann 

2 Fehler konnte ich bis jetz mit Multiplayer festgestellt

(1). wenn man ein Kurs aufzeichnet kann man denn nicht speichern

(2). wenn man ein abfahrer  einstellt und denn wider entlassen tut geht nix mehr

I wanted to ask mall if CP can also be released for multiplayer

2 errors I could until now with multiplayer detected

(1). if you record a course you can not save

(2). if you hire a driver and because repudiated is doing nothing more

**Comment by pseikoNL** [comment]
At this moment CoursePlay is only available voor single player mode, also not all the modes in single player are working already, they are work in progress by the CP dev team. When al modes in single player are working properly the dev team will have a look into multi player, till that time you have to wait and have to deal with the fact that CoursePlay isn’t available in multi player.
