### ISSUE TITLE
Course Generation Suggestion - Up the middle

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3250]
Any chance of creating a course generation choice that cuts up the middle, and has two combines working up and down working each side heading from center to edge of field?

This is how I always approach harvesting with two comines and an auger wagon..  it leaves the middle open for augers to reach both combines easily.

**Comment by pvaiko** [comment]
Wouldn't be too complicated for a not too irregularly shaped field. 

Very few people realize how complex course generation can be, especially when you have islands or non-convex fields or both, where you have to work in blocks. (I guess no one ever noticed that CP uses a genetic algorithm in some cases). The challenge would be to make it work in all of those cases. I'll have to think about that.

**Comment by donnti** [comment]
I would like this also but then I play on maps with big fields that don't, for the most part, aren't irregular or have obstacles in the field.

**Comment by mehdinasef** [comment]
I have got another similar suggestion, which is generating a spiral course. I have already done it by making the number of headlands the bigger it could be, but it may be better to have an option that generates this kind of courses automatically. In this course, the pipes of the harvesters are always out of the crop which makes it easier for the auger to unload them.
![spiralharvest](https://user-images.githubusercontent.com/47159754/52977115-5b52aa80-33cc-11e9-920b-d4b7617d347e.png)
![spiralunload](https://user-images.githubusercontent.com/47159754/52977152-7b826980-33cc-11e9-8bfc-6335566603d2.png)

**Comment by pvaiko** [comment]
@mehdinasef why don't you try those different settings for the Field center?

**Comment by mehdinasef** [comment]
I do not know how to do it but I will try.
by the way,thank you for your great job!

**Comment by pvaiko** [comment]
> I do not know how to do it but I will try.

Like changing up/down to spiral?

**Comment by mehdinasef** [comment]
I well try that tomorrow, l have to leave now (it's too late in the night where I live and I have to wake up early in the morning)

**Comment by mehdinasef** [comment]
> Like changing up/down to spiral?

@pvaiko I have done it. I have been trying different settings to generate a course where the combine harvesters start harvesting the field from the centre. I found out that if I set the field centre option to spiral and choose to start working in the up/down rows in the headlands options, it generates the kind of courses you wanted.
![fconeheadland](https://user-images.githubusercontent.com/47159754/53032513-45e28c80-346f-11e9-953a-542d1403cf7d.png)
![fieldcenture](https://user-images.githubusercontent.com/47159754/53032595-6d395980-346f-11e9-9ea5-b507d90adbac.png)
![fcview](https://user-images.githubusercontent.com/47159754/53032631-7b877580-346f-11e9-9608-b3dadb318d61.png)

this setting worked almost well but it had 2 issues:
1) the harvesters have to start with the up/down rows. Therefore they make their turns on the crop in the headlands (not harvested yet). the overloader also have to drive on that crop to get to the harvesters
2) the harvesters make there first turn without any problem, but in the 2nd, 3rd... they start turning around and they seem to get lost.

![turnoncrop](https://user-images.githubusercontent.com/47159754/53033573-a377d880-3471-11e9-9a73-8b86b77afbd3.png)

![turningissiue](https://user-images.githubusercontent.com/47159754/53033646-cc986900-3471-11e9-91df-2b5ef428c220.png)

I also wadered if that waypoint should be there (highlighted in red)

![startheadlands](https://user-images.githubusercontent.com/47159754/53033860-50525580-3472-11e9-96b6-a6d7b55f6d79.png)
for isue (1) if i set it to start with the headlands, it doesn't start from the middle.

![startheadlands](https://user-images.githubusercontent.com/47159754/53034072-c787e980-3472-11e9-932f-3414ba963411.png)

**Comment by pvaiko** [comment]
Closing this as with the new racetrack pattern we have something realistic implemented.
