### ISSUE TITLE
Vehicles Not Driving Merged Courses

### ISSUE THREAD

**Issue by cwattyeso** [Courseplay/courseplay#3251]
Have been trying to test whether it's possible to have a vehicle drive multiple courses loaded together as one big course. For example on the Estancia Lapacho Map I want to Cultivate Fields 1, 2 and 3 with the same tractor and cultivator in one go. I open courseplay and load the Course for Field 1, I then click the folder icon to merge the course for Field 2 and then Field 3, this should give me the extended course I want now. I have also tried this by loading the Course for Field 1 and then clicking the folder icon for 'Append at End of Course'.

What happens in game then when I set the Courseplay worker off is they happily do the work on Field 1 but upon reaching the end of field 1 it stops and tells me it has reached the trigger. If I click Drive Now or Continue in the Courseplay Hud the worker just goes back to the beginning of Field 1 and starts again. He never moves onto Field 2 as he should and work that before moving onto Field 3.

I also notice if I'm doing seeding/fertilising work if I load a Refill Course that I have made so that if the worker runs out of seed/fertiliser/fuel he should go and fill up before continuing on with the field the same thing occurs. The courseplay worker doesn't move onto the refill course when it needs to and instead seems to think that the two courses are completely separate and not in anyway merged.

This seems to be indicated when you put the course overlay dots on and each field/course appears separate with their own start and ending (P) point and there is no connection between any of the courses.

I'm using the latest 6.01.00076 version of Courseplay Beta.

**Comment by sootysax** [comment]
Courseplay doesnt work this way

**Comment by cwattyeso** [comment]
Really? Because it could do this in FS17 and I watched a YouTube video recently by Farmer Klien where he did both examples of what I want to achieve. He had a 3m Cultivator do one field on Ravenport and then move over and do another field. He also showed a Fertiliser running out of fertiliser and then automatically going to the refill course and filling up before returning to the field and carrying on where it left off. However I for the life of me can’t get these functions to occur despite using a much more recent and updated version of the Courseplay Beta then he is in the videos.

**Comment by alpha117** [comment]
The reason it works in his video, is that the fields are right next to each other, don't think it would work if the fields were on opposite sides of the map. Now this begs another question:
Courses recorded for:
Field A seeding
Field A refill
Transfer course field A to Field B
Field B seeding
Field B refill

1. Would it be possible to load and append ALL these in one go?
2, What order does CP run  loaded/appended courses
3. What is the max course that CP can have loaded/appended in one go?

The seed/Fert + refill course works just fine here, just like his video.

**Comment by cwattyeso** [comment]
I understand it wouldn’t be feasible to function across an entire map. However ever example I have tried the fields are right next to each other. Look at the Estancia Map Fields 1, 2 & 3 are in a perfect row with literally a single vehicle width seperating them. Each of the courses when looked at individually the stop point of field 1 is right next to the start point of field 2, which stop point is right next to start point on field 3. So I can’t understand when merging the three courses of even loading them as an append to the end of course 1, that the Courseplay worker isn’t driving them.  Even if I manually move him off of field 1 and start him on field 2 using the ‘Nearest Waypoint’ option he’ll work Field two but again stop at the trigger of Field 2, hitting continue he just circles back round and starts at the start point of field 2 again.

**Comment by alpha117** [comment]
need some Dev input on this I thinks

**Comment by alpha117** [comment]
Not if this would resolve the issue??
![image](https://user-images.githubusercontent.com/30005040/52911642-7f17d280-329e-11e9-9ae2-2a01aecc3b6a.png)

**Comment by cwattyeso** [comment]
Yeah which is why I opened this to get a definite answer from the devs. I’ve tried to multiple courses on a couple of maps now official and modded and Courseplay just doesn’t play ball. What’s funny on the Estancia Map with the Fields I tried is that the default vanilla in game AI workers will do, they happily Hope from Field 1 to 2 and then to 3 if left unsupervised.

As for the refill course I’ll have another look at it and see if it’s possibly something wrong I’m doing, if I’m recording the course in the wrong mode or something. I have tried recording the start and stop points off the field, I’ve tried recording it with the start and stop points on the field but so far no look getting the worker to go and refill when he’s empty he just stops. As for the crossing point above I’m not seeing that when merging or appending courses. In fact on my test with the refill course starting/ending on the field there is still definitely two independent start points/end points for both courses and two separate course paths, no crossing points at all are visible even where the courses overlap.

**Comment by alpha117** [comment]
The refill course is a course in its own right. Recorde them in 'transfer mode' , then save. Clear the course, then load the fieldwork/seeding course now append the refill course.

**Comment by cwattyeso** [comment]
Okay so just done a test with a seeder/fertiliser sower where I recorded the refill course, saved it. Then I went to the field and created the work course and then loaded the refill course with the append to end option. Set the Courseplay Driver off with a little bit of seed and fertiliser loaded, when he ran out of seed first he stopped and drove the refill course and filled up to 100% on seed. He then drove back to the field and resumed where he left off from. A couple of lanes later he ran out of fertiliser. Again he stopped, went to the refill course and drove it. However now he broke, he refilled with seed despite having over 17000 litres in the seeder then drove back to the field, completely forgetting to load with fertiliser when he passed that refill point. He tried to start seeding again, went a few metres, realised he was still out of fertiliser and stopped again and drove the refill course. He once again filled up with only a handful of seed to replace what he just used in the few metres he tried to sow, and again completely drove past the fertiliser station, forgetting to fill up. I then stopped him as presume he would be in this loop indefinitely.

**Comment by sootysax** [comment]
I merge courses all the time..  but not field work on one course, moving to another field, and then fieldwork on another course..  you need to do them one at a time

**Comment by cwattyeso** [comment]
But why if the fields are so close, why can't you load and merge multiple courses and have a worker go do all of them in one go with the same tool?

**Comment by sootysax** [comment]
i don't know 'why not'..  I've just been using CP long enough to know that's the way it is..

**Comment by sootysax** [comment]
I suppose if you manually recorded the fieldwork (not using the course generator) you could record it all in one go..  but the worker would not raise the tool or stop spraying in between fields.

**Comment by alpha117** [comment]
> I merge courses all the time..   I record segments.  from the farm entrance to the yard..  then the yard to fertilizer refill, yard to lime refill, yard to seed and fertilizer refill, yard to farm exit, farm exit to field, field to farm entrance etc..  then when I am working a field, I generate the field work course, then add the segments i need..
> but you cannot merge field work on one course, moving to another field, and then fieldwork on another course..  you need to do them one at a time

I like that way of recording and merging, how does CP then 'link' the end of the field work course to the farm entrance to yard as an example, if they are far apart?

**Comment by sootysax** [comment]
crossing points are automatically created at the start and end of each course, also at the end of every course generator course..  I record the refill course with the start point on the field - to the entrance of the farm.   then add to the end of the course (with the second icon with the + symbol)  the course from the entrance through the refill trigger to the farm exit, then add the course from the farm exit back to the field.   no crossing point is needed in this case

**Comment by alpha117** [comment]
So, as long as each of these 'sub' course start and end within 50m of the next/previous course all is good?

**Comment by sootysax** [comment]
When I have access to Courseplay Editor (WIP), i do like to record a course on each road on the map, going in each direction..  then you create crossing points at each intersection, and at each field entrance and sellpoint, farm entrance exit..   then you do not have to record overlapping courses, and just use the one course for anywhere you wanna go..   I find that it's nearly impossible to pull off without Courseplay Editor however..   you need to be able to fine tune the crossing points on different courses at the same time.    But when it's all setup right, you can use the first add course icon (without the + symbol) and the courses will merge at the place the two crossing points happen

**Comment by sootysax** [comment]
yeah, you want to end your 'field to farm entrance' course close to where 'farm entrance to refill trigger' course begins..   Its good to turn on the crosspoint display so you can see where crosspoints are while you are recording

**Comment by alpha117** [comment]
Is the Editor available for selective testing yet?  'Turn on the crosspoint display...how do I do that?

**Comment by sootysax** [comment]
still a WIP, not available yet..   and HUD General Settings - show waypoints, there is a crosspoint icon

**Comment by alpha117** [comment]
cool, thanks, CP is looking even better, thanks for the pointers, great stuff. I'll give it a good this afternoon

**Comment by alpha117** [comment]
Currently then, using the road recording as an example, as you record this, as you get to a junction you then either stop or slow down to add a crossing point and then carry on with the recording?

**Comment by sootysax** [comment]
yes..  but crossing points and speed need to be PRECISE..  why i use the editor..  or else the vehicle is going to crash into something..   I've found that you need a crossing point before and after a driveway entrance in the course on the lets say 'northbound road' course and one on the course in the middle of those two on the 'southbound road course'.  they should look like a triangle when you look at both courses

**Comment by alpha117** [comment]
Great, how do you see both courses at the same time, sorry for all these questions!

**Comment by sootysax** [comment]
Courseplay Editor

**Comment by alpha117** [comment]
oooh...drat!

**Comment by sootysax** [comment]
this is advanced courseplay stuff..  you should get the hang of merging course segments before trying my crossing points method.  its a full time job :)

**Comment by cwattyeso** [comment]
Well maybe they could add the option in this new version of Courseplay for FS19 to link multiple fieldwork courses together. Would be very useful and time saving.

**Comment by alpha117** [comment]
> this is advanced courseplay stuff..  you should get the hang of merging course segments before trying my crossing points method.  its a full time job :) . I will publish a tutorial on using Courseplay Editor when it's released..   I just wanted to show you what merging courses was about..  and that it's not about linking multiple fieldwork courses together.

Will do, thanks for all your help. Do you have a timeframe for release of the editor?

**Comment by sootysax** [comment]
> Well maybe they could add the option in this new version of Courseplay for FS19 to link multiple fieldwork courses together. Would be very useful and time saving.

They never have before every time it's brought up when every new version of courseplay comes about...

**Comment by sootysax** [comment]
> > this is advanced courseplay stuff..  you should get the hang of merging course segments before trying my crossing points method.  its a full time job :) . I will publish a tutorial on using Courseplay Editor when it's released..   I just wanted to show you what merging courses was about..  and that it's not about linking multiple fieldwork courses together.
> 
> Will do, thanks for all your help. Do you have a timeframe for release of the editor?

no, and don't you know it's rude to ask when mods are going to be completed?

**Comment by alpha117** [comment]
As a test, I just created 2 simple courses. Yard > Farm Entrance and Farm Entrance > Shop. Loaded and merged both, worked perfectly. 

On the Farm Entrance > Shop, when I recorded it I added crossing points at junctions and other key areas like fields, stables, sell points etc. Hopefully to utilize these going forward. This is defiantly the way to go in using CP; time consuming but once done that's it

**Comment by sootysax** [comment]
if you can see your crossing points while you're recording your sell routes at the sellpoints, you should be able to start and stop those courses in a good spot to connect with your crosspoints on your road course...  I would try to be rolling when you start and stop those courses instead of being at a dead stop..  do it at a realistic turning speed, and it will drive better

**Comment by alpha117** [comment]
I now have 

1. Main Road (west)
2. Main Road (east)
3. BGA sell point
4. Shop
5. Yard to farm entrance

On the main road courses, if the entrance is on  my side I add crossing point just before and just after the entrance. If the entrance was on the other side I added crossing point in the middle. East and west now form the triangle as you suggested.

I need to change how I end a course as you suggested, I'm stopped them at 90, which as you said makes it difficult for CP to navigate.
 get to the shop easy Load #5 merge #2 merge 4. 
get to the BGA  Load #5 merge #2 merge 3

Many thanks for this 'learning', it's been worth it.

Thanks

**Comment by alpha117** [comment]
Turning off traffic helps when recording.....lol!


Yep, need the editor to be to move the crossing points, I must have recorded main road (east) 6 times now ,as the middle crossing point was not correct ….aaarh  ;-)

**Comment by alpha117** [comment]
I now have a lot of the 'base' Courses recorded:

![image](https://user-images.githubusercontent.com/30005040/52949825-5282ba00-3375-11e9-80cb-0a7b4ac492da.png)

I can now get to a lot of places by merging the correct base courses.  They are not perfect, as some of the waypoints could do with a 'tweak' to make them perfect; but they are workable.  Fantastic function (Merge) that I have never used before, thanks for the insight.  Still lot more to do, but should not take to long to complete

**Comment by Tensuko** [comment]
I think it had something to do with field detection when to lower tool and such.
And if add refill course, how can CP know wich field to go back to ?
What refill course to choose, when on field number 3 of lets say a total of 5 ?
You got to add a lot more informations to the courses and connections between them.

Like Field A+refill, Field B+refill and so on.
In wich order would you add the courses ? For Fieldwork I see it impossible for the way CP handels it right now. The Crosspoints are only to for not need to record so many courses. Like 1 main street with a Crosspoint at each sidestreet and then the single courses so it goes away from maincourse to sidecourse, something like that, but I rly never used them.

**Comment by alpha117** [comment]
You cannot merge fieldwork courses.  I have so far 37 courses for Marwell Manor, and now use merged course to get around Marwell manor, brilliant way to do it.

**Comment by PromGames** [comment]
Yes, courseplay editor is working and in beta test. We have setup a GitHub page for reporting issues and open to create wiki pages by collaborators. 

This is the link

http://courseplaypatheditor.github.io/CoursePlay-Editor-6/

I expect you join us in developing this tool

Prom Games

**Comment by alpha117** [comment]
Thanks, already in. I'll continue report there, do you want me to transfer the suggestions etc or start with new ones?

**Comment by sootysax** [comment]
@alpha117 I'd love to check out your courses if you're willing to thrrow them up on google drive..   Hoping to be able to get Course editor working on my computer soon..

**Comment by alpha117** [comment]
[FS19_Marwell_Manor_Farm.ModMap.zip](https://github.com/Courseplay/courseplay/files/2889971/FS19_Marwell_Manor_Farm.ModMap.zip)

There you go, got course editor work OK here.

**Comment by sootysax** [comment]
cool, i'll check them out..    they take a REEEAALLY long time to load by the way..    you normally shouldn't save fieldwork courses, but regenerate them when as needed.  Will cut your game load time by 5 minutes lol

**Comment by alpha117** [comment]
Great tip, thanks

**Comment by cwattyeso** [comment]
> I think it had something to do with field detection when to lower tool and such.
> And if add refill course, how can CP know wich field to go back to ?
> What refill course to choose, when on field number 3 of lets say a total of 5 ?
> You got to add a lot more informations to the courses and connections between them.
> 
> Like Field A+refill, Field B+refill and so on.
> In wich order would you add the courses ? For Fieldwork I see it impossible for the way CP handels it right now. The Crosspoints are only to for not need to record so many courses. Like 1 main street with a Crosspoint at each sidestreet and then the single courses so it goes away from maincourse to sidecourse, something like that, but I rly never used them.

On one of the maps I'm playing, the field layout really does seem to promote the need to have multiple fieldwork courses run in sequence.
![fsScreen_2019_03_09_13_52_27](https://user-images.githubusercontent.com/13921716/54072473-199e7c80-4273-11e9-956b-6d486867589b.png)

In my example I'd really like to be able to merge a Ploughing/Cultivator Course for Field 3, Field 6 & Field 7 and just have the worker do them all in turn and in sequence.

If I'm doing a Fertilising Cycle or Seeding I don't again see why Courseplay can't allow me to load and Merge the Courses for Fields 3, 6 & 7 and also have the Refill Course that all three fields share and if doing the fields one at a time can use without issue. I don't see why Courseplay would get confused about where to resume seeding after running the refill portion of the course or on what field as it's programmed to resume from the waypoint it ran out at, so it would always go back to the correct place and restart as it does now.

I understand merging fieldwork/fertilising/seeding courses like this probably isn't done on large scale maps with large fields, but on some maps and certainly the smaller maps it definitely lends itself to a practical application.

**Comment by Tensuko** [comment]
Outdated and CP can't and I am sure won't be able to handle this.
If anything new about such things, we will let you know.
Closed.
