### ISSUE TITLE
Rubicon 9000 turning radius

### ISSUE THREAD

**Issue by Spatzekopp** [Courseplay/courseplay#3253]
The automatically set turning circle for the Rubicon 9000 seems to be too small so that during some maneuvers the helper does not get the turn and leave the course. I think the problem is that as soon as I start the helper, he automatically switches to front-wheel steering even if I had previously adjusted to all-wheel steering. I guess the default 10-meter turning radius is meant for all-wheel steering which gets turned off by starting the helper. Setting the turning radius to about 15 meters fixes the problem.

**Comment by Tensuko** [comment]
[Rubicon9000Turn91214.txt](https://github.com/Courseplay/courseplay/files/3587402/Rubicon9000Turn91214.txt)
![fsScreen_2019_09_08_09_55_00](https://user-images.githubusercontent.com/27344744/64485281-f2733880-d21e-11e9-899a-a954361fb1cd.png)
![Uploading fsScreen_2019_09_08_09_54_53.png…]()
![Uploading fsScreen_2019_09_08_09_54_45.png…]()
![Uploading fsScreen_2019_09_08_09_54_01.png…]()
