### ISSUE TITLE
When 2 tools in the rear an in use Courseplay doesn't lift the front tool.

### ISSUE THREAD

**Issue by Hmmvee** [Courseplay/courseplay#3254]
You can see in the screenshot that ist doesn't lift the front tool when in the rear are 2 tool connected as the are planned to be used together.
At the screenshot it is changing the direction.
Then the really big turning radius of the front tool is used and creates often crashes between trees or other stuff beside the field.

![fsscreen_2019_02_17_13_20_56](https://user-images.githubusercontent.com/46241969/52912886-19384480-32b8-11e9-830f-f2e2d792f861.png)

Update 1:

Also doesn't lift the front tool when in the rear is only 1 tool used.

![fsscreen_2019_02_17_13_52_14](https://user-images.githubusercontent.com/46241969/52913153-6833a900-32bb-11e9-85ab-4b849b73a456.png)

Update 2:

Issue seams to be linked to the working mode.
The mode for field work lifts the front tool. The mode for seeding not.

![fsscreen_2019_02_17_14_45_47](https://user-images.githubusercontent.com/46241969/52913926-f0697c80-32c2-11e9-8e90-07b96a6eb21d.png)

**Comment by Tensuko** [comment]
Thats the Kuhn TF 1512 I talked about. Doesn't lift and cause the Tracktor to be not able to turn (sometimes), caus of the wheels can't go backwards.

**Comment by SuBerPL** [comment]
After update v6.01.00109 courseplay lowers the weight with the tool attached at the back
![1](https://user-images.githubusercontent.com/32776608/53695265-743e6100-3db9-11e9-8aed-9db538de4ccb.png)
![2](https://user-images.githubusercontent.com/32776608/53695267-76082480-3db9-11e9-8916-a803eee87230.png)
With kuhn seeder it's working good

**Comment by pvaiko** [comment]
That's why I reverted 109 and reopened this issue. Still not solved.

**Comment by corrado33** [comment]
> That's why I reverted 109 and reopened this issue. Still not solved.

I had this issue, but fixed it via a suggestion on reddit.

> In the vehicle XML, Section AI, add: "<needsLowering value="false" />"

This isn't a CP issue per se, just a game issue. When I use weights they are not lowered. But when I used the seed holder above it would lower, making the tractor impossible to steer. So I made the simple edit above and all is well. I suggest you do that.

**Comment by pvaiko** [comment]
It is not a game issue, just talked to the Giants folks yesterday on how to properly use the AIImplement API  and hopefully got it right in v118 without breaking anything else.
