### ISSUE TITLE
Headland turn needs improvement when angle is less than 90

### ISSUE THREAD

**Issue by Messy71** [Courseplay/courseplay#3255]
Setup:
F07 - Ravenport { [savegame1+courses](https://www.dropbox.com/s/bb4saxcik0o5gh0/savegame%2B%20courses.rar?dl=0)}
**Courseplay v6°01°00076
Farming Simulator 19 (Steam)
  Version: 1.3.0.0 b3694**
Tractor: Fendt 1050
Fertilizer spreader: Bredal K165 w/ 6m spreading unit
Turning circle: (mnl)22
Turning speed: 15 kph
Field speed: 24 kph
Reverse speed: 6 kph
Working width: 24m
Tool offset vertical: 2.0m (front)
Problem n°1:
I've created this course [[**course0012/F7SkipWaypoints564->575** | log+ photos](https://www.dropbox.com/s/7oyjgn2fp78o093/c12%20log%2Bphoto.rar?dl=0)]
Start with straight lines then two passes of headland ending point NE corner . At the **transition** from first headland to second (transition in corner of the field) it doesn't recognize it as a turn but as a lane change and skips from waypoit 564 to 575 {[here is just the log](https://gist.github.com/Messy71/c2c3bc01da550a9a824f128dc48348b5)} .Cp manages to execute the entire course but leaves non-worked area where it was skipping waypoints.

Then I've tried with this course[[**course0011/F7S->H343->348+4.5CWspins**| log+photos](https://www.dropbox.com/s/o0r3mtj1ec4k76q/c11%20log%2Bphoto.rar?dl=0)]
Start with straight lines then two passes of headland ending point: the middle of headland towards field 8.
At the **transition** between last straight line and first headland pass (there is a red end turn waypoint overlapping a orange waypoint) starts the turning (90° turn) at waypoint 343.
The tractor drives straight then turns for the bend , does 4.5 CW spins and then goes where he's supposed to go, put's it in reverse ,align itself with the second straight line of the 90° turn and continues the course from waypoint 348.{[here is just the log](https://gist.github.com/Messy71/e0b6d90c4e8701c621b0ee9380d21b24)}

**Comment by pvaiko** [comment]
Try to upload the photos directly here, no dropbox or rar please.

**Comment by Messy71** [comment]
For Course0012
![fsscreen_2019_02_17_16_10_37](https://user-images.githubusercontent.com/47163914/52929204-b8eee480-3343-11e9-82ab-51b9da2d3e7e.png)
![fsscreen_2019_02_17_16_10_50](https://user-images.githubusercontent.com/47163914/52929234-dae86700-3343-11e9-8429-1e7d0494c1ae.png)
![fsscreen_2019_02_17_16_11_07](https://user-images.githubusercontent.com/47163914/52929258-f8b5cc00-3343-11e9-87d1-be554131e6c5.png)
![fsscreen_2019_02_17_16_11_30](https://user-images.githubusercontent.com/47163914/52929284-12efaa00-3344-11e9-8c0f-5c37b3f026e4.png)
![fsscreen_2019_02_17_16_11_36](https://user-images.githubusercontent.com/47163914/52929294-1f740280-3344-11e9-9a43-b3b2ac7b2cb2.png)
![fsscreen_2019_02_17_16_11_42](https://user-images.githubusercontent.com/47163914/52929307-331f6900-3344-11e9-80fd-cbabddbd4250.png)
![fsscreen_2019_02_17_16_11_45](https://user-images.githubusercontent.com/47163914/52929317-403c5800-3344-11e9-9a5d-06f075247f3e.png)

**Comment by Messy71** [comment]
For Course0011
![fsscreen_2019_02_17_16_33_42](https://user-images.githubusercontent.com/47163914/52929374-6eba3300-3344-11e9-9ba1-499a0e8aff91.png)
![fsscreen_2019_02_17_16_33_45](https://user-images.githubusercontent.com/47163914/52929385-81346c80-3344-11e9-8fa4-23e1fc04ecdd.png)
![fsscreen_2019_02_17_16_33_52](https://user-images.githubusercontent.com/47163914/52929411-9dd0a480-3344-11e9-9a88-9a298c2961e6.png)
![fsscreen_2019_02_17_16_34_17](https://user-images.githubusercontent.com/47163914/52929443-bb9e0980-3344-11e9-8610-1dcb1d51644d.png)
![fsscreen_2019_02_17_16_34_37](https://user-images.githubusercontent.com/47163914/52929477-db353200-3344-11e9-962c-1760c8d7d445.png)
end of the 4 and 1/2 spins .

![fsscreen_2019_02_17_16_34_40](https://user-images.githubusercontent.com/47163914/52929530-120b4800-3345-11e9-86f5-27091a5a5dc7.png)
![fsscreen_2019_02_17_16_34_47](https://user-images.githubusercontent.com/47163914/52929553-20596400-3345-11e9-8996-30c8aa901f7f.png)
![fsscreen_2019_02_17_16_34_50](https://user-images.githubusercontent.com/47163914/52929563-39621500-3345-11e9-897e-60eb1c17e600.png)
![fsscreen_2019_02_17_16_35_04](https://user-images.githubusercontent.com/47163914/52929600-5c8cc480-3345-11e9-95b9-9c556e234424.png)
![fsscreen_2019_02_17_16_35_18](https://user-images.githubusercontent.com/47163914/52929618-70d0c180-3345-11e9-8e8d-69dbc470c16c.png)
![fsscreen_2019_02_17_16_35_33](https://user-images.githubusercontent.com/47163914/52929665-a1186000-3345-11e9-90e0-a560437f39f1.png)
![fsscreen_2019_02_17_16_35_48](https://user-images.githubusercontent.com/47163914/52929693-c1e0b580-3345-11e9-9324-a451afdb4401.png)
![fsscreen_2019_02_17_16_35_57](https://user-images.githubusercontent.com/47163914/52929698-cb6a1d80-3345-11e9-83cf-04f61693ac75.png)

**Comment by Messy71** [comment]
do you also need the courses in a gist ?( or anything else )

**Comment by pvaiko** [comment]
Thanks. The first case is fine tuning category and I'll probably won't fix it. The second however seems to be a bug, can you post that course here for me (just the XML)?

**Comment by Messy71** [comment]
sorry for the late reply (was at work) , here you go ->[**F7S->H343->348+4.5CWspins** ingame title](https://gist.github.com/Messy71/b5fc005dc4977f547e129daf5065aad2)

**Comment by pvaiko** [comment]
Can't reproduce this.

**Comment by Messy71** [comment]
@pvaiko I'm not sure if it has something to do with this but I have the vehicleControlAddon (old keyboardSteering) from Mpgli12 (on Github). I will try to reproduce it myself ( after work ) on other map without mods or with only that mod to see if there's a conflict between  them.

**Comment by pvaiko** [comment]
I tried with your course, same trailer, different tractor. Overlapping isn't a problem. 

Why are you using 22 m turn radius? That's way too much, does happen with the auto setting too? And why 2 m offset?

**Comment by Messy71** [comment]
The 22 m turn circle is almost  perfect for the 24m work width , when you do the inside linees ( parallels ) it makes the turn half a circle and keeps a constant speed trough out the turn. When i let it to auto the turn look’s like a «  U «  with a flat bottom and it slows down very much in the corners of the turn.

As for the 2m offset , when it’s spraying the base of the trapeze is at ~2.2m away from the auto setting. I set it that way because when it reverses it doesn’t go all the way to the end of the field. 
Put it this way , the affected area it’s a hexagon, the area at the last reverse waypoint in a turn it’s a square if you put them together the back corners aren’t covered with fertilizer the front ones will get covered when it goes forward. If you draw a rectangle in the hexagon the difference between the rectangle and the square is ~ 2.2m.
I’m not sure if i tested with the auto turning circle or what it does in that turn. I’ll post some pictures and another log later tonight.

**Comment by Messy71** [comment]
@pvaiko 
I've created a new savegame (same map/ same courses) only Courseplay as a mod.
Tested the Fendt 1050 -> does the same thing
Deleted all courses , recreated the course in question Fendt 1050 does the same thing also with auto turning circle.
I bought a CASE Magnum CVX 380 recreated the course all works fine. 
When hooked up to the fertilizer spreader both has the same turning circle 12m but at the same speed 15kph they turn different (1050 goes wider )
![fsscreen_2019_02_20_21_02_22](https://user-images.githubusercontent.com/47163914/53121667-fd9d9a00-3554-11e9-8f71-e3c22ec759e2.png)
Tested with the Fend 1100MT and when it starts reversing in the same turn the tractor follows the projected debugg line very well but jackknive's the spreader and at the end of the reversing sequence it says it's slipping.
 {**8m auto turning circle, also when hooked up to the fertilizer spreader the narrow side of the working area ( defined by the red rectangle) is way smaller. For the other two tractors is pretty much the same and about 4x bigger**.}

**Comment by pvaiko** [comment]
Can you set up a savegame with this and post it here and tell me what do I need to do to start them spinning?

**Comment by Messy71** [comment]
One question if you don't mind...
Does the course generation adjust itself if another value is set for the turning circle before the creation of the course? (in both case's when i set it up  auto or 22m turning circle the course layout is the same). 
@pvaiko How do you want to post the savegame here? ( explain for dummies , which files in the savegame,  should i put in a gist?)

**Comment by pvaiko** [comment]
Just zip the savegame folder and the CoursePlay_Courses folder, gist is fine

**Comment by pvaiko** [comment]
Turn radius only used for the headland round corners during course generation, nothing else.

**Comment by Messy71** [comment]
At the end of the straight line ( inside parallels ) you have two lines pretty much together , put your tractor on the top line (north) heading from West to East. Start from nearest waypoint and in the HUD should say waypoint 340 or someting smaller then 343.
Do you want the course set up with the Fendt 1050?

**Comment by pvaiko** [comment]
Absolutely. In a perfect world, all I have to do is click on 'Drive' and watch :)

**Comment by pvaiko** [comment]
don't need logs

**Comment by Messy71** [comment]
@pvaiko gist doesn't let me upload zip file!

**Comment by pvaiko** [comment]
ok

**Comment by Messy71** [comment]
Here it is [Fendt 1050/1100MT](https://www.dropbox.com/s/munq2pikrz0sil5/ForPeterWithLove.zip?dl=0)

**Comment by Messy71** [comment]
you could  hit drive with the 1050 from nearest waypoint i've line it up and the 1100MT is to the left.

**Comment by Messy71** [comment]
Small little problem doe....
When I've deleted the other courses from the savegame3 it also deleted them from savegame1 (both MapUS only one folder in the Courseplay_Courses folder) 
Could this be changed to where if you have savegame7 it creates a folder named MapUS7 ? @pvaiko thank you for the fast reply.

**Comment by Messy71** [comment]
> Turn radius only used for the headland round corners during course generation, nothing else.

@pvaiko I think it should be used also in the 90° corners where the tractor drives forward past the green waypoint ,reverses to the start of the projected turn line,drives along the curve and then starts reversing until the implement (work area ) is under the red waypoint.
This would mean that it would take longer to turn but it will align the trailer / implement with the tractor before reversing therefore the tractor wouldn't jackknife  so often.

**Comment by pvaiko** [comment]
Relax, that's a whole different animal, that's a turn maneuver, those are not calculated during the course generation and do take the turn radius into account of course.

**Comment by Messy71** [comment]
i was very worried .......:D 😜
Could the distance that it drives forward ( before aligning with red waypoint ) be increased ? ( or should i change it in a file [turn.lua?]).

**Comment by pvaiko** [comment]
This is a turn maneuver problem when the angle between the turn start and turn end waypoints is significantly less than 90 degrees. Won't fix this now, changed the course gen not to generate turns below 75 degrees.

**Comment by Hubcap-1** [comment]
Important suggestion in finding a solution to backing up.  I think the programming of this mod lacks a serious portion iof consideration. There is an important " geometry" consideration when backing any vehicle. This is known technically  as a " Bridge rule". The " Bridge" is the distance from the attacher pivot point to the center of the rear axle ( Or the middle point between a dual or triple rear axle). This measurement is key to figuring out the input required from the " control vehicle" ,( the tractor) , for a successful reverse maneuver. I believe the formula incorporated at this time is only worked out ( oversimplified) for short wheel base rear attachments like the Horsch pronto or something similar

**Comment by Hubcap-1** [comment]
This problem seems to happen for me when the angle is less OR greater than 90 degrees.

**Comment by pvaiko** [comment]
For those who want and who know how to do it, you may give the improved headland turns a try. This is on the separate headlandturns branch (https://github.com/Courseplay/courseplay/tree/headlandturns)

**Comment by Messy71** [comment]
@pvaiko i saw that commit from 2~3 day ago but i didn't have much time to play / tinker with it.
Is there a function in Sublime / notepad++ to merge in the correct way the files from this commit with those from the master branch? Or will they be pushed to a master commit later on?

**Comment by GeorgeEarslight** [comment]
> For those who want and who know how to do it, you may give the improved headland turns a try. This is on the separate headlandturns branch (https://github.com/Courseplay/courseplay/tree/headlandturns)

I'll give it a shot with the big towed sprayer on the weekend. 
I usually do 2 smooth pre-headlands with that implement. Do you want me to try anything specific?

**Comment by Messy71** [comment]
@GeorgeEarslight i found that the best way to test it for me is start with up/down first finish with two headlands in turn mode.
Try to set the ending point ( starting point if you set the headland first option ) in different points of the headland corners / middle ( also it’s a plus if the red transition waypoint overlapps a yellow one, in this situation i had the majority of the problems).

**Comment by pvaiko** [comment]
@Messy71 that's why I said 'those who know how to do it' :) it is easy to switch to any branch with git, research.
@GeorgeEarslight I have limited time (and motivation) to test, so I use one or two implements only, anything above that helps.

**Comment by Messy71** [comment]
@pvaiko so all i have to to is download this[headland reverse turn imporvements commit eef3f9d](https://github.com/Courseplay/courseplay/tree/eef3f9db6e595af230acc9c8b1bc5f9748af258d) and test the shit out of it.
But i was wondering if there is a way to merge it with the new master version v6°01°00099?

**Comment by pvaiko** [comment]
Rebased it on master (99), you can use this one: 3e79a0d2d6b141aefd595e52a3e0327b4e06fc35

**Comment by GeorgeEarslight** [comment]
> @GeorgeEarslight I have limited time (and motivation) to test, so I use one or two implements only, anything above that helps.

@pvaiko first test on Marwell F15 with simple 3point implement was immaculate.
There's a sneaky round bypass on the first power pole followed right away by Up-Down and the worker did it perfectly.
Got video with debug14 which I will upload this weekend when I test more tools on F15 (I consider it the most difficult field).

**Comment by Hubcap-1** [comment]
On that threaded page at the top is the zip download. That is a complete
master that now includes the new files download it and put it in your mod
folder

**Comment by Hubcap-1** [comment]
Okay I think I misunderstood your question yes if you look at that zip file
you will see two new turn files with in it. Just copy and paste replacing
the old ones in the new version master

**Comment by Messy71** [comment]
First : Fendt 1165 Flexicoil [LOG](https://gist.github.com/Messy71/72a03b15fb22dc9bb9f3ec77f25f98b5)
![fsscreen_2019_02_28_22_34_10](https://user-images.githubusercontent.com/47163914/53602186-4df8a580-3bae-11e9-8cfe-5182818235b1.png)
![fsscreen_2019_02_28_22_34_16](https://user-images.githubusercontent.com/47163914/53602187-4df8a580-3bae-11e9-87bf-231343888efd.png)
![fsscreen_2019_02_28_22_34_28](https://user-images.githubusercontent.com/47163914/53602188-4df8a580-3bae-11e9-8f6f-2515bf093f82.png)
![fsscreen_2019_02_28_22_34_46](https://user-images.githubusercontent.com/47163914/53602189-4e913c00-3bae-11e9-88a0-8355a3474fb6.png)
![fsscreen_2019_02_28_22_35_15](https://user-images.githubusercontent.com/47163914/53602190-4e913c00-3bae-11e9-87a9-21bd3084ea6e.png)
![fsscreen_2019_02_28_22_35_36](https://user-images.githubusercontent.com/47163914/53602192-4e913c00-3bae-11e9-8699-cbca0c382243.png)
![fsscreen_2019_02_28_22_35_39](https://user-images.githubusercontent.com/47163914/53602193-4e913c00-3bae-11e9-8cc5-cf5a1899316c.png)
![fsscreen_2019_02_28_22_35_41](https://user-images.githubusercontent.com/47163914/53602195-4e913c00-3bae-11e9-9597-1f20f0c9920a.png)
![fsscreen_2019_02_28_22_35_45](https://user-images.githubusercontent.com/47163914/53602196-4f29d280-3bae-11e9-88a4-b0230d2c2ea8.png)
![fsscreen_2019_02_28_22_35_53](https://user-images.githubusercontent.com/47163914/53602197-4f29d280-3bae-11e9-8afc-bf35b2474a42.png)
![fsscreen_2019_02_28_22_35_57](https://user-images.githubusercontent.com/47163914/53602198-4f29d280-3bae-11e9-9f8f-47c0cfd869d2.png)
![fsscreen_2019_02_28_22_36_07](https://user-images.githubusercontent.com/47163914/53602199-4f29d280-3bae-11e9-94b5-201b3c421d13.png)

**Comment by Messy71** [comment]
Second: Fendt 1050 Amazone Condor [LOG](https://gist.github.com/Messy71/0382815d3ea37860f53d0c0c296982d5)
![fsscreen_2019_02_28_22_54_09](https://user-images.githubusercontent.com/47163914/53602351-cb241a80-3bae-11e9-95c3-3b3a727c76f2.png)
![fsscreen_2019_02_28_22_54_12](https://user-images.githubusercontent.com/47163914/53602352-cb241a80-3bae-11e9-8fd7-83ff65357242.png)
![fsscreen_2019_02_28_22_54_16](https://user-images.githubusercontent.com/47163914/53602353-cb241a80-3bae-11e9-9a57-0ce4ff3da23d.png)
![fsscreen_2019_02_28_22_54_24](https://user-images.githubusercontent.com/47163914/53602354-cbbcb100-3bae-11e9-9b26-2d2e235525bb.png)
![fsscreen_2019_02_28_22_54_35](https://user-images.githubusercontent.com/47163914/53602355-cbbcb100-3bae-11e9-99db-8f0fd5204a75.png)
![fsscreen_2019_02_28_22_55_04](https://user-images.githubusercontent.com/47163914/53602356-cc554780-3bae-11e9-8950-282a743a53f1.png)
![fsscreen_2019_02_28_22_55_18](https://user-images.githubusercontent.com/47163914/53602357-cc554780-3bae-11e9-8a98-8853a28f57c7.png)
![fsscreen_2019_02_28_22_55_30](https://user-images.githubusercontent.com/47163914/53602358-cc554780-3bae-11e9-8227-754c09e6af2d.png)
![fsscreen_2019_02_28_22_55_35](https://user-images.githubusercontent.com/47163914/53602359-cc554780-3bae-11e9-9fba-5348c80f83c0.png)
![fsscreen_2019_02_28_22_55_41](https://user-images.githubusercontent.com/47163914/53602360-ccedde00-3bae-11e9-884b-69b5f34321cd.png)
![fsscreen_2019_02_28_22_55_43](https://user-images.githubusercontent.com/47163914/53602361-ccedde00-3bae-11e9-9e18-3e901735e661.png)
![fsscreen_2019_02_28_22_55_51](https://user-images.githubusercontent.com/47163914/53602362-ccedde00-3bae-11e9-8ebf-e5dbf07794a1.png)
![fsscreen_2019_02_28_22_56_03](https://user-images.githubusercontent.com/47163914/53602363-ccedde00-3bae-11e9-9c6a-7a49dbfd819e.png)
![fsscreen_2019_02_28_22_56_16](https://user-images.githubusercontent.com/47163914/53602364-cd867480-3bae-11e9-8b72-935238bce251.png)

**Comment by Hubcap-1** [comment]
VIDEO LINK to the above described Estancia turn problem with Fendt 1050 and Amazone Condor. Not my usual 1440P + resolution. Compressed ( fast ) down to 1080P / 30fps with handbrake. This saves a lot of upload time. Hopefully still HD on you tube. Please note that the actual problem starts just before 6 minute mark. However if you want complete course / field / plot info start from beginning. I do in the problem area try to include what I believe are the debug channels....not sure which ones are needed. A reply stating whether or not my uploads are helpful would be appreciated so I know I'm not wasting my efforts. If I need to change resolutions or anything else you would like me to do....let me know in a reply.

https://www.youtube.com/watch?v=crgWCkJ6B0c&feature=youtu.be

**Comment by Messy71** [comment]
@Hubcap-1 i think they are very helpfull also for the debugg channels when you hover over them with the mouse they will have a description bottom left corner in my photos i use channel 12 for waypoints details 13 and 14 are for back markers of the tractor small green / red lines  and the projected turn line ( i forgot wich does what) but does 3 should be fine

**Comment by Hubcap-1** [comment]
Okay forgive me I'm a little confused are you suggesting that I not just
click on the debug channels and Lyle the information to display or do I
need to hover my most over the information being displayed on the screen or
over the debug Channel itself...I'm also a little confused cuz I only see
debug channels if you look at the video up to 12 does that increase by
clicking on the button to the right of that thanks for the comeback

**Comment by Messy71** [comment]
at the end of 12 it’s a down arrow hit that and the next page it’s 13->24

**Comment by Hubcap-1** [comment]
and do I hover my mouse cursor over those channels while they're being
displayed maybe you can clarify exactly what you're looking for

**Comment by Messy71** [comment]
@Hubcap-1  when a developr ask you for a log with debugg channels 12,13, 14  you should highlit them by clicking on them( they turn gree in my pictures i have 13  and 14 activated 12 is also activated but i didnt take a picture of that page)
After you activated them start the course with the “nearest waypoint” option right before the corner that gives you problems (7-8 waypoints before the green waypoint in the corner) 
Stop the course after the tractor did the problem , save the game, exit the game.
In your user files you have a folder user/My Documents/My Games/FarmingSimulator19 at the bottom of the FarmingSimulator19 folder you have a file called log.txt
You than go to your github page click on your profile look for your gists / create a new gist / drag and drop there the log.txt/ hit create public gist/ change the embedded link to a share link / copy that link and put it under the link of the video

**Comment by Hubcap-1** [comment]
Okay I followed that and I have put my logs for that saved game into the g
i s t hopefully you can find it I title it hubcap _/Headlands /turn problem
on Estancia lapacho @Messi

**Comment by Hubcap-1** [comment]
Okay I'm missed to share the link I'll go back and do it again

**Comment by Messy71** [comment]
i can’t . you have to copy the share link and edit the comment where the video that you made is and paste it there , update the comment. 
That way it will be easier for dev Peter Vaiko to understand visuals and code all in one comment.

**Comment by Hubcap-1** [comment]
I’m not sure if you can help me to make this link work…take a look

https://github.com/Courseplay/courseplay/issues/3324

Sent from Mail for Windows 10

**Comment by Hubcap-1** [comment]
Once again forgive me if I can't see anything to share the link in the g i
s t where I copied the logs I did make them public the above address Henry
in my browser just shows GitHub GIS t.com I don't think that's the link
forgive me I'm stupid laugh out loud do you have discord I'm actually not
stupid I've just never done this before maybe you could join me on my
discord Channel and I could share my screen

**Comment by Hubcap-1** [comment]
Can you come onto my discord channel..I’ve just never done this and I’m missing something….I could share my sceen make it simple this way

https://discord.gg/uTP365

Sent from Mail for Windows 10

**Comment by Hubcap-1** [comment]
OK I think I figured it out and put the link to the GIST in with the link to my uploaded video….check and see if I have that right.

Sent from Mail for Windows 10

**Comment by Messy71** [comment]
yeah you got it right but when you create a log you should activate the debugg channels before you start the course. And keep it clean , by this i mean align your tractor 7-8 waypoints before your corner with the problem , save the game, exit the game (Alt + F4)
Enter the game go to the tractor activate channels 12, 13,14 change the start option to nearest waypoin hit drive wait for problem to happen stop the driver, save the game , exit the game. Take the log. txt make a gist share it there with the video ( take a look at on of my logs after the date and time on each line of courseplay there is dbg12 or dbg14  (dbg13)  i didn’t saw that in your log)

**Comment by Hubcap-1** [comment]
Ok redoing as we speak


Sent from Mail for Windows 10

**Comment by Messy71** [comment]
@Hubcap-1 now i really need to go to sleep it’s 3 am and i need to be up by 6 am. Good luck.

**Comment by Hubcap-1** [comment]
New Video link upload  and new Gist as per "How to",  help by @Messy71
Here is the new video link and the new GIST link to Estancia Lapacho Headlands / Turn issue on field 29

https://gist.github.com/Hubcap-1/2ece41234a39e670c87487e46402feb6

https://www.youtube.com/watch?v=xJpsVnYoLBg

**Comment by GeorgeEarslight** [comment]
Wow, lot's of traffic here. 
@pvaiko Anyway here's the original fork, working great for a 3point implement.
https://youtu.be/oYYJC9ZXLk4
Will do towed on weekend.

**Comment by Messy71** [comment]
@pvaiko from what i’ve tested today with version 6•01•00103 , i think the turn maneuvers works perfect. 
Still have an issue with transition from last up/down row where the second-to-last yellow waypoint points forward , the last one is at an angle of 42,5 degrees then the green turn waypoint it’s also at an angle of 42,5 degrees **but i’ll open another issue** for now i consider this one fixed.
