### ISSUE TITLE
Crossing points not be deleted when course is deleted

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#3259]
Therefore when you merge course it is using the closest Crossing point, even though that was in the deleted course.  Hope that makes sense!
Example:
![image](https://user-images.githubusercontent.com/30005040/52919476-c764de00-32fa-11e9-940f-07805a8fa5c2.png)
All courses deleted and left with the crossing point. these are User added crossing points BTW, not the ones at the start and end of the course, those one are deleted.

![image](https://user-images.githubusercontent.com/30005040/52919524-1dd21c80-32fb-11e9-861c-5662ab926d88.png)

**Comment by sootysax** [comment]
have you tried refreshing the courses on the course loading page?

**Comment by alpha117** [comment]
Morning,

Yep, just 'refreshed'  now, but they still remain

**Comment by alpha117** [comment]
User Error...again...sorry guys
