### ISSUE TITLE
issue for invert fieldcourse?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#3261]
Hello Guys
is it possible to invert a generated fieldwork course?
so if there is the first waypoint the last, and the last waypoint the first? 
i mean, i create a swath course, beginn with field/up/down driving and at least i round two rounds roundabout the field
when i came with the loaderwagon or the baler, i would like to beginn at the two rounds and the the up/down rows.
lg
andreas

**Comment by sootysax** [comment]
just generate the same course, but start with the up/down rows
