### ISSUE TITLE
Question:  Appended Course Start Waypoint

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#3263]
Now that I have got to grips with creating base courses and merging the ones to get me all around the map to every sell point, store etc etc. many thanks to **sootysax** for the help and advise on this.

When you append a course does CP always start at the start waypoint of the appended course or does it start at the nearest crossing point waypoint?

**Comment by sootysax** [comment]
the start point is the start point of the first course you load

**Comment by alpha117** [comment]
yep, understand that. Example field course with appended refill course. when it accesses the refill course does CP use the start waypoint or the nearest crossing point of the refill course

**Comment by sootysax** [comment]
you'll need to record a course entering and exiting the field

**Comment by The-Terraformer** [comment]
Alpha117 CP will drive the vehicle to the start point of the refill course, not the closest crossing point.

**Comment by alpha117** [comment]
thanks Guys
