### ISSUE TITLE
When using return to start point AI continues in circle at first turn

### ISSUE THREAD

**Issue by jhndrtxn** [Courseplay/courseplay#3264]
Attempting to use return to first point and start at selected point driver will continue up field then when called to turn and start first pass on field will continue circling until stopped and using start from nearest/ next closest waypoint

**Comment by pvaiko** [comment]
Read this like 3 times still don't understand.
https://github.com/Courseplay/courseplay/wiki

**Comment by jhndrtxn** [comment]
Try going to a field selecting a point to start from on map and enable return to start point, add a headland, and start on up/down rows then generate course. when the worker starts he will follow the route drive past the point where he should turn then try to reverse in circles trying to line up with that point

**Comment by jhndrtxn** [comment]
I've have noticed this issue on a few other scenarios  with the circling/ racetrack and spiral field centers which are an awesome addition for harvesters to keep pipe out of the crop but the worker searches for the next waypoint at the end of the row

**Comment by Messy71** [comment]
@jhndrtxn post some pictures with 
 generated course ( with the eye icon activateur in the course generation page, settings in the page settings combi mode) 

a picture when the problem happens with debugg channels 12,13,14 activated ( and a log with the same debugg  channels ).

**Comment by jhndrtxn** [comment]
Ok will do when I get off work

**Comment by jhndrtxn** [comment]
This is what i get when i start from first point with turn on field activated
![fsscreen_2019_02_20_10_24_47](https://user-images.githubusercontent.com/47084458/53103904-702e5b80-34fc-11e9-9fed-4bb8f9bb93f1.png)
![fsscreen_2019_02_20_10_24_23](https://user-images.githubusercontent.com/47084458/53103905-702e5b80-34fc-11e9-9816-f0247eecf432.png)
![fsscreen_2019_02_20_10_21_59](https://user-images.githubusercontent.com/47084458/53103907-702e5b80-34fc-11e9-8482-017ef5047027.png)
![fsscreen_2019_02_20_10_21_53](https://user-images.githubusercontent.com/47084458/53103909-702e5b80-34fc-11e9-9abc-125ef62ed6c7.png)
![fsscreen_2019_02_20_10_21_51](https://user-images.githubusercontent.com/47084458/53103910-702e5b80-34fc-11e9-99b2-bdc2e5539945.png)
![fsscreen_2019_02_20_10_26_12](https://user-images.githubusercontent.com/47084458/53103913-70c6f200-34fc-11e9-85cf-2b9a93ab61ba.png)

**Comment by jhndrtxn** [comment]
i need to start a clean log i had too many courses running at the time and is full of clutter

**Comment by pvaiko** [comment]
Is that a mod vehicle?

**Comment by jhndrtxn** [comment]
yes it is a mod vehicle

**Comment by pvaiko** [comment]
We are not able to deal with mod issues at the moment, please reopen if you can reproduce with a stock vehicle.

**Comment by Biker23** [comment]
![fs19](https://user-images.githubusercontent.com/30208621/55352619-310b0700-54b9-11e9-9e0e-80821c8b93ed.jpg)
![fs192](https://user-images.githubusercontent.com/30208621/55352620-310b0700-54b9-11e9-80a4-83a3b6662461.jpg)

Hello,

Just a quick one on this, I think I have this issue with a stock vehicle. I can only attach screenshots as I do not have much time on my hands, only saw on here that you can select spiral/racetrack and wanted to give it a go. Found the issue really funny to be honest.
In my case the generated course is cluttered. Seems like the combine will go to the next side without harvesting, only some bits and bobs there and there. The first combine will follow the generated course, but the second one is not able to turn and it will carry on till it gets stuck.

Thanks
