### ISSUE TITLE
Overloader Support Plans?

### ISSUE THREAD

**Issue by OhExcuseMe90** [Courseplay/courseplay#3265]
I understand that you brilliant people at courseplay are really busy fixing bugs and adding features but I was just wondering what the plans are for adding support for overloaders or auger wagons to courseplay 6

Thanks in advance

**Comment by Tensuko** [comment]
When the rest works as intended, they going to turn the next mode on and the fixing and tweaking starts over again. Step by Step.

**Comment by ThomasGaertner** [comment]
the overloader mode is based on the combi mode.  we are planning to refactor the whole combi mode and with this we will also reactivate the overloader mode .

**Comment by OhExcuseMe90** [comment]
Ok not a problem Like I said above I understand that the brilliant people at courseplay are busy fixing bugs and adding features, it was more a question of curiosity to find out the plans for the combi mode or overloader mode and you have both answered my question or curiosity.  It was a mode i used alot in the old version of courseplay and will probably be the same in this version once implemented. Also just want to say (while I have the chance) thanks for all the great work you do at courseplay because for me and probably alot of other people it has changed the way we play farming simulator and is an essential part of the game for me at least. Anyway enough rambling thanks for answering my question.

**Comment by Slimeon72** [comment]
You can use combi mode with an auger wagon until the overloading mode comes out, I've been doing it for a week or so now, it is possible if you set it up correctly.

**Comment by OhExcuseMe90** [comment]
@Slimeon72 I thought you could but for the life of me I cannot remember how I use to set it up to work right because I have not done it for a while. If remember correctly it involves the unload here button when recording the course.  Could you please let me know how you have set yours up? 

Thanks

**Comment by Slimeon72** [comment]
@OhExcuseMe90  I use the Kinze 851 which is 30k capacity  so I put a park at the semi trailer and use a wait time so it sets of again once unloaded. All you have to do is spend time sorting the crashes out. lol

**Comment by OhExcuseMe90** [comment]
@Slimeon72 Lol crashes with courseplay...... never........... Ok maybe sometimes lo. Thanks for that

**Comment by hombuilder** [comment]
any update on the overloading setting? I love using courseplay and really miss the overloader from fs17

Thank you
