### ISSUE TITLE
harvester not harvesting randomly but head still working 

### ISSUE THREAD

**Issue by Fusion9334** [Courseplay/courseplay#3266]
When harvesting, It will randomly glitch and no longer pickup/harvest the field although the combines head is down and everything seems in order. I have to stop the driver and continue and then it works fine again. 

Things I have noticed that may be helpful in narrowing down the cause.

1.) The same problem happens when using the in-game helper.
2.) combines harvest with no problems on a newly bought field. Maybe using CP to seed brakes it?
3.) I have seen this bug on all the maps and 3 different combines.
4.) using the seeding/cultivating/fertilizing combo as well as the seeding/cultivating implements.
5.) When this happens, and I let it go, the unloading driver tries to unload the combine as if it was at 50% when its only at around 20%. I thought that was interesting. 
6.) I have not tested it yet, but I'm thinking it may be related to the fact that I seed using the max amount of headlands to minimize the time when turning. But I use 2 combines when harvesting in Turn mode no headlands. Perhaps the different angles the seeder makes glitches the game or the harvester.

Running FS19 Version 1.2.0.1 (18001/20820)
CP Version (Unsure I downloaded the latest version from here on 2/16/2019 3:22 am EST)

#Thanks

**Comment by Bobster82** [comment]
I think its a game bug, I had it too... Its the fact that there are some old crops left on the same field, so he lets all go.
It helped for me to put crop withering on, never had any problem after ;)

**Comment by sootysax** [comment]
yes, has happened to me when there are old crops on the edges of the fields..  confuses the harvester..  you have to make sure you cultivate your fields entirely

**Comment by Fusion9334** [comment]
Yea, I tested it and can confirm that's what's happening. Thanks
