### ISSUE TITLE
Course generator behaviour when using Circle bypass islands 

### ISSUE THREAD

**Issue by GeorgeEarslight** [Courseplay/courseplay#3267]
The simple bypass detector works quite well, but not the circle. Shouldn't both detect the same?
Marwell F15 v00079 same settings on the generator apart from the bypass.
Which debug channels would you require?

![image](https://user-images.githubusercontent.com/30686125/53013692-0d32bb00-344f-11e9-8838-dbd04001257f.png)

![image](https://user-images.githubusercontent.com/30686125/53013809-466b2b00-344f-11e9-9571-1452db03f7d2.png)

**Comment by pvaiko** [comment]
Channel 7

**Comment by GeorgeEarslight** [comment]
[Course Generator Marwell F15 - Simple Bypass](https://gist.github.com/GeorgeEarslight/6f01e9864839e87ec3463e46abbf0a3c)

[Course Generator Marwell F15 - Circle Bypass](https://gist.github.com/GeorgeEarslight/b9a6420c2b811af5aff4c048f0012937)

**Comment by pvaiko** [comment]
Is this an updated version of Marwell? What is F15? The one I have (downloaded in the game) has no issues with these islands.

If you feel like experimenting you can try change the 5 in this line to -5 to disable that check:
https://github.com/Courseplay/courseplay/blob/d0c2671678ed7129a1e6a41561a099420bec26ce/course-generator/track.lua#L318
but I can't guarantee the result will be pretty with these tiny little polygons we have.

**Comment by GeorgeEarslight** [comment]
@pvaiko No, it's the original from ModHub. F15 is Field 15.
I'll try that code snipper next thing (the worker is fertilizing field 18 now).
I'm gonna also try to disable all the mods and see if anything changes.

**Comment by pvaiko** [comment]
> No, it's the original from ModHub

Don't understand then. I was playing on that field and that's what triggered my changes when driving on a circle around an island. Had no trouble generating it. Will check tonight at home.

**Comment by GeorgeEarslight** [comment]
Could also upload the save if you think it'd help.

**Comment by pvaiko** [comment]
The cultivator_density.gdm is all I need.

**Comment by GeorgeEarslight** [comment]
OK got something here.
Changed line 318 as per request nothing changed, BUT, when using Turn or Round headlands, I got the circle bypass.
No headlands or Smooth, doesn't generate the bypasses.

Tried again without the 318 edit and couldn't generate bypasses in any way,

**Comment by GeorgeEarslight** [comment]
> The cultivator_density.gdm is all I need.

https://we.tl/t-Q4Clh08CdV

**Comment by GeorgeEarslight** [comment]
@pvaiko Can attest solved, thanks.
