### ISSUE TITLE
Wilson Double bin trailer

### ISSUE THREAD

**Issue by stangman04** [Courseplay/courseplay#3268]
Any chance we may get support for dual bin trailers for grain transport and for combi mode chasebin offloading?

**Comment by sootysax** [comment]
#3265

**Comment by stangman04** [comment]
> #3265

Ah I forgot overloader mode is not released yet. That makes sense for that part. Would be nice to be able to offload both bins from a doublebin trailer in grain transport mode though.

**Comment by sootysax** [comment]
duplicate #3060
