### ISSUE TITLE
Game crashing when spraying

### ISSUE THREAD

**Issue by mredfloyd** [Courseplay/courseplay#3270]
Hi, My game started crashing 2 days ago when spraying with the NH 8340 with the Hardi Mega 2200 sprayer, usually when trying to switch from the tractor that is spraying to another vehicle
[log.txt](https://github.com/Courseplay/courseplay/files/2884694/log.txt)
It seems like the issue is with "Warning: Deleting object 'aiCollisionTrigger' before all triggers are removed" under "data/shared/assets/upperLinks/johnDeereUpperlink" and "walterscheid01" but im not sure

**Comment by Chris2996** [comment]
Pls try again with no mods except CP. Is the error still occuring?

**Comment by pvaiko** [comment]
Define 'crashing'.

**Comment by Chris2996** [comment]
"Warning: Deleting object 'aiCollisionTrigger' before all triggers are removed" as i understood appears to be printed when you buy/sell vehicles or something. I think i've read this here somewhere. Also warnings should not cause a chrash.

**Comment by mredfloyd** [comment]
Hi, Thanks for the fast replays, The game basically freeze for 1 second and just quits.

**Comment by mredfloyd** [comment]
Tried it now with only courseplay and Marwell Manor Farms activated and happaned again
[log.txt](https://github.com/Courseplay/courseplay/files/2884754/log.txt)

**Comment by mredfloyd** [comment]
Tried reproducing it on a new save game on both felsburn and MMF with all mods activated and could not make it crash again, Maybe my save file got corrupted?
And if so is there something to do to save it?
