### ISSUE TITLE
combine stops to refile while at end of row

### ISSUE THREAD

**Issue by totalstaples** [Courseplay/courseplay#3271]
Combine will call for refill and then stop with slipping error while perpendicular to the end of the field and will offload into courseplay trailer.  Trailer is then backed up and parked off field.  Combine will then continue on but trailer will no longer "find" combine

**Comment by totalstaples** [comment]
![end of field](https://user-images.githubusercontent.com/8403880/53105702-9acde380-34ff-11e9-993c-93739d9e5a6f.jpg)

**Comment by ThomasGaertner** [comment]
#3311
