### ISSUE TITLE
Horsch Pronto refill only fertilizer (not seed)

### ISSUE THREAD

**Issue by Martinnygaard** [Courseplay/courseplay#3272]
#3214 #3139 
This problem is likely related to the ones above.

I have the latest version (v6.01.00082) and this is still an issue for me (same seeder, excatly same setup)

Only difference, is that mine will accept Fertilizer, then close the lid and then drive right pass the seed tank without filling.
![courseplay1](https://user-images.githubusercontent.com/26490587/53108421-4a727800-3537-11e9-8d53-7640cb5734fe.png)

**Comment by ThomasGaertner** [comment]
The silos are too close to each other. I will think about how to make this possible. For now the minimum distance is the next silo must be in front of the tractor when it leaved the last fill trigger

**Comment by Messy71** [comment]
@Martinnygaard  I had the same problem i've spaced the silo and all works fine. Also you can test with another loop in the course recording for the seed (a figure 8 between the two silos ). Test it, see if it work's and close the issue if that fixes it.

**Comment by ThomasGaertner** [comment]
try with v.89 or higher and report

**Comment by RealFarmer** [comment]
Hello,

Now works perfectly.
Thanks for the work, used v.089

**Comment by RealFarmer** [comment]
Watch video,
https://youtu.be/6VZNo3PFSdc

**Comment by ThomasGaertner** [comment]
@Martinnygaard : what about you ?

**Comment by Martinnygaard** [comment]
I have not had the chance to test it yet (travelling with work).
I will get back to you ASAP.

**Comment by Martinnygaard** [comment]
It works! Thanks.
