### ISSUE TITLE
harvesters not moving any where -->combine convoy

### ISSUE THREAD

**Issue by mehdinasef** [Courseplay/courseplay#3273]
I set a course to harvest field 13 in In Istancia lapacho using 2 harvesters (7.6 meters each). I also used the combine convoy function to keep them far away from each other. then, I recorded a course for a tractor to empty the combins.
the problem happens when the first combine gets a full grain tank. When that happens, it stops and the second combine also stops ( this normally occurs when the tractor goes to unload in the silos). once the tractor comes back, it always starts emptying the second harvester and, when it is empty, the tractor waits for it to move away. that does not happen due to combine convoy and the hole set stops until i empty the first harvester myself. 
![combineconvoy](https://user-images.githubusercontent.com/47159754/53126491-85d56c80-3560-11e9-83a5-6eaa91c184a7.png)

**Comment by mehdinasef** [comment]
it happend to me several times

**Comment by ThomasGaertner** [comment]
Its a combi Mod thing to be concidered while refactoring it

**Comment by ThomasGaertner** [comment]
#3311
