### ISSUE TITLE
Slow working speed 

### ISSUE THREAD

**Issue by Martinnygaard** [Courseplay/courseplay#3274]
Courseplay version V6.01.0082dev

Hi,

i noticed today that 3 of 3 courses drove too slow.
The tractors is powerfull enough.
When CP is not activated, cruise control is set to 25kph, so thats not the reason.

Fertilizer is able to work at 20kph, but courseplay sets the speed to 14 kph
![courseplay32](https://user-images.githubusercontent.com/26490587/53146275-e33edd00-35a3-11e9-8cb7-18fc6dc381bd.png)
![courseplay3](https://user-images.githubusercontent.com/26490587/53146301-f3ef5300-35a3-11e9-91d7-395e0b7a4a71.png)

Sparyer is able to work at 12kph, but courseplay sets the speed to 9 kph
![courseplay22](https://user-images.githubusercontent.com/26490587/53146320-0ec1c780-35a4-11e9-81a7-92569dc28013.png)
![courseplay2](https://user-images.githubusercontent.com/26490587/53146322-12554e80-35a4-11e9-9016-a9a118950a0e.png)

also the weeder is able to work at 12kph, but courseplay sets the speed to 9 kph
![courseplay12](https://user-images.githubusercontent.com/26490587/53146330-1bdeb680-35a4-11e9-93e4-8ef4228a9fa3.png)
![courseplay1](https://user-images.githubusercontent.com/26490587/53146334-1e411080-35a4-11e9-8427-19dde4f1dc22.png)

**Comment by Martinnygaard** [comment]
It is not a courseplay bug.
It's the same when driving manually.

**Comment by Bobster82** [comment]
Maybe you need to repair ur vehicle ;)
