### ISSUE TITLE
Kleinigkeiten

### ISSUE THREAD

**Issue by derLocke** [Courseplay/courseplay#3275]
Mir ist aufgefallen das wenn das Rohr vom mähdrescher Richtung abgemähtem steht das dann die Meldung am abfahren..*Rohr Richtung frucht* steht. 
Kann es sein das deswegen der abahrer gerne dem mähdrescher im weg steht. Da er Mitte schwad Richtung stehende Frucht platz macht. 

(Das Problem kann auch vor dem Bildschirm hocken)

Und auf flustahl XXL erkennt er den verkaufspunkt von strohkraftwerk nicht.  (Ladewagen voller stroh) 

Version ist die 1.74 abfahren auf diversen Karten getestet. Mit Standart Fahrzeuge.

Wie gesagt nur Kleinigkeiten. Vielen Dank für die sehr hilfreiche mod.

**Comment by Tensuko** [comment]
Rohr richtung Frucht kann man um gehen, indem man beim Abfahrer die Fruchtumfahrung deaktiviert.
Fruchtzerstörung ist beim CP Fahrer aus, sieht zwar nicht schön aus, geht aber :)

Ich verstehe nicht ganz, was du mit 'Da er Mitte schwad Richtung stehende Frucht platz macht.' meinst.
Wenn der Drescher leer ist, fährt der Abfahrer auf eine Parkposition hinter dem Drescher, da sollte er nicht im Weg sein. Aktuell sind die Drescher aber auf Randale gestellt und könnte so einen Abfahrer auch mal zur Seite schieben oder wie bei mir das einemal auf die Seite kippen :)

Zu den Tiggern auf der Map kann ich nicht viel sagen, eventuell von der anderen richtung versuchen, oder was einige gemacht haben um die Anfahrgeschwindigkeit zu reduzieren, einen Wartepunkt vor dem Trigger gesetzt. Ansonsten braucht man mal ein Screenshot und Logfile mit Debug-Channel, aber ich weis leider nicht welcher benötigt wird.

Welche CP Version nutzt du ?

**Comment by derLocke** [comment]
1.00074 benutze ich. Er fährt auch hinter dem dreschen. Bleibt dann aber nicht mittig sondern meisten so das er leicht in der Frucht steht. Und den dreschen blockiert.

Werde mal von der anderen Seite anfahren. 

Danke für den tip

**Comment by derLocke** [comment]
Auf aktuelle version gewechselt da ist es auch noch so?
