### ISSUE TITLE
Kominierte Kurse der Abfahrer Stoppt

### ISSUE THREAD

**Issue by Moodijil** [Courseplay/courseplay#3278]
Hallöchen,

erstaml vielen Dank das es CP6 schon gibt und man damit schon fein Spielen kann.

Hier jetzt mein Problem:

Ich habe auf einem Feld die Strohschwad vom Drescher liegen und will diese mit einem Ladewagen abfahren lassen. Also habe ich den Kurs vom Drechser genommen und mit einem Abfahrerkurs zu diesem Feld Kombiniert. Der Lasdewagen wird auch beim Start voll geladen aber sobald er voll ist und zum Abfahren kommen soll fährt Stopt er vollständig und CP friert ein. Bin ich nicht gescheit genug oder ist das ein Fehler?

Ich habe auch mal die Log angehängt. :)

Vielen Dank schon mal. Trotzdem bisher Super Arbeit von Euch macht weiter so!
[log.txt](https://github.com/Courseplay/courseplay/files/2890469/log.txt)

**Comment by pvaiko** [comment]
Duplicate of #3276
