### ISSUE TITLE
Minor bug? CP crashes when in mode2 tractor frontloader is filled with grass

### ISSUE THREAD

**Issue by tjBerlin** [Courseplay/courseplay#3279]
Using CP version .00087, RAVENPORT, no mods. 

In combine mode (mode 2) cp crashes, when tractor has frontloader filled with grass. I guess, it crashes in that moment, when harvester is calling the CP driver. It is working perfectly without frontloader, therefore I guess, it is a not on high priority. 

![bildschirmfoto 2019-02-21 um 21 01 51](https://user-images.githubusercontent.com/24283753/53198529-e75b1100-361c-11e9-91b6-e87a5988fc2a.png)

Here is the log with dbg for mode 2 and 12.

[log.txt](https://github.com/Courseplay/courseplay/files/2891061/log.txt)

**Comment by ThomasGaertner** [comment]
#3311
