### ISSUE TITLE
Lag when you use the Fendt 1000

### ISSUE THREAD

**Issue by Moldhor** [Courseplay/courseplay#3280]
Lag when you use the Fendt 1000.
Every time the fendt 1000 is working, the frame rate of the pc is reduced a lot. I do not know why but the problem is the courseplay of the latest versions

**Comment by ThomasGaertner** [comment]
Log? What did the fendt work ?

**Comment by TomBos** [comment]
Seen this too, when cleaning/spraying the Fend and when attaching with (any) tool.

(Not using the Fend at this time)

**Comment by ride277** [comment]
Have this too. I had to sell the Fendt 1050 to continue my save. It was subsoiling on field 19 on marwell manor farm when the 1 frame/sec lag started.

**Comment by sootysax** [comment]
lots of me toos, not one log

**Comment by ThomasGaertner** [comment]
please press F2 to show the FPS and make a screenshot of the situation with CP Hud open Thanks

**Comment by Moldhor** [comment]
with other tractor and 6.01.00084 version the frame rate is 60
![fsscreen_2019_02_22_17_17_07](https://user-images.githubusercontent.com/40546830/53258844-e8984680-36cd-11e9-93ae-be932130ad1a.png)

With Fendt 1050 the frame rate is very low 
Just 3 fps !!!!
![fsscreen_2019_02_22_17_35_09](https://user-images.githubusercontent.com/40546830/53258958-390fa400-36ce-11e9-9894-aeb7bb1394c7.png)

But use old version (6.01.00038) with Fendt 1050 the Frame rate is 60
![fsscreen_2019_02_22_17_38_48](https://user-images.githubusercontent.com/40546830/53259168-bdfabd80-36ce-11e9-8db6-3f28d51cdd9e.png)

**Comment by El-Taco** [comment]
I've got this problem, too. Whenever I move the Fendt 1050, my framerate drops to 21-26 fps. Tried it in another savegame and I didn't have any issues there.
This happens every time I use the Fendt, even when I drive around without a CP course activated.

**Comment by MaLouPa** [comment]
Well, i´m still having this Problem with v209/210 etc.

any tips for me? Issue comes when i load the first Course and start it. Suddenly my FPS drops from 60 to under 20.

**Comment by Tensuko** [comment]
Logfile pls.

**Comment by Tensuko** [comment]
Closed due to inactivity.
Reopen if post logfile and more Infos.

**Comment by JoaoRabit** [comment]
What's the locetion of the logfile?

**Comment by Tensuko** [comment]
Version, Used Mods, Mod Errors and if needed debugchannels.
The Fendt should actually been fixed, but somehow the fix doesn't rly work.
As the last Team Talk, it is more a base Problem of the Fendt, so it is more a GIANTS Problem.
Can't do much that right now, sadly.

**Comment by JoaoRabit** [comment]
Ok thank you for the answer, I'm not sure if you're aware but the New Holland T9 also has the same lag problem.

**Comment by Tensuko** [comment]
Ok, will take a look.
