### ISSUE TITLE
Few error i notice for next update maybe

### ISSUE THREAD

**Issue by bibifr** [Courseplay/courseplay#3281]
Hello this is a little list of error i could notice on Current version of CP

* Combine do not unload If pipe is in fruit and Full Untill you Activate the option to run into Fruit for unload
* Mode 3 has not collision working system When 2 Tractor run to Silo they push each other whitou collision
* Mode 4 and 6 Now Running out of Field whitout reason and get stuck in Tree

That a few i noticed Atm 

Hope may help

**Comment by sootysax** [comment]
wheres your log

**Comment by Tensuko** [comment]
Nothing new, look arround in GitHub a bit for those things. Close pls.
