### ISSUE TITLE
Refill Course ( Again )

### ISSUE THREAD

**Issue by sesmo** [Courseplay/courseplay#3283]
The reffil course dont work with  seed hawk 980 air cart....

I remenber that ill work in older versions of courseplay ( about a week ago)

Every other implements that i use work fine, with no issues.

RP

![2019-02-22 6](https://user-images.githubusercontent.com/25755540/53264279-221f8080-36d3-11e9-8771-167a9010cab2.png)

**Comment by sesmo** [comment]
I forgot: The trigger was detected, but don´t fill with seeds or fertilizer...

**Comment by sootysax** [comment]
you also forgot to attach a log

**Comment by sesmo** [comment]
@sootysax  Done;

You can find the map, all the mod of storage and courseplay couses here: 

https://defogomao-my.sharepoint.com/:u:/g/personal/admin_defogomao_onmicrosoft_com/EXSRY9X-B8NOuWFEUhHQbZcBri5RreLEtum-nAmEVXgkHQ?e=WUuZZx



[log.txt](https://github.com/Courseplay/courseplay/files/2896763/log.txt)

**Comment by sesmo** [comment]
Another issue that i notice now.... We the silo is empty the driver continues without refiling. .. ( in all the implements )

**Comment by Innallas** [comment]
Hey personnally i put Waiting Point at the place where he need to refill , with the job Seed&Fertilize he will wait without waiting you or warning you.

**Comment by sesmo** [comment]
Hi @ThomasGaertner Sorry to come back with this question, but is possible to make automatic refill for seed hawk 980 air cart? If no we can close....

I remenber it work fine in FS17, and some older versions of the courseplay for FS19....

Anyway I make a video and a new log file:

 https://youtu.be/iPb9lq8OApQ

There´s also the question when the silo is empty the driver continues without refiling. .. ( in all the implements ) bus this is a minor issue for me.
[log.txt](https://github.com/Courseplay/courseplay/files/3076208/log.txt)

**Comment by ThomasGaertner** [comment]
it is the following problem: the air cart fill elevator must be opened and selected to the right thing (fertilizer or seed) before it reaches the trigger (you can see it in 00:27 in your video) so we have to stop and hit this small trigger with the elevator of the air cart which has to be opened BEFORE we are reaching the trigger. the common tools are opening their covers WHILE they are in the trigger so no chance for the air cart without an own script. This would be very low on our prio list. so I will be a wont't fix sorry

**Comment by sesmo** [comment]
ok @ThomasGaertner I understand... 

For solve this question I make a waiting point and them refill manualy, but some reason most of the time the tractor passes without stop... When I make the video it stops but is a exception....

I leave this open, but you can close , no problem...
