### ISSUE TITLE
New traffic ai - Question/suggestions

### ISSUE THREAD

**Issue by fudoido** [Courseplay/courseplay#3286]
As many have already have seen, the new traffic AI stops when a "worker" is making a turn on the field near a road, and a car is coming nearby.
this also affects how courseplay works, because the game identifies courseplay helpers as a worker too.
at start i thought it ws a nice feature, however while using CP now, i see that traffic also stops even when the worker is behind them, forcing CP to stop behind the ai vehicle.
i know i can just turn of ai traffic, but i always prefered to keep it on for some more realism (even tho cars going slower than a tractor is not very realistic).
is there any way to go around this giants ai feature in the future? or will it be too much of a headache and better to just turn traffic off all the time?
i know that if we are not focused in that area of the map, the ai vehicle ends up to de-spawn and CP will resume, but although it seemed a nice feature to prevent machinery getting interrupted by traffic while turning out of fields, it gets annoying for cp features.

**Comment by Tensuko** [comment]
Not happening anymore, can't reproduce or simply fixed.
