### ISSUE TITLE
BGA Schieben

### ISSUE THREAD

**Issue by Tommypz** [Courseplay/courseplay#3287]
Gibt es die möglichkeit schon das mann im BGA schieben kann?

**Comment by Tensuko** [comment]
Option ist noch nicht aktiviert (wie man im CP Menü sieht) und damit geht es noch nicht.
Komm später.

**Comment by Tommypz** [comment]
So ein Mist aber auch schade

**Comment by Paul2510** [comment]
Coursepaly befindet sich am Anfang! Es geht nicht alles auf einmal da alles neu gemacht wird und angepasst werden muss! Dann sind es ja auch nur Menschen mit Familien! Also am besten geduld haben und Tee trinken!
