### ISSUE TITLE
Helferkosten

### ISSUE THREAD

**Issue by petduddel** [Courseplay/courseplay#3288]
Habe mal eine frage, mir ist aufgefallen das keine Helferkosten für Courseplay abgezogen werden, obwohl es in den CP Settings aktiviert ist.... ist das noch ein fehler ?

**Comment by game455** [comment]
... mal abgesehen davon, dass 15€/std. (meinetwegen auch 50) weitaus realistischer als 1500€/Std. wären

**Comment by KenStumich** [comment]
> ... mal abgesehen davon, dass 15€/std. (meinetwegen auch 50) weitaus realistischer als 1500€/Std. wären

der helferpreis wird sich am giants-helfer orientieren  und dieser wird wohl im sinne des spielspasses (von seiten giants) gesetzt. die ingame zeiten sind ja auch nicht realistisch
