### ISSUE TITLE
tractors turning around in a circle forever

### ISSUE THREAD

**Issue by mehdinasef** [Courseplay/courseplay#3290]
I had a tractor seeding one of my fields. I set it to start with the up/down rows and then, the headlands. it did pretty well in the up/down. However, when it finished the up/down rows and was going to begin the headlands it started turning around in a circle for a long time until I stopped it and aligned it with the headland that it was going to seed.
this sometimes happens to a tractor that is in combi mode and trying to align itself with a combine harvester that has stopped because its gain tank is 100% full.
I do not know much about how coursepaly works but I think this is an alignment problem.

![turning](https://user-images.githubusercontent.com/47159754/53288986-32e1fc00-3790-11e9-9ee5-8458802f7ac9.png)
![turningaround](https://user-images.githubusercontent.com/47159754/53288990-3b3a3700-3790-11e9-94d8-3abc729aa705.png)

**Comment by pvaiko** [comment]
Can you get me a savegame and the course for this?

**Comment by mehdinasef** [comment]
I have got the save game but i didn't save the course

**Comment by mehdinasef** [comment]
i can create it again

**Comment by mehdinasef** [comment]
i'll be back in 10 minuts

**Comment by mehdinasef** [comment]
I have created the same course with the same settings but I don't know which one it is

![coursesfolder](https://user-images.githubusercontent.com/47159754/53289285-835b5880-3794-11e9-8400-d7d9611f6d75.png)

**Comment by pvaiko** [comment]
Look into courseManagement.xml it'll tell you.

**Comment by pvaiko** [comment]
Or just send them all and let me know the name of the course.

**Comment by mehdinasef** [comment]
it did not let me upload the folders in here, that's why I'm used drive

save game:

https://drive.google.com/drive/folders/1a3OmEcVQ7aYoVkL-sU3RcY_V539gIHK5?usp=sharing

courses:

https://drive.google.com/drive/folders/1LQi4JzInutOnqOdEU1PWyrK6h1X6IInr?usp=sharing

**Comment by mehdinasef** [comment]
the course name is: F13 seeding

**Comment by mehdinasef** [comment]
> the course name is: F13 seeding

sorry, it is F3 seeding

**Comment by mehdinasef** [comment]
the course is for field 3 even though I named it F13

**Comment by pvaiko** [comment]
Ok, this is similar to #3255, and will not fix it at this moment. I'd recommend using the smooth or round headland corners or, if you have to use the turn maneuver corner start your course further away from the corner.

**Comment by mehdinasef** [comment]
ok, thanks.

**Comment by mehdinasef** [comment]
should i close his issue??

**Comment by pvaiko** [comment]
No, thanks, leave it, this is a slightly different scenario, I'll need it when I fix this.

**Comment by pvaiko** [comment]
For those who want and who know how to do it, you may give the improved headland turns a try. This is on the separate headlandturns branch (https://github.com/Courseplay/courseplay/tree/headlandturns)

Still not pretty for this issue but at least it does not get stuck

**Comment by OmgBrother** [comment]
I see what is making theses errors , when you arrive to the green dot for turning manoever and look in front of you > check the angle of the turn to the red dot.
If the angle > 90 >> tractor/combi turn in loop

You can also use "counterclockwise" depending of your field, on somes field it revert all turns to be < 90 and all work nice.

In fact it's not only a problem about headland turns, it also do this for all up/down circuits inside the field , even using lifted corner (i always use this), inside field if angle between green&red waypoint nodes is > 90 it will make him turn in loop.

**Comment by pvaiko** [comment]
This really should not happen anymore
