### ISSUE TITLE
Pattern Center-Mode-Circular Question

### ISSUE THREAD

**Issue by KenStumich** [Courseplay/courseplay#3291]
I played around with  Center-Mode-Circular and can not see why it should used at all.

![center_mode_circular](https://user-images.githubusercontent.com/28400454/53289259-3d9e9000-3794-11e9-8c2b-9bd28c65f6d7.png)

as you can see , half of the time the pipe is in the fruit (yellow)  and the other half not (green). 
if i imagine a very long field expandet to the south/north  there is no difference to the normal up/down pattern in terms of unloading the combine.

maybe somone could give me a hint why this was introduced in the fist place

**Comment by pvaiko** [comment]
https://github.com/Courseplay/courseplay/issues/2923#issuecomment-456170425
