### ISSUE TITLE
Combi Mode

### ISSUE THREAD

**Issue by dsn005** [Courseplay/courseplay#3292]
I set up the combine path and the overload tractor path. When I tell the overload tractor to drive the course it freezes up. When I tap ESC no other implements show on the map. I can use the tabs across the top but the info is wrong. If I try to save the game everything freezes and I have to End Task in Windows 10. I have tried starting the combine first then the overload tractor, no luck.

Am I doing something wrong?

**Comment by hanrahs** [comment]
Same issue for me, but only occurring on some maps with some vehicle, If I set up a truck to run the same combi mode using the same already saved routes it will run fine

**Comment by sootysax** [comment]
#3140 please read

**Comment by ThomasGaertner** [comment]
#3282
