### ISSUE TITLE
Problem mit dem Tiefenlockerer

### ISSUE THREAD

**Issue by Strawberry93** [Courseplay/courseplay#3293]
Ich habe ein kleines Problem. Bei dem Bahnenwenden fängt der Helfer immer 1-2 m zu spät an den Lockere zu senken. Dies ist bei allen 3-4 m Tiefenlockerer der Fall. Wie kann ich das Einstellen damit er genau am Feldrand beginnt oder ist das noch ein Bug vom Spiel?

**Comment by sootysax** [comment]
how are the developers supposed to help you when you post no log, and they have no idea what version of CP you are using?  

https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
Funktioniert mit V157 und Combiplow Gold 3M.
![fsScreen_2019_03_30_15_57_56](https://user-images.githubusercontent.com/27344744/55277850-e3e63400-5304-11e9-858b-11ffba75180b.png)
![Uploading fsScreen_2019_03_30_15_57_59.png…]()

**Comment by pvaiko** [comment]
closed due to inactivity.
