### ISSUE TITLE
Speed in BGA silo

### ISSUE THREAD

**Issue by Stezil** [Courseplay/courseplay#3294]
I tested the BGA silo in CP and the tractor is driving at high speed. Speed ​​can not be set. 
It would be best to use rotational speed.
I only use the original machines and the map Neubrun. CP <version>6.01.00092</version>

**Comment by jerramywinches2** [comment]
I noticed this same bug. I noticed the speed was related to the reverse speed. i.e if you lowered the reverse speed as it went through the silo it would slow down. Couseplay seemed to reset the reverse speed to 17 km/h just as it entered the silo.  I think if the reset didn't happen the speed would be fine.

**Comment by KenStumich** [comment]
this is not always the case. if you use a medium size silage-silo the speed is 10 but häs to be 8 or 7

its somehow connetet to the reverse speed (you can adjust it on the fly while the tractor is in the silo trigger)  and i think this will be adjust in the next mode 2 version.

**Comment by panther5** [comment]
https://youtu.be/i-ygRH7r-Uo

that way ?
it only stopped because of the Fence the Driver hits.
no matter with or without Mods.

recorded with 15km in Pit

**Comment by Gadarol** [comment]
same issue here (.00117.dev)

**Comment by KenStumich** [comment]
@panther5 
weil du auf deutsch spielst hier mal ausnahmsweise in deutsch
zeichne eine kurs auf der durch das offene silagesilo führt  ( geschwindigkeit egal ).
wenn du nun in mode1 (beladen am startpunkt) oder mode 2 (abtanken und abfahren) durch dieses silo fährst schaust du auf das curseplay fenster (geschwindigkeit ausgewählt) und wirst feststellen, das CP sobald es den trigger vom silo erkennt (infozeile unten links ) auf einmal die geschwindigkeit für die rückwärtsfahrt ändert. jetzt mit der maus sofort umstellen auf ca 13 für grosse oder ca 8 km/h für mittlere durfahrtssilos. (der trecker fährt dabei weiter) das sollte dir helfen. musst du jedesmal machen wenn er durchfährt.

**Comment by panther5** [comment]
i will look and try.

**Comment by ThomasGaertner** [comment]
Ist das mit der aktuellen Version in Mode 1 oder 6 noch ein Thema ? Ich hab das komplett überarbeitet in V.112

**Comment by Gadarol** [comment]
Will test mode 1 & 6, we are talking mode 2 though...

**Comment by ThomasGaertner** [comment]
@Gadarol  #3311 :-)

**Comment by Gadarol** [comment]
Interesting, since mode 2 works quite well for me exept the speed issue in BGA silo. Would a hard max speed limit in manual speed option settings be a workaround option for now?

**Comment by ThomasGaertner** [comment]
It's not a question of function, its a question of maintainability. The code has been developed by many people over years, so there is no structure in it.  
Ok, when I fix #3006, i will copy the solution to the old code

**Comment by ThomasGaertner** [comment]
Ok I think I got the problem. try v.127 or higher and report

**Comment by KenStumich** [comment]
works like a charm for me. 
ravenport bga
krampe trailer 56 000 liter 
joskin trailer  31 000 liter

both around 13-14 km/h in the silage silo and tipping smooth from one end to the other 

thx thomas

**Comment by panther5** [comment]
ok, tested on Brook Modmap (Modhub)

works

i was shocked :)

**Comment by Gadarol** [comment]
Looking good, thank you :)
![looking_good](https://user-images.githubusercontent.com/12459293/54112387-53dc5b00-43e6-11e9-89dc-bff254d48d1f.JPG)

**Comment by KenStumich** [comment]
@ThomasGaertner  @Gadarol 
I only had the big silo on ravenport.
I could not test a medium size silo there and unfortunately it does not work with the unloading length.
As I see in the picture, Gardarol plays on NF march.
please try the mid-size-silo there. It is a built-in standart silo, so it should be enough for testing.

**Comment by panther5** [comment]
.127 worked for me in Ravenport BGA in Mode 2 ! 👍

**Comment by KenStumich** [comment]
for testing its faster to fill up a trailer and build a course  around a med silo. (circle ) test it with mode 1 and it skipps the loading if you are alredy full.

**Comment by panther5** [comment]
nah, will test it this way ^^
mode 6 (filling with fresh grass ) worked in .120 already

**Comment by KenStumich** [comment]
v 0127 / mode 1 / map NF-Marsch (not official mod map , but standart silo )
this are my results.

med size silo

![fsScreen_2019_03_11_23_18_35](https://user-images.githubusercontent.com/28400454/54162452-ce908f00-4455-11e9-84f9-f8675d63c9f4.png)
![fsScreen_2019_03_11_23_18_38](https://user-images.githubusercontent.com/28400454/54162458-d18b7f80-4455-11e9-9b64-befcd3cb5d53.png)
![fsScreen_2019_03_11_23_18_41](https://user-images.githubusercontent.com/28400454/54162461-d3edd980-4455-11e9-83c9-3dea32eee117.png)
![fsScreen_2019_03_11_23_18_47](https://user-images.githubusercontent.com/28400454/54162465-d6e8ca00-4455-11e9-9bef-ff436a6f0ed6.png)
 

but the big size works as described beforhand.

![fsScreen_2019_03_11_23_25_56](https://user-images.githubusercontent.com/28400454/54162540-17484800-4456-11e9-8c7b-f1fafc9e13d1.png)
![fsScreen_2019_03_11_23_26_10](https://user-images.githubusercontent.com/28400454/54162545-1a433880-4456-11e9-8df3-3291b92cf1b0.png)

as you can see, the drive trough speed is to high in the med size. around 14 in the big size and in the med size you can see speed up to 25. tipping point is detected in both but there must be somthing else.

**Comment by ThomasGaertner** [comment]
I will close here an keep tracking it in #3006
