### ISSUE TITLE
Harvester wont run tracks, Error: Running LUA method 'mouseEvent' (triggers.lua:486)

### ISSUE THREAD

**Issue by adorhun** [Courseplay/courseplay#3297]
hi!
got the v94 to test if silo unloading works.

im on riverview v2. lined up to a field, generated the course for the harvester. when i press run, the arrow for pointing to waypoints comes up and the vechicle remains stationary. vechicle inspector shows !blocking!, the vechicle is inoperable.

paste: https://pastebin.com/fBX2Zn1S

paste with debug channels on: https://pastebin.com/ACcq1kRF

ill test it on my felsbrunn save.

**Comment by adorhun** [comment]
No problems on Felsbrunn.

**Comment by donnti** [comment]
I had the same thing happened to me with both liquid and solid sprayer/spreaders. At first, I loaded up a saved course from version .92 then I created a new course with the same outcome. I ended up to hit the hired help key a couple of times to get control back.

**Comment by Innallas** [comment]
I got same troubles too but i noticed it happen often after i buy modification on the vehicle, like it reset/create new vehicle object and the object in mouseEvent become null ?

**Comment by Ntone107** [comment]
Comparable problems - https://github.com/Courseplay/courseplay/issues/3315
Map: FS19_FarmerToine, WIP Map made by myself.

**Comment by ThomasGaertner** [comment]
@Ntone107 : what is the name of the bunkersilos TriggerId  in your Map ?

**Comment by Ntone107** [comment]
There are no bunkersilos in the base map, but come to think of it, i'm thinking the problems started after buying and installing bunkersilos from the store.

Gonna test with a new savegame, before and after installing bunkersilos.

**Comment by Ntone107** [comment]
@ThomasGaertner tried with new savegame.

Had 4 CP courses running, 3 combi transport, 1 sprayer. No problems.
Bought and placed 1 bunkersilo, problem as described above reappeared. 
Other bug; engine sounds become crackling noises instead of normal sounds.

    <item className="BunkerSiloPlaceable" id="1" filename="data/placeables/bunkerSilo/bunkerSiloLarge.xml" position="-39.0000 50.1104 591.0000" rotation="0.0000 0.0000 0.0000" age="0" price="45000.000000" farmId="1">
        <bunkerSilo index="1" state="0" fillLevel="0.000000" compactedFillLevel="0.000000" fermentingTime="0.000000" openedAtFront="false" openedAtBack="false"/>
    </item>

**Comment by ThomasGaertner** [comment]
whats the status here with the current version ?

**Comment by adorhun** [comment]
its working fine.

they just get stuck on the hedge around the fields 😁
