### ISSUE TITLE
Game Crash/ Wont Save Game

### ISSUE THREAD

**Issue by cjn2** [Courseplay/courseplay#3298]
When I am running a CP, and try to manually or when the game automatically saves, the game crashes and when I load the game again, the save game is lost.

LOG: https://gist.github.com/cjn2/760ca9a77c4a775e91981dc9638bc148

v6.01.00094

Any map Ive tried

Mods: Lots, all mine are from facebook, modhub and modland

**Comment by sootysax** [comment]
you need to get rid of all of the MANY mods with errors and try again...

**Comment by cjn2** [comment]
ill try that

**Comment by ryanfur** [comment]
do you know any mods that conflict

**Comment by Thundermuffin645** [comment]
I also am having the same problem i deleted all mods and deleted FS19 and reinstalled still happening. sometimes i can play and save games for several hours before it locks up on save and after a hard shut down my game is gone.
