### ISSUE TITLE
Sale of bales with Arcusin.

### ISSUE THREAD

**Issue by RealFarmer** [Courseplay/courseplay#3300]
Collecting and selling goes well with the Arcisin, has to put a sales point. After unloading and selling the bales the tractor drives back to the field at a speed of 10km (see photos)
Usedv.0.94.
thank you for working.
regards
![fsscreen_2019_02_25_12_30_13](https://user-images.githubusercontent.com/46776331/53335307-6b521900-38fb-11e9-9a51-8736f78fd88d.png)
![fsscreen_2019_02_25_12_30_31](https://user-images.githubusercontent.com/46776331/53335320-7147fa00-38fb-11e9-988a-46cf46a84e76.png)
![fsscreen_2019_02_25_12_31_42](https://user-images.githubusercontent.com/46776331/53335326-7442ea80-38fb-11e9-9fc8-85ca4316e559.png)

**Comment by RealFarmer** [comment]
If you then stop Course Play and then start again, drive the tractor at normal speed.
I forgot to report.

regards

**Comment by Tensuko** [comment]
#3157

**Comment by pvaiko** [comment]
That seems to be an issue with the trigger, can you post a log with debug channels 1, 12 and 14?

**Comment by ThomasGaertner** [comment]
@pvaiko : do you reset the trigger after unloading ?

**Comment by RealFarmer** [comment]
The speed after full charging is also not good, then drive the max speed over the field.

regards

**Comment by sootysax** [comment]
Use GIST to post your log instead of pasting the whole thing in the issues 

![screenshot 2019-02-25 15 21 13](https://user-images.githubusercontent.com/6591048/53366221-0f928a80-3911-11e9-9088-51763c922abd.png)
