### ISSUE TITLE
Samson and Zunhammer Always nees refill when using digestate

### ISSUE THREAD

**Issue by PeterWeessies** [Courseplay/courseplay#3303]
When using the zunhammer or samson slurry tank, with the cultivator or spreader attachment, always say work tool needs to be refilled on Fertilezer mode. All in one slurry spreaders like the joskin work fine, but when it's a separate tank and spreader attachment it does not work.

![image](https://user-images.githubusercontent.com/1321261/53360396-b8eb7780-3935-11e9-967a-e0c67786e503.png)

**Comment by pvaiko** [comment]
Can you post a log with debug channel 14?

**Comment by PeterWeessies** [comment]
Made a clean log, disabled all mods exept courseplay, and tried again. 

`2019-02-25 20:06 :42 [dbg14 lp4300] 8400 R (#1): PG II 35: Fill levels: DIGESTATE: 34500.0/34500.0
2019-02-25 20:06 :42 [dbg14 lp4300] 8400 R (#1): SD 700: Fill levels: LIQUIDMANURE: 0.0/0.0`

It seems it's looking for the fill levels of the implements, which off course don't have a tank, and fails.
https://gist.github.com/PeterWeessies/91ed3fc338d7697287d4e294762917ed

**Comment by PeterWeessies** [comment]
Test 2: instead of using digestate i used slurry, and it's working fine

`2019-02-25 20:19 :52 [dbg14 lp43800] 8400 R (#1): PG II 35: Fill levels: LIQUIDMANURE: 31746.9/34500.0
2019-02-25 20:19 :52 [dbg14 lp43800] 8400 R (#1): SD 700: Fill levels: LIQUIDMANURE: 0.0/0.0`

So it only occurs when using digestate (which i would like to use, and sell my slurry)

**Comment by pvaiko** [comment]
Thanks for the concise bug report.

**Comment by PeterWeessies** [comment]
That was an really easy fix
