### ISSUE TITLE
Harvester is moving with 0 to 3 km/h when it should stop because it is full.

### ISSUE THREAD

**Issue by Hmmvee** [Courseplay/courseplay#3304]
This seems to be again a problem with latest version. I think that was solved in the meanwhile.

![fsscreen_2019_02_25_22_14_18](https://user-images.githubusercontent.com/46241969/53369194-f4447100-394a-11e9-8ad2-ababd6c0ff8f.png)

![fsscreen_2019_02_25_22_03_40](https://user-images.githubusercontent.com/46241969/53369231-0cb48b80-394b-11e9-87b8-a80e50a4126d.png)

![fsscreen_2019_02_25_22_03_42](https://user-images.githubusercontent.com/46241969/53369235-0e7e4f00-394b-11e9-8c29-5ffc9d8d435a.png)

**Comment by ThomasGaertner** [comment]
#3311
