### ISSUE TITLE
A Question

### ISSUE THREAD

**Issue by Sualk1972** [Courseplay/courseplay#3306]
Hello Mr. Gaertner, it is possible because Abfahrer the direction to program that he only turn the thresher left to drive away. Can you insert this. Thank you

**Comment by Tensuko** [comment]
Versuchs nochmal auf Deutsch :)
Zur not übersetzt das wer ins Englisch.

**Comment by Sualk1972** [comment]
Hallo Thomas Gärtner kann man den Abfahrer von einem drescher oder Roder das Kommando einstellen das  der Abfahrer den Drescher oder Roder immer links davon Abfäht wenn dieser voll ist.Mdg

**Comment by Tensuko** [comment]
Bin zwar nicht T.G. aber antworte trotzdem mal ^^

Im Grunde findet der Abfahrer das Rohr von alleine und entscheidet von welcher Seite der Abfahrer ranfahren muss.
Gibt es denn ein Problem ? Oder meinst du Häcksler ?

**Comment by ThomasGaertner** [comment]
ich sammle grad Ideen für den neuen combi mode #3282. Ich hab das Problem noch nicht ganz verstanden. aber wenn es das noch nicht gibt, was Du möchtest, dann bitte dahin. verständliches Deutsch können wir dann schon übersetzen :-)

**Comment by KenStumich** [comment]
ich nehme mal an, das der hänger voll war und der abfahrer direkt auf den startpunkt des abfahrkurses zugesteuert hat. das kann schon mal mitten durch den Ernter gehen .  aber wie "Herr Gaerter" schon erläutert hat, arbeiten sie gerade an einer neuen version.
