### ISSUE TITLE
Worker does not stop when slurry/manure source runs out

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3309]
When you set the option for a slurry or manure (cows or pigs) to be automatically used by the hired worker, when that source runs out, the worker continues the course, but does not spread any manure/slurry (even if the tank is full).  

If it is not possible when the source runs out for CP to either : 

switch the source of refill (to a different animals slurry pit)
or 
switch to use what is in the tank

then CP should stop the vehicle until a new source can be selected

https://gist.github.com/sootysax/9fd112e7a3c4436aa9c0f02903766da2

![fsscreen_2019_02_26_13_25_46](https://user-images.githubusercontent.com/6591048/53436854-1b8e5300-39ca-11e9-8204-998876fadabb.png)

![fsscreen_2019_02_26_13_21_39](https://user-images.githubusercontent.com/6591048/53436696-c5b9ab00-39c9-11e9-9c53-dcefe04164bc.png)

![fsscreen_2019_02_26_13_22_31](https://user-images.githubusercontent.com/6591048/53436705-ca7e5f00-39c9-11e9-898d-3557efb18279.png)
![fsscreen_2019_02_26_13_22_36](https://user-images.githubusercontent.com/6591048/53436711-cd794f80-39c9-11e9-9119-0a79d5f53b5b.png)

**Comment by pvaiko** [comment]
Debug channel 14 would be needed for fill levels, I don't see any relevant dbg14 entries in your log. And please, turn off channel 1.

**Comment by PeterWeessies** [comment]
Maybe Off-Topic, but how did you get the option to choose marwell cows for slurry, i only have the option off and buy, other options seems to be gone, even on vanilla maps

**Comment by sootysax** [comment]
Course will not start with Marwell Cows as helper refill - slurry selection unless there is something in the tank..  it will say 'tool needs to be refilled'.   If the option is set to 'Buy' the vehicle will run the course.

I put a little bit of slurry in the tank, and then set option to 'Marwell Cows' and the course runs.  Spreads slurry until cows slurry pit is empty, and then continues the course without spraying or using the slurry in the spreader tank.

https://gist.github.com/sootysax/a46277531ece80fd04f7d615f986febc

**Comment by sootysax** [comment]
> Maybe Off-Topic, but how did you get the option to choose marwell cows for slurry, i only have the option off and buy, other options seems to be gone, even on vanilla maps

@PeterWeessies  I don't know.. it's just there as an option, as well as the South View Farms pigs slurry.   Unfortunately, the Digestate from the BGA is NOT available

**Comment by pvaiko** [comment]
@sootysax would you type 
`print g_currentMission.missionInfo.helperSlurrySource`
in the console and paste the result in here?

**Comment by sootysax** [comment]
2019-02-26 23:27 g_currentMission.missionInfo.helperSlurrySource - nil
2019-02-26 23:27 Printing g_currentMission.missionInfo.helperSlurrySource (number), depth 1
2019-02-26 23:27 g_currentMission.missionInfo.helperSlurrySource: 4

**Comment by pvaiko** [comment]
Don't have time now but if you want, you can try to change that == 2 to >= 2 here:
https://github.com/Courseplay/courseplay/blob/4cbf56bcb29c76171bf54cf6761c62d0067c634b/FillableFieldworkAIDriver.lua#L104
