### ISSUE TITLE
#97  AI Traffic issues

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#3310]
Catches traffic and due to AI stopping as you approach and then you get this:

![image](https://user-images.githubusercontent.com/30005040/53438952-e6e5c000-39f8-11e9-874c-19e63cb446f9.png)

**Comment by ThomasGaertner** [comment]
you shouldn't be in normal mode, how did you get there ?

**Comment by alpha117** [comment]
normal mode? I just loaded/merged courses and then started it...what have I done wrong?

**Comment by ThomasGaertner** [comment]
![53438952-e6e5c000-39f8-11e9-874c-19e63cb446f9](https://user-images.githubusercontent.com/3279913/53440557-1dc1d300-3a05-11e9-86f1-2e946559f8c9.png)
there should be "AIDriver" it shouldn't change to normal mode, can you click on it to change ?
can I have a log?

**Comment by alpha117** [comment]
![image](https://user-images.githubusercontent.com/30005040/53440939-9de43a80-39fd-11e9-9069-15be4603b61e.png)
[log.zip](https://github.com/Courseplay/courseplay/files/2907206/log.zip)

Had to change 'mode' and then back to transfer and AIDriver appeared...strange one

**Comment by ThomasGaertner** [comment]
no it works ?

**Comment by alpha117** [comment]
yep, all good
