### ISSUE TITLE
the new mode2 (combi mode) is WIP, no support for the old one from now

### ISSUE THREAD

**Issue by ThomasGaertner** [Courseplay/courseplay#3311]
hello dear tester,
if your issue has been referenced here, you issued a problem with the obsolete version of combi mode.
We started working on it but since it's the most complex mode, it will take some time to be beta ready.
so please be patient. Please consider also the time we spend for answering issues, ist lost for developing.
Thanks for  understanding 
courseplay.devTeam 

---

**See** #4286 **for Updates!!**

**Comment by Innallas** [comment]
By the way i noticed that mode 8 (liquid prod transport) is not needed anymore because it's working well with the mode 1 in fact :) (im using it to reload animal water / fill milk house & a final tour transporting milkhouse to sell station)

**Comment by pseikoNL** [comment]
@innallas, as Thomas mentioned in the title of this thread this is about mode 2, so not about mode 8 and not about mode 1, please keep threads clear of unnecessary posts for better overview of the issues.

Otherwise, if you have some good working code for mode 1 to merge the way of working for mode 8 in there then u can make a pull request for it so the CoursePlay dev team can take a look at it and test it before importing it in a update.

**Comment by Innallas** [comment]
Ohh ok i saw the pulls requests yesterday, i need to make this to propose new changes ? But about the mode2 i have a problem while i want to use it to test , when i search for a combi i saw them but it's never selected, the "actual combi" always stay at "none". Is it what we need to fix ? the code to find the combi in mode 2 ?

**Comment by ThomasGaertner** [comment]
@Innallas : mode2 is dead

**Comment by Knowen** [comment]
Hello, I have one question about the leteral distance. Is there somewhere a database in which the whole distances of the individual combine harvester are in it or is the distance calculated? 
I can tell you that the distance for the RSM 161 and the 9240 Axial-flow on automode are not that good.

**Comment by ThomasGaertner** [comment]
![fsScreen_2019_03_09_12_59_47](https://user-images.githubusercontent.com/3279913/54071333-8150c980-426b-11e9-9455-4c5801115edb.png)
Teaser :-)

**Comment by Tensuko** [comment]
How far is it implimented in 153 ?
Before I open new Issue about Pathfinding for Mode 2 Driver when chopping chaff and about when the chopper got to start (wait till Mode 2 Driver reached final turn point) I would like to know.

**Comment by FforFarm** [comment]
Hi,

What is the status on this mode2 WIP-project?
For me, Iplay the game as a "Farm Manager"-mode, controlling workers (Courseplay).
Unfortunatly at some point during the last couple of months, the old mode 2 has become more and more unusable - now to the extend that it will crash into the combine at every single unload.

It removed a lot of joy, and desire to play the game, and i am really looking forward to the new mode2 release. 
I was just currious, if there is any update to tell :-)

**Comment by Tensuko** [comment]
Sadly, not yet, as dev doesn't have much time right now.
I don't know how good AD handels it, if you might use that one so long (Combine = CP and AD drives the Tracktor).
I play mostly the same way, but as it is not much work, to drive the Tracktor arround a bit, I mostly do it myself. Truck waiting at start to be loaded next to the field must be fixed, then you can even take a overloader and the truck will bring the fruit to the silo. We are on it, but I can't rly say when....
As soon as I got anything that is showable I will let you know.

**Comment by Knowen** [comment]
Hello,
is it possible to give us a short update on how this WIP is going on? But only when you have time for it.

Thanks 😃

**Comment by KingZogg** [comment]
So. Just to be clear. Mode 2 is NOT "Production Ready" ?
I can wait but just want to know.
Not trying to pressure you guys as you are all doing a great job and it's appreciated. Just want to know what the status is.

**Comment by ThomasGaertner** [comment]
the new mode 2 uses the same script as the current mode 1 and 6, so if it works there, it works in new mode2, if not then not :-)
