### ISSUE TITLE
AI Gas pedal "pulsation" on turn maneuvers 

### ISSUE THREAD

**Issue by GeorgeEarslight** [Courseplay/courseplay#3312]
The AI pulsates the gas while on turn maneuver, rather than keeping a steady speed.
I'm not sure if this has already been brought up yet, but it does seem an obvious issue, although searching "turn" or "maneuver" didn't return any relevant issues.
Do you need any logs or is this a known issue?

**Comment by sootysax** [comment]
I noticed this on reverse driving, but not forward

**Comment by pvaiko** [comment]
That's not us, that's the Giants AIVehicle slowing down on higher steer angles as far as I can tell. Not something we want to deal with at this point.

**Comment by GeorgeEarslight** [comment]
> I noticed this on reverse driving, but not forward

@sootysax It does this on my UP-DOWN lane transition manoeuvres.  Have you noticed something similar there, or it doesn't appear at all?
