### ISSUE TITLE
cant open hud on right click

### ISSUE THREAD

**Issue by Matteshow1** [Courseplay/courseplay#3314]
when i click right click the hud dosent open,also i can't click on the hud

**Comment by chuck-171** [comment]
You need change  in config. Add in mouse, keyboard.

**Comment by Matteshow1** [comment]
@chuck-171 already done, it does not work

**Comment by chuck-171** [comment]
You did it??
[http://prntscr.com/mqjiuo](url)

**Comment by Matteshow1** [comment]
Yes

**Comment by chuck-171** [comment]
hold, crtl + delete, and chang here 
![screenshot_2](https://user-images.githubusercontent.com/22191740/53446591-1c3adf80-39f2-11e9-9567-bebf96cf40f1.png)

**Comment by Matteshow1** [comment]
I can't change this, mouse don't click on hud

**Comment by chuck-171** [comment]
You need to leave the same as in the first photo. Where you have the mouse actions option, you need to go to the tab and click the mouse there. in the mouse column, not the keyboard
I had this same problem, I opened the mod but the mouse did not click. I had to change that and it worked for me.
