### ISSUE TITLE
Fertilize and seeding with Refill Course

### ISSUE THREAD

**Issue by sesmo** [Courseplay/courseplay#3316]
On Fertilize and seeding with e refill course, the tractor miss the first waypoint of the refill course and and move on without  following the next waypoints.

This happens randomly with several courses and tractors, Most of the times, the tractor drives the refill course with no problem.

I think it happens when the tractor drives from the refill course and misses the first waypoint of the field work, but in this case i dont have a log file.

![2019-02-27 1](https://user-images.githubusercontent.com/25755540/53494500-d0417680-3a95-11e9-95a2-fc62cb84d3f6.png)

[log.txt](https://github.com/Courseplay/courseplay/files/2910573/log.txt)

**Comment by pvaiko** [comment]
From your description it is unclear when is this happening, when changing from fieldwork to refill or the other way. Also, the log has like five CP helpers running, no idea where the problem happens. Need a better description and log with channels 12 and 14 only and need to know which vehicle it is.

**Comment by sesmo** [comment]
@pvaiko   This happen when changing from fieldwork to reffil.

You can download the log file with the link above.
There are only a driver...

The miss happens 3 or 4 minutes before i stop the game and save. 


https://drive.google.com/file/d/1LwZbE7HKJYaCKZOSDzg2VExYnkuR9hAA/view?usp=sharing

**Comment by pvaiko** [comment]
Nice long game... And what exactly happens when it misses the waypoint? Keeps driving straight?

**Comment by sesmo** [comment]
yes...

In all case the tractor going straight until the end of the map...

One thing I notice... Since version .00102 when you change the headlands this not happen so frequency...

Now i'm making a new test. 4 hours and no problem...

**Comment by sesmo** [comment]
@pvaiko Happen again.... This time I see and stop the tractor immediately.

In the photo you can see the path made by the tractor looking at the blue line.

The new log file:
![2019-03-02_li](https://user-images.githubusercontent.com/25755540/53686404-73a4bc80-3d1e-11e9-8fb5-64326ad66fa3.jpg)


The new log file:

https://drive.google.com/open?id=1wdsBNT1DY4FZbq3w1hC18MnXCjGEObM4

**Comment by sesmo** [comment]
Another Thing @pvaiko 

It can be coincidence: But all the times i see, the angle is about 45º between the field line and the first waypoint of the refill course.

**Comment by sesmo** [comment]
Hi @pvaiko 

Today i made 4 new experiences and happen every time. 

The Log file of the last one is here:
[log.txt](https://github.com/Courseplay/courseplay/files/2943882/log.txt)

I made a video here you can see what happen at minute 11:52.

I use 3 tractors. This time happen with just one. The other 3 times i made the same course happen with 2 of the tractors.

The video link is here:

https://www.youtube.com/watch?v=k_r49OqMdCk

**Comment by pvaiko** [comment]
Thanks for the video, that really helps.
