### ISSUE TITLE
curseplay key shotcuts highlight

### ISSUE THREAD

**Issue by LukasSevc** [Courseplay/courseplay#3317]
![inkednew-farming-simulator-17-gameplay-from-gamescom-fs-2017_li](https://user-images.githubusercontent.com/48060993/53500506-b9f1e580-3aaa-11e9-9544-bbfb0493c00a.jpg)

I have problem that I can't turn off curseplay key shortcuts preview in menu witch is in red area on the image. 
Please tell me where I can turn it off. It is ugly for me. I don't like it.

**Comment by pseikoNL** [comment]
At first, this git is about courseplay (a mod for FS). At second, you have an issue with the f1 menu of FS itself, maybe you can try the Giants forum to get some help with your FS17 issue.

**Comment by LukasSevc** [comment]
I am sorry I had a mistake in my issue. I correct it.

**Comment by sootysax** [comment]
@LukasSevc This Github is about Courseplay for FS19.

**Comment by LukasSevc** [comment]
please is any way to fx it or is some issue forum fo fs 17?

**Comment by bgo1973** [comment]
Even it has nothing to do with courseplay at all, just press "F1".

**Comment by LukasSevc** [comment]
f1 for me works but it will turn off all highlights but I want to turn off only curseplay highlights

**Comment by bgo1973** [comment]
There is no entry from courseplay in your help menu. Cruisecontrol is an ingame control which has nothing to do with courseplay.
