### ISSUE TITLE
Fill and empty shovel & Leveling and compacting Not selectable 

### ISSUE THREAD

**Issue by Fusion9334** [Courseplay/courseplay#3318]
Hi,

I have tried many different tractors front loaders, leveling implements, shovels etc. But everything I try, these 2 mode icons are not selectable and are greyed out. I also tried to set the unloading course from silo to the unload sell point at the plant. Nothing. Can't seem to get the option to let me select it.

I research this a good bit and found no one having this problem which leads me to believe I may be doing something wrong.  Every youtube video I have watch had the icon selectable. But not on mine. No Clue.

Also disable all mods except CP with no results. 

I have the latest version of CP as well as FS19. Any help will be appreciated.

Thanks,

**Comment by Jimmy-the-Geek** [comment]
This mode hasn't been activated yet, as they've been working on getting the
basics working first.

**Comment by sootysax** [comment]
@Fusion9334 #2912 - It's in the VERY first post....
