### ISSUE TITLE
extra fruits not dumping into silo

### ISSUE THREAD

**Issue by tuzlo** [Courseplay/courseplay#3319]
I have a question about CP and tip trigger points. 

Map is called PV Industries, I believe a conversion of a 16x FS 17 map. 

The placable silo I used for storage is http://www.modhub.us/farming-simulator-2019-mods/large-silo-facility-v1-1-0-0/

The map has many extra fruits installed upon it including Hemp and coffee (these 2 I can attest will not unload properly). 

The question I have is the tip trigger detection fruit dependent, Tractors auto dumped when unloading wheat or barley, but when I tried unloading the hemp from one field they did not detect the tip trigger.

Thank in advance
Tuzlo

**Comment by ThomasGaertner** [comment]
Log with debug chanel 1 active please

**Comment by Knowen** [comment]
Maybe the tip trigger is not the problem. I think the Silo is the problem. Have you ever tried to load hemp or coffee into the silo? If that does not work, then these types of fruit can not be stored in the silo and therefore not by CoursePlay.

**Comment by ThomasGaertner** [comment]
@Knowen that would have been shown in the log with debug1

**Comment by tuzlo** [comment]
I will get one, please give me time.

**Comment by tuzlo** [comment]
Log file can be found at https://pastebin.com/TL53gDCj

I think I need to explain that I have the placeable silo in the original post but I also added a silo extension found here:

http://www.modhub.us/farming-simulator-2019-mods/multi-silo-extension-v1-3/

I will add that I can unload manually.

**Comment by Innallas** [comment]
You probably need to add the fruits in the silo.xml , into the <fillTypes> beacons but it show only in store :D the other one where to add are in the beacon <storage> , both are in the XML definition file in the ZIP. You need to add them then > it will work (yep CP goes look what fill types are taken from the object directly > so its not a CP problem i think).

For the development name of your fruits, err you can look into the XMLs in your map zip
