### ISSUE TITLE
Video link showing new headlands branch in action

### ISSUE THREAD

**Issue by Hubcap-1** [Courseplay/courseplay#3322]
I think the new headlands branch is working very well I used a long wheel base Amazone seeder that was not only having problems doing the Headlands turns and transitioning to up / down, (even 90 degrees at times)....and this reason, as well as transitions,  meant 1 headlands was troublesome never mind 2,  ( Just couldn't do it) . Well here is a link to a 2 headlands Course video i did and uploaded to you tube and it seemed to go very well. I have since tested it on multiple fields including one  with no less than 7 corners and it is working perfect . Have also tested it with a harvester All field tests were with a long wheel base Amazone 15001 Condor.  Also importantly of note. Not once in almost 7 hours of continuous testing on multiple fields Has the Fendt 1050 + Amazone Condor ( or the case harvester ), entered a continuous fwd or rvs endless loop or failed to make the turn without delay.... two thumbs up I think we have  a winner !
Video was just posted and will not render in HD for at least a couple hours. ( 6:30 AM west coast time) Actual upload will be final  resolution on you tube at 1440P
https://youtu.be/HeSskumerHU

**Comment by Messy71** [comment]
@pvaiko for the 90° turns in headland it works like a charm ( is the Mona Lisa of turn maneuvers ) 
**But** there still is a small problem for degrees >90° and smaller then the limit where the course generation doesn't insert a turn with reverse maneuver (it just bends the waypoint line).
In this case the tractor fallows the generated forward line of the turn and at the end it starts turning outside the field **with Turn on field set to ON** it doesn't stop to reverse for the start of the generated curve line of the turn. 
@Hubcap-1 can you please try same setup on Estancia Lapacho fields 29, 30.  
I've tried with Fendt 1050 + Amazone Condor - up/down first then the headlands (2)
also the Fendt 1100 + the large flexicoil cultivator- headlands (2) then up/down at the end 
both tractors does the same thing ( for angles > 90 doesn't reverse  but goes forward and turns CCW) 
I'll post some pics/logs in this Issue later.

**Comment by Messy71** [comment]
First : Fendt 1165 Flexicoil [LOG](https://gist.github.com/Messy71/72a03b15fb22dc9bb9f3ec77f25f98b5)
![fsscreen_2019_02_28_22_34_10](https://user-images.githubusercontent.com/47163914/53602186-4df8a580-3bae-11e9-8cfe-5182818235b1.png)
![fsscreen_2019_02_28_22_34_16](https://user-images.githubusercontent.com/47163914/53602187-4df8a580-3bae-11e9-87bf-231343888efd.png)
![fsscreen_2019_02_28_22_34_28](https://user-images.githubusercontent.com/47163914/53602188-4df8a580-3bae-11e9-8f6f-2515bf093f82.png)
![fsscreen_2019_02_28_22_34_46](https://user-images.githubusercontent.com/47163914/53602189-4e913c00-3bae-11e9-88a0-8355a3474fb6.png)
![fsscreen_2019_02_28_22_35_15](https://user-images.githubusercontent.com/47163914/53602190-4e913c00-3bae-11e9-87a9-21bd3084ea6e.png)
![fsscreen_2019_02_28_22_35_36](https://user-images.githubusercontent.com/47163914/53602192-4e913c00-3bae-11e9-8699-cbca0c382243.png)
![fsscreen_2019_02_28_22_35_39](https://user-images.githubusercontent.com/47163914/53602193-4e913c00-3bae-11e9-8cc5-cf5a1899316c.png)
![fsscreen_2019_02_28_22_35_41](https://user-images.githubusercontent.com/47163914/53602195-4e913c00-3bae-11e9-9597-1f20f0c9920a.png)
![fsscreen_2019_02_28_22_35_45](https://user-images.githubusercontent.com/47163914/53602196-4f29d280-3bae-11e9-88a4-b0230d2c2ea8.png)
![fsscreen_2019_02_28_22_35_53](https://user-images.githubusercontent.com/47163914/53602197-4f29d280-3bae-11e9-8afc-bf35b2474a42.png)
![fsscreen_2019_02_28_22_35_57](https://user-images.githubusercontent.com/47163914/53602198-4f29d280-3bae-11e9-9f8f-47c0cfd869d2.png)
![fsscreen_2019_02_28_22_36_07](https://user-images.githubusercontent.com/47163914/53602199-4f29d280-3bae-11e9-94b5-201b3c421d13.png)

**Comment by Hubcap-1** [comment]
I will have to download that map but I will try to get back to you sometime
today

**Comment by Messy71** [comment]
Second: Fendt 1050 Amazone Condor [LOG](https://gist.github.com/Messy71/0382815d3ea37860f53d0c0c296982d5)
![fsscreen_2019_02_28_22_54_09](https://user-images.githubusercontent.com/47163914/53602351-cb241a80-3bae-11e9-95c3-3b3a727c76f2.png)
![fsscreen_2019_02_28_22_54_12](https://user-images.githubusercontent.com/47163914/53602352-cb241a80-3bae-11e9-8fd7-83ff65357242.png)
![fsscreen_2019_02_28_22_54_16](https://user-images.githubusercontent.com/47163914/53602353-cb241a80-3bae-11e9-9a57-0ce4ff3da23d.png)
![fsscreen_2019_02_28_22_54_24](https://user-images.githubusercontent.com/47163914/53602354-cbbcb100-3bae-11e9-9b26-2d2e235525bb.png)
![fsscreen_2019_02_28_22_54_35](https://user-images.githubusercontent.com/47163914/53602355-cbbcb100-3bae-11e9-99db-8f0fd5204a75.png)
![fsscreen_2019_02_28_22_55_04](https://user-images.githubusercontent.com/47163914/53602356-cc554780-3bae-11e9-8950-282a743a53f1.png)
![fsscreen_2019_02_28_22_55_18](https://user-images.githubusercontent.com/47163914/53602357-cc554780-3bae-11e9-8a98-8853a28f57c7.png)
![fsscreen_2019_02_28_22_55_30](https://user-images.githubusercontent.com/47163914/53602358-cc554780-3bae-11e9-8227-754c09e6af2d.png)
![fsscreen_2019_02_28_22_55_35](https://user-images.githubusercontent.com/47163914/53602359-cc554780-3bae-11e9-9fba-5348c80f83c0.png)
![fsscreen_2019_02_28_22_55_41](https://user-images.githubusercontent.com/47163914/53602360-ccedde00-3bae-11e9-884b-69b5f34321cd.png)
![fsscreen_2019_02_28_22_55_43](https://user-images.githubusercontent.com/47163914/53602361-ccedde00-3bae-11e9-9e18-3e901735e661.png)
![fsscreen_2019_02_28_22_55_51](https://user-images.githubusercontent.com/47163914/53602362-ccedde00-3bae-11e9-8ebf-e5dbf07794a1.png)
![fsscreen_2019_02_28_22_56_03](https://user-images.githubusercontent.com/47163914/53602363-ccedde00-3bae-11e9-9c6a-7a49dbfd819e.png)
![fsscreen_2019_02_28_22_56_16](https://user-images.githubusercontent.com/47163914/53602364-cd867480-3bae-11e9-8b72-935238bce251.png)

**Comment by Hubcap-1** [comment]
Now I'm not really sure I just think doing the up down before the headlands
is kind of backwards and defeats the whole purpose of a head length can you
try doing that but do Headlands first and tell me if you're still having
the same problem

**Comment by Messy71** [comment]
@pvaiko let me know if you need courses files
@Hubcap-1 now i'm going to sleep { **23:20 CET France Time Zone** } 
I'll do some more testing tomorrow after work.

**Comment by pvaiko** [comment]
@Messy71 you already have an open issue on this, please use that one. This is a video link, not an issue. Closing.
