### ISSUE TITLE
Implements dosent get lowered at start

### ISSUE THREAD

**Issue by Mannelig83** [Courseplay/courseplay#3323]
Hi.
with .99 Implements dosent get lowered when you start with headlands in seeding or cultivating mode.

Do you Need any debug channels or screenshots?

**Comment by Knowen** [comment]
Same problem here. Tried diferent combinations of tractors and seeders/cultivators, but everytime the same problem occures.

**Comment by Datalund** [comment]
Yup. Same problem here.
Implement is not being lowered, and when lowered manually,
 it is not working (cultivator is not cultivating) See image

Log file with channel 6 activated:
[](https://gist.github.com/Datalund/553b656a7c67cf3b7e3742b96d055970)

![2019_02_28_19_43_16_farming_simulator_19](https://user-images.githubusercontent.com/27280767/53592314-49c08e00-3b96-11e9-8142-d86933e26132.jpg)

**Comment by FS19-CP** [comment]
Having the same issue here, windrowers in my case.

Worker will not lower windrower at start, and will windrow a bit if lowered manually, but somewhere within the course... usually transitioning from up and down to headlands... he'll raise the windrower, and pointlessly finish the course.

**Comment by pvaiko** [comment]
I need a  log with channel 14.

**Comment by pvaiko** [comment]
Sorry folks, I swear it worked for me with a sowing machine... Should now be ok again.
