### ISSUE TITLE
Rain/Hail with Case AusToft sugarcane harvester crashes the game

### ISSUE THREAD

**Issue by juztinp** [Courseplay/courseplay#3325]
To reproduce: I have a sugarcane harvester with 2 tractors in combi mode offloading to the sale point. As it starts to rain/hail (in 120x speed) the game freezes. Can still get into menu but cant exit it. 
[save file for bug report - case austoft in rain.zip](https://github.com/Courseplay/courseplay/files/2917473/save.file.for.bug.report.-.case.austoft.in.rain.zip)

**Comment by Messy71** [comment]
@juztinp try to be more specific / descriptive
in wich way it freezes?
the menu of FS or the Courseplay HUD?

**Comment by juztinp** [comment]
Cant control or switch vehicles, the game engine is running - I can see tractors moving - the courseplay ones dont follow their routes - they go crash into things. I can go into the menu but cant leave it. Maybe there is an infinite loop happening? Not sure

**Comment by ThomasGaertner** [comment]
log ???????????????????????????

**Comment by pvaiko** [comment]
Reopen if you can provide a log.

**Comment by dexus92** [comment]
I have too this problem. What log I can give you?

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki
