### ISSUE TITLE
Helfer Klappt werkzeuge nicht ein un Fährt nicht weiter

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#3328]
Driver at the end of his route in the field. He does not pack this device together. this is also the case with the other devices.
He also does not want to continue when you push the button Continue. if you leave immediately, the font disappears, but when you press Continue, you are immediately visible again.

Here is a picture where he does not collapse:
![fsscreen_2019_03_01_18_39_58](https://user-images.githubusercontent.com/3021040/53655926-edbb3f80-3c51-11e9-828a-fbe94cfd566f.png)

MFG Mannie313

**Comment by Raints** [comment]
Not really sure what are you trying, but for mode you using 2 courses mean work course and refill course. In this picture your sprayer is almost full, so no need for refill.

**Comment by ThomasGaertner** [comment]
if he tells you that he's ready, then he will not move on the refilling route ...
was that the question ?

**Comment by Mannie313** [comment]
No. Um when he's done he does not fold the poor and who you click continue to drive nothing happens.

**Comment by Chris2996** [comment]
The worker is not supposed to start driving when he finished his course. Where should he go anyway? 

No Bug here, no fix needed. Close pls.

**Comment by Mannie313** [comment]
Kurs generiert fürs feld und zweiten kurs zum hof zwecks nachfüllen. aber da man nicht immer zu hof selber fahren kann mache ich gleich nen auffüllkurs dar gleichzeitig meine fahrzeuge zum hof bringt.

Also @Chris2996  sorry sinnloser kommentar.
MFG Mannie313

**Comment by Chris2996** [comment]
Solange die Spritze nicht leer ist oder der eingestellte Wert ab dem aufgefüllt werden soll erreicht wird, fährt der Helfer auch nicht zum nachfüllen. Schon gar nicht wenn er seine Arbeit beendet hat. Es handelt sich hier also nicht um einen Fehler in CP. Mit Anm. wie  "sinnloser Kommentar", wäre ich also vorsichtig.

**Comment by Mannie313** [comment]
Im LS17 hat er es auch gemacht obwohl er nicht vollständig leer wahr. 

MFG Mannie313

**Comment by Chris2996** [comment]
Wie hast du denn den Wert gesetzt ab dem er auffüllen soll? Wahrscheinlich wurde der Wert einfach nicht unterschritten.

**Comment by ThomasGaertner** [comment]
to make it clear: if the field work is finished, it will not fold and go to the unload course. it will stop, tell you that hes ready and wait for you patiently
