### ISSUE TITLE
wrong type of CP ai driver used in combi mode (mode 2) with traffic

### ISSUE THREAD

**Issue by Opa-Andre** [Courseplay/courseplay#3331]
I noticed a general traffic issue due to the type of cp ai driver used, which is specific to mode 2 (combi mode). But I'm unsure if this can be fixed easily. Reproed with the last versions of CP, for example 6.01.00103. When driving a course using mode 1 (grain transport) or mode 6 (transfer) the issue isn't observed. 

In transfer mode or even grain transport mode when you approach a "general traffic" driver from behind because of driving faster than the general traffic, the cp ai driver is slowing down and follows the traffic driver which is ok / the correct behavior. 

However in mode2 (combi) it will cause the traffic ai in front of you to stop, so the cp ai driver is bumping into the rear of the traffic car and tries to continue its path with spinning wheels but being blocked by the stopped traffic vehicle in front. 

You will notice the same if your mode2 driver is waiting on the field (end of route) for the harvesters fill level and close to a street with normal ai traffic. Then the normal traffic also stops...

I assume that the FS19 game offers 2 types of AI modes with different priorities. Priority 1 (higher) is for field work and causes priority 2 (lower) traffic to stop when in range of a prio 1 driver. So while Prio 1 mode is ok for high priority modes (modes 4, 6, 10) and prio 2 is for normal (lower) ai traffic (modes 1, 5 8, 9) the modes 2, 3, 7 should be able to switch between both priorities. 

So for mode 2 it would be great if you can implement to switch from prio1 (high) to prio2 (low) mode at the starting point of the route (street mode or street driving part) and from prio2 to prio1 mode at the end of the route, when the ai driver reached the field and starts to search for harvesters to unload them. This would have several advantages:

- While driving on the street (prio2) it won't block other traffic AI resulting in traffic jams.
- while driving on field (prio1) it won't be blocked by harvesters as it does have the same high prio, otherwise it would not be possible to unload them
- while waiting at the end of the route (in the field) for the harvesters fill level, it would block the next approaching combi driver behind which is still in prio1 (street) so that one wouldn't rush into the waiting driver. 

 Besides this congrats to your excellent work for the FS community!

kind regards
Andre

**Comment by sootysax** [comment]
#3311

**Comment by ThomasGaertner** [comment]
yes #3311
