### ISSUE TITLE
Courseplay Locking Up : v105

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3335]
im not sure what is triggering this, but I cannot move the vehicle, exit, tab out or esc menu when it happens

https://gist.github.com/sootysax/39a27ed4566e571bf9c00a284271d685

**Comment by Cup-Cakes** [comment]
i hade the same.. it keeps an helper on board when you say stop. press H to unload the helper.
I found more issues whit this version like driving over the unload trigger and not unload keeps driving.

I went back to version 98 wich was my last saved one.. after that version things are screwed up a bit.

**Comment by ThomasGaertner** [comment]
you tried to unload into a tipTrigger. do you know, which equipment it was ?

**Comment by Cup-Cakes** [comment]
At the hayloft and a silo (mod) with a Zelon CFS 2501 DO Farage Wagon.
I also notice problems when the tractor have a front loader attached or a weight on the front.
When there is nothing on the front thing goes better.

**Comment by sootysax** [comment]
the active course was a JD6230R with a TKD302, shuttling silage from a belt to the BGA.   But i cannot confirm it was not passing through a different tip trigger at the time..   I will watch and see if it happens again

**Comment by ThomasGaertner** [comment]
@sootysax did you use a front weight `?

**Comment by sootysax** [comment]
> @sootysax did you use a front weight `?

not sure - it hasn't happened since..  Unless @Cup-Cakes has a log and more details, we can postpone until it happens again

**Comment by Cup-Cakes** [comment]
Well i have one.. only have no clue at what tim,e i had those issues and its a pretty long session :-)
[log.txt](https://github.com/Courseplay/courseplay/files/2922482/log.txt)
