### ISSUE TITLE
Distance to track dosent match anymore

### ISSUE THREAD

**Issue by Mannelig83** [Courseplay/courseplay#3337]
Hi,
im harvesting with 2 harvesters and did this before multiple times where it worked flawless.
With the newest Version of CP the harvesters dont move to teh correct Track. 
They move to the Course with theire outer side instead of the outer side of the heder.
Pictures:

![screenshot 2019-03-02 19 09 07](https://user-images.githubusercontent.com/47121919/53685766-5e7c5d80-3d1f-11e9-983f-9bd988f36398.png)

![screenshot 2019-03-02 19 09 27](https://user-images.githubusercontent.com/47121919/53685769-63d9a800-3d1f-11e9-9c63-f5661b303f8b.png)

I hope this is fixable or is it gonna be sorted under new mode?

Greets Markus

**Comment by pvaiko** [comment]
Can't reproduce this. What does your work width show?

**Comment by Mannelig83** [comment]
Working with is 15m (like the Header is) and toal is 30m (2 vehicles selected).
I did recreate the Course and tryed what i could imagine.

Im confused by this one too cause in an earlier Version it worked flawless with exactly this Course and this machines and headers on this field.

If it could help i could try it with older CP Version to find the Version which broke it.
Like i said im not to sure what this can cause.

Any debug channel that could possibly help?

Greets
Markus

**Comment by pvaiko** [comment]
> If it could help i could try it with older CP Version to find the Version which broke it.

That would certainly help. Don't think we have changed anything there.

Debug channel 12 on while you are changing to multitool and lane offset settings should show the offset in meters.

**Comment by Mannelig83** [comment]
I tryed to reproduce it Right now but it didnt happen again.
im kinda speechless…

Do you have any clue what could cause this?
Could a reload of the game have fixed it?

Im so sorry that i wasted your time.
Im happy that i took screenshots at least... otherwise i would think im loosing my mind *smile*

Greets
Markus

**Comment by ThomasGaertner** [comment]
looks like your work width had been changed somehow...

**Comment by Mannelig83** [comment]
Thanks dudes. ill Keep an eye on it and reopen if i have more Input to share.
