### ISSUE TITLE
Game crash after a few minutes into a course.

### ISSUE THREAD

**Issue by fritzOSU03** [Courseplay/courseplay#3340]
The game freezes and the following error and stack trace are in the log hundreds/thousands of times. The error repeats until I force close the game. I am currently using version 6.01.00108.

`Validity check failed in TransformGroup_setTranslation:  
..\..\..\src\engine\app\ReflectionAndScriptBinding.cpp (3692): !MathUtil::isNaN(pArgs->arg[2].f)
LUA call stack:
=F:/C_Redirects/my games/FarmingSimulator2019/mods/FS19_courseplay/Waypoint.lua (155) : printCallstack
=F:/C_Redirects/my games/FarmingSimulator2019/mods/FS19_courseplay/PurePursuitController.lua (324) : setToWaypoint
=F:/C_Redirects/my games/FarmingSimulator2019/mods/FS19_courseplay/PurePursuitController.lua (192) : findGoalPoint
=F:/C_Redirects/my games/FarmingSimulator2019/mods/FS19_courseplay/AIDriver.lua (273) : update
=F:/C_Redirects/my games/FarmingSimulator2019/mods/FS19_courseplay/FieldworkAIDriver.lua (118) : drive
=F:/C_Redirects/my games/FarmingSimulator2019/mods/FS19_courseplay/drive.lua (11) : drive
=F:/C_Redirects/my games/FarmingSimulator2019/mods/FS19_courseplay/base.lua (1048) : drive
dataS/scripts/vehicles/SpecializationUtil.lua (30)
dataS/scripts/vehicles/Vehicle.lua (1305) : raiseEvent
dataS/scripts/network/NetworkNode.lua (98) : update
dataS/scripts/network/Server.lua (58) : updateActiveObjects
dataS/scripts/BaseMission.lua (1500) : update
dataS/scripts/FSBaseMission.lua (1971) : update
dataS/scripts/missions/mission00.lua (469) : update
dataS/scripts/main.lua (1863) : update`

**Comment by pvaiko** [comment]
Would certainly help a lot if you described what exactly you were doing when this happened.

**Comment by fritzOSU03** [comment]
> Would certainly help a lot if you described what exactly you were doing when this happened.

Sure thing! I'm on Marwell Manor Farm. First I generate a course for a JCB Fastrac 4220 pulling a Hardi Navigator 6000 to fertilize field 15 and I start it on its way. Then I generate a fieldwork course to plow field 19 with a Fendt 1149 MT pulling a Horsch Joker 12 RT and I start that one on its way. The issue occurs regardless of if I'm in one of the CP helper vehicles. Let me know if you need more info or if you'd like me to try something specific. Thanks for taking the time for such an awesome mod.

**Comment by pvaiko** [comment]
Can you post a savegame just before it happens? And the courses you are using.

**Comment by fritzOSU03** [comment]
I don't have any courses because I was just generating them on the fly. I just reproduced the issue and caught it fairly early if you'd like the full log file.

[savegame11.zip](https://github.com/Courseplay/courseplay/files/2922531/savegame11.zip)

**Comment by pvaiko** [comment]
In this savegame the Fendt has no implement.

**Comment by fritzOSU03** [comment]
That's strange because it is definitely attached to a plow (attached).

[FS19_Joker12RT_Plow_VE.zip](https://github.com/Courseplay/courseplay/files/2922542/FS19_Joker12RT_Plow_VE.zip)

**Comment by pvaiko** [comment]
Also, I need a savegame and the courses set up so all I need to do is to start the helpers. There are too many variables otherwise.

**Comment by pvaiko** [comment]
Well, it is not strange as it is a mod I don't have. That is why we always ask to reproduce problems with the standard equipment, devs are not able to download all possible mods ever published :)

**Comment by fritzOSU03** [comment]
> Also, I need a savegame and the courses set up so all I need to do is to start the helpers. There are too many variables otherwise.

Ok, those pieces are attached.

[savegame11.zip](https://github.com/Courseplay/courseplay/files/2922568/savegame11.zip)
[FS19_Marwell_Manor_Farm.ModMap.zip](https://github.com/Courseplay/courseplay/files/2922569/FS19_Marwell_Manor_Farm.ModMap.zip)


> Well, it is not strange as it is a mod I don't have. That is why we always ask to reproduce problems with the standard equipment, devs are not able to download all possible mods ever published :)

Wait, so you're telling me that you don't have all of the mods installed?! LOL

**Comment by pvaiko** [comment]
Ran both courses all the way to the end without any issues. Reopen if you can reproduce this with the latest version without any mods (except the map)
