### ISSUE TITLE
Forage trailer not lowering implement

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3344]
Looks like v.109 broke the forage wagon - it turns on but does not lower.

https://gist.github.com/sootysax/b650f1659be192f79e6edc370593751a

![fsscreen_2019_03_02_20_14_41](https://user-images.githubusercontent.com/6591048/53689645-43621b80-3d28-11e9-90b0-74d2ad11ba2d.png)

![fsscreen_2019_03_02_20_15_00](https://user-images.githubusercontent.com/6591048/53689653-52e16480-3d28-11e9-95c1-35fa1e35f022.png)

**Comment by pvaiko** [comment]
109 reverted. Seemed to be a good idea...
