### ISSUE TITLE
unsupported trailer capacity

### ISSUE THREAD

**Issue by Falkwa** [Courseplay/courseplay#3345]
having an issue where i cant use a tipper to offload my combine if its over 75k cap...   cant use a harvester thats over 60k cap..   same with semi trailers.    its not the trailer itself as the same trailer ect has many options for capacity.      any way to remove these limits?

**Comment by ThomasGaertner** [comment]
what do you mean with :can't use ? what happens then ? which equipment did you use ? what did you try to do ? more info would be nice

**Comment by BostonJohnny1226** [comment]
The capacities for my vehicles are as follows and work fine: combines are 99,000L, trailers are 300,000L, seeders,planters,sprayers and spreaders are 150,000

**Comment by Falkwa** [comment]
i did some digging.   seems the version the CP6 i had was ummmm extremely old..      as in 6.01.00014 old haha.     got the 112 on now and prob see if the issues i was having is resolved.
