### ISSUE TITLE
We correct bugs and you remove pull requests without correcting bug..... sweet

### ISSUE THREAD

**Issue by Innallas** [Courseplay/courseplay#3346]
Nice to see that we correct bugs and you just don't implement correction into code .... and even when its implemented you don't merge so contributors aren't shown... 

Very nice, look like we have childs coding....  you dont even know that the script do not understand ternary with and+or like in other compilers (i did 3 years of university in computing i know what i talk about). 
3 Errors i had fixed and you just dont implement.. BETTER ! You add useless things since official version who make everything to bug.... (if you use your and+or ternary everywhere and compiler don't understand it, i see why there are lot of bugs). 

Well have fun i see why there are so few contributors, nice childish behavior here, this explain why there are only 1-2 developper working....

TrafficCollision : bug still here , players pray to dont approach behind a car !
HuD : Look the issue and take my file to have the HUD window opening nicely with keyboard or mouse.
ToolManager : now all unloads do not respect unload distances calculated ! it's "static" somewhere, nice ! :D 
Triggers : You do not have biogaz loading stations... look in game , i did... without integrating storage system the biogaz isnt in the trigger list.

Well , have fun with theses sunday's coder.

As i said , you clearly dont even launched the game 1 time i bet , never try what u do, and don't know what you do too... , you look like to think you are coding in C or other but syntax is not the same in LUA script dudes, it's not a compiler......

Personnally i dont care i have fixed all this and share it, i even unload combis with mode 6 (you could remove mode 7 and integrate into but well you don't look pull request from users). 

Really pathetic behavior.

**Comment by ThomasGaertner** [comment]
#3343 
and now you are blocked.....
