### ISSUE TITLE
Potato harvesters

### ISSUE THREAD

**Issue by PavementPilot** [Courseplay/courseplay#3349]
Both the Grimes and Ropa potato harvesters are not being recognized as harvesters. With the Grimes, if you put the pipe or first, then start the course, it runs fine, but you need to drive the chaser manually. With the Ropa, it will not move if the pipe is out, and you start the course.

**Comment by ThomasGaertner** [comment]
so is it a mode2 issue ?

**Comment by PavementPilot** [comment]
I had mode 2 selected with the Grimes, but not with the Ropa.

**Comment by kybandy** [comment]
I think that part of the issue with the Ropa is that you can't have the pipe out while the harvester is running. That explains why Courseplay won't start harvesting with the pipe out, at least.

**Comment by ThomasGaertner** [comment]
so for the mode2 part: #3311 , the rest is @pvaiko is suppose

**Comment by pvaiko** [comment]
Does anyone have a savegame set up with potato and harvesters?

**Comment by kybandy** [comment]
I do. Can post tomorrow after work. 

Kyle Bandy

**Comment by kybandy** [comment]
Save game and log here: https://drive.google.com/open?id=1n7-PFxUYxjerQcwwR9jvOYeV4LaAgcR0

**Comment by pvaiko** [comment]
This savegame seems to be from a contract work. I need one with your own field, potatoes ready to harvest.

**Comment by kybandy** [comment]
Sorry for the delay. I have replaced the savegame at that Google Drive link with one with potatoes ready to harvest on a field I own.

**Comment by pvaiko** [comment]
These seem to work now, please open a new issue if not.
