### ISSUE TITLE
Neue Version

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#3350]
Gibt es schon ein neues Update von Courseplay 19

**Comment by Tensuko** [comment]
Da sich immer mal wieder etwas ändert, einfach unter Code nachschauen, da findest du die neueste Version.

**Comment by Charlyphyro** [comment]
![anmerkung 2019-03-03 192812](https://user-images.githubusercontent.com/21147032/53699609-84baff80-3dea-11e9-9b54-f73af02a8c49.jpg)
Hier erkennst du welches Update das aktuelle ist und wenn du es anklickst siehst du auch was geändertt worden ist :)
