### ISSUE TITLE
Tractor not turning V.00112

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/courseplay#3351]
I hope I put the right Debug Channels on.
![fsscreen_2019_03_03_19_04_57](https://user-images.githubusercontent.com/27344744/53699368-e168eb00-3de7-11e9-8ca1-75f6ce982e5a.png)
![fsscreen_2019_03_03_19_05_07](https://user-images.githubusercontent.com/27344744/53699369-e29a1800-3de7-11e9-8da3-f0e8fa89f461.png)
[log.txt](https://github.com/Courseplay/courseplay/files/2923475/log.txt)

**Comment by pvaiko** [comment]
This is just a plain old 180 turn, @Satissis would be the guy. May have something to do with the mower in the front, does it happen with only the mower/only wagon?

We'd also need debug channel 14, or even better a savegame if this is an official modhub map.

**Comment by Tensuko** [comment]
The Map is Provence from Modding Welt ( https://www.modding-welt.com/mods/file/2204-ls-19-provence/ )
It only happens when both Tools are Attached.
But anyway, log files for both, only mower, only wagon and Screenshot of a 2nd test for both tools.
Courses as well, don't worry about that one overlaping part, the turn is to hard, but thats ok
[both tools DeBug14.txt](https://github.com/Courseplay/courseplay/files/2927681/both.tools.DeBug14.txt)
[mower only DeBug14.txt](https://github.com/Courseplay/courseplay/files/2927682/mower.only.DeBug14.txt)
[wagon only DeBug14.txt](https://github.com/Courseplay/courseplay/files/2927683/wagon.only.DeBug14.txt)
![fsscreen_2019_03_04_19_11_13](https://user-images.githubusercontent.com/27344744/53753593-ebefb700-3eb1-11e9-84cf-e1025aceb060.png)
[LS19_Provence.SampleModMap.zip](https://github.com/Courseplay/courseplay/files/2927687/LS19_Provence.SampleModMap.zip)

**Comment by pvaiko** [comment]
@Tensuko the previous turns worked correctly, right?

**Comment by pvaiko** [comment]
Also, I can't find a savegame in the zip.

**Comment by Tensuko** [comment]
Previous turns ? He did that with all turn where the red and green arrow shows up, I just used next rows for some testing of different shapes testing.
The Savegame you can have, but you need the Map I posted up there (FileHorst is a good source, fast and easy download) and I think from ModHub I used the Mower, rest on the map and savegame should be vanilla so far. Same Savegame for Bunker Silo unloading issue.

Anything else needed ?

[savegame1.zip](https://github.com/Courseplay/courseplay/files/2949429/savegame1.zip)

**Comment by pvaiko** [comment]
Not perfect but works ok with v6.01.00126. Have no more time to polish it.

**Comment by Tensuko** [comment]
Need to create a new Course ?
Well, when it at least turn now, its good.
I will take a look at it how it performs now.

**Comment by pvaiko** [comment]
No need to create a new course.

**Comment by Tensuko** [comment]
👍  works with both tools now, no Idea what could be polished, time will tell.

Haven't tested if single tools make any problem now, but I doubt it will.

![fsScreen_2019_03_10_21_19_39](https://user-images.githubusercontent.com/27344744/54091045-6d948880-437b-11e9-87f6-9bd72f2bd445.png)

For me this can be closed.
