### ISSUE TITLE
Kartoffelernter von Grimme

### ISSUE THREAD

**Issue by Moodijil** [Courseplay/courseplay#3352]
Hallo Leute,

ich hoffe ich mache das richtig sonst bitte bescheid sagen.

Folgendes funktioniert nicht. Ich habe einen Anhänger am Feldrand platziert und wollte einen Kartoffelernter von Grimme in einem Kombinierten Kurs daran vorbeifahren lassen und Abladen lassen und dann weiter auf dem Feld Ernten lassen. Wenn mann den Kurs startet, funktioniert auch alles, aber wenn der Ernter voll ist und zu der Abladestelle fährt und dort ankommt stoppt der Kurs und es geht nicht mehr weiter und es friert ein

Ich habe die LOG mit angehängt.

Bin leider nicht sehr bewandert aber ich hoffe ich kann zum Fixen beitragen. :)

Liebe Grüße Christian
[log.txt](https://github.com/Courseplay/courseplay/files/2923497/log.txt)

**Comment by Tensuko** [comment]
Selber abladen funktionierte bisher so, dass es den Abladekurs (Feld zum Abladepunkt und wieder zum Feld) gab und nachdem man den Ernter mit dem normale Helfer (!!) gestartet hat, hat man zusätzlich den CP Fahrer eingestellt. Dadurch hatte CP die Kontrolle übernommen, sobald der Ernter voll war und von alleine den Helfer wieder eingestellt. Der Modus ist aber noch nicht wieder aktiv in CP6 von daher sollte das noch nicht gehen.

Ob sich daran etwas geändert hat oder sich etwas ändern wird, weis ich leider nicht.

**Comment by ThomasGaertner** [comment]
ja, das wird noch gemacht, kommt zusammen mit mode3 Überlader ...

**Comment by ThomasGaertner** [comment]
ich mach hier mal zu , das kommt aber noch...
