### ISSUE TITLE
Error: Running LUA method hud.lua:1167

### ISSUE THREAD

**Issue by Charlyphyro** [Courseplay/courseplay#3353]
Hallo zusammen,
Ich hab eine Fehlermeldung nach dem ich einen neuen Kurs generiert -->Gespeichert und einen Abfahrer eingestellt. Sobald ich diesen Kurs lösche (um ein neuen Kurs zu generieren) verschwindet die komplette HUD und im Log kommt eine Fehlermeldung. Danach komme ich auch nicht mehr ins ESC Menü und es hängt sich auf.
Falls ihr eine Log datei benötigt mit Debug, kann ich das gerne machen.

Version 6.01.00112
Fahrzeug: Case Puma 240 CVX + Bredal K105
Map: Michigan Map, Feld 13

![fsscreen_2019_02_25_18_41_40](https://user-images.githubusercontent.com/21147032/53699532-90f28d00-3de9-11e9-99fe-b945dad8d3b3.png)
Normale Ansicht 

![fsscreen_2019_03_03_19_05_02](https://user-images.githubusercontent.com/21147032/53699384-f80f4200-3de7-11e9-96bd-7f08dd255a13.png)
Nach dem Error

[log.txt](https://github.com/Courseplay/courseplay/files/2923470/log.txt)

[courseStorage0006.zip](https://github.com/Courseplay/courseplay/files/2923495/courseStorage0006.zip)

Viele Grüße
Charly

**Comment by ThomasGaertner** [comment]
also Kurs generiert, Abfahrkurs angehängt und gestartet und dann beim X drücken kommen die Fehler ?

**Comment by Charlyphyro** [comment]
Nein nur den Kurs zum Feld Düngern generiert ohne abfahrtskurs. Dann X gedrückt um einen neuen Kurs zu generieren. Ich schau noch mal genau wann es ein trifft.

Merke aber gerade das ich eine paar alte Kurse gelöscht habe. Es sind weit mehr als 100 Kurse und er schreibt ihn in als 6 Kurs

**Comment by ThomasGaertner** [comment]
ja probier mal bitte, hier klappt das ohne probleme ...

**Comment by Charlyphyro** [comment]
Okay neuer Test.
Es sind Aufträge (Vertrag zum Düngern vom Feld) auf diesen Felder (nicht meine) generiere ich den Kurs. Nach dem ich den Vertrag abschlisse und X drücke für einen neuen Kurs passiert erst nichts. Dann fahre ich zum neuen Auftrag/Vertrag Feld Düngern(nicht meine Feld) und sobald ich dort den Kurs generiere Crasht es.
[log_neuer_crash.txt](https://github.com/Courseplay/courseplay/files/2923552/log_neuer_crash.txt)

**Comment by Charlyphyro** [comment]
Nochmal getestet es passiert immer wenn ich auf Kursgenerierung gehe. 
Bin dabei immer noch auf Düngen und Säen sowie auf Abfahrer Steuerung. 

Das mit dem alten Kursen überschreiben macht keinen Unterschied. Es wurde jetzt einen neuen Kurs angelegt mit der fortlaufenden ID 178.

**Comment by ThomasGaertner** [comment]
fixed in v.113
