### ISSUE TITLE
Side Clearance

### ISSUE THREAD

**Issue by MeckyonTour** [Courseplay/courseplay#3355]
Hello dear CP-Team, first a big compliment for your work.
My question is, is it possible that in mode 2 there is the possibility that the CP is oriented on the unloading tube for the automatic side clearance and not always on the cutting unit where the front is attached? That's how it seems to me, because with Terra Dos and Tiger for the harvest of sugar beet, there are still problems that you have to set the side clearance manually. In this regard, I use only original vehicles from the game.
Sorry, i use Google translate

With best regards
MeckyonTour

Hallo liebe CP-Team, erstmal ein großes Kompliment für eure Arbeit.
Meine Frage ist, ob es möglich ist, das im Modus 2 vielleicht die Möglichkeit besteht, das CP sich am Entladerohr orientiert für den automatischen Seitenabstand und nicht immer am Schneidwerk wo vorne angehängt ist? So kommt es mir zumindest vor, denn mit Terra Dos und Tiger für die Ernte von Zuckerrüben gibt es da nämlich immernoch Probleme, das man den Seitenabstand manuell einstellen muss. Diesbezüglich nutze ich ausschließlich originale Fahrzeuge aus dem Spiel.

Mit den besten Grüßen 
MeckyonTour

**Comment by ThomasGaertner** [comment]
#3311
