### ISSUE TITLE
Downhill from the Grimme FT 300 and Rootster 604

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#3356]
The tractor Valtra N174 with Grimme FT300 and Grimme Rootster604 I have generated a harvest course on field 28 and runs without problems. But as soon as I got fueled with the Stara ST MAX 180 and Kroeger TKD 302 and he looked for a new waiting point to refuel I get the following error:
Error: Running LUA method 'update'.
2019-03-04 15:57 C:/Users/Manni/Documents/My Games/FarmingSimulator2019/mods/FS19_courseplay/combines.lua:484: attempt to index field 'spec_drivable' (a nil value)

With this error, the entire freeze is freezing.

version 6.01.00110 but also with version 6.01.00112

Here is the log  version 6.01.00110: [log.txt](https://github.com/Courseplay/courseplay/files/2926929/log.txt)

Here is the log  version 6.01.00112: [log.txt](https://github.com/Courseplay/courseplay/files/2926973/log.txt)

MFG Mannie313

**Comment by ThomasGaertner** [comment]
#3311
