### ISSUE TITLE
Offset at tatra phoenix 6 * 6 and lua error

### ISSUE THREAD

**Issue by lukimaho** [Courseplay/courseplay#3357]
Hello
Today I noticed that the Tatra phoenix 6 * 6 truck has a right offset in all modes. 
Furthermore, I harvested a field with 3 Harvester (NH Cr10.90) and 2 "Abfahrer" and suddenly I had lua errors, after that I stopped all cp drivers and set them again. If I had set the "Abfahrer" again, I had again the lua error (was set that he searches for harvester on field) 
[log.txt](https://github.com/Courseplay/courseplay/files/2927480/log.txt)

**Comment by KenStumich** [comment]
hi @lukimaho 
nice of you to support the project.
Problems are assigned to different people. to do so, its important to report only 1 problem per post.
and to get to the problem they need most of the time the log file.

pls use the info in the wiki ( button on top of this window ) to get the information you need.

**Comment by ThomasGaertner** [comment]
#3311
