### ISSUE TITLE
Ladezeiten/Loading Times

### ISSUE THREAD

**Issue by SchorschiBW** [Courseplay/courseplay#3358]
Hallo,

Ich habe jetzt nichts gefunden in der Issue-Sammlung, daher schreibe ich es mal:

Ich musste leider feststellen, dass bei großen Maps (4-fach Maps), wie bei der Western Australia die Ladezeiten extrem hoch sind, sobald Kurse (Erntekurs für den Drescher, Kurs für den Grubber und Kurse zum Abfahren) vorhanden sind

Hello,

I have not found anything in the Issue collection, so I'll write it down:

Unfortunately, I had to realize that with large maps (4-fold maps), as in the case of Western Australia, the loading times are extremely high, as soon as courses (harvest course for the thresher, cultivator course for the cultivator and courses for departure) are available

**Comment by MeckyonTour** [comment]
Das ist normal, weil ja jeder Punkt eines Kurses berechnet werden muss, deshalb halte ich es eigentlich so, das ich nur die Überführungskurse etc. speicher und nicht die Feldarbeit, es sei denn ich bin aktuell an einem Feld dran und kann es nicht fertig machen, dann speicher ich den Kurs. Aber wenn das Feld dann fertig ist lösch ich ihn wieder um die Ladezeiten zu verkürzen, spiel auch 4-fach auf der Kandelin.
Lieben Gruß
MeckyonTour

**Comment by SchorschiBW** [comment]
Das werde ich mal probieren. Danke für den Tipp

**Comment by MeckyonTour** [comment]
Nee, nicht im Savegame, sondern im Ordner FarmingSimulator2019  --> ganz oben "CoursePlay_Courses" ;)

**Comment by SchorschiBW** [comment]
danke, habe es gefunden
