### ISSUE TITLE
bale collector folds back right at the unloading waypoint

### ISSUE THREAD

**Issue by mehdinasef** [Courseplay/courseplay#3359]
when running a course with the round bale collector to transport the bales from the filed to the farmyard, the bale collector folds the unloading platform right in the unloading waypoint after dropping the bales. this moves the bales a little bit but, with this particular bale collector, it does not do that hard enough to make them fall. maybe the square bales collecter can make them fall ( haven't tested it).
it would be better if the collector moves a bit forward before folding the unloading platform back.

![balesunload](https://user-images.githubusercontent.com/47159754/53755224-468b1200-3eb6-11e9-84dc-04b3599e0ded.png)

**Comment by Tensuko** [comment]
Squared Bales Collector does the same, but also doesn't throw them down.
Tho it need a general fine tuning, but so far it works great.
