### ISSUE TITLE
6.01.00112: HUD sometimes disappears

### ISSUE THREAD

**Issue by Iwan1803** [Courseplay/courseplay#3361]
Sometimes the HUD disappears and i don't knwo why. I had the problem already in the previous versions.
Last time this happend:
- i tabbed to a tresher and tried to open the course generation
- i changed the trailer and tried to open Courseplay
To get the HUD back i've need to restart the game. It then affects only this one vehicle. For the others i can continue to use courseplay as usual.
As this happend earlier this day i activated the debug mode 18 and 19. I attached the log entries (a little bit shorten).
[log.txt](https://github.com/Courseplay/courseplay/files/2928007/log.txt)

**Comment by sootysax** [comment]
You should attach the whole log.

**Comment by Iwan1803** [comment]
Seems like it happens after playing 2 hours or more.
Enough played today, will attach it tomorrow if it happens again.

**Comment by ThomasGaertner** [comment]
fixed in v.113
