### ISSUE TITLE
Course recording enhancement

### ISSUE THREAD

**Issue by Messy71** [Courseplay/courseplay#3362]
Since there are some problems with course generation/ turn maneuvers i like to record my courses to get 100% coverage on the field. Problem is when using refillable implements(fertilizer, lime, seed) I can only stop the implement when inserting a turn waypoint .

It would be nice if there were 2 more buttons in the course recording page:

- raise implement (and stop if it's powered) [if spreader only stop]

- stop+raise+fold( in some cases you would have 2 fields next to each other or more, that need the same work, it's kinda same with append a new course but it would be useful if you need to squeeze trough some tight spaces)
Let me know if this is a good/bad idea. 
PS: I also tried inserting a turn point on a straight line (green and red pointing in the same direction but it doesn't raise or stop the implement. Neither inserting two turn sequences one after the other.

**Comment by pvaiko** [comment]
isconnectingtrack="true" will raise the implements. Also there are several tools out there to edit courses.
