### ISSUE TITLE
Game freezes with the newest version of CP (generateCourse.lua:1047)

### ISSUE THREAD

**Issue by Knowen** [Courseplay/courseplay#3363]
Hello,
with the newest version of CP i got a mayor issue. 
The gamre freezes, but not erverything. I can't move and after i switch one time from a tractor to another, even that is not possible anymore. The camera is also fix and not moveable. But the sound is working fine. And, after i was one time able to open the map, as it seems that other active CP Workers continues working, but i cant do anything. 
One big thing is, that i can not save anymore if this issue appears. I can click on save and the game says me that it had saved, but no. 

Here is a log, hopefully it is helpfull. 
[log.txt](https://github.com/Courseplay/courseplay/files/2933013/log.txt)

**Comment by pvaiko** [comment]
You had two John Deeres, one fertilizing, what was the other one doing?

**Comment by pvaiko** [comment]
reopen if v6.01.00116 does not solve it

**Comment by Knowen** [comment]
The other John Deere was working in mode2, collecting harvest from a 9240 axial flow. I can not tell you if the axial flow was working at the time this issue occurs.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
