### ISSUE TITLE
is it posible to deactivate saving the waypoint hight?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#3364]
Hi guys
is it posible to deactivate saving the waypoint hight?
some other programs, ev course drawer have problems to work with courseplay, since courseplay save also the high in the xml.
which value i must change, when i want have
`pos="14.97 217.14"/>`
back, and not
`pos="14.97 97.35 217.14"/>`
lg
andreas

**Comment by pvaiko** [comment]
This was actually requested by 'some other programs' devs, see #3096. I'd recommend ask them to update their software.

**Comment by andreasthu** [comment]
thanks for the link.
that help for me
can be closed
lg
andreas

**Comment by labruja2275** [comment]
Hi . One possible solution is to use the file course_management.lua from a previous version than the one in v6.01.00063. I use the course_management.lua of the version v6.01.00062 and it does not keep me the fist of the height, greetings from argentina. I do not speak English very much so use a translator
