### ISSUE TITLE
generateCourse.lua Error

### ISSUE THREAD

**Issue by Andii1980** [Courseplay/courseplay#3365]
Hallo, 

Ich bekomme immer das als Fehlermeldung ohne Ende.

> 2019-03-06 02:20 C:/Users/Andii/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/generateCourse.lua:1047: attempt to index local 'cp' (a nil value)
> 2019-03-06 02:20 Error: Running LUA method 'update'.

Bis dann der LS19 Crasht und nichts mehr geht.

mit bestem Dank
Andii1980

**Comment by pvaiko** [comment]
Duplicate of #3363

**Comment by pvaiko** [comment]
Irgendein Hinweis wann es auftritt? 'Immer' ist nicht besonders hilfreich.
