### ISSUE TITLE
LUA call Stack mit Version 6.01.00116

### ISSUE THREAD

**Issue by Andii1980** [Courseplay/courseplay#3366]
Hallo, 

seit Version .00116 bekomme ich jetzt nach ca 30min Spielen mit ein Paar CoursePlay Helfern diese Meldung für ca 30-45min bis dann der FS19 Crasht.

> 2019-03-06 08:07 Warning (script): Unknown entity id 310499 in method 'getParent'.
> 2019-03-06 08:07 LUA call stack:
> 2019-03-06 08:07   =C:/Users/Andii/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/bypass.lua (43) : getParent
> 2019-03-06 08:07   =C:/Users/Andii/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/mode2.lua (1336) : isTheWayToTargetFree
> 2019-03-06 08:07   =C:/Users/Andii/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/mode2.lua (158) : unload_combine
> 2019-03-06 08:07   =C:/Users/Andii/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/drive.lua (427) : handle_mode2
> 2019-03-06 08:07   =C:/Users/Andii/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/base.lua (1048) : drive
> 2019-03-06 08:07   dataS/scripts/vehicles/SpecializationUtil.lua (26)
> 2019-03-06 08:07   dataS/scripts/vehicles/Vehicle.lua (1281) : raiseEvent
> 2019-03-06 08:07   dataS/scripts/network/NetworkNode.lua (98) : update
> 2019-03-06 08:07   dataS/scripts/network/Server.lua (58) : updateActiveObjects
> 2019-03-06 08:07   dataS/scripts/BaseMission.lua (1495) : update
> 2019-03-06 08:07   dataS/scripts/FSBaseMission.lua (1990) : update
> 2019-03-06 08:07   dataS/scripts/missions/mission00.lua (462) : update
> 2019-03-06 08:07   dataS/scripts/main.lua (1857) : update

Gruß Andii1980

**Comment by ThomasGaertner** [comment]
#3311
