### ISSUE TITLE
Suggestion/Question: Fieldwork course generating

### ISSUE THREAD

**Issue by Knowen** [Courseplay/courseplay#3367]
When calculating the field rate, it sometimes happens that the last row is a different distance than any other. This often leads to the combine colliding with a waiting tractor. 

I adjusted that once:
![fieldwork](https://user-images.githubusercontent.com/47173160/53869191-fc11ae80-3ff7-11e9-8768-e2aaf647ecc1.png)

In this case, I have a headland.
Although I have a working width of 13.5m, but is it possible to evenly divide the inside of the field?
Then the tractor is never in the way or when fertilizing is not extra driven a lane for 2m.

**Comment by pvaiko** [comment]
This has been discussed in the past and someone was complaining about every solution. So will just leave it as is. The refactored mode 2 should make sure this does not happen.

> when fertilizing is not extra driven a lane for 2m

Well, if we evenly divide the same number of rows, it'll still drive an 'extra' row, it just won't be that obvious...

**Comment by Knowen** [comment]
Okay, i understand.
> This has been discussed in the past and someone was complaining about every solution. So will just leave it as is. The refactored mode 2 should make sure this does not happen.
> Well, if we evenly divide the same number of rows, it'll still drive an 'extra' row, it just won't be that obvious...

Well..but this happend a few hours ago with the newest version of CP.
![mode2](https://user-images.githubusercontent.com/47173160/53985475-f90fde80-411b-11e9-994b-d9d0e84d7eae.png)

So maybe it wouldn't be that obvious, but with evenly divided number of rows the CP Waitpoint wouldn't be a blocking point. I think #3311 needs a lttle tweek in this.
