### ISSUE TITLE
headland turns not working with multiple tools

### ISSUE THREAD

**Issue by mehdinasef** [Courseplay/courseplay#3369]
I have used the multiple tools function to cultivate one of my fields using 4 tractors (6m each). everything was just fine until they started doing the headlands. In every headland turn, they start turning in a circle or, rarely, in a back and forth  motion for a long time until I stop them.
The headland turns, that have been discussed in issues #3255 and #3290 and have been fixed, work pretty well when just one tool is used, but they do not work with multiple tools.

![trnsettings](https://user-images.githubusercontent.com/47159754/53900618-3e111380-403d-11e9-8d8a-f8ac5c91a5db.png)
![turn](https://user-images.githubusercontent.com/47159754/53900666-5a14b500-403d-11e9-840f-809f5c3134d3.png)
![turn1](https://user-images.githubusercontent.com/47159754/53900703-6993fe00-403d-11e9-9e63-3ae71c97f971.png)
![turn2](https://user-images.githubusercontent.com/47159754/53900724-744e9300-403d-11e9-9c21-2db188fe938a.png)

**Comment by mehdinasef** [comment]
here is the savegame:
[savegame1.zip](https://github.com/Courseplay/courseplay/files/2937531/savegame1.zip)

course:

[courseStorage0012.zip](https://github.com/Courseplay/courseplay/files/2937539/courseStorage0012.zip)

and map download link:

http://www.modhub.us/farming-simulator-2019-mods/flusstal-dedicated-tested-2-0-0-6/

in case you need them.

**Comment by Messy71** [comment]
@mehdinasef you can also upload a log with the debug channes ( 12 , 14, optional 13).It would be very helpful for the devs if you align the tractors 5-6 waypoints back from the waypoint in question (where the problem happens) , this way they just load the savegame and hit drive for each tractor. This makes things quicker  and finding the problem and solution a lot faster.

**Comment by mehdinasef** [comment]
I'll do that tomorrow, I'm quite busy right now.

**Comment by MoslessNeo** [comment]
I have this problem on my maps, on the plots where one of the edges is irregular. If I use 2 or more vehicles, the first one can follow the course, but the second is totally lost.

**Comment by mehdinasef** [comment]
here is the log with the debug channels 12, 13 and 14 and the savegame with the tractors aligned:

[savegame&log.zip](https://github.com/Courseplay/courseplay/files/2942048/savegame.log.zip)

I have put every tractor in one corner because this occurs in every turn.
I also noticed that the tractor that has the lane offset set to right 1 makes the turn easily.

**Comment by pvaiko** [comment]
Can't reproduce this on Ravenport.

I need a savegame and courses on an official map. I'm not able to download and install any random map you happen to see a problem on.

**Comment by mehdinasef** [comment]
I have created a course with the same settings on ravenport, field 12:

[ravenportturntest.zip](https://github.com/Courseplay/courseplay/files/2944972/ravenportturntest.zip)

hope it helps.

**Comment by mehdinasef** [comment]
> I also noticed that the tractor that has the lane offset set to right 1 makes the turn easily.

 same thing happens this time.
