### ISSUE TITLE
Call Stacks since .112

### ISSUE THREAD

**Issue by hoefti10** [Courseplay/courseplay#3370]
[log.txt](https://github.com/Courseplay/courseplay/files/2937826/log.txt)
 Since the Version .112 i had some Call Stack and nothing is move when i start CP with the same Courses. The Courses is still generated since the .7x Version.
 I tried a older Version but had the same Call Stacks :-(
Would be verry happy if somebody can told me what is wrong
regards

**Comment by ThomasGaertner** [comment]
try  with 117
