### ISSUE TITLE
LUA Error when Ursus Bale Collector loads last bale

### ISSUE THREAD

**Issue by RedOhne** [Courseplay/courseplay#3371]
Hi,

I've just updated CP to the latest version (116) and started a bale collecting and selling course. Once the ursus tries to load the last bale, I got the following LUA error:

https://gist.github.com/RedOhne/923031769815e8077f7b55129ab10aa5

Also a screenshot, which maybe helps understanding:
![20190306200607_1](https://user-images.githubusercontent.com/11273416/53907039-a1567200-404c-11e9-9510-46271f17cec9.jpg)

I checked similar issues, but wasn't able to find one. If you need some more information, logs, debug modes, feel free to contact me.

Thanks Tim

**Comment by Tensuko** [comment]
You got the real Dirt Mod active ? If so, delete it and try again. It looks like the error I had when started a combine and always got those kind of errors. After delete real dirt, it was gone.
If you want share your logfile, just drag and drop it in the comment box, just like screenshots.

**Comment by DevereM** [comment]
I have the same issue even with RealDirt completely uninstalled, so that isn't it probably.

**Comment by ThomasGaertner** [comment]
try  with 117

**Comment by DevereM** [comment]
Seems to have fixed it, works without issues. Great job on quickly dispatching the issues Courseplay team!

**Comment by RedOhne** [comment]
Works for me, too. Tested it yesterday. Thanks for the quick fix.
