### ISSUE TITLE
Sales or Abturch helper does not handle the traffic or objects

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#3372]
Hello, I have a problem. If I place a helper for the field to the cultivator or manure / sowing the traffic is perceived. However, if I place a helper for sale or fuel a tank he drives against any vehicle or obstacle. The log stays clean.

MFG Mannie313

**Comment by ThomasGaertner** [comment]
Schreibst das nochmal in deutsch bitte?

**Comment by Mannie313** [comment]
Hallo ich habe das problem der Helfer Beladen am Startpunkt und der Helfer Drescher abtanken Reagieren nicht auf den Verkehr und der Verkehr bleibt jedes mal stehen. auch bei hinernissen mit kolissionen fahren die zwei helfer ohne zu bremsen drauf.

MFG Mannie313

**Comment by ThomasGaertner** [comment]
mode2 ist klar, aber ist das wirklich auch im Beladen am Startpunkt modus ?

**Comment by Mannie313** [comment]
Ja aber ich schau mal nach ob es bei der aktuellen version auch noch ist.

**Comment by ThomasGaertner** [comment]
und ??

**Comment by Mannie313** [comment]
Ok beim verkehr hält er an aber an der Schranke nicht.

[url=https://filehorst.de/d/chyjimnc]Datei von filehorst.de laden[/url] 

fals es nicht geht
<a href="https://filehorst.de/d/chyjimnc">Datei von filehorst.de laden</a>

MFG Mannie313

**Comment by Tensuko** [comment]
Ich schließe das heir erstmal.
Wenn Mode1 noch immer probleme mit dem KI Verkehr hat, bitte mit dem Titel neu aufmachen.
Closed.
