### ISSUE TITLE
Game freeze and other issues related to weather fs19

### ISSUE THREAD

**Issue by boneys26** [Courseplay/courseplay#3373]
Rain causes problems while running a harvester, if the harvester is already running when the rain starts you get a warning up on the screen about rain and harvesting but instead of the harvester stopping it just drives in a straight line until it runs into something and anything else running on courseplay stops working but they continue to drive the course.. If you're lucky, switching to the harvester or another vehicle can cause the whole game to freeze. it also seams that until you get to switch the harvester off the rain doesn't actually start.

This has been a issue since I found the mod and started using it.. This will happen each time the harvester is working as the rain starts.

A example of this mornings issue.

Using this mod to harvest field 17 on Felsbrunn map with a seeder also using Courseplay following a few rows behind, While getting a coffee I Got a warning about rain and harvesting I dismissed the warning and switched to the harvester who by that time had driven from field 17 all the way over to field 20 and got stuck on my farm building, I noticed while switching to the harvester that the seeder had driven two rows on field 17 without planting it was just following the course, I switched to the harvester and hit stop driver on courseplay and switched back the the seeder and again hit stop, it stopped but the wheels and dust continued, the game had partially froze, I could switch vehicles for a short time I then hit escape thinking I could save and reload but the autosave kicked in and locked the game up I couldn't do anything after that, I was forced to end the process in task manager.

This was just todays example and the worse one I've had when using courseplay to harvest as the rain starts, sometimes it can get a little laggy when the rain starts while using courseplay running the harvester but corrects itself after stopping the driver.

intel i7 @3.8GHz
16GB ram
GTX 1080 (latest drivers)
windows 10 (latest updates)
fs19 V1.3beta (same issues running V1.2 also)
mods installed but no scripted mods and modded items were in use when I run into this as it was all stock harvester, tractor and seeder.

**Comment by Messy71** [comment]
@boneys26 you could also upload the log for the devs to have a look at
