### ISSUE TITLE
LUA Errors

### ISSUE THREAD

**Issue by MeckyonTour** [Courseplay/courseplay#3374]
Hi, Yesterday I had some ERROR Running LUA methods in my LOG, maybe it will help you

[log.txt](https://github.com/Courseplay/courseplay/files/2940924/log.txt)

**Comment by SavageMkII** [comment]
@MeckyonTour update CP to latest version. That should resolve the CP related errors in your log. Also, you have an incredible amount of warnings and errors from other mods in there. Try eliminating those .
 How to create a proper bug report for the CP devs:
https://github.com/Courseplay/courseplay/wiki

**Comment by MeckyonTour** [comment]
Thanks@SavageMkll, I also discovered, I'm already the biggest mistake of the other mods to remove.
