### ISSUE TITLE
Course calculation limit

### ISSUE THREAD

**Issue by MeckyonTour** [Courseplay/courseplay#3375]
I have a question in advance a few dates:
Map: Kandelin
Fields: 24, 10, 15 etc.
Working width: 6 meters

Can it be that the CP has built in a limitation when calculating the course? Because after about 3 minutes calculation comes a warning message and then CP has only calculated the headland or is that now first thought and will be developed later?

Kurs Berechnung Begrenzung 
Ich habe mal eine Frage vorab ein paar Daten: 
Map: Kandelin 
Felder: 24, 10, 15 etc.
Arbeitsbreite: 6 Meter

Kann es sein, das CP bei der Berechnung des Kurses eine Begrenzung eingebaut hat? Weil nach ca. 3 Minuten Berechnung kommt eine Warnmeldung und dann hat CP nur das Vorgewende berechnet oder ist das jetzt erstmal so gedacht und wird später weiter entwickelt?

**Comment by sootysax** [comment]
screenshot??

**Comment by MeckyonTour** [comment]
Hier meine Screenshots:

![screenshot 2019-03-07 14 36 08](https://user-images.githubusercontent.com/48213617/53960560-e0390600-40e6-11e9-9ae2-b03bc1118f5c.png)
![screenshot 2019-03-07 14 38 33](https://user-images.githubusercontent.com/48213617/53960578-e7f8aa80-40e6-11e9-8233-b234718c4795.png)
![screenshot 2019-03-07 14 38 50](https://user-images.githubusercontent.com/48213617/53960584-ed55f500-40e6-11e9-8ac7-6be3ccabba73.png)
 Weiß da jemand was da verkehrt läuft? oder sind die Felder einfach zu groß?

**Comment by pvaiko** [comment]
A log with debug channel 7 would help. 

But regardless, this field has so many little corners/nooks, especially with your headland turn settings that it must be split into way too many blocks to be able to work on it. Then we have a genetic algorithm trying to figure out the best sequence to work on those blocks and I suspect that this algorithm gives up after too many generations (I keep telling people that this is not a trivial thing, there are hundreds of scientific papers published on this topic)

**Comment by pvaiko** [comment]
Actually, it may fail even earlier during the headland generation. Try to get rid of these little nooks, it may help:

![image](https://user-images.githubusercontent.com/2379521/53965535-05ae1b80-40b7-11e9-83e5-92d2d3c2f52c.png)

**Comment by MeckyonTour** [comment]
Danke für die schnelle Antwort, Peter. Aber wie soll ich die Ecken weg bekommen? Das Feld wird ja von CP gescannt und wenn ich die Einstellung nutze, das er erst die Bahnen und dann das Vorgewende benutzen soll, kommt auch nur das Vorgewende, selbst wenn ich nur zwei oder drei Vorgewende mache.

**Comment by pvaiko** [comment]
Die Ecken kannst Du wegbekommen mit einem selbstdefinierten Feldrand.

Wie gesagt, ein Log mit Debug Channel 7 würde helfen. Hast Du schon die Vorgewende mit runden Ecken probiert? Geht es mit den einzelnen Felder? 

Du kannst auch deine Fielddefinitionen generieren und hier posten wie in Wiki beschreiben ich kann aber nichts versprechen, das ist wirklich ein Extremfall hier.

**Comment by MeckyonTour** [comment]
Mit den Runden Ecken das muss ich mal ausprobieren, wenn ich an das Feld wieder rankomme, das war eine Mission und da musste ich Zuckerrüben ernten und dort kam dieser Kurs herraus. Die Map ist gut geeignet für CP zu testen, denn da sind viele Extremfälle ;)

Zu Debugchannel 7: Wie muss ich da denn vorgehen, wenn ich den Kurs generiert habe dann auf die 7 klicken?

**Comment by pvaiko** [comment]
> Zu Debugchannel 7: Wie muss ich da denn vorgehen, wenn ich den Kurs generiert habe dann auf die 7 klicken?

Bevor du generierst.

**Comment by MeckyonTour** [comment]
also erst auf die 7 und dann generieren lassen? Bekommt ihr das dann, oder wie muss ich weiter vorgehn.... oh gott mein Englisch ist so schlecht.

Nutze den CP jetzt seit LS17 und habe bisher kaum was reported oder so und wollte euch jetzt nur helfen bei der Entwicklung und nun wirds immer komplizierter ^^

**Comment by pvaiko** [comment]
> also erst auf die 7 

Ja. https://github.com/Courseplay/courseplay/wiki

**Comment by MeckyonTour** [comment]
Ich hab jetzt mal auf einem anderen Feld ein paar Kurskombinationen versucht zu berechnen, kommt aber immer nur Vorgewende, hab den Debug 7 aktiviert gehabt, kannst du mal schauen?

**Comment by pvaiko** [comment]
Du musst das Log hier posten.

**Comment by MeckyonTour** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/2942575/log.txt)

**Comment by pvaiko** [comment]
Ja, das Feld wird auf 13 Blocks aufgeteilt und das is ein wenig extrem und wir geben auf. 

Kannst trotzdem probieren, diese Zeile auskommentieren (mit //) und sehen was dann passiert:

https://github.com/Courseplay/courseplay/blob/7ad5e0360a4f463f479ccf360d5c38215688f741/course-generator/center.lua#L251

**Comment by MeckyonTour** [comment]
Was meinst du mit auskommentieren? hinter der Zeile dann (//) hinzufügen? ohne ( ) versteht sich

**Comment by pvaiko** [comment]
Bin ein Idiot, arbeite mit zu viele verschiedene Programmiersprachen gleichzeitig....

Also, nicht // sondern -- (zwei bindestrich) vorne, so:
-- return nil, 0, 0, nil, false

**Comment by MeckyonTour** [comment]
Peter, kein Problem, wir sind alle nur Menschen... lach

Ich lad mir gleich mal die aktuellste Version runter und probier das mal aus. ;)

**Comment by MeckyonTour** [comment]
Hey Peter, das funktioniert :D
Aber der hat jetzt geschlagenen 12-13 Minuten gebraucht um den Kurs zu berechnen
![screenshot 2019-03-07 19 55 58](https://user-images.githubusercontent.com/48213617/53982409-260cc300-4115-11e9-976e-79d73646e502.png)
![screenshot 2019-03-07 20 09 00](https://user-images.githubusercontent.com/48213617/53982417-2c02a400-4115-11e9-8627-b40e719a6099.png)
 Und wenn ich das gerade richtig registriert habe funktioniert auch deine Funktion mit Geräte anheben und senken ;)

**Comment by MeckyonTour** [comment]
Peter, ich zieh meinen Hut vor dir ^^
Das sind meine Einstellungen für das Feld....
![screenshot 2019-03-07 20 20 39](https://user-images.githubusercontent.com/48213617/53987093-48580e00-4120-11e9-9fe0-f18101de4803.png)

... und nach Sage und Schreibe 15- 20 Minuten Berechnung schmeißt mir CP einen Kurs mit über 24.000 Wegpunkten raus und der funktioniert auch noch :D 
![screenshot 2019-03-07 20 39 48](https://user-images.githubusercontent.com/48213617/53987155-7d646080-4120-11e9-8712-544d2a17414d.png)

Diesen Vorgang hab ich direkt bei zwei weiteren Felder bzw Wiesen ausprobiert und siehe da ^^

![screenshot 2019-03-07 21 13 22](https://user-images.githubusercontent.com/48213617/53987187-9836d500-4120-11e9-84c1-437982d46369.png)
![screenshot 2019-03-07 21 25 58](https://user-images.githubusercontent.com/48213617/53987191-9e2cb600-4120-11e9-9d0e-068c7503a9d4.png)

Kann ich dann davon ausgehen, das es mit der nächsten Version erscheinen wird, oder muss ich mir das immer umschreiben? 

Lieben Gruß Micha

**Comment by pvaiko** [comment]
Increased maximum number of blocks in ac04a94ad77f330800a6eda1844d3ab81f3a143d
