### ISSUE TITLE
(Suggestion) Combine Engine Off When Raining

### ISSUE THREAD

**Issue by kybandy** [Courseplay/courseplay#3379]
An idea when there is inclement weather: the combine could shut off its engine if Fuel Save mode is on.

**Comment by Falkwa** [comment]
everything should shut off imo...  been noticing lately that the only thing that does shut off is my conmine unload routes...   everything else just runs and runs even if they finished the task.

**Comment by kybandy** [comment]
Is it just me, or when the combine engine shuts off when full will it not automatically start back up and continue harvesting? I have to hit "Stop Driver" and then "Drive Course" to get it to work again.

**Comment by BoxerHUN** [comment]
> 
> 
> Is it just me, or when the combine engine shuts off when full will it not automatically start back up and continue harvesting? I have to hit "Stop Driver" and then "Drive Course" to get it to work again.

Confirmed ... well with me. If the combine is not 100% full, then it will expose the supplier.

**Comment by pvaiko** [comment]
> expose the supplier

??

**Comment by BoxerHUN** [comment]
> 
> 
> > expose the supplier
> 
> ??

I'll show you ...

**Comment by BoxerHUN** [comment]
https://www.youtube.com/watch?v=LT1Mq0YmeK8

**Comment by pvaiko** [comment]
@BoxerHUN open a new issue for that.  

(Nem értettem mi az hogy "expose supplier", de most már látom, kösz)
