### ISSUE TITLE
Supported Maps?

### ISSUE THREAD

**Issue by Darkklotz** [Courseplay/courseplay#3381]
This is not an issue:  But I am wondering if there was a list anywhere of Courseplay supported or CP friendly maps?

**Comment by Knowen** [comment]
I think CP supports every map. As long as there are fields on it and they are marked as farmland so CP can recognise them. Some modes of CP are not working yet, but that’s not a big deal. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sootysax** [comment]
@Darkklotz If you want to help the developers beta test CP (otherwise you should wait for the release), then you should stick to maps that are available on Giants Modhub so the devs can easily troubleshoot.
