### ISSUE TITLE
Offset with Case 9240 harvester

### ISSUE THREAD

**Issue by Markojag27** [Courseplay/courseplay#3383]
When unloading harvester, have to set offset to 11m, automatic 9.2m is too close to harvester and grain don't fill up trailer

**Comment by iljarogoff** [comment]
Same here, offset has to be adjusted manually

**Comment by Knowen** [comment]
Sometimes my helper get the right distance automaticly, but in 8 of 10 times i have to adjust it.

**Comment by Markojag27** [comment]
If you once set it up manually, courseplay remeber it for this tractor you have bused

**Comment by ThomasGaertner** [comment]
#3311
