### ISSUE TITLE
Course Generating Direction = actually Traktor Direction ?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#3384]
Is this possible to generate a course with the actually tractor direction?
With the direction select it is only possible all 22.5degre.
My map has more angle directions. And some fields are in 5.6degree
Lg
Andreas

**Comment by pvaiko** [comment]
Have you tried the 'longest edge' option?

**Comment by andreasthu** [comment]
Yes i have.
Cp cant generate this course with longest esge.
I have v6.01.  0124.
Will try later again with other options.
Lg
Andreas

**Comment by pvaiko** [comment]
Which map is this? Do you have a screenshot of that field? Do you have a log with debug channel 7 trying to generate?

**Comment by pvaiko** [comment]
@andreasthu BTW, on the Advanced course gen screen we have 5 degree steps:

![image](https://user-images.githubusercontent.com/2379521/54087827-2d0a2000-4325-11e9-963d-4c90ac36b30f.png)

**Comment by andreasthu** [comment]
ok, thanks.
i doesnt see that bevore
there was only N, NNE, NE, ENE, E,...

ok, here is a zip, with the needet files,
[courseplay.zip](https://github.com/Courseplay/courseplay/files/2949683/courseplay.zip)
it is map felsbrunn, field25 doesnt work with longest edge,
the longest edge is ca 50,6°, (along the street)
![fsScreen_2019_03_10_17_05_32](https://user-images.githubusercontent.com/24860501/54087878-ff8a9a00-4357-11e9-80a3-a0e5cfce2edd.png)
![fsScreen_2019_03_10_17_06_13](https://user-images.githubusercontent.com/24860501/54087880-02858a80-4358-11e9-9475-e69d7d6197ea.png)

field 28/29 works with it, there is the longest edge 5,6°, also across the steet
![fsScreen_2019_03_10_17_02_45](https://user-images.githubusercontent.com/24860501/54087882-09ac9880-4358-11e9-9cdc-0702d8293598.png)
![fsScreen_2019_03_10_17_03_28](https://user-images.githubusercontent.com/24860501/54087884-0e714c80-4358-11e9-97f4-0afffd7e19a0.png)

lg
andreas

**Comment by pvaiko** [comment]
The course gen works with 2 degrees resolution, mostly for performance reasons when searching for the best angle.

If you want to play with this you can try changing this 2 to 1 for the longest edge to have a better resolution:
https://github.com/Courseplay/courseplay/blob/f6f3583fe91bb62883c5b4a4c02c2d9fb0ccbab1/course-generator/geo.lua#L232

**Comment by KenStumich** [comment]
i think its time to advice the tester to use the new course generator more often.  i dont think there are many ppl out there who know the differences . btw .. no work-width in the "new" gen :)

**Comment by pvaiko** [comment]
@KenStumich yeah, we wanted to remove the entire HUD page. What do you mean there's no work width?

**Comment by KenStumich** [comment]
the button to generate the work width

**Comment by Tensuko** [comment]
That Button is missing yea, but normaly the width gets callculated correctly.
And for me I don't think it is hard to chane that to the right width.
As long as I got an option to do it, its fine.

As I suggested in another issue, put the Fieldscanner in that Menu with advanced options like Name the Field and not only use Numbers (if that is possible) for like combined Field (F4+12+26) or anything like that.

**Comment by andreasthu** [comment]
![fsScreen_2019_03_12_11_52_14](https://user-images.githubusercontent.com/24860501/54194877-915fe780-44bd-11e9-9d36-d85752a5fbaf.png)


> 
> 
> The course gen works with 2 degrees resolution, mostly for performance reasons when searching for the best angle.
> 
> If you want to play with this you can try changing this 2 to 1 for the longest edge to have a better resolution:
> 
> [courseplay/course-generator/geo.lua](https://github.com/Courseplay/courseplay/blob/f6f3583fe91bb62883c5b4a4c02c2d9fb0ccbab1/course-generator/geo.lua#L232)
> 
> Line 232 in [f6f3583](/Courseplay/courseplay/commit/f6f3583fe91bb62883c5b4a4c02c2d9fb0ccbab1)
>  local width = 2

yes, it works now.
but i have changed the 
```
> Line 232 in [f6f3583](/Courseplay/courseplay/commit/f6f3583fe91bb62883c5b4a4c02c2d9fb0ccbab1)
>  local width = 2
```
to
`>  local width = 0.5`

**Comment by pvaiko** [comment]
0.5 may work ok for such a small field what people with bigger fields are going to complain, so I just close this now without changing anything.

**Comment by andreasthu** [comment]
Ok, 
I will plough this field after harvesting with 45degree.
So it is no longer a problem.
Lg
Andreas
