### ISSUE TITLE
Gülle ausbringen

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#3385]
Hello
Is it actually already possible that the driver puts out the manure on the field and then then back to the yard to refill.

Or does not it work yet?

Because I have retraced a course where the driver drives from the field to the yard fills the manure and then drives to the field and a second course for fertilizing and sowing on the field.
I've put the two courses together, but if the manure cart on the field is empty, he shows me down left, empty cart please refill

**Comment by sootysax** [comment]
the fieldwork course needs to be first, then the refill course

**Comment by ThomasGaertner** [comment]
@Hendirk : did you try that ?

**Comment by Hendirk** [comment]
Hello Thomas
Yes, I first took the course to the field and then the course to the farm.
Then I put the two courses on the mode fertilizing and sowing and then the driver has spread the slurry on the field and then filled the car back to the yard at the stable. I drove Samson slurry tanker with a towing hose and he worked the boom together on the road trip.
Works very well


Gesendet von Mail für Windows 10

Von: Thomas Gärtner
Gesendet: Mittwoch, 13. März 2019 13:43
An: Courseplay/courseplay
Cc: Hendirk; Mention
Betreff: Re: [Courseplay/courseplay] Gülle ausbringen (#3385)

@Hendirk : did you try that ?

**Comment by Chris2996** [comment]
Answer is there. Can be closed.
