### ISSUE TITLE
Ladewagen senkt PickUp nicht ab

### ISSUE THREAD

**Issue by alibaba258** [Courseplay/courseplay#3386]
Hallo zusammen,

mit der Version .00100 habe ich das Problem das ein Ladewagen beim sammeln von Stroh nicht mehr den Pickup senkt und anschaltet. Das Problem besteht bei einfachen Kursen sowie bei kombinierten Kursen. Das ganze lasse ich Modus Feldarbeit laufen. 

Senke ich den Pickup manuell und schalte ihn auch manuell ein bevor ich den Abfahrer einstelle läuft alles ohne Probleme. Sobald der Fahrer aber vom abladen (kombinierter Kurs) wieder am Feld startet, bleibt der Pickup wieder oben.

Beste Grüße

**Comment by pvaiko** [comment]
Das ist schon längst behoben, wir sind mittlerweile bei 126.
