### ISSUE TITLE
0127 present in installed mods, doesnt show when starting a save

### ISSUE THREAD

**Issue by adorhun** [Courseplay/courseplay#3388]
hi!
i've updated to the new version (0127), its present in the installed mods list.
but when i start a save, or try starting a new one, its not in the list.
![cp_127_mod list](https://user-images.githubusercontent.com/5048235/54143109-10531280-4421-11e9-99e0-3ec7bd38fd69.PNG)
![cp_127_game start](https://user-images.githubusercontent.com/5048235/54143114-12b56c80-4421-11e9-8650-8d2ba4dbe5ae.PNG)

**Comment by Falkwa** [comment]
working fine for me.   might just have to delete and redownlaod/install

**Comment by ThomasGaertner** [comment]
Log ?????????????????????????????????
