### ISSUE TITLE
Abkippen

### ISSUE THREAD

**Issue by franky135** [Courseplay/courseplay#3389]
Wenn der Helfer etwas abkippen soll an Verkaufstriggern hält er nicht an. Er öffnet Plane und Klappe, fängt an abzuladen und lädt den Rest irgendwo auf dem Rückweg auf der Strasse ab (Modus Beladung am Startpunkt). Im Combimodus fahren die Fahrzeuge an der Abladestelle vorbei und fangen erst dahinter an abzuladen. Dann wird auch die Lenkung der Fahrzeuge träge, sodass sie nach Kurven und Kreuzungen anfangen zu pendeln und zick-zack fahren.

**Comment by KenStumich** [comment]
welche map
welche version von cp 
und ein logfile wär auch anzuraten.
und zum schluss  normalerweise in englisch
https://github.com/Courseplay/courseplay/wiki

**Comment by franky135** [comment]
CoursePlay Beta v6.00.00033 FS19
Map is called Nordfriesische Marsch
log is clean- 2 callstacks from a mod i had. after deleting it there are no issues shown so far.

Sorry for that i wrote in german before- my english is not the best-

**Comment by KenStumich** [comment]
first, pls update to the newest version  (as of now 0127)
2. if your encouter the problem again, check on an official map too, so the devs can reproduce the problem itself, if necessary. 
3. the devs can german, but this is an international project, so avoid it. they call if its too terrible.
little tip for that- read the translations xml file to find the neccesary translation for specific menue points e.g. pathfinding - fruchtumfahrung.

for futher info ask here and i will help

**Comment by franky135** [comment]
Thank you for your fast support. I will try the update and otherwise tell you if it still doesnt work.

**Comment by KenStumich** [comment]
pls close this issue by yourself, and if nessesary open a new one if the problem still exist.
