### ISSUE TITLE
Grain Transport and Combi mode Unload

### ISSUE THREAD

**Issue by jasonvh1** [Courseplay/courseplay#3390]
Driver stops at marked unload point, starts unloading but the crop does not unload. Have to stop the driver, cancel unload and then unload manually. This was tested with multiple trailers while doing contracts..

**Comment by KenStumich** [comment]
how about this ?

....if you're still ok with this, please remember to post possible issues that you find in the developer version. That's the only way we can find sources of error and fix them. Be as specific as possible:

- [ ] tell us the version number
- [ ] only use the vehicles necessary, not 10 other ones at a time
- [ ] which vehicles are involved, what is the intended action?
- [ ] Post! The! Log! to Gist or PasteBin

For more details on how to post a proper bug report, visit our Wiki
```

**Comment by sootysax** [comment]
#3311

**Comment by ThomasGaertner** [comment]
yes I can confirm #3311 also for contracts ...
