### ISSUE TITLE
bad argument?

### ISSUE THREAD

**Issue by BlackMomba** [Courseplay/courseplay#3391]
![fsScreen_2019_03_12_12_17_56](https://user-images.githubusercontent.com/48421173/54223132-d6d3e300-44c4-11e9-81b6-a68cc4a06c48.png)

Wondering how I can fix this ussue?

**Comment by pseikoNL** [comment]
Maybe you can start with posting your log here, then we can help troubleshoot the issue.

**Comment by Falkwa** [comment]
how do you get that to show up?

**Comment by Shakermt** [comment]
I have the same issue with the same error. I get mine on every map when I try to save the game. After playing for a good amount of time (say 20min + ) when I go to save the game I get that error.

**Comment by Shakermt** [comment]
ok I found the issue, I had downloaded a mod by kman that was his Peterbilt 567. I deleted it and no more issue.

**Comment by pseikoNL** [comment]
@Falkwa
http://courseplay.github.io/courseplay/en/faq/index.html
—> How to provide a nice and sexy bug report
