### ISSUE TITLE
Suggestion: Add the convoy feature to other work modes

### ISSUE THREAD

**Issue by cyberndj** [Courseplay/courseplay#3393]
Hi,

I would like to suggest that the Combine Convoy feature be added to the other work modes (mostly Seed-n-Feed and Fieldwork). I see the suggestion in #2579, and i'm assuming it was closed because it was for FS17. 

Thought is to add the feature to a milestone (6.1+?) so current work can be focused on getting current features established and bugs squashed. Hopefully it will be as easy as taking the current snips of code and putting them into a new file so they can be referenced from multiple locations.

**Comment by Falkwa** [comment]
i 2nd this idea

**Comment by Tensuko** [comment]
The Combine does have a Convoy Mode becouse of the pipe I would say. When one is full and the other comes near, they crash into each other and can't get unloaded. This problem you won't rly have with seeder.
You just tell CP at the Coursegeneration, how many Drivers you want to have and place them on the Line you want him to be. I suggest you to use the regular line switch instead of symmetric one. 
Else then blue one comes down while maybe the orange one goes up and they slightly collide (maybe, collission model issue or something).
https://courseplay.github.io/courseplay/en/faq/index.html
But you got to try it on your own.

**Comment by ThomasGaertner** [comment]
@pvaiko : isnt it allready implemented ?

**Comment by pvaiko** [comment]
I haven't tested it but it is in FieldworkAIDriver which is the common code for mode 4 and 6 and I don't see why it would not work.

**Comment by cyberndj** [comment]
@Tensuko I've  set up many courses with multiple tools and symmetric/asymmetric lane changes and they mostly work. I've had a few courses where there have been a refill course added with a wait point thats been queued up, so when they implements get back to the field, they can collide (especially at the turns). I also tend to under size the working width so I don't get those pesky blank strips that sometimes happen.

@pvaiko & @ThomasGaertner, would it be as simple as adding the feature in the hud?
Update Line 813 in hud.lua to be?
`elseif vehicle.cp.mode == courseplay.MODE_SEED_FERTILIZE or vehicle.cp.mode == courseplay.MODE_FIELDWORK then`

**Comment by pvaiko** [comment]
@cyberndj yes it is probably that simple. If you really want to help you make the change and test it and then create a pull request ...

**Comment by cyberndj** [comment]
Hi, I went in and updated a local copy with the edit. I was able to get the Feed-n-Seed and Fieldwork modes to work with 'normal' implements. I also updated a bunch of the text to be capitalized or camel-cased. 

I think I made a proper pull request. It is my first one ever so please let me know if I did it wrong.

![fsScreen_2019_03_14_18_06_08](https://user-images.githubusercontent.com/16530317/54405750-bbb7cd80-4694-11e9-9eb1-ea5b44bf9868.jpg)
![fsScreen_2019_03_14_18_07_21](https://user-images.githubusercontent.com/16530317/54405751-bbb7cd80-4694-11e9-9561-5ae7fa3f7ea5.jpg)
![fsScreen_2019_03_14_18_24_19](https://user-images.githubusercontent.com/16530317/54405752-bc506400-4694-11e9-9ca0-994b4cfd55d7.jpg)
![fsScreen_2019_03_14_18_24_54](https://user-images.githubusercontent.com/16530317/54405753-bc506400-4694-11e9-9e6c-5724781dffd1.jpg)
