### ISSUE TITLE
no unloading

### ISSUE THREAD

**Issue by franky135** [Courseplay/courseplay#3394]
Yesterday i already had a problem with let the driver stop at the unloadingpoints. You pleased me to update to version 0127.
Today i tried with new version.
With old version the driver started unloading on sellpoint without stopping and lost the grain all over the street. With 0127 he stopps at sellpoint and starts tipping without unloading. Than he drives back to startpoint. i always have to stop the driver and unload manual.

The log is clean.
The map is Nordfriesische Marsch.

**Comment by KenStumich** [comment]
are you german ? selling on NF-Marsch is no problem. maybe i can help you on ts3 or discord somewhere in german. 
sounds like you have no expirience at all (your old version was the first version for public beta)

**Comment by KenStumich** [comment]
test it on NF-Marsch
round-courst mode 1 farmsilo (load) to trainstation (sell) and back. no problem at all.

start unloading
![fsScreen_2019_03_12_23_17_03](https://user-images.githubusercontent.com/28400454/54240131-80df5980-451d-11e9-8cd1-359aa8ad1179.png)

finisch
![fsScreen_2019_03_12_23_17_16](https://user-images.githubusercontent.com/28400454/54240137-8472e080-451d-11e9-872d-e888c27a1c8a.png)

**Comment by franky135** [comment]
hi! i am using courseplay since the first version as im playing ls since 2007. Trouble like this i never had before. i use courseplay very much- usually i have 1 or 2 combines working with it plus about 4 drivers for graintransport or 1 harvester plus 3 drivers for the corn, fieldwork like mowing,tedding, swathing, baling, plowing, seeding and all those things i do with cp. And it was working well in this game too. But suddenly the problems started: drivers had problems to find the course for few hours and now they suddenly dont unload anymore. They tell me sellpoint is reached, stop at the end of the trigger, start tipping but dont unload and if i dont stop they start driving and unload on the streets while driving.
i didnt add new mods- all these mods were working together with cp but from one to the next moment suddenly the trouble started.
I watched the video too but its all like im doing it amready. i also tried to set unloadpoints into the course too but the problem stays- loading at the start works, unloading doesnt.

**Comment by KenStumich** [comment]
I had assumed that you have little experience, because you mentioned in the first message v033.
no offense
I can not explain your sudden mistakes with your description.
I hope someone else can help you

**Comment by sootysax** [comment]
still no log..   you wont get any help from the devs until you follow protocol

**Comment by ThomasGaertner** [comment]
@franky135 : which mode did you use ? can you make a screenshot of the situation. I fear I have not enought debugs in the code, thats a TODO for me. If you can replicate it, please give me the courses and savegame

**Comment by franky135** [comment]
Hi! I tested some things on my own and guess i found the problem. Potatoes! I was harvesting and selling potatoes. I tried different unloadingpoints and tippers. with grain it works everywhere. But potatoes dont work on every point like Getreidehandel or Grosser Hofsilo at Nordfriesische Marsch.

@ThomasGaertner : I used Beladung am Startpunkt to sell from grosser Hofsilo to Getreidehandel and to Depot and combimode to bring the potatoes from field to grosser Hofsilo.

The log made few errors too today. If anybode please can tell me how to upload it here together with the savegame i will do it if it can help to fix this. Or could it be a problem of the map?

**Comment by pseikoNL** [comment]
@franky135, as asked before by @sootysax, can you post your log here? Do you have the filltype mass adjustment mod active?

**Comment by franky135** [comment]
Hope this works...
[log.txt](https://github.com/Courseplay/courseplay/files/2972188/log.txt)

**Comment by franky135** [comment]
the errors in my log shouldnt do anything to the game as far as i know?

**Comment by ThomasGaertner** [comment]
please test again with debug channel 1 active and post the whole log here. thanks

**Comment by franky135** [comment]
I tried with debug channel 1 and with 2 also after the problem stayed before you wrote to me yesterday evening. The log became so big that i had to put into a zip-folder to upload here.

[log.zip](https://github.com/Courseplay/courseplay/files/2974141/log.zip)

Nothing changed. Its still the same that a few trigger are not seen by the cp-driver. So he says point is reached, drives slowly over the trigger, starts tipping without unloading and starts driving back to startpoint while losing his load at the street. But its just with potatoes!

By the way: Thank you for so much support!

**Comment by ThomasGaertner** [comment]
2019-03-15 21:06 :12 [dbg1 lp33755] 820 Vario (#4): transformId=222802: exactFillRootNode
2019-03-15 21:06 :12 [dbg1 lp33755] 820 Vario (#4): transformId 222802 is in tipTriggers (#16) (triggerId=222802)
2019-03-15 21:06 :12 [dbg1 lp33755]     trailerFillType=9 POTATO
2019-03-15 21:06 :12 [dbg1 lp33755]     trigger (222802) does not accept trailerFillType (9)
2019-03-15 21:06 :12 [dbg1 lp33755]     trigger (222802) acceptedFillTypes:
2019-03-15 21:06     2: WHEAT
2019-03-15 21:06     3: BARLEY
2019-03-15 21:06     4: OAT
2019-03-15 21:06     5: CANOLA
2019-03-15 21:06     6: SUNFLOWER
2019-03-15 21:06     7: SOYBEAN
2019-03-15 21:06     8: MAIZE

**Comment by ThomasGaertner** [comment]
no questions anymore....

**Comment by KenStumich** [comment]
lol ... not accepted fill type. let me quote this...

> hi! i am using courseplay since the first version as im playing ls since 2007. Trouble like this i never had before.....

nix für ungut @franky135 . wir haben alle mal einen schlechten tag

**Comment by franky135** [comment]
well...if you dont have any questions anymore- i have! And if this is just a mistake by me you can explain this for sure:
![fsScreen_2019_03_20_18_09_24](https://user-images.githubusercontent.com/48451440/54704921-fcec2980-4b3b-11e9-921f-44469c91ffed.png)
![fsScreen_2019_03_20_18_09_50](https://user-images.githubusercontent.com/48451440/54704923-fcec2980-4b3b-11e9-8ae1-d823995d829b.png)
![fsScreen_2019_03_20_18_10_04](https://user-images.githubusercontent.com/48451440/54704927-fd84c000-4b3b-11e9-8fbd-48230dad3691.png)
![fsScreen_2019_03_20_18_10_10](https://user-images.githubusercontent.com/48451440/54704929-fd84c000-4b3b-11e9-83a4-b1197fffef57.png)
![fsScreen_2019_03_20_18_10_12](https://user-images.githubusercontent.com/48451440/54704930-fd84c000-4b3b-11e9-8b08-d5a9dcd09cea.png)
![fsScreen_2019_03_20_18_04_32](https://user-images.githubusercontent.com/48451440/54704931-fd84c000-4b3b-11e9-88df-ffb9e43849ec.png)
![fsScreen_2019_03_20_18_05_35](https://user-images.githubusercontent.com/48451440/54704932-fe1d5680-4b3b-11e9-8bbd-c9fc44139b92.png)
![fsScreen_2019_03_20_18_05_50](https://user-images.githubusercontent.com/48451440/54704933-fe1d5680-4b3b-11e9-8156-8b05a4e4b838.png)

As you see im bringing the potatoes to the big farmsilo. I can fill the joskin with potatoes, i can unload potatoes manual but the cp-driver does like shown on the screenshots. The same happen at "Getreidehandel"

**Comment by ThomasGaertner** [comment]
maybe it depends on the unload point which may not be there ?
and by the way : I couldn't manage to tip potato into the farm silo 

![fsScreen_2019_03_20_22_49_36](https://user-images.githubusercontent.com/3279913/54721727-089f1680-4b63-11e9-93c4-f452f89e65a5.png)

so maybe you can tell me how you did it ?

**Comment by franky135** [comment]
is there a difference between the small and big farmsilo?
or is it because im playing the Nordfriesische Marsch?

**Comment by ThomasGaertner** [comment]
nope and even on NF Marsch i couldn't do it .
![fsScreen_2019_03_21_17_13_36](https://user-images.githubusercontent.com/3279913/54767196-f5408980-4bfc-11e9-8bc2-e250c7ada996.png)

do you use any mods for that  ?

**Comment by StefanBraun2001** [comment]
@ThomasGärtner Use a big silo extension. Forse some reason you can store potatoes and sugar beets in it. Maybe a giants bug?

 

Von: Thomas Gärtner [mailto:notifications@github.com] 
Gesendet: Donnerstag, 21. März 2019 17:16
An: Courseplay/courseplay
Cc: Subscribed
Betreff: Re: [Courseplay/courseplay] no unloading (#3394)

 

nope and even on NF Marsch i couldn't do it .
 <https://user-images.githubusercontent.com/3279913/54767196-f5408980-4bfc-11e9-8bc2-e250c7ada996.png> fsScreen_2019_03_21_17_13_36

do you use any mods for that ?

**Comment by franky135** [comment]
StefanBraun2001 is right. The big farmsilo plus 2 extensions i use. 
I just tested in a new game- just the farmsilo doesnt take potatoes. With extension it takes.

**Comment by ThomasGaertner** [comment]
Crazy

**Comment by franky135** [comment]
nobody said it would be easy:P

**Comment by ThomasGaertner** [comment]
So it’s definitely a Giants thing. I don’t want to change our system for it, so I will close here with won’t fix
