### ISSUE TITLE
FS19 Courseplay 6.01.00128: lag nach dem Einstellen des Helfers

### ISSUE THREAD

**Issue by NEA1971** [Courseplay/courseplay#3395]
Zumindest beim Sähen und Pflügen habe ich das Problem, dass das Spiel nach dem Einstellen des Helfers unglaublich hängt und auf keinerlei Eingaben mehr reagiert. Kann das nur damit beheben, das Spiel ganz über den Taskmanager abzuwürgen.
Ist etwas bekannt, ob es hier eventuell ein Problem mit einem Mod gibt?

**Comment by Tensuko** [comment]
Logfile ? Screenshot ?

https://github.com/Courseplay/courseplay/wiki

Ansonsten ist das nur Rätzelraten.

**Comment by NEA1971** [comment]
jo, mit dem Screenshot wird ein bischen schwierig, das Ruckeln darzustellen - ich hab's mal mit einem [Video](https://youtu.be/bjlBTfN7yvk) versucht... Ansonsten [hier](https://gist.github.com/NEA1971/7b073cc601437542f3a8f5f472292bf0) das Log.

Im Log sind jede Menge Meldungen wg. dem Mod "FS19_realDirtColor" - ich habe das mal deaktiviert und dann läuft das auch. Von daher kann hier wieder zugemacht werden.
