### ISSUE TITLE
Error: Running LUA method 'loadMapFinished'

### ISSUE THREAD

**Issue by RedOhne** [Courseplay/courseplay#3396]
Hi, 

I've just updated to the latest CP Version (131). When I load my savegame with the map "Schwarze Pumpe" I get the following error:

2019-03-13 19:29 Error: Running LUA method 'loadMapFinished'.
2019-03-13 19:29 D:/Users/timfr/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/hud.lua:96: table index is nil

This also happens with my older Ravenport Savegame. 

Do you need any savegame  or additional log?

Best regards,
Tim

**Comment by RedOhne** [comment]
I've downloaded no each version up to the one to test, since when this error occured. V128 is working so I guess it was deliverd with 129?

**Comment by Tensuko** [comment]
I had no error in any Version so far.
128, 129, 130 and just now tried 131 and log is clean.
Can you post your full logfile ? You just got to drag and drop it into the Comment Window, no need to upload that file somewhere.

**Comment by RedOhne** [comment]
Attached the log. I've tried to start a new game without any further mods, but only CP. Same error

[log.txt](https://github.com/Courseplay/courseplay/files/2963145/log.txt)

**Comment by Tensuko** [comment]
RealDirtColor is in your ModFolder.
When you started a new savegame, did your just not turn on any mods or put all mods out of your modfolder ?
And what is this error ?
2019-03-13 19:54 Error: D:/Users/timfr/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/courseplay.lua:125: 	COURSEPLAY ERROR: could not load file D:/Users/timfr/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/course-generator/Pathfinder.lua

Are you sure you created the CP .Zip in the right way and not missed something ?

**Comment by RedOhne** [comment]
Hi Tensuko,

I just created a new game without removing them from the folder. The RealDirtColor does not make any issues with the version 129. 

I downloaded the complete code into a zip, opened the folder in it, marked all files and moved them into my FS19_Courseplay.zip. Worked since years. Are you from the developer team?

Tim

**Comment by Tensuko** [comment]
Not from the dev.
But you got 2 Erros that I don't have with the same Version.
Pathfinder.lua not found and the LUA at the end.
So first at all, the RealDirt made many different errors in the past, even for me at a version in a specific situation, so I would take that one out of the Mod Folder 1st, to make sure that isn't the issue.

How I do: download the zip, unzip the whole folder, get into folder, mark all, zip them into a new FS19_Courseplay and copy that on in Modfolder. Worked since years ;) I just think that else: your missed to add the pathfinder.lua to put into your zip, or it doesn't get copy or even downloaded probaly.
I suggest you to just redownload and try it again.
I don't know what happens, if you download while files get updated on github, becosue the last update was about 1 hour ago.

**Comment by RedOhne** [comment]
I gave it another shot. removed the realdirt, downloaded the latest version again. Extracted your way and tried again. Same error. Attached the LS19_CP.ZIP and log.
[FS19_Courseplay.zip](https://github.com/Courseplay/courseplay/files/2963315/FS19_Courseplay.zip)
[log.txt](https://github.com/Courseplay/courseplay/files/2963317/log.txt)

**Comment by pvaiko** [comment]
@RedOhne before you reinstall it make sure you delete the entire courseplay folder from the mod folder. 

It is the stupid Windows still can't handle case sensitive filenames, I renamed pathfinder.lua to Pathfinder.lua...

**Comment by Tensuko** [comment]
Well I also just overwrite the zip in Modfolder. But I delete the CP Github Folder and Zip after created the FS19_Courseplay.zip and moved it into Modfolder so I always got a fresh download and unzip in my downloads.

**Comment by squall39** [comment]
j'ai la même erreur sur n'importe quel map sans mod 2019-03-13 20:29 Error: Running LUA method 'loadMapFinished'.

**Comment by RedOhne** [comment]
@pvaiko : Thanks for the tip with removing the old ZIP first. I only updated the content of the old one. Maybe the new small written pathfinder.lua kept the uppercase P. It's ok now. 👍
