### ISSUE TITLE
How can I change UI default open from right click to ...

### ISSUE THREAD

**Issue by Hubcap-1** [Courseplay/courseplay#3399]
How can I change UI default open from right click to L alt + del in the LUA. I know everyone is busy working on other issues. However I feel the base problem of opening closing the UI is at the core " Right Click". We should omit this command option all together. Also I think if this was not vehicle dependent as to which key bindings open the UI but rather " Universal" it will solve the  problem including the use of mods ( for this issue). Anybody out there help me find how to edit this ? or even better how to remove the option of right click all together?   PS: None of the Mods I'm using are in the unsupported mods list.

**Comment by ThomasGaertner** [comment]
try again with v.151 or higher
