### ISSUE TITLE
How to download CP with no Issue

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/courseplay#3404]
Becouse more and more ppl come here to GitHub like in any other Forum with the same Issue, here is the solution:

To Avoid Issues becouse of renamed Files or any kind of this, follow this steps to get a clear actual CP Version from GitHub:

1) Download the Courseplay_Master Zipfile from GitHub

2) Unzip the Courseplay_Master Folder inside the Zipfile to a place of your choice

3) Open the Courseplay_Master Folder and mark all Files inside (Ctrl+A) and zip them into a brand new FS19_Coursplay.zip

4) Copy the new FS19_Courseplay.zip into your Modfolder

@ThomasGaertner @pvaiko  Stick this to top or delete if not want this here.

**Comment by PromGames** [comment]
The other possibility is to use the cpupdater from ElPatron, I have modified it to be valid for FS19 and allow the user to name the file as he normally does to get the update.

The good thing is that it will automatically update if there is new version

You can find the program in this link. If you have any troubles using it, let me know.

**Comment by PromGames** [comment]
The other possibility is to use the cpupdater from ElPatron, I have modified it to be valid for FS19 and allow the user to name the file as he normally does to get the update.

The good thing is that it will automatically update if there is new version

You can find the program in this link. If you have any troubles using it, let me know.

**Comment by Tensuko** [comment]
Does it look on File Names written with capital letters ?
Like: Path/path ?

**Comment by sootysax** [comment]
I use Github Desktop, and it's super easy to keep up with changes, and send new versions to a 'recently used zip' (mods\FS19_Courseplay.zip)

**Comment by pvaiko** [comment]
@sootysax it would be even easier to just have your git repository in the mods directory.

**Comment by sootysax** [comment]
> @sootysax it would be even easier to just have your git repository in the mods directory.

hot damn, all this time i thought CP needed to be zipped

**Comment by moehre85** [comment]
Hello, Windows users, 
I have written a small script/batch that performs the above steps for you automatically. Maybe it will help one or the other.
It clones or updates with git.exe the repo into the current folder and zips the files to FS19_CoursePlay6.zip then the file must be copied into the mod folder, that goes by script, but I do not want.
Requirements: git (https://git-scm.com/downloads) and 7-Zip (https://www.7-zip.org/download.html)
Since batch files are not supported, the file must be renamed.
[gitclone.txt](https://github.com/Courseplay/courseplay/files/2971667/gitclone.txt)

MfG Möhre

**Comment by pvaiko** [comment]
@moehre85 if you use git then you can clone directly into the mod folder, no zip is needed. Just saying.

**Comment by PromGames** [comment]
This is the program you can use to download the update version of courseplay from GtitHub

[https://drive.google.com/file/d/1bTlK1l_g7JmHnZ7nFPsNFv2aZcMARdlj/view?usp=sharing](url)

**Comment by alpha117** [comment]
HI, what/where do I change the MOD folder location? I have moved my MODs folder to another drive?

Thanks

**Comment by PromGames** [comment]
Just be sure to set the mod folder correctly in the gamesettings.xml file, mod override true and the new mod folder.

**Comment by alpha117** [comment]
Already done, since day 1

![image](https://user-images.githubusercontent.com/30005040/54512213-5b05ea80-494b-11e9-8605-58f5a9d26e56.png)

**Comment by alpha117** [comment]
Still saves it to the default....only MOD in that folder

![image](https://user-images.githubusercontent.com/30005040/54512292-a4563a00-494b-11e9-9943-16a63b837ca9.png)

**Comment by PromGames** [comment]
SET to true directoryoverride in gamesettings.xml and set the directory like this, you have it as False

<modsDirectoryOverride active="True" directory="C:\Users\User\My Games\FarmingSimulator2019\mods" />

You have it wrong as it has a final / that is not correct

**Comment by PromGames** [comment]
SET to true directoryoverride in gamesettings.xml and set the directory like this, you have it as False

<modsDirectoryOverride active="True" directory="C:\Users\User\My Games\FarmingSimulator2019\mods" />

You have it wrong as it has a final / that is not correct

**Comment by PromGames** [comment]
You have an icorrect / in the path. Could be this the reason. ??

**Comment by alpha117** [comment]
I'll change it....let you know

**Comment by alpha117** [comment]
Nope
![image](https://user-images.githubusercontent.com/30005040/54512847-7245d780-494d-11e9-9e04-e1320509cfb9.png)
I've tried 
<modsDirectoryOverride active="true" directory="G:\FS19 Maps\Fenton Forest\"/>
and
<modsDirectoryOverride active="true" directory="G:\FS19 Maps\Fenton Forest"/>

MODS from Mod hub work OK

**Comment by PromGames** [comment]
As a temporary solution, you can just overwrite the path to your desire and direct to your mod folder, just change it with the editor, the .bat file where all the program is.

**Comment by alpha117** [comment]
yep, done  thanks

**Comment by pvaiko** [comment]
Added some magic so there's a zip file created automatically for each version, **[download here](https://github.com/Courseplay/courseplay/releases)**.

**Comment by ThomasGaertner** [comment]
@Tensuko : schick mir ma ne mail bitte.
