### ISSUE TITLE
Waypoint.lua 275 fehler am start

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#3405]
Hallo ich hab deas problem wen ich den kurs starte zum schwaden oder Ballenpressen bekomme ich folgenden fehler;
2019-03-14 15:10 Error: Running LUA method 'update'.
2019-03-14 15:10 C:/Users/Manni/Documents/My Games/FarmingSimulator2019/mods/FS19_courseplay/Waypoint.lua:275: attempt to index a nil value

Courseplay version 6.01.00133

Hier die log;
[log.txt](https://github.com/Courseplay/courseplay/files/2966817/log.txt)

 und hier ein Video:
https://youtu.be/nTincbNEeRU

MFG Mannie313

**Comment by pvaiko** [comment]
Brauche ein Log mit debug channel 12 und 14.

**Comment by Mannie313** [comment]
> Brauche ein Log mit Debug-Channel 12 und 14.

hier bitte 
[log.txt](https://github.com/Courseplay/courseplay/files/2967117/log.txt)
