### ISSUE TITLE
Beta

### ISSUE THREAD

**Issue by tuzlo** [Courseplay/courseplay#3406]
Is this out of Beta testing and available to the public yet?

**Comment by Jimmy-the-Geek** [comment]
No.

**Comment by Tensuko** [comment]
If it gets 'more' to public, you will find it on ModHub in FS19.
Beside that, this version from github is public beta, so feel free to download and use/test it.

But: This is not a Forum like some ppl think, it is for Bugtracking, so this gets closed.
