### ISSUE TITLE
Implements not lowered when unload course end is too close to fieldwork start

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#3407]
@pvaiko das problem ist immer noch da: Waypoint.lua:275: attempt to index a nil value (#3405)
[log.txt](https://github.com/Courseplay/courseplay/files/2967730/log.txt)

Courseplay Version 6.01.00135

MFG Mannie313

**Comment by pvaiko** [comment]
Wie peinlich :) Noch ein Versuch mit 136...

**Comment by Mannie313** [comment]
@pvaiko jetzt geht es aber er geht nich in die arbeitsstellung. sprich er sammelt das stroh nicht auf.

MFG Mannie313

**Comment by pvaiko** [comment]
Ok, das ist ein anderes Problem, passiert nur wenn der Unloadcourse zu nah am Anfang des Feldkurses endet.

**Comment by Mannie313** [comment]
Das hat aber in den vorherigen versionen gut geklappt.

MFG Mannie313

**Comment by pvaiko** [comment]
Ich weiss. Das ist weil ich jetzt Pathfinding drin habe und dieser Fall ist noch nicht sauber implementiert. Wenn du die Fruchtumfahrung auschaltest müsste es wieder funktionieren.

**Comment by Mannie313** [comment]
ok werde ich mal machen.

MFG Mannie313

**Comment by Mannie313** [comment]
@pvaiko wer ist für die feldarbeit und Düngen / Sähen zuständig?

MFG Mannie313

**Comment by pvaiko** [comment]
Zuständig ist hier keiner. Ich habe es implementiert.

**Comment by Mannie313** [comment]
Ich hab da ein kleines problem festgestellt. und zwar fangen die arbeiter nicht am ersten wegpunkt vom feld an sonder an einem ganz anderen punkt auf dem feld. ist immer unterschiedlich wo sie anfangen.

**Comment by pvaiko** [comment]
Reopen if still occurring.
