### ISSUE TITLE
Manure trailer not stopping at waiting point to get refilled

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3408]
This old issue has resurfaced for me, first visited in #3243. wait point set at manure pit on a refill course from the field.   Tractor slows down but rolls past wait point and does not stop to get filled.

https://gist.github.com/sootysax/2d76faeb5955f8692c0af3c7586f35b9

![fsScreen_2019_03_14_15_22_40](https://user-images.githubusercontent.com/6591048/54385586-5f8d8300-466d-11e9-9e61-cd1bbbb9489c.png)

**Comment by Falkwa** [comment]
im noticing the same things on version .135 and .136.    my tippers wont offload at the silo triggers.   just drive right on through.   also noticing extreme lag.   everything was working fine last night using version .127

**Comment by sootysax** [comment]
@Falkwa entirely different issue..  create a new issue and post a log, screenshots, savegame

**Comment by ThomasGaertner** [comment]
@sootysax: can you send me your current course folder to check it and the other issue as well ? cant replicate here...

**Comment by sootysax** [comment]
[#3408_CoursePlay_Courses.zip](https://github.com/Courseplay/courseplay/files/2970991/3408_CoursePlay_Courses.zip)

f6 manure and refill is in the top level folder

**Comment by sootysax** [comment]
[savegame2.zip](https://github.com/Courseplay/courseplay/files/2970998/savegame2.zip)

**Comment by sootysax** [comment]
it must be an issue with conflicting triggers, because I tried coming at the bunker from the opposite direction, and now it stops at the waitpoint..

**Comment by ThomasGaertner** [comment]
you are right, it found the fill trigger of the tanker trailer there. I could write something to use both but I think the risk to break many other situations for it is too high. So I would say won't  fix ....
