### ISSUE TITLE
Issues since 135/136

### ISSUE THREAD

**Issue by Falkwa** [Courseplay/courseplay#3409]
everything is the same as last night when using .127,    now offload runs from combine wont trigger, extreme lag and jumps, harvesters randomly stop harvesting and follow the course and act like they are running.  i have had to force close the game 3 times today.   only thing that changed was updating to 135/136 from 127

**Comment by sootysax** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Falkwa** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/2968888/log.txt)   looks like a bunch of jibberish to me haha

**Comment by sootysax** [comment]
too many mods with errors - that's your problem, not CP

**Comment by Falkwa** [comment]
Every worked just fine with .127 though...

**Comment by sootysax** [comment]
I'm just giving you a heads up...  the only reason you should be posting here is to help beta test Courseplay..   and a log full of errors from I can't even count how many mods you have installed is not supported..  not yet..

**Comment by Falkwa** [comment]
im aware that X mod might not work ect.   some do and some dont..   but everything was working all fine and dandy with .127,   after i went with .135/136 and nothing else was changed nor added ect..  its all broken.

**Comment by Tensuko** [comment]
2019-03-14 18:00 LUA call stack:
2019-03-14 18:00   dataS/scripts/objects/NightIllumination.lua (47) : setShaderParameter
2019-03-14 18:00   dataS/scripts/objects/NightIllumination.lua (19) : new
2019-03-14 18:00   Error: BunkerSilo.onCreate is deprecated!
2019-03-14 18:00   Error: BunkerSilo.onCreate is deprecated!

Take that Mod out first.

When you want to help CP and want find out what is wrong, do this:
- Rename your Modfolder (e.g. mods_all)
- create a new 'mods' Folder
- copy CP in it and try it out
- paste mod by mod in the mods folder and try again and again (you can also go for all mods with 'a' then with 'b' and so on)
- when the error happens after you put a specific mod in it, you got your error source

**Comment by Falkwa** [comment]
> 
> 
> 2019-03-14 18:00 LUA call stack:
> 2019-03-14 18:00 dataS/scripts/objects/NightIllumination.lua (47) : setShaderParameter
> 2019-03-14 18:00 dataS/scripts/objects/NightIllumination.lua (19) : new
> 2019-03-14 18:00 Error: BunkerSilo.onCreate is deprecated!
> 2019-03-14 18:00 Error: BunkerSilo.onCreate is deprecated!
> 
> Take that Mod out first.
> 
> When you want to help CP and want find out what is wrong, do this:
> 
>     * Rename your Modfolder (e.g. mods_all)
> 
>     * create a new 'mods' Folder
> 
>     * copy CP in it and try it out
> 
>     * paste mod by mod in the mods folder and try again and again (you can also go for all mods with 'a' then with 'b' and so on)
> 
>     * when the error happens after you put a specific mod in it, you got your error source

just went through all my mods.   nothing dont have a bunker silo mod.    but turned off alot of crap for that game save and i do have a placeable bunker silo placed..   but its not a mod..  its the one included in the game

**Comment by Falkwa** [comment]
Now thinking some more.    It’s a mod map.    Wonder if that’s popping up from a bga bunker.    There’s a crap load of sunken trees ect.    Might just have to bite the bullet and abandon the map

**Comment by Tensuko** [comment]
Well it is always the best way to see if CP causing the error or a mod in combination with CP, by take out all except CP and start a full vanilla save, if that is ok, add mods untill the error happens.
Then you can better take a look at the issue, becouse you know from where it comes and maybe what causes the issue. Then else talk to the mapper or, for CP, create an issue on github.

Anything else is more guessing what it could be.
Since the last Versions had some changes in bunker filling and speed, it might be a reason why the error happens now and not with .127 but then I would rather say, that the Map Silo is not like the Vanilla one.

-----------
@ThomasGaertner could this be an issue with the last changes (I don't know the Coding stuff) ?

**Comment by Falkwa** [comment]
Interesting observation.    Ya I don’t normal update the master file if it’s a fix that doesn’t affect me.    But still will regardless once I’m 5 updates or so behind.    And ya most fixes was due to bga stuff.    Makes me think it broke the stock one on clover creek

**Comment by ThomasGaertner** [comment]
I suppose, its   " FS19_CloverCreek_multifruit " we don't use the old function
