### ISSUE TITLE
Samson PG II 35 always turned on when Agro SBH4 36 is connected / Spraying before fully unfolded

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3411]
Noticing that no matter what kind of course is running, even if it's a transfer course or a refill course, the Samson PG II 35 slurry spreader is always turned on.  this is only when the Agro SBH4 36 is connected..  I have not tried it with the other attachments (SD700 or TD12). 

![fsScreen_2019_03_14_21_09_09](https://user-images.githubusercontent.com/6591048/54401304-84015380-469d-11e9-9f63-44a7e16f284d.png)

The spreader will also start spraying slurry before the distributor is fully unfolded, losing about 800l of slurry/digestate before getting moving when resuming spraying after a refill.   I believe this to be because the tanker is turned on while it is unfolding. 

https://gist.github.com/sootysax/c021fe8a45142edce2f8bc81843fcf75

I snapped a screenshot where it starts prematurely spraying to identify the time on the log

![fsScreen_2019_03_14_21_30_43](https://user-images.githubusercontent.com/6591048/54402038-cbd5aa00-46a0-11e9-9a0c-b83fe867904e.png)

**Comment by pvaiko** [comment]
This may have been fixed by 3252242e in 197, please reopen if not.
