### ISSUE TITLE
Digestate Refill - only refills on first run

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3412]
https://gist.github.com/sootysax/c20925737aa284ac1667e5a9c3dd09d4

Digestate refill route refills correctly on the first refill run... after that, the refill trigger is not recognized, and the tractor backs all the way up and out without refilling.

Quitting the game and coming back in will allow the course to refill again, but driver loses his place on the field when returning, and heads for the first waypoint again instead.

Fendt 939 Vario / Samson PG II 35 / SAMSON SBH4 36

![fsScreen_2019_03_14_21_17_34](https://user-images.githubusercontent.com/6591048/54401713-22da7f80-469f-11e9-84f1-da1692a36735.png)

**Comment by ThomasGaertner** [comment]
schould be fixed now
