### ISSUE TITLE
Backing into a fillpoint?

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3414]
Is there any proper way to back into a fill point?   I am having no luck in attempting to record any successful course that works 100% of the time.

I have a belt set up on the Marwell silage pit, and the only way I can get it to successfully work all the time is to go around the back, through the cow and sheep fields and forward to the start point.

![fsScreen_2019_03_15_09_50_43](https://user-images.githubusercontent.com/6591048/54436123-500f4800-4708-11e9-9b4d-ae5c4529d5ad.png)

I would prefer to back up into the start point..  This works only some of the time, and eventually will back up so the back of the trailer reaches the start point and pull back out without loading (the start point i've pushed over to the side, to try and avoid this situation).  I was hoping it would back all the way to the wall and then pull forward to the start point, but it does not.

![fsScreen_2019_03_15_09_52_45](https://user-images.githubusercontent.com/6591048/54436282-99f82e00-4708-11e9-9c80-01a4cf756626.png)

**Comment by sootysax** [comment]
Here, on the 3rd run, the info text came up and got to 'loading 304 of 31000' and then pulled out again.   Stopping and driving from nearest waypoint got it to fill 100% again.  

Perhaps i can plot the course better?  it's a tricky load area.

![fsScreen_2019_03_15_10_13_24](https://user-images.githubusercontent.com/6591048/54437474-1429b200-470b-11e9-9ab2-d6959ba49932.png)

**Comment by ThomasGaertner** [comment]
@pvaiko ?

**Comment by pvaiko** [comment]
@ThomasGaertner why me? :)

**Comment by ThomasGaertner** [comment]
@pvaiko : :-) its reversing to the last waypoint , I thought would be a challenge :-D

**Comment by pvaiko** [comment]
@ThomasGaertner I thought this is a fill trigger issue... 
So @sootysax does it work if you set it up the way that it starts/ends somewhere else?

**Comment by sootysax** [comment]
this is the only attempt i've done at trying to back into a start/load point..   just because the silage bunker is pretty tucked away on this farm.   The round about approach to this loading point also works, but ultimately I wouldnt want to drive through both animal paddocks to get to it.

**Comment by StreelRodent** [comment]
As long as the reverse course is recorded without a trailer I've not had a problem getting it to roughly end up in the same spot each time. Only the stuff I want it to reverse into (like the hayloft) currently doesn't with CP apparently, so I've not been able to make much use of it yet.

**Comment by Tensuko** [comment]
Can you try this again with 163 or higher, if still got issue ?
The reverse seems kinda fine with the last test.

**Comment by Tensuko** [comment]
No answer.
Closing unless this Issue is still valid.
Closed.
