### ISSUE TITLE
Cotton harvesters fail to turn at turning points.

### ISSUE THREAD

**Issue by SteelRodent** [Courseplay/courseplay#3416]
Basically in a nutshell:

- I let CP generate the course with 2 lanes (12 m) of headland, set to use "turn" for the headland.
- Set cotton harvester to start from first waypoint.
- Running on "field work" mode.
- When the harvester reaches the end of the first lane of the headland, it drives outside the field and stops with the rear end outside the border, then it reverses back onto the field to the point where it's supposed to turn. Then, instead of turning, it just runs straight ahead at full speed in the direction it's facing.
- Same issue whether the course is generated for 1 or 2 harvesters, and whether I generate it with the old method of doubling the workwidth and setting the offset for each machine.
- Symmetric or assymetric lane change makes no difference.
- Disabling pathfinding makes no difference.

I first ran into this on the Lapacho map (which is my only save where I bother with cotton), so I tested it on my Felsbruun test save with as many mods disabled as possible. It's the same behaviour on either map.

This is with CP 6.01.138 and FS19 1.0.3 beta.

Worth noting that the cotton harvesters worked just fine about a week ago (with CP 124 or something like that), but I haven't touched that save since. I haven't had any issues with regular combines on 138.

Log.txt: [https://gist.github.com/StreelRodent/d76946a6509a336fbbc351904dde7baf](https://gist.github.com/StreelRodent/d76946a6509a336fbbc351904dde7baf)

(Still have no idea how to use the debug mode, sorry)

EDIT: 3 tries to get the log link working ;)

**Comment by pvaiko** [comment]
This is because we don't set the front/back markers correctly for tools which do not have an active input attacher joint. The whole logic in an around setMarkers is completely flawed and there are frustrating side effects and mutual dependencies all over the place in the legacy code.

Not sure when I'm going to have the motivation to clean this mess up.

**Comment by Tensuko** [comment]
I used the Cotton Harvester with one of the latest Versions and it worked fine, just dropped the Bales on teh Field, wich is hard to pick up without kill the Fruit (if it is supposed to grow again, don't know...).
So this one should be solved, if still faceing Issue, reopen or make a new Issue.
Closed.
