### ISSUE TITLE
Plow does not turn on field

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/courseplay#3417]
Log: https://gist.github.com/StefanBraun2001/5626b9092549160e004d2b334de413a4

When i hire a helper to plow the field (it happens with all plows, only the POH 5 works) and the setting "truning on field" is on the helper doen´t turn on field, he makes a huge turning maneuver outside  instead. Why? It is possible to drive backwards with the plows, and in most cases there is not sufficent space for the turning maneuver...

**Comment by Tensuko** [comment]
Try again with 163 or higher. If still got problems, make a new Issue.
Closed #3417
