### ISSUE TITLE
BGA silage trigger not recognized

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#3419]
Trying to unload a tipper at the BGA silage sell point. But CP seems not to recognize it, so it just drives through.
![fsScreen_2019_03_16_17_25_10](https://user-images.githubusercontent.com/21023840/54478282-b2537000-4810-11e9-9125-bf5422bc6a25.png)
Tried to hit the sellpoint in different angles and directions.
Is the sort of the tiptrigger another in the BGA than at other sellpoints?
I'm on CP 6.01.00139

**Comment by GeorgeEarslight** [comment]
#3070
