### ISSUE TITLE
How to organize saved courses?

### ISSUE THREAD

**Issue by Hubcap-1** [Courseplay/courseplay#3420]
My saved course list in the HUD seems disorganized. I think generally it is trying to organize them in ascending order ( field 1 plots then field 2 plots and so on), but i get some fields where they are scattered throughout the list . Example, currently my list comes up with a field 8 all by itself then a group of field 1's then 2's....then a couple more 8's and so on. Is there a way to put all field courses, in order,  and TOGETHER ???  ( Possibly an edit of the XML ? )

**Comment by sootysax** [comment]
Folders and subfolders..  I have all my fieldwork in field folders (F1, F2, F3) and all of them are in a FIELDS folder.   I also have folders for SELLPOINTS, YARD, ROADS etc.  contents of each folder are presented alphabetically

**Comment by Hubcap-1** [comment]
Then I don't understand why that's not happening for me because I called
them field one field to field 3 but they are all separate know most of them
present in order like 1 2 3 and together meaning the field one line field 1
cedarfield one Harvester are all together but I get a few of them they're
out of order like for some reason my list starts with a field 8 plow and I
have filled eight other stuff down below

**Comment by Tensuko** [comment]
Hmm, one thing you need to know is the difference:
F10
F1
F20
F2
or you go like:
F01
F02
F10
F20

I think there is also an Order change when use space inbetween.
But just like sootysax said, make Folders to put your Course in.
[F01]
 -F01_Seed6m
 -F01_Plow3m
[F02]
 -F02_Harvest
 -F02_I_think_you_get_the_Idea

;)
