### ISSUE TITLE
Impossible maneuver 

### ISSUE THREAD

**Issue by GeorgeEarslight** [Courseplay/courseplay#3421]
v138

![CP_3421_138](https://user-images.githubusercontent.com/30686125/54482386-75589f00-484b-11e9-958f-17f2f11585b5.png)

Course F18ToDO, maneuver from 2nd to the 3rd row.
https://we.tl/t-KYktLW2To3

**Comment by Tensuko** [comment]
A File of 2MB you can easy drag and drop into the message window and upload here on github.... No need to use weird upload pages.

**Comment by GeorgeEarslight** [comment]
@Tensuko wetransfer a weird upload page? You need to rethink that or ask your work colleagues about it.

**Comment by Tensuko** [comment]
why my work colleagues ? you don't know anything about me or my work...
And I never heard about that wetransfer so....

**Comment by Messy71** [comment]
@GeorgeEarslight if you’ve created your course in HUD ( on that same settings page from the picture) try creating it with the advanced course generator ( in the same settings page you have the gear icon on the top right, near the generate and save course buttons) see if that works.
The HUD course generation it’s outdated and at the moment the devs are advising the use of the advanced course generator.

**Comment by GeorgeEarslight** [comment]
> @GeorgeEarslight if you’ve created your course in HUD  ...
> The HUD course generation it’s outdated and at the moment the devs are advising the use of the advanced course generator.

@Messy71 It's on the advanced generator. If you look closely, I've also used the skip rows option, which is only available on the advanced mode.

**Comment by pvaiko** [comment]
@GeorgeEarslight that upload site is indeed disturbing, not going to download anything from there. Please upload to GitHub.

**Comment by GeorgeEarslight** [comment]
@pvaiko Is this a joke? 
https://www.alexa.com/siteinfo/wetransfer.com
https://reviews.financesonline.com/p/wetransfer/
https://www.trustpilot.com/review/www.wetransfer.com
I'm genuinely curious about the reason you find it disturbing unless you're just toying. 

Anyhow, here's the zip. 
[CP_3421_138.zip](https://github.com/Courseplay/courseplay/files/2978696/CP_3421_138.zip)

**Comment by pvaiko** [comment]
No joke, I clicked on it twice both times I got a full page stupid animated ad in my face. 

I'm genuinely curious about the reason to upload a file anywhere else other than the platform (GitHub) we are already using to track issues.

**Comment by GeorgeEarslight** [comment]
I never got any ads from there, perhaps due to my adblocker.
As for my reason, is because in my use case it's just one extra click and I've been using it for work and non-work related big file transfers for years, aka it's working for me.

**Comment by vertigoogle** [comment]
Maybe you employer wants to hear about which external databases you feed with work-related data ;)
