### ISSUE TITLE
Log Fehler  Xerion 4000

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#3425]
Courseplay: Xerion 4000: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
Courseplay: Xerion 5000 Chip: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
Courseplay: Xerion 4000: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
Courseplay: Xerion 4500: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
Courseplay: Xerion 5000: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!
[log.txt](https://github.com/Courseplay/courseplay/files/2975435/log.txt)
Courseplay: Xerion 5000 Chip: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!

**Comment by ThomasGaertner** [comment]
will be solved in #3239
