### ISSUE TITLE
Kein Sprit Verbrauch bei Laden am ersten Punkt

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#3427]
Hallo Courseplay Team. Die abfahrer brauchen keinen Sprit mehr aber macht man CP aus verbraucht das Fahrzeug wieder sprit.
Mod = https://forbidden-mods.de/filebase/file/5359-scania-r730-hooklift/

MFG Mannie313

**Comment by Tensuko** [comment]
Momentant wird nicht direkt auf Mods eingegangen, da es wichtiger ist, dass wieder alle Funktionen von CP vorhanden sind.
Aber da normalerweise der Spritverbrauch funktioniert, würde ich mal auf einen Fehler in der Mod tippen.
Nur mal so: Die Option, dass Helfer den Sprit von alleine kaufen ist aber aus ? :D

**Comment by Tensuko** [comment]
Keine Rückmeldung vom User, ansonsten mit mehr Info und logfile neu aufmachen. Closed.
