### ISSUE TITLE
Startup Issue

### ISSUE THREAD

**Issue by FlameTech-Entertainment** [Courseplay/courseplay#3428]
Dear Courseplay-Developer-Team,

When I try to start the game, this error message appears in the log.

Nevertheless many thanks for the efforts for this Mod!!

`2019-03-17 21:24 Error: Running LUA method 'loadMapFinished'.`
`2019-03-17 21:24 ../FarmingSimulator2019/mods/courseplay/hud.lua:96: table index is nil`

**Comment by pvaiko** [comment]
See #3404, if a clean install does not solve your problem reopen and post the full log here.
