### ISSUE TITLE
Request: PDA map in overview

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3430]
I really miss the PDA map display in the course overview as it was in previous versions of CP.   It really makes a big difference when building combined courses..   is there any chance this is going to be implemented?

**Comment by Flacwby** [comment]
I've used Courseplay since FS15 and I never knew there was a PDA. How do you trigger it?

**Comment by Tensuko** [comment]
It is the little Eye Symbol in the top left corner, when you loaded a Course.
