### ISSUE TITLE
LUA Callstack v. 141 in mode2

### ISSUE THREAD

**Issue by hoefti10** [Courseplay/courseplay#3431]
Hi, had LUA Callstack since version .141 in the Moment when i Start Mode 2
attached me Log :-)
[log.txt](https://github.com/Courseplay/courseplay/files/2979381/log.txt)

**Comment by ThomasGaertner** [comment]
would be interesting to know which trailer you used for that...

**Comment by hoefti10** [comment]
I'll guesss the problem was the tractor. i try a different one and it was completly in function without an Callstack. Sorry.

**Comment by ThomasGaertner** [comment]
so can we close ?

**Comment by Tensuko** [comment]
FS19_Fendt800VarioTMS ? If so, same as LS_Modcompany Forum. So can be closed, even don't know for sure wich of the Erros in the log caused it, but it doesn't come from CP.
