### ISSUE TITLE
combine convoy suggestion: ajustable distance.

### ISSUE THREAD

**Issue by mehdinasef** [Courseplay/courseplay#3433]
combine convoy is an awesome feature of courseplay especially when it has been added to other field work modes. however, as far as I know, the distance between the vehicles can't be adjusted. I think that it will be better if the distance becomes adjustable.

**Comment by cyberndj** [comment]
Hi,
I was looking at this issue and was going to attempt a crack at it. I found this snip from hud.lua, but I can't find what file this function/method/(proper lua name) sits in. I have spent an hour opening files and searching for 'content.' Could I get a reference to what file to look at?
`vehicle.cp.hud.content.pages[1][5][2].text`
Thanks!

**Comment by mehdinasef** [comment]
> What are some logical choices for a minimal and maximum set follow distance?

I think that the minimal may be 10 meters and the maximum for me can be a bit above 100m, for example, 120 or 130 meters.

**Comment by GeorgeEarslight** [comment]
If possible, please also add minimum distance, so that the leading vehicle doesn't stray too far.
Moving too far can cause collisions on various occasions.

**Comment by ThomasGaertner** [comment]
you mean maximumdistance I assume. :-) I will think about it. How should it work? If the last one is blocked, all others have to stop?

**Comment by GeorgeEarslight** [comment]
@ThomasGaertner Yes, you are correct about max distance!
I haven't looked at the code to see how it works now, but here is how I would try to do it (pseudo-code):

```
--[[ 0 index is the first vehicle, max is the last ]]--
if n > 0
  if (convoyVehicle[n].dist < convoyVehicle[n-1].minDist) then allowedToMove = false
if n < max
  if (convoyVehicle[n].dist > convoyVehicle[n+1].maxDist) then allowedToMove = false
```
I think if you run a for loop on the convoyVehicle array, they should stop on their own without looking at further vehicles, just their front and rear.
Obviously the user should put some hysteresis between min-max, perhaps around 20 meters or so.

**Comment by Tensuko** [comment]
Try V168 and give feedback pls :)

**Comment by mehdinasef** [comment]
Ok, I'll do as soon as I have enough time. Probably tomorrow.

**Comment by mehdinasef** [comment]
I have taken a quick look at it today and it is working pretty well. I also liked the new hud it is awesome. Great work!!

**Comment by Tensuko** [comment]
Closed.

**Comment by GeorgeEarslight** [comment]
@ThomasGaertner Thomas, I'm working on min-max distance. Also needed some HUD moving around of the waitRefill, had to move in to (3,8) from (3,5). Thanks for leaving some code fragments ;)

**Comment by ThomasGaertner** [comment]
yea i prepared it but i'm not quite sure I will implement it. there is too much space for missuse...

**Comment by GeorgeEarslight** [comment]
The current implementation works well for its purpose anyway.
I'm trying a bit different approach. I'll send a fork when I'm ready (probably not very soon).
