### ISSUE TITLE
Course does not start

### ISSUE THREAD

**Issue by WolfmoonCT** [Courseplay/courseplay#3436]
After update to 1.3  I created a new course, 2 headlands for fertilizing.  when I told it to start at first waypoint  all I get is a big yellow arrow pointing to the waypoint.  Once started, clicking the area to stop the driver does nothing.   The only errors I see is this one

2019-03-19 06:34 C:/Users/wolfm/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/triggers.lua:527: table index is nil

**Comment by WolfmoonCT** [comment]
Just tried again, and what I saw was that once you try to start a course, you lose control of the tractor.  You can't move forward, backward, or steer it.  It's like the AI has it, but it's not driving anything.

**Comment by Messy71** [comment]
@WolfmoonCT did you tried with a new savegame and a fresh install of Courseplay?

**Comment by sootysax** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by sootysax** [comment]
@WolfmoonCT What version of courseplay are you using?

**Comment by WolfmoonCT** [comment]
Sorry I didn't include the log file.  Here is a link to it.  https://pastebin.com/4uxg4Eih
I  have not tried a new savegame or fresh install of courseplay.

**Comment by sootysax** [comment]
what stolen mod website did you download that version of CP from?   There have been 122 updates since the version you are using.

**Comment by sootysax** [comment]
This issue was solved a month and a half ago. #3165

You are using a version of CP that is 122 updates behind the current dev version. 

You should read the pinned post about how to update CP, and also scan through all current and closed issues to see if your issue was already posted before posting.

**Comment by WolfmoonCT** [comment]
I'm sorry.  I did the original download off ModHub and I was not using the dev versions.  I don't normally use GitHub and I was not updating to smaller versions.

**Comment by sootysax** [comment]
@WolfmoonCT Just so you know, Modhub.us is at the bottom of the list of shady and untrusted websits.  It was an unauthorized upload of an old dev version, as are almost every other mod that is posted there.   They post mods that are hack conversions, broken mods, and mods that are outright stolen from open and closed beta testing.   

I would highly advise you to seek out the modder of any mod on there you are looking at, and find the official home for that modder, whether it's on Github, Facebook or some of the reputable website.

Here is a link to a google doc that is updated and has a list of reputable and untrusted mod sites for FS19.

https://docs.google.com/spreadsheets/d/1HKJHIwk_YiIEr0feW4ImBolVczhReaTmWtnhn8c7If8/edit#gid=813430799

**Comment by WolfmoonCT** [comment]
Thank you so much for the link.  I meant that I got my copy of CP off the http://www.farmingsimulator19mods.com page. That and the official mods page are about the only two I really use. I will get more familiar with github and grab it from here from now on.
