### ISSUE TITLE
Combine not stopping at field end.

### ISSUE THREAD

**Issue by abcderic73** [Courseplay/courseplay#3437]
When harvesting anything using CP, the combines never stop at the field end to keep the straw swath straight.

They also lower the header before going back into the field which causes some of the fruit to be missed everytime it starts a new row.

Not a very big deal, it's manageable, just kinda annoying because this didn't happen in 17.

**Comment by ThomasGaertner** [comment]
@pvaiko I think its a double but I cant find the first one ...

**Comment by pvaiko** [comment]
> They also lower the header before going back into the field which causes some of the fruit to be missed everytime it starts a new row

Don't quite get how lowering it later would prevent missing fruit.

**Comment by cyberndj** [comment]
I noticed in my game that is usually the first way point where fruit gets missed in a course. I've also noticed that its only harvesters (and not tools) that won't stop at the last way point for me.

**Comment by BigUser8888** [comment]
I’ve also noticed it when the harvester (with corn attachment) seamlessly starts the next row as part of completing its turn... but it’s almost but not fully completed the turn yet - so  isn’t fully lined up straight when starting the row... so misses an initial corner of the ‘crop row’.

**Comment by pvaiko** [comment]
@BigUser8888 the same question to you: how would lowering it later prevent missing fruit?

**Comment by Tensuko** [comment]
I wonder more abour the Course and what settings you used to create it ? ...
If use the new mid part pattern (spiral and circle), they don't rly do a turn manuver and as I saw last time with Channel 14 they even do a good Pathfinding and wonder how they miss anyhthing.

**Comment by Tensuko** [comment]
Fixed with V160. Closed
