### ISSUE TITLE
Courseplay won't unload Slurry at BGA

### ISSUE THREAD

**Issue by cwattyeso** [Courseplay/courseplay#3438]
I've been trying to record a course with Courseplay to take Slurry from my Farm's Silo and automatically take it and unload it at the BGA. When I run the course, it loads the Slurry into the tanker perfectly fine, drive to the BGA just fine, gets to the trigger point and just drives straight over it and back to the farm without unloading/selling the slurry. Doesn't matter what Tractor/Truck/Tanker combination I use it never unloads when it reaches the BGA.

Recording a course in the opposite direction, taking Digestate from the BGA and delivering it to the Farm Silo works perfectly fine and the Courseplay can be left unsupervised to run the course repeatedly until the BGA is empty and it can't fill the tanker anymore.

However try as I might I can't get it to deliver the Slurry from the farm to the BGA.
[log.txt](https://github.com/Courseplay/courseplay/files/2984539/log.txt)

**Comment by ThomasGaertner** [comment]
Please test again with debug Channel 1 aktive

**Comment by cwattyeso** [comment]
Have re-recorded the course and tested it with Debug Channel 1 active and the same thing happens. Driver just drives over the unload point and continue back to the course start/fill point.
![20190320151930_1](https://user-images.githubusercontent.com/13921716/54698127-b0e2ba00-4b26-11e9-80fb-0e4bcc0a0fc3.jpg)

Another weird thing I noticed this time when recording the course, the course track seems to get placed to the left of the vehicle and not laid directly in line with the centre of the truck and trailer:

![2019-03-20 (7)](https://user-images.githubusercontent.com/13921716/54698200-d1ab0f80-4b26-11e9-9d06-2a5d6635e03b.png)

Here is the latest Log file, with the Debug Channel 1 info included:
[log.txt](https://github.com/Courseplay/courseplay/files/2988976/log.txt)

**Comment by ThomasGaertner** [comment]
we are currently at verison .143 so please try again with a version higher than .140 and report

**Comment by cwattyeso** [comment]
Updated to Version .143 and can now happily report tankers are offloading at the BGA now correctly, without any extra steps or assistance needed by myself. Thank you for your assistance in this matter.
