### ISSUE TITLE
Request : Leave Lights On

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3439]
Can you make a change so that when you stop a course, headlights will stay on??  Its hard to work at night when if you want to take over driving when CP is driving, its totally pitch black when you 'stop driver'

**Comment by pvaiko** [comment]
Certainly it would be possible, only I already see the new requests coming from others to turn lights off when stopping. So we'll leave it as it is.

**Comment by SpacemanJay** [comment]
I was just about to ask this myself. Seasons makes the lights come on before sundown which is great, and I find myself working into the evenings more. It really does get pitch black at night. Just a minor annoyance to have to turn them right back on to refill/unload, but it's quite the immersion-breaker. 

What about if the course has ended and the engine has shut off then kill the lights as normal, but if the player hits "stop driver" then they stay on if they were already on?

**Comment by pvaiko** [comment]
#3533

**Comment by SpacemanJay** [comment]
"Manual Stop CP, keep on light and tools
CP finish job by itself, turn off light, stop and fold the tools"

So this is a planned feature? Great, thanks :)
