### ISSUE TITLE
Runs too fast through silo

### ISSUE THREAD

**Issue by xerion8300** [Courseplay/courseplay#3440]
When unloading, the tractor drives too fast through the silo and tilts outside.
Can one adjust the speed somewhere?

**Comment by ThomasGaertner** [comment]
screenshot and log with debug channel2 active please

**Comment by Tensuko** [comment]
That should have been fixed since few versions. Logfile or better ask, wich CP Version do you use ?

**Comment by ThomasGaertner** [comment]
@Tensuko its in the log :-)

**Comment by ralfmuehle** [comment]
tractor drives through  the silo with "Turn speed" so you must change this value

**Comment by Tensuko** [comment]
The speed gets calculated by filllevel and I think bunker lenght, so you can't set this by changeing the turn-speed.

At least it is supposed to work like that.

Still need the logfile with debug channel 2 as Thomas said.

**Comment by xerion8300** [comment]
Im Anhang die Log und ein Bild
[log.txt](https://github.com/Courseplay/courseplay/files/2991435/log.txt)

https://abload.de/img/fsscreen_2019_03_21_0dvjcs.png

<a href="http://abload.de/image.php?img=fsscreen_2019_03_21_0dvjcs.png"><img src="https://abload.de/thumb/fsscreen_2019_03_21_0dvjcs.png" /></a>

**Comment by xerion8300** [comment]
Im Anhang die Log und ein Bild 
[log.txt](https://github.com/Courseplay/courseplay/files/2991435/log.txt)

https://abload.de/img/fsscreen_2019_03_21_0dvjcs.png

<a href="http://abload.de/image.php?img=fsscreen_2019_03_21_0dvjcs.png"><img src="https://abload.de/thumb/fsscreen_2019_03_21_0dvjcs.png" /></a>

**Comment by Tensuko** [comment]
To many maps in Modfolder:
FS19_New_Bartelshagen
FS19_NF_Marsch
FS19_NF_Marsch_oG
Niederbayern

This Mods like to create unknown Erros and/or Modconflicts:
FS19_realDirtColor

**Comment by xerion8300** [comment]
Will remove the mods and then look again.
Thank you

**Comment by ThomasGaertner** [comment]
strange, please test with debug 1 and 2 please

**Comment by Mychomizer** [comment]
I have the same issue myself, tried with several different trailers. Here is a log.txt with debug 1+2 from me.
[log.txt](https://github.com/Courseplay/courseplay/files/2994323/log.txt)

See from line 855

**Comment by Tensuko** [comment]
You got some LUA Erros too.
Not sure if that is still an issue, but I would take out realDirtColor.
And I don#t know about some other script Mods like WorkRPM and that other dirt mod, what they do.
Is it possible you try it again with no Mod except the Map and CP ?

I got a lot Mods too, but for me it was fixed.
When I am home later, I see if I can put up some test with the actual version.

**Comment by ThomasGaertner** [comment]
are you reversing into the silo ? what I'm misssing in your logs is the calculation of the speed

**Comment by xerion8300** [comment]
Wher find this  this Protokoll   the calculation of the speed.
I just drove over one silo

[log.txt](https://github.com/Courseplay/courseplay/files/2995600/log.txt)

**Comment by Mychomizer** [comment]
I ran some tests and the problem is solved (atleast for me) by removing the mod "Real Dirt Color"

That's a shame since that mod really adds feel to the game, especially on Estancia Lapacho. Any fix/workaround or is it on Real Dirt Color devs tabel?

**Comment by Tensuko** [comment]
Again realdirt... Well that mod is screwed up somehow... I know it is cool but as for me I prefer CP

**Comment by Mychomizer** [comment]
UPDATE again.

I started playing again harvesting corn into chaff (without realdirt and same modlist as when it first worked again) and i'm having the same issue now with the tractor driving to fast in the silo. So mabye it's not related to real dirt after all? Log with debug 1+2 is included


[log.txt](https://github.com/Courseplay/courseplay/files/2997402/log.txt)

**Comment by Tensuko** [comment]
RealDirt is still listed in your logfile ?!

**Comment by Tensuko** [comment]
[log_Bunker.txt](https://github.com/Courseplay/courseplay/files/2997508/log_Bunker.txt)
There you go, with Speed-Calculation.
Some Mod is definitly blocking this.
RPM ? RealDirt ? ....
Only chance to find out is you take one Mod out of your Mod Folder one by one.
I would start with ScriptMods, like I mentioned.

**Comment by Mychomizer** [comment]
RealDirt, RPM etc mods are still in the mod folder but not loaded. Mabye its not enough, I will completely move them from the mod folder and test again. I'll post an update later

**Comment by xerion8300** [comment]
Have now used a standard tractor un real dirt was also in the game and he drove slowly over the silo.
Then a mod tractor and it went.
After the 4 times drove all again with about 20 Kmh on the Silo.

**Comment by Tensuko** [comment]
So you might think that it is a combination of mod tractor + real dirt ?

**Comment by xerion8300** [comment]
Could be it will continue testing and give notice

**Comment by Tensuko** [comment]
With and without RealDirt and the Axion 900 Mod, I get the right calculation from CP:
Pls test a bit more Mods, I will also see if I can make some test on my Provence Savegame.

2019-03-23 15:07 :40 [dbg1 lp25061]     trailerFillType=28 GRASS_WINDROW
2019-03-23 15:07 :40 [dbg1 lp25061]     trigger (111819) accepts trailerFillType
2019-03-23 15:07 :40 [dbg1 lp25061] axion 920 (#1): self.cp.currentTipTrigger=111819 , cpActualLength=55.30986192743
2019-03-23 15:07 :45 [dbg2 lp25394] axion 920 (#1): REPEX 34S in mode 6: entering BGASilo:
2019-03-23 15:07 :45 [dbg2 lp25394] axion 920 (#1): emptySpeed: 2270l/sek; fillLevel: 33833.3l
2019-03-23 15:07 :45 [dbg2 lp25394] axion 920 (#1): Silo length: 39m/Total unload time: 16.904552707572s *3.6 = unload speed: 8.31kmh
2019-03-23 15:07 :45 [dbg2 lp25394] axion 920 (#1): start tipping

**Comment by Tensuko** [comment]
Provence, Vanilla Fahrzeuge, BGA Silo (was mir nichtmal gehört) und RealDirt:

2019-03-23 15:49 :55 [dbg1 lp52185]     trailerFillType=28 GRASS_WINDROW
2019-03-23 15:49 :55 [dbg1 lp52185]     trigger (82735) accepts trailerFillType
2019-03-23 15:49 :55 [dbg1 lp52185] 8340 (#2): self.cp.currentTipTrigger=82735 , cpActualLength=97.125072763364
2019-03-23 15:50 :02 [dbg2 lp52625] 8340 (#2): ZELON CFS 2501 DO in mode 6: entering BGASilo:
2019-03-23 15:50 :02 [dbg2 lp52625] 8340 (#2): emptySpeed: 1530l/sek; fillLevel: 22885.9l
2019-03-23 15:50 :02 [dbg2 lp52625] 8340 (#2): Silo length: 76.099975585938m/Total unload time: 16.958082618864s *3.6 = unload speed: 16.16kmh
2019-03-23 15:50 :02 [dbg2 lp52625] 8340 (#2): start tipping
2019-03-23 15:50 :30 [dbg2 lp54273] 8340 (#2): reset self.unloadSpeed

Muss also noch etwas anderes sein, was mich wundert ist, dass es bei dir funktionierte nachdem du RealDirt rausgenommen hast.

(Kenne das aber auch, RealDirt raus, Fehler war weg, aber das war ein anderer Fehler).

**Comment by ThomasGaertner** [comment]
@xerion8300 : gibts neue infos ?

**Comment by xerion8300** [comment]
Ich habe es jetzt mit Platzierbaren Silos ausprobiert da hat es funktioniert. Habe ca. 5-6 Ladungen Mais  hinein gefahren.
Andere Map
Bin beim einfahren des Kurses mit ca 8 Km/h über das Silo gefahren und danach hat er 4-5 mal normal ab gekippt und danach ist er wieder schneller darüber gefahren
Standard Map
Als ich die Standard Map gespielt habe ist der selbe Traktor mit ca. 20 Km/h durchgefahren beim ab kippen.
Danach habe ich gedroschen und habe den Hänger an der Mühle ab kippen lassen, da hat es super funktioniert. Ich kann es nicht sagen an was es liegt.

**Comment by ThomasGaertner** [comment]
ich mach hier zu , wenn es nochmal auftritt, aber nicht in mode2 dann neue issue machen Danke
