### ISSUE TITLE
FSX 63.72 bale loader refuses to unload on field

### ISSUE THREAD

**Issue by Esgargoth** [Courseplay/courseplay#3441]
Sorry if this has been answered although i searched and found none.
The loader runs the course fine and collects every bale but when it comes to unload i simply get "work tool needs to be unloaded" and it will just sit there.  
Then i must unload manually, (stop cp and hit y a few times) 
Also, if i resume the course while the bed is still up it will not pull it down.
I did have an option to unload on field before but even that didn't work.
Again sorry if this is still experimental and not fixed yet.
Log attached with debug 6 and 11, 

[log.txt](https://github.com/Courseplay/courseplay/files/2987306/log.txt)

**Comment by Tensuko** [comment]
You need 2 Course to unload bales. The normal Field Course to collect and an unload course where to put the bales. Just like the refillcourse, but you got to set the manual unload point at the place to unload or drive over a selltrigger, if you want to sell them directly.
Best is to store them somewhere, but I woul drive in reverse to the place to store them.
Then CP can create rows of unloaded bales with a set distance. (I think the Basevalue ist set automatically for square and round bales).

**Comment by Esgargoth** [comment]
> You need 2 Course to unload bales. The normal Field Course to collect and an unload course where to put the bales. Just like the refillcourse, but you got to set the manual unload point at the place to unload or drive over a selltrigger, if you want to sell them directly.
> Best is to store them somewhere, but I woul drive in reverse to the place to store them.
> Then CP can create rows of unloaded bales with a set distance. (I think the Basevalue ist set automatically for square and round bales).

Thank you for this, works perfectly and even better than how i was dealing with it before.
Thanks again, have a great day.
