### ISSUE TITLE
Tractor don't go to the combine on mode 2

### ISSUE THREAD

**Issue by jeremy3112** [Courseplay/courseplay#3442]
The harvester does not call automatically the tractor when it has to empty.
The tractor wait and I'm forced to click (on harvest courseplay) on call to make him come 
I don't know if the problem is with courseplay or my mods.

[log.txt](https://github.com/Courseplay/courseplay/files/2987543/log.txt)

**Comment by patch110** [comment]
I have noticed this issue too. Seems to be on fields I have made myself mostly (ie Ploughed 2 fields Into 1). although I have used the Detect Field Edge Path after doing so

**Comment by GeorgeEarslight** [comment]
#3311
