### ISSUE TITLE
Option to use or not use fertilizer function of seeder missing?

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3443]
There is no option to use the Stara Ceres Master 3570 seeder without the fertlizer function as there is with other seeders that fertilize.

Actually - it seems like that option to either use or not use the fertilizer function of a seeder has disappeared from CP all together?   Did it get removed?

**Comment by pvaiko** [comment]
But you have the convoy instead, don't you? :)

**Comment by RUGhost** [comment]
Please bring fertilizer function back.

**Comment by sootysax** [comment]
> But you have the convoy instead, don't you? :)

Are they mutually exclusive?

**Comment by ThomasGaertner** [comment]
@sootysax  nope, but they use the same place in the HUD

**Comment by cyberndj** [comment]
I was looking at it. I see that row 2 is open. There is also some rows open under the Drive Settings page. Which spot seems more logical to have the Fert function reside at?

**Comment by pvaiko** [comment]
I'd leave it on the same page. Not ruse row 2 is really open isn't that where we show 'Continue' when stopped at a waitpoint?

**Comment by ThomasGaertner** [comment]
Maybe we can use HUD page 7 for the convoy stuff

**Comment by cyberndj** [comment]
I'll try putting it there when I get home from work tonight.

**Comment by cyberndj** [comment]
Hi, I was looking into this more and have an update. I managed to bring back the fert option and keep Convoy active. I was attempting to follow @ThomasGaertner suggestion to move convoy to page 7, but I couldn't get past the loading screen (error messages at bottom).

I moved ridgemarkers to row 2. I know that stomps out "Continue." I was looking at moving it to column 2 next to "Drive Now" and change the row assignments of 2 and 3. (I ran out of time last night)
Some other thoughts I had for this are:
- Add a scroll bar so there could be more than 8 rows (and reorder this list)
- Move "opposite turn direction" to page 7 ...and reorder
- Move the current course to (ex F12 8M) to next the the drive settings ex "Stop driver (F12 8m)" and the distance/position to the Convoy Row, column 2 ex "Combine Convoy     Activated <--890m--> 3/3" Freeing up a row...and reorder
- Expand HUD to be larger giving more space
- Suggestions?

FInally, should I do a pull request with this temporary sloppy fix and open another issue for a better fix?

![fsScreen_2019_03_21_23_15_05](https://user-images.githubusercontent.com/16530317/54842650-ad1e7700-4c8f-11e9-9909-9e27acf613de.png)
![fsScreen_2019_03_21_23_14_29](https://user-images.githubusercontent.com/16530317/54842655-b14a9480-4c8f-11e9-9b40-49b894330e85.png)
![fsScreen_2019_03_21_23_14_29 - Copy](https://user-images.githubusercontent.com/16530317/54842657-b576b200-4c8f-11e9-9eb6-4119a725e98b.png)
`2019-03-21 21:50 C:/Users/Jake/Documents/My Games/FarmingSimulator2019/mods/combineUnload_management/CpManager.lua:1077: attempt to call method 'getFullPx' (a nil value)
2019-03-21 21:52 Info: Failed to request rc, HTTP code 0`

**Comment by ThomasGaertner** [comment]
Well since there is a question for making the distance adjustable, I would prefer the page 7 thing. I will check it next week . Thanks for the effort

**Comment by cyberndj** [comment]
Hi, I managed to get Convoy over to page 7. I see that the sower with fert option is back under page 1. I did notice that the fert option will force convoy to be activated/deactivated opposite to the fert function being active/deactive. I will create a seperate issue for this. 

To do so, I had to move The course copy icon on page 7 from Row 8 over to Row 7, column 3. I personally don't use this feature in CP, so could we get some validation this didn't break.

I also set it up so Convoy will show the Activate/Deactivate settings only if the engine is not Driving. If its driving, it will show the follow distance/ convoy member info. I'm going to create the pull request with how these snips show.
![3443 Convoy ActiveDeactive](https://user-images.githubusercontent.com/16530317/54869259-29c65980-4d53-11e9-86d9-6da87c162f37.png)
![3443 Convoy Driving](https://user-images.githubusercontent.com/16530317/54869261-2cc14a00-4d53-11e9-92de-5abfcced7064.png)
![3443 Copy Course](https://user-images.githubusercontent.com/16530317/54869264-2fbc3a80-4d53-11e9-96cf-42a096ee373d.png)

**Comment by ThomasGaertner** [comment]
Hmm please give me the time to check it. Will do it next week

**Comment by cyberndj** [comment]
> Hmm please give me the time to check it. Will do it next week

Thanks! I claim to be a 'beginner' at this coding thing, so I'll take all the review I can get.

**Comment by ThomasGaertner** [comment]
I'm on it but will close here...
