### ISSUE TITLE
Helfer setzt nich am ersten wegpunkt nach zuordnung fürs zweite feld nicht an

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#3445]
Hallo @pvaiko .
Der helfer beim düngen und grubbern setzt beim zweiten Feld nicht am Ersten wegpunkt an.

[log CP version 6.01.00143.txt](https://github.com/Courseplay/courseplay/files/2989754/log.CP.version.6.01.00143.txt)

MFG Mannie313

**Comment by pvaiko** [comment]
Zweiten Feld? Was ist hier die Erwartung eigentlich?

**Comment by Mannie313** [comment]
wen ich in an einem feld angesetzt habe ist er richtig gefahren. habe ich ihn zum nächsten feld mit neuen wegdaten geschickt fängt er nicht am ersten wegpunkt an sondern auf einem x belibiegen punkt auf dem feld.

**Comment by Tensuko** [comment]
Also:
- Feld 1 Arbeit erledigt
- Neuen Kurs für Feld 2 geladen (alten rausgeschmissen und nicht neuen hinzugefügt ?)
- CP Fahrer gestartet (mit welcher Einstellung?)
- CP Fahrer fängt irgendwo an ?

**Comment by Mannie313** [comment]
Feld 1 Fertig
Kurs gelöscht
Neuen kurs geladen
Feldarbeitsmodus
Fängt nicht am ersten wegpunkt am feld an sondern irgendwo

**Comment by Tensuko** [comment]
Trotz Einstellung 'Am ersten Wegpunkt starten' ?

Feldarbeit oder 'Düngen und Säen' ausgewählt, weil du oben schreibst 'beim düngen und grubbern' oder meinst du das als, sowohl als auch ?

Sry wegen der Fragen, aber man muss halt erstmal wissen, was los ist. Selber habe ich das auch noch nicht probiert.

Das Problem ist, beim 'nächsten passenden Wegpunkt' bin ich auch noch nicht durchgestiegen, wo er anfängt, daher die Frage.

Kannst ja mal ein Logfile mit Debugchannel 14 (glaube ich) hier mit reinposten.

**Comment by Mannie313** [comment]
siehe log oben mit debug 12 und 14.

MFG Mannie313

**Comment by pvaiko** [comment]
Wir wissen immer noch nicht was du beim starten eingestellt hast...

**Comment by Mannie313** [comment]
Danke hat sich erledigt.

MFG Mannie313
