### ISSUE TITLE
Beta Branch

### ISSUE THREAD

**Issue by pvaiko** [Courseplay/courseplay#3446]
When implementing the pull back for the combines (see https://github.com/Courseplay/courseplay/issues/3282#issuecomment-466402561) I had to do more refactoring than I'm comfortable with to push on master. I think it is quite ok but as usual, I did not have time to test everything. So for those who want to try, here's the beta branch:

https://github.com/Courseplay/courseplay/tree/beta

I also threw in #3379 to stop the engine automatically after 30 seconds because I fear there'll be some edge cases where CP won't start the engine when it needs to.

Please report any problems you find with the beta in this issue.

**Comment by RUGhost** [comment]
First, In case of first headland if combine harvester is full of grain it just stand there and unloader needs to drive through fruit to unload the harvester.  (Suggestion_1:  it should make a pocket before fill up for the unloader) 
second, sometimes combine harvester start automatically (if it stoped for saving fuel) but maximum time it won't start.  
(suggestions_2: if harvester is 90 or 95% full (which amount you like)  before entering next row then he call unloader.)

**Comment by pvaiko** [comment]
Thanks for testing. The reason I linked a specific comment from #3282 is that I implemented that specific idea only. I have **not** implemented all the others yet, including both of your suggestions.

> second, sometimes combine harvester start automatically (if it stopped for saving fuel) but maximum time it won't start

Not sure what are you trying to say here.

**Comment by RUGhost** [comment]
Sometimes combine harvester wait for a unloader and stop its engine. After I unload him, he doesn't start engine automatically. To make it working I need to stop the cp driver then  I need to activate "drive course".

**Comment by RUGhost** [comment]
And thanks for implementing pull back to the combine. Its working nice.

**Comment by pvaiko** [comment]
Merged to master, closing
