### ISSUE TITLE
Feature Request: No go zones and "controlled turns"

### ISSUE THREAD

**Issue by corrado33** [Courseplay/courseplay#3448]
First off, I LOVE courseplay, you guys are great. I know you're busy with basic functionality, but if you get a chance, I'd love to see these things. 

However, I'd like to put in a feature request. Basically a zone where no courseplay controlled vehicle will go. Say, in a line of trees, or around a power line tower, or around anything that will make the vehicle get stuck. The reasoning for this is that if I have a tractor running in combi mode on a field that has an island (say something in the middle of the field, like a power line tower), the combi tractor that's dragging the trailer will often head STRAIGHT toward the harvester, and if the harvester happens to be behind the obstacle.... well it'll get stuck on the obstacle. So if there were someway we could say "Hey CP vehicles, DON'T GO HERE."

The second feature request is what I'll call "controlled turns". Basically if you **manually** create fields and use the "begin turn" and "end turn" functions to avoid wasting seeds/fertilizer, you cannot tell the tractor how to do the turn (CP won't record points between begin turn and end turn), so if you have obstacles near your field (trees, sheds, etc.) the tractor will likely get stuck.... especially with huge sprayers. Yeah this can be avoided if you just do more headland loops, but sometimes that's not a great idea. (I tried separating the "turnstart" and "turnend" lines in the course xml, but it just resulted in the course not loading and freezing the game.)

**Comment by pvaiko** [comment]
For the 'no go zones': once mode 2 is ready it'll bypass obstacles in the field (like mode 4/6 is doing already).
