### ISSUE TITLE
Possible to narrow the field? 

### ISSUE THREAD

**Issue by SnoopBok** [Courseplay/courseplay#3452]
I'm wondering if it is possible to narrow down the field? So you cut off, for example, 3 meters from the field borders so you won't hit any trees or something else.

**Comment by Tensuko** [comment]
Headland ? The option Narrow Field ? CP offers a lot possibility to do such things.

**Comment by TomBos** [comment]
> Headland ? The option Narrow Field ? CP offers a lot possibility to do such things.

Where's the option "Narrow Field"? Can't find it. In which CP-menu context?

**Comment by Tensuko** [comment]
Advanced Coursegenerator. Click the Gear in the coursegen menu

**Comment by Messy71** [comment]
@SnoopBok you can also record a course around the new edges of the field( like a perimeter at the end you’ll end up with a rectangle/square or other shape that unites the starting point of the course with the end point) save it as « new edges-Field xx » and load it to your tractor go to advance course generator (on the gear symbol) and where you have the field option (for wich field hou want to create new course) you can select the option «  Currently loaded course »  and it will create the course with the new edges.

**Comment by Falkwa** [comment]
easiest way for me...   just use a roller to delete that part of the field permanent.   then save and reload the game... CP will autoscan the field.
