### ISSUE TITLE
Bypass islands, slight miscalculation

### ISSUE THREAD

**Issue by gentfarmer** [Courseplay/courseplay#3456]
FS19, Marwell Manor Farm, spraying field 15 with bypass islands set to circle.
There are 3 power poles in field 15, course generator identifies the 2 outer poles but not the middle one. On the Northerly path the sprayer passes the middle pole but on the next Southerly pass the sprayer arm hits the pole by about 2 metres.

Equipment used, hardi Navigator 6000 36m boom, tractor used either Fiat 1300DT or Valtra T194
Courseplay v6.01.00128.dev
[FS19_Marwell_Manor_Farm.ModMap.zip](https://github.com/Courseplay/courseplay/files/2999634/FS19_Marwell_Manor_Farm.ModMap.zip)

**Comment by pvaiko** [comment]
First of all, you should update to the newest version. Second, I can't reproduce this, the middle seems to be detected just fine with 36m work width:

![image](https://user-images.githubusercontent.com/2379521/54871801-2f8a6200-4d88-11e9-97d9-cff26164b872.png)

**Comment by gentfarmer** [comment]
Pleased to confirm that v 6.01.00147 corrects the problem. Thanks for looking Peter.

**Comment by pvaiko** [comment]
Haven't changed anything, can't reproduce the problem
