### ISSUE TITLE
"Fertilizer function of sowing machine" disables Convoy ability 

### ISSUE THREAD

**Issue by cyberndj** [Courseplay/courseplay#3457]
Hi, 
While I was working on issue #3443 I noticed that "Fertilizer function of sowing machine" has a direct impact on Convoy.

If Fertilizer function is Activated, You can not Set Convoy to Active. (It works as normal otherwise)
If Fertilizer function is Deactivated, Convoy works as expected.

**Comment by ThomasGaertner** [comment]
we decided to refactor the HUD handling, as you would have noticed, its a nightmare atm. we will take this issue and the convoy issue #3458  in account while setting it up.

**Comment by cyberndj** [comment]
Ya, I was getting confused a bunch. I gathered that text was in one section while all the buttons looked like it was near the bottom of the file.
I understand the balancing act of getting things working (i'm really looking forward to mode 2 working) vs adding improvement. 
I also like the Projects/Khanban Boards to help watch the progress of the development going!

**Comment by Tensuko** [comment]
Try with V168 and give feedback pls :)

**Comment by Tensuko** [comment]
Should be fixed.
If get any more trouble, open new Issue, thank you.
Closed.
