### ISSUE TITLE
Suggestion: Convoy Info in HUD Footer

### ISSUE THREAD

**Issue by cyberndj** [Courseplay/courseplay#3458]
Hi,

I would like to suggest that when the convoy feature is active, the distance and position is put in the footer section of the HUD.  If convoy is not active...it shouldn't show up.

Thoughts?

The picture is chopped up, but it is what I'm imagining.
![Convoy Info](https://user-images.githubusercontent.com/16530317/54870668-fb527980-4d66-11e9-8c48-71f61d1fe430.png)

**Comment by Tensuko** [comment]
Should be fixed.
If get any more trouble, open new Issue, thank you.
Closed.
