### ISSUE TITLE
Three field corner fine tuning suggestions

### ISSUE THREAD

**Issue by elektronemulo** [Courseplay/courseplay#3460]
Suggestion one: loop to turn. If the vehicle is making a sharp right turn where it stops work, lifts implements, turns, and starts working again, make a loop to the left to get better alignment. Should be optional in case the implement is working a field with walls or off-field obstructions.

![image](https://user-images.githubusercontent.com/20167300/54873317-36c26780-4daa-11e9-81c1-cc2b4f218613.png)

Suggestion two: after the implement lifts and the vehicle is backing, begin turning while backing instead of backing straight. This will give the implement better alignment with the next line. Again, might need to be optional based on field-edge barriers.

![image](https://user-images.githubusercontent.com/20167300/54873335-8acd4c00-4daa-11e9-9060-2e030f6367ab.png)

Suggestion three: On second and subsequent headlands, have the implement continue all the way up to where the cut line is next to the previous lane's stop/lift/back point so that implements cover all of the ground.

![image](https://user-images.githubusercontent.com/20167300/54873381-73db2980-4dab-11e9-883b-3fdbde3c7c49.png)

All of these suggestions are to solve this issue:

![image](https://user-images.githubusercontent.com/20167300/54873441-a20d3900-4dac-11e9-9b1c-f3a5633d6d8a.png)

Thanks for what y'all do; the FS series just isn't the same without CoursePlay!

**Comment by Tensuko** [comment]
But you got a lot of space arround your field.
Some Fields there is no space, thats why I use Headlands to get that kind of turn inside of the Field.

**Comment by elektronemulo** [comment]
> But you got a lot of space arround your field.
> Some Fields there is no space, thats why I use Headlands to get that kind of turn inside of the Field.

Suggestion 3 should fix the issues for fields with obstructions right next to the field. The idea with suggestion 3 is to keep going until any possible chance of remaining crop or un-tilled soil is gone. Then make the turn maneuver and go over the same ground again just to be sure, especially on the second and subsequent headlands.

**Comment by Tensuko** [comment]
If we can get different turn options added for harvesters, like we already got, straight backwards or turn backwards (something like this...), that might be an option and a solution for the referenced Issue (#3285 )

**Comment by elektronemulo** [comment]
> If we can get different turn options added for harvesters, like we already got, straight backwards or turn backwards (something like this...), that might be an option and a solution for the referenced Issue (#3285 )

Actually, I think #3760 is a much better solution than what I proposed.

**Comment by pvaiko** [comment]
So we can close this here. Will work on #3760 anyway.
