### ISSUE TITLE
How does CP recognize islands?

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3461]
Just wondering what does CP look for when generating fieldwork to recognize it as an island?   Do I have to paint the landscape with a certain texture?  Do I have to use the roller around a pole or power line tower in the middle of a grass field?  Is there a setting on the paintbrush that is the same as the meadow roller?

**Comment by pvaiko** [comment]
You should probably better ask a map modder. 

All I know is we use this function:
https://github.com/Courseplay/courseplay/blob/eb109da67dcf45292fc524809f79c1060eed9f09/fruit.lua#L51
which in turn uses the undocumented DensityMapModifier and DensityMapFilter Giants classes. At the end, all this is stored int the cultivator_density.gdm file which can be converted to an image where the black pixels are the non-field areas :)
