### ISSUE TITLE
Map Locks when loading save game with CP

### ISSUE THREAD

**Issue by AC2500S** [Courseplay/courseplay#3462]
[log.txt](https://github.com/Courseplay/courseplay/files/3000026/log.txt)

Previous to closing game sound was lost. Restarted game game won't load with CP. I started a new saved game and deactivated all other mods and map still won't load, game locks on loading screen to the map. 
I am using mod map FS19 Western Australia and have harvested field 5, started ploughing field 5, I have a road train running between two wait points and have started harvesting field 1.
I have about 5 course saved (only created ingame courses).

I manually deleted courses from CoursePlay_Courses folder. saved game loaded with all mods activated.
possibly a bug currupting saved courses?

**Comment by Tensuko** [comment]
Update CP first and try again.
And deactivating Mods doesn't help, you got to put them out of the modfolder.

Also, how many Courses did you have ?
Loading Courses take a long time and what I know from fs17, it can take rly long and looks like FS hanged up, but patient waiting helped and the game loaded.

**Comment by Tensuko** [comment]
No reply from User.
If happens again with 163 or higher, open a new issue.
Closed #3462
