### ISSUE TITLE
Narrow Field Settings got no Impact

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/courseplay#3463]
I got that Field 27 on Provence for some Coursegenerator Testing and discovered that the NarrowField Mid Stratagy settings got no Impact on the Coursgenerator and don't know if that is right or a bug.
![fsScreen_2019_03_24_09_08_22](https://user-images.githubusercontent.com/27344744/54876973-d74f7080-4e18-11e9-92eb-e7318e186202.png)
![fsScreen_2019_03_24_09_08_28](https://user-images.githubusercontent.com/27344744/54876974-d8809d80-4e18-11e9-8bf2-2496b0a9b998.png)
![fsScreen_2019_03_24_09_08_32](https://user-images.githubusercontent.com/27344744/54876976-da4a6100-4e18-11e9-9031-47cfbd754967.png)

**Comment by pvaiko** [comment]
Guess you meant that the field center settings have no impact in narrow field mode. What is the problem we are trying to solve here?

**Comment by Tensuko** [comment]
Not rly an Issue, but if that is supposed to work like that, then just remove that option for narrow field, not important but I just noticed that.
Thats all. You can close this if its not an issue.
