### ISSUE TITLE
Coursegenerator Improvements for Short Edges

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/courseplay#3464]
Version: 145

I got it nicely to work, but I think some turn points are misplaced.
Course:
[courseStorage0014.zip](https://github.com/Courseplay/courseplay/files/3000182/courseStorage0014.zip)

Settings:
![fsScreen_2019_03_24_09_15_48](https://user-images.githubusercontent.com/27344744/54876999-2b5a5500-4e19-11e9-8230-fdb79f67bb05.png)

Turn Points misplaced:
![fsScreen_2019_03_24_09_16_50](https://user-images.githubusercontent.com/27344744/54877003-3a410780-4e19-11e9-8eb2-33447493790f.png)

Some Adjustments to that WP would be great too, as he skipped the one in the Corner:
![fsScreen_2019_03_24_09_18_20](https://user-images.githubusercontent.com/27344744/54877006-42994280-4e19-11e9-82e6-5a11a22218ee.png)

Also for this settings, the CW/CCW was ignored, unless I go in the upper right Corner to create the Course, to change the Direction. In the Corner I used to, the direction is CW and perfect for pipe always outside of the fruit.

**Comment by pvaiko** [comment]
Congratulations, you are the first one testing this with the spiral center settings :) 
I think it wouldn't miss anything in the normal up/down mode.

**Comment by Tensuko** [comment]
I like to use new stuff, so why not try out ;)

Sure I can rly use only up/down and test the new combine reverse, but I wanted to have pipe ourside of fruit, so why not use the feature for that :)

**Comment by Th301** [comment]
I'd really like to use the courses with "short edges-Option". 
Unfortunately the turning points of the headland on the short edges are directly above the field-border. (You can see this in the first picture of the initial post)
This causes every vehicle, even combines with the implement in front of the vehicle, to leave the field completely before starting the turn. Are these points placed like that on purpose? Isn't it possible to leave a distance between the field border and the turning point, like it is on courses with all around headland, and than use "sharp" as propertie for the headland-turn? Than the combine would have to do 2 sharp turns on the field without leaving it.

**Comment by pvaiko** [comment]
This should work fine with 186, reopen if not.
