### ISSUE TITLE
Backwards problem

### ISSUE THREAD

**Issue by BoxerHUN** [Courseplay/courseplay#3468]
It would be better to wait for the combine to go away and then continue ahead.

(Jobb lenne megvárni, hogy a kombájn elmenjen és utána előre folytatni az utat.)

in video: 4:05
https://www.youtube.com/watch?v=bzmKVm4Y-p0

**Comment by pvaiko** [comment]
Mode 2 (combi mode) is under refactoring, see #3311. 

I thought you gonna post an issue about your other video with the combine going back and forth...
