### ISSUE TITLE
Auger Wagons Failing to work

### ISSUE THREAD

**Issue by Scrambler87** [Courseplay/courseplay#3472]
So I set up the course like before for the auger wagons yet they never unload, or respond at all. They will unload the combine pull up to the semi and sit there. 

Is this something that has not been implemented yet or am I not understanding how to set it up for the new courseplay?

**Comment by GeorgeEarslight** [comment]
@Scrambler87 This is mode3, I don't think it's implemented yet. Need to wait for mode2 first.

**Comment by wlfheart** [comment]
In combi mode set a Park waypoint by a truck then set wait timer long enough to empty wagon. this works well for me until overloader is implemented. The only bad thing is you need to use a regular trailer and not a double belly dump to keep it simple otherwise you have to set 2 park points

**Comment by Tensuko** [comment]
workarround solution, so we close this 1st and wait for Mode 3 to be available.
