### ISSUE TITLE
Fülltyp

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#3473]
Was muss ich da machen
Ich wollte das Silo leer fahren und habe Füllart Weizen eingestellt und vor dem Silo sagt der Abfahrer Fülltyp nicht vorhanden obwohl Weizen im Silo ist
Als Courseplay ist Beladung am Startpunkt eingestellt, was auch immer funktioniert hat, nun funktioniert ist nicht mehr und ich habe Patch 1.3 installiert

**Comment by andreasthu** [comment]
have the same issue
cp v6.01.00150
game v1.3
lg
andreas

**Comment by ThomasGaertner** [comment]
mehr details ? savegame? hier funzt es....

**Comment by ThomasGaertner** [comment]
test with v.153 or higher ...

**Comment by Chris2996** [comment]
Fixed with v.153

**Comment by Tensuko** [comment]
Closed.
