### ISSUE TITLE
Merkwürdiges Fahrverhalten bei 2 Fahrzeuge auf selben Kurs 

### ISSUE THREAD

**Issue by Charlyphyro** [Courseplay/courseplay#3474]
V: 6.01.00147
Hallo zusammen,
Bei zwei Mähdrescher im Verband und auf demselben Kurs, fährt der Linke Drescher beim Abladen immer rückwärts mittig von der Bahn Links und Rechts. Nach dem entladen kollidiert der Mähdrescher mit dem Kipper, wenn er auf seinen Kurs wieder geht. 
![fsScreen_2019_03_24_22_25_39](https://user-images.githubusercontent.com/21147032/54886265-85453400-4e86-11e9-8086-1b9784fd9d14.png)
Der Kipper ist dann dem auf der Rechten Spur fahrenden Mähdrescher im weg (Parkposition nach abladen, Mähdrescher Linke Spur).

PS. Auf Deutsch kann ich es besser erklären.

**Comment by pvaiko** [comment]
https://github.com/Courseplay/courseplay/releases/tag/6.01.00148, wenn du Fruchtumfahrung auschaltest fährt der Drescher nicht mehr zurück.
