### ISSUE TITLE
Wrong Trailer for this Mode

### ISSUE THREAD

**Issue by stangman04** [Courseplay/courseplay#3475]
Using a modded trailer (XL Distinction) which allows for capacities of 50k,100k,250k,500k,1million and 5 million. This trailer has 2 bins which each consists of half (25/25k, 50/50k etc). 

I am using this trailer in Combi mode and it works fine with all capacities except the 5million capacity. When using the 5million capacity I get "Wrong Trailer for this mode" but all other capacities work. Looking at the XML file all the configuration in each capacity is the same in terms of fill type etc. Is there a capacity limit for Combi mode?

**Comment by ThomasGaertner** [comment]
5 million ? really ?

**Comment by stangman04** [comment]
> 5 million ? really ?

Sugar beets and potatoes on 4x map fields is a PITA.

**Comment by Tensuko** [comment]
Get more Trailers for a Roadtrain :)

**Comment by stangman04** [comment]
> Get more Trailers for a Roadtrain :)

The problem with multiple trailers is on Kiwi farms map for example the restaurant sell point is surrounded by fenches in a small area which is a problem for longer trailers. I typically use the smaller capacity on the trailer for grain and other crops. The root crops have such a high volume. 

1 million should be fine, I am just finishing contracts since I can't afford any land yet due to prices and sugar beets/potatoes are good $$ to get me started and then probably never touching root crops again on this map. Just wanted to know if this warning was caused by a capacity limitation or not since that is the only change being made.

**Comment by ThomasGaertner** [comment]
if you want, you can change the value in drive.lua(1853) to a one >5mio. I don't want to do it...
