### ISSUE TITLE
CP to open lid at refill point

### ISSUE THREAD

**Issue by asyvan** [Courseplay/courseplay#3477]
For example, when using Bredal sprayer trailers and running a refill course (for Lime for example). When you get to the refill station, the Bredal can not be refilled unless the lid is manually opened. So I suggest CP opens the lid during its refill course when it reaches the trigger.

**Comment by GeorgeEarslight** [comment]
It's working for me on both Marwell and Fenton.
Are you sure you're passing through the triggers?

**Comment by ThomasGaertner** [comment]
hmm, should work, it's implemented . pleas give me your savegame and courses to test

**Comment by asyvan** [comment]
> It's working for me on both Marwell and Fenton.
> Are you sure you're passing through the triggers?

Yes, because if I remove the top of the Bredal it no longer have a lid, its always open. And in that configuration it refills.

**Comment by asyvan** [comment]
> hmm, should work, it's implemented . pleas give me your savegame and courses to test

I hope these links work for download.

https://drive.google.com/open?id=1Q0PtgFeVDLt9-aB5xkTqB2L3l80RxA6d
https://drive.google.com/open?id=1TKSOi25zE-sv3YCNaCStOYiA-8YIu-El

**Comment by asyvan** [comment]
> > hmm, should work, it's implemented . pleas give me your savegame and courses to test
> 
> I hope these links work for download.
> 
> https://drive.google.com/open?id=1Q0PtgFeVDLt9-aB5xkTqB2L3l80RxA6d
> https://drive.google.com/open?id=1TKSOi25zE-sv3YCNaCStOYiA-8YIu-El

The correct refill course is LimeF23, not Lime_F23.

**Comment by asyvan** [comment]
> > It's working for me on both Marwell and Fenton.
> > Are you sure you're passing through the triggers?
> 
> Yes, because if I remove the top of the Bredal it no longer have a lid, its always open. And in that configuration it refills.

Can be verified with base game as well, no mods. Take the Bredal with lid to a lime station on base map. It can not be refilled unless lid is manually opened. If CP already SHOULD take care of this, then I am making some mistake... but I can not see any.

**Comment by ThomasGaertner** [comment]
so, you mean wait point with fill point ? and with trigger you mean the same ?

**Comment by asyvan** [comment]
> so, you mean wait point with fill point ? and with trigger you mean the same ?

Well, if you refer to the wait point in the course, I added it to see if it would help to open the lid and refill. But it didn't. It refills if there is no lid at all on the Bredal, even before the wait point when it passes the refill station trigger.
