### ISSUE TITLE
I can't use some modes

### ISSUE THREAD

**Issue by dexus92** [Courseplay/courseplay#3478]
Hi,
I can't use mode 3 and 7-10. I use FS19 1.3 patch for non-steam.
Map Felsbrunn
![courseplay](https://user-images.githubusercontent.com/48918599/54928338-072f6e80-4f14-11e9-8da5-80151a21b462.png)

**Comment by Jimmy-the-Geek** [comment]
And you won't be able to until the devs activate them. Be patient.
