### ISSUE TITLE
man it runner has no courseplay

### ISSUE THREAD

**Issue by docgaming** [Courseplay/courseplay#3479]
I can't open courseplay when i am in the man it runner mod works works on every thing but that.
 i am using 6.0100144

**Comment by Tensuko** [comment]
logfile ?

**Comment by docgaming** [comment]
ok so i loaded up my test map with only courseplay and the man IT runner mod here is the log for it not sure if it is part of  same problem but the game crashed when i saved the game 
[log.txt](https://github.com/Courseplay/courseplay/files/3020198/log.txt)

**Comment by cwattyeso** [comment]
Interesting, I too had the game crash on me whilst saving last night and it was after purchasing the IT Runner Man Truck. I normally use a different modded truck for the IT Runner euipment, but figured I try this ModHub mod last night. Guess it's time to delete that Mod, as pretty sure it must have caused a crash in a game a week or two ago that I wrongly blamed on an Autoloading Trailer Pack.

Went into the Savegame Folder and the only files left in there were the Courseplay XMLs and a few other mod setting XMLs, anything actually relevant to the savegame were gone. Have had to restore from the backup save folder.

**Comment by docgaming** [comment]
just a update i tryed the man it runner with the new update for it and i got the same I allso moved all mods out of the mod folder still the same/ game will not save and save file got deleted. i allso tryed for auto drive mod and that don't work with the man it runner as well (the hud don't show)
[log.txt](https://github.com/Courseplay/courseplay/files/3042411/log.txt)

**Comment by Tensuko** [comment]
Then it is a mod issue and we cant do anything about it. Closed #3479
