### ISSUE TITLE
Strohsammler reduziert geschwindigkeit

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#3482]
Gerätschaften:
Fendt 900 Vario
Ladewagen Rapide 580V
FS19_DondiegoMap Feld 14
Fendt & Ladewagen fährt auf das Feld14
1. mal mit eingestellter Geschwindigkeit auf Feld 31 Km/h  (siehe Bild)
Ladewagen voll zum Abfahrpunkt auf Feld 31 Km/h auf Straße 51 km/h ---> Entladen
zurück zum Startpunkt --> auf Feld nur noch mit 14 Km/h bis zum Schwad Tür offen 
(siehe Bild)
![fsScreen_2019_03_26_14_34_16](https://user-images.githubusercontent.com/48583507/55002266-956c2900-4fd6-11e9-8d47-af6b65284378.png)
![fsScreen_2019_03_26_14_38_52](https://user-images.githubusercontent.com/48583507/55002287-9e5cfa80-4fd6-11e9-9de3-51fb7171ebd4.png)

**Comment by ThomasGaertner** [comment]
#3449
