### ISSUE TITLE
Karten laden nicht mit CoursPlay

### ISSUE THREAD

**Issue by Marcel0198** [Courseplay/courseplay#3484]
Hallo,

und zwar hab ich folgendes Problem:

DIe Standart-Karten laden mit Coursplay nicht, sprich es ist ein endloser Ladebiltschirm. Ich hab alle Mods mal rausgeschmissen und es geht trotzdem nicht . 

Hier mal meinen Log .
[log.txt](https://github.com/Courseplay/courseplay/files/3009659/log.txt)

Kann mir irgend jemand beimeinem Problem helfen?

**Comment by ThomasGaertner** [comment]
#3404
