### ISSUE TITLE
Tractor fails to drive reverse with several bale stackers

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/courseplay#3485]
Hello!
Log: (with debug channel for reverse driving acitvated, with the arcusin stacker) 
![fsScreen_2019_03_27_01_15_34](https://user-images.githubusercontent.com/47073128/55041595-0559ce00-502e-11e9-8baa-e0707af7798c.png)
https://gist.github.com/StefanBraun2001/bffb6baa40c66c8b9317db4a6c80f978

It appears with some bale stackers, e. g the Arcusin bale stacker for square ones, or the new anderson bale stackers for round bales (i don´t know how the Anderson square Bale stackers work, i didn´t tested it yet) When it starts reverse driving driver drives backwards, but due to steering mistakes trailer and tractor become wedged after short time, but driver still try´s to drives backwards and does not stop. Increasing turning radius does not work. With the Ursus Stacker everything works fine

**Comment by sootysax** [comment]
which mode are you using?   Reversing with a bale stacker only really works in Mode 6.

**Comment by StefanBraun2001** [comment]
Hello!

Yes, i use Mode 6 (Fieldwork)

 

Von: Scott Mueller [mailto:notifications@github.com] 
Gesendet: Freitag, 29. März 2019 13:45
An: Courseplay/courseplay
Cc: StefanBraun2001; Author
Betreff: Re: [Courseplay/courseplay] Tractor fails to drive reverse with several bale stackers (#3485)

 

which mode are you using? Reversing with a bale stacker only really works in Mode 6.

**Comment by Tensuko** [comment]
Try with 163 or higher and report.

**Comment by StefanBraun2001** [comment]
It works fine with bale stackers

**Comment by Tensuko** [comment]
Fixed. Closed. #3485
