### ISSUE TITLE
Yellow arrow comes up when I start course

### ISSUE THREAD

**Issue by cirrus1162** [Courseplay/courseplay#3486]
When I try to start a course I get a yellow arrow on the screen and on the course play window if a a message saying distance 6m tractor or combine engine will start but will not move to start of course if I use the help menu on fs19 it tells me hired work is active ie message says Demi’s hired worker this has just started happening do you think I have mod conflict ?
Look forward to any help

**Comment by ThomasGaertner** [comment]
Dont know without log

**Comment by baldrick123** [comment]
@cirrus1162 did you buy the new DLC? I have the same issue since installing that. 
Yellow arrow appears indicating distance, combine doesn't move. I'm not on the latest release of courseplay though, not tried pulling the new code in yet.

**Comment by baldrick123** [comment]
Update: Just pulled the latest version of Courseplay. Issue gone.

**Comment by Tensuko** [comment]
Looks fixed, so closing issue.
