### ISSUE TITLE
Grain transport with "Gärreste"

### ISSUE THREAD

**Issue by hsvfreak** [Courseplay/courseplay#3488]
Hello,
I can't fill any of the slurry tankers with CP at the south BGA from the map "NF Marsch 1.4" with trenches. 
I use the "grain-transport" function, but instead of filling the tanker, my traktor drive slowly thru the loading trigger for "Gärreste".  The CP-Hud even show in the Trigger "filling 0 from X". When I'm filling it manual and start it then, the unloading is without problems but the new filling fail again.
Furthermore i have the same problem like #3483 since the update on the FS1.3 patch.

Sorry for my bad English, i hope you can understand my problem.

[log.txt](https://github.com/Courseplay/courseplay/files/3013090/log.txt)

**Comment by hsvfreak** [comment]
![fsScreen_2019_03_27_13_40_43](https://user-images.githubusercontent.com/48988883/55076750-7fbe3880-5096-11e9-94d2-0091f7913ab8.png)

**Comment by ThomasGaertner** [comment]
liquid transport will be mode 8 its not implemented yet ...

**Comment by hsvfreak** [comment]
Thank you! Is there a plan when it could be? Or maybe the Bunker-Mode?

**Comment by ThomasGaertner** [comment]
yes the plan is to have it ready, after  mode2 and 3 are ready :-)
