### ISSUE TITLE
Terrain Editor and Courseplay

### ISSUE THREAD

**Issue by RagingDawn** [Courseplay/courseplay#3491]
There is an issue with the courseplay beta and the terrain editor tool. Courseplay treats it like a vehicle, so when you right click using the terrain editor it attempts to open up the CP Hud, and locks the cursor in a small radius around the crosshair. To reproduce open terrain editor (while not in a vehicle) and go to land sculpting and try to lower the terrain.

**Comment by Tensuko** [comment]
Should be the same with the Shop, if you right click there, your Courser disappears too.
Not sure if that happens too, if you are about to place a building, like a silo.

**Comment by ThomasGaertner** [comment]
try with V.155 or higher

**Comment by RagingDawn** [comment]
I can confirm it has been fixed in V.155.
