### ISSUE TITLE
overloader

### ISSUE THREAD

**Issue by Buhler0014** [Courseplay/courseplay#3493]
I am not sure if I am doing something wrong since the last time I used courseplay or not but no matter what cart I put behind the option stays unlit for over loader mode. Also when using 3 or more harvesters the harvesters will take off across the map periodically when comes to corner and I get nothing in log about error or warning this was with 151

**Comment by GeorgeEarslight** [comment]
Mode3 is not enabled yet.

**Comment by Jimmy-the-Geek** [comment]
That's because it isn't activated yet. If the function is grayed out, it's
being worked on.

**Comment by Tensuko** [comment]
Mode 3 is not activated yet.
