### ISSUE TITLE
Headlands turn direction ( Clockwise vs counter clockwise)

### ISSUE THREAD

**Issue by Hubcap-1** [Courseplay/courseplay#3494]
slightly new bug. Both programing routes in the course plot set to " Counter clockwise". you can see the tractor wants to turn as if he comes from the clock wise direction. creating all kinds of new problems.

**Comment by Tensuko** [comment]
Can you give more details ?

I know from my own testing, that some Course Generater Settings won't have an effect in some situations.
If you place the Tracktor on another corner of the field and try again, the direction should change.
Also: Changing from Headland to Midpart, the Trackter will change from CW to CCW, or from CCW to CW.

I haven't figured out yet, when does what happen, but you need to try a bit.
Screenshots from Settings and the result would be helpful.

**Comment by Hubcap-1** [comment]
If you can give me the “ De Bug “ ,channels to display I will put up a link to live video and provide a gist as well…will be tomorrow though “ beddy -by – bo time”

Sent from Mail for Windows 10

**Comment by Tensuko** [comment]
Just need a Screenshot from the new Coursegenerator screen with the settings you used and a Screenshot of the problematic situation. Might need the created Course too.

**Comment by Hubcap-1** [comment]
having problems reproducing error
