### ISSUE TITLE
Courseplay makes MouseActions in RealManualTransmission unuseable

### ISSUE THREAD

**Issue by CityFarmerDE** [Courseplay/courseplay#3495]
https://github.com/modelleicher/FS19_realManualTransmission
You still have a Cursor if you open the menu in RealManualTransmission v0.4.0.9, but you can´t use the LMB. There was no conflict till Courseplay v6.01.00150.

**Comment by Tensuko** [comment]
Did you try only CP with RealManual Transmission in modfolder ?

**Comment by CityFarmerDE** [comment]
Yes, tested with v...150, ...151 and ...155 
Made a test with default inputbindings too, same result.

**Comment by ThomasGaertner** [comment]
so to clarify: 150 worked or not ?

**Comment by Tensuko** [comment]
Es war kein Konflikt bis zur V150, würde sagen mit 150 ging es schon nicht mehr.

**Comment by CityFarmerDE** [comment]
150 funktionierte noch.

**Comment by Tensuko** [comment]
Bin vor einer Sekunde fertig geworden mit Versionen ausprobieren. Ja 150 geht, 151 nicht mehr.

6.01.00151: add actionEvents for inputs

**Comment by Tensuko** [comment]
Pls try with 178 or higher, to see if this have changed with the HUD Rework.

**Comment by CityFarmerDE** [comment]
Tested with 183, its still not working.

**Comment by Tensuko** [comment]
Closed.
