### ISSUE TITLE
New bug unloading harvester

### ISSUE THREAD

**Issue by Hubcap-1** [Courseplay/courseplay#3496]
check out the linked video....this is new !
https://www.youtube.com/watch?v=PSitqch5pNI&feature=youtu.be

**Comment by Tensuko** [comment]
This is not new, it is the newest feature.
When Combine Pipe is in the fruit, the Harvester moves back, so that the pipe is outside of the fruit, like you just saw. The Mode 2 for it is not ready yet.

Closed.

**Comment by pvaiko** [comment]
Turn off pathfinding for the combine, it'll work as before.

**Comment by Hubcap-1** [comment]
Thanx


Sent from Mail for Windows 10

**Comment by Lustiger-Hubi** [comment]
He only does that when he's fully loaded!

**Comment by Lustiger-Hubi** [comment]
Switch off the pathfinder for the combine harvester, it will work as before. If so,
how do I turn it off?

**Comment by Hubcap-1** [comment]
You will see Pathfinder on or off in the courseplay HUD
