### ISSUE TITLE
Mode4 and Mode6 can use for each other Tools

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#3497]
Fertilizing and sowing
whether I stop sowing field work or fertilising sowing does not matter
He sows with both methods

**Comment by Tensuko** [comment]
Can you explain a bit more, what you want to do and what happens? I don't get the problem right now.
Wich Device you use for sowing ? Wich for fertilising ?

Logfile is always nice to have :)

**Comment by Lustiger-Hubi** [comment]
I can put on (fertilizing sowing) or on (field work)
this is the same effect in both cases is sown.

**Comment by Lustiger-Hubi** [comment]
![fsScreen_2019_03_30_10_13_51](https://user-images.githubusercontent.com/48583507/55274120-d31dca00-52d4-11e9-92a4-28bf00e6f5f5.png)
![fsScreen_2019_03_30_10_13_42](https://user-images.githubusercontent.com/48583507/55274122-dc0e9b80-52d4-11e9-86a2-070e661e0749.png)
![fsScreen_2019_03_30_10_13_39](https://user-images.githubusercontent.com/48583507/55274123-e29d1300-52d4-11e9-86ed-1d400b4dc2c5.png)
[log.txt](https://github.com/Courseplay/courseplay/files/3025299/log.txt)

**Comment by Tensuko** [comment]
Im Feldarbeitsmods gibt es kein nachfüllen und es sollte auch nur gehen, wenn du den Dünger bereits eingeschaltet hast. Ich wetde das aber mal überprüfen, ob sich die Feldspritze auch im Feldarbeitsmodus einschaltet.

**Comment by Lustiger-Hubi** [comment]
Im Feldarbeit- Modus (Bild1) war sonst Düngen & Säen (CP -FS17) nicht möglich!
Das ging nur bei Einstellung Düngen/Säen (Bild 3)
Die Spritze (oder die Sämaschine) schaltet sich autom. ein!
Egal was für eine Einstellung ich habe ob Feldarbeit oder Düngen/Säen

**Comment by Tensuko** [comment]
Ok, ist das denn schlimm ?

**Comment by Lustiger-Hubi** [comment]
nein! war nur eine Anmerkung was sonst (CP17) nicht ging!
Danke & Close

**Comment by Tensuko** [comment]
Mode4 geht auch für z.B. Tiefenlockerer und Mode6 z.B. für Feldspritze.

**Comment by Lustiger-Hubi** [comment]
was verstehe ich unter Mode4 and Mode6
lese es öfter aber kann damit nichts anfangen

what do I mean by Mode4 and Mode6?
read it more often but can't do anything with it

**Comment by Tensuko** [comment]
Im grunde sind das die CP Funktionen, die du unten im HUD auswählst.
Mode4 ist Düngen und Säen und Mode6 ist Feldarbeit.

**Comment by Lustiger-Hubi** [comment]
Danke, hatte die Frage schon gelöscht, da ich mir das schon dachte!
Hab mal nachgezählt!
Ihr seid ja schneller als die Polizei erlaubt!
Super Super Ihr seit einfach klasse! 
ps Ich kann kein Englisch mache alles mit deepl dauert dann länger!

**Comment by Tensuko** [comment]
Kannst auch auf deutsch posten, kriegen wir schon hin, wenn das englische zu holprig wird.

**Comment by Tensuko** [comment]
Fixed. Closed.
