### ISSUE TITLE
Teile des Feldes werden beim bearbeiten noch ausgelassen.

### ISSUE THREAD

**Issue by Strawberry93** [Courseplay/courseplay#3498]
Hallo,

Ich habe dieses bereits mit dem Tiefenlocker beschrieben und jetzt habt ihr das bei fast allen Maschienen. 
![2019-03-30 (2)](https://user-images.githubusercontent.com/16910900/55273788-2d685c00-52d0-11e9-8898-cefd7e9e80c9.png)

**Comment by Tensuko** [comment]
Wie sieht der Kurs aus ? Die ganzen Debugchannel nutzen so nichts, ohne log und sind wohl auch zu viele.
Mach mal alle Wegpunkte an und mach nochmal ein Bild. Sieht nach der erste Bahn aus, die recht dicht an der zweiten ist (Feldbreite/Arbeitsbreite=Anzahl der Bahnen+Überlappung). Da kann das Wendemanöver recht eng sein an der Stelle.

**Comment by Strawberry93** [comment]
es liegt nicht am Wendemanöver wie ich bei den Tiefenlocker schon beschrieben hab sondern am Zeitpunkt wo der Drescher sein Schneidwerk herunterlässt nämlich erst ab Feldrand und das ist wenn er vorher nicht kurz stehen bleibt wie das der Helfer vom Spiel macht zu spät.

**Comment by Tensuko** [comment]
Klappt bei mir wunderbar...
Ich probiere das nachher mal mit deinem Drescher.
Wie gesagt, ich vermute die kurze Arbeitsbreite im zusammenhang mit dem Wendemanöver!
Beim Tiefenlockerer muss ich nachher mal versuchen, wie es bei mir aussieht.

![fsScreen_2019_03_30_10_02_06](https://user-images.githubusercontent.com/27344744/55273975-fba4c480-52d2-11e9-8c59-ec9c375d64b8.png)
![fsScreen_2019_03_30_10_02_18](https://user-images.githubusercontent.com/27344744/55273976-fba4c480-52d2-11e9-9ca1-6ab1c184b6e3.png)
![fsScreen_2019_03_30_10_02_28](https://user-images.githubusercontent.com/27344744/55273977-fba4c480-52d2-11e9-84cf-bdcd463912e7.png)
![fsScreen_2019_03_30_10_02_35](https://user-images.githubusercontent.com/27344744/55273978-fba4c480-52d2-11e9-9a9a-0b6f9af63d4e.png)

**Comment by Strawberry93** [comment]
Ja mit dem Debugmodus lässt er die Schneide immer unten dann passiert der Fehler auch nicht. Wie mache ich das denn bei Kalk?

**Comment by Tensuko** [comment]
Mit dem debugmodus hat das nichts zu tun. Das zeigt nur an, was er tut. Ich lasse ja nicht die ganze zeit den debug channel an. Mit dem Kalken ist das sone sache, das liegt an der streuform, ist beim düngen das gleiche. Wie gesagt ich gzck mir später mal bsschen kleinere geräte an und auch den tiefenlockerer. Eventuell liegt es auch am wenden auf dem feld an/aus

**Comment by Strawberry93** [comment]
![2019-03-30 (4)](https://user-images.githubusercontent.com/16910900/55276059-f9506380-52ee-11e9-8f0e-db93cc04076a.png)
aber die Form habt ihr richtig abgedeckt nur er hält schon am grünen Strich an statt am roten strich. Das ist alles

**Comment by Tensuko** [comment]
Mein Tiefenlockerer von Kuhn hat gerade super sauber gearbeitet.
Egal ob wenden inner- oder außerhalb des Feldes.

Auch der kleine Drescher arbeitet bei einfachen Feldern sauber.
![fsScreen_2019_03_30_14_38_39](https://user-images.githubusercontent.com/27344744/55276906-0f175600-52fa-11e9-9bed-763c883b6b77.png)
![fsScreen_2019_03_30_14_41_46](https://user-images.githubusercontent.com/27344744/55276907-1474a080-52fa-11e9-9c52-a72f1207d5f4.png)

Der große fährt nicht weit genug Rückwärts (in dem Fall der Ideal).
![fsScreen_2019_03_30_15_04_37](https://user-images.githubusercontent.com/27344744/55277188-88647800-52fd-11e9-8afa-ad93f0c54952.png)
![fsScreen_2019_03_30_15_04_43](https://user-images.githubusercontent.com/27344744/55277189-88647800-52fd-11e9-8551-f3922d4d2be4.png)

Mit dem Streuer ist halt dieses Problem:
Der eigentliche Anfang vom streuen ist recht rechte Strich und durch diese Streuerweiterung beginnt die breitere Streuung weiter hinten. Ich weis nicht ob man da was machen kann.
![fsScreen_2019_03_30_15_05_44](https://user-images.githubusercontent.com/27344744/55277219-d5e0e500-52fd-11e9-9284-125f885c3efc.png)

**Comment by Strawberry93** [comment]
Ja ich habe das doch beobachtet das er bei dem 14 debug CH statt die bei mir auf dem Screenshot nicht bis zum grünen Strich ausfährt sondern schon am roten anhält

**Comment by Tensuko** [comment]
> 
> 
> Ja ich habe das doch beobachtet das er bei dem 14 debug CH statt die bei mir auf dem Screenshot nicht bis zum grünen Strich ausfährt sondern schon am roten anhält

Wir haben es auf dem Zettel, wird sich zeigen, was man da machen kann, ich könnte dir noch vorschlagen, das ganze mal mit einem Vorgewende zu probieren, ob du dann mehr Abdeckung erreichst.

Wann etwas passiert, wird sich zeigen, da im moment andere Dinge wichtiger sind. z.B. den neuen Mode 2 fertig zu kriegen.

**Comment by Tensuko** [comment]
#3242

**Comment by Tensuko** [comment]
Beobachtung mit Striegel:
Striegel in Mode4, bleibt kurz vor Feldende schon stehen.
Striegel in Mode6, arbeitet sauber ab.

Düngerstreuer in Mode4, gleiches wie in 3242
Düngerstreuer in Mode6, viel zu weit weg vom Feldrand.

**Comment by franky135** [comment]
Hallo! Das gleiche passiert auch beim Gras mähen. cp stoppt ca 1 Schlepperlänge zu früh. Mit angehängten Geräten setzt cp zu spät ein...

**Comment by pvaiko** [comment]
This should now all be fixed except the problems described in #3558 and #3598.

**Comment by Strawberry93** [comment]
Dieser Fehler wurde nicht gefixt

**Comment by Strawberry93** [comment]
![2019-04-20](https://user-images.githubusercontent.com/16910900/56459238-0feb5700-6391-11e9-98db-cbc21b7651a7.png)

**Comment by Tensuko** [comment]
Finetuning wird immer mal wieder mitgemacht, versuch es einfach mal mit einem Vorgewende....
