### ISSUE TITLE
Mähdrescher erntet nicht 

### ISSUE THREAD

**Issue by thomascool130** [Courseplay/courseplay#3499]
Der Mäahdrescher erntet einen 1 meter und den fahrt ihr nur noch über das feld 

Hier noch ein videos 

https://youtu.be/wFwQf53ZgMc

Version  Courseplay_6_01_00157

https://pastebin.com/v9tgNrfL logs

**Comment by knoxville73** [comment]
Hello thomascool.  It's because you have different fruit in the field, see in the corner.

**Comment by Tensuko** [comment]
Kannst du das nochmal ohne FS19_EnlargeFieldYield ausprobieren ?

Werde paralel auch nochmal einen test machen.

**Comment by Tensuko** [comment]
> 
> 
> Hello thomascool. It's because you have different fruit in the field, see in the corner.

True, some left overs here and there. Good point...

**Comment by thomascool130** [comment]
I was right on the other fruit in the corner made it away and it went again


hast recht lag an der anderen Frucht in der ecke habs weg gemacht und es ging den wieder

**Comment by Tensuko** [comment]
Ok, dann ist ja alles gut. Closed.
