### ISSUE TITLE
game freezes when overload is activated

### ISSUE THREAD

**Issue by Firebaugh2014** [Courseplay/courseplay#3500]
on eastbridge hills everytime i activate the overload course the game freezes up and the workers start missing sections of the course and the overload does not work

**Comment by Jimmy-the-Geek** [comment]
That mode isn't activated yet.

**Comment by Tensuko** [comment]
How do you even activate the overloard course ?
I course with a Waitpoint and start with a overloader?

**Comment by Firebaugh2014** [comment]
how long before its active on this map i love this map

**Comment by Jimmy-the-Geek** [comment]
It's not a map-specific mod. At any rate, this mod will be made to work
with in-game stuff before any modded items. And, it will be done as soon as
the devs can get it done. Be patient.

**Comment by Tensuko** [comment]
Mode3 Overloader will come later, 1st Mode2 gets a remake. Closed.
