### ISSUE TITLE
Game crash when harvesting potato - LUA Error combines.lua:484: attempt to index field 'spec_drivable' (a nil value)

### ISSUE THREAD

**Issue by Mychomizer** [Courseplay/courseplay#3501]
Getting this every now and then when harvesting a big field with potato

Courseplay v6.01.00157
Harvester: GRIMME VARITRON 470 PLATINUM TERRA TRAC (Stock harvester)
Truck: TATRA PHOENIX 6X6 AGRO-TRUCK (Stock truck) + Trailer KRAMPE SB II 30/1070 (Stock Trailer)
Map: Nordfriesische Marsch 1.5

The equipment are contract leased

Sorry for a long long but the issue starts at line 9174
[log.txt](https://github.com/Courseplay/courseplay/files/3026111/log.txt)

and yeah I saw i had one "_tmp.drivedownload" file in the mods folder but I don't think thats the issue anyways.

**Comment by Tensuko** [comment]
You got a few modmaps inside your modfolder. As you see, renaming them with deactivated, doesn't help. You got to take them out.
Also try take out realdirtcolor.
 Does the issue appear when the Harvester is about to turn, or the Tatra when try to unload the Harvester ?

**Comment by Mychomizer** [comment]
I tried again now without extra maps in mod folder (and some other) and ran into the same issue after a few turns. Seems to happen when the harvester are turning.

Next up is to test without realdirt
[log.txt](https://github.com/Courseplay/courseplay/files/3026629/log.txt)

**Comment by Mychomizer** [comment]
Samme issue without Real Dirt

[log.txt](https://github.com/Courseplay/courseplay/files/3026946/log.txt)

**Comment by Mychomizer** [comment]
Seems to be same issue (or similar) with the small trailed beet harvester. (GRIMME SE260 +GRIMME KS75-4)

[log.txt](https://github.com/Courseplay/courseplay/files/3027105/log.txt)

**Comment by Tensuko** [comment]
I wasn't able to reproduce it.
Can you upload your savegame and the course in a zip file and tell me what to do to get that error ?

**Comment by JoergFra** [comment]
I think I had the same issue while harvisting.
I Use CP Version ..163. The Harvester ist controled by the normal ingame worker. 
Modmap: Suedhemmern
Harvester: 

HIre is the log: 
[log.txt](https://github.com/Courseplay/courseplay/files/3051318/log.txt)

It happens while i tried to fire the worker at 1:40.

And a Video where you can see when the crash happens:
https://youtu.be/k_rsWBB_WNI

**Comment by Tensuko** [comment]
@JoergFra 
That seems Mode2 related, so no support till Mode2 got reworked. sry!
#3311 
@Mychomizer 
For the turn.lua:589 we can't do much right now.

Does this LUA Error happens a lot with V166 or higher ?

**Comment by Mychomizer** [comment]
I haven't had the time to test for quite some time sorry. I will try to see if I can test tonight and report back.

**Comment by Mychomizer** [comment]
So I had some time to play yesteday and I ran a big field (around 4h harvesting time) of potatoes with the GRIMME VARITRON 470 PLATINUM TERRA TRAC and wasent abel to recreate the error so it seems like V166+ have fixed the problem.

Thanks for your hard work guys
