### ISSUE TITLE
Bale Wrapper doesn't stop when wrapping

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3507]
The bale wrapper used to stop when it was wrapping bales, and I used to be able to drive next to stacks of bales and set the field speed to 1mph, and it would wrap the whole line of bales..  now the vehicle doesn't stop and just knocks over all the bales.

I even if you were wrapping them along the same course as the baler drove, it would be better for the wrapper to stop, and leave the bales in the original position, rather than driving along with them and dropping them where they were finished.

![fsScreen_2019_03_31_09_24_12](https://user-images.githubusercontent.com/6591048/55289661-29ebd800-5397-11e9-9233-600be5d589f5.png)

**Comment by GeorgeEarslight** [comment]
#3237 ?

**Comment by Tensuko** [comment]
Not implemented yet, under work.
3237 should be related, thx.

**Comment by sootysax** [comment]
the Ursus will actually drop the bales when done wrapping.

**Comment by Tensuko** [comment]
Test again with 159 and report.

**Comment by mxalbert** [comment]
I experienced the same issue before 159, just tested with 160 and everything worked as expected. From my side thank you for the fix.

**Comment by Tensuko** [comment]
Closed.
