### ISSUE TITLE
not following lines

### ISSUE THREAD

**Issue by ploughedfieldman123** [Courseplay/courseplay#3509]
why isnt the tractor in centre of lines 

[ <a href="https://i.imgur.com/vJZnYuj.jpg"><img src="https://i.imgur.com/vJZnYujl.jpg"></a>  ](url)

**Comment by Tensuko** [comment]
Check the Offsetmenu...
And if you have more trouble, pls give more details about your problem.
Debug 9 and 14 give some nice driving informations too (screenshot and logfile).

https://github.com/Courseplay/courseplay/wiki

**Comment by mehdinasef** [comment]
I have the same problem. CP sometimes sets an offset automatically  to tools that does not need any offset.

**Comment by Tensuko** [comment]
So it is just, that you have to readjust the offset to zero ?
Can you try a bit if that comes from specific tools or maybe from an angle of the device stands towards another tool/tractor when creating the course ?

Maybe use the mower and stay in 90° infront of the field and like 45°.
Embrace my paint skills XD
![offset](https://user-images.githubusercontent.com/27344744/55323675-094b7d00-5480-11e9-9cf0-0d5a632889d7.png)
Could be something like this with the mower. I remember the old GPS had teh same issue when the tool was more at the side to the tractor.
![offset2](https://user-images.githubusercontent.com/27344744/55323780-5f202500-5480-11e9-9546-3d9032b81689.png)

**Comment by GeorgeEarslight** [comment]
@ploughedfieldman123 Also remember that Courseplay stores settings **per machine** (tractor, combine, etc) not per implement.
It has happened to me a lot of times that I forget that I used the offset on the previous course.

**Comment by Tensuko** [comment]
Can you pls report if the offset was your issue ? So I can close this or we make a real Issue out of that...

**Comment by Tensuko** [comment]
If you still getting Issues with the offset, make a new Issue with more details pls and check your settings.
Closed #3509
