### ISSUE TITLE
Zähler "unbegrenzt" funktioniert nicht

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#3510]
Situation: Mode1 wird Stroh zur BGA transportiert. Funktioniert ohne Probleme
Problem: Nach 10 Fahrten ist Schluß, obwohl bei Anzahl "unbegrenzt" eingestellt wird.
Erst nachdem man auf "Weiterfahren" klickt, gehts weiter, wieder für 10 Fahrten.
Ist das gewollt oder ein Bug?
![fsScreen_2019_04_01_11_11_39](https://user-images.githubusercontent.com/21023840/55316758-62f77b80-546f-11e9-9c71-eed1d07bcb24.png)

**Comment by Tensuko** [comment]
Es stand erst Unbegrenzt da, einmal draufgeklickt, wurde dies zu einer 11, dann konnte man nur noch zwischen 0 und 10 einstellen.

**Comment by Tensuko** [comment]
Funktioniert!
1-10 und durch draufklicken schaltet man um zwischen Zähler und Unbegrenzt.
Fixed. Closed.
