### ISSUE TITLE
Baler does not unload by its own

### ISSUE THREAD

**Issue by Th301** [Courseplay/courseplay#3512]
Since one of the last updates, the combi machine to wrap silage bales does not unload by its own anymore. 

I use 
FS19 AUTOMATIC UNLOADING FOR BALE WRAPPERS
and
Round Baler Extension v1.0 FS19 
for this work. Last time I saw this work fine was on friday I think.

I know, this is perhaps a mod-conflict but it worked perfectly before! ^^

**Comment by Tensuko** [comment]
Did you try without the mods ?
Try one by one to find out wich of the two mods causing the conflict.

**Comment by Th301** [comment]
I just made the tests you suggested.

I tested with:
- both mods active
- with none of the two mods active
- with only Automatic Unload active
- with only Round Baler Extension active.

Nothing worked :(

**Comment by ncolton** [comment]
I wish I had updated CoursePlay more recently as I could give you a narrower range, but I also found this behavior. Somewhere between 6.01.00110 and 6.01.00160 is when the baler ceased auto-unloading.

In my case, I am not using either of the two mods Round Baler Extension or the auto-unload mod.

The device I'm using is the KUHN FBP 3135, in case it matters.

**Comment by pvaiko** [comment]
Thanks, I know exactly where I screwed it up, the tools which are balers _**and**_ bale wrappers don't work as balers at the moment.

**Comment by Tensuko** [comment]
Try with 161 and report back pls.

**Comment by Th301** [comment]
I will try it in the evening.

One question before: should it work without one of the extensions I mentioned in the initial post?

I think I will just make the same tests like before, with all combinations. This will keep up the comparability.

**Comment by Tensuko** [comment]
That would be nice if you can test all situations to make sure it works fine now.

**Comment by hsvfreak** [comment]
Befor the unload-problem the Kuhn FBP 3135 was wrapping while he was baling and has only wait, when the wrapping needs more time then the filling of the Baler. Now it waits until it finisched the wrapping and starts then to fill the baler again. Could it be changed or isn't it possible?

**Comment by pvaiko** [comment]
Should work now for balers, bale wrappers and the combination of the two.

**Comment by ninjayx02** [comment]
have you the auto unload mod set to automatically unload bales

**Comment by Tensuko** [comment]
CP got nothing to do with that mod.

**Comment by iljarogoff** [comment]
Works fine with .00162

**Comment by jspring0811** [comment]
> have you the auto unload mod set to automatically unload bales
To expand on what ninjayx02 said...   For Automatic Unload mod, baler-wrapper, you have to "Z key" change drop mode: Manual/Collect/Automatic (and you can also "LCtrl-LAlt" key toggle wrap on/off).  For wrapper-only, "Z key" change drop mode Manual/Automatic.

**Comment by Tensuko** [comment]
Still dont know what it got to do with cp...
As this is only for using on your own, not cp controlled. Why would you want to manual unload when cp does the work.

Explain a bit more what you expect to happen with that mod in combination with cp...

**Comment by ninjayx02** [comment]
if you have the auto unload mod in game, then the settings affect courseplay,  e.g.  set the baler to for manual unload and courseplay creates the bale, wraps the bale, then stops because of the manual unload function of the auto unload.  Try it and see

**Comment by pvaiko** [comment]
Original issue solved, closing.

**Comment by Th301** [comment]
Sorry, I found no time to test yesterday.
But reading all the comments, I think it should work now :)
