### ISSUE TITLE
Grain Transport - Adding Message when Silo is empty or full

### ISSUE THREAD

**Issue by ninjayx02** [Courseplay/courseplay#3513]
it appears that if there is not enough grain to fill the trailer, it waits at the fill point for manual intervention,  but no message

**Comment by sootysax** [comment]
@ninjayx02 as it has always done..  not a bug

**Comment by ninjayx02** [comment]
in 17,  there was a message that the silo was empty

**Comment by Tensuko** [comment]
When got a bit grain, it wills up till empty and then drive its round.
When silo is empty, it gives out a message.
Thats what I remember from my NF_Marsch Straw Compost loop with silo and compost_master.

**Comment by Tensuko** [comment]
should be done already, still tweaking the new Triggers a bit. Closing anyway.
