### ISSUE TITLE
LS19 Mods/FS19_CoursePlay6/mode2.lua:356: attempt to compare nil with number

### ISSUE THREAD

**Issue by Berndie5** [Courseplay/courseplay#3514]
Hello,

Combine works on the field via CP, pickup (tractor and trailer) should drive via CP. Just before the level is reached, nothing works. Pickup does not start, partly freezes the game, must restart.

[log.txt](https://github.com/Courseplay/courseplay/files/3032785/log.txt)

**Comment by cwattyeso** [comment]
You should probably check the pinned thread at the top of the GitHub: https://github.com/Courseplay/courseplay/issues/3311

Mode 2 is not currently supported as it has not been written and coded yet for Courseplay 6 and FS19, it is still using old code from FS17, so it's there for people to use at their own risk, but the devs won't offer any support for people using it.

**Comment by Tensuko** [comment]
#3311 Closed.
