### ISSUE TITLE
Drescher drives off the track when he's full.

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#3515]

**Comment by Lustiger-Hubi** [comment]
Drescher drives off the track when he's full.
CP version>6.01.00162 
![fsScreen_2019_04_02_15_37_26](https://user-images.githubusercontent.com/48583507/55407261-f7d8a280-555d-11e9-8238-1fb2852e83d1.png)
![Uploading fsScreen_2019_04_02_15_37_28.png…]()
![Uploading fsScreen_2019_04_02_15_37_30.png…]()
![Uploading fsScreen_2019_04_02_15_37_33.png…]()
![Uploading fsScreen_2019_04_02_15_37_36.png…]()

**Comment by eddiem54** [comment]
[https://github.com/Courseplay/courseplay/issues/3496](url)

**Comment by pvaiko** [comment]
#3496 is what he meant.
