### ISSUE TITLE
Tractor's crashing!

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#3517]
Traktor fahren stumpf auf einander!
Tractor's crashing!
CP Version 6.01.00162
![fsScreen_2019_04_03_13_44_42](https://user-images.githubusercontent.com/48583507/55476585-46964300-5617-11e9-994a-106fe1d12aaf.png)

**Comment by Tensuko** [comment]
Because Mode 2 is still under rework....
#3311

Closed.
