### ISSUE TITLE
enhancement make checks of filling levels optional

### ISSUE THREAD

**Issue by bp-ouhaha** [Courseplay/courseplay#3518]
Hi courseplay-dev,

I love your work for many many year! I have a small suggestion for courseplay in FS19:
- is it possible to disable (oilseed-raddish filling level > 0) on the weeder [fieldwork mode]?
- is it possible to disable (fertilizer filling level > 0) on the seeder/corn-planter [seeder mode]?

Thanks for all help so far, I love this mod!

As I can program, maybe I can implement it myself? Would you be open to this? A little starting point would be nice.

Best Regards

**Comment by Tensuko** [comment]
So you want the fertilizeroption disabled if not used ? That is already possible, but need to wait for the HUD Rework.

Sane could be possuble for oilseed I guess.

**Comment by ThomasGaertner** [comment]
i don't understand you intension. Do you want to use a seeder as a cultivator ? is it manually possible ?

**Comment by Tensuko** [comment]
I think the problem is, if you don't fill up oilseed-raddish in the weeder or fertilizer in the seeder, you get the msg that you got to fill up the machines.
Thats why he wants to disable the check for seed/fertilize higher then 0.

Else you can't use a specific weeder (müsste Striegel sein?) that got a oilseed-radish tank.
Same for seeder with fertilize option. But as I said, that options are available, just got to get them back on, thats related to the combine distance adjust right now.

#3433
#3457

**Comment by ThomasGaertner** [comment]
its a bit problematic: technically i would need to count it to the sowing machines. but i don't want to make an option to deactivate the sowing function on a sowing machine. This would be valid for all sowing machines

**Comment by ThomasGaertner** [comment]
try with v.205 or higher ...

**Comment by Tensuko** [comment]
As feedback of #3637 - It is fixed (Weeder with fert works without it).
Closed.

**Comment by bp-ouhaha** [comment]
it is manually possible to:
- remove weeds without seeds in the weeder Pneumaticstar 900.
- plant corn without fertilizer using Vaderstad Tempo V8.

It is solved in v.205 with a new option in the UI (Vehicle Specific Settings tab -> Fertilizer function of Sowing machine).

Thanks all! Wonderful!

I will try the weeder later on.

**Comment by bp-ouhaha** [comment]
The weeder works very well without seeds in "fieldwork" mode.

**Comment by bp-ouhaha** [comment]
after testing over and over: donation made for happy fixing 👍

**Comment by Tensuko** [comment]
Glad you like it. Happy Farming :)
