### ISSUE TITLE
LUA error seems to be Crashing Saves - base.lua:1717: bad argument #1 to 'concat'

### ISSUE THREAD

**Issue by OutlawVol** [Courseplay/courseplay#3519]
Looks like an there's a base.lua argument keeping the game from saving on the latest version (6.01.00162)

Look at the last line to see the argument error

https://pastebin.com/czfuHSDw

**Comment by Tensuko** [comment]
Pls post the whole logfile.
You just got to drag and drop the log.exe into your comment box...

**Comment by OutlawVol** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3040684/log.txt)

**Comment by pvaiko** [comment]
You seem to have quite a few mods installed, throwing a million errors. Highly unlikely this is a Courseplay error, closing. Reopen if you can reproduce this with official mods only.
