### ISSUE TITLE
Transform group for Distance Calculation (next time make a better title pls...)

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#3520]
Hwy guys,
I know, new mode2 is in work,
I will only say that the distance between agco ideal and the trailer is calculatet automatict by 8.6 m actually.
This is a bit less, 9 to 9.5m were better.
Please can you tell me, which transform group courseplay search in the ideal.i3d or ideal.xml to calculate the distance?
So i can move the transformgroup on a other position.
Lg
Andreas

**Comment by Th301** [comment]
what a meaningful title...

**Comment by limoman39** [comment]
How do you guys not get frustrated with the comments you get from the people using your mod?

Keep up the great work guys!!!

**Comment by andreasthu** [comment]
Sorry guys.
I amon travel and my aignal quality is low.
Tipped in a normal title, but thwre was lost some.
Lg
Andreas

**Comment by ThomasGaertner** [comment]
Its the distance between root node and discharge node. Im not sure that you should möge one of these. Use the Manual offset instead

**Comment by andreasthu** [comment]
Ok, thanks for the answer.
I am looking atthese tg's.
When it's is to complicatet i use manuall mode.
And wait for new mode2.
Lg
Andreas

**Comment by Tensuko** [comment]
Question Answered I guess.
Closed. #3520
