### ISSUE TITLE
Horsch Pronto 9DC füllt nicht neu auf (Multisilo)

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#3521]
Habe mir einen Kurs erstellt (Säen, Mode4), läuft. Einen Kurz für den refill angehängt. Fährt die Route ab, aber fährt dann durch den Trigger durch. Klappe vom Horsch geht auf. Es handelt sich um ein Multisilo, welches Dünger und Saatgut ausschüttet. Manuell auffüllen geht problemlos.

**Comment by Tensuko** [comment]
Einmal das komplette logfile bitte. log.txt in die Kommentarbox ziehen.

Welches Multisilo ist das ?

**Comment by iljarogoff** [comment]
Ist ein Multisilo, welches bei der DonDiego Map dabei ist.
[log.txt](https://github.com/Courseplay/courseplay/files/3044989/log.txt)

**Comment by Tensuko** [comment]
Hmm log sieht erstmal gut aus.
Eventuell komme ich morgen dazu mir das mal an zu gucken.
Muss erst die Map laden.

**Comment by iljarogoff** [comment]
Ich bin mir selber nicht sicher, aber ich meine zu glauben, dass es auf einem anderen Kurs schon mal funktioniert hat. Leider habe ich keine Beschreibung, wie man solche kombinierten Kurse _richtig_ einfährt.

**Comment by Tensuko** [comment]
Im grunde vom Feld über den Trigger, wenn du richtig über den Trigger fährst, sollte der Deckel aufgehen, oder zumindest im F1 Menü die option zum auffüllen kurz auftauchen.

**Comment by iljarogoff** [comment]
Ich denke, den Trigger erkennt CP ja, da der Deckel der Horsch aufklappt und der Schlepper langsam heranfährt. Aber in dem Moment, wo der Dünger oder Saatgut eingefüllt werden sollten, fährt er einfach weiter , ohne stehen zu bleiben.

**Comment by ThomasGaertner** [comment]
Debug 2 und 19 bitte

**Comment by iljarogoff** [comment]
Bitteschön
[log.txt](https://github.com/Courseplay/courseplay/files/3048030/log.txt)
