### ISSUE TITLE
No waiting time for combi mode and 100% fill-level

### ISSUE THREAD

**Issue by Th301** [Courseplay/courseplay#3522]
Yesterday I started harvesting sugar beet with the Holmer (the big one).

I used only a small trailer to unload, so it is filled for 100% in one unloading process most of the time.
I figured out, that there seems to be no waiting time to check the surrounding area for clearance when the trailer is fully loaded. The tractor drives straight towards the unloading course without regard of the harvester. It's always a crash than.

When the trailer is only loaded 95%, the tractor stops accurately and says: "Waiting for a clear waiting position".

Is it possible to activate the waiting time for fully loaded trailers too?

**Comment by Tensuko** [comment]
#3311 
Closed.

**Comment by Th301** [comment]
Sorry, my fault!

**Comment by Tensuko** [comment]
No Problem.
When Mode 2 is reworked and you face issues, feel free to make a new issue :)

**Comment by Raints** [comment]
In my opinion its the only problem for mode 2 atm when driver's leave the field with full load. Everything else is depend's how you set your course up and it is working really good for me.
