### ISSUE TITLE
bale autoloaders

### ISSUE THREAD

**Issue by docgaming** [Courseplay/courseplay#3523]
this is more of a suggestion with the autoloaders from by testing is woks ok apart from where it stops to unload. it stops with just the back end still in the tip trigger so only the bales at the back will set sold it will be better if it stops in the middle of the trigger if you can do that

**Comment by Tensuko** [comment]
There is a distance set in the HUD. Can you try set it down to 0 if this case still happens ?
Normaly that setting is for unloading somewhere to store them and to get a distance to the old pack of bales.

**Comment by docgaming** [comment]
it was set to 0 i have tried to set it back as well but still unloads in the same point where is unloads is good for everything about from the autoloaders 
![Screenshot_3](https://user-images.githubusercontent.com/48932718/55637141-4be0c280-57bc-11e9-92bf-698d2042536b.png)
this is where it unloads and only the back roll is in the sell point 
![Screenshot_4](https://user-images.githubusercontent.com/48932718/55637303-a24e0100-57bc-11e9-8f5a-70347e27ca31.png)
it needs to be around here for them all to sell

**Comment by Tensuko** [comment]
That is becosue those kind of autoload is not supported.
CP only works with the normal Bale Loaders.
No Idea if that will ever become full supported, but for sure not for now, as other things are more important.

**Comment by Tensuko** [comment]
Closed.
