### ISSUE TITLE
Grain transport Corn or Maize

### ISSUE THREAD

**Issue by asyvan** [Courseplay/courseplay#3524]
Q: I can't get the trailer to load Corn at the Silo. It says the filltype does not exist (or something like that). I do have corn. But when looking at the XML for the Silo itself the filltype is called Maize. Is CP checking for the correct filltype or is my error elsewhere?

**Comment by Tensuko** [comment]
Logfile pls.
Wich Map ?

**Comment by ThomasGaertner** [comment]
"or something like that" : and what exactely ?

**Comment by asyvan** [comment]
Map is New Woodshire

ZIP of the CP courses
https://drive.google.com/open?id=1yCMg49UkEpMXRJwnBLW-aNWRcAIi9yXs

ZIP of the Savegame
https://drive.google.com/open?id=1RP6PqmMyGCZKkBGfg08l5Pk5TtI3cSv_

ZIP of FS19 log file
https://drive.google.com/open?id=18SlNCl3m7YXZbKkD85J6VeMR4yKPUszy

Screenshot
https://drive.google.com/open?id=1Pk5I4BBwiu7bcul8ngJHC3kiKtT1nJAB

Youtube video
https://youtu.be/bi1R-LSx_NQ

**Comment by asyvan** [comment]
And I can't get it to load Sun Flowers either. Have not tried any other crop. I have not done this before on any other map or any other silo either. But I suspect the silo on this map being the problem ?????

**Comment by Tensuko** [comment]
Try the same on vanilla map, if it works then it is the map. Try and report pls.

**Comment by asyvan** [comment]
This can be closed.
I found the issue, there was a Lime Refill that was in reach and CP reacted to that refill point instead of the silo. If I remove the Lime Refill it works, even on the New Woodshire map.
Sorry for the inconvenience.
