### ISSUE TITLE
Baler/Wrapper combi should not unload during the turn

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/courseplay#3525]
Hello!
Since Bale Wrapper support the kuhn baler with wrapper does unload bales during turning maneuver. He didn´t do that before. Is this wanted?

**Comment by Tensuko** [comment]
Try with 164 or higher and report.

**Comment by StefanBraun2001** [comment]
It is working again, baler/wrapper combi does unload bales when finished turning maneuver
