### ISSUE TITLE
CP's Engine auto off is enabled for unloading mode6 combine

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#3528]
When combinein mode6 is unloading to at field edge the auto shut off CP does is not disabled. CP shuts down the engine after 30 secs. This is a change from 17 sorry if this was intentional.  Or is a part of the mode2 refactoring

**Comment by Tensuko** [comment]
Mode2 and Combine not communicate with each other yet. I guess that is the Issue.

'is not disabled' ? I guess you mean is disabled, else it would work like intended ?

There is still some stuff to do, but a lot depends on Mode2.
Need to wait a bit more.

**Comment by pvaiko** [comment]
Why is this a problem?

**Comment by Tensuko** [comment]
Actually I would just let the engine run till the mode2 driver arrives... so I don't see a problem but I don't mind a change...

**Comment by pops64** [comment]
There is no communication. In 17 auto off would check to see if there is any active courseplayers. AKA there was a tipper to unload to. I guess this got disabled or is no longer used. @pvaiko This would be a problem because if you look at the engine start time issue this would cause a 2-3 sec delay every time it was unloading at a field if it was working. That was why in 17 it was decide to prevent combines for using shut off when unloading.

**Comment by Tensuko** [comment]
Mode2 is under rework, thats why there is no communication.
Wait for the rework in Mode2, then we look into some Fine Tuning with Communication.
Closed. #3311 #3528

**Comment by pops64** [comment]
This doesn't have to deal with mode2 at all. Just the conditions for auto off didn't get carried over to 19. Line 1176 in AiDriver and Line 891 to 895 in star stop are all the 17 conditions that didn't get carrier over
