### ISSUE TITLE
CP drops down implement way too early in seeding/fertilizing

### ISSUE THREAD

**Issue by asyvan** [Courseplay/courseplay#3529]
CP drops down (starts spraying etc) the implement way too early, when seeding and fertilizing and plowing (field work). See the following short video for an example.

https://youtu.be/w1JiABn1mRg

**Comment by pvaiko** [comment]
If you could post a log (and maybe a video) with debug channels 12 and 14 that would be great.

**Comment by asyvan** [comment]
Video with debug 12 and 14.
https://youtu.be/0ZC75zeiqOM

Log file:
https://drive.google.com/open?id=1A7cDkb_ChMmZGUkgMt2vqQ0PS7hFWPfZ

**Comment by pops64** [comment]
Also saw this issue.  It lowered the implement when the tractor reached the field. And not the front marker.

**Comment by sootysax** [comment]
wait, you can seed a field without plowing it first?   thats kind of ridiculous GIANTS...

**Comment by Raints** [comment]
@sootysax It's called direct seeding, has nothing to do with Giants.

**Comment by pvaiko** [comment]
This should have been fixed by 3252242e.
