### ISSUE TITLE
Courseplay doesn't let me chosse a mode

### ISSUE THREAD

**Issue by Mythmen** [Courseplay/courseplay#3530]
Hi i downloaded Coursplay yesterday and it load perfectly fine i see it in my mod ingame, can activate it (or not), show up in game but then there the problem, i dont have access to any of the mode (ie: combi mode etc) the only mode i have access is field work and driver assist.
Thanks to whoever can help me fugured out this issue.

P.S: i have downloaded it several time and from different place and version and it always the same
![fsScreen_2019_04_06_09_38_11](https://user-images.githubusercontent.com/49342426/55670325-fdc9ce80-5850-11e9-9cd6-545541a86eb3.png)

**Comment by Raints** [comment]
In combine you can only use those two mode's. Did you try in different vehicle?

**Comment by Mythmen** [comment]
just tried and it work thank a lot and sorry if i opened an issue for nothing

**Comment by Tensuko** [comment]
HUD is under refactoring.
And yes Combine dont have other modes yet (selfunload not active yet).
Closed. #3530
