### ISSUE TITLE
Combine Self unload not enabled

### ISSUE THREAD

**Issue by khurrambaig007** [Courseplay/courseplay#3531]
HI 
Combine Self unload is not enable. 
currently My CP ver is  6.01.00164-dev
my Game version is 1.31

any idea ? why it is not enabled

![image](https://user-images.githubusercontent.com/5454894/55672804-bbd47300-58b8-11e9-90bc-41758ebb89c7.png)

**Comment by Tensuko** [comment]
Because it is not implemented yet... Closed. #3531
