### ISSUE TITLE
light of the vehicles at night when we stop the courseplay

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/courseplay#3533]
Hello,

Just a little report. When it is dark and you stop the Courseplay, the vehicle lights go out. Is it possible to keep them on?
Also, when you stop the Courseplay, the hitched machines stop working. Each time you have to restart them. (with a square bale press, for example ...)
Thank you

**Comment by Tensuko** [comment]
I don't know what would happen, if CP finish the job by itself.

So:
- Manual Stop CP, keep on light and tools
- CP finish job by itself, turn off light, stop and fold the tools
