### ISSUE TITLE
Mode 2, unload trigger not recognized, trailer does not unload

### ISSUE THREAD

**Issue by gabriel170603** [Courseplay/courseplay#3534]
I am using the map Southern Farming and it seems, that CP doesn't recognize the silo and doesn't unload the trailer. I tried it in different modes as well, it didn't work. I tried everything I could, CP doesn't recognize the trigger.

[FS19_Southern_Farming_CPCourses.zip](https://github.com/Courseplay/courseplay/files/3051471/FS19_Southern_Farming_CPCourses.zip)
[Southern_Farming_Savegame.zip](https://github.com/Courseplay/courseplay/files/3051474/Southern_Farming_Savegame.zip)

**Comment by Tensuko** [comment]
Does it work on other maps ?

**Comment by gabriel170603** [comment]
It does work on other maps, how and where can I get the log file?

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
I would rather call it a Map Issue, we can't rly help you with that.
Right Silo for the Fruits to unload ?
What silo ? What trigger ? How is scripted ? etc etc...
But post logfile anyway, maybe I can see something there.

debugchannel 2 and 19 on pls.

**Comment by gabriel170603** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3051966/log.txt)
It is the right silo for the fruits to unload, when I go over the trigger without CP I can unload the trailer, thats no problem. It is a usual grain silo.

**Comment by gabriel170603** [comment]
I just tried it in Mode 1 and it works perfectly fine, just not in Mode 2

**Comment by Tensuko** [comment]
Not sure if that is a Mode2 issue, if so, got to wait for mode2 rework.

**Comment by Bruid3** [comment]
I am having a similar issue with the last update (Courseplay_6_01_00167) on the Felsbrunn map.
I have set up several Combine unload courses where the Trailer will go to the trigger try to tip and leave with the trailer up in the air with the load still on board.
If I stop the driver and re enter the trigger the trailer is immediately displaying the unload tool tip.
On one occasion I tried stopping the driver and selecting a different side of the trailer to unload (the back) and then starting the Driver and that caused the trailer to not display the tool tip until I cycled through all of machines back to the tractor pulling the trailer.
The previous version I had was Courseplay_6_01_00161 which worked fine for this sort of thing.

**Comment by Bruid3** [comment]
I will have another crack carting Sunflower on the current contract I have.
Its odd in that I had it working previously.
I have tried setting a tip point manually to make sure the trailer was over the trigger as well as just driving through the trigger when I set the course up. I have also made sure I was centered and approaching the trigger straight on and leaving it the same way.

**Comment by Tensuko** [comment]
No need a tip point for triggers.

Currently Thomas is busy with tweaking the HUD, need to wait a bit before we can look at it.
I see it more as a map problem...

**Comment by gabriel170603** [comment]
Yeah, I think it worked for me, when I drove to the trigger the other way around and drove over it straight. I think with that I will close the issue, because it is not a real 'issue'.
Still thanks for your help everyone
