### ISSUE TITLE
LS19: Error: Running LUA method 'update' 

### ISSUE THREAD

**Issue by AgrarlohnHohenzollern** [Courseplay/courseplay#3536]
Hallo zusammen,
ich hab folgendes Problem:
Sobald ich bei Courseplay bei geöffnetem Fenster mit der Maus klicke wirft es mir folgenden Fehler in der Log:
2019-04-07 14:32 Error: Running LUA method 'update'.
2019-04-07 14:32 C:/Users/Josh der Frosch/Documents/My Games/FarmingSimulator2019/mods/ZZZ_Courseplay_6_01_00166/input.lua:486: attempt to index a nil value

Kann mir vieleicht jemand helfen?
Hab es auch schon versucht indem ich nur Coursplay im Mod-Ordner in der Version 6.01.00166 hatte, der Fehler kommt trotzdem. 

Vielen Dank schon mal und noch einen schönen Sonntag

[log.txt](https://github.com/Courseplay/courseplay/files/3051539/log.txt)

**Comment by Tensuko** [comment]
Welches Fenster genau ?
Habs eben ausprobiert und kein Fehler.
Erzähl mal bitte genau, was du gemacht hast.

**Comment by rmn18** [comment]
Er meint sicher das Course Play Menü ,ich habe auch den selben Fehler wie er ,jedes mal wenn man die rechte Maustaste drückt .

**Comment by Tensuko** [comment]
'Das Courseplay Menü' - Es gibt viele Menüs in Courseplay...
Wenn ich in Courseplay rumklicke, bekomme ich garkeinen Error.
Bitte einmal die Tastenbelegung zurücksetzen und dann nochmal ausprobieren.
Und wenn der Fehler weiterhin auftritt, bitte einmal stück für stück erklären, was ihr macht.
Beginnen mit 'In Fahrzeug X einsteigen'

**Comment by AgrarlohnHohenzollern** [comment]
Ich meinte das Menü, das angezeigt wird sobald ich Courseplay öffne (siehe Screenshot). Der Fehler kam schon beim Öffnen von Courseplay und sobald ich  (egal mit welcher Maustaste und egal wo hin) geklickt habe. Das ganze war auch unabhängig vom Fahrzeug, das war bei jedem der Fall.

Hab die Tastenbelegung jetzt zurück gesetzt und jetzt kommt es nicht mehr. 
@Tensuko vielen Dank für den Tipp. Weißt du wieso es jetzt nicht mehr kommt? Würde gerne vermeiden, dass der Fehler wieder auftritt.
![fsScreen_2019_04_07_22_26_01](https://user-images.githubusercontent.com/49366233/55689418-7d0bef00-5984-11e9-9655-2eb938543d18.png)

**Comment by Tensuko** [comment]
Warum kann ich nicht genau sagen. Kann an einer Mod liegen die sich verschluckt hat mit der CP Belegung, kann ein CP Update gewesen sein, etc etc. Wenns nun geht ist gut. Wenn es wieder auftritt, genau so nochmal reporten. Eventuell kommen wir dem ganzen auf die Schliche ;)
Closed. #3536
