### ISSUE TITLE
Terra Dos T4-40 doesn't turn after end of row

### ISSUE THREAD

**Issue by mxalbert** [Courseplay/courseplay#3538]
Since v166 the Terra Dos T4-40 doen't make the turn after the end of a row. It worked fine with v165. Now the combine drives of in a huge circle (Diameter like at least 100m), without a chance to find the next row like this.

I also tried a normal combine, with the same result.

**Comment by Tensuko** [comment]
![fsScreen_2019_04_07_17_00_56](https://user-images.githubusercontent.com/27344744/55685453-c04f6900-5956-11e9-864f-58614b32a3ef.png)
![fsScreen_2019_04_07_17_01_04](https://user-images.githubusercontent.com/27344744/55685454-c04f6900-5956-11e9-8bef-af74383208b9.png)

For me it does. Try recreate the course.

**Comment by Tensuko** [comment]
![fsScreen_2019_04_07_17_06_02](https://user-images.githubusercontent.com/27344744/55685526-7e72f280-5957-11e9-8f66-dc0258de20e5.png)
![fsScreen_2019_04_07_17_06_16](https://user-images.githubusercontent.com/27344744/55685527-7f0b8900-5957-11e9-9aed-7ff5dfa4fa5e.png)

This one seems broken tho....
Going to try more.

**Comment by pops64** [comment]
Yeah picutre with debug 12 and 14 or a video would be better with same channels. I know there is a bug yet to be reported that when combine is unload on fruit side it resets the waypoint back to 1 at field edge which causes weird behavior but I have yet to properly document it. So I haven't reported it yet

**Comment by Tensuko** [comment]
There is nothing to be unloaded yet. Also the normale Combine does its job fine while tested the Terra Dos.
![fsScreen_2019_04_07_17_07_13](https://user-images.githubusercontent.com/27344744/55685553-f3462c80-5957-11e9-9f59-75ad379fc5c6.png)
![fsScreen_2019_04_07_17_08_19](https://user-images.githubusercontent.com/27344744/55685554-f3462c80-5957-11e9-930d-e2a2e8f7feb0.png)
logfile with 9 and 14 and 12 more at the end
[log.txt](https://github.com/Courseplay/courseplay/files/3051651/log.txt)
![fsScreen_2019_04_07_17_11_05](https://user-images.githubusercontent.com/27344744/55685581-56d05a00-5958-11e9-9c5a-d2437b5b714c.png)
![fsScreen_2019_04_07_17_11_08](https://user-images.githubusercontent.com/27344744/55685582-56d05a00-5958-11e9-91a9-712f92043f67.png)
![fsScreen_2019_04_07_17_11_20](https://user-images.githubusercontent.com/27344744/55685583-56d05a00-5958-11e9-9bba-32170f491ac9.png)

**Comment by pops64** [comment]
You have two different pictures of the turn generated. Are they the same? The 2nd looks like it would fail. The combine rootNode is after the turn. The other should have been fine. And we can confirm that with v165 that this bug doesn't occur?

**Comment by Tensuko** [comment]
Last 3 pics are all shot in a row.
Position near end and about to generate turn.
Generated Turn and moves along.
Ignore the generated turn and moves somewhere.

I go test the same with 165, give me a minute pls.

**Comment by pops64** [comment]
No it is defiantly my push. For what ever reason it is not using enough steering angle would be my guess

**Comment by pops64** [comment]
Sorry for spam. I am bout to leave for a few hours. Could you test it with a regular course in mode 5 with as sharp a turn as possible. I think I know what the problem is just want to check

**Comment by Tensuko** [comment]
Well with 165 it does the turn, not rly good, but it takes at least the calculated one.
I would guess, the problem is the differen steering types ? As it seems to have problem with the generated turn too. https://1drv.ms/f/s!ArGbP_j369r8kA8Dv8dWTZOvQaXo
[log.txt](https://github.com/Courseplay/courseplay/files/3051695/log.txt)

**Comment by pvaiko** [comment]
This one has crab steering, see what I wrote in https://github.com/Courseplay/courseplay/issues/3062#issuecomment-475921477 :
> CP does not force anything, it uses what the standard Giants CrabSteering:onAIImplementStart() returns, which is the all wheel steering by default.
> 
> We won't change this. We probably need to check our math when driving four wheel steering vehicles but we don't directly control the steering angle so I don't think there's a problem there.
> 
> If you want front wheel steering then you can add the aiSteeringModeIndex attribute to the vehicle's crabSteering setting in the XML:
> 
> `<crabSteering aiSteeringModeIndex="2">`

**Comment by Tensuko** [comment]
Is it possible to block CP using the different steering for the Terra Dos ? Like use the 1st one when you get it from the shop ? That is all WheelSteering I think. The TurnSteering, CP seems to hate that, as you can see when you try to let it drive backwars in that steering mode.
When use all Wheel Steering (standart one) it does its job great.

**Comment by Tensuko** [comment]
![crap](https://user-images.githubusercontent.com/27344744/55686363-a155d480-5960-11e9-9658-c59f468e7769.png)
![good](https://user-images.githubusercontent.com/27344744/55686364-a155d480-5960-11e9-840c-e58f1af359a7.png)

**Comment by pvaiko** [comment]
That's what I'm saying, the way to tell CP which steering mode to use is to add the <crabSteering aiSteeringModeIndex="2"> to the XML, that's what it was provided for by Giants.

**Comment by pvaiko** [comment]
Of course, the number in aiSteeringModeIndex could be different depending on the tool, whichever works best.

**Comment by pvaiko** [comment]
For this specific vehicle you could try changing the line from
`    <crabSteering distFromCompJointToCenterOfBackWheels="6.3695" aiSteeringModeIndex="2" toggleSpeedFactor="0.1" >
`
to 
`    <crabSteering distFromCompJointToCenterOfBackWheels="6.3695" aiSteeringModeIndex="1" toggleSpeedFactor="0.1" >
`
in the XML and see if it helps

**Comment by Tensuko** [comment]
It is not only this Vehicle...
V165:
![fsScreen_2019_04_07_18_55_17](https://user-images.githubusercontent.com/27344744/55686862-bd5c7480-5966-11e9-911e-9e2ef2426b6a.png)
V166:
![fsScreen_2019_04_07_18_50_53](https://user-images.githubusercontent.com/27344744/55686864-c2b9bf00-5966-11e9-8bbe-8c962d4edc32.png)

Both did Reverse fine, when about to do the generated turn, in V166 it runs away.
Got to do with the Knicklenkung (articulated-frame steering ?) in both Vehicles I would say.

**Comment by pops64** [comment]
No it has to do with the steering angle calc still. I think it is the bendy vehicles that are causing the issue. The terra dos returns an steering angle limit of 1718 degrees or so. But in driveInDirection function how hard it turns is done via this calc. maxium possible rotation times  angle/steeringAngleLimit, This returns a number very close to zero preventing it from using its maximum rotation. I am currently trying to figure out how driveToPoint avoids this issue. This is why you don't have a problem with mode5 or 165 and eailer. Why I deleted my comment sorry.

**Comment by pops64** [comment]
Try replacing turn with this file and report back thanks 
[turn.zip](https://github.com/Courseplay/courseplay/files/3051965/turn.zip)

**Comment by pops64** [comment]
Try replacing base with 
[base.zip](https://github.com/Courseplay/courseplay/files/3051982/base.zip) Thanks are report sorry for the double post

**Comment by pvaiko** [comment]
One of the problems here is that vehicles with ArticulatedAxis specialization have the vehicle.maxRotation value in degrees instead of radians due to a Giants bug.

**Comment by pvaiko** [comment]
This has been confirmed by Giants as a bug. Added a workaround. Won't at the moment have any effect, other than probably the Giants helper will work better with articulated axis vehicles.
