### ISSUE TITLE
LUA:Error beim speichern MAN IT Runner Modhub

### ISSUE THREAD

**Issue by Gram90** [Courseplay/courseplay#3539]
Moin

Sobald ich mir den Miststreuer vom ITR und den MAN Hakenlift auf dem Modhub kaufe wirft er mir einen Error. Siehe Log. Er bleibt dann beim Speichern hängen und der Spielstand muss über ein Backup wiederherstellt werden.

Kann dies jemand reproduzieren?

Dankeschön
[log.txt](https://github.com/Courseplay/courseplay/files/3051841/log.txt)

**Comment by Tensuko** [comment]
Man kann davon ausgehen, wenn die meisten anderen Fahrzeuge funktionieren, aber der MAN Hakenlift LKW nicht läuft, ist dieser Fehlerhaft.
#3479
Aber ich habe ihn eben gekauft, kein Fehler gekrigt... Muss eine weitere Mod sein, die auch noch mit reinspielt.
![fsScreen_2019_04_07_19_24_27](https://user-images.githubusercontent.com/27344744/55687228-fd255b00-596a-11e9-8e91-aed67b68e4bb.png)

**Comment by Gram90** [comment]
Moin

Wenn ich nur CP und den MAN drin habe, tritt der Fehler auf sobald ich speichere
[log.txt](https://github.com/Courseplay/courseplay/files/3051951/log.txt)

**Comment by Gram90** [comment]
> Man kann davon ausgehen, wenn die meisten anderen Fahrzeuge funktionieren, aber der MAN Hakenlift LKW nicht läuft, ist dieser Fehlerhaft.
> #3479
> Aber ich habe ihn eben gekauft, kein Fehler gekrigt... Muss eine weitere Mod sein, die auch noch mit reinspielt.
> ![fsScreen_2019_04_07_19_24_27](https://user-images.githubusercontent.com/27344744/55687228-fd255b00-596a-11e9-8e91-aed67b68e4bb.png)

Has du auch gespeichert?

**Comment by Tensuko** [comment]
Hm ja das hat was mit dem speichern zu tun.
Aber das muss trotzdem an dem MAN liegen.
Man sieht in der Log aber sehr schön, was alles schief geht.
An der Stelle von CP, werden halt Einstellungen, die du in CP für dein Fahrzeug gemacht hast abgespeichert. Da der MAN kein CP HUD hat, kann da auch nichts gespeichert werden.

**Comment by Gram90** [comment]
Ja, liegt am MAN. Ich habe diesen jetzt erstmal rausgeworfen.

danke für eure Hilfe
