### ISSUE TITLE
Turning on field not working with several tools

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/courseplay#3540]
I noticed that Turning on field is not working with some tools. They can reverse, but they don´t do it. Only in case of sharp headland corners they drive backwards. I tried it with and without mods. But it does not work. Log without any debugs has no errors or warnings in it

List of the tools which do not turn on field: (maybe it is incomplete)
- Agriesem Cultiplow 8 Meter
- Grimme SE260 Potato harvester
- All wheeled plows
- Great Plains seeding machine

**Comment by Tensuko** [comment]
No matter what you post, we need a logfile anyway.
Just drag and drop it into the commentbox, thx.

**Comment by pops64** [comment]
#3538

**Comment by StefanBraun2001** [comment]
Okay, here is the log without mods and on felsbrunn. I tested it with all machines that are on my list (Cultiplow, Seeding Potato for Grimme SE260, Plow, Great Plains Seeding Machine). Turning on field is on of course. For some reason some lua callstacks has been occured i don´t know why
[log.txt](https://github.com/Courseplay/courseplay/files/3051981/log.txt)

**Comment by Tensuko** [comment]
Try go back to Version 165 if the LUA still happens and if you face the same issues.
https://github.com/Courseplay/courseplay/releases/tag/6.01.00165

**Comment by pops64** [comment]
This is related to #3538 and not standard tractor or combine(AKA articulated, zero turn, crab steering etc.) Is broken in 166

**Comment by pvaiko** [comment]
Those lua callstacks are harmless and not related to the problem

**Comment by StefanBraun2001** [comment]
This Problem occurs longer. i reported it by now

**Comment by Tensuko** [comment]
He got the same LUA Callstacks in logfile as in #3541
Closing this 1st.
Turn on Field yes/no I take a look into later, or wait for HUD Refactoring.
Closed #3540
