### ISSUE TITLE
Reverse Fail with some tools - LUA Callstack in Logfile

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/courseplay#3541]
Hello!

Some tools fail to drive reverse. When driving backwards he driver steers with a wheeled vehicle, the result is that Trailer and Tractor becoming wedeged. This happens with all of the Kuhn Windrowers (Merge Max and GA become wedged when driving backwards after turning (He steers more and more, and the windrower become wedged) WIth the ROPA Keiler 2 it is similar. It drives backwards after reaching field end (sometimes sucessfull, sometimes he become wedged) Then driving backwards to field end, he is become wedged everytime. I think the steered wheel of the tools could be the prblem (The KUHN Sr14 has no steered wheel, i belive courseplay think that this windrower is a not wheeled tool. log has no warning or errors without debugs

**Comment by Tensuko** [comment]
No matter what you post, we need a logfile anyway.
Just drag and drop it into the commentbox, thx.

**Comment by pops64** [comment]
#3538

**Comment by StefanBraun2001** [comment]
For the windrowers (except the SR314) The commit with turn maneuver tuning has done something. Now sometimes the turning maneuver is going good, sometimes windrower and tractor becoming wedged when reversing to field end. The SR314 does still not work and become wedged during reversing. Log is posted here. ROPA Keiler 2 is not working. When driving back to field end he becomes wedged
[log.txt](https://github.com/Courseplay/courseplay/files/3052120/log.txt)

**Comment by Tensuko** [comment]
Go back to V165 and try again.
If that is the same, we got to take a look into this.

**Comment by StefanBraun2001** [comment]
Tried again with V165, same issue, LUA Callstacks are gone. I have to say that this reverse problem exists longer, i only reported it now. 
[log.txt](https://github.com/Courseplay/courseplay/files/3054216/log.txt)

**Comment by Tensuko** [comment]
Thats ok, I would have closed it, if it wouldn't get so messy with LUA and V166 issue.
I got that on my list and we take a look into that. Thx anyway :)
