### ISSUE TITLE
Reversing with trailer does not stop at same point as recording

### ISSUE THREAD

**Issue by asyvan** [Courseplay/courseplay#3542]
When reversing with trailer, CP records the reverse stop point in relation to tractor rear end. But the playback stops when rear end of trailer (not the tractor) is at end-point of the recorded reverse.  This leads to the trailer not being reversed as long as the recording. 

See the following video for example, debug 12 and 14 turned on.
https://youtu.be/f__WlwmGOFI

**Comment by Tensuko** [comment]
You doing it wrong.
Reverse driving always without Trailer!
Get it straight, pause the record, put trailer aside.
Get back to the last waypoint, continue and start reverse untill you reach your target.
Then undo reverse mode, and drive where you want to be.

That have to be like that, becouse CP drives the Tractor in the way, that the trailer stays on the waypoints in reverse mode. Imagine you record a Course with a rotating stool....
Your Course would go left right left right and when CP drives it, he tries to put the trailer on that path... impossible.

(sry, its german Tutorial): https://youtu.be/PMYgtdyQWJM?t=607


Closed. #3542
