### ISSUE TITLE
Callstack Mode 2

### ISSUE THREAD

**Issue by hoefti10** [Courseplay/courseplay#3543]
Hi folks,
I had since the Version .166 the problem that when iam starting Mode2 i get allready a Callstack
Try it with some difference tractors.
[log.txt](https://github.com/Courseplay/courseplay/files/3051922/log.txt)
Maybe someone had a tip :-) thanks.

**Comment by Tensuko** [comment]
Go back to .165
Also old Mode2 is not supported #3311 
Can you tell me exactly what tools you used in Mode2 ?

**Comment by hoefti10** [comment]
Fendt 511 C and a vanilla Loader.
But i'll guess the problem was the 
front-end loader.
Without an attached gadget it works fine :-)
