### ISSUE TITLE
suggestion: keycommand for COURSEPLAY_REQUEST_UNLOADING_DRIVER

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#3545]
Hello Guys.
is it possible to add a key command für "Abfahrer rufen"?
from Translation_de.xml:
`		<text name="COURSEPLAY_REQUEST_UNLOADING_DRIVER" 					text="Abfahrer rufen" />`

lg
andreas

**Comment by ThomasGaertner** [comment]
#3085
