### ISSUE TITLE
some unusual coursegeneration?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#3547]
Hey Guys,
i changed fieldsize Felsbrunn Field13, and generate a new Harvester course,
i see unusual course generation:
the course beginns in the "2.row", the 1Turn is to the outside Fieldborder,
here are pics:
![fsScreen_2019_04_08_13_42_38](https://user-images.githubusercontent.com/24860501/55722027-4924de00-5a05-11e9-9183-3ee5285db650.png)
![fsScreen_2019_04_08_13_42_19](https://user-images.githubusercontent.com/24860501/55722029-4aeea180-5a05-11e9-8b45-a76b6b79e1f1.png)

and field13 from courseplayCustomFields.xml:
[Neues Textdokument.txt](https://github.com/Courseplay/courseplay/files/3054120/Neues.Textdokument.txt)

whats wrong?
edit:
the wide of the field is167,7m (z coordinates -135,10 and 32,60)
divide through 12m are 13,975rows
also cp calculate one row to much, and also on the false side.

lg
andreas

**Comment by Tensuko** [comment]
You got any disadvantage of it ? I would just suggest to reduce the work with by 0.1 or 0.2m to get a better result, as you won't loose any time, couse you will have one extra lane anyway, wich is even less use as you see...

**Comment by andreasthu** [comment]
I know.
I try to make my fields nearby at a wide divide through 12.
(Combine ideal 12m, rsm161 9m, kuhn fertilizer 24m, seeder 9m and 6m, ..)
That means with a fieldwide with 168m there are 14 rows with 12m wide.
This field13 is 167,7m wide and cp should calculate 14 rows, 13 with 12m and one with 11.7m.
But cp calculate 15 rows, the first error.
Then beginn the cp course in the 2nd row, first turn go to 1st row, second turn go to 3rd row, this is also a error. 3rd, 4th, 5th row are ok.
The course should beginn in the first row, not the second, and why calculate cp to much rows?
This are the suspect thinks.
I can work with them, no question, i will only report a issue.
Lg
Andreas

**Comment by Biker23** [comment]
I get this as well and it is really annoying if you use more than one machine. would not be such a problem if it did this at the end of the course when you have to check on them anyway.

**Comment by pvaiko** [comment]
1. It will be either at the start or at the end of the course, depending on many factors, especially the starting position, headland setting, angle of field. We'll not change that.
2. I can probably fix the turn directions if that really is a problem
3. Depending on the field geometry and the implement width there'll always be cases where end up with a narrow band of fruit. Looking at the issues here (e.g. #2571) there seem to be no consensus what should happen in that case:
- current behavior, that is, one narrow row either at the end or the beginning
- two narrow rows, one at the beginning, one at the end
- all rows spaced equally so the rows will overlap
- or a combination of the above, maybe automatically selected based on the number of rows and width?

In any case, this is not something I'll change in the near future.

**Comment by andreasthu** [comment]
hell @pvaiko 

1. i understand, but it is a really easy course,
the field is rectangle, 90degree east to west, really straight borderlines, no curves,... no headlands, ...

2. no, the turn direction is not the problem, the row 1 is only to much, completely senseless
all was the combine make, is also covered with row 2 and row3
when there was no row1, the field is covered with row 2 - 15

3. i see #2571, but i think it is not the same.
when in #2571 covered the 2nd row 50% from the workwide from the sowing machine.
when there was no row2, them 4,5m (i think Horsch 9m machine) were not be sowing on this field

i also attach here the field13 border and field13 fieldwork
[Field13_border.txt](https://github.com/Courseplay/courseplay/files/3072013/Field13_border.txt)
[courseStorage0090.xml.txt](https://github.com/Courseplay/courseplay/files/3072015/courseStorage0090.xml.txt)
so you can calculate this by yourself.

here also a ingame picture:
![fsScreen_2019_04_12_08_26_36](https://user-images.githubusercontent.com/24860501/56019082-0e23f280-5d04-11e9-92ad-3a89846f90f6.png)
you see, when the dresher beginns not at first waypoint, rather but he beginns at the first waypoint from row2, the hole field was covered, row1 is not needed to cover the whole field

here is also a pic from the coursegenerator, with coordinates from the coursestorage90.xml and the field13 coordinates:
![fsScreen_2019_04_12_08_27_07](https://user-images.githubusercontent.com/24860501/56019271-7c68b500-5d04-11e9-85b8-e493d78b5392.png)
here you see the same, with calculated wides from me.
the fieldwide is 167,7m, the combine needs 14 rows x 12m, the covered workwide is then 168,0m
 also 0,3m more than needet.

lg
andreas

**Comment by andreasthu** [comment]
Thanks,
works perfect with v6.01.0187
![fsScreen_2019_04_12_08_27_07](https://user-images.githubusercontent.com/24860501/56091992-abbf2380-5eb6-11e9-84ed-8a62c0e8a4f8.png)
![fsScreen_2019_04_14_12_54_31](https://user-images.githubusercontent.com/24860501/56091993-ad88e700-5eb6-11e9-8640-44fb68ed4153.png)

lg
andreas
