### ISSUE TITLE
Work tool needs to be refilled 

### ISSUE THREAD

**Issue by kartal2339** [Courseplay/courseplay#3548]
hi.. when i want to fertilize my field with a kuhn fertilizer ...it gives this error and doesnt start...but my tank is full and i create the work path correctly

**Comment by Tensuko** [comment]
Did you use Mode4 ?
Logfile pls.
And screenshot.

**Comment by kartal2339** [comment]
![IMG_20190408_003508](https://user-images.githubusercontent.com/33800597/55783683-a1b4b380-5ab7-11e9-93af-b8ab9128e598.jpg)

its same for all fertilizer or herbisid machine

**Comment by Tensuko** [comment]
Press the 'print' key on your keyboard, you screenshots are found in ...My Games\FarmingSimulator2019\screenshots
for the logfile, fallow this:
https://github.com/Courseplay/courseplay/wiki
just drag and drop it into the comment box

**Comment by kartal2339** [comment]
i solved also this problem for deleting jd 8r v2.0 ..thanks for your help

**Comment by Tensuko** [comment]
Closed.
