### ISSUE TITLE
Why is this always a problem to show in game mods list

### ISSUE THREAD

**Issue by Hubcap-1** [Courseplay/courseplay#3549]
I just don't get it. I have been using cp since the beta released. But at no time when i update the version could i just put the zip file into my mods folder and have it show up in the selectable mods list in game. I have always had to rename it ( deleting master from the title). Now that doesn't even work.....what is the issue.

**Comment by Tensuko** [comment]
Just download the finished zip here.
You will have to throw out the old one when load a new or rename it like you want e.g. FS19_Courseplay or FS19_Courseplay6 or whatever. Closed #3549
