### ISSUE TITLE
Rational use of space on HUD

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Courseplay/courseplay#3553]
![fsScreen_2019_04_09_19_07_30](https://user-images.githubusercontent.com/8200153/55818351-13fcb680-5aff-11e9-94cc-e2234422efe2.png)
![fsScreen_2019_04_09_19_14_05](https://user-images.githubusercontent.com/8200153/55818352-14954d00-5aff-11e9-911d-e273c05fc3a9.png)
There are pages on which a lot of empty space. But often there is not enough space for text in other languages.
If now began to improve the view, maybe this problem also solve?

**Comment by ThomasGaertner** [comment]
test with v.175 or higher and report

**Comment by Gonimy-Vetrom** [comment]
Now everything is fine. Thank.
