### ISSUE TITLE
zu abtankenden Drescher auswählen geht nicht mit der version 6.01.00168

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#3555]
Hallo CP team. ich kann mit der version 6.01.00168 keinen drescher mehr auswählen wo abgetankt werden soll:
![fsScreen_2019_04_09_18_56_51](https://user-images.githubusercontent.com/3021040/55819554-528f7280-5af9-11e9-86d9-11940f33e640.png)

aber das automatische suchen bei den feldern geht:
![fsScreen_2019_04_09_18_57_05](https://user-images.githubusercontent.com/3021040/55819581-62a75200-5af9-11e9-92a2-9daaa138edf8.png)

MFG Mannie313

**Comment by Mannie313** [comment]
Habe noch ein problem gefunden. Ich kann wen ich nen Ordner Hof erstellt habe und dann nen Ordner Mit abfahrer in den ordner Hof einfüge den ordner abfahrer nicht öffnen.

MFG Mannie313

**Comment by ThomasGaertner** [comment]
test 169 and report bitte nur ein problem pro issue

**Comment by Mannie313** [comment]
Ok mache ein neues Thema auf wegen dem 2ten fehler.
Aber jetzt kann ich wieder die drescher selber auswählen. Danke

MFG Mannie313
