### ISSUE TITLE
Kuhn Axis Düngerstreuer wird abgesenkt

### ISSUE THREAD

**Issue by Steve0068** [Courseplay/courseplay#3556]
Hi CP-Team,

bei einem generierten Düngerkurs, wird der Düngerstreuer, hinten an der Hydrauklik vom Traktor, beim Düngen abgesenkt. Je nach Bodenunebenheiten, behindert das den Traktor beim Fahren. Das war bei früheren Versionen von CP nicht der Fall. Leider kann ich nicht sagen, ab welcher Version das auftrat.

LG
Steve

**Comment by iljarogoff** [comment]
Kann ich nicht bestätigen. Allerdings schaltet CP den Düngerstreuer viel zu früh ein und entsprechend am Feldende viel zu früh aus, so dass immer unschöne ungedüngte Flecken entstehen. Habe versucht, dies über den Gerät-Versatz auszugleichen, aber das hat keinerlei Auswirkung.

**Comment by Tensuko** [comment]
Ich mach den hier mal zu, fals sowas wieder auftritt, bitte bescheid geben, dann machen wir den wieder auf.
Screenshot wo man sieht wann er den Streuer absenkt wäre gut.

Closed.
