### ISSUE TITLE
LUA method 'draw' - hud.lua:465: attempt to index a nil value - V168

### ISSUE THREAD

**Issue by Racker2409** [Courseplay/courseplay#3557]
When I open the HUD and want to generate a course I have Error

[log.txt](https://github.com/Courseplay/courseplay/files/3060157/log.txt)

**Comment by Tensuko** [comment]
Logfile with debug 18 pls.

**Comment by ThomasGaertner** [comment]
try again with v.170

**Comment by Racker2409** [comment]
I'm sorry. Translator

I'll test it, and report back

**Comment by ThomasGaertner** [comment]
test with v.174 or higher

**Comment by Racker2409** [comment]
I don't have any mistakes at the moment. If there's anything wrong, I'll get back to you.

Many thanks for your help
