### ISSUE TITLE
Mähdrescher hinterlässt Flecken beim Wenden am Feldende

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#3558]
s. Titel und Bild :)
![fsScreen_2019_04_09_19_27_58](https://user-images.githubusercontent.com/21023840/55821478-eb27f180-5afd-11e9-9850-eb273c7f290d.png)

**Comment by Tensuko** [comment]
Sind dran...

**Comment by iljarogoff** [comment]
Danke 👍

**Comment by iljarogoff** [comment]
.0180 still same problem with combine
![fsScreen_2019_04_11_18_53_34](https://user-images.githubusercontent.com/21023840/55976138-bf3a7680-5c8b-11e9-9d55-ea695df52cc8.png)

**Comment by pvaiko** [comment]
Duplicate of #3742
