### ISSUE TITLE
No working mode for ingame Rubicon 9000

### ISSUE THREAD

**Issue by Raints** [Courseplay/courseplay#3559]
![Untitled](https://user-images.githubusercontent.com/3618060/55822138-9a1cfb00-5b07-11e9-9287-79ee95b54dff.png)

**Comment by Tensuko** [comment]
Logfile with debug 18 pls.

**Comment by Raints** [comment]
With version 172 I can choose work mode again. Thanks!

**Comment by alfchristian** [comment]
Now you can not set course on any other vehicles
