### ISSUE TITLE
Combines reset to waypoint 1.

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#3561]
I have only seen this occur when combine has stopped at field edge with the fruit under the pipe. After the tractor leaves it will reset to waypoint one causing random behavior.  This occurs after the turn if it unloads during the turn. And before the turn if it unloads before the turn has started. Two differnt combines both had this issue not combine related. Both were contract missions and both had no headlands just standard updown course  [Log](https://pastebin.com/vGnecZj0) Sorry if it has been reported. Look through the English issues didn't seem to show anything

**Comment by Tensuko** [comment]
Got a lot of changes since that varsion, so closing this 1st.
