### ISSUE TITLE
LUA method 'mouseEvent' - settings.lua:1151: attempt to index field 'orderButton' (a nil value) - V168

### ISSUE THREAD

**Issue by Datalund** [Courseplay/courseplay#3562]
Testing out the new layout on the hub and got some LUA error:

2019-04-09 18:21 Error: Running LUA method 'mouseEvent'.
2019-04-09 18:21 C:/Users/Datalund/Desktop/FS mapbuilding/FS19_Courseplay/settings.lua:1151: attempt to index field 'orderButton' (a nil value)

The test was done on a new save game with only Courseplay and the map loaded as mods.

Logfil can be found here:
https://gist.github.com/Datalund/60055f215233e9da85ece88c61be7068

**Comment by Tensuko** [comment]
What is this path ? 2019-04-09 18:21 Error: Running LUA method 'mouseEvent'.
2019-04-09 18:21 C:/Users/Datalund/Desktop/FS mapbuilding/FS19_Courseplay/settings.lua:1151: attempt to index field 'orderButton' (a nil value)

Need a logfile with debug 18 pls.

**Comment by Datalund** [comment]
I've just changed the mod directory in gameSettings.xml to have a test environment. Very useful for map making, and it doesn't affect how the game works. If needed I can change back to standard settings.

A log with debug 18 coming up soon :)

**Comment by Datalund** [comment]
Did a new test. Again with a new savegame and only the map and Courseplay as active mods.
Eneabled debug 18 and same error.

To create the error, I am trying out different options in the advanced course generator. Changing direction of the headlands and so on, and this time the game froze and I had to use Alt+F4

Logfile with debug 18:
https://gist.github.com/Datalund/ee40f676e51596580b6f016d271abda9

**Comment by Tensuko** [comment]
Thank you for discribing, we going to take a look into this!

**Comment by ThomasGaertner** [comment]
try again with v.170

**Comment by Tensuko** [comment]
Fixed. Closed.
