### ISSUE TITLE
Kann keine Unterordner im Hud Öffnen

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#3563]
Ich kann wen ich nen Ordner Hof erstellt habe und dann nen Ordner Mit abfahrer in den ordner Hof einfüge den ordner abfahrer nicht öffnen.

MFG Mannie313

**Comment by Tensuko** [comment]
Kann ich so nicht bestätigen.
Bitte einmal ein Logfile mit Debugchannel 18 reinstellen.
