### ISSUE TITLE
LUA method 'draw' - hud.lua:736: attempt to index a nil value

### ISSUE THREAD

**Issue by zed636** [Courseplay/courseplay#3566]
Hello Devs

Game Version: 1.3.0.1 b4009
CP version: 6.01.00172
Time of event: 2019-04-10 01:38
Map: Ravenport
No mod installed
[log.txt](https://github.com/Courseplay/courseplay/files/3061365/log.txt)

When you enter in page COURSEPLAY_PAGE_TITLE_COMBI_MODE with a seeder connected, the following error message appears:
2019-04-10 01:38 Error: Running LUA method 'draw'.
2019-04-10 01:38 C:/Users/zed63/Documents/My Games/FarmingSimulator2019/mods/FS19_courseplay6/hud.lua:736: attempt to index a nil value
![fsScreen_2019_04_10_01_38_18](https://user-images.githubusercontent.com/19471664/55842170-9a7ebb80-5b32-11e9-9f0b-4ab51be58afc.png)
when disconnecting the tool the hud reappears
![fsScreen_2019_04_10_01_38_36](https://user-images.githubusercontent.com/19471664/55842172-9a7ebb80-5b32-11e9-8b9f-2ef38ebbce7d.png)
regards
Marco

**Comment by ThomasGaertner** [comment]
test with v.174 or higher

**Comment by zed636** [comment]
it works well
thanks
