### ISSUE TITLE
Can't use Course Generation with recent HUD updates.

### ISSUE THREAD

**Issue by abcderic73** [Courseplay/courseplay#3567]
![20190409230210_1](https://user-images.githubusercontent.com/47501264/55848640-94c9ab80-5b1b-11e9-8097-6f2770205b4e.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/3061796/log.txt)

HUD also shows "No Course Selected" text when you close the HUD.

Can not create any course with any tool now.

**Comment by Martinnygaard** [comment]
![cp](https://user-images.githubusercontent.com/26490587/55851002-2f93ab80-5b57-11e9-8e59-9a7bae96222d.png)
So, in the new update, the coursegenerator is located under the "main menu" as shown in my screenshot.

Also you need to be in one of the modes i have marked for the option to show. (transport mode will hide the courseplay generator button)

At last, then a tractor need a cirtain implement within the mode you want to activete before you are even able to choose the mode. In the picture i have a cultivator, so i can select fieldwork mode.

**Comment by Tensuko** [comment]
#3552 
Closed.

**Comment by pvaiko** [comment]
@Martinnygaard thanks for the explanation
