### ISSUE TITLE
Mode 6 is missing for loader wagon

### ISSUE THREAD

**Issue by Williwillswisse** [Courseplay/courseplay#3568]
Mode 6 is missing for loader wagon

![K1600_Pic](https://user-images.githubusercontent.com/47098121/55855770-b1400500-5b68-11e9-87bf-fbaa1fcedfc4.JPG)

**Comment by ThisPf** [comment]
I had that at the first moment with the sowing machine too. Detach and attach again helped.

**Comment by Williwillswisse** [comment]
Thanks for the hint, but that does not work.

**Comment by ThomasGaertner** [comment]
test with v.174 or higher

**Comment by Williwillswisse** [comment]
Now it works. Thanks a lot for your hard work on this beautiful Mod.

**Comment by Tensuko** [comment]
Closed.
