### ISSUE TITLE
MultiMap LS19 freeze

### ISSUE THREAD

**Issue by turbodani** [Courseplay/courseplay#3569]
Ab der 163 und mit aktiviertem CP spinnt das komplette Spiel auf der MultiMap in LS19. Spielstände werden nicht gespeichert und das Spiel hängt sich kurz nach Speicherversuch auf ohne Speicherung. Version 162 funktioniert tadellos.

**Comment by Tensuko** [comment]
1) Neueste Version laden (aktuell 172)
2) logfile ( https://github.com/Courseplay/courseplay/wiki )
3) welche Map genau ?

**Comment by turbodani** [comment]
Werde ich später machen mit der 172. Habe bis 168 getestet, fängt ab der 163 an, wie gesagt. Log hänge ich an, sobald ich zuhause bin.

MultiMap LS19.

**Comment by Tensuko** [comment]
Geschwindigkeit im Fahrsilo, funktioniert nur in Mode6, da Mode2 noch neu geschrieben wird und die Berechnung dort noch nicht drin ist.

**Comment by turbodani** [comment]
Ok, mit der 175 ist wieder alles super und im Mode2 funktioniert auch die Geschwindigkeitsanpassung.. :)

**Comment by Tensuko** [comment]
ok, dann kann das ja zu.
Closed.
