### ISSUE TITLE
Schriftzug trotz ausgeblendetem CP HUD

### ISSUE THREAD

**Issue by Willi-77** [Courseplay/courseplay#3570]
hallo hab die neuste Version 6.01.00172 aufgespielt und wollt mal fragen ob das gewollt ist auch wenn das CP Hud ausgeblendet, das trotzdem schriftzug angezeigt bleibt ob ein Kurs geladen ist oder "kein Kurs geladen"!!

Steht bei mir bei allen Fahrzeugen da war in der Version 6.01.00167 nicht die hatte ich zu letzt.

mfg

**Comment by Tensuko** [comment]
#3552 Closed.

**Comment by Willi-77** [comment]
ist in der Version 6.01.00173 leider immer noch genauso??
