### ISSUE TITLE
Hud Disappears

### ISSUE THREAD

**Issue by sesmo** [Courseplay/courseplay#3572]
The HUD disapears when I click on " Vehicle Specific Settings "

The video with the bug is here: https://youtu.be/1xwe0wT1zUw

Another question: What happend with fertilizer optional?

Thank´s.

**Comment by Tensuko** [comment]
Logfile with debugchannel 18 on and do the same again pls.
Thank you.

**Comment by ThomasGaertner** [comment]
test with v.174 or higher

**Comment by sesmo** [comment]
Work´s.... thank´s

Case closed...!!!!!!!!!

**Comment by Peppobrasil** [comment]
Version 201
Sometimes, clicking “start route”, the HUD disappear.
It happens with only one tractor and is not always the same.
The HUD exists and is under the game window.
If I click in the right place to stop the route, the HUD reappear.
The help and speed dashboard also disappears with the HUD.
How can I help you fix the bug?

**Comment by Tensuko** [comment]
Logfile ?

**Comment by Peppobrasil** [comment]
Channe 18?

**Comment by Tensuko** [comment]
Might help

**Comment by Peppobrasil** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3133933/log.txt)

**Comment by maartenpeels** [comment]
I have this same problem, in the newest beta version(v6.01.00360).
