### ISSUE TITLE
Schrift vom Hud trotz ausgeblendetem

### ISSUE THREAD

**Issue by Willi-77** [Courseplay/courseplay#3575]
das problem aus Version 6.01.00172 ist leider immer noch das trotz geschlossenem CP Hud immer noch die Schriftzeile da bleibt das entweder "kein Kurs geladen ist" oder der jeweilig geladene Kurs angezeigt wird.

Weiß nicht ob das gewollt ist der ein Bug ist. bei version  6.01.00173 war die noch nicht.

**Comment by Tensuko** [comment]
Lese doch mal den Beitrag ?! #3552 Closed.
Einstellungen: Mini-HUD ausschalten!
