### ISSUE TITLE
Man kann immer noch keine Unterordner im HUD öffnen

### ISSUE THREAD

**Issue by Hartmut88** [Courseplay/courseplay#3576]
Leider kann man seit den letzten (ich glaube 10 Versionen) keine Unterordner mehr öffnen. Der erste und auch der zweite Unterordner geht zu öffnen.. danach leider nicht mehr. Da meine Kurse alle in mehreren Unterordnern liegen, kann ich keine Kurse mehr laden.

Folgendermaßen ist es bei mir aufgebaut:

Feld XX  >>>
                      Arbeitskurse  >>>
                                                     Drillen   >>>      usw.

Vielleicht könnt ihr das bald fixen???

**Comment by ThomasGaertner** [comment]
wie viel Unterordner soll ich einrichten ? das Problem ist , dass dadurch die mouse area kleiner wird und dann hab ich issues dass man nicht mehr scrollen kann.. welchen Wert soll ich annehmen ?

**Comment by Hartmut88** [comment]
Na also ich brauch min. 3 Unterordner... aber 4 - 5 wäre natürlich schöner, man weiß ja nie, was noch so kommt. 
Unterordner braucht man ja um es einigermaßen übersichtlich zu halten.

**Comment by Hartmut88** [comment]
Wenn nicht könnte man doch das CP HUD einfach breiter machen, damit es mit den mouse area´s keine Probleme gibt oder?

**Comment by ThomasGaertner** [comment]
probier mit v.176 sollte gefixt sein ohne Limit

**Comment by Hartmut88** [comment]
Ja geht :-) Danke dir für deine schnelle Hilfe. Schönen Abend noch!
