### ISSUE TITLE
Tractor cant keep trailer straight while going backwards

### ISSUE THREAD

**Issue by Crytiv** [Courseplay/courseplay#3577]
Video captured with 9, 13, 14 debug channels on.
https://youtu.be/i-nduzHomjE
https://youtu.be/wn_DpOC5g6k
https://pastebin.com/TuWbzuKB

**Comment by pops64** [comment]
CP has never been know to play nice with pivoted trailers. It is usually a hit or miss whether it works. And you are compounding the problem by using what looks like a modded trailer which may or may not be recognized by CP correctly

**Comment by pops64** [comment]
The functionality is there #3578. The option to change it got removed in the HUD refactoring, In the meantime you can cheat by selecting a mode where the option is visible and changing it.

**Comment by pvaiko** [comment]
This isn't something trivial, won't fix it.
