### ISSUE TITLE
Mode2 is missing turn on field

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#3578]
There is no option to allow mode2 to turn on field which was critical function for tools that don't play nice with reversing 
![fsScreen_2019_04_10_12_12_26](https://user-images.githubusercontent.com/10678220/55895348-fe809e80-5b89-11e9-97ba-53c0d15e0732.png)

**Comment by ThomasGaertner** [comment]
@pops64 would you please stop wild cross referencing the issues ? its a bit annoying .
please test v.177 concerning this issue...

**Comment by pops64** [comment]
Sorry. Same person split an issue. Wasn't to sure which was the primary
