### ISSUE TITLE
Drive Now button always visible

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#3579]
Drive Now button is always visible. Even when CP isn't currently driving the tractor. 
![fsScreen_2019_04_10_12_14_44](https://user-images.githubusercontent.com/10678220/55895492-456e9400-5b8a-11e9-98fd-bf9d328c4bb4.png)

**Comment by Tensuko** [comment]
It disappears when you click on it, we will take a look at it.

**Comment by ThomasGaertner** [comment]
#3311

**Comment by pops64** [comment]
What does this have to do with mode2?

**Comment by ThomasGaertner** [comment]
nope it isnt. its just in mode 2 and 6 and the way , vehicle.isLoaded  handled in mode2  will not be changed in the dying version...

**Comment by pops64** [comment]
It still should not be visible when CP is not driving. Cause you know that variable only applies to driving functions assuming that carried over in the refactoring and it clutters the 2nd pg imo.
