### ISSUE TITLE
Hosted files versions for FS17 ?

### ISSUE THREAD

**Issue by Anonymous-any** [Courseplay/courseplay#3582]
Hello, @ThomasGaertner I would like to submit a thing that youtuber's want to know and I by the way were we see different hash version of CP for FS17 in whole internet.
It seem there is more than one version like 5.3.0.0 you have on https://courseplay.github.io/courseplay/ , redirect on modhub https://www.farming-simulator.com/mod.php?mod_id=92045 Released 06.07.2018 like it show maybe not updated look old ? and the called supposed and fixed Final Release for FS2017 here https://github.com/Courseplay/courseplay/releases/tag/v5.03.00050 as 23 Nov 2018. Event not enough players seem use them to play online with, you know different versions cannot reached. Can make the light on these please ?
Another question please, are people allowed to host renamed file versions elsewhere for example ?
Best regard

**Comment by Tensuko** [comment]
We won't support the old FS17 anymore.
You can get the latest Version only on github or take the most stable version we had that time on modhub.

You are NOT allowed to publish ANY modified or renamed files anywhere!

**Comment by Anonymous-any** [comment]
Many thank for fast answer.
Br
