### ISSUE TITLE
Field mode - turn off and transport mode of implement before "Return to start point"

### ISSUE THREAD

**Issue by Martinnygaard** [Courseplay/courseplay#3583]
I think that "Field mode" should turn off implement (and preferable put it in transport position) before it starts the "Return to first point".

In this case, my raker drives diagonal over the field, resulting in some small bits and pieces raked diagonal (even when the raker is lifted, because it is still running)

![cp](https://user-images.githubusercontent.com/26490587/55909473-75468780-5bdc-11e9-80f0-d22424512d89.png)

**Comment by pvaiko** [comment]
Reopen if does not work.
