### ISSUE TITLE
Cant save the game - LUA Errors (at End of Logfile)

### ISSUE THREAD

**Issue by kartal2339** [Courseplay/courseplay#3584]
hi.. i play fenton forest map and when i activate courseplay my game cat save ... but without courseplay there is no problem.. i added my log 
[log.txt](https://github.com/Courseplay/courseplay/files/3065686/log.txt)

**Comment by Tensuko** [comment]
Load mod: FS19_FentonForestByStevie (Version: PublicV1.34) (Hash: 1af910ef89fc96131a5af6fd7abf5256)
Error: Failed to open xml file 'C:/Users/unsal/Documents/My Games/FarmingSimulator2019/mods/FS19_FentonForestByStevieV134UNZIPME/modDesc.xml'.
Load mod: FS19_FentonForestByStevieV134UNZIPME (Hash: 9e4c0037358d46f5d71ce129c86e6818)
Error: Missing descVersion attribute in mod FS19_FentonForestByStevieV134UNZIPME

what is this ? 2 times same mod, one with some version in name ?
Both got Errors anyway.
Also: RealDirt is in your Mods, that doesn't have to make errors, but can.

Maybe some Vehicle conflict with CP ?
2019-04-10 22:22 Warning (script): 'setXMLInt': Argument 2 has wrong type. Expected: Int. Actual: Nil 
2019-04-10 22:22   ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (791): expectedType == Value::VoidType || expectedType == Value::ClassType

**Comment by kartal2339** [comment]
thanks for your help.. i solved the problem.. i deleted custom moding jd 8r v2.0 and courseplay starts to work properly...

**Comment by Tensuko** [comment]
ok, thx for rply. Closed.
