### ISSUE TITLE
Combine controls page - overlapping text name

### ISSUE THREAD

**Issue by zed636** [Courseplay/courseplay#3585]
Hello Devs

Game Version: 1.3.0.1 b4009
CP version: 6.01.00177
Time of event: 2019-04-10 23:30
Map: Ravenport
No mod installed

as you can see in the screenshot below, the following commands are superimposed in the Italian translation. Is it possible to move the corresponding text name slightly to the right?
![fsScreen_2019_04_10_23_31_01](https://user-images.githubusercontent.com/19471664/55915644-518a3e00-5bea-11e9-82a7-7cfe1730629b.png)

They are located on the page COURSEPLAY_PAGE_TITLE_COMBINE_CONTROLS and are the following text names:
COURSEPLAY_STOP_DURING_UNLOADING 
COURSEPLAY_ACTIVATED
COURSEPLAY_DEACTIVATED

COURSEPLAY_HEADLAND_REVERSE_MANEUVER_TYPE
COURSEPLAY_HEADLAND_REVERSE_MANEUVER_TYPE_STRAIGHT
COURSEPLAY_HEADLAND_REVERSE_MANEUVER_TYPE_CURVE

regards
Marco

**Comment by Tensuko** [comment]
Thats right, thats some tweaking need to be done.
