### ISSUE TITLE
toolManager.lua:992: attempt to index local 'currentDischargeNode' (a nil value)

### ISSUE THREAD

**Issue by Ralleran** [Courseplay/courseplay#3586]
[log.txt](https://github.com/Courseplay/courseplay/files/3066580/log.txt)

**Comment by Tensuko** [comment]
What did you do to get that LUA Error ?
Short discription would be nice.

**Comment by Ralleran** [comment]
Ich hatte ein Drescher im Feldarbeits Modus laufen und ein Abfahrer im Modus 2

**Comment by ThomasGaertner** [comment]
wenn Du mir noch sagst, welche Tools Du benutzt hast hab ich ne Chance, vielleicht was raus zu finden. Eine bessere Beschreibung der Situation ist immer Hilfreich.

**Comment by Tensuko** [comment]
Closed wegen inaktivität.
Wenns was neues gibt, wird der wieder aufgemacht.
