### ISSUE TITLE
working with the hud while driving

### ISSUE THREAD

**Issue by ThisPf** [Courseplay/courseplay#3587]
Hi

I noticed, as I searched for a course on the way to the field.  The steering wheel and the pedals did not work, as soon as I with the mouse on the Hud. Can someone else confirm that?

CP version: 6.01.00177

Erkläre es noch etwas genauer auf Deutsch:
Sobald der Mauszeiger auf der Liste mit den gespeicherten Kursen war, waren das Lenkrad wie auch die Pedalen ausser Funktion. Ich nehme an, mit einem Gamepad wäre es dasselbe. Ich glaube es war erst dann der Fall, wenn die Scroll-Funktion angezeigt wurde. Es war schon spät, weshalb ich keine weiteren Tests gemach habe. Könnte ich heute Abend machen, falls sonst keiner dies bestätigen kann.

Vielen Dank für eure Arbeit
Grüsste ThisPf

**Comment by Tensuko** [comment]
Das ist so gewollt.
Jedes Menü bei dem man Scrollen kann, werden eingabn deaktiviert.
Grund: Wenn man durch das Menü scrollt, verstellt man sonst die Kamera! Das ist sehr nervig.
Das wird auch erstmal so bleiben und ist bereits seit sehr viele Versionen so.
Closed.
