### ISSUE TITLE
Mähdrescher 

### ISSUE THREAD

**Issue by Tommypz** [Courseplay/courseplay#3588]
Hallo

Der Mähdrescher und der Anfahrer kommen sich ins gehege bei der Version 1.78

es hat doch mal sogut funktioniert!
![fsScreen_2019_04_11_08_50_08](https://user-images.githubusercontent.com/47914756/55936874-d3548880-5c37-11e9-86e5-f9f6f08b3ab6.png)
![fsScreen_2019_04_11_08_50_28](https://user-images.githubusercontent.com/47914756/55936881-d8b1d300-5c37-11e9-88a8-e9ed2701b076.png)

**Comment by Tensuko** [comment]
Mode2 wird erst noch neu programmiert.
Closed #3311
