### ISSUE TITLE
no visible Field-Border? v6.01.00178

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#3590]
Hello Guys,
whem i stand in an nw Field and want generate a new FieldBorder, i cant see the Blue Lines / Yellow Points from the recognized field so as in earlier versions:
COURSEPLAY_SCAN_CURRENT_FIELD_EDGES
![fsScreen_2019_04_11_12_26_36](https://user-images.githubusercontent.com/24860501/55950873-2f2e0a00-5c56-11e9-88ca-81e0fa2e281e.png)
to controll, that cp generate the Field correct.
is it possible to turn it on again?

edit:
my false, the eye was not here, it was in the old coursegenerate menü,
but is it possible, to turn it on so that we can see / controll the fieldborders?

2. i see no chance to abort the field edges scan.
earlier there was a "stop" or abort sign (the circle with slash - iconSprite.dds: 8.Row, 2nd sign)
![fsScreen_2019_04_11_12_44_32](https://user-images.githubusercontent.com/24860501/55951535-ca73af00-5c57-11e9-83e5-8f02789c85c4.png)

lg
andreas

**Comment by DemonRaven** [comment]
Same issue here

**Comment by ElfVierzehn** [comment]
I am here, because I wanted to check if somebody mentioned the issue. Yesterday evening I experienced the same. Version: 6.01.00185

**Comment by pvaiko** [comment]
Giving this back to @ThomasGaertner as he commented the call to showFieldEdgePath() out when reworking the HUD. Once showFieldEdgePath() is called again and still does not work I'm happy to take over again.

**Comment by andreasthu** [comment]
Thanks,
test it with 6.01.0205 and both changes work perfect.
now i can see the feildborder after generating (eye)
or abort fieldgenerating with the other icon

lg
andreas
