### ISSUE TITLE
Sprüher klappen nach arbeit nicht zusammem

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#3591]
Ich benütze den Kuhn DELTIS 1302 MTA3. Er klappt nach dem er das Feld gedüngt oder mit Pflanzenschutz besprüht hat nicht mehr zusammen. Welche debug Channel wären dafür erforderlich. Eingestellt Düngen und Sähen.

MFG Mannie313

**Comment by Tensuko** [comment]
Momentan können wir da nichts dran machen. Im Prinzip benutzen wir den AIDriver von GIANTS um den Kurs abzufahren, und was der AIDriver nicht macht, macht CP aktuell auch nicht.

Erstmal alle Modi zurückbringen und LUA Errors beseitigen.
Closed.
