### ISSUE TITLE
Problem create an Course since Vers. ....171 !?

### ISSUE THREAD

**Issue by scandal65** [Courseplay/courseplay#3593]
...at first sorry for my english! ;)

since version **courseplay-master60100171** i couldn`t create any course!
so i have no botton look at my picture

version courseplay-master60100167 works !
![fsScreen_2019_04_11_15_53_57](https://user-images.githubusercontent.com/49526721/55966212-467def00-5c78-11e9-8413-ec2133166024.png)
![fsScreen_2019_04_11_15_59_24](https://user-images.githubusercontent.com/49526721/55966213-467def00-5c78-11e9-9bc0-3028b9e2ebfd.png)
![fsScreen_2019_04_11_15_59_28](https://user-images.githubusercontent.com/49526721/55966214-47168580-5c78-11e9-8d94-f7733ffc8e6b.png)
![fsScreen_2019_04_11_15_53_48](https://user-images.githubusercontent.com/49526721/55966215-47168580-5c78-11e9-8af6-b1ffd41775ae.png)

**Comment by Tensuko** [comment]
Red this #3552
Closed.
