### ISSUE TITLE
Düngerstreuer stoppt Düngung zu früh

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#3594]
Düngerstreuer (hier Bredal K-105) düngt nicht bis zum Feldende, es bleiben immer kleine, ungedüngte Flecken. Tritt soweit ich es testen konnte, auch mit anderen Mineral-Düngerstreuern auf.
![fsScreen_2019_04_11_17_22_15](https://user-images.githubusercontent.com/21023840/55969919-e2aaf480-5c7e-11e9-96b7-31304c5f0e47.png)

**Comment by Tensuko** [comment]
#3498

**Comment by pvaiko** [comment]
duplicate of #3242
