### ISSUE TITLE
Mode2 öffnet die Plane beim Abfahrer nicht

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#3597]
Siehe Screenshot, bis .0167 hat das funktioniert, seit HUD rework (?) gehts nicht mehr
![fsScreen_2019_04_11_18_51_30](https://user-images.githubusercontent.com/21023840/55975985-7387cd00-5c8b-11e9-9162-625120bdf676.png)

**Comment by Tensuko** [comment]
#3311 
warum das jetzt nicht mehr geht, keine Ahnung.
Aber es wird kaum was dran gemacht werden, solange Mode2 nicht neu geschrieben wurde.

**Comment by iljarogoff** [comment]
Ok, wollte es nur mitteilen. Weiter so, ihr macht nen spitzen job!
