### ISSUE TITLE
Small unworked patches when going from headland to field up down rows

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/courseplay#3598]
Since the old course generator is gone i use the new one. It works good, but there is one thing: When you make some sharp headland corners he do the headland corners without problem. But: When done with headland there are missing turning manuever start and end points, so the driver makes an 180 Grad Turn and misses some fruit. Happens with all devices. 
![Screenshot (1761)](https://user-images.githubusercontent.com/47073128/55977259-abdcda80-5c8e-11e9-9541-6ddb7f1ef5ab.png)

**Comment by andreasthu** [comment]
Maybe there was a turnstart turnend point the solution.
So that the combine makes no 180degree turn, 
Insteed a normal turning so as in the up/down rows after.

Vielleicht wäre hier auch eine turnstart und turnend funktion die lösung.
Also anstelle der 180grad wendung,
Eine normale wendung wie in den hoch/runter reihen danach.

Lg
Andreas

**Comment by pvaiko** [comment]
Try with 206 or later.

**Comment by StefanBraun2001** [comment]
I will try it today.

**Comment by pvaiko** [comment]
What generator settings are you using? I can't reproduce this, it could be off a meter or two but not 10 like here.

**Comment by StefanBraun2001** [comment]
![Screenshot (2455)](https://user-images.githubusercontent.com/47073128/57574222-43bc1880-7435-11e9-9990-6e668c3826dd.png)
![Screenshot (2456)](https://user-images.githubusercontent.com/47073128/57574223-43bc1880-7435-11e9-9178-68c9d63c0d02.png)
That settings i use. Number of headlands does not matter. (it happens with 1 headland and 20 too)

**Comment by pvaiko** [comment]
Too bad you switched to another map. This what I see on Felsbrunn Field 16 with same settings you have:

![image](https://user-images.githubusercontent.com/2379521/57576218-fc775d00-741f-11e9-9630-366440210d55.png)

No idea what are you doing different but there's something...

**Comment by StefanBraun2001** [comment]
I will make a test on felsbrunn again and report back
Peter Vaiko <notifications@github.com> schrieb am So., 12. Mai 2019, 02:09:

**Comment by pvaiko** [comment]
Closing due inactivity, reopen if problem still exists.
