### ISSUE TITLE
Abfahrer schiebt Drescher weg

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#3599]
Wenn der Abfahrer voll ist und dann auf den Abladekurs wechselt und der Mähdrescher diesen Weg kreuzt, schiebt der Abfahrer den Drescher weg, schneidet ihm quasi den Weg ab und die beiden kollidieren
![fsScreen_2019_04_11_19_57_22](https://user-images.githubusercontent.com/21023840/55980305-776c1d00-5c94-11e9-91b3-2b5c290aed53.png)

**Comment by iljarogoff** [comment]
Hier noch ein paar Screens
![fsScreen_2019_04_11_20_07_18](https://user-images.githubusercontent.com/21023840/55980830-9b7c2e00-5c95-11e9-895e-efcc5c817cfd.png)
![fsScreen_2019_04_11_20_07_23](https://user-images.githubusercontent.com/21023840/55980834-9dde8800-5c95-11e9-92dd-ec5486832459.png)
![fsScreen_2019_04_11_20_07_25](https://user-images.githubusercontent.com/21023840/55980838-9f0fb500-5c95-11e9-948a-f82764aad059.png)
![fsScreen_2019_04_11_20_07_27](https://user-images.githubusercontent.com/21023840/55980840-a0d97880-5c95-11e9-8ae7-74c1c2c09e0e.png)

**Comment by Th301** [comment]
Mode 2 Problem. Wird wohl geschlossen weil die Überarbeitung aktuell läuft.

**Comment by pulimatrix** [comment]
Habe Das Selbige Problem, Abfahrer Schieb drescher bei seite, bzw fährt genau drauf zu, ohne mal irgendwie auszuholn :/ Wird daran Aktuell gearbeitet?!

**Comment by CialisSiggi** [comment]
Guten Tag, wann wird es einen Fix geben? So lässt sich leider unmöglich spielen.
