### ISSUE TITLE
Deactivating fertilizer function is not working like expected

### ISSUE THREAD

**Issue by Th301** [Courseplay/courseplay#3600]
Hey there,

I just saw, that deactivating the fert.-function at a sawing-machine does not work like I would expect it to work.

The driver uses the fert. until it is empty. than he continues without fert.

In my opinion, the fert. should stay untouched, when the function is deactivated.

greetz :)

**Comment by ThomasGaertner** [comment]
this is an untested shot from the hip. please test v.181 and report

**Comment by StefanBraun2001** [comment]
With Version 181 the sowing machine does not drive when fert. function is off. When on he drives like normal...

**Comment by Th301** [comment]
Thanks for testing @StefanBraun2001.

I can not test it until the afternoon.

**Comment by ThomasGaertner** [comment]
try with 183, should work now...

**Comment by Th301** [comment]
with 183 it is working like expected! :)

**Comment by StefanBraun2001** [comment]
I tested it too, the fert. function work good now, but when i fert. by myself no fert. is being used for field. It only works when CP is active...

**Comment by Th301** [comment]
zu früh gefreut.

it is working like expected when using cp.

When I try to seed and fert. manually on my own, it seems as if the fert. function is completely deactivated and there is no key to bind to activate the fert. function when you don't use cp.

**Comment by StefanBraun2001** [comment]
Finaly, it works fine with V 184, when i drive the seeder myself fert is used. Thank you very much,

**Comment by Tensuko** [comment]
Fixed. Closed.
