### ISSUE TITLE
Pause Button

### ISSUE THREAD

**Issue by moehre85** [Courseplay/courseplay#3601]
would it be possible to add a pause-button that stops the current course departure and does not always release the helper?
Thank you for your excellent work.

wäre es möglich einen pause-button hinzuzufügen, der die aktuelle Kursabfahrt anhält und nicht immer den Helfer entlässt?
Vielen Dank für Ihre ausgezeichnete Arbeit.

**Comment by Krahazik** [comment]
A pause button would be usefull for dealing with ceratain situations where you need to have some control over the vehicle for just a moment. Such as opening the cover to refill a tool, or extend the overload pipe, etc. Once done, you unpause and the helper resumes the course.

**Comment by Tensuko** [comment]
Not going to happen, sry.
