### ISSUE TITLE
Abfahrer beläd nicht am Startpunkt

### ISSUE THREAD

**Issue by hobi17** [Courseplay/courseplay#3602]
Hallo an alle und meinen großen Respekt und Dank an die Macher hier von CP!
Ich nutze CP nun schon von Anfang an seit CP für LS19 verfügbar ist. 
Seit ca. der Version 155 habe ich im Mode 1 Probleme! Und zwar beläd mein Abfahrer nicht am Silo. Ich habe mehrere Verkaufskurse mit Startpunkt am Silo. Bis zur Version 154 funktionierte dieses auch. Nun allerdings schon länger nicht mehr. Ich habe längere Zeit abgewartet und auch alles mögliche ausprobiert, wie Standartsilos, Modsilos, Standartfahrzeuge und Modfahrzeuge, aber nichts hat geholfen.
Vielleicht ist dieses Problem ja bekannt oder es liegt doch irgendwo an mir?! Ich weiß es nicht
und wollte deshalb einmal hier mein Glück versuchen und vielleicht auch helfen wenn ich kann.
Gruß

**Comment by Tensuko** [comment]
Logfile wäre gut.

**Comment by ThomasGaertner** [comment]
Und ein Screenshot

**Comment by hobi17** [comment]
![Bild1](https://user-images.githubusercontent.com/49533659/56017137-a7500a80-5cfe-11e9-8bcd-792a091a1ab6.jpg)
Hier die Einstellung des Kurses!
![Bild2](https://user-images.githubusercontent.com/49533659/56017139-a7500a80-5cfe-11e9-8ca4-08848a00b3e6.jpg)
CP erkennt den Trigger und sagt wird beladen!
![Bild3](https://user-images.githubusercontent.com/49533659/56017140-a7e8a100-5cfe-11e9-84f6-3fc663696bd0.jpg)
Macht dann aber am Startpunkt die Plane zu und fährt durch!

Hier auch noch meine log!
[log.txt](https://github.com/Courseplay/courseplay/files/3071881/log.txt)

Vielen Dank! Grüße!

**Comment by ThomasGaertner** [comment]
probiere bitte einmal, den startpunkt ein bisschen weiter entfernt zu setzen, da wo jetzt  der fünfte ist.
dann sollte es funktionieren. wenn nicht, log mit debug 2 aktiv bitte

**Comment by hobi17** [comment]
@ThomasGaertner 
Vielen Dank für die Hilfe - das war tatsächlich die Lösung!!!
Da wäre ich nie drauf gekommen, da es vorher funktionierte und bei allen Erklärungsvideos auf YT wird oft gesagt den Startpunkt knapp am Anfang des Anhängers zu legen.

Also nochmal vielen Dank - ich werde dann mal die Verkaufskurse neu anlegen! 

Grüße
