### ISSUE TITLE
Mode 1, Sofort abfahren fehlt.

### ISSUE THREAD

**Issue by zsorra** [Courseplay/courseplay#3603]
Hallo,

seit der Umstellung auf die neue HUD, fehlt die Möglichkeit im Mode 1 den Helfer abfahren zu lassen, auch wenn der Hänger nicht zu 100% voll war. Das war sehr nützlich wenn das Silo mal leer war.

Hello,

since the change to the new HUD, there is no possibility to let the helper drive in mode 1, even if the trailer was not 100% full. This was very useful when the silo was empty.

mfG

**Comment by Tensuko** [comment]
Fixed. Closed.
