### ISSUE TITLE
base.lua:1704: bad argument #1 to 'concat' (table expected, got nil)

### ISSUE THREAD

**Issue by skynyrd47** [Courseplay/courseplay#3604]
So since I updated to the newest beta I keep getting this same error which unfortunately freezes the game at the save screen. Any ideas? I have read thur most of the logged issues and responses and cant seem to break this. Thank you.

[log.txt](https://github.com/Courseplay/courseplay/files/3070982/log.txt)

**Comment by pvaiko** [comment]
Reopen if you can reproduce this without all those mods. See also #3519

**Comment by skynyrd47** [comment]
So if I revert back to 147 I can save and have no problems. Any thoughts? 
[log.txt](https://github.com/Courseplay/courseplay/files/3076331/log.txt)
