### ISSUE TITLE
mode 1 last line, course name will be overwritten

### ISSUE THREAD

**Issue by omegaMV6** [Courseplay/courseplay#3605]
Courseplay V 6.01.00181

First of all many thanks for given us this greatfull mod! 

How you can see in the picture there are too many letters in the last line in mode 1.  The course name and the fruitname are overwritten. 
The course name has the length i can write into the hud for saving a course.
![fsScreen_2019_04_12_01_39_16a](https://user-images.githubusercontent.com/22158501/56003521-03973800-5cc7-11e9-9cf0-a6971d7c3bab.png)

So maybe its better to write the fruitname in the hud like in older version of cp.

**Comment by ThomasGaertner** [comment]
we decided not to move the test, but to cut the course name. I hope, you can live with that :-)
