### ISSUE TITLE
Fahrzeuge Crashen zusammen ?

### ISSUE THREAD

**Issue by Starkwood12345** [Courseplay/courseplay#3608]
Hi nur selten steht mal der text da er steht steckt im verkehr fest.

Zum beispiel beim Drescher abfahren.

Der Drescher ist voll der Traktor mit Kipper kommt.
Wenn der Traktor Voll ist fährt er sofort los trotz Wartezeit  und fährt den Drescher sehr oft einfach rein.

Auch  Wenn meine Saatmaschine unterwegs ist und sich gerade aufn Hof kreuzt mit ein anderes Fahrzeug Crashen sie einfach zusammen es wartet leider keiner.

Mache ich was falsch?

Würde mich über eine Antwort freuen :) danke

**Comment by pvaiko** [comment]
#3311
