### ISSUE TITLE
HUD Page 1 not visible with cotton harvester

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/courseplay#3609]
For the Cotton Harvester the HUD Page 1 is missing. 
![Screenshot (1820)](https://user-images.githubusercontent.com/47073128/56073008-e5e8d200-5d9d-11e9-8f2d-a2a1d4569f07.png)

**Comment by Tensuko** [comment]
Becouse you cant unload it with a Mode2 Driver...
