### ISSUE TITLE
Drescher reverses the downhill driver.

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#3611]
CP version 6.01.00184
threshing, fruit bypass active
Drescher drives off the track, after unloading wants to the
Drescher back into the lane and knocks over the driver!
The thresher then drives into the field. (see pictures)
![fsScreen_2019_04_13_10_07_58](https://user-images.githubusercontent.com/48583507/56076982-f2d5e780-5dd6-11e9-884b-2ca452b7355b.png)

**Comment by ThomasGaertner** [comment]
#3311

**Comment by Lustiger-Hubi** [comment]
Did I do something wrong?

Hab ich was falsch gemacht?

Sorry

 

Von: Thomas Gärtner <notifications@github.com> 
Gesendet: Samstag, 13. April 2019 10:43
An: Courseplay/courseplay <courseplay@noreply.github.com>
Cc: Lustiger-Hubi <margot@lwb-wassertechnik.de>; Author <author@noreply.github.com>
Betreff: Re: [Courseplay/courseplay] Drescher reverses the downhill driver. (#3611)

 

#3311 <https://github.com/Courseplay/courseplay/issues/3311>

**Comment by Lustiger-Hubi** [comment]
Did I do something wrong?

Hab ich was falsch gemacht?

Sorry

 

Von: Tensuko <notifications@github.com> 
Gesendet: Samstag, 13. April 2019 10:57
An: Courseplay/courseplay <courseplay@noreply.github.com>
Cc: Lustiger-Hubi <margot@lwb-wassertechnik.de>; Author <author@noreply.github.com>
Betreff: Re: [Courseplay/courseplay] Drescher reverses the downhill driver. (#3611)

 

Closed #3611 <https://github.com/Courseplay/courseplay/issues/3611> .

**Comment by Tensuko** [comment]
Nein hast du nicht :)
Aber da es Mode2 betrifft ( #3311 ) wird erstmal nichts dran gemacht.
Mode2 wird neu geschrieben, daher gibt es erstmal keinen support für Mode2.
Sry!

**Comment by Lustiger-Hubi** [comment]
Danke für deine Mühe

 

Von: Tensuko <notifications@github.com> 
Gesendet: Samstag, 13. April 2019 12:04
An: Courseplay/courseplay <courseplay@noreply.github.com>
Cc: Lustiger-Hubi <margot@lwb-wassertechnik.de>; Comment <comment@noreply.github.com>
Betreff: Re: [Courseplay/courseplay] Drescher reverses the downhill driver. (#3611)

 

Nein hast du nicht :)
Aber da es Mode2 betrifft ( #3311 <https://github.com/Courseplay/courseplay/issues/3311>  ) wird erstmal nichts dran gemacht.
Mode2 wird neu geschrieben, daher gibt es erstmal keinen support für Mode2.
Sry!
