### ISSUE TITLE
LUA  method 'draw - hud.lua: 592: + LUA Call stacks

### ISSUE THREAD

**Issue by kartal2339** [Courseplay/courseplay#3612]
hi.. when i use cp after a time my game have been crashing and i cant change vehicle or i cant save my game at this time keyboard dont affect anything ...only mouse active and it starts only cp or stop 
[log.txt](https://github.com/Courseplay/courseplay/files/3076152/log.txt)

**Comment by Tensuko** [comment]
duplicate of #3592
Closed.
