### ISSUE TITLE
suggestion: mode1 for bale collector

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#3613]
Hey guys.
Sometimes i have no collecting fieldcourse, when i want deliver or sell silagebales to the "Scheune" on Felsbrunn.
I mowing grass on fieldrands, make bales, make silagebales and will sell them on the Scheune. 
So i collect them manually with the arcusin autostack.
But when i will let cp drive him to the Scheune so i have now no funktion in cp.
In the old hud it was able to give it a mode1 course, in the new hud no chance.

Lg
Andreas

**Comment by pvaiko** [comment]
Just for my understanding, why can't you do this in mode 6?

**Comment by andreasthu** [comment]
hello pvaiko
ok, normaly i mowe the grass around the Fields, make Grassbales with the Baler and wrap them into silage bales.
so my bales are scattered around the fields.
here you can see a mappdapic from mowed grass:
![fsScreen_2019_04_16_13_41_46](https://user-images.githubusercontent.com/24860501/56206973-e7402600-604d-11e9-8dba-d45ecc441563.png)
around Fields 09-14, 17-22 and 25-29.

now i collect them manually with the arcusin autostack.
when the autostack is full (in this example south from Field21),i will let them drive with cp to the Scheune in Felsbrunn, unlaod them there (silagebales are good money) and will drive them also to the point to Field21, then i collect again manually.
i use the saved course, which i use when i collect straw from field21 to scheune (here i have a fieldcourse, and addet the drive-away course - this works normal),

but now i have no fieldcourse as first course, my course is only the drive-away course from field21 to Scheune.
when i drive this course in mode5, the tractor drive only during all coursepoints and come back with the full load.
when i drive this course with mode6, cp unfolds the arcusin autostack and drive the drive-away coures as Working course.
![fsScreen_2019_04_16_13_40_29](https://user-images.githubusercontent.com/24860501/56207387-e3f96a00-604e-11e9-87d8-21538e0eef2f.png)

so i think it was fine, when it is possible, to activate mode1 also for balecollectors.
to let cp drive them to the Scheune, unload there the bales, and come back to my place where he starts.
everything understood?
lg
andreas

**Comment by Tensuko** [comment]
Create a Fake Course (2 Waypoints) and add your sell course to this. Can you try this methoed and report ?

**Comment by andreasthu** [comment]
Ok, danke
 I will test it after eastern.
No time yet - two little kids

Lg
Andreas

**Comment by andreasthu** [comment]
Hallo Tensuko
es hat doch etwas länger gedauert.
hier die Ausgangssituation:
stehe mit vollem Arcusin (16Ballen) in der nähe von Feld11, Felsbrunn, und möchte nun den Arcusin per cp zur Scheune fahren, dort die Ballen entladen lassen, und mit dem Gespann wieder zu Feld11 zurückfahren, um weiter manuell die Ballen zu sammeln.
im video sieht man zwei versuche, erstmal den gespeicherten kurs Feld11-Scheune, mode6, cp klappt den arcusin aus uns will sammeln, da voll, bleibt er stehen, der nächste versuch, vorher einen temporären kurs anzulegen, und dann mit dem gespeicherten Kurs zusammenzulegen funktioniert auch nicht.

https://youtu.be/XTkufVgQEZ0

was funktioniert, einen Feldarbeitskurs zu generieren, und dann den Verkaufskurs anhängen.
aber es wäre echt einfacher, wenn man mit dem arcusin für den kurs auch den mode1 auswählen könnte 

lg
andreas

**Comment by Tensuko** [comment]
Ich verstehe was du erreichen willst.
Werden das mal durchsprechen.

Es kann sein, dass 2 Wegpunkte nicht genug sind für einen Arbeitskurs.
Werden uns das mal anschauen.

**Comment by andreasthu** [comment]
Danke

**Comment by Tensuko** [comment]
Also wir haben drüber gesprochen und werden das so erstmal nicht anfassen.

Mal ein Vorschlag:
Du hast ja bei dem Feld bestimmt irgend ein Feldarbeitskurs. Lade den einfach und hänge den anderen Kurs zum wegfahren dran. Sag dann Warten am Letzten Wegpunkt oder Trigger. Er sollte dann eigentlich wieder beim Feld ankommen und dort am Endpunkt warten und nicht mit der 'Arbeit am Feld' loslegen.

Sollte so funktionieren, was anderes können wir erstmal nicht anbieten.

**Comment by andreasthu** [comment]
ok, danke
werd ich so machen müssen.
lg
andreas

**Comment by Tensuko** [comment]
Ich mach den hier denn erstmal zu.
Wenn der auch beim Abladen wartet, sag mal bescheid.

Closed.
