### ISSUE TITLE
New Mini-HUD always on - every game start, every vehicle

### ISSUE THREAD

**Issue by 51stHD** [Courseplay/courseplay#3614]
Would it be possible to give the new HUD feature some way of remembering it's setting when you turn it off?

As it is currently at every game restart the HUD is back on in each and every vehicle.

**Comment by Tensuko** [comment]
I just loaded my savegame and the HUD is off at all vehicles. Even when I saved the game with one Vehicle HUD on...
Can you give us a lofgile with debugchannel 18 and do some on/off the HUD and save at the end (don't know if that help anyhow....)

**Comment by 51stHD** [comment]
Here's the log. [log.txt](https://github.com/Courseplay/courseplay/files/3076359/log.txt)

This still happens for me, no mods in folder, even without the Anderson DLC enabled, so it doesn't appear to be a mod clash. It's a bit frustrating, as I really love CP, but don't intend to use the new HUD, so for now it's turned CP into a 4 click per vehicle click-fest every time I load a game.

I hope you can sort somehow.

Thanks

**Comment by 51stHD** [comment]
Just to be clear, I am referring to the "mini" HUD, ie., the white ticker tape that now appears on screen by default and requires to be disabled in the setting menu, not the CP HUD, in case there was a mis-understanding :)

**Comment by Tensuko** [comment]
Ah okay! That clear thungs up! Ok I will take a look again :)

**Comment by ThomasGaertner** [comment]
so for my understatement: you want the mini-HUD option (active/deactivated) setting saved  ?

**Comment by 51stHD** [comment]
Yes that is correct.

**Comment by Tensuko** [comment]
Should be fixed with 189 or higher.
Closed.
