### ISSUE TITLE
LUA method 'draw' - AIDriver.lua:558 (HUD Issue?)

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/courseplay#3615]
Hab vorhin diesen Error gehabt, konnte ihn reproduzieren:
- Ziel ist es, Mode2 zu starten
- Im HUD zu Mode1 und dann wieder zu Mode2 wechseln
- Mode2 abfahrer einstellen
- Error erscheint
- cpStopAll
- Im HUD auf Mode1 wechseln
- Abfahrer einstellen und stoppen
- Wieder auf Mode2 gehen und Abfahrer einstellen
- Kein Error

Oder anders: Wechselt man kurz den Modus zu 1 und dann wider zu 2, gibt es den Error.
Hat man in Mode1 einmal den Abfahrer eingestellt, kann man dies auch wieder in Mode2.

Getestet mit Vanilla, V185

[log.txt](https://github.com/Courseplay/courseplay/files/3076290/log.txt)

**Comment by ThomasGaertner** [comment]
ist zur Kenntnis genommen , fällt aber unter #3311 da mode2 (alt) nicht das neue Course System benutzt.
