### ISSUE TITLE
Grimme GL 860 Compacta drops down to late.

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/courseplay#3618]
Hello!
I noticed that the Grimme GL 860 Compacta drops down the machine too lateduring headland so small unworked patches are left. In up/down rows turning works fine
![Screenshot (1846)](https://user-images.githubusercontent.com/47073128/56083028-1cffc780-5e20-11e9-9006-cedf7d3476a0.png)
The driver lowerd device just now

**Comment by Tensuko** [comment]
I guess you mean to late ? He reverse, then go forward again and drops it to late ?

**Comment by StefanBraun2001** [comment]
Oops, i am an idiot. Of course i mean he drops down to late, sry

**Comment by StefanBraun2001** [comment]
![Screenshot (1911)](https://user-images.githubusercontent.com/47073128/56099873-4ea58b00-5f13-11e9-9304-6ff2261aeda5.png)
Tested it again, it works better, but still a small unworked patch.
