### ISSUE TITLE
Not recognising custom vehicle types.

### ISSUE THREAD

**Issue by kylemeyer13** [Courseplay/courseplay#3621]
I have noticed that courseplay is not working at all with custom vehicle types. If you buy a tractor that has a custom vehicle type the game will not save. I have tried multiple vehicles with custom types with no success most of these mods are very high quality and it is a bummer that they can't be used with cp. Is there any progress with this or is it something we are going to have to deal with

**Comment by Tensuko** [comment]
The question is why does those Mods have to be Custom Vehicle Type ?
If they just use the GIANT Vehicle Type it would be fine...
Can you give some examples of those Vehicles ? (With original download source pls)

**Comment by kylemeyer13** [comment]
https://sharemods.com/rbct5575qx43/FS19_CM_8R_Series.zip.html

This is the only one that I can share right now. As far as I can tell they are using a custom vehicle type so the can have folding flasher arms on the back of the tractor.

**Comment by kylemeyer13** [comment]
As far as I can tell you cannot have the foldable specialization in a standard tractor.

**Comment by 37cee** [comment]
Why the "custom" type is used is questionable. I changed the type in the mods xml and it worked fine without CP crashing. Custom Modding has done this alot though... but they are not the only modders by far, sometimes i think modders don't understand that the type described the basic function.
So this is really the modders fault and not CPs, since the "new" vehicle offers no different functionality.

**Comment by Tensuko** [comment]
Thx for the info @37cee

**Comment by cwattyeso** [comment]
Not sure about other Modders but Custom Modding do the Custom Vehicle Type when they are beta testing their mods, which they release to their site subscribers/patreon supporters first. It's almost a security feature of their's that if someone goes and uploads a beta version of their mod on any of the many mod sites that steal and re-upload other people's content then anyone downloading it is going to run into issues with compatibilities with mods and stuff and have issues saving or crashes as a result of this Custom Vehicle Type. When they actual release the actual public and final version of the mods on their own site, they don't have this Custom Vehicle Type and use the standard Giants Categories.

**Comment by kylemeyer13** [comment]
That link came straight from their facebook page so??? I will have to change the vehicle type and see if everything works.

**Comment by kylemeyer13** [comment]
Well I have been testing out a few tractors with the custom vehicle type names changed to tractor and they seem to work well with courseplay but now I get all kinds of lua callstacks and they all go away as soon as I change the name back. So I highly doubt that custom vehicle types are going away.

**Comment by Kn1ghtwolf** [comment]
The other one is SiiD's 70 series combine it causes the same problem and The overkill truck and few other mods

**Comment by kylemeyer13** [comment]
Jhhg modding found a solution to the issue. The modders have to add a bit of code to their custom vehicle type in the modDesc. I can't remember what it is off the top of my head but I will post it in here when I get time to look.i have edited all the machines I was using like this and have multiple hours of game time with no errors.

**Comment by Kn1ghtwolf** [comment]
Okay, I've got like 4 or 5 things using custom vehicle types and it just causes the game to never save and I want to use em but I like courseplay better so it's gotta be cp before the others lol

**Comment by Tensuko** [comment]
Closing this one, as CP only gets into Vehicle when it can or something like that.
Should not Trouble your savegames anymore, but also can't use CP on that Vehicle then.
