### ISSUE TITLE
Can't save on The old stream farm - base.lua:1704: bad argument #1 to 'concat' (table expected, got nil) + LUA Callstack

### ISSUE THREAD

**Issue by davidgustavsson** [Courseplay/courseplay#3623]
I'm trying to start using courseplay. It seems to work but when I try to save the game it freezes and deletes the save file. It seems to works on other maps but this still happens on "The Old Stream Farm".

[log.txt](https://github.com/Courseplay/courseplay/files/3077223/log.txt)

**Comment by davidgustavsson** [comment]
Tested whit 184 - 187

**Comment by pseikoNL** [comment]
Can you test it with only the map ‘The old stream darm’ and CoursePlay as active mods? This to exclude other mods to interfere.

Kind regards,
PseikO

**Comment by Tensuko** [comment]
You got a lot of Mods with Errors in your logfile.
Clean this up 1st and try again.

**Comment by davidgustavsson** [comment]
Tested a new gamefile with coresplay and it worked. So it has to be some of the mods that I have bought in the earlier gamefile. Had the same mods but didn't buy anything.

**Comment by davidgustavsson** [comment]
I will test to se what mod it is and let you know. Thanks for the help.

**Comment by cwattyeso** [comment]
Looking at your log file, I see one Mod that is not compatible with courseplay and causes the save game freeze/crash and deleting of save game files issue that you are having. That is the Man IT Runner Truck Mod from the in game Giants Mod Hub. If you have that loaded you'll get the problem you are having. Remove that mod and it'll probably solve your problem, unless you have another faulty mod that's not been made courseplay compatible by the author.

**Comment by Tensuko** [comment]
Oh you are right, I haven't see it. Thank you!
Yes that Mod is screwed up. Take it out and test again.

**Comment by davidgustavsson** [comment]
Tested now, an you ware right. It is: MAN TGS ITRunner (https://www.farming-simulator.com/mod.php?lang=en&country=se&mod_id=123383&title=fs2019)

That's to bad - I like that truck. Is there something you can do to make it work or is it the Trucks mod author that has to to something? Maybe work together?

**Comment by Tensuko** [comment]
That is a Mod Issue. The Mod doesn't even support open the CP HUD, wich is not a CP problem, more a problem that the Modder not used the standart GIANTS Vehicle Types and stuff.

But there is another IT Runner Truck on the ModHub, you could try use that one.
Closed.

**Comment by davidgustavsson** [comment]
Ok, thank you for the help. I will use the other truck.
