### ISSUE TITLE
can't generate course 

### ISSUE THREAD

**Issue by pjr846** [Courseplay/courseplay#3624]
hi 
I can't generate any course. The menu  is different than usual.

**Comment by pvaiko** [comment]
What a helpful problem report...
https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
I think that is a kind of Issue like haven't read #3552

**Comment by pjr846** [comment]
Hi glad you liked it. 

So when I go to field work lats say to generate a harvest course instead of the usal menu that starts with field number, tool width and so on. I'm getting the following list: Lane offset, Turn on Field, Pathfining, Tool Offset Vertical And Opposite Turn Direction. Even the save icon is gone. and the gear icon to open the bigger page for the generator is on vacation as well.

Hope you enjoy this as well.
Jokes apart thanks for the great work guys.

**Comment by pjr846** [comment]
you was right from the start I din't read and went in panic mode sorry for wasting your time guys. 
thanks for the great work you do.

**Comment by Tensuko** [comment]
Closed.
