### ISSUE TITLE
Kleine Spikes und Lags in Mode Feldarbeit

### ISSUE THREAD

**Issue by Starkwood12345** [Courseplay/courseplay#3625]
Hi erstmal danke für diese Geile Modt es ist die beste in LS19.

zum Problem auf irgendwo in Thüringen 2 oder Celle die 4 Fach Maps habe ich immer Probleme bei der Feldarbeit.

Wenn ich den Fahrer einstelle erst dann fängt es an ein wenig zu ruckeln und Spikes. Obwohl 60 FPS ist.

Habe ein guten PC

Woran könnte das liegen Gruß

**Comment by Starkwood12345** [comment]
Auf der Marsch map habe ich überhaupt keine Probleme nur auf diesen zwei Maps Thüringen und Celle und ich würde so gerne 4 fach maps spielen mit Courseplay :)

**Comment by pseikoNL** [comment]
Can you upload your log and so on?

https://github.com/Courseplay/courseplay/wiki

Kind regards,
PseikO

**Comment by Tensuko** [comment]
Hast du immer nur eine Map im Modordner ?
Dies ist auch im LS19 eine wichtige Regel.
Und wie pseikoNL schon schrieb, ein Logfile als Anhang in die Kommentarbox bitte.

**Comment by Starkwood12345** [comment]
habe 6 maps in map ordner und ja ich suche gerade die Log :)

**Comment by Starkwood12345** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3077348/log.txt)

**Comment by Starkwood12345** [comment]
Habe auch mal probiert alle mods beim savegame am start obzuwählen und starten aber das problem ist leider trotzdem da

**Comment by Starkwood12345** [comment]
vllt liegt es ja an die 6 maps dann haue ich mal alle raus bis auf eine?

**Comment by Tensuko** [comment]
Mods nur abwählen bringt nichts.
Man muss die Mods rausnehmen.
Und ja, nur eine Map im Modordner.
Man muss dann halt ein wenig hin und herschieben.

**Comment by Starkwood12345** [comment]
ok teste das mit der einen map ! danke

**Comment by Tensuko** [comment]
2019-04-14 14:31 Error: Vehicle type 'AutoLoadWoodTrailer2' has unknown specialization 'realDirtColor'!

RealDirt als nächstes mal rausnehmen bitte.

**Comment by Starkwood12345** [comment]
Jap habe entfernt Real Dirt und auch alle Maps bis auf die Eine die ich jetzt spielen möchte ich melde mich :) danke schon mal

**Comment by Starkwood12345** [comment]
Habe gerade den Grubber aktiviert und wenn ich Fahrer einstellen drücke habe ich wieder leider so ganz kleine Spikes alle 3 sec ca.

:(

hier noch mal der neue log 
[log.txt](https://github.com/Courseplay/courseplay/files/3077411/log.txt)

**Comment by Tensuko** [comment]
Ist das immer beim gleichen Fahrzeug ?
Wenn ja welcher Traktor+Grubber

Ich weis leider nicht, was diese Zeile zu bedeuten hat:
2019-04-14 15:33 Warning: Mod-List download failed... retry in 2.000041 s. 0 trail

**Comment by Starkwood12345** [comment]
Nicht immer das Gleiche Fahrzeug egal ob Drescher oder Traktor mit Grubber wenn ich Fahrer einstellen drücke habe ich kleine Spikes.

**Comment by Starkwood12345** [comment]
wie gesagt auf marsch habe ich keine probleme leider nur auf 4 fach maps

**Comment by Tensuko** [comment]
Ich habe noch keine 4fach Map probiert.
Aber ich befürchte das wir da nichts dran machen können, da die LOG keine Fehler rausschmeißt, die auf CP hindeuten. Ich muss mal schauen ob ich das provoziert kriege.
Kann aber etwas dauern...

**Comment by Starkwood12345** [comment]
ich teste auch mal noch ein wenig rumm ! danke

**Comment by Starkwood12345** [comment]
kannst ja mal die irgendwo in thüringen map 2 downloaden und schauen ob du es auch hast

**Comment by Starkwood12345** [comment]
Habe rumm getestet egal welcher Traktor egal welcher Grubber. so bald ich fahrer einstelle drücke lagt es noch nicht direkt erst wenn der Grubber abgesenkt wird und er anfängt lagt es

**Comment by Starkwood12345** [comment]
Spiele gerade auf der 4 Fach Map Dondiego Map keine probleme keine lags alles flüssig.

Kann es sein das Courseplay nicht klar kommt mit den Feldern auf Maps die nicht Viereckig sind?

auf Dondiego Map sind die maps alle viereckig und leicht zu berechnen läuft super.

Auf Thüringen 2 oder Celle sind die Maps nicht Viereckig sondern alle anders verwinkelt. 

Kann es daran liegen warum ich Lags habe?

**Comment by Starkwood12345** [comment]
Ok habe eine Erfahrung gemacht die mir sagt es liegt nicht an Courseplay.

Auch wenn ich ohne Courseplay ohne Helfer alleine Grubbern will habe ich auch kleine Spikes sobald er ins Feld eintaucht.

Auch wenn ich Dresche habe ich kleine spikes sobald ich etwas mache aber nur auf die maps die ich spielen will -.-

Irgendwo in Thüringen 2 und Celle habe ich diese Probleme

Woran könnte es liegen?

**Comment by Tensuko** [comment]
Habs schon vermutet, dass es an der Map liegt.
Hier können wir dir damit aber nicht helfen. Ich würde dir vorschlagen, das Thema im Forum der LS-Modcompany mal anzusprechen, rein im bezug auf die Map und was du beobachtet hast.

Da es nichts mit CP zu tun hat, mache ich hier zu.
Closed.
