### ISSUE TITLE
Combine Harvester does not cut pocket

### ISSUE THREAD

**Issue by RUGhost** [Courseplay/courseplay#3628]
If I deactivate symmetric lane change, the harvester give me a space to unload him (picture-1) by pull back over the fruit (picture-2).
![1](https://user-images.githubusercontent.com/48012198/56093207-7121af00-5ee7-11e9-80e8-864f135e2452.png)
![2](https://user-images.githubusercontent.com/48012198/56093232-b7770e00-5ee7-11e9-9d16-4ce7f3049d63.png)

If I activate symmetric lane change to overcome this problem, they collide each other (picture-3&4).
![3](https://user-images.githubusercontent.com/48012198/56093262-fc02a980-5ee7-11e9-9655-b3b95714a307.png)
![4](https://user-images.githubusercontent.com/48012198/56093280-248aa380-5ee8-11e9-89e8-8e9a30298762.png)

**Comment by Tensuko** [comment]
I doubt we can do much about any of those situations.
The symmetric lane change on is not a solution for sure (don't even know what is that for, becosue of colide issue)

Symmetric lane change off is the right way, but what would you do in real life ? back up all the way out of the fruits ? I don't think we can do anything there. What is if you start the other Harvester 1st ? Then there should be free space or am I wrong.

**Comment by RUGhost** [comment]
Sending other harvester do the same. So it will be wise to deactivate symmetric lane change. But it would be nice if the combine cut a pocket (like picture-5) instead of just pullback.
![FarmingSimulator2019Game Screenshot 2019 04 14 - 19 44 25 78](https://user-images.githubusercontent.com/48012198/56093796-8948fc80-5eee-11e9-8240-4a6caab0a32d.png)

**Comment by seeske123** [comment]
In real life you go back 180 degrees , empty and then go on again. That is what I always did

**Comment by Th301** [comment]
Is the crash perhaps a result of the different width of the two implements?

**Comment by RUGhost** [comment]
@Th301 The width of two header are same. The actual cutting width of every header perhaps smaller than the width of header.  In my case, the width of the header is 13.7 meter but its cutting with is 13.5 meter. Thats why they collide. The beeter idea is deactivate symmetric lane change.

**Comment by Th301** [comment]
Looked like different sizes on some pictures.
But when using a smaller cutting-width as the real width of the header is to calculate the course, it is not a surpise that they collide.

**Comment by Lustiger-Hubi** [comment]
Question why don't you drive in the compound?
And then turn off the fruit bypass!
![fsScreen_2019_04_17_16_43_42](https://user-images.githubusercontent.com/48583507/56297214-3fe7ef80-6130-11e9-8d43-07aed8fff778.png)

**Comment by Tensuko** [comment]
Try with 198 or higher and report how it works now.

**Comment by pvaiko** [comment]
The original issues should now be fixed by the referenced commits.
