### ISSUE TITLE
Man kann seit der letzten ...

### ISSUE THREAD

**Issue by spielera** [Courseplay/courseplay#3629]
Hi Leute,
erst einmal ein großes Dankeschön, für eure Arbeit, macht weiter so.
Seit der letzten Version, kann man keine Kurse mehr generieren .
Wenn man auf diese Maske klickt, kommt der Inhalt, wo man die Bahnbreite usw. einstellen kann.

translated with Google!!!!

Hi guys,
First of all a big thank you, for your work, keep it up.
Since the last version, you can no longer generate courses.
If you click on this mask, the content comes, where you can adjust the web width, etc.

**Comment by pseikoNL** [comment]
Please read: #3552

Kind regards,
PseikO

**Comment by Tensuko** [comment]
#3552 
Closed.
