### ISSUE TITLE
The problem with the turn

### ISSUE THREAD

**Issue by Horozor** [Courseplay/courseplay#3630]
Ropa Tiger 6 during the shuttle movement makes many unnecessary movements during the turn. I hope you understand what the error is. My English is very bad sorry for that.
![fsScreen_2019_04_15_03_43_21](https://user-images.githubusercontent.com/37561569/56101885-19a83100-5f31-11e9-8cc4-5d89a38bb701.png)
![fsScreen_2019_04_15_03_43_28](https://user-images.githubusercontent.com/37561569/56101886-1a40c780-5f31-11e9-82ea-576eb3b8747f.png)
![fsScreen_2019_04_15_03_43_32](https://user-images.githubusercontent.com/37561569/56101887-1a40c780-5f31-11e9-8249-7c4f897e2914.png)
![fsScreen_2019_04_15_03_43_38](https://user-images.githubusercontent.com/37561569/56101888-1a40c780-5f31-11e9-9fbe-becde9e66f11.png)
![fsScreen_2019_04_15_03_43_43](https://user-images.githubusercontent.com/37561569/56101889-1a40c780-5f31-11e9-893b-94f90694e790.png)

**Comment by MeckyonTour** [comment]
Das liegt am Wendekreis, weil er Allrad-Lenkung hat, versuch den Wendekreis auf 8-10m zu begrenzen, dann läuft es besser.
LG

**Comment by Tensuko** [comment]
Liegt nicht nur am Wendekreis. Auch die Knicklenkung macht zu schaffen.
Momentan geht es nicht perfekt, mit dem Wendkreis ist aber ein guter Tip.

Mal so am Rande: Schonmal den GIANTS Helfer beim wenden Beobachtet ?

Da es momentan eher ein Bug von GIANTS ist, wird das hier erstmal wieder zu gemacht.
Das ganze ähnelt der #3538 auch wenn der Ursprung ein anderer ist.
Closed.
