### ISSUE TITLE
Collision detection 

### ISSUE THREAD

**Issue by TSperfeld** [Courseplay/courseplay#3631]
First of all thank you for your tedious work on Courseplay, in spite of everything I have a question.
Why do not the Coursplay vehicles detect obstacles or better Why is the collision detection active only in one field only when the vehicle drives to a harvester and as soon as it approaches the course again inactive?

**Comment by ThomasGaertner** [comment]
Can  you tell me an example? The collision detection is active on Street and fieldwork . I can imagine you mean  the bypasing Funktion to bypass e.g. Bales on the field . How should this one Look like on the Street ?

**Comment by Racker2409** [comment]
Maybe this will help.
![fsScreen_2019_04_16_11_48_10](https://user-images.githubusercontent.com/49451864/56199927-1ea6d680-603e-11e9-9f86-063cb432266f.png)
![fsScreen_2019_04_11_15_22_19](https://user-images.githubusercontent.com/49451864/56199937-26ff1180-603e-11e9-85df-48a58ceefc7c.png)

**Comment by Racker2409** [comment]
![fsScreen_2019_04_16_11_57_36](https://user-images.githubusercontent.com/49451864/56200405-0a170e00-603f-11e9-8965-2a9cc2d2f040.png)

**Comment by Racker2409** [comment]
![fsScreen_2019_04_16_12_00_53](https://user-images.githubusercontent.com/49451864/56200648-785bd080-603f-11e9-9947-1bf55d63751f.png)

**Comment by Tensuko** [comment]
Mode2 #3311
Try again when Mode2 is reworked.
Closed.

**Comment by Krahazik** [comment]
As far as I can tell, there is no collision detection in any mode. I am constantly having issue where vehicles are running into things and then attempting to drive through the solid object. Things like trees, houses, fences, sheds, silos, other vehicles, traffic, etc. Sometimes it appears the route planning is intentionally trying to drive into things in bizar ways.

In my latest batch of fiascos I am trying to setup a forage harvester to harvest grass with a tractor set on mode 2 (unload harvester) and the tractor and the tractor keeps running into trees on the side of the field on one end. Other times with the offset set on auto, it chooses a side of the harvester that garontees its on the inside of the headland course of the harvester, and thus garonteeing that when the harvester gets to the corner its going to turn into the tractor and trailor.

**Comment by Tensuko** [comment]
There is detection, just not for objects and mode2 is still under rework

**Comment by Krahazik** [comment]
Detection of objects would be usefull.
