### ISSUE TITLE
Drives to fast in BGA Silo

### ISSUE THREAD

**Issue by Mychomizer** [Courseplay/courseplay#3633]
Still seems to be a issue with the calculation of the correct speed to unload in a silo. Have had the same issue since I started using CP in FS19.

Sometimes it works, most of the time it dosen't.
Sometimes it works at first but after a few runs it suddenly stops again.
Restarting the game sometimes solves the issue for one trailer but then might brake the other.
I tried plenty of different tractors and trailer combinations both stock game and modded versions and the success rate are the same.
Tried on atleast 3 different maps with different kinds of silos + standard placeables
Tried with and without alot of script mods and others (RealDirt especially)

I have not found a connection to this problem so far.

When it dosen't work and the tractor drives at full speed it shows a negative reversing speed. If you sit ready in the tractor a work around is to be quick and scroll down the rev speed to desired. See img
![wrongspeed](https://user-images.githubusercontent.com/48811628/56153670-050e7c00-5fb7-11e9-93f4-217f1a4aab56.png)

log with debug 1+2 when the miscalculation happens
[log.txt](https://github.com/Courseplay/courseplay/files/3081471/log.txt)

**Comment by Tensuko** [comment]
Did you use Mode2 ?
If yes (and that what I expect) that doesn't work at all yet.
Only Mode6 use the speed calculation.

**Comment by Mychomizer** [comment]
Yes it's mode2. So that means it's not possible to chop corn in it's current state then? Thanks for a quick answer

**Comment by Tensuko** [comment]
Thats the case. Sry, close this 1st.
Closed.
