### ISSUE TITLE
Trailed harvesting tools working bad

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/courseplay#3634]
Hello! 
All the trailed harvesting tools (like Grimme SE260; ROPA Keiler 2, ROOSTER 604) working not good at the moment. You don´t have hud Page 1, so you can´´t call driver or set stop while unloading. Also headland turns are corrupt. Some tools dosn´t turn on field in up/down rows, but can reverse, and they do it in sharp headland corners and reverse driving with Grimme SE260 and ROPA Keiler 2 is bad there (Heavy stearing because the trailer is "Pending"

**Comment by Tensuko** [comment]
Similar to #3538
Closed.
