### ISSUE TITLE
Combine pullback

### ISSUE THREAD

**Issue by Emilioso007** [Courseplay/courseplay#3636]
When a harvester is full, and the pipe is in the crop, then is the calculations based on the header, indstead of the actual pipe on the harvester. I hope it makes sense.

**Comment by Tensuko** [comment]
I don't know what you want to tell us with that ? ...

**Comment by seeske123** [comment]
Back 180 degrees and then back again. You do not want to have a tractor between the combine and the fruits.Never make a pocket. Only in the first turn. Afeterwards 180 and then empty and q180 and continue

**Comment by pvaiko** [comment]
Unfortunately we still have no idea what you guys are talking about. If anyone of you is able to clearly describe what the issue is or what the suggestion is reopen this.
In the meanwhile, read through #3282 and watch this video https://www.youtube.com/watch?v=XCfo6EZvKeA&feature=youtu.be
