### ISSUE TITLE
EINBÖCK PNEUMATICSTAR 900 not recognized as a weeder

### ISSUE THREAD

**Issue by 51stHD** [Courseplay/courseplay#3637]
![fsScreen_2019_04_16_21_26_05](https://user-images.githubusercontent.com/47107082/56238626-3195c700-608f-11e9-9c09-8fd75566a5ad.png)
![fsScreen_2019_04_16_21_27_37](https://user-images.githubusercontent.com/47107082/56238629-35c1e480-608f-11e9-985c-73edafbf54ad.png)

**Comment by Tensuko** [comment]
deactivating the seed option is problematic: #3518

**Comment by ThomasGaertner** [comment]
can you use this tool empty manually without CP ?

**Comment by RUGhost** [comment]
This equipment doesn't need to be turned ON. You just need to lift down this implement (like cultivator) to work as weeder. If you turned ON it, then it will be worked as seeder.

**Comment by 51stHD** [comment]
> can you use this tool empty manually without CP ?

With the standard helper / hired hand?, if so the answer is yes.

**Comment by ThomasGaertner** [comment]
try v.205 or higher ...

**Comment by 51stHD** [comment]
That's fixed it.

Great job, thanks. It works just as I hoped it should and dare I say, better than than Giants helper, as it can now work as a seeder too :)
