### ISSUE TITLE
crop dont cover the cutter fully

### ISSUE THREAD

**Issue by kartal2339** [Courseplay/courseplay#3638]
i use a mod s785 with stevie 645fd cutter and when i harvest the crop dont cover the cutter fully .. 
![fsScreen_2019_04_17_00_36_21](https://user-images.githubusercontent.com/33800597/56246162-de7d3d80-60a9-11e9-8131-d85b2d4ce231.png)

**Comment by kartal2339** [comment]
my combination of cp is 6 headland , clockwise ,

**Comment by pvaiko** [comment]
That's because we have a few percent of overlap on the headland to make sure not to miss any fruit in corners.

**Comment by kartal2339** [comment]
thanks very much for your reply...
