### ISSUE TITLE
Just installed the latest edits and having this error.

### ISSUE THREAD

**Issue by westgate911** [Courseplay/courseplay#3639]
Error: C:/Users/Anthony/Documents/My Games/FarmingSimulator2019/mods/FS19_ZZZCourseplay/courseplay.lua:128: 	COURSEPLAY ERROR: could not load file C:/Users/Anthony/Documents/My Games/FarmingSimulator2019/mods/FS19_ZZZCourseplay/course-generator/Pathfinder.lua

**Comment by pvaiko** [comment]
Don't know where you got your copy of Courseplay, but you'd better not use that site anymore. Delete your FS19_ZZZCourseplay folder and install a proper release from https://github.com/Courseplay/courseplay/releases
