### ISSUE TITLE
Using Dev V189 - Can't see option to enable Plough/Work Past Field Edge 

### ISSUE THREAD

**Issue by cwattyeso** [Courseplay/courseplay#3640]
Using Dev Version 189 of Courseplay with the new HUD revision. I'm not finding an option on any of the tabs now when I have a Plough equipped to enable the 'Plough Past Field Edge' option that was in previous versions of courseplay. I am now seeing the problem again in game when Ploughing Fields that the worker will lift the plough well before he's reached the edge of the field and thus miss sections on every lane.

I also notice with other tools and equipment since this update they are also struggling to work correctly to the field edge and seem to stop quite short. Here is a screenshot with a Slurry/Digestate Spreader showing the issue and how far from the field edge it stops spreading on each lane.
![2019-04-17](https://user-images.githubusercontent.com/13921716/56286238-2a170200-6111-11e9-890c-93332cf8ba30.png)

I know the devs are currently and have recently been fine tuning some of the lift and lower points for tools and equipment. However I was wondering whether it may be possible to re-add the 'Plough Past Field Edge Option' but make it more of a universal 'Work Past Field Edge Option' so you can select it for use not just with Ploughs but any vehicles doing Field Work Courses or Seeding/Fertilise Courses to prevent this issue of them missing bits at the edges of fields on each lane.

**Comment by pvaiko** [comment]
Functionality still there just probably not on the HUD.
