### ISSUE TITLE
LUA Error turn.lua:541 - attempt to index local 'turnContext' (a nil value)

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#3644]
Hi! I have a Problem with the new Version 
FS19_CoursePlay6/turn.lua:541: attempt to index local 'turnContext' (a nil value)
2019-04-17 17:32 Error: Running LUA method 'update'.

LG

**Comment by pvaiko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Elgroo** [comment]
/turn.lua:541: attempt to index local 'turnContext' (a nil value)

Same problem. No new mod's, error with version 191

**Comment by pvaiko** [comment]
And it is the same problem with issue description as the previous one. Until the devs learn telepathy to figure out what exactly you were doing, why not read https://github.com/Courseplay/courseplay/wiki to find out how to provide a useful bug report...
