### ISSUE TITLE
Drescher/Abfahrer stoppen nicht am Feldrand beim Abtanken

### ISSUE THREAD

**Issue by Taktkonform** [Courseplay/courseplay#3645]
Ist eigentlich kein schwerwiegendes Problem, aber nervend. Drescher ruft Abfahrer, weil Trigger erreicht, stoppt aber nicht am Feldrand sondern fährt in die Wende, um dann mitten in der Wende das Stoppsignal zu bekommen. Beim LS17 war das noch so gelöst, dass der Abfahrer wartete, bis der Drescher die Wende vollendet hat, nun leider nicht mehr. Das führt regelmäßig zu einem Chaos am Feldrand, da der Abfahrer den Drescher in der Wende stoppt und versucht abzutanken.
Unter verschiedenen Einstellungen getestet, Fruchtumfahrung an/aus, Stopp beim Abtanken, das Ergebnis ist immer das Gleiche.

**Comment by Tensuko** [comment]
Drescher beim Abtanken anhalten in den Abfahrer Optionen aktivieren.
Ansonsten für Mode2 gillt noch immer #3311 

Closed.
