### ISSUE TITLE
Kann nur noch gespeicherte Kurse benutzen

### ISSUE THREAD

**Issue by Immi1971** [Courseplay/courseplay#3646]
Ich habe mir vor ein paar Minuten die letzte Version heruntergeladen und in den Modordner gepackt. Allerdings kann ich mit der neuen Version keine Feldbearbeitungskurse mehr erstellen.

**Comment by Tensuko** [comment]
Mehr Details bitte...
Wie genau meinst du das ?
Was fehlt ?
Was geht nicht mehr ?
Welche Schritte hast du gemacht ?
#3552 gelesen ?

Und ein logfile bitte. 
https://github.com/Courseplay/courseplay/wiki

**Comment by AugustinerOpA** [comment]
er hat wohl kein Arbeitsgerät am Traktor - ich hatte das auch schon mal übersehen. Das Icon für die Kurserstellung von Feldarbeiten färbt sich erst "weiß", wenn man ein Arbeitsgerät am Traktor hängt

**Comment by Tensuko** [comment]
Closed. Wenn es noch immer nicht geht, mache ich heir wieder auf, aber nur wenn es mehr Details gibt. Danke.
