### ISSUE TITLE
Fehler beim Beladen von Doppeltrailergespannen (Mode1+2)

### ISSUE THREAD

**Issue by Dirk78** [Courseplay/courseplay#3647]
Mein Trailergespann: **TKD302 + HKD302**
**Mode1:**
Beim Abfahren mit einem Doppeltrailergespann wird im ersten Durchlauf nur der erste Trailer befüllt, der zweite nicht.
Ab dem zweiten Durchlauf wird gar kein Trailer mehr befüllt und der Kurs wird einfach nur abgefahren, ohne be- und entladen.

**Mode2:**
Beim ersten Abtankzyklus eines Dreschers ist die Beladung ohne Probleme. Beide Trailer werden befüllt und im Silo abgeladen.
Im zweiten Zyklus wird beim Abtanken nur der zweite Trailer befüllt und der erste nicht. Sobald der zweite Trailer voll ist, wird abgefahren, obwohl der erste noch leer ist.
Im dritten Zyklus wird der erste Trailer wohl wieder erkannt und auch als erstes befüllt.
_Mehr Abtankyklen hatte ich bisher noch nicht gebraucht._

**Comment by Tensuko** [comment]
Beladen von nur einem Trailer klappt noch nicht, genauso funktioniert das Beladen bis X% nicht. (Mode1)

Was noch aufgefallen ist, es gibt Trailer die können nicht nach hinten abkippen, wenn ein weiterer Trailer abgehangen wurde (geht auch Manuell nicht!).

Auf Mode2 gehen wir erstmal nicht weiter ein, wird aber der gleiche Grund sein wie in Mode1.

**Comment by Tensuko** [comment]
Zu diesem Issue gibt es ein Update:
Das beladen im Mode1 funktioniert:
Zwischen Stop und Startpunkt muss so viel Platz sein, dass der zweite Trailer unter dem Trigger ist, bevor die Zugmaschine den Startpunkt erreicht hat.
Beladen bis X% ist allgemein bekannt und wird noch wieder aktiviert.

Der rest gehört zu Mode2 ( #3311 ).
Daher werde ich diesen Issue zu machen, alles weitere mit dem Mode2 rework release.
