### ISSUE TITLE
Couseplay showing as installed but when opening career save game it says it is not installed

### ISSUE THREAD

**Issue by Nifarmer** [Courseplay/courseplay#3648]
![Uploading Screenshot (1).png…]()
![Uploading Screenshot (2).png…]()

See screenshots. Have cloned/downloaded several times and rezipped and shows up as installed in my mods but second screenshot is what happens when I try to load my saved game.

**Comment by Nifarmer** [comment]
Shows as installed and works with a new career save game on same map (Marwell Manor)but existing save game doesn't reckonise this latest version.

**Comment by Tensuko** [comment]
logfile pls.
And you have to make sure only one CP Version is in your Modfolder.
What I also do is, deactivate all Mods per Button before loading, and activate them all again, to make sure all new Mods are getting loaded into my savegame.
When you got 2 CP Versions in your Modfolder, maybe you get error.
Your Pics are not loadable btw.

**Comment by Nifarmer** [comment]
I downloaded the latest update today and it’s working as normal. Must have been a minor  bug/glitch in last version.

**Comment by Tensuko** [comment]
Closed.
