### ISSUE TITLE
Cannot load The old stream with CP

### ISSUE THREAD

**Issue by Thesol157** [Courseplay/courseplay#3650]
[log.txt](https://github.com/Courseplay/courseplay/files/3091631/log.txt)

CP works as expected with every other map with all my mods.
and the map loads fine without CP enabled.

The log is me trying to load map with no mods, tough they are not removed from mod folder

**Comment by Tensuko** [comment]
Get the newest Version of CP here and try again:
https://github.com/Courseplay/courseplay/releases

You got a load Error in FS19_Fliegl_Flatbed_Square_Autoload
And something went wrong with your CP Folder I guess: (looks like p/P problem again)
2019-04-17 23:31 Error: C:/Users/joans/Documents/My Games/FarmingSimulator2019/mods/CourseplayBeta/courseplay.lua:128: 	COURSEPLAY ERROR: could not load file C:/Users/joans/Documents/My Games/FarmingSimulator2019/mods/CourseplayBeta/course-generator/Pathfinder.lua

Just download the latest version and just rename the zip file. No need to re-zip the file.

**Comment by Thesol157** [comment]
Thank you!

I used the link you gave me and downloaded the latest version, placed the mod in folder and deleted the faulty one.

Thank you again for your help.
