### ISSUE TITLE
Turn on field not working for some tools

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/courseplay#3653]
Hello!
Since always some tools won´t turn on field, even if the option is activated. It makes a big turn outside field (Like "turning on field" deactivated) I can post a log (With mods) if needed. It happens without any mods too. And yes, the tools are able to drive backwards

A list (it may be incomplete):
- Grimme SE260
- Grimme Rooster 604
- The 8 Meter "Tiefenlockerer"
- The Greatplains "single-corn" seeding machine
- All wheeled plows (The Agro Masz works)

When the vehicle turns in sharp headland turns reverse driving works.

**Comment by Tensuko** [comment]
Some tools doesn't have the option to do it.
Closed.
