### ISSUE TITLE
Just a question about headland to up-down row

### ISSUE THREAD

**Issue by crimso** [Courseplay/courseplay#3654]
Hello,

First I woould like thank you about your great work what you are making :)
I just want to ask:

![f1](https://user-images.githubusercontent.com/2950677/56384769-8b2bfc00-621d-11e9-9a53-e76d3c14465b.png)

![f3](https://user-images.githubusercontent.com/2950677/56385095-70a65280-621e-11e9-8097-1225b2df7e7c.png)

![f4](https://user-images.githubusercontent.com/2950677/56385116-7ef46e80-621e-11e9-876c-2486f12d087f.png)

As you can see in the picture, after finishing the second headland and the combi wants to start the up and down rows he need to make a sharper turn what will cause that it can not cut a bigger area.

But, almost the same turn in a up and down row is just working fine:

![f5,](https://user-images.githubusercontent.com/2950677/56385145-97fd1f80-621e-11e9-8320-4ae762ab8b67.png)

Maybe it is only my misstake that I add wrong data to generate the course.

Thank you

**Comment by Tensuko** [comment]
I had to learn that too: The solution is not to start a course at the Corner, when using Headlands.
Take arround the middle of the south side of the field and try again.
It should work much better, also we know that the move from headland to mid-part is not always perfekt.
Closing this, as this is not an Issue. Hope I could help you a bit.
Closed.
