### ISSUE TITLE
Absence of pause button

### ISSUE THREAD

**Issue by RUGhost** [Courseplay/courseplay#3655]
Pause button is absent in latest CP hud.
![Desktop Screenshot 2019 04 19 - 00 43 32 07](https://user-images.githubusercontent.com/48012198/56390579-2e950500-624e-11e9-8b93-b5f18d5231ed.png)

**Comment by Mannie313** [comment]
Muss er nicht erst ein paar wegpunkte haben um den Pausenknopf zu drücken.

MFG Mannie313

**Comment by Tensuko** [comment]
Somehow my answer got lost.
You need at least 4 Waypoints, currently, you got to klick on any Page or Mode Button to refresh the HUD, to get the Pause Button active, this is known already and will be fixed later.

**Comment by tuzlo** [comment]
I'm going to agree with Tensuko on this one,. Pause button is missing when recording courses.
