### ISSUE TITLE
trailer doesnt wait the harvester 

### ISSUE THREAD

**Issue by kartal2339** [Courseplay/courseplay#3657]
after unload the harvester trailer doesnt wait harester ..it starts turning and crash 
![fsScreen_2019_04_18_23_06_19](https://user-images.githubusercontent.com/33800597/56395299-b70da880-6242-11e9-8e07-dbfa1fd243d2.png)

**Comment by sootysax** [comment]
how many times must we reference #3311

**Comment by Tensuko** [comment]
This is Mode2 and still under rework.
#3311 Closed.
