### ISSUE TITLE
Verkehrserkennung

### ISSUE THREAD

**Issue by Chlous11** [Courseplay/courseplay#3658]
Wenn ein Fahrzeug im Silo ablädt fährt das nächste hinten auf. Ist es möglich das die Fahrzeuge sich erkennen?

**Comment by Tensuko** [comment]
Hört sich nach Mode2 an ? Abfahrer ?

**Comment by Chlous11** [comment]
Ja wenn ich im abfahren mod bin oder am startpunkt beladen. Die fahrzeuge erkennen sich nicht und fahren ineinander.

**Comment by Tensuko** [comment]
Mode2 wird noch neu geschrieben, daher wirst du noch warten müssen bis das richtig funktioniert, sry!
#3311 Closed.
