### ISSUE TITLE
Lime on Mode 4

### ISSUE THREAD

**Issue by jeremy3112** [Courseplay/courseplay#3659]
Hello,
I've found problems for lime on mode 4. With some tools it's impossible to start course cause caution appear with message ''need to be refill'' it's the same for pesticide with amazone panther.
With the old versions I do the job with the mode 6 and all work perfectly. Now it's impossible because the mode are locked when you have a specific tool attached
![image](https://user-images.githubusercontent.com/25390419/56415401-eeee0d80-628d-11e9-8e47-c5038e0c4aa0.png)

**Comment by Tensuko** [comment]
What are the tools for example ?
Amazone Panther I will check, what is this in the screenshot ?

**Comment by Mannie313** [comment]
Düngen, Spritzen, Güllen und Miststreuer Lass ich über Düngen und Sähen laufen. Ist das der modus 4 oder 6.

MFG Mannie313

**Comment by Mychomizer** [comment]
> What are the tools for example ?
> Amazone Panther I will check, what is this in the screenshot ?

I belive this is the one https://ls-portal.eu/new-leader-nl345-3/

**Comment by Tensuko** [comment]
@Mannie313 Mode4.

@Mychomizer when that one doesn't work with Mode4 then something is wrong with the mod I would say.

@jeremy3112 logfile pls.

**Comment by Tensuko** [comment]
Closeing becosue of inactivity.
If getting resposne with more details (and not so smal pciture and logfile etc) then reopen this.
Closed.
