### ISSUE TITLE
Krone BIG M450 Turn issue

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/courseplay#3661]
Hello!

I noticed that CP has Problems with Krone BIG M450. The mower in front drops down then v button is pressed, the side mowers about 1-2 Seconds later. CP does not recognize that and does not wait for the side mowers, equals unworked patches like in screenshot. Is it possible to fix this?
![Screenshot (2061)](https://user-images.githubusercontent.com/47073128/56425951-9b43ea00-62b6-11e9-8d64-dd59a34c916d.png)

**Comment by pvaiko** [comment]
We use the animation times to figure out when to start lowering the implements this one does not have the ones we use configured. Have another algorithm in there which measures the lowering times which could be used here but it had some issues and is currently disabled. Won't fix this now.

(Should work ok if there's a headland, btw.
