### ISSUE TITLE
Vehicles are not stopping for traffic

### ISSUE THREAD

**Issue by SmartAg** [Courseplay/courseplay#3662]

**Comment by SmartAg** [comment]
Instead of stopping and waiting for traffic to clear the machines just run into each other. I have not tested with AI traffic only other vehicles running CP.

**Comment by Mannie313** [comment]
Welcher modus????

MFG Mannie313

**Comment by Tensuko** [comment]
What situation and what Mode did you use when they run into each other ?

**Comment by Acrylic84** [comment]
Not Sure about SamrtAg, But for me if you set them to Combi Mode to unload/follow a Forage Harvester, they will ignore collisons.

**Comment by Tensuko** [comment]
The question is, if that happens in Mode2, if so, it is not supported yet and not an actual Issue untill Mode2 rework.

**Comment by SmartAg** [comment]
@Tensuko The main issues have been in combi mode. I am assuming that is mode2. If so and that is not supported yet we can close this issue.

**Comment by SmartAg** [comment]
Have confirmed that vehicles will run into each other in fieldwork mode as well as combi mode. See video.

https://youtu.be/ejCvXqu6dlU

**Comment by Tensuko** [comment]
What are you actually doing on that course ?
More details pls, as this is rly unnormal use of CP, at least it looks like it.
How does one of them drive in the wrong direction.

**Comment by SmartAg** [comment]
In this particular case it is a vehicle convoy of 4 tractors, based on the course generated the first pass is too narrow so the first tractor will run into the 2nd one after it turns around and heads back in the other direction.

**Comment by Electromech-YT** [comment]
![20190512011936_1](https://user-images.githubusercontent.com/50011356/57578397-63653800-7459-11e9-8585-382cc66676bf.jpg)
The combine rammed the tractor while avoiding this island.
The vehicles need to be more aware of what each other is doing

**Comment by Tensuko** [comment]
@Electromech-YT 
#3311 
The other thing with convoy and to narrow is a problem of in wich sequenze you start them.
Closed, but added to discuss in team.
