### ISSUE TITLE
Can't open HUD (Error: Running LUA method 'update'.)(attempt to index field 'activeBindings' )

### ISSUE THREAD

**Issue by mq1506** [Courseplay/courseplay#3663]
Hi, courseplay installed and loaded just fine. I get the "no courses loaded" prompt at the bottom of the screen. However I am unable to open the HUD with the default keybindings 

Things tried:
Resetting key bindings
deleted inputBinding.xml
changing the keybindings 

There are a couple errors that appear in the log file that appear to be related.  I've attached it below. 
[log.txt](https://github.com/Courseplay/courseplay/files/3099643/log.txt)

I typically use FS19 with a xbox one controller but disconnecting it and restarting doesn't appear to make a difference.

**Comment by jan12342203** [comment]
Do you have both courseplay versions active at the same time?

**Comment by Tensuko** [comment]
Load mod: FS19_Courseplay (Version: 6.01.00175) (Hash: 24088077d6d1ca116f821a22c463d8b1)
Load mod: FS19_CourseplayLv (Version: 6.01.00194) (Hash: 79abf8a7437b3b4806c3041095139cb4)

2 CP Versions in Folder.
Delete one and try again. Little Tip from my Side: Always name the File the same way, so you will always overwrite the old one.

**Comment by KarwendelHopper** [comment]
"hud.lua:465: attempt to index a nil value"

Diesen Fehler habe ich auch. Kommt nur manchmal. Passiert mir, wenn ich einen Kurs den ich einmal eingefahren habe, lade. Dann wird das HUD unsichtbar. Das Problem kann ich manchmal beheben wenn ich Anhänger dann abkupple.

Kann mir jemand helfen?
[log.txt](https://github.com/Courseplay/courseplay/files/3099894/log.txt)

**Comment by Tensuko** [comment]
@KarwendelHopper 
Mach dafür bitte mal ein neues Issue auf, den Fehler kenne ich zwar schon, aber noch nicht rausgefunden wie ich den reproduzieren kann.

**Comment by KarwendelHopper** [comment]
ok

**Comment by mq1506** [comment]
Sorry, I should have mentioned I only installed the older version as an attempt to resolve the issue. I gave the original a different name in case I wanted to revert to the latest version. Deleting one does not solve the issue. I've attached the updated log. 
[log.txt](https://github.com/Courseplay/courseplay/files/3100887/log.txt)

**Comment by Tensuko** [comment]
Try again to reset your keybindings (don't forget to save it after you did it) and reload the whole game again....
Can't get why there are so many LUA I guess couse you had a lot of inputs twice with same target or anything.

**Comment by KRoover** [comment]
Same problem here. Can't open hud or zoom out. Only CP installed, no other mod.
I Tried reseting keybindings, saving and reloading the game, but no success.
[log.txt](https://github.com/Courseplay/courseplay/files/3105645/log.txt)
.

**Comment by KRoover** [comment]
> Can you try to delete all inputs for CP, save and reload ?
> An other Idea is, any Joystick or GamePad attached ?

Hi there. I did as you asked, deletede all CP keybindings in the keybinding page, saved and quit the game. When I went back, all CP keybindings were automatically reseted. I did the process again, but instead of quiting the game, I loaded my very fresh savegame, but no success, same error again, cant open de HUD neither zoom in or out. Everything else works fine.
Game and CP are fresh installed, no other mods installed.
![Desktop Screenshot 2019 04 23 - 13 36 57 78](https://user-images.githubusercontent.com/10836276/56600071-4d88f380-65ce-11e9-9159-667bf31d7adc.png)

**Comment by Tensuko** [comment]
Hmm the last Idea I got is, you remove the inputBinding.xml and start the game again and let the game settle all keybindings by itself....

**Comment by KRoover** [comment]
Yeah... already did that, but the result was the same as before.
However, I found something new in my log.txt. Although I disabled all joystick and gamepad options, my log still shows that these options are active.
[gamesettings + log.zip](https://github.com/Courseplay/courseplay/files/3108768/gamesettings.%2B.log.zip)

**Comment by Tensuko** [comment]
Is your Error still happening with V208 ?
Just need a quick update if you managed to solve it somehow, as I can't rly see the problem you got.

**Comment by Tensuko** [comment]
Closed couse of inactivity.
