### ISSUE TITLE
/hud.lua:465: attempt to index a nil value

### ISSUE THREAD

**Issue by KarwendelHopper** [Courseplay/courseplay#3664]
Hallo.

Ich benutze die letzte Version von CP :....00194.

Diese Meldung im Log erhalte ich öfter, wenn ich in einem Fahrzeug einen Kurs laden möchte. Es erscheinen die Wegpunkte aber das HUD verschwindet und wird unsichtbar.

Oftmals kann ich das HUD wieder erscheinen lassen wenn ich ein an den Traktor befestigtes Anbaugerät abkuppel und anschliesend direkt wieder ankuppel. Dann erscheint das HUD wieder und ich benutze CP wieder ganz normal.
EDIT: Geht natürlich nur wenn ich was abkuppeln kann! Wenn ich nur das Fahrzeug fahren will mit Überfuhrungskurs dann bin ich hilflos und HUD ist weg!! (QUIT Game und Neustart)

Ein weiterer Fehler der mir auf der Felsbrunn Standart Map aufgefallen ist, wenn ich einen Beladung am Startpunktkurs eingestellt habe( in diesem Fall ein Traktor mit Fass um Gärreste von der BGA abzuholen und zu beladen), habe ich den Fehler z.B dann an allen Punkten die ich benutzen kann wie Kärcherreiniger das ich sobald ich dort "R" drücke Gärreste überladen "könnte". Vom Kärcher? ;-) 

Evtl. kann mir jemand helfen? Unsichtbares Hud ist blöd .
[log.txt](https://github.com/Courseplay/courseplay/files/3099914/log.txt)

**Comment by Tensuko** [comment]
Ich habe das eher, wenn ich mein Spielstand geladen habe und dann in einen Traktor wechsel und einen Kurs lade. So wenn ich im Spiel bin bisher noch nicht.
Wäre nett wenn du uns noch weitere Erfahrungen mitteielst, dass wir das noch etwas eingrenzen können.

**Comment by KarwendelHopper** [comment]
Ok werde ich.

**Comment by Beardman89** [comment]
Ich habe genau das gleiche Problem, sobald ich den Kurs für die Sähmaschine lade verschwindet das HUD und ich kann nichts mehr machen.

[log.txt](https://github.com/Courseplay/courseplay/files/3106916/log.txt)

**Comment by Tensuko** [comment]
Sehr altes Issue, könnte behoben sein mit der neuesten Version V288 oder höher.
Wenn nicht, neues Issue bitte.
Closed.
