### ISSUE TITLE
Headland Corner Fine Tuning

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/courseplay#3665]
![Screenshot (2094)](https://user-images.githubusercontent.com/47073128/56455670-69d42880-6361-11e9-9b9b-4e6aff56321c.png)

Hello!
The Grimme Compacta 6 Meter Potato Seeder has still a probloem in sharp headland cornes. 250fdf9 has improved it a bit, but he still leaves smal unworked patches in the headland corners. I will post a picture later.

**Comment by pvaiko** [comment]
How about f7f841fb4aa0369b017ce607cb59d7e37984180a? (198)

**Comment by pvaiko** [comment]
Closed due to inactivity.

**Comment by pvaiko** [comment]
Don't know what else can I do, work fine with me:
![image](https://user-images.githubusercontent.com/2379521/57449931-c5882800-7222-11e9-8b39-66933e8ad21b.png)

**Comment by StefanBraun2001** [comment]
Hmm, maybe the rason isthat the field is not flat, it is tilted... Tested it on a flat field and tada it works...
