### ISSUE TITLE
Drescher und Abfahrer Rammen sich

### ISSUE THREAD

**Issue by Strawberry93** [Courseplay/courseplay#3666]
Wenn ein Drescher nicht auf dem Feld abgeladen wird sondern beim Wenden fährt er danach Random irgendwo hin.

**Comment by Tensuko** [comment]
Logfile ?
Mit Mode2 autmatisch abgeladen ?
Screenshot ?

**Comment by Strawberry93** [comment]
Ich habe das nicht mehr reproduziert bekommen. Ich habe dies jetzt so gemacht das der Abfahrer erst bei vollen Drescher Tank abholen fährt, Danach passiert aber da
![2019-04-21 (5)](https://user-images.githubusercontent.com/16910900/56468028-e4b34700-6426-11e9-89cb-1b0a9dc241ee.png)
![Uploading 2019-04-21 (4).png…]()

s:

**Comment by Tensuko** [comment]
Das ist #3311 wie gehabt... Abfehrer fuktioniert noch nicht richtig, bzw wird neu gemacht.
