### ISSUE TITLE
Can't follow sharp turns with offset and high working width

### ISSUE THREAD

**Issue by sesmo** [Courseplay/courseplay#3667]
The tractor moves forward when changing the from the vertical lines to the headline.

In this case the tractor of the rigth side did the course with no problems.

It happens sometimes, not always.

Here are the video:

https://youtu.be/feOrrnutHGo
[log.txt](https://github.com/Courseplay/courseplay/files/3100311/log.txt)

**Comment by Tensuko** [comment]
I just had the same Issue with single use of my Course.
But I think that was on a normal turn with a LUA in turn.lua:1713 iirc.
We look into this and see if we find the issue. Thx.

**Comment by pvaiko** [comment]
I need that course.

**Comment by sesmo** [comment]
Here the course :  <slot fileName="courseStorage0010.xml" isUsed="true" id="57" parent="2" name="Campo #2 Trabalhos"/>

download of the courses and the map if you need:

https://drive.google.com/open?id=19Nt22MBYMVlZWsQ95rgQwMkmpsFPF_BK

**Comment by pvaiko** [comment]
@sesmo can't do much on that map without a savegame, it doesn't even have a proper map, have no time trying to figure out how to get to the field...

**Comment by Tezzward** [comment]
pvaiko, here are the courses and savegame that you asked for in the other thread.  

[savegame5.zip](https://github.com/Courseplay/courseplay/files/3198175/savegame5.zip)
[FS19_MidwestHorizon.SampleModMap.zip](https://github.com/Courseplay/courseplay/files/3198176/FS19_MidwestHorizon.SampleModMap.zip)

**Comment by pvaiko** [comment]
@Tezzward I'm sorry but I have those two JCBs standing there with nothing attached and no idea what mod I may be missing.

**Comment by Tezzward** [comment]
The Anderson DLC solid fertilizer spreaders.  36 meter work width

**Comment by pvaiko** [comment]
With 225 vehicles should now stay on course.
