### ISSUE TITLE
problem mit cp

### ISSUE THREAD

**Issue by nbsimulation** [Courseplay/courseplay#3668]
ich kann unter feldarbeit kursgenerriren keinen kurs erstellen was tun????

**Comment by pseikoNL** [comment]
Do you have a ball of glass for all of us? Otherwise please provide a couple of screenshots of the actions you do in the CoursePlay HUD.

Kind regards,
PseikO

**Comment by nbsimulation** [comment]
wie kann ich ein screenshot schicken?

**Comment by Tensuko** [comment]
#3552 lesen
Gerät anhängen, Mode4 oder 6 auswählen, Kursgenerator wie beschrieben starten.
Wenn du den Generator dann noch immer nicht gestartet kirgst, logfile bitte per drag and drop in die Kommentarbox (genauso kannst du auch Screenshots hier hochladen).

**Comment by nbsimulation** [comment]
Es ist alles angehängt welche Log willst du habe noch nicht viel mit cp
gearbeitet

Tensuko <notifications@github.com> schrieb am Sa., 20. Apr. 2019, 19:33:

**Comment by nbsimulation** [comment]
![fsScreen_2019_04_20_19_25_44](https://user-images.githubusercontent.com/49818028/56460499-fc95b700-63a3-11e9-92dc-79c1e91cf7fd.png)
![Uploading fsScreen_2019_04_20_19_25_40.png…]()

**Comment by nbsimulation** [comment]
welche logfile brauchst du und wo finde ich die

**Comment by nbsimulation** [comment]
![fsScreen_2019_04_20_19_25_40](https://user-images.githubusercontent.com/49818028/56460541-9d847200-63a4-11e9-8464-f7f8dc2b1016.png)

**Comment by nbsimulation** [comment]
da sind beide

**Comment by Tensuko** [comment]
#3552 <- lesen Und auf dem letzten Bild steht doch 'Kursgenerierung...'
Fürs nächste mal: https://github.com/Courseplay/courseplay/wiki (abte bitte per drag and drop anhängen).
Closed.

**Comment by nbsimulation** [comment]
ich kann aber keinen generiren siehe bild 1

**Comment by Tensuko** [comment]
Bild 1 zeigt mir das Menü zum Einstellen vom Versatz usw.
Das hat nichts mit dem Kursgenerator zu tun, desshalb LESEN: #3552

**Comment by nbsimulation** [comment]
Dass kommt aber wenn ich auf kursgenerriren klicke

Tensuko <notifications@github.com> schrieb am Sa., 20. Apr. 2019, 20:08:

**Comment by Tensuko** [comment]
Ich habe noch immer kein logfile von dir.
Bei allen funktioniert es.
Lade sonst cp mal neu runter oder schmeiß das alte raus https://github.com/Courseplay/courseplay/releases/tag/6.01.00194

**Comment by nbsimulation** [comment]
Wo finde ich die Logfile

Habe ich schon bringt nichts

Tensuko <notifications@github.com> schrieb am So., 21. Apr. 2019, 10:06:

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by nbsimulation** [comment]
Mach ich gleich später

Tensuko <notifications@github.com> schrieb am So., 21. Apr. 2019, 10:32:

**Comment by nbsimulation** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3101055/log.txt)

**Comment by nbsimulation** [comment]
da

**Comment by Tensuko** [comment]
1) Immer nur eine Map im Modordner
2) Eine menge Mods mit Errors, erstmal aufräumen bitte
3) Vermute Modkonflikt

Du kannst es auch erstmal so probieren, indem du deinen Mods ordner umbenennst, einen neuen erstellst und da nur CP rein packst. Dann ein neues Savegame starten und schauen ob es da funktioniert.
(Muss es eigentlich....)

Aber damit wir uns auch richtig verstehen, du klickst mit der Maus auf den Text 'Kursgenerierung...' richtig ?

**Comment by nbsimulation** [comment]
Ja richtig mach ich gleich mal wie erkenne ich Fehler mods in der Log

Tensuko <notifications@github.com> schrieb am So., 21. Apr. 2019, 11:07:

**Comment by nbsimulation** [comment]
jetzt gehts danke
