### ISSUE TITLE
Missions with CP

### ISSUE THREAD

**Issue by Peppobrasil** [Courseplay/courseplay#3670]

**Comment by Peppobrasil** [comment]
If I collect the money without canceling the completed path, the completed path message remains indefinitely.

**Comment by Tensuko** [comment]
I don't understand what you actually talking about.
Can you give more details what you did and maybe add a Screenshot and a logfile ?

**Comment by Peppobrasil** [comment]
Sorry for my English.
I think this is only a fine tuning.
I create a path for a mission. The path ends and a blue message appears that a path is finished. If I don't clear the path in the HUD, but go to the mission screen to collect the prize, the blue message remains forever. It only disappears with a new reboot of FS.

**Comment by Tensuko** [comment]
Ah ok, thx for explaining! :)

**Comment by Tensuko** [comment]
When Mission is finished and completed it.
Message won't disappear, also Rent Vehicles are gone and when click that Msg got LUA Error:
2019-12-30 19:12 Error: Running LUA method 'mouseEvent'.
2019-12-30 19:12 dataS/scripts/BaseMission.lua(1881) : attempt to index field 'controlledVehicle' (a nil value)

So Still Valid with V353+

**Comment by pvaiko** [comment]
Last time I tried a mission this worked fine.
