### ISSUE TITLE
Mode 4: Issues with spreader Bredal K165 (not  #3641)

### ISSUE THREAD

**Issue by XPiRiJenZ** [Courseplay/courseplay#3671]
Hi all!

Scenario: spread lime on field and refill spreader
Driver: Standard tractor with front weight
Spreader: Standard spreader Bredal K165, 18m work width
CP-Version: 0191

Map: Zweisternhof_GP (https://www.modhoster.de/mods/zweisternhof) with combined fields 9, 10, 11)

I recognized that the driver starts the tool at the end of refilling course instead of last point of field work, before the spreader was empty.
Also it starts (sometimes) the spreader when in turning maneuver when changing field lanes
(please see video: https://www.youtube.com/watch?v=g5g2gGN8HAw)

Log file: 
[log.txt](https://github.com/Courseplay/courseplay/files/3101079/log.txt)

**Comment by Tensuko** [comment]
Wie man sieht, passiert das ja nicht immer. Merkwürdig.
Ich nutze den gleichen Streuer und habe auch ein Kurs mit 2 oder 3 Vorgewende, aber beim Turn Streuer an ist mir bisher noch nicht untergekommen.

**Comment by XPiRiJenZ** [comment]
Version: 0196

Problem beim Turn-Maneuver behoben
Abfahrer fängt immer noch am Ende des Auffüll-Kurses an zu streuen und fährt dann zum letzten aktuellen Wegpunkt der Feldarbeit, um dort die Arbeit fortzusetzen.

**Comment by Tensuko** [comment]
Ok danke für die Info!

**Comment by pvaiko** [comment]
@XPiRiJenZ ich brauche ein Log mit 12 und 14. (Ich weiss dass 17 für Mode 4/6 gedacht ist, werden wir ändern, aber momentan ist 14 das wichtigste)

**Comment by XPiRiJenZ** [comment]
Here we go:

Log: [log.txt](https://github.com/Courseplay/courseplay/files/3107403/log.txt)

Video: https://gaming.youtube.com/watch?v=sBy2kvpXaYg

Selbes Spiel wie zu Beginn des Reports:
Spielstand frisch geladen und Abfahrer eingestellt -> Wende ohne Zwischenfall
Abfahrer fährt zum Auffüllen und kommt zurück -> Gerät wird deutlich zu früh eingeschaltet.



Habe versucht das ganze auf einer Standard-Map zu verifizieren (Ravenport, Feld 12), aber siehe da: hier funktioniert alles einwandfrei: https://www.youtube.com/watch?v=EsNzY53MghI

Log: [log.txt](https://github.com/Courseplay/courseplay/files/3107490/log.txt)


Werde den ersten Spielstand mal auseinander nehmen und gucken, ob es ein Modkonflikt ist oder an den zusammengelegten Feldern liegt.

**Comment by pvaiko** [comment]
Das mit dem zu früh einschalten beim Wenden ist ein Bug.  

Das mit einschalten nach Auffüllen ist evt. auch aber wenn Du die Fruchtumfahrung oder wenigstens die Alignment (1. Punkt gerade anfahren) einschaltest dürfte nicht mehr passieren.

Warum eigentlich endet dein Auffülkurs mitten im Feld (und nicht am Feldrand)?

**Comment by XPiRiJenZ** [comment]
@pvaiko 
Deswegen: 
![fsScreen_2019_04_24_18_00_16](https://user-images.githubusercontent.com/43669988/56674830-062c6100-66bb-11e9-9ec7-10dbd3916fff.png)


Die Punkte, so wie ich es auf der Feldmitte handhabe, sind von jeder Position auf dem Feld erreichbar. Gerade wenn es Felder mit L-Form o. ä. und Bebauung am Feldrand sind, hat CP ja immer so seine Probleme gehabt und ich hab mir das so angewöhnt.
CP findet den Punkt leicht -> weniger Kopfschmerzen bzw. graue Haare für mich ;)

**Comment by Tensuko** [comment]
Wenn Pathfinding wieder wir im LS 17 läuft ist das egal. Der hat bei mir sogar bei einem U Feld die hintere Ecke gefunden.

**Comment by pvaiko** [comment]
@XPiRiJenZ wenn du Fruchtumfahrung einschaltest und das Gebäude nicht auf dem Feld steht muss es funktionieren.

**Comment by pvaiko** [comment]
Im mode 4 und 6 funktioniert Pathfinding schon seit länger in FS19.

**Comment by Tensuko** [comment]
Ok ich wusste jetzt nur nicht wie weit es ausgebaut ist, da ich das noch nicht ausgereizt hatte.

**Comment by XPiRiJenZ** [comment]
@pvaiko 
ja, gut und schön... was ist mit den Leuten, die Fruchtumfahrung nicht nutzen (ich z.B.), haben die dann gelitten? Wenn man einen "schönen" Kurs zum Auffüllen haben will, dann wird man ja fast genötigt Fruchtumnfahrung zu aktivieren... dann kann man es ja auch gleich fix machen...

**Comment by pvaiko** [comment]
@XPiRiJenZ wovon reden wir jetzt eigentlich? Die Bugs werden behoben, es wird kein frühes Einschalten mehr geben, egal ob mit oder ohne Fruchtumfahrung.

**Comment by XPiRiJenZ** [comment]
@pvaiko Alles gut! Ich war jetzt beim Auffüllkurs und deiner Frage, warum ich den Kurs auf dem Feld beginne. The rest is done, when it's done :)

**Comment by pvaiko** [comment]
Probier's mit 197 (3252242e7d8ae35dd7f806758b874189d50c989f ).

**Comment by XPiRiJenZ** [comment]
Getestet mit 198 und läuft einwandfrei!

**Comment by Tensuko** [comment]
Closed.
