### ISSUE TITLE
New Holland 313 Discbine change side like a plow

### ISSUE THREAD

**Issue by jobyrns72** [Courseplay/courseplay#3674]
Hello! I was wondering since the new Holland 313 mower cuts from either side if it was possible in back and forth mode to have the mower cut to the side that the tractor would be outside of the crop and not running it over. Thanks!

**Comment by Tensuko** [comment]
Can CP drive in reverse with that Mower ?

**Comment by jobyrns72** [comment]
Yea might not be the easiest for it unless it’s centered when it backs ip
