### ISSUE TITLE
Issue with 6.01.00195 - close combine and cutter, but there is still something in the bunker

### ISSUE THREAD

**Issue by caplink811** [Courseplay/courseplay#3675]
When CP finshed it goes back to the startpoint, what is ok, but within the movemet it unfold the draper, and close the binker of the combine and fold the pipe although still harvested grain in it. The pipe can't move anymore, and the couldn't open as well. So it is necssary to reset the combine, which results in a lost of thje harvest.

**Comment by pvaiko** [comment]
No need to reset, just unfold and then pipe out. 

Will fix it with #3158

**Comment by caplink811** [comment]
thanks for the latter.
That was my assumption too, but at least with the case 9240 (imho) it wouldn't work. But with some kind of JD harvester it worked on another field.
