### ISSUE TITLE
Combi (Empty combine and offload)

### ISSUE THREAD

**Issue by RayzerSharpe** [Courseplay/courseplay#3676]
Very small issue. When combine is finished a field i usually driver it the next field. I usually drive past the waiting tractor and trailer to empty the remainder of the grain.  However as soon as i start unloading the tractor flies off and go around in a big ring and come back to roughly the same spot. Its obvious recalculating its unload position but should it be set not to recalc if its getting filled

**Comment by Tensuko** [comment]
Sounds like you run the Tractor in Mode2, wich is a case of #3311

**Comment by RayzerSharpe** [comment]
apologies..i keep forgetting
