### ISSUE TITLE
Mode 2 Verursacht immer noch leider Kollisionen 

### ISSUE THREAD

**Issue by Starkwood12345** [Courseplay/courseplay#3677]
Hi weiß habe es schon mal geschrieben.

Wann ist das so ca gefixt erstmal nochmal danke für diese geile modt!!!

Also Wenn ich einstelle Drescher Abtanken ect tut er meist alles umrasen was aufm weg ist auch bei Feldarbeit sähen.  Er sieht den Traktor schon es steht auch links einmal kurz da steckt im verkehr fest aber er stopt nicht er fährt einfach drauf zu und die verkeilen dann und nix geht mehr :/

Auch bei der Drescher Ablade Funktion tut mein Traktor danach einfach manchmal direkt los fahren und einfach in den Drescher rein :/

Glaube alle Modes haben noch keine Kollisions Erkennung oder=?

**Comment by game455** [comment]
Der Abfahrer fährt, wenn der 1. Punkt des Kurses VOR dem Drescher liegt direkt drauf zu = Kollision, wenn es zur Drescherseite geht. Liegt er hinter dem Drescher, dann dreht er immer nach der Überladeseite des Dreschers weg = keine Kollision
Beim Einfahren des Abfahrerkurses vielleicht einfach mal das Hirn einschalten, statt hier rum zu drängeln.
Sorry, musste mal sein.
DevTeam - ihr macht einen super job. Lasst euchnicht aus der Ruhe bringen

**Comment by Starkwood12345** [comment]
Wenn ich mein Grubber zum beispiel auf Feldarbeit gestellt habe. 

Fährt mein Grubber einfach auf ein Traktor der auch aufn Feld steht weil er dort wartet bis Drescher Füllstand erreicht ist.

Er wartet ja dafür aufn Feld ?

Was kann ich dagegen machen? der Grubber Fahrer fährt alles um was ihn im weg kommt?

**Comment by game455** [comment]
Einfach etwas mehr Geduld aufbringen. Zuviel Verkehr auf dem Feld macht immer Probleme, das war auch vorher schon so

**Comment by Starkwood12345** [comment]
Wie meinst du das mit den Ersten Punkt kannst das genauer erklären bitte wäre dir sehr verbunden dafür.


Stelle mein Drescher immer ein auf 3 Runden vorgewende also fährt er 3x im Kreis dann fährt er an hoch und Runter zu fahren. Dann liegt ja der Punkt immer links oder Rechts also das Rohr.

Wo muss dann der Abfahr Kurs erstellt werden Optional? fange immer mittig neben Feld an?

**Comment by Tensuko** [comment]
#3311 
Closed.
