### ISSUE TITLE
Change to tracking

### ISSUE THREAD

**Issue by shane101978** [Courseplay/courseplay#3678]
Would it be beneficial to change the turn maneuver at the end of the field from square to rounded?  It's just a thought.

   
![Farming Simulator 19 4_21_2019 7_20_31 PM](https://user-images.githubusercontent.com/46532864/56476838-cb80b980-646b-11e9-941c-9b060d1d26b3.png)

![round](https://user-images.githubusercontent.com/46532864/56476852-ff5bdf00-646b-11e9-85a5-ca775ba28978.jpg)

**Comment by Tensuko** [comment]
Headland - Mid Strategie: Circle or Spiral, try it out.
Won't change anything on that normal turn, except some turn manuver rework (MAYBE!!)
Closed.
