### ISSUE TITLE
Bearbeiten Button

### ISSUE THREAD

**Issue by OberstRudel** [Courseplay/courseplay#3679]
Wäre es möglich ein Button einzubauen wo man später nochmal die Kurse bearbeiten kann?? MFG

**Comment by Tensuko** [comment]
Das wird so nicht machbar sein, da die Punkte von einem Punkt des Traktors aus gemacht werden.
Es gibt ein Projekt den sogenannten CP Editor: https://www.modhoster.de/mods/courseplay-6-editor-osm-converter-fur-ls19

Closed.

**Comment by OberstRudel** [comment]
Danke. würde ja schon reichen wenn der Kurs von gespeicht zurück in den zustand bringt bevor man die aufzeichnung gestopt hat. mfg Schöne Ostern euch noch.
