### ISSUE TITLE
Reversing Issues with Stara Estrela 32 in Generated Course

### ISSUE THREAD

**Issue by buden3000** [Courseplay/courseplay#3683]
When Trying to reverse in the row end turn the tractor jack knifes the seeder. Currently using cp build 194, Tractor was JD 8400R with rear duals, pulling Stara Estrela 32. Did manage to mittigate the issue by using the row skip set at 2 (less lining up to do so less reversing). Let me know if you need more info ect.

**Comment by Tensuko** [comment]
Turn on field deactivated is not an option ? With Headlands ofc.

**Comment by buden3000** [comment]
Nope, to many trees in the hedge rows.... so turn on field active, field is square and not very big so not practical to have more than 1 headland pass around. (F15 on Marwell Manor if your wondering)

**Comment by Tensuko** [comment]
I would have a solution for you, but there is just some tweaking left....
![F15](https://user-images.githubusercontent.com/27344744/56510523-5c1dcf00-652a-11e9-9f0e-5d56e7ce41d3.png)

@pvaiko possible to do something about that? The Tool gets lift up to early/transmission course starts to early.
![fsScreen_2019_04_22_18_08_42](https://user-images.githubusercontent.com/27344744/56510526-5de79280-652a-11e9-869f-5b6205509336.png)

Lifting up now:
![fsScreen_2019_04_22_18_10_21](https://user-images.githubusercontent.com/27344744/56510583-896a7d00-652a-11e9-9ad0-01aaa4c80ba6.png)

**Comment by Tensuko** [comment]
Oh beside that, reverse looked fine at least for 90° turn.
![fsScreen_2019_04_22_18_04_51](https://user-images.githubusercontent.com/27344744/56510648-b1f27700-652a-11e9-8462-9ce58ce67000.png)
![fsScreen_2019_04_22_18_04_29](https://user-images.githubusercontent.com/27344744/56510649-b1f27700-652a-11e9-8bce-6791301f18f6.png)

**Comment by pvaiko** [comment]
@Tensuko that mode works really only for rectangular field. Why don't you try the spiral or racetrack?

**Comment by buden3000** [comment]
I've messed about trying to recreate the situation and it now behaves so all i can think is it had something to do with the start point i chose.....?

**Comment by Tensuko** [comment]
You mean it works fine now ?
You could try more, like 1 Headland and then go for spiral or something. But I must say Spiral and Circle are not much perfect yet. I tried it with skip row now on my savegame and that looked good.

**Comment by buden3000** [comment]
yeah, even with no skip row it managed to not jack knife, it's not a very pretty reverse but it does the job. Think there may be some fine tuning to look at for the reversing of longer tools such as the estrela and also noticed the amazon condor has a bit of an odd reverse going on too at the headland. to clarify they both reverse fine at the row end, perform the turn to the next row fine, but when reversing to the row start position seem to over compensate. Not really a major issue and i'm sure there are bigger and better things to be working on (Overloading mode and Compacting mode...... hint hint)
