### ISSUE TITLE
Error: Running LUA method 'draw' - AIDriver.lua:560: attempt to index field 'course' (a nil value)

### ISSUE THREAD

**Issue by Phips99** [Courseplay/courseplay#3685]
Nach ein paar Minuten Spielzeit schließt sich plötzlich das Cp hud und ich kann es nicht mehr öffnen. Außerdem kann ich weder aussteigen, noch fahren, noch das Fahrzeug wechseln. Nur ein Neustart des Profil hilft.

Ich habe noch einen Mod installiert, der das Fahrverhalten verändert. --> TSX Enhanced Vehicle
Vielleicht hat er was damit zutun?

**Comment by Tensuko** [comment]
Logfile bitte:
https://github.com/Courseplay/courseplay/wiki
Einfach log.txt in die Kommentarbox ziehen.

**Comment by Phips99** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3107592/log.txt)

**Comment by Tensuko** [comment]
Error: Invalid mod name 'FS19_Buy_Forage_1.1'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

Error: Failed to open xml file 'C:/Users/Philipp/Documents/My Games/FarmingSimulator2019/mods/LS19Real_straw_texture/modDesc.xml'.
Load mod: LS19Real_straw_texture (Hash: 8ef64b2b9128ea197a08895e578273d6)
Error: Missing descVersion attribute in mod LS19Real_straw_texture

Vom MBTrack gibt es übrigens schon einige neue Versionen, aber das nur so als Tip am Rande.

LUA Error1:
2019-04-22 11:29 Error: Running LUA method 'draw'.
2019-04-22 11:29 C:/Users/Philipp/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay6/AIDriver.lua:560: attempt to index field 'course' (a nil value)

LUA Error2:
2019-04-22 12:18 Error: Running LUA method 'findBlockingObjectCallbackRight'.
2019-04-22 12:18 C:/Users/Philipp/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay6/bypass.lua:182: attempt to index field 'cp' (a nil value)

Könntest du kurz beschreiben, was an Fahrzeuge und CP Fahrer rumfuhren bei dir ?
Z.B. Saatmaschine X Mit Mode4 oder Sammelwagen mit Mode6 usw...
Brauchen halt ein paar mehr Infos, bei was das passiert sein könnte.

**Comment by Phips99** [comment]
Ich habe Mais gehäckselt:

2x Krone X 1180 mit X-Collect 900-3
Modus 6 im Drescherverband

6x Abfahrer:
                    -> Fendt 900 Vario mit Krampe Bandit 750 (Mod)
                    -> New Holland T7 mit Krampe Bandit 750 (Mod)
                    -> 4x John Deere 7R mit Krampe Bandit 750 (Mod)
Modus 2 mit manueller Drescherzuweisung

1x Fendt 900 Vario zum Silo verdichten mit 2x Holaras Stego 485 Verdichtwalzen
1x Fendt 900 Vario zum Silo verdichten mit 1x Holaras Stego 485 und 1x Holaras MES 500
Selbst gefahren

Courseplay hat sich aufgehängt, als ich bei einem John Deere 7R den Abfahrer entlassen wollte.

**Comment by Tensuko** [comment]
Also ich kann es nicht zu 100% sagen, aber da Mode2 noch nicht neu geschrieben wurde, könnte ich mir vorstellen, dass es zu problemen mit der Drescherzuordnung kommt, gerade wenn man so viele hat und einen Abfahrer wieder entlässt, aber das ist wirklich nur eine Vermutung.
#3311 
@pvaiko was sagst du dazu ?

**Comment by pvaiko** [comment]
@Tensuko also das ist eher @ThomasGaertner, ausserdem mit so vielen Mods und Fehler ist es schwer zu sagen woran es liegt.

**Comment by Phips99** [comment]
ok trotzdem danke

**Comment by Tensuko** [comment]
Closed, da inaktiv und zu viele Mods mit Errors in der log.
Wenn bereinigt und Fehler tritt noch immer auf, Reopen.
