### ISSUE TITLE
Strange behavior when trigger is reached with tractor

### ISSUE THREAD

**Issue by rymus** [Courseplay/courseplay#3688]
Running an empty combine/tip to silo course, issues start occurring when either the start/stop or the tip triggers are reached. In the case of tip trigger, once the trailer begins to tip into the silo, the tip progress appears to freeze, the tip animation & sound continues to play. At this point controls become erratic, i.e. I can tab to another vehicle but not always. I can enter the menu but cannot leave it, etc. Similar behavior when start/stop trigger is reached. The 3rd person viewpoint freezes at the trigger location but the tractor continues to drive. 

Running Marwell & latest version of courseplay.

**Comment by DemonRaven** [comment]
to you use follow me or ai expansions mod with cp? I had same problem but it fixed itself after removed those 2 mods.

**Comment by DemonRaven** [comment]
Hmmm but is the tractor or trailer you use vanilla or modded?

**Comment by rymus** [comment]
should have added that info the original report. Tractor and trailer are vanilla. I'm going to run through more testing on this later including attempting the same course on base map and unloading what few other mods I have installed.

**Comment by Tensuko** [comment]
logfile with debug2 (not sure about 19) and screenshot.
https://github.com/Courseplay/courseplay/wiki

I noticed that the trigger of the cowshed does the same, but I can just stop it and continue normaly.
I was thinking that the cowshed mod (Modding Welt US Version) could be the issue.

**Comment by rymus** [comment]
noticed the same while doing some testing on Marwell map. I guess some dependency of the Marwell mod doesn't play nicely.

**Comment by DemonRaven** [comment]
Hmm i found this issue for me in felsburn edit map, but my issue was either follow me or ai extensions, i did not tested what one of them was problematic quz i had with follow me another bug to and ai extensions is in beta stage so i just remove both
