### ISSUE TITLE
Dual HUD when driving with a drivable attachment

### ISSUE THREAD

**Issue by Martinnygaard** [Courseplay/courseplay#3690]
Hi,

I noticed that when i am driving a tractor with an attahment that in it self is a vehicles (like the conveyor and the wood crusher), then i can see the HUD for both vehicles. (on the screenshots, you can see both HUDs)

![image](https://user-images.githubusercontent.com/26490587/56671066-39b7bd00-66b4-11e9-8d4c-35a0381888eb.png)

![image](https://user-images.githubusercontent.com/26490587/56671344-c4002100-66b4-11e9-8fd0-fb2b6591a222.png)

**Comment by Tensuko** [comment]
Happens with V236, when you get into the drivable attatechment and open the HUD, then switch to the Tracktor, a HUD is already open from the attatchment and you can open anotehr HUD.

Haven't tried out what happens if you deattatch and reattatch....

**Comment by Tensuko** [comment]
Still valid with V353+
Ignore specific Vehicles ?

**Comment by Tensuko** [comment]
fixed.
