### ISSUE TITLE
Error: Running LUA method 'draw' - hud.lua:465: attempt to index a nil value + Callstacks

### ISSUE THREAD

**Issue by stueja** [Courseplay/courseplay#3691]
Using CP v6.01.00194dev on LS19, the driver loads water from the start point and unloads it correctly. When the water trailer gets empty during unloading, i. e. the stable's water supply is not yet full, the driver simply does nothing. A click on "How many rounds" (translated from German) in that situation even crashed CP. Had to restart the career.

**Comment by Tensuko** [comment]
Du meinst Savegame neu laden ? Oder Savegame zerschossen ?
Wasser soll eigentlich später über Flüssigkeitstransport laufen.
Mit den Triggern bei z.B. Kuhstall habe ich auch schon einiges bemerkt, was nicht rund läuft.
Kannst du mal ein logfile mit Debugchannel 2 laufen lassen und hier posten ? (drag and drop in die textbox)

**Comment by stueja** [comment]
Nein, das Savegame ist weiterhin intakt, ich mußte es neu laden, weil die CP-GUI nicht mehr erscheinen wollte. 
Gerade wollte ich das Verhalten nachstellen, da trat das Problem mit der verschwindenden GUI bereits nach Klick auf "Kursaufzeichnung stoppen" auf. Modus ist "Abfahrer (Beladung am Startpunkt)". CP läuft noch irgendwo im Hintergrund, weil ich mit rechter Maustaste zwischen "CP-Modus" und "LS-Modus" hin- und herschalten kann, aber die GUI bleibt unsichtbar. Wenn man im "CP-Modus" irgendwo hinklickt, wo eine CP-Funktion sein könnte, dann hört man den Bestätigungsklickton.
Kann hiervon ein Debug aufgezeichnet werden?

**Comment by Tensuko** [comment]
Gibt den HUD Debugchannel 18.
Kannst du weiter arbeiten wenn du das Gerät einmal abhängst ?
Wieder dranhängen wird dann warscheinlich wieder den Fehler auslösen, aber die Geräte einmal zurücksetzen und dann wieder zusammen setzen sollte dann wieder gehen.

**Comment by stueja** [comment]
Ich kann die Geräte normal manuell weiterbedienen, nur eben ohne CP.
Gerade trat das Problem beim Klick auf "Kursaufzeichnung stoppen" auf, obwohl ich nur einen Feldkurs einfahren wollte (Modus "Überführung"). Ich hatte kein Gerät dran, was ich hätte abkoppeln können.
Nach Neuladen des Savegames wollte ich einen anderen gespeicherten Kurs laden, da war die GUI dann gleich nach dem Klick auf den Ladebutton weg. Das gleiche danach noch einmal, ich hatte Debugchannel 18 eingeschaltet. Wo finde ich das Log?

**Comment by Tensuko** [comment]
Ok danke dir, wir schauen mal rein.

**Comment by Tensuko** [comment]
#3672
ähnlich wie das was ich gefunden hatte.

**Comment by stueja** [comment]
Ich möchte nur anmerken, daß ich zum Zeitpunkt des Fehlers in einem Stock-(nicht-Mod)-Traktor saß ;)

**Comment by Tensuko** [comment]
Versuchs mal mit V205 oder höher.

**Comment by Tensuko** [comment]
Mein Issue #3672 ist fixed.
Ich gehe mal davon aus, dieser heir auch. Ansonsten bitte nochmal mit neuester Version und logfile melden.
Closed.
