### ISSUE TITLE
Rubicon 9000 problem

### ISSUE THREAD

**Issue by Horozor** [Courseplay/courseplay#3692]
Greetings. When fertilizing with Rubicon 9000, it leaves non-fertilized areas after turning. The fact is that it turns on the sprayer 3-5 meters late. Offsets don't help.
![fsScreen_2019_04_25_18_38_26](https://user-images.githubusercontent.com/37561569/56749873-3cd1ac80-678b-11e9-9945-e85bb1707eae.jpg)

![fsScreen_2019_04_25_18_38_30](https://user-images.githubusercontent.com/37561569/56749369-44448600-678a-11e9-8f14-f8b26849fcc4.jpg)

**Comment by pvaiko** [comment]
This should work with 258 or newer. Reopen if not.
