### ISSUE TITLE
Combine unloading from the edge of the field

### ISSUE THREAD

**Issue by Horozor** [Courseplay/courseplay#3694]
Greetings. Version v6.01.00194. Map and equipment standard. When i try to unload the combine from the edge of the field, it does not stop, starts to go back and make a meaningless maneuver. I found that you added this in 
> v6.01.00165 6.01.00165 Fine tuning
> Combine makes pocket on outermost headland

I have a large field on which the combine works in a circle. This creates problems during unloading. Tell me how to remove this feature or disable it.

![fsScreen_2019_04_26_18_08_20](https://user-images.githubusercontent.com/37561569/56818761-ffcfed80-6850-11e9-9643-1a1664f2ff86.jpg)
![fsScreen_2019_04_26_18_08_34](https://user-images.githubusercontent.com/37561569/56818762-ffcfed80-6850-11e9-89d8-7c5293958e70.jpg)
![fsScreen_2019_04_26_18_08_41](https://user-images.githubusercontent.com/37561569/56818763-00688400-6851-11e9-8f44-a60ca921454a.jpg)

**Comment by Tensuko** [comment]
I think that was Avoiding Fruit on disabled for the Combine.

**Comment by Horozor** [comment]
> I think that was Avoiding Fruit on disabled for the Combine.

Thank you. When I turn off the Avoiding Fruit harvester just stopped and waited for unloading.

**Comment by Tensuko** [comment]
Closed.
