### ISSUE TITLE
FS19 crashes during Save when CoursePlay and MAN ITR truck are in game

### ISSUE THREAD

**Issue by asyvan** [Courseplay/courseplay#3695]
FS19 crashes during Save when CoursePlay and this mod is in the game (MAN truck bought in shop) at the same time.  The savegame is then corrupted, leaving only 2-3 files (course play settings and environment).
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=123383&title=fs2019

No other mods where active, Ravenport standard map. If you don't buy the truck, it can still be loaded as mod without issues.

Reproducable: Install CP and the above listed mod. Start a map, buy the truck, try to save.

ZIP'd logfile showing the error:
https://drive.google.com/open?id=1o8OluzRtUEfCs5SeaC-8yzNmOfabQxW0

```
2019-04-27 09:33 Error: Running LUA method 'onSaveStartComplete'.
2019-04-27 09:33 e:/users/Gaming/My Games/FarmingSimulator2019/mods/FS19_CoursePlay/base.lua:1696: attempt to index field 'driver' (a nil value)

```

**Comment by Tensuko** [comment]
Mod Issue.
That MAN IT Runner don't even have a possibility to open the HUD.
We can't do anything about that.
You can try contact the Modder and tell him to fix his Mod.
Closed.

**Comment by legendarytater** [comment]
Same issue with the John Deere sts combine
