### ISSUE TITLE
Saved couses problem

### ISSUE THREAD

**Issue by MAOGAMI** [Courseplay/courseplay#3696]
There's strange problem with saved courses.

Imagine I have generated a course, started working on it and everything is fine. I save it and load it the next day to continu my work and it's still fine. But every few days (randomly i guess?) my courses are flipping over ie i have harvested half of the field yeasterday and when I start the same course today it's starting from this point but going opposite way "harvesting already harvested" part of the field. Markers are also flipped sideways, there where was green now is red and where was red is green turn marker, headlands are right instead of left etc.

It's only my problem?

I don't have any info and screenshots how it could happen, last time i was thinking i saved it wrong way, but now its not possible, CP changed direction of my course itself.

**Comment by sootysax** [comment]
generally you shouldn't save fieldwork courses - just regenerate them again when you need them

**Comment by pvaiko** [comment]
Can't think of any way how this can happen. If you have reliable way to reproduce this, reopen this issue and describe all the detailed steps.
