### ISSUE TITLE
Vehicle is sliding

### ISSUE THREAD

**Issue by MAOGAMI** [Courseplay/courseplay#3697]
I have noticed that for example if you have combine harvesting field and tractor in mode 2 and that tractor runs on eg. tree and start sliding, the combine starts sliding too, if you stop this slidin tractor the combine starts harvesting again.

**Comment by Tensuko** [comment]
#3311 
I guess you mean the sliding msg.
That is becouse the Combine waits for the Mode2 Driver to reach its Parking position.

Closed.
