### ISSUE TITLE
Mode 4 Transiting field at work speed

### ISSUE THREAD

**Issue by enderwiggin07** [Courseplay/courseplay#3698]
On Seed/Fertilize the worker is using the work speed to transition to a different point (not working)

For example after a fertilizer refill, the worker exits at field speed but once back on the field uses work speed (7 mph) to get back to the resume point 

Similar for a seeder transitioning from headlands to up/down rows.  Crosses the entire field at work speed.  

Not a major issue by any means but for very large fields it adds a lot of time.  
Thanks

**Comment by pvaiko** [comment]
Which version?

**Comment by enderwiggin07** [comment]
196.  I just saw the 197 release but haven't installed yet

**Comment by pvaiko** [comment]
How does it work with 201?

**Comment by enderwiggin07** [comment]
Tested before work so didn't do anything with a refill course, but seeder seemed to use field speed to move to first waypoint so the fix seems to have worked.  

Great release, including the turning optimization.  Appreciate your work very much
