### ISSUE TITLE
Error: Running LUA method 'update' - vehicles.lua:726: attempt to call method 'getWheels' (a nil value)

### ISSUE THREAD

**Issue by Berner93** [Courseplay/courseplay#3699]
When i open my savegame with CP the HUDS wont show up, i cant go to any menus and the hole game goes very dark.
When i open without CP it's fine.
i have the 197 version
![fsScreen_2019_04_27_20_33_13](https://user-images.githubusercontent.com/47973910/56853708-bdc7aa00-692b-11e9-9f27-ff05ff6847cf.png)

**Comment by Berner93** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3124283/log.txt)

**Comment by Tensuko** [comment]
Looks like a Mod Issue.
Take out mod by mod and see when it works again.

**Comment by Tensuko** [comment]
Closing couse inactive. Reopen if anything new. (with Mods taken out...)

**Comment by Clipless** [comment]
I have this exact same issue. This is on a saved game and last time I opened the game everything was fine, this time dark and EXTREMLY laggy. If I disable Courseplay all is fine. I can start a new farm with exact same mods (including Courseplay) and everything works fine. So seems to be something with Courseplay in that specific save.
