### ISSUE TITLE
v6.01.00197 - Field Working - Come back to the start point Feature

### ISSUE THREAD

**Issue by neooblaster** [Courseplay/courseplay#3701]
Hi Team,

I'm not sure if it is a real issue, but with the latest v6.01.00197 (that was the latest when I download it yesterday), my vehicules which are working in fields always come back to the start point when they have finished whether the option is enable or not.

I see nothing about this change, that why I'm not sure if it a regression or a change on default behavior ?

Thank a lot for this awesone mod !

Kindly Regards
Neoblaster

PS : my game version : v1.3.0.1

**Comment by Tensuko** [comment]
It is a bit under construction right now.

With V195:
- use pathfinding when starting the field work and when returning to
the first point (this helps #3535). For now, always return to the first
point, we'll have to add this option to the HUD later and remove from
the course generator.

- when returning to the first point, raise and fold implements (#3583)
Note that this does not work if your course is generated with the 'return
to first point' option, see above.

A bit patient pls then the option will be back, but in the HUD and no longer as a Generator Option.
Closed.
