### ISSUE TITLE
combine astray

### ISSUE THREAD

**Issue by AlvinMJ** [Courseplay/courseplay#3702]
It was a little strange way:
https://steamcommunity.com/id/Alvinmj/screenshot/822380354965070969

**Comment by Tensuko** [comment]
And how does this report help us in any way ?
https://github.com/Courseplay/courseplay/wiki
Screenshot and logfile of the course with debug channel 9 and 14 on.

**Comment by AlvinMJ** [comment]
Screenshot ar on my link. Logfiles I do not know much about, but can try to find them. I can also try to repeat it on tupe.

**Comment by pvaiko** [comment]
Most likely a duplicate of #3598

**Comment by AlvinMJ** [comment]
yes

**Comment by AlvinMJ** [comment]
Video: https://youtu.be/_aUn66t4z-I
[log.txt](https://github.com/Courseplay/courseplay/files/3127081/log.txt)
