### ISSUE TITLE
Courseplay switches off collison

### ISSUE THREAD

**Issue by xerion8300** [Courseplay/courseplay#3703]
As soon as I switch from course depart to load depart, the collision is switched off. I have attached two pictures to the file

![fsScreen_2019_04_28_14_22_29](https://user-images.githubusercontent.com/25564472/56864418-498c1580-69c2-11e9-8d38-02e8e9ba44d1.png)
![fsScreen_2019_04_28_14_22_42](https://user-images.githubusercontent.com/25564472/56864419-498c1580-69c2-11e9-8352-6cd3c642d53e.png)

**Comment by Tensuko** [comment]
logfile pls.
https://github.com/Courseplay/courseplay/wiki
What tools used ?

**Comment by pvaiko** [comment]
What exactly is the problem? Also, mode 2 as we all know, not finished yet.

**Comment by xerion8300** [comment]
Well then I put the problem in the back, didn't know it had to do with Mode 2.
The problem is that the collision is turned off when I change the mode and the tractor then hits the other one.

**Comment by pvaiko** [comment]
There are many duplicates of this, closing.
