### ISSUE TITLE
capacity limit

### ISSUE THREAD

**Issue by levisbaja** [Courseplay/courseplay#3705]
Hi!
Can I change the capacity limit for the trailers and combines? 
I can not use courseplay because all of my fields are very big, so my combines and trailers capacity over 1M.
Thank you

**Comment by Tensuko** [comment]
A Quote from @ThomasGaertner 

> 
> 
> if you want, you can change the value in drive.lua(1853) to a one >5mio. I don't want to do it...

You can edit this, but this won't find its way into CP.
Closed.

**Comment by levisbaja** [comment]
where can I find this?

**Comment by Tensuko** [comment]
In your cp zipfile.

**Comment by levisbaja** [comment]
I've found it. Thank you
