### ISSUE TITLE
Error: LUA method draw.hud.lua:465: bei Tiertransporter

### ISSUE THREAD

**Issue by Charlyphyro** [Courseplay/courseplay#3706]
Hallo,
Beim versuch mit einem der Tiertransporter zu fahren, kommt sofort die fehlermeldung und die HUD ist verschwunden. Ab- & Ankoppeln bringt auch nichts.

[log.txt](https://github.com/Courseplay/courseplay/files/3125190/log.txt)

Grüße Charly

**Comment by Tensuko** [comment]
Welcher Modus ?
Tiertransport mit Auf- und Abladen ist nicht unterstützt.
Mode5 zum reinen A/B fahren sollte funktionieren.

Daher mehr Infos bitte, was genau gemacht wurde, welcher Modus und ein logfile bitte.
https://github.com/Courseplay/courseplay/wiki

**Comment by Charlyphyro** [comment]
Modus 5 da hängt sich er auf. Bereits beim ankoppeln

**Comment by Tensuko** [comment]
#3672

**Comment by Tensuko** [comment]
Try with 203 or higher and report.

**Comment by Tensuko** [comment]
Fixed.
Closed.
