### ISSUE TITLE
Course will not generate on some fields

### ISSUE THREAD

**Issue by Tezzward** [Courseplay/courseplay#3708]
Using Midwest Horizon map.  When trying to create any new course on some fields, it freezes for a few minutes (pulls a massive amount of ram) and either doesn't generate a course at all, or it will create a really crazy course that starts in the correct field and goes off in random directions.  

Happened in v196 and also in v201.  Using vanilla equipment.  Many mods loaded but not in use except for map and a placeable shed (not in field that I'm attempting to create a course in).  

Complete Log: https://pastebin.com/Ld322Yt9

error text: 2019-04-29 01:00 CourseGeneratorScreen:onCreate()
2019-04-29 01:02 Error: Running LUA method 'mouseEvent'.
2019-04-29 01:02 C:/Users/twank/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00201/course-generator/center.lua:165: attempt to index local 'b' (a nil value)

**Comment by Tensuko** [comment]
Just a sidenote:
Load mod: FS19_Gameplay_Grass_Patch_v2013 (Version: 2.0.1.3) (Hash: bfd2bf22cc94ed2bee54c2a0f16f7d56)
still needed ?

To your problem: Can you make a Screenshot of the Coursegenerator Settings, with the Field next to it and a new Logfile with Debugchannel 7 on, when try to generate.

**Comment by Tezzward** [comment]
You are correct on the grass patch mod.  I'm the type that downloads mods, doesn't use them, and doesn't delete them until they cause a conflict.  

Directly after trying to generate on field 73 and after unfreezing.  (I have tried other courses with other tools as well on these same fields.)

![20190429035441_1](https://user-images.githubusercontent.com/50094589/56883670-5eee5780-6a35-11e9-9d92-fa203c4b6d57.jpg)

Nearby field with same course
![20190429035550_1](https://user-images.githubusercontent.com/50094589/56883758-a1b02f80-6a35-11e9-95a8-06aa2a8b02f7.jpg)

field 31 to show the weird course generated on that field. 
![20190429040247_1](https://user-images.githubusercontent.com/50094589/56883808-c0aec180-6a35-11e9-8481-406be27148c9.jpg)

Field 32 directly next to 31, normal course generation. 
![20190429040414_1](https://user-images.githubusercontent.com/50094589/56883833-d45a2800-6a35-11e9-8d8a-6c4b14c579b4.jpg)


New log after closing, reloading, enabling debug channel 7 and attempting to create the same course.  
https://pastebin.com/yjMbFBhE

**Comment by pvaiko** [comment]
There's something wrong with that map, I'll probably have some time to look at it if you post your field definitions as described here: https://github.com/Courseplay/courseplay/wiki#how-to-post-your-field-definitions

You may also want to buy all fields before with gsBuyAllFarmlands to include all fields.

**Comment by Tezzward** [comment]
It is too large for pastebin.  Do you want me to paste it directly into a comment?

**Comment by Tensuko** [comment]
Just drag and drop the log.txtinto comment box

**Comment by Tezzward** [comment]
https://gist.github.com/Tezzward/d770ca4c56ca3b1907906d87186bc1ed

**Comment by pvaiko** [comment]
That's clearly a map issue. CP can't correctly detect the edge of fields 31 and 73, you can see it in the XML as the numPoints="2000", that's the upper limit of the number of points defining a field for CP. You can see all other fields have a reasonable number (few hundred). 

The map creator should check the area of these two fields in the cultivator_density file.

**Comment by Tezzward** [comment]
Thank you very much for your time.

**Comment by Txzar** [comment]
pvaiko,
What exactly should I check for in the cultivator_density file?

**Comment by pvaiko** [comment]
@Txzar I'm not the expert on map making but as far as I know the cultivator_density.gdm is created from a bitmap (PNG) where the value of the individual pixels define the fields. CP finds the field edge based on these (using Giant's DensityMap* functions probing small areas in steps. 

If you have two adjacent fields too close (just a pixel or two between them) or there's a pixel left accidentally between two fields that'll confuse this algorithm. If can't seem to find the reason, you can send me a PNG and I can look at it or if everything else fails, point me to your map and I can enable some debugs and traces to figure out where the problem is.

**Comment by Txzar** [comment]
I'm thinking the cause is too few pixels. I am adjusting now to test. Thank you for the additional explanation.
