### ISSUE TITLE
Pause button still disabled

### ISSUE THREAD

**Issue by khryssmar** [Courseplay/courseplay#3709]
The pause button during course recording is still disabled from the initial recording trigger until stopping the recording.

It can be enabled though by pressing every other button (except stop) available on recording menu.

**Comment by XPiRiJenZ** [comment]
you can also switch to transfer-mode. there you can pause and delete course recording

**Comment by Tensuko** [comment]
You just got to switch a mode or HUD Menu to get it back.
The HUD needs a refresh when the Pause button gets available, the bug is know and will be fixed soon.
Duplicated of #3655
Closed.
