### ISSUE TITLE
Control key orders the AI driver to continue (wait waypoint)

### ISSUE THREAD

**Issue by mehdinasef** [Courseplay/courseplay#3710]
I have noticed that pressing left control key when the tractor arrives at a wait waypoint makes it continue. This happens when I use left control + delete to open the HUD.

**Comment by Tensuko** [comment]
Is there any Keybind to this in the Keysettings ?

**Comment by mehdinasef** [comment]
I don't know what you mean by "keybind" but I had this issue when I used CP with a tractor with front loader, I chose the option to open the HUD with left Ctrl + delete and that makes the tractor continue whenever I open the HUD. Later I found out that pressing left ctrl button only does the same even if I have the hud opening set to right mouse button.

**Comment by mehdinasef** [comment]
I also have default keysettings. I didn't change any thing there.

**Comment by Tensuko** [comment]
![keybinding](https://user-images.githubusercontent.com/27344744/56904653-05227780-6a9f-11e9-81d0-47cd3a2fd982.png)
Try to delete this if you got this. Not sure if my settings are all to default, but should be.

**Comment by mehdinasef** [comment]
Ok, I'll do as soon as I have time

**Comment by Tensuko** [comment]
Closing this, report if still got any problem and what you found out with more details pls.
Going to reopen it then.
