### ISSUE TITLE
Silo Abfahrer fährt mit zu schnell durch

### ISSUE THREAD

**Issue by starkwood123** [Courseplay/courseplay#3711]
Hi, Mein Silo abfahrer fährt einfach zu schnell durchs BGA Silo durch und verstreut es hinten raus noch ca 50 M zu weit raus.

Habe ganz normalen Kurs gemacht er kennt auch abladestelle ect aber fährt dann mit 53 KmH durch

**Comment by StefanBraun2001** [comment]
Das passiert mir auch immer, im Modus 2. #3311 Der wird noch neu geschrieben. Versuch irgendwie es mit einem Modus 6 oder Modus 1 Abfahrer zu machen oder manuell abladen

**Comment by starkwood123** [comment]
Bild https://www.bilder-upload.eu/bild-839fa2-1556565857.png.html

**Comment by starkwood123** [comment]
Habe schon Videos gesehen wo das Super klappt :/ bloß bei fährt er einfach so schnell durch :(

**Comment by StefanBraun2001** [comment]
Manchmal klappt das, aber meist fährt er da volle Pulle durch. ist so eine Glückssache

**Comment by starkwood123** [comment]
Habe mich so aufs Maishäckseln mit Courseplay gefreut  Heul  :-D

**Comment by StefanBraun2001** [comment]
Ich machs immer so ich lass den Modus 2 Abfahrer bis zur BGA fahren dort abkippen und 3 Förderbänder verladen das auf einen anderen Trailer der das dann ins Silo kippt. Umständlich, aber es funktioniert.

**Comment by starkwood123** [comment]
Meinst du baust dir eine Strecke In Mode 2 wo du bist zur BGA fährst dort ein Abkipp punkt erstellt wo da förderbänder stehen und das in dein Trailer machen?  ist der Trailer auch mit courseplay verbunden? wenn ja wie macht der das ins Silo oder machst du das

**Comment by StefanBraun2001** [comment]
Ja, wo die Förderbänder stehen einen Abladepunkt setzen. Dort beladen dann 3 Förderbänder einen weiteren Trailer der im Mode 1 dann durchs Silo fährt. UNd das funktioniert auch zuverlässig

**Comment by starkwood123** [comment]
Kenne mich mit Mode 1 wenig aus wie machst du den Kurs da? Einfach durch fahren ?

**Comment by StefanBraun2001** [comment]
Ja, unter den Förderbändern starten dann durchs Silo und den Kurs kurz vor dem Anfang der Förderbänder beenden. Achte aber darauf dass die Förderbänder nicht zu nahe sind sonst bleibt der im Verkehr stecken. Ist etwas tricky da er manchmal einfach so los fährt ohne zu beladen, indem Fall nochmal versuchen wenn Häckselgut verladen werden kann dann sollte es klappen

**Comment by starkwood123** [comment]
Danke dir sehr oder lade mir bis das behoben ist diese Modt runter https://www.modhoster.de/mods/silageherstellung#description

Dann kippt er es in ein Silo und da wird Silage draus erstellt

**Comment by Tensuko** [comment]
Mode2 noch immer im Rework...
#3311 
Closed.
