### ISSUE TITLE
fertilizing while seeding

### ISSUE THREAD

**Issue by newride** [Courseplay/courseplay#3712]
Is there a plan to add the option to fertilize during seed? In fs17 it was an option for it with couseplay so you didn't have to fertilize during seeding. Otherwise if the seeder you are using fertilizes and seeds you have to keep both full if there was an option then you could just seed and not put fertilizer down.

**Comment by Tensuko** [comment]
Still available.
![Unbenannt](https://user-images.githubusercontent.com/27344744/56946600-d4881f80-6b2a-11e9-97d9-5705f43cdb07.png)

Closed.
