### ISSUE TITLE
Working Speed Väderstad Rapid 600s

### ISSUE THREAD

**Issue by spiessphilipp** [Courseplay/courseplay#3714]
With the Väderstad Rapid 600s seed drill, the helper drives only 15 km/h instead of the possible 18 km/h, as with the other seed drills that can only reach 15 km/h working speed. In the settings you can't change that because under speeds unfortunately only the driving speeds are adjustable. Would it be possible to fix this, or is that what is intended?

**Comment by Horozor** [comment]
Is your seed drill repaired? With decreasing strength, the working speed is lost.

**Comment by Tensuko** [comment]
No answer, if getting any more problem. Create a new Issue with actual CP Version and post your full logfile pls.
https://github.com/Courseplay/courseplay/wiki
