### ISSUE TITLE
Missing sections of field (Seeding)

### ISSUE THREAD

**Issue by Derplodactyl** [Courseplay/courseplay#3715]
Unsure if this is an issue other's have experienced, but generating a course with the "Turn" settings on during headlands makes the worker start seeding, stop and leave a patch, then start again some time later (see the image below).

Running the latest version of CP, Old Stream Farm, and affecting base game tractors/implements and modded ones alike.
![FarmingSimulator2019 64bit 30_04_2019 14_38_39](https://user-images.githubusercontent.com/49948811/56965794-f8ad2600-6b55-11e9-970a-b66789f088bb.png)

**Comment by Tensuko** [comment]
Screenshot of Course, Settings of Course, logfile.

**Comment by seeske123** [comment]
One waypoint later for course change and it is fixed. Not only here but also at the stop. There the same. One waypoint more.

**Comment by pvaiko** [comment]
@seeske123 No idea what you are talking about.

**Comment by Derplodactyl** [comment]
Hello.

Thank you for the replies.

Unfortunately, due to an unrelated mod conflict, the original game save I used to take the screenshot above corrupted. Please also excuse the many mods present - I have yet to go through the folder and delete the obsolete ones I no longer use! However, I started a clean game save with only Courseplay active, and I had similar issues. Please see the attached. 

![Farming Simulator 19 30_04_2019 18_40_28](https://user-images.githubusercontent.com/49948811/56982353-0cb64f00-6b79-11e9-9753-9e96b9c3ff5c.png)

[LogForCourseplayError.txt](https://github.com/Courseplay/courseplay/files/3132484/LogForCourseplayError.txt)

I also have in game footage of this occurring, however, I am unable to upload it here. It you would like to see it, I can provide it in some way. 

On an unrelated note, I cannot get rid of the "No course generated" text at the bottom of the screen. Again, this may be previously discussed, I am unsure - see the image below:

![Farming Simulator 19 30_04_2019 18_43_52_LI](https://user-images.githubusercontent.com/49948811/56982511-67e84180-6b79-11e9-808f-f91ea3c377b3.jpg)

**Comment by pvaiko** [comment]
Log with debug channel 12 und 14 please.

**Comment by Tensuko** [comment]
For the Text at the bottom, read #3552 it is in the settings, Mini-HUD on/off

**Comment by seeske123** [comment]
If you extend this one waypoint more when changing lane and the stop also one waypoint more.

**Comment by Derplodactyl** [comment]
Thank you @Tensuko - I missed that!

And the logs are attached as follows:

[LogDeBug12.txt](https://github.com/Courseplay/courseplay/files/3132603/LogDeBug12.txt)

[LogDeBug14.txt](https://github.com/Courseplay/courseplay/files/3132613/LogDeBug14.txt)

**Comment by pvaiko** [comment]
Not sure, first of all you should have both 12 **and** 14 turned on at the same time,  second, I don't know what you were doing but these logs don't show any turn maneuver.

**Comment by Derplodactyl** [comment]
Ok, no problem. I'll have a look and see if I can work it out. It seems to be an isolated issue on my end anyhow. Thank you for your time looking!
