### ISSUE TITLE
Imperador 3.0 traffic detection range

### ISSUE THREAD

**Issue by khryssmar** [Courseplay/courseplay#3716]
The Imperador 3.0 detects traffic which is still very far from the machine. 
![imperador **bug](https://user-images.githubusercontent.com/50015320/56972331-603a9400-6b9d-11e9-9350-aad49214948c.PNG)**
Even when trying to load Liquid Fert treats it as a traffic.

**Comment by ThomasGaertner** [comment]
double #3239
