### ISSUE TITLE
Rapide

### ISSUE THREAD

**Issue by khryssmar** [Courseplay/courseplay#3717]
I am using Rapide 580V and a JCB FASTRAC 8330 for collecting grass and when the AI returns to its last position (loading wagon is full and stated the unloading waypoints), there are a few meters that is being neglected by the AI.
This picture I stopped the AI when it is about to continue from where it left:
![JCB FASTRAC](https://user-images.githubusercontent.com/50015320/56972836-4e0d2580-6b9e-11e9-8ce5-2970167158ed.PNG)

These the patches that it left before I relized what was happening.
![fastrac](https://user-images.githubusercontent.com/50015320/56973141-d68bc600-6b9e-11e9-9ed2-2b84cde3c386.PNG)

**Comment by Tensuko** [comment]
logfile ? Wich CP Version ?
The Screenshots doesn't help when we not even see Waypoints

**Comment by pvaiko** [comment]
This should have been fixed in 195, if you are using an older version, upgrade and retry. If you are using 195 or newer than post a log with debug channels 12 and 14.

**Comment by khryssmar** [comment]
I am using V201.
[log.txt](https://github.com/Courseplay/courseplay/files/3133751/log.txt)

I will retry this process again with the loading wagon. I'll post the log file again.

**Comment by khryssmar** [comment]
Here is the log file with debug channels 12 and 14 enabled.
[log.txt](https://github.com/Courseplay/courseplay/files/3133878/log.txt)
It seems like the problem is with the turning radius generated for the tractor when approaching to its last waypoint is too small.

**Comment by pvaiko** [comment]
This looks ok to me, tractor passing waypoint 453 and returning to 450 which is about 15 m behind. A screenshot or video with channels 12 and 14 and the course made visible would help.

2019-05-01 12:14 :51 [dbg14 lp98405] Fastrac 8330 (#2): onWaypointPassed 453
2019-05-01 12:14 :51 [dbg14 lp98416] Fastrac 8330 (#2): Will return to fieldwork at waypoint 450
2019-05-01 12:14 :51 [dbg14 lp98416] Fastrac 8330 (#2): at least one tool is empty/full, aborting work at waypoint 450.
2019-05-01 12:14 :51 [dbg14 lp98416] Fastrac 8330 (#2): changing to unload/refill course (161 waypoints)

**Comment by khryssmar** [comment]
Ahh its okay now. The problem was that i am not using the default speed settings. I am using 24kph for turn and reversing and max for field speed. I did this since when the field im working is to big, it would take too long to travel to the last waypoint with a speed of 24kph.

Maybe you could include this one in the code to make use of the default speed (field speed 24kph) when the tractor is closing in towards the last waypoint but will use the set speed by the user otherwise.
