### ISSUE TITLE
Gärreste Befüllen Mode 1

### ISSUE THREAD

**Issue by starkwood123** [Courseplay/courseplay#3719]
Hi habe kein Moddet Gülle Anhänger aber ich kann in Mode 1 leider nicht mit Gärreste auffüllen er fährt nur durch.

Er zeigt zwar unten an Beladen 0 > 30.000 aber er fährt nur durch leider :/

hilfe bitte^^

**Comment by starkwood123** [comment]
Habe gerade Probiert mit Mode 4 Kombi Kurs das geht also er fährt runter füllt sich mit Gärreste auf und fährt wieder aus Feld.

Ich wollte ein Abfahrer machen der in Mode 1 mit Gärreste aufüllt und zum Feld fährt aber mit Mode 1 geht es nicht leider.

**Comment by Tensuko** [comment]
Flüssigkeitstransport ist noch nicht wieder aktiv.

**Comment by starkwood123** [comment]
Danke für die Info macht weiter so ohne Courseplay könnte ich nicht :-D danke

**Comment by Tensuko** [comment]
Closed.
