### ISSUE TITLE
Different vehicle fuel

### ISSUE THREAD

**Issue by dezza69** [Courseplay/courseplay#3720]
Hello,

This is not an issue, but more a suggestion or request??

I've modded a map and have custom fuels in some vehicles, and have noted those vehicles no longer work with Courseplay because of it checking specifically for diesel in drive.lua.

Is it possible to allow for different fuel types please, perhaps on a per vehicle basis?

Thank you for your considerations.

Kind regards.

**Comment by dezza69** [comment]
Hello Devs,

Me again, here's what I've done:

In the latest "205" offering, I modified "drive.lua" with the below adjustments and everything seems to work without error.


lines 1827:
if workTool.getConsumerFillUnitIndex and (index == workTool:getConsumerFillUnitIndex(FillType.DIESEL) 
ADDED-->	or index == workTool:getConsumerFillUnitIndex(FillType.CUSTOM_FUEL_TYPE)
or index == workTool:getConsumerFillUnitIndex(FillType.DEF)

line 2085:
CHANGED-->	local dieselIndex = vehicle:getConsumerFillUnitIndex(FillType.DIESEL) or vehicle:getConsumerFillUnitIndex(FillType.CUSTOM_FUEL_TYPE)


Whilst this is great, I'm not very LUA smart and am wondering if it's possible for the fuel type of the vehicle to be found with a more elegant method which dynamically selects rather than requiring fuel-type hard-coding?

Thanks very much,

Kind regards.

**Comment by Tensuko** [comment]
Won't happen, sry.

Closed.
