### ISSUE TITLE
Feild worker/field transport for combine offloader

### ISSUE THREAD

**Issue by laddken** [Courseplay/courseplay#3721]
I dunno if it is already known, But didnt see any feed back regarding it. 

When i ve been trying to set up a combine off-loader on field, the game seems to lock up, once i toggle from that vehicle after selecting the field, setting up the automatic find of combi, set the unload path and point for the hopper unload in to a semi/grain trailer setup, the game will seem to lock up, loosing alll keyboard funtions in game,ending in a atl-f4 to close the program. If i dont tab out of the vehicle, the vehicle will just sit on field even when combi is full and ready for unload and do the same thing.

**Comment by Tensuko** [comment]
Are you talking about Mode2 ?

**Comment by laddken** [comment]
yes, dunno if its supported or no yet but figured id give some feed back or see if it just something im doing wrong

**Comment by laddken** [comment]
i think i see what the issues is...... im taking it you can not use a auger wagon with mode 2 this time around.... a forum on reddit says that only dump wagons work and auger wagons will be mode 3 when it comes out

**Comment by Tensuko** [comment]
That is related to #3311 
Mode3 will come with Mode2, what we do about the Augur we will see, as this is some special overloader.
Closed.
