### ISSUE TITLE
Big X 1180, trailer and BGA silo unload problem (+Error: Running LUA method 'update' - AIDriver.lua:897: attempt to call method 'getTipState' (a nil value)

### ISSUE THREAD

**Issue by Boregepco** [Courseplay/courseplay#3724]
Hi,
May be the problem is here, but I want to ask.
I am with a Courseplay_6_01_00205. The map is Ravenport from the game.
I have Big X with a trailer and I use type Fieldwork in courseplay. When the trailer is full BigX starts it's course to unload in BGA silo, but courseplay crashes in silo...
I started to use type Fieldwork in field and when trailer is full I stopped the courseplay, changed type to type Grain transport and  continued with a courseplay…
But this is stupid,,,
Where is the problem? 
I can't use types Shovel filling and emptying and Leveling and compacting, they are grey...
Thank you in advance.

**Comment by Tensuko** [comment]
Mode6 is right so far. What exaclty does crash.
You getting an Error? The BigX crashes into silo wall?
How does your course look like?
Generally, CP should be able to unload into Silo, but success is always a matter of how good you made the course for the actual tractor+trailer.

Just drag and drop a few screenshots into the comment box of your crashing situation with Debugchannel 9 and 12 was it I think.

**Comment by Boregepco** [comment]
From the field to this point everything is ok.
![1](https://user-images.githubusercontent.com/24497717/57080888-3c419480-6cfc-11e9-9e6d-c52a7cd7057d.jpg)
After the trigger BigX continue the course, but without unloading, keyboard is inactive and I need to stop course with a mouse.

**Comment by Tensuko** [comment]
So it doesnt crash, but it is not unloading ?
Then we need a logfile with debugchannels 1 and 2 active.

**Comment by Boregepco** [comment]
Is this ok?
[log.txt](https://github.com/Courseplay/courseplay/files/3139134/log.txt)

And again about  types Shovel filling and emptying and Leveling and compacting, they are grey...

Thank you

**Comment by Tensuko** [comment]
Becouse they are not implemented yet...

@ThomasGaertner 
Notepad++ Line 837
2019-05-02 20:09 :31 [dbg2 lp8213] Big X 1180 (#1): Big X 1180 in mode 6: entering BGASilo:
2019-05-02 20:09 :31 [dbg2 lp8213] Big X 1180 (#1): emptySpeed: 1000l/sek; fillLevel: 0.0l
2019-05-02 20:09 :31 [dbg2 lp8213] Big X 1180 (#1): Silo length: 64.102401733398m/Total unload time: 2s *3.6 = unload speed: 115.38kmh

Und LUA:
2019-05-02 20:09 Error: Running LUA method 'update'.
2019-05-02 20:09 C:/Users/47/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00205/AIDriver.lua:897: attempt to call method 'getTipState' (a nil value)

**Comment by Tensuko** [comment]
Since Mode2 does work fine for this, I don't see a reason to drive with the chopper in the bunker silo.
Closing.
