### ISSUE TITLE
Error:Running LUA method `update´ - input.lua:441:attempt to index a nil value

### ISSUE THREAD

**Issue by thorben2110** [Courseplay/courseplay#3725]
Bitte um hilfe. Seid der version 6.01.00151 habe ich diese error Fehlermeldung sobald ich Courseplay öffne und bei jedem klick imCourseplay Menü. Haut mir die komplette Log voll.

FS19_Courseplay6/input.lua:441:attempt to index a nil value
Error:Running LUA method `update´

**Comment by Tensuko** [comment]
Tastenbelegung mal zurücksetzen auf standart, speichern, spiel neustarten und  schauen.

Und bitte immer komplette log anhängen.

**Comment by thorben2110** [comment]
Habe ich schon versucht. Im ersten moment geht es aber sobalt ich das spiel beende und neu starte habe habe ich den gleichen Fehler wieder.

**Comment by stueja** [comment]
Hast Du das Fahrzeug mal zum Händler zurückgesetzt? Das hat bei mir in einem ähnlichen Fall geholfen.

**Comment by thorben2110** [comment]
Habe ich ausprobiert, hat aber nichts gebracht. Wie gesagt, bis zur Version 6.01.00150 war alles super und alle nachfolgenden Versionen schmeißen bei mir diesen Fehler. Aber trotzdem danke.

**Comment by Tensuko** [comment]
Also mit V151 und 152 gab es Änderungen in der input.lua
Was jetzt aber euren Fehler auslöst kann ich nicht sagen.
Ich hatte bisher null schwierigkeiten trotz großer Anzahl Mods und Modmap usw.
Meine InputBinding habe ich komplett zurückgesetzt und nie einen Fehler gehabt.

Probeirt doch bitte mal aus, GamePad oder sonstiges vom PC zu trennen, die InputBinding zurück zu setzen und auch tools wie xpadder und co auszuschalten.
Irgendwo muss ja der Haken sein.

**Comment by thorben2110** [comment]
So ich habe den Fehler jetzt gefunden. Also falls es überhaupt ein Fehler ist oder vielleicht auch so gewollt ist.
Ich habe die Tastenbelegung noch mal zurück gesetzt auf standart so wie ihr ja schon gesagt habt und sobalt ich eine CP-Funktion auf eine andere Taste lege schmeißt er mir diesen Fehler. Solange ich alles auf Standartbelegung lasse funktioniert es.

**Comment by Tensuko** [comment]
Ok das könnte helfen, werde das mal ausprobieren.

**Comment by Tensuko** [comment]
Konnte es nicht reproduzieren, aber für die allgemeine Nutzung:
Keycommand einstellen und abspeichern, Funktion einmal mit der Maus auslösen, dann funktioniert auch der Keycommand, warum, weis ich nicht...

**Comment by Tensuko** [comment]
Continue in #4070
Closed.
