### ISSUE TITLE
Speed limite to 20 km/h with self-loading trailer in mode 1

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/courseplay#3727]
Hello,

When you transport silage (or other) from one point to another, in mode 1, with a self-loading trailer, the tractor is limited to 20 km / h (which corresponds to the maximum working speed) It does not go faster?
I tested with krone, and the 2 schuitemaker. I also removed all mods and the problem is the same.
![image](https://user-images.githubusercontent.com/36656729/57095795-fdb7d400-6d13-11e9-8d46-e82fd75ce68a.png)
https://gist.github.com/Crinouche/ccd620083b2b523d75fb4694212da7c1#file-log-txt

**Comment by sootysax** [comment]
you need to raise the cruise control to the fastest speed before starting your course.

**Comment by Crinouche** [comment]
Hello,

That's what I did. I know this problem with the "road" mode (trip from the beginning to the end of the race).
There, I talk about the mode "Driving assistance" (loading at startup)
I put my regulator at 63 km / h (photo1), but when I start the race, (photo2) it goes on 20 km / h throughout the race.
I do not have this problem with normal trailers, just with self-loading trailers.
![image](https://user-images.githubusercontent.com/36656729/57173954-eb828680-6e36-11e9-98ba-abb8b8a21b7f.png)
![image](https://user-images.githubusercontent.com/36656729/57173957-f4735800-6e36-11e9-87fc-1c4263630f60.png)

**Comment by Pitufo306** [comment]
it may be that you start the course with the trailer on or that the cp turns it on. Or simply that the CP understands that the trailer must be on and limits the speed to the maximum speed with the trailer on.

**Comment by sootysax** [comment]
shouldnt you be using mode 6 for forage trailers?   an unload route for a fieldwork course?

**Comment by Tensuko** [comment]
That trailer should also work in Mode1 and later in Mode2. I don't see a reason to not use it in Mode1 or 2.
Going to test things a bit later on my savegame.

**Comment by asyvan** [comment]
I have the same experience as this issue. It will not run at the recorded speed, but only at 20 unless you increase the FS19 cruise control speed after starting the course.

**Comment by Tensuko** [comment]
Still valid with V353+

**Comment by Tensuko** [comment]
fixed with 6.03.00060
