### ISSUE TITLE
Beacons not working - FS19/CP6

### ISSUE THREAD

**Issue by lavenki** [Courseplay/courseplay#3728]
Beacon lights don't work even in vehicles that have no courses loaded.

Tested if removing Courseplay restores Beacons, confirmed Courseplay causes bug.

_Aware of same issue #3204, however issue #3204 points out "Beacon mode not working"._ 

I'm pointing out that Courseplay messes with Beacons of all vehicles, even restarting does not fix it.

**Comment by Tensuko** [comment]
They do:
![fsScreen_2019_05_02_21_48_46](https://user-images.githubusercontent.com/27344744/57102563-14febd80-6d24-11e9-86e4-40bc1cfc3bec.png)
logfile ?
https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
No response.
Closed untill a logfile appears with actual version.
