### ISSUE TITLE
Application exit request forced map "Rassvet" bag Closing the game 

### ISSUE THREAD

**Issue by terrorbaff** [Courseplay/courseplay#3729]
Hello dear developers of the course. Faced with the problem of hanging the game on the map "Dawn" when recording the course of the truck from the combine to the Elevator. I begin to record the course and the game hangs away. The version of the course 205 (last).

**LOG**
> 2019-05-03 09:02 Warning (script): 'setWorldTranslation': Argument 1 has wrong type. Expected: Float. Actual: Nil 
> 2019-05-03 09:02   ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (791): expectedType == Value::VoidType || expectedType == Value::ClassType
> 2019-05-03 09:02 LUA call stack:
> 2019-05-03 09:02   dataS/scripts/sounds/SoundNode.lua (229) : setWorldTranslation
> 2019-05-03 09:02   dataS/scripts/sounds/AmbientSoundManager.lua (279) : setWorldPosition
> 2019-05-03 09:02   dataS/scripts/BaseMission.lua (1603) : update
> 2019-05-03 09:02   dataS/scripts/FSBaseMission.lua (1971) : update
> 2019-05-03 09:02   dataS/scripts/missions/mission00.lua (469) : update
> 2019-05-03 09:02   dataS/scripts/main.lua (1863) : update
> 2019-05-03 09:02 Application exit request forced.
> 2019-05-03 09:02 Application exit request forced.  

P.S I apologize for my English , translated by a translator , I am a Russian-Speaking user.

**Comment by Tensuko** [comment]
Does this happen with all Tractos, or just that one Truck.
What Truck is it ?
Can you give us a full logfile ?
Just drag and drop the log.txt into the comment box.

**Comment by terrorbaff** [comment]
Track MB Arocs
[log.txt](https://github.com/Courseplay/courseplay/files/3141023/log.txt)

**Comment by Tensuko** [comment]
You have some Mods with Errors. I am sorry, but we can't help you with Errors in other Mods here.
Ask in a Forum for help to get the description right.

I think that is the problem:
Load mod: FS17_Arocs (Version: 1.2.0.0) (Hash: 5dba2924ff962c1d1625c0f6e1bf581d)
Error: Unsupported mod description version in mod FS17_Arocs

More Errors:

Load mod: LS19_MKS100_OY (Version: 19.5) (Hash: 965b342556eba24ac284cc7f8650aaa6)
Error: Failed to open xml file 'C:/Users/DEN4IK/Documents/My Games/FarmingSimulator2019/mods/MA7_lisier/modDesc.xml'.

Load mod: MA7_lisier (Hash: 4f404045ed1e35ed7ab6ff1f630ef7fe)
Error: Missing descVersion attribute in mod MA7_lisier

Load mod: FBM19_prefab_FrontloaderHosesConnector (Hash: 13fb64fd2650f7cf0940bf14315f32dd)
Error: Missing descVersion attribute in mod FBM19_prefab_FrontloaderHosesConnector

Load mod: FBM19_MengeleMaisblitz300 (Version: 1.0.0.0) (Hash: 9c81aa0fc6e84430aba0938f6c5a1116)
Error: Failed to open xml file 'C:/Users/DEN4IK/Documents/My Games/FarmingSimulator2019/mods/FBM19_prefab_FrontloaderHosesConnector/modDesc.xml'.

Hope you get your Mods Error free.
When Mods are Error free and you still get a problem, feel free to make a new Issue.

Closed.
