### ISSUE TITLE
Error: Running LUA method 'update' - turn.lua:581: attempt to index local 'curTurnTarget' (a nil value)

### ISSUE THREAD

**Issue by OnkelH0tte** [Courseplay/courseplay#3730]
[log.txt](https://github.com/Courseplay/courseplay/files/3143113/log.txt)

Game crashed

Einziger Fahrer der gerade über CP unterwegs war, war der Gülledünger (der Große mit 36m original Giants, komme gerade nicht auf den Namen) kurz danach ging nur noch ein hard reset des Spiels

**Comment by Tensuko** [comment]
Mehr details, welches Fahrzeug in welcher Situation.

**Comment by OnkelH0tte** [comment]
Traktor war der T8.435 mit Güllegespann PG II 35 und SBH4 36. Während des Düngens vom Feld. Was er gerade gemacht hat, kann ich nicht sagen, war nicht dabei ;). Danach crashte das Spiel.

**Comment by pvaiko** [comment]
Reopen if still a problem.
