### ISSUE TITLE
Mode 1 not load or load only some fruits at start

### ISSUE THREAD

**Issue by piropiro24** [Courseplay/courseplay#3731]
even changing start point, for some course not fill the tippers and start looping. For other course fill only few fruits (even if filling set to 100%) and start corse in loop
![image](https://user-images.githubusercontent.com/49072277/57162943-11d10380-6df0-11e9-9730-bd81e9ebc82c.png)

**Comment by FS19-CP** [comment]
I've found that the starting point and first waypoint or two need to be straight, which yours are.

But, i've also found that I'll have loading issues if my stop point on the loop isn't fairly close to the start. I don't see a stopping point in your frame, try it with it a few meters back from the start, and see what happens. I've had no issues, other than manure, which is expected... no actual fill point for it, in my case.

**Comment by piropiro24** [comment]
You are right! Putting the first three waypoint in straight and last waypoint close to the start works well.
Thanks!
