### ISSUE TITLE
Driver ignores timer for waiting point in mode 5

### ISSUE THREAD

**Issue by XPiRiJenZ** [Courseplay/courseplay#3733]
Hi! 
As the topic says: I've recognized that the driver is ignoring the timer-settings for halt at waiting points in mode 5 and stops there, until I tell him to continue.

Tested with v205

**Comment by Tensuko** [comment]
Stimmt.

Man könnte eventuell noch ne Timeranzeige einbauen an der stelle, wo bei Mode1 die Anzahl der Abfahrten steht (?).

**Comment by XPiRiJenZ** [comment]
Entweder dort, oder wie der Timer für die Restdauer für Feldarbeiten im unteren Teil des HUDs.

**Comment by sesmo** [comment]
On mode 4 the driver ignores the waiting point too... Should I make a video?

**Comment by pvaiko** [comment]
@sesmo no, thanks, we know why it, just in the process of clarifying the wait point behavior in different modes.

**Comment by XPiRiJenZ** [comment]
getestet mit 214 und funktioniert einwandfrei. Danke

**Comment by Tensuko** [comment]
Ok.
Fixed. Closed.
