### ISSUE TITLE
Return to start

### ISSUE THREAD

**Issue by Horozor** [Courseplay/courseplay#3736]
How to disable the return to the start? After the end of the work, the tools do not fold up correctly and cannot be opened. In the route generator, the function is disabled, but it still works. It comes from the version 195

**Comment by Tensuko** [comment]
This will be changed as option in the HUD in the near future.
Right now he return to start only if the startpoint is in the headlands.
A bit more patient pls.

**Comment by pvaiko** [comment]
@Horozor I'll remove 'return to start' from the course generator and it'll become an option you can set in modes 4 and 6. Currently it'll return to start when the work ends in the middle of the field, that is, the course starts with a headland.

I'm not aware of any folding issues, if there are any you'll have to describe it in more detail (surprise, surprise), what vehicle, what tool, what exactly 'do not fold up correctly' and 'cannot be opened' means as we can't read your thoughts (yet).
