### ISSUE TITLE
Slurry Sprayer not working with Mode4 - Needs to be refilled

### ISSUE THREAD

**Issue by GerFs** [Courseplay/courseplay#3737]
![fsScreen_2019_05_05_16_10_11](https://user-images.githubusercontent.com/50300125/57197363-495dbe00-6f5e-11e9-83a0-dd5e9401ceed.png)

**Comment by Tensuko** [comment]
No ?!!! - logfile ?
https://github.com/Courseplay/courseplay/wiki

**Comment by GerFs** [comment]
no matter if i use mods or ingame equipment it wont drive ive tried manually filling spreader ive set it to helper buys everything but it still wont work it on the right course and field as it has worked the odd occasion more so not i have deleted all mods now and only using ingame eqipment but it still wont work

**Comment by GerFs** [comment]
i have also tried uninstalling courseplay and downloading it again but still no sucess

**Comment by Tensuko** [comment]
We would still like to see a logfile.
I will check that Issue too, but next time find a proper Titel!

**Comment by GerFs** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3145891/log.txt)

**Comment by Tensuko** [comment]
Just to show you that it actually works:
![fsScreen_2019_05_05_20_33_56](https://user-images.githubusercontent.com/27344744/57198620-2a1e5b00-6f75-11e9-8db7-43954a530f6b.png)

Load mod: courseplaymaster (Version: 6.01.00195)
Get a proper Version here: https://github.com/Courseplay/courseplay/releases

Mod with Error:
Error: Failed to open xml file 'C:/Users/i5/Documents/My Games/FarmingSimulator2019/mods/FS19_HauerKonsolenPack/modDesc.xml'.
Load mod: FS19_HauerKonsolenPack (Hash: 7db198b564910a7f1303b640c3026427)
Error: Missing descVersion attribute in mod FS19_HauerKonsolenPack

Not sure if any of your Mods got a conflict with CP, but I won't check them all.
Delete the Mod with error and download CP V208 and delete the old one then try again.

**Comment by Tensuko** [comment]
Closed, couse of inactivity.
