### ISSUE TITLE
Unable to get into the HUD

### ISSUE THREAD

**Issue by Lockna** [Courseplay/courseplay#3738]
Hey! I'm unable to get into the HUD. When I rebind the key to another button, it still doesn't work. When I get into a savegame, it asks me if I want to scan all fields, I press yes and with the Honorar I also press yes. Can anyone help me?

**Comment by Tensuko** [comment]
Logfile ?

**Comment by Tensuko** [comment]
Also, set the active tool (key G) to the tractor to make the HUD open with the binded key.

**Comment by maphi13** [comment]
I have this problem to, I startet a new Savegame at Felsbrunn without other mods than courseplay in the "Farming Simulator 19/ mods" ordner. I have installed the latest Cp Version, of course. I was in all standard vehicles with set key G in the tractor, but the "right mouse menu"(HUD) didn´t opened.
As you can see from my logfile, there are a lot of warnings :-(.
https://gist.github.com/maphi13/5ff8c20557526deda3a2ef64fced6e3e
I look forward to hear from you soon.
 
Philipp

**Comment by Tensuko** [comment]
@maphi13 
there are tons of Warnings for Keyassigning. Something is wrong there but I can't rly tell you what.
I wouldalso suggest you to else delete your inputbindings or rest it in the ingame menu.

**Comment by maphi13** [comment]
OK, thanks for your answer.
--
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.

Am 06.05.19, 17:53, Tensuko <notifications@github.com> schrieb:

@maphi13
there are tons of Warnings for Keyassigning. Something is wrong there but I can't rly tell you what.
I wouldalso suggest you to else delete your inputbindings or rest it in the ingame menu.

**Comment by Lockna** [comment]
Where can I see the logfile?

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Lockna** [comment]
https://pastebin.com/e6T0x8PV
This it the whole logfile

**Comment by Tensuko** [comment]
@pvaiko 
??
2019-05-06 18:59 WARNING: COLLISION MESH FOR 'aiCollisionTrigger' IS BEING COOKED AT RUNTIME - THIS WILL NOT WORK ON CONSOLES

2019-05-06 19:00 Error: Running LUA method 'update'.
2019-05-06 19:00 C:/Users/Raphael/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00208/CpManager.lua:239: attempt to call method 'getFields' (a nil value)

Anschließend LUA Callstacks mit nur CP drin...

**Comment by Lockna** [comment]
Hmm, and what are you suggesting?

**Comment by pvaiko** [comment]
Upgrade your FS19 to the latest, you have an ancient version running:
  Version: 1.0.0.0 b2614

Reopen this issue if you still have a problem.

**Comment by Lockna** [comment]
Hmm, now I can get into the HUB with STRG+LÖSCHEN, but I can't click anything. Not even the x to leave the HUD. I'm only able to get out with STRG+LÖSCHEN again. When I hover overa button it gets green or blue but when I click on it. Nothing happends

**Comment by Tensuko** [comment]
New logfile pls with debug 18 (hud actionns) when you try to open/close the hud and try to klick anything.

**Comment by Lockna** [comment]
https://pastebin.com/1nRAETc2
what do you mean with debug 18?

**Comment by Tensuko** [comment]
Ehm yea that way my bad. You won't be able to turn on debug channel 18 if you can't get in the HUD...

However I don't know what is this:
Info: Same productKey VID:'738' PID:'2217' already defined in file C:/Users/Raphael/Documents/My Games/FarmingSimulator2019/inputDevices/SaitekHeavyEqptWheelPedal_PS4.xml
  Info: Same productKey VID:'738' PID:'2218' already defined in file C:/Users/Raphael/Documents/My Games/FarmingSimulator2019/inputDevices/SaitekSidePanelControlDeck_PS4.xml

Warning: Failed to download input devices.

Warning: Mod-List download failed... retry in 2.000041 s. 0 trail

Warning: Mod-List download failed... retry in 4.018467 s. 1 trail

This looks like a corrupted file for your savegame, so try it out in a brand new one too:
2019-05-07 16:19 Error: Failed to open xml file 'C:/Users/Raphael/Documents/My Games/FarmingSimulator2019/savegame2/weed_growthState.xml'.

I can't say more about your logfile. Mostly just compare to my one if I got any of those msg too.

**Comment by Lockna** [comment]
Hmm, i tried a new savegame but its the same
