### ISSUE TITLE
Keycommand "CP: sofort abfahren" does not work, v 6.01.0209

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#3740]
Hey Guys,
i have the problem, that the Keycommand "CP: sofort abfahren" does not work
all other keycommands work
i have designated new keys for the commands, but with the original keys, this one also does not work - everyone else already
with a klick in the cp-hud this is working,
![fsScreen_2019_05_06_09_22_46](https://user-images.githubusercontent.com/24860501/57221353-34853700-6fff-11e9-80df-f7362466f929.png)
 
i have also no double assigned this key

lg
andreas

**Comment by Tensuko** [comment]
Einige Keybinds scheinen nur zu gehen, wenn man den Tracktor ausgewählt hat und nicht die Tools.
Ich weis aber nicht, in wie weit der Modus wichtig ist, ob das Kommando da so mit dem Keybind funktioniert.

**Comment by andreasthu** [comment]
ok, danke für die info,
werd ich dann probieren ob es einen unterschied macht ob der Traktor oder der Hänger ausgewählt ist.
Habe ich beim mode2, Drescher abfahren, folgende Gespanne:
1. Man TGS 18.500 4X4 mit Krampe KS950 Kippsattel 
2. Valtra S mit Kröger TAW30 ASW
es ging vor einigen Wochen jedenfalls, k.a. irgendwas mit version zw 01.0150 und 01.190 noch, also vor den 200er versionen

lg
andreas

**Comment by andreasthu** [comment]
ok, 
habs versucht, es ist egal, ob der Traktor oder der Hänger aktiv ausgewählt ist,
das keycommand strg-links + D funktioniert bei beiden einstellungen nicht.
der klick auf "sofort abfahren" im cp-hud immer, egal was für ein gerät angewählt bzw aktiv ist.
lg
andreas

**Comment by Lupo36** [comment]
Kann ich bestätigen. Die  Tastenbelegungen für weiterfahren und sofort abfahren funktionieren nicht. Bei Version 151 funktionierte es.

**Comment by Tensuko** [comment]
Könnt ihr mal folgendes Ausprobieren:
Belegt die Taste nach euren wünschen, benutzt die Funktion einmal mit der Maustaste.
Danach könnte auch der Keycommand funktionieren.
Bei mir war es mit V236 so gewesen bei Fahrer einstellen/entlassen.

**Comment by andreasthu** [comment]
Ok, habs versucht. 
Abfahrer einstellen macht er beim zweiten keycommand. 
Sofort abfahren auch nicht nach dem 10. mal drücken.
Hab diese keybinding schon an x verschiedene Tasten gegeben,  keine funktionierte.
Lg
andreas

**Comment by Lupo36** [comment]
Lieber Tensuko,
"Sofort abfahren" funktioniert definitiv nicht. Welche lua ist denn dafür zuständig, vielleicht kann ich für mich da was ändern?

**Comment by Tensuko** [comment]
Das weis ich leider nicht. Kann auch an Mode2 liegen, denke das es in Mode2.lua steht. Wie ist das denn z.B. In Mode6 beim Stroh sammeln oder so. Funktioniert das da ?

**Comment by Lupo36** [comment]
Auch nicht, der keycommand für "Sofort abfahren" scheint in keinem Mode zu funktionieren. Wie gesagt, bei Version 167 klappte es noch, ab 168 nicht mehr.

**Comment by Tensuko** [comment]
Glaube zwar nicht, dass es mit 288 mitlerweile funktioniert, aber es steht momentan nicht auf priorität.

**Comment by Tensuko** [comment]
Ich packe das mal mit zu einem anderen Issue um ein wenig die übersicht zu behalten:
#4826

Mache hier zu.
