### ISSUE TITLE
[Frage] courseStorageXXXX.xml

### ISSUE THREAD

**Issue by plexten** [Courseplay/courseplay#3741]
In den generierten Kursen ist ein y- Wert vorhanden, muss dieser sein oder kann man diesen irgendwo abschalten. Ohne diesen y- Wert könnten die Kurse in dem CourseDrawer bearbeitet werden.

### <course>    <waypoint1 speed="1" angle="176.62" pos="466.58 222.53 -848.28" crossing="1"/>
    <waypoint2 speed="20" angle="176.59" pos="467.17 223.56 -858.28"/>
    <waypoint3 speed="24" angle="177.56" pos="467.77 224.65 -868.33"/>
    <waypoint4 speed="24" angle="-176.56" pos="467.87 224.91 -870.81"/>
    <waypoint5 speed="24" angle="-168.77" pos="467.78 225.08 -872.33"/>
    <waypoint6 speed="25" angle="-160.10" pos="467.48 225.24 -873.84"/>
    <waypoint7 speed="25" angle="-150.93" pos="466.95 225.41 -875.32"/>

**Comment by Tensuko** [comment]
Wo ist da der y-Wert ?
Letzten Endes würde ich sagen X und Y sind die Koordinaten des Wegpunktes auf der Map.

**Comment by pvaiko** [comment]
@plexten das wurde hier mehrmals diskutiert (auch mit dem CourseDrawer Entwickler), suche nach CourseDrawer
