### ISSUE TITLE
Combine with wide header leaves small unworked areas on turns

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#3742]
![fsScreen_2019_05_06_20_28_31](https://user-images.githubusercontent.com/21023840/57246548-d297f200-703d-11e9-8020-7491d82c23af.png)

**Comment by Tensuko** [comment]
That got something to do with the turn and the wide Cutter. I think it starts at 10 or 12m.

**Comment by pvaiko** [comment]
You already opened an issue with this #3558 leave this one open as it is in English.

**Comment by Tensuko** [comment]
Fixed with V214+
![fsScreen_2019_05_12_11_25_11](https://user-images.githubusercontent.com/27344744/57580361-c500c300-74a8-11e9-8917-0279db202f02.png)
![fsScreen_2019_05_12_11_25_43](https://user-images.githubusercontent.com/27344744/57580362-c6ca8680-74a8-11e9-9638-abd04f793287.png)
Closed.
