### ISSUE TITLE
Alternate load/unload route for mode 4-6 ?

### ISSUE THREAD

**Issue by Simon-AK** [Courseplay/courseplay#3743]
It's more like a question or a suggestion than an issue, but : 
Is it possible to have multiple alternate route when refilling tool or unloading ?
So let say I have a fieldwork route to collect grass with my Loading Wagon, my merged route unload the grass in a Silo Bunker, but after a couple run, it get too high and tractor get stuck in the bunker.
So is it possible to merge multiple unload route to one fieldwork so that the tractor can unload at multiple unload point.
So he'll unload at the first route, then the second, then the third, etc, then back to the first and so on.

**Comment by pvaiko** [comment]
This would be nice but we have no time to implement it.
