### ISSUE TITLE
seeding gap 

### ISSUE THREAD

**Issue by kartal2339** [Courseplay/courseplay#3745]
when i seed it leaves some gap below photo
![fsScreen_2019_05_01_00_09_17](https://user-images.githubusercontent.com/33800597/57253501-8d80b980-7057-11e9-9388-90c112749e76.png)

**Comment by pvaiko** [comment]
That course looks really weird, how was that generated?

**Comment by dezza69** [comment]
Does that unit have a seperate seed tank and drill mechanism??  As I've notice the new Horsch Slurry trailer with the smaller back unit (all I've tested it on) does a similar thing.

If this is the case, is it possible Courseplay is using a trigger from the front trailer instead of the second linked trailer unit?

**Comment by kartal2339** [comment]
it is a amazone seeder with a seed tank and solid fert tank on seeder not seperate one... and it is a custom seeder..and it leaves gaps lile that on two sideof field

**Comment by pvaiko** [comment]
What do you mean 'custom' seeder? Is that a mod? Can you reproduce this with the standard equipment?

**Comment by Tensuko** [comment]
Still no Screenshot of the Course and Settings of the Generator.

**Comment by kartal2339** [comment]
sorry ..the seeder is a default one not a mod..

![fsScreen_2019_05_09_20_03_20](https://user-images.githubusercontent.com/33800597/57472331-e473d200-7295-11e9-8461-cd6c717c327f.png)
![fsScreen_2019_05_09_20_01_26](https://user-images.githubusercontent.com/33800597/57472345-ec337680-7295-11e9-9a2d-d23ec05b5e9e.png)
![fsScreen_2019_05_09_20_06_50](https://user-images.githubusercontent.com/33800597/57472426-16853400-7296-11e9-8907-72c111edd443.png)

**Comment by pvaiko** [comment]
And if we had a log we also knew which version you are using...

Certainly not the last one.

**Comment by kartal2339** [comment]
i couldnt send a log because of its 100mb and i cant transfer it to gist

**Comment by kartal2339** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3164030/log.txt)

**Comment by pvaiko** [comment]
Can you reproduce this on a standard map with no other mods loaded? I can't.

**Comment by kartal2339** [comment]
i create a new game and i install version 6....212 with same tractors and seeder i cant create course because of i cant choose field... but at my fenton forest save i disabled  real dirt my issue solved

**Comment by kartal2339** [comment]
sorry it is about custom modding group jd 8r mod.. it leaves gap pnly with this truck and with other implements like cultivator

**Comment by kartal2339** [comment]
it leaves gap only with 8r truck also with jhhg&siid  8r
