### ISSUE TITLE
Mode 2 Combi, Start From Here

### ISSUE THREAD

**Issue by Simon-AK** [Courseplay/courseplay#3746]
Hello sorry to bother you again,
Is there a way to start our Combi run right where the truck stand ?
On extreme large field, it's sometime annoying to drive to the start of the route or wait for the worker to go by himself.
And while I'm here, sometime the truck in combi get stuck doing something when you start the run,  like he wanna go to the silo empty the trailer, but you want him to empty the harvester, even if you reload the run, he's kinda stuck there.
Is there a way to refresh the run ? Or maybe an option to start the run at search for an harvester.
Thx again

**Comment by Tensuko** [comment]
#3311 
Wait till we reworked the Mode2 (+Mode3) then we will see what else we can do and what is possible.
