### ISSUE TITLE
Mode4 issue (headland turn)

### ISSUE THREAD

**Issue by OldFamous** [Courseplay/courseplay#3748]
I don't know what is happend but when I generate a course(seeding or cultivating) the tractor is just acting weird in corner's. Im not sure whats going wrong but some time's the tractor is just driving in circles and some time's the tractor will get the right line but he allready missed my corner's for seeding or cultivating.

This are my log with debug channels 12 and 14 activated and some screenshots for the seeding course.
[log_Seeding.txt](https://github.com/Courseplay/courseplay/files/3153496/log_Seeding.txt)
![fsScreen_2019_05_07_17_53_18](https://user-images.githubusercontent.com/5245750/57314468-f6b50b00-70f1-11e9-9e49-2e94cf2e8c88.png)
![fsScreen_2019_05_07_17_53_43](https://user-images.githubusercontent.com/5245750/57314470-f6b50b00-70f1-11e9-921b-3f3821e4c0b8.png)
![fsScreen_2019_05_07_17_53_56](https://user-images.githubusercontent.com/5245750/57314471-f6b50b00-70f1-11e9-9600-a49aab6c1852.png)
![fsScreen_2019_05_07_17_54_00](https://user-images.githubusercontent.com/5245750/57314472-f6b50b00-70f1-11e9-8944-8e787a25fe75.png)

This are my log with debug channels 12 and 14 activated and some screenshots for the cultivating course.

[log_Cultivator.txt](https://github.com/Courseplay/courseplay/files/3153615/log_Cultivator.txt)
![fsScreen_2019_05_07_17_44_11](https://user-images.githubusercontent.com/5245750/57316466-282fd580-70f6-11e9-8201-4a579e04f43e.png)
![fsScreen_2019_05_07_17_44_30](https://user-images.githubusercontent.com/5245750/57316467-282fd580-70f6-11e9-8d06-03b47ad35c56.png)
![fsScreen_2019_05_07_17_44_41](https://user-images.githubusercontent.com/5245750/57316468-282fd580-70f6-11e9-834e-a6373349cc97.png)
![fsScreen_2019_05_07_17_44_49](https://user-images.githubusercontent.com/5245750/57316469-28c86c00-70f6-11e9-807c-f836b9c0ec80.png)

If you need more information just ask and I will provide it.

**Comment by Tensuko** [comment]
Screenshots with the waypoints would help too I guess.
Also the Coursesettings would be interesting.

**Comment by OldFamous** [comment]
Here are the screens with setting's on it.
Seeding,
![fsScreen_2019_05_07_17_52_12](https://user-images.githubusercontent.com/5245750/57319759-a17ef680-70fd-11e9-9357-babf66d8131f.png)

Cultivating,
![fsScreen_2019_05_07_17_43_51](https://user-images.githubusercontent.com/5245750/57319794-b491c680-70fd-11e9-8ae6-384cc85700a9.png)

I don't have screens with waypoints but I have seen them to see if there's the problem, there whasn't anything strange I guess. 
But tommorow I will try again and make some screens with the waypoints.

**Comment by pvaiko** [comment]
Do you know since which version is this happening? Also, if you had a savegame that would be great.
