### ISSUE TITLE
Abfahrer erkennt Fülltyp nicht

### ISSUE THREAD

**Issue by stueja** [Courseplay/courseplay#3751]
Ähnlich zu #3473 / #3483 erkennt der Abfahrer den Fülltyp Milch nicht.
Valtra T6.125
Lizard MKS 8
Karte: Provence
Was kann ich tun?

**Comment by Tensuko** [comment]
Denke mal warten bis der Flüssigkeitstransport Modus aktiv ist :)
An den Kuhstalltriggern muss ich auch noch einiges testen, da dort endlos entladen wird komischer weise.

Aber wie gesagt, muss leider noch etwas warten.
Kannst du das mal mit Wasser probieren ?

**Comment by stueja** [comment]
Ach, das hat mit dem Flüssigkeitstransport zu tun, das hab' ich übersehen. Ich dachte, das Problem betrifft nur Wasser. Wasser geht gar nicht, am Brunnen fährt er einfach vorbei ohne aufzutanken.

**Comment by Tensuko** [comment]
Das wird dann auch mit Gärreste und Gülle nicht funktionieren.
In wieweit da von GIANTS und CP unterschieden wird (flüssig zu fest) kann ich nicht sagen, aber ich weis das es im 17er dafür den Modus für Flüssigkeitstransporte gibt.

Hilft erstmal nur warten.
Closed.
