### ISSUE TITLE
Courseplay won't start and yellow arrow

### ISSUE THREAD

**Issue by N3XTX** [Courseplay/courseplay#3752]
(FS19)

When i have loaded a course or either create one and start the course the tractor won't move, and it shows a yellow arrow (i can only drive the tractor again after i have restarted the game) . i have had this problem before but back then i was able to fix it with an update of courseplay, now that does not work

**Comment by pvaiko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by N3XTX** [comment]
seems that when i've tried to reinstall (update) CP somehow i have not correctly deleted the old one. I did it correctly now and the issues seems to have been fixed
