### ISSUE TITLE
Proposal Slowdown zone

### ISSUE THREAD

**Issue by MikeRohsoft74** [Courseplay/courseplay#3753]
A course at maximum speed. There are problems with curves or triggers because the vehicle is too fast.
With a click in the HUD start slowdown (speed/2) curve or drive over triggers click stop slowdown (max speed)
So the curves and triggers should not be a problem anymore.

**Comment by Tensuko** [comment]
I never had a too fast Vehicle...
Also normaly when a trigger is near, he should slow down already.

**Comment by MAOGAMI** [comment]
Actually slowdown zone could be great, yesterday I was hauling lime from sellpoint to my farm and after some runs my worker just started to hit a tree growing near lime station. Maybe this slowdown zone could help.

**Comment by FS19-CP** [comment]
I've been having more luck with using the recorded speed, but making sure I'm extremely methodical in my course recording....slowing, swinging wide for posts, etc.. then just running full speed in the straights.  You get realistic motions, but speed when it's needed.

**Comment by MAOGAMI** [comment]
> I've been having more luck with using the recorded speed, but making sure I'm extremely methodical in my course recording....slowing, swinging wide for posts, etc.. then just running full speed in the straights. You get realistic motions, but speed when it's needed.

I'm doing the same thing and thats why I'm surprised about my course. I re-recorded it few times but I gave up. When he stucks on that tree I just stop hauling

**Comment by Tensuko** [comment]
Never had a problem with the Speed too, as I said. We will discuss this if can do anything, but I am pretty sure when a trigger gets approached, he already slows down. When that is not even possible, then you just go to fast...

**Comment by MikeRohsoft74** [comment]
That's right, it's slowed down before a trigger. But with fully loaded trailers and small tractors, it comes a little late and the tension drives over this trigger.
Using FillTypesMass Adjust

**Comment by Tensuko** [comment]
How fast is your smal tracktor going with a full loaded trailer (capacity?) ?
A Video of it would be great...

**Comment by fudoido** [comment]
i made a simmilar suggestion some time ago. Since CP creates closer waypoints when curving, it could detect when those waypoints are getting close while on full speed and slow down to acomplish the curves, simmilar to the way it detects the pause points and slows down also (but brakes to stop on this case).
by detecting in advance that set of waypoints closer to each other, it could slowdown to the "field speed" for example.

**Comment by Tensuko** [comment]
We discussed this and this won't get implemented, couse we record the speed for such reasons.
If your Trucks are to fast, slow down when recording the course, to keep it at a more realistic speed.
Sry. Closed.
