### ISSUE TITLE
Proposal tank route

### ISSUE THREAD

**Issue by MikeRohsoft74** [Courseplay/courseplay#3754]
Extra distance to be marked for refueling.
Should work similar to loading attachments or unloading trailers.
A field course has been selected. Another course has been selected and marked as refuel.
Then it should be so: If tank <n% stop work, drive course refuelling and start again with work.
Written amateurish.

**Comment by Tensuko** [comment]
Only one Refillcourse per Fieldwork Course.
But you can also make one Course that bypass all refills (might work).

Will discuss this in team if we do any kind of fuel refill, but I doubt.
Closed.
