### ISSUE TITLE
Proposal Change driving modes

### ISSUE THREAD

**Issue by MikeRohsoft74** [Courseplay/courseplay#3756]
Mode transfer course to field
mode change 
Mode field work course fieldwork
mode change 
Mode transfer course to farm

**Comment by Tensuko** [comment]
In LS15 I made a Course to the 1st WP of the Field and from last Waypoint back to the start.
Merged that with the + (starting with Farm_Field+Field_Work+Field_Farm).
Try it out, maybe that still works, but won't make a Mode change.
Closed. 1st but will discuss the similar old working stuff.
