### ISSUE TITLE
Bunker silo unloading speed

### ISSUE THREAD

**Issue by aviator64** [Courseplay/courseplay#3759]
I saw some closed issues on this topic but I may have a new piece of the puzzle.

If I load my course and start a tractor with a full trailer a short distance away from the bunker, then it sets a proper reversing speed and unloads correctly.

However - if the tractor first goes to the field and fills from the chaff harvester, then when it reaches the bunker it will go too fast and continue unloading beyond the bunker.

I have been able to repeat this multiple times.

Please see attached screen shot with the unbelievable reversing speed shown!

![20190508153343_1](https://user-images.githubusercontent.com/19857526/57384107-e1021d00-71a7-11e9-95a8-89599e10dc6c.jpg)

On a related matter - the leveling/compacting mode does not seem to be implemented yet, or am I missing something?

**Comment by Tensuko** [comment]
Mode2 still doesn't have the right calculation and that is all about the Issue.
If I use Mode6 (collcting from field) it all works fine.
And yes, Compacting is not implemented yet.
#3311 
Closed.

**Comment by sashh82** [comment]
i have same problem idk why :-(
