### ISSUE TITLE
Mode 2, Real Life, Suggestion Video

### ISSUE THREAD

**Issue by FS19-CP** [Courseplay/courseplay#3760]
In #3739, a conversation was started with @pvaiko on real-life experience in corn chopping, in relation to Mode 2. I just finished up a video, demonstrating what I was explaining there.

It's about twenty minutes, but it goes over a myriad of details... things I've picked up over the years driving trucks and operating forage harvesters for a local dairy operation, that I've applied and scaled to my FS19 hobby with Courseplay. I've always wanted more out of Mode 2, and this seemed like the time to get my opinion into the mix.  I'm not a developer, and just barely code for tiny purposes, so if this seems like a complication.... I wouldn't question it. Lol. 

But, if reality is the goal, this is something to look into... and, beyond the realism factor, this would seem to streamline a lot of issues with the operation of Mode 2, as well as the fieldwork, when it comes to corners.

YouTube link below.
https://youtu.be/b76BfGVUx_w

**Comment by FS19-CP** [comment]
We also use this technique with combines, but clearly altered for their purposes... the wheat we cut in our local is in borders, and generally a border is three passes. So, left side of border, turn left, right side of border, turn left, right side of border, turn left, left side of border, turn left, center, left, center... then its a right turn to start the next border. Or vice versa

Not having borders in the sim, it wouldn't need to be that complicated of a pattern, but the idea of the leapfrogging here is that the pipe is mostly going to be out of the crop for unloading.

**Comment by pvaiko** [comment]
@FS19-CP this video is amazing. Thank you, this is one of the most valuable contributions to CP I'v ever seen.

**Comment by FS19-CP** [comment]
Glad to help!

I've always loved the efficiency of the system we have ran, and thought implementing it into CP would be pretty awesome. I mimic the real life stuff I do, so end up with very fast-production work cycling through all fields... a functional Mode 2 is crucial. The current Mode 2 forced me to rework my systems as a patch until you guys worked your magic... it just so happens that the way I would do it helps the current Mode 2 work... and then I realized that you guys might want to see it.

Much appreciated.

**Comment by GeorgeEarslight** [comment]
@FS19-CP Thank you for the insight on real farming work routines. It's very interesting for us couch farmers. It's probably not the easiest thing to translate all this information in the mod itself, but it helps a ton to steer it in the right way.

**Comment by FS19-CP** [comment]
By the way, guys, my profession these days is in video, the kind with real cameras... so creating, "shooting," and editing FS videos is a fairly simple thing for me... if you would want further demonstrations of any task, just let me know.

**Comment by limoman39** [comment]
Great video FS19-CP,  this is the type of feedback needed to move forward.  I would agree that the harvester portion of this course could be used in any harvesting situation.  
Great job everyone working on CP, hope this all helps.

**Comment by pvaiko** [comment]
@FS19-CP I'm working on changing the fieldwork pattern to accommodate multiple blocks. What is the minimum and maximum number of rows you want to skip?

**Comment by FS19-CP** [comment]
I would say the minimum would need to be one, even if it's not used often. There are just some field sizes that will require a direct u-turn no matter what, at least once.... usually the last turn is the culprit.  

For maximum, I would say anymore than six rows would start becoming a time-waste... but, multiple choppers on a field would change that. It seems to often be four rows that are skipped, then three or two to finish the pattern.... but I'm also on a map that doesn't have massive fields. I still think an average of four would work well though.

**Comment by GeorgeEarslight** [comment]
> multiple choppers on a field would change that
Since you mentioned multiple choppers, would it be easy for you to upload a video with two choppers working together?

**Comment by Tensuko** [comment]
Thanks for all the Suggestions, a lot of them have made it into the Release Version already.
We also have some other open Issues for Suggestions.
