### ISSUE TITLE
FPS Drops with Fendt 1000 Series

### ISSUE THREAD

**Issue by MaLouPa** [Courseplay/courseplay#3761]
Well, i´m still having this Problem with v209/210 etc.

any tips for me? Issue comes when i load the first Course and start it. Suddenly my FPS drops from 60 to under 20.

_Originally posted by @MaLouPa in https://github.com/Courseplay/courseplay/issues/3280#issuecomment-490845158_

**Comment by Tensuko** [comment]
Reopened the other Issue.
This one Closed.
