### ISSUE TITLE
Just an FYI for people the new Man TGX Tanker on ModHub does not play nice with Courseplay

### ISSUE THREAD

**Issue by cwattyeso** [Courseplay/courseplay#3762]
Discovered rather painfully again today that another mod released on the Giants in-game ModHub does not play nicely or seem compatible with Courseplay. The Man TGX Tanker Truck that released yesterday, has the same issue found with the Man IT Runner Truck released a while back in that once you purchase it in game, you'll find the next time you try to save the Game will Lock-Up/Freeze on the Saving Screen, this will force you then to force close the game, which will then delete all the files in that particular savegame folder, forcing you to have to copy files back from one of your savegame_backup folders.

I think the cause is down yet again to the Mod Author creating his own vehicle types which is evident in the moddesc file which has all this extra crap in it:

	<vehicleTypes>
	<type name="man_milk" parent="base" filename="$dataS/scripts/vehicles/Vehicle.lua">
        <specialization name="ikChains" /> 
        <specialization name="wheels" />
        <specialization name="crawlers" />
        <specialization name="slopeCompensation" />
        <specialization name="speedRotatingParts" />
        <specialization name="enterable" />
        <specialization name="fillUnit" />
        <specialization name="motorized" />
        <specialization name="drivable" />
        <specialization name="aiVehicle" />
        <specialization name="aiImplement" />
        <specialization name="articulatedAxis" />
        <specialization name="lights" />
        <specialization name="attacherJoints" />
        <specialization name="powerTakeOffs" />
        <specialization name="suspensions" />
        <specialization name="connectionHoses" />
        <specialization name="honk" />
        <specialization name="wipers" />
	<specialization name="fillVolume" />
        <specialization name="frontloaderAttacher" />
        <specialization name="bunkerSiloCompacter" />
	<specialization name="fillTriggerVehicle" />
	<specialization name="waterTrailer" />
	<specialization name="dischargeable" />
	</type>

	</vehicleTypes>

**Comment by Tensuko** [comment]
Good to know.... thx for the Information, but I wonder why ppl always got to make their own Vehicle typ... I start think some ppl don't know what this is for and just say: 'Hm, I name my Vehicle like that'.

**Comment by pvaiko** [comment]
Should not happen anymore
