### ISSUE TITLE
Vertrag / Mission: Gerät muss aufgefüllt werden

### ISSUE THREAD

**Issue by stueja** [Courseplay/courseplay#3763]
Ich versuche, eine Mission zu erfüllen. Die Geräte sind geliehen: ein Massey Ferguson 7700 und eine Kartoffelsämaschine Grimme GL 860 Compacta. Die Sämaschine ist zu 100% gefüllt. Nach Kursgenerierung und Klick auf "Abfahrer einstellen" meldet CP "Gerät muss aufgefüllt werden" und fährt nicht ab.
Es fällt auf, daß über den "Kartoffeln" links unten ein zweites, aber leeres Behältnis genannt ist.
Was kann ich tun?

![Farming Simulator 19 09 05 2019 20_10_06](https://user-images.githubusercontent.com/9169222/57476269-7aa7f800-7296-11e9-967c-5bff1d202ded.png)

**Comment by Tensuko** [comment]
Es fehlt Dünger :)
Solltest du aber im HUD ausschalten können (sollte schon gehen, hab ich ehrlich gesagt nie nach geguckt).

**Comment by stueja** [comment]
Au Mann, Dünger! Das könnte ja auch mal irgendwo in LS dokumentiert sein. Aber vielleicht habe ich auch nur Tomaten auf den Augen. Danke!
