### ISSUE TITLE
Mode1

### ISSUE THREAD

**Issue by Lupo36** [Courseplay/courseplay#3765]
Hallo,
ich würde mich freuen, wenn das Limit der capacity der trailer aufgehoben wird. Beim LS17 konnte man viele Millionen transportieren. Momentan leider nur 999999.

**Comment by Tensuko** [comment]
Das hatten wir schon in einem anderen Issue und dort wurde gesagt, das wir das nicht machen werden.
Mal davon abgesehen, dass es unrealistisch ist.

Ansonsten lese dir dieses Issue durch, dort steht es geschrieben: #3705

Closed.
