### ISSUE TITLE
Tractor does not return to first way point

### ISSUE THREAD

**Issue by RUGhost** [Courseplay/courseplay#3766]
After completing a field work Tractor stop at end point instead of returning first way point. There is no option "Return first point" in course generation window.
![Desktop Screenshot 2019 05 11 - 13 31 44 100](https://user-images.githubusercontent.com/48012198/57566799-3e89aa00-73f2-11e9-8143-11617068298b.png)
![Desktop Screenshot 2019 05 11 - 13 31 28 31](https://user-images.githubusercontent.com/48012198/57566800-3e89aa00-73f2-11e9-8041-320e4caec493.png)

**Comment by Tensuko** [comment]
The option got removed and will be an option in the HUD later. WIP.
Closed.
