### ISSUE TITLE
axion 960: Work tool needs to be refilled

### ISSUE THREAD

**Issue by crimso** [Courseplay/courseplay#3767]
Hello,

Maybe its not courseplay problem so just FYI, when I want to seed with horsche seede and Axion 900 (downloaded from Modhub) the seeding will not start as you can see on the picture below.
![farmingsimulator2019game exe Screenshot 2019 05 11 - 11 54 56 57](https://user-images.githubusercontent.com/2950677/57568225-899cc080-73e4-11e9-9002-008cd6f5cefd.png)
![farmingsimulator2019game exe Screenshot 2019 05 11 - 11 55 08 49](https://user-images.githubusercontent.com/2950677/57568226-8a355700-73e4-11e9-8a0d-59a0de2606fa.png)

My log file:

[log.txt](https://github.com/Courseplay/courseplay/files/3168897/log.txt)

Thank you

**Comment by Tensuko** [comment]
Axion900 doesn't work, its a Mod problem.
Was figured out in another Issue but I can't find where.
Sad but that is the Issue of the Modder of the Axion.
Closed.
