### ISSUE TITLE
Combine folds when full and/or player freezes and combine drives away.

### ISSUE THREAD

**Issue by corrado33** [Courseplay/courseplay#3771]
I searched around and found THIS issue.

https://github.com/Courseplay/courseplay/issues/2969

I seem to be facing the exact same issue with a few of the newest versions of courseplay for fs19. Now, I'm certainly not playing with vanilla fs19, so it may just be me and my choice of mods/map. I've tried a few versions of courseplay, I've tried 159, 182, and 215, they all have the same or similar problems. Interestingly, this happens even when the combine ISN'T completely full. It'll often happen when the combine is only 95% full. 

EDIT: Before you read my ramblings, check my edit below, I replicated the problem in a somewhat "sterile" environment with no other mods using only stock equipment. 

Sometimes, instead of this happening, I'll get the "tractor drives on, player frozen in place" glitch as well. If I let the combine continue after it folds when it is full, it'll eventually reach the end of the course and THEN I'll get the "tractor drives on, player frozen in place" glitch. 

Here is a log file using 215. Let me set the scene for you. I have a save file where I have a john deer 790 (970?) combine attached to an iconik header (although I have confirmed that this happens with a stock john deer header from the vanilla game as well). The combine is 95% full. It's on a course that's made for 4 combines to run in tandem, but it is the only one that has run anything so far, it's in the far left lane. I back up a little bit, then tell courseplay to start the course at the next closest waypoint it does so, then... a few seconds later... I get the "player freezes in place, combine keeps driving bug". Luckily.... since I'm actually on this combine, if I click "stop driver" I can recover from this bug, but when I do I find the combine has folded up, despite being full (or rather, still 95% full.) If, however, I happen to NOT be on this combine when this happens, my game is frozen, permanently. I cannot switch to the affected vehicle and I have to force quit the game. 

I know I'm harvesting poppy, a modded crop here, but I can assure you, the same thing happens with canola in the next field over. In the log I enabled debug channel 14 like you asked when this issue came up previously. 
[log.txt](https://github.com/Courseplay/courseplay/files/3170314/log.txt)

I have also reproduced the bug in courseplay version 159.

In THIS version I get the combine folding when it gets... almost full (in this case it was 99% full), then it'll drive to the end of the course (straight there, not following the course)... then I'll get the "player freezes in place, combine drives in circles" glitch. I have attached THAT log here. Again with channel 14 logging enabled. 
[log.txt](https://github.com/Courseplay/courseplay/files/3170332/log.txt)

In both cases I had the combine following a MANUAL course that I had made using the GPS steering mod with a width of 4x the combine. In order to properly make the course, I would "start recording, then insert a wait point indicating the start of the "work area" then drive the course, then insert another wait point indicating the end of the "work area" then end the course." Courseplay automatically adds crossing points to the first and last points of the course as well (verified in the courseplay files.) Regardless, I have attached the actual course here. 
[courseStorage0046.zip](https://github.com/Courseplay/courseplay/files/3170334/courseStorage0046.zip)

I'm currently playing on the NF Marsch map 1.4. 

I love all the work you guys are doing, if I can help in any way please let me know. I've never programmed in lua, but I have plenty of experience using a variety of other programming languages, so I'm sure it wouldn't be too much trouble to learn. 

 What's even more interesting is that... this only just seem to have started happening. I haven't updated courseplay since I first started playing FS19, hence why I was on 159, and while playing through my first map (the DE map), it was fine. Courseplay would just pop up and tell me "hey, the combine needs unloading." And then suddenly, without warning, it just started doing this. I don't know if it's when I updated to 1.3 or what. I'm just unsure. (I typically don't let my combines ever get full since I unload them myself.) I'm going to go try on a brand new save and see if it happens there. 

**EDIT YOU SHOULD CHECK TO SAVE TIME**: Very... very interesting. I tried it on a brand new save on the US (stock) map with the latest (215) (EDIT: I'm sorry, I still had 159 installed at this point, so everything below corresponds to that, with 215 installed it's not much better though, it's just the order of the glitches is reversed, as discussed above. Yes, I did go back and try it with 215 to verify this.) courseplay. I literally only had the courseplay mod enabled, NO other mods whatsoever. I was using the 790 harvester with it's associated 13.7m header, and I was harvesting barley on field 12 (the one that's literally ready to harvest when you start the "medium" difficulty game. At first I generated a course using the course generator and it worked as expected. It reached the point where it was almost full, and the combine backed up and made room for an unloading truck since the pipe was in the fruit. So, feeling a bit defeated and like this was just a problem specific to me, I first dumped a bit of crop onto the ground, then went and created a MANUAL course (I sold the field (so the crops wouldn't get destroyed), recorded the course by driving back and forth across the remaining crops a few times, then bought the field again and let courseplay run the course) and well, WHAD'YA KNOW, it happened exactly like I reported before. Using the manually created course when the combine reached almost full it folded up (despite being full), immediately drove to the nearest point outside of the crop, then drove to the end point of the course at which point I got the "player freezes" glitch. 

So, this is a problem with MANUAL courses, not generated courses. Which is kinda a bummer since generated courses just aren't quite perfect yet. 

If I had to guess, I'd say this is a problem with the "auto backup and make room for the unload truck" routine. Or at least the code to send the vehicle to that routine. There's a glitch in the logic that determines what to do when the combine gets full or a seeder gets empty when using manual courses. And I wonder if I can avoid it by making my combines go the other way around the field therefore making their pipes always accessible. EDIT: No, I cannot, in my original savegame I was already going clockwise and my combine was already on the edge of the field where his pipe was in the open and not blocked by anything.)

EDIT (FINAL... I HOPE): For the record, I think this ALSO affects merging courses, like a seeding course and a refill course. If I merge a manual seeding course with a refill course, my seeder will drive to the end of the seeding course (straight there, not following the course path) before driving to the beginning of the refill course when it gets empty. Very similar behavior except that it... technically doesn't cause problems unless the end of the seeding course is behind a building or something.

**Comment by corrado33** [comment]
Ok, I've done a bit more research into this. It seems that courseplay does NOT like that I'm not using the turn function. 

I mean, that's the entire reason I'm doing manual courses in the first place, because the AI is often stupid and gets caught up on just about everything under the sun.... trees.... lightposts... guard rails, cars, buildings, etc. Especially with large tools like sprayers, huge seeders, weeders, etc. Nothing against you guys of course, sometimes I just like to have manual control over my turns (and... to my knowledge... the turn function doesn't even seem to work that well when creating manual courses anyway but that may have changed in updated versions, I haven't tried it since 159.) I also like manual courses because I can make absolutely sure that they are perfect and that don't miss anything. And lastly, the generated courses are often SLOW. Not in terms of how fast the tractor is going, but just how much ground is gone over twice, how often the tractor stops, picks up the implements, puts down the implements etc etc. It's quicker to just keep going and never stop.

Anyway, I did a little experiment on a fresh save in the US map, on field 12, with the barley, with the S790 and it's 13.7 m header. The first log below is with the generated course.

The second log is with a similar manual course. As you can see, toward the end of the useful part of the log (before it goes off on the endless tangent of the failing update function) the combine goes on an endless loop of a circular course it created around the ending waypoint of the manual course. At this point my player was frozen in place. I had no control until I stopped the driver. 

Both logs are here. I hope they help.

[logGood.txt](https://github.com/Courseplay/courseplay/files/3170566/logGood.txt)
[logBad.txt](https://github.com/Courseplay/courseplay/files/3170567/logBad.txt)

**Comment by pvaiko** [comment]
There's a lot of text here but it is really hard to make any sense of it, we need to be a little more structured here.

I'd recommend that you set up a scenario with a stock map and equipment and post a savegame and your courses and describe the exact steps we need to take to reproduce the problem, describe what the expected behavior is and what you see instead.

BTW, I wonder why do you think that _"AI is often stupid and gets caught up on just about everything under the sun"_, I agree that there are some edge cases it can't handle but in general, as long as everything set up correctly I don't see it being that bad...

**Comment by corrado33** [comment]
> There's a lot of text here but it is really hard to make any sense of it, we need to be a little more structured here.
> 
> I'd recommend that you set up a scenario with a stock map and equipment and post a savegame and your courses and describe the exact steps we need to take to reproduce the problem, describe what the expected behavior is and what you see instead.
> 
> BTW, I wonder why do you think that _"AI is often stupid and gets caught up on just about everything under the sun"_, I agree that there are some edge cases it can't handle but in general, as long as everything set up correctly I don't see it being that bad...

Can do, I will post the save game and courses at once!

**Comment by corrado33** [comment]
> There's a lot of text here but it is really hard to make any sense of it, we need to be a little more structured here.
> 
> I'd recommend that you set up a scenario with a stock map and equipment and post a savegame and your courses and describe the exact steps we need to take to reproduce the problem, describe what the expected behavior is and what you see instead.
> 
> BTW, I wonder why do you think that _"AI is often stupid and gets caught up on just about everything under the sun"_, I agree that there are some edge cases it can't handle but in general, as long as everything set up correctly I don't see it being that bad...

Here ya go boss! All zipped up and ready to go. It's on the ravenport map (US) so you already have that. I just included the save game and the courses. All you have to do is buy the field (12) and load one of the 3 courses and go.
[FarmingSimulator2019.zip](https://github.com/Courseplay/courseplay/files/3170638/FarmingSimulator2019.zip)

**Comment by pvaiko** [comment]
You have three courses in there. Which one is causing a problem?

**Comment by corrado33** [comment]
> You have three courses in there. Which one is causing a problem?

The two ones with "manual" in the name. Course 2 and 3.

**Comment by pvaiko** [comment]
How did you record that course? Why do you have a wait on the waypoint before the last one?

**Comment by corrado33** [comment]
When reading through the manual it says that there should be two waiting points for "fieldwork" courses, one where the "field" starts, and one where it ends. However that doesn't seem to... work, but if you don't include the wait points courseplay is not happy and will not merge refill courses with the course properly (in the case of fertilization or seeding courses).

I was following these instructions...

> You record the course yourself. It is important that there need to be two waiting points. The first one at the position where the work on the field should start, and the second at the position where the work on the field should end. This work area is absolutely necessary for the correct functioning of this mode.

On this page

https://courseplay.github.io/courseplay/en/manual/index.html#driveMode6

**Comment by corrado33** [comment]
Oh and I just drove the harvester along and recorded it with the header up, yes I know the speed was a bit fast but it shouldn't matter in the end, courseplay will always just go the max speed of the implement if the speed in the course is faster than the implement can go. But maybe I'm wrong?

**Comment by pvaiko** [comment]
But if you have a refill/unload course and you load the fieldwork course first and then the refill/unload, it works fine. 

I just tried with your savegame, recorded an unload course, loaded your ManualCourseTest and then my unload, works fine.

Also, no idea why to record a field course manually, would like to see that field where a course generated with 2-4 headlands with this combine does not work properly...

**Comment by corrado33** [comment]
> But if you have a refill/unload course and you load the fieldwork course first and then the refill/unload, it works fine.
> 
> I just tried with your savegame, recorded an unload course, loaded your ManualCourseTest and then my unload, works fine.
> 

Oh awesome! I never really gave my harvesters unload courses because I typically just unloaded them myself on the move because things get messy when you have multiple harvesters and multiple trucks on combi mode, you're bound to have multiple collisions so you have to sit and babysit anyway, you may as well just drive a single truck and not worry about it. Generally if I was slow they'd just wait for me, which was fine/preferable. 

I suppose that's an acceptable workaround though. I just don't understand why there's a discrepancy between generated courses and manual courses. I mean, it's still certainly a bug, but I'll stop complaining about it :) Thanks for the help! Should I close the issue?

**Comment by pvaiko** [comment]
Leave it open, sure, there's a bug as when you start the course, it searches for the second waypoint and considers everything before that the fieldwork course, everything after the unload course. In your case the unload course is only a single waypoint which does not make sense and the code isn't protected against this case.

**Comment by corrado33** [comment]
Ok, will do. Thanks again for the help and quick response and dealing with my ramblings.
