### ISSUE TITLE
Drescher läst sein Schneidwerkzeug beim Wenden wieder ab

### ISSUE THREAD

**Issue by Strawberry93** [Courseplay/courseplay#3772]
Hallo,

mir ist folgendes Probelm aufgefallen. Beim Drescher, wenn dieser entladen wird beim Wenden, dann lässt er nach dem entladen sein Schneidwerkezeug wieder ab im Wendemanöver. Dieses hat dann zur folge wenn das benachbarte Feld Reif wäre dann würde diese Abgeerntet werden und danach macht der Drescher nicht mehr weiter da man ein anderes Frucht im Drescher hat. 
![2019-05-12 (2)](https://user-images.githubusercontent.com/16910900/57585565-3745c780-74ea-11e9-916e-fa67c1395812.png)
![2019-05-12](https://user-images.githubusercontent.com/16910900/57585566-37de5e00-74ea-11e9-8ed0-b34e2935341c.png)

**Comment by Tensuko** [comment]
Hab mal ein paar tests gemacht...

Beobachtung:
- Wenn Turn generiert, Drescher ignoriert warten während abtanken

Issue konnte reproduziert werden:
- Drescher: Warten bei Abtanken auf aktiviert
- Abfahrer provoziert das ausfahren des Rohrs vor oder während des Turns
- Beim einklappen des Rohrs im turn, wird auch das Schneidwerk gesenkt (im turn)

**Comment by Tensuko** [comment]
Tested with V353 and works.
So this seems fixed.
Closed.
