### ISSUE TITLE
Mode 1 No wait for loading

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/courseplay#3773]
Hello!

Mode 1 is working fine when start is a trigger (Like a silo) But i have a big problem with others. Then Silage is ready to be moved from Bunkersilo to Silo i made a course. The trailer should be filled with Conveyor Belt. But the driver does not wait for load he instantly drives on and no silage is in bunke (And yes, "Farmsilo-Befüllung: Silage" is set. What kind of mistake a make? I start course record when Conveyor beld loads silage into trailer

**Comment by Tensuko** [comment]
I used Mode1 for other stuff already and it worked unless to an unload point and got LUA, but that got fixed.
Then I haven't try out if the start still works. I got to make some tests on that, before I can give you an answer to that.

**Comment by FS19-CP** [comment]
Make sure your last few and first few waypoints are straight, and put your start and stop points pretty close together. Works fine, if you keep that in mind.

**Comment by Tensuko** [comment]
Closed. If there is still an Issue with that. Pls post a Video or situation of the Video with DebugChannel 1 and 2 acive for Triggers.
