### ISSUE TITLE
Vehicle does not stop when in traffic

### ISSUE THREAD

**Issue by nbhubbard96** [Courseplay/courseplay#3775]
combines are not stopping when they detect they are in traffic with the unload tractor

**Comment by newride** [comment]
what combine are you using?

**Comment by Tensuko** [comment]
#3311 
Closed.

**Comment by nbhubbard96** [comment]
Using the in game case 9230 combine and it won’t stop when the unload tractor gets in front of it

**Comment by Tensuko** [comment]
Thats correct. We will see if things gets changed in the future after mode 2 rework.
