### ISSUE TITLE
Mode 6 skipping some fruit at beginning of row

### ISSUE THREAD

**Issue by Verios44** [Courseplay/courseplay#3778]
map: Espachia Lapachio
field: 29
harvester: varltron 470 Tera-trac
issue: Every single straight up/down pass results in a small amount missed in the beginning of the row. 
settings: 1 headland, rest up/downs, path finding and turn on field both on

I am not sure if I am doing something wrong at my end, or if its an actual issue.  

 
![steel (3)](https://user-images.githubusercontent.com/47251997/57639475-ff885f80-757d-11e9-933c-1ac12f7aec15.PNG)

**Comment by pvaiko** [comment]
#3642

**Comment by FS19-CP** [comment]
I generally need to play with turning circle and turning speed to even out end passes, so nothing gets missed... usually, though, I've been recording harvest courses myself as a way of guaranteeing everything gets taken.
