### ISSUE TITLE
Mode 2 rework

### ISSUE THREAD

**Issue by seeske123** [Courseplay/courseplay#3780]
In mode 2 at the moment we have the following situation. The unloader is going to his waiting position behind the harvester. If the havester is passing this waiting position the pipe goes out. And the harvester is stopping to unload. Normal because there is atrigger.. My proposal is that the unloader is two rows away or the trigger is only there if the unloader is called.Good succes with mode 2.Regards Hans

**Comment by Tensuko** [comment]
#3311 
Closed.
