### ISSUE TITLE
Mode2 Abladestelle wird nicht mehr erkannt

### ISSUE THREAD

**Issue by turbodani** [Courseplay/courseplay#3781]
Moin, mit der 215 ignoriert der Abfahrer die Abladestelle(n) und fährt mit normaler Geschwindigkeit einfach drüber.

**Comment by Tensuko** [comment]
Logfle ?
Welche Abladestelle ?
Passiert das auch in Mode1 oder Mode6 ?

**Comment by turbodani** [comment]
Ok.. Schon erledigt. Liegt am Fendt 930 TMS. sorry..
