### ISSUE TITLE
Beacon lights not working

### ISSUE THREAD

**Issue by johnonline1** [Courseplay/courseplay#3783]
Becon lights not working if you tell course-play to turn them on when setting up a course.

**Comment by pvaiko** [comment]
We need little more detail than this.

**Comment by johnonline1** [comment]
When you setup a course and tell course play to turn the beacons or head lights on within course-play the light don t work.

**Comment by pvaiko** [comment]
Ok, I try this one last time. Describe the exact steps you are taking (what exactly you click), what exactly do you expect to happen and what actually is happening.

**Comment by johnonline1** [comment]
I was setting up a course to seed a field and thiers an option there to turn on head light or beacons always l always select beacons always but the beacons done come on. On fs17 it worked fine but this version for fs19 seems to be a bit different.

**Comment by Tensuko** [comment]
Beacon Light Settings working when not on Fieldwork Course with V294.
I think it works as it should.
If there is something not working on track/streets or somewhere.
Discripte it with more details.
Untill then, this one is closed.
