### ISSUE TITLE
Courseplay not running to the edge of the field it stop short.

### ISSUE THREAD

**Issue by johnonline1** [Courseplay/courseplay#3784]

**Comment by johnonline1** [comment]
Most of the time the seeder / cultervator does not run to the edge off the feild it seems to stop short and you need to drive back over the egdes again when the course is done.

**Comment by Tensuko** [comment]
logfile, screenshots of the case with shown course and course settings you used.
What Vehicles are used are also helpful.

**Comment by johnonline1** [comment]
Harvesters and seeder seem to be the main units, l run a headland course first and that a temp fix for me but l think it needs to go a little bit further off the fields egdes to stop this problem.

**Comment by Tensuko** [comment]
> 
> 
> logfile, screenshots of the case with shown course and course settings you used.
> What Vehicles are used are also helpful.
> 
> https://github.com/Courseplay/courseplay/wiki

This.

Also the Fielddata on the map can create problems like that too.
We know not much about your situation right now. Version, Map, Device used, etc

**Comment by johnonline1** [comment]
I done a work a round by doinb a headland first the up/Down rolls

Haversters and seeders.

**Comment by Tensuko** [comment]
I told you what we need zo see what we can do about it. Without the information, we cant do anything here...

**Comment by pvaiko** [comment]
#3844
