### ISSUE TITLE
Grain Transport Convoy

### ISSUE THREAD

**Issue by NumseBacon** [Courseplay/courseplay#3786]
Is it possible to add convoy to grain transport?

**Comment by Tensuko** [comment]
Do they crash into each other then ? Did you try that ?

**Comment by NumseBacon** [comment]
Yes

**Comment by Tensuko** [comment]
Ok I found out something rly weird.
I put 3 Tractors. One of the Vanilla seems like doesn't have Collision detection... that is some sad news.... So I guess there are more...

![fsScreen_2019_05_14_17_03_28](https://user-images.githubusercontent.com/27344744/57708751-2ae87880-766a-11e9-8877-e63f0f9debc1.png)

![fsScreen_2019_05_14_17_04_34](https://user-images.githubusercontent.com/27344744/57708843-50758200-766a-11e9-87cd-259927bd71ab.png)

Ok I add your Idea as Suggestion, Also we have some Convoy addition Pending what comes later. So no Idea if and when it finds its way into CP.

**Comment by NumseBacon** [comment]
Ok thanks!

**Comment by FS19-CP** [comment]
I have also noticed the trucks don't seem to have any collision detection, so I've had to set a waiting point for the 2nd truck in line to avoid collisions... I'll have to check if that applies to the Giants trucks, I've only experienced it with mods.

**Comment by Tensuko** [comment]
This should be fixed already with a better Collission detection.
Closed.
