### ISSUE TITLE
Alle fahren zum Startpunkt Modus 4/6

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#3787]
Warum Fahren alle Helfer Grubbern/Sähen/Düngen/Strohsammeln immer wieder zum Startpunkt.

MFG Mannie313

**Comment by Tensuko** [comment]
Die Option wurde aus dem Kursgenerator entfernt und wird später im HUD eingebaut (Zurück zum Startpunkt an/aus).

Da das noch nicht der Fall ist:
Startpunkt im Vorgewende -> Fahrzeuge fahren zum Startpunkt
Startpunkt auf Feldlinien mit Vorgewende -> Fahrzeuge bleiben am Ende (Vorgewende).
Startpunkt auf Feldlinien ohne Vorgewende -> Fahrzug fährt zum Startpunkt (glaube ich...)

Closed.
