### ISSUE TITLE
FPS Drop with version 216

### ISSUE THREAD

**Issue by Sozzy76** [Courseplay/courseplay#3788]
After downloading version 115 my game started having bad FPS drops from 60 down to 30 to 40. I removed CP and the FPS is a steady 60 no issues.

regards 

Sozzy

**Comment by Jimmy-the-Geek** [comment]
Try updating to the latest version...

⁣Get BlueMail for Android ​

**Comment by Sozzy76** [comment]
I have just tried version 116 and its just the same, checked my log and there is no errors

**Comment by Jimmy-the-Geek** [comment]
Go to GitHub and download the latest -- 216...

⁣Get BlueMail for Android ​

**Comment by Tensuko** [comment]
As Jimmy said, download 216 from here: https://github.com/Courseplay/courseplay/releases
And if you have any Issues, make a new one with a proper titel and better discription and post a logfile!
https://github.com/Courseplay/courseplay/wiki
Closed.

**Comment by Sozzy76** [comment]
Sorry guys I meant 216

**Comment by Tensuko** [comment]
Then pls post a logfile, a screenshot with the shown fps and tell us wich vehicles you used, or more details when the FPS drops.
Becouse I don't think the FPS drops when you got only CP in the Modfolder and not do anything with it :)

**Comment by Sozzy76** [comment]
The FPS drops when I have 2 or more courses happening at the same time either in Fert/seed or field work modes; the fps drop is worse when I use leased vehicles and equipment

I have added my log and screenshot of me driving around at the main farm whilst I have one course play cultiploughing with a MF8737 and a course with a MF7727 spreading lime all owned equipment and a course with a MF8737 cultivating with leased equipment. The FPS drop happens all over the map and is worse than others. 

when i remove CP v.216 my fps is fine and all my graphic setting is fine 

[New Compressed (zipped) Folder.zip](https://github.com/Courseplay/courseplay/files/3184107/New.Compressed.zipped.Folder.zip)

**Comment by Tensuko** [comment]
Few mods where I wonder if they may create a conflict:
HUD Smart Shade
VehicleControlAddon
realDirtColor
ToolDisplay

Also: Wich map do you play ?
Does it happen on Vanilla Map too ?

**Comment by Sozzy76** [comment]
It could be the realdirt mod as I think it is known to cause issues

I play on Oakfield 

I haven’t tested it on a vanilla map, I will try that tonight

**Comment by pvaiko** [comment]
@Sozzy76 try without the Real Dirt Color mod.

**Comment by TheAngryGamerTAG** [comment]
im having the same issue but it isnt all the time and only certain distance from implement that has a course

**Comment by Tensuko** [comment]
Closed due to inactivity.
Get Patch 1.4 and newest CP Version (236 or higher) and see if still have problem (Required a clean logfile without RealDirt as pvaiko said).
