### ISSUE TITLE
courseplay will not  open up menus

### ISSUE THREAD

**Issue by hackselgut** [Courseplay/courseplay#3789]
i am running a course play mod titled "courseplay_6.01_00216.zip" this mod is in the mod list, it is checked as active, but for some reason i can not get any of the menus to show in any way, in fs17 all i had to do was  click the mouse button , menu then would open,then i could start doing a Course, but for some reason i can not get a menu to build a course on version 6.01,  why, ,HELP PLEASE   Bob.  thank you...

**Comment by Tensuko** [comment]
#3552 
Normale Course Recording should work as normal.
But it sounds like you can't find the Coursegenerator.

If this is not what you looking for, tell a bit more in detail, what you want to do and post a logfile.

**Comment by Racker2409** [comment]
"courseplay_6.01_00216.zip" It's for LS19. Not for LS17.

**Comment by Tensuko** [comment]
He just said how it was in ls17 and in ls19 it dorsnt work. But he justdoesnt know about the new hud, thats all.

**Comment by Racker2409** [comment]
It's easier to ask questions than to try it yourself.

You are doing a great job

**Comment by Tensuko** [comment]
Well, its ok to ask and we try to help.
But sometimes we need some informations and have to ask for them.
Even if it is just like 'have you read this' or 'did you try that'... :)

**Comment by hackselgut** [comment]
Who am i talking to for help on this problem...Bob
[test cp.txt](https://github.com/Courseplay/courseplay/files/3188881/test.cp.txt)

**Comment by Tensuko** [comment]
I need more information and what is not working...
You can't open the generator ?
You can't open the HUD at all ?
You can't switch Modes ?

**Comment by hackselgut** [comment]
HI... I do not get anything to come up ,no menu nothing at all, for some reason I get the idea that there are some people that are getting it to work for them,,, so what are they running their system on, what map , there has to be some difference , that is letting some of us to get it to open  and not others,  so what could be different.         Bob  Hastings.

**Comment by Tensuko** [comment]
Ok, try the following:
Have only CP in your Modfolder.
Start a new Savegame.
Get in your ingame Settings and reset your keybindings to default, save settings, save your savegame, restart the game.
Get a Tracktor and use right click to open CP menu (actually thats a fixed way to optn CP Menu and can't be changed).
Why some other Keybindings not working is another Issue and we will look at this later...

**Comment by hackselgut** [comment]
OK,    what I am going to do is the following,put in a new mods folder, rename old one to mods2  then make a folder called mods. the I will put in the mods directory the following files, CP mod and the farm I am  using at this time. I will the  open a new game, in slot #3,start the game, save it,reopen the game, go to settings,, locate reset to default, save and shutdown,then  re open the game,buy a vehicle and see if course play functions, yes or no.   Bob.

**Comment by hackselgut** [comment]
OKAY,   so I did as stated above, still no menu pop up,, but I do notice one thing that I never would see or act on, and is, as the game opened i see a pop up of course play doing an auto scan of some type, then I would click not options listed, I would never do an auto scan of fields before for FS17, as this option always gave me problems, FS17 never did the opening scan, but it is doing it for the FS19, this mite be the problem, as I said I did not see this scanning before .

**Comment by Tensuko** [comment]
Well CP6 (FS19) always does auto scan on start if you wanted it to do so at the start of a new savegame.
I can hardly get why you not able to start the CP Menu with a right Mouse Click....
As I see you got only CP and newest Patch of FS19....

@pvaiko you got any Idea ?

**Comment by hackselgut** [comment]
Well   Well......it seems to work okay, got a menu with right mouse button, but I notice one thing , that is that only have one option button available ,no drive " start to end, no unload, harvester, no overload option. I  assume it is still being worked on,  CORRECT. Also do I have to do the same my first game as I did with this one

**Comment by Tensuko** [comment]
I suggest you to read this Issue: #3552 (yes the screenshots are german, but you will get the Idea of it)
The options will come up, if you attatch the right trailer or tool to get the right menu open.
The HUD basically was made to get ppl into CP to choose the right mode for the attatched device.
Try it out and report back :)

**Comment by hackselgut** [comment]
![fsScreen_2019_05_17_05_05_33](https://user-images.githubusercontent.com/10256656/57919553-060d2480-7867-11e9-88ae-f5c3e9b10391.png)
![fsScreen_2019_05_17_05_08_03](https://user-images.githubusercontent.com/10256656/57919555-06a5bb00-7867-11e9-8bdc-9f2538e6a610.png)
![fsScreen_2019_05_17_05_15_59](https://user-images.githubusercontent.com/10256656/57919556-06a5bb00-7867-11e9-98c9-5a358135b284.png)
![fsScreen_2019_05_17_05_17_22](https://user-images.githubusercontent.com/10256656/57919557-06a5bb00-7867-11e9-97ea-79bf7260ecf0.png)
![fsScreen_2019_05_17_05_18_07](https://user-images.githubusercontent.com/10256656/57919558-06a5bb00-7867-11e9-833f-a1d943a8fea8.png)
![fsScreen_2019_05_17_05_21_09](https://user-images.githubusercontent.com/10256656/57919559-06a5bb00-7867-11e9-8f1f-15dc2adedb66.png)

**Comment by hackselgut** [comment]
Okay,  I have set in a course on my original save game, I need to refine it as it is not giving me a notice at the main silo dump, Aldo there is one button on the control pop up , #4 that is not active, why, I will if it comes on later as I fibish my set up.  Bob,   thanks good job.

**Comment by Tensuko** [comment]
NoTrailer or Tool = no other Mode.
Attatch the Trailer and you get mode 1 and 2...
Sawing/Fertilizing Machine Mode4...

**Comment by hackselgut** [comment]
Mourning, the fourth button iss for ( or was )settig settings for when a vehicle started to go pick up from a Combine ,wait till 100% full or not also allows an offset for the discharge pipe , some harveters have right or left side discharge so I need this option.  Also this years fs is using different triggers on the dump points for all main silos and place able types,so as is  now  no dump.   Bob

**Comment by Tensuko** [comment]
Mode2 is under rework...
And the HUD got everything you need to let CP work.

Can you pls tell me clearly, what is the Issue and what you need to know.
We moved from can't open to you miss anything...

**Comment by hackselgut** [comment]
Hi, Well I guess this issue of not opening can be closed and said to be fixed. i will have open a new issue 
  Bob.
