### ISSUE TITLE
No fill type selection on transport

### ISSUE THREAD

**Issue by Ragworm** [Courseplay/courseplay#3793]
Hi 

just noticed when i was going to haul some crops that i cant change selection from wheat

**Comment by Tensuko** [comment]
It does work. If you can't, we need Screenshot (or Video), Name of Vehicles and a logfile.

https://github.com/Courseplay/courseplay/wiki

**Comment by Ragworm** [comment]
My appoligies i did not see it on the next page sorry to mess you around
