### ISSUE TITLE
Lizard Hulk Truck Records/Drives Courses Offset

### ISSUE THREAD

**Issue by cwattyeso** [Courseplay/courseplay#3794]
I've noticed in game when using the Lizard Hulk Truck or mods of this Truck that when recording courses with the truck, the course line and way-points are always offset to the left of the truck. If you then use another model truck or tractor to drive one of these course they have problems because they then drive correctly centred on the course line, which means they are more to the left. The opposite of course happens that if you use the Lizard Hulk Truck on a course that was recorded with another model truck or tractor, when it runs the course it positions itself to the right of the course line and can therefore run into problems with objects, fillpoints, unload points or traffic. I see no way in the Courseplay menus to be able to correct this alignment with the Hulk Truck.
![2019-05-15](https://user-images.githubusercontent.com/13921716/57870262-a24f1100-77fe-11e9-9fa3-1786db1d48ad.png)

**Comment by Tensuko** [comment]
That is on some GIANTS Trucks, sadly we can't do much about it.
You can see a yellow dot above the Vehicles if you turn on Debugchannel 12. That is where CP sets the points and then also drive the course.
Currently you can only take the offset in mind when creating the course with the truck and only use that one for truck only.
Sry to tell that, but thats the current state...

I don't know why GIANTS did that...

**Comment by Tensuko** [comment]
I did Inform Lisertan about it a while ago and I didn't get any Answer back.
Will try it again at GIANTS Support, but as we can't do anything about Models from GIANTS, I will close this one.
