### ISSUE TITLE
coordinate system transformation

### ISSUE THREAD

**Issue by GrisuLychen** [Courseplay/courseplay#3795]
Hallo liebe Entwickler,
ich habe eine Frage zu der Positionierung der einzelnen Wegpunkte bzw. zum Koordinatensystem. Ich habe mich an die Portierung von "CourseDrawer" von LS17 auf LS19 gewagt, da ich Kurse auch gern nach dem Einfahren ändern möchte. Leider werden die Kurse auf der importierten Karte an der Komplett falschen Stelle angezeigt. Die Koordinaten in den xml Dateien entsprechen nicht der im Spiel. Der Koordinatenursprung scheint nicht in der Mitte zu sein (wie bei LS17), der Winkel ist auch anders. Egal wo ich schaue, welche Koordinaten des Spiels ich vergleiche oder welche Lua Datei ich mir anschaue, ich verstehe das Koordinatensystem nicht. Könnt ihr mir vielleicht helfen und kurz erklären, wie ich die xy Koordinate im Spiel aus der CP xml Koordinate errechne.

Danke für eure Hilfe
Grisu

___

Hello dear developers,
I have a question about the positioning of the individual waypoints or the coordinate system. I ventured to port "CourseDrawer" from LS17 to LS19, cause I would like to editing courses after creating. Unfortunately the courses on the imported map are displayed in the wrong place. The coordinates in the xml files are different from those in the game. The origin of the coordinates does not seem to be in the middle (as in LS17), the angle is different also. No matter where I look, which coordinates of the game I compare or which Lua file I look at, I do not understand the coordinate system. Can you maybe help me and explain how to calculate the xy coordinate in the Game from the CP xml files.

thanks alot for your help
Grisu

**Comment by pvaiko** [comment]
This is maybe because we now have the y coordinate (altitude) also stored, see #2356
