### ISSUE TITLE
CP Fahrer fahren mit voller Geschwindigkeit durch das Fahrsilo

### ISSUE THREAD

**Issue by Tombarkemeyerbruns** [Courseplay/courseplay#3796]

**Comment by Tombarkemeyerbruns** [comment]
Moin bei mir fahren die cp Fahrer mit voller geschwindigkeit durch das Fahrsilo

**Comment by Tensuko** [comment]
Logfile mit Debugchannel 1 und 2, was für ein Fahrzeug, welcher Modus (Spoiler: du benutzt Modus 2 in dem die Berechnung noch nicht eingebaut ist).
Modus6 hat die Berechnung.

**Comment by Tombarkemeyerbruns** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3188937/log.txt)
mode2 massey fergusun 7700 da gings manchmal geht manchmal fährt er mit vollgas durch

**Comment by Tensuko** [comment]
Mode2 hat, wie gesagt, die Berechnung noch nicht drin, da Mode2 neu geschrieben wird.
#3311 
Könnte gehen, wenn du erst in ein Hofsilo abkippst und von da mit Mode1 arbeitest, habe ich aber noch nie ausprobiert.
Closed.
