### ISSUE TITLE
Unloading problem with Ingame Wilson PaceSetter

### ISSUE THREAD

**Issue by timber3000** [Courseplay/courseplay#3797]
Hi, when setting a route in mode 1 or 2 with the ingame Wilson Pacesetter trailer, it only unload one of the two compartment and leave.  It doesn't recognize the other.

**Comment by FS19-CP** [comment]
Seconded... only dumps the selected hopper. I expected it though, being a TMR Wagon will skip a tip trigger if the wrong tip side is selected.

Can a function be added that searches for applicable triggers for all tip sides, and use either side?(or both, in the case of a hopper... although one at a time would be the most accurate for most situations... most augers will only be processing a hopper at a time, they're not usually fast)

**Comment by Tensuko** [comment]
#3060

**Comment by cwattyeso** [comment]
They also have an issue if trying to load them in Mode 1, where the driver will fill the first hopper of the trailer and then just sit there forever waiting. He won't pull forward to fill the second hopper and then continue on with the course to transport the contents. This is also an issue if using the new released Wilson Super B Trailers or Wilson A Train Trailers, as Courseplay will only presently fill one trailer and never move on and fill the other trailers attached in the road train.

**Comment by Kn1ghtwolf** [comment]
Thats the issue with The A and B trains to CP doesn't recognize hoppers or dual trailers

**Comment by Kn1ghtwolf** [comment]
Thats the issue with The A and B trains to CP doesn't recognize hoppers or dual trailers

**Comment by Tensuko** [comment]
Closed, continue in  #3060 but will be looked into later, as GIANTS use tip side to change the bin to unload.
