### ISSUE TITLE
Frage: zwei Touren auf selbem Kurs?

### ISSUE THREAD

**Issue by stueja** [Courseplay/courseplay#3798]
Kann ich eigentlich den selben Kurs benutzen, um z. B. Gras zum Silagesilo zu bringen und auf der Rückfahrt Silage ins Hofsilo?

**Comment by Tensuko** [comment]
Das wird glaube ich kaum funktionieren.
Wenn wir annehmen, du startest am Hofsilo und tankst dort Gras, dann fährst du durch das Silo bis kurz vor dem Hofsilo. An welchem Punkt würdest du Silage aufnehmen ?
Das ging vlt mit einem Wartepunkt auf Endlos (bist du sagst, es geht weiter) und bevor du am Entladerohr wieder ankommst, währst du eine Tour über die Abladestelle des Silos.
Aber das müsstest du einfach mal ausprobieren.

**Comment by Tensuko** [comment]
Closed, da inaktiv.
Wenn es so wie ich es beschrieben habe nicht funktioniert, wird es leider keine andere Möglichkeit geben.
