### ISSUE TITLE
Eingefahrener Kurs geht nicht mehr mit anderem Traktor

### ISSUE THREAD

**Issue by stueja** [Courseplay/courseplay#3799]
Ich habe einen Modus-1-Kurs eingefahren, um Gras vom Hofsilo zum Silagesilo zu bringen.
Gespann zum Einfahren: Massey Ferguson 7700 (oder Valtra T234, weiß nicht mehr genau) mit Kröger Agroliner TKD 302. (Alles Nicht-Mod).

Jetzt wollte ich den Kurs fahren mit
Gespann: Deutz-Fahr 9340 TTV und Strautmann Celon CFS 2501 DO (alles Nicht-Mod).
Effekt: am Ladepunkt wurde nicht oder nur so wenig geladen, wie während des Durchfahrens geladen werden konnte.

Test mit Deutz-Fahr und Kröger: das gleiche.

Valtra T234 und Kröger sowie Valtra T234 und Strautmann funktionieren hingegen.

**Comment by Tensuko** [comment]
Ok das schaue ich mir mal an...

**Comment by Tensuko** [comment]
Kannst du ein logfile mit debugchannel 1 und 2 machen und anhängen ?

**Comment by stueja** [comment]
Klaro. Hier geht ein Versuch los: 2019-05-18 18:37 :23 [dbg1 lp16083] updateAllTriggers(). Beim Versuch zuvor hatte ich Weizen statt Gras ausgewählt.
[log.txt](https://github.com/Courseplay/courseplay/files/3194272/log.txt)

**Comment by stueja** [comment]
Hasn't been an issue ever since.
