### ISSUE TITLE
60100216 - Issues with follow the course when use as sprayer 

### ISSUE THREAD

**Issue by caplink811** [Courseplay/courseplay#3800]
On a course with 1 round on headland CP won't follow the turn to fieldcourse, instead it ends up in the wild. 
Please see screenshot for details.
This was a Deutz7 with sprayer addon on the back attacher, as well as a 2nd tank on front attacher. The Log shows nothing (no debug channels active)

![FS19_CP60100216](https://user-images.githubusercontent.com/49813958/57941025-12789800-78ce-11e9-9c71-8a285555719b.png)

**Comment by pvaiko** [comment]
Need a log with debug channels 12 and 14.

**Comment by caplink811** [comment]
Ok, now with 60100217 it isn't better. The only difference was that this time the sprayer couldn't passed the trees, so it stuck there.
Please see screenshot for details, as well as the attached logfile.

[FS19_CP60100216_Log.txt](https://github.com/Courseplay/courseplay/files/3192701/FS19_CP60100216_Log.txt)
![FS19_CP60100216_Log](https://user-images.githubusercontent.com/49813958/57949722-7e1a2f80-78e5-11e9-9660-2882e73e375c.png)

**Comment by pvaiko** [comment]
@caplink811 did anyone say it is going to be better with 217? :) 

Not sure which map is this, if it is an official one on modhub you can post a savegame and your courses as I can't reproduce this. 

If you can't, a video or at least a screenshot when the temporary course (purple glowing lines) is shown would help. 

Is this also happening when you lower the field speed to 15 km/h?

**Comment by caplink811** [comment]
Morning,

the map is 

<version>1.6.0.0</version>
-<title>
<en>Südhemmern</en>
<de>Südhemmern</de>
</title>

You're guess points in the right direction, the sprayer stay on the course if the max speed isn't higher than 18kmh (maybe ok with 19 also, dunno), but it goes wrong with a speed of 20kmh.

Attached you find the savegame as well as the CP courses and the logfile. Also I try to attach 2 videos, 1 good case and the other shows the bad case.

[Suedhemmern_LS19.SampleModMap.zip](https://github.com/Courseplay/courseplay/files/3193809/Suedhemmern_LS19.SampleModMap.zip)
[savegame6.zip](https://github.com/Courseplay/courseplay/files/3193810/savegame6.zip)
[log.txt](https://github.com/Courseplay/courseplay/files/3193812/log.txt)

Hm, it seems that I've figure out, how to add video or at least link to it...

**Comment by caplink811** [comment]
let me try

https://1drv.ms/u/s!Aqt5msdvWb55g05rEbeKak6LF8hv which is the good case,
https://1drv.ms/v/s!Aqt5msdvWb55g09-hPnI0SjFfy-j which is the bad case

TIA

**Comment by Tensuko** [comment]
Try with 218 or higher and report (you got to create the course again)

**Comment by pvaiko** [comment]
Don't need to recreate the course.

**Comment by Tezzward** [comment]
I was having this issue with the Anderson DLC solid fertilizer spreaders set to run 2 work tools with 217.  I tried with 218 with the old course and generated a new one.  It's still just driving off instead of making the first turn after a headland.

**Comment by pvaiko** [comment]
@Tezzward that must be a different issue then. Do you have a video with debug channels 12 and 14 on?

**Comment by Tezzward** [comment]
It still has 20 minutes left on the course.  I will set them close to the end of the headland and run them with those debug channels on and record it asap.

**Comment by Tezzward** [comment]
Log:  https://pastebin.com/GtRH324E

video: https://youtu.be/ykjyX1vw1Tc

video starts at the end of headland.  When the tractors make the right turn, instead of making another right to start the first line, they drive off.  

This also occurs at the end of the course.  The tractors reach the last point, fold up, and drive to the first point.  When they reach the first point, they drive the headland at field speed (set to 25mph), and when they reach the first turn after the headland, they drive off in the exact same direction.

**Comment by pvaiko** [comment]
Oh, ok your issue is #3667, you did not mention you are using offset.

**Comment by caplink811** [comment]
Morning,
I reused the existing course, and tried it with Vmax == 20, 24 and 28 kmh, all speeds worked for me. IMHO the turn from headland to filedcourse looks now much smoother. 

thanks for your efforts

**Comment by pvaiko** [comment]
@Tezzward turned out the map in #3667 isn't very useful, would you have a savegame and courses on a decent map so I can reproduce this?

**Comment by Tezzward** [comment]
It is on Midwest Horizon.  I can send you all of it if that map works.

**Comment by pvaiko** [comment]
I have that map, just need a savegame and the courses.

**Comment by pvaiko** [comment]
#3667
