### ISSUE TITLE
How to do?

### ISSUE THREAD

**Issue by NumseBacon** [Courseplay/courseplay#3801]
How do i do the #3250 ?

**Comment by Tensuko** [comment]
Next time ask your question in the specific Issue and not make a new one pls.
That is the Field you got to change to make different mid pattern. Try all 3. (Just click generate again)
I suggest everyone to play arround with the settings a bit to find out what does what and try out to see what is the best for your field.
![Settings](https://user-images.githubusercontent.com/27344744/57944245-acdcd980-78d6-11e9-802e-de76d8a2ba6d.png)
I know this is german but the location of the Menu is the same...
Closed.
