### ISSUE TITLE
Mähdrescher 

### ISSUE THREAD

**Issue by sepp1** [Courseplay/courseplay#3802]
Mähdrescher stoppt wenn er in die nähe eines Abfahrer,s kommt wenn das Rohr ausserhalb der Frucht ist. Version ist die 217 Karte ist die NF Marsch 1.7. Oder wird das Problem mit dem neuen Mode2 behoben?
![fsScreen_2019_05_17_19_02_16](https://user-images.githubusercontent.com/30937239/57947410-24166b80-78df-11e9-8ca9-fd7d71756876.png)

**Comment by Tensuko** [comment]
Das hast du im Drescher so eingestellt. Während Abtanken anhalten und das ist auch alles richtig so. Mode2 wird später anders parken. Closed.
