### ISSUE TITLE
Course play not stopping at any dump sites, have set  a pause point, then click stop.

### ISSUE THREAD

**Issue by hackselgut** [Courseplay/courseplay#3804]

**Comment by hackselgut** [comment]
Hi.... the course play does not recognize the new type of triggers for all dump sites, silos and sell points.  I am running version 6.01  217

**Comment by Tensuko** [comment]
Map, device, logfile with debug 1 and 2.

**Comment by hackselgut** [comment]
Hi...I do not have or see the debug operation on the control hud, what button is the operatio in?
![fsScreen_2019_05_18_07_01_56](https://user-images.githubusercontent.com/10256656/57968731-50aca080-793c-11e9-809b-9db209e6d5fe.png)
[log.txt](https://github.com/Courseplay/courseplay/files/3193989/log.txt)

**Comment by hackselgut** [comment]
Hi....comment...last year fs17 had options for making adjustments for certain operations, example using combi mode to empty a harvester we could set when the vehicle headed out to be filled from harvester,also we could adjust for  any misalignment with the discharge pipe. these options are not available at this time.
So now with the fs1*9   the problem I have is as follows, Option 2 combi mode, the vehicle to empty the harvester will leave to soon to empty  harvester and is now going to follow along side to try to be filled, but as the vehicle comes along side, the pie  is not aligned to the load trigger,  so it will continue to follow hoping to find the alignment to fill the vehicle,Hear is where I need to set an offset to correct fault, 
Using  option 1 to remove crop to silos or sell points,  you require bring the harvester to the vehicle unload then return to field location  again,, time consuming so option 2 is preferred, or use a augar  wagon, but their is no mode available for this..
Now I have made two courses to dump crop to silo and they will not dump at the location just keep going .sending pictures of what I tried to do.            Bob
[log.txt](https://github.com/Courseplay/courseplay/files/3194136/log.txt)

**Comment by hackselgut** [comment]
PICTURES
![fsScreen_2019_05_18_07_01_56](https://user-images.githubusercontent.com/10256656/57970955-f1f42080-7955-11e9-9e20-2aebe3d01ef7.png)
![fsScreen_2019_05_18_07_39_30](https://user-images.githubusercontent.com/10256656/57970956-f28cb700-7955-11e9-933a-c9952b86c31a.png)
![fsScreen_2019_05_18_07_39_57](https://user-images.githubusercontent.com/10256656/57970957-f28cb700-7955-11e9-8ae5-c8583eb313e7.png)
![fsScreen_2019_05_18_08_12_07](https://user-images.githubusercontent.com/10256656/57970958-f28cb700-7955-11e9-8742-2fdfa698d160.png)
![fsScreen_2019_05_18_08_12_34](https://user-images.githubusercontent.com/10256656/57970959-f28cb700-7955-11e9-970a-097fbeb6a166.png)
![fsScreen_2019_05_18_08_13_53](https://user-images.githubusercontent.com/10256656/57970960-f28cb700-7955-11e9-9a10-d7c701bb919e.png)
![fsScreen_2019_05_18_08_14_29](https://user-images.githubusercontent.com/10256656/57970961-f28cb700-7955-11e9-908d-12cffd42641a.png)
![fsScreen_2019_05_18_08_16_09](https://user-images.githubusercontent.com/10256656/57970962-f28cb700-7955-11e9-90e2-6cbf2820ec92.png)
![fsScreen_2019_05_18_08_22_33](https://user-images.githubusercontent.com/10256656/57970963-f28cb700-7955-11e9-8e1d-2c7939fad9f2.png)
![fsScreen_2019_05_18_08_23_08](https://user-images.githubusercontent.com/10256656/57970964-f28cb700-7955-11e9-9383-d07538c7e6cc.png)
![fsScreen_2019_05_18_08_24_31](https://user-images.githubusercontent.com/10256656/57970965-f3254d80-7955-11e9-8c1e-5fbeafde1107.png)
![fsScreen_2019_05_18_08_26_11](https://user-images.githubusercontent.com/10256656/57970966-f3254d80-7955-11e9-838c-3a954a6ceab5.png)
![fsScreen_2019_05_18_08_26_30](https://user-images.githubusercontent.com/10256656/57970967-f3254d80-7955-11e9-9223-1735253258b7.png)
![fsScreen_2019_05_18_08_29_16](https://user-images.githubusercontent.com/10256656/57970968-f3254d80-7955-11e9-8b77-3988247ba8ce.png)

**Comment by Tensuko** [comment]
Just look arround in the HUD a bit...
![settings](https://user-images.githubusercontent.com/27344744/57972271-5f28a580-7998-11e9-88f6-9b564b0bb568.png)

The debugchannels have always been in the CP Settings Menu.

Your Screenshots not helping much...
Also this is Mode2 so #3311 

What you can do is play arround with Fruit Bypass on/off for both Harvester and Tracktor/Truck,
as well as the Values in the Same Menu I you see in the picture.

What I don't see is the topic problem, that it doesn't stop for a 'dunp sies' (Silo/Selling Triggers ?)

**Comment by hackselgut** [comment]
Hi,,,,the picture of the hud you have shun me is hot active, for me.
Also the pictures I sent show me coming up to dump point, full of crop, leaving with vehicle still full, so it did not accept the dump.     Bob.

**Comment by Tensuko** [comment]
Then your Trailer got a problem, that Menu I can select when Mode2 selected.
Why it doesn't dump the Fruit in there I don't know. Maybe it goes to fast before the trigger.
But one for your pics show trigger reached.

**Comment by hackselgut** [comment]
Hi,,, I set in a course having a pause point on  the dump point, wait for  30 sec, no dump indicated, hit the stop course button ,dump signal; comes active
All of the dump points in this years game are new or   different from last years type.
I have  also noticed that as you stated  I did see one time, an indicate of tip trigger reached. but did not dump that time.    Bob.

**Comment by hackselgut** [comment]
Hi,,, follow up to last message, I have spent the last couple of hours trying to find a way of getting crops to dump at the main silos and replaceable  type silos. I have come up with the only way to do it is set in a pause  point, set to 30 sec or so,, and when the vehicle is stopped I hit the key i, that starts the unload. vehicle stays in the course set in.
This will do for now until  you fellows can come up with a way of getting it to work properly.
If this statement is acceptable to you, you can close issue.  Bob

**Comment by Tensuko** [comment]
Is that in Mode2 ? In Mode6 everything works fine... Also Mode1
That got nothing to do with acceptable state, the problem is that I can't reproduce that.. I will make a try with Mode2 next week. And a sell Course... A bit patience pls.

**Comment by sootysax** [comment]
I also have issues not being able to unload anything in mode2 at certain sellpoints..   works fine in mode1.   I closed my issue because it's mode2 and I didn't think it would be addressed.

This was on the midwest horizon map - and none of the sellpoints would work in mode 2.   I switched to the Oakfield map, and I seem to be able to unload in mode2 on that map..  so it's trigger specific.

**Comment by Tensuko** [comment]
Seems like it. There are even different fill up triggers.
I noticed that for Seed, else you simply click R and it fills up or you click R and get that box where you can select what to fill up, I evn saw that for seed.
But I got both to work on my map (placables...) anyway, got to talk in the team about this issue, could also be related to other issues.

**Comment by Tezzward** [comment]
I've only had that issue when I try to run 2 tippers on the same course, or when I don't pull very straight across the trigger when making the course.  

If you run two tippers, or run 2 combines with separate tippers, it works much better if you create 2 separate courses for the tippers.

**Comment by hackselgut** [comment]
Morning, Here is what I find this morning, I have set in a course to dump crop at the farm silo, have built the course with a pause on the trigger, set for 20 sec,, now the vehicle will come to the dump point, stop, wait 20 sec, then leave,. at this point theNote vesicle goes forward 5 to 5 feet, stops and then dumps the crop, when unloaded it finishes its course as set.Note,I have not hit the key I or any thing else, no interference done. It is not normal to have to use a pause point, but operation is working for the moment. on its own,This is using cp 601.19. two pictures sent in.  Bob
<img width="960" alt="fsScreen_2019_05_20_08_57_26" src="https://user-images.githubusercontent.com/10256656/58027709-3fec5e00-7ae7-11e9-982d-3a28b3844c71.png">
<img width="960" alt="fsScreen_2019_05_20_08_57_36" src="https://user-images.githubusercontent.com/10256656/58027710-3fec5e00-7ae7-11e9-9ef0-c17a5e8741b4.png">

**Comment by Tensuko** [comment]
I don't need a pause waypoint.
But I also don't use Mode2.
Mode1 and Mode6 is fine and I was trying something different with a 3 Tracktor chain in a smal circle to load and unload in an endless loop.

So again: do you use Mode2 in that Case ?

**Comment by hackselgut** [comment]
Hi,,, Could you verify the programming  of mode 1 and 2 to see if there is some difference, in regard to the following,  mode 1 will dump correctly at  a dump location , no pause required. mode 2 will not dump at a sell location without a pause bring required. Also a pause point is able to be used with any mode 1 or 2, but one placed in mode 1 gives no option to set a time, button inactive. In mode 2 a placed pause, you have an  active button to set time.   Bob.

**Comment by hackselgut** [comment]
Hi, Tensuko, It looks as if the dump problem has been corrected. but one comment, as we set in a course, and go to name it, the box that the text is put in gives us no contrast with the text, hard to see if we have any  typing errors before saving the name, a different color would be helpful. So if you wish you can close the issue. thanks Bob.

**Comment by Tensuko** [comment]
> Could you verify the programming of mode 1 and 2 to see if there is some difference

#3311 

Closed.
