### ISSUE TITLE
Typical work tool speed limits can be circumvented by using "transfer" mode.

### ISSUE THREAD

**Issue by corrado33** [Courseplay/courseplay#3806]
Using version 215. I accidentally forgot to switch a tractor from transfer (the seemingly "default" mode) to "seeding/fert" mode and noticed my fert spreader was going 30+ MPH. (While in operation.) My "speed" was set to "maximum speed" and not to "recorded" speed". If I set it to "recorded speed" it did, indeed, drop down to the recorded speed. 

I then tested it with a weeder and it worked as well, although the tractor did seem to be slowed down by the weeder. 

Not necessarily game or courseplay breaking, just a way to cheat. That's all. Either disable the ability to turn tools on and/or lower/unfold tools in transfer mode or implement the same speed limiting techniques you did for the other modes. :) 

You guys do great work. Let me know if you need any more info. I think this issue is pretty cut and dry though. To replicate simply load up a course, unfold the work tool (try a fertilizer or weeder, as those are what I tried), make sure to click on "transfer" mode, then I actually started the driver THEN lowered/activated the tools. Although it seemingly works either way. (Albeit this was with a modified weeder, but the fertilizer I used was just the stock medium sized fertilizer.)

Thanks for developing courseplay, it's a wonderful mod!

**Comment by pvaiko** [comment]
@corrado33 thanks, I guess we have more important issues to take care of right now...

**Comment by corrado33** [comment]
No worries, I get it, just wanted to bring it to your attention. :) You guys are the best!
