### ISSUE TITLE
mode3.lua:24: attempt to perform arithmetic on a nil value

### ISSUE THREAD

**Issue by stangman04** [Courseplay/courseplay#3807]
Playing on Midwest Horizon when all of a sudden my camera froze and I could not switch between machines and when I hit esc I was unable to resume the game and had to force quit. I was combining and using Combi mode to unload the combine.

Edit: I updated courseplay and same error. Uploaded new log.

[log.txt](https://github.com/Courseplay/courseplay/files/3193485/log.txt)

**Comment by Tensuko** [comment]
How can you have a mode3 lua error ??
What tools did you use ?

**Comment by stangman04** [comment]
> How can you have a mode3 lua error ??
> What tools did you use ?

I was using a T560 combine, I was running that manually. Now for courseplay I was using a John Deere 7R pulling a Kinze 851 Auger Wagon in mode 2 (combi mode).

**Comment by Tensuko** [comment]
#3311 
Old Mode2 not supported anymore.
The LUA is weird couse it says Mode3, but that is the problem of the augur wagon I guess, wich is also currently not supported.
Better let CP Harvest and drive the rest by yourself untill Mode2 is reworked.
Sry.
Closed.
