### ISSUE TITLE
Courseplay_6_01_00213

### ISSUE THREAD

**Issue by TheCRUSTYSmurf** [Courseplay/courseplay#3808]
Courseplay_6_01_00213 doesn't seem to work. Meaning when Courseplay_6_01_00213 is the only mod selected or installed. My game A- Doesn't want to load into the game/map B- Save a game. Meaning when I try to save the game it hangs my game/or takes forever to try to save causing me to quit out of the game losing all my progress! Any idea or suggestions would be nice. I even tried an older version to where I wasn't getting this problem. Thank you for your time>

**Comment by corrado33** [comment]
Try the latest updates? Alternatively try clearing out your courseplaySettings.xml and/or courseplayCustomFields.xml files in your savegame. If that still doesn't work, maybe try temporarily clearing out your courses folder? (Of course, make backups of these files first somewhere else.)

The only time I've ever had courseplay hang my game is when I've manually edited a course and did so poorly, in a way that courseplay didn't expect/wasn't programmed to handle.

**Comment by Tensuko** [comment]
Newest Version:
https://github.com/Courseplay/courseplay/releases
Logfile:
https://github.com/Courseplay/courseplay/wiki

**Comment by TheCRUSTYSmurf** [comment]
Still nothing...If it helps, it seemed like when I bought items from the shop. That the saving hangings. I've try with only Courseplay as the mod selected and/or installed. Nothing... Thanks for your help and let me know if you have any more suggestions!

    On Saturday, May 18, 2019, 11:50:57 AM EDT, Tensuko <notifications@github.com> wrote:  
 
 
Newest Version:
https://github.com/Courseplay/courseplay/releases
Logfile:
https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
Still no logfile...

**Comment by Tensuko** [comment]
Closed due to inactivity.
