### ISSUE TITLE
Güllezubringer Mode 1

### ISSUE THREAD

**Issue by Phips99** [Courseplay/courseplay#3809]
Hello

I use Mode 1 as a slurry feeder, but it doesn't fill up the manure at the charging point. He's slow to drive past here. I created a stop here, but it just waits and doesn't fill up.

I play on Map Ebelsbach and use the Tatra truck with the feeder of Horsch.

**Comment by Tensuko** [comment]
I think that is becouse we got an extra Liquid Mode, wich is not activated for CP6 yet.

@pvaiko 
Is it much different to Mode1 ?

**Comment by Phips99** [comment]
How can i do with the mode 1?

**Comment by FS19-CP** [comment]
I've been using Mode 1 with Digestate from a BGA... truck and tanker and very good waypoint alignment. Play with it... discharge spout straight over the cover wouldn't load, just behind the cover does.

It generally works, but can be finicky.

**Comment by Tensuko** [comment]
The Mode8 is back and should work like you wanted it.
It can bring Slurry to the Field (need a waiting point there) and goes for reilling itself when empty.
Fieldworker can refill himself at the Mode8 Driver.
If got any Issue with that, report here: #4107
Closed.
