### ISSUE TITLE
Seeding & Fertilizing show weird result after completing course

### ISSUE THREAD

**Issue by RUGhost** [Courseplay/courseplay#3810]
After completing the fertilizing or seeding course tractor go to the point (this is the point from where he started the course after refilling) and started the course again. This problem only occur if the course have any refill course. If the course does not combined  with any refill course then this problem does not occur.

![Desktop Screenshot 2019 05 18 - 23 11 55 81](https://user-images.githubusercontent.com/48012198/57973371-c90d7300-79c9-11e9-824b-ea2b36564bcb.png)
This course has no problem

![Desktop Screenshot 2019 05 18 - 23 13 04 17](https://user-images.githubusercontent.com/48012198/57973386-07a32d80-79ca-11e9-8df0-c29f80328e20.png)
This course make the problem

![Desktop Screenshot 2019 05 18 - 23 28 16 11](https://user-images.githubusercontent.com/48012198/57973398-41743400-79ca-11e9-8d09-245b0f32ac13.png)
After completing the course tractor follow the blue glowing line. I activate debug channel 14 to show you the path of tractor.
![Desktop Screenshot 2019 05 18 - 23 28 31 10](https://user-images.githubusercontent.com/48012198/57973428-a760bb80-79ca-11e9-93ee-72bacd2608ca.png)
![Desktop Screenshot 2019 05 18 - 23 28 59 35](https://user-images.githubusercontent.com/48012198/57973429-a7f95200-79ca-11e9-9bc6-41b1cb5c9f68.jpg)
![Desktop Screenshot 2019 05 18 - 23 29 05 97](https://user-images.githubusercontent.com/48012198/57973430-a7f95200-79ca-11e9-8c1a-af221bf726d1.jpg)

**Comment by corrado33** [comment]
Is "Stop at last point or next trigger" Activated? Did you make sure that you're actually on seeding/fertilizer mode and not transfer mode. (I get the same behavior if I'm accidentally on transfer mode.)

**Comment by pvaiko** [comment]
@RUGhost do you have the log for that with debug 14?

**Comment by RUGhost** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3194821/log.txt)

**Comment by pvaiko** [comment]
Thanks for the clear bug report, try with 219.

**Comment by RUGhost** [comment]
Yea now its working. Thanks a lot
