### ISSUE TITLE
Error: Running LUA method 'update'.6.01.00218

### ISSUE THREAD

**Issue by Racker2409** [Courseplay/courseplay#3812]
Here's the problem:
Mod: FS19_8R_EU and spreader from the game

The message is only displayed after approx. 30 minutes.
[log.txt](https://github.com/Courseplay/courseplay/files/3195291/log.txt)

**Comment by pvaiko** [comment]
The Giants nameNum() function returns nil for this vehicle, contact the mod author to fix it.
