### ISSUE TITLE
Abfahrer mit Holmer funktioniert nicht

### ISSUE THREAD

**Issue by Moodijil** [Courseplay/courseplay#3813]
Hallo zusammen,

ich versuche gerade mit dem Homer Terra einen Drescher Abzutanken und ihn in einen Anhänger abzuladen aber leider stürtzt dann immer das gesamte Spiel ab.

Mache ich was falsch anbei mal die Log dazu.

Vielen Lieben Dank für die Hilfe
[log.txt](https://github.com/Courseplay/courseplay/files/3195364/log.txt)

**Comment by Tensuko** [comment]
#3311 
Der Holmer ist ein Überlader und der Mode3 hängt mit dem Mode2 zusammen, daher wird es erstmal kein Support dafür geben.
Wir sind aber dran. Bitte noch etwas geduld.
