### ISSUE TITLE
Workaround - Mode3: Temporary solution for overload

### ISSUE THREAD

**Issue by fudoido** [Courseplay/courseplay#3814]
Decided to try something today and it worked out, using combi mode for overload functions, while the actual  overload mode is not ready.
As many might know, combi mode (mode 2) is also being redesigned, and therefor count with bugs while using it, but here is what i did to overcome the lack of mode 3 (overload mode).
1- set a transport course with trailer A as you would for the "delivery" trailer for use with overload trailer.
2- get tractor with overload trailer and extend its pipe straight away.
3- record a course with overload trailer, as you would if it was ment for overload mode, with the waiting point near the "transport" trailer A.
4- set waiting time for at least 30 seconds, select combi mode for overload trailer.
5- run course. When overload hits the unload capacity, it will go near the transport trailer A and unload to it, but since its not on overload mode, it would remain there on waiting point, however i set the waiting time and it should be enough for it to unload.
6- after reaching the waiting time period, overload will drive off back to end of course and wait for combine to call, just as normal with combi mode.
7- adjust waiting time if your overload waits too long after full unload, or if it leaves before unloading completely.
REMEMBER: start course with overload pipe extended and keep it that way. Combi mode does not operate the pipe on the overloader, hence why it must be kept extended to unload into transport trailer.

Hope it helps some people that are waiting to get overload mode back, such as i.

**Comment by fudoido** [comment]
Admins and mods, i apologise as i wanted to add the suggestion label, but forgot how to do it :/
I hope you dont consider this a closed issue while overload mode isin the works, so people can keep looking at this temporary solution for overload.

**Comment by Tensuko** [comment]
Since mode3 is there we don't need a workarround.
