### ISSUE TITLE
Ropa nawaro fill trigger

### ISSUE THREAD

**Issue by Twetch** [Courseplay/courseplay#3818]
Hi, is it possible to set in mode 1 pipe from ropa nawaro as fill trigger? If you have trailer under pipe, you must hit unload in nawaro, otherwise it not start filling.
![fsScreen_2019_05_20_16_21_02](https://user-images.githubusercontent.com/22034856/58050173-e3bd2480-7b4e-11e9-9e21-76c471e3e1ab.png)

**Comment by Tensuko** [comment]
The Ropa used to work in Mode2 if I remember Correct.
Mode1 is not made for Fill from Pipe.
There is a nice Tutorial of it for FS17 on YouTube.
Closed. #3311

**Comment by Twetch** [comment]
In FS19 they work different than in FS17, so you can't use it, as you say.....
