### ISSUE TITLE
Courseplay and AutoDrive Suggestion

### ISSUE THREAD

**Issue by fudoido** [Courseplay/courseplay#3819]
Hello Team.
I believe many people like me is very happy to see your colaboration with AutoDrive mod developer. I am using AutoDrive toghether with Courseplay and so far it all works great. I only have one question for you.
Will you at any point Colaborate with AutoDrive developer to make a way for vehicles using autodrive set a combine level to unload, similar to what courseplay already has implemented?
This is usefull in order to avoid time wasted with truck/tractor driving to combine only when combine gets 100% full and has to wait truck/tractor for unload.
Any plans to make this an option on autodrive?
Also, would it possible for autodrive mod work along courseplay ina way for it to unload and keep following combine while harvesting, as it would also save time and is a feature of courseplay?
Both questions were also made on AutoDrive Github, hopefully you can work this out toghether, or maybe even incorporate the best features of both mods as only one single mod (wishfull thought lol). I love the way AutoDrive records and "plugs" the diferent courses and selects its paths, would love to see that feature on courseplay instead of the current path recording, at least for long transport courses, and keep your course recording for fieldwork and some other modes. Its not that your course recording is bad, not at all, autodrive just seems to be more simplier (sorry to be so honest). 
Thanks in advance.

**Comment by pvaiko** [comment]
Happy to work with Stephan on this, I'm sure there are synergies here, I also brought up the idea in #3792 to use AutoDrive to generate refill/unload courses for Courseplay as that is a lot easier than recording.

**Comment by Tensuko** [comment]
Continue here as a overal Discussion Topic: #3820
Closed.
