### ISSUE TITLE
CP freezing game when starting course with Terra Dos.

### ISSUE THREAD

**Issue by SuBerPL** [Courseplay/courseplay#3822]
Like in title. When i click to start, course game is freezing, but i can still using CP. When i stop course, game backed to normal and working good.
Course generator have a problem too, like in last pecture. 

[log.txt](https://github.com/Courseplay/courseplay/files/3202643/log.txt)

![FarmingSimulator2019Game 2019-05-21 15-00-38](https://user-images.githubusercontent.com/32776608/58098676-5fb07e80-7bda-11e9-887c-0786a540576e.png)
![FarmingSimulator2019Game 2019-05-21 15-00-58](https://user-images.githubusercontent.com/32776608/58098691-65a65f80-7bda-11e9-93d6-fd1a82d24142.png)
![fsScreen_2019_05_21_15_12_56](https://user-images.githubusercontent.com/32776608/58099016-0eed5580-7bdb-11e9-8c40-08645f87c48e.png)

**Comment by pvaiko** [comment]
Upgrade AutoDrive to the newest one.

**Comment by SuBerPL** [comment]
Ok updated and everything is working, except unloading in mode 2. CP is driving throught unloading point without unloading.

**Comment by pvaiko** [comment]
Ok, so this can be closed. I'm sure there's an issue already for your mode 2 problem, also see #3311
