### ISSUE TITLE
SKE 18.5 and Zunidisc Mode 5

### ISSUE THREAD

**Issue by piropiro24** [Courseplay/courseplay#3825]
Using mode 5 with SKE 18.5 and ZuniDisc attached, cause SKE activation.
![image](https://user-images.githubusercontent.com/49072277/58173181-fcd2ec00-7c9a-11e9-8e83-5821df87e499.png)

**Comment by pvaiko** [comment]
We are not turning it on, looks like Giants does that for the sprayer. As it does not seem to be causing any issues, I would not want to spend time on this.
