### ISSUE TITLE
Selected Fruit for Mode1 is not saved for Vehicle.

### ISSUE THREAD

**Issue by hackselgut** [Courseplay/courseplay#3826]

**Comment by hackselgut** [comment]
Hi.  I tried your option of seeing if any other issues were related, so dis hot get in to a problem description, sorry,. So here is the fault I notice A course using mode 1 is to pick up crop from a silo and deliver to a sell point, you have to set what type crop you are loading, I set the type from lit and start course, works as it should. Later on I shutdown, I restart later on and restart coursers, now the type of crop I selected is now at wheat, first item in a list of 10 or more, so the selected did not lock in.  Bob

**Comment by hackselgut** [comment]
Hi, Tensuko,,,,,thank you   Bob.

**Comment by Lupo36** [comment]
Hallo, ich möchte hier gleich was hinzu fügen:
Kurs beginnen am........"naheliegensten Wegpunkt", "ersten Wegpunkt", "aktuellen Wegpunkt" werden leider auch nicht gespeichert. Nach Neustart des Spiels ist immer "nächsten passenden Wegpunkt" eingestellt.

Hello, I would like to add something here:
Course start on ........ "most obvious waypoint", "first waypoint", "current waypoint" will unfortunately
also not saved. After restarting the game, "next matching waypoint" is always set.

**Comment by Tensuko** [comment]
It is not said, that it will find the way into CP, but will add this to the list and discuss this with the team, if it is possible to save more settings like those. But it is not number one on the To Do List...

**Comment by Lupo36** [comment]
Hi, Tensuko,,,,,thank you

**Comment by Lupo36** [comment]
Hallo Tensuko,
wurde schon was beschlossen?

**Comment by Tensuko** [comment]
Should be fixed now, just loaded savegame and setting was still there.
