### ISSUE TITLE
Auger wagon hits harvester once unloaded as it returns to unload course. 

### ISSUE THREAD

**Issue by johnonline1** [Courseplay/courseplay#3827]
I have setup a course to unload my combine in overload mode. 
When the combine calls to be emptied by the auger wagon it takes off to the combine then it empty's it then it takes off and cuts in front of the combine and mucks up the whole course.
I have to manually send it of to unload then it gets to the first way point of the unload course and it cant find the 1st way point to unload the auger wagon, l have to send it manually on its way then it unloads into the waiting truck and waits for the combine to recall for its next pickup again.
It still needs a bit more work to get it right ,l think the auger wagon once it is loaded by the combine needs to wait for 6-8 seconds before it goes back to way point one that way it wont hit the combine as it moves off.
Thank you for all your hard work course-play real makes this game what it is.
Regards john

**Comment by Tensuko** [comment]
#3311 
#3472 
Closed.
