### ISSUE TITLE
CP won't  load on 4X maps with multi fruits

### ISSUE THREAD

**Issue by Redneck0Farmer** [Courseplay/courseplay#3828]
Ok so the two maps that I now for sure are the Western Australia and Midwest Horizon. there may be more but I haven't tried any others but these two. I can get it to work with Farms of Madison County witch only has the standard in game fruits and is also a 4X map.     I have also tried uninstalling all miss other then CP in the log it stops at some thing about weeds or weed density I don't remember exactly what it says any way it freezes my whole system and I have to do a hard restart

**Comment by Tensuko** [comment]
Why you didn't post the logfile ?
https://github.com/Courseplay/courseplay/wiki

**Comment by johnonline1** [comment]
I had this problem yesterday ,go into you user/Documents/fs19 and delete your top courseplay folder that stores your current courses you have made in the game and retry the map it will load with no ptoblems.
There isccan issue someware but until its found out what is causeing the conflict thats the only fix that works.
Jope this helps...

**Comment by iljarogoff** [comment]
Playing on a 4x map with multifriut (DonDiego) and have no issues with cp not loading

**Comment by Redneck0Farmer** [comment]
I didn't post the log file because it had been a few days since I had tried it and had started playing on a different map, so no log for the two maps in question.   How the post that  johnonline1 made did at least temporarily fix the issue, but if it happens again I will post the log file.

**Comment by johnonline1** [comment]
I m still having issue with the fs19 4x map Dondiego myself but l don,t mind redoing courses if that loads the game.
But the funny thing is it loads most of the time the game loads but every once and a while it wont and its all course plays doing ,lf i remove course-play my game load every time.
Theres a gremlin in course-play at the moment but the team will sort it out l m sure.
