### ISSUE TITLE
Ropa maus & nawaro v2

### ISSUE THREAD

**Issue by Twetch** [Courseplay/courseplay#3829]
Hi,Ropa maus and nawaro was changed since FS17 and they dont unload to trailer just by drive under conveyor,so i want ask if possible allow it to be used as forage harvester and unload it with mode 2(it will drive only with trailer under conveyor)? I test it already in field work with straight course and it barely work,but speed is to high.This can be really good help for beet or silage transport for people who like it this way...

Example:
https://www.youtube.com/watch?v=8N-whUvAm-U

![fsScreen_2019_05_23_15_48_51](https://user-images.githubusercontent.com/22034856/58259155-46dbd080-7d74-11e9-9c8a-011259458b3a.png)

**Comment by FS19-CP** [comment]
I would love to have an operational mode for the Maus.

My main focus is generally silage, to the extent that I've removed the process limitations from the BGA.xml... so, every few game days, I'm using the Maus to load two to three million liters of silage into four trucks on a transport loop... the Maus doesn't stop at all with this arrangement.

Whether a prerecorded bunker course, or an awareness of the material that is there, it would be incredible for the Maus to have the capability of moving through the bunker, and moving the belt by tracking a preset unload area.

**Comment by Tensuko** [comment]
I think we bring this back when Mode2 is fully working, as it basically is a Harvester that needs to be unloaded :)
