### ISSUE TITLE
Drescher fährt Rohr beim abtanken immer wieder ein

### ISSUE THREAD

**Issue by S22e14** [Courseplay/courseplay#3831]
Hallo,
Ich habe das Problem, dass der Drescher (S790) das Rohr immer wieder einfährt, wenn das Abtankfahrzeug neben den Drescher fährt. Außerdem fährt das Rohr ein wenn das Abtankfahrzeug unter dem Rohr ein Stück vor fährt, und dann wird es auch nicht mehr ausgefahren. Kann ich da irgendetwas in den Einstellungen verstellen? Habe bis jetzt nichts passendes gefunden. Abtankfahrzeug ist btw Roadrunner und Krampe SB II 30/1070

**Comment by Tensuko** [comment]
logfile bitte und wie wird der Abfahrer gefahren ? AD, CP Mode2 oder manuel ?
Drescher wird mit CP gefahren ?

**Comment by S22e14** [comment]
Also er wird mir CP Mode 2 (Wenn es der Modus Kobiniert abtanken und abfahren ist, sorry ich weiß jetzt nicht alle Begriffe was was ist) gefahren, und der Drescher wird ebenfalss mit CP gefahren.
[log.txt](https://github.com/Courseplay/courseplay/files/3219477/log.txt)

**Comment by S22e14** [comment]
Was ich vielleocht hinzufügen kann, ist das es unregelmäßig nicht funktioniert. Manchmal geht es, manchmal auch nicht. Ein genaus Schema. wann es nicht funktioniert, kann ich nicht erkennnen.

**Comment by Tensuko** [comment]
#3311 
Closed.
Bitte noch etwas Geduld...
