### ISSUE TITLE
Approach design of the pathway to the pipe on a Ropa Harvester

### ISSUE THREAD

**Issue by hackselgut** [Courseplay/courseplay#3834]

**Comment by hackselgut** [comment]
The pathway built to unload a Ropa Harvester is a poor design, The vehicle for loading comes in behind the harvester, ( now think of the shape of a box )turns at the bottom right corner, now it goes to the top left corner to approach, thus it is approaching at an angle to the pipe, the pipe,, this a problem depending on where you are located on the field for the unload operation. Using mode 2 for this operation.  Bob

**Comment by RUGhost** [comment]
The present mode 2 is outdated. No support for this mode from dev. You need to wait for the new mode 2.

**Comment by Tensuko** [comment]
#3311 
Closed.
