### ISSUE TITLE
After cleaning up old, unnecessary courses from course folder and coursemanager.xml, courseplay overwrites remaining courses with new ones.

### ISSUE THREAD

**Issue by corrado33** [Courseplay/courseplay#3835]
Very low priority thing here.

What I did was go through my courses folder and go through the coursemanager.xml file and delete literally every course I wasn't using. I didn't like the courses cluttering up my folder and, at the time, I was under the impression that the massive number of courses, including many, many unused ones (in the hundreds) were causing some courseplay issues. 

They probably weren't, and this isn't something most people would do, but it's still a rather unexpected and... unpleasant thing to deal with.

I've since learned that the courses I've been making SINCE I've done that have started their file name numbering at the lowest number of course I deleted. (The lowest course number I deleted was course #41, my first course I created after the "mass purge" was a NEW course 41, then 42,43,44, etc.)

For example.

My course file numbers before I deleted anything were courseStorage0001-0200 (for example). Then I deleted course # 41-43, 57, 65, etc. from both the folder and from the coursemanager.xml (I just deleted the whole line.)

Now, whenever I record a course in courseplay, it started back at number 41. So my first course recorded after I deleted things was courseStorage0041, then 0042, then 0043... then 0044, which was an already existing.... still in use course. Now there were two references to course 44 in the coursemanager.xml file. This is... obviously a problem. Not only did it overwrite a previous course, but now when I load either course it points me to the most recent one. This isn't a huge problem for generated courses, but when you've spent a good amount of time making a manual course, it's a bit more problematic considering the old course is quite literally... gone. No longer with us, deleted, overwritten. Buh bye. Etc.

While this does not affect the operation of courseplay, I feel that there should be a bit more rigorous overwrite protection or namecheck when creating a new course file name. ;) Even if for the reason of sharing courses between players. Or, you know, for idiot protection, in my case specifically. 

Thanks for all your hard work, I know this is low priority and you have a lot better things to work on, but just something to consider if you ever get back to that part of the code in the future. :)

**Comment by corrado33** [comment]
I was in the middle of fixing it when I decided to write this up, but here is one of my smaller half fixed coursemanager.xml files. I'm unsure how I'm going to fix it completely. I may have to just renumber all of my courses, which isn't a huge issue with a little bit of scripting. 

[courseManager.zip](https://github.com/Courseplay/courseplay/files/3219729/courseManager.zip)

**Comment by abehnke** [comment]
For CP5, I found that in courseManager.xml I must maintain the sequence of slots.  The deleted ones should be replaced with, for example,

 <slot fileName="courseStorage0067.xml" isUsed="false"/>
 
The "courseStorage####.xml" are slots for courses.  The number of slots can be extended but there can be no gaps in the sequence.
 
I assume the above is true for the current CoursePlay?

I use the DOS command:
sort < coursemanager.xml > c:\temp\sorted.txt
to help verify there are no duplicates or gaps in the sequence.

**Comment by pvaiko** [comment]
We haven't changed anything (yet) in the course management since CP5. 

As for the original problem, I don't think it is a bug since as long as you manipulate courses from within CP they are not overwritten. And don't think we'll have time to do anything with it, looks like @corrado33 has at least some knowledge of scripting, we always welcome pull requests...

(I just started with a change to load the courses (courseStorage*.xml files) on demand only and not at startup.)
