### ISSUE TITLE
Menü unsichtbar

### ISSUE THREAD

**Issue by MatrixSystemPVP** [Courseplay/courseplay#3836]
Guten Tag,
ich habe ein fehler gefunden. Unswar wenn man einen abfahrer im kombiniert modus einstellt dann wird das menü unsichtbar aber man kann es trotzdehm benutzen. In der Konsole kommt folgender fehler: 

Error: Running LUA method 'draw'.
C:/Users/USERNAME/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00224/AIDriver.lua:581: attempt to index field 'course' (a nil value)

ich hoffe ihr könnt es beheben und das man das versteht was ich geschrieben habe :D

MFG MatrixSystemPVP

**Comment by Tensuko** [comment]
Ein komplettes logfile wäre gut. Einfach per drag and drop in das Kommentarfeld ziehen.

**Comment by MatrixSystemPVP** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3220286/log.txt)

**Comment by Tensuko** [comment]
#3311 
Vermute aber, dass es in Kombination mit AD zu diesm Fehler kommt.
@pvaiko @Stephan-S kann das sein ?

Notepad++ 1028

2019-05-25 21:37 C:/Users/Kevin/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/AutoDriveDriveFuncs.lua:191: attempt to index a nil value

Danach kommt
2019-05-25 23:01 Error: Running LUA method 'draw'.
2019-05-25 23:01 C:/Users/Kevin/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00224/AIDriver.lua:581: attempt to index field 'course' (a nil value)

Selber habe ich das noch nicht probiert mit aktiven AD einen Mode2 Fahrer in CP ein zu stellen.

**Comment by Stephan-S** [comment]
Sieht so aus als würde hier versucht einen AutoDrive Fahrer zu starten, während die Auswahl der Ziele nicht korrekt war. Da fehlt auf meiner Seite noch ein ~= nil check.
Aber auf jeden Fall war kein bzw ein bereits gelöschtes Ziel ausgewählt.

Die Auswirkungen auf CP kann ich hier aber nicht direkt sehen.

**Comment by Tensuko** [comment]
@MatrixSystemPVP 
Update AD bitte mal auf 1.0.2.2 und schau, ob das Problem wieder auftaucht.

**Comment by MatrixSystemPVP** [comment]
@Tensuko Ja das mit dem munü klappt, es wird jetzt angezeigt vielen dank.

**Comment by Tensuko** [comment]
Ok super, danke an @Stephan-S 
Closed.
