### ISSUE TITLE
Wechseln zwischen MODE1 und MODE2

### ISSUE THREAD

**Issue by Trigger87** [Courseplay/courseplay#3838]
Hallo zusammen,

ich finde Courseplay echt super und freue mich über jedes Update das ihr entwickelt.

Persönlich nutze ich den Mode1 (Abfahren) und den Mode2 (Abtanken + Abfahren) sehr häufig. Leider habe ich bei Mode 2 festgestellt das dieser sich auf dem Feld zwar super verhält, aber auf der normalen Straße einige Probleme macht:

1) Mode2 - Rücksichtloses Verhalten gegenüber dem Verkehr (sehr dichtes Auffahren und rammen der Fahrzeuge)
2) Mode2 - hält nicht so gut wie Mode1 die Spur? (Selber Rundkurs, anderes Ergebnis)
3) Mode2 - falsche Geschwindigkeitsberechnung in der BGA zum Abkippen
4) Mode2 - Hält auf der Straße teilweise entgegenkommenden (abbiegenden) AI-Verkehr an (so wie beim Wenden auf dem Feld)

Momentan wechsel ich also ständig zwischen MODE2 (auf dem Feld) und MODE1 auf der Straße manuell hin und her. Ich habe auch verstanden das sich dieser MODE2 als WIP-Project verhält.

**Gibt es nicht die Möglichkeit in der Modifiaktion am Übergang von Feld zu Straße auf Mode1 zu wechseln und beim zurückfahren von Straße auf Feld wieder Mode2 zu aktivieren?**. Das würde euch auch einiges an Entwicklungszeit hinsichtlich MODE2 sparen da der MODE1 (Abfahren) doch sehr gut funktioniert.

Ich hoffe meine Sichtweise ist nicht zu sehr eingeschränkt oder zu speziell und freue mich schon auf kommende Updates eurer Modifikation. Vielen Dank für eure investierte Zeit :)

Trigger

**Comment by Tensuko** [comment]
#3311 
Mode2 muss halt Umgestellt werden auf das neue System.
Ich weis, dass es nun schon eine weile dauert, aber ich kann nur nochmals um ein wenig geduld bitten.
CP ist halt auch nur ein Hobby Projekt und muss dem realen Leben ab und an weichen und dann ist nicht all zu viel Zeit für CP.
Wir sind dran und die Issues/Wünsche sind nicht weg.
Deine Beobachtungen sind auch schon in anderen Issues verpackt gewesen und stehen alle auf unserer Liste.

Eventuell kannst du ja was mit AutoDrive in der Zeit anfangen. AD kann bereits den CP Drescher abtanken (etwa holbrig noch), aber es geht.

Mode2 wird kommen, keine Sorge :) 
Closed.
