### ISSUE TITLE
(suggest) CCW should be default headland direction 

### ISSUE THREAD

**Issue by enderwiggin07** [Courseplay/courseplay#3839]
In a tractor the controls and monitors are mainly on the right hand side.  So if there is an option you would do your perimeter with the field edge on your right hand side, meaning you're traveling counter clockwise to the field.   

It's not unusual to have to go the wrong way (clockwise) but it's preferred and natural to keep the perimeter on your right

**Comment by FS19-CP** [comment]
I don't see why there would be a firm preference either way.

Combine pipes are on the left, meaning doing the headlands CCW would keep the pipe in the crop.

With racetrack patterns, the direction of the headland is the main determinate of whether or not there's an extra pass to get to the starting end.

**Comment by enderwiggin07** [comment]
You're right, I was only thinking about field work. There's no reason to make a change since the preferred side isn't consistent
