### ISSUE TITLE
BunkerSilo Mode 10 isn't working? 

### ISSUE THREAD

**Issue by kleba78** [Courseplay/courseplay#3840]
Hi there,
i am just testing Courseplay Six but i miss mode 10 ( bunker silo ), is it not yet implemented.  The courses like the previous versions of Courseplay.

---------------------------------------------------------------------------------------------------
Ich teste gerade Courseplay Six, aber ich vermisse Modus 10 (Bunkersilo), ist es noch nicht implementiert. Die Kurse ähneln den Vorgängerversionen von Courseplay

Do you need any further information?

**Comment by Tensuko** [comment]
Bunker Mode not implemented yet.
I cant say when that Mode will come back, as the priority number one is Mode 2 rework.
