### ISSUE TITLE
Unloading a combine using mode 2

### ISSUE THREAD

**Issue by hackselgut** [Courseplay/courseplay#3841]

**Comment by hackselgut** [comment]
As the vehicle on mode 2 comes to the combine on the side that has been cut already the vehicle will load then will proceed to go forward, thus crossing in front of the combine, thus getting into a collision with the combine. If approach is on the uncut side all works as it should do.,I am cutting across the field, side to side, Vehicle on mode 2 is on one end of the field. Cutting speed is 6 mph or less.     Bob.

**Comment by Tensuko** [comment]
#3311 
Closed.
