### ISSUE TITLE
Drescher fährt bei Beendigung der Feldarbeit Rohr nicht automatisch aus - Combine does not extend pipe automatically when field work is completed

### ISSUE THREAD

**Issue by haamic** [Courseplay/courseplay#3842]
Hallo
Ich spiele mit der version 6.01.00225. ich weiss nicht, ob das schon mal ging, aber der Drescher bleibt nach Arbeitsende stehen, ohne das Rohr auszufahren. Somit kann der Abfahrer (AD) nicht den Rest abtanken.
Gruss Micha
---------------------------------------------------
Hello
I'm playing with version 6.01.00225. I don't know if that's been possible, but the combine stops after work without extending the pipe. So the driver (AD) can't load the rest.
Greetings Micha

**Comment by Tensuko** [comment]
Look into #3792
Closed.
