### ISSUE TITLE
Abfahrer kollidiert regelmäßig mit Mähdrescher

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#3843]
Siehe Bilder, Fehler besteht schon länger...
Abfahrer ist voll, anstatt zu warten bis der Drescher vorbei ist, zieht er gleich nach links um den Abfahrer-Kurs zum Silo zu fahren.
![fsScreen_2019_05_27_19_38_59](https://user-images.githubusercontent.com/21023840/58433427-90e7ed80-80b7-11e9-915c-9fe5b0139eba.png)
![fsScreen_2019_05_27_19_39_05](https://user-images.githubusercontent.com/21023840/58433429-92191a80-80b7-11e9-8853-5141d66957d5.png)
![fsScreen_2019_05_27_19_39_07](https://user-images.githubusercontent.com/21023840/58433432-92b1b100-80b7-11e9-80bf-e06fca513ec4.png)
![fsScreen_2019_05_27_19_39_10](https://user-images.githubusercontent.com/21023840/58433434-93e2de00-80b7-11e9-8971-68ba030d286f.png)

**Comment by Tensuko** [comment]
#3311 
Closed.
