### ISSUE TITLE
seeders and cultivators skips spots on ends

### ISSUE THREAD

**Issue by newride** [Courseplay/courseplay#3844]
when i mode 4 and mode 6 when the tractor gets to the end it makes it turn and starts the nest round but it dosen't stop and low the implement it just keeps driving and then it leaves a strip. in fs17 the tractor would stop and let the implement lower all the way then it would take off.

**Comment by johnonline1** [comment]
That is so true in fs17 the tractor stopped at the start of the field and lowered the attachment down then took off. in fs19 course-play it try s to do it on the run and lower the attachment to late and it miss,s the edge of the field.
There needs to be a stop then lower then go.

**Comment by Tensuko** [comment]
Logfile and Screenshot and what tools and Tractor did you use.
I don't have had any problem with the tools I used on my savegame, so some more information would be great so I can test and check this and maybe find the Issue.

**Comment by FS19-CP** [comment]
I've been seeing this as well, under certain circumstances. For me, mainly when using the racetrack course, the last few turns will leave small strips on headland edge.

Experienced with Amazone Condor 15001, as well as a JD DB60 mod.

**Comment by pvaiko** [comment]
@FS19-CP which version did you use? I made quite a few changes to the racetrack pattern lately.

**Comment by FS19-CP** [comment]
.225!  I'll check out the latest release tomorrow. Thanks.

**Comment by pvaiko** [comment]
@FS19-CP make sure you regenerate the course. 

What is your opinion on stopping while lowering the implement? I've seen combines lowering the header without stopping, I've seen tractors with sowing machines stop at the beginning the row, not sure what the best practice is.

**Comment by FS19-CP** [comment]
Will do.

My experience with planting is more limited, but yes, it seems you would generally stop, lower the planter, and go... mainly, this is a function of GPS and setting up for the pass. I'm sure most planters would be just fine being lowered while rolling, but it seems like everyone I see will set up for the pass before lowering the implement. Tillage tools tend to just be dropped while on the move, as the forward motion is what drives them into the ground anyway. 

In a combine, you would try to keep the machine moving, simply lowering the header when approaching the crop.

**Comment by Tensuko** [comment]
Should be improoved in V230, as tools stop when lowering.
Closed.
