### ISSUE TITLE
Suggestion: Headland Turn manuver

### ISSUE THREAD

**Issue by RUGhost** [Courseplay/courseplay#3845]
Some equipment does not allow tractor to pullback (see the picture). But Tractor always pull it back if you use "Headland corner as Turn". If i use "turn on field deactivated" and the tractor do the turn like the video clip in headland, this problem should be solved.  "Headland corner as Smooth" has no problem but it left a chunk of unworked area.

![FarmingSimulator2019Game Screenshot 2019 05 28 - 14 39 17 02](https://user-images.githubusercontent.com/48012198/58474285-83406f80-816c-11e9-99c3-beb5c6e5b1bf.png)
![FarmingSimulator2019Game Screenshot 2019 05 28 - 14 39 56 13](https://user-images.githubusercontent.com/48012198/58474310-8dfb0480-816c-11e9-85ea-628e4f545734.png)

https://youtu.be/1Sjx5sQcLxw

**Comment by pvaiko** [comment]
See #3470. 

I keep this open for a while in case someone has a video about how this is done in real life.

**Comment by enderwiggin07** [comment]
I don't think it would happen in real life.  If you have this big nice area you can pull your drill through, it would be part of the hill.

Real life this big seed drill would be used on fields so big that the little area unworked is inconsequential.

Smooth headlands turns is most realistic for this tool. 

You'd only really back into a corner with a tool you completely lift up with the 3 point arms
