### ISSUE TITLE
Ich kann die neueste Version nicht downloaden!

### ISSUE THREAD

**Issue by xV1RUZZ** [Courseplay/courseplay#3846]
Wenn ich versuche die neueste Version runterzuladen, dann bekomme ich an Ende nur Courseplay in der Version 6.01.00063. Ich nutze CoursePlay seitdem es draußen ist und hatte dieses Problem bisher noch nie.

**Comment by Tensuko** [comment]
Unten bei Assets
https://github.com/Courseplay/courseplay/releases
Zumindest kommt bei mir der Ordner mit der richtigen Version.

**Comment by xV1RUZZ** [comment]
Leider ändert das nichts, es wird zwar eigentlich die Version 227 heruntergeladen und in der .Zip Datei steht auch Version 227, allerdings wird im Spiel die Version 63 angezeigt und es ist auch die Version 63.

**Comment by Tensuko** [comment]
Ich schaue mal wenn ich zu hause bin

**Comment by Tensuko** [comment]
Das kann ich so nicht bestätigen.
Version 227 ist installiert bei mir und auch Ingame vorhanden.
Bitte einmal das logfile posten. 
https://github.com/Courseplay/courseplay/wiki

**Comment by xV1RUZZ** [comment]
https://gist.github.com/xV1RUZZ/51ead78834f327c002c69d54c71887ab

**Comment by xV1RUZZ** [comment]
https://gist.github.com/xV1RUZZ/e1fd203fdb4f7bb8c685fbb6e6d3936f

**Comment by xV1RUZZ** [comment]
Ich weiß zwar nicht warum aber jetzt läuft es. Ich habe CP zum 4 mal runtergeladen und zum 4 mal wieder eingefügt und auf einmal läuft das Spiel mit der Version 227. Woran es liegt kann ich nicht sagen, aber zumindest funktioniert es für den Moment. Vielen danke für deine Hilfe. 
MfG
