### ISSUE TITLE
Combi Offload Causes Game to Freeze

### ISSUE THREAD

**Issue by TheAngryGamerTAG** [Courseplay/courseplay#3847]
When I have a tractor on combi offload it causes my game to freeze and therefore i have to force close the game and lose any progress made since last save due to giants crappy save game function ive been trying to figure out if something is causing it but cant really find anything idk if it is the map or another mod of sorts but i dont believe it is being i am not using any modded equipment do you have anything on this like how long until it gets fixed. also it doesn't seem to happen at a set time sometimes it happens right when i click drive course others its just what seems to be out of nowhere.

**Comment by FS19-CP** [comment]
Mode 2 is being reworked by these awesome developers, so it's a non-starter until that is done. 

The ONE time I tried to run an auger wagon, starting with the pipe down, I got a hard freeze when I started the course. No freezes with the pipe up when you start, but it's not very functional anyway.

They're working on it, and it will surely be awesome.

**Comment by Tensuko** [comment]
As FS19-CP said, Mode2 is under rework. A bit more patient pls.
#3311 
Closed.

**Comment by TheAngryGamerTAG** [comment]
ohhh i didnt know what the mode numbers are i just refer to them by what they do but thanks about how long do you figure it will take. ima just gonna be doing combi offload by hand courseplay still really good tool for the fact it would be possible to harvest two fields at once the way i do without courseplay

**Comment by Tensuko** [comment]
No problem 
You just count from left to right for the mode number.
I cant say much about when,as this is still done in free time of the programer.
