### ISSUE TITLE
RUL gehen nicht bei allen Fahrzeugen

### ISSUE THREAD

**Issue by GeorgK1988** [Courseplay/courseplay#3850]
Hallo,
Vorweg. Hut ab vor eurer Arbeit! Ohne CP wäre LS nichts!! :)

habe aber leider das selbe Problem wie bei #3473 #3483, meine CP Version ist: 6.01.00227
Mein Abfahrer fährt zum Silo und sagt mir dann dass der ausgewählte Typ (Weizen) nicht vorhanden ist. Obwohl genug Weizen darin ist. Normal/Manuell befüllen klappt auch, nur über CP nicht. 

Desweiteren funktionieren die RULs nicht. Er schaltet diese nicht ein wenn er unterwegs ist. Funktionierte aber schon..!
Lg
[log.txt](https://github.com/Courseplay/courseplay/files/3237320/log.txt)
![2019-05-30 15_53_32-Greenshot](https://user-images.githubusercontent.com/49338248/58638093-4606e980-82f4-11e9-95f0-f42f42c61ea8.jpg)

**Comment by iljarogoff** [comment]
Nur ne Vermutung meinerseits... du hast ja direkt daneben das Dünger-Silo stehen, vielleicht bist du schon zu nah an dessen Trigger dran, bzw. der Trigger vom Hofsilo und vom Dünger-Silo überschneiden sich?

**Comment by GeorgK1988** [comment]
@iljarogoff jap das war es, es war zwar nicht das Dünger-Silo aber das Flüssigdünger-Silo was davor stand!!
Perfekt danke!!

Aber das Problem mit den RUL´s ist immer noch da. Bei manchen geht es, bei manchen nicht. Wie z.B. bei dem Gespann im Screenshot. auch beim originalen JCB geht sie nicht. Bei einem Mod (ein John Deere) da geht es wiederrum.. hmm..

LG

**Comment by Tensuko** [comment]
Wir schauen uns das mit den RULs mal an.
Wird aber keine hohe priorität haben.
Ich benenne das Issue dahingehend um.

Danke fürs Feedback und viel Spaß noch :)

**Comment by GeorgK1988** [comment]
@Tensuko  ja super! kein Problem ist ja nur ein Detail ;)

Darf ich vielleicht aus Neugier noch fragen wie es denn mit den anderen "Modulen" wie Silage fahren und Frontlader arbeiten beim CP aussieht? Darauf freu ich mich schon ganz besonders! :)

**Comment by Tensuko** [comment]
Ich kann nur so viel sagen, dass Modus2 (damit auch Modus3) vorrang haben, ich werde aber in der nächsten Besprechung mal wegen den anderen Modi fragen.

**Comment by GeorgK1988** [comment]
@Tensuko 
Alles klar, danke! Wäre cool wenn das wieder kommen würde!

Und nochmal, Hut ab was Ihr leistet!! Danke dafür!
Lg

**Comment by Tensuko** [comment]
Also ich bemerke bei meinen Fahrzeugen, dass dei gefühlt ständig RUL anhaben.
Ich weis nicht wie jetzt hier der Stand ist....
Gibt es noch Probleme damit ?

**Comment by GeorgK1988** [comment]
@Tensuko puh gute Frage, ich glaube manchmal gehen sie manchmal nicht, aber ich habe jetzt länger nicht gespielt.. ich werde mal die neueste Version laden und dann mal ausprobieren!

**Comment by Tensuko** [comment]
Einfach mal beobachten, wie es sich verhält, ist sowieso keine hohe priorität, aber wenn du Beobachtungen gemacht hast, teile sie uns gerne mit.

**Comment by Tensuko** [comment]
Ich weis nicht was ich hierzu sagen soll.
Wo gehen die RULs, wo gehen sie nicht, wann sollen sie funktionieren und wann sollen sie nicht funktionieren.
Wenn mal jemand eine klare Auflistung hierfür machen kann, wäre das sehr hilfreich :)

**Comment by GeorgK1988** [comment]
Kann man getrost schließen, hab es jetzt nicht mehr beobachtet. Es wäre mir aber auch nicht mehr aufgefallen beim letzten mal spielen.
Lg

**Comment by Tensuko** [comment]
Ok, ich danke dir für die Rückmeldung.
Closed.
