### ISSUE TITLE
6.01.00226 vehicles return to first point immaterial of last-marker setting

### ISSUE THREAD

**Issue by prjndigo** [Courseplay/courseplay#3851]
tractors with implements seem to reset "stop at last" to deactivated even when they're started with it activated... this results in a pile of running tractors fighting to return to the original trigger.

This was not a problem prior to 6.01.00200

**Comment by Tensuko** [comment]
We took away the option 'return to start' on teh generator.
Now they will do it automatically untill we add an Option into the HUD, wich will come soon.

He will only return to 1st point, if the 1st point is in the Headlands, maybe that helps you out till we added the option.

Closed.
