### ISSUE TITLE
6.01.00226 spreaders filled with lime "must be filled before use" when already full

### ISSUE THREAD

**Issue by prjndigo** [Courseplay/courseplay#3852]
Multiple spreaders filled with lime refuse to start course because of error "implement must be filled first" when already fully loaded

**Comment by Tensuko** [comment]
logfile and screenshot pls, also wich lime spreader did you use ?

**Comment by pvaiko** [comment]
log with debug channel 14

**Comment by zippgunn** [comment]
I had this happen to me as well, but my tracktor had a frontloader shovel as well, which was empty.
I checked that the object selection was on the spreader, but did not help.
Then I tried detaching of the front loader shovel and the front loader forks, then it CP worked as expected.
I suspect in some cases, CP is seeing the fronloader bucket as empty by mistake.

**Comment by Tensuko** [comment]
Closed due to inactivity.
Reopen when got logfile with V230 and Tool used.
