### ISSUE TITLE
6.01.00226 interface state fault, mouse unlink from first person/tractor view function caused by courseplay hud interface 

### ISSUE THREAD

**Issue by prjndigo** [Courseplay/courseplay#3853]
The mouse cursor becomes visible and unlinked from camera control/motion control in game (reduced turn rate and cursor comes off sides of game window) and this is directly related to courseplay's HUD because opening the HUD then closing it using the window[x] close button corrects the problem.

**Comment by Tensuko** [comment]
Can you give more information on what you did to make this happen ?
Also post a logfile pls.
I couldn't create this Issue yet, so I think that might be a Mod Conflict.
More details needed so we can check what causes this error.

**Comment by corrado33** [comment]
I have actually experienced the same thing, but have never thought anything of it. It's actually been happening for quite a while (for versions long before 200). 

I always thought of it as weird. It's almost like a "mid state" between the complete camera control you have when the courseplay hud is NOT open, and when the absolute lack of camera control you have when the courseplay hud IS open. The camera moves a little bit (almost like someone turned your camera sensitivity down to 25%)... but you can still see the mouse... and the courseplay hud is open. I'll try to grab a log file the next time it happens. It doesn't happen often, or regularly. Unfortunately I DO have a ton of mods installed.... so yeah, no help there, sorry.

**Comment by The-Wolzenator** [comment]
I have found that this happens with the Helper Advanced AI Mod as well. I have found that I can get the cursor to do as it is supposed to as long as I reopen and close either CP or HAAI. I have noticed that the trigger for this error is opening either CP or HAAI and then switching to another tractor and opening CP or HAAI in the second tractor, again leaving it open, then moving to a third tractor(vehicle) driving it, and then going back to either of the other tractors.

**Comment by Tensuko** [comment]
So it does only happen with another Mod, that open a HUD with right click ?

**Comment by The-Wolzenator** [comment]
The Helper AI has a hotkey of "LeftCTL+H" to open their hud, that then releases the mouse from the camera so that a player can manipulate settings in their hud. I have not tried to test if this is CP's issue, or if it is a Helper AI issue.

**Comment by Tensuko** [comment]
Closed due to inactivity.
If you found out wich Mod creaste the Issue, let us know.
