### ISSUE TITLE
Kollision Ls19

### ISSUE THREAD

**Issue by Marko230** [Courseplay/courseplay#3854]
Hallo, 
ich habe mal eine Frage. 
In LS 17 war es ja so, das wenn ein Fahrzeug im weg stand, courseplay das gemeldet hat und jetzt im LS 19 ist das ja nicht so.. Wird diese Funktion auch im Ls 19 kommen? 
Denn ich habe immer auf dem Feld nach dem Abtanken das Problem das der Abfahrer wenn er voll ist den Drescher wegschiebt. Ich benutze die neuste CP version.
Und wann wird ca die Funktion für das Silo zu entleeren ( Radlader mit schaufel ) freigeschaltet ? 
Danke für eine Info :) 
MfG Marko 

P.S. : Sehr tolle Arbeitet von euch :)

**Comment by Tensuko** [comment]
#3311 
Drescher schiebt den manuellen Abfahrer weg, werde ich mal ansprechen.
Die anderen Modi sind nicht vergessen, aber Mode2 (+Mode3) hat priorität.

**Comment by TSperfeld** [comment]
Hallo,
auch beim Courseplay Abfahrer und Drescher kommt es immer dann zu einer Kollision zwischen den beiden, wenn der Drescher wieder ins Schwad fahren möchte und der Abfahrer gleichzeitig in seine Warteposition, so dass der Mode 2 im Grunde derzeit nicht nutzbar ist.
Eine kurzfristige Lösung wäre es evtl. den Abfahrer einen kurzen Zeitraum warten zu lassen, bis der Drescher wieder arbeitet und dann erst in die Warteposition zu schicken.
MfG
Thomas

**Comment by Tensuko** [comment]
Es müsste eigentlich der Drescher warten, bis der Abfahrer weg ist.
Gibt viele Situationen, wo der Abfahrer im Weg ist.
Momentan geht es halt leider noch nicht.
Mode2 ist recht aufwendig, daher dauert es halt....

**Comment by Tensuko** [comment]
Closed.
Statusupdate kommt vielleicht dieses Wochenende, wenn ich die Zeit dazu finde...

**Comment by topo1010** [comment]
Hallo zusammen, es wäre echt super wenn im Häcksler-Modus  die Kollision wieder funktionieren würde. Sobald eine Schlange beim warten auf dem Feld ist crashen die Traktoren zusammen. Das nimmt leider echt ziemlich den Spielspaß. Wäre super wenn ihr euch das noch mal Anschauen könnt und beheben! Vielen Dank für den tollen Job ansonsten.

**Comment by Tensuko** [comment]
Das gehört zu #3311
