### ISSUE TITLE
CP 227 - Field Mode Sowing, headland turn around issue

### ISSUE THREAD

**Issue by zippgunn** [Courseplay/courseplay#3857]
See comment below.
Using CP 227

**Comment by zippgunn** [comment]
Seems the dynamic path generated is reversing the direction of turns, causing the tractor to get stuck. see screen shots. 
Suggest the turn spline maybe needs to be flipped on a mirror axis?
This happens more if the field is less square.
![20190601170950_1](https://user-images.githubusercontent.com/17567291/58745233-b39c4c80-8491-11e9-89cc-6fefddbcc0c1.jpg)
![20190601171000_1](https://user-images.githubusercontent.com/1
![20190601171028_1](https://user-images.githubusercontent.com/17567291/58745251-eb0af900-8491-11e9-8028-df8039743269.jpg)
7567291/58745239-ba2ac400-8491-11e9-8a0f-c0f51835e902.jpg)
![20190601171022_1](https://user-images.githubusercontent.com/17567291/58745240-bdbe4b00-8491-11e9-8ff8-dd9e66f84277.jpg)

**Comment by Tensuko** [comment]
@pvaiko #3421 ?

**Comment by pvaiko** [comment]
Try with 228 (945120763c9822ebe2e341da0fdd336932d0d5d9 , I managed to screw up the commit message...)

**Comment by zippgunn** [comment]
Perfect, thanks.
![20190602112237_1](https://user-images.githubusercontent.com/17567291/58755562-8dc28680-8529-11e9-8a93-648cc971e66e.jpg)
