### ISSUE TITLE
Gärreste werden beim Düngemodus nicht geladen

### ISSUE THREAD

**Issue by NicoDreamzZ** [Courseplay/courseplay#3859]
Guten Tag,

erstmal **vielen Dank** für die tolle Arbeit an Courseplay!
Ich habe momentan folgendes Problem, wenn im Dünge/Säen Modus der Abfahrer unter einen Gärreste Trigger fährt, füllt dieser das Fass nicht auf. Der Abfahrer fährt einfach daran vorbei, als wäre dort kein Trigger. Dies passiert auf den Orginal-Maps bei den BGA's sowie bei einer platzierbaren BGA als Mod. Ich habe folgend noch ein paar Logs angehängt.

Wenn man den Abfahrer startet (Channel 1)
https://pastebin.com/DUYERgEs

Wenn der Abfahrer unter dem Trigger durchfährt (Channel 2)
https://pastebin.com/ESpJcGYJ

Gülle am Kuhstall wird ohne Probleme bei mir nachgefüllt.

Getestet in 00224 und 00228 mit verschiedenen Güllefässern

**Comment by Tensuko** [comment]
Bitte channel 1 und 2 anmachen und die komplette log.txt anhängen als Datei
Was du auch mal machen kannst ist in LS19 F5 drücken, dann werden dort Trigger angezeigt und andere Dinge.
Ich hatte mal das Problem, das ich vorher noch durch einen anderen Trigger gefahren bin, danach kann man so auch schön schauen. Ich habe noch keine BGA im Betrieb, daher habe ich das mit der BGA noch nicht getestet, aber Gülle funktioniert z.B.

**Comment by NicoDreamzZ** [comment]
Genau, Gülle funktioniert bei mir auch problemlos, nur Gärreste will der nicht nachtanken.

Hier einmal ein Bild von dem Trigger (F5 Modus):
![20190605145412_1](https://user-images.githubusercontent.com/12086166/58958628-9faf5e00-87a3-11e9-8b14-0d01ca799802.jpg)

Und hier die Log.txt:
[log.txt](https://github.com/Courseplay/courseplay/files/3257318/log.txt)

**Comment by NicoDreamzZ** [comment]
Oke ich muss jetz peinlicher Weise zugeben das ich übersehen hab, das man im Einstellungen Reiter auch auf Gärreste umstellen muss. Funktioniert nun alles problemlos. Der Bug saß mal wieder selbst vor dem Rechner.
Danke für die Zeit die @Tensuko sich genommen hat um mir zu antworten ;)

**Comment by Tensuko** [comment]
Warte, das ist interessant. Die Auswahl des Ladegut ist eigentlich für Mode1 gedacht (bin ich der Meinung). Wenn es so funktioniert ist ja gut.
Saat und Dünger werden ja so automatisch aufgefüllt.

@ThomasGaertner zufall oder gewollt ?
