### ISSUE TITLE
Error Running LUA update

### ISSUE THREAD

**Issue by Phips99** [Courseplay/courseplay#3861]
Der Fehler tritt auf, wenn ich einen Courseplay Helfer starte. Dieser fährt kurz und dann fängt das Bild zu flackern an. Außerdem erscheint der folgende Fehler in der Logfile (siehe Bild)
![20190602132656_1](https://user-images.githubusercontent.com/49783287/58760624-c1f27300-853a-11e9-9f4d-f19249a92b16.jpg)

**Comment by Tensuko** [comment]
logfile ?
https://github.com/Courseplay/courseplay/wiki

**Comment by Phips99** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3244913/log.txt)

**Comment by pvaiko** [comment]
Da stimmt mit dem Kurs irgendwas nicht, ein Log mit debug channels 12 und 14 wäre hilfreich (aktiviert bevor der Kurs ist gestartet)

**Comment by Phips99** [comment]
Komischerweise habe ich den Fehler jetzt nicht mehr. Ich habe die Debug Channels aktiviert und den Kurs gestartet, aber kein flackern mehr vorhanden. Das Einzige was ich noch gemacht habe, ist ein Treiberupdate für meine Grafikkarte.

Trotzdem habe ich hier mal die neue logfile dazu gehängt:
[log.txt](https://github.com/Courseplay/courseplay/files/3248461/log.txt)

**Comment by Tensuko** [comment]
Sind noch ein paar Errors drin, gerade das mit dem Straw würde ich mal bereinigen:

Error: Failed to open xml file 'C:/Users/Philipp/Documents/My Games/FarmingSimulator2019/mods/LS19Real_straw_texture/modDesc.xml'.

Error: Missing descVersion attribute in mod LS19Real_straw_texture

Was mir zum ersten mal auffällt sind die Errors mit ReverseDriving requires a animation in 'vehicle.reverseDriving#animationName'!
Muss ich mal bei mir in die Log schauen...

**Comment by FlameTech-Entertainment** [comment]
In der aktuellsten Version habe ich leider auch LUA Call Stacks...

Der Fehler passiert, wenn ich einen Helfer im Häcksler einstelle und ich einen Abfahrer im Mode 2 anstelle.

[log.txt](https://github.com/Courseplay/courseplay/files/3271993/log.txt)

**Comment by Tensuko** [comment]
#3311 
Closed.
