### ISSUE TITLE
john deere 6m series don't work with mode 2

### ISSUE THREAD

**Issue by docgaming** [Courseplay/courseplay#3862]
i was using  john deere 6m series to unload my harvester but when it got to my silo it did not unload or show "tip trigger reached" i have had this problem with other modded silos so i tested it with a in game silo. that did not work so i tried my john deere 7R and 8R they both work ok in mode 1.2 and mode 6. the  john deere 6m series only unloads in mode 1 and 6.
there is nothing in the logs so let me know what channels to have open so i can send you a log file

**Comment by Tensuko** [comment]
So it us more about the silo trigger ? Tryed different trailers ? 
This could be related to #3311 
Can you make a logfile with debugchannel 1 and 2 when try to unload at the silo ?

**Comment by docgaming** [comment]
ok i don't get it i did a test with sek 802 trailer and tkd 302 trailer both did not work so i turned on channels 1 and 2 and tested some others they all worked so i tested the other 2 trailers again and now they work then i hit quit game with out thinking so i think i lost the log file for that. i tried new routes, silos etc to try and get it to well not work but it was all working ok now so i don't get what was going on.
here is the 2 log files i have when i tested it 
[log1.txt](https://github.com/Courseplay/courseplay/files/3245188/log1.txt)
[log2.txt](https://github.com/Courseplay/courseplay/files/3245190/log2.txt)

**Comment by Tensuko** [comment]
So, now it works all fine as it should ?

**Comment by docgaming** [comment]
ok so i had it again on other map open up channel 1 and 2 and tried 2 or 3 times in mode 2 and did not unload tried in mode 1 with same everything and it unloaded then i tried mode 2 again 2 times and they both worked.
[log.txt](https://github.com/Courseplay/courseplay/files/3266370/log.txt)

**Comment by docgaming** [comment]
after i reset the game i had the same problem i did the same as abouve to get it to work i had to do it many times for it to work when i did get it to work the CP hud and the info you get in the bottom right (speed etc) was gone so i stop all CP workers to get it to come back did 2 times then 3rd was working ok,
[log.txt](https://github.com/Courseplay/courseplay/files/3266647/log.txt)

**Comment by Tensuko** [comment]
Can you clean up your Errors and try again ? I will do some tests on it too later with V229.1

Error: Failed to open xml file 'D:/Documents/my games/FarmingSimulator2019/mods/FS19_RopaPackByStevieUNZIPME/modDesc.xml'.

Error: Missing descVersion attribute in mod FS19_RopaPackByStevieUNZIPME

Error: Invalid mod name 'New folder'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Error: Invalid mod name 'New folder (2)'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Error: Failed to open xml file 'D:/Documents/my games/FarmingSimulator2019/mods/Suedhemmern_Entpacken/modDesc.xml'.

Error: Missing descVersion attribute in mod Suedhemmern_Entpacken

2019-06-07 14:53 Error: Can't load resource 'D:/Documents/my games/FarmingSimulator2019/mods/FS19_Oakfield/map_preview.png'.

**Comment by Tensuko** [comment]
Also you are getting this LUA in your 2nd try:
2019-06-07 16:34 Error: Running LUA method 'draw'.
2019-06-07 16:34 D:/Documents/my games/FarmingSimulator2019/mods/FS19_coursplay/AIDriver.lua:581: attempt to index field 'course' (a nil value)

Wich CP Version you used ? It only shows 228, but it can also be 228.1 or .2 or .3 wich killed Mode2, should be ok with 229.1

**Comment by docgaming** [comment]
i am not at home now so i can't check i think i am using 228.2

**Comment by Tensuko** [comment]
Works fine with V236.
Also this is very old and inactive, so going to close this.
If still got anything, make a new Issue with the actual Error and a clean logfile.
Closed.
