### ISSUE TITLE
Mode1 Suggestion:  Wait until lowered

### ISSUE THREAD

**Issue by enderwiggin07** [Courseplay/courseplay#3863]
For trailers that lift to dump out of the rear, some sell points (on mod maps) might have you inside a building.  When the trailer is empty, the helper drives on and the trailer collides with the building until it lowers enough to let free.  

At any rate to me it's more realistic that you would lower the trailer before driving off anyway, but maybe some would disagree so if it wasn't too much trouble, an option for "wait until lowered" could let the helper pause at the unload point until the trailer was all the way down.

**Comment by Martinnygaard** [comment]
I think this is a good suggestion!

**Comment by ThomasGaertner** [comment]
try v293 and report ...

**Comment by RedMonster-HUN** [comment]
Hi. I am new here. I use cp for a long time and sometimes it makes me really mad. When I set up a combine to harvest and a tractor or truck to follow and unload the harvester, the truck doesn't recognise the combine and its header, and collides whit them. Could this be fixed? Cause it really destroys the game experience.

**Comment by Bobster82** [comment]
@RedMonster-HUN , If you have a new issue, please make a new thread, that make it more orderly ;)
And you using mode2, that mode is still in development ;)

**Comment by Bobster82** [comment]
@ThomasGaertner 
Works good, every trailer I used in mode2 waits till close, only problem I saw was when a trailer drive trough a bunker, the trailer stayed up, it didnt close ... I needed to close it manually

**Comment by Tensuko** [comment]
Works fine and Bunker+Mode2 is a different story and will be looked into after Mode2 rework is done.
Closing this.
