### ISSUE TITLE
228.1 and 228.2

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#3864]
Was hat es damit auf sich? Wo wird das neue "Feature" erklärt? Stelle nur fest, dass meine Sämaschine auf den Kursen, die ich mit 227 und davor eingefahren habe, nicht mehr sauber funktionieren, da an den Feldenden die Maschine zu früh anhebt, außerdem wendet der Schlepper zu eng, sodass an den Feldenden manchmal die Arbeitsbreite nicht genutzt werden kann bzw. überlappt (schneidet die Kurve zu stark)
![fsScreen_2019_06_03_17_16_52](https://user-images.githubusercontent.com/21023840/58813128-6e0f8900-8623-11e9-9058-0dd09512b280.png)

**Comment by Tensuko** [comment]
Hat schon einen Grund, warum das .1 und .2 ist und nicht im Main Branch...


BETA VERSION, COULD BE BUGGIER THAN USUAL

6.01.00228.1 Beta: turn maneuver refactoring

Create a front and a back marker node at the front/rear of the work area
and use these to determine when to lower/raise implements.

Also, let sowing machines stop while lowering to make it more realistic

Combine headland turn fixed, it lowered the header at the turn start
waypoint, but in headland turns lowering is controlled by the turn wp
attributes.

Abwarten und ohne logfile mit 12 und 14 kann man da nichts machen.
Ich konnte noch nicht alles vorabtesten, die Furhparkkombinationen in LS sind halt zu groß.

**Comment by Tensuko** [comment]
![fsScreen_2019_06_03_17_47_46](https://user-images.githubusercontent.com/27344744/58815402-cea0c500-8627-11e9-8192-fd81d0c72765.png)
![fsScreen_2019_06_03_17_46_48](https://user-images.githubusercontent.com/27344744/58815403-cea0c500-8627-11e9-9a93-5ec7eea68192.png)
[log.txt](https://github.com/Courseplay/courseplay/files/3248403/log.txt)
Funktioniert, Kurs aber neu erstellt, sollte eigentlich keine Auswirkung haben, da turn on the fly generiert wird...

**Comment by pvaiko** [comment]
@iljarogoff der Kurs ist auf deinem Screenshot leider nicht sichtbar daher ist es schwer zu sagen was das Problem sein könnte. Anheben müsste jetzt eigentlich besser sein, das andere Problem mit dem Feldende und Kurve versteh ich nicht.

**Comment by pvaiko** [comment]
Log mit 12 und 14 und ein Screenshot während des Turns.

**Comment by iljarogoff** [comment]
Alles klar, screens etc. kommen noch.
P.S.: als ich grade nochmal mein post gelesen hab, kam das was ich geschrieben hab glaub ich etwas motzig rüber... war nicht meine Absicht! Ihr macht hier super tolle Arbeit! Danke dafür

**Comment by Tensuko** [comment]
Das sollte eigentlich mit den Debugchannel 12 und 14 mitkommen.
@pvaiko was davon in meinen Screenshots sind die Front und Back Marker ? :D

**Comment by iljarogoff** [comment]
> 
> 
> @iljarogoff du erstellst keinen Marker, das macht CP, sind mit channel 14 auch sichtbar wie z.B. auf @Tensuko Screenshot.

Ah ok, hab ich mißverstanden. Kann man mit den Markern rumspielen? Also bspw. einen offset einstellen nach vorne/hinten?

**Comment by pvaiko** [comment]
Nein. Die sind die Work Areas der Maschine, festgelegt von Giants (oder der Modder).

**Comment by Tensuko** [comment]
Ich mach das hier mal zu, da es sich auf einen Beta-Stand bezieht.
Wenn noch Fragen oder Probleme auftauchen, bitte mit entsprechenden logfile ein neues Issue aufmachen.
