### ISSUE TITLE
11 Tabs at the to of the Hub. 

### ISSUE THREAD

**Issue by quick8ball212** [Courseplay/courseplay#3865]
I left click to Open The Course Play Hub, at the top of the hub are 11 different tabs. On the 9th tab witch would be the course generation option, it say Mode Specific Settings. and Im not able to generate a course. 

In this pic my mouse in hovering ove what should b the Course generation tab so show what is says.
![fsScreen_2019_06_03_13_58_55](https://user-images.githubusercontent.com/49184919/58827376-7f976780-8608-11e9-9bac-3be13316746f.png)
 
in this pic shows when i click on the mode specific Setting tab or what should b the Course Generation tab show what comes in stead of Course generation options. 
![fsScreen_2019_06_03_14_07_18](https://user-images.githubusercontent.com/49184919/58827643-254ad680-8609-11e9-97bc-d31f084b71e5.png)

**Comment by fudoido** [comment]
Course generating is on the main mode tab options now, if I remember from last version I tested last week.
Correct me if wrong.

**Comment by tuzlo** [comment]
Try using the Courseplay Control Tab

**Comment by Tensuko** [comment]
#3552 
Closed.
