### ISSUE TITLE
Combines doesn't extend Pipe when full

### ISSUE THREAD

**Issue by WindsHD** [Courseplay/courseplay#3867]
Firstly hello to all the good guys making Courseplay, i am using version 6.0100228 since 6.0100228.1-6.0100228.2 still have issues when turning and basicly corrupting the game.

My issue is with combines not extending pipes when stoped with full tank, they basicly refuse to extend the pipe even when the runner comes near or is almost at pipe tipping point. 

I can provide logs if needed(although i am not really sure when i can find them).

**Comment by WindsHD** [comment]
![image](https://user-images.githubusercontent.com/44409777/58871976-525bbf80-86c3-11e9-94ec-c144ed4e0b92.png)

Both veichels are on courseplay.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki
logfile needed.

**Comment by pvaiko** [comment]
> since 6.0100228.1-6.0100228.2 still have issues when turning and basicly corrupting the game.

I would really be interested in how exactly those are corrupting the game, would you mind open an issue for that?

**Comment by WindsHD** [comment]
Hmm after you guys gave me the idea of log.txt i went and cleaned my mod folder of any mods that caused error and it seems that fixed it.

And about the corupting the game, everytime the combine would turn it started spamming the turn function with nil value in console and that seems it delayed other functions of the game which caused the game to stop working as intended, couldnt get to menu or switch vechiles and some parts of the hud were missing, cant replicate the problem since i fixed my other problem.

Anyway i guess its fixed for now thanks for the help!
