### ISSUE TITLE
AIDriver.lua:589 (Error: Running LUA Method 'Draw')

### ISSUE THREAD

**Issue by Martinnygaard** [Courseplay/courseplay#3868]
Hi,

I am running two Case IH Magnums and two case IH combine harvesters (All vanilla)

When i start the newest bought CaseIH, the HUD dissapeares (everything else works fine, bu i cannot right-click and get it back to turn it off).
By using code "cpStopAll" everything stops and works again.

At the same time, i get the log error: 
Dirrection:/FS19_Courseplay/AIDriver.lua:589: attempt to index field 'course' (a nil value)
Error: Running LUA method 'draw'.

Yesterday when i first noticed it, i also had this error:
FS19_Courseplay/turn.lua:403: attempt to index local 'turnContext' (a nil value)
Error: Running LUA method 'update'.

Log file: [https://gist.github.com/Martinnygaard/c3437312a73e863652c5eeb81ee26a47.js](URL)
![cp](https://user-images.githubusercontent.com/26490587/58888498-c60fc380-86e7-11e9-8cd3-e7eda9eae85d.png)

**Comment by Martinnygaard** [comment]
I am using the new V6.01.00228.2.dev.

**Comment by Erwin1944** [comment]
2019-06-04 12:51 Error: Running LUA method 'update'.
2019-06-04 12:51 D:/Edwin Dávila/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay6/mode3.lua:65: attempt to perform arithmetic on a nil value

Same Over here
[log.txt](https://github.com/Courseplay/courseplay/files/3254231/log.txt)

**Comment by Tensuko** [comment]
@Erwin1944 this is a different Error.
Also in your log: Error: Invalid mod name 'FS_19 Courseplay 6'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
I don't know where that come from, also I wonder how you get a Mode3 Error, as Mode3 isn't even active yet.

@Martinnygaard I can't open you link. Can you just drag and drop the log.txt as Erwin1944 did ?

**Comment by Erwin1944** [comment]
I was working on work mode 2 and trying to create a new course, what i did to keep playing is create the course with another tractor, the error never came back

**Comment by Martinnygaard** [comment]
Okay - i've got it attached now.

I downloaded an earlier version (V6.01.00228) And that seemed to remove my problems.

[Log.txt](https://github.com/Courseplay/courseplay/files/3260099/Log.txt)

**Comment by Tensuko** [comment]
This is not your complete logfile, a lot is missing like loaded mods.
AD puts out Errors and some other Mods too.
Clear that up 1st...

**Comment by Martinnygaard** [comment]
After i downgraded to V6.01.00228 and now upgraded to V6.01.00229, ia have not seen the error again.
I will close for now and reopen later, if it occurs again.
