### ISSUE TITLE
Error: Running LUA method 'update' - turn.lua:404: attempt to index local 'turnContext' (a nil value) - when sending Mode2 Driver away

### ISSUE THREAD

**Issue by NSalai** [Courseplay/courseplay#3870]
When attempting to send a tractor to return to his course (go dump the tipper into the silo after offloading a combine) by pressing "Send Driver Home", game freezes. 

Originally encountered with mods (maps and equipment), stripped game down to vanilla with only courseplay 6.01.00228.1 in the mods folder and problem persists. 

Log attached. 

[log.txt](https://github.com/Courseplay/courseplay/files/3254749/log.txt)

**Comment by Tensuko** [comment]
Update to 288.2 but I think that have to do with #3311 but I wonder why it is turn.lua
@pvaiko you got an Idea ?

**Comment by pvaiko** [comment]
Yeah, it is the old mode2, using turn for the alignment course, you can try turning the 'align with first wp' off but then it'll most likely break somewhere else. That's why it is beta. Not sure I want to fix it.

**Comment by NSalai** [comment]
Apologies, didn't correlate that 'Combi' was Mode 2 and that it was the 'old' version...

So what is the recommended work around? Hop into the tractor and click "Continue" or "Drive Now" and then continue on with other tasks?

**Comment by Tensuko** [comment]
@NSalai just for getting the newer Version, didn't saw .3 when I wrote the comment.
Or you just go for the 229 or higher now, as the .1 .2 .3 are Betas for turn (I guess 229 doesn't include the turn rework)

**Comment by slam0** [comment]
Crash is still appearing in version 6.01.00229.2 Beta.

Log is attached.

[log.txt](https://github.com/Courseplay/courseplay/files/3269346/log.txt)

**Comment by pvaiko** [comment]
This is a bug in 129.2
