### ISSUE TITLE
Error : Running LUA method 'loadTriggerCallback'

### ISSUE THREAD

**Issue by Opa-Andre** [Courseplay/courseplay#3872]
Hi all, I've got a question regarding the error:
----------- snip -------------------
2019-06-05 07:05 Error: Running LUA method 'loadTriggerCallback'.
2019-06-05 07:05 /Users/andre/Library/Application Support/FarmingSimulator2019/mods/FS19_Courseplay/helpers.lua:129: attempt to call method 'getName' (a nil value)
-----------snip -------------------

From what I found out, it's related to the AI traffic system on some modmaps. 
For example: Playing the map [Muehlenland-Mittelkreis from Modhub](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=127462&title=fs2019) will show this error once during loading the savegame. If AI traffic is switched on, then the error will be thrown from time to time again in the log. 

If AI traffic is switched off, then the error only occurs once during loading the savegame, but before loading is completed, so I'm unable to setup CP debug levels. I assume that one of the AI vehicles (placed as deco elements in the map) as a "parked car" might be causing this, but going through the traffic system XML file didn't show anything obvious. All defined AI vehicles in the system do have a name "vehicle1", "vehicle2" and so on, so it looks normal.

So my question would be, what's CP looking for but unable to find? 

I attached my complete log as well, it's just starting the savegame, saving the game as soon as it is completely loaded (for the timestamp and ending - you'll find the error just before loading finished (where player game settings are applied).  

[log.txt](https://github.com/Courseplay/courseplay/files/3261642/log.txt)

Please ignore the additional mods loaded - the error occurs as well just with CP, the mod-map and the "compositeHallPack" (also from Modhub) which is needed for this map.

**Comment by Opa-Andre** [comment]
Hi @Tensuko , well my reported problem is more a "general" issue, as it's seen on several maps. The referenced Hof Bergmann does have several other issues with Courseplay due to specific scripts etc. Therefore I referenced the Muehlenkreis-Mittelland map (link in my first post) where it should be possible to find that specific cause much more easily.

**Comment by pops64** [comment]
Dup #3887

**Comment by Tensuko** [comment]
Try 249 or higher and report back, thx.

**Comment by Opa-Andre** [comment]
Confirmed - tried 253.  Thanks for fixing it.
