### ISSUE TITLE
Seit 228/229 hinterlässt der Drescher (wieder) Flecken beim Wenden

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#3873]
Das hat doch bis 227 sehr gut funktioniert. Aber seit 228 und auch mit 229 ist das Problem wieder da. Habe es mit den generierten Kursen von 227 als auch neu generierten Kursen mit 229 probiert.
![fsScreen_2019_06_06_18_21_09](https://user-images.githubusercontent.com/21023840/59049421-36554b00-8888-11e9-9a0c-730dc2f7a542.png)
![fsScreen_2019_06_06_18_29_50](https://user-images.githubusercontent.com/21023840/59049813-1f632880-8889-11e9-8dc5-cc9ff8622c4e.png)

**Comment by Tensuko** [comment]
Bilder vom Kurs ? Logfiel mit Debugchannel 12 und 14 ?

**Comment by pvaiko** [comment]
Ist das eine Beta Version?

**Comment by iljarogoff** [comment]
> Und Welche Version genau ? Mit .1 .2 oder .3 ?

229.1. eine neuere gibt es ja nicht

**Comment by iljarogoff** [comment]
> 
> 
> Ist das eine Beta Version?

wahrscheinlich ist es eine beta, ja

**Comment by pvaiko** [comment]
Keine Ahnung was du machst, ich kann es nicht reproduzieren. 

Wenn du es auf einer Modhub Map nachstellen kannst dann brauche ich ein Savegame und deinen Kurs

**Comment by Tensuko** [comment]
Ich konnte das so extrem auch nicht reproduzieren.
Das ich auf meinem selbst erstellten Feld mit rauf und runter mal ein kleines Büschel habe, was stehen bleibt, ist dann so, aber auch verständlich.
Ein gerades eckiges Feld wird zu 98%+ sauber abgeerntet.

**Comment by Tensuko** [comment]
Bitte einmal Feedback geben, wie es mit V232 aussieht, ob wir das hier zu machen können, danke!
