### ISSUE TITLE
Refilling manure spreader from conveyor belt does not honor "refill until" percentage

### ISSUE THREAD

**Issue by asyvan** [Courseplay/courseplay#3874]
Either I am doing something wrong, but when having a refill course to a manure conveyor belt (with a wait point) it does not honor the "refill until" percentage. It fills to 100% and then continues.

**Comment by asyvan** [comment]
Video will soon be available at:
https://youtu.be/1kVKlTLwTzA

**Comment by Tensuko** [comment]
Did you try it without the wait point ?
I am not sure if the conveyor gets noticed as a trigger to refill, if so, it should work without wait point.
Debugchannel 1 and 2 should tell more.

**Comment by asyvan** [comment]
I tried without wait point, CP does not stop at the conveyor (it's not recognized as trigger).
Do you still need debug 1 and 2?

It's not a big thing, the best would have been if CP recognizes the conveyor... that would automatically fix the "refill until".

**Comment by Tensuko** [comment]
I am not sure if that rly works, as the filling under a conveyor is nothing you trigger, it just starts as soon as a trailer is under it. So we can't send a start and stop command.
What you could do is, use the waitpoint to use a time how long it should stay under the conveyor.
Sry but this can't be solved like normal refill triggers :(
Closed.

**Comment by asyvan** [comment]
I am fine with workaround, my thoughts was just that even if the conveyor is not a trigger that CP can start/stop... CP can still detect if the trailer fills during the Wait and instead of continue only when full actually continue when fill-until is honored.
