### ISSUE TITLE
Overall status CP6?

### ISSUE THREAD

**Issue by AgroWillem** [Courseplay/courseplay#3875]
Guys,

No doubt that developing a good CP this time is a pain in the @ss.
As i see the # of issues and the modes that are not supported yet, it sure is.

It would be nice to hear from you what the actual troubles are and the perspectives.
A sort of Status Update would be nice.

Grtz,

**Comment by Tensuko** [comment]
Having time is the most trouble. Mode2 is rly not easy and we won't touch other Modes before that is reworked, as it is the most important (includes Mode3).

Maybe I can make a little Status Update this Weekend.
Basically CP is working fine, some Mod Issues, Map Conflicts and random strange behaviours wich are hard to find, but we are on it.

Closed.
