### ISSUE TITLE
Error: C:/Users/mah28/Desktop/Outlaw Farms FS19/Courseplay/courseplay.lua:128

### ISSUE THREAD

**Issue by OutlawRedneckGaming** [Courseplay/courseplay#3876]
Have a Error Running LUa method loadmapFinished got this on two maps i play on i attched my log file
[log.txt](https://github.com/Courseplay/courseplay/files/3267156/log.txt)

**Comment by Tensuko** [comment]
Only 1 Map in Modfolder allowed.

Errors in log:
Error: Failed to open xml file 'C:/Users/mah28/Desktop/Outlaw Farms FS19/FS19_JohnDeereDN345/modDesc.xml'.

Error: Missing descVersion attribute in mod FS19_JohnDeereDN345

Error: Failed to open xml file 'C:/Users/mah28/Desktop/Outlaw Farms FS19/Seed_Runner_3755_XL/modDesc.xml'.

Error: Missing descVersion attribute in mod Seed_Runner_3755_XL

**Comment by OutlawRedneckGaming** [comment]
Thanks for the info and im working on the other errors

**Comment by OutlawRedneckGaming** [comment]
so i took all my maps except the one i wanted and when i loaded it with courseplay it still has the same error i was told that the new update for farm sim has caused this but im not sure

**Comment by Tensuko** [comment]
What about the Mods with Errors ?
Wich map do you play now ?

**Comment by OutlawRedneckGaming** [comment]
Those are edits im still working on in my single player and i have tried on midwest and ravenport and even pv industries

**Comment by Tensuko** [comment]
Closed due to inactivity, if you still face that Issue with a clean logfile, let us know and we reopen this.
