### ISSUE TITLE
Issues with mod map Hof Bergmann 1.0.0.1 FS19 by farmer_andy

### ISSUE THREAD

**Issue by SpacemanJay** [Courseplay/courseplay#3877]
When you try to save, the game hangs and you have to force exit. Here is the entry from the log file when it happens. It worked fine in version 1.0.0.0 of the map. Naturally they say it's nothing they have done, even tho it worked before. I've emptied my mods folder, deleted the entire docs folder and let the game rebuild it, and verified game files via steam.
[log.txt](https://github.com/Courseplay/courseplay/files/3267980/log.txt)

2019-06-07 21:19 Error: Running LUA method 'onSaveStartComplete'.
2019-06-07 21:19 C:/...FarmingSimulator2019/mods/FS19_CoursePlay6/base.lua:1699: bad argument #1 to 'concat' (table expected, got nil)
2019-06-07 21:20 Application exit request forced.

**Comment by Tensuko** [comment]
Looks like some Trigger Issue:

2019-06-07 21:18 Error: Running LUA method 'loadTriggerCallback'.
2019-06-07 21:18 C:/Users/rsdnt/OneDrive/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/helpers.lua:129: attempt to call method 'getName' (a nil value)

Maybe this is it:
2019-06-07 21:18 C:/Users/rsdnt/OneDrive/Documents/My Games/FarmingSimulator2019/mods/FS19_HofBergmann/objects/roundbales/**roundbaleHay_w112_d130.i3d** (6.21 ms)
2019-06-07 21:18 data/objects/roundbales/roundbaleSilage_w112_d130.i3d (1.42 ms)
2019-06-07 21:19 Warning (script): 'setXMLInt': Argument 2 has wrong type. Expected: Int. Actual: Nil 
2019-06-07 21:19   ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (791): expectedType == Value::VoidType || expectedType == Value::ClassType
2019-06-07 21:19 LUA call stack:
2019-06-07 21:19   =C:/Users/rsdnt/OneDrive/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/base.lua (1698) : setXMLInt
2019-06-07 21:19   dataS/scripts/vehicles/Vehicle.lua (896) : saveToXMLFile
2019-06-07 21:19   dataS/scripts/missions/mission00.lua (827) : saveToXMLFile
2019-06-07 21:19   dataS/scripts/missions/mission00.lua (850) : saveVehicleList
2019-06-07 21:19   dataS/scripts/FSCareerMissionInfo.lua (292) : saveVehicles
2019-06-07 21:19   dataS/scripts/missions/SavegameController.lua (290) : saveToXMLFile

**Comment by SpacemanJay** [comment]
Thank you for looking at this. Their official position is that they don't use CP, so they have no interest in making sure their map works with it, even tho there are many, many comments in their forums from ppl asking about CP compatibility. They get angry about it even. It's also the best map I've ever seen, otherwise I'd just move on haha. Anything at all you guys can do?

**Comment by Tensuko** [comment]
Not sure but we will take alook into this for sure.

**Comment by Tensuko** [comment]
Helpers.lua Ref #3872

**Comment by SpacemanJay** [comment]
Thank you so much! Without CP I would have stopped playing long ago haha. Fingers crossed!

**Comment by Pleasure0102** [comment]
> Thank you for looking at this. Their official position is that they don't use CP, so they have no interest in making sure their map works with it, even tho there are many, many comments in their forums from ppl asking about CP compatibility. They get angry about it even. It's also the best map I've ever seen, otherwise I'd just move on haha. Anything at all you guys can do?

Well the problem is mostly you can't provide support for every mod to work with a map. Its just not possible. I actually talk with the creator a lot. And tbh we do not know what the issue is. It worked in an earlier version just fine.

**Comment by cwattyeso** [comment]
I imagine this map and author's who make maps like this are an absolute nightmare for the developers of mods like Courseplay. I can understand why an error is being caused by objects in the map like Bale Storage Points. Those are static objects, that really should be considered silos/misc buildings within the games placeable system. Yet for some weird reason this map author has decided that they should be setup as vehicles. The same thing applies to the other Production Stations around the map like the items that mix Pig Food, Cow Food, Cheese etc Why the mod author chose to set these up as vehicles makes no sense, when they are fixed objects in a map.

**Comment by Pleasure0102** [comment]
> I imagine this map and author's who make maps like this are an absolute nightmare for the developers of mods like Courseplay. I can understand why an error is being caused by objects in the map like Bale Storage Points. Those are static objects, that really should be considered silos/misc buildings within the games placeable system. Yet for some weird reason this map author has decided that they should be setup as vehicles. The same thing applies to the other Production Stations around the map like the items that mix Pig Food, Cow Food, Cheese etc Why the mod author chose to set these up as vehicles makes no sense, when they are fixed objects in a map.

Because you have no idea what they do :) they are automatic unload and stack systems which in the current system only work if they are setup as vehicles in this case as bale wagons. So they can stack the bales. You cannot set them up as other objects and make them do stuff vehicles do just like that.

**Comment by SpacemanJay** [comment]
Ohhh I wondered how those worked, they are very cool. I guess it's also worth noting that I don't have any log errors with all the other mods I use, 99% of them from Giants modhub. It's only when CP is introduced do they crop up, but again it's only with this map.

**Comment by Pleasure0102** [comment]
well i will do whatever i can to help get this fixed, but i myself have no idea about scripting and stuff. So Only thing i can do is test things or let Andy know what we could to or test etc.

**Comment by SpacemanJay** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3269500/log.txt)

Maybe this will help as well. This is a fresh log with all the mods I'm currently using, including CP. I also marked where I saved. Oddly enough, it doesn't seem to have as many errors in this one before the "save" event. I wonder if it's because I've got several hours on the map now, and I've interacted with most everything, including the auto-haystacks...?

**Comment by Tensuko** [comment]
Well seems like they did a nice way to get some features into their map, but when buildings ore placables treated as a custom vehicle type (I guess?) that is ofc conflict potential.
Not sure if there is anything doable from out side @pvaiko ?

**Comment by Pleasure0102** [comment]
the issue also was not there in the first version. There were already vehicles as buildings present in that version.

**Comment by Tensuko** [comment]
Is there a changelog for the Map Update, so you can figure out, what causes the Error ?

**Comment by SpacemanJay** [comment]
Yes, here it is...

Changelog v1.0.0.1



fixes:



- Pigsty Mistplane Fixed (Fixed)

- Pig Feed / TMR Mixer FillType / Fillplane will not be updated when done (fixed)

- Heuplane on Hayloft of Heutrockner wrong (fixed)

- Mod presses could not fix sticky balls (fixed)

- Hoftankstellen no vehicle refueling possible (fixed)

- Wood tribe triggers added at joinery (wood tribe trigger, sold by NPC)

- Buttermax, fill now possible no matter where the drum is (was necessary by MP Syncroproblem)

- Fixed decals on herbicide / liquid fertilizer / RubinTT buy trigger on Raiffeisen

- slurry storage at the farm, compatibility increased for standard liquid manure barrels

- Cow and Stable Hotspots l10n fix

- Reperatur neediness of productions disabled.

- Heuraufe mounted on paddock (horses lost in value without food)

- Spinning cotton could not be sold (fixed)

- Field7 farmland fixed generated callstack due to FieldInfo

- Production Script generated CallStack with standard feed mixer (fixed)

- Fixed TipCollision to straw barn, straw went through the walls

- Goal of BGA is now bought together with the BGA on the acquisition of the farmland

- Farm shop selling triggers fixed, under circumstances it happened that objects buggten under the ground and immediately sold.

- EffectHolder for biomass in sliding panels was missing (fixed)

- Fixed grass and clover, harvest levels

- Einzugssparticle effects fixed at the blowers (position was not right)

- Slurry storage, fill types were reset when filling another Filltypes eg digestate if already manure was in it (fixed)

- Fixed silos at the yard and compost silo, faulty plans (pyramids)



New features / changes:



- Heap height of the map adjusted to 2.80m

- BigBag Pack fully implemented in the map (MOD FS19_lsfmBigBagPack.zip can be removed from the modfolder)

- Big bag creation disabled with SeedMaster and VertiMixers (use bottling line for BigBag production)

- Transport prices of animals increased

- Eggs production slightly increased (from 0.1 to 0.8)

- Raiffeisen: manure can now also be bought (for farmers who do not have that much manure at the farm)

- Seedmaster production time slightly increased (from 20 to 60sec)

- FixFermenter production time increased to 15 min

- RubinTT can now also be bought via LSFM UniversalTanktrailer on Raiffeisen

- Deco figure removed at the inn

- Pig feed VertiMixPigFood / Silo upgraded technically and optically (for storage by trailer the lid must be open)

- Double silo at the yard, right bunker is now used for silage storage.

- sheepfold, woolen yard beautified

- Sheepfold, wool pallets changed to handy wool bales known from the farm miner from the LS17 (500L per bale)

- Productions now show the HUD from the outside you have to have been in it at least once in a production.

- Pig feed and mixed ration, sales prices reduced

- Horse stable, floor door can now also open from below, the trigger is located at the wheelbarrow

- Price for farmland of the BGA has been adjusted to a more realistic value

- It is now possible to wrap sticky balls with bale wrappers. Both round and square bales.

- Placeable Multisilo in Map Integrated (User requests for more storage options via Silo System)

- Dairy has got PDA symbol

- Milk tank in cheese dairy increased to 50,000 liters

- Added paving stones to the Landscape Tool

- BigBag filling line added (can be used to buy all big bags that can be bought in the shop + fill potatoes into portable bags)

- Households can be supplied with potato sacks, small sideline!



Updates Vehicles:



- Fendt 500 not Dediserver capable (fixed)

- added Lsfm UniversalTank Pack to SemiTrailer grain meal (only with SiloSkipper config)

**Comment by Pleasure0102** [comment]
[changelog.txt](https://github.com/Courseplay/courseplay/files/3269513/changelog.txt)

this way would have been easier :)

**Comment by Pleasure0102** [comment]
maybe a way to fix it could be that you add the courseplay option to each vehicle you buy, like the gps system does.

**Comment by SpacemanJay** [comment]
That sounds logical, FollowMe should do this is well, it's being installed to all the things it shouldn't be

**Comment by Tensuko** [comment]
> maybe a way to fix it could be that you add the courseplay option to each vehicle you buy, like the gps system does.

That sounds like a good Idea, but I am not sure if that is possible with the current System, how CP handels. Specialy for the Tools.

**Comment by SpacemanJay** [comment]
Even with the relatively small number of ppl who have the map update, CP is still mentioned every day in those private forums. If they release this update without it working with CP, their public forums are going to explode with complaints, and they will get very annoyed, very quickly.

**Comment by D3ltorohd** [comment]
Maybe you can use a ignore or blacklist ? There we can entry vehicles like this static on the map and cp will ignore this vehicles to do something or react with it ?

**Comment by Tensuko** [comment]
No Idea... Cant give a solution yet, got to figure it out in the relatedIssue, but that takes some time, sry.

**Comment by D3ltorohd** [comment]
One more idea, maybe you can at a query and when something is missing, you can ignore this vehicle and cp works continue. Only some thoughts.

**Comment by pvaiko** [comment]
Does anyone have a clean download link to this map? (I still wonder if we should even think about supporting mods not on Modhub...)

**Comment by SpacemanJay** [comment]
Not sure if this will work, the updated version is only for "supporters" so far, so I doubt it. If it does not, let me know and I'll link it to you as soon as they make it public.

https://www.lsfarming-mods.com/filebase/index.php?download/38/

**Comment by pvaiko** [comment]
Wow. So the expectation is to fix a conflict with a mod which isn't even available publicly?

**Comment by SpacemanJay** [comment]
It'll prob go public tomorrow, they said after the weekend, I had no way of knowing if you needed the map or not, or if you could tell what was going on by the log, or how long it might take before you guys looked at it, or if you were even going to look at it at all. So... sorry?

**Comment by D3ltorohd** [comment]
@pvaiko the mod is publicly available the latest version but first for supporters and then for all. I think for testing purposes

**Comment by Pleasure0102** [comment]
i have permission from the developer to share it with the CP devs, since he cannot figute out what the problem is. I will pm @pvaiko with the map dl link

**Comment by pvaiko** [comment]
@Pleasure0102 tell them to remove the aiVehicle specialization from their modDesc.xml, the line
`<specialization name="aiVehicle" />`
must go away as Courseplay installs itself in vehicles which have the aiVehicle specialization. I'm not sure why a hay barn or hay dryer must have the aiVehicle spec.

In general, they should check their baseDrivableHB and only add specializations which are really necessary for what they are doing.

If you unzip the mod and delete that line from modDesc.xml it should be saving the game with no errors.

**Comment by SpacemanJay** [comment]
Trying this now, will report back in a few

**Comment by Pleasure0102** [comment]
done, messaged to farmer_andy and it seems to work :) thanks guys, the next version will have this set. And CP will work again, we will also post the fix in the forums so people can fix themselves.
