### ISSUE TITLE
FYI Modhub mod  IMT 5360 tractor is freezing and deleting save game when Courseplay is present

### ISSUE THREAD

**Issue by VergylTantor** [Courseplay/courseplay#3880]

**Comment by VergylTantor** [comment]
It looks like the new Vehicle type issue

<vehicleTypes>
		<type name="5360" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
			<specialization name="baseMaterial" />
			<specialization name="tipOccluder" />
			<specialization name="foliageBending" />
			<specialization name="washable" />
			<specialization name="wearable" />
			<specialization name="dynamicallyLoadedParts" />
			<specialization name="animatedVehicle" />
			<specialization name="dashboard" />
			<specialization name="cylindered" />
			<specialization name="mountable" />
			<specialization name="ikChains" />
			<specialization name="wheels" />
			<specialization name="slopeCompensation" />
			<specialization name="speedRotatingParts" />
			<specialization name="enterable" />
			<specialization name="fillUnit" />
			<specialization name="motorized" />
			<specialization name="drivable" />
			<specialization name="aiVehicle" />
			<specialization name="aiImplement" />
			<specialization name="articulatedAxis" />
			<specialization name="lights" />
			<specialization name="attacherJoints" />
			<specialization name="powerTakeOffs" />
			<specialization name="suspensions" />
			<specialization name="connectionHoses" />
			<specialization name="honk" />
			<specialization name="wipers" />
			<specialization name="frontloaderAttacher" />
			<specialization name="bunkerSiloCompacter" />

**Comment by VergylTantor** [comment]
<vehicleTypes>
		<type name="5360" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
			<specialization name="baseMaterial" />
			<specialization name="tipOccluder" />
			<specialization name="foliageBending" />
			<specialization name="washable" />
			<specialization name="wearable" />
			<specialization name="dynamicallyLoadedParts" />
			<specialization name="animatedVehicle" />
			<specialization name="dashboard" />
			<specialization name="cylindered" />
			<specialization name="mountable" />
			<specialization name="ikChains" />
			<specialization name="wheels" />
			<specialization name="slopeCompensation" />
			<specialization name="speedRotatingParts" />
			<specialization name="enterable" />
			<specialization name="fillUnit" />
			<specialization name="motorized" />
			<specialization name="drivable" />
			<specialization name="aiVehicle" />
			<specialization name="aiImplement" />
			<specialization name="articulatedAxis" />
			<specialization name="lights" />
			<specialization name="attacherJoints" />
			<specialization name="powerTakeOffs" />
			<specialization name="suspensions" />
			<specialization name="connectionHoses" />
			<specialization name="honk" />
			<specialization name="wipers" />
			<specialization name="frontloaderAttacher" />
			<specialization name="bunkerSiloCompacter" />

**Comment by Tensuko** [comment]
Oh nonot again... Thx for the Information...Guess I will have to make a sticky list for those Mods.
What CP Version did you use ?

**Comment by VergylTantor** [comment]
Sorry, I was having trouble entering text for some reason. 
V 6.01.00229
Only Courseplay and IMT 5360 loaded.

**Comment by VergylTantor** [comment]
Sorry I didn't give better info and respond in a timley manor. I see
the issue has been rightly closed, but here is the info I intended to
paste into the origonal post. (I think I need to update Notepad++
because I had the same problem on Nexus Mods today.

I isolated the issue on Felsbrunn Map with only Tractor and CP
6.01.00229 active.

<vehicleTypes>
		<type name="5360" className="Vehicle"
filename="$dataS/scripts/vehicles/Vehicle.lua">
			<specialization name="baseMaterial" />
			<specialization name="tipOccluder" />
			<specialization name="foliageBending" />
			<specialization name="washable" />
			<specialization name="wearable" />
			<specialization name="dynamicallyLoadedParts" />
			<specialization name="animatedVehicle" />
			<specialization name="dashboard" />
			<specialization name="cylindered" />
			<specialization name="mountable" />
			<specialization name="ikChains" />
			<specialization name="wheels" />
			<specialization name="slopeCompensation" />
			<specialization name="speedRotatingParts" />
			<specialization name="enterable" />
			<specialization name="fillUnit" />
			<specialization name="motorized" />
			<specialization name="drivable" />
			<specialization name="aiVehicle" />
			<specialization name="aiImplement" />
			<specialization name="articulatedAxis" />
			<specialization name="lights" />
			<specialization name="attacherJoints" />
			<specialization name="powerTakeOffs" />
			<specialization name="suspensions" />
			<specialization name="connectionHoses" />
			<specialization name="honk" />
			<specialization name="wipers" />
			<specialization name="frontloaderAttacher" />
			<specialization name="bunkerSiloCompacter" />

Thanks to you and the whole team for the only mod that I concider
essential for FS19 play.
