### ISSUE TITLE
Coursplay & Twobar mod

### ISSUE THREAD

**Issue by neooblaster** [Courseplay/courseplay#3883]
Hi All,

I open a issue to warn you there is a very strange bug between Coursplay and mods standing for tow functionnality.

I try this two following mods :

http://www.modhub.us/farming-simulator-2019-mods/tow-hook-v2/
http://www.modhub.us/farming-simulator-2019-mods/4337-tow-bar-1-0/ + http://www.modhub.us/farming-simulator-2019-mods/4513-tajfun-egv-80-ahk-v1-0-0-0/

I activate only CP & Tow Hook + Tajfun EGV 80 AHK mods and the game become uncontrollable.

I aware this kind of bugs are absolutely not your priority but maybe have you an idea why that happens ?

I don't see something revelant in log which can explain the behavior.

Thank you for all you made for FS Community !

Kindly Regards,
Neoblaster

**Comment by Tensuko** [comment]
The Taifun you can get on ModHub is working fine with CP6, as I use it on my own.
The Towbar not Sure about it, I could try the chain I got... somewhere...
For what is the Hook ?

A logfile would be nice to see anyway, maybe can find something there.

**Comment by neooblaster** [comment]
Hello Tensuko,

The hook is to attach with the Tajfun to a tractor instead of log. You attach the hook on your tractor, and then you can attach the cable on the hook.
The tajfun also works (without hook).
The chain and the cord also seam to work.

This is only the towbar and the hook which break the game.
I have no log currently. I have to reproduce the bug to send the file.
But maybe you want to close the thread due to very specific case ?

Thanks for your answer.

Kindly regards,
Neoblaster

**Comment by Tensuko** [comment]
I keep it open, I would like to see the log if there is anything.
But when the Mod breaks the game and we don't see any specific Error, we can't do much about this.
Does the 3 Mods work when they are alone ?

**Comment by neooblaster** [comment]
Hi Tensuko,

Thank you for your support.
Mod works when used alone.
I succeeded to reproduce the error with the right error.
It's due to the hook implement : `attempt to call method 'getAttachedImplements' (a nil value)`

Please find below the TowHook.xml file (truncate)

````xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<vehicle type="pallet_tb">
    <annotation>Copyright (C) GIANTS Software GmbH, All Rights Reserved.</annotation>

    <storeData>
        <name>Tow Hook</name>
        <specs>
        <functions>
            <function>$l10n_function_liftertool</function>
        </functions>
            <combination>LIZARD 1300 XL</combination>
        </specs>
        <functions>
            <function>$l10n_function_lifterTool</function>
        </functions>
        <image>textures/icon.dds</image>
        <price>600</price>
        <lifetime>600</lifetime>
        <rotation>0</rotation>
        <brand>Exley</brand>
        <category>misc</category>
        <shopHeight>1</shopHeight>
        <vertexBufferMemoryUsage>59232</vertexBufferMemoryUsage>
        <indexBufferMemoryUsage>9060</indexBufferMemoryUsage>
        <textureMemoryUsage>5592496</textureMemoryUsage>
        <instanceVertexBufferMemoryUsage>0</instanceVertexBufferMemoryUsage>
        <instanceIndexBufferMemoryUsage>0</instanceIndexBufferMemoryUsage>
    </storeData>

    <base>
        <typeDesc>$l10n_typeDesc_lifterTool</typeDesc>
        <filename>TowHook.i3d</filename>
        <size width="2" length="2" />
        <components>
            <component centerOfMass="0 0.05 0" solverIterationCount="20" mass="50" />
        </components>
        <schemaOverlay attacherJointPosition="0 0">
            <default name="DEFAULT_IMPLEMENT"/>
            <selected name="DEFAULT_IMPLEMENT_SELECTED"/>
        </schemaOverlay>
    </base>
	
	
	<tensionBeltObject>
		<meshNodes>
			<meshNode node="visual"/>
		</meshNodes>
	</tensionBeltObject>

    <attachable>
        <inputAttacherJoints>
            <inputAttacherJoint node="trailerAttacherJoint" jointType="trailer" rootNode="Hook_main" attacherHeight="0.251" />
            <inputAttacherJoint node="trailerAttacherJoint" jointType="trailerLow" rootNode="Hook_main" attacherHeight="0.251" />
			<inputAttacherJoint node="trailerAttacherJoint" jointType="semitrailerHook" rootNode="Hook_main" attacherHeight="0.251" />
			<inputAttacherJoint node="trailerAttacherJoint1" jointType="skidSteer" rootNode="Hook_main"/>
        </inputAttacherJoints>
    </attachable>
	
</vehicle>
````

[log-from-loading-save-tajfun-hook-cp.txt](https://github.com/Courseplay/courseplay/files/3271652/log-from-loading-save-tajfun-hook-cp.txt)
[log-from-loading-save-tajfun-hook-only.txt](https://github.com/Courseplay/courseplay/files/3271653/log-from-loading-save-tajfun-hook-only.txt)

Kinldy regards,
Neoblaster

**Comment by Tensuko** [comment]
Sry for a late rply.
It is always helpful to have a full logfile.
Not sure what we can do about it tho, as the Modder needs to stay to GIANTS Standarts.

**Comment by pvaiko** [comment]
Sorry, this is very low priority.
