### ISSUE TITLE
Lkw hält im Mode 1 nicht an 

### ISSUE THREAD

**Issue by Tombarkemeyerbruns** [Courseplay/courseplay#3884]
bei mir hält der Lkw nicht wenn das  warten aktiviert ist im mode 1

**Comment by Tensuko** [comment]
Der LKW ?
Das Warten im Mode1 ?
Bitte beschreibe mal genauer, welcher LKW, was soll er tun und was macht er.

Und ein Logfile bitte anhängen mit Channel 1 und 2.

**Comment by Tombarkemeyerbruns** [comment]
Der Man lkw verkauft  Mischfutter und hält nicht an wenn man sagt das am letzten wegpunkthalten soll

**Comment by Tensuko** [comment]
MAN von GIANTS oder eine Mod, wenn Mod, welche.
Wie iat dein Kurs aufgebaut, dass er am letzten Wegpunkt oder Trigger halten soll ?

**Comment by Tombarkemeyerbruns** [comment]
der ist Standard

**Comment by Tombarkemeyerbruns** [comment]
ich hab in manuel losgeschickt also manuel gefühlt dann manuel  zum ersten wegpunkt gefahren und losgeschickt

**Comment by Tombarkemeyerbruns** [comment]
![fsScreen_2019_06_10_00_23_13](https://user-images.githubusercontent.com/50717293/59165094-877a6e80-8b16-11e9-94e9-330ff709e4a3.png)

**Comment by Tombarkemeyerbruns** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3270020/log.txt)

**Comment by Tensuko** [comment]
Er hält auch am Startpunkt nicht an...
Das wird zu einem Problem führen, wenn Mode3 mal wieder aktiv ist.
Ist ein Bug.

**Comment by Tensuko** [comment]
Könnte sein, dass dies gelöst ist, wie auch immer, aber neulich konnte ich den LKW mit Starten am ersten Wegpunkt einsetzen, daher mache ich das heir zu. Sollte sowas nochmal auftreten, bitte neues Issue aufmachen.
