### ISSUE TITLE
Unloading Combine pipe over crop, not over harvested area when course is generated.

### ISSUE THREAD

**Issue by 57IowaFarmer** [Courseplay/courseplay#3886]
Courseplay currently generates courses so that the unload pipe is positioned over the crop. If the courses were generated so that the pipe was over the harvested area, then the combine would not have to back up to unload.  In real life, farmers try to operate their combines in this manner.

**Comment by FS19-CP** [comment]
You have to generate the course in such a way as to accomplish that, the generator just does what you ask.

Pick the correct corner, and correct direction.

**Comment by corrado33** [comment]
I think this has more to do with the tractor running combi mode than the combine itself. If the combi tractor has pathfinding on, it'll do its best to stay out of the crop, so it will only attempt to unload on the non crop side (in theory). Unfortunately, it doesn't always end up that way in practice. Sometimes the combine gets full with the crop on the left side, and therefore must back up to let the tractor in. 

That said, tractors in combi mode don't actually destroy crops so.... eh, I tend not to care. 

Also, you can generate courses that start from the center of the field and work outwards in an counterclockwise manner, therefore keeping the pipe in the harvested area all the time.

**Comment by Tensuko** [comment]
@57IowaFarmer 
You got to start in the right corner and the choose the right direction for your Headland. Just as FS19-CP said.

@corrado33 I think he talks about general pipe outside the fruit, so Coursegeneration.
The new 'Headland' Modes are a good way too, just experiment with the settings to find a good way.

Closed.
