### ISSUE TITLE
Error: Running LUA method 'update' - MathUtil.lua(173) : attempt to perform arithmetic on local 'x' (a nil value) + Callstack

### ISSUE THREAD

**Issue by gazorange01** [Courseplay/courseplay#3888]
[log.txt](https://github.com/Courseplay/courseplay/files/3282218/log.txt)
after task is complete a dialog is shown (above map)
when this shortcut to vehicle is clicked, the game freezes and a hard boot is required

**Comment by Tensuko** [comment]
Error: Invalid mod name 'course-generator'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

Warning: Duplicate l10n entry 'function_farmHouse' in mod 'FS19_farmhousecaravan'. Ignoring this definition.

Error: Failed to open xml file 'C:/Users/gazor/Documents/My Games/FarmingSimulator2019/mods/img/modDesc.xml'.
Load mod: img
Error: Missing descVersion attribute in mod img

Error: Failed to open xml file 'C:/Users/gazor/Documents/My Games/FarmingSimulator2019/mods/sounds/modDesc.xml'.
Load mod: sounds
Error: Missing descVersion attribute in mod sounds
Load mod: stollToolbaleFork (Version: 1.0.0.0) (Hash: 4aa5706a822b46bfe65f002791f1a439)
Error: Failed to open xml file 'C:/Users/gazor/Documents/My Games/FarmingSimulator2019/mods/test/modDesc.xml'.
Load mod: test
Error: Missing descVersion attribute in mod test
Error: Failed to open xml file 'C:/Users/gazor/Documents/My Games/FarmingSimulator2019/mods/translations/modDesc.xml'.
Load mod: translations
Error: Missing descVersion attribute in mod translations

---
Maybe delete RealDirtColor becouse:
2019-06-12 14:20 Error: Vehicle type 'jdsts70' has unknown specialization 'realDirtColor'!
2019-06-12 14:20 Error: Vehicle type 'jdsts60' has unknown specialization 'realDirtColor'!

---
Clean up your Mod Folder and put only a clear CP Zip File in your Mods Folder.
Just like the Load mod: fs19_courseplay (Version: 6.01.00229) (Hash: e42193980aa9b29cf1d608fe59dfcb3e)
Or get the newest here: https://github.com/Courseplay/courseplay/releases
(I used to Rename them to FS19_Courseplay)

---
If your Error still happens: Discripe more about what Mode and Vehicle you used.

**Comment by gazorange01** [comment]
went through my mod folder and found it to be a mod conflict with Waiting Workers.

Thanks for the fast reply

**Comment by Tensuko** [comment]
So the Issue is solved now ?

**Comment by gazorange01** [comment]
in my circumstances yes, however i believe others have the mod with no errors?
