### ISSUE TITLE
Combine clicking noise while unloading

### ISSUE THREAD

**Issue by Rbk3** [Courseplay/courseplay#3890]
Sorry hit submit before I was done and can’t wdit title 

When any combine is set to stop to unload it starts making this weird clicking noise when it stops. I linked to a video of the issue. I am on the latest beta. 

https://youtu.be/_a4Hw5ckmVI

**Comment by Tensuko** [comment]
I need a full logfile pls.
Strange sound... Any Mod Combine you used there ? Or Vanilla one ?
https://github.com/Courseplay/courseplay/wiki

**Comment by aviator64** [comment]
I experience this too. It seems to happen with any piece of equipment when its Fuel Saver mode is activated and its engine shuts off. It does not generate a log entry.

**Comment by Rbk3** [comment]
Interesting. It is happening on any combine on my one save but I started a new game with just courseplay and it is fine.

What do you mean when you say fuel saver mode?

**Comment by aviator64** [comment]
This happens to me consistently, on every map and on new games as well as savegames.

In the CP "general driving settings" you will see "fuel save option". Try disabling that and see if you still have the issue. I found that if I disable it, the engine keeps running and there is no clicking sound.

**Comment by Rbk3** [comment]
Awesome thanks for the info!

**Comment by Tensuko** [comment]
I got it active and I am sure I have no sound in that situation, I will check that and if I find a reason for it...

**Comment by aviator64** [comment]
Could this have something to do with it?

2019-06-20 15:17 Warning (performance): Raw audio format C:/Users/Oliver/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/sounds/cpClickSound.wav.

**Comment by jala15** [comment]
It´s caused by automatic engine start and courseplay turning off engine when stopped (fuel save option I guess)
If you change game options to disable automatic engine start it won´t sound anymore, but not the best solution

**Comment by pvaiko** [comment]
Can someone post a log with debug channel 14?

**Comment by aviator64** [comment]
Here you go.. as always, as soon as the fuel saver activated, the strange noise started.

[log.txt](https://github.com/Courseplay/courseplay/files/3358997/log.txt)

**Comment by pvaiko** [comment]
@aviator64 ok, this happens when you enable the auto engine start, the Giants code will start the engine whenever you enter a vehicle.

Not sure how to fix this, there are two options:
1. do not stop the engine when auto engine start is enabled (even with fuel save on)
2. disable auto engine start when fuel save is on.
3. override the Giants code to not try to start the engine when CP is driving.

**Comment by aviator64** [comment]
OK, all of that makes sense. For what it's worth though, this didn't happen in FS17 and I always had auto engine start enabled.

**Comment by pvaiko** [comment]
@aviator64 yes, this changed in FS, now it wants to start the engine. I implemented option 1 as it is the easiest.

**Comment by pvaiko** [comment]
Reopen if it is still an issue with 236
