### ISSUE TITLE
mode1, fill only the first time

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#3891]
hey guys,
i tried to bring forage from the mixing station in the storage.
my drived in course works only one time - in the secound run, the trailer wont be filled, and the tractor drives empty alle the way.
when i fire and hire the helper it works also one time with filled
cp version: 6.01.00229.5 
course:
[courseStorage0066.xml.txt](https://github.com/Courseplay/courseplay/files/3284926/courseStorage0066.xml.txt)

and here a small video (2min) with the problem:
https://youtu.be/wXrZqPVUj4A
(it take a little time, is in upload)

lg
andreas

**Comment by andreasthu** [comment]
update:
it seems do get problems, whem it is a push-back-to-load course

it works perfekt by drive-throught:
this works, as example:
`        <slot fileName="courseStorage0065.xml" id="65" parent="8" isUsed="true" name="2b.FermSilo-Hayloft"/>`
![fsScreen_2019_06_13_11_52_15](https://user-images.githubusercontent.com/24860501/59424748-dd7c3a00-8dd4-11e9-841f-c8e19b7a8cdd.png)

the two following dont work, only 1x:
`        <slot fileName="courseStorage0066.xml" id="66" parent="8" isUsed="true" name="2b.FutterMix-Rootstorage"/>
        <slot fileName="courseStorage0067.xml" id="67" parent="8" isUsed="true" name="2b.Heutrockner-Hayloft"/>`
![fsScreen_2019_06_13_11_52_56](https://user-images.githubusercontent.com/24860501/59424824-fbe23580-8dd4-11e9-8586-605dc2d2709f.png)
![fsScreen_2019_06_13_11_53_35](https://user-images.githubusercontent.com/24860501/59424831-fe448f80-8dd4-11e9-9d91-47d7a3219589.png)

or whats getting wrong?

here i have a zip with savegame, cp-courses and map/needed mods
https://filehorst.de/d/czyvnrht

lg
andreas

**Comment by Tensuko** [comment]
We got a similar Situation here: #3884
I will have to make some more Vanilla Test with different course and and Vehicles...
Can you make a logfile with debugchannel 1 and 2 for the Courses with 2 runs, so we can see when it works and when it doesn't ?

**Comment by andreasthu** [comment]
bittschön log.txt mit debug 1+2,
[log.txt](https://github.com/Courseplay/courseplay/files/3286100/log.txt)
hab den kurs courseStorage0066.xml 4x abfahren lassen,
das erstemal aufgefüllt, die anderen drei mal durchgefahren

lg
andreas

**Comment by Tensuko** [comment]
Also... ich konnte es nicht reproduzieren, bei mir fährt der munter seine Runden.
Was mich bei deinen Screenshots irritiert, sind die ganzen Zeichen über den Kursen. Hast du alle Kreuzungspunkte sichtbar an ?
An sich sieht der Kurs auch nicht falsch aus, viel anders hätte ich den auch nicht gemacht.

Wenn es beim ersten mal geht, wo startest du den CP Fahrer ? Direkt am Silo oder ein paar WP davor ?
Es gab mal Probleme damit, wo genau der Start und Stop WP am Silo standen.

Ich bin mir auch gerade unsicher, was mit den anderen Triggern ist, durch die du fährst...
Ich bin weiter am probieren, kann aber dauern...

**Comment by Tensuko** [comment]
[logdebug2.txt](https://github.com/Courseplay/courseplay/files/3287876/logdebug2.txt)
Das schmeißt der debugchannel2 bei mir raus, mit ein paar Runden Hafer verkaufen.
Den ablauf mit Add und Remove Trigger vermisse ich in deinem Log, ich kann aber nicht erkennen warum das so ist.

**Comment by andreasthu** [comment]
Ja, habe alles an, startstrecke, mittelteil, ende und kreuzungspunkte.
Aber eigentlich nur beim testen u kurse einfahren.
Weil kreuzungspunkte, start u ende sind beim einfahren neuer kurse hilfreich.
Im spiel nur start u endstrecke.

Start ist wie am video ersichtlich, ein paar WP vor dem ende.
Aber ich achtete da nie drauf, eigentlich immr irgendwo an der strecke, der wo der grade an nächsten zum traktor ist.
Also ich fahre nicht bewusst erstmal zu einem bestimmten WP hin.

Ja, da sind einige trigger in der nähe, das rootstorage ist da aber das einzige das forage nimmt.

Sry, diese log ist mir ein spanisches buch, kanns zwar lesen und verstehe einzelne teile davon

Das letzte  wäre lustig, hab die fahrten auf unbegrenzt stehen, werde demnächst mal 5 o.ä. einstellen und testen. Wäre ein ungewöhnlicher fehler aber drauf m u ss man mal kommen.
Danke dir für diese idee und gebe dir dann bescheid.

Lg
Andreas

**Comment by andreasthu** [comment]
nope, keine besserung
habe mittlerweile v 6.01.0230,
3 durchläufe eingestellt,
wieder nur beim ersten mal beladen,
log:
[log.txt](https://github.com/Courseplay/courseplay/files/3288175/log.txt)

auch hört der Fahrer nach drei durchläufen nicht auf und fährt munter weiter.
letzte zeile vom cp-hud sieht in der mitte irgendwie überlagert aus
auch im video zu sehen
https://youtu.be/nS_GrwiYfnk
(lädt aber noch hoch, ca 2std noch)

lg
andreas

**Comment by Tensuko** [comment]
Ja komplett alles verstehen tu ich auch nicht in den logs, desshalb der Vergleich, was bei mir passiert.

Video ist nicht verfügbar.

Hast du nachdem du den Convoy rausgenommen hast, das nochmal probiert ?

Das durchfahren von anderen Triggern hat bei mir mal den Fehler ausgelöst, dass der Mode6 Fahrer nicht mehr richtig im Silo abgekippt hatte, was eigentlich immer ging.
Irgend einen Grund muss das haben, dass es bei dir nicht klappt, aber bei mir.
Ich lade mir heute mal dein Packet runter und schau mal ob ich das hinkrige, dass es klappt und warum.

WP skippen muss nichts heißen, das kann durch die Triggererkennung sein.

**Comment by andreasthu** [comment]
So, sorry, die zwei videos waren noch auf status "entwurf".
Hab sie nun auf "veröffentlichen" geändert.
Bin ein youtube-noob.
Habe jetzt heute abend zw 11 u halb 3 stundenlange versuche mit geringen koordinatenänderingen vor/zurück, wp löschen, neue winfügen,... gemacht, bin aber auf keinen grünen zweig gekommen
K.a. was das ist, das klappte in LS17 immer wunderbar.

Lg
Andreas

**Comment by andreasthu** [comment]
GESCHAFFT
ich habe zw dem vorletzten und dem letzten WP noch einen eingefügt.
[courseStorage0066.xml.txt](https://github.com/Courseplay/courseplay/files/3289428/courseStorage0066.xml.txt)

`    <waypoint60 speed="29" angle="12.12" pos="-71.59 66.00 -149.04"/>
    <waypoint61 speed="27" angle="2.48" pos="-71.04 66.00 -146.49"/>
    <waypoint62 speed="26" angle="-0.03" pos="-70.98 66.00 -144.99"/>
    <waypoint63 speed="20" angle="179.96" pos="-70.98 66.00 -143.22"/>
    <waypoint64 speed="17" angle="-179.99" rev="1" pos="-70.27 66.00 -153.24"/>
    <waypoint65 speed="17" angle="179.95" rev="1" pos="-70.97 66.00 -158.30"/>
    <waypoint66 speed="12" angle="0.00" rev="1" pos="-70.97 66.00 -163.50"/>
    <waypoint67 speed="12" angle="0.00" pos="-70.97 66.00 -162.50"/>
    <waypoint68 speed="12" angle="0.00" pos="-70.97 66.00 -161.50" crossing="1"/>
</course>
`
WP67 ist neu und genau mittig zw WP66 u 68
![fsScreen_2019_06_14_09_09_04](https://user-images.githubusercontent.com/24860501/59490348-baa95e80-8e84-11e9-9097-e95611b68ab9.jpg)

geh jetzt mal zum arzt und werd mir nachher das ganze noch mit dem Heutrockner ansehen.

lg
andreas

**Comment by Tensuko** [comment]
Das heist nach dem WP wo du beim aufnehmen von Rückwärts auf Vorwärts geschaltethast, hast du noch einen WP und dann Stop ? Das würde ja heißen, dass man zwischen rückwärts und stop mindestens einen WP braucht, oder der Abstand groß genug sein muss.

**Comment by andreasthu** [comment]
Ja genau.
Habe den wp67( den letzten) kopiert und darunter eingefügt, zeilennummer von 67 auf 68 geändert.
Dann beim wp67 die 3. Koordinate von -161.5 auf -162.5 geändert( mittig zw wp66 u 68) und das criossing weg.
K.a. wieso, aber nun läufts super

**Comment by Tensuko** [comment]
Scheint gelöst zu sein.
Ich mache hier zu...
