### ISSUE TITLE
lua callstack  Error: Running LUA method 'update' v 229 in mode 2

### ISSUE THREAD

**Issue by xXxBufu** [Courseplay/courseplay#3892]
When running courseplay in Mode 2 the game freezes after short time with lua callstack
[log.txt](https://github.com/Courseplay/courseplay/files/3284961/log.txt)

**Comment by Tensuko** [comment]
#3311 
Also you use V229_2
Get V229_5 from here and report back:
https://github.com/Courseplay/courseplay/releases

**Comment by xXxBufu** [comment]
I just tried with v230, the 'update' error is fixed.

**Comment by Tensuko** [comment]
Ok, closed.
