### ISSUE TITLE
v.230 mode 4 beet harvesters still not turning properly

### ISSUE THREAD

**Issue by aviator64** [Courseplay/courseplay#3894]
Using the standard in-game TerraDos 4_40 and Tiger 6
Mode 4 course generation on plain rectangular field
"turn on field" and "pathfinding" both disabled

When the harvesters reach the end of a row, they make several reversing maneuvers to attempt to line up with the next row. The Tiger eventually lines up and starts the new row; the TerraDos ends up turning in circles forever.

No log entries are generated.

I see that they always change to "turn steering" when CP is activated which makes them effectively articulated vehicles. What about allowing them to stay in "all wheel steering" mode?

**Comment by pvaiko** [comment]
See #3538 and #3062
