### ISSUE TITLE
Completly broken on original in game maps

### ISSUE THREAD

**Issue by GreaseMonkey57** [Courseplay/courseplay#3895]
The issue I am having is with using course play in any capacity on the base maps for fs19 it will not work at all. I have not modified the maps at all and even tried a new save with only course play and it still did not work. I also played with some of the debug tools and saw this don't know if this can be of any help.
![Screenshot_1](https://user-images.githubusercontent.com/51829926/59520833-d4ed3780-8e98-11e9-8d5d-83b066ec41c9.png)
 
![Screenshot_2](https://user-images.githubusercontent.com/51829926/59520914-08c85d00-8e99-11e9-8ee3-e7c8c692db21.png)

**Comment by GreaseMonkey57** [comment]
Forgot to mention it works fine on my moded maps

**Comment by Tensuko** [comment]
6.01.0001.dev ?
I don't know where the hell you got that cracked Version of CP from, but the ONLY Source you get a proper CP Version is here: https://github.com/Courseplay/courseplay/releases

Any more problems, can only help with a proper logfile: https://github.com/Courseplay/courseplay/wiki

The Debugchannels won't help at any point, they are just printing information into the logfile and we will tell you wich information we need.

**Comment by GreaseMonkey57** [comment]
alright so I updated to the new version and it works fine I got that old version from a mods site because I didn't honestly know this existed.  Thanks for your help and have a great day! :)
