### ISSUE TITLE
attempt to call method 'shouldRaiseImplements' (a nil value)

### ISSUE THREAD

**Issue by mnicklisch** [Courseplay/courseplay#3896]
Hi,
just encountered an error on DonDiego Map.
Had two tractors going around, one making silage bales and the other with two mowers attached to the front and a windrower on the back. Watched the second tractor driving his rounds, nearly finished the field. No User inputs and then suddenly the error occurred. Only had the modded NOVACAT mowers on the map, every other vehicle or implement was vanilla.

[log.txt](https://github.com/Courseplay/courseplay/files/3292373/log.txt)

**Comment by pvaiko** [comment]
That's weird. What mode you were running those tractors? Need a log with debug channels 12 and 14.

**Comment by mnicklisch** [comment]
Hey there, I had the tractors in fieldwork mode.
I tried to reproduce it, with debug channels 12 and 14. This time I got an error way earlier. The first tractor was already mowing the first field and I was just done setting up the course for the second tractor. Then the game kind of freezed, it ran but I couldn't make any inputs, like the last time with the other error. The error from above didn't appear in the log this time, but some other errors.

[log.txt](https://github.com/Courseplay/courseplay/files/3292846/log.txt)

**Comment by mnicklisch** [comment]
I tried it again, this time I got the second tractor to work, but a few moments later the error ocurred again.
I set up both courses with two headland passes and a smaller working width than courseplay suggested, because the mover has a smaller width than the windrower.
[log.txt](https://github.com/Courseplay/courseplay/files/3292858/log.txt)

**Comment by mnicklisch** [comment]
And I tried a third time =) This time I disabled the debug channels, because I wanted to see if there is any difference. I set up the course for the first tractor and didn't even start the driver and it crashed... something wrong here^^
[log.txt](https://github.com/Courseplay/courseplay/files/3292866/log.txt)

**Comment by mnicklisch** [comment]
The last days I was busy fixing my game because a new mod I downloaded made some problems, which I didn't know because I forgot about the new mod... It didn't support courseplay or autodrive and produced errors similar to #3877. The suggested fix fixed the problem of crashes, but I removed the mod. After that, suddenly the mod realistic steering had problems and didn't let me load any map, not even the vanilla maps, although I was playing with this mod for months now without any problems... I removed the mod and could at least load a map again.

**Comment by mnicklisch** [comment]
I think I'm just an idiot, I think the errors from the last few tries were no errors but just a dying battery in my controller....
I will try to test again this evening.

**Comment by mnicklisch** [comment]
Alright, I've tried again and this time everything worked. Maybe it was a problem with another mod I already removed. I've attached the log anyway. There is an error at the end of the log, but it seems to be related to the map. So I think this issue can be closed for now.
[log.txt](https://github.com/Courseplay/courseplay/files/3293389/log.txt)
