### ISSUE TITLE
Refill course bug

### ISSUE THREAD

**Issue by aviator64** [Courseplay/courseplay#3897]
Field work course
Stock Amazone Condor (holds seeds and fertilizer)

On the refill course - if the vehicle passes by a lime station before the solid fertilizer tank, the cover opens and although it does not fill with lime, it also does not fill with fertilizer. It will then fill with seed, but the cover never closes as it returns to the field.

No log entry is generated.

If the refill course reaches the fertilizer tank before the lime tank, everything works correctly. So, there is an easy workaround but wanted to make you aware.

**Comment by Tensuko** [comment]
Even there is no logentry, a logfile helps in several ways, like wich cp version you use.
Logfile with debugchannel 1 and 2 would be helpful.

**Comment by aviator64** [comment]
I ran the course again with the debug channels activated but was unable to duplicate the issue. So, not sure what happened the previous time. If it happens again I will post a log.

**Comment by shadow250** [comment]
i have a similar issue. only after refilling the tractor does not resume the course after filling. it just sits there with the refill numbers flickering. i have to stop it and start it using current waypoint.

**Comment by aviator64** [comment]
> i have a similar issue. only after refilling the tractor does not resume the course after filling. it just sits there with the refill numbers flickering. i have to stop it and start it using current waypoint.

That is interesting. I have never experienced that one. Is this a mod tractor and/or implement?. Does it happen with all your tractors and implements? Or is it a mod filling station from someone other than Giants?

**Comment by shadow250** [comment]
it is not a mod tractor or implement although i do have the extended capacity and the 18m upgrades on the fertilizer. the tractor is the medium orange and white one only goes 15 mile km hr 150 hp (i think i dont know the name without looking) the filling station is from giants modhub. i havent tried other tractors cuz my farmer is broke. his house is the 2 porch chairs i found somewhere. i could'nt find that tent mod.

**Comment by aviator64** [comment]
Are you filling fertilizer or lime?
I have to wonder if your filling stations are too close together and their triggers are overlapping.

**Comment by shadow250** [comment]
im filling lime. i will try spacing them farther apart and see what happens.

**Comment by shadow250** [comment]
the above solution fixed it.

**Comment by Tensuko** [comment]
I close this one as it seems solved.
If you got more about that Issue, just let me know pls :)

Closed.
