### ISSUE TITLE
Error: Running LUA method 'update' - turn.lua:654: attempt to call method 'shouldRaiseImplements' (a nil value)

### ISSUE THREAD

**Issue by Krahazik** [Courseplay/courseplay#3899]
Coursplay version 6.01.00230
Game Log (gist): https://gist.github.com/Krahazik/c130cf259594a6cefbba2db1ed1b15c9
Tractor: Fendit Favorit 515c (Vanilla)
Gather Wagon: Strautmann Zelon CFS 2501 DO (Vanilla)
Other mods were present.

I had just finished windrowing a field of hay with a loaded course.
I started the same course with a gather wagon attached, head lowered and started.
Hud was hidden using the mini-hud.
Shortly after courseplay started the run, my camera became detached from the vehicle, and the vehicle kept going in a strait line as if the accelerator was stuck and no one was driving. Nolonger following the course.
I had opened the map and visited my cow far to exit the vehicle. The ingame help window still shows the controles for being in the tractor.
The game is nolonger accepting any keyboard inputs related to the game, and as such, I am not able to bring up the main hud to stop the driver.

**Comment by Tensuko** [comment]
Could be Mod Conflic as in #3896

One Mod creates an Error:
2019-06-15 08:19 Error: LogsWinch got a colliding action: LOGSWINCH_RELEASE_PLAYER

And not sure, but RealDirt loves to make Trouble with some other Mods combined:
2019-06-15 08:38 Error: Vehicle type 'autoEgg' has unknown specialization 'realDirtColor'!

**Comment by pvaiko** [comment]
I think this can only happen if you start a fieldwork course in mode 5. I'll provide a fix anyway...

**Comment by Krahazik** [comment]
I'll try loading a new game with just coursplay active and see if I can get it to do it again.

**Comment by Krahazik** [comment]
I was in mode 6 Field Work when the bug occured for me.
