### ISSUE TITLE
AutoDrive option not show

### ISSUE THREAD

**Issue by piropiro24** [Courseplay/courseplay#3900]
Hi, AutoDrive option not show, maybe because is a language problem.
Do you need any log?
Thanks

![image](https://user-images.githubusercontent.com/49072277/59562511-ec115e00-902d-11e9-81fe-d587cd4c365d.png)

**Comment by Tensuko** [comment]
@Stephan-S Anything from your side ?

**Comment by pvaiko** [comment]
You must have at least 1.0.2.9 version of AutoDrive for this to work.

**Comment by piropiro24** [comment]
Ok, I've check the Modhub but there the version still 1.0.1.9. I've found it in github. Thanks!

**Comment by Admilson** [comment]
last version not show

**Comment by Stephan-S** [comment]
Hey, I already commented in the other issue but just for clarity, here once again.

The current check of CP to see if AutoDrive is installed (in the correct version), seems to be executed in the first onUpdate() run or at least before the AutoDrive mod had time to run it's initialization and expose the spec_autodrive. A delayed or repeated check would be needed here on CP side.

This changes from vehicle to vehicle on each start of the game as it depends on which mod (CP or AD) is run first on the vehicle.
