### ISSUE TITLE
combine to trailer or trailer to combine ?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#3902]
Hey guys,
i have now CP 6.01.0232 and AD 1.0.3.3
i harvest Field23 on Felsbrunn, with a CP course, and want use AD to drive wheat away to the Getreidemühle.
when i use the new option Autodrive fill/refill in the hud, the combine drives to the trailer.
i find is better, the trailer get to the combine.
who can i change this?

lg
andreas

**Comment by pvaiko** [comment]
Yeah, I should have disabled it for the combine. That option is will use AutoDrive for fieldwork unload/refill courses only, for example to unload a forage wagon or refill a sowing machine. Does not make any sense for a combine.

**Comment by Tensuko** [comment]
That actually works ? I mean the Combine drives to the Trailer and unloads into Trailer ?
That would be our oly Mode7, at least kind of.

**Comment by andreasthu** [comment]
No. That does not work.
The combine tries to drive to the "field23" point.
But on this point waits the tractor/trailer, so the combine crashes in the tractor.

I think it was my mistake, when i turn this off, the tractor come to the combine.
This option is senseless by combines.

I think your intention was to drive fieldworkcourses sprayer lime fertilizer, manure spreader and so things to work the field with CP and then refill with AD?
Is this work also with loading wagons, load straw at field with CP, AD drive to the hayloft unloading, drive to field, and CP beginns the loading again?
Lg
Andreas

**Comment by Tensuko** [comment]
Ok, then got to disable that option for Combine.

And yes it was made to refill the CP Seeder, by letting AD drive the refill course.
But it works ok, as my Seeder reaches the point, I got to press R to get the seed, then press continue in AD. When reached the AD Point CP will take over again (still need to figure out a bit how AD works...)

**Comment by jobyrns72** [comment]
Since I’m all about mode 7 have you already disabled that combine auto drive option?

**Comment by Tensuko** [comment]
Not sure about the AD implemention Stuff, but Combine Selfunload is an Option now under Advanced Settings.
For the AD Stuff no Idea what is the Status.
Make new Issue pls if have any AD/CP Conflict.
Closed.
