### ISSUE TITLE
Turn on Field doesn't seem for fieldwork v6.01.00229

### ISSUE THREAD

**Issue by artcwolf** [Courseplay/courseplay#3905]
I've noticed over the last few days a lot of slipping.  So i started watching and my tractors are no longer backing up and turning on the field as they once did.  I have both pathfinding and turn on field set to active.  While it doesn't go drive off the field in an uncontrolled manner, it does pose an issue with fields that have ditches and trees.  I've set a headland and it does help a bit to keep it out of the ditches.  But it does cause crop damage on other fields if i don't use the headlands, and the field next door is close.  I've tested with in game tractors and seeders, and mods with the same results.

**Comment by pvaiko** [comment]
First of all, try with the latest version which is 232. 

If you still have a problem post a log with debug channels 12 and 14.

**Comment by pvaiko** [comment]
Also, a little more description of what exactly is happening would be nice as I can't figure out if they actually making a turn or not and where's the slipping going on.

**Comment by artcwolf** [comment]
i apologize i sometimes ramble trying to make sense. Just tested with the 232 version same issue. 

Using the seeding option(got terms mixed up)  I would generate a course without a heardland.  set the turn on field to active, and pathfinding to active.  I would start the driver.  It reaches the end of the straight line and goes off the field to turn around instead of the backing up and turning.  Same with the headland generated in a course.

 I did a bit more testing to see if it might have been a mod so i used an in game Cat 875E to pull the Great Plains YP-2425A planter, instead of the mods for them that i have started using.  I think those two items are the issue.

I tested with a JD8750 and a condor and the turn on field worked properly, by backing up and turning.  
I tested a mod bigbud and mod plow using the field work option and the turn on field worked.

hooked the JD up to the YP-2454 it did not turn on the field.
Hooking the cat 875E to the condor it did not turn on the field.

I hope that made more sense.

This is the game log, i'm not sure how to get the log file you are requesting.

[log.txt](https://github.com/Courseplay/courseplay/files/3294832/log.txt)

**Comment by Tensuko** [comment]
We need a logfile with debugchannel 12 and 14 active while the Tracktor is running.
Just go into the CP HUD Settings and turn them on, then start the Course with the Error.
After finish it (or he crashed into someting), you can stop the Tracktor and exit the game, then you got the Logfile with the Debugchannel information we need.

**Comment by artcwolf** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3296163/log.txt)
I can get a bigger log this evening when i get home from work if you need.

**Comment by pvaiko** [comment]
That sowing machine (GreatPlains YP2425A By Stevie) is a mod, correct? Is it on modhub?

**Comment by artcwolf** [comment]
it is a mod yes, but not on mod hub.  I tested it with the in game one and had the same issue.  I'll take the mod out completely and test it again and get the log for the in game sowing machine.  I did a quick run this morning before work. I'll get you a better log file tonight with more info.  Thank you for your help and patience.

**Comment by artcwolf** [comment]
here is a bigger log using only the in game tools.  Pulling the TempoL with 3 tractors it works (well the cat doesn't back well) and then the yp-2425 with the same 3 tractors.  all 3 fail to turn on the field.
[log.txt](https://github.com/Courseplay/courseplay/files/3298755/log.txt)

**Comment by artcwolf** [comment]
noticed it was doing it last night with the Cultiplow Platinum 8m  so i cleaned out every mod but the money mod from modhub here is the log with just in game items no mods 
[log.txt](https://github.com/Courseplay/courseplay/files/3316816/log.txt)

**Comment by artcwolf** [comment]
Test both the great plains planter and the cultiplow platinum 8m  on a field with no mods engaged just stock game items and i still had the issue :(  i'm using v238.1

[log.txt](https://github.com/Courseplay/courseplay/files/3412767/log.txt)

**Comment by pops64** [comment]
The problem I suspect is line 339 in turn. As I noticed this was occurring on 3 point turns and line 341 is the if statement to select either FWD or REV 3 point turns. And from all the tools listed it seems to be the 3 point turns causing issues. ATM I am trying to replace 339 with 

`local neededSpace = abs(turnInfo.targetDeltaZ) + abs(turnInfo.zOffset) + 1 + turnInfo.centerHeight + (turnInfo.reverseWPChangeDistance * 1.5);`

Will report back on testing

**Comment by pvaiko** [comment]
The reason these tools can't turn on field is that both have problems reversing so they have reversing disabled in Courseplay.
