### ISSUE TITLE
Kombinierter Kurs mit Haltepunkt

### ISSUE THREAD

**Issue by stueja** [Courseplay/courseplay#3906]
Ich habe einen Feldkurs zum Einsammeln von Gras und einen Abfahrkurs.
Der Abfahrkurs enthält einen Haltepunkt ("P"), an dem der Abfahrer warten soll.
Der Abfahrer sammelt Gras, beginnt den Abfahrkurs und fährt allerdings über den Haltepunkt hinaus, ohne zu parken/halten/pausieren. 
Wenn ich den Abfahrer dann entlasse, um manuell zu entladen und danach den Abfahrer "ab nächstem passenden Wegpunkt" einstelle, dann fährt der den Abfahrkurs zurück zum Feld. Auf dem Feld allerdings beginnt er die Arbeit beim ersten Wegpunkt, nicht an dem Punkt, an dem er die vorige Runde beendet hat.
[log.txt](https://github.com/Courseplay/courseplay/files/3296451/log.txt)
[savegame1.zip](https://github.com/Courseplay/courseplay/files/3296452/savegame1.zip)

**Comment by Tensuko** [comment]
Getestet mit V294.
Bug.

**Comment by Tensuko** [comment]
Getestet mit 02.00040, Bug noch vorhanden.

**Comment by Tensuko** [comment]
Sollte gar nicht nötig sein.
Könnte aber auch klappen...
Sind eh dabei was zu tun, erst mal zu hier.
