### ISSUE TITLE
CP and Autodrive

### ISSUE THREAD

**Issue by Bobster82** [Courseplay/courseplay#3907]
Hello guys,

How do u use courseplay and autodrive to work together?

I have a combine using courseplay for fieldwork.
I have a autodrive truck waiting on his field unload point..

If I use autodrive to unload the combine, it takes ages to get to it... If I have a courseplay route, then unloading goes a lot faster...
But here is the point: I dont want to creat courses for all fields to unload. I want autodrive to drive the road and courseplay to just unload the combine...
How do I ever set this up? can't find any info on it here and on youtube :P 

Thanks for all the work u guys do together.

**Comment by Tensuko** [comment]
Actually CP doesn't unload Combines yet.
What happens is: CP tells AD, when Combine is rdy to unload. (If I am not mistaken).

Check and Discuss things here pls: #3820

**Comment by Bobster82** [comment]
Thanks, will continue there
