### ISSUE TITLE
Mode 2 has an inconsistent operation when emptying a harvester

### ISSUE THREAD

**Issue by hackselgut** [Courseplay/courseplay#3910]
When i have a vehicle on mode 2 to empty a harvester about 3 or 4 times out of 10 the vehicle will collide with the harvester, the vehicle will cross in front of the harvester, instead of waiting for the harvester to drive on, then have the vehicle come in behind the harvester, then get it`s order to proceed to go to unload location   Bob.

**Comment by hackselgut** [comment]
Pictures of issue,  Bob
<img width="960" alt="fsScreen_2019_05_26_16_51_18" src="https://user-images.githubusercontent.com/10256656/59709165-2288dd80-91d4-11e9-8c6b-b101eb5a14ee.png">
![fsScreen_2019_06_18_01_26_30](https://user-images.githubusercontent.com/10256656/59709167-2288dd80-91d4-11e9-8c3e-943535079d58.png)
[log.txt](https://github.com/Courseplay/courseplay/files/3302890/log.txt)

**Comment by iljarogoff** [comment]
This happens when the vehicle is at 100% filled. Try to drive it off before it reaches 100%

**Comment by Tensuko** [comment]
#3311 
Closed.
