### ISSUE TITLE
Mode 6 lifts before end of row when using 2 tractors

### ISSUE THREAD

**Issue by aviator64** [Courseplay/courseplay#3911]
With stock tractor and planter:
When using just one tractor, it always works to the end of the row as it should.
When I set up the course for two tractors (same equipment), the tractor making the narrower turn at the end of a row lifts the implement too soon and leaves a small un-worked patch.
The tractor making the wider turn does not do this.
Nothing in the log (using .233). Which debug channels do you need?

![fsScreen_2019_06_18_20_40_12](https://user-images.githubusercontent.com/19857526/59714577-e4a6ac00-9209-11e9-9188-8a42b9566005.png)

**Comment by pvaiko** [comment]
Try with 234.

**Comment by aviator64** [comment]
That fixed it, thanks!
