### ISSUE TITLE
Finetuning: Bredal 165 Dünger/Kalkstreuer

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#3912]
![fsScreen_2019_06_19_15_31_22](https://user-images.githubusercontent.com/21023840/59770167-d5763b80-92a7-11e9-8895-3a1c42c9bdec.png)

**Comment by iljarogoff** [comment]
Ähnliches beim BigX1180 
![fsScreen_2019_06_20_12_06_19](https://user-images.githubusercontent.com/21023840/59842799-8c7dc000-9357-11e9-985d-d816cf04e04f.png)

**Comment by Strawberry93** [comment]
Ihr hattet das schon behoben gehabt zumindest bei dem Kalkstreuer in dem ihr den Triggerpunkt vom Feldende mit dem Triggerpunkt Feldanfang zusammengeführt habt. Aber als ihr eine neue Version habt ihr das irgendwie wieder entfernt xD

Zu dem andern gehe ich bei sowas 1 Meter herunter mit der Arbeitsbreite bis man das irgendwann mal eingestellt hat. Ich finde das jetzt nicht so schlimm

**Comment by pvaiko** [comment]
@Strawberry93 ich weiss, und ich habe auch ein Fix dafür, geniesse aber gerade meinen wohlverdienten Urlaub und wollte nichts pushen weil momentan Segeln wichtiger ist als eventuelle Fehler in CP zu beheben :)

Diese Sprayer sind übrigens sehr kniffig weil sie mehrere Workareas haben (abhängig von Material auch)  die nicht rechteckig sind. Ich habe das Handling am Reihenende/anfang komplett umgebaut damit CP die Entfernung ganz genau weisst und nicht nur schätzt.

**Comment by Strawberry93** [comment]
Das habe ich gesehen da steht immer immer Starz und end jetzt. Nur da gibt es ein Problem auf der Felsbrunn wo ihr nicht mal was für könnt. Die Felder haben da so etwas schlimme Ränder.

Wenn sich das Spiel um die Felder kümmert dann nehmen sie die Ränder so wie CP das auch sieht. Fährt man aber das Feld selber sieht man, dass das Feld eigentlich größer ist. Da kann ich als Beispiel Feld 19 geben.

**Comment by iljarogoff** [comment]
> @Strawberry93 ich weiss, und ich habe auch ein Fix dafür, geniesse aber gerade meinen wohlverdienten Urlaub und wollte nichts pushen weil momentan Segeln wichtiger ist als eventuelle Fehler in CP zu beheben :)

Hab mir schon gedacht dass ihr Urlaub macht, weils keine Updates gibt :) Viel Spass beim Segeln und geniesse die Zeit!

**Comment by Strawberry93** [comment]
Jeder hat mal Urlaub Verdient. Ist auch super Wetter :D Auch zum Segeln :D

**Comment by XPiRiJenZ** [comment]
@pvaiko  lass es dir gut gehen 👍 :)

**Comment by pvaiko** [comment]
Reopen if not fixed by 237 or higher.
