### ISSUE TITLE
Warning vom Patch 1.4

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#3913]
Hallo Coursepaly Team.

Seit jetzt Patch 1.4 draussen ist kommen in der log immer diese warnings wen CP aktiv ist:

WARNING: performing emergency garbage collection pass - memory went from 82728 KB to 155445 KB in less than one frame

INFO: usage is now 129539 KB; full GC took 132.088800ms

MFG Mannie313

**Comment by Alphaone1709** [comment]
Du weißt aber schon das warnings in der log nicht spielbehindert sind ? und ich habe komischerweise diese einträge nicht in der log. würde mal auf einen anderen mod tippen

**Comment by pvaiko** [comment]
Ich glaube die kommen wenn CP die Kurse lädt, und wenn die viele Wegpunkte haben brauchen die auch viel Speicher und da wird der Lua GC angestossen, sieht harmlos aus.
