### ISSUE TITLE
not working HUD

### ISSUE THREAD

**Issue by qwert779** [Courseplay/courseplay#3914]
I cant open the hub. I tried everything.

**Comment by Tensuko** [comment]
I don't think you tried everything to open the HUD.
We need a logfile and just to make clear:
Reset your keybindings, save them, get into a Tracktor, right mouse click to open the HUD.

https://github.com/Courseplay/courseplay/wiki

**Comment by shadow250** [comment]
also try shift and delete if it was changed.

**Comment by Tensuko** [comment]
Closed couse didn't provide the needed informations.
Pls note, that not all Mods are based on GIANTS Standart, wich make some Vehicles unable to use CP, like the Claas Axion 900 from ModHub.
