### ISSUE TITLE
some base game vehicles not defined with aiCollisionTrigger

### ISSUE THREAD

**Issue by Axel32019** [Courseplay/courseplay#3916]
Hello,
While operating 1 terraDosT4_40 and 1 Tractor with trailer with CP on a field I got the impression they crash together more often then other harvester/tractor combinations.
The used vehicles are no mods, but only the included ones in the basis game!
So I investigated the collision of them and it looks like this:
![NOK](https://user-images.githubusercontent.com/52026009/59825463-5ed34f80-9334-11e9-87b1-ac6bbdfa9e58.png)
[log_NOK.txt](https://github.com/Courseplay/courseplay/files/3309146/log_NOK.txt)

The log contains the message "## Courseplay: Terra Dos T4-40: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!". So I looked for the reason of it and found that Terra Dos is not having "aiCollisionTrigger" in its XML. I did a local modification around the code of "i3dMappings.aiCollisionTrigger" in base.lua and TrafficCollision.lua and now it looks like this:
![OK](https://user-images.githubusercontent.com/52026009/59825721-1700f800-9335-11e9-80db-3b2effd4afb8.png)
[log_OK.txt](https://github.com/Courseplay/courseplay/files/3309054/log_OK.txt)
Now the log does not contain the message "## Courseplay: Terra Dos T4-40: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!". 
A test in the game gave a better collision detection of this vehicle combination 👍 
But further investigation regarding the collision definitions of the base game vehicles show that following vehicles do not use the naming "aiCollisionTrigger" as collisionTrigger:

trafficCollisionTrigger - terraDosT4_40.xml, poettingerTop462.xml, buffalo.xml, fox11.xml
collisionTrigger - T5.xml
aiTrafficTrigger - estrela32.xml
aiTrafficCollisionTrigger - GL860.xml

The most strange one is ponsseScorpion.xml without ai - section in the XML, but trafficCollisionTrigger defined in i3dMappings.

Further hint: The code in base.lua around "i3dMappings.aiCollisionTrigger" is using some for - loops, but in TrafficCollision.lua they are not in. From my understanding the functionality at the end should be the same , right?

Wenn gewünscht können wir natürlich auch auf Deutsch fortsetzen...
Gruß
Axel32019

**Comment by Tensuko** [comment]
I also know, that one or even some of the smal Tracktors have the same Issue.
Found them out but doing a test Circle for Mode1 and added more and more differen Tracktors.
While some stop for the others, some simply crash into them and then I saw Issue.

From my point of view, its a GIANTS Problem, as we can't modifie there vehicles.

**Comment by Tensuko** [comment]
Fresh bought:
![fsScreen_2019_06_27_18_49_44](https://user-images.githubusercontent.com/27344744/60284677-75694000-990c-11e9-920b-d554eb5828d4.png)
CP in use:
![fsScreen_2019_06_27_18_50_11](https://user-images.githubusercontent.com/27344744/60284682-7bf7b780-990c-11e9-9afa-6175987ca48b.png)
CP stopped:
![fsScreen_2019_06_27_18_50_18](https://user-images.githubusercontent.com/27344744/60284688-80bc6b80-990c-11e9-8c17-dd41d40a0207.png)

Somehow it doesn't get back to normal.
Did you try out your part of the Code ?
Or do you got to modifie the Vehicles itself ?

**Comment by Axel32019** [comment]
I guess your questions are addressed to me - sorry for the delay I was busy with some more analysis and testing...

From my point of view this issue is having more than one topic - so I leave it to you to split into more issues or follow up all in this one.

1. mode topic
CP is using 2 colli handlings for the different modes. One is for the AIDriver and one for the other.
This makes it difficult to handle it correct when changing between the modes, activating / deactivating and so on
A proper solution for the future would be to change all modes to AIDriver...

2. colli detection
Currently the activation of the colli boxes is implemented at different places, also due to 1.
This leads to not having a consistent handling and detection. In fact in Mode2 the detection is not working - see testing section below

3. AIDriver detection
I have still included my code I mentioned in #3924. This solves the issue of the snake boxes, but only for AIDriver colli!

4. LUA error - missing function
During my tests I catched a LUA error, which stopped the control of all vehicles. So drove ahead and I had no possibility to stop them :-(
I guess this is an covered issue due to 2.
The missing function call to "courseplay:setPathVehiclesSpeed(self,dt)" leads to this. 
Where / when this function got lost???

5. your last question
I do not want to modify vehicles, as with the next vehicle / an other user of CP will not have the changes, but the issues!

Workaround:
Beside the already mentioned code I changed the creation / deletion of the colli snake to start_stop.lua.
So at the start the colli will be created depending on the drive mode: AIDriver or legacy CP collision
At the end it will be deleted.
This I am testing now on my real game...

Testing
To see most of the issues related to the topic I suggest the following setup:
- use 2 diffent tractors each with a trailer to get diffent modes available for testing
- have a CP course with more than 20..30 waypoints
- the course should have a slide curve - to see / or not the snake is following / or not
- activate the collision view (as done in the pictures above)
- setup the first tractor on the course with slow speed (~30 kmh) and the second with full speed (>50 kmh) to see them collide on the course
- drive the course in diffent modes, i.e. Mode2 and Mode5

**Comment by sdl112** [comment]
Any update here? This issue makes it almost impossible to use CP with more than one vehicle on the same course or even crossing courses.

**Comment by Axel32019** [comment]
Well, I am working on it...
@dev-team: Are you in general interessted to get the changes?

What I have changed / fixed:
- Collision boxes are setup and available in the different modes, i.e. mode2, AIDriver
- clean up the implementation of traffic collision in different files, locations, i.e. moved the legacy code to traffic.lua
- figured out not needed / used variables, code etc.
- implementation of a collision detection when driving on a field, the current function uses the waypoints of the course which point in complete wrong direction(s)
- Up to now I did not check TrafficCollision.lua to have the improved traffic collision detection as well in modes based on AIDriver
- found setPathVehiclesSpeed(..) in an older version, but it works
- modify drive() to avoid hitting multiple tractor's for the same harvester

And something more...
The workaround(s) for the initial issue will take more time to collect all the definitions used by GIANTS in their vehicles, tools...

As I am new here, how do I pass the changes to you? Is it via the "Pull requests" ?

**Comment by pvaiko** [comment]
@Axel32019 thanks for taking the time to fix CP, we are absolutely interested in fixes and improvements as we have some issues with developer's availability and motivation... 

However, I think before you making extensive changes it would probably make sense to contact me directly (github@vaiko.us) to avoid spending time on something that does not align with our future plans. For example, not sure what you changed in drive.lua, but drive.lua is practically dead, the only reason it is there is that the mode2.lua refactoring isn't finished yet.

**Comment by pvaiko** [comment]
Oh, and yes, the way to pass changes to CP is a pull request.

**Comment by Axel32019** [comment]
@sdl112 , @andrenrei Bitte mal testen: #3975 Das hilft allen weiter wenn wir uns hier beteiligen...

**Comment by sdl112** [comment]
Gerne, wie binde ich das ein?

**Comment by pvaiko** [comment]
Ich glaube du musst CP von Axel's Repo runterladen.

**Comment by sdl112** [comment]
Habs schon hingekriegt, bin gerade am testen. Sieht soweit gut aus bisher. Habe eine LUA fehler, gehe allerdings davon aus dass der modabhängig ist. Ich teste das gerade.

**Comment by andrenrei** [comment]
sry das ich mich so spät erst zu wort melde habe aus beruflichen gründen immoment kaum zeit zum testen aber wen mir was auffällt dan werde ich mich aber melden ...........

**Comment by Tensuko** [comment]
Bisher scheint alles gut zu funktionieren.
Sollten noch Probleme auftauchen, die mit der Kollision zusammen hängen, bitte ein neues Issue aufmachen mit Beschreibung und ein Screenshot mit F5 an (siehe ersten Bilder in diesem Issue).
Closed.
