### ISSUE TITLE
Courseplay unable to start

### ISSUE THREAD

**Issue by theodorejames** [Courseplay/courseplay#3917]
Hello,

Tried downloading courseplay from github and followed Farmer Klien's tutorial video to install it. Attempted his process several times and was unable to see courseplay show up in my selected mods nor did the first time setup appear in game.

Later tried downloading the file from: 
<del>farmingsimulator19mods.com/courseplay-v6-01-00037-fs19</del>

Followed their install instructions and this did not work either.

I feel like I must be doing something wrong but I am unsure what that might be. Any assistance would be appreciated as I really want to try courseplay out.

**Comment by RUGhost** [comment]
Download from here https://github.com/Courseplay/courseplay/releases
And move the downloaded file to mod folder

**Comment by Tensuko** [comment]
I would suggest you to not download any mods from thise 'X-Simulator-Y.com Sides...
V00037 is ages ago.
As RUGhost write, get the correct and newest Version from the GitHub Link.
Closed.
