### ISSUE TITLE
Combine Unload Issue

### ISSUE THREAD

**Issue by CluelessUKGamer** [Courseplay/courseplay#3922]
Hi All

When the combine and the unloading wagon are heading towards each other, (After the combine has requested a unload) the loading wagon will always attempt to cut across the combine and cause a crash.  It appears to favor the right side of the combine when the pipe is on the left.

When the loading wagon comes from behind, there is no issue.

I am running version 6.0100234
Stock equipment.  In this case the T560 combine, with the T9 Tractor

**Comment by Tensuko** [comment]
#3311 
Closed.
