### ISSUE TITLE
Abfahrer Kolidiren beim beladen

### ISSUE THREAD

**Issue by andrenrei** [Courseplay/courseplay#3924]
Hallo habe da ein Problem bez. eine frag wen ich 2 oder mehr Abfahrer auf dem selben cours starte egal ob zum abtanken und abfahren oder um es verkaufen zu fahren und es am silo beladen werden soll schieben die abfahrer den abfahrer der gerade beladen wird am silo weg und beim abtanken vom drecher passirt das selbe am warte punkt des abfahre courses ich kenne das aus ls17 so das wen man mehrere abfahrer hat sie alle hintereinander warten.

**Comment by Tensuko** [comment]
Das hat etwas damit zu tun:
#3916
Ich bin mir nicht sicher, ob das von seitens GIANTS ein Problem der Fahrzeuge ist, oder ob wir da etwas machen müssen. Werde ich aber in einer nächsten Teambesprechung mal durchsprechen mit den Devs.

**Comment by omegaMV6** [comment]
@andrenrei, ich denke mal das Du alles über Mode 2 regeln willst, also Drescher abtanken und abfahren. Dieser Mode 2 ist aber noch WIP.
Bei Beladung am ersten Startpunkt, also Mode 1 hatte ich diese Probleme noch nicht. Vielleicht beim nächsten Mal die Einstellungen nochmal überprüfen.

Gruß
omegaMV6

**Comment by andrenrei** [comment]
@omegaMV6 ja wie du schon sagtest habe eben gerade die aktuellste version raufgespielt sprich xxx34 seit dem geht es im modus 1 und im modus 2 drecher abtanken und abfahren werde ich erst morgen sehen da ich jetzt meine riesen felder erst mal ein sähen muss aber danke fpr die schnelle antwort

**Comment by sdl112** [comment]
Hänge mich hier mal dran, habe seit dem letzten Update  xxx234 das selbe problem. Sowohl in M1 als auch M2. Selbst auf Verbindungskursen ballern die sich beim abbiegen munter gegenseitig über den Haufen. Scheint als ob aktuell gar keine Kollsionskontrolle in CP funktioniert. Da es bei AD Kursen klappt, gehe ich hier von einem CP problem aus.

**Comment by Tensuko** [comment]
Wir schauen uns das an, aber Grundsätzlich könnte ihr mal mit F5 die Kollisionserkennung von den Fahrzeugen anschauen, wie in #3916

**Comment by omegaMV6** [comment]
@Tensuko 
Hallo, ich glaub da liegt ein Missverständnis vor. Die beschriebenen Probleme haben nicht ausschließlich mit dem Terra Dos T4-40 oder anderen Erntemaschinen zu tun. Das Problem ist der Mode 2, bei dem die Kollisionserkennung nicht funktioniert.
Infolge dessen klappt natürlich auch ein eventuelles Zusammentreffen von Helfern im Mode1 und Mode2 nicht und zusammen mit dem Giants-Ki-Verkehr kann da schon mal ein gepflegtes Chaos entstehen ;) 
Um es mit den Verkehrsnachrichten zu sagen: "Der nachfolgende Mode2 Abfahrer konnte nicht anhalten und fuhr ungebremst in die Unfallstelle" :)
Dem entsprechen vermutlich auch das Problem von @sdl112. Eben der Mix aus Mode1, Mode 2 und Ki-Verkehr führt zu dem von Dir beschriebenen Problem, so meine Vermutung.

Entsprechend müssen wir bis zum Release des CP mit neuem Mode2 uns so weiter behelfen. Ist mit viel probiererei schon machbar. AD legt halt den Ki-Verkehr völlig lahm und das gefällt mir persönlich auch nicht so gut, deswegen im Moment deaktiviert.

Gruß
omegaMV6

**Comment by Tensuko** [comment]
Nur weil ich den #3916 markiert habe, heist das nicht, dass es sich auf den Tera-Dos bezieht.
Das Problem was dort beschrieben wird, ist die fehlende Kollisionserkennung bei einigen Fahrzeugen, was auch für Mode1 und andere Modi der Fall ist, was ich selber in Vanilla getestet habe. Das ist leider so und kann man sich sehr leicht angucken, indem man im Spiel mal F5 drückt.
Ob wir da von unserer Seite abhilfe schaffen können muss ich in der nächsten Teambesprechung sehen.

**Comment by Axel32019** [comment]
Ich denke schon das die Kollisionserkennung  generell momentan etwas "eigenartig" läuft:
1. Die "Boxes" falten sich im CP Betrieb zusammen
![fsScreen_2019_06_24_18_44_03](https://user-images.githubusercontent.com/52026009/60037527-085a6e00-96b2-11e9-8679-a1eed9950624.png)

2. nach Abfahrer entlassen ist nur noch die "nicht"-CP Box da
![fsScreen_2019_06_24_18_44_25](https://user-images.githubusercontent.com/52026009/60037551-20ca8880-96b2-11e9-9973-ea3a735bb025.png)

FS19_CoursePlay (Version: 6.01.00234)

**Comment by Tensuko** [comment]
Kauf dir mal die kleinen Vanilla Traktoren und vergleiche die Kollisionserkennung ohne CP Fahrer.
Ich meine die war auch ohne CP merkwürdig, der test ist aber etwas länger her.
Komme in letzter Zeit leider wenig zum rumprobieren.

Aber klar, auch seitens CP muss ein wenig gemacht werden. Wie im verlinkten Issue beschrieben (vlt) da muss ich auf @ThomasGaertner warten.

**Comment by Axel32019** [comment]
Hab mal noch ein bisschen weiter experimentiert:
zu 1. Das Zusammenfalten ist so in CollisionDetector:update implementiert, Das kann vielleicht noch etwas "schöner" gemacht werden. Die "Snake" könnte am Anfang eines befahrenen Courses komplett entfaltet sein und erst am Ende, so wie jetzt schon, zusammenfalten damit auch das Ende komplett erreicht wird.

zu 2. Das lässt sich folgendermaßen beheben:
In die Funktion AIDriver:dismiss() am Anfang hinzufügen:
	if self.collisionDetector then
		self.collisionDetector:deleteTriggers()
		self.collisionDetector:createTriggers()
	end

**Comment by Tensuko** [comment]
Schauen wir uns an, kann aber nicht sagen wann das was wird, aber danke für die Info!

**Comment by andrenrei** [comment]
@Axel32019 allso da bin ich raus mit programiren habe ich nix am hut xD

**Comment by andrenrei** [comment]
@Axel32019  wen du das kannst würde ich die datei einfügen und dan mal testen

**Comment by andrenrei** [comment]
was mir jetzt auch noch aufgefallen ist, wen man rechte maustaste betätigt erscheint zwar die maus aber nicht das coursplay fenster damit das wieder komt muss man das ganze spiel neustarten ist aber nur bei einem nicht bei allen fahrzeugen sprich ich habe 3 tracktoren (fahrzeug art spielt dabei keine rolle) ist diese problem nur bei einem so.

**Comment by Tensuko** [comment]
Kannst du mir sagen, welcher das ist ?
Beim Claas Axion 900 aus dem MotHub z.B. geht CP garnicht, da man sich wieder nicht an den GIANTS Standart gehalten hat.

**Comment by andrenrei** [comment]
Fahrzeug mässig benutze ich momentan nur die standert von Giants mod mässig habe ich dort dan nur einen Krone Tx 560 OY mit 100000 kapazität dran alls ich das kommentar geschrieben habe war es der fend 1050 ich hoffe ich jkonnte helfen sobalt das jetzt noch mal vorkommt mache ich ein bild

**Comment by Tensuko** [comment]
Ich hab es jetzt mal richtig gesehen, was da los ist und ja, da stimmt was nicht in CP....
Ich mach da aber im #3916 weiter.

**Comment by Tensuko** [comment]
Bisher scheint alles gut zu funktionieren.
Sollten noch Probleme auftauchen, die mit der Kollision zusammen hängen, bitte ein neues Issue aufmachen mit Beschreibung und ein Screenshot mit F5 an (siehe ersten Bilder in diesem Issue).
Closed.
