### ISSUE TITLE
CP 6.01.00.234 - ignore unload trigger from time to time

### ISSUE THREAD

**Issue by caplink811** [Courseplay/courseplay#3925]
Beside of "in work state" of mode 2, when harvester unloaded, and the unload driver follow the course to the unload point (selling point) the 1st round mostly works well, in the next rounds the unload driver return with a full trailer to the field. When it reached the unload trigger there is no message "abladpunkt erreicht" in the HUD displayed. I will provide log file when one could tell me, which debug modes are necessary.

**Comment by Tensuko** [comment]
Channel 1 and 2 is the right I guess, as they are for the Trigger.
So the unload only works once at the 1st try?

**Comment by caplink811** [comment]
hm, I play around with the params, and my guess is, it depends on the unload amount (abfahren bei), seems ok till 70%, becomes bad > 90% (tested with those values). but as mode 2 isn't that good, it was necessary to fire and hire the unload driver in between - so its only a guess.

I put a video on onedrive, and attached the logfile (part of) with dbg 1/2/12/14 switched on (my best guess).

tia and thx
[FS19_Log.txt.txt](https://github.com/Courseplay/courseplay/files/3318405/FS19_Log.txt.txt)

https://1drv.ms/v/s!Aqt5msdvWb55g1Kipjx_fV9Cev3Y

**Comment by Tensuko** [comment]
Full logfile pls...
And if you change the abfahren bei on Mode2 driver, this is #3311 
Just keep it below 70% then untill we managed to rework the mode2.

**Comment by andreasthu** [comment]
I see a.difference in unloading between mode 1 and 2.
Mode 1 unload at the beginning of the trigger, 
Mode 2 will unload at the end of the trigger, sometimes he is to fast to brake and stop, and so the trailer is out of them.
You can test it, drive in a course through a unload trigger and let the driver drive it up with both modes.
You can see the difference when the.traktor stops in both mod3s.
Lg
Andreas

**Comment by caplink811** [comment]
I'd a little spare time this day to do more research on this problem described above. In opposite to my 1st mention it seems not related to the value of "abfahren bei", it depends on this "updateAllTriggers()" function. When those runs before the unload driver reaches the trigger, all works as expected. I assume, that this function should be called when I hire the unload driver. But this happens not always, and then it comes to the described problem. 

This is just a remark for the protocol, as I have neither a log nor a movie of this behaviour.

thx for your effort and time

**Comment by Tensuko** [comment]
Mode2 uses the old Driver, not the AIDriver, that is one big reason why so many things not working and causing troubles. That would explain why they are not always get the Trigger right. There are might be some Adjustments needed to Triggers.

**Comment by Brendoni69** [comment]
I have the same problem. Works the first time but after that it won’t even register the top trigger. Works when I have a little bit over 70% but anything more it won’t register. Then when I set the drive on at 70% it still fills up to 95% each time?

**Comment by Tensuko** [comment]
Can someone tell if this is still valid ?
I don't have any problems on the latest Version.
This does not inclue Mode2 ofc!

**Comment by caplink811** [comment]
morning,

I guess you're right so please go ahead and close this issue. 

have a nice new year eve :-)

**Comment by Tensuko** [comment]
Thank you for your fast answer :)
Closed.
