### ISSUE TITLE
Game freezes after set helper has reached the end, while not in set vehicle

### ISSUE THREAD

**Issue by Denhalen** [Courseplay/courseplay#3926]
When having a courseplay set for field work, as a helper has reached the end of the course. If I don't drive along or in the direct area of him, while tabbing through the vehicles, the game freezes when getting into the vehicle. The last vehicle is still showing. 
There is no way to close the game, other then to either reboot the system or log out of my account. This happens only after a little while has gone by, between reaching the end point and switching to set vehicle. 
Note. This never happens with the transport function. Only Field work or Fertilizing.

**Comment by Tensuko** [comment]
Just beside... did you try to alt-F4 instead of reboot ?

Anyway: Logfile pls!
https://github.com/Courseplay/courseplay/wiki

**Comment by Denhalen** [comment]
Alt+F4 does nothing at all. Alt+Tab is also fruitless. I will try to reproduce this and post the logfile. I have a lot of different mods as well, including a modded map.

**Comment by Denhalen** [comment]
For some unknown reason, I can't upload a log file. Git gives me a 405 Not Allowed. And Pastebin keeps on loading.

**Comment by Denhalen** [comment]
2019-06-24 08:57 Warning (script): 'getParent': Argument 1 has wrong type. Expected: Int. Actual: Nil 
2019-06-24 08:57   ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (864): expectedType == Value::VoidType || expectedType == Value::ClassType

**Comment by Denhalen** [comment]
This warning is the last part as it freezes.

**Comment by Tensuko** [comment]
Doesn't help. There must be more.
So you can't drag and drop the log.txt into the comment box ?
That normaly works...

**Comment by Denhalen** [comment]
The file is more them 10 MB big. It's currently 64 MB

**Comment by zippgunn** [comment]
@Denhalen I had the same happen to me, and the same events in the log, but after pondering it over I remembered I added the waiting worker (yumis' mod in modhub) mod just before, and once that was removed, the game stopped having the issue. So if you are using that mod as well, try with it removed and see.

**Comment by Denhalen** [comment]
@Zippgunn, You might be on to something there. I did add this mod. I don't know why I added it, as it has no real value. I'll toss that one in the bin and hope for the better. Thanks for you advice.

**Comment by Denhalen** [comment]
@zippgunn, You hit the hamer on the nail. This solved my issue. Thanks for @Tensuko for trying to help me. I deleted the waiting workers and I could tab to my stopped vehicle. I will close this issue, as it is solved.
