### ISSUE TITLE
Course Play Combine pipe

### ISSUE THREAD

**Issue by ploughedfieldman123** [Courseplay/courseplay#3927]
Im on version  6.01.00234

But it seems to stop working say when combine gets stuck on a collision when reversing near a hedge, so when you release it from hedge then start it up again on CP this is when it just reverses and no pipe extends. whilst CP is activated, but if you stop CP then you can open pipe, but then tractor & trailer wont go to combine. as it has to be activated

**Comment by Tensuko** [comment]
Well it sounds like #3311 
But I will take an eye on that.

**Comment by Dschowy** [comment]
I have the same issue. Playing on Felsbrunn with fields 17-20 combined to a large one. Creating a couresplay field didn't work properly so I have to use the FS19 helper for the combine.
It seems that coureplay generates a "invisible wall" in front of the combine that makes him stop.

**Comment by Tensuko** [comment]
This CP Version is very old and not sure if that Issue still exist.
Closing it, if you face any Issue with Combine getting stucked, feel free to open a new Issue and discripe your Problem and add a Screenshot of the situation, thank you.
Closed.
