### ISSUE TITLE
tatraPhoenix

### ISSUE THREAD

**Issue by Ragworm** [Courseplay/courseplay#3928]
The tatraPhoenix has it`s waypoints to the left of centre when creating a course which means it needs its own courses

**Comment by Tensuko** [comment]
That is a known Issue and we can't do anything about it. We don't know how and why GIANTS take that Point, what we use for WP creation and driving. I think it was debugchannel 12 where you can see a little yellow dot above the Vehicle, that we use for WPs.
Closed.
