### ISSUE TITLE
Creating a pocket

### ISSUE THREAD

**Issue by Horozor** [Courseplay/courseplay#3930]
Why is this happening? Аfter unloading the combine starts moving simultaneously with the truck, because of this they are stuck. The pocket creation function does not work as it should, why did you add it? After all, workers still do not destroy crops, why do we need this function of creating a pocket? If you disable the movement of crops, workers do not understand that they interfere with each other.
https://youtu.be/eGDYWkjgtyU

**Comment by Tensuko** [comment]
Becouse you unload it.
If you don't want it to create a pocket, turn off fruit bypass on the Combine.
Beside that, it works as it should!
The any automatic things happening with Mode2 is #3311
