### ISSUE TITLE
tractor and plow

### ISSUE THREAD

**Issue by Siniy-lom** [Courseplay/courseplay#3931]
Объясните мне дремучему, неужели ТАК сложно организовать движение  в пределах прямоугольника? почему оно работало в ФС17, ФС15? Откуда у вас взялись рукожопы которые все испортили? 
============ googletranslation===========
Explain to me the dense, is it really so difficult to organize movement within a rectangle? Why did it work in FS17, FS15? Where did you get the handcuffs that ruined everything?

1.  https://mega.nz/#!BzRCQYya!oJptpJ4Kj8yMRrpudDnA1uz46LjADZ95jzZyhD70wP0   
зачем он поехал блуждать по всей карте? why did he go wandering around the whole map?
2.   https://mega.nz/#!cnJETSjJ!zZZss3zg2NaXwLijKnT9-A5NQlOc8t61wTaoIrJKq_k
https://mega.nz/#!8qBiRCyR!to9f7H-XYQt2ZkFBeV19D-R4TWPFgQWKFardGTU5XDM
https://mega.nz/#!YqJiDIbL!mZCVP0RYl_Kq3CeQxdsrUbYCJwJrY38dCIZU3nYuI_Q
https://mega.nz/#!czAwhIbL!KdAWQCHhUM6tZPxaqcRZVHYAHofQsr5bhl9nhnWwLMU
https://mega.nz/#!VqBi2K5L!4fMcKsCEnOkutvq9WqRoB0SeGML-dwT37aCNKJroW0Q
что это за пропуски? what is this omission?
3. я вообще молчу про непонятные попытки записи информации на Steamcloud
 I generally keep quiet about incomprehensible attempts to record information on the Steamcloud

**Comment by Tensuko** [comment]
1. No Idea what is your problem
2. No screenshot posted
3. No logfile attatched
4. FS19 is very different to FS15 and FS17 and a lot of things have to be reworked. A lot of old Code back from FS13 are still in CP Code.

**Comment by Horozor** [comment]
Насчет пропусков могу предположить. Плуги в 19 ферме кривые, они очень чувствительные к неровностям, у самого было так, правда с плугом побольше, малейшая кочка, и он уже из земли вылазит и пропуски делает.
Насчет куда трактор попер, это возможно из-за кривого поля. Длина проходов разная, они переделывали алгоритм поворота вроде, и теперь на таких "треугольных" окончаниях проходов такое случается, 
Совет, попробуй отключить разворот в пределах поля это первое. Второе сделать 1-2 прохода по кругу вначале. Ну и обновить версию, может че уже поправили насчет этого.

**Comment by Tensuko** [comment]
@Horozor 
can you try explain to me in english, what is the Issue ?
From google translation it is something with the plow course doesn't work very clean or something ?

**Comment by Horozor** [comment]
@Tensuko 
I also use a translator to communicate with you. I do not use plows, but sometimes I have to use them. The problem with the rotation if in the last tab the function is turned on within the field. If you turn it off the problem disappears. However, there is another bug. Even if the "plow out of field" function is enabled, it does not reach the edge and leaves a pass.
In the video, I tried to show when and how it all happens. Sorry that without editing, there is not much time to edit the video.
[Log](https://gist.github.com/Horozor/2e071bf56d61b573b8f2f902169e3c7f)
[Video](https://youtu.be/7VGftmgp0Sw)
[Savegame GoogleDrive](https://drive.google.com/open?id=1WXnigWMyoppBV4DzXk6-xVI_o2jzpvIz) course name 2\

**Comment by Tensuko** [comment]
Ok, thank you, I know what to look for yet.

**Comment by Siniy-lom** [comment]
https://drive.google.com/drive/folders/1GYvLT5Y7onxZduH8jqfSk4qY_MUAQL7O?usp=sharing     
на видео видно ВСЕ что происходит, требуемые логи и курсы там же.
the video shows ALL of what is happening, the required logs and courses there.

**Comment by Siniy-lom** [comment]
> 
> 
> Насчет пропусков могу предположить. Плуги в 19 ферме кривые, они очень чувствительные к неровностям, у самого было так, правда с плугом побольше, малейшая кочка, и он уже из земли вылазит и пропуски делает.
> Насчет куда трактор попер, это возможно из-за кривого поля. Длина проходов разная, они переделывали алгоритм поворота вроде, и теперь на таких "треугольных" окончаниях проходов такое случается,
> Совет, попробуй отключить разворот в пределах поля это первое. Второе сделать 1-2 прохода по кругу вначале. Ну и обновить версию, может че уже поправили насчет этого.

ну вроде бы не маленький, и не первый раз курсплей использую...

**Comment by Siniy-lom** [comment]
> 
> 
>     1. No Idea what is your problem
> 
>     2. No screenshot posted
> 
>     3. No logfile attatched
> 
>     4. FS19 is very different to FS15 and FS17 and a lot of things have to be reworked. A lot of old Code back from FS13 are still in CP Code.

2. есть там скриншоты...

4. ФС 19 отличается от ФС17 тем что:
1. в угоду производителям железа сунут только DX11 (вот нафиг он там нужен? да еще и так коряво?)
2. попыткой выдать 32х за 64х (как работало на одном ядре так и продолжает)
3. тотальной сменой адресации всего во все... типа вот мы работаем, аж 2 недели, лениво...

для смеху  - сравните хеш шейдеров фс19 и фс17...

**Comment by Horozor** [comment]
@Siniy-lom Маленький или нет не важно. Я более подробно описал в чем причина, повторил и сразу понял в чем причина такого поведения трактора, что и описал разработчику.

**Comment by Siniy-lom** [comment]
> 
> 
> @Siniy-lom Маленький или нет не важно. Я более подробно описал в чем причина, повторил и сразу понял в чем причина такого поведения трактора, что и описал разработчику.

причина либо в рукожопости, либо в желании создания вида работы...
пример из жизни - заявили программисты - расплывчато написано ТЗ, вот и написали как поняли... взяли 2х створчатый шифонер, пару бит, и просидели у них, АБСОЛЮТНО МОЛЧА 2 часа... стразу и тз нормальное стало, и руки из жопы вынулись, да еще и перестали дико бояться такого вида деятельности как оптимизация. )))

**Comment by Horozor** [comment]
@Siniy-lom 
Люди добровольно занимаются разработкой этого мода, они нам (игрокам) ничего не должны. Но они все же для каждой версии игры делали, и продолжают делать моды, и в данном случае продолжают улучшать его. Так что это не совсем корректно обзывать их рукожопами.
Причина в типе разворота если что. Просто пока не использовать режи "разворот в пределах поля" а в следующих версия поправят и это.

**Comment by pvaiko** [comment]
My Russian is a bit rusty but not sure I even want look at his after reading the original post, that attitude rather motivates me to delete the whole issue...

**Comment by Tensuko** [comment]
@Horozor 
Thank for the help in Translation and explaining, we appreciate that.

@pvaiko 
Translated stuff is hard to mention how that is meant, but after I translated all the text, I am with you and will close this one.

@Siniy-lom 
It is not like we don't want to help you, BUT this is a Mod created by ppl with a job and family and they get not payed for it! We do what we can, but when you come arround with such rude words (I won't take the translater 1 to 1...) there is no mood at all to fill your wishes and it won't speed up ANYTHING! It takes time, we are aware of the Plow Issues, but when I say FS19 is different then FS17, then it is nothing that you can see, it is more for the Code, else you could simply put CP5 into Modsfolder, wich is NOT possible. Also we take the step to rewrite the code, since old parts in the CP Code are still from FS13.

Enough said. Closed.
