### ISSUE TITLE
nur mal eine Frage

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#3937]
Nur so nebenbei
kümmert sich noch jemand um CP17?
Ich halte nichts von FS19 für mich =  Müll
Wäre schön wenn das so wäre!
MfG

**Comment by Tensuko** [comment]
Kurz und Knapp: Nein.

Warum FS19 gleich Müll für dich ist, verstehe ich zwar kein Stück, da es durchaus ein paar Verbesserungen gab, aber ok, jedem das seine, aber bitte halte dich hier an konstruktive Kritik und nicht an 'Müll' ;)

**Comment by Lustiger-Hubi** [comment]
Ja! die Frage ist ja beantwortet worden!
Danke Dir!
