### ISSUE TITLE
FPS Einbrüche beim FENDT 1050

### ISSUE THREAD

**Issue by MoritzJDR** [Courseplay/courseplay#3940]
Wenn ich beim stadart FENDT 1050 Vario den Modus von Courseplay von z.B. Transport zu Feldarbeit ändere, bekomme ich erhebliche FPS Einbrüche. Durch Neuladen (Wo sich CP dann bereits im zuvor gewählten Modus befindet) läuft wieder alles super, bis man den Modus wieder ändern möchte. Das Problem tritt sowohl mit als auch ohne Mods auf.

**Comment by Tensuko** [comment]
This is a bit complicated, actually there should be a workaround for it in CP, but mostly it is a GIANTS Issue:
 #3502

**Comment by MoritzJDR** [comment]
Okay, thanks^^

**Comment by MaLouPa** [comment]
Hi,
bei mir hat es damals geholfen nur mit Standard Fendt zu fahren. Seitdem ging es damals unter 1.3 noch.
Sobald ich zu viele Mod Fendt drin hatte (Yogi zb. ) ging nichts mehr

**Comment by MaLouPa** [comment]
Hi,
bei mir hat es damals geholfen nur mit Standard Fendt zu fahren. Seitdem ging es damals unter 1.3 noch.
Sobald ich zu viele Mod Fendt drin hatte (Yogi zb. ) ging nichts mehr

**Comment by Tensuko** [comment]
Danke mal das ist ein Shader/Texur Problem seiten GIANTS, ich hab den Fendt 1050 schon mit CP im Einsatz gehabt und keine Probleme feststellen können.
Ich mach den erstmal zu, ansonsten muss man da mal mit GIANTS sprechen.
