### ISSUE TITLE
Long loading game

### ISSUE THREAD

**Issue by Horozor** [Courseplay/courseplay#3942]
Hello. For a long time I could not understand why the game is loaded sometimes for 5 minutes. Having tested all my mods, I realized that the matter was in the courseplay. In the video, I showed the difference in loading speeds without a mod and with a mod.
- New game, standard map
- ~12 sec without courseplay
- ~40 sec with courseplay
- ~12 sec with all my mods except courseplay

I would be grateful if you tell me the reason
[Log](https://gist.github.com/Horozor/13c318e2c5c390900b5e12972b0b6e5c)
[Video](https://youtu.be/MsOIfHi6iOE)

**Comment by Tensuko** [comment]
Hello.
That is very easy to explain:
The more Saved Courses you have, to longer the loadtime.
Copy your courses somewhere on the Desktop and load the game again with CP, it should go much faster.
Some ppl say, just save your Refill Course or Transition Course and always create the Field Course new and just temporary save them.

Try it out. If you still have a long loading time with CP and no Course in Folder. Please let me know.

**Comment by Horozor** [comment]
@Tensuko 
I deleted all the courses from CoursePlay_Courses folder, and the game now loads very quickly. Thank you!
