### ISSUE TITLE
Not showing in MODS/DLCS when creating new game save

### ISSUE THREAD

**Issue by Cobe123** [Courseplay/courseplay#3943]
Courseplay SIX shows in my installed mods folder but when I go to start a new game it's not available .

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Cobe123** [comment]
https://gist.github.com/Cobe123/d91ff72262f10564faf53b182f06447d

**Comment by Horozor** [comment]
@Cobe123 
Just delete - in name of mod "courseplay-master"
Mod names should not contain special characters, for example (  )  -

**Comment by Cobe123** [comment]
Thanks bud <3
