### ISSUE TITLE
Trailers tipping but not emptying

### ISSUE THREAD

**Issue by imnjs** [Courseplay/courseplay#3944]
Using all non-mod equipment, when the tractor is filled by the combine and continues on to the unload point, the trailer tips but the contents of the trailer do not empty.

Attached is log below;

[log.txt](https://github.com/Courseplay/courseplay/files/3353311/log.txt)

**Comment by Tensuko** [comment]
That will end up in #3311 but I will try to take a look at it with V236

**Comment by Tensuko** [comment]
Works fine:
![fsScreen_2019_07_06_12_24_20](https://user-images.githubusercontent.com/27344744/60754972-4a0be280-9fe9-11e9-91aa-70a4eb799cdd.png)

Trailer, Silo, Map, Screenshot pls

**Comment by imnjs** [comment]
I apologize. That was my own fault. I was setting an unload point at the silo that was causing the trailer to rise but not empty. I wasn't aware at the time that you just had to drive over it and CP would pick up the trigger automatically. That was in grain transport mode.
