### ISSUE TITLE
Mode 2, sofort abfahren fehlt

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#3945]
Hallo Leute,
Mir ist gestern abend aufgefallen, das beim mode 2 die Funktion "sofort abfahren" fehlt.
Die war immer im 2. Reiter von links unter "abfahrer entlassen" gelistet.
Im mode1 ist sie immer noch vorhanden.
(Mal davon abgesehen, das das keycommand dafür immer noch nicht funktioniert)
Spiele mit cp v 6.01.00234

Ist halt nervig, wenn das feld abgeerntet ist, aber man keine möglichkeit hat, den halbvollen Abfahrer abfahren zu lassen.

Lg
Andreas

**Comment by Lupo36** [comment]
Weil das fehlende Keycommand nicht funktioniert spiele ich immer noch die Version 167, denn ab Version 168 geht es nicht mehr.

**Comment by Tombarkemeyerbruns** [comment]
#3311

**Comment by Tensuko** [comment]
Muss ich mir angucken, wenn ich zu Hause bin.
Ich meine da war was.

**Comment by Tensuko** [comment]
Gleiche stelle mit V236:
![fsScreen_2019_07_06_12_24_39](https://user-images.githubusercontent.com/27344744/60754959-1df06180-9fe9-11e9-9f8f-0b22ecb083f4.png)

**Comment by Tensuko** [comment]
Habe durch ein anderes Issue was rausgefunden für eure Keycommands:
Sie funktionieren! ABER: Ihr setzt einmal den Input wie ihr ihn haben wollt, speichert dies ab (wie gehabt) und erst nachdem ihr das ganze einmal mit der Maus ausgelöst habt (z.B. Fahrer einstellen/entlassen) funktioniert auch der Keycommand! Warum weis ich nicht, werds aber mal so aufnehmen.

**Comment by andreasthu** [comment]
Hallo tensuko
Hab nun die v 236 und da isser wieder der sofort abfahren button.
Bzg 2. Hab das im anderen thread beantwortet.
Lg
Andreas

**Comment by Tensuko** [comment]
Ok ich mach dann hier zu. Wenn das problem erneut auftritt, nochmal melden, dann müssen wir aber mal genauer gucken wieso die option weg ist.
Closed.
