### ISSUE TITLE
Mode 2 unload ROPAstyle harvester

### ISSUE THREAD

**Issue by hackselgut** [Courseplay/courseplay#3946]
Could you fellows adjust, the approach, style of mode 2 vehicle so that it has more of a square style.
As it is now it comes in from behind harvester and takes an angle to the pipe, from bottom right, to top left corner, should be more of a square, that is bottom right to bottom left then to top left, thus a better line up to the pipe. Picture included to show approach, as is now.   Bob
![fsScreen_2019_07_03_08_52_42](https://user-images.githubusercontent.com/10256656/60596710-8cc68400-9d77-11e9-927e-612b6c2f59e3.png)

**Comment by Tensuko** [comment]
#3311 
Closed.
