### ISSUE TITLE
CP fails to turn around with Horsch 12 and 18 meter planters

### ISSUE THREAD

**Issue by SteelRodent** [Courseplay/courseplay#3947]
CP 234 / FS19 1.0.4

I'm almost certain this is actually a Giants issue, but... when using the 12 and 18 meter Horsch Maestro planters from the free Horsch Agrovision DLC (which yes, was released as a mod), CP fails to turn around after the first lane. It stops, lifts the tool, and then takes off either straight ahead or at an angle.

All other tools in this pack that CP currently support (including both seeders) work just fine. Every vanilla planters that I've tried work just fine as well. Only those two are acting up.

The chosen crop do not appear to matter. Also tried with three different tractors CP normally likes, so fairly certain it's the machines themselves that cause the problem.

Log: [https://gist.github.com/SteelRodent/d57158a4a8884cfce79e41815977d4f0](https://gist.github.com/SteelRodent/d57158a4a8884cfce79e41815977d4f0)
Note: Large log and current CP seems to get into a panic every time it has to generate a new route. 

EDIT: Fixed log link

**Comment by pvaiko** [comment]
> current CP seems to get into a panic every time it has to generate a new route

Not sure what this exactly means I see no CP errors in that log.

**Comment by SteelRodent** [comment]
> 
> 
> > current CP seems to get into a panic every time it has to generate a new route
> 
> Not sure what this exactly means I see no CP errors in that log.

I mean these parts:
2019-07-02 21:11 CourseGeneratorScreen:onCreate()
2019-07-02 21:12 WARNING: performing emergency garbage collection pass - memory went from 128550 KB to 273632 KB in less than one frame
2019-07-02 21:12 INFO: usage is now 130951 KB; full GC took 251.154846ms 

Not an error, but I haven't seen this with the previous versions

**Comment by pvaiko** [comment]
Oh, that's fine, this came with 1.4, looks like they added either the garbage collection or this message to the Giants lua engine. The course generation uses a lot of (temporary) memory that's why GC kicks in at the end.

**Comment by Tensuko** [comment]
Sounds like the Issue I had, you maybe remember @pvaiko

**Comment by SteelRodent** [comment]
> 
> 
> Oh, that's fine, this came with 1.4, looks like they added either the garbage collection or this message to the Giants lua engine. The course generation uses a lot of (temporary) memory that's why GC kicks in at the end.

Got it. Haven't played in a while so was surprised to suddenly see it. But yeah, obviously not related to the issue.

**Comment by pvaiko** [comment]
@SteelRodent is this still an issue with 240 or later?

BTW, does anyone have a real life video of a tractor reversing on the field with a >15m sowing machine?

**Comment by SteelRodent** [comment]
Only just had time to test today. With CP 245 these two machines appear to work normally now. At least working the field on Felsbruun. Haven't been able to test on other maps yet (need to harvest them first).
