### ISSUE TITLE
CP+AD Hay Collection problem

### ISSUE THREAD

**Issue by RUGhost** [Courseplay/courseplay#3949]
I use CP to collect hay from field and AD to transfer hay from field to burn but CP does not detect AD. I activate "AutoDrive for Unload/refill" but that does not help.
if you need log, tell me which channel should active?

https://youtu.be/5IIoIvUqDXQ

**Comment by jala15** [comment]
I have the same issue. CP does detect AD but it "forgets" (resets) the "use AutoDrive for unload/refill" setting every time you press drive, and CP only calls AD the exact time when it detects the full trailer. Changin the setting when already full does nothing. For testing you can try and empty a bit of your Hay so CP can continue working, then activate CP and quickly (before reaching full again), activate the "AutoDrive for unload/refill" option.

**Comment by RUGhost** [comment]
@jala15 yes that tricks working nice but i think this problem should be eliminated by dev

**Comment by pvaiko** [comment]
Should be fine with 235

**Comment by roadrunnerR74** [comment]
my version 235 still does not detect autodrive

**Comment by pvaiko** [comment]
That's a different issue, you need the latest AutoDrive.

**Comment by roadrunnerR74** [comment]
autodrive Version	1.0.1.9 this is the latest i can find  and it does not detect this version 

> That's a different issue, you need the latest AutoDrive.

autodrive Version	1.0.1.9 this is the latest i can find  and it does not detect this version  dont know if that is the latest btw thanks anyways for the CP work

**Comment by andreasthu** [comment]
1.0.3.3 is the latest autodrive you can find:
https://github.com/Stephan-S/FS19_AutoDrive

lg
andreas

**Comment by roadrunnerR74** [comment]
> 1.0.3.3 is the latest autodrive you can find:
> https://github.com/Stephan-S/FS19_AutoDrive
> 
> lg
> andreas

thank you andreas
