### ISSUE TITLE
Trailer tipping but not emptying

### ISSUE THREAD

**Issue by N3h3miah** [Courseplay/courseplay#3953]
I have a course to empty the combine. The tractor does reach the silo tipping point and starts tipping but the trailer doesn't empty at all. Is this a bug or user error?
Here is what I guess is the relevant section of the log file:
2019-07-07 10:34 :41 [dbg1 lp167196] 7230 Pro (#5): transformId 146709 is in tipTriggers (#30) (triggerId=146709)
2019-07-07 10:34 :41 [dbg1 lp167196]     trailerFillType=4 OAT
2019-07-07 10:34 :41 [dbg1 lp167196]     trigger (146709) accepts trailerFillType
2019-07-07 10:34 :41 [dbg1 lp167196]     trigger (146709) fillLevel=0, capacity=480000 
2019-07-07 10:34 :41 [dbg1 lp167196] 7230 Pro (#5): self.cp.currentTipTrigger=146709 , cpActualLength=38.495661444205
2019-07-07 10:34 :41 [dbg2 lp167196] Trans-SPACE 8000: distanceToTrigger=29.647981009317, bestTipReferencePoint=table: 0x026d8fb49db8 -> trailerInTipRange=false
2019-07-07 10:34 :41 [dbg2 lp167196] Trans-SPACE 8000: goForTipping = false [trailerInTipRange == false]
2019-07-07 10:34 :41 [dbg2 lp167197] Trans-SPACE 8000: distanceToTrigger=29.45429813009, bestTipReferencePoint=table: 0x026d8fb49db8 -> trailerInTipRange=false
2019-07-07 10:34 :41 [dbg2 lp167197] Trans-SPACE 8000: goForTipping = false [trailerInTipRange == false]
2019-07-07 10:34 :41 [dbg2 lp167198] Trans-SPACE 8000: distanceToTrigger=29.0549819511, bestTipReferencePoint=table: 0x026d8fb49db8 -> trailerInTipRange=false
2019-07-07 10:34 :41 [dbg2 lp167198] Trans-SPACE 8000: goForTipping = false [trailerInTipRange == false]

**Comment by N3h3miah** [comment]
Stopping the driver and restart the tipping fixes this state: https://imgur.com/1qNQnpa

**Comment by sootysax** [comment]
you're supposed to post your complete log as an attachment

**Comment by N3h3miah** [comment]
https://gist.github.com/N3h3miah/545f1e38042f836afc1f8d53de4bc4bd

**Comment by Tensuko** [comment]
Normal Silo ? Got a screenshot or Video ?

**Comment by N3h3miah** [comment]
There is a screenshot link in my first comment

**Comment by Krahazik** [comment]
I have noticed the same thing. Even with a vanilla tractor, trailor and silo.
What additional information might help? I can see about getting the info.

**Comment by Krahazik** [comment]
> 
> 
> Stopping the driver and restart the tipping fixes this state: https://imgur.com/1qNQnpa

While that works as a temp workaround, to my mind it kind of defeats the purpose and breaks the automation of the whole thing.

**Comment by Flashsolutions** [comment]
I saw this problem as well.  I discovered that there is an option in which you must fill out what type of grain you are carrying (Vehicle Specific Settings).  Since it is not available in every mode, for instance the combi mode, you would probably miss it.  By default it is set to wheat.  If you are carrying canola, the trailer will open but the canola will not dump.  To find the setting you have to be in the Courseplay Control option and select the first icon on the left, Grain Transport mode in order to see it.  I should note that it is NOT saved, so every time you prepare to drive a course, you need to check and reset it to the crop in your trailer.

**Comment by N3h3miah** [comment]
Thanks @Flashsolutions I would say since the mod doesn't show the option in the combi mode this is just a workaround. In the grain transport mode this makes sense since the mod does need to know what grain type to load. In the combi mode this should not be necessary.

**Comment by Krahazik** [comment]
I just traied the workaround where I set the load type in the transport mode first, and its not working. Still not dumping automatically.

[My Log File on Gist](https://gist.github.com/Krahazik/c5c75ebbc020f0d9c5f732188ac83ff9)

**Comment by N3h3miah** [comment]
> I just traied the workaround where I set the load type in the transport mode first, and its not working. Still not dumping automatically.
> 
> [My Log File on Gist](https://gist.github.com/Krahazik/c5c75ebbc020f0d9c5f732188ac83ff9)

I can confirm that, the suggested workaround doesn't work for me either.

**Comment by Gyxoz** [comment]
I am having the same problems and the workaround does not work for me neither. 

I noticed that when trying to unload into a placed grain silo on my property, the trailer will open and tipp without the grain coming out. The helper then drives on with the trailer still tipped, and as soon as it reaches regular ground, it starts unloading onto the ground.

**Comment by N3h3miah** [comment]
Why is this still on "more information needed" do you need something more?

**Comment by Tensuko** [comment]
In the logfiel are LUA Errors, that can be anything.
Try with V283 (skip .1 or .2 and so on) and post a logfile with debugchannel 1 and 2 active.
I am still sure there is a Mod Conflict/Issue, as it normaly works...

**Comment by aceooooooooo** [comment]
I am having the same Issue, this is with any fermenting silo that I have tried to download. Runs the course fine. When unloading the trailer raises and the unload animation works, but it subtracts nothing from the trailer. The driver will just continue to sit there. I can stop the driver stop the unload process manually and it will unload fine. I have tried using the modes for the hopper and etc. with out any changes.

**Comment by aceooooooooo** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3518902/log.txt)

**Comment by RaggedWolf** [comment]
I have the same problem.I have to use a parking system for a workaround...so i go check every 5 min just to unload the trailer manually..Witch is a bit annoying because it defeats the automation of CP...

**Comment by Tensuko** [comment]
Still valid wtih V357+ ?

**Comment by Tensuko** [comment]
Closed due to inactivity.
