### ISSUE TITLE
Mode 6 issues with plow

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3954]
![fsScreen_2019_07_07_10_20_40](https://user-images.githubusercontent.com/6591048/60769723-6703ec80-a0a1-11e9-8abd-e237524ed1a3.png)

Turn on field is not working with the POH5 plow..   if it is activated the tractor will back up forever until it hits an obstacle.

If turn on field is turned off, the tractor stops and lifts its plow several meters before the end of the row, and then turns around and lowers the plow several meters before the beginning of the row.

https://gist.github.com/sootysax/4d045f3397efbe852822aaf06dc8640d

**Comment by pvaiko** [comment]
Asked Giants about this as the work area nodes of this plow do not point forward as all other tools I saw, causing this issue.
