### ISSUE TITLE
Need Help with log error

### ISSUE THREAD

**Issue by 00Donkey** [Courseplay/courseplay#3956]
So my game keeps crashing, and it seems to happen either when switching vehicles, or just as often, whenever i tell AI-drivers to offload their assigned combine, The A.I. drivers will sometimes start going to offload, and then my entire HUD disappears (both Courseplay HUD & the in-game help/tips menu as well as the mini-map... then when i switch to a different vehicle from there, the game freezes....
      I've tried removing all the mods from my logs that had any type of errors, and basically i'd like to know if my log file hints at whether it's just a normal bug from the courseplay beta? or is it another mod or keybinding issue? I notice the log says something about bindings for the keys "L" and "M" going back and forth but i cant figure out where in the keybindings it's talking about?
[log.txt](https://github.com/Courseplay/courseplay/files/3366316/log.txt)

**Comment by pvaiko** [comment]
Not sure where did you get the Courseplay version you are using, I don't see the usual CP startup messages in your log, make sure you install the official version from here https://github.com/Courseplay/courseplay/releases

**Comment by Tensuko** [comment]
The only Error I see is FS19_manTGS41500HKL.hookLiftTruck and that is not a CP Issue.
There are some Mods that are not on GIANTS Standart and not working with CP, wich we are not supporting. Check that Error in a Forum, at best of the Mod.
Closed.

**Comment by 00Donkey** [comment]
I'm about to Download/Install CoursePlay from the NEW link you just gave me! But if you're wondering where i got my version of Courseplay,... I'm a long time subscriber of Ian Robson and got it from the link he provided in his video (Video Link at the correct Timestamp of when/where he said to download Courseplay) https://youtu.be/b-6y6WtsqpQ?t=13 ...Anyways, i will forllow the link you guys gave me, and also after doing some Hunting on Google for "Mods that cause Courseplay to crash" and other similar search words regarding FS19 mods & Courseplay... And so i figured out that the MAN TGS Hooklift truck you guys mentioned... Apparently, That mod is NOTORIOUS For Crashing or freezing the game when you have Courseplay installed! As well so does any mod that has a "BALE-AUTOLOAD" Script built into the mod, and i had THREE OF THOSE "AUTOLOAD" Trailers installed from FS19's Modhub section of the game! And so this is what leads me to my next question... Why have i never seen courseplay in any version of Farming-Simulator's "Mods Download" section of either FS15 FS17 or now FS19? I mean, i know it's a complicated mod, and it's quite often in a beta state due to all the HUGE AMOUNTS OF TIME AND EFFORT you guys undoubtedly have to put into Courseplay, ...But it WOULD be cool to have it modhub, Simply because i've noticed over time, that (sometimes) When people upload their mods onto Modhub, They will often make sure that their new mod will work with other established mods for the bennefit of the folks who enjoy and use their mods... And a mod like Courseplay which has a HUGE and VALUABLE REPUTATION, would MOST LIKELY have a LOT of modders wanting to make sure their mods will work and cooperate with courseplay! *(This is more or less, my simple opinion, & Take into consideration please that my humble opinion is the opinion of somebody who doesn't know the FIRST THING about creating/updating or building Mods and the intricate scripting that's involved with that!)* But again, THANKS EVERYONE FOR ALL YOUR HELP!! And if the game crashes on me again after removing my autoload trailers and my copy of the MAN-TGS Hook-lift Truck mod,... I'll DEFINITELY LET YOU GUYS KNOW! Thanks again! 👍
