### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Horozor** [Courseplay/courseplay#3957]
Is it possible to add the ability to unload sugar beets in a silo bunker? This is possible manually, but the driver doesn't want to unload the trailer when I use mod 2 to unload the combine.

**Comment by Tensuko** [comment]
It should be possible, if you can do it manually.
Somehow I think there are problems with Modded Silo Bunkers.
Some ppl have problem with unload too.
Can you make a logfile with debugchannel 1 and 2 ?

**Comment by Horozor** [comment]
@Tensuko 
[Log](https://gist.github.com/Horozor/1e36f3c79947c188380137aecf050dae)
I am using the Westeel Silo Extension mod, and the standard bunker
![fsScreen_2019_07_09_10_42_59](https://user-images.githubusercontent.com/37561569/60868891-a1eb5900-a236-11e9-9352-a2e6ecc679ea.jpg)

**Comment by Horozor** [comment]
Thanks to you I understood what to look for. In the file farmSiloLarge.xml on the path **E:\Games\Farming Simulator 19\data\placeables\farmSilos**  added sugarbeets to the fillTypes line. Now unloading works

**Comment by Tensuko** [comment]
@Horozor Nice! Glad I could help you.
But I think that must be added in the Mods too if ppl want to unload it in the Mod Bunker too
