### ISSUE TITLE
Suggestion: spiral course generation

### ISSUE THREAD

**Issue by kobra60** [Courseplay/courseplay#3958]
I love the spiral course with the headlands. I've had a lot of problems with the normal way.  One thing I've found though is it will cut across corners which are generated. This is fine in a normal square field or round one. The problem comes when there's a corner by a farm or some other place that has fences with collision. The equipment gets hung up on the obstacle every time it goes around. I'm trying a work around to manually doing a headland course and generate the rest off that.   If it's possible, I think this could be remedied by starting the spiral on whatever the inner most headland is. Then we could put in enough headlands to get by those corners before the spiral course starts. 

Keep up the good fight. I can't imagine all the items you are working on to get this beast working, but I wouldn't bother playing farm sim without it. 
Thank you for your efforts!

**Comment by pvaiko** [comment]
@kobra60 would you have a screenshot of a course with the corner problems?

**Comment by kobra60** [comment]
I'll come up with one hopefully today.

Thank you.

￼


Blackbird Transport LLC

Kevin Eckhoff, President

1013 Fern Ave SE

Menahga, MN  56464

(218) 255-0308

**Comment by kobra60** [comment]
I ran a couple courses and took several shots of them where the problem happens. I'm almost always using multiple tools too.  It usually just messes up the outside one.   I just use two at a time in this map though,   In looking closer, the course would work fine too if it just stuck strictly to the headland course and didn't create those shortcuts.


![20190709080632_1](https://user-images.githubusercontent.com/36580296/60893447-92641400-a226-11e9-80f8-fd6967b7f4fa.jpg)
![20190709080711_1](https://user-images.githubusercontent.com/36580296/60893449-92641400-a226-11e9-9bd7-f5bc7dcbb9e8.jpg)
![20190709080921_1](https://user-images.githubusercontent.com/36580296/60893450-92fcaa80-a226-11e9-93e6-77995f0ee241.jpg)
![20190709081444_1](https://user-images.githubusercontent.com/36580296/60893451-92fcaa80-a226-11e9-9d2a-5ad7a26204f3.jpg)
![20190709081524_1](https://user-images.githubusercontent.com/36580296/60893452-92fcaa80-a226-11e9-945b-2edece1472d5.jpg)
![20190709081658_1](https://user-images.githubusercontent.com/36580296/60893454-92fcaa80-a226-11e9-8e33-5c0f9c39beaa.jpg)
![20190709082129_1](https://user-images.githubusercontent.com/36580296/60893455-93954100-a226-11e9-9e0b-7b4d8c2af67a.jpg)
![20190709082246_1](https://user-images.githubusercontent.com/36580296/60893457-93954100-a226-11e9-8cac-b07bc40deeab.jpg)

**Comment by pvaiko** [comment]
ok, thanks, I see now what the problem is, looks like my pathfinding algorithm needs some tuning.

**Comment by knoxville73** [comment]
Hello,
For a better realism with the spiral function, it is necessary to have the possibility to divide the field in 2, 3, 4, ... (depend of the field dimension).  With a division, we reduce the tractor displacement without working.

**Comment by pvaiko** [comment]
@knoxville73 have you tried the racetrack pattern?

**Comment by knoxville73** [comment]
Hello Peter,
The racetrack is not exactly what I want to explain.
The correct situation is to use the Spiral many times on the same field, always in the same direction.  With the racetrack, you work in two spiral at the same time.  with this, the pipe of the combine is in fruit side one time of two.  For a better way, it is perfect if we work one little spiral and at the end, we begin a next spiral always in the direction to have the pipe at the correct position (sorry for my english ...).

**Comment by pvaiko** [comment]
@kobra60 which map is that? Could you save the field definitions from it as described in the Wiki and post it here?

**Comment by pvaiko** [comment]
@knoxville73 I see, spiral wasn't meant for wide fields originally,  I can certainly split the field into sections, do they do this IRL?

**Comment by knoxville73** [comment]
@pvaiko 
Yes, the splitting is used IRL for two reasons:
First reduce the lost time in the headland.
Second, reduce the soil compaction.

The racetrack is an option and the multi spiral is the other option (I prefer this because it's possible to have always the pipe in the best position)

**Comment by pvaiko** [comment]
Thanks, I know why splitting make sense, was jsut not sure they use the spiral pattern this way too.

**Comment by kobra60** [comment]
That map is County Line.  It's a 4x map.  I've made the file and included a log too.  As long as we were at it, I thought I'd mention the sharp v's in courses that cause the vehicle to seem to 'pause, then jerk a bit,' then gives up and takes off in a bee line to parts unknown.  Sometimes it will just spin circles.  There have been some great improvements made recently to the course generation, and maybe this is a known issue.  I thought I'd post a screenshot of a course example in a field I fight with a bit because of its odd shape.  I'm working on widening out the narrow part on top and that should help a lot.

https://gist.github.com/kobra60/738318833b9566c11175b39cc10e862c

![20190716091639_1](https://user-images.githubusercontent.com/36580296/61338334-7819cf80-a7fe-11e9-89e6-7e0c109662d7.jpg)
![20190716091739_1](https://user-images.githubusercontent.com/36580296/61338335-7819cf80-a7fe-11e9-8509-773cf968b375.jpg)

**Comment by pvaiko** [comment]
Yeah, that's a difficult one. Die you try the 'longest edge' starting direction, may give better results.

**Comment by kobra60** [comment]
I'll give that a shot. Might be offline a couple days. Thanks!

￼


Blackbird Transport LLC

Kevin Eckhoff, President

1013 Fern Ave SE

Menahga, MN  56464

(218) 255-0308

**Comment by pvaiko** [comment]
Reopen if this is still an issue with 239 or later.

**Comment by kobra60** [comment]
Thank you!  I look forward to trying these later today!

￼


Blackbird Transport LLC

Kevin Eckhoff, President

1013 Fern Ave SE

Menahga, MN  56464

(218) 255-0308

**Comment by GeorgeEarslight** [comment]
> Reopen if this is still an issue with 239 or later.

Hi @pvaiko, still have the problem with spiral. 
It's an extended field, which files do you need apart from screenshot?

Also, a relevant comment. It's possible that during a transition route (row-to-row) an extended tool travels outside the field bounds, even if the vehicle is inside. Would you like to discuss it here, or should I open an issue?

**Comment by pvaiko** [comment]
Apart from the screenshot I need the field number and the field definition XML as described in the Wiki.

Not sure I understand your other problem though, the vehicle should travel on the headland path so tools should not go off-field.

**Comment by GeorgeEarslight** [comment]
Custom field 5 as shown on the generator. It's made by connecting 4 and 5, and using "overwrite field 5's path in list.
![image](https://user-images.githubusercontent.com/30686125/62062280-64745d00-b231-11e9-8524-6cfa32f47282.png)
[FS19_washoeNevada.SampleModMap.zip](https://github.com/Courseplay/courseplay/files/3443089/FS19_washoeNevada.SampleModMap.zip)

I'll need to delay the comments on the other problem as I have some bales to clear on this.

**Comment by pvaiko** [comment]
But does this actually causing an issue? Isn't that going to be a turn maneuver, a wide turn with corner avoidance, the one you fixed?

**Comment by Tensuko** [comment]
What is the status of this ?

**Comment by knoxville73** [comment]
Hi Tensuko,

For me, the spiral was not exactly what I want, but the new setting (I don't know his name) is the better at this moment.
If you add the possibility to increase de number of lap (4 - 6 - 8 ...) or to choose a division of the field (divide in 2 - 3 - 4, ...) I think all is perfect.

The most important is to have always the pipe at the correct side (out of fruit), the user choose the rotation (different if is a combine or a potatoes harvester).

I had one time a problem with this new setting.  My configuration is 3 headlands at the end of the work.  The tractor after finishing the central work of the field join the begin of the headland but with the tools in lower position (work mode)

**Comment by pvaiko** [comment]
@knoxville73 the new Lands pattern should do exactly what you want I guess. Also, the turn maneuvers should work fine in the latest version.
