### ISSUE TITLE
Exit point from field

### ISSUE THREAD

**Issue by HawkPat** [Courseplay/courseplay#3959]
Hi there,
in my opinion it is one of the best moves so far in FS19 mods. Using CP for field work and AD to use the network is awesome.
However, there is one issue I recognized: if I have a driver unloading a combine, he is exiting the field near the starting point of the AD route like setup in AD menu. Just fine. But if I have a CP driver picking up straw/grass or fertilizing he always tries to exit the field to the nearest waypoint, which of course often ends in a collision with trees et cetera. Is that an AD or a CP issue?

**Comment by Tensuko** [comment]
Not sure about that.

@Stephan-S @pvaiko ?

**Comment by pvaiko** [comment]
Could be solved in either AD or CP. The real question is how to define the location of that exit point.

**Comment by HawkPat** [comment]
Well, exiting by the starting point does work for the combine unloading driver. So there has to be already a definition somewhere in your or Stephan-S code :-)
But my guess is that it is AD because as soon as the unloader is full CP is giving it to AD to exit the field.

**Comment by HawkPat** [comment]
So, I thought about that issue again: the combine unloader is working of course because its AD only.
For the other drivers there has to be a conclusion in AD, too, I guess. So I wrote a new issue at the AD github forum.

**Comment by Stephan-S** [comment]
Hey guys,
I just pushed a new release of AutoDrive which includes a new interface function:
'AutoDrive:StartDrivingWithPathFinder'
If this would be called from CP when passing control over to AD, the driver will use the field exit strategy set in the Autodrive menu. So either just use the closest point (as it does now, but without proper path finding), use the start point of the course or use a waypoint some distance behind the start to avoid traffic jams with potential waiting drivers at the start.

@pvaiko I am honestly not sure where or whether to include a 'switch' for users to either make CP call this new function or the standard one. If there are no problems, this should be the new default function and make the other one obsolete, so I guess you could just switch the call in CP and wait for user feedback.

Best regards,
Stephan
