### ISSUE TITLE
Side (body selection) unloading on course

### ISSUE THREAD

**Issue by terrorbaff** [Courseplay/courseplay#3963]
Hello, please Tell me how to pour out on the course with a trailer on which two of the body? Pours only odby body on the course, the second is selected as the unloading side on the "U"button. 
P. S Sorry for my English, used a translator.
![fsScreen_2019_07_13_14_33_16](https://user-images.githubusercontent.com/45336568/61171106-96bc6400-a57b-11e9-9283-3f99af64a5e6.jpg)
![fsScreen_2019_07_13_14_33_19](https://user-images.githubusercontent.com/45336568/61171107-9a4feb00-a57b-11e9-9ff0-8ca2159f362e.jpg)

**Comment by Tensuko** [comment]
I am not sure, but I don't think CP use the selected settings.
Maybe @pvaiko know this ?

**Comment by Tensuko** [comment]
It should be the same problem as the GIANTS Standart Trailer.
No Idea when and how to fix that right now.
Got to wait for it, sry.

**Comment by Tensuko** [comment]
I will comebine this in this Issue: #3060
Closed.
