### ISSUE TITLE
Transfer car

### ISSUE THREAD

**Issue by IcemanGSXR** [Courseplay/courseplay#3964]
The use of course play and transfer car does not work yet? Or do I do something wrong that it does not work?

**Comment by Tensuko** [comment]
Transfer car ?
Wich Mode are you talking about ?

**Comment by Bobster82** [comment]
I think he meant overload mode ;)

**Comment by IcemanGSXR** [comment]
Yes, thank you. I searched for this word. Overload...

**Comment by Tensuko** [comment]
That depends on Mode2 rework.
#3311
Closed.
