### ISSUE TITLE
Combine Harvester leave field

### ISSUE THREAD

**Issue by RUGhost** [Courseplay/courseplay#3965]
If I use "autodrive unload/refill" after 95% full harvester leave the field and drive to the place which is selected in autodrive hud. He doesn't call autodrive unloader. I used CP-236 and AD-3.6

**Comment by Tensuko** [comment]
You don't have to do anything in the Combine. Just Mode2 driver.

**Comment by RUGhost** [comment]
You are right. Thanks.
