### ISSUE TITLE
Field Turning Endless Circle

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3966]
With the latest update, turning in the field with this setup reaches the end of the circular turn where the straight backup line is and then circles endlessly.  doesnt really matter what the turn radius is.

https://gist.github.com/sootysax/169b3dfdb4095d6ef24be9a7bb61c6c1

![fsScreen_2019_07_14_09_18_16](https://user-images.githubusercontent.com/6591048/61184189-d1c0a500-a618-11e9-812e-9b9686fb081e.png)

![fsScreen_2019_07_14_09_16_19](https://user-images.githubusercontent.com/6591048/61184205-0b91ab80-a619-11e9-8836-4d410c637a18.png)

**Comment by pvaiko** [comment]
Yeah, looks like not all implements have AI markers defined, so I use the work area nodes instead.
