### ISSUE TITLE
No stop when the tree planter is empty

### ISSUE THREAD

**Issue by ghost** [Courseplay/courseplay#3967]
Courseplay doesn't detect when the tree planter is empty, it continues without stoping though no trees are being planted.
![treeplanter](https://user-images.githubusercontent.com/47159754/61188010-6a870d00-a679-11e9-9e38-1612ebbbe60b.png)

**Comment by Opa-Andre** [comment]
@mehdinasef Which mode you are using as it can't be seen in your screenshot? Make sure you are using the seeder / fertilizer mode as this happens when using fieldwork mode. I've once had the same issue by wrongly selecting fieldwork mode when using a fertilizer. In fieldwork mode it doesn't stop when getting empty....

**Comment by pvaiko** [comment]
@Opa-Andre according to the icon it is in seeder mode.

@mehdinasef post a log with debug channel 14.

**Comment by mehdinasef** [comment]
here it is
[log.txt](https://github.com/Courseplay/courseplay/files/3398298/log.txt)

**Comment by pvaiko** [comment]
For this log, was it always empty? I only see
2019-07-16 18:31 :51 [dbg14 lp17900] Puma 240 CVX (#2): PL-75: Fill levels: TREESAPLINGS: 0.0/0.0
and was wondering if it reports a capacity > 0 when the fill level is > 0.

**Comment by mehdinasef** [comment]
No, I loaded it with a pallet of trees and ran it until it was empty, then I stopped it.
Do you you want me to do that another way??

**Comment by mehdinasef** [comment]
I think that the problem is that is does not detect the load or when it is full

**Comment by pvaiko** [comment]
Yeah, the stupid treeplanter seems to report 0 capacity.

**Comment by Tensuko** [comment]
I don't rly see a solution for this, as it won't help to increase the capacity in the XML (only gain an additional filltank).
The Trees seems to be handled completely different.
