### ISSUE TITLE
Error: Running LUA method 'update'. - vehicles.lua:899: attempt to index field 'attacherJoint' (a nil value) - Problem with New SYN TRAC tractor

### ISSUE THREAD

**Issue by DrDrulia** [Courseplay/courseplay#3968]
Game crashes sometimes when trying to attach Fertilizer sprayer or even bale collector
MOST important is that dont go on planned route do to this error : 

2019-07-14 22:15 Error: Running LUA method 'update'.
2019-07-14 22:15 D:/FS19MODS/FS19_courseplay6/vehicles.lua:899: attempt to index field 'attacherJoint' (a nil value)

![vehicle lua line 899](https://user-images.githubusercontent.com/47076028/61189411-1da93380-a685-11e9-9f72-bb299707957d.PNG)

![20190709233115_1](https://user-images.githubusercontent.com/47076028/61189369-601e4080-a684-11e9-88f1-eacb5044143b.jpg)

**Comment by Tensuko** [comment]
Full logfile pls.

**Comment by pvaiko** [comment]
@DrDrulia if you can post a savegame on a standard map with everything set up before attaching so we can reproduce the issue then we can look into it.

**Comment by DrDrulia** [comment]
Hello 
I will do it tomorrow.

**Comment by Krahazik** [comment]
I have encountered the same issue. When it happened to me I was hooking upto the towed potato harvester with the 3-point hitch adapter attached. It has been inconsistant with me.
When it happend to me, I was experimenting with the mouse controles for the tractor, and had tried the Left+Right mouse combo control to see if I could figure out what it does. Nothing happened at first and then stuff stopped working. Checking the log showed this error.

**Comment by Krahazik** [comment]
I have game log and save file for you for this one. Setup a test case on a vanilla map with vanilla tools.
[Log File](https://gist.github.com/Krahazik/f9de8ef4dae3c22562348c4bea9a83fa)

I did have a few mods other than Courseplay and Syn Trac installed, but I do not think they were a factor but will list them;
- CoursePlay SIX
- Syn Trac
- PlaceAnywhere
- Placeable Solar Panels
- Workshop Tabber
- Disable Vehicle Camera Collision

The zip file was to big to include as an attachment so I uploaded it to my onedrive directory.
[Savegame folder with mods folder in a zip file](https://1drv.ms/u/s!AqA8n6LMdiWcqZNMJXkKOlLbq3h72g?e=249Nob)

**Comment by DrDrulia** [comment]
I set this up on my work laptop. Just istalled game and course play and syntrac. Game dont crash but save lua error 

[savegame1.zip](https://github.com/Courseplay/courseplay/files/3393990/savegame1.zip)
[log.txt](https://github.com/Courseplay/courseplay/files/3393991/log.txt)

**Comment by pvaiko** [comment]
Ok, folks, I tried both savegames, whatever I do, the entire game crashes during loading, the last log entries about the SynTrac mod loading, so that's it, this won't be fixed for a while...

**Comment by Krahazik** [comment]
I do have another save file well before the error occured. Where I had all of the equipment sitting at the shop still.

For me everything was working fine untill I tried to run a course on field 20, the moment I hit start.

[Savegame before moving equipment from shop](https://1drv.ms/u/s!AqA8n6LMdiWcqZNNXU8_h8XOAkfgTA?e=T7TJTA)
This zip was done before the other zip I did, taken before I had moved any of the mowing equipment or Syn Trac equipment. This one should load, as I had exited the game and reloaded this save myself.

1. What I did was attach both 3-point hitch adapters.
2. Then I attached the mower followed by hooking up to the gather wagon.
3. I drove to my land stopping infront of field 20.
4. I used the route generator to generate a route to mow field 20.
5. Set courseplay to start at the start point.

All was good up to that point. That was where I made my 2nd save, just before starting the mowing operation. Figured that would be good as there did not appear to be any errors going on at that point.
Then I clicked on start driver, and thats when nothing happened. I checked the log and spamming of the nil value error was going on.

**Comment by DrDrulia** [comment]
Hello. Cant close case. You running low graphics on your game and mod crashes game. You need delete transclear. dds file from mod.

**Comment by Krahazik** [comment]
I had to change my texture setting to high to be able to use the Syn Trac, with it set to low the game would crash every time I opened the vehicle in the store.

**Comment by DrDrulia** [comment]
Or delete transclear.dds from mod 


Sent from Mail for Windows 10
