### ISSUE TITLE
Suggestion - Try-or-Die in functions to check for nil values

### ISSUE THREAD

**Issue by Krahazik** [Courseplay/courseplay#3969]
I have noticed a number of errors where a 'nil value' in a variable is causing the script to crash or loop resulting in game crash or freeze. Both myself and looking through the issuess posted by others.

Perhaps a check should be put into place in functions expecting a specific value, a check to make sure the value is not nil and something that is expected. If the check is passed then the function procedes as normal. If the check fails, then a note is logged and the function aborts instead of looping endlessly. In some cases, maybe provide an alert to the player that the action attempted could not be done because of specified issue. IE, can't load the hud, unknown tool attached, unidentified attache point, etc.

Hopefully in this way, if it is just a single vehicle or tool that can't be used, the player can keep playing or whatever without the whole thing comming to a crahsing halt.

**Comment by pvaiko** [comment]
This sounds easier than it really is:
- first of all, CP functions are called by the game engine periodically many times per second. There's no 'looping endlessly'. So if you wanted to log this condition you'd need a proper logging facility (like syslog) which wouldn't log the same message multiple times.
- we try to catch these in the newer code
- some parts (like the course generator) is wrapped in a pcall() to catch these exceptions and report it to the user. There are many places where a pcall() could be added, but our time to spend on CP is limited.
- checking every input parameter is a lot of work
- it isn't always obvious what may be nil and what not
- CP has a lot of legacy code with global variables and insanely long functions with side effects all over the place
- your are more than welcome to open a pull request if you have a good fix for these.

**Comment by Krahazik** [comment]
Thank you for the info. I would if I had any idea for a fix myself, but so far LUA escapes me.
