### ISSUE TITLE
Abfahrer fährt zu schlecht

### ISSUE THREAD

**Issue by C43AMG** [Courseplay/courseplay#3970]
Courseplay entwickelt sich immer mehr zu einer tollen Mod, Dreschen, Feldarbeiten, Überführungen, Verkaufsfahrten laufen tadellos, was mir schon länger ein ganz großer Dorn im Auge ist sind die Abfahrer.

Egal ob man einen Drescher abfährt oder Häcksler oder oder oder die Abfahrer fahren einfach entweder in den Drescher einfach rein, finden Wegpunkte nicht korrekt, erkennt keinerlei Objekte auf dem Feld. 

Es ist doch kein Problem dem Abfahrer zu sagen, warte einfach bis der Drescher weg ist, das steht ja auch im Fenster, aber er macht es nicht, er knallt einfach sinnlos los in den Drescher rein und alles ist versaut, wenn der Abfahrer voll ist merkt er nicht oh da ist etwas im Weg nein er ballert einfach durch, Abfahrer sind eine totaler Schwäche von Courseplay momentan, verstehe nicht warum dazu nie Updates kommen?!

**Comment by iljarogoff** [comment]
Ja, der Mode2 ist fast unbenutzbar, produziert auch öfters Komplettabstürze des Spiels. Aber es wurde ja schon geschrieben, dass daran gearbeitet wird und das es doch aufwendiger ist als gedacht. Soweit ich es verstanden habe, muss der Mode2 komplett neu geschrieben werden.

**Comment by C43AMG** [comment]
> Ja, der Mode2 ist fast unbenutzbar, produziert auch öfters Komplettabstürze des Spiels. Aber es wurde ja schon geschrieben, dass daran gearbeitet wird und das es doch aufwendiger ist als gedacht. Soweit ich es verstanden habe, muss der Mode2 komplett neu geschrieben werden.

Achso echt ja? Das daran gearbeitet wird habe ich wohl übersehen :o ja der ist wirklich unbenutzbar leider!

**Comment by Tensuko** [comment]
> Es ist doch kein Problem dem Abfahrer zu sagen, warte einfach bis der Drescher weg ist, das steht ja auch im Fenster, aber er macht es nicht, er knallt einfach sinnlos los in den Drescher rein und alles ist versaut, wenn der Abfahrer voll ist merkt er nicht oh da ist etwas im Weg nein er ballert einfach durch, Abfahrer sind eine totaler Schwäche von Courseplay momentan, verstehe nicht warum dazu nie Updates kommen?!

Doch ist es, da sich in LS19 viel geändert hat und CP vielen alten Code von LS13 noch hat, wird das meiste neu geschrieben. Für die Kollisionserkennung wird es eventuell demnächst eine Lösung geben. Das wird sich aber nicht auf Mode2 auswirken, da dort noch nicht der AiDriver genutzt wird.
Die Abfahrer sind aus den genannten Gründen die schwäche von CP6 (CP5 für LS17 läut tadellos).
Warum dazu nie ein Update kommt ? Kannst du LUA Scripts ? Dann helf mit. Momentan sind die Devs mit Familie und Arbeit beschäftigt. Es ist und bleibt ein Hobby.

Somit ist das ganze erstmal abgehakt und Updates kommen wenn sie kommen:
#3311 
Closed.
