### ISSUE TITLE
Suggestion: Fertilising & Crop destruction (Not an issue!)

### ISSUE THREAD

**Issue by Derplodactyl** [Courseplay/courseplay#3971]
Hello,

I see a couple of posts with a suggestion tag - hopefully this is ok to post, but feel free to remove if not!

As an idea, I think it could be beneficial that, when using the Seeding and Fertilising mode when creating a course, that the courseplay AI driver will destroy the crops as it drives through them. This would be incredibly helpful in the creation of tramlines for the player to use (similar to a GPS system in a modern machine), as the destroyed crops would allow the player to replicate that same route as necessary for spraying/spreading of fertiliser, herbicide, lime, manure, or slurry.

I have no idea how useful this would be to others, but I feel it could help those individuals who wish to play realistically! :)

Thanks! 
James

**Comment by Tensuko** [comment]
You want to use cp to create a path that you can use manualy ?
I know there are tools that will do it what you want. No Idea if they work with cp.
Buz I dont see the reason to implement that. You could rather use GPS and create it on your own.
Or explain more whats the use of it.

**Comment by Derplodactyl** [comment]
You're correct, would could create such a course with GPS, but I feel that CP will allow a more straightforward course generation method of creating such a route for the player. I do understand what you mean - it does perhaps seem a little backward to use an advanced mod to create a manual path for the player, but I feel it be a nice way for the player to have the option of whether they want to drive the AI created course themselves, which is where crop destruction would assist by effectively drawing out a route for the player.

Like I said, it was a mere suggestion. :)

**Comment by pvaiko** [comment]
@Derplodactyl won't do crop destruction but you can probably use the feature I enabled in 241.
