### ISSUE TITLE
Trucks Cut through field with pathfinding on

### ISSUE THREAD

**Issue by sainsworth97** [Courseplay/courseplay#3972]
My trucks in combine unload mode seem to cut through the crops with or without pathfinding, sometimes resulting in head on collisions with the harvester. I have tried mod/vanilla vehicles and i will say the vanilla avoided the collisions (barely missing front of header) but both wont stay out of the crops, which pathfinding should not allow from my understanding (have not used fs17 version).

**Comment by Tensuko** [comment]
#3311 
Closed.
