### ISSUE TITLE
Combine

### ISSUE THREAD

**Issue by Panthr0** [Courseplay/courseplay#3976]
When I park in front of Combines path to intercept it. The Combine pipe targets the tractors Root instead of the trailers Root. Thus I have to pull forward each time it stops.

**Comment by Tensuko** [comment]
Why do you park in front of the combine ?
Screenshot pls...

**Comment by Panthr0** [comment]
Map: Estancia Lapacho
Fields: 1-8 Combined & Trimmed for simplicity
Tracktors: Valtra-T234 (x3) (Mod)
Seeders: Horsch-Pronto 9 DC (x3)
Fertilizers: Kuhn-Axis 40.2 M-EMC-W(x2)
Harvesters: Case III-9240(x2)
Headers: Case III-3162 TerraFlex Draper 45FT(x2)
Loading Wagon: Krone-ZX 560 GD(x2)
Trailor: Joskin-Drakkar 8600
CoursePlay Version: 6.01.0241
Phase 1: Seed/Cultivate convoy of 3.
                   Only issues is with traffic listener. These will not stop for each other. They will just pile up. (sent of in a timely Fashion works for me).
Phase 2: Fertilize. Convoy of 2
                 Haven't noticed any issues here as they keep apart anyways.
Phase 3: Harvesting. Convoy of 2
                  There has been many issues with the communication between Trailer Driver and     Combine Driver.(To be posted individually For simplicity after I find out if the issue is Code or User error)(I understand CP is in Beta) So I elected to Manually drive the trailer myself.
Reasons to intercept a combine (park in front of one) is to Either A)Make sure first combine is always moving, preventing 2nd combine from catching up. Or B) My trailer is at 80+% and I want to fill it before going to unload point. Or C)Combine is at end of row where it can be unloaded with pipe OUT of fruit side.(I have field destruction off, But seem to keep the practice :p)
![Screenshot 1](https://user-images.githubusercontent.com/53055095/61547448-06fe3600-aa11-11e9-952c-45241f02cde7.png)
![Screenshot 2](https://user-images.githubusercontent.com/53055095/61547483-141b2500-aa11-11e9-92a7-498bd562b37b.png)
![Screenshot 3](https://user-images.githubusercontent.com/53055095/61547498-2006e700-aa11-11e9-916b-3aaeacd7c182.png)
![Screenshot 4](https://user-images.githubusercontent.com/53055095/61547525-2b5a1280-aa11-11e9-8f68-2dd27aaebecc.png)
![Screenshot 5](https://user-images.githubusercontent.com/53055095/61548057-598c2200-aa12-11e9-9f85-0beb38b1e922.png)





Screenshot 1: Combine approaching waiting trailer.
Screenshot 2: Combines stopping point to unload into trailer.
Screenshot 3: Shows why I don't want 2nd combine catching up!
Screenshot 4: Shows my AD Settings.
Screenshot 5: Shows the field currently being worked on in Orange.

I'll post other issues individually. I'm a 1 issue/1 post kinda guy. It makes things easier for the developers.
I hope this information helps. I'll be happy to provide more if needed.

**Comment by Tensuko** [comment]
Why you don't use the Convoy Option when you use 2 Combines on one Field ? So they don't catch up, like in your situation.
AD Settings doesn't help us at all.
Nice big field, but the question is still: Whats the actual problem and what you try to do ? :)

The Communication between Combine and AI Driver I don't know how this is made, as it use AD.

**Comment by Panthr0** [comment]
I have all multi tool setups to run in convoy mode.
![Convoy](https://user-images.githubusercontent.com/53055095/61551811-c7891700-aa1b-11e9-8683-592d3cd01879.png)

**Comment by Tensuko** [comment]
Ah. Okay. But seems like the Trailer is to close to Combine. Maybe that creates this behavior.

Actually the Combine doesnt adjust itself to the Trailer. The Trailer drives under the pipe, unless the offset is wrong. So I don't see the problem in the combine. Try to move the Trailer a bit more away, see where the Combine stops then.

**Comment by Panthr0** [comment]
I have. I've been too far, Too close, Just right. Same effect. If it's not an issue, Close this out. Thanks for your time.

**Comment by Tensuko** [comment]
We got to figure out why that happens. Thats all...

**Comment by Panthr0** [comment]
1) Is combine targeting tractor or trailer?
Lets intercept the combine while facing it. This will invert the tractor/Trailer roots.
![SS6](https://user-images.githubusercontent.com/53055095/61581490-75f88f00-aae4-11e9-9419-828c061ff10b.png)

Combine stops behind trailer (Where tractor would normally be) So its safe to say combine is NOT targeting or being triggered by the tractor.

2)So why does combine stop so far ahead of the trailers center(Root)?
Lets see if Way-points are effecting this. First I will align trailers root equal to a way-point. Then between 2 way-points.
![SS7](https://user-images.githubusercontent.com/53055095/61581502-ab04e180-aae4-11e9-8626-0f4ea939dff2.png)
![ss8](https://user-images.githubusercontent.com/53055095/61581507-b2c48600-aae4-11e9-93e5-399b772d8a91.png)

Here we can see the stopping point hasn't changed. So it's safe to say way points DO NOT effect the outcome.

Is this because the field has been edited?
Lets buy field 9 and harvest it to find out.
![ss9](https://user-images.githubusercontent.com/53055095/61581509-ccfe6400-aae4-11e9-8362-b5f8b1197ddb.png)

This test is showing identical results. So i won't continue as I did earlier. So it's safe to say Edited/Unedited fields doesn't effect this.

So the combines trigger could be set to open to late. Or the stopping point is set to stop too late. I can't test either of these. I'm not sure what else I could do from my end.

**Comment by Panthr0** [comment]
I forgot to mention. I disabled Auto drive mod. So I know that also isn't affecting the outcome.

**Comment by Tensuko** [comment]
Tho I already think I know what happens, a Video would be helpful too.

But when you let the Tracter with Trailer stay there and wait the Combine pass by, the Pipe takes to long to expand while combine continue drives. When pipe is extended, the combine stops, but already moved to far. The Combine got an Area where to detect a near Trailer and as long the Trailer is near enough, the Pipe keeps expanded. Thats what you pics look like. But what is it what you want ? The Combine won't stop on the Center of the Trailer, as the Tracter moves under the Pipe, not the Pipe (Combine) over the Trailer...

**Comment by Panthr0** [comment]
Yes. The combine continues to move until pipe is fully extended. I thought CP determines when the trigger activates and could trigger it sooner. If it doesn't. Then this is something Giants can fix, Not you guys.
Again Thanks for taking the time out. You guys do splendid work. Very prompt too. :)
