### ISSUE TITLE
savegame failed to load - stuck at course management

### ISSUE THREAD

**Issue by mdbguy** [Courseplay/courseplay#3977]
Using 6.01.00241
course_management.lua:118: attempt to index a nil value (log attached)
I suspect this is related to _commit 6.01.00240 Load courses only when needed_
[log.txt](https://github.com/Courseplay/courseplay/files/3407389/log.txt)
[CoursePlay_Courses_FS19_GWExtreme.GWExtreme.zip](https://github.com/Courseplay/courseplay/files/3407398/CoursePlay_Courses_FS19_GWExtreme.GWExtreme.zip)

- sorry there are a lot of mods cluttering the log file. I do not believe mods come into consideration for this issue but will create a new savegame with same map and CP courses if required

**Comment by pvaiko** [comment]
Yes, I need a savegame as this when it loads a course into the vehicle at startup.

**Comment by pvaiko** [comment]
nvm, I just reproduced it with another savegame.

**Comment by pvaiko** [comment]
I think you have a savegame with a vehicle assigned a course which has been deleted.

Still, CP should not freeze the game, I'll fix that.
