### ISSUE TITLE
Text stays on screen(241)

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#3978]
Hi All. 
Close the GUI and text remains on the screen
Thanks
Clive

![image](https://user-images.githubusercontent.com/30005040/61485731-cadbbe80-a999-11e9-9ddf-da369d7cb251.png)

**Comment by eddiem54** [comment]
Settings - Mini HUD - Activated/Deactivated

**Comment by alpha117** [comment]
Thanks...sorry about that
