### ISSUE TITLE
Blue Screen

### ISSUE THREAD

**Issue by thomasglavesb** [Courseplay/courseplay#3979]
Guys,

hope all going well

Look, I am using the FS19_Lehndorf map and when I try to create a course in a large field my computer goes to blue screen and restarts. It has already happened to me above all the big maps that I have tried to use. Is there any solution to this?

thanks

**Comment by Tensuko** [comment]
I doubt that got something to do with Courseplay.
full logfile pls...

**Comment by thomasglavesb** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3409606/log.txt)


It is this file?

**Comment by thomasglavesb** [comment]
Pardon my ignorance.

Look, my computer is only going to blue screen with FS. And only when I try to create courses. That's why I'm consulting

thank you

**Comment by Tensuko** [comment]
FS19_Lehndorf and FS19_SchwatzingenV2SP sounds like maps to me.
Every FS Version got one rule about mods: Only one Map in Mod Folder.
Try remove one Map and get the newest CP Version from here:
https://github.com/Courseplay/courseplay/releases

Try again and report back pls.

Also I guess this is the last entry before the blue screen:

2019-07-19 15:24 Error: 'g0' (g0Shape) doesn't have all required vertex attributes for material 'dosierer_01_mat'. <- @pvaiko you know anything about that ?
2019-07-19 15:25 dataS2/character/crow/crow.i3d (11.11 ms)
2019-07-19 15:25 CourseGeneratorScreen:onCreate()
2019-07-19 15:26 CourseGeneratorScreen:onCreate()
2019-07-19 15:26 Info: Failed to request rc, HTTP code 0
2019-07-19 15:26 Warning: Performing emergency garbage collection pass - memory went from 92819 KB to 249137 KB in less than one frame
2019-07-19 15:26 Usage is now 109693 KB; full GC took 193.796800ms

**Comment by thomasglavesb** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3409819/log.txt)


Hi mate,

I deleted all the maps I have and keep doing the same.

**Comment by pvaiko** [comment]
@thomasglavesb can you activate debug channel 7 before hitting Generate and send that log?

Also, this does not seem to be on the modhub, if that's the case, can you post your field definitions here (as described on the wiki) and tell us which field you have the problem with?

**Comment by thomasglavesb** [comment]
Okay,
I am more than happy to send you information that you request in order to solve the problem. But I'm going to need your help. Could you explain to me step by step what you need? Please excuse me again for my ignorance and been an pain in the ass but I do not understand 100% what you ask me. I hope to learn after this.

  greetings and many thanks

**Comment by Tensuko** [comment]
Go to CPSettings in the CP Hud and turn on DebugChannel 7 (the 7 down there). Then you create the course. That logfile what comes out of it, that we need. For the Field Data, see this: https://github.com/Courseplay/courseplay/wiki

**Comment by thomasglavesb** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3413018/log.txt)

**Comment by thomasglavesb** [comment]
[fs19.zip](https://github.com/Courseplay/courseplay/files/3413035/fs19.zip)

**Comment by thomasglavesb** [comment]
I have problems at the moment with Field 13

**Comment by pvaiko** [comment]
So the logs looks fine, the course generation seems to finish properly. When exactly are you getting that blue screen, you click on 'Generate' and then what happens?

**Comment by pvaiko** [comment]
Course gen does not seem to have an issue with this field:
![image](https://user-images.githubusercontent.com/2379521/61572805-114c1e80-aa69-11e9-8402-99fe5907dd97.png)

**Comment by Tensuko** [comment]
Can you trs this with Version 262 or higher if it still happens ?

**Comment by Tensuko** [comment]
Closed due to inactivity, if still got Issue, post here with V294 and new logfile with debugchannel 7 on creating the course.
