### ISSUE TITLE
Articulated seeders and swinging loading augers

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#3980]
Hi 
I appreciate this is about FS 17 and your probably devoting all time to CP for FS19.
However the problem I have is articulated seeders such as Hatzenbichler Teminator Air Seed Drill or the Bourgalt seeder when I set a drill course and send it on is merry way before they start they swing out the loading auger and open the seed tank lid. The seeders will then begin drilling. If I stop them and close the auger manually as soon as CP is engaged out comes the auger again. I thought it might be the mod but having tried a couple of articulated seeders with the auger it happens with them all.

Any ideas to solve the swinging auger?

Many thanks

**Comment by pvaiko** [comment]
Sorry, FS17 is not supported anymore.
