### ISSUE TITLE
Refill Problem

### ISSUE THREAD

**Issue by RUGhost** [Courseplay/courseplay#3981]
Any seeder which have fertilizer functionality does not refill neither seed not fertilizer. Driver just go to refill point and wait and wait without refilling. 
![Farming Simulator 19 V1 4 0 0 Screenshot 2019 07 19 - 15 31 14 39](https://user-images.githubusercontent.com/48012198/61529234-b30c4500-aa42-11e9-86de-9417971ccc1a.png)
![Farming Simulator 19 V1 4 0 0 Screenshot 2019 07 19 - 15 29 41 16](https://user-images.githubusercontent.com/48012198/61529258-bef80700-aa42-11e9-9598-acc043e2ff43.png)
![Farming Simulator 19 V1 4 0 0 Screenshot 2019 07 19 - 15 32 23 13](https://user-images.githubusercontent.com/48012198/61529259-c0293400-aa42-11e9-8c5d-9d07643034d0.png)
![Farming Simulator 19 V1 4 0 0 Screenshot 2019 07 19 - 15 34 28 85](https://user-images.githubusercontent.com/48012198/61529261-c15a6100-aa42-11e9-9886-64a040200d72.png)

**Comment by jala15** [comment]
This is more an AutoDrive issue than an CoursePlay issue, so you should open it here instead: https://github.com/Stephan-S/FS19_AutoDrive/issues
Anyway, as far as I know, AutoDrive only detects loading triggers when loading the game so if you bought those placeables silos after loading your savegame they wont be detected. Save your game, exit, load your game and try again.

**Comment by RUGhost** [comment]
@jala15 

> Save your game, exit, load your game and try again.

Its working now but another problem appears. You can only load one fill type, not both seed and fertilizer. Driver just fill one fill type and stay idle instead of fill another fill type.
![Farming Simulator 19 V1 4 0 0 Screenshot 2019 07 19 - 20 26 00 90](https://user-images.githubusercontent.com/48012198/61543335-1018f280-aa65-11e9-8faa-a09a24c6723e.png)

**Comment by Tensuko** [comment]
AD Problem. Whrn you use only CP and it works its fine for us...
