### ISSUE TITLE
fs19

### ISSUE THREAD

**Issue by robeman** [Courseplay/courseplay#3982]
the mod shows up in installed.but not in selected mod

**Comment by Tensuko** [comment]
No proper titel, no logfile, get the actual and right version here: https://github.com/Courseplay/courseplay/releases
If still got Issues, create a new titel with logfile as discribed here: https://github.com/Courseplay/courseplay/wiki

Closed.

**Comment by robeman** [comment]
Ok i had the steam dlc check i un check them now it works tvvm

**Comment by robeman** [comment]
![20190722092109_1](https://user-images.githubusercontent.com/11693823/61638994-93566600-ac68-11e9-86f6-1ca08c785fe6.jpg)
![20190722095450_1](https://user-images.githubusercontent.com/11693823/61639026-a6693600-ac68-11e9-8b49-204ea7a0df7b.jpg)
![20190722100144_1](https://user-images.githubusercontent.com/11693823/61639042-b123cb00-ac68-11e9-88a7-067fd73a7f6c.jpg)
