### ISSUE TITLE
Traffic Collision

### ISSUE THREAD

**Issue by MacedonskyAlex** [Courseplay/courseplay#3989]
Vehicle sees an obstacle but doesn't stop
![fsScreen_2019_07_20_17_50_19](https://user-images.githubusercontent.com/52257646/61580141-fb953280-ab16-11e9-87c6-04d70f21d362.png)

**Comment by pvaiko** [comment]
@Axel32019, this is yours.

**Comment by Axel32019** [comment]
Where does the vehicle sees an obstacle?
Do you mean the message "Courseplay: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!..."? This is just an information that a Vehicle or Tool (attached) does not have a collision node defined in its description. For attachments it is not important, for vehicles it is, as they will not have collision handling in that case.
In your screenshot only the attachments are listed, but not the tractor - so no problem.

**Comment by MacedonskyAlex** [comment]
Tractor rides on the field, put in front of him another tractor. The first tractor writes that ahead an obstacle, but does not stop and crashes into the second tractor

**Comment by Axel32019** [comment]
@pvaiko Is there any specific reason why colli is disabled in FieldworkAIDriver:changeToFieldwork() - calls self:disableCollisionDetection() ?

**Comment by pvaiko** [comment]
@Axel32019 I'm not sure mode 4/6 driver need traffic collision while working, if you have multiple vehicles working on the same field then the convoy mode should protect them. Other vehicles on the field (like mode 2) should yield to those working on the field.

But you are more than welcome to enable it if you think it makes sense and are ready to handle issues with it.

**Comment by Axel32019** [comment]
I would give it a chance.
