### ISSUE TITLE
tractor returns to first trigger no matter what setting is used

### ISSUE THREAD

**Issue by prjndigo** [Courseplay/courseplay#3990]
tractors doing field work are returning to the first trigger/start no matter what settings are used, this makes them pile up if you use more than one tractor on the field... if you *disable* "stop at next" then they drive back and forth from corner to corner across the field until they run out of fuel.

you removed this issue when I posted it a month ago WITHOUT FIXING THE PROBLEM

**Comment by Tensuko** [comment]
If Tractor end work at Headlands, it won't return to start.
The Addition on the HUD will be done later.

And I tell you this only once:
Capslock won't help you anything here.
This is not a 'we have to do it'.

**Comment by seeske123** [comment]
prjndigo. Are you paying for this??? Or are people using there spare just for us????I love CP and AD. And thanks for the people behind. Shame to you.

**Comment by FS19-CP** [comment]
It's amazing what people think they deserve, having paid nothing for it...

**Comment by sootysax** [comment]
this is happening for me also, headlands or no headlands

**Comment by Tensuko** [comment]
Hmm okay, I will check that one if I find time for it.

**Comment by Tensuko** [comment]
Conclusion:
- Combine never return to start
- No Headland, will return to start
- Headland 1st, will return to start
- Headland 2nd, will not return to start
- Option for Return to Start yes/no, will be added into the HUD, can't say when.

This was said already, when we removed the option from CourseGenerator.
