### ISSUE TITLE
Problem with Loader-Trailer

### ISSUE THREAD

**Issue by MisterGeniusj007** [Courseplay/courseplay#3993]
I want to load straws!
But even I use a Loader-trailer, the game will freeze
and I get an Error:
2019-07-21 16:08 /***/Courseplay_6_01_00236/helpers.lua:129: attempt to call method 'getName' (a nil value)
2019-07-21 16:08 Error: Running LUA method 'loadTriggerCallback'.

I hope, it is correct to report such an error!
greetings
Yours MG007

**Comment by Tensuko** [comment]
Full logfile, just drag and drop it.
What Loader exactly.

**Comment by MisterGeniusj007** [comment]
[log_courseplay-problem.txt](https://github.com/Courseplay/courseplay/files/3414913/log_courseplay-problem.txt)

**Comment by MisterGeniusj007** [comment]
I know, there is a lot inside! :-)
Only look for the coursplay-errors!

**Comment by MisterGeniusj007** [comment]
https://forbidden-mods.de/filebase/file/6989-strautmann-zelon-cfs-3301-do/#comments
these is the mod which I'm using!

**Comment by MisterGeniusj007** [comment]
now I get the same error with a standard landing-trailer

**Comment by pvaiko** [comment]
Doubt it. vehicle.getName() should work with all standard vehicles and tools.

**Comment by Tensuko** [comment]
Closed due to inactivity, also unclear Issue.
If got more Information, reopen this.
