### ISSUE TITLE
Error: Running LUA method 'update' - mode3.lua:24: attempt to perform arithmetic on a nil value

### ISSUE THREAD

**Issue by raxtor** [Courseplay/courseplay#3996]
Hello,
CP crashes my FS19 after "start course" for my tractor with overloader. I use 2 combines in conwoy mode. Also I am not able set 2 tractors for combine unloading. Tracktors start be stuck, lose speed, lose course and finally crashes game. 1 tractor for 2 combines works OK.
log.txt: https://pastebin.com/AmZcXFFF

**Comment by Tensuko** [comment]
Error: Failed to open xml file 'C:/Users/Charlie/Documents/My Games/FarmingSimulator2019/mods/fs19_tatra_joskin/modDesc.xml'.
Load mod: fs19_tatra_joskin (Hash: 383978671b4be949918fca54daca5e27)
Error: Missing descVersion attribute in mod fs19_tatra_joskin
Load mod: FS19_Terra_Gator_ (Version: 1.0.0.0) (Hash: 1eaadfeed1fadd613db232e6dd6b9e5f)

Error: Failed to open xml file 'C:/Users/Charlie/Documents/My Games/FarmingSimulator2019/mods/grimmeRH2460_OPEN/modDesc.xml'.
Load mod: grimmeRH2460_OPEN
Error: Missing descVersion attribute in mod grimmeRH2460_OPEN

Load mod: HUMMEL (Version: 1.0.0.0) (Hash: c4cc528a8b9cca63d07362abc7790026)
Error: Unsupported mod description version in mod HUMMEL

Again Mode3.lua.... how ???
2019-07-22 18:33 Error: Running LUA method 'update'.
2019-07-22 18:33 C:/Users/Charlie/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00247/mode3.lua:24: attempt to perform arithmetic on a nil value

#3311 ?
@pvaiko How can this happen ?

**Comment by raxtor** [comment]
I used in-game overloader Stara. I assume this one:
2019-07-22 18:24 data/vehicles/stara/ninja19000/ninja19000.i3d (65.12 ms)
- Firstly I tried set 2 tractors with trailer in combi mode... no success as I wrote above. 
- So I tried 1 tactor with overloader in combi mode, which tried fill next tractor in grain transport mode.. not sure how modes are numbered.

**Comment by MacedonskyAlex** [comment]
2019-07-23 22:05 dataS/scripts/AchievementManager.lua(257) : attempt to index local 'farm' (a nil value)
2019-07-23 22:05 Error: Running LUA method 'update'.
2019-07-23 22:05 dataS/scripts/AchievementManager.lua(257) : attempt to index local 'farm' (a nil value)
2019-07-23 22:05 Error: Running LUA method 'update'.
2019-07-23 22:05 dataS/scripts/AchievementManager.lua(257) : attempt to index local 'farm' (a nil value)
2019-07-23 22:05 Application exit request forced.

**Comment by pops64** [comment]
There is a cross over to mode 3 in CombineUnloadAIDriver line 777. Probably was a copy and paste error. @pvaiko I am not sure how mode2 was available to be selected when attached to an augur wagon maybe disable this?

**Comment by MacedonskyAlex** [comment]
Version 244 works stably, the log is clean. All versions above fail
![image](https://user-images.githubusercontent.com/52257646/61893998-1224fa80-af18-11e9-948b-3d7a4a67def9.png)

**Comment by Tensuko** [comment]
Close this couse of #3311 and #4286 
There will be new issue on stuff like that anyway so close this one.
