### ISSUE TITLE
Bale loader has no ai markers or work areas

### ISSUE THREAD

**Issue by SavageMkII** [Courseplay/courseplay#3998]
Hello, I have encountered a problem with automatic bale loaders. When it comes to the end of the lane and turns around, upon completing the turn, it tries to reference the ai markers of the tool, then, since there are none, tries the work areas, which it doesn't have, so gives up. This goes on in a loop, while the driver goes off, usually in a straight line, to nowhere in particular.

I have done some tests, and it appears to be caused by the update to version 6.01.00237 (Mode 4/6 Improvements). Using version 6.01.00236, the bale loader will turn around just fine and continue on the fieldwork course.

Here is my log from a basic test, on Felsbrunn, with only CP version 6.01.00246 in the mod folder. I do have the Anderson DLC active, but I don't think that matters. I activated debug mode 14.

https://gist.github.com/SavageMkII/c6b21928f56c8a40bf23afb68542970e

Also, you will see in the log(lines 890 to 900) that there appears to be an issue with aiCollisionTriggers. CP seems to be searching for the triggers on the trailer(or trailed implement), but of course, can't find any, so throws a warning. I have noticed this happening on many trailers.

Perhaps I should open another issue for this, but there is also a problem with the Anderson DLC bale loaders. When using CP on a fieldwork course, the driver does not lift the arm when the bale loader is full. It leaves the arm down all the way to the unload point(as long as it doesn't hit anything and get stuck), where it will unload, then lowers the platform and the arm goes up into travel position and stays there until the tractor returns to the field course.

These issues are easy to reproduce, but if you need any more info, screenshots, or anything, I will be glad to help any way I can.

**Comment by pvaiko** [comment]
@SavageMkII thanks for the great analysis, I'll look into that. Bale loaders in general aren't AI implements for Giants so I'll see what we can do.

And there's already an open issue for the Anderson baler.

**Comment by SavageMkII** [comment]
@pvaiko thanks for looking into this issue so quickly! I will test as soon as I get the chance.

I was not talking about the Anderson bio baler though. I meant the bale collectors. It's the bale grab arm that does not lift up to travel position when the trailer is full.

I can open a new issue for that if you would like. Let me know.

Thanks!

**Comment by pvaiko** [comment]
#3516

**Comment by SavageMkII** [comment]
Oh okay, sorry about that. Once again, I only searched open issues, so didn't see that one. I can say though that the issue persists with version 246. I will test again tomorrow with the latest version and report in the other thread.

**Comment by SavageMkII** [comment]
@pvaiko the bale collectors are working fine now, for turns, but I just noticed that the Anderson RB580 bale wrapper is having the same issue. When it completes a turn, it starts looking for ai markers or work areas but can't find them, so goes off in a straight line.

I hope that posting in this thread is ok. I would reopen, but can't.

Let me know if you need more info.

Thanks
