### ISSUE TITLE
Problems with headland maneuvers with versions greater than 6.01.00236

### ISSUE THREAD

**Issue by MoslessNeo** [Courseplay/courseplay#4000]
I'm having trouble with headland maneuvers with articulated tractors (BigBud 747 - plow and 450 - planting).
The tractor is spinning in a circle, with 1 or more implements or sometimes it runs away from the route.
This is happening with versions above 6.01.00236
Many problems have been fixed, in planting is not left behind a piece without planting, the loading of the saved courses.
If you need more information, photos or log, I can provide.

**Comment by MoslessNeo** [comment]
The map is the XLFarms X1
The fields are "square".
I simulated with 1 Big Bud 450 tractor and a photo seeder set.
The same problem occurs with the Big Bud 747 with GB arrado.
If you need I test with 2 Big Bud 450
If you need, send the savegame.

[screenshot 1](https://1drv.ms/u/s!AlW6BjVQKGAYgcOHVuivxP5j1qpQaG8)
[screenshot 2](https://1drv.ms/u/s!AlW6BjVQKGAYgcOHV66cLTXCwQfst4E)

Log:
[CP LOG](https://gist.github.com/MoslessNeo/dadc4fec72ef20135d029ca9004ff5f1)

**Comment by pvaiko** [comment]
Is that a standard sowing machine from the game or a mod?

**Comment by MoslessNeo** [comment]
Thank you for your attention.
The mods are originals of the game and the tractor was downloaded from the official FS website.
I noticed that the problem started after v6.01.00237

**Comment by MoslessNeo** [comment]
With original Case IH 620 + original seeder:
[Log](https://gist.github.com/MoslessNeo/1700f97533dc15ff2db35ec889f6aa2a)

[Screenshot](https://1drv.ms/u/s!AlW6BjVQKGAYgcOHWG9fhXNi9Nr6Y3M?e=ByzbbQ)

**Comment by pvaiko** [comment]
Oh, thanks, I think I know what the problem is, I'm not checking the implements attached to another implement, CP does not see the sowing machine, only the tank. I'll fix that.

**Comment by MoslessNeo** [comment]
Glad to be able to help.
But in the case of the GRÉGOIRE-BESSON SPSL 9 + TRAILED LIFTER plow? The same thing happens.
LEMKEN GIGANT 12 S 1600 as well.
Need the log?

**Comment by pvaiko** [comment]
will close once fixed.
