### ISSUE TITLE
Issues with mode2 in 6.01.00240

### ISSUE THREAD

**Issue by HgoDR** [Courseplay/courseplay#4002]
Hello guys, I'm having this problem with CP mode2 where the tractor standby after loading in the combine always stops in a position in front of the harvester route, I've read some old posts about this problem but with no solution. . Is there any configuration to solve this?
![Farming Simulator 19 22_07_2019 12_51_32](https://user-images.githubusercontent.com/53275522/61821307-3d7eeb00-ae2d-11e9-8d49-27be16b59050.png)

**Comment by Tensuko** [comment]
Currently not. #3311 and same Situation as #3985
Mostly this is the Potato Harvester having Problem with the Current Mode2 state I would say.
Closed.

**Comment by HgoDR** [comment]
But the Potato Harvester is not the only one that i have this problem, i have this issue with others harvester too

**Comment by Tensuko** [comment]
This is still a case of #3311 
The Harvester got other Problems as well, thats why I said that.
I will have a check about status of that, but not for the Mode2.
