### ISSUE TITLE
Kipper entlädt nicht

### ISSUE THREAD

**Issue by haamic** [Courseplay/courseplay#4003]
Hallo,
ich hab schon etliche "Kipper" , also LKW mit direktem Aufbau, ohne Anhänger, getestet.
Diese lassen sich bei mir nicht mit CP entladen. Werden zwar machmal befüllt, manchmal gehts aber auch nicht.  aber es funktioniert definitiv kein entladen. Alle getesteten Fahrzeuge fahren durch den Abladepunkt ohne stop zurück zum Start. Fahre ich händisch erscheint auch die  "I...Fruchttyp"-Meldung am Abladetrigger. Woran liegt das?
Gruss Micha

**Comment by Tensuko** [comment]
Von was werden die Kipper gezogen ? GIANTS LKW ? Das Problem ist, dass diese einen versetzten ich nennes es mal Guide-Punkt haben und es könnte sein, dass die so bei dir am Trigger vorbei fahren, durch den Versatz...
Aber da Beladen am Startpunkte auch nicht klappt, nehme ich das mal auf und überprüfe das.

Kommt denn im CP HUD die Meldung 'Abladepunkt erreicht' ?

**Comment by haamic** [comment]
Nicht gezogen. Meinte eben LKW mit kippmulde oder Pritsche. Ich glaub das sind nur mods die ich getestet habe. Sowas gibts glaub ich nicht von Giants. 
Im CP Hud hab ich nicht geschaut ob da eine Meldung kommt. 
Wäre ein Versatz, könnte ich beim eigenhändigen entladen doch auch nicht abladen? Das geht aber.

**Comment by haamic** [comment]
Scheint so als ist das leider ein generelles Problem mit diesem Fahrzeug Typ. Auch mit Autodrive funktioniert das laden und entladen nicht.

**Comment by pops64** [comment]
English please. #4 in the wiki "Write in English. We have users (and developers) from all over the world. And by writing in English, you help them (and us) understand and maybe even contributing to the solution."

Anyways your topic. Dump trucks have never worked with CP and I do not think the code for unloading tippers was adjusted to accommodate this. It has to do with the fact that the vehicle driven is not is not a work tool and when it goes to unload it selects the first work tool available. Which in this case there is none so it does not know to stop to unload or to select the vehicle to unload.

**Comment by Tensuko** [comment]
Versatz im Modellmarker, da gibt es ein Debugchannel für um den anzeigen zu lassen, ist ein gelber Punkt über dem Fahrzeug.
Aber da es eine Mod ist (welche denn?) wird es wohl daran liegen.

@pops64 
they did, in FS17 I got one dump truck, they load (load at start point, wich doesn't work in CP6 for Trucks in any Kinds right now) and unload, even backwards.

**Comment by Tensuko** [comment]
@haamic 
Kannst du mal ein Screenshot davon machen und mir sagen, welches Fahrzeug (Mod) das ist und woher ?

**Comment by haamic** [comment]
Ich habe es nochmal getestet, liegt definitiv z.b. an dem Mod (FS19_ChevyC70_Grain.zip). Andere ähnliche Fahrzeuge/Mods funktionieren, andere wiederum nicht.
Das ist der Mod: https://www.modhoster.de/mods/1977-chevrolet-c70-grain-truck
Beladen wird er am SIlo, aber am Abladetrigger kommt keine Meldung, das die Abladestelle erreicht ist. So stehts auch in den Kommentaren zum mod, das dieser nicht für CP zu gebrauchen ist.
Hab ein video dazu gemacht: https://www.magentacloud.de/lnk/rBiAnK2k
Wie im Video auf der rechten Seite zu sehen, hab ich noch andere Fahrzeuge getestet, diese wiederum funktionierten.
Gruss Micha
----------------------------------------------------------------
I re-tested it, it's definitely the one mod (FS19_ChevyC70_Grain.zip). Other similar vehicles/mods work, others don't.
This is the mod: https://www.modhoster.de/mods/1977-chevrolet-c70-grain-truck
It is loaded at SIlo, but at the unloading trigger there is no message that the unloading point has been reached. So it is also in the comments to the mod that this is not usable for CP.
I made a video about it: https://www.magentacloud.de/lnk/rBiAnK2k
As you can see in the video on the right side, I tested other vehicles, which worked again.
Greetings Micha

Translated with www.DeepL.com/Translator

**Comment by Tensuko** [comment]
Da werden wir dann aber leider nicht beigehen, da es sich nur um eine einzelne Mod handelt, die auch nicht im ModHub ist. Wir haben uns dazu entschieden, bei einigen Mods, grenzen zu ziehen, da es einfach zu viel wird und leider auch jeder sein eigenes Süppchen kocht und sich nicht an GIANTS Standarts hält. Sry, aber da werden wir nichts machen. Gibt es Probleme mit ähnlichen Fahrzeugen aus dem ModHub, melde dich gerne nochmal, dann schauen wir mal rein.

Closed.
