### ISSUE TITLE
Problem with unloading havester

### ISSUE THREAD

**Issue by Molsam** [Courseplay/courseplay#4004]
![Farming Simulator 19 Screenshot 2019 07 25 - 10 47 28 51](https://user-images.githubusercontent.com/53295578/61860316-10344a80-aeca-11e9-9c8f-deaf2e20566e.png)

am i doing something wrong?
It wont emty

**Comment by Axel32019** [comment]
Which CP version do you use?

**Comment by Molsam** [comment]
v6.01.00249.dev

**Comment by Axel32019** [comment]
@Molsam It is difficult to reproduce your situation. Could you please provide some more informations:
- Which map is it, version ?
- Which field No.?
- Which direction the harvester is going on the screen, i.e. S-N, W-O...?
- Where is the end point of the course Tem 41 of the tractor (N,O,W,S)?  Would be helpful if you post a screenshot of the end point to see where it is on the field.

**Comment by Molsam** [comment]
It is Petervill the version 1.0.0.0
It is on every field in every direction, but the one I reported is field 41
the harvester is going from east to west
![Farming Simulator 19 Screenshot 2019 07 26 - 14 51 00 41](https://user-images.githubusercontent.com/53295578/61952706-dc821f00-afb4-11e9-8ee2-b68a87ddc3c3.png)
Thats the pic. of the harvester setup anf i am using number 6 - Fieldwork

**Comment by rgoe** [comment]
Maybe I can contribute to solving the problem with some additional details. I did some testing on standard Ravenport map.
Only 3 mods (Courseplay (*.251), AutoDrive (1.0.3.6) and FollowMe (1.3.0.6)) are in the mod-folder.
Vehicles used are all stock: 
- John Deere 6R + Krampe Bandit 750
- John Deere 7R + Kroeger TAW30
- Massey Ferguson 8700 + Krampe Bandit 750
- Krone BigX1180 + Collect 900-3
- Case IH Axial 9240 + Draper 3162

Setup is mode 6 for forage harvester(field 8)/combine(field 11) and mode 2 for the tractors (although I don't think this is a mode 2 problem)
It looks like the forage harvester and the combine are seen as obstacles/traffic by the unloading tractors as soon as they get close and therefore the tractors stop notifying that they are stuck.
Interesting is - this happens with the 7R and the MF 8700 but not with the 6R - the 6R approaches the combine and the harvester as he is supposed to do.

As far as I can see these problems started after version *.241 - with 241 all tractors approach their combine/harvester.
I made some screenshots in case they're of any help

Full log attached - no hints in it.
[log.txt](https://github.com/Courseplay/courseplay/files/3436196/log.txt)


MF8700:
![fsScreen_2019_07_26_15_50_57](https://user-images.githubusercontent.com/21224499/61959447-b021cf00-afc3-11e9-9701-6f75ba493ab0.png)
6R approaches correctly:
![fsScreen_2019_07_26_15_53_12](https://user-images.githubusercontent.com/21224499/61959472-c2037200-afc3-11e9-82e3-47b64b7566ea.png)
MF8700:
![fsScreen_2019_07_26_15_56_30](https://user-images.githubusercontent.com/21224499/61959527-e3fcf480-afc3-11e9-8d52-2a823bc153c3.png)
7R:
![fsScreen_2019_07_26_16_08_48](https://user-images.githubusercontent.com/21224499/61959554-f414d400-afc3-11e9-9166-db4ab1405a15.png)
MF8700:
![fsScreen_2019_07_26_16_11_05](https://user-images.githubusercontent.com/21224499/61959599-0b53c180-afc4-11e9-8e52-9c349817600e.png)
6R working as it should:
![fsScreen_2019_07_26_16_14_40](https://user-images.githubusercontent.com/21224499/61959620-173f8380-afc4-11e9-97f2-31282819f251.png)

**Comment by Molsam** [comment]
Downloaded 00.253 and the problem is still there and now the tractor says its in traffic when there is nothing in front of it. 
![Farming Simulator 19 Screenshot 2019 07 27 - 13 46 37 14](https://user-images.githubusercontent.com/53295578/61994008-4d890b80-b075-11e9-919f-c351960f2b31.png)

It was when the combine says it needs to be unloaded.

**Comment by Axel32019** [comment]
@Molsam Thanks for that hint - it gives me an idea what condition I can search...

**Comment by Axel32019** [comment]
@rgoe / all: Thanks for your investigations! As long as there is not the message "## Courseplay: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work! ..." in the log all vehicles should operate the same way. The difference in your shown scenarios is the angle the tractors approach to the combine:
1. MF8700: Here I doubt the tractor will manage a turn to get beside the chopper and hence stuck
2. 6R approaches correctly: Here the tractor come the "good" way from the back to the side of the chopper and everthing is fine
3. MF8700: This looks interesting. The tractor seems to detect the yellow box behind the chopper as obstacle and stops. But on other screenshots the tractor does not stop here.
4. 7R: Here it looks like the tractor detects the "AINeedsTrafficCollisionBox"
5. MF8700: Here the tractor "hits" the header of the combine
6. 6R working as it should: As you already mentioned 👍 

At the moment I am working on a 2-part solution:
1. Adapt the collision detection on the distance to the combine to avoid detecting a collission of combine objects like a "very small" back axis (!) when the tractor is approaching -> this is 95% finalized
2. Assign the tractor the combine it is working with as an ignored object, but this becomes more difficult as it migth end up in the following dead lock:
![fsScreen_2019_07_27_23_28_21](https://user-images.githubusercontent.com/52026009/61999797-57d4f500-b0c9-11e9-92a0-5968c458ee13.png)
The tractor is waiting for the combine, but the combine stopped as the tractor is the collission...

**Comment by Axel32019** [comment]
If someone is able to test, please download from the link: [https://github.com/Axel32019/courseplay/archive/e70eb949ac0f69c8f0ab71322d35396f82b43081.zip](url)

**Comment by rgoe** [comment]
@Axel32019 : I was able to do a short test using the same setup described above (leaving the 6R aside as it worked anyway).
It looks as if you found the culprit - pretty good work - the MF8700 and the 7R approach the combine/harvester without any hickups:
![fsScreen_2019_07_28_21_19_51](https://user-images.githubusercontent.com/21224499/62011906-3d5d5300-b17f-11e9-90d3-15e2244e3a11.png)
![fsScreen_2019_07_28_21_19_58](https://user-images.githubusercontent.com/21224499/62011907-3d5d5300-b17f-11e9-9bca-bde6de7e1d77.png)
![fsScreen_2019_07_28_21_25_09](https://user-images.githubusercontent.com/21224499/62011909-48b07e80-b17f-11e9-9a2d-109cfcd84831.png)
![fsScreen_2019_07_28_21_25_20](https://user-images.githubusercontent.com/21224499/62011910-48b07e80-b17f-11e9-895c-69b9e30924b0.png)
![fsScreen_2019_07_28_21_27_38](https://user-images.githubusercontent.com/21224499/62011911-5a922180-b17f-11e9-970f-d5f02c1628d3.png)
![fsScreen_2019_07_28_21_27_41](https://user-images.githubusercontent.com/21224499/62011913-5a922180-b17f-11e9-8ed1-1965365b5731.png)
![fsScreen_2019_07_28_21_27_58](https://user-images.githubusercontent.com/21224499/62011915-5b2ab800-b17f-11e9-8c4d-d830dcb8cc86.png)
![fsScreen_2019_07_28_21_30_48](https://user-images.githubusercontent.com/21224499/62011916-5b2ab800-b17f-11e9-9c43-7e638d490161.png)

**Comment by Molsam** [comment]
Hey Alex. It seems to do the job. Tried on to of the fields i had the problem on and nothing now. The only thing is the tractor sometimes stops in the uncut crops when it has emtyed the combine so when the combine comes back up the tractor is blocking. But thats not a big problem

**Comment by Axel32019** [comment]
Hi @Molsam Thank you for your feedback! The issue the tractor goes out of the field I also know, this is an old behaivior and seems to be deep in mode 2.

**Comment by caplink811** [comment]
Morning gents,

as I experienced, at least nearly, the same problems as desribed above with V601.00256, I tried the version you provided above, and guess what,, the problem seems to be much better now.

The screenshot is from F33 (direction of fieldtracks are n to s or s to n, both directions won't work)
![Saxonia_F33_Mode2](https://user-images.githubusercontent.com/49813958/62409891-364e9e80-b5de-11e9-8456-7af8ef128069.png)
 on Saxonia map, the unload driver worked without problems, but when it comes to the point where he unload the 1st time, and then came back to the field to unload the harvester, he never could reach them, cause of obstacle warning. I tried it with different tractors, but the obstacle warning won't gone. With your version its ok (but now I have a lack of cross points, neither own, nor foreign are visible)

thx 
 JrB

**Comment by Axel32019** [comment]
@caplink811 Thanks for your test! It would be helpful if you create the screenshot(s) with enabled collis - press "F5". In the meantime i fixed some additional issues, which migth be the issue in your screenshot or the direction the tractor is driving to the combine. Please see #4017. This is included in https://github.com/Courseplay/courseplay/releases/tag/6.01.00259

**Comment by Tensuko** [comment]
Is this one fixed as well ?

**Comment by Axel32019** [comment]
@Tensuko Who you are asking?

**Comment by Tensuko** [comment]
Creator of the Issue. If solved for him it can be closed.

**Comment by caplink811** [comment]
morning gents,
as an addional information, with 6_01_00260 it seems that everything works well now, Just tried it on 3 different fields (F1, F11, F13 on Saxonia) with 3 different tractors (Fendt 1050,Deutz 9 FSM and FBM) at the same time, no problem (at least) with any collision issues. The courses are with fieldtracks as well as with headlands in combination.

From my point of view this issue is resolved, but it depends on @Molsam .
 
thank you 
bye
 JrB

**Comment by Tensuko** [comment]
If any more problems I will reopen.
Closed.
