### ISSUE TITLE
Circle pattern

### ISSUE THREAD

**Issue by jobyrns72** [Courseplay/courseplay#4007]
Hey guys I was thinking is suggestion for work mode at least having an option for a circle pattern or basically in theory total headland around the whole field. This works well equipment that are offset  to one side. For some reason I thought there was that option maybe in another fs. I have a pull type forage harvester if I could ever get courseplay to recognize it right I’d like to use that way as I’m speaking of.

**Comment by Tensuko** [comment]
1 Headland arround the Field, should be normal Headland Setting with 1 Headland.
Then you decide your mid pattern. I think we need more details or a graphic or drawing of what you expect.

**Comment by pvaiko** [comment]
@jobyrns72 have you tried setting many headlands, like 20?

**Comment by jobyrns72** [comment]
The forage harvester is only 2.5 m wide lol

**Comment by Tensuko** [comment]
Hmm, use 2 or more in a Convoy ? :)

**Comment by jobyrns72** [comment]
Here’s with 50 headland passes lol

**Comment by Tensuko** [comment]
F12 for a Screenshot, wich are in ...\Dokumente\My Games\FarmingSimulator2019\screenshots

But I don't see a solution for it, when your work width is so smal and your field that big.
What pattern does help make it faster. The only way I see is use more tools at one course...

**Comment by jobyrns72** [comment]
It’s not the point of faster or the size of it the point Is suggestion. Many implements are offset to one side and you can’t go back and forth unless you want to run over your crop. In the field center where you have the spiral and racetrack options it would be nice to have a circle option that basically goes round and around

**Comment by pvaiko** [comment]
@jobyrns72 got it, will implement it, this has been requested before.

**Comment by jobyrns72** [comment]
This can be a work around for this #3674 until it able to swing left and right to go back and forth correctly

**Comment by SteelRodent** [comment]
AI Vehicle Extension for FS17 did spiral modes. Granted that mod works very different from CP, but especially with the potato harvesters that have to be emptied every 300 meters it's just a lot easier running around in a spiral than going up and down.

RL I've seen farmers cut down the middle of the field and then work their way outwards from the middle (so the pipe is always in the clear part). Could be an alternative to the spiral that may work better with how CP functions now.

**Comment by WhiskeyBravo813** [comment]
Yes, an outside-in spiral would be one option, and an up-down-inside-out as another.

**Comment by ffbhallman** [comment]
Could you just create an option for a circular pattern for the whole field?

**Comment by pvaiko** [comment]
I think with the Lands pattern for the center of the field most of this problems should be solved or at least have a workaround.

**Comment by jobyrns72** [comment]
The only problem with this is the attached combines can’t make the turns at the end and just stay stuck. I’m using the pottinger mex6
