### ISSUE TITLE
Häcksler Feldarbeit mit Anhänger nicht möglich

### ISSUE THREAD

**Issue by Hyrcleon** [Courseplay/courseplay#4008]
Sobald ich meinen Häcksler los schicke, bleibt die Kamera und das gesamte HUD hängen, der Häcksler fährt los, aber nicht auf dem Kurs und häckseln tut er auch nicht.

Courseplayversion: 6.01.00252.dev
Log habe ich gekürzt, die Fehler wiederholen sich, sodass ich innerhalb von 3 Minuten in Game über 400000 Zeilen Log (40MB Textdatei!) erzeugt habe.... 
[logSend.txt](https://github.com/Courseplay/courseplay/files/3435625/logSend.txt)

![2019-07-26 13_43_58-Farming Simulator 19](https://user-images.githubusercontent.com/53340164/61950149-4d253d80-afad-11e9-866a-b5dd3ce96736.png)

Map: FS19_Przemasowo v1.0.1.0
HäckslerMod: John Deere 8000i Paket Fixed v1.0
LadewagenMod: Krone ZX 430 GD v1.0.0.0

**Comment by pvaiko** [comment]
Dem Häcksler fehlen die AI Markers, geht wahrscheinlich mit dem Giants Helfer auch nicht. Bitte wieder öffnen wenn mit standard Tools reproduzierbar.

**Comment by Hyrcleon** [comment]
Ja ist korrekt - Giants helper gehen nicht. Komisch nur, dass ich diesen Häcksler vor einigen Courseplay versionen noch fahren lassen konnte mit Courseplay -  da hat nur das abladen oder parken nicht funktioniert.

Wie sehen die **AI Markers** in der mod xml aus?

**Comment by pvaiko** [comment]
`    <ai> 
       <areaMarkers leftNode="aiLeftMarker" rightNode="aiRightMarker" backNode="aiMarkerBack"/>
        <collisionTrigger node="aiCollisionTrigger"/>
    </ai>
`
![image](https://user-images.githubusercontent.com/2379521/61958155-6e266800-af86-11e9-8dae-88bf776c2230.png)
