### ISSUE TITLE
Abholer steckt im Verkehr fest ohne hindernis

### ISSUE THREAD

**Issue by Hyrcleon** [Courseplay/courseplay#4009]
Map: FS19_Przemasowo v1.0.1.0  
Courseplayversion: 6.01.00252.dev  

Seit den letzen Updates habe ich vermehrt probleme bei meinen abholern, diese bleiben "im Verkehr" mit den Dreschern hängen.

Der 1050 bleibt ohne ersichtlichen grund mitten auf dem Feld hängen.
![2019-07-26 14_44_23-Farming Simulator 19](https://user-images.githubusercontent.com/53340164/61955622-b1e79480-afbb-11e9-9730-030bd033d8c7.png)

Meine Fastracks bleiben immer hängen, wenn Sie eigentlich ein Stück rückwärts zur Warteposition fahren sollen. Entlasse ich den fahrer, bis der Ernter gedreht hat und stelle ihn wieder ein, klappt alles wieder.
![2019-07-26 15_38_18-Farming Simulator 19](https://user-images.githubusercontent.com/53340164/61955631-b4e28500-afbb-11e9-826f-cfd4a9fa8d76.png)
![grafik](https://user-images.githubusercontent.com/53340164/61955655-c3c93780-afbb-11e9-8a10-9763f9754314.png)
[LogFastTrac.txt](https://github.com/Courseplay/courseplay/files/3436006/LogFastTrac.txt)

**Comment by pvaiko** [comment]
@Axel32019 bitte.

**Comment by Tensuko** [comment]
Wenn es Probleme mit der Kolli gibt, sind Screenshots mit F5 recht hilfreich, oder @Axel32019 ?

**Comment by Axel32019** [comment]
Das würde mir sehr helfen!

**Comment by Hyrcleon** [comment]
bin neu hier... bitte erläutern wie ich euch helfen kann. Mit F5 macht er entweder keine Screenshots oder ich weiß nicht wo ich die finde...

**Comment by rgoe** [comment]
Looks like it's related to or the same as #4004 .
@Hyrcleon: Tensuko was asking to take the screenshots as usual (pressing print) but with the collision-/trigger-wireframes turned on by pressing F5 once. Just have a look over at #4004 to see some examples.

**Comment by Hyrcleon** [comment]
ok, nothing will turn on by pressing F5... i'll check my keybindings and will try to post a screenshot asap

**Comment by rgoe** [comment]
Maybe you need to turn on developer controls:
- Browse and open Documents/My Games/Farming Simulator 2019.
- Open the file “game.xml” and at the very bottom you will see “development” "controls" change it from "false" to "true". After that the e.g. pressing F2 should show the FPS.

**Comment by Hyrcleon** [comment]
The Fasttrac starts to reverse and stops at this position.
![fsScreen_2019_07_27_00_00_27](https://user-images.githubusercontent.com/53340164/61984122-52ad7280-b003-11e9-86c7-28e7e2474318.png)
![fsScreen_2019_07_27_00_00_35](https://user-images.githubusercontent.com/53340164/61984124-53de9f80-b003-11e9-9fda-8816cc387103.png)

**Comment by Tensuko** [comment]
Guess it is the pipe. I know that from other tools in fs17 with to big vehicles.
But we will see whats possible.

**Comment by Axel32019** [comment]
@Tensuko From my perspective the root cause(s) is / are the same like #4004. I suggest to work only with #4004.

**Comment by Tensuko** [comment]
Das ist wohl auch nicht gewollt...
![fsScreen_2019_08_03_12_13_22](https://user-images.githubusercontent.com/27344744/62410609-3358ab80-b5e8-11e9-9f7c-7315d583633b.png)

**Comment by Axel32019** [comment]
@Tensuko Das liegt an einer vorher detektierten Colli, siehe #4017. Sollte mit https://github.com/Courseplay/courseplay/releases/tag/6.01.00259 nicht mehr auftreten.

**Comment by Tensuko** [comment]
Ok schaue ich mir an und teste das hiervmal, dann mache ich zu wenns passt.

**Comment by Hyrcleon** [comment]
Mit 260 tritt der Fehler bei mir nicht mehr auf. Von meiner Seite aus kann das Ticket geschlossen werden.

**Comment by Tensuko** [comment]
Ok dann mache ich den zu.
Danke @Axel32019 für den fix!
Closed.
