### ISSUE TITLE
courseplay doesnt stop on trigger to unload milk.

### ISSUE THREAD

**Issue by shadow250** [Courseplay/courseplay#4010]
this might be due to the fact there is no liquid transport mode as yet. anyway i tried using grain transport mode and it does list milk as something to load which it does but at the unload trigger it just drives on by. it does see the trigger. i tried using the unload marker on the create course window but that makes it stop way before the trigger the crossing icon is ignored and the wait point just makes it stop until i do something. 

NOTE: upon further testing i removed the bucket loader with silage in it for added weight. and now it works as expected. sorry for being a bother.

**Comment by Tensuko** [comment]
Yea, some Transportation gets problems with other loadable tools.
Its ok, good for finding it out yourself.
Closed.
