### ISSUE TITLE
unload trailer cuts off combine

### ISSUE THREAD

**Issue by shadow250** [Courseplay/courseplay#4011]
when the unload trailer in mode2 unloads on the fruit side it speeds ahead and crosses in front of the combine causing an accident. also none of the tractors stop or slow for things in their path and just keep trying to go on collision.

ps, this mod is great overall and i thank you for your work on it :D

**Comment by Tensuko** [comment]
#3311 
For Mode2, Collision detection isn't fully working as I know.
Sry!
Closed.
