### ISSUE TITLE
Pull type harvest

### ISSUE THREAD

**Issue by jobyrns72** [Courseplay/courseplay#4012]
Hey guys I’m trying to get my pull type silage harvester (http://www.fs19mods.com/new-holland-900-mod/?fbclid=IwAR2AWdmmCDuFZgpG2tyUMQr3zBHdUT_Md8fsbn3XeMB-5VoamwBl-Tq75q0)(url) to work with field mode correctly. I tried this https://github.com/Courseplay/courseplay/issues/2462 but still didn’t have the combine call page

**Comment by jobyrns72** [comment]
![image](https://user-images.githubusercontent.com/4283225/61966893-881d7600-af99-11e9-841a-52625a6e0097.jpg)

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki
F12 = Screenshots
As for me, we won't support Mods from that Modsource.
If you got a Mode2 Driver, you can assign it to the tool, if the tool is listed as a Combine.

**Comment by jobyrns72** [comment]
I can assign a driver to the tool but that’s not a problem.  It won’t unfold which I knew it wouldn’t with out some work so that’s what I’m trying to figure out the special tool. Here’s the original link sorry about that. https://www.dropbox.com/s/fiysxi71w9840hg/FS19_NewHolland900_TrailedForager.zip?dl=0&fbclid=IwAR2r1sVkbdHz5VtmAbAO7NIMJlQa1SXCFgb395nGMMwyjwYxEkIFJiuUXn0

**Comment by Tensuko** [comment]
It is not about the download source, more about where the mod come from, but anyway, dev decided to not support this mod. (Unless you get one from ModHub)
If you can reproduce this with vanilla Harvester, we will check on that Issue.

**Comment by jobyrns72** [comment]
Lol that’s alright I’ll figure it out somehow was just looking for some insight but thanks anyways
