### ISSUE TITLE
Front and back markers are reversed Spirit R 300S

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#4013]
The markers on the spirit R 300s are reversed. It lifts the tool when the trailing edge of the work area hits the edge of the field and lowers it at leading edge. Probably not the only tool will test more

![fsScreen_2019_07_26_16_57_24](https://user-images.githubusercontent.com/10678220/61981098-a9e12200-afc6-11e9-90a2-b7ae20a13bd9.png)
![fsScreen_2019_07_26_16_57_50](https://user-images.githubusercontent.com/10678220/61981100-ab124f00-afc6-11e9-8715-0c8bc2ce1fe1.png)

**Comment by pvaiko** [comment]
They are not reversed, this is how it works now to make sure everything is covered for example with multiple implements, sprayers or plows.

**Comment by pops64** [comment]
It is a change from previous version of CP. Plows were covered with my GUI option. And everything else didn't have an issue. If it did this fix is just masking a deeper problem but it is now your show so.
