### ISSUE TITLE
Courseplay for FS19 v6.01.00253 - reversing problem with weight (and other implements with no work areas)

### ISSUE THREAD

**Issue by Bartalos** [Courseplay/courseplay#4014]
Hi,

would like to report an issue when tractor is cultivating with Rau polymag 300 after end of the row it turns properly, then as he starts to reverse towards the edge of a field it wont stops and it reverses infinitelly .

This issue was non existent in v 238 for example and worked properly.
Hopefully this report will help

**Comment by alpha117** [comment]
Morning Guys, I'll add to this one with 'turn on Field', activated/deactivated; not sure if this is working correctly. No matter what is selected it will still reverse off of the field, even with the correct number of headlands done first. I'm currently on Greenwick Valley  and trying to either plow or seed fields #32 and #33, completing the headlands first then it will reverse sometimes forever at the end of the turns when on the up/down route. headlands no issues at all. 

Thanks

**Comment by alpha117** [comment]
Just gone back to #238, I can also confirm that with #238 it is PERFECT on both fields at Greenwick Valley, turn on field works as it should, with no overrun when reversing.

Thanks

**Comment by pvaiko** [comment]
Folks, I can't reproduce it. I need a savegame on a standard map.

**Comment by alpha117** [comment]
Pvaiko, do you want a savegame with #253 or #238. I'll do one on Greenwich Valley

**Comment by alpha117** [comment]
[savegame1.zip](https://github.com/Courseplay/courseplay/files/3438133/savegame1.zip)
attached is one with #238

**Comment by alpha117** [comment]
[savegame1.zip](https://github.com/Courseplay/courseplay/files/3438137/savegame1.zip)
This one is with #253 where it reverses forever, again just replicated it again, when testing #253 for this savegame

**Comment by pvaiko** [comment]
There's no Polymag in this savegame (the second you sent)

**Comment by Bartalos** [comment]
Here you go sir 
[savegame15.zip](https://github.com/Courseplay/courseplay/files/3438157/savegame15.zip)

**Comment by alpha117** [comment]
oooh..no Polymag..not sure if that is good or bad to be honest :-)

**Comment by alpha117** [comment]
what is a Polymag...sorry if I should know this

**Comment by pvaiko** [comment]
@alpha117 the original issue was about the Polymag cultivator.

**Comment by alpha117** [comment]
Ok, I have the same issue and I do not have this equipment, sorry about the confusion

**Comment by pvaiko** [comment]
Sorry guys, I screwed this up, this is an issue with any tool if you have a weight attached to the front, will fix it soon.

**Comment by alpha117** [comment]
phew, I thought it was me that caused the confusion..many thanks as always

**Comment by Bartalos** [comment]
roger that. thank you

**Comment by pvaiko** [comment]
Reopen if this is still an issue.
