### ISSUE TITLE
Stop at Last Waypoint or at Next Trigger

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#4015]
I'm on #238 due to issue #4014, if this option is deactivated, then tractors just goes on a drive around randomly when the course has been finished and ends up crashing somewhere. Not sure if this is just in #238 and has been fixed in the latest version. Could someone let me know

Thanks

**Comment by pvaiko** [comment]
Stop at last waypoint is automatically activated when you start the fieldwork as I'm not aware of any use case where someone would want to restart working on the same field again. So you must have deactivated it during the work, what are you trying to accomplish by deactivating it? You don't want the vehicle to return to the first point?

**Comment by alpha117** [comment]
Hi Pvaiko, no was just testing to see what would happen if  that function was deactivated.

**Comment by pvaiko** [comment]
Now you know :)

**Comment by alpha117** [comment]
yep, thanks

**Comment by alpha117** [comment]
Tested and work perfectly...many thanks
