### ISSUE TITLE
CP6.01.00251/CP6.01.253 - can't see any foreign cross-, start- or stoppoints

### ISSUE THREAD

**Issue by caplink811** [Courseplay/courseplay#4016]
with the latest versions I can't see any foreign cross-, start- or stoppoints. Only the one from my loaded course. And yes, the flag in the UI is ticked in both cases.
With CP6.01.00234 I could see other crosspoints(start- stop as well), so I could use those for adding new courses.

Myself assuming, that behaviour is an impact of the new "loadtechnic" (load courses only when there is a need for that course).

**Comment by caplink811** [comment]
works like expected, thx

**Comment by pvaiko** [comment]
@caplink811 see the release comments for 286

**Comment by caplink811** [comment]
nice feature, thanks for that :-)
