### ISSUE TITLE
vehicle drives only with 10 km/h - Mode2 only (?)

### ISSUE THREAD

**Issue by spiessphilipp** [Courseplay/courseplay#4017]
my tractors and combines only drive 10 km/h even if he is able to drive faster. If i change the settings to maximum speed its the same.

**Comment by Tensuko** [comment]
All repaired ?
Wich Mode ?
What are they doing ?
Logfile ?
Maybe a Screenshot ?

**Comment by Hyrcleon** [comment]
same here - but not on every route and tractor.
![fsScreen_2019_07_28_00_18_53](https://user-images.githubusercontent.com/53340164/61999992-6f15e180-b0cd-11e9-8c8d-cedfba0831a0.png)
![fsScreen_2019_07_28_00_19_15](https://user-images.githubusercontent.com/53340164/61999993-6f15e180-b0cd-11e9-9d83-4e1c490d99f3.png)

**Comment by raxtor** [comment]
I mentioned it earlier in #3996... Its Combi mode problem when course uses 2 or more vehicles...

**Comment by raxtor** [comment]
Respective problem is same also for 2 different courses but both are using same field for combine search

**Comment by iljarogoff** [comment]
Mine too... constantly accelerating and braking like a weird.

**Comment by Tensuko** [comment]
In wich Mode they do it ?
Every Mode ?
I need all conditions listed pls...
If it only happens when 2 or more on the same course in Mode2, then you know whats the problem.
Is it every Mode, but only when 2 or more Vehicles ? Then we got to check on that...
It must be reproducable guys...

**Comment by iljarogoff** [comment]
It happened so far only on Mode2 for me, but it's a very fresh bug. A versions earlier that issue didn't happen, even with "not working" Mode2.
Trying to reproduce is hard, after restarting savegame, it works. Will try to get a log.
Did unloading of a field chopper, while driving to unload it's ok, but when driving to Silo, it bugs sometimes.

**Comment by raxtor** [comment]
Easiest way how to reproduce it:
Set course for Combi mode. Set 2 tractors to that course. Sit to combine with Field work and start combine course and tahn manually call unloader.. Problems will start soon..

**Comment by Tensuko** [comment]
So it only happens in Mode2 right ?

**Comment by raxtor** [comment]
Yes.

**Comment by iljarogoff** [comment]
> 
> 
> So it only happens in Mode2 right ?

For me, as far as I could see, yes. Haven't had the issue in other modes yet.

**Comment by Tensuko** [comment]
I guess it could be a combination of the collission detection change and the ild cp driver of mode2... Will make some test to try to find out. If any of you find out more, pls let us know.

**Comment by BambuleBernd** [comment]
I have the same problem.
If I do it the way like Raxtor explained a few minutes ago, the two tractors run well till unloading each of them the first time. After that point the unloaded tractor slows down and often stucks in traffic whitout an obstacle in his way.
Additionally the hud disappears sometimes.

**Comment by Tensuko** [comment]
HUD disappear is mostly a sign of a lua error. If that happens, can you attatch your logfile ?

**Comment by raxtor** [comment]
Yes, collision warning is active too sometimes, but there is no vehicle around. 
I think that HUD error and game freezing were fixed.. didnt find it already from versions 252 or higher... but for sure wait for @BambuleBernd confirmation if he is using latest version...

**Comment by BambuleBernd** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3439428/log.txt)

**Comment by BambuleBernd** [comment]
![Abfahrer mit Häcksler](https://user-images.githubusercontent.com/53407041/62011017-0a14c700-b173-11e9-81f4-af34014c3806.jpg)
![Abfahrer Beladung am Startpunkt](https://user-images.githubusercontent.com/53407041/62011020-0b45f400-b173-11e9-9300-9378d100e58c.jpg)
The first picture shows mode 2 after unloading the first time with "stuck in traffic".
After that I choose mode 2 and the tractor was driven by ai without a problem.

**Comment by raxtor** [comment]
Also u can fix it for a while when you clear assigned combine to tractor.. but usually it will stuck second tractor soon.

**Comment by BambuleBernd** [comment]
I tried again, but I can´t reproduce the disappearing hud. It happens sporadically.

**Comment by iljarogoff** [comment]
> 
> 
> HUD disappear is mostly a sign of a lua error. If that happens, can you attatch your logfile ?

This is a general problem of Mode2

**Comment by iljarogoff** [comment]
The problem with the unloading driver started with some changes in collision detection and/or aidriver, maybe since 249?

**Comment by Tensuko** [comment]
This one is weird:
@pvaiko know anything about this?
2019-07-28 18:58 Error: Running LUA method 'mouseEvent'.
2019-07-28 18:58 C:/Users/The Go-Kackjens/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6/settings.lua:248: attempt to index field 'cp' (a nil value)


2019-07-28 19:10 Error: Running LUA method 'draw'.
2019-07-28 19:10 C:/Users/The Go-Kackjens/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6/AIDriver.lua:611: attempt to index field 'course' (a nil value)

**Comment by BambuleBernd** [comment]
I tried the version 247 and it´s the same result. I started with the Case 7250 and the problem began immediately. I didn´t need to fill and unload the trailer like I had to with the version 253. 
CP could drive another tractor with a trailer to the forage harvester, but after getting filled this tractor got the same problem, too. The log-file shows only the Case 7250 - error.
[log.txt](https://github.com/Courseplay/courseplay/files/3440994/log.txt)
"2019-07-29 10:09 ## Courseplay: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work! vehicle 1100
2019-07-29 10:09 ## Courseplay: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work! vehicle Big Body 900 S
2019-07-29 10:09 data/shared/ai/trafficCollision.i3d (25.38 ms)
2019-07-29 10:09 dataS2/character/humans/player/player02.i3d (329.60 ms)
2019-07-29 10:10 Info: Failed to request rc, HTTP code 0
2019-07-29 10:10 ## Courseplay: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work! vehicle 1100
2019-07-29 10:10 Error: Running LUA method 'update'.
2019-07-29 10:10 C:/Users/The Go-Kackjens/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6/PurePursuitController.lua:309: attempt to index field 'course' (a nil value)
2019-07-29 10:10 Error: Running LUA method 'cpOnTrafficCollisionTrigger'."

**Comment by iljarogoff** [comment]
Maybe FYI: Tested unloading field chopper with multiple drivers on .238 and there I don't have this issue

**Comment by Tensuko** [comment]
So same situation and with 238 it works and 239 doesn't ?

**Comment by iljarogoff** [comment]
> 
> 
> So same situation and with 238 it works and 239 doesn't ?

Not tested yet with .239 but will go on testing to find out what version starts to bug here

**Comment by spiessphilipp** [comment]
Problem fixed oneself after a restart. It only appears in a new savegame that wasn restarted.

**Comment by iljarogoff** [comment]
OK, after some testing, I figured out that since .250 this issue happens. With .249 it was the last version that was ok. It is not reproduceable one shot, the unloaders have to do some turns from field to silo until the bug happens. Beginning with getting stuck where nothing is in the way until it accelerates and brakes constantly and driving with 10 km/h

**Comment by Tensuko** [comment]
6.01.00250 Traffic collision improvements and fixes

**Comment by BambuleBernd** [comment]
I could reproduce the problem with version 247 in Geiselsberg-Map today with standard-tractors.

**Comment by iljarogoff** [comment]
> 
> 
> 6.01.00250 Traffic collision improvements and fixes

That was my guess :)

**Comment by BambuleBernd** [comment]
Later today with version 253 I set the Case 7250 and the Deutz 6.61 in mode 2 to the same combine harvester Case 9240.
When the Deutz began to struggle, I set him on a new course with another combine harvester Ideal 9 and struggling was over.

**Comment by iljarogoff** [comment]
Have the issue with .249 now too... what a mess

**Comment by BambuleBernd** [comment]
Did someone set two tractors on different courses but to the same harvester?
Otherwise I would test it tomorrow morning.

**Comment by iljarogoff** [comment]
> 
> 
> Did someone set two tractors on different courses but to the same harvester?
> Otherwise I would test it tomorrow morning.

Not yet... please try it 👍

**Comment by raxtor** [comment]
yes, same trouble.. its related to scanned field and combines on that field. No matter from which course. When 2 or more mode2 vehicles scan same field for combines and are attached to combines, than trouble starts... it has something to do with combine attaching to vehicles in mode2.

**Comment by iljarogoff** [comment]
Ok... I did again a lot of testing. I can reproduce now on a savegame. With .244 the issue happens, with .242 it is ok. .243 is not available...? So I can't test it. So it has to do with the changes made from 242 to 244.

**Comment by Tensuko** [comment]
242: 6.01.00242 Avoid crash when loading a savagema with a non existing co… 
Then: improvements of traffic collisions (3975) 
243: 6.01.00243 Traffic collision improvements (3916)
244: 6.01.00244 Bale loader moves forward after unloading
245: 6.01.00245 Don't start chopper until pipe is discharging to trailer

Source: https://github.com/Courseplay/courseplay/commits/master

I would still say, something with Traffic Collission, still under some tweaking.

**Comment by iljarogoff** [comment]
Ok, I hope I did help you guys a little bit

**Comment by raxtor** [comment]
> Problem fixed oneself after a restart. It only appears in a new savegame that wasn restarted.

I can confirm that for 256 version.. all what u need is save game and reload that save game.. after that this bug  disappears.

**Comment by raxtor** [comment]
Here is log with channel3 dbg, hope it helps finally..
https://pastebin.com/1cyxm6d0

**Comment by Axel32019** [comment]
If you want to test it, feel free: https://github.com/Axel32019/courseplay/archive/bugfix-4017.zip

**Comment by raxtor** [comment]
@Axel32019 hi there, I tested it right now and all seems good...2 tractors in mode 2 and no troubles after 3 unloadings...
I have big request yet.. now when we havnt mode3 yet is there no way how to use grain cart. There is possible workaround. Earlier was possible mode2/combi for grain cart, which could dump cargo to truck in mode1/grain transport. Is there any easy way how to take grain cart as classic trailer till mode3 will be ready. In latest versions is not possible use graint cart anyhow with CP... thx for collison fix!
