### ISSUE TITLE
The baler does not remove the baler. Collaborate with AutoDrive

### ISSUE THREAD

**Issue by MacedonskyAlex** [Courseplay/courseplay#4020]
The baler does not remove the baler. Collaborate with AutoDrive
![fsScreen_2019_07_29_00_26_18](https://user-images.githubusercontent.com/52257646/62013188-dc8e4480-b197-11e9-844e-53a8bcc3b553.png)

**Comment by Tensuko** [comment]
Does CP folds the collector and AD unfolds it again ?

**Comment by MacedonskyAlex** [comment]
No. He's coming from the field in this condition. Doesn't even try to work out.

**Comment by Tensuko** [comment]
Ah okay I know what it is. CP gives control to AD at a to early point, we have some similar issue somewhere, not sure if I find it somewhere.

**Comment by Tensuko** [comment]
Does this still happen with actual CP and AD Version ?

**Comment by Tensuko** [comment]
Closed due to inactivity.
If there are more Issues with not folding tools when use CP+AD, lets us know in a new Issue.
