### ISSUE TITLE
Zuckerrohranhänger werden nicht entladen

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#4021]
Habe gerade versucht, mit dem Randon Zuckerrohrtransporter zu arbeiten. Er wird einwandfrei beladen (Mode2) aber nicht Entladen im Silo. Liegt wahrscheinlich daran, dass der Anhänger "in der Höhe" gekippt wird und dafür anders angesteuert wird (also nicht mit "I". Wäre es möglich, CP beizubringen, auch solche Anhänger zu entladen?
![fsScreen_2019_07_29_18_29_59](https://user-images.githubusercontent.com/21023840/62065558-8a98fd80-b22f-11e9-9145-3089165eb417.png)

**Comment by Tensuko** [comment]
Sollte in der 6.4.0.5 jetzt drin sein, da wo auch Schaufelpositionen gespeichert werden.

**Comment by Tensuko** [comment]
Vertan, ist noch nicht mit drin...
