### ISSUE TITLE
Bale collectors and wrappers turns broken again

### ISSUE THREAD

**Issue by SavageMkII** [Courseplay/courseplay#4022]
Hello again,

It seems that with version 255(possibly 254), bale collectors and wrappers, upon completing a turn, are trying to reference aiMarkers or workAreas, and go off in a straight line to nowhere. Could be because of the 254 update to ignore implements with no work areas on turns, since bale collectors and wrappers have no work areas.

Log: https://gist.github.com/SavageMkII/2aa19962f7c2849e9aa84d31f7031a60

This log is from my regular save game, with lots of mods, but I can test with a clean save if you think it would help. I have been playing on this game without having this problem since @pvaiko fixed it originally with versions 248 and 253. I just updated to 255 this morning.

Anything else you need, just let me know.

Thanks!

**Comment by pvaiko** [comment]
Damn, I keep breaking those bale loaders/wrappers :(

**Comment by Tensuko** [comment]
Try with 256 or higher and report back.

**Comment by SavageMkII** [comment]
Tested and all is working perfectly again. Thanks @pvaiko and @Tensuko!
