### ISSUE TITLE
After last update ignore implements  - No Capslock allowed -

### ISSUE THREAD

**Issue by DrDrulia** [Courseplay/courseplay#4023]
After last update ignore implements - No Capslock allowed - Greetings, Tensuko

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
@pvaiko turn problem with fertilizer sprayers

**Comment by DrDrulia** [comment]
i tried all

![round](https://user-images.githubusercontent.com/47076028/62079988-ab6d4d00-b247-11e9-99c3-c56201f3e316.jpg)

**Comment by pvaiko** [comment]
Not sure what 'fertilizer sprayers' are we talking about. What I tried all work fine.

**Comment by DrDrulia** [comment]
Big Brute, that’s New Holland in a picture, teragator, case.
That’s post from Facebook 
Github. Just did an update yesterday and still having vehicles just turning in circles, vehicles crossing in front of the combine after loading and vehicles not finding the combine. I have tried using it after removing all other mods with just the regular game and still have the same problem, so it couldn't be a mod conflict.

**Comment by Tensuko** [comment]
'That’s post from Facebook Github' 
???

'vehicles crossing in front of the combine after loading'
#3311 

What about a logfile ?

**Comment by pvaiko** [comment]
Can't do much with this until we get a proper bug report.

**Comment by DrDrulia** [comment]
Recreated on different PC Big brute looks like its working now but not Millew-New Holland and Teragetor
Link for mods from my Drive: https://drive.google.com/drive/folders/1r9gI0-q8Wo2UwsLaOQ6hZgMpwnFDaUEh?usp=sharing
Save game 
[savegame2.zip](https://github.com/Courseplay/courseplay/files/3447651/savegame2.zip)


[FS19_Welker_Farms.SampleModMap.zip](https://github.com/Courseplay/courseplay/files/3447628/FS19_Welker_Farms.SampleModMap.zip)


[teragator](https://user-images.githubusercontent.com/47076028/62145073-c04eec80-b2ea-11e9-9fba-71ee0cdc8ad0.jpg)
![miller new holland](https://user-images.githubusercontent.com/47076028/62145074-c04eec80-b2ea-11e9-9a4c-5f9a804f665a.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/3447619/log.txt)

**Comment by DrDrulia** [comment]
https://github.com/Courseplay/courseplay/files/3447619/log.txt

**Comment by pvaiko** [comment]
Need a log with debug channel 14.

**Comment by DrDrulia** [comment]
ok where I can find this ?

**Comment by Tensuko** [comment]
CP HUD Settings, down there are Numbers. With the Arrows up and down next to it, you switch the Debugchannel Pages.
Turn on Channel 14 (lights up green), then you reproduce it with channel 14 on and post the logfile. (drag and drop log.txt into comment box)

**Comment by Tensuko** [comment]
Closed due to inactivity, reopen if we get the logfile with debugchannel 14 active as I discriped above.
