### ISSUE TITLE
CP folds cotton harvesters when not empty

### ISSUE THREAD

**Issue by SteelRodent** [Courseplay/courseplay#4024]
CP 255

When done work, CP folds up the cotton harvesters even when they're not empty, which causes the models to glitch out because (since 1.3) it's not supposed to be possible to fold them without unloading them first. 

Basically CP needs to either check if the machines are empty before folding them up, or it needs to just not fold them and leave it for us to decide. Also folding them up if we're going to take them to another field is honestly a bit silly, so I think the best option is to just not fold (just like the combines aren't folded when done).

When driven manually the Case can only be folded when it's less than half full (believe it's actually <40%), but the new John Deere cannot be folded at all when it contains any amount of cotton. And currently there's no way to fully empty the JD (because Giants left out the option to manually dump the precompress chamber into the bale chamber) so it's actually not possible to fold it back up unless it's completely empty, which is rarely likely to happen.

**Comment by pvaiko** [comment]
Is this something new with 255?

**Comment by SteelRodent** [comment]
I'm pretty sure it's not new to 255, but I haven't been using the cotton harvesters with CP for a long time because it didn't work properly for a while and I only just got the JD cotton DLC a few days ago. I have seen with previous CP that it will fold the Case, but haven't noticed before that it doesn't always do it properly, so don't know if that's new or not.

**Comment by SteelRodent** [comment]
Just tested with the John Deere baler ... after CP has folded it up with a partial bale inside, I tried to unload the "unfinished bale" in this state, but the bale was offloaded underneath the machine and disappeared under the ground surface.  Yet to find a way to recover that bale.
