### ISSUE TITLE
When DBG course is displayed brings FS to a slide show(#256)

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#4025]
When the DBG course is shown on screen, FS becomes a slide show and is not usable. Displaying the 2D course no issues.
Gone back to #254 and all is perfect again, when the DBG course is displayed

Thanks

Clive

**Comment by pvaiko** [comment]
@alpha117 do you think a log would help?

**Comment by alpha117** [comment]
Rgr that..sorry about that

**Comment by alpha117** [comment]
[log.zip](https://github.com/Courseplay/courseplay/files/3447377/log.zip)

Log attached.   I think it has to do with the number of 'vertices' in the course, the more vertices that needs to be displayed the more resources are used, a very big field with a very short width implement will generate far more vertices than if a wider implement was used. You would only get this I think on the large field US maps. I've raised this as I have never seen this issue with FS19 or back with FS17.  
Thanks

**Comment by alpha117** [comment]
it might be something just to be aware of. I'll do some more testing on some US maps that have the larger fields and use a small implement and let you know what happens. If that is the case I'm not sure if there is anything that can be done to be honest
Thanks

**Comment by pvaiko** [comment]
@alpha117 thanks, got it, I thought it is due to some error, that can slow things down, but this looks more like a performance problem. The reason you did not see it that DBG was not enabled in the previous versions. Won't fix.
