### ISSUE TITLE
The Tractor won't move after unloading at the semi

### ISSUE THREAD

**Issue by moose31608** [Courseplay/courseplay#4026]
Once the Auger Wagon Unloads into semi it just seat there

**Comment by pseikoNL** [comment]
@moose31608
http://courseplay.github.io/courseplay/en/faq/index.html

**Comment by Tensuko** [comment]
There are several Issues about Auger Wagon already, some are closed due to #3311 (Mode3 related) and some are just not on priority yet. If everything works fine without it, Its not an important Issues yet.
I still will talk to dev about it.
