### ISSUE TITLE
Seit v245 stotternde Fahrt beim Feldhäckseln

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#4027]
Seit .245 fährt der Abfahrer besonders, der Feldhäcksler aber auch, sehr unruhig, stotternd. Beim Abfahrer wechselt die Geschwindigkeit im Millisekundentakt zwischen 5 und 15 km/h.
Getestet mit dem Krone BigX und Fendt1050 mit Krone Ladewagen.
Werden log und debug channels benötigt?
Die Ursache liegt evtl darin:
> 6.01.00245 Don't start chopper until pipe is discharging to trailer
> Fixes #3574, chopper waits until pipe is turned towards the trailer. <

**Comment by Tensuko** [comment]
Das ist durchaus gewollt, nicht das stottern, sondern die Funktion.
Denn: Egal ob ein perfekter Mode2 oder manuelles Abtanken vom Häcksler.
Beim Start und jedem Wendemanöver, startet der Häcksler zu früh, und nimmt die ersten Meter mit, ohne das etwas im Trailer landet. Du könntest auch lange hinterher fahren mit einem gewissen abstand, dein Feld wird leer, aber nichts landet im Trailer.
Ich würde mal versuchen, den Abstand zu verringern in den Einstellungen.
Ansonsten ist das jetzt ein Problem von #3311 würde ich mal behaupten.

Ich werde bei gelegenheit aber nochmal ein paar test machen, ob man da noch etwas dran drehen kann...

**Comment by Th301** [comment]
Kann das Problem bestätigen. Ist erst neu seit einem der Updates. Habe den New Holland Häcksler und verschiedene Wagenkombinationen zum Abfahren versucht. Alle stottern und teilweise wird der Wagen nur bis 99% voll und danach sagt der Häcksler, er steckt im Verkehr fest. Der Abfahrer fährt nicht ab und der Häcksler nicht weiter.

**Comment by iljarogoff** [comment]
@Tensuko 👍  ok, alles klar. Die Funktion ist ja durchaus sinnvoll, hab das oft genug erlebt, dass dann reichlich Häckselgut verloren ist, lieber gehts dann ein bisschen langsamer. Werde das mal mit dem Abstand versuchen.

**Comment by Tensuko** [comment]
Ok ich habe mir das mal eben schnell angeguckt und das Problem erkannt.
Erstmal: es passiert nicht immer, aber wenn man genau hinschaut, sieht man, was passiert.

- Häcksler fährt erst los, wenn Häckselgut auch im Trailer landen kann
- Traktor fährt mit gleicher Geschwindigkeit, wie Häcksler
- Traktor 'schwingt' scheinbar etwas über einen Punkt, wo der Häcksler abladen kann
- Häcklser will für einen sehr kurzen Moment stoppen, fährt aber dann doch weiter, weil er wieder abladen kann
- Traktor macht diese Bewegung verzögert mit, Traktor 'stottert'

Man sieht diese Beobachtung beim Häcksler ganz gut und es handelt sich hier auch nur um einen kurzen Moment.

@pvaiko würde dir da ein debugchannel außer 9 12 und 14 helfen ? Fasl da etwas machbar ist ?

**Comment by pvaiko** [comment]
Ich kann da nicht viel machen, das muss auf der Abfahrerseite gelöst werden.

**Comment by iljarogoff** [comment]
Jap, denke auch dass es genau so ist. Evtl einen größeren Toleranzbereich zulassen?
Das Feature, welches mit .245 eingeführt wurde, müsste da evtl etwas angepasst werden?

**Comment by Tensuko** [comment]
Es müsste halt etwas 'weicher' gefahren werden beim einhalten der Geschwindigkeit, aber das ist #3311 
Kommt mit auf die Liste Teambesprechung...

**Comment by Th301** [comment]
Das Problem ist nicht vom Mode 2. Das Problem besteht genauso, wenn man manuell neben dem Drescher herfährt!

**Comment by Tensuko** [comment]
Kann ich nicht bestätigen.
Video ?

**Comment by Th301** [comment]
Ich schaue, ob ich morgen ein Video machen kann. Es liegt noch genug auf dem Feld ;)

**Comment by Dome328** [comment]
Ich habe das selbe Problem, aber in .288.
Habe mehrere Häcksler und Anhänger ausprobiert. Wenn ich den Häcksler über CP fahren lasse, besonders beim PickUp, stottert der Häcksler extrem. Er fährt teilweise nurmit 6 km/h anstatt der Höchstgeschwindigkeit von 17 km/h. Allerdings läuft nur der Häcksler im CP und ich fahre selbst den Abfahrer. Sobald auf dem Kurs aber ein Stück ohne Schwad kommt, wo normalerweise welcher liegen würde, beschleunigt der Häcksler sofort auf Höchstgeschwindigkeit.

**Comment by Th301** [comment]
Ich komme leider aktuell nicht dazu ein Video zu machen.

Aber bei mir war es die gleiche Situation wie bei Dome328. Habe auch versucht mit einem Häcksler (New Holland) mit dem Pickup Grasschwaden aufzunehmen. Beladen wollte ich den Holmer Selbstfahrer mit dem Überladesystem drauf. Der Häcksler ist manchmal, so wie Dome328 auch schreibt, losgeheizt und dann zappelt die Geschwindigkeit wieder bei 3-5 km/h rum, obwohl ich selbst den Abfahrer gefahren habe.

@Tensuko : Evtl. ist es wirklich spezifisch beim Aufnehmen von Grasschwad mit einem Häcksler? Hast du es damit schon probiert?

**Comment by Dome328** [comment]
Dafür hab ich mal eben ein Video gemacht.

[CP_Video.zip](https://github.com/Courseplay/courseplay/files/3529209/CP_Video.zip)

**Comment by Tensuko** [comment]
Existiert das Problem noch ?
Ich habe Rückmeldung von einigen, dass es keine Probleme mehr gibt.

**Comment by Tensuko** [comment]
Sollte gefixt sein, mache heir zu....
