### ISSUE TITLE
Meadows

### ISSUE THREAD

**Issue by Bartalos** [Courseplay/courseplay#4029]
Hi,
I would like to propose a suggestion.

Currently, courseplay wont recognize meadows, not even in manual mode.
From one simple reason it would be nice if courseplay could do this.
Fields with grass looks very ugly compared to meadows.

Would this feature be possible ?
thx. Vlad

**Comment by Tensuko** [comment]
Can't.
CP uses Fielddata to create courses.
On some Maps, Mapper been so smart and put Fielddata for their meaows, so you can load them like a simple Field.
What else you can do is, create a course that surrounds your meadow, like you want it. Start and End Point have to be near to get a good Field Border.
Save that Course as you like, e.g. Meadow_Border01.
When you are in a Tractor with a mower or anything, load that Border Course and get into the generator, at the top, there should be the option for 'current loaded course' as the selected Field. Now just create your course as you are used to it, CP takes the Border from your course and not the FieldData. But Note, if you want to make changes, you got to load the Border course again, else he tries to make a course in your generated course (if that is even possible...).

Try out and report, closed.
