### ISSUE TITLE
seasons game crashes

### ISSUE THREAD

**Issue by killallaround** [Courseplay/courseplay#4030]
my game seems to crash with seasons running I have run it on the base map and moded map?

**Comment by Tensuko** [comment]
This is a Courseplay GitHub, not an any Mod GitHub.
If you don't bring a logfile with clear Error that shows a modconflict between CP and Season, then you are wrong here.

Create a new Issue with a proper titel, just liked discribed here unless it got nothing to do with CP: https://github.com/Courseplay/courseplay/wiki

Closed.
