### ISSUE TITLE
LUA call stack bei version _00256

### ISSUE THREAD

**Issue by klauskleber14** [Courseplay/courseplay#4032]
Hallo Zusammen,

ich bekomme neuerdings beim start eines Savegames LUA call stacks angezeigt. Dieses Problem besteht schon seid der version _00253 hatte allerdings gedacht das es bei einer neueren Version weg ist.

Das Problem tritt bei mir bei den Standart Maps und auch bei verschiedenen Mod Maps auf. Allerdings ist das Spielverhalten trotz der fehlermeldung normal.

Ich habe die komplette log beigefügt.

[log.txt](https://github.com/Courseplay/courseplay/files/3456148/log.txt)

Wäre super wenn mir jemand helfen könnte.
Vielen Dank schonmal

**Comment by Tensuko** [comment]
Kann jetzt nicht direkt erkennen, ob das an CP liegt.
Taucht der Fehler auch auf, wenn du kein CP im Mod-Ordner hast ?
Wie ist das mit Season ja/nein ?
AD + Season ?
Ich weis nicht, was Season alles mit den Fahrzeugen macht, da war ja auch eingriff in die Abnutzung oder sowas, wenn ich mich nicht irre...

**Comment by klauskleber14** [comment]
Danke schonmal für die schnelle Antwort.

Ich habe gerade nochmal ein paar Tests gemacht.
Wenn ich Seasons oder Autodrive aus dem Ordner entnehme, ändert sich nichts. 

Habe dann jeden mod seperat hinzugefügt und getetstet und dabei festgestellt das es an einer von mir veränderten Version des Fliegl BPT Pack liegt. Mit dem originalen Fliegl Pack taucht der Fehler nicht auf.

Somit liegt das Problem bei mir und das Thema kann wieder geschlossen werden
trotzdem Vielen Dank für die Hilfe
