### ISSUE TITLE
when using Väderstad Tempo L 16 it tells me: load first, but it's full loaded already

### ISSUE THREAD

**Issue by geo-luchs** [Courseplay/courseplay#4035]
Hello
I'm playing LS 19 with CPsince several months. It's a very useful addon. Thanks for your effor.
But now I've problem when using Väderstad Temp L 16

I'm using an Claas Axion 960 +  Väderstad Temp L 16

It's full with seed and fertilizer, but when trying to start CP for seeding, it tells me I've to fill it first

in logfile found 

2019-08-03 18:20 :08 [dbg17 lp108410] Tempo L 16: setFoldedStates()
2019-08-03 18:20 :08 [dbg17 lp108410] startAnimTime=nil, turnOnFoldDirection=nil, foldingPartsStartMoveDirection=nil --> realUnfoldDirection=-1
2019-08-03 18:20 :08 [dbg17 lp108410] 	foldingPart 1: isFoldedAnimTime=16000 (normal: 1), isUnfoldedAnimTime=0 (normal: 0)
2019-08-03 18:20 --------------------------------------------------
2019-08-03 18:20 :08 [dbg17 lp108410] Tempo L 16: isFolding(): realUnfoldDirection=-1, turnOnFoldDirection=nil, startAnimTime=nil, foldMoveDirection=nil
2019-08-03 18:20 :08 [dbg17 lp108410] 	return isFolding=true, isFolded=false, isUnfolded=true 

please have a llok on it.
Thanks.

**Comment by Tensuko** [comment]
That Axion is from ModHub ? Temp L 16 is Vanilla one ?
A full logfile is always helpful https://github.com/Courseplay/courseplay/wiki

**Comment by geo-luchs** [comment]
sorry
I tried it now with no other mods loaded 
I'm using CP .256
It's the original Väderstad Temp L 16.
Claas Axion 960 is a downloaded mod, I can't remember from which location I downloaded, there are several possibilities :-(

But I can say: the problem only occurs with this vehicle. I tried it with vanilla ones from LS 19 itself, and the problem doesn't occurs. Also I've donlowaded a Fendt within LS19 modhub, and it works fine


Here is my logfile  with debug mode 17 activated
[log.txt](https://github.com/Courseplay/courseplay/files/3464162/log.txt)

**Comment by Tensuko** [comment]
So it only happens with Axion ?

**Comment by Tensuko** [comment]
> 
> 
> @ashmills158 your issue seems to be related to that Claas Axion tractor which reports no DEF (AdBlue) and no air. Can you reproduce this with a standard tractor?

From #3866
It should be the Axion. (Wait for Platinium Addon :) )

**Comment by geo-luchs** [comment]
error not repdocucable with other tractors.

it seems, that there are different mods for Claas Axion 900  in the web are available  with the same name FS19_CLAAS_Axion_900.zip
my  was version 1.0.0.0, but contains Claas Axion 960.
Now I found another zip file (https://fs19.net/farming-simulator-2019-mods/tractors/claas-axion-900-by-smety/) but it doesn't contain 960.

this is not showing this error message, but it's driving without seeding and giving fertilizer.
Without CP it's seeding normally.

I think, it's really better to wait for Platinium

Sorry, for wasting your time
