### ISSUE TITLE
Full trailer crashing to combine

### ISSUE THREAD

**Issue by raxtor** [Courseplay/courseplay#4037]
When a trailer is unloading a moving combine and the combine empties and trailer is not full, tractor waits for cleared waiting point.
But when the trailer gets full while unloading, the tractor/trailer will cut right into the combine to head for the unload route.

Another trouble I have with headland or when pipe side is over crop and combine is full. In that case combine makes maneuver to clear place for tractor and waiting for him. Its ok but after unloding combine crashes into tractor when is going back to original track, cuz tractor has collision with combine header. There should be some reverse maneuver for tractor or combine should go stright for a while yet after unloading.

**Comment by Tensuko** [comment]
#3311 
Closed.
