### ISSUE TITLE
Bale unloading

### ISSUE THREAD

**Issue by ice81rm** [Courseplay/courseplay#4038]
Hello everyone ... my problem is that when I go to unload the bales, the first unloading does it to the right point, but at the second unloading it makes it to the same point of the first ... without stopping a few meters before ...

Fabio da Roma

**Comment by Tensuko** [comment]
That normaly should work and the meters that can be set, are on additional iffset, at least I understood it like that in CP5. I will have a look at that.

**Comment by pvaiko** [comment]
CP6 is looking for bale objects when reversing and stops if one found.

**Comment by Tensuko** [comment]
Even Smarter... I will check later...

**Comment by ice81rm** [comment]
> CP6 sta cercando oggetti di balle durante l'inversione e si ferma se ne trova uno.

**Comment by ice81rm** [comment]
> CP6 sta cercando oggetti di balle durante l'inversione e si ferma se ne trova uno.


I did not understand, sorry .. my problem has been solved or is it in the testing phase?

**Comment by Tensuko** [comment]
CP6 see the bales and unload infront of the bale stack.
I will try it later, if that works or whats wrong.
