### ISSUE TITLE
Speed problem krone 1180 at work

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/courseplay#4040]
Hello,

I'm using the .259 version and I'm experiencing a speed problem with the Krone 1180. The problem was the same with the .256 version
At work, it rolls between 5 and 8 Kms / h while I wish it to advance to 18 km / h
Attached, my log

https://gist.github.com/Crinouche/0e57202490b0325570dc167f3ccda180#file-log-txt

![image](https://user-images.githubusercontent.com/36656729/62421858-17690e80-b6a9-11e9-8bf4-6b4d955f767f.png)
![image](https://user-images.githubusercontent.com/36656729/62421861-2ea7fc00-b6a9-11e9-9e24-7a36831c455d.png)

**Comment by EsbenHoue** [comment]
Ive noticed same problem. what fixed it for me was that there wasnt enough grass on the field. Try to mow the field two times before collecting

**Comment by Crinouche** [comment]
Sorry EsbenHoue, but your solution, which I tested, does not solve the problem.

**Comment by pvaiko** [comment]
Does not seem to be a CP problem, you can see in the log that CP is setting the speed to 18 km/h.

**Comment by raxtor** [comment]
I had similar problem with rented vehicles... repair fixed it..

**Comment by Tensuko** [comment]
Just tested it and it works pretty fine.
Even together with Mode2... Full 20km/h

**Comment by Crinouche** [comment]
Sorry, but for me, it doesn't work.
I removed all the mods, I repaired all the vehicles, but the problem remains the same:
The selected speed flashes and the Krone 1180 rolls between 5 and 10 km / h.

**Comment by Crinouche** [comment]
I tested this morning with Rostselmash and NH 780 on the RAVENPORT map and the problem is the same.
This problem only occurs with forage harvesters equipped with Easy flow 300S or NH 300FP that collect grass or hay.
There is no problem with corn collectors.

In addition, the EF300S and the NH 300FP do not open automatically at the start of the course ...

**Comment by pvaiko** [comment]
Isn't this the same as #4027?

**Comment by pvaiko** [comment]
Who is driving the tractor? You? CP? Autodrive?

**Comment by Crinouche** [comment]
I don't know if it's the same problem as # 4027? I have trouble translating German. Even with google translate.

Everything is managed by CP. tractor + forage harvester.
I can't understand what is my problem???

**Comment by Crinouche** [comment]
Hello,
I tested all previous versions of CP
I think that my problem has appeared from version 6.01.00243 or higher and that it is a problem of collision with the grass, because when there is no grass in front of the machine this one rolls well at the right speed

**Comment by Tensuko** [comment]
So you think when the grass is to much ? I will test that...

**Comment by Tensuko** [comment]
![fsScreen_2019_08_06_09_31_51](https://user-images.githubusercontent.com/27344744/62520229-6cce2880-b82d-11e9-90f2-34ac0401be21.png)
![fsScreen_2019_08_06_09_31_39](https://user-images.githubusercontent.com/27344744/62520230-6d66bf00-b82d-11e9-88d9-6c4b07c60a10.png)
I already doubt it is a grass Problem.
It works very good with V262
You use any Mod or something for that?

**Comment by Crinouche** [comment]
Hello,
As I said before, I removed all the mods and repaired all the vehicles. I have to test again, but I still have my problem.
I'm desperate.
Thanks anyway for trying to help me.

**Comment by Tensuko** [comment]
Well there must be a reason why it does this and it would be good to find out why.
What I noticed is, that CP doesn't unfold the EasyFlow, had to do it manualy.
But I haven't touched any other options in CP.
Maybe you did something I haven't done, like fill level or something.

**Comment by Crinouche** [comment]
Hello,

My problem is solved.
With the new versions everything works fine.
Thanks for your help.

**Comment by Tensuko** [comment]
Ok, closed.
