### ISSUE TITLE
Planters always need to be refill on version 6.01.00259

### ISSUE THREAD

**Issue by Kartikai** [Courseplay/courseplay#4042]
Any planters ask to be refill on course start and won't run.
<img width="1280" alt="issue-planter-6 01 00259" src="https://user-images.githubusercontent.com/21087377/62425219-b2acb480-b6a6-11e9-9c82-078e59bc4da6.png">

**Comment by Tensuko** [comment]
Its the Axion.
See this for more Info.
#4035
