### ISSUE TITLE
Hud will not close anymore ! cant change hud opening setting

### ISSUE THREAD

**Issue by D3ltorohd** [Courseplay/courseplay#4043]
I start a new game, and click the right mouse button on an tractor (Fend Favorit 515c original), after that i have no mouse for this tractor anymore, i cant click on cp and i cant close the hud, also not with strg+entf.

When i switch to another tractor it works. But when i switch back to this tractor the hud is still there. so i save the game close ls and start it again, load the save and switch to the tractor, and the hud is directly shown without trigger something.

The next thing, i cant change the setting for opening the hud.

here is the log file

[log.txt](https://github.com/Courseplay/courseplay/files/3465162/log.txt)

**Comment by Tensuko** [comment]
you got 2 CP Versions in Mod Folder:

Load mod: Courseplay_6_01_00248 (Version: 6.01.00248) (Hash: 477bc8b9f47c53690e2de686f3982db2)
Load mod: Courseplay_6_01_00259 (Version: 6.01.00259) (Hash: 145af0d418ffead5e0c3e219f7e2a1a9)

I give you a tip:
Whenever you downloaded a new CP Version, rename the .zip to FS19_Courseplay or FS19_Courseplay6 if you like, so this won't happen.


Just a sidenote:
Load mod: FS19_ITS_SynTrac (Version: 1.1.0.2) (Hash: 3f47d5babf495d4b7ddb4875136522d3)
Not working with CP (at least not the 1st version, didn't try the new one)... or did you try it again and now it works ?

**Comment by D3ltorohd** [comment]
Yes, omg im so sorry. Normaly when i download a new version i search for the old one and then i delet it. But for now, i maybe have forgot an older version. After that it works all fine now. Sorry. So we can delet this issue because it is not an issue. Maybe there are some issues with my eyes :-)

**Comment by Tensuko** [comment]
I guess it is solved then.
Closed.
