### ISSUE TITLE
Harvester signals slipping at the end of row

### ISSUE THREAD

**Issue by Exeria** [Courseplay/courseplay#4044]
Using using version 259, Map: Michigan Farming, Equipment: MF Activa 7347 S with header for canola. Has happened in multiple feilds. Does not happen every time. Slipping can last for a few seconds to a few minutes but harvester always starts going again without intervention.

**Comment by Exeria** [comment]
![20190804112500_1](https://user-images.githubusercontent.com/34689372/62427722-08d02680-b6ac-11e9-9ed9-b72f0c1d2741.jpg)

**Comment by Tensuko** [comment]
This is just a message and comes from old Mode2 if I am not wrong.
You can ignore this, as it got no influence on anything, sure it is irritating, but nothing to worry about.
Duplicate and Similar to #3048
Closed.
