### ISSUE TITLE
Unloading Harvester Issue

### ISSUE THREAD

**Issue by Exeria** [Courseplay/courseplay#4045]
version 259, Equipment: John Deere 6541 M, MF Activa 7347 S. Map: Michigan Farming. My previous problem has been fixed with the new update, however a new one has come up. In instances where the harvester has its pipe in fruit it backs up from the crop making room for the tractor and tipper. The issue im having is when they finish unloading both pieces try to continue their courses at the same time. This means that the harvester is turning left while the tractor is turning right, causing them to collide and try to carry on. I recieve no red text above the map in the lower left when this occurs.
![20190804115406_1](https://user-images.githubusercontent.com/34689372/62428259-6ff1d900-b6b4-11e9-98e9-324aab5d0f08.jpg)
My 2nd issue is also when the harvester moves over when the crop is to its left. When the tractor with the tipper is coming to the harvester from the front it is given a waypoint that is directly behind the harvester resulting in the tractor just running into the harvester
Also would like to just say thank you guys for making this mod. I love it and some of the more realistic things your trying to put into it. Such as the harvester moving over when its pipe is in the fruit.

**Comment by Tensuko** [comment]
#3311 
Closed.
