### ISSUE TITLE
Nor turning on implement (Fert)

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#4046]
Hi All,

CP does not turn on this implement(FERT), you have to manually turn it on before starting the course.  Apart from that all good. Turns it off when empty and goes onto the refill course, then goes back to field course, lowers it OK, but does not turn it on.

Thanks

![image](https://user-images.githubusercontent.com/30005040/62454738-c6bae980-b76c-11e9-9b66-d72b0f014b8e.png)

**Comment by pvaiko** [comment]
Does it work with the Giants helper?

**Comment by alpha117** [comment]
I'll test and let you know..standby

**Comment by alpha117** [comment]
No, same issue; but one thing I did notice is that the 'helper' turns a lot quicker when at the end of a row and turning around. CP turns 3mph  the helper turns a 6mph, and reasons for that?

Thanks

**Comment by pvaiko** [comment]
@alpha117 so that seems to be a Giants issue. The speed is a different story, closing this here.
