### ISSUE TITLE
Abfahrer Kolidieren beim Abfahren mit Drescher

### ISSUE THREAD

**Issue by pulimatrix** [Courseplay/courseplay#4047]
Hey, hab das Problem das Seit dem Ubdate Jetzt wider die Drescher und abfahrer collidieren, abfahrer Fährt von vorne Ran, fährt genau im Drescher rein, drescher tankt ab, drscher fährt zum abtanken aus spur abfahrer kommt laded ab nach dem abladen will er nach vorne rechts fahren und der drescher fährt nach vorne ,lings somit collidieren diese zusammen :/

**Comment by Tensuko** [comment]
#3311 
Closed.
Das war schon immer so, wenn es vorher funktioniert hat, dann eher nur aus zufall, weil Drescher und Abfahrer sich noch nicht miteinander unterhalten.
