### ISSUE TITLE
CP 6_01_00260 - when the harvester finished his course, the unload driver sleeps deep and so there ist no unloading anymore

### ISSUE THREAD

**Issue by caplink811** [Courseplay/courseplay#4048]
with the version named above, when the harvester finished his course, the unload driver does not recognize this and stood still. 
At least when the harvester call the unloader, then the unloader starts and comes to unload the harvester.

(sry, no log atm)

bye
 JrB

**Comment by Tensuko** [comment]
So when the Combine reaches the last waypoint, he doesn't extend the pipe ?
And so no unloader comes ?
But when you get in the combine and call the unloader, then it works ?

**Comment by caplink811** [comment]
morning,

3 x yes on your questions, exactly this happens. 
I've 1 field left to harvest, so I could gather a log in the evening, any special settings needed?

**Comment by pvaiko** [comment]
It is hard to believe that this is because of 260 where the only change was not turning off the lights at the end of the course.

**Comment by caplink811** [comment]
Just tried it with versions back to .234, and I never saw the pipe extended on the course end. So I assume a mod conflict (due I've deactivated all mods which are new or updated within the last 10 days)

my best guess is to close this issue at the moment.

thank you
