### ISSUE TITLE
GlobalCompany und Courseplay

### ISSUE THREAD

**Issue by Marko230** [Courseplay/courseplay#4049]
Hallo

In meinem aktuellen Single Gameplay erkennt Courseplay die Trigger von den GC gebäuden nicht.

Er fährt einfach vorbei und bringt auch nicht die Standard Meldungen (Abladestelle erreicht usw.)

Die anderen ohne das GC Script funktionieren tadellos.
Jetzt kann ich nicht sagen ob das ein CP Problem ist oder ob es am GC liegt.

MfG Marko

**Comment by Tensuko** [comment]
Och habe das ehrlich gesagt noch nicht ausprobiert, aber ich mach mich mal dran und versuche was rauszufinden.

**Comment by Tensuko** [comment]
Jo wird geblockt...
2019-08-06 13:53 :44 [dbg1 lp24866] 939 Vario (#1): added Fermenter_vis to trigger blacklist -> total=14
Mal schauen was sich da machen lässt

**Comment by Marko230** [comment]
Danke für schnelle Antwort :)

**Comment by Tensuko** [comment]
@ThomasGaertner 
Für die GC Trigger als Antwort von Kevin der LS-Modcompany
g_company.triggerManager -> Da werden alle Trigger registriert. (utils/GC_TriggerManager.lua)
Liegt in der Hauptmod drin.

**Comment by kris25-05** [comment]
![fsScreen_2019_08_09_00_03_30](https://user-images.githubusercontent.com/53919668/62741033-c60aa780-ba39-11e9-8793-92487912b20b.png)
I have same problem. I use BGA From GlobalCompany. Also slurry tanker 
just passing by trigger and don't fill it up.

**Comment by ThomasGaertner** [comment]
@Tensuko : ich bräuchte den exactFillRootNode in den einzelnen Triggern mit drin, damit ich die auseinanderhalten kann

[log.txt](https://github.com/Courseplay/courseplay/files/3486189/log.txt)

**Comment by kevink98** [comment]
Wäre sinnvoller, wenn du die Trigger im TriggerManager ausliest, nicht das Factoryscript... Weil dann funktionieren andere Scripte nicht^^ Wo das ist, wurde ja schon weiter oben weitergeleitet.

**Comment by ThomasGaertner** [comment]
please test v275 or higher and report...

**Comment by Marko230** [comment]
Hallo ThomasGaertner
Ich habe jetzt gerade die v275 auf der NfMarsch2.2fix getestet.  Also bis jetzt funktioniert alles.. 
getestet mit dem Komposter beladen ( Stroh ) , Kalkstation beladen ( Wasser ) , Mehlfabrik beladen ( Weizen ) 
vielen Dank für die ganze Arbeit

**Comment by Opa-Andre** [comment]
Komme aktuell leider nicht zum testen... funktioniert auch das Befüllen des Trailers mit Produkten einer GC Produktion?

**Comment by kevink98** [comment]
@ThomasGaertner: Warum ließt du nicht meine Kommentare hier? Macht kein Sinn, wenn du nur auf das Factoryscript eingehst. Du musst auf den TriggerManager von GC reagieren. Mit dem kommenden Update wird es ein weitere Script geben und dann wird's ja wieder nicht funktionieren.

**Comment by Marko230** [comment]
@ThomasGaertner 
Das Befüllen des Trailers funktionier leider nicht... Man muß bei jeder Produktion zum beladen des Anhängers die R Taste drücken... Automatisch beladet CoursePlay nicht
MfG Marko

**Comment by ThomasGaertner** [comment]
@kevink98 : ich habe Deine Kommentare gelesen. Leider konnte ich in der utils/GC_TriggerManager.lua nirgends die Zuordnung der Nodes zu den einzelnen Triggern finden. Ich benötige in meiner Tabelle den einzelnen Trigger mit dem entsprechenden node als Id um die mit einem Raycast wiederzufinden. Wenn Du mir die Stelle zeigen könntest, wo ich diese Trigger für alle company trigger auslesen kann, werde ich das gern machen. Außerdem wäre es gut, wenn ihr die standart Giants variablen nicht anders benutzen würdet als sie gedacht sind. Beispiel sind hier die providedFillTypes im loadTrigger.

**Comment by ItsSimon05** [comment]
@Marko230 Kann ich bestätigen

**Comment by ThomasGaertner** [comment]
@Marko230 @ItsSimon05 : habt ihr ein paar mehr Details ? Wo, Was, Wie ??

**Comment by Marko230** [comment]
@ThomasGaertner 
  Also wenn ich vom Hofsilo zb Stroh zum Komposter bringen möchte ladet CP den Anhänger automatisch am Hofsilo und befüllt Automatisch den Komposter....
Aber wenn ich von CP den Kompost aus dem Komposter abholen möchte beladet er nicht automatisch sondern bleibt am Ausgaberohr stehen und man muß erst die R Taste drücken damit CP den Anhänger mit Kompost befüllt.
Das ist auch zb bei der Düngerproduktion , Saatgutproduktion .. Das beliefern funktioniert nur das abholen nicht.

**Comment by Marko230** [comment]
@ThomasGaertner 
Ich habe Ihnen 2 Bilder per Email gesendet, bekomm es hier irwie nicht hin ...
Test 1 = Mit WartePunkt. CP bleibt stehen und wartet bis man die R Taste drückt.
Test 2 = Ohne WartePunkt . CP fährt weiter ohne Aufzufüllen...

Ich hoffe man kann damit ein wenig was anfangen..
Gruß Marko

**Comment by ThomasGaertner** [comment]
bitte für Test 2 mal die log mit debugChannel 1 und 19 aktiv posten, Danke

**Comment by Marko230** [comment]
@ThomasGaertner 
ich hoffe es hat funktioniert mit der Log :) 
[LOG Debug.txt](https://github.com/Courseplay/courseplay/files/3496853/LOG.Debug.txt)

**Comment by ThomasGaertner** [comment]
please try v276 or higher...

**Comment by Marko230** [comment]
@ThomasGaertner 
Das mit dem Düngerladen hat funktioniert. aber mit dem Komposter nicht..
[Komposter.txt](https://github.com/Courseplay/courseplay/files/3497596/Komposter.txt)
![Test NEU](https://user-images.githubusercontent.com/51233639/62952897-d4b3de80-bdec-11e9-917c-c7ff799f510a.png)
![Test NEU 1](https://user-images.githubusercontent.com/51233639/62952901-d67da200-bdec-11e9-95c6-9d70e4275fb0.png)

**Comment by kevink98** [comment]
@ThomasGaertner Denkfehler von mir... sorry. 

Gloabl für das GC kannst du es noch nicht machen. Werd es aber ändern, dass du auf alle TriggerManager Zugriff haben kannst.

Für die Zwischenzeit: 
Bei jeder Fabrik gibt es
`triggerManager` Dort dann `.registeredTriggers` Und in der table sind alle Trigger dann drin.

**Comment by Marko230** [comment]
@ThomasGaertner 
@kevink98 
habe es jetzt beim Komposter getestet und es funktioniert... Dann denke ich gehen die anderen Produktionen auch :)
Vielen Dank für die Arbeit

**Comment by Marko230** [comment]
@ThomasGaertner 
[278 LUA Fehler.txt](https://github.com/Courseplay/courseplay/files/3499989/278.LUA.Fehler.txt)

**Comment by ThomasGaertner** [comment]
@Marko230 #4081

**Comment by Marko230** [comment]
@ThomasGaertner 
Version getest und log ist fehlerfrei

Danke dafür

**Comment by Sualk1972** [comment]
Hallo habe eine Frage Habe Die neuste Version Von Courseplay drauf und er füllt nichts in den Hänger bei den Global Company mods von der NF Marsch von FED ACTION  wenn ich nicht drin sitze im Fahrzeug . Wenn ich im Fahrzeug sitze geht es wunderbar. Log schicke ich mit. mfg
![fsScreen_2019_08_18_11_46_56](https://user-images.githubusercontent.com/48014389/63223036-14454680-c1b0-11e9-91d4-859366f0fd00.png)
[log.txt](https://github.com/Courseplay/courseplay/files/3512882/log.txt)

**Comment by alpha117** [comment]
There is a fix here:
https://github.com/Stephan-S/FS19_AutoDrive/issues/369

**Comment by Sualk1972** [comment]
Alpha117 heb ich bereits gemacht trotzdem geht das befüllenn nicht.

**Comment by Stephan-S** [comment]
The fix was for AutoDrive only, but can very easily be expanded for CP. I am sure there's already something being done :-)

**Comment by Tensuko** [comment]
@ThomasGaertner wenn du mal Zeit hast, könnten wir das kurz mal durchsprechen, wie der stand ist ?

**Comment by kris25-05** [comment]
Hello My BGA from GlobalCompany still doesn't work. The tractor stops in front of the silo. The slurry tanker passes by and does not fill with liquid manure.
![cp_problem](https://user-images.githubusercontent.com/53919668/63640177-795fd700-c69d-11e9-8476-31eca014c6b5.png) Game version 1.4.1, CP 6.01.00291

**Comment by Tensuko** [comment]
The Global Company Patch for AutoDrive is out, not sure if it helps for CP too.
Can you guys test that and report with logfile and debugchannel 1 and 2 active if there is a problem ?

**Comment by JPHartmann1980** [comment]
Moin.
Bei mir funktioniert es nicht. Getestet auf der Felsbrunn Version 1.4.1 Global Company 1.1 einmal mit dem Fermenter von FEDAction und einmal mit dem Fermenter vom Global Company. Anbei die beiden Logs.
[log FED GC Mod.txt](https://github.com/Courseplay/courseplay/files/3625260/log.FED.GC.Mod.txt)
[log GC Fermenter.txt](https://github.com/Courseplay/courseplay/files/3625263/log.GC.Fermenter.txt)

**Comment by Tensuko** [comment]
Sollte mitlerweile geklärt sein...
Closed.
