### ISSUE TITLE
Cannot use CP with this seeder

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#4051]
Works OK with Giants 'Helper'

Thanks

![image](https://user-images.githubusercontent.com/30005040/62604693-7d93a280-b8f0-11e9-881d-1514fdc073b0.png)

**Comment by Tensuko** [comment]
More Info ?
Logfile ? Debugchannel 17 might help.
https://github.com/Courseplay/courseplay/wiki

**Comment by alpha117** [comment]
How strange, reload FS activate db17 and all OK

![image](https://user-images.githubusercontent.com/30005040/62608303-863ba700-b8f7-11e9-88b1-95b3d7fb2423.png)
