### ISSUE TITLE
text 'bleed through'

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#4052]
Text is showing through from other CP 'screens'

![image](https://user-images.githubusercontent.com/30005040/62604981-13c7c880-b8f1-11e9-81db-5c92930b1428.png)

**Comment by Tensuko** [comment]
Can't reproduce, logfile ?

**Comment by alpha117** [comment]
Strange one, reloaded FS and activated DB17 and all is good

Thanks
