### ISSUE TITLE
Lemken Diamant is not turning properly on headlands

### ISSUE THREAD

**Issue by dicktimmerman** [Courseplay/courseplay#4053]
I use a Lemken Diamant plough (http://www.farmingsimulator19mods.com/lemken-diamant-12-v1-0-0-0-fs19/), it does not turn properly on the headlands. It even ends up somewhere 3 fields further. Problem, turn is started, then the tractor back up while plough is not straight behind the tractor and ends up cross behind the tractor. In the ModDesc there is a setting that should prohibit backing up. Or at least CP should line up the implement properly before backing up.

**Comment by Tensuko** [comment]
Sry but we are not supporting Mods that doesn't come from ModHub.

We had to make that Decision, becouse the Mods are getting to many and everyone makes his own way of building one and not Sticking to GIANTS Standart. (Even on ModHub sometimes...).

If you have the same Problem with a Similar Vanilla plough or one from ModHub, then I reopen it and we takeing a look at it.

Sry again. Closed.

**Comment by dicktimmerman** [comment]
At this moment the Lemken Diamant is supported by ModHub, Issue still there.
