### ISSUE TITLE
Call Stack (v6.01.00265)

### ISSUE THREAD

**Issue by GeorgK1988** [Courseplay/courseplay#4054]
Hallo,

Erstmal Hut ab vor eurer Leistung!! Courseplay ist wirklich genial =)

Habe aber gerade in der Log gesehen dass mir Courseplay (v6.01.00265) ein paar Call-Stacks wirft!?
Kann mir wer weiterhelfen?
[log.txt](https://github.com/Courseplay/courseplay/files/3478950/log.txt)

Danke schon mal!
LG

P.s.: habe auch ein kleines Problem mit dem Mode9, soll ich dafür einen eigenen Issue anlegen?

**Comment by Tensuko** [comment]
Ja, bitte eigenen Issue anlegen für Mode9.
Log guck ich mir morgen genauer an, sieht aber nach dem Konflikt aus.
Welche Fahrzeuge genutzt uns was hast du gemacht als es auftrat ?

**Comment by Tensuko** [comment]
Load mod: FS19_ClaasAxion800 (Version: 1.0.0.0) (Hash: 5bba32a0510f70c11a4304f991a8dac2)
Load mod: FS19_ClaasAxion800v2 (Version: 2.0.0.0) (Hash: 9abba79e56f955b25ebe8ac01dc136a7)
Müssen beide drin sein ? (Finds immer super wenn der Modder für jede neue Version einen neuen Namen in der .Zip Datei benutzt.....)

Load mod: FS19_CLAAS_Axion_900 (Version: 1.0.0.0) (Hash: 2ea33d3664586500e4d242491cfa03d7)
Wenn das der aus dem ModHub ist, der ist bekannt dafür, Fehler zu verursachen.

Du hast so viele Mods drin, ich meine ich auch, aber muss man jede Variante eines Tracktors haben und auch noch die V1 und V2 vom gleichen ?

Errors:

2019-08-07 23:02 Error: Can't load resource 'C:/Users/Kolli/Documents/My Games/FarmingSimulator2019/mods/FS19_ClaasXerion5000CV_ByKOTmodsV1_3/dataS/scripts/vehicles/Vehicle.lua'.

2019-08-07 23:02 Error: Vehicle type 'FS19_JohnDeere6Rsmallnew.rseries' has unknown specialization 'FS19_JohnDeere6Rsmallnew.AddConfig'!

Jedenfals macht einer deiner Mods Probleme...

**Comment by GeorgK1988** [comment]
Hallo,

Alles klar, ich werde mal aussortieren gehen!! Danke fürs durchschauen!
Trat aber erst jetzt auf, hab immer alles gleich, mir ist nur aufgefallen das beim Mode 9 sich mal der Abfahrer "aufgehängt" hat..
Vielleicht deswegen?
Weil vorher hatte ich keinen Call-Stack drin.

Lg

**Comment by Tensuko** [comment]
Desshalb muss ich wissen, was du gemacht hast, als der Callstack auftrat.
Mit welchem Fahrzeug hast du was gemacht.
Mode2 benutze ich kaum und nur um reproduzieren ehrlich gesagt.
Kann ich bei gelegenheit mal ausprobieren...

**Comment by GeorgK1988** [comment]
Naja ich habe beim Kuhstall mit dem originalen Massey Ferguson Telelader und der originalen Schaufel per Courseplay Mode9, in den "Fendt 926 Vario Turboshift Chip" (Mod) mit angehängtem "Strautmann Streublitz PS2201" (Mod) Mist geladen. 
Weil ich den neuen Mode ausprobieren wollte. Dort entstand dann der Call Stack vermute ich.
Alle anderen Geräte stehen in der Garage und machen zurzeit nichts.

Letztens hing sich in der gleichen Situation das ganze Spiel auf.

Habe jetzt mal ausprobiert, einen originalen Miststreuer anzuhängen. 
Bin dann aus dem Spiel ausgestiegen (vorher gespeichtert), hab die Log gelöscht, hab LS19 neu gestartet, bin in mein Savegame rein, und habe mal nichts gemacht. Bin nur gestanden nach dem Laden, Courseplay hat die Felder erkannt und dann habe ich die "live Log" eingeschalten. Call Stack ist wieder drinnen.

Soll ich dir mein Savegame zukommen lassen?

**Comment by Tensuko** [comment]
Ne das kann ich so mal ausprobieren, aber ich vermute das es am Misthaufen Trigger leigt.
Wie hast du denn den Kurs erstellt ?

**Comment by GeorgK1988** [comment]
Hmm okee, hab dir mal nen Screenshot gemacht. Ich hoffe der hilft dir weiter?

![2019-08-11 17_05_01-Greenshot](https://user-images.githubusercontent.com/49338248/62835558-3ee84a00-bc5a-11e9-8be8-1ab287813267.jpg)

**Comment by Tensuko** [comment]
Da sich die Versionen gerade überstürtzen, kannst du das nochmal mit V272 probieren ?
https://github.com/Courseplay/courseplay/releases/tag/6.01.00272
Der Kurs ist an sich richtig, bisschen mehr gerade aus beim wegfahren vom trailer soll man machen, aber vlt gehts ja so.

**Comment by GeorgK1988** [comment]
Also mit der neuen V6.01.00275 ist der Call Stack jetzt weg!! :)
Danke für deine Hilfe!!
Lg

**Comment by Tensuko** [comment]
Ok, super.
Closed.
