### ISSUE TITLE
Tiefenlockerer hinterlässt unbearbeitete Stellen

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#4055]
![fsScreen_2019_08_08_06_26_53](https://user-images.githubusercontent.com/21023840/62675135-ed179980-b9a5-11e9-8c18-b99a711c04f3.png)
"Wende auf dem Feld" ist deaktiviert. Das hat vorher (vor .262?) einwandfrei noch funktioniert mit dem Kuhn Tiefenlockerer

**Comment by pvaiko** [comment]
Was ist die Wendemanővergeschwindigkeit?

**Comment by iljarogoff** [comment]
Pendelt so zwischen 5 und 10 km/h

**Comment by pvaiko** [comment]
Probier mal mit 267 (c2e96b4c0b99885463c39e5ff468520014a975a3).

**Comment by iljarogoff** [comment]
Funktioniert jetzt, danke!
