### ISSUE TITLE
error log courseplay 6.01 in log game

### ISSUE THREAD

**Issue by criss20ster** [Courseplay/courseplay#4056]

**Comment by criss20ster** [comment]
Hello. I have this my log game i see this error 

Warning (performance): Raw audio format F:/Users/CRISS/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay_6_01_00262/sounds/cpClickSound.wav.

Warning (performance): Texture F:/Users/CRISS/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay_6_01_00262/img/fieldScanInfo.png raw format.

Could you fixit ?

**Comment by Tensuko** [comment]
Just Warning, not an Error.
Warnings are harmles.
If you have real Error, post your full logfile with the right Titele.
https://github.com/Courseplay/courseplay/wiki

Closed.
