### ISSUE TITLE
Tractor collides with Harvester

### ISSUE THREAD

**Issue by Flashsolutions** [Courseplay/courseplay#4058]
Chase vehicle crashes into harvester after unloading of harvester.  I turned on debugging and recorded the crashes.  Youtube video with debug log in background shows precise times and exactly what happened.  This has happened more than once.  

https://youtu.be/7_vOoRE9wWI

Log file is attached
[saved_log.txt](https://github.com/Courseplay/courseplay/files/3482162/saved_log.txt)

**Comment by Tensuko** [comment]
#3311 
Closed.
