### ISSUE TITLE
Opening courseplay

### ISSUE THREAD

**Issue by redrummed1** [Courseplay/courseplay#4059]
Hi,
I downloaded the latest version and for some reason the HUD will not open at all with either the RMB or DEL key on keyboard. I have attached logfile. 
Cheers guys
[log.txt](https://github.com/Courseplay/courseplay/files/3483807/log.txt)

**Comment by Tensuko** [comment]
Becouse it is not in your Modlist...
download, (rename if want to FS19_Courseplay), put in your modfolder, start the game and don't forget to mark it before start loading the game.

**Comment by dariumz** [comment]
Same issue, right mousebutton does nothing, CTRL+DEL opens GUI, but buttons are non-functional, nothing happens when you click on anything.

**Comment by Tensuko** [comment]
Update AutoDrive to 1.0.4.0
Manuel Attatch, not sure about that if it cause Issues.
Same for VehicleControlAddon and RM_Seasons
I don't see a real reason, couse it works for me, actually....

**Comment by SteelRodent** [comment]
Only way I have that happen is when I forget to rezip the files and don't enable the mod on load.

Make sure you take the subfolder out of the zip you download and re-zip it, like it says at the bottom here:
http://courseplay.github.io/courseplay/en/installation/index.html

The right-click to open is an issue because a lot of other mods use them, so maybe check the keybindings.

**Comment by Tensuko** [comment]
You dont have to unzip or zip anything...
Download it from here:
https://github.com/Courseplay/courseplay/releases

**Comment by SteelRodent** [comment]
> You dont have to unzip or zip anything...
> Download it from here:
> https://github.com/Courseplay/courseplay/releases

Thanks, that's a lot easier. I've always used the pull link on the other page. Seemed easier than trying to work out where to find the right fileset on Git, but it is prone to error like I wrote before.

**Comment by Tensuko** [comment]
So, can you open CP now when download the correct file ?

**Comment by redrummed1** [comment]
No still not opening, I changed key binding to different key, still not opening. I have just updated courseplay and autodrive
[log.txt](https://github.com/Courseplay/courseplay/files/3509543/log.txt)

**Comment by redrummed1** [comment]
Got it, once I reset the bindings yet again it worked. Thanks. please close

**Comment by Tensuko** [comment]
Still suggest you to keep always the same name for CP Modsfile (e.g. FS19_Courseplay) so I never had any trouble with double HUDS or not opnening, unless it is a mod that not stick to GIANTS Standart...
Anyway, Closing this.
