### ISSUE TITLE
Abfahrer kollidiert regelmäßig mit Mähdrescher

### ISSUE THREAD

**Issue by ole22143** [Courseplay/courseplay#4061]
Das Problem Besteht immer noch 
Wenn der Mähdrescher entladen wird und den anhänger des Abfahrers 100% voll macht fährt dieser sofort zur feldausfahrt ist nun der Drescher im weg kollidiren beide wenn der Anhänger nicht voll wird geht das aber
![Neue Bitmap](https://user-images.githubusercontent.com/5673152/62822294-82bb5080-bb81-11e9-8561-08d1b307b212.jpg)

**Comment by Tensuko** [comment]
Es wurde auch nirgends gesagt, dass es behoben wurde, siehe:
#3311 
Closed.
