### ISSUE TITLE
The course is in a circle

### ISSUE THREAD

**Issue by MacedonskyAlex** [Courseplay/courseplay#4062]
In version 268 it is impossible to make a full course in a circle (Screenshot 1). In version 267 you can make a full course in a circle (Screenshot 2)
![fsScreen_2019_08_10_21_37_51](https://user-images.githubusercontent.com/52257646/62825598-502c4a80-bbb7-11e9-838f-c6d679ba9a51.png)
![fsScreen_2019_08_10_21_39_53](https://user-images.githubusercontent.com/52257646/62825599-54f0fe80-bbb7-11e9-8e65-d16f1bd6af22.png)

**Comment by Tensuko** [comment]
So it automatically switches down to 8 Rounds only ?
What tool you got attatched when you created that course ?
maybe more question will come from @pvaiko :)

**Comment by pvaiko** [comment]
Need a log with debug channel 7. 

(There's really nothing in 268 which would be causing this, and I can definitely generate courses with headlands only)

**Comment by MacedonskyAlex** [comment]
I put on a maximum of circles, and it turns out only 8. Where to find log with debug channel 7?

**Comment by Tensuko** [comment]
CP HUD Settings, click on that 7 (it turns green), create the course, the logfile should be there as discripedhttps://github.com/Courseplay/courseplay/wiki.

**Comment by MacedonskyAlex** [comment]
Put about 50 rounds , 29 rounds gives. Use a plow with a width of 2.7 meters, tractor MTZ
[log.txt](https://github.com/Courseplay/courseplay/files/3489852/log.txt)

**Comment by pvaiko** [comment]
The log does not have debug channel 7 activated.

Also, in your example above, the headland generation most likely stopped because the headlands started overlapping in the south-east corner.

**Comment by MacedonskyAlex** [comment]
I don't understand what needs to be activated

**Comment by Tensuko** [comment]
![debug7](https://user-images.githubusercontent.com/27344744/62834068-8d401d80-bc47-11e9-84e7-3531c0408693.png)

If that 7 is green.
Create the course like you normaly would.
Then post the new logfile.

**Comment by MacedonskyAlex** [comment]
Log file
[log.txt](https://github.com/Courseplay/courseplay/files/3492995/log.txt)

**Comment by Tensuko** [comment]
Your Idea of this is nice, but it still creates some Errors:
Load mod: DEACTIVE_animalsclean (Hash: 0e84b4941e2cf20f7131e72e75ff8be4)
Error: Missing descVersion attribute in mod DEACTIVE_animalsclean
Load mod: DEACTIVE_Caravan (Hash: bf823b998cf94a7d567248ca46cb4571)
Error: Missing descVersion attribute in mod DEACTIVE_Caravan
Load mod: DEACTIVE_FS19_amazoneZGB55_8200_MF_c4f59 (Hash: 6124e3e4f2d0b2f45395b0b5c314aad2)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_amazoneZGB55_8200_MF_c4f59
Load mod: DEACTIVE_fs19_animalpenextension (Hash: ea68bd9672c79384576076d6cc370c4e)
Error: Missing descVersion attribute in mod DEACTIVE_fs19_animalpenextension
Load mod: DEACTIVE_FS19_AnimalSpecies
Error: Missing descVersion attribute in mod DEACTIVE_FS19_AnimalSpecies
Load mod: DEACTIVE_FS19_ATC_ContainerPack (Hash: ae9e590990ac85c089844fa0750b1539)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_ATC_ContainerPack
Load mod: DEACTIVE_FS19_barrelWeight600kg (Hash: 1ecf452aabe78ec36f17a875de79a2c3)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_barrelWeight600kg
Load mod: DEACTIVE_FS19_BaseTransceiverStation (Hash: 0c3520b716e3c0d79a1aebd69426acf5)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_BaseTransceiverStation
Load mod: DEACTIVE_FS19_Biobeltz_UM_300 (Hash: a045669156655d3af6ebd05edca94788)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_Biobeltz_UM_300
Load mod: DEACTIVE_FS19_Blumen (Hash: 9163a615561254f8948f1f21569ca6eb)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_Blumen
Load mod: DEACTIVE_FS19_Case_Puma_ModLandNet (Hash: c315484d107dcaf014d02c1bd5ee8918)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_Case_Puma_ModLandNet
Load mod: DEACTIVE_FS19_chickenbox_MF_483b0 (Hash: 7df72c33cb2878870a411dfbc2b7e8b2)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_chickenbox_MF_483b0
Load mod: DEACTIVE_FS19_chickenCoop_MF_54e0b (Hash: 63fd1d24f313358be2481292cde84804)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_chickenCoop_MF_54e0b
Load mod: DEACTIVE_FS19_chickenStable (Hash: 4e0357a27d9b766810eb1cd36c9c7077)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_chickenStable
Load mod: DEACTIVE_FS19_CowBarn_MF_f7569 (Hash: fc136c0d1234da8c0ba57c2276b4c9d6)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_CowBarn_MF_f7569
Load mod: DEACTIVE_FS19_EC300_APACHE_DEMOLITION (Hash: a1deb0e580d9f94345b2d658eade4f0f)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_EC300_APACHE_DEMOLITION
Load mod: DEACTIVE_fs19_extra_large_sheep_pasture (Hash: 961e4ae8400d6c51b4e9742be85ff28c)
Error: Missing descVersion attribute in mod DEACTIVE_fs19_extra_large_sheep_pasture
Load mod: DEACTIVE_FS19_Fortschritt_E514 (Hash: 626a9d5459bb9c50b56966a70dfa2337)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_Fortschritt_E514
Load mod: DEACTIVE_FS19_Fortschritt_E689_Kartoffel (Hash: 9b79a08e07c8f7067b065bb1704c7556)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_Fortschritt_E689_Kartoffel
Load mod: DEACTIVE_FS19_Fortschritt_KS6_Pack (Hash: 4ca6de96c0b37ef89c76ac5d57677fb8)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_Fortschritt_KS6_Pack
Load mod: DEACTIVE_fs19_grosserhuehnerstall (Hash: df466123fc12b5aa75180fb785ba6fc7)
Error: Missing descVersion attribute in mod DEACTIVE_fs19_grosserhuehnerstall
Load mod: DEACTIVE_fs19_heating_plant_placeable (Hash: 69f7966081d3c96537e6600d06401371)
Error: Missing descVersion attribute in mod DEACTIVE_fs19_heating_plant_placeable
Load mod: DEACTIVE_FS19_HorseHelper (Hash: 78ceb5de29e5986f34930aee322787ce)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_HorseHelper
Load mod: DEACTIVE_FS19_House_SpawnPoint (Hash: fa1431e6401ee9f1b6a272093ebad187)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_House_SpawnPoint
Load mod: DEACTIVE_FS19_JohnDeere_DB120 (Hash: 5589b5213250c32fcfbd5bfa6762311a)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_JohnDeere_DB120
Load mod: DEACTIVE_FS19_JohnDeere_DB60 (Hash: 68284cabb66a9fa56abf5f1ae7693942)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_JohnDeere_DB60
Load mod: DEACTIVE_FS19_JohnDeere_DB90 (Hash: 91b124ad63e5af8aaa151553688e3dbb)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_JohnDeere_DB90
Load mod: DEACTIVE_FS19_John_Deere_DB60 (Hash: f781315ee3b68f77890deb2e5f9ea138)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_John_Deere_DB60
Load mod: DEACTIVE_fs19_lizardautoloader (Hash: 323595596177fbb9eda5bb667ef9ef10)
Error: Missing descVersion attribute in mod DEACTIVE_fs19_lizardautoloader
Load mod: DEACTIVE_FS19_LizardGP140SPBK (Hash: 2c94f7062c3486fbeca26f5c5cc7a3d7)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_LizardGP140SPBK
Load mod: DEACTIVE_FS19_Milchhof (Hash: b8bd9ca2b0c2b9f1f5197b007e599dab)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_Milchhof
Load mod: DEACTIVE_fs19_outdoorclimatepigsty (Hash: 73d9277668d6d5ab732a7a17823bc7eb)
Error: Missing descVersion attribute in mod DEACTIVE_fs19_outdoorclimatepigsty
Load mod: DEACTIVE_fs19_placeablebeehive (Hash: 60813800315c9c8f7ec75b20dfe58dc9)
Error: Missing descVersion attribute in mod DEACTIVE_fs19_placeablebeehive
Load mod: DEACTIVE_FS19_PlaceableElevator (Hash: 6978a48bea6dc90d809e4feb80025692)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_PlaceableElevator
Load mod: DEACTIVE_FS19_Placeable_Horse_Stable_with_Riding_Hall (Hash: 827daf9c58740ad26697747475d2ffe8)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_Placeable_Horse_Stable_with_Riding_Hall
Load mod: DEACTIVE_FS19_Placeable_Milchhof (Hash: 91a06e5bdce15d576c5c9c9efa764f84)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_Placeable_Milchhof
Load mod: DEACTIVE_FS19_Rooster18Row (Hash: ae2138caa524ba203727ba108f63b267)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_Rooster18Row
Load mod: DEACTIVE_FS19_SheepHusbandry (Hash: 1bbc7161189ecc6ba13401bec41c3f18)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_SheepHusbandry
Load mod: DEACTIVE_FS19_SmallPigStable_MF_83858 (Hash: e1e9339942925f54ec35f0552af50785)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_SmallPigStable_MF_83858
Load mod: DEACTIVE_FS19_SM_Gewaechshaeuser (Hash: a4f32522dce6aa81fd309236ccc5f902)
Error: Missing descVersion attribute in mod DEACTIVE_FS19_SM_Gewaechshaeuser
Load mod: DEACTIVE_fs19_sm_kuhstall2000 (Hash: 77e2071da53fe0d75297148bc625ea78)
Error: Missing descVersion attribute in mod DEACTIVE_fs19_sm_kuhstall2000
Load mod: DEACTIVE_horse_stud_v1_1 (Hash: ddefab8c59c560b170abb7a8dc48a4b9)
Error: Missing descVersion attribute in mod DEACTIVE_horse_stud_v1_1
Load mod: DEACTIVE_LS19_Groenbedrijf_Shop (Hash: 8a3bad501db129f175cdde08a145c6ee)
Error: Missing descVersion attribute in mod DEACTIVE_LS19_Groenbedrijf_Shop
Load mod: DEACTIVE_LS19_HW80_SHA_Auflieger (Hash: 0200a3768db4fdd6d5fea5fbb98fc06e)
Error: Missing descVersion attribute in mod DEACTIVE_LS19_HW80_SHA_Auflieger
Load mod: DEACTIVE_MANF200019414Silent (Hash: dbdd05cc1f3990da0a57dd772c6b2af9)
Error: Missing descVersion attribute in mod DEACTIVE_MANF200019414Silent
Load mod: DEACTIVE_MercedesXclass_Fs19_MF_03cde (Hash: fb74772f0e29490fe95b33b0c4b05337)
Error: Missing descVersion attribute in mod DEACTIVE_MercedesXclass_Fs19_MF_03cde
Load mod: DEACTIVE_ruche_v1_0_by_jameslebavard (Hash: b9b849f34a3a9b2c3677d7a7ace9ade9)
Error: Missing descVersion attribute in mod DEACTIVE_ruche_v1_0_by_jameslebavard

My Suggestion:
Create a new Folder and Name it 'All Mods' and copy your not used Mods in there, or create more 'mods_Save1' and 'mods_Save2' Folder, so you can switch them arround.

But you did it right and we got the debugchannel 7 Information.

**Comment by MacedonskyAlex** [comment]
unused mods removed

**Comment by pvaiko** [comment]
As I said, headlands started overlapping in the SE corner, as the log also indicates:
2019-08-12 17:41 :29 [dbg7 lp21083] Generated headland track #30, area -49576, clockwise = true
2019-08-12 17:41 :29 [dbg7 lp21083] Can't fit more headlands in field, using 29
