### ISSUE TITLE
Abfahrer kollidiert regelmäßig mit Mähdrescher

### ISSUE THREAD

**Issue by ole22143** [Courseplay/courseplay#4063]
Wenn der Abfahrer beim nebenherfahren zu 100% befüllt wird fährt er sofort los zum ersten Wegpunkt und wenn dieser ungünstig liegt fährt er in den Mähdrescher.
Wird er nur zu 95% voll fährt er erst los wenn die Wartepos frei ist und es Passiert nicht

**Comment by ole22143** [comment]
![Neue Bitmap](https://user-images.githubusercontent.com/5673152/62827064-10219380-bbc8-11e9-917f-7017e10438aa.jpg)

**Comment by Tensuko** [comment]
Ich hab dir das schon im anderen Issue gesagt: #4061
Wenn sich da etwas tut, wirst du das mitkriegen.
Es ist und bleibt erstmal bei #3311 
Closed.
Der nächsten Beitrag von dir mit dem Thema wird direkt gelöscht.
