### ISSUE TITLE
turn.lua:431: attempt to index local 'turnContext' (a nil value)

### ISSUE THREAD

**Issue by raxtor** [Courseplay/courseplay#4064]
Last version 268 freezes my game with error in log:
turn.lua:431: attempt to index local 'turnContext' (a nil value)

**Comment by pvaiko** [comment]
Do you think it would help to know what you were doing?

**Comment by Myrkur** [comment]
This happens to me too.

Two vehicles in mode 2 - One in mode 6.

If any of these vehicles miss their waypoint and start doing circles around it, trying to hit the waypoint, the game starts to experience lag spikes. When a spike stop, you'll see that the harvester will miss a short part of the crop, so i end up with short sections of crop not harvested on my field, one for each pause / lag spike my game encounters.

**Comment by raxtor** [comment]
@pvaiko sry.. I thought u can find wrong code by genrated error but what wrote @Myrkur is exactlly same... in addition same map...

**Comment by Heartbeatss1** [comment]
Hey, have the same error.
most orginals vehicles. nothing special at the moment but every minute i got an freeze
[log.txt](https://github.com/Courseplay/courseplay/files/3489869/log.txt)

**Comment by raxtor** [comment]
I used 3 combines and 2 vehicles in mode 2.. I noticed that also tere is changed turning maneuveur for combines in this version for sharp corner and doesnt work corectlly... look at image <a href="https://ibb.co/hKS5Wqm"><img src="https://i.ibb.co/nDF2cWL/field.jpg" alt="field" border="0"></a>

**Comment by pvaiko** [comment]
The original issue should be fixed by 270. @raxtor would you mind opening another issue for the headland turn?

**Comment by raxtor** [comment]
done #4068
