### ISSUE TITLE
Zweiter Kipper wird nicht beladen

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#4066]

**Comment by Lustiger-Hubi** [comment]
FS19_DondiegoMap mit zwei Krampe Kipper im Mode1
der erste Kipper wird beladen der zweite, angehängte leider nicht!
![fsScreen_2019_08_11_12_16_42](https://user-images.githubusercontent.com/48583507/62832657-3bd96380-bc32-11e9-80ef-70e9f2e5b2bb.png)
![fsScreen_2019_08_11_12_17_19](https://user-images.githubusercontent.com/48583507/62832658-3c71fa00-bc32-11e9-899e-eaa4bcb08de9.png)
![fsScreen_2019_08_11_12_17_43](https://user-images.githubusercontent.com/48583507/62832659-3c71fa00-bc32-11e9-9790-969153c8ca30.png)

**Comment by raxtor** [comment]
I can confirm that, same trouble for Wilson trailers with 2 grain bins.. in fact it is not possible use nice Wilson trailers with CP...

**Comment by Tensuko** [comment]
For the Wilson trailer got an Issue here: #3060
For loading, it seems similar, unloading is the problem, that for wilson trailer you got to switch 'unlaod side'.

**Comment by Lustiger-Hubi** [comment]
Mon, 
ich habe festgestellt, dass wenn ich den "Startpunkt" 
auf dem **zweiten** Häger lege dann werden beide Anhänger beladen!

**Comment by Lustiger-Hubi** [comment]
Auch der Wilson funktioniert 
Beladen (Start auf zweiten Anhänger) 
Abladen beide Trailer

![Startpunkt](https://user-images.githubusercontent.com/48583507/63075600-8dd00100-bf32-11e9-9323-f323c47e74d2.png)
![Beladen1](https://user-images.githubusercontent.com/48583507/63075609-91fc1e80-bf32-11e9-8656-76ae0c04f91c.png)
![Beladen2](https://user-images.githubusercontent.com/48583507/63075627-9a545980-bf32-11e9-9eb5-e6f76a45a9f6.png)
![Abladen 1](https://user-images.githubusercontent.com/48583507/63075641-a17b6780-bf32-11e9-8461-eddb540c6a90.png)
Er kippt beide Kipper ab!!

**Comment by Tensuko** [comment]
Gemeint ist der Trailer mit 2 Behältern)Kammer.
Das mit dem Startpunkt ist sehr intetessant, aber man kann ja nicht für jedesvgespann einen Kurs machen... Ich schau mal...

**Comment by Tensuko** [comment]
@ThomasGaertner war das schon immer so, dass es so funktioniert ?
Beladen am Startpunkt sieht ander aus, oder gilt das nur für Positioinen ohne Trigger ?
![fsScreen_2019_08_15_09_31_00](https://user-images.githubusercontent.com/27344744/63079876-d80baf00-bf3f-11e9-8d2f-afc69d7bad41.png)
![fsScreen_2019_08_15_09_33_34](https://user-images.githubusercontent.com/27344744/63079879-d9d57280-bf3f-11e9-96dc-283051fdae68.png)

**Comment by Lustiger-Hubi** [comment]
Das geht auch mit den Krampe, wie oben abgebildet!
Nur der Startpunkt muss weiter vorne liegen
Als wenn ich den zweiten Anhänger befüllen will.

**Comment by ThomasGaertner** [comment]
bei Beladen am Startpunkt wird zwischen dem letzten und dem ersten Punkt nach einem loadTrígger gesucht, wenn da keiner ist, bleibt der Traktor am ersten Punkt stehen und wartet. Wenn da einer ist, dann hält er im trigger an und befüllt. Wenn der Zug zu lang ist dann funktioniert das nur mit den Hängern die bis dahin im trigger waren.

**Comment by Tensuko** [comment]
Hatte ich mir schon so halb gedacht, aber dann gillt das nur, wenn die Zugmaschine zwischen end und startpunkt ist und in dem fall der trailer unter einem trigger steht. Sonst kann mein zweiter screenshot kaum funktionieren...

**Comment by Tensuko** [comment]
Denke der kann zu, da es ja funktioniert.
Closed.
