### ISSUE TITLE
Mode2 - tractor cant recognize full combine and combine conwoy is stucked

### ISSUE THREAD

**Issue by raxtor** [Courseplay/courseplay#4069]
<a href="https://ibb.co/1n7BJ0f"><img src="https://i.ibb.co/1n7BJ0f/fs-Screen-2019-08-11-16-12-13.png" alt="fs-Screen-2019-08-11-16-12-13" border="0"></a> <a href="https://ibb.co/8s2GCV9"><img src="https://i.ibb.co/8s2GCV9/fs-Screen-2019-08-11-16-12-51.png" alt="fs-Screen-2019-08-11-16-12-51" border="0"></a> <a href="https://ibb.co/dQ9Bz1N"><img src="https://i.ibb.co/dQ9Bz1N/fs-Screen-2019-08-11-16-19-10.png" alt="fs-Screen-2019-08-11-16-19-10" border="0"></a>

Not sure which additional info do you need.. feel free ask me.

**Comment by Tensuko** [comment]
I think he don't find the right one on a field with few Combines.
But that is part of #3311 
I would suggest you to use manual 1st.
Was it always like that or just in one of the last Versions ?

**Comment by raxtor** [comment]
It happens only when harvester is 100% full and waiting for unload and other unloaders are busy or returning from silo.. No idea if this happened in earlier versions, but minimally last 10 I can confirm. Which part of manual do you mean?

**Comment by Tensuko** [comment]
Say manually wich unloader takes wich Combine and not use auto mode for Field 22.

But this is #3311 and will get closed.
Sry.
