### ISSUE TITLE
Cp lädt nicht ab

### ISSUE THREAD

**Issue by ItsSimon05** [Courseplay/courseplay#4073]
Hey
mein CP Fahrer lädt nicht Ab bei Platzierten Produktionen mit Global Company (Ich weiß nicht ob es daran liegt deswegen schreib ich es dazu). Ich habe kein "Hier Abladen" eingestellt sonder nur wie auch beim Hofsilo normal den Kurs eingefahren

**Comment by Tensuko** [comment]
Duplicate of #4049
Closed.
