### ISSUE TITLE
Error: Running LUA method 'draw'. - AIDriver.lua:614: attempt to index field 'course' (a nil value)

### ISSUE THREAD

**Issue by Jagsta2121** [Courseplay/courseplay#4074]
i just started a new save on county line coming from midwest horizions with the exact same mod setup. when i start the combi mode the courseplay ui disappears on the cart tractor it tries to open the mouse comes but but it floods the log with: mods/Fs19_Courseplay/AIDriver.lua:614: attempt to index field 'course' (a nil value)
cp version: 6.01.00268
i worked fine on midwest horizions.

**Comment by Tensuko** [comment]
Full logfile pls.

**Comment by iljarogoff** [comment]
my guess: this is a mode2 issue. when switching from another mode , e.g.from mode5 to mode2 while the course is already loaded, CP will crash the game when starting the combi

**Comment by Tensuko** [comment]
That would be like what I found out in #3615 (sry, its in german just for a note...)

**Comment by Jagsta2121** [comment]
i had to shorten the log a bit to get it to upload. i started off in combi mode before creating a course for the overloader. the combine course was already started.[https://pastebin.com/raw/8pEUS6Tm](pastebin)

**Comment by Tensuko** [comment]
Link not working.
You can drag and drop the log.txt into comment box to upload it.

**Comment by jala15** [comment]
His written link is ok but if you press it, it directs you to a diferent direction. Here you are: https://pastebin.com/raw/8pEUS6Tm

**Comment by Obsiana2019** [comment]
I have the same Error on my map. I am new at CP but here is my logfile.

[log.txt](https://github.com/Courseplay/courseplay/files/3503579/log.txt)

**Comment by Jagsta2121** [comment]
here is logfile
[log.txt](https://github.com/Courseplay/courseplay/files/3503961/Cplog.txt)

**Comment by Tensuko** [comment]
@Jagsta2121 ???
Load mod: Courseplay_6_01_00205 (Version: 6.01.00268) (Hash: ef8634ba13b42e37f5e03a9874ee0eb2)
Download newest Version and Name it propaly, not that mix with Versions pls... https://github.com/Courseplay/courseplay/releases

@Stephan-S
What is this ? 2019-08-14 17:53 Error: Failed to open xml file 'C:/Users/xxxxxxxxx/Documents/My Games/FarmingSimulator2019//mods/FS19_AutoDrive/AutoDrive_Porta_Westfalica_init_config.xml'.

All who got this problem, can you pls try to make a new save, wich just CP 279 in mods Folder and try it, next you put your map in you want to play and try again. I want to see if it is map or an other Mod. I don't have the problem with all my Mods inside, so there must be else a Map or Mod Issue.

And I might have overseen it, only 1 Map in Modsfolder! :)

**Comment by Stephan-S** [comment]
@Tensuko It's just a message that pops up if AD is installed but there is no xml file provided for this map in the mod (No init config) and the config in the savegame is also not there or doesn't contain any roads. Nothing that causes any problems.

**Comment by Obsiana2019** [comment]
@Tensuko 
I have reinstall the newest Release and Testet it with my Map, no more Lua Error at the moment.

**Comment by Tensuko** [comment]
I set this to #3311 
But we keep an eye on that...
