### ISSUE TITLE
Error: Running LUA method 'update' - Waypoint.lua:668: attempt to compare number with nil + CallStack

### ISSUE THREAD

**Issue by aviator64** [Courseplay/courseplay#4075]
On a fieldwork (sowing) refill course, while the implement is being refilled the game crashes. This has happened each time I have reloaded the savegame and tried the course again.

[log.txt](https://github.com/Courseplay/courseplay/files/3495753/log.txt)

**Comment by Tensuko** [comment]
2019-08-13 08:19 Lua memory usage has reached 316259 KB; this is a dangerous level for consoles.

No Idea what that means, it might be couse of to many different FillTypeMover Scripts...

**Comment by ThomasGaertner** [comment]
should be fixed in the current version. @pvaiko changed something :-)
