### ISSUE TITLE
Der Überladewagen lädt nicht ab

### ISSUE THREAD

**Issue by Phips99** [Courseplay/courseplay#4076]
Hallo,

Am Anfang hat es geklappt, doch jetzt läd mein Überladewagen nicht mehr über. Ich benutze den JD 8400 R mit Elmers Haulmaster Überladewagen. Der Überladewagen wird von mir gefahren. Der LKW ist ein Man TGX (Mod) mit einem Krampe Auflieger (Mod), der auf einem Verkaufskurs im Mode 1 unterwegs ist.

[log.txt](https://github.com/Courseplay/courseplay/files/3496467/log.txt)
![20190813120615_1](https://user-images.githubusercontent.com/49783287/62933885-81796600-bdc3-11e9-90fd-d8ac632457ce.jpg)

**Comment by Tensuko** [comment]
1) Zu viele Mod-Maps im Modordner
2) AutoDrive und CP Version veraltet
3) kann das kaum an CP liegen

Ich werde das mal überprüfen....

**Comment by Tensuko** [comment]
Funktioniert mit V275

**Comment by Phips99** [comment]
Mit der aktuellen CP Version hat es funktioniert.

Danke für die Hilfe.
