### ISSUE TITLE
mode6, Fehler bei Kursgenerierung

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#4077]
Hallo Leute
habe einen Fehler beim Kursgenerieren fürn drescher bemerkt, mode6,
wenn man in der Ecke startet, mit 3 Bahnen rundherum, scharfe Ecken, fährt CP in der Startecke bei den nächsten beiden Runden etwas zu weit, und bei der letzten Umrundung vor dem Übergang zum hoch/runter lässt er etwa 20m Frucht stehen.
siehe Bilder:
![fsScreen_2019_08_13_20_08_26](https://user-images.githubusercontent.com/24860501/62966810-1b630200-be08-11e9-9334-021872a89429.jpg)
![fsScreen_2019_08_13_20_09_24](https://user-images.githubusercontent.com/24860501/62966816-1dc55c00-be08-11e9-80ed-9edbdba86c83.jpg)

v6.01.00275
lg
andreas

**Comment by Tensuko** [comment]
Wenn Vorgewende verwendet wird, hat es noch nie gut funktioniert an der Ecke zu starten.
Ich würde mittig an der kleinen Kante stehen und dann den Kurs generieren, dann wird da ein komplett sauberer Kurs draus.
Ist übrigens Mode unabhängig :)

**Comment by Tensuko** [comment]
Starte eher mittig an der Kante dann wird der Kurs sauber generiert.
Closed.
