### ISSUE TITLE
Error: Running LUA method 'update'. - combines.lua:488: attempt to index field 'spec_drivable' (a nil value)

### ISSUE THREAD

**Issue by Kuhbert** [Courseplay/courseplay#4078]
Serwus Leute
Das Problem ist das jedesmal wenn eines der 2 Geräte den Abfahrer ruft, das Spiel komplett abschmiert. Solange kein Abfahrer eingestellt ist und man selber ablädt funktionieren sie einwandfrei. Hab schon div. Traktoren und ohne Mods probiert aber da ändert sich nichts.

[logRooster604.txt](https://github.com/Courseplay/courseplay/files/3498385/logRooster604.txt)
[logGrimmeSE260.txt](https://github.com/Courseplay/courseplay/files/3498386/logGrimmeSE260.txt)

**Comment by Tensuko** [comment]
Du hast 2 mal CP drin:

Error: Failed to open xml file 'C:/Users/Obi/Documents/my games/FarmingSimulator2019/mods/LS_19Courseplay6/modDesc.xml'.
Load mod: LS_19Courseplay6 (Hash: 5d4f3fc21efdf39b528eb3057d2e4e5a)
Error: Missing descVersion attribute in mod LS_19Courseplay6

Außerdem ist Mode2 #3311 
Wäre auch interessanter, welches Fahrzeug beim Abfahrer ist und ob der Rooster und Grimme Modfahrzeuge sind.

Aber schmeiß erstmal die doppelte CP Version raus...

Benennt die neu runtergeladenen Dateien doch bitte immer gleich um in FS19_Courseplay oder FS19_Courseplay6 ...

**Comment by Kuhbert** [comment]
Hab jetzt die neueste CP Version geladen und umbennant wie du es gesagt hast, alle Mods bis auf CP und Moneytool hab ich entfernt und es ist immer noch genau das selbe.
Der Rooster 604 und Grimme Se 260 sind keine Mods genauso wie die Abfaher. Als Abfahrer hab ich folgende verwendet: JCB Fasttrac 8330, Challanger MT700 Series, Steyr 6300 CVT
Aufgefallen ist mir vorhin sobald der Abfahrer den Grimme auf dem Feld erkennt, dann fängt es auf einmal zu ticken an. Hört sich so an als ob das Mausrad auf einer Einstellung am Hud dreht.

neue Log:

[logGrimmeSE260NEU.txt](https://github.com/Courseplay/courseplay/files/3498725/logGrimmeSE260NEU.txt)

**Comment by Tensuko** [comment]
019-08-13 22:20 Error: Running LUA method 'update'.
2019-08-13 22:20 C:/Users/Obi/Documents/my games/FarmingSimulator2019/mods/FS19_Courseplay/hud.lua:1533: attempt to index field 'hud' (a nil value)
2019-08-13 22:20 Error: Running LUA method 'update'.
2019-08-13 22:20 C:/Users/Obi/Documents/my games/FarmingSimulator2019/mods/FS19_Courseplay/combines.lua:488: attempt to index field 'spec_drivable' (a nil value)

**Comment by pvaiko** [comment]
This would be @ThomasGaertner .

**Comment by superblaubeere27** [comment]
I just faced the same issue
[log.txt](https://github.com/Courseplay/courseplay/files/3916694/log.txt)

**Comment by Tensuko** [comment]
Sehr altes Issue, seither keine weiteren Meldungen gehabt.
Mache hier erstmal zu.
