### ISSUE TITLE
Dieser fehler kommt immer beim erzeugen eides Kurses

### ISSUE THREAD

**Issue by Berndi** [Courseplay/courseplay#4079]
Lua memory usage has reached 307208 KB; this is a dangerous level for consoles

**Comment by Tensuko** [comment]
Komplettes logfile, immer...

**Comment by Berndi** [comment]
es ist noch ein fehler dazu gekommen
[log.txt](https://github.com/Courseplay/courseplay/files/3501035/log.txt)

**Comment by Tensuko** [comment]
Kann keinen Fehler finden.
Kannst du denn einen Kurs erzeugen oder nicht ?
Oder was geht nicht ?

**Comment by Berndi** [comment]
ich versuche den fehlernochmal zu bekommen hatte es vorher probiert aber kamm nicht aber dann kam das 
2019-08-14 13:15 Warning: Performing emergency garbage collection pass - memory went from 97658 KB to 208846 KB in less than one frame
2019-08-14 13:15 Usage is now 165521 KB; full GC took 146.691000ms 

2019-08-14 13:22 Lua memory usage has reached 309849 KB; this is a dangerous level for consoles.

ich hab das mal aus der log copiert damit sie es in der log finden ich bedanke mich führ ihre mühe

**Comment by Berndi** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3501497/log.txt)


hir noch mal die log

**Comment by Tensuko** [comment]
Das ist aber nur ein Warning und kein Error...
Du hast auch eine menge Mods drin und sehr sehr viele Meldungen fürs Key Assigning.
Wie gesagt, hast du irgendwelche Probleme oder funktioniert etwas nicht ?

**Comment by pvaiko** [comment]
Duplicate of #3913
