### ISSUE TITLE
Combi Mode, Transport Vehicle Runs into Harvester

### ISSUE THREAD

**Issue by PsyberMind** [Courseplay/courseplay#4080]
I'm running into a rather serious issue with Combi Mode.. The mode itself works just fine, until the Driver comes to offload the product. It will offload just fine, and then indicate it's headed to a wait point, which, once again is fine and dandy, but before the Harvester is even clear, it starts to make the turn into the field to hit the wait point, and always, always runs into the the Harvester, causing slip and traffic warnings like mad..

For reference, I'm running nothing but headland passes, because I want to ensure the pipe is out of the fruit before the driver comes to offload.. Otherwise it runs right onto the field. I thought the Combines were able to back up on the field to offload so that the pipe was always in a safe spot, but that hasn't been the case..

**Comment by Tensuko** [comment]
#3311 
Closed.
