### ISSUE TITLE
LUA Fehler beim speichern

### ISSUE THREAD

**Issue by Nano68x** [Courseplay/courseplay#4081]
Seit der Version v6.01.00277 und v6.01.00278 habe ich beim speichern LUA Fehler. Standard Map und nur GC Mods.
[log.txt](https://github.com/Courseplay/courseplay/files/3500954/log.txt)

**Comment by Tensuko** [comment]
Wo hast du die FED Mods her ?
Würde das gerne nachstellen und ausprobieren.

**Comment by Nano68x** [comment]
Hier Bitte
http://ul.to/wkog9asi

**Comment by Nano68x** [comment]
Kommt bei mir nur alles mit Standard, keine Mods nur die DLC und CP. Beim ersten Kurs den wo ich fahre gehe ich auf speichern
[log.txt](https://github.com/Courseplay/courseplay/files/3501538/log.txt)
 und LUA Fehler. Bei den Versionen davor nichts.

**Comment by Marko230** [comment]
@Tensuko 
Hallo
bei mir ist es auch seit gestern..
siehe bitte : GlobalCompany und Courseplay #4049
Gruß Marko

**Comment by Tensuko** [comment]
Ok kann ich bestätigen, habe ich auch, fällt mir nur nicht auf, da er speichert und gut ist...

**Comment by ThomasGaertner** [comment]
bitte mal mit v.279 probieren....

**Comment by Nano68x** [comment]
Super der Fehler ist beseitigt, noch so schnell dazu.
Ich DANKE Euch.

**Comment by Tensuko** [comment]
Fixed.
Closed.

**Comment by ImPaKt7** [comment]
I loaded this up, I use mods (lots), upon entering the map jumped in a vehicle and my wheel and pedals did not work. Logitech G29.
