### ISSUE TITLE
Problem mit Krone BigM 500 VE

### ISSUE THREAD

**Issue by xpedicion** [Courseplay/courseplay#4082]
Nachdem ich seit etwas längerem (hatte noch 6.01.00236) Courseplay mal wieder aktualisiert habe, musste ich feststellen, dass ich nun Probleme mit diesem Selbstfahrer habe. Das Vorgewende macht er noch ohne Probleme und fährt auch auf die 1. Bahn. Am Ende der Bahn wendet er allerdings nicht mehr, sondern fährt stumpf geradeaus.
Ich habe dann mal durch Ausprobieren festgestellt, dass das Problem ab der 6.01.00237 auftaucht. Wie es scheint, ist das Umstellen der Berechnung aus den einzelnen Work Areas auf die AI Marker die Ursache. Habe mir mal die i3d im GE angeschaut, aber dort sind aiMarker vorhanden und in der xml ebenso im &lt;ai&gt;-Tag aufgeführt. Hab das mal mit dem BigM 450 verglichen, der in der 6.01.00278 tadellos funktioniert. Sah auf den ersten Blick vom Prinzip her gleich aus.
Wenn ich mal eine Vermutung anstellen soll, sieht es für mich so aus, als ob Courseplay den Wendekurs zu früh bzw. nicht weit genug vorneweg erstellt.
Hier noch ein paar Screenshots und die log. Diese ist mit der 00237 entstanden. Solltet ihr das nochmal mit einer aktuellen Version benötigen, kann ich die gerne auch nochmal generieren. Sagt mir dann bitte, welche Channels ihr tatsächlich haben wollte.

![20190814132359_1](https://user-images.githubusercontent.com/5276567/63018496-49445700-be99-11e9-9da4-28886abfa370.jpg)
![20190814132411_1](https://user-images.githubusercontent.com/5276567/63018502-4d707480-be99-11e9-9d95-1d1ba8e3c31e.jpg)

[log.txt](https://github.com/Courseplay/courseplay/files/3501098/log.txt)

**Comment by Tensuko** [comment]
Komplettes logfile bitte.
Eigentlich sollte der nun richtig arbeiten, da er nach dem Wenden zu spät anfing.

**Comment by xpedicion** [comment]
Hier bitte

[log.txt](https://github.com/Courseplay/courseplay/files/3501269/log.txt)

**Comment by Tensuko** [comment]
Hmm das wird warscheinlich darauf hinauslaufen, dass nichts passiert, da es eine Mod ist die nicht im ModHub vorhanden ist.
Mal sehen was @pvaiko dazu sagt...

**Comment by SledgeHammer75** [comment]
das Problem mit dem BigM 500 kann ich bestätigen

davon ab, der Standard-Trecker Fendt 1165 MT (mit Ketten) hat wohl das gleiche Problem, den musste ich beim letzten Spiel auch mehrfach aus der Feldbegrenzung puzzeln

**Comment by pvaiko** [comment]
Hat jemand ein Savegame mit Standard Map/Fahrzeug/Tool?

@xpedicion deine Analyse ist korrekt, die AI Markers sind auch auf dem Screenshot sichtbar (AI Left/Right/Back).

**Comment by xpedicion** [comment]
Hier bitte: [klick mich](https://dreiling-ms.de/dl/savegame19.zip)
Hab mal beide Versionen vom M500 reingepackt, aber die unterscheiden sich nicht groß.

**Comment by Tensuko** [comment]
Bitte mit V280 oder höher testen und rückmelden ob es funktioniert, oder andere probleme auftauchen.

**Comment by xpedicion** [comment]
Hatte kurz Zeit, mal eben den BigM zu testen. Das sieht hervorragend aus. Danke für den raschen Fix.
Und ausserdem ein fettes Dankeschön für eure Zeit, die ihr investiert, um uns das FS19-Leben etwas angenehmer zu gestalten. 😁 👍

**Comment by Tensuko** [comment]
Super, dann kann das hier zu. Viel Spaß weiterhin.
