### ISSUE TITLE
slurry tanker does not fill automatic if real person drive with field container next to it

### ISSUE THREAD

**Issue by spiessphilipp** [Courseplay/courseplay#4083]
My empty slurry tanker does not fill from the Kotte FRC if i drive net to the tanker. Same thing with seeders. They does not open their roof if a overloading wagon or a bigbag is ready to fill them. Is that a bug or wanted?

**Comment by Tensuko** [comment]
Can be solved with the Mode8, refill by itself on a Container.
Should make a general Issue about Refilling on the Field by Hand....
