### ISSUE TITLE
Installling Latest Beta

### ISSUE THREAD

**Issue by cchen1212** [Courseplay/courseplay#4085]
Hey I'm having trouble Installing beta 6_01_00278, I'm extracting the files and re-zipping them under FS19_Coursepaly_6_01_00278 but it seems farming simulator doesn't recognize it as it doesn't pop up in my mods list or when I make a new game.
Any help would be great, I have watched and read several videos and tutorials but they are from January 2019

**Comment by raxtor** [comment]
Easiest way is go to releases (its under [tab Code](https://github.com/Courseplay/courseplay/releases/download/6.01.00279/Courseplay_6_01_00279.zip)) and click to latest Courseplay release and u will see 3 sources. Download [*.zip](https://github.com/Courseplay/courseplay/releases/download/6.01.00279/Courseplay_6_01_00279.zip) to your mod folder.
Also is good use for name of CP *.zip file something like **FS19_courseplay6.zip** and just reaplace ii with new one. No unpacking needed.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/releases
Open Assets, download e.g. Courseplay_6_01_00279.zip
 and rename it into FS19_Courseplay.zip or FS19_Courseplay6.zip and place it into your Modsfolder.
You don't even have to rename it, but I can tell you, you will forget to delete the old CP.zip later when you get a new Version, so get used to rename it to always the same, so you replace it.
