### ISSUE TITLE
Ladezeiten

### ISSUE THREAD

**Issue by fischbesuch** [Courseplay/courseplay#4087]
Hallo, kann man das nicht wieder ändern, dass die Kurse erst geladen werden, wenn man sie braucht ? Ich lösche ungern die Kurse immer wieder.

LG

**Comment by Tensuko** [comment]
Das hatte zufolge, dass man Kreuzungspunkte von anderen Kursen nicht mehr gesehen hat, bis man diese auch einmal geladen hat. Ich kann dich verstehen, aber glaube nicht, dass da eine Lösung in sicht ist.
@pvaiko Kommt da was ?  Sonst mach zu...

**Comment by pvaiko** [comment]
Ich werde es ändern damit es in XML konfigurierbar ist oder was änliches.

**Comment by Triple5soul89ny** [comment]
It would bei great, If there would a possibility to have the choice by yourown.

**Comment by Tensuko** [comment]
Thats the Idea what @pvaiko said, but we will see.
