### ISSUE TITLE
Problem mit combi modus

### ISSUE THREAD

**Issue by quazumii** [Courseplay/courseplay#4088]
Moin ich versuche zurzeit mit einem Abfahrer und einem Häcksler zu häckseln. Das klappt aber leider nicht ganz so, da der Abfahrer immer im Kombi modus gegen Hauswände fährt bzw ich auch die Fahrzeug Einstellungen garnicht benutzen kann.. Das Feld ist bei mir einfach ausgegraut

**Comment by Tensuko** [comment]
Bitte mal ein Bild davon, welches Fenster ausgegraut ist.
Logfile bitte auch (Damit man die CP Version sieht etc...)
Ansonsten fährt er gegen Hauswände weil #3311 bzw weil das noch nie so richtig ging, Wänden auszuweichen.... sonst davon auch mal ein Bild machen, was du meinst.

**Comment by quazumii** [comment]
Ok mach ich.. Ich mache halt auch nur ganz normal meinen Kurs durchs Silo fahre da nur langsam mit 10km durch und beeden den kurs am Feldrand und speicher ihn... Das Ding ist aber, dass der Helfer da mit 35 oderso durchkloppt also keine Ahnung was ich falsch gemacht hab :/

**Comment by quazumii** [comment]
https://prnt.sc/ot6xc9 Wenn ich ihn jz abfahren lasse verschwindet sogar das komplette Overlay.. Geil :D

**Comment by Tensuko** [comment]
Mode2 kann noch nicht im Silo abladen.
Geil wäre ein logfile von dir... https://github.com/Courseplay/courseplay/wiki
Warscheinlich ist das einfach das gleiche Problem wie bei anderen auch, ein Mode2 Issue mit irgend einer Mod

**Comment by quazumii** [comment]
Ok gut ich schick euch den mal morgen, danke für die Schnelle Antwort!

**Comment by quazumii** [comment]
Ok ich habe jz ein anderes Spiel gestartet, wo ich garkeine Mods ausser de Courseplay und mein Moneytool drin hatte.. Das Problem bestand leider immer noch. Oder muss ich den kompletten Mod ordner mal clearen und dann das spiel starten?

**Comment by quazumii** [comment]
Btw bei welcher Version hab ich denn noch den alten Mode? Der Mode, der auch in Silos abladen kann..

**Comment by Tensuko** [comment]
Mods müssen immer aus dem Ordner raus, oder Ordner umbenennen z.B. Mods_All und einen neuen Ordner erstellen und mods nennen. Dort dann CP reinkopieren.

**Comment by quazumii** [comment]
Ok ich erstell einfach nen Ordner aufm desktop und knall alle meine mods ausser CP und Moneytool da rein :D

**Comment by Tensuko** [comment]
Der alte Mode ist und bleibt der alte bis der neue fertig ist.
Im Silo Abladen kann Mode1 und Mode6
Also entweder von einem Lagersilo abholen und im Silo abladen, oder mit Ladewagen vom Feld holen und dann im Silo abladen.

**Comment by quazumii** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3509494/log.txt)
 Hier mein LOG, hoffe du kannst damit was anfangen bzw mir helfen.. Wie meintest du das eigtl mit dem Ladewagen? Soll ich also mit nem LAdewagen neben dem Häcksler fahren? xD

**Comment by Tensuko** [comment]
Ich habe dir nur aufgelistet, welche Modi zum abladen im Silo funktionieren und das ist Mode6 und in Mode6 kannst du nur was mit dem Ladewagen aufsammeln um es im Silo abzuladen.

2019-08-15 21:24 Error: Running LUA method 'draw'.
2019-08-15 21:24 C:/Daten/Finn/Documents/My Games/FarmingSimulator2019/mods/ls19_courseplay/AIDriver.lua:614: attempt to index field 'course' (a nil value)

Duplicate of  #4074
Closed.
