### ISSUE TITLE
Kann keine Ropa - Ernter entladen

### ISSUE THREAD

**Issue by Spielbauer** [Courseplay/courseplay#4089]
Hallo, ich habe keine Möglichkeit die Fahrzeuge von Ropa in Verbindung mit AD zu entladen. Da der Ernter im Entlademodus seinen Erntekopf (siehe Bild) nicht gerade stellt und der Abfahrer von AD den gleichen Winkel nimmt den der Erntekopf hat, ist die Entfernung vom Abladearm zum Abfahrer zu groß. Stelle ich nun im AD-Menue die Entfernung kleiner crasht der Abfahrer in den Ernter. Ich kann jetzt nicht sagen ob dies ein Problem von CP oder AD ist. Sobald der Ernter auf manuell steht, stellt er den Kopf gerade und der Abfahrer kann entladen.

![fsScreen_2019_08_14_16_03_12](https://user-images.githubusercontent.com/54139649/63109953-a0762480-bf8a-11e9-81b0-4e87278831a9.png)
![fsScreen_2019_08_15_14_44_16](https://user-images.githubusercontent.com/54139649/63110059-e501c000-bf8a-11e9-8884-73b557ba398c.png)
![fsScreen_2019_08_15_17_39_14](https://user-images.githubusercontent.com/54139649/63110077-ef23be80-bf8a-11e9-9520-9ab73afd799f.png)

**Comment by Tensuko** [comment]
Das liegt daran, dass die CP Ernter eine Tasche bauen, wenn das Rohr in der Frucht ist.
Und da die Ernter leider etwas problematisch seitens GIANTS sind, können wir auch das Lenkverhalten nicht beeinflussen (irgendwie so war das doch oder ? @pvaiko ) desshalb steht der etwas komisch.
Was AD angeht, musst du mal @Stephan-S fragen.

**Comment by Stephan-S** [comment]
Hm, ich kann probieren bei den Fahrzeugen den Winkel des Fruchtkorbs statt des Kopfs zu nutzen. Aber ob das immer gut geht oder der 'Kopf' dann zu sehr im Weg ist kann ich nicht gut abschätzen.
Vielleicht macht es Sinn bei diesen Fahrzeugen das 'Taschen' fahren auszulassen, wenn das zu solch schrägen Stellungen führt.

**Comment by Spielbauer** [comment]
Hallo kurzes Update,
mit der neuen AD Version 1.0.4.6 und deaktivierter Fruchtumfahrung für die Ernter lassen sich jetzt die Fahrzeuge einwandfrei entladen. Danke an alle für die Hilfe

**Comment by pvaiko** [comment]
@Spielbauer danke, Fruchtumfahrung deaktiviert die 'Taschen'.
