### ISSUE TITLE
Game Locks at Start

### ISSUE THREAD

**Issue by HC1Gunner** [Courseplay/courseplay#4092]
I'm kind of perplexed by this weird problem, especially since I have about (8) hours on the Yogiland_EN_OY v1 map. I spent some time setting a up a few placeables, and then I create some course with CP, but never used them. After I had my farm setup and ready to go, I harvested (3) fields, mowed (2) meadows, and collected the grass using CoursePlay (v6.01.00236) with zero issues. You know how FS can pull you in, next thing I know yesterday I had (5) hours in the game. I spent the last (30) minutes in the game doing chores and setting up for stuff for the next day. I saved and exited the game, then a few hours later I wanted to just look a few field states, as to whether they were going to require plowing or lime. But when I fired up the map, about 10 - 15 seconds after hitting start, the game does a weird lock up. 

1. You can't Alt+tab to the Windows desktop, if you use Ctrl+alt+del and open the task manager, you can never select the Giant Engine to kill it, the only option is to Ctrl+alt+del, and logout of Windows.

2. So first thing I thought was, my save game file had become corrupt, but after going back to several older files, still the same lockup. I’ve waited with the game locked for up to (10) minutes, if you do get to the desktop, its dead, nothing functions from it or the taskbar.

3. So then I removed all mods, started a new save game, and with v6.01.00236 running, FS still locks after hitting the Start. I then went to Git Hub and got the latest version (v6.01.00279 ), same lockup.

I mystified and perplexed by having (8) hours into Yogiland with CP running, and had zero hiccups, to suddenly it won’t launch, locks, even with a new save game. If I remove the CoursePlay mod, have all my other mods installed, then the map fires right up from my last (newest) save game file, and I can do a new game save. 

Zero errors are created in the log, you start with an empty log, and after FS locks up, you still have an empty log.

**Comment by Tensuko** [comment]
Where is the full logfile ?
No matter what the log say, we want one for some reasons, so post full logfile, always. (drag and drop it into comment box, it is sueper easy! )

What do you mean by you removed all mods ? Did you rly take them all out of your mods folder ? if not, just not activate them is not enough.

**Comment by Martinnygaard** [comment]
In my old savegame i had between 1 and 200 courses. It took almost 6 minutes to load (Same map without CP took less than one minute) 
For five of the six minutes, everything was completely frozen, but i just had to leave the computer alone for some time and it works.

@pvaiko recently did a change so CP didn't load all courses on startup, but when needed - but that resulted in some other problem, so he made it load all courses on load again.

**Comment by Tensuko** [comment]
Patience is the key, sometimes :)

**Comment by HC1Gunner** [comment]
No I actually removed the mods from the mod folder, only thing in its is the Yogiland map and CP.

[log.txt](https://github.com/Courseplay/courseplay/files/3511034/log.txt)

**Comment by HC1Gunner** [comment]
Log file added as requested, BTW, thanks for the quick reply.

I have a fast PC, its not my the map taking a long time, it only has 21
fields, and its small in file wise because it doesn't have lot extra eye
candy stuff in the map. From push of Start, map normal loads in about 8 -
10 seconds, that was with CP working, and auto reading fields. When the
game locks at load, it actually freezing up part of MY PC, everything on it
is dead desktop wise and taskbar, only thing that functions is the mouse
and KB.

Longest loads times with CP mod are on Frohnheim and Suedhemmern maps,
those take about 30 - 40 seconds max with CP running.

**Comment by Tensuko** [comment]
First at all, what is a fast PC ?
My Smartphone is also fast for what it is supposed to do :)
And it is not only the Map or Numbers of Fields.
CP rly takes long, when you got a lot of Courses.

2019-08-16 16:08 ## Courseplay: loading courses and folders from "courseManager.xml"

Looks like you stopped the game and everything, when CP was about to load the Courses, at least your logfile ends there.
How long did you wait, before you cancel everything ?

**Comment by HC1Gunner** [comment]
You're not understanding, @ about 8 - 10 seconds, the game locks, I'v
walked away and left it sitting for 20 minutes, and when I return its at
the same locked state, the the game never loads the map, its stuck on the
splash screen with the dots going around in a circle with the preview
picture of the map that your going to play. Retired IT professional for 20+
years, I can tell the game is locked, as Windows 10 is locked up / froze. I
have to Ctrl+Alt+Del and logout of Windows and back in, to get a
functioning desktop.

(7) courses created and saved, remember I just started this map.
I have (2) fieldwork combine courses.
(1) fieldwork course to pickup straw on a field.
(2) courses to mow grass on two different meadows.
(2) courses to  to pickup the grass on the two meadows.

Its not the fastest system out there, but I don't overclock, but its no
slouch, it fairly fast at crunching raw data.

I built the PC to run FPS games, it has fast Intel processor running @
4.2 GHz
G.SKILL TridentZ Series 32GB DDR4 3200 Model F4-3200C14D-32GTZSW
Gigabyte AORUS GeForce RTX 2080 8G
My CPU and GPU are liquid cooled.

**Comment by pvaiko** [comment]
This Yogiland sounds interesting, I see there's holy water there....

Not sure I want to install that map just to fix this, but in any case can you post your courses (*Yogi* something in the CoursePlay_Courses folder)

**Comment by HC1Gunner** [comment]
My guess is you would install it, and have no issues at all.

I'm not sure what is going on, I just know that something unusual or weird
happened. I posted this is Giant's forum, and cwattyeso state he load the
map with CP and 140 other mods, and had no issues, and of course this is
how I start out.

"I then exited the game, made a new mod folder, that only had YogiLand
V19.1.EN and Courseplay 6.01.00280 in it, started the game and started a
new savegame and it loaded fine again for me with no lockup. I can't
replicate the problem you're having."

His only suggestion was to uninstall / reinstall FS, which I could do, but
seems if there was a corrupt file, it would do it with all maps I launch
with CP. The rest of my previous maps load and run fine

https://forum.giants-software.com/viewtopic.php?f=963&t=151196&p=1173642#p1173642

**Comment by Triple5soul89ny** [comment]
I Play the Multimap 2019 with quiet a lot courses saved in CP. My Game Start needs around 10-15minutes

**Comment by HC1Gunner** [comment]
Believe me, its not still loading, Windows is locked up. I don't know if
you notice, but Giant has coded / design the Lame side of FS, where it acts
like it runs from a window. During any course at the start, or in the game,
you easy Alt+Tab out and run or do anything on your desktop, go through
email, search the net, etc. I'm sorry none of my maps running CP at the
very longest have taken about 2 -3 minutes, and those were on 4x  with
small fields, and 16x map where I had a ton of courses. I even get Ms
notifications that appear on my screen while I'm in-game, if your touch
them, you're instantly on your desktop. At "no" time while you launch or
run this game is the Windows desktop dead and non-working. Besides if you
have a long load, the little dots running in a circle in the upper left
still move from time to time, at about 10 seconds after start, they never
move again, and the Giant's farming tips never change, believe me The game
is locked, and when I go into windows event logger, I can tell that Windows
had an execution issue, and froze up. Hardly anything goes on in you PC
that Ms is not logging somewhere.

**Comment by CHaWoLS** [comment]
I know this problem from FS17

It was an issue with big maps and many courses...  It took quite some time to load those...  and nearly the whole computer stuck while this...  

Just save away the courses, delete them from the FS-Folder and try what happens...  

I'm not sure what it is, that made the whole thing stuck - but especially on big maps the course-files are huge with ton's of coordinates....  that seems to take quite a while for the computer till they're loaded...

my five cents

**Comment by HC1Gunner** [comment]
I doesn't make any different if you delete those files, and start from
scratch, it just does the same thing, been there, done that. Not only that
but if you start a new save game that creates a a new save folder, you
start from nothing, those files don't even exist as they have to be created.

**Comment by cwattyeso** [comment]
Actually in FS19, Courseplay will loads courses you have created for a map, on any savegame using that map. You can create entirely new games in new save slots, however as you load into it, Courseplay checks the map, checks the courses folder and loads the courses. So courses you've made on old save games, can be used on new save games.

Something to test would be to delete or move the CoursePlay_Courses folder from your Farming Simulator saved data folder in your My Documents/My Games/ folder and then try launching the game and loading the Yogi Map and Courseplay and see if it loads. That would at least rule out one of your saved courses, however basic they may have been just to combine a field, mow some grass etc from being corrupted or something which is causing the lockup when Courseplay tries to load the courses at that point on the splash screen where you get the lockup.

Also on a general courseplay usage thing, if you have courses to combine a field, and mow grass, you don't need separate courses to load straw/grass or bale straw/grass, you can just load those courses into your tractor/truck/mower and put them in fieldwork mode and let them run. Saves you create and saving a load of extra courses you don't need which as mentioned can increase game loading time when you start building up the courses.

**Comment by HC1Gunner** [comment]
First off, Thank You very much, after something bugs for me for an extended
period of time, I sometimes get blinders. I kind knew that folder resided
in "Documents\My Games\FarmingSimulator2019", but I for \got all about it,
and was only deleting the (2) CP files in the save game folders.
Awesome dude, that fixed it, I feel a FS marathon coming at some point
today. I had no idea how I was going to run the Yogiland 4x production map
without CP.

Are you one of the Dev's at CP?

I do a separate course for straw pickup, as I use that Schuitemaker Rapide
8400 Loading Wagon with Nadel Windrower, its at 21m.

**Comment by cwattyeso** [comment]
No I'm not a Courseplay Developer, but someone who has over 1800 hours logged in Farming Simulator 19 on PC alone between the Steam Version and Giants version, with probably another 300 hours or so in the PS4 Version. I've played 25 different maps so far on PC, and have 1184 mods in my main mod folder currently, so I have had a lot of time playing with Courseplay and finding stuff that does and does not work well with it. I've probably tried and used every Dev version of Courseplay since the Beta came out.

**Comment by Tensuko** [comment]
I think we can close this then, if anything, you can keep discuss in closed state.

Closed.
