### ISSUE TITLE
Bypass Islands generation getting confused

### ISSUE THREAD

**Issue by SpacemanJay** [Courseplay/courseplay#4093]
I just started playing on the new seasons update for oxygendavid's Oakfield, which has vegetation or powerpoles in some fields. When I played this map when it first came out, bypass islands worked fine. Here's everything I worked out...

- It works fine if you have 1 or 2 headlands, but if you do 3 or more, it gets mixed up
- Doesn't matter if you select simple or circle, you get the same mixed up result
- If you do not skip rows, the result is a little better, but still would not work well
- If you skip more than one row, you get a different, but still mixed up result

This is what it looks like if you have 4 headlands, circle bypass, with a 6 meter plow. I haven't tried it with any other implements yet, let me know if you want tests with anything else.

![20190816_084025](https://user-images.githubusercontent.com/31190745/63169580-2afb6a00-c005-11e9-9f64-39bc30890f49.jpg)

**Comment by Tensuko** [comment]
It does that little thing in the north. That pike or something. Beside that is looks good.

**Comment by SpacemanJay** [comment]
Yeah it doesn't seem to be working out the lane changes correctly, but the circle paths themselves are ok

**Comment by pvaiko** [comment]
What exactly is the problem here? Have you actually ran that course?

**Comment by SpacemanJay** [comment]
It tried, it somewhat did it, but the 180 degree turn at the end of the circle route caused it problems. In older versions, the track would start on the outside of the circle and work its way in, and at the end on the inside, it would simply continue on around and drive straight out to its original lane. This avoided all the sharp turns, reversing, etc. It was a much better path. And like I said it doesn't matter now if you select circle or simple, you get the exact same result, Simple is supposed to just do a bypass half circle and keep going. Neither mode is working correctly, and it doesn't matter how many headlands, what direction you go, whether you do headlands first or not, starting location... nothing makes any difference to it.

**Comment by pvaiko** [comment]
Ok, will take a look, can't remember changing anything in that area.

**Comment by Tensuko** [comment]
Somehow, it works for me Field again, a smooth circle, no Idea why.
I had the exactly same Issue like shown in the pic, but now with V283.3 is fine....
I try to reproduce this.

@SpacemanJay can you try ii with 283.3 too ?

**Comment by SpacemanJay** [comment]
Sure thing, I'll try it right now and report back in a few min

**Comment by SpacemanJay** [comment]
Just tried 283.4 and I'm still getting the same result :( No mods except CP and the Oakfield map, started new save in new farmer mode, just used the ingame JD 6R and 6m cultivator to generate the course. I tried multiple different settings, none of them made any difference except the number of headlands. If I used 3 or more, it made 3 of those same circles. If I used 2 headlands, then it generated 2 circles, but still cutting to the inside first and ending with a 180 degree backtrack. The same for 1 headland, it made 1 circle that ended in a 180 degree turn. Here's my log along with a screenshot (50% size) of the settings I was trying originally and the result.
[log.txt](https://github.com/Courseplay/courseplay/files/3522321/log.txt)
![bad2](https://user-images.githubusercontent.com/31190745/63379133-ad678f00-c361-11e9-905a-6b759fe2be43.jpg)

**Comment by pvaiko** [comment]
It has nothing to do with the mode. There are two circle bypass modes, one for small islands and one for big islands, and it depends on the implement width and the size of the island if it is categorized as small or big.

Your second screenshot is a small island, the one above is a big island (because the implement width is smaller)

You seem to have problem with the big islands, nothing changed there for the last year or so, entering the inner headland is a sharp turn but there should be a turn maneuver generated for. When exiting, there's no 180 turn, there's a reverse to not miss anything.

Also, it is working from the inside out by design. If your are harvesting, it'll do the island headlands when the course first meets the island, when sowing, it'll do it last.

So not sure what exactly the issue is, if you have a video or a screenshot of something actually driving the big island headland that may help.

**Comment by SpacemanJay** [comment]
Hmm. Well those screenshots are from the same island in the same field (except the middle one). In the last ones I tried with a 8m cultivator in fieldwork, and a 9m direct drill seeder in mode 4, so the only real difference was 1m in width. I suppose I just didn't understand why the courses weren't generated the same.

**Comment by pvaiko** [comment]
You can look up how it is calculated here:
https://github.com/Courseplay/courseplay/blob/7631930cb4f27cad5c6d84d5024e2ed0c1918ed9/course-generator/Island.lua#L229

**Comment by SpacemanJay** [comment]
Ok I get the basics of it, for the most part. What happened in my case was it jackknifed when it tried to reverse at the end, and started turning circles. This only seems to happen when I have the working width set less than the actual working width, trying to balance out all the rows just so the last one doesn't overlap like 95%. 

Anyways I assumed any island headland would only be 1 track, so when it had 3 and started on the inside I thought it wasn't working right. Does it do a max of 3 to give room to turn around for the up & down rows? Or what is the reason if you don't mind me asking?

**Comment by pvaiko** [comment]
If it is a big island, let's say 20 rows wide you don't want do drive around the island 20 times and continue the same row on the other side of the island, so you end your rows there as it was the field boundary. 

Max of 3 is to have plenty of room to turn, more is rarely practical, especially with islands near the field boundary.

And yes, all this could be made options on the UI, I just don't have the time to implement everything I wanted.
