### ISSUE TITLE
Tipping in drive-through silo

### ISSUE THREAD

**Issue by MADxHAWK** [Courseplay/courseplay#4094]
I ran into the following problem. when letting coursplay unload a chopper and should tip into a drivethrough silo
![fsScreen_2019_08_16_19_09_29](https://user-images.githubusercontent.com/8193408/63185696-fb774c80-c05a-11e9-8fea-a225a2bccbf3.png)

Cp approching the silo with low speed, recognizing the tip-trigger and speed up driving through the silo while continue tipping when silo is left, see screenshot. 

Pastbin for Logfile with Tip Triger Log: https://pastebin.com/Aw1BK9dC

**Comment by Tensuko** [comment]
#3311 
Mode2 can't unload into silo yet. Only Mode1 and Mode6.

Closed.

**Comment by Tensuko** [comment]
Addition:
You could unload it manualy and use the existing course thrue the silo with Mode1 (load at start) that might work....
