### ISSUE TITLE
Combine Harvester not Working

### ISSUE THREAD

**Issue by cchen1212** [Courseplay/courseplay#4096]
When i set up a combine harvest course the combine harvester doesn't actually pick up any product
https://imgur.com/a/qADeu4H

**Comment by raxtor** [comment]
seems like withered.. wait to FS morning :-)

**Comment by cchen1212** [comment]
That was just after the crop matured/ Grew and was ready to harvest

**Comment by raxtor** [comment]
So are u able harvest it without CP?

**Comment by cchen1212** [comment]
No, once CPhas tried to harvest the field, the combine harvester doesn't work anymore

**Comment by CHaWoLS** [comment]
One question here - I just watched the pictures...  what crop is this an what cutterbar are you using ?   It looks like a Heilanthus....  which wouldn't work....  Either with or withour CP...  

...just one thing that should be clarified...  This has happened to me once before too...  ;)

**Comment by Tensuko** [comment]
If you cant even harvest manualy, it got nothing to do with cp. Reset your combine and tool and try again. If still not working, well... You do something wrong....

**Comment by caplink811** [comment]
That is what myself expierenced too from time to time, different maps, different fruits, most times it helps to detache the cutter, leave the harvester reenter the harvester attach the cutter and try again. After finish the work, plow the field.
Just my 2 cents

**Comment by Tensuko** [comment]
I close this until there is a clear Error that is CP related with logfile.
Post it here and I reopen it.
