### ISSUE TITLE
Request: Mouse Share with other Mods for example AutoDrive by Stephan Schlosser

### ISSUE THREAD

**Issue by kleba78** [Courseplay/courseplay#4097]
Hi there, 

is there any possibility to share the Mouse Pointer for these two mods, after your collaboration there is a litte bit of hope, that this is possible.

This will take the usability and gameplay of Courseplay and autodrve to a next level.

Thx for your Work.
kleba

PS: The same Request ist posted in Git AD

**Comment by Tensuko** [comment]
Right Click is already able to use AD and CP.
Middle Click is only AD.
What do you expect to happen ?

**Comment by kleba78** [comment]
sorry, i think i have to check my inputbindings first stephan s. replied the same points as you.

**Comment by Stephan-S** [comment]
But I have to chime in on this:
I rewrote my mouse implementation to react to any mousecursor changes.
Courseplay is still only accepting mouse input if your mouse toggle input is clicked/pressed.
So to be compatible to every mod with mouse input I think we should all implement something similar. Except you would have a valid reason not to react to mouse inputs with an active mouse cursor visible.
One important thing was to check for an open GUI, before accepting mouse input though.

Best regards,
Stephan
