### ISSUE TITLE
Pflügen mit CoursePlay 6.01.00275 - 6.01.00279

### ISSUE THREAD

**Issue by RK54** [Courseplay/courseplay#4098]
ab der CP Version 275 ist ein Pflügen mit CP nicht mehr möglich.
Nach 1-2 Bahnen macht sich der Schlepper selbstständig, ich habe keine Kontrolle mehr.
Nach dem einstellen des Abfahrers fängt er an und ändert den seitlichen Abstand, mal nach links, mal nach rechts. 
Das fahren selbst ist stockend und unregelmäßig.
Auffallend ist das Ganze nur in Zusammenhang mit GC
[log.txt](https://github.com/Courseplay/courseplay/files/3511886/log.txt)

Gruiß RK54

**Comment by Tensuko** [comment]
Ich werde das jetzt endlich mal selbst ausprobieren.
Magst du mir nochmal sagen, welche Fahrzeuge/Geräte du benutzt hast ?

**Comment by Tensuko** [comment]
Funktioniert problemlos, wie sieht denn ein Kurs aus ? Welche Map welches Feld ?

**Comment by Tensuko** [comment]
@pvaiko der macht das nun richtig:
![fsScreen_2019_08_17_14_51_54](https://user-images.githubusercontent.com/27344744/63212144-5adb6800-c100-11e9-9c8e-f4a762f7a3b5.png)
der müsste nach meinem verständnis anders rum arbeiten, also Tracktor zur gepflügten Seite:
![fsScreen_2019_08_17_14_58_47](https://user-images.githubusercontent.com/27344744/63212156-79d9fa00-c100-11e9-95e2-bd41734b9d24.png)
Habs mal versucht zu forcieren, aber er dreht sich den immer wieder so hin.
Bei dem kleinen hab ichs nicht probiert, aber denke mal der zeigt ähnliches verhalten.

Vollgestopfte log mit 9, 12 und 14, kann dir aber auch eine neue machen.
[log.txt](https://github.com/Courseplay/courseplay/files/3512022/log.txt)

**Comment by RK54** [comment]
Hallo,
ist die Multimap von FalPos: https://www.modhoster.de/mods/multimap2019--2
dort das Feld 32, mit einem Vorgewende, der Fendt 1050 Giants, und den Grubberpflug:
https://www.modhoster.de/mods/lemken-gigant-12s-pflug-und-grubber-pack-muliticolor oder
https://www.modhoster.de/mods/horsch-cruiser-12xl-oy. 
Der Kurs wird ordnungsgemäß generiert, fährt auch anfangs einwandfrei, bei Feld 32, fast fertiges Vorgewende, dann geht es los, höchstens noch eine Bahn rauf und runter, dann ist es Ende.
Modusabhängige Einstellungen bei Geräteversatz seitlich ändert er laufend den Abstand

Gruß RK54
![Feld 23](https://user-images.githubusercontent.com/54204656/63213894-e9a4b080-c111-11e9-9bf4-0d89d073594f.png)
[log.txt](https://github.com/Courseplay/courseplay/files/3512135/log.txt)

**Comment by Tensuko** [comment]
Ich glaub ich ahne was das Problem ist.
Das Teil ist als Pflug registriert und CP erkennt das auch als dieses, dabei sollte das für GIANTS bzw CP eigentlich ein Grubber sein.
Da wirds wohl keinen support für geben denke ich.
Es wird aber nicht an der Map oder am Kurs liegen.

**Comment by RK54** [comment]
ich habe das ja nur moniert, weil das Problem ist erst aufgetaucht mit GC.
Habe getestet mit den gleichen Fahrzeugen und Kursen, ohne GC, der wollte nicht mehr aufhören zu Pflügen. Dachte dass das an GC liegt, da ohne arbeitet CP problemlos

**Comment by Tensuko** [comment]
Also nur um das nochmal einfach zu halten.
Mit CP 283 und ohne GC, Pflügt CP mit genau dem Fahrzeug und Pflug ohne Probleme.
Sobald du GC (das original von LS-Modcompany) drin hast, geht es nicht mehr ? Ohne das du etwas anderes gemacht hast ?

**Comment by RK54** [comment]
genau so ist es, 
ich pflüge immer mit angegebenen Grubber/Pflüge, ohne GC gehen die einwandfrei.
GC im Mods Ordner, gleichen Kurs auf gleichem Feld, und schon gibt es Ärger.
Was mir aufgefallen ist, scheinbar psssiert das immer nach dem wenden, und dann wieder neu ansetzen

**Comment by Tensuko** [comment]
Ergibt überhaupt keinen Sinn... eigentlich...
Ich kaufe mir gleich mal nen Pflug...

**Comment by RK54** [comment]
ich hebe immer den von Yogy, ist 14 Mtr. breit, kann ich den Drescher Kurs dazu verwenden, 13,5 Mtr
Ich nutze immer solche Fahrzeuge mit ähnlicher Breite, damit ich viel arbeiten kann mit wenigen CP Kursen.
Achte mal beim Benutzen des Pfluges auf die Einstellungen:
Modusabhängige Einstellungen bei Geräteversatz seitlich ändert er laufend den Abstand

Modusabhängige Einstellungen bei Geräteversatz seitlich ändert er laufend den Abstand

**Comment by pvaiko** [comment]
Habe die Übersicht verloren hier, wenn es noch Problem gibt bitte neue Issue mit klare Beschreibung aufmachen.
