### ISSUE TITLE
Drescher und Häcksler

### ISSUE THREAD

**Issue by Landwirt56** [Courseplay/courseplay#4099]
Hi,
ich benutze die Courseversion 280. Ich habe die Fehlermeldungen schon durchgelesen, doch leider hierfür nichts passendes gefunden. Der Drescher und der Abfahrer, wenn der Drescher am Ende des Feldes ist, fahren immer zusammen. Zum Häcksler. Wenn ich Mais häckseln will, und einen Abfahrer laufen lasse, dann scheint fast alles ok zu sein. Setzte ich jedoch einen 2ten Abfahrer ein, stürzt CP ab. Das Programm läuft wohl weiter, doch mir ist es nicht mehr möglich den Abfahrer zu steuern. Ich nenne es mal die Konsole. Sie verschwindet sowie das Fenster vom LS, was ich mit einer F Taste öffnen kann.
Ladwirt

**Comment by Tensuko** [comment]
Das liegt daran, dass Mode2 noch WIP ist, siehe #3311 (Ich muss das wohl doch wieder als sticky machen).
Was gemacht werden müsste ist, auch wenn man selbst abtankt, dass der Drescher so lange am Feldrand steht und ablädt, bis Trailer voll oder Drescher leer.
Aber das wird leider noch etwas dauert...

Da es Mode2 betrifft, muss ich das erstmal wieder zu machen, sry.
Closed.
