### ISSUE TITLE
Kursgenerierung - Return to Startpoint (for HUD)

### ISSUE THREAD

**Issue by Christoph40** [Courseplay/courseplay#4100]
Hallo,

ich hätte eine Frage zur Kursgenerierung.

Seit einigen Versionen ist es so das es die Funktion am Startpunkt Enden nicht mehr gibt.

Mittlerweile ist es so wenn ich einen Kurs erstelle zum Düngen/Säen oder Feldarbeit/Grubbern das der Fahrer immer automatisch am Startpunkt endet. 

Ich habe jetzt probiert, am letzten Wegepunkt oder Trigger warten auf Deaktivieren gestellt,aber dann fährt er immer Kreis zum Startpunkt und wieder zum Ende des Kurses. Die Arbeit wird nicht beendet.

Wie kann ich es einstellen das der Fahrer am Ende des Kurses stehen bleibt? Oder ist das gar nicht mehr möglich?

MfG

**Comment by Tensuko** [comment]
Das wird eine neue Funktion im HUD, wo man dies einstellen kann.
Zur Zeit ist das so: Drescher wartet immer am Ende, Ist der Start im Vorgewende, wird an den Startpunkt zurück gefahren, Ist der Start in den Feldreihen, wird am Endpunkt gewartet.
Ohne Vorgewende bin ich mir gerade garnicht sicher, was passiert, aber man wird es wieder einstellen können!

@ThomasGaertner ich lasse den für dich offen als Erinnerung :)

**Comment by Christoph40** [comment]
Ok,danke dir für deine schnelle Antwort.

**Comment by pvaiko** [comment]
Duplicate of #3990, closing
