### ISSUE TITLE
Mode9 issue

### ISSUE THREAD

**Issue by hoefti10** [Courseplay/courseplay#4104]
Mode 9 is not working for me, hopefully iam the mistake and not CP :-)
I will fill the shovel und unload in the trailer.attached you the the screenshots and the log.
Tested it with XXX.081 an XXX.082 and two different courses.
![20190818114553_1](https://user-images.githubusercontent.com/25055083/63223213-83239f00-c1b2-11e9-895a-350c17bc49e4.jpg)
[logxxx.081.txt](https://github.com/Courseplay/courseplay/files/3512893/logxxx.081.txt)
![20190818115912_1](https://user-images.githubusercontent.com/25055083/63223214-83239f00-c1b2-11e9-85c4-b776611d5034.jpg)
[logxxx.082.txt](https://github.com/Courseplay/courseplay/files/3512894/logxxx.082.txt)
![20190818115933_1](https://user-images.githubusercontent.com/25055083/63223215-83239f00-c1b2-11e9-8824-2d2b68d19374.jpg)

Thanks in advance :-)

**Comment by Tensuko** [comment]
Mach mal in den CP Optionen alle Wegpunkte an (die 3 Punkte in der mitte) und mach dann einen screenshot.
An sich sollte der Kurs so aussehen:
Startpunkt vor dem Ladegut, Wartepunkt genau vor dem Ladegut, Wartepunkt am Ende des Ladeguts, rückwärts wegfahren, vorwärts zum Trailer, dort einen dritten Wartepunkt (so dicht am Trailer wie es geht, es seidenn da hat sich nun was getan, bin mir nicht sicher), gerade rückwärts wegfahren, am besten vor den Startpunkt, stückchen vorwärts und dort dann vor dem startpunkt stoppen.
z.B. so:
![fsScreen_2019_08_07_11_26_52](https://user-images.githubusercontent.com/27344744/62612081-1208ff80-b907-11e9-8360-eb240afbb950.png)

Aber was geht denn nicht bei dir?

**Comment by hoefti10** [comment]
Moin, so sieht der Kurs bei mir auch aus. Starte ich am  „ersten Wegpunkte“. Fährt er gar nicht erst los. Wenn ich am „aktuellen Wegpunkt“ starte fährt er los, füllt die Schaufel und bleibt dann stehen wie im letzten Screenshot. Kann aber gern nachher nochmal das geforderte Bild nachreichen ;)

**Comment by hoefti10** [comment]
![20190819164417_1](https://user-images.githubusercontent.com/25055083/63274948-fc012480-c2a0-11e9-8d2c-72e061bebdb6.jpg)

**Comment by Tensuko** [comment]
Also:
Er fährt los, lädt etwas auf und bleibt dann vor dem Trailer stehen ohne abzuladen ?
Schonmal mit der Trailerposition gespielt ? Etwas vor oder zurück ? Vlt auch dichter an den Wartepunkt ran. Er muss halt erkennen, dass dort ein Trigger zum abladen ist.

**Comment by ThomasGaertner** [comment]
nein es ist so, dass der Trailer nicht erkannt wird wenn die Schaufel leer ist. ab 284 sind da auch debug prints für drin

**Comment by Tensuko** [comment]
Versuch nochmal mit der neuesten Version glaub 286.

**Comment by hoefti10** [comment]
Beim ersten Screenshot war die Schaufel voll, abgeladen hat er trotzdem nicht. Ich teste nachher nochmal mit der neusten Version hat sich ja einiges geändert scheinbar. Ich melde mich dann nochmal. Danke erstmal für eure Hilfe ;)

**Comment by RK54** [comment]
@ Tensuko,
ich hätt da auch wieder gern ein Problem.
Endlich kann ich Mist laden mit Radlader und Schlepper, die machen aber beide was sie wollen.
Kurs eingefahren wie er sein soll, passt.
Der Abfahrer lädt Mist, fährt den Kurs ab, mit 2-5 Km/h,
macht sich bereit zum Entladen, kurz vorm Anhänger macht er einen links Schlenker und lädt eine Schlepperbreite neben dem Wartepunkt ab, der Radlader nimmt seine Ladung wieder mit.
Habe einige Fahrzeuge getestet, immer das gleiche
![3](https://user-images.githubusercontent.com/54204656/63467666-441d7400-c466-11e9-95bd-1aed558e3d0c.jpg)
![4](https://user-images.githubusercontent.com/54204656/63467686-4c75af00-c466-11e9-8f02-029e7d430817.jpg)
![5](https://user-images.githubusercontent.com/54204656/63467716-5d262500-c466-11e9-89b5-b1b70191f23f.jpg)
![6](https://user-images.githubusercontent.com/54204656/63467733-62836f80-c466-11e9-9c61-c2edd8217b0b.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/3527253/log.txt)

**Comment by Tensuko** [comment]
So dann mal kurz hier weiter, ja das Problem kenne ich auch. Bist du mit dem Trailer mal dichter an den Wartepunkt gefahren ?

**Comment by RK54** [comment]
ich habe den Kurs eingefahren, mit 3 Wartepunkten.
den 3. direkt am Anhänger, dichter geht nicht.
Im oberen Bild siehst Du den Schlepper, lädt direkt nebem dem Wartepunkt ab.
Der Radlader biegt gleich ganz ab.
Dichter kann ich den Wartepunkt nicht setzen

**Comment by RK54** [comment]
@Tensuko,
habe ich auch schon versucht, habe auch schon einkalkuliert die Schaufelbreite die der Schlepper neben dem Wartepunkt, aber selbst da will er unbedingt schräg über die vordere Ecke entladen

Gruß  RK54

**Comment by Tensuko** [comment]
Ok, schade. Dann wird es wohl noch etwas dauern bis eine Lösung kommt...

**Comment by RK54** [comment]
@Tensuko,
danke für Deine Nachricht.
Du weißt ja, ich Faulenzer, schau den anderen gerne bei der Arbeit zu, aber was nett geht, geht nett. Macht auch keinen Sinn so weiter zu arbeiten, nach jedem Wagen der beladen wird, muss man hin und den Mist weg schaufeln, der daneben gefallen ist

Gruß RK54

**Comment by Tensuko** [comment]
Auch für hier folgender Tipp:
Dritte Wartepunkt direkt über dem Trailer!
Trailer nehmen, Mode9 Kurs laden, Trailer unter dem dritten Wartepunkt stellen, Kurs raushauen und dann den Trailer Kurs aufzeichnen. Hat die letzten male gut Funktioniert.
Ich mache hier erstmal zu...
