### ISSUE TITLE
Question (also suggestion for headland working width), how to not miss any spots on field ?

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#4106]
I want to have perfectly done fields without any missed spots when worker is done with the job.
In FS17 and 19, its almost impossible to create perfect course, unless i record the whole field by myself (no way im gonna do that) or if field is perfectly square and tractor/combine goes only up/down.
There will be not any missed spots on the field.
I play mostly on Oakfield farm, fields are natural wierd shapes.
I have tried Smooth , Round and Turn headland corner options, but all of them will miss some spots on the corners of the field (especially if corner is sharp).
Also i tried to use landscaping tools and paint the outer parts of corner with grass, but still everytime i create new course, those tiny outer parts will get missed (also inner parts of corners, between 1st and 2nd headland and between 2nd and 3rd).
What i tried to do is to decrease working width by 2-3 meters, then everything is OK, there is an overlap between headlands and on the turns, so there are no missed spots, field is done 100% perfect, but the problem is, field center (up/down) will have constant overlap of 2-3m which is waste of time and resource (fertilizer,lime etc).

What i want to suggest is this:
in course generator, could you guys please add working width for headlands and working width for center of the field (thats the current option we have right now).
Lets say i have seeder Amazone Condor 15m width....in headlands i would use 12m (would be small overlap on headlands and turns, which is what i want) and for center of the field (up/down) i would use of course 15m width.

Is it possible to add this option, headland working width ?

That you for your great work and sry for bad english and for very long post, but i wanted to explain it in details :).

**Comment by RUGhost** [comment]
So you want to spend a whole lot of fert and seed by overlapping 2 or 3 headland pass to cover-up  the tiny bit of missing corner?

**Comment by bojanh66** [comment]
Correct, so i can have field without missed spots on corner turns.
I know it sounds ridicilous, but at the end of the year, you are in big money surplus anyway, so small overlap on headlands (additional cost of fertilizer/lime) is not a big loss, but looking and fields without any missed spots gives some nice satisfaction.
And i am not the only one to ask for something like this, there are many threads on github where people try to figure out how to fix headlands on wierdly shaped fields and so far, i think only small overlap (adding new option "headland working width") would "fix" it.
You maybe dont agree with me, but if we already had this option, i would certainly use it.
Right now i can reduce working width by 1-2m less than implement, but the whole field will be overlapped...thats why i ask if its possible to add headland working width for implements ?

**Comment by cwattyeso** [comment]
Best solution, is to get yourself a tractor and plough, and setup a course to do some headlands, using either the smooth, turn or radius option of your choice. Generate it and then exit the tractor, open the Terrain Paint tool and paint grass all over the field edge maximum tool width of 20 is advised, Once you have been round the whole outside of the field (Effectively deleting the original field edge and making the field a bit smaller.) get back in the tractor, enable allow create fields on the plough then start courseplay. It will now go round and plough a brand new edge on the field, that in future you other vehicles, sprayers, combines etc should be able to follow without missing bits when doing the headlands.

**Comment by SteelRodent** [comment]
Just putting it out there, that IRL they generally can't cover 100% of a field and it's normal to see blank spots here and there. The bigger the machines they used, the bigger these spots will be. On blob shaped fields and fields with obstacles, you'll often also see blank spots in the middle of fields everywhere they had to swerve for one thing or another. They generally only overlap where the headlands cross the main tracks because nothing ever grows well in the headlands anyway - it's basically like sowing on a paved road compared to the rest of the field because the headland gets much more traffic. Only difference is that real fields are a lot bigger than what we can get in the game, so the missed spots don't look as big in comparison.

**Comment by Tensuko** [comment]
Just make the workwith smaler then it actually is and you got what you want, no need to use the automatic calculated work with. Sure then you got that on the up down rows too, but I don't think there will happen anything more....

@pvaiko your opinion on that ?

**Comment by bojanh66** [comment]
Yes, thats what i do, just a tiny bit smaller working width, i also round up corners with grass (landscaping tools) to make it easier for worker when doing turns.
Thanks for advice guys, but i would like to hear, is it possible to add headland working width as an option or that would be too much complicated ? I am just curious.

**Comment by pvaiko** [comment]
@bojanh66 first of all, the course generator already uses a 7% overlap for the headlands (only the headlands) by default to cover up some uworked patches in the corners when using the smooth option, as with that option it is geometrically not possible to cover 100% if the corner radius on the innermost headland is less than the turning radius. 

That's what you have the 'round' option for which makes sure none of the headland corners will have a radius less than the turning radius but you'll have some unworked patches is the corners only. 

The 'turn' option should not leave any patches, however it'll only make headland turns on sharp corners and sometimes field corners aren't really corners (although they look like corners) but arcs with a very small radius so there won't be turn maneuvers.

**Comment by pvaiko** [comment]
Guess question is answered, closing.
