### ISSUE TITLE
mode8 is online please test and report

### ISSUE THREAD

**Issue by ThomasGaertner** [Courseplay/courseplay#4107]
Field Supply Mode is now online.
Set up a course starting somewhere, leading through a fill trigger and set a wait point where you want to deliver. if there is a container, it will overload into it otherwise it will wait till the set fillLevel is reached to go on.

**Comment by Heartbeatss1** [comment]
Working very Good!

**Comment by Bobster82** [comment]
Hi @ThomasGaertner ... I did some testing for this mode, this is my findings so far. I hope its clear ;)

* Recorded route is doing good, except the end and the start of the course, the vehicle slows down... 
  so when making his rounds, everytime he passes the end and start its some waypoints where the speed is reduced to about 10km/h

* When loading slurry (or digi), CP menu is showing: "loading 0 from 0"

* Selecting the amount to fill (50% as test) is working.
* Driver at wait point, starts to overload, is working.
* When the container is full (or the fieldworker) and the trailer is below the drive at % level, its getting another refill, if its above this % it waits, is working.

* When loading or overloading, there is no option to press continue (whenever u want the driver to start before the fill % is reached or before trailer is empty with overloading)

* I used a fieldworker to load at the container without a waitpoint, is working. (also the fill % selected in the fieldworker)
  - If the container is empty, the fieldworker just drives by the container and goes back to the last point on the field (empty)
* I used a fieldworker to load at the container with a waitpoint, its driving to the container, fills up, drives a bit further to waiting point, waits a bit and drives back to last point, is working. (also the fill % selected in the fieldworker)
  - If the container is empty, the fieldworker waits at the waitpoint, but when the container gets a refill from a trailer, the fieldworker doesnt start to fill, it just stands there.

* I used a fieldworker to load at the trailer without a waitpoint, it drives by the trailer, no slow down, it loads a bit and drives back to last point on the field, not working.
* I used a fieldworker to load at the trailer with a waitpoint, it drives by the trailer to the waitpoint but it start filling allready, drives to waitpoint and waits till its full or when the trailer is empty and drives back to last point on the field, no matter how much loaded (no matter what settings filllevel % on the fieldworker)
  - If the trailer is driving for a refill and the fieldworker waits at waitpoint, the trailer comes back and the fieldworker starts to refill and drives back the last point on the field (no matter the fill level). But the message that the fieldworker waits at waitpoint stays.

* Both courses with fieldworker to load from a trailer or a container needs a waitpoint to wait whenever the trailer or container needs to refill.
* If the truck with trailer is waiting at the waitpoint (overload point) and i press stop driver, drive a bit and want the driver to pick up the route a bit further, it just stops and does nothing (as it still thinks it is at the waitpoint) I need to reset the route and start another route before i can use the refill route again.

**Comment by ThomasGaertner** [comment]
thanks for this impressive test report 
the loading indication and the continue button will be fixed with the next update
for the not restarting filling issue, we have to discuss it. Normally is this option with the wait point to get manure by a shovel and not to actively refill on triggers. For the field worker passing the loader without loading: I've checked it and it works. please check, that the field worker has set the correct fill type to load and the field worker drives correctly through the trigger of the loader (check with F5) that where the mistakes I did while testing...

**Comment by Bobster82** [comment]
@ThomasGaertner 
I got a issue that might be easy to solve.
* Unload slurry to a container without a waypoint.

This time i created a route with ad network. Created the return route to field x just a waypoint behind the slurry waypoint. 
The trailer fills up, it drives the route to field x, (there I parked a container next to the ad destination point) It drives by the container and doesnt start to overload and drives back to the slurry load point.

I dont want to create a refill route for every field as I have a AD network for that ;)
If I use AD for the refill route, it just loads slurry and overloads it to the container ;)

Or maybe make the destination as a waitpoint when u select the return route in mode8?

**Comment by BigBear864** [comment]
All works well until it has to overload into the container, it gets to the container and the game just basically freezes and no vehicles can be driven, I can tab to the slurry transport vehicle and stop driver (courseplay) and it unfreezes and starts unloading into the container and the game runs fine again. 
I tried to test it directly unloading into a slurry spreader but then the game froze as above and once the driver was stopped, the game was all fine
The log is showing this
"C:/Users/**********/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/AIDriver.lua:1175: attempt to call method 'getTipState' (a nil value)"
I have tested this in a savegame with only courseplay enabled and tried with the latest version of courseplay
Video for reference https://youtu.be/JpzvAT06OEg

**Comment by Tensuko** [comment]
Mode8 is working perfectly right now.
Fill up anywhere, drive to a waitpoint and else fill up a container next to it, or wait there for a fieldworker.
Closing this info to clean up a bit.
If you have any Issue with Mode8 or got a Question, open a new Issue or check for existing one.
Closed.
