### ISSUE TITLE
Kombinierter Kurs Saatgut und Dünger auffüllen und GC

### ISSUE THREAD

**Issue by Moodijil** [Courseplay/courseplay#4109]
Hallo zusammen,

ich habe glaube ich nur ein kleines Problem. Wenn ich einen Kombinierten Kurs benutze zur Einsaat und der Helfer auf den Kurs fährt um Dünger oder Saat wieder aufzufüllen dann tut er das nur wenn ich auf dem Traktor mit sitze ansonsten fährt er am Trigger vorbei. Er öffnet zwar die Plane beim vorbeifahren wenn ich nicht mit drin sitze aber er befüllt es nicht.

Mache ich was falsch? Wenn ich mit drin sitze funktioniert es Tadellos. Ich habe die aktuellste Version von CP drauf 282.

Liebe Grüße Christian

**Comment by Tensuko** [comment]
An was für einer Auffüllstation denn ?
Logfile mit Debugchannel 1 und 2 sollte hier helfen.

**Comment by Moodijil** [comment]
Hallo Tensuko,

es ist ein Düngerhersteller und Saatguthersteller von FedMods.

Hier noch die LOG mit dem Debugchannels, vielen Dank schon mal für die schnelle Antwort.

LG. Christian
[log.txt](https://github.com/Courseplay/courseplay/files/3513402/log.txt)

**Comment by Moodijil** [comment]
Hallo,

ich habe mir mal gedacht ich hänge auch mal die gleiche LOG drann wenn cih im Fahrzeug mit gesessen habe.
[log.txt](https://github.com/Courseplay/courseplay/files/3513410/log.txt)

**Comment by Tensuko** [comment]
In deiner ersten log ist ein Error gefolgt von LUA Callstacks.
Zeile 449 2019-08-18 14:16   Error: Failed to find child 9 from node visuals, only 9 childs given
Weiter unten noch ein Callstack (Zeile 767)
Gibt es nicht mal eine original Quelle wo ihr die FED Mods her habt ? Auf der FedAction Website habe ich nichts gefunden!
Oder sind die in der Map mit bei ?

**Comment by Moodijil** [comment]
Ich könnte die Dateien hier hoch laden der beiden Herstellungen wenn das hilft. Von der Webseite bekommst Du nur einen kompletten Satz alles an Produktionen und die Karte und etliches andere.

**Comment by Tensuko** [comment]
Welche Website und wo. Gebt mir doch mal nen original Link wo das steht....

**Comment by Moodijil** [comment]
Von hier lade ich das runter:

https://www.fedaction-letsplay.de/ls19-nordfriesische-marsch/

**Comment by Moodijil** [comment]
Es ist die Karte ohne Gräben da sind alle Mods enthalten in der RAR Datei verpackt.

**Comment by Tensuko** [comment]
Das ist doch mal eine Aussage :) gucken wir uns an.

**Comment by Lars-LS17** [comment]
Hallo,

ich habe ein Ähnliches Problem. 
Ich habe mein selbst erstelltes Saatgut und Dünger im Hochsilo von Fed-Mods eingelagert. Dieses funktioniert auch mit GC. Wenn ich dann ein Kurs einfahre zum wiederauffüllen fürs säen, dann füllt er nur das Saatgut auf, jedoch nicht Dünger. 
Er müsste eigentlich ein Meter weiter vorfahren und dann noch Dünger auffüllen. Dies macht er aber nicht automatisch. Er fährt einfach weiter.
Anbei die Log-Datei mit Debug Channel 1 und 2.
[log.txt](https://github.com/Courseplay/courseplay/files/3516594/log.txt)

**Comment by Tensuko** [comment]
Dieser Fehler sollte mit der neuesten GC Version behoben sein.
Closed.
