### ISSUE TITLE
Speed on AD course not reduced in corners

### ISSUE THREAD

**Issue by MacedonskyAlex** [Courseplay/courseplay#4110]
Download the route from AD, CP travels with maximum speed and cornering CP is not slowing down, which causes a deviation from the route and turning transport

**Comment by raxtor** [comment]
CP never did it, there 2 options, u can use manual set for speed ot u can use speed from recording.. AD is not recording speed.

**Comment by SteelRodent** [comment]
Seems CP needs to use AD's drive mode to use AD's routes, or it's not likely to ever work properly since the two mods don't determine speed the same way.

**Comment by Bobster82** [comment]
#4108

**Comment by pvaiko** [comment]
Some fine tuning may be necessary but is working now.
