### ISSUE TITLE
Missing error check when AD fails to return from refill trip

### ISSUE THREAD

**Issue by SteelRodent** [Courseplay/courseplay#4112]
If AD fails to return from a refill trip,  - like if it can't find the way back - it will stop running and immediately pass control back to CP, which in turn attempts to go in a straight line back to its resume point. CP needs to somehow know if AD fails to return and I guess stop or pause as well.

I'm still working out how and when to use AD together with CP (and if it even makes sense) and in this case I forgot to test if AD was able to find its way to the field before activating CP. Turns out I had forgotten to connect the paths by the field so there was no possible route, only AD apparently checks each leg separately so it went to refill and then told me it couldn't find the way back, at which point CP took over and wrapped the tractor around a tree next to the refill point (halfway across the map from the field it was working on). This problem was entirely caused by me, but CP needs to know if the trip has failed so it doesn't try to continue when it's not possible.

**Comment by pvaiko** [comment]
Not sure if this is something CP needs to solve. @Stephan-S, what do you think?

**Comment by Stephan-S** [comment]
@pvaiko I think I will add a parameter to the callback function, which is true if all went fine and AD reached the destination and false otherwise.

This way, CP can decide if they want to take over and try to salvage the situation or if they also shut down/fire driver

**Comment by pvaiko** [comment]
@Stephan-S that makes sense, have you already added it?

**Comment by Stephan-S** [comment]
No, not yet. Probably next weekend until I find some time to properly do something besides small responses here on Github. I'll let you know!

**Comment by Tensuko** [comment]
Not sure about the Status of this one.
If that Issue appears again, pls open an Issue at AD GitHub and link this one.
