### ISSUE TITLE
Game crashing when loading a saved game on version CP 6.01.0283.2

### ISSUE THREAD

**Issue by Maunose** [Courseplay/courseplay#4113]
Hi,

I tried testing the latest version of CP as of now but I couldn't load my saved game. The game crashes while loading.

Here is the log. https://pastebin.com/qfCEX7JM

Thank you.

**Comment by MADTJ** [comment]
I have similar problem I cannot load my saved game, not even new game with this mod enable. I've remove all mod but this 6.01.0283.2 still enable and cannot load.

**Comment by Tensuko** [comment]
Much to old Version of AD:
FS19_AutoDrive (Version: 1.0.1.9)
Beside that, 283.2 (the .2 shows it) is hightly experimental, so I recommend to stick to 283 unless you want to try the new AD Feature, wich requires AD 1.0.4.8 or higher.

**Comment by IDeserveToBeWrited** [comment]
Same for 283.3
[courseplay log.txt](https://github.com/Courseplay/courseplay/files/3516422/courseplay.log.txt)

**Comment by Tensuko** [comment]
Seems to be another Issue for you:

2019-08-19 16:45 C:/Users/doode/Documents/My Games/FarmingSimulator2019/mods/Courseplay/course_management.lua:1698: attempt to index global 'FS19_AutoDrive' (a nil value)
2019-08-19 16:52 Error: Running LUA method 'update'.

But I would say that is becouse you don't even have AutoDrive...

@pvaiko no Check if AD is in ModList yet ?

**Comment by Maunose** [comment]
> Much to old Version of AD:
> FS19_AutoDrive (Version: 1.0.1.9)
> Beside that, 283.2 (the .2 shows it) is hightly experimental, so I recommend to stick to 283 unless you want to try the new AD Feature, wich requires AD 1.0.4.8 or higher.

You were right, I just updated the AD to the latest version (1.0.4.9) and the game loaded correctly.

Thank you.

**Comment by Tensuko** [comment]
> 
> 
> Same for 283.3
> [courseplay log.txt](https://github.com/Courseplay/courseplay/files/3516422/courseplay.log.txt)

You need AD to get CP to run right now, this will soon change, so you can run CP without AD again.
You could also get the V283 without addition, as the .1 .2 and .3 are just adding AD stuff.
