### ISSUE TITLE
Reading AD courses v6.01.00283.2 FS19 will not start

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#4114]
Files attached

[AutoDrive_Fenton_Forest_4X_By_Stevie_V1_42__config.zip](https://github.com/Courseplay/courseplay/files/3515006/AutoDrive_Fenton_Forest_4X_By_Stevie_V1_42__config.zip)
[log.zip](https://github.com/Courseplay/courseplay/files/3515075/log.zip)

**Comment by Tensuko** [comment]
don't zip your log pls.... just drag and drop the log.txt (next time...)
[logfromalpha117.txt](https://github.com/Courseplay/courseplay/files/3515189/logfromalpha117.txt)

**Comment by alpha117** [comment]
roger that.

**Comment by pvaiko** [comment]
@alpha117 did you load an AD course and then saved the game?

**Comment by alpha117** [comment]
not sure what you mean. I've even created a new save game and AD imports the xml automatically and still will not start

**Comment by alpha117** [comment]
A thought.....maybe it might be due to some of the routes are 2-way(red) and CP only currently reconizes 1-way paths(green)?

![image](https://user-images.githubusercontent.com/30005040/63266183-407fc680-c287-11e9-9864-5cacf69227b4.png)

**Comment by alpha117** [comment]
Nearly there, FS19 now loads OK, but still cannot load  an AD course from the CP GUI
[log.txt](https://github.com/Courseplay/courseplay/files/3515955/log.txt)
 an AD course from the CP GUI

**Comment by alpha117** [comment]
..update CP will load the courses BUT not the ones that are named Field'X' (Field 2, Field 3 etc etc)

**Comment by pvaiko** [comment]
2019-08-19 13:49 :51 [dbg8 lp3157] 1165 MT: Received AD course from current position to 20 with 0 waypoints
2019-08-19 13:49 :53 [dbg8 lp3258] 1165 MT: Received AD course from current position to 27 with 0 waypoints

AD gives CP a path with 0 waypoints as you can see, maybe @Stephan-S knows why. Frankly, I don't know what a 2-way course is.

**Comment by alpha117** [comment]
Thats not the issue, just done more testing, CP will not load a course that has a number in the course title

**Comment by alpha117** [comment]
It will load a course named 'Field' but not load a course named 'Field 1'

**Comment by pvaiko** [comment]
CP does not use the name other than displaying it. It is using the destination ID it gets from AD. As I said, maybe @Stephan-S has an idea.

**Comment by alpha117** [comment]
Done it now, all routes now load...standby I'll let you know why with some screenshots

**Comment by alpha117** [comment]
CP will not generate a route with the AD destination name at the last Node/Waypoint

Example
CP will generate a route to field 8 as the 'name' is not the last WP

![image](https://user-images.githubusercontent.com/30005040/63269426-17aeff80-c28e-11e9-9059-8d326f310748.png)

CP WILL NOT generate this course as the Name is the last WP in the route

![image](https://user-images.githubusercontent.com/30005040/63269591-6e1c3e00-c28e-11e9-9ac8-5de056df7308.png)

**Comment by Tensuko** [comment]
@pvaiko Ad got 2 Kind of Routes to create. the normal light green one (one way, like the Arrows) and the purple way, wich can be used in both directions (for smal field streets or something).

**Comment by alpha117** [comment]
Sorry the  2-way routing was not correct, that was not the issue..my fault sorry about the confusion

**Comment by pvaiko** [comment]
> CP will not generate a route

Just to clarify: CP is **not generating** a route. It asks AD for a route and just uses what it gets from AD.

**Comment by pvaiko** [comment]
So I think this can be closed here, right?

**Comment by alpha117** [comment]
yep, sure can
