### ISSUE TITLE
LUA Call Stack CP 6.01.00283

### ISSUE THREAD

**Issue by ArnieD23** [Courseplay/courseplay#4115]
Wenn ich einen generierten Feldkurs (Grubbern/Säen/Pflügen) abarbeiten lasse und der CP Helfer fertig ist freezed das Game. Kann nur noch den PC neustarten.
Habe keine Ahnung ob es durch einen Konflikt mit einem Mod verursacht wird.
Vielleicht kann mir jemand helfen. Danke

[log.zip](https://github.com/Courseplay/courseplay/files/3515766/log.zip)

**Comment by Tensuko** [comment]
Verkleinertes logfile, die Lua Callstacks unten rausgenommen.

[logfromArnieD23.txt](https://github.com/Courseplay/courseplay/files/3516004/logfromArnieD23.txt)

**Comment by Tensuko** [comment]
Und wieder sind die GC Mods von FED mit dabei, ich muss mal sehen das ich die teste...

Außerdem Error in Mods:
Load mod: FS19_flieglDPW180 (Version: 1.0.0.0) (Hash: 857b54460affdb9bdc39026c8300e9be)
Error: Failed to open xml file 'C:/Users/arnie/Documents/My Games/FarmingSimulator2019/mods/FS19_flieglDPW180RB_BD/modDesc.xml'.
Load mod: FS19_flieglDPW180RB_BD (Hash: 4c109c60de29df04f910f48bee68f612)
Error: Missing descVersion attribute in mod FS19_flieglDPW180RB_BD
Error: Failed to open xml file 'C:/Users/arnie/Documents/My Games/FarmingSimulator2019/mods/FS19_flieglDPW180SB_BD/modDesc.xml'.
Load mod: FS19_flieglDPW180SB_BD (Hash: e69573a3e0e147e3d92d1945ca994caf)
Error: Missing descVersion attribute in mod FS19_flieglDPW180SB_BD

Es sieht auch so aus, als ob du die Callstacks bereits am spielstart hast.+
Welche Mod das verursachen könnte, kannst du nur selbst herausfinden, indem die Mod für Mod hinzufügst, also quasie bei 0 Mods (bis auf CP) anfangen...

**Comment by ArnieD23** [comment]
Habe jetzt die Fliegl DPW's rausgenommen, Log einmal gelöscht und mein Savegame gestartet.
Rausgetabt und mal in die Log geschaut. Die Call Stacks sind noch nicht vorhanden also sieht es so aus das deine Vermutung das sie schon beim Spielstart da sind nicht richtig.
Wie gesagt hab null Ahnung davon und verstehe nicht wirklich was diese Call Stacks bedeuten und wo sie herkommen

**Comment by ArnieD23** [comment]
Habe die besagten GC Mods von Fed auch noch nicht auf der Map verbaut aber das wird wahrscheinlich keinen Unterschied machen oder?

**Comment by Tensuko** [comment]
Naja du hast jetzt die Fliegel DPWs raus genommen (haben die Autoload ?)
Also schon eine Veränderung.
Das mit den Callstacks ist so eine Sache, da kann man nur probieren und schauen, wann sie kommen und was man gemacht hat zu dem Zeitpunkt und ob das ganze reproduzierbar ist.
Ich hatte eben auch 3 CallStack Einträge und bin noch nicht dahinter gekommen, wo die her kommen.
Kann CP sein kann AD sein kann GC sein, oder der Horror: Eine Mischung aus allen 3...

**Comment by ArnieD23** [comment]
Ja die haben Autoload, aber der Call Stack ist ja nur aufgetreten sobald der CP Helfer fertig war und ich zu dem Schlepper getabt habe, dann war Freeze und die Log voll.
Was ist AD?

**Comment by Tensuko** [comment]
AutoDrive.
Wenn es daran liegt, dann müsstest du das ja mit Maschine X und Tracktor X auf Map Y und Feld Z immer wieder reproduzieren können. Wenn du etwas änderst (eines nach dem anderen) und der Fehler weg ist, dann weis man woran es liegt :)

**Comment by Tensuko** [comment]
Achja, schlechter Convert oder was ist da passiert:
Load mod: FS17_cargopack (Version: 1.0.0.2) (Hash: 68073b8f6918a29b232c3c5dfe61ec51)
Error: Unsupported mod description version in mod FS17_cargopack

4 verschiedene 500er Fendt Favorit Mods hast du auch drin (muss sowas sein ? - Es werden immer mehr je mehr ich durch deine Log Scrolle...)

Hab auch immer noch die FED Mods in verdacht, ich bin am laden, dauert aber noch...

Der FS19_ITS_SynTrac ist (oder war?) nicht kompatibel zu CP.

Und mehrere Maps im Modordner ging noch nie gut...

**Comment by ArnieD23** [comment]
Naja das Problem tritt ja bei verschiedenen Schleppern, auf verschiedenen Feldern und verschiedenen Maps auf. Immer wieder sobald er mit einem Feld fertig ist und in Wartestellung geht.
Ja ich weiß die 500er Fendt vergesse ich immer raus zu nehmen.
Das der SynTrac nicht CP fähig ist oder war habe ich keine Ahnung.
Und die 2te Map hab ich wohl auch vergessen.
Hab jetzt mal die Sachen entfernt und werde heute Abend weiter testen ob da Problem wieder kommt.
Bin ja schonmal sehr froh das du deine Zeit für mich opferst.
Wie sieht es mit Seasons aus? Könnte das auch ein Problem sein?
Naja ich werds testen und berichten

**Comment by Tensuko** [comment]
Seasons wüsste ich jetzt nicht, kanns aber auch nicht ausschließen.
Du wirst wohl oder über deine Mods durchschauen müssen...
