### ISSUE TITLE
Worker charging for fertilizer when disabled on seeder/planter

### ISSUE THREAD

**Issue by Doczott** [Courseplay/courseplay#4116]
When having the worker able to buy fertilizer enabled, workers will charge for fertilizer even when the seeder/planter has the fertilizer function disabled for the course. v6.01.00282dev

**Comment by edkitch** [comment]
I have also been having this on several save games. Even with a seeder or fertilizer full the amount never drops and you are charged extra. I had this on v6.01.00283.dev

**Comment by Tensuko** [comment]
Not sure how CP handels deactivated fertilizer on seeder.
Or if I just imagine, when you got another mod to deactivate fertilizer, how would FS19 handle this.
We need to look at it later I guess, this won't be on high priority, as you can turn off the buy fertilizer option ingame as a workarround.

**Comment by mlcjohnson16** [comment]
Let me know what I can do to help with reproducing this issue.  I have been playing with the 6.1.00395 version on a multiplayer server and we have been noticing that the driver is being charged for fertilizer even when that is disabled.  In some cases you can see clearly on the field that he is not fertilizing the field, but is still being charged; however, we have also had issues where he was fertilizing regardless.

We've noticed it with multiple different seeders / planters / potato technology.

I did try to turn off the buying of fertilizer in the game options as well, but then the worker would not proceed at all.

**Comment by Goof245** [comment]
Still happening for me on latest CP version 6.02.00005. Fertiliser setting in CP advanced settings is deactivated, but worker is still charging for fertiliser and it's still being applied to the field.
![20200505184546_1](https://user-images.githubusercontent.com/3851003/81049161-0469c000-8f01-11ea-8108-3b0677d6f5bf.jpg)
![20200505184553_1](https://user-images.githubusercontent.com/3851003/81049166-06cc1a00-8f01-11ea-82db-b5ec1c60c2c9.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/4579741/log.txt)
Not sure what debug settings would help for this :|

**Comment by Tensuko** [comment]
I would like to see a screenshot of your ingame settings where you also turn on and off the AI Cars and automatic engine start and such

**Comment by Goof245** [comment]
![20200505204515_1](https://user-images.githubusercontent.com/3851003/81058260-6af6da00-8f11-11ea-912d-f3fde15fe81c.jpg)

**Comment by Goof245** [comment]
FWIW, last time I was trying to find workarounds for this issue (can't remember what CP version that was), dumping the fertiliser out of the seeder would cause CP to complain it was empty. **This time** though dumping the fertiliser out, with buy fertiliser set to off, results in the CP worker just using seeds without wasting fertiliser...

![20200505210140_1](https://user-images.githubusercontent.com/3851003/81059356-a2ff1c80-8f13-11ea-809a-56f6ab77a755.jpg)

"Dry" colour of field shows it's unfertilised, also no fertilisation showing on the map, so at least we have a workaround this time.....for this seeder at least...

**Comment by Tensuko** [comment]
![81058260-6af6da00-8f11-11ea-912d-f3fde15fe81c](https://user-images.githubusercontent.com/27344744/81059881-a40f5a00-8ed1-11ea-967b-c68216f8e78f.jpg)


Closed........

**Comment by Goof245** [comment]
.........and if that setting is off, it uses the fertiliser in the seeder tank, **ignoring the CP setting that specifically says the fertiliser function is to be disabled**??? Is that option in the CP settings for decoration? Can CP even control this in the FS engine or is it a relic from older FS versions?

Like I said before, in prior CP versions you **had** to have that on, or set up a refill, or CP wouldn't run the course at all.

**Comment by Tensuko** [comment]
It works as it should, I just had someone else who confirmed it.
Helper buy it, CP will always buy fert, no matter of the otehr option.
Helper don't buy it and fert is activated, it will use whats in the tank untill empty.
Helper don't buy it and fert is deactivated, it sow without fert.

Do you even click on ok in the advanced settings after turn off the fertilizer ?

**Comment by Goof245** [comment]
> Helper don't buy it and fert is deactivated, it sow without fert.

Nope, CP worker sows and uses fertiliser from the seeder tank, ergo the CP option is ostensibly doing nothing. 

Yes I'm clicking OK to make sure the option saves.

**Comment by Tensuko** [comment]
Thats just half correct.
The option does indeed do something, you can run the seeder without fertilizer in it and don't buy fertilizer. So CP ignores the fact that there is no fertilizer in the machine.

What was missing is the option itself, so the machine fertilizing gets deactivated, well yea that was my bad and I missed this. Shit happens.

You can only notice this, when you have fertilizer in the machine and turn off the ferti option in cp settings.

But what is fact, this Issue was about 'Worker charging for fertilizer when disabled on seeder/planter'
and that was solved, couse that option in Ingamesetting was on.
Ofc this will change when I fix what I missed out in the code.

**Comment by Goof245** [comment]
Yeah I misread the initial issue I think....

**Comment by pvaiko** [comment]
Should now be fixed.

**Comment by Goof245** [comment]
With the CP option set to deactivated, and the FS 'helper buys fertiliser' set to on, the CP worker will now deplete money that's accounted as fertiliser in the finance screen. However he won't lay it on the field. Turning the 'helper buys fertiliser' off stops the money drain. When this option is off the CP worker also correctly fertilises from the seeder tank according to the CP option.

Still not **quite** perfect, but this is way easier to work around :)

**Comment by pvaiko** [comment]
@Goof245 awesome, I just wanted to make it work and completely ignored the financial aspect of it...
