### ISSUE TITLE
CP tries to fill already full Väderstad Tempo L 16

### ISSUE THREAD

**Issue by SteelRodent** [Courseplay/courseplay#4118]
This is not a new issue, but I thought I had fixed it by replacing the planter. Also not sure when it started, but several builds ago.

CP will drive to refill the planter as normal. Then after doing it successfully several times, it suddenly gets stuck in the trigger saying it's "Filling 7000 of 7080" while the planter is already 100% full. Total capacity of this machine is 7080 liter.  This only happens with this machine. 
[Imgur link](https://imgur.com/BT3I9ti)

Image is from Lapacho with the MF refill sheds, but this also happens on Fellsbruun with Giants' refill silos. Otherwise this is a vanilla tractor and vanilla planter.

Once CP gets stuck like this I can stop the driver, manually drive out of the trigger and restart CP with "next nearest waypoint" , and it will drive back to the field and usually resume working where it came from without any problem. Once it's glitched, though, it seems to be 50/50 whether gets stuck on the refill again.

[Log-txt on Gist](https://gist.github.com/SteelRodent/8e1cc54ddcca9ea166ff92062683e939)

**Comment by SteelRodent** [comment]
Setting the max fill level to 99% seems to keep it from getting stuck for now.

**Comment by Tensuko** [comment]
![fsScreen_2019_10_30_18_53_51](https://user-images.githubusercontent.com/27344744/67884766-aa013880-fb46-11e9-9ff7-e5911292e1fa.png)
Can't reproduce this. I tested it with the Stuff you see there.
Is there a specific Silo that you use ? I had some trouble getting it to work couse of the lids to open on that tool, but with 2 Triggers like that (not sure about triggers with a pipe) I got it to work and it refilled.
Used V318.
Can you try this again with actual Version and maybe also show me the used Refill Silos/Stations ?

**Comment by Tensuko** [comment]
Closed due to inactivity.
Check your Refill Silos and remember if use GC get the 1.1.3.0 From GitHub (link can be found on LS-Modcompany)
