### ISSUE TITLE
Version 283.3 not loading

### ISSUE THREAD

**Issue by Maverick283** [Courseplay/courseplay#4119]
Hey everyone, just downloaded version 283.3 but the career won't load because farming sim is stuck with this log line:
[...]FarmingSimulator2019/mods/Courseplay_6_01_00283_3/course_management.lua:1698: attempt to index global 'FS19_AutoDrive' (a nil value)

**Comment by Bobster82** [comment]
You got the latest autodrive? I just downloaded courseplay 283.3 and autodrive 1.0.4.9 and works perfect.

**Comment by Maverick283** [comment]
I do not, didn't have that at all for the previous versions and that worked fine. Thanks for letting me now, on my way to download that now...

**Comment by Tensuko** [comment]
If you don't want to add or use AD, stick to V283 without the addition .x Version as that Versions are only for AD addition right now, that will change later.
Closed.

**Comment by Maverick283** [comment]
Ah thanks, must have not read that somewhere.
Works just fine with AD, thanks for the great work! Keep it up! :)
