### ISSUE TITLE
CP belädt nicht automatisch an der Beladestation 

### ISSUE THREAD

**Issue by RK54** [Courseplay/courseplay#4120]
auf der Multimap von FalPos habe ich Kurse eingefahren, beladen am Starpunkt.
Ich fahre vom Grastrockner auf den Hof zum Heulager, und wieder zurück.
Der Abfahrer macht das auch ohne Probleme, aber nur so lange ich auf dem Fahrzeug bin.
Bin ich außerhalb, und schaue dem Abfahrer beim Beladen zu, sehe ich nix, er belädt nicht.
Steige ich mit "E" ein, fängt sofort die Beladung an.
Ich habe CP 283 und GC im Mods Ordner
[log.txt](https://github.com/Courseplay/courseplay/files/3517086/log.txt)

**Comment by RK54** [comment]
eben vergessen,
das ist bei allen Ladestationen so, die GC verwenden

**Comment by Tensuko** [comment]
Ist bekannt...

**Comment by RK54** [comment]
danke für die schnelle Antwort

**Comment by hoefti10** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/issues/369
Da ist ein fix von Stephan. Kannst du ja mal testen ;)

**Comment by altbier1** [comment]
Habe das Problem auch bei Farmsilos (Farmsilo vom Maurice). Mein Kalkstreuer (Case Titan) öffnet die Plane fährt unter dem Trigger durch wird dabei langsamer und fährt danach leer wieder aufs Feld. Dort startet er erneut um Kalk zu holen. Das Durchfahren erfolgt ganz egal ob ich drin sitze oder nicht.
Meine Vermutung ist, dass durch GC und deren einen Triggerdefinition  zusehr an den Dialog / Triggersuchroutinen modifiziert werden musste...

**Comment by Tensuko** [comment]
Kannst du auf der 4ten Seite nicht auswählen was geladen werden soll ? Ich vermute mal, dass der Streuer Dünger und Kalk laden kann und dort momentan Dünger drin steht, was er an der Kalkstation nicht findet. Versuch das bitte mal.
Und bitte schreibt rein, ob es sich bei der Ladestation um ein GC Gebäude oder ob es sich um ein normales Lager handelt.

**Comment by RK54** [comment]
@ Tensuko,
ich mich mich mal ein,
das Lager ist ein normales, https://www.modhoster.de/mods/fs19_maurice_multilager_v4
Der selbstfahrer ist https://forbidden-mods.de/filebase/file/7857-case-titan-wide/
Ich habe es auf unserr Map, Mulimap: https://www.modhoster.de/mods/multimap2019--2
getestet, mit dem geichen Ergebnis.
Da der Ladekurs angehängt wird, kann man nichts auswählen.
Was mir aufgefallen ist, beim Kurs einfahren sind die "Wege" viereckig mit einer Spitze, wegweisend.
Bei diesem angehängten Kurs sind die Wege rund wie Kugeln.
Habe es auch mit Wartepunkten versucht, mit dem gleichen Ergebnis, wird erkannt, Plane geht auf, ein kurzer Klecks im vorbeifahen, das war es

**Comment by Tensuko** [comment]
Klar kann man das auswählen:
![fsScreen_2019_08_20_13_46_25](https://user-images.githubusercontent.com/27344744/63344548-fbc06200-c350-11e9-9415-63096e6091c2.png)
Da unten steht es ja, Feldkurs geladen, Auffüllkurs geladen, Kalk ausgewählt, er fährt los und lädt Kalk aus einem Multilager (ModHub). Was die anderen Mods betrifft, kann ich nichts zu sagen....
Was GC betrifft, wird es wohl noch ein update geben müssen, dass habe ich noch nicht probiert, hat aber kaum was mit einem Multilager zu tun, behaupte ich mal.
Wie es mit AD aussieht in der Kombination, müsste ich auch erstmal ausprobieren....

Du sprichst bestimmt von den kleinen Kugeln oder ?
![fsScreen_2019_08_20_13_50_01](https://user-images.githubusercontent.com/27344744/63344745-72f5f600-c351-11e9-9d3f-fe9347771b1b.png)
Das wird im DBG angezeigt und ist erstmal für den User nicht relevant. Die Kurse werden nach wie vor mit den kleinen Pyramiden angezeigt (Fahrzrichtung, liegend).

Werde mich gleich mal an GC setzen und schauen was da so abgeht mit beladen oder auch nicht beladen....

**Comment by RK54** [comment]
@Tensuko 
Du darfst mich kleen Doofi nennen.
es stimmt alles was Du geschrieben hast.
Ich schätze dass altbier1 den gleichen Fehler gemacht hat wie ich, in besagtem Silo war nichts drinnen.
Das Maurice Silo muss man erst befüllen, dann kann man auch etwas entnehmen.
Habe es mit Kalk befüllt, das Ergebnis ist da, guggst Du
![3](https://user-images.githubusercontent.com/54204656/63350264-637caa00-c35d-11e9-8085-30deaf920aef.jpg)

**Comment by Tensuko** [comment]
Nah klein Doofi nenne ich lieber keinen, das fällt sonst schnell auf mich zurück :D 
Was ich aber eben rausgefunden habe ist, dass für die Saatmaschine keine Auswahl existiert, warscheinlich weil es 2 filltrigger sind und nicht einer der X und Y kann.
Aber wenn man den Kurs richtig einfährt und nicht so wie ich mit rückwärts und um alle ecken, klappt auch das beladen von der Saatgutherstellung:
![fsScreen_2019_08_20_15_46_03](https://user-images.githubusercontent.com/27344744/63352864-2535b980-c362-11e9-8e19-3d5dc236c74b.png)

Das Problem ist, dass ich mit dem Bogen bereits einmal in der nähe des Triggers war und er dann nicht mehr befüllen wollte, starte ich beim rückwärstfahren, fährt er schön ran und befüllt brav. Wie das mit ergänzung für Dünger usw alles ist, keine Ahnung... man kommt so schwer an die FED Action Mods ran ohne Uploaded Premium.

Ich bin mir halt unsicher, wie @ThomasGaertner die Trigger eingebaut hat, ob CP auf alle Trigger, die irgend eine GC Mod verwendet, zugreifen kann. Da war halt was in  #4049 und für AD wird es wohl nen Fix für GC geben, aber da stecke ich nicht so richtig drin....

**Comment by RK54** [comment]
ich habe die Amazone Condor15001, mit der gibt es die gleichen Probleme.
Auf dem Hof gibt es Lager, bei denen kann man nacheinander Saatgut und Dünger laden.
Das klappt auch mit CP, man muss nur genau fahren, mittig unter den Ladearm fahren

**Comment by altbier1** [comment]
Manuell kann ich den Case Titan beladen, im Lager sind 1,7 Mio Kalk

**Comment by RK54** [comment]
@ altbier1,
wie Du auf meinem Bild sehen kannst, es funktioniert mit dem Maurice Silo.
Setze mal einen Wartepunkt, dann sollte es klappen

**Comment by Tensuko** [comment]
@RK54 geht es denn auch wenn du nicht im Tracktor sitzt ?
Eigentlich wollte es auch so ohne Wartepunkt gehen...

**Comment by RK54** [comment]
@Tensuko,
das ist ein "normales" Silo, ohne GC.
Das Laden geht ohne und mit Wartepunkt, Vorraussetzung, es ist was im Silo drinnen
![2](https://user-images.githubusercontent.com/54204656/63362371-02130600-c372-11e9-822d-890e82c108e5.jpg)

**Comment by Tensuko** [comment]
@RK54 absolut richtig, aber ich hatte bei meinen GC Gebäuden auch noch kein Problem, aber es scheint ja aus irgend einem Grund bei altbier1 nicht zu klappen.... Es gibt auch ähnliche Issues wie z.B. #4109

**Comment by RK54** [comment]
es wurde ja gefixt, seitdem werden die Trigger ja erkannt von GC.
Wenn altbier1 noch nicht das Update installiert hat, könnte das möglich sein.
Was mir schon aufgefallen ist, genau mittig unter die Pipe fahren, zum Abladen auch, genau mittig.
Ich habe mich gewundert, alle Fahrzeuge kommen voll geladen zurück, kontrolliert, schräg angefahren, haarscharf am Trigger vorbei.
Seitdem drücke ich F5 und sehe wie und wo der Trigger ist, seither keine Probleme mehr

**Comment by RK54** [comment]
das 4109 könnte mit den Mod Produktionen zusammen hängen.
Ich nutze die Produktionen von Farmer_Schubi, die funktionieren ohen Probleme

**Comment by altbier1** [comment]
> es wurde ja gefixt, seitdem werden die Trigger ja erkannt von GC.
> Wenn altbier1 noch nicht das Update installiert hat, könnte das möglich sein.
Update bei GC oder bei Couseplay? Hast du einen Link zum Update von GC- falls es das schon gibt?

**Comment by RK54** [comment]
@ altbier1,
ups, jetzt hast Du mich erwischt, bin mir nicht sicher, denke aber dass es CP war.
Ab 283 sollten die Trigger von CP erkannt und bedient werden

**Comment by Sualk1972** [comment]
Hallo die Hänger werden nur befüllt an GC Profuktionen wenn man im Fahrzeug sitzt kommt da noch ein Fix.mfg GC Produktionen von FED Action hänge mal meine Log mit an.
[log.txt](https://github.com/Courseplay/courseplay/files/3526756/log.txt)

**Comment by RK54** [comment]
@ Sualk1972 ,
hast Du den 3. Beitrag von oben gelesen? 
Tensuko hat doch geschrieben dass das bekannt ist

**Comment by Sualk1972** [comment]
Ja sicher hätte nur gemeint das es schon behoben wurde.mfg

**Comment by RK54** [comment]
@ Tensuko,
frage, hat sich schon etwas getan wegen dem Beladen mit CP an den GC Ladestellen?
Ich frage nur, weil ich so gut wie alles mit CP mache.
So wie im Moment, kann ich von den Maps nicht allzuviel nutzen

Gruß RK54

**Comment by Tensuko** [comment]
Noch nicht, da sich gerade 100% auf Mode2 konzentriert wird inkl. globalen Verbesserungen die es in sich haben. Ob mit dem release dann kurz zeit für GC ist kann ich nicht sagen. Eventuell mal versuchen, für GC Trigger erstmal AD zu verwenden.

**Comment by RK54** [comment]
@Tensuko,
danke für die schnelle Antwort.
Ich bleibe aber bei CP, mit AD kann ich mich nicht anfreunden.
Ich behelfe mir im Momant mit anderen Silos, oder Produktionen, die mit CP einwandfrei funktionieren

Gruß RK54

**Comment by Axel32019** [comment]
Hallo, Wer sich traut kann ja mal folgendes testen:

2 Anpassungen sind notwendig in:
Global Company Version 1.1.0.0, Datei GC_LoadingTrigger.lua
1. Die folgende Funktion ganz am Ende einfügen
```
	function GC_LoadingTrigger:vehicleHasCoursePlayActive(vehicle)
		if vehicle ~= nil and vehicle.cp ~= nil and vehicle.cp.isDriving then
			return true;
		end;
		return false;
	end;
```		

2. In Zeile 487 sollte folgendes stehen:
`	if (vehicle == g_currentMission.controlledVehicle) or self:vehicleHasAutoDriveActive(vehicle) then`
	ersetzen durch:
`	if (vehicle == g_currentMission.controlledVehicle) or self:vehicleHasAutoDriveActive(vehicle) or self:vehicleHasCoursePlayActive(vehicle) then`

Aber Achtung! Ich fange gerade auch erst zu testen an.
Was ich schon OK getested habe ist Schüttgut laden, Flüssigkeit laden.

Rückmeldung(en) willkommen :-) !

Gruß
Axel

**Comment by Tensuko** [comment]
Also wenn das die kösung ist weis ich nicht warum ls modcompany das nicht gleich mit eingebaut hat... Teste das bitte mal weiter durch und melde dich vlt krigen wir das in ein GC update

**Comment by RK54** [comment]
@ Axel32019  und Tensuko,
ich habe mal mein Glück versucht, dabei ist es aber geblieben.
Bin überzeugt dass ich in die falsche Zeile eingetragen habe, nämlich in Zeile 633
CP hat einwandfrei geladen und abgeladen.
Wollte jetzt über CP mit GC beladen, dann gibgs los.
Mit E ausgestiegen, und schon bin ich Kerusell gefahren.
Meine Log will er nicht, ist 10,1 MB
GlobalCompany/triggers/GC_LoadingTrigger.lua:487: attempt to call method 'vehicleHasCoursePlayActive' (a nil value)

**Comment by RK54** [comment]
Habe mal ein BIld gemacht, aus Zeile 487

![1](https://user-images.githubusercontent.com/54204656/66075969-00d21d00-e55d-11e9-97fe-6fc91a7f1953.jpg)

**Comment by Axel32019** [comment]
Punkt 1. vergessen / übersehen?

**Comment by RK54** [comment]
Hy Axel,
nein, habe ich auch so eingetragen wie Du es vorgegeben hast, bin mir aber nicht sicher, da wort jede Menge and stehen.
Das Bild habe ich nur gemacht, weil da was von 487 steht.
Habe es gerade noch mal getestet, steige ich mit E aus dem Fahrzeug, sofort Blick zum Himmel und Karussell

**Comment by TobiPlayZ** [comment]
Ich will keine emails mehr bekommen bitte helft mir!!!

Von meinem iPhone gesendet

**Comment by Tensuko** [comment]
Einfach den knopf unsubscripe klicken auf der rechten seite. Browser aufmachen desktop version.

**Comment by Axel32019** [comment]
@RK54 Pack doch mal Deine GC_LoadingTrigger.lua als Anhang hierher, dann schaue ich mal...

**Comment by RK54** [comment]
Hy Axel,
anders will das Programm nicht
[GC_LoadingTrigger.zip](https://github.com/Courseplay/courseplay/files/3683148/GC_LoadingTrigger.zip)

**Comment by Axel32019** [comment]
Hi @RK54 GC_LoadingTrigger:vehicleHasCoursePlayActive mitten in der Callback-Funktion playerTriggerCallback kann nicht gut gehen - bitte ggggaaaannnnzzzz ans Ende der Datei einfügen!!!

**Comment by RK54** [comment]
noch hinter die 1000 end, oder eines davor?

**Comment by Axel32019** [comment]
Hinter das allerletzte "end"

**Comment by RK54** [comment]
Hy Axel,
alles klar wird gemacht, dachte nur wegen dem Ende, dass das davor käme.
Die Zeile in 487 ist richtig?
Weil diese doch moniert wurde.
Ich danke Dir auf jeden Fall mal herzlich für Deine Hilfe.
Bin ein absoluter CP Fan, aber auch nur weil ich ein Faulenzer bin, den anderen gerne bei der Arbeit zusehe, und schon 72 Jahre Jung bin

Gruß Robert

**Comment by Axel32019** [comment]
Hi Robert,
487 ist richtig. Wurde moniert da die Funktion in 487 nicht aufgerufen werden konnte, war ja im Callback "versteckt". Für die 72 bist Du aber noch gut dabei!

**Comment by RK54** [comment]
Hy Axel,
danke für die Blumen.
Die Spielerei und das drum herum, ist für den Kopf, nicht dass da auf einmal der Kalk rieselt.
Und es macht sich bemerkbar, weil da Sachen dabei sind, bei denen man das Hirn einschalten muss, und das macht mir Spaß.
Und hier bei CP, wenn ich kann, warum soll ich da nicht helfen oder testen, ich bin doch auch Nutznießer, ich spiele und Teste auf der MM von FalPos, und nutze nicht mal die hälfte, weil noch nicht das Beladen funktioniert
Nochmals vielen Dank für Die Hilfe, weiß nur noch nicht ob ich heute noch teste, kommt auf jeden Fall ein Feedback

Gruß Robert

**Comment by RK54** [comment]
Hy Axel und Tensuko,
ich muss Euch leider mitteilen, es funktioniert einwandfrei, ich bin begeistert.
Da kommt von Tensuko die berechtigte Frage, warum hat das ls modcompany  nicht eingebaut?
Ich möchte nicht Eure Arbeit schmälern, aber für mich sind das 2 Einträge, und es geht ohne Probleme.
Ist mir auch irgendwo egal, ich kann CP jetzt fast uneingeschränkt nutzen, dank Euch, werde Euch in mein Nachtgebet einschließen.
Meine Log ist wieder sehr geschrumpft, nicht wie gestern mit über 10 MB, habe nur noch einen Error, weiß aber nicht ob das von da kommt, dem Spiel macht es nichts aus, alles im grünen Bereich.
Mir persönlich fehlen jetzt noch 2 Sachen, Überladewagen und der Schaufelmodus.
Schaufelmodus gabs ja schon mal, nur der Schlepper hat abgeladen wo er wollte.
Noch einmal meinen Herzlichen Dank an Euch, und einen schönen Feiertag
![Heu](https://user-images.githubusercontent.com/54204656/66107157-d6657b80-e5bf-11e9-83fc-68b0326f8a58.jpg)
![Mist](https://user-images.githubusercontent.com/54204656/66107164-dbc2c600-e5bf-11e9-9d1c-0983a6048260.jpg)
![Stroh](https://user-images.githubusercontent.com/54204656/66107170-e0877a00-e5bf-11e9-8084-9d4cbda10b52.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/3684907/log.txt)

**Comment by Tensuko** [comment]
> Mir persönlich fehlen jetzt noch 2 Sachen, Überladewagen und der Schaufelmodus.
Schaufelmodus gabs ja schon mal, nur der Schlepper hat abgeladen wo er wollte.

ÜLW wird später mit Mode2 rework kommen, der Mode9 und 10 funktioniert doch ?
Sonst stell deine Fragen zu dem Modus im entsprechenden Issue :) Ja kann noch etwas holprig sein, aber grundsätzlich geht es.

So und im Bezug auf GC, ich werde das mal bei LS Modcompany ansprechen.

**Comment by RK54** [comment]
Moin Tensuko,
ich hatte hier schon mal geantwortet, mit Bilder, wegen dem Mode9, bei der nächsten CP Version war es wieder grau.
Ich habe im Moment die Version 300, und da ist es immer noch grau.
Im Bild ganz unten siehst Du es
![1](https://user-images.githubusercontent.com/54204656/66108166-47a62e00-e5c2-11e9-8a6d-a4fb025fc339.jpg)

Gruß Robert

**Comment by Tensuko** [comment]
Ja moment, du sitzt ja auch im Traktor mir einem Ladewagen, da kann der Schaufelmodus auch nicht funktionieren :) Mit dem Ladewagen kannst du nur im Bunker abkippen, mit Mode10 kannst du dann mit einem Schiebeschild aufschütten und mit Mode9 (Schaufel) die Silage mit einem Frontlader oder Radlader rausholen und in einen Anhänger/Silo/BGA laden. Vlt haben wir uns in den anderen Issues immer missverstanden ? :)

**Comment by RK54** [comment]
jetzt verstehen wir uns falsch, ich wollte Dir nur zeigen dass der Mode9 grau ist.
Der sammelt sein Stroh ein, und das zuverlässig

**Comment by Tensuko** [comment]
Ja das ist auch richtig so, desshalb verstehe ich das hier von dir nicht:
> Mir persönlich fehlen jetzt noch 2 Sachen, Überladewagen und der Schaufelmodus.
Schaufelmodus gabs ja schon mal, nur der Schlepper hat abgeladen wo er wollte.

Weil der Schaufelmodus existiert ja und der funktioniert auch. Was fehlt dir denn daran ?
Der Button wird erst aktiv, wenn du auch in einem Traktor mit einer Schaufel sitzt, oder einem Radlader.

**Comment by Tensuko** [comment]
@Axel32019 
kannst du die editierte Datei von GC hier hochladen ?
Die erlaubnis habe ich von Kevin:
![ungeduldig](https://user-images.githubusercontent.com/27344744/66112771-c784c600-e5cb-11e9-9045-481ae8b4ded1.png)
Er wird es einbauen, kommt momentan aber nicht all zu viel zum LS Modden, daher kann es auch etwas länger dauern, bis GC das update krigt.

**Comment by RK54** [comment]
@Tensuko,
stimmt, auf dem Radlader sehe ich dass der Schaufelmodus da ist.
Seit damals als ich hier mein Problem beschriben habe, mit Bilder, habe ich es nicht mehr probiert.
Habe eben den Beitrag von mir gesucht, finde ihn nicht mehr, war je ein Bild mit Schlepper mit Frontlader und ein Radalder dabei.
Der Schlepper hat eine Schaufelbreit neben den Wartepunkt abgeladen, der Radlader überhaupt nicht, hat am Wartepunkt abgedreht.
Werde es heute mal testen, mein Misthaufen ist voll

**Comment by RK54** [comment]
@Tensuko 
habe es gefunden, 
ist Mode9 issue #4104

Gruß Robert

**Comment by Axel32019** [comment]
Hier die Datei für Global Company Version 1.1.0.0


[GC_LoadingTrigger.zip](https://github.com/Courseplay/courseplay/files/3687456/GC_LoadingTrigger.zip)

**Comment by RK54** [comment]
@Tensuko
in den letzten CP Versionen, ist da die Änderung von Axel dabei?

Gruß RK54

**Comment by Tensuko** [comment]
Das hat ncihts mit CP zu tun, das muss in Global Company rein. Siehe #4049 2ter Post (meiner) Unter UPDATE ... da steht alles beschrieben.

**Comment by RK54** [comment]
@Tensuko,
klar, war falsch ausgedrückt von mir, wollte wissen ob Du was weißt, ob das schon mittlerweile eingebaut ist.
Dank Deiner und Axels Hilfe kann ich anderen helfen, habe schon wieder einen User mit dem Problem

Gruß RK54

**Comment by Tensuko** [comment]
Ist noch nicht eingebaut, wird man sehen, wann Kevin das Update auf ModHub bringt.
Man kann es aber selber einbauen, siehe #4049 
Ich mache hier mal zu.
