### ISSUE TITLE
Suggestion for Convoy mode

### ISSUE THREAD

**Issue by Martinnygaard** [Courseplay/courseplay#4121]
I just discovered the beauty of convoy mode - what a blast! :D

I am using it for picking up grass on a field. I am using AD to do the unload run.

Then the leading tractor is full, it will go home and empty. 
When the 2nd tractor get closer than "min distance" to where the leading went for unload, the 2nd will stop.

My suggestion is, if the leading is away for unload and the 2nd is just waiting - why not send the 2nd for unload also, if the fill-level is above "fill until" ? Then they are both empty and ready for a new start. 

(I noticed this because my 2nd tractor was waiting 5 minutes while it was 98% full. It made very little sence)

**Comment by Tensuko** [comment]
Adding max distance request to prevent 'overtaking'.
maybe slow down if leading device is to fast with tolerance in distance.

 #6307
