### ISSUE TITLE
turn.lua:1668: bad argument #2 to 'format' (number expected, got nil)

### ISSUE THREAD

**Issue by IDeserveToBeWrited** [Courseplay/courseplay#4122]
Courseplay v6.01.00283.3
AutoDrive 1.0.4.9
[courseplay.log.txt](https://github.com/Courseplay/courseplay/files/3517247/courseplay.log.txt)
https://youtu.be/kWeZnptDy_Q
[courseStorage0011.xml.txt](https://github.com/Courseplay/courseplay/files/3517250/courseStorage0011.xml.txt)

**Comment by pvaiko** [comment]
Does this happen with v6.01.00283 too?

**Comment by IDeserveToBeWrited** [comment]
Yes

**Comment by pvaiko** [comment]
May be the same as #4072

**Comment by pvaiko** [comment]
This should now be fixed, #4072 is a different problem.
