### ISSUE TITLE
Changing tires in garage resets CP settings to default

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#4127]
If i change tires in garage, my CP settings will reset to default and its annoying to set up again my desired settings for each vehicle.

**Comment by Tensuko** [comment]
I don't think that can be changed, as it is like resetting the vehicle, wich set them to 'like you just bought it'. Sometimes it is even better, in case CP got stucked with some stuff in the vehicle.

**Comment by ThomasGaertner** [comment]
Yes, nothing to do here. The tractor with the changed wheels is a complete new one. So it’s a can’t fix ,,,

**Comment by bojanh66** [comment]
OK, thanks for clarification.

**Comment by Tensuko** [comment]
Can't fix as already said, change something on Traktor is like a hard Reset/New Traktor.

So this one can be closed :)
