### ISSUE TITLE
Error: Running LUA method 'update' - mode3.lua:65: attempt to perform arithmetic on a nil value

### ISSUE THREAD

**Issue by HC1Gunner** [Courseplay/courseplay#4128]
I’m not sure what version I was using, but a few months ago, since there the "overload" mode is not yet included in CP 6.xx, I was using an overload grain cart with the "Combi" mode between the combine and a mother bin at the edge of the field, and about 90% of the time it was working, it only failure was, after unloading, sometimes it would just remain at the mother bin, and not return to  the field when the combine was full.
Any ways last night using CP  v6.01.00279, I tried using both the vanilla Kinze, and Elmer's from the store, and the Brent Avalanche mod. I tried several times with all (3) but right after I created/saved the combi course, the 1st attempt to leave vehicle by any means, and the game would crash, PDA blew out, and none of the menus worked, I had to Alt+tab tot h desktop to kill the game.
[log.txt](https://github.com/Courseplay/courseplay/files/3522973/log.txt)

**Comment by Tensuko** [comment]
I don't know what changed for that, but Mode3 sticks to Mode2 and i guess somehow the overloader got referenced to mode3 wich coused the Error.
Normaly for Mode3 you need a waitpoint, I guess there is some conflict.
Don't think that will be fixed, before Mode2 (and Mode3) rework.

**Comment by Tensuko** [comment]
I reference this one to #3996 as it is similar. There must be some cross refernece, also it sticks to #3311 
Closed.
