### ISSUE TITLE
Thanks.....

### ISSUE THREAD

**Issue by BostonJohnny1226** [Courseplay/courseplay#4134]
Thank you for all of your hard work on this so far. If it weren't for CP, I probably wouldn't be playing FS. Keep up the great work!

**Comment by SteelRodent** [comment]
Totally agree with this. I definitely wouldn't have a thousand hours in FS19 if it wasn't for CP.

**Comment by BostonJohnny1226** [comment]
First of all, you folks are and have been doing this for FREE since FS13! In so doing, you have made a game much more playable. A simple thank you or any show of gratitude goes sooo far.
To be honest, I cringe at the thought of Giants trying to add it to FS.

**Comment by SirStranger1989** [comment]
I'd like to take a moment aswell to thank you all for the amazing work!
I'm following the development since v0.30, amazing how far you'v all come in such a short time. 

Much respect and alot of gratitude.
