### ISSUE TITLE
Map lädt seit CP - Aktualisierung nicht mehr

### ISSUE THREAD

**Issue by peramedic93** [Courseplay/courseplay#4136]
Ich habe CP auf die neueste Version aktualisiert und nun lädt die Map (NF - Marsch o.G.) nicht mehr. Gibt es Alternativen zum eventuell notwendigen Downgrade bzw. kann jemand helfen und hat eine Idee, woran es liegt?

**Comment by Tensuko** [comment]
Logfile ? https://github.com/Courseplay/courseplay/wiki

**Comment by peramedic93** [comment]
Hallo, 
danke für die schnelle Reaktion! 
Hier die Logfile: https://www.file-upload.net/download-13698257/log.txt.html

**Comment by Tensuko** [comment]
Einfach die log.txt per drag and drop in die Kommentarbox ziehen bitte, wie im wiki beschrieben.

**Comment by peramedic93** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3530244/log.txt)

**Comment by Tensuko** [comment]
Viele Modbeschreibungsfehler und dann noch sowas hier:

Error: Failed to open xml file 'C:/Users/phein/OneDrive/Dokumente/My Games/FarmingSimulator2019/mods/IndividualHudFiles_unzip/modDesc.xml'.
Load mod: IndividualHudFiles_unzip (Hash: b7f4913518c2aabc343cf631f7fdd682)

Error: Failed to open xml file 'C:/Users/phein/OneDrive/Dokumente/My Games/FarmingSimulator2019/mods/zzz_guidanceSteering/modDesc.xml'.
Load mod: zzz_guidanceSteering (Hash: 4145fa8c951b4440599ec50a7313828c)
Error: Missing descVersion attribute in mod zzz_guidanceSteering

---

Das sollte einer der Errors sein, warum dein Spiel nicht startet:
2019-08-22 09:01 Error: Running LUA method 'update'.
2019-08-22 09:01 dataS/scripts/BaseMission.lua(1881) : attempt to index field 'controlledVehicle' (a nil value)

Das kommt von irgend einer Mod, die auf Spieldaten zugreift, hat aber nichts mit CP zu tun.

---

Ein Error von CP:
2019-08-22 09:01 Error: Running LUA method 'loadSharedI3DFileFinished'.
2019-08-22 09:01 C:/Users/phein/OneDrive/Dokumente/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00288/course_management.lua:1714: attempt to call method 'GetAvailableDestinations' (a nil value)

Und das liegt daran, dass deine AD Version veraltet ist:
Load mod: FS19_AutoDrive (Version: 1.0.1.9) (Hash: 6b9cce8e25592c84cecb0b5c475b348f)
Die neuester Version 1.0.4.9 gibt es NUR im GitHub! Danach darf man im ModHub kein update ausführen, da ModHub nur nach veränderten Daten guckt.
https://github.com/Stephan-S/FS19_AutoDrive/releases

---

Noch ein Hinweis:
Load mod: Courseplay_6_01_00256 (Version: 6.01.00288) (Hash: 27df33903abe9875d7375addf211a1ed)
mach sowas nicht. Benenne die CP Zipdatei Versions unabhängig. Ich nenne sie immer FS19_Courseplay.

**Comment by peramedic93** [comment]
Okay, danke!
AD ist aktualisiert. Ich schau mal, ob es jetzt wieder läuft.
Danke für eure grandiose Arbeit, die ständigen Verbesserungen & die tolle Betreuung der Community. Ohne CP wäre der FS nicht das, was es ist. 
Ich werd' mal den Spendenbutton drücken. :)

**Comment by peramedic93** [comment]
Problem gelöst, vielen Dank nochmal! 👍
