### ISSUE TITLE
3162 Draper 45ft wrong width

### ISSUE THREAD

**Issue by Lars225** [Courseplay/courseplay#4138]
Hey, the New Holland 3162 Draper 45FT cutting unit from the New Holland CR10.90 have 13,5m instead of 13,7m

**Comment by Tensuko** [comment]
So this is about 20cm right ? ...

**Comment by Lars225** [comment]
Yes, its only 20 cm but the devil is in the Detail. I know you can change it At the course generator.

**Comment by bojanh66** [comment]
So is the real width 13.7m but CP detects it wrong or its really 13.5m but Giants wrote wrong width ?

**Comment by Tensuko** [comment]
45ft = 13,7m so it is correct. The question is if the model got the right with, I am sure CP takes the with from the notes or something.

**Comment by pvaiko** [comment]
CP uses the work areas of the vehicles/implements to calculate the width. The work areas are defined by a start/end/width node which are placed by the creator of the vehicle/implement in the model. 

You can use the gsVehicleDebugAttributes console command (and then pressing F5) to make these areas visible.
