### ISSUE TITLE
#290 release..Just want to say..

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#4139]
FANTASTIC....great work. the return for the AD courses works great..many thanks

![image](https://user-images.githubusercontent.com/30005040/63596325-e34f8200-c5b2-11e9-9f71-45a4f11095cf.png)

**Comment by pvaiko** [comment]
Would not have been possible without @Stephan-S ...

**Comment by Bobster82** [comment]
Nice work guys! Now we need a option to make maps, as the list getting huge. lol

But the return option doesnt work perfect yet as the last issue still remains (course starting of the back of the vehicle

![cp_290_1](https://user-images.githubusercontent.com/47780758/63603650-5a444500-c5ca-11e9-822b-5d0a4d73aa1d.JPG)

**Comment by pvaiko** [comment]
> But the return option doesnt work perfect yet as the last issue still remains

Jeez. Guys, let it go. It's reported over here: https://github.com/Stephan-S/FS19_AutoDrive/issues/393

**Comment by Bobster82** [comment]
> > But the return option doesnt work perfect yet as the last issue still remains
> 
> Jeez. Guys, let it go. It's reported over here: [Stephan-S/FS19_AutoDrive#393](https://github.com/Stephan-S/FS19_AutoDrive/issues/393)

A new update from u guys, is a new finding from me.
Alpha117 said it worked perfect, i say not perfect as its making strange routes ;)

**Comment by Bobster82** [comment]
@pvaiko , My excuses!... I started the return in the middle of nowhere... But u created it as a return to the closest destination. 
That works as intended and I love that Idea! Thanks!

**Comment by alpha117** [comment]
I think it is dependant on how the AD network is created. I've only done Fenton Forest 4X to bew honest and have had no issues with the return. I'll start another map and create an AD network and see how it goes.  What map would be good to do?

**Comment by Tensuko** [comment]
Is this the same as #4149 ?
Or at least similar... Just for some clean up, since I see those 2 Issues as AD Implementation Status...

**Comment by alpha117** [comment]
Agree, close this one
