### ISSUE TITLE
Courseplay doesn´t register triggers of productions in the map.

### ISSUE THREAD

**Issue by tn4799** [Courseplay/courseplay#4141]
Hello. 
I´ve planed to fill my cow feed mixer with an course in mode 1 from the farmsilo top the production with works with global company. but every time the cp-driver just drives over the trigger and continue driving without unloading.
The trigger works how it should work, manually unloading works.
And if i work with an waitpoint, i don´t resive an info that the cp-driver reached the waitpoint.

tn47

**Comment by Tensuko** [comment]
log with debugchannel 1 and 2 active.

**Comment by tn4799** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3535331/log.txt)
Here is the log file.

**Comment by Tensuko** [comment]
Need to wait for @ThomasGaertner got time to look into this

**Comment by ThomasGaertner** [comment]
do you have a savegame and courses for me ??

**Comment by tn4799** [comment]
https://drive.google.com/drive/folders/1SqujUZee_qnLMOQh1kofo8CjjaPljPra?usp=sharing
savegame, requiered mods and cp courses are in the google drive.
The cp-course for unloading at the inbuild production find you at the following path:
 Verkauf -> Mischfutterfabrik -> Mischfutter abladen Stroh

**Comment by Tensuko** [comment]
I will reference this to #4049 for Global Company Productions, as most Maps use GC now, I don't see a point in supporting other Scripts at this point. See my 2nd Post to make a early fix for GC and read for more details.

Closed.

**Comment by Tensuko** [comment]
Sry post there is in german, I forgot. There is a file that you can download and replace in your GlobalCompany.zip file that Adds CP for Triggers.
