### ISSUE TITLE
Seeding/fertilizing mode - Issue with drip hose booms(schleppschlauchverteiler)

### ISSUE THREAD

**Issue by Heartbeatss1** [Courseplay/courseplay#4144]
Hey, guys thanks for all the Hard Work but i found an Problem with the fertilizing mode.
I made an Course with fertilizing manure and get this manure automaticaly from an container.

But if the Manure Vehicle has an drip hose boom(engl. laut google für Schleppschlauchverteiler ;))
it does not correctly filled up. It starts the loading but does not Stop, if i disconnect the additional Part it works correctly.

I made an Video of this.
https://youtu.be/Rhv77YzsN-I (Video is rendering qt youtube at the moment)
The Problem is also with the original FS vehicles.
[log.txt](https://github.com/Courseplay/courseplay/files/3535789/log.txt)

**Comment by Heartbeatss1** [comment]
Hey, i found an Workaround for this. If you set an waypoint at the container it works with 3 or 4 seconds wait time

**Comment by Heartbeatss1** [comment]
i think i found the Problem with this bug.
Maybe it can help at the analysis.
Cp think that the Vehicle has more place to refill.
![20190827163410_1](https://user-images.githubusercontent.com/42302359/63860667-d0212580-c9a9-11e9-924f-27915779d94b.jpg)

**Comment by Tensuko** [comment]
Try with V337+ and report.

**Comment by Tensuko** [comment]
Should be fixed.
If have more problems, make new Issue with log with debugchannel 1 and 2 active.
Closed.
