### ISSUE TITLE
Deactivating Slurry tanker

### ISSUE THREAD

**Issue by Th301** [Courseplay/courseplay#4145]
Hey there,

when I use a slurry tanker in the fertilizer mode and a refill-course with AD, the device is not deactivated after the tanker is empty. Due to this, the tractor or self driving machine drives all the way to the refill point with increased engine speed.

This would not be a problem really but I think, this could be perhaps the reason, why it is not possible to refill at a field container. (I tried with a mod and a vanilla container).
Filling at the bga works but it takes a long time to drive there every time.

Am I doing something wrong? Any suggestions?

Greets and thanks for your awesome work!!! :)

**Comment by Tensuko** [comment]
Refill by AD I am not sure about that, I used Slurry long ago and did a normal refill router without waitpoint, just pass a Slurry Trigger and it was all fine.

@Stephan-S you know anything about this ?

**Comment by Tensuko** [comment]
Could it be the same Problem as in #4144 ?

**Comment by Th301** [comment]
Hey, good morning!

I was using drip hoses aswell, so it could be a similar problem. In the Video I can see, that the slurry wagon was not deactivated by CP, like it was in my case too. After taking over the controll and than reassigning the driver, the filling process works. I havent tried to reassign, but I still think, the missing deactivation is perhaps the key to this problem.

**Comment by pvaiko** [comment]
Will ask Giants about this as for example the Horsch Slurry Tank with the Drag Hose attached is not returned in getAttachedAIImplements() (like the Drag Hose) and therefore the onAIImplementEnd event we raise does not turn it off.

**Comment by pvaiko** [comment]
Current status: CP is doing it right, and the tanker is turned off but there's something turning it on afterwards, still looking for it.

**Comment by pvaiko** [comment]
The problem is that WorkArea:onUpdateTick() always raises a onStartWorkArea event and Sprayer:onStartWorkArea turns on the tanker if AI is driving, as Giants assumes that when the AI is driving it is always doing fieldwork. This would be way too much work to fix.

**Comment by GeorgeEarslight** [comment]
Is this relevant?
https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=138176&title=fs2019
