### ISSUE TITLE
tractor doesnt wait for manure spreader to fill completely before going

### ISSUE THREAD

**Issue by shadow250** [Courseplay/courseplay#4146]
refill course was made using a wait point to mark the fill trigger in this case a conveyor belt. 

edit: it seems that i have to aim for the back of the spreader instead on the front for it to work. seems odd to work that way.

**Comment by Tensuko** [comment]
So it is solved ? If not, Screenshot pls...

**Comment by shadow250** [comment]
yes it only works if you line up the conveyor up with the very rearmost section of the spreader. i guess you could call it solved though it would be better if it would work in the front or middle too.

**Comment by Tensuko** [comment]
How does it work manualy ? Also just rear or only back ?

**Comment by shadow250** [comment]
manually it will fill along the full length of the spreader, ive been trying to use the samson one that holds 22900 liters i think.
