### ISSUE TITLE
Error: Running LUA method 'update' - inputCourseNameDialogue.lua:116: attempt to index a nil value

### ISSUE THREAD

**Issue by biomex81** [Courseplay/courseplay#4147]
Error when try to create a new folder to save a course:
Error: Running LUA method 'update'.
../games/FarmingSimulator2019/mods/Courseplay_6_01_00290/inputCourseNameDialogue.lua:116: attempt to index a nil value

**Comment by Tensuko** [comment]
Full logfile anyway...

@pvaiko could come from AD reading ? Not sure....
