### ISSUE TITLE
V291 fix the AutoDrive direction so courses do not begin behind the vehicle

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#4149]
Very good improvement, just one more node would be good

![image](https://user-images.githubusercontent.com/30005040/63633639-9798e900-c643-11e9-977f-f06030b43317.png)

**Comment by Bobster82** [comment]
Sorry to break the fun again @alpha117 ...
But my testings didnt go that good as yours ;)

I have a question at @pvaiko and stephan (cant tag him?)
Why "can" AD does this correct and CP "can't" ??
CP asks for a route from AD but it doesnt get the same route as AD would ??

* Does CP asks AD for a route from the CP vehicle position? Or does CP asks AD for a route and AD looks at the vehicle pos too?
* If its only driving what CP does, then the route should always be 100% the same as AD provides it (only diff is CP driving the route or AD driving it) but it isnt.
Im only reviewing this from my point of view (I try to do my best ;) )

Here a vid to show u guys what im saying:
https://www.youtube.com/watch?v=qAo9nBkUKHs&feature=youtu.be

**Comment by Bobster82** [comment]
I am not a coder, so understanding ur coding is pretty hard ;)
But I see that CP changes lines in the coding to get the vehicle position correct.
But isnt it possible to ask AD for a vehicle position too??
CP asks AD for a route to field x but CP also says to AD sort out my vehicle position too... then we get it right? (im just thinking out loud. lol )

**Comment by pvaiko** [comment]
You can tag @Stephan-S. I think I did what he asked for in the AD. Eventually, we'll get it right, no worries.

**Comment by alpha117** [comment]
Evening All, 

With @Stephan-S changes to AD earlier this afternoon, it seems that my courses here at Fenton Forest are now starting in front(sorry Bob)....but this look like we now have a few minor issues.
It's  getting there, that's for sure..

1. The vehicle position on the CP 2D map is now not correct
2. In this example I select the CP liquid/refill Mode(you know which one!). On arrival at  the trigger did not refill trough. As soon as I 'stopped' the CP driver, then the option appeared to unload water(I)

![image](https://user-images.githubusercontent.com/30005040/63641212-584db500-c6a2-11e9-99e1-3d6389749dfa.png)

**Comment by alpha117** [comment]
Update on this on, not sure if this was also inV291 but this fixes the vehicle starting position with V292.  Once course is load, just move the vehicle forward less than 0.5m and the 2D point will align with start of course..all good....... Bob does it work Ok with you now?

**Comment by Bobster82** [comment]
Didnt had time tonight to get some tests done... will try it tomorrow. Thanks for the update

**Comment by alpha117** [comment]
Agree, great work by both guys

**Comment by Tensuko** [comment]
Closing this, if there is still an Issue with this, let me know and I reopen it, pls also add the required information, thank you.
