### ISSUE TITLE
Ordnerverwaltung Ordner erstellen und löschen

### ISSUE THREAD

**Issue by Mapela1980** [Courseplay/courseplay#4150]
Ich nutze schon länger CP aber hab bis jetzt nur Kurse erstellt und keine Ordner. In der Version 288 +289 geht das nicht. Ich kann keine Ordner erstellen, habe dann alle mods raus und nur mit cp und ravenport getestet, leider das selbe. Dann bin ich auf die Version 272 zurück, da geht Ordner erstellen problemlos, habe in der version 272 einen Testordner erstellt und bin wieder raus dem Spiel. Ich lade die version 289 und kann plötzlich auch hier wieder Ordner erstellen. Nun wollte ich den Testordner löschen. Das macht er leider nicht. Ist das problem bekannt? Kann jemand helfen bitte :) 
Ihr macht einen super job ich bedanke mich rechtherzlich für die vielen Stunden die ihr hier verbringt um an cp zu basteln :)

lg

Ich weiss leider nich wie man hier eine log einfügt, kann mir das jemand noch erklären :)

edit doch nun weiss ichs :)

> 
[log.txt](https://github.com/Courseplay/courseplay/files/3536978/log.txt)

**Comment by Tensuko** [comment]
Keine Probleme damit.
Ordner erstellt und wieder gelöscht.
Kann höchstens sein, dass es an der AutoDrive abfrage liegt, da du ja kein AutoDrive im Mods Ordner hast.

**Comment by Mapela1980** [comment]
Hallo, herzlichen dank für die schnelle Antwort. Also hab nun das autodrive aus dem github installiert und nun kann ich mit der version 290 ordner erstellen und löschen. 

Was ich abeer mal in die Runde werfe, was ich nicht verstehe: Der User RK54 hat noch nie autodrive benutzt und kann ohne probleme ordner erstellen und löschenin der version 290 und in der version 272 konnte ich auch ohne Autodrive Ordner errstellen und löschen. Rein Interessehalber wie kann sowas sein? Wie schon geschrieben habe ich in den Vorgängerversionen noch nie irgendwelche Ordner erstellt..
es grüßt herzlich
Mapela80

**Comment by Tensuko** [comment]
Das kann ich dir so nicht beantworten.
Eventuell wüsste @pvaiko etwas.
Du könntest natürlich mal probieren, mit Autodrive was erstellen, Route berechnen, Exportieren (das Speicher-Symbol) und dann AD wieder entfernen, ob se dann auch ohne AD geht, CP aber etwas von AD braucht.... warum auch immer, ich kann es dir echt nicht sagen...

**Comment by Tensuko** [comment]
Achja: CP V291 könnte das auch beheben!
