### ISSUE TITLE
Kuhn Deltis 1302 and PF 1500

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#4152]
Courseplay will not refill the PF 1500 additional tank for the Deltis 1302 sprayer..   nor will it properly use any fertilizer or herbicide when the main sprayer is empty and only product remains in the additional tank when starting a course.

**Comment by Tensuko** [comment]
Selected the right filltype ?

**Comment by sootysax** [comment]
yes.. it fills the Deltis 1302, but not the additional tank, just drives off - may be because you have to hit N to open the cover before it will fill

**Comment by Tensuko** [comment]
Hmm yea, that would match the same problem as we got for unloading the 2bin trailer...
I will set it as bug. Maybe logfile with debugchannel 1 and 2 to see whats up...

**Comment by sootysax** [comment]
So it's actually the extra tank in the front that is filling up... and the 1302 is not filling..  it just pulls away and heads back to the field.

https://gist.github.com/sootysax/c804e15c4fd09321e90783b77bb63eb4

If you try and drive the course with just the additional tank full, it will say that the tool needs to be filled.

**Comment by SteelRodent** [comment]
This appears to be the case for any type of sprayer with front tanks. With the Amazon sprayers from the modhub, CP will consume the contents of both the front tank and the sprayer, but it only fills the front. It still detects that the sprayer is empty, so it goes into an infinite loop trying to refill it.

I also tried getting CP to fill in the field instead (pull up to the road and fill from a tanker) to get around this, but it seems CP doesn't know how to "overload". It's a different function than the slurry containers, I guess.

**Comment by bojanh66** [comment]
I have same problem, but only when loading a savegame.
Let me explain.
CP wont start work if main sprayer is empty, but i still have herbicide in additional front tank.
If i load only few liters in main sprayer, 30-40 litres, then CP will start work.
If i stop CP and start it again, it will work just fine.
So, the problem is, CP wont start work with empty main sprayer only on newly loaded game.
https://youtu.be/dHDYdORiF4Y
