### ISSUE TITLE
CP-Fahrer belädt nicht mit Förderband 

### ISSUE THREAD

**Issue by ItsSimon05** [Courseplay/courseplay#4155]
Hey,
ich hab einen Kurs eingefahren für Silage. Wie die anderes auch Startpunk und Entpunkt ca. 100 meter dahinter. Dann das Förderband bereitgestellt den LKW auf Beladen am Startpunkt und auf Silage umgestellt. Der LKW fährt aber ohne zu halten einfach durch. Log ist fehlerfrei,

**Comment by ItsSimon05** [comment]
Nicht nur beim Förderband auch beim Hofsilo so. Nutze die Version v6.01.00275.dev

**Comment by Tensuko** [comment]
Veraltete Version.
Was meinst du mit Start und Endpunkt 100meter dahinter ?
Am besten funktioniert es so:
Start----------------- Trigger----- Ende
CP Sucht auf dem Weg zum Startpunkt nach Triggern, diese müssen sich bis der Tracktor/LKW am Startpunkt ankommt neben/über dem Trailer/Tank befinden.
Ob es bei Förderbändern so funktioniert, weis ich nicht, ansonsten beim Kurs aufnehmen einen Wartepunkt setzen, wenn der Trailer unter dem Förderband steht und beladen wird, das kann man dan per Zeit steuern oder durch den Befehl weiterfahren.

**Comment by ItsSimon05** [comment]
Neue Version geladen und es geht. Danke für die Hilfe
