### ISSUE TITLE
What's the trick to have Multiple Tools not leave a gap when running a course?

### ISSUE THREAD

**Issue by cwattyeso** [Courseplay/courseplay#4156]
Playing on the new Fenton Forest 4x Map, I figured it would be good to try and use the feature in Courseplay where you can run Multiple Vehicles Tools on a Course to make working fields easier/quicker.

I've tried it a couple of times now with Fertilisers, Ploughs, Cultivators and each time I find the same problem. When I generate the Course I'm doing my usual process, selecting no. of headlands, start on up & down rows, check the working width is correct for the tool being used, then set the number of vehicles/tools in my case so far each time I only have two vehicles or tools. Then generate the course.

Now I check the first vehicle and make sure it is set to the Left Lane Offset, and then tell it to start at First Waypoint and set it off on it's way. Then I go to the second vehicle, copy the course from the first vehicle, set it's Lane Offset to Right Land and then tell it to go off and start at the first waypoint. I then let the vehicles run and go off and do other things. When I check on them a little while later I discover the same thing:

![2019-08-26](https://user-images.githubusercontent.com/13921716/63690206-f0af7b00-c803-11e9-90ee-25db8e0353d8.png)

The vehicles drive and actually miss/leave a gap between themselves, which carries on for the whole field and across the whole course. How do you get the vehicles/tools to actually work the field without leaving a gap? For example if I have two 18m Cultivators as in the screenshot above, the two vehicles should produce a single strip 36m wide shouldn't they? Right now they produce two strips 18m wide with what looks to be 4m gap between them?

**Comment by GeorgeEarslight** [comment]
Are you sure the cultivator is 18m? Also, check if you've left any tool offsets from previous tools/work.

**Comment by cwattyeso** [comment]
Cultivators are definitely 18m, they are the Swifter ones, just before you get to the Flexicoil in the store. Both tractors are also default standard in-game Fendt 1050. No tractors have any offsets as haven't done anything else besides operate these cultivators so their only offsets are the lane ones to be either left or right of the course line.

Like I said I have also experienced this with the Hardi Rubicon Sprayer when operating two of them side by side, and also two Fendt 939 Tractors pulling the Bredal 165 Lime Spreaders.

The only way I can actually seem to stop them leaving a gap, is when I generate the course on the course generation screen to manually decrease the working width, and it's a bit of guess work and trial and error to find out how much you have to decrease the width to get it to work properly with the different tools and vehicles.

For the Culitvators above I had to manually set the width to 16m, which got rid of the gap, however then there was some overlap, which meant when the two tractors were driving towards each other, their culitvators would collide, tangle and then cause slipping, so I'd need to stop them, untangle them and then start them off again and hope they'd not run into each other again.

**Comment by GeorgeEarslight** [comment]
Did you enable the convoy option? I've worked quite many hours on #3617 with two or three tools but never had any such problems. I'll try to replicate with the tools you mention.

**Comment by GeorgeEarslight** [comment]
By the way, did you set the Tools on the generator options to 2? This is required to make a 36m course out of two 18m tools.

**Comment by cwattyeso** [comment]
I've never enabled Convoy Option ever in all my time using Course Play with FS19, I thought that was an option related to Harvesting and Trailer running, or Mode 2 which doesn't work/has been implemented yet.

Yes I set the Tools to 2 in the Course Generation Screen, have done this each time I have tried to use multiple vehicles and tools:
![2019-08-26 (3)](https://user-images.githubusercontent.com/13921716/63696365-6f131980-c812-11e9-9db7-087c643777ed.png)
The only difference in the setup between the Vehicles and Tools I have tried using is the one setting that determines which one drives on the Left of the Course Line and which drives on the Right of the Course Line:
![2019-08-26 (5)](https://user-images.githubusercontent.com/13921716/63696411-910c9c00-c812-11e9-8077-75855c566893.png)
![2019-08-26 (4)](https://user-images.githubusercontent.com/13921716/63696424-98cc4080-c812-11e9-81ae-0f540f8480c1.png)
No other offsets, tool offsets, horizontal or vertical settings are in effect. I'm not running these course merged with refill or unload courses. So should be nothing that stops the tools or vehicles just running the course generated.

**Comment by Bobster82** [comment]
@cwattyeso , the convoy option isnt going to help, that option is for not running further into the 1st tractor by the meters given in optoin...
I think its just a CP bug, that when started, cp changes the offset 
Start them again and then look at both the tractors and check the offset.
You can also see which tractor is out of line by checking the cp route line, if 1 or both are crossing that line with the tool, then the offset is wrong or the width

**Comment by Tensuko** [comment]
There is no offset in both tools.
I just tried it out and all went fine.
It can only happen if you had a tool before, that needs an offset like a plough. CP somehow saves that offset.
But for the show tools no offset where calculated and they worked very nice in their 18.2m base.

**Comment by Bobster82** [comment]
> There is no offset in both tools.
> It can only happen if you had a tool before, that needs an offset like a plough. CP somehow saves that offset.

That is a good explanation for that problem, i thought it just happens sometimes random as a bug... didnt reported it...

And yes, All tools work fine here when using multiple tools on 1 field, I use that all the time ;)

**Comment by GeorgeEarslight** [comment]
Also tested, works as intended without any gaps. 
By the way, the Swifter is 18.2m not 18m. Are you using Stevie's modded versions?

**Comment by cwattyeso** [comment]
Yeah I know the Swifter is 18.2, but I never ever use machines at less then an exact figure so, I round them down to 18m exactly. I do the same when using Guidance Steering too.

I'm still not sure how I'd have managed to get any hidden offsets on the Cultivators, because I literally bought two tractors in the store, bought the cultivators, reset them all to the farm, connected them and then went to the field to start cultivating and they drove with a 4m gap between them, until I regenerated the course with their working widths set at 16m instead.

I had a similar problem then using two brand new never used on any other tool 939 Tractors on two brand new never been used before DB60 Planters, again 18m width, but had to manually set them to 16 otherwise the generated course they leave a gap.

Finally the two Fendt Rogator Liquid Fertiliser Sprayers, they have never had any tools attached to them, they have no attachment options, but again when trying to fertilise with two of them at their 41m working width there is a gap. So I've had to decrease the width on those to 39m to ensure the field is covered correctly.

**Comment by GeorgeEarslight** [comment]
@cwattyeso I really don't know what else to add to this other than try to test on a base map without any other mods except Courseplay.

**Comment by GeorgeEarslight** [comment]
@pvaiko It's pretty much functional but I need to rebase after my extended vacation/break from coding CP. I'll try to wrap it up within September if that's OK with you.
I'd also like to implement #4121 for multiple fillable tools, it's a nice idea, in line of what I was thinking originally.

**Comment by Tensuko** [comment]
I don't get how you getting a gap between those tools.
What happens when you set a course for only one tool ?
Even with headland they won't make any stuff like that.

**Comment by Bobster82** [comment]
@Tensuko , lol I just had this issue again... Used the biggest seeder (25m) then I started the course from outside the field. When started, the seeder went way outside the field line, so i checked the offset, and yes it was set to 4m ??? I dont even have a tool that uses offset, so I never changed the offset ;)
Log was clean, so can't proove any

**Comment by Tensuko** [comment]
At least we know that it comes from an offset. Now need to find how and where does the offset comes from.
@pvaiko got an Idea ?

**Comment by Bobster82** [comment]
any debug channels that give info on that? maybe i can try to reproduce it with more info for u guys

**Comment by Bobster82** [comment]
Sorry @pvaiko , It was not the tool offset, it is the lane offset... didnt had channel14 on, I hope I can recreate it
![cp out of line](https://user-images.githubusercontent.com/47780758/63853241-76652f00-c99a-11e9-837f-06afae988663.jpg)

**Comment by Bobster82** [comment]
I got 1 again, but didnt see any offset in the menu, but saw the tool out of line
I hope u can find some problems in the log...

![cp out of line2](https://user-images.githubusercontent.com/47780758/63854262-10c67200-c99d-11e9-9095-d19c8a78234e.jpg)

[log cp out of line.txt](https://github.com/Courseplay/courseplay/files/3550747/log.cp.out.of.line.txt)

**Comment by cwattyeso** [comment]
One thing I am noticing that may be contributing to this issue, is that when you have finished a course with vehicles and tools in multi-tool mode, when you clear the course, the lane offset values don't also get cleared or returned to default. Instead of being Left Lane/Right Lane, courseplay is actually then converting this to an actual X No. Meters Offset Left or Right, which annoyingly, persists then on the vehicle even after closing courseplay, exiting the game, re-starting the game and reloading. I wonder if this X Offset then gets factored into the equation when you generate a new course then on another field?

I have found that by making sure the offsets are completely gone, and the best way I find to do this is go into the workshop on a vehicle or tool, as that seems to completely reset courseplay settings on it and then go generate a course and let the vehicles run they seem to run okay and don't leave a gap. However should I after doing a field, just clear the temp course, move them to a new field and then generate a new course and set them off they can then get the gap again. I assume because after clearing the course, course play has then converted the Left/Right Lane offset into an actual Distance Offset.

**Comment by raxtor** [comment]
Happened to me when I accidentally loaded 2 times same course, so combine had 2 fieldworks from same course. No idea if it can be releated to this problem.

**Comment by CaptSully** [comment]
Is it possible you have "Symetric Lane Change" activated on one of your tractors? That will produce a similar affect.

**Comment by pvaiko** [comment]
Does anyone have any idea what the status of this is? Don't have the time to read through all seems to be a lot of different things mixed.

**Comment by Zoochase** [comment]
I've had this happen a few times as well.  I would just flip the "Lane OffSet" from left to right and back a couple times and that would fix it.  It's like it has the wrong amount of off set left from a previous course but you can't see it because it says left and right not showing the amount.

**Comment by pops64** [comment]
I have briefly skimmed this don't know if this has been tried. But ensure you are creating one course then copying that course to the other tractor. As this was the way I intended for this feature to work when originaly designed. If you make two different courses on each tractor there is a chance that there won't be alignment between the courses. With the old 17 course gen you could get way without copying. But with new 19 you must. The last time I checked it is not 100% repeatable

**Comment by Tensuko** [comment]
Hope this works...

Sorry folks, there is a big fix for the multi tool problems is in the works, until then, try with 386.

_Originally posted by @pvaiko in https://github.com/Courseplay/courseplay/issues/4968#issuecomment-589639859_

**Comment by pops64** [comment]
Without seeing how the courses are setup here I am still confident that this issue is separate from that.

**Comment by Tensuko** [comment]
Try with newest Version and Report back.

**Comment by Tensuko** [comment]
This should be working fine now, if have more Issues with new Mutitool feature, make a new Issue.
