### ISSUE TITLE
CP601_00293 - no crosspoints with loadCoursesAtStartup active="false"

### ISSUE THREAD

**Issue by caplink811** [Courseplay/courseplay#4160]
at least with the version named above, there are no crosspoints anymore, with settingparam false, neither I load the course before... please see screenshots.

1st with param=false

![fsScreen_2019_08_26_20_58_40](https://user-images.githubusercontent.com/49813958/63716653-c7640e80-c846-11e9-9189-cf0c23099d0e.png)

2nd with param=true

![fsScreen_2019_08_26_21_05_28](https://user-images.githubusercontent.com/49813958/63716671-d77bee00-c846-11e9-9445-073dba2d1197.png)

in the 1st case I load the foreign course at first, and than I expect the crosspoints should appear, but they don't.
Maybe, I understood wrong, but my understanding was, at least I should see the crosspoints from the foreign course, when I load it before.

thx

**Comment by Tensuko** [comment]
Thats why it was taken back few versions ago, becouse you can't see the crosspoints.

If you want to see them, you got to load all the course at start. (=true)
If you don't need, them, you can load your game faster. (=false)

Closed, you can still rply to this in closed state, but won't make an Issue out of it, as I don't think there is an other way for it (@pvaiko or got any Idea ?)

**Comment by caplink811** [comment]
ah ok, so I misunderstood, with param=false, there are no crosspoints anymore, ok, thanks for clarify this behaviour.
