### ISSUE TITLE
CP does not respond

### ISSUE THREAD

**Issue by VENAAAA** [Courseplay/courseplay#4161]
CP doesn't work. It does not start. I only turn on HUD via CTRL + DELL. And even then it does not work. I tried only CP in mod folder. SRY translator
[log.txt](https://github.com/Courseplay/courseplay/files/3545599/log.txt)

ver. - Courseplay_6_01_00293
FS 19

**Comment by VENAAAA** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3545616/log.txt)
empty mod folder

**Comment by Tensuko** [comment]
Right Mouse Click ?
Also doesn't work ?
Normaly it is set to Mouse and you have to change it to CTRL+DEL in CP HUD Settings.

**Comment by VENAAAA** [comment]
Right Mouse Click It also doesn't work.
There is nothing to click in the HUD. Does nothing.

**Comment by Tensuko** [comment]
Screenshot ? When HUD is on, what do you want to click ?

**Comment by VENAAAA** [comment]
All icon does not work. 
![1](https://user-images.githubusercontent.com/25279042/63771062-b9f66500-c8d6-11e9-8216-c6c640b4ea53.jpg)

**Comment by VENAAAA** [comment]
I can only display the HUD. And just CTRL + DELL.
Nothing else goes on.

**Comment by Tensuko** [comment]
Even the white one doesnt work ?

**Comment by VENAAAA** [comment]
No, not even the white one

**Comment by VENAAAA** [comment]
I had a stream version of the game. They stole me. He bought the boxed version and reinstalled it.

**Comment by Tensuko** [comment]
Steam or Boxed Version doesn't matter, as long as you got the newest Patch.

**Comment by VENAAAA** [comment]
version I have. 1.4.1

**Comment by VENAAAA** [comment]
Because of the boxed version of the game, I have a DVD emulation. Can't it be that?

**Comment by Tensuko** [comment]
No Idea.

**Comment by Tensuko** [comment]
No Idea.

**Comment by pseikoNL** [comment]
Emulation should not give a problem with CoursePlay, I run an iso image of FS19 on my system as well (so the disc stay nice and clean in the box) and CoursePlay function correctly.

**Comment by VENAAAA** [comment]
Helped to reinstall the game

**Comment by Tensuko** [comment]
Solved ?

**Comment by VENAAAA** [comment]
Solved.
