### ISSUE TITLE
Suggestion: Pipe side setting for Spiral generation

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#4163]
Hey,
I noticed a problem with the ~~racetrack and~~ spiral course generation:
in RL they are used to keep the Pipe on the opposing side of the crop for long fields, but there is no setting in the generator for choosing wich side of the combine should be kept away from the crop, causing the generator to sometimes generate courses, where its impossible to unload on the go, because the pipe is always facing the crop.

I hope its possible to implement this, or even automaticaly check, on wich side of the Harvester the pipe is.

greetings,
JD_Tiger

**Comment by Tensuko** [comment]
CW and CCW ?

**Comment by JDTiger** [comment]
err, yes, sorry, those two kinda confuse me :D

the problem exists only in the spiral mode.

Additionally, is the a page explaining the different modes and how/when best to use them?

**Comment by JDTiger** [comment]
The problem exists at least on Fields 26 and 14 of the KAndelin map, when the generator has to split the field.

The first Block works fine, but the other blocks are pipe towards the crop when using spiral mode.

Generated course, field edge file adn a screenshot of the course generator window: [Sprial.zip](https://github.com/Courseplay/courseplay/files/3562559/Sprial.zip)

**Comment by Tensuko** [comment]
@pvaiko you did something for Lands pattern if I remember correct, is it for racetrack too ?

**Comment by Tensuko** [comment]
#6659 duplicate

**Comment by rohne83** [comment]
Wouldn't say that's a duplicate. 6659 is rather for splitting the field into parts with definable width which shall be processed one after the other, as already possible with lands pattern. While the intention here seems to be a different one. Or you're planning to have this treated there as well?
At the moment it looks like you always have to start your spiral course at the first half of a short edge. All other start points would result in different turn directions for headlands vs field rows (if your headlands are worked clock-wise, the field rows go ccw and vice versa). Not sure whether it must necessarily be a user setting. For spiral it would be enough if headland and field row turns are always the same direction, independent of where your starting point is. And for racetracks I don't see much use, as fruit side is always changing from lane to lane anyway.

**Comment by pvaiko** [comment]
The plan is to handle it in #6659 since the lands pattern already has the pipe side logic.
