### ISSUE TITLE
Seeding/Fertilizing (Mode 4) not return to last waypoint (CP/AD)

### ISSUE THREAD

**Issue by MADxHAWK** [Courseplay/courseplay#4164]
I found a problem with fertilizing (Lime) on a CP course with AD used for refilling.
After refilling, the spreader dont return to the last waypoint when it have to U-Turn to reach it. 
It Heading toward the Point but start U-Turning way befor it reaches a posittion, so it can actually reach the last waypoint and start running away. 
![fsScreen_2019_08_27_16_55_32](https://user-images.githubusercontent.com/8193408/63783668-adc9d200-c8ed-11e9-8fd8-368938ad2737.png)
When Reaching Waypoint 15 of the temporary course the Vehicle starts a 180 deg. U-Turn instead of following the plottet course and ran off. 
Same happens sometimes, depending on the angle the vehicle approches the last waypoint, escpacilay when the angle is close between 45 -90 deg relative to the driving course.
![fsScreen_2019_08_27_16_55_55](https://user-images.githubusercontent.com/8193408/63783859-fa151200-c8ed-11e9-921a-89cc118ae332.png)

CP Log: https://pastebin.com/4hsaGD0e
Even this happens sometimes with default Tractors / pulled spreader too, this is the mod i used noticed this problem after every refill: https://www.modhoster.de/mods/terragator-6203-v2-1-fs19

**Comment by pvaiko** [comment]
Could you try this with:
1. a bigger turn radius set, the mod may not have the correct turn radius.
2. at a lower speed

Also, if you happen to have a savegame on a stanard map with standard tools to reproduce it, that would be great.

**Comment by MADxHAWK** [comment]
I could try, but i dont have a save on standard map since i play on MultiMap modmap. 
If i find some time i will try to reproduce it on a standard map.
I will try reduce speed and increas turn radius on my current game and will report back

**Comment by pvaiko** [comment]
Try with 297 and reopen if it does not fix it.

**Comment by MADxHAWK** [comment]
Will test it and report back, tyvm :)

**Comment by MADxHAWK** [comment]
@pvaiko by now none of my vehicles ran off with the latest version, seems like you fixed the problem, thanks a lot :)
