### ISSUE TITLE
Problem to load Geiselsberg map.

### ISSUE THREAD

**Issue by mauma123** [Courseplay/courseplay#4165]
I dont know is this problem because cp&ad or is the map only broken somehow.
It load everytime when i use only cp or ad mod, but dont work if i use them both sametime.
[log.txt](https://github.com/Courseplay/courseplay/files/3547809/log.txt)

And it does that error in every map loading.

**Comment by mauma123** [comment]
Looks like that newest autodrive update what came like 15min ago repair this problem.

**Comment by Bobster82** [comment]
lol, u used a pretty old autodrive when it happend ;) glad its working now

**Comment by Tensuko** [comment]
1.0.4.9 minimum.
1.0.5.1 is out now.
