### ISSUE TITLE
Question about Mode 9 (Shoveling)

### ISSUE THREAD

**Issue by MADxHAWK** [Courseplay/courseplay#4166]
I ran into 2 problems with mode 9 and need some advice. 
Sorry usesd wrong mode in headline

1. When using a wheelloader telescope loader to empty a bga-silo into a trailer eeverything wors fine untill the loader gets close to the trailer, short befor unload the loader went into a curve driving straight to the front or end of the trailer to unload even the course is straight, see screenshot.
![fsScreen_2019_08_17_00_32_18](https://user-images.githubusercontent.com/8193408/63861165-ab797d80-c9aa-11e9-98cc-4aae3331a3ac.png)
This happens regardless if i use vanilla vehicles or modded ones, so i doubt its because of a mod. 
While Creating the course, i drove close to the trailer. stopped, set the parkingpoint, then set the drive backward option, drove back in a straight line, disabled backward driving and drove back to the silo. 

2. Whenn using CP to empty a BGA-Silo into the fermenter everything works fine untill the fermenter is filled. CP Stops the wheelloader in front of the fermenter and seems to wait until there is enough spae to unload the shovel, Anyway CP seems to stuck in this waitingstate forever and never continue the work until its restarted. 

Any advice would be nice, i have a Silo filled with 5000m³ or 5 Mio liter to empty :/

**Comment by ThisPf** [comment]
Try to put the endpoint closer to the trailer. For me it worked, if the endpoint was about in the middle of the trailer.

**Comment by MADxHAWK** [comment]
Thanks vor advice, i will try :) 
Just one question, with "Middle of the trailer" you mean the lenght or widht axis? 
When i set it to the middle of the wifth axis, will the wheelloader not crash into the trailer whil trying to reach the endpoint?

**Comment by Tensuko** [comment]
I think the wheel loader waits for a trailer to arrive and stays more far away. So the wheel loader doesn't wait at the position where it tips.
At least like that it was in FS17.

**Comment by ThisPf** [comment]
like on this picture, the trailer stands under the endpoint:
![image](https://user-images.githubusercontent.com/25609067/63881080-5734c480-c9cf-11e9-89d9-c04655c55b5d.png)

**Comment by MADxHAWK** [comment]
Ok Thanks, will try this :)) 

@Tensuko thanks for editing the title, couldnt edit it by myself

**Comment by Tensuko** [comment]
I take this one as outdated or solved.
The Unloading works best, when the Trailer is direclty under the 3rd Waitpoint.
Load the Shovel-Course, Park Trailer under the 3rd Waitpoint, remove course and directly start record the Course for the Trailer.
If have Issues with that one... Look for other Issues 1st, or make a new one with clear Issue discription :)
Closed.
