### ISSUE TITLE
Probleme mit Häckselgut abfahren 

### ISSUE THREAD

**Issue by MeckyonTour** [Courseplay/courseplay#4168]
Hallo zusammen, ich habe immernoch Probleme mit dem Häckselgut abfahren in Durchfahrsilos, dass am Ende des Silos eine Kurve gefahren wird und weiter Häckselgut als Linie hinterhergezogen wird.
CP Version 293
Karte : Nordfriesische Marsch 2.3 ohne Gräben
Fahrzeug: New Holland T6 und kleinste Ladewagen alles original
[log.txt](https://github.com/Courseplay/courseplay/files/3552350/log.txt)

**Comment by Tensuko** [comment]
#3311 Mode2 kann nach wie vor nicht richtig im Bunker abladen, weil es noch der alte CP Fahrer ist und nicht AiDriver, welcher die neue Bunkersilo Berechnung beherrscht.
Alternative: Im normale Silo zwischenspeichern und mit Mode1 in den Bunkersilo füllen oder mit Mode6 Ladewagen Gras einsammeln und wegbringen.

Oder wenn es Mode2 sein soll, einfach Rückwärts im Bunkersilo abladen und mit Mode10 Silo verteilen und verdichten.

Closed.
