### ISSUE TITLE
CP läd an Produktionen weder ein noch aus und komische Logfehler

### ISSUE THREAD

**Issue by f4mous96** [Courseplay/courseplay#4169]
Hallo, 
1.wie im Log zu sehen kommt es bei mir zu fehlern die ich nicht identifizieren kann.
[log.txt](https://github.com/Courseplay/courseplay/files/3552476/log.txt)

2. Ich nutze die neuste CP-Version und spiele auf der neusten Nordfriesischen Marsch Version. die Produktionen von dem Modder habe ich nur in Kapazität und Produktion pro Stunde verändert.
Die Aufzeichnung eines CP-Kurses (von Produktion ins Lager und zurück mit Typ Abfahrer") funktioniert gut, die erste Fahrt schau ich mir auch immer nochmal an ob es funktioniert (was es auch tut) aber dann bei der zweiten Fahrt wenn ich nicht mehr drinne bin, läd er nicht mehr von der Produktion auf (erst wieder wenn ich einsteige).

Sind diese Probleme in Bearbeitung?

LG f4mous96

**Comment by Tensuko** [comment]
Das liegt an einem bug in GC.
Das war auch bei AD so.
Der Fehler wird in einem GC update behoben sein und dann kann es sein, dass es noch ein update von CP braucht (eventuell) damit es dann richtig funktioniert.

Die Error in deiner Log:
2019-08-28 19:19 Error: i3d  'C:/Users/rapfr/Documents/My Games/FarmingSimulator2019/mods/FS19_FJ_Transport_Pack/dynaloadparts/Semitractors/DLP_SemiTrailer_ConnectorUnit_SemiCargo.i3d' could not be found.
2019-08-28 19:19 Error: failed to load i3d file 'C:/Users/rapfr/Documents/My Games/FarmingSimulator2019/mods/FS19_FJ_Transport_Pack/dynaloadparts/Semitractors/DLP_SemiTrailer_ConnectorUnit_SemiCargo.i3d'

(verdammt, den werde ich auch haben...)

Und daraus resultieren die Call Stacks....
Gehe ich jedenfals ganz stark von aus...

**Comment by f4mous96** [comment]
Ist schon ein etwaiger Zeitraum bekannt wann es mit einem möglichen Update dazu kommen wird?

**Comment by Tensuko** [comment]
Nein, wenn dann musst du bei LS-Modcompany nachfragen, ich mene aber, dass das Update diese oder nächste Woche zu GIANTS gehen sollte, danach liegt es an GIANTS wie schnell das update verfügbar ist.

**Comment by rgoe** [comment]
@Tensuko - Der Fehler aus dem FS19_FJ_Transport_Pack sollte mit dem heutigen Update auf v1.1.0.0 behoben sein - konnte allerdings noch nicht testen.
https://ls-modcompany.com/filebase/file/518-friesenjung-transport-pack/#versions

**Comment by Tensuko** [comment]
Danke für den Hinweis!

**Comment by f4mous96** [comment]
@Tensuko GC ist derzeit bei Giants im Test. Wie schnell nach veröffentlichung kann man mit einer neuen CP-Version rechnen?

**Comment by Tensuko** [comment]
Da kann ich dir leider nichts versprechen, je nach Zeit und Aufwand.
Ich werde dann aber bescheid geben.

**Comment by Tensuko** [comment]
#4049 
Closed.
