### ISSUE TITLE
Tractor Refilling Amazone Condor won't leave fert trigger

### ISSUE THREAD

**Issue by MtBakerScum** [Courseplay/courseplay#4174]
Hello!

Thanks for making such an excellent mod.  I'm having an issue with my tractor not moving on from the fertilizer trigger once it fills the Amazon Condor, and moving on to the seed fill point.  It just gets stuck at the fert trigger. Haven't tried these fill points with any other equipment, was using a planter w/out a fert before.  Hopefully, I've included everything you need, let me know if not.

Thanks!

![20190828220343_1](https://user-images.githubusercontent.com/54657774/63911996-278eb800-c9e1-11e9-82a9-4716d7deb9af.jpg)

[log.txt](https://github.com/Courseplay/courseplay/files/3553915/log.txt)

**Comment by Martinnygaard** [comment]
I have experienced the ame for other seeders and spreaders (and the problem started many releases ago)

I figured out that if i lift the tractor and throw it further away on it's route (Heavy lift mod) it will get outside the fill trigger and continue the course.

**Comment by MtBakerScum** [comment]
yeah i usually just start and stop the course and it continues and finds its last spot back on the field, but its just annoying to have to monitor that...

**Comment by Tensuko** [comment]
Still valid with V357+ ?

**Comment by MtBakerScum** [comment]
Sorry I haven't played much in the last month. I'll fire it up today and check

**Comment by MtBakerScum** [comment]
@Tensuko Tried the original refill route, it does not leave the fert trigger.

I created a new course with the tractor going through the seed trigger before it goes through the fert trigger, and it successfully leaves the seed trigger and starts to head to the fert trigger.  It fills with fert then start to drive off and then gets stuck in a open/close cover loop. 

![20200112094358_1](https://user-images.githubusercontent.com/54657774/72223112-7bc5af00-3520-11ea-9b6a-24d29f46e57c.jpg)

[log.txt](https://github.com/Courseplay/courseplay/files/4050905/log.txt)

I ran with channel 1, 12, 17, and 19.  Let me know if you need anything else

**Comment by MtBakerScum** [comment]
Good news! I set up another course on a new farm and am using a modded Great Plains YP-4025A that uses liquid fert, and its working great.  Fills up at the liquid fert tip then continues on to the seed fill tip and continues on with no issues

**Comment by Tensuko** [comment]
Just as it should work.
In several tests I had to do I didn't had any Issue with refilling.
Can we take this as solved or is anything unclear ?

**Comment by MtBakerScum** [comment]
@Tensuko Up to you, i think that open close loop with the condor is a bit weird but it may have to do with the pile of fert on the ground at the tip point.  I'm also having an issue with liquid fert refilling with Custom Modding's [Great Plains YP2425A with fertilizer tank SML1000](https://www.facebook.com/custom.mdg/posts/2170220859684019).  The tractor pulls through the liquid refill point and the just buys fertilizer endlessly.  I don't know if this is a courseplay issue or an issue with the mod itself.  let me know if you want a log.txt with debug channels

**Comment by MtBakerScum** [comment]
Yeah you can probably close it.  I think any other bugs i'm encountering are with the seeder mods i'm using.  Stock equip works fine

**Comment by Tensuko** [comment]
Ok I will close this one then.
Generally it works :)
Closed.
