### ISSUE TITLE
Tractor/truck doesn't recognise combine

### ISSUE THREAD

**Issue by RedMonster-HUN** [Courseplay/courseplay#4175]
Aspects of the issue:
Aspect 1: In gamemode 2 (I think it is gm2) the tractor/truck doesn't recognise Combine and its attached header and collides with them.
Aspect 2: When truck aproaches combine to empty it, the combine stops during a turning manuever and then only makes circles without proceeding work.
Aspect 3: When a combine's grain tank gets full and the pipe is above standing grain, the combine doesn't call truck to empty it. It would be great if the combine with full grain tank would call truck even the pipe is above grain.
Aspect 4: When combine stops working due to full grain tank, it makes a reversing maneuver. When truck takes all of the grain out, it tries to leave the place. The combine tries to continue work at the same time so they collide. I think the combine should wait until truck leaves the grain completely, and only after that proceed work.

**Comment by wlfheart** [comment]
I believe these are all known issues.

**Comment by RedMonster-HUN** [comment]
Then why do these issues still exist?

**Comment by eddiem54** [comment]
#3882

**Comment by Tensuko** [comment]
They still exist becouse not done.... #3311 
Closed.
