### ISSUE TITLE
Field work course (center mode) for multiple machine

### ISSUE THREAD

**Issue by raxtor** [Courseplay/courseplay#4176]
Is possible fix course generator for multiple machines? This course only leads to combine crashes together with "L" moving from row to other row.. Correct way should leads by last headland row.
![fsScreen_2019_08_29_20_11_34](https://user-images.githubusercontent.com/831266/63965675-f6be8980-ca99-11e9-94e1-ca0da6132697.png)

**Comment by pvaiko** [comment]
Duplicate of #4091
