### ISSUE TITLE
mode 2 BGA unload speed

### ISSUE THREAD

**Issue by daan1024** [Courseplay/courseplay#4177]
Courseplay is supposed to calculate the speed at which the tractor needs to drive thru the BGA, only it doesn't seem to do that and just drives at a speed way to fast leaving about a third of the chaff outside the bunker.
the equipement is vanilla but the map is fenton forrest 4x by Stevie, the bunker is also placed in a (unused but owned) field and not a standard BGA location, it does however detect that there is a bunker pressent and procedes to unload.

**Comment by Bobster82** [comment]
@daan1024 , mode2 is still in development. U need to drive urself and use mode1 to unload in the bunker ;) (that works for me at least )

**Comment by Triple5soul89ny** [comment]
I use a Mode 2 overload an Mode1 to Bring the chaff to Silo.

**Comment by Tensuko** [comment]
Mode2 is still the old driver and doesn't use the new calculation.
#3311 
Closed.
