### ISSUE TITLE
CP stürzt ab

### ISSUE THREAD

**Issue by Landwirt56** [Courseplay/courseplay#4178]
Hallo,

CP stürzt ab, wenn ich z.B. einen Trecker auf einem Kurs fahren lasse, danach einen Trecker oder LKW fahren lassen will. Dann geht die Steuerkonsole weg sowie das Fenster , von LS, was mit F2 zu öffnen und zu schließen ist. Andere Fahrzeuge kann ich anwählen, nur das betreffende nicht mehr. 
Ich spiele nur mit Original Fahrzeugen.

**Comment by Tensuko** [comment]
Logfile ?
https://github.com/Courseplay/courseplay/wiki

**Comment by Landwirt56** [comment]
Hi,
derzeit passieret der Fehler nicht. Da ich regelmäßig ein Update von CP installiere, kann ich im Moment nicht sagen, welche Version davon betroffen gewesen ist. Wenn es nochmal auftritt, werde ich sofort den Log mit posten.
Landwirt 56
