### ISSUE TITLE
TERMINATOR TH18 and Seed Hawk XL Toolbar 84FT Refill issue

### ISSUE THREAD

**Issue by RUGhost** [Courseplay/courseplay#4179]
"TERMINATOR TH18 with TH1400" and "Seed Hawk XL Toolbar 84FT with Seed Hawk 980 Air Cart" both seeder does not refill at refill station. Driver may be detect refill station (Loading 0 of 0), reduce speed and passes away without stopping. I'm weak in English hence added log file (debug 12&14) and screenshot for better understand.
[log.txt](https://github.com/Courseplay/courseplay/files/3560447/log.txt)
![Desktop Screenshot 2019 08 30 - 20 00 38 50](https://user-images.githubusercontent.com/48012198/64031126-9eef5380-cb69-11e9-8a29-3dafe6ed0c32.png)
![Desktop Screenshot 2019 08 30 - 20 15 28 92](https://user-images.githubusercontent.com/48012198/64031232-cd6d2e80-cb69-11e9-98b5-6e5e68639f5c.png)

**Comment by Bobster82** [comment]
That seeder will only load if the pipe is out

**Comment by RUGhost** [comment]
@Bobster82 CP driver does not unfold the loading pipe.

**Comment by RUGhost** [comment]
@Bobster82 Unfolding pipe will be more problematic. Because pipe will hit the loading silo.

**Comment by Bobster82** [comment]
I know, I was just pointing out the problem ;)

**Comment by Tensuko** [comment]
What happens if you manualy unfold the pipe and let it run the course ?

**Comment by RUGhost** [comment]
I unfold pipe manually then start the course. Driver passes the refill tank without refilling. Also he doesn't fold the pipe.

**Comment by MADxHAWK** [comment]
I have noticed a problem with many "refill-stations" at least with AD, not tested it with CP jet. 

`<buyingStation stationName="$l10n_shopItem_fertilizerRefillTank" appearsOnPDA="false" storageRadius="0" fillSoundIdentifier="fillSound01">
        <loadTrigger triggerNode="3" fillLitersPerSecond="500" autoStart="true"/>
        <fillType name="fertilizer" priceScale="1.3" />
    </buyingStation>`

Many "refill-stations" missing the `autoStart="true"` option in the `<loadTrigger .... />`
At least AD always stop at the trigger but you have to jump to the vehicle and start loading manually

Anyway, as already stated the Seedhawk Aircart need the pipe unfoldd to start loading. 
Maybe you can add an option to automaticaly unfold the pipe when reaching the loadingtrigger. 
When you use this Seeder you have to pay attention to not get to close to the silo and that the silo have to be on the side of the pipe when creating the course. 

Another option is to manually refill the cart on the field with a mod like this https://www.yesmods.com/fs19-mods/trailers/auger-wagons-grain-carts/meridian-seed-express-1260-wl/
