### ISSUE TITLE
Unloading issue

### ISSUE THREAD

**Issue by Smokified** [Courseplay/courseplay#4180]
I have a route setup between a field and my farm silo.  The route seems to work fine except that when unloading, none of the grain actually leaves the trailer (TAW 30) even though the unloading animation is triggered.  I have to stop the driver, manually unload the grain, and then start the driver again for it to complete the full loop.

**Comment by Smokified** [comment]
I should note that I am using the latest version of CP as of yesterday.  I am also using the Fenton Forest 4x map by "Stevie".  The farm silo is a custom one, which may have something to do with it?  Loading and unloading at the silo works fine when done manually.

**Comment by Tensuko** [comment]
logfile with debugchannel 1 and 2 I think.

**Comment by Slick001** [comment]
I'm having the same issue, Grain loaded up and went to deliver to the Ranch and once at the tip trigger the trailer tipped up but no soybeans came out of the trailer and then it was bugged from there requiring a restart. Log file 1 and 2 included
[log.txt](https://github.com/Courseplay/courseplay/files/3567531/log.txt)

**Comment by Slick001** [comment]
Fyi..the log has some other entries on it as well. New to the Sim and mod so was playing around with the buttons. So its the last entries you will be needing

**Comment by Slick001** [comment]
Here is my log file and screen shot of my issue #4194. Hope this helps. 
[log.txt](https://github.com/Courseplay/courseplay/files/3576098/log.txt)
![fsScreen_2019_09_03_23_17_10](https://user-images.githubusercontent.com/54826978/64283520-3adbdf00-cf1d-11e9-96fd-f55dfd6859db.png)

**Comment by ridernl** [comment]
i think i found the sollution 🤔 
was messing arround with some buttons since i had the same issue.
Was sleeping when i did the post and did a few things wrong.

But now it  happend again, this is i was sure i did it right.

But it fails when field turn and path finding is off.
When you turn both back on, it works fine!

**Comment by Slick001** [comment]
I tried it again making sure those both were on. No luck. However, the tractor is behaving better when it comes to unloading the combine. Nat making erratic turns after loading. Stops and waits for combine to leave area and then pulls over and stops. I Didn't get a screen shot but it pulls over to the right a little to close so when the combine comes by on the next pass they collide.

Log file and screen shot included for the tip trigger event at the silo after trailer full from the combine.
[log.txt](https://github.com/Courseplay/courseplay/files/3598517/log.txt)
![fsScreen_2019_09_10_21_07_38](https://user-images.githubusercontent.com/54826978/64662877-928fb400-d40f-11e9-8b27-fbeef2f4f4da.png)

**Comment by Slick001** [comment]
Disregard, I got it to work!

**Comment by Tensuko** [comment]
ok, Closed.
