### ISSUE TITLE
courseplay hud not responding

### ISSUE THREAD

**Issue by ELFBOY71194** [Courseplay/courseplay#4182]
my course play hud it non responsive to any commands by mouse but will work with keyboard commands

**Comment by Tensuko** [comment]
logfile ?

**Comment by ELFBOY71194** [comment]
where do i get the log file ?

**Comment by ELFBOY71194** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3563403/log.txt)

**Comment by Tensuko** [comment]
I don't even see Courseplay in your Mods Folder and not loading. How you even get the HUD working ?

By the way, you got more then 1 Mod Map in Mods Folder, wich can cause Errors too.

**Comment by ELFBOY71194** [comment]
i shall repost my log file

**Comment by ELFBOY71194** [comment]
i sorted it with thanks to you :) it was a conflicting map

**Comment by Tensuko** [comment]
Ok, if anything new, make new Issue.
Closed.
