### ISSUE TITLE
can't get courseplay to work

### ISSUE THREAD

**Issue by tecknologic5555** [Courseplay/courseplay#4184]
So I'd like to believe I'm not a complete idiot, I've tried on multiple accounts to get courseplay to work on my FS19 I'm up to date to 1.4.0 on FS downloaded the most updated version of courseplay. I unpacked the folder went into the following folder and zipped up on the contents into another zip file renamed that zip file "FS19_courseplay" "FS_19_courseplay" "zzz_courseplay" "FS19_courseplay6" basically everything I can find on the internet to resolve this issue I've tried so far. Is there something I'm doing wrong, maybe something I missed?

**Comment by Tensuko** [comment]
Download it from here:
https://github.com/Courseplay/courseplay/releases
That File you only have to rename, no unzip and zip again.
Suggest you to rename it to FS19_Courseplay so it is easy to find and when you get a new Version and you name it the same, you replace the old, so you won't have 2 or more CP Versions in your mods Folder.
If still don't work, pls attatch a logfile.

**Comment by tecknologic5555** [comment]
Worked like a charm. I appreciate it very much Tensuko!
