### ISSUE TITLE
Issues with IC-Control and Courseplay

### ISSUE THREAD

**Issue by Serfalon** [Courseplay/courseplay#4185]
When Courseplay is in your modfolder and you want to use IC-Control in a Tractor, the mouse stutters extremely and clicking on the IC-Button's doesn't do anything.

This only happens when using a Tractor with IC and when Courseplay is in the modfolder.

**Comment by Tensuko** [comment]
How to open IC Control ?

**Comment by Serfalon** [comment]
Well IC control is opened with Space Key originally and then pressing left mouse button to interact with the IC. I've remapped IC to Alt-Left, this didn't fix it. 
The mouse is still stuck in the middle of the screen, stuttering, and flickering

This is the part of the logfile for the time where i had an vehicle with IC

[RBxyDxaT.txt](https://github.com/Courseplay/courseplay/files/3566824/RBxyDxaT.txt)

**Comment by Tensuko** [comment]
Can't see anything in that log.
I don't think we will do anything on that, at least this isn't on any priority.
I rather say the IC must be changed, as in FS17 it worked fine.

**Comment by WinssPL** [comment]
I have the same problem with Polish Pack. Is there any idea to solve this problem?

**Comment by sympathiqueone** [comment]
I am also impacted which is preventing me from using a lot of amazing mods (tractors). 
To be honest, i don't care about IC. I am hopeful a workaround will be found.

**Comment by Tensuko** [comment]
Is there a keybinding for IC ?
If so, what happen if you set a different key or simply deactivate the key ?

**Comment by sympathiqueone** [comment]
I believe the default key is space, i did unmap but the issue persist.

**Comment by sympathiqueone** [comment]
It seems IC is activated via script. I have been able to use courseplay and the Polish pack by deleting the 3 interactive*.lua files located in FS19_PolishPack.zip\Scripts. 

I haven't had any issues with the mods doing so.

**Comment by WinssPL** [comment]
> 
> 
> It seems IC is activated via script. I have been able to use courseplay and the Polish pack by deleting the 3 interactive*.lua files located in FS19_PolishPack.zip\Scripts.
> 
> I haven't had any issues with the mods doing so.
> 
> EDIT: Also tested with the John Deere 6R Series made by AgrarDesignGroup and it works.

sympathiqueone It works thank you

**Comment by WinssPL** [comment]
sympathiqueone It works thank you

**Comment by T670i** [comment]
Okay now that there are coming more and more Mods with the IC, it gets really annoying, that you can not use them with Courseplay.
So I made some investigations on whats going on there.

First of all.
IC is a Skript from Manuel Leitner (SFM-Modding). First Release was in LS09 with the Fendt 380 GTA.
When you have a look in the Skript Folder of a LS19 Mod with IC, you will see three Files:
- InteractiveControl.lua
- InteractiveComponentInterface.lua
- InteractiveWindows.lua

Looking into them, you will notice this:

-- InteractiveControl v2.0
-- Specialization for an interactive control
--
-- SFM-Modding
-- @author: Manuel Leithner
-- @date: 17/10/10
-- @version: v2.0
-- @history: v1.0 - initial implementation
-- v2.0 - convert to LS2011 and some bugfixes

Then I checked a FS17 Mod with IC. Here you get this:

-- InteractiveControl v3.0
-- Specialization for an interactive control
--
-- SFM-Modding
-- @author: Manuel Leithner
-- @date: 15/05/2013
-- @version: v2.0
-- @history: v1.0 - initial implementation
-- v2.0 - convert to LS2011 and some bugfixes
-- v3.0 - covnert to LS2013 and bugfixes

Why they are using 2.0 Version from 2010 in the FS19 Mods ?!
The FS17 Mods are using Version 3.0.
I think here might be the problem.

**Comment by Tensuko** [comment]
That I don't know why.
Problem is iirc, that IC use right click too activate.
When someone knows LUA, you can try to assign another key to IC and try it with CP.

It can't be always CP that needs adjustments, specialy when it is something that everyone knows: right click to open CP HUD.

**Comment by T670i** [comment]
Yeah i agree with you. It is not a Problem of Coursplay.
The Problem ist not Rightclick. To aktivate IC you need to hit the spacebar.
Basically it is working. The Problem is, that you can not control the mouse, cause IC and CP are both trying to affect the mouse.
I think the Problem is the old IC Version.... Why did they do that -.- Everyone is now using this old verion for their Mods.

**Comment by Tensuko** [comment]
So it is still spacebar, but then you get a mouse conflict ? Even when CP HUD is not active ?
Do you also have AD in your Mods Folder, just to make sure it doesn't interact there too.

**Comment by T670i** [comment]
If CP is active, IC is not working anymore. It does not recognize the mouse click.

Here is a Video of the behavior without CP.
In the left corner you can see, when I press the space bar.
https://www.youtube.com/watch?v=jXE1JHAJFA0&feature=youtu.be

And here with CP.
And when I open CP the mouse bounces back to the middle of the screen, when I try to move the mouse.
https://youtu.be/xXT2ut4gVHg

**Comment by Merrlin** [comment]
There is a temporary workaround like kind of thing.
If you disable IC Control in the mod everything works fine.
At least in the John Deere 6R (others i haven't tried yet ) you can disable it by editing the modDesc.xml.

Within the modDesc.xml u find 2 lines that are calling the IC Script. They are:

`<specialization name="interactiveControl" className="InteractiveControl" filename="scripts/InteractiveControl.lua" />`
and `<specialization name="interactiveWindows" className="InteractiveWindows" filename="scripts/InteractiveWindows.lua" />`

Just comment it out with `<!--` and `-->`

The red rings on the IC Elements (Steeringwheel etc.) stay. For this i have to look further in the code but i 've a significant lack of time at the moment

**Comment by ErikW0147** [comment]
So, I've just downloaded a mod that has IC, John Deere 6000 premium, and came upon this same issue.

My workaround was to bind a different key for Change IC State ingame and I managed to interact with IC points, as for Courseplay, if I want to move my mouse around I just need hold the spacebar down, this allows me to interact with the Courseplay HUD.

Hope this helps.

**Comment by Farming69** [comment]
I found a way to make it work. 
If you remap switch IC state from space to left alt. Then remap change IC state to left alt Q it should work.

**Comment by Tensuko** [comment]
This might work better now with the keybind rework I did for CP, but we won't do anything to support an old IC Script.
simpleIC is working perfect (e.g. put simple IC on middle mouse button) so nothing will happen for this.
