### ISSUE TITLE
corners

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#4187]
![fsScreen_2019_09_02_20_36_52](https://user-images.githubusercontent.com/27097241/64131808-03591f80-cdc3-11e9-932f-12f743ec09fb.png)

hello what am I doing wrong with corners it misses loads or is it a feature of courseplay im also running latest version

**Comment by Tensuko** [comment]
no logfile, no screenshot of the course or any settings.
We can't help you this way, we need more information... Tool etc too....

**Comment by matty2123** [comment]
What log do you need do I need to press a number? Also I’m using the gigantic 12 s1600 and I’ll try uploading the course

**Comment by matty2123** [comment]
![fsScreen_2019_09_03_14_04_12](https://user-images.githubusercontent.com/27097241/64175781-f59faa80-ce53-11e9-9725-6d274ea3f5cf.png)

**Comment by pvaiko** [comment]
Yeay, that's exactly what the Round corner option does. Try the smooth or turn maneuver options.
