### ISSUE TITLE
[Question] create course for Seeder with towed aircart without reverse driving?

### ISSUE THREAD

**Issue by MADxHAWK** [Courseplay/courseplay#4188]
Im now trying to create a course for a seeder with towed aircart (Like Seed Hawk / Terminator) nut always ran into the problem that CP want to reverse befor / after turning, wich will result in CP get stucked.
Even i used 3 or 4 rows of headland, which should be enough space to turn just forward driving. 
Is there any trick to make CP turning just driving forward and not backward?

**Comment by Tensuko** [comment]
There is an option named: Turn on Field, that you got to deactivate to make the big turn in the Headland.

**Comment by MADxHAWK** [comment]
Ah, ok tyvm

**Comment by Tensuko** [comment]
I guess this is solved, if you have still Issue with this, let me know and post a screenshot with debugchannels 9, 12 and 14 on.

**Comment by MADxHAWK** [comment]
Sorry, didnt had the time to try it jet, if there will be any problems i will report them ;)
