### ISSUE TITLE
HUD lässt sich nicht öffnen 

### ISSUE THREAD

**Issue by Wehnki** [Courseplay/courseplay#4189]
Der HUD lässt sich weder mit Linker Maus noch mit der Tastatur öffnen.
Habe es auch ohne andere Mods versucht ging auch nicht.

Ohne Mods
[log.txt](https://github.com/Courseplay/courseplay/files/3569290/log.txt)

Mit Mods
[log.txt](https://github.com/Courseplay/courseplay/files/3569259/log.txt)

Währe schön wenn das wieder geht, finde die CP richtig gut. 
Habe jetzt schon 3 Stunden rum Probiert Installiert/Deinstalliert, neu Runtergeladen ging alles nicht. 

MFG
Wehnki

**Comment by Tensuko** [comment]
Mit Mods fällt mir nur das auf:
Error: Invalid mod name 'IHFv0.6_unpack'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Aber ohne Mods sollte das problemlos gehen.
Ich würde mal die inputbindings zurücksetzten oder sogar einmal löschen und vom Spiel neu erstellen lassen.
Manchmal hilft es. Ansonsten gibt es keinen Grund warum CP sich im Vanilla Game nicht öffnen lassen sollte.

**Comment by MeckyonTour** [comment]
HUD geht doch mit Rechter Maustaste auf, nicht mit links?!

**Comment by Tensuko** [comment]
Wenn es an der falsche Maustaste liegt, verzweifle ich bald.... Wenn man nicht mal wenigstens beide Maustasten ausprobiert...

**Comment by MeckyonTour** [comment]
@Tensuko :dancing_men:

**Comment by Wehnki** [comment]
@MeckyonTour  oh da habe ich mich wohl vertippt :) @Tensuko okay, zurücksetzen kann ich mal probieren aber wie löschen gehen weiß ich nicht

**Comment by MeckyonTour** [comment]
@Wehnki Löschen geht ganz einfach, gehst in deinen Dokumente- Ordner, wo auch der Mod-Ordner ist und unten findest du eine Datei inputbindings, diese einfach mit ENTF löschen und dann das Spiel neu starten, dann wird eine neue erstellt

**Comment by Wehnki** [comment]
Das löschen hat geklappt, danke für die Hilfe

**Comment by Temmedde** [comment]
Hallo, habe das Problem mit der Aktuellen CP Version. Kann das habe alles ausprobiert und es funktioniert immer noch nicht, kann die CP Tastenbelegung werden mir ingame auch nicht angezeigt 
Mfg Temmedde

**Comment by Temmedde** [comment]
Hallo, 
Habe das selbe Problem mit der Aktuellen CP Version. Habe alles ausprobiert funktioniert denoch nicht, Tastenbelegungen werden mir auch nicht angezeigt hat jemand Tipps?
Mfg Temmedde

**Comment by Tensuko** [comment]
Tipp 1:
logfile anhängen.

**Comment by Temmedde** [comment]
Welchen? Oder ist das egal?

**Comment by Tensuko** [comment]
Es gibt nur ein logfile.. log.txt Es sei denn du redest jetzt vom Server, dann gibt es 2.

**Comment by Temmedde** [comment]
Danke, jetzt funktioniert es wie es soll PS: lass dir von 
Bg Werner nichts anschwätzen
