### ISSUE TITLE
course_management.lua:1714: attempt to call method 'GetAvailableDestinations' (a nil value)

### ISSUE THREAD

**Issue by dog691978** [Courseplay/courseplay#4190]
i can,t update after 287

**Comment by dog691978** [comment]
sorry and it what load the game

**Comment by Tensuko** [comment]
no logfile....
AutoDrive outdated, get the newest here: https://github.com/Stephan-S/FS19_AutoDrive/releases

**Comment by Tensuko** [comment]
Closed due to inactivity, also the Issue is known and it is the outdated AutoDrive. Get AD 1.0.5.1 or higher.
