### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by Gery2003** [Courseplay/courseplay#4191]
Abend zusammen
Wollte heute mal wieder mit courseplay Selber Hexeln und einen abfahrer einstellen dabei musste ich feststellen das dies nicht mehr funktioniert man kan zwar alles einstellen nua das Problem ist das das der abfahrer nicht hinterher fährt sondern stenbleibt wie bei drescher abtanken und abfahren gibt es dafür eine Lösung oder mit der neuen Version eine andere Einstellung in den ersten Versionen hat es ja funktioniert würde mich über eine Antwort freuen 🙂 

LG gery

**Comment by Tensuko** [comment]
Duplicate of #4193
Kein Guter Titel, außerdem #3311 
Closed.
