### ISSUE TITLE
turn.lua:2435: attempt to perform arithmetic on local 'frontMarkerDistance' (a nil value)

### ISSUE THREAD

**Issue by eddiem54** [Courseplay/courseplay#4192]
Hi,
Getting this error, tried 2 maps.
[log.txt](https://github.com/Courseplay/courseplay/files/3570870/log.txt)

**Comment by bojanh66** [comment]
I have same problem, i downgraded to previous version until this is fixed.

**Comment by Tensuko** [comment]
What did you do when this Error happened ?
Seeding was still fine with this Version, is it Harvesting ?

2nd Error is 2019-09-03 19:14 Error: Running LUA method 'update'.
2019-09-03 19:14 C:/Users/eddie/OneDrive/Documents/My Games/FarmingSimulator2019/mods/FS19_courseplay/turn.lua:625: attempt to index local 'turnContext' (a nil value)

**Comment by Tensuko** [comment]
Btw: Stick to the Release Version!
https://github.com/Courseplay/courseplay/releases
The recent update wasn't made for release, so don't update from branch, always use release page to get newest update.

**Comment by eddiem54** [comment]
Hi again,
Sorry for the delay, had to work.
It was actually cultivating: Case IH 7210 & RAU Polymag 300, both standard.

Regards
