### ISSUE TITLE
unable to unload trailer at Silo or selling points (Logs and screenshot included)

### ISSUE THREAD

**Issue by Slick001** [Courseplay/courseplay#4194]
Once the Tip Trigger is reached the trailer tips but the grain remains in the bed and then the tractor will pull out slowly with the bed still up. I have tried it several times with different parameters. Moving the trigger location to different parts of the grate, as well as, slowing down the field and turn speeds. Nothing is working. I turn off the course and return to the silo and am able to dump the grain. 
![fsScreen_2019_09_03_23_17_10](https://user-images.githubusercontent.com/54826978/64225766-7eddce00-cea2-11e9-9273-fd24797551c1.png)

Logs and screen shot included
[log.txt](https://github.com/Courseplay/courseplay/files/3572703/log.txt)

**Comment by Tensuko** [comment]
Log with debugchannel 1 and 2 active.
Got duplicate somewhere, will add reference later.

**Comment by Tensuko** [comment]
Got it #4180 post your logfile there pls.
Duplicate, Closed.

**Comment by Slick001** [comment]
will do
