### ISSUE TITLE
Tiefenlockerer wird wie Pflug verwendet

### ISSUE THREAD

**Issue by Lars225** [Courseplay/courseplay#4195]
Hallo, wenn der Courseplay Helfer ein Feld mit dem Tiefenlockerer bearbeitet entstehen zwischen 2 Bahnen ein kleiner Abstand. Ich denke es liegt daran das er mit dem Tiefenlockerer fährt als wäre es ein Pflug und so nicht die volle breite ausnutzt.

**Comment by Tensuko** [comment]
Screenshot ? Einstellungen überprüft ? Welcher Tiefenlockerer ?
Es gibt Modder-'Experten' die bauen Tiefenlockerer als Pflug um. Das ist alles eine Frage davon, was in den XML Dateien steht.
Grundsätzlich funktioniert es, ich verwende auch fast nur Tiefenlockerer und hatte noch nie schwierigkeiten.
Desshalb: Mehr Infos bitte.

**Comment by Lars225** [comment]
Siehe Bilder. Bei beiden Tiefenlockerer das selbe Problem egal ob mit oder ohne Sämaschine mit der neusten Courseplay Version.

![20190904132324_1](https://user-images.githubusercontent.com/41234245/64250922-9acf8700-cf17-11e9-9593-03d3db039350.jpg)
![20190904132349_1](https://user-images.githubusercontent.com/41234245/64250923-9acf8700-cf17-11e9-869a-a32e7645811a.jpg)
![20190904132356_1](https://user-images.githubusercontent.com/41234245/64250924-9acf8700-cf17-11e9-9461-c361b9d7725f.jpg)
![20190904132400_1](https://user-images.githubusercontent.com/41234245/64250925-9acf8700-cf17-11e9-881a-4d65bb6af830.jpg)
![20190904132406_1](https://user-images.githubusercontent.com/41234245/64250927-9b681d80-cf17-11e9-82f9-5ac3ff1ae815.jpg)
![20190904132409_1](https://user-images.githubusercontent.com/41234245/64250929-9b681d80-cf17-11e9-8085-66f35d84d948.jpg)

**Comment by Tensuko** [comment]
Dein Kurs ist ja auch auf 4.2m Breite, kann ja nicht gehen. Die Tiefenlockerer haben aber nur 4m. Die Saatmaschine ist dann wohl 4.2m die du mit dran hast.

**Comment by Lars225** [comment]
Ich hatte das Problem ja zuerst mit dem Gelben ohne Sämaschine eingestellt auf 4m. Ich habe gerade nochmal versucht den Fehler nur mit dem gelben zu reproduzieren aber es funktioniert jetzt
