### ISSUE TITLE
AIDriver.lua:1125: attempt to call method 'getTipState' (a nil value)

### ISSUE THREAD

**Issue by RUGhost** [Courseplay/courseplay#4196]
I setup a liquid manure course and place a slurry container at unloading point. When Driver reach at unloading point game freezes. 
[savegame3.zip](https://github.com/Courseplay/courseplay/files/3574229/savegame3.zip) (Feldsbrunn)
[log.txt](https://github.com/Courseplay/courseplay/files/3574240/log.txt)

**Comment by ThomasGaertner** [comment]
since we have some issues with the version numbers please update to last version and try again, the issue will be there but the line number will fit

**Comment by RUGhost** [comment]
I used the latest version available in release section (v6.01.00294).

**Comment by adastra89** [comment]
Same issue for me, using the latest version from github.

**Comment by DrGreene1981** [comment]
Same problem here. Version in use: 6.01.00300

**Comment by superblaubeere27** [comment]
I am having the same problem. Version 6.01.00342

**Comment by Tensuko** [comment]
fixed. Tested with 02.00040
