### ISSUE TITLE
Error: Running LUA method 'update' - LevelCompactAIDriver.lua:208: attempt to index a nil value

### ISSUE THREAD

**Issue by Berios** [Courseplay/courseplay#4198]
Hallo zusammen!

Als Erstes mal vielen Dank für eure Arbeit und das den Mod.
Leider habe ich in den letzten Tagen massive Probleme mit Courseplay. Ich bin bereits auf die Version 293 zurück gegangen, aber leider hat das auch nicht wirklich etwas gebracht.
Courseplay bleibt innerhalb des Spiels eine Lange Zeit stabil - aber an irgend einem Punkt macht der Mod "komische" Sachen. Heute z.B. entlädt er stundenlang im Bunkersilo die Ladewagen vollkommen korrekt. Um 20.01 Uhr macht es dann "bumm" und die Fahrer (komischer Weise aber scheinbar nur von diesem Kurs - mein Drescher hat ganz normal weitergearbeitet) fangen an mit 5 km/h stotternt zu fahren (der eine fährt nur noch 5 km/h und der andere entlädt nicht mehr richtig - siehe nachfolgende Darstelllung). Dann entlädt der Mod die Ladewagen bis auf 3 Grasshalme (echt, es waren immer 3 Grasshalme im Ladewagen), weshalb das Gespann den Abladevorgang nicht mehr zu Ende bringt. In der Log (siehe Anlage) findet sich der oben genannte Fehler. Außderdem hatte ich gleichzeitig auch den Money burn - innerhalb von ca. 8 Minuten habe ich über 100.000,- Ingamegeldeinheiten verloren. Und das Geld tickerte fleissig weiter nach unten (alle paar Sekunden ein Sprung nach unten). 

Ich hoffe, meine Beschreibung der "Spielumstände" hilft euch weiter (weshalb ich so ausführlich bin).

Danke und weiter so - trotzdem ein super Mod. :-)

Berios

[log.txt](https://github.com/Courseplay/courseplay/files/3576065/log.txt)

**Comment by Tensuko** [comment]
Money Burn könnte ein anderes Problem sein.
Könnte ähnlich wie dies hier sein #3929 
Hast du mal versucht das ganze nur mit CP nach zu stellen ?
Um einen Modkonflikt auszuschließen.
Außerdem, was ist wenn du in den AU Einstellungen, die Helferkosten auf 0% setzt.
Ich meine das CP Geld verbraucht, weil in AutoDrive Helferkosten stehen, hab aber noch nicht viel rumexperimentiert wann und wie das zu stande kommt.

**Comment by Berios** [comment]
Hallo!

Nein, leider konnte ich das Ganze nicht mehr nur mit CP nachstellen.
Der Fehler ist erst aufgetreten, als der Befüllvorgang des Silos quasi schon zu Ende war. 
Ich werde es das nächste Mal mal nur mit CP versuchen.
In Bezug auf das Geld - Problem:
Das ganze Spiel ist bei mir ca. 8 Stunden lang ohne Probleme gelaufen. CP und AD haben ganz "friedlich" nebeneinander gearbeitet. Die Löhne für beide Helfer wurden korrekt abgezogen. Erst als um 20.01 Uhr der Lua - Fehler auftrat, spielte auf einmal der "Geldabzug" verrückt. 
Interessanter Weise hat sich das Geldproblem nach Beenden des Spiels und einem Neustart sofort wieder gelegt (auch bei der gleichzeitigen Nutzung von CP und AD). Alleine die beschriebenen Probleme beim Abladen bleiben - das Stottern des anderen Gespanns war dann auch weg. Das Gespann mit dem Abladeproblem hat einmal nach dem Neustart richtig abgeladen, danach waren wieder die 3 Grashalme übrig - diese konnte ich nur über einen Silotrigger aus dem Hänger rausbekommen (das dann aber ohne Probleme). 
Könnte das eventuell an der Ablademenge (kippe im Silo ja auf den Boden - bei den benutzen Hängern sind es über 50.000 Liter auf einen Schlag) in Kombination mit einem eventuell ungünstigen Punkt oder Winkler (obwohl das Gespann praktisch gerade rückwärts ins Silo gefahren ist) liegen? Das ganze Abladeverhalten war komplett anders als bei dem zweiten, identischen Gespann. Dieses hat sich nach dem Neustrat vollkommen problemlos verhalten. 
Ich werde die Helferkosten mal auf 0 stellen - mal sehen, ob sich der Fehler dann trotzdem wiederholt.

Berios

**Comment by xgaetx** [comment]
Hello, 
I don't understand German but the title looks like the problem I have had yesterday evening on 2 occasions. The game froze for quite a while before I forced the closing of FS.
While reading the log (altough I don't really understand all of it, it appears that the message in the title comes a high amount of time).
[log.zip](https://github.com/Courseplay/courseplay/files/3581033/log.zip)

Thank you for the great mod, I don't think I would stil play FS without it.
Cheers

**Comment by Tensuko** [comment]
Not sure where to add this, but should be a collection of Mode10, so add this there for now:
#4254
