### ISSUE TITLE
Suggestion - split field work

### ISSUE THREAD

**Issue by ddiis** [Courseplay/courseplay#4199]
Recently, I use the following scheme of work - I generate a route for one device and then send several tractors to different points. Thus, they do not intersect (200 meters of the convoy are clearly not enough to avoid collisions and also do not wait for the required distance with the sprayer turned on). But there is also a problem - you must constantly monitor to manually stop the tractor when it goes to the already processed part of the field. Maybe it is possible to implement - divide the field into 2/3/4 equal parts and so that the tractor stops when it reaches the next part of the field?

![image](https://user-images.githubusercontent.com/4257956/64328210-b731f900-cfd5-11e9-80ef-2734c88819ec.png)

![image](https://user-images.githubusercontent.com/4257956/64328232-c153f780-cfd5-11e9-8e71-b7b8ab26b0f2.png)

![image](https://user-images.githubusercontent.com/4257956/64328427-15f77280-cfd6-11e9-8f57-4ab50261cd4d.png)

**Comment by Tensuko** [comment]
The only thing I can Imagine is an option, similar to stop at last waypoint to make them stop at Waypoint X.
But actually, when you use some tools and use convoy mode, there is no Issue with collission.

**Comment by ddiis** [comment]
Sometimes in large fields the distance between the rows is not maintained and 200m distances do not help. Can you then increase the maximum distance of the convoy?

![image](https://user-images.githubusercontent.com/4257956/64336947-dbe29c80-cfe6-11e9-93d2-6d4af18b7212.png)

**Comment by ddiis** [comment]
and maybe turn off the seeders or fertilizers when the convoy stops, for example, first tractor stuck, the rest stop but tools continue to work

**Comment by MtBakerScum** [comment]
Sort of on topic, I think an option to run the current field course in reverse would be handy.  So that combines are working totally different parts of the field at one time.

**Comment by Tensuko** [comment]
So you start in headland and one stats in the middle ?
Doesn't make much sense...

**Comment by MtBakerScum** [comment]
@Tensuko Well I'd probably start the 2nd combine after the headlands were created, then the first combine would be working the up/down courses from the start of the course, and the 2nd combine would be running the course in reverse and starting from the end of the original course.  Then they'd finally meet in the middle.  

I already have to control when I start the combines.  If I don't start the 2nd combine late enough on the up/down rows, they inevitably collide with their headers.  

Maybe an option could be to "Start up/down at end of course after headlands are made"

**Comment by Tensuko** [comment]
#6659 duplicate
