### ISSUE TITLE
CP mode4 crashing / restarting PC when checking field state

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#4200]
I have problem when using mode4 and checking the field state in main menu and switching panels between crops, growth stages and fertilization stages.
CP is v6.01.00294.
Problem occur even on default map Ravenport without any mod, only CP.

Can someone else test and see if they can reproduce problem?
1.start new game on ravenport
2.buy some tractor and fertilizer k165 with extension
3.put some solid fertilizer into it
4.create course on some field and let CP worker do its job in mode4
5.open main menu and start clicking on left or right arrow (picture attached) and see if your PC will restart or not
I am just curious is it problem with my PC or with CP.
![fs19-tips-10](https://user-images.githubusercontent.com/32069662/64339030-5b6e6c80-cfe3-11e9-8157-b22194e7fba3.jpg)

**Comment by Tensuko** [comment]
logfile ?

**Comment by bojanh66** [comment]
Nothing shows in logfile unfortunately, because computer restarts when that happens, its like when you press Reset button.
Could you check if same thing happens to you on Ravenport ?
[log.txt](https://github.com/Courseplay/courseplay/files/3579640/log.txt)

**Comment by Tensuko** [comment]
Will do but it is always better to have a logfile so don't need to ask for every single information that we might need.
Will check when I am home.

**Comment by Tensuko** [comment]
2019-09-05 16:01 Error: C:/Users/Gaming/Documents/My Games/FarmingSimulator2019/savegame3/courseplayCustomFields.xml. . .

2019-09-05 16:01 Error: C:/Users/Gaming/Documents/My Games/FarmingSimulator2019/savegame3/weed_growthState.xml. . .
2019-09-05 16:01 Error: C:/Users/Gaming/Documents/My Games/FarmingSimulator2019/savegame3/economy.xml. . .
2019-09-05 16:01 Error: C:/Users/Gaming/Documents/My Games/FarmingSimulator2019/savegame3/treePlant.xml. . .

Some corrupted files there or what is it about the '. . .'
Never seen them or at least I can't remember.

**Comment by bojanh66** [comment]
Bumping this thread, i am still getting crash or better said, shutdown of PC in mode4, did anyone test what i said in 1st post ?
I even updated graphic drivers to latest version, didnt help.

**Comment by Tensuko** [comment]
It is just 1 day ago andI posted you loginfo, on what you can check your game.
Try with full vanila game and only cp release 294 then try on a complete and clear savegame slot.
If I got time for it I might can test it tmr...

**Comment by Tensuko** [comment]
Can't reproduce, as I said, it should be the corrupted files in your savegame3 folder or some modconflict.
Nothing with CP.

**Comment by Tensuko** [comment]
Closed due to inactivity.
