### ISSUE TITLE
Tractor wandering off and doing loops or other strange maneuvers (multitool offset) - The inner ones (right 1 and right 2)

### ISSUE THREAD

**Issue by Crazysonoran** [Courseplay/courseplay#4202]
Dont have any screenshots but running 6.01.000294 on Countylines map and had 4 tractors plowing a field with a 6m plow. The one I set to '2 right' suddenly decides to do a left turn and just head straight off into whatever it might run into. I stopped the driver and put him back where he was supposed to be and he immediatley pulled the same stunt and started driving off, I then ran him manually for a little ways and started him up again he went a short distance then off he went again. This has done it with the '2 Right' position to me before on a different map but then it would do a sharp left then right (like a U) then resume plowing normally or do a loop then resume plowing. May be worth looking into.

**Comment by Tensuko** [comment]
logfile with 9 12 and 14 an screenshot of the course

**Comment by MADxHAWK** [comment]
Same happend to me while collecting straw using CP for collecting and AD for drive to silo. 
The problem seems to be random and is not "repeatable" on purpose. 
What i noticed by accident, it seems to happen when CP dont find or miss the final waypoint during a turning manouver or when trying to get back to the line after unloading / refilling. 
Maybe its also depends (or is triggered) by #4164 where the vehicle also ran away.

**Comment by Crazysonoran** [comment]
All I can tell you is I had 4 John Deere 6M tractors with Weba 6M plows plowing Field 23 on the countylines map. I was using multiple tools set to 4, and when I set the headlands I set it to 50 and let courseplay truncate it, the '2 Right' took is what headed off this and the previous time I've had problems, this tractor was on its second headlands pass and the other 3 tractors were still plugging away. Since then I had a single tractor which waas seeding a combined field 13/14 on the krebach SE map just started driving in circles forever when it tried to transition from the headlands to the up/down. vehicles have given me issues on the corners near the starting waypoint if the waypoints get all zig-zaggy, moving the starting waypoint down one side of the field has cures that pretty much though. I am working for 3 more days and dont have time to try to recreate this issue right now but how do I enable the logging and what did you mean by 'with 9 12 and 14'?

**Comment by MADxHAWK** [comment]
In the CP GUI Settings tab there are numbers from 1-24 at the bottom, these numberboxes enable different logging options, just tick 9,12 and 14  ;)

**Comment by C43AMG** [comment]
Happened also for me with the new patch, same routes and settings

**Comment by MADxHAWK** [comment]
Approching
![fsScreen_2019_09_09_06_42_57](https://user-images.githubusercontent.com/8193408/64503899-95828b80-d2cd-11e9-90c3-4d3d6071173b.png)
Start turning
![fsScreen_2019_09_09_06_43_02](https://user-images.githubusercontent.com/8193408/64503900-95828b80-d2cd-11e9-8a24-2c8117b82da7.png)
Turning
![fsScreen_2019_09_09_06_43_06](https://user-images.githubusercontent.com/8193408/64503902-95828b80-d2cd-11e9-9ae6-167c395849cc.png)
Running off
![fsScreen_2019_09_09_06_43_10](https://user-images.githubusercontent.com/8193408/64503903-95828b80-d2cd-11e9-8c63-d611fc582229.png)

Log: https://pastebin.com/uLPLqwPb
Hope it helps

**Comment by Crazysonoran** [comment]
Recreated an issue little different than what happened last time. This was the '2 Left' tractor, 4th one I started working but the one I generated the course with. 
![image](https://user-images.githubusercontent.com/54956919/64592799-a8df3680-d361-11e9-8118-59fd72d38d6a.png)
(Ignore the vshare on the screenshot its not relevant)

![image](https://user-images.githubusercontent.com/54956919/64592519-0de65c80-d361-11e9-9af9-6e2072d67052.png)

[log.txt](https://github.com/Courseplay/courseplay/files/3594278/log.txt)

**Comment by Tensuko** [comment]
Turn should be fixed with V316+ test and report.

**Comment by Crazysonoran** [comment]
Still does it, here is the result of my test.. 4 JD 7310's pulling a 8m cultivator on field 23 of Countylines map, Generated course using headlands set to 50 which the system truncated to the proper amount. Seems to do it only on multiple headlands which may not be common but with large squarish fields I do use sometimes. As a workaround lately I have just did the up/down after 1 headland pass.

![image](https://user-images.githubusercontent.com/54956919/67698930-7d8fc580-f968-11e9-9fd0-9f2829b1428e.png)

**Comment by Crazysonoran** [comment]
It was doing something weird in the last few seconds before I paused here. It stopped, turned left put up the 'relevanent waypoint' like it does on corners then turned back into its course and continued, it did it 3 times in a short distance. No objects directly in front of the vehicle at all. Testing with no other mods running as a test. Log file 

[log.txt](https://github.com/Courseplay/courseplay/files/3781227/log.txt)

**Comment by Crazysonoran** [comment]
![image](https://user-images.githubusercontent.com/54956919/67729856-05e58900-f9b0-11e9-97c8-e9ab99d02623.png)
When it does act up a lot of the log text disappears if that helps any. 

[log.txt](https://github.com/Courseplay/courseplay/files/3781306/log.txt)

**Comment by Tensuko** [comment]
Only one Map allowed and is this the Tractor you are useing on the screenshot ?
Load mod: JD_2130_V1_2 (Version: 1.2) (Hash: a5eaa442cded9118219bd947e95ad6e1)
Error: Unsupported mod description version in mod JD_2130_V1_2

Also this smal part of the screenshot doesn't help much... This could be anywhere in any situation.

**Comment by Crazysonoran** [comment]
I tested on 3 maps to rule out any problems with the map itself, I tested both with and without other mods to rule out a possible mod conflict, (this rules out that JD_2130 mod as a possible cause), for the record I used both the stock in-game JD 7R and 8R to rule out a problem with the tractor itself and have seen this glitch with at least 5 tools behind these 2 tractors. To say only one map allowed is counter productive to finding a fix for this bug. I saw collision detected in the log so I decided to rule out some object hiding in the map file, using another map. First picture is just simply proof that it glitched, second picture shows that a lot of the text that appears when the course is being driven disappeared as soon as it glitched. Even though that pic was taken after I stopped it the text was already gone before I stopped it. Same field as when I initially posted about this issue so the first screenshot of the course would be very similar to the one I used in one of my tests here. Map shape doesn't matter either, I've tested on randomly shaped fields as well as a square field. I have ruled out any outside problem except the background code of the game itself or the courseplay code. The latest log has more than the usually debug codes enabled, personally after watching the equipment run closely it starts to act like it is turning at the corner of the field (relevant node shows just like when its turning a corner) and since it really isn't a corner it gets confused and goes to have a beer. You might have to set up your own test and see if you notice anything abnormal as it acts up. Set up 4 tractors of a random type, with the same cultivator or plow on each, set it to use at least 5-6 headlands and watch it run. Usually the 3rd or 4th headland pass it glitches. Before it heads off it will start to glitch at least 3-4 times, where the tractor stops for a second, turns toward the field edge, decides it is wrong then turns back onto its preset course and continues. (relevant node info shows here too). Other tractors that are behind it dont even blink when they come to that same spot so it doesnt appear to be a course generation issue. Hope this longer description and clarification helps narrow down what is really happening.

**Comment by Tensuko** [comment]
> To say only one map allowed is counter productive to finding a fix for this bug.
This is something general you should keep in mind when use Mods!

I will try Convoy with 4 Tools to see what happens later.
But smal cuts without any Course Informations doesn't help.

Anyway, I try this out to see whats going on here.

**Comment by Tensuko** [comment]
@pvaiko 
Course and Savegame for Testing.
Just Tab to the Tractors.
1st = Left2
2nd = Left1
3rd = Right1
4th = Right2
Convoy all on, can start one by one. Had Issue on the 3rd Tractor (Right1) in the 2nd Corner of 1st Headland.
Channel 14 on spammed the log and game stuttered (maybe couse I had 4 active, not sure)

[Convoy.txt](https://github.com/Courseplay/courseplay/files/3790370/Convoy.txt)

[MapUS.zip](https://github.com/Courseplay/courseplay/files/3790354/MapUS.zip)

[savegame3.zip](https://github.com/Courseplay/courseplay/files/3790355/savegame3.zip)

**Comment by 74656b** [comment]
Hitting this issue on 385.

4 Tractors, 4 plows, typically it's 2 Right, the tractor that has the tightest turn, thus does the outside loop turn. It will abort the loop and just takes off in a direction.

Also observed that during the same field with racetrack, the pathing between up/down rows would track into the path of other tractors and cause terrible pile ups.

My next plowing cycle I'll make sure to capture logs and videos of the shenanigans in action.

**Comment by pvaiko** [comment]
@74656b thanks, no need for logs/videos, we know the multitool settings have issues on the headland, actually I'm working on this very issue right now.

**Comment by Tensuko** [comment]
Try Version 388 or higher and report back pls, thx.

**Comment by Tensuko** [comment]
This should be working fine now, if have more Issues with new Mutitool feature, make a new Issue.
