### ISSUE TITLE
Tractor doing strange things after fill from combine

### ISSUE THREAD

**Issue by Slick001** [Courseplay/courseplay#4203]
The Tractor heads off at random headings sometimes cutting off the combine, or backing up and never able to find the waypoint its been assigned to travel too and just spins around in circles. Log and screenshot are the instance where it cuts hard right into the combine.
[log.txt](https://github.com/Courseplay/courseplay/files/3581388/log.txt)
![fsScreen_2019_09_05_16_55_28](https://user-images.githubusercontent.com/54826978/64386599-35ef5c00-cfff-11e9-8c7d-dbcfe1386030.png)

**Comment by ExocetC3i** [comment]
Sounds like known behaviour issues with WIP mode2 #3311

**Comment by Tensuko** [comment]
#3311 
Closed.

**Comment by Slick001** [comment]
Ok, sorry to duplicate problem, new to the mod. This mod is fantastic!!!
your doing great work, thank you so much!
