### ISSUE TITLE
Random Wage Charges

### ISSUE THREAD

**Issue by Natervater** [Courseplay/courseplay#4204]
Hello, currently on build 6.01: 00294. Getting charged for wage payments regardless of choosing no at the beginning of the map. Wage costs vary from over $1000 to $2 and in between. Not sure where I am being charged from. Currently, I have 1 tractor leveling, a forage harvester and 1 tractor harvesting corn. Please advise. 

Thanks in advance
-Natervater

**Comment by Tensuko** [comment]
logfile ?
Got AutoDrive ?
You need to set AutoDrive Helper cost to 0%
MAYBE similar to: #3929

But I think since it is max $1000 I think it is AD Settings.

**Comment by Natervater** [comment]
Apologies, which log file should I upload? I'm not familiar with all the debug channels yet.

**Comment by Tensuko** [comment]
Just the logfile.no need debugchannel yet

**Comment by Natervater** [comment]
Understood, please explain how to get log files, will do it when I get home

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
Closed due to inactivity.
Reopen when got the requested informations.
