### ISSUE TITLE
Game Crash - base.lua - bad argument #1 to 'concat'

### ISSUE THREAD

**Issue by laneparton** [Courseplay/courseplay#4206]
I've been trying to debug this. Is there something I'm not seeing in this log?

The line that is throwing the error:
`setXMLString(xmlFile, newKey..".basics #courses", tostring(table.concat(self.cp.loadedCourses, ",")))`

I should add that I have no courses whatsoever. This is my first experience with CP.

Please let me know if I can provide any other debugging or take any steps to help understand the error.

I'm on Midwest Horizon

**Comment by Tensuko** [comment]
Post your logfile like anyone else have to do it:
https://github.com/Courseplay/courseplay/wiki

**Comment by laneparton** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3586601/log.txt)

**Comment by Tensuko** [comment]
Something with your CP is wrong.
Download a fresh version from here: https://github.com/Courseplay/courseplay/releases
and ONLY rename it to FS19_Courseplay
No zipping or unzipping!
I miss the CP Beta Note:

2019-09-07 12:17 Special dev magic for Courseplay developer unlocked. You go, girl!
2019-09-07 12:17     ******************************************* WARNING *******************************************
2019-09-07 12:17     * You are using a development version of Courseplay, which may and will contain errors, bugs, *
2019-09-07 12:17     * mistakes and unfinished code. Chances are your computer will explode when using it. Twice.  *
2019-09-07 12:17     * If you have no idea what "beta", "alpha", or "developer" means and entails, remove this     *
2019-09-07 12:17     * version of Courseplay immediately. The Courseplay team will not take any responsibility for *
2019-09-07 12:17     * crop destroyed, savegames deleted or baby pandas killed.                                    *
2019-09-07 12:17     ***********************************************************************************************

Also I don't have your base.lua Error in the logfile.
A discription on what you would be nice too.

**Comment by pvaiko** [comment]
The logfile you posted does not have the error.

Also, Courseplay is not multiplayer compatible, you are not trying to use multiplay, right?

**Comment by laneparton** [comment]
Wow, my apologies.

I downloaded the latest CP v6.01.00295 and renamed it to FS19 before this log. I am on Career, not multiplayer.

[log.txt](https://github.com/Courseplay/courseplay/files/3587873/log.txt)

**Comment by Tensuko** [comment]
I think you got a Modconflict:

2019-09-08 14:12 Error: Running LUA method 'onSaveStartComplete'.
2019-09-08 14:12 C:/Users/First Name/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/base.lua:1695: bad argument #1 to 'concat' (table expected, got nil)

**Comment by pvaiko** [comment]
And we still don't know what exactly you were doing when this error is logged.

**Comment by laneparton** [comment]
I thought it would be clear by the log... method “onSaveStartComplete”... this error happens every time I load a game with courseplay on and go to save it.

I just thought I would report the issue. Yes, maybe there is a mod conflict, but I thought maybe you would see something in the log that I missed. I’m interested in figuring out what mod is causing the conflict.

**Comment by Tensuko** [comment]
We are not responsable for other Mods and sry to tell you but we got by far not any time to try out several mods that may cause an Issue here and there.
Thats why we are here on GitHub, to got you guys to help find out.
The best way to find out is to start a Vanilla Savegame with only CP and add Mod by Mod in it.
Well I did that in the early state of CP, just by add all my Mods start with an A, then all with B and so on (or C+D if not many). When Error happens then, I take all out again and just add the Mods start ... with lets say M ... one by one and try find out wich one.... If you know wich Mod it is, can try find the Issue. If it is a general Problem and we will run into more Problems with other Mods, then got to find a fix for it. If it is just this one Mod (and not from ModHub) we won't do anything about it....

**Comment by laneparton** [comment]
Nobody expects you to try out all the mods.

Again, I just wanted to report my issue to further the development of this mod. I only wanted to know if the people close to the mod saw something in the log file that would give a clue as to what is causing the error.

Thanks for your hospitality and all your help.

**Comment by pvaiko** [comment]
I'm sure it is one of the mods where CP could not install itself properly. Nevertheless, CP should not crash the save game in that case, @laneparton are you familiar with git, would you be able to test a branch?

**Comment by laneparton** [comment]
@pvaiko Yep, I'm familiar with git and would be happy to test a branch.

**Comment by pvaiko** [comment]
Give it a try with branch 4206 (https://github.com/Courseplay/courseplay/tree/4206)

**Comment by PsyberMind** [comment]
I'll get the Test Branch tomorrow and report back here as well.. My conflict is guaranteed to be with the 2014 9R Referenced in #4223 but if the test branch works, maybe solved others..

**Comment by postalservice14** [comment]
@pvaiko This happens to me as well - I've got a way to reproduce it every time.

1. Create New RavenPort game with only CoursePlay, IT Runner, and SX Heavy Pack.
2. If you save game immediately - it works fine.
3. If you purchase a SX Heavy IT Runner - then save game, it crashes with the attached log.

I understand if this is a problem with the SX Heavy Pack mod, there is nothing you can do.  But SX Heavy Pack works by itself, it's just when CoursePlay is also in the mix that it crashes.

Let me know if I can help in any way.

[log.txt](https://github.com/Courseplay/courseplay/files/3610832/log.txt)

**Comment by postalservice14** [comment]
I also tried your 4206 branch and this is the log file when using that branch.

[log.txt](https://github.com/Courseplay/courseplay/files/3610901/log.txt)

**Comment by Tensuko** [comment]
Guys, the only way we can provide a fix for it, if you make a clear test.

- Get the Branch from here: https://github.com/Courseplay/courseplay/tree/4206
download, unzip and zip the files inside the folder again. Just like the old style of CP download from github.
- Start a NEW savegame, with ONLY CP Branch 4206+ the Mod that makes trouble (e.g. 2014 9R Referenced in #4223 )

There is no other way to test it, if you take new and different mods in it, that creates other Errors, like outdated AutoDrive and stuff...

Won't reopen untill we get a nice testreport from the CP Brach 4206+ Mod that makes the Error.

@postalservice14 you discribed your steps right, but you didn't take out all the mods, as you see in the logfile, you got to take the mods out of the mods folder.

**Comment by postalservice14** [comment]
@Tensuko I only had the mods I mentioned enabled. CoursePlay, IT Runner, and SX Heavy Pack.

Not sure what the log is telling you, but that's all I had enabled.  Is that not correct?

**Comment by postalservice14** [comment]
I've removed all mods from the mods folder except those three.  Here is the log file using current master branch of courseplay and 4206 branch of courseplay.

[log-master.txt](https://github.com/Courseplay/courseplay/files/3611384/log-master.txt)
[log-4206.txt](https://github.com/Courseplay/courseplay/files/3611385/log-4206.txt)

**Comment by Tensuko** [comment]
Enable/Disable doesn't help. It is just what you have available in your savegame, but the mods getting loaded anyway. You can see that in your logfile.
All the 'Load Mod:' entries.
Thx for testing.

@pvaiko is it that what you need ? Error changed:
2019-09-13 13:31 Error: Running LUA method 'onSaveStartComplete'.
2019-09-13 13:31 C:/Users/John/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/base.lua:1650: bad argument #1 to 'concat' (table expected, got nil)

2019-09-13 13:33 Error: Running LUA method 'onSaveStartComplete'.
2019-09-13 13:33 C:/Users/John/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/base.lua:1700: bad argument #1 to 'concat' (table expected, got nil)

**Comment by pvaiko** [comment]
@postalservice14 if you want you can give it a try with the 4206 I just pushed.

**Comment by postalservice14** [comment]
@pvaiko Yep, that fixed it.  Thanks!

**Comment by PsyberMind** [comment]
Confirmed as well on my end with my insane amount of mods. Thank's a lot guys..

**Comment by laneparton** [comment]
@pvaiko My apologies for the silence from my original issue. I've been traveling a bunch.

I just tested branch 4206 and am happy to report I had no issues saving!

**Comment by judg393** [comment]
Hi all great that this has been fixed but I’m a complete novice on cp and github can anyone provide step by step on what I do to implement this fix in my game ? I presume I need to overwrite something in CP file? Or can I just DL a new version of CP love the game and the mod and don’t want to break anything! 

Thanks

**Comment by pvaiko** [comment]
You can always download the latest version here: https://github.com/Courseplay/courseplay/releases

**Comment by judg393** [comment]
Thanks Pvaiko i’ll Try that tonight! - think I may have lost my current day play through but oh well!
