### ISSUE TITLE
Error: addRequiredCropType foliage must match the size of the ground terrain detail.

### ISSUE THREAD

**Issue by Horozor** [Courseplay/courseplay#4208]
Hey. This error appears when the tractor completes work on the field. No matter what kind of work, sowing, harvesting, mowing the grass .. Always at the end of the path these errors appear. Is there any way to solve this?

Map Canadian Production Map V3.1 8x Season 
[Map](https://www.modland.net/farming-simulator-2019-mods/maps/canadian-production-map-v3.1-8x-season.html)
Courseplay_6_01_00294
[Log](https://gist.github.com/Horozor/5e7e853153800de70a03e687ef103232)

**Comment by pvaiko** [comment]
Don't think this has anything to do with Courseplay. Reopen if you can find out which specific mod is conflicting, we then may look into it.
