### ISSUE TITLE
Issue with loading Lime Bredal K105

### ISSUE THREAD

**Issue by Slick001** [Courseplay/courseplay#4209]
I can not for the life of me after hours of trying am i able to get CP to load Lime in a Bredal K105. At the lime refill station it recognizes the tripper and slows down but drives straight through without opening the top cover. When I have it drive by pallets it again slows down and opens the cover but does not stop. 

I see issue #3043 that has been closed but I'm still having the issue.
[log.txt](https://github.com/Courseplay/courseplay/files/3586687/log.txt)

**Comment by Tensuko** [comment]
Did you set the right refill type ?
Can you give us a Screenshot of where the Trigger is with the Course (F5 on keyboard to show triggers).
And a logfile with debugchannel 1 and 2 active.

**Comment by Slick001** [comment]
Disregard, Im sorry to waste your time. I got it to work. User error. I'll test a little more before i post here, i know you guys are busy

**Comment by Tensuko** [comment]
Ok, if got Issue with it again, I will reopen this one.
