### ISSUE TITLE
Pathfinding issue while unloading stationary combine

### ISSUE THREAD

**Issue by KillBait** [Courseplay/courseplay#4211]
Came across an issue with a tractor pathing a collision course with a stationary combine waiting to be unloaded. The full on collisions only occurs from my testing when the tractor coming to unload approaches from the front of the combine. There is a separate issue with approaching from behind but not as bad an can be reported seperatly.

![20190907172752_1](https://user-images.githubusercontent.com/7914589/64477720-d6c44f80-d196-11e9-99ec-fde9b7209d45.jpg)

Courseplay version: 6.01.00294.dev
Map: Fenton Forest - Field 1
Tractor: Fendt 724 Vario
Trailer: Agroliner TAW30
Combine: Case 9240 + 3162 TerraFlex Draper 45Ft

The combine has reached 100% fill and pulled back to its waiting position to be unloaded. The tractor did'nt unload earlier as it waited off the field due to the pipe being in fruit. Even from a distance away the course still collides

![20190907172738_1](https://user-images.githubusercontent.com/7914589/64477817-dbd5ce80-d197-11e9-920a-f6b05c14b817.jpg)

Even as the tractor approaches close the the combine it does'nt deviate from the collision course
![20190907172752_1](https://user-images.githubusercontent.com/7914589/64477837-10e22100-d198-11e9-99d9-fac5b7819be7.jpg)

Even as it collides it still has a waypoint pathed behind the combine
![20190907172758_1](https://user-images.githubusercontent.com/7914589/64477855-396a1b00-d198-11e9-8168-e5133a41dd1f.jpg)

I was'nt 100% sure what dubug channels to include in the log so i enabled channels 9, 10, 12 + 14

[log.txt](https://github.com/Courseplay/courseplay/files/3586802/log.txt)

**Comment by Tensuko** [comment]
#3311 
Closed.
