### ISSUE TITLE
HUD - Mode 1 Waittime setting missing

### ISSUE THREAD

**Issue by valdimellen** [Courseplay/courseplay#4212]
Hi Guys. 

V6.01.00294 

i am missing Wait-time at mode 1

**Comment by Tensuko** [comment]
You are right.

![Haltezeit_MIssing](https://user-images.githubusercontent.com/27344744/64484867-a58c6380-d218-11e9-8a58-e0e1aa168ab5.png)

@ThomasGaertner Die beiden Zeilen eine nach unten und unter Planen die Halzezeit einfügen ?
In den anderen Modi wird sie dort angezeigt. BTW, sind die beiden optionen nur zwischen stop und start beim Trigger suchen aktiv oder auf der ganze Strecke ?

**Comment by Tensuko** [comment]
#6402
