### ISSUE TITLE
Bunker Silo wird nicht korrekt befüllt

### ISSUE THREAD

**Issue by Vega56** [Courseplay/courseplay#4213]
Hallo,

leider fährt mein Abfahrer einfach durch das Bunker Silo durch und lädt nicht alles komplett innerhalb ab. Der Kurs läuft im Mode 2.
![20190908153656_1](https://user-images.githubusercontent.com/55054246/64489058-19e1f980-d24f-11e9-9727-4df1df255057.jpg)
![20190908153729_1](https://user-images.githubusercontent.com/55054246/64489059-1a7a9000-d24f-11e9-907a-8525a20d149c.jpg)

**Comment by Tensuko** [comment]
Das wurde schon öfter besprochen und fällt unter #3311 weil der Mode2 fahrer der alte CP Fahrer und nicht AiDriver ist.
Abwarten.
Closed.
