### ISSUE TITLE
Combine mode unloading problem

### ISSUE THREAD

**Issue by ridernl** [Courseplay/courseplay#4216]
For the past 2 versions i have the problem that the trailer is not unloading when in combine mode.
It does tip the trailer and it has a 50/50 change to show the image of unloading (while it is not emptying)

When the unloading image doesnt appear, courseplay just drives off leaving a trail on the ground.
When the unloading does appear it gets stuck and waits forever (left the game running for 15 min just to see what it does)

I used a few debug channels, but nothing is showing up in the log (kinda new to this so i might look over it), atleast no errors in the normal log file.

i also used a blank game on ravenport with only courseplay active, yet it still does the same.

Note, it only happends in combine mode, load mode works fine.
![20190910105155_1](https://user-images.githubusercontent.com/54935953/64599841-6ac23100-d3ba-11e9-887d-91668ec3fa56.jpg)

**Comment by ridernl** [comment]
![20190910105110_1](https://user-images.githubusercontent.com/54935953/64599940-9c3afc80-d3ba-11e9-860f-c19d9743d00f.jpg)

**Comment by Tensuko** [comment]
The trail is becouse you put an unload waypoint, this is for tipping anywhere, not into triggers.
Logfile with debugchannel 1 and 2 would be necessary, but this is #3311 
What ever Issue you face, always post a logfile, as I don't even know your CP Version.
https://github.com/Courseplay/courseplay/wiki

Closed couse Mode2 WIP #3311
