### ISSUE TITLE
Courseplay not showing up in save game

### ISSUE THREAD

**Issue by faron0375** [Courseplay/courseplay#4218]
I had courseplay installed on my game and everything was working fine, I was having some conflicting mod issues and a lot of unused mods so I decided to start over.  I deleted all of the mods out of my mod folder and deleted FS19, then reinstalled the game and started over with mods.  Well, when I downloaded courseplay again, I have not been able to get it to show up in game.  If you look at the modhub on the game is has the icon for it showing as if I downloaded it, but it does not show up in the startup menu for a save game.  I have scrolled through the entire list of mods and do not see it when starting up a save game.  
I recently downloaded the guidance steering from this site, and had the same thing happen, it shows up in the downloaded list (or at least the icon does), but not on the list of mods prior to start up on a save game.  
I am wondering if in the midst of my deleting mods and game files if I somehow deleted a file that was important to those mods.
Any input would be greatly appreciated, really missing courseplay right now.
Thanks,

**Comment by Tensuko** [comment]
logfile ? https://github.com/Courseplay/courseplay/wiki
Download the only right and official CP Version here: https://github.com/Courseplay/courseplay/releases
Tip: ONLY Rename it to FS19_Courseplay or FS19_Courseplay6, no unzipping and zipping needed.

**Comment by faron0375** [comment]
I will take a look later tonight when I get home and get you the log file
uploaded and also try your tip.
Thank you for responding.
Faron

**Comment by Tensuko** [comment]
Closed due to inactivity.
If CP still doesn't show up when got the official download from Release side, post a full logfile and I will take a look at it.
