### ISSUE TITLE
cursplay fuelt das farzeug nicht

### ISSUE THREAD

**Issue by RudiBergfeld** [Courseplay/courseplay#4221]
ich spiele auf der Suedhemmern neuster Version. Wenn ich Flüssigkeiten wie Milch. Schaps oder Bier verkaufen möchte erkennt Curseplay den Trigger nicht und fährt einfach ohne zu befuellen  weiter ich verwnde den modus Fuellen am Start. wenn ich den modus flüssigkeitranzport nehme dann erkennt er den Verkaufstrigger nicht

**Comment by Tensuko** [comment]
Der Kurs muss so aussehen, dass bevor der Tracktor am Start Wegpunkt angekommen ist, der oder die Trailer am Filltrigger sind, Im Grunde sucht CP einen Trigger zwischen Stop und Start. Außerdem musst du das Ladegut auswählen, in dem Fall Milch, Schnaps oder Bier.
Flüssigkeitentransport ist nicht mehr zu 100% aktuell und dient eher dazu, Gülle zum Feld zu bringen. da wird noch ein bisschen dran gebastelt werden.

Es kann aber sein, dass deine Trigger von GlobalCompany sind, da gibt es aktuell noch einen Bug, der eigentlich schon behoben ist, aber noch kein Patch von GC draußen ist. Da hilft erstmal nur abwarten.

**Comment by RudiBergfeld** [comment]
Danke Das war der Fehler
ich habe den Startpunkt verlegt alles gut
