### ISSUE TITLE
Mode 2 - Abfahrer bremst vor Kurven nicht bei Max. Geschwindigkeit

### ISSUE THREAD

**Issue by Rumspringa90** [Courseplay/courseplay#4222]
Hi, Ist das ein Fehler oder liegt das an mir? 

Wenn ich "Beladen am Startpunkt" oder "Feldarbeit" (z.b. Stroh sammeln und abfahren) auswähle und auf "maximale Geschwindigkeit" stelle, dann bremst er vor kurven ab und fährt langsamer durch die Kurven.

Im Modus 2 (Drescher abtanken und abfahren) bremst er aber vor kurven nicht ab sondern fährt in die Kurve, bremst dann zu Spät (so wie ich vermute am ersten Kurven-Wegpunkt) und schafft dann die Kurve nicht mehr. Heißt er fährt so gesehen weiter gradaus. 

Courseplay v6.01.00293

Gruß Henne

**Comment by Tensuko** [comment]
Mode2 ist WIP ( #3311 ) und kann dies noch nicht.
Daher Closed.
