### ISSUE TITLE
Possible addition to Mod Conflicts

### ISSUE THREAD

**Issue by PsyberMind** [Courseplay/courseplay#4223]
Needs further testing on my end, but I believe the 2014 JD 9R is causing the game to crash on save, and removing all of the save data from the directory..

See https://pastebin.com/rYgW7mk9

**Comment by Tensuko** [comment]
See #4206 maybe you can help there with your info.
It is for sure a modconflict, but in wich way we don't know.
There is a testbranch on git but see for yourself pls. Also we always need a complete logfile.
Closing thise couse I think it is same Issue as #4206
