### ISSUE TITLE
Combine does not honor straight/curve setting

### ISSUE THREAD

**Issue by Flashsolutions** [Courseplay/courseplay#4226]
version 296... Combine always backs up and turns to the right.  The augur wagon then passes the combine and causes unloading not to work since it won't line up with the pipe of the combine.  Then the combine crashes into the augur wagon when restarted.

**Comment by Tensuko** [comment]
Deactivate fruit bypass when you don't want the combine to not move back. This is not an Issue and mode2 is under rework. #3311 
Closed.

**Comment by Flashsolutions** [comment]
Tensuko, I do not find a setting "fruit bypass".  Where exactly is that?

**Comment by Tensuko** [comment]
3rd Menu from the right, where you set distances and values for unloader.
