### ISSUE TITLE
Game locks up when using CP to follow beat harvester on contract.

### ISSUE THREAD

**Issue by Dilligaf1981** [Courseplay/courseplay#4227]
Using CP v6.01.00296 only other mod installed and used is Holmer Terra Variant DLC.

The equipment is leased. If I only use CP to do the harvest and drive the unloader never locks up, just when i start the second course it locks ups.

Pastebin: https://pastebin.com/pEsbqNix

**Comment by Tensuko** [comment]
Use only this Release:
https://github.com/Courseplay/courseplay/releases

Also, when does this happen ?
The Error is know and is here: #4078
Sry that Issue is in german. But maybe you can discripe what you did when that happened ? Maybe call unloader ?

**Comment by Dilligaf1981** [comment]
I'll try the new release tonight and see if i get the same results.

It happens when i start the second course on the unloader. It seems like it doesn't matter if the harvester is calling for it or not when it locks up.

**Comment by Tensuko** [comment]
Why second course ? Every unloader needs only one course, from Field to Trigger and back to the Field.

**Comment by Dilligaf1981** [comment]
Yes it only has one course loaded. I didnt phrase it right. The second course is just how many courses I have running in general one for the harvester and the second one is for the unloader.

**Comment by Tensuko** [comment]
I will reference this to #3311 and #4286 Couse we are not far from get it into Main Release.
Won't fix this untill new Mode2 comes up.
