### ISSUE TITLE
 Error: Running LUA method 'update'DataS/ scripts/specializations/Atachable.lua(1203)

### ISSUE THREAD

**Issue by Reiko40** [Courseplay/courseplay#4231]
Ich kann seit 97 keinerlei Feldarbeit mehr machen. Bin auch wieder zurück gegangen mit den Versionen aber keinerlei Änderung. Vieleicht kann mir jemand verraten was ich machen kann
![fsScreen_2019_09_14_15_22_37](https://user-images.githubusercontent.com/35115409/64908663-910e0680-d703-11e9-965c-f74198691d85.png)

**Comment by Despopanda** [comment]
Ich habe genau das gleiche Problem

**Comment by schniedertoenz** [comment]
Ich auch

**Comment by Despopanda** [comment]
Das muss ein Mod sein, ich bin gerade dabei es rauszufinden welcher das ist wenn ich was gefunden habe sag ich bescheid

**Comment by schniedertoenz** [comment]
einer von denen

![image](https://user-images.githubusercontent.com/10504674/64910324-5f05a000-d715-11e9-8ec9-41e0ae534017.png)

**Comment by Despopanda** [comment]
Der Fehler ist der MOD FS19_towBar (Abschleppstange)

**Comment by Tensuko** [comment]
Durfte ich selber auch schon feststellen, das Teil wurschtelt irgendwie an den Attatchern rum, steht auhc in #3882 in der Liste.
Closed.

**Comment by Reiko40** [comment]
Danke habe ich schon rausgeworfen.
