### ISSUE TITLE
Rübenmiete mit Terra Dos?

### ISSUE THREAD

**Issue by OnkelH0tte** [Courseplay/courseplay#4233]
Ist es noch nicht möglich mit dem Terra Dos beim Abfahren/Abtanken eine Rübenmiete zu erstellen? Modus 7 scheint ja noch nicht zu funktionieren?! Oder mache ich etwas falsch? 

Abfahrkurs eingefahren sowohl mit einem als auch zwei Abladepunkten, aber bei beiden Kursen fährt CP einfach weiter ohne abzuladen.

**Comment by Tombarkemeyerbruns** [comment]
Der mode 7 wird es nicht mehr geben #3882

**Comment by Tensuko** [comment]
So ist es, Mode7 kommt nicht wieder.
Mit Mode2 und einem Überlader (der für Rüben, Name vergessen) sollte es dann gehen.
Closed.
