### ISSUE TITLE
Harvester collisions

### ISSUE THREAD

**Issue by Beebtrek** [Courseplay/courseplay#4235]
Hello guys this is a description of the problem I have unloading harvesters using a recorded path now what seems to happen sometimes not all the time and usually on the smaller Fields, is when the Harvester has stopped and has a full hopper the tractor comes along and rams the Harvester in other words he comes in from the side and doesn't seem to have enough turning circle to turn the trailer under the outgoing pipe most times the tractor comes in from tens of metres from the rear and lines the trailer up with the pipe and then proceeds to get under it and unload it.
Also so when the Harvester has finished unloading the tractor moves off almost at the same time as the Harvester and sometimes crosses the harvesters path causing it to be rammed either by the Harvester or trapped by the cutters it would seem logical is to put a variable delay in the options one to tell the Harvester to not start moving until the tractor is x metres away or delay the Harvester moving by x number of seconds that would solve the latter problem the earlier problem I would imagine is a matter of path alignment and maybe it should be looked at, I am not sure how to cure this.
Thank you for your attention and I shall continue to contribute to your Paypal channel occasionally yours gratefully Stephen

**Comment by Tensuko** [comment]
#3311 
Closed.
