### ISSUE TITLE
Error: Running LUA method 'update' - TrafficCollision.lua:277: attempt to index field 'trafficCollisionTriggers' (a nil value)

### ISSUE THREAD

**Issue by OzarkOne** [Courseplay/courseplay#4236]
At least 50% of the time when trying to cart grain from combines using a grain cart, the combine loads for 1-2 seconds, stops, retracts the auger and repeats the loop.

**Comment by Tensuko** [comment]
Sounds like mode2 wich is #3311 
Logfile and screenshot ?

**Comment by OzarkOne** [comment]
I'm the one driving the grain cart and CP is driving the combine
[log.txt](https://github.com/Courseplay/courseplay/files/3613140/log.txt)

**Comment by Tensuko** [comment]
You got some Errors in your Mods and I also wonder how ppl don't even see stuff like this and simply copy folders into mods Folder....

Load mod: Unzip
Error: Missing descVersion attribute in mod Unzip

I guess you got a Mod Conflict.

**Comment by Tensuko** [comment]
Btw, your CP is also outdated:
https://github.com/Courseplay/courseplay/releases

**Comment by OzarkOne** [comment]
Updated and removed said mod, still have the same results.

**Comment by Tensuko** [comment]
Can yiu give me a new logfile to see it ? And a screenshot when you pressed F5 once so the traffic colli is displayed.

**Comment by Tensuko** [comment]
Closed due to inactivity.
Also Old Issue. If sill got Problem, provide the needed informations.
