### ISSUE TITLE
Courseplay vehicle freezes

### ISSUE THREAD

**Issue by marmarino62** [Courseplay/courseplay#4237]
the vehicle freezes when giving a saved route to follow

**Comment by Tensuko** [comment]
Logfile ??

**Comment by marmarino62** [comment]
Please I need your help because every time I try to start a course it apears a big yellow arrow in the middle of the courseplay screen and the tract freezes, I have added the link to the problems picture.

https://steamuserimages-a.akamaihd.net/ugc/763846429154065864/47565C12C15F6364ABD9037E8159D2A8553F3421/

**Comment by marmarino62** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3614253/log.txt)

**Comment by rgoe** [comment]
At first glance:
- Update your Courseplay version: "Load mod: zzz_courseplay (Version: 6.01.00001) (Hash: f756839cdd5c69cb6c57ece6ef7ccbe0)"
- Clean up your moddir - at least of those giving errors or warnings and those that are known to play not well with courseplay (e.g. realdirtColor) - have a look at #3882
- Remove all maps besides the one you're playing on from mod dir.

**Comment by Tensuko** [comment]
Get new CP Version here and try again:
https://github.com/Courseplay/courseplay/releases

**Comment by Tensuko** [comment]
Closed due to inactivity.
If there is still Issue with actual Version from Releases Site, make new Issue with proper Titel and post your logfile.
