### ISSUE TITLE
Problem with all ploughs

### ISSUE THREAD

**Issue by lukki78** [Courseplay/courseplay#4240]
The problem is that the tractor cannot turn with the plow into the path next to it (He goes somewhere far beyond the field). I have this problem with all ploughs (both original and mods).

I have this problem since version 266+ (all versions from 265 down worked fine).

**Comment by Tensuko** [comment]
Screenshot and I think debugchannel 9, 12 and 14 for the logfile.

**Comment by pvaiko** [comment]
And your settings, especially turn on field, pathfinding, etc. 

Also, I think you mean 268, not 266 as 266 had nothing related to plows.

**Comment by lukki78** [comment]
Thanks guys for the answers. 
Problem has been solved. The old version of the follow me module was to blame.
I had problem :
 2019-09-15 18:33 Error: Running LUA method 'update'.
2019-09-15 18:33 dataS/scripts/vehicles/specializations/Plow.lua(680) : attempt to compare number with nil

With new version Follow Me mod  everything is fine.
