### ISSUE TITLE
Mode 2 Tractor and wagon running into header when coming from opposite direction

### ISSUE THREAD

**Issue by tylerdixon3105** [Courseplay/courseplay#4241]
When harvesting a field East to West, when a tractor and wagon previously unloaded a combine on the west side of the field and the combine goes back east with pipe in fruit wagon stays put as it should. Then once combine turns around to come back west and is prepared to be unloaded tractor and wagon drive in edge crop to meet combine and end up running into header rather than staying out of its path and out of crop. Combines running on Courseplay also.

Courseplay_6_01_00295
County Line Season map

![fsScreen_2019_09_15_08_28_51](https://user-images.githubusercontent.com/55352594/64922516-b8151880-d795-11e9-87a5-6f989e08593d.png)
![fsScreen_2019_09_15_08_28_52](https://user-images.githubusercontent.com/55352594/64922517-b8151880-d795-11e9-8652-9bb084c52b9f.png)
![fsScreen_2019_09_15_08_28_53](https://user-images.githubusercontent.com/55352594/64922518-b8151880-d795-11e9-9c0b-ad01b59a7de9.png)

**Comment by Tensuko** [comment]
#3311 
Closed.
