### ISSUE TITLE
Düngemodus Problem

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#4243]
Hallo! Tut mir leid das ich auf Deutsch schreibe! Hab das Problem das ich im Düngemodus mit z.B. Samson PG II 20 und Samson TD 12 das Fass immer eingeschaltet bleibt und wenn er die Vorgewende fertig hat nict mehr nachfüllen fährt sondern mit 0 Liter ohne zu düngen fertig düngt! 
In der log kommt dann dieser Fehler

FS19_CoursePlay6/AIDriver.lua:1310: bad argument #1 to 'remove' (table expected, got nil)
[log.txt](https://github.com/Courseplay/courseplay/files/3614178/log.txt)

**Comment by Tensuko** [comment]
Du hast auch nen LUA Callstack.
Könnte ein Modconflict sein.

**Comment by Tensuko** [comment]
Same Error in #4297 continue there, closed.
