### ISSUE TITLE
6.01.00298 Courseplay freezes game when loading save with fields that are mereged or when detecting field edges.

### ISSUE THREAD

**Issue by BW-RP** [Courseplay/courseplay#4245]
I manually combined multiple large fields with a plow, and upon loading that save courseplay attempts to can fields freezing halfway through scanning them. 

My second try at merging fields was done with automatic field scanning turned off. I manually joined multiple fields and then drove onto them to detect fields edge. This action also froze the game. 

In both instances, I had to kill the Farming Simulator task in task manager. 

Please let me know if there is anything else I can provide to help.

**Comment by Tensuko** [comment]
There is always one thing that you can do...
Post a logfile!
https://github.com/Courseplay/courseplay/wiki

**Comment by RK54** [comment]
@ Tensuko,
CP erkennt die zusammen gelegten Felder nicht, da diese anders konfiguriert sind.
In so einem Fall fahre ich um beide Felder herum, und gebe einen Kursnamen ein.
Diesen kann man für alles Arbeiten auf dem zusammengelegten Feld benutzen,
und CP bricht nicht mehr ab

Gruß RK54

**Comment by Tensuko** [comment]
Maybe this is related, just reference this  #3074

**Comment by Tensuko** [comment]
No logfile since long time...
Also: I merge fields a lot on my maps and simply scan them manually and give them a number.
Works pretty fine. When still got an Error, make new Issue with logfile and actual Version.
Closed.
