### ISSUE TITLE
Convoy fieldwork bug 

### ISSUE THREAD

**Issue by aviator64** [Courseplay/courseplay#4248]
This just started recently

Multiple harvesters on field, working header rows
When a harvester is doing the turn maneuver at a corner, it "drops out" of the convoy. So, the harvester behind it suddenly becomes 1/2. When the turn is finished it goes back to 2/2.

The issue is that when the harvester is doing the turn, the harvester behind it no longer sees it in the convoy and can get too close.

Harvester ahead is turning and has dropped out of convoy:
![fsScreen_2019_09_01_10_11_17](https://user-images.githubusercontent.com/19857526/64953792-b160d100-d87b-11e9-8f7d-6827918a7dac.png)

Harvester ahead has resumed its path and is now back in the convoy:
![fsScreen_2019_09_01_10_11_32](https://user-images.githubusercontent.com/19857526/64953836-d5241700-d87b-11e9-9876-09cb461eae57.png)

**Comment by Tensuko** [comment]
293 is old version.
Logfile ?

**Comment by pvaiko** [comment]
Test with https://github.com/Courseplay/courseplay/releases/tag/6.01.00303.1 and report back.
