### ISSUE TITLE
AIDriver.lua:679: attempt to index field 'course' (a nil value)

### ISSUE THREAD

**Issue by Flashsolutions** [Courseplay/courseplay#4249]
Just installed update 299 and restarted a field I had been working.  Got this error. AIDriver.lua:679: attempt to index field 'course' (a nil value)

**Comment by Tensuko** [comment]
Full logfile, always.

**Comment by Flashsolutions** [comment]
Here is the log file
[4249_log.txt](https://github.com/Courseplay/courseplay/files/3620843/4249_log.txt)

**Comment by pvaiko** [comment]
What exactly 'restarted a field' means? Which vehicle(s), what mode?

**Comment by Flashsolutions** [comment]
I had been working field 35 on Eiersholt Map and had quit the game and came back later to restart where I left off.  If I remember correctly, I opened courseplay on the tractor I was last using and the HUD disappeared and would not reopen.  That is when I looked at the log and saw the above error.

**Comment by pvaiko** [comment]
Weird. Can you reproduce this?

**Comment by Flashsolutions** [comment]
I can try.  I don't know if I still have a savegame from that time.  If so, I will let you know.

**Comment by Flashsolutions** [comment]
Well, I do have the savegame just prior to the restart, but am unable to duplicate the error.  Can a check for a nil value of the course variable be made and some more helpful information be saved to the log file that might be of use?

**Comment by pvaiko** [comment]
Well if you had channel 14 active when it happened then we had some more information.

But in general, the AIDriver should always have a course, if we make a check we should be making it when the driver is started, but from your description my understanding is that you did not start it.

Anyway, reopen if you can reproduce it.
