### ISSUE TITLE
Save game does not finish loading

### ISSUE THREAD

**Issue by Koejongen** [Courseplay/courseplay#4251]
When I Enable the newest version of Courseplay it does not load my savegame, and when I load my save without Courseplay it wil load within 30 seconds. 

Logs:
[log.txt](https://github.com/Courseplay/courseplay/files/3617195/log.txt)

**Comment by Tensuko** [comment]
AutoDrive Outdated:
Load mod: FS19_AutoDrive (Version: 1.0.1.9) (Hash: 6b9cce8e25592c84cecb0b5c475b348f)

Already Known Error, get newest AD 1.0.5.7 here: https://github.com/Stephan-S/FS19_AutoDrive/releases
