### ISSUE TITLE
[Suggestion] Harvester opens pipe when waiting to be unloaded.

### ISSUE THREAD

**Issue by Krahazik** [Courseplay/courseplay#4252]
Sometimes when im approaching the harvester to nload it I have difficulty getitng my vehicle the correct distance from the harvester to end up under the pipe when it opens.

I think it would work better, and be helfull, if the harvester opened its pipe when it needed to be unloaded and waited for unload with the pipe open that way as the player approaches the harvester they can see exactly where the spout of the pipe is.

I always harvest with stop while unloading turrned on for harvesting grains.

**Comment by Tensuko** [comment]
Going to discuss this... maybe as an option...

**Comment by Homeyboy69** [comment]
Would be good as a setting so people can have it the way the want it. I would prefer it to be on as I too have trouble aligning with the combine sometimes.

**Comment by masneoquil** [comment]
An option would be good. In FS17 often when the combine reach 80%, the tractor often gets on traffic due to being unable to pass under the pipe. In my case, it would be better if the combine only open the pipe when a tractor is on the side.
Of course, only if you are able to control that pipe do not opens when reaching 80%

**Comment by eickrieger** [comment]
Hello I have a question

Courseplay 6 will run on a dedicated server
when the new update comes out?
 
would love to play on a dedicated server

I would look forward to an answer

**Comment by Tensuko** [comment]
MP will take a long time to get it working good...

**Comment by Tensuko** [comment]
Btw this is implemented so I close this Suggestion. See advanced option.
