### ISSUE TITLE
Speed to High in Bunker Silo V2

### ISSUE THREAD

**Issue by Mannelig83** [Courseplay/courseplay#4255]
Hi, for me a old issue returned.
Same as #3006 but couldnt reopen it.

Here is the log:
https://pastebin.com/Y6XwmCEJ

like you see in line 2661 it seems to not "find" the filllevel of the Trailer.
happens in mode 2...

Greets
Markus

**Comment by Tensuko** [comment]
And unloading into Bunker Silo still doesn't work, as the Mode2 driver is still the old one and doesn't have the calculation. #3311 
Closed.
