### ISSUE TITLE
combi unload to silo not working

### ISSUE THREAD

**Issue by Uruk8** [Courseplay/courseplay#4256]
The trailer tips but not content is unloaded, it remain like in the pic.
I tried different silos(mod and vanilla) same result, this issue is present only in combi mode.
Grain cart works on all tested silos.

![image](https://user-images.githubusercontent.com/40040979/64986383-2c9ba480-d8c7-11e9-906f-423f70333f00.png)

**Comment by SirStranger1989** [comment]
Don't use tip trigger. Cp will detect it automatically.

Op ma 16 sep. 2019 21:19 schreef Max-C <notifications@github.com>:

**Comment by Uruk8** [comment]
oh good to know, Tested OK without tip trigger.
