### ISSUE TITLE
Anyway to stop certain vehicles and tools at a Course stop point, rather then them driving back across fields to the start point?

### ISSUE THREAD

**Issue by cwattyeso** [Courseplay/courseplay#4259]
I don't know if this is something that only irritates me right now or whether other people also are effected by this but for a while now in Courseplay there has been this really annoying thing with certain vehicles or tools when doing field work, that they don't just stop, switch off and wait for the player to interact with them when they reach the stop point on the field, but decide for whatever reason to fold up and drive back to the first point of the course, usually across the field they have just worked, into the path of other tools and vehicles that may be on the field before getting to the start point and then stopping.

Surely the Stop Point should just be the stop point for vehicles and tools and they should remain there until the player comes to retrieve them/move them?

So far I have noticed this behaviour with Seeders, Spreaders, Sprayers, Ploughs and Harvesters, and I don't see any options or setting the player can manually choose to stop them doing it. Even if I select the Stop at Last Point or Next Trigger option, they don't stop at the Stop Trigger and still drive back to the Starting Point.

It makes it annoying for me as it breaks the natural flow of moving between my fields to work them, when the vehicles/tools don't stop in the correct place and would be easy to move onto the next field.

![fsScreen_2019_09_17_10_24_27](https://user-images.githubusercontent.com/13921716/65029920-8091a200-d936-11e9-803d-b02a037fffeb.png)

**Comment by Tensuko** [comment]
HUD - Settings - Advanced Settings - Return to Start on/off in Vehicle tab.
Got that opion since V296 6.01.00296 Option on HUD to return to first point when fieldwork ends
Just that we put that in the new Advanced Setting Tab, not sure why can't click that in normal HUD, but there at least the status gets displayed on to CP driver on/off page.
Closed.
