### ISSUE TITLE
[Suggestion] Turning Circle min and maximums

### ISSUE THREAD

**Issue by Krahazik** [Courseplay/courseplay#4261]
This is a suggestion to perhaps smooth out menuvering calculations. Instead of a fixed turning circle which the helper tries to do for all menuvers, how about having 2 turning circle settings, a minimum circle and a maximum circle with the AI calculating the most efficient turning circle that falls within those limits.

I have a tractor which is capable of making 2m circular turns, but that isn't always the most efficient diameter in some cases, and I notices in some places to make a turn the helper was 'dancing' the tractor, making 2-3 full circular turns to get into position with some other jockying and backing just to make a single 90 degree corner.

Perhaps also add in some collision detection to the calculation so the helper will avaoid trying to make a menuver thats garonteed to hit an object.

**Comment by Tensuko** [comment]
Doubt this is possible, as the turn gets calculated once and is not dynamic, but lets see what @pvaiko thinks about it.

**Comment by Krahazik** [comment]
When is the turn calculated? Was thinking that the min-maxs are used when the turn is calculated to determin the optimal turn angle/circle. 
Was not thinking about dynamically adjusting the turn durring the turn.

**Comment by Tensuko** [comment]
Well but how will you do it ? It is not like cp can try out the turns and look for the best one

**Comment by pvaiko** [comment]
If your are seeing 2-3 full circles during headland turns then something else is wrong (vehicle or implement data) and the vehicle was not able to follow the calculated path.

As for the the collision detection: that is one of the reasons we started experimenting with the AI turns which are currently available only for combines and non-towed implements, and do not include collision detection yet, but should on the mid term, especially for working on fields with obstacles around.
