### ISSUE TITLE
Sprayer moving on before filled?

### ISSUE THREAD

**Issue by Krahazik** [Courseplay/courseplay#4262]
I have run into a minor issue durring lime spraying operations where the helper will drive on before I have finished delivering lime. The moment it has any lime in the sprayer it begins driving again, even when it is set to wait till filled to a specified point.
Been using the Bredal K105 with no cover and sprayer discs for the sprayer and a Strara Ninja 19000 augar wagon to deliver the lime. 
I have had this issue with other tools used to deliver Lime. The first time it happened, I had the sprayer configured with the wider sprayer arms. I was using one of the lime bags from the store and a telahandeler.
I started using the augar wagon so I could drive next to the sprayer and continue delivering while the helper drives on. I also had to take the sprayer arms off so I could get within range while driving.

I do not know if this has occured with any other tools as Lime sofar has been the only time I have had to refill the tool in the middle of the operation.

**Comment by Tensuko** [comment]
That happens to not only lime sprayer, also seed and stuff.
We will take a look at it, but won't happen soon.

**Comment by pvaiko** [comment]
A savegame would help.

**Comment by Tensuko** [comment]
Any Tool for Mode4, start the course, refill it with a seed/fertilizer bag and you will see.
But I can prepare something for you, just gimme few min.

**Comment by Tensuko** [comment]
[savegame4.zip](https://github.com/Courseplay/courseplay/files/3827284/savegame4.zip)
Gen Course, F31 just up down generate, start it.
Try to fill it up with the 2nd Tractor, it will keep move and not stop while beeing loaded.

**Comment by Tensuko** [comment]
It is very enjoyable when you fill up a manure sprayer with a wheelloader, but no Idea if CP can detect that.
