### ISSUE TITLE
Babrosty map field 20

### ISSUE THREAD

**Issue by froobze** [Courseplay/courseplay#4263]
unsure if other fields are affected, generating course is intermittent and unreliable, headland function always sets to 1 regardless of whats set before the course is generated.

**Comment by Tensuko** [comment]
Screenshot ?
It is not like we know all Maps with all Fields.
Fielddate like discribed here would be helpful too:
https://github.com/Courseplay/courseplay/wiki
A logfile with debugchannel for course generating can help too (I think it was 5 or 7, just check in your HUD). Turn it on then generate the course and post it here.

**Comment by froobze** [comment]
log file is here https://pastebin.com/vXbDaLs5

screenshot https://imgur.com/a/EwpMnPd

.xml file is in this zip file. 
[cpFields.zip](https://github.com/Courseplay/courseplay/files/3624621/cpFields.zip)

**Comment by pvaiko** [comment]
There's not much I can do about it, that field has some issues in two corners marked here:
![image](https://user-images.githubusercontent.com/2379521/65458921-58151680-de14-11e9-834a-83f113299af3.png)

**Comment by froobze** [comment]
ok thanks.. map problem, closing the issue.
