### ISSUE TITLE
Abladetrigger wird mal erkannt und mal nicht

### ISSUE THREAD

**Issue by Rumspringa90** [Courseplay/courseplay#4264]
Hallo,
ich hab ein Problem mit einem Trigger. Dieser wird meistens nicht erkannt aber ab und zu schon. habe schon mehrere Kurse versucht aber alle immer gleich. 

Anbei die Log Datei mit Debug 1 und 2 aktiviert.
[log.TXT](https://github.com/Courseplay/courseplay/files/3626951/log.TXT)

**Comment by Tensuko** [comment]
Führt der Kurs auch an anderen Triggern vorbei ? Mal mit einmal F5 drücken nachschauen, ob man den Trigger getroffen hat.
Ein paar Zeilen lauten auch so:
2019-09-18 16:20 :19 [dbg1 lp127218]     trigger (189807) does not accept trailerFillType (10)
2019-09-18 16:20 :19 [dbg1 lp127218]     trigger (189807) acceptedFillTypes:
2019-09-18 16:20     23: WOODCHIPS
2019-09-18 16:20     31: STRAW
2019-09-18 16:20     28: GRASS_WINDROW
2019-09-18 16:20     30: DRYGRASS_WINDROW
2019-09-18 16:20     24: SILAGE

Sonst mal nen Screenshot vom Trigger machen.

**Comment by altbier1** [comment]
Um was handelt es sich? Um ein normales Lager/Silo oder um ein GC Lager/Silo bzw um eine GC Produktion?

**Comment by Rumspringa90** [comment]
Hab jetzt mal ein 2. Kurs noch versucht und bin von der andere Seite in die Abladezone gefahren. beim ersten mal hat er ihn gefunden. Aber bei den anderen malen nicht mehr. Anbei die neue Log datei und ein Screenshot von der Abladestelle.
[log.TXT](https://github.com/Courseplay/courseplay/files/3631453/log.TXT)
![CP_Trigger](https://user-images.githubusercontent.com/50840355/65248796-1114e180-daf3-11e9-9840-e1df956c7995.jpg)

**Comment by Tensuko** [comment]
Ist das ein GlobalCompany Gerät ?

**Comment by RK54** [comment]
@ Rumspringa90,
es kann auch sein dass das Fahrzeug zu schnell ist.
In so einem Fall stelle ich die Geschwindigkeit langsamer ein.
Einen kurzen Kurs extra zum Entladen erstellen, dor kann man das einstellen

Gruß RK54

**Comment by teneco** [comment]
Hallo, ich hatte das gestern auch: zwei Abfahrer, derselbe Kurs, einer lädt ab, der andere fährt durch. Dann habe ich einfach einen anderen Traktor vorgespannt und es ging!?

**Comment by RK54** [comment]
@teneco 
das sollte man immer erst mal versuchen.
Leider kann man nicht alle Fahrzeuge mit CP benutzen, warum auch immer.
Ich teste immer einige Fahrzeuge, bevor ich Hilfe suche, klappt aber nicht immer

Gruß RK54

**Comment by Rumspringa90** [comment]
danke für eure Antworten. Es war aber scheinbar ein Fehler beim Trigger. Habe den ein bisschen nach oben geschoben und jetzt scheint es zu funktionieren.
