### ISSUE TITLE
Problem AIDriver.lua

### ISSUE THREAD

**Issue by jareklyson** [Courseplay/courseplay#4267]
Hello 
when I wanted to make silage from oats, the courseplay panel disappear, including speedometer, 
and when its traied to work tractor don't following silageharwester
/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/AIDriver.lua:679: attempt to index field 'course' (a nil value)
2019-09-18 22:34 Error: Running LUA method 'draw'.

**Comment by Tensuko** [comment]
Duplicate of #4217
Closed.
