### ISSUE TITLE
Error: Running LUA method 'update'. - FieldManager.lua(541) : attempt to index a nil value

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#4268]
Ich bekomme mit der Version v6.01.00300 immer Logfehler!
[log.txt](https://github.com/Courseplay/courseplay/files/3630545/log.txt)

Mit der Version v6.01.00297 habe ich die Fehler nicht!
[log1.txt](https://github.com/Courseplay/courseplay/files/3630559/log1.txt)

**Comment by Tensuko** [comment]
Ich bin mir nicht sicher, aber ich denke das ist kein CP Fehler. jedenfals kommt er nicht von CP:
2019-09-19 11:41 dataS/scripts/fieldJobs/FieldManager.lua(564) : attempt to index a nil value

Das muss wo anders herkommen, den Fehler kenne ich auch von der Riesenbeck bei mehreren CP Versionen.
Kannst du genau sagen, wann der Fehler auftritt ? Also was tust du, damit der Fehler passiert ?
Ich konnte das noch nicht eingrenzen.

**Comment by pvaiko** [comment]
Das ist in dem Giants Code, nicht in Courseplay und nicht einmal auf der GDN Seite Dokumentiert.

**Comment by Lustiger-Hubi** [comment]
Aber warum habe ich das mit der v6.01.00297 nicht?

**Comment by Tensuko** [comment]
Hast du eine Anleitung um das zu 100% zu reproduzieren ? Wenn nein, wie kannst du sicher sein, dass der Fehler mit 297 nicht auftritt ?
Beide Versionen mal ohne andere Mods im Vanilla Game ausprobiert ?

**Comment by Lustiger-Hubi** [comment]
Nein, habe keine Anleitung,
ich kann nur sagen das mit v297 nicht der Fall ist!
Sorry Aber ich probiere es morgen mal ohne Mod

**Comment by Tensuko** [comment]
Wenn du das nicht zu 100% reproduzieren kannst, wie kannst du dir sicher sein, dass es mit v297 nicht passiert ?

**Comment by alku50** [comment]
Ohne CP ist der LS19 nicht viel wert !!! Danke für Eure Arbeit.
Leider habe ich das gleiche Problem. Bei mir an der Stelle "mode3.lua:24"
[log7.txt](https://github.com/Courseplay/courseplay/files/3639904/log7.txt)
Es wäre super, wenn jemand das löswn könnte. Danke

**Comment by Lustiger-Hubi** [comment]
alku50
du hast da einige Error dir! Mach mal die entsprechenden Mod´s raus!

**Comment by Lustiger-Hubi** [comment]
Tensuko
Wenn du das nicht zu 100% reproduzieren kannst, wie kannst du dir sicher sein, dass es mit v297 nicht passiert ?
weil es bei v297 nicht passiert! Auch nach 3 Std. nicht!
Warum auch immer! Nur habe ich festgestellt, das wenn ich ein Kurs festlege (generiere)
bekomme ich ich immer diese Warnung:
2019-09-23 12:20 CourseGeneratorScreen:onCreate()
2019-09-23 12:20 Warning: Performing emergency garbage collection pass - memory went from 123947 KB to 265516 KB in less than one frame
2019-09-23 12:20 Usage is now 154888 KB; full GC took 164.620200ms 
Ich Glaube das hier der Auslöser zu suchen ist!

Kann es auch daran liegen, das ich zwei Felder zusammen gepflügt habe
denn bei ein Einzelfeld ist das nicht so!

**Comment by Tensuko** [comment]
Das was du da hast ist ja nur eine Warnung. hat es denn weitere Auswirkungen ? Ich lege oft Felder zusammen, berechne die Feldgrenzen neu, lege eine Feldnummer fest und erstelle meine Kurse dann damit. Irgendwelche LUA Errors ?

**Comment by Lustiger-Hubi** [comment]
Ich kann es leider nicht sagen woran es liegt
Leider
