### ISSUE TITLE
[Suggestion] Waiting time before and after unloading

### ISSUE THREAD

**Issue by Un4GivenN** [Courseplay/courseplay#4269]
The combine makes the unloading maneuver too quickly when the pipe is on the crop side when the swath is switched on and starts when the unloading is completed without waiting for the tractor to reverse. I suggest adding 5 seconds before undertaking the unloading maneuver and 5-8 seconds after unloading so that the tractor can drive away.

**Comment by Tensuko** [comment]
#3311 
Closed.
