### ISSUE TITLE
The problem with the harvester

### ISSUE THREAD

**Issue by Horozor** [Courseplay/courseplay#4272]
All problems are shown in the video. 
The main problem with mod 2. When the truck goes after unloading to the combine, it rams it and gets stuck. 
Make instructions for mode 2 and mode 10, videos or pictures. I don’t understand why nothing works.

[Log](https://gist.github.com/Horozor/ab7192071acd83b1af44c708035f4aae)
[Video](https://youtu.be/cif0hYfH9L8)

**Comment by Tensuko** [comment]
Mode10 you need to use the right tool.
Put the Shield on the back of the Tractor, then reverse infront of the silo.
Start the Course by driving to a save parking position and put the wait point there, then switch to reverse driving and drive back in front of the silo, but stop before the start.
Then it depends what mode or Mode10 you use and the tool. The rest CP does by itsel.
I could only give you a german tutorial, but maybe you see what happens there:
https://www.youtube.com/watch?v=OZ7MNVQx_Ks
Its the same for drive through silos.

Mode 2 is #3311 and will have some news soon.

**Comment by Horozor** [comment]
So mod 2 is not working right now? Sadly

**Comment by Tensuko** [comment]
Not working well, basically it works, but you got to live with collissions with combine.
