### ISSUE TITLE
Drescher wird vom Abfahrer geblockt

### ISSUE THREAD

**Issue by tjBerlin** [Courseplay/courseplay#4273]
Hallo!

Erst mal herzlichen Dank für die wirklich tolle Arbeit an CP! Ohne diesen Mod wäre der LS nicht das, was er ist!

Ein kleines Problem: Der CP-Drescher wird vom CP-Abfahrer geblockt. Drescher tut eigentlich das was er soll, er wechselt kurz vor dem Abtankmanöver  in die Feldspur, damit der CP-Abfahrer beim Abtanken nicht in der Frucht steht. 

Allerdings zieht der CP-Abfahrer soweit vor, dass der Dresche nicht mehr auf die Ursprungsspur zurückkommt. Abfahrer bewegt sich eigentlich gar nicht und Drescher meldet: Stecke im Verkehr fest. 

Spiele mit CP v300.

Hier ist der log.txt

[log.txt](https://github.com/Courseplay/courseplay/files/3635450/log.txt)

Herzliche Grüße, TJ

**Comment by Tensuko** [comment]
#3311 
Closed.
