### ISSUE TITLE
Destruction derby? 

### ISSUE THREAD

**Issue by froobze** [Courseplay/courseplay#4276]
Lone Oak farm field 42

combine and tractor/trailer keep ramming into each other, having the trailer auto load from the combine to the silo is pretty much bugged to the point of it not working at all. 

logfile provided, apologies if i didn't get the right logs, i can correct this if needed. 
[log.txt](https://github.com/Courseplay/courseplay/files/3636841/log.txt)

**Comment by Racker2409** [comment]
Too many maps in the folder. always only with one map in the Mods folder Play otherwise it can lead to conflicts. 

DeepL Übersetzer

**Comment by froobze** [comment]
ok i'll delete all the other maps and give it a try.

**Comment by Tensuko** [comment]
Take a better Title next time...
Also this is #3311 
Closed.
