### ISSUE TITLE
Driving course and railroad crossing on Countylines

### ISSUE THREAD

**Issue by Crazysonoran** [Courseplay/courseplay#4277]
Have a truck that runs through the train crossing just west of the store on the Countylines map, when the crossing guard is active and the vehicle in question is in the spot they normally stop for the train the game locks up, even if I am across the map on a different vehicle or even on foot. If I can get to that vehicle and "stop driver" the game unlocks and once the crossing guard is done with its animation I can tell the vehicle to continue and all works fine. Attached a log with the options that seemed to be related to travelling courses. I can reproduce it easily.
[log.txt](https://github.com/Courseplay/courseplay/files/3638515/log.txt)

**Comment by Tensuko** [comment]
CP Error
2019-09-21 00:00 Error: Running LUA method 'update'.
2019-09-21 00:00 C:/Users/David/Documents/my games/FarmingSimulator2019/mods/Courseplay6/base.lua:964: attempt to index local 'np' (a nil value)

But you got a lot of Callstack msg.

Other Error that might get created by another Mod:
2019-09-21 02:10 Error: Running LUA method 'update'.
2019-09-21 02:10 dataS/scripts/utils/MathUtil.lua(173) : attempt to perform arithmetic on local 'x' (a nil value)

Also you got an older CP Version.

But I am sure there is a Modconflict somewhere...

**Comment by Crazysonoran** [comment]
It may be the crossing guard on the Countylines map, I might try a test on felsbrunn or ravenport just to see. Thanks for the info, I'll update my CP. Wasnt exactly sure how to check which version I had.

**Comment by Crazysonoran** [comment]
My test on Ravensport showed the vehicle waiting for the crossing to go up before even approaching, On countylines if I didnt pause it the vehicle would run into the train or crossing.  Looks like it's the crossing guard script they are using on that map that's the issue.
