### ISSUE TITLE
Combine low speed Krone Big-X 1180

### ISSUE THREAD

**Issue by Horozor** [Courseplay/courseplay#4280]
Hi, it's me again) I have a question about the speed of the combine Krone Big-x 1180. The harvester works in mod 6 working on the field, I try to drive nearby with a truck at a speed of 10 km / h. However, the harvester reduces the speed to 5-6 km / h, I have to push it from behind so that it goes with normal speed. With a standard trailer, the same thing. What could be the problem?
I did not know exactly which debug to include, sorry.
[Video](https://youtu.be/VaGTN-wO3rY)
[Log](https://gist.github.com/Horozor/5e941e5251f94e8d054e7d5177d9544c)

**Comment by Patrick-Kopadt** [comment]
Kann mir jemand sagen wie ich mit der neusten Courseplay Version den Abfahrer beim Häckseln ein Wendemanöver durchführen lassen kann weil ich den Häcksler mit GPS selber fahre. Bitte um schnelle Hilfe. 
Und noch was wie bekomme ich das noch hin das der Abfahrer nicht mit voller Geschwindigkeit durch das Durchfahrsilo an der BGA fährt.
