### ISSUE TITLE
Combi mode not working?  

### ISSUE THREAD

**Issue by Beatz1122** [Courseplay/courseplay#4281]
After I record the course in combi mode and then press drive course the hud menu disappears. Pressing the right mouse button does not bring up the menu and the tractor/trailer does not empty combine or drive the course?  Is anyone having the same issue.

**Comment by Horozor** [comment]
When this happens you need to click on an empty place where there should be a stop button.  the interface will reappear.  Then you need to unhook the trailer and re-hook.  after that, everything will work.  I solve this problem this way

**Comment by Tensuko** [comment]
Console Command cpStopAll also works for that, tho all CP driver will stop then.
The reason for that is a LUA Error wich you find in the log, that you could post here.
But at the moment, Mode2 is under rework, see #3311 
So I will close this. News about Mode2 soon...
