### ISSUE TITLE
Mode2 Status Update

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/courseplay#4286]
Hello peoples,

I know you are all waiting for a very long time already, but as mentined, the Mode2 Rework is a large project. I recorded a few things, that are already working (sry for the bad Video Edit), but keep in mind that this is more a Alpha Status and the cuts are made for a reason. Some Adjustments needs to be done. <del>A pre-release could happen in the near future (chopping only, no promise), so can't give a date for that.</del> Alpha is Open for test, see post from ThomasGaertner down in the Comments!

Also: MP is on the way too!

Now have fun watching the new Mode2 at work:
https://youtu.be/U9WS0OG-o3o

**Comment by 3lronMcBong** [comment]
Mega geil :-D
Besonders das letzte. Super!

**Comment by TSperfeld** [comment]
WOW... es sieht schon sehr sehr geil aus!!!! Mehr davon, ich kann es kaum noch erwarten testen zu dürfen.

**Comment by knoxville73** [comment]
Very good job guys !  
You are the most important team for this game ...

**Comment by Horozor** [comment]
Very cool. You guys are the most important modders in this game. Without you, playing the farmer simulator alone would not have been possible. Thank you for your work.

**Comment by Knowen** [comment]
Wow, that looks pretty awesome! 
In the end, it'll be worth the wait.

**Comment by froobze** [comment]
looking great, excellent work guys.

**Comment by FS19-CP** [comment]
This is awesome to see!

Nice to see a few of my ideas implemented, as well as some new ones!

Thanks guys, you do awesome work!

**Comment by ThomasGaertner** [comment]
so guys, a early alpha is ready to test: but consider that there are still limitations:
you can find it in the CombineUnloadAIDriver branch
- at the moment only chopper mode is supported
- best chopper is the BigX
- there is a new trafic system on field which will show points on the driveways
- if the tracors are standing still, give them some time to solve the problem by themself (deadline is 90 sek)
- also there are some texts in the screen

when posting issues I want to ask you to deliver the log and a screenshot of the situation

since I've made it from scratch there will be stuff which has been there and I forgot to implement, so please tell me

**Comment by Tensuko** [comment]
Addition: Pls add the information, that you use the CombineUnloadAIDriver Branch, so we can seperate the Issue from old Mode2 Issues.

**Comment by evansv2** [comment]
I know right , take courseplay out of the game, and like why even bother loading this thing, might as well play like another guns blazing game, courseplay gives it strategy mind, thats why its important for courseplay to be around, and should receive payments from giants directly, or it will be another game you load, and unload, saw all the nice tractors and bye kind of thing

**Comment by JDTiger** [comment]
Hey, i encountered two problems with this branch:
1. the Chopper always starts his course at WP1, even if half of the field is done and no matter wich start option (nearest Waipoint etc.) is selected, the chopper always drives to WP1 and starts the course from the beginning

2. The Hud crashes in the Chopper when selecting the unloaders menu

i attached the log for the second issue, will make and upload a video of the first one shortly
[log.txt](https://github.com/Courseplay/courseplay/files/3664248/log.txt)

**Comment by Knowen** [comment]
I can confirm the second issue. 
Log says: 
`2019-09-27 21:41 D:/LS19 Mods/FS19_CoursePlay6_1/hud.lua:1104: attempt to call method 'getHasCourseplayers' (a nil value)
2019-09-27 21:41 Error: Running LUA method 'draw'.`
Also the Combine driver is totaly freezed and makes nothing, after the hud crashes. The unloader behind him, keeps pushing the combine.
![fsScreen_2019_09_27_21_41_21](https://user-images.githubusercontent.com/47173160/65797713-38615380-e170-11e9-970f-e7efe4e813b4.png)

**Comment by TSperfeld** [comment]
I have just had the same experiences.

**Comment by Bobster82** [comment]
I have a map related problem... I cant load the game, it crashes when I start a savegame or a new game with the map Honey_Dew_Farms_XL

[log.txt](https://github.com/Courseplay/courseplay/files/3664491/log.txt)

**Comment by Jimmy-the-Geek** [comment]
Your first step should be to remove all the other mods but Courseplay and
Honeydew Farms XL. It appears to crash out during the FieldManager
initialization, but to make sure it is actually a map problem, you should
test ONLY with CP and the map. If that doesn't work, then the map is the
problem.

**Comment by Bobster82** [comment]
> Your first step should be to remove all the other mods but Courseplay and Honeydew Farms XL. It appears to crash out during the FieldManager initialization, but to make sure it is actually a map problem, you should test ONLY with CP and the map. If that doesn't work, then the map is the problem.
> 

I know its the map, cuz all other maps work with this version. (but for ur question, I did test it with only cp and the map, and its giving the same errors)
The base cp v300 works with this map, only the test mode2 v300 doesnt work with this map. So there is something changed on the mod map that CP needs. Cant really tell what it is, need to figure that out. Or someone here can say what it is exactly ;)

**Comment by Tensuko** [comment]
This version is not for regular play, its an alpha to test it. Don't expect everything work like the release v300. And pls if you got an Issue, create one like the other two already did with log and info that it is mode2 alpha branch etc.

**Comment by Farmer89** [comment]
I have question about MP ,as you mention, when i enable it in moddesc, if it will be usable for some kind at least combine, or it all need rework first?thx

**Comment by Tensuko** [comment]
For MP it was just a side note, that we got someone who try to get it to work. So far he was able to start the game in MP without LUA Error, but nothing else worked if I remember correct, so there is nothing for MP out yet.

For the Mode2 Combi Mode: You can try the version if you download the Branch: https://github.com/Courseplay/courseplay/tree/CombineUnloadAIDriver

Unzip, open folder, zip the files inside, take that zip into your mods folder. But this is Alpha and not meant for general play, as there are some debug notes and some bugs in that version.

**Comment by Twetch** [comment]
I did some testing with MP and when you are there alone, looks like all  works fine, but when i try join with another person, it get stuck on sync screen.

**Comment by betrox007** [comment]
Hi...
Thanks for your effort working on course Play,i try Mode 2 and look like working fine, the only problem is when using for Unload at Silo Bunker and at silo bunker there has a tractor doing courseplay Filling the bunker, the tractor mode 2 won't stop for wait until the tractor in bunker clear and stop at waiting point, i'm using version 6.01.00310 and bellow is my log and screenshoot


![fsScreen_2019_10_16_22_33_08](https://user-images.githubusercontent.com/56646850/66937841-597bdc80-f06a-11e9-8720-629260c74a82.png)

[log.txt](https://github.com/Courseplay/courseplay/files/3735329/log.txt)

**Comment by Tensuko** [comment]
No one said the new Mode2 is in the Main Release yet....

**Comment by evansv2** [comment]
> No one said the new Mode2 is in the Main Release yet....

How long on the mode 2? i believe its been like half a year, dont want to sound like an impatient dick

**Comment by Tensuko** [comment]
When we decide it is time to add it to the main branch.

**Comment by betrox007** [comment]
sorry for that  i dont know if that mode didn't made yet for unloading in bunker..,my missunderstanding,realy appreciate your hardwork mate...


Dikirim dari ponsel cerdas Samsung Galaxy saya.
-------- Pesan asli --------Dari: Vlad <notifications@github.com> Tanggal: 17/10/19  00:45  (GMT+07:00) Ke: Courseplay/courseplay <courseplay@noreply.github.com> Cc: betrox007 <robertpilipus168@gmail.com>, Comment <comment@noreply.github.com> Subjek: Re: [Courseplay/courseplay] Mode2 Status Update (#4286) 

No one said the new Mode2 is in the Main Release yet....

How long on the mode 2? i believe its been like half a year, dont want to sound like an impatient dick

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Courseplay/courseplay/issues/4286?email_source=notifications\u0026email_token=ANQFZQXQ5XWDXACZANS2TPTQO5HL7A5CNFSM4IZNLEYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBNLERQ#issuecomment-542814790",
"url": "https://github.com/Courseplay/courseplay/issues/4286?email_source=notifications\u0026email_token=ANQFZQXQ5XWDXACZANS2TPTQO5HL7A5CNFSM4IZNLEYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBNLERQ#issuecomment-542814790",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by evansv2** [comment]
> This version is not for regular play, its an alpha to test it. Don't expect everything work like the release v300. And pls if you got an Issue, create one like the other two already did with log and info that it is mode2 alpha branch etc.

Tensuko, did Giants change alot from the fs17 engine that fs19 engine needs so much additional code?

**Comment by ArtV-Nef** [comment]
> Addition: Pls add the information, that you use the CombineUnloadAIDriver Branch, so we can seperate the Issue from old Mode2 Issues.
> 
> Link to Branch:
> https://github.com/Courseplay/courseplay/tree/CombineUnloadAIDriver

how install this branch mode2?

**Comment by Corran1327** [comment]
is this Mod2 a Deferring branch from https://github.com/Courseplay/courseplay/releases/tag/6.01.00380 or are the changes you making on it rolled into this

**Comment by Corran1327** [comment]
oh i would love to try mode3 in its broken form is there a way to do that

**Comment by polosubtil** [comment]
Hi guys, @pvaiko @ThomasGaertner 
Do you need us to make more tests on that branche ? Just let me know if you want some more testers around !

**Comment by pvaiko** [comment]
@polosubtil thanks for the offer but at the moment it looks like what we need is not more testers but more developers.

**Comment by polosubtil** [comment]
> @polosubtil thanks for the offer but at the moment it looks like what we need is not more testers but more developers.

Sorry, I can’t help you there 😂

**Comment by gentfarmer** [comment]
QUESTIONS
Is the CombineUnloadAIDriver branch still only for the chopper or is it suitable for a normal harvester?
Do we have to run this branch instead of the main Courseplay branch or is it now incorporated in the main Courseplay release?
Thanks

**Comment by Tensuko** [comment]
You should only stick to the Release from Release Site, all other Branches are WiP and can contain Errors that crash your game or got debugging and testing functions active that won't do what you want.
