### ISSUE TITLE
Foraging 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#4287]
More of a suggestion when I’m driving a forager and using courseplay for the Tractor trailer to collect is there a option so I can select what size the worker goes on it keeps cutting in front of the forager so ideally like it to be to the left. Im using a claas forager with a standard silage trailer and fastrac. Also 2nd thing is there a way when the worker is unloading at the clamp it’s hitting the trigger and unloading but obviously it can only dump so much why won’t it drive forward slowly to carry on dumping?

**Comment by Tensuko** [comment]
#3311 #4286 
Closed.
