### ISSUE TITLE
helpers are not driving.

### ISSUE THREAD

**Issue by swiftyHD1998** [Courseplay/courseplay#4288]
any help please when I gen a course then tell it to start it freezes my camera and i have to alt F4 of the game but now it's just crashing my game every time.
thanks.

**Comment by Woife1** [comment]
post the log.txt (the version while game is running, just the moment when you had to quit with alt+f4)
without any error all could only guess what is wrong in your game

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
Closed due to inactivity.
Reopen when posted a logfile from actual Version
