### ISSUE TITLE
Fehler beim Fahrsilo füllen

### ISSUE THREAD

**Issue by DerDoktorHD** [Courseplay/courseplay#4290]
hi ich habe das problem das wenn ich den feldhächsler automatisch abtanken lassen möchte und das hächselgut ins silo bringen lassen möchte das der abfahrer dann im fahrsilo erst ab der hälfte abkippt und dann bis 20-30m nach dem silo ablädt. in jeder erklärung die ich gesehen habe wurde beim kurseinfahren einfach durch das silo gefahren und es hat funktioniert
![fsScreen_2019_09_23_20_42_43](https://user-images.githubusercontent.com/51912972/65498941-12605880-debd-11e9-897c-d39c1e340e84.png)

**Comment by Tensuko** [comment]
#3311 Kann er noch nicht, wird er können #4286 
Closed.
