### ISSUE TITLE
Idear - CP/AD crossing 

### ISSUE THREAD

**Issue by FritzHugo3** [Courseplay/courseplay#4291]
### **(English Translation are down )**

In German
CoursePlay (CP) und AutoDrive (AD), sind zwei total tolle Mods.

Courseplay hat ganz klar seine Stärke auf dem Feld und AutoDrive auf der Straße. 
Es wäre wundervoll, gäbe es eine Crossmöglichkeit. 

Ich glaube ich habe eine Idee, die einigermaßen einfach umzusetzen sein könnte (so Die Spielengine es ermöglicht, Tastendrucke zu simulieren bzw. Befehle/Werte von einem zum anderen Mod übergeben kann).

Ich stelle mir das so vor, man hat ganz normal seine CP Maschinen auf dem Feld, der LKW (Abfahrer) parkt am Feldrand, fährt dann mit CP los um den Drescher ab zu laden und macht das so lange, bis er eben X-voll ist. Also der ganz normale CP Zustand. Der volle Laderaum lässt den CP Fahrer dann zurück zum Feldrand Fahren und sagt dann (entweder per Tastensimulation oder direkter Wert/Befehlsübergabe) AD bescheid, aktiviere dich (natürlich ist hier die Wegstrecke vorher eingefahren worden und der Feldhaltepunkt ist unmittelbar vor dem CP Feldrandpunkt (Man fährt die Strecken also so ein, das ein direkter Streckenübergang problemlos von dem Pathfinder funktioniert). AutoDrive fährt dann sein gewohntes Streckennetz ab

Zusammenfassung:
CP Abfahrer tankt Drescher ab bis voll, sagt AD es soll aktiviert werden und schalte CP ab), kommt wieder beim Feld an – AD sagt zu CP schalte dich an (die ganzen Einstellungen sind ja noch vorhanden) und schalte AD ab.

Somit hätte man zwei völlig unabhängige Mods, die super zusammenarbeiten würden ohne das man tiefgründig was am eigentlichen Code beider Mods verändern müsste. Es ist quasi, „nur“ ein Switchschalter bei beiden Mods nachzurüsten bei der Aufnahme.

Was dazu vom Spieler notwendig wäre – während der Aufnahme an den Endpunkten einen neuen Button drücken „Übergabe an CP“/ “Übergabe an AD“ (Ein erweiterter Aufnahmestop Button quasi).

(Was für euch notwendig wäre, vermutlich viele Stunden Mehrarbeit, Kopfzerbrechen, Schlafentzug…. *duck*)

Beide Projekte haben ihre absolute Berechtigung und Nutzen, seht die Mods nicht als Konkurenten, beide haben ihre Stärken und nicht so starken Bereiche. 

(Mir ist bewusst, es gibt per Überladewagen einen Workaround, womit es jetzt schon geht, braucht aber ein zusätzliches Fahrzeug, es ist umständlicher, unsauberer, gibt einfach mehr Fehlerquellen und Probleme in der Praxis und nicht alles funktioniert mit einem Überladewagen)

**Ich habe den aller größten Respekt vor euren beiden Projekten und bedanke mich für beide Mods, die den Landwirtschaftssimulator auf eine ganz andere Ebene bringt (Wäre ich Giants, würde ich euch beide Anwerben als freie Mitarbeiter). 
Vielen Dank für die sicherlich vielen hunderten von Stunden Freizeit, die ihr in diese Projekte gesteckt habt. (Und dann kommt da so ein Trottel wie ich daher und möchte mehr grins, Spaß).**

Ich sage vielen Dank für eure Aufmerksamkeit, eure tollen Mods und seht es als kleine Anregung, lasst es euch mal durch den Kopf gehen.

Einen tollen Tag euch beiden 
FritzHugo3

### **In English (sorry ist only a translation software, my english is very bad ;-) ).**

CoursePlay (CP) and AutoDrive (AD) are two great mods.

Courseplay clearly has its strength in the field and AutoDrive on the road.
It would be wonderful if there was a cross option.

I think I have an idea that could be reasonably simple to implement (like the game engine makes it possible to simulate keystrokes or pass commands / values from one mod to another).

I imagine that way, you have your CP machines on the field as usual, the truck (Abfahrer) parks at the edge of the field, then starts with CP to load the Drescher and does that until he just X-full is. So the normal CP condition. The full load space then lets the CP driver drive back to the edge of the field and then tells AD (either by key simulation or direct value / command transfer), activate (of course the distance has been retracted and the field stop point is immediately before the CP field margin point (Man drives the tracks so that a direct route crossing easily from the Pathfinder works.) AutoDrive then departs its usual route network

Summary:
CP Abfahrer refuels Drescher until full, says AD it should be activated and switch off CP), arrives back at the field - AD says to CP switch on (all the settings are still there) and turn off AD.

Thus one would have two completely independent mods, which would work super without the profound what would have to change the actual code of both mods. It is almost, 'only' a switch switch in both mods retrofit when recording.

What would be necessary for the player - during the recording at the end points press a new button 'Transfer to CP' / 'Transfer to AD' (An extended recording button Button quasi).

(Which would be necessary for you, probably many hours extra work, headache, sleep deprivation .... * Duck *)

Both projects have their absolute justification and utility, do not see the mods as competitors, both have their strengths and not so strong areas.

(I am aware that there is a workaround by means of a transfer vehicle, which already works, but it needs an additional vehicle, it is more complicated, more unclean, it simply gives more sources of error and problems in practice and not everything works with a transfer vehicle)

**I have the utmost respect for your two projects and thank you for both mods that take the farming simulator to a whole new level (If I were Giants, I would hire both of you as freelancers).
Thank you for the many hundreds of hours of free time that you have put into these projects. (And then there's such a jerk like me and would like more smile, joke).**

I say thanks for your attention, your great mods and see it as a small suggestion, let it go through your head.

Have a great day both of you
FritzHugo3

**Comment by FritzHugo3** [comment]
(Same Text are here at the other mod)
https://github.com/Stephan-S/FS19_AutoDrive/issues/524

**Comment by Woife1** [comment]
kann mich FritzHugo3 nur anschließen wunderbare Arbeit von euch, ok ein paar bugs sind noch drin aber ist ja noch alpha bzw beta ;)

Müsste die Wege von AD in CP nochmal testen ob es mit der Geschwindigkeit mittlerweile funktioniert.
Beim letzten mal musste ich die harte max. Speed Grenze ziehen, weil bei direkter übernahme des Kurses der Fahrer mit maximaler Geschwindigkeit in die engsten Kurven ging und dadurch irgendwo in der Pampa landete ;)
Dafür gibt es ja auch einen Work Around mit Übergabe wäre es einfacher 
CP braucht doch eigentlich nur 1 Punkt für Mode2 oder sehe ich das falsch (für den Fall es würde Funktionieren das CP an AD für die Fahrt übergibt).
Also CP nimmt den "Parkpunkt" von AD am Feld als Start und Endpunkt für Mode2.

Und wie im Titel schon beschrieben geht es erstmal nur um eine Idee was man besser/anders machen könnte. Wir müssen uns alle dem unterordnen was ihr da bastelt ;)

**Comment by FritzHugo3** [comment]
@Tensuko, wie ich im parallel Thread bei AutoDrive geschrieben habe ist es nicht das gleiche mit einem AD Fahrer und einem CP Fahrer. ich möchte schlicht keine AD Fahrer auf dem Feld haben. Die Gründe sind hier viel weniger Einstellmöglichkeiten, anderes fahrverhalten undn och einige andere Gründe. 

Mode 2 ist halt noch sehr Buggy und lässt mein Spiel komplett abstürtzen (solange man einen Abgabetrigger mit Einfährt funktioniert der Mode, sonst Freeze). Hatte das mit einem seperaten Überladewagen als Workaround/Schnittstelle beider Mods versucht. 


Beide Mods haben eben ihre klaren Stärken und ich vermute mal über Autohotkeys, könnten sich die Mods gegenseitig akti- und deaktivieren, was (ich als Leie in meinem jugentlichen Leichtsinn sage) relativ geringem Aufwand, verhältnismässig einfach um zu setzen wäre. (Man dast eben bei der Aufnahme an den Endpunkten der Strecken beider Mods, hier Übergebe an CP/AD). Somit könnten beide Mods ihr eigentliches Potential voll ausschöpfen.

**Comment by Tensuko** [comment]
Ich weis nicht wad ihr wollt. AD gurkt nicht auf dem Feld rum. Mode2 ist noch im Rework, aber genau so wird es dann funktionieren. CP fährt auf dem Feld und AD auf der Straße mit dem AD Netz. CP hat dann nichts mehr damit zu tun. Probiert es erstmal nit düngen und säen aus und AD zum nachfüllen. Alles was mode2 betrifft kommt später. Ansonsten läuft es doch bereits... Ich weis nicht was ihr da umschalten wollt.... AD nutzen ja/nein ist imCP HUD....

@pvaiko kannst du was hiermit anfangen ? Ich nicht...

**Comment by FritzHugo3** [comment]
Magst du mir noch den Satz erklären? 
@Tensuko "Du kannst auch das AD Netzwerk nutzen um in CP einen Kurs zu laden" wie geht das denn? Unter den Kursen in CP sehe ich keine AD Kurse.

Ich hatte dich hier so verstanden, als das du sagst, ich kann einem CP Fahrer einen Wegpunkt aus dem AD Netzwerk zuteilen und fahren lassen. 
In deinem letzten Post schreibst du wieder das auf der Straße AD fährt. 
(Für mich wiedersprüchig)

"AD gurkt nicht auf dem Feld rum"
Und wenn man dem AD fahrer auf Drescher abtanken stellt, würde natürlich ein AD Fahrer zum Drescher fahren (das machen so ja einige und, das ist aber, was ich eher nicht gerne mache, weil es einfach gewisse Nachteile hat). 

Ich werde es morgen einfach so versuchen zu lösen, das ich pro Feld ein Silo hinbaue, dann kann da der CP Fahrer abladen und dann kann AD da aufladen und es über das Streckennetz verkaufen. Damit muss ich nicht alle Fahrten für CP Aufzeichnen und so sollte es keine Probleme mit dem CP Mode 2 geben. (Sobald ein Abgabetrigger dabei ist, funktioniert das ja in der Regel. 


Im ersten Post steht alles drinnen, was meine Idee angeht, evtl. liest es der Programmierer und hällt es für unsinnig, sinnig oder irgendwas zwischen drinnen, wie auch immer ;-). 
Somit sehe ich meine Schuldigkeit getan, nämlich einen (zumindest aus meiner Sicht) sinnvollen Verbesserungsvorschlag abzugeben - mehr wollte ich hier nicht und da es erledigt ist, mach ich hier mal zu. 

Sollten doch noch Fragen bestehen, so kann ein Moderator oder der Modder ja noch mal auf machen. 


Danke für die Beteiligung und Hilfeversuche.

**Comment by Tensuko** [comment]
Also:
- Möglichkeit1: Du hast ein AD netzwerk und benutzt CP um aus dem Kurs Menü den AutoDrive Ordner zu öffnen und ein AD ziel zu laden, dann hast du einen CP Kurs mithilfe der AD Wegpunkte und kannst so ganz normal mit CP fahren, auch hier, einfach mal ausprobieren!
- Möglichkeit2: Du hast dein AD Netzwerk, nutzt einen Mode4 fahrer zum säen oder Mode6 fahrer zum laden von Stroh oder was auch immer und aktivierst im CP HUD AD benutzen, stellst AD so ein, dass er zu einem Abladepunkt fährt und zurück zum Feld (AD Ziele beim Abladepunkt und Feld vorrausgesetzt) dann wird CP wie gewohnt die Arbeit auf dem Feld erledigen, das weg fahren und zurück zum Feld wird AD machen

Daran ist überhaupt nichts wiedersprüchlich, es sind 2 Dinge die bereits möglich sind.

Deine Problematik spricht wieder Mode2 an ( #3311 ) da lässt sich nichts dran drehen.
Es wird vlt so kommen, dass CP abfährt und dann AD die Strecke zum wegbringen übernimmt, aber erstmal muss Mode2 fertig sein, dann wird man weiter sehen.
Und genau dafür ist das laden von AD Zielen gedacht, Stell deinen Mode2 fahrer aufs Feld, lade im AD Ordner dein Ziel wo abgeladen werden soll (mit rückfahrt) und schon hast du deinen CP Kurs für Mode2, ohne einen AD Fahrer. Du musst halt nur ein AD Netzwerk haben. Keine Silos am Feldrand nötig, wenn du das richtig machst.

Also: Erstmal ausprobieren, dann gerne Vorschläge und Ideen, weil das was du willst ist an Mode2 gekoppelt und geht halt noch nicht, das hat aber ncihts mit AD+CP zu tun, sondern liegt alleine am Mode2 Rework.

**Comment by FritzHugo3** [comment]
Versionen:
AutoDrive_1.0.5.8 (vor drei Tagen geupdatet)
CoursePlay_v6.01.00300 (gestern nach der neusten Version geupdatet)
von hier: https://github.com/Courseplay/courseplay/releases
Ich gehe also davon aus, ich habe bei beiden die neusten Versionen

![CP-AP](https://user-images.githubusercontent.com/55752226/65609778-a101d200-dfb0-11e9-8886-2afcaa376c30.png)

"benutzt CP um aus dem Kurs Menü den AutoDrive Ordner zu öffnen und ein AD ziel zu laden"

Ich habe hier beim CP Menü: Aktualisieren, Sucheingabefeld (mit Ordnern taucht da nichts auf), neuen Ordner anlegen, die CP Kurse. (Dann links noch ein Auge mit 2D, DBG, wozu auch immer das gut ist, ich sehe da jedenfalls keine Ordnerstruktur, Kurse oder so). Neben den CP Kursen habe ich "Kurs laden und zusammenfügen", "Kurs Anhängen", "in Ordner verschieben"

Ich habe auch die anderen Menüseiten durchgeschaut, ich finde hier keinen Button um AD Kurse angezeigt zu bekommen.

Soweit erst mal zu meinem ist-Zustand, den ich erkennen kann

___
Wenn das aber geht bzw. angedacht ist, dann ist meine Idee ja bereits teilweise umgesetzt oder in Planung oder funktioniert intern schon oder was auch immer und ich warte einfach noch, bis das richtig funktioniert und freue mich dann. 

Ich bin nur Spieler und sehe nur das, was mir die jetzigen Menüs auf dem Bild anzeigen (evtl. hab ich auch falsche Versionen oder es geht auch ganz anders, das man die Kurse aus AD sich im CP Menü anzeigen lassen kann, ich finde es jedenfalls nicht)

"Also: Erstmal ausprobieren, dann gerne Vorschläge und Ideen"
Was ich sehe probiere ich aus. Bei Sachen, die ich nicht sehe wird es schwierig. 
Also wenn ich das Symbol übersehe mit dem in einen Kurs aus dem AD-Netzwerk anzeigen lassen kann oder eine falsche Version habe tuts mir leid. Hätte ich eine Solche Funktion gesehen, hätte ich diese auch genutzt und hätte gar nicht erst den Thread auf gemacht. Ich teste Sachen mehrere Stunden aus, Google länger als 5 Minuten, schaue mir auch gerne 2 Stunden lang Tutorials an (wenn sie Wissen vermitteln) - Ich bin jetzt keiner, der erst nen Thread auf macht ohne vorher zu schauen, wie der Mod funktioniert.


Was hingegen da ist, ist die Option in "Fahrzeugspezifische Einstellungen" AutoDrive -> use/dont use. Und das funktioniert ja auch und da das nicht so meins ist habe ich überhaupt erst die Idee oben entwickelt gehabt, weil ich von Möglichkeit 1. noch gar nichts wusste und sie bis jetzt nicht gefunden habe).




Eine ganz andere Sache, die eigentlich gar nichts mit dem hier zu tun hat.
(Das ist auch nur als Vorschlag und Anregung zu verstehen)
"Drescher steuern" -> "Während des Abladens anhalten -> hier noch eine Option Drescher stehen bleiben ohne rückwärts und zur Seite, so das er wirklich einfach steht und wartet.

Jetzt macht er es mal so und dann wieder anders, wenn man es ihm fest  sagen könnte wäre das eine feine Sache. 

Ich dresche zum beispiel fast immer das ganze Feld per Vorgewende, damit gehe ich sicher, das das Rohr immer von der Frucht weg zeigt und es ist auch schneller zum Wenden und da macht es keinen Sinn, wenn der Drescher gerne mal nach hinten und seitlich in die Frucht rein fährt).

Wie gesagt, mal bleibt er tatsächlich einfach stehen, mal fährt er erst rückwerts-seitlich in die Frucht rein, Eine Regel dahinter habe ich nicht herausgefunden. Darum eine fest einzustellende Option -> Bunker voll, an genau der Stelle stehen bleiben, Motor aus, warten bis Bunker abgetankt wurde, weiter fahren (so wie er es ja bereits macht nur eben nicht immer)




Und nein, mir ist nicht langweilig, ich schreibe auch nicht zum trollen, ich möchte auch niemanden nerven und ich bin nicht zu faul zum googlen. Ich habe größte Wertschätzung für eure Arbeit und verstehe, das man auch von der einen oder anderen Frage, Anliegen usw. genervt sein kann. 

Versteht aber bitte auch User, die sich bemühen wollen und es dennoch nicht verstanden haben oder es bei ihnen (warum auch immer) nicht funktioniert, wie bei anderen oder es Verständnis/Formulierungs-Probleme gibt und man aneinander vorbei redet. 

Ich wünsche noch einen angenehmen Tag.

**Comment by Tensuko** [comment]
>>
Was hingegen da ist, ist die Option in "Fahrzeugspezifische Einstellungen" AutoDrive -> use/dont use. Und das funktioniert ja auch und da das nicht so meins ist habe ich überhaupt erst die Idee oben entwickelt gehabt, weil ich von Möglichkeit 1. noch gar nichts wusste und sie bis jetzt nicht gefunden habe).<<
Das ist genau das, was du haben willst, jedenfals liest es sich so, CP auf dem Feld, AD auf der straße, nur das unser mode2 das eben nocht nicht kann. Die option stellt einfach nur ein, dass beim nachfüllen oder wegbringen AD benutzt wird, statt CP, nicht mehr und nicht weniger, auf dem Feld bleibt der CP fahrer. Anders wird es das auch nicht geben!

So muss es aussehen, der Ordner sollte immer da sein, die Kurse die da gelistet werden, kommen erst nachdem das AD Netzwerk gescannt (exportiert oder nicht keine Ahnung musst du Stephan fragen) und dann einmal Savegame aus und wieder anmachen (natürlich mit speichern) dann sind auch 'Kurse' in dem AutoDrive Ordner. Diese werden von deiner aktuelle Position zum gewählten Ziel erstellt und bei Wunsch mit rückfahrt, wie du im Screenshot sehen kannst.

![fsScreen_2019_09_25_18_18_36](https://user-images.githubusercontent.com/27344744/65619729-f04ffe80-dfc0-11e9-9a0b-e9e2cf396fe6.png)
. #3311 

---

Zum Drescher:
Fruchtumfahrung aus, dann bleibt er stehen.
Fruchtumfahrung an: Erstes Vorgewende, baut eine Tasche, Reihne mit Frucht links und rechts, baut eine Tasche, Rohr in der Frucht, fährt rückwärts raus, Rohr nicht in der Frucht und nicht im ersten Vorgewende, bleibt er stehen

**Comment by FritzHugo3** [comment]
"So muss es aussehen, der Ordner sollte immer da sein, die Kurse die da gelistet werden, kommen erst nachdem das AD Netzwerk gescannt (exportiert oder nicht keine Ahnung musst du Stephan fragen) und dann einmal Savegame aus und wieder anmachen (natürlich mit speichern) dann sind auch 'Kurse' in dem AutoDrive Ordner. Diese werden von deiner aktuelle Position zum gewählten Ziel erstellt und bei Wunsch mit rückfahrt, wie du im Screenshot sehen kannst."

Diesen Ordner habe ich noch nie gesehen bei mir. Jetzt verstehe ich auch, wieso das für dich so selbstverständlich ist und ich nur Bahnhof verstehe grins. 
Aus irgendeinem Grund habe ich das bei mir noch nie gesehen. Das heißt, das evtl. irgendein anderer Mod, Die Map, Mein Windows 8, die Versionen oder sonst ein anderer Grund dafür sorgen, das es bei mir nicht so funktioniert, wie bei dir auf dem Bild zu sehen ist. Ich werde dann die Tage versuchen alle Mods raus zu schmeissen. Falls es dann funktionieren sollte schmeiß ich so lange die Mods rein, bis es wieder nicht geht, damit wäre ein Grund/Fehler identifiziert. 

Liest CP das aus der Datei AutoDrive_Multimap_2019_config.xml 
(bzw. AutoDrive_[Mapname]_config.xml aus dem Verzeichnis ...\FarmingSimulator2019\savegame[Zahl]? Vielleicht findet er diese Datei nicht aus welchem Grund auch immer. (Der Dateiname ändert sich ja auch je nach Map)

Ich habe nach dem Einfahren mit Ad muss immer neu Berechnet werden, sonst geht gar nichts, das ist mir bewusst, ich habe gespeichert, Spiel neu geladen und so weiter alles bereits versucht gehabt. 



Danke zum Drescher unten, das sollte sehr hilfreich sein. (warum auch immer das mal so und mal so eingestellt ist, ohne das ich da was umgestellt habe).

**Comment by pvaiko** [comment]
CP fragt die Destinations direkt bei AutoDrive ab, liest nichts aus der Datei.

**Comment by FritzHugo3** [comment]
Update. Habs mit vanila Fahrzeugen auf einer vamila Map und nur mit den beiden Mods CP und AD versucht. Der Ordner bleibt bei mir verschwunden. Wenn ich mal Zeit habe, kann ich noch versuchen das game zu deinstallieren und komplett neu runterzuladen, ob es dann funktioniert, sonst wüsste ich nicht woran es liegen könnte, wenn das bei euch mit den angegebenen Versionen funktioniert und bei mir nicht (Kann es am Windows 8 liegen, irgendwas wegen Rechten oder so, habsch schon mit Admin Rechten versucht zu starten).


Zu der Dreschereinstellung ist mir aufgefallen, das es tatsächlich unterschiedliche Einstellungen gibt, je nachdem welches Fahrzeug bzw. Map man und ob man ein Fahrzeug neu kauft oder es bereist bei einem neuen Spielstand besitzt oder ähnlichem. 
Jedenfalls ist die Fruchtumfahrung defaultmässig nicht grundsätzlich an oder grundsätzlich aus. Ist mir nur aufgefallen. (Hatte es noch mal getestet, weil ich mir sicher war, das ich da nie was verändert hatte). Ist ja auch wurscht und nicht schlimm. 


Ansonsten bedanke ich mich bei euch für eure Geduld und netten Umgang mit mir schwierigem Kunden ;-) und hoffe ihr habt auch weiterhin viel Spaß und Zeit am Modden und freue mich auf weitere Versionen. 

Alles Gute 
FritzHugo3

**Comment by Woife1** [comment]
Die Standart Einstellung ist Don' use, nach dem Start des Spiels sind die Standart Einstellungen geladen 

Das Use und Don't Use wird nicht in einem Kurs oder im Savegame gespeichert.
(Falls du die Option fürs Abladen/Auffüllen(unload/refill) über AD meinst)

**Comment by FritzHugo3** [comment]
Ich habe es jetzt noch mal mit einer sauberen Installation von LS19 versucht, hatte nur AD und CP im Modordner, versucht auf einer vanila Standart Map. Habe ein neues Spiel begonnen, habe einen neuen (zusätzlich zu den bestehenden, die AD hier von sich aus mitbringt) Kurs mit Wegpunkt angelegt. Habe den Kurs in AD neu berechnen lassen (damit AD den Kust auch verarbeitet und speichert), habe das Spiel gespeichert. Das Spiel habe ich dann komplett aus gemacht, wieder an gemacht, den Save geladen und dieser Ordner, der bei euch auf dem Bild zu sehen ist in Kurse Verwalten taucht definitiv nicht auf.



Mir ist aber was neues aufgefallen. Wenn ich meinem Drescher sage, er soll AD nutzen und starte dann den CP-Drescher passiert folgendes: CP Drescher fährt die Räder (Straßenmodus, zum Anhängen) des Schneidwerks aus und gibt vollgas übers Feld, gleichzeitig springt der "Apfel" (also das ON/OFF Symbol) bei AD an (was es ja eigentlich nicht tun dürfte)

Irgendwie schafft es der Drescher das dann sowohl der Abfahrer von CP und AD gleichzeitig laufen.
Sollte es notwendig sein, mache ich auch gerne ein kurzes Video davon. 



Die Version, das CP Drescher + CP Abfahrer im Mode 2 das Korn an einem Feldrand-Silo abladet und von dort dann seperat von einem AD Fahrer weiter verkauft wird, funktioniert tadellos.

Die Kombination, Abfahrer sammelt Stroh mit CP und hängt automatisch einen AD Kurs zum abladen hinzu funktioniert ebenfalls tadellos.

**Comment by Anonymous-any** [comment]
> 
> 
> CP fragt die Destinations direkt bei AutoDrive ab, liest nichts aus der Datei.

Yes that (I) we see that. I tried to joint AD courses between CP in CP panel.
The problem that this produces is CP always start to add the AD course with your actual position...
Of course that cannot join them good in queue when they are combined, and make mess in the show EYE's button how to courses are added. I hope this go find a fix !!
