### ISSUE TITLE
beim Pfügen streikt CP

### ISSUE THREAD

**Issue by RK54** [Courseplay/courseplay#4293]
nachdem CP meinen breiten Pflug nicht mag, habe ich es mit einem normalen Pflug versucht.
Bei dem Versuch ist es auch geblieben, mein Schlepper ist mit gesenkten Pflug quer über die Karte gefahren, bis an die Mapbegrenzung.
Er hat mich auch nicht einsteigen lassen, konnte nur das Spiel beenden.
Schlepper ist der https://www.modhoster.de/mods/fendt-900-vario-s5-prototype
Pflug ist der https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=125532&title=fs2019.
[log.txt](https://github.com/Courseplay/courseplay/files/3649144/log.txt)

**Comment by Tensuko** [comment]
Anderen schlepper probiert ? Mods die nicht vom ModHub kommen werden im moment nicht unterstützt und ich meine zu dem Tracktor gab es bereits ein Issue mit problemen... Kann mich auch irren.

**Comment by RK54** [comment]
@ Tensuko,
habe es mit dem https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=139255&title=fs2019
und auch mit dem https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=124080&title=fs2019 
mit dem gleichen Pflug versucht, das Ergebnis ist das gleiche.
Einziger Unterschied, ich kann wieder auf den Schlepper, er fährt irgenwo dann weiter, am Ende der Spur mag er wieder nicht
[log.txt](https://github.com/Courseplay/courseplay/files/3651876/log.txt)
Gruß RK54

**Comment by Lustiger-Hubi** [comment]
Ich habe auch keine Probleme mit dem Pflug sei es Original oder Mod FS19_FlexCoil_ST820_Plow

**Comment by RK54** [comment]
@ Lustiger-Hubi,
geht bei Dir auch ein Bahn und dann ende?
Er fährt rückwärts, hebt davor den Pflug, und haut mir die Log voll Error

Gruß RK54

**Comment by Tensuko** [comment]
Haut die log voll Errors und dann postest du kein logfile ? ....

**Comment by Tensuko** [comment]
Log nicht gesehen... Abwartennn bitte

**Comment by RK54** [comment]
@ Tensuko,
Log ist die gleiche wie oben

**Comment by Tensuko** [comment]
Ja gesehen, mit Handy iat alles etwas kleiner :)
Abwarten was @pvaiko dazu sagt.

**Comment by Lustiger-Hubi** [comment]
@ Lustiger-Hubi,
geht bei Dir auch ein Bahn und dann ende?
Er fährt rückwärts, hebt davor den Pflug, und haut mir die Log voll Error

Nein, läuft ganz normal, Keine Logfehler

**Comment by Lustiger-Hubi** [comment]
Also ich habe mir den Schlepper geladen
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=139255&title=fs2019
Mein Pflug genommen, keine Probleme siehe Bilder
Was für ein Pflug haste genommen?
![fsScreen_2019_09_25_19_23_24](https://user-images.githubusercontent.com/48583507/65624870-ffd44500-dfca-11e9-86b4-fc37b8ac3fe4.png)
![Uploading fsScreen_2019_09_25_19_24_05.png…]()
![Uploading fsScreen_2019_09_25_19_25_33.png…]()

**Comment by Tensuko** [comment]
Das Teil ist ein Grubber, nur umgebaut zur Pflugfunktion.
Ich behaupte mal wir meinen hier einen richtigen Pflug der Quer verläuft. So ein Grubber zu händeln ist leicht...

**Comment by Lustiger-Hubi** [comment]
Was für ein?

**Comment by Tensuko** [comment]
Guck einfach in die kategorie pflug im ingameshop da sind genug beispiele für einen pflug.

**Comment by Lustiger-Hubi** [comment]
Ja aber welcher ist es der abstürzt?
oder sind das alle?

**Comment by Tensuko** [comment]
Es muss nichtmal am Pflug liegen... Aber das was du da hast ist zwar mit der pflugfunktion ausgestattet, aber es ist symetrisch und wird einfach gezogen. Und ich behaupte es wird auch im weiten turn gewendet. Das problem ist oben beschrieben. Da ich eben selber mit nem pflug von lemke CP arbeiten lies kann ich nur sagen das alles supper klappte... Also warum bei RK54 nicht.

**Comment by Lustiger-Hubi** [comment]
Ja dann ist ja gut! 
cu

**Comment by pvaiko** [comment]
Der Fehler kommt von einer Giants Funktion die wir während des Turns immer wieder aufrufen damit der Giants Code den Pflug drehen kann. Ich habe den PLN 6-35 ausprobiert, funktioniert ohne probleme.

Andere haben schon Probleme beim Pflugen mit Follow Me Mod berichtet, habe jetzt keine Lust zu suchen, diese  hier mache ich jetzt zu, wenn Du es ohne andere Mods reproduzieren kannst bitte neu öffnen.
