### ISSUE TITLE
Courseplay Bunker Mode drives into Walls

### ISSUE THREAD

**Issue by Bram1455** [Courseplay/courseplay#4295]
Hello, 

i'm relatively new to this, but i'am using courseplay for several years now. In FS19 everything works fine for me but the bunker mode.

I can't get it to work properly. 
I've tried to set up several courses, with several machines, in several bunkers on several maps, but it is not working. De tractor sometimes keeps running in circles around startingpoint. or it keeps leveling the same litlle area (about 5 metres). Also it runs into the bunkerwalls driving in a corner while the course is in a straight line.
At the waitingpoint is always tries to drive further in a curve to the right for about 5 metres.

As i said i've never posted an issue like this so i hope i'm doing this the wright way. 
I posted the log in the bottem line.

thanks in advance,

Bram
[log.txt](https://github.com/Courseplay/courseplay/files/3651854/log.txt)

**Comment by Bram1455** [comment]
Using Courseplay 6.0100297

**Comment by Tensuko** [comment]
I keep seeing those kind of Errors in logfiles, just check your mod name before you put it into mods folder:
Error: Failed to open xml file 'C:/Users/Bram/Documents/My Games/FarmingSimulator2019/mods/Liquid_cropProtection_package_Unzip/modDesc.xml'.

Some more Erros in your logfile.

What Tracktor did you use to level the bunker and can you make a screenshot of the course ?

Basically you start with the back in front of the bunker, drive straight to a save position to set a waitpoint, then switch to reverse and stop before you reach the start.

**Comment by Bram1455** [comment]
Yes i noticed those errors indeed. Just change those modnames into FS19_.......? and the errors will be fixed? Those errors might have anything to do with my problems with the bunkermode?


I tried with every holaras blade, the green blade, the wheelloader, Case Magnum, John Deere 6r,  7R, nothing seems to work.

 When i click on start course on the photo the tractors drives to waitpoint, drives back to the bunker, lowers blade, makes a turn and drives into the wall backwards. Also "self:drivePush(dt)" comes on the screen.
I watched every video on yt about the bunker mode, and i tried setting it up exactly as they do it in the tutorial. One thing i did notice is there are no video's of the bunkermode in fs19? Only 15 and 17 as far as i can see.

I hope you know what i'm doing wrong.



Bram


![20190925_190920](https://user-images.githubusercontent.com/54806320/65624481-4aa18d00-dfca-11e9-8d0b-ba9559a283fd.jpg)
![20190925_190910](https://user-images.githubusercontent.com/54806320/65624505-5725e580-dfca-11e9-8878-ec9df4b335ba.jpg)

**Comment by Tensuko** [comment]
Read this one carefully, it is part of the error I posted for you....
**Liquid_cropProtection_package_Unzip**

And for the course: I said start in front of the Bunker, not inside the Bunder.
Else he can't scan whats in there and the the circle.

**Comment by Bram1455** [comment]
So should i erase this liquid cropprotection pack? Or is it named the wrong way? I don't understand what you mean exactly. 

I did try to start the course right in front of the bunker, but then message: cannot find a bunker at startpoint comes up.

**Comment by Tensuko** [comment]
I will make a more detail help for the course.

The mod say ' unzip' at the end. It is a package that contains a few modfiles... At least it should.

**Comment by Bram1455** [comment]
Ok, i tried ones more to set it up with the startingpoint in front of the bunker, but it says "can't find bunker at startingpoint'. 

Is there an explanation for the 'self:drivePush(dt)'? line that is in the screen when i click on start course?

**Comment by Tensuko** [comment]
Sry I was wrong, the 1st Start have to be in the Bunker, I mixed it up with another Mode.
I will show you how I made my course for it when I am home today.
the self:drivepush is just an information print I think just didn't put it out.

What might help is to set the stop a bit more far away, so the Angle to the 1st heap won't be that high.

**Comment by Tensuko** [comment]
This is for FS17 but the same rules are for FS19 https://www.youtube.com/watch?v=OZ7MNVQx_Ks
it is in german but you will get the Idea of how the course have to look like.

**Comment by deeg427** [comment]
im having the same problem on marwell manor, when the tractor goes to enter the pit it just tries to turn right whole time, iv never had this problem on previous couresplays

**Comment by Tensuko** [comment]
Did you try this?

> What might help is to set the stop a bit more far away, so the Angle to the 1st heap won't be that high.

**Comment by Bram1455** [comment]
Yes i did yesterday, and it 'works' now. Thanks for your advice.

Problems i still have are though:

The tractor with silagewagon won't wait for the compacter tractor?

Sometimes when the tractor gets to the 'end off the course' the place where the stopsign is and the blade lowers, cp says: wrong tool for this course

I let the tractor drive backwards in the bunker first and then it has to unload. I t drives back into the bunker, and as soon as it hits the triggerpoint It unloads at one place, so the unloading stops as soon as there is too much chaff behind the wagon. How can i make the tractor wait to unload, drive back, and unload driving forward?

Can i use the blade and the Stego 485 in combination with bunker mode?

**Comment by Tensuko** [comment]
Tool depends on Mode and the Mode looks for the flags in the tool xml, @ThomasGaertner can explain this better, but for the wait for the compacter I can tell you, when you use Mode2, there is no communication between them, so this won't work yet, see #3311 and #4286

**Comment by deeg427** [comment]
I have tried several different ways to get this too work but my tractor will only go half way in the bunker then stop then move forward then starts all over again doing the same thing! I'm using foreplay v6.0.1.00316, any help would be much appreciated

**Comment by Gibbanator** [comment]
same here.. I'm using foreplay on my wife and I get the same reaction..

**Comment by deeg427** [comment]
im still having the same problems with the levelling and compact mode tbh, the tractor still reverses into the side of the silo,

**Comment by Tensuko** [comment]
Collecting Issues in #4254

Closed.
