### ISSUE TITLE
Courseplay läd an fest verbauten Produktionen nicht ab

### ISSUE THREAD

**Issue by tn4799** [Courseplay/courseplay#4296]
Hi.
ich habe zwar schon mal zu diesem Thema einen Post verfasst, letztes Mal in englisch nur bin ich grad zu faul dafür, aber da ich und mehrere andere, mit denen ich mich unterhalten hab, das selbe Problem haben wollte ich es noch einmal ansprechen.

Bei platzierbaren Produktionen läd CP nach meinen tests problemlos ab. Jedoch bei den fest verbauten Produktionen läuft es noch immer nicht. CP fährt einfach den Kurs ab ohne abzuladen.
Der Kurs führt rückwärts an den Abladetrigger heran. Wenn man manuell abkippt funktioniert der Trigger, somit ist hier schonmal ein Fehler ausgeschlossen.

verwendete CP-Version: v300, vor ein paar Stunden frisch heruntergeladen und installiert. 
Logfile mit debug-mode 1&2 sowie screenshots liegen dabei. Wenn ihr Fragen habt, steh ich euch gern zur Verfügung.

MfG
tn4799
![fsScreen_2019_09_25_15_46_23](https://user-images.githubusercontent.com/52242395/65607090-3d75a580-dfac-11e9-8194-125399854d02.png)
![fsScreen_2019_09_25_15_46_32](https://user-images.githubusercontent.com/52242395/65607092-3d75a580-dfac-11e9-8c9c-d90ca0bc7dfd.png)
![fsScreen_2019_09_25_15_46_40](https://user-images.githubusercontent.com/52242395/65607093-3e0e3c00-dfac-11e9-9721-1e41202ec328.png)
![fsScreen_2019_09_25_15_46_46](https://user-images.githubusercontent.com/52242395/65607096-3ea6d280-dfac-11e9-8d0b-6190e5f9d1bb.png)
[log.txt](https://github.com/Courseplay/courseplay/files/3652816/log.txt)

**Comment by Tensuko** [comment]
Sieht sehr nach GC aus siehe #4049 war noch keine Zeit da etwas an zu passen, da gerade Mode2 priorität hat, wir haben das aber auf dem Schirm.

**Comment by Tensuko** [comment]
Deine Map ist recht alt, V1.8 und erst ab 2.2 läuft NF Marsch mit GC.
Was das andere für Trigger sind (denke mal die ersten Versuche für Fabrik-Scripte) kann ich dann nicht sagen und ob wir die unterstützen weis ich nicht. Ein Map-update wäre mal nicht schlecht.

**Comment by Tensuko** [comment]
Mit FS19_EasyDevControls kannst du deinen Stronger Farmer übrigens rauserfen.

**Comment by tn4799** [comment]
die mapverison ist so alt weil es ein privatumbau von mir ist und ich keine lust hatte, die ganzen umbauten immer wieder zu machen. in der orginalen version von FED ist nichts fest verbaut soweit ich weiß.
und dass der strong farmer raus kann weiß ich, ist eh nur n testmodordner, da hab ich nicht dran gedacht doppelte mods zu entfernen.

**Comment by Tensuko** [comment]
Also selbst eingebaut die Trigger... Was für trigger ? Nur weil sie manuell gehen heist es nicht das sie auch von AI Drivern bedient werden können.

**Comment by tn4799** [comment]
wenn ich mich recht erinnere exportierte trigger aus dem seedmaker und in die i3d eingebaut.
in #4141 müsste ich auch nen link zu nem google drive geschickt haben wo u.a. die map drin ist.
kannst dir ja mal ankucken, falls n fehler drin ist für AI-drivers, gerne sagen dann beheb ichs und tests nochmal

**Comment by Tensuko** [comment]
also aus dem seedmaker vom GC, dann ist es geklärt, weil CP noch probleme mit GC hat, wie in #4049 bekannt ist. Kann leider noch dauern.

**Comment by RK54** [comment]
@ tn4799,
Tensunko hat Dir ja schon einiges geschrieben.
Was ich auf Deinen Bildern vermisse, den Wartepunkt am Ender der Rückfahrtstrecke.
Mit dem CP 300 habe ich es noch nicht getestet, aber ich mache immer einen Wartepunkt, und hatte keine Probleme. Den Kurs habe ich mit einem Schlepper solo eingefahren, mit einem LKW hat es nicht geklappt
Gruß RK54

**Comment by Tensuko** [comment]
Für eine erste Lösung für GC Trigger, schaut bitte meinen 2ten Post in #4049 an. Dort wird es beschrieben, wie ihr das Problem lösen könnt.

Mache hier erstmal zu.
