### ISSUE TITLE
Tractor with articulated steering dos not use full angle when driving a course

### ISSUE THREAD

**Issue by sudo-karamir** [Courseplay/courseplay#4298]
Drive a new course with a tractor with articulated steering. Drive a full curve with maximum angle.
When following the course the tractor dos not use its full steering angle.

See picture:
[https://i.imgur.com/7s1DC1q.jpg](https://i.imgur.com/7s1DC1q.jpg)

**Comment by Tensuko** [comment]
Tractor with articulated steering is fixed, use V316+
Closed.
