### ISSUE TITLE
Fill and empty? 

### ISSUE THREAD

**Issue by Beatz1122** [Courseplay/courseplay#4299]
I set up a course to fill a trailer with silage to take to bga. After loading the sheer grab it reverses out of the clamp/silo then just comes to a stop.  If you stop the worker and move it towards the trailer, then select nearest waypoint it sometimes will empty into the trailer then resume the course then will come to the stop again after reversing out of the silo!!

**Comment by Tensuko** [comment]
!! Screenshot ? Logfile ?

**Comment by Tensuko** [comment]
Closed due to inactivity, reopen if got the provided informations.
