### ISSUE TITLE
Grimme 260 Potatoe Harvester freezes in combi mode, occured in v .300

### ISSUE THREAD

**Issue by evansv2** [Courseplay/courseplay#4300]
Freezes when Tractor with a tipper  in mode 2 combi mode, Waits for adequte levels to reach, then when they do reach, when trying to run to the harvester , games  freezes, tried it with no mods, and all vanilla
[log.txt](https://github.com/Courseplay/courseplay/files/3663173/log.txt)

for the most part error I get is 
`hud.lua:1604: attempt to index field 'hud' (a nil value)`
then this
`combines.lua:488: attempt to index field 'spec_drivable' (a nil value)`

**Comment by Tensuko** [comment]
Error: Invalid mod name 'FS19PlaceAnywhere-master'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

And you got GC so this mod must the deleted.

Load mod: MouseSteering (Version: 3.4.1) (Hash: 3f1a6bb55eea7fff70ea3ce322f55c09)
Error: Unsupported mod description version in mod MouseSteering

And I guess you use the V300 from Main Release, so this is #3311 
Closed.

**Comment by evansv2** [comment]
> And you got GC so this mod must the deleted
> Load mod: MouseSteering (Version: 3.4.1) (Hash: 3f1a6bb55eea7fff70ea3ce322f55c09)
> Error: Unsupported mod description version in mod MouseSteering

Ok i removed basically all of the mods and just left autodrive and the v300 coursplay
here is another log that caused the crash 
[log.txt](https://github.com/Courseplay/courseplay/files/3663552/log.txt)

so I should just wait for the #3311 to be closed and released, and wait right , as I take it my issue connected to the #3311  ?

**Comment by Tensuko** [comment]
Yes, got to wait, or when you got a savegame where you try stuff out, you can take a look here:
 #4286 and try out the new Mode2.

GC (Global Company) got the PlaceAnywhere Mod included, so an extra Mod for it us not needed, also the Version of the Mod you had caused an Error, so you don't need the old playceanywhere. thats all.
