### ISSUE TITLE
Alpha mode 2 

### ISSUE THREAD

**Issue by RUGhost** [Courseplay/courseplay#4302]
Thanks to CP team for bringing back the new mode 2. Unfortunately i could not make the new mode 2 to work. 
I couldn't select the field for generating course. Couldn't found the combine searching option. Combi driver did not go to chopper. If i press drive now combi driver drive at 24 kph. 

[log.txt](https://github.com/Courseplay/courseplay/files/3664500/log.txt)

![1](https://user-images.githubusercontent.com/48012198/65801598-48425d00-e19b-11e9-8757-f3f87e6e3b34.png)
![2](https://user-images.githubusercontent.com/48012198/65801615-4f696b00-e19b-11e9-9ce9-f09f5ae2fed3.png)
![6](https://user-images.githubusercontent.com/48012198/65801636-5c865a00-e19b-11e9-8c02-2681cdab1863.png)
![3](https://user-images.githubusercontent.com/48012198/65801669-71fb8400-e19b-11e9-82c7-81b18949ed05.png)
![4](https://user-images.githubusercontent.com/48012198/65801683-7aec5580-e19b-11e9-8bfd-e00dd196e88a.png)
![5](https://user-images.githubusercontent.com/48012198/65801688-8049a000-e19b-11e9-89f0-3356cdce911f.png)

**Comment by RUGhost** [comment]
Update:
After restarting pc, all of the above problems are gone except the driving speed on the road. It just drive 24 kph on the road. He also does not avoid fruit. Drive through the fruit.

**Comment by Tensuko** [comment]
Issue still valid to the Alpha Branch ? Can we update this, or close this and make a new one if needed ?

**Comment by Tensuko** [comment]
Most of this is fixed or things changed.
Closing this, make new Issue for the newest update.
Going into Master Branch soon...
