### ISSUE TITLE
Show HUD Right Click wont work

### ISSUE THREAD

**Issue by biomex81** [Courseplay/courseplay#4304]
The last vers. worked perfectly but I dont know why, suddenly I cant open the HUD by Mouse Right Click, Also I noted in the log file many of this error reapeted many times at startup game:

2019-09-27 11:05 Error: Running LUA method 'draw'.
2019-09-27 11:05 C:/Users/UserName/Documents/my games/FarmingSimulator2019/mods/Courseplay_6_01_00300/AIDriver.lua:679: attempt to index field 'course' (a nil value)

**Comment by Tensuko** [comment]
full logfile as always needed.
Did you change any keyssettings ?

**Comment by biomex81** [comment]
I tried to reset all keybinds but no fixed
Also I can open the HUD only with secondary key "Left-Ctrl Del" and at the general settings "open CoursePlay" is setted to "unknown"
This is my log file:
https://pastebin.com/vHxn1Rbt

**Comment by Tensuko** [comment]
Hmm I don't see any Error.
Does this happen in all Vehicles ?
I would try a full Vanilla Game + CP to make sure there is no Modconflic.
The Settings 'Unknown' is the right Mouse click to open.

**Comment by biomex81** [comment]
Yes, it happen in all vehicles, and with CP only installed in vanilla map
Yes the settings 'Unknown' is the right Mouse click to open, instead "mouse Right Click" as usual.

**Comment by Tensuko** [comment]
When you got only CP in Mods Folder and then it still doesn't work, then something is wrong with your LS or your Keysettings (delete inputbinding.xml).

**Comment by biomex81** [comment]
Ok, it was a keybinding conflict, thank you very much ;)
