### ISSUE TITLE
Truck instead of tractor for combine offload

### ISSUE THREAD

**Issue by Lefurjah** [Courseplay/courseplay#4306]
I like to use hook lift trucks instead of tractors for offloading combines. However, when I place it in combine mood it assumes it is a tractor and pulls it to far ahead of the combine so that it can't unload.   Is there a way to set how far ahead of the combine you want the vehicle to pull or toggle between tractor and trailer?

**Comment by Tensuko** [comment]
There are parameters to change distance and stuff, but don't ask me on what page they are, just look arround when you are in Mode2 (I don't use Mode2 as long as it is in rework so I don't know it right now, sry).

**Comment by Tensuko** [comment]
Closed due to inactivity.
