### ISSUE TITLE
Coursplay klappt werkzeug nicht mehr ein

### ISSUE THREAD

**Issue by da4id** [Courseplay/courseplay#4307]
Wenn die Feldarbeit beendet ist, klappt coursplay die Maschinen nicht mehr ein. Verions 6.01.00300

**Comment by Vega56** [comment]
Du musst das selbst einstellen.

"Am Startpunkt enden"

![20190929124050_1](https://user-images.githubusercontent.com/55054246/65831131-79638000-e2b6-11e9-8ceb-bfcec73ca790.jpg)

**Comment by Tensuko** [comment]
Use this English Issue to keep that up to date: #4730
Closing here.
