### ISSUE TITLE
tractor/combine turning is choppy and slow

### ISSUE THREAD

**Issue by ImpacTas** [Courseplay/courseplay#4308]
CP version 6.02.00300 (but it happened with older versions too, not sure from which version it started happening)

When turning tractor/combine movement becomes choppy and it looks like it gassing up and stopping continuously. In game helpers turns good.
New save, no mods enabled except Courseplay, map is Felsbrunn, tractor is in game Fendt 1000 Vario with standard Horsch Pronto 9 DC on field 31.
Video:
https://youtu.be/RlRx1R0JSIs
Log: 
[log.txt](https://github.com/Courseplay/courseplay/files/3666664/log.txt)

**Comment by Tensuko** [comment]
Video is private.

**Comment by ImpacTas** [comment]
video should be fixed

**Comment by Tensuko** [comment]
Does this happen with other Tractors too ? Also: Deactivating Mods doens't help, you got to have them outside of the mods folder.

**Comment by ImpacTas** [comment]
Yes it happens with others too, I removed all mods from mods folder, there is a new log file 
[log.txt](https://github.com/Courseplay/courseplay/files/3667453/log.txt)

John Deere 6R
https://youtu.be/1fFtVIuSC0Y

There is exemple with combine, it’s not so obvious but it still stutters from time to time

Rostselmash 161
https://youtu.be/wAsNAF7ht7g

**Comment by Tensuko** [comment]
Yeah I can confirm this, happens in all turns.

**Comment by GeorgeEarslight** [comment]
@Tensuko #4001

**Comment by Tensuko** [comment]
I now this destoryed more then it helped, I am not sure if we have an other actual Issue open, so keep this one open for now.

**Comment by pvaiko** [comment]
I know, this keeps coming up, and the real problem is that those turns are driven by the code in turn.lua which drives to the discreet waypoints instead of using the PPC. It is on my list.

**Comment by pvaiko** [comment]
This should now be fixed with 306 or higher.
