### ISSUE TITLE
CombineUnloadAIDriver Branch  Unload course unload point

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#4310]
Hey,
How does one setup a unload point in the new mode two correctly?

Currently my driver backs into the silo until it hits the unload point, starts unloading, but does not move forward to unload the trailer completely.

**Comment by Tensuko** [comment]
Screenshot of the course at Bunker ?

**Comment by JDTiger** [comment]
Sorry, forgot that:
![Capture104](https://user-images.githubusercontent.com/9157835/65890583-637fb900-e3a3-11e9-8840-333b2b45cf9a.PNG)

**Comment by Tensuko** [comment]
Not sure but the Issue here could be that it is not straight out of the bunker (paralel to walls) but @ThomasGaertner will know it :)

**Comment by JDTiger** [comment]
yes, that seems to have been the problem, tried another angle now, it works.

**Comment by Tensuko** [comment]
Ah ok, good to know :)

**Comment by ThomasGaertner** [comment]
the unloading is now exactely the same in mode 1, 2, and 6. special in bunkersilo: don't need to use unload points, the last reverse waypoint is a virtual unload point.

**Comment by Tensuko** [comment]
>>special in bunkersilo: don't need to use unload points, the last reverse waypoint is a virtual unload point.<<

That is something very important to know :)
Yea one day I might have the mood for the website, but I got most problem with the graphics...

**Comment by Tensuko** [comment]
#5272
