### ISSUE TITLE
CombineUnloadAIDriver Branch  Chopper only starts at first waypoint

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#4311]
Hey:
The Chopper always starts his course at WP1, even if half of the field is done and no matter wich start option (nearest Waipoint etc.) is selected, the chopper always drives to WP1 and starts the course from the beginning

Link to the video and corresponing log: https://youtu.be/84u7-gJwncE  
[log.txt](https://github.com/Courseplay/courseplay/files/3664258/log.txt)

_Originally posted by @JDTiger in https://github.com/Courseplay/courseplay/issues/4286#issuecomment-536064969_

_started new issue to move this out of the info thread_

**Comment by ThomasGaertner** [comment]
the I would say it's a mode 6 issue isn't it ?

**Comment by JDTiger** [comment]
Yes, though its something that only occured with the beta branch, just tried the master branch and it works flawlessly.
Also, it seems to be a problem of the field, since it works perfectly fine on another

**Comment by ThomasGaertner** [comment]
hmm ok

**Comment by Tensuko** [comment]
#5272
