### ISSUE TITLE
Crazy speed of the harvester

### ISSUE THREAD

**Issue by Horozor** [Courseplay/courseplay#4313]
Hey. Today I decided to try moving in a circle on the field, but found such a problem. When the harvester reaches the turning point, its speed increases and then it continues to work at the speed of maneuver. Also, it does not stop when the hopper is full.

[Course](https://drive.google.com/open?id=10MGijox43XI58LuQwSDxEqHFhlrLU-0O)
[Log](https://gist.github.com/Horozor/e92b85f2ce506cf77edf6cb74c000186)
[Video](https://youtu.be/uaMRHr8A56o)
Courseplay_6_01_00303_1
![fsScreen_2019_10_01_03_45_31](https://user-images.githubusercontent.com/37561569/65921923-51763880-e3ec-11e9-9bfe-3eff61138bb9.jpg)

**Comment by Tensuko** [comment]
V303 works and V303_1 not ? if so, it is from the AI Turn for Combine.

**Comment by Tensuko** [comment]
Also in log:
2019-09-30 01:12 Error: Running LUA method 'draw'.
2019-09-30 01:12 C:/Users/Horozor/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00301/hud.lua:608: attempt to index local 'selectedField' (a nil value)

**Comment by Horozor** [comment]
> 2019-09-30 01:12 Error: Running LUA method 'draw'.
2019-09-30 01:12 C:/Users/Horozor/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00301/hud.lua:608: attempt to index local 'selectedField' (a nil value)

These lines from the previous session have nothing to do with this problem (I made a mistake when I copied the log). I tried to reproduce the problem on version 302, 303. On both versions, it is present

**Comment by Horozor** [comment]
It starts with version 301. I think the problem is this (6.02.00301 AI Turn experiment for combine inner headlands) on version 300 the turn is completely different and does not cause a problem

**Comment by pvaiko** [comment]
So just turn off AI Turns in the Advanced Settings until this is fixed.

**Comment by Horozor** [comment]
Yes it worked. Will wait for fix
