### ISSUE TITLE
Infinite Loading screen when using CP and AutoDrive

### ISSUE THREAD

**Issue by Bravo21Niner** [Courseplay/courseplay#4314]
Hey guys, i've ran into an issue using both Courseplay and Autodrive at the same time.  If I load up one or the other on a new map, I can load in just fine.  But if I have both mods selected, the loading screen loops infinitely.  The longest i've waited was 38 minutes, and the game doesn't respond to any inputs.  I have to Alt F4 out every time I try it.

Log attached

https://gist.github.com/Bravo21Niner/4faf6c27a6ad195b1e2a4cd01b81a133#file-log-txt

**Comment by Tensuko** [comment]
Old AutoDrive:
Load mod: FS19_AutoDrive (Version: 1.0.1.9) (Hash: 6b9cce8e25592c84cecb0b5c475b348f)
Get new one here: https://github.com/Stephan-S/FS19_AutoDrive/releases
go for 1.0.5.8
Closed.
