### ISSUE TITLE
Worker Auto Slurry Refill

### ISSUE THREAD

**Issue by JohnCorf** [Courseplay/courseplay#4319]
the worker will only refill the slurry tanker at the digester if you are in the cab, if you are in another vehicle/ on foot the worker skips the wait point and continuously loops because they are empty

**Comment by Woife1** [comment]
This sounds like the known problem with the GlobalCompany Triggers

**Comment by huffert** [comment]
Don't think so, that it is a CP issue.
Got this yesterday at field container too.

**Comment by Tensuko** [comment]
Container at field, Field Course with refill course to the container.
Logfile with debugchannel 1 and 2 active, post here pls.
It actually sounds like the same Issue as GC Trigger, could be similar one, will take a look at it.

**Comment by huffert** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3682067/log.txt)

**Comment by huffert** [comment]
hope this will help.
thx for great work anyway :)

**Comment by Tensuko** [comment]
Mode8 works perfectly for this, also GC does work with CP when use 1.1.3 or higher.
Closed.
