### ISSUE TITLE
Cp .00303 trailer doesn not Close after unloading

### ISSUE THREAD

**Issue by Heartbeatss1** [Courseplay/courseplay#4320]
Hello Everyone,
with the new 303 update not the untested.
After the unloading Trigger the Trailer doesnt close, so at the silo it instant unload the stuff ;)

Video:
https://youtu.be/QTskzhiHVLo
[log - Kopie.txt](https://github.com/Courseplay/courseplay/files/3678049/log.-.Kopie.txt)

**Comment by Tensuko** [comment]
> After the unloading Trigger the Trailer doesnt close, so at the silo it instant unload the stuff ;)

Nach dem Trigger wird der Trailer nicht geschlossen, also lädt er am Silo sofort ab ?
Das der Trailer nicht geschlossen wird sehe ich, aber was meinst du mit der zweiten hälfte ?

Wurde der Trailer denn in einer älteren Version geschlossen ? Wenn ja, seit welcher Version wird er nicht mehr geschlossen ?

**Comment by Heartbeatss1** [comment]
Hallo Tensuko,
Der Kurs fährt direkt zum Silo und belädt den Anhänger neu. Dadurch dass der Anhänger noch offen ist entlädt sich ein Teil direkt wieder am Silo.
Ich habe ein paar Versionen übersprungen da ich in den anderen Probleme mit dem flüssigkeitstransport hatte. Die Version müsste ich zuhause nach schauen. Irgend etwas um die .29X

**Comment by Tensuko** [comment]
Wird hier fortgeführt: #4534
Closed.
