### ISSUE TITLE
Error: Running LUA method 'update' - AIDriver.lua:1179: attempt to call method 'getTipState' (a nil value) - Mode8

### ISSUE THREAD

**Issue by weneedsmods** [Courseplay/courseplay#4321]
hi guys so the liquid transport mode does not unload when you're slurry tanker gets to the waiting point when it does get to the waiting point the whole game bugs out you got into like a free cam is the best way i can describe it and you cant move the only way to fix it is to stop the driver or save the game quit then reload you have to quit an reload because you cannot tab back to you're slurry tanker.  only mods i have loaded are goverment subsidy and multi filling station

here is a video demonstrating: https://youtu.be/FMeg3X9NqOc

**Comment by Tensuko** [comment]
logfile ? I already can tell you that your log gets spamed with a lua error, but we need the logfile to see it.
if this happens again: use console command cpStopAll to continue the game.

Also: that mode is not made for that way. The Nw liquid transport is made to drive to a field, and then a Fieldworker can unload from the Truck.
That what you do there should work in Mode1 just without WaitPoint and choose the right filltype. Also you maybe got to adjust the start and stop a bit: CP looks for a trigger to load the trailer, when the truck/tractor is on the way from stop to start point.

Post log with the Error happend and try the same in Mode1 and report back.

**Comment by RUGhost** [comment]
Debug channel 2 and 23 enabled 

[log.txt](https://github.com/Courseplay/courseplay/files/3680663/log.txt)

![FarmingSimulator2019Game 2019-10-02 16-09-17-17](https://user-images.githubusercontent.com/48012198/66037728-19790d80-e532-11e9-8462-672c92be80f9.png)

**Comment by weneedsmods** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3680704/log.txt)
i cant use mode 1 the button is greyed out i can only use mode 1 if i have a trailer attached

**Comment by Heartbeatss1** [comment]
Hey, i have maybe another info for you. I also got this error with every Version higher than 292. 
In 292 everything works fine with the Liquid Course

**Comment by Tensuko** [comment]
Maybe it got something to do with this, not sure:

6.01.00293: stop tippers while unloading till they are closed again

**Comment by FlameTech-Entertainment** [comment]
Maybe I can help with my log:

Activated Debug Channels: 2, 23
Courseplay Version: 6.01.00309

After the driver reaches the tipper (bga Felsbrunn) courseplay gets an error (get nil value).

[log.txt](https://github.com/Courseplay/courseplay/files/3725779/log.txt)

**Comment by Tensuko** [comment]
Mode8 should have been fixed back then, just now have another bug and is looked into.
Closing this one, as this Error should be gone for a long time.
