### ISSUE TITLE
course_management.lua:1714: attempt to call method 'GetAvailableDestinations' (a nil value)

### ISSUE THREAD

**Issue by Heartbeatss1** [Courseplay/courseplay#4322]
Hey Everyone,
after i tried the Beta one today my Savegame does not Start anymore with Courseplay.
It makes no difference, which courseplay version i choose.
The Savegame does not load anymore.
Another Savegame from yesterday also does not Startup.
I am only updated the GC and restartet my game after i found some issues with the beta version

[log - Kopie (2).txt](https://github.com/Courseplay/courseplay/files/3682944/log.-.Kopie.2.txt)

[savegame1.zip](https://github.com/Courseplay/courseplay/files/3682946/savegame1.zip)

**Comment by Tensuko** [comment]
Same Error as many ppl before you and it is again this:
Load mod: FS19_AutoDrive (Version: 1.0.1.9) (Hash: 6b9cce8e25592c84cecb0b5c475b348f)
You got an old AutoDrive, get newest here: https://github.com/Stephan-S/FS19_AutoDrive/releases
Closed.
