### ISSUE TITLE
Suggestion: Combine straw

### ISSUE THREAD

**Issue by Martinnygaard** [Courseplay/courseplay#4324]
Hi,

I am a terrible person for remembering stuff. And the case is that when CP is doing my headland, i enable the straw chopper, in order to not putting down the straw.

When the combine starts the up/down rows i intend to disable the chopper, to drop the straw for the baler - but i always forget until half the field is harvested.

Would it be possible for CP to control the straw? Set it to drop straw "always", "during up/down rows" or "Never"?

**Comment by Tensuko** [comment]
That should be possible I think.
@pvaiko on/off/headlands as 3rd option ?

**Comment by Tensuko** [comment]
For the HUD same position where you can turn on/off the fertilizer for sawing machine ?

**Comment by Martinnygaard** [comment]
That would make sense for me, yes.

**Comment by Tadeloach** [comment]
I like the thought of this as well! Or at least a way to toggle it while the cp driver is driving.

**Comment by Knowen** [comment]
i realy like that idea. 
It would be awesome, if this would be an option in CP!

**Comment by Hmmvee** [comment]
Nice would be when CP don't drop the bales at the turning or when the baler is still not completely in the row.

**Comment by Martinnygaard** [comment]
> Nice would be when CP don't drop the bales at the turning or when the baler is still not completely in the row.

I agree much - that way, the straw swath is always straight and the baler can easily pick it all up.

**Comment by Tensuko** [comment]
@pvaiko possible in advanced settings for on/off/only up+down ?

**Comment by Baker79** [comment]
Hallo.
das selbe Thema hatte ich auch eröffnet. leider ist weg oder gelöscht worden.
Eine weiterer plus punkt wäre. Das der Traktor der Ballen presst nicht mit einem Ballen vom vorgewende kolldiert und sich fest fährt.

**Comment by Martinnygaard** [comment]
Hi,

I saw that you prepared for this funvtion in the last update.
Will it be possible to also make it disable swath, then it makes the reverse to unload move?
That makes a strange pocket of straw that a CP helper cant pickup.

In general - at the end of each row, there will be a pile of straw, because it stops for a second.
If CP would turn on the shredder just before that, this will never happen.

The case is i use the Premos from Straw harvest to make straw pellets. The premos turn off if to much product is going through at the same time (normal speed + that pile stops everything)
And CP does not recognize it is turned off - therefore it just drives without shreadding.

![image](https://user-images.githubusercontent.com/26490587/81040522-d3ab6b80-8eab-11ea-92fd-8312647cfffe.png)

**Comment by Tensuko** [comment]
I get your Idea. But I am not sure if CM will change or already changed that Issue of the Premos. Will have a look.

**Comment by Martinnygaard** [comment]
> I get your Idea. But I am not sure if CM will change or already changed that Issue of the Premos. Will have a look.

But the thing is, i don't think it's a bug - i think it's a "realism feature" of the Presmos. :-)

**Comment by Tensuko** [comment]
The original issue is solved.
For the Premos that is another Problem.
