### ISSUE TITLE
Error: Running LUA method 'update' - bunkersilo_management.lua:59: attempt to index local 'secondaryMovingTools' (a nil value) - Mode9

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/courseplay#4325]
Attached Weight causes this LUA Error, If deattach, it works.
Ignore Weights ?
Also makes it unable to teach the Shovel Positions, when got Weight Atttched.

**Comment by Tensuko** [comment]
Now it works with Weight Attached, going to figure out how to reproduce it exactly.

**Comment by ThomasGaertner** [comment]
to reproduce, attach the weight first and then the shovel. other way it should work , please confirm ...

**Comment by Tensuko** [comment]
Weight 1st then front loader with shovel was no problem.
So I deattached the shovel and frontloader, so left the weight, then used the saved positions:

2019-10-04 08:39 Error: Running LUA method 'update'.
2019-10-04 08:39 I:/Dokumente/My Games/FarmingSimulator2019/mods/FS19_Courseplay/bunkersilo_management.lua:59: attempt to index local 'secondaryMovingTools' (a nil value)

I still try to reproduce it, that I couldn't even teach the positions.
Will report more.

**Comment by Tensuko** [comment]
How to reproduce:
Attach Front Loader + Shovel
Set up the Positions for Mode9
Add a Weight
Use CP to get to the shovel positions, LUA Error.
Not tested in automatic mode yet, but I think will have the same Issue.

**Comment by GeorgeEarslight** [comment]
This should have been fixed I think.

**Comment by pvaiko** [comment]
Thanks.
