### ISSUE TITLE
Mode 10: Worker starts to early

### ISSUE THREAD

**Issue by Heartbeatss1** [Courseplay/courseplay#4326]
Hey Guys,
sry for the much issues i opend the last days.

I found a new issue withe the latest Build.
I am not sure if its since the last 304 version or maybe earlier.

When the unloading vehicle reaches the bunker silo it waits correctly until the mode 10 worker is at the waiting point.
After unloading the trailer it starts to drive away and then after a few meters it stops and the mode 10 worker starts his work.
The Video is not cutted but the link is with an Timestamp.
https://youtu.be/QV6-BdKhoH0?t=779
Log is attached.

Best Heartbeat
[log - Kopie.txt](https://github.com/Courseplay/courseplay/files/3688196/log.-.Kopie.txt)

**Comment by Tensuko** [comment]
What happens if you reverse to that position ?

**Comment by Heartbeatss1** [comment]
Hey, what do you mean with if you reverse to that position?
My worker is configured to only activate if a cp driver is near

**Comment by Tensuko** [comment]
I mean reverse the unloader to the Bunker.

**Comment by Heartbeatss1** [comment]
Hey, did you mean it like that?
https://youtu.be/JkXvDGZLL7Q

**Comment by bkoster** [comment]
I had the same problems but i sold that problem to decrease trailer capacity to Max 22500 because the heap in bunkersilo can not be bigger than 31000 on one spot.

**Comment by Heartbeatss1** [comment]
@bkoster That is not the Problem, the worker wiats until everything is empty but then if the driver tries to drive away it gets stops

**Comment by bkoster** [comment]
Yes because the trailer is open and it wil not close because the tractor had ro move forward because of the heap recheas 31000 and evrytime de tractor can off load in one time you have no issus but when the tractor had to move hé forget to close trailer and hé fails and stop.

**Comment by Heartbeatss1** [comment]
@bkoster it makes no differences.

**Comment by Tensuko** [comment]
Collecting Issues here: #4254
