### ISSUE TITLE
Spielstand lädt mit CP Version .304 nicht mehr

### ISSUE THREAD

**Issue by Sequenc** [Courseplay/courseplay#4328]
Hallo, 
ich habe gestern mal seit langer Zeit von der CP Version .22X auf die Version .304 geupdatet.
Seitdem kann ich leider meinen Spielstand von der NF Marsch nicht mehr laden.
Das Spiel bleibt einfach im Ladebildschirm hängen und lässt sich nur mit Alt + F4 beenden.
Der Log konnte mir da leider auch nicht weiterhelfen, aber sicherlich gibt es hier welche die damit mehr anfangen können als ich.
[log.txt](https://github.com/Courseplay/courseplay/files/3689427/log.txt)

Vielen Dank schon mal für die Hilfe!

**Comment by Tensuko** [comment]
Load mod: FS19_AutoDrive (Version: 1.0.1.9) (Hash: 6b9cce8e25592c84cecb0b5c475b348f)
https://github.com/Stephan-S/FS19_AutoDrive/releases
Liegt nicht an CP. Neueste AD laden, dann klappts.

**Comment by Merrlin** [comment]
Vielleicht solltet ihr ne Anfrage auf die korrekte AutoDrive Version machen...oder so ne FETTE Messagebox

**Comment by Tensuko** [comment]
Oder ihr eure Mods aktuell halten :)

**Comment by Merrlin** [comment]
Das wäre natürlich auch ne Möglichkeit. Aber irgendwie ist jedes 2te Issue wegen altes AutoDrive
