### ISSUE TITLE
Wait points are ignored, Keiler 2 tested to totally fail

### ISSUE THREAD

**Issue by evansv2** [Courseplay/courseplay#4330]
Potatoe harvester seems to work somewhat OK, it stop for the unload trigger, but Keiler 2 doesnt even stop for wait points, soon as the trailer drives up Keiler 2 seems to wants to just dip out

**Comment by evansv2** [comment]
Details: Work mode for keiler 2, second route appended for the unload tried wait point and unload trigger, does not seem top stop at all, this is just on Keiler 2, potatoe harvester grimme seems to be Ok

**Comment by evansv2** [comment]
#3052 needs to be addressed please!!!!

**Comment by Tensuko** [comment]
Actually, this shouldn't be possible to work with attatched course.
But I think @pvaiko is on it and wants to add this as an option.

**Comment by evansv2** [comment]
> Actually, this shouldn't be possible to work with attatched course.
> But I think @pvaiko is on it and wants to add this as an option.

pvaiko is a private porn star))) lol  ! I love him !

**Comment by Tensuko** [comment]
Maybe this can be made with selfunload, not sure if there is a way.
@pvaiko

**Comment by pvaiko** [comment]
Closing as I don't like the 'totally fail' part of the title.
