### ISSUE TITLE
Düngerstreuer und Frontlader

### ISSUE THREAD

**Issue by teneco** [Courseplay/courseplay#4331]
Süßer Fehler: Nutze einen Fendt 500 Favorit mit **leerem** Frontlader und gefülltem Düngestreuer Axis 40.2. Beim Versuch mit CP 6.01.00304 ein Feld zu düngen kommt die Meldung "Gerät muss aufgefüllt werden"

**Comment by Axel32019** [comment]
Habe ich auch schon gehabt - Schaufel abkoppeln und es funktioniert.

**Comment by Onkel2000** [comment]
Bin mir unsicher aber funktioniert auch wenn man die Schaufel nach unten stellt, also abladen.

**Comment by Tensuko** [comment]
Bekannt und wie Axel schrieb, abkoppeln und funktioniert.
Closed.
