### ISSUE TITLE
Pflügen mit CP Error

### ISSUE THREAD

**Issue by RK54** [Courseplay/courseplay#4332]
@pvaiko,
hier übersichtlicher.
Ich pflüge mit dem https://www.modhoster.de/mods/horsch-cruiser-12xl-oy.
Vorgewende kein Problem,
nach dem ersten wenden, reagiert LS nicht mehr, und die Log ist voll bis zum Anschlag.
![3](https://user-images.githubusercontent.com/54204656/66256247-209b5800-e78c-11e9-9d14-0a5412dbd6c4.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/3693348/log.txt)

Gruß RK54

**Comment by Tensuko** [comment]
Duplicate of #4240
Closed.

**Comment by Tensuko** [comment]
Aktualisiere mal deine FollowMe Mod aus dem ModHub https://farming-simulator.com/mod.php?lang=en&country=gb&mod_id=126862

**Comment by RK54** [comment]
danke, bin ich gerade dabei, hatte noch die 1.0.1.0 jetzt die 1.3.0.6

Gruß RK54

**Comment by RK54** [comment]
Hy Tensuko,
ich weiß zwar nicht was FollowMe mit dem Pflug zu tun hat, dass der hinterher kommt?
Aber, das scheint es gewesen zu sein.
Vielen Dank für Eure Hilfen, CP wird immer besser, und die anderen wollen mir laufend AD aufs Auge drücken, mog ih nett.
Ich hätte noch eine Frage zu Wartepunkten, hier stellen oder neues Thema eröffnen?

Gruß RK54

**Comment by RK54** [comment]
![4](https://user-images.githubusercontent.com/54204656/66257278-36fae100-e797-11e9-8cd0-e6512d3a4387.jpg)
