### ISSUE TITLE
Mode 6, Mähdrescher drischt nicht

### ISSUE THREAD

**Issue by sdl112** [Courseplay/courseplay#4333]
Beim dreschen in Modus 6 startet der Drescher, drischt ein paar meter und fährt dann mit eingschalteter Haspel und gesenktem Schneid
werk weiter übers Feld, jedoch bleit die Frucht stehen.
[log.txt](https://github.com/Courseplay/courseplay/files/3693356/log.txt)

**Comment by Tensuko** [comment]
Error: Invalid mod name 'AutoDrive Course Editor'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

Außerdem muss das nicht an CP liegen, können reste von alter Frucht sein. Schonmal selber versucht ohne CP das ab zu ernten ?

**Comment by Woife1** [comment]
Du spielst auf der Multimap?
bei den Feldern die man auf einfach direkt hat sind die Einzeichnungen von Falpos nicht perfekt und die Giants-Engine baut auf diesen meist das Falsche an ;) 
die Lösung ist das Vorgewende selbber fahren dann gehts wieder wunderbar

**Comment by sdl112** [comment]
Also, da ich manuell dreschen konnte, und es auf 3 Feldern mit Courseplay nicht funktioniert hat, dachte ich, der Fehler liegt bei Courseplay. Inzwischen habe ich die Felder einmal platt gemacht und neu angebaut, jetzt funktioniert es. Es lag wohl tatsächlich an der map.

Kann also geclosed werden.
