### ISSUE TITLE
Frage bezüglich Coursplay 

### ISSUE THREAD

**Issue by FarmingPower** [Courseplay/courseplay#4335]
Hallo,

wäre es technisch möglich z.B. beim Mais Häckseln dem Abfahrer die Feldgrenzen zu übermitteln so das er vom Startpunkt aus sich nur auf dem Feld bewegen kann solange er befüllt wird und das gleiche auch macht wenn er Befüllt wurde und auf dem Weg zum AbladeKurs ist ?

da ich auf meiner Karte doch viele Wälder und Zäune verbaut habe wo er sich regelmäßig aufhängt.

Gibt es eine Möglichkeit den abfahrern zu sagen das sie Rücksicht aufeinander geben ?

**Comment by Tensuko** [comment]
#3311 #4286 einfach mal ins Mode2 Preview schauen.
Closed.
