### ISSUE TITLE
Tractor not unloading at silo - map Old Stream farm

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#4336]
I am using mode 2 to unload combine, then driver drives to silo, but doesnt unload, it just drives through the silo.
I was using the course with debug 1 and 2 (i hope i did right), then game locked up.
log text:
https://gist.github.com/bojanh66/0b935cc2ce9478b647412b75b95997d3#file-gistfile1-txt

If i put default Giant's silo on map and create unload mode2 course, it works just fine, driver finds the silo trigger and unload...but with Blacksheep's silo it doesnt work.

map is latest version 1.2.0.1
game is latest version 1.4.0.1
CP is latest version v6.01.00304

Mods active were only Axion 850 and CP.

**Comment by Tensuko** [comment]
#3311 
Closed.
