### ISSUE TITLE
Error: Running LUA method 'draw' - AIDriver.lua:683: attempt to index field 'course' (a nil value)

### ISSUE THREAD

**Issue by ujkjec** [Courseplay/courseplay#4338]
I get this error in the log
Error: Running LUA method 'draw'
C:/Users/Valera/Documents/My Games/FarmingSimulator2019/mods/Courseplay/AIDriver.lua:683: attempt to index field 'course' (a nil value)
[log.txt](https://github.com/Courseplay/courseplay/files/3694696/log.txt)

**Comment by ayumakesit** [comment]
I get it, too

**Comment by Tensuko** [comment]
Happens when and with what tools ? I guess when use Mode2 ?

**Comment by ujkjec** [comment]
was with  ITRunner 26.23 HD Pack

**Comment by ayumakesit** [comment]
> Happens when and with what tools ?

how could I find out which tools are responsible for that?

**Comment by ujkjec** [comment]
Roll-off container 30m³:
Price: 8.000 €
Combination: ITR 26.23 HD
Capacity: 30000l

**Comment by pvaiko** [comment]
When reading these issues I always wonder what people were thinking when writing them up.. Do they think that the CP developers can read their mind? What do they think, how could a developer fix their issue without knowing how to reproduce it? Very motivating.

**Comment by Tensuko** [comment]
I bet it is used in Mode2...

**Comment by StenAfMARS** [comment]
> I bet it is used in Mode2...

That is correct, I to have just encountered this error, with running in mode2.
Using modded Fendt Favorit 500 and combine CLASS Mega 208.
Fendt does run the assigned course and empties combine but CP GUI does not render.

Attached Log file:
[log.txt](https://github.com/Courseplay/courseplay/files/3695657/log.txt)

**Comment by ujkjec** [comment]
Yes. Mode2

**Comment by Tensuko** [comment]
#3311 you can try it with the new Branch in #4286 and make a specific Issue where we know that you use the Alpha Branch.
Closed.

**Comment by digaph** [comment]
I too just experienced this bug in mode 2 (Unloading combine and deliver at sell point)
As soon as I order the tractor (A base game massey ferguson 7719 with standard farmtech trailer) to start the course it hides the HUD and starts driving off into the distance until it hits a tree.
The log is filling up with endless amounts of the error message posted above.

I was working on field 7 of the Gemeinde Rade map.

`
[log.txt](https://github.com/Courseplay/courseplay/files/4055573/log.txt)
`
