### ISSUE TITLE
Combine and truck collides when offloading combine. Mode 2?

### ISSUE THREAD

**Issue by zorro625** [Courseplay/courseplay#4340]
First of all, many thanks for making this great mod :) 
Secondly, i did discover a bug while testing it out.

[log.txt](https://github.com/Courseplay/courseplay/files/3696162/log.txt)

Set up combine to harvest the field (field 12), when its full it backs up and drives to the right to be offloaded.  When combine is fully offloaded, it tries to drive back to its track and continue harvesting.  At the same time the truck tries to drive forward and to the right to wait, thus hitting the combine.  

If it helps, here is a video showing it happening : https://www.youtube.com/watch?v=_YRwX7w7pvI&feature=youtu.be 

Map : Felsbrunn. 
Mods :  Autodrive 1.0.5.1 , Courseplay 6.01.00304

Hope this helps you out.

**Comment by Tensuko** [comment]
#3311 you are not the 1st one who discovered this... also see #4286 
Closed.
