### ISSUE TITLE
Tractor lowers implement too late on turns

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#4341]
I have same problem as this guy:
https://github.com/Courseplay/courseplay/issues/3844

When starting new turn, tractor doesnt stop to lower implement, but just go which results in missed parts of field.

I use this pack of cultivators and they require more time to lower than other cultivators, but they are ideal for small maps.
https://forbidden-mods.de/filebase/file/8793-kpm-pack/

Is it possible to fix this in new release or should i search for another cultivator with fast lowering time ?

![fsScreen_2019_10_07_10_25_10](https://user-images.githubusercontent.com/32069662/66296449-dd58fa80-e8ed-11e9-97ad-fe78eadc3e57.png)

**Comment by bojanh66** [comment]
I just tried another same cultivator KPM 10m which has fast lowering speed and it works fine.
https://forbidden-mods.de/filebase/file/5470-kpm-10/

So i dont know if its problem with courseplay lowering implement too late with this cultivator or its mod problem that takes too much time to lower or maybe both...but anyway i deleted this mod and am using same cultivator from another mod creator.
https://forbidden-mods.de/filebase/file/5470-kpm-10/

**Comment by Tensuko** [comment]
If not on ModHub, we don't support them unless there is a general problem.
Did you try the same tool with slower lowering, but a different tractor, maybe a vanilla one?

@pvaiko what do you think about the lowering for tools ? Just a bit like I had with my plow kind tool from Vanilla, just that I couldn't reproduce it.

**Comment by pvaiko** [comment]
CP is using the animation time of the tool to figure out when to lower. It may also lower at the wrong place if the AI nodes of the tool are not at the right spot.
