### ISSUE TITLE
Farzeuge warten nicht bis schieber aus dem Silo ist.

### ISSUE THREAD

**Issue by hathor1411** [Courseplay/courseplay#4342]
Hy

Ich erläutere mal mein Problem. 

Wenn ich im "Feldarbeitsmodus" das Gras vom Feld zum Silo fahre, wartet der Traktor bei der eingestellten Entfernung, bis der Schieber aus dem Silo ist und auf seiner Warteposition steht. Geschoben wird im "aufschütten" Modus in einem Keilsilo.

Jetzt habe ich ein Maisfeld, welches gehäckselt wird und auch in das gleiche Silo soll. Nur warten die/der Traktor/en nicht bis der Schieber aus dem Silo ist, sondern rast gleich zum abladen rückwärts ins Silo. Dort kommt es dann zu einer deftige Kollision.
Das abfahren passiert dann aber im "Drescher abtanken und abfahren" Modus.

Ist das ein bekanntes Problem? Oder mach ich was falsch.

Kleine Hilfe wäre cool.

PS: Dank den Moddern, die uns das Game wieder so richtig schmackhaft gemacht haben.

**Comment by Tensuko** [comment]
Weil beim Häckseln abfahren der alte Mode2 benutzt wird.
#3311 aber gerade das näckseln kannst du mit einer Alpha Version ausprobieren, siehe #4286 und dann gerne ein Issue erstellen mit der Anmerkung, dass du die Alpha verwendest.

Und noch was allgemeines: Bitte immer die log.txt anhängen (drag and drop in die kommentar box).

Closed.
