### ISSUE TITLE
FS19 Failed to open xml file

### ISSUE THREAD

**Issue by pixie-farmer** [Courseplay/courseplay#4344]
Hey guys
i have a problem as soon as i put on a pair of new wheels for a jd 8530 but as soon as i start the game, i cant find it anywhere and in the log it says 
Error: Failed to open xml file '/Users/timzakrisson/Library/Application Support/FarmingSimulator2019/mods/FS19_8530_ByKOTmodsRS_V1_1/modDesc.xml'.
Load mod: FS19_8530_ByKOTmodsRS_V1_1 (Hash: 154b9d02cb5532b7aa1e96fcd10df628)
Error: Missing descVersion attribute in mod FS19_8530_ByKOTmodsRS_V1_1
all help is appreciated

**Comment by Martinnygaard** [comment]
How is this related to courseplay?

**Comment by Tensuko** [comment]
No CP Error, its a Mod Problem of the FS19_8530_ByKOTmodsRS_V1_1
Closed.
