### ISSUE TITLE
CP is using driver wage from AD

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#4345]
CP is using driver wage from AD.
Bug in CP or in AD ?
To explain: if i set driver wage to 0%, money is not reduced, if i set driver wage for example to 1000%, money is going down really really fast.

**Comment by Tensuko** [comment]
1000% is 10 times more then normaly AD use. ofc it is really really fast....
But yes, I think that is AIDriver Problem. Not sure if can solve this.

**Comment by Tensuko** [comment]
not sure if this is the same reason: #3929

**Comment by bojanh66** [comment]
Finally i found out how to reproduce this bug.
I disabled all mods, except Courseplay and Money Tool.
Bought default ingame tractor and cultivator.
Steps to reproduce bug:
1. activate normal worker (keypad H)
2. stop normal worker (keypad H)
3. start courseplay worker (fieldwork with cultivator)
4. CP will start to use wage from normal ingame worker

Can somebody test and confirm this , is it a bug in CP ?

**Comment by pvaiko** [comment]
Should now work fine with 324, reopen if not.
