### ISSUE TITLE
Mode2Alpha Error: Running LUA method 'update' - PurePursuitController.lua:507: attempt to index field 'course' (a nil value)

### ISSUE THREAD

**Issue by FarmingPower** [Courseplay/courseplay#4348]
Hallo,

wir im Titel erwähnt hat dieser Fehler mir eben die Log voll gehauen.

Habe die Datei CombineUnloadAIDriver Datei im Mod ordner.
Die Map ist eine von mir selbstgebaute 4 Fach karte.

Maschinen waren die Standart geräte aus dem Hauptspiel.

Im Anhang die Log Datei .

[log.txt](https://github.com/Courseplay/courseplay/files/3717766/log.txt)

**Comment by Tensuko** [comment]
Wann ist der Fehler aufgetreten, von wann ist die Version ? Wir zählen leider nicht hoch in dem Branch. Vor ca 18 Stunden gab es ein Update.

**Comment by FarmingPower** [comment]
Hallo,

die Version habe ich heute erst runtergeladen, folgende Version steht in der moddesc 6.01.00304

Habe 2 Abfahrer eingestellt der erste hat den Feldhäcksler erkannt und dann kam der Fehler schon. 
Ich konnte keine Kamera mehr bewegen nur noch das Courseplay menü öffnen. Hab dann das Spiel über die Console beendet.

**Comment by Tensuko** [comment]
Wie hast du die Zuordnung gemacht ?
Manuell oder Autoamtisch ? Im Falle Automatisch, musst du ein Feld auswählen.

Sollte dein Spiel mal fest hängen, nachdem du einen CP Fahrer eingestellt hast, Console Command: 'cpStopAll' verwenden.

**Comment by FarmingPower** [comment]
Ich habe den Fahrern ein festes Feld zugeteilt.

Ich werde es nochmal ausprobieren.

**Comment by Tensuko** [comment]
Kann ich nicht sagen. Ich teste den Branch bisher nur auf Felsbrunnen, da Alpha.
Ich bin noch weiter am probieren, was geht und was nicht....

**Comment by ThomasGaertner** [comment]
wie ist der Häcksler gefahren ? mit CP oder selber oder Helfer ??

**Comment by FarmingPower** [comment]
bin den Häcksler selber gefahren.

**Comment by Tensuko** [comment]
#5272
