### ISSUE TITLE
Frontgewicht wird abgesenkt - Mode10

### ISSUE THREAD

**Issue by xerion8300** [Courseplay/courseplay#4349]
Hallo wenn ich den CP benutze senkt sich ständig beim fahren das Frontgewicht ab.
Wie kann man das beheben.

**Comment by Tensuko** [comment]
Welcher Modus ?

**Comment by xerion8300** [comment]
Es ist der Modus Silageschieben.

**Comment by Tensuko** [comment]
Collecting Issues here: #4254
