### ISSUE TITLE
Left Ctrl key stopped working on v6.01.00305

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4350]
I was using v6.01.00069.
After updating to v6.01.00305, the Left Ctrl key is no longer increasing or decreasing the values by 0.5, only 0.1 ...

**Comment by Tensuko** [comment]
Stepping 5 ?
Yea we got a little key command Issue right now, but that is not important right now...

**Comment by rogeriodec** [comment]
Sorry for my bad English... I improved the sentence in the original post to be clearer.

**Comment by Tensuko** [comment]
Isn't it better to have more fine adjustments ?
