### ISSUE TITLE
It stops to unload on silo, but unloads further on the floor

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4351]
As you can see on [this video](https://drive.google.com/file/d/1umKyzGYEO3K5jMlVOIM_8xnja_1731ws/view?usp=sharing), the truck stops normally in the silo, but it does a few seconds doing nothing, then advances a little and unloads everything to the ground ...
[Here my current game](https://drive.google.com/open?id=1xysnMK19dr9TH2CN9mvQ_NXM2-BJWUp5).
How to fix this?

**Comment by Vega56** [comment]
Why do you have a unload Trigger in use? You dont need one. Just drive over the Silo.

**Comment by rogeriodec** [comment]
It worked.
Thanks!
