### ISSUE TITLE
Update current save

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4352]
At least what I understand so far is that every time I save a course, I have to name a NEW file.
This becomes annoying when you edit the current course and don't want to miss the edits.
Hence you have to create multiple versions of the same course.
Is there any way to overwrite the current course (and not always create a new course)?

**Comment by Tensuko** [comment]
Not right now, I am not sure if that will be possible, since the Course will be saved as IDs and just getting a name behind it.

**Comment by rogeriodec** [comment]
But if you load an existing course, you have the current ID... would not be easy just update it?

**Comment by Tensuko** [comment]
Merged into #4367
Closed.
