### ISSUE TITLE
Harvester speed limit dropping to 0

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4353]
Using the same file I sent in my [last issue](https://github.com/Courseplay/courseplay/issues/4351), you also can observe that in some cases the harvester speed limit dropping to 0, when the harvester reaches the some border of a field. 
In time: the harvester is using the native FS19 employee. 
When this happens, I have to manually increase its limit pressing the key "2" many times...

**Comment by Tensuko** [comment]
AIDriver active under 'Advaned Settings' ?

**Comment by pvaiko** [comment]
Sorry, don't understand the description, who is driving the harvester when this happens?

**Comment by rogeriodec** [comment]
The harvester is being driven by the native FS19 AI, not by Courseplay. 
But the truck is in the Combi mode.
I didn't get the exact cause, but what I have noticed, is after the harvester unload at least one time to the truck and after the harvester reach a border of a field (when it will start to make the curve to return to the field), its speed is being dropped to 0 and the harvester stay struggling to advance.
Then I have to manually return its speed limit.
I don't know how Courseplay is interfering in the native FS19 AI, but it seems it's happening.
But when I get the same situation, I'll create a video to show this issue.

**Comment by Tensuko** [comment]
You use the old Mode2 Combi Mode from normal Release or the new Branch ?

**Comment by rogeriodec** [comment]
This is a tricky question for a beginner :) 
What I did was just download the latest version (Courseplay_6_01_00305.zip) and try to follow the steps of [this video tutorial](https://youtu.be/uqBWlX-grgU) where I learned how to automate the grain loading and unloading process from the harvester to the truck...

**Comment by Tensuko** [comment]
So that is old Mode2, wich is #3311 also take a look at #4286 for new Mode2 status.
Won't support the old Mode2, sry.
Closed.

**Comment by rogeriodec** [comment]
So, from what I saw, one of the best features of this mod is no longer supported and the new one requires you to use only one specific type of harvester, am I right?

**Comment by Tensuko** [comment]
No. It will be just a remake of the old Mode2. What you see there is just a preview.

**Comment by rogeriodec** [comment]
In short: how to use it?

**Comment by Tensuko** [comment]
Only with branch right now, or wait for it to merge into the release.
