### ISSUE TITLE
Saatgutrechner nicht mehr vorhanden?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#4355]
Hallo Leute.
Wollte jetzt in CP v6.01.0305, die Feldgrössen bestimmen, das geht normal ja über den in CP integrierten Saatgutrechner.
Blos finde ich den nicht.
Bin mit Traktor und Düngerstreuer zum Feld gefahren, hab die Feldgrenze generieren bestimmen lassen, und als Feld 11 abgespeichert.
Habe dann einen Feldarbeitskurs zum Düngen generiert und wollte dann über den Saatgutrechner die Feldgrösse und den geschätzten Düngerverbrauch abrufen. 
Blos habe ich den in dem neuen CP hud nichtmehr gefunden.
Gibts denn noch, wenn ja wo,
Oder wurde der gestrichen?
Bzw bis zu welcher cp-version ist der noch dabei?
Lg
Andreas

**Comment by Tensuko** [comment]
Den Knopf gibt es noch, aber den Rechner nicht mehr, bzw aktuell nicht.
Steht auch recht weit unten auf der Prioliste, sry.
Closed.
