### ISSUE TITLE
Grubber mit Sähfunktion

### ISSUE THREAD

**Issue by teneco** [Courseplay/courseplay#4357]
Grubber oder Scheibeneggen mit Saatfunktion grubbern aber sähen nicht; z.B. 
Stara Asa Laser CR-DCR13
Kuhn Discolander XM52
wenn vorher Ölrettich auf dem Feld war.

CP 6.01.00305

**Comment by Tensuko** [comment]
Düngen und Säen Modus funktioniert nicht ?

**Comment by teneco** [comment]
düngen können die Geräte nicht; nur grubbern und sähen.

**Comment by Tensuko** [comment]
Ob der Modus funktioniert... Mode4...

**Comment by teneco** [comment]
nope, in Mode 4 grubbert er nur.

Im Mode 5 grubbert er auch nicht - da fährt er nur den Kurs ab.

**Comment by Tensuko** [comment]
Mode5 ist ja auch nur Kurs abfahren.

Hast du das denn mal manuell versucht ?

Wenn Ölrettich drauf war, was willst du denn mit dem Grubber bestellen ?
Denke der kann nur Ölrettich und Gras ?

Sind die Tools Mods oder Vanilla ?

**Comment by teneco** [comment]
Manuell geht es: da grubbert er den Ölrettich unter (was eine Düngestufe ausmacht) und sät dahinter Raps aus - kann man gut in der Übersicht sehen (Wachstumsstufen).
Maschinen und Traktor sind Vanilla.

**Comment by Tensuko** [comment]
Funktioniert nicht, ist ein Bug.

**Comment by pvaiko** [comment]
Manuell geht es aber mit dem Giants Helfer geht auch nicht. Du musst die Sähfunktion einschalten bevor du den Helfer (Giants oder CP) startest, dann geht es.

Das ist ein Giants Bug.

**Comment by Quintto** [comment]
Im sorry to reopen an old and closed issue, 
but I just tested the kuhn discolander  XM52 in game and in the current version the cultivator works just like a normal cultivator if it has no seed in it with an ingame worker. 
So would it now be possible to add this functionality for CoursePlay as well?
