### ISSUE TITLE
Roder lädt nicht auf dem Haufen ab

### ISSUE THREAD

**Issue by michel5998** [Courseplay/courseplay#4358]
Moin,
ich hab ein Problem und zwar wollte ich, so wie man es in echt auch macht, dass der Rübenroder die Rüben auf einem Haufen am Feldrand ablädt, nur funktioniert das irgendwie nicht, da der Roder das Abladeband nicht ausfährt am Abladepunkt
![fsScreen_2019_10_13_13_18_58](https://user-images.githubusercontent.com/49126733/66714846-5cea3c00-edbc-11e9-82bc-aa2ab16e8570.png)

ich hoffe dass mir da jemand helfen kann

**Comment by Tensuko** [comment]
Das funktioniert auch noch nicht. Eventuell lässt sich da was machen.

@pvaiko 
Mode6 Drescher Kurs anhängen zum abladen fahren (Trigger/Ablade WP) möglich ?

**Comment by Tensuko** [comment]
Grundsätzlich sollte das durch die neue Option 'Drescher fährt selber abtanken' unter den Advanced Settings einstellbar sein und der das auch machen. Nur für die Rübenmiete suchen wir noch nach einer Lösung. Eine erste Idee ist vorhanden, aber ob und wie man das umgesetzt krigt, muss man sehen.
