### ISSUE TITLE
Engine not shutting down when Fieldwork is finished.

### ISSUE THREAD

**Issue by ujkjec** [Courseplay/courseplay#4359]
Hello
During downtime, the cursor does not shut down the engines and does not save fuel. Correct please.

**Comment by Tensuko** [comment]
Not sure if that is similar to #3933

**Comment by lcc1211** [comment]
The attachments used to fold up as well, but they no longer do that.

**Comment by Tensuko** [comment]
@pvaiko 
Advanced Option like return to start (same page), stop engine and fold tool at end of course ?

**Comment by lcc1211** [comment]
Just on a regular course where you're fertilizing a field. If the attachment was capable, CP would fold it up.

**Comment by Tensuko** [comment]
From the Title of the Issue:
This is fixed, as Engine gets shutted down now when Idle or finished the course.
Closed.
