### ISSUE TITLE
Overlay characters

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Courseplay/courseplay#4361]
It is **<** and **>** + **ꓥ** and **ꓦ**
![Screenshot_17](https://user-images.githubusercontent.com/8200153/66719825-4adcbd80-edfd-11e9-90d0-f2861bb38011.jpg)

**Comment by Tensuko** [comment]
Dramatical Issue.... we will take a look into this....

**Comment by Tensuko** [comment]
@schwiti6190 maybe you have an easy fox for this ?

**Comment by Tensuko** [comment]
Seems to be gone, as I can't find the double symbol anymore.
