### ISSUE TITLE
Course not working for different tractor

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4363]
This tractor is not running courses:
![image](https://user-images.githubusercontent.com/11199752/66722368-03e1ce80-ede3-11e9-85bb-2a4743d8637a.png)
However, if I use another tractor like this, it works:
![image](https://user-images.githubusercontent.com/11199752/66722379-2d025f00-ede3-11e9-8f52-dafdc7512229.png)
What's wrong?

**Comment by Tensuko** [comment]
Logfile when this happend.
Also what do you want to do ? Send it to next Field ?
Let him start the work ?
For the Work you need Mode4 active and not Mode5

**Comment by rogeriodec** [comment]
Not getting to reproduce again.
