### ISSUE TITLE
CP Won't Work with Contracting

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#4364]
Map: Welker Farms
Equipment: Vanilla Giants tractor/mower
CP Version: 6.01.00.307
The field can't be selected.
I tried to attach my log file, but it is too large to attach here. 450MB.

**Comment by RUGhost** [comment]
If it is field 3 then you can't do it. Field 3 is undetectable for CP. The problem is in the map, not CP.

**Comment by Tensuko** [comment]
450MB big logfile ?!
Then something is realy wrong with your whole game or mods.....

And as RUGhost wrote, sounds like Map Problem.
Try to find Field Border and add to course list, if that doesn't work, its map Issue.

Closed.
