### ISSUE TITLE
will not let sow if fertilizer tank is empty

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4365]
I have this composition where the tank has seeds and fertilizer:

![image](https://user-images.githubusercontent.com/11199752/66728381-e92b4c00-ee1a-11e9-8ee2-0f673e676b9e.png)

I do land-sowing missions for other farmers.
But I don't want to spend fertilizer.
This way I leave only the seeds in the tank.
In FS19 native AI, it is possible to sow a field with an empty fertilizer tank.
However, this mod does not allow this.

**Comment by Tensuko** [comment]
it does, you got to turn off use fertilizer in settings.
I don't remember on what page it is, look for that.

**Comment by rogeriodec** [comment]
It worked. Thank you very much!
