### ISSUE TITLE
Drescher bleibt stehen

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#4368]
Ab Version 6.01.00306 - 308 fährt mein Dreschen nach abladen nicht weiter!
6.01.00305 noch ok
Mit der Einstellung "Während dem Abladen anhalten" Aktiv 
**fährt der Drescher nicht weiter.**
Bei der Einstellung "Während dem Abladen anhalten" deaktiviert
**fährt der Drescher wieder!!**

Bitte überprüfen!

**Comment by Tensuko** [comment]
#3311 #4286 

@pvaiko wird das mit Mode2 release besser oder wäre ein fix zu diesen Zeitpunkt wichtig ?

**Comment by pvaiko** [comment]
Habe gestern was kaputtgemacht. Der wird bestimmt weiterfahren wenn der Ablader wegfährt.

**Comment by pvaiko** [comment]
Weiss nicht wie ich reproduzieren kann, es wäre wichtig die genaue Schritte zu kennen, in genau welcher Situation das passiert, war der Drescher voll, hat schon gestoppt, wartete auf den Ablader, Vorgewende oder Feldmitte, wenden auf dem Feld eingeschaltet, etc, am besten ein Video.

**Comment by Lustiger-Hubi** [comment]
Der fährt nur dann weiter wenn ich 
"Während dem Abladen anhalten" deaktiviert ist!

**Comment by pvaiko** [comment]
Versuch's mit 309

**Comment by Lustiger-Hubi** [comment]
Ja funktioniert wieder!
Danke für die schnelle Bearbeitung
Danke
