### ISSUE TITLE
mode 10 level capacity changed 

### ISSUE THREAD

**Issue by docgaming** [Courseplay/courseplay#4373]
I am not sure whats going on but when i have a worker in mode 10 the capacity for the level triples and that makes it to heavy  and it can't push the  chaff to the back of the silo I use all in game items. 
![Screenshot_11](https://user-images.githubusercontent.com/48932718/66770261-1590a800-eeaf-11e9-9721-c1649f7a27fc.png)
The capacity for it is only 10k when i use it i have tried the other levels and they all are triple the normal capacity.

**Comment by Tensuko** [comment]
Funny is, that I even had that when I did it manually. I am not sure if CP Changes the capacity of the tools wich then stay.... we will take for sure a look at this.
Can you pls post a logfile anyway ?

**Comment by docgaming** [comment]
sure what debug channels will you need

**Comment by Tensuko** [comment]
not sure if Channel 9 still have debug for Mode10.

**Comment by docgaming** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3725737/log.txt)
here is a log fiel for it i had 9 and 10 open

**Comment by IDeserveToBeWrited** [comment]
If I remember correctly this was the same in FS17. I thought this was a feature, so the worker would be quicker, lol.

**Comment by Tensuko** [comment]
Issue is solved in the next release.
