### ISSUE TITLE
How to avoid collisions?

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4374]
One of the things that most hinder the resourcefulness of this mod is collisions (with vehicles and static objects).
Every time a mod-operated vehicle collides with something, it no longer knows what to do, so I always have to do manual interference.
I wonder if there is already a solution to this?

**Comment by Tensuko** [comment]
On Street there is, on Field there will be, for Objects not sure and not yet.
Closed.

**Comment by rogeriodec** [comment]
For me, collision control with other vehicles on the street is not working.
For example, a slow car ahead will be run over by the mod-controlled truck, meaning the truck is not braking.
How do I get collision control to work?

**Comment by Tensuko** [comment]
press F5 and look for orange Arrows. Mode2 still not supported in any way, just for information, see #3311

**Comment by rogeriodec** [comment]
I pressed F5  during the truck ride on the street but saw no orange arrow...

**Comment by Tensuko** [comment]
![fsScreen_2019_10_14_21_14_18](https://user-images.githubusercontent.com/27344744/66776887-c9059680-eec7-11e9-8cfb-863f597dc19e.png)
As I said, Mode2 doesn't have that yet.
