### ISSUE TITLE
Levelling and compacting problems

### ISSUE THREAD

**Issue by Vega-84** [Courseplay/courseplay#4377]
Hi
I can't get my tractor to do this, or I can but it bumps in the silo walls.  It also do not stop the tractor which are comming with chaff. Is it a general problem, or can I do something wrong?
I have followed Datalunds tutorial from FS17 CP on youtube.

**Comment by Tensuko** [comment]
Logfile channel 10 and video with all wp active.

**Comment by Vega-84** [comment]
Hi Tensuko.
Sorry but I am new with CP, where do I find the logfile you are requesting?

**Comment by Tensuko** [comment]
It is the ls log with debugchannel 10 active (cp HUD settings)
https://github.com/Courseplay/courseplay/wiki

**Comment by Vega-84** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3730630/log.txt)

**Comment by Vega-84** [comment]
[https://vimeo.com/366546583](url)

**Comment by Alkoholix** [comment]
Hello, i think your waiting point is way too narrow in front of the silo. So Courseplay can´t get proper courses into the silo. Also set your pushing blade width to more than the real working width, 7,5m or more will avoid from crashing into walls.
For unloading you can try setting an parking point for the trailers.

**Comment by Tensuko** [comment]
Actually it should start at the stop point.
Any Start in front of a wide Bunker, leads to a high angle to the heaps and will cause a Crash into Wall.

**Comment by Vega-84** [comment]
#Alkoholix
Okay I will try that 👍🏼

#Tensuko
I have started the course inside the bunker for levelling and compacting tractor, is it bot the right way to do it? 😀

**Comment by Tensuko** [comment]
Start in Bunker, forward out of it to a save place, waitpoint there, switch to reverse, reverse to the front of the bunker (not to close) and stop the course there. Thats it.

**Comment by Tensuko** [comment]
This seems to be kinda the same problem as here #4621
So closing this one and use the other one to check for enhancements...
