### ISSUE TITLE
Truck standby position blocking the harvester

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4378]
I'm on a mission to harvest potatoes.
After the truck is positioned correctly to unload the harvester for the first time, the harvester moves forward and the truck is positioned slightly forward...
![image](https://user-images.githubusercontent.com/11199752/66857681-29dfae00-ef5e-11e9-86dd-6103a802563a.png)

Then he moves further forward...
![image](https://user-images.githubusercontent.com/11199752/66857725-3e23ab00-ef5e-11e9-899d-37637a08bf53.png)

...  but on the harvester's return path, finally blocking it:
![image](https://user-images.githubusercontent.com/11199752/66857862-8511a080-ef5e-11e9-9029-6041d5179048.png)

[log.txt](https://github.com/Courseplay/courseplay/files/3730806/log.txt)

**Comment by Woife1** [comment]
This is a problem with Mode2
And the Mode2 is still in an early WIP Version (that means it didn't work as well as it should and is very buggy)

**Comment by rogeriodec** [comment]
What should I do to solve this?

**Comment by Woife1** [comment]
wait until a new version of Mode2 is released or use AutoDrive for unloding Harvester an Combines

**Comment by rogeriodec** [comment]
Thanks for the tip. Any predictions for the release of the new version of Mode 2?

**Comment by Woife1** [comment]
ask the CP-Team when they will have done ;)

You could also use anything else then the Grimme to harvest, should be better with unloading on the left side

**Comment by Tensuko** [comment]
#3311 #4286 
Closed.
