### ISSUE TITLE
Truck not following course accurately during sharp turns

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4379]
A truck's curve is not following the previously created route exactly. 
When I created the route, I drove the truck in such a way that when turning, the trailer would not bump into objects.
However, as can be seen in [this video](https://youtu.be/fRshCptiAxs), it seems that the truck is not following exactly the same route, even at low speed.

[log.txt](https://github.com/Courseplay/courseplay/files/3731523/log.txt)

**Comment by Woife1** [comment]
the newest Versions of CP have problems with curves and turns
you can see it in a few other issues

**Comment by Tensuko** [comment]
What other Issues ?
This actually looks right to me. Its not even the offset from some vanilla trucks as I see it.

@pvaiko you know anything about this ?

**Comment by pvaiko** [comment]
This is how the pure pursuit controller works, the main parameter to tweak is the look ahead distance (the distance between the vehicle direction node - yellow dot and the green line the vehicle is following). Smaller look ahead distances mean better accuracy but also instability. 

The look ahead is currently set to the turn radius by default and seems to work fine elsewhere. It is difficult to tell from this video how big it really is, looks way too far for me. You can always experiment with setting a smaller turn radius for the vehicle.

And I'll probably add the look ahead distance as a vehicle setting.

**Comment by rogeriodec** [comment]
I'm using a Roadrunner and a KS 950
![image](https://user-images.githubusercontent.com/11199752/66920509-d15dee80-eff9-11e9-82e1-bca771a08dcd.png)
Unfortunately, the game doesn't show its lengths.

**Comment by rogeriodec** [comment]
If think this is happening also due to the same problem:
![image](https://user-images.githubusercontent.com/11199752/67122795-ffdbf500-f1c4-11e9-8553-81a7b612d9b7.png)

**Comment by Tensuko** [comment]
This is also different.
How did you generate the course ?
When with smooth Corners, how is he even able to hit those parts ?
Physically not possible with that turn.

**Comment by rogeriodec** [comment]
Here how to course was generated:
![image](https://user-images.githubusercontent.com/11199752/67126640-f3a86580-f1cd-11e9-82ae-5b67bec3c672.png)

And as you can see, some corners are not being harvested:
![image](https://user-images.githubusercontent.com/11199752/67126711-1d618c80-f1ce-11e9-82b4-9274036ca3eb.png)

**Comment by pvaiko** [comment]
@rogeriodec jeez. Geometry my friend, geometry.

It is not possible to cover everything with the same turning radius. It is even discussed in agricultural books.

**Comment by rogeriodec** [comment]
I know, but this is a mod that can be improved. 
As it already does by driving in reverse sometimes, to correct imperfections.

**Comment by shadow250** [comment]
i saw this too. i compensated by recording the truck course with wider turns.

**Comment by Tensuko** [comment]
For the truck, record wider turns.
For Fieldwork, use proper settings for your tools.
Closed.
