### ISSUE TITLE
Folder organizations not working very well

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4381]
I am trying to organize my courses in folders, but it is difficult.
First, a simple intuitive movement of dragging and dropping over a folder is not possible.
Second, the manual says you must first select the folder and then click on the folder icon that appears next to each course. But I don't know how to select the folder, nothing shows if a folder is selected.
![image](https://user-images.githubusercontent.com/11199752/66881906-dd689280-ef9e-11e9-9928-7008a4dcea38.png)

How to do this?

**Comment by Tensuko** [comment]
1st won't work
2nd you click the course with the little arrow up, then click on the folder (or level 0) with the arrow down.
Just like you did there. Folder '06' got 6-7 and 6-recarga-6 inside.
So what do you want to do now ?

**Comment by pvaiko** [comment]
Very low priority, won't change.

**Comment by rogeriodec** [comment]
Now I got it, this is not so usual, but it's working.
Thank you for your help!
