### ISSUE TITLE
speed not being recovered when using key to stop driver

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4382]
Every time a vehicle finishes a course, its maximum speed is not being recovered.
![image](https://user-images.githubusercontent.com/11199752/66881839-94184300-ef9e-11e9-8ad9-3dc04dc33340.png)
[log.txt](https://github.com/Courseplay/courseplay/files/3732119/log.txt)

I noticed now when the course is completed, the tractor stops but the course is still active. Then I have to press Ctrl + 7 to turn off the course. However, pressing the Ctrl key only causes the tractor to walk again. Then I press Ctrl + 7 again and only then the original maximum speed is recovered.

**Comment by Tensuko** [comment]
If you stop it by clicking in the HUD, what happens then ?

**Comment by Tensuko** [comment]
I hope this will be solved with some keybind readjustments in #4826
Closing here just to have a bit overview about this.
