### ISSUE TITLE
Cant Select Fields In Course Generator

### ISSUE THREAD

**Issue by patch110** [Courseplay/courseplay#4383]
Just updated to latest developer version and now it seems I cant select fields while trying to create courses
Edit
Just tried in game maps and everything seems fine.
Must be an issue with the mod map I have but was working ok before updating to latest dev version
Please feel free to delete post

**Comment by Lassemikkellsen** [comment]
I am experiencing the same problem
does someone know a fix to this problem?

**Comment by patch110** [comment]
Yes go into advanced settings in course play huddle and there is several settings off by default. I turned bottom 2 on and it now works

**Comment by Lassemikkellsen** [comment]
thanks that fixed it

**Comment by Tensuko** [comment]
Scan Fields on Start up on/off in Advanced Options.

Closed.
