### ISSUE TITLE
Trailored harvester does not want to be unloaded 

### ISSUE THREAD

**Issue by evansv2** [Courseplay/courseplay#4384]
Just wanted to post a video, that I made, v310 , trailored harvesters donot work at all, nor beets nor potatoes with grimme  , soon as you set the combine ,and turn off pathfinding crashes immediately

just wanted to point this out with a video, funny thing is that harvesters built in into the vehicle work , how hard is it to enable the trailored harvesters? 

https://www.youtube.com/watch?v=V37ZN__bWo0

**Comment by Tensuko** [comment]
Whats not working ?
The tool works as I see, the unloader won't work becouse of #3311 #4286 

Can you explain it in more detail ?

**Comment by Tensuko** [comment]
Since that should be Mode2 related, I close this.
