### ISSUE TITLE
Plow not respecting option to turn on the field

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4385]
[log.zip](https://github.com/Courseplay/courseplay/files/3737006/log.zip)

I have a field with little room for maneuvering, however, as you can see in [this video](https://youtu.be/947dMz5D2-8), even with the options to turn on the field activated, the tractor is not respecting this limit.

**Comment by GeorgeEarslight** [comment]
This is an implement that does not allow reversing.
Use more headlands.

**Comment by Tensuko** [comment]
Tool is not made for reverse and you won't find anyone in Real Life that will drive this oen reverse.

Closed.
