### ISSUE TITLE
Reverse with two-hitch tractor doesn't work right

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4386]
I have this composition as my seeder:
![image](https://user-images.githubusercontent.com/11199752/66970452-04d56300-f064-11e9-8b77-300d9c43c2fe.png)

The problem is when CP tries to back up the tractor, the whole thing gets stuck, as in the image.
Should I choose a seeder that does not depend on an additional hitch?

**Comment by Tensuko** [comment]
The Tractor can't reverse, try an other.
Also the Tool is not made for use in reverse and won't happn.

Closed.
