### ISSUE TITLE
Tractor/trailer on mode 2 runs into combine

### ISSUE THREAD

**Issue by Petje81** [Courseplay/courseplay#4388]
This issue is troubling me for a longer time now but running version 310 i experienced the most problems with this (or its just a coincidence), sometimes it is more worse than others and it happened on all maps i've played (so also vanilla maps).

I run a tractor/trailer combination on mode 2 carting from field to silo which stops at a location on the road between fields. From there on i let it drive to wherever the assigned combine is at.

- When the tractor is driving up to the combine to get the trailer filled sometimes it just runs into the combine straight on not dodging it in time (tractor/trailer are driving through the crops)
- Sometimes after loading while harvesting the tractor sprints ahead of the combine and decides to cut in front of it and just take it out.
- Sometimes while "pathfinding" to the auger it wants to cross the path of the combine and crashes into it from the side.
- When loading while harvesting and the combine reaches the headland both vehicles stop nicely, wait while filling/emptying but when the trailer is full before the combine is empty while the next waypoint is on the other side of the combine the tractor just takes off and takes the combine with it.

All these problems occur with pathfinding and turn on field turned on and off, with the combine running a regular worker or a courseplay worker at any given work speed (even the standard speeds) and it is completely random.

Maybe the workers are just having some bad days and want to take out the combine....

**Comment by Tensuko** [comment]
#3311 #4286 
Closed.
