### ISSUE TITLE
Mode 9 Keybinding seems not to work

### ISSUE THREAD

**Issue by Knowen** [Courseplay/courseplay#4389]
Hello,

i assigned keys for all 4 positions of the shovel in mode 9. 
If i use this keybinding noting happens.

For example: I assigned alt+numpad 1 for the loading position. if i press alt+numpad 1 the shovel doesn't move. And yes, the shovel was in a difrent position at that time.

There is no error entry or something else in the log.
Just let me know, if you need more information.

Greetings,
Knowen

**Comment by Tensuko** [comment]
Jep, they don't work yet.
But Keybinds is a general problem on some things, will be looked into later.
(I know they are very helpful :) )

**Comment by Knowen** [comment]
Okay, Thanks for the information.

**Comment by jhomer** [comment]
I commented on this on a closed issue #4050
@Tensuko  @ThomasGaertner 
 
The shovel keybindings do work fine.
The input key for "COURSEPLAY_MODIFIER" needs to be pressed and held, then the key assigned to the desired shovel position pressed.
I have used it quite a bit and works fine.

Here was my message from #4050 

I was also having trouble with the key bindings for shovel positions.
They actually do work fine.
I looked through the current code to find and then remember from FS17 you also have to have the courseplay modifier button pressed in order for it to work.

Line: 443 of Input.lua
if courseplay.inputModifierIsPressed then
if keyStatus == 1 and vehicle:getIsActive() and vehicle:getIsEntered() then

Which this does make it quite difficult for using a controller of some kind. With limited button combinations, it kind of has to be a 3 button press on a controller to make it work.

Could the modifier button press be removed from the shovel positions?

**Comment by Knowen** [comment]
so i need to press the buttons i used to open the CP HUD + the shovel key?
Gonna test that later :)

**Comment by Rumspringa90** [comment]
Ich habe da mal ein bisschen mit der Tastenbelegung der Schaufelpositionen rumprobiert. jhomer hat recht, die Tasten funktionieren im Zusammenhang mit der taste CP:Modifikator (STRG LINKS). Allerdings nicht, wenn man in Mode9 ist. Wenn in den Modus auf Überführung umstelle, dann funktionieren die Tastenkombinationen.

**Comment by Tensuko** [comment]
Keybinds now works complete freely without modifier.
Somehow you got the press all keys once 1st or reenter vehicle to get them work.
I am on it but for now it is fixed.
