### ISSUE TITLE
Spielstand lädt nicht mehr

### ISSUE THREAD

**Issue by Phips99** [Courseplay/courseplay#4390]
Ich habe mir die aktuelle Version von Cp runtergeladen und aktiviert. Nun kann ich keinen Spielstand mehr laden.

Hier ein Bild vom Lua Fehler:

![20191017185222_1](https://user-images.githubusercontent.com/49783287/67030367-91892b00-f10f-11e9-88c4-39c38bac38aa.jpg)

**Comment by Tensuko** [comment]
AutoDrive aktualisieren (AutoDrive Github)

Closed.
