### ISSUE TITLE
90° turn - Fährt immer zu weit außerhalb des Feldes

### ISSUE THREAD

**Issue by Lars-LS17** [Courseplay/courseplay#4391]
Hallo Zusammen,

erstmal vielen Dank für eure Unterstützung. Ohne CP würde LS kein spaß machen.
Ich habe jetzt seit einigen Versionen das Problem, dass beim Feldmodus oder Sähmodus der Traktor in den Ecken extrem Weit außerhalb des Feldes fährt. Das war vor einigen Versionen noch nicht so.

Kann man das wieder so einstellen, dass der kurz vorm Feldrand stehen bleibt und dann erstmal die 90° wendet und rückwärts bis zum Rand zurück fährt. Dann würde er die Ecken auch sauber abarbeiten.
![fsScreen_2019_10_17_21_05_17](https://user-images.githubusercontent.com/31773176/67039544-db7b0c80-f121-11e9-8f58-da159040d92f.png)

**Comment by Tensuko** [comment]
Ich war auch der meinung, das er früher aufhörte und den teil den er nicht mehr gemacht hat vor dem turn, dann nach dem turn mit macht.
