### ISSUE TITLE
Kursgenerierung funktioniert nicht

### ISSUE THREAD

**Issue by Alkoholix** [Courseplay/courseplay#4392]
Hallo, ich habe zu dem Problem nichts weiter gefunden, aber bei mir lässt sich in der Version 6.01.00310 kein Kurs mehr generieren. Getestet mit leerem Modordner, außer Autodrive 1.0.6.3., auf Felsbrunn. Mit 6.01.00305 funktioniert alles.

**Comment by Tensuko** [comment]
logfile mit debugchannel (da steht irgendwo kursgenerierung...)
Was ich auf jedenfal sagen kann: Es geht! Warum bei dir nicht ? Keine Ahnung, desshalb logfile.
https://github.com/Courseplay/courseplay/wiki

**Comment by Alkoholix** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3743533/log.txt)

Hallo, danke für die schnelle Reaktion. Es ist so dass ich bei Kursgenerierung auf der Map dann keinen Acker anklicken kann. Beim Klick auf generieren kommt dann die Meldung: Konnte keinen Kurs generieren, bewegen sie das Fahrzeug... obwohl das Fahrzeug mitten auf dem Acker steht.

Ich lade mir das Archiv aber nochmal neu, nicht auszuschließen daß da eventuell eine Datei beschädigt war.

**Comment by Tensuko** [comment]
Ah ich glaub ich weis schon.
Im HUD unter Settings, Advanced Settings, Scan Field on Start aktivieren.
Glaub das Savegame dann einmal neu laden und dann sollte es gehen.
( @pvaiko Knopf zum Scannen der Felder im HUD möglich ?)

**Comment by pvaiko** [comment]
@Tensuko ja, dann sollte es gehen, ausserdem habe gerade in 311 (https://github.com/Courseplay/courseplay/releases/tag/6.01.00311) das Problem behoben.

**Comment by Tensuko** [comment]
Wie kann ich den Daumen runter löschen ? :D 
Dicke Finger am Handy is doof :D
