### ISSUE TITLE
Combine harvester inexplicable behaviour - Drescher unerklärliches Verhalten

### ISSUE THREAD

**Issue by haamic** [Courseplay/courseplay#4398]
Hello,
Recently, probably after the new LS update, I have the problem that the Combine harvester sometimes stops when it is full, sometimes with 100% full tank, continuing the CP field course.
At 100% it folds out the pipe and raises the cutterbar. But he stubbornly continues his course. So the unloader does not reach him.
Combine harvester = CP
Unloader = AD
Call setting earlier and thresher follow on "yes"
Can anyone confirm that?

Greetings Micha

Translated with www.DeepL.com/Translator
------------------------------------------------------------------------
Hallo,
Hab neuerdings, wahrscheinlich nach dem neuen LS Update, das Problem, das der Drescher manchmal anhält wenn er voll ist, manchmal mit 100% vollem Tank, den CP-Feldkurs weiter fährt.
Dabei klappt er bei 100% das Rohr aus und fährt das schneidwerk hoch. Fährt aber stur seinen Kurs weiter. So erreicht der Abfahrer ihn nicht.
Drescher = CP
Abfahrer = AD
Einstellung früher rufen und Drescher folgen auf "ja"
Kann das jemand auch bestätigen?
Gruß Micha

**Comment by Tensuko** [comment]
Ist das nur im Zusammenhang mit AD als Abfahrer, oder auch nur mit CP ?
Weil ich benutze in diesem Moment einen Drescher mit CP und er macht was er soll.

logfile bitte anhängen!

**Comment by haamic** [comment]
Teste das gerade nochmal. Bisher läufts noch reibungslos. Wer weiß woran es lag. Hab aber auch das heutige Update von CP drauf. Weiß nicht ob es dadurch wieder funktioniert. Wenn es wieder Auftritt, sende ich das log. Ich muss noch dazu sagen, gestern hatte ich 4 Drescher im Verband mit je einem Abfahrer auf einem Feld. Jetzt nur einen Drescher.

**Comment by Tensuko** [comment]
Teste mal weiter und berichte.
Denke dran, alles was Mode2 betrifft (Abfahrer) ist im moment irrlevant :)
