### ISSUE TITLE
Drescher tankt sich selber ab - inaktiv

### ISSUE THREAD

**Issue by kurtlohnunternehmen** [Courseplay/courseplay#4399]
Wird es die Funktion "Drescher tankt sich selbst ab" auch irgendwann wieder zur Verfügung stehen? Denn aktuell kann man ja die Funktion nicht nutzen (inaktiv) oder sehe ich da etwas falsch?

**Comment by Merrlin** [comment]
Wie in dem gepinnten Issue #3882 beschrieben wird der Mode 7 (ich hoffe den meinst du) leider nicht zurückkommen.

**Comment by Tensuko** [comment]
Der Mode wird so nicht wieder kommen.
Was wir schonmal überlegt haben ist, einen angehängten Kurs zum selbst Abtanken im Mode6 ein zu bauen. In wie weit das machbar ist (Trigger/Trailer usw) weis ich noch nicht.

@pvaiko machbar ?

**Comment by Merrlin** [comment]
@tensuko da fällt mir ein: wäre es nicht potentiell möglich den Drescher bei vollem Korntank zu Mode 1 wechseln zu lassen? In Kombination mit nem Parktrigger hätte man dann ja zumindest so etwas ähnliches.

**Comment by Tensuko** [comment]
Das wäre wohl fast schwerer umzubauen, als wenn man das in den Mode6 einbaut.
Im Grunde wie jeder Ladewagen Gras oder Stroh sammelt und dann mit dem angehängten Kurs zum Silo fährt, oder zum Abladepunkt oder Wartepunkt.... das müsste 'eigentlich nur' für den Drescher aktiviert werden, nur das der Drescher beim Wartepunkt das Rohr ausfährt und beim Abladepunkt einfach ablädt, das müsste genauso wie der alte Mode7 funktionieren. Ob das möglich ist, weis nur @pvaiko

**Comment by Merrlin** [comment]
Jupp genau so meinte ich das....

**Comment by pvaiko** [comment]
See #4690
