### ISSUE TITLE
Not unloading sugar beet in the silo

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4400]
I have already created a route to unload the beet into the silo twice, which is automatically loaded during harvest, the truck goes through the silo but does not stop and does not unload.
[log.txt](https://github.com/Courseplay/courseplay/files/3745070/log.txt)

**Comment by Tensuko** [comment]
debugchannel 1 and 2 active for logfile.
Can you unload there manualy ?

**Comment by rogeriodec** [comment]
Yes, I can unload sugar beet manually in the silo.
Here is the log with channels 1 and 2:
[log.txt](https://github.com/Courseplay/courseplay/files/3745152/log.txt)
And a [video](https://youtu.be/LfIhtb4Ct6A).

**Comment by Tensuko** [comment]
2019-10-18 15:04 :50 [dbg1 lp164254]     trailerFillType=10 SUGARBEET
2019-10-18 15:04 :50 [dbg1 lp164254]     trigger (135377) does not accept trailerFillType (10)
2019-10-18 15:04 :50 [dbg1 lp164254]     trigger (135377) acceptedFillTypes:
2019-10-18 15:04     2: WHEAT
2019-10-18 15:04     3: BARLEY
2019-10-18 15:04     4: OAT
2019-10-18 15:04     5: CANOLA
2019-10-18 15:04     6: SUNFLOWER
2019-10-18 15:04     7: SOYBEAN
2019-10-18 15:04     8: MAIZE

That one is not made for Sugarbeet. So it won't work.
You can get a MultiFruit Silo I think even on the ModHub that is very similar to that one.
If this is fixed on the map, then the mapper not made it to get sugarbeet unloaded there by AI.
As you see in the debug, its simply not made for unload sugarbeet there.
Closed.

**Comment by rogeriodec** [comment]
But the current silo ACCEPTS both the **loading** and **unloading** of sugar beet manually.
And FS19 correctly shows the quantities in inventory as for any grain ...
Thus, CP should allow beet (and others) automatically, since FS19 allows this.

**Comment by Tensuko** [comment]
When I check your logfile, you got no mods.
So it is Vanilla Silo and there is no Sugarbeet.
![fsScreen_2019_10_18_21_23_54](https://user-images.githubusercontent.com/27344744/67122403-0a5eb480-f1ee-11e9-9d51-24ac69274510.png)
You mix the informations on the Screen:
![fsScreen_2019_10_18_21_24_09](https://user-images.githubusercontent.com/27344744/67122497-3a0dbc80-f1ee-11e9-81ca-ec9693a8c7b6.png)
And the proove, that the Silo can't take Sugarbeet:
![fsScreen_2019_10_18_21_26_13](https://user-images.githubusercontent.com/27344744/67122510-442fbb00-f1ee-11e9-9de9-226cb67afed6.png)


The Problem I found out is, when you add Extension Silos, the game accepts even sugarbeets and stuff.
Problem here remains anway: The Trigger for the Big Main Silo reports: no sugarbeet!

**Comment by rogeriodec** [comment]
Sorry, but for the sake of logic, I have to insist: If an additional silo allows root unloading, this is a rule accepted by FS19.
Therefore it is a rule that should also be accepted by CP.

**Comment by Tensuko** [comment]
It is NOT. Its a gamebug and realisticly it should not go in as well.
We won't do anything there.
