### ISSUE TITLE
Does not warn when a tractor arrives at a stopping point

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4401]
![image](https://user-images.githubusercontent.com/11199752/67120581-f603c300-f1bf-11e9-817e-d4311604938b.png)

To create a workaround for the problem mentioned at https://github.com/Courseplay/courseplay/issues/4400, I set that when the tractor arrives at the Silo unloading point, it will stop and wait for my interaction.
However, CP does not give any warning that the tractor has stopped and is waiting for user interaction.
It would be important for CP to warn about this situation, as it already does with several others.

**Comment by Tensuko** [comment]
The Truck drives in Mode2 ?
Does it show msg in any other Mode ?

**Comment by rogeriodec** [comment]
Sorry for my ignorance, I see you talking mode 2, mode 10 ... mode n  ... what does this mean? Where do I get a list of these ways to understand?

**Comment by Tensuko** [comment]
![Modes](https://user-images.githubusercontent.com/27344744/67121834-c15a3080-f1ec-11e9-98c3-b698ee65374c.png)

**Comment by rogeriodec** [comment]
Got it. Thanks.
Yes, the truck is in Mode 2.

**Comment by Tensuko** [comment]
So thats the reason why it doesn't report it.
Closed. #3311
