### ISSUE TITLE
Loop for grain transport until the silo is empty?

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4402]
Using the grain transport mode. is it possible to have a truck load-> transport-> unload-> return to the silo and repeat the entire process AUTOMATICALLY as many times as necessary until the silo empties into that specific grain?

**Comment by Tensuko** [comment]
Just use Mode1, say what you want to load, then stick to unlimited repeats.
And no, there is no way to make him load every kind of fruit untill silo is empty.

Course for Mode1:
Startpoint position should be when the Trailer is under the pipe and stop is before the pipe.
Try it out, it works!

**Comment by rogeriodec** [comment]
Thank you, I already proceed this way.
However, there are cases where the truck has to make several trips between the silo and the buyer to completely clear the grain silo. For example, if the silo has 300,000 l of wheat, the truck will have to make several trips to sell, for example, in the restaurant.
Currently, I have to interact with CP for each silo load.
Is it possible to automate this loop? 
Or if it is not, could you implement this as a suggestion for improvement?

**Comment by Tensuko** [comment]
It is automatically....
![fsScreen_2019_10_18_21_37_01](https://user-images.githubusercontent.com/27344744/67123097-a341ff80-f1ef-11e9-9f10-f0e73ac1c15e.png)
![fsScreen_2019_10_18_21_37_08](https://user-images.githubusercontent.com/27344744/67123133-b8b72980-f1ef-11e9-8fbe-39fd33c5f247.png)

When there is not enough in the silo anymore, you have to press continue, else he wait for more to load.

**Comment by rogeriodec** [comment]
Hmm, that was the problem, I forgot to set the specific fruit in the configuration...
Now it's perfect!
Thank you!
