### ISSUE TITLE
Mode 2: driver does not always go to harvester after returning to the field

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4404]
[log.txt](https://github.com/Courseplay/courseplay/files/3745745/log.txt)

Using mode 2, the truck goes to unload at the silo.
In the meantime, the harvester stops because it is full.
When the truck returns to the field (and the harvester is stopped, full) strangely, the truck **sometimes** gets stoped inside the field and does not go to the harvester.
Other times the truck goes to the harvester normally.
I would like to understand the reason for this inconstancy ...

**Comment by Merrlin** [comment]
Do you use automatic combine finding? If so you can try to manual assign a combine.

**Comment by Tensuko** [comment]
#3311 #4286 
Closed.
