### ISSUE TITLE
Turns not working with speed over around 13 km/h

### ISSUE THREAD

**Issue by Horozor** [Courseplay/courseplay#4409]
The turns are broken from version 307. After the fix in version 307, the turns do not work as they worked before. Now the equipment makes a sharp turn at the beginning of the maneuver and begins to ride in a circle. If you reduce speed or play with the turning radius, the technique sometimes turns correctly. But it’s all the same somewhere an error, because until the 307 version everything worked differently and better.
Logs with 12 and 14 channel
[Log v305](https://gist.github.com/Horozor/c5d35db312b0a24f5217f9c73ba2f140)
[Log v307](https://gist.github.com/Horozor/964cc66ff4ef2166145829fa6b48186a)
[Log v311](https://gist.github.com/Horozor/61130bd5adf4ae15672bab5e835d8cf4)
[Video](https://youtu.be/IoSXDw_YWcI)
I continue to use version 305, so far the most stable
This happens not only with the tools on the video. I took them just as an example

**Comment by Tensuko** [comment]
Why not stick to the basic 10km/h wich is set automatically ?
It works for up to 14km/h I just tested it with the Cultiplow.

**Comment by Horozor** [comment]
Because it's too slow

**Comment by pvaiko** [comment]
@Horozor DId you watch your own video? Did you see the speed with 305? Did you see it is between 8 and 10, sometiimes 4?

**Comment by Horozor** [comment]
Then make a maximum maneuver speed of 13 km. If speed can be increased, it should work, but it does not work.

**Comment by Tensuko** [comment]
Try with V316+ and report

**Comment by Horozor** [comment]
Turns work fine. 
Now we are waiting for when mod 2 will work. The truck and harvester often get stuck at the edge of the field. 
Thanks for the work.

**Comment by Tensuko** [comment]
Closed.
