### ISSUE TITLE
Mode 2 collisions and drunk driving

### ISSUE THREAD

**Issue by KingZogg** [Courseplay/courseplay#4410]
edit: CP 6.01 .00311dev No mods loaded other than CP and Money tool.

I have tried and tried to get mode 2 working but am having a lot of issues with the pickup vehicle crashing into the combine harvester.
The follow vehicle sometimes charges straight at the combine and blocks it.
On other occasions it cuts the combine off.
Sometimes it runs it up the back.
All in all the collision detection does not seem to work properly.
I notice too that the pathfinding driving of the pickup vehicle is really odd. The algorithm makes the driver look like he is drunk and it is not very smooth.
Not quite sure how you want me to show this. Would a video be enough ?

P.S. I am a previous CP v5 user with 2017 and have no trouble with that version.
P.P.S. Thanks for putting time into getting this working guys. Best mod for FS ever.

**Comment by Tensuko** [comment]
#3311 #4286 
Closed.

**Comment by KingZogg** [comment]
Without comment ... charming.

**Comment by Tensuko** [comment]
What about you look for the Stickys on GitHub, look for all that has been said to Mode2 and just click on the Numbers I posted to read the Issues that are behind that.
I won't type everything about Mode2 over and over again. So just read the Issues.
