### ISSUE TITLE
Mist streuen und Laden

### ISSUE THREAD

**Issue by pulimatrix** [Courseplay/courseplay#4411]
Hab seit neuem Ubdate Problem das er zawar mist streut aber nicht im miststreuer einläd :/ kurs Hinzufügen brachte nix und zusammen fügen brachte nix, weder am stall da rasst er durch um nur ansatz weise zu laden selbst am silo fährt langsam ran fährt weiter ohne zu laden, nutzen tuh ich mist streuer samson flex 23 Standart

**Comment by Tensuko** [comment]
Feldkurs + Angehänger Auffüllkurs
Auffüllkurs fährt wo dran vorbei zum nachfüllen ?
Fährst du durch den Trigger durch ?
Hast du das richtige Ladegut ausgewählt ?
Logfile mit debugchannel 1 und 2 anhängen:
https://github.com/Courseplay/courseplay/wiki

**Comment by pulimatrix** [comment]
Feldkurs + Angehängter Auffüllkurs: Ja
Auffüllkurs fährt am Mist silo am hiof vorbei (GC)
Ja fahre durch einen trigger durch( Anbei Screnshot)
![fsScreen_2019_10_20_13_47_32](https://user-images.githubusercontent.com/46344269/67159084-32f6c380-f340-11e9-9dba-288b42c16cec.png)
![fsScreen_2019_10_20_13_47_15](https://user-images.githubusercontent.com/46344269/67159086-39853b00-f340-11e9-813d-03abc178e3e2.png)


MIst habe ich gewählt ja!
Anbei die log
[log.txt](https://github.com/Courseplay/courseplay/files/3747809/log.txt)

**Comment by Tensuko** [comment]
Da war der Hinweis:
GlobalCompany!

Guckst du hier: #4049
Kann man mit dem File fixen, indem man den GC Mod entpackt, Files austauscht und wieder packt.
Ein Update von GC wird noch offiziell kommen, dauert aber.

Bitte melde dich nochmal, ob dass das Problem gefixt hat :)

**Comment by Woife1** [comment]
blöde Frage warum lässt du AD nicht den Mist holen?
den Kurs hast du ja drin
und über AD funktionieren die GC-Trigger auch ;)

**Comment by pulimatrix** [comment]
weil ich auch noch miststreuen möchte? wenn mir sagst wie das geht dann mach ich das so :_D

**Comment by Woife1** [comment]
stell AD auf Modus Abholen (Ziel dein Feld oder was auch immer ;) ) Untere Ziel (wo abholen) auf "laden Mist Hof" daneben was: Mist 
AD nicht anschalten 

dann machst du in CP einfach deinen Feldkurs und setzt Use AD auf for Unload/refill (ist im CP Tabmenü an 4. stelle (sieht man auch auf deinem oberen Screenshot letzte Zeile)
dann startest du ganz einfach den CP Kurs 
warten und freuen das es funktioniert

**Comment by pulimatrix** [comment]
Danke muss ich mal Probieren bin grade am ernten danach misten dann berrichte ich mal obs klappte :_D

**Comment by Woife1** [comment]
mach das 
so funktionert alles was du für die Feldarbeit nachladen musst Saatgut, Dünger, Pflanzenschutzmittel, Gülle....

**Comment by pulimatrix** [comment]
Habs aktuell probiert geht noch immer nicht :/

**Comment by Woife1** [comment]
an was scheitert es?

**Comment by pulimatrix** [comment]
Immer noch selbiges Problem, hab autodrive Ziel, z.b. feld 17 angegeben laden mist hof dan hab ich feld kurs berechnen lasen + kurs anhängen das er den mist am hof läd mit return das er auch wieder zum feld zurück fährt, werd mal gleich probieren Feld kurs berechnen zum hof anhängen vom hof zum feld anhängen geht auch nicht, es kommt einfach nicht wird beladen 0 von 32000, bei kalk keine probleme bei dünger saatgut , herbicid keine probleme macht nur probleme bei mist :/ gülle hab ich noch nicht probiert da ich noch keine gülle hab, bei allen anderen filltypen macht er es nur mist ebend nicht hatte ja schon den debug channel 1,2 an selbiges wie schon weiter oben gepostet bin icht am ende mit meinem leitn :/ habs wie gesagt auch AD so eingestellt das ziel mein feld ist frucht hab ich mist ausgewählt und beladen das symbol laden mist hof (Anbei Mal ein Bild)
![fsScreen_2019_10_21_08_36_07](https://user-images.githubusercontent.com/46344269/67181792-ec57a680-f3dd-11e9-9efd-256b9b900e34.png)

**Comment by pulimatrix** [comment]
so was ich jetzt auch mal versucht habe, ist nur den feld kurs berechnen lassen, abholen findet er wohl automatich fährt den kurs von feld 16  (ABF feld16) an fährt zum hof fährt langsam ans silo ran fährt durch trigger und...... joar läd nicht, beim durch fahren vom trigger will er gleich feld 16 ansteuern obwohl die kurfe nach links geht fährt er nach rechts ohne geladen zu haben -.-

**Comment by Tensuko** [comment]
Also wenn es mit CP und mit AD nicht funktioniert, stimmt da was nicht.
Ist das denn ein Lager? Ist da noch was drin? (Frage musste sein...)
Auf deinem letzten Bild ist dein Miststreuer ja voll, dann kann er auch nichts laden.

Wenn es mit den anderen Sachen funktioniert, behaupte ich es ist entweder das Fahrzeug, oder der Trigger...

**Comment by pulimatrix** [comment]
Ist richtig das er voll ist weil ich mir r beladen habe, wie kann ich dir den trigger zeigen wenn es am trigger liegt? Also sind knapp 900tausend liter im lager, mit AD gehts da entläd er ja, nur cp weigert er sich, vllt mach ich was falsch, also ich stelle AD ziel mein feld 2. Ziel mist laden hof und als frucht was er lsden soll mist, zu cp, bei cp stell ich ein bzw feld berechnen macht er, dann geh ich auf AD kurs ordner such mir mistladen hof und wähle mit return soweit sogut, feld arbeit tadel los vom vold zum lager auch gut am lager läd er nicht fährt durch zurück zum feld leer! Bei use hab ich befüllen umfüllen gestellt macht er dennoch nicht

**Comment by Tensuko** [comment]
Ja moment jetzt mal langsam, das wird mir zu sehr durcheinander mit laden und entladen CP/AD....
Also:
Mit CP laden und entladen an GC Triggern geht nur, indem du die Datei ( siehe #4049 ) in GC einbaust.
Mit AD sollte es so gehen, da für AD der fix bereits drin ist.

Für AD kann ich dir nicht sagen wie es geht.
Für CP brauchst du den Kurs hin und wieder zurück und der Kurs wird am Feldkurs anghangen. (Ordner mit dem +)

Jetzt bitte ich dich bei deiner nächsten Antwort dir etwas mehr Zeit zu nehmen was Punkt und Komma angeht, da ich deine Beiträge 5 mal lesen muss um zu verstehen was du meinst.

**Comment by pulimatrix** [comment]
Mit CP Feld Berechnet!
![fsScreen_2019_10_21_17_12_51](https://user-images.githubusercontent.com/46344269/67218964-898afd00-f427-11e9-8415-1c1cf3c8768a.png)
durch eingefahrenden kurs AD mit + Über CP Angehangen am Kurs
![fsScreen_2019_10_21_17_13_31](https://user-images.githubusercontent.com/46344269/67219025-a32c4480-f427-11e9-882e-5f2ccef5c8cc.png)
 Was den so ausschaut.
![fsScreen_2019_10_21_17_13_34](https://user-images.githubusercontent.com/46344269/67219122-c6ef8a80-f427-11e9-8b70-d20b1f598848.png)

am Hof Angekommen zum Beladen von mist für das Feld.
![fsScreen_2019_10_21_17_20_32](https://user-images.githubusercontent.com/46344269/67219140-d078f280-f427-11e9-880b-e6ee20987374.png)

die Datai hab ich bereits eingefühgt, brachte jedoch keinen Erfolg.

**Comment by pulimatrix** [comment]
Fals jemand denkt da ist nix im Silo, also hab es jetzt auch mal Probiert so wie woife1 mir sagte, Feld Kurs Berechnen AD nicht angeschaltet, ohne einen kurs anzuhängem oder dazu zufügen, wartet drauf bis er Befüllt ist, entweder mach ich da was Falsch oder ich bin einfach zu doof :/

![fsScreen_2019_10_21_18_30_35](https://user-images.githubusercontent.com/46344269/67224200-fa82e280-f430-11e9-8a13-322c0e4f5dda.png)

**Comment by Woife1** [comment]
hattest du nur einen Versuch mit AD gemacht   
nach deiner Beschreibung hatte der in dem Versuch nen Rechen- bzw Übergabefehler
was dagegen helfen kann ist: Spiel neustarten und Kurse neuberchnen lassen 

weil wenn das nicht funktioniert wäre das noch ein weiteres Issue für den AD Channel

**Comment by Tensuko** [comment]
Ich muss das selber mal nachstellen, gib mir bitte etwas Zeit, im Moment ist Turn und Mode2 am werden. Ich muss halt erst etwas aufbauen, aber ich probiere es aus (muss nur nen GC lager finden...)

**Comment by Woife1** [comment]
Das einfachste nen GC-Lager zu finden ist die Multimap v2.2

**Comment by pulimatrix** [comment]
Woife1, bin Bissel begriffsstutzig sorry, erkläre mir mal genau mit übergabe Fehler! versuch das grade die ganze zeit, also was ich mache ist, Bin mit Schlepper am Feld Punkt 1, punkt 2. ich Lasse ihn Feld Kurs berechnen was er auch tut! Ohne irgendwas zuzufügen lasse ich ihn Arbeiten bis leer, nach deiner aussage müsste er lediglich ABF feld16 anfahren von dort aus zum mist lager laden zurück zum Feld weiter arbeiten So richtig? oder hab ich da einen denk Fehler oder etwas missverstanden?!

Weil, ansaat kalken etc geht tadellos! nur ebend bei mist nicht, gülle kann ich noch nicht Probieren, da noch keine gülle vorhanden ist!

**Comment by Woife1** [comment]
dein geschriebener Fehler das dein Fahrer direkt beim beladen vom Kurs falsch abgebogen ist hört sich an als würde da die Übergabe zwischen AD und CP nicht richtig funktionieren und viel zu früh zu erfolgen (kurz falsche Berechnung/bug)

Düngen mit einem Düngerstreuer oder Spritze geht auch wunderbar so

probier evtl noch den AD Modus Abholen und Anliefern evtl mag er Mist nicht nur auf Abholen sonst erstmal kp was da nicht so ganz hinhaut

**Comment by Tensuko** [comment]
Der angehängte Kurs sieht komisch aus.
Mach mal bitte einen eigenen vom Feld (starten auf Feld) zum aufladen für Mist (also einmal durch den Trigger durch) und wieder auf dem Feld enden.
Speichern, Feldarbeitskurs laden, Nachfüllkurs anhängen, ausprobieren.

**Comment by pulimatrix** [comment]
So hab das Ebend aus Probiert, Kurs vom Feld zum lager und wieder zurück zum Feld Gespeichert!
Feldarbeitskurs berechenet, Auflade kurs mit + angehangen los, Selbe Bild

**Comment by pulimatrix** [comment]
Das Lustige ist grade, Feld kurs berechnet ohne was angehangen und schon gehts über AD Problemlos, hab paar mal neu gestartet jetzt gehts auf einmal mit AD aber Mit CP nach wie vor nicht!

**Comment by Tensuko** [comment]
Ein Feldkurs berechnet man nicht, man erstellt ihn über den Kursgenerator.
Natürlich braucht man für AD nichts anhängen, wenn AD benutzt wird, AD benutzt ja auch sein eigenes Netzwerk....
Ich glaube kaum, dass du dein Global Company wie beschrieben modifiziert hast....

**Comment by Woife1** [comment]
hatte auch gerade einen "kleinen" Test (Feldkurs CP und auffüllen mit AD) auf der Felsbrunn zwar nur mit normalen Modsilo hat funktioniert
![20191021221436_1](https://user-images.githubusercontent.com/55350545/67239863-7c363880-f450-11e9-8e96-922245ebd86d.jpg)

mit CP gings auch ist ja auch kein GC-Silo
das CP die AD-Kurse mit bremsen vor Abbiegungen benutzt ist absolut spitze :)

**Comment by pulimatrix** [comment]
Tensoku, gut sorry Falsche Wort wahl ja klar hab den Feld kurs Erstelt mit hilfe vom Generator, also irgendwas scheint echt nicht zu stimmen, mal gehts mal gehts nicht, soll ich einfach mal das savegame senden? und schaut euch das mal an wo vllt da irgendwo der fehler liegt?

**Comment by Tensuko** [comment]
Gib mir etwas zeit um das zu testen.
Ich teste gerade so viele Dinge, was Turns und vorallem den neuen Mode2 angeht mit Video aufnahme etc, da kann ich nicht alles gleichzeitig machen.

Fakt ist: Wenn es mit Feldkurs+Anhang als Refillkurs bei Saatgut, Dünger, Klak usw geht (GlobalCompany Trigger) MUSS es auch mit Mist gehen.

Und ich kann es nur nochmal für alle mit GC sagen:
Schaut in #4049 rein, da ist beschrieben wie ihr einen fix für GC einbauen könnt, jedenfals sollte dieser gehen (hoffentlich nicht nur zum entladen...).

**Comment by Woife1** [comment]
Auf der Multimap sind die Saatgut, Kalk und Düngerlager ganz normale Silos (am einfachsten sichtbar im GC-Hub bzw in der Verkaufstabelle)

**Comment by pulimatrix** [comment]
Hab komplett neu angefangen Plus mods neu gezogen, selbiges Problem besteht immer noch mit fix, In GC einzufügen! mit anhänger läd er wunderbar über Coursplay ab, nur ebend nicht mit mist streuer:/ Versuch jetzt mal Eigende Kurse Durch zu probieren und Variationen Werde Später mal Berrichten ob was brauch bares Dabei rum kam.

**Comment by Tensuko** [comment]
Hab einen haufen Versuche gemacht:
- CP kann im Düngen/Säen Modus aus einem Silo Mist nachfüllen
- CP kann im Düngen/Säen Modus Saatgut aus einer GC Produktion holen und arbeiten
- CP kann im Modus1 aus dem Trigger Mist holen und wieder einlagern (Dauerschleife)
- CP kann NICHT im Düngen/Säen Modus Mist aus dem Trigger holen (verschiedene Miststreuer und Ansätze, wie man an den Trigger fährt ausprobiert)

So.... daraus soll mal einer schlau werden. An sich wird der Trigger von CP registriert, da Mode1 läuft und auch Mode4 mit GC funktioniert, sonst könnte ich kein Saatgut aus einer Produktion rausholen.
Mist nachfüllen aus einem Mod Multisilo klappt auch soweit ohne Probleme.
Warum also aus dem GC Trigger nicht ? Ich habe auch andere Trigger auf dem Map ausprobiert im Modus1, sogar mit durchfahrt durch mehrere lade und entlade Trigger, funktioniert!
Was stimmt also an der Kombination Modus4, Miststreuer und der entsprechende Trigger nicht ?!

**Comment by Tensuko** [comment]
Bitte triff deine Aussage richtig:
CP kann bei diesem GC Trigger auf der Multimap keinen Mist rausholen.

Denn:
- CP kann Mist aus Trigger laden, in alle Modi
- CP kann mit GC Triggern interagieren, sofern der GC Script das Update drin hat

Es betrifft aktuell NUR den Trigger für Mist auf der Multimap, bis ich mal eine GC Script Gebäude für Mist zum platzieren gekrigt habe! Vorher brauchen wir nicht nach Fehlern im CP oder GC suchen.

**Comment by pulimatrix** [comment]
Okey, sorry für die wort wahl, hab probleme mich manschmal auszudrücken was ich will, hoff kannst mir verzeihn ;-) jetzt zu meiner frage, willst du plazierbares Objeckt haben? oder reicht dir das Script aus der Multimap?!

**Comment by Tensuko** [comment]
Alles kein Problem, nur bitte sagen was der Stand ist, sonst drehen wir uns am Ende im Kreis und kommen nicht weiter...

Was ich brauche ist ein Platzierbares Gebäude bei dem ich irgend etwas rein packe (z.B. Stroh) und über ein Rohr (Ladetrigger) Mist laden kann auf Basis des GC Mods.
Dann kann ich das Map und auch andere Mods unabhängig testen.
Was noch wichtig wäre, dass die Entlade- und Ladetrigger weit genug voneinander weg sind (nur um sicher zu gehen).

**Comment by pulimatrix** [comment]
Ok ich frag grade bei Falpos an ob er was hat, also ich halte dich aufen stand ich würd schon gern CP voll nutzen da es echt spass macht ;-) nur hin und wieder spinnt der CP helfer ist wohl Die testerrei leid xD SPass bei seite, sobald ich was hab meld ich mich ist ja auch für andere von vorteil :D lg

**Comment by Woife1** [comment]
falls ihr noch eine schnelle Mistproduktion braucht ich hab da schnell was umgeschrieben (effektiver nutzen gibt es davon nicht ;) )
http://ul.to/34tc7j4j

falls nicht gewünscht lösch ich den link wieder

**Comment by Tensuko** [comment]
Ich mach dieses Issue zu, da es ein Problem der Karte zu sein scheint.
Wenn das Problem auch an anderen Stellen auftritt, bitte ein neues Issue aufmachen und dies hier Referenzieren.

Closed.
