### ISSUE TITLE
Right-click still opening CP even when configured for Ctrl+Delete

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4412]
I decided to change the shortcut for opening CP for the default right-click to Ctrl+Delete.
However, even when Ctr+Delete active, right-click keeps still active, ie, both are working at the same time.

**Comment by Tensuko** [comment]
Where did you change that ? In the HUD ?

**Comment by rogeriodec** [comment]
Yes

**Comment by Woife1** [comment]
Did you do this on every vehicle that you have?
This is a vehicle specific setting

**Comment by rogeriodec** [comment]
I tested a bit more and realized now that the situation is exactly this:

1. If Ctrl+Delete is active for the vehicle, when HUD is CLOSED, in fact, the right-click does not work as it should.
2. However, if HUD is OPEN, right-click works again (even with Ctrl+Delete still active for the vehicle) ...


Take the test to see if the same thing happens to you.

**Comment by Tensuko** [comment]
Ctrl+Delete is only for open.
Right-Click is always for activating mouse.
It is only about what to click for open the HUD.
And it works as it should.
Closed!
