### ISSUE TITLE
Drescher wie Häcksler abtanken - Möglich?

### ISSUE THREAD

**Issue by kurtlohnunternehmen** [Courseplay/courseplay#4413]
Kann man eigentlich mit CP den Drescher wie einen Häcksler nutzen - also ohne zwischen zu bunkern - direkt abtanken wie beim Maishäckslen?

**Comment by Tensuko** [comment]
Im Prinzip ging das im 17er, aber noch nicht alle Funktionen wieder da und wenn das Rohr in der Frucht ist, ergibt das keinen Sinn.
Aber erstmal den Mode2 aufarbeiten, siehe #3311 und #4286
