### ISSUE TITLE
How to connect to bi-directional waypoints?

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4414]
I'm trying to create a bi-direction (blue) route and when I deleted some blue waypoint, after trying to link them again, AD is creating a green waypoint.
![image](https://user-images.githubusercontent.com/11199752/67166349-b88c6a80-f364-11e9-9795-b3a30a3a9269.png)
How to do this?

**Comment by Woife1** [comment]
This is the false page, here is Courseplay

with your conection tool in AD works this
you build a way between the red and the yellow point
if you turn the two (on your picture) and connect you get a blue/violet line

**Comment by rogeriodec** [comment]
Oh shame, sorry!
Even so, thanks for the tip!
