### ISSUE TITLE
leveling and compacting: Wrong tool for this mode

### ISSUE THREAD

**Issue by Quintto** [Courseplay/courseplay#4415]
the leveling and compacting mode isn't working for me,

when I start the course courseplay says that I have the wrong tool for this mode. I tried it with the small 3m level (forgot the name) and with the 4m Holaras. both with an ingame 511 tractor and with a modded 1055XL but it just doesn't seem to work?

why would this be?

**Comment by Tensuko** [comment]
For leveling and compacting you don't use a shield.
That is actual set in the XML of the tools.
You can use the othr option (click on the text) and use the shileds, but when you still got a Bunker where Tractors got to drive through, its bad Idea (or make unload reverse...)

**Comment by Quintto** [comment]
So I just need to try it without a shield attached, and the compacting will also level the pit for me?
I'll give that a try later today

**Comment by Quintto** [comment]
it's working now, thanks for the help!
