### ISSUE TITLE
Trateurs ne s'arrete plus lors d'une marche arriere. (someone can help Translate ?)

### ISSUE THREAD

**Issue by Bernard-57** [Courseplay/courseplay#4416]
Depuis la dernière version du CP quand je lance un tracteur du hangar il ne s'arrête plus en fin marche arrière et ne repart plus en marche avant.
Fonctionne très bien avec la version  06.01.00310.

**Comment by Tensuko** [comment]
Translator gave up on this.
- Picture
- Tool
- Workmode
- logfile

**Comment by Tensuko** [comment]
Drive from Field 7 to Field 4 with Mode4 ?
Doesn't work ?

**Comment by Bernard-57** [comment]
Non car le condor se déploie.

**Comment by pvaiko** [comment]
Not sure I want to spend time on translating from French and trying to understand what the problem is, if this is important for the person reporting the issue, he should take the time and effort to write it up properly in English.
