### ISSUE TITLE
Error: Running LUA method 'update' - toolManager.lua:441: attempt to call method 'getAttachedImplements' (a nil value)

### ISSUE THREAD

**Issue by Petje81** [Courseplay/courseplay#4417]
Today a ITRunner for silos was released on the ingame modhub. Now i know there are issues with CP and ITRunners so if this problem is one of them or a new one, now you know.

When attaching the silo to the ITRunner the game freezes in a way you can only press one key one time before it stops working. So in the end everything freezes...

Here's a log:

[log.txt](https://github.com/Courseplay/courseplay/files/3752507/log.txt)

**Comment by DirkSch** [comment]
This mod has the problem: 
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=142834&title=fs2019

if you attach the container wit the hkl crash the game instantly.

**Comment by Tensuko** [comment]
It got a fixed version i ModHub and it is working.
Closed.
