### ISSUE TITLE
How to use CP with AutoDrive to unload combine? 

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4418]
Although I've seen there is a "use Autodrive" option in HUD, I can't get how can I use it to replace the Mode 2, ie, unload the harvester in a field to a truck and transport and unload it to a silo and then return to the original field to wait for more load.
Any tutorial?

**Comment by Tensuko** [comment]
By simple use AD only for the Driver and CP for Combine, nothing needs to be set there.. Ask in AD GitHub.
Closed.
