### ISSUE TITLE
Why to limit headland passes to 50?

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4419]
I have this to harvest potatoes:
![image](https://user-images.githubusercontent.com/11199752/67240480-f1414800-f427-11e9-8622-c5976407240f.png)

This is only 1.8 m wide.
To avoid excessive maneuvering in an uneven field, I always use the Normal Headland option when generating a course.
However, I need more than 50 passes to cover all the field with this spiral way:
![image](https://user-images.githubusercontent.com/11199752/67240582-2057b980-f428-11e9-9c86-5fd8886f8cfe.png)

How to solve this?

**Comment by Woife1** [comment]
switch the option under "cendro do campo"
there must be an option for spiral way (it is experimental)

**Comment by pvaiko** [comment]
You can also skip rows so there'll no reversing.

I can increase that limit, not sure how realistic is harvesting a field of this size with 1.8 m, how long does it take to finish?

**Comment by rogeriodec** [comment]
> switch the option under "cendro do campo"
> there must be an option for spiral way (it is experimental)

Spiral seems to be a good solution, thank you!

**Comment by GeorgeEarslight** [comment]
This looks like more than 10k waypoints. Are you planning to leave that working all day?

**Comment by Tensuko** [comment]
There are ways to get arround of to many turns and Ideas have been said.
I think that can be closed...
