### ISSUE TITLE
Tipping at the bunker doesn't fully empty the trailer

### ISSUE THREAD

**Issue by Big-Bambino** [Courseplay/courseplay#4420]
Hello,

I'm just wondering, when CP reverse empty's into a bunker, when the pile is saturated at the back of the trailer and the trailer isn't fully empty. Is there a option to make the tractor go forward a little bit, to empty the rest that is in the trailer ? Or some kind of work around ? Because otherwise CP doesn't move and you have to manually empty the rest.

I guess this is only a issue when you reverse in a bunker.

Sorry for my poor English.

Kind regards, Big-Bambino

**Comment by Tensuko** [comment]
There will be some Improove for Bunker with Mode2 release (you don't need unload WP anymore, just reverse into silo). So I am not sure if that would be solved then.
Normaly, when he can't tip there, he should move forward automatically.

You could try this out by using the Mode2 Branch, more Infos in #4286 
Try out and report.

**Comment by Big-Bambino** [comment]
Nice ! I didn't realise that you needed to put down a unload point, for the tractor to go forward automatically. I was so used to FS17 when the tractor did go forward and didn't need the unload point. 

So i guess that it doesn't work when it's a i3d/trigger, that the program doesn't allow the forward movement ? just like if you want to empty grain in a silo.

At least i can silage like this now, i'm more than happy to do so.

Nice job with CP you guys are great

**Comment by Tensuko** [comment]
So its solved I guess, anything more about this Issue, let me know.
Closed.
