### ISSUE TITLE
Tractor no longer stops in reverse

### ISSUE THREAD

**Issue by Bernard-57** [Courseplay/courseplay#4421]
Since the last version of the CP when I launch a tractor from the hangar it no longer stops at the end of the reverse and does not start again.
Works very well with version 06.01.00310.
![image](https://user-images.githubusercontent.com/56793536/67304293-e7851680-f4f3-11e9-85d8-a47acde594aa.jpg)
Tracteur fendt 1050
Condor 15001
[log.txt](https://github.com/Courseplay/courseplay/files/3756867/log.txt)

**Comment by pvaiko** [comment]
Could you provide a log (and maybe a video?) with debug channels 12 and 14?

**Comment by pvaiko** [comment]
Also, are you using an Autodrive course?

**Comment by Martinnygaard** [comment]
My combines did this recently (earlier today - cannot remember if it was before or after i updated CP to newest beta release)

It did it only during headland course, while reversing for the corner turn maneuver.
(Headland was also the only part of the course that had reverse parts in it)

**Comment by Merrlin** [comment]
Das kann ich so bestätigen. Ab 311.0 hat mein Drescher nicht mehr angehalten. War auf der Hof Bergmann Feld 5 Vorgewende scharf. Drescher war der RSM 161.

**Comment by pvaiko** [comment]
Great, but still no logfile with debug channels 12 and 14.

**Comment by Bernard-57** [comment]
Thank you for looking at my problem
Sorry I can’t help you anymore being 66 years old I’m not very good at computers.Bravo for the work you do.
[log.txt](https://github.com/Courseplay/courseplay/files/3760137/log.txt)

**Comment by Tensuko** [comment]
I tested 311.4 with several tools but I got no Issue at all....
No Idea what you guys doing. Hof Bergmann Field 5, what tool ? Combine ? How did the course look like ? I want to reproduce this exact situation!

**Comment by Martinnygaard** [comment]
> I tested 311.4 with several tools but I got no Issue at all....
> No Idea what you guys doing. Hof Bergmann Field 5, what tool ? Combine ? How did the course look like ? I want to reproduce this exact situation!

I sadly does not have log file. I will try to reproduce it next time the field needs harvesting. (soon)
I was running Fenton Forrest 4x from Stevie.
Using two Fendt Ideal combines in convoy, doing 3 headlands.
AD was doing the unloading.

**Comment by Merrlin** [comment]
Ich kann dir die Daten erst frühestens Samstag Abend geben weil bin mim LKW unterwegs. Aber beschreiben kann ich.
Drescher Rostselmash RSM161 mit standardschneidwerk.
Feld 5 mit Weizen.
Kurs: Startpunkt rechte Kante Mitte, 2 Vorgewende scharf im Uhrzeigersinn.
Version 311 (ohne Zusatz)
AI Turning war glaub ich an (wobei ich mir da absolut unsicher bin)

**Comment by Tensuko** [comment]
311 ohne PPC ist eh nicht relevant und der AI Turn hat auch nichts damit zu tun.
Probiere 311.4 und berichte

**Comment by Merrlin** [comment]
Mach ich... Bei Problemen CH. 12 +14?

**Comment by Tensuko** [comment]
Kommt auf das Problem an, in diesem Fall ja.

**Comment by Merrlin** [comment]
Problem gefixt... Habs mit der 313 probiert und der Bug lässt sich nicht mehr wiederholen.
