### ISSUE TITLE
FS17 Tipping problem.

### ISSUE THREAD

**Issue by tryst46** [Courseplay/courseplay#4425]
I set the tractor to unload the combine and drive to the silo to tip there. I have done this before in FS13 with courseplay quite successfully and it tips according to the settings on the trailer for left, right or rear tipping.

The problem I find with FS17 Courseplay is that it insists on driving on while tipping. This results in half the load being tipped on the ramp leading down from the silo tip area. It also insists on tipping to the left despite the trailer being set to tip to the rear.

I have tried setting a tip point and then following it with a wait point for 20 seconds, hoping that it would stop the tractor moving forward until the trailer was empty. The problem is that it ignores the wait instruction until the tipping is complete, this takes it way past the wait area.

**Comment by Tensuko** [comment]
I hightly doubt that there is still any support for the FS17 Version of CP...

**Comment by tryst46** [comment]
Does anyone know of a work-around?

**Comment by Tensuko** [comment]
Did you look for a Tutorial ?
I am sure that was working in FS17, maybe you do something wrong.

**Comment by Tensuko** [comment]
Sry but we don't support CP5 (FS17) anymore.
I rly suggest you to look for Tutorials for FS17 CP on YouTube.
I only know a rly good one in german, maybe you can get along with that:
https://www.youtube.com/channel/UCAdM47qDXS5cGr1ZfD_8U-Q

Closed.
