### ISSUE TITLE
Plötzlich dropt die FPS auf 10

### ISSUE THREAD

**Issue by Phips99** [Courseplay/courseplay#4426]
Wenn ich in einen Spielstand reinlade und warte paar Minuten dropt sofort die FPS auf 10.
Es wird folgender Fehler ausgeworfen.
![20191023190756_1](https://user-images.githubusercontent.com/49783287/67417365-dc4fea80-f5c8-11e9-9937-db2c5716a5a7.jpg)

**Comment by Tensuko** [comment]
Und wo auf dem Screenshot steht etwas von Courseplay ?
Wo ist das komplette Logfile ?
https://github.com/Courseplay/courseplay/wiki

**Comment by Phips99** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3763650/log.txt)

**Comment by Tensuko** [comment]
Error: Invalid mod name 'FS19_Buy_Forage_1.1'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

Error: Failed to open xml file 'C:/Users/Philipp/Documents/My Games/FarmingSimulator2019/mods/LS19Real_straw_texture/modDesc.xml'.
Load mod: LS19Real_straw_texture (Hash: 8ef64b2b9128ea197a08895e578273d6)
Error: Missing descVersion attribute in mod LS19Real_straw_texture

Nur eine Map im Mods-Ornder erlaubt! Hab mindestens 10 gezählt.

Paar Farmland Errors, Animated object Errors, usw
Mod Issue, hat nichts mit CP zu tun, eher mit einer deiner Maps!

Closed.
