### ISSUE TITLE
Fieldwork turn issue

### ISSUE THREAD

**Issue by RedMonster-HUN** [Courseplay/courseplay#4428]
https://youtu.be/QOKR5t8QMd8

**Comment by Tensuko** [comment]
Exact version ? Logfile with debugchannel 12 and 14

**Comment by RedMonster-HUN** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3765888/log.txt)
Version number is in the title of the video. AI turn maneuvers and virtual waypoints switched on.

**Comment by RedMonster-HUN** [comment]
https://youtu.be/mJBQIUSNptg
This was recorded in version 311.6
The map is the same as yesterday.
[log.txt](https://github.com/Courseplay/courseplay/files/3766047/log.txt)

**Comment by Tensuko** [comment]
I try this later...

**Comment by RedMonster-HUN** [comment]
Is it possible, that Claas dlc messed the things up?

**Comment by pvaiko** [comment]
No, you are fine, I messed it up.

**Comment by pvaiko** [comment]
Should all be good now with 311.7 hopefully.

**Comment by raxtor** [comment]
I like AI turn maneuvers improvements but is there any chance to fix next turn maneuver problem #4091?
