### ISSUE TITLE
Tractor drive in circles infinitely

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4429]
[log.txt](https://github.com/Courseplay/courseplay/files/3764806/log.txt)

As https://github.com/Courseplay/courseplay/issues/4372, this tractor also goes to an infinite loop:
https://youtu.be/QjFoogZcxeM

**Comment by pvaiko** [comment]
Duplicate of #4372. Also, try with the PPC on (advanced settings).

**Comment by rogeriodec** [comment]
I don't understand, you say it's duplicated but the other issue was closed and the problem persists...
What does it mean?

**Comment by pvaiko** [comment]
Have you tried with PPC on?
