### ISSUE TITLE
Potato Harvester and Semi

### ISSUE THREAD

**Issue by Gibbanator** [Courseplay/courseplay#4430]
Tractor will not go to full potato harvester. Notice combines pipe is in fruit and will not go to harvester to unload.. I can only get the semi to go when I click request driver from the combine.

Note:
Semi still turns close to combine to line up and pushes the combine instead of pulling up beside combine... Semi will also sometimes wait for combine in the next row of the combines path instead of path that has already been collected

**Comment by Tensuko** [comment]
#3311  #4286 
Closed.
