### ISSUE TITLE
Unloading harvester with Claas DLC not working wirh CP / AutoDrive

### ISSUE THREAD

**Issue by TobiHH78** [Courseplay/courseplay#4431]
Not sure if this is more a AD issue or a CP issue (or a combination of both)
Just wanted to make sure that this is also mentioned here,, so that hopefully a quick solution can be found.
https://github.com/Stephan-S/FS19_AutoDrive/issues/682#issuecomment-545609111

**Comment by Tensuko** [comment]
I am not into using AD for unloading, so I can't rly try this.
But I will check on the Claas Combines in general.

**Comment by Martinnygaard** [comment]
As i see it, it is because the claas combine does not open the pipe. (Which is the sign AD is looking for, when searching for a combine to unload)
Today CP already has a code specially for open the pipe for AD to see, so i guess this bug can be fixed both in CP or AD.

**Comment by Iwan1803** [comment]
I don't think that CP extends the pipe for AD. This is an action/trigger from AD itself.

**Comment by Tensuko** [comment]
From what I read on Ad GitHub, its an AD problem. As CP only waits for AD to come, then CP opens the pipe.
Closing this here. Continue on AD GitHub, if Stephan need Infos, he will let us know.
