### ISSUE TITLE
Mode 2 Alpha: CombineUnloadAIDriver.lua:161

### ISSUE THREAD

**Issue by Knowen** [Courseplay/courseplay#4432]
Hello,

i set up a chopper on field 7 Ravenport also one unloader. 
First i started the chopper and after that the unloader. Then this error occures:
`2019-10-24 21:50 D:/LS19 Mods/FS19_CoursePlay6_1/CombineUnloadAIDriver.lua:161: attempt to index field 'combineToUnload' (a nil value)
2019-10-24 21:50 Error: Running LUA method 'update'.`

Also the Hud and camera freezes and i had to use the command cpStopAll to get rid of it.

I also tried to unload a combine ( i saw that the early implements were done a couple days ago). I used a new Claas DLC combine. 
I got this error message: 
`2019-10-24 21:50 D:/LS19 Mods/FS19_CoursePlay6_1/base.lua:675: attempt to perform arithmetic on field 'fillLitersPerSecond' (a nil value)
2019-10-24 21:50 Error: Running LUA method 'draw'.`
What i can say is, that the unloader follows the combine pretty well, but this error message pops up without a pattern. As for now, i cant figure a pattern out. 

Here is the log: 
[log.txt](https://github.com/Courseplay/courseplay/files/3769303/log.txt)

Greetings,
Knowen

**Comment by Tensuko** [comment]
Well, latest update we made a change to the Mode2 HUD Page.
You can select there, what Combine to unload and set the Field (I think currently it is just for overview).
On my tests it works pretty good and I didn't get the Error.
Going to make more tests based on your information.

**Comment by Tensuko** [comment]
Wasn't able to reproduce this, are you sure you got the newest version from 3 days ago ?
The HUD should look like this:
![fsScreen_2019_10_24_23_10_05](https://user-images.githubusercontent.com/27344744/67525655-74c29980-f6b3-11e9-959a-9d86eb9254de.png)

**Comment by Knowen** [comment]
I downloaded the latest version earlier today. And my HUD looks like yours. 
By choosing the field you just filter the avaiable combines. 

On both tests i selected the right combine/chopper in the HUD.
So...maybe there is a problem with the new Claas DLC vehicles in alpha mode 2?

**Comment by Tensuko** [comment]
Will test the claas combines tmr with mode2 alpha....
Sadly, somehow GIANTS have done some weird stuff with the combine else I got no clue for those Issues....

**Comment by Knowen** [comment]
Okay, i'll make a new test later and report back.

**Comment by Knowen** [comment]
Okay, something was wrong on my side. I dont know what was wrong, but i got the chopper with two unloaders running.

But i noticed some other bugs, little errors.

![fsScreen_2019_10_25_16_19_48](https://user-images.githubusercontent.com/47173160/67583318-a424e500-f74b-11e9-8187-a316a1120a64.png)
So..the chopper wants to do a right turn but the tractor blocks his way. The tractor stands still and waits till the chopper finished his turn. Could it be possible, that the tractor stops earlier? 

`2019-10-25 15:53 D:/LS19 Mods/FS19_CoursePlay6_1/TrafficControllerSolver.lua:17: attempt to index field 'otherVehicle' (a nil value)
2019-10-25 15:53 Error: Running LUA method 'update'.`
The chopper was running with two unloaders. I manually stopped one and assigned him a new course to a diffrent silo. If i pressed start CP, the error message above occures in the log. All CP driver stops working properly (the chopper continues driving without chopping the maize, the both unloaders starts driving circles) and i used the cpStopAll command.
Once i restarted every CP driver, everything goes on.

A few minutes later i wanted to assign a CP driver to mode 10, so a little bit of work inside the silos gets done. So i set up a course...as soon as i gehts inside of a Silo with a shield the game start to stutter and this is in the log:
`2019-10-25 16:13 D:/LS19 Mods/FS19_CoursePlay6_1/CombineUnloadAIDriver.lua:1287: attempt to call method 'isAutoAimNodeFixed' (a nil value)
2019-10-25 16:13 Error: Running LUA method 'update'.`
Okay, didnt work so i tried the other mode leveling and compacting. No error in the log, but it didnt work. The tractor just stands still in front of the silo and does nothing. 

I just wanted to mention last two things with the mode 10, maybe the "alpha mode 2 CP version" doesnt work well on this mode.

[log.txt](https://github.com/Courseplay/courseplay/files/3772742/log.txt)

Greetings,
Knowen

**Comment by Tensuko** [comment]
That could be couse of some changes to Bunker stuff, not sure.
Thanks for the Tests.

**Comment by Reiko40** [comment]
Der neue Mode 2 sieht sehr gut aus. Freue mich schon wenn er veröffentlich wird. Macht weiter so.

**Comment by Tensuko** [comment]
#5272
