### ISSUE TITLE
Stops at field end when plowing

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#4435]
Does not turn and continue, just stops after a row
![fsScreen_2019_10_25_15_55_38](https://user-images.githubusercontent.com/21023840/67577249-69697f80-f740-11e9-9b8c-69086a1ce5ef.png)
no entry in log, please tell me what debug channel you need
map is "the pacific northwest"

**Comment by Tensuko** [comment]
Channel 12 and 14.

**Comment by Gibbanator** [comment]
looks like the tractor is facing the opposite direction of the arrows

**Comment by Tensuko** [comment]
v313 should have solved the Issue, try it out.

**Comment by iljarogoff** [comment]
No, still having it. Tractor just drives a little further, but stops then.
![fsScreen_2019_10_25_16_55_07](https://user-images.githubusercontent.com/21023840/67581404-3dea9300-f748-11e9-90b0-83fc6c104f0a.png)

**Comment by Tensuko** [comment]
Channel 12 and 14, log and maybe screenshot of the displayed line.

**Comment by iljarogoff** [comment]
here we are again :)
![fsScreen_2019_10_25_16_58_46](https://user-images.githubusercontent.com/21023840/67581725-d1bc5f00-f748-11e9-912a-86bf1ac8f0e8.png)
![fsScreen_2019_10_25_16_58_53](https://user-images.githubusercontent.com/21023840/67581731-d2ed8c00-f748-11e9-80ca-d2f3bcf54a57.png)

[log.txt](https://github.com/Courseplay/courseplay/files/3772618/log.txt)

**Comment by pvaiko** [comment]
Turn off AI turns for now.

**Comment by pvaiko** [comment]
Interesting, only does this with the plow. This is some Giants weirdness.

**Comment by pvaiko** [comment]
I messed it up, obviously. Should be ok with 315.
