### ISSUE TITLE
Potato Harvester

### ISSUE THREAD

**Issue by Gibbanator** [Courseplay/courseplay#4436]
Distribution Belt on a Potato Harvester is on the right unlike the extendable pipes on a normal harvester which is on the left (when looking from behind the vehicle). The belt is fixed and does not retract after distribution to the trailer.

Trailer will wait for Harvester to get to fill level in clear lane but it is to close for when the Potato Harvester makes it turn the distribution belt  hits the waiting trailer which causes major problems and has to be corrected manually and everything must be reset. This has to be done many times since the potato harvester collects thin rows.

The Trailer needs to wait further out in order for the potato harvester to pass unrestricted.

Is it possible to do this when collecting from a potato Harvester?

**Comment by Tensuko** [comment]
I guess you use normal release Version, so this is #3311 
You can take a look into #4286 and try out that Version and report with the needed Information (Screenshots, logfile and so on).
I must say I didn't test it yet, couse only the newest Turn Rework (V312+) make it possible to use the Harvester in a good way.

**Comment by Gibbanator** [comment]
I should of put the Version of courseplay I was using v6.01.00313

Didn't take screen shots :( thought this was simple explanation. Will start another potato harvest and get the info you requested..

**Comment by Tensuko** [comment]
That normal Release is just not with the new Mode2, thats the problem.
So there won't be any changes for your Issue.
We have an extra Branch you can check in #4286 and use that one to test it and report back, but in a new Issue pls and mark it with something like 'Mode2 Alpha' so I can sort it :)
Closing this.
