### ISSUE TITLE
Return to 1st waypoint, some mode/tools can only changed in advanced settings, not in HUD

### ISSUE THREAD

**Issue by RedMonster-HUN** [Courseplay/courseplay#4437]
https://youtu.be/hBahJo1-FGg
Recorded in version 313. Returning to first point doesn't work at any kind of field work.

**Comment by Tensuko** [comment]
Can't reproduce:

![fsScreen_2019_10_25_22_42_15](https://user-images.githubusercontent.com/27344744/67603320-ced96280-f778-11e9-9a74-341ec27baded.png)

It stands at Startpoint and the Endpoint is on the other Side of the Field.

Logfile Channel 9 12 14 maybe can see something there.

**Comment by Tensuko** [comment]
What I noticed is, when Combine is in Mode6, click in the HUD doesn't change the Return option, only under Advanced Settings.

**Comment by Tensuko** [comment]
You have to change that under Advanced Settings.
The Setting in the HUD is only for display right now somehow.
At least on some Tools. Will write it down for enhancement.
