### ISSUE TITLE
Lua Fehler 

### ISSUE THREAD

**Issue by Phips99** [Courseplay/courseplay#4438]
Hallo,

plötzlich tritt ein Lua Fehler auf (siehe Bild) und das Spiel hängt sich auf. Man kann nichts mehr machen.

Ich habe den Claas Tucano (Platinum Addon) und den Claas 660-610 (Platinum Addon) auf einem Feld benutzt. Eben als Drescher und als Abfahrer zum Verkaufen.

Hier ein Screenshot vom Fehler
![20191025223748_1](https://user-images.githubusercontent.com/49783287/67603303-c3863700-f778-11e9-9e35-b2df84a7c644.jpg)

**Comment by Tensuko** [comment]
> Eben als Drescher und als Abfahrer zum Verkaufen.

#3311 #4286 

Konsole aufmachen und 'cpStopAll' eintippen zum stoppen der CP Fahrer (sollte dann helfen) und IMMER ein logfile anhängen https://github.com/Courseplay/courseplay/wiki

Closed.
