### ISSUE TITLE
Turn maneuver with Xerion dosent work since .313

### ISSUE THREAD

**Issue by Mannelig83** [Courseplay/courseplay#4439]
Hi.
When he turns with a loading wagon and starts driving backwards then it does jackknive.
There is no loggerror.

Which debugs do you Need?
with .311 ist flawless.

greetings
Markus

**Comment by pvaiko** [comment]
which loading wagon?

**Comment by Mannelig83** [comment]
It is a Krone ZX430GD from the Giants Mod Hub.

**Comment by pvaiko** [comment]
It wasn't the Xerion causing this, any towed implement or trailer the Giants helper can't handle was a problem when reversing. Hopefully is fine with 314.
