### ISSUE TITLE
Grubbern mit dem Flexicoil ST820 unsauber

### ISSUE THREAD

**Issue by Nano68x** [Courseplay/courseplay#4440]
Hallo,

seit der Version v6.01.00311 habe ich Probleme das der Grubber ST820 zu spät in der neue Reihe anfängt. Teilweise auch mit einer Sämaschine LS19_Hatzenbichler. Er senkt den Grubber nicht früh genug.
https://youtu.be/QACEMHLr_Ws
[log.txt](https://github.com/Courseplay/courseplay/files/3773818/log.txt)

**Comment by Tensuko** [comment]
Advanced Settings, AI Turn off, raise implement late, lower implement early.
Probiere es aus.

**Comment by Nano68x** [comment]
Funktioniert perfekt. Das Feld wird sauber gegrubbert.
Das 2.Problem mit der Sämaschine und dem DLC Xerion ist auch behoben wie ich gerade gesehen habe. Der ist mit der Horsch Sämaschine MaestroSW2475 nur im Kreis gefahren jetzt zieht er sauber seine Bahn.
Danke !!!

**Comment by Tensuko** [comment]
ok, closed.
