### ISSUE TITLE
Driver crashes into the Harvester when full 311.7

### ISSUE THREAD

**Issue by Vega56** [Courseplay/courseplay#4442]
Hello,

when the Driver is finish with unloading the Harvester, it crashes. He is not waiting until the Position is free.

Log:
https://gist.github.com/Vega56/7673512e21c44b2691abfdf6b7eaf4a2

Video:
https://youtu.be/GRK2Vy9dosI

**Comment by Tensuko** [comment]
#3311 #4286 
Closed.
