### ISSUE TITLE
When turning onto a new row

### ISSUE THREAD

**Issue by NumseBacon** [Courseplay/courseplay#4444]
So when it turns onto a new row, and puts down sower it always wants to drive 1 circle before starting the row

**Comment by Tensuko** [comment]
logfile with debugchannel 12 and 14
Screenshot of course when channels on and he is doing the turn.

**Comment by NumseBacon** [comment]
Debugchannel 12 and 14? what?

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
What actually is this ?
Load mod: FS19_Courseplay_6_300_JJ_mp1 (Version: 6.01.00300) (Hash: 3c16dbbebb5b91dbef49e67949fe7683)

And then you got this too:
2019-10-26 14:25 Error: Running LUA method 'draw'.
2019-10-26 14:25 C:/Users/numse/OneDrive/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay_6_300_JJ_mp1/hud.lua:608: attempt to index local 'selectedField' (a nil value)

**Comment by NumseBacon** [comment]
I did send the log file??

**Comment by NumseBacon** [comment]
I dont know

**Comment by Tensuko** [comment]
not an official version from us.
Not supporting this, stick to our release: https://github.com/Courseplay/courseplay/releases
Closed!
