### ISSUE TITLE
Wanting to circle when starting a new row

### ISSUE THREAD

**Issue by NumseBacon** [Courseplay/courseplay#4445]
So when the sower starts a new row it wants to drive in a circle first
https://gyazo.com/a72147d8dc323fd3541020a232d4fad5

**Comment by Tensuko** [comment]
logfile with actual release v315+ and debugchannel 12 and 14 on ?

**Comment by NumseBacon** [comment]
I have the newest release. Debugchannel 12 anf 14 on. It wont let me copy the log file into pastebin its too big

**Comment by NumseBacon** [comment]
[Nyt tekstdokument (2).txt](https://github.com/Courseplay/courseplay/files/3775013/Nyt.tekstdokument.2.txt)

**Comment by NumseBacon** [comment]
https://gyazo.com/a6322e2b12d553b47c8f9befa2fc02f7
This just happened. It just supposed to bypass an island

**Comment by Tensuko** [comment]
This will be related to #4446 I am pretty sure.
Closing this as duplicate.
