### ISSUE TITLE
Sähmaschine zieht nach Wenden auf dem Feld einen Kreis

### ISSUE THREAD

**Issue by Strawberry93** [Courseplay/courseplay#4446]
Beim Feld Sähen zieht mein Traktor nach dem Wenden nachdem er die Sämaschine abgelassen hat danach einen Kreis und im Mode 14 werden zwei grüne Linien angezeigt.
![2019-10-26 (7)](https://user-images.githubusercontent.com/16910900/67623135-4a431e80-f822-11e9-803a-60039bb876f0.png)
![2019-10-26 (8)](https://user-images.githubusercontent.com/16910900/67623137-4c0ce200-f822-11e9-9bd2-204118c34629.png)

**Comment by Tensuko** [comment]
Debugchannel, nicht Mode.
Logfile mit Debugchannel 12 und 14 bitte.

**Comment by Tensuko** [comment]
Achso und update mal auf V315

**Comment by pvaiko** [comment]
Try with 316.
