### ISSUE TITLE
Düngerspritze Mega 2200 hört früher am Feldrand Auf

### ISSUE THREAD

**Issue by Strawberry93** [Courseplay/courseplay#4447]
Die Spritze Mega 2200 hört ein kleines Stück vorher auf und so bleibt immer ein Rand mit Unkraut oder nicht gedüngt stehen
![2019-10-26 (12)](https://user-images.githubusercontent.com/16910900/67623338-313b6d00-f824-11e9-96e9-ded676d18d80.png)

**Comment by Tensuko** [comment]
Advanced Settings, raise implement auf late stellen, sollte dann gehen.
Wenn nicht mache ich hier wieder auf.
