### ISSUE TITLE
Crash or hang of the game, when using TAB to switch to vehicle.

### ISSUE THREAD

**Issue by LindavK1972** [Courseplay/courseplay#4449]
Hi,

I get a game crash of hang, when using TAB to switxh to a vehicle that is done with field work. So like a tractor seeding, reachers end of the route, i get the notification bar and switch to the vehicle...
And then the game stops. 

[log.txt](https://github.com/Courseplay/courseplay/files/3775246/log.txt)

**Comment by Tensuko** [comment]
Over 2200 Mods ?!
Not going to support that Issue.
I saw several Maps, stuff like Axion and Axion_v2 and so on.
This is ridiculous. Get your Mods sorted and only add the one you rly want and check the versions of your mods, before blind add any.
Your Error is a Callstack but you got a lot of Map Errors and some Mod Errors.
Closed!
