### ISSUE TITLE
It goes to the side when its full?

### ISSUE THREAD

**Issue by NumseBacon** [Courseplay/courseplay#4450]
It backs up and then it drives a little to the right and stops, and it continues on the normal path again when its empty
![billede](https://user-images.githubusercontent.com/49767592/67626349-71ade180-f84a-11e9-99eb-57bfa6cd12a8.png)

**Comment by pvaiko** [comment]
Yes, that's a feature, not a bug. Allows you to unload it without destructing the crop.

**Comment by NumseBacon** [comment]
How do I then disable it

**Comment by pvaiko** [comment]
If you like destructing the crop just disable pathfinding.

**Comment by Gibbanator** [comment]
yes it is a good feature. but the harvester and trailer takes off together (at the same time) after unloading resulting in Crash/Stuck/Unable to move
Have to stop both drivers and untangle them.
If the Harvester stays on line and does not back out than it runs smooth. So I set my trailer to unload at 50% for the harvester never fills and backsout    On Saturday, October 26, 2019, 06:17:33 PM EDT, Peter Vaiko <notifications@github.com> wrote:  
 
 
If you like destructing the crop just disable pathfinding.

**Comment by NumseBacon** [comment]
Yes its annoying when they crash into each other

**Comment by pvaiko** [comment]
Sure it is annoying but that is a problem with the Mode 2, not with the combine and should be fixed there.

**Comment by NumseBacon** [comment]
@pvaiko So since youre here I've got another issue. I just created a empty harvester and transport it to silo course, and when i click start nothing happens, and i cant move anything, not even click esc or tab

**Comment by NumseBacon** [comment]
It an auger wagon behind the tractor
