### ISSUE TITLE
Platinum - Axion 920 lädt nicht ab

### ISSUE THREAD

**Issue by kurtlohnunternehmen** [Courseplay/courseplay#4451]
Der Claas Axion 920 - 960 von der Platinum Edition lädt egal mit welchem Anhänger nicht ab! Die anderen Class Traktoren machen keine Probleme - der 920 - 960 brettert so über den Silo Trigger als wäre er nicht da.

**Comment by Tensuko** [comment]
Welcher Modus ?

**Comment by Tensuko** [comment]
Funktioniert im Mode1.
Was für ein Modus, was für ein Silo, Logfile mit Debugchannel 1 und 2.

**Comment by kurtlohnunternehmen** [comment]
Abtanken und abfahren

**Comment by Tensuko** [comment]
#3311 #4286 
Closed.
