### ISSUE TITLE
Forrage harvesting with new holland 780 forage combine  

### ISSUE THREAD

**Issue by Murtlock** [Courseplay/courseplay#4454]
Hi,
when i mow grass with the newholland 780 or krone big x the combine and tractor unloading it cannot complete the turn at the end of headland.They keep bumping in each other;its not like before when the combine reaches the end of the the headland turn ,turn and drive forward to the next way point.The tractor then turns away turns after the combine has turned and the drives up a couple of meters then reverse back to the combine,it does not do that anymore instead it follows the combine and get stuck in the turn
thanks for tour good work
regards

**Comment by Tensuko** [comment]
#3311 #4286 
Closed.
