### ISSUE TITLE
Fehler ab der 6.01.00311

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#4455]
Saatmaschiene läst Ecken stehen
![Ecken](https://user-images.githubusercontent.com/48583507/67633052-5aeba700-f8ab-11e9-89c8-60322ae92918.png)

Drescher muss Abfahrer rufen! sonst kommt kein Abfahrer
Das alles ab v6.01.00312
Mit v6.01.00311 war alles noch in Ordnung

**Comment by Tensuko** [comment]
Das sind 2 verschiedene Sachen....
Saatmaschine will ich den Kurs sehen, die Situation und ein logfile mit debugchannel 12 und 14 aber auf version V316+ !

Das andere is noch immer #3311 #4286 !!

**Comment by Lustiger-Hubi** [comment]
version V316+ werde ich testen
