### ISSUE TITLE
Question/Possible Issue

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#4458]
Is CP only capable of avoiding obstacles while doing field work? I ask because my appended refill courses sometimes drive directly into objects on the edge of fields. Also the tractor will sometimes turn to the right after filling from the combine and strike it.

**Comment by Tensuko** [comment]
1st Issue is the problem of how you record the course or better say where at the field you start it.
The other one is #3311 #4286 
What we can do about better colli detection we will see, but not on the to do list right now...
