### ISSUE TITLE
Automatischer Seitenwechsel funktioniert nicht mehr

### ISSUE THREAD

**Issue by Hartmut88** [Courseplay/courseplay#4459]
Hallo Leute,

seit kurzem habe ich festgestellt, dass der automatische Seitenwechsel bei meinen Abfahrern nicht mehr funktioniert.
Also meine Abfahrer sind auf "kombiniert" eingestellt und fahren neben dem Häcksler. Wenn das Feld zu ende ist und der Häcksler wendet, sollten auch die Abfahrer ihre Seite wechseln oder? Dies funktionierte auch in den letzten Versionen.. nun nicht mehr.

Außerdem wechselt auch der Häcksler, eingestellt auf "Feldarbeit" die Seiten nicht mehr (bei eingestelltem seitl. Versatz). Dies ging ebenfalls in den letzten Versionen.

Hinzu kommt noch, mein Häcksler (E-281) hat nur 3,10m Arbeitsbreite. Dies bedeutet, die Abfahrer müssen auch ziemlich dicht an den Häcksler kommen. Dadurch gibt es ebenfalls beim wenden Probleme. Die Abfahrer bleiben zu dicht am Häcksler stehen und blockieren diesen dann beim wenden. Bei größeren Arbeitsbreiten hatte ich dieses Problem nicht. Vielleicht könnte man ja am Wendemanöver des Abfahrers ein wenig was ändern, damit dieser weiter weg fährt und dem Häcksler mehr Platz zum wenden gibt/ ermöglicht.

**Comment by Tensuko** [comment]
#3311 #4286 
Closed.
