### ISSUE TITLE
Bypass islands dont work

### ISSUE THREAD

**Issue by NumseBacon** [Courseplay/courseplay#4461]
I trie both with the simple and the circle none of them did anything. It just drives into the tree
![billede](https://user-images.githubusercontent.com/49767592/67686274-bfcffb80-f996-11e9-8f39-03c268215534.png)

**Comment by Tensuko** [comment]
This looks very faimilar, I think the Problem here was, that the Island was to smal in the Field Data.
Post your Fielddefinitions like written here:
https://github.com/Courseplay/courseplay/wiki

**Comment by NumseBacon** [comment]
Working width 15m
https://gyazo.com/e8029b6d06695189a7687583ae2151f3
[cpfields.txt](https://github.com/Courseplay/courseplay/files/3779511/cpfields.txt)

**Comment by Tensuko** [comment]
How to Post Your Field Definitions

To troubleshoot fieldwork course generator issues the devs may need your field definitions.

    Make sure you have the developer console enabled (google it, or see this video)
    Activate the console (tilde/backtick key twice above the TAB) and type in cpSaveAllFields
    Courseplay writes a file named cpFields.xml to the CoursePlay_Courses/ folder (in the game folder). Post this file in the issue and tell us course generator settings including work width and the number of the field you are having problems with.

**Comment by NumseBacon** [comment]
[cpfields.txt](https://github.com/Courseplay/courseplay/files/3779574/cpfields.txt)

**Comment by NumseBacon** [comment]
oh 1 field because i only have 1 field

**Comment by pvaiko** [comment]
Field definitions won't help in this case as the island information is not contained in there.

What would help is a debug log with channel 7. And to let us know which map this is ...

**Comment by Tensuko** [comment]
Sry that was my bad... Mixed that up....

**Comment by NumseBacon** [comment]
I dont know how to debug log but the map is horsch Agrovation. The bypass islands has worked before but it just stopped working

**Comment by Tensuko** [comment]
HUD Settings, click on the white 7 (it becomes green) then generate the course, then  post the logfile.

**Comment by NumseBacon** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3779720/log.txt)

**Comment by pvaiko** [comment]
Based on this log you either don't have the island bypass turned on or CP does not see an island on that field.

**Comment by pvaiko** [comment]
Which was the last CP version it worked with? Is it still working with that version?

And in the meanwhile you can post your cultivator_density.gdm file from your savegame.

**Comment by NumseBacon** [comment]
Im pretty sure it was 315 and I almost never use cultivator but ok

https://www.mediafire.com/file/9dzyukwkz572rdn/cultivator_density.gdm/file

**Comment by NumseBacon** [comment]
and im currently using 315

**Comment by NumseBacon** [comment]
Now it doesnt work with any versions

**Comment by NumseBacon** [comment]
I actually think it stopped working after i reinstalled fs19

**Comment by Tensuko** [comment]
I hightly doubt that the reinstall for fs19 is the reason....

**Comment by NumseBacon** [comment]
so what do i do? :(

**Comment by Tensuko** [comment]
I haven't seen a full logfile from you yet.

**Comment by NumseBacon** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3780199/log.txt)

**Comment by pvaiko** [comment]
Something must have happened on that map eradicating those islands, this is the original:
![image](https://user-images.githubusercontent.com/2379521/67713286-88138480-f993-11e9-8477-03b9ee03a7bc.png)

and this is yours (note the white dots representing the islands are disappeared):
![image](https://user-images.githubusercontent.com/2379521/67713239-716d2d80-f993-11e9-91c3-fcbdd3c5a5a2.png)

There seem to be plenty of evidence that this isn't a CP problem, closing until proved otherwise.

**Comment by NumseBacon** [comment]
Weird i even tried reinstalling the map. My only fix was to remove the tree which took some time and money
