### ISSUE TITLE
Mode 2: Truck crosses in front of harvester when leaving for unloading in silo

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4464]
[log.txt](https://github.com/Courseplay/courseplay/files/3780403/log.txt)
In mode 2, a combine stops to unload to a truck. 
When the truck is full, it will not wait for the combine to return to its last point and ignoring it, will cross in front of it.
But at the same time, the combine is trying to go back to its last point to continue to harvest, causing the collision.

**Comment by Tensuko** [comment]
You are not new on GitHub and I am sure I aready closed an Issue with Mode2 already from you.
#3311 #4286 Just read those Issues....
Closed.

**Comment by Gibbanator** [comment]
One of the major problems with getting a field to complete on its own without having to keep returning to the field to fix manually. 
CP has a way to go yet to do what it is meant to do.
