### ISSUE TITLE
Seeder just drives to the side.

### ISSUE THREAD

**Issue by NumseBacon** [Courseplay/courseplay#4465]
I use version 315.

https://www.mediafire.com/file/l8bqcks1oh8ev1x/2019-10-28_21-43-46.mkv/file
Please download the file and watch the video so you can see what happens

**Comment by Tensuko** [comment]
Offset ? Convoy ? I can see 2/2 down in your HUD ....

**Comment by NumseBacon** [comment]
Yes convey. Lane offset was Right but new its Left

**Comment by Tensuko** [comment]
Lane switch symetric and asymetric, try out what you like, I don't see an Issue here.....

**Comment by NumseBacon** [comment]
It just turns and keeps driving. It isnt switching lane in the video it just turns and keeps driving the other way onto another field, and the other seeder didnt do it

**Comment by Tensuko** [comment]
Why not use 317 ? In 316 there are some fix for those Tractors with tools....
https://github.com/Courseplay/courseplay/releases

**Comment by NumseBacon** [comment]
I doubt it will change anythig but ok

**Comment by Tensuko** [comment]
Is this still Valid with V330+ ?

**Comment by Tensuko** [comment]
Closed due to inactivity.
Try again with V336+, makew new Issue with needed informations...
