### ISSUE TITLE
need help for working width tool

### ISSUE THREAD

**Issue by betrox007** [Courseplay/courseplay#4467]
some body can help?
i'm using cultiplowPlatinum8m as listed at the shop its wide 8 meter, but when generating course at field its wide only 7,8 m in CP hud, so i adjust it manualy and then generate course at 8 meter wide each line
but then again after run the CP, at the Hud, working width it's show 7,8 meter again, not 8 meter as course generated, i try to to adjust it manualy, by hold down LCTRL+Mouseclick at the hud, but increment of width 1 meter (7,8 m while click + at hud its increase 8,8 and so on ) can't adjust its number behind coma, can someone tell me how to adjust it like 7,8 to 7,9 then 8,0 and so on?

Thanks

![fsScreen_2019_10_29_09_46_53](https://user-images.githubusercontent.com/56646850/67734371-7b466d80-fa33-11e9-8134-983cc757d09a.png)
![fsScreen_2019_10_29_09_59_23](https://user-images.githubusercontent.com/56646850/67734404-9618e200-fa33-11e9-93d2-f8802ead9575.png)
![fsScreen_2019_10_29_10_00_16](https://user-images.githubusercontent.com/56646850/67734457-ba74be80-fa33-11e9-84df-d41097b9d45e.png)
![fsScreen_2019_10_29_10_00_36](https://user-images.githubusercontent.com/56646850/67734486-cbbdcb00-fa33-11e9-84f9-c232578cb5f7.png)
![fsScreen_2019_10_29_10_01_41](https://user-images.githubusercontent.com/56646850/67734501-d710f680-fa33-11e9-941a-f7d95e5832ae.png)
[log.txt](https://github.com/Courseplay/courseplay/files/3781526/log.txt)

**Comment by Tensuko** [comment]
Hold ctrl when scroll up. It should do 0,1 steps.
The width comes from tool, nothing we can do about it...

**Comment by betrox007** [comment]
alrigth its work, but its not direcly scroll by 0,1 see this video [https://youtu.be/daDk7LCrguQ](url)
thank's
