### ISSUE TITLE
Potato Harvester Pipe in fruit issue

### ISSUE THREAD

**Issue by Tadeloach** [Courseplay/courseplay#4469]
Hello, I am using Autodrive to unload combines.  My issue is the Terra Potato Harvester backs the wrong way because the pipe is on the reverse side compared to other combines.  This always leaves me with the unloader parked in the fruit if unloaded with pipe towards the fruit.  Is there anyway to make the potato harvester reverse the correct way away from the fruit?
![PH1](https://user-images.githubusercontent.com/56048034/67779063-20f8dd00-fa32-11e9-881c-b3a011f412e1.png)
![PH2](https://user-images.githubusercontent.com/56048034/67779083-26562780-fa32-11e9-9d72-8e3586fda27c.png)

**Comment by pvaiko** [comment]
Should work fine with 320.

**Comment by Tadeloach** [comment]
I haven't played in awhile, but using version 6.01.00391 This is happening again.
![image](https://user-images.githubusercontent.com/56048034/75997265-b74b7c80-5ec4-11ea-9723-a28c94504136.png)
