### ISSUE TITLE
Game Freeze

### ISSUE THREAD

**Issue by Gus321** [Courseplay/courseplay#4470]
My game freezes when I use combi mode. Is there a way to make it unfreeze or for combi mode to work properly? I have seen others use it just fine.

**Comment by Woife1** [comment]
Do you have a waiting point or a trigger in your route? (you mean Mode 2? 2. Mode to choose)

And this Mode is still underconstruction

**Comment by Gus321** [comment]
I have an unload point. Yes mode 2

**Comment by Woife1** [comment]
Post your log or we could only say wait for rebuilded Mode 2

**Comment by Tensuko** [comment]
No need any log, couse #3311 #4286 
Closed.
