### ISSUE TITLE
Offset while plowing is constantly changing by itself

### ISSUE THREAD

**Issue by blaz62746** [Courseplay/courseplay#4471]
I started plowing the field after I generated the course in fieldwork mode. After I press "Start course", tractor starts zig-zagging and I can see the offset being changed very frequently. I tried on official map and only with courseplay enabled and the problem still exists.

**Comment by pvaiko** [comment]
Offset for plows is adjusted automatically. I haven't seen this behavior, what tractor/plow are you using?

**Comment by blaz62746** [comment]
I was using Big Bud 747 with SPSL 9 plow. I thought Big Bud is causing problems but then I tried Fendt 1000 Vario with Salford 8312 plow and it does little zig-zagging (less than Big Bud with SPSL 9) but within 0.3 meters (offset changes from 0.4 - 0.7 meters to the right).

**Comment by pvaiko** [comment]
Can you reproduce this with no mod other than CP on standard map with standard equipment? Do you have any mods installed which is changing the driving behavior?

**Comment by blaz62746** [comment]
I can. Can you tell me which debug channels I should turn on?

**Comment by pvaiko** [comment]
Ok, I see it happening too, interestingly only after the first 180 turn.

**Comment by blaz62746** [comment]
For me, it's doing it right from the start. If I can help somehow, I'll be glad.

**Comment by pvaiko** [comment]
Thanks, there's nothing you can do at the moment, I need to come up with a better solution, I think I know what to do.
