### ISSUE TITLE
How to make a multi steps refill (seeder + fertilizer)?

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4473]
I'm using this combination for seeder/fertilizer:
![image](https://user-images.githubusercontent.com/11199752/67815999-5380f500-fa87-11e9-9505-0b8415222948.png)
![image](https://user-images.githubusercontent.com/11199752/67816007-58de3f80-fa87-11e9-9458-b6d6aab86717.png)

The fist has 2 bins (seed/fertilizer) and the second is an additional bin for seeds.
When I create a route to refill, it's just making one-stop (fertilizer):
![image](https://user-images.githubusercontent.com/11199752/67816102-a9ee3380-fa87-11e9-8ef1-39e94523e95d.png)

In this case, the would need to make 3 stops: 

1. Refill the front of the tractor (FH 2200) with seeds
2. Refill the rear (Tempo L16) with seeds
3. Refill the rear (Tempo L16) with solid fertilizer

How can I automate this process?

**Comment by Tensuko** [comment]
I don't see how you made the course so I can't tell you if you made a mistake or if I have to check if it actually works.
Normaly, Fieldcourse + Add a Course that passes all refillstations that you need (the trigger must be hit ofc).

**Comment by rogeriodec** [comment]
I'm using mode 5, but it seems it's not the correct way to have multiple stops in a unique course...

**Comment by Tensuko** [comment]
Mode5 is A B transition... Nothing can be filled up there it is just a drive from A to B ....

**Comment by rogeriodec** [comment]
Ok, could you please tell me how can I do this?

**Comment by rogeriodec** [comment]
> add the refill-course to a fieldcourse or use the mode fill at startpoint (i think mode 1)

Here's my tractor ready to start to seed in field 7.
![image](https://user-images.githubusercontent.com/11199752/68044338-e30beb00-fcb5-11e9-8b09-64fdff9394a8.png)

Mode 1 isn't available.
How can I automate the refill of seeder + fertilizer process?

**Comment by Tensuko** [comment]
It

**Comment by Tensuko** [comment]
Closed due to inactivity.
To make it clear again:
Create Fieldcourse -> save it
Create refill router -> save it
Load Field Course, Load refill router with the +Folder
Run Mode4 Seeding and its fine.
