### ISSUE TITLE
Standbild bei Modus 8 

### ISSUE THREAD

**Issue by Sinonplayz253** [Courseplay/courseplay#4474]
Ab der Version 293 (mir ist der fehler erst vor ein paar tagen aufgefallen) ist bei mir Standbild, wenn der Abfahrer mit Modus 8 (Farmsilo-Befüllung: Gülle oder Gärreste) auf ein Wartepunkt zufährt und dabei erscheint dieser fehler: Error: Running LUA method 'update'.
                                   Courseplay_6_01_00293/AIDriver.lua:1125: attempt to call method 'getTipState' (a nil value).

Und bei Modus 2, wenn der Abfahrer zum silo fährt oder wo anders hin, bremst er bei den kurven nicht ab sondern fährt mit voller geschwindigkeit in die kurve. Das ist bei den anderen Modis nicht. Muss ich irgendwas einstellen?

**Comment by Tensuko** [comment]
Du beschreibst hier 2 verschiedene Dinge....

Zum ersten Problem: Duplicate of #4196

Zum zweiten Problem: #3311 #4286 

Und nächstes mal bei solchen Sachen direkt ein logfile anhängen (drag and drop in die Kommentbarbox).

Closed.
