### ISSUE TITLE
Sugar Beets harvester unload lead to loop of errors

### ISSUE THREAD

**Issue by TyKonKet** [Courseplay/courseplay#4475]
Hello, I'm trying to use the Terra Variant 585 ( from the Holmer DLC ) to unload my beets harvester and then unload in a heap on the ground.
This is my setup:
![image](https://user-images.githubusercontent.com/7534621/67851517-edd64c80-fb0a-11e9-8ede-87a6d7f25625.png)
![image](https://user-images.githubusercontent.com/7534621/67851432-bff10800-fb0a-11e9-8678-73e9a2d307eb.png)

When I start the driver for the first time I get a loop of this error:
`Error: Running LUA method 'update'.`
`Courseplay_6_01_00317/mode3.lua:24: attempt to perform arithmetic on a nil value`

Now if I stop the driver the error stops, but if I start the driver again a new error adds to the loop and HUDs disappears:
`Error: Running LUA method 'draw'.`
`Courseplay_6_01_00317/AIDriver.lua:687: attempt to index field 'course' (a nil value)`

**Comment by Tensuko** [comment]
#3311 #4286 
Closed.
