### ISSUE TITLE
improvement: call waiting for unload At the End of the route

### ISSUE THREAD

**Issue by geo-luchs** [Courseplay/courseplay#4476]
Hello

I'm using cp in combination with AD.
When CP reached the end of the Route, AD will not start automatically.

I asked Stephan, and HE told me, AD is normally only waiting that CP gives the Information for unload.
I Think cp is Doing it only when fill Level is reached.

Can you call it at the end of the route,  too?

vehicle.cp.driver:isWaitingForUnload()

**Comment by pvaiko** [comment]
Try with 320, I have not tested it with AutoDrive but should be fine. 

Close this issue if works.

**Comment by geo-luchs** [comment]
Hi @pvaiko   Thanks for this quick solution.
I've tested it, and it looks fine.
Harvester is first calling for unload. AD driver is coming, unloading, then finally CP is writing : end of route is reached.
