### ISSUE TITLE
CP fail to follow course with two harvesters on same field.

### ISSUE THREAD

**Issue by SteelRodent** [Courseplay/courseplay#4477]
This appears to be somewhat random, but when running with two JD cotton harvesters (from the DLC) or double Lexion combines (the new ones) in convoy, I'm having a recurring issue where the one machine won't follow the course - meaning the one will follow the course perfectly while the other will fail some of the turns and run off in the wrong direction.

![20191030175341_1](https://user-images.githubusercontent.com/20990941/67881364-ac609400-fb40-11e9-943b-0bfae2e61012.jpg)

The PPC shows the correct turn path for the combine, but for some reason it decided to run off in the opposite direction. It did this twice before I gave up.

I've yet to have it happen with the original New Holland CR10.90 or Agco combines running together. The JD cotton harvesters used to work fine with CP, but last I used them was with CP295 or something like that. 

Course generation looks normal

![20191030175432_1](https://user-images.githubusercontent.com/20990941/67881682-3d376f80-fb41-11e9-9216-a67c3fa35d0e.jpg)

This is on Ravenport. The cotton harvesters I only use on Lapacho.

I turned on every debug channel that sounded relevant to pathfinding, but sorry if I missed one.
[log.txt on gist](https://gist.github.com/SteelRodent/dc0001a1c23a6357ead7ce595419cc8b)

EDIT: I've run with dual Xerion cultivating/plowing and not had any issue like this. Only run into this issue with these DLC harvesters,

**Comment by pvaiko** [comment]
Channel 12 would be interesting but it is maybe easier if you post a save game and courses set up

**Comment by pvaiko** [comment]
Loaded your savegame, tried, could not reproduce it. Can't even bring up the HUD for one of the combines (the one on the left in your screenshot), the other one turns just fine. 

Debug 12 and 14 is what I need, a video would be the best, but a log may help (you did not have 12 on). Best of course would be a savegame which can reliably reproduce this.

**Comment by Dajoor** [comment]
I have seen this happening with up to 6 harvesters (any type any header). Commonly the right side(s) seem to have this issue, and sometimes the left side(s). Never seen the center machine act weird. Most commonly this happens on headlands, or with island evasion. It looks like the offset calculation has a bug where one of the point co-ords gets set off the map. If it happens I set debug view on then drive manually a few points past, then let the CP driver take over again.

**Comment by Tensuko** [comment]
Logfile with channel 12 and 14 ...

**Comment by Tensuko** [comment]
Closed due to inactivity.
Reopen if you got the log with channel 12 and 14 active and for best, a video of the Issue.
