### ISSUE TITLE
Using curve line speed limit when driving in a straight line

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4479]
Why sometimes the combine is driving limited to the curve speed limit (10 Km/h) even when it's moving to a new point?

![image](https://user-images.githubusercontent.com/11199752/67907379-775f3c00-fb56-11e9-8d03-9388d2309703.png)

**Comment by Woife1** [comment]
The driver lowering his speed some points before he get to a curve and use this speed for turn maneuver

**Comment by pvaiko** [comment]
Because it is executing a turn maneuver and during turn maneuvers the maximum speed is the 'turn speed' (not curve speed in English, BTW).

**Comment by rogeriodec** [comment]
As you can see in the image, there are no turn maneuvers... 
Around 500 meters straight line...
The harvester is traveling a straight path from one point of the field to the other to continue harvesting.
No curves, no crop, just a straight line of displacement to resume harvesting at the new point ...

**Comment by rogeriodec** [comment]
@Tensuko You love to close issues, even without this being resolved, huh?

**Comment by Woife1** [comment]
it looks like he is on a turn maneuver when he isn't he has an other bug or a big offset and drives in the false direction

**Comment by Tensuko** [comment]
@rogeriodec 
provide a proper Issue report with logfile and more details on what happens there, then we can do more about it.
I only see a Combine next to a course and the arrows looks like pointing in a different direction.

https://github.com/Courseplay/courseplay/wiki

**Comment by pvaiko** [comment]
> You love to close issues, even without this being resolved, huh?

@rogeriodec  I'd like to remind you that this is a community project, developers have families and jobs and do this in their spare time. They pick whatever they prefer to work on, depending on how much time they want to spend on CP.

And since their time is limited, they may simply decide not to work an in issue and just close it.

**Comment by pvaiko** [comment]
@rogeriodec and by the way, just because the combine is driving in a straight line it is still a f@!% turn maneuver.

**Comment by Tensuko** [comment]
Conversation Closed.
If you face a real Issue, proper screenshot and logfile with debugchannel 9, 12 and 14 for turn and drive informations.
