### ISSUE TITLE
abfahrer fährt nach dem abtanken nicht zurück 

### ISSUE THREAD

**Issue by iceman234de** [Courseplay/courseplay#4481]
Hallo, folgendes wenn der Mähdrescher am Ende seiner Bahn ist und zum Wenden ansetzt , dabei aber vom Helfer abgetankt wird , fährt der Helfer nicht mehr rückwärts weg sondern bleibt stehen , und der Drescher meldet dann " steckt im Verkehr fest " . Erst wenn ich den abfahren manuell weg fahre fährt der Drescher weiter . In Version 103 ging das noch , bei Version 117 nicht mehr . 

Grus iceman

**Comment by Tensuko** [comment]
#3311  #4286 
Closed.
