### ISSUE TITLE
 Trebbia scaricara on the sideline

### ISSUE THREAD

**Issue by ice81rm** [Courseplay/courseplay#4482]
Hello guys!!
Excuse the disturbance .. do we know anything about when the modality that allows us to let the thresher (or the potato lever ..) go to be unloaded on the trailer?
Thanks Fabio, Rome

**Comment by Tensuko** [comment]
We don't answer 'when' questions. There is an Idea for that, but WHEN @pvaiko will be on it, is a question of motivation and especialy time!
Closed.
