### ISSUE TITLE
UI Ladegut und Durchläufe liegen übereinander

### ISSUE THREAD

**Issue by VatriXxX** [Courseplay/courseplay#4483]
Hallo,
nutze Courseplay jetzt seit einigen Tagen und mir ist beim Abfahren aufgefallen, dass das was er laden soll mit der % Angabe und die Durchläufe übereinander liegen und man es schlecht erkennen kann.
Hier zur Veranschaulichung:
![grafik](https://user-images.githubusercontent.com/2685763/67943920-715f6e80-fbdb-11e9-8f43-c397fd0ee638.png)

**Comment by Tensuko** [comment]
Danke für die Info, wird aber dauern, bis ein fix dafür kommt, momentan ist wichtigeres dran :)

**Comment by VatriXxX** [comment]
Ja alles gut, wollte das nur mitteilen, falls es nicht schon bekannt ist.

**Comment by Tensuko** [comment]
Wird sich wohl bald erledigt haben.
