### ISSUE TITLE
Gerät anheben und absenken Einstellung speichert nicht

### ISSUE THREAD

**Issue by VatriXxX** [Courseplay/courseplay#4484]
Aloha,
mir ist wieder eine Sache aufgefallen die nicht so sein sollte.
Wenn ich in den Erweiterten Einstellungen das anheben und absenken auf spät bzw. früh einstelle behält er das noch, bis ich das Spiel neustarte.
![grafik](https://user-images.githubusercontent.com/2685763/67947181-5d1f6f80-fbe3-11e9-898d-facaaa6e5c47.png)

Nachdem ich das Spiel neugestartet habe, ist die wieder auf der standard Einstellung:
![grafik](https://user-images.githubusercontent.com/2685763/67947158-4c6ef980-fbe3-11e9-8aaa-9368ae8e0dbd.png)

Kann es sein, das er die nicht richtig abspeichert in den Settings? Sondern nur temporär?

**Comment by Tensuko** [comment]
Naja das könnte auch problematisch werden, denn je nach tool was du anhängst, kann es ja eine andere Einstellung benötigen, aber die Settings werden ja beim Traktor gespeichert....
Mal sehen was machbar ist.

**Comment by pvaiko** [comment]
Das müsste mit dem Savegame gespeichert sein, ist aber Fahrzeugspezifisch, bist du sicher dass du das Ok taste gedrückt hast nach der Änderung und auf dem selben Fahrzeug guckst?

Kannst auch in savegame in vehicles.xml prüfen, z.B.:
`
            <implementRaiseTime value="1"/>
            <implementLowerTime value="2"/>
`

**Comment by VatriXxX** [comment]
Ah okay, danke, das wusste ich nicht.
Ich dachte das ist eine generelle Einstellung.

Dann wäre das geklärt.
