### ISSUE TITLE
Rescan field changes without restarting FS19?

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4485]
When I expand or decreased the boundaries of a field (with a plow or a Meadow Roller Vario), CP can't understand these changes until I restart FS19.
Is it possible to rescan the fields without restarting the game?

**Comment by pvaiko** [comment]
Have you tried the scan current field edge function?

**Comment by rogeriodec** [comment]
Yes. 
This even shows the new edges of the field. But when calculating a new course inside the field, the old edges still prevail. Only by restarting FS19 to be able to create a new course within the new field dimensions.

**Comment by Merrlin** [comment]
After you have scaned the field Edges you have to save the edge course again. The function is one line below the scan field Edges button

**Comment by rogeriodec** [comment]
> After you have scaned the field Edges you have to save the edge course again. The function is one line below the scan field Edges button

Thanks for your help but I didn't find what you're saying.
To better understand, here's an example of a current field course:
![image](https://user-images.githubusercontent.com/11199752/68042294-4ba49900-fcb1-11e9-9ad5-106c15914343.png)
Then, the same field corner reshaped:
![image](https://user-images.githubusercontent.com/11199752/68042333-64ad4a00-fcb1-11e9-9623-dbc4f3788350.png)
Now I click this option to rescan the field:
![image](https://user-images.githubusercontent.com/11199752/68042367-7db5fb00-fcb1-11e9-87f2-4a20a1a00ceb.png)
This shows me the correct new border (and the label changes to "number of field's border":
![image](https://user-images.githubusercontent.com/11199752/68042450-ae963000-fcb1-11e9-9e9a-da4eb1d85683.png)
Now I create a new course:
![image](https://user-images.githubusercontent.com/11199752/68042517-d71e2a00-fcb1-11e9-8655-7c99d929d6ac.png)
But, as you can see, the borders used to calc de course are still the older one:
![image](https://user-images.githubusercontent.com/11199752/68042573-02a11480-fcb2-11e9-872b-52f4521b635a.png)

**Comment by SirStranger1989** [comment]
Try the calculate field edge before you create a course.
Then save it either over the existing field or, if you for some reason want
to keep that old field calculation , as a new field number.

Op vr 1 nov. 2019 18:15 schreef Rogério Dec <notifications@github.com>:

**Comment by Tensuko** [comment]
Scan Field, then see the blue lines, then you got to place your new Field Border to a new Number (what ever Number you like) then it is shown as 'X (user)' in course generator. else he takes the old Border.

**Comment by rogeriodec** [comment]
Thanks, @Tensuko, also some screenshots would be more didactic, once there are term variations in different languages and sometimes it is difficult to understand just for words like 'x (user)'.

Here one reshaped field, then I click on the option to recalculate the current border:
![image](https://user-images.githubusercontent.com/11199752/68058849-190e9680-fcd9-11e9-99d4-49f177492b41.png)

Then I get the blue lines new the option "number of field's border", then I click on "+":
![image](https://user-images.githubusercontent.com/11199752/68059020-bf5a9c00-fcd9-11e9-8c08-f9580b75c7a7.png)

Then I get this new option to "Rewrite border of field 1 on the list":
![image](https://user-images.githubusercontent.com/11199752/68059091-f466ee80-fcd9-11e9-9a54-a0f8eb139c8c.png)

Then I generate the course, but the old border is still there:
![image](https://user-images.githubusercontent.com/11199752/68059155-27a97d80-fcda-11e9-9372-763e256e3fd6.png)

**Comment by rogeriodec** [comment]
Nevermind, I got it
![image](https://user-images.githubusercontent.com/11199752/68059418-35133780-fcdb-11e9-8bfa-a7aa21dd2feb.png)

**Comment by Tensuko** [comment]
Good....
Closed.
