### ISSUE TITLE
Problems with bale stackers

### ISSUE THREAD

**Issue by krambc** [Courseplay/courseplay#4488]
Hello everyone.
First of all congratulate you for the good work done with the Courseplay.
Excuse me for my English (I used google translator).

I have been reading the different issues on this topic and have not found an answer.

When I create a course to pick up the bales and stack them, i set an unload point where i want the bales to be stack.

When trying it, I find that after unloading the bales the autostacker does not fold before returning to the fieldwork.

Should I set a wait point?

I have tried it with the arcusin and with several mods for round bales.

https://youtu.be/LbCS9OS37RQ

Thanks for your help!

**Comment by pvaiko** [comment]
Need a full log with debug channel 14.

**Comment by krambc** [comment]
Hi. I attach the log.
[log.txt](https://github.com/Courseplay/courseplay/files/3799370/log.txt)

https://youtu.be/zuRdyVUbFR0

**Comment by lcc1211** [comment]
I think something is wrong with this file. I downloaded it and moved it into my mods folder. I started up the game, and when I look for it in mods to activate, it isn't showing. I shut down the game, went to my mods folder and it is there. I downloaded it a 2nd time and replaced the file in my mods folder and started up the game again, but it still doesn't recognize it.

**Comment by lcc1211** [comment]
[courseplay-6.01.00341.zip](https://github.com/Courseplay/courseplay/files/3876895/courseplay-6.01.00341.zip)
