### ISSUE TITLE
Plough offset sideways does not change the side (right to left does not work)

### ISSUE THREAD

**Issue by Scaracuila** [Courseplay/courseplay#4492]
Hi dev Team,

since version ...319 I have the problem, that the offset on the side of the plough is permanently set to the right and I can't change it manually anymore, it is always set to 0.7m (right) and doesn't plough the whole field but leaves gaps! With version ...318 everything runs without problems!

Map: Somewhere in Thuringia V2 (Irgendwo in Thüringen V2)
Actual Giants Patch

Attached some pictures...

Which log of which version do you need and which debug channels should I activate?

Here three pics with current Version ...321

![CP 1 0021](https://user-images.githubusercontent.com/34663971/68030558-0df83e00-fcba-11e9-8887-ff52d3a5d839.png)

![CP 2 0021](https://user-images.githubusercontent.com/34663971/68030585-1c465a00-fcba-11e9-9ff0-f69a3c435a99.png)

![CP 3 0021](https://user-images.githubusercontent.com/34663971/68030626-2ff1c080-fcba-11e9-8bca-fe9179605e08.png)

And here two pics with Version ...318

![CP 1 0018](https://user-images.githubusercontent.com/34663971/68030637-354f0b00-fcba-11e9-92c1-f0bec6cb1a47.png)

![CP 2 0018](https://user-images.githubusercontent.com/34663971/68030654-3ed87300-fcba-11e9-8baf-f61b284c7e70.png)

**Comment by pvaiko** [comment]
Which plough is this?

**Comment by pvaiko** [comment]
And a log with debug channel 14.

**Comment by Scaracuila** [comment]
Hi,

the plough is https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=143248&title=fs2019

here is the Log with version ...318

[log 318.txt](https://github.com/Courseplay/courseplay/files/3798509/log.318.txt)

and here is the log with version ...321

[log 321.txt](https://github.com/Courseplay/courseplay/files/3798521/log.321.txt)

thanks

**Comment by pvaiko** [comment]
Thanks, I see, this is a plow where the left/right AI markers are rotated with the plow. Will fix.

**Comment by pvaiko** [comment]
Should work fine with 323

**Comment by Scaracuila** [comment]
Thank you very much, I will test it immediately!
