### ISSUE TITLE
CP crashes when mowing with Big M 500

### ISSUE THREAD

**Issue by ghost** [Courseplay/courseplay#4493]
mod: https://www.modhoster.de/mods/krone-big-m-500--6
cp-version: 6.01.00319
map NF-Marsch 2.4
log-line 5470

When I start the Big M500 on field 20/33 I can´t exit the Big M with "E" or tab. Also I can´t stop CP with the console-command "cpStopAll" (line 6508). all other vehicles work with cp.
[log.txt](https://github.com/Courseplay/courseplay/files/3798288/log.txt)

**Comment by pvaiko** [comment]
That's not even an error from Courseplay. That mod seems to have some issues. Closing.
