### ISSUE TITLE
Can't see Courseplay window

### ISSUE THREAD

**Issue by Interaction1** [Courseplay/courseplay#4495]
Hey Guys!
Since the Platinum Update i hear the sound from CP when i open it, but can't see the window. I tryed it with three differend versions, but its not working. I have no new mods since the update...
Hope for help and Thx if u can help

**Comment by Tensuko** [comment]
Logfile ?!

**Comment by Interaction1** [comment]
https://gist.github.com/Interaction1/263d6ef441c6b58d580bfc158cc9a141

**Comment by Tensuko** [comment]
Error: Invalid mod name 'FS19_courseplay-master'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
you got 2 times CP in your mod folder.
Get new one here: https://github.com/Courseplay/courseplay/releases
And a tip from me: ONLY Rename it to FS19_Courseplay always so you don't have a problem when you download new one.

**Comment by Tensuko** [comment]
Oh and btw....

Error: Failed to open xml file 'C:/Users/Fabio/Documents/My Games/FarmingSimulator2019/mods/Krone_BigX/modDesc.xml'.
Load mod: Krone_BigX
Error: Missing descVersion attribute in mod Krone_BigX
Load mod: lizardFloodLightTrailer_V2_Edit_By_DBP (Version: 2.0.0.0) (Hash: 5ce8eefc055921824d7c9c2d69c2fa4e)
Load mod: LS19_Zweisternhof_GP (Version: 1.0.0.1) (Hash: 26ca9efccb61d3b7af7ed011a3fa4e8f)
Load mod: MTLModdingTeam_Snuefelstueck (Version: 5.0) (Hash: a4c8faa0631a8553780e9e6c37d9244f)
Load mod: MultipleMissions (Version: 1.0) (Hash: bff1b1841a8ed254777270fa35fb7520)
Load mod: MW_PLACEABLE_HOF (Version: 1.3) (Hash: e443fa1ab7b15e51b873aee87ceec87b)
Load mod: MW_PLACEABLE_HOF_USA (Version: 1.0) (Hash: 2d0628917a48fa1767d4f861d20a42f2)
Error: Failed to open xml file 'C:/Users/Fabio/Documents/My Games/FarmingSimulator2019/mods/Never_Land_Mods_ENTPACKEN/modDesc.xml'.
Load mod: Never_Land_Mods_ENTPACKEN (Hash: bbc0267d32d5edab65302be65ed2ba11)
Error: Missing descVersion attribute in mod Never_Land_Mods_ENTPACKEN
Load mod: podnoszenie (Version: 1.0) (Hash: 06a75fc4de6988a6ddc059a5eafb1f94)
Error: Failed to open xml file 'C:/Users/Fabio/Documents/My Games/FarmingSimulator2019/mods/Ravenport_Edit_By_Barbicha_Final_Unzip_mods_included/modDesc.xml'.
Load mod: Ravenport_Edit_By_Barbicha_Final_Unzip_mods_included (Hash: 86772fb16a07aeb2178473e6c8c8b96e)
Error: Missing descVersion attribute in mod Ravenport_Edit_By_Barbicha_Final_Unzip_mods_included
Load mod: SM19_MiniSize_MAXIsilo (Version: 1.0.0.1) (Hash: 333ed0d0927478669977001e2216cff4)
Load mod: TSX_EnhancedVehicle (Version: 1.6.3.1) (Hash: bba1a2775c6bf60f447eca1d7a276b28)
Error: Invalid mod name 'UnpackBeast-28-122-1546874090'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Load mod: VehicleFruitHud (Version: 0.53 Beta) (Hash: 082051688d557dd4bcfa99cad0545400)
Load mod: xcollect50meters (Version: 1.0) (Hash: d859c544713d827a763e0b2fcb99fbe9)
Error: Invalid mod name 'Zeisternhof_GP_bitte entpacken'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Error: Failed to open xml file 'C:/Users/Fabio/Documents/My Games/FarmingSimulator2019/mods/Zuckerrohr_Pack/modDesc.xml'.
Load mod: Zuckerrohr_Pack (Hash: 1123081aa0a97e03f189e95020e2127b)
Error: Missing descVersion attribute in mod Zuckerrohr_Pack
Load mod: _V1_FDRLogging___Map___GrizzlyMountain (Version: 1.1.0.0) (Hash: 82bd15c50120eea828cdbc61bad9eba2)
Error: Failed to open xml file 'C:/Users/Fabio/Documents/My Games/FarmingSimulator2019/mods/__MACOSX/modDesc.xml'.
Load mod: __MACOSX
Error: Missing descVersion attribute in mod __MACOSX

Just copied a part where are lots of errors in your log....

**Comment by Interaction1** [comment]
https://gist.github.com/Interaction1/3a44d777e51976ddc80491b862cb4db2

OK! Most of the errors i could fix! downloaded the new version from CP and deleted the other two which i didn't recognized. BUT it's still not working :/
I think i am to stupid for that :D

**Comment by Interaction1** [comment]
How should i explane? Down in the middle is the text No Course loaded. So actually it would work, but it doesn't open. I hear the sound like i am doing something in it, but i can't see mor than the text

**Comment by Tensuko** [comment]
But you know how to open the HUD ? And Screenshot ?

**Comment by Interaction1** [comment]
![20191102123638_1](https://user-images.githubusercontent.com/57270008/68070371-8f5cd880-fd6d-11e9-8fa0-67caea5e3d1a.jpg)
Yes i know how to use and open it! Did it since CP is out for FS19

**Comment by Tensuko** [comment]
Resetted Inputbindings ?
Maybe try ctrl+del ?
Also send me a new logfile with your updated CP Version.
CP is working on that combine that I can see...
What about other Vehicles ? If none of them, it must be your keysettings somehow or a modconflict that gets inbetween....

**Comment by Interaction1** [comment]
Ok, resetted Inputbinds, doesn't work. Tested FS19 for Errors and downloaded some data, doesn't work. Restetted Inputbinds again and than it worked. Strange thinks were happening :) Thanks man!

**Comment by Tensuko** [comment]
Well, it have to work :)
Closed.
