### ISSUE TITLE
CombineAIDriver.lua:73: attempt to call method 'getCurrentDischargeNode'

### ISSUE THREAD

**Issue by rgoe** [Courseplay/courseplay#4496]
Hi there,
I think I found an issue that prevents a savegame from loading.
Symptom: Loading of a savegame gets stuck with 
```
:24 [info lp2704] Module Express 635: Could not find implement with pipe
2019-11-01 20:01 Error: Running LUA method 'loadSharedI3DFileFinished'.
2019-11-01 20:01 D:/Users/User/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay6/CombineAIDriver.lua:73: attempt to call method 'getCurrentDischargeNode' (a nil value)
```
Environment:
FS19 1.5.1.0
DLCs: Anderson, JD, Claas
Mods: AutoDrive 1.0.6.6, CP 6.01.00321, EasyDevControls 1.0.0.0, FollowMe 1.6.0.29, GC 1.1.2.0

How to reproduce: 
Start new game and buy a cotton harvester (tested with both - vanilla from game and John Deere from DLC), send it to some field and generate a working course (mode 6), no need to run it though. Save the game at that point and try to reload - it get's stuck with above mentioned error.

The error appears only with CP 6.02.00321 - tested with .311, .315, .319, .320 the game loads as usual.

Workaround: Open vehicle.xml from savegame with an editor an delete the <courseplay></courseplay> section of the regarding vehicle and the game loads fine.

Full logfile attached:
[log.txt](https://github.com/Courseplay/courseplay/files/3799310/log.txt)

**Comment by Tensuko** [comment]
Jep, was able to reproduce.
Btw, awesome bugreport, thx for that!

**Comment by pvaiko** [comment]
I know, I know, I screwed it up... Try with 322.

**Comment by rgoe** [comment]
Looks good on my end - no error anymore, game loads fine again.
Thanks and best regards.
