### ISSUE TITLE
Raise combine headers during corner and pocket maneuvers

### ISSUE THREAD

**Issue by Nicola-11** [Courseplay/courseplay#4500]
I´m have the following problem with combine harvesters.

On courses with headlands, the combine does not raise the cutterbar when it threshes the corner of a headland.
Also when threshing the pockets for the driver to pick up the corn, the combine does not raise the cutterbar when reversing.
Is this a known problem? I didn't find anything while searching, maybe only I have this problem.
Many thanks for possible information to solve the problem.

Translated with www.DeepL.com/Translator

**Comment by Tensuko** [comment]
Not rly an Issue, but can add this as Enhancement.

**Comment by Nicola-11** [comment]
Wow! First of all thank you for the quick reply!
Second, would be really nice if you could add this... it looks quite odd to me without lifting the cutterbar.
Thanks again and keep up the fantastic work! :)

**Comment by pvaiko** [comment]
Closed due to inactivity. Reopen if still an issue.

**Comment by Nicola-11** [comment]
Leider kam ich in letzter Zeit nicht wirklich zum spielen und konnte somit auch nicht feststellen ob das "Problem" nich immer besteht.
Leider hebt der Drescher beim Zurücksetzen am Feldende noch immer nicht das Schneidwerk sondern setzt mit gesenktem Schneidwerk zurück um dann die Tasche für die nächste Kante des Feldes (Vorgewende) zu dreschen.
