### ISSUE TITLE
Suggestion: use field speed during turn maneuvers if next waypoint is far away

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4502]
As required by @Tensuko in https://github.com/Courseplay/courseplay/issues/4479#issuecomment-548397894, here is the current log with debugchannel 9, 12 and 14:
[log.txt](https://github.com/Courseplay/courseplay/files/3800765/log.txt)

And a [video](https://youtu.be/KpNBWW4Pu0g)

**Comment by Tensuko** [comment]
Jep, its a turn like @pvaiko already said, start is far away from end, so the distance is very long.
Closed.

**Comment by rogeriodec** [comment]
Sorry to insist, but I don't understand what a long-distance has to do with my question.
As you can see, the harvester is traveling from point A only to reach point B in a straight line.
So, why is it using the curve speed (10 Km/h) instead of the field speed (24 Km/h)?

**Comment by Tensuko** [comment]
You can insist as much as you want, Harvester is in a turn manuver and that is driven with 10km/h

**Comment by pvaiko** [comment]
> So, why is it using the curve speed (10 Km/h) instead of the field speed (24 Km/h)?

Because this is a low priority issue. You are more than welcome to open a pull request with a fix for this, I guess it wouldn't be too complicated to increase the speed during a turn maneuver when the next waypoint is far away.

**Comment by pvaiko** [comment]
@rogeriodec You are also more than welcome to experiment with the million options of the course generator, for example add headlands, use another up/down pattern, skip rows, set the direction, etc. you may find a setting that works better for you.

**Comment by Tensuko** [comment]
The new turn should make this Issue needless.
Closed.
