### ISSUE TITLE
Combine is maneuvering by turning off the field, even with the on-field turning option enabled

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4504]
What am I doing wrong? 
As shown in the [video](https://youtu.be/XC-x3iX3Cu4), the combine is maneuvering by turning off the field, even with the on-field turning option enabled, so it's colliding with that tree...

[log.txt](https://github.com/Courseplay/courseplay/files/3801054/log.txt)

The debugs 09, 10, 12 e 14 are activated.

**Comment by Woife1** [comment]
there is no place to maneuver so he is going off field 
set course with 2 lines around the field and it works

**Comment by rogeriodec** [comment]
But this is different behavior from, for example, a seeder/fertilizer moved by truck which is respecting the field limit, ie, when it reaches the limit, the tractor goes back in reverse to reposition and then turns ...

**Comment by Woife1** [comment]
with a harvester it would be a very complex turn 
after turn there is always fruit

maybe don't avoid fruit helps or set pre-turn on 2

**Comment by pvaiko** [comment]
Generate course with 2 headlands, and relax.
