### ISSUE TITLE
Modus 8 Spiel hängt sich auf wenn der Zubringer am Feldcontainer ist

### ISSUE THREAD

**Issue by michel5998** [Courseplay/courseplay#4506]
Moin,
ich wollte mit Courseplay Gülle von der Biogasanlage zum Feldrandcontainer fahren, doch 

1. Courseplay erkennt selten bis nie den Ladepunkt vom Güllebehälter an der Biogasanlage und fährt immer dran vorbei, ohne voll zumachen(hab mich nach einem Tutorial gehalten und den Startpunkt am Güllebehälter gesetzt)

2. Sobald der Zubringer am Conainer an kommt(ich habe eine Wartepunkt an der Stelle gesetzt, wo mir beim einfahren vom Kurs das Überladesymbol angezeigt wurde) hängt sich das Spiel auf und die Log wird voll mit Lua Fehlern zugeschmissen.

Verwendet wurde ein Claas Arion 660 vom Platinum Addon mit Standartdolly und dem Standartzubringer
[log.txt](https://github.com/Courseplay/courseplay/files/3801382/log.txt)

**Comment by Tensuko** [comment]
2019-11-03 09:29 Error: C:/Users/Florian/Documents/My Games/FarmingSimulator2019/mods/FS19_FeedBales/FeedBales.lua:10: attempt to index global 'FeedingTroughTipTrigger' (a nil value)

2019-11-03 09:31 Error: Can't load resource 'C:/Users/Florian/Documents/My Games/FarmingSimulator2019/mods/FS19_Fendt800VarioTMSV4/new/new/shared/detailArray_specular.png'.
2019-11-03 09:31 Error: Can't load resource 'C:/Users/Florian/Documents/My Games/FarmingSimulator2019/mods/FS19_Fendt800VarioTMSV4/new/new/shared/detailArray_normal.png'.
2019-11-03 09:31 Error: Can't load resource 'C:/Users/Florian/Documents/My Games/FarmingSimulator2019/mods/FS19_Fendt800VarioTMSV4/new/new/shared/detailArray_diffuse.png'.
2019-11-03 09:31 Error: Can't load resource 'C:/Users/Florian/Documents/My Games/FarmingSimulator2019/mods/FS19_Fendt800VarioTMSV4/shared/detailArray_specular.png'.
2019-11-03 09:31 Error: Can't load resource 'C:/Users/Florian/Documents/My Games/FarmingSimulator2019/mods/FS19_Fendt800VarioTMSV4/shared/detailArray_normal.png'.
2019-11-03 09:31 Error: Can't load resource 'C:/Users/Florian/Documents/My Games/FarmingSimulator2019/mods/FS19_Fendt800VarioTMSV4/shared/detailArray_diffuse.png'.
2019-11-03 09:31 Error: Failed to open xml file 'C:/Users/Florian/Documents/My Games/FarmingSimulator2019/mods/FS19_fendtFavorit500v1/shaders/vehicleShader.xml'.

Der Error ist ein Callstack, das kann an sonst etwas liegen.

Bei welchem Kurs hast du einen Wartepunkt gesetzt ? Beim Zubringer am Feldrand wäre das richtig.
Der Kurs zum nachfüllen des Feldarbeiters braucht keine Wartepunkt.
Ich probiere das auch nochmal aus...

Courseplay wird schon lange nicht mehr mit zzz_ eingepflegt.
FS19_Courseplay oder FS19_Courseplay6

**Comment by michel5998** [comment]
ich habe es bei modus 8 also flüssigkeitstransport gemacht und nicht bei düngen/säen

**Comment by michel5998** [comment]
und der callstack kam genau ab dem moment wo der zubringer am feldrandcontainer an kam und immer dann wenn ich den fahrer entlassen hab, lief das spiel normal weiter und wenn ich den fahrer wieder eingestellt hab, ging es wieder los mit dem callstack

**Comment by Tensuko** [comment]
Ach du hast noch einen Container am Feld stehen den du mit Modus 8 auffüllen willst ?
Das sollte mit Mode1 gehen und auch da ohne Wartepunkt probieren.
Mode8 sollte eigentlich nur so funktionieren:
Am Trigger laden, zum Feld fahren, am Wartepunkt (beim Feld) warten und dort kann der Feldarbeiter sich auftanken, wenn dann der Mode8 fahrer leer ist, füllt er sich am Trigger wieder auf und fährt wieder zum Wartepunkt am Feld.
Mit einem Zwischencontainer funktioniert das nicht, aber wie gesagt, da kannst du mal den Mode1 probieren (ohne Wartepunkt). Einfach das Füllgut einstellen und los gehts.

Und noch was zum Auffüllpunkt: der Trigger zum auffüllen muss zwischen Ende und Start sein, so das der Anhänger dann im Trigger ist, bevor der Traktor am startpunkt, sollte etwas besser laufen.

Warum alle immer überall Wartepunkt setzen bei Überladestellen ist mir echt ein Rätzel wer das verbreitet....

**Comment by michel5998** [comment]
https://youtu.be/RqHaAKvuQGo?t=505 ich habe mich nach diesem video gerichtet, ich habe mich schon vorher darüber versucht zu erkundigen doch nur wenige video gefunden, wo das thema zubringer angesprochen wurde. von ls17 kenne ich das so und da hats immer so funktioniert

**Comment by michel5998** [comment]
![fsScreen_2019_11_03_14_13_41](https://user-images.githubusercontent.com/49126733/68085728-59d6ee80-fe44-11e9-8898-47dca6d62a56.png)

hier ein bilde davon, ist halt der standartzubringer

**Comment by Tensuko** [comment]
Ach ja da war noch was mit den Fässern und Mode1.... Das müssen wir uns nochmal anschauen.

Ja es hat sich halt doch etwas geändert für CP in FS19 gegenüber FS17...

Müssen wir uns angucken, das ganze...

**Comment by Tensuko** [comment]
Start - Warten - Stop.
Am Wartepunkt (befüllt mit Gülle):
2019-11-03 15:27 Error: Running LUA method 'update'.
2019-11-03 15:27 I:/Dokumente/My Games/FarmingSimulator2019/mods/FS19_Courseplay/AIDriver.lua:1200: attempt to call method 'getTipState' (a nil value)

**Comment by michel5998** [comment]
das witzige an der sache ist dass der gleiche fehler auch auftritt wenn ich keinen feldrandcontainer stehen hab und er inprinzip auf das fass warten soll

**Comment by Tensuko** [comment]
Also ohne Zwischenspeicher da warten bis der Feldarbeiter kommt und auffüllen will ?

**Comment by michel5998** [comment]
genau

**Comment by michel5998** [comment]
hab heute nochmal mit nem mod probiert, wo der dolly fest am fass verbaut ist, hat leider auch nichts gebracht, ich probiere es nachher mal mit standart lkw und standart zubringer

**Comment by michel5998** [comment]
habe es nun mit dem man tgx vom spiel mit dem zubringer probiert und immer noch der selbe fehler und auch da kann ich modus 1 nicht auswählen 
[log.txt](https://github.com/Courseplay/courseplay/files/3805733/log.txt) hier die log

**Comment by Grisu118** [comment]
Den Fehler kann ich so bestätigen. Mode 8 Kurs mit Wartepunkt am Feldrand, sobald der Fahrer dort ankommt füllt sich die Log mit dem Fehler.

Gefahren wird auch mit Auflieger, Dolly und Traktor

[log.txt](https://github.com/Courseplay/courseplay/files/3820961/log.txt)

**Comment by michel5998** [comment]
ich hoffe die können den fehler schnell finden, ich muss auf einem feld gülle fahren, wo der anfahrtsweg lang ist und ich brauche da mindestens 2-3 zubringer

**Comment by Tensuko** [comment]
Schnell geht da leider garnichts...
Derjenige der den Mode8 geschrieben hat, arbeitet (wenn er denn zeit hat) an Mode2 und seine Zeit ist sehr begrenzt.... Ging es ohne Zwischencontainer garnicht ?

**Comment by michel5998** [comment]
nope

**Comment by Tensuko** [comment]
@GeorgeEarslight
since you found a solution for #4559 you have an Idea for this one ?
To explain it:
Mode8 is changed a bit to be a field supply mode, for now for slurry and liquid manure.
It should basically work like Mode1, but with additional Waitpoin (as an Action point) so the Fieldworker can pass by and refill there (as in #4559 ).
Problem is when The Mode8 driver reaches the Waitpoint, LUA Error happens:
2019-11-18 09:28 Error: Running LUA method 'update'.
2019-11-18 09:28 I:/Dokumente/My Games/FarmingSimulator2019/mods/FS19_Courseplay/AIDriver.lua:1186: attempt to call method 'getTipState' (a nil value)

The other way, that there is a container at the Field that gets refilled, produce Error too with Mode8, but actually that should work with Mode1, just that Mode1 is not available for those kind of Trailers.
Not sure if @pvaiko can activate the Mode for them (e.g. Garant VE 8000 ).

**Comment by Tensuko** [comment]
I try out stuff and getting more and more weird things...
For testing I use a joskin mod that can take digestate and stuff, this one works in Mode1 too.
I used a digestate storage mod, but couldn't load, it was the same as in #4559 that is just moved on and not stop for refill. Since that thing made a Callstack when placed, I throw it out.
Then I placed a slurry sellpoint, that worked.
I tried Mode1, he fills up, but doesn't fill up the field Container (just passes by).
Then I tried Mode8, he fills up and moved to the waitpoint, but here is the strange thing:
![fsScreen_2019_11_18_10_06_53](https://user-images.githubusercontent.com/27344744/69039162-ad703d00-09eb-11ea-990f-a417415ab55c.png)
No LUA Error like with the other tools ( AIDriver.lua:1200 and AIDriver.lua:1186 ) but a weird move to the side (see screenshot) and now he just stands there and wait for... nothing?!

So maybe enable overfill for Mode1+Enable Mode1 for Slurry Trailer, or... actually I don't know what happens in Mode8 with the normal slurry Trailer, why they couse LUA Error and that Mode one not, but also not overload....

**Comment by GeorgeEarslight** [comment]
@Tensuko I'll take a look when I get some free time.
From your log CP is trying to read 'getTipState' which probably doesn't exist in tankers.

Mode 8 course Starts near field container, pass via BGA and finish at field container?

**Comment by Tensuko** [comment]
The Idea of Mode8 is:
- Fill up at any Trigger (we started with slurry and digestate, wich was the old Mode8).
- Drive to the Field where is a Waitpoint and wait there.
- When empty, start drive course and fill up again at Trigger.

Basically, it is just like Mode1, just with the Waitpoint so Fieldworkers can refill at the Driver.

The other thing is what ppl originaly tried in this Issue:
Use Mode8 to drive to a Fieldcontainer to fill it up, wich normaly should be done with Mode1 (pick up something at start and empty in trigger on the way without waitpoint), but the Trailer doesn't have Mode1 active, I would have to ask @ThomasGaertner or @pvaiko about that. And as you see in Mode1 there is no overloading, but thats another Issue wich I just found out.
Base Error in Mode8 currently is this:
2019-11-18 09:28 Error: Running LUA method 'update'.
2019-11-18 09:28 I:/Dokumente/My Games/FarmingSimulator2019/mods/FS19_Courseplay/AIDriver.lua:1186: attempt to call method 'getTipState' (a nil value)

**Comment by GeorgeEarslight** [comment]
@Tensuko I've attempted to suppress the nil value error.
Unfortunately, I can't test until the weekend and also don't know if this fixes the general problem.

**Comment by Tensuko** [comment]
@GeorgeEarslight thats ok, no rush. It is already great that you can take a look at this :)

**Comment by Tensuko** [comment]
@GeorgeEarslight I got no words for this, but your fix works, at least on this test.
Does it have any influence on other Modes that I should pre-test ?
![fsScreen_2019_11_19_18_42_30](https://user-images.githubusercontent.com/27344744/69171558-80f81600-0afc-11ea-9edf-2c93c04b2e38.png)

**Comment by Tensuko** [comment]
Oh my god even this is working now.... it simply refills the container.... got to adjust the refill course tho to not crash into it :D 
![fsScreen_2019_11_19_18_55_16](https://user-images.githubusercontent.com/27344744/69172471-26f85000-0afe-11ea-80b6-761579cf2dc7.png)
@pvaiko anything that need to be tweaked on that fix or something ? I have no Idea if that could have any impact on other Mods or Tools

**Comment by pvaiko** [comment]
Don't think so (tipping is Thomas, and BTW, should be moved out of the AIDriver), looks good to me, @GeorgeEarslight thanks again.

**Comment by GeorgeEarslight** [comment]
@Tensuko
No problem, glad to offer any help.
I would check a Mode1 route with a silo and sell point and a seeder with a refill route.

@pvaiko 
I can't really make any useful call search apart from "find in files" in Notepad++ (attemp to show as parent/child stack call) :
```lua
AIDriver:getHasAllTippersClosed() 
  AIDriver:tipIntoStandardTipTrigger() 
    AIDriver:dischargeAtTipTrigger(dt)
    FieldSupplyAIDriver:drive(dt)
  AIDriver:onUnLoadCourse(allowedToDrive, dt)
    GrainTransportAIDriver:drive(dt)
```

**Comment by pvaiko** [comment]
@GeorgeEarslight I use IntelliJ Idea with the EmmyLua plugin (the annotations in the code are for that plugin, it can even keep track of derived classes) that works really well and shows you all the usage plus syntax checking / coloring.

**Comment by Tensuko** [comment]
@GeorgeEarslight will check on that.
And for Notepad++ there is a LUA Plugin that helps a bit with highligthing and kind of code blocks (e.g. if-then-end). Helps me with find the right position to paste in stuff :D

**Comment by GeorgeEarslight** [comment]
@pvaiko @Tensuko 
Thanks for the editor/IDE tips. Some I've already used, some I'll try.
Next, I'll try to fix the fuel saver option when waiting.

**Comment by Tensuko** [comment]
Something what should be added as well is, check if there is at least one waitpoint in the course, just like Mode9 and Mode10 does.
Why ?
-> It won't load the Fieldcontainer and ofc won't stop at the Fieldborder for the Fieldworker.

My other tests went good and it seems to work very good.

**Comment by Tensuko** [comment]
Works now, even the Mode8 Driver is currently buged with another Problem. ( #5029 )
