### ISSUE TITLE
version 00321 : Warning: Tried reverting to input context [COURSEPLAY_HUD] which is not defined 

### ISSUE THREAD

**Issue by betrox007** [Courseplay/courseplay#4508]
hello i got frezze game after creating course, at the begining everything is working fine till i create a fertilizing course with refill course.
the warning said : Warning: Tried reverting to input context [COURSEPLAY_HUD] which is not defined and then game frezze.
any idea whats i did wrong?...

Thanks for help..
[log.txt](https://github.com/Courseplay/courseplay/files/3801525/log.txt)

**Comment by Tensuko** [comment]
No Idea what you did there... I always use EasyDevControls with CP and I got no Issue at all.
Maybe you had anything open or anything keybinded that cause that conflict....
@pvaiko you got an Idea where that Error comes from ? I mean the CP one....

2019-11-03 15:32 Error: Running LUA method 'mouseEvent'.
2019-11-03 15:32 C:/Users/obet/Documents/My Games/FarmingSimulator2019/mods/FS19_EasyDevControls/scripts/gui/EasyDevControlsFieldFrame.lua:169: attempt to compare number with nil

2019-11-03 18:49 Error: Running LUA method 'printVariable'.
2019-11-03 18:49 C:/Users/obet/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay_6_01_00321/CpManager.lua:612: attempt to concatenate local 'variableName' (a nil value)
2019-11-03 18:50 Error: Running LUA method 'loadFile'.
2019-11-03 18:50 C:/Users/obet/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay_6_01_00321/CpManager.lua:617: attempt to concatenate local 'fileName' (a nil value)
2019-11-03 18:51 Error: Running LUA method 'callVehicleFunction'.
2019-11-03 18:51 C:/Users/obet/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay_6_01_00321/CpManager.lua:648: attempt to concatenate local 'funcName' (a nil value)

**Comment by betrox007** [comment]
at the begining everything working fine, i had a 4 tractor cultiplow at field no4, then 2 tractor at field no 2 and 2 at field no 3 all cultiplow, so i add 2 tractor fertilizing at field no 6 with refill course, all working, when i add more 2 tractor for fertilizing at field no8, after create field course then combine it with refill course, that time game frezze... i don't know, maybe lack of memory from my computer or something like that?..., because for other fieldwork its very good work even using multiple tractor in same field and same job, like this video https://youtu.be/qpuvCtrwUXU, i'm using 8 tractor for single field :D

**Comment by Tensuko** [comment]
But you use Follow Me in that Video right ?
It could be the reason for a ModConflict.

**Comment by betrox007** [comment]
yes , ok maybe that the problem, i'll try again and remove the follow me mod

**Comment by betrox007** [comment]
i think its only a memory lack from my computer, i've try again and its work fine now, thanks for your hardwork on courseplay, and make fs19 more fascinating to play on :+1: 
[log.txt](https://github.com/Courseplay/courseplay/files/3802355/log.txt)
![fsScreen_2019_11_03_17_44_05](https://user-images.githubusercontent.com/56646850/68094364-38244880-fed2-11e9-9fd4-667bbb5586db.png)
![fsScreen_2019_11_04_06_55_54](https://user-images.githubusercontent.com/56646850/68094365-38bcdf00-fed2-11e9-950a-6303b4a4aa0e.png)
![fsScreen_2019_11_04_06_56_22](https://user-images.githubusercontent.com/56646850/68094367-38bcdf00-fed2-11e9-8ba5-d9b4442f30d0.png)

**Comment by Tensuko** [comment]
So is this kinda solved for you know or still any Clear CP Issue ?

**Comment by Tensuko** [comment]
I got news for you:
I was randomly arround on ls-modcompany and read, that seasons doesn't work with easydevcontrol, and that woul fit your Error! Remove EasyDevControls from your Mods Folder, that should work.

**Comment by betrox007** [comment]
okay thanks.. i see now what was the error is...

**Comment by Willbobber** [comment]
I constantly get this problem. It wont show for a while and then it keeps coming back. 
I fix it by reloading the game, sometimes I have to reload once, sometimes twice but it works eventually.

PS I dont use follow me mod
