### ISSUE TITLE
When unload combine ready don't drive in front on combine

### ISSUE THREAD

**Issue by Duxtu** [Courseplay/courseplay#4509]
When unload combine is ready, the tractor is driving in front of the combine, standing still in crops.

Not going to work. Is there an setting for the tractor to stay on hold and drive never in front of the combine in crops but always behind the combine? 

![9240](https://user-images.githubusercontent.com/57111591/68085189-9bfd3180-fe3e-11e9-81fd-efaac2b3c1fb.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/3801562/log.txt)

**Comment by Tensuko** [comment]
#3311 #4286 
Closed.
