### ISSUE TITLE
Bunkersilo CP parkt nicht für andere Fahrzeuge

### ISSUE THREAD

**Issue by turbodani** [Courseplay/courseplay#4513]
Guten Abend, leider parkt der CPler auf der BGA beim Silo aufschütten für andere Fahrzeuge nicht - andere CPler (die Abfahrer) halten allerdings auch nicht. 

Problem besteht ohne und mit Mods.

edit: es spielt auch keine Rolle wie groß ich die Entfernung einstelle leider. 

edit2: habe festgestellt, dass der "verdichter" in die P-Position fährt, sobald man slebst im Abfahrer sitzt und CP deaktiviert. Also erkennen die CPler sich "nur" untereinander nicht.

Hat Jemand eine Lösung?

**Comment by Tensuko** [comment]
CP erkennt nur die Mode2 Fahrer nicht.
#3311 #4286 
Closed.
