### ISSUE TITLE
Trailored harvesters during unload decides to hit the poll instead of stopping and unloading nicely

### ISSUE THREAD

**Issue by evansv2** [Courseplay/courseplay#4514]
Sometimes it goes haywire like in this video
Video reference
https://www.youtube.com/watch?v=hpRD8ZTYGUM

, sometimes just unloads and stops and does not continue,
but overall the problem is in this function after thourouhly debugging myself because no one seems to care about trailored harvesters these days, I thought i dig my self into the problem

The problem is in this function UnloadableFieldworkAIDriver:driveUnloadOrRefill(dt)
this is my version that works, its a bit flawed but works, an official update or fix would be nice

never the less here is my version below that works ok

`function UnloadableFieldworkAIDriver:driveUnloadOrRefill(dt)

	self:updateOffset()
    
	local allowedToDrive = true
	local isNearUnloadPoint, unloadPointIx = self.course:hasUnloadPointWithinDistance(self.ppc:getCurrentWaypointIx(),20)
	 
	local takeOverSteering = FieldworkAIDriver.driveUnloadOrRefill(self)
	
	if isNearUnloadPoint then
	 
	  allowedToDrive, takeOverSteering = self:dischargeAtUnloadPoint(dt,unloadPointIx)
	
	end
	 
	 --change speed to very slow right before unload with load
    if isNearUnloadPoint and self.vehicle.cp.totalFillLevel > 400 then
		self:setSpeed(15)
	
		
    elseif isNearUnloadPoint and self.vehicle.cp.totalFillLevel < 400 then
	
	    courseplay:resetTipTrigger(self.vehicle, true)
		self:setSpeed(0)
		
	elseif self:hasTipTrigger() and self.vehicle.cp.totalFillLevel > 400 then
	    self:setSpeed(0) 
		allowedToDrive, takeOverSteering = self:dischargeAtTipTrigger(dt)
	    print("trying to set speed 0")
	end
	  
	 
	  
    if not allowedToDrive and self.vehicle.cp.totalFillLevel > 400 then 
		self:setSpeed(0)
        print("stopping")		
	end
	
	
	if not self.ppc:isReversing() then
		-- 'cause reverse does the raycasting for us
		self:searchForTipTriggers()
	end
      
	return takeOverSteering
end`

**Comment by evansv2** [comment]
Welp this function works with the .304 looks like the .321 , seems to decide to also not complete the unload and just keep driving on a date to brad pitt

**Comment by Tensuko** [comment]
We got a plan for self unloading, paralel to our new Mode2.

**Comment by evansv2** [comment]
> We got a plan for self unloading, paralel to our new Mode2.

Is there a temporary quick fix for this Tensuko? because I take it Mode 2 has been in development since february

Because Mode 2 I take it, the self unloading wont be needed since we can just sit a vehicle with a trailer to pick up the goods, Im using self unloading because nothing else works right now

Here is how I have it in .304 modified with the above code, just for reference
https://www.youtube.com/watch?v=fgUrn8m6eFw

**Comment by pvaiko** [comment]
@evansv2 please create a pull request, copy pasting code here does not help at all, no idea what the changes are.

**Comment by evansv2** [comment]
> @evansv2 please create a pull request, copy pasting code here does not help at all, no idea what the changes are.

Well this code only works on 304 its just for reference, There is no point pulling request for this, What do you guys debug the code with, i take it , its not notepad++ ?

**Comment by Tensuko** [comment]
Are you talking about the 304 UnloadAIDriver branch ?
Couse this runs on V304

**Comment by evansv2** [comment]
> Are you talking about the 304 UnloadAIDriver branch ?
> Couse this runs on V304

I Edited UnloadableFieldworkAIDriver.lua Line 100-130 in v304 for it to function correctly.
New version, if edited wont work, because it starts driving regardless after unloading 5%

**Comment by evansv2** [comment]
> Are you talking about the 304 UnloadAIDriver branch ?
> Couse this runs on V304

the vanilla code does run on 304, BUT time to time, i stops and not goes anywhere after unloading, since it was beets it was unloading like every 2 minutes, and sometimes it would just stop and sit there, thats what motivated me to investigate and modify it, to the above code , the issue was it was regurly stopping random times and just stop after it finished unloading

**Comment by evansv2** [comment]
so to summ it up, on 304 it worked but randomly stopped, on the latest release it goes haywire and turns into batman like in the video :-)

**Comment by evansv2** [comment]
> We got a plan for self unloading, paralel to our new Mode2.

I feel you guys on the rework, cause lots of bugs come when rebuilding, probably alot more than coding from scratch, I hate hate recoding, because, some other code f's up somewhere, else, but coding from scratch would murder the timeline, so its like what do you, its like having a wife, and a new girl with nicer tits , but wife been with you the longest, and your like fuck what do you do

**Comment by pvaiko** [comment]
The problem is not refactoring, the problem is the lack of automated tests. And you probably want to watch your language here.

**Comment by Tensuko** [comment]
Btw Mode2 is written from scratch and currently the problem is time to code and debug!

**Comment by evansv2** [comment]
> Btw Mode2 is written from scratch and currently the problem is time to code and debug!

Yeah debugging LUA is a time consuming process, its not visual basic, where you got a debugger running side by side, lua needs full load of the games, and with mods thats like 45 seconds a pop, I wish they had a better way to debug things, like loading LUA Dynammically while the game is running that would be like super awsome

**Comment by evansv2** [comment]
> The problem is not refactoring, the problem is the lack of automated tests. And you probably want to watch your language here.

Aight Ill quit cursing , im from russia they curse here all the time  sorry about that @Pvaiko I'll try to keep it professional

**Comment by pvaiko** [comment]
> like loading LUA Dynammically while the game is running that would be like super awsome

If you look carefully in the Courseplay code you may find something ...

**Comment by Tensuko** [comment]
Expand SelfUnload to this one ?
