### ISSUE TITLE
Turn on field doesnt work

### ISSUE THREAD

**Issue by Meizter** [Courseplay/courseplay#4517]
Hello! im new on github so i hope this is right place. Im playing FS19 and latest courseplay version and playing on lone oak farm and driving a tractor with a plow, it works as it should but it wont turn on field when i have it activated, i have used courseplay alot, even in fs17. anyone else have this problem?

sry for bad english :)

**Comment by Tensuko** [comment]
Some Tools are not made for turn on Field.
If you can tell us wich plow, I can tell you if this is a bug or simply not possible to turn on the Field.

**Comment by Meizter** [comment]
Its Lemken Titan 18 plow with the fieldwork mode

**Comment by pvaiko** [comment]
CP can't reverse with the Lemken Titan. 

BTW, since we are talking about it, I asked many times before if someone has a real life video of reversing during fieldwork with such big implements.

**Comment by Meizter** [comment]
oh! i thought it could with everything, im sorry i didnt knew that! and i havent tried IRL so i dont know :) thnx for answer!

**Comment by Tensuko** [comment]
I think this is cleared and can be closed :)

**Comment by Merrlin** [comment]
@pvaiko Der Titan ist doch n ganz normaler Aufsattelpflug mit Stützachse. Von der Fahrmechanik müsste das wie mit nem Standardanhänger oder Sattelauflieger funktionieren...
Verwechselst du den vielleicht mit der fetten Terminator TH 18 die aus 2 Anhängern besteht?

**Comment by pvaiko** [comment]
@Merrlin bin nicht ganz sicher was du sagen willst, die Frage war nicht ob es technisch möglich ist mit sowas rückwärts zu fahren sondern ob es man im Praxis tut.

**Comment by Merrlin** [comment]
Wie das in der Praxis aussieht weiß ich natürlich nicht. Beim Titan kann ich mir das gut vorstellen. Da ist vorwärtsfahren wegen dem Überhang deutlich kritischer. Von Kollegen weiß ich daß die auch 20-30m Länge ohne Probleme rückwärts fahren.
Beim Terminator wird man allerdings zu 90% nicht rückwärts fahren. Mit 2 Anhängern ist Rückwärtsfahren fast nicht möglich.
