### ISSUE TITLE
Courseplay / plow problems

### ISSUE THREAD

**Issue by dogunddoc** [Courseplay/courseplay#4519]
Hi,
starting with version 317, plowing does not work properly anymore. Map DonDiego plow SPSL9. Tractor does not matter, field does not matter. The offset always goes to zero automatically. Everything is right until version 316.

I tried it without GC and without mods

Best regards and thanks for your work Thomas

**Comment by raxtor** [comment]
![fsScreen_2019_11_04_23_22_27](https://user-images.githubusercontent.com/831266/68163896-c8f33680-ff5b-11e9-9276-1a7605129559.png)
![fsScreen_2019_11_04_23_34_18](https://user-images.githubusercontent.com/831266/68163897-c98bcd00-ff5b-11e9-9df3-fa0d1f7efbd0.png)
I have some problem too... 1st row is ok and you can stop tractor and restart course and plow will stay on same side. But as you can see a few rows later, when you stop CP (game restart etc), right tractor is always inverting tool but should stay in the same postion like left tractor has it.

**Comment by pvaiko** [comment]
329 should work

**Comment by raxtor** [comment]
Now it works synchronously but after restart both plows are chaning to opposite side than before restart.

**Comment by pvaiko** [comment]
Nothing changed there. Rotation depends on which row the plow is, generally it is on the opposite to the side where the auto ridge markers would be.

**Comment by raxtor** [comment]
![fsScreen_2019_11_05_03_08_48](https://user-images.githubusercontent.com/831266/68173030-e636fd80-ff79-11e9-8bdc-d642f2b74af1.png)

**Comment by raxtor** [comment]
...can you check conwoy mode pls? It doesnt remeber distance in conwoy.. after restart its always set to default 100m..

**Comment by dogunddoc** [comment]
Works Great !! thanks
