### ISSUE TITLE
Avoid islands

### ISSUE THREAD

**Issue by Tritura2** [Courseplay/courseplay#4521]
Hey,

when i created a course on a field with an island, it went straight trought it.

![fsScreen_2019_11_05_09_04_35](https://user-images.githubusercontent.com/37582657/68190157-2bc0ee00-ffad-11e9-98c8-73078098f05a.png)

You can see the CP settings on the right of the picture.

Map: Eiersholt by Datalund v1.0.0.8

Mods: CP v6.01.00329
AD 1.0.6.7

deactivated Mods: Claas DLC
Claas Preorder
Holmer Terra Variant DLC

used maschinery: Puma 200 CVX
                           Bredal K165 + 6m Streueinheit (30m workwide)

![fsScreen_2019_11_05_09_05_20](https://user-images.githubusercontent.com/37582657/68190427-aa1d9000-ffad-11e9-902a-223a2cf7a78e.png)

AI turns deactivated

[log.txt](https://github.com/Courseplay/courseplay/files/3807896/log.txt)

When I use the option "ganzer Kreis" it works fine.

![fsScreen_2019_11_05_09_05_06](https://user-images.githubusercontent.com/37582657/68190989-cbcb4700-ffae-11e9-98be-c95232928472.png)

**Comment by Tritura2** [comment]
![InkedfsScreen_2019_11_05_09_04_35_LI](https://user-images.githubusercontent.com/37582657/68191232-5dd34f80-ffaf-11e9-9aa3-1afdfc9d2278.jpg)

thats the way the helper tries to drive

**Comment by pvaiko** [comment]
That's why it is called 'simple', it can't handle all situations. Use the circle setting.
