### ISSUE TITLE
Feldgrößen ausgeben

### ISSUE THREAD

**Issue by Rumspringa90** [Courseplay/courseplay#4522]
Hallo,

gibt es eine Möglichkeit mit Courseplay die Feldgrößen (in Hektar idealerweise) auszugeben? Entweder in eine Datei oder über einen Debug Channel? 

Ermittelt werden die werte ja, sofern ich das richtig verstanden habe im Code. Konnte nur nicht rausfinden ob man diese irgendwie raus bekommt.

Gruß Henne

**Comment by Tensuko** [comment]
Da kann ich dich nur auf diese Mod aus dem ModHub verweisen:
https://farming-simulator.com/mod.php?lang=de&country=de&mod_id=137433&title=fs2019
Wir werden da (sehr warscheinlich) nichts dran machen, da CP nicht dafür gebaut ist.
Closed.
