### ISSUE TITLE
Spiel lädt nicht

### ISSUE THREAD

**Issue by supernovischer** [Courseplay/courseplay#4524]
wenn ich cp vor dem start des spiels hinzufüge lädt mein Spiel nicht

**Comment by Tensuko** [comment]
Oh großer Zauberkugel, verrate mir das Problem oh erhöre mich so bitte nenne mir auch gleich die Lösung!

Update mal dein Autodrive auf die aktuelle Version. Findes du im AutoDrive GitHub!

Ansonsten logfile anhängen!!

**Comment by Gibbanator** [comment]
no i'm not afraid of being humiliated when posting a problem. lol

**Comment by Tensuko** [comment]
It is always the same, no matter where you look.
'Doesn't work pls help' <- What can ANYONE do with that information ?

**Comment by Merrlin** [comment]
It's a quite simple thing. Who can do LUA vodoo MUST be an Oracle, or at least a famous Wizzard.😁

**Comment by supernovischer** [comment]
Hattest recht mit der neuen AD Version
Funktioniert Wiede


Tensuko <notifications@github.com> schrieb am Di., 5. Nov. 2019, 18:16:

**Comment by Tensuko** [comment]
Wizard Mode deactivated (Closed) :)
