### ISSUE TITLE
forage harvester problem after v6.01.00312.

### ISSUE THREAD

**Issue by docgaming** [Courseplay/courseplay#4527]
i think the problem is after v6.01.00312.
before v312 when a forage harvester gets to the end of the row the tractor following it moves to the side and waits for the forage harvester to get to the next row and changes side keeping to the outside so it don't get in the was on the end of the next row. this works very well.
now after v312 the tractor don't stop at the end of the row and it just stays next to the forage harvester most of the time they will run into each other.
let me know what debug channel you need i can make a video of the it as well if needed

**Comment by Tensuko** [comment]
#3311 #4286 
Closed.
