### ISSUE TITLE
How to disable combine repositioning when full?

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4529]
![image](https://user-images.githubusercontent.com/11199752/68242908-29cc4e80-fff0-11e9-90af-92fc49479d92.png)
This function is not helping much as, as previously reported, the unloader truck is crossing in front of the combine when it is unloading, causing a collision.
How do I get the combine to stop in place (without doing that reverse maneuver) after it's full?

**Comment by Gibbanator** [comment]
having same problem which causes me to have to go back unstick them.. Needs constant attention to complete field. Good workaround is to unload the harvester before 100%. I set mine at 50% for it takes time to get to the harvester. 

Works fine is Harvester does not pull out.. If trailer were to move than Harvester after clear it would be great.  offset of Trailer is to forward for Harvester to move first without collision.

**Comment by Tensuko** [comment]
Deactivate fruit bypass for combine, then it won't back up or do a bag in 1st headland.
Closed.
