### ISSUE TITLE
Error loading and unloading grain, when use two trailers

### ISSUE THREAD

**Issue by BlitzKrieg-76** [Courseplay/courseplay#4530]
Hello. When I use courseplay to take merchandise from my silo to a point of sale using two (2) trailers, the merchandise is only loaded onto one of the trailers. When the set of vehicles arrives at the unloading site, it does not unload, following the return route. Does I do something wrong or is it a program bug?

https://youtu.be/zaZVKFDRLio

**Comment by Tensuko** [comment]
You placed start and stop the wrong way.
You need to make sure, the Tractor hit the Start point when the 2nd trailer is under the Pipe.
CP looks for the loading trigger between stop and start and if Tractor passes start waypoint, he won't load anything.
Try it out and report.

**Comment by BlitzKrieg-76** [comment]
Hello. On the question raised by me yesterday and by Tensuko's answer, I have to inform you that the situation has been resolved.
For loading the trailers I put the starting point outside the loading zone and it worked.
Thanks

**Comment by Tensuko** [comment]
Solved. Closed.
