### ISSUE TITLE
having trouble harvesting corn for chaff

### ISSUE THREAD

**Issue by RENATERA87** [Courseplay/courseplay#4532]
sorry about the bad english.
im having trouble harvesting corn for chaff with the combi mode. the tractor with the trailer in combi mode doesnt recognise the option to deactivate the "AI maneuver". he start the run on the wrong side of the harvester and at the beginning of the first turn they can`t make the turn by themselves. at the second turn they are able to make the turn but the tractor is to far away from the harvester to unload it. the main trouble is that the "AI maneuver" is not disabled when i turned off in the options menu. the video link is below.
[https://www.youtube.com/watch?v=wGyeREzn8wc](url)

**Comment by Tensuko** [comment]
#3311
#4286 
Closed.
