### ISSUE TITLE
Ladewagen wird nach Abladen ins Fahrsilo nicht wieder geschlossen

### ISSUE THREAD

**Issue by Rumspringa90** [Courseplay/courseplay#4534]
Hallo,

habe mir eben ein Kurs zum Fahrsilo vom Normalen Silo eingefahren und wollte es befüllen lassen. Aber der Abfahrer schließt hinten die Ablade-klappe nicht mehr. In der [log.TXT](https://github.com/Courseplay/courseplay/files/3820233/log.TXT) steht am start des Silos "start tipping" und am ende des Silos nochmal "start tipping". Habe es von beiden seiten versucht da ich dachte das es an einem Anderen Trigger liegen könnte aber da war es identisch.

Courseplay V6.01.00331.dev

Gruß Henne

**Comment by Tensuko** [comment]
Das problem kenne ich, aber es passiert nicht immer, manchmal geht es und manchmal nicht, hatte ich erst vor kurzem. Ich kann noch nicht genau sagen, was da das Problem ist, aber ich vermute das es mit dem ich nenne es mal dynamischen abladen zu tun hat. Also wenn der Haufen zu groß wird, fährt er weiter vor, das funktionierte nicht immer und wenn ich dann manuell losfahren wollte, passierte das gleiche, Klappe blieb offen und es tropften noch 2 Liter Stroh raus....

Also eine Mischung aus:
- Anzeige bei 0%
- Minimale Reste an Stroh noch im Trailer
- Abladehaufen zu groß, müsste vorfahren

**Comment by Rumspringa90** [comment]
Funktioniert das mit Rückwärts reinfahren und aufschütten besser? Oder sind da auch noch solche Probleme?

**Comment by Merrlin** [comment]
Ich denk das ist ein Giants Bug. Das passiert bei mir auch ohne CP Beteiligung. Da bleibt halt auch die Klappe offen. Nur mich hintert halt keiner dran den Fuß wieder aufm rechten Pedal zu parken.

**Comment by Tensuko** [comment]
@Rumspringa90 egal wie, passiert bei beiden Varianten.

@Merrlin du hast recht, ist mir auch schon passiert wenn ich selber durch ein Silo gefahren bin...

**Comment by Merrlin** [comment]
@ Tensuko wäre es eigentlich potentiell möglich bei 1% nen timer loslaufen zu lassen und nach Ablauf loszufahren, egal ob die Kiste leer ist?
Damit ließe sich der Bug umgehen.

**Comment by Tensuko** [comment]
Hmm denke das könnte gehen, das problem ist ja, das ab und zu auch nur 0% da steht und wenn die Klappe noch auf ist, jedesmal außerhalb des Bunkter Triggers dann Häckselgut/Gras/Stroh oder was auch immer raustropft, die Klappe würde dann zwar zu gehen, aber ob das jetzt die beste Lösung ist weis ich nicht.... ma gucken.... Es liegt warscheinlich an GIANTS...

**Comment by Merrlin** [comment]
Ja das Problem ist ja das CP den Trailer anhält weil noch n Gramm drin ist. Wenn das Gespann für z.B. 5 sek erst mit z.B. 1km/h fährt ist ja sichergestellt daß er leer ist. Mir ist halt aufgefallen das der LS manchmal die Klappe erst zumacht wenn der Trigger verlassen wird aber nicht schön wenn der Trailer leer ist. Und das wird CP halt abprüfen.

**Comment by Rumspringa90** [comment]
Ich bin mir nicht ganz sicher ob ihr das gleiche meint wie ich. Bei euch hört es sich so an als würde es an dem Abkippen hängen wenn der Haufen zu groß ist.

Bei mir war das Silo aber noch leer und er hat auch alles soweit passend von Anfang bis Ende des Silos abgeladen. (Demnach entstand kein großer Haufen wo er nicht mehr abladen konnte) Also war der Ladewagen komplett leer da tropfte hinter dem Silo auch nicht mehr raus. er fuhr einfach weiter seine Strecke ab aber mit offenem Ladewagen und beim befüllen würde dann natürlich alles gleich wieder abgeladen.

Vielleicht war es schlecht beschrieben von mir oder ihr meint das gleiche und ich hab das falsch verstanden

**Comment by Reiko40** [comment]
Passiert bei mir auch ab und zu wenn ich Gras ins Keilsilo fahren lasse. Ich nehme dann den starken Bauern und ziehe den Ladewagen aus dem Trigger und schon schließt sich die Klappe und er fährt wieder los.

**Comment by JackNorton1** [comment]
[BunkerError.zip](https://github.com/Courseplay/courseplay/files/3880353/BunkerError.zip)
Falls das hilft, ich kann das reproduzieren. Ich teste es mit neue Felsbrunn Map und MAN TGS + SB II 30 (semitrailer). Trailer ist am anfang voll und am ende ist lehr. Bleibt aber offen. Ich habe SaveGame vorbereitet, wo kann man das sehen.

**Comment by Tisdan** [comment]
Ich habe den Bug auch. Habe auch schon div. Silos getestet, weil ich dachte, dass es vllt daran liegt.

**Comment by Ylohn** [comment]
Bei mir funktioniert das Abladen im Durchfahrsilo in Mode1 bis CP-Version 292.

In neueren Versionen wird wohl das Ende nicht erkannt.
Obwohl schon lange aus dem Silo draussen, steht immer noch "Abladestelle erreicht" da und fährt auch nur 10km/h. Der Kipper bleibt oben oder die Klappe beim Schiebe-, Ladewagen offen.

In Mode2 funktioniert es ohne Problem auch bei neueren CP-Versionen.

**Comment by Tensuko** [comment]
Das habe ich ehrlich gesagt noch nie gehört, dass Mode2 super funktioniert und Mode1 nicht....
Bist du sicher, dass du die Modi nicht verwechselst, bzw wie sind deine Kurse eingefahren ?
V292 ist ja nun auch Uralt, welche Version verwendest du aktuell ?

**Comment by Ylohn** [comment]
Aktuell fahr ich mit Version 292, da ich hauptsächlich im Mode1 das Fahrsilo befülle.
Mein Kurs: Startpunkt Farmsilo -> eine Runde durchs Fahrsilo (ohne Wartepunkt, Abkippen, etc) -> Ende vorm Startpunkt.

Zu Mode2 hab ich jetzt keinen Langzeittest gemacht. Hab ich nur interessehalber mal getestet, ob es da (besser) funktioniert.

**Comment by Tensuko** [comment]
So eine alte Version wird nicht unterstützt. Versuche V345 mit Mode1 das wird im Normalfall funktionieren. Zu sagen das es ab X nicht mehr geht ist fraglich...

**Comment by Tisdan** [comment]
Also wenn es in einer alten CP-Version klappt, dann scheint das wohl doch ein Problem mit CP zu sein :o

**Comment by Tensuko** [comment]
Ich wiederhole mich nochmal....
Es passiert auch wenn man selber ablädt.... und es passiert nicht immer!
Du testest neue Version, es passiert, du testest alte Version, es passiert nicht... das kann auch zufall sein.
Mache 100 mal Abladen mit der neuen Version und 100 mal mit der alten Version, dann können wir drüber reden.

**Comment by JackNorton1** [comment]
Bei mir passiert es immer und nur mir CP. Manuell geht es und AutoDrive funktioniert auch. Oben ist mein SaveGame wo kann man das sehen.

**Comment by Tensuko** [comment]
So ich habe komplett ohne Mods und nur mit CP ein paar mal entladen und es hat immer funktioneirt!
Ich habe eine andere Mod im Verdacht, aber ich weis noch nicht welche.
Es muss eine sein die viele von uns Nutzen....

**Comment by Tensuko** [comment]
So ich komme nicht drauf, da ich das nicht reproduzieren kann....
Es funktioniert einfach...
Was ich zu 100% sagen kann, dass ich in meinem Savegame auf der Hof Bergmann die gleichen Probleme hatte, egal ob ich manuel oder mit CP entladen habe.

Jetzt bin ich mir aber gerade unsicher, ob ich in meinem Save einen Unload Point gesetzt habe, weil eben bei meinen tests habe ich das nicht. Ich bin einfach bis hinten an die Silo Wand gefahren und dann wieder vorwärts und es hat wudnerbar funktioneirt.....

Könnt ihr bitte mal erzählen, wie euer Kurs aussieht ? Mit Abladepunkt oder ohne und wenn mit, könnte ihr das nochmal ohne Abladepunkt probieren und das Silo bis hinten durchfahren, fals ihr rückwärts abladet ?

Ansonsten wie gesagt, habe ich irgend eine Mod im Verdacht.
Wichtig: Jeder Art der Nutzung von Mode2, wird hier nicht berücksichtigt, da Mode2 dafür aktuell nicht funktioniert!

Meine Tests liefen alle mit Mode1.

**Comment by Tisdan** [comment]
Vielleicht mal eine Liste mit Mods machen, die in Frage kommen könnten. Spontan würde mir nur Follow Me einfallen

**Comment by zsorra** [comment]
Hallo,
bei mir tritt das Problem genau ab der Version 293 auf, bis zu dieser Version lief alles Problemlos.
An Mods liegt es nicht, den ausser Coursplay und der DonDiego-Map, war der Modordner leer.

Nach einigem herumexperementieren konnte ich das Problem für mich lösen, in dem ich in der AiDriver.lua zwei Einträge geänder habe:
in der Zeile 1017 habe ich nachfolgenden Eintrag auskommentiert:
      
      if not self:getHasAllTippersClosed() then
      stopForTipping = true
      end

und ab Zeile 1097 in etwa habe ich den Eintrag geändert;

Vorher:
	if self:hasTipTrigger() and self.vehicle.cp.totalFillLevel == 0 and self:getHasAllTippersClosed() then
	courseplay:resetTipTrigger(self.vehicle, true);
	end
Nacher:

	if self:hasTipTrigger() and self.vehicle.cp.totalFillLevel == 0 then
	courseplay:resetTipTrigger(self.vehicle, true);
	end

Die Lösung funktioniert auch mit der aktuellen Version 353.

Der Nachteil ist, der Fahrer fährt sofort los, wenn der Anhänger leer ist und wartet nicht mehr bis der Anhänger in Endposition ist, das heisst, wenn man einen Kipper entleert, dann fährt der Fahrer los und senkt den Kipper während der fahrt, das kann auf manchen Maps zu Problemen führen.
Das war allerdings bis zur Version 292 Standart und wurde erst mit der 293 geändert.

Ich hoffe ich konnte etwas weiterhelfen bei dem Problem.

Mit freundlichen Grüßen
Zsorra

**Comment by Tensuko** [comment]
Das ist allerdings sehr hilfreich, vielen dank für deine Mühe!
Ich finde es generell trotzdem sehr merkwürdig, weil es mal ging und mal nicht.

Eventuell findet man eine alternative Lösung um auf das zusammenklappen des Kippers zu warten.

**Comment by Merrlin** [comment]
Ohne es ausprobiert zu haben: Müsste es nicht auch gehen wenn man self.vehicle.cp.totalFillLevel == 0
Zu
self.vehicle.cp.totalFillLevel =< 1
ändert?
Damit wartet CP nicht mehr darauf das der Trailer komplett leer ist sondern nur. Noch das höchstens 1 drin ist.

**Comment by Tisdan** [comment]
Soweit ich weiß, arbeitet FS19 (Und auch der Vorgänger) nie mit ganzen zahlen. Selbst wenn das Silo leer ist, schaut man sich die XML an, dann ist der Wert 0.00235 oder so

**Comment by Tensuko** [comment]
Wenn ihr eine Lösung findet, dass erst auf das zuklappen des Trailers gewartet wird und der Fehler nicht mehr auftritt wäre super :) könnt es ja selber probieren und sonst einen pull request machen.

**Comment by Merrlin** [comment]
Hast du eigentlich ein gutes GitHub Tutorial? Das mit dem ausprobieren wird bei mir aber mindestens bis Freitag Abend dauern

**Comment by Tensuko** [comment]
Ich für GitHub nicht, aber @pvaiko hat eventuell einen Tip.
Selber testen kannst du ja erstmal bei dir offline machen :)

**Comment by Merrlin** [comment]
Da gibt's nur das kleine aber feine Hindernis das ich im Internationalen Fernverkehr fahr, aber im LKW keinen PC hab...
Aber für Tipps, Tricks etc. wie das mit GitHub so funktioniert (insbesondere auch Krams ins Repo reinbekommen) bin ich immer zu haben.

**Comment by Tensuko** [comment]
Muss ja nicht sofort passieren ;)

**Comment by Farmer-87** [comment]
> Hallo,
> bei mir tritt das Problem genau ab der Version 293 auf, bis zu dieser Version lief alles Problemlos.
> An Mods liegt es nicht, den ausser Coursplay und der DonDiego-Map, war der Modordner leer.
> 
> Nach einigem herumexperementieren konnte ich das Problem für mich lösen, in dem ich in der AiDriver.lua zwei Einträge geänder habe:
> in der Zeile 1017 habe ich nachfolgenden Eintrag auskommentiert:
> 
> ```
>   if not self:getHasAllTippersClosed() then
>   stopForTipping = true
>   end
> ```
> 
> und ab Zeile 1097 in etwa habe ich den Eintrag geändert;
> 
> Vorher:
> if self:hasTipTrigger() and self.vehicle.cp.totalFillLevel == 0 and self:getHasAllTippersClosed() then
> courseplay:resetTipTrigger(self.vehicle, true);
> end
> Nacher:
> 
> ```
> if self:hasTipTrigger() and self.vehicle.cp.totalFillLevel == 0 then
> courseplay:resetTipTrigger(self.vehicle, true);
> end
> ```
> 
> Die Lösung funktioniert auch mit der aktuellen Version 353.
> 
> Der Nachteil ist, der Fahrer fährt sofort los, wenn der Anhänger leer ist und wartet nicht mehr bis der Anhänger in Endposition ist, das heisst, wenn man einen Kipper entleert, dann fährt der Fahrer los und senkt den Kipper während der fahrt, das kann auf manchen Maps zu Problemen führen.
> Das war allerdings bis zur Version 292 Standart und wurde erst mit der 293 geändert.
> 
> Ich hoffe ich konnte etwas weiterhelfen bei dem Problem.
> 
> Mit freundlichen Grüßen
> Zsorra

Darf ich mal fragen wo du das genau eingegeben hast bzw wo ich das machen muss ?? Ich kenne mich da nicht so mit aus

**Comment by Merrlin** [comment]
In der AiDriver.lua Zeile 1017 und 1097

**Comment by Tensuko** [comment]
Besteht dieses Problem mit der neuesten Version noch immer ?

**Comment by Tensuko** [comment]
Könnte gefixt sein, sonst neues Issue aufmachen.
