### ISSUE TITLE
Collision when trailer unloads from combine

### ISSUE THREAD

**Issue by rob230580** [Courseplay/courseplay#4535]
Hi, im finding when the combine is full and drives to the side to unload into trailer, the trailer empties and then collides with the combine everytime. Even if I stop course on combine and wait for trailer to move it will park where the combine needs to go. When they're unloading the other direction ie away from the crop there is no problem. 

Is this a new feature? Can I disable somehow as I would rather the trailer drives in the crop and no collisions. Im using the multimap and ive tried with NH and Case combines and many different tractor/trailer combination. Ive used courseplay alot so ive tried most of the usual tricks. 

Apologies if an old topic i couldn't see it.

**Comment by Tensuko** [comment]
Deactivate Fruit bypass for the combine in the CP HUD.

The rest is #3311 #4286 
Closed.
