### ISSUE TITLE
Silo loading problem on a farm to fill 100%

### ISSUE THREAD

**Issue by vbanditto** [Courseplay/courseplay#4537]
The tractor does not load the trailer from the farm silo to the end only to about 15%. There is no waiting point to fill 100%
https://i.imgur.com/s9onbxV.jpg
https://i.imgur.com/KsXC8J0.jpg
https://i.imgur.com/xaW4taM.jpg
https://i.imgur.com/8TODSal.jpg

**Comment by Tensuko** [comment]
I guess it keeps on driving ?
Try to make the line between stop and start more straight.
There could be an Issue about that wich I didn't figure out yet, but I ran into a similar Issue.

**Comment by vbanditto** [comment]
Recording the course once again with longer lines now works correctly and loads to 100%.
I will have to record the courses more precisely. :)
Thank you for the wonderful work the team is doing.
![20191108210531_1](https://user-images.githubusercontent.com/57539782/68507686-ca2ea700-026c-11ea-874d-4ebb97704a1f.jpg)

**Comment by Tensuko** [comment]
Ok so it is kinda solved, but I will keep an eye on that if can improove somehow.
Closed.
