### ISSUE TITLE
Geräte warten nicht, bis voll gefüllt, oder Nachfüllquelle leer.

### ISSUE THREAD

**Issue by iceman234de** [Courseplay/courseplay#4540]
Hallo, wäre es evtl möglich beim Befüllen eines Airseeders das der Traktor stehen bleibt bis der Saatgut und düngertank gefüllt sind ? 

Grus iceman 

P.s. super mod weiter so

**Comment by Tensuko** [comment]
Das gillt eigentlich für alle befüllbaren Geräte. Im moment fahren sie los, sobald wieder etwas drin ist.

**Comment by Tensuko** [comment]
Duplicate of #4262
