### ISSUE TITLE
VehicleSettingsPage.lua:87: attempt to index a nil value

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#4541]
Bei jedesmal Öfffnen von den CP einstellungen kommt dieser Fehler:

Error: Running LUA method 'mouseEvent'.
2019-11-09 15:35 C:/Users/Manni/Documents/My Games/FarmingSimulator2019/mods/FS19_courseplay/gui/VehicleSettingsPage.lua:87: attempt to index a nil value

hab dennur zweimal drin.

MFG Mannie313

**Comment by Tensuko** [comment]
Version ? Logfile ?

**Comment by Mannie313** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3827412/log.txt)

wen ich die einstellungen öffne kommt dieser Fehler.

version 6.01.00333

MFG Mannie313

**Comment by Tensuko** [comment]
Jetzt habe ichs, Advanced Settings!
Jup ist ein Bug, aber bisher hat er noch keine Auswirkung oder ? Bei mir jedenfals nicht.

**Comment by Mannie313** [comment]
bis jetzt nicht. Kommt aber bei jedem mal aufmachen.

MFG Mannie313

**Comment by Mannie313** [comment]
@Tensuko .

Ich hab bei der translation_de Englisch in deutsch Übersetzt. Wo kann ich die Datei jemanden von euch geben.

MFG Mannie313

**Comment by Tensuko** [comment]
Das kann @pvaiko genauer sagen :)

**Comment by Mannie313** [comment]
Kann ich die xml auch hier posten??

MFG Mannie313

**Comment by pvaiko** [comment]
Nein, das geht über Github mit Pull Requests.
