### ISSUE TITLE
V333 - When stop CP while turn and start CP again, CP won't count up WP and doesn't generate turn anymore

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/courseplay#4542]
- Get any Tractor with any Tool
- Generate a simple up/down course on any field
- Let the Tractor start any turn and stop CP
- Start CP at the next Line

-> WP in the HUD won't count up and on the next turn, he will not generate a turn.

Addition: This only happens if you stop CP while in the turn, not when he finished the turn. The problem is when he hits a tree or something, while turn, you got to stop CP, then Issue happens.

[savegame3.zip](https://github.com/Courseplay/courseplay/files/3827551/savegame3.zip)

**Comment by pvaiko** [comment]
>  The problem is when he hits a tree or something, while turn, you got to stop CP
Not with the AI Turn :)

**Comment by Tensuko** [comment]
Won't fix the Issue, that when you stop the CP driver on turn, you can't continue the work.

**Comment by pvaiko** [comment]
You should really try the AI turn once, it backs up when it hits a tree...

**Comment by Tensuko** [comment]
I will try next time, but even if he does it perfect, it is an Issue wich get thing stucked... see if you can do something about it like a reset of PPC, video and log is in discord

**Comment by Tensuko** [comment]
Looks good, seems fixed.
