### ISSUE TITLE
IC Control

### ISSUE THREAD

**Issue by TrakisJoci** [Courseplay/courseplay#4543]
If I use courseplay mode, IC Control does not work.

**Comment by TrakisJoci** [comment]
https://ls-portal.eu/john-deere-6030-premium-3/


I only used this 1 tractor mode and courseplay. The courseplay menu on this machine is cumbersome. IC Control does not work with Courseplay!

**Comment by Tensuko** [comment]
Duplicate of #4185
Closed.
