### ISSUE TITLE
Harvester turn in corner on narrow field with fences doesn't work

### ISSUE THREAD

**Issue by geo-luchs** [Courseplay/courseplay#4544]
Hello

I've on map NF Marsch 4fach V1.1 a field, which is narrow with fences.
Field 11.

Don't worry about the screenshots, that there is no fruit anymore. I did these screnshots after driving on the field.

When I'm using a course in CP, which have haedland, he is driving the first line until end of field, but a little bit more, so he hits the fence.

AI Turn maneuver is activated.

![First_stop_OK](https://user-images.githubusercontent.com/53658780/68535282-2b737a80-0340-11ea-87ba-0735c711e27e.PNG)

After short time, he is detecting this, and drives back. This is very good.
Then he is doing a short turn to the left, this is also ok.
Then he is driving again against the fence, but this time he is not detecting the fence, means he is not driving back.
![2nd_drive_not_ok](https://user-images.githubusercontent.com/53658780/68535287-37f7d300-0340-11ea-87e7-9b5d9ab7bef8.PNG)

Why he is not detecing the fence, is driving back as he did it the first time?

sorry, I can't explain it better in english.

(kurz in Deutsch:
Der Drescher fährt die 1. Bahn auf dem Vorgewende, trifft am Ende des Feldes auf den Zaun, nach kurzer Zeit merkt er, er kommt nicht weiter, udn setzt von allein zurück. Dann macht er den kleinen Schlenker nach links, fährt dann wieder parallel zum rechten Zaun, fährt wieder gegen den Zaun, diesmal bleibt er aber im Vorfährtsgang, kommt natürlich nicht weiter. Aber diesmal setzt er nicht von allein zurück.

Ich hätte jetzt erwartet, dass er hier auch wieder erkennt, dass er blockiert wird, und eigenständig zurücksetzt)

**Comment by pvaiko** [comment]
Wow, that's a tight corner there. I'm always working on improving turns in tight spaces as I love to play on those maps too. But it may take I while until I get all of it fixed....

**Comment by geo-luchs** [comment]
My question is: Why he is driving back automatically the First Time, but Not the 2nd Time wenn driving to the fence?

**Comment by pvaiko** [comment]
Do you have a safe download source for that map?

**Comment by geo-luchs** [comment]
This Map has ~760 MB.it can be Downloaded from uploaded.net

**Comment by Tensuko** [comment]
Try V362 or higher with AiTurn turned on and report.

The download for the Map is here: https://www.fedaction-letsplay.de/ls19/4fach-nf-marsch/

**Comment by pvaiko** [comment]
A site where I see this isn't safe according to my definition:
![image](https://user-images.githubusercontent.com/2379521/72460013-9d799d00-3791-11ea-88f3-fb6c09c8a4e6.png)

**Comment by Tensuko** [comment]
Normal commercial tricks now days but I get your point...

**Comment by Tensuko** [comment]
Talked about this and it should work better with AiDriver on and newest CP Version.
Try it out, else we reopen this and I get the map to see whats happening here....
Closed for now.
