### ISSUE TITLE
Drescher lädt nur für 1sek. ab und klappt dass Rohr danach wieder ein.

### ISSUE THREAD

**Issue by Cajus0815** [Courseplay/courseplay#4546]
Ich Dresche mit einem JD S790i (läuft in Modus 6 also Feldarbeit) und fahre mit einem 930 und Annaburger ÜLW ab (funktionierte für ca. 30h problemlos). Die CP version ist: v6.01.00333.dev und bin auf der NF Marsch 4fach. Log ist bis auf eine "aiTrafficCollisionTrigger missing" von einem anderen Fahrzeug fehlerfrei. Auch, wenn ich manuell mit anderen Anhängern abtanken will, ist es das selbe Spiel. Möglicherweise ist es ein Bedienerfehler oder hat noch jemand solche Probleme und hat eine Lösung gefunden?

**Comment by Tensuko** [comment]
Schritt für Schritt bitte.
Drescher macht also seine Arbeit, du fährst mit einem Traktor+ÜLW hin und er tankt nur 1sekunde ab dann klappt er das Rohr ein ?

**Comment by Cajus0815** [comment]
Genau so nur passiert dies auch bei anderen Anhängern

**Comment by Tensuko** [comment]
Gib mir mal bitte ein komplettes logfile von dir.

**Comment by Cajus0815** [comment]
Logfile?
das, was mir in der Log angezeigt wird oder was?

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Cajus0815** [comment]
Ich habe noch weiter mit weiteren ÜLWs getestet und habe herausgefungen, dass dieses Problem nur bei den "europäischen" Modellen auftritt(die schmaler sind). Die breiteren, wie die aus dem Coolamon Pack, Brent Avalanche oder auch dem Horsch Titan 34UW. Beim Annaburger und dem Hawe ULW 5000 zeigt sich das gleiche Problem

**Comment by Cajus0815** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3828529/log.txt)

**Comment by Tensuko** [comment]
Soweit sehe ich jetzt keine Probleme.
Ich kann das aber nicht so richtig nachvollziehen...
Passiert das auch mit nur Vanilla Fahrzeugen ? Ich kann es halt nicht so richtig glauben, weil ich mit meinen über 550 Mods keine Probleme in der Richtung habe...
Kann es sein, dass der Wagen die Frucht die du abtanken willst garnicht aufnehmen kann ?

**Comment by Cajus0815** [comment]
Es ist nur normale Gerste und es lief wie gesagt für 30h gut. Die Vanilla Fahrzeuge Funktionieren und ich bin jetzt einfach auf eine Anderes Gerät Umgestiegen

**Comment by Tensuko** [comment]
Ich interpretiere den letzten Satz als 'hat sich erledigt' und mache hier zu.
