### ISSUE TITLE
Problem mit Silo schieber (BGA)

### ISSUE THREAD

**Issue by pulimatrix** [Courseplay/courseplay#4547]
Hey Jungs da das Problem ja bereits bekannt ist das wenn Ladewagen ins Silo fährt und bei  einem korn bzw 1ltr Hängen bleibt(Hoff das das Bald geht, jetztt hab ich das Problem das der silo schieber kurs anfährt einmal schiebt zur park position fährt und ab dann schmeist er 

C:/Users/ronny/Documents/My Games/FarmingSimulator2019/mods/courseplay_6/LevelCompactAIDriver.lua:208: attempt to index a nil value fehler :/

Vorher selber Version nix geändert seit heute trat das Problem auf! beim ersten mal silo schieben lief alles super das beladen und das verdichten klasse aber seit heute zu nehmend fehler :/ lg wenn bilder gewünscht sagen und wenn log benötigt auch. lg

**Comment by Tensuko** [comment]
Ich weis nichtmal welche Version du hast....
Wie sollen wir das jetzt feststellen vorallem wenn du nichtmal die CP Version gewechselt hast.

**Comment by pulimatrix** [comment]
Also,habe die version v6.01.00.333 dev,
habe mehr fach neu gestartet, und so wie ich grade feststelle, da ich noch einen AD kurs zum külle beladen an der BGA hat, fährt er zur park position und verharrt dort, starte ich spiel neu und mache rein nur die BGA dann läuft alles wie gewohnt. Ich schaue immer in Regel mässigen abständen(alle 2-4Tage) ob es was neues gibt. und lade mir immer die neuste Version runter! ABer wede mir an merken das ich immer die infos der Aktuellen Version mitliefere :-)

**Comment by betrox007** [comment]
hi @Tensuko i have  same problem with version 00350, when i try to figure out that error only happen when there some spillage of chaff outside of bunker trigger and near with the stoped point from course, when i remove the spillage manually, after removed spillage then run the leveling course again the error no appears again..
here is my log file and some screenshot
![fsScreen_2019_12_29_19_58_48](https://user-images.githubusercontent.com/56646850/71557840-70817680-2a7e-11ea-9743-0ffa4240d6ad.png)
![fsScreen_2019_12_29_19_59_00](https://user-images.githubusercontent.com/56646850/71557841-711a0d00-2a7e-11ea-9773-5bac47be5f45.png)
![fsScreen_2019_12_29_20_04_32](https://user-images.githubusercontent.com/56646850/71557842-711a0d00-2a7e-11ea-9d2d-f0946dbbe9d8.png)
![fsScreen_2019_12_29_20_08_35](https://user-images.githubusercontent.com/56646850/71557843-71b2a380-2a7e-11ea-9fad-41ae6f043fe8.png)




[log.txt](https://github.com/Courseplay/courseplay/files/4008100/log.txt)

thank's...
i'm sorry for my bad english

**Comment by Tensuko** [comment]
Besteht das Problem weiterhin ?
