### ISSUE TITLE
Reminder: Keyboard Commands

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#4550]
Just my annual reminder that some more keyboard bindings would be just awesome... Glad to see you added the shovel positions..

A few others I really am hoping for, that I have to reach for my mouse quite alot are:

Start Course at : this would be the best key command ever..   always reaching for my mouse when driving to switch between First and Next or Current waypoint.

Clear Current Course:  This would also be very handy, as its constantly being used

Show All Waypoints : Also something I would like to be able to more easily toggle

Thanks for your hard work!

**Comment by Tensuko** [comment]
Duplicate of #3085
Closed.
