### ISSUE TITLE
Mode 2 alfa: The game does not load

### ISSUE THREAD

**Issue by badfly** [Courseplay/courseplay#4553]
Good afternoon! when trying the alpha version of mod 2, the game does not load. The following is in the log:

[Log cut.txt](https://github.com/Courseplay/courseplay/files/3831843/Log.cut.txt)

The last 10 lines in log are repeated, the 489 megabyte log is now
![2019-11-11_17-46-49](https://user-images.githubusercontent.com/9772203/68595859-55957b80-04ab-11ea-9b6e-62d01c519c00.png)
`

**Comment by Tensuko** [comment]
Must be some Mod Conflict.
A Callstack is hard to say whats the Error.
The only thing I see is you still got old FS19 Version. Not sure if that is a problem.

**Comment by badfly** [comment]
https://www.modhoster.com/mods/holmer-pack-oy

This mod was the cause of the crash. Thank you!
