### ISSUE TITLE
Combine runs into tractor when unloading (with AutoDrive)

### ISSUE THREAD

**Issue by Flashsolutions** [Courseplay/courseplay#4555]
While using Autodrive to unload the combine, when the combine becomes empty, it turns to the left and runs into the tractor as it tries to straighten out to resume harvesting.  If there could be a 1 or 2 second delay before resuming, the tractor would have time to reverse away from the combine.

Question....  How do you prevent the combine from reversing and pulling to the right when it becomes full?  I have tried every setting I can find and nothing works to make the combine just stop and wait to be unloaded without backing up and turning to the right of the field.  See youtube video link for settings I am using... https://www.youtube.com/watch?v=vMQ_GA-tkD0

If you need more information, tell me what debug options you want turned on.  
[log.txt](https://github.com/Courseplay/courseplay/files/3832851/log.txt)

**Comment by Tensuko** [comment]
Deactivate Fruit bypass in settings.
Not sure what @pvaiko can do about delay or wait for Driver, thats basically what we do for our Mode2 (Communication between Combine and Driver).

**Comment by Woife1** [comment]
you can also set a distance for the trailer
so the overload point could be at the front of the trailer

**Comment by Flashsolutions** [comment]
@Woife1, yes, I have tried to change that too, but if you try to set it past the trailer, the combine will not unload, so I have set it as close to the front of the trailer as possible, but the combine still grazes the tractor when it departs.  Ideally, I would like for the combine to stay on its path rather than backing up and turning when doing the perimeter.   But the setting 'straight' and 'curved' do not change its behaviour.  Maybe that is a bug.

**Comment by pvaiko** [comment]
Should be an easy fix, I'll change it once I have a little time.

**Comment by Flashsolutions** [comment]
Excellent work! I retested this with pathfinding turned on and the delay gave the tractor ample time to get out of the way.  Thank you!

**Comment by KCHARRO** [comment]
This same problem is currently happening in mode2, there is no communication between harvester and driver, and they crash into each other, I remember that version 280 worked well in mode2, the combined one backed down, the driver was placed and unloaded and the combined one hoped that The driver left and did not collide.

Sometimes I left home, leaving CoursePlay working, and when I returned, the work was done.

**Comment by Tensuko** [comment]
@KCHARRO That is becous of #3311 and #4286 
For what am I makeing sticky notes on top of all Issues.....
