### ISSUE TITLE
Mode 2 paying wages

### ISSUE THREAD

**Issue by Misamangame** [Courseplay/courseplay#4556]
Hello guys,

since update 6.01.00333 I'm having issue with mode 2. When I assign truck/tractor to this mode, money will start go down even when I have wages off. First I thought it will be truck/trailer combo mode issue, but it does same thing for me with vanilla tractor/trailer.  Does anyone else experinced this? Will do some more testing tomorow, if there is some bug channel which can help let me know.

**Comment by Tensuko** [comment]
Thats becouse Mode2 still use the old Driver.
#3311 #4286 
Closed.
