### ISSUE TITLE
Massive FPS drop when CP is running

### ISSUE THREAD

**Issue by SteelRodent** [Courseplay/courseplay#4558]
Running cultivators (mode 6 obv) with CP the game drops to 25-35 fps, but the odd thing is that it's only while it's doing the up-down parts. As soon as CP reaches the end of a track (and lifts the tool) and goes into a (PPC) turn, the game jumps back to 60 fps. Then when CP lowers the tool and heads down the next track, the fps instantly drops again. Then when it gets to the headland (doing up-down first and then headland) the fps goes up by about 20 fps.

At first I thought it was because I was using articulated tractors (2-3 at a time), but it happens with a single regular tractor as well. Tried on 3 different maps, 2 of them by giants, different tractors and different tools, and it's the same thing. Whether I'm running 1-2-3 tractors at a time, or have CP running multiple jobs in different parts of the map, don't appear to make any difference to the framerate.

I haven't tried with plows, but so far I haven't noticed this heavy fps drop with harvesters, mowers, tedders, or windrowers, and mode 4 and 10 don't seem to hurt the framerate much at all either. There's always some fps drop when CP is driving, but normally not this bad, and to me it's weird that the fps drops so hard on what I would assume is the simplest part of the job (going in a straight line).

Size of field (and thus number of waypoints) also don't appear to make any difference.

This is on CP 334 and 335.
It appears to only be a performance issue, but the game isn't really playable when the fps drops below 30 and that's the real problem.

On a side note: The stuttering issues I had with the forage harvesters appear to be fixed and it's been running perfectly smooth on these last two builds.

**Comment by Tensuko** [comment]
Checked logfile for any Error ? Can you attatch your logfile pls.
Beside that: It must be on your end, couse I don't have any performance Issue on Mod-Map with several Mods running, while 2 or more CP driver do ther jobs. Also see YT ppl do recording with CP and have no Issue with performance (even on 4x NF Marsch)

**Comment by SteelRodent** [comment]
Log file: https://gist.github.com/SteelRodent/68a51444618cb345b8d70abca9b77b88
Two of the mods have minor issues, but it's never been a problem.

Won't deny it could be my computer (it is a bit old by now), but I just noticed that it's only when going east-west. On north-south courses there's no abnormal performance hit. So now I'm really dumbfounded.

The one core is at 80% load the entire time when CP is running, but when the fps goes down the GPU slows down, which normally means the game isn't sending it anything to draw. I'll keep an eye on it, but you may be right that it's not CP's fault.

**Comment by Tensuko** [comment]
There is one rule for mods: Only one Mod Map in the Mods folder to prevent any Issues. Thats what you should try 1st.
Then try without follow me mod and maybe realdirt have a problem with any textures from the map. Its just a try as I cant tell you 100% whats the Issue, but keep only one map at the time in mods folder.

**Comment by SteelRodent** [comment]
Removed every modded map other than Lapacho where I'm playing atm, and that seems to have helped. Honestly thought Giants had learnt not to load stuff not in use when they stopped listing every installed map on the mod loading screen, but guess not. Have to clean out the mods some more I guess, to only keep what's in use.

Sorry for bothering you with an issue that's not for you to fix. But thanks a lot for the help nevertheless :)
