### ISSUE TITLE
Horsch Slurry tank 21.000 refill issues

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#4559]
This tool have some issue with refill course.
I have a refill course near the field with and without Wait Point.
Without Wait Point, tractor will just drive the course without stopping at refill container.
With Wait Point, tractor will stop at Wait Point, but then wont continue even if its full.

If i use ingame default slurry tank, Joskin for example, it works without issues.

Is Horsch DLC having issues with CP ?

![fsScreen_2019_11_12_16_52_26](https://user-images.githubusercontent.com/32069662/68687164-17609080-056d-11ea-9a33-a1a2e04ed026.jpg)
![fsScreen_2019_11_12_16_52_47](https://user-images.githubusercontent.com/32069662/68687165-17f92700-056d-11ea-8231-d50ed7a16c27.jpg)

**Comment by Tensuko** [comment]
Did you set the right filltype on the 4th page ? (the up/down slider symbol)

**Comment by bojanh66** [comment]
Yes, yes, Farm silo load Slurry or Digestate.
Actually, i think this is the problem:
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=135293&title=fs2019

I tried to use Samson PG II 20 with Zunhammer Farmland Fix 15 and same issue, it just goes past refill trigger.

Does this mod have issue with CP ?

**Comment by Tensuko** [comment]
Oh okay I see.
Does it happen too if you use other attatches so can say its a general problem with those kind of configurations or just this specific one ?

**Comment by bojanh66** [comment]
Tested now with few default ingame attachers, same issue, it just drives past refill tank.
It detects it at first few seconds and says "Loading 0 of 20000" but then just continue.

Do you need some logs ?

**Comment by Tensuko** [comment]
Channel 1 and 2 with vanilla equipment.
But not sure when we take a look at it, but I mark it as a bug.

**Comment by bojanh66** [comment]
https://youtu.be/7TiLPUJEwEU

[log.txt](https://github.com/Courseplay/courseplay/files/3837277/log.txt)

**Comment by SteelRodent** [comment]
I had issues with this not working when I tried doing it with one of the Samson slurry spreaders, but that was a few months ago and I just assumed it wasn't implemented yet. It should work to refill it from the field tank (or what the heck it's called in the game), but it definitely has a problem with the towed tankers.

The Horsch sprayer also won't refill from the Horsch truck-tanker, from the same DLC - have to do it manually - but this works fine with CP in FS17. But last I tried using self-propelled sprayers in FS19 CP didn't like them, so haven't tried this in a while.

I have had CP automatically fill the vanilla potato seeder with fertilizer from the IT-runner tanker (26.23 mod on the modhub). So whether the problem is isolated to slurry or just Giants' tankers I can't say.

**Comment by Tensuko** [comment]
> but this works fine with CP in FS17

This is rly no argument, pls stop bring this up.
CP6 was at some point rebuild and had to, else it still wouldn't run at all....

And as figured out, somehow it can't load when the tank got an attatchement.

**Comment by GeorgeEarslight** [comment]
> https://youtu.be/7TiLPUJEwEU
> 
> [log.txt](https://github.com/Courseplay/courseplay/files/3837277/log.txt)

Can you log with channel 19?

**Comment by bojanh66** [comment]
Do you need channel 19 only or 1 + 2 + 19 ?

**Comment by bojanh66** [comment]
https://youtu.be/aG4C3WB6EZM

[log.txt](https://github.com/Courseplay/courseplay/files/3837935/log.txt)

**Comment by GeorgeEarslight** [comment]
Yes, as Tensuko said CP is checking if TD12 is able to fill and it's messing it. 
I need to further read what's going on as there should be a check whether an implement is fillable so it can be skipped.

**Comment by Tensuko** [comment]
Thx @GeorgeEarslight for helping out. Much  appreciate that.

**Comment by GeorgeEarslight** [comment]
@bojanh66 Could you try the fix and report, please? 
I've only tested with the Samson and TD12.

**Comment by bojanh66** [comment]
I tried it now with same equipment as u did.
It will work only if i put Wait Point during refill course.
If there is no Wait Point, driver will not stop for refill.

**Comment by Tensuko** [comment]
@GeorgeEarslight your fix works perfectly! Thank you! You can push that and @pvaiko will (hopefully) make new release out of it :)
![fsScreen_2019_11_18_09_32_33](https://user-images.githubusercontent.com/27344744/69036532-63388d00-09e6-11ea-8e6d-6792a5ae0bd0.png)

@bojanh66 
you had to add a codline from George to try it, not only with the tool.
And I tell you this one too: There is no need of Waitpoints! I don't know who spread that nonsence arround, but waitpoints are for what they are named, to simply wait (and do some actions in specific modes....) but won't help for triggers! Else the trigger is noticed correctly or not. A Waitpoint won't change anything on that... Wait for the pushrelease, then you can try it with next version.

**Comment by bojanh66** [comment]
Oh im sorry, i didnt see he posted a codline.
Yea i know Wait Point is not needed on refill courses, but in this case, its just a temporary fix :)

**Comment by GeorgeEarslight** [comment]
@Tensuko I've already made a request #4572. 
This might also fix #4144.

**Comment by Tensuko** [comment]
@GeorgeEarslight do you mind take a look into #4506 ?
I posted a summery and my latest experiments at the end in English.
Maybe you have an Idea about it...

**Comment by pvaiko** [comment]
Pull request merged, release built, thank you @GeorgeEarslight, I really appreciate your contributions.
