### ISSUE TITLE
CP getting stuck refilling

### ISSUE THREAD

**Issue by SteelRodent** [Courseplay/courseplay#4560]
Hate to bring this up again, but I couldn't find the old issue (several months back).

It's still completely random when this happens. CP will happily drive to refill dozens of times, and then all of a sudden it gets stuck in the refill tipper. It does refill, but it appears it loses track of the fill level.
![20191112195100_1](https://user-images.githubusercontent.com/20990941/68702150-91ead980-0588-11ea-960a-1e65a51b9aa0.jpg)

I've had this happen with all the sprayers I've used, the Bredal lime spreaders, and some of the sowers/planters.
With the Bredal spreaders the game plays the hydraulic sound and tries to close the cover, but CP keeps opening it, so it sits there flapping rapidly.

Stopping CP and immediately hitting "drive now" with "nearest" waypoint makes it go back to where it left the field. Though sometimes I've had to move it completely out of the trigger before it would go back to work, but it still goes back to where it stopped.

I tried moving the refill points further apart so it can't possibly sit in more than one trigger at a time, but seems that wasn't the problem.

**Comment by Tensuko** [comment]
I didn't had that many runs yet.
The problem is that it generaly works, but what cause it to not work is the question.
Channel 1 and 2 would help I guess, but it wouldhave to record the one working and the one not working....

I wonder if that is same kind like the unload in bunker, when there is a tiny bit left and it doesnt stop tipping, just here not stop refilling....

Can you try also to set refill to 99% ?

**Comment by betrox007** [comment]
> Hate to bring this up again, but I couldn't find the old issue (several months back).
> 
> It's still completely random when this happens. CP will happily drive to refill dozens of times, and then all of a sudden it gets stuck in the refill tipper. It does refill, but it appears it loses track of the fill level.
> ![20191112195100_1](https://user-images.githubusercontent.com/20990941/68702150-91ead980-0588-11ea-960a-1e65a51b9aa0.jpg)
> 
> I've had this happen with all the sprayers I've used, the Bredal lime spreaders, and some of the sowers/planters.
> With the Bredal spreaders the game plays the hydraulic sound and tries to close the cover, but CP keeps opening it, so it sits there flapping rapidly.
> 
> Stopping CP and immediately hitting "drive now" with "nearest" waypoint makes it go back to where it left the field. Though sometimes I've had to move it completely out of the trigger before it would go back to work, but it still goes back to where it stopped.
> 
> I tried moving the refill points further apart so it can't possibly sit in more than one trigger at a time, but seems that wasn't the problem.

have you check for the load Silo setting at CP hud?, i ever get that problem with Bredal lime spreaders, after refill it stuck at refill station, when i check out the Load silo setting was wrong, it set to fertilizer not lime..also with sprayer for herbicide, silo load set to liquid fertilizer not herbicide..thanks

**Comment by SteelRodent** [comment]
> have you check for the load Silo setting at CP hud?, i ever get that problem with Bredal lime spreaders, after refill it stuck at refill station, when i check out the Load silo setting was wrong, it set to fertilizer not lime..also with sprayer for herbicide, silo load set to liquid fertilizer not herbicide..thanks

I checked it to make sure, but I always double check before I start CP driving because I've noticed it gets reset when the tools are disconnected (so I'm guessing that value isn't saved with the tool).

I tried running lime on field 2 on the Welker map (which requires several refills), but it never failed. So not sure if this is a Lapacho issue, though since neither map is scripted I don't know what the actual difference is other than the ground textures.

@Tensuko last I had this I tried setting it to 99% and it worked for a while and then it broke again. Will try again and see if it makes a difference.

**Comment by SteelRodent** [comment]
Set it to 99% and started the lime job again. When CP went into refill it got stuck refilling again, this time it said "filling 18700 of 18950", but it filled to 18770. This time the spreader glitched rapidly opening and closing, and kept going even when I stopped CP and pulled the spreader out of the trigger. Had to restart the game.

Log with debug 1 and 2 on: https://gist.github.com/SteelRodent/e5edc7f8d7080ebc137fabd76dff7388

**Comment by SteelRodent** [comment]
Tried running on different fields, but I just could not get CP to do a succesful run on Lapacho, so switched to the Welker map. Otherwise same tractor, weight, and spreader, and the same mf refill shed, but it works just fine there.

Log: https://gist.github.com/SteelRodent/6895c5d9f23b00fd9c3df57af3bc1e4c
Honestly can't see any difference on the debug info in the log, but you're the  experts ;)

Will post again if it decides to behave on Lapacho.

**Comment by Tensuko** [comment]
This one is kinda old and it was prooven that refilling works fine. Not sure about specific maps or silos...
Closed anyway.
