### ISSUE TITLE
Cp freezing at the end of a row and won't perform turn manuver

### ISSUE THREAD

**Issue by Kn1ghtwolf** [Courseplay/courseplay#4561]
At the end of a up/down row cp freezes and throws a calls stack and locks up my game and it does it on multiple maps with multiple equipment
![2019-11-12 (1)](https://user-images.githubusercontent.com/50271046/68731274-805ffc80-059d-11ea-9307-69093cadff3e.png)

**Comment by Tensuko** [comment]
This doesn't look like a Vanilla Plow.
Wich one is it and from where ?
Full logfile pls...
https://github.com/Courseplay/courseplay/wiki

**Comment by pvaiko** [comment]
Yes, those are error messages from the Giants code when CP updates the turn progress to rotate the plow when possible. Guess that the rotation parameters of the plow aren't set up correctly because CP works just fine with the standard rotating or non-rotating plows.

**Comment by Tensuko** [comment]
Mod Issue I would say...
