### ISSUE TITLE
Mode 2:Tractor won't unload combine when I'm in that same tractor

### ISSUE THREAD

**Issue by blaz62746** [Courseplay/courseplay#4563]
Pretty much what I wrote in the title.
I'm working on the field with combine. I generated course for it and I recorded course for tractor to unload to farm silo. I started the combine and also started course for 2 tractors with trailers to unload combine and then transport grain to farm silo. Combine has driver priority set to fill level. However, if I'm in the one of the tractors that should unload combine, that same tractor won't unload combine even if it has more grain in the trailer than second tractor nor if it is closer than second tractor (which it shouldn't do anyway). When I'm in the combine, it all goes as it should.
Note that, I'm not doing it on the vanilla map but still, I think that if the map itself is the problem, then it wouldn't work even if I'm not in either of the tractors.

**Comment by Tensuko** [comment]
You got latest version ? We don't count Versions on that Alpha.
Also: the Mode2 Page is new, you assignt Mode2 drivers to the combine.
Try it out.

**Comment by blaz62746** [comment]
I'm using v335.
Yes, I assigned mode2 drivers to the combine and the combine itself was on fieldwork mode.

**Comment by Tensuko** [comment]
V335 doesn't have mode2 alpha...... see #4286

**Comment by blaz62746** [comment]
Sorry man, I didn't know that is not alpha. Anyway, I'm having that problem on v335. Does that mean that v335 has less bugs than alpha?

**Comment by Tensuko** [comment]
As I wrote, for alpha Version read #4286
