### ISSUE TITLE
Bunker Silo Speed Not Unloading All In Bunker

### ISSUE THREAD

**Issue by jhomer** [Courseplay/courseplay#4564]
I think this has been talked about already, a while back. Not sure if this is still a know issue or if there is any workaround for this?

Mode 2: Sometimes it will unload the entire trailer in the bunker "drive through" then the next time it will be driving a ways past the bunker and still unloading.
I am using 3 identical trailers.

On a different topic, don't think it's an issue:
I haven't done much with FS19 or CP in the past months but if I seen correctly from looking through the issues and posts, in mode 2, when chopping, the tractor trailer driver would drive behind the chopper when opening up a field. I have not seen this work for myself yet. Maybe there is something I have missed, a setting, or doing something wrong? 

Thanks for your time!

**Comment by Tensuko** [comment]
See #3311 and especialy #4286 you can try out the Mode2Alpha Branch discribed there.
Other then that, no support for old Mode2.
Closed.
