### ISSUE TITLE
Fehler beim Drescher abfahren

### ISSUE THREAD

**Issue by seeferkel** [Courseplay/courseplay#4565]
Benutzte Version : 6.0.1.00335
Wenn der Feldrand während dem Abfahren erreicht wird sollte der Drescher anhalten.
Er wendet jedoch normal und kommt entweder mit dem Abfahrer in Kollision oder beide blockieren sich gegenseitig bei der weiterfahrt.
Früher blieb der Drescher stehen bis der Abfahrer abgetankt hatte und danach den Weg frei machte.

**Comment by Tensuko** [comment]
#3311 #4286 
Closed.
