### ISSUE TITLE
Kollision beim Abfahren

### ISSUE THREAD

**Issue by seeferkel** [Courseplay/courseplay#4566]
Benutzte Version : 6.0.1.00335
Wenn der Abfahrer neben dem Drescher her fährt und sein max Füllstand erreicht wird versuchte  sofort vor dem Drescher zum abladen zu fahren, was natürlich zur Kollision führt.
Abfahrer sollte stoppen nachdem er voll ist und warten bis der Weg frei ist-

**Comment by Tensuko** [comment]
#3311 #4286 
Closed.
