### ISSUE TITLE
Feature request: Button to reset offset to 0

### ISSUE THREAD

**Issue by SteelRodent** [Courseplay/courseplay#4567]
I'd just like a button that resets the offset to 0, instead of having to click it 0.1 meter at a time.
When taking any vehicle that's been running on a multi-tool course the offset tends to be stuck when clearing the course. It would just be nice to have a button next to the +/- buttons to set it back to 0.

Sometimes it's useful to keep the offset, so automatically clearing it wouldn't be a good idea.

Otherwise, keep up the great work guys :)

**Comment by pvaiko** [comment]
There's a calculator button to reset the X offset

**Comment by Tensuko** [comment]
Since there is a resetbutton, I close this. (never rly used that one...)
