### ISSUE TITLE
Mode 2 Alpha: combines.lua:6:

### ISSUE THREAD

**Issue by jhomer** [Courseplay/courseplay#4568]
I have just tried the CombineUnloadAIDriver alpha branch today and keep getting this error when tractor looks for combine.
ZZZ_courseplay/combines.lua:6: bad argument #1 to 'pairs' (table expected, got nil)

Trying to run chopper mode. 
I downloaded CombineUnloadAIDriver alpha branch and unzipped and re-zipped files and renamed ZZZ_courseplay and replaced the current developer version.
I have tried with mods and without any mods loaded but courseplay and map.
I have also tried 3 different choppers- New Holland and both Krone's. 
Guessing I got something wrong on my end as I can't find any other issues on git like this.
[log_CombinesLUA.txt](https://github.com/Courseplay/courseplay/files/3844373/log_CombinesLUA.txt)

I have also taken all mods out but courseplay and map, still with same issue.
[log.txt](https://github.com/Courseplay/courseplay/files/3844408/log.txt)

**Comment by jhomer** [comment]
I think I figured out what the issue was.
I had 3 combined courses for the unload course.
Always in the past I would load the courses in order using the first folder icon which had always worked with the current developer version but with trying the alpha version, I first loaded the courses the same way, but then tried loading the courses with the second folder icon "append at end". Which this took care of the above problem.

**Comment by Tensuko** [comment]
There is nothing changed in loading the course.
Always add them with the +Folder.

What you got to do is set the Combine to unload in the new Mode2 HUD Page.
You will see a list of Combines and you got to tick one.

It is Alpha for a reason, so nothing is 100% finished there :)

**Comment by jhomer** [comment]
Ok. Yeah I didn't have any issues of getting that error after I loaded them using the +Folder and no trouble finding combine so all should be good, no issues. I got the error every time when the tractor got to course end in field when loading the courses the other way. I guess I was doing it wrong in the past with using the first folder icon but just got lucky with having no issues.

Thanks!

**Comment by badfly** [comment]
Good day! I got the same problem, only my game crashed.
[log.txt](https://github.com/Courseplay/courseplay/files/3854083/log.txt)

**Comment by Tensuko** [comment]
#5272
