### ISSUE TITLE
Mode 2 - Waiting point of worker is of the field + aligning before unloading

### ISSUE THREAD

**Issue by Veraseca** [Courseplay/courseplay#4569]
Hello,

I noticed twoissue during the unloading of the combine. 

1. The waiting position of the worker that unloads the combine after a first unload is not on the field and creates opportunities for colliding with fences, trees, ....
2. Aligning with the combine (on smaller fields) is troubling, if the combines turns for a full turn (no corner), the co-worker that unload the combine crashes in the combine or gets of the field colliding with trees, ....

I know you are fixing the mode 2, is this part of the fix and if yes, what is the status on the new mode 2?

Thanks a lot!

**Comment by Tensuko** [comment]
#3311 #4286 <- check this and try the new mode2 in alpha branch.
Closed.
