### ISSUE TITLE
Course generation enhancement

### ISSUE THREAD

**Issue by Mr-Cake** [Courseplay/courseplay#4570]
The course generator loves to put the reduced/odd width pass at the start (example below), usually the longest pass. With the settings in the screenshot switching to automatic moves it to the last pass. I kept running into it so in different places thought it could be improved. 

![image](https://user-images.githubusercontent.com/8469644/68942614-ebb00580-080d-11ea-914e-3b1c1202a5ea.png)

**Comment by Tensuko** [comment]
You mean the overlaping up/down part should be at the end.
Well, sometimes it is the case, I am not sure how and when coursegenerate does it.

**Comment by Mr-Cake** [comment]
Yep. It might be calculating backwards from the finish depending on what settings you give it.

**Comment by Dajoor** [comment]
It should be at the end, and it should be optional. I find that often the large equipment are unable to make the short turn, then either do crop circles, or drives off to a point beyond the map. I would rather have it as an option, then do it myself at the end.

**Comment by Tensuko** [comment]
That is not a question of an option, it is the way it calculates...

**Comment by KCHARRO** [comment]
When this happens I will change the working width + - 0.1-0.2 until it generates an even course without overlapping, what you can do is give it much + of the width so that the head does not leave parts of crops.

And the circular mode works perfectly, you can use it ...

**Comment by Mr-Cake** [comment]
Yes I play with the width as well, but when you sprayer is 48.5m wide and you have something like 5m it would be good to just ignore it. If we could edit the course and delete points off the end until its gone would be great. 

Being able to set the with above 50m inside the course generator would be helpful as well.
