### ISSUE TITLE
Tractor Won't Stop Bashing into Combine

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#4571]
It doesn't matter if I use a Giants map or a mod. It doesn't matter if I use mod equipment. Trying to empty the combine (especially on a headland) is bad. I am having to untangle the combine and tractor multiple times on a field's harvesting. Please see the video here: https://www.youtube.com/watch?v=KFKUXlHYPfA
[log.txt](https://github.com/Courseplay/courseplay/files/3852793/log.txt)

CP Version: 6.01.00335
Map: Lone Oak Farm
Combine and tractor are from modhub. I've attached my log as well.

**Comment by Gibbanator** [comment]
:( I believe the is the biggest issue being worked on.

**Comment by Tensuko** [comment]
#3311 and again take a look at #4286 
Closed.
