### ISSUE TITLE
Auto Drive Ordner

### ISSUE THREAD

**Issue by katerhinz** [Courseplay/courseplay#4574]
Ich benutze die neueste Version AD. Bisher konnte ich neue Ordner erstellen und neue Ziele in die jeweiligen Ordner verschieben. Das ist jetzt vorbei. Ordner existieren noch, aber z.B. ein Ziel, welches im Standartordner ist, kann nicht in den vorgesehenen Ordner für ein solches Ziel verschoben werden. Liegt das an mir oder einem fehlenden Update oder wo sind die Gründe? Kann ich Hilfe oder einen Hinweis bekommen. Danke in voraus

**Comment by RalfGorden** [comment]
du musst AD Editor anhaben dann geht es

**Comment by Tensuko** [comment]
Ha ? Kann mir das mal wer genauer erklären ?
Ich kann meine Kurs verschieben und Ordner erstellen wie ich Lustig bin, was hat das mit AD zu tun ?

**Comment by katerhinz** [comment]
Hallo RalfGorden, Klar, der Editor ist an, geht ja nur dann, aber normalerweise ist oberhalb des Standartordners immer das Kreuz um einen Ordner hinzuzufügen und wenn ich dann innerhalb der Ordner ein Ziel ausgewählt habe, kann ich dann das Ziel auch verschieben. Geht aber nicht mehr, bzw. die entsprechenden Symbole sind gar nicht mehr da???
Hallo Tensuko, mein Problem betrifft nur AutoDrive

**Comment by Tensuko** [comment]
Dann besprecht sowas bitte auch im AutoDrive GitHub
