### ISSUE TITLE
Worker skips waypoints - possible bug ?

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#4575]
Take a look at video.
https://youtu.be/-FbHLr8k2Lo
Worker skips from 345 to 426 waypoint.
This started to happens few days ago and it happens only when using baler, i tried to use seeder or cultivator on this same course and they will follow waypoints without skipping.
So, issue is with baler in mode6, started to happens recently, like 5-10 days ago, before that it was working nice.
Do you need some logs ?

**Comment by bojanh66** [comment]
It seems AI Turn maneuver in advanced settings is causing this issue (ive disabled it for now and im still testing)
Once i disabled it, tractor with baler doesnt skip waypoints and turns much nicer from one to another row.
What is that option anyway, what does it do ?

**Comment by Tensuko** [comment]
That is that the AI take over for the turn. It can handel 3-point tools better @pvaiko told me, can turn in smaler areas and stuff. But a logfile is always nice to have and in this case I think 9 12 and 14 isn't wrong :)

**Comment by bojanh66** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3854843/log.txt)

**Comment by pvaiko** [comment]
This isn't due to the baler I think, this can happen with any towed implement when the headland isn't close to perpendicular to the rows.

Just don't use AI turns for now.

**Comment by Tensuko** [comment]
Can you test it again with V341+ and report ?

**Comment by bojanh66** [comment]
Yea, ive forgot to report back, it works without an issue now.
But IMO, i think worker turns better from row to row with this option Disabled.
At least, i like it more, its smoother and more rounded turn.

**Comment by Tensuko** [comment]
So this is fixed.
Closed.
