### ISSUE TITLE
Harvester drives away from field

### ISSUE THREAD

**Issue by Woife1** [Courseplay/courseplay#4577]
The harvester did not allways follow the waypoints maybe this is coused by some CP-Drivers turning at the same time
here is a video for this issue: https://youtu.be/lq3LprXgQBw

i shorten the log couse it is really a big wall of text original 3.946 KB
[log.txt](https://github.com/Courseplay/courseplay/files/3854726/log.txt)

i hope i get all relevant debug-channels 
the harvester is an John Deere S790 edited by Onkel Yogi and the Drapper from him (i hate this extreme short repairintervall)

**Comment by Tensuko** [comment]
Does this happen with Vanilla Combine ?

**Comment by Woife1** [comment]
I try to test it tomorrow

**Comment by betrox007** [comment]
> Does this happen with Vanilla Combine ?

i get this problem too with vanilla combine, but not often,this morning happen to FR780,  https://www.youtube.com/watch?v=lW5lnWKw7GA at minute 1:42

**Comment by Woife1** [comment]
Maybe a solution/work around could be if driver didn't reach next waypoint in 10 secs (or up to 1 min) he stops and write a warning that he is blocked or so
and what i forgot if he is away from course and drives against a tree or so he didn't write that he is blocked
