### ISSUE TITLE
Rückwärts abladen

### ISSUE THREAD

**Issue by RK54** [Courseplay/courseplay#4578]
ich benutze die CP Version 6.01.00335, auf der Saxonia von FalPos.
Von der map habe ich noch ältere Kurse, die einwandfrei funktionieren.
Auf dem Hof gibt es 3 Lager, Dünger, Saatgut und Kalk.
Dünger und Kalk werden problemlos bedient, so wie der Kurs eingefahren ist.
Der mittlere Kurs, Saatgut, bringt mich zum Verzweifeln, klappt einfach nicht.
Denke nicht dass ich es verlernt habe Kurse einzufahren.
Das erste Bild ist Saatgut, er bleibt stehen weil er die Abladestelle erreicht hat, das wars dann.
Als Vergleich habe ich die beiden anderen Kurse mit geladen, da ist zu sehen, dass alles Kurse gleich sind, links und rechts die Kurse funktionieren einwandfrei, die Mitte nicht.
Wäre schön wenn Euch dazu was einfallen würde, ich bin mit meinem Latain am Ende.
Gruß RK54
![1](https://user-images.githubusercontent.com/54204656/69000270-288f0180-08cd-11ea-9913-9522cb99d42c.jpg)
![2](https://user-images.githubusercontent.com/54204656/69000275-30e73c80-08cd-11ea-8068-4dc3b2395ae2.jpg)

**Comment by Tensuko** [comment]
Was ich immer nicht verstehe ist, warum alle einen Wartepunkt setzen.
Für Mode1 wird keiner gebraucht, entweder der trigger wird erreicht und erkannt oder nicht, da nützt auch ein Wartepunkt nicht.
Kannst ja testweise mal den Kurs in der XML öffnen und den Eintrag für Wartepunkt entfernen (solltest du erkennen). Ansonsten logfile mit channel 1 und 2 anhängen, da könnte man was erkennen. Benutzt du für alle Kurse den gleichen Anhänger ?

**Comment by RK54** [comment]
moin Tensuko,
ich nutze CP seit es den gibt, ich, seit LS 09.
Irgendwann konnte man Rückwärts fahren, der Kurs wurde nur mit Schlepper solo eingefahren.
An der Abladestelle wurde ein Wartepunkt gesetzt, usw. Seitdem mache ich das so, und bei den beiden Äußeren klappt es ja einwandfrei.
Zu meiner Schande muss ich gestehen dass ich mich nie mit dem Innenleben von CP befasst habe, und aus dem Grund mit Logfile Channel 1 und 2 nicht anzufangen weiß.
Wass ich gefunden habe, kann man im Bild erkennen, 57, 58, 59 sind die 3 Lager.
In der 58 sehen die Eintrage anders aus als in den anderen beiden, vielleicht hilft Dir das weiter.
Bevor ich nach Hilfe schreie, teste ich erst mal verschiedene Fahrzeuge, dort klappt es mit keinem. Bei den anderen beiden kann ich mit allen Fahrzeugen entladen, selbst mit einem Sattel.
Gruß RK54
![3](https://user-images.githubusercontent.com/54204656/69005184-a92a1e00-091e-11ea-920a-354c0ebb1b48.jpg)

**Comment by RK54** [comment]
halloTensuko,
ich versuche mal für die 58 mit den Einstellungen von 57 und 59 zu verwenden, nur mal so aus Blödsinn, mal sehen was passiert

Gruß RK54

**Comment by Tensuko** [comment]
Tja und ich fahre alle meine Kurse ohne Wartepunkt und habe keine Probleme...
Wie gesagt, Trigger wird erkannt oder nicht, ein Wartepunkt (wie du siehst) hat nichts damit zu tun.

Channel 1 und 2 an und dann den CP fahrer fahren lassen, dann hast du einträge in der log und die posten.

**Comment by RK54** [comment]
halloTensuko,
die Änderung am Kurs hat nichts gebracht, also gelöscht das Teil.
Habe dann den Kurs neu eingefahren, 3 mal, hatte 2 mal wieder den P gesetzt, und Du wirst es nicht glauben, es geht auch ohne Wartepunkt, warum auch immer. Ich danke Dir für Deine Hilfe, und habe wieder was gelernt.
Hat jetzt zwar nicht unbedngt mit dem Rückwärts fahren zu tun, aber mit dem Abladen.
Kann man die Wartezeit nach dem Abladen verkürzen?
Du weißt, meine devise lautet, hoch lebe die Arbeit, aber so hoch dass ich nicht dran komme.
Bei allen Schiebewand Wagen fällt das extrem auf, Fahrzeug entlädt, Klappe geht zu, Wand fährt zurück. Das dauert eine Ewigkeit, und dann fährt er erst los, hinten bildet sich ein Stau wie auf der Autobahn. Früher war der Anhänger leer, und CP ist los gefahren, hat im wegfahren die Klappe geschlossen und die Wand zurück gefahren.

Gruß RK54

**Comment by Tensuko** [comment]
Das lässt sich so erstmal nicht verkürzen. Die Wartezeit kam daher, dass viele mit Kipper abgeladen haben und in einer Scheune standen, dann mit dem hochgefahrenen kipper am Tor hängen blieben :)
Du siehst je nach Situation gibt es bestimmte Wünsche. Ob man Kippen/Schieben unterscheiden kann und ob das dann auch gemacht wird, steht aktuell in den Sternen :)

**Comment by RK54** [comment]
alles klar, weiß ich Bescheid.
Ich danke Dir für die Hilfen und Antworte, und die Zeit die Du heute wieder an einen alten Knagger verwendet hast.
Schönen Restsonntag noch

Gruß RK54

**Comment by Tensuko** [comment]
Gerne doch, wünsche ich dir auch!
Aber verrate mir noch kurz, ob du jetzt Saatgut abladen kannst in dein Lager oder nicht ? :)

**Comment by RK54** [comment]
hast Du bestimmt überlesen. 
Weil ich nicht aufgepasst habe musste ich den Kurs 3 mal einfahren, aus Gewohnheit hatte ich 2 mal einen P gesetzt.
Dann eingefahren ohne P, und es geht einwandfrei, auch ohen Wartepunkt.
Steht in der 4. Antworten vor Deiner letzten.
In der habe ich nach der Wartezeit gefragt

Gruß RK54

**Comment by Tensuko** [comment]
Ah ok es bezog sich also darauf, das war mir nicht ganz klar, alles klar super dann klappt es ja nun :)
Closed.
