### ISSUE TITLE
1050 (#2) : work tools need to be refilled

### ISSUE THREAD

**Issue by PruneMyGoone** [Courseplay/courseplay#4579]

**Comment by PruneMyGoone** [comment]
I am trying to sow a field but it keeps saying I need to fill the tool
I am using the Fendt 1050 tractor with an Agribumper and the Amazone Condor 15001 sower

**Comment by PruneMyGoone** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3855564/log.txt)
Using V 6.01

**Comment by Tensuko** [comment]
Update to 335 https://github.com/Courseplay/courseplay/releases
and I guess you don't have fertilizer in your machine, then just turn off fertilizer in the CP HUD.

**Comment by PruneMyGoone** [comment]
Will give feedback in few minutes 
Let me test it

**Comment by PruneMyGoone** [comment]
Works perfect thanks
Think it is a dumb issue from my side
