### ISSUE TITLE
Neue Mode 2

### ISSUE THREAD

**Issue by Reiko40** [Courseplay/courseplay#4580]
Hallo mich interesiert mal wie weit ihr mit dem neuen Mode 2 seit.

**Comment by Tensuko** [comment]
Siehe #4286 
Closed.

**Comment by Merrlin** [comment]
Die Mode2Alpha kann man sich zum testen runterladen...da kannst du es selbst erfahren.
Nachdem das aber noch eine Alpha ist werden auch Debugdinge angezeigt und es kann nicht ausgeschlossen werden das Frucht oder Babypandas gekillt werden.
Hier gibt's auch irgendwo ein Statement dazu.

**Comment by Tensuko** [comment]
> und es kann nicht ausgeschlossen werden das Frucht oder Babypandas gekillt werden.

Desshalb fahre ich nur auf abgesperrten Gelände ;)
