### ISSUE TITLE
Loading Issues

### ISSUE THREAD

**Issue by Reifenwilli** [Courseplay/courseplay#4582]
Hi everyone,

I´ve got a Problem while loading a savegame... with Version 6.01.00335.
It´s loading endless. Could only exit via closing the task manually.

Got this message in log file: C:/Users/.../Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/course_management.lua:1714: attempt to call method 'GetAvailableDestinations' (a nil value)

[log.txt](https://github.com/Courseplay/courseplay/files/3855973/log.txt)

Any ideas?
Regards Reifenwilli

**Comment by Tensuko** [comment]
Update AutoDrive from AutoDrive GitHub
Closed.
