### ISSUE TITLE
Fronttank of Seeders doesn't open lid and refill on any seed source (bigbag and silo)

### ISSUE THREAD

**Issue by ibeXedi** [Courseplay/courseplay#4584]
Hello,
Im using default vehicles on Hof Bergmann.
Here he wants to refill:
![Farming Simulator 19 Screenshot 2019 11 17 - 22 01 52 60](https://user-images.githubusercontent.com/57322815/69014123-32753b00-0987-11ea-8a6c-fc397a786d4d.png)

I made a video to simplify things:
https://youtu.be/kE9wtodw2ow

Versions:
CP: 6.01.00335
GC: 1.1.3.0

**Comment by Tensuko** [comment]
Not sure but the Error happens very early, is it possible that you hit an other trigger from the pig shed ? You can see them by press F5.

If thats not the case, it could be the custom silo from the map.

**Comment by Merrlin** [comment]
Hmm Strange... There is just a trigger for liquid slurry... It looks like the game crashes when the collision box hits the trigger. The trigger is quite at the position where the tractor hits the wall

**Comment by Tensuko** [comment]
What Version of the Map do you play ? Or does the Silo print chang based on what you fill in it ? I haven't used that one yet, but play on same Map in Version 1.0.0.4  :)

**Comment by Tensuko** [comment]
Well, there are some Problems with this....
1st, I made a testcourse with avoiding other triggers and had no LUA Errors that way.
I will make a test when run thrue the Triggers next to the pig shed. (there are some triggers on your route).
2nd problem was, that the refill is not a normal trigger as you think.
It didn't reload, but as soon as your manualy drive under it, the lids won't open by self (normaly they do when got something to fill up near) and when you open them, the seed will flow automatically. So this is no Trigger that need actions like selltriggers.
2 Things that would need to be done: Open the Lids and wait while get loaded (wich is still that needs to be done for refill manualy on field...). For the Lids not sure if there is a solution for it.

I can just suggest you for now, the get a Mod Silo for seed, there are some smal good one arround wich works :)

**Comment by ibeXedi** [comment]
Thanks for responding but my driver just dont want to refill his seeder.
On the video you can see at 0:23 (https://youtu.be/kE9wtodw2ow?t=23) 2 Pickups, 1 with the normal seed pallet and 1 with the Hof Bergman BigPack or whatever. I had another course loaded before where the guy drives directly next to the guys and he just passes them :/

**Comment by Tensuko** [comment]
I must say I never tried to refill next to a bigpack... Not sure if CP can see the kind of trigger area.

**Comment by ibeXedi** [comment]
The bigpacks should work and they work but not always.
I thought maybe its the seeder so I tested a bunch: https://youtu.be/z6WtZs1gBrw

Amazone D8 30: https://youtu.be/z6WtZs1gBrw
TF 1512 + BTF 4000: https://youtu.be/z6WtZs1gBrw?t=20
Maestro 12 SW: https://youtu.be/z6WtZs1gBrw?t=35
FH 2200 + Tempo V 8: This one is interesting because the seeder itself has a tank so sometimes it works sometimes it dont. 
Looks like the tank is buged aswell not only the silo.

**Comment by ibeXedi** [comment]
It seems to be not just some refillproblem because you cant even refill some seeders with the normal seeds you can buy I mean that makes the use of CP completly useless :S 

https://youtu.be/fGZjpfIx_WA

0:47 without fertilizer
2:26 with fertilizer

**Comment by Tensuko** [comment]
Completly useless ? Ok then seed the Field on your own... I don't think you want to do this ;)
Actually I can refill my seeders...
I will make a testsave and see if I find out whats wrong...

**Comment by Tensuko** [comment]
For Sugarcane you need special seed as far as I know. There is a special seed tank for sugarcane. Not sure if can refill on normal seed manualy. Basically you use sugarcane leftovers to plant new one.... Also check the refilltype on the CP Hud Page.

**Comment by Tensuko** [comment]
For the Sugarcane seeder, switch to seed in the refill HUD Menu. That works!

For the Seeders in general, it seems to be only a FrontTank Problem.
So it is not a Problem of BigBag.

**Comment by ibeXedi** [comment]
> For the Sugarcane seeder, switch to seed in the refill HUD Menu. That works!
> 
> For the Seeders in general, it seems to be only a FrontTank Problem.
> So it is not a Problem of BigBag.
> 
> [log.txt](https://github.com/Courseplay/courseplay/files/3896430/log.txt)

Hello,

so the Sugarcane seeder works when you put it on seed and not sugarcane ^^

Sorry I was just pissed of that nothings works I was trying to do.
Thanks for responding I appreciate your work it makes it even possible to move more than 1 vehicle effectivly.

**Comment by Tensuko** [comment]
Close this to get to a newer Issue with actual Version.  #5377
