### ISSUE TITLE
Unloading in field mode 

### ISSUE THREAD

**Issue by penuiel** [Courseplay/courseplay#4587]
Whenever I make a course where a loading wagon needs to unload at the either the hay loft or silage silo it will not work. There is no “tip trigger reached” notification. It can unload as intended in Combi mode

**Comment by Tensuko** [comment]
Logfile with channel 1 and 2 active then let it run the course.
Also: What tool, what silo.

**Comment by penuiel** [comment]
I’ll get back with the log file. It’s both the gay loft from the original game and the original medium double bunker silos

**Comment by penuiel** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3874586/log.txt)
The log file is attached with debug channel 1 and 2 active running the course, collecting hay and going back to the hayloft.

**Comment by GeorgeEarslight** [comment]
> [log.txt](https://github.com/Courseplay/courseplay/files/3874586/log.txt)
> The log file is attached with debug channel 1 and 2 active running the course, collecting hay and going back to the hayloft.
> The tool is the Strautmann ZELON CFS 2501 DO (the smallest loading wagon)

Did you by any chance have Silage in the wagon?

**Comment by Tensuko** [comment]
Pls make sure you modsfolder is clean (just a sidenote....):
Error: Invalid mod name 'Ny mappe'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Error: Invalid mod name 'Ny mappe (2)'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Error: Failed to open xml file 'C:/Users/caspe/Documents/My Games/FarmingSimulator2019/mods/savegame2/modDesc.xml'.
Load mod: savegame2
Error: Missing descVersion attribute in mod savegame2

Its kinda clear what happens here:
2019-11-21 13:09 :35 [dbg1 lp163000]     trailerFillType=24 **SILAGE**
2019-11-21 13:09 :35 [dbg1 lp163000]     **trigger** (114293) **does not accept trailerFillType** (24)
2019-11-21 13:09 :35 [dbg1 lp163000]     trigger (114293) **acceptedFillTypes**:
2019-11-21 13:09     31: **STRAW**
2019-11-21 13:09     30: **DRYGRASS_WINDROW**

**Comment by penuiel** [comment]
Thanks for the answer. The wagon was loaded with hay at the time

Sendt fra min iPhone

**Comment by penuiel** [comment]
Thanks again for the quick reply :) So if I understand that correctly, the log file says the loader contain silage, and not hay. I am sure I loaded it with hay. I have the same problem when loading grass and trying to unload it at the bunker silo. Could it be something with seasons mod conflicting with the filltypes? Am I supposed to make a waitpoint before the unload point to make the trailer unload? 

Sendt fra min iPhone

**Comment by Tensuko** [comment]
Waipoint does nothing in that case..
Why all ppl think a waitpoint is the way to go... Stop spread that nonsence... Trigger is Trigger and right filltype is always needed...
Unloading into bunker silo have problem when use Mode2 or the general Giants Issue that there is like 2 liters left but game says 0, this happens also when unloading manualy.

**Comment by penuiel** [comment]
I saw a video tutorial on YouTube where the guy put a waitpoint in front of the bunker silo. When I tested using the bunker silo, it was “brand new”. I will try again and provide a new log file. Thanks again for the info

Sendt fra min iPhone

**Comment by Tensuko** [comment]
You only need waitpoints at Silo for Mode9 and Mode10. Not for unloading...

**Comment by penuiel** [comment]
But I still don’t understand why it can unload if I change the mode to Combi. Shouldn’t it give the same fill type error?

Sendt fra min iPhone

**Comment by Tensuko** [comment]
Mode2 use the old Driver, can make a lot of trouble.

**Comment by penuiel** [comment]
After your comments I realized the tractor i was using was also mounted with a front loader with some silage in it - which caused the log as you correctly say. After unmounting the front loader it works amazing :D - both unloading at the hayloft and in the bunker silo :)
A thousand thanks :D and all the best
