### ISSUE TITLE
Tractor doesn't drive to combine

### ISSUE THREAD

**Issue by Michael9220** [Courseplay/courseplay#4588]
The tractor doesn't drive to combine unless I actually sit in the combine. Both tractor and combine are set up with courseplay. The tractor is set to drive to combine at 70% full, but when the combine hits 70%, nothing happens, unless I sit in the combine. If I sit in the combine, the tractor will drive to the combine at exactly 70%. 

I've attached the log and it looks fine. No other maps added other than the DLCs and the courseplay mod.

[log.txt](https://github.com/Courseplay/courseplay/files/3870842/log.txt)

**Comment by Tensuko** [comment]
#3311 #4286 
Closed
