### ISSUE TITLE
Behind the combine?

### ISSUE THREAD

**Issue by Meizter** [Courseplay/courseplay#4589]
Hello! How do you make the trailer drives behind the combiner? I can only use automatic, right and left. I use a claas jaguar from the dlc that cuts chaff from corn and a claas tractor with claas trailer :)

Thnx for help!

**Comment by Tensuko** [comment]
See #4286 it is Mode2 Alpha Version.
Closed.

**Comment by Meizter** [comment]
I cant find it there! :/
