### ISSUE TITLE
Suggestion: Mode2

### ISSUE THREAD

**Issue by KCHARRO** [Courseplay/courseplay#4590]
I believe that if it is possible to make the aiDriver can surround the crops again, collisions between Driver and Harvester would be avoided, since when going on a front approach course, the driver creates a direct route without avoiding crops and crashes head on With the harvester. I don't care if it takes a little longer to circle the entire field, even if it's big.

This option even if enabled does not work.

**Comment by Tensuko** [comment]
#3311 #4286 look it up....
Closed.
