### ISSUE TITLE
Error: Running LUA method 'update'. - Plow.lua(680) : attempt to compare number with nil

### ISSUE THREAD

**Issue by Kn1ghtwolf** [Courseplay/courseplay#4591]
This is all I get when I try to plow regardless of ingame plow or modded plow but I never used to have this issue until the recent updates. and it just repeats over and over until I stop courseplay from running

**Comment by pvaiko** [comment]
#4240 ?

**Comment by Tensuko** [comment]
Check #4240 and Update your FollowMe to newest Version or try without it.
If anything more, pls let us know.

**Comment by gidadavid** [comment]
Had the same issue... tried it withoud the FollowMe and it worked

**Comment by Kn1ghtwolf** [comment]
That was the problem thank you!
