### ISSUE TITLE
Courseplay with Autodrive

### ISSUE THREAD

**Issue by Siryes** [Courseplay/courseplay#4592]
AutoDrive with courseplay, pressing tab key spawns you under map

**Comment by Merrlin** [comment]
Correct Description and logfile pleas

**Comment by Tensuko** [comment]
Without a logfile we cant do anything here and since your are the only one with this Issue so far I can already say you will have a Modconflict or not the actual Version of something...

**Comment by Siryes** [comment]
Only Two Mods installed Courseplay and Autodrive.
Steps to reproduce:

Load Map, Turn off Switch Trains, Buy Tractor, Reset Tractor , Press Tab Key 
You are now under the map. 
This will happen on every Map no matter if Modded map or just Default map.


Here is the log file: 
[FS19-Spawn.txt](https://github.com/Courseplay/courseplay/files/3882630/FS19-Spawn.txt)

**Comment by Tensuko** [comment]
Load mod: FS19_AutoDrive (Version: 1.0.1.9) (Hash: 6b9cce8e25592c84cecb0b5c475b348f)
You got a super old AutoDrive Version.
Get the new one from AutoDrive GitHub.

And this I got no Idea from where that Error comes, but never seen it before:
2019-11-23 10:30 Error: Running LUA method 'update'.
2019-11-23 10:30 dataS/scripts/BaseMission.lua(1881) : attempt to index field 'controlledVehicle' (a nil value)

**Comment by Siryes** [comment]
That Version of AutoDrive is the current version up on ModHub

**Comment by Tensuko** [comment]
I tell you this only ince mire: your AutoDrive is old and you need a newer version! Get it from AutoDrive github!

**Comment by Siryes** [comment]
Yes I did use the Newest github autodrive, but it is showing " needs update " in game and does not load unless you update it, not sure you understand how modhub / update works

**Comment by Tensuko** [comment]
No, you don't understand how ModHub Update works, it checks for the HASH Value, not for the Version.
AutoDrive on ModHub is 1.0.1.9 and GitHub is 1.0.6.9 now you want to tell me ModHub knows better what is the newest Version ?
https://github.com/Stephan-S/FS19_AutoDrive/releases

This Error shows me you got the old Version and need Update couse AD gets something that CP need in a later Version:
2019-11-23 10:29 Error: Running LUA method 'loadSharedI3DFileFinished'.
2019-11-23 10:29 C:/Users/Dappe/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay/course_management.lua:1714: attempt to call method 'GetAvailableDestinations' (a nil value)

Also for that other Error you should consider reinstall your game, as this Error seems to come from Basegame:
2019-11-23 10:30 Error: Running LUA method 'update'.
2019-11-23 10:30 dataS/scripts/BaseMission.lua(1881) : attempt to index field 'controlledVehicle' (a nil value)

And if your savegame doesn't load with new AD Version, you modified something or it is a AD Problem, wich need a logfile too.

**Comment by Siryes** [comment]
Starting a fresh install now! Thank you for information and your time. Will update

**Comment by Siryes** [comment]
After fresh install Everything working great! 
Since FS13 have never had such a strange corruption of my file.


Very sorry to have taken your time , ty for input.

**Comment by Tensuko** [comment]
Np. Yw.
Closed.
