### ISSUE TITLE
LUA call stack. LS hängt sich auf.

### ISSUE THREAD

**Issue by Farmer-Bene** [Courseplay/courseplay#4594]
Switche ich zu dem Fahrzeug, welches von CP gesteuert wird, kommt es wieder und wieder zu diesem Fehler. Egal ob mit TAB, zu Fuß oder über die Karte. Dabei ist mindestens 1 Helfer von CP aktiv. Es kommt bei allen Fahrzeug vor! Ich spiele mit XBOX 360 Controller.
[log.txt](https://github.com/Courseplay/courseplay/files/3877255/log.txt)

Danke für Ihre Mühen

**Comment by pvaiko** [comment]
Glaube nicht dass es ein Courseplay Problem ist, du hast viel zu viele Mod Fehlermeldungen, vor allem der fs19_fendtvario800 scheint problematisch.

**Comment by Tensuko** [comment]
Bring deine Mods in Ordnung dann probiere es nochmal.

**Comment by Farmer-Bene** [comment]
Nun habe ich alles was Error oder Warning entfernt. Nach wie vor bleibt das Spiel stehen, wenn ich in ein Fahrzeug steige was grade von CP gesteuert wird! Was kann ich nun noch machen, woran könnte das liegen?
[log.txt](https://github.com/Courseplay/courseplay/files/3880898/log.txt)

**Comment by Tensuko** [comment]
Es wird eine Mod sein die ein Konflikt hat, welche musst du raus finden da können wir dir nicht helfen außer durch Erfahrung durch andere User

**Comment by pvaiko** [comment]
Das ist nicht einmal ein CP Fehler.
