### ISSUE TITLE
Phoenix 6x6 Agro-Truck	drive side ofset

### ISSUE THREAD

**Issue by WM3x** [Courseplay/courseplay#4595]
Hello all, after some playing the game I find out, that truck have waypoints aimed in the drivers seat on the left side, what is causing that driving courses made with tractors not working because truck is driving same course with side ofset. It is possible to use middle of the vehicle instead of the driver position to drive course?

**Comment by Tensuko** [comment]
Thats a Giants Problem.
When you turn on debugchannel, I think it was 12, you see a yellow dot, thats where cp creates and drives the course with. I got no Idea why the Giants Trucks have them on the Side, but we can't do much about that. You could try the offset settings.

**Comment by mricher-git** [comment]
Old but in case someone is looking or cares, as I did....
The issue is here:
            <ackermannSteering rotSpeed="40" rotMax="30" rotCenterWheel1="3" rotCenterWheel2="3" />

Both wheel 1 and 2 are set to the left middle wheel. Should be
            <ackermannSteering rotSpeed="40" rotMax="30" rotCenterWheel1="3" rotCenterWheel2="**4**" />
