### ISSUE TITLE
liquid transporters dont stop at loading point 

### ISSUE THREAD

**Issue by Murtlock** [Courseplay/courseplay#4596]
Hi,i play NFMarsch 2.6 where i use a water trailer to load water for my sugar factory.
It only does not work for water trailers the others are fine; it does not stop at the water tank trigger to load, it just moves on.

**Comment by Tensuko** [comment]
For normal Transport use Mode1 ( we should rename Mode8...) and the 1st and Endpoint should be straight to each other

**Comment by Tensuko** [comment]
You can also post a screenshot of your loading position.

**Comment by Murtlock** [comment]
Hi baie dankie :) thanks alot it works now
