### ISSUE TITLE
Almost 70 seconds to load CP

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4597]
I have FS19 1.5.1 installed on a dual SSD raid0 drive (1 GB/s throughput). 
I have some mods, including CP and AD.
However, when CP is **activated**, the game takes **90 seconds** to load!
And when CP is **deactivated**, it takes only **19 seconds**.
Why CP take to long to load? 

[log.txt](https://github.com/Courseplay/courseplay/files/3879845/log.txt)

**Comment by Merrlin** [comment]
Maybe you have Load courses on Startup activated. The setting is found in the advanced settings

**Comment by rogeriodec** [comment]
In fact, deactivating Load Coursed on Startup solved the problem.
The loading time of CP was reduced to almost zero!
Thank you!

Now, what is this option for?

**Comment by Tensuko** [comment]
Load the Course on start or load them when you click on the actual course....
Or in other words: Load course when you need them (load from the list in the HUD)
Closed.

**Comment by rogeriodec** [comment]
Thanks.
