### ISSUE TITLE
Suggestion - Pöttinger Novacat A10 Cross Flow - extendable working width

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#4598]
This mower has working width of 10m, but only if we manually extend it with mouse.
https://farming-simulator.com/mod.php?mod_id=135535

Sometimes i forget to extend it before starting the course, so it stays at default width which is 8.5 or 9m, cant remember.

Is it possible to make CP automatically extend width to 10m when starting the course ?

**Comment by Tensuko** [comment]
CP gets the workwith from the Nodes of the Tool and we won't start to put Tool based adjustments into CP.
You will have to do the same for Sprayer depending on what is filled in (lime or fertilizer).
Closed.
