### ISSUE TITLE
Mode9: Add Unload here Point as option intead 3rd Waitpoint.

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#4601]
Can mode9 be used to clean cows or its mostly for selling at BGA and loading manure into the trailer?
Take a look at video.
Log.txt doesnt give any info about CP when i start or stop course.
Do you need some debug channels ?
https://youtu.be/XDeSmvvwM0c

**Comment by Tensuko** [comment]
Basically yes.
Waitpoint at the start of the area where you want to pick stuff up, waitpoint at the end (this defines the area) then a waitpoint infront ot the unload area.
Video I got to take a look later.

**Comment by Tensuko** [comment]
Looks like the place got no Trigger, since Mode9 looks for a Trigger/Trailer to unload.
I am not sure if can add the Unload-Here-Point as addition to do it like in your video (but would be a nice Idea...)

**Comment by Tensuko** [comment]
Should not be needed, the unload works very good now.
