### ISSUE TITLE
Truck waiting outside the field

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4602]
![image](https://user-images.githubusercontent.com/11199752/69444628-80939100-0d2f-11ea-9f07-d4f3fd2d1500.png)

Many times, when the truck follows the harvester during its unloading, and coincidentally the harvester goes empty near the edge of the field, the truck goes off the field but does not return.
How to fix this?

[log.txt](https://github.com/Courseplay/courseplay/files/3880583/log.txt)

**Comment by Tensuko** [comment]
#3311 #4286 
Closed...
