### ISSUE TITLE
Mit der Courseplay version _6_01_00342  lädt das spiel nicht.

### ISSUE THREAD

**Issue by tim2234** [Courseplay/courseplay#4603]
Wie schon im Titel steht lädt das spiel mir der Version 342 nicht aber mit einer ältern version Courseplay_6_01_00185 schon. Das Spiel lädt und lädt hab mal knapp 15 min laden lassen aber nix passiert.

**Comment by Tensuko** [comment]
Und trotz der langen Wartezeit nichtmal ein logfile angehangen ?!
Wie sollen wir so etwas dazu sagen können ?

**Comment by tim2234** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3884158/log.txt)
Ich glaub nicht das man mit der all zuviel anfangen kann

**Comment by Tensuko** [comment]
Wenn du den Error auch nicht reproduzierst, sprich die V342 drin hast, kann man da auch nichts sehen, außer das du fehlerhafte Mods hast:

Sowas:
Error: Failed to open xml file 'C:/Users/Tim/Documents/My Games/FarmingSimulator2019/mods/Shadermod_FS19_GermanWarrior_V1/modDesc.xml'.
Load mod: Shadermod_FS19_GermanWarrior_V1 (Hash: 6d104be7248f2ae65e5cae1fa9b4dded)
Error: Missing descVersion attribute in mod Shadermod_FS19_GermanWarrior_V1

Oder sowas weil man wieder nicht gelesen hat.....
Error: Failed to open xml file 'C:/Users/Tim/Documents/My Games/FarmingSimulator2019/mods/FS19_tatra_joskin_Pack_Entpacken/modDesc.xml'.
Load mod: FS19_tatra_joskin_Pack_Entpacken (Hash: bc860e172119d4d288a8eb5c2ece3880)
Error: Missing descVersion attribute in mod FS19_tatra_joskin_Pack_Entpacken

**Comment by Tensuko** [comment]
V342 rein, spiel laden, log posten.
Und tip am Rande: Bennenne CP immer FS19_Courseplay damit du keine doppelten CP Versionen drin hast.

**Comment by Tensuko** [comment]
Und wie du siehst geht es, es liegt also an einer deiner Mods oder du hast CP nicht richtig reingepackt, doppelte version oder sonst was, desshalb immer gleich benennen nach dem runterladen, damit sowas nicht passieren kann.
![fsScreen_2019_11_24_22_46_56](https://user-images.githubusercontent.com/27344744/69502172-6a8ef780-0f0c-11ea-86ed-9aaeed8f5224.png)

**Comment by tim2234** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3884216/log.txt)

**Comment by Tensuko** [comment]
2019-11-24 23:12 Error: Running LUA method 'loadSharedI3DFileFinished'.
2019-11-24 23:12 C:/Users/Tim/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/course_management.lua:1714: attempt to call method 'GetAvailableDestinations' (a nil value)

AutoDrive aus AD GitHub laden, neueste Version, dann gehts (ja sowas verrät die log.txt)

**Comment by tim2234** [comment]
Danke jetzt geht wieder alles
