### ISSUE TITLE
End at starting point does not work anymore

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#4604]
DE: Am Startpunkt enden ist aktiviert aber kein fahrzeug fährt zum startpunkt. Wen sie die feldarbeit beenden bleiben sie stehen. Manche kann man per sofort abfahren wegschicken andere wiederum nicht.

EN: End at start point is activated but no vehicle is moving to start point. When you finish the fieldwork you stop. Some can be driven away immediately, others not.

MFG Mannie313

**Comment by Tensuko** [comment]
Geh mal bitte in die Advanced Settings und schalte das dort um, nicht im HUD.
Irgend etwas ist im HUD schief gegangen, mal geht es mal geht es nicht, da scheint eine Überlagerung von funktionen zu sein.
Es ist auch so, wenn ich das im HUD versuche um zu schalten, wird der Feldrand gescannt.

@pvaiko kannst du das aus dem HUD komplett rausnehmen erstmal, oder eine reine Anzeige einbauen, wenn wir die Option im Advanced Settings haben?

**Comment by Mannie313** [comment]
Geh mal bitte in die Advanced Settings und schalte das dort um, nicht im HUD. 
Hab ich dort gemacht. Hilft aber nichts. 

MFG Mannie313

**Comment by pvaiko** [comment]
Das müsste jetzt funktionieren.
