### ISSUE TITLE
Mit CP Rübenmiete anlegen

### ISSUE THREAD

**Issue by ratze68** [Courseplay/courseplay#4606]
Hallo zusammen,

leider kann ich nur in Deutsch schreiben Sorry!

Ich habe folgendes Problem:
Möchte gerne auf Acker eine Rübenmiete anlegen. Klappt alle prima, das abtanken am Roder und zu der stelle wo der abfahrer die Rüben abladen soll. Bis dahin alle ok:

Er fährt bis zu den Haufen rückwärts, fängt das Kippen der Abladevorgang beginnt, fährt etwas vor läd alles ab. Dann fährt er Rückwärts über den Rüben bis zum Ablademakierung. Um dann vorwärts weiter zufahren. Um so größer der Haufen wird um so schlechter kann er abfahren. Und bleibt stecken.
Schauen Sie auf den Fotos:

![20191125153530_1](https://user-images.githubusercontent.com/53152008/69550374-2860c700-0f9b-11ea-974f-f293051ca836.jpg)

![20191125153538_1](https://user-images.githubusercontent.com/53152008/69550405-3e6e8780-0f9b-11ea-9e6b-15badca7fa10.jpg)

![20191125153549_1](https://user-images.githubusercontent.com/53152008/69550407-3f9fb480-0f9b-11ea-8592-b9aa6422caed.jpg)

![20191125153639_1](https://user-images.githubusercontent.com/53152008/69550414-40d0e180-0f9b-11ea-9bcf-fe57c433b295.jpg)

Ich habe viele Standard Fahrzeuge getestet, immer das gleiche Spiel manche verloren die Spur.

Ich benutze Mode2

Lg Stefan

**Comment by Tensuko** [comment]
Das kann gut am Mode2 liegen, der noch den altern Fahrer benutzt.
Man müsste das mal mit Mode1 probieren, sprich die Rüben irgendwo aus einem Trigger abholen und dann eine Miete anlegen.
Muss ich schauen ob das generell ist oder nur den Mode2 betrifft. (was ich leider vermute).

**Comment by ratze68** [comment]
Vielen Dank für eure Arbeit

Vielleicht eine Blöde frage was heißt das genau: "der noch den alten Fahrer benutzt"

Lg Stefan

**Comment by Woife1** [comment]
Der Fahrer von Mode 2 bzw der komplette Mode 2 sind noch vom Anfang der CP 6 Entwicklung.
D.h. es sind einige Fehler darin bzw es funktioniert nicht immer so wie es sollte 

wie oben angepinnt wird am Mode 2 in einer vollkommen neuen Version gearbeitet
wann diese erscheint kann aktuell wohl noch niemand wirklich sagen

**Comment by Tensuko** [comment]
So ist es. Es mangelt einfach an Zeit bei der Entwicklung.
Ich lasse gerade Mode1 laufen um zu sehen, ob das wirklich ein Mode2 Problem, oder ein generelles Problem ist.

**Comment by ratze68** [comment]
Ok Danke,

**Comment by Tensuko** [comment]
Ich hab das mal im Mode1 versucht, ab einer gewissen länge wollt er bei mir auch auf den Haufen fahren, allerdings zum abladen, zumindestens sah das so aus.
Ich hab allerdings meine Teststecke etwas doof angelegt (rückwärts bergauf....)
Aber das er ablädt und dann erst zum ersten Abladepunkt fährt hatte ich nicht, daher Tippe ich mal ganz stark auf Mode2 Issue.
Ich lasse den Issue hier mal auf, bei gelegenheit probiere ich noch mehr aus...

**Comment by ratze68** [comment]
Danke dir!

**Comment by ratze68** [comment]
Hallo zusammen,

Ich habe mal versucht das der Roder zu abladen zubewegen........geht nicht.
Aber, wäre das nicht ein Option, den Roder die Funktion zu abladen zu spendieren?

Lg Stefan

**Comment by Tensuko** [comment]
Die Idee existiert und ist auch geplant, aber die Umsetzung lässt noch auf sich warten :)

**Comment by Tensuko** [comment]
Problem wird hier weiter verfolgt.
Soll am warten auf die Schließen-Animation liegen....
#4534
