### ISSUE TITLE
Mode 4 - Headland issues with 3 fertilizer spreaders

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#4608]
I cannot get a course with 3 fertilizer spreaders to make it around the headland without either or both of the left or right vehicles going completely off course and driving off in a straight line until they crash into something.

it's always on the corners of the headland, and the display says "two intersection points" when the vehicle goes off course.

AI Turns : deactivated
Auto 12m radius

Here is log with 12 & 14 and pics of the Left (inside) vehicle as the vehicle abandons the course and drives off straight towards the trees

https://gist.github.com/sootysax/96b4adc76c766bc194501534f2a27671

![Screenshot 2019-11-25 15 33 30](https://user-images.githubusercontent.com/6591048/69576436-4a0d7e80-0f9a-11ea-8cb3-82ee8817cce5.png)
![Screenshot 2019-11-25 15 33 32](https://user-images.githubusercontent.com/6591048/69576438-4bd74200-0f9a-11ea-8f40-6536003df9a4.png)
![Screenshot 2019-11-25 15 33 34](https://user-images.githubusercontent.com/6591048/69576448-4e399c00-0f9a-11ea-8078-df3776f0eb95.png)
![Screenshot 2019-11-25 15 33 36](https://user-images.githubusercontent.com/6591048/69576453-51348c80-0f9a-11ea-907a-9fa20dbc4ad5.png)

**Comment by pvaiko** [comment]
@sootysax if you keep clicking the eye icon on the top left corner of the HUD the offset course (red line) will eventually appear. Would help a lot a screenshot with that.

**Comment by sootysax** [comment]
![Screenshot 2019-11-25 21 21 37](https://user-images.githubusercontent.com/6591048/69594293-dedba080-0fc9-11ea-8273-8ae320115c42.png)
![Screenshot 2019-11-25 21 21 41](https://user-images.githubusercontent.com/6591048/69594306-f155da00-0fc9-11ea-9695-f6eceb85ecf0.png)
![Screenshot 2019-11-25 21 21 44](https://user-images.githubusercontent.com/6591048/69594315-f581f780-0fc9-11ea-97df-cab3f6f76cd2.png)
![Screenshot 2019-11-25 21 21 47](https://user-images.githubusercontent.com/6591048/69594323-fb77d880-0fc9-11ea-841c-1a290c4f9549.png)

**Comment by sootysax** [comment]
https://gist.github.com/sootysax/27edd9e974817b34d3c8e18ef49efb6b

Heres another example..  3 spreaders.. 1 headland with 'smooth' setting..  30 meter width.. started with headland clockwise.

I didn't get very far onto the headland before hitting one of these points on the outside lane.

Here is a partial log that starts right when I get to the problem point (the log would have been too long to upload)


![Screenshot 2019-11-26 18 34 18](https://user-images.githubusercontent.com/6591048/69681377-e22f6480-107b-11ea-9750-360b18073765.png)
![Screenshot 2019-11-26 18 34 25](https://user-images.githubusercontent.com/6591048/69681393-ed829000-107b-11ea-9fcc-02a9efa65a0e.png)
![Screenshot 2019-11-26 18 34 27](https://user-images.githubusercontent.com/6591048/69681397-f1161700-107b-11ea-8f43-6b4c321ed98b.png)
![Screenshot 2019-11-26 18 34 32](https://user-images.githubusercontent.com/6591048/69681402-f3787100-107b-11ea-9e86-7ee4c24f7037.png)

**Comment by pvaiko** [comment]
Did this started recently, was it working before? If yes which release? 

It is really difficult to tell from these screenshots what's happening, would you have savegame and the course?

(The problem is that the current, naive implementation of the multitools/offset will never work correctly with these working widths on the headland. We will have to use the algorithm in the course generator to generate the headlands for the offset vehicles in this case and I'm sure at some point I'll get it done...)

**Comment by pvaiko** [comment]
Should work with 388, reopen if not.
