### ISSUE TITLE
  bunkersilo?

### ISSUE THREAD

**Issue by evybart** [Courseplay/courseplay#4610]
Is there a prefer for cp what bga bunkersilo that i best use for reverse unloading silage  . The ingame or a mod . Thanks for the great work so far no cp no fs .

**Comment by Tensuko** [comment]
Every Bunker Silo that Sticks to GIANTS Standarts should work for that.
Just keep in mind, that Mode2 works not as good as Mode1 and Mode6 for unloading into a Bunker Silo right now.

**Comment by evybart** [comment]
Mode1 via a overloader or via the farmsilo Bud how do yo mean with mode6 how do you that for the bunker silo mode6 is fieldwork when i am correct

**Comment by Tensuko** [comment]
Mode1 else Load at Start from a Overloader or from a Silo, yes.
Mode6 when collecting Gras with a Loadingtrailer.
Same would be when you Play the Map HofBergmann and collecting Straw from Field, to bring it into a Bunker for Compost, that would be done in Mode6 too :)

**Comment by evybart** [comment]
Ah ok thanks for the reply i was confust by mode 6 for direct from harvester to the bunkersilo Bud i understand what you mean now with mode6 for the mode2 alfa when you Rename  the zip file can we do also fs19courseplay6 use for that or a other name for the zip file

**Comment by Tensuko** [comment]
You can only use Mode2 Alpha Branch or the normal Release.
Both won't work together, but if you want unloading into Bunker Silo with Mode2, the Alpha Version works better, but not perfect yet, as it is still an Alpha Version :)
In that case, I would drive throuh the silo and not unload in reverse, just a little tip ;)

**Comment by evybart** [comment]
Ok thanks 👍
