### ISSUE TITLE
Spreader Starting then Stoping on headland.

### ISSUE THREAD

**Issue by VergylTantor** [Courseplay/courseplay#4611]
If I use Bredal K165 (Vanilla) spreader the fertilizer start working but then fertilizer will stop spreading about 2-3 seconds after starting. It tends to do this if I create the course from current position then pull forward until The tractor is directly under the starting point. I have seen this issue with other spreaders/sprayers. My be related to Issue #4562 

[log.txt](https://github.com/Courseplay/courseplay/files/3892868/log.txt)

**Comment by Tensuko** [comment]
I just used it on my Field, with Lime, no Issue....
Logfile with channel 12 is enough I think, lets see wich waypoint he wants to go.

**Comment by Tensuko** [comment]
Oh and also, how does your course look like ?
On headlands you got to be careful where you start, as it have some waypoints wich are transitions from headland to main part, where the sprayer gets deactivated.

**Comment by VergylTantor** [comment]
I started in the corner as shown in screenshot. I let it move until the dry fertilizer shut off for a short time. Then I repeated from the place that I stopped and repeated this 2-3 times
.
![fsScreen_2019_11_26_12_21_18](https://user-images.githubusercontent.com/39446775/69661776-9d3e0a80-1048-11ea-908d-6d2b104d5413.png)
[log.txt](https://github.com/Courseplay/courseplay/files/3893449/log.txt)

**Comment by Tensuko** [comment]
Yea I think it is happening exact as I thought.
You are might be at the start (under/behind it, wich is failure number one) and after one round Headland, it will go into transition to the up/down row.
But the way you start, it instantly run the transition, where the sprayer is not active.
You should create the course not at the corner, but somewhere on the side of the Field, so you have a more clear course. Or you drive more far back, and say start at the 1st waypoint.

**Comment by VergylTantor** [comment]
Yes, starting at 1st waypoint prevents this from happening. In the end toggling between start a 1st waypoint/nearest waypoint is not a big inconvenience and the only reason I posted this as an issue is that this behavior only started recently, somewhere around ...335. I hesitate to start along the side of the field because in my area (central USA) we grow about 50% row crops and would start planting from the corner if possible.

**Comment by Tensuko** [comment]
Well you can start from corner, but the course generated might not be perfect.
Important is start from 1st waypoint, when got only one Headland.
So this seems solved :)

Closed.
