### ISSUE TITLE
 ## 8970: fixing maxRotation, setting to 29 degrees

### ISSUE THREAD

**Issue by levisbaja** [Courseplay/courseplay#4612]
Hi!

I noticed an issue with same body type trators, like Bud 747, T9, Steiger,  NH 9822, JD 9870:

2019-11-26 22:47 ## 8970: fixing maxRotation, setting to 29 degrees

If I have changed to 30 degrees in XML file, the  error is:

2019-11-26 22:51 ## 8970: fixing maxRotation, setting to 30 degrees

Thanks for your help!

**Comment by Tensuko** [comment]
So... the Issue is what ?
Logfile ?

**Comment by levisbaja** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3895988/log.txt)

**Comment by pvaiko** [comment]
See https://github.com/Courseplay/courseplay/issues/3538#issuecomment-480627888 so if you don't want to see that message you have to change it radians.

Also, this should only come whenever an ArticulatedAxis specialization is loaded when the game starts, for each vehicle. Reopen if you see this after the game is already started.
