### ISSUE TITLE
Question : Tatra Phoenix

### ISSUE THREAD

**Issue by Horozor** [Courseplay/courseplay#4614]
Hello. When recording a route on a Phoenix Tatra truck, points are written on the left side of the truck.
I want to fix this in a giant editor. I think this is due to the truck model (giant bug). The question is, what point is used by the courseplay when recording the route.

![Безымянный](https://user-images.githubusercontent.com/37561569/69814161-4c6f1300-11fc-11ea-9a97-2f08afdc0a44.jpg)

**Comment by Tensuko** [comment]
You can see a yellow dot with channel 12 on.
No Idea what the Node Name is.
@pvaiko sure knows this.

**Comment by Misamangame** [comment]
@Horozor Tatra Phoenix will still go same course you recorded, so it looks offset from the centre like your picture  but any other vehicle (unless it has same bug) will have same course in the middle like it should be. The difference between them something like 1 - 1,5m, but if you record your courses safely they should be usable for Tatra and for other vehicles as well without big problems. But if you find solution for this I hope you will share it here :)

**Comment by Horozor** [comment]
@Misamangame I know how this affects the course and it doesn’t bother me much, I just wanted to fix this problem.
I thought I would find a solution as simple as with Rubicon 9000, there I just changed the width of the collision and now the courseplay does not get stuck around objects.
But here everything is more complicated, I could not find the problem myself

**Comment by Tensuko** [comment]
I sent GIANTS a Discription and a Compare-Screenshot of the Vanilla Trucks.
I am not sure about any Status or if they will change anything on them, but we can't do much about that and I think you will find more help on that in a modding Forum, or compare it to the other Trucks. 
Here is the screenshot I sent them:
![Nodes](https://user-images.githubusercontent.com/27344744/72435563-a1f88280-379e-11ea-8db1-5634a9e3f715.png)

Closing this, as I said, no one can rly help you on this one here, sry.
