### ISSUE TITLE
2 verschiedene Güter laden (2Anhänger)

### ISSUE THREAD

**Issue by Despopanda** [Courseplay/courseplay#4615]
Hallo zusammen,

Gibt es eine Möglichkeit, wenn man 2 Anhänger am Trecker dran hat, auf jeweils 1 Anhänger verschiedene Sachen zu Laden?, und wenn nicht könnte man das eventuell irgendwie mit einbauen.

LG

**Comment by Tensuko** [comment]
Das ist bisher nicht möglich.
Ob das irgendwie machbar bzw ins HUD integrierbar ist, muss man sehen.
Ich nehme das mal als Suggestion auf.

**Comment by Despopanda** [comment]
Okay Danke!!!
