### ISSUE TITLE
Wiggling movement of some articulated axis steering tractors

### ISSUE THREAD

**Issue by RedMonster-HUN** [Courseplay/courseplay#4616]
There is an issue (I think it is) with the movement of the mentioned type of tractors when cp controlls them.
https://youtu.be/8uqPEv4R_1I

**Comment by RedMonster-HUN** [comment]
Another issue: When I send a tractor with seeder attached (which has a fertilizing option as well) to reload, cp doesn't reload fertilizer, only seeds.

**Comment by Woife1** [comment]
Do you have checked the filling options 
i think there is a option for filling both

**Comment by pvaiko** [comment]
But not with **all** articulated axis vehicles right? I did not see this before. Can you post a video with debug channels 12 and 14 enabled and the course made visible?

**Comment by Martinnygaard** [comment]
I do not have a log, bus i had the exact same issue with a Case IH Quadtrack and a large sower, while it was doing the fieldwork.

**Comment by RedMonster-HUN** [comment]
https://youtu.be/U1LHdw8UfnI
This is the new video recorded with debug codes enabled and course made visible.
[log.txt](https://github.com/Courseplay/courseplay/files/3907294/log.txt)

**Comment by pvaiko** [comment]
Where exactly is the wiggling here?

**Comment by RedMonster-HUN** [comment]
I dont know why it didn't wiggle this time but fertilizer is still not refilled.

**Comment by RedMonster-HUN** [comment]
The fertilizing was on, on both videos, but I think it means only that cp uses fertilizer during fieldwork. Is it possible to refill both seeds and fertilizer at the same trigger? Because the map I play on has a purchase point for all supply materials at the silo I recorded. So can courseplay use the same one trigger to refill seeds and fertilizer?

**Comment by pvaiko** [comment]
Open another issue (or even better, search the existing ones, there may be one already) about the filling, this is about that cute wiggling...

**Comment by pvaiko** [comment]
@Martinnygaard do you have instructions on how to reproduce it?

**Comment by RedMonster-HUN** [comment]
https://youtu.be/H1RSF1aGJc4
Here it comes again :(
[log.txt](https://github.com/Courseplay/courseplay/files/3908174/log.txt)

**Comment by pvaiko** [comment]
What is the turn diameter setting of that tractor? Looks like it is set to 2.6m?

**Comment by RedMonster-HUN** [comment]
In the ui it is called turning radius (if you think about that) and it is set to 14 meters. I noticed that wiggling starts when tractor approaches the end of the line and after that it continues.
