### ISSUE TITLE
Tractor turns "funny" if driving direction is reversed 

### ISSUE THREAD

**Issue by NexX0** [Courseplay/courseplay#4619]
Hey there,
 
so i noticed if you reverse the direction of the cockpit of a Tractor (player looks out the back window) Courseplay generates a Path to the next waypoint from the Front (what is now the Back) of the Tractor wich results in mostly Working but weird Pathfinding.

Also with AI turnmaneuver enabled it seems to not work at all.

https://www.youtube.com/watch?v=jP_MNQJw86c&feature=youtu.be

**Comment by Tensuko** [comment]
Video is private.

**Comment by NexX0** [comment]
> Video is private.

Fixed

**Comment by Tensuko** [comment]
Good Video, I think I know whats wrong. Front Node to create path finding turn?
@pvaiko can fix this like use other node when tractor cabin is turned or something ?

**Comment by pvaiko** [comment]
Already using the reverse driving node, wouldn't be able to drive at all otherwise. Something with the turn generation is not using it though.

**Comment by pvaiko** [comment]
344 should fix this, also the AI turn.

**Comment by NexX0** [comment]
Thanks,
i tested all variations that quickly came to mind seems to work perfectly now.
