### ISSUE TITLE
Error: Running LUA method 'update'. - AIVehicleUtil.lua(305) : attempt to call method 'getAIToolReverserDirectionNode' (a nil value)

### ISSUE THREAD

**Issue by RedMonster-HUN** [Courseplay/courseplay#4620]
Idk what is that is this and why it happens but it is like the camera gets stuck in certain situations. In current case it happened when I made cp work with the in-game 13meters tedder. On an other map it happened during combine and truck worked together. The common point is that both case happened in mode 6.
https://youtu.be/JjL2wFCtsAk

[log.txt](https://github.com/Courseplay/courseplay/files/3911300/log.txt)

**Comment by Tensuko** [comment]
This is not a camera stuck, this is a lua Error.
2019-12-02 13:29 Error: Running LUA method 'update'.
2019-12-02 13:29 dataS/scripts/vehicles/ai/AIVehicleUtil.lua(305) : attempt to call method 'getAIToolReverserDirectionNode' (a nil value)

Do you have Use AI Turn on in advancedvsettings ?

**Comment by pvaiko** [comment]
Has nothing to do with AI Turn.

Which exact tedder is this?

**Comment by Tensuko** [comment]
Wasn't able to reproduce this.
Used the Poettinger HIT 12.14 T from Vanilla Game.

**Comment by pvaiko** [comment]
Yes, that one has the reverser direction node defined in the XML so it would really be interesting this error to happen especially that it is in the Giants code...

    <ai>
        <needsLowering value="true" />
        <areaMarkers leftNode="aiMarkerLeft" rightNode="aiMarkerRight" backNode="aiMarkerBack" />
        <sizeMarkers leftNode="sizeMarkerLeft" rightNode="sizeMarkerRight" backNode="sizeMarkerBack" />
        <collisionTrigger node="aiCollisionTrigger" />
        <allowTurnBackward value="false" />
        <toolReverserDirectionNode node="sizeMarkerBack" />
        <turningRadiusLimitation rotationJointNode="attacherJoint" wheelIndices="1 2" />
    </ai>

**Comment by RedMonster-HUN** [comment]
So there is nothing you can do to fix it?

**Comment by pvaiko** [comment]
Not unless we can reproduce it.
@Tensuko  have you tried with a turn maneuver where it is reversing?

**Comment by Tensuko** [comment]
It always reverse, at least in my cases, more narrow lines at start and also the regular one for 13m. What I didnt try is to increase or decrease turn radius or turn speed.

**Comment by pvaiko** [comment]
If it worked in reverse I have no idea why it does not work for @RedMonster-HUN, unless you have a savegame with all other mods disabled to reproduce it there's nothing I can do.

**Comment by RedMonster-HUN** [comment]
All other mods disabled? Including the map?

**Comment by pvaiko** [comment]
Yes.

**Comment by RedMonster-HUN** [comment]
I tried to reproduce it on Ravenport field 9. Same tedder (HIT 12.14 T), different tractor. Only CP was enabled, but nothing. :(

**Comment by pvaiko** [comment]
I suspect it is a mod conflict, try disabling the mods which change the vehicle behavior, for instance follow me but I remember seeing another one in your log too.

**Comment by Tensuko** [comment]
FS will load all mods anyway, you should remove them out of your folder to be sure that there is no conflict.

**Comment by RedMonster-HUN** [comment]
I have found the mod that caused the conflict. It was the front attached Lizard multitool shown in the first video.
