### ISSUE TITLE
all that happens to me in mode 10!

### ISSUE THREAD

**Issue by deeg427** [Courseplay/courseplay#4621]
i do this the whole time while trying to do silage please someone point in the right direction, i have started the course just inside the bunker and farther in to no avail. i always have the stop out a good bit outside the bunker also.

https://youtu.be/nLb30VvkZhM

**Comment by Tensuko** [comment]
Video private...

**Comment by deeg427** [comment]
> Video private...

try now sorry

**Comment by Woife1** [comment]
If i remember right you should not have the course inside the bunker

try it again with the course start infront of the bunker without going inside (just your course with the startpoint a few meters to the camera)

**Comment by deeg427** [comment]
> If i remember right you should not have the course inside the bunker
> 
> try it again with the course start infront of the bunker without going inside (just your course with the startpoint a few meters to the camera)

will give it a bash tomorrow cheers :)

**Comment by Tensuko** [comment]
The Course is correct.
The Problem I can't rly tell you here, only @ThomasGaertner maybe knows whats wrong.
What you could do is, manually push the chaff on the side towards the end so the most chaff is in the middle, then it should work normaly. It might have something to do with the width of the bunker and the angle between the stop point and the start of the bunker.
![bunkerwinkel](https://user-images.githubusercontent.com/27344744/70025237-b1c85880-159c-11ea-8323-05cc062e96eb.png)

**Comment by Tensuko** [comment]
Add to Collection: #4254
