### ISSUE TITLE
Mode 4 not working with specific tractors?

### ISSUE THREAD

**Issue by dozerjz** [Courseplay/courseplay#4623]
What can i check to see why mode 4 does not work on CM's 8400?  Work a few days ago, was all excited, as of a new save I started back to not working..... is there something i can look at and change?

**Comment by Tensuko** [comment]
logfile, what is CM's 8400 ? Mod ? from where ?

**Comment by dozerjz** [comment]
Custom Moddings John Deere 8400 V2.0

**Comment by dozerjz** [comment]
i will send you the log file when I get back home, wont be until later today.

**Comment by pvaiko** [comment]
With debug channels 12 and 14. And a useful description of what exactly 'does not work' mean would sure help.

**Comment by dozerjz** [comment]
Will do, I apologize for being vague, I cannot select The option mode 4 (Planting and fertilizing), it is blacked out and cannot select it.  If I unhook the DB60 planter and attach another tractor to it, it works perfect.  It has to be something with that 8400 from Custom modding, just not sure what makes a tractor switch from field to plant mode....

**Comment by pvaiko** [comment]
In that case debug channel 6 and 11 while attaching

**Comment by dozerjz** [comment]
Sooooooo.... I freaking figured it out.... Custom Modding's Tractor is realistic alright!  You have to purchase the star-fire GPS and the Monitor for the Planter to work!!!  I have been stewing on this until i got home and had to try one last thing before I sent everything to you. Consider this closed!!!!
