### ISSUE TITLE
Open Silage bunker cant get it to work.

### ISSUE THREAD

**Issue by lodewijk12** [Courseplay/courseplay#4625]
i cant for the life of me get my workers to unload into a silage bunker.

im using mode 2, to unload a forage harvester. then i loop the tractor trough the BGA and 1 bunker this is how ive always done it since courseplay for fs15 i think or fs13.

i put a wait point at the start of the bunker, as ive seen in youtube tutorials, drive straight trough. and go back to my initial start point near my field.

but every time my workers stops and and i get notified he has reached his trigger or waitpoint. but then i have to press continue, after pressing continue he unloads but also speeds up to field speed. so he is busting trough the bunker doing 20km/h. with a full trailer he will be out of the bunker before even 20% is unloaded.

 this is with the "stop at last point or trigger" option deactivated.

i have also tried setting it up the old school way with 2 unload triggers at each end of the bunker, but no luck. it will just dump everything at the first unload waypoint and then it will carry on.

i have tested it both with a bunker that is part of the map, and with a placed down vanilla bunker from the store, they have the same result. my worker either dumps stuff into a huge pile, or he stops at the wait point untill i press continue and then races off dumping more then half his load outside the bunker.

any help would be greatly appreciated.

**Comment by Tensuko** [comment]
Unload in bunker dont need any waitpoints, just drive through it.
But note that mode2 is old driver and doesnt unload so nicely as you are used to it.
If you want to see a proper unload into Bunker,  use mode1 or mode6 with a loading wagon for it, just to try and see how it works.
Again, no wait or unload points needed, unless you unload in reverse, then need the unload point.

**Comment by lodewijk12** [comment]
thank you for the answer, the only problem for me that remains is that it will drive trough the bunker at field speed. so i still need to switch to the vehicle to set field speed slow enough for it to empty into the bunker, but then i have to switch it back so it doesnt drive just 8km/h when in the field moving towards my harvester.

**Comment by Tensuko** [comment]
That is couse of old Mode2 Driver, as I said, try it with Mode1 and get your chaff from a Silo or Mode6 loadign Grass with a Collecting Wagon, then unload into Silo.
Or try out the Mode2 Alpha Version, you find a discription here #4286

**Comment by lodewijk12** [comment]
thank u very much. ill try out the alpha mode 2. i sort of got it to work without it just an hour or so ago.

i just have to stop 50-100 meters in front of the bunker. and then drive at 6km/h all the way trough it, untill the trailer is out of the bunker.

then it works again. the workers sometimes have a bit of trouble following the harvester around. but nothing major yet, regardless i'll try out that mode 2 alpha.

thank you for the help!
