### ISSUE TITLE
Abtanken von Drescher/Häcksler und Rübenroder

### ISSUE THREAD

**Issue by Icke09** [Courseplay/courseplay#4626]
Ich habe das Problem, dass der Abfahrer nachdem er das Erntefahrzeuge entleert hat gegen den Drescher fährt. Nach einer kurzen geraden Strecke liegen die Wegpunkte die er hat genau dort wo der Drescher steht (Lade in der Frucht ab). Somit fährt er jedes Mal nach dem Abbladen gegen den Drescher.  Das Problem tritt nur auf, wenn der Drescher zwischen Abfahrgespann und Verlasspunkt des Feldes steht. 
Vielleicht eine schnelle Lösung: eine Wartezeit am letzten Wegpunkt des Abtankens einfügen von 7-10 Sekunden, damit der Drescher  vorbeifahren kann.
MfG Lars

**Comment by Tensuko** [comment]
#3311 #4286 
Closed.
