### ISSUE TITLE
Issue with human v1.0 OR Virtual AutoDrive Folder not present

### ISSUE THREAD

**Issue by Merrlin** [Courseplay/courseplay#4627]
I 've started recently to use CP in combination with AutoDrive.
With v.283 there is a Virtual AD folder introduced. And there my problem Starts.
I can't find the folder. Is there any hidden function or option to reveal that option or how are the steps to use that function?
CP is v.344 and AD is v 1.0.7.

Greetings Daniel

**Comment by Tensuko** [comment]
In the CP HUD where you load CP Course.

**Comment by Merrlin** [comment]
Yeah there should it be... But in the CourseManager is no Folder Folder called AutoDrive... Is it possible that it is only generated if the Couselist is initially empty?

**Comment by Tensuko** [comment]
CP just load it from AD.
I am not sure if you need AD Targets and also try out recalculate AD Network.
Else post your logfile maybe I find something.

**Comment by Merrlin** [comment]
Oh ok.... It seems I'm not dumb... I've used a predefined Network  for now. Then i go into further investigation...
I will try some things

**Comment by Tensuko** [comment]
Try only use AD+CP without any other mod in mods folder.
Then just load Felsbrunn Map, it should have AD Network pre installed (at least I had it) and so CP also had he AutoDrive Folder.

**Comment by Merrlin** [comment]
Hallo Tensuko,

Es geht immer noch nicht... Hab alles leer gemacht, hab die älteren AD Versionen (mit denen das eingeführt wurde) installiert. Hab extra nen AutoDrive Ordner erstellt. Hab die CP Kurse gelöscht, hab extra ein neues AD Netzwerk mit 2 Punkten aufgezeichnet... Es funktioniert einfach nicht.
Unload/Refill funktioniert ohne irgendwelche Probleme.

Um das nochmal zusammenzufassen: Sobald AD installiert ist und Punkte hat sollte im CP Coursmanager eigentlich ein neuer Ordner mit dem Namen AUtoDrive erscheinen? Darin befinden sich dann die Zielpunkte, richtig?
Sicherheitshalber häng ich noch die Log an. Vielleicht hat ja @pvaiko noch eine Idee.
[log.txt](https://github.com/Courseplay/courseplay/files/3933642/log.txt)

**Comment by Tensuko** [comment]
Du brauchst keinen Ordner erstellen.
CP erkennt ob AD da ist und macht selber einen Ordner und wenn AD Wegpunkte hat, werden diese dort auch gelistet.
Ich versuche das nachher auch noch mal....

**Comment by pvaiko** [comment]
@Merrlin Zuerst beides updaten:

Load mod: AutoDrive (Version: **1.0.4.9**) (Hash: 2d190644426c344db82938962397eca8)
Load mod: Courseplay (Version: **6.01.00291**) (Hash: a8f5f43a3b7dcb966430aeee7e639d14)

**Comment by Merrlin** [comment]
So, Bug gefunden. Der Virtuelle Ordner funktioniert NUR wenn die Datei exakt FS19_AutoDrive heißt...
Sobald sie umbenannt wird, werden die virtuellen Kurse nicht mehr geladen.
@pvaiko War nur zum testen...

**Comment by Tensuko** [comment]
Warum benennest du FS19_AutoDrive auch um ? Das kommt doch so vom AD GitHub unter releases....

**Comment by Merrlin** [comment]
Zum einen kennzeichne ich mir so die Mods die von externen (Nicht-Modhub) Quellen kommen, und zum zweiten finde ich die Dateien dann im ModFolder leichter wieder, weil sind ganz oben.

**Comment by Tensuko** [comment]
Denke mal das Problem wurde gefunden und kann geschlossen werden....
