### ISSUE TITLE
Cutter and transporters

### ISSUE THREAD

**Issue by Severan500** [Courseplay/courseplay#4630]
Hello, I want to ask if anyone also has a similar problem with Courseplay when using a cutter and derivative. I use not only the most recent CP, unfortunately when I release the cutter and transporter, so nowhere I can not find settings to turn at the headland every other direction. From the first point, they go correctly in the settings automatically, but at the headland they already collide and the derivative goes on one side. usually on the left. Nowhere can I find the settings to turn in reverse. Last where it was according to videos youtubers around cca V6.01.124? Does anyone have a similar problem? Thank You!

**Comment by Tensuko** [comment]
What Mode, what Tools ?
Do you use Mode2 ?
Maybe #3311 and #4286 related ?

**Comment by Severan500** [comment]
I use the combine / cutter mode for the krone big x and the "drive the combine to the cutter" mode for the derives. or we misunderstood the question with those numbers and mods.

**Comment by Tensuko** [comment]
I am not rly sure if I understand what you try to do....
Modes are counted from the left to the right in the HUD.
Mode1-10

**Comment by Severan500** [comment]
I use MODE 2 for the cutter, of course, but I use the mod 6 for the cutter. At the end, the transporter does not drive away and does not cross over to the other side of the cutter, but keeps it on the side of the cutter so that it locks and collides when cornering.

**Comment by Tensuko** [comment]
Well, check out #3311 and #4286 for more information about that.
Closed, sry.
