### ISSUE TITLE
mode1 doesnt load from TMR Mixer silo

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#4631]
I am using this mod:
https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=146546&title=fs2019

I use mode1 for loading TMR into the trailer, but tractor will not stop under the pipe.
It just says loading 0 of 40000 for half a second, then tractor continues without loading.

Which debug channels should i use to give u log.txt ?

**Comment by Tensuko** [comment]
Channel 1 and 2.
Question: Did you set the TMR in the HUD as the good that you want to load ?

**Comment by bojanh66** [comment]
Yes, i did, but it didnt help.
Ill post a video and log in a few minutes.

**Comment by bojanh66** [comment]
https://youtu.be/gmw_L6F-Tyo 

[log.txt](https://github.com/Courseplay/courseplay/files/3935083/log.txt)

**Comment by Tensuko** [comment]
I already see the Problem (I think....)
You have the stop behind the fill trigger.
Try do it like this and best would be, if you could make the course a bit more straight behind the start, not sure if that can work. But CP looks for a Trigger between start and stop.
![start stop](https://user-images.githubusercontent.com/27344744/70375144-afe2fa00-18fa-11ea-8b29-aa0510622155.png)


SideNote:
Your FS19_Lexion_8000 throws a lot og Errors, you should take it out.
I also wonder what 8000 it is....

Beside that I don't see a real Error in your log, but I just made a fastcheck on it...

**Comment by bojanh66** [comment]
Its modded Lexion 8900 with different tyres and capacity.
Ok, im gonna try to record new course and hopefully it will work.

**Comment by bojanh66** [comment]
Tried it on default map, it works perfect, so i guess i need to play with better course recording, but its tight space :/

**Comment by Tensuko** [comment]
Most important is the order:
stop - trigger - start
The turn at start I am not sure how much CP can handle, before he continues. That you got to try out.

**Comment by bojanh66** [comment]
Yes that was the main problem, turn after start, 2nd and 3rd waypoint.
I had straight first 3 waypoints and now it works :)
