### ISSUE TITLE
Malfunction detected in CP Mode 5+6 - Malfunction detected in CP Mode 5+6

### ISSUE THREAD

**Issue by haamic** [Courseplay/courseplay#4633]
Malfunction detected in CP Mode 5+6.
I have therefore created a test course in the form of an "S".
-Mode 5+6 only the tractor, drives from start to finish and drives back to start and starts again from the front without stopping.
-Mode 5+6 with trailer, drives from start to finish. however approx. 5 waypoints before destination the vehicle drives straight ahead with approx. 9km/h, without stopping, does not reach the destination.

Translated with www.DeepL.com/Translator (free version)
+++++++++++++++++++++++++++++++++++++
Fehlfunktion bei CP Mode 5+6 festgestellt.
Ich habe darum einen Testkurs erstellt in Form eines "S".
-Mode 5+6 nur der Traktor, fährt vom Start zum Ziel und fährt zurück zum Start und beginnt wieder von vorn, ohne zu stoppen
-Mode 5+6 mit Anhänger, fährt vom Start zum Ziel. allerding ca. 5 Wegpunkte vorm ziel fährt das Fahrzeug dann geradeaus mit ca..9km/h, ohne zu stoppen, erreicht das Ziel nicht.

**Comment by Tensuko** [comment]
logfile with channel 9 12 and 14, just to be sure...

**Comment by haamic** [comment]
standard map Felsbrunn, standard Tractor, no other mod, only CP, Mode 5, testcourse with 37 waypoints - vehicle does not stop at last waypoint, returns to another waypoint

[CP Mode 5 log.txt](https://github.com/Courseplay/courseplay/files/3935939/CP.Mode.5.log.txt)

the other problem in mode 6 had to do with a mod loader wagon, not with cp.
i could determine that myself.
only in mode 5 i got the error that CP does not stop at the last waypoint

**Comment by Tensuko** [comment]
When you started the CP Driver, did you set it to wait at last waypoint or trigger ?

**Comment by haamic** [comment]
no i didn't. with option enabled it works. sorry.
But isn't it illogical? A simple transfer from start to finish should end automatically. But it wasn't like that before, was it? Or was the option always switched on automatically in the past?
++++++++++++++++++++++++++++++++++++
nein hatte ich leider nicht. mit eingeschalteter option funktioniert es. sorry.
Aber ist es nicht unlogisch? Eine einfache Überführung vom start zu Ziel sollte doch automatisch am Ziel enden. Früher war das aber nicht so, oder? Oder war die option früher immer automatisch eingeschalten?

**Comment by Tensuko** [comment]
It works as it should and always did.
Closed.
