### ISSUE TITLE
Drescher vs Trecker...

### ISSUE THREAD

**Issue by michel5998** [Courseplay/courseplay#4635]
moin,
ich habe ein problem, was ich mit einem einzigen bild erklären kann
![fsScreen_2019_12_08_21_25_29](https://user-images.githubusercontent.com/49126733/70395692-a42e2b00-1a01-11ea-9faf-fa8626c68438.png) seht es euch an, das passiert jedes mal. ganz normale kurse, alles richtig eingestellt, fruchtumfahrung an, einmal nicht hingesehen heißt es ... hat durchdrehende reifen und dann begrüßt mich diese und ähnliche bilder

**Comment by Tensuko** [comment]
Das habe ich schon oft gesehen....
Und trotzdem: #3311 #4286 
Closed... Einfach mal die Stickys lesen....
