### ISSUE TITLE
CoursePlay not working in game

### ISSUE THREAD

**Issue by ColtRemington-BarretBrowning** [Courseplay/courseplay#4636]
Course Play does appear to load up in game with its loading screen showing up for a few seconds. When I press Lft Ctrl and Delete nothing happens. I am using the default keybinds for it.. The game does see it and I know it's installed correctly since the file structure mirrors my other mods. 

Ideas?

**Comment by Tensuko** [comment]
No logfile, no help...
I am not a magican...

**Comment by ColtRemington-BarretBrowning** [comment]
Here's the log file. At least I assume it is the correct one.
[log.txt](https://github.com/Courseplay/courseplay/files/3937576/log.txt)

**Comment by Tensuko** [comment]
Err actually the default key to open the HUD is right mouse click..... you can switch that to the keys in the CP HUD from unknown tu ctrl+del but default for every vehicle (that can use CP) is right mouse click.

Also you should take out this mod, as it could cause you some trouble:
2019-12-08 12:22 Error: Can't load resource 'C:/Users/Whitey/Documents/My Games/FarmingSimulator2019/mods/EXP19_Toyota_LC_VDJ76/script/logsWinch.lua'.

**Comment by Tensuko** [comment]
Closed due to inactivity.
Load actual and newest version and try again. Remember that some Vehicles doesnt support CP. You would have to contact the modder for that.
Closed.
