### ISSUE TITLE
modDesc.xml wird nicht geladen

### ISSUE THREAD

**Issue by RichbackIsHere** [Courseplay/courseplay#4637]
Hey nach einer sauberen Neuinstallation von FS und den Mods die ich so nutze möchte CP nicht mehr laden. Im Log steht halt das die modDesc.xml nicht geladen wird. Um genau zu sein das hier: 

Error: Failed to open xml file 'C:/Users/KingK/Documents/My Games/FarmingSimulator2019/mods/courseplay_master/modDesc.xml'.
Load mod: courseplay_master (Hash: dc946c55eee4d105cef296841dd11c62)
Error: Missing descVersion attribute in mod courseplay_master 

Bedanke mich sehr für deine Hilfe.
[log.txt](https://github.com/Courseplay/courseplay/files/3937241/log.txt)

**Comment by Merrlin** [comment]
Ja du lässt auch das komplette Master-Branch runter. Das ist falsch (da müsstest du Aus- und wieder Einpacken)
Es reicht vollkommen wenn du hier auf der Code Seite auf releases (steht Recht weit oben) clickst.
Damit kommst du auf die Seite mit den ganzen Releases. Unter jedem Release gibt es den Punkt assets. Da draufklicken und du bekommst das richtige File das du einfach nur in den ModOrdner hauen musst.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/releases
Als Tipp am Rande: Achte darauf, dass du keine zweite CP Version im Mods Ordner hast.
Damit das nicht passieren kann, benenne die Datei immer gleich.
Also Zip File runterladen, umbenennen (z.B. FS19_Courseplay) und fertig.

Closed.
