### ISSUE TITLE
Courseplay and DynamicstorageHall

### ISSUE THREAD

**Issue by OldFamous** [Courseplay/courseplay#4638]
Hello,

I try to get courseplay working with the DynamicStorageHall from "global company"
But it seems that courseplay can't recognize the unloading trigger?

I'm talking about this mod [https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=140589&title=fs2019](url)

I also attached my log file with debug channel 2 in a test save game without mods except courseplay(github version6.01.00341)  , global company(newest github version) and DynamicStorageHall
[log.txt](https://github.com/Courseplay/courseplay/files/3939180/log.txt)

If you want to know more let me know.

Best regards,

OldFamous

**Comment by Mannie313** [comment]
Du must erst eine Box auswählen zum abladen.

**Comment by Tensuko** [comment]
I didn't try this storage yet, but GC 1.1.3 is needed and as Mannie313 said, you got to select the box 1st to unload. Maybe you can't use it with CP if you have to make some special actions for unloading.

**Comment by OldFamous** [comment]
Yes Iam using GC 1.1.3 version and I have selected the box allready.

I hoped there was a way to wich works together. I liked the storage but if I cant use it with courseplay its nothing for me.

Thank you.

**Comment by Tensuko** [comment]
I will try it out when I got time for it.
What you could do is create a logfile with channel 1 and 2 active.
Select the right box, select the right fruit to pick in CP HUD, then run the course.
When in Mode1, remember to have the start behind the Trigger and Stop in front of the Trigger (start so that the trailer can pick it up).

**Comment by OldFamous** [comment]
I just made a log file for dumping Rapeseed and a second log file for extract Rapeseed from the silo. 
I selected the first box in both situations also selected both times Rapeseed.





[DrivingHelperExtractGrain.txt](https://github.com/Courseplay/courseplay/files/3977797/DrivingHelperExtractGrain.txt)
[DrivingHelperDumpingGrain.txt](https://github.com/Courseplay/courseplay/files/3977798/DrivingHelperDumpingGrain.txt)

**Comment by schuelli238** [comment]
![image](https://user-images.githubusercontent.com/20584917/74093510-2eaf0b80-4ad3-11ea-95e5-b20104cd5273.png)


Ich kann auch an der Halle nicht abladen. 
Versuche mir gerade auf der Karte "Hof Bergmann" das leben einfacher zu machen.

Same on my side. Maybe the trigger is to small. Just trying to get the work done easier with cp on "Hof Bergman" map.

**Comment by pvaiko** [comment]
Should work with 388, reopen if not.
