### ISSUE TITLE
Reversing ORDER of course waypoints.

### ISSUE THREAD

**Issue by mr-g-1969** [Courseplay/courseplay#4639]
I haven't seen anyone suggesting this but to me it would be beneficiary to have an option to reverse the created/loaded course.  That way - If I choose, I can record a course from one location to the other (driving in the middle of the road) and only save that ONE course instead of having one "farm to field" and another "field to farm".

**Comment by Tensuko** [comment]
Hmm that could be possible I think.
You would have to change the Order of the Waypoints.
I add this here as suggestion.

**Comment by mr-g-1969** [comment]
Awesome! Thanks for the awesome MOD by the way ;)

**Comment by Merrlin** [comment]
Funny... I thought about that suggestion just yesterday.
Would be useful for driving field courses in reverse for example with loading wagons.

**Comment by mr-g-1969** [comment]
And you won't have to keep two routes.. One "to" and one "back" in
reference to a location. Lessens the number of routes to keep track of.
You can see that I also updated the subject now that I figured out how to
make a post a suggestion ;-)

**Comment by pvaiko** [comment]
I like this idea, one question: how would you envision the workflow for this on the HUD? Where would the 'reverse course' button go and what exactly would it do?

**Comment by Tensuko** [comment]
Hmm is it possible to add a toggle button at top of the course load page, so that when the toggle is on, all load actions will reverse the waypoints ? Not sure if that cause trouble on fieldcourse with the turn WP.

**Comment by mr-g-1969** [comment]
I was thinking of maybe an icon that had a right arrow above a left arrow in the top bar where you click to clear "unload" a route or hit the floppy to save a driven route.
   It would only show when you're on the "drive" tab. Clicking the icon would reverse the loaded (or temporary) course..

![Courseplay Suggested HUD](https://user-images.githubusercontent.com/56283300/71017014-f3402400-20c3-11ea-8d78-9ec75ebbe214.png)

**Comment by Tensuko** [comment]
That will be a bit problematic as you could only change all your loaded WP.
![kurse](https://user-images.githubusercontent.com/27344744/71017814-7f1f7380-20f7-11ea-99a8-fcf44a07ec46.png)
Lets say you have 2 Course, the red and the green.
Now you want the red one in reverse and the green one the normal way, how to load them.
Next time you want to green one in reverse and the red one the normal way...
Depends on where you want to go from what place and stuff.
For a simple A - B Route like save only Shop to Farm and can reverse that its a simple solution...

**Comment by pvaiko** [comment]
@mr-g-1969 wish we had someone the skills and motivation to add new icons...

**Comment by suchna** [comment]
I think that easy way to do this is in course generation screen. When you generate course through field and than click to "reverse button" whitch will swich start and end point of the generated course. Than you can save it like every other route...  (it would be useful when you make rows and bales from grass and need to collect them from field " reverse way" )

Reversing Recorded route can also be IMHO in Driver Controls under "Stop at last point or trigger"

**Comment by Tensuko** [comment]
Reverse a Fieldwork Course is not rly needed in my opinion...
A to B Course yea couse you only got to record one, but as I said, you need the option to add them in reverse and normal way at the same time so....

**Comment by Merrlin** [comment]
Of course reverse Fieldcorse is a good idea, at least for me.
For example if you now grass you cut and widrow it you will do this from the inner to the outer because you don't want to drive every time on the freshly mown gras.
But if you collect it (and want to use the widrowing course)  you don't want to drive over the widrows on every turn. So you collect from the outer to the inner.

**Comment by Merrlin** [comment]
For the combined courses: I think it is enough if you reverse the parts separately, save them and reload them.

**Comment by Tensuko** [comment]
Add to collection: #6270
