### ISSUE TITLE
Tastenbelegung für Schaufelposition funktioniert nicht

### ISSUE THREAD

**Issue by Rumspringa90** [Courseplay/courseplay#4640]
Hi,
ich hab in der Tastaturbelegung gesehen, das es Tasten für die Position der Schaufel gibt. Leider passiert nichts wenn ich dann die Taste drücke. Wenn man im Modus 9 die Tasten mit der Maus anklickt funktioniert es. Kann man das beheben? habe leider keine LOG da ich nicht weis welchen Debug-Channel dafür zuständig ist.
Es würde das manuelle arbeiten mit dem Frontlader deutlich einfacher machen wenn man nur eine Taste auf der Tastatur drücken muss. (Vielleicht kennt auch jemand ein Mod dafür)

CP Version 6.01.00341

Danke. Gruß Henne

**Comment by Tensuko** [comment]
Ja das ist bekannt, die Keybindings für CP müssten generell nochmal auf das FS19 System angepasst werden, nur haben wir im moment niemanden der Zeit dafür hätte...
Ich kann die Tasten sogar selber gerade ganz gut gebrauchen, aber es ist wie es ist.
Ist aber auch schon bekannt, #4389
Closed.
