### ISSUE TITLE
BGA Silo verteilen und verdichten

### ISSUE THREAD

**Issue by tobi694** [Courseplay/courseplay#4641]
Ich kann das BGA Silo nicht mit einem Schiebeschild verteilen und verdichten. 

Version: 6.01.00344

**Comment by Tensuko** [comment]
Ein Schibeschild ist auch zum Aufschütten, steht sogar in der XML des Tools.
Zum Verteilen und Verdichten wird ein anderes Tool benötigt, dessen Name ich nicht weis...
Sind diese Runden scheiben. Ansonsten siehe #4621
Closed.
