### ISSUE TITLE
Mit Radlader BGA Silo entleeren

### ISSUE THREAD

**Issue by tobi694** [Courseplay/courseplay#4642]
Die Funktion BGA Silo entleeren funktioniert auch nicht richtig mit dem Radlader.
Kann nicht mal geradeaus vor und zurück fahren.  
Zudem lädt der Radlader zu früh vor dem Trigger der BGA, obwohl der Wartepunkt richtig gesetzt wurde.

**Comment by Tensuko** [comment]
Und der Kurs sieht wie aus ? Was funktioniert nicht richtig ?
Video ? Screenshot ?

**Comment by Tensuko** [comment]
Closed weil inaktiv und keine Details gegeben werden.
Mit gemoser lässt sich halt nicht viel anfangen...

**Comment by tobi694** [comment]
Es wurde eine E-Mail am 13.12.2019 mit dem Video geschickt. Haben Sie dies nicht erhalten`?

**Comment by tobi694** [comment]
https://www.youtube.com/watch?v=5gxUbmdo9Wg

**Comment by Tensuko** [comment]
Nein habe ich nicht, wenn dann Videos hier verlinken.
Und unter dem Link steht Video ist Privat.

**Comment by tobi694** [comment]
https://youtu.be/5gxUbmdo9Wg

Jetzt sollte das Video öffentlich sein
