### ISSUE TITLE
Mais hächseln mit Abfahrer

### ISSUE THREAD

**Issue by tobi694** [Courseplay/courseplay#4643]
Der Maishächsler funktioniert einwandfrei, jedoch startet der Abfahrer kein Wendemanöver, wenn die Bahn zu ende ist, somit kommen die beiden Fahrzeuge immer in Kontakt. 

Zudem fährt der Abfahrer immer auf der Feldseite, obwohl Fruchtumfahrung eingeschalten ist, somit habe ich dann das gleiche Problem wie oben beschrieben.

**Comment by Tensuko** [comment]
Siehe #3311 und #4286 
Closed.
