### ISSUE TITLE
CP und Autodriver nicht zusammen spielbar ( Log )

### ISSUE THREAD

**Issue by Somailo88** [Courseplay/courseplay#4645]
Hi @ zusammen . Ich hab folgendes Prob. Cp allein ( altuelle Vers. von Heute. ) startet in Savegames und neue spielstände. LS ist ebenfals aktuel,. kommt aber Autodiver dazu (  auch aktuel, heute runter geladen ) hängt das beim laden sihe LogData. Der AD allein ohne CP funktuniert auch.  und ich hab keine weiteren mods aktiviert. Ich brauch da mal raht , den die log sagt mir das ögend was mit der CpManager  nich richtig is . aber siht selbst .

danke im vorraus für die hilfe 
[log.txt](https://github.com/Courseplay/courseplay/files/3946612/log.txt)

**Comment by Merrlin** [comment]
Punkt 1: Pro ModOrdner nur EINE Karte. Alles andere macht massiv Probleme.
Punkt 2: In deinem ModOrdner schaut es aus wie bei Hempels unterm Sofa. AUFRÄUMEN! Alle Mods die du nicht brauchst raus. Insbesondere die AutoLoad Mods.
Punkt 3: Wiel dein ModOrdner so chaotisch ist, hast du warscheinlich übersehen das deine AutoDrive Version STEINALT ist. Du Hast 1.0.1.9, aktuell ist 1.0.7.

**Comment by Scaracuila** [comment]
Hi, 1.0.1.9 ist die Modhub Version! Lade dir mal die github version runter!
Grüße

**Comment by Tensuko** [comment]
Sooo chaotisch sieht es nichtmal aus, habs schon schlimmer gesehen.
Aber ja... nur EINE Map, Mods aktualisieren und sowas muss raus oder korrekt runter geladen werden:
Error: Failed to open xml file 'C:/Users/Somailo/Music/Documents/My Games/FarmingSimulator2019/mods/AIVehicleExtension/modDesc.xml'.
Load mod: AIVehicleExtension (Hash: d10538c3919df4acda88e5850efd74b1)
Error: Missing descVersion attribute in mod AIVehicleExtension

Und ja auch AutoDrive ist wie @Merrlin schon sagte stein alt.
Bitte von AutoDrive GitHub die neueste Version laden.

**Comment by Somailo88** [comment]
Danke für eure hilfe ich werde das den mal auf den neusten stand bringen. Den ich lade hauptsächlich von modhoster die mods. Den sind die dort ebenfals den nicht aktuell. 
Thema Karten die muss leider drauf haben da ich die im mp spiele . Naja bis auf die 2 basismaps.

**Comment by Merrlin** [comment]
Ja du machst dir einfach für jede Map einen eigenen ModOrdner und dann ist alles in Butter...

**Comment by Somailo88** [comment]
Top an alle die zu raht und tat standen. Es funktioniert alles . Mods die ich nutze simd raus, bzw die ich gebrauche sind aktuell. Ornder sind sortiert nach maps . Thx thx. 


Closed this Thema.
