### ISSUE TITLE
Suggestion: Movable Hud

### ISSUE THREAD

**Issue by Elite82pt** [Courseplay/courseplay#4646]
Great mod!! 
If you have time (ever). Could you make the Hud movable? I play in a 21:9 monitor and the sides could be used for the Hud, but I cant move it

Please take this only has a last priority suggestion

**Comment by Tensuko** [comment]
I am not sure if the way the HUD is made, can be changed to be movable.
But I keep it here as suggestion.

**Comment by pvaiko** [comment]
You can't drag it with the mouse but you can change the position (and size) of the HUD by editing the posX, posY and hudScale settings in the courseplaySettings.xml file in your savegame folder.

**Comment by Elite82pt** [comment]
Thank you!! you could put that info in one of the pages in the HUd I believe a lot of players would enjoy that!
