### ISSUE TITLE
Mehrere Fehler?

### ISSUE THREAD

**Issue by Blackjack155** [Courseplay/courseplay#4647]
Und zwar sind mir mehrere sachen auf gefallen
1. Beim Dreschen der Abfahrer fährt in denn Drescher wenn dieser bei 100% zurück gesetz hat und nach dem abtanken wieder los fährt
2.Beim Fahrenen Abtanken Ruckelt der Abfahrer nach vorne und hinten er bremst also immer abrubt ab um die geschwindichkeit zu halten.
3. beim schwaden fährt er nicht bis zum ende des feldes so das reste liegen bleiben
4.Bei neustart der spieles weiß z.b. der Ladewagen fahrer nicht mehr wo er zu letz auf gehört hat das war beim ls17 noch anders

bei weiteren fehlern würde ich diese mit hier posten

**Comment by Tensuko** [comment]
Schau bitte erstmal GitHub durch, bevor du hier alles doppelt schreibst.
Zu Punkt 1: siehe #3311 und #4286 
Zu Punkt2: das gleiche
Zum 2ten Punkt2: Im HUD unter Advanced Setting könntest du mit der einstellung lower und lift implement experimentieren, ob das abhilfe schaft.
Zu Punkt4: Das mag sein, aber dafür gibt es die option 'beim nahesten Wegpunkt starten' natürlich muss er dafür auf dem Feldkurs sein.

Mache hier trotzdem zu, weil wenn echte Fehler da sind bitte einzelnd posten mit logfile!

**Comment by Blackjack155** [comment]
unter Advanced Setting ist nichts?
Geht das bisschen genauer? :)

**Comment by Tensuko** [comment]
Doch da ist etwas ?
![advset](https://user-images.githubusercontent.com/27344744/70719740-d4701500-1cf2-11ea-8f26-2211768980a9.png)
Augen auf beim Eierkauf....
Ich weis ja aber nicht mal welche Version du hast...

**Comment by Blackjack155** [comment]
die aktuelle die hir zu laden ist 

aso dachte du meintest darunter :D
okay ich bin mit denn englischen nicht so was sind denn die beiden felder damit ich das richtig verstehe?

**Comment by Tensuko** [comment]
Das bezog sich hierrauf:
beim schwaden fährt er nicht bis zum ende des feldes so das reste liegen bleiben

When to raise implement early/late heist Das tool anheben früh oder spät
das gleiche für lower (absenken).
Stell das mal so ein:
Raise = later
Lower = early
eventuell 'schwadet' er dann besser

**Comment by Blackjack155** [comment]
okay ich werde es demnächst mal testen und gebe dann feadback
