### ISSUE TITLE
Batco Augers cause traffic

### ISSUE THREAD

**Issue by Jeffstan123** [Courseplay/courseplay#4648]
I am using the Batco Augers to offload trailers and whenever I set a course to go over them the course registers it as traffic when it is not. is it possible to change this so that it does not cause traffic?

**Comment by Tensuko** [comment]
Can you make a screenshot of the situation when you pressed F5 one time ingame, so I can see the Collission and Traffic Markers ?

**Comment by newride** [comment]
[
![20191219115221_1](https://user-images.githubusercontent.com/25779903/71197148-99bc2e80-2256-11ea-8649-95d6202d0de1.jpg)
](url)

**Comment by Miketeg** [comment]
Seems that the traffic issue is fixed, but now it does't see the trigger, so it will continue without emptying.

Workaround is to set a Wait point and empty by ourself.
