### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Blackjack155** [Courseplay/courseplay#4649]
Warning (performance): Raw audio format C:/Users/chris/OneDrive/Dokumente/My Games/FarmingSimulator2019/mods/FS19_Courseplay/sounds/cpClickSound.wav.

Warning (performance): Texture C:/Users/chris/OneDrive/Dokumente/My Games/FarmingSimulator2019/mods/FS19_Courseplay/img/fieldScanInfo.png raw format.

[log.txt](https://github.com/Courseplay/courseplay/files/3962520/log.txt)

**Comment by Tensuko** [comment]
This is only a Warning and nothing to worry about.
Closed.

**Comment by Blackjack155** [comment]
warung ist für für mich ein fehler?

**Comment by Tensuko** [comment]
Eine Warnung ist kein Fehler, es ist eine Warnung...
