### ISSUE TITLE
Combine Self Unloading

### ISSUE THREAD

**Issue by Robinsonb1980** [Courseplay/courseplay#4650]
Hello, 

Per the Manual I have been trying to activate combine self unloading, I have done as the manual says: 

The combine needs to be hired as a regular helper (or with AutoCombine), and only then Courseplay may be activated. The combine will work as a helper until its fill level reaches the percentage set at Start at %. Then it drives to the course's start point, follows the course until the waiting point, where it will unload into a waiting trailer. After, it will follow the course until the end point, from where it will drive to the last position where it worked as a helper. Now, it will activate its cutter and continue threshing.

I have activated him as a regular helper and I have tried the AI Vehicle Mod which is the replacement for autocombine since FS15.   

But everytime I goto activate it I get this:
https://postimg.cc/Fkc9Wnrj

I can not activate the Combine Self Unloading Feature, and there is a Trailer and tractor on the field for it to unload to. Any assistance would be helpful with this issue, thank you Kindly.

**Comment by Tensuko** [comment]
This Mode7 won't come back in this way, but.... wait a bit longer ;)
I will post more detail about that later.

**Comment by Robinsonb1980** [comment]
Ok, I will patiently await more detail soon. Thank You.
