### ISSUE TITLE
Combine load and unload 

### ISSUE THREAD

**Issue by Rednick69** [Courseplay/courseplay#4651]
I've been experiencing a bug using courseplay. I have removed all other mods from the game except courseplay and a money mod and also deleted the FS19 folder in my documents and let it recreate a new file. I disabled steam cloud so it wouldn't bring my save games over as well. I've tried both stock maps and I can't get it to work right. 

My tractor with trailer keeps acting crazy and when it goes back to my silo to unload the grain the grain won't come out of the tipper. Instead the tractor just pulls up and dumps it on the ground. I know this could be user error because I've watch a lot of videos of this working perfectly but I just can't figure out how people are getting this to work out like it should. 
Please see the recording I've uploaded. 

https://youtu.be/Ju19qjYJ1so

**Comment by Rednick69** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3963529/log.txt)

**Comment by Tensuko** [comment]
That is becouse yoz set a manual unload point... Why you did that...
It unloads as soon as he is in a trigger
Try it out without a unload point in the course and report.

**Comment by Rednick69** [comment]
Thank you for the quick reply. I figured this would be user error. I didn't realize that the unload point I was setting wasn't needed. 

Is there a way to avoid the collision that appears at .51 seconds in the video?

**Comment by Tensuko** [comment]
Not with the old Mode2.
You can take a look at #3311 and #4286 about that.

Smal Hind: The Unlaod point is for unload anywhere, like unload sugarbeets on the fild or something :)
