### ISSUE TITLE
Frage

### ISSUE THREAD

**Issue by Blackjack155** [Courseplay/courseplay#4653]
Undzwar bekomm ich das nicht hin das er am Startpunkt beladen soll er fährt dort sofort los auch wenn ich ihm sage Trigger Warten.

Szenario: Ich möchte am Hänlder denn LKW mit Kalk ladenn dann soll er zum silo es abkippen und wider dort hin zurück los fahren wenn er wieder voll ist.

Befüllen bis 100% ist drin

**Comment by Tensuko** [comment]
Du stellst deinen LKW so hin, dass der Trailer am Kalktrigger steht (bzw unter dem Rohr vom Kalksilo).
Dann startest du die Kursaufnahme und fährst den weg ab.
Den Stop machst du VOR dem Trigger wo du Kalk kaufst.
Wichtig: Bei befüllen bis 100% auch einstellen, dass du Kalk laden willst.

**Comment by Blackjack155** [comment]
nein am händerl will ich sie ja via bigpag verladen  aber auch das abladen funksioniert nicht er fährt rükwärt aber läd nicht ab

**Comment by Tensuko** [comment]
Das geht nicht, Bigbags kann man nur zum wieder auffüllen im Mode6 nutzen.

**Comment by Tensuko** [comment]
Bzw ich müsste es probieren, aber der Trigger ist sehr klein und es müsste immer genau stimmen...

**Comment by Blackjack155** [comment]
es ist doch am startpunk beladen
und das wird er doch dann versteh ich nicht warum er nicht wartet bis 100% sind 
wieder aufüllen? das sind die standart dinger 
bei dem silo frag ich mich warum er da nicht abläd? weil dort 2triger sind der eine zum abladen und der andere zum aufladen und wenn er beide passiert das er es nicht hin bekommt?

**Comment by Blackjack155** [comment]
mir is gerade ausgefallen das in die verion 6 schlechter geworden is als die vom 17er man kann ja garnicht mehr mit einer mulde laden und beladen   kein wunder das es nicht geht

warum wurde das enfernt was mal funkzioniert hat?

**Comment by Tensuko** [comment]
> 
> 
> es ist doch am startpunk beladen
> und das wird er doch dann versteh ich nicht warum er nicht wartet bis 100% sind
> wieder aufüllen? das sind die standart dinger
> bei dem silo frag ich mich warum er da nicht abläd? weil dort 2triger sind der eine zum abladen und der andere zum aufladen und wenn er beide passiert das er es nicht hin bekommt?

Beladen am startpunkt:
Entweder er sucht zwischen stop und start einen trigger, oder wenn nicht, wartet er am start, bis er durch irgendetwas seinen eingestellten Füllstand erreicht.

Warum er nicht wartet:
Das kann verschiedene Gründe haben, auch ein schlecht eingefahrener Kurs... wie gesagt, ich muss es ausprobieren.

2 Trigger laden/entladen:
Hat nichts miteinander zu tun.
Was für ein Silo, kann das Silo das Ladegut überhaupt annehmen, wie gesagt, wie sieht dein Kurs aus ? usw usw....



> 
> 
> mir is gerade ausgefallen das in die verion 6 schlechter geworden is als die vom 17er man kann ja garnicht mehr mit einer mulde laden und beladen kein wunder das es nicht geht
> 
> warum wurde das enfernt was mal funkzioniert hat?

Das ist ja schön, wenn du es schlächter findest... dann kannst du ja auch LS17 weiter spielen.
Nur mal so: Man kann sehr wohl mit CP6 mit einer Mulde laden/entladen.

Warum was entfernt wurde ?
Dir ist schon klar, dass der LS19 anders funktioniert was LUA angeht, als LS17 ?
Dir ist schon klar, dass eine ganze menge geändert werden musste, damit CP6 überhaupt für LS19 funktioniert ?
Und ist dir auch klar, dass die Module hier alle neu geschrieben wurden (bis auf Mode2, da hängt es etwas), damit CP überhaupt so gut läuft, wie es das jetzt tut ?

**Comment by Blackjack155** [comment]
Warum was entfernt wurde ? habe ich extra gelöscht denn kommentar...

**Comment by Blackjack155** [comment]
`Warum er nicht wartet`
In wie fern schlecht eingefahren was könnte denn der fehler sein dann könnte ich das nach prüfen?
2 Trigger laden/entladen:
Kann vlt auch am LKW liegen? Problem war das ich einen LKW brauch weil zum rückwärs fahren nicht viel platz ist

**Comment by Blackjack155** [comment]
![fgsh](https://user-images.githubusercontent.com/26688591/70856016-a9ddb200-1ed4-11ea-9e4a-b75493eaf29f.PNG)

**Comment by Blackjack155** [comment]
er so da nicht laden sondern Endladen

**Comment by Blackjack155** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3964468/log.txt)

**Comment by Blackjack155** [comment]
Test jetz mit Standart FZG dort läd er wieder nicht also ich weis nun wirklich nicht ob es ein benutzerfehler ist oder wirglich noch ein Bug

**Comment by Blackjack155** [comment]
Nächster Test anderes FZG  er bleib am Beladepunkt stehn.  Warum ?  

KEINE AHNUNG???  also ich versteh es nicht das er mit welchen fzg kann und dann nicht und das auch mit standart

**Comment by Tensuko** [comment]
Warte es doch ab, ich schau mir das morgen an und mache einen test...
Frage zwischendurch: Sind die Silos auf deinem Bild für Kalk ? Ich kenne die nur für Saatgut und Dünger...

**Comment by Blackjack155** [comment]
Ja dünger kalk und saatgut

test 3.  kein abladen am silo

Okay dann warte ich bis du mir berichtest
brauchst du vlt die karte?

**Comment by Blackjack155** [comment]
Also mit der Horsch gehts aber mit der Lemken nicht

**Comment by Tensuko** [comment]
So, laden an BigBags funktioniert im Mode1 nicht. Aber was sich schon probiert hatte ist, dass sich Saatmaschinen durchaus an BigBags auffüllen, außer Fronttanks, aber dafür gibt es bereits ein Issue, siehe #4584

Rückwärts in das Silo abladen ist kein Problem:
![fsScreen_2019_12_15_16_57_46](https://user-images.githubusercontent.com/27344744/70865302-35e6ec80-1f5c-11ea-9d81-3d07d3987349.png)

**Comment by Blackjack155** [comment]
das ist ein anderes silo
wie gesagt wie bei dir gehts nicht falsdu es vergessen hast ich kann es nicht gerade anfahren

**Comment by Tensuko** [comment]
Der Trigger sollte aber der gleiche sein...
Und ich habe nur so eine lange Strecke, weil ich einen Trailer mit Deichsel habe.
Mit deinem LKW kannst du natürlich einfacher ran fahren.
Das Bild soll auch nur zeigen, wie der Kurs in etwas auszusehen hat.
Ich hab von deinem Kurs ja noch kein Bild gesehen und ein logfile mit debugchannel 1 und 2 auch noch nicht.

**Comment by Blackjack155** [comment]
mach ich dir fertg sobalt ich kann

**Comment by Blackjack155** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3965519/log.txt)
![20191215225515_1](https://user-images.githubusercontent.com/26688591/70869956-5d56ad00-1f8e-11ea-84cf-25c3db72f9c1.jpg)
![20191215225520_1](https://user-images.githubusercontent.com/26688591/70869958-5d56ad00-1f8e-11ea-87df-2338dae5a127.jpg)

wie gesagt beläd er nicht mit Saatgut
Was brauchst du noch?
höffe es ist richtig gemacht

**Comment by Tensuko** [comment]
Mir gings eigentlich um das abkippen aber egal, keine Ahnung woran es liegt, aber er erkennt den Trigger nicht... da du schon probleme mit dem abkippen hast, muss das irgendwie an den Silos liegen....
Aber konntest du da nun andere Saatmaschinen nachfüllen ?

Das wird mir hier auch langsam zu bund!

Es ging erst um Kalk transport mit abkippen, dann saatmaschinen nachfüllen.....

Und ich hatte schonmal ein Problem mit einem Trigger auf der Map, es würde mich also nicht wundern wenn es wieder das selbe ist.... Ich kann die Saatmaschine nochmal ausprobieren, aber mehr auch nicht....

**Comment by Tensuko** [comment]
Kurs:
![fsScreen_2019_12_16_00_12_55](https://user-images.githubusercontent.com/27344744/70870868-06a2a080-1f99-11ea-8316-2d30bcdc8861.png)
Nachfüllen mit der Saatmaschine:
![fsScreen_2019_12_16_00_13_29](https://user-images.githubusercontent.com/27344744/70870869-0b675480-1f99-11ea-87bf-8a67aa484bd7.png)

Also funktioniert, es liegt am Trigger auf der Map.
Grundsätzlich:
Feldkurs+Kurs vom Feld, durch den Trigger, zurück aufs Feld = 2 Kombinierte Kurse.
Wenn das nicht geht, liegt es am Trigger!

Ich mache hier schon mal zu...

**Comment by Blackjack155** [comment]
ja wie soll ich das behebn 

ansosnten welcher mod ist dann teste ich denn mal druch?

**Comment by Blackjack155** [comment]
finde sie nämlich nicht

**Comment by Tensuko** [comment]
Die Silos ? Da fragst du mich jetzt was... Könnte ein Teil vom Hofpack, bin mir aber nicht sicher

**Comment by Blackjack155** [comment]
welche map?

**Comment by Blackjack155** [comment]
weil ohne saatgut nachtfühlung machts kein sinn da ich nun mal gerne mangage und blöd wenn es nicht läuft :D

**Comment by Tensuko** [comment]
Das ist keine Modmap die ich da habe, sag doch einmal genau waa du wissen willst sonst mache ich hier gleich ganz zu.

**Comment by Blackjack155** [comment]
HABE ICH!!! die SILOS damit ich das testen kann was du da gemacht hast ob es auch bei mir dann funkzioniert

**Comment by Blackjack155** [comment]
musst doch deine Mods kennen :D
Standart is es nicht und denn Hofpack denn ich gefunden habe ist dies nicht dabei

**Comment by Tensuko** [comment]
So mir reicht es jetzt.
Ich habe dir genau gesagt, dass es Teil eines Hofpacks ist, das hat mit Maps GARNICHTS zu tun, sondern sind platzierbare Objekte. Und mit großbuchstaben bist du bei mir an der falschen Adresse, das hier ist GitHub und geht um CP Bugs, nicht um deine Map und erst recht keine ModSuche! Such dir vernünftige Saatgut Silos zum platzieren, ich bin hier schließlich nicht deine persönliche Auskunft. So und dami hat sich das hier jetzt erledigt!
