### ISSUE TITLE
CombineUnloadAIDriver: Unloader gets stuck trying to align to waiting combine at the edge of the field

### ISSUE THREAD

**Issue by tanordheim** [Courseplay/courseplay#4654]
I'm running the latest copy from the CombineUnloadAIDriver branch and am running into an issue where the combine gets full when at the edge of the field and the unloader gets stuck trying to find a path to get behind it.

Some screenshots to illustrate:

![20191215141851_1](https://user-images.githubusercontent.com/49933/70863243-31afd480-1f46-11ea-90e1-8acf1e405dee.jpg)
![20191215141855_1](https://user-images.githubusercontent.com/49933/70863245-35dbf200-1f46-11ea-9fe9-04bf0aa0ac53.jpg)
![20191215141916_1](https://user-images.githubusercontent.com/49933/70863250-3a080f80-1f46-11ea-917d-d909a57b8a85.jpg)
![20191215141925_1](https://user-images.githubusercontent.com/49933/70863251-3d030000-1f46-11ea-976b-41c11d4f5185.jpg)

They end up in a stalemate here; the combine is full and is waiting to be unloaded - the unloader can't get where it needs to go because the tractor is in the way.

In this same situation, if the combine was NOT full, the unloader would end up driving along the white line to turn around and crash into the side of the header on the combine.

I don't have any debug logs from this as I'm not fully sure what is of any interest in this situation but I've taken a copy of the savegame a minute or so before this happened so I can easily reproduce it (both the stalemate situation and the crash) to provide any more data on the matter.

Thanks for a really, really great mod - I get you guys have an uphill battle after FS19 with the changes that came but I really appreciate the work you guys put into this. Even this alpha of the new release with its quirks and bugs just adds so much more fun stuff to the game.

**Comment by Elonair** [comment]
I have a similar issue, where the "Headland reverse maneuver" results in both the unloader and the combine proceed to drive straight into each other after the unloading is done. This is however only if the AI choses to use the function midfield. It seems to work around the edges of the field.

As I've been searching for information on this, as i thought i was doing something wrong, i do not have a debug or save game of this, but i will add it to this thread when it happens again, as I'm sure the result can be reproduced.

Thx for a great mod! and all your hard work.

**Comment by Tensuko** [comment]
#5272
