### ISSUE TITLE
Forage harvester and tractor

### ISSUE THREAD

**Issue by Tbol1987** [Courseplay/courseplay#4655]
Hi all,
I'm having problems with harvesting corn using the forage harvester and a tractor+tipper. All runs well until the forage harvester needs to make a turn. When turning to start the next row the tractor will follow. When the harvester starts backing up, tractor and harvester will drive into each other and get stuck. Anyone knows what I'm doing wrong? 

I tried with and without mods, nothing really changes. Log found here: https://drive.google.com/file/d/1Fq997nNNFo60eA7nCGYvt4v68zkEeYYX/view?usp=sharing

Picture of crash attached.  
![CP forage problem](https://user-images.githubusercontent.com/58362844/70863971-fa452600-1f4d-11ea-88e1-cf0a95d1fd16.png)

Thanks!

**Comment by Tensuko** [comment]
See #3311 and #4286 about this Issue.
Closed.

**Comment by Crinouche** [comment]
417/5000
I have the same problem and it is rather annoying.
Tbol1987, the problem will not be resolved until the new mode 2 is active.
(Besides, do you know when the new mode 2 will be active, Tensuko?)
On the other hand, Tbol1987, there is a temporary solution which allows to have less collision: In "specific settings mode" you activate "turn in the field" and the tractor should make a maneuver, at the end of the row.
