### ISSUE TITLE
Unverstendniss

### ISSUE THREAD

**Issue by Blackjack155** [Courseplay/courseplay#4656]
Es kann nicht sein das man ein Problem hat dies hier Meldet versucht denn fehler zu finden und dann noch angelöffelt wird dafür das man ein wenig zuarbeit bekommt !?
Man schreibt mit denn Modern der Map und wird hir her verwissen CP schickt einen einfach wieder weg und man steht da und is kein schritt weiter und hat kein bock mehr auf LS.
Wenn ihr kein Fehlermeldung wünscht dann lasst es ich sitz seit tagen nur am PC um Dateien hin un her zui schicken um denn fehler zu finden und dann wird man Sitzen gelassen!?

Super klasse macht weiter so und keiner hat mehr lust hier was zu Melden

Und noch mal DIE MAPPER SAGEN CP IST SCHULD  also bin ich als  User natürlich der dumme

**Comment by Tensuko** [comment]
Zeige mir das die Funktion in CP nicht gegeben ist im Standart Spiel und es ist ein Fehler! Wenn nur auf bestimmten Maps mit bestimmten Mods haben sich die Modder nicht an die Standarts gehalten! CP supported auch GC mi Erfolg!

Wenn du nichts melden willst, bitte, gibt genug Leute die hier mitmachen, was wir nicht brauch können ist ein chaotisches Issue bei dem zwischen problematiken gewechselt wird. Es ist nicht meine Aufgabe hier dir bei der Modsuche zu helfen, damit du ein funktionierendes Saatgut Silo hast! Wenn CP mit verschiedenen Silos funktioniert aber mit dem auf der Map nicht, liegt es an der Mapwenn du ernsthaft helfen willst CP zu verbesser machvein sauberes Issue mit logfile undcetwas, was auch mit nur CP nicht funktioniert.
Closed, end of discussion.
