### ISSUE TITLE
Will the unloading of two bodies be added?

### ISSUE THREAD

**Issue by terrorbaff** [Courseplay/courseplay#4658]
Hello. My name is MAC. Founder of the LSSA team. 
We have added trailers with two bodies on modhub ( links at the end of the post), I would like to see the possibility of unloading the hire of both bodies. Is it possible to implement on the courseplay? 
P. s Sorry for my translation through translator

https://www.farming-simulator.com/mod.php?lang=en&country=ru&mod_id=140887&title=fs2019

https://www.farming-simulator.com/mod.php?lang=en&country=ru&mod_id=142428&title=fs2019

**Comment by Tensuko** [comment]
Well, I think that is the same Problem as the Wilson Trailers.
Do you switch the bodies with the key N too ?

**Comment by terrorbaff** [comment]
Yes, the principle works as on Wilson Trailers. Only switching between bodies is made by the U key

**Comment by SteelRodent** [comment]
These trailers have tip-side as well as switching compartment on the same function, so imagine it'll be a little trickier to code than for the wilson trailers (which only have front/rear)

**Comment by Tensuko** [comment]
Combine Issues:  #3060

**Comment by Tensuko** [comment]
@terrorbaff 
I know this is an very old Issue, but I wanted to inform you somehow, that you Trailers are working now, even with 2 seperate fillTypes to load.
We used some kind of tweak by flipping arround the 'tipside' but only the 1st two entries are used, so the 1st two are both the right side so can only tip to the right, but it is working :)
