### ISSUE TITLE
Courseplay Driver Colides with Objects Frequently

### ISSUE THREAD

**Issue by Robinsonb1980** [Courseplay/courseplay#4659]
![20191216132927_1](https://user-images.githubusercontent.com/31859651/70936566-2ae99600-2008-11ea-850c-312b680122a6.jpg)
When observing the Courseplay Drivers, I notice an issue where a driver when he is turning to line up to plow next row, or any sort of field work will run into a tree or a light post or get stuck on a rail track depending on the map you use.   Right now the only way to get them back on course is manually stop them and adjust the tractor then have it continue on the current or nearest waypoint.

This issue kind of makes it difficult to get fields done with courseplay, and so I wanted to mention this as a bug issue to fix in the next release if it can be please? Thanks for any help in advance on this issue :)

**Comment by bojanh66** [comment]
Do 2-3 headlands and tractor will stay on field when turning to next row.

**Comment by Tensuko** [comment]
Can also try to reduce the turn radius a bit.

**Comment by Robinsonb1980** [comment]
Ok Will try that thank you :)

**Comment by Robinsonb1980** [comment]
Just to note, changing the Lane offset helps with this issue as well as long as no turn is being made.
