### ISSUE TITLE
Adjustable Steering Wheel

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#4660]
In several tractors and combines, the steering wheel moves toward the driver once in the vehicle, but when CP starts driving, the wheel is locked in the forward position away from the driver.

Generic map
Tractor 818 Vario & others

**Comment by Tensuko** [comment]
Well, that is just for nice looking and nit rly on a high priority...
What does the normal GIANTS helper look like ? Does he also pull the wheel towards the driver ?

**Comment by lcc1211** [comment]
Same for Giants. The 818 Vario is from the game. So for both mods and in-game machinery.

**Comment by pvaiko** [comment]
Wow. Once issues like this are the most serious ones on the list, we'll address it.. Closing to keep to issue list clean.
