### ISSUE TITLE
Einfahren Cours für Laden der SaatDrille

### ISSUE THREAD

**Issue by Blackjack155** [Courseplay/courseplay#4661]
Ich habe das Problem das ich es nicht schaffe das die Drille vom feld zum Silo fährt und dort Saatgut nachtankt  ich habe mehrere Silos verwendet mehre Course eingefahren mods enfernt und weiß nicht an was es liegt

Mods die ich verwenden:
![Unbenannt](https://user-images.githubusercontent.com/26688591/70996871-01963c00-20d4-11ea-9747-1ee570215cab.PNG)

vlt liegt es an Seasons 19? Vlt auch an company?

ich weiß es nicht können ja nicht alle Mods fehlerhaft sein denn bei anderen geht nur bei mir nicht

bin auch ma versuchen an denn modern vom seasons heran zu tretten um denn fehler zu finden mehr weis ich mom auch nicht zu tun

**Comment by Blackjack155** [comment]
Getestet mit Neuen Spielstand und Ohne Seasons  Der Fehler Bleibt weiter hin
![20191217141344_1](https://user-images.githubusercontent.com/26688591/70998411-99e1f000-20d7-11ea-8210-846774ffe0fb.jpg)
![20191217141242_1](https://user-images.githubusercontent.com/26688591/70998412-99e1f000-20d7-11ea-90e6-26e2208907ec.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/3973422/log.txt)

**Comment by Tensuko** [comment]
Feldkurs erstellen -> Speichern
Auffüllkurs erstellen -> Speichern
Feldkurs laden -> Auffüllkurs anhängen (Der Ordner mit dem + drin)
Am Ersten Wegpunkt starten (Düngen/Säen Mode4)

Achtung: Man sollte etwas Saatgut in der Saatmaschine haben, ansonsten kann es ein Problem beim fortsetzen des Feldkurs geben, wenn er am Start anfangen soll, bin noch nicht dahinter gestiegen warum das so ist.

Und eine ganz besondere Frage an dich:
Hast du in dem Silo denn Saatgut drin?! Das ist halt nur ein Lager...
Und ich sehe du hast nun die anderen Silos gefunden, es würde auch mit dem auf deiner Map funktionieren, ich hab es ja getestet. Aber versuch nun erstmal so.

**Comment by Blackjack155** [comment]
es ist nicht gölich denn fehler zu finden ich habe ALLE mods einzeln getestet da kann er es laden lade ich dann alle mods gehts auch so warum geht es dann im anderen spielstand nicht? gleiche mods alles das selber auch die Karte aber dann geht es nicht mehr?

ich versteh nicht wie aus einem Düngersilo Saat draus kommen kann also ich kann denn Fehler nicht erklären

**Comment by Blackjack155** [comment]
> Feldkurs erstellen -> Speichern
Auffüllkurs erstellen -> Speichern
Feldkurs laden -> Auffüllkurs anhängen (Der Ordner mit dem + drin)
Am Ersten Wegpunkt starten (Düngen/Säen Mode4)

genau so gemacht habe extra tut geschaut alles 1 zu 1 nach gemacht

**Comment by Tensuko** [comment]
Das Silo hat einfach FilLType drin, da musst du den Modder fragen.
Eventuell hast du nicht das getan, was ich dir geschrieben habe.

Außerdem solltest du mal an deiner Formuleirung arbeiten, man kann manchmal sehr schwer rauslesen, was du eigentlich willst odermeinst.



> 
> 
> > Feldkurs erstellen -> Speichern
> > Auffüllkurs erstellen -> Speichern
> > Feldkurs laden -> Auffüllkurs anhängen (Der Ordner mit dem + drin)
> > Am Ersten Wegpunkt starten (Düngen/Säen Mode4)
> 
> genau so gemacht habe extra tut geschaut alles 1 zu 1 nach gemacht

In deinen Screenshots schaut es aber anders aus, sonst würde im HUD stehen 2 Kombinierte Kurse...

**Comment by Blackjack155** [comment]
Ich habe denn Feld kurs dann denn kurs zum hof dann kurs zum silo dann kurs zum feld  PUNKT
das is das was ich eingestellt habe so sollte er ja gelegt werden?

**Comment by Blackjack155** [comment]
> In deinen Screenshots schaut es aber anders aus, sonst würde im HUD stehen 2 Kombinierte Kurse..
ist es doch auch? dort sind in dem sinne 4 Kurse drin.

**Comment by Blackjack155** [comment]
kleine bug am rande erwähn cp frag am anfang nur ob er die felder scanen soll icht ob der helfer auch bezahlt werden soll  is mir nur aufgefallen

**Comment by Tensuko** [comment]
Das ist kein Bug Herr Gott.... Das ist eine Frage, ob du das willst und das beantwortest du einmal und gut ist! Danach kannst du das in Advanced Settings auch umstellen.

**Comment by Tensuko** [comment]
So und hier der Videobeweis:
https://1drv.ms/v/s!ArGbP_j369r8kxqDfrD90_MUq6xY

**Comment by Blackjack155** [comment]
> Das ist kein Bug Herr Gott.... Das ist eine Frage, ob du das willst und das beantwortest du einmal und gut ist! Danach kannst du das in Advanced Settings auch umstellen.

nein ich mein das er das eben nicht mehr fragt!!!

**Comment by Blackjack155** [comment]
> So und hier der Videobeweis: 

der bringt aber mir nichts :D und du hast ja 2 kurse bei mir sind es 4 wie schon gesagt

**Comment by Tensuko** [comment]
Er soll auch nur am start des savegames fragen!
Da deine 4 Kombinierten Kurse guck mal was da aus dem Silo in die Saatmaschine rieselt...
![fsScreen_2019_12_17_15_59_58](https://user-images.githubusercontent.com/27344744/71006896-5d69c080-20e6-11ea-8e1a-cefdc23f953f.png)

Noch ein letztes mal:
Feldkurs laden, nacheinander deine 3 Kurse mit dem +Ordner dazu laden.
Und auch noch mal die Frage: Hast du überhaupt Saatgut im Silo?!

Das ist jetzt deine letzte Chanze anständig zu reagieren, ansonsten ist heir gleich Schluss, ich bin hier nur am hin und her schalten und deinen Kram testen und krige nur unmöglichen Antworten von dir!

**Comment by Blackjack155** [comment]
> Er soll auch nur am start des savegames fragen!

ist richtig so kenne ich das ja auch aus 15 und 17 aber das tut er aber nicht verstest du? er hat nicht gefragt und das hat er noch nie bei mir im 19er. das muss ich selbst in der xml nach tragen. 

Laden nach einaders okay so abe ich es auch gemacht 
ich zeige dir gleich wie ich die zusammen stelle das is ein neues save muss ich erst alles ein fahren dann kann ich dir das zeigen

**Comment by Tensuko** [comment]
Das heist die Frage kommt auch nicht, wenn du ein neues Savegame auf machst ?
Frage mich gerade wo du Courseplay runtergeladen hast....
Lade dir einmal hier die .zip Datei runter https://github.com/Courseplay/courseplay/releases/tag/6.01.00344 und benenne diese in FS19_Courseplay um (und bitte genau so und nur umbenennen).
Dann schmeißt du deine andere Courseplay Version raus (die hast du FS19_xXx_Courseplay genannt).

**Comment by Blackjack155** [comment]
> Das heist die Frage kommt auch nicht, wenn du ein neues Savegame auf machst ?

nein
>  Frage mich gerade wo du Courseplay runtergeladen hast....
 
von euch hir

> und benenne diese in FS19_Courseplay um (und bitte genau so und nur umbenennen).
Dann schmeißt du deine andere Courseplay Version raus (die hast du FS19_xXx_Courseplay gen

habe ich nur so genannt da es ja beim 15er und 17er üblich war das das zu letz geladen werden musste

**Comment by Blackjack155** [comment]
hofe du das geht so

![20191217170535_1](https://user-images.githubusercontent.com/26688591/71012530-90648200-20ef-11ea-85ce-58b9b6047721.jpg)
![20191217170512_1](https://user-images.githubusercontent.com/26688591/71012532-90648200-20ef-11ea-8110-fa7d9919820c.jpg)
![20191217170518_1](https://user-images.githubusercontent.com/26688591/71012533-90648200-20ef-11ea-99c0-3a2e83d37b52.jpg)
![20191217170529_1](https://user-images.githubusercontent.com/26688591/71012534-90fd1880-20ef-11ea-9ea2-f917c3cf7c83.jpg)

**Comment by Blackjack155** [comment]
aber es geht wieder nicht ich gebs auf ich habe keine ahnung mehr er fährt zum silo und läd mal wieder nicht

**Comment by Blackjack155** [comment]
es macht kein sinn es sind die gleiche mod beim testpiel hat er geladen nun geht es wieder nicht also mal erlich das ist nicht normal

**Comment by Tensuko** [comment]
Jetzt wechselst du wieder zu etwas anderen.... 
Hast du bei dem Streuer denn auch eingestellt, dass der Dünger laden soll ? Das ist auf Seite 4 im HUD.
Da der Streuer Kalk und Dünger laden kann, musst du das auch richtig auswählen.

**Comment by Blackjack155** [comment]
> Hast du bei dem Streuer denn auch eingestellt, dass der Dünger laden soll ? Das ist auf Seite 4 im HUD.
Da der Streuer Kalk und Dünger laden kann, musst du das auch richtig auswählen.

das ist mir wirlich sowas von peinlich jetz fährt und läd er es nein das war dort falsch eingestellt :(
ich kannte diese einstellung nicht beim15 und 17 ging das so gott tut mir das leid  

dann is ganz klar warum er nicht geladen hat wie auch er will kalk laden fährt aber unter ein dünger silo und bei der drille wird es sicher auch flasch gewesen sein

ich teste das gleich noch mit der drille wenn er mit düngen fertig is ob die dann auch läd dann war echt ein übersehn

**Comment by Tensuko** [comment]
Bei Saatmaschinen gibt es die Option nicht, da sie entweder beides oder nur eines braucht.
Düngerstreuer können halt nur eins laden.

**Comment by Blackjack155** [comment]
kann cp es nicht ab wenn man durch 2 silos fährt? weil das war ja voher so er solte bei mir erst duchs dünger dann druchs saat silo für drilln die beides laden können?

**Comment by Tensuko** [comment]
Das sollte ohne Probleme funktionieren.

**Comment by Blackjack155** [comment]
So getestet mit der doppelkammer drille  geht auch
weiß nicht wo der fehler gelegen hat
kann das sein das der cach und alte save gelöscht werden müssen bevor man neu anfängt das er daher probleme hate die triger richtig zu erkennen?

**Comment by Tensuko** [comment]
Kann ich nicht ausschließen, kann also gut sein.
Funktioniert es denn jetzt, so dass ich das hier als erledigt abhaken kann ?

**Comment by Blackjack155** [comment]
das fehler mit dem lohn müsste noch geklärt werden

ich teste das jetz mal ausgiebig und gebe dir bescheid

**Comment by Blackjack155** [comment]
<CPSettings>
    <courseplayHud posX="0.335938" posY="0.029861" hudScale="1.000000" uiScale="1.000000">
	NOTE 1: Do not change the uiScale Manually.
	NOTE 2: If you change the hudScale and you haven't changed the posX and posY manually,
			then you need to delete the posX and posY section to center the hud again.
	</courseplayHud>
    <courseplayFields onlyScanOwnedFields="true" debugScannedFields="false" debugCustomLoadedFields="false" scanStep="5"/>
    <courseplayIngameMap active="true" showName="true" showCourse="true"/>
    <course2D posX="0.650000" posY="0.350000" opacity="0.700000"/>
    <workerWages value="100"/>
    <autoFieldScan active="true"/>
    <loadCoursesAtStartup active="false"/>
    <earnWages active="false"/>
</CPSettings>

solte auch nicht das geld höher sein`??

**Comment by Blackjack155** [comment]
Solte nicht auch das Geld höher sein?

![Unbenannt](https://user-images.githubusercontent.com/26688591/71023224-8e57ee80-2102-11ea-9eba-c722a102e050.PNG)

**Comment by Tensuko** [comment]
Da gibt es nichts zu klären, es funktioniert so wie es soll.
Einmale Abfrage beim Start eines neuen Savegames, wenn das alte Savegame sauber gelöscht wurde klappt das auch.
Nachträgliches ändern geht im CP HUD unter einstellungen, advanced settings, dort im 2ten Reiter...

**Comment by Blackjack155** [comment]
neben bei wo kann ich fragen stellen was ich alles mit kursen machen kann und allg. das gehört sicher nicht her hin?

**Comment by Tensuko** [comment]
Youtube xperijenz der hat gute tutorials.

**Comment by Blackjack155** [comment]
ja das stimmt die habe ich gesehn aber es fehlen einige wie z.b. rückwers abkippen für die rübenmiete oder schaufel befüllen ect :)

**Comment by Blackjack155** [comment]
was ist eigl mit dem zusammen klappen der maschiene geworden bei beendigung ihrer arbeit geworden?

**Comment by Tensuko** [comment]
Glaub das macht er aktuell nur wenn du unter Advanced Settings das Am Startpunkt enden aktiviert hast.

**Comment by Blackjack155** [comment]
okay Danke
ich habe leider kein Video gefunden wegen dem Rückwärs abkippen  kennst du eins?
und ich habe es nich nie mit cp geschaft der das Silo verdichtet ach mit 3 Videos angeschaut allein von Gadarol ich weiß nicht ob vlt an denn Silos an sich liegt oder ob ich einfehler übersehe

**Comment by betrox007** [comment]
@Blackjack155 https://www.youtube.com/watch?v=FwxV5eXKUtQ&t=21s This The Sample Course for Field work with Refill Course.. Thanks

**Comment by Blackjack155** [comment]
@betrox007  das problem wurde schon längst gelöst :) Aber danke

**Comment by Tensuko** [comment]
Das Thema sollte nun endlich gegessen sein.
Closed.
