### ISSUE TITLE
drive.lua:114: attempt to index a nil value

### ISSUE THREAD

**Issue by rt-2** [Courseplay/courseplay#4663]
I get this error and the game freezes
```
2019-12-18 18:25 Error: Running LUA method 'update'.
2019-12-18 18:25 C:/Users/rt-2/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay/drive.lua:114: attempt to index a nil value
```

**Comment by Tensuko** [comment]
Full logfile. Just drag and drop the log.txt into comment box and we need to know what you did what Tool you used...

**Comment by rt-2** [comment]
quick edit, might fix: https://github.com/Courseplay/courseplay/pull/4664

**Comment by rt-2** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3980970/log.txt)
I don't know how to reproduce the bug yet, will keep an eye open

**Comment by Tensuko** [comment]
Is 1.3.0.1 the newest LS Patch for normal Version ?

**Comment by rt-2** [comment]
negative, I have stopped updating because I had issues with v1.4.1.
This mod announces itself compatible with the first version https://github.com/Courseplay/courseplay/blob/master/modDesc.xml#L2

**Comment by pvaiko** [comment]
Since you did not supply any details on what you were doing when this happened I can only assume it was the old Mode 2 (as nothing else should be using drive.lua now) which isn't supported anymore. 

Reopen if you can reproduce it in any other mode.

**Comment by rt-2** [comment]
To me it seems like a worker with a route is removed and the plugin is still trying to execute that route. Not sure.
