### ISSUE TITLE
Field generating short edges plus racetrack

### ISSUE THREAD

**Issue by rt-2** [Courseplay/courseplay#4665]
If you try to generate a field route with 'Short edges' and 'Racetrack' at the same time, it will not generate it, the mouse will lag
```
2019-12-19 09:12 CourseGeneratorScreen:onCreate()
2019-12-19 09:12 Error: Running LUA method 'mouseEvent'.
2019-12-19 09:12 C:/Users/rt-2/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00344/course-generator/Pathfinder.lua:500: bad argument #1 to 'ipairs' (table expected, got nil)
```
[log.txt](https://github.com/Courseplay/courseplay/files/3983956/log.txt)

**Comment by Tensuko** [comment]
Try to generate the course with channel 7 active and post the log

**Comment by rt-2** [comment]
I found out that I need to keep the "starting position" untouched or it will not bug in my case. Here is a example

**Comment by pvaiko** [comment]
You may be the first one who tried this combination...

**Comment by rt-2** [comment]
I worked on this and I was able to track the problem to https://github.com/Courseplay/courseplay/blob/master/course-generator/track.lua#L180 it seems as if the the function does not receive any headlands or islands, so 2 empty table.

https://github.com/Courseplay/courseplay/blob/master/course-generator/track.lua#L319L336
in this function, courseGenerator.headlandPathfinder:findPath is called with empty to/from.
The error is in ``HeadlandPathfinder:findPath`` inside Pathfinder.lua because the ``headlands`` variable is still empty....

To me it seems to only happen with the ``racetrack`` mod, meaning there should be a problem in this condition I think.

Im too tire to analyze all deeply but good luck

**Comment by rt-2** [comment]
Plus, it seems to be the combination of 3 things, The 'short edges' option, the 'racetrack' option, and im not sure, but it seems like it must be the first thing you try, I can have the error multiple time as I want, but once I get a successful try, the error is not coming back.

**Comment by rt-2** [comment]
There is a bug with the mouse at the moment when this happens, I will send the same message that says to double check the parameter, anyway it seems to only do that with an empty route/perimeter.
When you first enter the game, if you change nothing and press ok, the message will tell to modify the query, it is totally valid to send the same message,

**Comment by pvaiko** [comment]
What is the status on this?

**Comment by rt-2** [comment]
I had implemented a fix that at least wouldn't lag the mouse. Its not in the file right now Im not sure why and/or since when.

**Comment by Tensuko** [comment]
Generating with Short Edges was not a Problem with V 02.00040 right now, but on a normal rectangular field.
Might have Problmes on od shaped one.
