### ISSUE TITLE
IN-Game worker ends while courseplay still keeps going 

### ISSUE THREAD

**Issue by henrypeas** [Courseplay/courseplay#4674]
The IN-Game worker ends while the courseplay one still keeps going then when I try to enter the vehicle my game crashes so i dont know what to do

**Comment by Tensuko** [comment]
step one: post your logfile: https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
Closed due to inactivity.
Post log and provide more detailed information, then reopen.
