### ISSUE TITLE
Pflügen mit CP

### ISSUE THREAD

**Issue by Blackjack155** [Courseplay/courseplay#4677]
Was ich nicht versteh CP kann mit aufgehaneden Pflug fahren aber hat man ein Pflug dran der ein Gelenk vorna hat Fährt er damit Falsch. Also er versucht Rückwärs zu fahren und Hält denn Pflug nicht in der Spurkurve so das er sich verkeilt. Hofe man versteht es.
Warum Dreht CP nicht nach vorne um wenn der es Rückwärs nicht kann?

Beispiel Pflug Lemken Titan 18

**Comment by Tensuko** [comment]
Auf dem Feld wenden deaktivieren versuchen...

**Comment by Blackjack155** [comment]
Das mit denn 2 Fzg auf einen Kurs geht auch nicht dahren beiden hintereinader obwohl der eine link und der andere rechts hat
![20191221140743_1](https://user-images.githubusercontent.com/26688591/71308329-55b65e80-23fb-11ea-8888-3f0b2db7b002.jpg)

**Comment by Tensuko** [comment]
Weder kenne ich deinen Kurs, noch sehe ich die Einstellungen von beiden Fahrzeugen.
Es gibt auch einen unterschied zwischen 'geht nicht' und 'nicht richtig eingestellt'...

**Comment by betrox007** [comment]
if using 2 or more tractor working together in one field, better generate course with headland,using 2 or more headland, also deploy the 2nd tractor after the first tractor run the second turn,and so on for the next tractor

**Comment by Blackjack155** [comment]
2019-12-22 02:51 :44 [info lp597255] TGX 26.640: has no Courseplay installed, not adding Courseplay data to savegame.

was heißt das?
CP ist doch instaliert und wieso fügt er keine savegame daten hinzu?
