### ISSUE TITLE
Error: Running LUA method 'mouseEvent' - triggers.lua:648: table index is nil

### ISSUE THREAD

**Issue by prehnj112** [Courseplay/courseplay#4678]
Hallo ich habe ein Problem mit der neusten Version, aber seid neusten auch mit der älteren, das wenn man den CP startet ein Pfeil kommt und dann der LUA Fehler in der log.
Anbei ein Bild davon.
MFG prehnj112

![fsScreen_2019_12_22_01_12_47](https://user-images.githubusercontent.com/54482369/71315267-e2dbd080-2458-11ea-9b88-9ce15f02b9f0.png)

**Comment by Tensuko** [comment]
Komplettes logfile bitte und wenn es mit allen Versionen so ist würde ich mal die anderen Mods hinterfragen.

**Comment by prehnj112** [comment]
Ok hier die Log.
Das einzige was neu ist ist die Karte.
[log.txt](https://github.com/Courseplay/courseplay/files/3992428/log.txt)

**Comment by Alphaone1709** [comment]
Das problem wird durch die Rade map verursacht. Denn nur dort scheint der Fehler zu bestehen. Jetzt mehrfach in Foren und Facebook gelesen. Alle anderen Maps laufen normal ohne fehler

**Comment by prehnj112** [comment]
Ok danke für die Hilfe, hoffentlich wird es an der Map noch gefixt.

**Comment by Tensuko** [comment]
Übriens ist eine wichtige Regel, immer nur eine Map im Mods Ordner zu haben.
Mache dann heir zu.
