### ISSUE TITLE
Suggestion: Add timer "start in x minutes"

### ISSUE THREAD

**Issue by C43AMG** [Courseplay/courseplay#4680]
To have a smoother workflow i would like to have a timer for starting the course for each helper.

Some times there are smaller distances between farmers so they drive into each other. I mark a example on the picture, if i have the choice to start the mashines with a timer these problems wont exist.

https://imgur.com/34YsChJ

I have 3 seat mashines on this track on the marked position they will make a crash if i start all at the same time, i also cant setup the distance to the front so high that the crash wont happen

**Comment by Tensuko** [comment]
Why not use Convoy ?

**Comment by C43AMG** [comment]
> Why not use Convoy ?

As i mentioned, the convoy is great for sure, but i only can setup 200m, it would be also helpful if i coulp make it like 2000m, then this would also get solved :)

**Comment by Tensuko** [comment]
For what do you need such a big distance ?
The Driver won't get any closer then 200m if you set it up...
Remember you have to activate that on all 3 Driver.

**Comment by wakka79** [comment]
Oh I would love the ability to set the distance in convoy further apart. I keep having unloaders tangling with my combines even when set to 200m.

**Comment by C43AMG** [comment]
> Oh I would love the ability to set the distance in convoy further apart. I keep having unloaders tangling with my combines even when set to 200m.

Would also appreciate that :)

**Comment by Tensuko** [comment]
Unloaders got nothing to do with Convoy....
That is Mode2....
