### ISSUE TITLE
Gemeinde Rade courseplay funktioniert nicht

### ISSUE THREAD

**Issue by GogsDS** [Courseplay/courseplay#4681]
Ich habe diesen Fehler bemerkt und der Kurs will nicht laufen!

http://imgbox.com/7hrKawub

Danke, wenn etwas behoben werden kann!

Ich habe das gleiche Problem im GE-Forum gefunden!

https://forum.giants-software.com/viewtopic.php?f=958&t=156665

**Comment by Tensuko** [comment]
Das Problem ist bekannt siehe hier #4678
