### ISSUE TITLE
Häcksler fährt nicht, Map: Gemeinde Rade

### ISSUE THREAD

**Issue by michel5998** [Courseplay/courseplay#4682]
moin,
ich habe ein Problem mit CP auf der neuen Gemeinde Rade. Ich habe mir einen Course für den Häcksler erstellt damit er im Feldarbeitsmodus das Feld häckselt, so wie ich es halt immer mache, Flotte steht schon aber wenn ich CP einstelle sieht es folgender Maßen aus 
![fsScreen_2019_12_23_00_21_02](https://user-images.githubusercontent.com/49126733/71328629-9a84e700-251a-11ea-852d-3d755b67e6c3.png) in diesem Beispiel habe ich einen Claas Jaguar geholt, da ich anfangs dachte dass es mit dem John Deere Häcksler vom Kemper-Pack von Giants zusammen hängt.  Wenn ich einmal auf "Abfahrer einstellen" geklickt habe, kann ich den Häcksler nicht mehr steuern, weder lenken, beschleunigen oder bremsen. in dem Beispiel blieb der Tempomat drin und ich konnte den Häcksler nichtmal mehr ausstellen. Wenn ich aussteige, bleibt eine Person im Häcksler sitzen, der tut aber nix 
[log.txt](https://github.com/Courseplay/courseplay/files/3993119/log.txt)
 hier noch die Log, ich hoffe ihr könnt mir weiter helfen und ich hoffe, dass ich es genau genug beschrieben habe

PS: hab gerade gelesen dass  die Log recht unübersichtlich ist daher hier der Fehler der aufgetaucht ist als ich den Abfahrer einstellen wollte:

2019-12-23 00:20 Error: Running LUA method 'mouseEvent'.
2019-12-23 00:20 C:/Users/Florian/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/triggers.lua:648: table index is nil

**Comment by Tensuko** [comment]
Das ist ein Problem der Map, siehe #4678
Closed.
