### ISSUE TITLE
Error while starting dedicated server

### ISSUE THREAD

**Issue by 820fahrer** [Courseplay/courseplay#4683]
Hey guys,

I know that the CP mp support is new and not everything is working at the moment.

My problem comes up when I restart the server. On the first run with no exisiting CP folders etc. the server starts and you can join without any problem.
Without any change on the files or the game I just restart the server and then this appears in the log:

`2019-12-23 09:02 Error: Running LUA method 'loadMapFinished'.
2019-12-23 09:02 C://gameservers//s1335822//ls2019//gameProfile/mods/courseplay/debug.lua:96: attempt to index field 'debugChannels' (a nil value)
`

Next thing I just tried: delete the settings.xml so CP has to create it on start, then there is no issue.

Next thing: I activated debug lvl 5 (mp debug) in the ingame settings. Now it's working after a restart. Maybe the debugchannels array doesn't exist? I'm not familiar with lua programming or scripts for FS.

Is there any quick fix for this?

**Comment by Tensuko** [comment]
@davboecki can you take a look at this one ?

**Comment by davboecki** [comment]
Yes, I'm already trying to figure this one out.

**Comment by davboecki** [comment]
I'm currently not able to reproduce this. 
Do you have any other mods installed when testing this?
What exactly did you do to get this error?

I tried:
* Start Dedi server
* Choose empty game slot
* Start FS Server
* Connect with Client
* Log in as Admin
* Save Game
* Logout
* Stop Game Server
* Start Game Server
* Connect with CLient

Everything worked. No errors inside the Server log

I also tried: 
* Start Dedi server
* Choose empty game slot
* Start FS Server
* Connect with Client
* No Saving
* Logout
* Stop Game Server
* Start Game Server
* Connect with CLient

And I also tried: 
* Start Dedi server
* Choose empty game slot
* Start FS Server
* No Client connection
* Stop Game Server
* Start Game Server
* Connect with CLient

Everything worked fine all the time.

Maybe upload a complete log as well.

**Comment by 820fahrer** [comment]
At first,
I'm sorry, but there are plenty of other mods installed. It's the server we use with some friends and we installed CP yesterday after the MP release.

So it's an old savegame. ~115h playtime.

I know that this could cause problems. 
I will do some more testing today. 

I tested the restart again after I made the debug level change:
Start Server
Connect with client
Activate debug level 5
Disconnect
Restart Server
Issue appears again.

Maybe the script is searching for the debugging functions etc. on server side, but debugging is only available on client side? I don't know the functions..

I will upload the full log from several test runs (first start, incl. client forced save, restart, etc.)

**Comment by davboecki** [comment]
Even with my own big modpack I'm not able to reproduce this, so its probably one specific mod or modcombo I don't use. Hopefully, the log will help.

**Comment by davboecki** [comment]
Maybe you can upload the faulty settings XML as well while you're at it, maybe that will help as well

**Comment by 820fahrer** [comment]
Hi

I've tested as follows:
started the server without existing settins xml
joined the server via client and changed the settings xml -> activate wages
saved the game end exit
restart the server without any other change, issue appears

[log](https://pastebin.com/jUt7eCZx) and [settings xml](https://pastebin.com/ss3Zr6Xv)

After that test, I've deleted the settings xml and restarted the server: no issue appears.

**Comment by davboecki** [comment]
[courseplay.zip](https://github.com/Courseplay/courseplay/files/3995693/courseplay.zip)
Would you mind testing if this cp version fixes it?

**Comment by 820fahrer** [comment]
I've tested this version now several times with ingame connection and saving changes.
Now the server starts without any issue.

Thanks for your help. :)

**Comment by davboecki** [comment]
See: https://github.com/Courseplay/courseplay/pull/4685
