### ISSUE TITLE
Problem mit Häcksler auf Gemeinde Rade

### ISSUE THREAD

**Issue by michel5998** [Courseplay/courseplay#4684]
moin das probem ist aktuell auf der gemeinde rade map, ich habe einen feldarbeitscourse gemacht, doch es will einfach nicht funktionieren. jedesmal wenn ich versuchen will den fahrer einzustellen, geht es nicht 
![fsScreen_2019_12_23_17_02_35](https://user-images.githubusercontent.com/49126733/71367676-0e200600-25a6-11ea-966b-70b4feda68e7.png) das kommt dabei raus, der fahrer fährt nicht und die maschine kann ich dann auch nicht mehr bewegen, ich kann niemanden entlassen und niemanden einstellen, der häcksler bleibt stehen, läuft und es sitzt die ganze zeit ein fahrer drinn aber es passiert nix 
[log.txt](https://github.com/Courseplay/courseplay/files/3995506/log.txt)

getestet hab ich es mit dem john deere häcksler vom kemper pack und später mit dem claas jaguar vom claas dlc

**Comment by Tensuko** [comment]
Das habe ich dir eben schonmal gesagt:
Das ist ein Problem der Map, siehe #4678
Closed.
