### ISSUE TITLE
Course does not start on the Map Gemeinde Rade

### ISSUE THREAD

**Issue by Dadageneral** [Courseplay/courseplay#4686]
Hello,

First, your mod is excellent.

When starting the Course, only one arrow indicates the starting position, then the tractor does not move.
To take control of the tractor, you need press "H". 

[log.txt](https://github.com/Courseplay/courseplay/files/3996403/log.txt)

**Comment by Tensuko** [comment]
Map Issue.
Check their website for infos and this Issue #4678

Closed.
