### ISSUE TITLE
Fehler mit IC Steuerung

### ISSUE THREAD

**Issue by Blackjack155** [Courseplay/courseplay#4687]
CP Funktioniert nicht mit IC Steuerung wie z.b. mit denn Fendt Vario 900 S5. Ich habe mich auch an denn Moder gewendet zwecks dieses Problem. Es liegt an CP.
Und zwar volgendes Passiert Sobald man CP höffnet Flackert die maus und belibt in der Mitte des Bildschirmes hängen, aber nur so lange wie man das CP Hud offen hat.
Wäre schön wenn man das Beheben könne.

**Comment by Merrlin** [comment]
Ist bekannt... Lies dir halt Mal die issues durch, vor allem die abngepinnten, bevor du ein neues aufmachst.
Sonst wird's hier absolut unübersichtlich.

**Comment by Blackjack155** [comment]
Ich hatte kein Betreff mit IC Steuerung gesehn...

**Comment by Tensuko** [comment]
Duplicate of #4185
Closed.
