### ISSUE TITLE
MP, Dedi, 2 or more Vehicle

### ISSUE THREAD

**Issue by Justice-Molton** [Courseplay/courseplay#4688]
If I want to use more as one vehicle on the same field doing fieldwork. They doesn't react to the Lane offset. They always drive in the center.

**Comment by Tensuko** [comment]
@davboecki not sure what you can do about that, be we really appreciate the work you put into making CP MP ready <3

**Comment by Justice-Molton** [comment]
Merry Christmas! This can wait :-)

**Comment by Justice-Molton** [comment]
I can adjust it via the manual offset, but I guess that it is supposed to work with the left and right options

**Comment by davboecki** [comment]
Could you retest this and make sure what you are trying also works in SP. Because from my limited testing at the moment this get's the Works on my Machine Label...

**Comment by pvaiko** [comment]
Is this the same as https://github.com/Courseplay/courseplay/issues/4677#issuecomment-568180074

**Comment by Justice-Molton** [comment]
Of course I’ll let you know.

**Comment by Justice-Molton** [comment]
@pvaiko yes it’s kinda the same issue. I’ll test soon if it work in SP. Do I need to use the latest version or is the initial MP supporting Version enough?

**Comment by Justice-Molton** [comment]
So for me, it works like intended in SP. MP doesn't work with the selection of left and right, only if I adjust the manual offset it works.

**Comment by davboecki** [comment]
What vehicle with task are you trying to use?

**Comment by Justice-Molton** [comment]
With 2 Fendt 1050 and two Amazone 15000

**Comment by PHansen940** [comment]
I can reproduce this issues; MP; dedicated server; Vehicles: John Deere 8R, plowing

Is this still on the "To do"-list?

If I try to adjust it with manual offset, vehicle reacts but steers back immediately to the center line, ignoring the manual offset as much as it ignores the setting "1 left" or "1 right"

**Comment by PHansen940** [comment]
Correction: Manual offset does not work with the Mod plow, it works with a standard cultivator.

Even though, original problem stays the same

**Comment by Blonde-Bomber** [comment]
Just wanted to comment I am also able to reproduce this issue in MP, dedicated server, 2x John Deere S790, Harvesting Soybeans.

I am however able to manually set the left and right offset and it's respecting them.

**Comment by Tensuko** [comment]
Collecting all in #5484
