### ISSUE TITLE
SelfUnload and Merry Christmas!

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/courseplay#4690]
Hello Together,

With the new 6.01.00347 release you can activate the SelfUnlaod feature for combines (beta) in the Advanced Settings screen.

![Unload](https://user-images.githubusercontent.com/27344744/71419760-843d6f00-2671-11ea-9f02-5e38b9e5a508.png)

The trailer must be on the field or within 20 meters of it and have some free capacity for the combine to find it.

You can let a Mode1 Driver wait at a start point to be filled or just place trailers on the field and drive them off later.

I would like to show you an example video, but YouTube is making fun of me and jumps arround in the upload percent... Maybe I can add this later.

If you like the work of our developers and want to support them a bit, check our (hopelessly outdated) website https://courseplay.github.io/courseplay/en/index.html
and look for a yellow Donate button :slight_smile: And while donations are appreciated (but not expected), if you really want to help, please contribute translations,
updating the manual, fixing bugs, implementing new features.

A huge thank you to our community for their support and patience.

Special thanks to our contributors:
@GeorgeEarslight
@Axel32019
@davboecki
... and to all our translators.

The CP Team wishes you all a Merry Christmas and a peaceful Christmas time.

Greetings,
CP Team.

**Comment by panicsheep79** [comment]
Hi...Ich hoffe mal man darf hier schreiben. Frage. Was sind denn die Vorraussetzungen das der Drescher da selbst abtankt? Der Trailer mit Hänger steht auf dem Feld, es ist Platz im Kipper, er läuft im Mode 1..

Aber was muß ich machen das der Drescher dann da hin fährt? Oder wie ist das zu verstehen? Der Drescher ist voll und er tut nichts. Die Option ist in den Settings an. Fährt der also dann von allein zum Trecker + Hänger oder was macht er wo und wie? Wie gesagt... bei mir tut der nix. er steht voll rum und steht und steht und steht und steht...   tbc

**Comment by pvaiko** [comment]
@panicsheep79 neue Issue öffnen mit log (debug channels 7 und 14)
