### ISSUE TITLE
Fertilizer Refill Course Ignored

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#4691]
CP release 347 ignores the fertilizer (solid) empty state and continues driving through the field. 

[log.txt](https://github.com/Courseplay/courseplay/files/3998779/log.txt)

**Comment by pvaiko** [comment]
Can't reproduce this. Need a log with debug channel 14.

**Comment by lcc1211** [comment]
I am heading out in a few minutes. I'll try and get it to you within the next 24.

**Comment by lcc1211** [comment]
My initial report had all the mods removed except for the tools I was using. This one is with all mods in place. With or without I get the same results.
[log.txt](https://github.com/Courseplay/courseplay/files/4000832/log.txt)

**Comment by pvaiko** [comment]
Don't know what vehicle you are using but certainly not vanilla. According to the log this one does not even report the fertilizer level.

**Comment by lcc1211** [comment]
You're right. I am using a mod of a giants spreader.
