### ISSUE TITLE
dataS/scripts/vehicles/specializations/events/SetPipeStateEvent.lua(54) : attempt to index field 'object' (a nil value)

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#4693]
Error: Running LUA method 'packetReceived'.
dataS/scripts/vehicles/specializations/events/SetPipeStateEvent.lua(54) : attempt to index field 'object' (a nil value)

Dieser fehler kommt immer wen der drescher auf dem Dediserver abtanken will.

https://youtu.be/-XECWYUHF2A

MFG Mannie313

**Comment by Tensuko** [comment]
@davboecki

**Comment by davboecki** [comment]
What is the type of that harvester? And I'm going to need a full log to start looking into this.

**Comment by Mannie313** [comment]
ideal9T als mod aber sonst alles aus dem originalspiel.

MFG Mannie313

**Comment by Onkel2000** [comment]
Have exactly same problem. With the Host everything is normal. With my players this problem on also steps with the lime or me to the field syringe, he does not hear on with the fill-up.

**Comment by davboecki** [comment]
@Mannie313 Maybe start out with Debug Channels 5 and 11 activated.

**Comment by Mannie313** [comment]
@davboecki hier die log mit Debug-Kanälen 5 und 11

[log.txt](https://github.com/Courseplay/courseplay/files/4008198/log.txt)

MFG Mannie313

**Comment by Mannie313** [comment]
Dieses Problem besteht immer noch.

MFG Mannie313

**Comment by schwiti6190** [comment]
This issue is the same as #4711 and should be fixed with the latest version.

**Comment by Tensuko** [comment]
Collecting all in #5484

**Comment by andremeyer123** [comment]
Error: Running LUA method 'packetReceived'.
dataS/scripts/vehicles/specializations/events/SetPipeStateEvent.lua(54) : attempt to index field 'object' (a nil value)
der Fehler taucht auf synchronisiere daten mit anderen spieler   auf den server 
@schwiti6190 
[serverlog.txt](https://github.com/Courseplay/courseplay/files/5269624/serverlog.txt)

**Comment by Bandesss** [comment]
Hallo zusammen schön wie Cp sich entwickelt 
Gibt's was neues zu diesem Problem?

**Comment by pvaiko** [comment]
Fixed by 9f247eb7
