### ISSUE TITLE
Tractor Routing with CoursePlay

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#4694]
CP version 347
Map is Lone Oak
Doesn't matter what tractor
When offloading a combine, the tractor often leaves the field after emptying the combine, but before the trailer is full enough to take to the sell point. Could you keep it from leaving the field until it supposed to? Also, in CP for FS17 I could stop the tractor if it starts heading for an object (see video link), but for the last several versions of CP, it won't reset when I start it up again.   https://youtu.be/J8_4wNeKMik

**Comment by Tensuko** [comment]
#331 #4286 
Closed.

**Comment by lcc1211** [comment]
Why have you cited 331 & 4286? Neither of those have anything to do with the issue I reported. You say you want major issues reported, but you close this ticket. How is the primary function of farming - gather crops - not a major issue? You have made dozens of updates for things like Auto Drive and other minor things, but you can't fix the problem of the collisions of tractors and combines on the field? You can't fix the issue of the tractor and trailer wrapping themselves around trees?

**Comment by Tensuko** [comment]
You go do it and help us then :)
If you can do lua and have all the free time of programming such an easy problem :)
And yes, the Issues have to do with your Problem couse it happens in Mode2
