### ISSUE TITLE
Fehler beim Startpunkt beladen

### ISSUE THREAD

**Issue by Blackjack155** [Courseplay/courseplay#4696]
Mal wieder Funktioniert es nicht das es vom Silo Beladen kann warum auch immer.
Im Video sieht man das er Koregt eingrfahren und eingestellt ist

https://drive.google.com/file/d/1w5E9pYLoannw6yBcUw8BNDh5Eo0uMIRL/view?usp=sharing

[log.txt](https://github.com/Courseplay/courseplay/files/4000486/log.txt)

**Comment by Tensuko** [comment]
Nein ist es nicht....
Dein Traktor erreicht den ersten Wegpunkt bevor dein Trailer unter dem Rohrtrigger ist.
Das sieht man sehr deutlich im Video.
Startpunkt weiter hinten dann geht es.

**Comment by Korann1** [comment]
Tensuko hat recht. Es geht. Ich hatte Anfangs auch Probleme damit. Ich habe das Gefühl das da etwas bei den Einstellungen von Courseplay verändert wurde. ( Ist nur ein Gefühl ) :). Nach mehreren Versuchen hat es nun geklappt. Du musst viel weiter vorne beginnen mit dem Aufzeichnung des Kurses dann geht's wieder.

**Comment by Blackjack155** [comment]
Das problem dann ist er im Andren Trigger drin und denkt er kann nur Stroh laden :D

**Comment by Merrlin** [comment]
Das macht überhaupt nichts. CP entscheidet anhand der Einstellung die du getroffen hast was es lädt.

**Comment by Blackjack155** [comment]
Nein eben nicht denn dann kommt an diesen Silo giebt es diese Frucht nicht.

**Comment by Tensuko** [comment]
@Blackjack155 das ist quatsch was du da erzählst.
Der Trigger wird immer zwischen Stop und Start gesucht und wenn der Traktor den Startpunkt erreicht hat muss der Trailer unter dem Trigger stehen.

Ich will jetzt nicht wieder ewig darüber Diskutieren müssen... es ist so!

**Comment by Blackjack155** [comment]
@Tensuko 
`Ich will jetzt nicht wieder ewig darüber Diskutieren müssen... es ist so!`

also wenn dir das zu anstregend ist leuten zu helfen ist du ungeignet für hilfen    es ist sehr anstregend mit dir zu schreiben da du unbeding recht haben musst anstatt auf das problem ein zu gehn und für lösungen zu suchen

**Comment by RalfGorden** [comment]
> 
> 
> Mal wieder Funktioniert es nicht das es vom Silo Beladen kann warum auch immer.
> Im Video sieht man das er Koregt eingrfahren und eingestellt ist
> 
> https://drive.google.com/file/d/1w5E9pYLoannw6yBcUw8BNDh5Eo0uMIRL/view?usp=sharing
> 
> [log.txt](https://github.com/Courseplay/courseplay/files/4000486/log.txt)

dann nimm doch AD geht prima

**Comment by Tensuko** [comment]
> also wenn dir das zu anstregend ist leuten zu helfen ist du ungeignet für hilfen es ist sehr anstregend mit dir zu schreiben da du unbeding recht haben musst anstatt auf das problem ein zu gehn und für lösungen zu suchen

Es reicht jetzt... nicht ohne Grund hast du wieder beim nächsten Forum Urlaub bekommen, bist aus Discord geflogen und aus einem anderen Forum gebannt worden.

Ich helfe ständig und jedem, mache Stundenlang tests und habe dir sogar mal ein Video gedreht, aber wenn man meine Hilfe nicht annehmen will, ist das dein Problem.

Und noch einmal: Dein Video zeigt eindrucksvoll, wie der Kurs NICHT richtig eingefahren ist.
Wenn du das nicht ändern willst, lass es halt.
Versuch gerne dein Glück mit AD, aber wenn du schon so unbelehrbar bei CP bist, wirst du auf das gleichen Problem bei AD stoßen....

Und jetzt ist hier schluß... Die Lösung wurde genannt.
