### ISSUE TITLE
Abtanker wartet an ungünstigen Postitionen

### ISSUE THREAD

**Issue by txmazing** [Courseplay/courseplay#4699]
Jaaaa wie schon oben erwähnt gibt es Probleme mit dem Abtanker von Dreschern. Der Abtanker wartet an einer Position in öfters weit über dem zu bearbeiteten Feld liegt und fährt so auf Felder die gerade anders genutzt und bearbeitet werden. Es kommt öfters zu Kollisionen mit auf diesen Feldern arbeitenden Helfern.

Ich weiß nicht, eventuell gibt es eine Möglichkeit dem Abtanker eine andere Warteposition zu ermöglichen.

**Comment by Tensuko** [comment]
Schau mal da:
#3311 #4286 
Ist leider momentan so.
Closed.
