### ISSUE TITLE
Combine not stopping at end of field while unloading

### ISSUE THREAD

**Issue by Zoochase** [Courseplay/courseplay#4702]
Combine continues driving while unloading, turning into or away from the tractor when it reaches the end of the row.
Prior to FS 19, if the combine was unloading and reached the end of the row, it would stop and continue to unload until empty.  Then the tractor would pull out, make a U-turn and stop behind the combine.  Then the combine would make it's turn and continue.
All combines and all tractors this happens.

**Comment by Tensuko** [comment]
Yea this is something that should be added even when you unload manualy.

**Comment by wakka79** [comment]
Seconded. On the 4x Maps that I play on it is a necessity to babysit all the unloaders. I think that this used to work properly back on Version 328 (ish). Most of the problems I have with the unloaders is on the end of the rows.

**Comment by Tensuko** [comment]
Not sure if this one already works, haveing no time to reproduce this.

**Comment by Tensuko** [comment]
Kinda fixed, not in the best way, but basically it does work.
