### ISSUE TITLE
CP doesn't lower implement

### ISSUE THREAD

**Issue by 820fahrer** [Courseplay/courseplay#4705]
Hey guys,

sadly I have another issue and at the moment I don't know why this occures.

I've generated a course to get my field work done. I've used the 1046 with the Agrisem cultiplow.

At the beginning of the course the tractor doesn't lower the implement. (I've seen the same issue with the Lexion 8900, the combine doesn't lower the cutter)

[Log with debug channels 6, 8, 11](https://pastebin.com/41UvXfJe)

Same problems with seeders and a disc harrow.

It doesn't depend on the field borders. This issue occures with automatic scanned borders and with a selfmade border route.

**Comment by 820fahrer** [comment]
Here's the whole log:
[log.txt](https://github.com/Courseplay/courseplay/files/4002533/log.txt)

**Comment by 820fahrer** [comment]
https://github.com/Courseplay/courseplay/issues/4689
When I've tested the edits in this version, I had no problems with implements.. I will do some more tests now.

**Comment by Tensuko** [comment]
You got a Callstack related to FollowMe Mod.
Take that one out and try again.

**Comment by 820fahrer** [comment]
I just realised that I didn't upload the server log...

No I've tested without FollowMe. Same issue..

But now I've no errors neither in my log nor in the server log.
[clientlog](https://github.com/Courseplay/courseplay/files/4002874/log.txt)
[serverlog](https://github.com/Courseplay/courseplay/files/4002878/log.txt)

**Comment by 820fahrer** [comment]
I've tested another debugging mode (server log, not client log)

https://pastebin.com/R0DG1kzX

The tools (in this case only the Pronto 9) is activated but not lowered. The debugging says it's lowered.

At the moment this problem is equal to all other implements, CP just don't lower the implements. They are all started correctly (combine, seeder, etc. but CP doesn't lower it)

**Comment by Tensuko** [comment]
Oh it is MP related. Sry I didn't notice this.

**Comment by Tensuko** [comment]
@davboecki

**Comment by davboecki** [comment]
@820fahrer Did I understand you correctly, that the cp version I posted in https://github.com/Courseplay/courseplay/pull/4689 does not have this problem? If so then -> https://github.com/Courseplay/courseplay/pull/4707

**Comment by 820fahrer** [comment]
Sorry, I forgot to mention that it's MP related.

> @820fahrer Did I understand you correctly, that the cp version I posted in #4689 does not have this problem? If so then -> #4707

Without your changes I wouldn't be able to test CP in multiplayer. https://github.com/Courseplay/courseplay/pull/4707 that's important for CP to work in multiplayer.

At the moment our main problem is, that the implement lowering doesn't work properly. As you can see in the logfile, there is no error. Based on the debugging, the function which checks the implements are lowered returns true (that's my understanding of how this is implemented).

The tractor/combine activates the implement or the combine itself, but the attached tool won't be lowered.

I know that the issues which I report are not easy to reproduce because of the other mods and multiplayer server.. 

I will create a test savegame later, only with CP and on a server, just to test some cases. But as I said, I don't know how to reproduce this issue.

Sometimes, we can activate the first CP worker without any problems and sometimes also the first worker has this issue. At the moment I don't know if there were more than 1 worker activated at the same time. But I cannot see why they should affect each other.

**Comment by 820fahrer** [comment]
So I made some more tests. Because of my friends we didn't start a test savegame only with courseplay.

But I think I found a issue in a client log that could be part of this problem:
[client log](https://pastebin.com/jKkQFGCk)

So at first: I think I'm able to reproduce that there is a problem with starting CP when there are more than 1 player on the server.

Because of the issue in the above mentioned log, I think that this depends on the CP start_stop function in multiplayer.
I think that there are some things that are not correctly send to the server or something similar.

**Comment by 820fahrer** [comment]
Here's a screenshot where you can see that there is some problem with the start/stop of workers.
As you can see, the tractor in the picture is just standing there, without any worker in it. But on the minimap it's shown with a worker.
Same issue with the other machines on the other farms. There are no workers in the machines but at some point the game says that it is.

![fsScreen_2019_12_27_14_17_21](https://user-images.githubusercontent.com/57295635/71518679-48461c00-28b4-11ea-9b80-01025bc44c72.png)

I think this problem could relate to https://github.com/Courseplay/courseplay/issues/4693

To be honest: At the moment we're using courseplay an at some point, there are more than 3 workers at the same time activated and it doesn't raise any error.
But the only way to get the workers activated correctly, is just spamming the AI start at different point with different options (current waypoint, first waypoint etc.) and sometimes it will begin the work. But i wasn't able to reproduce this specific option yet.

**Comment by Lillemats90** [comment]
also it Lowers the weight & the blade when doing leveling, should only lower the weight.

**Comment by 820fahrer** [comment]
Hi,

as @Lillemats90 wrote, it's no problem when you start the worker with CTRL + Num7
There is another workaround for using the mouse. When you've started the worker by clicking you mustn't move the mouse and lower the implement by yourself with pressing V.
After this or with 'CTRL + NUM7' everything works.

**Comment by Tensuko** [comment]
Collecting all in #5484
