### ISSUE TITLE
Information: Gemeine Rade - Map Issue

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/courseplay#4706]
The LUA Error you are getting on this Map is a Trigger Issue from the Map.
The CP Code in that line is 5 Years old and working on every Map so far, only Gemeinde Rade Map couse that Issue.

Error: Running LUA method 'mouseEvent'.
triggers.lua:648: table index is nil

**Comment by tijmen2** [comment]
I had also a issue on gemeine rade. The driver won't drive the course it sits right on his place. Is that the same issue

**Comment by Tensuko** [comment]
You can check your logfile for the Error that I wrote in the 1st post:
triggers.lua:648 <- just search for that text :)

**Comment by tijmen2** [comment]
Jep same problem😧

**Comment by NSA-Quicki** [comment]
For people who want a fix:
FS19_GemeindeRade/platzierbar/Kuhweide/Kuhweide1.xml
line 40 needs to be:
<config node="0|1|0" exactFillRootNode="0" baleTriggerNode="3" animalPlacesNode="1" acceptedToolTypes="bale">

Credits goes to "Gismuh" in the german forum.
https://forum.giants-software.com/viewtopic.php?f=958&t=156665

**Comment by NSA-Quicki** [comment]
For people who want a fix:
FS19_GemeindeRade/platzierbar/Kuhweide/Kuhweide1.xml
line 40 needs to be:
`"<config node="0|1|0" exactFillRootNode="0" baleTriggerNode="3" animalPlacesNode="1" acceptedToolTypes="bale">"`

Credits goes to "Gismuh" in the german forum.
[](https://forum.giants-software.com/viewtopic.php?f=958&t=156665)

**Comment by Tensuko** [comment]
Thank you for the Information!
Will they Update the map too?

**Comment by NSA-Quicki** [comment]
One of the creators said that they will fix known bugs after christmas. 

For the german speaking people:
[Look here](https://forum.giants-software.com/viewtopic.php?f=958&t=156667)

**Comment by nismof15** [comment]
@NSA-Quicki Thank's for the reply, problem is solved. :) Thank you very much for the answer.

**Comment by NSA-Quicki** [comment]
After further testing there are still some bugs. 
If im using the course generator on some fields another lua error occurs.

2019-12-27 17:42 Error: Running LUA method 'mouseEvent'.
2019-12-27 17:42 C:/Users/Dokumente/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00348/course-generator/center.lua:168: attempt to index local 'b' (a nil value)

The game will go on but i cant generate a course for this certain field.
Happens on following fields:
Field 13
Field 31
Field 48

**Comment by pseikoNL** [comment]
@NSA-Quicki , as it works correctly on all other fields on that map my guess is that it is a fault in the code of the map Gemeinde Rade, I don't play that map so I can't check the code or reproduce it, but may I suggest that you contact the creater of the map Gemeinde Rade to check if there is anything other for these 3 fields you mentioned then the other fields of that map.

Greetz,
PseikO

**Comment by smyers7409** [comment]
I cannot even get the map to load

**Comment by Tensuko** [comment]
Well, sad to hear, but that you got to post where you get support for the Map and also with a logfile, else it is just an information...

**Comment by SteelRodent** [comment]
It seems this map has a lot more issues than just trigger errors. Every now and then the game massively lags just walking around the yard... either way, the map has yet to be updated (on modhub anyway) and CP still does not work on this map as it is now.

**Comment by Tensuko** [comment]
Update is out: https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=149030&title=fs2019

Closing here.
