### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by Lillemats90** [Courseplay/courseplay#4709]
If u are in need of any help, we at [EDGE](https://github.com/edge-gaming) / [FS 19 Mods by EDGE
](https://github.com/FS19-Mods-By-EDGE) would love to be able to contribute. We normally make mods mostly doing 3D design and XML files not so much scripting, meaning we could help a lot with cleaning up XML files, spelling and translations, also some lua coding. we have a modified version of your code on our system atm, and could implement some of the simple changes we have already done to it that we mean makes it even better.

**Comment by Tensuko** [comment]
If you can explain what changes and what they do, we can take a look at it.

**Comment by Lillemats90** [comment]
Well, we are not able to submit em, atm it's mostly minor stuff like translations, and cleanup moddesc, but we where hoping we could be able to contribute to more. But as we are not able to push any of our suggestions we are not able to contribute.

**Comment by Tensuko** [comment]
But you should be able to commit stuff.
You got to understand that we can't allow everyone to push any changes to CP, as we not know what they did.
Why not tell us what you changed....

**Comment by Lillemats90** [comment]
Yes I understand that very well, I think we just have misunderstood each other a little. We'll figure it out and come back to you.

**Comment by pvaiko** [comment]
@Lillemats90 thanks for your offer, we really appreciate contributions. If you have improvements you are more than welcome to open a pull request.

**Comment by Lillemats90** [comment]
yes thats what we wanted to hear, thank you :) we'll be happy to help in what ways we can. have a good day

**Comment by Tensuko** [comment]
Oh yea pull request I mean :)
So @pvaiko can check the changes and implement them if they fit :)
