### ISSUE TITLE
Load at the starting point

### ISSUE THREAD

**Issue by Blackjack155** [Courseplay/courseplay#4710]
It is not possible for me to load crap because the driver continues to drive no matter which vehicle.
Everything is set and the JD drives but the driver does not stop and simply drives on.

![20191227182648_1](https://user-images.githubusercontent.com/26688591/71526386-e2b75700-28d6-11ea-89d6-87148c2795ba.jpg)
![20191227182703_1](https://user-images.githubusercontent.com/26688591/71526387-e34fed80-28d6-11ea-883d-56384ac394c1.jpg)

**Comment by Tensuko** [comment]
Und wieder sehe ich nicht, was du gemacht hast.
Hast du den Fahrer vor dem Startpunkt oder hinter dem Startpunkt eingestellt.
Was passiert, wenn du den Fahrer einfach mal eine Runde fahren lääst ? Bleibt er dann am ersten Wegpunkt stehen ?

**Comment by Blackjack155** [comment]
I let the driver start before the starting point, then load below from 0-32000 and drive to the first point and continue.

The driver continues even if he has driven several laps, he has not even stopped

**Comment by Blackjack155** [comment]
video about it

https://drive.google.com/file/d/1LNm4kORMW3UvwZ3lReudlCubToAKGGDu/view?usp=sharing

**Comment by Tensuko** [comment]
Again Start and Stop to close to each other.
![fsScreen_2019_12_27_19_21_54](https://user-images.githubusercontent.com/27344744/71528282-6ffea980-28df-11ea-9544-80e6944fd12d.png)
![fsScreen_2019_12_27_19_29_57](https://user-images.githubusercontent.com/27344744/71528285-71c86d00-28df-11ea-8dff-2b99293cb79b.png)
When the Trailer is in the Waitpoint for the Unloadpoint of the Frontloader, then start the Courserecord. Stop the Course with a higher Distance. I would always make sure the Trailer fits nicely inbetween stop and start.
Just for demonstration, ofc the course should not be loaded or combined like that:
![fsScreen_2019_12_27_19_32_21](https://user-images.githubusercontent.com/27344744/71528361-bce28000-28df-11ea-9116-8253eb5b3806.png)

**Comment by Blackjack155** [comment]
should i join the courses?

**Comment by Tensuko** [comment]
>
>
> Just for demonstration, ofc the course should not be loaded or combined like that:

**Comment by Blackjack155** [comment]
No, it still doesn't work

**Comment by Blackjack155** [comment]
in the video you can see how i enter the course and that it still doesn't work
Find mistakes

https://drive.google.com/file/d/1Q_5GG57kgoHztioULfhQIAesQ3obUDDc/view?usp=sharing

**Comment by Tensuko** [comment]
Now he found a loading Trigger between stop and start.
You can see that whe he stops before reached the start.
Create your course in a different way...

**Comment by Blackjack155** [comment]
bitte was wie viel versionen soll ich denn noch einfahren?
is ist doch zu sehn das es nicht geht ergo ist es ein bug

ich kann doch nicht 100 kurse fahren ?

der kurs war so aufgebaut wie deiner also mehr kann ich nicht tun

**Comment by Blackjack155** [comment]
scheinbar ist es ein fehler das CP es nicht erkennt ich habe mehrere kurse eingefahren bei keinem Funkzioniert es ergo ein bug

mehr kann ich auch nicht tun vlt doch was umschreiben das er es besser erkennt?

**Comment by Tensuko** [comment]
Nein es funktioniert so wie es soll, warum verstehst du es nicht ?
Stop --- Trigger --- Start = Laden vom Trigger.
Stop --- Nichts --- Start = Laden am Startpunkt.
Hast du bei deinem Kurs zwischen Stop und Start einen Trigger, obwohl er da nichts laden soll, fährst du den Kurs falsch ein. Ergo ist es kein Bug, sondern DU baust den Kurs falsch.

**Comment by Blackjack155** [comment]
man sieht doch ganz genau wie ich denn kurs einfahre mehr mal und das es nicht geht wie soll er dann falsch eingefahren sein? ich habe mehrere kurs gebaut mehrere fahrzeuge verwendet  was soll da denn noch falsch sein????

**Comment by Tensuko** [comment]
Du fährst bei deinem Stall durch einen Ladetrigger, das habe ich dir eben gesagt.
Er bleibt zu früh stehen und sagt wird beladen, daran erkennst du das er einen Trigger gefunden hat.
Sonst würde er am Startpunkt warten.

**Comment by Blackjack155** [comment]
ich habe denn abstand gehalten ich habe denn enladepunkt genau so gehalten alles genau wie bei dir auf denn fotos 

und er hat nur ein trigger auf dem kurs das sieht man auch das is der endlade trigger 

> Du fährst bei deinem Stall durch einen Ladetrigger, das habe ich dir eben gesagt.
Er bleibt zu früh stehen und sagt wird beladen, daran erkennst du das er einen Trigger gefunden hat.
Sonst würde er am Startpunkt warten.

ja beim ersten video beim 2 mache ich aber ein bogen von allem und fahre nur duch denn endlade trigger kein  anderer ist auf denn kurs weiter

**Comment by Blackjack155** [comment]
ich mach dir ein foto das da keine trigger sind....

**Comment by Blackjack155** [comment]
keine trigger der denn kurs behindert
![20191227222729_1](https://user-images.githubusercontent.com/26688591/71533262-1e164d80-28f8-11ea-823f-37aea17c5e52.jpg)
![20191227222726_1](https://user-images.githubusercontent.com/26688591/71533263-1e164d80-28f8-11ea-8133-dd26e62ddaaf.jpg)

**Comment by Blackjack155** [comment]
was soll ich denn deiner meinung noch tun?

**Comment by Tensuko** [comment]
![fsScreen_2019_12_27_22_39_07](https://user-images.githubusercontent.com/27344744/71533634-34250d80-28fa-11ea-8482-7150788d3ce6.png)
Auf jeden Fall ist es kein Bug!
Ich hatte zwar eben eine ähnliche Situation wie du, konnte aber sehen, das ich durch einen Trigger vom Kuhstall oder was da ist gefahren bin, glaub der Gülletrigger war es.
Jedenfals habe ich jetzt 5 Kurse gebaut die alle funktionieren....
Aber offenbar hast du deine Map umgebaut, mit platzierbaren Objekten oder im Giants Editor ?

**Comment by Blackjack155** [comment]
der stall ist von gebeudepack und ein platzierbarer im editor  habe ich nichts gemacht 
wie gesagt ich fahre denn kurs nur durch ein trigger  wie schon genannt

**Comment by pseikoNL** [comment]
@Blackjack155 , I've watched the movie you made and I can tell you that you record the courses wrong.
What you do wrong is that you first record the course for the trailer and after that you record the course for the frontloader, this create a unloading trigger for the frontloader in front of the trailer and not above the trailer.
So record first the course with the frontloader, and after that you create the course for the trailer so that the trailer will stand under the unload trigger of the frontloader.

Greetz,
PseikO

**Comment by Tensuko** [comment]
That sounds interesting @pseikoNL it never happened to me, as I always create the other course 1st.
But it shouldn't make any difference, couse after the 1st unload run, you end up in the same situation, that the Frontloader wants to unload, creates a tip trigger, and the tailer will come back.
But I will try that one out.

**Comment by pseikoNL** [comment]
![issue4710](https://user-images.githubusercontent.com/26251950/71533876-8a468080-28fb-11ea-9428-b8687991cb5f.png)

**Comment by Tensuko** [comment]
Yea thats the Problem of the Unloadpoint to hit the trailer in the right position.
Hmm it could be that the trigger area for the place to unload is in the way, thats true.
But it got not much to do with the order when to record what course...
Also it should work without any Frontloader running.

**Comment by Blackjack155** [comment]
@pseikoNL I'm currently testing it

**Comment by pseikoNL** [comment]
The order of recording courses doesn't matter of course, but when you record the frontloader course first, and the trailer course after that you know where the trigger will be.
Therefore I myself always have the 4 course display options to 'on', so you will see the triggers of other courses.

![issue4710b](https://user-images.githubusercontent.com/26251950/71534074-7fd8b680-28fc-11ea-825c-07d39946cdf8.png)

**Comment by Tensuko** [comment]
Yea ofc it makes it much easier to hit the Unload Trigger of the Frontloader :)
I try to make that wrong on purpose now to see if that causes the Issue.

**Comment by Blackjack155** [comment]
now i have the problem where it should tip over and stop too early

**Comment by Tensuko** [comment]
Well, this is not the case.
As I said, he won't just find the Trailer, but he will definitly drive to the start...

Course to much on the side, so he can't hit the trailer:
![fsScreen_2019_12_27_23_06_54](https://user-images.githubusercontent.com/27344744/71534300-37ba9380-28fe-11ea-90b4-4fbfe651631e.png)

Debugchannel 10 shows the area where he try to find a Trailer to tip into:
![fsScreen_2019_12_27_23_09_54](https://user-images.githubusercontent.com/27344744/71534301-3be6b100-28fe-11ea-90d6-713a8f0097ec.png)

Directly after the screenshot above, started the trailer and voila the Trailer waits at Startpoint.
![fsScreen_2019_12_27_23_10_30](https://user-images.githubusercontent.com/27344744/71534304-3f7a3800-28fe-11ea-89e6-baf36aacad7b.png)


What can happen is, that when you got to many waypoints directly after start, that the he will jump over the Start and drives off, but the Course Blackjack made, doesn't look like that to me, but that he wait just behind the Stop Waypoint is normaly a Problem of a Trigger.
Just when you got any unload Trigger of a Silo in the Path between Stop and Start (just like it is supposed to work)

**Comment by Blackjack155** [comment]
![20191227231755_1](https://user-images.githubusercontent.com/26688591/71534442-2f168d00-28ff-11ea-9ad6-8d8a9505ef9c.jpg)
![20191227231814_1](https://user-images.githubusercontent.com/26688591/71534443-2faf2380-28ff-11ea-9d30-370bc221e82f.jpg)

**Comment by Tensuko** [comment]
So does the Trailer now wait there with CP driver on ?

**Comment by Blackjack155** [comment]
I don't have enough crap to test it properly like you

I would need more runs to test this unless you tell me how I can write more in the editor or xml in the warehouse so that I can unload there with a trailer and test it
do you understand?

**Comment by Tensuko** [comment]
No, couse all you need to test it is a tractor and a trailer and make a circle, else he stop at the start or doesn't....
That got nothing to do with a frontloader.....
But I will talk to Dev about the PPC that skips the 1st Waypoint, that could improove it a bit.

**Comment by Blackjack155** [comment]
kannst du mir mal bitte sagen wo im savegame die lager drin sind dann würde ich das gerne ausgiebig testen und dir gleich bescheid geben ob es richrtig funktioniert?

**Comment by Tensuko** [comment]
Für sowa nutze ich die Mod 'easydevcontrols'

**Comment by Blackjack155** [comment]
oh da mich druch zu arbeiten kann länger dauern

**Comment by Blackjack155** [comment]
mal nebenbei  bei der mistplate habe ich das problem das er zu weit nach vorne fährt obwol P. recht weit hinten ist kann man das noch umstellen oder muss er weiter hinter?

**Comment by Blackjack155** [comment]
bekommst nicht hin er läht nicht wie er soll versteh es nicht das er denn kurs nicht nachfährt und dann so abdrivtet

![20191227234615_1](https://user-images.githubusercontent.com/26688591/71535020-1b6d2580-2903-11ea-9dc1-06136e16ddab.jpg)

**Comment by Blackjack155** [comment]
und nun schmiert CP komplet ab und bekomm ERROR ?? O.o
[game.log.txt](https://github.com/Courseplay/courseplay/files/4006409/game.log.txt)

**Comment by Tensuko** [comment]
Was zum teufel soll das für eine log sein ?
Das nützt garnichts?!

**Comment by Tensuko** [comment]
Und dein Dritter Wartepunkt ist ja auch nicht genau über dem Trailer wie @pseikoNL es dir gezeigt hat.

**Comment by Blackjack155** [comment]
> Und dein Dritter Wartepunkt ist ja auch nicht genau über dem Trailer wie @pseikoNL es dir gezeigt hat.

das schreibt aber CP so?! ich fahre bis ganz heran!

**Comment by Blackjack155** [comment]
![20191227235558_1](https://user-images.githubusercontent.com/26688591/71535192-76534c80-2904-11ea-9eb6-ae05955f01ff.jpg)
 da mehr geht nicht!?

**Comment by Blackjack155** [comment]
das Problem ist das du sehr genau denn lader platzieren must sonst chekt er nicht wo der Trailer ist und fährt endwerder links oder rechts weg 
man müste wie du schon geschrieben hast diesen punkt verbreitern sonst erkennt er ihn nicht

**Comment by Tensuko** [comment]
![fsScreen_2019_12_27_19_32_21](https://user-images.githubusercontent.com/27344744/71535748-8a994880-2908-11ea-943a-5f0c416acba1.png)
Wie wäre es, wenn du den Trailer zur Seite fährst, oder erst den Frontladerkurs machst und danach deinen Trailer ausrichtest ?
Du siehtst das es so geht.

**Comment by Blackjack155** [comment]
ist egal habe ich auch schon so gemacht
resoltet ist das gleiche

**Comment by Tensuko** [comment]
Na dann zeig doch mal, dass der 3te Wartepunkt genau über dem Trailer sitzt, das will ich gerne mal sehen bei dir...

**Comment by Blackjack155** [comment]
habe ich dir schon gezeigt siehe weiter oben

**Comment by Tensuko** [comment]
Sehe ich nicht.

**Comment by Blackjack155** [comment]
habe ehr das problem das er immer gegen die wand fährt bei der mist platte 

teste halt eben noch das CP irgewie im 19 schwieriger zu händeln ist als in denen davor...

**Comment by Tensuko** [comment]
Es ist anders.... Welche Wand ? Seite oder hinten ? Wenn hinten hast nicht genug Mist...

**Comment by Blackjack155** [comment]
ja hinten 
na erkennt er es nicht wenn es leer ist?

**Comment by Tensuko** [comment]
Wenn da nichts mehr liegt sollte er das erkennen.

**Comment by Blackjack155** [comment]
liegt minimal aber knallt halt dann gegen die wand und ich habe ihn schon weit hinten gesetz

**Comment by Tensuko** [comment]
Wenn du den 2ten Wartepunkt weit hinten ansetzt, kann er ja nur gegen die Wand fahren wenn er weit hinten noch was suchen soll.... oder wen hast du weit hinten gesetzt ? Schreibe mal bitte in ganzen Sätzen, was du wohin machst..... Das habe ich dir auch schon einmal gesagt....

**Comment by Blackjack155** [comment]
denn 2 mein ich ehr richtig öffnung nicht richtig wand

**Comment by Blackjack155** [comment]
erklär mir doch erst  mal bitte warum CP ständig mein game crasht  ich kann die kurse kaum testen ohne das es abschmiert

**Comment by Tensuko** [comment]
Wer sagt denn das es CP ist ? Poste erstmal ein anständiges Logfile und nicht diesen krimskrams was du vorhin gepostet hast.

**Comment by Blackjack155** [comment]
das war die richtige log??

**Comment by Tensuko** [comment]
Nein, ist es nicht.

**Comment by Blackjack155** [comment]
kp was du meinst eine andere log giebt es nicht

**Comment by Tensuko** [comment]
Das ist ein logfile
[log.txt](https://github.com/Courseplay/courseplay/files/4006485/log.txt)

**Comment by Blackjack155** [comment]
ja habs gesehn sry

**Comment by Blackjack155** [comment]
der kurs jetz
![20191228010238_1](https://user-images.githubusercontent.com/26688591/71536302-c97dcd00-290d-11ea-840e-e2ab3bb6c619.jpg)
![20191228010224_1](https://user-images.githubusercontent.com/26688591/71536303-c97dcd00-290d-11ea-802c-6943b04c4451.jpg)

**Comment by Tensuko** [comment]
![compare](https://user-images.githubusercontent.com/27344744/71536309-efa36d00-290d-11ea-81f5-ff8857f5dc84.png)
Und du willst mir jetzt sagen, dass das die richtige log ist, wenn ich unsere mal vergleiche ?
Ich weis nicht was du mit deinem PC, deiner LS, deiner Map, deinen Mods usw alles anstellst, dass immer nur du Probleme damit hast.... Ist ja nicht so, dass ich die Geschichten aus den anderen Foren nicht mitkriege....

**Comment by Tensuko** [comment]
Ja so sieht der Frontlader Kurs gut aus.

**Comment by Tensuko** [comment]
Jetzt steigst du in den Traktor mit dem Trailer ein und startest genau dort einen Kurs und bringst du Mist zu deinem Silo, dann fährst du zurück und stopst ich sag mal eine gute Trailer länge vor dem Startpunkt.
Wichtig: Direkt beim Start nicht direkt um die Kurve, da macht unser PPC System nicht mit. Ich würde also etwas gerade aus fahren und dann abbiegen, dann sollte es auch klappen.

**Comment by Blackjack155** [comment]
> Und du willst mir jetzt sagen, dass das die richtige log ist, wenn ich unsere mal vergleiche ?
Ich weis nicht was du mit deinem PC, deiner LS, deiner Map, deinen Mods usw alles anstellst, dass immer nur du Probleme damit hast.... Ist ja nicht so, dass ich die Geschichten aus den anderen Foren nicht mitkriege....

wenn du mir so kommst habe ich keien lust mehr mit dir hir weiter zu schreiben ganz erlich!!! ich versuch alles was du sagt und alles drum herum 
entweder redest du vernüftig oder ich suche mir wo anders hilfe!

**Comment by Blackjack155** [comment]
> Jetzt steigst du in den Traktor mit dem Trailer ein und startest genau dort einen Kurs und bringst den Mist zu deinem Silo/Abladepunkt, dann fährst du zurück und stopst ich sag mal eine gute Trailer länge vor dem Startpunkt.
Wichtig: Direkt beim Start nicht direkt um die Kurve, da macht unser PPC System nicht mit. Ich würde also etwas gerade aus fahren und dann abbiegen, dann sollte es auch klappen.

ja habe es jetzt eingefahren  und teste denn kurs bis jetz läuft es

**Comment by Blackjack155** [comment]
>  Und du willst mir jetzt sagen, dass das die richtige log ist, wenn ich unsere mal vergleiche ?

wenn du gelsen hast habe ich beberkt das es die falsche datei war und sry geschreiben aber das übersieht man mal wieder!!

Mal ganz erlich die LS Community ist die einzige die so krasse Probleme macht mit denn leuten nirgendwo anders hat man das Problem und kommt recht schnell zur lösung nur hier nicht so mehr sag ich nicht dazu

ich teste denn kurs jetz

es wird noch sicher mehr kommen allein denn frühren post denn ich gesehn habe mit dem Drescher habe ich auch das die Ki sich da verhagt konnte aber die lösung dazu nicht lesen da ihr denn zu schnell geschlossen habt

**Comment by Blackjack155** [comment]
> Wichtig: Direkt beim Start nicht direkt um die Kurve, da macht unser PPC System nicht mit. Ich würde also etwas gerade aus fahren und dann abbiegen, dann sollte es auch klappen.

das werde ich bei denn nächsten kursen berüchtigsen  Danke für diesen Hinweis

**Comment by Blackjack155** [comment]
Hier is das was ich meinte das er dann hängen bleibt, ich weis nicht wie ich das noch einfahren soll das er das eben nicht mehr tut. Vieleicht muss die Arbeitsbreite verkleinert werden.

![20191228014800_1](https://user-images.githubusercontent.com/26688591/71536841-2e3c2600-2914-11ea-9a7c-adc43dba2ee8.jpg)

**Comment by Tensuko** [comment]
> 
> wenn du mir so kommst habe ich keien lust mehr mit dir hir weiter zu schreiben ganz erlich!!! ich versuch alles was du sagt und alles drum herum
> entweder redest du vernüftig oder ich suche mir wo anders hilfe!

Ich habe schon lange keine Lust mehr auf dein Art die du hier an den Tag legst.
Und ich möchte nur mal anmerken, dass DU hier ein Problem hast und hilfe suchst, nicht ich! Ich muss mich nicht mit dir und deinem Problem beschäftigen, ich mache das freiwillig nur du machst es mir und anderen mit deiner Art und Weise verdammt schwierig! Such doch wo anders Hilfe! Ich kann dir nur sagen, dass du so auch bei anderen nicht weiter kommst und ich kenne die Leute aus dem Forum und Discord wo du rausgeflogen bist.
So und jetzt ist hier Schluss, das ist schließlich kein Forum sondern eine Entwicklerplattform und das was du da hast ist kein Bug.
Closed.
