### ISSUE TITLE
MP: Combine Pipe Not Opening

### ISSUE THREAD

**Issue by jspring0811** [Courseplay/courseplay#4711]
With combine full and waiting for offload, the pipe is not extended.  When I pull up next to the combine in a cart, the pipe does not extend, however, the grain animation shows emptying of the grain out of the pipe to the rear of the combine and the cart is being filled.
![pipeout](https://user-images.githubusercontent.com/48362683/71529374-614dcd80-28b2-11ea-9f7a-043ac03c00a1.png)

**Comment by Tensuko** [comment]
@davboecki

**Comment by GarfeildThaCat** [comment]
After doing some testing. the pipe as acting like it has opened. reason why it unloads even thou it is not. I think this has to do something about Animations not playing possible. Cause you still get the collision from when its out even thou it shows it not out.

**Comment by Justice-Molton** [comment]
Same here, the pipe stays folded .362 MP Dedicated Server

**Comment by jspring0811** [comment]
Fix works great.  Thank you!
