### ISSUE TITLE
Combine collides with grain cart after pocket unload

### ISSUE THREAD

**Issue by jspring0811** [Courseplay/courseplay#4712]
Every time the combine resumes after unloading from a pocket position it collides with the grain cart.
![pocketcollision](https://user-images.githubusercontent.com/48362683/71529460-d1f4ea00-28b2-11ea-91f4-5e0105fab44c.png)

**Comment by deadgeek** [comment]
I see this behavior as well.

**Comment by Tensuko** [comment]
#3311 #4286 
Closed.
