### ISSUE TITLE
Coursplay will keinen Lohn mehr!

### ISSUE THREAD

**Issue by RobinHooooood** [Courseplay/courseplay#4714]
Hey hab ein Problem und zwar Spiel ich mit der Courseplayversion 6.01 
und seit dem ich gewechselt bin nimmt Coursplay kein Lohn mehr dann erscheint immer +0 Lohnzahlungen und das nervt irgendwie ich würde gern das Courseplay wieder Lohn nimmt und falls jemand fragt ich hab am Anfang des Savegames Courseplay gesagt er kann Geld nehmen. Aber wenn ich jetzt ein neues Savegame mache werd ich nichtmal mehr gefragt ob er Lohn nimmt oder nicht er fragt nur ob er die Felder Scannen soll.

Bitte um Hilfe

**Comment by Blackjack155** [comment]
Dort kannst du es einstellen :)
![20191228101424_1](https://user-images.githubusercontent.com/26688591/71541556-28b5fe80-295b-11ea-8ffa-a9dfa4b37494.jpg)
![20191228101434_1](https://user-images.githubusercontent.com/26688591/71541557-29e72b80-295b-11ea-93f4-992a263b58eb.jpg)

**Comment by Blackjack155** [comment]
> Aber wenn ich jetzt ein neues Savegame mache werd ich nichtmal mehr gefragt ob er Lohn nimmt oder nicht er fragt nur ob er die Felder Scannen soll.


Diesen fehler habe ich auch schin gemeldet wird aber hir nicht ernst genommen. sry ist aber so

**Comment by Tensuko** [comment]
@Blackjack155 
Wenn du hier weiter so einen schwachsinn verbreitest, war es das bald für duch.
Das es keine Abfrage mehr gibt ist beabsichtigt und KEIN Fehler.

@RobinHooooood 
Version 6.01 ist etwas allgemein. 6.01.xxx und xxx = die aktuelle Version.
Melde bitte zurück ob es nun klappt.

**Comment by Blackjack155** [comment]
@Tensuko  meinung haste bekommen.

**Comment by RobinHooooood** [comment]
@Tensuko Ja es funktioniert jetzt aber mal eine andere Frage wird es noch nen Modus alleine fürn Überladewagen geben da meine aktuelle Lösung dafür nicht so toll ist

**Comment by Tensuko** [comment]
An sich hat CP so einen Modus, das ist der Modus3.
Nur funktioniert dieser genau so wie Mode2 (+Wartepunkt zum Abladen) und das unser Mode2 im moment noch nicht fertig ist, ist ja bekannt. Von daher gibt es momentan nur die Möglichkeit, Drescher zum abladen zu schicken (V350+).

**Comment by RobinHooooood** [comment]
@Tensuko Kannst du mir dann sagen warum der Abfahrer immer in den Drescher fährt und nach den abtanken vor dem Drescher parkt

**Comment by Tensuko** [comment]
Genau das ist das Problem bei unserem Mode2.
Der benutzt noch den alten CP Driver und nicht den neuen AiDriver und kann daher nicht mit dem Drescher kommunizieren.
Was ich von anderen weis ist, dass es helfen soll, die Fruchtumfahrung beim Drescher und Abfahrer aus zu schalten und den Start und Endpunkt vom Abfahrer Kurs dort zu haben, wo der Drescher anfängt mit Abdreschen. Ich selber nutze den Mode2 aber ehrlich gesagt im moment nicht.

**Comment by RobinHooooood** [comment]
@Tensuko Hab gerade das ausprobiert mit den Lohn anschalten  leider zieht mir Courseplay die ganze Zeit Geld ab

**Comment by Tensuko** [comment]
Das heist sobald du das einschaltest wird immer Lohn abgezogen, auch wenn kein CP Fahrer fährt ?

**Comment by RobinHooooood** [comment]
@Tensuko Nein sobald ich ein Einstelle zieht er Geld ab aber er soll doch immer jede Stunde abziehen und nicht im Augenblick

**Comment by Tensuko** [comment]
Das ist nicht mehr so, da das alte System nicht mehr funktioniert hat. Es ist nun so wie bei normalen Helfern.

**Comment by Tensuko** [comment]
Sollte soweit klar sein.
Closed.
