### ISSUE TITLE
Failure to harvest

### ISSUE THREAD

**Issue by Blackjack155** [Courseplay/courseplay#4715]
These mistakes are shown to me during the harvest. Is it from the driver or the thresher?
019-12-28 11:00 Error: Running LUA method 'update'.
2019-12-28 11:00 C:/Users/chris/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/mode2.lua:1654: attempt to call method 'onWhichFieldAmI' (a nil value)

[log.txt](https://github.com/Courseplay/courseplay/files/4006933/log.txt)

**Comment by Tensuko** [comment]
#3311 #4286 
Closed. Note for Blackjack: All Mode 2 Issues will get closed due to the reasons discribed in the referenced Issues.
