### ISSUE TITLE
Calulate field size with border

### ISSUE THREAD

**Issue by wwaayynn33** [Courseplay/courseplay#4717]
Hello,

no issue but a suggestion for a feature which could be added to the course generation menu. How about adding the field size in ha depending on the stored field boarders?

I've created a lot of new fields so it would be interesting to know how big the field are now. Of course i can look through the statistics, but most of the time multiple vehicles are running on different fields or i forget to check it. Thanks.

**Comment by Tensuko** [comment]
I think that is Possible.
When you choose the Fieldnumber in Coursegen Menu, that there is an Information about the Field size.

**Comment by wwaayynn33** [comment]
Could you show me a screenshot of this? i have to admit, i still run an older version of CP.

**Comment by Tensuko** [comment]
No this is not implemented. Just an Idea how and where ut maybe could be.

**Comment by essentian** [comment]
This would be extremely useful, along with the functionality from older courseplay releases to calculate fertilizer, seed, herbicide costs based on the size calculated.

**Comment by Ferenzee84** [comment]
I'm definitely interested in this, I really enjoy making custom fields, and I never know how big they are.

**Comment by Tensuko** [comment]
More then what we have with V00026 won't come into CP, this should be what you want, see coursgenerator screen and activate seed calculator.
