### ISSUE TITLE
Create waylines by contur segments

### ISSUE THREAD

**Issue by wwaayynn33** [Courseplay/courseplay#4718]
Hello,

also now issue but maybe a good feature for the course generation in future. This is how its used on real tractors:
https://www.youtube.com/watch?v=9hBTd6AuMSM

Somtimes(if field are curvy/no staight lines at all) it would be quite beneficial if you could choose a segment of the border(segments are created automatically depending on the board or can be created graphically by the user in the menu) which is then copied/shifted to the inner of the field to cover the rest of the area(length of the lines depending on the headland). Automatic selection like in the video is not needed as course play is driving on its own anyway.

For sure this adds complexity for calculating waylines regarding minimal radius etc. but would be a cool feature in the future.

**Comment by Tensuko** [comment]
That looks a bit like pre-turn with the mode 'short edges', if you tried that one.
But yea that Idea is nice too.

**Comment by pvaiko** [comment]
@wwaayynn33 I was thinking of this already, it can get very ugly when those shifted lines reach the opposite end of the field which may have a completely different shape. Can you show an example field and draw what would you like to have generated?

**Comment by wwaayynn33** [comment]
Hello,

here are two examples:
![grafik](https://user-images.githubusercontent.com/47117420/71562593-9c066000-2a82-11ea-97c4-ce0dba7c80c3.png)
![grafik](https://user-images.githubusercontent.com/47117420/71562597-ad4f6c80-2a82-11ea-8551-5dcd0bf645b7.png)

Another shape is this boarder, kind of a round u-shape:
[courseStorage0051.zip](https://github.com/Courseplay/courseplay/files/4008543/courseStorage0051.zip)

Another approach could be to give the user the possibility to divide the field into segments to reduce complexity with in different waylines like here:
https://www.claas-group.com/press-corporate-communications/press-releases/silver-for-6--less-processing-time-in-the-field/657108

**Comment by pvaiko** [comment]
@wwaayynn33 sure, I get it, my question was really about the transition areas (circled in yellow below), what would be the algorithm to exactly find the location of these, this field seems to have 3 segments, each using a different edge as a contour.
![line](https://user-images.githubusercontent.com/2379521/71563465-a1998100-2a55-11ea-9401-3e9c9a853679.png)

**Comment by wwaayynn33** [comment]
Yes thats true, almost impossible as a farmer i would look at the field and do the optimization as i want to do it, same when raking a unknown field. Two round and then you take a look where to start best.

Anyway for that case above it course play would create straight lines(yes?) So it would be a triangle in the bottom left top right corner. What would fulfill already my request if i could choose the right contur as the reference and move the wight wayline across the whole field. Of course the will be also cases where you get triangles, but thats the same in reality.
Therefore my second suggestion would be to split the field into different wayline sections. But if thats really needed, needs to be checked after a feature like the first point is available.

**Comment by pvaiko** [comment]
@wwaayynn33 would you have some example field definition files for me (https://github.com/Courseplay/courseplay/wiki#how-to-post-your-field-definitions) where you'd want to use it?

**Comment by Tensuko** [comment]
Can we get the requested information for this or is there no interest in it anymore ?
