### ISSUE TITLE
MP: Engine / Implement are left running at end of course

### ISSUE THREAD

**Issue by jspring0811** [Courseplay/courseplay#4720]
On dedi server the vehicle and any running implements are left running after end point.  Combine header is also running during on-field stationary unload and at end of course.  Field work implements are left running.  Sprayer, spreader, and seed implements are left running at end of course.
![running](https://user-images.githubusercontent.com/48362683/71549237-17cfb200-2988-11ea-8c11-07753d61c2be.png)

@davboecki
I very much appreciate the ability to help test cp multiplayer...  have been looking forward to this for a long time :)

**Comment by Nickem112** [comment]
there bug cp will not put pip out on the haverster on dedicated server please fix it

**Comment by Tensuko** [comment]
Collecting all in #5484
