### ISSUE TITLE
AIDriver.lua:715: attempt to index field 'course' (a nil value)

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#4724]
Dieser Fehler kommt auf dem Dedi sobald ich nen Abfahrer Beladung am Start einstelle.

[log.txt](https://github.com/Courseplay/courseplay/files/4008177/log.txt)

MFG Mannie313

**Comment by Tensuko** [comment]
Du meinst Mode1 ? Beladen am Startpunkt ?

**Comment by Mannie313** [comment]
Ja genau und dann kommt dieser fehler und das ganze hud vom CP Verschwindet.

MFG Mannie313

**Comment by Tensuko** [comment]
Ok, magst du nochmal ein logfile posten mit debugchannel 14 eingeschaltet und dann dan Fehler reproduzieren und das logfile heir posten.

**Comment by Mannie313** [comment]
Kann ich heute mittag machen soll ich die neueste version vom CP Nehmen.

MFG Mannie313

**Comment by Tensuko** [comment]
Das wäre gut :)

**Comment by Mannie313** [comment]
Hallo @Tensuko hier mal die log: 
[log.txt](https://github.com/Courseplay/courseplay/files/4010519/log.txt)

mir ist noch was aufgefallen. ich hab ja oben mehrere reiter. wen ich den Reiter Abfahrhelfer Steuerung anklicke passiert dieser fehler. bei den anderen reiter nicht. 

Hier mal ein paar bilder:
![fsScreen_2019_12_30_18_40_14](https://user-images.githubusercontent.com/3021040/71593336-e5fb4e80-2b33-11ea-9cee-45b7d55bf836.png)

![fsScreen_2019_12_30_18_40_18](https://user-images.githubusercontent.com/3021040/71593341-ee538980-2b33-11ea-891d-42392d0bfee4.png)

![fsScreen_2019_12_30_18_40_21](https://user-images.githubusercontent.com/3021040/71593348-f3b0d400-2b33-11ea-924d-6db69f0ac230.png)

![fsScreen_2019_12_30_18_40_23](https://user-images.githubusercontent.com/3021040/71593358-f90e1e80-2b33-11ea-92ab-61bf7425590c.png)

![fsScreen_2019_12_30_18_40_25](https://user-images.githubusercontent.com/3021040/71593361-fe6b6900-2b33-11ea-8119-960465fff4ba.png)

![fsScreen_2019_12_30_18_40_28](https://user-images.githubusercontent.com/3021040/71593364-04614a00-2b34-11ea-81d4-4e8ecd08e08c.png)

MFG Mannie313

**Comment by Tensuko** [comment]
@davboecki
