### ISSUE TITLE
Triggers Not Being Recognized

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#4725]
NOTE: As long as 100% of drills, fertilizers, tippers and tractors are all vanilla - no issues. Using any mod CP fails to fill fertilizer, seeds or to dump from the tipper.
Map: Loan Oak
CP Versions: 346-351
Tractor-Giants Claas Ario 660 (and any other tractor I use - to include MODS)
Trailers: Multiple modded.
ALL MODS DOWNLOADED FROM MODHUB WITHIN GAME
Silo: Lizard Large Silo Facility Tractor drives right through without dumping
Silo: Lizard Fertilizer Station - Drives through without filling
Silo: Lizard Seed Station - Drives through without filling
These used to work. I don't know if I have a bad mod or just that CP has stopped recognizing them.
[log.txt](https://github.com/Courseplay/courseplay/files/4008252/log.txt)

I'm able to manually use all silos.

**Comment by Tensuko** [comment]
Only one CP Error and that is Mode2 (not sure if @pvaiko changed something on that one)
2019-12-29 10:53 Error: Running LUA method 'update'.
2019-12-29 10:53 C:/Users/lcc12/OneDrive/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00351/mode2.lua:1654: attempt to call method 'onWhichFieldAmI' (a nil value)

Those are other Errors.

2019-12-29 11:10 Error: Running LUA method 'mouseEvent'.
2019-12-29 11:10 C:/Users/lcc12/OneDrive/Documents/My Games/FarmingSimulator2019/mods/FS19_SiloDisplays/scripts/SiloDisplay.lua:815: attempt to compare nil with number
2019-12-29 11:10 Warning (script): 'getBitVectorMapPoint': Argument 1 has wrong type. Expected: Int. Actual: Nil 
2019-12-29 11:10   ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (882): expectedType == Value::VoidType || expectedType == Value::ClassType
2019-12-29 11:10 LUA call stack:
2019-12-29 11:10   dataS/scripts/utils/FSDensityMapUtil.lua (1614) : getBitVectorMapPoint
2019-12-29 11:10   dataS/scripts/misc/AsyncManager.lua (42) : lambda
2019-12-29 11:10   dataS/scripts/misc/AsyncManager.lua (119) : runLambda
2019-12-29 11:10   dataS/scripts/misc/AsyncManager.lua (139) : runTopTask
2019-12-29 11:10   dataS/scripts/main.lua (1857) : update
2019-12-29 11:10 Warning (script): 'getBitVectorMapPoint': Argument 1 has wrong type. Expected: Int. Actual: Nil 
2019-12-29 11:10   ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (882): expectedType == Value::VoidType || expectedType == Value::ClassType

2019-12-29 11:10 Error: Running LUA method 'update'.
2019-12-29 11:10 dataS/scripts/AchievementManager.lua(257) : attempt to index local 'farm' (a nil value)

Also:
Discribe a bit more on what you did with the Trailers or Drills or whatever...
Refill ? Dumping into Silo ?
A logfile with channel 1 and 2 active for triggers would be also helpful.

About this manually use Silos:
Start a full vanilla game and place the normal GIANTS Silo.
You will notice, you can't dump sugarbeets into it, right ?
Now place a Silo extension, voila, now you can dump them there, BUT:
The Trigger itself, doesn accept them... why is it working anyway ? We don't know and thats a GIANTS Problem.
So only Trigger can tell us, what is accepted by code (that can be found in debug channel 1 and 2 data). So: I'm able to manually use all silos. <- This doesn't mean anything...

Also a smal sidenote... I am not a fan of capital letters...

**Comment by Tensuko** [comment]
Also found this:
Error: Invalid mod name 'FS19_FarmSiloMulti_1.1'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

Also only one Map allowed in mods Folder.

**Comment by lcc1211** [comment]
From the following actions:
Offloading vanilla and mod harvestors (potato and grain). The tractor has drives off to the the Lizard silo, but if the tipper is a mod it just drives on through.

When sowing with a refill course appended & mod sower it leaves the field and drives through without filling from fertilizer silos and skips the seeds as well. These are mod sowers.

When fertilizing with refill course appended & mod fertilizer it leaves the field and drives through 
without filling.

I'm able to manually use all silo means, I can stop the tractor and drive it to the dump point or the refill point and trigger it myself.
[log.txt](https://github.com/Courseplay/courseplay/files/4008294/log.txt)

**Comment by Tensuko** [comment]
Unloading in Mode2 is this:
2019-12-29 11:51 Error: Running LUA method 'update'.
2019-12-29 11:51 C:/Users/lcc12/OneDrive/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00351/mode2.lua:1654: attempt to call method 'onWhichFieldAmI' (a nil value)

About refilling I will try out with Mods...

**Comment by Tensuko** [comment]
Modmap, Modsilo, Modtool... Can you name a specific Tool that doesn't work ?
Except all your Errors in the log, I can't rly explain why it should not work with Mods...
![fsScreen_2019_12_29_18_18_20](https://user-images.githubusercontent.com/27344744/71560249-aa934e00-2a67-11ea-9b0e-20b0f87a3d5b.png)

**Comment by lcc1211** [comment]
Here are the tools I used:
Seed Refill: Giants Claas Arion 960 with Vaderstad Rapid A 600s and Vaderstad Tempo F8 (MOD) & neither refilled from the lizard seed or solid fertilizer silos. The Fertilizer course used the Agromatax Fertimax and the Agro Masz and the ABC Bruns MBA 12000. The offload from combine used the Bailey TB16, TC 21000,  Bijlsma Hercules 1400 and a few others.

The Lone Oak silo will allow me to use the mod tippers, but I can't use the mod silos. The map's lime refill point works with mods as well.

**Comment by Tensuko** [comment]
Just a Question... you know that you got to select what to refill on some tools, right ?
Cosue that one easy refills and my refill course passes also lime and seed and it just works perfectly...
![fsScreen_2019_12_29_18_47_52](https://user-images.githubusercontent.com/27344744/71560552-c1d43a80-2a6b-11ea-8428-a706cd607f64.png)
For Seeders, there is a know bug for the fronttanks ( #4584 )
For Unloading... well... not sure what happened there, but the answer might be the same as always. But it would be strange if that only happens to mod Trailers.

**Comment by lcc1211** [comment]
The only thing I can think of is that your map is different and the refill point you're using isn't the same as mine.

**Comment by Tensuko** [comment]
Well that for sure, but that includes that your Trigger seems faulty :)
As I said, you got some Errors and 2 Maps in your Mods Folder.
So the general refill of CP is working, also with Mod Tools.

And as I showed you the example with GIANTS Issue about Vanilla Silos and Sugarbeets, it can be the trigger, even if you can unload/load there manually...

**Comment by lcc1211** [comment]
Here's what is happening with refill of fertilizer. First with mod and then with Giants.

https://youtu.be/KXWCLsjmTM0

**Comment by Tensuko** [comment]
You didn't set fertilizer to refill....
That Mod you used in Video can load both, lime and fertilizer so you need to choose what to load.
The GIANTS one got only fertilizer....

**Comment by lcc1211** [comment]
I've never set it before with this fertilzer mod. Driving it under a fertilizer only silo has always delivered fertilizer. How far back did this option get added to CP?

**Comment by Tensuko** [comment]
This must be a long time ago since the Sprayer from GIANTS can load both too and that had to be added to the HUD :)
