### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Blackjack155** [Courseplay/courseplay#4729]
@pvaiko 
I just wanted to say thank you the mistakes are now gone

if I also ask that the vehicles do not know where they left off after restarting the game, is that okay?
because e.g. With the loading wagon it is so that I have to constantly bring him to the last point where he left off

**Comment by Blackjack155** [comment]
unfortunately discovered a mistake when he wants to fill up the helper always goes in front because thresher

![20191230022146_1](https://user-images.githubusercontent.com/26688591/71565193-7726e280-2aac-11ea-90bc-94dee5cc8440.jpg)
![20191230022918_1](https://user-images.githubusercontent.com/26688591/71565194-7726e280-2aac-11ea-85a7-d09d8bcda28a.jpg)

**Comment by pvaiko** [comment]
#4286, no old mode 2 bugs will be fixed.
