### ISSUE TITLE
Fold tool at the end of a course

### ISSUE THREAD

**Issue by Zoochase** [Courseplay/courseplay#4730]
Can you add an option or just make it automatic to have the tool fold at the end of the course?
Sometimes when using multiple units, the tool's (seeder, cultivator, etc) will collide at the end.  If the tools folded at the end, this would help prevent that.  Shutting the engine off would be nice too.  Fuel save option does not seem to currently work in this situation.

**Comment by Tensuko** [comment]
So far it only does it when you turn on the 'end at start' option.
About Fuel Save Option I am not sure, I thought it work already but I can be wrong, haven't checked on that one.

**Comment by Justice-Molton** [comment]
It didn't turn of the tool, it just folds it. I tried it with a sprayer an it folds but the sprayer was still spraying

**Comment by pvaiko** [comment]
@Justice-Molton I think that has been reported already, if not open a new issue but make sure you have MP in the title loud and clear.

**Comment by bishop1806** [comment]
Hello All! Best solution will be option, to fold or not at the end of course, in my opinion. For example cutters with own wheels looks terrible, when cutter fold at the end of course.
