### ISSUE TITLE
Error: Running LUA method 'mouseEvent'. - settings.lua:932: attempt to index a nil value

### ISSUE THREAD

**Issue by Blackjack155** [Courseplay/courseplay#4731]
CP crash  in single player
This error came when I created a route for a driver, so a combined course and when I wanted to start it, this happened

2019-12-30 11:48 C:/Users/chris/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/AIDriver.lua:715: attempt to index field 'course' (a nil value)
 
[log.txt](https://github.com/Courseplay/courseplay/files/4009599/log.txt)

**Comment by Tensuko** [comment]
Logfile with debugchannel 14 active.

**Comment by Blackjack155** [comment]
Then it didn't go on because of ERROR

so stopped recording in the log

**Comment by Mannie313** [comment]
@Tensuko ist das nicht das selbe wie der #4724

MFG Mannie313

**Comment by Tensuko** [comment]
@Mannie313 
Hmm im Prinzip ja, wenn das im SP und MP auftritt und auch mit dem gleichen fix gelöst werden kann. Aber im Log steht nun wieder etwas anderes...


In this log got this:
2019-12-30 14:51 Error: Running LUA method 'mouseEvent'.
2019-12-30 14:51 C:/Users/chris/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/settings.lua:932: attempt to index a nil value

But not the other LUA Error discribed in the 1st post.

**Comment by Mannie313** [comment]
Ich hab im Sp keine probleme geht einwandfrei. Was hat der den zu dem zeitpunkt gemacht. das ist jetzt die große frage.

MFG Mannie313

**Comment by Blackjack155** [comment]
dedi und sp sind aber 2 welten

**Comment by Blackjack155** [comment]
`Was hat der den zu dem zeitpunkt gemacht. das ist jetzt die große frage.`

na ich hatte einen kombienerten kurs erstellt und er solte zum nächst gelegenden wegpunkt fahren

**Comment by Mannie313** [comment]
Diese log kommt aus dem sp.

MFG Mannie313

**Comment by Blackjack155** [comment]
welche log?

**Comment by pvaiko** [comment]
Also Leute das hier ist total unübersichtlich weiss kein Mensch was jetzt eigentlich das Problem ist und welche Log gehört zu welchen Fehler. Deshalb mache ich das hier erstmal zu.

**Comment by Blackjack155** [comment]
is das witz wieso wird ständig mein themen geschlossen!?
