### ISSUE TITLE
Drescher Strohablage verbessern, Fahrer auf Feld Stroh ausweichen (siehe letzter Kommentar)

### ISSUE THREAD

**Issue by RK54** [Courseplay/courseplay#4732]
moin,
ich habe ein Problem mit meinen Abfahrern und den abgelgten Schwaden.
Am Ende von einem Kurs auf dem Feld, bleibt der Drescher stehen und entleert das noch vorhandene Stroh, dreht um und fährt wieder los.
Ich würde es schöner finden, wenn der Drescher am Ende 2-3 Meter rückwärts fährt, damit nicht solch ein Strohhaufen entsteht, in dem die Abfahrer stecken bleiben.
Meiner Meinung nach war das schon mal am Anfang der CP Versionen, fand ich klasse.
Gruß RK54
![1](https://user-images.githubusercontent.com/54204656/71583014-e502f680-2b0c-11ea-866b-0d012f158095.jpg)

**Comment by Tensuko** [comment]
Das Problem am Anfang war, wenn man ohne Vorgewende gearbeitet hat, wurde das Stroh wärend des Wenden außerhalb des Feldes verteielt. Jetzt läuft es so wie in FS17. Nur das jetzt noch mehr manöver hinzu gekommen sind, wo er Haufen auf dem Feld hinterlässt.

Während Stroh abladen rückwärts fahren, fügt natürlich wieder Zeit zum bearbeiten hinzu.

**Comment by RK54** [comment]
hier ist die absolute krönung, 
da kann nicht mal ne Kuh drüber springen
![1](https://user-images.githubusercontent.com/54204656/71590587-66688200-2b29-11ea-98f8-c90634b6f1f3.jpg)

**Comment by Tensuko** [comment]
Nimm mal weniger Dünger :D

**Comment by RK54** [comment]
ich hab doch noch nicht mal Mist oder Gülle verwendet

**Comment by Mannie313** [comment]
Aber @Tensuko der originalhelfer fährt ja auch rückwärts bei jeder bahn wo er beendet.

MFG Mannie313

**Comment by Blackjack155** [comment]
@RK54  Liegt auch mit drunter daran das du das flasche Schneidwerk verwendest
nur weil du jedes ankuppeln kannst heißt es nicht das du jedes nehmen soltest ;)

**Comment by RK54** [comment]
@ Blackjack155
kennst du dich aus mit CP?

**Comment by Blackjack155** [comment]
>  kennst du dich aus mit CP?

in wie fern?

**Comment by Tensuko** [comment]
Welches Schneidwerk man an welchen Drescher verwendet ist egal, solange die höhe und die Leistung des Drescher stimmt, geht es.

**Comment by Blackjack155** [comment]
wo is denn mein beitrag schon wieder hin!!!

**Comment by Tensuko** [comment]
Kommt drauf an welchen du meinst.

**Comment by Blackjack155** [comment]
@Tensuko du weist genau welchen du gerade wieder gelöscht hast und ich keine antwort drauf bekomme obwohl cp diesen fehler immer wieder macht

**Comment by Tensuko** [comment]
Erstens: Lese mal was ich dir da drunter geschrieben habe. Lesen und Verstehen!
Zweites hör auf hier dieses Issue mit solch einem Nonsence zuzutexten.
Drittens: Dein Beitrag ist nicht gelöscht, er ist geschlossen, so wie jeder andere auch der sich auf den Mode2 bezieht.

**Comment by Blackjack155** [comment]
aber warum? wenn Mode2 diese fehler hat  warum solte dies denn nicht gefix werden das is was ich nicht verstehe 
ihr wolt doch die fehler meldungen 
und drunter hast du nichts geschriebn sonst hätte ich eine e-mail bekommen 
gneauso wurde mein beitrag geschlossen mit dem ai error weil IHR drunter gespemt habt  ich erwarte eine gewissen anstand zu denn leuten die sich die zweit nehemen und hir die fehler melden mit debug ect.

**Comment by RK54** [comment]
@ Blackjack155 ,
was soll das hier?
ich habe eine Frage gestellt und nach einer Lösung gesucht.
Da gehört dein Blödsinn nicht dazu.
Also halte Dich raus und gebe endlich mal Ruhe.
Dein Glück dass ich hier nicht zu sagen habe

**Comment by Blackjack155** [comment]
@RK54  Kollege überlege mal dein TON! ich habe mein wissen dazu bei getragen was die kombinazion mit dem drescher und dem schneidwer an geht also reis dich mal ein wenig zusammen mit deinem großen Mun!

Weil es nun mal daran liegen kann das dass schneidwerk so viel "stroh" Produziert das deswegen zu viel hinten raus kommt  normal haste das ja an dem New Holand angebaut und es dort eben nicht passiert das so viel endsteht

**Comment by RK54** [comment]
@ Blackjack155 ,
du bist ja einsame Spitze, in 2 Sätzen 10 Fehler, klasse.
Dem Drescher ist es egal was da vorn für ein Schneidwerk dran hängt, 
hat mit dem Strohauswurf nichts zu tun

**Comment by Tensuko** [comment]
> 
> 
> @RK54 Kollege überlege mal dein TON! ich habe mein wissen dazu bei getragen was die kombinazion mit dem drescher und dem schneidwer an geht also reis dich mal ein wenig zusammen mit deinem großen Mun!

Das sagt der richtige... deine PM aus dem LS-Modcompany Forum habe ich noch als Daten vorliegen, wenn dir danach ist. Überlege es dir...

**Comment by Blackjack155** [comment]
@Tensuko das war eigenverschulden also von daher wirf mir nichts vohr ich arbeiten wenigtes daran das fehler gesehn werden aber bitte ich brauch auch keine fehler melden  dann is das euer problem  wie schon mal gesagt ich muss es nicht haben hir tage lang zus sitzen die fehler zu suchen und sie hir melden ich kann auch sagen egal wird gelöscht fertig
und das zeigt auch das du NULL verstanden hast was ich dir da geschrieben habe  aber ich sag jetz nur nich eins  es war das letze mal das ich irgendein fehler melde wenn das hier so weiter geht  ich muss mir das nicht jeden tag an tun denn scheiß cp zu testen euch denn fehler zu melden und dann wird man noch blöd voll gelöffelt  ich zieh jetz hier die grenze kommt noch was an einem angriff bin ich raus und melde ihr kein einzigen fehler mehr

**Comment by Blackjack155** [comment]
`du bist ja einsame Spitze, in 2 Sätzen 10 Fehler, klasse.
Dem Drescher ist es egal was da vorn für ein Schneidwerk dran hängt,
hat mit dem Strohauswurf nichts zu tun`
@RK54 
jetz zu dir nur schlaumeier doch hat es dieses spiel verwendent relativ reale werte was die MASSE an geht bzw das VOLLUMEN  in Real fährt du mit einen Drescher so wie denn auf dem Foto mit dem Schneidwerk max vlt 4-5 Km/H da der Drescher ne rießege menge an Getreide verarbeiten muss so aber im LS ist es so das dass spiel nicht erkennt bzw es denn wert nicht giebt wie Ausgelastet der Drescher ist ergo kannst du mit 10 km/h fahren was dazu führt das du mehr masse druch bringst 
ich bin in der Landwirtschsft daher kenn ich ca die daten.
verstehst du würdest du ein kleineres oder das original nehmen was zum Drescher passt würdest du viel weniger stroh hinten haben
Und normal ist es so das der Drescher gerade aus weiter fährt bis er alles abgelegt hat jedenfalls bei uns ist es so natürlich mit vorgewende 
Hoffe es verständlich erklärt zu haben warum du so ein haufen hinter hast

**Comment by Blackjack155** [comment]
man giebt sich so viel mühe mit dem schreiben und dann wird es hier GELÖSCHT?

damit wars das ich bin raus ich werde dieses Pojekt nicht mehr untersützen und keine fehler mehr melden das is mir zu blöd  wenn ihr kein wolt der die fehler meldet bitte ich bin weg!!

und wie dumm muss man sein denn text auch noch zu löschen wo ich erkläre wie das verhältniss ist :D das war sogar hilfreich  aber mir jetz egal ich bin jetzt hier raus denn stress ist mir LS nicht wert mit solchen oberflächlichen und undfreundlichen menschen  sag nur ciao :D

**Comment by RK54** [comment]
versprich nicht was du nicht halten willst.
Hast du schon so oft gesagt, bist immmer noch da,
alles leere Versprechungen

**Comment by Tensuko** [comment]
Wenn du Sinnvolle Beiträge Leistest, bleiben diese auch bestehen.
Wenn du dich weiter so verhälst, wie in deinen letzten Beiträgen, werde ich auch diese löschen.
Du hast ordentlich eine Frage gestellt in einem Issue, ich habe dir Ordentlich geantwortet und wärenddessen gehst du RK54 an er solle auf seinen Ton achten und den Mund nicht so weit auf machen. Bist du dir eigentlich selber bewusst, was du da schreibst ? Belasse es dabei und verlasse GitHub, wenn du nicht in der Lage bist, vernünftige Beiträge zu leisten.

**Comment by Tensuko** [comment]
- Wenn Rohr außerhalb der Frucht und Drescher voll, sollte dieser erst ein paar Meter zurück fahren um das Stroh besser zu verteilen.

-Fahrten auf dem Feld sollten größere Strohberge umfahren.

**Comment by schwiti6190** [comment]
@Tensuko Wie sieht der status hier von aus mit den stroh änderungen (nur mitte) ?

**Comment by Tensuko** [comment]
Sieht gut aus, warten auf PR merge :)

**Comment by Tensuko** [comment]
Ich mache den hier erst mal zu.
Das mit den Strohbergen ist so eine Sache, es gibt viele Situationen wo, der Drescher rückwärts fahren müsste um solche Berge zu vermeiden...
