### ISSUE TITLE
Abfahrer bei der Rübenernte fährt nicht los

### ISSUE THREAD

**Issue by teneco** [Courseplay/courseplay#4733]
Hallo,

nutze CP 6.01.00353 und den Rübenernter Ropa Tiger 6XL. Der Ernter fhrt einen CP-Kurs mit 4 Vorgewenden. Das Problem: Der LKW-Abfahrer fährt nicht los; es steht immer nur "warte bis Füllstand erreicht ist"
Während der Ernter innerhalb der Vorgewende ist steht sogar ein "Rohr ist in der Frucht" - was aber nicht stimmt.

Stefan

**Comment by Blackjack155** [comment]
habe ich auch beim Drescher, vlt können die jungs das fixen 

Tipp von mir Fruchtumfahrung kurz aus dann fährt er los

**Comment by RalfGorden** [comment]
nimm AD geht super

**Comment by teneco** [comment]
AD?
Jetzt nach dem Neustart des Spiels fährt auch der Abfahrer automatisch los. Kann es an den Vorgewenden liegen?

**Comment by Tensuko** [comment]
Schwer zu sagen, müsstest du mal nen Screenshot schicken und äh ja gute Frage welche debugchannel... 9 12 und 14 gehen fast immer :D 

AD = AutoDrive. In wie weit die ihren Unloader fertig haben weis ich nicht, aber sollte mit CP zusammen funktionieren.

**Comment by Tensuko** [comment]
Da es sich um den alten Mode2 handelt, mache ich hier zu.
#3311 #4286 
Closed.
