### ISSUE TITLE
Eine Frage zu einem error zur version 353

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#4734]
2019-12-30 19:04 Error: Running LUA method 'packetReceived'.
2019-12-30 19:04 C:/Users/Manni/Documents/My Games/FarmingSimulator2019/mods/FS19_courseplay/fruit.lua:60: attempt to index field 'fieldMod' (a nil value)

Was bedeutet dieser fehler. Mein freund und ich hatten felder gekauft und jetzt gehören sie uns nicht mehr und können sie auch nicht mehr kaufen.

[log.txt](https://github.com/Courseplay/courseplay/files/4010595/log.txt)
Zeile 689 + 690 steht dieser fehler drin.

MFG Mannie313

**Comment by Tensuko** [comment]
Also Multiplayer ?

**Comment by Mannie313** [comment]
Ist passiert auf dem Dedi server. Aller felder stehen zwar da zum Kaufen können es aber nicht.

Im Sp oder selbstgehosteten MP hab ich es noch nicht probiert. aber mit der Version 351 geht es normal.

MFG Mannie313

**Comment by Tensuko** [comment]
@davboecki

**Comment by Tensuko** [comment]
Collecting all in #5484
