### ISSUE TITLE
An in-game course editor

### ISSUE THREAD

**Issue by russbeuker** [Courseplay/courseplay#4735]
Hello fellow sim farmers!  I have been enjoying Courseplay, and really appreciate the efforts made by the Courseplay devs and our community to continue to enhance and support this excellent mod.  

I have been developing an in-game course editor that allows you to drag, insert, delete and change the speed and type of course waypoints.  This has proven to be pretty useful to me, so I posted it to my Github page for others to try.  This is a fork of the main distribution .00350dev.  

[Here's Youtube video showing how it works.](https://youtu.be/ZC9jk23XVbM) 

![And here's a screenshot of it in action
](https://user-images.githubusercontent.com/38263621/71595528-e8888480-2af0-11ea-9f83-8fa8af73fa0f.jpg)

Editing a course so a semi can get around this corner
![CourseEditor2](https://user-images.githubusercontent.com/38263621/71610369-1eefef00-2b45-11ea-8947-a00b18a59af4.jpg)

[Here is my forked Courseplay page with the code](https://github.com/russbeuker/courseplay/blob/master/readme.md).   All help, code and notes are in courseeditor.lua)

So I put this out there in the hopes that someone may find it useful as well.  If you have any questions or issues with it, please post these to the Issues forum on my Github page and I'll do my best to respond to your questions or observations.

Cheers!

Russ B

**Comment by Tensuko** [comment]
Wow!
Thats awesome! But you basically have a Copy of CP.
It would be nice if you can work with @pvaiko to merge that into the Original CP Version :)

**Comment by Tensuko** [comment]
I think all you got to do is to make a pull request here :)
That would be one of the best Contributions to CP!
(I always dreamed about that option :D )

**Comment by Tensuko** [comment]
From the 1st Test, there are some Keybindings not working direclty.
The Toggle got to set to a key and other example is increase the speed doesn't react on ctrl+2
When I rebind them by myself to ctrl+1 and +2, they work when control is on the vehicle.
Just F1 Menu displays weird stuff like ctlr+ctlr+1 then, but ofc it is just only one ctrl :)

**Comment by pvaiko** [comment]
@russbeuker awesome. Rebase onto the latest master and open pull request if you feel like you'll be able to support this.

**Comment by russbeuker** [comment]
@pvaiko I was wondering if I should do the pull request from the main branch of my fork, or should there be a separate courseeditor branch here and then I can do a pull request from that.  Any thoughts on how to best proceed?  I can support the editor code, so I am hoping I can find the optimal way to do the pull requests.

**Comment by pvaiko** [comment]
@russbeuker master is fine, no need for new branch.

**Comment by russbeuker** [comment]
@pvaiko sounds good, I'll submit a pull request tonight after I re-fork.  I didn't get it quite set up right the first time.

**Comment by russbeuker** [comment]
@Tensuko I just tested the key bindings and could duplicate what you encountered like 'ctrl+ctrl+1'.  To fix it, bind only the '1' key as the LCTRL key has already been added from the courseplay modifier hotkey.  So, you don't need to bind the modifier to each editor hotkey.

**Comment by Justice-Molton** [comment]
Wow! That’s a Game Changer! this is awesome

**Comment by Tensuko** [comment]
@russbeuker 
I did that too, but it didn't work for me. I also checked for double keybind.
I will try again on a vanilla savegame.
The strange thing is, that it work for speed down but not for speed up.
Did you maybe throw out some other keybind to make it work ? Like normal 1 and 2 for cruise control ?

**Comment by russbeuker** [comment]
@Tensuko Indeed I had removed all keybindings for 1 and 2 before I added these editor keybindings using 1 and 2 for speed control.  In thinking about this some more, I'm not sure what should be the best practice for the default hotkey settings for the editor.  Should they all be unassigned, or maybe just have the editor toggle 'e' defaulted?  We may just need to default them all then mention in the doucmentation/vids that the first thing you should do before using the editor for the first time is to check the bindings.

**Comment by Tensuko** [comment]
Keybindings in FS19 is a general Issue, just like in every FS...
I think to let them remove normal keybinds is not the best Idea but to make real default keybinds with ctrl sounds good.

**Comment by pvaiko** [comment]
This is now included in https://github.com/Courseplay/courseplay/releases/tag/6.01.00355

**Comment by ploughedfieldman123** [comment]
I cant seem to get ctrl+1  or ctrl+2   working plus in the F1 menu some keys are below F1 menu so cant see what they are

**Comment by Tensuko** [comment]
This is some Keybind Issue.
Check where else you got the 1 and 2 in use (mostly Cruise Control) and delete those settings or change the Editor Keys.

**Comment by ploughedfieldman123** [comment]
> This is some Keybind Issue.
> Check where else you got the 1 and 2 in use (mostly Cruise Control) and delete those settings or change the Editor Keys.

ok will check that out thanks
