### ISSUE TITLE
Bale unloading

### ISSUE THREAD

**Issue by ice81rm** [Courseplay/courseplay#4737]
Hi guys, first of all thanks and a huge thank you for all the work you are doing for all of us :)
My problem is this:
When I unload the square bales the first and second unloads it correctly, the third leaves it a little distant

Hi guys, first of all thanks and a huge thank you for all the work you are doing for all of us :)
My problem is this:
When I unload the square bales the first and second unloads it correctly, the third leaves it a little distant
(I attach photos)
and after the fourth discharge .... a lot of mess :)))
![Screenshot (135)](https://user-images.githubusercontent.com/39805100/71601067-27025b80-2b52-11ea-829d-6ddd1eabf456.png) 
![Screenshot (136)](https://user-images.githubusercontent.com/39805100/71601126-67fa7000-2b52-11ea-8539-9742a5cccf9c.png)

**Comment by Tensuko** [comment]
I think you are the 1st one who tried that out :)
Well I know there is some fixed distance in the bale unload.
Not sure if the manual one still exist as a 1st workarround.
Should be on a HUD Page.
@ThomasGaertner created that he knows best what this could be.

**Comment by pvaiko** [comment]
@ice81rm I need a logfile with debug channel 14 for this. Or a savegame just before the third one is being unloaded, with courses.

**Comment by ice81rm** [comment]
Ciao! Il primo log è fino al secondo scarico
[log.txt](https://github.com/Courseplay/courseplay/files/4051661/log.txt)
![fsScreen_2020_01_12_23_24_18](https://user-images.githubusercontent.com/39805100/72226669-01cf0d80-3594-11ea-8a97-3ab5d550c576.png)
![fsScreen_2020_01_12_23_31_28](https://user-images.githubusercontent.com/39805100/72226671-0267a400-3594-11ea-9f55-51831edee1de.png)
![fsScreen_2020_01_12_23_21_05](https://user-images.githubusercontent.com/39805100/72226672-0267a400-3594-11ea-8653-19b281f9e193.png)

-----------------------------------------------------------------------------------------
Al terzo scarico, sembra tutto ok....
![fsScreen_2020_01_12_23_41_07](https://user-images.githubusercontent.com/39805100/72226790-3abbb200-3595-11ea-8ab3-ca3fc5fc406c.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4051695/log.txt)

-------------------------------------------------------------------------------------------
Quarto scarico: si è verificato il piccolo bug :)
![fsScreen_2020_01_12_23_50_25](https://user-images.githubusercontent.com/39805100/72226884-80c54580-3596-11ea-9012-ef5b62f0f5f1.png)
![fsScreen_2020_01_12_23_50_35](https://user-images.githubusercontent.com/39805100/72226885-80c54580-3596-11ea-9b6a-e66305b315fb.png)

[log.txt](https://github.com/Courseplay/courseplay/files/4051719/log.txt)
