### ISSUE TITLE
CP fährt nach Abtanken in denn Drescher

### ISSUE THREAD

**Issue by Blackjack155** [Courseplay/courseplay#4738]
Fehler hate ich schon mal gemeldet aber wurde geschlossen....

![20191230222439_1](https://user-images.githubusercontent.com/26688591/71601331-49e13f80-2b53-11ea-9730-143dc2637f35.jpg)
![20191230222438_1](https://user-images.githubusercontent.com/26688591/71601332-49e13f80-2b53-11ea-82e2-6cb3c1892acb.jpg)

**Comment by Tensuko** [comment]
#3311 #4286 
Immernoch.... Wie schon einmal gesagt.
Closed.

**Comment by Gibbanator** [comment]
Every time.. ;) One day just maybe... one day..
