### ISSUE TITLE
Fragen über Fragen..

### ISSUE THREAD

**Issue by Blackjack155** [Courseplay/courseplay#4739]
Soll ja andere Issues nicht voll spam..

Dann möchte ich gerne das mit denn Mode2 erklärt bekommen
Der alte wird nicht mehr Untersütz das habe ich so weit verstaden heißt also er wurde überarbeitet ist das so richtig?
Wenn das so ist heißt das mit denn neuen Verionen der Neu dabei ist 
Aber dann versteh ich nicht warum dann die Fehlermeldungen Dazu gelöscht werden? denn ich fahre immer mit der Aktuellsten verion von CP. Oder versteh ich die abkützung Flalsch was WIP heißt?

Vlt erstelle ich die meldungen auch falsch dann kann man mir das sagen VERNÜFTIG wie ich diese am besten hier posten sollte dait die Modder damit am besten klar kommnen.
Ich möchte ja auch so wie alle anderen das fehler ausgebssert werden. Aber ich weiß auch nicht alles also würde ich gerne darüber mehr erfahren damit ich mein beitrag dazu Leisten kann CP zu verbessern :)

**Comment by Tensuko** [comment]
Der neue Mode2 ist WIP, das heist Work in Progress und noch nicht release.
Desshalb werden alle Fehler, die sich auf den Mode2, aus dem normalen Release, beziehen mit den Referencen versehen. Auch die Sticky weisen darauf hin (z.B. #4286 ).
Da dort in den Issues alles dazu steht, kommentiere ich das nicht jedesmal aufs neue.
Dafür gibt es das Referenzieren, man muss es halt mal lesen.
Um es nochmal klar zu machen: Mode2 Issues = kein Support, bis wir mit dem neuen fertig sind.
Und dein Issue ist nicht gelöscht, es ist geschlossen.

Wenn du etwas beitragen willst zu CP, dann poste Issues mit einer klaren, verständlichen Überschrift, einer genauen Beschreibung und so, dass man es nachvollziehen kann, was du dort getan hast.
Und wenn dir jemand (egal wer) sagt, du solltest dies oder jenes tun, um etwas festzustellen, reproduzierbar hin zu kriegen, oder deinen Fehler zu beheben, dann mach es auch. Und vorallem, nicht mehrere Probleme in einem Issue mischen, das führt zu garnichts.

**Comment by Blackjack155** [comment]
okay das klärt einiges 
aber mehr als videos und die angeforderten debugs zu aktiveiren geht ja nicht und natürlich zu erklären was wann gerade passiert ist

aber damit weis ich schon mal das ich denn mode 2 bis zum relese nicht melden brauch das wuste ich ja nicht

da es in englisch ist muss ich es ja mir eben übersetzen wo aber nicht alles zu verstehn ist aber im groben habe ich verstanden wasdort besprochen wurde nur das der halt mom nicht supportet wird wuste ich nicht 

dann kann ich damit auch besser arbeiten

trozdem wurde obwohl ich alles befolgt habe mein AI Error geschlossn was unverständlich war da ich ja noch daran sitze denn fehler zu reproduzieren damit ihr wisst was ihn ausgelöst hat aber wenn die thmen jedes mal zu schnell geschlossen werden hab ich auch keine lust diese immer weider neu zu schreiben
