### ISSUE TITLE
MP: Feldarbeit funktioniert nicht - Field work doesn't work

### ISSUE THREAD

**Issue by kurtlohnunternehmen** [Courseplay/courseplay#4740]
Multiplayer: Feldarbeit 
Der Abfahrer macht auf dem Feld nicht seine Arbeit: Er mäht nicht das Gras oder sammelt das Stroh oder Gras nicht auf. Auch die anderen Feldarbeiten laufen nicht.

Muliplayer: Field work
The driver does not do his job in the field: He does not mow the grass or collect the straw or grass.
The other field work is not running either.

**Comment by Tensuko** [comment]
@davboecki

**Comment by Tensuko** [comment]
Maybe a logfile with debugchannel 17, not sure if that will help, but a general logfile (Client and Server) mostly helps :)

**Comment by Tensuko** [comment]
Collecting all in #5484
