### ISSUE TITLE
Error: addRequiredCropType foliage must match the size of the ground terrain detail.

### ISSUE THREAD

**Issue by Ntone107** [Courseplay/courseplay#4754]
I'm working on a map, based on FS19_Blank_Modmap_4x_by_Cazz64.

During testing I noticed lagging/freezing of the map. 
Error in log: Error: addRequiredCropType foliage must match the size of the ground terrain detail.

When I don't activate CP on the map, I don't have the error in my log.

Version of CP: V6.0100355.dev
FS is up to date

**Comment by Tensuko** [comment]
Need a full logfile.

**Comment by Ntone107** [comment]
Tried quickly with another blank map (also 4X), same issue.

**Comment by Ntone107** [comment]
https://pastebin.com/AdpwxkQe

At 17:41, I switched from playing without CP to playing with CP. (Save game, exit game, start game, load mods ....)

**Comment by pvaiko** [comment]
Since this hasn't been reported for any other map we assume that this isn't a Courseplay problem until proved otherwise. 

Also, see https://www.farming-simulator.org/19/terrain-common-errors.php

**Comment by Ntone107** [comment]
> Tried quickly with another blank map (also 4X), same issue.

@pvaiko i have the same problem on another 4x map, without CP no problem, CP activated problem reproduces...

**Comment by pvaiko** [comment]
What exactly is the problem, other than this message?

**Comment by Ntone107** [comment]
Lagging/freezing of the game.

Without CP on those maps, the game doesn't freeze. With CP activated, the game freezes at random moments.

Without CP, there's no error in the logfile, with CP activated, there's the above error.

**Comment by pvaiko** [comment]
Do you think it would help if you at least told us what CP was doing (if anything) when this happens?

**Comment by Ntone107** [comment]
Last time I tested i had 1 tractor-tipper combination running in combi-mode, harvester was running with a helper.

Before I had several in combi-mode and 2 in field-work mode.

**Comment by pseikoNL** [comment]
@Ntone107 , do you have this issue only at the two 4x maps you’ve mentioned above, or have you tried other released 4x maps (example: don diego 4x, Fenton forest 4x)?

Greetz
PseikO

**Comment by Ntone107** [comment]
@pseikoNL going to give Fenton a testrun tonight

**Comment by Ntone107** [comment]
@pseikoNL up until now no issues with Fenton

**Comment by pseikoNL** [comment]
If you’ve tried fenton forest 4x map with courseplay, and don’t encountered any of the earlier problems, then you know that the problem exist in that blank map you are working on and that the problem isn’t courseplay.
Compare your code of that blank map, the foliage layers etc. with that of fenton forest, and if you still encounter problems with your blank map you can ask help at the giants forum.

Greetz
PseikO

**Comment by Ragworm** [comment]
Hi 
i went back to version _6_01_00355. and all is ok so something has changed since then

**Comment by Tensuko** [comment]
way to old, this can be anything from a not appearing mod conflict to some very smal changes.
Won't support any version that is that old.
