### ISSUE TITLE
M2Alpha: Can´t assing Combines manually anymore

### ISSUE THREAD

**Issue by frm274** [Courseplay/courseplay#4756]
Issue #4662 seems to be fixed in the latest version.

But now, i cant assign Combines manually anymore.
Getting following Error when clicking on Combines name:
1 Error: Running LUA method 'mouseEvent'.
2020-01-01 20:41 C:/Users/FD/Documents/My Games/FarmingSimulator2019/mods/ZZ_Courseplay/settings.lua:1833: attempt to perform arithmetic on local 'line' (a nil value)

[log.txt](https://github.com/Courseplay/courseplay/files/4014483/log.txt)

**Comment by Tensuko** [comment]
A bit Patience on this one. @pvaiko worked on updating the Branch to the current Main Release and got to adjust a lot of things. Updates on that one will follow step by step. :)
