### ISSUE TITLE
Problem for collecting chaff with forage harvester and sugar cane

### ISSUE THREAD

**Issue by ontot** [Courseplay/courseplay#4757]
Good evening everyone. I would like to know why the truck turning system was changed when under load with the forage harvesters and sugar cane combines. In practice, before, the trucks always turned on the same side and went backwards, ready to be filled by the threshing machines. Today, however, they make a wrong turn. Furthermore, they no longer follow the threshing from the side already collected, but they walk from the side where there is the crop. Maybe I'm the one making some mistakes. In this case please suggest me the right way.
https://www.youtube.com/watch?v=5CiEb12CO7s

**Comment by Tensuko** [comment]
Hello,
this is an Mode2 Issue.
Check this #3311 and that #4286 for infos.

**Comment by ontot** [comment]
wow... i have see on youtube. it's wonderful.
ok... i will wait it.
thanks for your kind reply.
goos evening.

onofrio



________________________________
Da: Tensuko <notifications@github.com>
Inviato: giovedì 2 gennaio 2020 20:35
A: Courseplay/courseplay <courseplay@noreply.github.com>
Cc: ontot <ontot@hotmail.it>; Author <author@noreply.github.com>
Oggetto: Re: [Courseplay/courseplay] Problem for collecting chaff with forage harvester and sugar cane (#4757)


Hello,
this is an Mode2 Issue.
Check this #3311<https://github.com/Courseplay/courseplay/issues/3311> and that #4286<https://github.com/Courseplay/courseplay/issues/4286> for infos.
