### ISSUE TITLE
Headland "Turn" now at angle missing corner

### ISSUE THREAD

**Issue by jspring0811** [Courseplay/courseplay#4761]
Not sure when this started happening.  The headland turn logic seems to have changed with an odd angle near the end of the maneuver that causes a large swath to me missed as the combine resumes forward.
![headland-turn-issue](https://user-images.githubusercontent.com/48362683/71680592-8631bd00-2d58-11ea-88d6-9313fb693386.png)
![headland-turn-issue2](https://user-images.githubusercontent.com/48362683/71680633-a06b9b00-2d58-11ea-8e6c-4748631b7c97.png)
![headland-turn-issue3](https://user-images.githubusercontent.com/48362683/71680740-e6286380-2d58-11ea-95ec-68746c7ff9cb.png)
![headland-turn-issue4](https://user-images.githubusercontent.com/48362683/71680751-ea548100-2d58-11ea-9e14-273191bb03e0.png)

**Comment by Tensuko** [comment]
1st pic is a different turn then the 3rd and 4th pic.
Logfile with debugchannel 9 12 and 14 would be helpful here.

**Comment by pvaiko** [comment]
Also, you may want to try enabling the AI turns.

**Comment by jspring0811** [comment]
Can you explain the AI turns?   I was not sure if they should be enabled as Normal or if they were to be used as some alternate option.   What would be considered usual/normal mode, and what is the basic difference?   Thanks!

**Comment by pvaiko** [comment]
AI turns work for the normal headland turns (not the ones making a pocket on the outermost headland) and for simple 180 turns. The difference is that they don't use a precalculated path, instead maneuvering the vehicle based on its current position/heading relative to the turn start/end/corner points.

Part of the exercise is to figure out if this is a better way to do turns, it is certainly easier than calculating, we keep experimenting with these and still searching for the holy grail :)

**Comment by jspring0811** [comment]
Simple, AI enabled turn in this case did get the corner.   Here is debug 9,12,14 of both turns.  Non-AI starting at log 2020-01-02 12:23 and AI starting at log 2020-01-02 12:27.   Non-AI currently misses a small section of each turn.  I assume eventually we will want to be using Non-AI turns for the most advanced features.  Thanks,

[log.txt](https://github.com/Courseplay/courseplay/files/4016734/log.txt)

**Comment by jspring0811** [comment]
fyi, I did attach the log above if it is still worth reviewing.

**Comment by pvaiko** [comment]
361 should have fixed this, reopen if not.
