### ISSUE TITLE
Mist streuen im Sp fängt nicht immer am ersten wegpunkt an 

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#4765]
Hallo leute ich weiß nicht was ich noch machen soll. wen ich den Tracktor mit miststreuer zum hof schicke zum nachfüllen fürs nächste feld fängt er nich am ersten wegpunkt am feld an sondern mittendrin.

[log.txt](https://github.com/Courseplay/courseplay/files/4017510/log.txt)

MFG Mannie313

![fsScreen_2020_01_02_23_07_18](https://user-images.githubusercontent.com/3021040/71696252-c6268d80-2db4-11ea-9a28-72eb81edf4c3.png)

**Comment by Tensuko** [comment]
Das heist du hast ihn direkt auf den Nachfüllkurs geschickt ?
Der Endet vor dem ersten Wegpunkt und dann startet er irgendwo auf dem Feld, richtig ?

**Comment by Mannie313** [comment]
Ja genau

**Comment by pvaiko** [comment]
Der Wegpunkt wo der mit der Feldarbeit weitermachen soll ist nur zurückgesetzt wenn du das Mode wechselst. Das ist so damit du den Traktor auf dem Nachfüllkurs anhalten und neu starten kannst. 

Kann natürlich ändern, weiss nicht wie es am besten ist...

**Comment by Mannie313** [comment]
Ich habe immer den gleichen modus drinnen. das problem besteht nur bei mist Gülle und Kalken/Dünger.

Sähen geht wunderbar.

MFG Mannie313

**Comment by pvaiko** [comment]
Ich werde das nicht ändern. Wenn du vor starten kurz ein anderes Mode wählst, wird der auf 1 zurückgesetzt.
