### ISSUE TITLE
Silo Tip Triggers not recognised on sussex farms

### ISSUE THREAD

**Issue by buden3000** [Courseplay/courseplay#4770]
Using combi mode to unload combine and take to main farm silo on sussex farms map. Everything is fine until it reaches where it should detect the trigger and instead just drives straight on over it. using the krampe bandit trailer with a Class 960 tractor (from the DLC) have also tried it with the Case 7210 pulling instead and still no joy.

**Comment by buden3000** [comment]
Forgot to mention i also had the same result at the second storage silo as well

**Comment by Tensuko** [comment]
#3311 #4286 
Old Mode2 is WIP.
Closed.
