### ISSUE TITLE
the problem with the trailed beet harvester..

### ISSUE THREAD

**Issue by kapatyh** [Courseplay/courseplay#4771]

**Comment by kapatyh** [comment]
when working with a trailer harvester for beets , default.... the game hangs on the worker who works in conjunction with this combine.

**Comment by Tensuko** [comment]
I guess you talk about Mode2 (Combi Mode) ?

**Comment by kapatyh** [comment]
> Я думаю, вы говорите о Mode2 (Combi Mode)?

well, how to say....I'm running a trailer harvester for harvesting beets.... which is sewn into the game.... and accordingly, I want to launch a second course on the removal of beets from the combine ....  when the second course determines the harvester, it freezes...

**Comment by Tensuko** [comment]
Yes that sounds like Mode2.
Please take a look at #3311 and #4286 
The old Mode2 is not supported.
