### ISSUE TITLE
Lock bale unloading from Kuhn FBP 3135 after wrapping

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Courseplay/courseplay#4774]
I can make one bale and wrap it with foil. But I can not unload it with the Y key. If I remove the Courseplay from the mods, then it works.

**Comment by Tensuko** [comment]
Full logfile

**Comment by Gonimy-Vetrom** [comment]
Sorry. 
[log.txt](https://github.com/Courseplay/courseplay/files/4022101/log.txt)

**Comment by Gonimy-Vetrom** [comment]
Also, baleGrabberTransport RBM2000 (dlc andersonPack) does not unload the bales by pressing Y.

**Comment by Tensuko** [comment]
What is that ?
Error: Invalid mod name '9999'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

Also somehow for me it is Z and not Y :)
I also reset the keybindings and it is still Z.
Should be Tool function 3.

**Comment by Gonimy-Vetrom** [comment]
For Russian localization with English keyboard, by default there will be a key Y.

![fsScreen_2020_01_04_18_19_17](https://user-images.githubusercontent.com/8200153/71768586-f3dc1580-2f1f-11ea-8c8b-def52b3cfe82.png)
 But according to your example, I reset the keybindings and now works.
