### ISSUE TITLE
MP Worker Issue

### ISSUE THREAD

**Issue by GarfeildThaCat** [Courseplay/courseplay#4776]
When a player starts a worker and the worker finishes. The NPC stays in the vehicle for other players who did not start/setup the course. This results the other players to not be able to use the Vehicle until the either the firing key works or the original Course router comes and starts and stops it.

**Comment by Tensuko** [comment]
I guess a full logfile from Client and Server is needed.

**Comment by Tensuko** [comment]
@davboecki

**Comment by GarfeildThaCat** [comment]
I do love to get you this. I know i need to put it in pastebin for you. But what file are you looking for so i can have my buddy send me the file for the server.

**Comment by GarfeildThaCat** [comment]
Hi, I found it really heard to reproduce. could have been as simple as the server being up to long. So im gonna close this cause i could not reproduce this issue on my own.
