### ISSUE TITLE
Combi Unload causes mouse and keyboard to go unresponsive

### ISSUE THREAD

**Issue by bigdrummer** [Courseplay/courseplay#4777]
When activating Combi Unload, mouse and keyboard controls seize up about 3 seconds after clicking "Drive Now". I have successfully recreated the issue using game provided and mod maps and different combinations of tools, always using a overloader. I have tried with and without mods turned on. It happens with all game provided tools.    

[log.txt](https://github.com/Courseplay/courseplay/files/4022781/log.txt)

**Comment by Merrlin** [comment]
Overloaded is Mode 3 and depends on Mode 2. And Mode2 is #3311

**Comment by Tensuko** [comment]
Also #4286 
Closed.

**Comment by bigdrummer** [comment]
Thank you! Didn't find those master cases when I looked. Looking forward to it working again. I HATE chasing combines all day.
