### ISSUE TITLE
request? Two way courses like AD

### ISSUE THREAD

**Issue by mrPassion78** [Courseplay/courseplay#4780]
I would like to know if it would be possible for CP to have a 2-way route option like AD has, so it could also stop and wait if other traffic is using that bit of road,..
Or...
would it be possible to get CP to USE that 2-way route from AD..

My goal in that is..>>
I have a narrow street, AD course is 2-way (as in picture) with an overtaking bay, so vehicles can wait @ several points on that road, on each other,  to clear a section. 
![fsScreen_2020_01_05_12_43_10](https://user-images.githubusercontent.com/40406761/71779711-fd658c00-2fb8-11ea-8e60-064c35cb8a19.png)

I was wondering of such a thing could be created for CP, because AD does not have the option to FORCE tipping, only at a trigger..( my problem is that i want to unload at a cheap Conveyor-belt and AD does not recognize that, and with CP i could FORCE it to unload)

I tried to use CP just for the unloading part, but i cant get the option for AD to take over after the unloading.

I hope you can understand what i mean here..
Thnx for reading. 

Pascal

**Comment by Tensuko** [comment]
Add to collection: #6270
