### ISSUE TITLE
Mode2Alpha: Test Feedback

### ISSUE THREAD

**Issue by Knowen** [Courseplay/courseplay#4781]
Hello,

I tested a little bit around today and want to leave a feedback and mention a few problems I noticed. I used the Ravenport map for testing.

### Test 1: Chopper with a PickUp to collect grass

On-Field 6 I cut grass and collect that with a chopper and an unloader. The Chopper did his work very well, but the leftOK and rightOK status were always false. There was just a grass swath and left or right was always clear for the unloader. Is this handling intended? If so I can say that it works very good. The unloading process worked pretty well with one unloader. As I insert a second unloader, the two unloaders often collide on a tun manoeuvre. Sadly I forgot to take pictures of this collisions. 

### Test 2: Harvesting wheat with a combine + one unloader

On-Field 12 I start the wheat harvest. The combine does everything as intended. In the settings of the combine, I activated the option to wait while unloading. 
The unloader had just one issue but it appears quite often.

![fsScreen_2020_01_05_13_49_03](https://user-images.githubusercontent.com/47173160/71780731-77e8d880-2fc6-11ea-9886-d8c063935fe6.png)
As seen above the unloader follows the combine. So far so good.

![fsScreen_2020_01_05_13_49_23](https://user-images.githubusercontent.com/47173160/71780734-7c14f600-2fc6-11ea-8453-22e27b26148a.png)
Then he waits until the combine has finished his turn.

![fsScreen_2020_01_05_13_49_45](https://user-images.githubusercontent.com/47173160/71780735-7ddeb980-2fc6-11ea-84c7-9e2510fc206c.png)
After to combine has finished his turn, the tractor drives to the end of the lane and wants to continue following but doesn't make a turn. He just stands there. I stopped the CP unloader, made the turn by myself and started the CP driver again. Then everything(unloading the combine) went as expected until the next turn manoeuvre comes along. 

### Test 3: Chopping maize with 2 unloaders

The chopper had this course, just for you information.
![fsScreen_2020_01_05_14_05_07](https://user-images.githubusercontent.com/47173160/71780774-1412df80-2fc7-11ea-8b51-00857af55271.png)

Everything worked really, really good. Just on the two marked spots on the picture above appears a little problem. The chopper needed to reverse a little bit to continue working. The following unloader changed his status to: `Drive Back from reversing chopper`. But he did not go back far enough so that the chopper crashes into the tractor and couldn't reach his waypoint. With the exception of these two problems, the field was perfectly harvested.

Looks like mode2 is nearly finished (in my eyes).

Here is the log: [log.txt](https://github.com/Courseplay/courseplay/files/4023439/log.txt)

Greetings,
Knowen

.

**Comment by Tensuko** [comment]
Yes I think so too, that there is not much left to do, but if you look closer, there are some situations that needs to be covered.
Thanks a lot for that Testreport!

**Comment by Knowen** [comment]
The most situations where something went wrong are `handling turn manoeuvres` or `drive to combine/tractor`. From what I have seen.
Example for the last point:
A combine/chopper is working and heading east. The unloader comes from east heading west, wants to align to the combine and makes the last turn to avoid the crash too late. So basically a pathfinding problem I guess.

**Comment by gec100** [comment]
is this new MOD2  implemented or not? This forking thing is little bit confusing (or I'm just a little bit thick :) ) 
If not. where can one DL the last version? last I found is 6.01.00353

**Comment by Merrlin** [comment]
No the new Mode2 is still in alpha state. The latest Version can be found under
https://github.com/Courseplay/courseplay/tree/CombineUnloadAIDriver
You have to download and repack it.
But be warned. The Branch is for Testing purposes only.

**Comment by Tensuko** [comment]
#5272
