### ISSUE TITLE
MP: Fiat DT Tractor/Weeder Issues.

### ISSUE THREAD

**Issue by GarfeildThaCat** [Courseplay/courseplay#4782]
We are using a weeder to weed our fields. We of course been using the Fieldwork option to do the job. But after a while it seems the Ai will wonder off if no one is near it. (Sat in the tractor and it did fine) but unsupervised it ends up heading out to no where. Both the tractor we use is Vanilla game content, Tractor being the Fiat DT and using the Pneumaticstar 900. Also notice it doesnt turn on the weed some times its a 50/50 chance it turns on or not. This is on a Dedicated Multiplayer Server.

Just let me know what i need to do and what debug channels you need me to use. Thanks!

**Comment by Tensuko** [comment]
Log with channel 9 12 and 14 will help.
Server log might help as well.

**Comment by GarfeildThaCat** [comment]
First time doing this whole report deal and using the Debugs. Do I need to just set my weeder up again?

**Comment by Tensuko** [comment]
Channels on and let the weeder run the course again in mode6, just the normal way :)

**Comment by GarfeildThaCat** [comment]
Ok i got the same issue with a Fertilizer Spreader which is the k105.[https://pastebin.com/84g0atTm](url)

**Comment by GarfeildThaCat** [comment]
Hi, I'm giving a update. I've noticed this issue with only the Fiat DT. (probably was notice cause i bet barely anyone use it.) But my T6 seems to do the job fine. Just something i noticed.

**Comment by pvaiko** [comment]
@davboecki

**Comment by Tensuko** [comment]
Still no logfile with debuginformations....

**Comment by Tensuko** [comment]
Closed due to inactivity and missing informations.
