### ISSUE TITLE
After detach equipment - PurePursuitController.lua:560: attempt to index field 'course' (a nil value)

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Courseplay/courseplay#4787]
The first part of the course I worked with a loader wagon, and I wanted to complete the second part with the help of a baler. But when changing equipment, I got this error.
Courseplay worked with AutoDrive.
[log.txt](https://github.com/Courseplay/courseplay/files/4025959/log.txt)

**Comment by Tensuko** [comment]
Does this also happen, when you turn off 'use AutoDrive', before detach ?

**Comment by Gonimy-Vetrom** [comment]
At that moment I did not do this. I did not change the settings. I stopped the driver after he completed the course on the field and came to unload at the from AutoDrive.

**Comment by Tensuko** [comment]
So you stopped CP when he used the AD Course ?

**Comment by Gonimy-Vetrom** [comment]
Most likely I stopped the driver when he was following the course AutoDrive. There was no need to stop CoursePlay, because at that moment the tractor controls the AD.

**Comment by Tensuko** [comment]
Yea but might couse the Issue, at least that is what I think happens here.

**Comment by pvaiko** [comment]
> Most likely I stopped the driver when he was following the course AutoDrive

You mean you stopped it in the AutoDriver HUD?

**Comment by Gonimy-Vetrom** [comment]
yes

**Comment by pvaiko** [comment]
Looks like AutoDrive should dismiss (AIDriver:dismiss()) the CP driver when it is stopped while driving for CP. @Stephan-S ?

**Comment by Stephan-S** [comment]
@pvaiko Sure thing.
Currently AD only calls the provided callback function when it stops at it's destination not when stopping with an error or manually. This is to prevent CP from kicking in again and trying to start it's field course at the wrong place.

So what would you like me to call in case of an error?
vehicle.cp:dismiss() or is it vehicle.cp.driver:dismiss() (plus nil checks before that)

**Comment by pvaiko** [comment]
@Stephan-S there's a legacy function to call but I don't really want to deal with that old code. I'll implement an interface function to hide it and let you know.

**Comment by Tensuko** [comment]
Still valid ?
@Axel32019

**Comment by Axel32019** [comment]
@Tensuko I would say this is no longer valid. The cooperation between AD and CP was changed in several use cases - suggest to close this.

**Comment by Tensuko** [comment]
Alright, thank you.
