### ISSUE TITLE
Combi Unload collisions and unload fails

### ISSUE THREAD

**Issue by deadgeek** [Courseplay/courseplay#4791]
Can you all educate me please? Maybe I'm just stupid, but I'm having serious issues with combi unload. Sell points aren't triggering unloads at all, and trucks and combines are constantly colliding. Additionally, once full, the truck won't go anywhere, and I have to remove and re-add the combine assignment.

**Comment by Tensuko** [comment]
Check #3311 and #4286 
Closed.
