### ISSUE TITLE
Farmsilo hat den ausgewählten Fülltyp nicht

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#4792]
Der abfahrer im mode1 findet Getreideabfall nicht obwohl alles eingetragen und richtig geschrieben worden ist. Es handelt sich hierbei um eine Raffinerie.
Ist im SP MP und auf dem Dedi so.

![fsScreen_2020_01_07_07_06_18](https://user-images.githubusercontent.com/3021040/71872344-6fa2b180-311c-11ea-9d98-abbed8049303.png)

MFG Mannie313

**Comment by Tensuko** [comment]
Welche Map ist das und ist das zufällig eine GlobalCompany Produktion ?

**Comment by psoppa** [comment]
Moin Tensuko
Gestern noch drüber geredet jetzt doch die erste Frage dazu. 
Wenn's mit GC ist wird er bei einer Raffinerie Probleme bekommen da die erste Linie bestimmt Diesel sein wird und man kann in dem Hänger kein Diesel einstellen. Er braucht auf jeden Fall einen der Bulk Liquid usw also alles Laden kann. Hatte auch erst einen Trailer ändern müssen damit das geladen werden konnte

**Comment by Tensuko** [comment]
Moin, ja ich bin dran, aber dauert halt etwas :)

**Comment by Mannie313** [comment]
Es ist die Umgebaute Dondiego map von mir und ja die Raffinerie ist eine Produktion über GC alles Plazierbar.

MFG Mannie313

**Comment by Mannie313** [comment]
@psoppa ich kann meinen diesel aus der Raffinerie mit einem Tanktrailer laden und ins lager bringen mit CP.

MFG Mannie313

**Comment by psoppa** [comment]
@Mannie313 
Das glaub ich dass das geht. Da Diesel die erste Produktionslinie sein wird. Lass dir das von Tensuko erklären. Mag da nicht auch noch drin "Rum Pfuschen" (scherz) sonst wird es zu unübersichtlich. Das ich mich überhaupt dazu gemeldet habe war nur ein Hinweis für Tensuko.

**Comment by Tensuko** [comment]
Kurz und Knapp: Aktuell brauchst du einen Trailer der Diesel und Gezreideabfall laden kann :) Dann auf Diesel stellen und Getreideabfall wird geladen.

@psoppa 
Was mir noch eingefallen ist... Wie würde das laufen, wenn die Ausgabe aller Produkte über einen Trigger läuft ? Geht das überhaupt ?

**Comment by psoppa** [comment]
@Tensuko 
Ich bespreche das nachher mal mit Falk das er mal eine xml dahingehend ändert werde es dann testen und dir berichten.

**Comment by Mannie313** [comment]
Laut Bild ist Getreideabfall als ladegut gewählt. Fur Diesel hab ich Tankanhänger und die laufen über Liquid. Getreideabfall über Bulk.

MFG Mannie313

**Comment by Mannie313** [comment]
Weil mir ist aufgefallen AD Lädt ja getreideabfall nur CP nicht.

MFG Mannie313

**Comment by psoppa** [comment]
Dann trag mal entweder bei dem Trailer oder bei dem tank Anhänger die jeweils andere fillTypeCategory ein. Fahr drunter und stell auf Diesel

**Comment by Mannie313** [comment]
Geht ja bei mir nicht. Hab ich auch schon probiert. Ich kann in keinem einzigen Bulk anhänger Diesel laden.

**Comment by psoppa** [comment]
Du musst in der xml des Hängers unter fillUnit einfach noch Liquid hinzufügen. Neu packen und nochmal testen

**Comment by Mannie313** [comment]
<fillUnit>
		<fillUnitConfigurations>
			<fillUnitConfiguration name="$l10n_fillUnitConfiguration_waterTrailer5" price="0">
                <fillUnits>
                    <fillUnit unit="$l10n_unit_literShort" fillTypeCategories="LIQUID" capacity="32000">
						<exactFillRootNode node="exactFillRootNode" />
                    </fillUnit>
                </fillUnits>
            </fillUnitConfiguration>
			<fillUnitConfiguration name="$l10n_fillUnitConfiguration_waterTrailer6" price="1500">
                <fillUnits>
                    <fillUnit unit="$l10n_unit_literShort" fillTypeCategories="LIQUID" capacity="48000">
						<exactFillRootNode node="exactFillRootNode" />
                    </fillUnit>
                </fillUnits>
            </fillUnitConfiguration>
        </fillUnitConfigurations>
    </fillUnit>

**Comment by Mannie313** [comment]
Und ein auszug von dem Trailer auf dem Bild

<fillUnitConfiguration name="$l10n_configuration_capacityX" price="0" params="21000" >
                <fillUnits>
                    <fillUnit unit="$l10n_unit_literShort" fillTypeCategories="bulk" capacity="21000" >
                        <exactFillRootNode node="0>4|7|0" />
                        <autoAimTargetNode node="0>4|7|1" startZ="1.9" endZ="2.4" invert="false" fillUnitIndex="1" startPercentage="25"/>
                    </fillUnit>
                </fillUnits>
				<objectChange node="0>4|4" visibilityActive="false" />
                <objectChange node="0>4|3|2" visibilityActive="false" />
                <objectChange node="0>4|4|0" compoundChildActive="false" />
                <objectChange node="0>4|4|1" compoundChildActive="false" />
                <objectChange node="0>4|4|2" compoundChildActive="false" />
                <objectChange node="0>4|3|2|0" compoundChildActive="false" />
                <objectChange node="0>4|3|2|1" compoundChildActive="false" />
                <objectChange node="0>4|3|2|2" compoundChildActive="false" />                
	        </fillUnitConfiguration>
			
	        <fillUnitConfiguration name="$l10n_configuration_capacityX" price="3000" params="29000" >
                <fillUnits>
                    <fillUnit unit="$l10n_unit_literShort" fillTypeCategories="bulk" capacity="29000" >
                        <exactFillRootNode node="0>4|7|2" />
                        <autoAimTargetNode node="0>4|7|1" startZ="1.9" endZ="2.4" invert="false" fillUnitIndex="1" startPercentage="25"/>
                    </fillUnit>
                </fillUnits>
            </fillUnitConfiguration>

**Comment by psoppa** [comment]
<fillUnit unit="$l10n_unit_literShort" fillTypeCategories="LIQUID BULK" capacity="32000">

Änder das mal so

**Comment by Mannie313** [comment]
wie ändern ich sehe nix

**Comment by Mannie313** [comment]
meinst du bei allen oder nur dem Tanktrailer

**Comment by psoppa** [comment]
Schau nochmal

**Comment by Mannie313** [comment]
@psoppa Wo soll ich es überall eintragen?

**Comment by psoppa** [comment]
Mach erstmal nur in den tanktrailer ist ja nur zum testen

**Comment by Mannie313** [comment]
[Refinery_with_Lubricantfactory.zip](https://github.com/Courseplay/courseplay/files/4030990/Refinery_with_Lubricantfactory.zip)

Hallo @Tensuko hier hab ich dir mal die XML von meiner Raffinerie. Vielleicht könnt ihr damit was anfangen.

MFG Mannie313

**Comment by Mannie313** [comment]
@Tensuko hilft es dir weiter das ich ca über 100 Filltypes mit der map und den Plazierbaren mods ingesamt habe.

MFG Mannie313

**Comment by Tensuko** [comment]
Ich warte an sich nur auf einen Test von @psoppa und muss noch etwas abklären mit @ThomasGaertner  ob es eine Anpassung an CP oder GC geben muss für dieses Problem.
Vorher muss ich nur wissen, wie CP in dem Fall arbeitet, erst dann kann ich das entsprechend weiter geben und nach einer Lösung suchen...

Aber danke dir für das Angebot.

**Comment by Mannie313** [comment]
@Tensuko mit dem Tanktrailer LIQUID BULK kann ich mit der einstellung das er dort Diesel laden soll Getreideabfall laden. Das gleiche Problem wie bei modcompany.

MFG Mannie313

**Comment by psoppa** [comment]
@Tensuko 
Moin, da gibts wohl irgendwelche Probleme bzw es funktioniert nicht so wie es soll. Also wäre mein Vorschlag den Test bleiben zu lassen. 
@Mannie313 deswegen hatte ich dir das ja geschrieben. Bei der Modcompany sind Tensuko und ich ja auch schon dran.

**Comment by Mannie313** [comment]
Ich habe es ja gelesen was da abgeht. Liegt es dann an GC???

**Comment by psoppa** [comment]
An was oder wen es liegt ist halt nicht klar. Aber letztendlich muss nur was angepasst werden. Aber wer was anpasst und wie genau muss man sehen.

**Comment by Mannie313** [comment]
Mit AD kann ich ja Getreideabfall im kippen laden dort. Nur mit CP nicht.

**Comment by Tensuko** [comment]
Desshalb will ich das ja abklären, wie CP Arbeitet in dem Fall.
Eventuell wird auch gesagt, achso ja das ok kein Problem...

Aber eine Idee die ich hatte habe ich schon aus bestimmten Gründen verworfen, von daher, bitte noch etwas Geduld.

**Comment by Mannie313** [comment]
Ok kein problem.

**Comment by Tensuko** [comment]
Kannst du das noch mal mit der Original Fabrik mit der neuesten CP Version probieren ?

**Comment by Mannie313** [comment]
ja kann ich mal machen

MFG Mannie313

**Comment by Tensuko** [comment]
Funktioniert nun.
