### ISSUE TITLE
Tractor unload after harvester pickup

### ISSUE THREAD

**Issue by Beebtrek** [Courseplay/courseplay#4795]
Hi Guys. Load a collect course for the tractor . That is a harvester normal Empty job.
When the Tractor goes to the drop off point it just drives over the unload point without unloading Cargo. This happens with Wheat (the only one i tried) with the main farm Silo. On two different maps. Also with different trailers and tractors. Version

Courseplay_6_01_00326 OK

Courseplay_6_01_00358 and Courseplay_6_01_00359  Not ok.

Love the Click to switch Tractor good idea.

**Comment by Tensuko** [comment]
Logfile with debugchannel 1 and 2 active then let CP run the course.
I would also like to see a screenshot of the course and if it is a GC Silo or what exactly it is.

**Comment by Tensuko** [comment]
But actually, this sounds like the old Mode2 (see #3311 and #4286 )
but ofc curious why can't unload in normal silos anymore...

**Comment by Beebtrek** [comment]
Log file here together with Video that shows it perfectly. I have gone back to version 326....
[log.txt](https://github.com/Courseplay/courseplay/files/4035593/log.txt)

Link to Video 👍 
http://www.mediafire.com/file/8x5gw1ec49wsfkr/Farming_Simulator_19_2020-01-08_13-48-18.mp4/file

Screen grabs do not do it for me.

**Comment by Beebtrek** [comment]
Ok I give up. version 326 does exactly the same thing. Ok maybe the Map. It is westbridge hills . Still will try with the default map GERMAN. see if it fails. Something has changed but maybe it is here I do not no. Have not done anything other than add the new tractor DLC. OH HELL is the fact I am using one of those new DLC tractor. Will test and let you know.

**Comment by Beebtrek** [comment]
WHO IS A CLASS A PLONKER ME.
It is the new Platinum Expansion
OVERVIEW:
Contains over 35 vehicles and equipment from CLAAS. Including the following: ARION 660, AXION 870, AXION 960,

So guys a bit of a MAJOR red herring. So this DLC is not fully compatible yet.  So at least we have nailed it down.

**Comment by Tensuko** [comment]
Well.... it is something with our old Mode2...
We hope to manage to get the new Mode2 ready for the Mainrelease in the near future, but for now all  I can tell you is to have more patience.
See #3311 and #4286 for a Preview.

Closed.

**Comment by Beebtrek** [comment]
I have plenty of that more patience. that is. do not worry this Courseplay Mod is a Constant changing Animal and we all understand that new content takes time to implement. But at least you guys know where to look. I still Maintain this is the BEST MOD of Farming Simulator 2019.
