### ISSUE TITLE
Courseplay: aiTrafficCollisionTrigger

### ISSUE THREAD

**Issue by Gecko774** [Courseplay/courseplay#4796]
Hallo zusammen,

Courseplay gibt leider bei vielen Fahrzeugen auch aus dem Modhub die folgende Fehlermeldung in der LOG bzw KONSOLE:

"## Courseplay: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work! vehicle Standard"

Das vehicle Standard ist in dem Fall der John Deere W330 aus dem Modhub.

Durch die Fehlermeldung lässt sich der Drescher zb. beim Abtanken während des dreschens nicht mehr anhalten und fährt weiter obwohl "halten bzw warten" eingestellt ist, auch interessieren ihn dadurch keine Hindernisse mehr.

Die Fehlermeldung kommt bei recht vielen Fahrzeugen vor (zb. der alte MB Track 65/70)

Courseplay greift ihn den XML-Dateien der Fahrzeuge nur auf den  Code zurück:

` <ai>
< aiTrafficCollisionTrigger node="aiTrafficCollisionTrigger" />
<ai>`

Jedoch haben viele Fahrzeuge da andere Bezeichnungen bzw Werte stehen.
Bei den MB Trac 65/70 kann dies noch leicht angepasst werden in der XML durch verändern der Bezeichnung und hinzufügen der Werte bei i3dmapping und zusätzlich der Anpassung der i3d File.

Ist es möglich Courseplay dahingehend zu verändern, dass auch andere Bezeichnungen für den Collision Trigger zulässig sind?

MfG

Courseplay Version ist die aktuellste und der Fehler kommt auf allen Maps vor

**Comment by Tensuko** [comment]
Ich meine das ist nur noch im alten Mode2 der Fall.
@pvaiko weis da bestimmt mehr...

**Comment by pvaiko** [comment]
@Axel32019 vielleicht?

**Comment by Gecko774** [comment]
Die Meldung kommt auch direkt sobald man die gewissen Fahrzeuge im Shop anschaut, noch schnell bei zwei weiteren Fahrzeugen einem anderem MB Trac und das Auto:

![fsScreen_2020_01_08_16_47_01](https://user-images.githubusercontent.com/59656463/71993234-0c597200-3237-11ea-8483-bcd5aea42f61.png)
![fsScreen_2020_01_08_16_48_03](https://user-images.githubusercontent.com/59656463/71993235-0c597200-3237-11ea-93c9-e1d99e6f54b7.png)
![fsScreen_2020_01_08_16_49_05](https://user-images.githubusercontent.com/59656463/71993236-0cf20880-3237-11ea-90b8-a1d1db24fa69.png)

**Comment by Axel32019** [comment]
@Gecko774 
Es wird primär auf den von Dir aufgeführten XML Eintrag zurückgegriffen, jedoch hatte ich schnell festgestellt das sich sogar original Giants-Fahrzeuge nicht an deren eigenen Standart halten: #3916 
Daher hatte ich einige weitere Einträge in vehicles.lua courseplay:findAiCollisionTrigger(vehicle) eingefügt um das noch abzufangen, soweit ich sie gefunden habe. Alles kann man aber nicht abfangen was sich in Zukunft ändert und sich nicht an die Standart-Definition hält - Sorry.
Vielleicht hilft ja etsprechendes Feedback an den/die jeweiligen Modder (incl. Giants)
Alternativ können natürlich die Einträge aus den Mod-XML in vehicles.lua courseplay:findAiCollisionTrigger(vehicle) ergänzt werden.

**Comment by Tensuko** [comment]
Das sich nicht an Standart gehalten wird, wird von LS Version zu LS Version schlimmer, wenn sogar GIANTS es nicht mal schafft...

Danke dir @Axel32019 für die Info!

**Comment by Gecko774** [comment]
Vielen Dank für die schnelle Reaktion und die Antworten.

Die Einträge aus den Mod-XML in der der vehicle.lua eintragen find ich leider etwas schwieriger aufgrund von mangelnder .lua Erfahrung. ;-)

Bei den meisten Fahrzeugen die das Problem hatten bin ich wie auf dem Bild vorgegangen mit den MB Trac und es hat funktioniert.

> ![MB Trac](https://user-images.githubusercontent.com/59656463/72004217-3ae14800-324b-11ea-86a7-d1f83c4f87dd.jpg)

Beim Drescher aber leider habe ich das Problem das dieser mehrere Werte bei <AI> besitzt.

Gibt es evtl. dazu auch ein Lösungsvorschlag?

> ![330W](https://user-images.githubusercontent.com/59656463/72004234-45034680-324b-11ea-9bd6-31d5733d42a0.jpg)

**Comment by Axel32019** [comment]
Entscheidend ist der CollisionTrigger. Diesen Eintrage wie schon beim MB Trac ändern, dann sollte das auch funktionieren. Und willkommen im Club der LUA-Lernenden!

**Comment by Gecko774** [comment]
Dankeschön, die XML´s sind halt leichter :-)

Noch kurz vorhin getestet, sobald ich die XML wie beim MB Trac umschreibe und ergänze und natürlich noch in der i3d vom Drescher den aicollisiontrigger passend umbenne ist die Fehlermeldung im Spiel die durch Courseplay mit dem Trigger kam verschwunden.

Aber leider hält der Drescher trotzdem nicht an beim Abtanken obwohl es in den Einstellungen von Courseplay aktiviert ist.

Die LOG ist sauber und zeigt keine Errors/Warnings etc., getestet auf der Felsbrunn.

Ich vermute, dass es am JohnDeere liegt und irgendetwas in der XML fehlt das er nicht anhält.
Weis aber leider nicht was oder was etwas ergänzt werden muss um ihn zum anhalten zu bringen.
Die anderen Drescher (Claas / NewHolland) bleiben beim abtanken stehen nachdem dies eingestellt ist.

**Comment by Tensuko** [comment]
Das Collithema beschäftigt uns immer mal wieder und da sies kein Fehler sondern eher eine Meldung ist, mache ich hier erstmal zu.
