### ISSUE TITLE
'worldToLocal' has an error and then things fall apart.

### ISSUE THREAD

**Issue by Wynin** [Courseplay/courseplay#4798]
Courseplay version 6_01_00358
In my incompetent eyes it looks like the issue starts with this -
Warning (script): 'worldToLocal': Argument 1 has wrong type. Expected: Int. Actual: Nil

Which then escalates into multiple things failing, which eventually messes up the FS19s UI, controls misbehave, combines stop working and eventually locks up the game. 
Playing on Eiersholt (4x map) singleplayer at the time I believe I had the following going via Courseplay - 1 combine harvesting, 1 tractor with a forage wagon on a grass field combined with a unload course and finally manually driving a combine on a seperate field with a tractor on unload course.
I'm kinda hoping that I'm the issue somehow, since I simply cant do without Courseplay anymore. :)
[log.txt](https://github.com/Courseplay/courseplay/files/4040839/log.txt)

**Comment by Tensuko** [comment]
Only one Map allowed inside the Mods Folder, specialy with Scripts!
Old GC Version, wich doesn't support CP in case you want to use CP with the GC Trigger.
Also see this: #3311 #4286 
Closed.

**Comment by Wynin** [comment]
@Tensuko 
I've removed all other maps, updated GC from their github and used the alpha branch you guys have for mode2.
Granted the combine had its track loaded still but it wasnt running at the moment so shouldnt be relevant, so I decided to test my course which collects grass with the forager wagon and runs it to a grass dryer and I get the same error.  Driving the course manually and unloading it myself results in a different error extremely shortly after I've hit 'E' to unload ( CombineUnloadAIDriver.lua:1277: attempt to call method 'isAutoAimNodeFixed' (a nil value) ).

So I decided to just try and manually run one of the combines with a tractor on an unload course now that I was using the new mode2, that quickly resulted in an 'combines.lua:6: bad argument #1 to 'pairs' (table expected, got nil)' error spam, so I'm a bit at a loss as to what could be the issue now?

**Comment by Tensuko** [comment]
Use our normal Release Version for normal play and don't use Mode2 for now if you faceing issues with it. We are working on Mode2, but it takes time. Then when this one is out, any new Issues will then be looked at and try to solve :) Sry but there is no solution for this now.
If you have Issues with other modes, like collecting grass, pls make a new Issue about this.
