### ISSUE TITLE
Grimme SE 260 unload problem

### ISSUE THREAD

**Issue by gentfarmer** [Courseplay/courseplay#4799]
CP v6.01.00369
VEHICLES
Valtra N134
Grimme SE 260

MAP
mercury Farms

LOG FILE
<script src="https://gist.github.com/gentfarmer/f0f758e8f2a5d7a0a998ee06d586b1d0.js"></script>

When the Grimme pipe is outside the crop the tractor reverses and moves outside the crop for unloading, which is unnecessary. However when the pipe is in the crop the Grimme does not move out the crop so to unload you have to drive in the crop.
It's almost as if CP pathfinder is detecting the crop in reverse.

**Comment by pvaiko** [comment]
Need a logfile with debug channel 14.

**Comment by gentfarmer** [comment]
log file with debug channel 14
<script src="https://gist.github.com/gentfarmer/03cdeeb8e5b76893c2725f60e6c6dba6.js"></script>

NB that despite using an old saved game before the potato harvest and using the exact same Courseplay route the harvester only moved out of the crop, while the pipe was already outside the crop, once on the initial unload point.
However the harvester did not move out of the crop once the pipe was in the crop.
I hope the attached log file is of use and thank you to all the guys working on Courseplay 6, I couldn't play FS without it and it will be even better when mode 2 & 3 are finished.

**Comment by pvaiko** [comment]
Don't know how are you attaching that logfile but I can't read that.

**Comment by gentfarmer** [comment]
I used the same method as the first one Peter, however this one says the file is truncated but the full file can be viewed here
[https://gist.github.com/gentfarmer/a528b6f807380a5f9b47a6e7893b229b/raw/fed97e4f1ff209aa3f1d301422632b36ce4f5102/dave.wild.txt](url)
Looking at that file there are lots of dbg14 entries because I was harvesting a whole field, perhaps it would be better if I just logged the 2 instances where I think there are bugs and I upload 2 log files.

**Comment by pvaiko** [comment]
I wasn't able to download your first log either, and this one is just a link to  somewhere, no log file at all. 

Please make sure the link to the logfiles work.

**Comment by gentfarmer** [comment]
The previous log files were created in Gist (as the CP manual states) and the "create a secret Gist" link copied into these comments.
Does this work Peter?
[url=https://github.com/Courseplay/courseplay/files/4049596/log.txt]log.txt[/url]

**Comment by gentfarmer** [comment]
Fingers crossed this works Peter
[log.txt](https://github.com/Courseplay/courseplay/files/4058141/log.txt)

**Comment by pvaiko** [comment]
This time it worked and the log messages says 
2020-01-11 11:17 :12 [dbg14 lp13837] N134 (#1): Fruit left: 0.86 right 0.00, field on left true, right true
so CP clearly sees fruit on the left and nothing on the right. 
Wish you had a screenshot, there's something weird going on there, does this work ok with the Giants helper?

**Comment by gentfarmer** [comment]
I have a screen shot Peter but it's not very clear so i'll run the harvester again on a test field and also see if the same happens using AI

**Comment by gentfarmer** [comment]
If i run the Grimme 260 with a helper there is no attempt at all to move out of the crop for unloading Peter.
[pipe inside log.txt](https://github.com/Courseplay/courseplay/files/4071264/pipe.inside.log.txt)

![pipe in crop1](https://user-images.githubusercontent.com/25930119/72527125-f3b51180-385f-11ea-82a9-2f323c5e3081.jpg)

![pipe in crop 2](https://user-images.githubusercontent.com/25930119/72527148-fdd71000-385f-11ea-9763-939135d5cd29.jpg)

**Comment by gentfarmer** [comment]
When the Grimme 260 is doing the headlands and the pipe is outside the crop the 260 reverses out of the crop to unload even though that is not necessary

[pipe outside log.txt](https://github.com/Courseplay/courseplay/files/4071276/pipe.outside.log.txt)

![pipe out 1](https://user-images.githubusercontent.com/25930119/72527341-73db7700-3860-11ea-9efa-e02c4f09e606.jpg)

![pipe out 2](https://user-images.githubusercontent.com/25930119/72527353-7e960c00-3860-11ea-8a8f-5e959bf2a905.jpg)

![pipe out 3](https://user-images.githubusercontent.com/25930119/72527361-85248380-3860-11ea-938d-4a4495b0f09a.jpg)

**Comment by Tensuko** [comment]
seems to be ok
![fsScreen_2020_12_11_11_15_25](https://user-images.githubusercontent.com/27344744/101891372-3bdcd100-3ba2-11eb-9046-1680baa16ad8.png)

2020-12-11 11:13 :14 [dbg14 lp213554] 7210 Pro (#8): Fruit left: 0.00 right 0.84, field on left true, right true
2020-12-11 11:13 :14 [dbg14 lp213554] 7210 Pro (#8): change to fieldwork unload
