### ISSUE TITLE
Mode10: Aufschütten fährt nicht bis ans ende des Silos

### ISSUE THREAD

**Issue by Rumspringa90** [Courseplay/courseplay#4800]
Moin Moin,

Ich habe die CP Version 6.01.00359.dev

Ist das normal, das im Modus 10 bei der Betriebsart "aufschütten" der Fahrer mit dem Schiebeschild das Häckselgut nicht bis ans ende des Silo schiebt?
![Unbenannt](https://user-images.githubusercontent.com/50840355/72083696-860a6200-3302-11ea-9535-11117b73c427.jpg)
Ich hab das jetzt bei mehreren Silo getestet da ich einfach kein gescheites Bunkersilo finde. 

Gruß Henne

**Comment by Tensuko** [comment]
Kann ich so jetzt schwer sagen.
Ich weis nicht ob der Debugchannel 10 noch funktioniert dafür, aber einfach mal anmachen, laufen lassen und die log.txt hier posten (als datei hier einfügen).
Ansonsten die Frage: gehört das Land hinter dem Bunker dir ? Nicht das Da eine Sperre ist...

**Comment by Rumspringa90** [comment]
Ist ein bisschen länger die Log Datei, weil ich damit schon eine weile Teste.
[log.txt](https://github.com/Courseplay/courseplay/files/4041531/log.txt)
Das Land gehört alles mir ja. Hier nochmal ein bild mit den markieren vom Debug. Das Silo erkennt er meines Erachtens nach richtig.
![Unbenannt](https://user-images.githubusercontent.com/50840355/72087826-662a6c80-3309-11ea-9ea5-41e69648be00.jpg)

**Comment by Tensuko** [comment]
Jup, sieht erstmal gut aus, schaut sich jemand bei gelegenheit an.
Da es an sich funktioniert und sich nur um eine art 'Schönheitsfehler' handelt, verschieben wir das erstmal.

**Comment by Merrlin** [comment]
Das könnte an der Map bzw. dem Bunker liegen. Man sieht an der Log schön wie er die hinteren 75% schon als voll erkennt. Leider sieht man den roten Rahmen nicht. Bei mir hat der Schiebemodus auf der Hinterkaifeck am WE ohne Probleme funktioniert.

**Comment by Tensuko** [comment]
Ich mache den hier zu da sehr alt und grundsätzlich funktioniert es.
Denke es liegt an der Position, dass der hintere Teil nicht zum eigenen Land gehört oder die Bunker Area nicht passt.
