### ISSUE TITLE
Mode Specific Setting issues

### ISSUE THREAD

**Issue by Zoochase** [Courseplay/courseplay#4802]
Two issues, one only recent.
1: After using a vehicle as part of a multiple unit course, the "Lane Offset" does not reset or revert back to a single vehicle setting. It will go from "right" or "left" to -10 left or 10 right and must be manually changed back to zero or "-".  This even after the game has been shut down, obviously that setting being saved.  Shouldn't it reset as soon as you cancel the course?

2: Recently I noticed that after selecting "Activated" for Symmetric Lane Change, I can not switch back to "Deactivated".  As if locked out. 

Appreciate all your hard work CP.
Zoo

**Comment by Tensuko** [comment]
Wasn't there a button for resetting the lane offset ?

Didn't try the other one, but this would be a bug ofc.

**Comment by pvaiko** [comment]
@Zoochase I'll fix #2 but for #1, what exactly is the definition of 'cancelling a course'?

**Comment by Zoochase** [comment]
> 
> 
> @Zoochase I'll fix #2 but for #1, what exactly is the definition of 'cancelling a course'?

Clicking "Stop Driver" then the "X" to clear the selected course.  Maybe that is referred to as resetting?

**Comment by Tensuko** [comment]
For #1 

- a Course with 2 Vehicle ( left/right )
- Remove Course from Vehicle
- Lane offset change from left/right to the specific offset in meters
- Should get reset to zero or add a button to clear the offset

**Comment by Zoochase** [comment]
Symmetric Lane Change no longer works.  Button is fixed but it does not activate the maneuver.

**Comment by Tensuko** [comment]
The lange change works with newest Version.
I take it as solved and close this one.
Else write a Comment and I reopen or make a new Issue.

**Comment by Zoochase** [comment]
Seems to be working again.  Thank you very much.
