### ISSUE TITLE
Various erros in attempt to index a nil value MP Related

### ISSUE THREAD

**Issue by PromGames** [Courseplay/courseplay#4805]
Errors in the local game log
```
When using Baler
`CpManager.lua:920: attempt to index a nil value
Error: Running LUA method 'packetReceived'.
CpManager.lua:920: attempt to index a nil value`
 
When using plow
Error: Running LUA method 'packetReceived'.
2020-01-11 08:58 dataS/scripts/vehicles/specializations/events/PlowRotationEvent.lua(53) : attempt to index field 'object' (a nil value)
```
Errors in the game.log of the server
```
PurePursuitController.lua:560: attempt to index field 'course' (a nil value)
2020-01-11 00:24 Error: Running LUA method 'update'.
```

**Comment by Tensuko** [comment]
Full logfile of client and sever.

**Comment by PromGames** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4049423/log.txt)
[logclient.txt](https://github.com/Courseplay/courseplay/files/4049427/logclient.txt)

**Comment by PromGames** [comment]
Just a small comment on this issue, I saw that the errors refered above are produced in Dedi server, 

If you run from just a created multiplayer game, it works perfectly. 

I have tried to make remote debugging to dedi multiplayer but i get errors of no possible connection. Maybe some firewall or port problem.

**Comment by Tensuko** [comment]
Collecting all in #5484
