### ISSUE TITLE
Courseplay_6_01_00360 is not in installed mods

### ISSUE THREAD

**Issue by Boregepco** [Courseplay/courseplay#4806]
I don't know why I can't see this in installed mods...

I need a help...

Thank you in advance and sorry

**Comment by Tensuko** [comment]
logfile ?

**Comment by Boregepco** [comment]
I am with a 1.3.0.1 patch.
Courseplay_6_01_00354 i ok, but after it - not working.
I need to install a new patch or what?

**Comment by Boregepco** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4049485/log.txt)

**Comment by Tensuko** [comment]
No Idea where you got CP from, but this is the problem:
Error: Unsupported mod description version in mod Courseplay_6_01_00360

Download from the only official place here: https://github.com/Courseplay/courseplay/releases
Open Assets and download the zip file.
Copy that into your mods folder and delete the old one.

Also you should patch your game.

**Comment by Boregepco** [comment]
I made this like always.
With this one Courseplay_6_01_00353 I am ok - working.
All after it are not working.
Now I will try with this:
https://github.com/Courseplay/courseplay/releases/download/6.01.00361/Courseplay_6_01_00361.zip

**Comment by Boregepco** [comment]
"Also you should patch your game." - May be this is the problem...
