### ISSUE TITLE
V361, Mode1 doesn't react on triggers and doesn't stop on 1st Waypoint.

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#4807]
Title.
In 361 tractor doesnt stop at start (load point), it doesnt detect trigger at all, but with 360 version it works perfect.
Something is broken in 361 :D

**Comment by Tensuko** [comment]
Logfile ?

**Comment by bojanh66** [comment]
Which debug channels do i need to activate ?

**Comment by Tensuko** [comment]
Nevermind I created one....
[log.txt](https://github.com/Courseplay/courseplay/files/4050575/log.txt)

Stick to 360 for now.

**Comment by pvaiko** [comment]
Stupid typo, stupid reviewer...
