### ISSUE TITLE
Work with combine

### ISSUE THREAD

**Issue by ArtV-Nef** [Courseplay/courseplay#4808]
It would be desirable that the tractor when working with the combine and filling 100% did not tear at once from the place, and that eternal collisions turn out.

**Comment by Tensuko** [comment]
#3311 #4286 
Closed.

**Comment by Gibbanator** [comment]
is there anyway we can manually stop the combine from doing that? the collisions are a constant problem and is something that rarely happened in CP 2017. 

Just a question and nothing meant by it... Thanks for all you guys do..

**Comment by Tensuko** [comment]
Turn off Fruitbypass can help a bit.
