### ISSUE TITLE
Neuer Fehler.

### ISSUE THREAD

**Issue by Baker79** [Courseplay/courseplay#4809]
362 funktioniert jetzt teilweise. Traktor hält zwar am Startpunkt wird aber nicht beladen. Bitte nocheinmal überprüfen. Bei Gras hält der Traktor an bei Silage fährt er komplett durch.

**Comment by pvaiko** [comment]
Und mit 360 funktioniert alles ohne Probleme?

**Comment by Tensuko** [comment]
Bitte mal ein Screenshot von deinem Silagekurs und welche Fahrzeuge du genutzt hast.

**Comment by Baker79** [comment]
Hat sich erledigt. Danke trotzdem
