### ISSUE TITLE
Impossible to load a game

### ISSUE THREAD

**Issue by nico757** [Courseplay/courseplay#4811]
Hello, 
I've the last version of CPa dn also the last of Autodrive.
It's impossible for me to load a fame. I get this error

 C:/Users/nicol/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00362/course_management.lua:1722: attempt to call method 'GetAvailableDestinations' (a nil value)

Thanks

**Comment by Tensuko** [comment]
I already can tell you that you don't have the latest AutoDrive Version.
https://github.com/Stephan-S/FS19_AutoDrive/releases
ModHub one is totaly outdated.
Get that one and report.
Closed.
