### ISSUE TITLE
Mauvaise traduction Française 

### ISSUE THREAD

**Issue by taz87** [Courseplay/courseplay#4813]
Lors de la dernière mise à jour de la traduction français, les modifications ont été pires que l'original. Le texte est devenu presque incompréhensible
Est il possible de revenir aux anciens fichiers?

**Comment by Tensuko** [comment]
English Translation pls.

**Comment by knoxville73** [comment]
The message of @taz87 is this.
The last french translations are very bad.  Is it possible to reload the previous french translations ?

**Comment by Tensuko** [comment]
Thx.
You can make better translations and make a pull-request on github. Then @pvaiko will add them.

**Comment by knoxville73** [comment]
I don't know the system to make a pull-request.  See the file in attachment for the French translations
[translation_fr.txt](https://github.com/Courseplay/courseplay/files/4056142/translation_fr.txt)

**Comment by pvaiko** [comment]
Sorry, we'll accept changes only through pull requests.

Also, those speaking French should figure it out, we can't judge the quality of a translation. We haven't seen our regular French translator (@DavidFONTAINE) for quite a while.
