### ISSUE TITLE
lua:1277: attempt to call method 'isAutoAimNodeFixed' (a nil value)

### ISSUE THREAD

**Issue by SkiiBlock** [Courseplay/courseplay#4814]
I was fulfilling a water tank (MKS 32) and then the game froze without explanations. I've unload every mod I was using but the error came again.

Here is the log and a picture before the freeze.

[log.txt](https://github.com/Courseplay/courseplay/files/4055618/log.txt)

![Farming Simulator 19 Screenshot 2020 01 13 - 21 17 35 74](https://user-images.githubusercontent.com/26041016/72289185-d5c29380-364a-11ea-89aa-02247ca248da.png)

**Comment by SkiiBlock** [comment]
****I'm using the Mode2 Alpha version

**Comment by Tensuko** [comment]
That Version is not Made for other things to do.
It is only for test Mode2. Stick to normal release for such tasks.
Also for Water Transport use Mode1, wich needs a Modtank for best use.
Closed.
