### ISSUE TITLE
verteilen und verdichten Probleme

### ISSUE THREAD

**Issue by Flo1293** [Courseplay/courseplay#4815]
Cosplay fährt mit verteilen und verdichten modus wenn ich ihn auf 5 Meter einstelle mit den originalen verschiebe Schild in die linke Wand oder rechte Wand oder fährt im Kreis über in Bunker wenn er groß genug ist muss ich was einstellen dass er das nicht mehr tut ist es immer noch so wie in ls17 würde Hilfe benötigen war auch schon bei mir in ls17 teilweise so
![cp verdichten](https://user-images.githubusercontent.com/59848371/72292579-f510ef00-3651-11ea-85bc-106c0d718298.png)

**Comment by Tensuko** [comment]
Duplicate of
#4621 #4547
