### ISSUE TITLE
Convoy order optional

### ISSUE THREAD

**Issue by Misamangame** [Courseplay/courseplay#4816]
Hello guys,

first of all thank you for this great mod.  I do play on very big maps and very often (all the time actually :) ) use multiple equipment on 1 field. I use course loading at startup and this led me to this idea. If it was disscussed before sorry for that, did not seen it.. .When you have multiple tools and now talking especially about combines on the field (other equipment are not really an issue) you want them to go on proper order to harvest field from edges which looks better and is more realistics, but if you start them after loading the game you have to make sure to do it in correct order otherwise they will go in order you start them. So my question is if it is possible to fix Convoy order how you want from the start of the course (on creation) and if it is possible to keep this order with saved course ? Or change it manually if needed even during the work?

**Comment by Tensuko** [comment]
Is this still actual ? We don't rly know what you want to have.
Can you make some kind of a drawing where you explain what you want to do ?

**Comment by Tensuko** [comment]
Closed due to inactivity.
