### ISSUE TITLE
Multiplayer Harvest Issue

### ISSUE THREAD

**Issue by Saskfarmer** [Courseplay/courseplay#4817]
Hey ive been using courseplay with my roommate and we found when combining the auger will not come out on the joined players screen. Combines are modded versions of the johndeere S series.

**Comment by Tensuko** [comment]
What do you mean with combining the auger ?

Also what Modded Combines and what is the actual problem ?

logfile ?

**Comment by Saskfarmer** [comment]
Ok so I’m on one computer roommate is on the other. We have 3 combines activated on a course, when he pulls up with the grain cart the unload auger/pipe does not fold out but the combine unloads. On my computer when I pull up with the grain cart the auger will fold out and work normally. On his screen it still doesn’t fold out. It’s vice versa as well If I start the course with the auger folded out, the auger will stay folded out on his computer the whole course. My computer is hosting the server.

I will post both log files from each computer.

If you need screenshots as well I can post some.

**Comment by Tensuko** [comment]
Should be the same as in #4711
