### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by williaint9** [Courseplay/courseplay#4819]
Attempted to install version 6.01.00362 on 14/1/20. Downloaded master zip, unzipped, rezipped as per multiple youtube tutorials. No matter what I try, Courseplay does not appear on the list of mods to enable when starting a game. Have taken .zip from filename, tried all manner of unzipping and rezipping procedures, deleted all other mods in case of clash. Pulling my hair out at this point.

**Comment by Tensuko** [comment]
Download from release page https://github.com/Courseplay/courseplay/releases

Aseets - download the .zip file.
Copy and Paste into Mods Folder. No need to unzip and zip anything.
Pro Tip: Always Name it the same so you wont end up have 2 versions inside mods folder (e.g. FS19_Courseplay.zip ).
