### ISSUE TITLE
Gerät bzw. Maschine schaltet nicht ab (Multiplayer)

### ISSUE THREAD

**Issue by Matze9876** [Courseplay/courseplay#4820]
Hallo zusammen,

ich habe folgendes Problem auf unserem Server (ich weiß leider nicht ob dieses Problem bereits bekannt ist?):

nach dem z.B. der Gülle- oder auch Miststreuer zum befüllen fährt, schaltet das Gerät nicht ab.
Auch die Streuanimation läuft weiter.
Das befüllen funktioniert tadellos.

Ähnliches passiert auch beim Ladewagen, er hebt den Pickup schaltet ihn aber nicht aus!
Ich verwende Couseplay Version 00362
AutoDrive 1.0.7.0-35
GlobalCompany 1.2.0.0
![1](https://user-images.githubusercontent.com/57115689/72445921-d8d89380-37b2-11ea-89b6-f336b6b7f1eb.png)

https://gist.github.com/Matze9876/6cda78f009893ecef42b04b438806162#file-log

Es spielt dabei auch keine Rolle, ob Courseplay oder Autodrive den Lade- bzw. Entladekurs fährt.

**Comment by Tensuko** [comment]
@davboecki

**Comment by Tensuko** [comment]
Collecting all in #5484
