### ISSUE TITLE
Arcusin Autostack don´t Unload on the Field

### ISSUE THREAD

**Issue by Lars-LS17** [Courseplay/courseplay#4821]
Hello Together,

the Arcusin Autostack didntUnload the Bales on the Field.
![fsScreen_2020_01_15_19_00_29](https://user-images.githubusercontent.com/31773176/72459889-10076e80-37cc-11ea-9a96-9af425944363.png)
[Uploading log.txt…]()

**Comment by Tensuko** [comment]
You got to add a course where to unload them... Check for tutorials on youtube.

**Comment by Lars-LS17** [comment]
Oh. Is it not possible to Unload directly on the Field? The Setting to Unload on the Field doesnt work?

**Comment by Tensuko** [comment]
Well... I never rly used that one so I just forgot about that option...
@pvaiko ?

**Comment by Lars-LS17** [comment]
If it's not implemented, that's ok. 
Theni do a second course on the field.

**Comment by Lars-LS17** [comment]
I only need the car stack to collect the bales. Then I pick them up with a trailer.

**Comment by Tensuko** [comment]
I am not sure if that should work already or it is a bug.
Wait for @pvaiko to check in, he maybe knows it :)

**Comment by pvaiko** [comment]
No there's no such feature you need an unload course to unload the bales.
