### ISSUE TITLE
Fix mode "alignment and consolidation" of silage

### ISSUE THREAD

**Issue by Sania1996** [Courseplay/courseplay#4822]
When you select the "alignment and compaction" mode, labels appear on the screen, and in the "construction to the end" mode, the silo does not tamp.
I will be grateful. Good day :)

**Comment by Tensuko** [comment]
I have no idea what you talking about.
Logfile, screenshot, discribe it more precise.

**Comment by Tensuko** [comment]
Closed due to inactivity.
If it is about Silo compacting, check for existing Issues about this.
