### ISSUE TITLE
HUD-Option: Am Startpunkt Ende 'nil'

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#4823]
Hallo @pvaiko es steht 
Am Startpunkt Enden und bei Autodrive jeweils nil da und ich kann da nichts auswählen.

![fsScreen_2020_01_16_11_18_59](https://user-images.githubusercontent.com/3021040/72516789-8babfe80-3852-11ea-9b25-3462a44f0d72.png)

![fsScreen_2020_01_16_11_19_04](https://user-images.githubusercontent.com/3021040/72516809-91a1df80-3852-11ea-90e2-c112c1093229.png)

[log.txt](https://github.com/Courseplay/courseplay/files/4070594/log.txt)

MFG Mannie313

**Comment by Mannie313** [comment]
Sorry hatte vergessen zu erwähnen ist im Singleplayer spiel.

MFG Mannie313

**Comment by pvaiko** [comment]
Debug channel 7 und 14.

**Comment by pvaiko** [comment]
Ach so, sorry, log nicht nötig.
