### ISSUE TITLE
HybridPathfinding: LUA Callstack on sharp Headland Turn for Combine

### ISSUE THREAD

**Issue by Merrlin** [Courseplay/courseplay#4824]
Hi together,

Combine: Rostselmash RSM 161
Cutter: Diamond HS12
both Vanilla
Testgame just with CP in Mods
CP Version 364 

With sharp headland Setting a LUA Callstack occurs when the combine reaches the first Headland Corner and wants to Turn. With a smooth headland set up everything is fine. Maybe CombineSelfUnload shows the same problem but didn't  tested it on my testsave (just figured out a similar Callstack on my normal game).
[log.v364.txt](https://github.com/Courseplay/courseplay/files/4070977/log.v364.txt)

**Comment by Tensuko** [comment]
2020-01-16 12:13 Error: Running LUA method 'update'.
2020-01-16 12:13 C:/Users/Daniel/Documents/My Games/FarmingSimulator2019/mods_cp/FS19_Courseplay/PurePursuitController.lua:314: bad argument #1 to 'abs' (number expected, got nil)

+ Callstack

Does CP freeze when this happens ?
Also not sure if it works but can you create a logfile with debugchannel 9 12 and 14 ?

**Comment by Merrlin** [comment]
ja und nein... Die Framerate bricht stark ein und man kann nur noch eingeschränkt was machen. HUD bleibt ein bißchen bedienbar (abfahrer lässt sich entlassen), ebenso die Konsole.
Heir der Log
[log.txt](https://github.com/Courseplay/courseplay/files/4071274/log.txt)

**Comment by Tensuko** [comment]
Was heist Abfahrer ? Mode2 ?

**Comment by Merrlin** [comment]
Nene, der Button halt um den Drescher zu starten bzw. wieder zu beenden. Wenn ich mich recht erinner heißt der so.

**Comment by Tensuko** [comment]
Ja ok das ist halt auf deutsch Zweideutig, wollte nur sicher gehen :)

**Comment by Tensuko** [comment]
Versuch mal Version 365

**Comment by Merrlin** [comment]
Funzt wieder wie in der Drescherfahrschule... Dankeschön
