### ISSUE TITLE
Conflicting key bindings

### ISSUE THREAD

**Issue by Mogli12** [Courseplay/courseplay#4826]
Hi,

The courseplay editor blocks the keys KEY_leftbracket and KEY_rightbracket even if the courseplay editor is not even visible. Would it be possible to change onRegisterActionEvents so that it does not block other mods to use the same keys? Currently, [VehicleControlAddon](https://github.com/Mogli12/VehicleControlAddon) does not work together with courseplay.

Regards, Stefan

**Comment by Tensuko** [comment]
@russbeuker
Can you maybe do something about CP Keybindings in general ?
There are some other Issues with this, like ShovelPositions.
Maybe you got an Idea for a solution to this ?

**Comment by russbeuker** [comment]
@Tensuko I will take a look at this keybindings issue.

**Comment by Tensuko** [comment]
@Mogli12 
Does this still happens with latest release ?
I have changed some stuff about keybinds.

**Comment by Mogli12** [comment]
Yes, it is fixed for me.
