### ISSUE TITLE
Error LUA stack when baling

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#4827]
In version 362 or 363 i didnt have this LUA error when baling, but with 365 i have it, happens when tractor try to move from one to another row.

After few experiments, i found the cause.
With use AI turn maneuvers (Deactivated) it happens.
When this option is Activated, lua error doesnt happen.

Vehicle is Xerion 5000 and Claas square baler.

[log.txt](https://github.com/Courseplay/courseplay/files/4072515/log.txt)

**Comment by Tensuko** [comment]
2020-01-16 17:46 C:/Users/Gaming/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00365/Waypoint.lua:820: attempt to get length of local 'waypoints' (a nil value)
2020-01-16 17:46 Error: Running LUA method 'update'.

**Comment by SledgeHammer75** [comment]
same error here, not limited to bailer

**Comment by Woife1** [comment]
That part ends in this error

818 --- Append waypoints to the course
819 function Course:appendWaypoints(waypoints)
820	for i =1, #waypoints do
821 		table.insert(self.waypoints, Waypoint(waypoints[i], #self.waypoints + 1))
822 	end
823	self:enrichWaypointData()
824 end
