### ISSUE TITLE
Errors ohne Ende und Fahrzeuge fahren einfach weiter

### ISSUE THREAD

**Issue by f4mous96** [Courseplay/courseplay#4828]
Hallo,

in den Versionen 363 - 365 erscheint immer wieder der fehler "2020-01-16 20:01 dataS/scripts/animals/AnimalHusbandry.lua(354) : attempt to perform arithmetic on local 'minute' (a nil value)
2020-01-16 20:01 Error: Running LUA method 'update'."

Die Kamera bleibt dabei auf dem Punkt stehen und die CP-Helfer fahren aber immer gerade ausweiter.

**Comment by f4mous96** [comment]
anbei die Log mit Version 362 wo der Fehler auch kurz aufgetreten ist.
[log.txt](https://github.com/Courseplay/courseplay/files/4073366/log.txt)

**Comment by Tensuko** [comment]
Erstmal ist das nicht die aktuellste CP Version und zweitens: was hat der Fehler mit CP zu tun ?
Dafür sind zu viele andere Mods da und der Pfad sagt auch nichts über CP und die Beschreibung nützt auch nichts.
Closed.

**Comment by pvaiko** [comment]
Das ist kein CP Fehler, das ist ein Fehler in Giants Code.
