### ISSUE TITLE
Problem with courseplay when ending grid path with modded sugar beet header

### ISSUE THREAD

**Issue by resultwrap** [Courseplay/courseplay#4830]
I have a modded sugar beet head that harvests at 75.0m (lol), http://www.farming2015mods.com/farming-simulator-19-mods/fs-19-combines/fs19-ropa-rr-6x45-crazy-v1-0/
It was working fine in every version until v6.01.00363 and so on. So I'm not sure if it's that mod that's the issue but I somehow have a feeling it is courseplay. I'm also not sure if this is happening to other players with similar mods? Just thought I would bring it up.

Basically, it runs through the straight path fine until it reaches the end of the path to turn around, that's when courseplay quits, the machine keeps driving forward and nothing responds either than changing machines. I can't click anything, stop driver, mouse doesn't show up, etc. I have to force quit the game. https://youtu.be/fgfIGPJPBGA

I apologize for the laggy video... I couldn't understand why it was doing that in the editor either.

**Comment by Tensuko** [comment]
We are not supporting selfmade unrealistic Mods, since we want to make Courseplay to work as realistic as possible.

Closed.

**Comment by resultwrap** [comment]
Makes sense! I do have multiple savegame's that I try to be as realistic as possible, just this one savegame where I like to test things and go to the extreme. I will look out for more realistic issues.
