### ISSUE TITLE
Field calculator works half way

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#4831]
Hello devs.
Can you please take a look at this thread?
https://forum.giants-software.com/viewtopic.php?f=963&t=157546

One guy has CP field calculator, but when i try to do the same thing as him, i dont have.

I load the game, i own the seeder, load the course, drive to the field and CP calculator doesnt show up, but if other guy do the same, he has CP calculator.

I dont understand.

**Comment by Tensuko** [comment]
As the guy said, after buy seeder, reload game to have the calculator.
We will take a look at it, when it still works, we just got to move it to a proper position...

@pvaiko can you take a look at that ?
It seems like the Calculator shows up when you load a game and get into a seeder (doesn't work if you buy new one).

**Comment by bojanh66** [comment]
After few minutes of experiments, here is how it works:
1. i already own the seeder, so i attached it to the tractor and drive to the field
2. create a seeding course
3. check tab and CP calculator is not there
4. but, now i save game, then exit the game
5. load the game, create again seeding course and the CP calculator is there
6. if i detach and attach seeder, CP calculator is GONE (missing) until i again load the game

So yea, it is kinda "buggy", works only if you have loaded the game with already attached seeder to tractor...once you detach it, its game over until you reload the game.

So dear devs, is it possible to fix this, its such a nice tool :)

**Comment by Tensuko** [comment]
Did anyone try then if it calculates the seed correctly ( + - a few % ) ?

**Comment by bojanh66** [comment]
Well, now i got LUA error when i tried to calculate seed usage on different field.
But from what i can see before i got an error, it seems seed usage is correct.

2020-01-17 11:00 Error: Running LUA method 'draw'.
2020-01-17 11:00 C:/Users/Gaming/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00366/hud.lua:609: attempt to index local 'selectedField' (a nil value)

[log.txt](https://github.com/Courseplay/courseplay/files/4076276/log.txt)

**Comment by AndyK70** [comment]
is it possible to have the calculator even without attached seeder?
If I remember correctly I could have been sitting in a tractor open up the cp panel, select a field and did the calculation for how many seed I would need for that field. The seed type I could select in the calculator, if my memory doesn't trick me. Then I would buy the amount missing...
I always found it very handy to do calculations without needing to have the seeder ready with me.

**Comment by Tensuko** [comment]
We have a lot of other and more important things to do right now.
This calculator was just a side project.
Ofc its handy but there is just no time for it... maybe you can find someone who does a new calculator.
Keep in mind that some Mods throw more fertilizer then other, wich will end up in miscalculations :)
