### ISSUE TITLE
Test Report for Pre-release ver: 6.01.00366

### ISSUE THREAD

**Issue by skjatala** [Courseplay/courseplay#4833]
Pre-release ver: 6.01.00366
Map : Ellerbach v: 1.0.0.8
Course Type : Field work
Fields No : 29 Seeding , 31 Plow , 30 Lime spreading. 
Tool Types : Mix (Stock and Mods)
![Untitled-2](https://user-images.githubusercontent.com/9192542/72604769-60520e00-393d-11ea-9cb1-b033270753d4.png)
![Untitled-3](https://user-images.githubusercontent.com/9192542/72604782-6647ef00-393d-11ea-831f-2932a922ba43.png)
Log File . https://gist.github.com/skjatala/3adf680aa6eb4827fd1a1bf532883fe6
![Untitled-1](https://user-images.githubusercontent.com/9192542/72604804-7069ed80-393d-11ea-891d-fd6ddaf1ba55.png)
 One thing from me If you all ( Dev Team ) please don't mind. When user satisfaction level reached at 70 , 80%  suddenly change basic framework (It is my own thinking).  I also know very well your all working hard day and night without any greed.
Sorry for my poor English.

**Comment by pvaiko** [comment]
Which tool is this on the second and third screenshot? Also, make screenshots with the course visible, log with debug channel 7 and 14

**Comment by Tensuko** [comment]
Can't reproduce with V369

**Comment by skjatala** [comment]
@pvaiko "Which tool is this on the second and third screenshot? " it is plow "Rovic Leers DLB19 Pack"  from Farming Simulator's official web site, Link =https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=135316&title=fs2019.
and sorry my bad it is no any error with stock plows in same fields.
