### ISSUE TITLE
Achtung imme wenn ich mehre Abfahrer einstelle kommt der fehler

### ISSUE THREAD

**Issue by RudiBergfeld** [Courseplay/courseplay#4834]
immer wenn ich einige Abfahrer einstelle , ich kommt der Lua fehler das Problem habe ich seit der Version 364 siehe Log
[log.txt](https://github.com/Courseplay/courseplay/files/4076550/log.txt)

**Comment by Tensuko** [comment]
Bitte einmal die Version 367 ob der Fehler noch immer auftritt.
In welchem Modus passiert es denn ?

**Comment by RudiBergfeld** [comment]
ich muss euch enteuschen bei der Version 367  kommt immer noch der selbe Fehler bei 4 abfahrer 2 im modus  Sähen und Düngen 2 im modus Feldarbeit nach ca 15 min hier  noch mal die Log
[log.txt](https://github.com/Courseplay/courseplay/files/4077133/log.txt)

**Comment by Tensuko** [comment]
2020-01-17 14:54 Error: Running LUA method 'update'.
2020-01-17 14:54 C:/Users/rudib/OneDrive/Dokumente/My Games/FarmingSimulator2019/mods/courseplay367/course-generator/PathfinderUtil.lua:314: attempt to call method 'getNumberOfWaypoints' (a nil value)

Aber der turn Fehler + LUA Callstack sind raus aus deiner log, das ist schon mal gut.

**Comment by RudiBergfeld** [comment]
Auch version 369 hat nichts gebracht hier noch mal di Log
[log.txt](https://github.com/Courseplay/courseplay/files/4077209/log.txt)

**Comment by Tensuko** [comment]
Continue in the English Post here #4837
Closed due to duplicate.
