### ISSUE TITLE
Mode 2 headland turn driver offload collision

### ISSUE THREAD

**Issue by Corran1327** [Courseplay/courseplay#4835]
in Mode 2 the offloading drive will not clear away allowing the combine to make the turn. this only happens when driver does not have enough time to complete or get into position before the combine reaches turn.

in other words, if both combine and offloader are reaching the turning point at the same time

see pictures
![Farming Simulator 19 01_16_2020 19_19_06](https://user-images.githubusercontent.com/36859747/72614932-7cd05500-3901-11ea-810e-c370b604fc42.png)

**Comment by Twetch** [comment]
Mode 2 is not finished yet, so use Autodrive..

**Comment by Tensuko** [comment]
#3311 #4286 
Closed.

**Comment by Corran1327** [comment]
So I know this is closed and my initial bug report was bad but I thought I was using the new mode2 from the beta branch does that make a diference

**Comment by Tensuko** [comment]
That I would have to know ofc, if you use the Mode2AlphaBranch...

**Comment by Corran1327** [comment]
sorry mod version 6.01.00359

**Comment by Corran1327** [comment]
I'm going to try this again with today's version. ill post again if I reproduce with something better..... btw looking at the log file the potato harvester doesn't like the ai traffic collision so....
