### ISSUE TITLE
Combine class 8920

### ISSUE THREAD

**Issue by moose31608** [Courseplay/courseplay#4839]
When it gets to end of field it locks up and won’t make the turn

**Comment by Tensuko** [comment]
Logfile with channel 7 and 14

**Comment by moose31608** [comment]
It works just fine in 6.01.00362 but not in 6.01.00371

**Comment by Merrlin** [comment]
Anyway we need a Logfile with mentioned channels

**Comment by Tensuko** [comment]
Try again with Version 376 and report, or make a logfle with channel 7, 12 and 14.

**Comment by moose31608** [comment]
Yes that helped a lot. When are you going to fixed once the grain cart had unloaded into semi? And when it chases after combine it not all over the field wit tractors

**Comment by Tensuko** [comment]
For Mode2 see #3311 and #4286 
I won't answer 'when' questions.....

I think this can be closed now.
