### ISSUE TITLE
deleting saved courses 

### ISSUE THREAD

**Issue by donaldm5050** [Courseplay/courseplay#4840]
it glitches sometimes and the courses get messed up. so wed have to create a folder for deletes to put the messed-up ones in.

**Comment by Tensuko** [comment]
I need more details on that one.
Multiplayer or Singleplayer ?
When does that happen and what means messed up ?
Can you show us the XML files ?

**Comment by donaldm5050** [comment]
multiplayer
id go to click the save course once its clicked it would jump to a different course and then it would add them together

**Comment by Phlonk** [comment]
How do you delete courses in MP? Do I have to manually delete it from the folder on the server?
Thanks for any information.

**Comment by Tensuko** [comment]
Collecting all in #5484
