### ISSUE TITLE
Der Lua fehler ist noch da

### ISSUE THREAD

**Issue by RudiBergfeld** [Courseplay/courseplay#4841]
Ich habe immer das Proplem das ich immer den Selben Luafehler habe seit der Vesrion 364 ist mir das Augefallen auch mit der Version 371ist das Problem nicht behoben. Die version 362 läuft bei mir ohne probleme wie im Singel als auch im Multiplayer. Immer wenn ich 2 bis 3 Abfahrer laufen habe tritt das Problem auf . Ich habe hirzu schon einmal ein Issuer erstellt das ist aber als Duplikat Geschlossen worden. Hier noch mal die Log von der Version 371.
[log.txt](https://github.com/Courseplay/courseplay/files/4080788/log.txt)

**Comment by Tensuko** [comment]
2020-01-18 15:22 Error: Running LUA method 'update'.
2020-01-18 15:22 C:/Users/rudib/OneDrive/Dokumente/My Games/FarmingSimulator2019/mods/courseplay371/course-generator/HybridAStar.lua:613: attempt to index field 'nextEdge' (a nil value)

Wenn er als Duplicate geschlossen wird, heist es das der Fehler wo anders bereits behandelt wird und wir nicht 20mal das gleiche Issue brauchen.

Duplicate of #4836
Closed.
