### ISSUE TITLE
Courseplay hangs scanning fields on some maps

### ISSUE THREAD

**Issue by WolfmoonCT** [Courseplay/courseplay#4844]
I have found that some maps when I try to start a new game, CoursePlay will never do the scan fields and the game basically stops working.  No keyboard commands are accepted in the game., and I have to End Task the game to get out.
This is trying to use the auto scanning of the fields.

Here is the log file from the game.  What other files do you need?
[log.txt](https://github.com/Courseplay/courseplay/files/4082688/log.txt)

**Comment by Tensuko** [comment]
Only one Map allowed in Mods Folder and fix your Errors in Mods Folder, you got several Mods twice ( the (1) in the name ) or with failure:

Error: Invalid mod name 'FS19_CSZ_pack(1)'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Load mod: FS19_CSZ_pack (Version: 1.4.0.0) (Hash: 04d7f2c79ad4dee33776f076a85dfd2d)

Error: Failed to open xml file 'C:/Users/wolfm/Documents/My Games/FarmingSimulator2019/mods/FS19_flieglDPW180RB_BD/modDesc.xml'.
Load mod: FS19_flieglDPW180RB_BD (Hash: 818f39e0e23d256a798047851d6e1838)

Error: Invalid mod name 'FS19_LizardAutoloader(1)'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Load mod: FS19_LizardAutoloader (Version: 0.1.0.8) (Hash: 3794639b26d9ceb750291fa4b40fbcde)

Error: Invalid mod name 'FS19_Variable_Spray_Usage(1)'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Load mod: FS19_Variable_Spray_Usage (Version: 1.0.0.0) (Hash: 75c66e5ba35d7ae5456ce9ec2df1e3c6)

Error: Failed to open xml file 'C:/Users/wolfm/Documents/My Games/FarmingSimulator2019/mods/Map_FS19_Kiwi_Farm_4x_V3UNZIP/modDesc.xml'.
Load mod: Map_FS19_Kiwi_Farm_4x_V3UNZIP (Hash: e30ef738a7b338e54a146049af5479e1)
Error: Missing descVersion attribute in mod Map_FS19_Kiwi_Farm_4x_V3UNZIP

Also update CP to V374 https://github.com/Courseplay/courseplay/releases 
Other then that, there is no LUA Error in your log, so hard to say if the game stopped working or you just need to have some patience...

**Comment by pvaiko** [comment]
Also, since you did not tell us which specific maps have this problem it is difficult to say anything useful, most of the time this is caused by unclean field boundaries on the map.

**Comment by WolfmoonCT** [comment]
Sorry, I already cleared out the (1) mods, and the map I'm trying to load is Old Farm Countryside right now.

**Comment by WolfmoonCT** [comment]
Updated to the v374, and I get the same issue.  I cleared the log and this is the one from the test.
[log.txt](https://github.com/Courseplay/courseplay/files/4082733/log.txt)

**Comment by Tensuko** [comment]
You have still more then 1 Map in the Folder.

FS19_Ellerbach
FS19_Great_Plains
FS19_GreenRiver2019
FS19_Marwell_Manor_Farm
FS19_Oakfield
FS19_TheOldFarmCountryside
FS19_thePacificNorthwest
FS19_The_Old_Stream_Farm
FS19_Welker_Farms

And this:
Error: Failed to open xml file 'C:/Users/wolfm/Documents/My Games/FarmingSimulator2019/mods/Map_FS19_Kiwi_Farm_4x_V3UNZIP/modDesc.xml'.
Load mod: Map_FS19_Kiwi_Farm_4x_V3UNZIP (Hash: e30ef738a7b338e54a146049af5479e1)
Error: Missing descVersion attribute in mod Map_FS19_Kiwi_Farm_4x_V3UNZIP

Also I am not sure if Seasons can handle it if you got several GEO_Datas in your Mods-Folder.
Since I know from Forums, Seasons is messing arround with the code a lot...

**Comment by archaoncze** [comment]
I had same issue, but it was caused by animal pen extension (map champaign of france) - probably it had problem with custom animal pens.

**Comment by WolfmoonCT** [comment]
Thanks so much archaoncze.  Disabling Animal Pen Extension fixed it.  CP did the scan an the game loaded perfect.

**Comment by dbump** [comment]
I am seeing this issue on the Baltic Sea map from the official modhub.  CoursePlay takes about 40 seconds to scan fields 16 and 17.  The other 46 fields go by in a blur like normal.  I have tested this with only the three mods required by the map and CoursePlay active and visible to the game.  Is there any additional info I can provide?  I'm attaching the log.
[log-CP.txt](https://github.com/Courseplay/courseplay/files/4991667/log-CP.txt)
Not sure if that worked, here is the Gist link if it didn't: https://gist.github.com/dbump/c24aa065b9e51d24ace6aae4291f3003
