### ISSUE TITLE
i got a error code 

### ISSUE THREAD

**Issue by donaldm5050** [Courseplay/courseplay#4846]
idk if anyone else has gotten it but i got this error code that stops all courses and freezes up. 
020-01-19 14:30 C://SERVICES//ni2633638_1_local//lws19//profile/mods/Courseplay_6_01_00366/course-generator/PathfinderUtil.lua:350: attempt to perform arithmetic on a nil value
2020-01-19 14:30 Error: Running LUA method 'update'.
im on multiplayer 

tried using 374, 371 and 366 
[Error_Log.txt](https://github.com/Courseplay/courseplay/files/4083892/Error_Log.txt)

**Comment by Tensuko** [comment]
You also got a LUA Callstack, no Idea where it come from.
Also this one:
2020-01-19 17:59 Error: Running LUA method 'update'.
2020-01-19 17:59 C://SERVICES//ni2633638_1_local//lws19//profile/mods/Courseplay_6_01_00374/course-generator/PathfinderUtil.lua:363: attempt to perform arithmetic on a nil value

**Comment by pvaiko** [comment]
This may also be caused by using custom fields, could you try with 376 and report back?

**Comment by donaldm5050** [comment]
works a lot better no crashes so far

**Comment by theSwed506** [comment]
Got the same error on single player custom field 3.75. Will try 3.76

**Comment by Tensuko** [comment]
Closed due to inactivity, and should be solved with 376 or higher.
