### ISSUE TITLE
Coarse Play Causes Crashing

### ISSUE THREAD

**Issue by tyfauber** [Courseplay/courseplay#4847]
When launching a save file a randomly crashed course play.  When I went to hook up any trailer hitch would then freeze and crashed my game.  The tax time I loaded this a file without course plays it worked perfectly fine. I have tried removing all mods, going to different maps, and it only happens when I have course play on. I have tried all the different versions of course play. Does anyone know why this is happening?  It would be much appreciated if we can figure this one out as I have a ton of time into save file and I really enjoy using course play.

**Comment by Tensuko** [comment]
logfile ?
https://github.com/Courseplay/courseplay/wiki

**Comment by tyfauber** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4087608/log.txt)

**Comment by Tensuko** [comment]
Fix your Mods with Errors first.
Then get the newest CP Version and then delete the old one, not like this:

Load mod: courseplay (Version: 6.01.00364) (Hash: 80f34e4bfa949bace6fef0234d641433)
Load mod: courseplay342 (Version: 6.01.00342) (Hash: e2c4882a5b62ec1a82ef9414f05a1a70)

Also the Error spam is not from CP:
2020-01-19 22:23 Error: Running LUA method 'update'.
2020-01-19 22:23 dataS/scripts/AchievementManager.lua(257) : attempt to index local 'farm' (a nil value

**Comment by tyfauber** [comment]
I figured it out. I had a secondcourse play hidden in the mod folder

**Comment by Tensuko** [comment]
As I said... :) 
This should be solved then.
Closed.
