### ISSUE TITLE
A few questions from the gamer and junior developer from Belarus

### ISSUE THREAD

**Issue by valerismel** [Courseplay/courseplay#4849]
Hi!

You are a very cool team that creates a cool product - mod CoursePlay.

I have a few questions about the work of the mod.

1. Users constantly have questions about what they are building a route for transporting cargo, but the cargo is not unloaded. The question arises about how to fill the seeder after it has run out of seeds and fertilizers, only fertilizers are refueled, but the seeds are not.
Would you like to record video tutorials on how to work with all agricultural units?
Maybe you should think about a developer’s video blog?
Or maybe one could ask someone how and what works and record a video of a guide to your answers.
If such a person exists, give his contacts. (Email, WhatsApp, ets.)

2. The mode has debug mode.
Would you like to talk about him? What and how does it work? How can users use it during the game?

-------
Valery Melnikov.
valerismel@gmail.com

**Comment by pseikoNL** [comment]
FYI, here you’ll find a manual for Courseplay:
http://courseplay.github.io/courseplay/en/manual/index.html#intro

Notice: At this moment it’s not up-to-date, but it explain most of the basic Courseplay functions.

**Comment by Tensuko** [comment]
Check youtube tutorials for 'how to'.

For unload Cargo, this is due to Mode2 Work in Progress. See Stickys.

For Refill: Just bypass one seed and one fertilizer silo to refill both.
Also: I build a route from field to seed, fertilizer and lime silo, so I can use it for any tool that needs to be refilled and it does work.

Debug Channels are only needed when we ask for them, else they are named in the CP HUD, for what they are.

**Comment by valerismel** [comment]
> Check youtube tutorials for 'how to'.
> 
> For unload Cargo, this is due to Mode2 Work in Progress. See Stickys.
> 
> For Refill: Just bypass one seed and one fertilizer silo to refill both.
> Also: I build a route from field to seed, fertilizer and lime silo, so I can use it for any tool that needs to be refilled and it does work.
> 
> Debug Channels are only needed when we ask for them, else they are named in the CP HUD, for what they are.

Thanks!  At night, I read the manual and watched a video of English-speaking children.  I sort of figured it out a bit.  I will try.  
The Russian guys have a lot of questions about how and what works and they cannot find the answers.  So I decided to figure it out.

**Comment by valerismel** [comment]
> Check youtube tutorials for 'how to'.
> 
> For unload Cargo, this is due to Mode2 Work in Progress. See Stickys.
> 
> For Refill: Just bypass one seed and one fertilizer silo to refill both.
> Also: I build a route from field to seed, fertilizer and lime silo, so I can use it for any tool that needs to be refilled and it does work.
> 
> Debug Channels are only needed when we ask for them, else they are named in the CP HUD, for what they are.

Who is this Stickys? I didn't find him.

**Comment by Tensuko** [comment]
#3311 and #4286

**Comment by Tensuko** [comment]
Closing this to keep Issues clean.
If you have more questions, ask here (maybe I notice it) or make a new specific Issue.
