### ISSUE TITLE
Corseplay und AutoDrive

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#4851]
Mit der Neuesten version 376 übergibt Courseplay den Entlade Kurs nicht an Autodrive weiter auf dem Dediserver.

Sobald ich Cp anmache geht das Autodrive abfahren soll weg und der Strohsammler bleibt stehen.

Bei bedarf kann ich gerne ein Video Schicken.

MFG Mannie313

**Comment by pvaiko** [comment]
Und vor 376 ging es noch? Geht nur in MP nicht oder?

**Comment by Mannie313** [comment]
das habe ich noch nicht getestet kann ich gerne machen ob es im sp nicht geht.

Ja es ging im sp ob dedi es vorher auch ging weiß ich leider nicht.

MFG Mannie313

**Comment by Flo1293** [comment]
spiele ls19 sp und habe heute mal cp6  und habe  dann mal autodrive wieder rein in meine mode ordner in mein game gepackt und wolte spielen und ist immer hängen geblieben :(

**Comment by Tensuko** [comment]
Collecting all in #5484
