### ISSUE TITLE
Trailer loading

### ISSUE THREAD

**Issue by Podvorie** [Courseplay/courseplay#4852]
Sorry, I don’t speak English and it’s hard for me to look for a similar problem.

Problem: 

Very often I encounter the problem of loading a trailer in factories.
In automatic mode, the download does not occur. But if you sit in the tractor, then filling the trailer begins without any action of mine.

If necessary, I can make a video recording of the problem.

Map: Saxony 2019
Tractors and trailers - MISCELLANEOUS. Regardless of the mod or standard.

I also did not see the dependence on the type of plant or cargo. 

https://www.youtube.com/watch?v=VB5OU64zgz8

**Comment by Tensuko** [comment]
This can be one of those Problems:
- GlobalCompany Version is to old (1.2 comes soon on the ModHub)
- Courseplay Version is to old (Wich Version do you have ?)
- Or this Problem:

GlobalCompany Factories can have more then one Line, means Cargo A Transforms to Cargo B and Cargo C Transforms to Cargo D.
Now there is the Problem, that, when you want to load Cargo B, you choose Cargo B.
But when you want to load Cargo D, you also got to choose Cargo B.

But I can tell you maybe more, when you show me your logfile.
Drag and drop the log.txt into the comment box.

**Comment by Podvorie** [comment]
CP - 376
Global Company 1.1.0
[log.txt](https://github.com/Courseplay/courseplay/files/4096035/log.txt)

**Comment by Podvorie** [comment]
UPD.
Found, downloaded and installed Global Company 1.2.0.
Part of the problem is resolved. Now I check all the errors of loading the cargo known to me on this map

**Comment by Tensuko** [comment]
Then it was Global Company.
You Need 1.1.2 or higher to work with CP.
Version 1.2 comes to ModHub soon. (Or already is)

**Comment by Podvorie** [comment]
Thx.
I will monitor the situation
