### ISSUE TITLE
courseplay come up with wrong  measurement 

### ISSUE THREAD

**Issue by Mavrick373737** [Courseplay/courseplay#4854]
when try to set a course up on Felsbrunn tool Bredal K165 come up with 30 meter and 24 meter work width when it suppose to be 18 m and 12 m  can U fix it yes i am using the last courseplay just down 4 hours ago

**Comment by GeorgeEarslight** [comment]
This is correct, different width between lime and fertilizer.

**Comment by Tensuko** [comment]
The Width is beeing calulated by the AiMarkers if I am not wrong and will depend on the filltype you put in there, just as @GeorgeEarslight mentioned.
I will take a look on it whats going up and see if there is something wrong...

**Comment by Tensuko** [comment]
Works as it should.
You maybe have to click the button next to width that the generator use and next to that one is the width that CP calculates or get from the tool.
Just take a look before click generate :)

Closed.
