### ISSUE TITLE
worker don't start

### ISSUE THREAD

**Issue by denbeau** [Courseplay/courseplay#4855]
I downloaded courseplay and set up a course. Then i started the course, from the first point and he don't do anything. There is a hired worker in my tractor.  Somebody can help me please

**Comment by Tensuko** [comment]
logfile ?!
Vehicle, Tool, Mode, Screenshot, etc..... 
https://github.com/Courseplay/courseplay/wiki

**Comment by denbeau** [comment]
![image](https://user-images.githubusercontent.com/60213122/72967719-3f1c7200-3dc2-11ea-9c9f-7d2efe84d457.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4101979/log.txt)

**Comment by pseikoNL** [comment]
Error: Invalid mod name 'courseplay-master'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Load mod: courseplay (Version: 6.01.00360) (Hash: ae9dd8846054cae2c5f127962e396088)
Error: Unsupported mod description version in mod courseplay
Error: Invalid mod name 'courseplay_Beta mod 22-1-2020'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Load mod: FS19_CoursePlay1128 (Version: 6.01.00279) (Hash: fb94ddb94f7de224f20e302089bec773)
Load mod: FS19_CoursePlay6 (Version: 6.01.00084)
Load mod: FS19_CourseplayBeta (Version: 6.01.00376) (Hash: b8fc867b86ea59334abb1110efd00e75)
Error: Unsupported mod description version in mod FS19_CourseplayBeta
—-

You have more than 1 courseplay version in your mod folder

**Comment by denbeau** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4102238/log.txt)
still the same issue after i deleted them

**Comment by denbeau** [comment]
is it maybe because i didn't update? 
i am now updating

**Comment by denbeau** [comment]
FOUND IT thanks anyway
