### ISSUE TITLE
seit V6.01.00360 CP im Modordner funktioniert der Mod FS19_zzzSpeedControl nicht mehr

### ISSUE THREAD

**Issue by Willi-77** [Courseplay/courseplay#4856]
Hallo hab gemerkt das seit einiger Zeit der mod "FS19_zzzSpeedControl" nicht mehr funktinoniert hab jetzt herausgefunden liegt an Courseplay nehme ich CP aus dem Modordner heraus geht es.
Hab es mit der Aktuellen Version herausgefunden vom CP 6.01.00376 als es das letzte mal noch funtionierte war es die CP version 6.01.00348 nächste version vom CP die ich getestet habe war die 6.01.00360 dort ging der Mod auch schon nicht mehr.

mfg Willi

Hello have noticed that for some time the mod "FS19_zzzSpeedControl" has not worked anymore. It is now due to Courseplay, I take CP out of the mod folder.
I found it out with the current version of the CP 6.01.00376 when it worked the last time it was the CP version 6.01.00348 the next version of the CP I tested was the 6.01.00360 there the mod didn't work anymore.

mfg Willi

**Comment by Tensuko** [comment]
Musst deine Tastenbelegung mal überprüfen.
Kann sein das CP + und - irgendwo verwendet, wir sind am Keybinding dran.

**Comment by Willi-77** [comment]
Danke erstmal für die schnelle Reaktion, ne hab ich schon nachgesehen dem ist eigentlich nicht so. Geht um die drei Geschwindigkeiten die man speichern kann die liegen auf den Tasten 1-3 und die 1 und 2 lassen sich nicht mehr aktivieren nur die Taste 3 so wie im originalen Spiel. Liegt ja eigentlich nichts vom CP auf den normalen Zahlentasten 1-3.

**Comment by Tensuko** [comment]
Hmm okay.
Dann weis ich so spontan auch keine Abhilfe.
Müsste man nachschauen was das ist.

**Comment by Willi-77** [comment]
Hab die spielelog überprüft da gibts auch keinen Fehleranzeige die auf CP oder den mod hindeutet!

**Comment by huffert** [comment]
Das liegt an dem Editor. der verwendet 1 + 2.
die musst du umlegen. dann geht speedcontrol wieder

**Comment by Tensuko** [comment]
Also Keybinding, wie ich vemutet habe. Bitte mal rückmelden, dann verlinke ich das und mache es hier zu, wenn es daran liegt.

**Comment by Willi-77** [comment]
Ja stimmt lag doch an einer Doppelbelegung hatte gestern auch nochmal nachgesehen und dann gemerkt das auf den Tasten 1 und 2 jetzt auch was vom CP liegt hatte ich vorher übersehen.
Mal noch he Frage zu der Editorfunktion kann man da jetzt Course nachträglich bearbeiten wenn ja wo??

**Comment by Merrlin** [comment]
Ja kannst du... Wenn du in einem Fahrzeug sitzt das den CP Kurs geladen aber noch keinen Abfahrer eingestellt hat einfach Strg-E drücken.
Dann kommst du in den Editor Mode.

**Comment by Tensuko** [comment]
Kurs laden, Strg+E (CP Editor Toggle muss erst mit der taste belegt werden) dann kann man editieren und mit strg+F6 abspeichern (das funktioniert ohne tastenänderung).

Dann kann hier ja zu, da das eigentliche Problem gelöst ist.
