### ISSUE TITLE
v6.01.00376 wierd turns at start of new row

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#4857]
Take a look at video.
Started happening recently in last few versions, in older versions, tractor would start row perfect.
Path calculation is good at first, but once tractor approach new row, it offsets to the right.
log txt is with channel 14 only.

https://www.youtube.com/watch?v=17vxAVk_9fg&feature=youtu.be

[log.txt](https://github.com/Courseplay/courseplay/files/4104882/log.txt)

**Comment by Tensuko** [comment]
It works as it should, thats the new generated turn and have to make that adjsutment on pulled tools.
When you have unworked areas due to that one, let us know.
You can also turn it off with adv. settings use pathfinding.

**Comment by bojanh66** [comment]
There is a tiny bit of unworked area, even with activated "Use pathfinding in turns".
Its basically almost the same turn as with deactivated that option, but a bit better, offset is smaller, but still not perfect like in previous versions with old turn.

**Comment by Tensuko** [comment]
I had it too now with a smal pulled seeder.
Sometimes it shrinks back, sometimes not.
I still try to figure out when happens what and what could be solution like end the turn more early or something.

Skip row is not rly the problem, it is the new generated course, wich is basically not bad, but need some adjustment, mostly happens only on pulled tools.

**Comment by pvaiko** [comment]
Yeah, that offset should go back to 0 once the tractor is driving straight again, I'll take a look.

**Comment by Tensuko** [comment]
![Turn](https://user-images.githubusercontent.com/27344744/73086952-eb994980-3ed1-11ea-9022-b83b0eb10ea7.png)

What I noticed is, it happens more on offsets from start to stop when it looks like A.
Means the end of the turn is a smaler straight path, so the offset doesn't move back to the middle, means the tool is not alligned correctly.... I try make a screenshot of it....

**Comment by Tensuko** [comment]
![fsScreen_2020_01_24_17_55_49](https://user-images.githubusercontent.com/27344744/73087471-d670ea80-3ed2-11ea-896f-1619451196d2.png)
![fsScreen_2020_01_24_17_55_39](https://user-images.githubusercontent.com/27344744/73087472-d670ea80-3ed2-11ea-81fb-3d7a2ff804bd.png)
![fsScreen_2020_01_24_17_55_33](https://user-images.githubusercontent.com/27344744/73087473-d7098100-3ed2-11ea-9c6a-4406a07be33d.png)
![fsScreen_2020_01_24_17_54_54](https://user-images.githubusercontent.com/27344744/73087474-d7098100-3ed2-11ea-8968-9549e3106b33.png)
![fsScreen_2020_01_24_17_54_50](https://user-images.githubusercontent.com/27344744/73087475-d7098100-3ed2-11ea-955c-3197ca825340.png)
![fsScreen_2020_01_24_17_54_43](https://user-images.githubusercontent.com/27344744/73087477-d7a21780-3ed2-11ea-9440-ab7a8c7671ac.png)
and log
[log.txt](https://github.com/Courseplay/courseplay/files/4109601/log.txt)

**Comment by edjon2000** [comment]
Little thing, modDesc.xml still showing 6.01.00376

**Comment by Tensuko** [comment]
Try 377 Release and report back.

**Comment by edjon2000** [comment]
All good,

Thank you
