### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by KasparsGr** [Courseplay/courseplay#4858]
Courseplay version 4.01
Map: Greenwich valley(Mod map)
Crashes everytime I try to put it on harvesting with ingame John Deere harvester, game camera freezes and combine drives away.
The same happened when i tried fertilizing a field, also with ingame tractor

**Comment by Merrlin** [comment]
https://github.com/Courseplay/courseplay/wiki

Please add a Logfile. And which courseplay version? 4.01 is not a FS19 version number?

**Comment by ianbrown11** [comment]
I basically have the same problem I do use the fieldwork for my fertiliser and I choose it to go up and down the field and every time it makes a turn the game freezes and the vehicle continues on but if I choose the fertiliser to go around the field instead of up and down I have no issues

**Comment by Tensuko** [comment]
No logfle, then no one can help you.....

Indeed CP 4.01 is not an actual CP Version.
Pls keep in mind that we only support CP for FS19.
Older Versions are not supported anymore.

**Comment by KasparsGr** [comment]
Sorry, new to all of this. 
It appears its the version 364
[log.txt](https://github.com/Courseplay/courseplay/files/4107732/log.txt)

**Comment by Tensuko** [comment]
For all, always check for a newer Version before make Issues with few Versions lower...
Pls report back if Errors is gone.

**Comment by KasparsGr** [comment]
Dont have this error with the new version. 
But I have a question about paying the worker with courseplay. It appears for me, that with courseplay it is not paying the worker. Is it not yet a feature in CP or I havent set it properly?

**Comment by Tensuko** [comment]
Check under CP Hud the Advanced Settings, it is on the 2nd Page (Global Settings).

I close this then.
Anything new make new Issue.
