### ISSUE TITLE
Specially for courseplay

### ISSUE THREAD

**Issue by PromGames** [Courseplay/courseplay#4859]
[https://youtu.be/V8EYBWRaTfA](https://youtu.be/V8EYBWRaTfA)

![](https://cdn1.giants-software.com/modHub/storage/00149990/screenshot5.jpg)

**Comment by Tensuko** [comment]
I would say this should be an addon for the Mod itself, that you get 'into the vehicle' but end up stand next to it with the remote in the hand, if that is even possible.
No Idea how CP could handle this.
