### ISSUE TITLE
Courseplay LUA CALL STACKS with Trailer from "Gator Pack"

### ISSUE THREAD

**Issue by Phippsi** [Courseplay/courseplay#4861]
Hallo,

also nach mehreren Tagen konnte ich nun die Ursache für die LUA CALL STACKS finden.

Und zwar bekommt man diese Fehler nur wenn man entweder den Anhänger "**Gitter**" oder "**Plattform**" vom John Deere Gator Pack ankuppelt. **NUR** bei diesen beiden**!!!**
Dabei spielt es keine Rolle mit welchem Fahrzeug man das macht ( getestet wurden: der Gator, ein Traktor und der PickUp).

Da es den Fehler über Courseplay auswirft, vermute ich dass das Problem auch an Courseplay liegt.
Ich hoffe ich kann helfen diesen Fehler zu fixen!

Hier meine log.txt:
**[log.txt](https://github.com/Courseplay/courseplay/files/4112148/log.txt)**

**Comment by Tensuko** [comment]
Das jeder Trailer der einmal zur Plattform umgebaut wurde und angekuppelt wird einmal einen CallStack wirft ist bekannt und hat keine weitere Auswirkungen.
Siehe #4743 und #3145
Closed.
