### ISSUE TITLE
Conflict with Added Realism For Vehicles

### ISSUE THREAD

**Issue by DerBauer2** [Courseplay/courseplay#4862]
Hallo ich hätte da eine Frage beim Dreschen. Wenn der Drescher auf der Seite fährt wo das Rohr im Korn ist, konnte dieser doch wenn der Korntank voll war nach hinten Rechts ausweichen so das der Abfahrer nicht in diese Frucht gefahren ist. Wurde das entfernt oder muss dies eingestellt werden?

Danke schon mal für die Hilfe.

**Comment by Tensuko** [comment]
Fruchtumfahrung auf an stellen, dann sollte er das auch machen.

**Comment by DerBauer2** [comment]
Das Läuft jetzt zwar aber es giebt da Probleme mit AD. Wie man im Bild sieht muss der Abfahrer in die Frucht Fahren. Wenn der Anhänger dann aber nur halb voll ist bleibt ja AD Normal da stehn heißt der Drescher wird dann dort Blockiert. Kann man nich einstellen wie weit der Drescher Ausweichen soll das dass Rohr mehr auserhalb der Frucht ist`?

![20200126150622_1](https://user-images.githubusercontent.com/60297613/73136407-92eebb80-404d-11ea-9ecf-bdb3403cf720.jpg)

**Comment by pvaiko** [comment]
#3987

**Comment by DerBauer2** [comment]
@pvaiko aber das Problem mit REA löst das nicht.

**Comment by pvaiko** [comment]
Keine Ahnhung was REA ist.

**Comment by Tensuko** [comment]
So, Mod Conflict, kann es selber nicht reproduzieren, ansonsten Duplicate of #3987

Closed.

**Comment by DerBauer2** [comment]
was soll das denn hier? Fehler bestehen weiter hin? wird so mit fehlermeldungen um gegangen?!

**Comment by Tensuko** [comment]
Du hast auf der AD Seite doch geschrieben, dass das Problem an der einen Mod liegt.
Außerdem konnte ich es nicht reproduzieren.
Das andere mit dem Abstand ist bereits bekannt, also welchen Fehler haben wir übersehen ?
Sollen wir uns jetzt mit der Mod, die du hier nicht mal genannt hast, auseinander setzen ?

Und du hast die Frage von @pvaiko auch noch nicht beantwortet, was ist REA ?

**Comment by DerBauer2** [comment]
> Und du hast die Frage von @pvaiko auch noch nicht beantwortet, was ist REA ? 

Doch im dem Anderen welches du geschlossen hast.

Ich versuche ja schon zu zuarbeiten das ich denn moder angeschreiben habe.

**Comment by Tensuko** [comment]
> Doch im dem Anderen welches du geschlossen hast.

Da hatte es aber nichts zu suchen und der Issue war absolut überflüssig!

**Comment by Mannie313** [comment]
@Tensuko das mit dem abstand kann es auch an den schneidwerken liegen. umso Breiter das schneidwerk umso weiter von der frucht weg?

MFG Mannie313

**Comment by pvaiko** [comment]
Abstand ist Arbeitsbreite aber maximum 6 m. Wollte ich schon ändern, ist nur eine Kleinigkeit, für Selbstentladen musste ich die Rohrlänge sowieso implementieren, bin noch nicht dazu gekommen.
