### ISSUE TITLE
old mode2

### ISSUE THREAD

**Issue by eric4072** [Courseplay/courseplay#4866]
Hi!
Erstmal ich bin kein Scripter oder Modder, mir ist nur was aufgefallen:

Gleich mal danke für diese geile Mod! Sie macht für mich LS19 erst spielbar und ich will gar nicht schätzen wieviel Arbeit ihr da reinsteckt...

Ich hab auch gelesen dass ihr mit dem neuen Mode2 schon auf einem guten Weg seit. Trotzdem eine Frage für den alten Mode2, vielleicht sinds ja nur ein paar "Handgriffe"

Mir ist aufgefallen, dass wenn ich CP kurz vorm Silo auf "Abfahrer entlassen" und gleich wieder auf "Abfahrer einstellen" klicke, jeder CP-Fahrer den Silo beim durchfahren erkennt und die Geschwindigkeit IMMER passt. Egal welcher Tracktor (ob Mod oder Ingamekontent). Beim normalen durchfahren lassen kommt es häufig vor dass der Traktor scheinbar die Länge nicht erkennt und zu schnell durchfährt.

Vielleicht könnt Ihr was damit anfangen und man kann da eine schnelle Lösung einbauen. 

Danke, macht weiter so,

Eric

**Comment by Tensuko** [comment]
Wird nicht passieren.
Siehe #4286 da gibt es ein Video wo zu sehen ist, wie das neue System im Bunker ablädt.
Closed.
