### ISSUE TITLE
#4862

### ISSUE THREAD

**Issue by DerBauer2** [Courseplay/courseplay#4867]
Warum wird es einfach geschlossen ohne zu versuchen eine lösung zu finden?
Man solte schon mit seine Supporte besser um gehen wenn sie sich schon die ganzen mühen machen.

@pvaiko    REA=https://www.farming-simulator.com/mod.php?lang=de&country=ch&mod_id=138280

**Comment by Tensuko** [comment]
Du musst dafür kein neues Issue aufmachen...
Mache hier zu, rest wird in #4862 geklärt!
