### ISSUE TITLE
The problem with trailed potato harvesters

### ISSUE THREAD

**Issue by KroshkaRoo** [Courseplay/courseplay#4868]
CP v6.01.00377
VEHICLES
Valtra N144
Grimme SE 260

MAP
Yagodnoe 2.4.11

LOG

https://pastebin.com/vejMk7Xk

The problem arises when unloading vehicles try to build a route to a potato harvester. Not only SE 260, but also with combines from mods, for example AKPIL Kartofel.

**Comment by Tensuko** [comment]
This sounds like Mode2 to me ?!
See #3311 and #4286

**Comment by KroshkaRoo** [comment]
Yes, this is MODE 2. But with a normal potato harvester, unloading transport works fine.

**Comment by Tensuko** [comment]
You got to wait for the new Mode2 to come online, see the Issues I mentioned in my other Comment.
Closed.
