### ISSUE TITLE
Round Headland Corners not round

### ISSUE THREAD

**Issue by Zoochase** [Courseplay/courseplay#4869]
When selecting "Round (turn radius)" with multiple tools, the final corner is not rounded and causes the tractor to get bound up with the tool.  This happens on original and created fields like posted.
![InkedInkedCourse Generator_LI](https://user-images.githubusercontent.com/25461823/73240108-d717b400-4152-11ea-899c-1d0ea0f32230.jpg)
![InkedProposed Course_LI](https://user-images.githubusercontent.com/25461823/73240126-e0a11c00-4152-11ea-947f-68a426853a83.jpg)
![Stops](https://user-images.githubusercontent.com/25461823/73240160-f7477300-4152-11ea-94c7-22216b2767d2.jpg)
![Turns](https://user-images.githubusercontent.com/25461823/73240167-fadafa00-4152-11ea-9291-c8eaa075c12b.jpg)
![backs](https://user-images.githubusercontent.com/25461823/73240171-fdd5ea80-4152-11ea-9a61-4e0768ee42c4.jpg)

**Comment by Tensuko** [comment]
This Should be done in Multitool Rework, try Version 394 or higher.

**Comment by Zoochase** [comment]
Looks good.  Thank you very much.
