### ISSUE TITLE
Vorschlag/Anregungen - Proposals / suggestions

### ISSUE THREAD

**Issue by DerBauer2** [Courseplay/courseplay#4870]
Ich weis nicht ob es Technisch umsetzbar ist aber es wäre eine nette Funktion wenn man bei CP einstellen könnte das er beim Dreschen das Vorgewende das Stroh Häkelt und dann bei denn geraden Bahnen Ablegt. Wäre für das Automatische Ballen Sammlern sicher Besser. Was haltet ihr davon?

I do not know whether it is technically feasible but it would be a nice function if you could set at CP that he crochets the straw when threshing the headland and then deposits it on straight tracks. Would be better for automatic bale collectors. What do you think?

**Comment by Tensuko** [comment]
Wurde bereits Vorgeschlagen: #4324

Duplicate, Closed.
