### ISSUE TITLE
Courseplay not loaded in game at startup

### ISSUE THREAD

**Issue by jododk** [Courseplay/courseplay#4872]
Coruseplay is not loaded in to the game.

In the log fil i get this error:

Load mod: Courseplay_6_01_00377 (Version: 6.01.00377) (Hash: 768e332f6a26954071c158ee22642011)
Error: Unsupported mod description version in mod Courseplay_6_01_00377

[log.txt](https://github.com/Courseplay/courseplay/files/4127413/log.txt)

If i load Courseplay_6_01_00330 is will load and works

**Comment by Tensuko** [comment]
Only download it from here:
https://github.com/Courseplay/courseplay/releases

**Comment by jododk** [comment]
I have only download from https://github.com/Courseplay/courseplay/releases

This morning i try to download 6.01.00366, 6.01.00376 and 6.01.00377, this will not work, when i download 6.01.00330 is working

**Comment by Tensuko** [comment]
The Courseplay_6_01_00377.zip ?
Do not unpack and pack again, you can directly use it but delete old CP Versions!
You can also Rename it to FS19_Courseplay.

Btw... you log is missing a lot like Game Version and Stuff.....

What I can tell you is that the moddesc is ok and game loads to the Problem is somewhere on your side...

**Comment by billydragon** [comment]
> 
> 
> I have only download from https://github.com/Courseplay/courseplay/releases
> 
> This morning i try to download 6.01.00366, 6.01.00376 and 6.01.00377, this will not work, when i download 6.01.00330 is working

Me too. FS19 version 1.4.1 Steam not load courseplay after 6.01.00330.

**Comment by Tensuko** [comment]
Patch your game to 1.5.1
Always newst CP and newest FS Version is required.

**Comment by billydragon** [comment]
Fs19 latest version currently on Stream is 1.4.1 not an 1.5.1 for me now.

**Comment by Tensuko** [comment]
https://steamcommunity.com/app/787860/discussions/0/2733047810448603148/

How to get back to 1.4.1:

    Go to Steam Library
    Right click on Farming Simulator 19
    Choose “Properties” tab
    Choose “Beta” tab, then select patch 1.4.1

Maybe you should change to normal and not Beta 1.4.1 ?

**Comment by jododk** [comment]
Thanks it works after update th FS 19
