### ISSUE TITLE
Frage - Jeder Xte Spur

### ISSUE THREAD

**Issue by DerBauer2** [Courseplay/courseplay#4873]
Hallo Liebes Team,
Ich habe mal eine Frage. Ich hatte hier mal Bilder gesehn wo der CP Fahrer die Fähigkeit hat spuren zu überspringen. Also jede 2 Spur zu nehmen und das gleiche dann zurück. Ich meine jetzt nicht wenn 2 Fahrer auf dem Cours sind. Leider finde ich denn Post nicht mehr wo man das jetzt bildlich sehn kann.

Weiß man was ich meine?

**Comment by Tensuko** [comment]
Du wählst im Kursgenerator unten links einfach 'Überspringe Feldreihen' die entsprechende gewünschte Anzahl aus.
Besonders gut kommt es, wenn man ansät das ganze so ein zu stellen:
Vorgewende (Anzahl je nach Arbeitsbreite), Beginnen auf Feldreihen und Feldreihen überspringen 2 oder sogar 3, spart auch Zeit beim Wendemanöver.

**Comment by DerBauer2** [comment]
Okay das läuft super Danke :)
