### ISSUE TITLE
CP bugs out the game when finishes task.

### ISSUE THREAD

**Issue by Ursus95** [Courseplay/courseplay#4874]
A few weeks ago I ran into this problem. I loaded the save game(at this [https://www.modhoster.com/mods/mig-map-madeingermany-celle](url) map), and I tried to continue the course that I ran last time. The course contain a fieldwork part(collecting hay) and a transport part(from the field to the hay storage). The moment when the trailer was full and the mod switched to the transport part of the course the game freezed and the log was written all over with this error: addRequiredCropType foliage must match the size of the ground terrain detail.

The map is up to date, the coursplay is up to date, I tried to ran the save game with only just the map, the seasons mod and the courseplay mod and got the same error.

This save game file has 96 hours on it, so the bug is a new thing. I ran this course for many times before, with no changes at all before the error. I didnt changed any mod, before the first error, just happend one day to another. Its a possibility that the game itself got an update in that time, but Im not sure.

I bumped into a ton of people having this same issue, and the answer they got was the map they are playing on is causing it, or other mods. But in my case I didnt had problem with the map before, and the other mods didnt caused it because I tested it.

I also checked the hay storage, and it had more than enough room for that load of hay.

[log.txt](https://github.com/Courseplay/courseplay/files/4135329/log.txt)

**Comment by Tensuko** [comment]
Error: Failed to open xml file 'C:/Users/Koppány/Documents/My Games/FarmingSimulator2019/mods/Krone_BigX/modDesc.xml'.
Load mod: Krone_BigX (Hash: 312aa18615afd1ba275f4b6d5a424c05)
Error: Missing descVersion attribute in mod Krone_BigX

Error: Invalid mod name 'VehicleControlAddon-master'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

2020-01-30 18:58 Error: Failed to open xml file 'C:/Users/Koppány/Documents/My Games/FarmingSimulator2019/mods/LS19_MIG_Map_MadeInGermany_Celle/maps/map_transportMissions.xml'.

And I would guess this will cause the Error:
2020-01-30 19:01 Error: 'maizeHeap' (fertilizerShape) doesn't have all required vertex attributes for material 'fertilizer1'.

Also as always and forever:
Only one Map in Mods Folder allowed.... the more Maps with Scripts the more Problem you will have.
It also could be that you already corrupted your savegame with this Errors and to many Maps in it and did something that caused the Error...

This got no Error related to CoursePlay, so I close this.
Check Forums on your Mods with Errors....

**Comment by Tensuko** [comment]
What you could try is to make a new savegame with only map and courseplay in mods folder and try to reproduce this.
If you can, tell us exactly what you did.

Sry that I can't help you more on that.
