### ISSUE TITLE
mode10 problem - bunker silo fill level is decreasing while CP uses blade to fill it up

### ISSUE THREAD

**Issue by suchna** [Courseplay/courseplay#4875]
Hi guys,
  this is my first bug report, so sorry if i miss something and please ask me.

I am trying to fill bunker silo at my BGA station with chaff, but i struggle doing so. I set a course for unloading trailer which go infront of bunker (due to lack of space to the left corner), reverse back to bunker. Unloading trigger is recognised well, trailer starts to tip, but when heap is too high, it should go a little bit forth, but tractor wont move and cut engine off.

This is probably because of my inexperience, so any advice appreciated.

Bug comes when I use another tracktor with blade in the back to push heap to the end of bunker and fill it up. CP works correctly and will move whole heap in a while. BUT on each turn, fill level of silo is lover and lover. When I deactivate CP, switf message blinks on screen saing "fill limit of 3000 litres exceeded" or something like that

![mode10-bug-bunker-silo-fill-level-decresing](https://user-images.githubusercontent.com/1729587/73499347-26165100-43c0-11ea-913c-50057835fced.png)
LEGEND: 
  **tipping course (yellow color) generation:** start at position **_1._** - go forward to position **_2._** - hit "reverse" and go back as straight as posible to position **_5._** (end of bunker)- hit 'reverse' to stop reversing, make 'unload here waipoint'  - go forward to position **_6_**. and try to stay as close as posiible to reversing route - drive away to position **_7._**

  **Yellow Problem:** at position **_3._** trailer starts to open up while reversing. At position **_4._** Trailer start unloading, but stops due to maximum heap of chaff behing him. Engine stops and nothing else happens.

**Red color filling problem**: Start at position **_a)_**, lowers blade, **Fill level of bunker is 160k litre**s of chaff. Hits heap of chaff at position **_b)_** fill level of bunker starts to fluctuate and when tractor finish pushing of chaff at position **_c)_** (end of bunker) fill level of bunker rapidly decrease to 158k litres. Tractor goes to position **_d)_** and starts all over. **After 6 cycles, fill level is only 148 825 litres of chaf**f. And I tipped surely more than 400000 litres yesterday.

**When I stop CP** - message is shown on a screen for about 0.5sec. It has yelow-red color and flashes and looks alike official giants warning. And it says something like "fill unit 1 limit of 3000 litres has been exceded"

log file with modes 123 for tipper and mode 10 for filling:
[log.txt](https://github.com/Courseplay/courseplay/files/4136821/log.txt)

**Comment by suchna** [comment]
At first, I tried it with original orange 5m blade whitch has capacity 12000 litres, but it does sema thing much quicker - almost 10 full trailers with capacity over 50k litres and result was 150k litres of chaff int the bunker

**Comment by Tensuko** [comment]
Yea there is somehow a bug that the shield takes all the chaff like a bunker.

But btw why did you do all the drawing ? Just turn on view all Waypoints in CP HUD Settings....

**Comment by Tensuko** [comment]
It was a bug here but somehow the fix didn't work then
#1949

**Comment by GeorgeEarslight** [comment]
Is the OP by any chance using the 
[Fill Level Limiter](https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=150303&title=fs2019)
mod ?

**Comment by Tensuko** [comment]
Load mod: FS19_FillLevelLimiter (Version: 1.0.0.0) (Hash: 475a82cba6f391d180bffdc0b63a7be6)

Not sure what you mean with OP, but yea it is in and thats a good point @GeorgeEarslight

**Comment by GeorgeEarslight** [comment]
> Load mod: FS19_FillLevelLimiter (Version: 1.0.0.0) (Hash: 475a82cba6f391d180bffdc0b63a7be6)
> 
> Not sure what you mean with OP, but yea it is in and thats a good point @GeorgeEarslight

OP = Original Poster
I'm quite confident that whatever the fill level limiter script does to the silo blade, is also destroying the chaff.

**Comment by suchna** [comment]
> 
> 
> Yea there is somehow a bug that the shield takes all the chaff like a bunker.
> 
> But btw why did you do all the drawing ? Just turn on view all Waypoints in CP HUD Settings....

I used screenshot for mode 10 problem, where you can see all waypoints. But was lazy to make anotherone for tipping, so I quickly drow lines for tipper, so that you can give me advice if i do something wrong. Surely I can make new screenshot with waypoints visible. Or try to instal OBS and make a video to youtube.

**Comment by suchna** [comment]
> 
> 
> > Load mod: FS19_FillLevelLimiter (Version: 1.0.0.0) (Hash: 475a82cba6f391d180bffdc0b63a7be6)
> > Not sure what you mean with OP, but yea it is in and thats a good point @GeorgeEarslight
> 
> OP = Original Poster
> I'm quite confident that whatever the fill level limiter script does to the silo blade, is also destroying the chaff.

That sounds reasonable... I downloaded that mod last week and hasn't been playing since that, until yesterday. I also downloaded Variable bale capacity mod https://www.farming-simulator.com/mod.php?lang=en&country=cz&mod_id=129836&title=fs2019 so that can be mod conflict. 

Will try it in the evening and share results. Thanks for helping.

**Comment by suchna** [comment]
So it's mod conflict with [Fill Level Limiter mod](https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=150303&title=fs2019)

I have just tested it after deleting this mod and after 15 cycles only 120 litres of chaff disapierd which I assumed is because of some kind of rounding...

**Comment by Tensuko** [comment]
I close this one then.
This would need a fix in the other mod to ignore shields.

**Comment by suchna** [comment]
I suggest to add this mod conflict to [pinned modconflict page](https://github.com/Courseplay/courseplay/issues/3882)
