### ISSUE TITLE
Couseplay doesn't warn when a equipment is "slipping" anymore?

### ISSUE THREAD

**Issue by KauzDs** [Courseplay/courseplay#4878]
I noticed in the last few days while playing that many times equipment will get stuck in trees, buildings etc or just slipping on "mud" and CP will not give the little red warn in the low left corner above the minimap.

Here is a little video of it: https://streamable.com/t28if
Log: https://pastebin.com/raw/pZFAYprp
Version: 6.01.00378

**Comment by Tensuko** [comment]
Slipping is back and Working.

Closed.
