### ISSUE TITLE
Error: Running LUA method 'update' - drive.lua:114: attempt to index a nil value

### ISSUE THREAD

**Issue by TomaszWychocki** [Courseplay/courseplay#4879]
This issue seems to be similar to #4663.

My game freezes randomly when combine is working with AI enabled or when I'm trying to generate path for combine.

In log file I'm getting this error:
```
2020-02-01 19:32 Error: Running LUA method 'update'.
2020-02-01 19:32 C:/Users/wycho/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00378/drive.lua:114: attempt to index a nil value
```
[log.txt](https://github.com/Courseplay/courseplay/files/4143159/log.txt)

**Comment by Tensuko** [comment]
I got my Combine work with AI Enabled too.
Do you have a Mode2 driver running, maybe with an IT Runner or something ?

**Comment by TomaszWychocki** [comment]
I have only there mods installed:
![mods](https://user-images.githubusercontent.com/7690763/73600318-c306f480-454e-11ea-9ce1-e63a7de0da4a.png)

What is Mode2? Is it self combine unloading (by tractor with trailer)? I noticed that game freezes after a few seconds after enabling this mode. This tutorial is for FS17, byt I've done the same in FS19:
https://youtu.be/ZRlKFb41HkE

**Comment by Merrlin** [comment]
Mode 2 ist an Unloader for the Combine that drives a Course from Field to Target (silo, bunker, selltrigger, etc.). It's the second Mode Icon from the left.
If you want to self unload the Combine you just have to enable the function in the advanced settings (of the Combine). No unload cours for the trailer needed. And you have to put a Trailer beside the field. The field must be on the right side of the trailer. Courseplay does the rest of the magic.
