### ISSUE TITLE
Reversing into bunker 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#4880]
Hello can you confirm wether in the new versions that the tractor will reverse in to silage pits now I got a bit put off that I would set a course reverse tractor only in to the bunker and save but it would got the front of the bunker and unload annoyingly

**Comment by Tensuko** [comment]
Just record the reverse course till the end of the Bunker and back out.
I didn't even set an unload point last time and it worked.

**Comment by matty2123** [comment]
Shall try and report

**Comment by Tensuko** [comment]
Closed due to inactivity.
Should work as I said.
