### ISSUE TITLE
Suggestion: Changing unload trigger speed from Turn to Reverse Speed

### ISSUE THREAD

**Issue by Elite82pt** [Courseplay/courseplay#4882]
Some unloading triggers are quite small in some maps...so i would suggest changing the trigger speed from turning to reversing speed, avoiding missing it. Since reversing speed is much slower and not used as often in combine mode as turn speed.

**Comment by Tensuko** [comment]
So it means when you turn down the tuning speed, it will also lower the trigger speed ?
Did you try that and does it work ?

**Comment by Elite82pt** [comment]
Yes does exacly that And yes I did try! First i tried to reduce the speed near the trigger with the Course Editor to 2kph and with that I noticed that inside the trigger space the tractor would keep a steady 10kph. The same as turn speed. When I lowered it to 4kph the trigger speed also lowered to 4kph

**Comment by Tensuko** [comment]
Not going to trick arround with speeds, we have the plan to rework the speeds but last test didn't went well so not going to touch it for now.
