### ISSUE TITLE
Error: Running LUA method 'update' - AIVehicleUtil.lua(305) : attempt to call method 'getAIToolReverserDirectionNode' (a nil value)

### ISSUE THREAD

**Issue by franky135** [Courseplay/courseplay#4883]
Hello!
since i updated to new version yesterday its impossible to play. im playing the Nordfriesische Marsch and almost just mods.
i have 2 tractors seeding, 2 combines harvesting and 2 tractors driving home the squarebales i made plus 1 at ploughing. all with courseplay at same time while i bring away the crop and stack bales by telehandler.
But now i not even can start all vehicles before the game freeze. when i drive manual with courseplay menu open suddenly i freeze and the tractor drives away alone. before i had version 359 and all was working plus a tractor baling squarebales, but in 359 i had the issue that the ai drivers didnt unload the grain - but thats not important here.
Here is my log:
[log.txt](https://github.com/Courseplay/courseplay/files/4144248/log.txt)

Hope you can help me to solve the problem.
thanks

Frank

**Comment by Tensuko** [comment]
What exactly did you do when this Error came up ?

2020-02-02 14:31 Error: Running LUA method 'update'.
2020-02-02 14:31 dataS/scripts/vehicles/ai/AIVehicleUtil.lua(305) : attempt to call method 'getAIToolReverserDirectionNode' (a nil value)

**Comment by franky135** [comment]
after loading my savegame i jump from tractor to tractor to make them start their work. generate the fieldcourse for field 14 and start sowing, start the next tractor to drive to field 3 and collect bales, drive manual the tipper to the combine on field 13, generate the course for 2 combines on field 13 and start the first, open pipe at second because is full and after i copy the course from first combine and start it too, generate course for the plough on field 16 and start, start the second tractor to collect bales on field 3, drive a tractor manual to te right place on field 1 to generate a course and bring him to where he stopped and start sowing, jump to the telehandler to stack bales in the big building on farm. but game freeze when i drive a tractor manual with open cp menu or when i drive telehandler.
im using
FS19_JohnDeere6R (Version: 1.0) with FS19_lemkenVarioPackFEP and  FS19_lemkenSaphir8
FS19_JohnDeere7030v2 with FS19_balesAutoload (Version: 1.3.0.0)
FS19_MasseyFerguson7700S (Version: 1.2.0.0) with 2x FS19_rudolphDK280W (Version: 1.0.0.2)
2x FBM19_Maehdrescher_Set (Version: 1.0.0.0)
FS19_JD6030P_Series (Version: 1.0.0.0) with FS19_saphirGE601 (Version: 1.0.0.0)
FS19_MF_3000 (Version: 1.0.0.0) with FS19_balesAutoload (Version: 1.3.0.0)
FBM19_Fendt_Favorit_S (Version: 1.0.0.1) with original Rabe Kreiselegge and Amazone Sowmachine
original MF telehandler with FS19_BaleSpike (Version: 1.0.0.0)

i know i have alot of mods in my folder (thanks to my 7 years old nephew who really needs everything) so if you probably see mods there which you know in making issues please just tell me and i will sort them out and try again

**Comment by franky135** [comment]
i dont want to bother but is there anything else you need?

**Comment by franky135** [comment]
hello! i updated today to cp379 and deleted almost 20 mods out of my folder. than i started the game like always, generated the course for sowing and let start the tractor, jumped to the next to start collecting bales, drove the third out of the way, generated the course for 2 combines, started the first, copied the course into the other and started it too. after i couldnt jump to next vehicle anymore or drive manual. the onle possible to do was to do things with mouse in cp menu. had to quit the game again by taskmanager...
new log is attached
[log.txt](https://github.com/Courseplay/courseplay/files/4174920/log.txt)

**Comment by franky135** [comment]
its me again!
yesterday evening i tried alot and guess i found the problem. theres an autoloadtrailer i used to collect bales which doesnt work on the new courseplay. on older versions like 359 it was working.
I attach the trailer here for the case you want to check...
[FS19_balesAutoload.zip](https://github.com/Courseplay/courseplay/files/4176904/FS19_balesAutoload.zip)

**Comment by Tensuko** [comment]
Try it with newest Version, other way about the AutoLoad Trailers, where do you have it from and what Script does it use and so on.
We don't want to make single Mod Support, then we would only work in implement everyones Script and that we don't want to do...

**Comment by franky135** [comment]
I deleted the trailer and use new version and it works plus i did like i got told few posts earlier when making new courses. like this most things work fine and its really fun to play like this.

Thanks for help. i will close now.
