### ISSUE TITLE
Silage verdichten

### ISSUE THREAD

**Issue by xerion8300** [Courseplay/courseplay#4884]
Wenn ich mein Silo verdichten möchte fährt er die Erste Bahn komplett durch Silo und wieder zurück, danach fährt er wieder rückwärts in Silo aber dreht sich nur noch im Kreis.
Was mach ich falsch oder geht nicht.

**Comment by Tensuko** [comment]
Und wie sieht dein Kurs aus ?
Traktor Rückwärts vors Silo stellen, gerade aus zu einer sicheren Position fahren und Wartepunkt setzen, auf rückwärts schalten, bis vor den Startpunkt fahren, Kurs aufzeichnen stoppen.

**Comment by xerion8300** [comment]
Hier mal ein Link
[https://youtu.be/7r6FZHaUPQA ](url)

**Comment by xerion8300** [comment]
[https://youtu.be/7r6FZHaUPQA ](url)

**Comment by xerion8300** [comment]
[https://www.youtube.com/watch?v=7r6FZHaUPQA&feature=youtu.be](url)

**Comment by Tensuko** [comment]
Startpunkt mal weiter weg setzen.
Das silo ist VIEL zu breit und damit der Winkel zu groß um die Seiten richtig zu erwischen.

**Comment by xerion8300** [comment]
Ok danke werde es mal mit einem schmäleren Silo versuchen.
Melde mich ende der Woche.
Danke für die schnelle Hilfe

**Comment by xerion8300** [comment]
Habe jetzt den Startpunkt weiter nach außen gesetzt, jetzt geht es,
