### ISSUE TITLE
courseplay makes autosave not work

### ISSUE THREAD

**Issue by d86592** [Courseplay/courseplay#4885]
when I save in any way, it is stuck with the saving screen for ever! I have mods that need this to work so I need this.

**Comment by Tensuko** [comment]
And we always need a logfile attatched.
We need this realy!

**Comment by Tensuko** [comment]
Closed due to incativity.
One more Issue like that and I will directly close it untill we get a proper discription with a logfile... 
https://github.com/Courseplay/courseplay/wiki
