### ISSUE TITLE
When truck goes to unload combine it loops infinitely

### ISSUE THREAD

**Issue by y2177** [Courseplay/courseplay#4886]
So when the trailer that's supposed to unload the combine has gone up to it and is right about to receive the potatoes from it, it switches to "Drive behind Combine" and then makes a circle to go behind it, and then it switches to "Drive to Combine" and then right before it completes this and unloads it, it switches back to "Drive behind Combine". I'm not sure how to get it to successfully carry out Drive To Combine/Unload all the way through instead of it switching to drive behind combine right before it unloads. It does this forever unless I stop driver and I tried to make a new transportation/combine course for it but I still have the same issue unfortunately.

**Comment by Tensuko** [comment]
See #3311 #4286 
Closed.
