### ISSUE TITLE
CP & AD Automatisch Diesel Tanken

### ISSUE THREAD

**Issue by DerBauer2** [Courseplay/courseplay#4889]
Hallo, Ich weis das AD & CP selber Diesel nach Tanken können aber können sie das auch zusammen? Wie man sieht  is der Case fast leer und ich ich würde gerne wissen merkt CP das der Tank leer wird und kann er AD sagen das er bitte Tanken fahren soll oder ist das noch nicht möglich und man muss dies noch selber tun?

![20200203103116_1](https://user-images.githubusercontent.com/60297613/73641567-7f0c1080-4670-11ea-8fad-2cccb06a8ddc.jpg)

**Comment by Tensuko** [comment]
Weis ich nicht, kann sein das man dafür auch eine Schnittstelle braucht.
Auf jeden Fall muss in AD dafür ja eine Tankstelle eingetragen sein, sonst weis eine Saatmaschine z.B. nicht, ob sie Tanken fahren soll oder Saatgut auffüllen.

**Comment by Mannie313** [comment]
sprittanken geht bei AD wen er einen bestimmten wert unterschreitet.

MFG Mannie313

**Comment by Tensuko** [comment]
Dann muss CP eine Schnuttstelle bekommen, das wenn CP diese Schwelle Erreicht, dass er an AD übergibt.

**Comment by jala15** [comment]
In fact, just calling AD to refill seeds or fert makes AD automatically drive to a fuel station if low fuel (15%) when there is any saved target next to a fuel trigger, and then AD continues with its previous task

**Comment by KCHARRO** [comment]
It is a good idea, to have it also refill with fuel, but an on / off selector should be made in the interface to deactivate it in the harvesters, or simply that it does not work in these.

Imagine that Lexion or AGCO decide to refill fuel in the middle of a job?

**Comment by DerBauer2** [comment]
Na wie man sieht ist ja ein Punkt vergeben worden wo er tanken könnte nur kann CP an AD übergeben wenn er leer ist

**Comment by DerBauer2** [comment]
> In fact, just calling AD to refill seeds or fert makes AD automatically drive to a fuel station if low fuel (15%) when there is any saved target next to a fuel trigger, and then AD continues with its previous task (going to the silo to refill and back to field)

Well, does he do it when he has reached 15% or not?

**Comment by jala15** [comment]
> Well, does he do it when he has reached 15% or not?

Yes, AutoDrive does it, but Courseplay doesn't.


> ![20200203103116_1](https://user-images.githubusercontent.com/60297613/73641567-7f0c1080-4670-11ea-8fad-2cccb06a8ddc.jpg)

If you were using a seeder, when empty , CP would call AD, and then AD refills your seeder and your fuel tank. No need to set loading point as fuel station and fuel to load but your seed silo and seeds as fruit. 
Furthermore, as you are not using a fillable tool, AD should only drive to refuel and back to field, but to do so it first needs to be called from CP because of low fuel, but this isn't implemented yet

**Comment by DerBauer2** [comment]
@jala15 I already knew that but then you could add this? Would be a good idea

**Comment by jala15** [comment]
> @jala15 I already knew that but then you could add this? Would be a good idea

Pull request created on both mods. Hope they get accepted soon.
Backward compatible.

**Comment by DerBauer2** [comment]
But AD is currently no longer being developed? how can the Upade then function '?

**Comment by Tensuko** [comment]
Becouse AD is still being devloped as ppl make pull request just like @jala15 did...

**Comment by DerBauer2** [comment]
Stefan said that he doesn't feel like LS at the moment and AD is not being developed further?

**Comment by jala15** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/issues/273
>And if anyone wishes to add to those features, I am happy to merge pull requests and zip new release files.

@Stephan-S and @TyKonKet can merge pull request made by others, and I hope they don´t take too long to merge it, but if you are in a hurry you can download it from my forked repository (I would just wait for it to be officially merged)

**Comment by DerBauer2** [comment]
That may be but I am also active on his site and there has been nothing to hear from him for over a month and his statement was that he is currently not interested in FS
it was in his issue

**Comment by jala15** [comment]
Just for general info: AD has just been updated, automatic fuel refueling when fuel level below 15% and setting to unload/refill whith AD is active (or unload/refill + parking) should be working fine since AD v1.0.7.0-37.
I guess this can be closed

**Comment by DerBauer2** [comment]
Thank you @jala15
