### ISSUE TITLE
trying to use mex 5 with trailer on tractor

### ISSUE THREAD

**Issue by lonjon03** [Courseplay/courseplay#4890]
[log.txt](https://github.com/Courseplay/courseplay/files/4148369/log.txt)
trying to use mex 5 with trailer on tractor but when i generate a course on my field and start the driver the whole game framedrops and crashes, i am running the latest version. The camera stops following and the tractor just drives completely wrong. I have turned down the graphics to low, playing normaly at very high. 

![2020-02-03 (5)](https://user-images.githubusercontent.com/60608186/73653487-8d1a5b00-4689-11ea-8085-64034d83a2c0.png)
![2020-02-03 (1)](https://user-images.githubusercontent.com/60608186/73653499-90154b80-4689-11ea-99df-77f6c2c574f9.png)
![2020-02-03 (2)](https://user-images.githubusercontent.com/60608186/73653504-93a8d280-4689-11ea-9a2d-54e072d68696.png)
![2020-02-03 (3)](https://user-images.githubusercontent.com/60608186/73653509-95729600-4689-11ea-931b-f224f20b8c63.png)
![2020-02-03 (4)](https://user-images.githubusercontent.com/60608186/73653511-96a3c300-4689-11ea-989a-c4207ce4d417.png)

**Comment by Merrlin** [comment]
Please add Logfile as described in
https://github.com/Courseplay/courseplay/wiki

**Comment by lonjon03** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4148283/log.txt)

**Comment by Tensuko** [comment]
No Error in the log.
You have to post the logfile when the Error happened to we can see the Error msg.
Start game, start driver, error happens, post the log.
