### ISSUE TITLE
Mist laden mit Front oder Radlader, Fahrer stoppt nach X Durchgängen

### ISSUE THREAD

**Issue by RK54** [Courseplay/courseplay#4891]
Hallo Tensuko,
habe die CP Version 6.01.00378.
Die beiden Kurse, laden und abfahren, wurden nach Deinen Vorschlägen eingefahren.
Klappt auch einwandfrei, bis dem Lader es zu arg stinkt, dann verweiugert er den Dienst.
Egal ob mit Rad oder Frontlader, geht ein paar mal, dann Ende

Gruß RK54
[log.txt](https://github.com/Courseplay/courseplay/files/4149129/log.txt)

**Comment by Tensuko** [comment]
Magst du mir noch mal ein Screenshot vom Kurs schicken ? Was macht er denn, dass es nicht mehr funktioniert ?

**Comment by RK54** [comment]
hier einmal mit Radlader und einmal mit Frontlader.
Sie fahren beide den Kurs ab, sogar mehrmals, auf einmal bleiben sie mit voller Schaufel vor dem Auflieger stehnen, Arbeitsverweigerung
![1](https://user-images.githubusercontent.com/54204656/73679072-fb771180-46b9-11ea-96fc-98cdf5898278.png)
![2](https://user-images.githubusercontent.com/54204656/73679081-00d45c00-46ba-11ea-838f-a90c4f724859.jpg)

**Comment by Tensuko** [comment]
Ach verdammt... Dabei sieht das so gut aus... Muss ich mir mal nen Testkurs basteln und in dauerschleife laufen lassen und gucken was das ist....
Danke für die Meldung.

**Comment by RK54** [comment]
musst nur dran denken,
benötigst 2 Kurse,
einen für Radlader und einen für Frontlader.
Ich habe erst die Kurse eingefahren,
danach den Abfahrer Kurs etwas in den Wartepunkt gestellt, beladen am Startpunkt.
Habe mich schon gefreut dass es so jetzt funktioniert, dann das

**Comment by Merrlin** [comment]
Das gleiche oder ähnliche Problem ist mir auch schon untergekommen.
Mein Radlader befüllt fleißig die BGA und irgendwann nach 20, 30, 40 Durchläufen macht er dann Blödsinn... Entweder er verstreut Silage oder die Schaufel fährt die Position falsch an oder er wartet trotz leeren Vermenter auf Platz.
Aber es ist weder reproduzierbar noch wird im Logchannel 10 was sinnvolles angezeigt.
