### ISSUE TITLE
Course play 6 crash

### ISSUE THREAD

**Issue by mikeski97** [Courseplay/courseplay#4892]
I started playing Davenport and using courseplay 6. I'm 15 hours into the map. Everything was working fine until I changed the route for my combi for fields 14 & 15. I combined these fields together. But now once I start to run route. Once I hit the tab key, it freezes up or the camera stays still and my tractor goes on his own and basically have to restart the game again. I've tried loading it multiple times and it just doesn't again. Do I need to reinstall courseplay or what's a quick fix?

**Comment by mikeski97** [comment]
It's Ravenport

**Comment by Tensuko** [comment]
Create the Error and then drag and drop the log.txt into comment box.
Else I cant rly say whats up.
Also a Screenshot of the Course, Vehicle and Tool would be nice as well as what Mode you used.

**Comment by iljarogoff** [comment]
Looks like a mode2 issue?

**Comment by Tensuko** [comment]
Closed due to inactivity.
