### ISSUE TITLE
Adapter lua Fehler

### ISSUE THREAD

**Issue by s1100** [Courseplay/courseplay#4893]
Hallo!
Ich bekomme diesen lua Fehler beim verwenden des Adapters mit der Sämachine Horsch Serto, habe auch die Väderstad Einzelkorn probiert, immer das gleiche. Was müsste ich beim Adapter verändern das es funktionieren würde, oder liegt es an CP?
2020-02-03 21:53 Error: Running LUA method 'mouseEvent'.
2020-02-03 21:53 C:/Users/reini/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/vehicles.lua:897: attempt to index field 'attacherJoint' (a nil value)

Adapter ist dieser: https://farming-simulator.com/mod.php?lang=de&country=de&mod_id=146352&title=fs2019

**Comment by Merrlin** [comment]
Bitte poste deine Log wie hier beschrieben:
https://github.com/Courseplay/courseplay/wiki

**Comment by s1100** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4150271/log.txt)

**Comment by Tensuko** [comment]
Duplicate of #4741
Closed.
