### ISSUE TITLE
Widescreen Scaling issue for Course Preview

### ISSUE THREAD

**Issue by uded** [Courseplay/courseplay#4894]
FS19 latest, CP v6.01.00378, the map is Saxony v2.3, independent of the vehicle and/or implement. Resolution 2560x1080. Happens in 1920x1080, but less common (1 out of 8-10 with lower res, 8-9 out of 10 with higher res).

When both plotting a new course or showing a course the lines will greatly exceed the field. Mapping the field boundaries work correctly and the actual course is plotted correctly, just the map goes crazy on me.
![fsScreen_2020_02_01_20_23_30](https://user-images.githubusercontent.com/218623/73752346-19e41800-4761-11ea-9533-6375df6e4e97.png)
![fsScreen_2020_02_02_14_57_23](https://user-images.githubusercontent.com/218623/73752360-1fd9f900-4761-11ea-92a9-c8f4a835ed01.png)
![2020-02-04](https://user-images.githubusercontent.com/218623/73752371-28caca80-4761-11ea-9d09-25718be62a99.png)

In some fields, the line will go out just a bit of the right course. But still, there is some misdraw there:
![2020-02-04 (1)](https://user-images.githubusercontent.com/218623/73752405-38e2aa00-4761-11ea-96c2-7d15a0472d2c.png)
![2020-02-04 (2)](https://user-images.githubusercontent.com/218623/73770582-e9aa7280-477c-11ea-820b-b52c838e0876.png)

I do hope it's not a duplicate - searched but couldn't find a similar report...

**Comment by pvaiko** [comment]
If you can provide a clean link (no registration, no fake download buttons, etc.) to download this map I can look into it.

**Comment by uded** [comment]
I am not sure if I am allowed to, I can only provide this link privately - via Google Drive or something like that...

**Comment by uded** [comment]
@pvaiko I've sent you an email with private links to download all necessary files.

**Comment by pvaiko** [comment]
Can't reproduce this with 2560x1440.

**Comment by Tensuko** [comment]
Not sure if this map is out yet. But does your other testers have the same Issue ?

**Comment by uded** [comment]
It's still happening on my screen, but the resolution is higher than the mentioned by @pvaiko. Also, the last couple of versions _seems_ to make it a less of an issue, happened only once in six course generations.

**Comment by Tensuko** [comment]
Happens only on special zoom levels.
Case is to rare, won't change anything here, sry.

**Comment by uded** [comment]
Yeah, I know. Sometimes it does happen, sometimes it doesn't. And only on ultra wide screens...
