### ISSUE TITLE
Game freezing with Courseplay installed

### ISSUE THREAD

**Issue by roninla** [Courseplay/courseplay#4895]
Game freezes with courseplay installed. Its happened multiple times, and courseplay seems to be the common mod  between each time. 
[log.txt](https://github.com/Courseplay/courseplay/files/4156346/log.txt)

**Comment by Terp88** [comment]
I am having a similar issue. Not sure if you can get off of the loading screen, but I cannot. Used to work fine and one day it stopped. (Same log file, two different ways)
[log.txt](https://github.com/Courseplay/courseplay/files/4156802/log.txt)

[log.txt](https://gist.github.com/Terp88/19f2b23d7b7f718e44be5dd3ef6cdd6c)

**Comment by Tensuko** [comment]
@roninla 
Load mod: courseplay (Version: 6.01.00364) (Hash: 80f34e4bfa949bace6fef0234d641433)
update to newest version only from here: https://github.com/Courseplay/courseplay/releases

@Terp88 
Load mod: courseplay (Version: 6.01.00360) (Hash: ae9dd8846054cae2c5f127962e396088)
Load mod: courseplay (Version: 6.01.00360) (Hash: ae9dd8846054cae2c5f127962e396088)

you log is so damn messie, also got several Mod Erros, clean tem up 1st.
2020-02-04 18:57 Error: Running LUA method 'update'.
2020-02-04 18:57 dataS/scripts/misc/GroundTypeManager.lua(123) : attempt to index a nil value
This Error comes from GIANTS but not a Surprize with so many Errors.

And general Info in case you didn't know: Only one Map in Mods Folder! (haven't check this messie log for more maps...)

**Comment by roninla** [comment]
Ok. I’ll download the latest version, and only grab it from here. If I run into the same issue I will add the new log file to this issue tracker so as not to clutter things up.

**Comment by Terp88** [comment]
We were able to get courseplay to work again. After looking at the log, we took out my dataS file and put one from a different game in and the game did not accept it. We then put my dataS file back in and that fixed my issue.

**Comment by Tensuko** [comment]
I take this as fixed.
If there is still a Problem (wich I doubt) make new Issue

**Comment by JC268** [comment]
Hi Tensuko, I downloaded the latest version of CP and every time I click on start my PC will completely freeze. Please assist!

The version I uploaded was the one you posted on this chat.

**Comment by Tensuko** [comment]
Logfile ?
And for freeze when start...
more details on what you did, what vehicle, tool, mode and so on....

**Comment by JC268** [comment]
Any vehicle that I try will freeze the game. I just downloaded the mod, unzipped the folder like I normally would. I use winzar to unzip for all zipped folders.  I unzip all my mods so all of them are in their own folder.

So basically, I'll start the game, select a vehicle, select a course and when I say start course the vehicle will drive a meter and then the game will freeze.
