### ISSUE TITLE
Frage zum besseren Bodenbearbeitung?

### ISSUE THREAD

**Issue by DerBauer2** [Courseplay/courseplay#4896]
Hallo,
Wie kann ich CP besser einstellen das solche Stücken nicht mehr übrig bleiben?
Früher ist ja CP noch richtig in die ecken gefahren. Is das vlt eine bessere einstellungfrage?
Ich hatte es auch schon mit Scharfe kanten Probiert aber da fähert er einfach rum anstatt die wendung zu machen.

![20200205171426_1](https://user-images.githubusercontent.com/60297613/73860303-a5ca7280-483b-11ea-83cf-0d883b79b5b0.jpg)
![20200205171733_1](https://user-images.githubusercontent.com/60297613/73860301-a531dc00-483b-11ea-8aae-a8ee28144723.jpg)

**Comment by Tensuko** [comment]
Advanced Settings, use Pathfinding, experimentieren mit AI Driver (funtzt bisher nur beim Drescher gut) und den Kursgenerator richtig einstellen.

**Comment by DerBauer2** [comment]
In wie fern richtg einstellen?

**Comment by Tensuko** [comment]
Im ersten Bild mehr Vorgewende für mehr Platz.
Im zweiten Bild, das Feld hat keine 90° Ecke, somit wird das automatisch Runde, entweder Feld Eckig machen oder Runder.

**Comment by DerBauer2** [comment]
Ich Probiere das mal danke 
macht CP jedes  mal ein Felderscan also die Umradung eines felders bei save laden oder nur am 1. Start?
Wenn nein wie kann ich ihn die felder neu berechnen lassen?
