### ISSUE TITLE
Courseplay Not Working

### ISSUE THREAD

**Issue by heath36** [Courseplay/courseplay#4898]
I have downloaded courseplay and it is showing in my downloaded mods inside the game but it does not show up in my mods/dlc selection list though. I've tried removing all the mods and trying different maps but it's still not showing up in the game.
Thanks!

**Comment by Merrlin** [comment]
Log please... Oracle is on vacation atm.
https://github.com/Courseplay/courseplay/wiki

**Comment by heath36** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4167386/log.txt)

**Comment by newsec** [comment]
Had the same issue. Restart the game.

**Comment by Merrlin** [comment]
First of all clean the mod folder. There are some mods with irregular mod nsmes. For example courseplay. Further only one Version from each Mod at the same time.
And the most important thing is: load courseplay only from the releases section.
https://github.com/Courseplay/courseplay/releases
Put the mod in your mod folder and name it to FS19_Courseplay.zip. no repacking needed.

**Comment by Tensuko** [comment]
Error: Invalid mod name 'zzz_courseplay6.zip'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

Error: Invalid mod name 'courseplay-master'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

2 times files from CP in Mods Folder.
As @Merrlin said, download an actual version from release side.

**Comment by Tensuko** [comment]
This is for sure not CP fault.
When you have the actual release Version, all should be fine and keep your mods Folder clean.

Closed.
