### ISSUE TITLE
CP "verbauen"?

### ISSUE THREAD

**Issue by f4mous96** [Courseplay/courseplay#4899]
Hallo,

ich habe einen LKW, bei dem CP anscheinend nicht verbaut ist.
Wenn ich die rechte Maustase klicke passiert nichts, bei andern öffnet sich CP ganz normal.

Wo muss ich das nachtragen?

Es handelt sich um folgenden Mod:
https://www.modhoster.de/mods/man-tgx-tankwagen

**Comment by Tensuko** [comment]
Als aller erstes würde ich es bevorzugen, wenn man die Mod vom original Link her lädt ( https://farming-simulator.com/mod.php?lang=de&country=de&mod_id=128105&title=fs2019 ) und nicht von Schrotthoster.
Was CP und alle anderen Mods wie AD und FollowMe brauchen ist die GIANTS AI Funktion für das Fahrzeug.
In diesem z.B. wurde das nachträglich eingebaut: https://farming-simulator.com/mod.php?lang=de&country=de&mod_id=123383&title=fs2019

**Comment by f4mous96** [comment]
Ok mein Fehler, da hatte ich den Tankaufbau nicht sofort gefunden und daher den Modhoster link genommen. Ich bin mir sicher ich habe ihn auch daher (habe ihn aber nochmal vom Modhub runtergeladen).

Auf was muss ich da schauen wegen der Giants AI Funktion? Oder nach was muss ich suchen?

**Comment by Tensuko** [comment]
Das kann ich nicht genau sagen, da müsstest du dich mal in Foren umschauen.
Ich weis nur, dass wenn der GIANTS Helfer nicht geht, CP und AD etc auch nicht gehen.

**Comment by f4mous96** [comment]
ok dann schau ich mal im Forum nach.
Danke für die Hilfe!

**Comment by f4mous96** [comment]
So CP funktioniert, allerdings zeigt es nur die Icons "Überführung" und "Bunkersilo befüllen und verdichten" an. 
Ich möchte diesen LKW aber dazu nutzen dass er Gülle abholen soll beim Stall und diese in ein Zwischenlager transportieren soll.

**Comment by Tensuko** [comment]
Dafür muss auch Gülle eingetragen sein bzw die gleichen funktionen haben wie ein Gülletriler

**Comment by f4mous96** [comment]
Gülle ist (so wie auch Milch, Wasser, Kraftstoff etc) eingetragen. Hab ihn auch einmal voll entladen, aber dann versucht am Lager zu entladen, klappt aber nicht. Muss da wohl der unloadingtrigger fehlen oder?

**Comment by Tensuko** [comment]
Da bin ich ehrlich gesagt etwas überfragt.
CP checkt sozusagen eingetragene Eigenschaften der Fahrzeuge und Tools.
Mode4 z.B wird erst aktiv bei z.B. einer Saatmaschine. Da ich selbst nicht Modde musst du da selber mal schauen, sry.

**Comment by f4mous96** [comment]
Aber die Eigenschaften die z.B. Mode1 (Abfahrer - Beladen am Startpunkt) sind bei dem LKW doch vorhanden oder?

**Comment by f4mous96** [comment]
Ich machs mal zu, habe mich nun für einen IT Pack entschieden.
