### ISSUE TITLE
CP Driver is not unfolding any sprayers (Multiplayer)

### ISSUE THREAD

**Issue by Walawalawala** [Courseplay/courseplay#4900]
I have tried the vehicles and the implements with no luck. I think I got everything needed here: https://pastebin.com/ZSZzc8WU

**Comment by Walawalawala** [comment]
Also want to throw in that everything else is working fine. Seeders, cultivators, etc. Just sprayers. I have tried every sprayer except the ones that have the aux tank. If you need me to supply any more information I can. This is my first time using CP and it is insane!

**Comment by Walawalawala** [comment]
One more update. I had to put lime on a field. I am using the largest in-game spreader. The AI isn't unfolding the sprayer but it is doing to max width and running. I think this may be a visual bug as the pipe on my combine isn't coming out either put it has collision. 

Hope this helps!
![20200208104152_1](https://user-images.githubusercontent.com/20787708/74088091-6e88db00-4a60-11ea-9ea7-83ecaf750af2.jpg)

**Comment by bumbalaga** [comment]
Combine pipes were fixed in the newest release

**Comment by Tensuko** [comment]
Collecting all in #5484
