### ISSUE TITLE
RMB rebind not working

### ISSUE THREAD

**Issue by Tempuser8734** [Courseplay/courseplay#4901]
I have rebinded the RMB from courseplay to MMB but only RMB works. It forces me to disable mouse activation every time I need to use crane or similar complicated appliance.

**Comment by Tensuko** [comment]
This one cant rebind.
What I do with cranes is change open hud to ctrl+del in the cp hud under settings.

**Comment by Tempuser8734** [comment]
> This one cant rebind.
> What I do with cranes is change open hud to ctrl+del in the cp hud under settings.

This is what I am doing right now. But due to right hand being quite busy with mouse and steering wheel I have rebind it to ctrl+tilde to allow one hand operation. 
I have to check something ;D Maybe I can rebind this one to MMB and it will work fine!

**Comment by Tensuko** [comment]
As I said in some Issues, we have a bit Problems with Keybinds.
When you use the Vehicle by yourself you won't have to open the HUD so often.
Why not change to ctrl+del while use crane or stuff like that.
At least I would do that for a workarround.

**Comment by Tensuko** [comment]
- RMB to open is fixed keybind and can't be rebound
- We have a general problem with keybinds
- Workarround: change the open HUD in HUD Settings to ctrl+del for this Vehicle while use the Axes.
