### ISSUE TITLE
Changes made while vehicle in CP are not saving to the server.

### ISSUE THREAD

**Issue by CyberGriff** [Courseplay/courseplay#4903]
This is all happening on my dedi server at Gportal. 
Ok, so this is a strange one, when trying to setup a combine on a simple fieldwork course, i hit start course and the harvester drives to start of course, activates equipment and starts harvesting. HOWEVER, the harvester does NOT actually gain any fruit, it drives on deleting the crop texture but not actually harvesting any thing. 
Now, if i then disable CP driving, and use the AI helper, it instantly begins ACTUALLY harvesting, and the previous deleted crops all spring back, as if they haven't been drove over.

I had it working yesterday and now something has gone wrong, i've re-installed CP onto the server and my client, even deleted folders on server and put them back in and started a new save, loaded it, saved it and then reset server. Still no joy, is this a bug? or am i doing something wrong?

**Comment by CyberGriff** [comment]
This is MP related btw. Don't have the problem in single player.

**Comment by Tensuko** [comment]
Collecting all in #5484
