### ISSUE TITLE
Validity check failed in TransformGroup_setScale, setTranslation, localToWorld

### ISSUE THREAD

**Issue by zsoltbranduse** [Courseplay/courseplay#4906]
CP spams the server log file with this fails and it became 2Gb before the server crash and have to restart but its not froze for everyone. Sometimes just the frozen player have to disconnect through alt+f4 but he won't be able to join until restart.

I can't upload the log because it too large but here is a few lines

[log.txt](https://github.com/Courseplay/courseplay/files/4175471/log.txt)

Can you tell me which mod cause this issue and which one i should remove (not CP obviously)

Thank you in advance

**Comment by pvaiko** [comment]
There are some error messages from Courseplay, but the one you are complaninig about is not even from CP. No idea which mod is causing this, try removing them to figure out, sorry.
