### ISSUE TITLE
Not reversing when plowing

### ISSUE THREAD

**Issue by Iver88** [Courseplay/courseplay#4908]
When I use Ford 1300 DT and most cheapest plow from vanilla game, turn ratio is calculated as 12m automatically. When plowing, tractor is not reversing so doing 12m big circles and ramming into trees and other static.

**Comment by Tensuko** [comment]
Turn of Field is active ?

**Comment by Iver88** [comment]
> Turn of Field is active ?

Yes, it is. Both combine and tractor.

**Comment by Iver88** [comment]
https://youtu.be/Gdqt1v1Pyd8

**Comment by Tensuko** [comment]
What about Advanced Settings ?
Ai Turn, Pathfinding, etc. ?

**Comment by ThorstenHouy** [comment]
Same here. It doesn't matter which machine i use or which workmode. Work with "Turn on Field" always ends up with machine driving outside the field and so fort into trees or other objects. My harvester, forage harvester and even the tractor turning outside the field which is especially bad while playing Modded Maps which have nearly no distance from the field to a fence at all. I can provide a video later if needed.

**Comment by Tensuko** [comment]
I want to know if you Advanced Settings are set.
Go to CP HUD in the Settings, there is a Line called Advanced Settings.
Do you have those active ?
I would try to deactivate them.
I have no Tool that runs outside of the Field, thats why I am so curious about your situation.

**Comment by Iver88** [comment]
I don't think turning off advanced settings does something. I tested it. But I'll provide video as proof in few hours.

**Comment by ThorstenHouy** [comment]
https://youtu.be/U664O5CHm7g

**Comment by Tensuko** [comment]
Video not available.

**Comment by ThorstenHouy** [comment]
Hmm strange. Changed it now from "not listed" to "private" and to "not listed" again. Should be available.

**Comment by Merrlin** [comment]
Now if I read this: I've observed some similar Issues both with towed and attached implements. Even with attached sprayer or fertilizer and 2 headlands the Tractor ran out of field. I thought it had to do with course Generation. Maybe it started with AiTurn on Field Option in Advanced settings.

**Comment by pvaiko** [comment]
@Tensuko the easiest way to find this out is ask for a log with channels 12 and 14, the log will clearly state the turn maneuver being executed.

@All: turn off the AI Turns options and it should work.

**Comment by Tensuko** [comment]
This plow can't be used in reverse. (Video)
It is also set in the XML of the tool afaik.

**Comment by caplink811** [comment]
Morning,
I like to admit, that this behaviour isn't gone with 00383, ots still the same in 00384, pls see videos, logs, and cp course for details, they are all attached. (map is felsbrunn, fertilize device is the 1st standard device from the shop, kuhn I assume)

[f30_fert_test_MapDE.zip](https://github.com/Courseplay/courseplay/files/4209647/f30_fert_test_MapDE.zip)
[f30_fert_test_starts_near_line_4954_log.txt](https://github.com/Courseplay/courseplay/files/4209648/f30_fert_test_starts_near_line_4954_log.txt)
Clip 1
https://1drv.ms/v/s!Aqt5msdvWb55hzZ8hFkSOVz-Ya08?e=7VbObM
Clip 2
https://1drv.ms/v/s!Aqt5msdvWb55hzfav08PjAaDvNLK?e=aPzJ3m

**Comment by pvaiko** [comment]
@caplink811 sorry for the confusion, the above message is about a commit on a bugfix branch (peter), the fix isn't on master yet, no release contains that fix yet, I'll make sure next time the commit message clearly states it.

**Comment by Tensuko** [comment]
Should be fixed now.
Can you pls try with V385 and confirm this for your situations ?

**Comment by caplink811** [comment]
Hi,
With .385 tractor and trailed plow work as expected (wide turn on field, 
and then moving back and forward to go back on track).
So from my point of view, its ok to close the ticket.
--
Ciao Jörg


*** send from a mobile device ***

**Comment by Tensuko** [comment]
Thx for reply.

Closed.
