### ISSUE TITLE
Tractor and combine crash

### ISSUE THREAD

**Issue by Iver88** [Courseplay/courseplay#4909]
Small trailer, combine set to stop when full: when combine is full and reversing into field (doing free space outside fruit), combine unloads crop, tractor turn right, combine turns left and vehicles crash itself. Or just stays on place and both vehicles are waiting for each other's action.

Small trailer, combine set to continue work when unloading: both vehicles stops at end of the field, tractor wants to right, combine to left. Same case as above. They are waiting for each other.

**Comment by Tensuko** [comment]
See #3311 and #4286 
Closed.
