### ISSUE TITLE
Description for Mode10, blocking issue of tractor in the field

### ISSUE THREAD

**Issue by wwaayynn33** [Courseplay/courseplay#4910]
Can you please update the description how to set up the mode correctly? The way how its shown in LS17 is definitely wrong. So how to do correctly?

Tractor looking to the right, rollers on the back, no reverse driving
Version #1
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
 EndOfStack00000000000Start0000000000000End000000000Turn
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Tractor starts compacting, drives to EndOfStack then lifts the implement and drives to Turn. Starts driving backwards, at End it lowers the implement.
Failures:
- Raises the implement at EndOfStack and drives to Turn, even when compacting is not finished
- Stops tractor with loader wagon in front of the stack while active
- Stops randomly tractor somewhere in the field(not in .294, only standard machines in use)
------------------------------------------------------------------------------------------
Version #2
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
 EndOfStack00000000000Start0000000000000End000000000Turn+Pause
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Failures:
- like above
- Tractor waits always at pause, should only wait there if a tractor wants to drive through the silo
------------------------------------------------------------------------------------------
Version #3
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
 EndOfStack00000000Start0000End000000000000000000Turn
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Failures:
- Doesn't work at all
------------------------------------------------------------------------------------------
Version #4
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
 EndOfStack00000000End0000Start0000000000000000000Turn
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Failures:
- Doesn't work at all

------------------------------------------------------------------------------------------

It would be also good to adjust the value x via the CP menu
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
000000000000000000000000|<---x--->|
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
because the tractor is pushing a lot of material with its wheels out of the stack(only rollers mounted, no shield)

Furthermore:
- When only compacting is chosen, you can the the speed while working, but it always shows "automatic". If you switch over to leveling and compacting you can then see the speed.
- Option to send the tractor to park position(What is this and where? Park? Turn?) when compacting level 100% is reached, so save fuel and hours.

**Comment by Tensuko** [comment]
It does.
Tracktor with shield in front of Silo.
Start the Courserecord, drive in a corner where you are save, add a waitpoint there, then switch to reverse and drive in front of the Silo (far enough when you got a wide Silo) and stop the Record there.

**Comment by suchna** [comment]
initial release tutorial is in the first comment here [here #4101 ](https://github.com/Courseplay/courseplay/issues/4101) 

Then you have to be as straight as possible. 

Also, when recording path it is important, to drive to the end of the line, hit "reverse button" drive about a meter back and hit "park button" after that, stop button after that. Stop button is the waipoint where tool goes down, but it dosont work without waitpoint and reverspoint

And Stop point has to bee 3 meters max from the start point - otherwise tractor does not recognise begining of silo and for me it looks like he works in basic travel mode and stops at park waypoint

**Comment by Tensuko** [comment]
Closed due to inactivity.

Start inside the Silo, drive to a save spot, set a Waitpoint, switch to reverse drive in front of the Silo and Stop the Course record.
