### ISSUE TITLE
Tip triggers issue in MP

### ISSUE THREAD

**Issue by Mateusarchangelo** [Courseplay/courseplay#4911]
For some reason, tip triggers in multiplayer dont seem to be working. SP is ok.
I made two courses, one which withdraw some oat from a silo and tried putting it back, and the same with a hay shack using straw.

In the log file at 2020-02-09 12:36 :58 you will find a 'trigger (149964) does not accept trailerFillType (31)', but It was during the straw and hay shack attempts, it should be accepted shouldnt it? And afterwards it just stops with that warning, but has the same 'capacity=0' as the silo.

earlier attempts were from oat and normal silo runs. Everything run with vanilla itens.

From my little understanding, its reading the silo capacity as 0?

Log file:
[log.txt](https://github.com/Courseplay/courseplay/files/4177113/log.txt)

**Comment by samvdb** [comment]
Can confirm this issue. All silo related actions are bugged.

**Comment by samvdb** [comment]
Got same issue in single player.

Log file attached.
[log.txt](https://github.com/Courseplay/courseplay/files/4182684/log.txt)

**Comment by Mateusarchangelo** [comment]
Strangely, I tried replicating it in single player, but everything worked. MP still no go

**Comment by gec100** [comment]
not sure if it is connected but also my trailers are not filling in MOD 1. 
MP dedicated server, vanilla MAN truck and Krampe trailer. Unloads fine at the selling point but just waits under the silo. (Lizard Extralarge multyfruit). If I fill it manually it will continue till nex refill.
what I also noticed is:
- does not open or close cover
- if the silo is emptied before trailer is full, the "continue" option does not work
- if i set the number of runs, the runs are not counted (probably cause i refill manually)
- reset current number of runs option does nothing
attached is my log

[log.zip](https://github.com/Courseplay/courseplay/files/4208379/log.zip)
