### ISSUE TITLE
What node does courseplay use to record a path

### ISSUE THREAD

**Issue by kylemeyer13** [Courseplay/courseplay#4912]
I dont know if this is the right place for this but i have looked all over and cant find a answer. i am working on a few trucks and i have ran into this issue. when i am recording a path the path records the the side of the truck. I just need to know what it is using to record the path.
![fsScreen_2020_02_09_10_23_18](https://user-images.githubusercontent.com/26012725/74106215-4f568000-4b2a-11ea-8d94-e950d0d5e2d2.png)

**Comment by Tensuko** [comment]
GIANTS Problem, see this:
![Nodes](https://user-images.githubusercontent.com/27344744/74107128-4fc43a80-4b6d-11ea-8b34-c98a2546630a.png)
I sent this to Lisertan, but no Updates on that one.
It is only on those 2 Trucks (In FS17 Version they was fine).
So I got no Idea on what they did.
You can show those yellow Dots with Debugchannel 12

**Comment by pvaiko** [comment]
getAIVehicleDirectionNode() if that exists and returns something, otherwise the root node.

**Comment by kylemeyer13** [comment]
hmmm i dont see a vehicle direction node and my root node looks to be in the right place ill look around see if i can get a vehicle direction node

**Comment by kylemeyer13** [comment]
do you know of any mods or in game vehicles that use a AIVehicleDirectionNode that i could look at to see what im doing wrong

> getAIVehicleDirectionNode() if that exists and returns something, otherwise the root node.

**Comment by pvaiko** [comment]
https://gdn.giants-software.com/search.php?search=getAIVehicleDirectionNode

**Comment by kylemeyer13** [comment]
Im sorry for bugging you guys but I have tore through the entire mod trying to gain a understanding for this. For some reason that node that shows up with debug channel 12 moves with a wheel reference node. The only place the index for that node is referenced in the xml is for the wheel reference point. Any ideas?

**Comment by pvaiko** [comment]
That's why I linked the Giants documentation, you may want to look at that. Looks like they use the rotCenterNode?

**Comment by CZEKenyCZE** [comment]
Has anyone figured out how to write the correct node??  Thanks
