### ISSUE TITLE
Ability to Skip Headlands

### ISSUE THREAD

**Issue by Smokingenius** [Courseplay/courseplay#4915]
This is an enhancement request for the current route generator. It be nice if you had the ability to set the route generator when set to headlands to skip the first headland. This would be useful on smaller maps with tight fields, as I have noticed some collision issues even when turning on field. Also, IRL, there is often a grass swath added to the edge of the field as an animal patch with feed grass, so they eat that rather than the crop. 

Regards.

**Comment by Tensuko** [comment]
I don't get what you want....
Use ingame Tool to make the Grassline you want, then the Field Definition will shrink and you can create the course as you want.
You can also start in the up/down part and then do the headland, that options are all there.

Headland 2-4, start with up/down, skip rows 2-3.
Should do it pretty good.

**Comment by Smokingenius** [comment]
Greetings Tensuko,

Doing the settings you describe does not seem to give the effect I am looking for. The suggestion I have, and I will use similar terms you have used, is to allow you to skip the first headland on planting, so you can plant grass there instead. 

Headland 2-4, starting with headland, skip 1-3 headlands (currently not available option). 

Regards.

**Comment by Tensuko** [comment]
Not going to do anything about this, just start in the row where you want to seed your fruit.
