### ISSUE TITLE
Suggestion: Create waypoints with fake camera or via map view

### ISSUE THREAD

**Issue by ThorstenHouy** [Courseplay/courseplay#4917]
It would be helpful to have a fake camera, which you can move very fast to create waypoints with just setting up a few and let them link together one after another so you get fast shape creation or via map view. 

You could have a vertical and horizontal tool with threshold to align waypoints along the x / z axis or if possible to select a few waypoints and align them on x / z. Also a tool or snap grid for the x / z axis to create perfect lines with it from the beginning. 

**Bonus:** Smoothing tool and an afterward sizing tool for the entire path. Moving the entire path only needs to recalculate the coordinates.

_**1:** Standard waypoint mode. User creates waypoints one after another, and they link themselves in order.
**2:** Smooth function does smooth the edges. Maybe have a value to control the angle amount.
**3:** Sizing function after the path is finished.
**4:** Grid with snapping in the first place or afterward to manipulate the points on the z / x axis._
![WaypointCreation](https://user-images.githubusercontent.com/25899448/74147806-489c3b80-4c04-11ea-956e-d2450814efac.png)

**Comment by Tensuko** [comment]
Don't think we will be able to do it that way, way to complicated.
You can kinda do it with this, but I am not sure about the distance between waypoints. https://github.com/Courseplay/courseplay/issues/4735

@pvaiko what do you say about this ?

**Comment by pvaiko** [comment]
What is the use case of this?

**Comment by ThorstenHouy** [comment]
Use case would be to create paths way faster and more exact without driving. The problem i myself have and some others iv'e seen on Youtube is, that the manually created paths are way too "unexact" and if for example a perfect rectangle shape is wanted. Path creation this way would be much easier i think.

Combined with the problem that Courseplay often drives out of fields even if the property is set you can't create a perfect smaller field or a completely new one. If the map coordinates are the same like the 3d camera world coordinates, it would be even possible to create perfect routes for streets or other stuff without the clunky driving especially with the mouse/keyboard combination.

**Comment by pvaiko** [comment]
You are aware of the in game Course Editor (#4735) by @russbeuker, right?

**Comment by ThorstenHouy** [comment]
Still needs pre driving a path. Just missed the link part I'm sorry. But it's very nice indeed. I wasn't aware of this thank you very much. Btw thanks for all of your efforts you put into this.

**Comment by Tensuko** [comment]
A Tool to kinda paint Course is not planed in any near future.

Closed.
