### ISSUE TITLE
Translation in French

### ISSUE THREAD

**Issue by polosubtil** [Courseplay/courseplay#4918]
Hi everyone,

Sorry to post that here but I can't find my way around thing on Github.
How can I suggest a new translation for French ? I already tried to submit a new file in the "translations" folder using the edit tool but it doesn't work when I save my changes

Thanks for your help, but mostly thank you very much for the work you do for us !!!!

**Comment by knoxville73** [comment]
@polosubtil, is it possible for you to discuss with me about the french translation ?  See my proposal in the attachment. 
[translation_fr.txt](https://github.com/Courseplay/courseplay/files/4182073/translation_fr.txt)

**Comment by polosubtil** [comment]
Hi @knoxville73,
Sure, no problem, I am having a look right now and I will let you know.
My main changes would be
- French spelling, there are some around
- In the combine mode, change "Chauffeur" with "Remorque", I think it makes more sens
- Rearrange some terms to something more farmy (For example : Bouts de champs => Fourrières)
- Reorganize some words as they used different terms for the same thing at different places (Chauffeur, ouvrier, employés, etc.)
I will join my proposal as soon as it's done

**Comment by polosubtil** [comment]
@knoxville73 
See my proposal below
[translation_fr_polosubtil-20200211.txt](https://github.com/Courseplay/courseplay/files/4185852/translation_fr_polosubtil-20200211.txt)

**Comment by polosubtil** [comment]
@knoxville73, if you don't have much to say, we could carry on with our mixed version there
@pvaiko, what should I do with that file now ?

**Comment by pvaiko** [comment]
@polosubtil you have to clone this repository, making you changes in the clone and then start a pull request. There are many great tutorials on the net on how to do this.

**Comment by polosubtil** [comment]
I tried something, but I don't know if it worked :)
I guess this is still a little bit complicated for me.

**Comment by pvaiko** [comment]
Did not work if it does not show up here: https://github.com/Courseplay/courseplay/pulls

**Comment by polosubtil** [comment]
I just tried again, I think there is something now but it's probably a mess... Sorry guys, not sure I am helping much
