### ISSUE TITLE
Combine unloading issues 

### ISSUE THREAD

**Issue by Shain-Allen** [Courseplay/courseplay#4919]
The tracker does not head to combine at the given percentage and often loses the combine all together in manual mode. Also, when waiting for the combine the tracker makes a noise that seems to be the engine starting and stopping rapidly.  Pathfinding is turned on

Harvester: varitron 470 platinum terra track
truck: Phoenix 6x6 argo truck

version: 6.01.00381

**Comment by Tensuko** [comment]
See #3311 and #4286 
Closed.
