### ISSUE TITLE
Harvester/Tractor collision

### ISSUE THREAD

**Issue by Breytac** [Courseplay/courseplay#4922]
During automated  harvesting, the tractor/trailer and harvester will quite often collide, especially if the tractor is behind the harvester while it (the harvester) is performing a reverese maneuver to move into the next lane, requiring intervention. Is there any way to avoid this?

**Comment by suchna** [comment]
I suppose you are harvesting corn for silage. Have you tried to skip 3 or 4 rows with harvester? With combination of 2-3 headlands it would solve reversing problem. Or you can try to use spiral or racetrack mode of the centre of the field. But I didnt test it enough yet. Once racetrack needs my attention every turn, onece it was completely fine and easy...

**Comment by Breytac** [comment]
To explain: combine is happily harvesting away. Combine becomes full, sends signal to tractor. Tractor approaches combine. Combine reaches end of field, starts reversing maneuver, however the tractor is still performing it's approach, even though the combine is reversing. Collision happens, tractor and combine need rescuing.

**Comment by Tensuko** [comment]
See #3311 and #4286 
Closed.
