### ISSUE TITLE
Errors after Register configuration 'fillVolume'

### ISSUE THREAD

**Issue by zsoltbranduse** [Courseplay/courseplay#4923]
After CP setting up the  log says 3 times:
Warning: Configuration name 'fillVolume' is not defined in vehicle xml!
Warning: Configuration name 'trailer' is not defined in vehicle xml!

[logCP part.txt](https://github.com/Courseplay/courseplay/files/4185848/logCP.part.txt)

Here is the whole log. After it spams the log file to Gb-s
[log.txt](https://github.com/Courseplay/courseplay/files/4185838/log.txt)

**Comment by Tensuko** [comment]
You got a callstack and the Errors got nothing to do with Courseplay, as you see in the path.
That is some Vehicle Error or Mod Issue.

BTW: Dedi Server ?

**Comment by zsoltbranduse** [comment]
Yes it is. I tried to delete the only sprayer mod that we used because the warnings are under the 'SPRAYER' loading but those lines still there. Maybe a global company addon incompatibility? I saw they made version where the changelog says Fix for CP

**Comment by Tensuko** [comment]
Fix for CP got nothing to do with that.
You should rather find the source of your callstack.

**Comment by Tensuko** [comment]
I don't see any CP Related Error here, but some Erros in other Mods.
Closed.
