### ISSUE TITLE
Abfahrer auf andere seite oder hinter häcksler setzen ?

### ISSUE THREAD

**Issue by Malando2** [Courseplay/courseplay#4924]
Hallo,

mir fehlen beim häcksler im Feldarbeit modus die option dem Abfahrer zu sagen er soll auf die Linke oder rechte seite- (siehe anhang). Oder kann man das irgendwo anderst noch einstellen ?

Ich benutze CP auf einem multiplayer server.

![git](https://user-images.githubusercontent.com/46270845/74272329-bc2a6f80-4d0e-11ea-854c-65344d112038.jpg)

**Comment by Tensuko** [comment]
Siehe #3311 und #4286 
Closed.
