### ISSUE TITLE
Saatmaschine wird nicht gesenkt

### ISSUE THREAD

**Issue by Torben833** [Courseplay/courseplay#4926]
Wenn ich Courseplay mit verschiedenen Sämaschinen starte, dann senkt der Fahrer diese nicht, sondern schaltet sie nur an und fährt los. Er senkt die Sämaschine allerdings nicht und wenn ich dies vorher Manuell tue, dann hebt er sie vor dem Losfahren wieder an.
Die Benutzen Sämaschinen sind : Condor 150001 Multifruit NF_Marsch und Horsch Pronto 9 DC
Courseplay läuft auf einem Dedicated Server also im Multiplayer
Woran könnte es liegen?

**Comment by Tensuko** [comment]
Wie sieht der Kurs aus und wo startest du ?
Wenn du nur ein Vorgewende hast, solltest du einstellen, am Ersten Wegpunkt starten, sonst erwischst du den Überführungskurs vom Vorgewende zum mittleren Teil.

**Comment by Tensuko** [comment]
Achja und das übliche: logfile ?

**Comment by Torben833** [comment]
Ich starte am Feldrand und starte auch beim ersten Punkt, daran kann es also nicht liegen. Welche Logs brauchst du? die vom Server einfach?

**Comment by Tensuko** [comment]
Beide. Am besten mal debugchannel 9 12 und 14 anmachen, fahrer starten und die logs dann hier anhängen.

**Comment by Torben833** [comment]
Okay, brauche keine Logs mehr schicken. Jetzt wo ich mit Debugchannel gestartet habe, hat er alles ganz normal gemacht. Läuft also alles. Trotzdem Danke für die schnelle Hilfe und vor allem die schnellen Antworten :)

**Comment by Tensuko** [comment]
Die Debugchannel sind aber nicht dafür da um etwas ein oder aus zu schalten, sondern schreiben nur die Dinge in die LOG, die CP sowieso macht....
Sollte also auch ohne Debugchannel gehen!

**Comment by Torben833** [comment]
Ja ich verstehe das schon, wofür die sind.
Es funktioniert auch ohne die Channel. Wollte damit nur sagen, dass genau da wo ich die Logs aufzeichnen wollte, es dann funktioniert. 
Läuft alles Problemlos! :)

**Comment by Tensuko** [comment]
Bestens! Dann kann hier ja zu :)
