### ISSUE TITLE
Error: Running LUA method 'packetReceived'. 

### ISSUE THREAD

**Issue by zsoltbranduse** [Courseplay/courseplay#4927]
Its a dedicated server, after i start the course it won't start to go through but it has another line of error:
 04 [info lp359077] Fastrac 4220 (#2): There is no course with id=6, not loading course for this vehicle
But there is a course in the game but no course in Courses folder

Here is the log file
[log.txt](https://github.com/Courseplay/courseplay/files/4194826/log.txt)
version is 0379

**Comment by Tensuko** [comment]
This is not a full logfile.
A big part is missing like Versions and Mods and so on.
Also you have another Error wich comes from the Game.

**Comment by zsoltbranduse** [comment]
Sorry i don't have the log file before these lines, you can close the issue
