### ISSUE TITLE
Question: Why does my plug team not turn on the field, although activated in the settings? - Frage: Warum wendet mein Plug-Gespann nicht auf dem Feld, obwohl in den Settings aktiviert?

### ISSUE THREAD

**Issue by haamic** [Courseplay/courseplay#4930]
Hello,
i am tinkering with a small map and am currently testing the functionality with courseplay. The fields are recognized correctly. I am ploughing a field, which is located between trees (forest) and houses. The driver always wants to turn outside the field, although the option "Turning on the field" is active and therefore drives against the trees or houses. So over a driven curve to the next row. 
There are also 2 headlands. The space should be sufficient.  I remember that the CP used to drive backwards, turned around and backwards again to the start of the next row. Is this not the case anymore? Do I have to do anything else on the map to make CP recognize the trees and houses as obstacles?  I would be happy about helpful answers, thanks. 
Greetings Micha

Translated with www.DeepL.com/Translator (free version)
+++++++++++++++++++++++++++++++++++++++++++++++++++++
Hallo,
ich bastel an einer kleinen Map und teste gerade die Funktionalität mit Courseplay. Die Felder werden ordnungsgemäß erkannt. Ich pflüge ein Feld, das sich zwischen Bäumen (Wald) und Häusern befindet. Der Fahrer möchte immer ausserhalb des Feldes wenden, obwohl die Option "Wenden auf dem Feld" aktiv ist und fährt deshalb gegen die Bäume oder Häuser. Also über einen gefahrenenen Bogen zur nächsten Reihe. 
Es sind auch 2 Vorgewende da. Der Platz sollte eigentlich ausreichen.  Ich erinnere mich, das CP sonst eigentlich rückwärts  fuhr, wendete und wieder rückwärts zum start der nächsten Reihe. Ist das neuerdings nicht mehr so? Muss ich an der Karte noch was machen, damit CP die Bäume und Häuser als Hindernis erkennt?  Über helfende Antworten würde ich mich freuen, Danke. 
Gruss Micha

**Comment by Tensuko** [comment]
Kommt auf den Pflug drauf an.
Ich werde mir das aber noch mal angucken.
Das wurde aber schon angemerkt in #4908 von daher mache ich hier zu und es geht im anderen Issue weiter.
