### ISSUE TITLE
Agroliner TKD 302 will not unload in Lizard Extralarge multifruit silo

### ISSUE THREAD

**Issue by gec100** [Courseplay/courseplay#4931]
Not sure if this is Agroliner problem, Farm silo set mod problem or CP problem.

CP v6_01_00382 
MP Dedi server

Bergmann REPEX 34S will unload no problem.

**Comment by Tensuko** [comment]
log with channel 1 and 2 active.

**Comment by gec100** [comment]
Log is attached. happened at the end of the log.

It's not happening all the time. Today was working correctly most of the time.

another issue that raised from battling with this one is that i have no option to delete courses.

 
[log.zip](https://github.com/Courseplay/courseplay/files/4204398/log.zip)

**Comment by Tensuko** [comment]
Delete Course Issue: #4840

**Comment by Tensuko** [comment]
Load mod: Courseplay_6_01_00382 (Version: 6.01.00382) (Hash: bdd0268e700df1951fa7e3a7499f8bed)
Load mod: Courseplay_6_01_00383 (Version: 6.01.00383) (Hash: cd95e3dd56ef7893214a78db99c2e424)

...

Thats why I tell ppl to always ONLY rename it to FS19_Courseplay so you will always have a check for this.

Fix or remove this too:
Load mod: FS19_FlieglshovelPack_2 (Version: 1.1.0.0) (Hash: 4d2cac33b2d0e63d39f6367418d366f3)
Warning: No l10n file found for 'modDesc_l10n' in mod 'FS19_FlieglshovelPack_2'

Unload into Silo with Mode2 doesn't work if that is the case.
See #3311 and #4286

**Comment by gec100** [comment]
Here is the clean log

[log.txt](https://github.com/Courseplay/courseplay/files/4209462/log.txt)

**Comment by Tensuko** [comment]
Collecting all in #5484
