### ISSUE TITLE
Stop at last point or at next trigger "locked"

### ISSUE THREAD

**Issue by Nyggen81** [Courseplay/courseplay#4934]
Hello,

I have an issue where you click "stop at last point or at next trigger" it will change mode from "deactivated" to "activated". After that Im not able to go back to "deactivated".  This happens in all modes.

Im currently running version .00383.dev.
Only uses placeable tanks mod and CP.

Will a log or a savegame help investigating this further?

**Comment by Tensuko** [comment]
Will check that one later.

**Comment by gec100** [comment]
i can confirm this problem

**Comment by Misamangame** [comment]
me too

**Comment by Tensuko** [comment]
Start Driver - automaticly on activated
Stop Driver - automatically on deactivated
Click on it to activate it, then can't be deactivated, only when start and stop driver, it switches back to deactivated.

**Comment by Nyggen81** [comment]
@Tensuko What do you mean by "stop driver"? 
Im in multiplayer and after I have clicked "activate" its not possible to deactivate it unless I log out and into the game again. 

Tried to stop vehicle, jumped out and into the vehicle, cancel route and loaded new route, still it stays at "activate"
