### ISSUE TITLE
Question: for Gitub forks and Mode 1(Multiplayer Fix)

### ISSUE THREAD

**Issue by schwiti6190** [Courseplay/courseplay#4935]
Hi,
I've tried to fix mode 1 for Multiplayer and after a few test I found a possible solution.
Now the problem is i am not sure if I broke some of the other trigger behavior associated with courseplay.
Can somebody maybe explain to me how I can create a clean new pull request ? 
How should I go about the fixes, if i am not sure it might break singleplayer stuff?

**Comment by ddewar** [comment]
And to expand on this a little bit, does any sort of documentation exist on how to help contribute? Some sort of developer guide might get more of us jump in and fix some bugs if you guys want any help!

**Comment by pvaiko** [comment]
We desperately need contributors, thank you for contacting us.

@schwiti6190 there are many good tutorials for Github and for git in general, you probably want to take a look at those, I know pull requests may be confusing. Regarding your other question: unfortunately we have no automated tests for any of the CP code so the only way to find if something else is broken is to test it yourself, let others review your code (pull request for example) and once you feel comfortable, push it, the user community is big enough to find new bugs quickly, don't ask how do I know this...

@ddewar There isn't a lot of information on this, although newer CP code will generally have more comments explaining what is happening and be more structured. 

We have some hacks built in to CP to make development a lot easier (reload sources without restarting the game, print variables, call functions from console etc.) 

If you guys are serious about helping out, send me your email addresses and I'll invite you to the Discord channel, we have a German and an English one.
