### ISSUE TITLE
Hoover "manage courses" tab, looses control over vehicle

### ISSUE THREAD

**Issue by Nyggen81** [Courseplay/courseplay#4936]
Maybe its a bit early to begin posting "polishing" suggestions, but anyways..

Hoovering with the mouse pointer over the "manage courses" page will make you loose the ability to control the vehicle. This is just kinda annoying when you are driving at the same time that you are puzzling routes together.

Easy fix or intended to be like this?

**Comment by Tensuko** [comment]
This is on purpose, so when you have any Menu where you can use the Mouse Wheel to scroll, you won't change your camera zoom.
So ppl also find it annoying when scrolling some numbers or list in CP and the camera zoom will change :)
