### ISSUE TITLE
CoursePlay conflict with SpeedControl mod

### ISSUE THREAD

**Issue by RUGhost** [Courseplay/courseplay#4937]
SpeedControl mod ( [https://farming-simulator.com/mod.php?lang=en&country=za&mod_id=125190](url) ) does not work if CoursePlay is active. Pressing 1 or 2 does not change cruise speed. 
CP version 6_01_00354 worked fine but later version does not work. May be it happens for the key binding of "in-game course editor".

**Comment by Tensuko** [comment]
Yea this is another Problem with KeyConflict...
We would need someone who can rewrite our keybind system....
