### ISSUE TITLE
courseplay not not working in game

### ISSUE THREAD

**Issue by JohnLJ86** [Courseplay/courseplay#4938]

**Comment by JohnLJ86** [comment]
i have downloaded the mod.
unzipped the files.
compressed the files.
remamed the compressed folder.
moved the compressed folder to FS mod folder.
courseplay is not working in game.

**Comment by uded** [comment]
Download a ZIP file from the "Assets" for any of the [releases](https://github.com/Courseplay/courseplay/releases). The name should start with _Coureplay_6_...

**Comment by Nyggen81** [comment]
Did you put the zipped folder in "my documents/fs19/mods"?

Do you see the mod in the modlist ingame?

Did you activate the mod befor entering the game?

**Comment by JohnLJ86** [comment]
> Did you put the zipped folder in "my documents/fs19/mods"?
> 
> Do you see the mod in the modlist ingame?
> 
> Did you activate the mod befor entering the game?

yes i put the zipped folder in FS19 mods.
yes the mod is in the modlidt in game menu.
the mod is not in the game startup list to be activated

**Comment by JohnLJ86** [comment]
> Download a ZIP file from the "Assets" for any of the [releases](https://github.com/Courseplay/courseplay/releases). The name should start with _Coureplay_6_...

that worked 

thank you
