### ISSUE TITLE
überladewagen fährt Rohr nicht aus 

### ISSUE THREAD

**Issue by iceman234de** [Courseplay/courseplay#4939]
Hallo, mir ist aufgefallen das der überladewagen nicht das Rohr ausfährt beim abtankvorgang , nur so nebenher.
 Habe die aktuellste Version von courseplay 

Gruß iceman

**Comment by schwiti6190** [comment]
Besteht das Problem im Singleplayer oder nur im Multiplayer ?
Hast du vlt eine Log Datei zu dem Fehler?

**Comment by iceman234de** [comment]
Logfehler habe ich keine , nur das der cp abfahrer nur am ü Wagen die Pläne schließt und am Ende wieder öffnet , nur das abtankrohr bleibt geschlossen , mus man selbst ausfahren damit der überladevorgang von statten geht

**Comment by iceman234de** [comment]
Habe nur Singleplayer

**Comment by Merrlin** [comment]
Siehe dazu #3311 und #4286...
Mode 3 hängt an Mode2 und der ist noch in der Mache
