### ISSUE TITLE
Corn harvest

### ISSUE THREAD

**Issue by shane101978** [Courseplay/courseplay#4940]
Would it be possible to set up corn headers so they strike out a land and keep turning left to the next pass?  this is most generally how corn harvest works with an auger cart so the auger on the combine is to the open side of the pass, going back and forth across the field defeats the purpose of keeping the combine going. This is more of a suggestion than an issue.

**Comment by Tensuko** [comment]
Did you experiment with the Coursegenerator settibgs for Midfield Strategie ? Like Racetrack and the other option that I forgot what it is called :)

**Comment by shane101978** [comment]
So after experimenting the racetrack is what I'm looking for, but is there a way to reverse the path.  The auger on the combine is still over the planted portion of the field.  The only option I see is for headland to go clockwise/counter clockwise

**Comment by Tensuko** [comment]
Everything that have to do with Mode2 is #3311 and #4286

**Comment by pvaiko** [comment]
@shane101978 with that pattern there'll always be one direction where the pipe is in the fruit. The only pattern where the pipe is never in the fruit would be a spiral starting in the middle of the field but then the combine would have to travel great distances on the headland.

**Comment by Tensuko** [comment]
Not going to change anything on Coursegenerator.

Closed.
