### ISSUE TITLE
LUA Call Stack Issue (173 or 882)

### ISSUE THREAD

**Issue by Butterz51** [Courseplay/courseplay#4941]
Hi, I am hoping you would be able to shed some light on an issue I am having with an LUA call stack.  I have courseplay driving from a field to a CFM mixer to unload when it's full; the course that I am running to the CFM is from autodrive. The LUA call stack only appears when the tractor gets close to the CFM mixer.
This call stack locks the game up so I am forced to ALT-F4 out
I have tried deleting autodrive network, removing all mods (except for the map, courseplay, and autodrive)  and re-doing the courses with no success
I have also tried setting up a course using only courseplay from the field to the CFM but I am still getting this call stack. 

[log.txt](https://github.com/Courseplay/courseplay/files/4208823/log.txt)

CoursePlay Version 6.01.00384

**Comment by pvaiko** [comment]
I'm sure you know exactly what a CFM mixer is, I have unfortunately no idea.

**Comment by Butterz51** [comment]
Cow Feed Mixer.. sorry I guess I should of just put that

**Comment by Butterz51** [comment]
Do you need any more info if so just ask!!
Map: Eiersholt        Ver: 1.0.1.0
AutoDrive Ver: 1.0.7.1
CoursePlay Ver: 6.0.1.00385

**Comment by Tensuko** [comment]
What CFM is it ?
GC one ?
Is this still actual with Newest Release Version ?

**Comment by Butterz51** [comment]
it is not a GC one and I also tried the new version of CP 388 and it still happens. Also, there is a Pig Feed Mixer (PFM) its the same building and there are no problems with it. I will do a test today later on with the newest version of CP and send a new log file if there are any changes to the call stack

**Comment by Tensuko** [comment]
Is it a fixed build in CFM on the Map?

**Comment by Butterz51** [comment]
The CFM is built into the map. I have tried today the new CP version 390 and I'm still getting the call stack. I have attached the log file and a new screenshot.
[log.txt](https://github.com/Courseplay/courseplay/files/4272239/log.txt)
![20200301132354_1](https://user-images.githubusercontent.com/18358355/75631383-6b48c100-5bc0-11ea-8dc4-ce3fafb84dec.jpg)

**Comment by Tensuko** [comment]
Between the Callstacks is always this:
2020-03-01 13:23 Error: Running LUA method 'update'.
2020-03-01 13:23 dataS/scripts/utils/MathUtil.lua(173) : attempt to perform arithmetic on local 'x' (a nil value)
That one comes from GIANTS and I am pretty sure that there is something wrong with the CFM in the Map. I don't have any other Idea then that, when the Mixer for PigFood is running fine with the same setup, then the CFM should do fine too unless there is something wrong.
Or try to drive the course in another way, maybe you hit an other trigger or something.

**Comment by bgo1973** [comment]
Hi Tensuko. Thx for reply. Is it possible that the issue is called by setting collision bit 12 on the bale trigger? Because the bale trigger is the only difference between the two feeder stations.

**Comment by Tensuko** [comment]
I have no Idea about this :)
Try it out.

**Comment by bgo1973** [comment]
We will do and report. Thx so far.

**Comment by Butterz51** [comment]
So I have tried the edited CFM and I still got the call stack (that's with the bale trigger removed).
Game Details:
Fresh New Game - Mods used: CP .390 , AD 1.0.7.1 , Eiersholt 1.0.1.0 (MAP) , EasyDevControls

**Comment by Tensuko** [comment]
Any News about this ? Even I don't think it is CP, but tried this with V397 ?

**Comment by Butterz51** [comment]
It's still happening with CP Version 397 / AD Version 1.1.0.1 the map hasn't changed.

**Comment by Tensuko** [comment]
Got a Savegame ?

**Comment by Tensuko** [comment]
Closed due to inactivity.
