### ISSUE TITLE
Silo does not have the selected fill type (mode 1)

### ISSUE THREAD

**Issue by Nyggen81** [Courseplay/courseplay#4943]
CP ver: 6.01.00383.dev
SP/MP: Multiplay
Mode: 1 grain delivery

Tipper is not filled from silo even if you have the selected grain in the silo. You get "Silo does not have the selected fill type" message. If you manually fill the tipper will be emptied on unload point.

Log and savegame:
https://gist.github.com/Nyggen81/d16c5681fe1ef23e2fc299870357cb82

**Comment by Tensuko** [comment]
logfile with debugchannel 1 and 2 active, then drive the course.

**Comment by Nyggen81** [comment]
Log: https://gist.github.com/Nyggen81/6f23e50a8bb37d3bf82151998cd92220

**Comment by Nyggen81** [comment]
I am able to manually press "R" and refill even if the course is active. When fill level is reach then the vehicle will l leave.

**Comment by Tensuko** [comment]
Error: Failed to open xml file 'C:/Users/kjeti/Documents/My Games/FarmingSimulator2019/mods/autodrive/modDesc.xml'.
Load mod: autodrive (Hash: 5167a73ff63715c237647ce367a5384e)
Error: Missing descVersion attribute in mod autodrive

And log doesn't look like complete. I miss the part where he checks the silo.

**Comment by Nyggen81** [comment]
Now I tried several times and I get the message every time. Log file should cover it now. Also I deleted autodrive even if it wasnt in use.

https://gist.github.com/Nyggen81/3f4bf19bd20d0003908025d0cc1c3af9

**Comment by Tensuko** [comment]
![log](https://user-images.githubusercontent.com/27344744/74594642-f78fab80-5038-11ea-8979-495d161afd25.png)
this is the last thing what I see in your log.
Just drag and drop the log.txt into comment box....

**Comment by Nyggen81** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4208968/log.txt)

**Comment by Nyggen81** [comment]
I tried several times to fill tipper, you wont see the whole route where he tips it (the tipping part works).

**Comment by Tensuko** [comment]
Screenshot of the Silo and the Course part pls I don't get it.

**Comment by juninholiveira** [comment]
The exact same problem happens to me, the veihcle stops under the Silo and i get the warning that i dont have the grain, even if a do. Manually refilling works tho.

**Comment by Tensuko** [comment]
But you all did select the right fruit in the HUD, right ?
And it is not a Global Company Factory ?

**Comment by Nyggen81** [comment]
https://imgur.com/a/KLVyp6g

I chose soybeans and there is soybeans in the silo. (works manually)
Same happens both in the Railroad silo east and one placeable built on my farm.

**Comment by ddewar** [comment]
Is this a dedicated server? I've been seeing lots of similar issues on the dedicated server that I wasn't having on my local machine hosting a sever.

**Comment by Nyggen81** [comment]
This is indeed on a dedicated server / multiplay yes.

**Comment by schwiti6190** [comment]
I have a potential fix for it but there is still two bugs with synchronizing variables. I will probably look at it later and create a pull request. 
At the moment I am still trying to recover from yesterdays party 😅

**Comment by Mannie313** [comment]
@Tensuko  ist es nicht das gleiche wie # 4792

MFG Mannie313

**Comment by Tensuko** [comment]
> 
> 
> @Tensuko ist es nicht das gleiche wie # 4792
> 
> MFG Mannie313

kein Global Company in der log :)

**Comment by Tensuko** [comment]
Should be similar to  #4778

**Comment by candymant** [comment]
i have it in single player to
