### ISSUE TITLE
Häcksler: Pickup wird nicht angesteuert

### ISSUE THREAD

**Issue by Merrlin** [Courseplay/courseplay#4944]
Hallo Zusammen,

hab ein Issue in Zusammenhang mit den Feldhäckslern und den Standard-Pickups (Für Stroh und so) gefunden.
Und zwar werden die im Mode 6 nicht angesteuert. Sie werden also weder ausgeklappt noch abgesenkt und der Häcksler schaltet sich auch nicht ein. Allerdings klappt sich der Häcksler selbst schon aus(Rohr ausfalten, Kabine heben). Schaltet man den Häcksler manuell ein, wird der Pickup beim Bahnwechsel auch nicht angehoben. Der Häcksler fährt aber den Kurs mit Worktool Speed ab.
Getestet hab ich den BigX 1180 und den FR780. Beide Vanilla und mit dazugehörigen Pickup auf Felsbrunn.
Edit: Am Ende der Route wird sogar alles ordnungsgemäß zusammengefaltet
[log.txt](https://github.com/Courseplay/courseplay/files/4209047/log.txt)

**Comment by pvaiko** [comment]
Funktioniert es mit dem Giants Helfer?

**Comment by Merrlin** [comment]
Grad genauer probiert. Beim Pickup tuts der Helfer überhaupt nicht. Bei Strohschwad wird nichtmal was aufgenommen. DirectDisk und Maisgebiss funktionieren einwandfrei mit CP und Helfer.

**Comment by eric4072** [comment]
leider wurde mein Beitrag bzgl. des gleichen Themas geschlossen: Hätte noch eines dazu zu sagen: der Standardhelfer ist hier kein Vergleich da dieser ja keinen Schwad erkennt...

**Comment by Merrlin** [comment]
Das ist egal, er sollte zumindest den Pickup bzw. Den Häcksler ansteuern. Aber nicht Mal das tut er, müsste er aber damit es in CP Out of the Box Funktioniert.

**Comment by SeriouZ12** [comment]
Hi, gibt es hierzu ein Update?
