### ISSUE TITLE
Course Generation not working for currently loaded field/Fields Not Loading Entirely

### ISSUE THREAD

**Issue by xXAzureDragonXx** [Courseplay/courseplay#4946]
I currently have Courseplay version 6.01.00381 and multiple other mods (all tested and working) running on a rented dedicated server. Now as far as Courseplay itself and all the other mods are concerned, they have all been tested and confirmed working _flawlessly_ in Career Mode without issue at all, this is simply and literally a CLONE of that save game OR a new game entirely on the server. This being said, on Multiplayer ONLY, the Course Generation fails. I can manually scan the fields edge path just fine but when attempting to create a course within these guidelines, nothing happens when clicking the 'Generate Field Course' button or by pressing 'Spacebar'. Secondly, when trying to just select a field for course generation, one of two problems occur but not BOTH at the same time. The option to change the 'Field Edge Path' from (Currently Loaded Course) is IMMOVABLE. You cannot change this option. If this is NOT the case, then I am able to select (in my testing) Field 29. Upon selection of said Field 29, I can now click the 'Generate Field Course' and the pathing that is shown does not cover the whole field, parts are missing, ect. It is almost as if the map was not loaded fully. Thought of this and i tried MANY steps to fix this issue, ### **TO SOME SUCCESS!** Below I will list the steps I have already attempted, as I can remember.

1) Upon noticing the field colors, areas were blank, without color. Hitting 'Esc' or 'X' multiple times, in rapid succession would force load more 'pixels' or area of the fields. I did this for AGES and filled every field in completely. Tried again both forms of course generation = **Failure**

2) Created a 'New Game' in 'Career' mode, Saved, exited and uploaded the .zip file to my server, tried all of the above mentioned steps = **Failure**

3) Removed any conflicts or errors (even unrelated to Courseplay) from my mods folder and the server, Tried again. **Failure**

4)  It appears as though the 'Scan Fields Automatically' feature is getting interrupted by an error (though this error is benign to the actual game play, coding, courseplay, ect (Its "Place Anywhere" and "More Trees" having an issue with "Global Company" as I mentioned above, disabling these mods has no effect). Not sure if this has anything to do with the issue, so this leads me to 5.

5) In the settings of Courseplay, I turn off the automatic scan option, save the game, exit the game, restart the server, log BACK in the game, go back into the settings menu, turn BACK ON the automatic scan option and Courseplay works _FLAWLESSLY_. I get about 10 seconds to star at it in stupidity, wondering what I did before my internet disconnects and I am disconnected from the game. 

6) Upon loading back into the game, Courseplay is again, effed, plagued from this cancerous problem again. **FAILURE**

7) Here we find the answer I have been seeking, lucky number 7 (for me :), that just happened by chance in writing this) upon placing all of the puzzle pieces together and retracing my steps, I have found a work around but not a complete solution and that is why I am here. _**SUCCESS**_

The 'Work Around' _**MUST BE DONE IN THIS ORDER!!**_

1) Start your game
2) Get in a vehicle that is able to access the Courseplay menu
3) Go to the 'Advanced Settings' and disable "Auto Scan Fields'
4) Exit the game (save if you wish, I didn't see it have any effect on the settings, this may have because I did most of my testing live on a multiplayer server) **_EDIT_** You **MUST** save your game, even if it is a multiplayer map, to save the courseplay settings.
5) Re-Launch the game, load back in and _**WAIT**_ for all of the fields to FULLY load with the color of the indicated crop type.
6) After fields have loaded, hop back in your vehicle and re-enable 'Auto Scan Fields'
7) After scan is complete disable the 'Auto Scan Feature again.

This will force a reload of all of the fields on the map from Courseplay and all of vehicles and subsequent courses will generate properly. _**BE WARNED**_ Upon exiting the game, you **_MUST_** repeat these steps to continue to use Courseplay.

I hope this helps someone else for now. I am here trying to find someone who can maybe help me resolve this issue and perhaps it can improve the mod itself. I have spent hours on this already and I feel that there is nothing more that I can do at this point, so I leave it here, in the hands of more capable individuals. I will continue to check this post for any future help or answers I might find and thank you if you have made it this far. :)
![Flawless Course Generation](https://user-images.githubusercontent.com/61098826/74597649-4a149c00-5028-11ea-8995-b860015257bd.png)
![Fully Loaded](https://user-images.githubusercontent.com/61098826/74597650-4aad3280-5028-11ea-8d76-fe044d5c2d38.png)
![Partially Loaded 1](https://user-images.githubusercontent.com/61098826/74597651-4bde5f80-5028-11ea-93e1-ae14458acc61.png)
![Partially Loaded 2](https://user-images.githubusercontent.com/61098826/74597652-4c76f600-5028-11ea-87aa-3bd30947963e.png)
![Wrong Course Generation](https://user-images.githubusercontent.com/61098826/74597654-4da82300-5028-11ea-89ce-8a3281f75740.png)

**Comment by xXAzureDragonXx** [comment]
I also forgot to mention that after this is successful and your course is fine, IN MY CASE, when clicking back onto the 'Current Field Selection' and trying to Generate a course, this will cause the game to crash CLIENT side.

**Comment by xXAzureDragonXx** [comment]
A few updates I have found affecting this mod so far. 

1) Saving courses works fine, as long as you can create them and they seem to load fine regardless of the fields loading condition.

2) Workers will not unfold or turn on equipment.

3) Some vehicles will not abide by working speed rules when loading a saved course. They will go full driving speed instead of the max working speed of the tool. Ex. A sprayer I have that has a max working speed of 7mph and working width of 36m will go 32mph down the field on the Valtra S374 (just my chosen tractor).

4) Contract work fields will not load in courseplay, nor is there an option to generate a course for the field as you cannot select it. Manually recording a course on this field and hiring a helper to run the course will work and you can pull up the course at any time.

This is all I have found so far, after my initial findings. I will post my Log file just as further proof and for someone else to look into it for me. If there are any other files someone would like to see, I will gladly send them. 
[log.txt](https://github.com/Courseplay/courseplay/files/4211305/log.txt)

**Comment by tibike262** [comment]
if you have joined more fields do following:
1. scan for field
2. save selected field under field numbers that are those fields joined (this overrides the normal field boundaries)
3. generate the course for the field nr. XY that you have saved
4. Profit. GL&HF

**Comment by Tensuko** [comment]
Collecting all in #5484
