### ISSUE TITLE
Game stuck in loading screen

### ISSUE THREAD

**Issue by Stupremee** [Courseplay/courseplay#4947]
When I activate courseplay in my savegame, my game gets stuck in the loading screen and nothing happens.
But as soon as I turn courseplay off, it works fine again.
In the log I find the following error:
```
2020-02-16 11:49 Error: Running LUA method 'loadSharedI3DFileFinished'.
2020-02-16 11:49 .../Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00384/course_management.lua:1722: attempt to call method 'GetAvailableDestinations' (a nil value)
```

Courseplay Version: v6.01.00384
Log: [log.txt](https://github.com/Courseplay/courseplay/files/4209657/log_courseplay.txt)

**Comment by Stupremee** [comment]
I looked at the source code where the error happens and saw that it tries to load AutoDrive destinations.
After I disabled auto drive and enabled courseplay, it worked.

**Comment by Nyggen81** [comment]
Same happens to me. Latest autodrive and cp will get the game stuck in loadingscreen. I have not yet been able to start with both of them.

**Comment by Stupremee** [comment]
I updated to the [latest](https://github.com/Stephan-S/FS19_AutoDrive/releases/) AutoDrive version and it worked.
