### ISSUE TITLE
Ativar modo para usar a bazuca

### ISSUE THREAD

**Issue by erksartori** [Courseplay/courseplay#4948]
Ola, estou querendo usar a bazuca no jogo com o courseplay, porem nao esta abilitando a opcao confo
![bazuka](https://user-images.githubusercontent.com/8292001/74604122-ba0f3a80-5099-11ea-8385-1252c1769d97.png)
rme imagem

nao lembro o nome pois esta desabilitado, mas seria a terceira opcao "modo" para habilitar o modo de ir ate a colheitadeira descarregala, e depois ir ate a carreta para descarregar a bazuca.

**Comment by Tensuko** [comment]
English pls.
https://github.com/Courseplay/courseplay/wiki

**Comment by Merrlin** [comment]
See #3882. Mode3 depends on Mode2 and is WIP. For details see #3311 and #4286

**Comment by erksartori** [comment]
A ultima vez que coloquei em ingles pediram pra mim colocar no meu idioma

The last time I put it in English I was asked to put it in my language

Eu uso somen te tratores e equipamentos originais do jogo.  e estou querendo fazer a rota para utilizar a bazuca conforme imagem. Mas o sistema nao esta habilitando o modo de autocarregar, exemplo imagem do farming 17

![bazuka17](https://user-images.githubusercontent.com/8292001/74692011-14a4b580-51c4-11ea-8063-4023c133c763.png)

**Comment by erksartori** [comment]
Ha um detalhe especifico, eu sempre estou utilizando a ultima versao de voces. 
Esqueci do log.

There is a specific detail, I am always using the latest version of you.
I forgot the log.


[log.txt](https://github.com/Courseplay/courseplay/files/4216681/log.txt)

**Comment by Tensuko** [comment]
Mode3 not active yet, couse we are rebuilding Mode2.
See #3311 and #4286 
Sry but you have to wait.

Closed.
