### ISSUE TITLE
 Problem with mode 9

### ISSUE THREAD

**Issue by ice81rm** [Courseplay/courseplay#4949]
Hello to all
I have a problem with the shovel when I load the isolate from the trench ...
at the first point everything is fine, when it loads 100% the blade remains in the first position, then everything is fine but when it reaches the unloading point it does not perform it and goes back ....
![Screenshot (243)](https://user-images.githubusercontent.com/39805100/74604121-3ebe8080-50bb-11ea-98a2-90b3df040402.png)
![Screenshot (242)](https://user-images.githubusercontent.com/39805100/74604141-6e6d8880-50bb-11ea-8dab-1df7d0034226.png)
![Screenshot (241)](https://user-images.githubusercontent.com/39805100/74604174-9826af80-50bb-11ea-8f95-e75992fc25aa.png)
![Screenshot (240)](https://user-images.githubusercontent.com/39805100/74604190-bbe9f580-50bb-11ea-8916-18514d0d16ca.png)
![Screenshot (239)](https://user-images.githubusercontent.com/39805100/74604207-e045d200-50bb-11ea-83a3-08312e0f46cc.png)
![Screenshot (238)](https://user-images.githubusercontent.com/39805100/74604220-079c9f00-50bc-11ea-8b37-ae69ea333288.png)
![Screenshot (237)](https://user-images.githubusercontent.com/39805100/74604232-29962180-50bc-11ea-9f12-c1dbb8740d33.png) 
[log.txt](https://github.com/Courseplay/courseplay/files/4209766/log.txt)

**Comment by TinyCrocodile** [comment]
Is this still a issue or did you get it workig meanwhile?

**Comment by Tensuko** [comment]
Tested a while ago and that mode works fine.
