### ISSUE TITLE
Unloading doesnt work

### ISSUE THREAD

**Issue by franky135** [Courseplay/courseplay#4950]
since few versions of courseplay i already have the problem that i cant unload any grain or potatoes at farmsilo or selling points.
the tractor drives to the sellpoint, lift the lorry but doesnt unload and than drives back to the field with lifted lorry without loosing grain and there start again his trip. when i stop courseplay at front of the sellpoint i can unload manual by "I" and start tractor again
the only difference between combi mode and loading at startpoint is that when i choose this it starts lifting the lorry already like 50m before the sellpoint.
harvesting silage works.
[log.txt](https://github.com/Courseplay/courseplay/files/4209822/log.txt)

**Comment by Tensuko** [comment]
Load newest VCersion 1st.
https://github.com/Courseplay/courseplay/releases
Then I need more information, like Map, Tool, and how does your Course look like ?
I hope you didn't put Waitpoints anywhere...

**Comment by Tensuko** [comment]
![fsScreen_2020_02_16_16_25_22](https://user-images.githubusercontent.com/27344744/74607452-53aa0c80-50d9-11ea-99b1-9044a339358d.png)
![fsScreen_2020_02_16_16_27_35](https://user-images.githubusercontent.com/27344744/74607456-54db3980-50d9-11ea-8ac9-974f4e5a8fc7.png)

works as it should.

**Comment by franky135** [comment]
hi!
i updated and its still the same. i play on nordfriesische Marsch and tried with different sellpoints, different tractors, different fruits and different lorries, (mods and original).
this problem came up for the first time at october last year or something like that but wasnt disturbing on a small farm.
[log.txt](https://github.com/Courseplay/courseplay/files/4210748/log.txt)

**Comment by Papa-Scherzkeks** [comment]
Benutze [**P**] und nicht den Entladebetrieb dann sollte es gehen. 
Hatte das selbe Problem und habe es um gestellt seit dem geht es.

**Comment by Tensuko** [comment]
Weder Wartepunkt, noch Entladepunkt! Es ist schlicht weg falsch und kann zu problemen führen! Wenn der Trigger erkann wird, wird er erkannt und ein Wartepunkt ändert nichts daran...

**Comment by franky135** [comment]
Mein Kurs startet am Feld, geht über die Straße zum Verkaufstrigger und zurück zum Feld. Am Abladepunkt habe ich immer den Entladepunkt gesetzt, weil ich früher das Problem hatte, dass der Fahrer beim Entladen weiter fuhr und alles auf der Straße verteilte. 
Also meinst du, dass es ohne funktionieren könnte?

**Comment by Tensuko** [comment]
Wartepunkt = Warten
Entladepunkt = Hier abladen, das ist wie strg+i und das macht man am Verkaufstrigger ja nicht.
Was aber dein Problem sein kann wenn du Mode2 benutzt das eh nichts funktioniert...
Wenn Mode1 dann sollte das ohne irgendwelche spezielle Punkte gehen wie auf meinen Screenshots zu sehen.

**Comment by realskudd** [comment]
I am able to reproduce this with the latest build. Currently working on Felsbrunn.

If it would be useful, I can share my `careerSavegame.xml`.

**Comment by Tensuko** [comment]
Log channel 1 and 2, screenshots of unloadpoint with shown course and savegame like this doesnt help,would need the folder zipped.

**Comment by franky135** [comment]
hi there! i tried on channel 1 and 2 and it works without setting a tippoint

**Comment by Tensuko** [comment]
Becouse you never set an unload or waitpoint on selltriggers.... what a surprice that it works now...

**Comment by realskudd** [comment]
Yeah, that seems to have been the issue. Don't set an unload trigger over a silo dump.
