### ISSUE TITLE
Using "Tool offset vertical"

### ISSUE THREAD

**Issue by vemendoza** [Courseplay/courseplay#4952]
Hello guys, thank you for your excellent job about Courseplay.

So, I'm using this mod for about a short time and maybe I'm setting offset vertical, for any tools, using an incorrect setting.

Looking this picture, you can see that a short space of my land is not prepared (red) when the tractor is going out of my land. However, when the tractor turns, all works well.

![Desktop Screenshot 2020 02 16 - 15 04 34 06](https://user-images.githubusercontent.com/48180617/74610637-a1237b00-50d3-11ea-9061-9facc91fbdaa.png)

In this case I'm using "Tool offset vertical" -2.0m (back).
If I use +2.0m (front), the problem is inverted. In other words, using front distance, when the tractor is going inside my land, a short space is not prepare, and whem the tractor out, all works well.

Maybe, and this is a suggestion, you can insert a little code that invert this offset for each lane when the tractor is inside or outside of the land (if -2.0 outside the land to +2.0 inside the land, and if +2.0 outside the land to -2.0 inside the land). The purpose is ever cover all the land.

Sorry my English, and have a good job.

**Comment by pvaiko** [comment]
Try using the raise/lower implement settings (early/late) in the advanced settings dialog instead of the offset.

**Comment by Tensuko** [comment]
Chane raise implement to late and lower implement to early.

**Comment by vemendoza** [comment]
Well.... now is perfect... hehe. I'll try with the other implements like seeders and sprayers. I never touched this options.

Very very thank you.
