### ISSUE TITLE
Fieldwork machines go full speed when "Continue" is pressed after starting a course (MP dedicated)

### ISSUE THREAD

**Issue by Playnot** [Courseplay/courseplay#4954]
Hi everyone. Every time I start a new course a button appears below "Drive Course", that's labelled "Continue". If I press that button the machine that's currently running the course goes at the fastest available speed, while at the same time doing the work. So there's sowing/harvesting/fertilizing going around at 40-50-60kmh, up to the machine's top speed. This only happens in the MP dedicated server I'm running. 
Attaching a video for demonstration:
https://youtu.be/BMO76PWNknA
CP version is v6.01.00381.dev
FS19 is 1.5.2.1 (21150/28545) - latest on the Epic Launcher as of writing this.

**Comment by celendis** [comment]
Issue also arises if simply pressing 'control' on the keyboard. Courseplay also no longer attempts to raise or lower any implements during a row turn.

**Comment by Tensuko** [comment]
Collecting all in #5484
