### ISSUE TITLE
Error: Running LUA method 'draw' from the editor when saving

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#4955]
Wen ich einen Kurs generiert habe und ihn dann mit dem Editor bearbeitet habe und dann die tastenkombination zum speichern drücke kommt dieser fehler:

Error: Running LUA method 'draw'.
F:/LS19_Mods/mods/FS19_courseplay/course_management.lua:782: bad argument #1 to 'pairs' (table expected, got nil)

[log.txt](https://github.com/Courseplay/courseplay/files/4213483/log.txt)

MFG Mannie313

**Comment by Tensuko** [comment]
Hast du nach dem generieren den Kurs vorher normal gespeichert ?

**Comment by Mannie313** [comment]
Du meinst das spiel gespeichert nein. Habs auch dann sorum probiert kommt immer diese fehlermeldung.

MFG Mannie313

**Comment by Mannie313** [comment]
Die geänderten kurse werden nicht gespeichert.

MFG Mannie313

**Comment by Tensuko** [comment]
- Kurs erstellen
- Kurs speichern
- Editor starten
- Editieren
- Strg+F6 zum edit speichern

**Comment by Mannie313** [comment]
sobald Strg+F6 kommt diese fehlermeldung. egal ob ich am anfang den kurs ändere oder später.

MFG Mannie313

**Comment by pvaiko** [comment]
@russbeuker

**Comment by Mannie313** [comment]
hab mal einen neuen spielstand angefangen. und da kommt auch dieser fehler.

for k, v in pairs(cp_course.waypoints) do

das steht in der zeile 782.

MFG Mannie313

**Comment by Mannie313** [comment]
Vor dem Bearbeiten
![fsScreen_2020_02_17_16_27_00](https://user-images.githubusercontent.com/3021040/74666989-cd59fd00-51a2-11ea-9aeb-6cd1fad3ce46.png)


Nach dem Bearbeiten
![fsScreen_2020_02_17_16_27_19](https://user-images.githubusercontent.com/3021040/74666996-d0ed8400-51a2-11ea-8d9c-c8b8e13fb851.png)

MFG Mannie313

**Comment by Tensuko** [comment]
Ich kann es nicht reproduzieren.
Der Editor läuft wie er soll:
Vorher:
![fsScreen_2020_02_17_18_09_18](https://user-images.githubusercontent.com/27344744/74674030-c5a15500-51b0-11ea-947d-31c7c56c5a43.png)
Nachher:
![fsScreen_2020_02_17_18_09_33](https://user-images.githubusercontent.com/27344744/74674036-c934dc00-51b0-11ea-85a1-e604b079f255.png)

**Comment by Mannie313** [comment]
Mit der Autodrive version 1.0.7.0-38 geht es.
Mit der Autodrive version 1.0.7.1 geht es nicht mehr.

MFG Mannie313

**Comment by Tensuko** [comment]
Dann haben wir den Übeltäter.
Da muss sich etwas geändert haben was course_management.lua nicht mag.

**Comment by Tensuko** [comment]
Versuch das ganze richtig miteinander zu verlinken: https://github.com/Stephan-S/FS19_AutoDrive/issues/1094

**Comment by Mannie313** [comment]
ok Danke

MFG Mannie313

**Comment by Mannie313** [comment]
Hab nen neuen Spielstand angefangen bis jetzt ging es wieder. mal sehen was die zeit bringt.

MFG Mannie313

**Comment by Tensuko** [comment]
Was hast du denn alles gemacht, bevor das kam ?
Weil Kurs erstellen, Kurs speichern, Kurs ändern schien ja zu gehen anfangs.

**Comment by Mannie313** [comment]
Ich hab alle Mods wieder rein wo ich brauche. Aber ich hab ein weg gefunden trotzdem den geänderten Kurs zu speichern. 
1 Kurs erstellen
2 Kurs editieren
3 Kurs normal speichern

MFG Mannie313

**Comment by Tensuko** [comment]
Ist ein guter Tipp, dass das auch so geht. Ohne strg+F6 :)

**Comment by Mannie313** [comment]
Ja geht sogar sehr gut.

**Comment by Goof245** [comment]
Getting something similar, only it's every time I mouse over a waypoint, making the editor entirely unusable...
[editor broken.txt](https://github.com/Courseplay/courseplay/files/4613033/editor.broken.txt)
`2020-05-12 12:12 Error: Running LUA method 'draw'.
2020-05-12 12:12 C:/Users/ayoun/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay6/courseeditor.lua:568: bad argument #3 to 'format' (number expected, got nil)` over and over, and the GUI vanishes. Moving the mouse off the waypoint restores the GUI and the messages stop.
![20200512121200_1](https://user-images.githubusercontent.com/3851003/81631573-7daa6b00-944b-11ea-8e43-06e93b0b0594.jpg)
![20200512121203_1](https://user-images.githubusercontent.com/3851003/81631586-81d68880-944b-11ea-917d-356fb9a54965.jpg)

EDIT: It's happening on courses that were generated by AD and sent to CP, the editor appears to work fine for pure CP courses...

**Comment by Goof245** [comment]
Maybe it's missing speed data or something?

**Comment by Goof245** [comment]
Hmm, if CP treated waypoints with nil speed data as "auto" speed, I wonder if that'd help things.

Might also fix CP completely failing to follow high speed AD courses.....

**Comment by Tensuko** [comment]
This is becouse the course is not rly saved, it is generated. What happens if you save the course under a new name ?

**Comment by Goof245** [comment]
Same behaviour as far as I can tell. Loaded an AD course, saved it, cleared current course and reloaded the saved CP version, still get the same error when mousing over the waypoints.

**Comment by Goof245** [comment]
If it helps, in CourseManager.xml it was saved as
`<slot fileName="courseStorage0094.xml" id="142" parent="0" isUsed="true" name="test"/>`
In courseStorage0094.xml
```
<course>
    <waypoint1 speed="0" angle="-90.93" pos="-96.46 98.61 -502.15" crossing="1"/>
    <waypoint2 speed="0" angle="-84.46" pos="-99.55 98.82 -502.20"/>
    <waypoint3 speed="0" angle="-79.63" pos="-102.85 99.09 -501.88"/>
    <waypoint4 speed="0" angle="-77.14" pos="-106.95 99.27 -501.13"/>
    <waypoint5 speed="0" angle="-70.66" pos="-110.06 99.25 -500.42"/>
    <waypoint6 speed="0" angle="-67.59" pos="-115.90 99.27 -498.37"/>
    <waypoint7 speed="0" angle="-67.59" pos="-127.20 99.49 -493.71"/>
    <waypoint8 speed="0" angle="-69.23" pos="-131.59 99.49 -491.90"/>
    <waypoint9 speed="0" angle="-69.23" pos="-134.49 99.50 -490.80" crossing="1"/>
</course>
```

**Comment by Tensuko** [comment]
What happens if you change the speed manualy ?

**Comment by Goof245** [comment]
Changing speed in the xml to 1 for all waypoints works, lets me then edit the course ingame.
Leaving the speed at '0', but adding `generated="true"` to the initial `<course>` tag also appears to work, the waypoints then show as '0 KPH' in the editor and let me edit the course.

**Comment by Goof245** [comment]
Also, generating course in AD, saving the course, clearing the course, then loading the course in CP throws the error.
*However*, generating course in AD, saving the course, clearing the course, **reloading courses in CP** then loading the course in CP works, the editor shows the waypoints as 0KPH and lets me edit them.
