### ISSUE TITLE
Occasional game crash when a course is completed. (Reached End Trigger)

### ISSUE THREAD

**Issue by EradicationGod** [Courseplay/courseplay#4956]
Dear Dev(s),

I have only one annoying bug when using Courseplay v6.0.385 for FS19.

Occasional, more often than not, when a course is completed (blue message showing Reached End Trigger) and I need to switch to said vehicle, the game will freeze/crash. I can only use task manager to end task and then restart the game.

Error shown constantly : 

dataS/scripts/vehicles/Vehicle.lua (1703) : getParent
2020-02-17 20:07   dataS/scripts/vehicles/specializations/Suspensions.lua (259) : getParentComponent
2020-02-17 20:07   dataS/scripts/vehicles/specializations/Suspensions.lua (276) : setSuspensionNodeCharacter
2020-02-17 20:07   dataS/scripts/vehicles/SpecializationUtil.lua (30)
2020-02-17 20:07   dataS/scripts/vehicles/specializations/Enterable.lua (621) : raiseEvent
2020-02-17 20:07   dataS/scripts/BaseMission.lua (1881) : enterVehicle
2020-02-17 20:07   dataS/scripts/utils/Utils.lua (381) : oldFunc
2020-02-17 20:07   dataS/scripts/FSBaseMission.lua (3243) : onEnterVehicle
2020-02-17 20:07   dataS/scripts/vehicles/VehicleEnterResponseEvent.lua (66) : onEnterVehicle
2020-02-17 20:07   dataS/scripts/network/Connection.lua (77) : run
2020-02-17 20:07   dataS/scripts/vehicles/VehicleEnterRequestEvent.lua (68) : sendEvent
2020-02-17 20:07   dataS/scripts/network/Connection.lua (77) : run
2020-02-17 20:07   dataS/scripts/BaseMission.lua (1852) : sendEvent
2020-02-17 20:07   dataS/scripts/utils/Utils.lua (393) : oldFunc
2020-02-17 20:07   dataS/scripts/BaseMission.lua (1384) : requestToEnterVehicle
2020-02-17 20:07   dataS/scripts/BaseMission.lua (2595) : toggleVehicle
2020-02-17 20:07   dataS/scripts/input/InputEvent.lua (100) : callback
2020-02-17 20:07   dataS/scripts/input/InputBinding.lua (3202) : notifyInput
2020-02-17 20:07   dataS/scripts/input/InputBinding.lua (2924) : updateInput
2020-02-17 20:07   dataS/scripts/main.lua (1871) : update
2020-02-17 20:07 Warning (script): 'getParent': Argument 1 has wrong type. Expected: Int. Actual: Nil 
2020-02-17 20:07   ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (882): expectedType == Value::VoidType || expectedType == Value::ClassType
2020-02-17 20:07 LUA call stack:
2020-02-17 20:07   dataS/scripts/vehicles/Vehicle.lua (1703) : getParent
[log1.txt](https://github.com/Courseplay/courseplay/files/4215827/log1.txt)

log.txt wil be included.

**Comment by Tensuko** [comment]
You have some Errors in your Mods:
Error: Invalid mod name 'guidanceSteering-master'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

I haven't check all Mods, but be sure there is only one Map inside the Modsfolder.

I don't see a reason to alt+f4 the game, but I will check on that one.
It looks a bit like you had a Harvester running with self Unload active, is it ?

**Comment by EradicationGod** [comment]
Dear Tensuko,

I have replaced the 'guidanceSteering' mod with the latest release.  After
reading your mail I checked this mod and indeed I had the 'gs-master'
version from Github.
Although in all fairness, this mod worked properly and as expected in game.

Answer to your next question, no I did not have a harvester running at all,
at this point in my game I don't even own a harvester.
It happened constantly in v.380. Now I have updated Courseplay to v.385 and
it seems to happen a lot less,
but occasionally it still happens on random. I just started a fresh map on
'Sussex Farm' map with seasons and most realism mods enabled.

In all cases it happens with a tractor and a lime spreader or a plough or a
seeder. Pretty much all implements while preparing fields, have caused the
game to freeze up when a course had finished.
At the moment I'm not even close to my first harvest. But because it is so
random, the only constant is the tractor used, although I use two different
Massey Ferguson tractors, the brand is the same.
Other than that, imho it just happens at random. Although I'm sure there
are more errors and false positives in my mods list and logs.txt, none have
seemed to mess up my game so far.

I have a general rule when it comes to mods I use, they need to function
properly in game without errors or else I delete the mod instantly. I have
a lot of pc experience, but alas little understanding of coding or
scripting,
which is why mostly I don't even bother trying to fix it myself. But
Courseplay is such a fine piece of art and so needed in game, I would like
to get this sorted, not just for me, but for all others that possibly might
have similar issues. Keeping Courseplay as the best mod out there.....

Thank you and hope to hear from you again, if you might need more specific
information to help you speed along this issue or need help testing other
issues, please let me know, always happy to help.

Keep it up....

EradicationGod


Op di 18 feb. 2020 om 07:08 schreef Tensuko <notifications@github.com>:

**Comment by pvaiko** [comment]
None of these errors are from Courseplay itself, those are standard game scripts. 

I see a few when CP tries to register, for the towbar and the Volvo FH16 mod.

The only thing you can do is figuring out which mod is causing the problem by trial and error.

**Comment by Tensuko** [comment]
Closed since there is no Issue from CP.
Check your Mods wich one cause the Problem.

**Comment by EradicationGod** [comment]
Well it is, I don't know what else to tell you.

I tried a clean basegame (vanilla) with just CP running as mod. I still get this issue with vanilla equipment.

The peculiar thing is that it only happens after the course a ended a while and the engine gets shut off. Whenever I change to that particular vehicle, AFTER the engine has turned off, then it will crash the game and a CTRL+ALT+DEL is necessary to restart the game.

I also discovered a new bug, perhaps I should open a new issueform for that.
It unrelated and has to do with implements that have covers on them.

Hopefully with this new info you might be better suited to find this pesky bug.

Thank you again for a great mod otherwise.

**Comment by Tensuko** [comment]
Did you reinstall your game and reset settings too ?

**Comment by pvaiko** [comment]
@EradicationGod do you have the log from this (with no other mods)?

**Comment by EradicationGod** [comment]
No, I deleted it already, but I could start a new game and a clean log.txt if you like....no problem.

Please let me know...

**Comment by pvaiko** [comment]
If you don't post the log we can't fix it...

**Comment by EradicationGod** [comment]
Tensuko, no I did not.... I have over 20Gb of mods installed.... 

After many issues with not just CP, but also other mods I Hvae restarted so many times in the last week, I'm at the point of giving up and throw the game in a closet or something.... It gets too boring to keep starting over and over and over again. 

It's a lot of work and time that goes into modding and setting things up properly.
I'm not prepared to spent so much time on reinstalling/resetting a game, when there is not much going on, but some pesky bugs. In all fairness, it happens to the vanilla vehicles as well, not just modded stuff.(Just saying, not blaming anyone, these things happen)

After all these years, I think Giants should be embarrassed with them self, if they would help you guys along and implement basic frameworks for modding and scripting(like GlobalCompany just did) a lot of frustration and buggyness would have been spared.

Thank you

**Comment by EradicationGod** [comment]
pvaiko,

I'm on it.... plz give me a day or two....

I need some time to get this done..... currently there is some national holiday going on and things are a bit crazy over here..... 

But i'm on it....
