### ISSUE TITLE
suggestion for sharp turns

### ISSUE THREAD

**Issue by evybart** [Courseplay/courseplay#4957]
Is it possible for only the headland rounds the selection sharp turns be activate en when the headlands are done fluently turns activate

**Comment by pvaiko** [comment]
@evybart no idea what the suggestion is, try describing it a bit more clearly, what is the problem you are trying to solve and how exactly. It is ok if it is more than one sentence :)

**Comment by evybart** [comment]
its ok my mistake cp do it al ready what i propose can be closed
