### ISSUE TITLE
Mode 10 Autodrive

### ISSUE THREAD

**Issue by Tombarkemeyerbruns** [Courseplay/courseplay#4958]
Moin ist es möglich das Courseplay im mode 10 die Autodrive fahrer erkennt das die denn warten.

**Comment by Tombarkemeyerbruns** [comment]
> 
> 
> Moin ist es möglich das Courseplay im mode 10  die Autodrive fahrer ernnt das die anhalten

**Comment by Tombarkemeyerbruns** [comment]
> 
> 
> Moin ist es möglich das Courseplay im mode 10 die Autodrive fahrer erkennt das die denn warten.



> 
> 
> Moin ist es möglich das Courseplay im mode 10 die Autodrive fahrer erkennt das die denn warten.

**Comment by Tensuko** [comment]
@Stephan-S Frag mich nicht welche Schnittstelle das ist...
An sich sollen CP Fahrer (Mode1, Mode6 und irgendwann Mode2) sich mit dem Mode8 Fahrer unterhalten und warten bis der Mode8 Fahrer seinen aktuellen Zyklus beendet hat und zum Wartepunkt fährt.

**Comment by Stephan-S** [comment]
Mode10 ist welcher genau? Bzw. Auf was oder wen sollen AD Fahrer warten? Danke für die Infos :-)

**Comment by Tensuko** [comment]
Silo Verteilen/Verdichten/Aufschütten.
Also im Grunde der Fahrer, der das Silo platt macht :)

**Comment by Stephan-S** [comment]
Ich kann gerne eine Schnittstelle bereitstellen, die einen aktiven Fahrer pausieren/abbremsen und warten lässt. 
Dann wäre es aber in CPs Verantwortung in der Umgebung nach AD Fahrern zu suchen und diese Funktion zyklisch aufzurufen.
Ich kann noch eine convenience Funktion einbauen, die angibt, ob der aktuelle Fahrer auf dem Ziel zu einem Ablassziel in der Nähe des anfragenden CP Fahrers ist

**Comment by Tensuko** [comment]
@pvaiko

**Comment by Tombarkemeyerbruns** [comment]
Soll ich das jetzt zu machen weil es nicht weitergeht?

**Comment by Tensuko** [comment]
Du könntest auch einfach abwarten :)

**Comment by Tombarkemeyerbruns** [comment]
ok

**Comment by sdl112** [comment]
Wenn es hier weiter geht, wäre es evtl möglich, dass der CP Mode10 Fahrer nur auf Abfahrer reagiert, die Ihn betreffen? Also, ich denka da an die selbe variante wie mit dem Drescher. Bei dem M10 CP Driver stellt man z.b. "Silo1" Abladepunkt in AD ein, schaltet AD jedoch nicht an. Dann bearbeitet er mit CP das Silo (aufschütten, verteilen) und sobald ein Abfahrer in Reichweite kommt, der auf AD Kurs "Silo 1" ist, fährt er auf die Seite.
Somit wäre es möglich, mehrere Silos parallel zu befüllen, oder andere Arbeiten mit AD/CP auf dem Hof auszuführen.

**Comment by Tombarkemeyerbruns** [comment]
Ja so wäre das Perfekt

**Comment by Merrlin** [comment]
Hmpf @Tombarkemeyerbruns lass doch das issue bitte auf sonst kommt man durch einander oder es wird vergessen

**Comment by Tensuko** [comment]
Und kann mir mal einer sagen was nun das Problem ist ?

Ich zitiere mal die Changelog von Version 00032:

Level/compact: hold AutoDrive vehicles

Also kann hier auch zu!
