### ISSUE TITLE
ShovelModeAIDriver vs GlobalCompany Triggers

### ISSUE THREAD

**Issue by KCHARRO** [Courseplay/courseplay#4960]
I don't know if it will be a problem, but in ShovelModeAIDriver, CoursePlay does not detect the GlobalCompany triggers, when approaching the loading point it lowers the shovel and starts to circle to the right, and in some cases when it loads, it goes to the discharge point and It stops when it reaches the download point, and enters standby mode because it does not detect the download trigger.

    CoursePlay: 6.01.00385
Wheel Loader: CLAAS Torion 1914
           Shovel: MAGSI Wheel Loader Shovel
              MAP: Slovak Village
        Location: Quarry(stone, soil and gravel charge and discharge triggers)

In the manure and solid fertilizer maker, he correctly loads the shovel, goes to the discharge trigger and stops just like the previous case.

in Log no errors, only ""Waiting for Trailer""

**Comment by Tensuko** [comment]
It is funny how ppl think they only got to post the log where there is an Error.
You can see way more Stuff. Just for your Information.

Anyway, Screenshot with all waypoints on (CP Hud Settings) so I can see how you created the course.

**Comment by Tensuko** [comment]
Closed due to inactivity.
