### ISSUE TITLE
Tractor attachment working width issues

### ISSUE THREAD

**Issue by TheChiliDogger6** [Courseplay/courseplay#4961]
Hello,

This just started happening today. First screenshot is a tracker that is calculating the attachment width correctly, but it is offset. The second screenshot is my other tractor, but the same model and brand. As you can see, it is correct. This is causing this tractor to miss strips on the fields. Both tractors have the same attachment and field loaded.

Is there something I am missing in the settings for this tractor? I tried different attachments with same result. It's just this tractor.

Thanks for the help!

<img width="779" alt="Offset" src="https://user-images.githubusercontent.com/61202102/74760176-3e4af480-5237-11ea-864f-74fe8bdef260.png">
<img width="762" alt="Correct" src="https://user-images.githubusercontent.com/61202102/74760182-40ad4e80-5237-11ea-9f29-e5528c55a1b8.png">

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/releases

https://github.com/Courseplay/courseplay/wiki

**Comment by TheChiliDogger6** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4220725/log.txt)

Ravenport

Mods used:
Disable Vehicle Camera Collision
Follow Me
Placeable refill tank
Vehicle Inspector
Guidance steering
Fermenting Silo T500

**Comment by TheChiliDogger6** [comment]
V 6.01.00385

**Comment by Tensuko** [comment]
In your screenshot is not Version 385.
So did you try it again with newest Version ?
Couse I did just now create a course and let the driver seed my field and all is fine :)

**Comment by Tensuko** [comment]
Load mod: courseplay (Version: 6.01.00378) (Hash: cf91013f5aabb18e57bd4d71a3d330de)
Load mod: Courseplay_6_01_00385 (Version: 6.01.00385) (Hash: a59d8e9f20ac0dd4304c80f2037b2326)

...........delete old CP Version 1st.......

**Comment by TheChiliDogger6** [comment]
It was with 378 the first time. I then updated it to 385 and still had the issue. I have two Case 7210 Pro tractors. One does just fine whether its seeding or cultivating etc. The other one has the width offset.

**Comment by Tensuko** [comment]
Did you delete the old Version ?

**Comment by TheChiliDogger6** [comment]
Yes I did

**Comment by pvaiko** [comment]
@TheChiliDogger6 so why don't you just reset the offset? The tool offset is set automatically for example when using a plow and we have an issue not resetting it when the implement is changed.

Until that is fixed, just go to the fieldwork settings and reset the offset.

**Comment by TheChiliDogger6** [comment]
Thank you for your help!

**Comment by Tensuko** [comment]
Don't rly see an Issue here, just click the calculator and it is back to the right one. Same should work for Offset and stuff (I know sometimes seed usage calculator comes up but thats another problem.....)
