### ISSUE TITLE
Can not use CoursePlayer editor while in AGCO 1000 series tractor

### ISSUE THREAD

**Issue by chickenedFry** [Courseplay/courseplay#4962]
I have AGCO 1000 series mod 2.0v (First selection in large tractors in game modhub). Inside tractor mouse is constantly getting fixed into center of screen while Courseplay editor is open thus not allowing me to do anything with mouse.

**Comment by Tensuko** [comment]
Does the tractor have IC Control ?

**Comment by russbeuker** [comment]
This behavior is as designed.  Please do not use the editor from inside the tractor.

**Comment by RalfGorden** [comment]
that's because of the IC controls, I took them out

**Comment by chickenedFry** [comment]
Hey guys. Yes it was because of IC which I wasn't aware of. I removed IC  controls from xml and it works now, sorry for bothering you.

**Comment by chickenedFry** [comment]
> 
> 
> This behavior is as designed. Please do not use the editor from inside the tractor.

It did glitch even outside of cabin.
