### ISSUE TITLE
Turn manouver, implement collides on turn

### ISSUE THREAD

**Issue by frm274** [Courseplay/courseplay#4964]
Hi,

i know, that implements like sprayers may collide while turning.
So, i added for a test implement 'workTool.cp.widthWillCollideOnTurn = true;' in specialTools.lua
I was happy to see, that the tractor was pulling back now, before starting the turn.
But then, the tractor is not instantly starting the turn and heads forward again. Turning at the position like it has not reversed.

Adding a few pics. What debug channels could i activate to make this easier to understand?
<a href="https://abload.de/image.php?img=fsscreen_2020_02_19_1rek0h.png"><img src="https://abload.de/thumb/fsscreen_2020_02_19_1rek0h.png" /></a> <a href="https://abload.de/image.php?img=fsscreen_2020_02_19_16ij4y.png"><img src="https://abload.de/thumb/fsscreen_2020_02_19_16ij4y.png" /></a> <a href="https://abload.de/image.php?img=fsscreen_2020_02_19_1fij56.png"><img src="https://abload.de/thumb/fsscreen_2020_02_19_1fij56.png" /></a> <a href="https://abload.de/image.php?img=fsscreen_2020_02_19_120ke8.png"><img src="https://abload.de/thumb/fsscreen_2020_02_19_120ke8.png" /></a> 

1. Stops working, start heading backwards
2.Stops, should turn now, but:
3.Heads (in a minimal angle) forward
4.Tries turning and collides

![fsScreen_2020_02_19_19_06_50](https://user-images.githubusercontent.com/24813263/74861812-4300cd00-534b-11ea-8c71-40380e27e68d.png)

**Comment by Tensuko** [comment]
We can't even see what CP Version you use, your screenshots are in a bad resolution (why not drag and drop them into comment box ?)
There was a big update on turns at V385.
Else helpful channels are 7 9 12 and 14, also the information if you turned on AI turn and pathfinding.

**Comment by pvaiko** [comment]
Just as a heads up: that workTool.cp.widthWillCollideOnTurn = true (and probably the whole specialTools.lua) is deprecated and will go away in this form sooner or later.

**Comment by frm274** [comment]
Version == newest.

deleted: workTool.cp.widthWillCollideOnTurn = true 

Recorded one turn with given Channels

![fsScreen_2020_02_19_20_28_29](https://user-images.githubusercontent.com/24813263/74868529-b1975800-5356-11ea-8ed1-7fc88c5ec753.png)
![fsScreen_2020_02_19_20_28_14](https://user-images.githubusercontent.com/24813263/74868536-b3f9b200-5356-11ea-8f52-678e22286318.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4226983/log.txt)

**Comment by Tensuko** [comment]
Old version, turns had some changes, will close this one.
