### ISSUE TITLE
Grimme Rootster 604 cannot harvest

### ISSUE THREAD

**Issue by OleKullmann** [Courseplay/courseplay#4965]
For the documentation of this problem, I used Ravenport field 10, which is pre-sown with sugarbeets.
I took a tractor with the Grimme FT300 in front and Grimme Rootster 604 after and drove to the field. Starting in the SW corner, I generated a course with a Headland count of 5. No other changes in Course generation. CP mode was set to Fieldwork.
At first, I let the tractor drive with the FT300 alone. No problem.
Then, I switched to the Rootster 604 and tried to start it from 1st point. The Rootster was lowered and started working as expected, but the tractor did not move as it should.
Additional information:
Tried with the FT300 in front also. Did not help.
Tried in mode Transfer. Activated the Rootster manually (keys B and V). The tractor ran off and harvested in an incredible speed, but of course it did not stop at full tank.
Tried the same course with a Ropa Panther 2. It harvested quite well.
I have tried various fields and various tractors, but CP failed to harvest with the Rootster in all cases.
Harvesting manually with the Rootster works fine.
I will be happy to provide additional information, if required. So far, I can only think of the giant log file. [log.txt](https://github.com/Courseplay/courseplay/files/4231660/log.txt)
Best Regards,
Ole

**Comment by Tensuko** [comment]
Just tested with v 02.00040 and works just fine.
