### ISSUE TITLE
drive course / stop driver assigned key works only partly

### ISSUE THREAD

**Issue by OleKullmann** [Courseplay/courseplay#4966]
I have recently switched to FS19, but with loads of experience with FS15 and FS17, I installed CoursePlay right away. And at the very first run, I noticed that Right Ctrl + Keypad 4 did NOT make the tractor drive the specified course. It only turned on the light as Keypad 4 ALONE is set up to do.
Funny though, when the tractor IS driving a course and I press Right Ctrl + Keypad 4, CP DOES stop the driving as expected.
At first, I thought it was a conflict with another mod.
However, today I tried running FS19 with only the Courseplay mod checked in. The error persists.
Whether this is a CP bug or FS19 bug, I don't know. What do you say?
If you need a log to study, you can find it in issue #4965
Best Regards,
Ole

**Comment by Tensuko** [comment]
Welcome to the Collection: #4826

Closed.
