### ISSUE TITLE
Double course lines displayed

### ISSUE THREAD

**Issue by OleKullmann** [Courseplay/courseplay#4967]
While working on the documentation of issue #4965, one of my tractors suddenly started showing the course twice. One 5 meters above the tractor and an identical 10 meters above (see attached screen shot).
The error was only related to one of my tractors, but to all the courses I loaded for that tractor.
I was able to cure the problem by resetting the tractor.
![Double course lines](https://user-images.githubusercontent.com/24568300/74955997-bd8e2300-5405-11ea-84dd-47740c1cffcc.jpg)

**Comment by Tensuko** [comment]
the little DBG icon on the top left is on and it is not an Error...
