### ISSUE TITLE
Problem mit symmetrischem Bahnwechsel

### ISSUE THREAD

**Issue by Michael170978** [Courseplay/courseplay#4968]
Hi.

Ich hab leider Problem mit dem symmetrischem Bahnwechsel.
Am Besten schaut euch das Video an. Da kann man das Problem gut sehen.

Es geht darum, dass der zweite Schlepper die Bahn nicht wechselt.
Der erste Schlepper macht wiederum keine Probleme. Vielleicht sind meine Einstellungen falsch. Dann würde ich euch bitten mir zu erklären wie ich einstellen soll.

https://youtu.be/5Lh2bv1Xu3o

**Comment by Tensuko** [comment]
Symetrischer Bahnenwechsel, Links wechselt auf rechts, rechts wechselt aber nicht auf links.

Kannst du ein logfile mit Debugchannel 9 12 und 14 erstellen und in der Kommentarbox anhängen ?

**Comment by Michael170978** [comment]
> Symetrischer Bahnenwechsel, Links wechselt auf rechts, rechts wechselt aber nicht auf links.
> 
> Kannst du ein logfile mit Debugchannel 9 12 und 14 erstellen und in der Kommentarbox anhängen ?


Hab noch nie mit Debugchannel gearbeitet, deshalb reißt mir bitte den Kopf nicht ab falls ich falsch gemacht habe.
Zur Info: New Holland wechselt als Erster.  Der Fendt folgt ihm hinterher. Heißt aber nicht, dass das Problem immer bei dem zweiten Schlepper auftritt. Beim Mähdrescher trifft das Problem auch auf. Alle Maschinen sind original

![image](https://user-images.githubusercontent.com/53015927/74965744-106fd680-5416-11ea-804d-736ee7e60d3e.png)
![image](https://user-images.githubusercontent.com/53015927/74965780-1d8cc580-5416-11ea-9298-c3772bb46c9b.png)

**Comment by Tensuko** [comment]
An sich hast du das schon richtig gemacht, aber die log.txt Datei musst du noch anhängen (Liegt da wo auch ein mods Ordner ist) und genau wie die Bilder anhängen bitte.
Also: Debugchannel an, Kurs laufen lassen, so dass das Problem auftritt und dann das logfile anhängen.

**Comment by Michael170978** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4232432/log.txt)

Bitte schön

**Comment by Tensuko** [comment]
Du solltest deine log mal durchgucken, da sind einige Mods die Fehler werfen. Sei es in der ModDesc oder das .zip file selber.

**Comment by Michael170978** [comment]
Die meisten Fehler spuckt der scheiß Autoloader aus. Aber damit kann ich leben. Ich würde mich aber nicht wundern, wenn du mir sagen würdest Courseplay funktioniert nicht richt weil ich Class DLC nutze. Autodrive hatte auch so seine Probleme aber Stephan hat sie behoben.

**Comment by Tensuko** [comment]
Mit dem Claas DLC hat das bei CP nichts zu tun. Ich nutze selber viele Claas Tools und Drescher. Aber ja, der Bahnwechsel ist im moment Fehlerhaft.

Die Errors waren auch nur ein Hinweis für dich, weil ein sauberer mods Ordner wichtig ist (einige Mods haben nen Error bei dir, wie ich sagte).

Eine log mit Infos hilft, heist aber nicht das es sofort behoben wird. Daher muss man leider warten.

Funktioniert denn der asymetrische Bahnwechsel ? Also deaktiviert ?

**Comment by vemendoza** [comment]
So, I can't use this version.

For this case, I'm using CP v6.01.00355, that 5 combines works perfect. (I only need to change CP to this old version)

Thank you for your great job.

**Comment by pvaiko** [comment]
Sorry folks, there is a big fix for the multi tool problems is in the works, until then, try with 386.

**Comment by Michael170978** [comment]
Das Problem ist beseitigt. Vielen Dank für die den schnellen Support. Ihr macht echt einen super Job. Großen Respekt habt ihr verdient. Meinetwegen könnt ihr mein Ticket zu machen.

english: The new version fixed my issue.

**Comment by vemendoza** [comment]
Hello guys,

With this version my five combines is working perfect.
Thank you for your great and speed job.

**Comment by pops64** [comment]
@pvaiko Judging by the video alone it looks like what use to trigger the flip of the offset isn't on. Last I looked at the code in 17 for symmetrical the lane assignment should change when entering the turn. The phrase 1 right should become 1 left and vice versa. But once again I haven't looked into 19s code in a year and half

**Comment by pvaiko** [comment]
you probably should look into it, especially after I push the multitool fix, the entire offset course will be generated when the vehicle starts.

**Comment by pops64** [comment]
@pvaiko I will do a deep dive into it but from what I understand from your comment is CP now generating a whole new course now or is still like the old way using offsets from the course?

**Comment by pops64** [comment]
So I have looked into it appears on first glance that AIturn.lua is missing.
```
--- Get the new turn target with offset
	if courseplay:getIsVehicleOffsetValid(vehicle) and turnContext:isHeadlandCorner() == false then
		courseplay:debug(string.format("%s:(Turn) turnWithOffset = true", nameNum(vehicle)), 14);
		courseplay:turnWithOffset(vehicle);
         end;
```

 This is the bulk of the code that updates the offset when turning it is one the first functions called with CPs turn code

Also `self.cp.switchLaneOffset` should be set to true prior to calling this function. This I believe was used to prevent multiple flips. Tho might not be needed anymore as this was more for mode 4 and 6 abort work calls. I would have to play with it some more to truly figure out what it does

**Comment by pvaiko** [comment]
@pops64 as I said, it is fully refactored, most of the code you pasted here does not even exists or used anymore, it is on my working branch.

**Comment by pops64** [comment]
Sorry, Yes it looks like your hot fixed this problem as self:generatePathfinderTurn() function does not appear to always call self:generateCalculatedTurn() which this function calls the old courseplay:turn() function which is where the code I pasted still exists in 386 and still active. 

My 2 cents on keeping this old way of doing it. Tho I am not to sure it still apply to FS19. 1 is simplicity. I only have to keep 1 course and then tell it which side of the course to run on.  Yes this becomes somewhat void when you go above 4 or more tools. The other which I know as always been a problem is file space. If you save theses course you take up more file space and there by increase load time. This is very prevalent in 15 and not so much in 17 but still achievable. I haven't looked at differences in file structure since 19 but in 17 I was trying to get Stassis to help with creating a on demand file system instead loading every course at game start.

**Comment by Tensuko** [comment]
Should work not as intended.
Test and report, thx.

**Comment by Tensuko** [comment]
This should be working fine now, if have more Issues with new Mutitool feature, make a new Issue.
