### ISSUE TITLE
Ropa Keiler

### ISSUE THREAD

**Issue by franky135** [Courseplay/courseplay#4969]
harvesting potatoes still has some issues:
-driving backwards in the fieldcorners makes problems because the ropa turns to left or right
-when its full it stops and lift the bunker and you can unload into a lorry but when its empty the cp-driver doesnt wait till you have driven away the lorry. he just start driving forward without harvesting and to start the harvester again you have to stop and restart him
-on mode 2 they dont find the ropa so its impossible to unload it by a cp-driver

just saying...

**Comment by Tensuko** [comment]
Mode2 is sill #3311 and #4286 
Come on guys you know this... its sticky for so long...

The other Problem is also written here (german, but the name is the same....) #4793
