### ISSUE TITLE
Using 5 combines whith symmetric lane change problem (v6.01.00385)

### ISSUE THREAD

**Issue by vemendoza** [Courseplay/courseplay#4970]
Hello guys and thank you for your last support.

So, I'm trying to use the latest version v6.01.00385, but if I try to use CP with 5 combines, the symmetric lane change doesn't work.

You can see in this example that I configure my combine to 2 Right lane. (symmetric lane is activated)

![Desktop Screenshot 2020 02 20 - 22 26 06 95](https://user-images.githubusercontent.com/48180617/74997004-d9102280-5433-11ea-8715-70644a324033.png)

 When de combine turns, CP not change it to 2 Left, and the combine continue with 2 Right again. 

![Desktop Screenshot 2020 02 20 - 22 26 40 53](https://user-images.githubusercontent.com/48180617/74997074-0a88ee00-5434-11ea-91b8-7590e5b4f304.png)

So, I can't use this version.

For this case, I'm using CP v6.01.00355, that 5 combines works perfect. (I only need to change CP to this old version)

If you need some log, can you tell me what chanel I need to activated...?

Thank you for your great job.

**Comment by Tensuko** [comment]
The same happens in #4968
right one stays on the right.

**Comment by pvaiko** [comment]
So, this is a dupliacate of #4968 and therefore closing it...

**Comment by Zoochase** [comment]
Symmetric stopped working when the button was fixed.  See Mode Specific Setting issues #4802

**Comment by denisok3635609** [comment]
У меня проблема с этой версией на силосной яме. После генерации маршрута и его запуска с любой точки, трактор опускает ковш и начинает двигать в бок. Не важно на полной яме это делаешь или на пустой. Может я делаю что-то не так?! Вот что могу предложить...
![Новый точечный рисунок](https://user-images.githubusercontent.com/61220323/75362596-69d27c80-58d2-11ea-81d7-59a9b6c5e5d9.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/4256766/log.txt)
