### ISSUE TITLE
Unload Acrusin Autostack

### ISSUE THREAD

**Issue by Lars-LS17** [Courseplay/courseplay#4971]
Hello Togehter,

i have a Problem to Unload the bales wit the Arcusin AutoStack. 
I have recorded a route that will take me backwards to the unloading point. This works perfectly 7 times. Then he no longer recognizes the bales and would like to continue resetting until they are unloaded.
![fsScreen_2020_02_20_18_39_04](https://user-images.githubusercontent.com/31773176/75042160-47012c00-54be-11ea-88c5-d4aff49a7182.png)

**Comment by pvaiko** [comment]
Currently it works only within 25 m of the unload point. But it is great to hear it works! What would be a reasonable limit?

**Comment by Lars-LS17** [comment]
Yes it Works perfectly!
 I Play on the Map Nordfriesischer Marsch 4x. 
When i have a field with 30ha. I need much more then 25m. 
It must be mandatory to specify a maximum distance?
Or can't you set a limit?

**Comment by Lars-LS17** [comment]
But when you need i maximum limit, then it will be perfectly like 50m :)

**Comment by Tensuko** [comment]
#5837 duplicate
