### ISSUE TITLE
Debug text still shown with mode 10 in "reverse unload" mode

### ISSUE THREAD

**Issue by TheDestroyerKSP** [Courseplay/courseplay#4972]
https://i.imgur.com/9F4qYt9.png

The debug text of self:drivePush (and Pull) is visible when mode 10 is set to "reverse unloading". Otherwise, the mode seems to work fine (does not display text in "filling up" and "compacting" mode.

Not sure if this means this mode is still under development, otherwise it would just be nice to have it go away since it is always there across all vehicles.

**Comment by Tensuko** [comment]
Should be gone, as I am testing v .00063
