### ISSUE TITLE
V601.00386 - Combine opens automatically when switch from mode5 to mode6

### ISSUE THREAD

**Issue by caplink811** [Courseplay/courseplay#4974]
This happens with version 6.01.00386.
Is this expected?

The combine opens (partiall) when switch from mode 5 to mode 6 (driving -> fieldwork), please see attached video for details. There is no entry in the logfile in the moment where I switch the modi.

To close the combine, I have to press X two times (assuming that the 1st press X complete the open commnd, the combine, 2 2nd is the close combine command)

thanks and bye
 JrB

https://1drv.ms/v/s!Aqt5msdvWb55h0QzKrfYyUfhOI2w?e=7TkXbj

**Comment by Tensuko** [comment]
Yes this is a forgotten testing 'feature' and nothing to worry about.
