### ISSUE TITLE
Sprayer (Hardi Rubicon 9000) dosent fold. Dedicated Root Server CP v6.01.00386

### ISSUE THREAD

**Issue by Justice-Molton** [Courseplay/courseplay#4975]
We play MP on our Server and we've just found out that the Hardi Rubicon 9000 doesn't fold its tool and doesn't stop working during a refill drive. It's working on its full working area and the collision is also there, but there's no animation for folding the sprayer frame. It's similar to the combine pipe issue that you've already fixed.

**Comment by AUZ001** [comment]
I can confirm that this also happens in Single Player using vanilla map Ravenport.

**Comment by Tensuko** [comment]
Collecting all in #5484
