### ISSUE TITLE
Infopanel flickers when a course is running with an implement that has a cover.

### ISSUE THREAD

**Issue by EradicationGod** [Courseplay/courseplay#4976]
Dear Dev(s),

(Courseplay v6.01.00385)
A new issue I came across a few days ago, which I can't seem to fix is the following; 

Whenever I record a course with an implement that has a cover on it, (e.g. Trailer with cover, Fertilizer with cover), everything works fine. After recording is finished, I run the course and then my infopanel/helppanel (the panel with all your buttons in it) starts to flicker/alter so fast it makes you dizzy if you keep watching it. Everything keeps working fine, but the menu is unreadable and unusable while the course is active. As soon as the course is terminated by the player, the panel returns to a normal and stable state and all is fine. 

It is so annoying, I started to play without this panel on-screen, which is a cleaner look, granted, but not always so useful. Especially when one has some issues in properly remembering a 4 dozen keys, including mods.....

Maybe also worth mentioning, whenever a course like this runs, it doesn't matter if the 
'Covers - automatic' option is on in CP. The covers stay in their last known position/state the player has left them in prior to starting the course. I.e. if I start a course with the covers open, they stay open while the course is running and they will not close 'automatically' although one might have the option enabled in CP. Same goes for a 'closed cover' state, they stay closed and don't open, even if it needs to load at a loadpoint in the course. I need to press 'stop driver', manually operate the covers and then press 'continue at closest waypoint' to resume the course. Which ofcourse, beats the entire purpose of this awesome feature in CP.

I tried a vanilla trailer with and without a cover, also the vanilla implements are affected by this issue whenever they have a cover on it, if there is no cover on it, there is no issue at all. Doesn't matter if it is modded are vanilla equipment. Both have thoroughly been tested. 
I even changed and then deleted the keybindings for anything with covers or flaps. Thinking it might be something with double-allocated-keybindings concerning covers. Doesn't fix it.
I tried several debug-channels in your CP mod, but it doesn't seem to do much or I don't know how to work those channels. 

I have tried for the last three days, changing keybindings, deleting keybindings, debug channels in CP, vanilla versus modded, cover versus no cover, trying to find stuff in my log.txt or checking xml's.

Not much to find by me, perhaps you guys wanna take a look at this, as your knowledge and experience is much vaster than mine.....

Enjoy your weekend otherwise and thank you for your awesomeness called CoursePlay 

Please help, if any more info is needed, please let me know.

**Comment by Tensuko** [comment]
logfile and a video of it.

**Comment by EradicationGod** [comment]
Dear Tensuko,

If you could tell me how to make a video of it.... I will make one.
But I never did make one before, so I don't know how to...

Logfile attached below...
[log.txt](https://github.com/Courseplay/courseplay/files/4243286/log.txt)

**Comment by EradicationGod** [comment]
Quick update,

I did a clean reinstall of the game and tried to recreate said issues.
I was unable to, so it surely is a mod conflict of sorts.

I will do some more research and get back at this issue later on
(Same goes for the issue #4956) 

Thank you anyway, keep it up the great work.

**Comment by EradicationGod** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4243717/log.txt)
[log_CleanInstall.txt](https://github.com/Courseplay/courseplay/files/4243719/log_CleanInstall.txt)

**Comment by EradicationGod** [comment]
Dear Tensuko, Pvaiko,

This flickering is caused by the 'covers addon' mod, where this mod makes it possible to open and close covers on implements manually when outside a vehicle. Not sure what exactly might cause an error, but there is most surely something going on between the 'covers' option in CP and this mod.

Thank you and hopefully it might help you guys later on.....
