### ISSUE TITLE
Planters / Seeders - Headland issue

### ISSUE THREAD

**Issue by HC1Gunner** [Courseplay/courseplay#4978]
Most maps have obstacles at the end of the their fields. I create a course to make 2 - 3 headland passes. But with the last few versions of CP, (currently using v6.01.00378), once the headlands have been planted, and CP starts making passes up and down the field, the tractor stops, lifts the planter where it should, but instead of immediately making a 180 turn like it used to, it now acts like there are no headlands for the course, drives to the end (edge) of the field, and then gets hung up on stuff every single pass.

**Comment by Tensuko** [comment]
Always use newest CP Version:
https://github.com/Courseplay/courseplay/releases

You also want to try out AI Turn and Pathfinder in Advanced Settings.

**Comment by Tensuko** [comment]
Closed due to inactivity.
