### ISSUE TITLE
Problem beim Miststreuerbefüllen im "Düngen und Säen" - Modus mit Schaufel

### ISSUE THREAD

**Issue by Borni1975** [Courseplay/courseplay#4980]
Hallo zusammen.
Als erstes Mal vielen Dank für diesen sehr hilfreichen Mod.

Ich habe folgendes Problem, wenn ich den Miststreuer im Düngen u. Säen Modus befüllen möchte.

Im Ls13 und Ls15 war es so das ich zuerst einen "Düngen und Säen" Kurs von dem jeweiligen Feld generiert habe, anschließend einen Abfahrerkurs vom Feld zum Ladepunkt, dort einen Wartepunkt gesetzte und wieder zum Startpunkt des zur düngendem Feldes zurück erstellt habe.
Beide Kurse habe ich miteinander verbunden.
Jetzt war es dann so, dass der Abfahrer, sobald der Miststreuer leer war, zum Ladepunkt gefahren ist und am Wartepunkt stehen geblieben ist, bis er von einem anderen Fahrzeug welches mit einem "Schaufel befüllen und entleeren"- Modus versehen war, befüllt würde und erst mit vollem Streuer zurück zum Feld gefahren ist.
Seit dem LS 17 funktioniert das aber mit dem Halten am Wartepunkt, bei mir zumindest, nicht mehr, so das mir nur die Möglichkeit bleibt, den Miststreuer mit einem Förderband oder Silo zu befüllen.
Mach ich da jetzt irgendetwas falsch oder hat jemand von euch eine Lösung, wie man es hinbekommt, den Miststreuer im "Düngen und Säen"-Modus mit der Schaufel zu befüllen?

Vielen Dank schonmal im Voraus
Mit freundlichen Grüßen Borni1975

**Comment by Tensuko** [comment]
Momentan nur durch ein Silo oder ähnlichem Trigger (ob Förderband geht weis ich nicht, habs nicht probiert).
Leider fehlt es an 'Manpower' um gewisse Sachen umzusetzen für den LS19, daher geht es im moment nicht anders.

**Comment by Borni1975** [comment]
Hall Tensuko.
Vielen Dank für Deine schnelle Antwort.
Hatte mir das so in etwa schon gedacht. Bei dem heutigen Fachkräftemangel, braucht man sich nicht wundern, wenn manche Sachen halt was länger dauern ;-) :-).
Würde mich ja gerne anbieten, aber wohl mehr als "Testfahrer" würde wohl dabei nicht raus kommen

**Comment by Tensuko** [comment]
Wenn wir eines genug haben, dann sind es Testfahrer :)
