### ISSUE TITLE
Error: Running LUA method 'update' - ShovelModeAIDriver.lua:439: attempt to index a nil value

### ISSUE THREAD

**Issue by RudiBergfeld** [Courseplay/courseplay#4981]
immer wenn iich die Fondladerarbeit von Cp386 einschalte Stürtzt das Spiel ab das ist mir erst seit der Version 386 aufgefallen. Vieleicht ein Bug?
[log.txt](https://github.com/Courseplay/courseplay/files/4249232/log.txt)

**Comment by Tensuko** [comment]
So with V385 all was fine ?

**Comment by RudiBergfeld** [comment]
MMM ich weiß es nicht? muss der Kurs neu eingefahen werden? Als ich den Kurs neu eingefahren habe war auch mit der Version 386 alles ok Die alten Versionen Haben Auch nichts gebracht. Ich habe 385, 384 und 383 getestet.

**Comment by Tensuko** [comment]
Hast du denn die Schaufelpositionen gespeichert ?
Muss man bei jedem Fahrzeug natürlich machne.
Ansonsten alle Wegpunkge an, Screenshot und Kurs mal zeigen.

**Comment by RudiBergfeld** [comment]
Ich habe die Schaufeleinstellungen gespeichert. Ich habe Heute die Bilder gemacht und da war alles Ok.
Alles gleich Die selbe Map die selben Mods und die Selbe Version386 Gstern muste ich den Kurs neu einfahren Heute nicht Oder ist das bei den Frondlader Kursen Version abhänig?
![Frondlader Kors](https://user-images.githubusercontent.com/10323527/75336143-e477a980-588a-11ea-9d27-a31d2287459d.png)
![Schaufel einstellungen](https://user-images.githubusercontent.com/10323527/75336171-f2c5c580-588a-11ea-8d15-ff24ab1829ec.png)
Ich habe Versucht den von mir eingefahrenen Kurs ein Screenshot zu machen ich hoffe du kannst etwas damit Anfangen

**Comment by Tensuko** [comment]
Sieht auf den ersten Blick erstmal nicht falsch aus was du da gemacht hast.
Ich probiere das mal selber mit der V386, ma gucken.

**Comment by Tensuko** [comment]
Ich konnte es gerade nicht reproduzieren.
Glaub du müsstest mal schauen, ob es an einer Mod liegen könnte.

**Comment by RudiBergfeld** [comment]
MMM wie soll ich das finden ich habe alle mods im 10 Pack getestet und habe keinen Fehler gefunden 
ich denke das behalte ich im Auge und wenn der Fehler erneut kommt melde ich mich. Wie gesagt Heute hatte ich keine Probleme. Aber danke das ihr euch gekümmert habt.

**Comment by lcc1211** [comment]
I think I am having a bit of a similar issue with 386. I created a shovel course for filling a manure spreader. It doesn't matter if I use a tractor with a shovel or a telehandler. The equipment will drive to the manure, pick it up and drive to the waiting manure spreader, but veers off course completely missing the target.

**Comment by RudiBergfeld** [comment]
Ich bin mir nicht sicher aber ich glaube das liegt am Gamepad ich habe es mal getauscht

**Comment by Tensuko** [comment]
Not sure what is the Problem here.
Closeing this and if there is something similar make a new Issue with discription and log etc.
