### ISSUE TITLE
Mouse cursor bug on some tractors. 

### ISSUE THREAD

**Issue by gruszon18** [Courseplay/courseplay#4982]
I checked new version, and older version also.. On some vehicle courseplay works fine, and at some mouse cursor start to bug, starts to disappear and always go to center of the screen.

**Comment by Tensuko** [comment]
no log, no info about tracktors... great... I make a forecast.... Tracktors with IC ?

**Comment by gruszon18** [comment]
Sorry, dont know the drill. 
So here is my log [https://www49.zippyshare.com/v/NA1WSa0F/file.html
](url)
One tracktor have IC-JD 6030 Premium. 
2nd idk about IC cause i dont use IC.  Its JD 8R (2016-2018) EU series .

**Comment by Tensuko** [comment]
You know the point is that we get several bug reports and most of them are user generated or conflict with other mods or some kind like that.
And without any more information then just 'This doesn't work' it won't help at all.
We also have a wiki for what we need: https://github.com/Courseplay/courseplay/wiki
(on the top of github).

Btw the links doesn't work.
The log can be added by drag and drop into comment box.
Also I don't know this zippyshare, I would prefer a YT, onedrive or similar upload for the video.

**Comment by gruszon18** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4256947/log.txt)
https://youtu.be/RLOIB9rlPGw

**Comment by Tensuko** [comment]
Also erstmal würde ich CP Updaten https://github.com/Courseplay/courseplay/releases

Dann gilt im LS eine wichtige Regel: Immer nur eine Map im mods Ordner.

Dann hast du LUA-Errors vom Load mod: FS19_animalsKeeper (Version: 1.0.0.5)
Und LUA Callstacks die KÖNNTEN von FS19_NH_cr890 kommen. (Sicher kann man sich da nie sein... Könnte auch sein das du einen Plarformtrailer an einem Traktor hast, dann wäre der Callstack egal :D ).

Und ab nun wirds es schwerer, es könnte eine Mod sein, die auch die Maus benutzt, bzw ein Konflikt mit Keybindings erzeugt, aber da bin ich mir halt nicht sicher welche das sein könnten.

Eventuell mal EnhancedVehicle updaten auf die 1.6.3.1 (MH) weiter weis ich im Moment auch nicht.

**Comment by gruszon18** [comment]
So this bug is made by some other mod. Ok, i will check that.

**Comment by Tensuko** [comment]
Oh god I am sry I just noticed that I exchanged the Issues in terms of language....
My bad sry that you had to translate it but yes you got the point.

Damn I had to be sleepy yesterday :s
