### ISSUE TITLE
neueste Version

### ISSUE THREAD

**Issue by Bandesss** [Courseplay/courseplay#4983]
Kein einloggen im Mulitiplayer möglich mit der 35er Version geht es.
Kann dies jemand bestätigen?

Greetz

**Comment by Justice-Molton** [comment]
Wir haben keine Probleme im MP mit einloggen.

**Comment by Bandesss** [comment]
https://github.com/Courseplay/courseplay/releases/tag/6.01.00386

Mit dieser komme ich nicht drauf

**Comment by Tensuko** [comment]
- Besserer Titel
- Log vom Client
- Log vom Server

Sonst mach ich hier dicht, weil wilde Spekulation über Serverprobleme passen nicht zum CP GitHub :)
