### ISSUE TITLE
augur wagon issues fs19

### ISSUE THREAD

**Issue by demonkiller69** [Courseplay/courseplay#4988]
i try to use augur wagons to transport between a harvester and my silo truck and it locks the game up and won't move, it will put on the beacon lights but locks the camera controls, keyboard and if i press esc to go to the menu the field map just scrolls and all of the information that is usually on the map is gone also if i press e to get out of the vehicle the game locks up and i have to alt+f4 to shut it down, but if i just have the auger wagon on and have courseplay set to drive a continuous loop it will keep running the course it locks up in either mode 1 or 2, also it is not just one auger wagon that it happens with it happens with all of them here is my log link. https://pastebin.com/Ne4QFWd4

**Comment by Tensuko** [comment]
See #3311 and #4286 
Mode3 stick to Mode2

**Comment by demonkiller69** [comment]
sorry to sound like a moron but which one is mode 2 now since all of the buttons on the bottom aren't selectable?

**Comment by Tensuko** [comment]
From left to right, just count.
1 2 3 4 .... up to Mode10.

**Comment by demonkiller69** [comment]
i have it on mode 2 but when i click to start courseplay with it as i said the beacon lights come on and it just sits there and i cant even move the camera like i can in any other vehicle and if i change vehicles the game locks and i have to alt+f4 it
