### ISSUE TITLE
 harvester does not stop when unloading at the end of the field

### ISSUE THREAD

**Issue by androno12** [Courseplay/courseplay#4989]
Hello. CS 00386. A harvester can hit the tractor when turning at the end of the field. But old versions Courseplay (April 2019) work fine. (google translator)
https://youtu.be/wtXXB0-KbjM

**Comment by Zoochase** [comment]
Asked already...
Combine not stopping at end of field while unloading #4702

**Comment by androno12** [comment]
thanks

**Comment by Tensuko** [comment]
Duplicate of #4702

Closed.
