### ISSUE TITLE
Abfahren mit 2 Dreschern/Rübenerntern

### ISSUE THREAD

**Issue by AngeloMerte** [Courseplay/courseplay#4990]
Hi,

Ich habe das Problem, dass ich den Kurs mit 2 Rübenerntern (Terra Dos) auf dem selben Kurs zwar generieren kann, die Fahrzeuge aber den Versatz nicht beachten. Ich habe einen auf links und einen auf Rechts gestellt, beide fahren aber exakt mittig, als wenn sie beide auf einem Solokurs unterwegs wären. Version ist die aktuellste.

**Comment by Tensuko** [comment]
Multitool fix kommt demnächst, aber ich werde das mal testen ob es mit gefixt ist.

**Comment by Tensuko** [comment]
Versuch mal bitte mit der neuesten Version und melde ob es klappt.

**Comment by Tensuko** [comment]
Sollte nun klappen, ansonsten noch einmal melden bitte.
