### ISSUE TITLE
Weiter arbeiten wenn Füllvolumen <=1%

### ISSUE THREAD

**Issue by RudiBergfeld** [Courseplay/courseplay#4992]
ist es möglich das der Cp Abfahrer seine Arbeit fortsetst obwohl eine Restmenge von der alten Frucht im Tailer oder Schaufel ist? Der Farmigsimmolator lässt Gerne mal eine Restmenge drinne  unter 1Prozent

**Comment by Tensuko** [comment]
Abfahrer heist jetzt welcher Modus ?

**Comment by RudiBergfeld** [comment]
Hauptsächlichist es mir bein arbeiten mit dem Frondlader Aufgefallen und auch beim Ablifern an eine Verkausstele wenn er nicht Komplet endläd dann macht er nicht weiter

**Comment by Tensuko** [comment]
Hmm poste bitte mal dein logfile. (Dragn and Drop in die Kommentarbox)

**Comment by RudiBergfeld** [comment]
Gerne kannst du die log haben ich glabe nicht das du dort was findest. Ich habe das mal Gegoogelt das poblem ist wol bekannt und ich denke das ist ein Bug oder Gewollt von Giantis es gibt einen Trik wenn ich das Fahrzeug oder Gerät zurück Setze dann ist es leer und mann kann die Arbeit fortsetzen ich habe schon mal Giantis angeschrieben aber bislang keine Antwort erhalten. Der Cp Fahrer denkt natürlich "ich bin noch nicht leer und wartet" und das vergebens denn er wird nicht leer. Des halb meine Idee op ihr in sagen könnt wen noch 1 Prozent im fahzeug ist bin ich leer. Ich hab kein Plan ob das möglich ist.
[log.txt](https://github.com/Courseplay/courseplay/files/4270720/log.txt)

**Comment by Tensuko** [comment]
Naja ich habe das Problem noch nie im Betrieb gehabt, aber habe auch nicht etliche Transporte am Stück durchgeführt.
Auch beim Schaufelmodus habe ich das noch nicht gehabt (ja man sieht manchmal Reste in der Schaufel), aber wenn es von GIANTS kommt, wird es schwer sein da etwas zu machen denke ich...

Müssen wir sehen...

**Comment by Merrlin** [comment]
Das ist genau das gleiche Problem wie bei den Ladewagen die im Silo hängenbleiben.
Aber da nicht repriduzierbar, schwer wirkungsvoll zu fixen.

**Comment by Tensuko** [comment]
Wie aktuell ist dieses Problem ?
Kann das jemand mit der aktuellen Version reprduzieren ?

**Comment by Tensuko** [comment]
Sollte nicht mehr auftreten, ich mach das hier mal zu.
