### ISSUE TITLE
Courseplay with FendtVario1000 Ahran Modding and Fendt900Vario_S5_PC doesn't work

### ISSUE THREAD

**Issue by dicktimmerman** [Courseplay/courseplay#4993]
Hi, 

Above mentioned mods do not work properly. If activated the mouse pointer cannot be brought into the menu area to hit the menu buttons. Don't know if this is their problem or CP's problem, I tried to contact CP first.
[FS19_Fendt900Vario_S5_PC.zip](https://github.com/Courseplay/courseplay/files/4270699/FS19_Fendt900Vario_S5_PC.zip)
[FS19_fendtVario_1000.zip](https://github.com/Courseplay/courseplay/files/4270702/FS19_fendtVario_1000.zip)

**Comment by Tensuko** [comment]
I guess they have IC, wich is already known ( #4185 )

Other then that, no specific Mod Support, maybe ModHub Mods but that will be decided per Mod.

Closed.

**Comment by Merrlin** [comment]
Jupp they have IC... But if you hold down the SPACE Key and hit then the Right Mouse Button you can control CP anyway.

**Comment by Merrlin** [comment]
Forget what I've said. You have to disable IC within the mod itself.
