### ISSUE TITLE
Game locks up while Calculating Offsetcourse for Multitool

### ISSUE THREAD

**Issue by moose31608** [Courseplay/courseplay#4994]
After making a course and hit start to drive it locks up computer

**Comment by Tensuko** [comment]
logfile ? ...
https://github.com/Courseplay/courseplay/wiki

**Comment by moose31608** [comment]
It’s doesn’t do it when you use 1 tractor. But if you setup multi tools in the same field it locks up

**Comment by moose31608** [comment]
And all mods are in game

**Comment by Tensuko** [comment]
Logfile.......

**Comment by moose31608** [comment]
I don’t understand the log file? Where is it at

**Comment by Tensuko** [comment]
..\My Games\FarmingSimulator2019\log.txt

That file, drag and drop it into the comment box.

**Comment by moose31608** [comment]
It’s what ever you changed in 6.01.00388. Because don’t have any problems in 6.01.00387

**Comment by moose31608** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4272036/log.txt)

**Comment by moose31608** [comment]
there problly wont be anything for it when the computer locks up I have to manually shut it down

**Comment by Tensuko** [comment]
Warning: Loading file with invalid case 'C:/Users/Jim/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00377.zip'.

Load mod: Courseplay_6_01_00377 (Version: 6.01.00377) (Hash: 768e332f6a26954071c158ee22642011)
Warning: Loading file with invalid case 'C:/Users/Jim/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00387.zip'.

Load mod: Courseplay_6_01_00387 (Version: 6.01.00387) (Hash: 38b5a192866cd2cb5864ec5d7f373c19)
Warning: Loading file with invalid case 'C:/Users/Jim/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00390.zip'.
Load mod: Courseplay_6_01_00390 (Version: 6.01.00390) (Hash: 67a40b3b7cf57b969c8b2f47f66ede5a)

This is exactly the reason why I tell ppl to ONLY rename the file to FS19_Courseplay so you will notive when you have more then one Version in mods-Folder.

Delete all old CP Versions (390 is newest)
Beside that, what is this one before you load mod:
Warning: Loading file with invalid case

**Comment by moose31608** [comment]
It still does it with only 6.01.00390

**Comment by Tensuko** [comment]
Some other Rules:
Only one Map in Mods Folder.
I want to see a screenshot of the course, the settings, then tools.

And when you are done with cleaning up I want to see the new logfile if you still have the same error msg.

Why I ask for all this ? -> I don't have any Problem with MultiTools.

**Comment by moose31608** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4272125/log.txt)

**Comment by moose31608** [comment]
And it didn’t start doing this until global company was added. I don’t use it

**Comment by Tensuko** [comment]
Can't reprodice with only CP and EasyDev (no GC installed).
![fsScreen_2020_03_07_00_04_24](https://user-images.githubusercontent.com/27344744/76129256-3ba61880-6007-11ea-84e0-8807689b1a5b.png)

**Comment by moose31608** [comment]
Well never had the problem until 6.01.00389 and beyond

**Comment by moose31608** [comment]
How are you settling up the course?

**Comment by manierim** [comment]
Latest version (6.01.00392) it does not freeze completely for me.

When starting a 2 tools course for cotton harvesting it freezes the game (unresponsive, no radio, etc.) for a rather long time (30 secs), then the vehicle start and everything keep working normally.

It happened for both vehicles...

The log is clean of errors or warnings

**Comment by Tensuko** [comment]
@manierim this is not a lock up this is the GIANTS Engine getting to its limit while calculating the offset Lanes for the 2 Worktools.

Nothing to worry about.

**Comment by moose31608** [comment]
I have waited 5 minutes and still doesn’t work have to shutdown computer manually down

**Comment by pvaiko** [comment]
Yes, this is due to the multitool change, we know recalculate the entire course for each vehicle of the group otherwise the inner corners will never be smooth. On very big fields with narrow implements this can take a while.

Not sure if there's a better solution, this at least should result in driveable courses for all vehicles.

**Comment by moose31608** [comment]
If you guys don’t believe me then come to my house and I’ll prove it to you.

**Comment by moose31608** [comment]
It will make the course with know problem. When I hit start to drive that when it locks up

**Comment by Misamangame** [comment]
Hello all,

I can confirm this issue from atleast .390 version.  I just tried newest .392 and it is still the same. when I set the course for 5 combines, course will set up nicely, but when I start first combine to run game freezes completely. 
[log.txt](https://github.com/Courseplay/courseplay/files/4301890/log.txt)

![Course 33](https://user-images.githubusercontent.com/33344465/76144819-42bf3c00-6084-11ea-8cbd-fa6b2375ce44.jpg)

**Comment by moose31608** [comment]
Thank you.

**Comment by pvaiko** [comment]
@Misamangame can you turn on debug channels 14 and 7 and post a log?

**Comment by Misamangame** [comment]
@pvaiko  sure I can, turned them on before course generation, 
[log.txt](https://github.com/Courseplay/courseplay/files/4302299/log.txt)

**Comment by pvaiko** [comment]
Bummer. Not much to see there. Can you post the xml file of this course?

**Comment by moose31608** [comment]
Don’t know what had changed but I didn’t have any problem with 6.01.00387 but after that update that’s when my computer started locking up.

**Comment by Tensuko** [comment]
We know what have changed.

**Comment by Phobs** [comment]
Hey there, I looked at the log file you posted and this looked very familiar:
2020-03-01 10:39 Error: Running LUA method 'update'.
2020-03-01 10:39 C:/Users/Jim/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00387/PurePursuitController.lua:537: attempt to index field 'course' (a nil value)

I've seen this happen as well, those lines will keep getting spammed to the log while the game is completely frozen up, and the log file keeps growing and growing in size.

This happens when you incorrectly start a Combi (empty combine and offload)  course, I can recreate this by just making the course a few dots in length and then placing a waiting dot and then stopping the course recording.

Hope that helps identifying the cause :)

**Comment by Misamangame** [comment]
@pvaiko not sure if I did it correctly
https://gist.github.com/Misamangame/1bf7e9c31352ce5408def398667963eb

**Comment by Tensuko** [comment]
What I can for sure say is that it is not the Computer that locks up, it is simply the game Engine that takes a long time to calculate the Offsetcourse.
How can I tell you this ? -> The rest on my Computer runs smooth.
And it does work:
![fsScreen_2020_03_08_11_35_10](https://user-images.githubusercontent.com/27344744/76161187-288f6780-6131-11ea-8f04-50a81e2ddfe7.png)
This is Wild West x16 Map, not the biggest Field but 4k+ Waypoints.
There is maybe an improovement in calculation needed.

**Comment by pvaiko** [comment]
@Misamangame thanks, got it, tried on the Ravenport map (don't know which map you are using, in any case, it covers the entire standard map), here's what I see.

1. This course is quite big, has over 9000 waypoints, of which 3000 are on the headland (these take long to generate with offset), almost 50 km long.
2. Just loading this course from the disk takes 50 seconds on my laptop.
3. It takes 2 minutes for my slow laptop to generate the offset course for a combine but I see no lock up or freeze.

**Comment by pvaiko** [comment]
Was a stupid bug, try with 394 and later.

**Comment by moose31608** [comment]
That fixed it. It took 3 to 5 seconds to start. Thank you

**Comment by Tensuko** [comment]
I guess this is fixed then, closed.

**Comment by moose31608** [comment]
Its doing it on the seeding 
[log.txt](https://github.com/Courseplay/courseplay/files/4303553/log.txt)

**Comment by Tensuko** [comment]
Das ist ein anderer Fehler, bitte neues Issue machen:
2020-03-08 13:01 Error: Running LUA method 'update'.
2020-03-08 13:01 C:/Users/Jim/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00394/PurePursuitController.lua:537: attempt to index field 'course' (a nil value)

**Comment by moose31608** [comment]
I don’t know how to do it. I just download them and use it
