### ISSUE TITLE
Keine Kombination von Kursen / Auto Drive / CP .389

### ISSUE THREAD

**Issue by Vega56** [Courseplay/courseplay#4995]
Hallo,

mit der aktuellen CP Version .389 kann ich keine Kurse mehr mit Auto Drive kombinieren.
Sobald ich einen Kurs für CP erstelle (z.B. mit dem Ladewagen Gras einsammeln), und diesen mit einem AD Kurs kombinieren möchte passiert bei der Auswahl des entsprechenden Kurses nichts. Heißt sobald ich bei dem AD Kurs auf kombinieren klicke passiert einfach nichts.

AD Version 1.0.7.1
CP .389

Mit CP .386 noch ohne Probleme.

Log:
[log.txt](https://github.com/Courseplay/courseplay/files/4271524/log.txt)

**Comment by Alkoholix** [comment]
Same here. Kurs lässt sich mit dem +Ordner kombinieren, der AutoDrive Kurs wird aber sehr merkwürdig abgefahren.
