### ISSUE TITLE
Designate trailer for offload.

### ISSUE THREAD

**Issue by BadFoxDragon** [Courseplay/courseplay#4997]
I have no idea where or how to post this so if it's in the wrong place please close the issue.

Anyway, don't know if it's already in, I would love to see a feature where I could park a trailer near a field or two, and designate it as the drop off point for harvesters going through a course. Or maybe a few pallets of fertilizer or seed and have the requisite machine go and automatically load up from it when they run empty. Being able to leave an ITRunner container next to a field and have one or two harvesters automatically offload into it/them would be great for productivity and an awesome new feature for the mod.

**Comment by Tensuko** [comment]
Combine -> HUD Settings -> Advanced Settings -> SelfUnload -> activated

Trailer/Container have to be within 20m of the Field Border (or on the Field). Note that the Combine need some space for turning and stuff, the Course it will generate by itself, but it doesn't always find a path, so don't give up when it doesn't work on 1st try :)

Refill: Just Park a Trailer with Seed/Fert/Lime Packs next to Field and Create a Route from Fieldborder along next to the Trailer. Save that Course and now Load the Fieldwork-Course then Add the 'Refill'-Course with the Folder with the + in it. Then just start it running. Same way when you place a refill Silo next to the Field. It doesn't work for Overloaders or normal Trailers.

**Comment by BadFoxDragon** [comment]
That's awesome to know! :D Thank you so much, I had no idea that was already in the mod.
