### ISSUE TITLE
Waiting until fill level is reached " tic tic tic sound"

### ISSUE THREAD

**Issue by Siryes** [Courseplay/courseplay#4998]
In mode2  , Combi ( empty combi and offload ). Tractor at stop postion , waiting for combi to call and it just starts making tic tic tic , stuttering sounds.  Can reproduce on fresh map no Mods. 
using newest CP beta. No errors in logs just the tic tic tic sound.

https://imgur.com/wKJmhgI

**Comment by Tensuko** [comment]
See #3311 and #4286 
Closed.
