### ISSUE TITLE
Adding mods - 'special tools area'

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/courseplay#5000]
Hello,

is it possible to add these 2 mods in "specialTools", so that they work with Courseplay?

https://www.ls-novinky.cz/farming-simulator-2019/prislusenstvi-3/sekacky-3/lely-p300-mengele-sh40
https://fs19.net/farming-simulator-2019-mods/implements-and-tools/pottinger-mex-5-lacotec-lh2-v1-0/

On FS 17, you gave me the lines to add to make it work. But on FS 19, adding these same lines, it does not work ... The game hangs
If you explain to me how to do it, I can test that
Thanks in advance

**Comment by pvaiko** [comment]
Congreatulations for posting the 5000th CP issue!

What exactly are you trying to do and what specific lines you added?

Other than that, special tools area is waiting for a refactoring, the goal would be to move all these settings (if they even needed) to an (optional) XML file and not hard code them.

**Comment by Crinouche** [comment]
I am happy to be the 5000th post. Am I entitled to a gift? :)

In specialTools, I added the last 4 lines, below, as I did for FS 17. But for FS 19, it doesn't work.
- ######################################################### ###########
- [1] HANDSETS / CUTTERS
- Combines / Harvesters [Giants]
elseif workTool.cp.xmlFileName == 'grimmeTectron415.xml' then
workTool.cp.isGrimmeTectron415 = true;
workTool.cp.isHarvesterSteerable = true;

elseif workTool.cp.xmlFileName == 'terraDosT4_40.xml' then
workTool.cp.isHolmerTerraDosT4_40 = true;
workTool.cp.useCrabSteeringMode = 1;
workTool.cp.isHarvesterSteerable = true;
workTool.cp.pipeSide = 1;
workTool.cp.ridgeMarkerIndex = 6;
elseif workTool.cp.xmlFileName == 'tiger6.xml' then
workTool.cp.isRopaTiger6 = true;
workTool.cp.isHarvesterSteerable = true;
workTool.cp.useCrabSteeringMode = 1;


elseif workTool.cp.xmlFileName == 'holmerHR9.xml' then
workTool.cp.isHolmerHR9 = true;

elseif workTool.cp.xmlFileName == 'LelyP300.xml' then
workTool.cp.isTraileredChopper = true;

elseif workTool.cp.xmlFileName == 'MengeleSH40.xml' then
workTool.cp.isTraileredChopper = true;

**Comment by pvaiko** [comment]
> I am happy to be the 5000th post. Am I entitled to a gift? :)

Yes, your issue will receive special attention :)
So, what exactly isn't working?

**Comment by Crinouche** [comment]
https://gist.github.com/Crinouche/9053f7ac6373cdede458164c6b4674af

Hello Pvaïko.
Attached is my log file.

But drop my problem. I prefer that you work on the new mode 2 ( # 3311 & # 4286) because, I am impatient to be able to use it.
I am also worried that it will never be finished ...
thank you for your work

**Comment by Tensuko** [comment]
For Mode2, we are on a good way right now, but it is a step by step process and every step might have a stone in the way...
No need to drop this, as we said special tools area is waiting for a refactoring, but not on hight priority :)

**Comment by Tensuko** [comment]
#6684 collecting stuff
