### ISSUE TITLE
CP6.01.00390 - spreader won't go back to actual waypoint

### ISSUE THREAD

**Issue by caplink811** [Courseplay/courseplay#5003]
Morning,
when the spreader is empty, usually I fired the driver and refill the spreader manually, then I hire the driver again (with parameter "start at actual waypoint), and expect that cp will continue with the spreading work on actual waypoint (as shown in the bottom line), but as soon as I start the driver, cp switch the spreader on and continue on the nearest waypoint (which is not the actual).
please see attached video for details. With debug channel 12 and 14, there are no entries in logfile.

thank you
bye JrB

Video: https://1drv.ms/v/s!Aqt5msdvWb55h2QIOWLeCdsPfmdN?e=MOxEY3

**Comment by Tensuko** [comment]
When you even turn on devugchannels, what is so hard to simply drag and drop the log.txt into the comment box so we can have a look ? ... I don't get it...

**Comment by Friendlyx** [comment]
can confirm that bug. Will look for debug channels and post later if still needed

**Comment by caplink811** [comment]
morning,
first - please bear with me, but when you get to my age you may experience something similar ;-)
second - see video as well as log and the courses for details, the map is Saxonia_2_2_1.

thank you, ciao JrB

Courses: https://1drv.ms/u/s!Aqt5msdvWb55h2gWuhk5kfasgcU5?e=QmRiED
Movie: https://1drv.ms/v/s!Aqt5msdvWb55h2dPYmWhTHqc4ysU?e=FRl4eE
[030320_1332log.txt](https://github.com/Courseplay/courseplay/files/4281295/030320_1332log.txt)

**Comment by pvaiko** [comment]
@caplink811 Yeah, I saw this coming, which is not an excuse of course. Until I fix it you may experiment with automatic refill, probably even using AutoDrive for the refill course :)

**Comment by caplink811** [comment]
@pvaiko , not a problem at all. It's still a beta, isn't it...

cheers JrB
