### ISSUE TITLE
'Sofort Abfahren' nur wo es Sinnvoll ist

### ISSUE THREAD

**Issue by risch6186** [Courseplay/courseplay#5004]
Hallo. Ich habe folgendes Problem mit dem Sofort Abfahren: Im Modus Feldarbeit erscheint der Button   "Sofort Abfahren" nur wenn ein Grubber, Schwader oder Wender angehängt ist. Wenn ich einen Pflug angehängt habe, erscheint der Button nicht?!?. 
Im Modus Düngen/Säen ist das Problem ähnlich. Kein Button" Sofort Abfahren" bei einer Dünge - oder Sämaschine.
Ansonsten funktioniert das Sofort Abfahren sehr gut.

**Comment by Tensuko** [comment]
Mal eine Verständnissfrage... wofür benutzt du denn 'Sofort Abfahren' im Mode4 und Mode6 ?

**Comment by risch6186** [comment]
Ich habe nach dem Feldarbeitskurs noch einen Kurs zum Hof angehängt und möchte das Fahrzeug nach Beendigung der Feldarbeit mit Sofort Abfahren dann zum Hof fahren lassen, wenn das Feld sehr weit vom Hof entfernt ist. Ist für mich sehr praktisch...

**Comment by Tensuko** [comment]
Das ist so nicht gedacht, eher Feldarbeit raus, Kurs zum Hof laden und losfahren.
Werde das mal besprechen...

**Comment by Tensuko** [comment]
Das wird nicht passieren.

Wir werden Sofort Abfahren für Farhzeuge die sammeln (Sammelwagen, Ballenwagen) für den Mode6 integrieren, für alle anderen macht es keinen Sinn.

Der extra angehängte Kurs ist nur fürs Abfahren und Nachfüllen.

Willst du eine Art Parkfunktion haben, solltest du dir zusätzlich AD anschaffen. Da kannst du für jedes Fahrzeug eine Parkposition hinterlegen. Das sollte mit CP+AD funktionieren, jedenfals wurde es hier gewünscht:  #4515

**Comment by risch6186** [comment]
Könnte ich trotzdem eine Info bekommen wie und in welcher Datei/Dateien in courseplay ich das "Sofort Abfahren" nach meinen wünschen einstellen kann. Vielen Dank
