### ISSUE TITLE
Been awhile, need guidance

### ISSUE THREAD

**Issue by Tadeloach** [Courseplay/courseplay#5005]
It has been awhile since I played and am way behind on updates to courseplay and AD.  Are there any new walkthroughs available or anything for running refill courses etc for sowers/planters?  All the videos are for the old versions.  Just need pointed in the right direction.  Thanks

**Comment by Tensuko** [comment]
For AD ask in AD GitHub, I don't use it enough.
For CP it is still the same.
Generate Fieldcourse -> Save it.
Record Refillcourse (can be all silos, seed, fert, lime in one course but all extra silos) -> Save it.
Load Fieldcourse, add Refillcourse (Folder with the +) and let it go :)

**Comment by Tadeloach** [comment]
> For AD ask in AD GitHub, I don't use it enough.
> For CP it is still the same.
> Generate Fieldcourse -> Save it.
> Record Refillcourse (can be all silos, seed, fert, lime in one course but all extra silos) -> Save it.
> Load Fieldcourse, add Refillcourse (Folder with the +) and let it go :)

If you have Autodrive points to your refill points, cant you load them the same way?

Was combi mode 2 ever finished?

**Comment by Tensuko** [comment]
If you have a AD Network, it should work too.

Mode2, see Pinned Issues #3311 and #4286

**Comment by Tadeloach** [comment]
Thanks Tensuko
