### ISSUE TITLE
Simple IC

### ISSUE THREAD

**Issue by Friendlyx** [Courseplay/courseplay#5006]
CP und Simple IC scheinen sich zu behaken.
Habe viel probiert und erst einen anderen Mod als Verursacher gefunden doch nach weiteren Tests habe ich diesen Konflikt ausgemacht.
Zum Test: Input bindings gelöscht, neuer spielstand, nur den FBM Unimog + Simple IC aktiv und es funktioniert. Ich kann auf die IC marker klicken und es tut sich was. Jetzt noch CP6 dazu aktiviert und es passiert beim klicken auf die IC marker nix mehr. Leider auch eine fehlerfreie LOG sodass man da nicht direkt sieht woran es liegt.
Ich hoffe es findet sich für das CP Team hier ein Ansatz um dieses Problem zu lösen. Evtl kann man ja mit Modelleicher zusammen arbeiten auch er weiß nun von dem Konflikt.

danke für die sonst so tolle Arbeit an CP

**Comment by Tensuko** [comment]
Es besteht kein Konflikt zwischen CP und SimpleIC da ich es selber beides benutze.
Es kann nur sein das ein Keysetting nicht passt und du eine andere Taste zuweisen solltest.
![fsScreen_2020_03_04_18_31_44](https://user-images.githubusercontent.com/27344744/75906110-70b73d00-5e46-11ea-881e-d39e96247037.png)
