### ISSUE TITLE
Namensgebung AD - CP

### ISSUE THREAD

**Issue by scandal65** [Courseplay/courseplay#5007]
Hallo,
ist es möglich die Namenänderung von Autodrive in Courseplay zu übernehmen?
Wenn ich z.b. den Fendt Ideal 8T in AD in **Drescher1** umbenenne - meldet mir CP **Fendt Ideal 8T** ist mit der Arbeit fertig!
Da ich aber meistens mit mehreren Dreschern arbeite, muss ich immer erst suchen **welcher Fendt Ideal 8T** fertig ist.
Es wäre super wenn beide Systeme den selben Namen verwenden würden!

lg scand@l

(  google english  ;-)  )

Hi there,
is it possible to change the name from Autodrive to Courseplay?
For example, if I Rename the Fendt Ideal 8T to AD in **Drescher1** - CP ** reports me. Fendt Ideal 8T ** is done!
But since I mostly work with several threshers, I always have to search first **which Fendt Ideal 8T** is ready.
It would be great if both systems use the same name!

lg scand@l

**Comment by Tensuko** [comment]
Wir müssten dann immer prüfen, ob AD vorhanden ist, dann auf die Daten von AD zugreifen und das mit einbinden...

Wenn wir das machen sollten, steht es nicht oben auf der Prioritätsliste.

@Stephan-S
Ich nehme an, ihr habt dafür so eine Art Tabelle in der die Farhzeug-IDs mit Namen versehen werden ?

**Comment by Iwan1803** [comment]
@Tensuko die Info steht in der verhicles.xml.
Sowie CP dort unter jeder ID Infos speichert, legt auch AD die Infos dort ab (FS19_AutoDrive -> driverName).

**Comment by Tensuko** [comment]
Wir haben uns vorerst dagegen entschieden.
Wir behalten das Thema mit den Namen im Auge.
