### ISSUE TITLE
Abfahrer wechselt die Seite trotz fester Einstellungen 

### ISSUE THREAD

**Issue by harleymac** [Courseplay/courseplay#5010]
Hallo,
zum Abtanken vom Case Austoft 8800 MR verwende ich die Einstellung seitlicher Abstand -4.2m, vertikaler Abstand -3.5m. Damit bleibt der Abfahrer immer rechts vom Zuckerrohr-Ernter. Nach dem Abfahren zum Silo und der Rückkehr ändert sich der Wert des seitlichen Abstands plötzlich von selbst auf +4.2m, der Abfahrer fährt nun links vom Ernter mitten in den Feldfrüchten und stößt mit ihm an der nächsten Biegung zusammen. 
Warum bleibt der eingestellte Wert nicht erhalten?

**Comment by Tensuko** [comment]
Siehe #3311 und #4286 
Closed.
