### ISSUE TITLE
ki fahrer collision (drescher + abfahrer)

### ISSUE THREAD

**Issue by nimanox** [Courseplay/courseplay#5011]
course play is nen toller mod allerdings habe ich probleme was die ki fahrer angeht wen ich 2 drescher und 1 abfahrer habe tretten jedes mal mehrere probleme auf  

1. die drescher bleiben jedes mal an einanderhängen wen sie sich entgegen fahren  also einer auf bahn a nach oben und der ztweite drescher auf der bahn b nach unten die daneben liegt und verkeilen sich in einander mit ihre drescher vorne.
2.habe ich die arbeitsbreite breiter gemacht als sie eigentlich sind, dann hat es funktioniert aber es tratt das nächste problem auf das sie sich mit ihren abfüll rohren verkeilen weil beide ihre rohre ausfahren wen sie auf einander treffen.
 3. wen ein drescher voll war fährt er in die vorherige bahn rückwärts wen das rohr in die frucht ragt  wo eig gleich der andere drescher fahren sol,l was nicht so problematisch ist weil der zweite ja stehen bleibt dank fahrzeugverband. das größere problem ist das wenn nun der abholer kommt und dne vollen drescher abtanken tut und fertig ist und der drescher wieder nach links in seine alte spur will will gleichzeitig der abfahrer auch weiter fahren aber fährt jedesmal in den drescher rein und verkleilen sich. 

gibt es da möglichkeiten wie ich  diese probleme von meiner seite aus löse wen es mein fehler ist oder is das ein reiner programm fehler?

**Comment by Tensuko** [comment]
Siehe #3311 und #4286 
Closed.
