### ISSUE TITLE
MP CP Driver not exiting vehicle.

### ISSUE THREAD

**Issue by Glithander** [Courseplay/courseplay#5013]
On MP (Dedi) - When hitting 'Stop Driving' the CP Driver (for the player that initiated the CP Driver) stops and disappears.  For the other player(s) the vehicle stops, but the CP Driver remains as a 'helper' in the vehicle and if the other player(s) enter that vehicle, the F1 Help menu shows 'Dismiss Worker' - We found that having the original driver reset the vehicle usually works to dismiss the CP driver for all players, making the vehicle usable again. 

If one of the other players tries to reset the vehicle, though, you get the message that 'Tool is in use and cannot be reset'.

**Comment by jspring0811** [comment]
I'm recently seeing the Stop Driver does not dismiss the worker even when I'm the only person logged into the MP server.  This just started happening on MP in very recent release.  Stop Driver used to also dismiss the worker.  I am on v6.01.00395 now and I ~think~ I was on 391 when it was dismissing the worker.

**Comment by MicaelJarniac** [comment]
Happened to me as well. Probably the same as #5087 and #5150.
