### ISSUE TITLE
Computer freeze after trying to create a new Course

### ISSUE THREAD

**Issue by Vega56** [Courseplay/courseplay#5014]
Hello,

i have a Problem with the Multitool Course Generator.

**The Problem showed up after i created a course for my BGA Silo. When i try to generate a course with the Multitool, my PC freeze and i have to restart the System.  (Maybe its similar to #4994)

Bevor i created the Course for the BGA Silo everythin worked without Problems!**

**I use .391**

[log.txt](https://github.com/Courseplay/courseplay/files/4297787/log.txt)

**Comment by Tensuko** [comment]
There is no Error in the logfile.
Create the Issue and THEN post that logfile.

Also: Multitool Course in a BGA Silo ?
Can you pls make a Screenshot of the Situation and discripe it a bit more precise what you trying to do ?

**Comment by Vega56** [comment]
This is the Logfile after i try to create a Course..... After the try i have to restart my Computer or have to logout.

No, i have used the Multitool on a Field. This have nothing to do with the Silo. It all started after i created a Course with "Verdichten" ( I dont know the English word :) ). I removed the Course but the Problem is still there.

I am just trying to create a Course for Amazone Condor 15001.

**Comment by Tensuko** [comment]
The point is, it sounds like it have to do with multitool... but now you say it starts after the BGA Course...

What are the steps to create the issue and did you try to recreate this when you not make a multitool course before running the BGA ?

I can't even say whats the Issue here...

You can also change to german it is kein Problem :)

**Comment by Vega56** [comment]
Also wenn das kein Problem ist :)

Ich habe in einem BGA Silo einen Kurs fürs Verdichten angelegt. Gestartet habe ich diesen nicht, sondern einfach nur mal angelegt und gespeichert. Nachdem ich das getan habe wollte ich das nächste Feld vorbereiten. Also Sämaschine ran und auf das Feld gefahren. 

Nächster Schritt ist die Erstellung eines Kurses mit dem Multitool. 
(Das hat alles wunderbar funktioniert bevor ich den BGA Kurs erstellt habe). 

Was mir gleich als erstes aufgefallen ist, er hat nicht wie gewohnt die Arbeitsbreite der Sämaschine übernommen sondern hatte die Arbeitsbreite eingestellt die ich vorher bei dem BGA Kurs verwendet habe für das Schild. Obwohl der Kurs nicht geladen war. Selbst jetzt wo der Kurs eigentlich gelöscht ist.
(Hatte ich vergessen oben zu erwähnen - Sorry).

Sobald ich jetzt auf Kurs generieren klicke friert das Spiel ein. Selbst in Windows kann ich keine Fenster schließen. Es bleibt mir nur die Abmeldung oder der Neustart.

Es spielt keine Rolle ob mit Vorgewende oder sonst was, das Ergebnis bleibt das gleiche.

**Comment by Tensuko** [comment]
Mach bitte mal ein Bild von den Einstellungen die du nutzt um den Kurs zu generieren

**Comment by Vega56** [comment]
Anbei.

Das erste zeigt die 7.8m Arbeitsbreite des Silo Kurs. Dieser ist aber bereits gelöscht. 
![20200306125205_1](https://user-images.githubusercontent.com/55054246/76081479-79745400-5fa9-11ea-886f-5dd6bdc854a2.jpg)
![20200306125219_1](https://user-images.githubusercontent.com/55054246/76081482-7a0cea80-5fa9-11ea-95b0-f6a7fcaa845d.jpg)

**Comment by Tensuko** [comment]
Ich verstehe es zwar nicht was du da machst mit Silokurs usw, aber hab ne Idee was das Problem sein könnte.
Allerdings hat das so nichts mit Multitool zu tun.

Sonst schreib mir mal was du vor hast.
Wiese mähen und dann sammeln und ab in den Bunkersilo oder wie ?

**Comment by Vega56** [comment]
Der Silo Kurs mit dem Mode "Bunkersilo befüllen und verdichten" ist für später gedacht. 
Dazu habe ich Mais auf Feld 1 der dann später mit dem Häcksler entsprechend verarbeitet wird. Danach Abladen im Silo an der BGA. Während das läuft soll der CP Fahrer verdichten.

**Comment by Tensuko** [comment]
Um eine Verwirrung aus dem ganzen zu nehmen: Multitool bedeutet einen Kurs für mehrere Geräte, z.B. 2 oder 3 Grubber auf einem Feld/Kurs.

Ich glaube du keinst einfach nur den Kursgenerator, mit dem du erst den Kurs zum Feld 1 Häckseln generiert hast und jetzt willst du wo anders einen Kurs generieren und dein Spiel friert ein. Ist das in etwar so richtig ?

**Comment by Vega56** [comment]
Sorry, mit dem Multitool meinte ich die Feldarbeit.  :(

Jein. Nachdem ich dem BGA Kurs zum Verdichten erstellt habe.
Danach Feldarbeit Kurs auf F20 und seitdem friert das Spiel ein.

**Comment by Tensuko** [comment]
So ich bin nun auch zu Hause und habe mal geguckt, aber ich kann es nicht reproduzieren und habe auch keine Idee was das sein könnte.

Sry aber ich brauche mehr Infos:
Am besten Bilder oder Videos mit den Fahrzeugen und Tools die du benutzt um deine Kurse zu erstellen und wie du das machst.

Weil einen Kurs aufnehmen und speichern ist kein Grund warum das Spiel einfrieren sollte, wenn man dann einen weiteren Kurs generiert.

Also entweder dein Save oder dein Spiel hat ein Problem, oder ein Modkonflikt, oder du machst etwas falsch was wir dann eventuell verhindern sollten, dass man das nicht mehr machen kann.

**Comment by Vega56** [comment]
Ich habe jetzt in der zwischenzeit mein Rechner neu aufgesetzt. Einfach um auszuschließen das es an Windows oder LS19 liegt.

Courseplay habe ich zuerst nicht mit in den Mod Ordner gepackt. Spiel gestartet , gespeichert und geschlossen. Danach Courseplay .391 rein und versucht Kurs zu erstellen. Zack Spiel wieder eingefroren :(

Versucht habe ich das ganze mit Standardfahrzeugen wie z.B. Deutz Series 9 oder Fendt 900.

Und wie gesagt, es hat die ganze Zeit alles wunderbar funktioniert, egal welches Feld oder egal welche Art von Kurs. Der Generator hat immer tadelos funktioniert. Alles hat angefangen mit dem BGA Silo Kurs. Ich habe keine Mods o.Ä. dazu gepackt oder sonst was an dem Spiel geändert.

Es scheint so als hätte mein Savegame irgendetwas abbekommen. Bleibt mir wohl nix anderes übrig als ein neues anzufangen. Anbei habe ich mal das Savegame.


[savegame1.zip](https://github.com/Courseplay/courseplay/files/4298946/savegame1.zip)

**Comment by Tensuko** [comment]
Kannst du mal versuchen das in einem neuen Savegame nach zu stellen ?

**Comment by Tensuko** [comment]
Passiert das noch immer mit der neuesten Version 394 ?

**Comment by Vega56** [comment]
Hallo,

sorry , war jetzt eine Weile nicht am Rechner. Im neuen Savegame habe ich mit der alten Version das ganze nachgestellt. Dort hat es komischerweise funktioniert. Wie bereits erwähnt, am Spiel oder an den Mods gab es keinerlei Änderungen. Ich benutze noch die gleichen wie zuvor. 

Somit hat sich das jetzt erstmal erledigt. Danke für die Hilfe.
