### ISSUE TITLE
Error: Running LUA method 'update' - PurePursuitController.lua:537: attempt to index field 'course' (a nil value) - Only on Grimme SE260

### ISSUE THREAD

**Issue by eddieflyinv** [Courseplay/courseplay#5016]
Courseplay Version v6.01.00385
Problems exist with:
Ropa Kieler 2
Grimme SE260
Both tools pulled  by a stock Case 7200 Pro, no other mods active, new game, Courseplay Only

The Ropa Kieler 2 willl successfully harvest with Courseplay, and appears to work perfectly, but cannot be recognized as a harvester option by a Courseplay Combi Mode driver, neither automatically by combi driver being in the same field as the harvester, or manual assignment

The SE260 causes more issues. Course generation works fine, but when clicking on the combine options tab on courseplay HUD when inside the tractor towing it, the hud disappears completely. I can right click to bring the mouse pointer back, and click randomly where the other tabs are (that i cannot see as the whole HUD is gone) and the HUD will reappear upon successfully selecting a different one.

When trying to start the generated course with the SE260 the tractor does not move, and most game controls are lost. after the mouse pointer disappears the game camera will not move around, but I can right click to bring the pointer back and stop the driver and return the game to normal. if I start the course, and tab to another tractor, i progressively and eventually lose all control of the game, unless i get back to that tractor to stop the courseplay driver, or I can get to the menu to quit the game.

anyways, log attached, I dont know how to evaluate them at all, but i loaded my save, tried the kieler 2 and tried to get a combi driver to recognise it. purchased the se260 and tried to use it and basically lost control of the game and quit the game.

ultimately i can just use other means of harvesting, but i like the idea of using these tools when starting a fresh game and cannot afford the self propelled units (which have always worked for me)
I have tried these tools with multiple versions of courseplay v6 in the past, i just never got around to reporting these issues.

Thanks for your time folks! I absolutely love courseplay by the way, cannot play without it.
[log.txt](https://github.com/Courseplay/courseplay/files/4299463/log.txt)

**Comment by Tensuko** [comment]
Get the newest Version and try again:
https://github.com/Courseplay/courseplay/releases

**Comment by eddieflyinv** [comment]
Alright, did another round of testing with the newest version
I created a new save game again as well, and deleted all my old courses, created new ones for Field 21 testing.
Exact same issues as before. SE260 still causes the HUD to disappear when selecting combine options, and doesn't move when course is started/freeze up controls etc.
I also tested with the Kieler 2, and same problems as before as well, could start and drive the course, but CP combi mode doesn't detect the harvester

For curiosities sake, I saved a copy of the log.txt after testing, and then I enabled AutoDrive when reloading my save, to see if the combine unload feature of AutoDrive worked with either of those harvesters. and it did not.

I am not sure if that is relevant to your troubleshooting, but I tried the Kieler 2 with a CP helper pulling the harvester, and again with an AI helper, and no matter which one was driving the machine, the AD helper would not go unload it,
and same for the SE260, (minus trying with a CP Helper as it would freeze etc)
anyways, 2 logs attached,
Log1 - Courseplay only
[log1.txt](https://github.com/Courseplay/courseplay/files/4300006/log1.txt)

Log2 - Courseplay and AD
[log2.txt](https://github.com/Courseplay/courseplay/files/4300009/log2.txt)

hope that helps ?

**Comment by Tensuko** [comment]
Oh I just noticed you use Mode2 (Combi Mode).
Well then I only got to say this:
Check the pinned Issues #3311 and #4286

Closed.

**Comment by polosubtil** [comment]
Hi Tensuko
I think this has nothing to do with mode 2, I have the same problem than @eddieflyinv 
Grimme SE260 is crashing mode 6
[log.txt](https://github.com/Courseplay/courseplay/files/4300282/log.txt)

**Comment by Tensuko** [comment]
> The Ropa Kieler 2 willl successfully harvest with Courseplay, and appears to work perfectly, but cannot be recognized as a harvester option by a Courseplay Combi Mode driver, neither automatically by combi driver being in the same field as the harvester, or manual assignment

Thats why I say its Mode2 related.
But I will check on that one...

**Comment by Tensuko** [comment]
Ok so it is only the Grimme SE260 with the Error:
2020-03-06 20:39 Error: Running LUA method 'update'.
2020-03-06 20:39 C:/Users/Paul/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/PurePursuitController.lua:537: attempt to index field 'course' (a nil value)

**Comment by Tensuko** [comment]
Additional I had this Error when start from more far away.
2020-03-06 21:59 Error: Running LUA method 'mouseEvent'.
2020-03-06 21:59 I:/Dokumente/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CombineAIDriver.lua:100: attempt to call method 'setPipeState' (a nil value)

**Comment by eddieflyinv** [comment]
Thanks guys,
Yeah I thought the mention of Combi mode might get this thrown away, as I understand it is a WIP right now,
But as I kind of mentioned I have had this problem with this specific equipment in many previous releases, and it wasnt even the combi driver that was causing the freeze as they never even got started.
Just wish i had got to reporting this alot sooner lol I would just use other equipment when the freeze used to happen. Also happened alot with the tow behind sugar beet harvester as well, but i cant confirm its the exact same error as i dont have log files from when i last tried/failed to use that one.
