### ISSUE TITLE
Combine Issue

### ISSUE THREAD

**Issue by zshurtliff** [Courseplay/courseplay#5018]
When ever I set up a combine course it runs great until I set up an unload course. As soon as I start the unloading course for my tractor the combine stops harvesting. Any suggestions or something I'm missing. Thanks.

**Comment by Tensuko** [comment]
What do you mean with unlaod course ?
A Course that you add to the combine so he drive to the Trailer is not needed, if you want the Combin to unload itself. You just got to turn on Self Unload in the Advanced Settings.

Anything like Mode2 (Combi Mode) is #3311 and #4286

**Comment by zshurtliff** [comment]
I'm trying to set up a tractor with an auger wagon to unload the combine in the field.

**Comment by Tensuko** [comment]
That is Mode2, see my Comment.

Closed.
