### ISSUE TITLE
Add field islands into recorded roundcourse

### ISSUE THREAD

**Issue by OculusRealis** [Courseplay/courseplay#5020]
Is there a possibility to add a field island to a self recorded roundcourse?
Especially if there a custom made fields with obstacles courseplay does not recognize.

Greeting
OR

**Comment by Tensuko** [comment]
Hmm not sure, I also tried it with make 2 course one for Fieldborder one for Fieldisland and load them both but didn't work.

I am not sure if can add this to the system like it is right now, but I take it as Suggestion, but will be on lower Priority...

**Comment by pvaiko** [comment]
Courseplay should recognize islands if you change the area of the island before with the landscaping to something other than a field. Obstacles by themselves aren't recognized during course generation.
