### ISSUE TITLE
Frozen game when muliple vehicles on one course version 6.01.388 or newer.

### ISSUE THREAD

**Issue by Williwillswisse** [Courseplay/courseplay#5021]
Hallo, ich habe seit kurzem ein CP Problem beim Arbeiten im Fahrzeugverband. Wenn ich im Kursgenerator einen Kurs mit mehr als einem Fahrzeug generiere und diese im Fahrzeugverband laufen lassen möchte passiert das Folgende:
bis Version 6.01.00387 -> alles funktioniert wie erwartet schnell.
ab Version 6.01.00388 -> wenn ich auf Abfahrer einstellen klicke ist das Spiel über 8 Minuten eingefroren (reagiert nicht im Taskmanager). Nach dieser langen Zeit läuft das Fahrzeug dann.
Dieses ist bei jedem Fahrzeug im Verband so.
Karte: Wild West 16x
Fahrzeuge: Claas DLC
keine Log Einträge

google translate ;-)
Hello, I have recently had a CP problem when working in the vehicle association. If I generate a course with more than one vehicle in the course generator and want to run it in the vehicle association, the following happens:
up to version 6.01.00387 -> everything works quickly as expected.
from version 6.01.00388 -> if I click on set driver the game is frozen for 8 minutes (does not react in the task manager). After this long time the vehicle will run.
This is the case for every vehicle in the association.
Map: Wild West 16x
Vehicles: Claas DLC
no Log entries

**Comment by Tensuko** [comment]
Log immer posten.
In dem Fall bitte mal Channel 7 und 14 einschalten, Kurs generieren, Fahrer einstallen und dann die log posten.

**Comment by Williwillswisse** [comment]
Hallo Tensuko,
hier die gewünschte Logdatei mit Channel 7 und 14.

[log.txt](https://github.com/Courseplay/courseplay/files/4302634/log.txt)

**Comment by vemendoza** [comment]
Yeah, I have the same problem, but my game freezes for 30 seconds maybe. Other problem is that vehicles (2 combines) isn't working again using symmetric lane change. The same problem that I had until CP 6.01.00386. My option was rollback the CP version to 386.

Thanks for your job guys.

**Comment by vemendoza** [comment]
Yeah, I have the same problem, but my game freezes for 30 seconds maybe. Other problem is that vehicles (5 combines) is working fine using symmetric lane change, but the text in the hud, not change.

Example, if i set for the first combine to 2-left, when the combine turns, the hud keep showing 2-left, but the combine now is working in the lane 2 right. The same occurs if I set to 2-right. When the combine turns, the hud keep showing 2-right, but the combine now is working in the lane 2 left.

Until this moment I had using CP 6.01.00386. My option was rollback to CP version 386. This version works fine.

Thanks for your job guys.

**Comment by Tensuko** [comment]
@vemendoza 
The change in the HUD is correct. I know it is confusing, but the side where they go is set from the startdirection.
Actually the Version 393 is working correct in terms of how it is supposed to work.
The wayittime is calculation the offset course for the Vehicles.

@Williwillswisse 
Hab mir die Karte mal geladen und ja es ist nicht das größte Feld, aber es geht mit einer kurzen Wartezeit.
Welches Feld mit welchem Fahrzeug hast du in deinem Fall versucht zu bearbeiten ?
Weil im Prinzip funktioniert es wie es soll, nur die lange Berechnung ist unschön, aber das ist eben der größe des Kurses geschuldet. Muss man sehen in wie weit man da etwas machen kann.

![fsScreen_2020_03_08_11_35_10](https://user-images.githubusercontent.com/27344744/76161263-fd594800-6131-11ea-82ad-814770dc2be3.png)

**Comment by Tensuko** [comment]
![fsScreen_2020_03_08_12_12_16](https://user-images.githubusercontent.com/27344744/76161705-22e85080-6136-11ea-8ccd-3d4613095022.png)
Nicht ganz 4 min für einen Drescher auf Feld 60.
Ist natürlich viel bei 5 Drescher sind es dann 20min.
Mal schauen was sich da machen lässt.

**Comment by Williwillswisse** [comment]
Hi Tensuko, ich bearbeite Feld 60 auf der Wild West mit 5 Häckslern(CP) und 5 Abfahrern(AD). Was mich wundert ist nur, dass es bis Version 387 ja ohne Wartezeit funktioniert. Erst bei den neueren Versionen braucht CP so lange. Habt ihr zu dem Zeitpunkt was geändert?

**Comment by Tensuko** [comment]
Ja, steht ja auch im Release:

Multitool/offset refactored.

When using multitools, the entire offset course is calculated
when starting the vehicle using the left/right lane offset
setting. This setting can't be changed while CP is driving.

This should fix all issues with multitools, especially headland
turns on the inner courses.

**Comment by Williwillswisse** [comment]
Ah, ok. Danke für den Hinweis.

**Comment by Tensuko** [comment]
Wie gesagt, Ideal ist das so noch nicht.
Mal sehen ob wir dafür eine bessere Lösung finden.
Aber an sich funktioniert es mit etwas mehr geduld.

**Comment by pvaiko** [comment]
Was a stupid bug, try with 394 and later.

**Comment by Williwillswisse** [comment]
Thank you, works like a charm.
