### ISSUE TITLE
Crash game after use Rubicon

### ISSUE THREAD

**Issue by Vanquish081** [Courseplay/courseplay#5024]
Adde log file, I don't know why, but when finish the task for herbicide with courseplay, the game crash to the change vehicle...

[log.txt](https://github.com/Courseplay/courseplay/files/4303121/log.txt)

**Comment by Tensuko** [comment]
Try Newest version first and report.
If still happens I will check on that one.

**Comment by Vanquish081** [comment]
The version was ....386, now testing with ....393

**Comment by Vanquish081** [comment]
Well, now no crash, but no complete all area the field and no use the mode steering wheel full, only steering wheel in the front wheels.

**Comment by Tensuko** [comment]
CP HUD Settings -> Advanced Settings ->
Lower Implement early and maybealso raise implement late. Try it out and report.

**Comment by Vanquish081** [comment]
Well, with this setting work fine, closing
