### ISSUE TITLE
GUI wird nicht Angezeigt

### ISSUE THREAD

**Issue by M4rciii** [Courseplay/courseplay#5025]
Hallo,

Ich habe die aktuelle Version von CP und die Aktuelle Version von AD auf meinem Server. AD wird angezeigt aber wenn ich die Rechts klicke bekomme ich zwar den Mauszeiger angezeigt aber kein GUI von CP.

**Comment by Merrlin** [comment]
Logfile?

**Comment by Tensuko** [comment]
Log vom Client und Server.

**Comment by M4rciii** [comment]
Ohm okay ich habe soeben das letzte Update von CP auf den Server Gespielt und wollte die Logfile posten aber nun geht alles. AD funktioniert und CP wird das GUI Angezeigt. Aber hier noch die Logfile.

Game Logfile: https://pastebin.com/dhrRKnss
Server Logfile: https://pastebin.com/rRJU412H

**Comment by Tensuko** [comment]
Na dann ist ja alles super! :)
Mache hier dann wieder zu.
