### ISSUE TITLE
Autodrive Routen werden nicht korrekt erkannt

### ISSUE THREAD

**Issue by AngeloMerte** [Courseplay/courseplay#5026]
An sich funktioniert Courseplay einwandfrei bei uns. Sobald wir aber Strecken von Autodrive in Kurse integrieren wollen, z.B. "Silo (and return)"wirft er uns immer willkürlich irgendwelche Kurse rein, anstatt dem, den wir angeklickt haben. Ab dem Zeitpunkt sind dann alle Courseplaykurse durcheinander, also es werden immer andere geladen als wir anklicken, auch bei den "normalen" Courseplaykursen, bis wir den Server einmal neustarten. Scheint da also irgendein Problem zu geben, wenn Courseplay sich die Kurse über Autodrive ziehen will. Hoffe es war einigermaßen verständlich.

P.S. 
Vielen, vielen Dank für deine Arbeit. Dein Tool ist Weltklasse und mit Geld nicht zu bezahlen!

**Comment by Tensuko** [comment]
Nur auf dem Server oder auch im SP ?

**Comment by AngeloMerte** [comment]
Bislang nur auf dem Server. Da scheint es aber aktuell generell einige Probleme zu geben, da wir auch die Netze nicht erweitern können. Ich warte erstmal aufs neue Autodrive update, was angekündigt wurde. Vielen Dank trotzdem erstmal :)
