### ISSUE TITLE
Can't calculate right offset course for multitool

### ISSUE THREAD

**Issue by moose31608** [Courseplay/courseplay#5027]

**Comment by moose31608** [comment]
https://github.com/Courseplay/courseplay/files/4303553/log.txt

**Comment by pvaiko** [comment]
Screenshot of the course you generated

**Comment by moose31608** [comment]
And it doesn’t do it until you try to start the second tractor

**Comment by nimanox** [comment]
er will damit sagen das wenn man zwei säe maschienen gleichzeitig laufen lassen will die eine maschine nicht mit der rechten bahn anfangen will habe derzeit das selbe problem. steht nur still da und wen man den anschaltet steht unter entlassen weiterfahren aber danach passiert auch nichts

**Comment by pvaiko** [comment]
@nimanox update to the latest version, you are running 391, we are at 395.

**Comment by moose31608** [comment]
It does it on the latest one too

**Comment by pvaiko** [comment]
@nimanox kannst du das bitte mit 395 reproduzieren und wenn's nicht geht hier genau beschreiben wie ich es nachstellen kann?

**Comment by nimanox** [comment]
so  ich habe es nochmal mit einen 2 stunden älteren spielstand getestet mit der selben cp version und konnte es dort auch reproduzieren .jetzt mit der neuen version wird ein anderer kurs berechnet als mit der version davor
http://prntscr.com/rfci8g

allerdings ist der fehler der gleiche mit älteren und neueren spielstand und wen ich jetzt auf weiter fahren drücke hängt sich alles auf kann noch esc drücken und auf die karte schauen aber dort wird nichts mehr angezeigt und er zoom immer weiter raus
http://prntscr.com/rfclzm
 

[log.txt](https://github.com/Courseplay/courseplay/files/4324824/log.txt)

**Comment by Tensuko** [comment]
Also ich kann es kein Stück nachvollziehen, bei mir klappt alles reibungslos...

**Comment by nimanox** [comment]
ja ich auch nicht mit der selben version von 391 gings vorgestern auch ohne probleme

**Comment by Tensuko** [comment]
Ja und mit der 395 ?
Also ich habe eben verschiedene Startrichtungen und mit Vorgewende probiert und die haben brav ihren Job gemacht.

**Comment by pvaiko** [comment]
Das liegt irgendwie an dem speziellen Kurs oder Feld, CP kann die rechte offset Vorgewende nicht generieren. Ein log mit debug channel 7 sagt vielleicht mehr.

**Comment by nimanox** [comment]
wie mache ich den ?

**Comment by Tensuko** [comment]
CP HUD Settings die 7 anklicken (wird grün) und dann Kurs generieren mit der Anzah Tools und den Traktor für die entsprechende Seite einstellen. Das logfile dann hier posten, wäre in dem Fall gut wenn es nicht klappt wie es soll, damit man sieht was da schief läuft. Bitte mit der aktuellen CP Version machen.

**Comment by nimanox** [comment]
hab ich gemacht soll ich den dann ne weile wrten wo der nichts macht ? oder dann gleich aus dem spiel raus gehen und log posten?

**Comment by Tensuko** [comment]
Im prinzip egal. Es geht nur ums generieren des Kurses bzw des Offest Kurses wenn der Fahrer eingestellt wird.

**Comment by nimanox** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4326019/log.txt)

**Comment by pvaiko** [comment]
Das ist das Problem:
2020-03-12 20:08 :31 [dbg7 lp5531] Recursion limit of 200 reached for headland generation
Da stimmt irgend etwas mit dem Kurs nicht, kannst du das Kurs XML File hier posten?

**Comment by nimanox** [comment]
heist den kurs speichern und dann aus cp raus suchen und posten?

**Comment by nimanox** [comment]
braucht ihr noch irgend etwas ?
