### ISSUE TITLE
Bug, Can't stop Mode 8 driver after 394 release

### ISSUE THREAD

**Issue by MtBakerScum** [Courseplay/courseplay#5029]
Can't stop my mode 8 driver anymore after the 394 release.  Noticed the bugs with multi vehicles in with 393 release, 394 fixed most of what I noticed, except for this bug where I can no longer stop the driver without a reset of the game entirely.  Vehicle also seems to think its in traffic when its not, and will continue in a straight line after not making a turn.  All my other courses seem to be running fine
![20200308114231_1](https://user-images.githubusercontent.com/54657774/76169107-78226300-6132-11ea-9c9c-b03b288f14b1.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/4303689/log.txt)

**Comment by MtBakerScum** [comment]
Actually a couple of my Mode 1 courses seem to be effected too, drivers driving off course

**Comment by pvaiko** [comment]
Won't be able to fix this until we have at least one concrete example with detailed description or video and log with debug channel 12 and 14.

**Comment by MtBakerScum** [comment]
@pvaiko log i attached has channel 12 and 18. I'll create a new one with channel 12.  Not sure how to record ingame, I'll look into it

**Comment by MtBakerScum** [comment]
Log with Channel 12, 14, and 18
[log.txt](https://github.com/Courseplay/courseplay/files/4303769/log.txt)

Video, didn't drive off course, but did encounter traffic when all surrounding vehicles were off and should have been far enough away.  Sorry for the music, did turn it off so you could here me clicking the stop course button.
https://youtu.be/kcYce42mEhM

**Comment by MtBakerScum** [comment]
Trying to recreate a video of Mode 1 trucks driving off course but not having any luck. Always seems to happen when you're not paying attention, right?

**Comment by Tensuko** [comment]
Sidenote:
For Transporting to another Silo you should use Mode1.
Mode8 is basically like Mode1, but you add a Waitpoint to tell the Driver where to overload into a Container or wait for a Fieldworker.

**Comment by MtBakerScum** [comment]
@Tensuko I thought Mode 8 was used for transporting liquids to the field? In the video I'm transporting digestate from my silo to a wait point next to the field for my Digestate spreader to refill from

**Comment by Tensuko** [comment]
I was confused by the bypass of the Tank.

**Comment by MtBakerScum** [comment]
Ah sorry, I made it leave the wait point 100% so it didn't need to refill at the tank

**Comment by Tensuko** [comment]
This is even more Confusing :)
Mode8:
- Start at a Source for liquid manure or digestate just like you would do at mode1. Then make a waitpoint where you want to fill up a fieldcontainer or where you want your transporter to wait for a fieldworker to refill at your mode8 driver.

Wont change the fact, that the mode8 driver cant be stopped, but this is how mode8 works :)

**Comment by MtBakerScum** [comment]
Mode 8 courses don't start at the source? At least according to the manual they don't.  And my course had been working just fine previously
![manual_mode8_en](https://user-images.githubusercontent.com/54657774/76172246-0a396400-6151-11ea-8e54-d7b217d6d057.jpg)

**Comment by Tensuko** [comment]
For CP6 now they do.

**Comment by Tensuko** [comment]
The Actual Plan for Mode8 was to change it to a Fieldsupply Mode, wich works like Mode1 but with the Waitpoint for, as I already said, overload to a Container or wait to let Fieldworker refill there, expanded to Seed and Fert and everything that could be needed on Field, but we kept it first for the 2 Liquids.

That it can fill up in the mid of the Track wasn't intended as I understood it right, since we wanted it to be 'Load on Trigger between stop and start or wait at start untill it is loaded (as said, like mode1 works).

@pvaiko Maybe this is the Issue here, that it keep looking for a Trigger on the Course itsel ?

**Comment by pvaiko** [comment]
@Tensuko no, it's because the FieldSupplyAIDriver is derived from FieldworkAIDriver, no idea why (was not involved in this) since as far as I know, you should not be doing fieldwork in Mode 8.

**Comment by MtBakerScum** [comment]
Ah, I will redesign my Mode 8 courses then. Is there an updated piece of documentation to describe all the Modes as they currently work?

**Comment by pvaiko** [comment]
@MtBakerScum 395 should have fixed it.

And, no there's no updated docs, we are still looking for volunteers to update them.

**Comment by MtBakerScum** [comment]
What're your requirements for volunteers?

**Comment by pvaiko** [comment]
We aren't very picky :) Anyone is more than welcome to contribute as long as can write understandable English (or German for that matter) sentences.

**Comment by polosubtil** [comment]
Hi @pvaiko 
I can do a bit if you want, that's kind of what I use to do in farm machinery !!!

**Comment by pvaiko** [comment]
@polosubtil absolutely, what would you like to start with?

**Comment by polosubtil** [comment]
@pvaiko, do we have a proper chat or another way to communicate for that ?
I was thinking about starting from the beginning, how to set up a course and the description of the modes (already done but it might need a few updates), and then describe all he setting to set a course in a field. But it's up to you, what's urgent in your mind ?

**Comment by pvaiko** [comment]
shoot me an email github@vaiko.us

**Comment by Tensuko** [comment]
Ehm, I would say this is fixed and the rest will be communicated per Mail ?
