### ISSUE TITLE
Full Combine Runs Away When Full

### ISSUE THREAD

**Issue by aletheist** [Courseplay/courseplay#5030]
I have two courses generated for fieldwork and appended them together, expecting the combine to work one field, stopping for unloading, and then pathfind between the end of one course and the start of the next and do the same.

Instead, the combine gets to the point in the first field where it is full, raises its tool, simply runs all the waypoints. It does pathfind as expected and makes it all the way to the end of the second field.

**Comment by Tensuko** [comment]
This is not how it works in any way.

For any Fieldwork, only one Fieldwork Course.
When you want the Combine unload itself, just run the Combine Fieldcourse and Activate Self Unload under Advanced Settings and place a Trailer within 20meter of the Fieldborder (works very good when 2 Preturns are finished).

**Comment by aletheist** [comment]
Thanks, what I want to do just isn't possible.
