### ISSUE TITLE
Turn angle (maybe) incorrect

### ISSUE THREAD

**Issue by vemendoza** [Courseplay/courseplay#5031]
Hi guys, maybe this problem came back again.

I'm using CP 394, with 2 tractors (muti tools). When my tractors start turn, CP is using an angle too large...

![Desktop Screenshot 2020 03 08 - 18 41 55 37](https://user-images.githubusercontent.com/48180617/76172399-25699b00-6174-11ea-822c-eee8f0210a83.png)
![Desktop Screenshot 2020 03 08 - 18 42 01 64](https://user-images.githubusercontent.com/48180617/76172400-28fd2200-6174-11ea-87a4-58696ca63774.png)
![Desktop Screenshot 2020 03 08 - 18 42 10 79](https://user-images.githubusercontent.com/48180617/76172402-2dc1d600-6174-11ea-8b6a-ec28c348f39c.png)

, so when the tractor come back to the land, it need to correct angle and some piece of my land isn't worked.

![Desktop Screenshot 2020 03 08 - 18 42 19 09](https://user-images.githubusercontent.com/48180617/76172438-b771a380-6174-11ea-9df1-5a3bcb121d71.png)
![Desktop Screenshot 2020 03 08 - 18 42 26 54](https://user-images.githubusercontent.com/48180617/76172410-43cf9680-6174-11ea-91f5-d85bc783cc75.png)

A short time ago I saw this error, but was corrected.

Thank you guys.

[log.txt](https://github.com/Courseplay/courseplay/files/4303989/log.txt)

**Comment by MtBakerScum** [comment]
I also just noticed something similar, on a multi tool course. Side note, how do you get the purple track to show? I can't for the life of me figure that out

**Comment by MtBakerScum** [comment]
Also were your turn radii really, really large on auto? Mine were 164m on a Claas Exerion 5000 and 72 on a Unimog.  Wasn't sure if that was due to the plow I was towing or not.  Plow is a Mod John Deer 2410 Field Plow

**Comment by Tensuko** [comment]
@vemendoza 
what options do you have turned on ?
AI Turn, Pathfind, Turn on Field, etc ?

@MtBakerScum 
Debugchannel 14 for blue Line.
The Turnradius comes from the Tool and specialy Mod Tools could end up in a very big turn radius.

**Comment by vemendoza** [comment]
Hi again..., I don't know what is going on, but this time I created a fresh savegame and all works fine.

![Desktop Screenshot 2020 03 09 - 21 44 11 36](https://user-images.githubusercontent.com/48180617/76270179-0d1c7d80-6253-11ea-8b82-01a0ab97d557.png)
![Desktop Screenshot 2020 03 09 - 21 44 20 56](https://user-images.githubusercontent.com/48180617/76270184-0f7ed780-6253-11ea-923f-268735e307fe.png)
![Desktop Screenshot 2020 03 09 - 21 44 27 24](https://user-images.githubusercontent.com/48180617/76270186-11489b00-6253-11ea-81e4-34845d86bf9b.png)

So, maybe it's a problem with other mods. I'll be investigate.

Sorry guys and please, close this issue. Thank you
