### ISSUE TITLE
Combine fault while unloading while pipe is over unharvested field 

### ISSUE THREAD

**Issue by Djarnis1** [Courseplay/courseplay#5032]
when combinen driving with pipe over the unharvested field and carting tractor comming up on its side in the unharvested field, it starts unloading but combine goes backwards to give space for the tractor  to not stand in the field and then driving away from the tractor/trailer standing in the unharvested field. 
cant seem to find any way to stop this

**Comment by Tensuko** [comment]
See #3311 and #4286 
Closed.
