### ISSUE TITLE
Combine fault while unloading while pipe is over unharvested field.. (not a dublicate)

### ISSUE THREAD

**Issue by Djarnis1** [Courseplay/courseplay#5034]
Tensuko closed the thread but linked to 2 other threads but they wasnt what i meant with it..
This time i provide a screenshot.. since it had nothing to do with corn but most other crops.
![Combine 0](https://user-images.githubusercontent.com/61974328/76240455-9328cc00-6233-11ea-9f71-93864a39dd8e.jpg)
![Combine 1](https://user-images.githubusercontent.com/61974328/76240466-96bc5300-6233-11ea-9c1c-5556be514937.jpg)

and with this its going into a loop.. tractor comming up on left side.. 
combine detects tractor, drive backwards away from crops, wait, continue and detects tractor and repeat. 

when combinen driving with pipe over the unharvested field and carting tractor comming up on its side in the unharvested field, it starts unloading but combine goes backwards to give space for the tractor to not stand in the field and then driving away from the tractor/trailer standing in the unharvested field. cant seem to find any way to stop this

**Comment by Tensuko** [comment]
Ofc it have to do with #3311 and #4286 

But you can stop this when you turn off Fruitbypass for the Combine.
