### ISSUE TITLE
Drive mode seems bugged.

### ISSUE THREAD

**Issue by Phobs** [Courseplay/courseplay#5035]
Hey guys,

Drive mode seems quite bugged, I mean, game mechanics get totally broken.
For example, say you have a tractor pulling a baler, if instead of choosing fieldwork when you start the course you choose transfer mode and before starting the course you turn your baler on and lower it and then start the course, it will run the course at tractors full speed so if you have like a 73 kph tractor you're baling at 73 kph totally ignoring the balers 20 kph limit.. now obviously transfer mode should not be used for fieldwork, but nothing stops you so you can completely ignore mechanics.
Another thing you can do is run a forage harvester the same way and it doesn't even need to unload it just keeps harvesting the entire field at 41 kph and keeping all the chaff inside until you decide to unload in a tipper and it will just fill that tipper multiple times until the entire field is basically emptied in one go. I did not try other tools like cultivators and regular harvesters but I'm gonna guess it'll be the same!

I don't think this godmode is by design so I figured I'd report it, it's really easy to reproduce so I don't think screenshots or logs are needed on this one, the version I'm using is 6_01_00391 in case that does matter. :)

It is quite funny if you ask me, I just happened to forget to switch modes and I see myself baling at top speed, then I was like woah let's try to reproduce this with a forage harvester and see what happens, and the results were totally unexpected, had to roll back my safe game cause that's just crazy!

Edit: Ignore the forage harvester part apparently it does that when you have a trailer attached and not related to courseplay, ignoring its speed is though, since the speed should be limited to 10 kph by the header but transfer mode goes the harvesters full speed.

**Comment by Tensuko** [comment]
I have a nice tip for you: gsCheatMoney X and X = the amount you want.
If you want to play the game like it should be played, use CP like it should be used.
Not going to do anything about it, else you can drive a Tool from A to B.

Closed...

**Comment by Phobs** [comment]
Wow. Not sure who pissed in your cereal. Obviously I did not mean for it to happen and I simply forgot to switch, did some further testing to see if it happened with other things, rolled back my save game, and decided to make a bug report because it clearly is and which you do when something is in beta. Now it's fine if you don't want to do anything about it, that's up to you, but you can keep your "tips" to yourself and just respond normally.
