### ISSUE TITLE
LS19 Courseplay - Bahnversatz geht nicht mehr

### ISSUE THREAD

**Issue by BrunoMoser13** [Courseplay/courseplay#5036]
Hallo !

Seit der Courseplay-Version 6 01 00388 geht der Bahnversatz nicht mehr.
Ich benötige diese Funktion um den Ballensammelwagen seitlich versetzt arbeiten zu lassen.

Bitte um Rückmeldung

**Comment by Tensuko** [comment]
Welche Version benutzt du, Logfile debugchannel 9 12 und 14, Screenshots vom Kurs und der HUD Einstellung und am besten wie der Abfahrer nunr fährt.

**Comment by BrunoMoser13** [comment]
Ich benutze AD 1  0 7 2 und CP 6 01 00395. In der Log gibt es keine Fehler. Debugchannel habe ich noch nicht benutzt.
Wenn ich auf die CP Version 6 01 00387 zurückwechsle funktioniert der Bahnversatz. Ab der Version ..00388 eben nicht mehr. Hier fährt der Abfahrer immer auf der Arbeitsspur egal wohin ich den Bahnversatz stelle.

**Comment by Tensuko** [comment]
Du machst im CP HUD unter Settings die Zahlen auf grün und lässt dann den Kurs fahren und stellst die Zahlen ein.
Dabei fällt mir ein.... Warum Arbeites du eigentlich mit Bahnversatz und nicht mit Geräteversatz ?

Kleine Info noch am Rande: Egal ob im Logfile fehler sind oder nicht, man kann daraus mehr lesen als mach einer glauben mag...

**Comment by BrunoMoser13** [comment]
Okay - werde ich ausprobieren wenn ich am PC bin.... dann kann ich auch ein Logfile einstellen.

Geräteversatz funktioniert zum Einsammeln von Ballen mittels Pickup und Ballensammelanhänger nicht!

**Comment by Tensuko** [comment]
Warum nicht ?

**Comment by BrunoMoser13** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4312936/log.txt)

**Comment by Tensuko** [comment]
Und wie das mit dem Geräteversatz geht... Man sieht den Arbeitsbereich und was ich als Offset eingestellt habe...
![fsScreen_2020_03_10_18_43_48](https://user-images.githubusercontent.com/27344744/76342593-23801300-62ff-11ea-908d-c9ac310aa3a3.png)

**Comment by BrunoMoser13** [comment]
Also das mit dem Geräteversatz geht jetzt mit der CP Version ...395.  Ich kann den Ballenanhänger damit aus der Spur fahren lassen.  
Der Bahnversatz geht aber trotzdem nicht - sollte aber, da es ja eine Funktion im CP ist.

Das LOG file habe ich reingestellt.

**Comment by Tensuko** [comment]
Der Banversatz funktioneirt auch für den Multitool betrieb bei einem Kurs mit 2 oder mehr Geräten, dafür ist dieser da.

**Comment by BrunoMoser13** [comment]
Hat sich seit der Version 387 etwas geändert?Hast du dir meine Log angesehen?--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 11.03.20, 09:11 schrieb Tensuko <notifications@github.com>:

  Der Banversatz funktioneirt auch für den Multitool betrieb bei einem Kurs mit 2 oder mehr Geräten, dafür ist dieser da.

**Comment by Tensuko** [comment]
Ich weis nicht was du von mir willst, ja dein log habe ich gesehn, was sich geändert hat steht bei den Release bei, 388+ Multitool Rework, seit dem kannst du den Bahnversatz nicht mehr in Meter einstellen, für deinen Anwendungsfall ist der Geräteversatz da und der Bahnversatz bei der Verwendung von 2 oder mehr Geräten.

**Comment by BrunoMoser13** [comment]
Okay. Danke --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 11.03.20, 09:17 schrieb Tensuko <notifications@github.com>:

  Ich weis nicht was du von mir willst, ja dein log habe ich gesehn, was sich geändert hat steht bei den Release bei, 388+ Multitool Rework, seit dem kannst du den Bahnversatz nicht mehr in Meter einstellen, für deinen Anwendungsfall ist der Geräteversatz da und der Bahnversatz bei der Verwendung von 2 oder mehr Geräten.
