### ISSUE TITLE
Ernter fährt Rohr aus und sofort wieder ein

### ISSUE THREAD

**Issue by ItsSimon05** [Courseplay/courseplay#5037]
Hallo,
ich habe einen Holmer im Einsatz (Standard) und denn auf der NF Marsch als Ernter mit CP im Einsatz. Der Ernter fährt aber das Rohr ned aus auch ned wenn er voll ist. Wenn ein Abfahrer in die Nähe kommt und daneben steht, fährt er das Rohr aus und gleich wieder ein und das dann immer wieder. 
Was kann ich machen um dies zu beheben`?

Vielen Dank für die HIlfe schon mal im Voraus.

Version: 6.01.00395.dev

**Comment by ItsSimon05** [comment]
![image](https://user-images.githubusercontent.com/54044024/76325622-d2b0f000-62e7-11ea-8557-0e246e059d4f.png)

**Comment by Tensuko** [comment]
Passiert das auch, wenn du den LKW selber hin fährst ?

**Comment by ItsSimon05** [comment]
ja

**Comment by Tensuko** [comment]
Konnte ich nicht reproduzieren, bitte einmal das logfile posten (drang and drop in die Kommentarbox)

**Comment by ItsSimon05** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4318816/log.txt)

**Comment by Tensuko** [comment]
Error: Invalid mod name 'FS19_GlobalCompanyPlaceable_BGA_GrimmeBeetBeater (1)'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Load mod: FS19_GlobalCompanyPlaceable_BGA_GrimmeBeetBeater (Version: 1.0.1.0) (Hash: 47b5474f5c5ad7f972a942d4bdec9d9f)
Error: Invalid mod name 'FS19_GlobalCompanyPlaceable_FermentingSilo (1)'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Load mod: FS19_GlobalCompanyPlaceable_FermentingSilo (Version: 1.0.1.0) (Hash: 1f0c60cafb214283ac5f61e04a0d1e47)

Bitte dafür sorgen, dass du nur eine Version drin hast!

Genauso hier den Namen ändern:

Load mod: Fliegl_Animal_Transport_Pack (Version: 2.1) (Hash: 9df05435ead0c2a0d642fafd544286bf)
Error: Unsupported mod description version in mod Fliegl_Animal_Transport_Pack

Nur eine Map im mods Ordner, ganz wichtig besonders wenn man 2 ähnliche Maps hat:
Load mod: FS19_NF_Marsch (Version: 2.5) (Hash: a934eec7de77ea677b11d8886377cb89)
Load mod: FS19_NF_Marsch_4fach (Version: 1.4) (Hash: 34025731d579310678699934e68115e2)

Ansonsten keine Auffälligkeiten.

**Comment by ItsSimon05** [comment]
Das mit der Karte und denn Namen ist mir selbst aufgefallen beim Durchgegehen der Logs und hab das auch behoben. Wäre es evtl iwie möglich damit der Ernter einfach das Rohr immer ausgefahren hat?

**Comment by ItsSimon05** [comment]
Ich habs behoben. Der Anhänger haut eine Funktion eine Leiter auszuklappen und dadurch erkennt der Ernter nicht damit der Anhänger beladen werden kann und fährt das Rohr wieder ein :D Anderer Hänger und ging

Trotzdem danke @Tensuko

**Comment by Tensuko** [comment]
Na dann haben wir ja den Übeltäter :)
Rohr immer Ausgefahren war auch ein Wunsch, mal sehen ob man das in den Settings untergebracht krigt, bei normalen Dreschern würde das aber nur zu weiteren Problemen führen.
