### ISSUE TITLE
Harvester do not lower the header after rain

### ISSUE THREAD

**Issue by Misamangame** [Courseplay/courseplay#5039]
Hello guys, 
I'm using CASE 9240 harvesters and when the rain start they stop the work and header is raised. Unfortunately when rain stops they continue in their way by course but do not lower the header, and therefore not harvesting :) I'm using old combi mode and I know there is no suport, it is just note to take it into consideration when you are doing new one. Not sure if  someone else experinced this.

**Comment by Merrlin** [comment]
No worry's Harvesters are Mode 6.  So it is a "supported" bug. But we need a Logfile too.

**Comment by Misamangame** [comment]
ok I will when my next harvest season starts

**Comment by McGamer1998** [comment]
Hello,

we play the mod in multiplayer (even if not released for it) and the problem does not only occur after a blockcade. Even if we are just starting the course it often happens that cutters or machines are not lowered/started. We helping us with „close" the machine and restart it... are there any news about the bugfix yet?

Best Regards

Patrick

**Comment by Tensuko** [comment]
Can someone try to reproduce this with .00064 ?

**Comment by Misamangame** [comment]
Hello guys, I'm providing logfile with .00066 version of CP.  When rain starts all 3 harvesters raised headers and stop engines and when humidity went down (using Seasons), all harvesters started and continued without lowering headers down. (Logfile) BUT I did some more testing and there are expections on that. I have always convoy on and when harvester which is in convoy is on desired distance (for example 200m) and harvester before him stopped because of waiting for unloader and rain starts this harvester will leave header down, engine running during the rain and when humidity is down he will continue normally. 
Maybe it will helps

[log.txt](https://github.com/Courseplay/courseplay/files/5397504/log.txt)
