### ISSUE TITLE
game freeze after activating a course

### ISSUE THREAD

**Issue by Dan-Gecko** [Courseplay/courseplay#5040]
game version: >log.txt
mod version: >log.txt
other mods:  >log.txt
type used: combi
files attached:
[courseStorage0004.xml.txt](https://github.com/Courseplay/courseplay/files/4318073/courseStorage0004.xml.txt)
[log.txt](https://github.com/Courseplay/courseplay/files/4318171/log.txt)

INTENT: create a course to overload from a specified combine and unload to an auger feeding a silo using an auger wagon

MACHINES:
  Tractor - massey ferguson 8737
  auger wagon - HaulMaster with max capacity

OCCURRENCE: after activating the course the game freezes

HOW TO GENERATE: starting a course with type:combi - driving the course to teach - switch to a specific combine in settings - don't change any other setting - activate - semi-freeze (get out of cab, total freeze, open map - only field graphics remain, other stuff vanishes - can't close map with "ESC" - freeze)

Testing done so far: 
- the position of start/end do not matter
- specified field number instead of combine does not matter
assumption: could be the trailer - script does not understand how to unload an auger

additional information (i.e. pictures) can be provided if needed

**Comment by Tensuko** [comment]
> type used: combi

This is Mode2, see sticky #3311 and #4286 
Closed.
