### ISSUE TITLE
Idee: Serielles Sammeln mit Sammelwagen / Abfahrer (Combi-Mode) übergibt an AD

### ISSUE THREAD

**Issue by DerBauer2** [Courseplay/courseplay#5042]
Könnte man das umsetzen das wenn man 2 oder mehrere Ladewagen auf einem Feld hat oder haben möchte das der letzte Ladepunkt vom Ladewagen übergreifend zu dem anderen Fahrer Mittgeteilt werden kann? Also das der 2. Fahrer dort an fängt wo der 1. aufgehört hat. Vlt kann man das auch so gestalten das der 2. oder 3. Fahrer Wartet bis der 1. Fertig ist mit laden und an diese Stelle fährt und weiter beläd.

Kann man auch mit CP häxlen abfahren aber nach beladenung vom häxler zum feld fährt und dann erst an AD übergiebt ?

Danke :)

**Comment by Tensuko** [comment]
Zum ersten Teil.
Also serielles Arbeiten und nicht parallel.
Die Idee ist interessant, wird aber nicht leicht umzusetzen sein.
Wo wartet denn der 2ten Sammelwagen bis der erste voll ist und warum sollte er warten ?
Da würde ich eher schauen was passiert wenn 2 im Convoy fahren, ob die sich neu einordnen, auch wenn einer dann eine Leerfahrt macht... richtig Sinn dahinter sehe ich nicht...

Zum zweiten Teil:
Nur schwer verständlich, aber ich denke mal du meinst AD fährt auf der Straße bis zum Feld, dann übernimmt CP das Abfahren des Häckslers und wenn der Abfahrer voll ist fährt er wieder zum Feldrand und übergibt an AD.
Ich denke dass das so oder so kommen wird, aber nicht bevor unser neuer Mode2 entsprechen funktionstüchtig ist.

**Comment by DerBauer2** [comment]
> Zum zweiten Teil: 

Jap genau so 

> Zum ersten Teil.

Man könnte es auch so gestalten das jeder Abfahrer eine Reihe übersprinngt. 
![grafik](https://user-images.githubusercontent.com/60297613/76448909-6c050280-63cb-11ea-8525-7b35c1ba3c07.png)

Hoffe man versteht das.

**Comment by Tensuko** [comment]
Das lässt sich leicht realisieren, indem du 2 Drescher als Mutlitool laufen lässt, dann hättest du bereits 2 Bahnen (links/rechts) und müsstest auch nicht mit skip row arbeiten.

Oder du lässt den Drescher normal arbeiten, nimmst für die beiden Sammelwagen die gleiche Arbeitsbreite deines Dreschers, aber sagst du hast 2 Fahrzeuge auf dem Kurs, dadurch verdoppelst du die Arbeitsbreite und wärend Sammelwagen A auf der ersten Bahn vom Drescher fährt, fährt der Sammelwagen B schon auf der zweiten Bahn (wenn ich mich da jetzt nicht vertan haben)

Man könnte noch weiter mit Arbeitsbreiten, Anzahl Fahrzeuge, Startposition, etc weiter rum spielen um zu einem ähnlichen Ergebnis zu kommen.

**Comment by DerBauer2** [comment]
Problem ist du musst die genauen meter haben und das geht nicht so genau ein zu stellen dann verschiebt sich das 
auserdem muss das ja für Gras und Stroh gelten da wäre es leichter dies einzubauen in CP
zumal man nicht immer mit 2 Dreschern fährt

**Comment by Tensuko** [comment]
Das macht es nicht leichter ein zu bauen...

Vom großen Schneidwerk die 13.7m z.B. sind einstellbar und das für 2 Geräte für die Sammelwagen wäre machbar. Ich stelle das mal nach wenn ich Zeit habe...

**Comment by DerBauer2** [comment]
CP möchte man ja Benutzefreunlich gestalten da wäre so eine Funkzion wirklich hilfreich. Aber eins nach dem anderen.

**Comment by Tensuko** [comment]
Das werden wir so nicht umsetzen können, dafür müsste viel geändert werden.
Eventuell irgendwann mal in ähnlicher Form.
