### ISSUE TITLE
Error: Running LUA method 'packetReceived'. attacherjoints?

### ISSUE THREAD

**Issue by twistedsanity** [Courseplay/courseplay#5044]
When this error appears all courses in game seem to be swapped and do not appear as the one you load. Also anyone currently in the game can continue to play, but no one else can join until the server is resrtarted. (stack trace on server AIvehicle.lua (241) : streamWriteUint, Argument 1 has wrong type)

Although I have a number of mods I have cleared out the directory, used a new save and still run into the issue.           

https://gist.github.com/twistedsanity/bd554abaea37c87ebf52006fca35be2b 
Log from client

This issue is on a multiplayer dedicated server.

**Comment by twistedsanity** [comment]
Not sure if related at all but also I I am finding that the behavior of "turn on filed" seems to be reversed in this config too.

**Comment by Tensuko** [comment]
Collecting all in #5484
