### ISSUE TITLE
No Helper Loan

### ISSUE THREAD

**Issue by TheWolf28** [Courseplay/courseplay#5046]
Hi there, 
I have the 395 version, but now, there is no more a loan for the CP helpers.

Did someone have a solution for this problem?

Theres also no question at the gamestart, if i want to pay or not for the helpers

**Comment by Tensuko** [comment]
Did you check advanced settings ? The loan system was reworked.

**Comment by Justice-Molton** [comment]
Same here. we use it on our dedi and checked the adv settings. but the helpers working for free.
MP, Dedi, CP397

**Comment by Tensuko** [comment]
Does @TheWolf28 also play in MP ?

**Comment by Tensuko** [comment]
Collecting all in #5484
