### ISSUE TITLE
Flüssigkeitentransporter lädt nicht ab

### ISSUE THREAD

**Issue by AngeloMerte** [Courseplay/courseplay#5049]
Hi,

habe das Problem, dass wenn ich eine Route vom Wasserbehälter zur Brauerei erstelle, der Trigger zum Abladen scheinbar nicht erkannt wird. Er fährt den Kurs normal ab, hält auch am Wassertank und belädt, fährt dann aber einfach am Wassertrigger vorbei. Was mache ich falsch? Habe es durch einfach vorbeifahren probiert, ebenso habe ich testweise einen Abladepunkt hinzugefügt, er fährt aber immer einfach weiter.

**Comment by AngeloMerte** [comment]
Wenn  ich das Ganze über den normalen Abfahrer einstelle, fängt er am Trigger an abzuladen, fährt dann aber auch einfach weiter und entlädt demnach nie komplett, sondern immer nur einen Teil

**Comment by Tensuko** [comment]
- Komplettes Logfile ( https://github.com/Courseplay/courseplay/wiki )
- Zum Wasser transportieren Mode1 mit entsprechendem Trailer (aktuell nur Mod Trailer, wird noch geändert)
- Kurs: Als wenn man am normalen Silo etwas aufladen will und weder Wartepunkt nocht Abladepunkt, Trigger ist Trigger, da gehört kein andere Wegpunkt hin.

**Comment by AngeloMerte** [comment]
Nach weiterem Herumprobieren habe ich das Problem lösen können. Der zweite Wegpunkt am Start war scheinbar durch eine Kurve bedingt so nah am ersten Wegpunkt zum Beladen, dass er direkt den nächsten Wegpunkt anvisiert hat, bevor er den Trigger erkannt hat.

**Comment by AngeloMerte** [comment]
Danke trotzdem für die Info. Eine Frage hätte ich noch, für welches Szenario benutzt man den Flüssigkeitentransport?

**Comment by Tensuko** [comment]
Also der Mode8 heist NOCH Flüssigkeitstransport, weil in älteren Versionen mit Flüssigkeiten anders umgegangen wurde. Ich habe den Modus schon umbenannt in der Translation zu 'Feldversorgung'.

Er funktioniert im Grunde wie Mode1, nur das man mit einem Wartepunkt, folgende Optionen hinzufügen kann:
- Der Fahrer wartet selber am Feldrand, so dass ein z.B. Gerräste Ausbringer mit einem normalen Nachfüllkurs bei dem Mode8 fahrer auftanken kann (geplant war mal das gleiche für Saatgut und Dünger, wissen aber noch nicht wie wir das machen).
- Oder der Fahrer einen Feldcontainer auffüllt (sozusagen als Puffer) und der Feldarbeiter sich am Container auffüllt.

**Comment by AngeloMerte** [comment]
Alles klar, dank dir :)
