### ISSUE TITLE
missing .zip for 397

### ISSUE THREAD

**Issue by Justice-Molton** [Courseplay/courseplay#5053]
you've forgot to attach the .zip to the actual release.

**Comment by pvaiko** [comment]
That's done by my server automatically through the GitHub API, let me check what happened....

**Comment by uded** [comment]
Seems OK already

**Comment by pvaiko** [comment]
yeah, just redelivered. When I last checked, GitHub said there's no limit on the number of releases, let's see if the next one works, this first delivery returned an error (HttpError: Error saving asset), then I deleted and old release, it worked afterwards. 

Leave open for now.

**Comment by moose31608** [comment]
How do you do for the right implement to be able to run 2 tools

**Comment by Tensuko** [comment]
> 
> 
> How do you do for the right implement to be able to run 2 tools

?? If you have any specific question make an own Issue and discripe it a bit more in detail, when you ask about how to set up 2 Tools for one course, check those several YT Tutorials.
