### ISSUE TITLE
Convoy Issue with Headland

### ISSUE THREAD

**Issue by Bobster82** [Courseplay/courseplay#5054]
@pvaiko , changes u made in v6.01.00387 made the convoy option not working correctly... At start the following tractor is at a right distance, but the 2nd tractor is passing the 1st tractor after a while, the actual position of the tractor and the purple line are different.  The 2nd tractor is pulling his a point way behind him (the purple line)  as seen in screenshots below... Both are v6.01.00387 , but you didnt change the version with a the commit.

I hope u understand what I mean. If u need anything else, let me know. Thanks in advance

![2 seeders cp v387_Broken](https://user-images.githubusercontent.com/47780758/76682362-de5c2980-65fb-11ea-8e06-08b1ca0b634c.jpg)

![2 seeders cp v387_OK](https://user-images.githubusercontent.com/47780758/76682364-e025ed00-65fb-11ea-8fd7-75c67399e689.jpg)

**Comment by Tensuko** [comment]
What about Update to latest Version ? https://github.com/Courseplay/courseplay/releases

(Wait for 397 .zip file or go for 396 Version)

**Comment by Bobster82** [comment]
I tried all versions above 387 and they are all broken... just tried the 396 too ;)

**Comment by Tensuko** [comment]
You know I tested a Mutlitool setup 5min ago and it worked....
Also your distance is set to 30m in HUD Settings I don't see something wrong there.

**Comment by Bobster82** [comment]
I have it on those 2 tractors and i also tried with 3 combines... 2 combines worked, the 3rd one has his purple line 200m behind him....

In the 2nd screenshot its correct, purple line on the tractor, 30m in the settings and u can see its 30m behind...
In the 1st screenshot its wrong, purple line way behind the tractor, 30m in the settings and u can see its 205m behind (but the tractor is way closer... the 1st tractor is at 3km/h, so the 2nd tractor will pass it then... (just for testing)

**Comment by pvaiko** [comment]
@Bobster82 yeah, the convoy code works with waypoint indexes and not with distances, and now that the offset course is generated, the inner one has less waypoints. Should only matter on the headland though, the up/down part has the same number or waypoints.

**Comment by Bobster82** [comment]
@pvaiko , Ah, that explains the 2 vehicle modes ;) and yes its only on the headlands that the distance is changing every corner, the up and down stays around the same distance.

But what about 3 combines? The 1st combine is driving on the left of the line and "index" or "purple line" is right next to it... The 2nd combine is driving at the center of the line and the purple line is right above it.... The 3rd combine is driving on the right of the line, but the purple line is way back....

So why is the 1st and 2nd using the same "index" and the 3rd a different index?
And why is this changed this way? needed for other problems? I was out for a bit, so didnt follow every step :P 

Is it possible that they all use the same "index" ? Else I need to change the distance on every restart of the game (standard is 100m)

**Comment by pvaiko** [comment]
The change is explained hopefully in https://github.com/Courseplay/courseplay/releases/tag/6.01.00388 , was mainly to fix the multitool inner courses.

I'll figure out something.

**Comment by Bobster82** [comment]
> The change is explained hopefully in https://github.com/Courseplay/courseplay/releases/tag/6.01.00388 , was mainly to fix the multitool inner courses.
> 
> I'll figure out something.

Thanks, I understand it makes multiple copies of the line when started the route. And yes its working better with multiple tools. Can u maybe let the convoy calculations be made from the original route or from the 1st vehicle in convoy? Is that posible or do I ask too much? :P

**Comment by Tensuko** [comment]
Is this one still valid ?
Didn't had any more Issues so far about this one.

**Comment by Bobster82** [comment]
Last time i had issues, but that was a few commits back. Im on holiday atm, so i cant test now.

**Comment by Tensuko** [comment]
Worked fine for me, will close this one, anything new, check issues if there is existing one or make a new one.
