### ISSUE TITLE
wendemanöver problem beim aussäen mit 397

### ISSUE THREAD

**Issue by nimanox** [Courseplay/courseplay#5056]
mit dem neuen patch habe ich das problem das sich der tracktor mit der Sämaschine an jeder ecke festfährt weil er beim rangieren zu sehr einlenkt bezieungsweile nicht mittig zurücksetzt sind leicht versetzt und am ende hart einlenkt um zur mitte zu kommen

http://prntscr.com/rgaig0

http://prntscr.com/rgaexn

wen er eine 180grad drehung macht lässt er ein stück am ende stehen bzw säät es nicht
http://prntscr.com/rgak6d

[log.txt](https://github.com/Courseplay/courseplay/files/4332907/log.txt)

**Comment by Tensuko** [comment]
Debugchannel 7 9 12 und 14 für das logfile bitte.

**Comment by Tensuko** [comment]
Kann es nicht reproduzieren:
![fsScreen_2020_03_14_16_22_04](https://user-images.githubusercontent.com/27344744/76684947-3b61da80-6610-11ea-91cb-4a02e035d431.png)
![fsScreen_2020_03_14_16_20_57](https://user-images.githubusercontent.com/27344744/76684950-3e5ccb00-6610-11ea-81d8-8c71a344b419.png)
![fsScreen_2020_03_14_16_20_07](https://user-images.githubusercontent.com/27344744/76684954-41f05200-6610-11ea-8bc8-95107fd36e86.png)
![fsScreen_2020_03_14_16_19_42](https://user-images.githubusercontent.com/27344744/76684956-4583d900-6610-11ea-8f9f-a7032ad43f30.png)
![fsScreen_2020_03_14_16_18_56](https://user-images.githubusercontent.com/27344744/76684957-4a488d00-6610-11ea-9de4-94ad5b04d22f.png)

**Comment by nimanox** [comment]
http://prntscr.com/rgayja

[log.txt](https://github.com/Courseplay/courseplay/files/4332936/log.txt)

habe bis jetzt immer in denn ecken angefangen und ging bis jetzt immer gut^^

**Comment by Tensuko** [comment]
könnte gefixt sein mit V00016 mache erstmal zu da sehr alt.
