### ISSUE TITLE
FS19 v6.01.00397

### ISSUE THREAD

**Issue by DerBauer2** [Courseplay/courseplay#5058]
Die neue Pfadfindung? wie akiviere ich die oder ist diese Automatsch?

**Comment by Tensuko** [comment]
6.01.00397 Pathfinding updates

Use the new pathfinding everywhere (except mode 2)

Wide turns (spiral/racetrack or skip row modes) can now use
pathfinding to avoid fruit and stay on the headland during the turn
when enabled in the Advanced Options screen.

Added a new option to use reverse in pathfinding so vehicles without
towed implements can make shorter (3 point) turns when needed.

**Comment by DerBauer2** [comment]
Was? Ich wolte nicht die Patchnote die kann ich selber Nach lesen

Ich wolte das erklärt haben auf meine Frage?

**Comment by Tensuko** [comment]
Deine Antwort steht in den Patchnotes...

**Comment by DerBauer2** [comment]
na ich versteh das nicht so ganz könnte man mir das Bitte erklären?

**Comment by Tensuko** [comment]
CP HUD, Advanced Settings, Use Pathfind in Turns einschalten, fertig.

Wide turns (spiral/racetrack or skip row modes) can now use
pathfinding to avoid fruit and stay on the headland during the turn
**when enabled in the Advanced Options screen**.

Mehr gibt es da nicht zu verstehen, es ist ein Turn der übers Pathfind berechnet wird, so wie Combine Self Unload und ein paar andere Dinge die schon drin sind und munter im Hintergrund laufen.

**Comment by DerBauer2** [comment]
okay Danke sehr
