### ISSUE TITLE
Error: Running LUA method 'mouseEvent' - FieldworkAIDriver.lua:281: attempt to index field 'fieldworkCourse' (a nil value)

### ISSUE THREAD

**Issue by Justice-Molton** [Courseplay/courseplay#5061]
If we dismiss a CP driver, the vehicle gets frozen. The only way to get it back under control is to hit two times the hire button of AutoDrive. After that, we can control the vehicle again.
You can see the error at the end of the log. 

[log.txt](https://github.com/Courseplay/courseplay/files/4333977/log.txt)

**Comment by PHansen940** [comment]
I can confirm that we have the same problem. MP, Dedi, Hof Bergmann, newest versions of Courseplay and Autodrive
