### ISSUE TITLE
Fruchtzerstörung und Reifenspuren

### ISSUE THREAD

**Issue by Michael170978** [Courseplay/courseplay#5062]
Hi.

Frage:
Hab ihr noch vor Fruchtzerstörung und die Reifenspuren bei Courseplay einzuführen?
Denn obwohl Fruchtzerstörung bei mir aktiv ist, wird die Frucht unter bei Courseplay Einsatz nicht zerstört. Ich weiß ihr habt ganz andere Probleme, die zu erst gelöst werden sollten bzw müssten. Aber ein an/aus Button für Fruchtzerstörung wäre schon nicht schlecht.
Das andere was mir auffällt , daß unter Courseplay die Fahrzeuge keine Reifenspuren hinterlassen. Habt ihr noch vor die Option hinzufügen oder ist es nicht machtbar?

**Comment by Tensuko** [comment]
Das ist in der Tat eines unserer geringeren Sorgen und wird erst wieder aktiviert, sobald wir mit dem Pathfinder in allen Modi zufrieden sind :)

**Comment by Michael170978** [comment]
Alles klar. Danke für die Info

**Comment by Tensuko** [comment]
Ich mach hier zu weil es hier auf gefragt wurde: #5146
