### ISSUE TITLE
CP can't reverse straight with Horsch Meastro SW 24.75

### ISSUE THREAD

**Issue by SteelRodent** [Courseplay/courseplay#5063]
CP is unable to keep the Horsch Meastro SW 24.75 (18 m planter from the free Horsch DLC on modhub) straight when reversing. Both during regular up/down lanes and on header turns, after turning around - whether it's a corner or lane change - it'll reverse, but then the machine veers off to the side before moving forwards, so you get a few meter strips of unworked field at the end of every lane.

![20200316143540_1](https://user-images.githubusercontent.com/20990941/76763634-cae3c680-6793-11ea-834a-0841c00bcfb8.jpg)
The further it has to reverse, the more the planter goes sideways.

It's much worse with an articulated tractor than a regular one, but it happens with both. As far as I've been able to test it doesn't happen with the vanilla helper, and CP don't appear to have any issues with the 9 and 12 m versions of this machine. CP also had no problem reversing with the 18 m cultivator using the same course, but then it's not as long as this planter.

Only tried this with 395 and 397. Haven't tried to use this planter in a really long time (or even played at all), so can't say if it's a new issue.

**Comment by Tensuko** [comment]
log with channel 7 9 12 14 active.
Also a screenshot of the generated course could help.

**Comment by SteelRodent** [comment]
Think I may have incidentally fixed the problem. Since the 9RX was behaving correctly, I decided to try resetting the vehicle settings for the QuadTrack (even though the CP UI said they were already at default values), and then it suddenly uses all of the 36m headland to turn around and don't bother to reverse on lane changes when there's plenty of space, so it doesn't miss parts of the field on the regular up/down lanes. It still struggles on headland corners so they're not perfectly 90 degrees, but they are much more acceptable.

![20200316190959_1](https://user-images.githubusercontent.com/20990941/76788734-d0550700-67bb-11ea-8036-a9d33a2f3360.jpg)

![20200316173213_1](https://user-images.githubusercontent.com/20990941/76788678-ab609400-67bb-11ea-83ac-47fd4fa67698.jpg)

[log.txt](https://github.com/Courseplay/courseplay/files/4339735/log.txt)

**Comment by Tensuko** [comment]
Well I was able to reproduce this and got a Video of it. Even the 1st run all worked fine and later it didn't (same Tractor and same Tool) I am not sure where it come from but I have an Idea.

Got to wait for it but as long as you can make it work it is ok for now.

**Comment by vemendoza** [comment]
@SteelRodent , I need to say that maybe this problem is very similar than mine in issue #5031, when a litle piece of land isn't worked when the tractor turns.

But with your explanation, maybe you explain why when I created a new save game all works fine. I'm thinking that with new save game the file vehicles.xml was empty of CP configurations. Or another file, I don't know.

I'll try the last version of CP again.

Thank you

**Comment by Tensuko** [comment]
Should be fixed, pls test and report.

**Comment by Tensuko** [comment]
Should be fixed, if not let us know where to reopen it.
