### ISSUE TITLE
Courseplay und SpeedControl funktionieren nicht miteinander

### ISSUE THREAD

**Issue by ssnd292** [Courseplay/courseplay#5065]
Wenn [SpeedControl ](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=125190&title=fs2019)und Courseplay gleichzeitig genutzt werden, kann man in der SpeedControl Mod nicht die ersten zwei Geschwindigkeiten auswählen.

Ich denke, dass liegt daran wie Courseplay diese abruft. Ist es möglich dieses Verhalten anzupassen, damit beide Mods miteinander funktionieren?

Mods:
Courseplay_6_01_00397.zip
SpeedControl aus dem Hodhub

Log:
[log.txt](https://github.com/Courseplay/courseplay/files/4339718/log.txt)

**Comment by Tensuko** [comment]
Was heist gleichzeitig genutzt.
CP HUD ist an und du willst etwas ändern ?
Es könnte durchaus wieder unser Keybind-Problem sein.
Entferne einfach mal alle Keybinds die CP benutzt und probiere das ganze noch einmal aus.

**Comment by ssnd292** [comment]
Ja da hast du recht. Wenn ich 1 und 2 von CP entferne geht es - Habe daran nicht gedacht.

**Comment by Tensuko** [comment]
Ich mache das hier dann zu denn Keybind ist so ein generelles Problem....
