### ISSUE TITLE
courseplay, beet harvester and FS worker

### ISSUE THREAD

**Issue by vortex1988** [Courseplay/courseplay#5066]
hi,

In my game in Feldsbrunn the game make me this error:

Error: Running LUA method 'update'.
2020-03-16 17:04 dataS/scripts/vehicles/Vehicle.lua(2920) : attempt to index a nil value

and then the game is unpleyable. I have the error when I use the courseplay in the John deere tractor or when i use the same tractor sith the follow me mod. Is the first time that I have this error in 200 hour in this savegame, the game is unpleyable and I can't save also.

Ok, maybe I found the problem.
it happens when I use the beet harvester (for the tractor) and, at the same time, I use the courseplay to unload it with the trailer.
In particular, it happens when the filling percentage reaches the level where the tractor must start to start unloading the beets.

P.S: I wrote a new message, and not edit the first, because is the solution of the problem (waiting for a fix from the creator of the courseplay)/ I don't use classic FS worker ahahah :) :) 

[log.txt](https://github.com/Courseplay/courseplay/files/4339827/log.txt)

**Comment by Tensuko** [comment]
The LUA Error comes from GIANTS script, you can see it in the path, else it would contain your mods folder path + the mod in it.
However, the Mode2 (Combi-Mode) is WIP. See #3311 and #4286 for it.
Hope we can give some updates in the near future...
