### ISSUE TITLE
CP + Graincart "Kreuzen der Schwerter"

### ISSUE THREAD

**Issue by sdl112** [Courseplay/courseplay#5067]
Seit der letzten oder vorletzten Version fährt der Abfahrer in M2 auch von vorne an den Drescher heran. Soweit so gut, jedoch wenn es sich bei dem Abfahrer um einen Überladewagen (Graincart) handelt, welcher auch ein abladerohr hat, kollidieren das Rohr des Dreschers und des Überladewagens. Könnte man diese Option als wählbar unter den advanced settings machen?

**Comment by Tensuko** [comment]
#3311 #4286 
Closed.
