### ISSUE TITLE
Realistic use or deactivation of support wheels (e.g. TVT 585 aditional Wheels)

### ISSUE THREAD

**Issue by Merrlin** [Courseplay/courseplay#5070]
Hi Guys,
I've found a misbehave, or better an unwanted behavior with the Holmer Terra Variant TVT585 (this one where you can change the Cargobays). It has 2 different modes, Working or Transport Mode. If you are in transport Mode, it lowers 3 additional Mini Wheels.
So and there is the problem. If you hire a worker for Fieldwork, it lowers automaticaly the miniwheels.

So my suggestion is to let the workmode untouched or bett switch between the two positions via the Modes. Mode 1& 8 -> Transport, Mode 4 & 6 Work

**Comment by SteelRodent** [comment]
FWIW: According to Holmer's video of the machine (IRL)  the support wheels should be down when driving on the road and up when on the field. The support wheels are there to support the suspension when it's heavy (full) to make it more stable and keep it from bottoming out. 

In game the wheels are only there for looks and realism, but they don't actually make a difference.

**Comment by Tensuko** [comment]
Is there any sirious Issue behind it or just visual stuff ?

As @SteelRodent said, lower on transport Mode is alright but on Field IRL they don't lower.
So is there any Problem on use it on the Field like can't turn or reverse or anything ?

**Comment by Merrlin** [comment]
yes and no... IRL they're there for regulatory reasons, iirc.  In Germany (and I think most other Countrys) the wight is limited to 18 Tons with 2 Axles. So if your vehicle is heavier you need more axles.

In the vanilla game the wheels are just for deco, but affect the physics system. And if you use Mods like REA, the wheels affect even the traction.

**Comment by Merrlin** [comment]
@Tensuko As said, if you use REA at least it feels like it's affecting the traction. But that's not a big deal, it's more like a suggestion.

**Comment by Tensuko** [comment]
I changed the title, does it fit the request ?

**Comment by Merrlin** [comment]
I've clarified a bit... but sounds good

**Comment by Tensuko** [comment]
Well... the use includes deactivate or activate in the right place but ok at least we know whats the point of the Issue.

**Comment by Merrlin** [comment]
Yeah of course... the deactivation means just CP doesn't control the wheels and leve them untouched as the player has setted up.

**Comment by KCHARRO** [comment]
I suggest staying up always, in the field with REA they are a headache, especially if you are going to work in a plowed field, the support wheels are settled and the others are without traction ...

**Comment by Tensuko** [comment]
Won't happen.
