### ISSUE TITLE
(some) helpers collect wages - others don't / while wages deactivated

### ISSUE THREAD

**Issue by viperchannel** [Courseplay/courseplay#5071]
Hi there!
running on v6.01 .00395.dev

I have a contract running with rented harvester and rented truck. 
CP wages in advanced settings are deactivated. 
Harvester and truck do not collect wages while working. (truck in combined mode).

If I set one of my own tractor + trailer as an additional driver in combine mode, this one will collect wages. The numbers kind of flicker but it collects about 1credit per second just for standing there waiting. 

I tried activating wages and deactivating again. It works properly for the other 2 vehicles when activated and deactivated.

I tried different values for the CP worker wages.

Am I missing something here?

**Comment by Tensuko** [comment]
So for every new CP worker you have to activate and deactivate the wages one time to not consume money ?
Does this only happen in Mode2 (Combi Mode) or also in other Modes, lets say one Seeding some Fields.

**Comment by viperchannel** [comment]
No, I don't have to activate/ deactivate for each worker, it seems to adjust for all workers, once I change it, exept for the worker using my own tractor+trailer. What seems very confusing is the insane ammount of Money it charges. 

Currently for testing, I have stopped all workers. Wages are off and set to 50%. As soon as I start my helper in my own tractor it charges appox 1€/s (just driving/waiting with a trailer, no seeding, fertilizing etc going on).

This does not happen in Mode1 and Mode 5 (same waypoints used)

**Comment by Tensuko** [comment]
I am very sure this is due to our old Mode2 (Combi Mode), wich is #3311 and #4286 
Currently working on it and we hope to have update on that one in the near future.
