### ISSUE TITLE
Adding code to a mod to get it to play nice with CP

### ISSUE THREAD

**Issue by MtBakerScum** [Courseplay/courseplay#5072]
Sorry for creating an issue, I wanted to message @ExocetC3i directly but didn't see a way how.  I'm trying to get modify the modDesc.xml of the John Deere STS 50 & 60 series mod by SiidModding.  Exocet touched on it briefly but didn't expand.

I tried adding a new line parent="combineDrivable" under each type header under vehicle types, but this breaks the mod so that FS19 can't even see it.  Is there another solution? 

<vehicleTypes>
        <type name="jdsts50" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
			<specialization name="baseMaterial" />
			<specialization name="tipOccluder" />
			<specialization name="foliageBending" />
			<specialization name="washable" />
			<specialization name="wearable" />
			<specialization name="dynamicallyLoadedParts" />
			<specialization name="animatedVehicle" />
			<specialization name="dashboard" />
			<specialization name="cylindered" />
			<specialization name="mountable" />
			<specialization name="ikChains" />
			<specialization name="wheels" />
			<specialization name="crawlers" />
			<specialization name="slopeCompensation" />
			<specialization name="speedRotatingParts" />
			<specialization name="enterable" />
			<specialization name="fillUnit" />
			<specialization name="motorized" />
			<specialization name="drivable" />
			<specialization name="aiVehicle" />
			<specialization name="aiImplement" />
			<specialization name="articulatedAxis" />
			<specialization name="lights" />
			<specialization name="attacherJoints" />
			<specialization name="powerTakeOffs" />
			<specialization name="suspensions" />
			<specialization name="connectionHoses" />
			<specialization name="honk" />
			<specialization name="wipers" />
			<specialization name="frontloaderAttacher" />
			<specialization name="bunkerSiloCompacter" />
			<specialization name="fillVolume" />
			<specialization name="dischargeable" />
			<specialization name="turnOnVehicle" />
			<specialization name="powerConsumer" />
			<specialization name="groundReference" />
			<specialization name="workArea" />
			<specialization name="workParticles" />
			<specialization name="foldable" />
			<specialization name="cylinderedFoldable" />
			<specialization name="combine" />
			<specialization name="pipe" />
			<specialization name="crabSteering" />
			<specialization name="tensionBelts" />
			<specialization name="trailer" />
        </type>
        <type name="jdsts60old" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
			<specialization name="baseMaterial" />
			<specialization name="tipOccluder" />
			<specialization name="foliageBending" />
			<specialization name="washable" />
			<specialization name="wearable" />
			<specialization name="dynamicallyLoadedParts" />
			<specialization name="animatedVehicle" />
			<specialization name="dashboard" />
			<specialization name="cylindered" />
			<specialization name="mountable" />
			<specialization name="ikChains" />
			<specialization name="wheels" />
			<specialization name="crawlers" />
			<specialization name="slopeCompensation" />
			<specialization name="speedRotatingParts" />
			<specialization name="enterable" />
			<specialization name="fillUnit" />
			<specialization name="motorized" />
			<specialization name="drivable" />
			<specialization name="aiVehicle" />
			<specialization name="aiImplement" />
			<specialization name="articulatedAxis" />
			<specialization name="lights" />
			<specialization name="attacherJoints" />
			<specialization name="powerTakeOffs" />
			<specialization name="suspensions" />
			<specialization name="connectionHoses" />
			<specialization name="honk" />
			<specialization name="wipers" />
			<specialization name="frontloaderAttacher" />
			<specialization name="bunkerSiloCompacter" />
			<specialization name="fillVolume" />
			<specialization name="dischargeable" />
			<specialization name="turnOnVehicle" />
			<specialization name="powerConsumer" />
			<specialization name="groundReference" />
			<specialization name="workArea" />
			<specialization name="workParticles" />
			<specialization name="foldable" />
			<specialization name="cylinderedFoldable" />
			<specialization name="combine" />
			<specialization name="pipe" />
			<specialization name="crabSteering" />
			<specialization name="tensionBelts" />
			<specialization name="trailer" />
        </type>
		        <type name="jdsts60old_kon" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
			<specialization name="baseMaterial" />
			<specialization name="tipOccluder" />
			<specialization name="foliageBending" />
			<specialization name="washable" />
			<specialization name="wearable" />
			<specialization name="dynamicallyLoadedParts" />
			<specialization name="animatedVehicle" />
			<specialization name="dashboard" />
			<specialization name="cylindered" />
			<specialization name="mountable" />
			<specialization name="ikChains" />
			<specialization name="wheels" />
			<specialization name="crawlers" />
			<specialization name="slopeCompensation" />
			<specialization name="speedRotatingParts" />
			<specialization name="enterable" />
			<specialization name="fillUnit" />
			<specialization name="motorized" />
			<specialization name="drivable" />
			<specialization name="aiVehicle" />
			<specialization name="aiImplement" />
			<specialization name="articulatedAxis" />
			<specialization name="lights" />
			<specialization name="attacherJoints" />
			<specialization name="powerTakeOffs" />
			<specialization name="suspensions" />
			<specialization name="connectionHoses" />
			<specialization name="honk" />
			<specialization name="wipers" />
			<specialization name="frontloaderAttacher" />
			<specialization name="bunkerSiloCompacter" />
			<specialization name="fillVolume" />
			<specialization name="dischargeable" />
			<specialization name="turnOnVehicle" />
			<specialization name="powerConsumer" />
			<specialization name="groundReference" />
			<specialization name="workArea" />
			<specialization name="workParticles" />
			<specialization name="foldable" />
			<specialization name="cylinderedFoldable" />
			<specialization name="combine" />
			<specialization name="pipe" />
			<specialization name="crabSteering" />
			<specialization name="tensionBelts" />
			<specialization name="trailer" />
        </type>
    </vehicleTypes>

> 
> 
> At least for me, this happens with the John Deere STS Combines from this mod - https://www.yesmods.com/fs19-mods/harvesters/combine-harvesters/john-deere-50-60-sts-siid/

The issue with the 50-60 series STS mod may be due to the mod maker not specifying a parent in the `vehicleTypes` part of modDesc.xml.

Try adding `parent="combineDrivable"` to the type header in modDesc.xml to see if it resolves. I believe that without the correct parent type, CP won't recognize the vehicle (e.g. the CP window won't even open if you're in one of those combines).

_Originally posted by @ExocetC3i in https://github.com/Courseplay/courseplay/issues/4186#issuecomment-528458020_

**Comment by MtBakerScum** [comment]
`<vehicleTypes>
        <type name="jdsts50" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
			<specialization name="baseMaterial" />
			<specialization name="tipOccluder" />
			<specialization name="foliageBending" />
			<specialization name="washable" />
			<specialization name="wearable" />
			<specialization name="dynamicallyLoadedParts" />
			<specialization name="animatedVehicle" />
			<specialization name="dashboard" />
			<specialization name="cylindered" />
			<specialization name="mountable" />
			<specialization name="ikChains" />
			<specialization name="wheels" />
			<specialization name="crawlers" />
			<specialization name="slopeCompensation" />
			<specialization name="speedRotatingParts" />
			<specialization name="enterable" />
			<specialization name="fillUnit" />
			<specialization name="motorized" />
			<specialization name="drivable" />
			<specialization name="aiVehicle" />
			<specialization name="aiImplement" />
			<specialization name="articulatedAxis" />
			<specialization name="lights" />
			<specialization name="attacherJoints" />
			<specialization name="powerTakeOffs" />
			<specialization name="suspensions" />
			<specialization name="connectionHoses" />
			<specialization name="honk" />
			<specialization name="wipers" />
			<specialization name="frontloaderAttacher" />
			<specialization name="bunkerSiloCompacter" />
			<specialization name="fillVolume" />
			<specialization name="dischargeable" />
			<specialization name="turnOnVehicle" />
			<specialization name="powerConsumer" />
			<specialization name="groundReference" />
			<specialization name="workArea" />
			<specialization name="workParticles" />
			<specialization name="foldable" />
			<specialization name="cylinderedFoldable" />
			<specialization name="combine" />
			<specialization name="pipe" />
			<specialization name="crabSteering" />
			<specialization name="tensionBelts" />
			<specialization name="trailer" />
        </type>
        <type name="jdsts60old" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
			<specialization name="baseMaterial" />
			<specialization name="tipOccluder" />
			<specialization name="foliageBending" />
			<specialization name="washable" />
			<specialization name="wearable" />
			<specialization name="dynamicallyLoadedParts" />
			<specialization name="animatedVehicle" />
			<specialization name="dashboard" />
			<specialization name="cylindered" />
			<specialization name="mountable" />
			<specialization name="ikChains" />
			<specialization name="wheels" />
			<specialization name="crawlers" />
			<specialization name="slopeCompensation" />
			<specialization name="speedRotatingParts" />
			<specialization name="enterable" />
			<specialization name="fillUnit" />
			<specialization name="motorized" />
			<specialization name="drivable" />
			<specialization name="aiVehicle" />
			<specialization name="aiImplement" />
			<specialization name="articulatedAxis" />
			<specialization name="lights" />
			<specialization name="attacherJoints" />
			<specialization name="powerTakeOffs" />
			<specialization name="suspensions" />
			<specialization name="connectionHoses" />
			<specialization name="honk" />
			<specialization name="wipers" />
			<specialization name="frontloaderAttacher" />
			<specialization name="bunkerSiloCompacter" />
			<specialization name="fillVolume" />
			<specialization name="dischargeable" />
			<specialization name="turnOnVehicle" />
			<specialization name="powerConsumer" />
			<specialization name="groundReference" />
			<specialization name="workArea" />
			<specialization name="workParticles" />
			<specialization name="foldable" />
			<specialization name="cylinderedFoldable" />
			<specialization name="combine" />
			<specialization name="pipe" />
			<specialization name="crabSteering" />
			<specialization name="tensionBelts" />
			<specialization name="trailer" />
        </type>
		        <type name="jdsts60old_kon" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
			<specialization name="baseMaterial" />
			<specialization name="tipOccluder" />
			<specialization name="foliageBending" />
			<specialization name="washable" />
			<specialization name="wearable" />
			<specialization name="dynamicallyLoadedParts" />
			<specialization name="animatedVehicle" />
			<specialization name="dashboard" />
			<specialization name="cylindered" />
			<specialization name="mountable" />
			<specialization name="ikChains" />
			<specialization name="wheels" />
			<specialization name="crawlers" />
			<specialization name="slopeCompensation" />
			<specialization name="speedRotatingParts" />
			<specialization name="enterable" />
			<specialization name="fillUnit" />
			<specialization name="motorized" />
			<specialization name="drivable" />
			<specialization name="aiVehicle" />
			<specialization name="aiImplement" />
			<specialization name="articulatedAxis" />
			<specialization name="lights" />
			<specialization name="attacherJoints" />
			<specialization name="powerTakeOffs" />
			<specialization name="suspensions" />
			<specialization name="connectionHoses" />
			<specialization name="honk" />
			<specialization name="wipers" />
			<specialization name="frontloaderAttacher" />
			<specialization name="bunkerSiloCompacter" />
			<specialization name="fillVolume" />
			<specialization name="dischargeable" />
			<specialization name="turnOnVehicle" />
			<specialization name="powerConsumer" />
			<specialization name="groundReference" />
			<specialization name="workArea" />
			<specialization name="workParticles" />
			<specialization name="foldable" />
			<specialization name="cylinderedFoldable" />
			<specialization name="combine" />
			<specialization name="pipe" />
			<specialization name="crabSteering" />
			<specialization name="tensionBelts" />
			<specialization name="trailer" />
        </type>
    </vehicleTypes>`

**Comment by MtBakerScum** [comment]
```
<vehicleTypes>
        <type name="jdsts50" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
			<specialization name="baseMaterial" />
			<specialization name="tipOccluder" />
			<specialization name="foliageBending" />
			<specialization name="washable" />
			<specialization name="wearable" />
			<specialization name="dynamicallyLoadedParts" />
			<specialization name="animatedVehicle" />
			<specialization name="dashboard" />
			<specialization name="cylindered" />
			<specialization name="mountable" />
			<specialization name="ikChains" />
			<specialization name="wheels" />
			<specialization name="crawlers" />
			<specialization name="slopeCompensation" />
			<specialization name="speedRotatingParts" />
			<specialization name="enterable" />
			<specialization name="fillUnit" />
			<specialization name="motorized" />
			<specialization name="drivable" />
			<specialization name="aiVehicle" />
			<specialization name="aiImplement" />
			<specialization name="articulatedAxis" />
			<specialization name="lights" />
			<specialization name="attacherJoints" />
			<specialization name="powerTakeOffs" />
			<specialization name="suspensions" />
			<specialization name="connectionHoses" />
			<specialization name="honk" />
			<specialization name="wipers" />
			<specialization name="frontloaderAttacher" />
			<specialization name="bunkerSiloCompacter" />
			<specialization name="fillVolume" />
			<specialization name="dischargeable" />
			<specialization name="turnOnVehicle" />
			<specialization name="powerConsumer" />
			<specialization name="groundReference" />
			<specialization name="workArea" />
			<specialization name="workParticles" />
			<specialization name="foldable" />
			<specialization name="cylinderedFoldable" />
			<specialization name="combine" />
			<specialization name="pipe" />
			<specialization name="crabSteering" />
			<specialization name="tensionBelts" />
			<specialization name="trailer" />
        </type>
        <type name="jdsts60old" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
			<specialization name="baseMaterial" />
			<specialization name="tipOccluder" />
			<specialization name="foliageBending" />
			<specialization name="washable" />
			<specialization name="wearable" />
			<specialization name="dynamicallyLoadedParts" />
			<specialization name="animatedVehicle" />
			<specialization name="dashboard" />
			<specialization name="cylindered" />
			<specialization name="mountable" />
			<specialization name="ikChains" />
			<specialization name="wheels" />
			<specialization name="crawlers" />
			<specialization name="slopeCompensation" />
			<specialization name="speedRotatingParts" />
			<specialization name="enterable" />
			<specialization name="fillUnit" />
			<specialization name="motorized" />
			<specialization name="drivable" />
			<specialization name="aiVehicle" />
			<specialization name="aiImplement" />
			<specialization name="articulatedAxis" />
			<specialization name="lights" />
			<specialization name="attacherJoints" />
			<specialization name="powerTakeOffs" />
			<specialization name="suspensions" />
			<specialization name="connectionHoses" />
			<specialization name="honk" />
			<specialization name="wipers" />
			<specialization name="frontloaderAttacher" />
			<specialization name="bunkerSiloCompacter" />
			<specialization name="fillVolume" />
			<specialization name="dischargeable" />
			<specialization name="turnOnVehicle" />
			<specialization name="powerConsumer" />
			<specialization name="groundReference" />
			<specialization name="workArea" />
			<specialization name="workParticles" />
			<specialization name="foldable" />
			<specialization name="cylinderedFoldable" />
			<specialization name="combine" />
			<specialization name="pipe" />
			<specialization name="crabSteering" />
			<specialization name="tensionBelts" />
			<specialization name="trailer" />
        </type>
		        <type name="jdsts60old_kon" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
			<specialization name="baseMaterial" />
			<specialization name="tipOccluder" />
			<specialization name="foliageBending" />
			<specialization name="washable" />
			<specialization name="wearable" />
			<specialization name="dynamicallyLoadedParts" />
			<specialization name="animatedVehicle" />
			<specialization name="dashboard" />
			<specialization name="cylindered" />
			<specialization name="mountable" />
			<specialization name="ikChains" />
			<specialization name="wheels" />
			<specialization name="crawlers" />
			<specialization name="slopeCompensation" />
			<specialization name="speedRotatingParts" />
			<specialization name="enterable" />
			<specialization name="fillUnit" />
			<specialization name="motorized" />
			<specialization name="drivable" />
			<specialization name="aiVehicle" />
			<specialization name="aiImplement" />
			<specialization name="articulatedAxis" />
			<specialization name="lights" />
			<specialization name="attacherJoints" />
			<specialization name="powerTakeOffs" />
			<specialization name="suspensions" />
			<specialization name="connectionHoses" />
			<specialization name="honk" />
			<specialization name="wipers" />
			<specialization name="frontloaderAttacher" />
			<specialization name="bunkerSiloCompacter" />
			<specialization name="fillVolume" />
			<specialization name="dischargeable" />
			<specialization name="turnOnVehicle" />
			<specialization name="powerConsumer" />
			<specialization name="groundReference" />
			<specialization name="workArea" />
			<specialization name="workParticles" />
			<specialization name="foldable" />
			<specialization name="cylinderedFoldable" />
			<specialization name="combine" />
			<specialization name="pipe" />
			<specialization name="crabSteering" />
			<specialization name="tensionBelts" />
			<specialization name="trailer" />
        </type>
    </vehicleTypes>
```

**Comment by Tensuko** [comment]
Is the Mod usable by the GIANTS Ingame Helper ?

**Comment by MtBakerScum** [comment]
You know, I haven't run an in-game helper since I installed course play haha. I'll test tonight when I get home from work around 0200 gmt

**Comment by MtBakerScum** [comment]
@Tensuko yes it works with an ingame helper.  

Actually you can close this.  I added `parent="combineDrivable"` to here: `<type name="jdsts50" className="Vehicle" parent="combineDrivable" filename="$dataS/scripts/vehicles/Vehicle.lua">`

**Comment by Tensuko** [comment]
Ok alrigt.
Closed.
