### ISSUE TITLE
Change file storage (enhancement)

### ISSUE THREAD

**Issue by Williwillswisse** [Courseplay/courseplay#5073]
Hi team, when I play on a dedicated server I cannot access the folder 
"C:\Users\"USERNAME"\Documents\My Games\FarmingSimulator2019\CoursePlay_Courses\"MAPNAME"" to backup my courses and/or restore them on another server or in a single player game.
I think it would be helpful to store the courses in the savegame folder so I can down- and upload the complete courseplay data within the savegame.zip

**Comment by PromGames** [comment]
I remember this discussion with the cp devs long time ago and why they took out the stored courses from save games. 

The main reason was to not being dependant on the giants save. Sometimes, some mods made save game corrupt disappearing many files, including cp files. 

Other reason is the capability of modify and display the courses (courseplay editor) files in game running without disturbing vanilla game.

The last reason was to be able to use your customised cp courses set stored when you activate an old map and the cp collection is there.

Prom

**Comment by Williwillswisse** [comment]
I think both is possible. Take a look at the latest AutoDrive versions. The file containing the waypoints is stored in the savegame folder. The developers have implemented an im/export function to store the files in the ....MyGames\... folder. This files in the MyGames folder can be edited via Editor etc. and copied back to savegame folder via import button.
The main problem to store the files only in the MyGames folder ist the following scenario:
If you are playing on a server an create a lot of courses there is no way to download this courses and use them in a single player or on another server.

**Comment by PromGames** [comment]
Ah, I see now the problem, and yes, you are right, now courseplay server multiplayer capabilities is really important and be able to extract all courses created by users is really important.

 it can be solved adding a function to export the courses folder to where? 
I do not think the system will allow you save folders in save game, I do not know.

we also have ftp access to the mod folder and there could be created folder, I think, CP devs maybe see a solution.

Prom

**Comment by MicaelJarniac** [comment]
I was going to suggest this as well.

I like the way AutoDrive handles it: everything is tied to the save game by default, but you can export it on demand, so you can import it on another save or server.

So if you're on a server and created a fancy road network, you just export it and that's it, load up your singleplayer game and it's there to be imported. Same goes for the other way around.

And one of the main reasons I like this approach is that, on a new save game everything will be fresh unless you actually want to import something you've already done.

The way Courseplay is right now, every time I load up a new save game, all of the courses I generated for my huge modified fields are there, on the new game with unmodified fields, and that gets pretty confusing. I'd like to be able to import just the courses that actually make sense on said save game. Yes, it might be the same map, but that doesn't mean the fields are shaped the same, or the silos are positioned on the same spot, etc etc.

So ideally, for me, it would work something like this:
* Courseplay saves all courses to the save game.
* If the user wants to work on a course with the external editor, or want to transfer it to another save game, or server, they export the course, and it gets copied to somewhere outside the save game.
* The user can then work on it with external tools, copy it around, send it to other users, etc.
* Then, after the user finished working on the course with the external editor, or has created a new save game or joined a new server, they can import it to the current save game.
* This process can be done for individual courses, for whole folders, or for absolutely all courses and folders in the save game, so the user has full control of what gets exported.
* Optionally, the user can activate an auto-export feature, that exports all courses on a set interval, as a backup option, so they don't have to worry too much for other mods corrupting the courses stored inside of the save game.

I think this would check all of the boxes:
- [x] Keep courses safe from misbehaving mods
- [x] Allow working on courses with external tool while the save is loaded
- [x] Allow transferring to/from server on demand
- [x] Allow backing up saves
- [x] Allow transferring between save games
- [x] Allow different save games on the same map to have different courses
- [x] Courses get transferred with the save game, so it's easier to share saves with others

**Comment by Tensuko** [comment]
Collecting all in #5484
