### ISSUE TITLE
Incorrect Working Width Detected 

### ISSUE THREAD

**Issue by aletheist** [Courseplay/courseplay#5074]
I'm using the [Cressoni CRX mod](https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=146008&title=fs2019) with the Cressoni CRX 7.20, which has a 7.2m working width. However, Coursplay detects its working width as 6.6m.

Are there any hints I can give Courseplay to help it get the right working width so I don't have to set it manually every time I use the implement? 

Here are snippets from the mod's XML file, which all seem to point towards 7.2m.

```
<vehicle type="cutter">


<storeData>

<name>Cressoni CRX 7.20</name>


<specs>

<workingWidth>7.2</workingWidth>

</specs>
```
```
<base>

<typeDesc>$l10n_typeDesc_cutter</typeDesc>

<filename>720.i3d</filename>

<size length="3" width="7.2"/>

<speedLimit value="10"/>
```
```

**Comment by Tensuko** [comment]
Does it detect correctly when unfolded ?
Also how does the screen of the coursgenerator look like, when you want to create a course, it can happen that the correct width is detected, but not automatically set in the width for the course.
The CP Work Width should come from left and right node of the tool.
Not 100% sure but I think debugchannel 12 shows the 2 nodes.

**Comment by aletheist** [comment]
It does not detect correctly when unfolded, in the Courseplay settings HUD, or in the course generator dialog.

I do not know how to show debug info in the game. Screenshot of autodetection attached.

![fsScreen_2020_03_18_08_10_42](https://user-images.githubusercontent.com/5422799/76959457-01ceef00-68f0-11ea-92b3-7cc18c515949.png)

![fsScreen_2020_03_18_08_09_23](https://user-images.githubusercontent.com/5422799/76959463-0398b280-68f0-11ea-96c3-e6a192648495.png)

![fsScreen_2020_03_18_08_11_27](https://user-images.githubusercontent.com/5422799/76959500-14492880-68f0-11ea-9dca-347b35e01103.png)

**Comment by aletheist** [comment]
What nodes are you calling left and right? There's a lot of nodes specified with lefts and rights or starts and widths.

**Comment by aletheist** [comment]
Found the issue. The mod's `*.i3d` files have a big. All three models (6m, 6.6m, and 7.2m) are set with the same AI lefts and rights (6.6m). 

I have adjusted the i3d files and re-zipped the mod and get correct detection now. I will see if I can find a way to report to the mod developer.

**Comment by Tensuko** [comment]
CP HUD Settings, click on the 12 (and the 6) and it should display the nodes.
![fsScreen_2020_03_18_16_27_20](https://user-images.githubusercontent.com/27344744/76977392-8b54e000-6935-11ea-8046-500875e6de05.png)

**Comment by aletheist** [comment]
Thanks for the info! I have managed to get this reported upstream to the mod creator and will close this issue since it's not a CP issue.
