### ISSUE TITLE
FS19 wont start with courseplay mod enabled

### ISSUE THREAD

**Issue by vflorian** [Courseplay/courseplay#5076]
Hi, 

For some reason FS19 is not starting with the courseplay mod enabled. It stops at the loading stage. 
I am attaching a log file. 
Thanks for taking a look. 
[FS19_log.txt](https://github.com/Courseplay/courseplay/files/4351034/FS19_log.txt)

**Comment by Flashmaster23** [comment]
Maybe the same error as #4322 ?
AutoDrive outdated, get the newest here: https://github.com/Stephan-S/FS19_AutoDrive/releases

**Comment by Tensuko** [comment]
Throw this one out: Error: Invalid mod name 'FS19PlaceAnywhere-master'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
You got GC there is place anywhere included.

Old AD Version get newest at the Link from Flashmaster.

Closed.
