### ISSUE TITLE
Manure/Mist

### ISSUE THREAD

**Issue by franky135** [Courseplay/courseplay#5077]
Die Düngung mit Mist funktioniert nicht. Wenn ich selbst fahre wird gedüngt. Beim originalen Helfer geht es auch. Dünger, Gärrest oder Gülle funktioniert. Das Problem trat schon in älteren Versionen auf, jetzt allerdings dauerhaft.
[log.txt](https://github.com/Courseplay/courseplay/files/4354245/log.txt)

**Comment by Tensuko** [comment]
Mehr Details bitte, was heist geht nicht.
Traktor, Tool, gewählter Modus, Kurs, etc etc Bilder wären auch gut.

**Comment by Tensuko** [comment]
Und von einem Logfile her zu lesen: Aktuelle Version laden und bitte FS19_Courseplay oder FS19_Courseplay6 benennen, das mit dem zzz ist uralt und totaler quatsch.

**Comment by Tensuko** [comment]
Ach und es könnte auch an deinem Callstack liegen, der nichts mit CP zu tun hat:
2020-03-18 20:00 Validity check failed in TransformGroup_setRotation:  
2020-03-18 20:00   ..\..\..\src\engine\app\ReflectionAndScriptBinding.cpp (6382): !MathUtil::isNaN(pArgs->arg[0].f)
2020-03-18 20:00 LUA call stack:
2020-03-18 20:00   dataS/scripts/vehicles/specializations/FillVolume.lua (305) : printCallstack
2020-03-18 20:00   dataS/scripts/vehicles/SpecializationUtil.lua (30)
2020-03-18 20:00   dataS/scripts/vehicles/Vehicle.lua (1306) : raiseEvent
2020-03-18 20:00   dataS/scripts/network/NetworkNode.lua (98) : update
2020-03-18 20:00   dataS/scripts/network/Server.lua (58) : updateActiveObjects
2020-03-18 20:00   dataS/scripts/BaseMission.lua (1500) : update
2020-03-18 20:00   dataS/scripts/FSBaseMission.lua (1977) : update
2020-03-18 20:00   dataS/scripts/missions/mission00.lua (469) : update
2020-03-18 20:00   dataS/scripts/main.lua (1896) : update
2020-03-18 20:00 Validity check failed in TransformGroup_setRotation:  
2020-03-18 20:00   ..\..\..\src\engine\app\ReflectionAndScriptBinding.cpp (6382): MathUtil::isFinite(pArgs->arg[0].f)

**Comment by franky135** [comment]
neue Version hab ich gerade geladen...ich habe mit verschiedenen mods aber auch mit standardfahrzeugen das gleiche problem...ich nutze den dünge-/sämodus....funktioniert nicht, bedeutet, dass der streuer mit cp keinen mist verbraucht und somit auch nicht düngt...
den callstack hab ich gestern nacht wohl übersehen- mal schauen was ich da rausschmeissen muss.

**Comment by franky135** [comment]
neue version ist drin, mods sortiert und die meisten call stacks sind weg, aber das problem ist geblieben.
[log.txt](https://github.com/Courseplay/courseplay/files/4354603/log.txt)
![fsScreen_2020_03_19_13_38_00](https://user-images.githubusercontent.com/48451440/77069226-4fc71e00-69e8-11ea-958f-a3845f60c767.png)
![fsScreen_2020_03_19_13_38_18](https://user-images.githubusercontent.com/48451440/77069237-548bd200-69e8-11ea-96b5-08147349aafd.png)
![fsScreen_2020_03_19_13_38_30](https://user-images.githubusercontent.com/48451440/77069246-581f5900-69e8-11ea-88b6-9b8c591469d6.png)

Bild 1 : blau= mit Helfer gedüngt, Flecken= mit CP (zb Feld14)
Bild 2: Kurs für Feld 1
Bild 3: ausgewählter Modus

**Comment by Tensuko** [comment]
ok ich schaue mir das ganze mal an das ist schon merkwürdig.
Mit einer Feldspritze oder normalem Dünger geht es denn ?

**Comment by franky135** [comment]
Düngerstreuer, Gülle und Kalk sowie Pflanzenschutz funktioniert. Flüssigdünger hab ich noch nie getestet.
auf 14,15,16,17 und 18 kann man die Flecken vom Miststreuen sehen. Der Rahmen um 15(danach Gülle alle) oder zb Feld 2 ist vom Gülle fahren. Feld 17 hat der Standardhelfer dann nochmal gedüngt bis der Mist alle war. 3 und 4 wurden beim säen gedüngt, Feld 1 war jetzt der Versuch- blau war der Helfer, ungedüngt war cp

**Comment by Tensuko** [comment]
Keinerlei Probleme fest zu stellen:

![fsScreen_2020_03_20_16_00_30](https://user-images.githubusercontent.com/27344744/77176230-119f2c80-6ac4-11ea-828a-56301a0a9c60.png)
![fsScreen_2020_03_20_16_01_11](https://user-images.githubusercontent.com/27344744/77176238-1368f000-6ac4-11ea-829a-6f243e92388b.png)

Ich fürchte du wirst da selber erstmal auf die Suche gehen müssen.

Aber du spielst im SP ?

**Comment by franky135** [comment]
ja nur sp.
in älteren cp-Versionen ging es ja noch- also vor ca 6 Wochen....
aber dann teste ich mal, ob sich was finden lässt.

Danke für die Mühe! Ihr macht einen tollen Job!

**Comment by Tensuko** [comment]
Closed due to inactivity
