### ISSUE TITLE
Leveling and Compacting: tractor doesn't go through all the silo 

### ISSUE THREAD

**Issue by alepinci** [Courseplay/courseplay#5078]
Hi, I tried the leveling and compacting mode but as I said in the title the tractor goes a few meters in reverse then stops and change position.
Moreover I can't change values on "max speed while pushing" and "blade height" 
Tried the filling up option but it's the same.

A few month ago it was working well but now it does this.. I've tried on different maps and without other mods but it's the same. 

Log File https://pastebin.com/jAyq7HxG
Video https://drive.google.com/file/d/1PkKHEisHJlbaHrWos5lyU2AwSnad749f/view?usp=sharing

**Comment by alepinci** [comment]
Just figured out that the tractor stops after a few meter because the blade is raised a bit and cannot catch the chaff. So the problem is the height of the blade i think.. why can't I choose manual height?

**Comment by Tensuko** [comment]
#4130
