### ISSUE TITLE
Kartoffel legen 

### ISSUE THREAD

**Issue by Baker79** [Courseplay/courseplay#5080]
Kartoffel legen funktioniert nicht. 
Soll das so sein ?
Ich verwende Standart Maschienen. MF 7726 und Grimme GL 420
auch mit einem Class Arion 660 probiert.
Saatmaschiene soll aufgefüllt werden kommt als Meldung

MFG

**Comment by Tensuko** [comment]
Logfile ?

**Comment by Baker79** [comment]
Sorry vergessen ..Hier ist sie.

[log.txt](https://github.com/Courseplay/courseplay/files/4360220/log.txt)

**Comment by Tensuko** [comment]
Bitte beheben:
Error: Failed to open xml file 'D:/Benutzerdaten/Dokumente/My Games/FarmingSimulator2019/mods/GlobalCompanyAddOn_Icons/modDesc.xml'.
Load mod: GlobalCompanyAddOn_Icons (Hash: 97cd108fc76694c3b9b0ccee3173ddbb)
Error: Missing descVersion attribute in mod GlobalCompanyAddOn_Icons

Eben versucht, bei mir geht es.
Kannst du mal ein Bild posten mit deinem Gespannt und Kurs ?

**Comment by Baker79** [comment]
![fsScreen_2020_03_20_16_04_17](https://user-images.githubusercontent.com/59795452/77176545-8bcfb100-6ac4-11ea-9cdb-04e71cd4116c.png)
Es ist Übrigens egal ob ich Saatgut oder Kartoffeln einstelle. Bei Farmsilo Befüllen.

**Comment by Tensuko** [comment]
Äh ja moment du hast ja auch kein Saatgut/kartoffeln geladen.
Wo sollen die denn jetzt her kommen ? :)

Wenn du willst das er selber abholen fährt, muss du deinen Feldkurs speichern (z.B. F6_Kartoffeln) dann nimmst du einen Kurs auf vom Feld zum Hof (oder wo auch immer du Saatgut her holst) an der Aufladestelle vorbei (durch den Trigger) und wieder zurück zum Feld. Den Kurs nennst du dann z.B. F6_KartoffelnLaden. Jetzt wenn du keinen Kurs geladen hast, lädst du erst den Feldkurs mit dem normalen Ordner Symbol und anschließend den Nachladekurs mit dem Ordner mit dem + Symbol drin. Dann fährt dein Traktor den Auffüllkurs ab und wenn er an einer gültigen Auffüllstelle vorbei fährt kommt er voll zurück und beginnt mit der Arbeit :) Dann muss man natürlich einstellen ob man an der Stelle Saatgut oder Kartoffeln laden will. Tipp von mir: Ich würde auf jeden Fall vor dem Start der Feldarbeit den Traktor einmal selber füllen, es könnte sonst sein das er zwar das Gerät absenkt, aber nicht arbeite. Das war/ist ein Bug, den habe ich noch nicht weiter verfolgt, weil sind wir mal ehrlich, wer fährt mit leerem Gerät zum Feld ;)

**Comment by Baker79** [comment]
Ahhh hab ich mirs doch gedacht. Ich dachte nur , mit einer normalen saatmaschiene weizen gerste und so weiter geht es ja auch. wird ja da gleich vom Konto abgezogen.

Trotzdem Danke für die turbo schnelle Hilfe 
MFG

**Comment by Tensuko** [comment]
Also mit vom Konto abziehen geht es natürlich auch, musst du halt in den Einstellungen von LS Saatgut Kaufen aktivieren.

**Comment by Baker79** [comment]
Ja das funktioniert aber nur bei , Saatmaschienen für Weizen Gerste ect.
Bei Kartoffeln scheint das nicht zufunktionieren. Da ich immer von cp ansäen lasse. Und diese option Saatgut kaufen immer an ist.

**Comment by Tensuko** [comment]
Hmm das kann ich wiederum nicht bestätigen.
CP eingeschaltet, in den Einstellungen auf kaufen gewechselt und ab gings.
Kann ich dir nicht sagen warum es bei dir nicht geklappt hat.

**Comment by Baker79** [comment]
Ok. 
falls hier noch jemand mitliest und dieses problem kennt ,,,gern kommentieren,,
Danke

**Comment by Baker79** [comment]
Hab das ganze auf einer anderen Map getestet. Selbes Problem. ABER....
ich habe festgestellt mit der Grimme GL 420 (ohne dünge funktion) geht es nicht. Meldung Gerät muss beladen werden.
Mit der Grimme GL 860 diese hat Düngefunktion geht es. Wenn man Dünger kaufen beim Helfer einschaltet. wenn diese option auf ,,aus,, steht geht es auch nicht.

**Comment by Tensuko** [comment]
Da muss irgend eine Mod bei dir zwischenfunken, ich kann deine Beobachtung so nicht bestätigen.

**Comment by Baker79** [comment]
ok ich begebe mich auf die suche

**Comment by Meditos77** [comment]
Hallo. Als erstes nimmst mal alle Mods raus die Fehler ( Error ) machen. Da du schon alleine in den Standartfrüchten fehler hast. (am Rande, Die GlobalCompanyAddOn_Icons ist kein MOD den du in den Mod Ordner rein gibst. )  Wenn du das gemacht hast, Startest du ein neues Spiel und das gleich wieder. So lange keine Mods mehr da sind die einen Fehler machen. Durch die Vielen Error was du hast, kennt sich CP, und FS19 nicht mehr aus und Deaktiviert Sachen die dann aber im folge Fehler machen. Und wie gesagt, Einige Mods werfen alleine schon in der log bei den Standartfrüchten  Fehler aus. Das darf mal gar nicht sein. CP funktioniert beim Ansäen in jeder variante Tadellos.

**Comment by Baker79** [comment]
Moin. das globel addon ico war mein fehler. Hab ich behoben. nun mach ich mich mal an das aussieben der error mods. könntest du dir meine log ansehen und mir ungefähr sagen welche mods es sind ?
Danke 

In dieser Zeit # DURCHHALTEN

**Comment by Baker79** [comment]
Es scheint an den Modmaps zuliegen.Weil auf standart map geht es ohne probleme.

**Comment by Tensuko** [comment]
Naja du hast 2 Maps im Mords Ordner wenn ich das richtig sehe.
SchwarzePumpe1988 und Gemeinde Rade.
Man sollte am besten immer nur eine Modmap im Ordner haben, ich würde mal eine raus nehmen und dann schauen.

**Comment by Baker79** [comment]
Ja gerade probiert. Die Maps kollidieren bei diesem Problem. also immer mur eine drin lassen.
Danke trotzdem ....

In dieser Zeit #DURCHHALTEN
