### ISSUE TITLE
Harvesting with Mex 5 

### ISSUE THREAD

**Issue by Firefall666** [Courseplay/courseplay#5081]
Hallo, 
zuerst mal, ich liebe eure Arbeit.
Leider ist habe ich einen Bug gefunden.
Sobald ich mit dem Mex5 Mais häcksle, streiken die Abfahrer und CP steigt mit einem LUA-Fehler aus.

Log ist im Anhang.
Spezifikationen:
Map: Dreisternhof, Feld 11
Häcksler: Mex 5 an einem Fendt Favorit 515c
Abfahrer: Valtra T234 mit einem Strautman SEK 802, 120000 Liter
Alternativer Abfahrer (gleicher Fehler) Case IH 7210 mit Strautman Zelon CFS2501

Manuelles Abfahren funktionert einwandfrei.
Sobald ich versuche einen Abfahrer (Mode 2) einzustellen, steigt CP aus.
CP.Version 393
[log.txt](https://github.com/Courseplay/courseplay/files/4361074/log.txt)

GoogleTranslation:
Hi there,
first of all, i love your work.
Unfortunately I found a bug.
As soon as I chop the Mex5 maize, the downhillers strike and CP gets out with an LUA error.

Log is attached.
Specifications:
Map: Dreisternhof, field 11
Chopper: Mex 5 on a Fendt Favorit 515c
Driver: Valtra T234 with a Strautman SEK 802, 120000 liters
Alternative driver (same error) Case IH 7210 with Strautman Zelon CFS2501

Manual shutdown works perfectly.
As soon as I try to hire a driver (Mode 2), the CP gets out.
CP version 393

**Comment by Tensuko** [comment]
Die Angepinnten Issues hast du aber gesehen ?
#3311 und #4286 

Closed.
