### ISSUE TITLE
 Ist das manureSystem aktiv funktioniert das Beladen in courseplay nicht mehr.

### ISSUE THREAD

**Issue by Flashmaster23** [Courseplay/courseplay#5082]
Hi,
wenn das manureSystem aktiv ist, funktioniert das automatische Beladen eines Helfers bei courseplay nicht mehr. Das Problem betrifft alle Trigger (Dünger, Silo, Wasser etc.) sowohl auf Mod-Maps als auch bei den Default-Maps.

Wenn der Hänger am Trigger steht und man dann in das Fahrzeug einsteigt, beginnt der Ladevorgang.
Nimmt man das manureSystem raus, funktioniert das Beladen wieder voll automatisch.
Vielleicht ist es möglich sich einmal mit dem Entwickerler vom manureSystem kurz zuschießen um eine Lösung zu finden?

Danke.

Getestest mit:

Courseplay v6.01.00397
Courseplay v6.01.00396
Courseplay v6.01.00395
Courseplay v6.01.00394
Courseplay v6.01.00390

und 
ManureSystem 1.0.0.0

[log.txt](https://github.com/Courseplay/courseplay/files/4361169/log.txt)

Edit:
hier noch der Issue bei Merrlin (ManureSystem)
https://github.com/stijnwop/manureSystem/issues/37

**Comment by Tensuko** [comment]
Die Lösung ist ganz simpel:
Das manure System verbietet offenbar das laden wenn kein Schlauch angeschlossen ist, also wie soll CP das machen ? Will man denn den Auffand treiben Schläuche an zu schließen, wenn man auf der anderen Seite eh alles von CP erledigt haben will. Finde ich etwas wiedersprüchlich ehrlich gesagt.

Da müsste man dann mit dem Modder drüber sprechen.

**Comment by Flashmaster23** [comment]
Danke für die schnelle Antwort. Ich bin davon ausgegangen, das dieses nur für die Güllegrube bzw. die entsprechenden Gerätschaften gilt. Ich lasse ja nur die stupiden Arbeiten von CP erledigen.. 

Danke auch für Deine Arbeit an CP, ohne macht der LS keinen Spaß. Ich lasse dann das Gülle System erstmal raus.. CP ist ist mir wichtiger ;)

**Comment by Flashmaster23** [comment]
Wird wohl vom Modder des Gülle Systems bearbeitet. Ich schließe den dann mal..
