### ISSUE TITLE
Worklights

### ISSUE THREAD

**Issue by Friendlyx** [Courseplay/courseplay#5083]
Hi,
I have the latest dev. version of courseplay and my helper is always using full worklight when driving in Route Mode. (Überführung)

**Comment by Tensuko** [comment]
We will see if we going to change something on that, but thats very very inimportant right now...

**Comment by Friendlyx** [comment]
ok thx for reply

**Comment by Tensuko** [comment]
Should be fixed long time ago, not sure if this is working correctly now. If not, new Issue pls...
