### ISSUE TITLE
Frage zu einigen Funktion

### ISSUE THREAD

**Issue by Michael170978** [Courseplay/courseplay#5084]
Hi.

ich verrichte fast alle Tätigkeiten mit Courseplay somit bin ich mit den Funktionen betraut. Trotzdem sind da ein paar Funktionen wo ich mich ständig frage wozu die gut sind.

Auf Youtube hab ich gesucht aber leider keine Antwort gefunden.

Somit könntet ihr mir bitte folgende Funktionen erklären:

-  Allgemeine Fahreinstellungen: planen
-  Haltezeit
- Modus abhängige  Einstellungen: Entgegengesetzt wenden (letzte Bahn)

Wann sind diese Funktionen hilfreich?

Vielen Dank

**Comment by Merrlin** [comment]
Mit planen stellst du ein ob CP die Plane bei manchen Anhängern (z.B. den Agrolinern) automatisch zumacht oder ob die offen bleibt.

Die Haltezeit sagt dem Traktor wie lang er an Wartepunkten (das P bei der Kursaufzeichnung) stehenbleiben soll. Das ist zum Beispiel nützlich wenn du eine Kartoffelsämaschine am Überladewagen befüllen willst.

Was entgegengesetzt wenden tut weiß ich allerdings auch nicht.

**Comment by Tensuko** [comment]
Zu dem letzten Punkt:
Ich meine das hat damit zu tun, dass er den Bogen für ein Wendemanöver einfach spiegelt um auf dem Feld zu bleiben.
Aber ehrlich gesagt hat mich die Funktion noch nie interessiert, die ist halt an und fertig, funktioniert :)

**Comment by Michael170978** [comment]
Sprich bitte nicht über Kartoffelmaschinen. Das ist echt ein Krampf. Vor allem wenn du ernten willst. CP erkennt die Erntemaschine nicht. Ich rede jetzt nicht über den Vollernter. Ich meine jetzt die Maschine die der Schlepper zieht. CP hängt sich auf. Es sei den die Jungs haben alles überarbeitet. Hab schon lange nicht mehr versucht. Aber das ist ein anderes Problem und gehört nicht in dieses Ticket rein. Trotzdem danke für die antworten

**Comment by Tensuko** [comment]
Die Überarbeitung ist im gange, aber auch keine Garantie das dies auf anhieb läuft, allerdings wird das Arbeiten an dem Problem erheblich leichter.

**Comment by Tensuko** [comment]
Ich mache den heir zu, aber man kann hier natürlich weiter schreiben :)
