### ISSUE TITLE
Cannot Level and Compact Multiple Silos

### ISSUE THREAD

**Issue by DizzyBHigh** [Courseplay/courseplay#5085]
CoursePlay 6 v 6.01.00397

Hi I thought I'd make a quick question before I start making bug reports and videos as i need to learn how!!!
I'm having an issue unloading into multiple Bunker silos, I can set up one course fine, I try to set up another for my second silo and it always tries to dump into the first silo I set up.
Any ideas or workarounds for this?

**Comment by Tensuko** [comment]
The question is how did you set up the course ?
One Course from Field/Silo per Bunker.
When you don't want to record every course one by one, make a course from start to the entrance of the place where your Bunkers are, then from there make each one course thrue every Bunker, then build your Course together like a system and save them as e.B. Silo to Bunker1 and Silo to Bunker2 etc... I only know a good german Tutorial https://www.youtube.com/watch?v=7WjFApz8WRk&list=PLHxTNC_mnOrZSncQLJBiq-YJLsZzOXKUL&index=1

**Comment by DizzyBHigh** [comment]
The dumping of silage from field to silo works fine. (reverse unloading into a closed bunker.
I have a tractor at my biogas plant.
Successfully set up one Levelling Run.

- Start in bunker -> click record
- Drive out to parking spot -> click park
- Drive forward 1 meter -> click reverse (otherwise it seems to do some weird turn before reversing)
- Reverse to just in front of silo click Stop

Works flawlessly, tractor does route levels silage in Silo One and repeats.

I try the exact above for my second silo I moved it to a different place as it was initially just driving into the wall of the silo, (trying to turn round to my first silo) and it does the route but when it gets to the front of the 2nd silo for compacting, it turns and drives to the 1st silo I set up and tries to level it there.

I think the issue is it only recognizes one silo and tries to do all the levelling only for that silo?

I've reloaded the game and recorded the second course in my second bunker.
It looks as though it only recognizes the first bunker recording.

Not tried a using separate tractor's for different silos as that seems like a waste of tractors!!
[log.txt](https://github.com/Courseplay/courseplay/files/4362892/log.txt)

**Comment by Tensuko** [comment]
Well I have to say that this Mode is realy not working perfectly in its current state and yea the problem will be that it sees some chaff maybe even in the wall of the 1st bunker and tries to get there.

The only solution (for now) would be haveing 2 Bunker with more space inbetween I would say.

Pictures you can do by pressing printscreen on your keyboard and the game will make a screenshot in this folder: ...\My Games\FarmingSimulator2019\screenshots

**Comment by DizzyBHigh** [comment]
The first bunker i set up is empty 
lp17066] 380 CVX (#1): Bunkersilo filled with UNKNOWN(1) will be devided in 4 lines and 3 columns

The second bunker has corn silage in it (not much)
Made A Gif (better than viewing separately!!)

![Bunker Levelling Course and Two levels Bunker One Only](https://user-images.githubusercontent.com/2430074/77227703-7c16a200-6b82-11ea-9467-576a7f3e0d61.gif)

The two bunkers are quite far from each other
![fsScreen_2_First Silo Course (9)](https://user-images.githubusercontent.com/2430074/77227452-d6166800-6b80-11ea-8aef-747ab7ea99e5.png)
![fsScreen_2_First Silo Course (10)](https://user-images.githubusercontent.com/2430074/77227455-d9a9ef00-6b80-11ea-84df-1d60b9084feb.png)
![fsScreen_2_First Silo Course (11)](https://user-images.githubusercontent.com/2430074/77227456-db73b280-6b80-11ea-915a-4991421f4972.png)
![fsScreen_2_First Silo Course (12)](https://user-images.githubusercontent.com/2430074/77227457-ddd60c80-6b80-11ea-9671-e7d8df4d1eeb.png)
![fsScreen_2_First Silo Course (13)](https://user-images.githubusercontent.com/2430074/77227461-df9fd000-6b80-11ea-8c2e-2e48d424955b.png)
![fsScreen_2_First Silo Course (14)](https://user-images.githubusercontent.com/2430074/77227464-e2022a00-6b80-11ea-93b7-8842c9274f7f.png)
![fsScreen_2_First Silo Course (1)](https://user-images.githubusercontent.com/2430074/77227467-e3cbed80-6b80-11ea-8be3-1d907dbb3128.png)
![fsScreen_Second Silo Course (14)](https://user-images.githubusercontent.com/2430074/77227468-e4648400-6b80-11ea-889c-39a9436ba42c.png)
![fsScreen_2_First Silo Course (2)](https://user-images.githubusercontent.com/2430074/77227469-e62e4780-6b80-11ea-9a1e-85fae3762d74.png)
![fsScreen_Second Silo Course (2)](https://user-images.githubusercontent.com/2430074/77227471-e9293800-6b80-11ea-93f8-4bfdf696aa2c.png)
![fsScreen_2_First Silo Course (3)](https://user-images.githubusercontent.com/2430074/77227472-e9c1ce80-6b80-11ea-8c42-af20504c436d.png)
![fsScreen_2_First Silo Course (4)](https://user-images.githubusercontent.com/2430074/77227476-ecbcbf00-6b80-11ea-8d60-3e44728103d0.png)
![fsScreen_Second Silo Course (3)](https://user-images.githubusercontent.com/2430074/77227477-ecbcbf00-6b80-11ea-8da9-c435708b48d8.png)
![fsScreen_Second Silo Course (4)](https://user-images.githubusercontent.com/2430074/77227478-f0504600-6b80-11ea-81d0-493e94960816.png)
![fsScreen_2_First Silo Course (5)](https://user-images.githubusercontent.com/2430074/77227479-f0e8dc80-6b80-11ea-92fe-9b5deed13967.png)
![fsScreen_2_First Silo Course (6)](https://user-images.githubusercontent.com/2430074/77227484-f3e3cd00-6b80-11ea-9f74-f081d35facdf.png)
![fsScreen_Second Silo Course (5)](https://user-images.githubusercontent.com/2430074/77227485-f3e3cd00-6b80-11ea-830d-eca3acf86a85.png)
![fsScreen_Second Silo Course (6)](https://user-images.githubusercontent.com/2430074/77227488-f6debd80-6b80-11ea-8d82-f9d94f211501.png)
![fsScreen_2_First Silo Course (7)](https://user-images.githubusercontent.com/2430074/77227489-f7775400-6b80-11ea-8ce1-6e2de416909c.png)
![fsScreen_Second Silo Course (7)](https://user-images.githubusercontent.com/2430074/77227491-f9d9ae00-6b80-11ea-88fa-c22eb193bfef.png)
![fsScreen_2_First Silo Course (8)](https://user-images.githubusercontent.com/2430074/77227492-fb0adb00-6b80-11ea-82e8-296676b8010c.png)
![fsScreen_Second Silo Course (8)](https://user-images.githubusercontent.com/2430074/77227493-fcd49e80-6b80-11ea-875c-a40fe8cde542.png)
![fsScreen_Second Silo Course (9)](https://user-images.githubusercontent.com/2430074/77227494-ffcf8f00-6b80-11ea-9d93-7923ace8f7ee.png)
![fsScreen_Second Silo Course (10)](https://user-images.githubusercontent.com/2430074/77227495-0231e900-6b81-11ea-8b89-e34493307040.png)
![fsScreen_Second Silo Course (11)](https://user-images.githubusercontent.com/2430074/77227496-03fbac80-6b81-11ea-8f57-e6b6d2394034.png)
![fsScreen_Second Silo Course (12)](https://user-images.githubusercontent.com/2430074/77227498-05c57000-6b81-11ea-9f83-13efb34eddd6.png)
![fsScreen_Second Silo Course (13)](https://user-images.githubusercontent.com/2430074/77227500-0827ca00-6b81-11ea-8419-268577dc7eff.png)

**Comment by 1d1ot1cPotato** [comment]
Just try with another tractor I have silos are right next to eachother and it works.
when i have one tractor and the silos are on the oposite sides of the map the tractor always wants to drive to the first silo, So for now just use 2 tractors one for silo 1 and the other for silo 2.

**Comment by Tensuko** [comment]
We have to work on that Mode and investigating this one already, but not highest priority, as it is kind of working.
Closing this for now.
As suggested, try another Tractor.
Hope we can bring improovements to this mode soon or later.
