### ISSUE TITLE
mode3: Error: Running LUA method 'update' mode3.lua:24

### ISSUE THREAD

**Issue by dersiedler1** [Courseplay/courseplay#5086]
Hi,

i recently experienced an error in mode3. For further details see the attached log file.

Situtation when this appears. 
- Multimap 19,
- 2 Combines ( CR1090 and 9240) on the field harvesting corn via CP. 
- 1 Overloading with a short CP course to unload the combines

The 2 combines are ready for unloading. The overloading trailer is at the start point of his unloading course. I press 'Abfahrer einstellen' and courseplay seems to crash. The combines driving to 'nowhere' and the overloading trailer doesn't do anything.

If you need mor information let me know.

[log.txt](https://github.com/Courseplay/courseplay/files/4363142/log.txt)
![CP_Error](https://user-images.githubusercontent.com/408450/77229060-c18b9d00-6b8b-11ea-9faf-c0796421c536.png)

**Comment by Tensuko** [comment]
#3311 #4286 
Closed, Mode3 is same for Mode2 is WIP.
