### ISSUE TITLE
Stuck running engine and hired workers

### ISSUE THREAD

**Issue by KailJaxxon** [Courseplay/courseplay#5087]
Not sure if others have the same problem on their FS19 hosted server, but after I have been playing for a while the engines on equipment (especially combines) will keep running and you will still see a hired worker sitting in the drivers seat. Nothing will deactivate the worker/engine except for doing a server restart. Any ideas?

**Comment by Tensuko** [comment]
a logfile is always welcome also for our MP users.

**Comment by KailJaxxon** [comment]
Here is the log file.

________________________________

**Comment by 51stHD** [comment]
This happens to me in single player with the standard helper, with AI extended helper and with CP, but it's due to a mod conflict on a heavily modded game rather than any issue with CP or the stock helper or the AI extended helper mod.

Looking at your log file you have what I would call a heavily modded game. If I was you I would start clean with CP as the only mod and add others in one at a time, testing as you go until you find the conflict. Takes time but it's the only way I know to do it.

**Comment by KailJaxxon** [comment]
Thank you for getting back to me on this. As for the mods, 90% of the mods are required for the map to work correctly. I will remove the others and try what you suggested. It only happens when I have been playing for many hours straight. Thanks again.

________________________________

**Comment by 51stHD** [comment]
No worries, it's a frustrating problem and if I can help that all good.
It's possibly quicker if you add say 4 mods at a time when testing, just a thought.

Also next time it happens, try blocking the path of the vehicle with another vehicle. I've found that this sometimes forces the AI give up control.

**Comment by KailJaxxon** [comment]
I tried the blocking the path with another vehicle. The CP AI just ran into it like it was not even there. Also I removed all the non essential mods and it still did it. So I thought I would try it again with no mods, just the map. Same thing. It happens primarily with the harvesters all the time. With tractors pilling things like plows or seeders it rarely happens. So not really sure what is the deal. LOL

**Comment by MicaelJarniac** [comment]
This just happened to me today. Friend was hosting, and pretty much every time I stopped Courseplay, the hired helper would still be in the truck, stuck there doing nothing, and blocking me from driving it. To fix that, I just had to press <kbd>H</kbd>, so it wasn't a big deal, but it was annoying.

`v6.02.00004`
