### ISSUE TITLE
Limits in number of vehicles in courseplay Single player

### ISSUE THREAD

**Issue by PromGames** [Courseplay/courseplay#5088]
Hello,

I have noticed that the courseplay system is doing mismatch of courses and status when there are more than 12 machines running, almost all of them in mode 2. Apart of that, mode 2 seems very stable,

No errors appears in log, the problems occurs sporadically and you find attractor that is not collecting straw.

The other fine tuning needed in mode 2 is the approach to the harvester, when is coming by front, it goes to the back of the harvester and if the truck head is 4 axels then the truck start to give rounds and rounds and never reach the harvester.

Also in mode 2, after the truck has finished to collect from harvester, if is not full, it waits but too short to start to go to park till next load.

But when is full, it tries to go instantly, some times give a round and then goes well, but other time , go straight and then crash with the harvester, 

Just small comments, but I see mode very stable in general. Leaving all night in mode 2 maximum of 8 vehicles works fine. 4 million straw to kompost master and 6 million grass to fermenter.

Prom

**Comment by Tensuko** [comment]
See #3311 and #4286 
Closed.
