### ISSUE TITLE
Courseplay Fehler: Fahrzeuge werden unsteuerbar wenn CP Helfer abfährt

### ISSUE THREAD

**Issue by S1m0n001** [Courseplay/courseplay#5089]
Hallo liebes Forum!
Ich verwende seit kurzem Courseplay und bin grundsätzlich auch total begeistert davon. 
Leider tritt bei mir immer wieder ein Fehler auf. Und zwar passiert das meistens wenn der CP Helfer den Drescher abfährt. Dann werden alle meine Fahrzeuge unsteuerbar und machen sonderbare Dinge (Fahren gerade aus, lenken, etc) ohne mein Zutun.Zeitgleich erscheint auch ein Error in der Log. Erst sobald ich den Abfahrer entlasse funktioniert wieder alles normal. Der Fehler tritt auf im Singleplayer, ich habe auch schon versucht alle Mods zu entfernen aber das hat leider auch nichts gebracht. Im Anhang findet ihr die Log.
Ich freue mich auch baldige Antworten!
[log.txt](https://github.com/Courseplay/courseplay/files/4364503/log.txt)

**Comment by Tensuko** [comment]
Mode2 ist WIP.
Siehe #3311 und #4286 
Closed.
