### ISSUE TITLE
Harvesting issue

### ISSUE THREAD

**Issue by RedMonster-HUN** [Courseplay/courseplay#5090]
Sometimes, when the combine stops because the grain tank is almost full, the worker doesn't open the combines pipe. This way the truck or tractor (operated by Autodrive) doesn't drive to the combine and the whole process gets stuck. The issue occured with base game combine (Case IH 9240) and with Claas combine (Lexion 8900) as well.

**Comment by Tensuko** [comment]
Logfile ?
And what does sometimes mean ? In wich situation ? Screenshots might help.

**Comment by RedMonster-HUN** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4364951/log.txt)
Screenshot and video later

**Comment by Tensuko** [comment]
Try a newer AD Version.
I think this should be fixed:
https://github.com/Stephan-S/FS19_AutoDrive/releases

**Comment by Tensuko** [comment]
Closed due to inactivity.
