### ISSUE TITLE
Problem bei durchfahrsilo / Problem with drive through silo

### ISSUE THREAD

**Issue by Meditos77** [Courseplay/courseplay#5091]
Hallo. Ich habe ein Problem mit dem Durchfahrsilo.  Habe mehrere verschiedene Karten versucht mit Mods und ohne Mods. Funktioniert nur bei Standard Karten. Aktuelle Version von CP: v6.01. 00397
Problem: Ich fahre ganz normal den Kurs ein, durch das Durchfahrsilo durch und wieder zurück zum Hofsilo. Alles ok. Wenn ich aber zum Durchfahrsilo komme, öffnet die Ladeklappe vom Anhänger und es ist egal welcher Anhänger, ladet das Material normal ab, und fährt raus. Super aber die Klappe schließt nicht mehr. Wenn ich dann beim Hofsilo stehe ladet er wieder aber alles fällt raus, weil ja die Klappe offen ist. Nur wenn ich das Fahrzeug anhalte, auf I drücke, und wieder starte funktioniert es. Aber das sollte ja automatische gehen. Woran liegt das? Kann ich das ändern ?

Translated by Google:
Hi there. I have a problem with the drive-through silo. Tried several different cards with mods and without mods. Only works with standard cards. Current version of CP: v6.01. 00397
Problem: I drive the course as normal, through the drive-through silo and back to the courtyard silo. Everything OK. But when I get to the drive-through silo, the loading flap of the trailer opens and it doesn't matter which trailer, unloads the material normally and drives out. Great but the flap no longer closes. Then when I stand by the courtyard silo it loads again but everything falls out because the flap is open. Only when I stop the vehicle, press I and start again does it work. But that should be automatic. Why is that? Can i change that?

**Comment by Meditos77** [comment]
Tut mir leid wegen LOG. Kein Fehler. Keine Warnungen. Ladet alles normal

I'm sorry about LOG. No mistake. No warnings. Load everything normally

**Comment by Tensuko** [comment]
Logfile möchte ich trotzdem immer gerne sehen, weil man mehr sieht als nur Fehler.

Das Problem kann sich mit einem anderen Trailer schon wieder beheben, das ist das merkwürdige an der Geschichte.

Ich war mit @Rumspringa90 schon am testen und er hatte auch einen guten Ansatz als fix, aber komischer weise hilft das auch nicht bei allen Trailern (siehe  #5041 ). Ich hoffe er kontaktiert mich noch mal auf Discord das man da noch einmal über diese Problematik sprechen kann.

**Comment by Meditos77** [comment]
Welchen log willst den haben von den 15 Karten die ich getestet habe? und ich habe jeden Trailer getestet. Die Standard und auch andere. Mache das seit 4  Tagen. Sogar meine eigene map x- Tausend male umgebaut da ich dachte es liegt an meiner Map. Es ist ja so. Er fährt rein, sagt an dieser stelle abladen, aber der Befehl das es vorbei ist, bekommt er nicht mehr. Macht man nach der BGA eine tipCol  hin, ladet er nicht mehr ab bis sie vorbei ist. Keine Schließung. Macht man die BGA kaufbar, das gleich. Selber einen Punkt setzten das er hier abladen soll, das gleich. Also ich glaube das er den Befehl nicht bekommt, zb.: nach 30sek schliessen oder so nicht mehr kommt. Achso und ich habe auch andre BGA´s getestet . Immer wieder das gleiche. Und die einzigen Addons die im Ordner sind ist: FS19_EasyDevControls und Coursplay. Ab und zu Auto drive. Also ich würde ja versuchen, eine Zeit rein zu bauen. ist immer eine Sichere Variante. Wenn Füllung 0 ist 15 sec schliessen oder so.

**Comment by Meditos77** [comment]
Problem Gelöst. Hätte ich aber auch gleich drauf kommen können. Ich bin immer durch das Fahrsilo in Richtung Ladestelle gefahren. Ich glaube das er in den nächsten trigger gekommen ist und somit den Ladevorgang noch einmal gestartet hat. Jetzt habe ich das ganze umgedreht. Ich fahre von der Ladestelle durch das Fahrsilo und dann raus. Und sofort nach dem entladen, schließt sich der Anhänger. Das einzige was noch ist, das Fahrzeug fährt viel zu schnell durch das Fahrsilo. Das heißt zumindest bei mir darf der Anhänger nicht grösser sein als 45000 Liter. Sollte er Größer sein, fährt er über das Silo hinweg und ladet alles Außerhalb .  Wie gesagt. Sobald ein anderer trigger in Reichweite kommt, startet er den Ladevorgang noch einmal. Habe beide Durchfahrsilos voll gemacht und dabei ist nur 1 mal der Fehler mit dem Offen bleiben da gewesen. Aber das war auch nur, weil 2 Fahrzeuge gewartet haben bis der Verdichter fertig war und beide sind dann durch gefahren. das hat er nicht gemocht.
