### ISSUE TITLE
Combing Self Unload Returns to 1st Waypoint

### ISSUE THREAD

**Issue by Tankieboy** [Courseplay/courseplay#5092]
After the combine unloads to the trailer it returns to the first waypoint on the field and not at the point where it moved off to unload?

**Comment by Tensuko** [comment]
Logfile ? It doesn't happen for me...

**Comment by Tankieboy** [comment]
https://1drv.ms/t/s!AkecDx3ps5u4oUL5SJPZoYs8fSML

**Comment by Tensuko** [comment]
Unzip:
Error: Invalid mod name 'FS19_IdealExtension_Bitte entpacken'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

Don't do this:
Error: Failed to open xml file 'D:/Documents/My Games/FarmingSimulator2019/mods/mod/modDesc.xml'.
Load mod: mod
Error: Missing descVersion attribute in mod mod
Error: Invalid mod name 'mod - Copy'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

Mod Error:
2020-03-22 10:53 Error: Can't load resource 'D:/Documents/My Games/FarmingSimulator2019/mods/FS19_johnDeereCottonPack/dataS/scripts/vehicles/Vehicle.lua'.
(Looks like a Mod Version of the DLC, not going to support this one, specialy if ppl failed to get it right...)

Some more Errors and a Callstack from a failure Mod.

Clean up your Mods pls...

**Comment by Tankieboy** [comment]
Great suggestion, will see what I can do

**Comment by Agrargorn** [comment]
Having the same issue with the DLC Lexion 8900
[log.txt](https://github.com/Courseplay/courseplay/files/4369864/log.txt)

**Comment by Tankieboy** [comment]
Same combine I am using. Thank god, thought I was going mad!

**Comment by Agrargorn** [comment]
But iirc, I had similar issues back then, when I didn't had enough money and rented the small rostselmash combine, but it was some courseplay missions before, maybe 3 weeks ago or something. It had even started to produce ai traffic issues in the log, and was rioting to even generate a route to unload the tank, but thats off topic.

**Comment by Agrargorn** [comment]
![20200412234854_1](https://user-images.githubusercontent.com/62554598/79080822-798a1100-7d18-11ea-914a-b6202fe5346d.jpg)
![20200412234858_1](https://user-images.githubusercontent.com/62554598/79080823-7a22a780-7d18-11ea-88cc-5144a26733e6.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/4467227/log.txt)

Here, tried my best to get the harvester, while he was doing his self unload thing, where he starts at waypoint 1 again

**Comment by Agrargorn** [comment]
![20200413000647_1](https://user-images.githubusercontent.com/62554598/79081141-e3a3b580-7d1a-11ea-950b-fef6ecc1a254.jpg)
![20200413000719_1](https://user-images.githubusercontent.com/62554598/79081142-e4d4e280-7d1a-11ea-9b15-67231b124527.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/4467250/log.txt)

got some more, where you can see how the combine startet the patch to unload and then got back to waypoint 1
