### ISSUE TITLE
Schaufelpositionen

### ISSUE THREAD

**Issue by Niceaux** [Courseplay/courseplay#5094]
Hallo,

ich habe auf dem Dedicated Server das Problem, dass ich keine Schaufelpositionen speichern kann (und Mode 9 dementsprechend nicht nutzen kann).
Die Position lässt sich speichern, wird auch grün und zeigt "OK". Wenn ich dann einen Kurs einfahre kommt immer "Es fehlen Schaufelpositionen" - obwohl diese definiert sind.
Also wollte ich diese übers CP HUD einfach mal setzen - der Pfeil wird jedoch nur rot. Nichts passiert. Nach einigem rumprobieren freezen dann alle Fahrzeuge, und es hilft nur ein Relog.

**Comment by Tensuko** [comment]
Collecting all in #5484
