### ISSUE TITLE
plowing switch to late on its offset position

### ISSUE THREAD

**Issue by eknievel115** [Courseplay/courseplay#5097]
Hi 2 things when the harvester pulls over to the side and the tractor pulls up beside it can you make it so the tractor back out of the way and the second thing is for plowing when the plow makes 1 pass and turns around it starts plowing over a bit then moves over where it supposed to be.

**Comment by Tensuko** [comment]
First is Mode2 (see #3311 and #4286 ). The second... I have no Idea where you talking about...

**Comment by Tensuko** [comment]
Ok I got what happens on the 2nd one.
Turn ends then switch to its offsetposition
![fsScreen_2020_03_25_19_09_49](https://user-images.githubusercontent.com/27344744/77570594-5401a880-6ecc-11ea-8165-d3fc4bd7fb69.png)
log mit 7 12 und 14
[log.txt](https://github.com/Courseplay/courseplay/files/4382682/log.txt)

See position where he ends turn and markers where he will go after turn.
![fsScreen_2020_03_25_19_12_12](https://user-images.githubusercontent.com/27344744/77570760-9925da80-6ecc-11ea-887b-1fff023d2a2a.png)

**Comment by TinyCrocodile** [comment]
I ran into the same problem a few days ago. It seems to me he is calculating the turn end target postiton without the tool offset. 
I swiched then tool offset to 0 and used lane offset instead. Still the same.  

I turned off turn on field and turned on AI turns but no pathfinding.  This solved the offset problem.
I guess with tool lowering early this would be ok for ploughing but i need some more testing  and report my findings here.

**Comment by vorezal** [comment]
I ran into this problem as well. Same as TinyCrocodile, using AI turns with pathfinding and turn on field off helped (assuming the AI could manage the turn). The same issue seems to exist for courses run with multiple tools. Perhaps offsets are treated the same way there.

**Comment by pvaiko** [comment]
The plow works great if you turn on the AI Turn Maneuvers in the advanced settings.

**Comment by pvaiko** [comment]
should be fixed by 57
