### ISSUE TITLE
Silo wird nicht richtig entleert

### ISSUE THREAD

**Issue by xerion8300** [Courseplay/courseplay#5098]
Wenn ich auf den Mod Schaufelbeladen gehe meinen Kurs einfahre und starte , füllt er drei bis vier mal richtig die Schaufel. Danach funktioniert es nicht mehr siehe Video
[log.txt](https://github.com/Courseplay/courseplay/files/4369671/log.txt)

[https://www.youtube.com/watch?v=n85LDAwKv5U&feature=youtu.be](url)

**Comment by Tensuko** [comment]
Duplicate of #4891

Closed.
