### ISSUE TITLE
Häcksler + Pickup Problem

### ISSUE THREAD

**Issue by eric4072** [Courseplay/courseplay#5099]
Hi, 

Der Häcksler (egal welcher und egal auf welcher Map, mit oder ohne Mods) hebt seit langem an Ende einer Schwad bzw. vorm umdrehen die Gras-Pickup nicht. AD fährt schön neben bei her, am Ende der Schwad steht dann "Häcksler wenden lassen", er setzt zurück und wartet dann auf das beenden des Wendemanövers. Scheinbar bekommt er aber dann von Courseplay keine Meldung dass er sich wieder neben den Häcksler stellen soll.

Weiters ist das Problem dass der Häcksler dadurch, wenn er irgendwo in seinem Wendemanöver ein wenig Gras in seinem Fahrtweg findet, stehen bleibt weil er natürlich nichts zum "überladen" findet.

Wär schön wenn Ihr dazu eine Lösung findet ;-)

Danke
Eric

Edit: Auch beim starten mit "Arbeitsmodus" und "Erster Punkt" senkt der Häcksler die Pickup nicht. Bei   starten mit "nächstliegenden Punkt" das selbe...

Mach ich hier irgend was falsch? Dachte mir nach 450 Std. LS19 und 1500 std LS17 hab ich CP gut im Griff...

**Comment by Tensuko** [comment]
Da kannst du so viel Zeit im LS haben wie du willst, wenn es nicht geht, geht es nicht :)
Ich guck es mir an, könnte durchaus ein Bug sein.
Denke mit richtigem absenken und anheben beim Wenden sollte auch das Problem mit dem AD Abfahrer behoben sein ?

**Comment by eric4072** [comment]
Ich weiß nicht ob AD das senken und heben der Pickup erkennt, da ja am Ende der Schwad auch die Pickup nicht gehoben wird. AD erkennt aber den Beginn des Wendemanövers das er zurücksetzen und warten muß.

**Comment by Tensuko** [comment]
Ich schaue es mir bei gelegenheit an.

**Comment by Merrlin** [comment]
Duplicate of #4944 😛

**Comment by Tensuko** [comment]
Danke, man kann ja nicht alles Issues im kopf haben...
Closed da duplicate...
