### ISSUE TITLE
Global Company BGA wird nicht befüllt

### ISSUE THREAD

**Issue by Schorlensteve** [Courseplay/courseplay#5100]
Hallo, 
habe seit kurzem die BGA von Global Company und wollte sie durch Courseplay mit Silage befüllen lassen (Schaufel befüllen und entleeren), aber leider bleibt der Helfer immer einige Meter vor dem Beschicker stehen. 
Habe in anderen Threads schon gelesen das auch andere das Problem haben und am Ende, dass das Problem eigentlich gelöst sein sollte, bei mir funktioniert es jedoch weiterhin nicht. Ich verwende die neueste Version von CP und habe alle Mods auf dem aktuellsten Stand.

Leider bin ich noch neu hier und weiß noch nicht wie ich logfiles o.ä. erstelle, deshlab bitte ich um Nachsicht falls es nicht gleich funktioniert oder öfter mal etwas nachgeliefert werden muss.

**Comment by Tensuko** [comment]
Also eine Lösung könnte sein, den dritten 'Wartepunkt' mit dem Editor etwas weiter in die BGA zu schieben, genau so wie der Wartepunkt 'im Trailer' sein sollte. Ob das geht bin ich mir nicht sicher, könnte sein das man da Änderungen am Mode selber machen müsste.

Alternativ, wenn es die gleiche BGA ist die ich auch nutze, mit einem Trailer abkippen, gibt da nen Trigger, kriege den auch nicht immer erwischt, da er etwas doof sitzt, aber könnte klappen.

**Comment by Schorlensteve** [comment]
Habe bereits versucht den Wartepunkt weiter in die BGA zu schieben, hat aber leider nur mäßig geklappt und vor allem nicht den erhofften Erfolg gebracht. Ich versuche es aber noch ein paar mal, vielleicht finde ich ja einen Punkt an dem es klappt.

Habe momentan als Abhilfe einen großen Futtermischwagen direkt vor dem Beschicker platziert, den CP fleißig befüllt, welcher wiederum von mir dann regelmäßig in die BGA entleert wird. Wäre nur schön wenn es auch ohne diesen Zwischenschritt funktionieren würde, da ich dafür dann auch immer extra einen Schlepper brauche.

**Comment by Tensuko** [comment]
Ich weis gerade nicht, ob Förderbänder funktionieren mit dem Lader...

**Comment by Schorlensteve** [comment]
Ist denn bekannt, warum das mit CP nicht funktioniert? Liegt das nur an einem verdammt schwer zu findenden Triggerpunkt (also letztlich an Mir), oder funktioniert CP mit der BGA von Global Company einfach nicht? In der Ursprünglichen/originalen BGA auf Felsbrunn hat das beschicken mittels CP ja ohne weiteres funktioniert...

**Comment by Tensuko** [comment]
Das könnte noch was mit GC Triggern in Verbindung mit dem Schaufelmodus sein, aber im Moment keine Zeit dazu genauer nach zu sehen. Issue bleibt aber offen, keine Sorge :)

**Comment by Alkoholix** [comment]
> Habe momentan als Abhilfe einen großen Futtermischwagen direkt vor dem Beschicker platziert, den CP fleißig befüllt, welcher wiederum von mir dann regelmäßig in die BGA entleert wird. Wäre nur schön wenn es auch ohne diesen Zwischenschritt funktionieren würde, da ich dafür dann auch immer extra einen Schlepper brauche.

Ich hab die "Fliegl Überladestation" vor die BGA gestellt, damit funktioniert es.

**Comment by schwiti6190** [comment]
Should be fixed with the last shovel mode fix
