### ISSUE TITLE
Multiple harvesters

### ISSUE THREAD

**Issue by Misamangame** [Courseplay/courseplay#5101]
Hello guys,
I would like to address two issues I have since last update.  I'm running 5 vanilla CASE 9240 harvesters on the field and when they reach full capacity it they will simply stop and waiting for tractor with overloader to unload. Unfortunately since last update the middle harvester when it reach 100% capacity it will make strange turn and goes somewhere, it could be just 20m, but in some cases he just went all over the field until I stopped him manually.(LOG attachement after I sttopped combine about 400m)  When tractor with trailer will catch him on this way and unload atleast part of capacity he will turn back and going to the place where he left and continue harvesting since that point like nothing happened.....  if you need some debug channell let me know, log is in attachement.
[log.txt](https://github.com/Courseplay/courseplay/files/4371459/log.txt)

Second issue is with convoys. I know it was fixed in last updates but I'm still experiencing problems.  When you start course  and set for example 100m, combines are going one by one in 100m spaces but when you have to stop lets say second of them third one might or might not stop in 100m distance and continue harvesting even overtake this second combine. I found easy fix with making immedietely bigger distance but it acts very strangely, because when I immedietely raise the distance for example on 200m combine will stop and keep distance saying 200m (can be even 400m) but distance is still 100m you can see it. This happens very randomly but I think when you once have to interupt initial start settings it will mess up. I don't have a log for this.

**Comment by Tensuko** [comment]
The question is how did you set it up and is self unload or fruit bypass activated ? I would turn both off when driving in Convoy (for now).
And yes ofc the Combine will fly out of the Convoy when you stop the CP Driver.

**Comment by Misamangame** [comment]
Hello Tensuko, you hit the nail to the head I really forgot to turn off self unload. I just use it very rarely on small field, but this was the issue of harvester going somewhere, you can close it now.

**Comment by Tensuko** [comment]
Oh okay :) Well that was a fast and easy soultion then :)
