### ISSUE TITLE
Abfahrer kolision

### ISSUE THREAD

**Issue by andrenrei** [Courseplay/courseplay#5103]
Hallo,
ich habe folgenden fehler entdeckt jedes mal wen mein abfahrer zum drächer fahren will kolidiren diese wen sie dan mit meiner hilfe neben einander stehen kolidiren die die zwei auch da der abfahrer nach dem abtank vorgang oft (nicht immer) über die spur des drächers zufahren siehe bilder und Video:
https://youtu.be/Z8TxU0qMNVw
https://youtu.be/XAIf12viz1M

![20200324_063200](https://user-images.githubusercontent.com/52126557/77392539-7942c980-6d9b-11ea-9c40-2575b3cc2571.jpg)

**Comment by Tensuko** [comment]
Siehe #3311 und #4286 
Und für Screenshots gibt es die Druck taste auf der Tastatur, die Bilder werden dann im Ordner Screenshots abgelegt, dort wo auch dein mods Ordner ist.

**Comment by andrenrei** [comment]
danke für die schnelle antwort
