### ISSUE TITLE
CP drives tractor with seed drill too far back - CP fährt Traktor mit Saatmaschine zu weit rückwärts

### ISSUE THREAD

**Issue by haamic** [Courseplay/courseplay#5107]
Hello,
I am driving the Condor seed drill in the field and have noticed that CP is going too far when reversing. 
I seem to remember that CP used to drive forward again as soon as the seed drill reached the "turning point". Now CP drives backwards until the tractor reaches this point.  Please improve. So it makes no sense if you could only make a headland and still drive the seed drill backwards to the edge of the field and beyond. 
You might collide with trees that are too close together.
Forwards is comparatively the same as it should be backwards.
Enclosed 2 pictures, I hope they explain what I mean.
Greetings Micha
+++++++++++++++++++++++++++
Hallo,
ich fahre mit der Saatmaschine Condor auf dem Feld und habe festgestellt, das CP beim rückwärtsfahren viel zu weit fährt. 
Ich glaube mich zu erinnern, das früher CP wieder vorwärts fuhr, sobald die Saatmaschine den "Wendepunkt" erreicht hatte. nun Fährt CP so lange rückwärts, bis der Traktor diesen Punkt erreicht.  Bitte nachbessern. So macht es keinen Sinn, wenn man nur ein Vorgewende machen konnte und die Saatmaschine trotzdem bis zum Feldrand und darüber hinaus rückwärts gefahren wird. 
Da kollidiert man mit evtl zu dicht stehenden Bäumen.
Vorwärts ist das vergleichsweise so, wie es rückwärts sein sollte.
Anbei 2 Bilder, hoffe die erklären es , was ich meine.
Gruss Micha

![CP Rückwärts](https://user-images.githubusercontent.com/28841989/77513046-7d8ee580-6e74-11ea-9156-afbc7dc72589.jpg)

![CP vorwärts](https://user-images.githubusercontent.com/28841989/77513058-8384c680-6e74-11ea-8356-51256c763245.jpg)

**Comment by Tensuko** [comment]
Log mit debugchannel 7 12 und 14

**Comment by haamic** [comment]
I had to restart my PC, after that I wanted to activate the debugchannel, but now I can't recreate this behaviour anymore. 
Now it works as it should. I can't explain it to myself, I haven't made any changes. 
Strange. Sorry for my issue. 
I'll close up.
++++++++++++++++++++++++++++++++++++
Ich musste meinen PC neustarten, danach wollte ich die debugchannel aktivieren, aber ich kann nun dieses Fahrverhalten nicht mehr nachstellen. Nun funktioniert es so, wie es soll. Ich kann es mir nicht erklären, habe keine Veränderungen vorgenommen. Merkwürdig. Sorry für mein Issue. 
Ich mach mal zu.

**Comment by Tensuko** [comment]
Die schönsten Issues sind die, die sich von alleine erledigen :)
