### ISSUE TITLE
triggers.luca.625 and "table index is nul"

### ISSUE THREAD

**Issue by Martin3111** [Courseplay/courseplay#5110]
Please help me! I just can't use che courseplay in any way! I will just copy the error seen in my log! Sorry for my bad english! 

2020-03-25 20:21 Error: Running LUA method 'mouseEvent'.
2020-03-25 20:21 C:/Users/Luca/Documents/My Games/FarmingSimulator2019/mods/cp/triggers.lua:625: table index is nil

**Comment by Merrlin** [comment]
Komplettes Logfile bitte...
Complete Logfile please

**Comment by Martin3111** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4383587/log.txt)

**Comment by Martin3111** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4383600/log.txt)

**Comment by Tensuko** [comment]
You need GlobalCompany 1.3.0.0 (should be on ModHub)
Load mod: FS19_GlobalCompany (Version: 1.0.0.0) (Hash: 4f1b2483641ac42d73a774d6a218e197)

If that doen't help, more details on what you did and what you try to do.

**Comment by Martin3111** [comment]
Just added the latest version of global company but I think it's still the same...

[log.txt](https://github.com/Courseplay/courseplay/files/4386294/log.txt)

**Comment by Martin3111** [comment]
And I've just tryed on another map (geiselsberg) and it is working!

**Comment by Tensuko** [comment]
Well I would say you got an Issue in the Map :)
