### ISSUE TITLE
Feature Request: Avoid fences/trees

### ISSUE THREAD

**Issue by realskudd** [Courseplay/courseplay#5111]
I'm digging the new pathfinding update, but it's leaving something to be desired for fields bordered by trees or fences. This is especially a problem when it comes to combine usage and combine unloading.

Being a software engineer myself, I realize this may be a significant effort. However, would it be possible to put some sort of a forward-looking scan for obstacles into the pathfinding? I have to admit that I'm not well versed in LUA, so the details of this ask are a bit high level coming from me.

**Comment by Tensuko** [comment]
That new pathfinding does exactly this. Vehicles have a Border arround them and the Pathfinder checks whats in the way (must be turned on in the advanced settings ofc) but as most problems that we have are mods, the fences and trees must have the right information as well, even they have collission, it is not enough if I understood it right. @pvaiko knows whats needed.
What we still want to add in the future is, that CP is able to see what turn works better, when AI and Pathfind is active, to see if there is enough space. But thats not our priority right now.

**Comment by pvaiko** [comment]
As @Tensuko said, however, the current pathfinding on master has a bug and does not recognize all obstacles. If I'll have a minute I'll merge those parts from the Mode 2 branch to fix that.

That will however come at a price, finding a path will take longer... Also, we aren't really good yet figuring out how much space a big trailer may need during a turn.

**Comment by pvaiko** [comment]
@realskudd BTW we could really use some software engineers here....

**Comment by realskudd** [comment]
@pvaiko If I had the time, I'd pick it up. 

It seems like the pathfinding is just a very narrow (0.5m) area in front of the vehicle. I've noticed combines with a large header struggle with catching on fences and trees, and that if the obstacle isn't directly in front of a tractor or truck - like 10 to 15 degrees off center - it sees it as clear space.

**Comment by realskudd** [comment]
> That new pathfinding does exactly this. Vehicles have a Border arround them and the Pathfinder checks whats in the way (must be turned on in the advanced settings ofc) but as most problems that we have are mods, the fences and trees must have the right information as well, even they have collission, it is not enough if I understood it right. @pvaiko knows whats needed.
> What we still want to add in the future is, that CP is able to see what turn works better, when AI and Pathfind is active, to see if there is enough space. But thats not our priority right now.

**Comment by realskudd** [comment]
>  but as most problems that we have are mods, the fences and trees must have the right information as well, even they have collission

I think this is the key. I've been playing on the County Line map lately, and some of the fields have trees right on the field border, no margin. Maybe they're not marked as an obstacle. FWIW, I don't have a very strong understanding of the different aspects of FS modding, so I may be using high level terms again. ;P

**Comment by pvaiko** [comment]
@realskudd as I said, the current version on master has a bug which causes it not recognizing all obstacles.

**Comment by realskudd** [comment]
I apparently can't github well. I mistakenly closed the issue but have since reopend it.

**Comment by Willbobber** [comment]
Just for information what are the correct settings that CP looks for on trees and hedges for the collision??

**Comment by Tensuko** [comment]
Improoving the Pathfinder (and also the behaviour in turns) is always on our list and for sure mentioned in other Issues.
Closing this.
