### ISSUE TITLE
Forage harvester changing offset of tractor

### ISSUE THREAD

**Issue by kobra60** [Courseplay/courseplay#5112]
When using a forage harvester with capacity, I manually set the offset of the tractor for unloading to be on the left side.  As it approaches the harvester it changes to the right side and I can't seem to force it to stick to my setting.  Auto never seems to work with my mods and it works great when it does stick to the left.  I am usually using an auger wagon behind the tractor and the only way I know how to get it to unload is to leave the pipe out. (Until mode2 is ready)  This causes the pipes to tangle most every time.  Is there a setting that I'm missing to force that left side unload?

Thanks for all you guys do for this!

**Comment by Tensuko** [comment]
This is also a part of Mode2, that side control stuff.
You will have to wait a bit more, we are currently 100% focused on Mode2, kinda every day.
