### ISSUE TITLE
Combine empty mode doesn't function correctly

### ISSUE THREAD

**Issue by falconluan** [Courseplay/courseplay#5113]
Test environment:
To eliminate as many non-related factors as possible, the test ENV is game default EU map with game default machines. 
No other mod than courseplay V6.01.00397 is loaded.
The harvester is controlled by game default worker.
A simple mode 2 route was setup, to unload the harvester and dump into the silo in farm.

Issues:
1. The tractor was driving in fruit side
2. The tractor was stopped at positions which block the way of harvester some time
3. The harvester was not released when trailer was full and tractor left the field to dump crops

I've a video here:
https://youtu.be/GK5l3KiP3pk

Also, I saved the corresponding game log(not sure it can be pasted directly here).
[Uploading log_EU_default.txt…]()

**Comment by Tensuko** [comment]
Another one who can't read Pinned Issues.
See #3311 (pinned) and #4286

Closed.

**Comment by falconluan** [comment]
Ah, sorry, didn't know the latest release still has got the most updated mode 2 code ...
Anyway, thank you for all the hard work on this project.
