### ISSUE TITLE
"Konnte keinen Kurs generieren"

### ISSUE THREAD

**Issue by F7ori3** [Courseplay/courseplay#5114]
Hallo,

ich habe seit heute das Problem das die Meldung:
**"Konnte keinen Kurs generieren. Versuchen Sie, die Einstellung zu ändern oder das Fahrzeug zu bewegen"**
Habe auch Coursplay schon aktualisiert.  Ich habe auch verschiedenen Maschine ausprobiert sowie verschiedene Felder. 

[log.txt](https://github.com/Courseplay/courseplay/files/4389754/log.txt)

**Comment by Tensuko** [comment]
Screenshot mit den Einstellungen im Kursgenerator bitte.

**Comment by F7ori3** [comment]
Danke für die Antwort, 
hier die Einstellungen. 
![Screenshot (1)](https://user-images.githubusercontent.com/62722039/77854915-6a21a880-71ed-11ea-9087-c05d37891611.png)

**Comment by Tensuko** [comment]
Aktuell geladener Kurs ? Nicht Feld 25 ?

**Comment by Tensuko** [comment]
Closed due to inactivity
