### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by Bandesss** [Courseplay/courseplay#5115]
Hallo zusammen welche Version ist denn gerade Tauglich für einen Multipalyer ?
Danke schon mal

**Comment by Merrlin** [comment]
Die Versionen, die in der Releases Section zu finden sind, sind alle auch Multiplayerfähig.

**Comment by Bandesss** [comment]
Ja aber zb Gras abfahren mit CP und dann Ad geht nicht ?! Darum fragte ich welche gut ist im Mp

**Comment by Tensuko** [comment]
MP funktioniert nur Teilweise weil wir niemanden haben der es weiter verbessert. Es gab kurz jemanden der es aktiviert hat und ein oder zwei sachen gemacht hat und das wars. Ist leider so.

**Comment by Bandesss** [comment]
Wie gesagt, ich habe davon keine Ahnung könnte
 es nur Testen

**Comment by Bandesss** [comment]
Durfte man für euch werben in verschiedenen Foren ? Das ihr noch Entwickler sucht?

**Comment by Tensuko** [comment]
Wüsste nicht was dagegen spricht, aber das muss natürlich passen was die dannmachen.

**Comment by Bandesss** [comment]
Es wird sich bestimmt jemand finden.
Habt ihr ein Discord für euer Courseplay

**Comment by Tensuko** [comment]
Keinen öffentlichen, nur auf Einladung, der jenige solltesich dann einfach auf github melden

**Comment by Bandesss** [comment]
Könnt ihr mir für du suche noch sagen was ihr genau sucht, sricpter lua usw ?

**Comment by Tensuko** [comment]
Naja jemanden der mit LUA und LS19 scriptdoku vertraut ist und für MP sich auch mit der Server geschichte auskennt.

**Comment by Bandesss** [comment]
Super, dann werde ich in den Foren Giants und ls Modcompany usw ihre Suche schalten und sie hierher verweisen

**Comment by Tensuko** [comment]
Also bei Farming-Simulator Website kannst du das gleich vergessen, weil ich weis was sich da für Leute tummeln und wie die Kommentare aussehen.
Bei LS-Modcompany bin sich selebr unterwegs.

**Comment by Bandesss** [comment]
Es gibt soviele Community s wo ihr dann die suche Posten konnt modding Welt lsfarming Landeier 
Da wird sich, doch jemand finden.

**Comment by Tensuko** [comment]
Jo in Modding Communitys klar wenn die gute Mods machen da kann man mal Werbung machen, sofern die Leute da nicht so drauf sind wie im Offiziellem Forum und erstmal CP die Schuld an allem geben sobald ein Fehler auftritt :)

**Comment by Bandesss** [comment]
Ich hatte auch forbidden mods vergessen.
Erstellt ihr eine suche ? Oder soll ich eine erstellen
