### ISSUE TITLE
Wende auf dem Feld funktioniert nicht

### ISSUE THREAD

**Issue by Schorlensteve** [Courseplay/courseplay#5116]
Hi,
habe momentan das Problem das ich es nicht auf die Reihe bekomme, dass CP auf dem Feld wendet (Samson PG II 25 + SBH4 36m, John Deere 8400R, nur original Fahrzeuge). Wende auf den Feld ist aktiviert, Fruchtumfahrung sowie AI/Pathfinding in den Advanced settings habe ich testweise einzeln an bzw. abgeschaltet. Ergebnis war immer, dass CP zum Wenden das Feld verlassen hat und regelmäßig an irgendwelchen Bäumen hängen geblieben ist.
Allgemeiner fehler, oder bin ich zu dumm zum einstellen?

**Comment by Tensuko** [comment]
Logfile, Screenshot mit Debugchannel 12 und 14 eingeschaltet, das man den Turn sieht und auch im CP HUD bei Settings alle Wegpunkte einschalten (dir 3 Punkte) damit man deinen Kurs sieht.

**Comment by Schorlensteve** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4393114/log.txt)

![Screenshot 2020-03-27 12 18 14](https://user-images.githubusercontent.com/62563289/77751191-807d0800-7025-11ea-9258-86c8341b4c45.png)

![Screenshot 2020-03-27 12 19 01](https://user-images.githubusercontent.com/62563289/77751198-84a92580-7025-11ea-8103-894a99a9e5f6.png)

![Screenshot 2020-03-27 12 19 05](https://user-images.githubusercontent.com/62563289/77751210-896dd980-7025-11ea-8ade-b0b3400a58bf.png)

![Screenshot 2020-03-27 12 19 14](https://user-images.githubusercontent.com/62563289/77751235-94c10500-7025-11ea-8b84-8717b1ede702.png)

![Screenshot 2020-03-27 12 19 11](https://user-images.githubusercontent.com/62563289/77751226-9094e780-7025-11ea-9651-b30a20262ec0.png)


![Screenshot 2020-03-27 12 19 09](https://user-images.githubusercontent.com/62563289/77751219-8d99f700-7025-11ea-9a37-01b11c719556.png)

**Comment by Schorlensteve** [comment]
Gleiches Problem tritt auch bei anderen Geräten auf, hierbei ist es mir nur zuerst aufgefallen.

**Comment by Tensuko** [comment]
Mal mal den AI Turn aus in den advanced Settings.

**Comment by Schorlensteve** [comment]
![Screenshot 2020-03-27 12 30 37](https://user-images.githubusercontent.com/62563289/77751890-cc7c7c80-7026-11ea-8b34-a9a5992a33be.png)

Kleine Veränderung, aber ansonsten gleiches Ergebnis.

**Comment by Tensuko** [comment]
Pathfind ist auch aus ?

**Comment by Schorlensteve** [comment]
Jawohl.
![Screenshot 2020-03-27 12 36 56](https://user-images.githubusercontent.com/62563289/77752399-c5a23980-7027-11ea-9afc-ca7546d998ce.png)
![Screenshot 2020-03-27 12 37 02](https://user-images.githubusercontent.com/62563289/77752400-c6d36680-7027-11ea-8eb2-b11218350145.png)

**Comment by Tensuko** [comment]
Das Problem sollte dies sein:
2020-03-27 12:45 :01 [dbg14 lp13525] TurnContext: Field edge not found (vehicle not on field)
Müssen wir schauen was man da machen kann. Dauert aber da momentan die Priorität auf etwas anderes liegt. Ich würde dir vorschlagen ein Vorgewende ein zu bauen.

![fsScreen_2020_03_27_13_00_36](https://user-images.githubusercontent.com/27344744/77754137-02236480-702b-11ea-8977-cd25c9e8dfad.png)

**Comment by Schorlensteve** [comment]
Alles klar, dann mach ich das, Danke!

**Comment by Tensuko** [comment]
Versuch noch mal mit v .00063, könnte nun klappen wenn das Fahrzeug damit rückwärts fahren darf.

**Comment by Tensuko** [comment]
Sollte nun gehen, wenn noch Probleme da sind, lass es uns wissen.
