### ISSUE TITLE
Startwegpunktoptionen nicht auswählbar

### ISSUE THREAD

**Issue by Niceaux** [Courseplay/courseplay#5118]
CP aktuelle Version, Dedicated Server:

Wenn man allein spielt, kann man Courseplay absolut wie vorgesehen nutzen. Keine Probleme.

Sobald ein zweiter Spieler dem Spiel beitritt, gibt es massive Probleme. So kann man dann zB. den Startwegpunkt ("erster Wegpunkt" und "Nächster passender Wegpunkt") so nichtmehr auswählen.
Beide Optionen verschwinden.

Ausserdem kommt es teilweise vor, dass manche Geräte plötzlich nur noch ihren Kurs abfahren, obwohl Feldarbeit eingestellt ist wird dann das Gerät nichtmehr gesenkt/angeschaltet.

**Comment by Justice-Molton** [comment]
Kann ich bestätigen, gleiches passiert bei uns auf dem Server.

**Comment by Tensuko** [comment]
Ein logfile wäre immer schön sowohl Client als auch Server. Allerdings haben wir aktuell niemanden der an der MP fähigkeit von CP arbeitet... so leid es mir tut.

**Comment by Justice-Molton** [comment]
Also brauchst Du auch keine Logs?

**Comment by Tensuko** [comment]
An sich nicht nein, wie gesagt, ist immer nice to have im Fall das einer sich das doch mal anguckt findet er gleich die nötigen Daten (oder zumindestens einen Teil). Aber ich glaube nicht, dass das in nächster Zeit passiert...
