### ISSUE TITLE
Panther Beet Harvester Auto Unload

### ISSUE THREAD

**Issue by Dune02** [Courseplay/courseplay#5120]
When using CP with auto unload the panther 2 wont get close enough to the trailer to unload but also dosent give a prompt saying that it needs to be unloaded. Screens included.
![20200328132903_1](https://user-images.githubusercontent.com/39396621/77833262-42511880-70f9-11ea-97ed-35d9b14ef04c.jpg)

**Comment by Tensuko** [comment]
Need to check on this one. Not sure if it is able to but you trailer also looks very high for the unload...

**Comment by Dune02** [comment]
I did notice that when I left it without a tractor on the side of the field it seemed to work more reliably.

**Comment by Agrargorn** [comment]
I'm having a similar issue with the holmer terra dos and the it runner with the containers, it doesnt't really matter if the container is on the wagon or not, the terra dos fails to get in place to unload properly

**Comment by Tensuko** [comment]
A lot have changed since that Version and we also have Mode2 active wich I was useing on those tools with success, so closing.
