### ISSUE TITLE
Drescherverband Fps drop

### ISSUE THREAD

**Issue by tschaha** [Courseplay/courseplay#5121]
Hallo, courseplay version 6.01.00397.dev
wenn ich in drescherverband arbeiten will und den Drescher der auf der rechten Spur ist einschalte gehen die fps auf 1 runter. Egal ob mit 2 Drescher (links-rechts) oder mit 3 drescher(links-hinten-rechts). Bei 3 Drescher starten links und hinten ohne probleme nur wenn ich den rechten starte gehen die fps runter und der drescher hat im tempomat nur 1 kmh stehen.
Lg manuel

**Comment by Tensuko** [comment]
komplettes logfile nachdem das aufgetreten ist.
Außerdem Screenshot von deinem Kurs bitte. (Alle Wegpunkte an = die 3 Punkte im CP HUD unter Settings)

**Comment by Tensuko** [comment]
Closed due to inactivity...
