### ISSUE TITLE
Q: how can I donate, or other ways to support the developers?

### ISSUE THREAD

**Issue by caplink811** [Courseplay/courseplay#5122]
see above.
Not found anything, maybe I'm beaten with blindness...

cheers
 JrB

**Comment by Tensuko** [comment]
You can donate by sending nice bug reports (except about Mode2).
You can help with scripting if you can, if you can't and still realy want to support us, you can check our (outdated) Website for the Donation Button Link to Website: http://courseplay.github.io/courseplay/

Enjoy farming :)

**Comment by caplink811** [comment]
so this information on the website is still correct.

thank you
 bye
 JrB
