### ISSUE TITLE
no option to generate course in courseplay 6

### ISSUE THREAD

**Issue by jk2359** [Courseplay/courseplay#5123]
i have on option to generate course in a combine, I have got the newest version courseplay 6 and know other mods running 

can someone help me 

![20200329131126_2](https://user-images.githubusercontent.com/62837905/77848982-498f2980-71c0-11ea-919f-316fa333934b.jpg)

**Comment by Tensuko** [comment]
Becouse you missed our HUD Refactoring several month ago...
See #3552

Closed.
