### ISSUE TITLE
Harvest Unloading

### ISSUE THREAD

**Issue by Deathtoll95** [Courseplay/courseplay#5124]
When I am trying to unload a tipper from combine to silo I usually wait a few seconds on top of the point but now for some reason it blows by the point and slams the break when its too far then continues back to the stop I also have the speeds set at from when I recorded it with the from recording option but it still speeds past the silo and another one I see a lot is the refill seeder and hit a trigger point notification constantly on when its still doing its job

**Comment by Tensuko** [comment]
log, screenshots, no idea what exaclty is your problem

**Comment by Tensuko** [comment]
Closed due to inactivity...
