### ISSUE TITLE
Digestate and slurry refill course.

### ISSUE THREAD

**Issue by tripseven** [Courseplay/courseplay#5125]
Hi guys,
Excellent job so far and of course thank you, this mod, in my opinion, is a must have.

I have encountered a problem while digestate spreading, i am using a vanilla tractor, vanilla spreader, the only deviation from Vanilla is the BGA, i am using a placeable which works in conjuction with Global Company.

After creating the course it runs great, from the field to the digestate refill point as long as MY character is in  the vehicle  while the course is running it will, stop at the fill point, refill properly, and carry on to the field and go to the correct point and start spreading digestate again.

 Here is the problem when i leave the tractor and go do something else or stand by the tractor, well hell the point is i am not in the tractor...lol.  Unfortunately it will not refill the slurry/digestate spreader. The worker will stop and then go back to the field and then realize it is not full and start the refill course again, this will repeat until i get back into the tractor, then and only then will it refill the digestate and carry on as it should.

Thanks for your ears and thanks for a great mod..

**Comment by Tensuko** [comment]
#5055

**Comment by Quintto** [comment]
I had the same issue, ( #5052 )
for me it was resolved by deactivating the manurse system mod, so maybe that will work for you too

**Comment by tripseven** [comment]
Thank you, never gave that fix one thought. I will try this. Again, thank you for your time.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Tensuko** [comment]
Closed due to inactivity/no log/sounds fixed ?
