### ISSUE TITLE
Bunker silo unloading

### ISSUE THREAD

**Issue by s187375** [Courseplay/courseplay#5126]
Hello, I set up a chaff unloading course into a closed bunker silo. The trailer starts to unload as soon as it reaches the "tip trigger" at the bunker's entrance instead of driving all the way inside as goes the course. I have tried setting a P point, unloading point, both, none far inside the bunker but still have the tractor unloading at the bunker's entrance.
Is this an issue or it's just me setting up the course in the wrong way?
Thank you!
[log.txt](https://github.com/Courseplay/courseplay/files/4399831/log.txt)
![fsScreen_2020_03_29_23_28_58](https://user-images.githubusercontent.com/62856466/77861663-8423b100-7216-11ea-9230-5cc008b5df31.png)

**Comment by Tensuko** [comment]
Remove the Waitpoint...

**Comment by Tensuko** [comment]
Also you got an Error:
Error: Failed to open xml file 'C:/Users/Marko/Documents/My Games/FarmingSimulator2019/mods/FS19_pack_5_em_1/modDesc.xml'.
Load mod: FS19_pack_5_em_1 (Hash: 32d1a9df94e72ff9d6fbf42a10606437)
Error: Missing descVersion attribute in mod FS19_pack_5_em_1

This is also a strange Nameing of CP:
FS19_courseplayMaster_0324 (Version: 6.01.00397) (Hash: 7cc41e983ec7368bac994c7e27bbcfa4)

Get a nice Clean Release Version here: https://github.com/Courseplay/courseplay/releases
And only name it FS19_Courseplay, thats it. You will have to reactivate the mod for your savegame but that is all.

**Comment by s187375** [comment]
Hello, thank you for answering so fast.

Did the following:
- deleted mod FS19_pack_5_em_1 that was causing an error,
- Re-downloaded the latest courseplay version and named it FS19_Courseplay (I named the previous inserting the download date - 24th march)
- recorded a new course without Waitpoint
- Tried the unload

Unfortunately I got the same result as before.
[log.txt](https://github.com/Courseplay/courseplay/files/4403407/log.txt)
![fsScreen_2020_03_30_16_15_37](https://user-images.githubusercontent.com/62856466/77923395-b2e76900-72a2-11ea-82d3-faa9cb9d85a9.png)

**Comment by Tensuko** [comment]
Hmm then it was the 'unload here' point, but I also think that we would need some rework on those kind of silos to unload, as there will be for the pass through silos.

**Comment by s187375** [comment]
setting an "unload here" point far inside the bunker gives once again the same result

**Comment by Tensuko** [comment]
ok then I have no other option for you right now.
I think the most problem is that the Mode2 (Combi Mode) that you use isn't able to work with those points and the new Bunker System.
Will have to wait for the rework and then we take a look at those silos if we can make the unload a bit smarter.

**Comment by s187375** [comment]
ok, thanks anyway. no other than waiting for the update.

I know you guys are working really hard at reprogramming Mode2... 1 million dollar question coming: do you have any idea how long till it will be ready (approx. 1 week, 1 month, 2 months,...)?

**Comment by Tensuko** [comment]
I can't give you any Date, as it depends on how much time can be spent on the Project and how many problems we are faceing.
My last status is, that we are on a good way.
Can't rly say more, sry. But I will update you as soon as we have something.

**Comment by TheDestroyerKSP** [comment]
Yeah, I had similar issues. I would recommend unloading into a multifruit silo, then using a separate courseplay driver on mode 1 for silo>bunker.

**Comment by Tensuko** [comment]
Will have to wait for Mode2 Update.

Closed.
