### ISSUE TITLE
Kombination AD und CP

### ISSUE THREAD

**Issue by Christoph1978** [Courseplay/courseplay#5128]
Hallo zusammen,

wenn ich in CP eine Kurs aus dem Autodrive-Ordner für die Anfahrt zum Feld lade und daran einen Feldkurs im Modus „Düngen und Säen“ anhänge, wird der Kalkstreuer direkt am Startpunkt ausgeklappt und eingeschaltet und nicht erst am Feld.

Kann mir einer einen Tipp geben, was ich falsch mache oder ist das ein bekanntes Problem?

Vielen Dank schon mal im Voraus!

**Comment by Tensuko** [comment]
Der Feldarbeitskurs wird nicht angehangen, der wird zu erst geladen, dann entsprechenden Auffüllkurs dranhängen mit dem Ordner mit dem + drin.

**Comment by Christoph1978** [comment]
Ist dann nicht die Reihenfolge falsch?
Ich möchte den Trecker vom Hof zum Feld schicken und dort soll er mit der Arbeit anfangen. Auffüllen und parken soll AD machen.

Werde das aber nochmal probieren.

**Comment by Tensuko** [comment]
Wenn AD fahren soll dann darfst du in CP auch nicht die Kurse laden.
AD benutzt sein Netzwerk, CP benutzt die Kurse die du lädst.
Das gehst du dann komplett falsch an.
Die Kurse im CP Menü sind nur dafür da um die AD Ziele zu nutzen um schnell mal einen Kurs für CP zu laden, wenn man den mal braucht. Das hat nichts mit AD auffüllen und Parken etc zu tun!

Das müsstest du dann im AD GitHub erfragen.

Für CP gilt:
Feldkurs + Auffüllkurs anhängen, mehr ist nicht. Kein zum Feld schicken zum Arbeiten, kein Tanken, kein Parken. Das muss über AD eingestellt werden mit den Zielen.

**Comment by Christoph1978** [comment]
Dann hab ich mich wohl unklar ausgedrückt - sry.
So hab ich das gemacht: im CP Menü einen AD Punkt ausgewählt für die Fahrt Hof - Feld und dann einen Feldarbeitskurs angehängt. Weiterhin im CP die AD-Option auf Refill/Unload and Park, die anderen Einstellungen im AD sind korrekt.
Es geht nur darum, das die Arbeit bereits ab dem ersten Wegpunkt angefangen wird und nicht erst, wenn der Trecker auf dem Feld ist.

**Comment by Tensuko** [comment]
So ist es nicht gedacht und so funktioniert es nicht...
Du lädst einen CP Feldarbeitskurs und wenn du ihn los schicken willst zum Feld, musst du den Rest über AD einstellen, wie weis ich nicht, aber die AD Kurse im CP Menü kann man dafür nicht benutzen.
Man kann diese AD Kurse nur benutzen um schnell mal einen Auffüllkurs an einen Feldarbeitskurs anzuhängen.

**Comment by Christoph1978** [comment]
Ok danke sehr nun hab ich es kapiert. Sry für die lange Leitung und danke für die Hilfe!

**Comment by Tensuko** [comment]
Kein Problem, aber frag dafür lieber mal im AD GitHub nach da kann man dir eher helfen, weil für das was du vor hast must du in CP nur den richtigen Feldkurs laden und die Einstellungen machen wo er starten soll und AD zum Affüllen etc, den Rest muss AD machen, das habe ich aber auch noch nie gemacht, da keine Zeit, desshalb kann ich dir da auch nicht weiter helfen :)
