### ISSUE TITLE
Cp fehler 

### ISSUE THREAD

**Issue by Bandesss** [Courseplay/courseplay#5129]
Hallo zusammen wollte das CP das stroh einsammelt und an AD übergibt.
Hab die aktuellste CP und Ad Version.
Ich stell im CP unload für ad vierter punk ganz unten, sobald der Drescher los fährt kommt Dont Use
Könnt ihr mir sagen mit welcher CP Version das noch geht ?
Aktuellste CP Version,ja
Sorry

[log.txt](https://github.com/Courseplay/courseplay/files/4410920/log.txt)

**Comment by Tensuko** [comment]
Mit der aktuellen ?
CP Fehler als Überschrift und dann so eine Frage, ohne Logfile bringt mal garnix...
#5055

**Comment by Bandesss** [comment]
Sorry hier die Log
[log.txt](https://github.com/Courseplay/courseplay/files/4410980/log.txt)
