### ISSUE TITLE
Feature Request: Percent Complete, Elapsed Time

### ISSUE THREAD

**Issue by realskudd** [Courseplay/courseplay#5131]
When running a route, I know there's the x/y waypoint indicator, but it would also be nice to get a percentage completed and a total time elapsed on the current route. I think it would probably fit on the lower part of the HUD, just like the other indicators.

**Comment by Tensuko** [comment]
There is not enough Space left, if you know what else can be displayed there in other Modes.
A percentage sounds interesting, elapsed time as well, but will have to revisit the HUD and check where to best place those Information. We will have a look but thats on low priority.

**Comment by realskudd** [comment]
How about in the space at the very bottom of the HUD? Right now, all that I've seen that is shown there is the version.

**Comment by Tensuko** [comment]
no space there:
![fsScreen_2020_04_02_19_36_18](https://user-images.githubusercontent.com/27344744/78280406-517cff80-7519-11ea-8ddd-d647e5b208d2.png)

**Comment by realskudd** [comment]
Hm. Okay. I hadn't considered that. What about something just above the vehicle display? I realize it adds a new element, but perhaps that would work.

**Comment by Tensuko** [comment]
Not going to happen, to much to change on HUD.
You can already see the waypoints passed.
