### ISSUE TITLE
Feature Request: Shovel mode thresholds

### ISSUE THREAD

**Issue by realskudd** [Courseplay/courseplay#5132]
In shovel mode, it would be nice to be able to set the drive on/start thresholds like with combi unload mode. This is especially helpful for those times when the scoop decides to not let go of that last grain of whatever, and it still registers as 0%.

**Comment by Tensuko** [comment]
This would be only a workarround.
We will check on the Shovel Mode later when there is time for it, until then, nothing will be done there.
