### ISSUE TITLE
Feature Request: Highlight the Loaded Course in Course Manager

### ISSUE THREAD

**Issue by realskudd** [Courseplay/courseplay#5133]
When running multiple combined routes, it's difficult to know which routes were combined. It would be nice to either have support for a mouseover popup (if that's a thing) on the "_n_ Combined Routes" that lists what each route is, or when viewing the saved routes, highlight the routes that are selected. If the latter is chosen, a placeholder for the current temporary route (if any) should also be in the saved routes list.

**Comment by Tensuko** [comment]
The System doesn't work like that...
Also I don't see a point in it...
When you have some routes combined and saved by name, then open the Course Overview you see where they go, no matter how many courses you loaded.

Tell more more about where you would need such feature, maybe I see the point in it.

**Comment by realskudd** [comment]
![image](https://user-images.githubusercontent.com/4642150/78254521-aab64600-74bb-11ea-86e3-4ce47024d8e5.png)

![image](https://user-images.githubusercontent.com/4642150/78254645-d9ccb780-74bb-11ea-88f2-2544ef252a4d.png)

**Comment by Tensuko** [comment]
Ah okay.
Maybe we could highlight the loaded course in the Course list.

I add this as a Suggestion then.

**Comment by Tensuko** [comment]
Add to collection: #6270
