### ISSUE TITLE
Hat cp mit der Fondladerarbeit ein problem ?

### ISSUE THREAD

**Issue by RudiBergfeld** [Courseplay/courseplay#5134]
Hallo,
hat cp mit der Fondladerarbeit ein Problem ? Irgent Wie bekomme ich das nicht hin. Mit einem Knicklenker nicht und auch mit einen Allradlenker nicht. Der Fahrer hängt sich auf und ich bekomme in der Log immer diesen Lua Error.
[log.txt](https://github.com/Courseplay/courseplay/files/4422403/log.txt)
So hab ich den Curse eingefahren

**Comment by RudiBergfeld** [comment]
Endschudigug so den Knicklenker
![fsScreen_2020_04_02_18_17_14](https://user-images.githubusercontent.com/10323527/78276927-02809b80-7514-11ea-867c-551618f39c77.png)
und so den Allradlenker:
![fsScreen_2020_04_02_18_40_00](https://user-images.githubusercontent.com/10323527/78277091-36f45780-7514-11ea-90dc-79ca0a0db127.png)

**Comment by Tensuko** [comment]
Das gehört da nicht hin, bitte mal die Beschreibung datu auf LSMC lesen:
Error: Failed to open xml file 'C:/Users/rudib/OneDrive/Dokumente/My Games/FarmingSimulator2019/mods/FS19_GlobalCompany_UserIcon/modDesc.xml'.
Load mod: FS19_GlobalCompany_UserIcon (Hash: 4ff6e490232cef8dd48819d02a172e19)
Error: Missing descVersion attribute in mod FS19_GlobalCompany_UserIcon

Schwer zu sagen woher der Error und der CallStack kommt.

Als erstes würde ich aber mal die Karten die du nicht spielst raus nehmen.
Das wäre in dem Fall die Suedhemmern (und andere die ich eventuell nicht gefunden habe), wenn du auf der NF spielst.

Die Kurse sehen für mich erstmal richtig aus, auch wenn etwas eng und ich würde dir empfehlen mit dem Editor den Wartepunkt über den Trailer zu schieben, oder eben den Trailer unter den Wartepunkt zu parken.

**Comment by RudiBergfeld** [comment]
Nein nichts neues  mach zu ich habe den Annimal Kieper in Verdacht das muss ich aber testen
