### ISSUE TITLE
Tool: Courseplay Auto-Updater for FS19

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#5135]
Hi there,

### Update May, 6th, 2020

- now displaying, that it checks version at GitHub to notify user what's going on instead of having a blank window for a couple of seconds.
- now using **FS19_Courseplay.zip** as default filename instead of **FS19_Courseplay6.zip**. _Old_ Filename will still be recognized but when updating to new version the new filename is used by then.

### Update 
Actual version checks here on GitHub for latest release, including pre-releases and displays the version number to you.
It then checks if you have Courseplay installed and if so, which version you got and displays it, too.
If there is a newer version (or you didn't have CP installed) it will get the new release from GitHub and put it into your mod folder.
If it can't download new version your current installed version will be left untouched.
Your current version is renamed to e.g. FS19_Courseplay6.01.00397.bak and will be restored to FS19_Courseplay6.zip if some other error occurs.
When everything has finished fine, as it generally should, the backup will be removed.

I made a gist where I've put this script.
Just download it as Zip, extract it and you'll find the file **FS19_courseplay_update.ps1** which you can run from console (Windows Terminal, Powershell, even from command line (cmd.exe) or by using the Windows Explorer with a right-click and selecting "Run with Powershell" from the context menu.
_Windows does not let you run Powershell scripts with a double click out of the box for security reasons._

You'll find it here: [FS19_courseplay_update.ps1](https://gist.github.com/AndyK70/a51680cc0fe19392ddb2ae8cb0bd1a52)

I hope somebody finds it useful.
### original post
I already had a cmd batch file which automatically updated the CP mod for me, but it relied on two external tools (zip and curl) to be present in the global path environment variable. 
So I took the challenge and walked on new fields, where I've never been before and made this script from scratch in Powershell.
First time ever scripting in that, oh boi what a nightmare.

Nevertheless I figured it out in the end and the script is self contained and does not rely on any other tool or user input _(if I've done everything right and no error occurs)_.

**What it does:**
1. It checks if you have a FS19_Courseplay6.zip in your mod folder and renames this to a backup
2. It downloads the current developer version from this repository
3. It extracts the archive (into the subfolder courseplay-master)
4. It takes the whole content of the folder and builds a new zipfile FS19_Courseplay6.zip directly usable by the game.
5. It outputs the CP version number it has downloaded and installed
6. It removes all the leftovers it created. No temporary files should remain, only the ready to use FS19_Courseplay6.zip

**What happens to my current CP if there's an error while updating?**
* If an error occurs it will tell you what happened, please post this per copy&paste as a comment under the gist as a bug report.
* If an error occurs during downloading your old CP installation remains untouched
* If an error occurs later on your old CP is restored and temporary files are removed.

**Comment by Tensuko** [comment]
Much to complicated.
Nice effort but this is much to complicated, becouse all you got to do is download the relese Version from here:
https://github.com/Courseplay/courseplay/releases
And either rename it to FS19_Courseplay or FS19_Courseplay6 (just as you like) or just copy the .zip file into your mods folder, just remember to delete the old one as it won't get replaced when you don't rename to the same name.

This is something what you should not do:
> and renames this to a backup

**Comment by Merrlin** [comment]
> This is something what you should not do:
> 
> > and renames this to a backup

Automatically backing up the outdated CP Zips is not a problem. At least if they are renamed to something like FS19_Courseplay6.397 (or what ever the version number is) 
For bugfinding it is, at least for me, sometimes a good attempt.
The only way you definitely don't do is to rename the Mod to FS19_CP-backup.zip

Just my 2M Zimbabwe Dollar

**Comment by Tensuko** [comment]
The Problem is that some users will just activate all Mods again and then you have 2 Cp Versions active and that couse a conflict. Not a good Idea, thats why.

**Comment by Bobster82** [comment]
I do like the effort for trying to contribute something ;)
For me personal, I always search this site for something new and download it here, so I dont need a script for it.
I can imagine it would be usefull for some people who can place a shortcut besides the fs19 shortcut, so before playing farming, u do a update check for cp and when a new is here it updates, then play farming... so no need for checking the website.

For backing up the "old" cp file, I would make a map CP_backup and place the "old ones" here or u can make a question in the script if u want to backup and or replace.

If its nothing for u, leave it... some people might find it usefull ;)

**Comment by Tensuko** [comment]
The general Idea isn't bad, but I don't like the Idea of the backup, as I know that this will cause Issues and the unnecessary unpacking and repacking.
Check new Release from Release site, and if it is new, download, rename, replace old and done.
Nothing to say against that :) You can even try to make a Version Selecter that when you want to go back, it downloads an older Version if you rly want to, but never back up any .zip inside you mods folder. Ppl are not able handle this and I get new Issues with several CP .zip files wich all get activated or couse Errors in the log.

**Comment by AndyK70** [comment]
Thanks for your comments.

> Nice effort but this is much to complicated, becouse all you got to do is download the relese Version from here:
https://github.com/Courseplay/courseplay/releases
And either rename it to FS19_Courseplay or FS19_Courseplay6 (just as you like) or just copy the .zip file into your mods folder,

Oh, yeah. alright. I wasn't aware of this. 
Back in the days when I used CP on FS17 there was no ready to use release zip. You always had to download the current branch, unpack the courseplay-master.zip and repack the contents of the unpacked courseplay-master folder. And it always was a tedious task to do so. That's what's my script is doing.
Well I guess with the ready to use releases my script is almost useless. :sweat_smile:

>  but never back up any .zip inside you mods folder. Ppl are not able handle this and I get new Issues with several CP .zip files wich all get activated or couse Errors in the log.

My Script does not create a backup zipfile, but a .bak file. Not recognized by the game and no errors in log, if for some reason the script would fail to clean up or restore the backup.

**Comment by Tensuko** [comment]
Oh ok now I got it with the backup.
Well that would be fine ofc :)

But anyway if you don't want to throw away your work totaly, you could try to change it to check for release Version. I am not sure how GitHub Support this kind of feature, but that would be a good Tool then for many ppl :)

**Comment by AndyK70** [comment]
Thanks 😊

In these days I got a little bit more time (who doesn't?), so I'll check how I can get to the latest pre-release without scraping the websites. When I get there I can change my script to check the version and download the latest version if there was a new one.

**Comment by Merrlin** [comment]
But the first Version (download xyz-master) would be great for AutoUpdate other Mods as well

**Comment by Tensuko** [comment]
AutoDrive got also Release Version.
GuidanceStearing I am not sure about.
ManureSystem also use Release.

In the end the Release Version is more save, as the Branch can also contain unfinished files, like WiP status.

**Comment by Merrlin** [comment]
Yes and no... Some ge the "CP" way, some like Manure do also releases, but not on every commit, just every 10 or so.
And others like VCA provide direct Zips but not in the releases section.
So I would prefer 2 Versions.. one for the releases section and one for the whole repo or for single files from the repo

**Comment by Merrlin** [comment]
Short but dirty workarround for your problem: Use a copy of the zipfile for checking the version.

**Comment by AndyK70** [comment]
and then...? 
After checking the version the copied file remains open and I can't delete it... nope, don't wanna leave temp files in the system, a bad habit

**Comment by AndyK70** [comment]
Got figured it out. Wow what a mess PS is 😅
First the Method Get-Content for the modDesc.xml file was blocking the file, because it read only to the pint where it finds the "version" and keeps the file handle open. I had to force it to read the whole file in order to close the handle. Not very elegant, but ok.
Then the opened installed zip file, which I opened for version checking was held open and there was no .Close method available... Had to dig a little deeper to find the grandparent's class "ZipArchive" has a method .Dispose to release all resources including open file handles. 

At least I got it.
Now the actual script in the gist [FS19_courseplay_update.ps1](https://gist.github.com/AndyK70/a51680cc0fe19392ddb2ae8cb0bd1a52) checks latest release version including pre-release) on GitHub, counter checks the current installed version, informs the user and updates only if necessary. 

I will add in the option to get the current repo (master branch only) and building the zip file from that at a later date. Need a break from powershell scripting. 😅
_PS: I was very close to throw it all away and rewrite it in C# in a proper way._

**Comment by Tensuko** [comment]
That sounds good!
Does it make any difference in capital letters ? like one time courseplay and other time Courseplay ?

**Comment by AndyK70** [comment]
In my post here it was a typo. lol
But you mention a good point though.
Will modify my script tomorrow to ignore upper/lower-case writings.

**Comment by Tensuko** [comment]
Ok thats very cool.
Can you edit your 1st post for the updated Version and give the actual information ? I will pin this Issue then :)

**Comment by AndyK70** [comment]
Done.
Do you want me to name the zip without the 6 (FS19_Courseplay.zip)?
It was m habit from Courseplay4 for FS15, CP5 for FS17 and now FS19 CP6... But if you want it without the 6 I will edit it. It's not a big deal.

**Comment by Tensuko** [comment]
Nah that is not a big deal if the 6 is there or not :)

**Comment by Tensuko** [comment]
You might need to update the updater for newest filename :)

**Comment by AndyK70** [comment]
@Tensuko thx, for notifying. 
Launched the script a few seconds ago and it is still working properly.

Still made a new version with a little change and addition:

- now displaying, that it checks version at GitHub to notify user what's going on instead of having a blank window for a couple of seconds.
- now using **FS19_Courseplay.zip** as default filename instead of **FS19_Courseplay6.zip**. _Old_ Filename will still be recognized but when updating to new version the new filename is used by then.
-
