### ISSUE TITLE
Beet Harvest Issue

### ISSUE THREAD

**Issue by Bovrinox** [Courseplay/courseplay#5136]
Hi folks
Love this mod, its far better than i could of imagined, top work!

Unfortunately i have encountered a rather annoying problem while trying to harvest sugar beet. I am using the topper and harvester attached to a tractor which i am driving myself, and 2  AI controlledtractors leading beets to the sell point. However, whenever the harvester reaches the fill level required to summon the trailer, the tractor stops responding to any input, the camera stops moving and the tractor just drives off screen until i switch vehicle.

Any help finding what i am doing wrong would be appreciated!

**Comment by Tensuko** [comment]
That is becouse Mode2 (your 2 Drivers) is under rework.
See #3311 and #4286 for Details.
