### ISSUE TITLE
LUA call stack:   vehicles.lua (35) : link und andere

### ISSUE THREAD

**Issue by BrunoMoser13** [Courseplay/courseplay#5138]
Ich bekomme auf der Hofbergmann 1.0.0.6 immer die LUA call stack .... und noch andere. Siehe logfile. Woran kann das liegen?
[log.txt](https://github.com/Courseplay/courseplay/files/4431498/log.txt)

**Comment by Tensuko** [comment]
Hast du einen Platformtrailer irgendwo angehangen ?
Da kommt ein Callstack, der macht aber nichts.
Hast du denn Probleme auf der Map ?

Es könnte auch daran liegen das du zu viele Maps im Mods Ordner hast.
Gerade Maps die verschiedene Scripte benutzen.
Spontan sehe ich heir auf einem Haufen:
FS_19Kandelin
HINTERKAIFECK
FS19_WestbridgeHills
HolzerMapLS19
...

Immer nur eine Map im Mods Ordner!

**Comment by BrunoMoser13** [comment]
Ich habe den Fliegl DPW180 Ballenanhänger aus dem Autoloadpack.....

Okay - dann werde ich die anderen maps einmal rausschmeissen...

**Comment by Tensuko** [comment]
Das wird er sein, der Ballenanhänger mit AutoLoad.

**Comment by BrunoMoser13** [comment]
Den brauche ich aber - was für alternativen gibt es denn ? Welchen Fehler hat denn der Ballenanhänger?

Habe das Spiel jetzt noch mal ohne die ganzen maps im modordner gestartet. Die Log ist anbei....
[log_ohne andere maps im mod ordner.txt](https://github.com/Courseplay/courseplay/files/4431794/log_ohne.andere.maps.im.mod.ordner.txt)

**Comment by Tensuko** [comment]
Glaub Trailer mit EasyAutoLoad sind problemlos.
Aber gibt es denn ein Problem ?
Hängt das spiel, geht etwas nicht, oder was passiert ?
Wenn nichts los ist, lass es so. Wie gesagt, die Callstacks können auch von Platformwagen von GIANTS kommen, ich weis halt nicht was für ein Callstack das ist, ob es der von den Plaformwagen ist oder jetzt speziell mit AutoLoad.

**Comment by BrunoMoser13** [comment]
Ich habe das Spiel ohne andere maps und ohne das Autoloadpack gestartet - die Log ist fast ident. D.h. die LUA Call stacks sind identisch .... es liegt also nicht am autoload .....
Das Spiel hängt nicht. Ab und zu ruckelt es und damit kann ich ja leben. 
Ich wollte eigentlich nur wissen was die call stacks bedeuten und wer diese verursacht.

**Comment by Tensuko** [comment]
Also die einzigen Callstacks von denen ich weis die durch CP Verursacht werden sind, wenn man einmal einen Wagen mit einer Platform ankuppelt (einmal pro Session) oder angekuppelt lässt und das Savegame lädt (also auch wieder eine Session).
Bisher hatten diese Callstacks keine Auswirkung.

**Comment by BrunoMoser13** [comment]
Ich werde das ganze einmal mit einer anderen map versuchen....

Danke für die raschen Rückmeldungen.

**Comment by Tensuko** [comment]
Ich mach hier zu wegen inaktivität...
