### ISSUE TITLE
Mode 6 Gruber senkt zu früh ab

### ISSUE THREAD

**Issue by John-Deere89** [Courseplay/courseplay#5140]
Hallo,
ist was falsches eingestellt oder warum fährt CP so komisch bei mir? Wie man sieht senkt er zu früh ab und Rückelt (Bremst & Beschleunigt) beim wenden.
Mod Gruber:
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=146161&title=fs2019
Video:
https://drive.google.com/file/d/1JiUdQe0p2eNusEgq7XkjlILEqEHhCrFy/view?usp=sharing
Log:
[log.txt](https://github.com/Courseplay/courseplay/files/4432277/log.txt)

**Comment by Tensuko** [comment]
log mit channel 7 12 und 14

**Comment by John-Deere89** [comment]
was meinst du? channel?

**Comment by Tensuko** [comment]
Debugchannel.
Im CP HUD bei Settings die Zahlen da unten anklicken so das sie grün werden.
7 12 und 14.
Dann lässt du den Traktor den Pfad abfahren (am besten auch wieder mit Video) und das logfile was dann entsteht hängst du an.

**Comment by John-Deere89** [comment]
Bitte
[log.txt](https://github.com/Courseplay/courseplay/files/4434341/log.txt)

**Comment by John-Deere89** [comment]
Is die Einstellung bei mit falsch oder kommt das von CP?

**Comment by Tensuko** [comment]
Kann ich noch nichts zu sagen.
Klar kann man mit den Einstellungen unter Andvanced Settings mal ein bisschen rumprobieren Pathfindturn, AI Turn etc.

**Comment by John-Deere89** [comment]
sry davon habe ich keine ahnung

**Comment by pvaiko** [comment]
Du kannst noch mit dem 'Tool absenken' Einstellung (früh/spät) rumspielen. Passiert das mit anderen Tools auch oder nur dieser hier?

**Comment by pvaiko** [comment]
(this is due to the very narrow angle between the headland and up down rows, while finishing the turn, the back of the work area is closer to the turn end than the front. The code should check for this condition and don't use the back distance if it is smaller than the front) 

Will work better with 'early' setting.
