### ISSUE TITLE
crash on (a nil value) with most maps 

### ISSUE THREAD

**Issue by sirbum69** [Courseplay/courseplay#5142]
seems i am not able to create a new game or play an existing save with courseplay as i keep getting this error and that is where it hangs. soon as i remove courseplay i am able to load up maps just fine. the error i get is this..

2020-04-05 14:53 Documents/My Games/FarmingSimulator2019/mods/FS_19Courseplay/course_management.lua:1723: attempt to call method 'GetAvailableDestinations' (a nil value)

i deleted out part of the path that showed my name. but this is what i get everytime

this is on lone oak which i have played many times with courseplay as well as pleasent valley industries. also doesnt matter if i pull all mods out exccept for just courseplay

**Comment by Tensuko** [comment]
Old AD Version, get newest from AD github.
Next time add your complete logfile...

**Comment by sirbum69** [comment]
actully the new autodrive version also causes the same issue. Because when I downloaded it, the name of the file is still AutoDrive

I figured out that I needed to rename that to Autodrive. Then everything worked just fine.

 

But thank you for looking into it. And yes I will add the whole log file next time.

**Comment by Tensuko** [comment]
My AD is named like this FS19_AutoDrive and I have no Crash at all....

**Comment by sirbum69** [comment]
sounds good. soon as i renamed mine to lower case d in drive i no longer got the crash. which i had read somewhere on forum boards was causing the issue. appreciate you looking into this though.
