### ISSUE TITLE
Error Running LUA method mouseEvent

### ISSUE THREAD

**Issue by KailJaxxon** [Courseplay/courseplay#5143]
I am having a problem with the AI getting stuck when fieldwork Course is used. This the error in my log file.

CourseGeneratorScreen:onCreate()
Error: Running LUA method 'mouseEvent'.
C:/Users/QCGemWorks/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00394/FieldworkAIDriver.lua:252: attempt to index field 'fieldworkCourse' (a nil value)
Warning (script): 'streamWriteUIntN': Argument 1 has wrong type. Expected: UInt. Actual: Nil 
..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (882): expectedType == Value::VoidType || expectedType == Value::ClassType
LUA call stack:
dataS/scripts/vehicles/specializations/events/AIVehicleSetStartedEvent.lua (70) : streamWriteUIntN
dataS/scripts/network/Connection.lua (88) : writeStream
dataS/scripts/vehicles/specializations/AIVehicle.lua (642) : sendEvent
=C:/Users/QCGemWorks/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00394/base.lua (1849) : superFunc
dataS/scripts/vehicles/specializations/AIVehicle.lua (1072) : stopAIVehicle
dataS/scripts/input/InputEvent.lua (100) : callback
dataS/scripts/input/InputBinding.lua (3202) : notifyInput
dataS/scripts/input/InputBinding.lua (2924) : updateInput
dataS/scripts/main.lua (1871) : update
Warning (script): 'setTranslation': Argument 1 has wrong type. Expected: Int. Actual: Nil 
..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (882): expectedType == Value::VoidType || expectedType == Value::ClassType
LUA call stack:
dataS/scripts/vehicles/specializations/AIVehicle.lua (702) : setTranslation
=C:/Users/QCGemWorks/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00394/base.lua (1849) : superFunc
dataS/scripts/vehicles/specializations/AIVehicle.lua (1072) : stopAIVehicle
dataS/scripts/input/InputEvent.lua (100) : callback
dataS/scripts/input/InputBinding.lua (3202) : notifyInput
dataS/scripts/input/InputBinding.lua (2924) : updateInput
dataS/scripts/main.lua (1871) : update

**Comment by Tensuko** [comment]
Full logfile and mroe details what tool and what you wanted to do.
Also I read this: Courseplay_6_01_00394
And this is not our newest Version:
https://github.com/Courseplay/courseplay/releases

**Comment by KailJaxxon** [comment]
I rolled it back to the 394 version when I was having problems. Will put the 397 back in and see what happens. So sorry about that. If the problem still persists I will send the entire log to you. Thanks for the prompt response. I love CP. LOL

________________________________

**Comment by KailJaxxon** [comment]
Here is the entire log file.



________________________________

**Comment by Tensuko** [comment]
Can you just drag and drop the log.txt into the comment box so I can read it with a proper tool (Notepad++)

**Comment by NexX0** [comment]
This is a Problem with the [Slurry System](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=155807&title=fs2019) Mod, as soon as i removed that mod it worked just fine

**Comment by KailJaxxon** [comment]
I do not use the slurry system mod actually.

**Comment by Tensuko** [comment]
Load mod: Courseplay_6_01_00394 (Version: 6.01.00394) (Hash: 0c2cd90d27d18b9efcb602c3238deaf6)
Load mod: Courseplay_6_01_00397 (Version: 6.01.00397) (Hash: 757edde1e05a73e48a5632f2b5e12325)
Thats why I tell ppl to only rename your .zip to FS19_Courseplay when you downloaded it so you will replace the old version.
