### ISSUE TITLE
GamePad bindings not working

### ISSUE THREAD

**Issue by o-xy-o** [Courseplay/courseplay#5145]
Hi, I can't get the gamepad bindings to work. 
I am using a Xbox360 GamePad and want to start/stop the course with LB+RB+DP-UP. So I set the CP Modifier to LB+RB and the function to DP-UP, but it is not working.

**Comment by Tensuko** [comment]
There is a problem with keybind we know it but dont have anyone to work on it right now.

**Comment by Tensuko** [comment]
The Keybinds should be able to set freely.
