### ISSUE TITLE
Enable crop destruction (adv settings?)

### ISSUE THREAD

**Issue by Squiffz** [Courseplay/courseplay#5146]
Is there a way for me to enable crop destruction when using Courseplay as it would be really useful for making tramlines?

**Comment by Tankieboy** [comment]
I would like this also.

**Comment by SirAlbertL** [comment]
Exactly what I was going to ask. Thinking of trying to make crop destruction active or disabled like fertilizer use,  beacons, or stop at trigger point extra.

**Comment by Tensuko** [comment]
#5541
