### ISSUE TITLE
MP issue with stopping driver

### ISSUE THREAD

**Issue by p0wderkeg** [Courseplay/courseplay#5150]
After driver has finished the course or during the course pressing stop driver you do not have access to drive vehicle.  you can exit vehicle and driver (worker) is still in vehicle.  Its like it just stops them from driving.  Even removing course from vehicle its the same.  This is a new issue im having after updating to 397.  was using 391 before and all was working.

**Comment by p0wderkeg** [comment]
The only way to get back to being able to drive vehicle is to exit game and enter back in, no need to stop the dedicated server, just your game.

**Comment by Justice-Molton** [comment]
if you use AutoDrive as well, try to hit the Start button two times. This is what works for us, but it is really boring. A fix for that issue would be cool, as we steped some CP versions back, where this not happens. 
I can send a log soon. Need to update the server with the new Version of CP.

**Comment by Justice-Molton** [comment]
@Tensuko here you have my client and the Server Log

[log.txt](https://github.com/Courseplay/courseplay/files/4455452/log.txt)
[log.txt](https://github.com/Courseplay/courseplay/files/4455456/log.txt)

**Comment by falconluan** [comment]
I've encountered this issue too. We are not using a dedicated server, instead, let's say A is hosting the game, B joins A's game. B enabled the courseplay to do some field work. After the work was finished, B can stop the courseplay, but he can't drive the vehicle and he can see the AI driver still sits in the vehicle. The workaround we are using is let the host, in this case A, to jump in and start another courseplay course and stop it immediately. After that, B can regain the control of the vehicle.

**Comment by CHaWoLS** [comment]
What works for me is hitting "H" for stopping the helper - seems as there's a helper active in Background...
Meaning: if CP finished work I stop CP, hit "H" and can go on as usual...

**Comment by MicaelJarniac** [comment]
Happened to me too. Seems to be the same as #5087.
