### ISSUE TITLE
Filling a silo from another silo

### ISSUE THREAD

**Issue by wilsontray** [Courseplay/courseplay#5151]
Is there a way to buy say seed from a silo or a shop or whatever and have it automatically loop to your silo dump the product into your silo then loop back and purchase another load ... rinse and repeat till the silo is full?

**Comment by Tensuko** [comment]
Sure there is... Just use Mode1 like any fruit transportation work. Did you try it ?

**Comment by wilsontray** [comment]
It sort of works... 2 issues with it, 1 I cant get it to go until the silo is full, I can however set a number of runs to do.... which I can work with but not optimal

2nd issue is the breaking one for me.... I set its start point at the load spot, and it fills up just fine, but then at the offload point I set an unload point and it does start to unload.... however it only unloads like 1% of the cargo then starts going again.... in fact thinking about it I am not sure it even stops it just slows down starts unloading and keeps going... so when it leaves the unload area it stops unloading.

**Comment by wilsontray** [comment]
I admit I am new to this so I very well am making a dumb mistake somewhere, but you have to learn somehow... and that means making those dumb mistakes :)

**Comment by Tensuko** [comment]
Where ever you got the information from, that you have to set an unload point at a trigger (in this case a silo) is 100% wrong and you should not listen to him anymore....
I got those kind of Issues a lot.
How does Mode1 work:
You can start to Record the course, when the last Trailer is under the Pipe/in the Trigger, then just drive the course untill you hit all positions where you want to unload. Do NOT place any unlaod or waitpoints at the stations!!! Then, when return back to your loading station, Stop the Record before you reach the Pipe/Trigger. Why ? Becouse CP looks between stop and start for a Trigger to load from. If there is nothing found, it will wait at the Start Waypoint untill filled up manualy.
Note: When start record, make sure there is a straight line for the 2nd and maybe 3rd waypoint, else the Tractor could drive off without load.

**Comment by wilsontray** [comment]
That worked perfectly, Thanks!

Out of curiosity, when do you use the unload, wait, or crossing triggers?  I always assumed wait was for waiting for some user input or action since it seems to wait for me to do something, unload obviously I misunderstood :) and crossing I use when it crosses other paths

**Comment by Tensuko** [comment]
Wait is used in mode 8 for overload to a fieldcontainer and mode9 and mode10 to define areas and tip points.
Unload is to unload at this position (like press ctrl+i).
Crossing is to complicated to type on phone :D check yt tutorials for this.
