### ISSUE TITLE
The mod doesnt show in the mod menu

### ISSUE THREAD

**Issue by player12234** [Courseplay/courseplay#5153]
i downloaded the mod unpacked it and go into the subfolder and selected all files and create a file the Name was : FS19_courseplay.zip i put the file in the mod Folder and deleted the other files. after that i go into the game and want aply the mod into the safegame but it doesnt Show me the mod

**Comment by Tensuko** [comment]
Or just download the finished .zip file from here:
https://github.com/Courseplay/courseplay/releases
no unzipping needed.
Pro Tip rename it to FS19_Courseplay (always) so you will existing files in case of an update.
Also a nice addition: Auto Updater, wich requiers the CP mod in mods folder ofc but for easier update maybe: #5135

**Comment by Tensuko** [comment]
Else, attatch your log.txt

**Comment by player12234** [comment]
the first link?

**Comment by player12234** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4455415/log.txt)

**Comment by Tensuko** [comment]
Error: Invalid mod name 'FS 19_courseplay'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
You got a space between FS and 19....
Anyway, the link shows all CP release, open Assets and download the .zip, and as I said, should only rename to FS19_Courseplay so always easy replace the old one.
Once you got one CP zip File in it, you can also try out the new AutoUpdater found in #5135 

Closing this as this is not a real Issue.
