### ISSUE TITLE
Speed question...

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#5154]
I maybe worng' i usually am but if i record a course with a 'slow' tractor i thought that if i then put  'faster' tractor on the same course the faster tracor would run at its maximin speed not the recorded max speed. 
With this version a 65KPH Fendt will only do 53KPH on a course recorded by a 'slower' tractor.

Im using V397.

**Comment by Tensuko** [comment]
Just change from recorded speed (lower option) so you can set your max used speed.
This should solve your Issue. Else you can use the CP Editor and adjust the Speed of every waypoint with it (check your keybinds, you might have to reassign the keys for it)
![fsScreen_2020_04_08_18_41_42](https://user-images.githubusercontent.com/27344744/78810513-c09a9e00-79c8-11ea-846b-860223db9527.png)

**Comment by kwguk** [comment]
Yeah thanks
The problem with running at max spped is the tractor doesnt slow down enough before corners and ends up sliding off th eroad and usually getting stuck trying to recover.
I guess easiest solution is to record course with fast tractor.

**Comment by Tensuko** [comment]
That might be easier :)
