### ISSUE TITLE
Error: Running LUA method 'mouseEvent'. - triggers.lua:461: attempt to index field 'storages' (a nil value)

### ISSUE THREAD

**Issue by MircoGT** [Courseplay/courseplay#5157]
Abend, sobald man das Heizkraftwerk platziert wirft Courseplay 2 Fehler und man kann nichts mehr machen im Spiel außer speichern und neustarten. Der Fehler tritt nicht bei dem StrawHarvest DLC auf sondern nur bei dem Bonusgebäude und dabei ist es egal welcher Modus.

In the evening, as soon as you place the pelletHeatPlant, Courseplay throws 2 errors and you can do nothing in the game except save and restart. The error does not occur with the StrawHarvest DLC but only with the bonus building and it does not matter which mode.

Standard Map and Hinterkaifeck
Mods:
CP Version: 6.01.00397
StrawHarvest Version 1.0
pelletHeatPlant

Error: Running LUA method 'mouseEvent'.
...../LS19_CoursePlay6/triggers.lua:461: attempt to index field 'storages' (a nil value)

[log.txt](https://github.com/Courseplay/courseplay/files/4452845/log.txt)

![787860_20200408225513_1](https://user-images.githubusercontent.com/63373394/78833707-9c04ed00-79ed-11ea-99ea-3c975834bd2d.png)

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/releases
398 testen bitte.

**Comment by Tensuko** [comment]
Ich habe das eben Platziert, kein Fehler...

**Comment by Tensuko** [comment]
Ok wenn man einen CP Fahrer startet kommt der Error...

**Comment by Tensuko** [comment]
Platziertes HKW + CP Driver start:
2020-04-09 08:27 Error: Running LUA method 'mouseEvent'.
2020-04-09 08:27 I:/Dokumente/My Games/FarmingSimulator2019/mods/FS19_Courseplay/triggers.lua:461: attempt to index field 'storages' (a nil value)

**Comment by Tensuko** [comment]
Ist wohl ein Fehler vom HKW Trigger... Bitte abwarten.

**Comment by MircoGT** [comment]
braucht ihr noch mehr Infos?

hab den Link zu dem Thema an CM weitergeleitet via Discord

**Comment by Tensuko** [comment]
Ich bin schon lange mit CM in Kontakt via Discord :)

**Comment by MircoGT** [comment]
Problem ist durch Creativ Mesh behoben, Update des HKW gibts auf der CM Seite

**Comment by Tensuko** [comment]
Was meinst du wer das zusammen mit CM getestet hat ? ^^
So zu jetzt hier...

**Comment by cassaro** [comment]
wo finde ich den download des HKW ubdates bin irgendwie zu doof

**Comment by Tensuko** [comment]
Im Grunde an der gleichen Stelle und ja es ist auch die Version 1.0 vom HKW, die Jungs haben die Version nicht hoch gezählt... einfach noch einmal runterladen

**Comment by cassaro** [comment]
habe die uber mod hub runteregeladen also da nochmal die selbe runterladen?

**Comment by Tensuko** [comment]
Also das HKW hast du bestimmt nicht im ModHub geladen...

**Comment by cassaro** [comment]
stehe garede etwas auf dem schlauch kanst mir den link schicken

**Comment by Tensuko** [comment]
Creative Mesh, Easteregg, Heizkraftwerk/Pelletkraftwerk. Und als Tip: Barcode auf den Pellettepaletten.
Mehr Info gibts nicht ;) Ist ja schließlich ein Easteregg..

**Comment by cassaro** [comment]
ok danke
