### ISSUE TITLE
CP/Game "Crashes" LUA Error  " Error: Running LUA method 'update' "

### ISSUE THREAD

**Issue by NexX0** [Courseplay/courseplay#5158]
Hey there,
so i prepared this [Video](https://youtu.be/Ct5uhXqvMtM) to best describe whats happening.
it is really weird tho because it only happens with "new" courses, with "older" courses for Harvesting or other stuff it didn't happen but since id say 1st of April if i generate any course on the Field this happens.
I normally don't save Field Courses but with Cornbelt being a x16 Map any fieldwork takes very long so i save them until the work is finished.

I will test Without any Mods but Courseplay (6.01.00398)
[log.txt](https://github.com/Courseplay/courseplay/files/4453684/log.txt)

**Comment by Tensuko** [comment]
I already saw 2 other Maps in your logfile.
Only one map in Mods Folder allowed.

The Error must come from something else what you attatched:
2020-04-09 04:13 Error: Running LUA method 'mouseEvent'.
2020-04-09 04:13 dataS/scripts/vehicles/specializations/Attachable.lua(1318) : attempt to index field 'attacherVehicle' (a nil value)
This is GIANTS Path.
And I think that Tool/Vehicle then couse to the CP Error:
2020-04-09 04:13 Error: Running LUA method 'update'.
2020-04-09 04:13 Mods/FS19_Courseplay/TrafficCollision.lua:281: attempt to index field 'trafficCollisionTriggers' (a nil value)

This is not all Callstack!

**Comment by NexX0** [comment]
okay i tracked it down to the [Tow Bar](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=156390&title=fs2019) Mod after removing that the game runs just fine.
