### ISSUE TITLE
Problem to load the mod

### ISSUE THREAD

**Issue by player12234** [Courseplay/courseplay#5159]
Here is the log 
[log.txt](https://github.com/Courseplay/courseplay/files/4455876/log.txt)
there is an error but i dont know why

**Comment by Tensuko** [comment]
oh I see the Problem now...
Farming Simulator 19
  Version: 1.2.0.1 b3269

oh und da du in deutsch spielst schreibe ich auch mal auf deutsch :)
Du solltest dein Spiel mal patchen. Entweder auf der FS19 Webseite oder über Steam je nachdem wie du das Spiel installiert hast.

**Comment by player12234** [comment]
Achso ok danke für die Information
