### ISSUE TITLE
Giants DLC Horsch Maestro SW 16.75 turn Problems

### ISSUE THREAD

**Issue by Agrargorn** [Courseplay/courseplay#5160]
Somehow my tractors don't manage to turn with that thing on the field, the driver either tries to move backwards and it looks like he doesn't know, that the machine is towed, so he gets stuck in the machine or he tries to drive backwards in small steps with the procedure of: turning a bit left, stop, turn a bit right, stop, rinse and repeat, so it takes him ages

[log.txt](https://github.com/Courseplay/courseplay/files/4457047/log.txt)

**Comment by Tensuko** [comment]
Throw this out pls:
Error: Invalid mod name 'courseplay-master'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

Also a logfile with channel 12 and 14 active and a screenshot of the turn situation will all waypoints active (CP HUD Settings the 3 Dots on)

**Comment by Agrargorn** [comment]
Will Do, but first, what exactly is Channel 12 and 14?

**Comment by Tensuko** [comment]
In CP HUD Settings Page the Numbers down there must be green to be on.
Then let the driver run the course and post that logfile like you did in the 1st post.

**Comment by Agrargorn** [comment]
ah ok got it, there you go:


![20200409184641_1](https://user-images.githubusercontent.com/62554598/78919992-0a4fbb00-7a93-11ea-9287-89032dee3c14.jpg)
![20200409184854_1](https://user-images.githubusercontent.com/62554598/78919993-0c197e80-7a93-11ea-9d66-cb33c76acfca.jpg)
![20200409184857_1](https://user-images.githubusercontent.com/62554598/78919997-0cb21500-7a93-11ea-8719-faa8f2b7cc4b.jpg)
![20200409184900_1](https://user-images.githubusercontent.com/62554598/78919999-0d4aab80-7a93-11ea-876f-80670529768c.jpg)



[log.txt](https://github.com/Courseplay/courseplay/files/4457526/log.txt)

**Comment by Agrargorn** [comment]
The Same result with the 1050 Fendt Tractor, so I guess its with every tractor.

**Comment by Tensuko** [comment]
hmm yea I think I know what that is.
Same as for some other turns I had, he got not enough straight lines to get the tool straight enough to push it back.

@pvaiko thats a bit similar to the problem I tried to tell you that one day... at least part of...

**Comment by Agrargorn** [comment]
I hope I could help a bit

**Comment by Tensuko** [comment]
This is a very strange bug.... it does work on other Fields like Field 21....

**Comment by Tensuko** [comment]
![fsScreen_2020_04_09_19_23_31](https://user-images.githubusercontent.com/27344744/78923936-42f29300-7a99-11ea-8a21-7ef4d0276478.png)
![fsScreen_2020_04_09_19_24_10](https://user-images.githubusercontent.com/27344744/78923945-46861a00-7a99-11ea-9c61-8d92a04cc12c.png)

Turn looks different here, still not able to push it back, wich is strange...
![fsScreen_2020_04_09_19_25_55](https://user-images.githubusercontent.com/27344744/78923963-50a81880-7a99-11ea-944b-212bc447912b.png)
![fsScreen_2020_04_09_19_26_02](https://user-images.githubusercontent.com/27344744/78924010-661d4280-7a99-11ea-8ad6-9d303a09100f.png)
[logTurn.txt](https://github.com/Courseplay/courseplay/files/4457763/logTurn.txt)

**Comment by archaoncze** [comment]
I had similar problem with several implements - i usually solve this by turn off turn on filed. Bud my personal gues where is problem is, that it always happen when i use towed tool, which is connected by 2 or 3 point adapter (as for example greatplains universal seeder/planter 18m - if you choose option with tow bar extension  CP is unable to reverse with it, if you remove it, its then ok) I am not sure if i described it correctly, so i put screenshot of  that machine part. It then seems like CP try perform turn like if you have connected mounted machine.
![xy](https://user-images.githubusercontent.com/60066992/79069495-fdb7a680-7cce-11ea-8755-c97c7127a63a.png)

**Comment by Agrargorn** [comment]
Yes, its my guess too with the towed/mounted machine differentiation. But its funny with the horsch maestro doesn't have this attachment, its just like a trailer attachment

**Comment by Tensuko** [comment]
I know what you mean, bu this one is a simple towed tool and others works all fine.
Just this one not (so far...).
