### ISSUE TITLE
Self Unload sometimes works, sometimes not

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#5161]
I activated the "self unload" option for my combine:
![image](https://user-images.githubusercontent.com/11199752/78930593-c0f37180-7a7a-11ea-9cfd-fb802438faf2.png)
Depending on the position in which I leave the trailer to receive the harvester unload, sometimes the harvester is positioned correctly, sometimes not:
![image](https://user-images.githubusercontent.com/11199752/78930796-12036580-7a7b-11ea-830a-89f3ab1cba7c.png)

How to solve this inconstancy?

**Comment by Tensuko** [comment]
Is that a Mod Trailer or Vanilla one ?

**Comment by rogeriodec** [comment]
No, it's Trans-SPACE 8000:
![image](https://user-images.githubusercontent.com/11199752/78962303-536f3180-7aca-11ea-8146-95e3343970a9.png)

**Comment by Grumpykitten710** [comment]
I found if you put it across the courseplay tracks it works the best, but also I found if it too far away it wont pick it up

**Comment by NicholasSoares** [comment]
Here sometimes it unload and reset its position to the begin of the course instead of returning to its original position on the course, happens most of the times when it is on the last turn of the course path.

**Comment by Agrargorn** [comment]
> 
> 
> I found if you put it across the courseplay tracks it works the best, but also I found if it too far away it wont pick it up

really? my fps just get crushed by the cpu and the combine either doesn't generate a route at all or does funny stuff, but if I place the container alongside the field, its allright, only problem is the harvester tends to start at waypoint 1 again, so I have to look after him

**Comment by Tensuko** [comment]
Your CPU isn't doing (almost) anything when generating a course.
This is to limited space for LUA or how that msg was, in other words, poor Engine.
When you have a 2nd Monitor, just set up task manager and let combine generate a course, your FPS will go down but your CPU usage stays low...

**Comment by Tensuko** [comment]
@NicholasSoares 
yes I had that bug too and got to record the needed Data (I hope).
Will check on that if there is time for it.
The Pathfinder (used for SelfUnload) is not perfect yet, we know it.

**Comment by Agrargorn** [comment]
oh, something new learned, I always thought this is a CPU heavy task

**Comment by rohne83** [comment]
I think the issues mainly occur when the pipes are rather short (old combines like the Bizon, or mods for Fortschritt combines). Then very often the combine will park too far away from the trailer to be able to unload.
When using newer combines with long pipes instead it works much better.

**Comment by Tensuko** [comment]
Interesting!
Thanks for your feedback, right now there is a smal Issue with Pathfinder that we are aware of.
Maybe we can adjust this in the same time, but will have to see.

**Comment by Tensuko** [comment]
continue here #6392
