### ISSUE TITLE
How to exclude some objects from field boundaries

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#5162]
I expanded my field, but in the middle, there is a house:

![image](https://user-images.githubusercontent.com/11199752/78962645-21120400-7acb-11ea-981c-1b1932694513.png)

When recalculating the borders, I would like to exclude this house (like an island) within the field, thus preventing the equipment from colliding with this house.
How to do this?

I tried this approach:
![image](https://user-images.githubusercontent.com/11199752/78963245-4b64c100-7acd-11ea-9e57-c990ec428506.png)

Is this the correct way?

**Comment by Tensuko** [comment]
Yes, it is.
What I would do now is use CP to scan Fieldborder (blue lines appear) and save it to the same number so i dont mix things up.

**Comment by rogeriodec** [comment]
Perfect. Thanks!
