### ISSUE TITLE
Dritter CP Fahrer macht unsinn

### ISSUE THREAD

**Issue by C43AMG** [Courseplay/courseplay#5163]
Morgen, 

ich schreibe das mal auf Deutsch, weil es auf Englisch wahrscheinlich noch komischer klingt..

Ich war auf der NF Marsch alles gut alles schön, nächster Tag nicht geändert an den Settings, ich schicke 3 Schlepper los zum säen, 1er links (alles klar fährt zum Start fängt an) 2er mitte ( auch alles gut) dritter ( fährt nicht zum Startpunkt sondern einfach zu irgendeiner Feldreihe und fängt irgendwo an... Drescher danach genau das selbe Spiel...

Das komische ist das die Anzahl der Waypoints dieselbe ist und die Zeit auch die selbe wie bei den anderen Beiden :/

**Comment by C43AMG** [comment]
Jetzt ist es auch so bei 2 CP Fahrern mit dem selben Kurs, links fährt normal zum Start und startet und rechts knallt mitten ins Feld und fängt einfach so irgendwo an

**Comment by Tensuko** [comment]
Trotzdem hast du weder log noch screenshots gepostet...
#5055

**Comment by C43AMG** [comment]
@Tensuko wo finde ich die Logs?

Und von welcher Situation genau brauchst du einen Screenshot? Wenn er mitten ins Feld ballert?

**Comment by Tensuko** [comment]
Log ist unter My Games\FarmingSimulator2019\
Screenshots vom Kurs und was der Fahrer macht, also an welcher Ecke das passiert.

**Comment by C43AMG** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4461038/log.txt)


My logs firstly @Tensuko

**Comment by Tensuko** [comment]
Fahren zufällig die JD 6M deinen Kurs ab ?
2020-04-10 10:50   Error (data/vehicles/johnDeere/series6M/series6M.xml): Failed to update suspension node 201299. Node does not exist anymore!

**Comment by C43AMG** [comment]
![cp111](https://user-images.githubusercontent.com/53007304/78995687-3e82b480-7b43-11ea-9211-2d46ea47fc9e.PNG)
![cp222](https://user-images.githubusercontent.com/53007304/78995689-40e50e80-7b43-11ea-95eb-b090d351ae86.PNG)
![cp333](https://user-images.githubusercontent.com/53007304/78995692-42aed200-7b43-11ea-86f8-57ff7366dada.PNG)
![cp444](https://user-images.githubusercontent.com/53007304/78995696-44789580-7b43-11ea-880a-fe9aeba99c8c.PNG)
![cp555](https://user-images.githubusercontent.com/53007304/78995703-46425900-7b43-11ea-8078-1c339d1c47d2.PNG)

**Comment by C43AMG** [comment]
Habs mit mehreren Schleppern und Dreschern probiert, bei mir buggt das Gespann total, der letzte Fahrer, zweiter, dritter, vierter etc macht dann das wie die Bilderstrecke egal welches Fahrzeug, egal welche Map, egal welcher Kurs, egal welche Aufgabe :o

**Comment by Tensuko** [comment]
Start an der Ecke ist nicht so toll.
Der rest liegt am multitool setup. Der innere Kurs ist kürzer... Müssen wir schauen...

**Comment by C43AMG** [comment]
> Start an der Ecke ist nicht so toll.
> Der rest liegt am multitool setup. Der innere Kurs ist kürzer... Müssen wir schauen...

@Tensuko Ahh okay, danke für euer Engagement <3

**Comment by Tensuko** [comment]
Convoy sollte mit der neuesten Version gefixt sein.
