### ISSUE TITLE
Krone BigPack StrohbergungAddon Helfer lässt sich nicht entlassen nach Überführung

### ISSUE THREAD

**Issue by spiessphilipp** [Courseplay/courseplay#5165]
Ich habe einen Traktor mit der neuen Ballenpresse KRONE BiGPack 1290 HDP II  aus dem Strohbergung Addon und dem BaleCollect 1230 an der Presse vom Händler zum Hof überführen lassen. Hat alles geklappt nur kann ich den Helfer nicht mehr entlassen. Es geht wenn ich das Spiel neustarte. Immer wenn man auf "Helfer entlassen" klickt gibt es einen Fehler in der log.txt im Anhang ist diese. Ich hoffe der Fehler wird schnell behoben.
[log.txt](https://github.com/Courseplay/courseplay/files/4463555/log.txt)

**Comment by Tensuko** [comment]
Hast du die Krone BiGPack mit automatisch oder manuell befüllen gekauft ?

**Comment by 3lronMcBong** [comment]
Moinsen,

habe auch so einen Fehler.
Wollte Quaderballen machen, mit AD zum Feld fahren lassen danach sollte CP auf dem Feld Ballen Pressen. 
Wenn er den ersten Startpunkt anfährt bleibt das Spiel stehen und haut mir die log voll.

KRONE BiGPack 1290 HDP II mit manuellem Garn befüllen
[log.txt](https://github.com/Courseplay/courseplay/files/4466592/log.txt)

![fsScreen_2020_04_12_17_35_45](https://user-images.githubusercontent.com/5399009/79073148-2fd40300-7ce5-11ea-9ed4-764ec328ec1f.png)

**Comment by spiessphilipp** [comment]
mit manuell befüllen hab sie auch vollständig aufgefüllt.

**Comment by spiessphilipp** [comment]
Zudem war es eine Überführungsfahrt also Strecke abfahren

**Comment by Tensuko** [comment]
Du musst sie mit automatisch befüllen kaufen.
Anders geht es im Moment nicht, das steht aber auch so in der Changelog drin bei den Releases.
