### ISSUE TITLE
Yellow Arrow appears with new Addon Straw Harvest Bonus Pellet Heat Plant v1.0 FS19

### ISSUE THREAD

**Issue by SniperKittenCZ** [Courseplay/courseplay#5166]
Hi, everything works fine, but when I placed new Addon Straw Harvest Bonus Pellet Heat Plant v1.0 FS19, Yellow Arrow appears everytime I started saved CoursePlay. 
Please, can You check it???
[log.txt](https://github.com/Courseplay/courseplay/files/4463955/log.txt)

**Comment by Tensuko** [comment]
You need to redownload the plant and maybe replace.
Check CM Discord for Info.

**Comment by SniperKittenCZ** [comment]
Unfortunatelly this does not work :(
