### ISSUE TITLE
CP/ManureSystem - Manure transporter did not stop in normal stable trigger

### ISSUE THREAD

**Issue by Mantikor83** [Courseplay/courseplay#5167]
Dear CP team, thanks a lot for your great work!

This report is **not** dedicated to full support of manure system by wopster!

When I use the manure system by wopster, the CP manure transporter has an issue with normal manure triggers. When CP is driving the course through a normal manure trigger at the stable, it doesn't stop and fill the trailer. If I jump into the vehicle while CP is driving the same course with same settings, everything is fine. CP stops, fills the trailer and goes on.

I know, that there is actually no full support of wopsters manure system, but it would be great to fix this, so I hope, small issue, so that a combined usage of CP on normal triggers and MS on prepared triggers is possible.

The issue was tested with vanilla vehicles and vanilla trailers (of course they are effected by MS)

Thanks in prior!

Manti

**Comment by Tensuko** [comment]
Already know of the Issue and in Contact with Wopster about this.
#5082

Closed.
