### ISSUE TITLE
Tractor with trailer crossing in front of the combine

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#5169]
![image](https://user-images.githubusercontent.com/11199752/79048766-bf9a8400-7bf5-11ea-8fd6-d035e4d8bb7c.png)
The tractor with trailer in the image above is crossing in front of the combine, after being 100% full, looking for the route to unload in the silo. The tractor did not wait for the harvester to go ahead, causing a collision.
How to solve this?

**Comment by Tensuko** [comment]
See #3311 and #4286 
Closed.
