### ISSUE TITLE
Tractor with seeder does not respect straight line on mode 4

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#5171]
This video shows the problem:
https://youtu.be/MGQQ2x0V82E

![image](https://user-images.githubusercontent.com/11199752/79050433-59ffc500-7c00-11ea-86bd-6c525254df59.png)

For some reason, this section (straight line, where nothing is sown) is not being respected in mode 4 (however, in mode 5, the tractor follows the correct route).
What's wrong?

[log.txt](https://github.com/Courseplay/courseplay/files/4465048/log.txt)

**Comment by Tensuko** [comment]
This is just a visual connection line between 2 waypoints.
Try Pathfind for turns (Advanced Settings)
This got also nothing to do with the Mode. It will happen in Mode6 as well.

**Comment by rogeriodec** [comment]
You mean, "Reverse for pathfinding in turns"?
![image](https://user-images.githubusercontent.com/11199752/79052975-64c25600-7c10-11ea-84cf-82afbe862a3f.png)

**Comment by Tensuko** [comment]
Use Pathfind in turns.
One option over it.
