### ISSUE TITLE
Horsch SW3500S Issues

### ISSUE THREAD

**Issue by Beattune** [Courseplay/courseplay#5173]
Hey CP-Team,

first at all thank you for your work! I have some issues with the seeder Horsch SW3500S with attached an Pronto 6AS (see https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=155181&title=fs2019). Sometimes when I use this seeder with CP everything works fine. But today it happend that CP all time says (sorry for german: "Gerät muss entladen werden"). I don't know why and I tried it to reproduce it also on Ravenport only with this mod and with CP. Same error, no entrys in the Logfile (see attached from my main savegame). 

I can provide you more informations if needed. 

Thank you for your help!

[log.txt](https://github.com/Courseplay/courseplay/files/4465228/log.txt)

**Comment by Tensuko** [comment]
Will have a look.

**Comment by Beattune** [comment]
@Tensuko i found the problem. There is both options available. There is Mode 4 and Mode 6 available. I have choosed Mode 6 and there is it not working. In Mode 4 is it working as intended.
So not really a bug, more a user problem :D
