### ISSUE TITLE
Multiplayer Dedicated Server with Multiple tools.

### ISSUE THREAD

**Issue by MountainDue** [Courseplay/courseplay#5176]
Hi
Can anyone confirm that course plays works on a dedicated server using multiple tools? In single-player, I can get three combines to work perfectly as they should with course play but as soon as I try it on a dedicated server no joy, all three tools follow straight down the route and will not shift to the left or right. Thanks for all the hard work, course play is the bee's knees.

**Comment by ObscuredEvil** [comment]
Same problem here

**Comment by Tensuko** [comment]
Collecting all in #5484
