### ISSUE TITLE
Krone BigPack Problem Feldarbeit

### ISSUE THREAD

**Issue by 3lronMcBong** [Courseplay/courseplay#5177]
Moinsen,

habe auch so einen Fehler.
Wollte Quaderballen machen, mit AD zum Feld fahren lassen danach sollte CP auf dem Feld Ballen Pressen. 
Wenn er den ersten Startpunkt anfährt bleibt das Spiel stehen und haut mir die log voll.

KRONE BiGPack 1290 HDP II mit manuellem Garn befüllen
[log.txt](https://github.com/Courseplay/courseplay/files/4466592/log.txt)

![fsScreen_2020_04_12_17_35_45](https://user-images.githubusercontent.com/5399009/79073148-2fd40300-7ce5-11ea-9ed4-764ec328ec1f.png)

_Originally posted by @3lronMcBong in https://github.com/Courseplay/courseplay/issues/5165#issuecomment-612635751_

**Comment by 3lronMcBong** [comment]
Mit Automatische Befüllung des Garns geht es :-)

**Comment by Tensuko** [comment]
Steht auch in den Commits:
Make sure to buy/set up everything with automatic refill supplies for now.

Daher: Ist bekannt, closed.
