### ISSUE TITLE
Worker does not restart Premos 5000 once stopped

### ISSUE THREAD

**Issue by tango99** [Courseplay/courseplay#5178]
I have got the Premos 5000 working with Courseplay using the latest patch of both Courseplay and Straw Harvest, however I have noticed that if the Premos is forced to stop due to taking in too much straw at one time, the worker will not turn it back on and continue driving the course with the machine turned off.

**Comment by Tensuko** [comment]
Yea I know this is a 'feature' of the Premos... will see if we can do anything about it, for now, get a stronger tractor (ppl said that on CM Discord..)

**Comment by tango99** [comment]
Ah, I didn't realise that it was related to the tractor power, i'll try with a more powerful tractor. Thanks!

**Comment by meikofr** [comment]
Hi,
Premos do not automatically start the course. I start it before.
The Premos is stopped when it is full. Logic!
After unloading, the Premos does not turn on automatically.
unloading in the truck at the edge of fields.

(google translat FR->US)
