### ISSUE TITLE
Function of the next/previous mode keys?

### ISSUE THREAD

**Issue by Valf203** [Courseplay/courseplay#5180]
Sorry, not sure if appropriate to ask here. Can someone explain what these key binds are supposed to do? I've never been able to get them to affect anything in Courseplay's pop-up menu, whether the modifier key is held down at the same time or not.
Other key binds related to driver command etc. works just fine for me.
Seaching here only brought me to the original request to implement them: https://github.com/Courseplay/courseplay/issues/932

**Comment by Tensuko** [comment]
Those keys are to switch the Mode...
I have done some changes to keybinds (not into actual version yet), but didn't take a look into those one but I will check on that.
Might not work with the newest HUD, but will see.
