### ISSUE TITLE
How to unload a combine directly to a silo?

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#5181]
My combine is close to the silo.
Is there a way for CP to unload it directly into the silo?
When the combine is full it should:

1. Disconnect the cutter bar
2. Go to the silo
3. Unload the fruit directly into the silo
4. Return to the point where the harvester had stopped in the field
5. Reconnect the cutter bar
6. Continue the harvest

How would that be possible?

**Comment by Tensuko** [comment]
Can't do.

**Comment by rogeriodec** [comment]
Could this thread be converted as a suggestion for improvement?
