### ISSUE TITLE
How to unload a bale collector in the barn?

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#5182]
I am collecting square bales with the Arcunsin FSX 63.72 bale collector.
![image](https://user-images.githubusercontent.com/11199752/79081840-6581e780-7cf7-11ea-8a74-b31228884e51.png)

How could CP proceed to unload this bale collector automatically in the barn, just as it does with fruits?

![image](https://user-images.githubusercontent.com/11199752/79081862-88140080-7cf7-11ea-914f-98fff0fc9403.png)

![image](https://user-images.githubusercontent.com/11199752/79081866-8f3b0e80-7cf7-11ea-907f-f78f4cd746be.png)

**Comment by Tensuko** [comment]
Add course like refill seeds, just add the unload here point to the course (iirc).

**Comment by rogeriodec** [comment]
Perfect. Thank you!
