### ISSUE TITLE
Courseplay HUD not showing

### ISSUE THREAD

**Issue by Grumpykitten710** [Courseplay/courseplay#5183]
Ok so I've got a bit of a weird situation I think, I started a new map and put courseplay on it with all my mods, didnt work, when i right clicked only the cursor came up and there was a definitive sound like it opened but no HUD, so i try a different map that i have previously used it on with all the same additional mods does the exact same thing, so I tried it again on both maps without any mods to see if theres a conflict and still same problem so I give a different map a kick at the can with the additional mods and it works perfectly fine, Hud comes up like it should and courseplay works fine. I'm just confuse as to what the problem is I've tried a updated version of CP and it just corrupts the game

**Comment by Tensuko** [comment]
But no log attatched...

**Comment by Grumpykitten710** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4470471/log.txt)

**Comment by Grumpykitten710** [comment]
sorry first timer here

**Comment by Grumpykitten710** [comment]
wow lol this can be closed i cleared the logs and its working fine now sorry
