### ISSUE TITLE
Pflug arbeitet nicht sauber an den Wendepunkten - .397

### ISSUE THREAD

**Issue by Vega56** [Courseplay/courseplay#5184]
Hallo,

zurzeit benutze ich die v6.01.00397 auf der Hof Bergmann.

Wie auf den Screenshots zu sehen arbeitet der Pflug an den Wendepunkten nicht sauber.

Es ist kein Mod sondern der Standard. Der Kurs wurde generiert ohne an der voreingestellen Arbeitsbreite etwas zu ändern. 

Welche Debug Channel benötigt ihr noch?

![20200413102039_1](https://user-images.githubusercontent.com/55054246/79105395-df09ec00-7d70-11ea-9a30-a3a50bade77c.jpg)

![20200413101959_1](https://user-images.githubusercontent.com/55054246/79105388-dd402880-7d70-11ea-8165-99bef4cd81e6.jpg)
![20200413102003_1](https://user-images.githubusercontent.com/55054246/79105389-ddd8bf00-7d70-11ea-97ea-64f8517299db.jpg)
![20200413102018_1](https://user-images.githubusercontent.com/55054246/79105393-de715580-7d70-11ea-992d-0f1b0506f93b.jpg)
![20200413102029_1](https://user-images.githubusercontent.com/55054246/79105394-df09ec00-7d70-11ea-96a4-25d753243fc4.jpg)

[log.txt](https://github.com/Courseplay/courseplay/files/4468685/log.txt)

**Comment by Merrlin** [comment]
Wenn du in die Advanced Settings gehst kannst du umstellen wann das Anbaugerät gehoben oder gesenkt werden soll.
Da sollte bei lower early und bei raise late eingestellt sein.

**Comment by Tensuko** [comment]
@Merrlin 
Ja das sollte etwas helfen.

@Vega56 
Mit solchen dunklen Screenshots sieht man leider etwas schlecht was da passiert.
Bitte das nächste mal darauf achten, dass es heller ist ingame.

**Comment by Vega56** [comment]
@Merrlin 

Danke für den Tipp! So klappt es.

@Tensuko 

Sorry, werde nächstes mal darauf besser achten. War noch früh :)
