### ISSUE TITLE
Combine offload problem?

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#5186]
Im using V.397.

This is a strange one to my mind. When i have a tractor with a course set up to unload the combine most of the time omce it has emptied the combine it will wait with a message 'waiting until position is free' then once the combne is far enough away it will pull in behind and wait.

However ocassionally when the tractor has finished unloading it will turn immediately right directly into the combine accompanied by the message 'drive to (a waypoint)'. I can only stop it if i take manual control.

There is no pattern to this it just happens randomnly. 

has anyone else experienced this?

**Comment by Tensuko** [comment]
See #3311 and #4286
