### ISSUE TITLE
Error in mouseEvent, Locks up Courseplay

### ISSUE THREAD

**Issue by ddewar** [Courseplay/courseplay#5187]
Hi there,

I have run into a few situation on the latest version of Courseplay where the game will freeze and Courseplay UI will stop accepting input. Looks like it is throwing this error right before:

2020-04-13 21:26 Error: Running LUA method 'mouseEvent'.
2020-04-13 21:26 dataS/scripts/vehicles/specializations/Attachable.lua(1318) : attempt to index field 'attacherVehicle' (a nil value)

I have experienced this using the Holmer Terra Variant 585 with the Annaburger Manurespreader XM3. But also on the previous release version using the Krone Big M 450.

[Log]( https://gist.github.com/ddewar/1aea6a831826f3750e754e6c2036c355)

( Sorry for the messy log, I will get a clean one when I get some time. )

**Comment by Tensuko** [comment]
Does it still happen when you throw out manuresystem ?

**Comment by Tensuko** [comment]
Closed due to inactivity, but I guess this is a modconflict.
