### ISSUE TITLE
Abfahrer für Premos verursacht lua fehler und Spielabsturtz

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#5188]
Hallo CP Team. Ich versuche die Premos mit einem abfahrer abzufahren als drescher.

Wen ich den CPfahrer einstelle kommt folgende fehlermeldung und ich kann nur noch das spiel über den taskmaneger beenden.

Error: Running LUA method 'update'.
F:/LS19_Mods/mods/FS19_courseplay/fruit.lua:189: attempt to index field 'spec_combine' (a nil value)

[log.txt](https://github.com/Courseplay/courseplay/files/4475294/log.txt)

MFG Mannie313

**Comment by Tensuko** [comment]
#3311 #4286 ?
Das solltest du mitlerweile wissen ;)

**Comment by Mannie313** [comment]
und was bedeutet dieser fehler. andere abfahrer gehen ja auch

**Comment by Tensuko** [comment]
Das bedeutet das wir den alten Abfahrer nicht unterstützen und am neuen arbeiten

**Comment by Mannie313** [comment]
das ist ein fehler von der ganz neuen version. 6.01.00398

**Comment by Tensuko** [comment]
Ja... Es ist trotzdem der alte Mode2 Abfahrer...
