### ISSUE TITLE
Sometimes not unloading a tip trigger (Working and broken videos)

### ISSUE THREAD

**Issue by willjallen** [Courseplay/courseplay#5190]
I recorded two videos, the tractor is on the same path with the same settings in both instances. In the first video, unloading works as intended. In the second, it does not. I find I have the experience in the broken video MUCH more often than the first.

FS19
v6.01.00398

Working:
https://youtu.be/BF08VVVhqBQ

Broken:
https://youtu.be/FxBdeXyM0TE

**Comment by Horozor** [comment]
@willjallen 
Create the same course, WITHOUT an unloading point and waiting point. Just drive along the platform. Hope this helps

**Comment by Tensuko** [comment]
Passing a Trigger is Passing a trigger, don't ever put a wait or unloadpoint as @Horozor said...
I wonder who spreads this total wrong Information...
