### ISSUE TITLE
Courseplay Editor - Kann nicht gestartet werden

### ISSUE THREAD

**Issue by BrunoMoser13** [Courseplay/courseplay#5192]
Ich verwende CP Version: 6.01.00398. Wenn ich einen Feldkurs mit dem Editor bearbeiten will passiert nix.

Anbei meine Log und meine input binding...
[inputBinding1404.txt](https://github.com/Courseplay/courseplay/files/4481563/inputBinding1404.txt)
[log_1404_.txt](https://github.com/Courseplay/courseplay/files/4481564/log_1404_.txt)

**Comment by Tensuko** [comment]
Hast du die Release Version geladen oder den Branch per .zip File ?
Das Problem ist die haben beide die Version 398 da wir noch keine neue Release Version erstellt habe.

**Comment by BrunoMoser13** [comment]
ich habe diesen link benutzt https://github.com/Courseplay/courseplay/releases/download/6.01.00398/Courseplay_6_01_00398.zip

**Comment by Tensuko** [comment]
Ok das ist die Release Version.
Das kann sein das es nicht gut geht.
Weis nicht ob du das schon mal gemacht hast:
https://github.com/Courseplay/courseplay
Oben rechts den grüne Button Clone or Download, download als .zip
Die .zip Datei entpacken und den Inhalt (also alle Dateien) in dem entpackten Ordner einmal in eine neue .zip Datei packst und diese dann in FS19_Courseplay benennst.
Dann sollte das mit den Tasten gehen und du kannst alles frei belegen wie gewohnt.
Kannst dann mal gerne Rückmeldung geben :)

**Comment by BrunoMoser13** [comment]
Siehe da - jetzt geht es wieder. Wie kommt es, dass sich diese Art von der normalen ZIP unterscheidet?

Danke für den Support

**Comment by Tensuko** [comment]
Naja der Branch hat aktuelle Cimmits also Änderungen. Davon gibt es aber noch kein Release, das ist alles.
