### ISSUE TITLE
Error: Running LUA method 'mouseEvent' - settings.lua:933: attempt to index a nil value

### ISSUE THREAD

**Issue by Berios** [Courseplay/courseplay#5193]
Hallo zusammen!

Leider habe ich gerade einen Lua 933 Error erhalten. Vielleicht könnt ihr mir helfen.
Ich hatte zum Zeitpunkt des Errors zwei drei Gespanne auf CP im Einsatz.
Der Error wurde auffällig, da meine CPU Auslastung eine Spitze bekam und das Spile kurzfrist hakte.

Eben die Eckdaten:

Karte: Oberthal 1.2.2.0
Ich hatte zum Zeitpunkt des Errors zwei drei Gespanne auf CP im Einsatz.
Ein Gespann ist Standard (bereits im Spiel vorhanden), die beiden anderen Gespanne bestehen aus Mod - Traktoren, einem Mod Ladewagen und einem Striegel (Standard).

Ich füge noch meine Log ein.

Danke für eure Hilfe im Voraus.

Berios

[log.txt](https://github.com/Courseplay/courseplay/files/4482892/log.txt)

**Comment by Tensuko** [comment]
Da stimmte was mit den Kursen nicht...
Was für ein Gespann war das und war der zufällig in einem Turn ?
Hast du in den Advanced Settings Use Pathfind in Turns auf aktiviert gesetzt ?

**Comment by Berios** [comment]
Hallo Tensuko!

Nein, das habe ich in der Tat nicht getan. Bin mir nicht sicher, ob er in einem Turn war. Der Fehler entstand nach dem Einstellen des Kurses. Dann habe ich ihn wieder aus dem Kurs genommen, da ich die Pflegebereifung vergessen hatte. Der Fehler hat sich aber nicht mehr wiederholt. Ich aktiviere mal die Pfadfindung in Turns und schaue mal weiter. Wahrscheinlich tatsächlich ein Bedienfehler von mir - ansonsten läuft das Ganze seit Stunden ohne ein einziges Problem.

Super Arbeit und ein tolles Script. Vielen Dank für eure Mühe. :-)
Ich schließe erst einmal dieses Issue. Sollte der Fehler wieder auftauchen mache ich eine neue Issue auf.
