### ISSUE TITLE
multiple routes issues

### ISSUE THREAD

**Issue by wilsontray** [Courseplay/courseplay#5195]
So Ive read up as much as I could find and watched a few youtube tutorials and I know you can combine 2 routes via crossing points however I am curious if what I want to do is possible since as of yet the driver ends up going crazy no matter how I implement it.

For a simplified example of what I am going for lets say I keep the tractors as Point A   and I have a loop route(call it B) that just circles all the farms...... I also have various fields... lets say field C

Now if I want to go from route A>B then take B to field C  then start fieldwork I know  I can combine routes and make a route that effectively goes from A to C then start up the fieldwork

But is it then possible for it  to take the loop route B to a gas route if it needs fuel, as well as a seed route if it needs more seeds to plant?

I guess my question is if I have a ton of different independent routes what is the best way to get the route to use the right routes at the right times?  or is that even possible?

I suppose I could make the loop route Also go through the fuel and seed and fert and whatever else it may need to get but figured Id ask the correct way to implement this before I do it.

**Comment by Tensuko** [comment]
> make a route that effectively goes from A to C then start up the fieldwork

This doesn't work automatically with CP.

CP can't choose a Route for the situations that you want.
You can have a Fieldwork Course and add a Refillcourse for Seeds and stuff, but not also one for Fuel and then let CP decide.

The Crossingpoints are for kinds like this:
(Attention, early in the morning Paint Skills are Incoming)
You got your green router with a Crossingpoint, you got your red course with 2 Crossingpoints and the purple one with a crossing point.
Load all 3 course (not sure about the Order to load, but it is the normal folder button) if CP reaches a crosspoint, it looks for the closes crosspoint on another course, that would be the red one, then drive till the next crosspoint and looks again for a close crosspoint, then he would drive the purple line. I know some ppl use it that way, I never did and I am not sure if can create a Route for refill that way.
I know that there is some kind of reset about the last used Fieldwork Course Waypoint, but didn't figured it out yet.
![crossing](https://user-images.githubusercontent.com/27344744/79415749-73ad5d80-7fae-11ea-8b52-453ae53c89db.png)

If you want that kind of automatic that you discribed, you would have to take a look to AutoDrive.
It can start CP Driver if you set all settings for CP correctly before start AD, I think it can check for fuel, but for sure can reload seeds (also in CP HUD, use AD for refill) and it should also be able to send it back to a Parkingposition when you set one for it in AD HUD.

**Comment by Tensuko** [comment]
Closed due to inactivity,
Explanation how it works is abouve.
