### ISSUE TITLE
Issue With Course

### ISSUE THREAD

**Issue by patch110** [Courseplay/courseplay#5196]
Basically i drove an unload course with the ingame MAN truck but when i put another truck (ingame Tatra) on the same course he runs offset and collides with roadside scenery. Can anyone tell me why this is happening.
The picture will explain better.
![fsScreen_2020_04_16_17_10_52](https://user-images.githubusercontent.com/32200890/79480780-7a67bf00-8006-11ea-945b-d618ac39c71d.jpg)

**Comment by Tensuko** [comment]
Say thanks to GIANTS makeing the Nodes on those Trucks wrong (falsch).
![Nodes](https://user-images.githubusercontent.com/27344744/79487850-231f1a00-8019-11ea-928c-663c98d0e0b3.png)

Try to use Offset or a Mod Truck.
