### ISSUE TITLE
Having Issues

### ISSUE THREAD

**Issue by navnik531** [Courseplay/courseplay#5197]
So I downloaded this mod for the first time yesterday because of all the great reviews on it, but after over 5 hours of playing around with the settings I am no closer to figuring out what I am doing wrong.  I have watched multiple videos on how to use it, but it seems every one of the videos has options they can use that I have greyed out.  I can't even scan a field.  

I started a new save in Ravenport with no other mods enabled but so far all I have been able to do is record a route around the field which all my equipment does when I try to drive the course is to drive in small circles and do nothing else.  I  am no further 6 hours after playing around with it and watching videos as I was in the first 10 minutes of using it.  I have enabled everything in the settings that every other user I can see has enabled, but it has had no effect on what I can do.  Any help on what I am doing wrong would be greatly appreciated. Screenshot is for the only options I have.

![image](https://user-images.githubusercontent.com/63807178/79485365-b7b65780-7fda-11ea-9448-af990c0fe6eb.png)

**Comment by Tensuko** [comment]
Becouse you have no tool Attatched.
A Tractor like you use there can only Drive/use Mode5 (the green Mode).
Count from Left to the Right Mode1 - Mode10 (lower Buttons).
If you want to cultivate the Field, buy a cultivator and attatch it, then you will see that Mode6 get white and you can click it. Then, when activated that Mode, you will have the option Course Generator and then you can set up the Field Course for your Fields.
Try it out, it is not that hard I think all you miss is that you need a Tool attatched :)

**Comment by Tensuko** [comment]
Tutorials and a bit more try ut should help.
Not rly an Issue so closing this.
