### ISSUE TITLE
Unloading Combine in mode 2

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#5198]
Im getting old but i seem to remember that in previous FS games when you used CP in mode 2 (offload combine and deliver) if the combine was unloading when it reached the end of a row it would stop and not move until it had emptied its tank.

At the mo, when the combine is emptying and comes to the end of the row it just carries on and turns to start its next run. Is this what's supposed to happen?

**Comment by Tensuko** [comment]
See #3311 and #4286
