### ISSUE TITLE
Warning, Version 6.01.0038 and LUA Problems

### ISSUE THREAD

**Issue by drich2211** [Courseplay/courseplay#5199]
Load mod: FS19_courseplay (Version: 6.01.00398) (Hash: 8db076ec71bbf2a6de4df04ce3d192fd)
Warning: Duplicate l10n entry 'COURSEPLAY_CLICK_TO_SWITCH' in 'C:/Users/drich/Documents/My Games/FarmingSimulator2019/mods/FS19_courseplay/translations/translation_en.xml'. Ignoring this definition.
[log.txt](https://github.com/Courseplay/courseplay/files/4493822/log.txt)

**Comment by Tensuko** [comment]
More Details, also check your Mods for Updates

**Comment by drich2211** [comment]
This is running with only Global Company and Global Company Icons, Jones Dairy Farm and Courseplay
[log1.txt](https://github.com/Courseplay/courseplay/files/4495534/log1.txt)

**Comment by Tensuko** [comment]
Translation Warning will be fixed in the next Release and I don't see any LUA Error.
The Ingame Vehicle Warning about Colission is not our Problem.
So where is the LUA Problem ?

**Comment by drich2211** [comment]
The LUA errors are listed in the original message above in the log I Sent!

**Comment by drich2211** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4504160/log.txt)

**Comment by Tensuko** [comment]
Debugchannel 7 active, then try to generate the course you want again and post that logfile.
Also make a Screenshot of the Course Generator Settings so we can see the settings and the Field.

**Comment by Tensuko** [comment]
> 
> 
> The LUA errors are listed in the original message above in the log I Sent!

Just to let you know, if you search inside your logfile in the original message, there is just a Callstack, wich is a totaly different Issue from what you showed me now...
