### ISSUE TITLE
Can i start a Course at my Farm to the field, fertilize it and send it back to farm

### ISSUE THREAD

**Issue by SeriouZ12** [Courseplay/courseplay#5200]
Title says it all. 
Im coming back to fs the first time since 17 and thought the good old Courseplay would do its job just as im used to it.
So i recorded a Course to the field, generated one for the required job, one refill course and a course back to the farm.
My goal was, like in 17:
1. Drive to the field
2. Do your job
3. If you need refill (Fertilizer, Seed) drive to the refill spot (Auger wagon or pallets waiting)
4. Drive back to the farm when finished.

Im appending the courses one by one.
For some reasons as soon as i hit drive cp is activating or lowering the implement on its way over the street.. 
The Break Points are set, i saw that while driving it to get an idea whats wrong. But i have noi clue..

Is this feature even longer supported in the newest Version?
If there is a Ticket with the Solution could you link it for me?
Thanks in Advance!!!

**Comment by Tensuko** [comment]
No.
Any Added Course to a Fieldwork Course is for refill.
Check AutoDrive, with CP+AD you can do that.
