### ISSUE TITLE
 v6.01.00398

### ISSUE THREAD

**Issue by Nickem112** [Courseplay/courseplay#5205]
there is an problem with running multitool to haverst an feild   can you fix it please

**Comment by Vega56** [comment]
https://github.com/Courseplay/courseplay/issues/5055

**Comment by Nickem112** [comment]
im not the only one that haveing this same problem

**Comment by Tensuko** [comment]
You still dont follow the rules for a bugreport!

**Comment by pvaiko** [comment]
Reminds me of that anecdote about pilots filling out problem reports for the maintenance personnel:
Pilot:  Something loose in cockpit.
Solution by maintenance folks: Something tightened in cockpit.

And with this, I close this issue...
