### ISSUE TITLE
Feld 17 Kursberechnungsproblem Map_FS19_WildWest_16x

### ISSUE THREAD

**Issue by regs1980** [Courseplay/courseplay#5207]
Ich schreibe es mal auf Deutsch, ist einfacher. 
FS19_courseplay (Version: 6.01.00398)
Das Problem besteht darin, das egal an welcher Seite man das Feld berechnet, immer das selbe Ergebnis raus kommt. 
Auch verschiedene Einstellungen habe ich probiert, immer mit dem selben Ergebnis.

<img width="960" alt="2020-04-19 10_50_27-Greenshot" src="https://user-images.githubusercontent.com/13314443/79684291-54bdfe00-8230-11ea-8659-ae66590e3faa.png">

<img width="960" alt="2020-04-19 11_20_39-Greenshot" src="https://user-images.githubusercontent.com/13314443/79684294-5982b200-8230-11ea-8112-e86c23059f32.png">

**Comment by Tensuko** [comment]
Wir bräuchten einmal die Field Definitions:

>>How to Post Your Field Definitions

To troubleshoot fieldwork course generator issues the devs may need your field definitions.

    Make sure you have the developer console enabled (google it, or see this video)
    Activate the console (tilde/backtick key twice above the TAB) and type in cpSaveAllFields
    Courseplay writes a file named cpFields.xml to the CoursePlay_Courses/ folder (in the game folder). Post this file in the issue and tell us course generator settings including work width and the number of the field you are having problems with.

**Comment by regs1980** [comment]
fieldNum="17" 

Is that what causes problems.
Settings as in the picture

[cpFields.zip](https://github.com/Courseplay/courseplay/files/4499868/cpFields.zip)

**Comment by regs1980** [comment]
Wie ist denn jetzt der Stand der Dinge, selbst mit der 6.01.00399 wurde das Problem noch nicht behoben, der Feldscan ein drittel des Feldes nicht zu berechnen, ich habe 20 Versionen von euren mod probiert alles das selbe Ergebnis, selbst bei zwei anderen Rechner funktioniert es nicht.

manueller Feldscan Oberseite 

<img width="1260" alt="2020-04-24 17_50_07-Greenshot" src="https://user-images.githubusercontent.com/13314443/80231785-26875680-8654-11ea-9ca9-723a4dea0533.png">


manueller Feldscan Unterseite 

<img width="1386" alt="2020-04-24 17_40_48-Greenshot" src="https://user-images.githubusercontent.com/13314443/80231907-57678b80-8654-11ea-96a0-53f2a5edcb6b.png">

Den blau gekennzeichneten Bereich kann der Feldscanner nicht berechnen 

![Inked2020-04-24 17_44_05-Greenshot_LI](https://user-images.githubusercontent.com/13314443/80232078-9695dc80-8654-11ea-9b30-b20e873d7088.jpg)

**Comment by Tensuko** [comment]
Wir haben auch nicht gesagt, dass wir das dran gemacht haben...

**Comment by ambardesign** [comment]
I have the same issue. Is there something I can do myself to resolve this?

**Comment by bjt3833** [comment]
I too have this problem on this map and field. I even went so far as to drive around the field and make a perimeter of the whole field to try doing it that way but that didn't work either. Is it possible that the field is just too large for courseplay? If I break that west square off by recording a path around it's perimeter and generating a course using path that then it will do the west square, that was drawn on the image above, properly.

**Comment by Tensuko** [comment]
Duplicte #6017
