### ISSUE TITLE
Game Crash when engaging CP with Baler and Balecollect

### ISSUE THREAD

**Issue by WubbeOP** [Courseplay/courseplay#5210]
When I start the CP Helper on the combines course to collect the straw for bales it essentially crashes my game. camera bugs and I cant stop the helper or anything.

so far only tested with the Krone Baler from the Addon and BaleCollect.

**Comment by Tensuko** [comment]
Logfile ? #5055

**Comment by WubbeOP** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4509238/log.txt)

**Comment by polosubtil** [comment]
I think you need the latest version https://github.com/Courseplay/courseplay/releases/tag/6.01.00398

**Comment by Tensuko** [comment]
- Update CP
- Update GC
- Update SH to Beta 26 (See CM Discord)
- Only one Map in Mods Folder.

**Comment by Zoochase** [comment]
I have the same issue with 398

**Comment by Tensuko** [comment]
Logfile ?

**Comment by le-muh** [comment]
hello, same issue here... Krone Big Pack with Bale Collect will crash the game (and even delete savegame in one case) when using Courseplay. I have just one Mod Map in my folder and only used straw harvest dlc with courseplay, no additional Mods. Please Help!

**Comment by Tensuko** [comment]
Logfile ? god damn it....

**Comment by Tensuko** [comment]
Closed due to inactivity....
