### ISSUE TITLE
question - function of mode1

### ISSUE THREAD

**Issue by caplink811** [Courseplay/courseplay#5211]
Hi,
maybe somethings wrong with mode1, or with me, so the question is "how is mode1 suppose to work"?

Background of my question is the behaviour of CP when I started mode1 and leave the car before it reached the 1st loading point, it stood forever in the trigger and won't load. The same works fine, when I stay in the car until the loading starts.
Works variante 1 as designed, or should it work as I assume (loading without a player in the car).

If it is an problem/error, I'll provide a log and video as well. If it isn't, then please close this issue.

tia
JrB

**Comment by Tensuko** [comment]
Loading at start or trigger:
Drive your Trailer under the Loadingpipe, then start recording the course.
The 2nd Waypoint should have some distance from the start point so drive a bit straight the 1st few meters.
Then drive your course (don't set any wait or unloadpoints at any riggers) and end the Course a few meters in front of the Loadingpipe.
If you want to it load something by wayting at the start, well then just don't have a pipe or loading trigger between stop and start.
Note: ManureSystem doesn't work with CP.

Also: Mode1 isn't working in MP, just in case you play in MP...

**Comment by caplink811** [comment]
Morning,
I think, the course worked fine in the past, bt now the loading only begins when the player is in the car.
For clarification please see the linked video. Also attached are log and courses folder. The map is Saxonia.

tia
 JrB

[FS19_Saxonia.SampleModMap.zip](https://github.com/Courseplay/courseplay/files/4507970/FS19_Saxonia.SampleModMap.zip)
[0420_CP_Mode1_Prob_log.txt](https://github.com/Courseplay/courseplay/files/4507977/0420_CP_Mode1_Prob_log.txt)
Video: https://1drv.ms/v/s!Aqt5msdvWb55iE4eRN1HJecwahc5?e=phGViT

**Comment by Tensuko** [comment]
The mode still works like it should.
Also if you read my answer and check your log you still see this in your logfile:
Load mod: FS19_manureSystem (Version: 1.0.9.0-beta) (Hash: 3e202c7c418da6cd4458d897042c6be5)

**Comment by Tensuko** [comment]
Also see this Issue at ManureSystem:
https://github.com/stijnwop/manureSystem/issues/37

**Comment by caplink811** [comment]
thanks, 
then I misunderstood you're 1st answer, me thinks that it is related to some liquid transports, and not to loading sugarbeets, or in this example silage.

Now I have to decide to fire my liquidmanure seperator, or feed the BGA not automatically...

I'll close this issue now.

bye
 JrB
