### ISSUE TITLE
Coursplay zeigt 13 Fehler auf meinem server an und kann auch keine kurs ordner löschen

### ISSUE THREAD

**Issue by Ank87** [Courseplay/courseplay#5212]
Hallo 
Ich habe ein Problem mit Coursplay auf meine server.
Im spiel drin kann ich keine gespeicherten Kurse löschen da wird kein mülleimer angezeigt 
ich habe es im normalen multiplayer getestet da geht alles nur nicht auf meinem Server.
woran kann das liegen.

**Comment by Tensuko** [comment]
Such dir ein Issue aus:
https://github.com/Courseplay/courseplay/issues?q=is%3Aopen+is%3Aissue+label%3A%22MP+Related%22
