### ISSUE TITLE
Mode1/2 observations

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#5213]
Firstly i love this mod, been using since 13. I wouldnt play FS without it.

But this Years CP is 'perplexing', having used it for 100+ hours now.  Im using mode 2 with 2 combines. The CP controlled tractor is sometimes very releuctant to pass the seond combine. It will then turn back on itself and end up doing dircles looking for the waypoint its been intructed to find. Im using the Lexion from Claas DLC. Ive tried various tractors, mod and vanilla and all do the same.

Another observation, when the CP tractor is called to empty the combine, it will drive what seems like a very long way past the combine before it turns to attempt to catch up and empty.

Ive found using mode 1 that neither 'fuelsave' mode or the beaconlights work. Both work fine on all other modes.

These are not criticsms just my observations! Keep up the good work and i hope these help in the development

**Comment by Tensuko** [comment]
Mode1 Issues might be fixed with the next version.
Mode2... I mean... this is known for so long now.... See #3311 and #4286 
Closed.
