### ISSUE TITLE
Can not Load Courseplay

### ISSUE THREAD

**Issue by jdog8829** [Courseplay/courseplay#5214]
Please help. I can not get this mod do download into the game. I have had a previous version of this mod in the past. I have done everything the same as I did when I downloaded it the first time. I unzip the master file, copy all contents, than create a new zip named FS19_Courseplay.zip and add that to the mods folder. What am I doing wrong?

**Comment by Tensuko** [comment]
Load the .zip file from here:
https://github.com/Courseplay/courseplay/releases/tag/6.01.00398
Only rename it to FS19_Courseplay.zip
And then you should maybe attatch the log.txt so I can see more about whats wrong.

**Comment by jdog8829** [comment]
So I followed your directions using the link and renamed the file as you said. Still no luck and I can't find any log.txt file to attach. If you could help me find that file I would be more than happy to send it over.

**Comment by jdog8829** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4510728/log.txt)
I found the log.txt file.

**Comment by Tensuko** [comment]
Many Mods with Errors, sort them out.

This is why CP not loads:
Load mod: FS19_Courseplay (Version: 6.01.00398) (Hash: d28d86af9f37a4668f2bd93ecd0f6f59)
Error: Unsupported mod description version in mod FS19_Courseplay

I can't give you a more direct link to the right file that you need to download:
https://github.com/Courseplay/courseplay/releases/download/6.01.00398/Courseplay_6_01_00398.zip
Don NOT unzip and zip again, only rename.... and I just tried it out, it does work....

Load mod: FS19_Courseplay (Version: 6.01.00398) (Hash: d28d86af9f37a4668f2bd93ecd0f6f59)
(this should be the Hash Value)

**Comment by Tensuko** [comment]
Many Mods with Errors, sort them out.

This is why CP not loads:
Load mod: FS19_Courseplay (Version: 6.01.00398) (Hash: d28d86af9f37a4668f2bd93ecd0f6f59)
Error: Unsupported mod description version in mod FS19_Courseplay

I can't give you a more direct link to the right file that you need to download:
https://github.com/Courseplay/courseplay/releases/download/6.01.00398/Courseplay_6_01_00398.zip
Don NOT unzip and zip again, only rename.... and I just tried it out, it does work....

Load mod: FS19_Courseplay (Version: 6.01.00398) (Hash: d28d86af9f37a4668f2bd93ecd0f6f59)
(this should be the Hash Value)

**Comment by Tensuko** [comment]
Sry for the spam but github throws some errors right now and is a bit slow....

**Comment by Tensuko** [comment]
Closed due to inactivity
