### ISSUE TITLE
Drescher senkt Schneidwerk nach Blockade nicht mehr

### ISSUE THREAD

**Issue by Rumspringa90** [Courseplay/courseplay#5215]
Moin,
ich hatte mit dir @Tensuko darüber ja schonmal gesprochen, das z.b. der Drescher wenn er von einem anderen Fahrzeug blockiert wird das Schneidwerk nicht mehr senkt nachdem das blockierende Fahrzeug aus dem weg gefahren wurde.

Hier jetzt ein Video dazu:
https://youtu.be/VTTQn97t8Qk

Gruß Henne

Edit:
Kann ich dafür ein Debug einschalten? Oder braucht ihr noch was von mir? CP version 398

**Comment by Tensuko** [comment]
Ja das Problem ist bekannt, das passiert auch wenn er durch regen unterbrochen wird.
Schau mal hier :) #5039

Ich mache hier zu als Duplicate.

Was machen deine Tests zum abkippen ? :)
