### ISSUE TITLE
When using 2 tractors for fieldwork, the right lane offset tractor skips headlands

### ISSUE THREAD

**Issue by NightHawkNuke** [Courseplay/courseplay#5216]
The error happens about 50% of fields. Sometimes changing starting direction helps or changing type of pattern (racetrack vs up/down). Right offset tractor will drive to the center lanes and skip headlands. Left offset tractor does as expected.

**Comment by Zoochase** [comment]
I can confirm this as well.

**Comment by Tensuko** [comment]
Duplicate #5054
