### ISSUE TITLE
how to send data out by luasocket or other methods

### ISSUE THREAD

**Issue by LevineYang** [Courseplay/courseplay#5218]
Hi guys, I have to say courseplay is amazing, thank you guys for your effor here!

Now I run into a problem, I can get translation, speed, rotation and so on from the API and courseplay, now I want to transfer them out (using luasocket or other methods) to do my control algorithm in other language ,say like c++, and then send the throttle and steering angle back to function like AIDriver:driveVehicleBySteeringAngle.

But every time I do "require("socket")", the terminal in the game gave me error like "attempt to call global 'require' (a nil value)". I tried to do this using luasocket, shared memory ,reading throttle data from a text file... but all of them need to require other module and I got the error. For reading from a text file, it tells me only 'write' is allowed.

It bothers me so much, any help will be appreciated! Any method, elegent or not, is acceptable for me. I am now very familiar with lua, if I did som operation wrong, you're very welcomed to point them out!

Cheers

**Comment by pvaiko** [comment]
@LevineYang there's not much we can do about it, the Lua interpreter built into FS19 has a lot of functions disabled by Giants. 

If you want to add functionality you have to implement it in Lua. Contributions to CP are always welcome!

**Comment by LevineYang** [comment]
@pvaiko  Thank you for your response, but one more question is how can I test or use the lua code in the test folder? If I don't understand it wrong, the code in test folder is not called in the normal run.
