### ISSUE TITLE
[Question] Mode 9 for more tools

### ISSUE THREAD

**Issue by Knowen** [Courseplay/courseplay#5220]
Hello,

just a quick question:
Would it be possible to have the shovel mode (mode 9 i guess) also avaiable for all the other attachments? 
Like a Ball Grapper, Palletfork and so on.

Greetings,
Knowen

**Comment by Tensuko** [comment]
Well I know what you want to have it for, but the automatic stuff won't work then ofc...
I will think about a solution for this.

**Comment by Tensuko** [comment]
Works for some more Tools now, but not all (like those Tree grabber).
Ofc an automatic Mode with those Tools doesn't make much sence.
Closing but we keep an eye on some more Tools to use with this one.
