### ISSUE TITLE
Game freezes without errors in log

### ISSUE THREAD

**Issue by NiklasWGC** [Courseplay/courseplay#5221]
Hello,
I have a problem with Courseplay.First of all it´s a very cool mod and I need it because I play on the map Kandelin which is a 4xmap.Sometimes my game freezes and then I can´t do nothing so I have to open Task-Manager to close Farming Simulator 19.In the log there is only written that the lua cache is on an dangerous level for consoles.I hope you can help me.

Niklas WGC

**Comment by Tensuko** [comment]
I still want to see a logfile....

Anyway, this could be pathfinder calculationg a field, you should just have a bit patience....

**Comment by NiklasWGC** [comment]
Sorry,I will send you the log.I saw that the ingame-log didn´t show me the errors but now I looked into the log in the folder on my desktop and I saw many lua errors.Sorry for my mistake.But now I have the problem if I wanr to upload the log github says that I have to try it with a file which is smaller than 10mb but the lock is about 30mb,how I can do this?

**Comment by NiklasWGC** [comment]
Is it OK if I upload the log on an other side and then I send you the link.I´m sorry if my english isn´t the best,I´m German.

**Comment by Tensuko** [comment]
Du kannst auch auf deutsch schreiben.
Hast du mal Gist probiert ?
Schau mal im Wiki https://github.com/Courseplay/courseplay/wiki

**Comment by NiklasWGC** [comment]
Ok danke.
Der lädt zu lange Die Datei ist zu groß.Ich habe es mal auf Mega hochgeladen.
https://mega.nz/file/x2hGzQ5L#rRDoKKehsZnppNwqhny80n1E9Xw8wJgS96VpHrLDXQ8

**Comment by Tensuko** [comment]
- Callstack
- nicht aktuelle CP Version ( https://github.com/Courseplay/courseplay/releases )
- StrawHarvest braucht Beta 26 (siehe CM Discord)
- Einige Mods mit Errors...
- ManureSystem läuft nicht mit CP, bzw du kannst nichts mehr laden oder entladen

Nach Maps habe ich nicht weiter geguckt, aber für den Fall das: Immer nur eine Map im Modsordner.

Bitte aufräumen und aussortieren.

**Comment by NiklasWGC** [comment]
Ok danke,jedoch muss ich sagen,dass ich das Problem auch schon hatte,bevor ich das Strohbergungsaddon genutzt habe und die CP-Helfer nur mit Grubbern gefahren sind,es waren zwar ca 3 stück aber trotzdem.hier ist es jetzt mit dem addon,hatte es aber auch schon bevor ich das addon drin hatte.
