### ISSUE TITLE
Course Loading Failure

### ISSUE THREAD

**Issue by ObscuredEvil** [Courseplay/courseplay#5222]
Hey,
I recently set up a dedicated server with some mods including courseplay with some friends. After about 30 hours of playtime we now have the problem that when selecting saved routes, a completely different route is selected. So far, this problem could only be solved by restarting the server and loading an older backup. Then for about 2 hours it appears to be ok and fails again. This is just annoying. Are there are currently similar problems and / or how to solve it?
Thank you

**Comment by ObscuredEvil** [comment]
We did change our Server Version from 6.01.00398 to 6.01.00397, now the problem does not appear anymore.

**Comment by Tensuko** [comment]
Collecting all in #5484
