### ISSUE TITLE
Courseplay Wendekurse

### ISSUE THREAD

**Issue by tobestar1995** [Courseplay/courseplay#5225]
Hallo an alle.

Ich spiele auf der NF Marsch 4fach und habe folgendes Problem.

Bisher sind meine Courseplay-Fahrer beim sähen, zur Wende, immer ein gutes Stück rückwärts gefahren und haben danach die Wende eingeleitet.

Seit dem ich auf die neueste Courseplay Version geupdated habe fahren meine Traktoren, beim Wenden, (vor allem beim Sähen im Verband, aber nur bei der Wende zum weiteren Kurs) einfach gerade aus und dann in die Kurve.

Deswegen bleiben SIe Immer wieder in Bäumen, Deichen, etc. hängen.

Was muss ich einstellen damit der Fahrer dieses Zurückfahren wieder macht?

Ich hoffe ich konnte mein Problem relativ verständlich beschreiben und Danke im Vorraus schon mal für die Hilfe.

**Comment by Tensuko** [comment]
Wenden auf dem Feld muss an sein, Ich empfehle Grundsätzlich immer mindestens 2 Vorgewende.
In den Advanced Settings kann man noch mit der Einstellung spielen für AI Turn, Pathfinder für Turn und Reverse für Pathfinder im Turn.
Ansonsten könnte es noch am Multitool liegen, eventuell mal schauen was passiert wenn man den Bahnenwechsel zwischen symetrsich und asymetrsich umstellt.

Ansonsten mach mal ein Screenshot wenn er Wenden will mit Debugchannel 12 und 14 an (CP HUD Settings die Zahlen da unten).

**Comment by Tensuko** [comment]
Closed weil inaktiv.
