### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by Smokified** [Courseplay/courseplay#5226]
I am using version ...398

I continue to have the issue, on multiple maps with every kind of trailer, where the tipper will show the tipping animation, but the load does not actually leave the trailer.  I have to stop the driver and manually unload.

The other issue is that with this version, the unloading tractor will immediately turn and crash into the combine as soon as the combine is done unloading.  In previous versions the tractor would wait for a few seconds and then pull up behind the combine and stop.  Now, it seems to want to stop in the next lane to be harvested, and wants to drive through the combine to get there.  It should at least always try to turn away from the combine, or wait like it used to do.  In this scenario, the combine is moving around the field clockwise, and the outflow pipe is on the left (outside) of the combine.  The offset had to be manually set due to the pickup trailer being too close to the combine.

**Comment by Tensuko** [comment]
1st) logfile ?
2nd) #3311 #4286

**Comment by Tensuko** [comment]
Closed weil ich brauch kein Grund...
