### ISSUE TITLE
off-topic question

### ISSUE THREAD

**Issue by Horozor** [Courseplay/courseplay#5230]
The team that works on the mod courseplay I think you are very talented 
Help me. Can you create a mod/script that changes only 1 parameter in the game **(wearDuration = "480") to (wearDuration = "4800")**. I'm tired of having to repair the equipment before refueling it. I am not a creator of mods, I do not understand writing scripts on lua, 
I know you are busy working on your mod, but if it's not difficult, please help. I searched the entire Internet and found nothing of the kind. Something similar is in the mod (seasons) but I would like to play without it.
I know I can change this parameter in the game files, but I would like to leave them unchanged

**Comment by pvaiko** [comment]
@Horozor sorry we really need to spend that little time we have to spare for Courseplay features.
