### ISSUE TITLE
Save default course generator settings for tool and field and OneButtonRun

### ISSUE THREAD

**Issue by ddiis** [Courseplay/courseplay#5238]
Hi! 

In most cases, I use the same settings in the course generator - start from the current position and 1-2 laps. But for some tractor or tool i use more laps or less (for combine I use 50 laps, for liquid ferilizer 3-4 on same field, where other tools 1-2 laps) . It would be great if the settings for specified device were saved by default, for example, for this field. Not the generated course itself, but just the generator settings. And we can generate route without opening COURSE GENERATOR window.

And add the AutoGenerateAndStart button in main bottom small window - when the tractor is near the field or on the field, a course from the default settings for this field and this tool is generated and CP automatically starts (and if you add a hokey it will be great). So i dont need to save course and search it from many many generated course.

And one more. Maybe it possible to move the “current position” forward a little, then there will be no skip at the very beginning if the tractor approaches the field on the side. Or maybe create some option with course start offset?

![image](https://user-images.githubusercontent.com/4257956/80251840-f0130100-867e-11ea-9a1d-561a302e3038.png)

![image](https://user-images.githubusercontent.com/4257956/80250277-2bf89700-867c-11ea-9bde-36c4132bc802.png)

**Comment by Tensuko** [comment]
Won't happen as we would have change to much about it.

**Comment by ddiis** [comment]
generate is 2-3 clicks, search from many fields and destinations from different folders + 4-5 different tool width - too much scrolling) 
Thanks for answer!
