### ISSUE TITLE
Need to dismiss Giants Helper after stop CP to reenter Vehicle

### ISSUE THREAD

**Issue by antara30** [Courseplay/courseplay#5240]
[Log.txt](https://github.com/Courseplay/courseplay/files/4532918/Log.txt)
Warning (physics): Add trigger callback failed, object cpAiCollisionTrigger 2 is not a physics trigger.

Wenn man den Courseplay deaktiviert muss man immer zusätzlich noch den Helfer deaktivieren

**Comment by Tensuko** [comment]
Komplettes logfile und ich weis nicht was du meinst...

#5055

**Comment by antara30** [comment]
[Log.txt](https://github.com/Courseplay/courseplay/files/4532920/Log.txt)

**Comment by antara30** [comment]
Wenn ich den Courseplay beende muss ich immer noch den Helfer mit der Taste "H" deaktivieren, damit ich das Fahrzeug wieder selber fahren kann.

**Comment by Tensuko** [comment]
This could be a Modconflict with one of those:
- FS19_FollowMe (I think this is the one)
- FS19_VehicleControlAddon (Could be this one, but I am not sure)

Also you need the Beta 26 (new is 27) for Straw Harvest Addon (Link can be found on CM Discord):
Load mod: FS19_addon_strawHarvest (Version: 1.0.0.0) (Hash: 1d15f60600f67db89fc72447145539f4)

**Comment by antara30** [comment]
Ok..was ist denn mit Beta 26 bzw. 27 gemeint??
Das FS19_addon_strawHarvest habe ich schon lange drin

**Comment by Tensuko** [comment]
Version 1.0.0.1 bzw 1.0.0.2
Findest du bei CM im Discord wir gesagt

**Comment by antara30** [comment]
:-)
Muss man denn auf 1.0.0.1 updaten oder kann ich direkt von 1.0.0.0 auf 1.0.0.2 updaten?

**Comment by Tensuko** [comment]
1.0.0.1 ist minimum damit es mit cp läuft, klar kannst du 1.0.0.2 nehmen

**Comment by antara30** [comment]
Ok...aber das Problem, dass ich "H" drücken muss und mein Fahrzeug wieder bewegen zu können besteht immernoch...

**Comment by Tensuko** [comment]
Ja und was hast du nun alles gemacht ?
Hast du die Mods rausgenommen die ich dir da geschrieben habe um es tu testen ?
Ich muss kein H Drücken damit der Helfer raus geht und ich habe aktuell 600 Mods im Ordner....

**Comment by Tensuko** [comment]
Das solltest du auch raus nehmen, da muss Wopster noch was am Script ändern damit es für CP und AD funktioniert:
Load mod: FS19_manureSystem (Version: 1.0.0.0) (Hash: f6e43e963a789d956eb7c4212c305a4c)

Keine Ahnung wie sich das hier auswirken könnte:
FS19_noSwitchInVehicle (Version: 1.0.0.0) (Hash: 771561d9497ee56e0393d0ba315a7b4e)

Auf jeden Fall hast du einen Modconflict/Modissue.

**Comment by antara30** [comment]
Ja Follow me und VCA habe ich raus genommen aber leider keine veränderung...versuche die beiden Mods noch

**Comment by antara30** [comment]
Also im Single mode habe ich gar keine Probleme und im Privaten MP auch nicht....nur auf dem Dedi Server gibt es probleme

**Comment by antara30** [comment]
Es passiert wirklich nur auf einem Dedi Server

**Comment by antara30** [comment]
Ich habe einen komplett neuen Spielstand ohne Mods außer Courseplay erstellt. das problem mit der H Taste besteht nur auf dem Dedi Server
