### ISSUE TITLE
Issue maybe

### ISSUE THREAD

**Issue by OldMarineGy** [Courseplay/courseplay#5241]
Not sure if this is an issue or operator error.  I can't seem to get fertilizing courses to work without it always paying helper fees.  Is there something I need to change other than the Advanced Settings?

If you think it is an error, I will collect logs and make a proper ticket.

**Comment by Tensuko** [comment]
What do you want to do ?

**Comment by OldMarineGy** [comment]
Maybe my question wasn't worded very well.

Should CP pay a worker that is fertilizing or sowing when pay wages are disabled?  Mine does.

**Comment by TinyCrocodile** [comment]
Are you shure this are wages?
Check if you have enabled or disabled the buying of seed or fertelizer in gameoptions.
If still paying wages you can set the CP wages to 50% or other and check if there is a difference. This way you can figure out if the wage is really payed by CP.

**Comment by OldMarineGy** [comment]
That was the issue.  I had no idea that that is how the addon worked.  Thanks for your time.
