### ISSUE TITLE
Log Fehlerhaft

### ISSUE THREAD

**Issue by Tornado1975** [Courseplay/courseplay#5242]
Guten Tag,

wir haben das Problem, das wenn wir einen Courseplay Fahrer entlassen, dass wir erst die Autodrive Helfer An und Aus machen müssen, damit wir überhaupt Zugriff auf das Fahrzeug erhalten, würde mich über Hilfe freuen. Danke :)

[log.txt](https://github.com/Courseplay/courseplay/files/4533167/log.txt)
[server log.txt](https://github.com/Courseplay/courseplay/files/4533168/server.log.txt)

**Comment by Tensuko** [comment]
Collecting all in #5484
