### ISSUE TITLE
Course generator issue?

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#5243]
I can run FS foe about an hour or so then my FPS drops dramatically. maybe 50%.

I checked the log and the last few enteries are as follows...

2020-04-25 16:03 CourseGeneratorScreen:onCreate()
2020-04-25 16:03 Warning: Performing emergency garbage collection pass - memory went from 186854 KB to 432057 KB in less than one frame
2020-04-25 16:03 Usage is now 186906 KB; full GC took 313.648605ms 
2020-04-25 16:04 Game saved successfully.
2020-04-25 16:08 deleting
2020-04-25 16:12 CourseGeneratorScreen:onCreate()
2020-04-25 16:12 Warning: Performing emergency garbage collection pass - memory went from 195690 KB to 495263 KB in less than one frame
2020-04-25 16:12 Usage is now 195619 KB; full GC took 350.479440ms 
2020-04-25 16:13 deleting
2020-04-25 16:15 CourseGeneratorScreen:onCreate()
2020-04-25 16:15 CourseGeneratorScreen:onCreate()
2020-04-25 16:15 Warning: Performing emergency garbage collection pass - memory went from 191761 KB to 432824 KB in less than one frame
2020-04-25 16:15 Usage is now 188512 KB; full GC took 325.717470ms 

Ive no idea what any of it means but im guessing its the reason for the fps drop?

**Comment by Tensuko** [comment]
logfile ?
What have you done ?
What Mode ?
What Tools ?
What Situation ?
................

#5055

**Comment by kwguk** [comment]
Apologies.

I think what ive done is use 'course generator' a lot. I tend to do a lot of missions which require me to generate a lot of different courses in a relatively short period of time.

Its always in fieldwork mode

Tools.....anything and everything. vanilla and mod.
[log.txt](https://github.com/Courseplay/courseplay/files/4533594/log.txt)

**Comment by kwguk** [comment]
Ive done it again after restarting, used the advanced course generator and i get the same warning in my log. Ive got nothing else running CP wise or anyother vehicle. It appears to my non techie mind that i can do it so many times before the fps take a massive hit

2020-04-25 18:57 Warning: Performing emergency garbage collection pass - memory went from 166845 KB to 420536 KB in less than one frame
2020-04-25 18:57 Usage is now 167700 KB; full GC took 283.795809ms

**Comment by Tensuko** [comment]
Ok can you do the following things:
Make a Screenshot of the Setting you use in Coursegenerator when the FPS Drops hit (so we can also see the Field/Map).
But before you generate, activate debugchannel 7 and post that logfile.

**Comment by kwguk** [comment]
OK i will try.

Of course now ive mentioned it, the last few times ive generated a course the error message hasnt appeared!

**Comment by kwguk** [comment]
I would say that therehas now begun to be a drop off in FPS, its pretty unstable now. fluctuating from the20's up to 60. beforehand it was stable at 55-60.

I hope ive managed to capture wgat you need because its bloody annoying and i love using CP.

[log.txt](https://github.com/Courseplay/courseplay/files/4533828/log.txt)

**Comment by kwguk** [comment]
![fsScreen_2020_04_25_19_26_29](https://user-images.githubusercontent.com/11178621/80288696-899aeb00-8731-11ea-95a4-26a0a76e2565.png)

**Comment by kwguk** [comment]
Ive done a bit of experimenting. I thought the problem may have been because i soemtimegenerate a manualcourse which can take several minutes for the CG to work out. This morning ive ony used the automatic settings and after three course generations and  an hour or so running my FPS goes from a solid 60+ to fluctuating as nuch as 30 frames.If i reload the game i go back to a stable fps before after a few uses of CG it will resort to fluctuating again.
Am i the only one having this problem? 
Is there a way of generating a course tha wont cause a warning?

**Comment by Tensuko** [comment]
There is no option.
The more complicated the course, the more calculation have to be done.
And one question.... do you need smooth FPS while looking at that screen ?
If you got low FPS after it generated the course, then we have an Issue and even that could be caused, when you have that little eye Symbol on the HUD in DBG Mode.

**Comment by kwguk** [comment]
There is a drop in fps whem theDBG is clicked on. 
But near enough everytime i generate a course i get the warning emergency dump thingy then after a while i get fluctuation in fps during gameplay. 
What can i say. I dont need smooth fps at the course generation screen but when its the course generation thats causing the problem i dont know what to do?
At the moment my fps is flcutuating from the 20's up to 60+ and everything in between. Im not saying its completely awful just that before i start generatingcourses the fps is solid.
If you can help great! If not i ll just keep reloading that game whenever the fluctuation becomes to annoying

**Comment by Tensuko** [comment]
This is just a Warning from GIANTS Engine. Nothing to worry about.
The DBG is only for debug and should be kept turned off.
Just let it generate and when its done with generate and then it is smooth again, whats the problem ?
When the Generator is not running (the Course is there and you can save it and start CP and stuff) and it is then low FPS, it have other reasons, maybe displayed waypoints are to many...
So turn off the 3 dots in CP HUD, or lower your view distance.

**Comment by kwguk** [comment]
Ok thanks for your help!

**Comment by kwguk** [comment]
Apologies for banging on about this issuebut ive been experimenting with different graphic settings and i still get a sharp decline i gameplay fps as soon as iuse the course generator feature.
Ive run on medium and high settings and still get the same issue, if anything its moew dramatic at the lower settings.
Has no one else reported this?
Could this just be map specific?
[log.txt](https://github.com/Courseplay/courseplay/files/4538959/log.txt)

**Comment by kwguk** [comment]
Sorry ignore the above

**Comment by Tensuko** [comment]
Ofc it is not a CP Problem, Generating a course take a long time can happen on big and complicated fields.
If there is a big drop in FPS after you left the generator, this can't come from CP.
