### ISSUE TITLE
LUA method "mouse event" - Lua 933 - nil value

### ISSUE THREAD

**Issue by Berios** [Courseplay/courseplay#5244]
Hallo zusammen!

Leider bekomme ich den vorgenannten Fehler mittlerweile bei fast jeder Session.
Vielleicht könnt ihr mir helfen.
Komischer Weise hat Coruseplay in den letzten Tagen diesen Fehler nicht gebracht.
Könnte mir dem Upate der Karte von 1.2.2.0 auf 1.3.0.0 zusammenhängen.
Karte: Oberthal 1.3.0.0
Ich hänge mal die log.txt mit an.

Danke,

Berios
[log.txt](https://github.com/Courseplay/courseplay/files/4533684/log.txt)

**Comment by Tensuko** [comment]
Was genau hast du gemacht als der Fehler auftrat und ist das im SP oder MP ?

2020-04-25 19:34 Error: Running LUA method 'mouseEvent'.
2020-04-25 19:34 D:/LS19/LS19 Modordner/LS19_Courseplay6/settings.lua:933: attempt to index a nil value

**Comment by Berios** [comment]
Ich spiele die Vierfachmap im Singelplayer.

Ich hatte zu dem Zeitpunkt 4 Gruppen mit Courseplay laufen:

Gruppe 1:
Drei Traktoren, welche jeweils einen Pflug im Fahrzeugverband gezogen haben. 
Der Fahrzeugverband war aktiviert mit 1000 Meter Abstand - zwei Traktoren hatten den symetrischen Bahnwechsel aktiv.
 
Gruppe 2:
Ein Drescher mit einem Überladewagenfahrer, welchen ich in Modus 2 (Ülw mit ausgefahrenem Rohr) betreibe.

Gruppe 3:
Eine Rubicon Feldspritze, die einfach eine entsprechenden Kurs zum Düngen abgefahren ist (Mission).

Gruppe 4:
Einen Traktor, welcher mit einem 6 Meter Pflug im Rahmen einer Mission ein Feld pflügt.

Das waren alle in Courseplay aktiven Gruppen / Fahrzeuge zu dem Zeitpunkt.
Leider kann ich den genauen Zeitpunkt in Bezug auf eine "ungewöhnliche" Tätigkeit nicht identifizieren. Es kann jedes der genannten Fahrzeuge sein. 
Allerdings würde ich auf den Abfahrer mit ÜLW tippen. 
Die anderen Gruppen haben ihre Tätigkeit ohne zu Zucken weiter ausgeführt, während der Abfahrer wie ein "Geisteskranker" seine Runden (und ich meine echt "Kreise") auf dem Feld gezogen hat. 
Auch in der Folge hat er immer wieder rumgesponnen und ist so ziemlich überall unterweges gewesen, nur nicht da wo er sollte. :-)

Hoffe, ich konnte mit diesen Informationen helfen. :-) 

Danke für die Hilfe.

Berios

**Comment by Tensuko** [comment]
> Gruppe 2:
> Ein Drescher mit einem Überladewagenfahrer, welchen ich in Modus 2 (Ülw mit ausgefahrenem Rohr) betreibe.

Das ist das Problem... Siehe #3311 und #4286 (daher mache ich zu)

Außerdem:
2020-04-25 19:34 Error: Running LUA method 'mouseEvent'.
2020-04-25 19:34 D:/LS19/LS19 Modordner/LS19_Courseplay6/settings.lua:933: attempt to index a nil value
Die richtige Überschrift wäre: Error: Running LUA method 'mouseEvent' - settings.lua:933: attempt to index a nil value
