### ISSUE TITLE
Sugestion for Combi mode.

### ISSUE THREAD

**Issue by masneoquil** [Courseplay/courseplay#5245]
Hello Guys.
I know that mode 2 its the one that needs a lot of work, but I thought that ir would be better to ask now that it is still in development.
It is possible that when in mode 2 and the trailer is full and needs to unload, that in that moment it switches to AD to unload the trailer? It would be an advantage to be able to use the network that we already have.
Maybe an option?
Just an idea, but no big deal. If it is possible and you like it the better, if not no problem.

**Comment by Tensuko** [comment]
That will come later and have already been requested.
So CP will do all the driving on the Field and will send it to AD when at the Fieldborder, but that will be added later.
