### ISSUE TITLE
Trailer not unloading.

### ISSUE THREAD

**Issue by Arcadia117** [Courseplay/courseplay#5246]
Hi, 
I have a tractor with a trailor that follows a combine (mode 2 i think) and automatically go to unload its content in a silo when it's done. The tractor stop at the right spot on the silo, the animation of the trailer unloading starts, but the trailor never empty itself. does someone ever had that problem before ?

**Comment by blue-painted** [comment]
I've had that problem today ... sort of. 

CP v6.01.00399 downloaded yesterday
Lone Oak 19
Base-game Case Puma
Mod Krampe BB pack

The first course (combi mode) I set up to run over the silo unload point ... and the tractor didn't stop. I edited the course to go slower and run straighter and still it wouldn't stop.

The second course I put an unload point right on top of the silo: The tractor stopped, the trailer tipped up but it didn't unload.

I'll try to reproduce with a base-game trailer.

**Comment by Tensuko** [comment]
Do not use unload or wait points at triggers...
Also #3311  and #4286

**Comment by blue-painted** [comment]
Can I get mode 2 alpha?  

Mode 2 - combi unload - is pretty much the only thing I use Courseplay for, and the lack of unload on the move is why I've regretfully had to abandon Autodrive.

**Comment by Tensuko** [comment]
It is just a testversion for now. We hope we can release it soon.
