### ISSUE TITLE
CP Abfahrer wartet nicht am Durchfahrsilo auf Verdichter (Video)

### ISSUE THREAD

**Issue by 0TheRiddler0** [Courseplay/courseplay#5247]
Hallo zusammen

Hier erstmal das Video, das das Problem am besten beschreibt:

https://streamable.com/k9y43a

Ich kann den Abfahrer einfach nicht zum WARTEN überreden, bis der Verdichter zur seiner Warteposition gefahren ist.

Woran kann das liegen?

Ich arbeite mit der CP Version 399
Hab auch schon 370 probiert, aber genau das gleiche.

**Comment by tobi694** [comment]
ich habe genau das gleiche Problem mit einem Keil-Silo

**Comment by Tensuko** [comment]
#3311 #4286
