### ISSUE TITLE
no issue, ask for help, CP does not drive with Mod-Tractor - kein Issue, bitte um Hilfe, CP fährt nicht mit Mod-Traktor

### ISSUE THREAD

**Issue by haamic** [Courseplay/courseplay#5248]
Hello,
I have brought a tractor from LS17 to LS19 and converted it. 
There are no bugs in the log concerning the tractor. 
ingame it works as desired and it works with the normal helper. 
But if I try to follow a course with CP, it stops and there are constantly repeating error messages.

Error: Running LUA method 'update'.
courseplay/drive.lua:2059: attempt to perform arithmetic on a nil value

Is my tractor still missing something that CP absolutely needs? 
I hope somebody can help me and has decisive hints that will help to find a solution.
Enclosed the log
++++++++++++++++++++++++++++++++++++++++++++++++++
Hallo,
ich habe einen Traktor von LS17  in LS19 gebracht und umgebaut. 
Es gibt keine Fehler im Log bezüglich des Traktor. 
ingame funktioniert er wie gewünscht auch funktioniert es mit dem normalen Helfer. 
Versuche ich aber mit CP einen Kurs abzufahren, bleibt er stehen und es entstehen ständig sich wiederholende Fehlermeldungen. 

**Error: Running LUA method 'update'.
courseplay/drive.lua:2059: attempt to perform arithmetic on a nil value**

Fehlt meinem Traktor noch etwas, was CP unbedingt benötigt? Ich hoffe jemand kann mir helfen und hat entscheidende Hinweise, die zu Lösung beitragen.
Anbei das log

[errorlog.txt](https://github.com/Courseplay/courseplay/files/4535300/errorlog.txt)

**Comment by Tensuko** [comment]
Sind die AI Funktionen drin ? Also läuft der mit dem normalen Helfer ?

**Comment by haamic** [comment]
> ingame funktioniert er wie gewünscht auch funktioniert es mit dem normalen Helfer.

ja mit dem normalen geht es.
sind das die AI funktionen die du meintest? oder was noch?

**Comment by Tensuko** [comment]
Ja... Irgendwo hatten wir schon mal so ein thema weis aber nicht mehr wo das ist...

**Comment by haamic** [comment]
Schade. Vielleicht fällt es dir ja wieder ein, oder jemand anderem. Wäre schön zu wissen.
Hab auch schon gesucht aber war nichts zu finden im Netz.
Werd nochmal die xml anderer Traktoren anschauen, vielleicht finde ich ja irgendeinen Eintrag, der wichtig ist.

**Comment by haamic** [comment]
Erledigt, funktioniert jetzt. 
Ich hatte übersehen, das ich im LS19 gar keine Tankanzeige  über dem Tacho hatte.
hier wurde ich fündig:
[https://ls-modcompany.com/forum/thread/6047-tankanzeige-geht-nicht/](url)

Nun fährt er mit CP ohne Errors zu verursachen.
Worauf man nicht alles achten muss.
