### ISSUE TITLE
Hello somebody can help on this error? LevelCompactAIDriver.lua:208: attempt to index a nil value 

### ISSUE THREAD

**Issue by betrox007** [Courseplay/courseplay#5249]
just want to ask what this error mean?,LevelCompactAIDriver.lua:208: attempt to index a nil value 
[log.txt](https://github.com/Courseplay/courseplay/files/4536058/log.txt)

i attached the log so maybe somebody can figure out what i done wrong.
thanks for the hard work and bring the course play and still develop this script till now..

**Comment by Tensuko** [comment]
I would need more information as how does your course look like and what you wanted to do.
All waypoints on and post screenshots. Maybe I can help you then :)

**Comment by betrox007** [comment]
my apologize not describe whats going on, okay so i'm filling the BGA bunker,and for filling i use CP compact mode,and for the transporter, instead using mode 2, unload combine, i'm using mode 1 grain transport, load at silo then dump at BGA bunker,and for combine at field use cp field work as ussualy, and transport to silo using AD.
why i doing this, because what i see if using mode 2 directly unload to bunker, the Compactor at bunker can't stop for incoming transporter,and causing collision among them, but if using mode 1 the compactor can give the command stop for transporter, so the next transporter will stop if the transporter ahead of it not clear from bunker.

and for you know i'm using two compactor at same time but different bunker, the only setting is i reduce detection range, so they can't detect each other.

you can see at the picture attached my course setting.
thanks and best regards
![fsScreen_2020_04_27_17_22_58](https://user-images.githubusercontent.com/56646850/80363094-e8856f00-88ad-11ea-95f3-963e0fa51727.png)
![fsScreen_2020_04_27_17_25_04](https://user-images.githubusercontent.com/56646850/80363102-ecb18c80-88ad-11ea-9195-0098199ed333.png)

![fsScreen_2020_04_27_17_23_41](https://user-images.githubusercontent.com/56646850/80363098-ea4f3280-88ad-11ea-8f0e-7b2b7b4bbd2d.png)
![fsScreen_2020_04_27_17_24_48](https://user-images.githubusercontent.com/56646850/80363099-eb805f80-88ad-11ea-8f9f-42370f65b109.png)

![fsScreen_2020_04_27_17_22_33](https://user-images.githubusercontent.com/56646850/80363059-dc99ad00-88ad-11ea-8084-802788ba7582.png)

**Comment by Tensuko** [comment]
Could be in combination with the old Mode2 Driver, but not sure. Will take an eye on that one.

**Comment by betrox007** [comment]
thank you very much, on reply, and as i remember at version 00350 or around, the compact mode was working good that time, i will  upload the video for this case to my channel on YT and give the link so you can figure out what happen.
once again thank you for the hard work and effort for make this mod..

**Comment by betrox007** [comment]
https://www.youtube.com/watch?v=JJG_5dofrqo

**Comment by Tensuko** [comment]
Version 350 is way to old to look back till that version.
We will check on that if the new mode2 is there.

**Comment by betrox007** [comment]
Hello @Tensuko i think, this is happen, when we abort the transporter due to the transporter take a wrong course, you know some times, during the course, the transporter, collide with any obstacle, so we must stop the CP course from the transporter,then this message appear, but this is do not have any intact to the Compactor in bunker,the compactor still running,i figure out this thing, when use the newest version and doing the mode 2, everything running well,but when i stop one of transporter, because hit the obstacle, then this message appear, and at screen also appear message **dz** and countdown number..(Sorry i'm forget to take the screen shot)
thanks

**Comment by Tensuko** [comment]
Thats a good point but we will have to look at this mode anyway since some stuff is not working correctly, but maybe your hind is useful, thanks for that :)

**Comment by Tensuko** [comment]
For one Mode2 Driver I didn't had this Error and I did a lot of compacting last weeks.
I take this one as solved for now, untill we get into new Errors with this Mode.
