### ISSUE TITLE
ShovelModeAIDriver.lua:439

### ISSUE THREAD

**Issue by tobi694** [Courseplay/courseplay#5250]
Hallo, 

ich habe gestern die neue Version 6.01.00399 installiert und nun stürzt das Spiel immer wieder ab nach ein paar Minuten. ich kann nichts mehr machen, weder zwischen den Traktoren tappen, oder aus und einsteigen. 

Ich habe in der LOG Datei gesehen, das ein Problem mit Courseplay ist. 
Hier die Error Zeile 
2020-04-27 11:23 C:/Users/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00399/ShovelModeAIDriver.lua:439: attempt to index a nil value
2020-04-27 11:23 Error: Running LUA method 'update'.

**Comment by Tensuko** [comment]
Komplettes logfile als .txt anhängen und genauer beschreiben was lief an Fahrern...

**Comment by tobi694** [comment]
Hallo, 
hier die Log-File. 
Ich habe zudem noch zwei Videos gemacht, welche das Problem zeigen. 

Ich speile auf der NF Marsch 4 Fach ohne Gräben. 
Ich habe nach den neustart des Spiels alle Courseplay Helfer wieder aktiviert und wollte nach dem einen neuen Kurs einfahren, jedoch dann spielt das Spiel verrückt. 

Ich hoffe sie können mir helfen. 

Videos müssten bald in Youtube online sein. 
https://youtu.be/4rgWPW5hunQ
https://youtu.be/aBaNaxgAMs8

Danke. 

[log.txt](https://github.com/Courseplay/courseplay/files/4539219/log.txt)

**Comment by Tensuko** [comment]
Raus da in GC mit drin:
Load mod: FS19PlaceAnywhere (Version: 1.3) (Hash: b8a337c8a0ff6b08dcb7fbce1db0bfad)

Version 1.0.0.2 von CM Discord runterladen:
Load mod: FS19_addon_strawHarvest (Version: 1.0.0.0) (Hash: 1d15f60600f67db89fc72447145539f4)

Macht gerne Probleme:
Load mod: FS19_FollowMe (Version: 1.6.0.29) (Hash: e399c9089ef81c9179a21a215170f672)

Für eine Karte entscheiden (immer nur EINE Map im Modsordner...):
Load mod: FS19_NF_Marsch_4fach_oG (Version: 1.7) (Hash: fa3becafd3c694e654ee60d4198f7632)
Load mod: FS19_NF_Marsch_oG (Version: 2.5) (Hash: fe60d346dd9debf0a9df3ef313f9cc00)

Videos muss ich noch abwarten, werden noch verarbeitet.

**Comment by Tensuko** [comment]
Also was ich auf deinem ersten Silo sehen soll weis ich mal so garnicht...

**Comment by tobi694** [comment]
Dieses Video zeigt, das dieses Problem auch im Menü besteht. Das andere Video ist etwas größer, daher braucht Youtube etwas länger dieses hochzuladen.

**Comment by tobi694** [comment]
Ich finde das Addon Strohbergung nur mit V1.0.0.0. 
Könntest du mir den Link für die oben genannte Version teilen?

**Comment by Tensuko** [comment]
Man man man.... begebt euch selber mal anständig auf die Suche, dann findet man auch genug:
https://discord.gg/KffYxz

**Comment by tobi694** [comment]
Also jetzt wäre das zweite Video auch Öffentlich bei Youtube zu sehen.

**Comment by Tensuko** [comment]
Wie gesagt, die Videos helfen mir nichts.
Ich sehe nur was passiert wenn der Error kommt, aber nicht das was den Error auslöst...

**Comment by tobi694** [comment]
Ok ich werde morgen mal versuchen den Sachverhalt nochmals besser dar zu stellen.

**Comment by tobi694** [comment]
Ich habe heute einen Neuen Spielstand mit gleichen Mods, Einstellungen usw. angefangen und der Fehler taucht nicht mehr auf.

**Comment by Tensuko** [comment]
Ich nehme das mal als erledigt an.
