### ISSUE TITLE
Shovel Mode - Only shovelling right had side of bunker

### ISSUE THREAD

**Issue by maxresnikoff** [Courseplay/courseplay#5251]
I have set up a course to unload a bunker full of silage. It does the course absolutely brilliantly except the fact that when it enters the bunker, it sticks to the right-hand side - leaving all other silage in the bunker. Once it gets to the end of its 'right-hand lane preference', it completes the job and stops.

The screenshot below shows the (I'm assuming) target waypoint for the vehicle. As soon as it hits the first wait point, it points towards the right and hunts the right wall until it gets to the end. 
The screenshot also shows how it has left the entire left side untouched.

I have re-recorded 10+ times with different variants such as spacing, reverse manoeuvres etc, with no luck. 

Am I missing something? or is this a bug?

![20200427170750_1](https://user-images.githubusercontent.com/48560713/80394652-09e45c00-88aa-11ea-8680-eeb9d54959d2.jpg)

Running Version: 6.01.00399
[log.txt](https://github.com/Courseplay/courseplay/files/4540874/log.txt)

**Comment by Tensuko** [comment]
Yea that red part is the target, maybe there is a tiny bit stuck inside the wall what he kept aiming.
This mode is rly not perfect and need adjustments...

**Comment by maxresnikoff** [comment]
Yeah I created a course from the other end in the hope it would bear to the right and get the last bit, and it didn't go to the same which the original course kept going to. So doubt there is anything stuck in the wall.

Luckily I have an open bunker!

**Comment by Tensuko** [comment]
Would just try the newest Version, I had very good results with .00064 and Shovel Mode2.
Keep in mind that, as soon as there is a tiny bit left inside the wall (yea this is a real struggle...) it will try to get that one again and again...
