### ISSUE TITLE
Ordnerstruktur funktioniert nicht

### ISSUE THREAD

**Issue by McGamer1998** [Courseplay/courseplay#5252]
Hallo,

mir ist bekannt, dass der Mod derzeit noch nicht für den Multiplayer optimiert wurde. Wir haben ihn dort ausprobiert und vieles scheint im Multiplayer auch zu funktionieren.

Um die gespeicherten Kurse zu sortieren (da mehrere Farmen genutzt werden) nutzen wir die Ordner. Leider sind diese nach einer gewissen Spielzeit immer wieder komplett durcheinander... was sehr schade ist, da man alles nur schwer wiederfindet. Da es keine Löschen-Funktion (das wäre auch ein sehr praktisches Feature) gibt, haben wir einen Ordner "Müll" erstellt. Besonders bei diesem Ordner ist es natürlich sehr lästig, dass diese immer wieder in andere Ordner rutschen oder sogar ganz aus dem Ordner rutschen. 

Ich und auch meine Mitspieler würden sich sehr über ein Fix dieses Problems freuen!

Viele Grüße

Patrick

**Comment by Tensuko** [comment]
Collecting all in #5484
