### ISSUE TITLE
Tipper not lowering after tipping grass/chaff

### ISSUE THREAD

**Issue by ConstructionGamer** [Courseplay/courseplay#5253]
When using the Grain Transport mode to transport grass/chaff to bunkers, both open ended and closed, after tipping at the tip trigger, the tractor drives off without attempting to lower the tipper. I have been using the Broughan Twin Axle, but I also tried the Agriliner just to check it wasn't an issue with the mod. Haven't tried a push eject trailer yet as I prefer to use tippers. 

The course set up did work fine with an older version of Courseplay. I updated to 6.01 after not playing FS19 for a while.

**Comment by Tensuko** [comment]
6.01 is all Versions....
6.01.399 ?

Where you downloaded it from ?

We have an Issue with this, we know it, but we also might have a fix, but we got to do other things 1st before we try out that fix.

**Comment by ConstructionGamer** [comment]
Apologies didn't take a note of the full number, using 00398. I always download from this site.

**Comment by Tensuko** [comment]
Pro Tip for your Comeback:
https://github.com/Courseplay/courseplay/releases
with Releasenotes.
Under Assests, the .zip file and I would rename it to FS19_Courseplay.zip (no packing and unpacking).

Also you can try out the AutoUpdater:
https://github.com/Courseplay/courseplay/issues/5135

**Comment by ConstructionGamer** [comment]
Thanks for your quick reply. I have now updated to 399, still same issue, but I see you say it's a known issue so won't bug you. Will patiently wait for a fix :). Having just updated there may be another issues though, or something I'm doing wrong. 

Still using Grain Transport the tractor returns to the way point at the end of the course, where I would like it to wait. But instead it tries to repeat the course. I have it set to grass, fill at 100%, stop at waypoint/trigger is on and I have even set it to only repeat once, 

I manually chase the forage harvester myself, would just like the tractor to drive to bunker unload and then return to trigger.

**Comment by Tensuko** [comment]
Mode1:
- Place your Tractor so the Trailer is under the Pipe
- Start Record Course and drive forward a bit first so the 1st 2 waypoints are straight (works the best)
- Continue Drive over the Trigger where you want to unload (do not place any wait or unload waypoints) - ( Or drive where you want it to tip on the ground and place an unlaod here waypoints )
- Drive back to your loading spot, but stop the course a few meters infront of the loading trigger

Thats how Mode1 works and thats how it rly (should) work without Issues.
Note: CP in MP got a lot problems so this is all for SP

**Comment by ConstructionGamer** [comment]
That method is definitely easier. I do use a slightly different course and maybe not how it's intended to be used. But I start from a field in which I'm working with a forage harvester and then tip grass/chaff into a bunker. As suggested using Grain Transport but without tip or way point triggers in the bunker. Then on the return to the field I do use a trigger to stop the tractor in the field, which works fine. 

The trailers do tip, but a problem I had, with an open ended silage bunker, the trailer doesn't begin to tip until it's half way in, the tractor then drives forward and leaves half of the load of grass/chaff in the bunker and half outside the bunker. Also with both open and closed silage bunkers, using the method you suggest, the tippers don't lower and I tried a push eject trailer, which leaves the back door open.

I'll leave it there. don't want to bother you too much. I know I'm not exactly using Grain Transport how it's intended. FS19 wouldn't be the same without Courseplay :)

**Comment by Tensuko** [comment]
Old Version and sounds ok for now.
Closing to keep Issues clean.
