### ISSUE TITLE
Dont unload shovel into triggerpoint

### ISSUE THREAD

**Issue by Denstorebandit** [Courseplay/courseplay#5254]
Hey, starting up my sawwork and dont know what i did wrong on the route?

CP keep stop at the waypoint before the trigger, setting itself in preunload position

Should be the newest CP xxx.399

![CP issue](https://user-images.githubusercontent.com/44508259/80539564-00411e00-89a8-11ea-9a36-4f66af1c06ad.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4548590/log.txt)

The triggerpoint works just fine with manual unload of bark/woodchips

**Comment by Denstorebandit** [comment]
Btw, no mans land map

Mods:
Courseplay
 FS19 Placeable Sawmill Pack 1.1.0.0 
Global Company (from modhub)

**Comment by Tensuko** [comment]
The first Problem is, that the waitpoint need to bit closer or in the tigger, just like for Trailers.
The second Problem is, that the Shovel Mode doesn't work for GC Triggers yet and I didn't had time to find out why, but we will definitly work on it.

**Comment by Denstorebandit** [comment]
Thanks for the fast reply, il look forward to the GC trigger working. 

I may have missed that post telling it wouldnt work.

Otherwise ty for a great mod!

*ill have to to get my hands dirty now and do manual labor

**Comment by Denstorebandit** [comment]
Wasnt pretty, but managed to get courseplay to load the wood powerplant, with the help of conveyerbelt and a manual unload here spot from a tractor/trailer setup..

![billede](https://user-images.githubusercontent.com/44508259/80577105-9c9a0d80-8a06-11ea-938d-2161e5707f25.png)
