### ISSUE TITLE
Mode 1

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#5255]
Apologies if this has been mentioned before

Im currently running manure from cow shed to BGA sell point using mode 1. Firstly the tractor doesnt stop and wait to be loaded it just drives on. Secondly when the load has been tipped at BGA i get a message saying 'farmsilo is full move onto next one'. 

Im using the Grimme quantum autoload belt to load the trailers and ver.397 on Eiersholt.

Oh and the beacon lights dont seem to work in mode one either
[log.txt](https://github.com/Courseplay/courseplay/files/4554505/log.txt)

**Comment by Tensuko** [comment]
How does your course look like ?

**Comment by kwguk** [comment]
Iv resolved it. I redid thecourse and it world fine

Close please
