### ISSUE TITLE
BaleWrapper folding when looping

### ISSUE THREAD

**Issue by DSul3791** [Courseplay/courseplay#5256]
Multiplayer simple single loop.

Base game wrapper the Kuhn sw 40??
Disable stop at next point

Expected behaviour the wrapper starts, unfolds, drives around continuously wrapping any bales that get in its path.

What actually happens - on the first pass everything works fine until it reaches the end crossing the stop and start then it folds and keeps going. Won’t reopen.

**Comment by DSul3791** [comment]
Additional info - only the BaleWrapper does this. Not the balers.

**Comment by Tensuko** [comment]
#5055

**Comment by DSul3791** [comment]
Please close this. I updated to the newest dev version and its fixed. thank you have a great day.
