### ISSUE TITLE
Question on fill type

### ISSUE THREAD

**Issue by dp-github** [Courseplay/courseplay#5257]
I am using a [mod that adds silos that output silage](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=146545&title=fs2019).  

When I develop a grain transport course that puts a silage-ready trailer under a silage silo, I receive the courseplay message `COURSEPLAY_FARM_SILO_NO_FILLTYPE` ("Farm silo doesn't have the selected fill type").

Does this suggest a problem with the silo mod?  

Could it be worked around inside courseplay:load_tippers?  If so, I'd appreciate any suggestions on how to approach this, and I'll begin exploration from there.

Thanks!

**Comment by Tensuko** [comment]
What mode do you use and if mode1 do you even know how it works ?

**Comment by dp-github** [comment]
Grain transport mode.

**Comment by Tensuko** [comment]
You have to choose what filltype cp should load.

**Comment by dp-github** [comment]
Of course, thank you. 

I've made that change, and the error message has disappeared.  The course is still not performing the way I expect (silo at start of course is not filling), but I will pursue local troubleshooting to try and resolve.

**Comment by Tensuko** [comment]
Place tractor with trailer under the pipe/in the trigger. Start record the course and make sure to drive a bit in a straight line so the 2nd waypoint is a bit ahead of the start.
Then drive the course and stop a few meters infront of the loading silo.

**Comment by dp-github** [comment]
I have created six Mode1 courses for 6 silos, all of the same type (mod) and content (silage).  All using the same tractors and wagons.

I find on 2 of these courses, CP automatically loads the wagon from the silo.

On the other 4 courses, CP does not automatically load the wagon, but it does wait underneath the silo.  If I press "R" to unload the silo, the wagon fills, and when it reaches the appropriate %, CP drives away and completes the course.

What might I do to help troubleshoot this problem?

**Comment by dp-github** [comment]
If it is helpful:  All courses start directly underneath the silo, and the course completes a few meters behind the starting point.

**Comment by dp-github** [comment]
With instructions, I'd be happy to collect and provide debug logs.

**Version** 6.02.00027.dev
**Silo type:**  Fermenting Silo T800
**Tractor:**  Massey-Ferguson 8737
**Trailer:**  Schuitemaker Rapide 8400W

**Comment by dp-github** [comment]
I noticed something just now:  the two correctly-functioning courses enter their from its rear entrance while the failing four silos enter from the front.   The front side of these silos have two overlapping trigger points (one for silage, one for digestate).  Perhaps that's part of the issue?

I'll reverse some of the other courses and see whether they start working.

**Comment by dp-github** [comment]
Indeed, I have confirmed that the "Fermenting Silo T800" will automatically unload only if the trailer approaches from the rear.

I do not know the cause of this - perhaps it is because the front of this silo has two trigger points that supply different products?

**Comment by Tensuko** [comment]
That could be the reason.

**Comment by Tensuko** [comment]
Make sure the stop looks like this so you won't end up in the other trigger.
Also I think there was a fix for this in any commit. V31 seems to work just fine.
![fsScreen_2020_06_19_14_25_56](https://user-images.githubusercontent.com/27344744/85132367-ecdc6180-b238-11ea-9cf3-97bc36fb250f.png)
