### ISSUE TITLE
Question: AD courses on AD

### ISSUE THREAD

**Issue by masneoquil** [Courseplay/courseplay#5258]
Hello

Sorry to ask this but I've looked everywhere and I couldn't find an answer.
I've read here on an old issue  4108, about CP importing AD courses.
I've exported the courses using AD but I don't seem to find how to import it to CP.
Any help would be appreciated. 

Thanks so much!!!

**Comment by Merrlin** [comment]
If AD and CP are both present at the same Time there is a Special Folder in the CP Course Manager.
In that folder you will find the AD Courses.
There is no need or possibility to Ex- and Import AD courses.

**Comment by masneoquil** [comment]
Yes, they are both present at the same time. I usually use AD to refill and as a combi mode.
But there is no Special Folder. Only the ones I created.

**Comment by masneoquil** [comment]
I did a test with only CP and AD on a default map, ando no folder either

**Comment by Tensuko** [comment]
Do you have an AutoDrive Network with Targets then ?
Screenshot of the Course Manger and a full logfile pls.
I don't even know wich CP or AD Version you use...

**Comment by masneoquil** [comment]
Sorry, I didn't think it was a bug.
The screenshot it is with the latest CP release and the latest AD RC.
It is a heavy modded game. But I did tried with only CP and AD.
[log.txt](https://github.com/Courseplay/courseplay/files/4561766/log.txt)

![Screen](https://user-images.githubusercontent.com/53353740/80766318-8b8ef080-8b1b-11ea-947a-a328311f6178.jpg)

**Comment by Tensuko** [comment]
Do not Name it like this...
aaFS19_AutoDrive -> FS19_AutoDrive
aaaCoursePlay6 -> FS19_Courseplay

**Comment by Tensuko** [comment]
Also update straw harvest to 1.0.0.2 Beta from CM Discord

**Comment by masneoquil** [comment]
Aaaand that did it!! 
Thanks so much for your time.
![Screen](https://user-images.githubusercontent.com/53353740/80770019-64d5b780-8b25-11ea-9db9-887269879c63.jpg)
