### ISSUE TITLE
Premos 5000 not detected by combi helper

### ISSUE THREAD

**Issue by s187375** [Courseplay/courseplay#5261]
hello,
I currently have the latest SH addon beta and latest CP version.
I noticed that the Premos 5000 doesn't get detected in the "Manage combines" window of the helper in combi mode . Other combines, modded and vanilla, get detected with no issues.
The premos has the automatic refill option active.

In the previous version of cp there was the option to manually select the Premos, but when the helper had to start other issues occurred (the game stopped responding). Didn't try automatic detection.

![fsScreen_2020_04_30_23_15_17](https://user-images.githubusercontent.com/62856466/80760005-7e342f00-8b38-11ea-9330-ce629ca0036b.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4561343/log.txt)

**Comment by Tensuko** [comment]
The branch is still WIP, stick to release version for now:
https://github.com/Courseplay/courseplay/releases
