### ISSUE TITLE
Courseplay_6_01_00399/triggers.lua:461: attempt to index field 'storages' (a nil value)

### ISSUE THREAD

**Issue by aimrabbit** [Courseplay/courseplay#5265]
Hi,
I have the problem that if I have generated the course and want to activate the helper, the helper is doing nothing and I'm getting errors in the Log file attached below.
It's a MP Server, Map 4FachMarsch.

Thanks for helping

[log.txt](https://github.com/Courseplay/courseplay/files/4562563/log.txt)

**Comment by aimrabbit** [comment]
I removed some of the errors from the log but the problem is still there.
Here is a second Log with less errors. I hope it will help solve the error.
[log2.txt](https://github.com/Courseplay/courseplay/files/4564717/log2.txt)

**Comment by aimrabbit** [comment]
I test a little bit and the problem seems to be only with a dedicated server. If you create a multi-player game and you self are the host everything is working so far.

**Comment by Tensuko** [comment]
Collecting all in #5484
