### ISSUE TITLE
traffic collision way to big

### ISSUE THREAD

**Issue by Friendlyx** [Courseplay/courseplay#5267]
what do I have to change to not get this collision warning? Seems to happen only to the MB Trac at least it is not affecting my other John Deere
![fsScreen_2020_05_01_16_35_58](https://user-images.githubusercontent.com/6493968/80814278-e08a3f80-8bcb-11ea-9cd6-580be90c2a96.png)

**Comment by Tensuko** [comment]
I would do more preturns.
We hope to have a new colission system working in all modes one day to solve this and other Issues but we will see.

**Comment by Friendlyx** [comment]
ok then my only chance is to do more than the already 4 rows headland.
