### ISSUE TITLE
Manual Width

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#5268]
Whenever i use the manual width calculator the red line indicating width wont disappear,even when i take the piece of equipment off. Its like its 'stuck' to the tractor. Ive tried both vanilla and mod tractors and get the same result.

![fsScreen_2020_05_01_15_48_22](https://user-images.githubusercontent.com/11178621/80815757-25ab7300-8bc6-11ea-9653-7eed5fdad611.png)
![fsScreen_2020_05_01_15_49_34](https://user-images.githubusercontent.com/11178621/80815771-2b08bd80-8bc6-11ea-8245-b1dfe4381fa4.png)
![fsScreen_2020_05_01_15_48_49](https://user-images.githubusercontent.com/11178621/80815798-35c35280-8bc6-11ea-8742-741d5b4371f8.png)

**Comment by Tensuko** [comment]
logfile ? ...

**Comment by kwguk** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4564870/log.txt)

**Comment by Tensuko** [comment]
REA Mod ist ds Problem.
Das Pfuscht bei vielen Visuellen Anzeigen bei uns rein, auch beim Kurseditor.
Da können wir nichts machen.
