### ISSUE TITLE
Convoy distance to next implement shows too great

### ISSUE THREAD

**Issue by aviator64** [Courseplay/courseplay#5271]
Situation: Three harvesters working a field. The second harvester shows the correct distance behind the first harvester.
The third harvester shows much too great a distance behind the second harvester. Please see attached screen shot. The third harvester will run right into the second harvester because its displayed distance never reaches the limit.
Also, not sure if this is related, but when the third harvester was started on the course there was a significant freeze/pause (5-6 seconds) before it started to move.
This is consistently repeatable, even after a reboot.
What debug channels do you need?

![fsScreen_2020_05_02_05_57_19](https://user-images.githubusercontent.com/19857526/80861183-dbb0a480-8c3a-11ea-95c2-5fa202d4365b.png)

**Comment by Tensuko** [comment]
#5054
