### ISSUE TITLE
New Mode 2

### ISSUE THREAD

**Issue by pvaiko** [Courseplay/courseplay#5272]
Hello Folks,

We know you have waited a very long time for this moment, after many hours of testing, many setbacks, developers leaving, we finally have now a Mode 2 version that runs somewhat stable so we decided to merge it to our master branch.

We can't tell you that it will work in all possible situations but we tested as many as we could. Now it is your turn to test things out.

But don't get too excited.

We decided to follow a staged approach, adding new functions in small steps. What we have here now on master is what software people call 'minimum viable product', so many features are still missing. We'll get there, but first let's make this stable.

### What works: ###
- Unloading a stopped combine ('stop for unload' is forced and combine will call unloader only if 100% full)
- Following a chopper
- Send driver to unload course
- We highly recommend to use at least 2 headlands
- Automatic distribution in drive through silos (record a straight line in the middle, maybe we look into a solution for wedge silo)

### What is deactivated/doesn't work for now: ###
- Multiple unloaders. You can assign more than one, but they may not be able to handle conflicts in a civilized manner.
- Combines/choppers have to be driven by a Courseplay helper. We aren't sure yet if we want to allow other (or manual) drivers, we'll see.
- <del> No Mode3, will come later</del>
- <del> Unloader won't drive to the combine until the combine is 100% full</del>

### How does it work: ###
- Be in a tractor with trailer that can use Mode 2
- Open the Combine Management page in the HUD
- Check the box with the combine you want to unload
- Select 'Unload' as a starting point to wait for the combine requesting an unloader, any of the other option will make you start on the unload course
- This Video of our Testsavegame might help you: https://youtu.be/PiUWD8ki8l4

### How to report a problem with Mode 2 ###
- **First of all, read the [FAQ](https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ)**
- A log file with debug channel 4, 7 and 14
- Screenshot of the situation with debug channel 4, 7 and 14 and all waypoints on (the 3 dots in CP HUD settings)
- What you expected 
- What happened

To preserve our sanity, any issue that does NOT have the above information or ask for information contained here will be instantly closed!

### Mode 2 worked fine in FS17, why did we change it? ###

Courseplay evolved and grew through many years and as many long running projects in the IT world, it became unmaintainable due to the tight coupling, no coherence and minimal encapsulation. Unmaintainable code means everything takes a lot longer than it should be, no new developers will want to touch the code as they fear they'll break something and it is a lot harder to add new features. We hope this will now change, just bear with us, on the long term it will pay off both for you, the users and for us, the developers.

**Comment by blue-painted** [comment]
I really, really, really hope that mode 2 gets back to a state where it will unload a manually driven combine that's moving.

**Comment by 0Pietro20** [comment]
Through various tests I have noticed that the tractor, standing next to the thresher, tends to go too far forward, preventing the latter from unloading correctly. Unfortunately I had activated only in debug channel number 4, if necessary I will repeat the test and activate the others.
I attach photos:
The first three show how the tractor moves forward by unloading the forage harvester at times or, at times, going too far and blocking the whole path

![Farming Simulator 19 16_05_2020 11_44_08](https://user-images.githubusercontent.com/59969508/82116774-64b3f980-976c-11ea-8bd6-d5b3d01a3298.png)
![Farming Simulator 19 16_05_2020 11_44_12](https://user-images.githubusercontent.com/59969508/82116775-667dbd00-976c-11ea-9590-0c7ec273be81.png)
![Farming Simulator 19 16_05_2020 11_45_32](https://user-images.githubusercontent.com/59969508/82116778-6978ad80-976c-11ea-91cd-63a4dcfd6492.png)

In my opinion this would be the best position (the tractor and forage harvester cabin at about the same level) as shown in the photo:

![Farming Simulator 19 16_05_2020 11_46_12](https://user-images.githubusercontent.com/59969508/82116867-e99f1300-976c-11ea-8142-4cc2fda0d608.png)

The game log:
[log.txt](https://github.com/Courseplay/courseplay/files/4638170/log.txt)

**Comment by turbodani** [comment]
> I really, really, really hope that mode 2 gets back to a state where it will unload a manually driven combine that's moving.

They fucked it up and didnt even care about it.

**Comment by dennisblack777** [comment]
> > I really, really, really hope that mode 2 gets back to a state where it will unload a manually driven combine that's moving.
> 
> They fucked it up and didnt even care about it.

@turbodani Don't be so disrespectful! The devs put their free time into the project for us here and it's still a beta.

**Comment by LesMinton** [comment]
So, did I misunderstand the new Mode 2? I ask because I followed the steps, and when my tractor goes to unload the combine, it goes to the wrong side of the combine, at top speed (not the field speed I have set) and starts ramming the header, forcing the combine off the path. Where the tractor will then stop, because I have stopped the combine. 

So far, I am not seeing that something was fixed, unless it was something that I dont use and what I DO use (mostly unload combine to silo) appears to not be working.

Can someone tell me what I am doing wrong, maybe repeat the steps more clearly, even though I thought that was pretty clear.

Failing this, can I be pointed in the direction of a version before the Mode 2 fix?

**Comment by Tensuko** [comment]
> So far, I am not seeing that something was fixed

There was nothing fixed becouse it is all new.
Since you not show us what you did, we can't tell you what you did wrong.

**Comment by LesMinton** [comment]
I tested on a different, cleaner map (I have many hours and a lot of equipment on the one I was using), and it worked flawlessly. Therefore I see it is something with the way I set it up, or the equipment doesnt like CP, but at least now I know a little more about what I was doing.

Sorry for any attitude I might have put out, this CP project is amazing.

**Comment by gyerli** [comment]
Hey guys, great work. Big fan of CP. Kudos to all of the developers working on this voluntarily. Quick question...
What is the ETA for this bug fix? (i.e. Unloader won't drive to combine until combine is 100% regardless of what "start at %" value on the unloader). 

Also, I'd like to help you by donating. The PayPal [here](https://courseplay.github.io/courseplay/en/index.html) still legit?

**Comment by Tensuko** [comment]
> What is the ETA for this bug fix? (i.e. Unloader won't drive to combine until combine is 100% regardless of what "start at %" value on the unloader).

This might need an update. The % is already working, but you need to keep some rulse in mind:
- Combine should be on 'Avoid Fruit active'
- We don't unload at given % on 1st Headland, Combine will make a Pocket for the Unloader to have enough space
- We don't unload when Pipe is in the Fruit, but trying to get the next best position to unload to meet with the Combine and Unload.


> Also, I'd like to help you by donating. The PayPal [here](https://courseplay.github.io/courseplay/en/index.html) still legit?

Still legit, just the Website is a bit outdated.

**Comment by gyerli** [comment]
> * Combine should be on 'Avoid Fruit active'
> * We don't unload at given % on 1st Headland, Combine will make a Pocket for the Unloader to have enough space
> * We don't unload when Pipe is in the Fruit, but trying to get the next best position to unload to meet with the Combine and Unload.

I checked all of those but still not working for me. May be b/c I'm using 2 combines and 2 unloaders. Let me try to get the logs and screenshots.

**Comment by Tensuko** [comment]
One Unloader per Combine currently.
There are some Issues labled with Mode2 if you can't find a specific one to post logfile, make a new one.
Remember to turn on the Debugchannels.

**Comment by blue-painted** [comment]
The initial post says:
"Combines/choppers have to be driven by a Courseplay helper. We aren't sure yet if we want to allow other (or manual) drivers, we'll see."

This still seems to be the case in 6.02.000637 (just seen that 000639 is current but don;t see any Mode.2 changes)

Is there any info on if this decision is final? And if so, I'd be very interested to know why the decision was made this way and if there is anything I could do to change it? I'm a reasonably competent C#/Typescript/JS/Pascal/Asm86 programmer.

**Comment by pvaiko** [comment]
@blue-painted The reason is that the developer who started mode 2 left CP. We have full time jobs and families, can't spend an unlimited time with CP either. Mode 2 is the most complex and time consuming part of CP (especially testing) and it seemed to be easier to implement this way as we know what the combine is doing and the unloader and the combine can coordinate their actions, which is not the case with a human driver. 

CP is an open source community project so anyone who can write reasonably good quality code is more than welcome to contribute. It probably wouldn't be too big of an effort to implement what you want.

**Comment by Tensuko** [comment]
Basically, you need some kind of 'Commands' to tell the unloder what he got to do, at least for chopper:
- Start
- Stop
- Drive to Unload Course
- Back up (to make room)

Not sure if we have more situations where you got to tell him what to do.
The Side to unload he find automatically.

**Comment by senseless93** [comment]
Just an idea for unloading player driven combines...

What about calling the unloader and requesting the player to stop the combine for unloading? 
On the other hand, what is the problem with player driven combines and choppers? Just out of curiosity...

**Comment by Tensuko** [comment]
> What about calling the unloader and requesting the player to stop the combine for unloading?
Would be a step backwards, won't happen like that.


> On the other hand, what is the problem with player driven combines and choppers? Just out of curiosity...
The Interaction between Combine and Mode2 Driver.

**Comment by blue-painted** [comment]
The CP-Combine "knows" where it is going to drive, and turn and reverse and so on, so the Mode2 driver can "know" where to rendezvous and how to get there. With a player driven combine Mode2 driver has no idea.

**Comment by pvaiko** [comment]
@senseless93 as @blue-painted said, and it is certainly doable what you are proposing, we can dumb down our CP combine driver to a passenger in the player driven combine, just be there to answer the Mode 2 driver's questions if it can. 
From a development perspective our biggest problem is testing, it takes a lot of effort as we'd have to drive the combine ourselves, I personally prefer to spend my time on other areas with a better cost/benefit ratio.

**Comment by rikilamaru** [comment]
bring back original mode 2 were you can drive forage harvesters!

**Comment by rikilamaru** [comment]
cause new one is complete and utter bullshit

**Comment by rikilamaru** [comment]
> @blue-painted The reason is that the developer who started mode 2 left CP. We have full time jobs and families, can't spend an unlimited time with CP either. Mode 2 is the most complex and time consuming part of CP (especially testing) and it seemed to be easier to implement this way as we know what the combine is doing and the unloader and the combine can coordinate their actions, which is not the case with a human driver.
> 
> CP is an open source community project so anyone who can write reasonably good quality code is more than welcome to contribute. It probably wouldn't be too big of an effort to implement what you want.

then why just leave mode 2 as it was before and instead of actively screwing over dairy/silage player who want to drive the dam forage harvester like come on it wasnt broken

**Comment by rikilamaru** [comment]
completely un needed change

**Comment by rikilamaru** [comment]
> @senseless93 as @blue-painted said, and it is certainly doable what you are proposing, we can dumb down our CP combine driver to a passenger in the player driven combine, just be there to answer the Mode 2 driver's questions if it can.
> From a development perspective our biggest problem is testing, it takes a lot of effort as we'd have to drive the combine ourselves, I personally prefer to spend my time on other areas with a better cost/benefit ratio.

so your say your to goddam lazy? should of just kept original mode 2

**Comment by senseless93** [comment]
> > @senseless93 as @blue-painted said, and it is certainly doable what you are proposing, we can dumb down our CP combine driver to a passenger in the player driven combine, just be there to answer the Mode 2 driver's questions if it can.
> > From a development perspective our biggest problem is testing, it takes a lot of effort as we'd have to drive the combine ourselves, I personally prefer to spend my time on other areas with a better cost/benefit ratio.
> 
> so your say your to goddam lazy? should of just kept original mode 2

Idiots like you are the reason devs like the cp ones stop theur work. 🤦🏻‍♂️
