### ISSUE TITLE
HUD disappears when using towed harvester

### ISSUE THREAD

**Issue by MicaelJarniac** [Courseplay/courseplay#5274]
[Log](https://pastebin.com/n2SwN2KK)
[Video](https://drive.google.com/file/d/1V6d80aKWdKjRktK3FE8wmFKRqSl3GiU0/view?usp=drivesdk)

CP v6.02.00001

When using a ~~trailer~~ towed harvester (I don't remember what it's called, but it's a harvester that requires a tractor pulling it), the HUD disappears if going into the first tab (for combine unloading), but it's still possible to interact with it while it's invisible.

**Comment by Tensuko** [comment]
Will take a look at it.

Some Infos about your log:
You need to get the Beta Version from CM Discord:
Load mod: FS19_addon_strawHarvest (Version: 1.0.0.0) (Hash: 1d15f60600f67db89fc72447145539f4)

Is known for causing trouble with CP:
Load mod: FS19_FollowMe (Version: 1.6.0.29) (Hash: e399c9089ef81c9179a21a215170f672)

This is integrated in GlobalCompany (throw it out):
Load mod: FS19PlaceAnywhere (Version: 1.3) (Hash: 11b65320d12e68e420ea60d91bce11ab)

Doesn't work with CP at least you can't load and unload with CP with this (Wopster knows it and will work on it):
Load mod: FS19_manureSystem (Version: 1.0.0.0) (Hash: f6e43e963a789d956eb7c4212c305a4c)

Not sure about some other of your Script Mods...

**Comment by pvaiko** [comment]
Yeah, looks like our handling of towed harvesters isn't there yet ...

**Comment by MicaelJarniac** [comment]
@Tensuko thanks for the heads up!
I haven't used Straw Harvest much, but I'll look for the newer version!
As for Follow Me, I just leave it there in case I need it, but I never actually did. I'll consider removing it.
Place Anywhere was just left in the installed mods, but it wasn't activated on my saves. I've already removed it.
Manure System is another one I never used, but I have it active because I was curious on how it works. Never caused me problems but I also never used it, I'll probably remove it for the time being too.

@pvaiko is it actually a bug then? :o I'm happy to have found it then! By the way, I couldn't figure out how to tag the issue, is it something that only people with high perms can do?

**Comment by MicaelJarniac** [comment]
I believe it's fixed now. At least, the HUD seems to no longer disappear, so I'll close this issue.

Thanks for everything! ❤️
