### ISSUE TITLE
krone premos not working properly

### ISSUE THREAD

**Issue by evert350** [Courseplay/courseplay#5275]
When I start the course, the Pick-Up doesn't lower by itself and the premos is not turned on. When the premos is full it does not raise the pipe to be unloaded. I have to do it manualy and after overloading, start the course again.

is there a way to solve this, or is this something to be fixed yet?

Regards

**Comment by Tensuko** [comment]
Make sure to buy/set up everything with automatic refill supplies for now.

Note that for the Premos 5000 to work correctly (turn on when the Courseplay
driver starts) you'll need an updated version of Straw Harvest Addon (Version 1.0.0.2)

**Comment by evert350** [comment]
where do i find the updated version 1.0.0.2.?

**Comment by Tensuko** [comment]
On Discord of Creative Mesh.
