### ISSUE TITLE
Tutorial da nova versao6.02

### ISSUE THREAD

**Issue by erksartori** [Courseplay/courseplay#5276]
Tudo joia galera. Sempre estou utilizando a nova versao, e de repente, nada funcionou. Coisa simples, descarregar a ceifadeira e descarregar no silo. Alguem tem algum video explicando como fazer agora.

Agradeço

**Comment by Tensuko** [comment]
Choose the Combine you want to unload in the Combine Manager Menu.

**Comment by Decypriano** [comment]
Estou com o mesmo problema, conseguiu resolver?

**Comment by Tensuko** [comment]
Can you guys switch to english pls...

**Comment by Decypriano** [comment]
I have the same problem, managed to solve? Tractor not edta following harvester to unload.
translation into english by google.

**Comment by Tensuko** [comment]
![Unload Combine](https://user-images.githubusercontent.com/27344744/80918180-fb8fb780-8d63-11ea-9c82-4fa6666cd3fd.png)

**Comment by Decypriano** [comment]
even if the tractor is marked, it does not follow the harvester.

**Comment by Decypriano** [comment]
I am using the route created in the interior version. Should I create a new route?

**Comment by Tensuko** [comment]
What do you expect to happen ?
What Harvester ?
Is the Harvester full and wait for unloader ?

**Comment by Decypriano** [comment]
the combine is not calling the tractor with a trailer to unload and proceed to the silo

**Comment by Tensuko** [comment]
Still don't know whats going on.....
Combine is running.
Set up the Mode2 Driver as in the picture and start it with unload if you are at the Field or any other option if you are far away from the field and want it to drive to the field.
Wait till combine is full, then combine will call the Mode2 driver. Thats all.

Else make screenshots and discripte it in more detail.

**Comment by Decypriano** [comment]
![1](https://user-images.githubusercontent.com/64737947/80921157-f83c0200-8d4a-11ea-82bf-347a6972dd25.png)

**Comment by Decypriano** [comment]
I think I could have a video explaining if possible.

**Comment by Tensuko** [comment]
Turn on debugchannel 4 and make a screenshot again.

**Comment by Decypriano** [comment]
![2](https://user-images.githubusercontent.com/64737947/80924748-24627d80-8d61-11ea-89f3-b110e95cf616.png)

**Comment by erksartori** [comment]
Bom fiz um, video. por favor me mostre o que esta de errado.
Well I did one, video. please show me what's wrong.

Neste vídeo, eu criei um a rota, e selecionei conforme solicitado acima, coloquei pra ele ir descarregar em 40%, mesmo assim nada dele ir buscar, fui na ceifadeira e cliquei pra chamar  e nada. 
In this video, I created a route, and selected it as requested above, put it for him to unload at 40%, even then nothing for him to get it, I went to the reaper and clicked to call and nothing.

Segue vídeo:
Here is a video:

https://youtu.be/277lYgAYnCE

log:
[log.txt](https://github.com/Courseplay/courseplay/files/4574565/log.txt)

**Comment by Tensuko** [comment]
Combine will only Call the Driver when it is full.
The 40% is not working right now and might get replaced by a more intelligent System.
The Field Selection is only a Filtersystem to find Combine on that specific Field.

Everything else look right. A few more minutes and you should have seen the Driver unload the Combine at the End of the Field :)

**Comment by erksartori** [comment]
OK vou fazer num campo maior e vamos ver. 
OK, I'm going to do it in a bigger field and we'll see.

**Comment by erksartori** [comment]
Fiz o teste e nada, mesmo problema, segue o video:
I did the test and nothing, same problem, follow the video:

https://youtu.be/6QWtOivMx94

LOG:
[log.txt](https://github.com/Courseplay/courseplay/files/4576257/log.txt)

**Comment by TinyCrocodile** [comment]
Is your combine a normal helper? 
It seems in the video but i dont understand. 
New mode2 only works when combine is a cp driver. As far as i know.

**Comment by Tensuko** [comment]
Still low Quality but maybe you can see how it should work:
https://www.youtube.com/watch?v=895zpaeE8iU

**Comment by TinyCrocodile** [comment]
Wow! Thank you for the video! So one can unload multiple combines on different fields with one driver. Sweet! 
I lost big chunk of cp development lately..
A mode 2 course is no longer needed to start and end inside field boundaries. I did not know that.

**Comment by erksartori** [comment]
Nossa valeu mesmo, vou testar, mas acredito que seja isso mesmo.  pois estava no automático do jogo, pois a versão anterior podia ser feito assim. 
Wow, I’m going to test it, but I believe that’s it. because it was in the game's automatic, because the previous version could be done like this.

**Comment by erksartori** [comment]
Fiz o teste e deu certo, Valeu pela ajuda. vai ter mais videos, com duvidas, pode ter até coisas que ainda não estão prontas, mas só assim poderei saber. abraços a todos.
I took the test and it worked, Thanks for the help. there will be more videos, with doubts, there may even be things that are not ready yet, but only then can I know. hugs to everyone.
