### ISSUE TITLE
Open cover automatically when refill a tool

### ISSUE THREAD

**Issue by Stupremee** [Courseplay/courseplay#5277]
It would be a nice feature if the courseplay helper would open the cover, e.g. of a sprayer, automatically if the machine is empty. At the moment you have to enter the tractor, disable courseplay, open cover, close cover, start courseplay.

**Comment by Tensuko** [comment]
Don't they open cover if you hover with a bigbag over them?

**Comment by Stupremee** [comment]
I don't use bigbags. I use an auger wagon and they dont open the cover if the pipe is above them.

**Comment by kwguk** [comment]
I think what Stupremee is meaning when you use either overhead silos or something like the Seedexpress1260 to refill. its the same for the Bredal trailed fert spreader.

**Comment by Tensuko** [comment]
The point is that normaly the Seeder and Fertilizer Tools open the cover when approach a refillstation or you get to them with a seed or fertilizer bag.

So it doesn't work with pipes of auger wagons. Will see what we can do.

**Comment by Stupremee** [comment]
> I think what Stupremee is meaning when you use either overhead silos or something like the Seedexpress1260 to refill. its the same for the Bredal trailed fert spreader.

Yep, thats exactly what I meant.


> The point is that normaly the Seeder and Fertilizer Tools open the cover when approach a refillstation or you get to them with a seed or fertilizer bag.
> 
> So it doesn't work with pipes of auger wagons. Will see what we can do.

Thank you 👍

**Comment by ddewar** [comment]
I believe this is a base game issue. Seeds do not open covers automatically for augers like they do for big bags.
