### ISSUE TITLE
Slurry tanker reloads sometimes

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#5278]
Hi again
Im using the vanilla Joskin slurry tanker and have a simple refill course from th field. However the tanker wont stop and refill everytime it takes the route. Somwtimes it will ignor the trigger and return to the field only to then realise its empty and go and refill only this time successfully.

Am i doing something wrong? Was is uspoosed to record the reload route in a different mode?
![fsScreen_2020_05_03_13_56_35](https://user-images.githubusercontent.com/11178621/80915049-6b437980-8d47-11ea-8efc-bf42b7eb3fbc.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4570362/log.txt)

**Comment by Tensuko** [comment]
You need to remove the FS19_manureSystem, as it blocks AD driven Vehicles from Refilling.

**Comment by kwguk** [comment]
Brilliant thanks!
