### ISSUE TITLE
HUD Allows Coursegeneration in Mode5 - TrafficController.lua:197: attempt to perform arithmetic on local 'fromIx'

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Courseplay/courseplay#5279]
I am trying to run multiple harvesters in one field. I get this error with different course settings.
[log.txt](https://github.com/Courseplay/courseplay/files/4570392/log.txt)

**Comment by Tensuko** [comment]
Can you show us the Course Settings you try to use ?

**Comment by pvaiko** [comment]
And also the exact steps to reproduce this.

**Comment by Gonimy-Vetrom** [comment]
I seem to have found the cause of this problem.
First, my carelessness. I was not convinced of what operating mode the course was generated.
I did it for COURSEPLAY_MODE_5!

Secondly. Courseplay allowed me this :) But only if you open it for the first time and do not change the mode.
https://youtu.be/9_Fzh_BXMAE

**Comment by Tensuko** [comment]
I noticed today too that you can open the coursegenerator when in mode5.
After change to another mode and back to mode5 its gone....

I both love and hate that HUD.....

**Comment by Tensuko** [comment]
Just to get it clear. When you generate on other mode then mode5 (wich should not be possible) then it is all ok ?

**Comment by Gonimy-Vetrom** [comment]
Yes. The course is generated and the combines begin to work in MODE_6. There are no errors.

**Comment by Tensuko** [comment]
So we just need to teach the HUD not to allow this :)

**Comment by pvaiko** [comment]
@Tensuko so what is the status on this one? Can we close? Is it about the HUD now? If yes can we change the title?

**Comment by Gonimy-Vetrom** [comment]
It works now
