### ISSUE TITLE
End on Startpoint Active: Running LUA method 'update' - AIDriver.lua:1357: attempt to index local 'course' (a nil value)

### ISSUE THREAD

**Issue by answermanitou** [Courseplay/courseplay#5280]
hello.
Playing Fs19 and use new CP 6.02 I was find few errors.
First was with transfer mode. The AI doesnt do anithing. I'll try to change method of start such as "start from begin/ start from nearest point'' -- this is doesnt work. Than I try to start course with "continue route" and its worked.
Second was with different field work. Generated course to crop, its Ok, but when AI allmost complete the route, the game was break. 
Log attached
[log.txt](https://github.com/Courseplay/courseplay/files/4570919/log.txt)

**Comment by Tensuko** [comment]
Get Version 1.0.0.2 from CM Discord:
Load mod: FS19_addon_strawHarvest (Version: 1.0.0.0) (Hash: 1d15f60600f67db89fc72447145539f4)

Also we need Information about what Tractor/Tool was used.

A logfile with debugchannel 12 and 14 would be good (not sure but maybe turn on channel 7 and 9 too...)

CP Error:
2020-05-03 18:02 Error: Running LUA method 'update'.
2020-05-03 18:02 C:/Users/manitou/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_02_00001/PurePursuitController.lua:544: attempt to index field 'course' (a nil value)

**Comment by answermanitou** [comment]
I think it was caused by "return to the start point - ON"
When AI is reach end of worked area Im leave the vehicle automaticly but Ai go forward
Equipment is all of basicle
I made few screen and attach fresh log.
in ver 399 and earlier its works fine besides mode for Loader in BGA
![fsScreen_2020_05_03_20_10_08](https://user-images.githubusercontent.com/64743178/80920941-baa39d00-8d7b-11ea-9e7f-c7e1038ec5fb.png)
![fsScreen_2020_05_03_20_10_10](https://user-images.githubusercontent.com/64743178/80920942-bbd4ca00-8d7b-11ea-933e-bf68c12181fe.png)
![fsScreen_2020_05_03_20_17_22](https://user-images.githubusercontent.com/64743178/80920943-bd05f700-8d7b-11ea-9d35-096f9ceb049c.png)

![fsScreen_2020_05_03_20_10_05](https://user-images.githubusercontent.com/64743178/80920940-b7a8ac80-8d7b-11ea-8eaf-17d5b4402060.png)

[log.txt](https://github.com/Courseplay/courseplay/files/4571064/log.txt)
![fsScreen_2020_05_03_20_08_26](https://user-images.githubusercontent.com/64743178/80920931-afe90800-8d7b-11ea-814d-0ca292c7b13d.png)
![fsScreen_2020_05_03_20_09_21](https://user-images.githubusercontent.com/64743178/80920935-b1b2cb80-8d7b-11ea-9d61-da2cefc2d136.png)
![fsScreen_2020_05_03_20_10_01](https://user-images.githubusercontent.com/64743178/80920937-b2e3f880-8d7b-11ea-818d-de8289e5414d.png)
![fsScreen_2020_05_03_20_10_03](https://user-images.githubusercontent.com/64743178/80920939-b5465280-8d7b-11ea-877b-513172bb6b57.png)

**Comment by answermanitou** [comment]
Please tell me where can i get new straw harvest ? Google search find nothing new. Only ver1.0

**Comment by pvaiko** [comment]
Sorry guys, I have no idea what the problem is. Need a step by step description of how to reproduce this and what exactly the problem is.

**Comment by Tensuko** [comment]
> 
> 
> Please tell me where can i get new straw harvest ? Google search find nothing new. Only ver1.0

Creative Mesh Discord

**Comment by answermanitou** [comment]
What I should to do?
Just now ill started same work in same place with same equipment but on ver 394 cp. Will wait

**Comment by answermanitou** [comment]
updates
AI was finished at end of route but not went to start point just stay at the last point of work route. The equipment are stoped and reise. Sorry for my english

**Comment by Tensuko** [comment]
304.... we are 96 Versions ahead.... do you rly think that this will help ? :)

**Comment by answermanitou** [comment]
Restart at 394 version . Its all works

**Comment by answermanitou** [comment]
Update for 6.02
AI doesn't fuel economy when awaiting combine and in the end of field work

**Comment by Tensuko** [comment]
Sry but this is not rly helpful writing one problem after an other in one Issue.
Also I don't understand any of your Problems....

**Comment by answermanitou** [comment]
> Sry but this is not rly helpful writing one problem after an other in one Issue.
> Also I don't understand any of your Problems....

Ok. I understud. 
Lets start again.
What is going on with CP on screenshots attached in my previous posts?

**Comment by Tensuko** [comment]
Will check this tomorrow with end on last waypoint

**Comment by Tensuko** [comment]
End on Startpoint active:
2020-05-04 18:19 Error: Running LUA method 'update'.
2020-05-04 18:19 I:/Dokumente/My Games/FarmingSimulator2019/mods/courseplay/AIDriver.lua:1357: attempt to index local 'course' (a nil value)

**Comment by pvaiko** [comment]
Still no idea what the problem is.

**Comment by answermanitou** [comment]
Will try it after my work

**Comment by Tensuko** [comment]
Tested with 00006, fixed.

**Comment by answermanitou** [comment]
Playing just right now. It's alright. Thanks to you very much. Want to ask is shovel mode works properly?
