### ISSUE TITLE
Several Issues with v6.02.00001

### ISSUE THREAD

**Issue by Christian13983** [Courseplay/courseplay#5281]
Hey guys, first I would like to say Thank you for your time and effort, you invest to the best Mod for Farming Simulator. 

I have several issues with the new CP Version v6.02.00001.

First Issue:
New Version doesn't load with existing savegame. 
First I thought, it was related with a mod, so I deleted all mods except the map NF Marsch.
But savegame doesn't load. With Version v6.01.00399 it works fine.

With a new clear map the new v6.02.00001 loads without problems.
(see attached file "logoldsavegame.txt")

Second Issue:
Mode 5 (Transfer) creates
PurePursuitController.lua:544: attempt to index field 'course' (a nil value)
I have tried all possible starting modes; "starting at first point, starting at nearest point...

![fsScreen_2020_05_03_21_08_31](https://user-images.githubusercontent.com/64726091/80924633-52a88300-8d8a-11ea-8bfc-0d8209ce7369.png)

I also tried it with a combine, the same problem, but other message
CombineUnloadManager.lua:285: attempt to call method 'isReadyToUnload' (a nil value)

Addionally the combine unfolds in Mode 5, but I think this is the same Issue as #5279

(please see attached file "logmode5"

![fsScreen_2020_05_03_20_59_46](https://user-images.githubusercontent.com/64726091/80924726-e11d0480-8d8a-11ea-8e83-ebd20071c505.png)

Third Issue:

The AI Driver in Mode 2 only starts when combine is 100% filled.
Setting (for example "start at 50%") in the HUD Menu doesn't take effect, AI Driver only starts when 
combine is full.

In this picture combine has already 57% and AI Driver is still waiting.
I thought it could be related to the first headland, that there is not enough space to field edge, 
but in second headland is the same behavior. 

![fsScreen_2020_05_03_21_21_24](https://user-images.githubusercontent.com/64726091/80924920-4de4ce80-8d8c-11ea-8bbf-ada89b788f2f.png)

Fourth and my last issue:

In setting "automatic laterally space" the AI Driver has not enough space to the combine and collides with the cutting-header.

But I'm not really sure, this could also be a "Phoenix Tatra Issue" 
because the Truck has curiously an offset to the right on the whole course.
Haven't tried it with another 

![fsScreen_2020_05_03_21_25_32](https://user-images.githubusercontent.com/64726091/80925122-a36dab00-8d8d-11ea-82a3-f45182d62896.png)

But the manual setting "laterally space" to combine also doesn't take effect. 

![fsScreen_2020_05_03_21_32_40](https://user-images.githubusercontent.com/64726091/80925131-bc765c00-8d8d-11ea-9506-539cd1423e6e.png)

Hope this will help you.

Regards 
Christian

[logmode2&5.txt](https://github.com/Courseplay/courseplay/files/4571572/logmode2.5.txt)
[logoldsavegame.txt](https://github.com/Courseplay/courseplay/files/4571573/logoldsavegame.txt)
[logmode5.txt](https://github.com/Courseplay/courseplay/files/4571570/logmode5.txt)

**Comment by Tensuko** [comment]
For the first Issue, can't reproduce it as I have switched arround with Versions a lot on my savegame on Gemeinde Rade and I didn't get into any Trouble.

The second Issue it never appeared to me either. Would need more Details on that one.

The third Issue, well, read #5272 ...

The fourth Issue is indeed the Tatra, wich got offset in its Nodes, GIANTS should know it already but there is no update so we can't do much about it. It will also drive all Course with this Offset:
![Nodes](https://user-images.githubusercontent.com/27344744/80925479-59d28f80-8d90-11ea-89fa-6a7c7e3e5a1a.png)

**Comment by Tensuko** [comment]
Old Savegame Error:
2020-05-03 21:49 Error: Running LUA method 'update'.
2020-05-03 21:49 C:/Users/cleve/Documents/My Games/FarmingSimulator2019/mods/zzz_courseplay/PurePursuitController.lua:67: attempt to perform arithmetic on field 'turnDiameter' (a nil value)

Mode5 Error:
2020-05-03 20:54 Error: Running LUA method 'update'.
2020-05-03 20:54 C:/Users/cleve/Documents/My Games/FarmingSimulator2019/mods/zzz_courseplay/PurePursuitController.lua:544: attempt to index field 'course' (a nil value)

**Comment by Christian13983** [comment]
Thank you for your fast reply.

The second issue I can reprodruce every time I start AI Driver in mode 5

I have recorded a new course and directly after I start the AI Driver i get the error.
Tractor doesn't move and camera freezes, after I click on "stop driver"

![fsScreen_2020_05_03_22_56_59](https://user-images.githubusercontent.com/64726091/80925724-740d6d00-8d92-11ea-82c6-a5225279dfba.png)
 everything is okay.

![fsScreen_2020_05_03_22_55_57](https://user-images.githubusercontent.com/64726091/80925680-2133b580-8d92-11ea-8046-ab5763776a90.png)

Third Issue...sorry my fault, didn't read that exactly. ;)

Fourth issue.. I tried it  with MAN > everything okay.


Regards
Christian

**Comment by Christian13983** [comment]
I have made another test to enclose the error.

So I made the same like before:

Record a course with John Deere 6M > start course in mode 5 > same error as before >
stop course > everything okay

Than I switched to another Mode in HUD (Showel Mode) and directly back to Mode 5
Start course again in mode 5 > no error

After that switch to Fendt 700 > record a course > start course in mode 5 > same error as before >
stop course > everything okay
Also switched to Showel mode in HUD of Fendt 700 and back to mode 5 again.
Start course again in mode 5 > no error

It seems that the error only appears to the first use of a tractor.

Hope this could help you to find out.

Regards
Christian
[log.txt](https://github.com/Courseplay/courseplay/files/4571793/log.txt)

**Comment by Tensuko** [comment]
This HUD drives me crazy... Thx for the tests I will take a look at this...

**Comment by pvaiko** [comment]
Can't reproduce this Mode 5 with tractor problem, just bought a tractor fresh, recorded course works fine.

For the 100%, yes that's how it works now, the combine will only call the unloader when full. On the long term, we'll remove that setting as it does not make sense, the combine will decide when to call the unloader.

**Comment by Goof245** [comment]
> On the long term, we'll remove that setting as it does not make sense, the combine will decide when to call the unloader.
Hopefully the combine will be smart enough to call early when it knows it's working a big field and the overloader is probably a long way away. Setting that low in old mode 2/3 was good for calling tractors early in huge fields so the combines wouldn't have to stop.

**Comment by pvaiko** [comment]
@Goof245 that is exactly the plan, the CP combines already have a quite good guess at where they are going to be full (you can see that in the log with debug channel 14), what we want is that they agree on a rendezvous with the unloader based on that estimate.

**Comment by NicholasSoares** [comment]
I also having the mode 5 bug, just need to record a course on the map (Felsbrunn) and save it, start a new game on the same map, get the Fiat DT tractor with the waggon, load the route and you will replicate this issue. You should not record a course with it or this problem will never happen, it just happen with fresh equipement loading existing courses

**Comment by pvaiko** [comment]
@NicholasSoares thanks, that helps, I was not able to reproduce it with 6.02.00003, could please give it a try?

**Comment by Christian13983** [comment]
Thank you, can't reproduce the error with v6.02.00004, it works fine.

Also my first Issue is fixed, old savegame now loads without problems.

Regards
Christian

**Comment by Tensuko** [comment]
Can we take this Issue as solved and close it ?
If there is only one point left, I would rather like to open a new Issue for this then.

**Comment by Christian13983** [comment]
Yes, all my issues are clarified, thank you.
