### ISSUE TITLE
Convoy distance seems off in new mode 2 test.

### ISSUE THREAD

**Issue by Goof245** [Courseplay/courseplay#5283]
Courseplay 6.02.00002

![20200504135820_1](https://user-images.githubusercontent.com/3851003/80936428-7f08e180-8e14-11ea-90d6-6de4bc8f376c.jpg)
[convoy failure log 2xharvesters testing mode2.txt](https://github.com/Courseplay/courseplay/files/4572785/convoy.failure.log.2xharvesters.testing.mode2.txt)

It seems like vehicle convoy with two combines isn't calculating the distance properly. These two were set to be at least 100m apart, yet they collided with each other. According to the mini-hud the rear combine thought the front combine was still 120m in front.

This would have also happened as early as the north corner on this field, when the front combine on the outside lane had stopped to unload. The only thing that prevented a collision then was the fact that it happened on the corner, and the rear combine recognised the traffic ahead and stopped.

**Comment by Tensuko** [comment]
This is not new and Issues already exists about it, this comes from headland.

**Comment by Goof245** [comment]
Might not have been mode 2 directly that caused it, but the issue has started after the big 6.02.00002 "Mode 2 update" :|

![20200504193338_1](https://user-images.githubusercontent.com/3851003/80953189-60b7db80-8e3e-11ea-8e17-9ffb13621702.jpg)

Exact same save, same course, same field, same machinces but on CP 6.01.00398 the inside combine waits correctly.

**Comment by Goof245** [comment]
....then I ran the same course again and they crashed in a completely different part of the field, over on the west this time...

Yay for non-reproducible behaviour... -__-
