### ISSUE TITLE
[Feature Request] Option to integrate Combine Unload (Mode 2) with AutoDrive

### ISSUE THREAD

**Issue by MicaelJarniac** [Courseplay/courseplay#5284]
Both Courseplay and AutoDrive have a Combine Unload mode, and each have their pros and cons.
With those new Mode 2 enhancements going on, Courseplay's Combine Unload feature is getting better and better, and I believe will soon be the smartest one available.

My suggestion is to allow us to easily integrate the Mode 2 Combine Unload from Courseplay with AutoDrive's unloading, so when the unloader is in the field, Courseplay takes full control, and once it's ready to unload itself to a silo or sell point, it hands control over to AutoDrive, for it to drive to the unload point, unload and then return to the field and give Courseplay control over it again.

I'm suggesting it because, although Courseplay is able to import a course from AutoDrive, it's sometimes tricky to find the desired course in the list, then to find a spot in the course where it's able to successfully import it, and then sometimes Courseplay messes up with the maximum speed when driving the course. That and also the fact that this manual import process would have to be repeated for each and every field.

Making it so that Mode 2 can optionally allow AutoDrive to unload the unloader would, IMO, make it a lot better, so we can use each mod to what they're great for: Courseplay for working inside the field and in sync with other workers, and AutoDrive for pathfinding and navigating huge distances around the map with minimal setup.

I'd imagine it would work like so:
When setting an unloader to do Combine Unload (Mode 2), we can either give it a course to follow when unloading (the Courseplay way) or tell it to use AutoDrive, without having to give it a course in Courseplay.
If it's set to use AutoDrive, it'd be in Pickup & Deliver mode, and Courseplay would wait AutoDrive to arrive at the pickup point, then take control. Once it's time to unload itself, Courseplay then gives control back to AutoDrive to drive to the deliver point, then AutoDrive will automatically drive back to Pickup once it's empty, and Courseplay takes control over it again.
For exiting the field, I'd imagine Courseplay could keep track of where it first took over control (when AutoDrive reached the pickup point), and then Courseplay would drive back to that point before giving AutoDrive control. That way, Courseplay would be able to coordinate field exit with the combine, and do that while using all its smarts.

**Comment by Tensuko** [comment]
This was asked many many times and that will happen one day...

**Comment by pvaiko** [comment]
This shouldn't be a big deal to implement since we already have something very similar to modes 4 and 6. It is really just a question of priority.

**Comment by MicaelJarniac** [comment]
> > Making it so that Mode 2 can optionally allow AutoDrive to unload the unloader would, IMO, make it a lot better, so we can use each mod to what they're great for: Courseplay for working inside the field and in sync with other workers, and AutoDrive for pathfinding and navigating huge distances around the map with minimal setup.
> 
> Unload the Unloader ? You Talk about Auger Wagon ?

@Tensuko, it was bad wording from my part. With "unloader" I meant the combine unloader, and with "unload" I meant to drive it to the silo/sell point. So "unload the unloader" would be "to drive the combine unloader to the silo/sell point".

Your example sounds awesome! I love using CP and AD together, and having both cooperate feels fantastic. CP doing everything inside of fields, AD doing stuff outside and navigating the map.

I did try to find another suggestion for this but I couldn't find any. Sorry for posting a duplicate.

@pvaiko, I use the AD integration on other modes all the time! That's where I got this idea from. After using the AD integration very successfully in most other modes, I really felt like it was just natural to have it on Combine Unload (Mode 2) as well. I even thought it was already there before realizing it wasn't.

And I thought about suggesting it now exactly because Mode 2 seems to be actively being worked on, so it felt like the perfect time to suggest new features for it. And as you said, AD integration is already a thing in other modes, so I'd imagine adding it to this mode as well shouldn't be too complex.

**Comment by TinyCrocodile** [comment]
Intresting option.
I have never used AD. Is it able to fill a Bunker Silo reverse or by driving forward?

**Comment by MicaelJarniac** [comment]
@TinyCrocodile, AD has just recently introduced reverse driving in their latest beta, it's still a bit experimental from what I see. But I imagine it is possible for you to create a route that goes to a bunker silo in reverse and set an unload trigger there. I've never tried it, though.

**Comment by Tensuko** [comment]
There are Tutorials from Mario Hirschfeld (German), maybe they do help you anyway.
Ofc that is not with the newest CP Version so he used AD to unload the Chopper.

**Comment by manierim** [comment]
> Intresting option.

And apart from the Bunker Silo, AD has also developed a combine unload mode (while CP mode 2/3 were under reworks) so this is an area of "competition": both mods can "drive" a vehicle in field to "chase" and then unload a combine and then transfer the crop to a trigger (CP mode 2) or to a trailer (auger wagon - CP mode 3)

**Comment by rohne83** [comment]
> For exiting the field, I'd imagine Courseplay could keep track of where it first took over control (when AutoDrive reached the pickup point), and then Courseplay would drive back to that point before giving AutoDrive control.

There's one big problem with that: very often you will have more than one unloaders, the following ones all waiting at exactly that AD point were CP took over. And there are many fields where the possible field entries are quite narrow. So the leaving unloader would crash into the waiting ones if CP drove exactly to that point. That's why you have those different field exit strategies in AD, and the recommendation to create those blue catch lines around your fields. So for finding the best point to leave the field AD is better, but on the other hand we don't want other drivers than CP on the field. Tricky... Think best would be if CP could also make use of those different field exit strategies. But don't know if that's possible.

**Comment by Rumspringa90** [comment]
Is there any progress yet? I would celebrate it if that would work 🎉

**Comment by rohne83** [comment]
Thanks to your generic code I was able to implement that option myself already. Quick&dirty it was just one line in hud.lua (to have the AutoDrive option shown in mode 2) and a few lines for CombineUnloadAIDriver (additional state and minor amendments to startUnloadCourse and onEndCourse). Maybe not too beautiful, since you really have to take care of the drive on percentages in CP+AD settings, but so far it's working really great! Exiting the field in my version is done by AutoDrive already - was easier to implement and that way I can make use of AD's different field exit strategies (really helpful when you have those blue catch lines around your fields so you can avoid your unloaders crashing into each other at the field entry).

Not too familiar with GitHub yet, so will have to see how I can provide it to you CP devs, if you're interested, to check whether this is sth you can work with and doesn't screw up other things ;)

**Comment by pvaiko** [comment]
@rohne83 awesome, please create a pull request for this feature!

Thanks for the contribution.

**Comment by rohne83** [comment]
managed to get the pull request created. CP still needs a course for mode 2, but this can be any random one even on the opposite corner of the map, as this one isn't used at all.
Start CP driver with options 'Unloading' and use AutoDrive 'refill/unload'. AutoDrive settings basically the same as for the fieldwork drivers: use pickup&deliver, select a proper field exit strategy and take care about appropriate drive on percentage (has to be lower than the setting in CP).

**Comment by Crinouche** [comment]
Very good job rohne83. I've been waiting for this option for a long time. Indeed, there are still some small synchronization problems with AD, but overall it works.

On the other hand, the grass fields are still a problem for the follow-up next to the forage harvester (pictures 1 to 3) I know that this problem has already been reported.
Pictures 3, the trailed forage harvester does not detect the trailer. So I can't use mode 2 + AD to harvest grass fields. (For now, I hope! :))
![image](https://user-images.githubusercontent.com/36656729/122632832-94eb6b80-d0d5-11eb-9f66-c46ef53efcca.png)
![image](https://user-images.githubusercontent.com/36656729/122632863-b8aeb180-d0d5-11eb-93c2-1bac65db9637.png)
![image](https://user-images.githubusercontent.com/36656729/122632960-3b377100-d0d6-11eb-837c-719ddffde85a.png)

**Comment by Tensuko** [comment]
@Crinouche 
 #5470

Maintopic seems fixed.

Thanks to @rohne83 !
