### ISSUE TITLE
Error When Offloading Combine w/ New Mode 2

### ISSUE THREAD

**Issue by KawaiiHalo** [Courseplay/courseplay#5285]
When the combine unloads the game freezes and the vehicles that are running continue infinitely in a straight line. I play with mods, so I removed all of them except one (the tractor I was using when the error first occured; CAT 75c), and I was able to harvest and offload an entire field with zero issues. This issue is occurring on a modded map with a modded harvester and tractor (vanilla trailer). The crop is also modded (cranberry). When I last tested it just a few minutes before writing this, the combine offloaded with no issue the first time, and the second time the issue occurred. The error is a failed to run the update method.

[log.txt](https://github.com/Courseplay/courseplay/files/4574962/log.txt)

Side note, when the tractor is offloading, it inches forward until the combine is empty, sometimes running the tractor out of the pipe range before it finishes offloading.

**Comment by Tensuko** [comment]
Load mod: FS19_Courseplay (Version: 6.02.00001) (Hash: 43cd235d9dd2b567a76fa1807bb39ed5)
Update to newest Version and try again:
https://github.com/Courseplay/courseplay/releases

**Comment by Tensuko** [comment]
Also: You got a lot of mod loaded with Erros and I am sure you also have more then 1 Map in Mods folder. That is not allowed.

**Comment by answermanitou** [comment]
> Also: You got a lot of mod loaded with Erros and I am sure you also have more then 1 Map in Mods folder. That is not allowed.

How many mod maps can I store in mods folder?

**Comment by Tensuko** [comment]
This and clean up your mods Folder....

**Comment by Tensuko** [comment]
You clean up your mods folder and try again with newest Version.
I clean up GitHub in the meantime :)
Make new Issue with a nice clean log and discribe what you did, then we take a look.
