### ISSUE TITLE
[Question] Why release files are named 'Courseplay_x_xx_xxxxx.zip'?

### ISSUE THREAD

**Issue by MicaelJarniac** [Courseplay/courseplay#5286]
Usually, FS19 mods are named `FS19_Modname.zip`, without the version in the file name. That's pretty much a rule for ModHub mods I think, and it's common practice for manually downloaded mods as well, it seems.

But with Courseplay, the file in releases isn't named following that convention, it's named as `Modname_version.zip` instead, like `Courseplay_6_02_00004.zip`.

I understand the version number is important, but it's already embedded inside the mod, and the mod manager inside the game displays it just fine, even without it on the file name.

And having the mod file named that way makes the mod manager unhappy. If you update the mod version, as the files have different names, the mod manager doesn't recognize it as the same mod, so it'll state that one of the mods was uninstalled, and the user will have to manually reactivate it.

The workaround is to manually rename the downloaded file so the naming is consistent. That works just fine, but it's a workaround, it has to be done every single time we want to update.

Also, it's easy to accidentally have two versions of the mod installed at the same time if the user doesn't pay attention and doesn't rename the files, as they'll have different names. If they had the exact same name, when moving the new version to the mods folder, the file manager would most likely ask the user whether they want to replace the old file with the new one or abort.

So my question is, why does Courseplay follow this unusual and possibly problematic naming scheme, instead of the more standard and widely used one?

**Comment by Tensuko** [comment]
I got a Suggestion for your Issue:
#5135

**Comment by pvaiko** [comment]
I can change it easily, releases are generated automatically using the GitHub API, I don't mind just calling it FS19_Courseplay.zip

**Comment by Tensuko** [comment]
Well that would make things much easier ofc, even for me by tell ppl they have to rename the file to avoide having CP 2 times in mods folder.

**Comment by MicaelJarniac** [comment]
@Tensuko, I've seen the auto update tool before, but I don't mind watching GitHub and downloading then renaming manually.

I've asked this mostly because well, I think most people do the exact same thing, download then rename, so I was curious why it's called the way it is, instead of having the name most people are going to rename it to straight away. I thought there was like an underlying reason, something specific, so I was curious.

But from what @pvaiko said, it's just this way because it was generated automatically, and setting its name to `FS19_Courseplay.zip` could be done. I'd vote for that!

In the past (I think pre-FS19 era) to download CP users would have to download the entire repository, then do some stuff, then rename, then do more stuff, etc. The way it is now is 1000% better. Changing the name would make it 5% better, but still, if it can be done and if it can make things easier, I see no reason why not!

**Comment by Tensuko** [comment]
I never asked for why it is named like that.
The Advantage is, if you have more .zip files arround to switch versions, it is easier to find, but sure for normal use it is better with FS19_Courseplay.zip

**Comment by MicaelJarniac** [comment]
Just saw the newest release, file is named as per the `FS19_Whatever.zip` standard now!

And you guys are on a streak! It's so awesome to see devs so talented and so dedicated and so awesome and everything! I hope one day I'll be a dev like you all are!

But for the meanwhile all I can do is thank you all very much for the time and effort and love that's been put into this awesome mod.

❤️

I'll close this issue now, thanks again for everything!
