### ISSUE TITLE
Driver doesn't drive to combine (6.02.00004)

### ISSUE THREAD

**Issue by Siwuees** [Courseplay/courseplay#5288]
I have started the unloader over the function start driver: "unloading", then CP calculates the path, but the tractor doesn't drive to the combine as expected. I also waited several minutes, but nothing happend. 
Most time, the unloading works, but in a few cases the tractor gets stuck as you can see in the picture. I already had the case, when the tractor was further away (and it didn't move), and after I drove it closer to the combine it worked all fine.

[log.txt](https://github.com/Courseplay/courseplay/files/4575684/log.txt)
![CP_2](https://user-images.githubusercontent.com/54322417/80986254-9c4ba900-8e30-11ea-847e-fcf1df716cdc.png)

**Comment by Tensuko** [comment]
Start in Line 5456

Line 5479: 2020-05-04 17:53 :48 [dbg4 lp193400] 6350R (#2): proximity: d = 0.0, too close, stop.

**Comment by pvaiko** [comment]
It is because of the weight I think. Try without the weight on the tractor (until we fix this).

**Comment by Siwuees** [comment]
It looks like it is working without the weight. Thank you for the help.
