### ISSUE TITLE
truck does not go to combine for unloading

### ISSUE THREAD

**Issue by androno12** [Courseplay/courseplay#5289]
For the truck, I chose the Unload mode. I chose the route to the unloading point. But when the combine is filled with grain, he stops and waits for the truck. But the truck stands still and does not go to the combine. No other mods except Fast Time
Only once did I see a truck go to the combine. At the same time, I got a big drop in frames (22-28) (normal - 60fps)
[log.txt](https://github.com/Courseplay/courseplay/files/4575711/log.txt)

**Comment by Tensuko** [comment]
Can you make a screenshot of the situation like where is the combine and where is the truck ?
A logfile with channel 4 7 12 and 14 active when try to unload the combine would help too.

**Comment by kwguk** [comment]
I get exactly the same,
![fsScreen_2020_05_04_17_36_26](https://user-images.githubusercontent.com/11178621/80990137-d6677b80-8e2d-11ea-8b35-56e3107b8796.png)

**Comment by kwguk** [comment]
Heres my log and two more screenshots
![fsScreen_2020_05_04_17_48_09](https://user-images.githubusercontent.com/11178621/80991176-88ec0e00-8e2f-11ea-9e35-f51c451370a2.png)
![fsScreen_2020_05_04_17_47_48](https://user-images.githubusercontent.com/11178621/80991225-9608fd00-8e2f-11ea-8a44-81d46c246069.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4575972/log.txt)

**Comment by Tensuko** [comment]
Who on Earth starts in the midpart of the Field ?

Anyway, on your 1st Screenshot you didn't check any Combine to unload.
You might need to reload the Page to get the Combine to show up. Or your Combine is not on Field 47. This is just a filtersystem.

**Comment by androno12** [comment]
Did I do everything right? 
![FarmingSimulator2019Game 2020-05-04 20-15-49-050](https://user-images.githubusercontent.com/47071055/80994093-df177c00-8e44-11ea-8718-3d9d3c92d6fc.jpg)
![FarmingSimulator2019Game 2020-05-04 20-17-59-680](https://user-images.githubusercontent.com/47071055/80994134-f0608880-8e44-11ea-8182-39960b2bbce7.jpg)
![FarmingSimulator2019Game 2020-05-04 20-18-23-010](https://user-images.githubusercontent.com/47071055/80994187-ff473b00-8e44-11ea-93c7-c966996c2d32.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/4576140/log.txt)

**Comment by kwguk** [comment]
Ok ive started again, One combine in field 47 as you can see but im getting no option to unload any combine. The tractor just sits there with 'no combine in reach' occassionally flashing up along the bottom.
![fsScreen_2020_05_04_18_44_43](https://user-images.githubusercontent.com/11178621/80996575-edab6680-8e37-11ea-99b2-6b0fcf0c00d4.png)

**Comment by Tensuko** [comment]
Before we continue anything here Update:
https://github.com/Courseplay/courseplay/releases
Then somehow all combines should register themself in that list unless your filter is set to the wrong field (it is jsut a filter for the combine....)

**Comment by kwguk** [comment]
Ah right apologies. I didnt realise i wasnt running the latest release. I cant keep up!
Will download now and retry....

**Comment by Tensuko** [comment]
Also maybe see this how it should work:
https://www.youtube.com/watch?v=895zpaeE8iU

**Comment by kwguk** [comment]
Yep i can see how it should work but im still seeing no option to pick a combine to unload
![fsScreen_2020_05_04_19_46_58](https://user-images.githubusercontent.com/11178621/81002060-9067e300-8e40-11ea-96de-4760577f278c.png)

**Comment by Tensuko** [comment]
Did you play arround with your Filter ? (Search Combien on Field) I would try set it to -- to see all combines on the map.

**Comment by kwguk** [comment]
Excuse my ignorance, your video was in German and my German is rubbish. Where would i look for filter on the HUD?

**Comment by androno12** [comment]
Changed the truck - still not working. "Waiting for combine call "... If I try to call the truck manually - "waiting for pathfinder"

**Comment by Tensuko** [comment]
> 
> 
> Excuse my ignorance, your video was in German and my German is rubbish. Where would i look for filter on the HUD?

Search Combien on Field ...

> 
> 
> Did you play arround with your Filter ? (Search Combien on Field) I would try set it to -- to see all combines on the map.

**Comment by kwguk** [comment]
> > Excuse my ignorance, your video was in German and my German is rubbish. Where would i look for filter on the HUD?
> 
> Search Combine on Field ...
> 
> > Did you play arround with your Filter ? (Search Combien on Field) I would try set it to -- to see all combines on the map.

I must be daft becaue on my 'manage Combines' tag on the HUD all i have is what ive always had which you can ee in previous screenshots.

Is the filter on the HUD somewhere??

**Comment by Tensuko** [comment]
![81002060-9067e300-8e40-11ea-96de-4760577f278c](https://user-images.githubusercontent.com/27344744/81008553-6b30a000-8e53-11ea-8577-ffb2299a9f20.png)

**Comment by kwguk** [comment]
Yes i get that . Ive watched your video again and i get none of the options that are in the video. All i can do on the Manage  Combine screen is scroll through the fields i own, nothing else.

**Comment by kwguk** [comment]
Forget all of that, the list of combines suddenly appeared out of nowhere

**Comment by Tensuko** [comment]
Well that is the problem.
I had the same problem and I looked arround and suddenly it was ok thats why I cant tell you the right solution.
We will for sure kerp an eye on that :)

Does the unload work for you now so we can close this Issue ?

**Comment by kwguk** [comment]
Well no it doesnt.
Firstly the tractor will drive to the combine thencreep alongside and the combine will start unloading> However the tractor will keep moving untilthe unloading pipe is right at the  back then it will start reversing until its away from th combine then it turns round nd returns to its start point. 

So i tried againi called the tractor when the combine was 50%. The tractor respeonded drove up to the combine then a beam of white light appeared between tractor and combine. The  tractor followed the combine for a bit then pulled longside and  proceeded to drive away aroubd the  edge of the field still connected  to the combine by the light beam,

This is all way above my intellect and i think i should leave  to you guys who are the experts to sortit out. Ill revert back to a previous version.

I enclose my log
[log.txt](https://github.com/Courseplay/courseplay/files/4577380/log.txt)

**Comment by pvaiko** [comment]
@kwguk #5272: no unloading of moving combine yet.

**Comment by Goof245** [comment]
Is the field yours? I've been finding that the mode 2 workers seem to be oblivious to combines working as part of a contract, on fields I don't actually own...

**Comment by Tensuko** [comment]
When you have accepted a contract you kinda 'own' the field else you couldn't do any work on it.
But I will try this one out...

**Comment by kwguk** [comment]
So ive done do a bit more with the latest version.

I do now get the list of combines to tick and unload.

However i still get the tractor approaching the combine slowly driving past until the pipe is at the the back or the 'target'. Then it will start to reverse slowly back away from the combine. It barely manages to empty 5%. The tractor will then either stop in the way of the combune trying to reverse or head back to the start point of the course.

**Comment by Tensuko** [comment]
logfile with debugchannel 4 7 12 and 14
A Video would help a lot too.

**Comment by Tensuko** [comment]
Btw what is ths mod ? Load mod: FS19_HelperAdmin (Version: 1.0.1.0) (Hash: dc46f245b14c591f44af0274548f30da)

**Comment by kwguk** [comment]
https://fs19.net/farming-simulator-2019-mods/scripts/helper-admin-v-1-0/

How do i do a video???

**Comment by Tensuko** [comment]
Remove that helper admin and try again.
For a Video, you can check for Radeon ReLive. I use it too and it works good.

**Comment by dsmith109** [comment]
I am also having the issue in which the trailer moves forward and backward while offloading the harvester. What setting do I need to adjust to fix this.

**Comment by Tensuko** [comment]
Offset Setting.
This happens if the Target of the Trailer is to far back.
Will try to tune this a bit.

**Comment by dsmith109** [comment]
Okay thanks for the quick reply. Is there a setting or workaround I can use to make it work in the meantime? Like maybe manual vertical offset?

**Comment by Tensuko** [comment]
Outdated Issue. Closing.
