### ISSUE TITLE
Enhancement request with RH 24-60

### ISSUE THREAD

**Issue by polosubtil** [Courseplay/courseplay#5292]
Hi guys,

No rush here at all, I just want to put that somewhere to see if it's doable eventually when major things will be up and running (Mode 2 first of course... ;)
I didn't find any reference to that yet

Is there a way to use the RH 24-60 trigger on a Mode2 or Mode1 course with CP ? I did some tests and looks like it's not working at all.

Thanks in advance guys, you really do a terrific work

**Comment by Tensuko** [comment]
Will try it out but this is not on priority list right now.

**Comment by polosubtil** [comment]
Of course, as I said, Mode2 first :)

**Comment by dp-github** [comment]
> Is there a way to use the RH 24-60 trigger on a Mode2 or Mode1 course with CP?

What are you trying to have happen?   

* Are you trying to get a tractor pulling a RH24-60 to drive a Mode2 course (drive up to your harvester when it is full, receiving the potatoes or sugarbeets?)

* Or are you trying to have a trailer run a Mode2 course, and unload the potatoes/beets at your RH24-60?

**Comment by polosubtil** [comment]
Option 2 : I am trying to use mode 2 with a normal trailer and discharge it (with beet or potatoes) in the RH 24-60

**Comment by dp-github** [comment]
Can you do this manually (without Courseplay)?  If so, what kind of trailer are you using to do it?

**Comment by dp-github** [comment]
I think you're going to have to wait for Mode3 to be implemented, and then you can use the TV585 with the MB35 attachment to overload into your RH24-60.

I was able to do this manually today, but it requires an overload, not a trailer tip.

**Comment by polosubtil** [comment]
Hi @dp-github 
It works with a normal tipping trailer loaded with potatoes or sugar-beets. In manual, you just have to reverse to it and the trigger appears (press "i" to unload)
I can make a video if you want

**Comment by dp-github** [comment]
Do you only get this trigger when the RH-24 is detached from a tractor?  Or do you also get it when you back up from the sides or unloading end?

**Comment by polosubtil** [comment]
Hi
Well the normal use of such a machine is the way you explained : detached from the tractor and with a tractor + trailer reversing to it
https://www.agrisanterre.com/ressources/images/3413464-1824.jpg
https://www.grimme.com/be/producttypes/lagertechnik/rh-24-combi-cleanloader

Thanks a lot for your help anyway, let's wait for mode 3

**Comment by Tensuko** [comment]
As I said I need to test it, this is not a Mode3 Problem, as Mode3 is to control Overloader and normal Trailers can unload into this Tool.
It might not notice this as an unload Trigger, wich would be the problem here.

**Comment by Tensuko** [comment]
Tested with .00067, works like a charm.
![fsScreen_2020_10_16_17_50_35](https://user-images.githubusercontent.com/27344744/96280334-24390000-0fd8-11eb-87ae-3327da1c9cd9.png)

**Comment by polosubtil** [comment]
Perfect guys, you rock !!!!!!!!!!!!!!!!!!!!
