### ISSUE TITLE
Abfahrer steht am Rand des Feldes und fährt nicht los

### ISSUE THREAD

**Issue by SevenFifty1996** [Courseplay/courseplay#5293]
hi Guys,
something went wrong with the last update. Whatever I do, the driver does not drive to the specified thresher. in the window, at the bottom, you can read very briefly, no thresher within reach. The beets and potato harvesters are not found at all. Field numbers are not displayed correctly.
greetings sevenf

**Comment by Tensuko** [comment]
#5272
