### ISSUE TITLE
Multiple Course Issues

### ISSUE THREAD

**Issue by Johnne25** [Courseplay/courseplay#5294]
This is a great mod and is quite complex.  So its possible I just don't know that I am doing.
Here is my scenario, maybe you can point out my flaws.

I have a field of Oats.  I create a course 14.4 meter wide for my harvester.  It follows the course nicely.
Once its complete, I use a different tractor and a baler.  I thought I could load the previous course since I want this tractor to follow the same path.
The issue with this is the tractor does 1 km per hour.  If I have it use max speed, it does 50 km per hour.  Not the proper baling speed.

I then create a new course for that tractor using the same width as the havester.  It then works correctly.

Now that its going I put the harvester in a new field, create a new course and have it go along its way.

In the mean time my baler completes and I move him over the new field and since the harvester is way ahead I create a new course for the baler and get him going.  I watch the for a few rows and they are working pretty good.

On the first field I get the straw trailer on a new course (using 14.4 as the width again) and an offest of 2.4 (left) to pick up the straw.

It works great on the way up the field, but on the way back its offset is no longer correct.
I adjust it 1.0 (left) and it seems to work better.

However, when I check the harvester and the baler on the other field I see that their offsets are also out of sync.  The harvester and baler offets are out of sync and the baler is missing the straw swath completely. 

Am I doing something wrong?

**Comment by Tensuko** [comment]
Logfile ?
What is your cruise control speed set when you start the course ?
You may increas the cruise control while the CP Driver is running with low speed (1)

**Comment by Johnne25** [comment]
My cruise control speed is always set to max, as I let the tool I am using determine my max speed.  I don't usually set the cruise control speed unless I have need to slow down a help because its being followed by a slower tractor.   

In the case that my baler had a speed of 1 when doing the course I could not change the cruise control speed (1 or 2 on the keyboard).

**Comment by Johnne25** [comment]
I can give you the course and log files, if you let me know what files you want and how I can add them to this issue.

**Comment by Tensuko** [comment]
Can you make a screenshot of the slow running Baler ?
I will also try to reproduce this, but a logfile with channel 12 and 14 would help (not sure about channel 9)

**Comment by Tensuko** [comment]
logfile attatch just drang and drop the log.txt into the comment box just like I do it with this screenshot :)

![fsScreen_2020_05_05_19_13_02](https://user-images.githubusercontent.com/27344744/81094913-85768680-8f04-11ea-87a3-1d9f81f09e23.png)

**Comment by Tensuko** [comment]
Even with Convoy Setting it does a good job:
![fsScreen_2020_05_05_19_14_54](https://user-images.githubusercontent.com/27344744/81095067-c1115080-8f04-11ea-8799-da6ff126e2c8.png)

But I would slow down the Tracot so it won't stop too often.

**Comment by Johnne25** [comment]
Thanks for trying this on your own.  If finally got a chance after work to reproduce the issue.
Here are the steps (hope they help with going through the logs).
I created a course for my Harvester 14.2.
I made sure the cruise control was full and turned off.
I saved the course as F48 14.2 Harvest.
When it got about half way through I started up the loader.
On a second tactor I loaded the course and clicked Drive.
The tractor goes to the start of the course then just stop there.  Not sure what its waiting for.
Click continue it doesn't do anything.
I manually drive a littler farther into the course and click drive again.
This time it start, but is stuck at 1 KM per hour.
Manually changing speed setting doesn't help.
I can't change the cruise control setting on the tractor either (1 or 2 on the keyboard).

**Comment by Johnne25** [comment]
![fsScreen_2020_05_05_18_53_56](https://user-images.githubusercontent.com/5278934/81124139-b2299e80-8f02-11ea-9387-7ecb5a56a597.png)

**Comment by Johnne25** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4584072/log.txt)

**Comment by Johnne25** [comment]
I had debug channels 9, 12 and 14 enabled.

**Comment by Johnne25** [comment]
You might see in the log file that I had other tractors on courses as well.  But, since those were out on their own new courses I wasn't having issues with them.

**Comment by Johnne25** [comment]
I saved and backed up my game just before starting this test.   I can use it to perform any other scenarios you might need.

**Comment by Johnne25** [comment]
Ok, Played around with this some more and as I mentioned in my first message it seems that the issue is with me. 
I assumed that when you saved the course everything in the HUD was saved as part of the course definition.  Looks like you have to choose options everytime you load and use the course.
You can see in my screen shot my loader is using the 'point to point' mode, when should be using farm work.   Looks like its my bad.   Sorry for taking up your time.
Is there a document where I can learn about the options and how to combine coureses?

**Comment by Tensuko** [comment]
There is nothing to learn for combine course.
Load the course and choose the right mode. If you want the loader to drive off, add unload course with folder with the +

**Comment by Tensuko** [comment]
Closing this to keep Issues clean.
If you got more questions, feel free to ask.
