### ISSUE TITLE
Steering Mode memory

### ISSUE THREAD

**Issue by Horozor** [Courseplay/courseplay#5295]
Hey. Is it possible courseplay save the selected Steering Mode. For example, I chose all-wheel steering, (Hardi Rubicon 9000 or Horsh leeb PT 350) but courseplay didn’t remember it, and switched to standard mode.

**Comment by Tensuko** [comment]
@pvaiko can we even control the steering mode ?

**Comment by pvaiko** [comment]
See the discussion here:
https://github.com/Courseplay/courseplay/issues/3062#issuecomment-475921477
