### ISSUE TITLE
IC / Simple IC not working with latest Courseplay version

### ISSUE THREAD

**Issue by fresH229a** [Courseplay/courseplay#5296]
Hey,

i just recognized it right now.
With the current versions of CP, Simple IC / ICs of some Mods are not working.
The IC is showing but if I press the left mouse button, nothing happens.

If I remove the left mouse button from the CP assigments, everything is working fine again.

BR

**Comment by Tensuko** [comment]
IC never worked and will never be supported.
SimpleIC does work I use it on my own.
You need to change the mouse button keybind (I suggest you middle mouse button).
