### ISSUE TITLE
[Feature Request] Default keybinding for "open HUD with"

### ISSUE THREAD

**Issue by MicaelJarniac** [Courseplay/courseplay#5300]
Currently, we can toggle between opening the HUD with <kbd>Mouse Right</kbd> or <kbd>CTRL</kbd>+<kbd>DEL</kbd>, and that already helps, but the problem is, mostly because of AutoDrive, I _never_ want <kbd>Mouse Right</kbd> to be used for opening the HUD, so on every vehicle I have I set it to <kbd>CTRL</kbd>+<kbd>DEL</kbd>. It works, but it's a workaround.

I'm suggesting a quality of life improvement, to add an option to set the default keybinding (shortcut) to open the HUD, so if the user wants to make <kbd>CTRL</kbd>+<kbd>DEL</kbd> the new default option, they can.

The reason having <kbd>Mouse Right</kbd> is a bad idea with AutoDrive is that for some HUD interactions inside AD, it actually does use <kbd>Mouse Right</kbd>. For example, when you're at a certain mode in AD and want to go back to the previous one, instead of having to do <kbd>Mouse Left</kbd> a lot of times to cycle all the way through all modes until you're at the previous one, you can do a single <kbd>Mouse Right</kbd>. And to record AD courses, if you <kbd>Mouse Left</kbd> the record button, it records a single way route, but if you <kbd>Mouse Right</kbd> it, it'll record a dual way route instead. There are more things that use <kbd>Mouse Right</kbd>, but those are the ones I remembered now.

If you try to <kbd>Mouse Right</kbd> the AutoDrive HUD while Courseplay is set to open its own HUD with <kbd>Mouse Right</kbd>, Courseplay HUD opens as well, which is usually not a big deal. But if you then try to use <kbd>Mouse Right</kbd> on AutoDrive's HUD while Courseplay's HUD is being displayed, the cursor disappears, and that makes using <kbd>Mouse Right</kbd> basically impossible in AD's HUD.

**Comment by MicaelJarniac** [comment]
I tried searching if there was already an issue for this, and the closest ones I could find were this one (#3399), that's a bit similar but it doesn't quite cover the reasons why one might want to change this default binding (and it also mentions completely removing the option to open the HUD with <kbd>Mouse Right</kbd>, which feels a bit extreme), and also this one (#1629), that's more like asking if the current behavior is a bug or is intended.

**Comment by Tensuko** [comment]
We would have to change a lot if we change something on mouse use.
But yea alternative HUD opening is something we can look into.
I will think about a working solution, maybe a global Setting for open HUD alternative or something similar.

**Comment by MicaelJarniac** [comment]
Simply having an option that allows us to choose the default option between <kbd>Mouse Right</kbd> and <kbd>CTRL</kbd>+<kbd>DEL</kbd> would do the trick. That option is already there, but it's per vehicle only right now. So basically having a dropdown in the settings that allows us to choose what that setting will be for new vehicles would suffice. It'd be pretty much the exact same setting that already exists, but this time it's setting the global default of that setting (it would still be possible to go in a vehicle and choose a different setting for that vehicle, just like it is right now).

Sure, reworking the mouse handling so that it's more streamlined with mouse events (because right now I think it only cares for cursor position, and it grabs the clicks from the game handling them as actions in the keybindings) would be nice, but the QOL thing I suggested is way waaay simpler than that.

**Comment by Tensuko** [comment]
But you shouldnot forget that some ppl want to keep most vehicle open hud with right click and only one or two vehicle use ctrl+del, this would be vehicle based option. Thats why I need to think about a solution, so a global setting will make the open hud to a keybind but also have the option to change it per vehicle like it is now.
Just give me some time for that...

**Comment by answermanitou** [comment]
> But you shouldnot forget that some ppl want to keep most vehicle open hud with right click and only one or two vehicle use ctrl+del, this would be vehicle based option. Thats why I need to think about a solution, so a global setting will make the open hud to a keybind but also have the option to change it per vehicle like it is now.
> Just give me some time for that...

90% vehicles are using with MouseRight. Only telehenders or frontloades I set to ctrl del bindings.
In this time this is not so big problem

**Comment by Tensuko** [comment]
I think the same way but as I want to make more changes to the keybinding I will check what options I can create for this...

**Comment by answermanitou** [comment]
> I think the same way but as I want to make more changes to the keybinding I will check what options I can create for this...

What about to do this in advanced settings?

**Comment by Tensuko** [comment]
That wont change anything beside it is in another menu

**Comment by MicaelJarniac** [comment]
@answermanitou I know this is far from an important issue. Like very very far from being an important issue. As I said, this is just a quality of life change. I suggested it so that at least the devs are aware of it, and maybe some day can think about doing something about it.

I don't mind having to go into every single vehicle to change the setting manually, but I think adding the option for the user to choose what the default behavior will be, instead of having it hard coded the way it is now, would be nice.

This isn't something that affects the functionality of Courseplay. It isn't something that breaks the game, it doesn't affect performance, anything like that. This is just a small detail that could be simplified.

I'm sorry if it sounded like I was rushing the addition of this feature, or if it seemed like I was trying to get it over prioritized.

**Comment by 51stHD** [comment]
I'm glad that you raised this issue and did it in a clear fashion that got enough attention for it to be now solved with a very decent solution.

I've raised this before now in #5002  but it never got any attention at all.

Anyhow now it's sorted I'm back to using CP after quite some time of doing without it, as in the end the click-fest was enough for me to delete it.

Thanks to you and to the guys who fixed it.

**Comment by Tensuko** [comment]
Well it should come in the next release, yes it is in Branch already, but official answer is: wait for release :p
