### ISSUE TITLE
LUA Error Mode10 when Enter Bunker

### ISSUE THREAD

**Issue by ontot** [Courseplay/courseplay#5302]
The video was made with version 0003, but still today with version 0005 it is the same. Applying the courseplay in the trench crashes the game.
This is the video https://www.youtube.com/watch?v=ljR4eYfsgxY

Thanks for the answer...

**Comment by Tensuko** [comment]
Why I always got to ask for this.... logfile ?!

**Comment by ontot** [comment]
I thought that the log you see in the video was enough ... sorry. 
anyway here is the log.

[log.txt](https://github.com/Courseplay/courseplay/files/4580297/log.txt)

**Comment by Tensuko** [comment]
Just an Info for you: You do not need to rename CP to this:
Load mod: ZZZ_Courseplay (Version: 6.02.00005) (Hash: 83f840273da82dc53ba78f2dbfb71847)

Just download the .zip in release and place it into mods Folder.
Ofc you got to reactivate it in your save but thats is not a problem at all.


Anyway I have found no conflicting mod, that might be a real Error:
2020-05-05 11:45 Error: Running LUA method 'update'.
2020-05-05 11:45 F:/onofrio F/Documenti/My Games/FarmingSimulator2019/mods/ZZZ_Courseplay/LevelCompactAIDriver.lua:640: attempt to perform arithmetic on local 'targetHeight' (a nil value)

Will check on this :)

**Comment by pvaiko** [comment]
@ontot can you make a video and a log with debug channels 10 and 14?

**Comment by ontot** [comment]
But I always rename it ZZZ_Courseplay.zip, as you can see in the photo. Thanks for the answer... 
![image](https://user-images.githubusercontent.com/26443217/81061625-f736dc00-8ed4-11ea-8877-e1eec633ee48.png)

**Comment by Tensuko** [comment]
@ontot 
I just tell you that you don't have to do it :)
Now all new Release will be named FS19_Courseplay.zip and you can just place it in your mods Folder.
You will just have to remove your zzz_courseplay and when load the savegame the next time, activate CP again. Nothing to worry about.

Ofc you can keep rename but I think this is easier :)

**Comment by ontot** [comment]
ah ... ok ... thanks Tensuko ... anyway here is the video of debugging 10 and 14, as requested by Pvaiko...  https://www.youtube.com/watch?v=KKAPygqUhhE  

[log.txt](https://github.com/Courseplay/courseplay/files/4580845/log.txt)

**Comment by Thomasrev** [comment]
I have the same problem with working in the trenches

**Comment by ontot** [comment]
hi to all... some news?

**Comment by bibifr** [comment]
Got exactly same issue as ontot

**Comment by seminexx** [comment]
I have the same problem. 
when i start my pc, the game freezes and the driver just drives in circles.

[log.txt](https://github.com/Courseplay/courseplay/files/4638033/log.txt)

**Comment by seminexx** [comment]
I have the same problem.
when i start my pc, the game freezes and the driver just drives in circles.
[log.txt](https://github.com/Courseplay/courseplay/files/4638039/log.txt)

**Comment by polosubtil** [comment]
Hi @pvaiko 
I also have the same issue. Just a thought here, looks like the blade height calculation isn't going well, could that be linked to this code ? Especially on the return ?

function LevelCompactAIDriver:getDiffHeightforHeight(targetHeight)
	local blade = self.vehicle.cp.workTools[1]
	local bladeX,bladeY,bladeZ = getWorldTranslation(self:getLevelerNode(blade))
	local bladeTerrain = getTerrainHeightAtWorldPos(g_currentMission.terrainRootNode, bladeX,bladeY,bladeZ);
	local _,_,offSetZ = worldToLocal(self.vehicle.rootNode,bladeX,bladeY,bladeZ)
	local _,projectedTractorY,_  = localToWorld(self.vehicle.rootNode,0,0,offSetZ)

	return targetHeight- (projectedTractorY-bladeTerrain)
end

**Comment by aviator64** [comment]
I have the same issue. This is on a course, and with the same equipment, that worked OK with 6.01.398. I tried recording a new course with 6.02.17 and the same issue persists. So, something happened to Leveling/Compacting mode under 6.02.

Do you need any additional log files?
