### ISSUE TITLE
Straw Harvest - Support for manual refill option

### ISSUE THREAD

**Issue by MicaelJarniac** [Courseplay/courseplay#5307]
| Mod | Version |
| -- | -- |
| [**Straw Harvest**](https://git.creative-mesh.com/projects/STRAW/repos/fs19_beta_strawharvest/browse) | `v1.0.0.2-beta` |
| [**Courseplay**](https://github.com/Courseplay/courseplay/releases) | `v6.02.00006` |

The **Premos 5000** from the Straw Harvest mod allows turning loose straw, hay or bales into pellets, and to function it needs water and molasses.

The problem is, if set to manually be refilled, Courseplay seems to believe that it needs to be unloaded, even if it has little or even no pellets stored, probably because it believes that it needs to unload the water and/or molasses.

[Video](https://drive.google.com/file/d/1cy9k32Qr4czeHp7Cs9qFUtJ8Jl9tQi8Z/view?usp=drivesdk) and [log](https://pastebin.com/v8msqdGL).

I believe this is a know issue, and probably the reason that users are told to buy the tools with the automatic refill option, but I didn't find an issue directly related to it, so I decided to open a new one.

**Comment by Tensuko** [comment]
Won't add extra support for manual refill.
