### ISSUE TITLE
Verify If New Behavior is Intentional

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#5308]
When I create a a course for my tractor to offload the combine and click to stop the recording I have always set it to go to Current Waypoint. This would cause the tractor to stop and wait for the combine to be at least 50% full. Now, however, the tractor immediately drives off to the sell point. If something happens during the running of the course, and I need to stop the tractor and restart it, the tractor will immediately head for the sell point. Was this change intended? It happens with the generic equipment as well as with mods.

2nd thing I notice is that if you have the strobes on when you start a course using the combine, they stay on. Now it is also happening with the tractors even though I have it set to default on the road only.

3rd thing is that none of the tractors can seem to find where they need to be under the pipe when side offset is set to auto. I have to always manually move it left. It appears to be using the header only to guide its offset distance.
[log.txt](https://github.com/Courseplay/courseplay/files/4584427/log.txt)

**Comment by lcc1211** [comment]
Reading through your notes I see this: Unloader won't drive to the combine until the combine is 100% full.
The problem is that the combine stops when it gets to 99%, so the tractor won't head over to the combine.

**Comment by MicaelJarniac** [comment]
@lcc1211, take a look at #5272:

> Select 'Unload' as a starting point to wait for the combine requesting an unloader, any of the other option will make you start on the unload course

I believe this was introduced in `v6.02.00001`, and it probably is the solution for the first issue you reported.

**Comment by lcc1211** [comment]
> 
> 
> @lcc1211, take a look at #5272:
> 
> > Select 'Unload' as a starting point to wait for the combine requesting an unloader, any of the other option will make you start on the unload course
> 
> I believe this was introduced in `v6.02.00001`, and it probably is the solution for the first issue you reported.

I think the next issue will be that the tractor still won't head for the combine, though, since it stops filling at 99%.

**Comment by MicaelJarniac** [comment]
> 3rd thing is that none of the tractors can seem to find where they need to be under the pipe when side offset is set to auto. I have to always manually move it left. It appears to be using the header only to guide its offset distance.

Take a loot at this comment: https://github.com/Courseplay/courseplay/issues/5281#issuecomment-623179859

There seems to be a known issue with the Tatra truck, it might be the same as your third issue. I'd suggest trying another truck and seeing if it's still positioned incorrectly, or if it's now in the right position.

**Comment by Tensuko** [comment]
All info is in #5272 
The combine will call the driver if it is 'full' no matter of 90% 95% or 99% the Combine decide it.

This maybe helps too. https://www.youtube.com/watch?v=895zpaeE8iU
If still got a problem make an Issue with requested information as in #5272
