### ISSUE TITLE
[Suggestion] Latest release download shortcut

### ISSUE THREAD

**Issue by MicaelJarniac** [Courseplay/courseplay#5309]
This is a follow up to #5286.

Now that the mod file has a consistent name on each release (`FS19_Courseplay.zip`), automating the download of it has become a lot simpler.

GitHub itself has this neat URL trick:
https://help.github.com/en/github/administering-a-repository/linking-to-releases

Basically, if you know the name of the file you want, `https://github.com/owner/name/releases/latest/download/asset-name.zip` will download it straight from the latest release.

The catch is, it doesn't work for **pre-releases**, only for **releases**.

This link takes you straight to Courseplay's latest "release":
https://github.com/Courseplay/courseplay/releases/latest

Note that it's a very old release, back in 2018, and it's for FS17, but still, it's technically the "latest release", as all following releases were marked as "pre-release".

Having the newer releases marked as "release", and not "pre-release" would allow the following static URL to always download whatever the latest version of Courseplay is:
https://github.com/Courseplay/courseplay/releases/latest/download/FS19_Courseplay.zip

**Comment by Tensuko** [comment]
Becouse this is very hard to finde...
https://github.com/Courseplay/courseplay/releases

**Comment by MicaelJarniac** [comment]
It's already very easy to go in there and download the latest release manually, and it's not like what I suggested is going to make it a whole lot easier, but it's something that's possible, and I think it's pretty cool.

But sure, it's just like a click or two shorter than going in https://github.com/Courseplay/courseplay/releases then clicking the file you want, so it's not going to make that much of a difference, but it's something to have in mind. And it could help people that get completely lost in GitHub.

And if the website gets updated (something that I'll see if I can maybe even help with, I like writing stuff), there could be a simple download button there that downloads the file straight away, instead of taking the user to the releases page for them to find what they want themselves.

Again, not a priority, just a cool trick to automate things a tiny bit more.

**Comment by TinyCrocodile** [comment]
See #5135 for auto updates

**Comment by pvaiko** [comment]
@MicaelJarniac changed the Node.js webhook code to create regular release.
