### ISSUE TITLE
shredded drain

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#5312]
I wanted to know if it was possible to change the fact that the trailer (while it is moving in the back) unloads immediately as soon as it entered the trench trigger. I ask why the tractor often makes the back, begins to unload but being the large trailer it cannot unload everything at that point and gets stuck there. Is it possible to implement the fact that if it fails to fully download it moves forward to finish? Couldn't it also be made during the recording of the route whether to unload at the beginning of the trench or further back? In the sense that if you want to unload it does it automatically, but if for example you manually put an unloading point (while recording the route) further back in the trench the trailer unloads at that point?

**Comment by Tensuko** [comment]
You talk about unload at a specific point ?
What version do you use ? Logfile ? ......

**Comment by 0Pietro20** [comment]
When I encountered that problem I used v6.01.00398. Unfortunately I don't have the log but I will recreate that situation and if it happens again I will report by entering the log. When it happened I tried to chop in a field and everything was fine (except maybe some AI problems that crashed against the forage harvester during the maneuvers) only that I arrived at the trench (I had recorded the drain in the back since the trench was closed) the tractor stopped as soon as the trailer had entered the trench and unloaded, even though I had inserted an unloading point further back in the path. I used the Bossini trailer and after unloading about 80% of the load it stopped because it was unable to unload other material on the ground and remained stationary; I had to stop the path and move it manually.
However, this morning I had problems with courseplay, I noticed that I do not have the updated version and I downloaded it. I know it is still in progress, but I tried to use a forage harvester hooked into a tractor and, after setting the paths, the tractor that should approach the forage harvester to allow it to unload on the trailer, while recognizing the tractor as threshes, does not approach and remains still. I report the log below

[log.txt](https://github.com/Courseplay/courseplay/files/4587439/log.txt)

**Comment by Tensuko** [comment]
Did you read #5272 ?
Also I have a smal Video on how it works:
https://www.youtube.com/watch?v=895zpaeE8iU&t=3s
I know its german but the Things you got to do stays the same.
Assign the Unloader to the Combine you want to unload.
Still wonder where the Error came from.
Maybe a logfile with channel 4 7 12 and 14 can help.
Also Screenshots about Course and what Tools you did use.

**Comment by 0Pietro20** [comment]
Okay, I will show the various screens and if I can I will make a small video so as to show the situation well. I hope it can help implement the forage harvesters attached to the tractor, I would love to be able to use them

**Comment by 0Pietro20** [comment]
I hope this video is fairly explanatory and correct. If by chance you need more information or videos ask for it


[Farming Simulator 19 2020-05-06 20-39-50_Trim.zip](https://github.com/Courseplay/courseplay/files/4588870/Farming.Simulator.19.2020-05-06.20-39-50_Trim.zip)

[Farming Simulator 19 2020-05-06 20-39-50_Trim (2).zip](https://github.com/Courseplay/courseplay/files/4588878/Farming.Simulator.19.2020-05-06.20-39-50_Trim.2.zip)

[log.txt](https://github.com/Courseplay/courseplay/files/4588831/log.txt)

![Farming Simulator 19 06_05_2020 20_42_08](https://user-images.githubusercontent.com/59969508/81215957-69ddaf80-8fda-11ea-8270-c7951ef8233d.png)

**Comment by Tensuko** [comment]
Towed tools are not fully supported right now I think, need to check commits but I think it is not done yet. Ofc this will be supported later.

**Comment by Tensuko** [comment]
![fsScreen_2020_05_12_17_48_00](https://user-images.githubusercontent.com/27344744/81715677-c75d7a80-9478-11ea-9023-6df9dfbf1278.png)
With Version 12 it is in the List, he drives to the tool, but the tool got a not so good position for the distance control and/or can't throw far enough so the Mode2 driver won't reach the Trailer.

**Comment by TinyCrocodile** [comment]
Picture of the real one. Here the driver is more beside the comine not behind. Not shure how to set it up like this.
[https://cdn.poettinger.at/img/landtechnik/collection/scheibenradhaecksler/mex_6_2.jpg](url)

**Comment by Tensuko** [comment]
We didnt design the first mode2 version based on all real use of any tools :) main part was to drive behind a chopper for headland and in racetrack so he won't leave the field and colide with any object. We sure try find a solution for those things later. For now only the bigX runs very good for chopping.

**Comment by TinyCrocodile** [comment]
> We didnt design the first mode2 version based on all real use of any tools :) 
Yes i know that. I was just curious how the machine is suposed to be used because the mod also has a attacher for a trailer.
I was tinking a more "fixed pipe" approach might worked better on this one as i saw the picture. Sorry for the spam.

**Comment by Tensuko** [comment]
This should work just fine now I think.
Closing, if still got problems, pls check similar Issues first to add it there.
