### ISSUE TITLE
Error: Running LUA method 'update' - CombineUnloadManager.lua:187: attempt to index local 'data' (a nil value)

### ISSUE THREAD

**Issue by answermanitou** [Courseplay/courseplay#5317]
Hello again
Sudenly started error.
3 fields, 1combine and 1vehicle on each

[log.txt](https://github.com/Courseplay/courseplay/files/4588452/log.txt)
![fsScreen_2020_05_06_20_37_31](https://user-images.githubusercontent.com/64743178/81210249-4dda0e00-8fda-11ea-8ddc-2bc2bcea6cc0.png)

**Comment by Tensuko** [comment]
Load mod: FS19_addon_strawHarvest (Version: 1.0.0.0) (Hash: 1d15f60600f67db89fc72447145539f4)
Get Version 1.0.0.2 Beta from Creative Mesh Discord.

This can cause Problems, but Wopster is working on it:
Load mod: FS19_manureSystem (Version: 1.0.0.0) (Hash: f6e43e963a789d956eb7c4212c305a4c)

This could cause Trouble too:
2020-05-06 20:12 Error: Can't load resource 'C:/Users/manitou/Documents/My Games/FarmingSimulator2019/mods/FS19_CM_CR9000Series/scripts/threshingFlowIndicator.lua'.
2020-05-06 20:12 Error: Vehicle type 'FS19_CM_CR9000Series.combineDrivableAnimated' has unknown specialization 'FS19_CM_CR9000Series.threshingFlowIndicator'!
2020-05-06 20:12   Error: Specialization 'foldable' already exists for vehicle type 'FS19_CM_CR9000Series.combineDrivableAnimated'!

For the Error of CP.
Could it be that you did a Contract Mission and Finished it ?
Or what did you do when this Error appeared ?

**Comment by answermanitou** [comment]
I'm also think about two mods of combines. I just right now restarted game, sold mod combines. Now we are working with caseih basic. Looks like there are no problem.

**Comment by answermanitou** [comment]
No 
Problem has to be.
Combine doesn't call unloader. But 1st combine works great with unloader. The 2nd and 3rd no, they are both reach 100% but unloader wait for call. At last the game was down.

**Comment by answermanitou** [comment]
there is log with debug
[log.txt](https://github.com/Courseplay/courseplay/files/4588719/log.txt)

**Comment by answermanitou** [comment]
What was before.
1st combine with generated course work properly. Unloader works by saved course. Ok
2nd combine works with helper. Unloader was staying in finish point of unloading course and wait 50% combine. In settings was select combine from the field X but CP doesn't select this combine.
3rd combine working with CP generated course. Unloader do the same as with 2nd combine -- nothing. 
Its all in different fields

**Comment by Tensuko** [comment]
Mode2 can only unload Combine that runs with CP.
The % is not working right now and might geet replaced by a more intelligent system.
3 Fields, each combine runs in a different way?
So each Combine got one Unloader ?

**Comment by answermanitou** [comment]
> Mode2 can only unload Combine that runs with CP.
> The % is not working right now and might geet replaced by a more intelligent system.
> 3 Fields, each combine runs in a different way?
> So each Combine got one Unloader ?

Yea. 1 combine and 1 unloader per field 
About mode 2 its important for me that must be cp course for combine and unloader

**Comment by Tensuko** [comment]
Yes, currently only works with CP and each need one course.

**Comment by answermanitou** [comment]
> Yes, currently only works with CP and each need one course.

Ok. If we have 3 fields that operate with 3 combines with generated Cp. Can I use one unloading course for two field by different tractors?

**Comment by Tensuko** [comment]
Yes. You could also use one Tractor to unload both Combine. Or 1 Course with 2 Tractor that unloads one Combine each on a different field.

But the LUA Error need to find out what happened too :)

**Comment by answermanitou** [comment]
If you sad that unloader must be operated with cp course combine it might do the game crash

**Comment by Tensuko** [comment]
Maybe you can see how it can work:
https://www.youtube.com/watch?v=895zpaeE8iU
2 Fields, one Combine on each Field with its own Course. One Unloader with one Course but can unload both Combines.

**Comment by answermanitou** [comment]
> Maybe you can see how it can work:
> https://www.youtube.com/watch?v=895zpaeE8iU
> 2 Fields, one Combine on each Field with its own Course. One Unloader with one Course but can unload both Combines.

Interesting.
Will try it next season.
At now I understood for what you add combine select.
Thank you for a video

**Comment by answermanitou** [comment]
![P_20200507_121335](https://user-images.githubusercontent.com/64743178/81277048-87ebf400-905c-11ea-8c46-2548e3142900.jpg)
looks like ropa panther and holmer doesn't work together. Also ropa doesn't call fendt favorit unloader

**Comment by answermanitou** [comment]
![P_20200507_122412](https://user-images.githubusercontent.com/64743178/81277491-2b3d0900-905d-11ea-82c6-b4cd4449cdcf.jpg)
waiting for call from combine ... The combine is calling

**Comment by Tensuko** [comment]
Assigned the Tractor to that Combine ?

**Comment by answermanitou** [comment]
> Assigned the Tractor to that Combine ?
> 
> Holmer is some other Issue.

Tractor doesn't respond ropa 
In combine select later I select "combine from this field" but cp from tractor don't see any combine. Of course it will be staying forever.

Before I launch holmer as unloader for ropa and holmer is saw combine in selected fields but don't went to him

**Comment by Tensuko** [comment]
You cant select a field. It is only a Filter for the List.
You have to assigen the combine like shown in my video. If the combine is not in the list, it didnt register into it or like in your case the towed tools are not fully supported yet.

**Comment by answermanitou** [comment]
I should be leave house.
Now restart fs19, again generate course for ropa. Load course for unloader and in combine list be present all available combines from map, select ropa but tractor continue staying . Fail

**Comment by answermanitou** [comment]
Restart the game again, but with ver 399 CP. Its all works. Ropa as always calling to the unloader. Unloaded equipped by fendt 500 is answer to call and confidently go to the combine

**Comment by Tensuko** [comment]
I dont know what you expect to happen...
Assign combine to unloader (only CP Driver)
Wait till Combine is full.
Unloader will drive to Combine.

**Comment by Tensuko** [comment]
Version 399 and lower is not supported anymore!

**Comment by answermanitou** [comment]
> Version 399 and lower is not supported anymore!

I understood this. I did this for experiment, will work or not

**Comment by Tensuko** [comment]
399 use the super old Driver.
00009 use the complete new Programmed Driver.
There is nothing you can compare to the old System.
The old System have many other Issues.

**Comment by answermanitou** [comment]
> I dont know what you expect to happen...
> Assign combine to unloader (only CP Driver)
> Wait till Combine is full.
> Unloader will drive to Combine.

I assigned combine and unloader. Combine was almost full when I start course and reach 100% but unloader still waiting for call

**Comment by Tensuko** [comment]
Try Version 12 or higher and report.

**Comment by answermanitou** [comment]
I do it later. In a game now middle of spring. 
Can I ask about silage harvester in mode 2? Is it workable with 2 or 3 unloaders per 1 harvester? It will be use 1 unloading course for bga station.

**Comment by answermanitou** [comment]
There is no time to work with sugar been. 
I have a trouble with 012 CP
1st of all i check that all preferences are that you recomended -- offset is auto. Fill level default. Harvester in vehicle CP window was selected.
1st field has case harvester and favorit unloader. generated course harv and saved course for unloader. Probably works properly.
2nd field has case harvester and fovorit unloader. generated course for harv and saved course for unloader. The unloader has different course from 1st. I remember for it. But but but. First of all unloader was not stable under unloader pipe it run forward/backward and dont unload harvester to empty level. Is catch ~20% and go backward to temp position. Second was that after emtying wagon the unloader were came from unloading course to the finish point and wait for call from harvester(in this moment it was 95% filling). It run to harvester only after force call from harvester. I attach many screenshoot and LOG wit debug 4.
in same time I have 2 worked vehicles on different fields and courses. All vehicles are vanilly
Will be great that U does unloading harvester not from full load 
![fsScreen_2020_05_12_21_29_32](https://user-images.githubusercontent.com/64743178/81733725-259b5500-949b-11ea-81df-84a93cd1b17a.png)
![fsScreen_2020_05_12_21_29_02](https://user-images.githubusercontent.com/64743178/81733747-2af89f80-949b-11ea-8318-ef6452e8f237.png)

 
[log.txt](https://github.com/Courseplay/courseplay/files/4617823/log.txt)
![fsScreen_2020_05_12_21_34_31](https://user-images.githubusercontent.com/64743178/81733704-203e0a80-949b-11ea-9aaf-68c759779be2.png)
![fsScreen_2020_05_12_21_33_42](https://user-images.githubusercontent.com/64743178/81733713-22a06480-949b-11ea-9ee5-58f480ad157c.png)

**Comment by answermanitou** [comment]
I forget to say. The game was total down no any respond for keyboard. Thanks god the console is working

**Comment by answermanitou** [comment]
> Try Version 12 or higher and report.

Reporting. Work bad(

**Comment by answermanitou** [comment]
Watch the log. @Tensuko   It was between screenshots
[log (1).txt](https://github.com/Courseplay/courseplay/files/4624709/log.1.txt)

**Comment by answermanitou** [comment]
I read log and there is horde of 561 bug error

**Comment by Tensuko** [comment]
Still in GC so can throw out:
FS19PlaceAnywhere (Version: 1.3) (Hash: 11b65320d12e68e420ea60d91bce11ab)

Still not supported, get Beta 27 (1.0.0.2) from Creative Mesh Discord:
FS19_addon_strawHarvest (Version: 1.0.0.0) (Hash: 1d15f60600f67db89fc72447145539f4)

As well not supported, try the newest Version from GitHub:
FS19_manureSystem (Version: 1.0.0.0) (Hash: f6e43e963a789d956eb7c4212c305a4c)


> First of all unloader was not stable under unloader pipe it run forward/backward and dont unload harvester to empty level.

That is becouse of target is to close to the middle, suggest do use some offset.
Also we are going to tweak this a bit.

Since you have more Problems then just the move to Combine it is hard to support this.

2020-05-12 21:17 Error: Running LUA method 'draw'.
2020-05-12 21:17 C:/Users/manitou/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/hud.lua:610: attempt to index local 'selectedField' (a nil value)

2020-05-12 21:36 Error: Running LUA method 'update'.
2020-05-12 21:36 C:/Users/manitou/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CombineUnloadAIDriver.lua:561: attempt to perform arithmetic on local 'dz' (a nil value)
+ Callstacks.

**Comment by answermanitou** [comment]
hello. Its still working bad.
One field works succesfuly
Second field doesnt -- only one time unloader came to harvester. Than he is stay and waiting for a long time.
watch the Log
[log.txt](https://github.com/Courseplay/courseplay/files/4627732/log.txt)

![fsScreen_2020_05_14_13_38_20](https://user-images.githubusercontent.com/64743178/81925349-0d395080-95e9-11ea-8418-9f0ddbc117cb.png)
![fsScreen_2020_05_14_13_38_07](https://user-images.githubusercontent.com/64743178/81925353-0f031400-95e9-11ea-8d4a-7482d6558c6d.png)
![fsScreen_2020_05_14_13_37_21](https://user-images.githubusercontent.com/64743178/81925356-0f9baa80-95e9-11ea-9bc4-22792a697f74.png)
![fsScreen_2020_05_14_13_36_13](https://user-images.githubusercontent.com/64743178/81925361-10344100-95e9-11ea-93da-c909edfb36e0.png)
![fsScreen_2020_05_14_13_35_59](https://user-images.githubusercontent.com/64743178/81925363-11656e00-95e9-11ea-9a67-90cea6cd99aa.png)

**Comment by answermanitou** [comment]
I also have much Fps down while CP working in mode 2

**Comment by Tensuko** [comment]
Chaotic Issue and not rly helpful. Also outdated, closing...
