### ISSUE TITLE
Help Please Combine doesn't call unloader

### ISSUE THREAD

**Issue by anz1000** [Courseplay/courseplay#5319]
Hi guys first off thanks for Courseplay much appreciated !!!!
I have an issue with Mode two ,the Combine doesn't call the unloading tractor and trailer i have to manually call it from the HUD it works sometimes but mainly i have to call it myself . 
The unloding tractor is set to mode two and the combine is checked in the box on Hud, not sure if im doing something wrong i think ive followed the set up correctly any help would be much appreciated .
![fsScreen_2020_05_06_19_19_47](https://user-images.githubusercontent.com/64729869/81215305-0ef38a80-8fd1-11ea-90a5-bacc8d0605e5.png)
![fsScreen_2020_05_06_19_19_06](https://user-images.githubusercontent.com/64729869/81215319-161a9880-8fd1-11ea-9b6f-39206b67ea16.png)
![fsScreen_2020_05_06_19_18_44](https://user-images.githubusercontent.com/64729869/81215390-2df21c80-8fd1-11ea-8113-53587eb804d1.png)

[Log.pdf](https://github.com/Courseplay/courseplay/files/4588796/Log.pdf)

**Comment by anz1000** [comment]
Sorry forgot to mention the start point on Hud is set to Unload on the unloading Tractor

**Comment by pvaiko** [comment]
Please next time no PDF logs, just plain text, this is hardly readable.

Also, you seem to have two unloaders involved here, as we said, that is not supported yet. 

I'm closing this now, if you can describe exactly what the two unloaders were doing when so we can somehow reproduce it, please reopen.

**Comment by anz1000** [comment]
Sorry didn't realise that two unloaders weren't supported yet . Many thanks for reply . Do i just copy and paste the log instead of Pdf ?

**Comment by TinyCrocodile** [comment]
Just drag and drop .txt file into the issue field.

**Comment by anz1000** [comment]
[log.txt](https://github.com/Courseplay
[log.txt](https://github.com/Courseplay/courseplay/files/4598737/log.txt)
[log.txt](https://github.com/Courseplay/courseplay/files/4598752/log.txt)

/courseplay/files/4598736/log.txt)
