### ISSUE TITLE
New mode 2 issue with proximity and front loader tool

### ISSUE THREAD

**Issue by vorezal** [Courseplay/courseplay#5320]
I'm using Courseplay 6.02.00008. Log file (hopefully the right one) attached.

When trying out the brand new mode 2 I happened to use a tractor with a front loader still attached. I think it is registering the tool as an obstruction and thinks it should remain stopped after path finding is successful and self.onFieldState is DRIVE_TO_COMBINE. I'm sure the log file contains both the issue and successes as I went through some trial and error testing. Look for lines where the T234 tractor sees a proximity of 0.3 or 0.4 and stops. I tried another tractor, which worked fine, and then I tried the original with the front tool removed and it worked as well.

Pretty easy issue to work around. Perhaps this post will help someone out if they happen to run into the same thing though.

[log.txt](https://github.com/Courseplay/courseplay/files/4588835/log.txt)

**Comment by Tensuko** [comment]
Thats a known Issue and we can only suggest you do use Mode2 without anny front Tools Attatched :)

**Comment by vorezal** [comment]
Thanks Tensuko. Really appreciate all the effort and work on the new Mode 2 by the way :)

**Comment by pvaiko** [comment]
Actually, I have code in front attached implements, only tested with a weight though but that worked fine, placed the proximity sensor on the front of the weight. Which tractor/frontloader?

**Comment by pvaiko** [comment]
Closed due to inactivity.
