### ISSUE TITLE
[Suggestion] Kursgenerator Standardeinstellung/Speicherfunktion

### ISSUE THREAD

**Issue by VatriXxX** [Courseplay/courseplay#5321]
Hallo,
ich hab da mal eine Frage bzw. Vorschlag, ist es möglich eine Standardeinstellung für den Kursgenerator zu setzen? Denn ich stelle immer die Startposition, Vorgewende (mit mehreren Bahnen) und überspringe Bahnen (1) ein und dies muss ich immer wieder neu einstellen...

Wenn ich ein Kurs für ein Feld generiere wäre es toll, wenn ich die Sachen einmal einstelle und es sich merkt. Denn aktuell ist es ja so, dass wenn ich das gleiche Fahrzeug für ein anderes Feld nehme (ohne das Spiel zu schließen) dann behält er die Einstellungen ja.
Aber wenn ich ein anderes Fahrzeug nehme oder das Spiel beende, dann muss ich ebenfalls das alles wieder neu einstellen.

Und ist es da nicht möglich eine Speicherfunktion einzubauen oder gar, dass man dies als Standardeinstellungen setzen könnte?

Mit freundlichen Grüßen
VatriXxX

**Comment by Tensuko** [comment]
Könnte mir Vorstellen Buttons zu machen und dort Presets speicherbar zu machen.

**Comment by VatriXxX** [comment]
Das hört sich doch super an, gefällt mir, freue mich schon :) , das macht die Sache einfacher.

**Comment by Merrlin** [comment]
Da suggested ich gleich mit. 
So ne Dropdownliste mit den gespeicherten Pressers wäre wirklich nice. 
Da kann man sich dann quasi die einzelnen Pressers für die Arbeitsgeräte auswählen
