### ISSUE TITLE
Abfahrer tankt Drescher nicht ab v6.02.00006

### ISSUE THREAD

**Issue by Mapela80** [Courseplay/courseplay#5322]
Wie mit Tensuko grad besprochen:
leerer Abfahrer steht auf dem Feld Drescher is voll, wird aber vom Abfahrer nicht erkannt oder aber erkannt aber fährt dennoch nicht los. In der Log stand sowas wie Path with Tucano not found Screenshot und Log sind dabei. Spiele die Gemeinde Rade. Die erste Fuhre hat er auch angetankt und danach stand Abfahrer nur noch auf dem Feld. 

Ihr macht nen SUPER guten Job, danke!!!

[log.txt](https://github.com/Courseplay/courseplay/files/4588970/log.txt)
![fsScreen_2020_05_06_21_02_45](https://user-images.githubusercontent.com/35222702/81218091-ec1ba300-8fdd-11ea-99a6-e9277804980c.png)

**Comment by pvaiko** [comment]
1. Ab 6.02.00009 kannst jetzt die Fruchtumfahrung auschalten, dann muss es gehen
2. Oder Fruchtumfahrung eingeschaltel lassen aber dann Traktor nicht in die Frucht fahren, irgendwo weit genug von Frucht damit der auch Wenden kann wenn nötig, ohne in die Frucht fahren zu müssen.
