### ISSUE TITLE
Problem unloading beet thresher

### ISSUE THREAD

**Issue by ritmodromo** [Courseplay/courseplay#5325]
Hi I have tried mode two with the rootster griemme in mode 2 with both workers in couseplay even if they arrive at 100% charge the worker is not called by the thresher I loaded the log with the debug channels activated 4, 7, and 14 and I downloaded the log I tried them all but it doesn't work.
![fsScreen_2020_05_07_08_45_29](https://user-images.githubusercontent.com/64949735/81264048-118dc880-9041-11ea-9663-9de1151d8f3a.png)
![fsScreen_2020_05_07_08_45_29](https://user-images.githubusercontent.com/64949735/81264296-72b59c00-9041-11ea-81b6-03988da7ddc1.png)
![fsScreen_2020_05_07_08_45_51](https://user-images.githubusercontent.com/64949735/81264306-76492300-9041-11ea-9bdc-06020d2bce70.png)
![fsScreen_2020_05_07_08_47_17](https://user-images.githubusercontent.com/64949735/81264310-78ab7d00-9041-11ea-9d36-ea3a88a4a88d.png)
![fsScreen_2020_05_07_08_47_23](https://user-images.githubusercontent.com/64949735/81264316-7b0dd700-9041-11ea-8732-9e4d6c0520be.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4591229/log.txt)

**Comment by Tensuko** [comment]
Better handling of towed harvesters (still work in
progress) (Version 00004 Commit Info).
Also I don't see a screenshot where you assigned the Unloader to the Combine.
Another thing I got to mention is, you should not use 2 Trailer, as this won't be able to reverse.

**Comment by ritmodromo** [comment]
![fsScreen_2020_05_07_09_59_24](https://user-images.githubusercontent.com/64949735/81269521-b6140880-9049-11ea-8374-f4e53dcd8d6b.png)
