### ISSUE TITLE
Fahrzeug friert ein wenn Abfahrer eingestellt wird + Lua Call Stacks

### ISSUE THREAD

**Issue by MMaarrttiin** [Courseplay/courseplay#5328]
Ich habe das Problem, dass wenn ich einen Abfahrer einstelle, der Abfahrer nichts macht, und ich im Fahrzeug auch nichts mehr machen kann. Es erscheint lediglich ein gelber Pfeil im Courseplay Menü. (Siehe im beigefügten Bild). 
![Farming Simulator 19 07 05 2020 15_28_37](https://user-images.githubusercontent.com/47082404/81299553-aeb72400-9076-11ea-9a53-e21cc331548a.png)
![Farming Simulator 19 07 05 2020 15_28_50](https://user-images.githubusercontent.com/47082404/81299635-ca222f00-9076-11ea-9741-5812c2a21a8b.png)

[log.txt](https://github.com/Courseplay/courseplay/files/4593132/log.txt)

**Comment by Tensuko** [comment]
Hast du das Pelletkraftwerk zufällig platziert ? Ich weis nicht ob das die neueste Version ist.... leider haben die Jungs die Version nicht hoch gezählt, daher weis ich nicht ob das nun die richtige Version ist.
Load mod: FS19_addon_strawHarvestBonus (Version: 1.0.0.0) (Hash: d22b91ab8b399d815468276bf8d6e04e)

Ansonsten kannst du bitte mal testweise das manure system raus nehmen und schauen ob der Fehler noch auftritt ?

**Comment by MMaarrttiin** [comment]
Das habe ich platziert ja, werde ich ausprobieren, das kommt mir eh komisch vor da ich mit dem Kraftwerk Geld bekomme obwohl da nix drinne ist. Das Manure System habe ich im Modordner aber nicht aktiviert.

**Comment by Tensuko** [comment]
Dann hört sich das sehr nach dem Kraftwerk an, ich würde das einmal neu runter laden auch wenn es dann die gleiche Version ist.

**Comment by MMaarrttiin** [comment]
Ja, es lag am Kraftwerk. Ich probiere dann es einmal neu herunterzuladen, wenn das dann auch nicht geht muss es auch ohne das Heizkraftwerk gehen, danke nochmal

**Comment by Tensuko** [comment]
Mit der aktuellen Version (man kann es nur am HASH Wert erkennen) sollte es gehen, hab es ja mit Wopster zusammen getestet :)

**Comment by lxfTTjek** [comment]
6.02Can we solve the problem of frame dropout?

**Comment by Tensuko** [comment]
> 
> 
> 6.02Can we solve the problem of frame dropout?

Totaly wrong Issue for this, no details, no log nothing at all.....

**Comment by Tensuko** [comment]
> 
> 
> Ja, es lag am Kraftwerk. Ich probiere dann es einmal neu herunterzuladen, wenn das dann auch nicht geht muss es auch ohne das Heizkraftwerk gehen, danke nochmal

Ich nehme das mal als erledigt.
Ansonsten melde dich noch mal hier, dann muss man weiter schauen.
