### ISSUE TITLE
Semi Not Moving in Mode 2

### ISSUE THREAD

**Issue by stangman04** [Courseplay/courseplay#5331]
Playing on my multiplayer server and using a semi with a trailer to unload my combines. I have downloaded the latest release (6.02.00010) but when the fill level is reached the semi does not move. Combine is selected. This mode works with version 397 but anything newer and I have this issue.

![image](https://user-images.githubusercontent.com/47079766/81318418-393e5a00-905c-11ea-87ce-671fb90eafbe.png)

Not going to read a log like that - Tensuko
[log.txt](https://github.com/Courseplay/courseplay/files/4594266/log.txt)

**Comment by Tensuko** [comment]
Drag and drop the log.txt into comment box.
It is written down in the box... Attach files by dragging & dropping, selecting or pasting them.
Else it is unreadable.....

**Comment by Tensuko** [comment]
> 
> 
> Playing on my multiplayer server and using a semi with a trailer to unload my combines. I have downloaded the latest release (6.02.00010) but when the fill level is reached the semi does not move. Combine is selected. This mode works with version 397 but anything newer and I have this issue.

Also no support for Versions older then 6.02.0000X

Version 397 is a completly old and outdated system for Mode2 Combi Unloader.

**Comment by stangman04** [comment]
Log file added.

**Comment by Vanishoxyact** [comment]
As a note, the new mode 2 does not currently work with multiplayer (if you're on a dedicated server anyway). I'm having some fun trying to fix it!

**Comment by stangman04** [comment]
> As a note, the new mode 2 does not currently work with multiplayer (if you're on a dedicated server anyway). I'm having some fun trying to fix it!

Ah then I guess I need to revert back to the older version until things are ironed out. I saw multiplayer fixes in the update today and figured I would try but I guess it is still a work in progress.

**Comment by KawaiiHalo** [comment]
I don't know if this is any help, but I am receiving this issue in single-player on 6.02.00010.

[log.txt](https://github.com/Courseplay/courseplay/files/4595373/log.txt)

**Comment by Kn1ghtwolf** [comment]
I'm having the same problem on SP it just sits there even tho my combine sitting there full and calling for the truck
![2020-05-12 (1)](https://user-images.githubusercontent.com/50271046/81714102-b4c94e00-9444-11ea-98b5-d01aee87ae48.png)
![Uploading 2020-05-12 (2).png…]()

**Comment by Kn1ghtwolf** [comment]
![2020-05-12 (3)](https://user-images.githubusercontent.com/50271046/81714291-eb06cd80-9444-11ea-8573-e4e0715594a0.png)

**Comment by Tensuko** [comment]
And where is your information we request ? Also you sit in the fruit how to calculate a way arround it ? Turn off pathfind in the HUD and not adv settinga and try again

**Comment by Kn1ghtwolf** [comment]
My pathfinding is deactivated and same with my turning on field log is there I deleted the other because I noticed it didn't have the log and I've messed with all advance settings on the combine and the truck and it still just sits there regardless if it's in the fruit or not I've recorded 2 courses never had an issue until most recent update

**Comment by stangman04** [comment]
> My pathfinding is deactivated and same with my turning on field log is there I deleted the other because I noticed it didn't have the log and I've messed with all advance settings on the combine and the truck and it still just sits there regardless if it's in the fruit or not I've recorded 2 courses never had an issue until most recent update

They mark this as a MP issue but I just played in single player with the latest version and still have this issue. I will test with a auger trailer but with a semi trailer and semi this mode no longer works for me. I keep reverting back to version 397 due to this issue with the new mode 2.

**Comment by stangman04** [comment]
![image](https://user-images.githubusercontent.com/47079766/82765410-cb788900-9de4-11ea-973c-e470855f7ce7.png)


[log.txt](https://github.com/Courseplay/courseplay/files/4674449/log.txt)

**Comment by Tensuko** [comment]
Collecting all in #5484
