### ISSUE TITLE
Spiel startet nnicht

### ISSUE THREAD

**Issue by IchDummer** [Courseplay/courseplay#5334]
Wenn ich die letzte Version verwende, satartet das Spiel nicht.
[FS19 log 07.05.20.docx](https://github.com/Courseplay/courseplay/files/4595398/FS19.log.07.05.20.docx)

**Comment by Tensuko** [comment]
why did you save a logfile in a .docx ???

**Comment by IchDummer** [comment]
Hier die log nocheinmal
[log.txt](https://github.com/Courseplay/courseplay/files/4599166/log.txt)

**Comment by Tensuko** [comment]
Ich vermute irgend eine Mod bei dir macht Probleme:
2020-05-07 21:07 Error: Running LUA method 'loadSharedI3DFileFinished'.
2020-05-07 21:07 C:/Users/werne/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay6/toolManager.lua:196: attempt to compare number with nil

Das kam direkt nach dem der hier geladen wurde:
FS19_ITS_JD_Haecksler

Hast du den auf der Map im Einsatz ?

**Comment by IchDummer** [comment]
Hab den mal rausgeschmissen. Jetzt läufts. Vielen Dan für die schnelle Hilfe!!!
