### ISSUE TITLE
[Feature Request] Option to add settings back to main HUD

### ISSUE THREAD

**Issue by MicaelJarniac** [Courseplay/courseplay#5335]
As of [`v6.02.00005`](https://github.com/Courseplay/courseplay/releases/tag/6.02.00005), some options that used to be in the main HUD are now hidden away in the advanced settings.

I understand that it helps declutter the HUD, and to keep things neat and simple, but some users might still prefer to have them easily available in the main HUD.

On my workflow, I use the AutoDrive and "use fertilizer of seeder" settings all of the time. Sometimes my truck is sowing my own farm, on which case I want it to use fertilizer, but then as soon as it's done, I send it to do a sowing contract, and I don't want it to waste fertilizer on the sowing contract, so I disable it. And depending on which tool I'm using, or if it's my own farm or contract, I toggle AutoDrive between disabled, refill, park and refill + park, and that's something I do basically on every single use.

Having those settings hidden away in the advanced settings has made quickly checking them and toggling them a cumbersome process, and I'd rather have them back on the main HUD, even if that means the HUD will be more populated.

As not every user is the same, and not every user uses every setting, my suggestion is to have those settings hidden by default (meaning they're under adv. settings, but not on the main HUD, the way it is currently), but having an option (in the adv. settings) to add a shortcut to those settings back in the main HUD, so by default the HUD is neat and simple, but power users can easily have those shortcuts back, for easier access.

**Comment by Merrlin** [comment]
Hmm.. maybe a checkbox besides each option, or some of them, labeled Show on HUD would be a good way to deal with it.
If the Box is checked the Option is shown in both locations. HUD and Adv. Settings. If not then it is only shown in Settings

**Comment by Tensuko** [comment]
I already have an Idea. Let me work on it...

**Comment by Tensuko** [comment]
Option won't get back into HUD, but for the 1st step I added a keybind to turn on/off the fertilizer for seeder. (Will toggle the adv setting option).
When I find more time and get more into the HUD. I want to add Symbols or some kind of indicator, wich status that setting got. (Maybe make this one als click-able). Same for Ridgemarkers and also for AD use Toggle.
But anyway, there is a Reason why I moved those things out of HUD for now.
Just wait for it and pls keep in mind, that some ppl use it one way and some use it the other way (I mean this for all those kind of feature requests...)

Just be patient for now.

**Comment by MicaelJarniac** [comment]
Thank you for the reply. I know there are many users with many different use cases, that's why I didn't suggest to simply revert the changes that removed those settings from the main HUD. I suggested giving users the option to, if they find necessary, toggle those shortcuts back.

I wish I knew LUA (I think most of this mod is in LUA) so I could also actively help out here. I'll see if I can get the hang of it, I really wish to become a dev some day. And for me, helping out open source projects like this one is going to be absolutely amazing.

Anyways, thanks again for everything, and sorry if it sounded like I was too demanding.

**Comment by Tensuko** [comment]
Done with .00018
