### ISSUE TITLE
List of Issues after 10 Hours of Testing

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#5337]
Let me start by saying I do appreciate the long number of months you have taken in updating CP. I offer these findings in hope a solution can be found either in something I need to do or in something you can do. These are all Mode 2. These issues are all from Lone Oak map with both generic and mod equipment (all from modhub downloaded while in the game's menu except for animal manners).

1. Tractor waiting for combine to fill won't shut off engine & the strobes are on 100% of the time.
2. If the combine gets full while on the 1st headland the tractor will not go under the pipe (see screenshot below).
3. When combine is full and the pipe is in the fruit, the combine will reverse but not move over. The tractor won't go under the pipe.
4. Combines both generic and mod with both generic and mod headers of 26 meters, 12 meters, 7.6 meters & 5.5 meters are leaving fruit behind all over the field but especially at the top of the row just before a right turn.
5. Advanced settings keep reverting back to default and won't maintain AI turns etc. Even during the same session.
6. If the tractor does make it under the pipe and reaches 90% fill it leaves even if the combine isn't empty.
7. After the tractor returns from a trip to the sell point or from the silo, it ignores the combine when it is full. I can usually successfully call it to the combine, but it won't go under the pipe.
8. Deleting the course for the tractor and recreating will work for the first time the combine needs to be emptied but then reverts back to not behaving.
9. The tractor recognizes object in the field and will go around them if you select that setting, but can't see object just out of the field's boundary
![20200506105013_1](https://user-images.githubusercontent.com/24764870/81356016-2d738780-909e-11ea-9a69-3cf92c6f5640.jpg)
![20200507191559_1](https://user-images.githubusercontent.com/24764870/81356032-36645900-909e-11ea-9983-b9acccadbb68.jpg)
![20200507193819_1](https://user-images.githubusercontent.com/24764870/81356042-3c5a3a00-909e-11ea-8810-b10b596964a8.jpg)
![20200507193948_1](https://user-images.githubusercontent.com/24764870/81356051-411eee00-909e-11ea-9f48-d03e82f5f968.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/4596338/log.txt)

 and will drive up against it or wrap around it.

**Comment by pvaiko** [comment]
@lcc1211 wow. That's quite a list of issues. You attached a log file spanning like two hours and I have no idea where to look for any of those 9 issues.

Looking at the first three screenshots, there is something wrong with all of them. 1 and 2: why is the combine not in the middle of the row, why did it move to the left? I have not tested it with that specific combine, but have never seen that happening. 

On the third screenshot, all combines I tested moved to the right when the pipe was in the fruit. Why is this one does not do it?

I tested these with the same combine, all works fine. I recommend posting a savegame with everything set up so we have a chance to reproduce it.

4 has nothing to do with mode 2, open a new issue about that if you'd like 
5 are you sure you click 'Ok' after changing the settins? If you do and it is still not persisted, open a new issue.
6 I haven't seen that happening if it does, open a new issue, with a log file attached and noting the time when the issue happened
7 see above


8 and 9 I don't understand

**Comment by lcc1211** [comment]
For number 8: When I generate the course that takes the fruit from the field to the sell point, and the tractor returns to the field, it will no longer return to the combine when it is full. I can see that the combine has that specific tractor assigned to it, and I can see from tractor that is knows it is supposed to move over to the combine. It just sits there though. If I cancel that course and then create a brand new one, the tractor will drive over to the combine.

For number 9: If you look at field 50 on Lone Oak there are 2 islands in the middle of the field. I can tell CP to go around those, so I know CP is able to recognize objects (at least ones on the field), but when the tractor (during plowing, sewing, fertilizing etc.) reaches the end of a field with little room between the edge of the field and a tree, fence, building or any other object, CP will drive right into it.

**Comment by lcc1211** [comment]
For Number 3: The combines stopped moving to the right after I upgraded to version 9, but reverting to a lower version now has the same behavior. The combine does move over on the headland although I think that probably is not necessary.

I am not sure which file or files I would need to send as a save file, but I think the one I attached is it. I have a lot of mods, though.
[savegame1_backup2020-05-07_08-06.zip](https://github.com/Courseplay/courseplay/files/4596620/savegame1_backup2020-05-07_08-06.zip)

**Comment by lcc1211** [comment]
Attached is the log from when the tractor wouldn't come to the combine. I also manually called it. When it still didn't move I saved it and exited the game to see if there was something in it. I also tried to capture a video of the tractor going into reverse away from the combine at before it was. The combine still had about 4500 liters in the grain tank.
[log.txt](https://github.com/Courseplay/courseplay/files/4596759/log.txt)

**Comment by archaoncze** [comment]
I also do some test for mode 2. But most of this probles does not occur. I can cionfirm, that tractor leave combine instantli, when trailer reaches 90% (it can be probable solve by settings - set poit when he should unload at 100% - i usuaaly play with this number according to capacity of combine tank vs trailer, to avoid geting full combine and just few % left in trailer, now, when unloadings appear only for full stopped combine is easy to find balance).
To issue with combine left uncut parts of field - it depends on used combine. For rosttlemasch with 9m header its was perfect, no left bit. If i use basic new holladn with 4 m header, it start to be mess on headland corners and on 1 edge of field (no matter if i use advanced manauvers or not) and yes it was for right turns.
I also have one problem, when combine does not move away from fruit to allow unloading - its occured when he reaches 95% just after turn - unloader unload him, but doesnt reverse far enough, so combine get stuck in traffic after next turn (he stopped just at the edge of fruit)
In two situations i have problem with pathfinding for unloader to find its way to combine - each time its happen, when tractor sits near combine which reverse back from fruit - unloader instantly set course for align under pipe without trying to do loop behind combine, which results into unloader trying go though combine (collision system stop him from this, but i must align him manually)
I have also problem, that unloder, after unload combine before its last pass before finish, stop in area where unload combine. (combine had pipe in fruit, so it reverse, make space for unloader and he just reverse few meterr behind). Problem occured becouse last run was little bit narrower and combine runs it by its centre - so when he gets in location where unloader stopped just at the edge of fruit, there is not enough space for combine to do clear passing. I suggest to tell unloader to move forwrd and little bit away from fruit after combine succesfully move away, by using pathfinder with colison detaction (I was amazed how well it works, i had two combines on one field and one stopped so badly in headland corner and unloader nicely go around him withnout problems).
I doesn have any problem with reseting advanced settings (it can be reset by reset vehicle it self i belive, at least in past this can happen).

I probalby should tell, that i doesnt use the latest version, as i dont use MP, so i find useless to apply fixes for it.
I hope, that i describe everything clear.

**Comment by Tensuko** [comment]
The Combine Manager is getting some revisit.
For 95% Full right after turn I have an Idea like, check path in reverse and decide if turn reverse in 90° so the pipe will be in the headlands. We also will add a forecast for when unloader will be full and deice if it makes sence to turn or unload before turn. But that will take a while.

**Comment by lcc1211** [comment]
A couple more screen shots where the combine was full waiting for the tractor but the tractor doesn't move. I then manually call for it, but the tractor doesn't register the call. There is a quick flashing message below the course name saying no combine found. They are both physically on the same field and I have the field and combine selected in the options.
![20200508072006_1](https://user-images.githubusercontent.com/24764870/81401230-e072ce00-90fc-11ea-85a4-77352388278b.jpg)
![20200508071955_1](https://user-images.githubusercontent.com/24764870/81401234-e4065500-90fc-11ea-9c38-ff620fe00b47.jpg)

**Comment by pvaiko** [comment]
Let's try working on one problem at a time. Start with this one, this has a log file:

> Attached is the log from when the tractor wouldn't come to the combine. I also manually called it. When it still didn't move I saved it and exited the game to see if there was something in it. I also 

According to the log, you started it and after **11 seconds** you saved and exited the game. The pathfinder wasn't done yet. You have to give it some time to finish. Or you can turn the pathfinder off, that will be much faster and it'll be driving through the fruit.

**Comment by pvaiko** [comment]
> A couple more screen shots where the combine was full waiting for the tractor but the tractor doesn't move. I then manually call for it, but the tractor doesn't register the call. There is a quick 

Same here, if don't care driving through the fruit then turn the pathfinder off. The pathfinder won't drive through it.

**Comment by lcc1211** [comment]
Pathfinder is turned off here, but this tractor won't move. AI Turns and all the rest are off as well. It has been my experience that it doesn't matter how long I wait. The tractor won't move. I have waiting up to 35 minutes.

**Comment by pvaiko** [comment]
Awesome. Now, where is the log with the debug channels for that case above?

**Comment by lcc1211** [comment]
I'll have to start over as I forgot to set debug channels.

**Comment by pvaiko** [comment]
And you are sure you have pathfinding turned off:
![image](https://user-images.githubusercontent.com/2379521/81407577-495c4500-9101-11ea-9724-3c63cba6b439.png)

**Comment by lcc1211** [comment]
Yes if you're referring to the advanced settings & RSM combine and the New Holland T6. However, I have them turned on under advanced for the John Deer tractor and combine.

**Comment by pvaiko** [comment]
Jeez. Look at the screenshot I attached.

**Comment by lcc1211** [comment]
![20200508091519_1](https://user-images.githubusercontent.com/24764870/81409219-bde8b100-910c-11ea-988b-14bb8243309a.jpg)

**Comment by pvaiko** [comment]
Are you trying to say that with this setting, in the scenario on the screenshot, combine visible from the tractor, the tractor won't drive to the combine?

If so, send me that savegame. Would be great if I wouldn't have to guess what are you trying to say.

**Comment by lcc1211** [comment]
@pvaiko I am sorry if what I'm typing is not clear to you. With a combination of my log, savegame and screenshots, I don't know how to be clearer with you.
