### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Wealthy73** [Courseplay/courseplay#5339]
Hello,

Can you come back to the fact that the harvester must be full to be emptied?

Because in reality the harvesters can be accompanied during their harvest.

this is not a bug but rather a suggestion.

**Comment by Tensuko** [comment]
Read #5272 ........

**Comment by Wealthy73** [comment]
I read but why did I remove it?

**Comment by Tensuko** [comment]
The old mode2 doesn't exist anymore, so we didn't remove anything.
We had to create it completely new.
It is just not implemented right now and will be added later.
Who said we won't add it again ?

**Comment by Wealthy73** [comment]
okay so i misunderstood sorry
