### ISSUE TITLE
Kurse können im Multiplayer nicht gelöscht und neu gelanden werden

### ISSUE THREAD

**Issue by DnbSTEb** [Courseplay/courseplay#5340]
Wie die Überschrift schon sagt können wir zur Zeit auf unserem Server die Kurse im Manager nicht löschen und das neu laden Zeichen ist ebenfalls nur im Singleplayer verfügbar. An sich arbeitet der Mod einwandfrei abgesehen von den zwei Funktionen ( funktionieren aber im Singleplayer ). 
Festgestellt bei der Version 6.02.00010, 6.02.00005, 6.01.00350 und 6.01.00390.

**Comment by Tensuko** [comment]
Collecting all in #5484
