### ISSUE TITLE
[MP] CP Not remembering Field's when disconnecting/reconnecting to server.

### ISSUE THREAD

**Issue by Jaiimez** [Courseplay/courseplay#5341]
If I leave the server and rejoin after buying a field, Courseplay doesn't seem to remember that I own the field, when I try to select the field in the course generator, it isn't there as an option, I have to manually detect and save the field and use that method.

It worked when I first purchased the field, but moment I leave/rejoin the server after initial purchase it's gone.

Using .00010, if you need any other information, let me know.

**Comment by schwiti6190** [comment]
@Jaiimez  
Hi,
Do you have a simliar problem with courses, let's say you've joined a game as a Client, do you have access to all the saved courses and can load them without problems?
I am acctually looking at the Synchroniziation of courses/fields once a client joins.

David

**Comment by Tensuko** [comment]
Collecting all in #5484
