### ISSUE TITLE
Unloader Drive back whitout emptying

### ISSUE THREAD

**Issue by bibifr** [Courseplay/courseplay#5342]
Hello dear, 

I noticed a error in mode 2. 

The Harvester stop at 100%, The Unloader Come And move to the pipe then he instantly Driving back. 

The haverster is also Not unloader more than 10% 

Maybe im did something wrong?

Best regard
Fabien
[log.txt](https://github.com/Courseplay/courseplay/files/4600073/log.txt)

![fsScreen_2020_05_08_17_54_23](https://user-images.githubusercontent.com/9522188/81423670-0fb52980-9155-11ea-85e7-aaf7159627e1.png)

![Uploading fsScreen_2020_05_08_17_54_25.png…]()

**Comment by Tensuko** [comment]
What is your % Settings for Unloader ?

As a sidenote:
Load mod: FS19_addon_strawHarvest (Version: 1.0.0.0) (Hash: 1d15f60600f67db89fc72447145539f4)
Update to 1.0.0.2 Beta from Creative Mesh Discord.

@pvaiko is this a part of your refactoring for CombineManager ?
2020-05-08 17:25 Error: Running LUA method 'mouseEvent'.
2020-05-08 17:25 C:/Users/Audoi/OneDrive/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/settings.lua:1828: table index is nil

**Comment by bibifr** [comment]
Current Settings for it are 50% 90%  as They was for Old system (50% to Run to Haverster and 90% to Go back to Farm silo) i havn't Touch it since mode2 was out.


![fsScreen_2020_05_08_20_24_36](https://user-images.githubusercontent.com/9522188/81436548-f8cd0200-9169-11ea-8403-333750a38da9.png)

**Comment by answermanitou** [comment]
> Current Settings for it are 50% 90% as They was for Old system (50% to Run to Haverster and 90% to Go back to Farm silo) i havn't Touch it since mode2 was out.
> 
> ![fsScreen_2020_05_08_20_24_36](https://user-images.githubusercontent.com/9522188/81436548-f8cd0200-9169-11ea-8403-333750a38da9.png)

the problem may be with bunker silo which haven't soybean as registered culture. I also have same problem with soy bean but in the factory GC.

**Comment by Tensuko** [comment]
I think this is not the Issue here.
As I understood him, the unloader drives to combine and instead of wait untill the combine is empty, the driver drives straight back and unload the combine for only 10%.
I don't see the target marker of the Trailer.
As for some Trailers, the Target is so far in the back, that the drive drives to far to the front so the pipe end up outside and will be sent away then.

**Comment by bibifr** [comment]
yes it's the problem

I tryed this morning whit a another trailer and The Haverster unload whitout any issue 

Some trailer has target too far

thanks you

**Comment by Tensuko** [comment]
@pvaiko is there a chanze to adjust this ?
I had the same problem with @siwuees and a mod trailer. He had to adjust the target also to the front to get it working.
Maybe use an offset value ?

**Comment by Goof245** [comment]
Can you access the position of the fillvolume rather than the target, and use that to work out where the tractor should start its fill pass?

**Comment by Tensuko** [comment]
Since with Version 12 you can adjust the Offset so you can use any Trailer.
