### ISSUE TITLE
Verbindung zu AD

### ISSUE THREAD

**Issue by RudiBergfeld** [Courseplay/courseplay#5343]
Hallo zusammen,
wie ist es nun in der Neusten Version die verbindung zu AD here zu stellen. Wenn der Fahrer von CP mit dem Modus Düngen und Sahen ist wie kann ich im sagen das er auf AD gehen soll wenn die Sähmaschine leer ist.
[log.txt](https://github.com/Courseplay/courseplay/files/4600347/log.txt)

**Comment by Siwuees** [comment]
Indem du in den erweiterten Einstellungen einstellst (AD Verwenden) dass er es zum auffüllen/abfahren nutzen soll

**Comment by Tensuko** [comment]
Werde das noch wieder einfacher Zugänglich machen, mit einer Taste und eine Anzeige im HUD auf der ersten Seite habe ich auch geplant (wenn es klappt...), weis aber nicht wann ich das hinkriege. Bis dahin wie @Siwuees gesagt hat, über die erweitereten Einstellungen :)
