### ISSUE TITLE
Combine driver stops when unloading, can't see the setting to change it

### ISSUE THREAD

**Issue by Matt-14** [Courseplay/courseplay#5344]
I just downloaded the latest as of today and now the combine stops when I unload it. The FPS tanks as well and I can't see the setting where you can change if it stops or not. I am running the bankout wagon myself and not using courseplay to do it. I read that it said for mode 2 stop for unload is forced on but I would like to be able to have it go during unload if I am emptying it.

**Comment by Tensuko** [comment]
Why no one read our Stickys.... https://github.com/Courseplay/courseplay/issues/5272
