### ISSUE TITLE
[Ideas] Smart field analysis

### ISSUE THREAD

**Issue by MicaelJarniac** [Courseplay/courseplay#5346]
Currently, after selecting a course, there are a handful of options as for where the driver should start driving it, like from the start, the nearest waypoint, and so on.

There's even an option that remembers where the driver was before stopping, so it resumes from there.

And Courseplay also has pathfinding capable of detecting fruit, in order to avoid it.

My idea is, what if this fruit detection was added as an option to start the course of a harvester?

For example, if the driver has a loaded course, Courseplay would scan some sample waypoints to figure out which waypoints the driver has been to and which ones it hasn't, sending it straight to the first waypoint that it hasn't harvested yet.

This would work similar to the "current waypoint" option, but it'd also work if the vehicle stops working on a field, goes work on another field then comes back to the incomplete field, or if you restart the game while working on a field, or accidentally resumes working on a field with "first waypoint" selected, for example.

And if it's possible to detect not only fruit, but also fertilizing status, weed and such, this "smart starting location" could work on those modes as well.

This is similar to how a human would work on a field (I believe): they first look at the field, then they identify which areas of the field haven't been completed, then head straight to those areas, and start working from there.

I've had this idea for a while and thought it'd be cool to share it, so it can maybe inspire the devs.

I'm not sure how hard it'd be to implement, as even though fruit detection is already a thing, it's used on a completely different area. And adding it to the starting position choices could end up in performance issues depending on field size.

Another idea I had related to this kind of field analysis was to add an option to, on course end, send the driver back to incomplete areas of the field, like when it misses a sharp corner, so it would follow the waypoints to that area, then use pathfinding to do a little touch-up where it was unfinished.

This idea, although possibly more useful, I think is exponentially harder than the first idea to implement, but it's still a cool idea to share IMO.

**Comment by Tensuko** [comment]
Why would you not finish a field ?

The 2nd Idea is way to complicated

**Comment by MicaelJarniac** [comment]
Well, both ideas are just like random thoughts, I don't expect them to be features any time soon, if ever.

About the first one, well, I've had it happen to me many times where for some reason, the "current waypoint" gets reset.

It usually happens when CP hands control over to AD, then AD gets in a road accident, and I have to restart it. Another thing that also happens is accidentally selecting the wrong starting option. Yes, it's user error, but still, that doesn't mean it isn't valid.

Also, I don't remember needing to stop working on a field halfway to go work on another, but I can see it happening.

For example, imagine you're waiting for your field to grow, so you can harvest it. While waiting, you decide to make some profit with your harvester, that would otherwise be sitting there unused, so you send it to work on a contract.

Halfway through the contract, you notice your own field finished growing. The contract is very long, and contracts don't have a time limit, so you decide it's better to get your harvester back to your field to harvest it, and then send it back to the contract.

That would have reset the "current waypoint" on the contract field, so you wouldn't be able to just tell AD to drive to the field and start CP on "current waypoint", and if you do it on "first waypoint", it'd be wasting a lot of time until it gets back to where it was before. The best option would be to manually drive the harvester back to where it left off, as it would otherwise have no way of knowing where it should resume working.

So that would be an example of why someone might not finish a field. And I believe quitting the game always resets the "current waypoint", so if the harvester wasn't on the field (for example, if it's on the unload path), you'd not only be unable to use "current waypoint", but "nearest waypoint" too, because it'd no longer be where it's supposed to resume, so you'd have to manually drive it back to the field and back to where it left off, so it can go on.

But again, those aren't even actual suggestions, I know they're very tricky and far away. I'm just sharing ideas, kind of brainstorming, and maybe someone can someday use those ideas on a similar feature.

**Comment by Tensuko** [comment]
Not going to implement this, as we have enough to rework and fix of the actual stuff.
