### ISSUE TITLE
Enhance CP drive on loaded AD Course.

### ISSUE THREAD

**Issue by wertigoxxx** [Courseplay/courseplay#5348]
Hy, 

The tractor goes on an autodrive course, brakes late before cornering!  When you are inside the modes of the real load script, you can't stop.  Also, designing for a combine often goes like a drunk.  (Salon)

I use the latest courseplay.

**Comment by Tensuko** [comment]
#5055 

> The tractor goes on an autodrive course, brakes late before cornering!

AD Issue ?

**Comment by wertigoxxx** [comment]
Yes

**Comment by Tensuko** [comment]
So why did you post this Issue here on CP GitHub ?

**Comment by wertigoxxx** [comment]
Because courseplay can read autodrive courses as well.  Because courseplay doesn’t want to travel nicely on the route created by the autodrive.  He takes turns at high speeds or just runs over them.🙂

Maybe a courseplay problem.  I've already experienced that the courseplay for him goes to the tree, the gate. Is there a solution?  Maybe it can be adjusted somewhere to see farther?

**Comment by Goof245** [comment]
It would be nice if AD could bake the calculated speed per waypoint into the waypoints it sends to CP.

**Comment by Tensuko** [comment]
I don't think that would be possible since AD does calculate the speed on the fly based on the settings and have them not saved somewhere.
Also you would have to adjust the values per vehicle anyway.
But @Stephan-S sure knows this better :)

**Comment by pvaiko** [comment]
CP already brakes before corners.
