### ISSUE TITLE
Race Track pattern

### ISSUE THREAD

**Issue by 57IowaFarmer** [Courseplay/courseplay#5354]
To keep the pipe out of the crop, how about beginning each loop so each starts with the outside leg and work in, just a suggestion.

**Comment by Tensuko** [comment]
This should be the 3rd option. try it out.

**Comment by Tensuko** [comment]
![fsScreen_2020_05_12_17_26_30](https://user-images.githubusercontent.com/27344744/81713257-ea3a5f80-9475-11ea-80be-d87fcf921fbc.png)

**Comment by 57IowaFarmer** [comment]
Thanks
