### ISSUE TITLE
FS19_Courseplay/CombineAIDriver.lua:1159: attempt to perform arithmetic on field 'pipeOffsetZ' (a nil value)

### ISSUE THREAD

**Issue by cwattyeso** [Courseplay/courseplay#5355]
Loaded Farming Simulator this evening with the latest update of Courseplay and immediately started getting a lua error spamming my game. This is particularly weird because in my current save game I don't even own or have a combine, and at the time I was trying to play I was actually trying to seed a field, so definitely not using a combine. So I have no idea what Combine Courseplay is trying to perform a Pipe Offset on.

[log.txt](https://github.com/Courseplay/courseplay/files/4606706/log.txt)

**Comment by pvaiko** [comment]
#5272

**Comment by Tensuko** [comment]
More Details... What used Vehicles and so on, Screenshots might help.

**Comment by cwattyeso** [comment]
John Deere 8RT Tractor, Case Seeder with Air Cart
Seeding Manually, Not using Courseplay, have not generated a Course on this save game in 12 hours of play even. Don't even own a Harvester in my farms equipment, so have no idea why Courseplay is crying and creating a script error about the Combine's Pipe. It starts generating that error and spamming the log file, the second I load into game and have control of my character, before I've even tabbed or climbed into a vehicle.

![fsScreen_2020_05_11_05_53_43](https://user-images.githubusercontent.com/13921716/81525230-ef9b8b00-934b-11ea-97f6-f33a5f166da9.png)

**Comment by pvaiko** [comment]
Should work with 6.02.00012, was caused by the JD cotton harvester as the log message also indicated:
`
2020-05-10 21:12 :01 [info lp8664] CP690: Could not find implement with pipe
`

**Comment by Dmitriy-30** [comment]
транспорт при вызове комбайном подъезжает к трубе и сдаёт назад не выгрузив его

**Comment by Maikel5** [comment]
Ahoj čeština  nefunguje?

**Comment by pvaiko** [comment]
Ideírok valamit magyarul is, csak hogy legyen még egy nyelv itt amit senki sem ért...

**Comment by Tensuko** [comment]
こんにちは、皆さん

**Comment by Maikel5** [comment]
> 
> 
> Ideírok valamit magyarul is, csak hogy legyen még egy nyelv itt amit senki sem ért...
A google-t is használom.
