### ISSUE TITLE
Combine emptying issue

### ISSUE THREAD

**Issue by Anthrack** [Courseplay/courseplay#5356]
I downloaded the new version of CP. I was harvesting and request the driver to empty the combine but nothing happens. He stay's at his starting point.  I don't know why, in a older version I had (almost) no issues to empty the combine. 
Has something changed? To find the combine in the field was also a struggle. I can select [x]CR6.70(field5) or [ ]CR6.70(field5). I don't know what the X mean? But both do not work.

**Comment by pvaiko** [comment]
#5272
