### ISSUE TITLE
Issue with waiting position

### ISSUE THREAD

**Issue by Madhax47** [Courseplay/courseplay#5358]
In the past I used an auger wagon in mode 2, then I set a waiting point next to the trailer I wanted to fill, together with a waiting time. With the current version the driver ignores the point and just slowly deceleates and comes to a stop a couple meters beyond the point. Also waiting time is ignored in every mode. I tested all of them.

**Comment by Goof245** [comment]
For auger wagons I've been putting the unload (not wait) point right at the back of the other trailer, seems to work OK so far.

CP doesn't extend seem the auger though, so I have to leave it extended all the time. Not a huge issue if the field is relatively clear with not much to crash into, but I guess auger wagons aren't supposed to be used with mode 2 anyway...

**Comment by Tensuko** [comment]
Thats what Mode3 is for, but not ready yet.
As this is not an actual Issue, I close this.
