### ISSUE TITLE
Feature Request: Option to display pretty blue pathfinder / turn manuever lines without debug 4/14

### ISSUE THREAD

**Issue by Goof245** [Courseplay/courseplay#5359]
As in the title. Would be great if there was a setting to turn on the blue pathfinder paths, minus the waypoint numbers. Interesting to see the path, if nothing else, but debug 4/14 cause too much log spam to leave on.

Maybe have an option in here next to "switch on endpoints / all points / crossing markers"?
![20200511182251_1](https://user-images.githubusercontent.com/3851003/81540728-6751d000-93b5-11ea-967a-38e437c3e1be.jpg)

**Comment by pvaiko** [comment]
These are what we call 'temporary' courses and it would really be super easy to do add this to the global advanced settings.

**Comment by Tensuko** [comment]
Option added to vehicle settings page.
