### ISSUE TITLE
Limit Pathfinding to Fields?

### ISSUE THREAD

**Issue by WubbeOP** [Courseplay/courseplay#5360]
Would it be possible to add a mode where fieldworkers would limit their pathfinding in turns to the field boundaries? Even with AI turns or the current pathfinding I constantly have workers end up in trees. I'm  already giving that 12m drill almost 40m of headland to turn on, it shouldnt have to leave the field boundaries for that. I feel like there should be an option to limit their turns to within the outermost headland line if that makes any sense. So that neither tractor or tool would ever be outside the field and in fences or trees again.

**Comment by Tensuko** [comment]
This is ofc one of our plans, but time is limited and everywhere ppl ask for different enhancements and reports how bad the (old) Mode2 is so where do we start/continue..... now we are working on mode2 so this needs to wait.

**Comment by WubbeOP** [comment]
I#M sorry if this had been requested before. Also I didn't mean to critizise the work of the devs, you are doing great work!
