### ISSUE TITLE
Mode 2 with Ver012 issues

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#5363]
Im trying the latest version but have run into problems.

The combine is full and has called the tractor....
![fsScreen_2020_05_11_15_09_53](https://user-images.githubusercontent.com/11178621/81571473-e89b6980-9399-11ea-9388-8759ece3bbb3.png)

The tracotor is aware of the combine but doesnt respond...
![fsScreen_2020_05_11_15_10_44](https://user-images.githubusercontent.com/11178621/81571609-14b6ea80-939a-11ea-8f9d-4c2687b0db5f.png)

I did get as far as previously the tractor did respond and when it got close the white beam appeared. 
![fsScreen_2020_05_11_15_05_19](https://user-images.githubusercontent.com/11178621/81572155-c35b2b00-939a-11ea-9819-fa67c709e39d.png)

The tractor followed. im assuming it still wont empty on the move, until the combine was full but when the combine had stopped and was readu to empty the tractor started to reverse until it hit a tree whn i intervened.

[log.txt](https://github.com/Courseplay/courseplay/files/4610098/log.txt)

**Comment by Tensuko** [comment]
2nd Screenshot, I don't see any assigned combine.
And for the last time, this is not a 'look for Combin on Field X' this is a simple stupid Filter for the List of Combines. Nothing more and nothing less......

**Comment by dexus92** [comment]
I have problem with new mode 2. How I must use that?
I have course from point A (start point) to point B (stop point) and I give "cross" in combine settings for combine to unload but the tractor stopped on end boint (B).

You can see it there:
https://youtu.be/m3QTMbyOHAM

**Comment by kwguk** [comment]
Ok 
Well regardless the tractor isnt detecting the combine.

Ironically i switched back to Ver.399 and its working well in mode 2

**Comment by Tensuko** [comment]
Version 399 is a fking old rubbish System that works stupid and with no actual System used in new CP6.
Sure you can stick to it but don't ask for any suppor then!

**Comment by Tensuko** [comment]
@dexus92 your Course looks good, but right now the Driver will only get to the Combine when its full :) The unload while driving is in development right now. See #5272

**Comment by dexus92** [comment]
@Tensuko ok, but when combine is full the tractor is stopped. :)
You can see it on the moment: https://youtu.be/m3QTMbyOHAM?t=196

**Comment by kwguk** [comment]
LOL
Ive gone back to 012!
However i cannot get a tractor to detect a combine. Plus the worklights are on all the time even on the road. And the tractor seems to ignore the speed ive set in the HUD and i can only change the speed using the cruise control buttons. 
How can i get the tractor to detect the combine??

**Comment by Siwuees** [comment]
**How to report a problem with Mode 2:**
A log file with debug channel 4, 7 and 14
Screenshot of the situation with debug channel 4, 7 and 14 and all waypoints on (the 3 dots in CP HUD settings)
What you expected
What happened

**Comment by Tensuko** [comment]
https://1drv.ms/v/s!ArGbP_j369r8lSohT3mk8-qpAB4P

**Comment by dexus92** [comment]
Ok. I do that as you but my tractor is stopped and it can't find combine. You saw that. Tell me why your course work fine but my not? :) They are similar.

**Comment by Tensuko** [comment]
@dexus92 
Can you turn on debugchannel 4 7 12 and 14 and post your logfile ? (Drag and drop into the Commentbox).
A video with those debugchannels might help too.
It just have to work.
I can only imagine a Modconflict in your case.

**Comment by dexus92** [comment]
All debugchannel at once or each one separately?

**Comment by Tensuko** [comment]
All together pls.

**Comment by dexus92** [comment]
[log — kopia (2).txt](https://github.com/Courseplay/courseplay/files/4611219/log.kopia.2.txt)

**Comment by dexus92** [comment]
Lol, I don't understand. When I give you log file don't work. But when I record video work fine.
It's crazy :D

**Comment by dexus92** [comment]
https://youtu.be/eyD4BBIe9a4

3rd - don't work. video with log file
[log — kopia (3).txt](https://github.com/Courseplay/courseplay/files/4611270/log.kopia.3.txt)

**Comment by Tensuko** [comment]
It is the Magic trick to show that it works ;)

I wonder if ths Mod create the Problems:
fs19_filllevelwarning

Oh I am very sure this could cause Errors:
fs19_fullstop

**Comment by dexus92** [comment]
Ok. I will check it without this mods tomorrow. And I let you know.

**Comment by Tensuko** [comment]
Do you have 2 Mode2 Driver assigned to the Combine ? The Axion 960 and 6250 R ?

**Comment by dexus92** [comment]
Only 6250R, Axion bales straw. :)

**Comment by pvaiko** [comment]
@dexus92 change the unloader priority to distance (instead of fill level you have now) and see if that works.

**Comment by dexus92** [comment]
@pvaiko I changed it and for first unload worked fine but for second unload of combine (after unload tractor) didn't work.
(without deactivate this mods - filllevelwarning and fullstop)
[log.txt](https://github.com/Courseplay/courseplay/files/4616003/log.txt)

You can see that (I know it's long video) + log.txt:
https://youtu.be/UjDDFf7a6IE

@Tensuko After I deactivated this mods. And You can see on this video:
[log.txt](https://github.com/Courseplay/courseplay/files/4616213/log.txt)
https://youtu.be/PveGK1i45bA

1. Don't work second unload combine when you unloaded the tractor after first unload combine.
2. Why tractor move up and back when combine is unloading? This make not complete unloading the combine.
3. Why the tractor don't drive to combine (end second video)?

**Comment by kwguk** [comment]
Couple of questions....

When do you think Mode 2 will be unloading moving combines?

If i wanted to unload combines on the move at the moment which version of CP could i use?

**Comment by Tensuko** [comment]
When it is done and tested...

**Comment by Tensuko** [comment]
Outdated Issue.
