### ISSUE TITLE
CombineUnloadManager.lua:247: attempt to call method 'getFillLevelPercent' (a nil value) - CP 6.02.00010

### ISSUE THREAD

**Issue by fuzzyOwl** [Courseplay/courseplay#5364]
I run three CP (v 6.02.00010) helpers, one in the combine, one using Horsch Titan 34 UW and a third one with a large trailer running between the field/Horsch and the farm silo. For the most part it works fine and I realize that this mode is still heavily under development, but this error appeared:

CombineUnloadManager.lua:247: attempt to call method 'getFillLevelPercent' (a nil value)
[log.txt](https://github.com/Courseplay/courseplay/files/4610258/log.txt)

Also it appears that (sometimes?) I need to enter the combine (run by CP) and call the overloader manually, for him to come and unload the combine.

I hope this hepls the development and thank You for all your work! I could not play FS without CP!

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/releases

**Comment by fuzzyOwl** [comment]
I could not reproduce ther error in version 6.02.00012, CP is working fine. Sorry I wasn't up to date!
