### ISSUE TITLE
Error: Running LUA method 'update' MathUtil.lua(173) : attempt to perform arithmetic on local 'x' (a nil value)

### ISSUE THREAD

**Issue by fritzix** [Courseplay/courseplay#5366]
Hallo, 
ich bekomme folgendenden Fehler.

Dieser Fehler tritt auf wenn ich mit dem John Deere 6230 + BiriFieldmaster 20 + SB700 im Vorgewende in die Nähe der Pellethalle mit Kran komme.
 
https://drive.google.com/file/d/1kvDQ-n8yN0PZbjNvMGpgvj9E9X2RqaP7/view?usp=sharing

[log.txt](https://github.com/Courseplay/courseplay/files/4610633/log.txt)

**Comment by Tensuko** [comment]
Problem vom Strohbergungs Addon.
Die haben irgendwas komisches mit den Gebäuden gemacht.
Muss da noch mal anklopfen.....
