### ISSUE TITLE
Error: Running LUA method 'update' CP ver/010

### ISSUE THREAD

**Issue by answermanitou** [Courseplay/courseplay#5367]
Have a problem with mode 2
2 fields 2 differrent case 9270 combines on each and one favorit as unloader
1 combine and 1 unloader firstly dont want to work. Combine is 97% but not 100 -- is it must be? 
with 3rd try unloader go to combine and all works properly.

2nd combine on field just start from generated course and works. He havent unloader yeat. While i run with unloader to nearest point of unloader course the game is crashed down with error CP

dont remind for me about update for straw mod))
[log.txt](https://github.com/Courseplay/courseplay/files/4611010/log.txt)

**Comment by Tensuko** [comment]
> dont remember for me about update for straw mod

Good luck then...

And also this:
https://github.com/Courseplay/courseplay/releases

#5272
