### ISSUE TITLE
Inquiry about settings

### ISSUE THREAD

**Issue by answermanitou** [Courseplay/courseplay#5368]
Please give me answer or better make manual pdf about settings.
If necessary to change advanced settings such as "use intelectual for return, force backward etc" for each vehicles or its sets globally for all vehicles on the map?

**Comment by Tensuko** [comment]
1st page is for vehicle. 2nd page is global.
I know I need and want to change those pages but got to find some time for it.

**Comment by answermanitou** [comment]
> 1st page is for vehicle. 2nd page is global.
> I know I need and want to change those pages but got to find some time for it.

Thanks for the answer. It will help. I wrong think that it's all global.
Please close
