### ISSUE TITLE
Few issues with 6.02.00012

### ISSUE THREAD

**Issue by polosubtil** [Courseplay/courseplay#5370]
Hi guys,
A few things I have on the latest version.
Just to be fully honest, I am playing on Oakfield map which is super challenging for courseplay as there are no straight line ever ;)
Both vehicules have pathfinding activated (both options). Tractor is set to "Unload" and I called a trailer manually on the combine
Combine course below
![fsScreen_2020_05_12_00_15_58](https://user-images.githubusercontent.com/60451845/81617534-e8c15680-93e5-11ea-869c-c74ccc62b6fe.png)

1. The combine T560 stay stuck or is really slow in some maneuver at the end of the row (usually tight turns >90°). I am using the vanilla corn header 6m
![fsScreen_2020_05_11_23_57_04](https://user-images.githubusercontent.com/60451845/81616405-b282d780-93e3-11ea-9a41-d50230e14a64.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4612320/log.txt)
I already saw that issue with previous 6.02 versions but it's happening more often in that field
This place is always stopping the combine
![fsScreen_2020_05_12_00_27_20](https://user-images.githubusercontent.com/60451845/81618353-72255880-93e7-11ea-8dd4-a0aaafad7eea.png)
Log, see at the end only : [log.txt](https://github.com/Courseplay/courseplay/files/4612398/log.txt)

2. When the combine is full, the tractor drives to the combine but aims for the combine center instead of the pipe. I tried with the pipe always out and without it but it doesn't make a difference. I had good results before (but with the classic header so not sure if the corn header is the issue or the version or myself).
[log.txt](https://github.com/Courseplay/courseplay/files/4612371/log.txt)
![fsScreen_2020_05_12_00_16_15](https://user-images.githubusercontent.com/60451845/81617558-f4148200-93e5-11ea-9c9b-4b87e1ece8a7.png)
![fsScreen_2020_05_12_00_16_18](https://user-images.githubusercontent.com/60451845/81617709-3dfd6800-93e6-11ea-8099-09916291a4d8.png)
![fsScreen_2020_05_12_00_16_39](https://user-images.githubusercontent.com/60451845/81617572-fb3b9000-93e5-11ea-9e8f-af82a6f2384c.png)
![fsScreen_2020_05_12_00_16_45](https://user-images.githubusercontent.com/60451845/81617733-48b7fd00-93e6-11ea-9c73-1a25fb9db241.png)
Not sure if I am doing something wrong here. Let me know if you want me to do more testing. I might try again with the classic header just to make sure

3. I guess it is normal but during the first headland (2 first handlands in that case) the tractor with Pathfinding is always going to the nearest field bordure. Which is strange because the field bordures are the same seize for both fields. But as I said, it's a challenging map, a lot of obstacles + hedges and nothing straight

**Comment by Tensuko** [comment]
The problem is with the offset, there is something saved in the vehicle.
I solved it in my testsave with resetting the vehicle.

**Comment by polosubtil** [comment]
I guess this is for my issue N°2. I will give it a try, thanks

**Comment by polosubtil** [comment]
@Tensuko, I reinitialized my combine and started again but I get the same issue. Does the header has anything to do with it ?
![fsScreen_2020_05_12_14_20_32](https://user-images.githubusercontent.com/60451845/81690796-1a750480-945c-11ea-8a50-670214b1b4de.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4615502/log.txt)

**Comment by Tensuko** [comment]
Not the combine makes the offset... Your Mode2 driver (tractor)

**Comment by polosubtil** [comment]
@Tensuko 
You were right, re-initializing the tractor worked perfectly.
![fsScreen_2020_05_12_15_02_18](https://user-images.githubusercontent.com/60451845/81694529-b7866c00-9461-11ea-831b-4da3f3c74941.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4615730/log.txt)
Any idea why this happened ? Any way to avoid it ?

**Comment by polosubtil** [comment]
What about the combine maneuver, anything I could try ? I turned on the AI turns but it's worse ;)

**Comment by Tensuko** [comment]
For the Combine I am not sure. Never had this yet.
Maybe check your speed settings ?

About the Offset, I have no real Idea, but it I think this is due to offset rework and old values where still saved in the tractor.

**Comment by polosubtil** [comment]
I think I tried all the settings i know but nothing works, reversing is always really slow (close to 0/1)

**Comment by Tensuko** [comment]
Outdated and maybe this helps you with settings https://www.youtube.com/watch?v=PiUWD8ki8l4
