### ISSUE TITLE
New feature idea. Pushing while waiting in traffic optional.

### ISSUE THREAD

**Issue by DSul3791** [Courseplay/courseplay#5371]
I've made courses where a few tractors have to drop off while driving over previously dropped product piles and having a slight push is helpful. This was wonderful. However; I have tractors lined up waiting for their turn to load and the tractors all at the back only stop for a minute then all start to push eventually causing a giant pile up of tractors. Would be nice if it was a check box or toggle in the specific mode options or something. Not sure if this is intentional or a bug.

**Comment by Tensuko** [comment]
You talk about a few tractors waiting in mode2 or where exactly... A screenshot could help.

**Comment by wertigoxxx** [comment]
I think tractor convoy thought.  I also think it's a good idea.  Keep distances between machines waiting for each other until they are in line.

**Comment by DSul3791** [comment]
Great questions. I just woke up and will work on this more today. I found in the code the collision detection was checking the traffics speed and if it was moving would set our speed to it. This is fine if moving forward in a line but it ignores if the traffic is backing up or turning. Again I'll take some screen shots when i can.

**Comment by DSul3791** [comment]
Also yes unfortunately an unplanned convoy. I have many power wagons collecting grass all on their own timing and occasionally one might veer a little and get stuck. when this happens they all stop and then continue to slowly push into each other until crushed. I will get screen shots next mishap

**Comment by DSul3791** [comment]
Ok Its not Mode2 Specific. Its over all collision detection. 
Theres a little fuzzy logic ie ~= in AiDriver.Lua that says

if trafficSpeed ~= 0 then
			--get the speed from the target vehicle
			self:setSpeed(trafficSpeed)
end

excellent code with the unfortunate sideeffect of creeping.
for now I adjusted with

self:setSpeed(0)

this solved all my collision problems. 
If this was an option with a toggle I could use the creeping in certain courses to help push where needed.

**Comment by DSul3791** [comment]
Hope I'm not breaking any rules here by posting that. I love the product and happen to be a coder myself. I'm retired and love to play in game code. Especially AI like stuff.

**Comment by wertigoxxx** [comment]
do you have any solution to keep the distance between the tractors more than 10 meters? when he notices that there is an obstacle on the route, he always climbs on the other tractor, remaining about 1 meter. the other tractor cannot move, the CP must be restarted.
maybe this can also be found in the code? :)

**Comment by DSul3791** [comment]
Wertigoxx I believe this is exactly the problem I was having and this does fix it temporarily. I'm not sure if it breaks anything else. So far my team of 4 tractors has all stopped running into each other and have been playing nice. None stop money making :)

**Comment by DSul3791** [comment]
Tensuko it is not Mode 2 specific. It is all vehicles at all times. They only wait a short time before piling up on each other. Everywhere always. Specifically in the middle of a field 12, 13 and at the barn drop off. My work around did completely fix this but I'm not familiar with the code enough to know if it breaks anything else.

If that answers your question.

**Comment by Tensuko** [comment]
> Everywhere always.

I have no doubt about your fix, but I doubt about this part.
Anyway, not sure when we replace teh current system....

**Comment by pvaiko** [comment]
@DSul3791 could you please open a pull request if you have a fix? We can discuss the details there.
