### ISSUE TITLE
Course loading issue

### ISSUE THREAD

**Issue by Mrsidders** [Courseplay/courseplay#5375]
I have been having trouble loading a certain course. When setting a course from a silo i.e TMR, pig food or fermenting silo to my store everytime I click start first point it makes every tractor regardless of implement say start filling, all the silos are attached to global company. I have included my log to see if it is courseplay causing the problem.

---

Pls don't post your log like this... just drag and drop the log.txt into comment box.
Those wall of texts are not readable..... - Tensuko

**Comment by Mrsidders** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4617193/log.txt)

**Comment by Mrsidders** [comment]
sorry I thought I had sent it the correct way. Hopefully this is better

**Comment by Tensuko** [comment]
A lot better :)
Could you make a screenshot of your course where the problem is (with all waypoints on, HUD option).
Maybe the Course have a Problem.
Did you set the right FillType to load ?

**Comment by Mrsidders** [comment]
Ive have been playing around again with it today with different ways for course but what I did notice that if the silo has mixed lets say TMR the tractor pulls up to first waypoint I have selected the fill type as load  I.E drive on once reached 100% full  Selected TMR It loads and then all the other machines on farm say start loading but once its full and pulls off to start it's course all the other machinery then go back to normal not saying start filling. It comes back after emptying the load and if the silo has not produced any TMR and the tractor sits and waits at loading point I.E first waypoint it then flicks all machinery back to start filling. I will send pic once i'm back on FS19

**Comment by Mrsidders** [comment]
![fsScreen_2020_05_14_19_33_22](https://user-images.githubusercontent.com/32279752/81979614-2c55d380-9625-11ea-87ce-65b64ff8379c.png)
this is the course with the only two waypoints
![fsScreen_2020_05_14_19_33_30](https://user-images.githubusercontent.com/32279752/81979716-53140a00-9625-11ea-860f-00ddd25c11a5.png)
this is when the course has been started to first waypoint
![fsScreen_2020_05_14_19_33_55](https://user-images.githubusercontent.com/32279752/81979784-6cb55180-9625-11ea-82bf-6715450612f5.png)
this is the tractor the other side of silo with no course loaded and it states start filling in HUD
![fsScreen_2020_05_14_19_34_09](https://user-images.githubusercontent.com/32279752/81979860-8ce51080-9625-11ea-99b9-4677d6ccb9b2.png)
as you can see the start filling is in hud on this tractor and seeder
![fsScreen_2020_05_14_19_34_17](https://user-images.githubusercontent.com/32279752/81979919-a423fe00-9625-11ea-807f-f6518b69df77.png)
and the same for this one with no course loaded.

**Comment by Mrsidders** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4739570/log.txt)
![fsScreen_2020_06_06_08_33_24](https://user-images.githubusercontent.com/32279752/83939087-f6de7900-a7d1-11ea-960f-76835be3897b.png)
I have reproduced the course and it is still doing the same
this is the course I have set with two waypoints and tractor is set to first waypoint, once set tractor to drive the other tractors, lorries, harvesters all say start filling as follows
![fsScreen_2020_06_06_08_35_11](https://user-images.githubusercontent.com/32279752/83939123-2f7e5280-a7d2-11ea-89eb-699bf9273d41.png)
the implement on this tractor does not need filling and there is no course set
![fsScreen_2020_06_06_08_35_30](https://user-images.githubusercontent.com/32279752/83939158-79ffcf00-a7d2-11ea-8ea4-37d25dd18230.png)
as you can see from this picture the tractor is stabled in shed and not unfolded but still states, start filling
and this is what happens once I click start driving from the silo to unload point

**Comment by Tensuko** [comment]
What about .00067 ?
I only see .00026 on your screenshots wich is waaay to old....

**Comment by Mrsidders** [comment]
If you look at date of sent it states 06 June 2020 so yes this old compared to now...………..

**Comment by Mrsidders** [comment]
I have not tried it anymore as I never got reply and was waiting for a reply if that makes sense ?

**Comment by Tensuko** [comment]
What about try it if I ask you to try it ?!

**Comment by Mrsidders** [comment]
Well that's a petty childish answer from someone with great knowledge for courseplay. Maybe you should hand the reins over to someone else that actually wants to help ??? GROW UP YOU CHILD !!!!

**Comment by Tensuko** [comment]
1st, I seem to be more grown up then you, regarding to your answer
2nd, I asked you a simple question to try it out with Version .00067 and now we are even at .00071

When we did a lot of stuff and changed a lot of stuff and we have not answered you, but simply ask you to try it out and all information I get from you is:


> 
> 
> I have not tried it anymore as I never got reply and was waiting for a reply if that makes sense ?

Ofc I will ask you again becouse I simply ask you to try it out ?
Whats so wrong about it ?
And now you blame me and call me a child ?!

**Comment by Mrsidders** [comment]
I was waiting for a reply to my issue that I was having which I understand you are busy so I left it until you replied in cased you came back with why don't you try this or try that.

your reply was taken as sarcastic with all the punctuation applied. I did not want to hassle someone that is busy sorting stuff out what is wrong with that ?

**Comment by Mrsidders** [comment]
What about try it if I ask you to try it ?!

**Comment by Mrsidders** [comment]
This is what I got from you 
I only see .00026 on your screenshots wich is waaay to old.
If you look at date of sent it states 06 June 2020 so yes this old compared to now...………..
I always update my courseplay every time I switch my PC on so when you replied to me from my June message in October I had already updated to latest version but that question was not asked. I tell you what we will leave it at that...…. Thank you for your help in this matter
