### ISSUE TITLE
Fronttanks won't get refilled

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#5377]
I don't know if it is already known but when using seeders that can also fertilize (even the original ones of the game, with the front tool to contain the fertilizer) the CP does not allow to reload them. Usually I reload sprayers and other tools to a silo (a mod) that sells many products including seeds and fertilizer, but when the worker led by the CP approaches he does not fill the seeder (while for example with sprayers, fertilizer spreaders or seeders that can just being filled with seeds works perfectly)

**Comment by 0Pietro20** [comment]
The game log
[log.txt](https://github.com/Courseplay/courseplay/files/4616417/log.txt)

**Comment by answermanitou** [comment]
I have same problem from last playing. If I put pallet w/seeds or tank w/fertiser near mod silo than CP recharge but 50/50

**Comment by Tensuko** [comment]
Can't reproduce... 
![fsScreen_2020_05_12_18_04_18](https://user-images.githubusercontent.com/27344744/81718433-080ac300-947c-11ea-9151-39495cd5b12f.png)
![fsScreen_2020_05_12_18_04_31](https://user-images.githubusercontent.com/27344744/81718439-08a35980-947c-11ea-96da-a568bb071d54.png)
![fsScreen_2020_05_12_18_11_15](https://user-images.githubusercontent.com/27344744/81718449-09d48680-947c-11ea-9636-c645f0453ad7.png)
![fsScreen_2020_05_12_18_11_28](https://user-images.githubusercontent.com/27344744/81718455-0b05b380-947c-11ea-8c16-9c71b4a28783.png)

**Comment by Horozor** [comment]
@Tensuko 
Try these planters **with front tool** They dont work
![fsScreen_2020_05_12_21_11_48](https://user-images.githubusercontent.com/37561569/81729882-655f3e00-9495-11ea-95cc-4307ba7c44d7.png)

**Comment by Tensuko** [comment]
See, this is a detail that needs to be named.....

**Comment by TinyCrocodile** [comment]
I did quickly reproduce. 
In a same scenario like your first one the azurit 9  gets filled correctly with seed.
When reaching the fertalizer silo it starts to buy fertalizer and load it into the azurit instead into solitair23. 
He never reaches fill level becaus azurit 9 have no fertalizer tank. only solitair 23 have it. 
Azurit gets heavy from all that fertalizer and cant move anymore :-) only reset did help. 
see screenshot and log with chanel 1,2,6  and 17
[log.txt](https://github.com/Courseplay/courseplay/files/4618101/log.txt)
![20200512212118_1](https://user-images.githubusercontent.com/34377785/81738787-8c6c3e80-949a-11ea-88bf-9e6d5856fcb4.jpg)

**Comment by Quintto** [comment]
I had the same issue when using the Goma manure tank ( https://www.farming-simulator.com/mod.php?lang=en&country=nl&mod_id=138704&title=fs2019 )
the driver would only fill the slurry trailer and not use the front mounted tank

**Comment by Siwuees** [comment]
I already had a similar problem, but in my case the front tank got refilled, but the sprayer does not get refilled. 
Debugs 1,2 and 17 (In the log around time 11:24 :18)

![image](https://user-images.githubusercontent.com/54322417/81795855-e7d71480-950c-11ea-923a-a042729ed96f.png)

[log.txt](https://github.com/Courseplay/courseplay/files/4620993/log.txt)

**Comment by ddewar** [comment]
I did some research on this awhile back. It's due to Courseplay not detecting those tanks as work tools, so they don't get seen as needing to be refilled. Some refactoring of the refill workflow might get it working, but it's not an easy fix due to the complexity of that part of Courseplay.
