### ISSUE TITLE
Combine Self-unload return to 1st waypoint after unload into Trailer.

### ISSUE THREAD

**Issue by miricha** [Courseplay/courseplay#5378]
When I activate it in advanced settings it works flawlessly, it finds the trailer on it's own it goes and it does what it's supposed to do. But after that, the combine goes to the first waypoint and stars over.

**Comment by Tensuko** [comment]
Can you make a logfile with debugchannel 7 12 and 14 and attach the log.txt ?

**Comment by miricha** [comment]
I got it to work.... somehow ;d
