### ISSUE TITLE
Strohsammler bleibt beim vollen Anhänger stehen

### ISSUE THREAD

**Issue by ratze68** [Courseplay/courseplay#5381]
Hallo Jungs,

![srohsammler](https://user-images.githubusercontent.com/53152008/81723670-8028b700-9483-11ea-853d-3c17b16abd18.jpg)

Der Sammler fährt auf dem Couresplay kurs,  Stelle im Couresplay den lade den Kurs stelle "auf erste wegepunkt ein" Im AD siehe Foto. Der Sammler fährt los, findet auch der erste wegepunkt, läd den Ladewagen Voll und bleibt stehen, und nichts passiert mehr.

Ich muss ihn im Courseplay ausschalten und AD an, dann fährt er los lädt ab.

Map: Obertahler
Version AD 1.1.0.5 RC2, 
CP: v60200012dev

[log.txt](https://github.com/Courseplay/courseplay/files/4617349/log.txt)

**Comment by Tensuko** [comment]
AD Meldung konnte keinen Kurs berechnen. Das hat nichts mit CP zu tun....

**Comment by ratze68** [comment]
Aha und was mache ich dagegen?

**Comment by lxfTTjek** [comment]
V6.02.00012 still has frame dropping, and there will be an error in relearning the gear combination and starting the trailer after saving and exiting the game! Hope to solve it!

**Comment by Tensuko** [comment]
> 
> 
> Aha und was mache ich dagegen?

Bei AD anfragen ?

**Comment by ratze68** [comment]
Sorry ich dachte ich wäre bei AD Aber Danke!

**Comment by lxfTTjek** [comment]
i 'm sorry! Because my English is not very good

**Comment by Tensuko** [comment]
> i 'm sorry! Because my English is not very good

Wrong Issue....

**Comment by Tensuko** [comment]
Chaos Issue ohne Wert und hat nichts mit CP zu tun...
