### ISSUE TITLE
Combine stops while unloading

### ISSUE THREAD

**Issue by getsome-Mojo** [Courseplay/courseplay#5382]
Every time I drive with the tractor and augerwagon beside the combine to unload, the combine stops.
Is it a bug or modconflict?

**Comment by Tensuko** [comment]
This is ppl don't read our stickys....
#5272

**Comment by getsome-Mojo** [comment]
I read #5272 but I don`t get it.
My problem is not explained in the thread or a solution is mentioned.

**Comment by Tensuko** [comment]
Unloader won't drive to the combine until the combine is 100% full
-> no unload while drive and the option is also not visible in the HUD

**Comment by getsome-Mojo** [comment]
Sorry I drive the tractor manual, but the combine is driven by courseplay.
Is there something to get this working? I want to drive the tractor manually..

**Comment by Tensuko** [comment]
....
This is not implemented yet
