### ISSUE TITLE
No seeding/Fertilizing option with Planter

### ISSUE THREAD

**Issue by emegbert** [Courseplay/courseplay#5383]
When using planters, CoursePlay doesn't give the seeding/fertilizing option therefore you can't set up an auto refill course.
The planter I'm using is the Horsch Maestro 12SW behind a John Deere 8R, however I've also noticed it with other planters also.

**Comment by answermanitou** [comment]
May be log file will be helpful in this situation with debug channels

**Comment by Tensuko** [comment]
Logfile and screenshot of the tool with hud open.

**Comment by emegbert** [comment]
Here is the log file and screen print.
[log.txt](https://github.com/Courseplay/courseplay/files/4624457/log.txt)
![Screenshot](https://user-images.githubusercontent.com/64389260/81860897-064d0800-952d-11ea-94f8-da6c38f515ab.jpg)

**Comment by emegbert** [comment]
I was able to determine that it was related to the tractor I was using.  It was the John Deere 8400R mod.  When I use the same tractor but not the mod it works just fine.

**Comment by Tensuko** [comment]
Ok this is a bit strange but I guessed that it is a Mod Issue.
Anyway, some Tips for your log:

You got Global Company so throw this out:
Error: Failed to open xml file 'C:/Users/earle/OneDrive/Documents/My Games/FarmingSimulator2019/mods/FS19PlaceAnywhere/modDesc.xml'.
Load mod: FS19PlaceAnywhere (Hash: d8d1b5e68fbea2a6469d5817b87b1d0a)
Error: Missing descVersion attribute in mod FS19PlaceAnywher

Another Mod with Error:
Error: Failed to open xml file 'C:/Users/earle/OneDrive/Documents/My Games/FarmingSimulator2019/mods/EXP19_Kenworth_W900/modDesc.xml'.
Load mod: EXP19_Kenworth_W900 (Hash: 38249257fe24abceb1ce4938ee1f9d48)
Error: Missing descVersion attribute in mod EXP19_Kenworth_W900

**Comment by Tensuko** [comment]
Closing as Mod Issue.
