### ISSUE TITLE
Problem with translation

### ISSUE THREAD

**Issue by MuuRuuk** [Courseplay/courseplay#5384]
Hi.
Im using czech localization of game but i can not see a text  just some courseplay things. Any tips? 
![fsScreen_2020_05_12_23_05_35](https://user-images.githubusercontent.com/65256510/81745944-f76f4280-94a5-11ea-8b29-8358eecf7a92.png)
![fsScreen_2020_05_12_23_05_52](https://user-images.githubusercontent.com/65256510/81745954-fb02c980-94a5-11ea-8860-e5b1a611160e.png)
![fsScreen_2020_05_12_23_06_11](https://user-images.githubusercontent.com/65256510/81745963-fd652380-94a5-11ea-81ac-17827b7995a7.png)

**Comment by pseikoNL** [comment]
There’s a “ missing at line 450 in translation_cz.xml

**Comment by Tensuko** [comment]
Sorry for this, we didnt notice this when merging. Will be fixed in the next release.
For now you could download the master branch, unzip it, rezip the files in it and rename to FS19_Courseplay (the old way).

**Comment by MuuRuuk** [comment]
Okay. Fixed. Thank you very much :)
