### ISSUE TITLE
Unloading Problems

### ISSUE THREAD

**Issue by JoaoSilva1994** [Courseplay/courseplay#5387]
Trying for the past 6h, to use CP to work with my forage harvester and then, after its full, take the chaff and unload it in a Fermenting Silo, but when the truck gets to the trigger, it detects it, stops and starts the unloading process, but the trailer does not empty anything, and it justs stays there stoped, doing nothing else.

At first i tought it was because the Silo was a modded, but it does the same thing with the vanilla Silo for crops.

**Comment by Tensuko** [comment]
#5272
