### ISSUE TITLE
Unloading Still not working

### ISSUE THREAD

**Issue by JoaoSilva1994** [Courseplay/courseplay#5388]
My issue was closed like an hour ago, and still, after another attempting at putting it to work, i doesn't unload nothing, and now, after following the instructions, the trucks just don't detect the unloading trigger..

I use a Fermenting Silo with a pass trough unloading trigger, not an Open Silo Bunker, i just use a Silo just like the one used for the Grain in all the maps, vanilla or not.

And CP doesn't either detect the trigger, or, when i put a trigger myself, it doesn't unload the cargo, even the animation going, and the trailer fully rised.

**Comment by Tensuko** [comment]
closed becouse you don't read #5272
