### ISSUE TITLE
edit routes

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#5391]
modifying a course, saving and returning in equal terms, the modification is not saved (it is kept during the current game but when I go out and return the path is the same as before). T
he images show the change made, what happens when I press Ctrl + F6 to save and how, in the closed and reopened game, it is not saved

![Farming Simulator 19 12_05_2020 22_03_04](https://user-images.githubusercontent.com/59969508/81832022-4f598800-953e-11ea-962b-c0dbb1e29738.png)

![Farming Simulator 19 12_05_2020 22_03_11](https://user-images.githubusercontent.com/59969508/81832052-554f6900-953e-11ea-82a9-399d7bd5c68d.png)

![Farming Simulator 19 13_05_2020 12_38_48](https://user-images.githubusercontent.com/59969508/81832058-57b1c300-953e-11ea-8897-cf9d0d16787f.png)

[log.txt](https://github.com/Courseplay/courseplay/files/4622918/log.txt)

**Comment by 0Pietro20** [comment]
When I press Ctrl + F6 the white parts in the photo remain like this, only closing the path and reopening it disappear (doing so the modification seems to be saved and for the current game it persists)

**Comment by Tensuko** [comment]
That is just a visual bug, caused by the REA Mod.
It also cause the visual offset to not disappear.
