### ISSUE TITLE
a sign that does not disappear

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#5393]
The red mark indicating the outline of the implement's operating area is continuously displayed. I don't know if it's just a graphic problem with my game or something

[log.txt](https://github.com/Courseplay/courseplay/files/4623484/log.txt)

![Farming Simulator 19 13_05_2020 18_17_20](https://user-images.githubusercontent.com/59969508/81842276-090b2580-954c-11ea-8c07-47f8b54e46d9.png)

**Comment by Tensuko** [comment]
#5391

> 
> 
> That is just a visual bug, caused by the REA Mod.
> It also cause the visual offset to not disappear.
