### ISSUE TITLE
Mode2: Stuck at: Waiting_for_pathfinder 

### ISSUE THREAD

**Issue by Martinnygaard** [Courseplay/courseplay#5396]
Hi,

I gave the new mode2 a try, but i had very mixed results.
I have version 6.02.00011 installed.
Running 1 chopper and two offloaders to a tip trigger.
3 headlands.

At first glance, everything is OK. A tractor drives to the chopper - and to the silo when full.
When the driver reaches back to the field waiting points, it just gets the status "Waiting_for_pathfinder" for 35sec, falls back to "waiting for call" and then try to find a path again.

Even if the chopper is only 20 meters ahead from the parking spot (in a direct line) it wont find a path.

![image](https://user-images.githubusercontent.com/26490587/81932540-40311380-95ec-11ea-9f21-be0618b4f001.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4628150/log.txt)

**Comment by Martinnygaard** [comment]
In general, the path finding is very slow for me. When trying to drive from the chopper to exit the field, it can take up to 30seconds aswell before finding a path.

**Comment by Tensuko** [comment]
ok this is a strange situation, it should very easy find the path.

**Comment by Martinnygaard** [comment]
If i stop all drivers, close the course from CP - then i can restart all the courses, and it will again let the first tractor fill up once, empty and drive to start - then it's all stuck again.
I have to restart both the combine and two tractors to make it work for one round more.

**Comment by Tensuko** [comment]
A log file with debug channel 4, 7 and 14 is needed here.

**Comment by pvaiko** [comment]
You can also try setting the offloader priority to distance (not fill level) and turning off pathfinding in the HUD.

> In general, the path finding is very slow for me.

That is because the new pathfinder will only generate drivable courses, taking into account the vehicle's turn radius and the starting/end direction, fruit and obstacles. If I did not have a day job and a family I could probably make it faster even in Lua. 

I may add an option later to make the pathfinder dumber but faster.

**Comment by answermanitou** [comment]
> You can also try setting the offloader priority to distance (not fill level) and turning off pathfinding in the HUD.
> 
> > In general, the path finding is very slow for me.
> 
> That is because the new pathfinder will only generate drivable courses, taking into account the vehicle's turn radius and the starting/end direction, fruit and obstacles. If I did not have a day job and a family I could probably make it faster even in Lua.
> 
> I may add an option later to make the pathfinder dumber but faster.

Dear. You make a great job. Do as you have time. We all are waiting and testing for bug and issues.

**Comment by Martinnygaard** [comment]
Here is 4, 7 and 14.
[log.txt](https://github.com/Courseplay/courseplay/files/4628964/log.txt)

I started the savegame, and tried to start both chopper and tractors as they were directly (as per image above)

No change.



I tried your suggestions:
I cannot find the unloader priority.
Shouldn't it be here?
![image](https://user-images.githubusercontent.com/26490587/81946415-9ce9f980-95ff-11ea-81e1-468616f49f1c.png)


Turning off the pathfinding made it find a route to the chopper - but at the first turn, it just wandered away...
![image](https://user-images.githubusercontent.com/26490587/81946573-d3c00f80-95ff-11ea-9d30-ec07cb65edb3.png)

**Comment by Martinnygaard** [comment]
I drove the tractor back to the field and started it. The other tractor was currently loading.
when it got empty, it came back, and both tractors tried to be at the same spot - both trying to offload...



![image](https://user-images.githubusercontent.com/26490587/81947456-dcfdac00-9600-11ea-8543-b09e17f88ef0.png)

[log.txt](https://github.com/Courseplay/courseplay/files/4629057/log.txt)

**Comment by pvaiko** [comment]
So the log shows that it was not able to find a path near the chopper, that is, from the vicinity of the chopper to a point behind the chopper, in the opposite direction. Would be nice to see that situation, where was the chopper, the tractor, the fruit..

**Comment by pvaiko** [comment]
@Martinnygaard as we stated many times, multiple unloaders are not supported yet.

**Comment by pvaiko** [comment]
Also, we never going to get anything fixed if everyone keeps throwing in five different problems into the same issue.

**Comment by Martinnygaard** [comment]
This screenshot is from the scenario last in the log.
![image](https://user-images.githubusercontent.com/26490587/81947868-585f5d80-9601-11ea-949e-5f10a93a5c70.png)

**Comment by pvaiko** [comment]
No idea why it can't find a path. Do you happen to have a savegame from that situation?

**Comment by archaoncze** [comment]
I doesnt try it with chopper, but i sometimes get similar problem. Unloader stuck trying to find way to combine for ages, so i stop him, move forward about 10 metrs, start him again and he find path pretty qwickly, even if he decide to move directly through forrest and find his way around trees. (field is very obscure shape and some edges have trees, or islands). Its little bit weird sometimes, but in general it works fine. For smaller fields especially. In big obscure shaped fields for headline runs is problems more often. But always works for me to stop unloader, move him little bit and start again.

**Comment by excubated** [comment]
I have found, the pathfinding from "unload course end" to "drive behind combine" tends to go a lot slower (or not at all) if unload courses last waypoint is outside the field. For some reason tho, spamming the keyboard shortcut for open/close HUD sometimes mysteriously fixes the stuck

OT: First post, yay.

**Comment by Martinnygaard** [comment]
> No idea why it can't find a path. Do you happen to have a savegame from that situation?

I have cleaned the savegame (sold all mods and stuff)
This is the status at time of save:
Only one unloader active. Pathfinding on. Chopper in the opposite corner of the field, working on the 3rd headland (so should be plenty of space to drive on).

The driver is "Waiting for pathfinding" and gives up every 35 seconds - then looping back on again.

![image](https://user-images.githubusercontent.com/26490587/82056015-9cb23280-96c1-11ea-9d48-0918c31435fd.png)
 
The map: (LakeLandValeByStevie)
[Stevie's Google Drive folder](https://drive.google.com/file/d/1dX9TvVw6gl9TTnEtkVi40PEZZr7q4LaH/view?fbclid=IwAR1HnMhYnBRGDeP8aYZuCEh53V07_dO7mIH4mSeXMKC_h7aP9HSSEsTGYCQ)

The Courses:
[FS19_LakeLandValeByStevie.Lakeland.zip](https://github.com/Courseplay/courseplay/files/4634676/FS19_LakeLandValeByStevie.Lakeland.zip)

Log from time of saving the savegame:
[log.txt](https://github.com/Courseplay/courseplay/files/4634665/log.txt)

The cleaned savegame with this scenario on it:
[savegame2.zip](https://github.com/Courseplay/courseplay/files/4634656/savegame2.zip)

**Comment by Partyborner** [comment]
Hello, I just wanted to say that I have exactly the same problem as Martinnygaard, my tractor does not drive over the harvested corn, it is stuck at waiting for path.
I suspect it's because of the harvested corn, because as soon as there is harvested corn at the entry of the path my tractor won't find the path anymore. 
Could that be the problem?

**Comment by Goof245** [comment]
I ended up making my own hacks to the pathfinder to get it to actually work on the larger fields I work on, code is very likely a hackjob but nonetheless may be of interest to look at...

https://gist.github.com/Goof245/c75732770d1cdc3640ce1eb47a45c9b9

**Comment by pvaiko** [comment]
@Goof245 wow. Finally someone. Thanks! Did you figure out how to use the DevHelper to test pathfinding in the game?

**Comment by Goof245** [comment]
Yeah that's what prompted me to look at it, the thing was just a bit too eager to "flood-fill" areas rather than move straight at the target when it could... The CTRL / ALT + <> is a neat tool!

50% is probably too high for "perfect" paths on smaller fields, but it's been working OK so far for the larger fields I've been messing around with (20-30ha fields)

As an aside, the "hybrid" part of the pathfinder makes some gorgeous looking patterns when it fails 😄 
![20200518215913_1](https://user-images.githubusercontent.com/3851003/82442015-3aeb3180-9ae2-11ea-8b4a-98fa64ee07e6.jpg)

**Comment by pvaiko** [comment]
Yeah, right, I love watching it growing.

I sent you an invitation to the dev chat if you are interested in discussing this.

**Comment by Goof245** [comment]
Thanks, I've very much in the "know just enough lua to be dangerous" category, but just hope I can help when I can <3

**Comment by Tensuko** [comment]
Uhm, what about this super old Issue ?
I think we can close this for now, as we have other Pathfinder related Issues ?
