### ISSUE TITLE
What have you DONE. Tractor does not get called

### ISSUE THREAD

**Issue by Beebtrek** [Courseplay/courseplay#5397]
I have a Harvester doing a field gets full. sets for ever with pipe out wait for tractor. Never comes.

Tractor has trailer waiting in field route set up and laid drive enabled but it does not call it. 

Tried setting the harvester to request said tractor it does not even see the tractor.

Why was it working in Courseplay_6_01_00397.

But Not now.

**Comment by pvaiko** [comment]
#5272
