### ISSUE TITLE
Ok INSTRUCTIONS.

### ISSUE THREAD

**Issue by Beebtrek** [Courseplay/courseplay#5398]
Those Instructions are difficult to understand. In that they are full of TECNO Speak Talking about Mode 2 and helper.

Ok let me Explain what Does Mode 2 Mean. In the end I realised it refers to the unload method.

Helper? That refers to a course running UNDER Courseplay Not the Farming Simulator 19 Helper.

I have Now spent the last couple hours trying to get the tractor to go to the Harvester But I seem to have to go to the harvester courseplay menu and Request harvester to attend. 

Also Trying to reset the STORED offsets for a used tractor from previous save was MY ERROR.
Even resetting it did not sort it. The only way was to sell Tractor and Buy a different model.

Now after starting a new Game I am still getting some of these issues.

YES I KNOW IT IS A DEVELOPER VERSION. So Flames are not appropriate but I do feel that a more logical approach to information would be helpful.

**Comment by Tensuko** [comment]
https://1drv.ms/v/s!ArGbP_j369r8lSoaKZjPfVN9eOzh?e=OLkM0g

**Comment by Beebtrek** [comment]
Thanks Tensuko . Most helpful.
I can now report on some valid errors. I will be testing over the next few days. This is what I have found. When the tractor returns from an Unload It does not seem to get recalled by harvester. Unless I call it from harvester.

Also If tractor is set to off load to silo at 100 % it start to leave harvester at 83% than does not goto silo and the harvester continues to harvest but does not recall tractor. OOPS.

But it does seem you have solved the ramming of the harvester problems we have been having for YEARS. Big Grin. Well three steps forward and two back. I will now read how to do correct bug reports as with High quality vids and screen shots as necessary with debug modes as needed.

**Comment by Tensuko** [comment]
> When the tractor returns from an Unload It does not seem to get recalled by harvester. Unless I call it from harvester.

only happens when the harvester is full. #5272 

> Also If tractor is set to off load to silo at 100 % it start to leave harvester at 83% than does not goto silo and the harvester continues to harvest but does not recall tractor. OOPS.

No Idea what you mean, read #5272 

> But it does seem you have solved the ramming of the harvester problems we have been having for YEARS. Big Grin.

That is not solved, the old got thrown away and created a new Mode2...

> Well three steps forward and two back.

We are on a completely new path...

> I will now read how to do correct bug reports as with High quality vids and screen shots as necessary with debug modes as needed.

Thats the only thing that will help. Thats why I close this now.

**Comment by Beebtrek** [comment]
True as to new path. Yes it is different and maybe need to start from scratch to look at what is going on without mods loaded other than courseplay. I have also noticed some lagging. But other things maybe causing that. Your video was helpful thanks.

**Comment by Beebtrek** [comment]
Also I think I am only looking in this GITHUB when I see difficult problems so do not keep up with all the threads.

**Comment by Beebtrek** [comment]
OK run one field with one harvester and one tractor it works GREAT. Or seems too. But if you try to push the boundaries it falls over. I.e four harvesters over four different fields it gets upset. Oh dear what a shame <grin> I am not seeing any framerate issues. But if I have lots of mods going that utilise programming features (LUA code) then you start to see slow downs.

Is that what is expected?
Are there any tests you want me to specifically look at ? I am using an intel  I9-7900X at 3.8 Gig with a 1080 gfx.
