### ISSUE TITLE
FPS Drop

### ISSUE THREAD

**Issue by MoritzJDR** [Courseplay/courseplay#5401]
Sobald der Abfahrer nach dem Drescher auf dem Feld sucht droppen die FPS von 60 auf 10 runter und es passiert erstmal 20 Sekunden gar nix. Dann hat er den Drescher gefunden und die FPS ziehen wieder hoch, sehr seltsam
--EDIT---
Der LKW (sowohl Standart als auch Mod) findet den Drescher überhaupt nicht mehr. Steht am Feldrand und macht nix mehr

**Comment by Tensuko** [comment]
#5272
