### ISSUE TITLE
Mode 9 issue when exiting the bunker

### ISSUE THREAD

**Issue by polosubtil** [Courseplay/courseplay#5402]
Hi,
No major issue, but I have an problem when my telehandler is filling its shovel in the bunker silo
The shovel is suppose to go to transport position as soon as it's full but for some reason (in 95 % of the case I would say), the shovel stays in filling positioning until it's getting out of the Bunker Silo.
Not sure, just a guess : STATE_REVERSE_STRAIGHT_OUT_OF_SILO has the wrong shovel position in the code. And STATE_REVERSE_OUT_OF_SILO has the correct one which could explain why it works sometimes. As my developer skills are below 0, this is just a wild guess. I gave it a try on my fork but I am completely useless so far :)

Everything else works fine by the way

![fsScreen_2020_05_14_23_01_56](https://user-images.githubusercontent.com/60451845/81989161-05a39700-963d-11ea-9c2c-869d548895a1.png)
![fsScreen_2020_05_14_23_01_58](https://user-images.githubusercontent.com/60451845/81989180-0e946880-963d-11ea-945b-ffe935f83ef8.png)
![fsScreen_2020_05_14_23_02_01](https://user-images.githubusercontent.com/60451845/81989191-16540d00-963d-11ea-95fa-e1863a27a842.png)
![fsScreen_2020_05_14_23_02_04](https://user-images.githubusercontent.com/60451845/81989217-2370fc00-963d-11ea-8a71-7627f5e10775.png)
![fsScreen_2020_05_14_23_02_05](https://user-images.githubusercontent.com/60451845/81989243-2f5cbe00-963d-11ea-8fe3-f2691b128da4.png)
![fsScreen_2020_05_14_23_02_07](https://user-images.githubusercontent.com/60451845/81989256-37b4f900-963d-11ea-878e-e248a705a9db.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4631040/log.txt)

**Comment by TinyCrocodile** [comment]
Hi 
Thanks to your guess i think i saw something in the code. I will give a try but will need some time to set things up.

**Comment by polosubtil** [comment]
@TinyCrocodile that's good news.
I have a savegame with everything set to do some tests, so just let me know if you want me to try some stuff
Just so you know, I tried to play with the code on my fork yesterday evening, it's a miracle my PC didn't set on fire as my code was sooooo wrong ;)

**Comment by TinyCrocodile** [comment]
I have it working on my Savegame.  I will submit a PR, when ready.

**Comment by polosubtil** [comment]
@TinyCrocodile, great thanks
Do you mind if I try it too ?

**Comment by TinyCrocodile** [comment]
@polosubtil 
You can Try at any times.
See the Code in the Pull Request above

**Comment by polosubtil** [comment]
I just tried, it works like a charm. Thanks a lot for that @TinyCrocodile

**Comment by TinyCrocodile** [comment]
You're welcome.
I'm glad to hear this.
