### ISSUE TITLE
Combine claims full at 99%, unloader does not trigger pickup

### ISSUE THREAD

**Issue by excubated** [Courseplay/courseplay#5403]
Hello,

I ran into a weird bug earlier today. A Bison combine was 99% full at the end of a row. It completed the turn but stops before starting next row, reporting "needs to be unloaded" in the GUI. Unloader tractor is not called, however, because it is looking for 100% flat. Rounding error maybe?

I can't imagine being able to easily reproduce under "natural" conditions, the chance of hitting 99 % at the end of a row is pretty slim. Shout out if a log file might help!

CP 6.2.12

**Comment by Tensuko** [comment]
The Tractor isnt looking for anything except the call.
The Combine will decide when the unloader should come.
Read #5272 and provide the needed informations...

**Comment by Pioner912** [comment]
Hallo zusammen Ich habe das gleiche Problem wie der Ersteller! 
Ich verstehe auch das der Drescher den Abfahrer nur triggert wenn er zu 100% Voll ist, aber bei mir in den Einstellung steht das er zu 100% auffüllen soll. 

Dies macht der Drescher aber nicht sondern bleibt bei 99% stehen und ruft dann den Abfahrer nicht. 
Der Drescher ist der Lexion vom Claas DLC gibt es mit diesem vielleicht ein Problem? 

Noch eine kleine Zusatzfrage warum kann ich bei dem Abfahrer nicht mehr einstellen das er bei sagen wir mal 80% "Starten" soll und den Dreschen anfährt? Das war immer ein wichtiges Feature für mich da man ja mal größere und auch kleiner Felder hat welche man bearbeitet und ich die Wartezeiten vom stoppen des Dreschers bis zum Entlerren so kurz wie möglich halten möchte. 

Vielen Dank schonmal im vorraus! 
Ihr macht eine super Arbeit :-)

**Comment by Tensuko** [comment]
2 Options:
1) Combine unload while stay, then the % should be set to arround 90% and the combine will tell the unloader when to come.
2) Combine unload while drive, set the % you want or leave it to 50% that should work now.
Closing this as tested.
