### ISSUE TITLE
Grimme Rootster 604

### ISSUE THREAD

**Issue by jspring0811** [Courseplay/courseplay#5404]
Several issues with this trying to use combine/mode2 (driver never gets called)...

https://drive.google.com/open?id=1jVIeiC2tPmD_SP4Sx5-KJrskhUTEW2ur

So, I am just trying to manually drive a tipper next to the Rootster and it keeps opening/closing the output (pipe) constantly.  I don't suppose there's a setting to force/leave the (pipe) output open all the time?

Thanks.

**Comment by Tensuko** [comment]
Becouse we force combine to stop while unload. This is written in #5272 and will be changed later when unload while drive is working and tested.
