### ISSUE TITLE
shredded

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#5405]
I tried to chop (using the CP v6.02.00012). Everything was controlled by the CP (a total of 5 routes, one for the forage harvester, three for the tractors with trailers and another for the tractor that pushed the chopper). I used the original Krone Big X 1180 forage harvester because I noticed that the others either have a too short duct and cannot unload on the trailers (I use the 3-axle Bossini) or, if they have a long duct, some have the signal (which says to the tractor as far as it can go without crashing on the forage harvester) too far back (sorry but I don't have photos of that). Anyway after the first two loaded trailers the third one got stuck and it was not moving towards the forage harvester anymore (I attach photos and log)

I also wanted to ask 2 more questions: what is the option on the "convoy of vehicles"? And it is possible to push the chopper using more than one worker (it would be very convenient since very often he cannot push before the next trailer arrives)

I also wanted to congratulate you for the excellent work for the programming of the maneuvers performed by the forage harvester and tractor with trailer, really compliments

![Farming Simulator 19 15_05_2020 12_34_31](https://user-images.githubusercontent.com/59969508/82042309-f3ac0d80-96a9-11ea-9808-1343cdc650cf.png)

![Farming Simulator 19 15_05_2020 12_34_44](https://user-images.githubusercontent.com/59969508/82042317-f7d82b00-96a9-11ea-9d18-e97c93f67f6b.png)

[log.txt](https://github.com/Courseplay/courseplay/files/4633869/log.txt)

**Comment by Tensuko** [comment]
To your questions:
Basically you can assign 2 or more Tractors, but we haven't worked on a good 'exchange' system so the Tractors switch at the Chopper. I am not sure about more then 2, if the 3rd will cause Problem.
That is one of our next Plans. Right now we are working on unload Combine while move.

What should work (and did in all my tests so far) was one Tractor per Combine/Chopper.
And right now I can only suggest you to use only one. I know its a bit slow, but we have to approach this step by step.

**Comment by 0Pietro20** [comment]
No problem, I'll wait for updates and for now I'll do the job with one (or if I see it works with two). However, as already mentioned, the maneuvers of tractors and forage harvesters have improved a lot and I find them well done.

If, in the future, you will also work on pushing the chaff in the trench (given that the grader pushes little material at a time unfortunately) maybe you could think about implementing that work in pairs

**Comment by 0Pietro20** [comment]
I would just like to point out a couple of things (so as to already have information for future updates on how to fill the trailer with a forage harvester): while the first tractor follows the forage harvester and when it has to go to unload it follows the path where it has already been chopped (not stepping on the crop) it is hindering the road to the second tractor that would follow the same trajectory. Since for now the second tractor does not follow the first one (when maybe the trailer is 80-90% loaded) I would find it useful if instead it followed it so that, during the exchange, a wide turn of the first would be enough to make room for the second and not get in the way of each other. I also noticed that the second one when the trailer is filled does not follow the trajectory where there is no crop passing through the middle of the field (I think it is the one that generates the problem that makes everything block)

**Comment by Tensuko** [comment]
As discribed here:
#5272
