### ISSUE TITLE
Fahrmodus  Spinnt als Abfahrer!?

### ISSUE THREAD

**Issue by RobinHooooood** [Courseplay/courseplay#5407]
Hab Ver 6.02 und immer wenn ich ein Kurs einfahre der den Drescher abtanken soll und ins Silo fahren soll Funktuniert das nicht. Der Abfahrer findet den Drescher nicht, den muss ich dann erst auswählen und selbst dann funktioniert es nur sehr selten, wenn ich im Drescher sitze und den Abfahrer manuel rufe kommt er auch nicht und ich kann wenn ich im Abfahrer sitze nicht sagen Sofort abfahren. 
Hatte auch das Problem wenn ich so ein Kurs richtig eingefahren hab ,dass nach den einstellen des Abfahrer es zu Massieven Lags komm von 60 auf 14 Fps. Ich kann mir das nur erklären das der Modus da so viele fehler geworfen hat das es zu diesen Lags kam. Nach dem ich den Abfahrer entlassen hab ging die Fps Anzeige  direkt wieder auf 60Fps hoch.
Nein kann meiner Meinug nach nicht an der Cpu liegen da sie selbst bei aktivierten Abfahrer mit 15Fps bei 20% Auslastung lang.

Hab ein Ryzen 7 2700x auf 4 Ghz

**Comment by Tensuko** [comment]
Das sind keine Fehler und keine lags. Es sind FPS drops und selbst wenn du einen supercomputer hättest würde die Engine mit dem LUA Code den Weg nicht schneller berechnen können.
