### ISSUE TITLE
Wurde das Problem mit der Premos behoben?

### ISSUE THREAD

**Issue by RobinHooooood** [Courseplay/courseplay#5409]
Möchte Fragen ob das Problem mit der Premos behoben wurde oder allgemein das Problem mit dem Strohbergungs Addon ?

**Comment by Tensuko** [comment]
Welches Problem ??

**Comment by RobinHooooood** [comment]
Na das wenn man beides Zusammen nutzt den Spielstand schrotten könnte.
Und noch eine Frage warum erkennt der Abfahrer die Premos nicht und läd sie nicht ab

**Comment by Tensuko** [comment]
Wenn du die aktuelle CP Version und die Beta 27 (1.0.0.2) von Strohbergung benutzt ist das Problem behoben.
Das nicht erkennen ist noch ein Problem da wir die Premos extra behandeln müssen.

**Comment by GeorgeEarslight** [comment]
@pvaiko Peter do you know how to check for a spec from another mod?
I'm trying to handle the Premos pelletizer but can't seem to be able to call/check the spec like base specs (Combine, Plow, etc).
`(StrawHarvestPelletizer = {} @ \\FS19_addon_strawHarvest.zip\src\vehicles\StrawHarvestPelletizer.lua)`

**Comment by pvaiko** [comment]
@Tensuko has contact with the straw harvest devs, he may be able to help

**Comment by Tensuko** [comment]
@GeorgeEarslight do you have Discord ? They got a Discord Server for such questions:
https://discord.gg/MegfJq

**Comment by GeorgeEarslight** [comment]
@pvaiko @Tensuko thanks guys, I'll check out their discord
