### ISSUE TITLE
Pathfinding Problems?

### ISSUE THREAD

**Issue by JoaoSilva1994** [Courseplay/courseplay#5411]
Ok, so 2 days ago, i had a problem with unloading triggers, and it was all fixed, and they worked perfectly for that day .

Today, i'm having this little problem, same courses, same routes, except this time i have 2 or 3 mores courses, with 3 different Combines, 1 for SugarCane, 1 for Chaff, and one for my Soybeans, all of the 3 are using, a CP generated Course, with 2 Headlands.

But now, the problem is with the pathfinding, or at least i think it is, all 3 combines are ready to unload, since the Chopper doesn't have a "tank", it's always ready, but all the trucks are just stopped, not going to the combines to unload, i thought it was because they didn't want to run over the fields that are no harvested, and so, i did one Headland by myself, on one of the chaff fields, but then i noticed that the Soybean Field, was almost fully harvested, and still, the truck, with imense space to go on the field, stands still, beside the combine, not going underneath the combine pipe to unload.
![fsScreen_2020_05_16_09_15_35](https://user-images.githubusercontent.com/9709349/82114812-d719df00-9756-11ea-871a-82e8d1a1d5f6.png)
![fsScreen_2020_05_16_09_15_43](https://user-images.githubusercontent.com/9709349/82114814-daad6600-9756-11ea-9181-9ab4b90efd07.png)
![fsScreen_2020_05_16_09_21_00](https://user-images.githubusercontent.com/9709349/82114817-ded98380-9756-11ea-939d-6f445f206f54.png)

I can see with the debug channels on **_(3,4,9,11,14,16)_** that the truck on the soybean field wants to take a certain path to follow the combine, but since the combine is stopped, he can't follow that path, and they just stand there with no actual unloading at all.

**Comment by JoaoSilva1994** [comment]
I don't know if its the map it self, that since it has those big canals near the fields, it's messing with the pathfinding, since one of the trucks, during its pathfinding adventures, found himself stuck in one of those said canals

**Comment by Tensuko** [comment]
Debugchannel 4 7 12 and 14

**Comment by JoaoSilva1994** [comment]
![fsScreen_2020_05_16_10_05_15](https://user-images.githubusercontent.com/9709349/82115786-d5531a00-975c-11ea-9a46-2d0696f1fe6a.png)
Here it is, with 4, 7, 12 and 14 on ! Other are off !

**Comment by Tensuko** [comment]
The logfile would be more important.

**Comment by JoaoSilva1994** [comment]
This is the current field i only have with courseplay enabled, the soybean i unloaded the combine by myself, and the combine then completed the course! I have a Sunflower field to combine still, if you want, i get the combine working on it, until full, and see if it does the same thing, and take a screen..

**Comment by Tensuko** [comment]
And why is the course in the middle of the field ? If you do that you should turn off pathfinding in the HUD (not adc settings)

**Comment by JoaoSilva1994** [comment]
> The logfile would be more important.

Sorry, here it is !!
[log.txt](https://github.com/Courseplay/courseplay/files/4638109/log.txt)

**Comment by JoaoSilva1994** [comment]
> And why is the course in the middle of the field ? If you do that you should turn off pathfinding in the HUD (not adc settings)

It has to be because of those said canals beside the fields, here is a screen, if i don't use the course like that, the trucks, tractores, and everything gets stuck .. Can't work around those ca
![fsScreen_2020_05_16_10_08_25](https://user-images.githubusercontent.com/9709349/82115862-5d392400-975d-11ea-9c3d-1126f0fb95f8.png)
nals..

**Comment by Tensuko** [comment]
Ok but then you have to turn off pathfinding else he wont find a way arround the fruit, couse he is in the fruit...

**Comment by JoaoSilva1994** [comment]
> Ok but then you have to turn off pathfinding else he wont find a way arround the fruit, couse he is in the fruit...

I think i will just change the map honestly, to be simple, because this map has been giving problem with everything, not only CP, but also the vanilla worker, they just get stuck in those canals all the time ...
