### ISSUE TITLE
chopped with a tractor

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#5412]
I open another topic because the problem occurs with a forage harvester and only one tractor. The field in question is not small and when the forage harvester is on the other side with respect to where the tractor is located (where I finished recording the unloading path of the tractor with trailer) the tractor does not move, not finding the path to arrive to the forage harvester. This test I did with ONLY ONE tractor and a forage harvester. The first two approaches worked perfectly, the third that occurs when the forage harvester is on the other side does not happen. Today I will try to send the driver to unload in a different position and see how it behaves. I wait for an answer (in case you need photos or logs of the game)

**Comment by Tensuko** [comment]
Debugchannels 4 7 12 and 14 as discrbed here #5272

**Comment by 0Pietro20** [comment]
I will attach the log anyway I have to apologize and correct the post: I did various tests and the tractor stops only when the forage harvester is at that point. Sending it to download a few meters before everything works perfectly (approximately). I also carried out a test with two tractors and all the exchanges work perfectly, the pushing of the silage is going well, everything is fine. The only flaw is caused by the tractor which, standing next to the threshing machine, tends to go too far forward, preventing the latter from unloading correctly

**Comment by 0Pietro20** [comment]
I commented where I was told

**Comment by 0Pietro20** [comment]
I have given below the photos of what happens with the indicated debug channels active. The message varies from "waiting for combine to call" to "waiting for pathfinder"

![Farming Simulator 19 16_05_2020 14_25_07](https://user-images.githubusercontent.com/59969508/82119757-5f14de80-9781-11ea-8c7b-86dfc1e30dbb.png)
![Farming Simulator 19 16_05_2020 14_25_18](https://user-images.githubusercontent.com/59969508/82119761-6340fc00-9781-11ea-9447-78a94286ef38.png)
![Farming Simulator 19 16_05_2020 14_25_26](https://user-images.githubusercontent.com/59969508/82119762-65a35600-9781-11ea-9ef9-6ac3604bcae4.png)
![Uploading Farming Simulator 19 16_05_2020 14_25_55.png…]()

The log
[Uploading log.txt…]()

**Comment by 0Pietro20** [comment]
I send back the last photo and the log (I can't see it so for safety I send it back)
![Farming Simulator 19 16_05_2020 14_25_55](https://user-images.githubusercontent.com/59969508/82119876-2de8de00-9782-11ea-9dea-a2137a61b260.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4638347/log.txt)

**Comment by Tensuko** [comment]
Pathfinder stuff.
Having some Issues and keep adjusting it, had a recent update so closing this as it is to old.
