### ISSUE TITLE
Crash game when use Tab.

### ISSUE THREAD

**Issue by Vanquish081** [Courseplay/courseplay#5413]
Leave the JCB Fastrac with the Lemken seeding using Courseplay and when you return to the vehicle switching with Tab the game crashes completely.
[log.txt](https://github.com/Courseplay/courseplay/files/4638793/log.txt)

**Comment by Tensuko** [comment]
I don't see a CP error here.....

**Comment by Vanquish081** [comment]
What is the error then? the hang occurred when changing to the vehicle using CP

**Comment by Tensuko** [comment]
Mod Issue I would say.
