### ISSUE TITLE
dediServer

### ISSUE THREAD

**Issue by JayT40** [Courseplay/courseplay#5414]
Hi, haben CP auf dem dediServer laufen und auch einige Kleinigkeiten festgestellt. Wenn ein Mitspieler den Abfahrer einstellt, sieht der zweite Mitspieler keinen Char im Traktor und wenn der Traktor fährt, sieht auch der zweite Mitspieler keinen Lenkeinschlag der Räder wenn das Fahrzeug Kurven fährt, Es lassen sich keine gespeicherten Kurse löschen und wenn man den Abfahrer entlässt muss man immer noch einmal per Taste H den Helfer entlassen, was wiederum nen callstack in die log.txt schmeißt. Aber glaube der callstack ist seit dem letzten fix nicht mehr vorhanden. Falls diese Sachen noch gefixt werden könnten sind wir überglücklich :-). Mfg

**Comment by JayT40** [comment]
Seit der neuen Version bzw. V. 6.01.00399 bis aktuell lässt sich der Abfahrer auf dem dediServer zwar einstellen aber bewegt sich keinen Meter mehr, bzw. findet /wählt keinen Mähdrescher mehr. Von Seiten des Mähdreschers lässt sich auch kein Abfahrer mehr rufen. Alles im Multiplayer auf einem Dedi-Server, müsste wenn auch so getestet werden, da  ein MP spiel wo ein Spieler auf macht und ein user joint nicht das gleiche ist wie wenn man einen Dedi-Server betritt ;-) . Viele Grüße

**Comment by TinyCrocodile** [comment]
#5272

**Comment by Tensuko** [comment]
Collecting all in #5484
