### ISSUE TITLE
Multiplayer - Contracts

### ISSUE THREAD

**Issue by resultwrap** [Courseplay/courseplay#5416]
Hello, I am the creator of our farm and have accepted a bunch of contracts before I had other players join. After they join, the players (except for me) can't create any courses on those contracts unless it's on a owned field. I have promoted them to a farm manager with all permissions. The are allowed to create courses on contracts that they accept after they join. 

Another example would be if we restart the multiplayer game, only I can create courses on already accepted contracts from the previous game. 

Thanks

**Comment by resultwrap** [comment]
I forgot to mention, when they can't create a course, I'll hope in and create a course which works fine for me, and then when I leave it, they can now see the course. However, when they delete the course and try to recreate it for themselves, they still can't.

**Comment by Tensuko** [comment]
Collecting all in #5484
