### ISSUE TITLE
Two Planters - Headlands

### ISSUE THREAD

**Issue by dsmith109** [Courseplay/courseplay#5418]
When I create a course for multiple tools (specifically 2 planters) I am having an issue with the workers starting on the headland.  I am attempting to plant a Clockwise Headland, beginning in the SW corner, for a field planting longways E/W.  The planter set 1 lane right, will not start on the headland.  He always skips the headland and begins on the first row going East.  I have attempted to recreate the course and change which tractors are in the Right offset, but it always reproduces the same issue.  If I make the course without a headland, the multiple tool planting works fine.  Is there something I am missing?

**Comment by vemendoza** [comment]
For me this problem ever occur when the points of headland is over the points of row. To solve this problem, I ever try to create a route that points of headland never stay over points of rows. Choose one place on map to put your 1st point that this not occur.

**Comment by Tensuko** [comment]
Headland course should start on the side of the field.
But for the Issue you have:
I think debugchannel 7, 12 and 14 would be enough.

**Comment by mpochylko** [comment]
I have the same problem with my harvesters. The machines will not pick up on the "right" side of the course for the headlands. Once off headlands, machines run great.

**Comment by TinyCrocodile** [comment]
> Headland course should start on the side of the field.
> But for the Issue you have:
> I think debugchannel 7, 12 and 14 would be enough.

Dito.

**Comment by pvaiko** [comment]
This should really only happen if you start the course at the 'next closest waypoint'. Should work fine with 'first waypoint', or any other I think.

**Comment by pvaiko** [comment]
And even then, it is really unlikely. Can someone post a video or at least a screenshot with all those debug channels and course shown? And there's still no log...

**Comment by mpochylko** [comment]
I'll try to get a video pvaiko

**Comment by mpochylko** [comment]
Could not replicate the problem folks.
