### ISSUE TITLE
Harvester self unload problem

### ISSUE THREAD

**Issue by Scania1983** [Courseplay/courseplay#5420]
[log.txt](https://github.com/Courseplay/courseplay/files/4639770/log.txt)

Hello, the self unload function is not working, trailer is in the field, self unload checked in de advanced settings, when full pipe goes out, engine running, but stops moving

**Comment by Tensuko** [comment]
Can you make a Screenshot where the Trailer and Combine is when it should go to unload ?

**Comment by Scania1983** [comment]
> Can you make a Screenshot where the Trailer and Combine is when it should go to unload ?



![fsScreen_2020_05_17_11_16_33 (2)](https://user-images.githubusercontent.com/65482225/82140665-b4f48f80-9830-11ea-9d41-944d14ef1b2e.png)

It won't fill to a 100 %. It gets to 9979 or so and stop harvesting, maybe there is the problem?

**Comment by Tensuko** [comment]
Did the Harvester drove by itself to unload now ?
I don't know what exactly is the problem now and how to reproduce this step by step.

**Comment by Scania1983** [comment]
No, I drove it to the trailer, it just stops harvesting, lift the mower, thinks, does the pipe out and stands still, weird situation, I randomly took another version of CP and put it in my mods map, still the same issue

**Comment by Scania1983** [comment]
I tried it again in a different map, same setup, same tractor and equipment, same error 😳

**Comment by Scania1983** [comment]
New update, when finished harvesting the whole field, it goes to the trailer and unload

**Comment by Scania1983** [comment]
This is now working too, with around the crop activated 👍🏻🙊
