### ISSUE TITLE
unload problem trailer

### ISSUE THREAD

**Issue by wertigoxxx** [Courseplay/courseplay#5422]
Hallo!
My problem is that the combine always tries to harvest the crop only when it is full, at the second event it just calls the tractor there, stands under the pipe and starts reversing right away.
The first event goes all the way through, the rest is just watering, but the tractor won’t wait for the combine to empty!
What can I do ?

**Comment by TinyCrocodile** [comment]
Hi 
1.st Read #5272 
2.nd Adjust the vertical offset oft the Trailer a bit to the front. 
3.d If both din't help post a log as  described in 1 and maybe a screenshot of the situation.

**Comment by wertigoxxx** [comment]
Why does it work that way?  😄 There was no such problem with older versions.  🙂

**Comment by TinyCrocodile** [comment]
Because the old one was outdated and hard to manage.
The devs needed to create a new one where changes are easier to implement and do not break other things.
It is way more complicated than this but i cant describe better in English.

**Comment by wertigoxxx** [comment]
Thanks for the help, but unfortunately what you suggested doesn't work :(
in the same other event, however, the tractor stands under the pipe and ignores it. it starts immediately and goes to try after the combine every half minute.

I'm sorry this is how it works!
Will it be fixed later?

**Comment by Tensuko** [comment]
This is not how it works and it doesn't need a fix.

Logfile with channel 4 7 12 and 14 and screenshot of your situation.
Also as @TinyCrocodile said, adjust with the offset. Some Mod Trailers have a stupid Target Position just at the back, no chanze to unload it in default settings, so change your offset.
Again, Screenshots will help.

**Comment by Tensuko** [comment]
Old Version, Old Issue and not requested Information, closing. Make new Issue with more clear Title and requested Information when Problem still exists.
