### ISSUE TITLE
How to change the key to open Courseplay on FS19 ?

### ISSUE THREAD

**Issue by HxgxxgxH** [Courseplay/courseplay#5423]
I juste whant to change the key to open courseplay on FS19, please give a solution please .

**Comment by patch110** [comment]
Im sure you can change it in the keybindings in the game

**Comment by Tensuko** [comment]
Keybindings ?
Default is set to del.
If you don't want that mouse click opens the HUD, disable the mouse in the adv settings, else on your vehicle (1st page) or global (2nd page).
