### ISSUE TITLE
HUD Seed Calculator button shows up on first start but not when mode Change

### ISSUE THREAD

**Issue by TinyCrocodile** [Courseplay/courseplay#5424]
Hi 
The Button for the seed calculator only shows up, when i Start the Game. If a other mode was active bevore, the Seed-Calculator button is not displayed. 
And also the Lane-Offset buttons do change. 

Clicking on the Seed calculator button throws folowing error:
2020-05-17 20:43 Error: Running LUA method 'draw'.
2020-05-17 20:43 E:/Daten Tinu/Dokumente/My Games/FarmingSimulator2019/mods/FS19_Courseplay6/hud.lua:610: attempt to index local 'selectedField' (a nil value)

I did also try to do this when a Field  was scanned with the same Result.

![fsScreen_2020_05_17_20_44_07](https://user-images.githubusercontent.com/34377785/82157428-aaaeb180-9881-11ea-8651-b90cb06d833b.png)
![fsScreen_2020_05_17_20_43_36](https://user-images.githubusercontent.com/34377785/82157417-9c609580-9881-11ea-810d-66c7010e2a55.png)
![fsScreen_2020_05_17_20_41_04](https://user-images.githubusercontent.com/34377785/82157412-97034b00-9881-11ea-96ad-a3f39503a1a7.png)

Log with chanel 18
[log.txt](https://github.com/Courseplay/courseplay/files/4640825/log.txt)

Steps to Reproduce:
Set up A Driver with a seeder and select mode 4. 
Swich to Offset Tab. No seed calculator
Save and restart the game.
Hop in the Tractor with seeder.
See the offset tab: seed Calculator is there
Click on the seed calculator: Error is thrown
Swich to Mode 5
Swich back to Mode 4: no seed calculator any more

**Comment by Tensuko** [comment]
Yea I know this, I also can't always bringt it up but to be honest I think about remove it, as Global Company got a Complete Calculator for all Fields and all kind of filltypes (seed, fertilizer, manure etc etc).
Not sure how accurate that GC Calculator is, but less for us to maintain.

**Comment by TinyCrocodile** [comment]
Thats a pity i don't like to use gc. But i understand your point. The best woud be to take it out and make it a standalone mod. Having not too much aditional stuff in cp is a good idea.
