### ISSUE TITLE
Quick question about combines unloading

### ISSUE THREAD

**Issue by mpochylko** [Courseplay/courseplay#5425]
Hi, 

Really quick, since the new update (latest CP) my combines stop and start backing up when the unload trigger is triggered. They back up and move over a lane, the same way the 1st combine does on lap one of a field. I've tried to shut all settings off I could think of but can't make them stop. They also stop to unload if the pipe is in the harvested side of the field, which creates a headache with 4 combines going. Any ideas on how to have the machines keep harvesting while unloading without stopping or backing up and over a lane?

**Comment by Tensuko** [comment]
#5272
