### ISSUE TITLE
Harvester Unloading, trailer won't stay still 

### ISSUE THREAD

**Issue by TexanMD** [Courseplay/courseplay#5428]
Hello, 

I think I might have a similar issue to #5422 but I realized I'm not experiencing "reversing right away"

In my case, the trailer is brought to the combine and then unloading begins.  Part of the way through the unloading, the unloading tractor+trailer starts "stutter moving" forward as if it is trying to keep itself aligned, but the harvester has not moved.  

I can work around most of the issue by setting thresholds to sell etc lower and also moving the vertical offset as far forward as possible, but it will often not fully unload the harvester before the trailer is no longer under the pipe.  

Since it is hard to describe I recorded a video of it happening.   I also enabled logging on 4,7.12 and 14 as requested in the linked issue.  

VIdeo is here (link is to a couple of seconds before the "stutter movement" starts) https://youtu.be/bQ7KCZZK8eM?t=155

In the log file I think that pathfinding for the unloader to path to the harvester starts at `2020-05-18 21:21 :23 ` (line 10487) 
[logTrailerMovement.txt](https://github.com/Courseplay/courseplay/files/4647807/logTrailerMovement.txt)

Please let me know if I can provide any extra info or if I can do anything else to help troubleshoot.

**Comment by Tensuko** [comment]
Yea that is some GIANTS 'feature'.
I also wan it to not happen as some trailers stutter to far forward and the unload stops.

**Comment by wertigoxxx** [comment]
That would interest me too, because that's my problem too! :)
It didn't do that with older versions.
I trust you, solve this too! ;)

**Comment by polosubtil** [comment]
I have the same issue. The only way I found is to move the target at the front of the trailer as much as possible using the offset setting. Then the target starts to move backward as the trailer fills up. I can load the trailer without issues now but the last combine unload is close to the back of the trailer.

**Comment by pvaiko** [comment]
I think this is for added realism to distribute the grain evenly in the trailer.

**Comment by lxfTTjek** [comment]
That would interest me too, because that's my problem too! :)
It didn't do that with older versions.
I trust you, solve this too! ;)

**Comment by polosubtil** [comment]
@pvaiko, well it does look nice now it's set on my trailers but I fear it might bring more complications for you ;)
The only way it could work is to make sure the target is actually at the very front of the trailer and starts moving backward only when the front "section" of the trailer is full (as high as possible). Same principle after that until it's full. almost like IRL.
But as I said, that is not really a priority, it would make it easier for you to keep it where it is all along the unload.

**Comment by kwguk** [comment]
I was happening for me so i put  a vertical offset in so it filled the middle of the trailer and it stayed still until the combine was empty. Sorted!

One very minor observation, the tractors flashing beacons stay on all the time even when theyre set to 'on street only'. You can turn them completely off or have them on all the time.

I seem to have to keep readjusting the cruise speed of the tractor. It seems to ignore the speeds i have set in the HUD and will appear to set its own speed. You can adjust this speed even when CP is  in operation using the usual cruise control keys.

Final minor gripe,when the tractor is calculating its route to the combine it kills my FPS for as long as the calculation takes.

**Comment by Tensuko** [comment]
Was not happening on my side anymore, not while standing and not while driving. Closing.
