### ISSUE TITLE
advanced settings / AutoDrive

### ISSUE THREAD

**Issue by STW0701** [Courseplay/courseplay#5429]
Hello
I have the problem with advanced settings/ AutoDrive.
The changes are not saved. If i change my vehicles.xml the cp settings for ad for example:
i change this line:
  <autoDriveMode value="3"/>
to
  <autoDriveMode value="2"/>
it work until i saved the game, then the changes will be undone

**Comment by Tensuko** [comment]
logfile ? ...

**Comment by STW0701** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4658364/log.txt)

**Comment by Tensuko** [comment]
You have some strange Errors in your log:
2020-05-19 21:43 Error: Running LUA method 'mouseEvent'.
2020-05-19 21:43 dataS/scripts/vehicles/VehicleEnterRequestEvent.lua(63) : attempt to index field 'object' (a number value)

do you play in MP ?

**Comment by STW0701** [comment]
I play SP

**Comment by Tensuko** [comment]
it saved just fine for me.
CP 02.00040 AD 1.1.0.5-RC5
