### ISSUE TITLE
AD setting for unload/refill missing

### ISSUE THREAD

**Issue by HawkPat** [Courseplay/courseplay#5431]
Hi,
in latest cp version I can't see the setting AD for unload/refill. It is clickable and working though, but not visible.

![cp_autodrive_fail](https://user-images.githubusercontent.com/52010642/82421007-bcaa7300-9a80-11ea-912c-4dd0fb8c6092.png)

**Comment by polosubtil** [comment]
Hi @HawkPat 
I think you will find it in the advanced settings, on the left column

**Comment by HawkPat** [comment]
I do. But my guess is, that it should still be visible there in the display, shouldn't it?
Like I said: it is still clickable, just not visible.

If it is not a fault but done on purpose: close this ticket please

**Comment by Tensuko** [comment]
It is moved to adv settings.
