### ISSUE TITLE
paths

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#5432]
I would like to pose a problem (I don't know if it has already been pointed out): during the planning of the working paths in the field for some tools (such as the side mower) to respect reality the tractor should always work rotating around the field, in order to Do not step on the grass. When I program the route, I therefore set the maximum number of possible warheads (50) so that the CP then readjusts them according to the size of the field, only that a central part always remains "forward and backward". I wanted to ask if it was possible to have a way to plan a route completely "around" the field, from the outside to the innermost point

**Comment by 0Pietro20** [comment]
I also noticed that sometimes, as in these photos, it creates many maneuvers (driving the tractor crazy) while it would be MUCH more comfortable to simply perform a straight path

![Farming Simulator 19 20_05_2020 13_02_10](https://user-images.githubusercontent.com/59969508/82439085-62b6a700-9a9a-11ea-8ff0-b6d1db4ac8b9.png)

**Comment by Tensuko** [comment]
Did you try the 3rd option ? Not sure what it is in english, not racetrack but spiral ?

**Comment by 0Pietro20** [comment]
I had tried but without success. I'll run another test and show the results

**Comment by 0Pietro20** [comment]
I tried again and it worked properly, thanks
