### ISSUE TITLE
Using Hardi sprayer /specializations/Attachable.lua(1302)

### ISSUE THREAD

**Issue by Miketeg** [Courseplay/courseplay#5433]
Playing on Nebraska Lands
Using Hardi sprayer (Giants)
Create a course = OK
Start drive = OK
As soon as it reach the startpoint, got these error and had to CTRL+F4 to quit the game.:

2020-05-20 10:56 CourseGeneratorScreen:onCreate()
2020-05-20 10:57 Error: Running LUA method 'update'.
2020-05-20 10:57 dataS/scripts/vehicles/specializations/Attachable.lua(1302) : attempt to index field 'attacherVehicle' (a nil value)

I have many mods installed, I have tried the same on Ravenport without any mod and same issue.

I have attached my log, look at line 10279
[log.txt](https://github.com/Courseplay/courseplay/files/4657624/log.txt)

It was working fine with version before 6.02

Let me know if you need more info / debug.

**Comment by Tensuko** [comment]
Tons of Mods and this Error is from GIANTS Code, not CP Code.
And can't reproduce, I say it is a mod Conflict you have somewhere.
![fsScreen_2020_05_20_18_37_34](https://user-images.githubusercontent.com/27344744/82472981-36664f00-9ac9-11ea-9163-dab369c635ca.png)
