### ISSUE TITLE
Tractor uses a path to turn that collides with outer objects of the field.

### ISSUE THREAD

**Issue by tirrera921** [Courseplay/courseplay#5434]
I'm not sure if this has been reported already but the course creates a large "figure eight" to turn for a 90 degree turn which usually puts the tractor in the path of objects on the outside of the field. Sometimes it uses a "3 point turn" which is much better as it keeps on the field and does not collide with anything. Of course, it only uses this turn sometimes and will change up throughout the course. I have noticed that the version 06_01_395 does not create the large "figure eight" and turns correctly each time. I've noticed it mainly with towed implements, (seeders, cultivators, etc.).  The issue has been across many maps and with mods enabled or disabled, other than the ones being actually used. I've also tried enabling and disabling various options with no change. Such as pathfinding, use AI turns, and allow pathfinding during reversing. I have included pictures showing the debug course and my log from that savegame.

![fsScreen_2020_05_20_10_06_12](https://user-images.githubusercontent.com/25624036/82468783-364a5d00-9a91-11ea-8dc3-f50ab7060052.png)
![fsScreen_2020_05_20_10_07_35](https://user-images.githubusercontent.com/25624036/82468793-39dde400-9a91-11ea-901e-37b03749cdf6.png)

![fsScreen_2020_05_20_09_51_28](https://user-images.githubusercontent.com/25624036/82468750-2e8ab880-9a91-11ea-9c10-7f7c18250211.png)

![fsScreen_2020_05_20_09_50_19](https://user-images.githubusercontent.com/25624036/82468688-1c107f00-9a91-11ea-8bef-a772068c76a7.png)
![fsScreen_2020_05_20_09_51_17](https://user-images.githubusercontent.com/25624036/82468711-23d02380-9a91-11ea-9e52-fdfd9c0270fc.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4657953/log.txt)

**Comment by Tensuko** [comment]
What do you expect with such big towed tools ?

**Comment by tirrera921** [comment]
It actually worked just fine with the same large tools with version 01_395. It would use the "3-point" style turn each time which is perfect for crowded fields. Of course I've also had it happen with the in-game larger seeders as well but it's more random, this particular seeder it's more consistent to replicate the issue. Not sure why it changes up and does both styles at random though.

**Comment by pvaiko** [comment]
Should work fine with 6.2.14. If it does not make sure you have a log with 14 and 12.

**Comment by tirrera921** [comment]
Ok, will do, thanks!

**Comment by tirrera921** [comment]
Update: I was able to test the newest version using the same scenario as
before and it worked perfectly. I tried every single 90 degree turn and all
of them used the correct turn style. Thanks again!
