### ISSUE TITLE
Is the module available in modhub?

### ISSUE THREAD

**Issue by filosganga** [Courseplay/courseplay#5436]
Hello,
Thank you for this awesome module, I really love it.

I am not sure this is the right place for asking questions. Am I right to assume this mod is not yet available in FS19 modhub?

If so, is there any plan to make it available? Or do you need help to make it happen?

Fs19 is now available via Nvidia GeForce now, but it is only possible to use mods from modhub.

Thank you for your time.

**Comment by Tensuko** [comment]
Wont happen.
You got no access to savegame folder and such ?

**Comment by filosganga** [comment]
Has it happened in the end?

https://www.farming-simulator.com/mod.php?lang=en&country=it&mod_id=209361&title=fs2019
