### ISSUE TITLE
SelectedCombineToUnloadSetting:init()

### ISSUE THREAD

**Issue by DrunkKiddo** [Courseplay/courseplay#5437]
Hello! I am having this "SelectedCombineToUnloadSetting:init()" thing spamming my log. No other mods. Only latest version of CP. This error happens when i am inside the shop menu, customizing any vehicle.

[log.txt](https://github.com/Courseplay/courseplay/files/4662287/log.txt)

**Comment by Tensuko** [comment]
Not an Error.
