### ISSUE TITLE
Schaufel wird nicht voll

### ISSUE THREAD

**Issue by xerion8300** [Courseplay/courseplay#5438]
Meine Schaufeln werden nur bis 98% befüllt.Das Problem wo dabei ist, ist das der Abfahrer dann durchs ganze Silo fährt und dann wieder zurück.
Ich weis nicht ob es ein Problem vom CP ist.
Vielleicht könnte man das einstellen das er auch schon bei 98 % Füllung das OK gibt und nicht erst bei 100%.

**Comment by polosubtil** [comment]
I think right now CP consider it full at 99 %

**Comment by TinyCrocodile** [comment]
Kannst du bitte ein screenshot machen, wo man die situation sieht inklusive sichtbarer Kurs. (3 punkte aktiv)

**Comment by xerion8300** [comment]
So habe ein Video gemacht und die Log hänge ich auch mit dran.
[log.txt](https://github.com/Courseplay/courseplay/files/4666781/log.txt)
![fsScreen_2020_05_22_09_48_07](https://user-images.githubusercontent.com/25564472/82645227-d8458300-9c12-11ea-9ed7-1fabb5212dd5.png)

https://youtu.be/LyBpWl0d7D4

**Comment by polosubtil** [comment]
Can you try with this version set at 0,98 %
[FS19_Courseplay.zip](https://github.com/Courseplay/courseplay/files/4667904/FS19_Courseplay.zip)
Are you using a shovel from the original game or a mode ?
It would be good to do a test with the normal courseplay and another equipment (telehandler + shovel for example)

**Comment by xerion8300** [comment]
Ich bekomme jetzt einen Lua Fehler, und ich kann die Schaufeleinstellungen nicht mehr öffnen
[log.txt](https://github.com/Courseplay/courseplay/files/4669007/log.txt)
Und beim wiederstarten bleibt das Spiel an dieser Position hängen.
[log.txt](https://github.com/Courseplay/courseplay/files/4669045/log.txt)
Ich hatte schon mehre Schaufeln und verschiedene Maps aber alle waren bei 98%

**Comment by polosubtil** [comment]
Ok, another attempt. This is just to confirm it can work
[FS19_Courseplay.zip](https://github.com/Courseplay/courseplay/files/4669172/FS19_Courseplay.zip)

**Comment by xerion8300** [comment]
So ich glaube ich habe die Lösung.
Habe in der ShovelModeAIDriver.lua in der Zeile 314 den W verändert. Seit dem werden alle schaufeln beladen und der CP funktioniertet
`return self.vehicle.cp.shovel:getFillUnitFillLevel(1) >= self.vehicle.cp.shovel:getFillUnitCapacity(1)*0.97`

**Comment by xerion8300** [comment]
> 
> 
> Ok, another attempt. This is just to confirm it can work
> [FS19_Courseplay.zip](https://github.com/Courseplay/courseplay/files/4669172/FS19_Courseplay.zip)

So deine Datei getestet funktioniert ein wand frei.
Danke für die schnelle Hilfe.

**Comment by pvaiko** [comment]
So folks, posting a zip file is not a solution. Will someone create a pull request or what's going on here?

**Comment by polosubtil** [comment]
Hi @pvaiko 
Of course I will, I am away for a few days and can’t really test before doing a PR. And I also wanted to check with you if that was OK to change the full value to 98%, I didn’t want to mess with the code just like that

**Comment by TinyCrocodile** [comment]
Maybe we can figure out the reason why it is not filling to full and fix that instead. We can still set it to 98 if we dont succeed.

What i am interested in is:
1. Is the shovel getting full if you stop him  and let him do a 2nd approach with almost full shovel?
2. What was the speed setting. Is he bumping over the pile bevore getting full. Try reducing the onfield speed to maybe super slow 5 kmh

**Comment by xerion8300** [comment]
Hallo TinyCrocodile
Punkt 1 habe ich ein paar mal gemacht, aber er füllt die Schaufel nicht weiter
Punkt 2 auf 5km/h gesengt geht auch nicht. siehe Video
https://youtu.be/IGBB2q3yBoo

**Comment by polosubtil** [comment]
Hallo @xerion8300 
Can you try in manual ? No CP !!!
I did a pull request to set the full value at 98 % in case we don't find a better solution

**Comment by xerion8300** [comment]
So habe jetzt manuell die Schaufel am Traktor beladen und jedes mal bei 98 Prozent stehengeblieben. Habe es an verschiedenen Silos ausprobiert, Standard und Mode. 
Ich habe nur eine Schaufel für einen Radlader und da sind es 100 Prozent im manuellen und auch mit CP.
Sollte ich Bilder anhängen sagt Bescheid.

**Comment by polosubtil** [comment]
Ok, so I suppose it's a question for Giant, not related to CP.
Let's set it at 98%, I am pretty sure it gets to 100% anyway if it can so it won't make a huge difference.
