### ISSUE TITLE
Ver015 mode 2

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#5440]

**Comment by kwguk** [comment]
So ive been giving it a go with mixed results.
It works ok if the combine is moving but as the tractor cant unload in the crop there are quite a few occassions when the combine has to stop to be emptied. this is what im 
finding is happening

![fsScreen_2020_05_21_21_56_07](https://user-images.githubusercontent.com/11178621/82605932-4a37b100-9bae-11ea-8e2d-924fd17f01f9.png)

[log.txt](https://github.com/Courseplay/courseplay/files/4664731/log.txt)

**Comment by NKESSEL560** [comment]
I have also noticed the same thing anytime the combine is stopped the unloader runs right into the back of the combine.  And if it doesn't it turns way to close in and still gets stuck.  I believe the option on the turn circle of the unloader helped in fs17 if i remember correctly.  Also the unloader does not respond much to the manual horiz distance to stay away from the combine very much.  It does make a difference but does not seem to respond to moving say 9m to 10m.

**Comment by pvaiko** [comment]
See #5272 on how to report a problem for Mode 2.

**Comment by pvaiko** [comment]
@kwguk you have a manual offset. Why? Reset it back to auto offset and it'll work.

**Comment by NKESSEL560** [comment]
Always set a pipe default offset, even for harvester with
no pipe, like a cotton harvester.

I think people are just misunderstanding what this meant.  As did I.

**Comment by Tensuko** [comment]
So you guys read commit messages that is meant for what has changed in the code and why, but don't read stickys.
This is just unbelivable...
Again: that was just for code part...
In #5272 is nothing written about set an offset.
All you did now is reverse the calculated offset position of the pipe, ofc this won't work....

**Comment by kwguk** [comment]
Calm down Tensunko, we're not all tech gurus.  Like most i massively appreciate the work you guys do but have no understanding how it actually works. I merely download it and use it.

So the answwr is set my offset back to 'Auto' and the problem is solved

**Comment by pvaiko** [comment]
@kwguk have you tried, is this working ok now?

**Comment by kwguk** [comment]
> @kwguk have you tried, is this working ok now?

Yes Pvaiko, its working well!
Couple of minor gripes, the flashers are on all the time and occassionally the tractor and combine dont communicate. i have to take the tractor closer to the combine for it to 'connect'
But bar that all good so far.
Topjob!

**Comment by NKESSEL560** [comment]
I'm not having such luck.... mine went from crashing into each other or getting stuck 1/3 of the time to maybe 1/5 of the time switching it to auto.

**Comment by kwguk** [comment]
What would be useful as you cant unload with the 'pipe in fruit' would be the ability to call a tractor when you want and for the combine to stop at the end of the row if its unloading,

Also for the mini-hud to show what stage the tractor is at. ie 'waiting for fill level to be reached'

**Comment by kwguk** [comment]
Without starting a new issue can i ask for some advice......

Obviously with the combine only unloading with the pipe not in fruit whats the best track to keep the pipe out of fruit the majoirty of the time?
is it best just to keep going round and round or use spiral or racetrack?

**Comment by pvaiko** [comment]
@kwguk what do you mean by 'combine only unloading with the pipe not in fruit'? When it is full with the pipe in fruit it'll move back and out so the unloader can get under the pipe without driving through the fruit.

**Comment by kwguk** [comment]
Yeah i appreciate mate that but on our farm we always have the combine cut in what we call 'lands' so the pipe is always on the left out of the cropso its constantly moving. Youd be amazed just how much time you stopping to back up over harvest period!

Obviously to do this in game with CP you could just go continuosly round the headland. 'Lands' are basically strips that the combine cuts  so its pipe is always on the left. When its completed one it cuts out another strip and so on until the field is done. Not  avery good expalanation but hopefully you get the jist.

**Comment by Tensuko** [comment]
This is a complete other Problem and got nothing to do with Mode2, but with Course Generator Patterns.
Not sure but I think we already got an 'Issue' about this.

**Comment by pvaiko** [comment]
@kwguk yes, I know, it is on the top of my list to implement that, we already do lands with the racetrack pattern, so it really wouldn't be a big deal to add that.

**Comment by pvaiko** [comment]
So original issue seems to be solved, there's another one for the lands with pipe out, I close this, if anyone has any issues with mode 2 open a new one but read #5272 before!

**Comment by pvaiko** [comment]
@kwguk 

> we always have the combine cut in what we call 'lands'

How would you call that new option in the course generator (we currently now up/down, racetrack, spiral)? Just 'Lands'?

**Comment by pvaiko** [comment]
@kwguk also, how many rows are in one of these lands?

**Comment by kwguk** [comment]
> @kwguk also, how many rows are in one of these lands?

It depends on the drivers choice. We use the John Deere Greenstar system, basically gps which works in a similar way CP in the game. But instead of cutting straight up and down the driver will go mybe a dozen or so rows down then 'strike out' so creating a block. He'll then com back up the other way with the pipe on the left all the time. He will continue to go theoretcially 'round and round' until the gap between is bigger than the block  is wide. He'll then switch to going 'round and round' the smaller block until its done. Once completed he'll move backto the remaining crop and strike out again. As its all done using GPS ypu never get any short work until you reach the farside.
Its not very well explained but hopefully you get the idea.
