### ISSUE TITLE
It says "drive to harvester" (translated from german), but it doesn´t drive

### ISSUE THREAD

**Issue by therealmistericraft** [Courseplay/courseplay#5442]
Hey there, i´m using the combi mode to unload the harvester and when it´s on the start point, it says "driving to the harvester" (i´m german so I have only translated it to english), but it won´t start driving. One time, it started driving, but said behind the harvester "6250R is stuck in traffic". I´m using the newest version, but in multiplayer. Before the update it worked.

**Comment by Tensuko** [comment]
#5272
