### ISSUE TITLE
Bug mit Überladewagen

### ISSUE THREAD

**Issue by Bikeslife** [Courseplay/courseplay#5443]
Wenn ich den Überladewagen einsetze um damit einen LKW zu befüllen, dann klappt dies nicht. Er tankt zwar den Drescher ab und fährt zum LKW, dort bleibt er aber nicht am Wartepunkt stehen. Anders funktioniert es soweit ich weiß ja auch nicht. Also kann man im Moment nicht mit einem Überladewagen arbeiten... Ich habe die neuste Release Version von Courseplay

**Comment by Tensuko** [comment]
Weil ÜLW noch nicht unterstützt sind und Mode3 noch nicht aktiv....
