### ISSUE TITLE
Combine wont call unloader when full

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#5446]
It seems like im always complaining!

ver016. Ive got two combines in two sepearte fields niether of whom will call for an unloader when full.
![fsScreen_2020_05_23_14_26_33](https://user-images.githubusercontent.com/11178621/82731947-06ee5700-9d02-11ea-83c5-6e14449b77f2.png)
![fsScreen_2020_05_23_14_26_38](https://user-images.githubusercontent.com/11178621/82731959-1372af80-9d02-11ea-8f2c-200854608704.png)
![fsScreen_2020_05_23_14_26_53](https://user-images.githubusercontent.com/11178621/82731966-1f5e7180-9d02-11ea-9aa6-9c502c653170.png)
![fsScreen_2020_05_23_14_27_07](https://user-images.githubusercontent.com/11178621/82731974-2be2ca00-9d02-11ea-81a1-a4aca431af62.png)

Ive tried running the tractors round the courses and ive tried callind for the tractors manually rom the combine. The tracroes appear to be waiting for the combine to call it over.
[log.txt](https://github.com/Courseplay/courseplay/files/4671836/log.txt)

**Comment by pvaiko** [comment]
As we told so many times, multiple unloaders aren't supported yet. Also, change the unloader priority to distance and it'll work.

**Comment by Goof245** [comment]
Did you select a combine?
![image](https://user-images.githubusercontent.com/3851003/82732436-84d94f00-9d50-11ea-877e-2725e92e4d77.png)

**Comment by kwguk** [comment]
Yes mate i did

I assumed incorrectly that 'multiple loaders' referred to them in the same field. Mine are in two sepearte fields. Having changed from 'fill level' to 'distance' its all working pretty well.
