### ISSUE TITLE
Request: Start course at Previous Waypoint 

### ISSUE THREAD

**Issue by enderwiggin07** [Courseplay/courseplay#5448]
Pretty frequently there's situations where I don't want to use an refill course on Mode 4 because maybe there are pallets on a truck that moves around or my farm has bad layout or the tool is too weird to let courseplay refill it, whatever reason.  

It'd be cool in that situation if I hit "stop driver" and it takes note of where in the course it stopped, so that after filling the tool and getting back on the field, I can just tell the driver to go back to work and he resumes as he would if he had run a CP refill course.

Thanks for all your efforts, CP is why the game is playable.

**Comment by Tensuko** [comment]
I think the problem is not previous Waypoint, but Waypoint on Workcourse.
Basically it should be saved, but something seems to be wrong on that sometimes (somewhere is an Issue about that).

**Comment by enderwiggin07** [comment]
To be clear, I'm not reporting a problem with the worker resuming the course if he does the refill course, just requesting if it would be possible to have the worker automatically resume if I manually stop and refill myself.

**Comment by Tensuko** [comment]
So without refill course ?
Start at current waypoint ?

**Comment by enderwiggin07** [comment]
I didn't realize that does that, I thought it was a somehow different version of "next closest waypoint".  How perfect that the feature I want already exists.  Thanks!!
