### ISSUE TITLE
Combine unload issue

### ISSUE THREAD

**Issue by Scania1983** [Courseplay/courseplay#5449]
When full tractor drives to combine, when almost in line its stops. Then it is making circles 3 times and stops. It won't go under the pipe. And i believe the combine should make room for the unloader to unload outside the crop?

[log.txt](https://github.com/Courseplay/courseplay/files/4672167/log.txt)

![fsScreen_2020_05_23_18_59_21](https://user-images.githubusercontent.com/65482225/82736332-39f81100-9d29-11ea-8cb2-4822803a5689.jpg)

**Comment by Tensuko** [comment]
Pathfinder on or off on Combine ? (HUD)

**Comment by Scania1983** [comment]
In advanced settings both are off

**Comment by pvaiko** [comment]
Not in the advanced settings, in the HUD.

**Comment by Scania1983** [comment]
I don’t know what u mean, it is driving a cp course

**Comment by Tensuko** [comment]
> 
> 
> Pathfinder on or off on Combine ? (HUD)

v

> 
> 
> In advanced settings both are off
> 
> If on nothing happens

v

> 
> 
> Not in the advanced settings, in the HUD.

???

**Comment by Scania1983** [comment]
Where to look in the hud

**Comment by pvaiko** [comment]
![image](https://user-images.githubusercontent.com/2379521/82744021-c0681f00-9d38-11ea-9c7f-906d92c039b1.png)

**Comment by Scania1983** [comment]
It was off, now it’s on and it works perfectly, thx for the help 👍🏻

**Comment by blue-painted** [comment]
But why would you ever drive a combine wrong-side relative to the crop?

**Comment by Scania1983** [comment]
> But why would you ever drive a combine wrong-side relative to the crop?

It is driving up and down, so every 2nd turn the pipe is in the crop, now it pulls back to give the unloader space to unload
