### ISSUE TITLE
Headland overlap

### ISSUE THREAD

**Issue by markus372** [Courseplay/courseplay#5450]
Hi

First of all, thanks for this amazing tool.
Now to my question: Would it be possible to make the headland overlap a value that is modifiable? This would solve the issue when in too tight corners with smooth corners selected the implement would not reach a tiny bit. 
IMO it is better to have some parts worked twice/ unnecessarily instead of having to go over these parts manually. 

Here is a picture of the situation
![Github_Issue_01](https://user-images.githubusercontent.com/65828332/82738652-85b2b680-9d39-11ea-92db-4293f89e7101.PNG)

Best regards

**Comment by Tensuko** [comment]
How about change the corners to sharp and not round ?

**Comment by pvaiko** [comment]
@Tensuko means use turns on the headlands or the round setting instead of smooth.

And yes, we can add the overlap (it is currently set to a fix 7% I believe, but that's not how real life agriculture works, I added a few screenshots from agricultural books and papers to illustrate the point, the last one is really interesting showing how they make another pass on those crescents once done with the rest of the field.

![image](https://user-images.githubusercontent.com/2379521/82740001-4e78e100-9d0a-11ea-9e21-981a5a724312.png)

![image](https://user-images.githubusercontent.com/2379521/82740026-7ec07f80-9d0a-11ea-9cc8-7541b062c5f2.png)

![image](https://user-images.githubusercontent.com/2379521/82740032-90098c00-9d0a-11ea-9717-2d8993e7d024.png)

**Comment by polosubtil** [comment]
@pvaiko is correct, but that is a really north american way of working. Never seen that in Europe ;)
In Europe, farmers would do a maneuver on the corners to work straight. We tend to avoid working in sharp curves as the equipment (especially large ones) isn't usually able to compensate for drilling / spreading / spraying.
If I had to work loike that IRL on my farm, I would drive out of the path on curves so the center of the equipment is following the path. But that's not really siomething easy to do as it depends on the equipment (length, pivot point, etc.)

**Comment by pvaiko** [comment]
@polosubtil thanks, I love feedback from people who actually work with these machines, I'd like to make CP as realistic as possible. 

> I would drive out of the path on curves so the center of the equipment is following the path

CP has code for that (tight turns), using the tow bar length, it is now used on the headland turns, and we could add it to the smooth corners too, but it won't help with a combine.

So how it is done in Europe with a combine?

**Comment by polosubtil** [comment]
@pvaiko 
No problem, I grew up on a farm and work in farm machinery for years now, so really happy to help.
That really depends on the situation but I read your last modification on the Mode2 branch and I think you are getting pretty close :
- On a straight field (as we have in my farm usually), we would do the headland x2 or x3 on each side (narrow side) as we have with the "COURSEPLAY_HEADLAND_MODE_TWO_SIDE". And then do a racetrack from the inside so we clear the field living the trailers in the center. We might do that up to 10/12 rows and start a new one if the field is wide.
- On a classic field (not straight, with hedges around like in the UK), it would be the same except the headland would be all around
- Some people don't want to drive the trailers inside the fields to avoid compacting the soils. In that case they leave the trailer on the edge of the field, along the road and empty the combine without moving (same as the CP option : "COURSEPLAY_SELF_UNLOAD_TOOLTIP" except they try to unload the combine when they are close to the trailer and almost full, when they finish a row). Usually doing a few headlands all around or just on both sides and then Up and Down rows.

To be fair, they are so many ways of working a field all around the world, CP has to be a compromise. I am travelling a lot for work and I am always amazed to see all this diversity :) In Australia for example, in some regions, they do what we can see in the first picture of that issue on purpose to leave some food for the sheep, which is crazy for a European farmer :)

**Comment by revrr** [comment]
IRL some seeders (e.g. bourgault) have sectional control, which resolves the problem of overlapping

**Comment by markus372** [comment]
> How about change the corners to sharp and not round ?

I just tried that, but if the field has rounded corners this has no effect on the course created. 
![Github_Issue_02](https://user-images.githubusercontent.com/65828332/82745729-ed8fee00-9d87-11ea-8c02-e0bc9470d359.PNG)

**Comment by polosubtil** [comment]
@markus372 
What I would do but it's a long job, is to move manually the point of the course outside the curve, so your tractor will do a larger turn and will probably help finishing correctly the corners.
Just use the CP modifier (left CRT + E)

**Comment by pvaiko** [comment]
> to move manually the point of the course outside the curve

CP can do that, let me check if it is being used in this case.

**Comment by pvaiko** [comment]
@markus372 if you turn on debug channel 14 you should be able to see the 'tight turn offset' entries telling what offset CP is applying for a curve.

**Comment by Tensuko** [comment]
Option added to coursgenerator.
