### ISSUE TITLE
Turning radius and roaming

### ISSUE THREAD

**Issue by wertigoxxx** [Courseplay/courseplay#5452]
**Hallo!**

I came again with a couple of mistakes.
I have found that the vehicle regularly deviates from the ground.
AIDrive is turned on, but it has to roam. :)

The turning radius should be improved because there are times when you turn between the trees and the trailer or the assembly stops!

I attached some pictures. Debug run!

**All due respect to you, you have done a great job! Thank you!**

Here the tractor goes like a drunk!
it can be refined on it so that it does not follow the line of the crop or the edge of the earth so densely!
![fsScreen_2020_05_10_16_32_02](https://user-images.githubusercontent.com/65092037/82746674-bd9a1800-9d92-11ea-9e76-84a400b5623e.png)
![fsScreen_2020_05_23_11_00_51](https://user-images.githubusercontent.com/65092037/82746679-c2f76280-9d92-11ea-850f-5db34bc884c0.png)
![fsScreen_2020_05_24_06_28_49](https://user-images.githubusercontent.com/65092037/82746681-c68ae980-9d92-11ea-939e-35a65c17d913.png)

**when you go to the combine to try to go back together, would that be normal?**
![fsScreen_2020_05_24_08_44_15](https://user-images.githubusercontent.com/65092037/82747753-a52efb00-9d9c-11ea-87ce-d32fbbf4fdf4.png)
![fsScreen_2020_05_24_08_44_22](https://user-images.githubusercontent.com/65092037/82747757-aa8c4580-9d9c-11ea-9384-76c6b68fcb15.png)
![fsScreen_2020_05_24_08_48_50](https://user-images.githubusercontent.com/65092037/82747761-af50f980-9d9c-11ea-9149-6a6720b6e498.png)

### the combine with the new design mode, goes through everything, goes out of the fields!
![fsScreen_2020_05_24_08_45_45](https://user-images.githubusercontent.com/65092037/82747768-bd067f00-9d9c-11ea-8859-96eae113fa9a.png)

**In this image, while emptying the combine, it dropped to around FPS 20 and the LUA froze!**
![fsScreen_2020_05_24_07_46_09](https://user-images.githubusercontent.com/65092037/82746684-cab70700-9d92-11ea-9223-a0d5d3ad2462.png)

LOG:
[log.txt](https://github.com/Courseplay/courseplay/files/4673054/log.txt)

**Comment by Tensuko** [comment]
And where is the logfile ? .......

**Comment by wertigoxxx** [comment]
updated!!!

**Comment by pvaiko** [comment]
Won't do anything with the drunk driving for now, that's a pathfinder fine tuning. Same for driving big trailers/rigs through the woods.

Since you did not follow the instructions in #5272 I have no idea what happened to the combine, that would be interesting to know.

The last one is most likely a problem with that trailer, guess it is a mod.

**Comment by Tensuko** [comment]
Old Issue, old Version.
If still have a Problem with Combine that is not already mentioned in any Issue, make a new one and stick to the insturctions in #5272
