### ISSUE TITLE
neuste CP version und Autodrive

### ISSUE THREAD

**Issue by Juergen11668** [Courseplay/courseplay#5453]
Hallo, habe mir die neue cp Version 6.02.00017 runtergeladen.

Meine Frage: Kann ich mit dieser Version nicht Autodrive aktivieren? 
habe ales im Forum gesucht und nichts gefunden.

Für einen Tipp wäre ich dankbar.

**Comment by 60erjonny** [comment]
Hallo @Juergen11668 
Das wurde vor einigen Versionen in -->Allgemeine Einstellungen -->Erweiterte Einstellungen...verschoben...
