### ISSUE TITLE
Harvester calling tractor MODE 2

### ISSUE THREAD

**Issue by Beebtrek** [Courseplay/courseplay#5455]
Hi, have not seen this in the queries yet so maybe an issue not reported.

Two Harvesters running on two separate fields.
With Two separate unloading tractors.
Harvesters are new holland CR10.90
Tractor is the Fendt 1050
Trailer is the 3401

Harvester one on a full tank calls tractor one no problem.

But Harvester Two just sits and waits till I manually request it from the CP Harvester menu. i.e. Request Driver.

**Comment by Tensuko** [comment]
#5272
