### ISSUE TITLE
Course set up for side spreader (manure) 

### ISSUE THREAD

**Issue by redrummed1** [Courseplay/courseplay#5456]
Hi, a question more than an issue, how would I set up a side spreader on a fieldwork course when it only discharges out the side instead of the back. Please see pic attached of mod I use. I think it's 8m wide spread. 
![Screenshot_20200524_111251_com facebook katana](https://user-images.githubusercontent.com/23707135/82751578-11ffc080-9db0-11ea-9052-c9cc7f328d08.jpg)

**Comment by TinyCrocodile** [comment]
Try generating a 8m course and then use a tool offset of 4m.

**Comment by redrummed1** [comment]
No success, Its a 4M spreader, i set up a 4m course with a 2m offset to the left , when the tractor turns at the end it just sprays the piece its already done.
![fsScreen_2020_05_26_12_49_41](https://user-images.githubusercontent.com/23707135/82897655-da2f7f00-9f4f-11ea-86e7-0ba88ad12332.png)
![fsScreen_2020_05_26_12_49_45](https://user-images.githubusercontent.com/23707135/82897715-f4695d00-9f4f-11ea-9823-5775a5386167.png)
![fsScreen_2020_05_26_12_50_04](https://user-images.githubusercontent.com/23707135/82897770-0e0aa480-9f50-11ea-9e15-4b13e519a8c4.png)

**Comment by TinyCrocodile** [comment]
I tested with that exact tool. Got it working with 4m course and 3.5 m tool offset. The work with does not start in the middle so the offset must be bigger. You may need to fine tune this even more for best results.

**Comment by Tensuko** [comment]
So when @TinyCrocodile can get it to work with offset its fine. I also don't see a reason why it should not work as wer have more tools with offset running.
