### ISSUE TITLE
truck or tractor, the trailer don't fill up.

### ISSUE THREAD

**Issue by candymant** [Courseplay/courseplay#5457]
I must be in the truck or tractor before it loads the selected fruit for transport mode1.
this can not be the meaning. global company triggers work. normal triggers not.

**Comment by Tensuko** [comment]
1st of all, you didn't attached a logfile.
2nd, this is working like it should unless you got the manuresystem Version 1.0.0.0 in your mods folder wich I am very sure you got. (Update is on GitHub).

**Comment by candymant** [comment]
yes this is the problem
