### ISSUE TITLE
Manual Work Width Increment

### ISSUE THREAD

**Issue by enderwiggin07** [Courseplay/courseplay#5458]
I found https://github.com/Courseplay/courseplay/issues/1953 but this solution doesn't seem to be active in current version.  I am trying to set some balers to have a work width equal to windrowers so that they correctly follow a 3 tool saved course.  Over 10m increment is 1m and rounded to full meters.  Is there a better way to do this?  Otherwise it would be nice to be able to just set them to the same width as the windrower, right now they're trying to set left & right based on their own small work width.  Thanks

**Comment by polosubtil** [comment]
Can't you use the same Course than the windrowers ? If you saved it. The width should be set correctly if you have the correct equipment attached to your tractor

**Comment by enderwiggin07** [comment]
As far as I can tell, it doesn't work that way.  I saved the windrower course with 3 tools @ 14.8m each.  So they ran left, center, right.    Now with the balers, of course the center follows the line correctly but the left and right only want to offset based on their own work width which is like 3.8m or something.  I know I can do something with the horizontal offsets to make it work but I thought the simplest way would be to just tell courseplay that the balers are the same width as the windrower and they should perfectly follow the same course.

**Comment by Tensuko** [comment]
But you got a course with 3 Tools (multotool) for the windrowers, right ?
Why not load the same course and place the Balers on mid/left/right ?
That actually have to work.

**Comment by Tensuko** [comment]
Alright, I see whats going on.... this wasn't any case so far.

**Comment by enderwiggin07** [comment]
Do you think it would ever be possible for "multiple tools" to be generating separate courses for each tool?  Like using the "skip row" ability but each tool would only take its own row and never go back to do the skipped rows.   It would solve this particular problem but another advantage I can think of is when you have your "narrow row" left over at the end of a field, only one tool would have to do it.  Right now if you have 1m of fruit at the end of the field, it has to send all the tools and most of them are "working" but not in fruit.  If there's things on the field like bales or windrows it can make a real mess.

**Comment by Goof245** [comment]
Internally CP already kinda does that, you just don't get access to those offset courses that it generates. Separate courses would potentially also further complicate the already broken convoy mode.

If convoy can be solved though, this would be pretty handy though 🤔 To be able to actually *see* those courses like normal would make it easier to diagnose some issues like badly calculated turns etc.

**Comment by Tensuko** [comment]
Try to set the work width in the HUD to the same as the windrower and try again.

**Comment by Tensuko** [comment]
> 
> EDIT: for the narrow field ending, try opening the course with the editor and setting a pause point before the tools start that last row. This way at least you'll get a message the machines have stopped, and you can go and dismiss the ones that don't need to continue working.

Not a good Idea. It have to work with multitool course and convoy.

**Comment by enderwiggin07** [comment]
> 
> 
> Try to set the work width in the HUD to the same as the windrower and try again.

This is my original point of raising an issue, there doesn't seem to be a way to manually set "14.8m" manual work width since it goes up by full 1m at a time and even if you start on like "3.8", you can go up like 4.8, 5.8, 6.8 but once you cross 10m manual work width, it goes to 10.0, 11.0, etc.  

So if your windrower is 14.8m you can use 15m but the tool will always do a bad job being 20cm off

**Comment by enderwiggin07** [comment]
> 
> 
> Internally CP already kinda does that, you just don't get access to those offset courses that it generates. 

I don't really agree with you, I'm pretty sure courseplay generates a course using a width of "work width * number of tools" and then just gives you a nice way of quickly setting the offsets on some tools, like "2 left" is "left offset of 2*work width".   I'm pretty much 99% certain it's one very wide course the width of all your tools combined

**Comment by Goof245** [comment]
Check current waypoint on all tools after the headland; they'll differ between center and side tools since there's some waypoint revision going on to avoid problems around tight turns. This is the pause you feel when you hit "Drive course" on anything other than the center tool in a multi-tool convoy. 

What I don't know for sure is whether or not the whole course is re-calculated or if it's selective modification on only problem areas. In any case, getting less and less relevant to the issue at hand...

**Comment by Tensuko** [comment]
The Offset course gets calculated once you start the driver with left or right.

> This is my original point of raising an issue, there doesn't seem to be a way to manually set "14.8m" manual work width since it goes up by full 1m at a time and even if you start on like "3.8", you can go up like 4.8, 5.8, 6.8 but once you cross 10m manual work width, it goes to 10.0, 11.0, etc.
> 
> So if your windrower is 14.8m you can use 15m but the tool will always do a bad job being 20cm off

Exactly this would be the Information we would need on the 1st post.... there is nothing to discuss about its a clear Issue that we can try, reproduce and find the Problem in the Code....

**Comment by Tensuko** [comment]
hold left alt key and then scroll up, try it and report.

**Comment by enderwiggin07** [comment]
Even when holding Alt key + using mouse wheel, increment is 1m with rounding to x.0 meters after 10m

**Comment by pvaiko** [comment]
@enderwiggin07 FYI, the left/right courses in a multitool setting are fully recalculated when you start the vehicle, each vehicle has its own course. This is mainly due to the problems with the inner courses on headlands, there were quite a few issues about that, just search for multitool.

**Comment by pvaiko** [comment]
See also #5467

**Comment by Tensuko** [comment]
This seems to be the same Issue:  #5997

setting the correct working width is not fine enough on the HUD.
