### ISSUE TITLE
Harvester unloading to trailer, cannot unload too close to harvester

### ISSUE THREAD

**Issue by bildgesnipe** [Courseplay/courseplay#5459]
Mode 2
The harvester works normally, however the trailer to unload to is having problems. The trailer comes to the side of the harvester to unload, however upon getting close, the trailer finds a new path (makes a circle/stops). I believe this is due to the trailer about to collide with the harvester. Same results when side offset is set manually.

Specific harvester and trailer - Grimme Varitron 470 Terra-Trac and Fendt 724 Vario

Logs: https://pastebin.com/812DNuDr Debug 4 7 14
Screenshots:
![1](https://user-images.githubusercontent.com/65861511/82758456-3a6fd500-9e19-11ea-8c38-8e82cec7f6d7.png)
![2](https://user-images.githubusercontent.com/65861511/82758505-89b60580-9e19-11ea-846a-b35ee8aec397.png)
![3](https://user-images.githubusercontent.com/65861511/82758547-bff38500-9e19-11ea-9999-d4314dc4e844.png)
![2](https://user-images.githubusercontent.com/65861511/82758642-50ca6080-9e1a-11ea-8766-d4265fba9c48.png)

**Comment by bildgesnipe** [comment]
I tried testing the fix. The trailer now continues to try unloading, but cannot do so due to collision bumping into the harvester. 
![fsScreen_2020_05_25_02_40_10](https://user-images.githubusercontent.com/65861511/82762333-f5f13300-9e32-11ea-91fa-b892fd1a8f5e.png)

Sometimes also, the trailer just stands still at state: Waiting for Combine to Call
![fsScreen_2020_05_25_02_42_36](https://user-images.githubusercontent.com/65861511/82762431-892a6880-9e33-11ea-9fb9-344b61a4d508.png)

2nd log: https://pastebin.com/00h1yhAd
There seems to be an error at the end of the file

Thank you for looking into it!

**Comment by Tensuko** [comment]
The 1st Screenshot of 2nd Post can sure be fixed with the offset.

**Comment by moose31608** [comment]
When are you fixing the auger wagon to be able to run more then one combine? Also when combine call for auger wagon it doesn’t work

**Comment by Tensuko** [comment]
> 
> 
> When are you fixing the auger wagon to be able to run more then one combine? Also when combine call for auger wagon it doesn’t work

There is nothing to be fixed, it have to get added and it will be done with there is the time for it.
Also it does work...

**Comment by Tensuko** [comment]
@bildgesnipe try V00019

**Comment by bildgesnipe** [comment]
Offset works when combine is stopped to unload; however if a moving combine, trailer collides with truck - unable to unload. Offset doesn't seem to apply in moving combines?
![fsScreen_2020_05_25_13_21_27](https://user-images.githubusercontent.com/65861511/82780971-3ed4d600-9e8b-11ea-8e3b-42ca3daa8375.png)
![fsScreen_2020_05_25_13_23_44](https://user-images.githubusercontent.com/65861511/82781112-8c514300-9e8b-11ea-8429-894bb139a4f8.png)

Regarding "trailer just stands still at state: Waiting for Combine to Call", it looks like it's fixed. Haven't encountered it again, will observe some more. Thank you again.

**Comment by Tensuko** [comment]
> Offset works when combine is stopped to unload; however if a moving combine, trailer collides with truck - unable to unload. Offset doesn't seem to apply in moving combines?

Good point, haven't tested this in extreme situations, just -0.5m for Tiger 6 Sugarbeet Harvester but that one could also unload with no offset if both tools are straight and on same hight.

Going to check the V00019 later anyway, will test it.

**Comment by pvaiko** [comment]
6.2.20 should now fix all reported problems in this issue. Open a new one if not...

**Comment by bildgesnipe** [comment]
Working perfectly, thank you devs!
