### ISSUE TITLE
Fieldwork pattern: Lands - enhancement

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#5460]
First, thx a lot a lot for that tremendous idea with the "lands" patterns. I love it. Just have a little idea for ennhancement: it would be great if we could adjust the size of the "lands", e.g. start in the middle of the field and let it work all over from inside to outside without breaking it into several threads with (i guess 6 or 8?) rows. I know, on big fields the ways from one side to the other become very long... but it would help to let the unloader not drive into the fruit. I hope i could explain... english is not my native language

**Comment by pvaiko** [comment]
Size is now adjustable
