### ISSUE TITLE
Combine cant be reached by grain cart V.6.02 DEV 0.00000016

### ISSUE THREAD

**Issue by Thrasher4257** [Courseplay/courseplay#5461]
Hello,
I'm currently new to coursplay and don't have a lot of skills using it. I'm running into the issue of coursplay not being able to reach the combine or detect that the combine is actually there. I have my combi mode set for my grain cart and the path i want it to take the path to dump the grains in the semi trailer. Then return to the combine and then repeat the process. I have viewed countless videos and have searched for what seems to now be an eternity. i have found a couple of videos that seem to help a bit. The things i have tried is toggling the path finding on both combine and grain cart. I have tried toggling the channel 4 to on, that seem to worked a bit it did move the grain cart. But not in the direction that the combine is moving to follow behind. i have also tried to use hire worker for the combine, but no luck. If you could help me with this issue that would be great.
Thank you,

**Comment by Tensuko** [comment]
First you should read #5272

**Comment by Tensuko** [comment]
Also I have made a Video that might help you:
https://www.youtube.com/watch?v=PiUWD8ki8l4

**Comment by Tensuko** [comment]
Closed due to inactivity
