### ISSUE TITLE
Vehicle freezes and Game freezes after restart with CSZ Pack Pallet fork

### ISSUE THREAD

**Issue by spiessphilipp** [Courseplay/courseplay#5462]
I have an autoload pallet fork from the CSZ Pack attached at the Deutz DX 6.61 with the Trima Frontlader from the FBM Team. The pallet is the Pioneer seed pallet from the Modhub. Suddenly the DX freezed when i clicked to start the helper for a drive track. It doesn't started the course and the vehicle freezed. I saved and restarted. When I start the game now, the Hud with the clocktime etc is not loading and the camera moves itself to the sky. Can anybody help me? Theres a big error in the log.txt 
[log.txt](https://github.com/Courseplay/courseplay/files/4674255/log.txt)

**Comment by Sejer74** [comment]
I am having the same error.

**Comment by spiessphilipp** [comment]
with the new Release its works. Maybe an Release error.
