### ISSUE TITLE
Error: Running LUA method 'update' - CombineUnloadManager.lua:228: attempt to compare nil with number +Callstack (from log)

### ISSUE THREAD

**Issue by wertigoxxx** [Courseplay/courseplay#5463]
new version bugs:

**- The tractors do not answer the call!**
[log.txt](https://github.com/Courseplay/courseplay/files/4674278/log.txt)

![fsScreen_2020_05_24_11_06_27](https://user-images.githubusercontent.com/65092037/82763407-bb25d580-9e07-11ea-885a-153b128dcc58.png)
![fsScreen_2020_05_24_21_42_08](https://user-images.githubusercontent.com/65092037/82763411-bfea8980-9e07-11ea-8d84-bf845c635237.png)

**Comment by Tensuko** [comment]
Did you select the Combine in the Combine Manager ? (on Mode2 Driver)

**Comment by wertigoxxx** [comment]
what exactly do you mean?

**Comment by Tensuko** [comment]
https://www.youtube.com/watch?v=PiUWD8ki8l4

**Comment by Lustiger-Hubi** [comment]
Das Problem habe ich auch!
Das Video sagt wenig aus! Die Einstellungen habe ich auch gemacht!

020-05-31 17:15 CourseGeneratorScreen:onCreate()
2020-05-31 17:15 data/shared/ai/trafficCollision.i3d (1.09 ms)
2020-05-31 17:16 vehicle.cp.hud.combinesListMouseArea: table: 0x021a55505bc0
2020-05-31 17:17 vehicle.cp.hud.combinesListMouseArea: table: 0x021b2fdfa450
2020-05-31 17:18 Error: Running LUA method 'update'.
2020-05-31 17:18 F:/Landwirtschafts Simulator 2019 mods/mods/FS19_CoursePlay6/CombineUnloadManager.lua:343: attempt to index a nil value
2020-05-31 17:19 dataS2/character/humans/player/player02.i3d (227.85 ms)
2020-05-31 17:21 Game saved successfully.

**Comment by Tensuko** [comment]
Der teil von der log sagt wenig aus, komplette log mit dem fehler als log.txt anhängen.

**Comment by Lustiger-Hubi** [comment]
Hier die Log
[log.txt](https://github.com/Courseplay/courseplay/files/4707938/log.txt)

**Comment by pvaiko** [comment]
@Lustiger-Hubi meinst du es würde uns helfen wenn du sagst was du gerade gemacht hast als der Fehler kam?

**Comment by Tensuko** [comment]
Mal davon abgesehen das 'Error: Running LUA method 'update'' alles sein kann und es nur durch den Teil schwer zu sagen ist, ob es der gleich Fehler ist.
Im Fall von @Lustiger-Hubi 
2020-05-31 17:44 Error: Running LUA method 'mouseEvent'.
2020-05-31 17:44 F:/Landwirtschafts Simulator 2019 mods/mods/FS19_CoursePlay6/settings.lua:1802: table index is nil

Weiter oben haben wir hud.lua:610 und nen callstack.....

Ich würde sagen @Lustiger-Hubi bitte neues Issue mit log und Beschreibung was du gemacht hast als der Fehler auftrat, dieses Issue hier werde ich erst mal richtig benennen.

**Comment by Lustiger-Hubi** [comment]
Also ich habe die Log nochmals mit Notepad++ geprüft (suchlauf)
konnte weder ein  "hud.lua:610 und nen callstack....." finden!!
Bzw: wurde mir nicht angezeigt.

**Comment by Tensuko** [comment]
Bei dir nicht aber beim Issue ersteller und es hilft nichts alles was error running lua... Unter einem Issue zu packen! Das wäre sonst alles hier drin und nicht hilfreich!

**Comment by Lustiger-Hubi** [comment]
Sorry Sorry
Ich versuche mich zu bessern

**Comment by Tensuko** [comment]
> 
> 
> Sorry Sorry
> Ich versuche mich zu bessern

Keine Panik, musste nur gesagt werden :)

**Comment by Tensuko** [comment]
@wertigoxxx is this Error still happening or can we close this ?

**Comment by Tensuko** [comment]
Closed due to inactivity (and I think it is fixed)
