### ISSUE TITLE
Auger Wagon doesn't go to Combine

### ISSUE THREAD

**Issue by moose31608** [Courseplay/courseplay#5465]
[log.txt](https://github.com/Courseplay/courseplay/files/4674770/log.txt)
![fsScreen_2020_05_24_21_04_48](https://user-images.githubusercontent.com/53488388/82769666-8152d000-9e03-11ea-8061-deb7e7bafc7e.png)
![fsScreen_2020_05_24_21_07_06](https://user-images.githubusercontent.com/53488388/82769668-83b52a00-9e03-11ea-80b1-03c3550cee16.png)
![fsScreen_2020_05_24_21_07_13](https://user-images.githubusercontent.com/53488388/82769670-86b01a80-9e03-11ea-8844-d01015a4a466.png)
![fsScreen_2020_05_24_21_07_31](https://user-images.githubusercontent.com/53488388/82769672-8879de00-9e03-11ea-92a0-9f9b93a1d03e.png)
![fsScreen_2020_05_24_21_07_50](https://user-images.githubusercontent.com/53488388/82769674-8adc3800-9e03-11ea-95f4-feb9265040da.png)

**Comment by Tensuko** [comment]
I would say it was abosut to meet up with combine and combine reached turn so driver stopped.
Now pipe is in the fruit.
Combine is full ?
If not it should make the move out of fruit and driver should then drive to it.

**Comment by stangman04** [comment]
Having same issue with mine but with a semi trailer. The new mode 2 just doesn't work. The bottom of the courseplay GUI flashes "no combine in reach" constantly at a fast rate. But, in the logs it sees the combine and the fill level it appears...
[log.txt](https://github.com/Courseplay/courseplay/files/4720208/log.txt)

**Comment by Tensuko** [comment]
> The new mode 2 just doesn't work

It does..... Again, when it does not work on your side, there is a reason for it and then it is it doen't work in this situation but in general it DOES work, as I used and tested it 1000 times...

**Comment by Tensuko** [comment]
Check #5272 and https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ
closing this chaotic Issue. Please check if there is already a similar Issue and only post if you can provide screenshots and logfiles for the Problem.
