### ISSUE TITLE
Mode 1 Ignoring Stop at last point or next trigger?

### ISSUE THREAD

**Issue by bildgesnipe** [Courseplay/courseplay#5466]
Using mode 1 to transport grains, after reaching stop, continues to drive to start waypoint even if Stop at last point or next trigger is set to Activated.
![fsScreen_2020_05_25_13_53_21](https://user-images.githubusercontent.com/65861511/82782693-82314380-9e8f-11ea-88f4-395edc1d7df9.png)

After reaching stop, continues to drive to next waypoint.
![fsScreen_2020_05_25_13_53_23](https://user-images.githubusercontent.com/65861511/82782719-99703100-9e8f-11ea-8bcd-fcde88ddb740.png)
![fsScreen_2020_05_25_13_53_31](https://user-images.githubusercontent.com/65861511/82782722-9b39f480-9e8f-11ea-9afd-99f1f5efebfe.png)

I expected that the vehicle would stop at STOP waypoint when option Stop at last point or next trigger is set to Activated. This is intended behavior?

**Comment by Tensuko** [comment]
Not realy but the question is what you try to do here ?
If you want load at start and there is no trigger between stop and start he will wait at start point, but you should place the 1st waypoint after start a bit behind the start, couse of our PPC system.

**Comment by bildgesnipe** [comment]
I was trying to make it so that after unloading (at sell point), once it comes back, it comes to a full stop at the end.

**Comment by Tensuko** [comment]
This is not how mode1 works.
Place start after stop and 1st waypoint after stop with a bit distance (straight) and it will wait at 1st point automatically.
If you got a trigger there, set rounds from unlimited to one.

**Comment by Goof245** [comment]
Are mode1 drivers *supposed* to wait at the start waypoint if there are no fill triggers? Trying to receive grain on the edge of the field earlier and the tractor just kept driving off empty instead of waiting there until full.... 

'Refill Until:' setting was on 100%, just wondering if it's related to what's happening here.
