### ISSUE TITLE
Offsetcourse generation based on workwidth in HUD not working (takes tool width)

### ISSUE THREAD

**Issue by Goof245** [Courseplay/courseplay#5467]
Situation is I have a course set up for 3x18m tools, to be run by combines. This leaves three nice straw swaths, with no further need to windrow.

Problem comes when I load that course into a tractor with a baler attached. I set the baler's work width to 18m manually, set right or left hand lane and start worker. Worker generates an offset course then drives 3m to the right of the course line, not 18m.

[log.txt](https://github.com/Courseplay/courseplay/files/4677371/log.txt)

Generated course:
![20200525231859_1](https://user-images.githubusercontent.com/3851003/82816980-78373100-9edf-11ea-9dee-675df41d0aff.jpg)

Settings:
![20200525231953_1](https://user-images.githubusercontent.com/3851003/82817008-884f1080-9edf-11ea-9b80-53082916511d.jpg)
![20200525231951_1](https://user-images.githubusercontent.com/3851003/82817014-8c7b2e00-9edf-11ea-9fe3-45a06e6ed281.jpg)

Result:
![20200525231957_1](https://user-images.githubusercontent.com/3851003/82817151-d3692380-9edf-11ea-8ec9-0a96c7dc5f95.jpg)
![20200525232021_1](https://user-images.githubusercontent.com/3851003/82817161-d7954100-9edf-11ea-9425-b82e52c8ddd0.jpg)

l've also had situations where I've copied the course from the tractor running down the centre lane, set lane manually to 18m right/left, then the tractor instead drives directly down the course line without even generating the offset course...

**Comment by 0Pietro20** [comment]
I think that in order to do this job better, you should also use it to pack the path used by the threshing machine, so as to better follow the traces of the threshing machine and save time

**Comment by pvaiko** [comment]
@Goof245 come on, why don't you just fix it :)

**Comment by pvaiko** [comment]
https://github.com/Courseplay/courseplay/blob/462b127322af93428b7a047a8824d1c9219c55c1/FieldworkAIDriver.lua#L756

Just need to replace that getWorkWidth with something taking the HUD into account.

**Comment by Goof245** [comment]
Heh yeah I'll maybe have a better look tomorrow once I'm more awake 😅 Nice to know where to start looking though 👍

**Comment by dp-github** [comment]
Came here to report exactly this same issue.  **Lane width for the purpose of calculating multi-tool offset should be overridable.**

**Comment by Tensuko** [comment]
Should be 'fixed' in the next Version, as the work width would need to be adjusted to the width of the combine to hit the swath.

**Comment by Tensuko** [comment]
I am sure this was fixed already, closing, if still a problem.

Remember if you want to bale straw on harvester lane, you got to make the baler workwidth the same as the harvester in the HUD.
