### ISSUE TITLE
Problem mit Mode 2 bei manueller Bedienung Drecher/Heckseler

### ISSUE THREAD

**Issue by BALumpie** [Courseplay/courseplay#5468]
Hallo zusammen,

ich habe das folgende Problem:
Wenn ich mir zum Gras Häckseln 2 Abfahrer mit Kurse generiere und anschließend den Häcksler selbst fahren will, bleiben die Abfahrer einfach am Startpunkt stehen. Die Abfahrer erkennen, dass auf dem Feld ein Häcksler steht, fahren aber nicht hin. Der Abfahrer sucht ständig nach einem Drescher/ Häcksler.

Wenn ich aber nun den Häcksler via CP laufen lassen fahren sie auch los. Ist das so gewollt oder ist das ein Einstellungsfehler von mir? 

![20200525162424_1](https://user-images.githubusercontent.com/65908671/82822495-29b97080-9ea6-11ea-94f2-4f7b8777f8f3.jpg)

Grüße
BALumpie

**Comment by Tensuko** [comment]
#5272 lesen ftw
