### ISSUE TITLE
Course generation not possible Version 6.02.00019

### ISSUE THREAD

**Issue by 9NickName5** [Courseplay/courseplay#5471]
I can't choose my fields in the Coursegeneration for example for the harvester or the seeder. (Playing on a Dedicated Server)
Have someone a hint what could be the Problem?

**Comment by superforno** [comment]
Same here.
Dedicated server, cannot generate course. But I've noticed that:
when I accept a contract, I can generate relative field course and do everything normally. If I close game (server still running) and the come back in, I cannot regenerate the course on active contracts.

**Comment by Tensuko** [comment]
Collecting all in #5484
