### ISSUE TITLE
Strange maneuvers

### ISSUE THREAD

**Issue by Tocik** [Courseplay/courseplay#5473]
Strange maneuvers when unloading. The car drove up to the combine, reversed, and drove up to the pipe, but not close enough. I drew an approximate route as it went
![Задний ход](https://user-images.githubusercontent.com/65189100/82835199-00abd680-9ecc-11ea-9570-ae15803442df.jpg)
![Новый точечный рисунок](https://user-images.githubusercontent.com/65189100/82836050-7749d380-9ece-11ea-924f-4bd18fd54a92.jpg)

**Comment by Tensuko** [comment]
#5272
