### ISSUE TITLE
Mode 5: Make "Stop at Last Point" Default

### ISSUE THREAD

**Issue by enderwiggin07** [Courseplay/courseplay#5476]
At least the way I use it, I think it's almost universal to want to activate "Stop at last point" on a Mode 5 transfer course, and it's easy to forget to activate it right now which usually results in vehicles wandering away after the last point.  I think this setting should be on by default for Mode 5 or at least be "sticky" so it doesn't have to be reactivated every time a transfer course is loaded.  Thanks

**Comment by Tensuko** [comment]
Done
