### ISSUE TITLE
autoloaders

### ISSUE THREAD

**Issue by MarckAmorim** [Courseplay/courseplay#5477]
the autoloaders will never work either, is there a solution?

**Comment by enderwiggin07** [comment]
Are you talking about stock bale autoloaders or autoload script mods?  I've definitely used stock bale loaders with courseplay and had them work correctly.  What specific issue are you having?

**Comment by MarckAmorim** [comment]
![image](https://user-images.githubusercontent.com/60390452/82899928-210e7c00-9f32-11ea-83d3-a8e99ab98bb2.png)
that! in Brazil we call it bazookas

**Comment by Tensuko** [comment]
Thats an Overloader or auger wagon.... not an autoloader.....

Mode3 for those comes later, closed.
