### ISSUE TITLE
Mode 2: Overloader drove in circles then did not restart after combine finished turn at end of field.

### ISSUE THREAD

**Issue by VergylTantor** [Courseplay/courseplay#5479]
Expected Action: Unload Combine
What Happened: Combine had completed the headlands and was moving without crop harvesting at 14 mph to end of field. The overloader (OL) came to the end of the first set of point plotted by CP, then OL drove in circles 2-3 times then it stopped all movement. I was “riding” in the truck and I am not sure what the combine was doing at the time but I assumed at the time that the OL was driving in circles then when the combine made it’s turn at the end of the field the OL stopped and did not restart after the turn was complete.

![Farming Simulator 19 5_25_2020 7_33_11 PM](https://user-images.githubusercontent.com/39446775/82850848-89724480-9ec3-11ea-887c-001176218b32.png)
![Farming Simulator 19 5_25_2020 7_30_37 PM](https://user-images.githubusercontent.com/39446775/82850881-a1e25f00-9ec3-11ea-8bd5-79d4168db0d7.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4679395/log.txt)

Mods in Folder
FS19_EasyDevControls
CP Version  6.02.0020

**Comment by pvaiko** [comment]
@VergylTantor the reason it did not restart is that it wasn't able to find a path to the waiting combine due to that fence right on the field.

As for the other problem (circling), can you send me your courses?

**Comment by VergylTantor** [comment]
Here you go. Let me know if I can help.


[courseStorage0003.xml.txt](https://github.com/Courseplay/courseplay/files/4682769/courseStorage0003.xml.txt)
[courseStorage0005.xml.txt](https://github.com/Courseplay/courseplay/files/4682772/courseStorage0005.xml.txt)

**Comment by VergylTantor** [comment]
Here you go, Let me know if you need anything else, but my last save game prior to this issue some time earlier so I don't think that it could be used to recreate the issue.
[courseStorage0003.xml.txt](https://github.com/Courseplay/courseplay/files/4682797/courseStorage0003.xml.txt)
[courseStorage0005.xml.txt](https://github.com/Courseplay/courseplay/files/4682798/courseStorage0005.xml.txt)

**Comment by VergylTantor** [comment]
BTW is there a better way to upload xml other than renaming txt

**Comment by pvaiko** [comment]
The circling is fixed in 6.02.00024.
