### ISSUE TITLE
Tractor wont drive to combine in combi mode (new mode2).

### ISSUE THREAD

**Issue by soend** [Courseplay/courseplay#5480]
Dedicated server
Map: Lazy Acres Farm
CP version: FS19_Courseplay (Version: 6.02.00020)

(First things first, is the latest Courseplay even ment to be working on dedicated mp servers yet?)

But here's the issue im having: I have set up combi route with my tractor and trailer, combine is on the field also running with Courseplay driver but the tractor never drives up to the combine even when its 100% full. 
Also i noticed that in dedicated server and having the debug channels 7 and 14 on dont show any debug data on the screen like in single player, is that how it should be?

Log: [log.txt](https://gist.github.com/soend/8085f83f343c7c082a1cf260f7f11314)
Video: [https://streamable.com/dyd7qr](https://streamable.com/dyd7qr)

**Comment by Tensuko** [comment]
Collecting all in #5484
