### ISSUE TITLE
Pathfinder, Path for Truck hits combine header while positioning to receive crop.

### ISSUE THREAD

**Issue by VergylTantor** [Courseplay/courseplay#5482]
What was expected: When the combine has the pipe over the crop, the overloader (OL) drives around combine to get into position for receiving crop
What happened: The combine had the pipe over the crop and when the tank was full it successfully completed the pullback maneuver. The OL was parked after the last unload such that the front of the OL was facing the front of the combine. When the OL drove to the combing a path was plotted that attempted to take the OL between the combine and the crop. The tractor cleared the combine header but the side of the trailer hit the header. The OL was stuck on the header for some time but eventually freed itself and successfully completed the unloading sequence.
Note: I allowed the game to run for a short time while I decided whether or not to open a new issue.

![Farming Simulator 19 5_26_2020 7_28_08 AM](https://user-images.githubusercontent.com/39446775/82908198-3f25ad80-9f2d-11ea-8117-41a0e7c61a4f.png)
![Farming Simulator 19 5_26_2020 7_28_36 AM](https://user-images.githubusercontent.com/39446775/82908397-857b0c80-9f2d-11ea-92a7-bf60114c24c2.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4682643/log.txt)

Mods in Folder
FS19_EasyDevControls
CP Version 6.02.00020

**Comment by Tensuko** [comment]
Thats becouse the Pathfinder don't see the Trailer when calculate the path.

**Comment by pvaiko** [comment]
Yeah, this is a tough one. As @Tensuko said the current pathfinder does not calculate with the trailer. That's on our list but it isn't a trivial fix and will make the pathfinder even slower.

**Comment by VergylTantor** [comment]
Question: Would it help to start the loop on the other side of the combine as the OL is less likely positioned like that on the first headland pass and after that a trailer would be more in line with the tractor as it passed the combine?

**Comment by pvaiko** [comment]
> Question: Would it help to start the loop on the other side of the combine

Not sure what loop you mean.

It is also on our list to make the combine more intelligent and call the OL before it turns into a row with the pipe in the fruit, but that may not help in all situations either.

You can try other patterns though, like the Lands one with the pipe out of the fruit most of the time.

**Comment by VergylTantor** [comment]
If the OL would pass the combine on the other side instead of the side with the crop.

**Comment by VergylTantor** [comment]
I was thinking it might help to pass the combine on the side that does not have crop and it might on the up and down passes. The more I think about it the more possible issues that might be caused by obstacles near the edge of the field even on the second headland pass, so take it with a pinch of salt.

**Comment by pvaiko** [comment]
@VergylTantor sure, but we have no direct control over which side the path is going to be. That is why the pathfinder needs to take the trailer into account, that way it'll pick a path avoiding obstacles.

**Comment by Tensuko** [comment]
#5983

**Comment by Tensuko** [comment]
Should not happen anymore, as we changed a lot of traffic behaviour in Version 6.03.00001
Closing for now and waiting for new Mode2 adventures to see :)
Long Trailers might still hit something on the way back after swerving arround conflicts.
