### ISSUE TITLE
How in mode 2 does the vehicle detect the boundary between the plants and the harvested field?

### ISSUE THREAD

**Issue by KroshkaRoo** [Courseplay/courseplay#5483]
On some maps, vehicles do not detect plants when harvesting, despite activating the "crop detection" setting. I’m trying to understand what is the difference between the fields on different maps. Why does courceplay normally detect crops on some maps, but not on others

**Comment by Tensuko** [comment]
#5272

**Comment by KroshkaRoo** [comment]
> 
> 
> #5272

I read it. I mean - how does it work in principle? Because on that map where crops are not defined, they are not defined on any version of courseplay.

**Comment by Tensuko** [comment]
@pvaiko any Idea ? ...

**Comment by pvaiko** [comment]
https://github.com/Courseplay/courseplay/blob/97213894e31e5bc070d0732804a5bac6f13de484/course-generator/PathfinderUtil.lua#L260

**Comment by KroshkaRoo** [comment]
Thanks, I'll try to figure it out.
