### ISSUE TITLE
Multiplayer Rework

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/courseplay#5484]
As most of you know, Multiplayer is not working that great.
We are aware of this and doing some rework but that also means some more rework of some parts of CP, wich takes a while.

Since we have so many MP related Issues, we closing all of them and before post any new MP Issue, wait for the rework.

We know about the Issues and they are not gone.

Greetings,
Dev Team.

**Comment by jgross328** [comment]
> As most of you know, Multiplayer is not working that great.
> We are aware of this and doing some rework but that also means some more rework of some parts of CP, wich takes a while.
> 
> Since we have so many MP related Issues, we closing all of them and before post any new MP Issue, wait for the rework.
> 
> We know about the Issues and they are not gone.
> 
> Greetings,
> Dev Team.

Good Afternoon, 

I recently tried the newly updated CP with FS19 and noticed that I am still getting hitches when driving vehicles, only when CP is enabled. I know this is an old issue, but it is my first time posting as I haven't seen a fix. If there is any information I can assist in providing please let me know as this is the first time I have responded on a github. If it is just a work in progress, please just let me know and mark it as closed. Thank you for all the hard work you guys do!
