### ISSUE TITLE
mode 2 ver 16 issue

### ISSUE THREAD

**Issue by answermanitou** [Courseplay/courseplay#5486]
hello again
ver16 of CP still doesnt work properly.
In a first time i start harvester in field 12 than attach to him unloader. When harvester is reach 95% he did maneures for unloading and stop. In same time unloader is stay sleep in the end of the course and waiting for calling ... lol
I restart the game because I plaing from morning.
Again was generated same course for harvester in a field 12. Launched unloader and its works .... but only one time. The unloader is take all grain from harvester and ride to silo for emptining(WHY?) the fill level was 65-70% something about. Than unloader stoped at finish point and wait for call ... as always. But its not. Harvester reach 95% was stopped and waiting for unloader. Terrible.

about settings -- offsets and levels was in auto. Unloader saw the properly harvester and harvester call right unloader. 
After all I have error, freezing ets

[log.txt](https://github.com/Courseplay/courseplay/files/4683588/log.txt)
![fsScreen_2020_05_26_19_17_36](https://user-images.githubusercontent.com/64743178/82926149-73c65300-9f87-11ea-9525-1e7e0c928a81.png)
![fsScreen_2020_05_26_19_17_00](https://user-images.githubusercontent.com/64743178/82926156-75901680-9f87-11ea-9f91-abd12d46e519.png)
![fsScreen_2020_05_26_19_15_26](https://user-images.githubusercontent.com/64743178/82926160-7628ad00-9f87-11ea-9a4c-7481713972b4.png)
![fsScreen_2020_05_26_19_14_30](https://user-images.githubusercontent.com/64743178/82926162-7759da00-9f87-11ea-8a0f-c05ab308a2d9.png)
![fsScreen_2020_05_26_18_59_22](https://user-images.githubusercontent.com/64743178/82926164-77f27080-9f87-11ea-9a56-9926691c3490.png)
![fsScreen_2020_05_26_18_59_19](https://user-images.githubusercontent.com/64743178/82926166-788b0700-9f87-11ea-9f28-030d2a0f2724.png)
![fsScreen_2020_05_26_18_58_50](https://user-images.githubusercontent.com/64743178/82926170-79bc3400-9f87-11ea-8a6d-19aa9b40dfc1.png)
![fsScreen_2020_05_26_18_58_45](https://user-images.githubusercontent.com/64743178/82926173-7a54ca80-9f87-11ea-8b85-82c9766eb6c3.png)
![fsScreen_2020_05_26_18_58_43](https://user-images.githubusercontent.com/64743178/82926177-7aed6100-9f87-11ea-8caf-787339afebae.png)

**Comment by answermanitou** [comment]
Wow
When did you relize 020 version? 
I just now find that new version is available.
Will try but first I will read changes and fixes

**Comment by Tensuko** [comment]
Pls stop use the word 'still' ... it sounds like we are not fast enough to 'finaly' get it to work.

**Comment by answermanitou** [comment]
> Pls stop use the word 'still' ... it sounds like we are not fast enough to 'finaly' get it to work.

keep calm. I dont want touch you. Have some trouble with language
