### ISSUE TITLE
mode 2 ver 20 issue

### ISSUE THREAD

**Issue by answermanitou** [Courseplay/courseplay#5487]
I think that ver20 will be like a mirracle. wrong.
What I have now. 
Harvester did one circle and on the second he rise header and run until next knot than lowering header and work. But not first harvester not second harvester cant unload because unloader do nothing
i particulary switching debug. ist looks like all is good.
 And I must clearing the fields with old grandma version Cp because seasons mod talking about raining days

[log.txt](https://github.com/Courseplay/courseplay/files/4684047/log.txt)

![fsScreen_2020_05_26_20_26_32](https://user-images.githubusercontent.com/64743178/82933311-65c9ff80-9f92-11ea-82f6-ba000a09b323.png)
![fsScreen_2020_05_26_20_26_18](https://user-images.githubusercontent.com/64743178/82933316-66629600-9f92-11ea-9c0b-f6ef8445de2e.png)
![fsScreen_2020_05_26_19_17_36](https://user-images.githubusercontent.com/64743178/82933321-66fb2c80-9f92-11ea-9f63-40fd38904919.png)
![fsScreen_2020_05_26_19_17_00](https://user-images.githubusercontent.com/64743178/82933323-682c5980-9f92-11ea-90af-c5921973d8e5.png)
![fsScreen_2020_05_26_20_42_16](https://user-images.githubusercontent.com/64743178/82933306-6367a580-9f92-11ea-8788-d58f9d8a1df3.png)
![fsScreen_2020_05_26_20_29_07](https://user-images.githubusercontent.com/64743178/82933309-65316900-9f92-11ea-9cab-ec970c6cc232.png)

**Comment by pvaiko** [comment]
I thought that by miracle you'd open an issue with all the information requested in #5272 and a usable description of what happened.

Wrong.

**Comment by answermanitou** [comment]
Lets start again.
I launch harvester by the generated course. It must make two circle of headlands.
The harvester as you can see did one headland but when he moved on second he rise header and run without collecting crop. When he reach next knot marked red colour  he lower header and continue work. 
Two last screenshots
Prelast -- he continue moving
Last -- he filled and wait for wagon but unloader wait for call.
Sorry for language

**Comment by enderwiggin07** [comment]
> 
> 
> Lets start again.
> I launch harvester by the generated course. It must make two circle of headlands.
> The harvester as you can see did one headland but when he moved on second he rise header and run without collecting crop. When he reach next knot marked red colour he lower header and continue work.
> Two last screenshots
> Prelast -- he continue moving
> Last -- he filled and wait for wagon but unloader wait for call.
> Sorry for language

Look in https://github.com/Courseplay/courseplay/issues/5272 and there's a section called "How to report a problem with Mode 2".  They need the debug/log info to understand where to even look in the code for a potential issue
