### ISSUE TITLE
Mode 2 settings

### ISSUE THREAD

**Issue by answermanitou** [Courseplay/courseplay#5488]
In a #5972 talking about 100% fill level for command to the unloader. In the settings for harvester I check twice that is 100%
But the harvester beginning preparing unloading place at 95% and while its prepare he reach 96-97%. Is it as has to be or its wrong. 
I spotted few times that unloader in this situation going to harvester with manual call

**Comment by pvaiko** [comment]
That's how it works as it needs some capacity left to make a pocket.
