### ISSUE TITLE
Waiting for pathfinder Ver.020

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#5489]
Version 020 using Forager and 3 trailers. On the whole its working well but im getting quite a lot of this message particuarly when starting a field.

![fsScreen_2020_05_26_19_04_45](https://user-images.githubusercontent.com/11178621/82935185-8db26680-9f84-11ea-85ad-f453b2ade82a.png)

Ive no idea what it means or if theres a way to overcome it. 
[log.txt](https://github.com/Courseplay/courseplay/files/4684170/log.txt)

**Comment by pvaiko** [comment]
Not sure now what exactly the issue is, you don't have all the debug channels we requested in #5272 active so it is hard to tell. I see that this 8800i Chip, whatever it is causing issues, looks like we can't find a path to it.

There's not much we can do with this, there's no screenshot from the harvester, don't know what situation it is.

**Comment by Tensuko** [comment]
Also all dark, can't see anything.
And as said a few times, 3 Tailers are not supported yet and I noticed that this can cause Problems.

**Comment by Tensuko** [comment]
And wow..... I don't want to see this in a logfile....
Clean log, with debugchannels, read #5272 about Trailers and a screenshot where we can actually see stuff.
Load mod: Courseplay_6_01_00399 (Version: 6.01.00399) (Hash: 7113fa7d5a2bbfd2ab41ab5e3ec497ca)
Load mod: FS19_Courseplay017 (Version: 6.02.00017) (Hash: cf831f79f84bea839d2997e62d4190e5)
Load mod: FS19_Courseplay020 (Version: 6.02.00020) (Hash: dec1d9e80b3ff030d0e19402a9cbd166)


Make new Issue...

**Comment by kwguk** [comment]
Ok as im not a techie guru ill try better next time

Anyway im ploughing on have found that if i turn off 'avoid fruit' the tractors find the forager no problem. Then theres the problem of no 'following tractor' mode which ive over come by increasing the percantage before the next tractor appraoches the forager.

I can see why youve chosen to make a full trailer reverse but wouldnt it be more practical just to have the full one pull away forwards? 

Ive got ver20 working with 3 trailers, sort of!
