### ISSUE TITLE
Cannot load trailer! 

### ISSUE THREAD

**Issue by 13PAMS37** [Courseplay/courseplay#5491]
My problem is that the trailer is not filled from the storage without my participation. In order for it to start filling up, I need to get in the tractor, and I can immediately leave it loading continues, but if I am doing other things and can't keep track of this tractor every time, it will not fill up. For the sale of crops, for example. In the video, I show that I want to fill the trailer with wheat, and that it is in my storage, but the trailer is not filled.
[Video](https://drive.google.com/open?id=1Bv7CAD092Mb5MYbIkjYJ7062BUdnhhEz)

**Comment by Tensuko** [comment]
Why no logfile ?
Even without log I am 100% sure you got manuresystem in your mods with version 1.0.0.0.
Update to GitHub Version and it should work....

**Comment by 13PAMS37** [comment]
I deleted mod ManureSystem, and it also dont working. ( How I can make a log files for you?

**Comment by Tensuko** [comment]
logfile is in the same folder as your savegames and mods folder.
Drag and drop the log.txt into comment box.
Pls make a screenshot of the place where you want to load, turn on all waypoints (3 Dots in HUD Settings).

**Comment by 13PAMS37** [comment]
![image](https://user-images.githubusercontent.com/64957824/82994008-263efa00-a00a-11ea-96dc-4227b30cc0d8.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4687376/log.txt)
