### ISSUE TITLE
Some remarks...

### ISSUE THREAD

**Issue by wertigoxxx** [Courseplay/courseplay#5493]
**Hy!

-You won't always find the combine, even though all the extra options are on!

-When you reach the combine and empty the hopper, then plan the route and cross in front of the combine (picture attached)

-durried route planning (there was no such problem with v6.19-)

-is when he goes through the ground as if he were going around the ground where he was already cut off.
*** Log attached!**

![fsScreen_2020_05_24_11_15_25](https://user-images.githubusercontent.com/65092037/82982568-c555f880-9fee-11ea-86eb-1f6538132b9b.png)
![fsScreen_2020_05_24_21_42_08](https://user-images.githubusercontent.com/65092037/82982579-cc7d0680-9fee-11ea-8e2b-c7c9ce7e6f98.png)
![fsScreen_2020_05_25_06_44_54](https://user-images.githubusercontent.com/65092037/82982598-d272e780-9fee-11ea-903a-73a94c94e9c7.png)
![fsScreen_2020_05_27_07_35_49](https://user-images.githubusercontent.com/65092037/82982607-d69f0500-9fee-11ea-99a5-a85c88a50a6d.png)
![fsScreen_2020_05_27_07_36_31](https://user-images.githubusercontent.com/65092037/82982621-dbfc4f80-9fee-11ea-8b92-a65911cd46f8.png)
![fsScreen_2020_05_27_07_41_25](https://user-images.githubusercontent.com/65092037/82982637-e3235d80-9fee-11ea-9717-97ac276ba7f2.png)
![fsScreen_2020_05_27_07_41_26](https://user-images.githubusercontent.com/65092037/82982650-e9193e80-9fee-11ea-83e5-fbc33bfb8033.png)
![fsScreen_2020_05_27_07_41_27](https://user-images.githubusercontent.com/65092037/82982661-edddf280-9fee-11ea-903a-638716de8c05.png)
![fsScreen_2020_05_27_07_41_29](https://user-images.githubusercontent.com/65092037/82982672-f2a2a680-9fee-11ea-9fd4-567715401f99.png)
![fsScreen_2020_05_27_07_41_46](https://user-images.githubusercontent.com/65092037/82982681-f7675a80-9fee-11ea-8132-c455ace90a72.png)
![fsScreen_2020_05_27_07_46_20](https://user-images.githubusercontent.com/65092037/82982686-fa624b00-9fee-11ea-9c16-7f647cff4328.png)
![fsScreen_2020_05_27_07_46_22](https://user-images.githubusercontent.com/65092037/82982698-ffbf9580-9fee-11ea-875e-93a544e44be8.png)

LOG: 
[log.txt](https://github.com/Courseplay/courseplay/files/4686694/log.txt)

**Comment by Tensuko** [comment]
Some pics are with 00016 some 00018 some 00020....
Not rly helpful to Problems from 3 different Versions...

**Comment by pvaiko** [comment]
Sorry, can't do anything with this, as @Tensuko said, these are from 3 different versions, log still does not have all the requested debug channels on, no idea which screenshot is for which (unclear) problem description and no idea which problems are included in the log.
