### ISSUE TITLE
Need help with the turning methods

### ISSUE THREAD

**Issue by LevineYang** [Courseplay/courseplay#5494]
Hi, now I am reading the turn.lua script trying to understand why the tractor turns in various methods like WideTurn, 3 points turn, reverse 3 points turn, .etc. In the turn script, there are lots of procedures like calculating the circle center coordinate, I don't really understand why we use that specific equation to do that. So my question is can you guys provide some reference papers or web pages for me to learn why and how to do that?

**Comment by pvaiko** [comment]
The guy who wrote most of those isn't longer developing CP. I added some for the headland turns, I used GeoGebra to visualize, for example https://www.geogebra.org/m/aZmqNbW3.

But it isn't rocket science, it just plain old geometry. 

If you are interested in other methods to generate turns search for Dubins and Reeds-Shepp methods, both used in CP.

**Comment by LevineYang** [comment]
Got it, thanks!
