### ISSUE TITLE
Problem beim Aufschütten eines Keilsilos

### ISSUE THREAD

**Issue by tobi694** [Courseplay/courseplay#5495]
https://youtu.be/H6WmTbD3BKM

Das erste Silo hat einwandfrei funktioniert und das zweite funktioniert nicht, obwohl ich den Kurs genau gleich eingefahren habe. 

Bitte um Hilfe. 

Log File: 
[log.txt](https://github.com/Courseplay/courseplay/files/4687661/log.txt)

**Comment by Tensuko** [comment]
Weil er das Schüttgut vom nachbarsilo erkennt, gibt irgendwo ein Sammel Issue für Mode10.

Außerdem schmeiß mal die alte CP Version raus:
Load mod: Courseplay_6_01_00399 (Version: 6.01.00399) (Hash: 7113fa7d5a2bbfd2ab41ab5e3ec497ca)
Die neue ist ja drin:
Load mod: FS19_Courseplay (Version: 6.02.00020) (Hash: 658ed2ebf0c4b4ca6795cac75d51006e)
