### ISSUE TITLE
CP arbeitet nicht mit Krone ComprimaV180XC (nachfüllbar)

### ISSUE THREAD

**Issue by Hartmut88** [Courseplay/courseplay#5497]
Hallo Leute,

kann man an CP vielleicht irgendwas machen, damit die Rundballenpresse "Krone ComprimaV180XC" (manuell nachfüllbar) funktioniert?
Die selbe Presse als "nicht nachfüllbar" funktioniert tadellos in Verbindung mit CP. Also liegt es wohl ganz klar an dem nachfüllbaren Netz.
Zu LS17 Zeiten war das ja auch mit CP möglich.. glaube da war es z.B. die Krone Ultima Presse oder so..

**Comment by Tensuko** [comment]
Duplicate #5307
