### ISSUE TITLE
Mode 2: On headland pass chopper and tractor stop and in traffic error message is displayed for tractor

### ISSUE THREAD

**Issue by VergylTantor** [Courseplay/courseplay#5498]
What was expected: Follow Chopper on headland pass and receive chaff using Claas DLC Equipment.
What happened: The Overloader (OL) was started with the “Start course at” item set to Unload. After all working well for a short time both the Chopper and Tractor stop. A CP error message is displayed showing the tractor is in traffic.
Note: This issue is repeatable at least on this saved game and I have a backup copy of the save in case further testing is requested.
![Farming Simulator 19 5_27_2020 6_37_11 AM](https://user-images.githubusercontent.com/39446775/83019408-845ce480-9fec-11ea-9a52-dd2a1fd355d0.png)
![Farming Simulator 19 5_27_2020 6_37_43 AM](https://user-images.githubusercontent.com/39446775/83019455-96d71e00-9fec-11ea-8577-fc150b014872.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4688725/log.txt)

Mods in Folder
FS19_EasyDevControls
CP Version 6.02.00020
FS19_MultiLager_Maurice (a silo that stores chaff)

**Comment by Tensuko** [comment]
This is becouse only the big BigX is able to throw far enough to reach all parts of the Trailer.
We have no solution for other equipment right now.

For Mods I tested this one and it works too:
https://farming-simulator.com/mod.php?lang=de&country=de&mod_id=126256&title=fs2019

For all the other Equipment is status WIP.

**Comment by TinyCrocodile** [comment]
I can confirm, that rsm1403 works. I use it a lot. but i guess it is because ai colision trigger is missing. At least my logfile says that. This results in some rare cases where i had the mode 2 crash into the combine.

**Comment by Tensuko** [comment]
Colli is not relevant here

**Comment by TinyCrocodile** [comment]
Ok thanks good to know
