### ISSUE TITLE
mode 2 unloader issue

### ISSUE THREAD

**Issue by answermanitou** [Courseplay/courseplay#5499]
Look. CP-020
Two harvester and two unloader on the separate courses and fields
From  the start each unloaders doesnt respond harvesters in combine manager as selected.
When harvesters reach 95% they are prepare pockets and wait for unloaders. The both unloaders are stopped and wait for call.
After I manualy call unloaders from both harvesters the unloaders moved to harvesters. Grab the crop and than waiting. Harvesters again reach full fill level, call the unloaders, its OK.
The unloaders are moving for emptying wagons. Then stop in the end of unloading course. Next they both lost connect with harvesters(harvester from field marked but dont select). In this time both harvesters have by 95-96% and waiting for unloaders. In trasport section of CP combine was select unloader(see screenshot).
I try twice. everything works until the unloader goes empty

[log.txt](https://github.com/Courseplay/courseplay/files/4688703/log.txt)
![fsScreen_2020_05_27_15_28_40](https://user-images.githubusercontent.com/64743178/83019188-32897e00-a02f-11ea-8f14-f2729734c668.png)
![fsScreen_2020_05_27_15_28_29](https://user-images.githubusercontent.com/64743178/83019190-34534180-a02f-11ea-9275-0e5316a2de3f.png)
![fsScreen_2020_05_27_15_27_51](https://user-images.githubusercontent.com/64743178/83019192-34ebd800-a02f-11ea-9810-57c3eafe434c.png)
![fsScreen_2020_05_27_15_27_39](https://user-images.githubusercontent.com/64743178/83019195-35846e80-a02f-11ea-8d4c-555979961bfd.png)

**Comment by pvaiko** [comment]
@answermanitou can you set the unloader priority to distance instead of fill level and try again?

**Comment by answermanitou** [comment]
> @answermanitou can you set the unloader priority to distance instead of fill level and try again?

Ok. I will try your recommends
