### ISSUE TITLE
Lands and grimme Tectron

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#5501]
Just a question really, lands is great works really well. Until you try it on the Grimme which has its unloading pipe on the right hand side. Is it possible to tell the 'harvester' which way to turn when it does its lands?

**Comment by Tensuko** [comment]
Did you try to change the direction from CW to CCW ?

**Comment by kwguk** [comment]
No, only because ive no idea what CW/CCW are.....

**Comment by pseikoNL** [comment]
CW = ClockWise
CCW = Counter-ClockWise

**Comment by pvaiko** [comment]
@kwguk no it won't, Lands is for harvesters with the pipe on the left. And unless has some IRL exmples for potato/sugarbeet harvesters using this pattern, I won't add it.

**Comment by kwguk** [comment]
Ok thanks

West Amesbury Farms
