### ISSUE TITLE
problem with trailer distance from thresher

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#5502]
during the unloading of the forage harvester, with mode 2, after having made the first turn around the field with the tractor and the trailer behind it positions itself next to the forage harvester, only that, as I had already said for past versions, the tractor tends to be too far ahead, in some cases the forage harvester cannot move forward since the trailer is too far forward. I use version 6.02.00020
I just wanted to point this out, since I noticed that many problems of this mode are being solved

![Farming Simulator 19 27_05_2020 22_03_25](https://user-images.githubusercontent.com/59969508/83067398-e22e1280-a066-11ea-8edc-b2d2b4caeb05.png)
![Farming Simulator 19 27_05_2020 22_05_36](https://user-images.githubusercontent.com/59969508/83067468-04279500-a067-11ea-947f-3adcdf7c8111.png)
![Farming Simulator 19 27_05_2020 22_05_48](https://user-images.githubusercontent.com/59969508/83067477-07bb1c00-a067-11ea-825b-cd65791f5528.png)
![Farming Simulator 19 27_05_2020 22_05_50](https://user-images.githubusercontent.com/59969508/83067484-0984df80-a067-11ea-8d33-06362b3a2c19.png)

**Comment by Tensuko** [comment]
So where is the logfile with 4 7 12 and 14 ? #5272 ?
The problem will be the trailer with its target position....

**Comment by 0Pietro20** [comment]
This zip contains a video of the problem: the tractor is moving too far ahead of the forage harvester:
[Farming Simulator 19 2020-05-28 09-38-36.zip](https://github.com/Courseplay/courseplay/files/4694174/Farming.Simulator.19.2020-05-28.09-38-36.zip)

Here is the log:[log.txt](https://github.com/Courseplay/courseplay/files/4694168/log.txt)

I think the problem is the trailer, since trying with another one the exhaust was completely successful. I took some photos:
![Farming Simulator 19 28_05_2020 09_44_16](https://user-images.githubusercontent.com/59969508/83116332-eccec300-a0cb-11ea-8c6e-7f173e854d3d.png)
![Farming Simulator 19 28_05_2020 09_53_33](https://user-images.githubusercontent.com/59969508/83116344-efc9b380-a0cb-11ea-992e-800548a99ce5.png)

**Comment by Tensuko** [comment]
Yea thats the Problem of some mod Trailers, where the modder didn't place the target correctly.

**Comment by 0Pietro20** [comment]
Okay, thanks for the support. I will use other trailers so as not to have problems.
Congratulations again for mode 2, it's a sight to see all the maneuvers done to perfection. When you have the tractor switches it will be perfect. Compliments

**Comment by pvaiko** [comment]
Yes, this is most likely the endZ in the autoAimTargetNode setting of the trailer's XML.
