### ISSUE TITLE
Mode 2 - won't unload

### ISSUE THREAD

**Issue by cjd118** [Courseplay/courseplay#5503]
Hi,

Tractor and trailer will not tip over tip point - it is not auto-recognised. I drove over it at 1mph. Setting unload waypoint also doesn't work. Does it only support "bunkers" for chaff? 

[https://i.imgur.com/v2dSWL8.jpg](https://i.imgur.com/v2dSWL8.jpg)

**Comment by Tensuko** [comment]
logfile ?! ...

**Comment by wertigoxxx** [comment]
That's my problem too! :(

You don't follow the unloading point, you have to try in front of it, but not always!

[log.txt](https://github.com/Courseplay/courseplay/files/4693509/log.txt)

**Comment by Tensuko** [comment]
@wertigoxxx 
> 
> 
> That's my problem too! :(
> 
> You don't follow the unloading point, you have to try in front of it, but not always!
> 
> [log.txt](https://github.com/Courseplay/courseplay/files/4693509/log.txt)

throw out Load mod: FS19_manureSystem (Version: 1.0.0.0) (Hash: f6e43e963a789d956eb7c4212c305a4c) or update to newest GitHub Version

@cjd118 this could be the same problem for you, but I need your logfile...

**Comment by wertigoxxx** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4694623/log.txt)

Next problem:
manure mod deleted!!!!
**harvester problem, script frozen!**
FS19_Courseplay/specialTools.lua:798: attempt to call method 'getUnitFillLevel' (a nil value)
![fsScreen_2020_05_28_11_30_26](https://user-images.githubusercontent.com/65092037/83124722-daa65200-a0d6-11ea-87c2-83d779b643f2.png)

**Comment by pvaiko** [comment]
@wertigoxxx and please stop throwing in unrelated problems. Even worse, this last log of yours is a multiplayer game and has many other mod errors. Will not be able to fix any of your problems until you reproduce them on a standard map with standard equipment, with only CP enabled. Többször nem szólok.

**Comment by wertigoxxx** [comment]
Dear pvaiko!  I wanted to help by explaining the problems.  I didn't mean anything wrong with that.  I experienced problems I thought was important to you for cp to work properly.  Hi.

**Comment by Tensuko** [comment]
> 
> 
> I thought was important to you for cp to work properly.

you mean like this ? https://www.youtube.com/watch?v=PiUWD8ki8l4&t=3s

**Comment by cjd118** [comment]
@Tensuko sorry for the delay, here is the log file

[log.txt](https://github.com/Courseplay/courseplay/files/4698092/log.txt)

**Comment by Tensuko** [comment]
why channel 1 -4 ?
#5272 
channel 4 7 12 and 14

**Comment by Tensuko** [comment]
Doesn't work with CP, I try to contact Modder for this.
Suggestion: GC Fermenting Silo.
