### ISSUE TITLE
Trafic jum

### ISSUE THREAD

**Issue by gagidmd** [Courseplay/courseplay#5504]
![1](https://user-images.githubusercontent.com/65872248/83082055-9ab57f80-a082-11ea-869c-9705d563b647.jpg)

[log.txt](https://github.com/Courseplay/courseplay/files/4692366/log.txt)

Sory for English
When frst tractor start manuvar in reverse hit secund tractor behaind him
Lot of issues for leveling and compacting

**Comment by TinyCrocodile** [comment]
As written in #5272 Multiple unloaders are not supported yet.
