### ISSUE TITLE
Mode 6 3rd combine isn't working

### ISSUE THREAD

**Issue by Matt-14** [Courseplay/courseplay#5505]
When I try and start combining a field the 1st and second combine start correctly and the convoy distance set thing works fine but the 3rd combine won't start and drops my frames when I try to. However, I used to be able to get the 3rd combine to work but the convoy distance thing wouldn't work for the 3rd combine. .

**Comment by Tensuko** [comment]
logfile with debugchannel 7 12 and 14

**Comment by Matt-14** [comment]
https://gist.github.com/Matt-14/671c8cea9bb3a695273ebc0c9ad0c673

**Comment by Tensuko** [comment]
Some Mods with Errors and try with CP Version 00024.
I will make a test with 3 Combines later.

**Comment by Goof245** [comment]
AFAIK, convoy distance is broken when running offset tools. #5054

**Comment by Tensuko** [comment]
> 
> 
> AFAIK, convoy distance is broken when running offset tools. #5054

If that would be the Issue here, you would have only a wrong distance shown but the Combine would drive the course anyway.

**Comment by Matt-14** [comment]
It did it even when I deactivated the convoy distance. I am downloading the latest courseplay and will see if it changes anything.

**Comment by Matt-14** [comment]
So far it is starting the course. When I move to the next field I can give you an update.

**Comment by Matt-14** [comment]
Unfortunately I moved fields and the 3rd combine wont start. It just stands there and my frames drop. Kind of funny how on the 1st field I did today it worked fine...

**Comment by Tensuko** [comment]
Always create course at the side of the Field and not at the corner.

**Comment by Matt-14** [comment]
Ok got it, thanks for your help
