### ISSUE TITLE
 The truck does not unload the combine.

### ISSUE THREAD

**Issue by ANDRiYAndrei** [Courseplay/courseplay#5506]
I want to collect a field of sugar beet, the combine harvests, **but the truck doesn't want to go to the combine to unload it**, it made exactly the same settings I used and it doesn't go to unload the combine. I go manually to unload the combine and I start it again and it goes to unload at the silo and when it comes back, the combine reaches its set limit of quantity, and the truck does not go to unload.

- I do not use any mode on these vehicles.
- if you ask for something like logfiles, tell me how to send them to you.

**Comment by Tensuko** [comment]
#5272 
https://github.com/Courseplay/courseplay/wiki

**Comment by ANDRiYAndrei** [comment]
https://gist.githubusercontent.com/ANDRiYAndrei/3dc122e027eca3a786ac4edb4df03976/raw/61c507aa3051f2877c00f98a1c8b4d29bb22a17e/gistfile1.txt

**Comment by Tensuko** [comment]
Get Version 00023 https://github.com/Courseplay/courseplay/releases
and turn on the requested debugchannels (read #5272 )

**Comment by ANDRiYAndrei** [comment]
![fsScreen_2020_05_29_18_31_43](https://user-images.githubusercontent.com/66096737/83277414-af0c9000-a1da-11ea-9e14-5265fd23145c.png)

**Comment by Tensuko** [comment]
How to report a problem with Mode 2

    A log file with debug channel 4, 7 and 14
    Screenshot of the situation with debug channel 4, 7 and 14 and all waypoints on (the 3 dots in CP HUD settings)
    What you expected
    What happened

**Comment by ANDRiYAndrei** [comment]
ok, on version 23 it works, but when it goes to the combine it makes a lot of lag and when it goes to the combine it also makes a lot of lag and the "side offset" setting works very strangely.

**Comment by Tensuko** [comment]
It is not lagging, it is FPS drop couse of Pathfinder generating the Path.
Offset Strange ? Doubt that. Keep it on Auto and it should work, if a little off, correct it with Offsetvalue.

Else Post Screenshot of Setting and how it stays next to Combine.

**Comment by ANDRiYAndrei** [comment]
https://youtu.be/VW-MVByKZiY

Waiting for the video to finish uploading.

**Comment by ANDRiYAndrei** [comment]
![fsScreen_2020_05_30_03_35_48](https://user-images.githubusercontent.com/66096737/83315171-d25d2c80-a226-11ea-9010-b9b3af4f4f23.png)
![fsScreen_2020_05_30_03_36_00](https://user-images.githubusercontent.com/66096737/83315172-d38e5980-a226-11ea-8fe3-8f3567667a46.png)

[log.txt](https://github.com/Courseplay/courseplay/files/4704848/log.txt)

Again he does not go to unload the combine.

**Comment by Tensuko** [comment]
Since the Combine have pipe in the fruit, try turn off Avoid Fruit in the HUD.
Else I don't see a reason, maybe @pvaiko got an Idea...

**Comment by ANDRiYAndrei** [comment]
Avoid Fruit is always off.

**Comment by androno12** [comment]
and I have a problem - the truck does not reach the combine
[log.txt](https://github.com/Courseplay/courseplay/files/4722514/log.txt)
https://youtu.be/C4q2Q2iTGSE

**Comment by pvaiko** [comment]
@androno12 https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ#the-unloader-does-not-drive-to-the-combine

**Comment by androno12** [comment]
> 
> 
> @androno12 https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ#the-unloader-does-not-drive-to-the-combine
the truck goes to the harvester! But it stops before reaching the combine!  oh, that google translator...

**Comment by Tensuko** [comment]
@androno12 you got a callstack in your log.
Update CP and I would try to check if Avoid Fruit is off.

**Comment by Tensuko** [comment]
Closed due to inactivity. Check Wiki and #5272 for Informations and other issues in case you still have a problem with this and it is similar.
