### ISSUE TITLE
Neue Version einfügen

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#5508]
Hallo 
Kann ich die neue Version in den Mod Ordner reinpacken und dann die vorige Version ersetzten oder muss ich noch etwas anderes löschen damit die Version funktioniert

**Comment by Tensuko** [comment]
alte Version löschen und neue Version einfügen wie sonst auch ?
https://github.com/Courseplay/courseplay/releases
.zip Datei runter laden und in den Mods Ordner packen, fertig.
Lade am besten die Version 00020 runter, da wir in der 00022 gerade einen Fehler drin haben den wir erst noch beheben müssen. Kann sein das er bei dir vor kommt, kann auch sein das alles gut geht.
