### ISSUE TITLE
Loss of control of machinery

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#5509]
Im using ver.022. 
Im using CP for various tasks, cultivating, spreading etc when all of a sudden i seem to lose control of the vehicles. The screen seesm to freeze as the vehicle contiunes to drive on into the distance. I can still flick between different vehicles but those inder CP control are either not doing their alloted task or carrying on in  astraight line.
Im hoping its just maybe a mod conflict because its happened with both 021 and 022.

[log.txt](https://github.com/Courseplay/courseplay/files/4701776/log.txt)

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

>
>
>> How to provide a nice and sexy bug report:

    Always update to the latest build and check if the problem really still exists before reporting issues.


https://github.com/Courseplay/courseplay/releases
