### ISSUE TITLE
Nearest waypoint suggestion

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#551]
I think it would be a helpful feature if when starting a course from the nearest waypoint, that it would choose the nearest way point that is in front of the tractor based on which direction it is facing.   This would allow you to drive into a course and resume it without the chance of grabbing a waypoint that is facing the opposite direction, but is closer (like the opposite facing row) or the waypoint just behind the tractor instead of the waypoint you want to start at, and have the tractor spin around in circles or crash into an obstacle trying to reach it.

**Comment by AndyK70** [comment]
> What if there are no waypoints in front of you? 
Then don't take them into consideration, as it is now

> What if there are, but they're 3000 ft away?
Only take into consideration waypoints in a radius of max 7 meters, as waypoints are created in steps of 5m there should be a valid waypoint in front of the vehicle within that radius. If not, it's not valid.

else?
