### ISSUE TITLE
can't find the combine on the field, long looking for pathfinder for several minutes

### ISSUE THREAD

**Issue by wertigoxxx** [Courseplay/courseplay#5511]
**Hey guys!

I'm sorry I have to open a topic again, but I ran into problems again. The CP is already there that the route search can take several minutes. You can't find the combine.
Useless because the game is constantly around 20-25 fps.
Something very climbed :(

The combine, when it cuts the ground, calls the tractor, the tractor crawls at one end of the ground, circles, searches for the combine, but travels the wrong route.

I've attached a few pictures and a log! Maybe this will help shed light on the problem.
I don't have a serious mod list, so I suspect the cp that something isn't good!

As for my other big problem, the pathfinder, looking for the route for a very long time, just kills the machine! (25 fps)**

With these modes, the older versions worked perfectly, you quickly planned the route to the combine, please fix it!

Thanks

![fsScreen_2020_05_29_18_46_24](https://user-images.githubusercontent.com/65092037/83284804-8639ca00-a1dd-11ea-9641-e8bc6a8715d3.png)
![fsScreen_2020_05_29_18_46_50](https://user-images.githubusercontent.com/65092037/83284819-8c2fab00-a1dd-11ea-8eb0-3d40f0388f12.png)
![fsScreen_2020_05_29_18_48_38](https://user-images.githubusercontent.com/65092037/83284842-92258c00-a1dd-11ea-94fa-32ddd498c03f.png)
![fsScreen_2020_05_29_18_48_46](https://user-images.githubusercontent.com/65092037/83284860-981b6d00-a1dd-11ea-8c73-2abdbfe902e7.png)
![fsScreen_2020_05_29_18_49_45](https://user-images.githubusercontent.com/65092037/83284872-9baef400-a1dd-11ea-892c-629a3d7483f4.png)
![fsScreen_2020_05_29_18_49_48](https://user-images.githubusercontent.com/65092037/83284882-a1a4d500-a1dd-11ea-8533-fff8d1ba6230.png)
![fsScreen_2020_05_29_18_49_55](https://user-images.githubusercontent.com/65092037/83284892-a7021f80-a1dd-11ea-80e0-3772585543ec.png)
![fsScreen_2020_05_29_18_49_57](https://user-images.githubusercontent.com/65092037/83284908-ae292d80-a1dd-11ea-950d-a33cf725fc63.png)
![fsScreen_2020_05_29_18_50_07](https://user-images.githubusercontent.com/65092037/83284920-b2ede180-a1dd-11ea-849a-3dc4825953c6.png)
![fsScreen_2020_05_29_18_50_20](https://user-images.githubusercontent.com/65092037/83284936-b7b29580-a1dd-11ea-996c-c33542e2573b.png)
![fsScreen_2020_05_29_18_50_38](https://user-images.githubusercontent.com/65092037/83284952-bc774980-a1dd-11ea-8ea5-6c946b2b9fca.png)

**LOG:**
[log.txt](https://github.com/Courseplay/courseplay/files/4703112/log.txt)

**Comment by Tensuko** [comment]
> As for my other big problem, the pathfinder, looking for the route for a very long time, just kills the machine! (25 fps)**

Your Comp will chill at low temps since the GPU and CPU are not the limits here....

> The combine, when it cuts the ground, calls the tractor, the tractor crawls at one end of the ground, circles, searches for the combine, but travels the wrong route.

It meets up with the combine


> With these modes, the older versions worked perfectly, you quickly planned the route to the combine, please fix it!

Won't fix it in the direction of an old Version.

**Comment by wertigoxxx** [comment]
when he plans the route, it drops to 20-25 fps and for a long time that way, I have a strong machine no problem for him. :)
one thing is for sure, planning takes a long time, there are times when you can’t find the combine and you’re close to it.

maybe it has to do with the density of the crop, it interferes?

**Comment by Tensuko** [comment]
Do you still face this Problem or can we close this ?
