### ISSUE TITLE
Spreaders and sprayers turn on very early when turning

### ISSUE THREAD

**Issue by vorezal** [Courseplay/courseplay#5512]
I've noticed this behavior with quite a few courses and tools that spray or spread. Here is an example screenshot from the Bredal spreading lime. It is turning to hit the node I've circled in red.

![spreader_starts_early](https://user-images.githubusercontent.com/37914382/83285418-2f67cc80-a1ac-11ea-865c-19348e796850.png)

I believe I have seen the same general behavior with rear mounted sprayers too, though I haven't tested recently. They seem to stop at the right time. There doesn't look to be any difference if the value of raise/lower implements early/late are changed. I am using courseplay v6.02.00020.

**Comment by vorezal** [comment]
I just noticed v6.02.00023 is out. I gave that a try and this looks like it may be fixed. Guess my timing was a tiny bit off.

**Comment by vorezal** [comment]
I definitely can't reproduce the issue any longer. I see no problem closing this until and unless it happens again. I'll attach a log file next time if it does.

**Comment by Tensuko** [comment]
Sounds good :)
