### ISSUE TITLE
Lua Problem mit der Comprima V 180 XC vom Strohbergungs Addon

### ISSUE THREAD

**Issue by RobinHooooood** [Courseplay/courseplay#5513]
Wollt nur euch aufmerksam machen das wenn ich mit Coursplay die Comprima V 180 XC aktiviert, dass dann ein Lua Error kommt. 
Also sobald ich den Helfer aktiviere friert das Spiel ein man kann zwar noch in den Shop und so aber man kann sich nicht mehr Bewegen und man kann den Helfer auch nicht wieder entlassen. 
Ist das normal undd kann man ddas fixen oder wirds nicht möglich sein die Comprima V 180 XC mit Coursplay zu nutzen?

Lg :D

Ver. 6.02

**Comment by Tensuko** [comment]
logfile ? Du hast 100% nicht die StrohBergungs Beta drin und Ver. 6.02 ist alles von 000001 bis 99999

**Comment by RobinHooooood** [comment]
Ver. 6.02 .00001 
[log.txt](https://github.com/Courseplay/courseplay/files/4704958/log.txt)
Log Error kommt ab Zeile 5743 und geht bis 6010

**Comment by Tensuko** [comment]
So, erstmal wie ich es vorausgesagt habe:
Load mod: FS19_addon_strawHarvest (Version: 1.0.0.0) (Hash: 8497c57136373717593e45fee2c0f0f3)
Beta bei Creative Mesh im Discord suchen und laden!

Des weiteren 00001 ?
Ich schlage mal dringend ein Update vor:
https://github.com/Courseplay/courseplay/releases

Und für das nächste mal:
https://github.com/Courseplay/courseplay/wiki

Wichtig: Geräte von Strohbergung mit Auto Refill kaufen.
