### ISSUE TITLE
Mode2, truck cant unload combine, cant keep right fieldstate

### ISSUE THREAD

**Issue by Bobster82** [Courseplay/courseplay#5515]
Hello, 
I found some time to test things out... my 1st test was mode 2 with a combine and truck/trailer.
Using CP Version: 6.02.00023 (dont bother the diff versions in the mod map, was testing diff versions)
Also made a video where u can see these "isues", hope this explains... also provided a log.
Video stutters a bit, dont know where that went wrong...

* The truck pathfinding to the combine is a bit off the line.
* The truck doesnt recognize the combine and header as collision... But it does goes trough a list of vehicles in the game, even the train... if its on purose, then nothing said (see log)
* The truck offset to the combine pipe is wrong in automode
* The truck keeps switching between onField modes, it cant drive next to the combine

If u need more, let me know.
https://youtu.be/KUOzC2plV0Q

[log.txt](https://github.com/Courseplay/courseplay/files/4704321/log.txt)

edit:
I just saw that a stopped combine works... but maybe this helps to get the driving combine unloading working (but you would already know "this problem"

**Comment by Tensuko** [comment]
![Nodes](https://user-images.githubusercontent.com/27344744/83308831-f8270900-a207-11ea-808f-ec3dc9b533d3.png)

GIANTS Truck Problem.

The other Things no Idea why it instantly stops when reach target.

**Comment by Bobster82** [comment]
> GIANTS Truck Problem.

Didnt know this. Will check other things tomorrow... i finaly have some time again... if i only could understand the code better

**Comment by polosubtil** [comment]
@Bobster82, did you try to move the target further back ? With the vertical setting ? The target looks really close to the front of the trailer

**Comment by Bobster82** [comment]
> vertical

If u checked the video, u saw i already tried that ;) that didnt make a difference

**Comment by Bobster82** [comment]
> @Bobster82, did you try to move the target further back ? With the vertical setting ? The target looks really close to the front of the trailer

If u checked the video, u saw i already was trying that. It didnt work

**Comment by Tensuko** [comment]
Why..... One Version and its name should be as you download it: FS19_Courseplay.zip ......

Load mod: FS19_CoursePlay6 (Version: 6.02.00022) (Hash: 0f2e6cf13585dfa1fc41971485aa3a5d)
Load mod: FS19_CoursePlay6_2 (Version: 6.02.00020) (Hash: 4f97694939a9878d00f34c5861df3dad)
Load mod: FS19_CoursePlay6_23 (Version: 6.02.00023) (Hash: 228b4d086dbed6bb9c3b7828d8a07bda)

And Update GC this one is to old:
Load mod: FS19_GlobalCompany (Version: 1.2.1.0) (Hash: 3e08e57c15c66834115c1d5849f4d14f)

**Comment by Bobster82** [comment]
> Why..... One Version and its name should be as you download it: FS19_Courseplay.zip ......
> 
> Load mod: FS19_CoursePlay6 (Version: 6.02.00022) (Hash: 0f2e6cf13585dfa1fc41971485aa3a5d)
> Load mod: FS19_CoursePlay6_2 (Version: 6.02.00020) (Hash: 4f97694939a9878d00f34c5861df3dad)
> Load mod: FS19_CoursePlay6_23 (Version: 6.02.00023) (Hash: 228b4d086dbed6bb9c3b7828d8a07bda)
> 
> And Update GC this one is to old:
> Load mod: FS19_GlobalCompany (Version: 1.2.1.0) (Hash: 3e08e57c15c66834115c1d5849f4d14f)

As i said in my top post to switch between them when testing... it doesnt affect any performance or usage ;) ... and i just started fs19 again and the 1st one i wanted to do is testing cp and ad... that other mods are old i dont care for now, only if they conflicting... but yes better remove them (or update haha) but thanks for checking my mess ;)

**Comment by Bobster82** [comment]
@Tensuko ,

I tested it with a man truck with trailer and a fend tractor with trailer, this worked as expected... So i think the bug with the fieldstate is in the "giants truck problem" maybe a workaround can be made or wait till giants fixes it... but until that, i wont use the "bugged" trucks... thanks for pointing me that out!!

**Comment by Tensuko** [comment]
GIANTS should know that as I sent Lisertan that pic long time ago, but I doubt they will fix it...

**Comment by Bobster82** [comment]
> GIANTS should know that as I sent Lisertan that pic long time ago, but I doubt they will fix it...

Maybe it isnt a priority... 

But you can close this one if needed... I got my answers, thanks
