### ISSUE TITLE
unload point and round the combine before collision

### ISSUE THREAD

**Issue by wertigoxxx** [Courseplay/courseplay#5516]
sorry for the english!
**I'm just trying to make the CP work great;)**
Thanks for the previous fixes!

I tried it in factory mode, the emptying point doesn't work when creating the course, when I want to empty left or right it doesn't.
if it tilts backwards, it works well. it is likely that a little trigger refinement is needed only.
I'll share it with you! :)

the other minor problem:

the tractor's trailer turns in front of the combine when planning a route (video attached)
this generates a collision, shifts the combine, throws the cut

![fsScreen_2020_05_30_08_25_49](https://user-images.githubusercontent.com/65092037/83321617-1cf39e80-a251-11ea-8200-417785e72494.png)
![fsScreen_2020_05_30_08_28_19](https://user-images.githubusercontent.com/65092037/83321622-22e97f80-a251-11ea-9865-de5baddc7f16.png)
![fsScreen_2020_05_30_08_29_02](https://user-images.githubusercontent.com/65092037/83321624-267d0680-a251-11ea-8dea-23b42555126b.png)
![fsScreen_2020_05_30_08_29_05](https://user-images.githubusercontent.com/65092037/83321629-2a108d80-a251-11ea-8d23-c6e2e708897d.png)
![fsScreen_2020_05_30_08_29_08](https://user-images.githubusercontent.com/65092037/83321632-2e3cab00-a251-11ea-8f28-5811795d2cd3.png)

Video:
https://youtu.be/1gCA9p6HG4k

LOG:
[log.txt](https://github.com/Courseplay/courseplay/files/4705203/log.txt)

**Comment by turtlbrdr** [comment]
I am also experiencing the tractors routing in front of the harvesters when taking off. I didn't notice it until a few days ago, but I suspect that the issue causing it happened with .0026. It only seems to happen for me when harvester is offloading while moving, specifically when the overloading trailer fills before the harvester empties, however it does not always do so.

When the harvester empties and the overloader is above its move on threshold it will not path in front of the harvester. When the harvester backs out of it's path to allow the overloader access to the pipe, the overloader will back up properly when it is done receiving product.

After looking into the circumstances a bit, it almost seems like the longer it takes the pathfinder to route the overloader off the field the less likely it is to impact the harvester. As I seem to have more problems at the side of the field where the harvester is closest to the offload route. This makes me think that there is a crucial moment, probably more or less a second, and it is the difference between the harvester moving far enough into the overloader's "field of view" and stopping it versus moving at an angle where it doesn't see the harvester. 

My setup to the above is similar, I'm using the same harvester mod (s790), though I am using the Midwest Duras 55ft header mod with mine. I do have to adjust the side offset (-0.4). Something I also noted about above is that I think they are using two overloading helpers (the 7310R and the 6300 CVT), I am only using one.

**Comment by pvaiko** [comment]
>  It only seems to happen for me when harvester is offloading while moving, specifically when the overloading trailer fills before the harvester empties

@turtlbrdr thank you for this great observation, this is exactly the kind of information what we are looking for, descriptions like this make it a lot easier for me to fix issues.

**Comment by Tensuko** [comment]
#5983

**Comment by Tensuko** [comment]
Should not happen anymore, as we changed a lot of traffic behaviour in Version 6.03.00001
Closing for now and waiting for new Mode2 adventures to see :)
This does not include a Trailer that might hit the Header a bit, but we will see.
