### ISSUE TITLE
waiting pathfinder 

### ISSUE THREAD

**Issue by answermanitou** [Courseplay/courseplay#5519]
Hello
Install last version of CP and looks like i have the same problem as by #5511 
I launched separately 3 field works process
field 26 and 27 are worked absolutly great.
field 32 from the begin works nice. But when unloader is came second time from emptying course he was staying and staying.
Than I activate debug channels and try to restart course for unloader -- nothing. Reselect combine -- nithing.
 There is waiting for pathfinder issue

Also I have much FPS down while mode2 is working 

On a screenshot you can see how long the work was properly does

[log.txt](https://github.com/Courseplay/courseplay/files/4705598/log.txt)

![fsScreen_2020_05_30_15_07_49](https://user-images.githubusercontent.com/64743178/83328018-de79d600-a288-11ea-9ddf-1890c7849841.png)
![fsScreen_2020_05_30_15_03_53](https://user-images.githubusercontent.com/64743178/83328020-e0439980-a288-11ea-903e-798492580991.png)

**Comment by pvaiko** [comment]
Make sure you have 'pathfinding' activated in the HUD for that combine on field 32. 

It should pull back and make room for the unloader under the pipe. The unloader does not find a path because the pipe is in the fruit.

Reopen if it does not help.

**Comment by answermanitou** [comment]
> Make sure you have 'pathfinding' activated in the HUD for that combine on field 32.
> 
> It should pull back and make room for the unloader under the pipe. The unloader does not find a path because the pipe is in the fruit.
> 
> Reopen if it does not help.


I downloaded the game from the moment I had a problem to check about settings. The pathfinding was activated. I attach screenshoot. You can compare with previous screenshoots by in game clock.


If I make changes to CP Hud when the AI ​​is on the go, will they be taken into account for future work. Or you need to recreate, restart the course from the beginning?

In this moment I  will recheck all settings -- that all in HuD is ON, regenerate all courses for harvesters. That write report.
one thing that bothers me is the strong FPS drawdown

**Comment by answermanitou** [comment]
I finished harvesting the fields.
Field 32 continued to drink blood.
Despite all the settings turned on, the unloader was always looking for a way. Restarting and other actions did not lead to success. Also, during the search for a path, a very large drop in the FPS.
The impression was that when three combines are working, then for the third there is not enough of something.
Debuging i on and off. While all was OK. Its was off.
[log.txt](https://github.com/Courseplay/courseplay/files/4706036/log.txt)
Here is how its stopped and wait for unloader and also I receive 1702 error
![fsScreen_2020_05_30_17_29_04](https://user-images.githubusercontent.com/64743178/83334081-bb611d80-a2ac-11ea-867f-9cee8b0a7566.png)

Here is unloader is waiting for pathfinder
![fsScreen_2020_05_30_17_33_47](https://user-images.githubusercontent.com/64743178/83334114-ff542280-a2ac-11ea-8f96-4874959ea76b.png)

Here is FPS down when he wait for pathfinder
![fsScreen_2020_05_30_18_38_52](https://user-images.githubusercontent.com/64743178/83334136-1bf05a80-a2ad-11ea-8ed1-062c6ca32fef.png)

here is I stop the course and FPS is normaly
![fsScreen_2020_05_30_18_38_47](https://user-images.githubusercontent.com/64743178/83334155-3591a200-a2ad-11ea-98e0-eb17a3715b68.png)
