### ISSUE TITLE
silage thrust

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#5520]
during the pushing of the silage the tractor often gets stuck against the bottom of the trench and does not unlock if not manually.
I state that I was trying to shred with various tractors and maybe he messed up the courseplay, if it is this type of problem then excuse me

![Farming Simulator 19 30_05_2020 18_00_04](https://user-images.githubusercontent.com/59969508/83333336-64ede200-a2a0-11ea-8923-0723f59d0652.png)
![Uploading Farming Simulator 19 30_05_2020 18_00_26.png…]()

log:[log.txt](https://github.com/Courseplay/courseplay/files/4705981/log.txt)

**Comment by 0Pietro20** [comment]
![Farming Simulator 19 30_05_2020 18_00_26](https://user-images.githubusercontent.com/59969508/83333415-95358080-a2a0-11ea-9bc2-e235f53918b9.png)

**Comment by Tensuko** [comment]
Try other Shield ? (GIANTS)

**Comment by 0Pietro20** [comment]
I also tried with the original blades of the game but it didn't work, always the same problem. I play on a different map from the original, maybe that's it. I was playing with the GreenRiver2019 map
![Farming Simulator 19 31_05_2020 22_16_34](https://user-images.githubusercontent.com/59969508/83383508-8dcbbf80-a3e5-11ea-96c1-ae5e9d191a3f.png)
![Farming Simulator 19 31_05_2020 22_16_57](https://user-images.githubusercontent.com/59969508/83383520-90c6b000-a3e5-11ea-9b71-7baaf10efb06.png)


log:
[log.txt](https://github.com/Courseplay/courseplay/files/4709833/log.txt)

**Comment by 0Pietro20** [comment]
I don't know what mistake it is, but during the first pushes everything works perfectly, after a few times instead it gets stuck sideways turning completely towards the left wall of the trench or it continues to push even after touching the bottom. Maybe to overcome all these possible problems you could put a "timer" that after a number of seconds that the tractor is working but did not change position automatically raises the blade and returns to push as before. I hope it helps

**Comment by Tensuko** [comment]
What could happen is, that some chaff is inside the wall and he tries to push it to the trigger end.

**Comment by 0Pietro20** [comment]
Understand where the error can be

**Comment by Tensuko** [comment]
Guess its chaff in the silo wall, will close this one for now
