### ISSUE TITLE
Transport can't find the harvester and not only that. v6. 02. 00024

### ISSUE THREAD

**Issue by Tocik** [Courseplay/courseplay#5521]
The latest version of v6. 02. 00024 has once again become relevant to the problem of searching for a combine.
I run all the routes I need (combine and truck). In the beginning, everything works fine. After filling the truck takes the grain for unloading, and after returning can not find the combine, although it is already standing and requires unloading. If you click on the combine to "call the transport", that's what he immediately went to download. There is a second problem that I have encountered. After a full load, the truck can't leave for unloading, because the harvester interferes with it. The truck goes back, and then makes a u-turn through the combine.
I'm sorry, the screenshots were not saved.
For comparison, in the v6.02.00020 version, there were no such problems, the truck always went to the combine without problems, and the u-turn after filling was done at the rear of the combine.

**Comment by Tensuko** [comment]
#5272
