### ISSUE TITLE
Waiting pathfinder

### ISSUE THREAD

**Issue by answermanitou** [Courseplay/courseplay#5522]
Continue of #5519 issue
I finished harvesting the fields.
@pvaiko  @Tensuko 
Field 32 continued to drink blood.
Despite all the settings turned on, the unloader was always looking for a way. Restarting and other actions did not lead to success. Also, during the search for a path, a very large drop in the FPS.
The impression was that when three combines are working, then for the third there is not enough of something.
Debuging i on and off. While all was OK. Its was off.
[log.txt](https://github.com/Courseplay/courseplay/files/4706036/log.txt)
Here is how its stopped and wait for unloader and also I receive 1702 error
![fsScreen_2020_05_30_17_29_04](https://user-images.githubusercontent.com/64743178/83334081-bb611d80-a2ac-11ea-867f-9cee8b0a7566.png)

Here is unloader is waiting for pathfinder
![fsScreen_2020_05_30_17_33_47](https://user-images.githubusercontent.com/64743178/83334114-ff542280-a2ac-11ea-8f96-4874959ea76b.png)

Here is FPS down when he wait for pathfinder
![fsScreen_2020_05_30_18_38_52](https://user-images.githubusercontent.com/64743178/83334136-1bf05a80-a2ad-11ea-8ed1-062c6ca32fef.png)

here is I stop the course and FPS is normaly
![fsScreen_2020_05_30_18_38_47](https://user-images.githubusercontent.com/64743178/83334155-3591a200-a2ad-11ea-98e0-eb17a3715b68.png)

_Originally posted by @answermanitou in https://github.com/Courseplay/courseplay/issues/5519#issuecomment-636355201_

**Comment by answermanitou** [comment]
Also one time while unloader is waiting for pathfinder it suddenly found it and move to the combine.

**Comment by pvaiko** [comment]
Just keep wondering: why are only two people having problems with Mode 2? No one else is using it? If others are using it, they don't have issues? Or they do, just not reporting it? Or these two are doing something differently then all the others?

**Comment by pvaiko** [comment]
@answermanitou there's no need to report the low FPS while the pathfinder is running. We know that, that's how it works.

**Comment by answermanitou** [comment]
> @answermanitou there's no need to report the low FPS while the pathfinder is running. We know that, that's how it works.

I think about it. It's because AI calculating his route ets. 
But I think that its calculating each times when Ai does maneuvers, but just in a case when he can't moved to target its do fps down

**Comment by answermanitou** [comment]
> Just keep wondering: why are only two people having problems with Mode 2? No one else is using it? If others are using it, they don't have issues? Or they do, just not reporting it? Or these two are doing something differently then all the others?

I don't know about others or who have or not same problem. You told me try with pathfinder on and report. I m do what you said. 
And now I hear reproaches in my direction

**Comment by pvaiko** [comment]
The only thing I can do for you is that you post your save game and courses here with a situation where the pathfinding does not work.

Of course only official maps and mods (downloadable from farming-simulator.com).

**Comment by answermanitou** [comment]
I browse some sites from rus region to find posts about CP. Most of them have old versions and few comments that mode2 doesnt work. I think that players didnt know about this site and most of them even if know do not write reports or issues about problem with Cp.

I loading winrar and put then folders:
mods, courseplay courses, global company folders, and backup savegame from the moment what we talking about
About settings by CP
Field 26
Harvester Case: start from Nord-east, direction automaticly, headlands 2 clockwise. Generate. Launch from nearest point
Unloader Fendt500: must have saved course or give him F26-unload

Field 27
Harvester Case: start from Nord-east, direction automaticly, headlands 1 clockwise. Generate. Launch from the nearest point
Unloader Fendt500: must have saved or give him F27-unl-soyfact

Field 32
Harvester Case: start from South-west, direction automaticly, headlands 1 clockwise. Generate. Launch from the nearest point but at first you probably should emptying it manualy
Unloader Fendt500: F32-unl-soyfact course
[savegame3_backup2020-05-30_17-20.zip](https://github.com/Courseplay/courseplay/files/4707327/savegame3_backup2020-05-30_17-20.zip)
[CoursePlay_Courses.zip](https://github.com/Courseplay/courseplay/files/4707329/CoursePlay_Courses.zip)
[GlobalCompany_GlobalMarket.zip](https://github.com/Courseplay/courseplay/files/4707330/GlobalCompany_GlobalMarket.zip)

The mods folder
https://drive.google.com/file/d/1P73039-faxYBwy_rDzM1hgUH_0AeZLLz/view?usp=sharing

**Comment by Tensuko** [comment]
This:

> Of course only official maps and mods (downloadable from farming-simulator.com).

**Comment by answermanitou** [comment]
> This:
> 
> > Of course only official maps and mods (downloadable from farming-simulator.com).

hmm
I think that the map what I played was from FS site ... 
yesmods Is this site suitable? 
https://www.yesmods.com/fs19-mods/maps/european-maps/slovak-village-mh/
or modhoster?
I found this map while browsing on giants forum
https://forum.giants-software.com/viewtopic.php?f=952&t=145416&sid=f5416e76cf10034e963b9e97f258533d&start=75

**Comment by kwguk** [comment]
ive had problems with mode 2 very similar to whats been described. i maanged to get round it by turning off 'avoid fruit' in the tractor HUD then it finds the combine/forager pretty much straight away. Its almost like the more crop bewteen the tractor and harvester the less chance the tractor uasing pathfinder will locate it. All the time the travtor ia searching its having a detrimetal effect on the FPS.

Its true that when the Tractor is looking for the route using pathfinder there is a drop in FPS. I get it when a machine is back from a 'reloading' route using AD then switches back to CP, whilst its looking where its continuation point is the FPS will halve.

Im a fair way off going harvesting again and admittedly ver020 was hte latest version out when i was last harvesting.

**Comment by answermanitou** [comment]
Interesting. I even want to retry with "moving on crop" off. But must going to work(
Will do it at evening

**Comment by pvaiko** [comment]
@answermanitou so, I looked at your savegame. 
1. as I told you already in https://github.com/Courseplay/courseplay/issues/5519#issuecomment-636328380, fruit avoidance in the HUD must be on on the combine, you have it off for the combine on field 32:
![image](https://user-images.githubusercontent.com/2379521/83351909-9355d680-a30d-11ea-8d1d-c1c6b7057e79.png)
Other combines have it on, that's why those work and this one does not.

2. This crop you left here:
![image](https://user-images.githubusercontent.com/2379521/83351949-cb5d1980-a30d-11ea-8fff-27d5c5fc0686.png)
prevents the pathfinding to find a path from that position, I won't go into the details why. If you hadn't left that there, or, would just moved your tractor forward a few meters (and set fruit avoidance for the combine, see above) it'd have worked.

**Comment by answermanitou** [comment]
> @answermanitou so, I looked at your savegame.
> 
> 1. as I told you already in [#5519 (comment)](https://github.com/Courseplay/courseplay/issues/5519#issuecomment-636328380), fruit avoidance in the HUD must be on on the combine, you have it off for the combine on field 32:
>    ![image](https://user-images.githubusercontent.com/2379521/83351909-9355d680-a30d-11ea-8d1d-c1c6b7057e79.png)
>    Other combines have it on, that's why those work and this one does not.
> 2. This crop you left here:
>    ![image](https://user-images.githubusercontent.com/2379521/83351949-cb5d1980-a30d-11ea-8fff-27d5c5fc0686.png)
>    prevents the pathfinding to find a path from that position, I won't go into the details why. If you hadn't left that there, or, would just moved your tractor forward a few meters (and set fruit avoidance for the combine, see above) it'd have worked.

About 1st. Is it can provide that harvester doesn't make a pocket for unload or move back and side from current row even the pipe on the cleared side?
About 2 that was begin of harvester course and why its don't cleared I don't now.

But thanks for your answers.
@pvaiko give me comment about upper questions
