### ISSUE TITLE
Can't find Harvester/ switch modes

### ISSUE THREAD

**Issue by paul-dotcom** [Courseplay/courseplay#5524]
Hi, my problem is that i can't assign a harvester manually in mode3 (pictures). 
![fsScreen_2020_05_30_19_40_47](https://user-images.githubusercontent.com/66199602/83348329-cd35d580-a32b-11ea-8f50-54d46ff5929c.png)
![fsScreen_2020_05_31_10_41_51](https://user-images.githubusercontent.com/66199602/83348332-ceff9900-a32b-11ea-8ddb-aa0d1e3bde59.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4707357/log.txt)

**Comment by Tensuko** [comment]
Mode2* and whats with the can't switch modes ?

Why not check the Box of the 9000 ?

More details pls....

Also throw out this:
Error: Invalid mod name 'AIVehicleExtension-master'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

Not sure if that Mods creates any issue with CP but I would try to throw this one out too:
Load mod: FS19_AIVehicleExtension (Version: 0.0.7.0) (Hash: 4f41baa99f9d4c49b33c5ab4d4786a4e)

Sidenote:
The 9000 have a wrong sitting proximity sensor so it won't work with Mode2 yet.
Read #5272 about it.

**Comment by paul-dotcom** [comment]
Yes, i already tried checking the box... doesn't matter, wont work.
The issue with switching modes: As you can see in picture one, you aren't able to change to the other mode where you can manually choose a Harvester. 
![fsScreen_2020_05_31_14_54_23](https://user-images.githubusercontent.com/66199602/83352834-bfde1280-a34e-11ea-82e4-7a1ff7e3c7ac.png)
normally it should look like this

**Comment by Tensuko** [comment]
Thats the old mode2 and does not exist. The box is checkable. If not then there is something wrong on your side.

**Comment by Jythier** [comment]
Paul, is the combine being driven by Courseplay too, or is it a helper or manual?

**Comment by paul-dotcom** [comment]
yeah i noticed it by myself while reading the dev-post.. i tried to drive the combine manually... so thanks for your help guys
