### ISSUE TITLE
click to swich enhancement

### ISSUE THREAD

**Issue by Bobster82** [Courseplay/courseplay#5527]
Hi @pvaiko , can u remove "vehicle.cp.mouseCursorActive and vehicle.cp.hud.show" from line 24 in input.lua?

The reason is that when the hud is hidden and I have a mouse cursor (AD) then i still would like to switch vehicles when clicked on them. I tested it myself and when removed, i can switch without the hud being shown... thanks in advance!

**Comment by Tensuko** [comment]
I did read it and we discussed about it, but not priority... will think about that.

**Comment by Bobster82** [comment]
Ah ok, thanks for the reply.
Is there anything I can help out with?
