### ISSUE TITLE
Combination baler not unloading wrapped bales

### ISSUE THREAD

**Issue by Chalky7625** [Courseplay/courseplay#5528]
Using the latest version of courseplay combination balers aren't unloading the wrapped bale once completed. 

The course then has to be stopped and it unloaded manually.

**Comment by Tensuko** [comment]
Logfile ?

**Comment by Chalky7625** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4707992/log.txt)

**Comment by Lustiger-Hubi** [comment]
Werfe erst mal die Mods mit den Error raus!

**Comment by Tensuko** [comment]
2020-05-31 11:42 Error: Running LUA method 'update'.
2020-05-31 11:42 C:/Users/Andrew/Documents/My Games/FarmingSimulator2019/mods/FS19_VehicleExplorer/VehicleSort.lua:1907: attempt to index a nil value
Wenn das mal nicht der Grund für den Fehler ist....
Mods aufräumen wie @Lustiger-Hubi schon sagte und dein VehicleExplorer mal rauswerfen, dann noch mal probieren...

**Comment by Chalky7625** [comment]
First bale unloaded but second one won't auto unload.

**Comment by Chalky7625** [comment]
After a bit of messing around. Bales still dont unload automatically. However, I found if I toggle "combine self unload" off and on then the bale will unload. 

Not sure if that is of any help.

**Comment by Tensuko** [comment]
Can you tell me wich baler you use, as the normal Kuhn one doesn't have any Issue.

**Comment by Chalky7625** [comment]
The one from the Claas DLC

**Comment by Tensuko** [comment]
Can't reproduce, could be this mod Load mod: FS19_baler_addon (Version: 2.0.0.1) (Hash: 429bd29203e4b6d7acbf61ad7d159e33) , but also update your CP as I said.

**Comment by Chalky7625** [comment]
Will try that, CP version has been updated to latest

**Comment by Chalky7625** [comment]
Removed baler addon, latest CP version. 

Still happening. Works for a while then won't unload

**Comment by Tensuko** [comment]
well.... can't reproduce... I am very sure the reason was the baler mod, but some configuration was left on the baler. When such things come up, a tool reset could help.
![fsScreen_2020_07_20_17_03_08](https://user-images.githubusercontent.com/27344744/87953105-eb59bf80-caaa-11ea-9590-c34c0c630e06.png)
