### ISSUE TITLE
Suggestion: Clear course from generator GUI 

### ISSUE THREAD

**Issue by enderwiggin07** [Courseplay/courseplay#5529]
Maybe there's a way to already do this and I don't know it.   But generally right now if I generate a course that I don't really like, I accept the course out of the generator map GUI, clear the course from the normal courseplay GUI, then go back into course generation to try again.   It would be nice to be able to clear the generated course from the map gui.

**Comment by Tensuko** [comment]
Way to complicated.... Just click generate again after you chamged a value...

**Comment by enderwiggin07** [comment]
That's actually perfect, I didn't realize the generation would run a second time after changing values, I've been closing the entire GUI to clear the course then try again.  

If you ever want help on updating the manual to be more current and complete, I'd certainly be willing to spend some time writing on it if I could get access to yours and other dev's knowledge on how the certain features work.

**Comment by Tensuko** [comment]
Wevalwaysblook for someone who gets our website to an actual state if your know how to work with github webpage that would be great.

**Comment by enderwiggin07** [comment]
I'm not familiar right now but I'll start reading about it then get back to you.
