### ISSUE TITLE
Error: Running LUA method 'mouseEvent

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#5532]
Folgendes habe ich gemacht!
Habe mit Drescher AxialFlow9240SeriesByStevie einen Kurs generiert.
Dann habe ich den Abfahrer einen bereits eingefahrenen Kurs zugeordnet.
Dann habe ich den Abfahrer den Drescher AxialFlow9240SeriesByStevie zugeortnet
das ging beim ersten mal nicht und da hat er den Fehler rausgeworfen!
Daraufhin habe ich den zweiten Abfahrer eingestellt, dieser fährt aber nicht zu Drescher
obwohl ich diesem den gleichen Drescher zugewiesen habe.
![fsScreen_2020_05_31_22_33_00](https://user-images.githubusercontent.com/48583507/83362210-c345be00-a38f-11ea-8fef-1ffff6905ca7.png)
![fsScreen_2020_05_31_22_33_37](https://user-images.githubusercontent.com/48583507/83362213-c640ae80-a38f-11ea-89a2-d32466adcc9b.png)
![fsScreen_2020_05_31_22_33_59](https://user-images.githubusercontent.com/48583507/83362217-c8a30880-a38f-11ea-812a-abeca24c0ba1.png)
![fsScreen_2020_05_31_22_34_04](https://user-images.githubusercontent.com/48583507/83362218-ca6ccc00-a38f-11ea-85a6-55f7c36fa958.png)
![fsScreen_2020_05_31_22_34_47](https://user-images.githubusercontent.com/48583507/83362220-cc368f80-a38f-11ea-83c0-c8a5200c0109.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4708382/log.txt)
 Ps in meiner Log habe ich kein "callstack" zumindest habe ich kein gefunden!
Ich hoffe ich konnte helfen
Danke

**Comment by Tensuko** [comment]
Mal einen anderen Drescher probiert ? Am besten Vanilla.

**Comment by Lustiger-Hubi** [comment]
Hallo Jungs
So jetzt habe ich mal ein Lexon 795 genommen!
Ein Error: Running LUA method 'mouseEvent wirft er nicht aus!
Aber der Abfahrer fährt nur einmal zu Drescher! dann kann er kein Drescher mehr finden!

Sollte ich hier was falsch gemacht haben möchte ich mich hiermit entschuldigen!
Ich hatte verstanden, dass ich ein neues issue (was das auch immer ist) erstellen soll!
issue verstehe ich mit, eine neue Fehlermeldung erstellen mit Log

PS ich bin 67 Jahre alt
Sorry Sorry Sorry
[log.txt](https://github.com/Courseplay/courseplay/files/4711242/log.txt)

**Comment by Tensuko** [comment]
Das neue Issue war Gold richtig, da es im anderen Issue um einen ganz anderen Fehler ging.

Vom Bild er sieht es schon mal gut aus, das Feld musst du nicht Auswählen, das ist nur dazu da um den Drescher in der Liste besser zu finden, fals man mehrere hat.

Wenn du jetzt im CP HUD bei den Einstellungen noch die Zahlen (Debugchannel) 4 7 12 und 14 grün (einschalten) machen kannst und dann noch mal versuchst den Drescher ab zu tanken, dann können wir schauen warum er jetzt nicht zum Drescher fahren will. (Ein Bild mit den Debugchannel an dazu hilft auch).

**Comment by Lustiger-Hubi** [comment]
So, habe 4; 7; 12; und 14 im Debugchannel am Drescher eingestellt
Wie ich sehen konnte, wurden diese Debugchannel auch autom im Abfahrer übertragen.
Der erste Abfahrer für normal ab der zweite leider nicht!
Auch lässt der Drescher an den Rändern Früchte stehen!
Bilder 1 zweiter Abfahrer fährt aber nicht zum Drescher
![fsScreen_2020_06_01_14_18_44](https://user-images.githubusercontent.com/48583507/83412432-5c211b80-a41a-11ea-9cf3-9e50a935d79a.png)
Bild 2 zeigt oben stehen Früchte
![fsScreen_2020_06_01_14_58_56](https://user-images.githubusercontent.com/48583507/83412539-896dc980-a41a-11ea-91dc-3e70722efd1e.png)

Hab ich alles richtig gemacht??
Danke

**Comment by Lustiger-Hubi** [comment]
So habe 6.02.00026 probiert!
Der erste Abfahrer fährt den Drescher ins Schneidwerk
Bild
![fsScreen_2020_06_01_16_16_28](https://user-images.githubusercontent.com/48583507/83418567-1b2e0480-a424-11ea-9d38-df562019ee44.png)
Der zweite Abfahrer findet kein Drescher auch wenn ich auf Feld 13 stelle!
Bild
![fsScreen_2020_06_01_16_14_58](https://user-images.githubusercontent.com/48583507/83418842-81b32280-a424-11ea-8bf6-a1a9ce93336c.png)
![fsScreen_2020_06_01_16_19_01](https://user-images.githubusercontent.com/48583507/83418712-54ff0b00-a424-11ea-891a-9f5588406141.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4711775/log.txt)
Sorry, Ich glaube es ist schlimmer geworden /oder nicht besser
Was soll ich machen?

**Comment by pvaiko** [comment]
Auto offset einstellen. 
Mehrere abfahrer sind noch nicht unterstützt.

**Comment by Lustiger-Hubi** [comment]
Was wo wie wer?
wo stelle ich den Auto offset ein?

**Comment by Tensuko** [comment]
![autooffset](https://user-images.githubusercontent.com/27344744/83422678-31d75a00-a42a-11ea-953a-33a5303120e4.png)
 und eventuell hilft dir das hier weiter:
https://www.youtube.com/watch?v=PiUWD8ki8l4&t=4s

**Comment by Lustiger-Hubi** [comment]
Werde ich versuchen!

**Comment by Lustiger-Hubi** [comment]
Neuer Test!
Habe jetzt nochmal ein neues Spiel angefangen!
Dann habe ich den Drescher FS19_AxialFlow9240SeriesByStevie (mit Vorgewende) fahren lassen!
Dazu erstmal nur ein Abfahrer (FendtPack_OY mit KronePack_OY) benutzt! 
(bis das Vorgewende fertig war!
Nach dem Vorgewende habe ich einen zweiten (Gleicher Art) hinzugeführt!
Und siehe da, alles läuft SUPER!

![fsScreen_2020_06_02_17_51_14](https://user-images.githubusercontent.com/48583507/83542409-3750a500-a4fb-11ea-8b3a-4ac9ec5a9004.png)

Danke EUCH für die mühe
