### ISSUE TITLE
Häcksler abfahrer betankung seite

### ISSUE THREAD

**Issue by Paladose** [Courseplay/courseplay#5535]
Hi hab jetzt neuerdings das problem das ich beim Häcksler nicht mehr wählen kann auf welcher seite er abladen soll da ich meine strecken immer mit dem abfahrer links gemacht habe diese macht er aber nicht mehr er bleibt dahinter und wird dann nicht gefüllt.

**Comment by Tensuko** [comment]
Keine log keine Bilder und man kann es nicht wählen weil er das automatisch macht im ersten vorgewende bleibt er immer hinter dem Häcksler.

**Comment by Paladose** [comment]
Komisch das ich kein vorgewende fahre  das ist doch müll vorher war das besser mit selbst auswählen. Na dann muss ich halt wieder auf ne alte version umsteigen schade

**Comment by Tensuko** [comment]
> das ist doch müll

Gern geschehen...

**Comment by TinyCrocodile** [comment]
Bei mir funktoniert der neue mode 2 fast perfekt. Es ist genial, wie das zusammenspiel zwischen abfahrer und häcksler oder Drescher funktioniert.  Besonders, wie sie sich gegenseitig platz machen. Also Danke für die viele Arbeit, die ihr hier reingesteckt habt. 

Ein guter startpunkt um den neuen mode2 zu lernen ist beispielsweise #5272 zu lesen. Das Beispielvideo  finde ich gerade nicht. Kommt noch.

**Comment by Paladose** [comment]
Ja danke hab jetzt alte version wieder drauf jetzt läuft wieder alles
