### ISSUE TITLE
Maneuver of the forage harvester

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#5537]
I encountered a small problem: during the forage harvester maneuvers that, coming out of a row, tries to enter the next one, when it lowers the bar in front it accelerates too much and ends up not picking up a small piece of crop

video: [Farming Simulator 19 2020-06-01 10-50-57.zip](https://github.com/Courseplay/courseplay/files/4710348/Farming.Simulator.19.2020-06-01.10-50-57.zip)
photo: ![Farming Simulator 19 01_06_2020 10_51_52](https://user-images.githubusercontent.com/59969508/83393133-92e53a80-a3f6-11ea-8a8a-0e3d13fb9b63.png)
![Farming Simulator 19 01_06_2020 10_59_11](https://user-images.githubusercontent.com/59969508/83393773-a513a880-a3f7-11ea-9f62-a7e0833ebd55.png)

Log:[log.txt](https://github.com/Courseplay/courseplay/files/4710349/log.txt)

**Comment by Tensuko** [comment]
Lower tool early is active ?

**Comment by 0Pietro20** [comment]
Yes

**Comment by 0Pietro20** [comment]
at least I think so

**Comment by Tensuko** [comment]
Can't reproduce this. Looks good for me with Vanilla Tools.
Play arround with raise and lower option, both of yours looks like raise and lower early, I would not raise it early.

**Comment by TinyCrocodile** [comment]
Also since we can adjust headland overlap this can be changed
