### ISSUE TITLE
Abladen und abfahren von Rüben

### ISSUE THREAD

**Issue by Bikeslife** [Courseplay/courseplay#5538]
Wenn der Holmer Terra Dos voll ist, wird der abfahrer gerufen. Dieser fährt auch los, bleibt aber links hinter dem Holmer mit einigen Abstand stehen und färhrt nicht weiter. Er wird nicht blockiert und es erscheint auch keine Fehlermeldung.

**Comment by Bikeslife** [comment]
Dies passiert allerdings nicht immer. Ich hatte es beim ersten Vorgewende.

**Comment by Tensuko** [comment]
#5272 lesen bitte danken gern geschehen :)
