### ISSUE TITLE
Vehicle Specific Settings - Working width plus and minus per meter

### ISSUE THREAD

**Issue by Dennizzzzz** [Courseplay/courseplay#5540]
Using version 6.2.00025.dev, the plus and minus sign on the 'Vehicle Specific Settings' of the setting Working Width decrease and increase by 1 m only, So if it is set to 9.1m, the minus button makes it 8.1m, and the plus button makes it 10.1m.

P.S. i'm using the dutch version, so maybe the screen and settings title I mentioned above are slightly different in English.

![2020-06-01 20_22_03-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/83440962-111cfd80-a446-11ea-9465-c4e9885bfadb.jpg)

**Comment by Tensuko** [comment]
I think it was hold ctrl then scroll up/down.

**Comment by Tensuko** [comment]
Tested, it only does meter per meter...

**Comment by pvaiko** [comment]
Duplicate of #5458
