### ISSUE TITLE
[Suggestion] Tire tracks/Crop destruction

### ISSUE THREAD

**Issue by masneoquil** [Courseplay/courseplay#5541]
Hello Guys.

I've noticed that whenever an AI worker (default, CP, AD) is in control of any vehicle, they fail to leave any tire tracks behind.
Is this has something to do with the fact that crop destruction is turn off when the AI is working?
If that is the case, is it possible to have crop destruction as an option?
Maybe is built in in the default AI and there is nothing you can do about it. In that case, not a big problem.

**Comment by masneoquil** [comment]
Sorry, to ask again.
Is in fact that crop destruction is  off the reason for no tire tracks? Cause if it is not, maybe this suggestion has no point

**Comment by SirAlbertL** [comment]
Could one of you show me the areas in the script that turns off Crop destruction and tracks so I can alter the script for myself to allow both. While CP is active?

**Comment by Tensuko** [comment]
The cases where we drive through the crops are still to unreliable (sadly) so we won't enable crop destruction for this FS version.
