### ISSUE TITLE
[Advice] shovel mode

### ISSUE THREAD

**Issue by answermanitou** [Courseplay/courseplay#5543]
Hello
I can't find instructions about shovel mode in Cp. @Tensuko @pvaiko please give few recomendarions about this mode. What must be enabled in hud and advanced settings etc. 
One is I remember that in this mode must be three waiting points.
Also want to ask how it will be works in a wide silage silo with basic implements for wheel loader. I mean that silage silo has 15 meters width and the shovel is 3m width. 
Great thanks

**Comment by Tensuko** [comment]
![Mode9](https://user-images.githubusercontent.com/27344744/83493644-5d535680-a4b5-11ea-84aa-77d5062417fa.png)

**Comment by answermanitou** [comment]
What about pathfinding, AI for revers. This must be enabled or not?

**Comment by Tensuko** [comment]
Got nothing to do with this, it is just for turns and Mode9 doesn't have any turn.

**Comment by answermanitou** [comment]
> Got nothing to do with this, it is just for turns and Mode9 doesn't have any turn.

Another words -- settings in advanced such as pathfinding, Ai, and reverse its just for mode 2 and unloaders?

**Comment by Tensuko** [comment]
No....
Pathfinder in Turns is for all kind of Mods with secific tools.... Not even Mode2 as Mode2 doesn't have any turn...

**Comment by Tensuko** [comment]
Should be clear now...
