### ISSUE TITLE
Search Combine on field appearing wrong information

### ISSUE THREAD

**Issue by nirakan** [Courseplay/courseplay#5544]
Goodday sir. We have a problem with information text on manage combine tool for unload harvester.

In this case I'm use an 'Farm of Madison country' a field 90 and field 91 is inside a same land.

Screenshot : https://drive.google.com/drive/folders/1_0JHqdTFyehoZkJM1g92LlKOwDCsk2gp?usp=sharing

**Comment by Tensuko** [comment]
Did you get it to work ?

**Comment by Tensuko** [comment]
Closed due to inactivity, check https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ and #5272 for Mode2 Information.
