### ISSUE TITLE
Slurry wont auto un/load with TSA30000 at biogas

### ISSUE THREAD

**Issue by djnekkid** [Courseplay/courseplay#5545]
Hello there.

I've tried to use the "grain run" (mode1?) with the mentioned 'stock' slurry tank and a MAN truck.
I can select mode1, and select slurry and 100% in the 'options' for that mode.

However, when i run the course, it will neither load at the farm, nor unload (if i load manually) at the biogas plant. (Felsbrunn map)
Anything i'm doing wrong, or is this some sort of bug?
Doing 'the same' with manure (from the 'multifruit silo') works perfectly, as well as other grains to the different vendors. Albeit with a bulk trailer.

Note:
1. When i stop the "slurry run", it defaults back to 'transport mode', and not 'mode1'.
2. I do have some mods, but both of theese are stock stuff. and its not HEAVILY modded.

**Comment by Tensuko** [comment]
And where is the logfile ?
Screenshots of the Course at loading point and unloading point ?

**Comment by djnekkid** [comment]
start:
![image](https://user-images.githubusercontent.com/65364380/83570726-d9d24d80-a526-11ea-9717-85627c0b4699.png)

End:
![image](https://user-images.githubusercontent.com/65364380/83570752-e35bb580-a526-11ea-8bfc-c314f7f3fe6e.png)
Its not shown here, but the truck is stopped, and the "unload slurry" bar is active in the bottom (Press I to unload type of thing)

And the "mode 1" is now gone. If i start the course, and stop it again, its back
![image](https://user-images.githubusercontent.com/65364380/83571044-5c5b0d00-a527-11ea-98b2-5c6721438170.png)

Here is the course:
![image](https://user-images.githubusercontent.com/65364380/83571078-67ae3880-a527-11ea-9170-9c4ff13e29cf.png)


Logfile: (expire in a couple of months)
https://pastebin.com/SjzxYZ5A

**Comment by djnekkid** [comment]
And  by the way, thank you for  GREAT mod! Especially the 6.02 is HEAPS and BOUNDS better then 6.01.

**Comment by Tensuko** [comment]
I will have a closer look at it tmr.
For your startpoint:
It is better when the 1st waypoint after the start is more far away from start, so drive a straight line after start record and then do the turn. Make sure to start record when trailer is in trigger and stop a few meters before trigger. For the unload and mode change I have to check whats going up.

**Comment by djnekkid** [comment]
With regards to the 'start point':
the "refill" thing in the "top left help window" triggers, AND i've tested it on another farm as well, where the angle is not so acute on the exit, and with same result.

Still wierd that it wont empty in the biogasplant?
The course were created with autodrive (on the roads and a the biogas plant), and the "unload" function with autodrive works as intended.

**Comment by djnekkid** [comment]
did a sanity-test, with this track:
![image](https://user-images.githubusercontent.com/65364380/83574800-72200080-a52e-11ea-90cb-e04095a175df.png)

![image](https://user-images.githubusercontent.com/65364380/83574866-9e3b8180-a52e-11ea-9d1e-b5c4d7ab81c9.png)

![image](https://user-images.githubusercontent.com/65364380/83574879-a85d8000-a52e-11ea-854a-b82d1fbe7c32.png)

The truck is "out of place" in the picture, but just to show proportions

And it does not fill as i would think, This would FOR SURE work no?

I've made a bunch of tracks on silos, and they work 100% all the time.


And at the Biogas i did this sanity-test:
![image](https://user-images.githubusercontent.com/65364380/83575414-b3fd7680-a52f-11ea-8ce8-113e91de8905.png)

![image](https://user-images.githubusercontent.com/65364380/83575503-ec9d5000-a52f-11ea-8178-38ac2c08ab08.png)

However, it will not stop to unload its load.

Is perhaps this trailer not really ment for this? But it seems to be a pure transport trailer, as it dont have any form of sprayer or sprayer attachment

**Comment by Tensuko** [comment]
Well... yea its a bug, I just tried it, will see if I can fix it...

**Comment by Tensuko** [comment]
Should be fixed with .00064 basically since Trigger Rework and the fixes...
