### ISSUE TITLE
Bug in Coursegenerator - Seeding with 2 drivers

### ISSUE THREAD

**Issue by Namajo** [Courseplay/courseplay#5546]
Hello,

sice version 6.02.00025, the course generator is Buggy on generating courses with 2 identical machines. The outer driver works fine until the last side of the headland. it skips it on the half an starts with the inner course. The secound driver skips the headland completely. I tryed to mark the driven ways in the "CoursGenBug" pic.
![CourseGenBug](https://user-images.githubusercontent.com/64135697/83554667-6f60e380-a50d-11ea-834a-2c1893b01773.png)
there is also a little hook at the beginning of all generated courses wich makes the driver do a very unclean start.
![StartHook](https://user-images.githubusercontent.com/64135697/83554673-712aa700-a50d-11ea-8c3d-d3ac4d9ae05f.png)

I'm working with 2x Class Xerion 5000 and 2x Amazone Condor 15001

**Comment by Tensuko** [comment]
Do not generate a course at a corner, do it on the side of the field.
if you don't want to drice there, use choose start point on map.

**Comment by Namajo** [comment]
Ich habe gerade gesehen, dass ihr hier eigentlich auch Deutsch sprecht. Daher mache ich jetzt auch mal auf Deutsch weiter um Missverständnisse zu vermeiden.

Ich habe jetzt einen Kurs an der Seite des Feldes gestartet. Das war aber nicht von Efolg gekrönt und es sieht nun wie folgt aus:
![fsScreen_2020_06_02_21_10_11](https://user-images.githubusercontent.com/64135697/83559793-755ac280-a515-11ea-924c-5c3652038022.png)

**Comment by Namajo** [comment]
Korrektur. Der kleine Haken ist weg. Aber ordentlich gefahren wird der Kurs noch immer nicht.

**Comment by pvaiko** [comment]
Ich kann das nicht reproduzieren. Hast du ein Log mit Debug Channel 7?

**Comment by Namajo** [comment]
Das Log ist hier: [https://gist.github.com/Namajo/e5e148677eec8d1a3137dc4e48670901](https://gist.github.com/Namajo/e5e148677eec8d1a3137dc4e48670901)

**Comment by Namajo** [comment]
Sorry für die späte Antwort. Schlaf und Arbeit kamen dazwischen ;)

**Comment by pvaiko** [comment]
Sorry, keine Ahnung, nichts interressantes in der Log, bei mir funktioniert es ohne Probleme:
![image](https://user-images.githubusercontent.com/2379521/83673310-3b350380-a59d-11ea-863c-1ca1c65217c1.png)

**Comment by pvaiko** [comment]
Nein, du kannst vielleicht mit einem frisch gekauften Traktor/Sähmaschnie ausprobieren.

Und es passiert wirklich nur ab 6.02.00025? Kannst mit 24 testen?

**Comment by Namajo** [comment]
Also es passiert seit ich von 6.02.00024 auf 6.02.00025 upgedatet habe. Seither aber mit allen Versionen die ich getestet habe ...24/...23/...22

**Comment by pvaiko** [comment]
Komisch. Kannst du dein Savegame und Kurs Ordner hier posten?

**Comment by Tensuko** [comment]
EasyDevControl -> Fahrzeug Zurücksetzen -> Standart
Ist dann wie ein frisch gekauftes.

**Comment by Namajo** [comment]
Also. Ich habe jetzt einen neuen Tracktor und eine neue Sämaschine gekauft und ... voila ... es geht. Und wenn ich nicht in einer Ecke starte, dann macht er auch keinen Haken.

PS: Ich bin bisher immer in den Ecken gestartet und das war auch nicht ein Problem. Aber seis drum. Wenn das alles ist, kann ich damit leben ;)

[FarmingSimulator2019.zip](https://github.com/Courseplay/courseplay/files/4725731/FarmingSimulator2019.zip)

PPS: EasyDevControl werde ich testen.

**Comment by Namajo** [comment]
Das Zurücksetzen des Fahrzeugs mit EasyDevControl hat ebenfalls funktioniert.
Ich danke euch vielmals.

PS: Ich hab's noch gar nicht gesagt. Es ist ein erstklassiges Addon und ihr macht wirklich gute Arbeit. Ich danke euch dafür.

**Comment by Namajo** [comment]
Ich nutze die Gelegenheit und schließe den Fall. Ihr habt den Fehler ja behoben :)
