### ISSUE TITLE
Refill fertilizer does not work unattended

### ISSUE THREAD

**Issue by Dennizzzzz** [Courseplay/courseplay#5547]
Using version v6.02.00026. I want to spray a field with fertilizer. And if it's empty, it should refill. But it only refills when i'm in the tractor with the AI. If I'm not in the tractor, the machine will not refill at the refilling point.

**Comment by Tensuko** [comment]
logfile ? ....... https://github.com/Courseplay/courseplay/wiki

**Comment by Dennizzzzz** [comment]
Sorry :-(

[log.txt](https://github.com/Courseplay/courseplay/files/4719591/log.txt)

**Comment by Dennizzzzz** [comment]
Map is Bjornholm

Mods:

![2020-06-02 22_46_46-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/83568399-519e7900-a523-11ea-8ccd-27d4b47ab77e.jpg)
![2020-06-02 22_47_01-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/83568403-52370f80-a523-11ea-88a9-eb9b7e047a99.jpg)
![2020-06-02 22_47_21-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/83568404-52cfa600-a523-11ea-9433-37dfa371fae3.jpg)
![2020-06-02 22_47_33-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/83568406-52cfa600-a523-11ea-966f-9445a0362971.jpg)
![2020-06-02 22_47_43-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/83568408-52cfa600-a523-11ea-8c91-904da0091c7a.jpg)

**Comment by Tensuko** [comment]
Mods are all listed in teh log.txt :)
You have to follow a very important Rule for every FS Version:
Only one Map in Mods Folder.
Put the not used one somewhere else.

And there we have the Problem:
Load mod: FS19_manureSystem (Version: 1.0.0.0) (Hash: 1c511663bbdd1c9e1acb465296dc382f)
Get the newest ManureSystem Version from GitHub (google it) and it should work.

The rest of your logfile looks fine.

**Comment by Dennizzzzz** [comment]
Thanks very much for the quick response.

**Comment by Dennizzzzz** [comment]
Just downloaded the newest version of ManureSystem, and removed all unused map mods as you described. Tested it, and it works.
