### ISSUE TITLE
Mode 8 wants to start on 1st waypoint after save reload.

### ISSUE THREAD

**Issue by candymant** [Courseplay/courseplay#5549]
If i do more then 2 liquide transports water and biogas then i can not reload my digestaat or refill my sprayers has this still somting to do with manuresystem or is this a courseplay problem.

Another problem  is if i restart my savegame the liquid transport course doesnt  continue from nearest waypoint but always want to start from start point whatever i choose  nearest waypoint , first waypoint ,next waypoint. Always return to startpoint of the course.

**Comment by Tensuko** [comment]
Can you add a logfile anyway ?

**Comment by candymant** [comment]
I wil do that this evening i am at work now.

**Comment by candymant** [comment]
I will explain it a little better. If a liquid transport is filling up and a transport course is filling in a global company trigger if not enough then it will stay filling up. then I can not fill up my sprayer. if I stop the transport course then I can fil my sprayer up. If a transport course and a liquid transport course are active then I get in the help window of the sprayer stop filling up. If I cancel the transport mission then in the help window appears fill sprayer up or begin filling.
[log.txt](https://github.com/Courseplay/courseplay/files/4726124/log.txt)

**Comment by candymant** [comment]
the liquid transport always returns to start point if a save game is loaded.

**Comment by Tensuko** [comment]
Short Question: Do you play in MP ?

**Comment by candymant** [comment]
no

**Comment by candymant** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4739192/log.txt)

**Comment by Tensuko** [comment]
I need to try this out, tho its a bit hard to get that situation done.
Give me some time for this.

**Comment by candymant** [comment]
hey have you already reproduced or isnt it possible?
