### ISSUE TITLE
Waiting timer not working

### ISSUE THREAD

**Issue by Njakkata** [Courseplay/courseplay#5551]
Hi!

Im trying to use a Auger Wagon in mode 2 to go to a combine and unload and then to a trailer to unload. Ive set up a course with the Auger wagon to go next to the trailer using the Park (P) and setting a waiting time for 30 sec - 1 min. But the Auger wagon stays put at (P) and dosent continue after the waiting time has passed. 

What am I doing wrong?

**Comment by Tensuko** [comment]
Read #5272 and this https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ
