### ISSUE TITLE
The truck doesn't go to the combine

### ISSUE THREAD

**Issue by Tocik** [Courseplay/courseplay#5552]
Combine after filling the hopper requires unloading, and the truck for some reason does not go.
![3](https://user-images.githubusercontent.com/65189100/83656275-025e5400-a5c8-11ea-8c06-8802899d0d05.jpg)
![1](https://user-images.githubusercontent.com/65189100/83656285-038f8100-a5c8-11ea-8520-41219f32709b.jpg)
![2](https://user-images.githubusercontent.com/65189100/83656286-038f8100-a5c8-11ea-8fef-c156feb5e5b4.jpg)

 If you call it manually, it will arrive without problems.
![4](https://user-images.githubusercontent.com/65189100/83656300-08eccb80-a5c8-11ea-9c45-1f334230fdfc.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/4724397/log.txt)

He was waiting for 10 hours.
Version v6. 02. 00026

**Comment by Tensuko** [comment]
No Idea what this does: FS19_GameExtension

Also this is a bit strange:
Load mod: FarmingTablet (Version: 2.0) (Hash: 3e69ba25090b98360fd459597923d8fc)
Error: Unsupported mod description version in mod FarmingTablet
Load mod: FarmingTablet_APP_Animalstatus (Version: 1.0.1) (Hash: e0977f065cc48f4471b26535bbe355e0)
Error: Unsupported mod description version in mod FarmingTablet_APP_Animalstatus
Load mod: FarmingTablet_APP_FabrikscriptExtension (Version: 1.0) (Hash: 224a06cba7e922e9e752b1a0b24a82fe)
Error: Unsupported mod description version in mod FarmingTablet_APP_FabrikscriptExtension

**Comment by Tocik** [comment]
> Понятия не имею, что это делает: FS19_GameExtension
> 
> Кроме того, это немного странно:
> Load моды: FarmingTablet (Версия: 2.0) (Hash: 3e69ba25090b98360fd459597923d8fc)
> Ошибка: неподдерживаемая версия Описания мод в модах FarmingTablet
> нагрузки мод: FarmingTablet_APP_Animalstatus (Версия: 1.0.1) (Hash: e0977f065cc48f4471b26535bbe355e0)
> Ошибка: неподдерживаемый мод версия описания в моде FarmingTablet_APP_Animalstatus
> Загрузить мод: FarmingTablet_APP_FabrikscriptExtension (Версия: 1.0) (Hash: 224a06cba7e922e9e752b1a0b24a82fe)
> Ошибка: неподдерживаемая версия описания мода в моде FarmingTablet_APP_FabrikscriptEx

This is a mod for additional productions run by Global Company.
If the route of the truck is reloaded from the starting point, it goes to load without problems, but only once. It doesn't go to the next upload.

**Comment by Tocik** [comment]
> No Idea what this does: FS19_GameExtension
> Game Extension script version 0.4.4.1 for Farming Simulator 2017 (v1.5.3. 1)
The script expands the game's features. Enable the settings window by pressing I.

Here are just some features of the script:
- screenshot mode
- increasing the distance to the object that can be taken
- increase the player's strength to lift objects
