### ISSUE TITLE
Can't append multiple courses correctly

### ISSUE THREAD

**Issue by cosmin-margarit** [Courseplay/courseplay#5554]
Hello, I'm trying to load multiple courses in one to work multiple fields at once with the same machine. I have set up AD routes to my fields, and CoursePlay knows how to use them but when trying to go for one field to the other it breaks.

In picture one, I load an AD route in CP to go to field 24 and it uses the AD route as expected, then, I append the CP fieldwork course that works again as expected, it starts from field 24 where the AD route finished and works the field. Now, when I try to append another AD route to field 19, CP doesn't use as a starting point the Stop position in the last course appended (field 24 as the last field worked) and it wants to go in a straight line to the very first starting point from where it all begun (as seen in picture 3).  
And then from there, it routes to field 19, and if I append again a course to work field 19 works ok from the end of the AD route as seen in picture 4.

Is it possible that the appended courses start from the ending point of the previous course? so it all can be chained together with AD routes and fieldwork?

How does exactly CP use the AD routes network, from a developer perspective?

Notes: 
- I have Return to first point option deactivated in CP

- I have an AD course to follow from the field (AD can go anywhere from the middle of the field and so can CP using the AD course from the field, but not when chaining to a ended CP course)

Thanks! 

![image](https://user-images.githubusercontent.com/32977353/83668463-ac45dc80-a5d8-11ea-8990-b30cc97409eb.png)
![image](https://user-images.githubusercontent.com/32977353/83668598-e2835c00-a5d8-11ea-9213-bb8b01e49be0.png)
![image](https://user-images.githubusercontent.com/32977353/83668634-f4fd9580-a5d8-11ea-8e2b-81fdf4f6bab5.png)
![image](https://user-images.githubusercontent.com/32977353/83668676-06df3880-a5d9-11ea-96a5-ece5280bd912.png)

**Comment by Tensuko** [comment]
This is not intended.
