### ISSUE TITLE
No combine in reach

### ISSUE THREAD

**Issue by IWo112** [Courseplay/courseplay#5555]
Hi.

I have issue where my CP is just not working. I made simple track to silo and to field hired worker on combine on the field and its just blinking no combine in reach and doing nothing....last time i played the game it was like november or december it was still the only singleplayer CP and it workd superb.
I have 250+ mods but i turned them off Its basic map with just CP.

Any ideas what could made this problem? Thx.
![issue](https://user-images.githubusercontent.com/66414471/83742319-91677c80-a659-11ea-9472-ed886e2eea84.png)
![issue 1](https://user-images.githubusercontent.com/66414471/83742349-9a584e00-a659-11ea-8dfe-53f6aeeca372.png)
![issue 2](https://user-images.githubusercontent.com/66414471/83742357-9cbaa800-a659-11ea-9e48-c91d88931d66.png)
![issue 3](https://user-images.githubusercontent.com/66414471/83742371-9f1d0200-a659-11ea-8832-07a1e3e417e4.png)

**Comment by Tensuko** [comment]
read #5272 and https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ

**Comment by IWo112** [comment]
yh i forgot to turn off avoidance im sorry but problem still persists im trying to fix this issue for 3 days and nothing working i tried all of the settings...i have no clue wat to do next
![issue 4](https://user-images.githubusercontent.com/66414471/83743365-e9eb4980-a65a-11ea-8988-37c32ae40ff5.png)
![issue 5](https://user-images.githubusercontent.com/66414471/83743518-1dc66f00-a65b-11ea-9a63-abba10b37c71.png)
![issue 6](https://user-images.githubusercontent.com/66414471/83743527-2028c900-a65b-11ea-91f5-bcc322d9197a.png)

**Comment by Tensuko** [comment]
Your Combine still sits in the Fruit, why ? On the first pics it did exactly what I said, no fruit avoide so pipe is in fruit. Now on your last pics the Combine is in the middle of the Fruit and is it even driven by CP ?

**Comment by Bobster82** [comment]
He has a hired worker on the combine, not cp (1st post)
@IWo112 , you need to setup ur combine to use cp, not the hired worker, else this wont work ;)

**Comment by IWo112** [comment]
Yh u r right now i finally managed to get it work !....I had no clue it have to be CP harvesting field.
I used older version of CP for ages and it worked like charm...anyway thx for help.
