### ISSUE TITLE
Mode 2 Question?

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#5556]
Firstly congrats on your hard work, Mode 2 in conjunction with 'lands' is brilliant.

Are you able to use multiple combines in the same field in mode2 yet?
Do you plan to allow the 'fill level' to work as well as the 'distance' when a combine is deciding which trailer to call?
Is it  possible to only have the beacons working on the road rather than on all the time in mode 2?

When your using a forage harvester you have a 'following tractor'. Is it possible to have a tractor follow the combine in a similar way. In big fields when the combine calls the tractor it can be a long way away. For instance once a tractor has taken its first tip is it feasible for it then to follow the combine until the correct fill level is reached?

**Comment by Tensuko** [comment]
Use mutiple combines always works but unload all of them could still make problems.
We will let you know when we support 2 Driver. For now, only 1 allowed.
Beacons that is visual stuff and have low priority.
Combine and Mode2 Driver will have a meeting point and combine won't stop.
Try it out. Just set it to Stop while unload on deactivated.
