### ISSUE TITLE
Courseplay dont unfold or activate working item - Animation problem

### ISSUE THREAD

**Issue by alexanderweide** [Courseplay/courseplay#5558]
Hi,

recently i have started to use Courseplay on my Multiplayer server. How ever when i use the Amazone or other Trailers on my Tractors, Courseplay dont unfold working trailers like Spray Arms. It sprays correctly so i think its just a animation issue. But its repeatable and looks weird. 
BTW Great job what you have done...!

best 

Alex

**Comment by Tensuko** [comment]
#5484
