### ISSUE TITLE
mode 1 and refill issue

### ISSUE THREAD

**Issue by answermanitou** [Courseplay/courseplay#5559]
Hello
I have the problem with mode1 -- transporting and selling. And refilling the implements have problem too. 
All of this problems is the similar.
When i launch mode 1 the truck can fill himself one time from the first circle. When it came to finish point he driving to the start point and should did filling but dont do it while I dont sit on the current vehicle. Then it beggins to filling. Also while Ai staying under silo pipe i have very very big Fps down -- slideshow
Similar goes on when seeder or sprayer came to recharge his tank.
when its with sprayer then AI closing to the refill Tank but keep moving by the refill route. If I sit in this vehicle before he reach refill tank the CP write "filling 0 from max capasity" and its OK. 
when its with seeder the Ai can refill the seeds but dont refill fertizer and against when i sitting in this vehicle then Ai refilling all.

the log is about 40mb i load it to my drive

https://drive.google.com/file/d/102ozLcDrLOwkR9jIC9GMUlH4HHvcx9Mf/view?usp=sharing

few screenshot
![fsScreen_2020_06_04_20_32_34](https://user-images.githubusercontent.com/64743178/83794851-43796580-a6a7-11ea-8ffa-6b1859b9ad11.png)
![fsScreen_2020_06_04_20_31_15](https://user-images.githubusercontent.com/64743178/83794853-44aa9280-a6a7-11ea-9f34-855bc1747624.png)
![fsScreen_2020_06_04_20_30_41](https://user-images.githubusercontent.com/64743178/83794856-45dbbf80-a6a7-11ea-986a-199c568d1fff.png)

**Comment by answermanitou** [comment]
Tell me what channel of debug I should enable and reload Log file is it need.
About techniks -- all is from giants
refill station from sosnovka map
sprayer is Kuhn deltis

**Comment by Tensuko** [comment]
As mentioned many times:
Load mod: FS19_manureSystem (Version: 1.0.0.0) (Hash: f6e43e963a789d956eb7c4212c305a4c)
Download GitHub Version or throw it out.

**Comment by answermanitou** [comment]
damn can you closing not so fast @Tensuko ???
I think similar about this manure mod. I think ist useless mod for singleplayer

**Comment by Tensuko** [comment]
Version 1.0.0.0 got an Issue and that got discussed many times, ManureSystem GitHub got a working version, not a CP Issue so closed, simple.
