### ISSUE TITLE
no path found combine

### ISSUE THREAD

**Issue by wertigoxxx** [Courseplay/courseplay#5560]
The CP cannot find the combine when it is in close proximity to it.
at rounds, the tractors stop and must be guided there manually for evacuation

![fsScreen_2020_06_04_19_44_42](https://user-images.githubusercontent.com/65092037/83797651-470aed80-a6a3-11ea-804e-699d65cd96f1.png)
![fsScreen_2020_06_04_19_44_46](https://user-images.githubusercontent.com/65092037/83797675-4eca9200-a6a3-11ea-9f02-ed379bab06a8.png)
![fsScreen_2020_06_04_19_44_49](https://user-images.githubusercontent.com/65092037/83797691-538f4600-a6a3-11ea-9083-54066a5b36cf.png)
![fsScreen_2020_06_04_20_37_03](https://user-images.githubusercontent.com/65092037/83797712-5853fa00-a6a3-11ea-8f89-2fbc3ac06bac.png)
![fsScreen_2020_06_04_20_37_06](https://user-images.githubusercontent.com/65092037/83797743-5f7b0800-a6a3-11ea-8084-5064bb21593c.png)

**Comment by Tensuko** [comment]
logfile with 4 7 12 and 14 ? #5272 ? https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ ?

**Comment by Tensuko** [comment]
Closed due to inactivity
