### ISSUE TITLE
Issue with Combine

### ISSUE THREAD

**Issue by Jaiimez** [Courseplay/courseplay#5564]
I'll be 100% honest, i'm not entirely sure what the fault is but i'll explain what happened and include the log, maybe it'll help you guys.

I was driving a tractor with a windrower attached, and suddenly it started turning and driving (without courseplay enabled) and wouldn't respond to what I was doing. When I pressed escape, nothing happened, no menu, half the HUD was blank, when I tabbed over to my combine (which was harvesting using CP v.26) it was stuck on a tree, when I checked the log it was throwing up a load of errors before I had to force close it to do with Courseplay so I assume it's CP that cuased the issue.
[log.txt](https://github.com/Courseplay/courseplay/files/4737175/log.txt)

**Comment by Tensuko** [comment]
Can you tell me wich Combine it was ?
Vanilla or a Mod ?
Not sure but it could be caused by REA Mod.

Never seen that Error before...

2020-06-05 16:42 Error: Running LUA method 'update'.
2020-06-05 16:42 C:/Users/jaiim/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/vehicles.lua:726: attempt to call method 'getWheels' (a nil value)

**Comment by Jaiimez** [comment]
Ofcourse was the RSM 161, I do run quite a few mods, but the actual combine in question was vanilla, as well as the tractor at the time I was driving.

**Comment by Bobster82** [comment]
> Ofcourse, it was the RSM 161, I do run quite a few mods, but the actual combine in question was vanilla, as well as the tractor at the time I was driving. and yea, I am running REA Dynamic Dirt

Maybe try the same what u were doing, but then without the "rea mod"... that mod is altering the vehicle.spec_wheels ... didnt look into it in detail, but give it a try, then we can find the problem better?

**Comment by Jaiimez** [comment]
I've just noticed it seems to also repeat it almost everytime it gets full, when I have combine self unload active. I'll have a try later with REA deactivated.

**Comment by Tensuko** [comment]
Closed due to inactivity.
I guess this is REA Problem maybe with a specific Vehicle or another Mod.
