### ISSUE TITLE
Mode 2 No combine in reach 

### ISSUE THREAD

**Issue by bwalters410** [Courseplay/courseplay#5567]
Hello,
 I have updated to the most recent version of Courseplay, and have been having trouble With mode say " no combine in reach". I've tried a variation of different courses included routes on the field trying automatically find, and with it assigned by field and by combine as well as a set of routes of the field, with routes set to automatically assign and manual assign.

Any way I have set it up i have not been able to get the offload tractor to pick up the combine in the field 
 I had used a similar method on the previous version with no problems which leads me to think there might be an issue.

Thank you in advance for your time and effort,
Absolutely love Courseplay

**Comment by Tensuko** [comment]
read #5272 and https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ
maybe this helps you too: https://www.youtube.com/watch?v=PiUWD8ki8l4&t=5s

**Comment by bwalters410** [comment]
> read #5272 and https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ
> maybe this helps you too: https://www.youtube.com/watch?v=PiUWD8ki8l4&t=5s

Turning off "fruit avoidance" with the unloader doesn't seem to make a change as recommended in #5272 
also attempted with different tractors following the same course method as shown in test 2 video and still am not able to pick up combine. I recorded a screen grab demonstrating but its to big to attach

**Comment by Tensuko** [comment]
No logfile, closing.
Also we have enough other Issues, we don't need the same Problem 100 times...
