### ISSUE TITLE
Mode 2 waiting for combine call

### ISSUE THREAD

**Issue by BeattyVS** [Courseplay/courseplay#5568]
Since the latest iterations of CP, i can't get tractors with trailers to unload combines or foragers. If you look in debug mode, it says waiting on combine call, even when i call it manually from within the combine. See also attached pics.
Previous versions of CP this mode was working good.
![fsScreen_2020_06_06_00_05_59](https://user-images.githubusercontent.com/66513862/83941091-d4a42580-a7e8-11ea-82f4-13594c52b727.png)
![fsScreen_2020_06_06_00_06_08](https://user-images.githubusercontent.com/66513862/83941092-d5d55280-a7e8-11ea-9172-6a607c997eff.png)
![fsScreen_2020_06_06_00_06_19](https://user-images.githubusercontent.com/66513862/83941093-d66de900-a7e8-11ea-9254-d2bfbd53056b.png)

**Comment by SchwarzschildX** [comment]
same as #5567?

**Comment by Tensuko** [comment]
#5272 ?
https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ

**Comment by BeattyVS** [comment]
> #5272 ?
> https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ

AS you can clearly see from the pics, the pipe wasn't in fruit. However tried this and made no difference

**Comment by BeattyVS** [comment]
Ok, i have done some further testing on this issue.
First removing all mods except the ones used in this harvest, no difference.
Second let Courseplay run the combine, then it started to work fine.
This is not how I usually play, normally i am running the combines or forage harvester myself and let CP do the carting. This seems to not work now. See below for log file.
[log.txt](https://github.com/Courseplay/courseplay/files/4740494/log.txt)

**Comment by Tensuko** [comment]
As you noticed, this is not working and if you read #5272 then you will know it is not working yet and not a bug as we didn't not implement it yet.
