### ISSUE TITLE
Plowing mode question/issue?

### ISSUE THREAD

**Issue by krzysiexx04** [Courseplay/courseplay#5571]
Hi,

Quick question, is option to plow until the edge of the field gone from Courseplay or there is some issue about it?

Thx in advance!

**Comment by Bobster82** [comment]
@krzysiexx04 , I think in advanced settings u can adjust when to lower and when to raise the implement... Let it know if it worked

**Comment by pvaiko** [comment]
@krzysiexx04 as @Bobster82 said that option is gone, you can now set raise late in the advanced settings dialog instead.

**Comment by krzysiexx04** [comment]
@pvaiko  I've seen those options, but still I think option "plow to the edge of the field" was way more precise and self explanatory in comparison to those two new options.

**Comment by pvaiko** [comment]
@krzysiexx04 if you have a problem with the raise late option, open a new issue about it.
