### ISSUE TITLE
Combine Keeps Returning to 1st Waypoint on Unload

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#5572]
Map: Lone Oak
Equipment CLASS equipment from CLASS DLC and vanilla tipper
What is happening: The tractor moves up to offload the combine and doesn't quite get into position so the combine offloads only a little bit. The combine then reverses and goes to Waypoint one and starts the course all over again. 
![20200606143046_1](https://user-images.githubusercontent.com/24764870/83951901-f8746500-a802-11ea-9c9b-14b4d816ba19.jpg)
![20200606143053_1](https://user-images.githubusercontent.com/24764870/83951904-fad6bf00-a802-11ea-968d-a073b71d3c66.jpg)
![20200606143113_1](https://user-images.githubusercontent.com/24764870/83951906-fd391900-a802-11ea-91cc-79af723b34a7.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/4740796/log.txt)

**Comment by pvaiko** [comment]
@lcc1211 looks like you have self unload turned on for the combine. Reopen if that's not the case
