### ISSUE TITLE
[improvement] Course generation with up/down first

### ISSUE THREAD

**Issue by markus372** [Courseplay/courseplay#5574]
Hi

I have a few courses where I start with up/down rows and then make the headlands (e.g. windrow). In this case, the chosen start point will still be used as the point where the courses headlands begin and the point where headland row changes occur. 

![Github_2](https://user-images.githubusercontent.com/65828332/83966219-359b2e80-a8b9-11ea-95f7-59bc8e3ce7e0.PNG)

Point 4: this is the start point of the created course
Point 1: the created starting point of the up/down course 
Point 2: the endpoint of the up/down course
Point 3: start point of the headland course

My suggestion is that the start point of the headland course be moved to Point 2 because this way the tractor moves around the field useless for up to 50 percent of the field circumference.

Best regards

**Comment by Tensuko** [comment]
Just change your position where you start by selecting a target on the map...
This one is very situationel....

**Comment by pvaiko** [comment]
So instead of 'current vehicle position' use 'select position on map' for the starting location.
