### ISSUE TITLE
Mode 2: Abfahrer fährt auf den anderen drauf

### ISSUE THREAD

**Issue by michel5998** [Courseplay/courseplay#5576]
Moin, das ist nun kein fehler oder so, es ist eine kleinigkeit, die mir aufgefallen ist, die etwas nerven kann 
![fsScreen_2020_06_07_14_46_51](https://user-images.githubusercontent.com/49126733/83973067-2f6e7780-a8e4-11ea-84d7-094eacd61dd4.png) so fährt der hintere die ganze zeit hinterher und wenn der vordere wegfahren will, fährt er ja n stück zurück und da der hintere hinten drauf hängt, kommt der vordere nicht weg, keine ahnung warum der das macht aber wäre schön wenn dieses detail noch gefixt wird

**Comment by Tensuko** [comment]
#5272 
Mehrere Abfahrer ist noch nicht unterstützt!
