### ISSUE TITLE
FS19 freezes occasionally when using courseplay

### ISSUE THREAD

**Issue by SnowFuhrer** [Courseplay/courseplay#5578]
[log.txt](https://github.com/Courseplay/courseplay/files/4742642/log.txt) Here is the log. Seems to do with tip trigggers.

**Comment by Tensuko** [comment]
Tractor, Trailer, what did you do, what mode, etc etc.....

**Comment by SnowFuhrer** [comment]
Man tgs 4 by 4  truck with a krampe trailer. Unloading a grimme potato harvester and hauling to a tip point(combi mode). On Dondiego map.

**Comment by Bobster82** [comment]
I tried to reproduce this and I didnt get any errors.
@SnowFuhrer , can give more info like what the unloading place was, maybe some screenshots, or video.
Also when does it happen? when a trailer hits a the unload point or when the combine is full?
How did u setup the course? The more info u give, the better ;)

**Comment by Tensuko** [comment]
To old Issue and not knowing whats going up.
So closed due to inactivity.
