### ISSUE TITLE
Combine(fieldwork) and Mode 2 configuration/issue?

### ISSUE THREAD

**Issue by krzysiexx04** [Courseplay/courseplay#5583]
Hi,

As per topic, I observed a situation that is a bit odd for me and disturbing while playing FS19 - using Courseplay.

![2020-06-08](https://user-images.githubusercontent.com/7941937/84016729-f97dd180-a97d-11ea-8304-fe4d1320ff44.png)

Two issues are shown in the screen.

1. Red line and behaviour of combine. Once it fills up (by the way its always 95% not 100%) it then goes back right and back so it ends up in possition visible on the screen. Is it possible to reconfigure courseplay and made combine to stand still and wait for the tractor?

2. Blue and green lines are for the tractor itself. Once we have combine in positions like on the picture. Then tractor stop close to combine so it can unload the grainf from the tank. Here is the tricky part, once unloading is finished, tractor is going back on reverse gear(this causes loads of collisions, stupid situations etc.). This is kind a behaviour I would like to avoid once having two trailers attached to a tractor. I think here are two solutions, one is to stop combine doing the "back-right-back" move or made tractor to move forward to "safe" place on field.

Guys, please advise.
Thx in advance!

**Comment by TinyCrocodile** [comment]
The behaviour is intended to give the unloader space when the pipe is in fuit. To change this i think you need to turn off pathfinding on both the combine and the unloader.  On combine options(first page) you can set the combine to wait while unloading. 

The collisins that this can create are the reason  why multiple unloaders are not suported yet. Detail is described in #5272.

**Comment by Tensuko** [comment]
And can you do me a favour... Make Screenshots when it is daytime, as it is hard to see anything on dark pics... gsSetDayTime iirc...

**Comment by Lustiger-Hubi** [comment]
Also ich kann mit zwei Abfahrer abfahren ohne Kollisionen!
Ich fahre auch nicht mit zwei Anhänger!
Ihr habt das schon super hinbekommen!

**Comment by krzysiexx04** [comment]
@TinyCrocodile So I followed your advise and the outcome is as bellow picture shows.

![2020-06-08 (1)](https://user-images.githubusercontent.com/7941937/84080382-658f2280-a9dc-11ea-87e6-62efb2c8503e.png)

Combine stoped, as mention above filled grain tank up to 95% not more (next bug here - most probably associated with those settings) although it did not help tractor. It started going back after finishing uloading process. Screen below shows that when your settings were set combine filled up the grain tank up to 100% like it should.
![2020-06-08 (3)](https://user-images.githubusercontent.com/7941937/84080934-5066c380-a9dd-11ea-908b-c0d24aba561e.png)


@Tensuko I am trying to make a screen on day time, but I have some difficulties with making the same situation as in above post.

**Comment by krzysiexx04** [comment]
@Tensuko Ok, it is a bit brighter. Again, grain tank filled up to only 95% - settings are set for 100% for the combine.
![2020-06-08 (6)](https://user-images.githubusercontent.com/7941937/84081958-3fb74d00-a9df-11ea-8b2a-202c59d6e19e.png)
![2020-06-08 (7)](https://user-images.githubusercontent.com/7941937/84081961-41811080-a9df-11ea-8121-df10158bc6d4.png)
![2020-06-08 (8)](https://user-images.githubusercontent.com/7941937/84081964-43e36a80-a9df-11ea-9437-6b31785448b6.png)
![2020-06-08 (9)](https://user-images.githubusercontent.com/7941937/84081969-45ad2e00-a9df-11ea-9a0d-9812073e70d3.png)

**Comment by Tensuko** [comment]
CP cant reverse with 2 trailers. Almost no one can do it, specialy not with those kind of trailers.

**Comment by Tensuko** [comment]
Oh and for unload comvine, 2 trailers are not supported :)

**Comment by krzysiexx04** [comment]
@Tensuko thats obvious. But is it possible to switch reversing by tractor off? Somehow? Haven't tested it yet with single one with normal type of trailer - I am here quite sure it will cause some problems as well.

**Comment by Tensuko** [comment]
Cant turn off and I just finished Kandelin Map Field 3 without any Issue :)

**Comment by Tensuko** [comment]
Closed due to inactivity.
Keep in mind that Mode2 will have improovements step by step while we can't ignore other Issues and our Jobs and Family. So have some patience pls.
