### ISSUE TITLE
Advanced settings - button "reset" doesn't work?

### ISSUE THREAD

**Issue by krzysiexx04** [Courseplay/courseplay#5584]
Hi,

Like in the topic, seems like "reset" button is not working. If it is not know issue then please advise. Maybe, somehow it is a desease of courseplay that I have on my PC.

Thx in advance!

**Comment by Tensuko** [comment]
To Reset the Settings ? Never tried, never used.
Will check...

**Comment by Tensuko** [comment]
Jep it is not working, but I don't see a use in it...
Will check if can fix one day, not rly on priority :)

**Comment by pvaiko** [comment]
Just remove the reset button.

**Comment by Tensuko** [comment]
Already done.
