### ISSUE TITLE
Recursion limit reached for headland generation

### ISSUE THREAD

**Issue by hellridergit** [Courseplay/courseplay#5585]
In a 2-combine course, starting with headland, the right combine lags briefly then starts from a completely different waypoint, while the left one goes on properly.
The weak workaround is to generate the identical course separately on the right combine and tell it to skip the headland and start from the lanes.

All mods unloaded except the Przemasowo map and Courseplay v6.02.00027
Recorded it for you (compressed too much :|) https://www.youtube.com/watch?v=wSZuCqIw5ak

Referencing issue https://github.com/Courseplay/courseplay/issues/5057
Log: https://pastebin.com/raw/GYyuxTVm

**Comment by hellridergit** [comment]
Regenerated the course several time across several restarts. Each time the same thing happened.

**Comment by Tensuko** [comment]
Generating a Course with a Headland on a corner never gives a good result, try it when change the startposition more on the side.

**Comment by hellridergit** [comment]
> Generating a Course with a Headland on a corner never gives a good result

Interesting as that's how I've always done it, drove with the implement lowered towards the start point and enabled the driver as soon as the vehicle went past it, as seen on the video.

> try it when change the startposition more on the side with 'select position on map'.

Tried it and it worked. Thank you. Closing.
