### ISSUE TITLE
Fieldwork with combine issue - header switched automatically back to transportation mode.

### ISSUE THREAD

**Issue by krzysiexx04** [Courseplay/courseplay#5587]
Hi,

Seems like all the time combine finish the job and header have such possibility courseplay switch the header back to the transport mode (screen below). Is is an issue or it is matter of proper configuration?
![2020-06-08 (4)](https://user-images.githubusercontent.com/7941937/84081280-f3b7d880-a9dd-11ea-8a76-f81ad2945839.png)

Thx in advance!

**Comment by Tensuko** [comment]
Thats an 'Issue' but I think everyone of us can press X after done the work. Will keep it as enhancement :)

**Comment by krzysiexx04** [comment]
@Tensuko Sure thing! Just letting you all know, it better to know than not.
Testing is way closer topic for me than developing so I am keeping fingers crossed!

**Comment by Tensuko** [comment]
Got an option in adv Settings now, so you can deactivate the folding of tools at the end of the row.
