### ISSUE TITLE
Güllezubringer befüllt nur wenn man sich im Fahrzeug befindet. 

### ISSUE THREAD

**Issue by Wolle00** [Courseplay/courseplay#5588]
Hallo Leute!
Der Güllezubringer befüllt Gülle am Kuhstall nur wenn ich im Fahrzeug sitze, ansonsten fährt er einfach weiter.
Spiele auf der Gemeinde Rade und wollte wissen ob das vielleicht ein generelles Problem ist ?

**Comment by Tensuko** [comment]
Logfile ? Bin ziemlich sicher das du manuresystem 1.0.0.0 drin hast, update auf die github version dann geht es...

**Comment by Wolle00** [comment]
Ja richtig habe ich drin... Versuche es mal, vielen Dank.

**Comment by Tensuko** [comment]
Mache heir zu weil ich mir zu 99% sicher bin das es am manuresystem lag :)
