### ISSUE TITLE
CP senkt die FPS

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#5589]
Kann es sein, das die FPS mit courseplay bis auf 17 FPS runterfallen?
Wenn ich CP nicht nutze, habe ich immer 60 FPS
Oder ist das nur bei mir so?
![fsScreen_2020_06_09_14_12_07](https://user-images.githubusercontent.com/48583507/84162739-ff081400-aa70-11ea-8470-0f0e02f7d520.png)

**Comment by Bobster82** [comment]
Im only having fps drops when pathfinding needs to calculate bigger routes (if a combine cals a unloader) else cp isnt a big issue. So when does it happen to you?

**Comment by Lustiger-Hubi** [comment]
Ich habe zwei Abfahrer läuft bis auf die FPS super
Nur das ruckeln der Map nerft.

I've got two downhill racers running great up to the FPS
Only the jerking of the map nerft.

**Comment by Bobster82** [comment]
@pvaiko , I didnt check the pathfinder at all, so i dont know if its posible, just trying to understand the lua and ur code... but isnt it possible to slowdown pathfinder a bit to calculate, so it doesnt drain all resources?

**Comment by pvaiko** [comment]
The pathfinder is already 'slowed down', using lua coroutines to spread out the calculation to many update cycles. We keep working on improving the pathfinder (see for example #5562 by @Goof245).

**Comment by Bobster82** [comment]
Thanks for replying... I try to decode ur code more so I can help out more ;) It isnt easy, but I can read lua atm

**Comment by Lustiger-Hubi** [comment]
Also ich habe mich jetzt entschieden und nehme die Courseplay_6_01_00399
die FPS stehen immer auf 60 kein Ruckeln
Alles läuft prima! 4 Abfahrer pro Feld kein Problem!
Werde ab und an mal die neuste Version Testen!
