### ISSUE TITLE
Probleme mit Überlader Workaround?

### ISSUE THREAD

**Issue by Dschowy** [Courseplay/courseplay#5590]
Hallo! Kann es sein, daß CP mit Überladewagen momentan nicht zurecht kommt? 
Das hat bei mir in einer früheren 6er Version schon funktioniert. Aktuell klappt es leider nicht.
Ich fahre den Kurs ein und mache extra langsam bevor es an den Überladepunkt geht, setze einen Parkpunkt und fahre weiter.
Der Trecker mit dem Überlader fährt über den Parkpunkt raus, bleibt stehen und fährt auch nicht weiter. Selbst wenn ich auf "weiterfahren" klicke, passiert nichts.
In den Optionen habe ich auch extra eingestellt, daß er die Geschwindigkeit wie beim Einfahren wählen soll, trotzdem brettert er wie blöd zum Anhänger.
Gibt es da noch eine Einstellung die man machen muss oder sollte? Wäre natürlich super wenn der echte Überlademodus wieder kommen würde, wie es im 17er schon gab.

**Comment by Tensuko** [comment]
ÜLW sind offiziell noch nicht unterstützt.
