### ISSUE TITLE
Abfahrer von Drescher

### ISSUE THREAD

**Issue by Bikeslife** [Courseplay/courseplay#5591]
Ich habe 3 Drescher und 2 Abfahrer. Die Abfahrer werden aber nicht automatisch gerufen. Wenn ich die aber vom Drescher aus manuell rufe, fahren die Abfahrer auch los und tanken ab. Soweit ich weiß hat dies in LS19 auch schon funktioniert. Ich habe es auch genauso gemacht wie in einem älteren Beispielvideo aber auch von LS19. Sorry, wenn es dazu schon was gibt...

**Comment by TinyCrocodile** [comment]
Es gibt ein neuer mode2.
Alle infos dazu sind in #5272 Und in https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ zu finden.
