### ISSUE TITLE
'Lands' mode suggestion

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#5592]
Now that you can pick the amount of turns in a 'land' is it possible to switch from turning left to turning right to basically go round the land?
The reason is if you chose a high number of runs particuarly if your headland is on an angle, you can end up having to run a long way, which only increases until youve completed that 'land'. What a combine would do IRL is once the gap between the land and the remaining crop is wider than the remaining runs of the land then the combine would then start to go round the land, ie it comes to the top and turns right and goes down the other side of the land. 
Its not very well explained but hopefully you get the gist.

**Comment by Tensuko** [comment]
Drawing would help.

**Comment by kwguk** [comment]
Exactly 
Is that no what I said?

West Amesbury Farms

**Comment by Tensuko** [comment]
Number of Lanes per Land can be choosed in the generator.
