### ISSUE TITLE
Combi unloader stops under pipe while combine is not stopping

### ISSUE THREAD

**Issue by Dennizzzzz** [Courseplay/courseplay#5593]
Using version v6.02.00027.

When my unloading truck is driving to the combine, it stops under the pipe, the combine will go on, and the truck will start again, driving just under the pipe and stopt again.

Image just before stopping
![2020-06-10 09_15_34-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/84239734-49cf6d80-aafd-11ea-8728-193626c606e6.jpg)

Image just after stopping (you see the combine drive on).
![2020-06-10 09_16_27-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/84239791-5a7fe380-aafd-11ea-84f6-41cc77156878.jpg)

After a while the unloading starts working (different between other images, this image shows the text 'target', this text is not showing when the unloader stops under the pipe).
![2020-06-10 09_20_00-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/84239832-65d30f00-aafd-11ea-8e98-18b3e0bcc746.jpg)

[log.txt](https://github.com/Courseplay/courseplay/files/4756838/log.txt)

**Comment by Tensuko** [comment]
Try to adjust the offset.
@pvaiko this should be the same problem again or similar.

**Comment by Bobster82** [comment]
@Dennizzzzz , how did u setup ur combine and truck?
Did u use avoid fruit on both or not? cuz the combine isnt making a pocked and ur truck is driving in the fruit...

**Comment by Dennizzzzz** [comment]
Combine settings:
![2020-06-10 13_10_36-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/84261375-f3255c00-ab1b-11ea-921d-9a86b9a59ba5.jpg)
* Turn on field: enabled
* Drive around crop: disabled

Truck settings:
![2020-06-10 13_11_20-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/84261389-f882a680-ab1b-11ea-9160-422dbc42c377.jpg)
* Drive around crop: disabled
* Turn on field: enabled

PS. just noticed the place of these two settings are different for the truck and combine (truck settings the drive around crop is above the other one, combine settings this setting is below the other one). Little bit confusing, maybe nice to switch the two settings so they are in the same order for trucks and combines?

**Comment by pvaiko** [comment]
Test with 28 and post the log here.

**Comment by Bobster82** [comment]
> During the issue I posted above, I was harvesting sunflowers with an 9m mower. But (I was not thinking) now i've sown soybeans which I had to mow with a 13.5m mower.
> But the unloader truck still keeps stopping.
> Here the log file.
> [log.txt](https://github.com/Courseplay/courseplay/files/4760390/log.txt)
> 
> If you need the log file when i'm mowing the same way as before, just let me know.

Can u show me what vehicles u used exactly? and the map? And can u try to remove all mods and try again? thx

**Comment by Tensuko** [comment]
> Can u show me what vehicles u used exactly? and the map? And can u try to remove all mods and try again? thx

And then ?
We know what happens there but not why, thats what V28 is for, it writes debug infos in the log, all you got to do is do the same again in the exact same situation. Don't mix things up here pls, thx.

**Comment by Bobster82** [comment]
Sorry just trying to help. Will leave it to you then

**Comment by Dennizzzzz** [comment]
Some extra info

Used vehicles:
D-754 Truck Pack v 1.2
https://fs19.net/farming-simulator-2019-mods/trucks/d-754-truck-pack-v-1-0/
![2020-06-11 17_02_37-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/84403574-2512ed00-ac06-11ea-9777-57eb44c2cdea.jpg)

Used both mowers:
![2020-06-11 17_03_01-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/84403584-280ddd80-ac06-11ea-84b6-9ae11b290c53.jpg)

Used combine.
![2020-06-11 17_03_15-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/84403597-2b08ce00-ac06-11ea-96dd-0736409dfe75.jpg)



Courseplay for FS19 v6.02.00028
Map: NF Marsch V2.8 (Nordfriesische Marsch)

**Comment by Tensuko** [comment]
Still valid with .00064 ?
I had no problems but I also don't unload driving combine in the fruit either...

**Comment by Tensuko** [comment]
Closed due to inactivity
