### ISSUE TITLE
Menu items keeps showing

### ISSUE THREAD

**Issue by Dennizzzzz** [Courseplay/courseplay#5594]
Using version v6.02.00027.

Sometimes (often) the menu for showing the route does not disappear. The images below shows what happens. I tried to reproduce the problem, but cannot pinpoint when this happens.

![2020-06-10 09_06_05-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/84240373-383a9580-aafe-11ea-9ea3-7112c9473482.jpg)
![2020-06-10 09_05_45-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/84240396-3e307680-aafe-11ea-8bd1-4c1a66bc3399.jpg)

**Comment by excubated** [comment]
Happens to me from time to time too, but like OP i haven't been able to pinpoint what triggers it.

I have, however, noticed that the bug isn't global. Again; I haven't noticed any common conditions, actions, work modes that triggers it, but it only happens to vehicles individually. If the affected vehicle is reset to shop or modified, the bug disappears.

**Comment by Tensuko** [comment]
Still valid, not sure what combination to do to create this bug...

**Comment by Tensuko** [comment]
Changed a lot on HUD.
Does this still happen ?
I didn't had the Issue in a very long time.

**Comment by Tensuko** [comment]
Guess it is fixed, if not, let us know.
