### ISSUE TITLE
Mode2 unloading combine only at 100%/ Abtanken erst bei 100%

### ISSUE THREAD

**Issue by FreelancerTrent** [Courseplay/courseplay#5595]
Hi,
I have the following problem with threshing takings in Mode 2:

No matter what% setting I use for "Start at", the tractor only starts when the grain tank of the combine is at 100%. The tractor is at its end point of the course which brings it from the field over the farm silo back to the field. The combine does its work and stops at 100%.

So for a brief description of the problem. Version of CP: Courseplay for FS19 v6.02.00028

Please tell me what additional information you need.

Thank you!

Trent

+++++++++++++++++++++++++++++++++++++++
German:

Hallo,
bei Drescherabtaken bei Mode 2 habe ich folgendes Problem:

Egal welche %-Einstellung ich bei "Starten bei" benutze, der traktor fährt erst immer los wenn der Korntank des Mähdreschers bei 100% ist. Der Traktor steht auf seinem Endpunkt des Kurses der ihm vom Feld übers Hofsilo wieder aufs Feld bringt. Der Mähdrescher verrichtet seine Arbeit und bleibt bei 100% stehen.

So zur kurzen Beschreibung des Problems. Version von CP: Courseplay for FS19 v6.02.00028

Bitte sagt mir, welche Informationen ihr zusätzlich benötigt.

Danke!

Trent

**Comment by Tensuko** [comment]
@pvaiko 
wird bei deaktivierter Fruchtumfahrung der 'Start at' Wert ignoriert ?

**Comment by Tensuko** [comment]
Viele verschiedene Probleme hier, gibt einiges noch zu verbessern, aber dafür haben wir Issues.
Das erste Problem abtanken bei X% funktioniert, jetzt mit option sogar im ersten Vorgewende.
