### ISSUE TITLE
Feature request: always turn backwards

### ISSUE THREAD

**Issue by Dennizzzzz** [Courseplay/courseplay#5598]
I like the default course generation without 'headlands' options.
 
![2020-06-10 22_02_13-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/84312991-2d1b5000-ab66-11ea-93d0-8718278ef570.jpg)

But this keeps happening:
![2020-06-10 21_55_13-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/84313052-44f2d400-ab66-11ea-83bc-c3b909b063cb.jpg)

It would be nice to have an option that keeps the tractor on the field, and turn backwards from the start of a turn to the end of a turn.
![2020-06-10 21_56_38-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/84313067-4b814b80-ab66-11ea-9eb1-1ef566101593.jpg)

**Comment by Dennizzzzz** [comment]
Tested  it again, but now the tractor does not get stuck in the ditch. But you can imagine the tractor will get stuck if the ditch was closer to the field.

Turn on field: activated
Avoid fruit: Deactivated

![2020-06-11 08_41_57-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/84355921-b745d180-abc3-11ea-87d0-ab4db06e834d.jpg)

![2020-06-11 08_43_03-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/84355934-bca31c00-abc3-11ea-8295-16bba27b175e.jpg)

![2020-06-11 08_43_49-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/84355942-c2006680-abc3-11ea-917c-d26206dba292.jpg)

Courseplay for FS19 v6.02.00028
Map: NF Marsch V2.8 (Nordfriesische Marsch)
[log.txt](https://github.com/Courseplay/courseplay/files/4763185/log.txt)

**Comment by Tensuko** [comment]
Pathfind in turns on or off ? Adv settings page1.
Else, add more headlands to your course.

**Comment by Dennizzzzz** [comment]
Pathfind is turned off. Should it be set to on?

More headlands could work, but I like the sharp turns on the field (otherwise I'm missing parts of the field), and if I set this, I get in trouble with the trees alongside the field which are really close to the field).

In my honest opinion, if I tell the AI to turn on the fields, it should honer that, and turn on the field, not around the field. (not meant to be offensive) :-)

**Comment by Tensuko** [comment]
More headlands does not mean you dont have sharp corners...

**Comment by Dennizzzzz** [comment]
@Tensuko Just for my understanding. Should I have Pathfind turned of or on? I'm not sure what this setting really does. Googled it, and read the CS manual, but i did not find any explanation about this setting.

**Comment by Tensuko** [comment]
Should be fixed (though some turns are not working correctly right now...)
