### ISSUE TITLE
Combine and unloader problem

### ISSUE THREAD

**Issue by kaisers13** [Courseplay/courseplay#5599]
Hello! I am using ver:6.02.00027.

I find an interesting thing, when I want to unload my combine. None of  either unloaders communicate with the combine. It happened both with mods and vanilla.
In origin map, and mod maps.
In logs there is one "error", 

" g_combineUnloadManager:getHasUnloaders(vehicle):false "

Error messages come everytime, when I'm open combine Hud, and select first column, where I can call tractors or click on calling unloader.

Thank you for answers.

Edit: I used before 6.01.00398, which worked well with minor bugs

**Comment by kaisers13** [comment]
Thank you for patience and guide. I found what was wrong, and now it is working.

**Comment by artcwolf** [comment]
Keiser, what was the solution?  I'm having a similar problem.
