### ISSUE TITLE
[Issue] Turn around with multiple Tools creates wrong path

### ISSUE THREAD

**Issue by markus372** [Courseplay/courseplay#5600]
When you create a course with multiple tools, the wide turn around is creating the wrong path. 

When you have the narrow turn around it creates a path from the middle of the left lane to the middle of the left lane in the other direction, this way it is correct. 
![Github_3](https://user-images.githubusercontent.com/65828332/84319082-bd11c780-ab6f-11ea-8c10-f8768367ef9a.PNG)

But when it creates the path for the wide turn around it creates a path from the middle of the left lane to the center of the created course instead of the middle of the left lane.
![Github_4](https://user-images.githubusercontent.com/65828332/84319255-05c98080-ab70-11ea-98fc-3e2c3ee7dfa5.PNG)

**Comment by Tensuko** [comment]
Symetric Lane Change on or off ? Same setting on both Tools ?

**Comment by markus372** [comment]
Symmetric Lane change is off and both have the same settings

**Comment by Tensuko** [comment]
Can't reproduce with 02.00040
