### ISSUE TITLE
Dumper In Mode 2 Hay Collecting Only Follows harvestor

### ISSUE THREAD

**Issue by DaToastVan** [Courseplay/courseplay#5601]
Good day,
This is my first time submitting an issue so bare with me.
I am trying to collect hay with a forage harvester and dump trailers. I make a course to rake the field and then load that course into the harvester to collect it. It runs pretty well but ever since the updated mod 2 the dump trailers only drive behind the harvester, never beside it. To make the problem even worse if the the harvester can not reach the dumper behind it then nothing moves at all.

So, What I expected to happen:
Dumper drives beside harvester like when harvesting corn.
What happens:
The dumpers only follow behind the harvester.

I have attached my log and a screen shot.

If its worth noting, auto drive did drive beside the harvester until I changed some settings, trailer stays in field I believe it was. Then it also only followed.
Also I can not use auto drive for this as auto drive dose not seem to know when the harvester has finished a turn at the headlands.

![102910392_10219357693507512_1035845222878334703_o](https://user-images.githubusercontent.com/66755855/84328159-3c42d380-ab4f-11ea-985a-0432e9dffbb1.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/4761706/log.txt)

**Comment by Tensuko** [comment]
We know about this. #5470

About not reach the trailer, read #5272 
The bigX and the rotselmas from GIANTS in ModHub are tested and work for this.
