### ISSUE TITLE
Frage bezüglich Drescherverband, in Erweiterte Einstellungen (Drescher selbst abtanken)

### ISSUE THREAD

**Issue by RobinHooooood** [Courseplay/courseplay#5602]
Hab eine Frage wenn ich den Drescherverband aktiviere stell ich ihn immer auf 200m ein aber es passiert sehr oft das der 2 Drescher nicht anhält sondern weiter fährt und dann in den anderen rein. Mach ich da was falsch oder ist das normal? 
Meine Zweite Frage ist wenn ich beim Drescher auf Erweiterte Einstellungen gehe und "Drescher selbst abtanken" aktiviere fährt der dann wenn ich ein Anhänger auf das Feld stelle immer selbst dahin oder wie läuft das, weil der Drescher nur wenn er den Wegendpunkt erreicht bei mir abtankt und nicht selbst.

**Comment by Tensuko** [comment]
Beide Drescher den Drescherverband an ?

Javder Drescher fährt dann selber zum Trailer. Kein Kurs anhängen den Trailer findet er alleine.

**Comment by RobinHooooood** [comment]
Ja beide sind im Verband aber der eine fährt manchmal einfach weiter. 

Komisch bei mir läd der Drescher nur ab wenn er den Endpunkt vom Dreschkurs erreicht sonst ned

**Comment by Lustiger-Hubi** [comment]
Javder Drescher fährt dann selber zum Trailer. Kein Kurs anhängen den Trailer findet er alleine.

Bei mir fährt der Drescher nicht zum Trailer!
Einstellung: Erweitert -Drescher fährt selben ab.
Frage auf welche Einstellung muss dann der Trailer stehen, dass der Drescher den Abfahrer findet
Am Startpunkt laden?
![fsScreen_2020_06_11_18_29_54](https://user-images.githubusercontent.com/48583507/84414236-00247700-ac12-11ea-8360-b996e9fd7d05.png)
![fsScreen_2020_06_11_18_29_57](https://user-images.githubusercontent.com/48583507/84414246-0286d100-ac12-11ea-826b-5a3dee7ced17.png)
![fsScreen_2020_06_11_18_30_47](https://user-images.githubusercontent.com/48583507/84414248-031f6780-ac12-11ea-9eec-23fa5b58ac12.png)

**Comment by RobinHooooood** [comment]
Aber wenn der Drescher kein Kurs haben darf wie soll er dann dreschen das versteh ich nicht ganz.

**Comment by Lustiger-Hubi** [comment]
Ich bekomme es auch nicht hin!
Ich kann einstellen was ich will funktioniert nicht!
Auch das habe ich probiert
![Combine self unloading](https://user-images.githubusercontent.com/48583507/84565985-cff1eb00-ad6d-11ea-8f25-8bb7194f22aa.jpg)
Vielleicht kann mir einer die Einstellungen verraten was ich genau machen muss!

Danke

**Comment by TinyCrocodile** [comment]
Das ist eine veraltete Garafik. Kein normaler helfer kein unload kurs(gelb gepunktet) dafür ein Feldarbeitskurs für den drescher. Self unload in den erweiterten Einstellungen des dreschers aktivieren. Das einzige was bleibt ist der waiting trailer.

**Comment by Lustiger-Hubi** [comment]
Wenn die Gelbe Grafik (normalerweise ja für Abfahrer) für den Drescher gemacht wird ohne Overloadpunkt! Wie soll der Drescher dann starten?
Sorry

**Comment by Tensuko** [comment]
So jetzt mal für Klarheit sorgen....
Drescher selber abtanken lassen:
- Erstellt einen normalen Feldarbeitskurs für den Drescher
- Aktiviert Drescher selber abtanken in den erwetierten Einstellungen
- Platziert einen Trailer (kann auch gerne ein Mode1 Fahrer sein) innerhalb von 20m zum Feldrand oder auf dem Feld
- Der Drescher wird, wenn er voll ist, seinen Weg zum Trailer selber generieren

Es wird also KEIN extra Abladekurs für den Drescher benötigt, so wie es z.B. bei einem Ladewagen zum Gras oder Strohsammeln gemacht wird.

**Comment by Lustiger-Hubi** [comment]
OK Danke
Funktioniert!!
Danke nochmals!

**Comment by Lustiger-Hubi** [comment]
Schade schade schade!
Der Drescher hat einmal abgeladen, dann will er anscheind nicht mehr!
Außerdem habe ich ein Kurs eingefaren (Startpunkt am Feldrand, Endpunkt 100m vor startpunkt
Jetzt wenn ich den Abfahrer (abfahren am Startpunkt) starte und er dann wieder kommt, dreht er sich immer nach links weg!
![fsScreen_2020_06_13_16_18_58](https://user-images.githubusercontent.com/48583507/84571248-58828280-ad92-11ea-8098-9e5498f4bc2e.png)
Drescher kommt trotzdem nicht!

**Comment by Tensuko** [comment]
Man kann den Drescher auch sagen Sofort Abfahren.
Leider geht es nicht anders, oder man stellt einen zweiten Trailer dazu, fals eine voll ist und weg fährt.

Mit dem Drescherverband ist es so, dass es im Moment Probleme gibt wenn der Kurs Vorgewende hat. Das wird leider nicht so einfach zu fixen sein wie gedacht...

**Comment by Tensuko** [comment]
Altes Issue und nicht gan klar was hier los ist..
