### ISSUE TITLE
Stuck on ScanningField window, field unknown to CP

### ISSUE THREAD

**Issue by Dennizzzzz** [Courseplay/courseplay#5603]
Frequently during loading of my game, the CP "field scan in progress" windows gets stuck:
![2020-06-11 08_10_24-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/84351572-eeb08000-abbb-11ea-8fc7-fb134b4a2ef9.jpg)

Sometimes the game crashes, sometimes I wait a while (about 30 seconds), and the game loads, but then field 20 is not selectable in the Generate Course window.
Also I cannot click on the field itself to select it.

![2020-06-11 08_12_45-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/84351685-25869600-abbc-11ea-9a77-37dd7715598c.jpg)

I have to reload the full game once or twice and then the 'field scan in progress' window will just load normally, and field 20 is selectable in the generate course window.

Courseplay for FS19 v6.02.00028
Map: NF Marsch V2.8 (Nordfriesische Marsch)
[log.txt](https://github.com/Courseplay/courseplay/files/4762943/log.txt)

**Comment by pvaiko** [comment]
This is almost always a map issue, usually the boundary between two fields is way too narrow or fields are even overlapping.
