### ISSUE TITLE
Bei Verbund von >=3 Fahrzeuge fahren einige falsch und falsches Bezugsfahrzeug im Fahrzeugverbund für die Entfernung

### ISSUE THREAD

**Issue by Clouseau219** [Courseplay/courseplay#5605]
ich habe da, mal wieder, ein paar Probleme mit dem Courseplay.
1. Problem
Wenn ich ein Fahrzeugverbund mit 3 Fahrzeugen machen, dann fährt dann fahren 2 richtig und der 3. fährt einen falschen Kurs.

In dem Beispiel ist es das rechte Fahrzeug, es sollte eigentlich dem Kurs (grüne Pfeile) folgen, aber das Fahrzeug dreht nach rechts ab und fängt dort den Kurs an.

![2020-06-10 22_54_55-Farming Simulator 19](https://user-images.githubusercontent.com/16350763/84373283-a3f33000-abdc-11ea-85fa-136cf8c1779c.png)

Ich habe keine Ahnung was ich da falsch mach und wie ich das ändern kann. Natürlich steht das Fahrzeug auf rechts, Symmetrischer Bahnwechsel und erster Wegpunkt usw. Das Linke und Mittlere fahren den Kurs richtig ab. Es liegt auch nicht am Gespann, wenn ich das ganze mit 3 Dreschern macht passiert das gleich. Es schaut fast so aus als würde er zu einem anderen Punkt springen, Obwohl das richtige Teilstück lila markiert ist.

2. Problem
Gerade bin ich wieder mit 3 Fahrzeugen im Verbund gefahren, dieses mal hat es ausnahmsweise mal mit dem Kurs geklappt, dafür hat das letzte Fahrzeug, wurde auch mit 3/3 angezeigt, sich dauern an die Entfernung zum ersten Fahrzeug orientiert uns ist so natürlich auf das 2. aufgefahren weil sich das 2. Fahrzeug schön brav am 1. orientiert hat und stehen geblieben ist.

Hat jemand eine Idee an was das liegen kann?

Grüße und vielen Dank,
GoboFraggle

**Comment by Tensuko** [comment]
Das Problem ist Kurs an einer Ecke gestartet.
Starte mehr am Rand, dann sollte es besser gehen.

**Comment by Clouseau219** [comment]
Danke, mit Rand klappt es besser. Nur der Fahrzeugverbund will nicht so ganz. Die Entfernung die man da einstellt, ist dass immer zum vorderen Fahrer oder zum 1. Fahrer im Verbund?

Zum Vordermann:
1. Fahrer < 100m> 2. Fahrer (100m eingestellt) < 100m > 3. Fahrer (100m eingestellt)

oder ist es zum 1. Fahrer:
1. Fahrer < 100m> 2. Fahrer (100m eingestellt) < 100m > 3. Fahrer (200m eingestellt)
Was aber wenig Sinn machen würde, weil wenn 2. Voll ist fährt der 3. im drauf.

Ich kann mir halt das nicht erklären:
![2020-06-11 15_48_53-Farming Simulator 19](https://user-images.githubusercontent.com/16350763/84418430-82636a00-ac17-11ea-8860-f7a0c34929a9.png)
Alle 4 sind im Verbund und der 4. wollte den 3. überholen. Er zeigt auch 105m an.

Wo liegt da mein Fehler?

**Comment by Tensuko** [comment]
Liegt am Vorgewende, innere Bahn ist kürzer und der Abstand stimmt dann nicht mehr.

**Comment by Clouseau219** [comment]
> Liegt am Vorgewende, innere Bahn ist kürzer und der Abstand stimmt dann nicht mehr.

Aber ist nicht genau dass der Sinn von dem Abstandhalten, dass wenn der Andere eine kürzere Strecke hat das hintere Fahrzeug warten soll und nicht daran vorbei zieht?

**Comment by Tensuko** [comment]
Desshalb wurde das ja nun auch gefixt:
https://github.com/Courseplay/courseplay/releases/tag/6.02.00032

Fahrzeugverband sollte nun wieder laufen. Hab ja nicht gesagt das es kein Fehler ist, nur was die Ursache ist.
Ich komme halt nicht ständig dazu alle Issues durch zu gucken, sry wenn es etwas gedauert hat :)

Wenn Probleme auftauchen, bitte bescheid geben, dann mache ich hier wieder auf.
