### ISSUE TITLE
No combine in reach 

### ISSUE THREAD

**Issue by haza757** [Courseplay/courseplay#5608]
Hello, 

I have updated to v6.02.00028- when I use mode 2 I get a flickering 'no combine in reach' and the tractor and trailer does not move towards to the combine, even when the combine is at 100%. I have deleted CP and reinstall back to 012 release but still get same issue. I have tried vanilla combines, tractor and trailers with same result. Iv attached my latest log. 

Thank you. 
[log.txt](https://github.com/Courseplay/courseplay/files/4766220/log.txt)

**Comment by Lustiger-Hubi** [comment]
Hast du hier dein X gemacht?
![fsScreen_2020_06_11_19_24_40](https://user-images.githubusercontent.com/48583507/84419807-6bbe1280-ac19-11ea-8ec1-e235ab8870ea.png)

**Comment by kwguk** [comment]
I would suggest you need to tell the unloader to look for the combine in field 13. At the moment inthe picture you have no field selected.

**Comment by Dschowy** [comment]
But what to do when you have large field that includes 2 or more smaller fields? In the picture you can clearly see that the combone is selected. I use the same method and most of the time it works, but sometimes the unloader doesn't drive to the combine or the combine doesn't call the unloader. Whatever.

**Comment by Tensuko** [comment]
> 
> 
> I would suggest you need to tell the unloader to look for the combine in field 13. At the moment inthe picture you have no field selected.

@kwguk 
One more time:
The Field Selection is a simple, stupid textfilder for the Combine list, nothing more, nothing less!

@haza757 
read #5272 and https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ

**Comment by polosubtil** [comment]
Just a comment from my experience with my game
When I start mode 2 with a tractor + trailer, I never have a combine in the list. For some reason, I just have to stop the tractor course if I already started it, switch to mode 1 then switch back to mode 2 immediately, then all combines are available. Not sure how or why but I have to do it at every new game start and it works all the time

**Comment by Lustiger-Hubi** [comment]
kwguk commented 12 hours ago
I would suggest you need to tell the unloader to look for the combine in field 13. At the moment inthe picture you have no field selected.

Das ist ja nicht sein Bild! Das soll @haza757 nur die einstellung zeigen (X) am Drescher!
Und Drescher suchen auf Feld, da sollte überhaupt nichts stehen!

**Comment by Dschowy** [comment]
Und was ist wenn man mehrere Felder zu einem zusammengefügt hat? Dann greift die Funktion nämlich nicht. Richtig Spass hat man, wenn man 2 Drescher auf dem Feld hat. Die fahren zwar brav ihre Kurse ab, aber es kommt oft vor dass der Abfahrer nicht gerufen wird.

**Comment by Tensuko** [comment]
> Und was ist wenn man mehrere Felder zu einem zusammengefügt hat? Dann greift die Funktion nämlich nicht.
Es gibt eben keine Suchen auf Feld Funktion. Außerdem sollte man vergrößerte Felde eh den Feldrand Scannen und dann als User Feld unter einer der Nummern abspeichern.



> Richtig Spass hat man, wenn man 2 Drescher auf dem Feld hat. Die fahren zwar brav ihre Kurse ab, aber es kommt oft vor dass der Abfahrer nicht gerufen wird.

Weil 2 Drescher oder mehrere Abfahrer noch nicht unterstützt sind.

**Comment by Dschowy** [comment]
OK, das wusste ich nicht. Danke für die Info!

**Comment by haza757** [comment]
Hello,

I still have problems with Mode 2 and 'No combine in reach'- I have taken out other mods, iv tried everything suggested above and updated to latest CP. My tractor and trailer (any) will not move at the STOP signal and flashed 'no combine in reach' - the combine has been selected and I start with Unload. 

Could anyone help with this please?

**Comment by Tensuko** [comment]
This topic is super old and there is not a problem with no combine in reach (testing mode2 stuff the last days so I am super sure about this one). Make sure to read #5272 and Wiki Page.
