### ISSUE TITLE
use autodrive for unload/refill

### ISSUE THREAD

**Issue by fischbesuch** [Courseplay/courseplay#5610]
Hallo
ich habe bisher die Version 6.01.00305 benutzt. Dort kann man mit der Funktion use autodrive for unload/refill courseplay und autodrive verbinden. In der aktuellen Version ist das weg. Gibt es sonst eine Lösung ? Wie macht man das jetzt ?

**Comment by Tensuko** [comment]
Ist in den erweiterten Einstellungen.
