### ISSUE TITLE
CP 6.02.00028 und Dedi

### ISSUE THREAD

**Issue by Kamparan0** [Courseplay/courseplay#5611]
Hallo zusammen,

Ich habe vorgestern Courseplay das neueste Release (6.02.00028) sowohl lokal als auch auf dem Dedi-Server aktiviert. Danach konnte ich mich nicht am Server mehr anmelden. Das Spiel bleibt stets bei "Sync mit anderen Spielern" hängen. Habe dann alle Mods raus und nach und nach wieder die Mods aktiviert. Das Problem trat immer bei Courseplay auf. Ich habe nun wieder 6.02.00026 installiert und konnte ich mich wieder ganz normal anmelden. Das passierte sowohl bei gespeicherten Spielständen als auch bei ganz neuen Spielen.

**Comment by Tensuko** [comment]
#5484
