### ISSUE TITLE
Levelling and compacting - wrong tool for this mode

### ISSUE THREAD

**Issue by s187375** [Courseplay/courseplay#5612]
I have set up a course in an open silo where the helper before entering the bunker (in levelling and compacting mode) stops and i get the message "wrong tool for this mode". If I switch from levelling and compacting to fill up, the helper starts working normally in the other mode. I get the same message no matter which tool is attached.
do the courses for filling up and the courses for levelling and compacting have to be se up differently? does it matter if the bunker is filled driving trough instead of reversing?
THX for all your work on this fantastic mod :)

**Comment by s187375** [comment]
the issue has been postponed, but to when? just let me know if it's a matter of days or it part of a bigger project that will be taken care of in a not so close future.
 thx ;)

**Comment by ddewar** [comment]
Hey @s187375, 

Two things:
1. Can you give any information about which tools you were trying to use on the front or back of the vehicle when getting the error?
2. Postponed just denotes it isn't currently being worked on by the team and it is unsure when someone will be able to investigate it.

**Comment by s187375** [comment]
I have tried the vanilla Holaras Stego 485 and H. MES 500; both on the front and on the back, together and one by one. Tried on a Xerion and on a NH T8

(thx for the info)

**Comment by Tensuko** [comment]
Still a problem with wrong tool for this mode ?

**Comment by Tensuko** [comment]
As I get no answer I take it as solved.

**Comment by gSe7eN** [comment]
I too am having this issue using a Xerion and MES 500 leveler. I'm on ver 6 .75
