### ISSUE TITLE
triggers.lua does not add tipTriggers for placeable objects with exactFillRootNode

### ISSUE THREAD

**Issue by dp-github** [Courseplay/courseplay#5613]
Some placeable objects (e.g. [Fermenting Silo T800](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=146545&title=fs2019)) expose unload points as exactFilRootlNodes.

Courseplay does not recognize these unload points as Tip Triggers, and therefore one cannot build fieldwork courses that unload at these objects.

**Comment by polosubtil** [comment]
Hi @dp-github,
As it looks like you know what you are doing, do you know how we could add a tip trigger for the Grimme RH 24-60 as I mentioned in #5292 ?

**Comment by dp-github** [comment]
Lol - I assure you that I absolutely do not know what I'm doing.  No lua experience, no Courseplay experience, no FS19 modding experience.

But I'll have a look and see whether I can't figure something out.

**Comment by polosubtil** [comment]
All right, thanks mate. Your first experience looks promising ;)
