### ISSUE TITLE
Fehler MP

### ISSUE THREAD

**Issue by Bandesss** [Courseplay/courseplay#5615]
Hallo haben die Version 28.
Aber auf dem Server hängt es bei Syncronisieren mit anderen Spieler
Mit der 27 er keine Probleme
[server.log](https://github.com/Courseplay/courseplay/files/4774338/server.log)
[webserver.log](https://github.com/Courseplay/courseplay/files/4774339/webserver.log)

**Comment by Tensuko** [comment]
#5484 bleib bei V27 in V28 ist eh nur debuginfo drin.
