### ISSUE TITLE
crashing about every 20 - 30 minutes upon swithing vehicles - please help

### ISSUE THREAD

**Issue by kf6shc** [Courseplay/courseplay#5617]
i have tried numerous versions of CP

[log.txt](https://github.com/Courseplay/courseplay/files/4775268/log.txt)

thx -sean

**Comment by Tensuko** [comment]
newest CP, clean mods folder, several mods with errors.

**Comment by kf6shc** [comment]
i am reading you correctly. you want me to remove all mods but courseplay and try again. also, i had waiting workers mod, but removed it and now seems okay. please confirm your instructions. thank you
