### ISSUE TITLE
stuck on game load v6.02.00029

### ISSUE THREAD

**Issue by GitTomahawk** [Courseplay/courseplay#5619]
settings.lua:2090: attempt to compare number with boolean

also applies to v6.02.00028

**Comment by Tensuko** [comment]
complete logfile SP or MP ?

**Comment by GitTomahawk** [comment]
MP

**Comment by Tensuko** [comment]
#5620
#5484

**Comment by Timo35** [comment]
Same Error for me in local Log. I add Server and local log. 
I tried today Version 6.02.00031
Last Version where i can join the dedicated Server was 6.02.00027. Any Version after this, i can't join the MP Game on the dedicated Server.
[log_server.txt](https://github.com/Courseplay/courseplay/files/4793861/log_server.txt)
[log_local.txt](https://github.com/Courseplay/courseplay/files/4793865/log_local.txt)
