### ISSUE TITLE
CP problem with Multiplayer

### ISSUE THREAD

**Issue by wertigoxxx** [Courseplay/courseplay#5620]
When the CP is in the mode folder, the other player cannot sit in the tractor, it makes a mistake!
v6.029 version!!!

![fsScreen_2020_06_14_10_36_47](https://user-images.githubusercontent.com/65092037/84589008-10b03980-ae2c-11ea-8263-8c9554873e0a.png)

**Comment by Bandesss** [comment]
Wir kommen garnicht auf den Server gleiches Problem war mit der 28er Version
27er alles gut auf dem Server

**Comment by schwiti6190** [comment]
Could you both please post a complete log file, so I can have look at

**Comment by Tensuko** [comment]
keep this in mind.... #5484
stick to 27 or provide needed information such as logfiles and stuff, else it is no help at all...

**Comment by Bandesss** [comment]
Meiner war gestern hinterlegt .... Ich schaue

**Comment by wertigoxxx** [comment]
Sry :)

![fsScreen_2020_06_14_13_28_09](https://user-images.githubusercontent.com/65092037/84592070-12d1c280-ae43-11ea-9a8e-2cb816e6ef04.png)

LOG:
[log.txt](https://github.com/Courseplay/courseplay/files/4776310/log.txt)

**Comment by schwiti6190** [comment]
@wertigoxxx Did you post the client or server log ?

**Comment by wertigoxxx** [comment]
> @wertigoxxx Did you post the client or server log ?

client.

where can i find the server log file? :)

**Comment by CxlledTxntx** [comment]
Dont know but there is the same problem at mine

**Comment by Kamparan0** [comment]
Same here.. Last running Version on MP is 6.02.00026

**Comment by Tensuko** [comment]
Even if 10000 ppl say 'same problem' it wont help anything without the needed logfiles...

**Comment by Kamparan0** [comment]
I really tried to find it. Logged in with Filezilla to my server but there was no log file. The only log I could provide is the local log file. Does it help?

**Comment by Kamparan0** [comment]
@Tensuko Kann Dir gerne TeamViewer öffnen und Du kannst es selber mal direkt auf meinem Rechner versuchen, falls das helfen sollte.

**Comment by Kamparan0** [comment]
Maybe it helps: 2 logfiles Both with CP 6.02.00029
Single Player and Multiplayer (same savegame) SP runs fine, MP (Nitrado-Server) does not start at all

[log 00029_multi_local.txt](https://github.com/Courseplay/courseplay/files/4776522/log.00029_multi_local.txt)

[log 00029_single_local.txt](https://github.com/Courseplay/courseplay/files/4776524/log.00029_single_local.txt)

**Comment by Tensuko** [comment]
![serverlog](https://user-images.githubusercontent.com/27344744/84595862-9814a180-ae5a-11ea-8516-32ed6796716c.png)

**Comment by Kamparan0** [comment]
game.log ist leer.

[server.log](https://github.com/Courseplay/courseplay/files/4776585/server.log)

**Comment by CxlledTxntx** [comment]
Do u still need logfiles?

**Comment by Bandesss** [comment]
Noch eine von der 27er
[Game.txt](https://github.com/Courseplay/courseplay/files/4776834/Game.txt)

**Comment by schwiti6190** [comment]
After locking at the last logs I've identified the problem, might be fixed in the next version, as I've put a possible fix on there with my last commit

**Comment by Bandesss** [comment]
Wie gesagt connecten auf den Mp Server geht mit der aktuellen CP Version nicht .
Danke für eure Mühe

**Comment by Tensuko** [comment]
Try Version 00032 and report.

**Comment by Bandesss** [comment]
Werden wir machen

**Comment by Kamparan0** [comment]
Thanks for all your efforts, patience and your message. 

Start is fine. I am able to join a MP-Game with 00032. That is more than happend before. Will test the new release within the next few days.

**Comment by Kamparan0** [comment]
Hi,

After interrupting a course - refilling - I am not longer able to restart at any waypoint but the first waypoint. I tried all options but vehicle always tries to start at first waypoint.

**Comment by schwiti6190** [comment]
@Kamparan0 could you try this with differnet modes ? I would like to know if this one is a general problem or specific for this one.

**Comment by Bandesss** [comment]
Auch bei uns kommt man wieder auf den Server

Danke an das ganze Team

**Comment by Tensuko** [comment]
I take this Issue as solved for now, sure there are more Bugs in MP, but our new Team Member works hard on get everything MP ready. :)
