### ISSUE TITLE
Lane offset not working

### ISSUE THREAD

**Issue by Dennizzzzz** [Courseplay/courseplay#5623]
I was setting up dual machine fieldwork for the first time the 'old' fashion way. Setting a course for one tractor, with double width, and setting the lane offset to half of the with to the right. But it seems the lane offset is not working (anymore).

Later I found the Multiple Tools setting in the advanced settings during course generation, this works fine.

But is seems the lane offset itself is not working.

![2020-06-14 16_01_02-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/84595870-a4006380-ae5a-11ea-8973-3d14742798ff.jpg)

Courseplay for FS19 v6.02.00029
Map: NF Marsch V2.8 (Nordfriesische Marsch)

[log.txt](https://github.com/Courseplay/courseplay/files/4776556/log.txt)

**Comment by Tensuko** [comment]
LaneOffset like this got no use anymore.
If want use multi tools, create a course for that.

**Comment by Dennizzzzz** [comment]
I know that this is not used anymore like this. But if you just want a Lane Offset, it looks like it is not working.

**Comment by Dennizzzzz** [comment]
> 
> 
> LaneOffset like this got no use anymore.
> If want use multi tools, create a course for that.

I know that this is not used anymore like this. But if you just want a Lane Offset, it looks like it is not working.

**Comment by Tensuko** [comment]
We don't need Lane Offset for anything.
If you think about bale collector or anything, it is tool offset.
