### ISSUE TITLE
Kann mit den Editor nicht mehr speichern

### ISSUE THREAD

**Issue by xerion8300** [Courseplay/courseplay#5624]
Welche Informationen benötigt ihr.
Wenn ich den Kurs bearbeite kann ich ihn nicht mehr abspeichern.
Habe auch schon probiert mit einer anderen Tastenbelegung, aber geht auch nicht.

**Comment by Tensuko** [comment]
Logfile, schritte die du unternimmst usw.
Nur so am Rande: vor 10 min habe ich eine Kurs editiert, war gar kein Problem...

**Comment by xerion8300** [comment]
Habe den Fehler gefunden.
Habe drei einzelne Kurse eingespielt aber ihn dann nicht zu einen Kurs gespeichert.
Habe es nun gemacht und funktioniert.
**Trotzdem besten Dank für euren guten und schnellen Support**
