### ISSUE TITLE
CONNECTION PROBLEM WITH FRIENDS IN MP

### ISSUE THREAD

**Issue by leo32128** [Courseplay/courseplay#5625]
I noticed that in v6.02.00029 and v6.02.00028, the MP does not work, the people who play with me cannot connect to the server returning to v6.02.00027 and the problem is solved. Am I doing something wrong? , because I tried almost everything and I was unable to solve the problem in the last two versions, the friends after the synchronization are not online with me on the server, thanks in advance for the good work with CP!

**Comment by KITT3000** [comment]
#5620

**Comment by BIMCodeAus** [comment]
Can i please get version v6.02.00027

**Comment by leo32128** [comment]
na v6.02.00027, funciona perfeitamente !
