### ISSUE TITLE
CP not showing lease harvester

### ISSUE THREAD

**Issue by Miketeg** [Courseplay/courseplay#5626]
Hello ! I leased an Panther 2 to harvest Sugarbeat on my farm. Unfortunately, it does not show up in the combine list to select it for the "unloader" tractor.

Not a big thing, but just wanted to let you know in case you were not aware.

Thanks for all your work ! CP make this game some much fun !

**Comment by Tensuko** [comment]
Try change to mode1 or mode 5 and back to mode2, then it should show up.

**Comment by Tensuko** [comment]
As I saw in a Lets Play, somehow it pops up when restart savegame or for some other reason, going to check on this...

**Comment by Tensuko** [comment]
Getting a Combine with leasing, it won't register into CombineList, tested with .00067

**Comment by Tensuko** [comment]
Somehow this is fixed...
