### ISSUE TITLE
Andere Einstellungen nach CP-Update

### ISSUE THREAD

**Issue by f4mous96** [Courseplay/courseplay#5627]
Hab das neuste CP-Update heute auf meinem SP SPielstand mal installiert und wenn ich CP losfahren lasse, hat er plötzlich andere einstellungen wie bei der vorherigen version.
Zb. ist die geschwindigkeit bei allen plötzlich auf maximale geschwindigkeit eingestellt statt auf wie beim einfahren. und die option "planen" ist immer auf deaktiviert statt aktiviert.

Ist die gewollt?

**Comment by Tensuko** [comment]
Das liegt wohl an dem Update der Settings, nicht wirklich ein Issue...

**Comment by f4mous96** [comment]
und was muss ich da dann einstellen das es dann wieder bei den "alten" einstellungen bleibt? das immer hinklicken ist doch mehr aufwand als nutzen

**Comment by Tensuko** [comment]
Da muss man nichts umstellen.
Du musst halt einmal deine Einstellungen neu machen und gut, die werden schon gespeichert, wenn nicht, Issue mit sauberen logfile!
