### ISSUE TITLE
Problem mit Courseplay und ManureSystem

### ISSUE THREAD

**Issue by Omat1998** [Courseplay/courseplay#5628]
Moin,
ich habe ein Problem mit der neuesten Courseplay Version und der neuesten ManureSystem Version.
Wenn ich einen Zubringer Kurs erstelle findet der Abfahrer zwar den Trigger ( unten im Bild steht: wird beladen) aber er hält nicht an und der Überladevorgang startet auch nicht.
habe es auf der Standard Map probiert nur mit diesen beiden Mods.

Hatte es mal in einer Alten Version von Courseplay probiert und da klappte es.
Vielleicht kann mir hier ja einer helfen.
LG Omat1998
[log.txt](https://github.com/Courseplay/courseplay/files/4782264/log.txt)

**Comment by Tensuko** [comment]
Modus, Tools, wie sieht der Kurs aus und im log sehe ich nur CP V20 aber nicht V29

**Comment by Omat1998** [comment]
Mir ist gerade selber aufgefallen, dass ich die falsche Log hochgeladen habe. Hier ist nun die richtige mit V29
[log.txt](https://github.com/Courseplay/courseplay/files/4782425/log.txt)

Ich habe den Standard MAN und den Standard Kotte Gülle Auflieger benutzt.
Den Kurs habe ich im Trigger gestartet, bin ein Stück gefahren und dann ein Haltepunkt gesetzt, dann weiter bis ca. 15m vor den Trigger gerade vor den Startpunkt und dort dann den Endpunkt gesetzt. 
Modus war der Feldversorgungs Modus (Modus 8?)

**Comment by Tensuko** [comment]
muss ich mir die tage angucken...

**Comment by Omat1998** [comment]
Ok alles klar 😄 
Vielen Dank für die schnelle Antwort!

**Comment by Omat1998** [comment]
Kann von meiner Seite aus geschlossen werden, Problem wurde mit dem neuesten Update des Manure System beseitigt!

LG Omat
