### ISSUE TITLE
Courseplay - Multiplayer   (English & German)

### ISSUE THREAD

**Issue by Astrosegler** [Courseplay/courseplay#5630]
English

Hello everyone.

As you know, the course play with version 26 is the last version that could be used in the MP.

The 27, 28, 29 and 30 version does not work in the MP.

Are there any approaches to when a multi-player courseplay version can be released !?

lg Micha

German
Hallo in die Runde.

Wie ihr wisst, ist der Courseplay mit der Version 26 die letzte Version die man im MP nutzen konnte. 

Die 27er 28er 29er und 30er Version klappt nicht im MP.

Gibt es schon Ansätze, wann ein multispieler fähige Courseplay Version rauskommen kann!? 

lg Micha

**Comment by Tensuko** [comment]
Lesen hilft... #5620 und #5484
