### ISSUE TITLE
Combine drives away from tractor then tractor gets in the way

### ISSUE THREAD

**Issue by TruckinFool** [Courseplay/courseplay#5631]
The issue I noticed yesterday is the combine would fill up, the tractor would head to the combine with no problems.  The tractor arrives at the combine, combine pipes out and once it hits the trigger, the combine drives away.  The tractor also drives along with the combine, but when the combine reaches the end of the row, the tractor is in the way and the combine cannot turn around for the next row.  Is there a way to set it up so the combine will unload before continuing?

**Comment by sistem442** [comment]
You can revert to 6.02.00012. In that version combines were stationary while unloading.

**Comment by TruckinFool** [comment]
> You can revert to 6.02.00012. In that version combines were stationary while unloading.

Will do.  Thanks for the help.

**Comment by TinyCrocodile** [comment]
You can also just set this in the combinesettings.

**Comment by TruckinFool** [comment]
> You can also just set this in the combinesettings.

Thanks.  Don't think I ever looked at those settings, lol.
