### ISSUE TITLE
Combine harvester and long search of lands and the crossing of routes

### ISSUE THREAD

**Issue by wertigoxxx** [Courseplay/courseplay#5633]
Hy guys!

When the combine is completely unloaded, the trailer is full and you plan the route, don’t wait for the combine to leave, immediately cross the road and collide.

**Again, you won’t find the combine quickly.**
**long route planning**
Up to 20-30 seconds

**It would be better for the tractor to wait for the combine to unload, leave and then plan the route!**

![fsScreen_2020_06_16_17_27_17](https://user-images.githubusercontent.com/65092037/84808885-9b9a5b00-b009-11ea-8d7c-3e8c75073c59.png)
![fsScreen_2020_06_16_17_27_26](https://user-images.githubusercontent.com/65092037/84808905-a228d280-b009-11ea-80bd-fa8a69453bfa.png)
![fsScreen_2020_06_16_17_27_40](https://user-images.githubusercontent.com/65092037/84808910-a3f29600-b009-11ea-9690-c21e19f5b042.png)
![fsScreen_2020_06_16_17_27_50](https://user-images.githubusercontent.com/65092037/84808930-a94fe080-b009-11ea-9327-4b7c2d8aa1be.png)
![fsScreen_2020_06_16_17_28_11](https://user-images.githubusercontent.com/65092037/84808943-af45c180-b009-11ea-921a-fc74ea8a6ffe.png)

LOG:
[log.txt](https://github.com/Courseplay/courseplay/files/4788228/log.txt)

**Comment by Tensuko** [comment]
I don't get it. If the Combine is empty and trailer is full, the tractor with trailer calculate router to unload start while Combine continue to harvest.
So what is not working ?

**Comment by wertigoxxx** [comment]
english:
do not wait for the tractor to leave after the event.
to better understand: the trailer is 100% planning the route, so far no problem!
however, when the combine is sideways and the trailer is so full, the tractor does not back down, but immediately plans the route and collides with the combine.

deutsch:
Warten Sie nicht, bis der Traktor nach dem Ereignis abfährt.
Zum besseren Verständnis: Der Trailer plant die Route zu 100%, bisher kein Problem!
Wenn der Mähdrescher jedoch seitlich ist und der Anhänger so voll ist, fährt der Traktor nicht zurück, sondern plant sofort die Route und kollidiert mit dem Mähdrescher.

**Do you understand ?**

**Comment by pvaiko** [comment]
Értjük.

**Comment by Tensuko** [comment]
So Tractor is full, Tractor reverse, Combine continue work, Tractor plans route to unload course.

**Comment by wertigoxxx** [comment]
not quite so! :)
the tractor is full, it should be reversed to release the combine, but it does not :( (the combine does not wait and goes to the tractor)
then comes the collision

**Comment by Tensuko** [comment]
We already have some Issues with Combine that colides with the Trailer.
Should be alredy better, rest ist Pathfinder aware of Trailer.
