### ISSUE TITLE
Seeders and Planters Won't Refill

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#5634]
CP versions 29 & 30
Map: Lone Oak
When sewing on fields with CP and with a 2nd course appended to refill the seeder, CP will drive by the Lizard Mod refill silo, with the message saying loading XXX, but drives on without reloading. When fertilizing the equipment is refilled from the Lizard Solid fertilizer. When spreading lime, it also does that. It worked on CP version 27. I didn't try version 28, but it doesn't work on 29 or 30.
[log.txt](https://github.com/Courseplay/courseplay/files/4789524/log.txt)

**Comment by Tensuko** [comment]
What Seeder ?
Fronttank ?
Pics of where you bypass the tanks might help.

**Comment by lcc1211** [comment]
Vaderstad Rapid A600S, Amazone D830 (vanilla) & Amazone D8 40 from Modhub and the mod from attached which is also from Modhub.
![20200617062818_1](https://user-images.githubusercontent.com/24764870/84887611-fcef1800-b063-11ea-929a-804d58c17855.jpg)
![20200617062820_1](https://user-images.githubusercontent.com/24764870/84887621-ffea0880-b063-11ea-8063-de60a3e25fb4.jpg)
![20200617062821_1](https://user-images.githubusercontent.com/24764870/84887630-04162600-b064-11ea-8f4b-813b03c5fa35.jpg)
![20200617062823_1](https://user-images.githubusercontent.com/24764870/84887633-06788000-b064-11ea-843c-fc52fb2037c9.jpg)

**Comment by lcc1211** [comment]
https://youtu.be/JJRpQgSD9z8

**Comment by Tensuko** [comment]
Ok this is strange, I will try this out later.

**Comment by Tensuko** [comment]
Change the option of the lids to activated, it is on the 8th page. We will change it back to default activated, this was not intended :) Just did test it and it works :)
