### ISSUE TITLE
Error: Running LUA method 'update' - toolManager.lua:441: attempt to call method 'getAttachedImplements' (a nil value)

### ISSUE THREAD

**Issue by SViking** [Courseplay/courseplay#5635]
With Courseplay 6.02.00026 loaded, attempting to attach ("Q") a pallet to a CSZ equipment pack pallet fork causes the pallet to defectively attach.  It will move with the fork, but not only loosely.  UI continue show option to attach pallet, but subsequent attempts result in no state change.  Subsequent keystrokes (e.g., <esc> to menu) will work once, but then fail on second attempts.

**Comment by Tensuko** [comment]
logfile ?!

**Comment by SViking** [comment]
Logfile attached.  I forgot to mention that this error is occurring with the telehandler pallet forks.  

 

Cheers.

**Comment by masterjedi115** [comment]
ich habe da ein problem mit courseplay 6.02.00031 ,Error: Running LUA method 'packetReceived'.
C:/Users/Rudi2/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/settings.lua:2090: attempt to compare number with boolean
NF Marsch 4fach v2.0 komme nicht ins multlplaye spiiel rein

**Comment by CurtisFeatures** [comment]
I am also experiencing a similar issue except mine crashes the dedicated server and it must be reset to fix the error - Just logged this before i saw this one https://github.com/Courseplay/courseplay/issues/5693

**Comment by Tensuko** [comment]
Old Issue and sure it is a Mod Conflict with CSZ, maybe already solved.
