### ISSUE TITLE
mode2 Wendekreis

### ISSUE THREAD

**Issue by dennisblack777** [Courseplay/courseplay#5636]
Hallo,

ich benutzte für das Drescher anfahren einen Fendt MT 1165 MT und HaulMaster Überladewagen. Leider wird der Wendekreis oft so eng gewählt, dass sich das Gespann nur schwer fortbewegt und das Wenden dauert 3-5min. Gibt es eine Möglichkeit das zu beeinflussen? 

Danke und Grüße

**Comment by TinyCrocodile** [comment]
#5350 Has some information about this

**Comment by dennisblack777** [comment]
thank you @TinyCrocodile i've added <turningRadiusLimitation> to the .xml  file and now it works much better!

**Comment by Tensuko** [comment]
woops, thank you @TinyCrocodile closing
