### ISSUE TITLE
Question : field speed

### ISSUE THREAD

**Issue by mrPassion78** [Courseplay/courseplay#5637]
Hi there, i was wondering if it would be possible to have an setting for tractor speed in the field, while the implement is not in use .

What do i mean here? 
I`m currently running a seeder on a 74 arce field with CP and AD (for loading seeds), and the seeding speed i have set to IRL 5kmh.
that works perfectly , just untill the tractor has to drive to the First waypoint where it should start, or retun to the last point after refill, and the tractor than drives over 10 min to the last/first point to where it will start, due to the setting of fieldspeed 5KMH.

Thats why it would be awesome to have a sepperate speed function , like in AD (field speed), just for the time that no implement is active, and after reaching the start point , it would switch to the set speed for seeding in my case.

I cannot thank you  enough for all the work youve done so far, and i have no clue how much work that would take to implement such a thing, IF even possible.

Thnx Pascal

**Comment by Tensuko** [comment]
![fieldspeed](https://user-images.githubusercontent.com/27344744/84897461-e669b080-b0a5-11ea-94e7-307f403ba35d.png)

**Comment by mrPassion78** [comment]
LOL.. maybe i explained it wrong..i  will try again..
That field speed is indeed a speed witch the tractor can drive at in the field..but that same speed is used for using an implement i.e. seeding..that would mean in you pic that the tractor would be able to seed at 24kmh, if it can reach that, 
so what i wonder is...could that setting be split for NO-ACTIVE field speed and ACTIVE-field speed.
That way the tractor can drive at 24kmh to the startpoint, and from there on, when active seeding, it would bee set at i.e. 5kmh.

i hope this makes it more clear :D

**Comment by Tensuko** [comment]
So we don't need a new speed Setting, we need this to work the right way.
use that Speed on Field, as the Tools don't need to be regulated in speed.

Would that fit what you looking for ?

**Comment by mrPassion78** [comment]
not really , or i am reading it wrong.
i would like to have the tractor travel to the first way point at 24kmh across the field, and when it starts seeding i would like to be able to reduce that speed automatically  via a setting to 5kmh.

Sins only a few planters can plant over 10kmh IRL, while maintaining  accuracy , and thats what i`m after, just to be able to set the tractor to a reduced speed for ACTIVE seeding or plowing or whatever, and when it is driving to the startpoint, that it than would takeover the setting of fieldspeed, 24kmh..so it does not take 15min to reach the startpoint with the fieldspeed set to 5km, to reduce the seedingspeed.

I hope it makes sence what i`m after.. lol.

and thnx for the quick reply on this all.

**Comment by MtBakerScum** [comment]
are you using a mod or ingame seeder? Courseplay uses the defined implement speed in whatever implement you are using.    

So if you are using a seeder with a define working speed of 10mph, and you have courseplay field speed of 25mph, CP will plant at 10mph, then increase to 25mph when its moving about the field.  I think rather than asking for an additional speed setting, you should modify the implement speed in your mods .xml file. If its an ingame seeder you'll have to dig deeper to change the implement speed.

**Comment by mrPassion78** [comment]
i would like the enhancement that i can set a seeding or cultivating speed with CP, and not via the xml.
why?..well if i want to seed wheat it can be done at i.e. 7kmh IRL, and with canola maybe faster or less..and still using the same seeder, thats why i wanted to ask for a setting ONLY for when the implement is active.
so if i want to cultivate with a disc cultivator, i do not want it to go at max speed, i.e 10-15kmh, sins i would like the option to let it run slower... and i can easily change that in the xml, but if the next field i would like to disc faster, i would have to end the game..change the xml..start again.

so to avoid that, i requested a feature to set a speed for when implement active.
even the case with spraying..
with fertilizer you usually spray slow..and with herbicide, you spray faster..if i use the same tool. i would again have to change the xml.

i hope this makes sense  :D.

**Comment by Tensuko** [comment]
We won't limit the Speed with an extra Setting.
What you could try is to reduce the CC speed of your vehicle while it is running with the seeder.
