### ISSUE TITLE
Transfer mod speed stuck at 3mph or 6mph

### ISSUE THREAD

**Issue by ConstructionGamer** [Courseplay/courseplay#5640]
Version 6.2.31. I have recorded a couple of transfer courses each with a trigger point at the end for the driver to stop at. But the fastest they will drive at is fixed at either 3 or 6mph. Tried changing 'speed from recording' to 'maximum speed'. Tried 2 different tractors both with and without trailer.

**Comment by JDTiger** [comment]
stop the driver and push the cruise control speed up to max, the tractor won't ever drive faster then the CC speed set before starting the CP driver

**Comment by Tensuko** [comment]
Closed due to inactivity.
Reopen when attach logfile with channel 12 and 14, screenshots and maybe the course file.
