### ISSUE TITLE
I can't play multiplayer after v6.02.00028

### ISSUE THREAD

**Issue by leo32128** [Courseplay/courseplay#5641]
Hello to all friends, after v6.02.00028 I can't play multiplayer anymore, friends can't connect to my server, is there anyone with the same problem? in v6.02.00027, it works normally, When I open a new game it works correctly in the latest versions, but a game already saved, the problem I describe above always happens, can someone help me?

**Comment by Tensuko** [comment]
Sticky: #5484
Duplicate: #5620
And on top no logfile. Closed!
