### ISSUE TITLE
suggestion :  route counter liquid transportmode

### ISSUE THREAD

**Issue by evybart** [Courseplay/courseplay#5642]
is it possible for a counter when you use liquid transportmode as in the first transportmode verry handy when you if the supply a factory 
thanks for the great job

**Comment by Tensuko** [comment]
Nope, couse we don't have liquid transportmode anymore, it is all done by mode1.
There is only a bug right now where you can't start those manure Trailers in Mode1, wich might be a bit more complicated. So, just use Mode1...

**Comment by evybart** [comment]
bud i use the transportmode liquid in the 6.2.28 version the mode is not away from de hud did i something wrang then

**Comment by Tensuko** [comment]
That Mode is no longer liquid transport mode, it is field supply and right now only used for liquid manure to bringt to a field container or stay in positon so liquiad manure spreader can refill. Normal Transportation is Mode1 and it does (should) work easy for Water and Milk and basically all kind of FillTypes.
