### ISSUE TITLE
mode2 unloader doesn't drive to combine from unloading point

### ISSUE THREAD

**Issue by dennisblack777** [Courseplay/courseplay#5644]
Hello Guys,

the unloader follows the combine perfectly and drives correct to the unloading point but only for one time. Any sugguestions on this?

when i stopp the unloader and drive few meters away and start him again, he finds the combine asap.

thank you

![ls19](https://user-images.githubusercontent.com/5053027/85056468-92db8d80-b19f-11ea-9f81-d9b535fb03b1.png)

[log.txt](https://github.com/Courseplay/courseplay/files/4800383/log.txt)

**Comment by Tensuko** [comment]
Nur ein Abfahrer ? Abfahrer Priorität auf Entfernung ? Wie sieht der Start aus ? Was passiert wenn du Fruchtumfahrung im HUD aus machst, geht es dann ?

Info zu deiner Log:
Immer nur eine Karte im Mods Ordner!

**Comment by dennisblack777** [comment]
@Tensuko ein Abfahrer auf dem Feld (Überladewagen), Priorität auf Entfernung, Fruchtumfahrung ist deaktiviert und der Start sieht meistens so aus bei mir:

![ls19](https://user-images.githubusercontent.com/5053027/85059663-52324300-b1a4-11ea-9458-3034110b6196.png)

Auch ist mir aufgefallen, dass der Abfahrer öfter über den Wartepunkt ein paar Meter zu viel hinhaus fährt (zu viel Geschwindigkeit?) und danke für die Info und schnelle Antwort.

**Comment by Thrall7734** [comment]
i can confirm that im having the same problem.

**Comment by Tensuko** [comment]
Und ich sehe 2 Abfahrer und einen sehr komuschen Kurs mit Wartepunkt...

**Comment by Tensuko** [comment]
Baut doch einfach mal die Kurse so wie wir es vorschreiben... Ansonsten braucht ihr euch nicht wundern wenn es nicht geht...

**Comment by dennisblack777** [comment]
> Baut doch einfach mal die Kurse so wie wir es vorschreiben... Ansonsten braucht ihr euch nicht wundern wenn es nicht geht...

@Tensuko Wo finde ich denn die korrekte Beschreibung? Sorry spiele LS19 erst paar Wochen.

**Comment by Tensuko** [comment]
![mode2](https://user-images.githubusercontent.com/27344744/85224421-90a94700-b3ca-11ea-9c22-8a934616c19c.png)

Ansonsten #5272 das Video gucken und lesen, immerhin sind ÜLW nicht offiziell unterstützt und den Modus für ÜLW gibt es noch nicht.

**Comment by dennisblack777** [comment]
@Tensuko ich danke dir für die Infos, war mir nicht bewusst.
