### ISSUE TITLE
Courseplay and Added Realism For Vehicles

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#5645]
I tried with the latest version of the "Added Realism For Vehicles" mod and I noticed that there are various problems in the log (I'm using a tractor to plow in the meantime). Can you clarify? thanks

[log.txt](https://github.com/Courseplay/courseplay/files/4801459/log.txt)

**Comment by Tensuko** [comment]
GIANTS Lua Error.
No Idea what it is.
Remove CP from mods Folder and try if Error is gone, else I say remove REA....

**Comment by 0Pietro20** [comment]
I tried to create a new game not including the Courseplay but keeping the "Added Realism for Vehicles" and, using the standard FS worker the usual error appears

[log.txt](https://github.com/Courseplay/courseplay/files/4803207/log.txt)

**Comment by Tensuko** [comment]
So its REA Issue not CP one.
