### ISSUE TITLE
Hide HUD key not working on Manage Courses tab

### ISSUE THREAD

**Issue by Dennizzzzz** [Courseplay/courseplay#5646]
When I'm on the Manage Courses tab, I'm unable to close the hud with a key.

![2020-06-19 10_15_56-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/85112506-002a0580-b216-11ea-83b2-09a5fae8f3df.jpg)

On all other tabs, I can use the Delete button to hide the HUD.

![2020-06-19 10_10_41-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/85112251-a1fd2280-b215-11ea-9032-234f8fdbdc8e.jpg)

Courseplay for FS19 v6.02.00031
Map: New Woodshire v1.1.0.1
[log.txt](https://github.com/Courseplay/courseplay/files/4803311/log.txt)

**Comment by Tensuko** [comment]
Becouse you have the mouse on the HUD, that is an area where no other actions work.
