### ISSUE TITLE
few issues on mode 2 when harvesting

### ISSUE THREAD

**Issue by franky135** [Courseplay/courseplay#5648]
Hello!
since your last update i have really bad issues on courseplay.
im harvesting luzerne/gras/hay with the kemper pack on Nordfriesische Marsch.
the gras was mowed, dryed and swathed by courseplay without any issues. the course from swathing is saved for the chopper like i always do.
now the issues:
- it doesnt matter if i choose 1 or 3 drivers to bring the gras to bga, they always get stuck behind the harvester and dont drive under its pipe to fill up the trailer. Instead they wait behind it. In past i just had to settle more distance in settings to make it work, but now this doesnt help.
- when i choose "unloading" for startpoint the drivers dont empty the trailer and come back full. on next or first waypoint it works.
- drivers dont use maximum speed on streets. always just from settings maximum speed on fields.
-as i now have to drive every tractor by myself to fill the trailer and set the speed by key 3 for it they do whole course on that speed if i dont speed up by key 2 to maximum before i start cp-driver again.

i attach my logfile for you and hope you can explain to me what im doing wrong.
[log.txt](https://github.com/Courseplay/courseplay/files/4804559/log.txt)

by the way: mode fieldwork works pretty well now!

Frank

**Comment by Tensuko** [comment]
#5272 https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ https://github.com/Courseplay/courseplay/wiki
Bisschen was zu lesen, dann versuch es noch einmal.

**Comment by franky135** [comment]
also ich weiss wirklich nicht, was ich falsch mache, denn vor eurem Update und bei allen anderen Versionen hat es so funktioniert. auch die mods nutze ich schon seit mindestens 6 Wochen ohne Probleme. ich hab mal die log gelöscht und euch die neue angehängt und von allen Einstellungen Screenshots gemacht. Übrigens kann ich beim Häcksler keine Seite für das Rohr mehr auswählen...
[log.txt](https://github.com/Courseplay/courseplay/files/4806348/log.txt)

Einstellung Abfahrer
![fsScreen_2020_06_19_20_06_01](https://user-images.githubusercontent.com/48451440/85172350-2af57780-b271-11ea-8e0e-1d9164663c86.png)
![fsScreen_2020_06_19_20_06_41](https://user-images.githubusercontent.com/48451440/85172363-321c8580-b271-11ea-84ab-32e79ae805e3.png)
![fsScreen_2020_06_19_20_06_56](https://user-images.githubusercontent.com/48451440/85172373-38aafd00-b271-11ea-872d-1ec7a7b39b3f.png)
![fsScreen_2020_06_19_20_07_15](https://user-images.githubusercontent.com/48451440/85172388-3f397480-b271-11ea-9f61-f5d5479ce2a3.png)

Abfahrerstartpunkt auf Unloading durchfährt den Silo ohne abzuladen
![fsScreen_2020_06_19_20_14_14](https://user-images.githubusercontent.com/48451440/85172400-45c7ec00-b271-11ea-8530-3512eea28620.png)
![fsScreen_2020_06_19_20_14_19](https://user-images.githubusercontent.com/48451440/85172411-4ceefa00-b271-11ea-9b69-9c601d9c2959.png)
![fsScreen_2020_06_19_20_14_28](https://user-images.githubusercontent.com/48451440/85172424-52e4db00-b271-11ea-8ffb-8aeec97c5a5e.png)

Tempomat zum manuellen Befüllen genutzt, wird beim Abfahren von CP nicht übersteuert wie in den älteren Versionen
![fsScreen_2020_06_19_20_18_24](https://user-images.githubusercontent.com/48451440/85172433-5a0be900-b271-11ea-9abf-77256645a062.png)
![fsScreen_2020_06_19_20_21_15](https://user-images.githubusercontent.com/48451440/85172446-61cb8d80-b271-11ea-9c03-a64a3b251542.png)
![fsScreen_2020_06_19_20_22_08](https://user-images.githubusercontent.com/48451440/85172453-6a23c880-b271-11ea-8f02-88e31601faa9.png)
![fsScreen_2020_06_19_20_23_16](https://user-images.githubusercontent.com/48451440/85172484-73149a00-b271-11ea-8fd3-6546b6d5f98c.png)

Startpunkt erster Wegpunkt- Fahrer entlädt im Silo
![fsScreen_2020_06_19_20_40_42](https://user-images.githubusercontent.com/48451440/85172500-7a3ba800-b271-11ea-944b-aa22449a1b79.png)
![fsScreen_2020_06_19_20_41_20](https://user-images.githubusercontent.com/48451440/85172505-80ca1f80-b271-11ea-9e1d-ee3933d8b13f.png)

**Comment by Tensuko** [comment]
Du hast dir wieder nichts durchgelesen, ansonsten müsstest du nicht diese Fragen stellen.

Alter Mode2 = weg, neuer Mode2 ist da, da gibt es nichts zum Seite einstellen.

Bisher funktioniert nur der BigX gut.

Es ist nur ein Abfahrer unterstützt.

Wo sind die logfile daten mit channel 4 7 12 und 14 ?

Das Video was im #5272 zu sehen ist erklärt auch einiges.
