### ISSUE TITLE
Feature request: extra button to replace course

### ISSUE THREAD

**Issue by Dennizzzzz** [Courseplay/courseplay#5650]
It would be nice to have an extra button in the managed courses tab that will replace the existing loaded course. 

Now when you want to load another course, you first have to use the clear current course button, than load another one.

![2020-06-19 17_48_09-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/85152306-215e1680-b255-11ea-9a32-6e04258d0ba6.jpg)

**Comment by Tensuko** [comment]
Add to collection: #6270
