### ISSUE TITLE
Several issues detected

### ISSUE THREAD

**Issue by Saskfarmer** [Courseplay/courseplay#5651]
Hey guys so some issues i came across with 6.02.00031

#1 multiple tools- i have 3 combines in a field field with convoy activated, they are all set for 40m. 1 and 2 obey the set distance, 3 does not. I even set combine 3 to 2000m and it didnt change a thing, combine 3 will ignore the convoy distance and over take combine 2 no matter what, this is with 1 headland set. However with no headland and 6 combines they will obey the set distance perfectly. In version 6.01.00381 the convoy distance worked fine with 6 combines and with having the course set with one headland.

#2 Mode 2- I have been trying to use mode 2 to replace mode 3. Ive been using wait points to stop the grain cart so that it can unload into a trailer. In version 6.01.00381 the tractor and grain cart would stop at the two wait points i would set. With the newest update my tractor will ignore the wait points and eventually end up off course and cant find its way back to the stop point of the course. The path finding in field, is phenomenal for mode 2 absolutely brilliant, and is a tremendous improvement. Absolutely blown away!

#3 Grain transport- I run the wilson super bee's they worked perfect in version 6.01.0381 by unloading both trailers since they only had one hopper for each trailer. In the latest version i can only unload the back trailer of the super bee's because the truck will not brake soon enough at the tip trigger. the tip trigger is maybe 10ft by 5ft so its small but worked before in version 6.01.00381. it will brake soon enough though if the tip trigger is 60ft by 20ft and will actually unload both trailers at the same time. 

I'm new to this issue reporting so i apologize in advance if i didnt provide enough. Willing to do what it takes to help resolve. Love the work all of you are doing to keep the best of mod of FS ever, alive!

**Comment by Tensuko** [comment]
Some Stuff to read first and several Problems in one Issue is always hard to maintain.
All Issues you wrote there are already known and posted somewhere.

https://github.com/Courseplay/courseplay/wiki
https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ

#5484
#5272
#3882
