### ISSUE TITLE
Courseplay for FS19 v6.02.00031 stuck at 29% of sync on dedicaded root

### ISSUE THREAD

**Issue by Justice-Molton** [Courseplay/courseplay#5652]
it's not possible to use CP on a dedicated root since v6.02.00028, because the sync gets stuck on an MP. v6.02.00027 works just fine. logs from our today test with v6.02.00031are attached 
[client_log.txt](https://github.com/Courseplay/courseplay/files/4807536/client_log.txt)
[server_log.txt](https://github.com/Courseplay/courseplay/files/4807537/server_log.txt)

**Comment by Tensuko** [comment]
grrrr

#5484

 #5620

a bit reading Issues before blind post Issues would save me a lot of work......

**Comment by Justice-Molton** [comment]
Okay Tensuko, we‘re done here. You might should have a look what the guys do in the last releases. Every version since the 27 has something with MP fixes to do, so we thought its maybe helpful to let the programmer know that these fixes are not really fixes the sync issues. 
Goodbye and have a nice one
