### ISSUE TITLE
My driver does not find any vehicle in the field

### ISSUE THREAD

**Issue by simon198205** [Courseplay/courseplay#5653]
In the current visions, my driver does not find any vehicle in the field. What could be the problem?
Stand on the field
Downhill is set to distance

Vision 6.01.00399 has been working since vision 6.02

**Comment by Tensuko** [comment]
read #5272 and https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ

**Comment by simon198205** [comment]
I have set everything as usual, there is just no blinking downhill, but does not start
