### ISSUE TITLE
QUESTION: Foraging grass

### ISSUE THREAD

**Issue by kwguk** [Courseplay/courseplay#5654]
When you're foraging maize once youve been round outside the unloader will switch to driving alongside the forager. Unless im mistaken this doesnt seem to be the case when picking up grass using a forager. Is it possible to make the unloader drive alongside the forager when picking up grass?

**Comment by TinyCrocodile** [comment]
This is a known issue. The reason is, that harvested grass still counts as fruit. Cant link because didnt find the duplicate.

**Comment by excubated** [comment]
I have no idea how to reference other issues, here are my two best guesses:

#5470

https://github.com/Courseplay/courseplay/issues/5470

**Comment by Tensuko** [comment]
Duplicate
