### ISSUE TITLE
Slurry spreading not working

### ISSUE THREAD

**Issue by Dennizzzzz** [Courseplay/courseplay#5655]
Trying to put slurry on a field with CP, but all slurry stays in the tank.

First image, showing the start. You see the slurry in the tank is 64%
![2020-06-20 21_18_47-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/85209928-2f3a9700-b33c-11ea-9abf-624a81877b40.jpg)

After a while, the slurry is still 64%.
![2020-06-20 21_18_56-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/85209946-5db87200-b33c-11ea-8528-783430087448.jpg)

The animation of the slurry getting on the field is showing.

I stopped CP, and started manual, and now you see the slurry on the field. You do not see this when fertilizing with CP.
![2020-06-20 21_19_18-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/85209958-72950580-b33c-11ea-852f-fecac8225e86.jpg)

Tried this with another slurry tank, same issue.

Courseplay for FS19 v6.02.00031
Map: New Woodshire v1.1.0.1
[log.txt](https://github.com/Courseplay/courseplay/files/4808464/log.txt)

**Comment by Dennizzzzz** [comment]
Just noticed that during seeding and fertilizing with another tractor, the fertilizer percentage is also not decreasing, but the field is fertilized:

During seeding and fertilizing
![2020-06-20 21_34_42-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/85210219-51351900-b33e-11ea-97ae-f6830d63f6a5.jpg)

Later on the seeding is going down, not the fertilizer percentage.
![2020-06-20 21_35_04-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/85210222-55613680-b33e-11ea-8b88-173def49c037.jpg)

Showing the fertilizing of the field is 50%:

![2020-06-20 21_36_00-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/85210224-572afa00-b33e-11ea-894a-298eff711342.jpg)

**Comment by dennisblack777** [comment]
@Dennizzzzz you have to turn off that helpers buy automatically seeds and fertilizer in the normal game settings in my opinion.

**Comment by Dennizzzzz** [comment]
I feel soooooooo stupid right now... For the slurry it was indeed the setting :-(

There is still something wrong with the fertilizer and seeder mod (Horsch SW3500S and Pronto 6AS). Also without CP the seed percentage is not going down. So it is related to the mod i think, not to CP....
