### ISSUE TITLE
Probleme beim Maishäckseln

### ISSUE THREAD

**Issue by turbodani** [Courseplay/courseplay#5656]
Moin.

Ist es gewollt, dass mit der aktuellen Version der Abfahrer hinter dem Häcksler fährt im 1. Vorgewende? Leider lässt sich das nicht umstellen, denn damit gibt es riesige Probleme. Nur der BigX mit langem Entladerohr ist bei mir in der Lage, die Abfahrer zu bedienen. 

Dann ist mir noch aufgefallen, dass seit der aktuellen Version die Abfahrer sofort den Kurs befahren wollen, wenn man sie kurz aus der Kette genommen hat. 

Zb: (1. Vorgewende musste manuell eingefahren werden wegen o.g. Problemen).

Der Abfahrer fährt neben dem Häcksler, der Häcksler fährt 90° auf die nächste Bahn - dann kommt es zur imaginären Kollision. Der Abfahrer meckert er würde im Verkehr stecken.

Bei solchen Situationen konnte ich dann manuell den Abfahrer wieder in Position bringen (nah an den Häcksler) und auf "Abfahrer einstellen" klicken - dadurch lief alles wieder. 

Nunmehr sucht der Abfahrer dann aber direkt den Weg zum Abfahrkurs um diesen dann bis zur BGA abzufahren, auch wenn noch nicht annähernd gefüllt. Das ist leider schon sehr sehr nervig. 

Dann ist mir noch aufgefallen, daß der Abfahrer den Häcksler nur erkennt, wenn dieser auch durch CP gesteuert wird - heißt also, dass ich den Häcksler nicht manuell steuern kann damit ein CP Abfahrer mich bedient. 

Gibt es dafür Abhilfe? Diese (wohl möglich) kleinen Fehler zerstören komplett meine Spielweise in LS. Ich habe oft bis zu 8 CPler im Einsatz. Mit der aktuellen Version ist es eine einzige Katastrophe.

Lg

edit: habe auch noch festgestellt, das man die Abfahrseite auch nicht mehr auswählen kann. Bin auf Version 390 zurück. Das hat mein Savegame zerstört - juhu.

**Comment by Tensuko** [comment]
#5272 und https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ lesen...
Das Video schauen hilft auch.
Außerdem kann man mit Starten bei 'Unloading' direkt auf dem Feld starten.

Tja das mit deinem Savegame ist halt so, hat ja keiner gesagt du musst zurück auf V390.
Informieren und auch mal lesen was hier an Stickys ist und im Wiki steht hilft!

**Comment by turbodani** [comment]
Der Mode2 FAQ kommt ja nicht mal annähernd in die Gegend, von der ich spreche.

Das Video hilft genau gar nichts. Zeigt mir nur, dass diese komische Idee bei euch bedingt funktioniert - bei einigen anderen nicht. 

Starten bei "unloading" funktioniert nicht. Abfahrer bleibt stehen und macht nichts mehr.

Und der letzte Satz kann auch nur ein absoluter Witz sein?????

CP hat so mega funktioniert - nun bastelt man am code und baut unsinnigen kram ein. frustet einfach weil es vor den super heftigen änderungen super gut funktioniert hat. und der Support wird auch mäh.


Kann man denn bitte wieder einbauen, dass das 1. Vorgewende nicht so abläuft wie jetzt? Das ist nämlich ne absolute Katastrophe wenn man nicht (wie im euren video) den dicksten häcksler mit dem dicksten anhänger verwendet... oder ist das dann auch "pech gehabt!" ?!?!?!?! Kann nicht im sinne des entwicklers sein.
Warum kann ich die Abfahrseite nicht mehr auswählen?

achja: natürlich waren die distanzen auf "auto" aber auch diese werte zu ändern hat absolut gar keine resultate. Er ändert den abstand einfach nicht.


Und natürlich muss ich auf ältere versionen zurück, wenn die aktuellen nur müll generieren.... Super Kommentar dazu! Junge junge
