### ISSUE TITLE
?!?!?

### ISSUE THREAD

**Issue by turbodani** [Courseplay/courseplay#5657]
Moin.

Ist es gewollt, dass mit der aktuellen Version der Abfahrer hinter dem Häcksler fährt im 1. Vorgewende? Leider lässt sich das nicht umstellen, denn damit gibt es riesige Probleme. Nur der BigX mit langem Entladerohr ist bei mir in der Lage, die Abfahrer zu bedienen.

Dann ist mir noch aufgefallen, dass seit der aktuellen Version die Abfahrer sofort den Kurs befahren wollen, wenn man sie kurz aus der Kette genommen hat.

Zb: (1. Vorgewende musste manuell eingefahren werden wegen o.g. Problemen).

Der Abfahrer fährt neben dem Häcksler, der Häcksler fährt 90° auf die nächste Bahn - dann kommt es zur imaginären Kollision. Der Abfahrer meckert er würde im Verkehr stecken.

Bei solchen Situationen konnte ich dann manuell den Abfahrer wieder in Position bringen (nah an den Häcksler) und auf "Abfahrer einstellen" klicken - dadurch lief alles wieder.

Nunmehr sucht der Abfahrer dann aber direkt den Weg zum Abfahrkurs um diesen dann bis zur BGA abzufahren, auch wenn noch nicht annähernd gefüllt. Das ist leider schon sehr sehr nervig.

Dann ist mir noch aufgefallen, daß der Abfahrer den Häcksler nur erkennt, wenn dieser auch durch CP gesteuert wird - heißt also, dass ich den Häcksler nicht manuell steuern kann damit ein CP Abfahrer mich bedient.

Gibt es dafür Abhilfe? Diese (wohl möglich) kleinen Fehler zerstören komplett meine Spielweise in LS. Ich habe oft bis zu 8 CPler im Einsatz. Mit der aktuellen Version ist es eine einzige Katastrophe.

Lg

edit: habe auch noch festgestellt, das man die Abfahrseite auch nicht mehr auswählen kann. Bin auf Version 390 zurück. Das hat mein Savegame zerstört - juhu.

Jetzt ist man so so frech und löscht/reguliert meine Inhalte und blockt die Antworten???

**Comment by turbodani** [comment]
Habt ihr noch so viel Anstand und beantwortet den Kram, den Ihr gelöscht habt?

**Comment by Tensuko** [comment]
> Ist es gewollt, dass mit der aktuellen Version der Abfahrer hinter dem Häcksler fährt im 1. Vorgewende?

ja



> Nur der BigX mit langem Entladerohr ist bei mir in der Lage, die Abfahrer zu bedienen.

Das liegt nicht am Entladerohr, sondern an der im Fahrzeug hinterlegten Wurfweite.



> Nunmehr sucht der Abfahrer dann aber direkt den Weg zum Abfahrkurs um diesen dann bis zur BGA abzufahren, auch wenn noch nicht annähernd gefüllt. Das ist leider schon sehr sehr nervig.

Start Kurs -> Unloading



> Dann ist mir noch aufgefallen, daß der Abfahrer den Häcksler nur erkennt, wenn dieser auch durch CP gesteuert wird - heißt also, dass ich den Häcksler nicht manuell steuern kann damit ein CP Abfahrer mich bedient.
> 
> Gibt es dafür Abhilfe? Diese (wohl möglich) kleinen Fehler zerstören komplett meine Spielweise in LS. Ich habe oft bis zu 8 CPler im Einsatz. Mit der aktuellen Version ist es eine einzige Katastrophe.

Ist jetzt so. Wenn es eine Katastrophe ist, dann nutze CP halt nicht.



> edit: habe auch noch festgestellt, das man die Abfahrseite auch nicht mehr auswählen kann. Bin auf Version 390 zurück. Das hat mein Savegame zerstört - juhu.

> 2020-06-21 16:05     ******************************************* WARNING *******************************************
2020-06-21 16:05     * You are using a development version of Courseplay, which may and will contain errors, bugs, *
2020-06-21 16:05     * mistakes and unfinished code. Chances are your computer will explode when using it. Twice.  *
2020-06-21 16:05     * If you have no idea what "beta", "alpha", or "developer" means and entails, remove this     *
2020-06-21 16:05     * version of Courseplay immediately. The Courseplay team will not take any responsibility for *
2020-06-21 16:05     * crop destroyed, savegames deleted or baby pandas killed.                                    *
2020-06-21 16:05     ***********************************************************************************************



> Jetzt ist man so so frech und löscht/reguliert meine Inhalte und blockt die Antworten???

Wenn man nicht in der lage ist mal die Infoseiten richtig zu lesen und dann noch Freche Antworten raus zu hauen braucht man sich darüber nicht wundern.

**Comment by turbodani** [comment]
Alles klar, augenscheinlich ist der Main Dev weg von euch und nun herrscht arroganter Kindergarten. Lächerlich.

"Ist jetzt so. Wenn es eine Katastrophe ist, dann nutze CP halt nicht." Genau so wirds kommen. Und hoffentlich viele andere auch, damit Ihr eure Stunden schön für die Katz verballert. Unfassbar.

"Wenn man nicht in der lage ist mal die Infoseiten richtig zu lesen und dann noch Freche Antworten raus zu hauen braucht man sich darüber nicht wundern."

Wenn man in der Lage wäre ordentlich zu coden und keine schwachsinnigen "Ideen" einbauen würde, nach denen eh niemand gefragt hat, wäre alles gut. Und natürlich liest man bei CP Verschlechterungen nicht jeden scheiß nach - also vorher. Nun weiß man ja, dass die Devs nen scheiß geben und augenscheinlich nur noch Mist coden. Da sollte man tatsächlich VORHER schauen. Entschuldigung für das entgegen gebrachte Vertrauen! Passiert nicht wieder ;)

**Comment by Tensuko** [comment]
> Alles klar, augenscheinlich ist der Main Dev weg von euch und nun herrscht arroganter Kindergarten. Lächerlich.

Nö, der ist noch da.



> "Ist jetzt so. Wenn es eine Katastrophe ist, dann nutze CP halt nicht." Genau so wirds kommen. Und hoffentlich viele andere auch, damit Ihr eure Stunden schön für die Katz verballert. Unfassbar.

Naja ist ja nicht so, dass wir CP im Auftrag von irgend jemanden bauen, sondern für die Leute die es nutzen wollen. Bezahlt werden wir auch nicht, also völliger quatsch was du da von dir gibst. Es ist halt ein Hobby.



> Wenn man in der Lage wäre ordentlich zu coden und keine schwachsinnigen "Ideen" einbauen würde, nach denen eh niemand gefragt hat, wäre alles gut. Und natürlich liest man bei CP Verschlechterungen nicht jeden scheiß nach - also vorher. Nun weiß man ja, dass die Devs nen scheiß geben und augenscheinlich nur noch Mist coden

hättest du gelesen was in #5272 steht und dir die letzten Monate angesehen, wie schlecht der alte Mode2 lief, würdest du wissen was los ist, aber lesen ist ja nicht deine Stärke.
