### ISSUE TITLE
Game stuck in loading screen in multiplayer when courseplay is active

### ISSUE THREAD

**Issue by cosmin-margarit** [Courseplay/courseplay#5658]
Hello,

I've set-up a server to play with my friend and when he tries to connect to the server he's stuck in the loading screen. We disabled everything but courseplay, and only courseplay is causing this issue.
He tried to create a singleplayer game with courseplay and worked fine and he also tried to create a multiplayer game with courseplay, he could join and I could join his CP server with no problems.
But when he tries to join my multiplayer game he gets stuck in the loading screen.
The map is Green River.

I've attached his logs, do you guys know what could be the problem or what's happening?

Thanks :) 

[log.txt](https://github.com/Courseplay/courseplay/files/4810137/log.txt)

**Comment by Tensuko** [comment]
Yes we know this, #5620 and #5484 I can only suggest you to get I think it was Version 27 from Release Page. https://github.com/Courseplay/courseplay/releases
It may be fixed with one of the next versions but not sure.

**Comment by cosmin-margarit** [comment]
Thanks for the fast response.
We also tried again with a dress Green River multiplayer server with just the CP and the map mods installed, and everything worked just fine. 
Here is the happy case log file:

[log (1).txt](https://github.com/Courseplay/courseplay/files/4810214/log.1.txt)


So I think there may be some mod conflict, here is another clean log file for a case in wich it didn't work with other mods:
[log (2).txt](https://github.com/Courseplay/courseplay/files/4810218/log.2.txt)


Maybe something from here is useful, thanks!

**Comment by Tensuko** [comment]
Oh that might help!
Thanks for this.

**Comment by schwiti6190** [comment]
@cosmin-margarit  Thanks for your good Issue report.
I would suggest you stick to this Version of Cp v6.02.00027 as the error from appove will probably reappear, as it doesn't depend on other mods and is a problem I've caused in cp.
The next version might fix these problems.
