### ISSUE TITLE
Feature Request: Support AutoDrive in Leveling and compacting mode

### ISSUE THREAD

**Issue by Axel32019** [Courseplay/courseplay#5662]
Hello,

Could you please change the following function in LevelCompactAIDriver.lua to support the hold of AutoDrive vehicles to stop until the CP vehicle has reached parking position?
This will come with the next AutoDrive Release Candidate, but could be tested already in Beta branch.

function LevelCompactAIDriver:stopCourseplayer(courseplayer)
	if courseplayer.cp.driver ~= nil then
		courseplayer.cp.driver:hold()
	end
    if courseplayer ~= nil and courseplayer.spec_autodrive and courseplayer.spec_autodrive.HoldDriving then
        courseplayer.spec_autodrive:HoldDriving(courseplayer)
    end
end 

p.s. I don't know why the code formating is not working.

**Comment by Tensuko** [comment]
as you know how to use git, can you make a pullrequest ?

**Comment by Axel32019** [comment]
merged -> closed
