### ISSUE TITLE
FS19_Courseplay/LevelCompactAIDriver.lua:208: attempt to index a nil value

### ISSUE THREAD

**Issue by xerion8300** [Courseplay/courseplay#5663]
Hallo woher kommt dieser Fehler.
Es ist immer wenn ich den Helfer einstelle um das Silo zu verdichten.
Dann wird auch nur noch in der Mitte abgeladen und nicht mehr versetzt.
[log.txt](https://github.com/Courseplay/courseplay/files/4814114/log.txt)

**Comment by Tensuko** [comment]
Update mal FS und CP und versuch es noch mal.

**Comment by xerion8300** [comment]
Hab mal alles auf den neusten Stand gebracht.nun geht es .
Danke für diei schnelle Hilfe
