### ISSUE TITLE
problems with tractor and "shop"

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#5664]
I created two routes, one to spread the quicklime and one to reload the trailer. Both the tractor that I use and the trailer are mod (the trailer has never given me problems, the tractor is the first time I use it for this purpose). I tried to start the tractor but during the road the tractor (which, by pressing the text "x" can be deployed, opening the door) travels with the door open. Once he arrives at the camp he closes the door and unfolds the trailer. When the latter is unloaded, it is no longer folded up and ends up getting stuck under the "shop", this is also a mod which, however, I noticed was not considered by the tractor (while it worked a few days ago). Is there a way to make the Courseplay understand to Unfold and fold only the tools and not the tractor itself?

[log.txt](https://github.com/Courseplay/courseplay/files/4814886/log.txt)

**Comment by Tensuko** [comment]
What Mod Tractor ?

**Comment by 0Pietro20** [comment]
Fendt Favorit 800

**Comment by Tensuko** [comment]
Not the Brand... wich Mod Tractor ?

**Comment by 0Pietro20** [comment]
Wich Fendt 824
The door is open:
![Farming Simulator 19 22_06_2020 19_42_20](https://user-images.githubusercontent.com/59969508/85369074-b2bada80-b52c-11ea-951f-ea09e29f692d.png)
Start work and door closed:
![Farming Simulator 19 22_06_2020 19_43_27](https://user-images.githubusercontent.com/59969508/85369147-d54cf380-b52c-11ea-8720-dc832fd8ff73.png)
charging process started with door closed but trailer unfolded:
![Farming Simulator 19 22_06_2020 20_05_32](https://user-images.githubusercontent.com/59969508/85369215-f7df0c80-b52c-11ea-8f53-595e3d642395.png)
![Farming Simulator 19 22_06_2020 20_06_30](https://user-images.githubusercontent.com/59969508/85369263-13e2ae00-b52d-11ea-8dbc-6b38840b21e5.png)

**Comment by 0Pietro20** [comment]
The page of tractor
![Fendt Favorit 800 v1 0 FS19 - Farming Simulator 19 Mod _ FS19 mod - Google Chrome 23_06_2020 08_35_19](https://user-images.githubusercontent.com/59969508/85369471-7471eb00-b52d-11ea-9581-c46cbbb24f9a.png)

**Comment by Tensuko** [comment]
Sry, we don't support mods from this website.
Only from ModHub.
Ask the Author to fix his Mod, suggestion: add simpleIC and not any kind of hack to get  the doors open and closed.
