### ISSUE TITLE
Fehler Meldung nach Überführungskurs aktivierung

### ISSUE THREAD

**Issue by RobinHooooood** [Courseplay/courseplay#5666]
![fsScreen_2020_06_23_05_34_07](https://user-images.githubusercontent.com/59301819/85358184-631be500-b513-11ea-978c-92fb68b58b58.png)

Hab nen Kurz eingefahren der vom Feld zum Hof geht und wenn ich den an einen anderen Trecker lade und einstelle kommt die Fehlermeldung

**Comment by Tensuko** [comment]
Siehe deinen anderen Beitrag, CP aktualisieren: 
https://github.com/Courseplay/courseplay/releases
Da ist die gleiche Fehlermeldung im log, daher mache ich hier erst mal zu.
