### ISSUE TITLE
Bug  Drescher/ Füllstände

### ISSUE THREAD

**Issue by RobinHooooood** [Courseplay/courseplay#5667]
Hab grade gedroschen, der Drescher war dann voll und dann kommt von Coursplay ja immer eine Meldung Drescher voll. Nun hab ich die Rechte Maustaste gedrückt und dann erscheint ja der zeiger nun war ich schon neben den Drescher hab dann E gedrückt bin dann in den Drescher gegangen. Nun war der Mauszeiger noch da hab nochmal Maustaste gedrückt und dann ging er weg und dann ist das Courseplay Menü aufgegangen . Man konnte zwar noch das Menü Schließen aber nicht aussteigen und das Spiel ist "gefreezt" so das man nur noch Speichern kann aber man kann sich nicht mehr bewegen etc. Hier die Log. Hoffe das ihr den Bug Reproduzieren könnt und es vllt Fixen können. 
[log.txt](https://github.com/Courseplay/courseplay/files/4817128/log.txt)

**Comment by Tensuko** [comment]
wow... ich weis nicht wo du die alte Version her hast, aber ich würde mal ein Update machen:
Available mod: (Hash: f2b0f8ca3a98887dfaf683738f9bc5e0) (Version: 6.02.00001) FS19_Coursplay
https://github.com/Courseplay/courseplay/releases

Die Mod hier könnte auch zu solchen Problemen führen:
Available mod: (Hash: 0c3b57bbb7958e72353b106d19601f51) (Version: 0.0.3.8) FS19_AIVehicleExtension
