### ISSUE TITLE
ne allgemeine  Frage 

### ISSUE THREAD

**Issue by iceman234de** [Courseplay/courseplay#5668]
Hallo, 

Wollte mal fragen ob die Option kommt das der drescherfahrer mit Helfer und der abfahrer mit courseplay abtankt und abfährt , momentan muß man ja ein drescherkurs mit cp machen nur bei meiner 4 fach map stürzt mir das Spiel ab bei der kursgenerierung , denke weil meine Felder gigantisch groß sind .

Gruß Andy

**Comment by Tensuko** [comment]
Also ob es wieder so sein wird, dass Abfahrer mit nicht CP-Dreschern funktionieren kann ich im Augenblick nicht sagen.
Das dein Spiel abstürtzt kann ich kaum glauben, da ich auch auf der Kandelin mit 6m breiten Geräten die Felder bearbeitet habe.

Wie sieht es denn aus wenn dein Spiel abstürtzt ?
Fehlermeldung ? Crash to Desktop (CoD) ?
Ansonsten Geduld!

**Comment by TinyCrocodile** [comment]
Hallo so wie isch das verstanden habe  wird das nicht kommen. Aber das problem mit der kursgenerierung sollte lösbar sein, sofern kein fehler  in der Map vorliegt. 
Mein Vorschlag: Titel ändern damit er den fehler beschreibt. Dann gemäss https://github.com/Courseplay/courseplay/wiki einen sauberen bugreport machan. Screen mit den Einstellungen des coursegenerators und debug channel 7 bei der generierung aktiv haben könnte ebenfalls helfen.

**Comment by iceman234de** [comment]
Guten Morgen,  ich spiele auf der Great plains und meine 2 größten Felder gehen von links oben nach komplett links unten , sind mehrere Felder zusammen verbunden , genauso wie rechts oben nach rechts unten über die gesamte Karte , 

Das Spiel friert ein und kann höchstens noch speichern oder es geht gar nichts mehr und das mehrere Minuten lang , hatte schon mal so ca 20 min gewartet aber rat sich nichts mehr , nur noch Spiel abwürgen übern taskmanager

**Comment by iceman234de** [comment]
![great-plains--2-1](https://user-images.githubusercontent.com/26508897/85505447-a0a17080-b5ee-11ea-8d77-25217d83be4a.jpg)

**Comment by Tensuko** [comment]
debugchannel 7 an, kurs generieren, logfile anhängen und ein Bild von den Einstellungen anhängen.

**Comment by iceman234de** [comment]
Hallo, 

konnte nicht mal ein Feldrandkurs generieren, ist das spiel eingefroren und hat die log zu gemüllt 
![20200624_161325](https://user-images.githubusercontent.com/26508897/85574895-6e683100-b637-11ea-8804-f5a49631fecf.jpg)

https://www.dropbox.com/s/ad0bwsp9flbzl7x/20200624_161347.mp4?dl=0

Hatte debug channel 7 angehabt

[log.txt](https://github.com/Courseplay/courseplay/files/4826005/log.txt)

Log hat eine größe von ca 1,5 Mb
 
Gruß Andy

**Comment by Tensuko** [comment]
Allgemeine zu deiner log:
(Version: 1.0.0.0) FS19_addon_strawHarvest - updaten
(Version: 1.5.0.0) FS19_GlobalCompany - updaten
(Version: 0.51 Beta) AAA_HiredHelperTool - dieser Mod kann echte Probleme machen


Und der Error kommt nicht von CP:
2020-06-24 16:06 Error: addRequiredCropType foliage must match the size of the ground terrain detail.
Entweder mit deiner Map oder einer deiner Mods stimmt etwas nicht.
Könnte mit Strohbergungsupdate behoben sein, sicher bin ich mir nicht.
Auf alle Fälle hat es nichts mit CP zu tun und ich würde sonst mal in einem Modding Forum nachfragen.
