### ISSUE TITLE
Seeder Refill quit working

### ISSUE THREAD

**Issue by emegbert** [Courseplay/courseplay#5670]
Okay I just discovered that my seeder refill courses are no longer working.  They will drive to the silos, open the cover and keep driving without filling the spreader or seeder.  The funny thing is if I am in the cab camera view it will work.  The equipment I'm using is stock equipment from the game.  I'm guessing that maybe related to a mod recently installed.  Is there any way to tell which mod it might be without going through and uninstalling all of them?
[log.txt](https://github.com/Courseplay/courseplay/files/4827906/log.txt)

**Comment by Tensuko** [comment]
The good thing about your Issue is, that you attached a logfile.
The funny thing is, that I don't even need to look at it and tell you that you have the manuresystem in Version 1.0.0.0 wich cause the Issue.
The solution to this is, download the newest manuresystem Version on GitHub (google it) and your problem is solved :)

**Comment by emegbert** [comment]
Deleted the manuresystem but same issue.  No change.  My seeder will pull and and fill but sit there after that.  My spreader will just bypass it all after opening the cover.
[log.txt](https://github.com/Courseplay/courseplay/files/4830665/log.txt)

**Comment by emegbert** [comment]
Deleted almost all mods and tried but same issue.   I wonder if it has to do with the kvernelandPack which was installed recently.  Not sure how to uninstall it since it is a DLC.
[log.txt](https://github.com/Courseplay/courseplay/files/4830868/log.txt)

**Comment by Tensuko** [comment]
What exact tools ? Fronttank ?

**Comment by emegbert** [comment]
Amazon D8 30
Bredal K105
JCB Fastrac 4220
Favorit  511C

Been using a new game on Fellsbrunn for testing.

**Comment by Tensuko** [comment]
Will try it but my last test did had any Issues.
But it is all in SP right ?

**Comment by emegbert** [comment]
Yes SP.

**Comment by Tensuko** [comment]
No Problem at all, can you make a screenshot of your course and how you made the refill course ?
![fsScreen_2020_06_25_18_45_14](https://user-images.githubusercontent.com/27344744/85762542-1d7a3a80-b714-11ea-8ef5-c6404650e606.png)

**Comment by emegbert** [comment]
![Course](https://user-images.githubusercontent.com/64389260/85790818-7f2bac00-b6f6-11ea-94a6-56ef5aec2516.png)
[MapDE.zip](https://github.com/Courseplay/courseplay/files/4833630/MapDE.zip)

Course was made by choosing a starting point, driving past the silos and then to an end point.

I've attached my save game.  Maybe you can see something there.  You have to ignore the seed and fertilizer bags.  I keep emptying the tools trying to figure out what is up.
Appreciate your looking at this!

[savegame3.zip](https://github.com/Courseplay/courseplay/files/4833598/savegame3.zip)

**Comment by emegbert** [comment]
Okay figured out part of the issue with my test map.  They were going to the wrong side of the silo.  Even though I can fill manually from that side they won't fill automatically.  The one issue I do see now is the seeder drives up to the silo, opens the cover and fills with seed but then sits there without moving.  If the cover is opened manually before it goes to refill it seems to work fine.  This is so strange.

**Comment by emegbert** [comment]
I switched seeders and it works like expected.   Went back to other farm and it looks like everything is working now.  Thanks for assist.
