### ISSUE TITLE
Combimodus funktioniert nicht im MP

### ISSUE THREAD

**Issue by CxlledTxntx** [Courseplay/courseplay#5671]
Hallo habe letztens im multiplayer zwar einen drescher ausgewählt jedoch wir er in der abfahrersich des dreschers nicht angezeigt. Er tank den Drescher auch nicht ab

**Comment by dennisblack777** [comment]
@CxlledTxntx  Guck dir #5272 an > How to report a problem with Mode 2.

**Comment by CxlledTxntx** [comment]
was bringt mir das? 
@dennisblack777

**Comment by CxlledTxntx** [comment]
Ich habe ja das problem im MP 
@dennisblack777

**Comment by schwiti6190** [comment]
#5659 Hi kannst du dir bitte den post mal anschaun. Wenn die nächste Cp version released wird kannst du dich gerne nochmal melden bei fehlern, dann aber bitte mit log datei. :)

**Comment by Tensuko** [comment]
> 
> 
> was bringt mir das?

Wenn logfile gefordert wird, muss es angehangen werden.

> 
> 
> Ich habe ja das problem im MP

... und das unabhängig von SP oder MP.

**Comment by CxlledTxntx** [comment]
@schwiti6190 weil im dem artikler #5659 steht das die letzte version die geht die 27er ist... Die geht nähmlich auch nicht im combimodus (MP). Trdm danke ich probiere das nochmals mit der neusten Version aus.
Danke schonmal

**Comment by Tensuko** [comment]
@CxlledTxntx 
#5484

Grundsätzlich: noch geht nicht alles im MP!

**Comment by CxlledTxntx** [comment]
@Tensuko ok danke für eure aufmerksamkeit
