### ISSUE TITLE
Mode 2 Abfahrer fährt nach Wartepunkt nicht mehr an.

### ISSUE THREAD

**Issue by smelborp-erom** [Courseplay/courseplay#5675]
Seit einigen Versionen ignoriert der Abfahrer Wartepunkte auf dem Abfahrkurs, was den Workaround #3814 für den (noch) fehlenden Mode 3 unmöglich macht.
Melde mich in Kürze noch mit log und Screenshots sobald ich herausfinde bis zu welcher Version es noch ging.

Die blaue Meldung das der Fahrer den Wartepunkt erreicht hat blinkt kurz auf, verschwindet aber sofort wieder. Der Abfahrer fährt dann weiter bis das Abtankrohr des Überladewagens auf Höhe des Wartepunktes ist, fährt jedoch nach der eingestellten wartezeit von 60 Sekunden nicht mehr an. 

Standardmap und nur courseplay, money tool und easydevcontrols im modordner.
Debugchannel 4,7,14 und sonst noch einen?

**Comment by smelborp-erom** [comment]
Hat sich auch schon wieder erledigt, anscheinend funktioniert Mode2 mit einem einzelnen Abladepunkt statt Wartepunkt seit 6.02.00032 perfekt (bis auf das klappen des Abtankrohres) als Überlader.

**Comment by Tensuko** [comment]
Im Mode2 haben weder Wartepunkte noch Abladepunkte etwas zu suchen.
