### ISSUE TITLE
harrow does not start at first waypoint / harvester does 

### ISSUE THREAD

**Issue by Kamparan0** [Courseplay/courseplay#5676]
[log.txt](https://github.com/Courseplay/courseplay/files/4840895/log.txt)

Hi,
Following the issue mentioned in MP-section earlier I could trace same problem again.

I am playing MP on a dedi server but for my own.

At the same two courses were active
1) Harvester: start at 1st waypoint, 2 lines headland, circle lines -> harvester did follow the course.
2) Harrow: start at 1st waypoint, no headland, circle lines -> harrow started at the nearest waypoint (which was on last line) and stopped at the end of that line.

Earlier I had the problem, that I could not start an interrupted course at the current/nearest waypoint. The harrow always tried to start at first waypoint. Could not trace that currently. But as soon I am faced with that situation I would post the log file.

**Comment by Kamparan0** [comment]
Kursberechnung:
Habe den Striegel jetzt mal gezwungen am ersten Wegpunkt zu starten. 1 Vorgewende, kreisförmig

Die Berechnung vergisst, je nach Breite der Felder - reproduzierbar  auch bei anderen Feldern - immer eine breite Bahn in der Mitte (s. Screenshot Feld 20).

![fsScreen_2020_06_27_19_24_55](https://user-images.githubusercontent.com/66828101/85928294-46cdce80-b8ac-11ea-8d8e-7fc6c3b3e06d.png)

**Comment by Kamparan0** [comment]
Reproduziert bei Feld 31:

[log.txt](https://github.com/Courseplay/courseplay/files/4841053/log.txt)
![fsScreen_2020_06_27_20_19_52](https://user-images.githubusercontent.com/66828101/85929324-1722c480-b8b4-11ea-9ad9-7833a15b67e1.png)
![fsScreen_2020_06_27_20_21_33](https://user-images.githubusercontent.com/66828101/85929326-1a1db500-b8b4-11ea-951b-1fa670c78e3c.png)
![fsScreen_2020_06_27_20_12_15](https://user-images.githubusercontent.com/66828101/85929328-1b4ee200-b8b4-11ea-812b-dfd8b4cf303e.png)
![fsScreen_2020_06_27_20_12_37](https://user-images.githubusercontent.com/66828101/85929329-1c800f00-b8b4-11ea-86ff-bb24286d2a02.png)

**Comment by Kamparan0** [comment]
Nächstes Thema bei MP:

beim course wurde ein seitliches Offset von 2.4m vorgeschlagen. Habe ich auf 0 geändert (leider kein Screenshot). Der Kurs wurde dennoch mit offset gefahren.

[log.txt](https://github.com/Courseplay/courseplay/files/4841464/log.txt)

![fsScreen_2020_06_28_02_10_15](https://user-images.githubusercontent.com/66828101/85934608-5584a780-b8e5-11ea-9e19-8c781153f8d3.png)

**Comment by schwiti6190** [comment]
> 
> 
> Reproduziert bei Feld 31:
> 
> [log.txt](https://github.com/Courseplay/courseplay/files/4841053/log.txt)
> ![fsScreen_2020_06_27_20_19_52](https://user-images.githubusercontent.com/66828101/85929324-1722c480-b8b4-11ea-9ad9-7833a15b67e1.png)
> ![fsScreen_2020_06_27_20_21_33](https://user-images.githubusercontent.com/66828101/85929326-1a1db500-b8b4-11ea-951b-1fa670c78e3c.png)
> ![fsScreen_2020_06_27_20_12_15](https://user-images.githubusercontent.com/66828101/85929328-1b4ee200-b8b4-11ea-812b-dfd8b4cf303e.png)
> ![fsScreen_2020_06_27_20_12_37](https://user-images.githubusercontent.com/66828101/85929329-1c800f00-b8b4-11ea-86ff-bb24286d2a02.png)

Könntest du mal schaun ob die Arbeitsbreite,welche im Hud verstellbar ist und die Arbeitsbreite im Kurs Generier fenster auf Server und Client gleich sind ? Und passiert dieses nur in der mitte vom feld ?

**Comment by schwiti6190** [comment]
Die anderen beiden Fehler liegen warscheinlich an der alten struktur von Cp und müssten einmal überarbeitet werden.

**Comment by Kamparan0** [comment]
Hi,
ich bin mir jetzt ehrlich gesagt nicht so sicher, was Du mit Fenster auf Server und auf Client meinst? Ich habe es jetzt mal so interpretiert, dass das HUD der Client ist und das Fenster, wo der Kurs generiert wird auf dem Server liegt.

Da sind beide Arbeitsbreiten gleich.
