### ISSUE TITLE
Mp auf der Neuwerk

### ISSUE THREAD

**Issue by Bandesss** [Courseplay/courseplay#5678]
Hallo wir bekommen mit der neuesten Version wieder fehler im MP
[Game.log](https://github.com/Courseplay/courseplay/files/4841261/Game.log)

**Comment by Tensuko** [comment]
Mehr Details bitte, wann kommen die Fehler, was habt ihr gemacht und alle logs bitte für den MP.

**Comment by Bandesss** [comment]
Kommt schon beim laden der Map auf dem Server

**Comment by schwiti6190** [comment]
@Bandesss Hast du zufällig mit den einstellungen des Automatischen Abfahrers für Drescher/Häcksler rumgespielt ? Also z.B. einen Drescher zugewiesen.

**Comment by Bandesss** [comment]
nichts gemacht,dass abfahren macht ad
