### ISSUE TITLE
12000 acres field

### ISSUE THREAD

**Issue by levisbaja** [Courseplay/courseplay#5679]
hi, any chance to use courseplay when the field size is 12000 acres?

**Comment by Tensuko** [comment]
I can't even answer this question with so less information, like, did you even try it ?

**Comment by levisbaja** [comment]
yes I did. When I start the game and courseplay read the field datas, is freezing at the large field.

**Comment by wertigoxxx** [comment]
after loading the game, the fields are read by Courseplay!
by the way, large fields need more time, during that time the machine can't process enough data so it freezes! if you have time you will wait! :)

**Comment by Tensuko** [comment]
So can close this. Even if not, we wont support Field scanning that big. But if it works with some patience its fine :)
