### ISSUE TITLE
cannot be combined with AIVehicleExtension

### ISSUE THREAD

**Issue by simon198205** [Courseplay/courseplay#5680]
Courseplay (current vision) cannot be combined with AIVehicleExtension.
What can that be?

**Comment by Tensuko** [comment]
And what is not working ?

**Comment by simon198205** [comment]
Downhill courseplay working not

**Comment by Tensuko** [comment]
I guess you talk about unloading (Mode2) ?
Yes, only CP Combines gets unloaded right now and not sure if we will ever change that.
