### ISSUE TITLE
Kartoffelroder wechselt immer von Allradlenkung in Wendelenkung

### ISSUE THREAD

**Issue by RobinHooooood** [Courseplay/courseplay#5683]
Coursplay wechselt die Lenkung immer und dadurch am Vorgewende zum Beispiel fährt er bis ganz nach hinten aber fährt dann nicht mehr los (Räder drehen nicht durch)
[log.txt](https://github.com/Courseplay/courseplay/files/4844076/log.txt)

**Comment by RobinHooooood** [comment]
Würde dir gern das Video schicken aber Github will kleiner als 10Mb die Datei und das klappt nicht und ja hab es schon komprimiert. Also was soll ich machen wie soll ich dir das schicken?

**Comment by Tensuko** [comment]
Youtube ?

**Comment by RobinHooooood** [comment]
Kann ich dir das auf per Google Drive schicken?

**Comment by Tensuko** [comment]
Ja

**Comment by RobinHooooood** [comment]
https://drive.google.com/file/d/1qUrFp91QkXIZBsHf7LuK6Se1zhW8TNiz/view?usp=sharing 

Musst aber noch anfragen wegen der Berechtigung weiß nicht wie ich das ändern kann

**Comment by RobinHooooood** [comment]
https://drive.google.com/file/d/1qUrFp91QkXIZBsHf7LuK6Se1zhW8TNiz/view?usp=sharing Jetzt sollte der für jeden zu sehen sein.

Sry wegen der Musik wusste nicht das Shaddow Play das mit aufnimmt xD

**Comment by Tensuko** [comment]
Der Turn sieht gut aus auch die Lenkung und alles, das Problem wird der der Damm hinter dem Fahrzeug sein schätze ich.
Gleiche Situation bitte einmal mit debugchannel 12 und 14 und das logfile anhängen bitte :)

**Comment by RobinHooooood** [comment]
willst du nur noch die Log ? hab dir ja die datei mit  den debug 12 und 14  schon geschickt

**Comment by Tensuko** [comment]
Ja, wie gesagt, gleiche Situation so das er stehen bleibt, aber mit channel 12 und 14 an.

**Comment by Tensuko** [comment]
Closed due to inactivity.
