### ISSUE TITLE
Bug Claas DLC

### ISSUE THREAD

**Issue by John-Deere89** [Courseplay/courseplay#5684]
Hallo,
bei mir ist das Problem das dass Claas Dlc verbuggt ist besser gesagt der Drescher denn wie man sieht ist er immer bei Spielbeginn Ausgeklappt.
Ich versteh nicht warum es so sein solte aber habe es mehrfach getestet und aus irgend einen Grund mach CP dies 
Könnt ihr das vlt fixen oder sagen was das ist oder ob es bekannt ist? 

![Class DLC Bug](https://user-images.githubusercontent.com/63151473/85981711-f6a65780-b9e4-11ea-80b7-b76b30522cda.PNG)

[log.txt](https://github.com/Courseplay/courseplay/files/4844219/log.txt)

**Comment by John-Deere89** [comment]
Fehler is gefunden: https://ls-modcompany.com/forum/thread/7680-claas-dlc-bug/?postID=90641#post90644

vlt kann man da noch was dran machen oder ändern. Da kommt man ja nicht drauf :D

**Comment by Tensuko** [comment]
Ja eben gelesen.

@pvaiko Testbeschleunigung (Instant unfold) noch drin ?

**Comment by John-Deere89** [comment]
diese Einstelung giebt es nicht

**Comment by Tensuko** [comment]
> 
> 
> diese Einstelung giebt es nicht

Habe ich auch nicht gesagt und war auch nicht an dich gerichtet...

**Comment by pvaiko** [comment]
@Tensuko das ist keine Testbescheuninung, das ist zum messen des Rohroffsets in aufgeklappten Zustand (empfohlen von Giants, BTW), sollte alles wieder zumachen.

**Comment by Tensuko** [comment]
Ehm naja wie kommt es dann das die Geräte aufgeklappt sind wenn Mode6 an ist und man das savegame lädt ?
Btw ich hab auch schon mal krampfhaft versucht nen Drescher auf zu klappen bzw zu und wieder auf zu klappen weil dieser Teils aufgeklappt war... lässt sich da etwas machen ?

**Comment by John-Deere89** [comment]
> Habe ich auch nicht gesagt und war auch nicht an dich gerichtet...

Oh sry :D

**Comment by cengotr** [comment]
Hi
After installing version 0037, the game is loaded on the map, and after starting the game, the game freezes. While researching in another mode, I found that the problem was caused by the course play file. Can you provide support for this situation? Thank you.

**Comment by Tensuko** [comment]
Can you previde a logfile then with the error ?

**Comment by cengotr** [comment]
@Tensuko You need to direct which file you want, my friend.

**Comment by cengotr** [comment]
1. https://hizliresim.com/7318Kz

2. https://hizliresim.com/X6VyVD

3. https://hizliresim.com/Rl62pJ

4. https://hizliresim.com/0fEdrF

then it does not move, the game freezes.

https://drive.google.com/file/d/139krmEpE7pHAPNTawg1kHf1bLcxkcNl6/view?usp=sharing

log file at this address.

**Comment by Tensuko** [comment]
I only see to many Mods with Errors and Mods that cause some Errors later on loading.
Nothing CP related.

**Comment by cengotr** [comment]
@Tensuko Thank you very much for your interest and interest. I have mods, but CP was working up to 2 days ago. started installing errors after installing the latest update. I think I will have to find out which mod is causing problems by looking at the mods that have not been. Thank you again for your interest and interest. Greetings.

**Comment by D21041995** [comment]
I would like to know when the version will come out so that I can use the sugar cane implements, overflow with the harvester

**Comment by D21041995** [comment]
I would like to know when a version will be released so that I can use the sugarcane implements transhipment and harvester
