### ISSUE TITLE
Kverneland/Vicon FastBale stoppt beim Ballenauswurf zum Wickler

### ISSUE THREAD

**Issue by BauerNepo** [Courseplay/courseplay#5685]
Hallo,
besten Dank erst mal für eure tolle Arbeit.
Ich verwende die FastBale Rundballenpresse/Wickelkombi aus dem Kverneland DLC. Der Vorteil dieser Presse ist die Verwendung zweier Presskammern, somit muss diese Presse nicht mehr anhalten um den Ballen an den Wickler zu übergeben. Leider funktioniert das mit CP noch nicht, wenn die Hauptkammer 100% Füllstand erreicht stoppt CP das Gespann bis die Hauptkammer entladen ist. Somit geht der Vorteil des schnelleren Arbeitens leider verloren bzw. aufgrund der schon geringeren Arbeitsgeschwindigkeit dieser Presse dauert das Pressen mit CP unnötig lange.
Es wäre Toll, wenn Ihr das so hinbekommen könntet dass CP nur noch stoppen würde wenn Vor- und Hauptkammer 100% erreicht haben sollten (Falls die Ballenübergabe noch nicht beendet wäre wenn die Vorkammer bereits wieder 100% erreicht hat, bei grosser Schwade).

**Comment by Tensuko** [comment]
Ja das ist mir auch schon aufgefallen, kommt mit auf die Liste!

**Comment by BauerNepo** [comment]
Nein, das hat nichts zu tun mit der Vorpresskammer (denke ich), CP stoppt ja wenn die Hauptkammer 100% erreicht hat. Nur würde halt jetzt wieder die Vorkammer gefüllt werden, wenn das Gespann weiterfahren würde. Ich denke einfach, dass bei einer grossen Schwad vielleicht die Vorpresskammer 100% erreichen könnte bevor die Übergabe des Ballens auf den Wickeltisch beendet ist und in dem Moment müsste CP dann halt doch stoppen.
Getestet habe ich das jedoch nicht, ich mache keine grosse Schwaden.

**Comment by Tensuko** [comment]
Wie ich es im Titel bereits geschrieben habe.
CP bleibt stehen wenn der Ballen ausgegeben wird zum wickeln.
Getestet, auf Video festgehalten, wir schauen uns das an.
Das hat nichts mit Schwaden oder Vorpresskammer zu tun, CP behandelt die Presse eben wie jede andere Wickelkombination, welche anhalten müssen wenn der Ballen fertig zum wickeln ist.

**Comment by BauerNepo** [comment]
Danke fürs anschauen.
Was den Rest betrifft, ich glaube wir schreiben aneinander vorbei...:-)
Das mit der Schwad habe ich nicht geschrieben für die momentane Handhabung durch CP. Das ist mir schon klar, dass CP diese Presse wie jede andere handhabt. Ich wollte nur für eine allfällige Änderung darauf hinweisen, dass es vielleicht doch nötig sein kann dass der "Aufsammelvorgang" gestoppt werden müsste, falls die Vorpresskammer erneut 100% Füllstand hätte bevor der aktuelle Ballen fertig entladen wäre.... aber egal, ich bin zuversichtlich dass Ihr dazu eine Lösung findet :-)
Ich habe ja auch keine Ahnung von Scripten und Modding, ich bin "nur" Spieler, der froh ist gibt es solche Leute wie Euch, die das Spiel für uns verbessern.

**Comment by Tensuko** [comment]
Ah ok dann habe ich dich etwas falsch verstanden.
Ja wir machen uns dran und mal gucken :)
