### ISSUE TITLE
ungewolte Arbeitsgeschwindigkeit absenkung

### ISSUE THREAD

**Issue by John-Deere89** [Courseplay/courseplay#5686]
Ich habe ne weile kein LS gepsielt mein letzter Stand con CP war v6.01.00399 oder so
Dann habe ich es gestern aktualisiert und nun is es so das nach einer gewissen zeit die Geschwinkeiten von denn geräten fallen und nicht schneller mehr arbeiten können egal ob mit KI oder Manuell. Warum?  Ich kann denn fehler behebn mit neu kauf des Geräts bis is irgendwann wieder auf Tritt 
Voher kamm das nie und wüste auch nicht was das anders verursachen sollte da ich paar tage vor dem neu herunter laden keine Probleme hatte. 
Ist es Bekannt ?
Ist das vlt von CP so gewohlt? (Abnutzung,Verschleiß)
Diese fuhr mal 18 Km/h nun nur noch 13Km/h 
![jfgtzx](https://user-images.githubusercontent.com/63151473/86009490-929e8600-ba1a-11ea-8e72-81fbffb68e46.PNG)

[log.txt](https://github.com/Courseplay/courseplay/files/4845671/log.txt)

Edit: Wird auch wieder zurück gesetzt wenn FZG Repariert wird (Fährt wieder 18Km/h)

**Comment by Tensuko** [comment]
Sowohl Saatmaschine als uach Traktor sind runter auf 96 bzw 71% das ist klar das die Geschwindigkeit runter geht, aber das ist eine GIANTS geschichte.
Wenn die nun langsam läuft obwohl beide Maschinen heil sind (gegen 0%) und der Tempomat nicht durch irgendwelche einflüsse runter gesetzt wurde, dann müsste man schauen, aber so sehe ich keine Probleme seitens CP.

**Comment by John-Deere89** [comment]
wie ? das wäre mir neu das die druch verschleiß lamgsamer werden oder wurde das gepatcht? Es ist 2 Monate her das ich ls gespielt habe kann sein das ich ja was verpasst habe. Solten die wirklich langsamer werden durch abnutzung O.o

**Comment by Tensuko** [comment]
Kein Witz:
Das ist ein Feature vom LS19 und war von Anfang an da...

**Comment by John-Deere89** [comment]
Das die Langsamer werden?
Das sie Repariert werden kann ich ja und das teile verschlissen aus sehn kenn ich ja aber nicht das ein gruber oder drille langsamer werden O.o

**Comment by John-Deere89** [comment]
tatsache : https://forum.giants-software.com/viewtopic.php?f=955&t=140597&#p1097926

**Comment by Tensuko** [comment]
Wie ich es sagte... nichts neues ;)

**Comment by John-Deere89** [comment]
is mir echt noch nicht aufgefallen  wieder was gelernt :D

**Comment by Tensuko** [comment]
> 
> 
> is mir echt noch nicht aufgefallen wieder was gelernt :D

Man lernt nie aus :)
