### ISSUE TITLE
Emptying Combine Stops before End of Lane

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#5687]
Map: Lone Oak
Equipment: ModHub's Fendt 9490x
Problem: Combine is emptying on the move into the tipper, but stops several meters before the end of the lane. Once emptied the combine moves to the next lane leaving fruit behind.
![20200629171741_1](https://user-images.githubusercontent.com/24764870/86057428-28431100-ba2d-11ea-8294-c4bce52569b3.jpg)
![20200629171813_1](https://user-images.githubusercontent.com/24764870/86057438-2c6f2e80-ba2d-11ea-9033-2b4ca9d7e0b9.jpg)
![20200629171816_1](https://user-images.githubusercontent.com/24764870/86057444-2e38f200-ba2d-11ea-8603-96d943c56988.jpg)
![20200629171833_1](https://user-images.githubusercontent.com/24764870/86057452-3133e280-ba2d-11ea-8745-a2b7483f3088.jpg)
![20200629171841_1](https://user-images.githubusercontent.com/24764870/86057460-33963c80-ba2d-11ea-801b-07c03f4c9c65.jpg)
![20200629171845_1](https://user-images.githubusercontent.com/24764870/86057471-37c25a00-ba2d-11ea-8ede-b1500948f738.jpg)
![20200629171902_1](https://user-images.githubusercontent.com/24764870/86057473-398c1d80-ba2d-11ea-8eea-308c2c52e33d.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/4848103/log.txt)

**Comment by pvaiko** [comment]
@lcc1211 turn of the fuel save option on the combine and it should be fine.

**Comment by lcc1211** [comment]
Did you mean that comment for this issue? It seems odd that the fuel save option would cause the combine to not get the last of the fruit at the end of a lane.

**Comment by pvaiko** [comment]
Odd or not, that's what is causing this, during the unload the combine stops the motor which raises the header. It is an edge case and not sure I want to spend time on fixing this if turning off the fuel save solves it.

**Comment by lcc1211** [comment]
I turned off fuel save and now the full tractor just sits there and the combine doesn't move on. I think you should not have the combine stopping short of the end of the lane as it is emptying. Perhaps have it go to the very end and stop like it used to do. Then the have the tractor sit still until or move out of the way (if necessary) while the combine moves to its next lane.

**Comment by pvaiko** [comment]
Log?

**Comment by lcc1211** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4918784/log.txt)

**Comment by pvaiko** [comment]
Ok, I think I know what this is, if, as you say the tractor was full, unfortunately unlike your previous log, you don't have any debug flags enabled, as we always ask for 4, 7 and 14, my bad I did not ask again...

Have you been waiting at least 30 seconds after the tractor was full? We have a clean up mechanism there kicking in after 30 seconds and that should have resolved this deadlock situation.

**Comment by lcc1211** [comment]
When I made the previous comment about it sitting at the end of the lane, several minutes had passed.

**Comment by Tensuko** [comment]
Still a problem ? if so log with channel 4, 7 and 14 pls.

**Comment by lcc1211** [comment]
Looks like I'm all clear now.
