### ISSUE TITLE
Combie wont fill to 100% and kart tractor wont empty it

### ISSUE THREAD

**Issue by ads0608** [Courseplay/courseplay#5688]
Hi there using the latest version of courseplay and i simply cannot get the tractor to kart for me at all it just sits there and dosent move and the combine wont fill to 100% but always 96% or there abouts even if i manually fill the combine to 100% the tractor will not unload the combie at all thanks 
[log.txt](https://github.com/Courseplay/courseplay/files/4848267/log.txt)
![fsScreen_2020_06_29_22_58_11](https://user-images.githubusercontent.com/67560036/86060718-3f99f280-ba5d-11ea-8386-79f4aa97fb3d.png)
![fsScreen_2020_06_29_22_58_24](https://user-images.githubusercontent.com/67560036/86060728-432d7980-ba5d-11ea-970d-b021672cecdf.png)
![fsScreen_2020_06_29_22_58_58](https://user-images.githubusercontent.com/67560036/86060735-46286a00-ba5d-11ea-9635-1ac4f86aed76.png)

**Comment by Tensuko** [comment]
Try to turn off Fruit Bypass in the HUD.
He stucks at waiting for pathfinder.
Also do not manualy drive the Combine to fill it up or anything there is no reason to do it.

**Comment by ads0608** [comment]
Same result tractor just sits and wont move i also tried a diffrent tractor this time not sure if its a claas DLC issue or not as i dont have any other tractors on this map at the moment 

![fsScreen_2020_06_30_07_39_35](https://user-images.githubusercontent.com/67560036/86092499-7d226e00-baa5-11ea-8da6-14aebec2ad2f.png)
![fsScreen_2020_06_30_07_39_43](https://user-images.githubusercontent.com/67560036/86092505-7f84c800-baa5-11ea-9fa6-b512fdf37946.png)

![fsScreen_2020_06_30_07_39_57](https://user-images.githubusercontent.com/67560036/86092513-83b0e580-baa5-11ea-832b-62f99c75c91c.png)

also i only manually drove combine to 100% to see if it made a difference and called the tractor
regards

**Comment by Tensuko** [comment]
Now you turned it off for Combine, do not do that.
Only turn off for unloader. You got a lot of fruit in the path.
He stucks again at waiting for pathfinder.

**Comment by ads0608** [comment]
I only deactivated the avoid fruit setting on the tractor not the combine, here how I set it up so you can tell me if I’m doing something wrong ☺️

Created field path on combine, then recorded tractor unload path, assigned to combine by checking the box, set to start at unload allowed combine to fill tractor never moves to unload 

Thanks

**Comment by Tensuko** [comment]
I should have checked your logfile as well.... you should update CP:
Available mod: (Hash: fcb806188f02e26f47578dbab7e84eea) (Version: 6.02.00022) FS19_Courseplay
https://github.com/Courseplay/courseplay/releases/tag/6.02.00032

On your first pic on 2nd post, the Combine stays there with pipe in the fruit, wich it should not do when Avoid Fruit is activated on combine.

**Comment by ads0608** [comment]
I thought I had the latest one installed 🙈🙈 I’ll update and let you know if it fixes the issue 👍🏻

**Comment by androno12** [comment]
and the tractor is still not unloading the harvester. This problem is a year old
[log.txt](https://github.com/Courseplay/courseplay/files/4858665/log.txt)

**Comment by Tensuko** [comment]
The problem is not a year old. The mode is working and you dont give any info beside this... Wow...

**Comment by androno12** [comment]
I wrote about this problem - I was ignored. This mod is free, so I don't worry about it. I just want to say that this mod doesn't work for me after April of last year. (Combine and tractor) I attached the log. I hope this helps

**Comment by Tensuko** [comment]
But you know that a few month ago we made the mode2 all new ?
And not last year april: #5272

**Comment by androno12** [comment]
I'm sorry, I don't want to offend anyone. I played Farm Simulator 2017 and everything was great there. After April last year, I have to unload combines manually, because this mod does not work for me. I'm using the latest version of the mod and it still doesn't work. Trucks and tractors do not want to go to the combine for unloading. I apologize again, maybe the problem is on my side

**Comment by Tensuko** [comment]
I can just suggest you do watch the video in #5272 to see how it works not.
Sure not all situations are fine yet, but we had to make a full rework and we are on a good state.
FS17 was complete different from FS19 ppl can be happy CP made it to FS19.

**Comment by harrysck1** [comment]
try this make sure your combine on the top left icon in courseplay is requesting a driver also if you run headlands or racktrack or spiral or a combination of these make your combines stop during unload ive run into this type of issue where it gets stuck behind the combine because its waiting for it to move it could be related

**Comment by ads0608** [comment]
Tried it just now with the latest version and it seams to be working there was some jankyness there the tractor lost the path and went across the combine but otherwise it seams fine, tho I really do hope you add carting for a human player back in I’ll leave this open for now as I was on a different map with different Vehicles before but so far all sorted 👍🏻

**Comment by ads0608** [comment]
Tried several times now and all working with the version I’m on 👍🏻
