### ISSUE TITLE
Courseplay-driver stops when I enter the vehicle

### ISSUE THREAD

**Issue by Tisdan** [Courseplay/courseplay#5691]
I made a course for filling the shovel of my telescopic handler. When I stand next to the vehicle, it drives the course just fine but as soon as I enter the vehicle, it stops

**Comment by TinyCrocodile** [comment]
Hi what Telehandler do you use? Giants or mod? What tool? 
Can you please post a logfile and screenshot of the situation with visible course (3 dots).

**Comment by Tisdan** [comment]
Log-File:
https://pastebin.com/0KZ2LyRL

Image: 
https://imgur.com/a/bcKG3eU

**Comment by Tensuko** [comment]
>  with visible course (3 dots).

you didn't turn on all waypoints.

**Comment by Crinouche** [comment]
Hello,

I have had the same problem for a long time and for many previous versions.
I have noticed this problem every time it rains and it seems to be your case.
The problem disappears when it no longer rains.

**Comment by Tisdan** [comment]
> Hello,
> 
> I have had the same problem for a long time and for many previous versions.
> I have noticed this problem every time it rains and it seems to be your case.
> The problem disappears when it no longer rains.

Thanks. I will try it :)

**Comment by Tisdan** [comment]
After the rain stopped, everything worked perfectly again. Thanks!

**Comment by TinyCrocodile** [comment]
Interesting. This should not be the case for shovelmode right? @Tensuko ?

**Comment by Tensuko** [comment]
Normaly not... Rly Interesting...

**Comment by dennisblack777** [comment]
same problem for me with the claas wheel loader, when it rains and enter the vehicle

[log.txt](https://github.com/Courseplay/courseplay/files/4878458/log.txt)

**Comment by Tensuko** [comment]
Tested on a Testversion, it is fixed or will be fixed with the upcomeing .00015
