### ISSUE TITLE
Attaching pallets - Error: Running LUA method 'update'. toolManager.lua:444: attempt to call method 'getAttachedImplements' (a nil value)

### ISSUE THREAD

**Issue by CurtisFeatures** [Courseplay/courseplay#5693]
When using the CSZ pack we have the option to attach pallets to our forks. 
If you press Q to attach the game freezes and the server must be reset

This is when the error starts occurring and it just repeats over and over again. 

2020-06-28 23:08 Error: Running LUA method 'update'.
2020-06-28 23:08 C:/Users/Administrator/Documents/My Games/FarmingSimulator2019/mods/FS19_courseplay/toolManager.lua:444: attempt to call method 'getAttachedImplements' (a nil value)

I have tried updating to the latest version of CP but i still get the same issue

Full log attached. 

[log.txt.zip](https://github.com/Courseplay/courseplay/files/4857337/log.txt.zip)

**Comment by pvaiko** [comment]
@CurtisFeatures can you post here a savegame on a standard map with everything set up so I just have to press Q to reproduce?

**Comment by CurtisFeatures** [comment]
Yes. I will get this done tonight

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Tensuko** [comment]
Still happening with .00053 ?

**Comment by Tensuko** [comment]
Closed due to inactivity. If got savegame where we can reproduce this Error, we reopen this one.
