### ISSUE TITLE
[Question] Use AD for Park

### ISSUE THREAD

**Issue by cosmin-margarit** [Courseplay/courseplay#5694]
I remember that CP used to have an option to use AD for unload/refill and parking the vehicle. And in version 29 if I'm not mistaken you could choose from a combination of those 3 options. But now it's not available anymore, was it removed or is it in another place that I don't see. 
And if it was removed it was because it was causing issues or is it in rework and will come back later?

**Comment by polosubtil** [comment]
I think you can find them in the advanced settings now

**Comment by cosmin-margarit** [comment]
@polosubtil It used to be there under AutoDrive option but no more

**Comment by Tensuko** [comment]
It is in adv settings 1st page.

**Comment by cosmin-margarit** [comment]
> It is in adv settings 1st page.

I seem to completely leave out the point of the question... I wanted to ask about the park option of the 
AutoDrive menu, now the options are "Don't use" and "For unload/refill". Before there was another option for parking the vehicle . Is that option to use AD for park going to return in the feature

**Comment by Tensuko** [comment]
Oh well I think when the vehicle got an park position for AD and it ends it work it should do it. I have not removed anything and just moved it into adv settings for AD.... Will have a look...

**Comment by cosmin-margarit** [comment]
> Oh well I think when the vehicle got an park position for AD and it ends it work it should do it. I have not removed anything and just moved it into adv settings for AD.... Will have a look...

Don't need to look into this, after I've set the park target for the tractor the option came back. Sorry for this, it's a new map and just updated to the last version of CP and when I saw the option missing I thought something changed, but everything is fine just need to set the Park destination in AD. Sorry for this and thank you! :)
