### ISSUE TITLE
Cotton Harvester doesn't wait enough to unload bale

### ISSUE THREAD

**Issue by cosmin-margarit** [Courseplay/courseplay#5695]
Map:  Green River
Version: 6.02.00034

Since latest version cotton harvester doesn's wait enough to unload bale, and starts the course in the middle of unloading missing some crop. Before updating to the latest version I was using version 32 and I didn't have this issue.

The logs are clean, nothing logged.

Link of a video to the issue:
https://drive.google.com/file/d/1VlLmGZ8jtdeoQfrQr9C0miDtm6gwOMfR/view?usp=sharing

Thanks! :)

**Comment by ddewar** [comment]
This might have been the update I made for the Vicon Fast Baler. @Tensuko, I will take a look at this ASAP.

**Comment by Tensuko** [comment]
Yea that might be the case.
I also haven't try out the normal Kuhn Combi Baler.

**Comment by ddewar** [comment]
I've tested with Square, round, cotton, combi, and fastbale
