### ISSUE TITLE
1.6 multiplayer Sync issue

### ISSUE THREAD

**Issue by Wiseantelope** [Courseplay/courseplay#5697]
when hosting a multiplayer server, a player joining starts syncing with everyone else but then when the host has finished, the persons trying to join continues forever. when there server comes down the play finishes syncing and is stuck in the ground with their game being crashed.

Map: Sandy bay 19 - 1.1
Version: 6.02.00034

**Comment by Wiseantelope** [comment]
> when hosting a multiplayer server, a player joining starts syncing with everyone else but then when the host has finished, the persons trying to join continues forever. when there server comes down the play finishes syncing and is stuck in the ground with their game being crashed.

**Comment by Tensuko** [comment]
And where is the logfile ?

**Comment by Wiseantelope** [comment]
where do i find that?

**Comment by Wiseantelope** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4862648/log.txt)
found the log

**Comment by Tensuko** [comment]
I saw more then one Map in Mods folder and an Error wich I am not sure what that is:
2020-07-01 19:04 Error: Startup with port while already running

Also two other Errors:
2020-07-01 19:09 Error: Failed to open xml file 'C:/Users/Tovey/Documents/My Games/FarmingSimulator2019/mods/FS19_PalletProductStorage/xml/digestatePalett.xml'.
2020-07-01 19:10 Error: Failed to open xml file 'C:/Users/Tovey/Documents/My Games/FarmingSimulator2019/mods/FS19_PalletProductStorage/xml/digestatePalett.xml'.

Both are not related to CP.

@schwiti6190 do you see anything whe it could not sync ?

**Comment by Wiseantelope** [comment]
No I Could Not we Tried it with just Course Play but we still had the syncing problem. this is ever since i have updated to 1.6 and I have finally confirmed after 3 reinstalls that it works with no mods.

**Comment by schwiti6190** [comment]
@Wiseantelope Did you post the client or Server log, seems to me like the server one but I am not sure? 
Would be helpful to get the other one also.

**Comment by Wiseantelope** [comment]
i took the one out of the my games/farming simulator 19 folder

**Comment by Wiseantelope** [comment]
where would i find it

**Comment by Wiseantelope** [comment]
exact location - is where you say in your sexy report tutorial on your wiki win7 although I am on win10

**Comment by Wiseantelope** [comment]
@schwiti6190 hope this helps

**Comment by schwiti6190** [comment]
@Wiseantelope Do you guys use a dedicated server or does one of you hostes the server localy on there PC ?

**Comment by Wiseantelope** [comment]
Hosts Locally (on mine where the log is from) But in Future we are lucking to put it on a home run dedi

**Comment by Wiseantelope** [comment]
How long do you think it will take to fix as i would just like an eta @schwiti6190

**Comment by schwiti6190** [comment]
Then it would be helpfull if you could post the log file of your friend(Client) on here, as he is the one with the errors.

**Comment by Wiseantelope** [comment]
ok will get him too

**Comment by schwiti6190** [comment]
might take some time, as I am currectly working on a bigger not related problem at the moment

**Comment by Wiseantelope** [comment]
@schwiti6190  ok thankyou i will get it at 6 as he is out all day but will be sure to send it :)

**Comment by Wiseantelope** [comment]
@schwiti6190 by some time do you mean weeks months or years. just to manage my expectations

**Comment by schwiti6190** [comment]
@Wiseantelope depends on the problem, might take a few weeks

**Comment by Wiseantelope** [comment]
@schwiti6190 ok thanks. i would highly apreciate if you could get it done quick but if you cant i dont mind 

thanks in advance

**Comment by gec100** [comment]
@Wiseantelope Hi m8! You do understand that devs are doing this for free, and in their own free time?

**Comment by Wiseantelope** [comment]
no ididnt but thaks for telling me now i understand

**Comment by Tensuko** [comment]
We dont give out any date.
It is done when it is done!

**Comment by jspring0811** [comment]
Not sure if this is related...  I had a problem with Dedi server join hanging at Synchronizing 29% (just before it would normally show the start button).  00027 was working, then had this issue with 00032, then installed 00034 and join was working again.  Possibly an issue somewhere between 00028 and 00031.  Working fine on our server now.

**Comment by schwiti6190** [comment]
I am not sure if this one is still relevant? If it is the it would be nice to have the client/server logs and some infos on what CP driver, where active at the moment.

**Comment by Wiseantelope** [comment]
ok will try it again soon on the latest update
