### ISSUE TITLE
tractor does not unload chaff

### ISSUE THREAD

**Issue by androno12** [Courseplay/courseplay#5698]
Am I doing something wrong?
https://www.youtube.com/watch?v=3CQqcBSEgjg

[log.txt](https://github.com/Courseplay/courseplay/files/4864953/log.txt)

**Comment by Tensuko** [comment]
Do you own the BGA ?
You can only dump chaff when you own the land (thats a general thing).

**Comment by androno12** [comment]
ups..  sorry , I completely forgot about it. Everything works well
