### ISSUE TITLE
[Help / Issues] islands on self created farms (trees)

### ISSUE THREAD

**Issue by ELF0001** [Courseplay/courseplay#5699]
so im playing on ( no man's land ) and there i have to create all farms manualy with a plow

when im using courseplay im driving around the farm i made and then using that to generate the couses becouse im unable to select them

i also have a lot of islands ( trees ) that im in need to go around but im unable to make it find them
i really want to keep the trees for the enviroment ;P general look and feel
i were wondering if it would be a idea to make it so that you can make a course around ( said island ) 
and then when generating the course you can tag that course as a island and it woud try to generate the course 
without entering into that area ?

**Comment by Tensuko** [comment]
So you want to use CP to create the Field and still keep those Islands ?
I have not rly tested it on none Field Areas, but what you could try is, plow the border of the Field by yourself, plow arround the Islands, then move on your plowed border and click on I think its called generate Fieldborder. It should then generate a blue line arround the border. Then you can give it a Number and add it as a Custom Field. What I don't know is, if it will notice the right Islands.

If you made the Field by yourself already, it should work just fine like a normal Field, as I always create my custom Fields by merging more Fields.

**Comment by ELF0001** [comment]
thx for the information on the generate field it works fine
it seems to work  as long as you make a big island around the trees
tho im still having problems makeing it detect the ones were the island is around the trees own size

i can work with how it detects now
but i woud still like a way to mark out islands manualy incase were it dosent detect them

**Comment by Tensuko** [comment]
If the islands are to smal it won't detect it, yes.
But what you can do is use the ingame paint tool and draw a bit grass arround it (I do it the same way) it will increase the island sice and works very good.

**Comment by ELF0001** [comment]
thx this will solve the rest of my problem 😄
