### ISSUE TITLE
v6.02.00034 geht nicht mehr  [BUG]

### ISSUE THREAD

**Issue by John-Deere89** [Courseplay/courseplay#5700]
Ich habe mir gestern eure neue Version herunter geladen nun habe ich nur noch Porbleme damit. Die Abfahrer Komm nicht mehr Richgtig zum Drescher und dann legt es nur noch andauernd wenn er Route Berechnet.
bitte behebt das wieder.

Nachtrag: CP hat das gesamnte Save zerschoßen da nun garnichts mehr geht bei denn abfahrern.
Auch Ältere Versionen gehn nicht mehr
NEIN es kam kein mod dazu
NEIN Ich habe nichts verändern nur CP aktualisiert

Weiß nicht was Ihr gemacht habt aber mir hat das ganze CP unbrauch bar gemacht ich kann älter versionen nehmen keine geht mehr   immer komm das gleiche das man Drescher mit einem X auswählen muss und er Fährt ihn einfach nicht mehr ab.
[log.txt](https://github.com/Courseplay/courseplay/files/4866258/log.txt)

**Comment by pvaiko** [comment]
Wenn du die release beschreibung liest kannst selber sehen dass wir in 34 nix geändert haben ausser die Exception Handling. Daran kann es nicht liegen. Das jetzt ältere Versionen nicht mehr funktionieren deutet auch darauf hin dass 34 ist nicht das Problem ist.
