### ISSUE TITLE
Offloader Wont Find Combine (Dedicated Server)

### ISSUE THREAD

**Issue by Redlinedracer** [Courseplay/courseplay#5701]
Hello, my offloader is not locating any combines when using courseplay. They sit at the waiting area with their lights going without moving. 

Image from offloader:
https://gyazo.com/1348e486875d93a5dfda1792a564ff6c

Imagefrom combine:
https://gyazo.com/98927b2d9c2eec390840ccb1153c02fb

Game log file pastebin:
https://pastebin.com/aNvryDAj

Server log file pastebin:
https://pastebin.com/RYJPVzNH

**Comment by Redlinedracer** [comment]
I realize I posted a screenshot from the wrong combine. 

Updated:
https://gyazo.com/944e5de9db6a1b60ca6238a98a2940c7

I noticed on previous versions of courseplay there was an option for the offloader to "automatically" locate the next combine to empty. That field seems to be missing from mine and I've seen screenshots of other people with similar errors that are missing that field as well. 

If that was remove don purpose than it's not related so never mind, but was just something I noticed.

I've tried adjusting some of the other settings - none of them seem to make any difference.

Settings page:
https://gyazo.com/c2f2abc5e7cea2b78ad0ddd1cacc98b5

Other settings page:
https://gyazo.com/bd8511fff7e5c4aa05ac2a92546a0c2b

**Comment by Redlinedracer** [comment]
I tried running courseplay in singleplayer (to make sure my file was okay) and it works.
** I used one of FS19s default maps
** I used all the same mods

However, I then went back onto the multiplayer server and did everything the same I had done it in singleplayer and had the same issues as before.

Sorry for so many notes but wanted to make sure I provided as much as I possibly could.

Thanks for everything you guys do! This is one of my favorite mods - I can't imagine how much of a pain in the A* this is to work on.

**Comment by Redlinedracer** [comment]
What does the Mode2 label mean? 

I clearly understand what "MP Mode" means haha.

**Comment by twistedsanity** [comment]
Just wanted to add I get what seems to be the exact same issue. Tried the same test using local game and also works, just not when running as a dedicated server. Happy to help and provide logs/further info but not sure what would be exactly wanted or which debug to switch on.

**Comment by Redlinedracer** [comment]
@twistedsanity - Do you want to post any log info and anything else you have just to cover our bases?

@Tensuko  - Any info on what the "mode 2 " label means? - Just want to make sure i'm on the same page.

Thank you again for your help!

**Comment by twistedsanity** [comment]
I will run some tests this weekend (guess I should use the latest version in case its fixed?) and provide log files, from my notes available on my phone I was seeing this in the logs:
CombineUnloadManager: Combine with most fill level is N/A
and in game it was showing the combine as: .......readytounload = false

**Comment by twistedsanity** [comment]
Removed all mods, used a completely fresh load, picked up a contract hiring the equipment to test. Towards the end of the file I clicked a few other debug channels to see if I could get anything more useful.

https://pastebin.com/s5fuu99F

**Comment by Redlinedracer** [comment]
Have you heard anything on this @twistedsanity ?

**Comment by twistedsanity** [comment]
No, but the team on courseplay are obviously very busy and with any 'free' dev work its not fair for ETA's. If you look at the commits there is a lot of work going on and I think this issue is part of a much bigger rewrite/rework which is looking very interesting.

**Comment by schwiti6190** [comment]
Hi there this one might take a while longer, as I am currently working on a diffrent part. It would interesting to know if the mode 2 is working in some form in MP, I would appreciate if you could tell me the working situations.

**Comment by Redlinedracer** [comment]
Could you tell me what you mean by "mode 2"? I'd be willing to run some tests.

**Comment by twistedsanity** [comment]
@schwiti6190 I'll try some tests over the weekend and see what I can get working. If you want to list out some scenarios I am happy to try and feedback. Also as my server is pretty much empty till we are fully functional again I guess I could give you access to test too if you want. (Its normally 24/7)
