### ISSUE TITLE
Tractor stops with CP on Combine FillLevel

### ISSUE THREAD

**Issue by Dennizzzzz** [Courseplay/courseplay#5703]
When I set the Driver Priority to Fill level, and start CP for tractor that should unload the combine, CP stops.

![2020-07-03 13_21_40-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/86481133-ae25cb80-bd4f-11ea-9abd-d2cb993e4248.jpg)

![2020-07-03 17_02_11-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/86481138-b1b95280-bd4f-11ea-97f4-a91388729853.jpg)

log error: attempt to call method 'getFillLevelPercent' (a nil value)

After switching tractor (from John Deere to Fendt) and restart FS, unloading on Fill Level works fine.
Switching to another tractor, and again getting the same error.

Added log 1: keep getting the error over and over again also switching between different tractors (not mod tractors).
[log.01.txt](https://github.com/Courseplay/courseplay/files/4870327/log.01.txt)

Log 2: after restart, and using the Fendt tractor (not a mod), it works fine.
[log.02.txt](https://github.com/Courseplay/courseplay/files/4870328/log.02.txt)

I use the modded combine Ropa Panther 2.

I'm not sure if this is related to the Modded combine or to CP

CP stopping related to Courseplay for FS19 v6.02.00034?

Courseplay for FS19 v6.02.00035
Map: RusticAcres_V3

**Comment by Tensuko** [comment]
And why do you set it to Fill level ?
We are not suporting more then 1 unloader yet!

**Comment by Dennizzzzz** [comment]
Ow, I thought the tractor was looking at the fill level of the combine to
check if it was over 50% (default) to start driving to the combine.

**Comment by Tensuko** [comment]
Nope, thats set with the % on the Mode2 Driver.
