### ISSUE TITLE
Stopping passed wait point

### ISSUE THREAD

**Issue by moose31608** [Courseplay/courseplay#5704]
When unloading grain cart into Trailer the tractor stops pass the wait point that is setup
[log.txt](https://github.com/Courseplay/courseplay/files/4871295/log.txt

![fsScreen_2020_07_03_15_56_56](https://user-images.githubusercontent.com/53488388/86495365-12905d00-bd47-11ea-8ac2-947801bf9a18.png)

**Comment by Tensuko** [comment]
And who said that Auger Wagons are supported in Mode2 ?

**Comment by moose31608** [comment]
Why?

**Comment by moose31608** [comment]
I use auger wagons. Where in from that’s how we do it in real life

**Comment by Tensuko** [comment]
Yea but Mode2 is not made for that.
We got Mode3 for it wich isn't ready yet.
