### ISSUE TITLE
Noch Mal  Mode 2 geht nicht

### ISSUE THREAD

**Issue by John-Deere89** [Courseplay/courseplay#5705]
Drescher wird nicht abgefahren seid der neuen Mode 2 er soll bei 15% los fahren aber das macht er einfach nicht O.o

![20200704181229_1](https://user-images.githubusercontent.com/63151473/86516594-32488380-be22-11ea-918c-a072a51c9f4b.jpg)

![20200704181237_1](https://user-images.githubusercontent.com/63151473/86516595-3379b080-be22-11ea-86ab-02d602bd7296.jpg)

Ich bin Ratlos  denn ich habe nur euer CP Aktualiesiert  daher versteh ich nicht was ich falsch gemacht haben soll O.o

Wie können wir das Problem losen? :)

**Comment by Tensuko** [comment]
Ganz einfach in dem man weis wie es sein soll:
Im ersten Vorgewende tanken wir keinen fahrenden Drescher ab!
Der Drescher muss auf Fruchtumfahrung aktiv stehen, dann baut er wenn er fast voll ist seine Tasche im ersten Vorgewende und ruft den Abfahrer.
Und wir brauchen auch keine 100 Issues über das selbe 'Problem' ...

**Comment by John-Deere89** [comment]
Wird wieder geschlossen ohne zu warten oder zu schauen ob es wirklich ein fehler ist das ist keine Professionelle hilfe 
kann ja mal erwarten das man sich drum kümmert und nicht einfach ab hackt wie man lust hat

zumall der Drescher auch wenn er voll ist nicht Abgetankt wird da der fahrer nicht zum Rohr kommt!

**Comment by Tensuko** [comment]
Worauf soll ich denn warten ?
Bis doch mal die nötigen Infos beigelegt werden ?
Logfile, debugchannel, Video usw usw.
Aber noch einmal: für das gleiche Problem brauchen wir nicht mehrere Issues, schon gar nicht 'Noch Mal Mode 2 geht nicht'
