### ISSUE TITLE
problems with mode 2, pushing chaff in the trench and blocking the tractors

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#5707]
I tried to chop a corn field using two tractors and a single forage harvester (I know it is not fully supported yet, but I must say that it works well enough, once you have made a turn around the field with the forage harvester, the tractors pass by without crashing). I had two questions to ask: I set the chaff pushing path, but the grader collects so little that I can't push everything before the next load: do you know any tricks to solve this problem? I tried to increase the capacity of the grader by 10 times (4.7mt wide, capacity after the modification of 70000, pushed by a JD8400R). When the tractor with the trailer approaches the unloading, at 50 meters it stops to allow the tractor that pushes to be able to exit the trench, however, after unloading, always at 50 meters it stops and no longer moves. If you move it a few meters manually then it will resume the path correctly. Any solution?

Log:[log.txt](https://github.com/Courseplay/courseplay/files/4873832/log.txt)

The amount of chaff that drives each time:
![Farming Simulator 19 04_07_2020 22_42_13](https://user-images.githubusercontent.com/59969508/86520814-dc3b0680-be48-11ea-87ab-6db030e1bcf1.png)

The tractor stops at this point (50 meters) and does not start again:
![Farming Simulator 19 04_07_2020 22_42_32](https://user-images.githubusercontent.com/59969508/86520825-01c81000-be49-11ea-92e5-00f135836199.png)

**Comment by 0Pietro20** [comment]
I use the v6.02.00035 version

**Comment by Tensuko** [comment]
Where is the course for the unloader ?
It always helps if you show all waypoints...

**Comment by 0Pietro20** [comment]
In a few hours I enter the game and show the path that the tractor uses to unload. To facilitate the push of the chaff, however, there are no shortcuts?

**Comment by Tensuko** [comment]
What kind of shortcuts are you looking for ?
There is no function like in shovel mode to control the blade if you ask for this.

**Comment by 0Pietro20** [comment]
I don't really know, I thought that maybe by increasing the capacity of the loader it was possible to collect and push more material every time, because I noticed that the tractor has difficulty pushing everything before the arrival of another load. Since I don't know if it's just my problem but the shovel fills me at the MAXIMUM of 2/3% before passing over the material without collecting it I wanted to know if maybe there was any solution. If it is not clear later, when I make the screenshot to the trailer path I also make a video of the silage push

**Comment by 0Pietro20** [comment]
This is the path that tractors with trailers take to unload the chaff:
![Farming Simulator 19 06_07_2020 11_38_47](https://user-images.githubusercontent.com/59969508/86579339-7a2fed80-bf7d-11ea-9439-ad0991e14b82.png)
![Farming Simulator 19 06_07_2020 11_39_03](https://user-images.githubusercontent.com/59969508/86579536-be22f280-bf7d-11ea-9ccd-d9b03ddf7071.png)

This is the path for pushing the chaff:
![Farming Simulator 19 06_07_2020 11_39_23](https://user-images.githubusercontent.com/59969508/86579492-b19e9a00-bf7d-11ea-92ed-9f6c4a7dd4fc.png)

**Comment by Tensuko** [comment]
Somehow the shield capacity will be x3 and we don't know why yet.
About blocking, not sure what cause the problem.
Is it blocking on the way back just as you shown in the screenshot ?

**Comment by 0Pietro20** [comment]
Yes, as shown in the screenshot shown at the beginning though (the one with the tractor with the trailer). It stops when the tractor with the shovel starts to push. When it comes close (50 meters I set) the tractor with the trailer stops to wait for the other to come out of the trench, unload and when he comes back, once again at 50mt from the tractor with the shovel (which begins to push) it stops. I have to stop the path, move it a few meters and then start again

**Comment by Tensuko** [comment]
Try Version 6.03.00018 or higher

**Comment by Tensuko** [comment]
Will close this, it is basically working.
