### ISSUE TITLE
Combine 'stop during unloading' disabled and 100% filled will not be unloaded

### ISSUE THREAD

**Issue by Dennizzzzz** [Courseplay/courseplay#5708]
I noticed that if a combine is 100% full, and waiting to be unloaded, and when the setting 'Stop During Unloading' is deactivated, the unloader tractor will stop behind the combine waiting for the combine to start driving. But it will never start, because it is full.

![2020-07-05 22_28_16-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/86543019-1d035000-bf1b-11ea-9e3a-9af45d00576e.jpg)
In above image the tractor is stopped, waiting for the combine to start driving.

As soon as I activate the 'Stop During Unloading', the tractor will start driving to the combine and unload it.
![2020-07-05 22_28_36-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/86543023-36a49780-bf1b-11ea-923e-6189ae69554e.jpg)

![2020-07-05 22_28_52-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/86543026-3f956900-bf1b-11ea-9487-f99997abd882.jpg)

[log.txt](https://github.com/Courseplay/courseplay/files/4875754/log.txt)

Courseplay for FS19 v6.02.00037
Map: RusticAcres_V3

**Comment by pvaiko** [comment]
2020-07-05 22:06 Error: Running LUA method 'mouseEvent'.
2020-07-05 22:06 C:/Users/dedam0/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/settings.lua:1786: attempt to call method 'shiftCombinesList' (a nil value)

@schwiti6190 can you look at this?

**Comment by schwiti6190** [comment]
@pvaiko I will have a look at it
@Dennizzzzz Did you have more the one combine on the map, might be a problem with the select combine List  ?

**Comment by Dennizzzzz** [comment]
@schwiti6190 I have two combines on the map at the time of this issue. But I did not noticed any problems with the combine list selection.

**Comment by schwiti6190** [comment]
I've added a few saftey checks might fix the problem. At least I couldn't recreate the bug with my changes.
