### ISSUE TITLE
Few Callstacks with Version v6.02.00037

### ISSUE THREAD

**Issue by Omat1998** [Courseplay/courseplay#5709]
Since the latest Version I´ve got these callstacks: 
[log.txt](https://github.com/Courseplay/courseplay/files/4876208/log.txt)

**Comment by Tensuko** [comment]
Full logfile and more details on what you did.

**Comment by Omat1998** [comment]
My log file is already in the first post.

I just did normal work with courseplay, harvesting maize and cultivate

**Comment by Tensuko** [comment]
That is not a complete logfile!

**Comment by Omat1998** [comment]
Sorry, i thought it shows all the Interesting errors.

I have a few mods in the game, but they are the same i used in the last Versions and no Callstacks came in
[log.txt](https://github.com/Courseplay/courseplay/files/4879498/log.txt)

**Comment by Tensuko** [comment]
Do you have some kind of flattrailer attached ?

**Comment by Omat1998** [comment]
yes but not with courseplay.
i just picked some bales when the AI Driver was cultivating

**Comment by Tensuko** [comment]
Yea but that is where this callstack comes from. It is harmless and got no impact. Also no LUA Error. Nothing to worry about.

**Comment by Omat1998** [comment]
Ok thank you :D
