### ISSUE TITLE
Ad und Cp Stroh abfahren

### ISSUE THREAD

**Issue by Bandesss** [Courseplay/courseplay#5710]
Hallo zusammen
Kein Fehler nur eine Frage 

Habe die neueste Version von Cp und AD
Leider geht das Stroh abfahren nicht mehr.
Früher gabs im vierten Reiter von Cp den Punkt usw Ad for load an unload.

Seit es nun, in den erweiterten Einstellungen ist bei Cp geht es nicht mehr.
In welcher Cp Version war diese Knopf noch im vierten Reiter ?
Oder warum geht es nicht mit der neuesten Version von CP!?

**Comment by Tensuko** [comment]
Das kann ich dir nicht sagen warum es nicht mehr geht.
Hast du nach dem einstellen auch auf OK gedrückt ?

**Comment by TobiHH78** [comment]
Bei mir geht das ohne Probleme. Habe auch jeweils die neueste Version.
Ein paar mehr Infos und die LOG wären sicher hilfreich.

**Comment by Bandesss** [comment]
Kannst du mir bitte sagen was du einstellst ?
Wir spielen die Kandelin.
Kollege sagte gestern
Zitat ; Gestern hatte ich komische Meldungen in der Konsole. Übergabe cp an ad für die strohabfahrt hat nicht funktioniert.

**Comment by Tensuko** [comment]
Aha, die Info für MP ist wichtig.
Ob das bereits funktioniert kann ich nicht sagen, siehe #5484

**Comment by Bandesss** [comment]
> Das kann ich dir nicht sagen warum es nicht mehr geht.
> Hast du nach dem Einstellungen auch auf OK gehört?

Ja unter erweiterte Einstellungen
Welche Version von CP hatte den Punkt noch im Reiter 4?

**Comment by Tensuko** [comment]
Das sollte für die Funktion an sich keine Rolle spielen.

**Comment by Bandesss** [comment]
Ja aber mit der Version ging es auf dem Server.
Darum hatte ich gefragt

**Comment by Bandesss** [comment]
Kann mir jemand die Version sagen, wo es den alten Punkt gab?
Habe jetzte mehrere Versionen durch geht halt nicht.

**Comment by Tensuko** [comment]
Wie ich bereits sagte.
Das verschieben der Option ist nicht die Ursache.
Das ist mit Version 00005 geschehen und somit ist in 00004 die Option noch an alter Stelle.
In der Zeit hat sich seeeehr viel getan, gerade für den MP bereicht.
Kann sein das wenn du auf 00004 zurück gehst viele andere Dinge im MP nicht laufen.

**Comment by Bandesss** [comment]
Sehr schade, wie gesagt so funktioniert es nicht...
Ich kann nicht mehr als in den einstellungen auf AD an schalten oder ?

**Comment by Tensuko** [comment]
Verstehe ich nicht...
Du kannst das in den erweiterten Einstellungen einstellen ?

**Comment by Bandesss** [comment]
Ja aber da passiert eben nichts

**Comment by Tensuko** [comment]
Muss dann am MP liegen wenn es im SP geht.... Abwarten...

**Comment by Bandesss** [comment]
darum habe ich ja gefragt, es hat ja mit dem alten symbol in reiter 4 geklappt im MP
Daher wollte ich die Version wissen.

**Comment by Bandesss** [comment]
@Tensuko bei welcher Version war der Button noch vorne ?

**Comment by Tensuko** [comment]
> 
> 
> Wie ich bereits sagte.
> Das verschieben der Option ist nicht die Ursache.
> Das ist mit Version 00005 geschehen und somit ist in 00004 die Option noch an alter Stelle.
> In der Zeit hat sich seeeehr viel getan, gerade für den MP bereicht.
> Kann sein das wenn du auf 00004 zurück gehst viele andere Dinge im MP nicht laufen.

Hab ich doch oben geschrieben....

**Comment by Bandesss** [comment]
0004 heißt 6.02.00034?
Danke

**Comment by Tensuko** [comment]
00004 heist 00004 ansonsten hätte ich 00034 geschrieben.
Und ja 6.02.xxxxx alles darunter ist käse.

**Comment by Bandesss** [comment]
Ich meinte mit der 26 oder 27 ging es auch noch

**Comment by Tensuko** [comment]
Und warum fragst du dann ?
Ich hab dir nun gesagt wann deine Einstellung weggewandert ist.
Das es damit nichts zu tun hat, habe ich dir bereits gesagt.
Wenn du meinst das es mit der 26 oder 27 auch noch ging, dann nutze die doch...

**Comment by Bandesss** [comment]
Sorry wollte niemand angreifen, wie gesagt wo die Funktion vorne war ging es halt . Ist nur eine Gestellung.
SorrY nochmals und danke

**Comment by Bandesss** [comment]
So neue Serverlog
[Gamelog.txt](https://github.com/Courseplay/courseplay/files/4904480/Gamelog.txt)
Hoffe ihr findet was ?
Gruß

**Comment by Bandesss** [comment]
Also es geht mit der neuen Version immer noch nicht
Könnt ihr mir helfen ?

**Comment by Bandesss** [comment]
Also mit 00004 gehts eiwandfrei auf dem Server, 
Warum musste man, die Version so umbauen das es auf dem Dedi nicht mehr geht ?

**Comment by Tensuko** [comment]
Ich mach das hier gleich zu.....
Als ob wir etwas mit absicht UMBAUEN das es nicht mehr geht.
Wir sind halt viel am vorbereiten umbauen neubauen etc, das sowas mal bei raus kommt ist halt so!

**Comment by Bandesss** [comment]
Ja ok, aber nun wisst ihr das es nicht mehr geht :)
Sorry nochmal
