### ISSUE TITLE
Courseplay leveling in a bunker

### ISSUE THREAD

**Issue by Redrooster1-web** [Courseplay/courseplay#5711]
Hello, when i'm using a tractor and in game Mes 400 to lvl chaff in a bunker on Bjornholm 19, its just not working.

Set-up: tractor about a quarter way inside bunker facing outwards, start course, go forward to a safe point set P, REVERSE BACK IN LINE OR AS NR TOO MIDDLE OF BUNKER AND STOP SHORT OF ENTRANCE, hit stop crse.  Save crse, and hit drive it starts to do circles, over and over.  This is not usuall. CAN YOU HELP??

**Comment by Tensuko** [comment]
logfile, screenshot of course with all WP on.

**Comment by Redrooster1-web** [comment]
Hey Tensuko i sent you screenshots and log yesterday, 8\06\20 are you working on my problem.

**Comment by Tensuko** [comment]
and where ?
why not attach it here ?

**Comment by Tensuko** [comment]
Closed due to inactivity.
Bunker mode is working ok so far, sure have some problems with different blades and bunkers, but that is general enhancement.
