### ISSUE TITLE
Settings not being saved

### ISSUE THREAD

**Issue by p0wderkeg** [Courseplay/courseplay#5712]
Any changes made to anything on the settings page does not get saved or used. Combine unload, tool lower early/late, etc.  This is happening on either version 35 or 37.  This started happening after I removed CP from the mods to see if a mod was causing lag issues, after I put all mods back in nothing will save or get used.  It shows activated bus does not get used, and after I exit and come back into game the settings are back to deactivated.  Is there something I'm missing?

**Comment by Tensuko** [comment]
But you do press ok on the settings page ?
else try to delete courseplaySettings.xml in your savegame folder.

**Comment by p0wderkeg** [comment]
Yes I have pressed ok.  I have also tried to delete all the courseplay files.  Even went through vehicles.xml and removed all the CP entries.  Once CP was started again all entries in vehicles.xml were put back.   I also bought a new vehicle to see if issue was just on previous owned vehicles but that had same issue.  I just tried version 34 and same issue.  Not sure what happened.

**Comment by Tensuko** [comment]
and if you start a new savegame with mods active on start ?
can you attach your logfile ?

**Comment by txmazing** [comment]
Same here. We are playing in MP.

**Comment by Tensuko** [comment]
pls don't mix up SP and MP.....

**Comment by Tensuko** [comment]
Checked settings and for SP they get saved without any problem.
