### ISSUE TITLE
Tipps für Kurserstellung mit Knicklenkerschlepper und den großen Sähmaschienen die 2 Anhänger haben

### ISSUE THREAD

**Issue by RobinHooooood** [Courseplay/courseplay#5716]
Da Cp bei normalen Kursen nicht schafft solche Sähmaschien zu wenden bzw. Vorgewende usw. zu lenken Frag ich mal euch wie Ihr das macht mit der Kursgenerierung für die großen Sämaschien z.b die Väderstad  Seed Hawk XL Toolbar 84 FT mit der  Väderstad  Seed Hawk 980 Air Cart

**Comment by Tensuko** [comment]
Naja die Kursgenerierung ist so wie sie ist. Die Wendemanöver werden on the fly berechnet.
Was ich für solche großen Geräte empfehle ist:
- Mindestens 2 mal Vorgewende
- Runde Ecken (nicht die ganz weichen, obwohl das auch eine option wäre)
- Feldreihen übersüringen auf 1 könnte noch gut klappen, somi ist mehr Platz vorhanden.

**Comment by Merrlin** [comment]
Es gibt da noch eine Funktion für die Feldmitte. Heißt spiralförmig oder so. Da klappt (oder klappte, hab's schon länger nicht gemacht) es eigentlich ohne Probleme.

**Comment by excubated** [comment]
I ran the smaller of the Borgault trains (24m?) yesterday, on an L shaped field. Turned AI pathfinding on, but left turning and reversing off, 2 headlands, up/down center with no lane skip. The seeder train was pulled by the flagship Claas tractor with all wheel turning on, and this managed to do the 180 degree turns in a simple curve 👏

**Comment by Tensuko** [comment]
Denke das hier ist geklärt.
