### ISSUE TITLE
Auffüllen mit COurseplay

### ISSUE THREAD

**Issue by tobestar1995** [Courseplay/courseplay#5717]
Hallo,

ich habe mir die neueste CP Version runter geladen. Ich habe jetzt das Problem das meine CP Fahrer wenn meine Sähmaschiene oder mein Kalk/Düngerstreuer leer sind zwar den auffüllkurs an- und abfahren, aber sie halten nicht unter meinem Silo und beladen die jeweilige MAschiene nicht, sonder fahren einfach weiter.
Muss ich seit neuestem einen Pausepunkt zum beladen setzen?

Wäre echt cool wenn ihr mir Helfen könntet.
Danke schon mal im Vorraus

**Comment by Tensuko** [comment]
Bitte mal ein Screenshot von der position wo aufgefüllt werden soll.
Ale Wegpunkte an (HUD die 3 Punkte) und vorallem welche Geräte du benutzt.
Und: SP oder MP ?

**Comment by tobestar1995** [comment]
Ich spiele auf der NF Marsch 4-fach im Single Player.
Ich nutze zum einen den Standart Düngerstreuer Bredal K165 und eine, mit Multifrucht geänderte, Amazone Condor 15001 Sähmaschiene.
<img width="1536" alt="Screenshot (1)" src="https://user-images.githubusercontent.com/64160319/87016500-143aa480-c1cf-11ea-855e-38e2387793cf.png">

**Comment by Tensuko** [comment]
Debugchannel 1 und 2 an, Kurs laufen lassen, komplettes logfile anhängen.
Wobei ich nicht sicher bin ob die Saatmaschine an einem normalen Hofsilo aufgefüllt werden kann.
Ich nutze normal dafür die Saatgutsilos.

**Comment by excubated** [comment]
The last couple of versions I have noticed that the "covers" setting that previously defaulted to auto (or on, don't remember), suddenly was set to disabled. When CP is not allowed to operate the covers, they just drive past the filltrigger.

Off topic, but noticed around the same time; the max speed set in CP that previously defaulted to "Recorded" now defaulted to maximum. Both issues seem to occur only once per tractor model, after changing to desired setting it seems to stick to it through modifications (wheels, engine etc.) and even between saves and maps.

**Comment by Tensuko** [comment]
Covers is already fixed...
Speed must check.

**Comment by tobestar1995** [comment]
Sorry für die bescheuerte Frage aber was sind die Debug channel?

**Comment by Tensuko** [comment]
Bescheuert ist die Frage nicht :)
Im CP bei den Settings sind unten so Zahlen.
Die auf grün machen dann werden Daten in das logfile geschrieben.

**Comment by tobestar1995** [comment]
Und das logfile ist dann das Textdokument was im LS Ordner ist oder?

**Comment by Tensuko** [comment]
Ja

**Comment by tobestar1995** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4902418/log.txt)

Hallo hier die log. Ich hoffe du kannst etwas damit anfangen. Vielen Dank schon mal für deine Hilfe

**Comment by Tensuko** [comment]
Du müsstest mal so ein paar Mods aktualisieren:
(Version: 6.02.00031) FS19_Courseplay
(Version: 1.0.0.0) FS19_addon_strawHarvest
(Version: 1.1.0.3) FS19_AutoDrive
(Version: 1.5.0.0) FS19_GlobalCompany

Ich probiere das heute mal aus, ob wir da ein bug haben, lange nicht gemacht.
Aber die log zeigst sonst erst mal nichts an.

Nur mal so ganz doof gefragt:
Ist denn noch Saatgut und Dünger im Silo ?

Ansonsten versuch es bitte mal mit extra platzierbaren Silos für Saatgut und Dünger.
Ich kann dir diese heir empfehlen: https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=140850&title=fs2019
Oder wenn du Lager willst, kann ich dir die Lager in diesem Pack empfehlen:
https://ls-modcompany.com/filebase/file/243-ls19-geb%C3%A4ude-pack/

**Comment by tobestar1995** [comment]
Ja Saatgut und Kalk sind im Silo
Das Fahrzeug zeigt auch unten an:

"Wird beladen 0von 18950" aber er hält nicht unter meinem Rohr an. Mit einer anderen CP Version wurde auch die Sähmaschiene am gleichen Silo beladen. 
Ich probiere es jetzt mal mit den anderen Lagern.

**Comment by tobestar1995** [comment]
ICh glaube ich habe meinen Fehler jetzt gefunden.
Und zwar war meine Geschwindigkeitseinstellung (warum auch immer vielleicht verklickt) auf maximal eingestellt. Dadurch hat der CP Fahrer zu spät gebremst und den trigger zu schnell überfahren. ich beobachte das jetzt nochmal.

**Comment by excubated** [comment]
> Off topic, but noticed around the same time; the max speed set in CP that previously defaulted to "Recorded" now defaulted to maximum. 

> Covers is already fixed ...
> Speed ​​must check.

Huh, didn't realize the max speed defaulting could actually directly affect refilling 😅

**Comment by tobestar1995** [comment]
Das mit dem befüllen klappt nun wieder.

Es haben sich aber mehrere fragen bezüglich den abfahr-Modus aufgetan mit der neuen Version

1. Ich kann den Traktoren die Drescher nicht mehr zuweisen. Bei einigen Traktoren werden sie mir angezeigt bei anderen nicht.
2. Die Traktoren fahren die Dresche auch im Automatikmodus nicht richtig an. Das heißt entweder sie fahren viel zu weit weg oder sie fahren in den Drescher. 
3.Die Traktoren fahren (Ich spiele mit deaktivierter Fruchtzerstörung) einfach nur rückwärts nachdem die Drescher leer sind und fahren nicht aus der Frucht raus, damit der Drescher vorbei fahren kann

Ich hoffe ihr könnt mir eiterhin so gut helfen wie mit meinem anderen Problem

Vielen Dank im Vorraus schon mal und einen schönen Montag noch

**Comment by Tensuko** [comment]
>     1. Ich kann den Traktoren die Drescher nicht mehr zuweisen. Bei einigen Traktoren werden sie mir angezeigt bei anderen nicht.

Beim Abfahrer einmal Modus wechseln, kann sein das der Drescher nicht richtig registriert wurde.



>     2. Die Traktoren fahren die Dresche auch im Automatikmodus nicht richtig an. Das heißt entweder sie fahren viel zu weit weg oder sie fahren in den Drescher.

debugchannel 4 7 12 und 14, screenshots und logfile



>    3. Die Traktoren fahren (Ich spiele mit deaktivierter Fruchtzerstörung) einfach nur rückwärts nachdem die Drescher leer sind und fahren nicht aus der Frucht raus, damit der Drescher vorbei fahren kann.

Fruchtumfahrung beim Drescher einschalten, somit fahren die Abfahrer auch nicht in die Frucht sondern immer nur dann, wenn das Rohr des Dreschers außerhalb der Frucht ist.


>     4. Wenn ich in die Drescher einsteige und einen Traktor rufe, dann passiert gar nichts.

Das kommt auf die Situation drau an, aber du solltest den Knopf einfach nicht drücken.... davon abgesehen, Drescher müssen mit CP gefahren werden damit das Abfahren überhaupt klappt.

Siehe #5272 da ist auch ein Video wo man bisschen was sehen kann.

**Comment by tobestar1995** [comment]
<img width="1229" alt="Screenshot (2)" src="https://user-images.githubusercontent.com/64160319/87319381-d967a200-c529-11ea-929f-2c6cdef6f4d5.png">
![Uploading Screenshot (3).png…]()
![Uploading Screenshot (4).png…]()
[log.txt](https://github.com/Courseplay/courseplay/files/4913264/log.txt)

**Comment by tobestar1995** [comment]
<img width="1229" alt="Screenshot (2)" src="https://user-images.githubusercontent.com/64160319/87319947-94903b00-c52a-11ea-8835-21b018b137cb.png">
[log.txt](https://github.com/Courseplay/courseplay/files/4913284/log.txt)
<img width="1229" alt="Screenshot (4)" src="https://user-images.githubusercontent.com/64160319/87319997-a2de5700-c52a-11ea-8ad7-64ded42cbe16.png">

**Comment by Tensuko** [comment]
Und ? Ist die Fruchtumfahrung beim Drescher an ?


> Fruchtumfahrung beim Drescher einschalten, somit fahren die Abfahrer auch nicht in die Frucht sondern immer nur dann, wenn das Rohr des Dreschers außerhalb der Frucht ist.

**Comment by tobestar1995** [comment]
Jetzt ja und jetzt funktioniert das auch.
Aber nochmal zu den Auffüllkursen. Wie kann es sein, das Mein CP Fahrer trotzdem das ich den Kurs gar nicht mit angehängt habe, trotzdem zu meinem Silo fährt obwohl ich eigentlich wollte das er mit Autodrive fahren soll?

**Comment by tobestar1995** [comment]
https://www.youtube.com/watch?v=NVpyZD_PILk

habe mal ein Video auf youtube gemacht um das zu verdeutlichen

**Comment by Tensuko** [comment]
Keine Ahnung was da ab geht.
Debugchannel 12 und 14 hätten da vlt geholfen.

**Comment by tobestar1995** [comment]
https://youtu.be/ColWW9NJbfk
[log.txt](https://github.com/Courseplay/courseplay/files/4926083/log.txt)

**Comment by knoxville73** [comment]
Hi,

I have the same problem to refilling but not with all tools.  With the Pronto 9 DC, all is perfectly running.  With the Kverneland DF2 + NG-S 101 F35 (official mod) and the same course, the seeder is not refilled.
