### ISSUE TITLE
6.02.00037 Header with inbuilt trailer unfolding and clipping under field on unload transition

### ISSUE THREAD

**Issue by excubated** [Courseplay/courseplay#5718]
Running a non-modhub (I think?) combine with vanilla 13.7m header, and decided to try out the combine self unloading switch in advanced options. Combine correctly transitioned from harvesting to unload course when nearing full, but CP decided to unfold (fold?) the header in the process. This alone wouldn't be a problem, but for some reason the header clipped under the field, causing all four wheels on the combine to lift off the ground when CP triggered "lift header". 

Attached logfile and screenshots.

[log-reset-080720.txt](https://github.com/Courseplay/courseplay/files/4891480/log-reset-080720.txt)
![20200708164717_1](https://user-images.githubusercontent.com/1683752/86936398-3e905180-c13e-11ea-923e-a23953e13163.jpg)
![20200708164634_1](https://user-images.githubusercontent.com/1683752/86936401-3fc17e80-c13e-11ea-94dd-69d8df746e9d.jpg)

**Comment by Tensuko** [comment]
Got nothing to do with Mode3 or Mode2.
Actually it is Mode6 but anyway, will try that one out, never noticed this.

**Comment by excubated** [comment]
Whoops sorry, I thought 3 was combine self unload 🤦

**Comment by Tensuko** [comment]
Can't reproduce.
![fsScreen_2020_07_08_18_35_26](https://user-images.githubusercontent.com/27344744/86945870-dd6e7b00-c149-11ea-9de2-e7c108553480.png)
attach full logfile pls.
Also I wonder, why did you combine 2 course ?
You can only load Fieldcourse for Combine and start it, nothing more.

Modes are just counted from left to the right.
Mode1-10 while Mode3 is not active yet and Mode7 won't come back.

**Comment by excubated** [comment]
The attached log file isn't edited, i just have a habit of renaming the current log.txt file whenever I encounter any issues. I can upload the previous two as well, but the log attached in first post is from the last two days or so.

The second course is unload course to waiting trailer, I thought maybe harvester on self unload worked the same as loading wagon field work + silo unload 🙄

I will try to reproduce with my map and customization of the harvester, which debugs should I enable for this?

**Comment by Tensuko** [comment]
> The attached log file isn't edited, i just have a habit of renaming the current log.txt file whenever I encounter any issues. I can upload the previous two as well, but the log attached in first post is from the last two days or so.

oh yea sry didn't see that one.



> The second course is unload course to waiting trailer, I thought maybe harvester on self unload worked the same as loading wagon field work + silo unload

self unload does not need an unload course, as it will generate its path to the trailer by itself and I think there is the reason for this Issue, couse when have a 2nd course, it will fold the tools so he can drive the course.

So just try to only have the Fieldwork and run the Combine with selfunload active, it have to work as I just tried it :)

**Comment by excubated** [comment]
Huh, running only the field course (not 2 courses combined) didn't reproduce the error. Worked as expected and the harvester magically found the waiting trailer.

Running a confirming test with combined courses now to verify cause of issue.

![20200708190917_1](https://user-images.githubusercontent.com/1683752/86949920-b155f880-c14f-11ea-88df-638395bc1621.jpg)

**Comment by excubated** [comment]
As you suspected Tensuko, combined courses made combine "fold" the header. Didn't clip and lift now tho, I'm starting to suspect bad work clearing tree stumps before plowing...

Can be closed
