### ISSUE TITLE
Drescher wendet nicht im Feld

### ISSUE THREAD

**Issue by txmazing** [Courseplay/courseplay#5719]
Moin, ich habe festgestellt, dass der Drescher nie im Feld wendet obwohl die Option auf aktiviert steht. Ist das beabsichtigt?

**Comment by Tensuko** [comment]
Ja ist es.
Ein Drescher soll nach möglichkeit nicht in der Frucht wenden, tun sie im realen leben auch nicht.
2 mal Vorgewende sollte immer passen.
