### ISSUE TITLE
Threshing settings

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#5720]
Hi, I wanted to ask if it was possible, maybe in the next versions of the CP implement a manual button that allows you to move the indicator that indicates the back of a shredder. It is known that the shredders of the game, the original ones, except the Krone, have a position marker on the back that is too far back and does not allow the tractor to position behind the forage harvester during the first rows. Maybe, even if manually, it would be nice to be able to move it longitudinally so that you can use any forage harvester without problems

**Comment by Tensuko** [comment]
The wrong position is just on about 2 or 3 Combines so far...
This is not the real Issue.
But we know about it and it does come when its done.
Ofc we are working on stuff in the background but when it is time for it.
