### ISSUE TITLE
CP mit ProSeed nutzen möglich?

### ISSUE THREAD

**Issue by Hartmut88** [Courseplay/courseplay#5721]
Hallo liebe Leute,

kann man was tun, damit CP sauber mit ProSeed zusammenarbeitet?
In meinem Test hat es auf "Semi" (beim ProSeed) nicht funktioniert... auch das HUD vom ProSeed geht weg, sobald CP aktiviert wird. Glaube zu LS 17 Zeiten ging das so per Semi und CP.. 

Das Einzige was bereits funktioniert ist der Auto Modus in Verbindung mit CP. Mann muss dann allerdings GPS genau auf den CP Linien (Kurs) haben.
Da funktioniert dann zwar die automatische Spurschaltung von ProSeed, aber auch nur solange man selbst in Traktor sitzt...
ja und das HUD ist hier ebenfalls verschwunden, wenn man CP einschaltet.

Bin mir jetzt nicht sicher, ob hier überhaupt CP "Schuld" an der "nicht funktionierenden Zusammenarbeit" ist. 
Ich hoffe eine Lösung kann gefunden werden.

**Comment by pvaiko** [comment]
@stijnwop, any idea?

**Comment by Tensuko** [comment]
Fahren im neuen Issue fort, da englisch.
