### ISSUE TITLE
Rundherum Vorgewende

### ISSUE THREAD

**Issue by txmazing** [Courseplay/courseplay#5722]
Moin, ich möchte fragen warum der Kurs für ein Vorgewende welches rundherum geht so berechnet wird wie er berechnet wird :D

Warum wechselt der Kurs erst nachdem er nochmal die selbe Vorgewendespur (West) gefahren ist?
![20200709152706_1](https://user-images.githubusercontent.com/47943772/87051220-95aa2b00-c1ff-11ea-9957-85f4e4059890.png)

Könnte nicht Dünger, Sprit, Kalk, Zeit usw. gespart werden wenn er ähnlich wie beim Wechsel von der ersten zur zweiten Vorgewendespur auf die inneren Feldreihen wechselt?
![20200709153458_1](https://user-images.githubusercontent.com/47943772/87051458-e15cd480-c1ff-11ea-96b1-04daf3d202db.png)
![20200709153748_1](https://user-images.githubusercontent.com/47943772/87051487-ea4da600-c1ff-11ea-9896-09c5130a21d7.png)
![20200709152813_1](https://user-images.githubusercontent.com/47943772/87051508-f20d4a80-c1ff-11ea-9d32-53af56ad204f.png)

**Comment by Tensuko** [comment]
Stare deine Kurse weiter an der Kante und nicht an der Ecke, dann hast du auch weniger Probleme.
