### ISSUE TITLE
Combine 'stop during unloading' disabled and 100% filled will not be unloaded (2)

### ISSUE THREAD

**Issue by Dennizzzzz** [Courseplay/courseplay#5726]
Sorry, problem still exists. 

Issue [#5708](https://github.com/Courseplay/courseplay/issues/5708) was closed, and I tried it again.

Below you see the tractor is not moving, while the combine is 'waiting to be unloaded'.
![1 2020-07-09 22_55_22-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/87090317-0d944780-c238-11ea-89ff-76b26c0825d9.jpg)

Below the tab where you see one combine used on this map.
![2 2020-07-09 22_52_57-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/87090318-0e2cde00-c238-11ea-84ec-96527c7df746.jpg)

Settings of the tractor: Avoid fruit, and Turn on field.
![3 2020-07-09 22_53_32-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/87090319-0e2cde00-c238-11ea-9516-d6c01133b4c4.jpg)

Setting of the combine: Stop during unloading is 'Deactivated'. It is almost full, and 'needs to be unloaded'.
![4 2020-07-09 22_54_14-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/87090320-0ec57480-c238-11ea-8a00-227b1ea61408.jpg)

Other setting of the combine: Turn on field, and Avoid fruit deactivated.
![5 2020-07-09 22_54_41-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/87090323-0ec57480-c238-11ea-972b-b8ca0e91e0f0.jpg)

As soon as I change the setting: Stop during unloading to Activated, the tractor start moving, and will unload the combine (the 'target' text appears).
![6 2020-07-09 22_55_47-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/87090324-0f5e0b00-c238-11ea-8e2b-f80182cf1fba.jpg)

[log.txt](https://github.com/Courseplay/courseplay/files/4899506/log.txt)

Courseplay for FS19 v6.02.00038
Map: Wild West

**Comment by limoman39** [comment]
I too have been having problems unloading a combine using an auger wagon (overloader).  I have tried everything that I know to do but nothing seems to work.  As you see in the picture I am able to pick the combine, I set the overloader to start at 20% but it waited until the combine was at 100% before it moved.  It moved to this position and stopped.  I have removed all mods with the exception of Courseplay and Autodrive.  Please let me know if there is something I am doing wrong.

Thank you
![Overloader Settings](https://user-images.githubusercontent.com/25773892/87104061-cd779980-c224-11ea-9ded-89369a395189.png)
![Overloader went through pause marker](https://user-images.githubusercontent.com/25773892/87104062-cd779980-c224-11ea-92a3-9136976cd055.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4900151/log.txt)

**Comment by limoman39** [comment]
![Overloader waiting for the combine to call](https://user-images.githubusercontent.com/25773892/87106401-61e4fa80-c22b-11ea-8ed4-48aa5adaa281.png)
![Overloader went through pause marker](https://user-images.githubusercontent.com/25773892/87106402-61e4fa80-c22b-11ea-958d-659dd1191113.png)

**Comment by Tensuko** [comment]
And again...
Did anyone say, that Augerwagons are already supported as you do it with wait point and stuff ?

Where are the logfiles with debugchannels discribed in #5272 ?

**Comment by John-Deere89** [comment]
hab ich das Richtig verstanden das mom noch keine ÜLW unterstütz werden?

**Comment by Tensuko** [comment]
Ja. Dafür gibt es den Mode3, welcher noch nicht fertig ist.

**Comment by John-Deere89** [comment]
Ah okay deswegen geht das mit dem ÜLW net gut zu wissen danke :)  Habe das sonst immer mit mode 2 gemacht weil wenn ich ein ÜLW dran hatte mode 3 nicht aktiv wurde auch in ältere versionen vor mode 2 umbau
aber dann weis ich das ich dadrauf erst mal verzichten muss

**Comment by limoman39** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4902352/log.txt)

**Comment by limoman39** [comment]
I did not know this method of using overloader was no longer working.  This was the work around we were using until mode 3 is back again.  
Thank you

**Comment by Tensuko** [comment]
> 
> 
> I did not know this method of using overloader was no longer working. This was the work around we were using until mode 3 is back again.
> Thank you

Workarround is all fine as long as it works, but this is nothing that is 'intended to work' and not supported like this.
If it does work it is fine if not, well then wait untill we have an actual support for it.

**Comment by Dennizzzzz** [comment]
Uhm, the initial issue here is not related to augerwagons unloading to a truck next to the field. I tried this but after some unloading next to the truck instead of in the trailer of the truck, I gave up on that mode. 

In this case I used the augerwagon to unload at the silo of my farm. But still the issue as described remains.

I will so some more testing, and use the comments in #5272, and post the log file here.

One other little thing, I can read German al little bit (i'm from The Netherlands), but my English is much better. And I thought the requested language was English.

**Comment by pvaiko** [comment]
@Dennizzzzz any reason you have fruit avoidance turned off for the combine? The way it is implemented now, it won't unload a moving combine with the pipe in the fruit. This is to avoid destructing your crop :)

https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ

**Comment by Dennizzzzz** [comment]
No reason i have fruit avoidance turned off for the combine. I guess i'm cheating setting the games option 'destroy crops' off :-)

**Comment by pvaiko** [comment]
@Dennizzzzz can you try with https://github.com/Courseplay/courseplay/releases/tag/6.02.00042?

**Comment by Dennizzzzz** [comment]
> @Dennizzzzz can you try with https://github.com/Courseplay/courseplay/releases/tag/6.02.00042?

Of course. I will do this as soon as I possibly can.

**Comment by Dennizzzzz** [comment]
Tried it, and it works with the 6.02.00042 version.
