### ISSUE TITLE
Anregung zum Menü

### ISSUE THREAD

**Issue by John-Deere89** [Courseplay/courseplay#5728]
Könnte man dort es ein wenig so gestateln das man sieht wann man Parken aus gewählt hat Danke :) 
![20200710134854_1](https://user-images.githubusercontent.com/63151473/87151556-5d185900-c2b4-11ea-8a58-664de5661dde.jpg)

**Comment by Tensuko** [comment]
Ich schau mal was man da machen kann :)

**Comment by Tensuko** [comment]
![AD Use](https://user-images.githubusercontent.com/27344744/87189808-99b67580-c2f1-11ea-8485-d75ad00c105a.png)
im Grunde nur den Text angepasst, ist das einfachste.

**Comment by John-Deere89** [comment]
reicht ja völlig aus das man halt erkennt das er auch Parken soll :)

**Comment by Tensuko** [comment]
Wird in der nächsten Relese Version drin sein.
