### ISSUE TITLE
Combine unload AI not working 

### ISSUE THREAD

**Issue by Jam989** [Courseplay/courseplay#5730]
I have set up a course to unload my combine however with v6.02.00038 the tractor and trailer just sit at the stop point and at the bottom of the screen it just flashes combine not in reach and it just loops it, I have selected the combine and field however it changes nothing i have deleted previous version and updated the game and everything but still no change even on brand new saves still the same issue with no mods installed

**Comment by Tensuko** [comment]
#5272 read it pls...

**Comment by Jam989** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4906523/log.txt)

**Comment by Tensuko** [comment]
Realy? ...
Available mod: (Hash: 7c7bee4577d0970c4715eecae77f0505) (Version: 6.02.00038) FS19_CoursePlay
Available mod: (Hash: 5dc1cae467084a1285c509d960cc3c5d) (Version: 6.01.00394) zzz_courseplay
delete the old 394 pls...

Also you have 3 GEO for Seasons, that won't work too.
Also some other mods with Errors, more then one Map too.

Clean up your mods first and then try it again with the Information shown in #5272 
Also your logfile doesn't contain the needed informations from debugchannel 4 7 12 and 14.
