### ISSUE TITLE
Combine harvester does not drive on after unloading (pocket) - Mähdrescher fährt nach Abladen nicht weiter (Tasche)

### ISSUE THREAD

**Issue by haamic** [Courseplay/courseplay#5734]
Hello, since some versions I have observed the following behavior.
A combine harvester or potato harvester is almost full and creates space for the driver (drives a "pocket" in the fruit).
After unloading, it doesn't drive on as long as I "ride along" in the vehicle.
When I get out, it starts moving.
If the vehicle stops normally for unloading, without a pocket, it continues to drive immediately after unloading if I am sitting in it.
Can anyone confirm and/or explain the behaviour?

Greetings Micha
++++++++++++++++++++++++++++++++++++++++
Hallo, seit einigen Versionen beobachte ich folgendes Verhalten.
Ein Mähdrescher oder Kartoffelernter ist fast voll und schafft Platz für den Abfahrer (fährt in der Frucht eine "Tasche").
Nach dem Abladen fährt er nicht mehr weiter, solange ich im Fahrzeug "mitfahre".
Steige ich aus, setzt er sich in Bewegung.
Hält das Fahrzeug normal zum Abladen, ohne Tasche, fährt es auch nach Abladen sofort weiter, wenn ich drin sitze.
Kann das Verhalten jemand bestätigen und/oder erklären?

Gruss Micha

**Comment by Tensuko** [comment]
Logfile mit debugchannel 4 7 12 und 14.
Channel an und Situation nachstellen, Screenshots könnten auch helfen.

**Comment by haamic** [comment]
logfile kommt wenn ich wieder dresche, bestimmt morgen.
ich vergass zu erwähnen, das der Abfahrer AD gesteuert ist. nur der Drescher ist CP gesteuert.

**Comment by haamic** [comment]
hier das log file, kurz bevor er die Tasche macht und dann abgeladen wird, danach stillstand, erst als ich ausstieg fuhr er weiter.

[cp-debug-log.txt](https://github.com/Courseplay/courseplay/files/4909438/cp-debug-log.txt)

**Comment by Tensuko** [comment]
Ich hab von dir noch kein ganzes logfile gesehen.
Ich weis weder deine CP Version, noch welche Mods du sonst noch benutzt um eventuelle Konflikte auszuschließen.

**Comment by haamic** [comment]
Ein ganzes log file brauchst du auch nicht sehen, ich habe dir das log geschickt,wo bei mir dieser Fehler auftritt. CP ist die aktuelle .40 . Mod hatte ich sonst keine, bis auf die Karte kandelin,CP und AD RC 5. Sonst mach erstmal zu. Ich bin  3 Wochen im Urlaub, kann nichts schicken.

**Comment by pvaiko** [comment]
> Ein ganzes log file brauchst du auch nicht sehen

Woher weisst du was ich brauche? Oft ist die Information die ich brauche Minuten bevor das Problem auftrat ins Logfile geschrieben.

```
2020-07-12 22:24 :54 [dbg12 lp1223151] Course with 28009 waypoints created/updated, 144043.7 meters, 211 turns
```
Wow. Ein 144 km Kurs. Das dauert mindestens 15 Stunden :)

**Comment by haamic** [comment]
Ja es dauerte seine Zeit. Hatte nur ein Drescher und das Feld war riesengroß. Klappte aber alles prima wenn ich nicht drin saß, als er die "Tasche" für den Abfahrer machte, Wegen Rohr in der Frucht.
