### ISSUE TITLE
Courseplay and mode 2 issues

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/courseplay#5735]
Hello

I decided, several weeks ago, to use version 6.02 and therefore the new mode 2
However, I see a lot of problems, especially with the forage harvesters (which I use a lot):
- some forage harvesters do not throw the silage far enough when the tractor is behind (including with the BIG X 1180) and the tractor follows too far. There is often too great a distance between the tractor and the forage harvester. Therefore, everything stops. It is therefore necessary to manually advance the tractor.
![image](https://user-images.githubusercontent.com/36656729/87245970-38ee8080-c44a-11ea-9b0d-71b85859fb11.png)
![image](https://user-images.githubusercontent.com/36656729/87245973-4572d900-c44a-11ea-88ef-907e6df27aa5.png)
![image](https://user-images.githubusercontent.com/36656729/87245977-4c99e700-c44a-11ea-94a4-0d54dcae415e.png)
- In round trips, the forage harvester makes a 180 ° U-turn, but sometimes, she is forced to back up and collides with the tractor which is waiting nearby.
- tractors do not stand on their side in the meadows. They are constantly late. I also tested with the "green moving" mod and mowed the grain. The problem is the same.
![image](https://user-images.githubusercontent.com/36656729/87245989-64716b00-c44a-11ea-953e-e7bcb267c593.png)
- when the tractor is full. He backs up, but very often he does not avoid the forage harvester and collides with it when he wants to reach the exit.
- great loss of FPS when the tractor searches for the way to reach the forage harvester in the field.
- tractors only follow the forage harvester if it works with courseplay. This is a problem when you want to finish an angle, or if you have to advance a few meters .. etc.
- if the engaged speed of the tractors is low (for example 20 km / h), they will drive constantly at this speed without taking account of the play parameters. (even if you have set to 50 km / h on the road) You must therefore set the speed to the maximum, before starting the racing game.
- In the bunker, if the unloading point is further than the silage heap, the tractors do not unload and get stuck in the silage heap.
- 2 symbols appear constantly when I use mode 2 and fill the bunkers.
![image 1_LI](https://user-images.githubusercontent.com/36656729/87246304-e498d000-c44c-11ea-98da-e822ffe71679.jpg)
![image 2_LI](https://user-images.githubusercontent.com/36656729/87246308-e793c080-c44c-11ea-9340-8d3b6773d0de.jpg)
![image 3_LI](https://user-images.githubusercontent.com/36656729/87246309-eb274780-c44c-11ea-9443-43a21702a5c0.jpg)
- problem with the HUD that I have had for a very long time. I already had this problem with version 6.01
![image 4_LI](https://user-images.githubusercontent.com/36656729/87246313-efebfb80-c44c-11ea-9741-3c7e42d0e542.jpg)
![image 5_LI](https://user-images.githubusercontent.com/36656729/87246318-f37f8280-c44c-11ea-8815-cf81d8918ea2.jpg)
![image 6_LI](https://user-images.githubusercontent.com/36656729/87246326-02fecb80-c44d-11ea-8c09-70bede07f8e4.jpg)

I think some of these problems have already been reported.

I am aware of the work to be planned, for this essential mod for FS19, but also worried, because I sometimes doubt that the Courseplay will one day be finished and 100% functional ...
Good luck and thank you!
[log.txt](https://github.com/Courseplay/courseplay/files/4908467/log.txt)

**Comment by Tensuko** [comment]
>     * some forage harvesters do not throw the silage far enough when the tractor is behind (including with the BIG X 1180) and the tractor follows too far. There is often too great a distance between the tractor and the forage harvester. Therefore, everything stops. It is therefore necessary to manually advance the tractor.

The BigX was tested a lot and should be able to throw far enough, as mentioned in #5272 

>     * In round trips, the forage harvester makes a 180 ° U-turn, but sometimes, she is forced to back up and collides with the tractor which is waiting nearby.

Might be a to tight turning angle. @pvaiko try to tweak the 'backing up to make space' for this situation ?

>     * tractors do not stand on their side in the meadows. They are constantly late. I also tested with the "green moving" mod and mowed the grain. The problem is the same.

No Idea what you talking about...

>     * when the tractor is full. He backs up, but very often he does not avoid the forage harvester and collides with it when he wants to reach the exit.

Avoid Fruit deactivated ? Screenshot of the Situation with channel 4 7 12 and 14 helps to understand whats going on.

>     * great loss of FPS when the tractor searches for the way to reach the forage harvester in the field.

We know about this, can't change much about that right now.

>     * tractors only follow the forage harvester if it works with courseplay. This is a problem when you want to finish an angle, or if you have to advance a few meters .. etc.

That is like it is for now, read #5272 we are not sure if we will change that, for not we have other things to do.

>     * if the engaged speed of the tractors is low (for example 20 km / h), they will drive constantly at this speed without taking account of the play parameters. (even if you have set to 50 km / h on the road) You must therefore set the speed to the maximum, before starting the racing game.

Set the max speed for Tractors before start it and it is fine. Thats a problem of Cruise Control set too low.

>     * In the bunker, if the unloading point is further than the silage heap, the tractors do not unload and get stuck in the silage heap.

Screenshot ? No Idea how is your course and the situation.

About the HUD:
we know this...

**Comment by rikilamaru** [comment]
they completely destroyed mode 2, mode use to work with player driving the forage harvester it literally better to go back to the old vers of courseplay

**Comment by Tensuko** [comment]
To many stuff in one Issue, most is also know or fixed already.
Reading https://github.com/Courseplay/courseplay/wiki also doesn't hurt.
Since got no Reaction, Closing.
