### ISSUE TITLE
MP dediServer erweiterte Einstellungen Speichern nicht

### ISSUE THREAD

**Issue by txmazing** [Courseplay/courseplay#5738]
Moin, wir spielen auf einem Server und mit der Courseplay Version ".00039.dev".

Das Problem:
Alle Einstellungen im "erweiterten Einstellungen" Fenster werden nicht übernommen und auch nicht gespeichert.
Es steht zwar dann die Änderung der Einstellung da, auch bei erneutem öffnen der Einstellungen doch es wird nicht ausgeführt. Sobald der Server dann neugestartet wird, sind die Einstellungen wieder rückgängig. Die einzige Möglichkeit die Einstellungen zu ändern ist die vehicles.xml zu bearbeiten. Diese Änderungen sind dann quasi die Standard und werden bei jedem Serverrestart übernommen.

**Comment by txmazing** [comment]
Bei was ich mir nicht sicher bin ob das "Kurs beginnen an" auch damit zusammen hängt. Ich habe nämlich festgestellt, dass es nicht juckt welchen Modus man einstellt er beginnt immer am nächstgelegenen.

**Comment by Fuzzy86** [comment]
Das ist uns auch aufgefallen. Was auch nicht funktioniert ist die übergabe an Autodrive z.B. beim Stroh einsammeln.

**Comment by Bandesss** [comment]
> Das ist uns auch aufgefallen. Was auch nicht funktioniert ist die übergabe an Autodrive z.B. beim Stroh einsammeln.

Ja mal geht's mal geht's nicht....

**Comment by schwiti6190** [comment]
Hi, Ich bin aktuell ein größere änderung vorzunehmen und es kann sein das dieses bei **meiner** nächsten version behoben wird, aber ich gebe keine garantie.
