### ISSUE TITLE
Multitool: Unloader waits until combine is 100% regardless of Start at % on first headland

### ISSUE THREAD

**Issue by gyerli** [Courseplay/courseplay#5739]
- Created a course with 2 headlands with multi-tool x 2
- I have two combines and two unloaders. Each combine assigned to one unloader.

@Tensuko said in [Mode 2 page](https://github.com/Courseplay/courseplay/issues/5272#issuecomment-657087251)
>We don't unload at given % on 1st Headland, Combine will make a Pocket for the Unloader to have enough space

Unloaders wait until combine is 100% regardless of Start at % or the number of headlands. Unloader heads the Start % only after combine completes **all the headlands** and starts the rows.

Also, @Tensuko's above statement is true when the course is NOT multi-tool course.
Uploaded the log. Great progress so far. Keep up the great work!
[log.txt](https://github.com/Courseplay/courseplay/files/4909282/log.txt)

**Comment by pvaiko** [comment]
@gyerli not sure I understand this. I think it may be a problem with the multitool but in a non-multitool setting, when the pipe is not in the fruit, the unloader should certainly start at the set % level.

**Comment by gyerli** [comment]
@pvaiko yes, the issue appears only when the course is multi-tool

**Comment by Tensuko** [comment]
Tested and it works with the set % level, keep in mind that you have the option to unload combine in 1st headland set to activated.
