### ISSUE TITLE
SCORPION 1033 dit not remember telescopic part settings in mode 9

### ISSUE THREAD

**Issue by WM3x** [Courseplay/courseplay#5741]
SCORPION 1033 dit not remember telescopic part settings in mode 9

**Comment by Tensuko** [comment]
Did you try the other Vehicles ?

**Comment by WM3x** [comment]
KRAMER KL30.8T  front loader is working corretly.

**Comment by Tensuko** [comment]
Ok so it is SCORPION Special.

**Comment by Tensuko** [comment]
Fixed with .00077
