### ISSUE TITLE
Baler misses a little grass, reverse on unload?

### ISSUE THREAD

**Issue by Dennizzzzz** [Courseplay/courseplay#5743]
A baler is skipping a little bit of grass when unloading. Is it possible to reverse before unloading?

![2020-07-14 11_22_20-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/87411924-b04a1e80-c5c8-11ea-9ef5-494360686535.jpg)

[log.txt](https://github.com/Courseplay/courseplay/files/4917944/log.txt)

Courseplay for FS19 v6.02.00040
Map: Stappenbach 2020

**Comment by Tensuko** [comment]
All balers or just this one ?

**Comment by WM3x** [comment]
> All balers or just this one ?

KUHN FBP 3135 same issue

**Comment by TheJimmyJob** [comment]
> All balers or just this one ?

Claas Rollant 455 also misses strips, often far longer than the little amount shown in the screenshot.
![2020-07-15 09_50_15-Farming Simulator 19](https://user-images.githubusercontent.com/65249616/87572592-a08e1100-c680-11ea-8aa7-27454923fbff.png)

**Comment by WM3x** [comment]
Next issue what I found regarding round balers is, if baler reach 100% when turning, it will miss long path, and unloads bale outside of the field.

**Comment by archaoncze** [comment]
Its simple all round balers. Miss bits is caused by time, that driver needs to stop from working speed to 0, that allow him unload. 
And i can confirm WM3x last comment, it can sometimes happen if baler get full in time, when CP driver starts turn manouver. It can cause aditional problem, if that maneuver consisst of some reversing - it can end with tractor stuck over bale, which have beed unloaded during maneuvering.

**Comment by ddewar** [comment]
@Tensuko, I'll take another look at these reports. Might be that change I made for Fastbale again. 🙄

**Comment by Tensuko** [comment]
@ddewar that could be the reason but I dont see a solution right now. Or we got to handle the fastbale on a very special way... Dont know...

**Comment by ddewar** [comment]
@Tensuko yeah, I was trying to find a specialization for the fast bale to use. But haven't had any luck finding anything.

**Comment by TheHaney** [comment]
As a workaround, have you tried limiting the speed on the tractor? Having it go slower would probably reduce the amount of grass it skips.

**Comment by ddewar** [comment]
Is everyone having this issue on different maps? I can't seem to get this to happen on base game maps with my testing setup.

**Comment by ddewar** [comment]
Ahhhh, I think I may have figured out what's going on here. Everyone missing sections while unloading, are you using Vehicle Control Addon? It looks like the braking force is lowered so we don't stop in time. We might be able to avoid this by slowing down earlier, but this would have a small adverse effect of losing a few seconds for those not using VCA.

**Comment by archaoncze** [comment]
I dont use VCA, but baler is behind old tractor, that may have lower braking power. If i reduce speed on field at 10 kph, its ok (for work on flat ground, downhill (pretty steep hill) still miss few bits). And i think, that its normal, that even CP that starts brake as soon as baler is full, it cant stop from 20 kph to 0 instantly.  But i defintly never have so big missed pieces as JimmyJob on his screenshot.

**Comment by ddewar** [comment]
> I dont use VCA, but baler is behind old tractor, that may have lower braking power. If i reduce speed on field at 10 kph, its ok (for work on flat ground, downhill (pretty steep hill) still miss few bits). And i think, that its normal, that even CP that starts brake as soon as baler is full, it cant stop from 20 kph to 0 instantly. But i defintly never have so big missed pieces as JimmyJob on his screenshot.

At 90% full the baler should try to go the the courseplay turn speed. Make sure your turn speed is turned down, it might help.

**Comment by archaoncze** [comment]
ok, i will try it for next harvest. 10kph for turn is still ok for me - definetly better than do whole field at this speed.

**Comment by Dennizzzzz** [comment]
Ah, i did speed up my turning speed, so next time will turn the turn speed down to see if this works.

**Comment by Dennizzzzz** [comment]
Whahooo. Just tested the baler with turnspeed 10 (i had it on 20) and the baler slows down at 90% full, and now it does it's job perfectly.

**Comment by ddewar** [comment]
@archaoncze Are you using a basegame tractor? I am finishing up some fixes for it and would like to check off a few different situations. If not, is there somewhere I can find the tractor?

**Comment by archaoncze** [comment]
I am using mod - old Zetor from "Zetor 12045-16145 Pack" which is available on modhub. I change only engine setup for highest horsepower output.

**Comment by ddewar** [comment]
FYI @TheJimmyJob when testing I noticed the baler using VCA does not miss spots when you are not in the cab. Avoid sitting in the tractor and it should miss less!

**Comment by Tensuko** [comment]
Did use the claas baler for another test.
Had no problem at all.

**Comment by Tensuko** [comment]
I take this one as solved for now and close.
