### ISSUE TITLE
the truck stops and does not go under load

### ISSUE THREAD

**Issue by ontot** [Courseplay/courseplay#5744]
why does the truck always stop before going under load? ... the log shows this message: "There is fruit at the target, disabling fruit avoidance". it stops and never starts again

![image](https://user-images.githubusercontent.com/26443217/87425188-79cace80-c5dd-11ea-8fd1-18de40a54b90.png)
![image](https://user-images.githubusercontent.com/26443217/87425848-a16e6680-c5de-11ea-9311-734035d4a680.png)

**Comment by ontot** [comment]
this is the log file
[log.txt](https://github.com/Courseplay/courseplay/files/4918817/log.txt)

**Comment by Tensuko** [comment]
Why you turned off Fruit Avoidence on your Combine ?
Also you didn't turn on the needed debugchannels discribed in #5272

**Comment by ontot** [comment]
OMG! ... I took it off because I wanted it to turn comfortably off the pitch, considering that I have a lot of space. I didn't think it was mandatory to have it inserted. anyway now i put it back and it works well. thank you Tensuko ... thank you very much indeed. you can close this thread. :+1:  thank you again...

**Comment by Tensuko** [comment]
Well, then it was an easy fix :)
Happy Farming.
