### ISSUE TITLE
Falsche Werte bei Feldcourse erstellung

### ISSUE THREAD

**Issue by Baker79** [Courseplay/courseplay#5746]
Hallo folgendes Problem

Ich erstelle ein Kurs, Feldarbeit, Feld x Arbeitsbreite x Kurs wird erledigt.
dann habe ich aber immer egal was für ein Feld oder welche Arbeitsbreite ein Gerät Versatz seitlich von 2,4m ohne das ich diese eingestellt habe. dieser scheint schon vorher da zu sein. Dieser Fehler ist mir bisher nur beim einsatz von einem Frontmähwerk aufgefallen.
Desweiteren habe ich immer eine voreinstellung von 7% Überlappung Vorgewende. Dieser Wert ist immer voreingestellt. Ist das so richtig ???

**Comment by Tensuko** [comment]
Der Wert von 7% ist immer so das ist richtig.
Das war auch vorher schon so, nur war es für niemanden Sichtbar.
Jetzt kann man ihn eben selber einstellen.

Seitlicher Versatz ja dann mach ihn doch weg ?
Der Versatz hat nichts mit Kurserstellung zu tun, sondern mit dem Gerät.

**Comment by Baker79** [comment]
ok. leider vergisst man das immer. und dann fängt er an zu arbeiten bleibt am zaun hängen und man weis erstmal nicht warum. oder drescher lassen dann naturlich immer ein stück stehen. das gilt auch für andere arbeiten. 
ich dachte wenn man ein course erstellt nimmt cp automatisch an das das gerät mittig angekoppelt ist und somit der course auch ohne geräte versatz erstellt wird.

**Comment by Tensuko** [comment]
Der Kurs wird auch ohne Geräteversatz erstellt.
Es wird einer im HUD eingestellt, wenn die WorkArea vom Gerätz ein Versatz hat.

**Comment by Baker79** [comment]
aha ok dann is alles klar 

ich Danke für die schnelle erläuterung.
mfg
