### ISSUE TITLE
Coruseplay hud öffnet nicht

### ISSUE THREAD

**Issue by Pipel19** [Courseplay/courseplay#5747]
Hallo,
ich nutze die aktuelle Version von Courseplay (auch mit einer davor  getestet). Im Spiel öffnet sich bei Betätigung der rechten Maustaste der hud nicht. Das Maussymbol erscheint aber mehr leider nicht. 
Ich habe auch bereits einmal die inputBinding gelöscht( Hab ich hier schonmal gelesen) aber ohne erfolg. Ich hab mal ein Logifle angehangen in der Hoffnung das ihr mir helfen könnt. Danke
Gruß
Philipp
[log.txt](https://github.com/Courseplay/courseplay/files/4920013/log.txt)

**Comment by Tensuko** [comment]
Spontan würde ich sagen den hier rauswerfen:
(Version: 0.51 Beta) AAA_HiredHelperTool

Aktualisieren:
(Version: 1.4.0.0) FS19_GlobalCompany

Und nur mal so die Frage:
In einem Fahrzeug warst du aber schon drin oder ?

**Comment by Pipel19** [comment]
Hab den mod rausgewurfen und auch GlobalComany geupdated. 
Und ja sitze in einem Fahrzeug, hab mehrere ausprobiert. Ohne Erfolg.
[log.txt](https://github.com/Courseplay/courseplay/files/4920311/log.txt)

**Comment by Tensuko** [comment]
Schau mal welche Taste bei HUD öffnen in der Tastenbelegung ist und versuche es damit, normal sollte es entf sein.

**Comment by Pipel19** [comment]
hab geschaut, ist entf. auch damit passiert das gleiche wie mit der Maustaste.  
Der Mauszeiger erscheint, mehr aber nicht. Bin langsam ratlos....

**Comment by Tensuko** [comment]
Mal bitte nur CP im Mods Ordner und neues game starten und probieren. Es muss gehen. Warum in deinem savegame nicht keine Ahnung...

**Comment by Pipel19** [comment]
neues Spiel funktioniert.... werde dann morgen mal alle Mods durchgehen und gucken bei welchem Mod das auftritt...

**Comment by Pipel19** [comment]
zur Info, habe die "courseplaySettings.xml"  durch eine von einem neuen Spiel ersetzt. Jetzt geht es wieder.
