### ISSUE TITLE
Gras / Heutrigger

### ISSUE THREAD

**Issue by Chris300876** [Courseplay/courseplay#5748]
Hallo,

Erstmal grosses Lob und Vielen Dank fuer die geopferte Freizeit. Ohne CP waere der FS nicht so spielbar wie wir ihn jetzt kennen.

Mein Problem: In bestimmten Konstellationen wird der Gras/Heutrigger nicht erkannt.
Ich habe also einen Feldkurs und einen Abfahrerkurs; Feldarbeitsmodus.
Wenn das Problem auftritt, passiert folgendes:
- Der Abfahrer verlaesst das Feld und folgt dem Abfahrkurs.
- Der Trigger wird nicht erkannt (Kein Text " Abladestelle erreicht", Trigger wird ueberfahren ohne abladen)
- Der Abfahrer faehrt zurueck zum Feld unbeginnt wieder mit dem ERSTEN Wegpunkt.
- Auch wenn ich haendisch ablade und den Abfahrer auf dem Abfahrkurs wieder einstelle, faehrt er wieder zum ersten Wegpunkt, nicht zum aktuellen.
- Wenn ich einen Haltepunkt am Trigger setze, um haendisch abladen zu koennen, wird dieser ueberfahren.

Wann tritt das auf?
1. Versuch: Vanilla, neuer Spielstand, keine Mods ausser CP, neuer Spielstand Felsbrunn: Trigger erkannt, abladen funktioniert, es geht am aktuellen Wegpunkt weiter mit aufladen. Alles gut.
2. Versuch: meine Standard Mods wieder im Modordner und aktiviert, aber nur Vanilla Fahrzeuge im Einsatz: Funktioniert immer noch wie gewuenscht.
4. Versuch: (Das ist die unten angehaengte log.txt) Nur CP und ein Mod traktor im Mod Ordner; Mod Traktor (Unimog) gekauft, Kurs vom anderen Traktor kopiert: Fehler tritt auf wie oben beschrieben. Dann wieder auf den Vanilla Traktor gewechselt: Fehler tritt immer noch auf.
Erst wenn man den mod Traktor wieder verkauft und den Spielstand neu startet, Funktioniert es wieder mit dem Standard-Traktor.

Ich glaube nicht, dass es an dem speziellen Mod liegt, weil ich schon verschiedentlich Probleme mit dem Abladen von Heu hatte.
Das habe ich nicht in der Tiefe getestet, aber ich bin mir fast sicher, dass es reicht, (bestimmte oder ueberhaupt) Mods im Spiel gekauft zu haben, damit der Trigger nicht mehr erkannt wird.

[log.txt](https://github.com/Courseplay/courseplay/files/4924089/log.txt)

**Comment by Chris300876** [comment]
Ach ja: Die Kurse habe ich nicht angehaengt, weil es ja mit dem Vanilla Traktor funktioniert und mit dem Mod nicht. Kann also nicht am Kurs liegen.
Ich kann das aber gerne nachholen.

**Comment by Tensuko** [comment]
Du meinst also es liegt am (Version: 1.1.0.0) FBM19_UnimogU1X00 ? Wie ist der denn konfiguriert ?
Sind das alle Mods die du hast, die im logfile zu sehen sind ?

**Comment by Chris300876** [comment]
Genau, dieser hier:
https://forbidden-mods.de/filebase/file/14847-fbm-team-unimog-u1200-u1400-u1600/#overview

In dem Versuch waren das alle Mods, ja. Den Rest hab ich rausgenommen.

Im 2. Versuch hatte ich noch followMe, extended driving, einen platzierbaren Verkaufstrigger (dachte erst dass der Probleme macht) und einige Fahrezeuge drin und aktiviert, aber nicht im Spiel gekauft. Das hat wie gesagt keine Probleme gemacht.

Wie gesagt, ich glaube nicht, dass es an dem Unimog direkt liegt, da ich auch schon sonst Probleme beim Heuverkauf hatte. Aber das war auf Modmaps, so dass sich verschiedene potentielle Ursachen ueberlagern.

**Comment by Chris300876** [comment]
Also ich habe noch ein bisschen rumprobiert.

1. Es betrifft nicht alle Mods, aber mehr als nur den einen. 
Z.B. ist dieser betroffen:
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=130799&title=fs2019
Dieser nicht:
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=133162&title=fs2019
Da beide betroffenen Mods LKW sind, habe ich mal alle XML Eintraege, wo es mir sinnvoll erschienen von "truck" in "tractor" geaendert - ohne Erfolg.
<vehicle type="tractor">
<typeDesc>$l10n_typeDesc_tractor</typeDesc>

2. Wann genau tritt es reproduzierbar auf?
Wenn einer der betroffenen Mods aktiviert und im Spiel in der aktuellen Session gekauft ist, passiert noch nichts. Alles ist wie es sein soll.
Sobald man den betroffenen Mod mit CP zum Heu abfahren schickt, passiert genau das was ich im ersten Post beschrieben habe (alle 4 Phaenomene). Danach funktionieren auch die Vanilla Traktoren nicht mehr.
Laedt man einen gespeicherten Spielstand in dem einer der betroffenen Traktoren gekauft ist, funktionieren ebenfalls weder mod noch Vanilla Traktoren.

Ich hoffe, das hilft etwas weiter.
Bei allen Tests war nur CP und jeweils ein Traktor / LKW mod im Mod Ordner, sonst nichts.

**Comment by schwiti6190** [comment]
@Chris300876  Could you try this with the newest version ?

**Comment by Chris300876** [comment]
Sorry, with .00049 it is still the same.

**Comment by Tensuko** [comment]
.00053 still the same ?

**Comment by Chris300876** [comment]
Can only test tomorrow evening.

**Comment by Chris300876** [comment]
It's partially better with 00053.

- Mod truck unloads, but the caption "Abladestelle erreicht" is missing (I don't know the english caption as I'm playing the german version)
- If I change back to the Vanilla tractor (mod truck still in the game), it does not unload, but stops at the waiting point that I placed after the trigger ( it also ignored the waiting point in older versions).

**Comment by Tensuko** [comment]
Könnte erledigt sein, wenn nicht, bitte wieder aufmachen.
