### ISSUE TITLE
Abfahrer finden Drescher nicht und Tanken nicht ab

### ISSUE THREAD

**Issue by StulleJr** [Courseplay/courseplay#5749]
Hab seit dem letzetn update Probleme mit den Abfahrern.
Sie finden den Drescher nicht mehr automatisch und müssen zugewiesen werden, zu dem fahren sie dann nicht abtanken und wenn man Sie auf dem Feld einstellt fängt mein Spiel an zu laggen.
Die Logs sind aber auf Fehler frei
Hab dieses Problem seit der V6.02.00039

**Comment by Tensuko** [comment]
Wow.... wer lesen kann #5272
