### ISSUE TITLE
Grain Transport setting not working with integrated storage vehicles

### ISSUE THREAD

**Issue by TheHaney** [Courseplay/courseplay#5752]
Modded vehicles with integrated storage (such as mining equipment), where the storage area is part of the vehicle rather than an attached implement, will not recognize any materials to be loaded. The materials option shows as <unknown> and trying to move it makes it vanish entirely.

Is there a workaround for this or does the grain transport mode only recognize trailers?

**Comment by Tensuko** [comment]
we are working on it...
