### ISSUE TITLE
Course Play Not Working with MAN TGS 18.500 Bale Transport AutoLoad

### ISSUE THREAD

**Issue by dreadoc20** [Courseplay/courseplay#5753]
Can record a course with this vehicle but nothing happens when i try drive a course. Am i missing something?

**Comment by Tensuko** [comment]
You are missing a logfile attached here :)

**Comment by dreadoc20** [comment]
sorry new at this. must i attach something? if so how do i do it

**Comment by dreadoc20** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4941736/log.txt)

**Comment by Tensuko** [comment]
What mode do you try to use it ?

**Comment by dreadoc20** [comment]
just the simple drive to point mode. I think it may be the fact that the truck does not have a fuel gauge

**Comment by Tensuko** [comment]
That could be a problem yes.
What Truck is it ? ModHub one ?

**Comment by dreadoc20** [comment]
Its the MAN TGS 18.500 Round Bale Autoload

**Comment by dreadoc20** [comment]
https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=153084&title=fs2019

**Comment by Tensuko** [comment]
That is an Mod Issue. The Vehicle got no fuel tank. As you can see on the right side of the Ingame GUI.
