### ISSUE TITLE
Holmer als ÜLW funktioniert nicht.

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#5754]
Hallo Leute, versuche mit einem HOLMER Terra Variant 585 und dem Grain tank GB 25 einen Agco ideal abzutanken.
Der cp kurs ist erstellt, mit Start-, Halte- und Endpunkt,
Wenn ich den Holmer abfahrer einstelle, fährt CP den Kurs bis zum letzten Punkt, dann macht der Holmer einen kleinen "Hüpfer" nach vorne und der abfahrer entlässt sich selber.
Wenn ich ihn wieder einstelle, genauso, er fährt den Kurs ab bis zum letzten Punkt und entlässt sich wieder selber.
Gibts da bekannte Probleme?
Lg
Andreas

**Comment by Tensuko** [comment]
logfile ?

**Comment by John-Deere89** [comment]
Ist bei mir auch so auch mit einen normalen ÜLW  mir wurde gesagt das dass momentan noch nicht untersütz wird daher denke ich wird es bei dir nicht gehen ;)

**Comment by andreasthu** [comment]
Na ok, der Fehler lag auf meiner Seite, ich hatte bei der überladestelle einen Wartepunkt gesetzt.
Ich habe nun anstelle des Wartepunktes einen Abladepunkt genommen, nun funktioniert das ganze perfekt.
@John-Deere89 
Wie gesagt, der Holmer funktioniert nun, ebenso der Elmers Haulmaster mit einem Claas xerion.
Btw, das Überladerohr musst du vorher selber ausfahren und die Position einstellen, CP macht das nicht, es bleibt also die ganze Zeit aufgeklappt.

Lg
Andreas
