### ISSUE TITLE
Problem beim einschalten von CP

### ISSUE THREAD

**Issue by Tobias80** [Courseplay/courseplay#5757]
Hi -hab ein Problem beim einschalten von CP bzw. wenn ich den Helfer starten lassen will

[log.txt](https://github.com/Courseplay/courseplay/files/4943495/log.txt)
![fsScreen_2020_07_19_11_23_36](https://user-images.githubusercontent.com/68498185/87871805-e6661480-c9b3-11ea-9722-6f49e8d65876.png)

**Comment by Tensuko** [comment]
Keine Ahnung, schätze ein Modconflict.
An der Map wird es auf jedenfall nicht liegen weil ich die auch spiele.

Möglich könnte sein:
(Version: 1.0) fs19_AutoAttach
(Version: 1.0.0.0) FS19_AutomaticUnloadForBaleWrapper

Hier bin ich mir nicht sicher:
(Version: 1.0.0.0) FS19_fillTypeMassAdjustmentRealistic

Die Benennung ist verdächtig...
Offizielle Quelle zum runterladen ist NUR hier:
https://github.com/Courseplay/courseplay/releases/tag/6.02.00040

**Comment by Tobias80** [comment]
Ok Probier ich mal aus - meld mich dann wieder 
Du CP Version hab ich von hier - hab auch mal ne ältere Version getestet ohne Erfolg

**Comment by Tobias80** [comment]
Ok hab’s herausgefunden - war das Heizwerk vom strohbergungs Add On

**Comment by Tensuko** [comment]
Ach hattest du noch die alte version ? Einfach neu runterladen auf der richtigen easteregg aeite dann geht es :)

**Comment by Tobias80** [comment]
Oh ok Das wusste ich gar net - trotzdem danke !

**Comment by Mario-AUT** [comment]
Hallo,

ich habe das Problem, dass sich CP im Game nicht bedienen lässt. Habe die CP Version 6.02...40 und die aktuellste Version vom LS19. Hängt das vielleicht mit einem Mod zusammen? Hab die Log Datei mal angefügt. Danke schon mal für die Hilfe! 
[log.txt](https://github.com/Courseplay/courseplay/files/4959908/log.txt)

**Comment by Tensuko** [comment]
Also als erstes bitte mal damit aufhören:
(Version: 6.02.00040) zzz_courseplay6
Das ist halt absoluter Käse mit dem zzz_
https://github.com/Courseplay/courseplay/releases/
hier die .zip Datei laden, in den Mods Ordner und fertig.

Es kann zu Problemen kommen wenn das Fahrzeug IC Steuerung hat.
Was wir absolut unterstützen ist simpleIC, eine einfache und geniala IC Lösung.

Ansonsten kann ich beim überfliegen der log nichts entdecken was auf so ein Problem hinweist.

**Comment by Mario-AUT** [comment]
Hat geklappt! Vielen dank für deine Mühe!
