### ISSUE TITLE
Error: Running LUA method 'loadSharedI3DFileFinished' - toolManager.lua:193: attempt to compare number with nil

### ISSUE THREAD

**Issue by SPLESHER1** [Courseplay/courseplay#5758]
[log.txt](https://github.com/Courseplay/courseplay/files/4943503/log.txt)
Hi!, i noticed today that this mod https://kutt.it/JD9000ITS is not loading in shop with courseplay mod enabled, it just loads forever, log doesnt say anything about errors with courseplay or smth, could you please look on this?

**Comment by Tensuko** [comment]
This is a Modissue we can't do much about it.
You can try to contact the Modder to fix it.
