### ISSUE TITLE
Frage an andere Mp user: Verbindung zum Spiel verloren 

### ISSUE THREAD

**Issue by Bandesss** [Courseplay/courseplay#5759]
Hallo zusammen, 
wir nutzen auf CP auf einem Rootserver.
Nun ist uns aufgefallen das wenn CP im Mods Ordner ist und aktiviert .
Wir immer wieder Verbindung zum Spiel Verloren bekommen
Kann das jemand bestätigen´? es kommt nach lust und laune .
Ohne CP keine Verbindungsabbrüche mehr.

Gruß

**Comment by Tensuko** [comment]
Und bringt keine Logfiles mit, weder vom Server noch vom Client...

Wenns ein eigener Rootserver ist mit eigener Software oder was auch immer kann es sosnt was sein.

**Comment by Bandesss** [comment]
Keine Ahnung in der LOG steht nichts... in keiner
Wir haben nen Root mit eigener Lizenz für ls 19 
Heute Morgen CP raus und seit dem Online.
Wenn wir 4 Leute auf dem Server waren, haben alle zu den unterschiedlichsten Zeiten dieses bekommen
Verbindung zum Spiel verloren. Server war immer Online, man bekommt den kick und kann gleich wieder connechten
Hab das Thema nur erstellt, zum sehen ob das mehrere User haben ?
