### ISSUE TITLE
Mode 2 pathfinder stuck

### ISSUE THREAD

**Issue by Veraseca** [Courseplay/courseplay#5761]
Hello,

My combine was full but the unloader didn't start moving to unload the combine in Mode 2
Screenshot in attach

![Screenshot (3)](https://user-images.githubusercontent.com/57765427/87885168-20670300-ca14-11ea-9ea2-5dde1fa19d1c.png)

**Comment by Tensuko** [comment]
#5272

**Comment by Veraseca** [comment]
logfile in attach
[log - Copy.txt](https://github.com/Courseplay/courseplay/files/4944688/log.-.Copy.txt)

**Comment by Veraseca** [comment]
Same situation over here

![Screenshot (4)](https://user-images.githubusercontent.com/57765427/87885340-6a9cb400-ca15-11ea-9122-f487921b1978.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4944693/log.txt)

**Comment by pvaiko** [comment]
https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ

Do you have a savegame and courses of this situation?

**Comment by Veraseca** [comment]
Hello, 
Savegame in attach. Courses were generated temporary. Way i did it, generate course on field 20, 2 headlands with starting position in south-west. For the unloader just a unload course to nearby silo.
[savegame4.zip](https://github.com/Courseplay/courseplay/files/4949400/savegame4.zip)

**Comment by pvaiko** [comment]
thanks. Can't use the savegame as you are using a mod combine. Do you have a link to a clean source for that mod? And the header if needed?

**Comment by Veraseca** [comment]
http://www.farmingsimulator19mods.com/claas-lexion-700-series-usa-edition-v1-0-fs19-2/

**Comment by pvaiko** [comment]
Thanks. This is a mod problem, the size of the combine is way too big, as you can see on this screenshot, the blue rectangle:
![image](https://user-images.githubusercontent.com/2379521/88001544-04239e80-cac6-11ea-9471-4fab0cc5c289.png)
You can see that in the XML too:
```xml
 <size width="4" length="18"/>
```
Obviously, 18 m seems a bit too long for this combine.

**Comment by Veraseca** [comment]
@pvaiko with the Ideal combine (standard combine in the game, i had the same issue

![Screenshot (9)](https://user-images.githubusercontent.com/57765427/88072038-dd707100-cb74-11ea-9873-d30594064d44.png)


[log - Copy (2).txt](https://github.com/Courseplay/courseplay/files/4954344/log.-.Copy.2.txt)

**Comment by Tensuko** [comment]
Different Issue

**Comment by pvaiko** [comment]
Why do you have a manual side offset?
