### ISSUE TITLE
Mode 10 driver does not go till end of bunker

### ISSUE THREAD

**Issue by Veraseca** [Courseplay/courseplay#5762]
Hello,

I tried out Mode 10 of CP and with mode 10. I expected the tractor with the leveler to go till the end of the bunker to fill the bunker with chaff. But the tractor stops after a few meters in (see screenshot)
[log.txt](https://github.com/Courseplay/courseplay/files/4944703/log.txt)
![Screenshot (5)](https://user-images.githubusercontent.com/57765427/87885489-c582db00-ca16-11ea-8a28-766bec5c0dd2.png)

**Comment by Tensuko** [comment]
Change from leveling and compacting to fill up.

**Comment by Veraseca** [comment]
That worked indead, sorry for the inconvenience.

I noticed during the filling that my tractor ran into the walls and got stuck.

![Screenshot (8)](https://user-images.githubusercontent.com/57765427/87886383-b9018100-ca1c-11ea-9852-a78a4b809269.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4944749/log.txt)

**Comment by Veraseca** [comment]
Also my tractor is occasionally stuck in the silage. How can i solve that?

[log.txt](https://github.com/Courseplay/courseplay/files/4954626/log.txt)
![Screenshot (10)](https://user-images.githubusercontent.com/57765427/88076616-984f3d80-cb7a-11ea-9b29-ecd2a6e44cd4.png)

**Comment by Tensuko** [comment]
> 
> 
> @Tensuko Also my tractor is occasionally stuck in the silage. How can i solve that?
> 
> [log.txt](https://github.com/Courseplay/courseplay/files/4954626/log.txt)
> ![Screenshot (10)](https://user-images.githubusercontent.com/57765427/88076616-984f3d80-cb7a-11ea-9b29-ecd2a6e44cd4.png)

Ask GIANTS for a better system and not make the chaff have hard corners to stuck :)

**Comment by Tensuko** [comment]
I know it is not rly solved, but can't do much about the GIANTS Physics.
For the Wallstucking, you might increase the blade width by 0.1 or 0.2, that might help.
Problem might come, if chaff is on the side infront of the Bunker Walls.
