### ISSUE TITLE
Mode 2 Collision during driving to unload course 

### ISSUE THREAD

**Issue by Veraseca** [Courseplay/courseplay#5763]
Hi,

During the cutting of chaff my trailer was filled perfectly and nicely. When the trailer was full the truck tried to go to the unloading route. I expected to turn it further away from the tractor. Instead the path was calculated to close and it hit the chopper.

![Screenshot (6)](https://user-images.githubusercontent.com/57765427/87885740-fa436200-ca17-11ea-8bdb-8edcf47c63e2.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4944711/log.txt)

**Comment by Veraseca** [comment]
Also when the truck has to drive behind the harvester, the distance is too big between the truck and harvester. The unloading process cannot continue

[log.txt](https://github.com/Courseplay/courseplay/files/4944742/log.txt)
![Screenshot (7)](https://user-images.githubusercontent.com/57765427/87886283-ffa2ab80-ca1b-11ea-8d5b-bc68ee510b7f.png)

**Comment by Tensuko** [comment]
1st Situation is Problem of Pathfinder not calculating with the Trailer
2nd Situation is Problem of the JD Harvester, having the ProximitySensor not at the right Position and can't throw far enough.
We suggest the BigX or this one https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=126256&title=fs2019

**Comment by Veraseca** [comment]
@Tensuko for the 1st problem - will there be a fix for the trailer or is there no support for the trailer?
for the 2nd problem - same question, do i have to switch harvester or will there be support for the JD?

Thanks in advance

**Comment by Tensuko** [comment]
For the 1st one, well, we want to support trailer for pathfinder, but that is a bit complicated and might make the pathfinder slower. But we sure looking for a solution.

For the 2nd one, that is actually a Mod Issue, but the Plan is to get other Choppers working too, but need to find a good way.

That all takes time and there is much other stuff to do, so all I can suggest you is, take another Chopper (BigX for example) and a shorter Trailer.

**Comment by Tensuko** [comment]
2nd Problem for Choppers should be fixed in actual Version.
The 1st Problem is Pathfinder tweaking when drive to unload course.

**Comment by Tensuko** [comment]
1st Problem is #5983
