### ISSUE TITLE
CP and Straw Harvest Addon generate an error.

### ISSUE THREAD

**Issue by MuuRuuk** [Courseplay/courseplay#5764]
Hi.
I found this error while using straw harvest addon and CP at the same time. Im attaching photo and log file. (im using newest version of CP v6.02.00040)
*EDIT* It makes that error with every single tools i have attached.
[log.txt](https://github.com/Courseplay/courseplay/files/4944726/log.txt)
![Farming Simulator 19 Screenshot 2020 07 19 - 23 28 52 44](https://user-images.githubusercontent.com/65256510/87885896-20b5cd00-ca19-11ea-8841-7fb961287a9e.png)

**Comment by Tensuko** [comment]
Do you by any chanze think, that only one GEO condition can be used and is enough?
Available mod: (Hash: 6bf585192c105b5da161af094837a5c8) (Version: 1.0.0.0) FS19_Geo_Belgium
Available mod: (Hash: dc940ede1d8086984d1d75899c83fa20) (Version: 1.0.0.0) FS19_Geo_Central_Poland
Available mod: (Hash: 1826350e4970fb1a250df0a76059683b) (Version: 1.0.0.0) FS19_Geo_Germany
Available mod: (Hash: d0c1aa880dc8ec39e455d2b884b7da40) (Version: 1.0.0.0) FS19_Geo_ischiaFarm
Available mod: (Hash: 21854fe221d395dadd06e63704d4d709) (Version: 1.2.0.0) FS19_Geo_Upper_Austria
Available mod: (Hash: adcc62c6ebe8f9d1bf54f17b02768fa5) (Version: 1.0.0.0) FS19_GEO_Virginia

Also I wonder what this is:
Available mod: (Hash: 0b41b6db3f593dded8a2cb98d9a280b2) (Version: 1.0) FS19_HarvestoreSystem
Available mod: (Hash: 31e9928c9c9e98da1d5a346d043a8b42) (Version: 1.0) FS19_HarvestoreSystem_2
Available mod: (Hash: 060536ebb755671cb5a5bbe21b447a63) (Version: 1.1) FS19_HarvestoreSystem_multifruit

There is also only one Map allowed in mods Folder. (general Rule)

Anyway, will check on that, but you should clean up your mods a bit...

**Comment by MuuRuuk** [comment]
I have not activated the season mod so these are not available in map a played. And the harvestoreSystem is not activated in that map. They are only available to load if you want to activate them. All mods you highlighted to me are deactivated in that map.

**Comment by MuuRuuk** [comment]
Its deactivated as you can see. 
![Farming Simulator 19 Screenshot 2020 07 20 - 22 01 03 37](https://user-images.githubusercontent.com/65256510/87980917-a6e31980-cad4-11ea-9fc6-c364824dd8b0.png)
![Farming Simulator 19 Screenshot 2020 07 20 - 22 01 45 67](https://user-images.githubusercontent.com/65256510/87980920-a8acdd00-cad4-11ea-8c25-875f3aab06af.png)

**Comment by MuuRuuk** [comment]
I only use them for different maps i play.

**Comment by Bandesss** [comment]
Nur deaktivieren reicht nicht,sie müssen aus dem Ordner gelöscht werden

**Comment by Tensuko** [comment]
Can't reproduce and not a CP Error.
