### ISSUE TITLE
Merging courses together

### ISSUE THREAD

**Issue by 419054** [Courseplay/courseplay#5765]
This may sound noobish, but it drives me crazy and i didnt figuered out how it works. I want transfer course merged with field work. Drive from farm to edge of field, perform work, return back to farm. I ve seen this https://github.com/Courseplay/courseplay/issues/1772 but as it sound easy i didnt manage it to work. Is it even possible with fs19? Field work and refill with transfer course works fine, shouldnt it work other way around? I hope i was clear enough

**Comment by Tensuko** [comment]
No, doesn't work.
For that to work you need AutoDrive, then you can send a Driver to work and back to a parking position after work.
