### ISSUE TITLE
courseplay unload combine

### ISSUE THREAD

**Issue by deadlygamer19** [Courseplay/courseplay#5766]
i have got a issue with courseplay when i have a combine that needs to be unloaded courseplay does not detect it. but if it does detect it, it just drives to the combine and unload a little bit , but when the combine drives the tractor with the trailer stops. this happens with ingame equipment when i have no mods only courseplay and it also happens with mods

**Comment by Tensuko** [comment]
read #5272 and https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ

**Comment by deadlygamer19** [comment]
that maybe helps me understand some things but with what i have read my isseu is not coming up. the tractor with just a trailer does not drive towards the combine even if the combine is 100% full. but when it does it drives to the combine the combine opens the auger and dumps drives whilst dumping and the tractor sits does not do anything. you could imply that the combine needs to be stopped at unloading but the thing also happins when the tractor finds the combine at 60% drives towards it and when the combine unloads whilst driving the tractor just stops and does not do anything again and when i tell the tractor to drive first waypoint it drives it and then goes back to point zero. not driving towards the combine

**Comment by Lustiger-Hubi** [comment]
@Tensuko Tensuko ich weiß ja nicht wie alt dieses Issue ist aber mit v6.02.00045 läuft es prima!
Ich habe ein ganzes Feld3 auf der LS19_Yogiland_OY abgeerntet ohne Probleme!
Ich hoffe es bleibt so.
Danke für alles.

**Comment by Tensuko** [comment]
Na das hört sich doch super an!

**Comment by Lustiger-Hubi** [comment]
Tensuko kann ich dir auf diesem Weg mal eine Frage stellen?
Gibt es irgendwo eine Beschreibung für die Einstellung der erweiterten Funktionen? 
oder Tastenkürzel z.B. Strg -  Num0 Kursbearbeitung? Editor?
Hattest du mir mal gesagt, aber wie geht das mit dem Editor dann?

**Comment by Tensuko** [comment]
![fsScreen_2020_08_03_13_02_35](https://user-images.githubusercontent.com/27344744/89176352-a729ed00-d589-11ea-8787-f8a9e5264894.png)
Normale Tastenbelegung, alles frei konfigurierbar, Standarttasten sind nur eine Empfehlung.

**Comment by Lustiger-Hubi** [comment]
Danke dir! 
Soll ich jetzt meine Fragen löschen?

**Comment by Tensuko** [comment]
Lass ruhig stehen eventuell stoplert jemand drüber und dann lernt er auch etwas dazu.

**Comment by Tensuko** [comment]
Closing as there have some improovements made and things start to getting messy.
