### ISSUE TITLE
Modus 2 Ernter entladen

### ISSUE THREAD

**Issue by Cyruss01** [Courseplay/courseplay#5767]
Abfahrer fährt nicht los obwohl Füllstand des Ernters bereits erreicht ist - Abfahrer fährt wenn Ernter 100% Füllstand erreicht hat los aber bleibt vor dem Ernter stehen und fährt nicht mehr weiter. Abfahrer ist zugewiesen- Fruchtumfahrung ist deaktiviert.

![Screenshot (1)](https://user-images.githubusercontent.com/68546888/87939690-b8a6cb80-ca98-11ea-924a-443283b361a5.png)
[log.txt](https://github.com/Courseplay/courseplay/files/4947780/log.txt)

**Comment by Tensuko** [comment]
Und wieder sieht man nicht wo wir denn auf dem Feld sind....

Zur log:
mehrere Maps im Mods Folder, das sollte man nicht run.
Warum dieses ? (Version: 6.02.00040) zzz_courseplay
-> https://github.com/Courseplay/courseplay/releases/tag/6.02.00040 .zip Datei rein und fertig...

Auch mal hier #5272 und hier lesen https://github.com/Courseplay/courseplay/wiki/Mode-2-FAQ

**Comment by Cyruss01** [comment]
Naja, würde sagen dass wir mittig im Feld sind... und dass das Rohr auch nicht in der Frucht ist sieht man ja im Ausschnitt.
Habe aber mittlerweile herausgefunden, dass es wenn man beim Ernter Fruchtumfahrung aktiviert - es geht, aber wenn Rohr auf der Fruchseite nur wenn Füllstand 100% und mit Rückwärtsmanöver des Ernters- nicht während der fahrt mit Fruchumfahrung deaktiviert.

**Comment by Tensuko** [comment]
Drescher würde ich immer Fruchtumfahrung aktiviert lassen.

**Comment by Cyruss01** [comment]
OK, vielen Dank. So geht es jetzt.
