### ISSUE TITLE
Kurse laden im Mp fehlerhaft.

### ISSUE THREAD

**Issue by txmazing** [Courseplay/courseplay#5768]
Wir haben festgestellt, dass ab einem uns unbekannten Zeitpunkt die Kurse nicht mehr richtig geladen werden können.

https://youtu.be/TGCfLgV4w2k

**Comment by Tensuko** [comment]
logdateien vom client und server bitte, danke...

**Comment by txmazing** [comment]
Soll ich irgendwelche Debug-Channel aktivieren?

**Comment by txmazing** [comment]
Er hat dies mal zwar die Kurse geladen, doch wenn der Abfahrer eingestellt wird kommen folgende Errors:

[log_server.txt](https://github.com/Courseplay/courseplay/files/4968067/log_server.txt)
[log_client.txt](https://github.com/Courseplay/courseplay/files/4968068/log_client.txt)

Nach 2 Mal auf "Abfahrer einstellen" geklickt und er sag er ist bei Punkt 1/1 obwohl es 1/140 sind.

https://youtu.be/GjcUkcVpX14

**Comment by txmazing** [comment]
[log_server.txt](https://github.com/Courseplay/courseplay/files/4968622/log_server.txt)
[log_client.txt](https://github.com/Courseplay/courseplay/files/4968623/log_client.txt)

Hier die log für das fehlerhafte laden.

**Comment by txmazing** [comment]
Wenn ich mich nicht irre ist es Fahrzeugabhängig.

**Comment by schwiti6190** [comment]
Hi, ich werde werde vorerst nichts an den Kursen speichern/laden etc. änderen, da diese ein aufwändigere Überholung notwendig hat.

**Comment by Dwarfbare** [comment]
Servus

Wir haben das gleiche Problem, wir haben festgestellt:
1: Server Restart bringt eine saubere Reihenfolge der Kurse
2: Verschieben der Kurse in einen anderen Ordner Verändert die Reihenfolge
3: ab dem 2 einloggen ohne Serverrestart werden die Kurse sporadisch falsch geladen.
4 ab  dem 3 einloggen ohne Serverrestart werden keine Kurse mehr richtig geladen.

Je mehr Kurse man erstellt / verschiebt umso schlimmer / schneller passiert der Fehler

**Comment by Tensuko** [comment]
Das sollte sich um einiges gebessert haben, trotzdem werden wir am Kursmanagement erst mal nichts ändern.
Mache hier erst mal zu.
