### ISSUE TITLE
HUD issue Switching between modes and 'Number of runs to perform'

### ISSUE THREAD

**Issue by Dennizzzzz** [Courseplay/courseplay#5771]
Using a tractor with a trailer to unload a combine

When switching from mode 5 
![1 mode5](https://user-images.githubusercontent.com/10248136/88191042-4b7f6b80-cc3b-11ea-98d5-84f85683ae73.jpg)

to mode 2:

![2 mode2](https://user-images.githubusercontent.com/10248136/88191067-5508d380-cc3b-11ea-8c4e-20f76058e6fa.jpg)

There is no 'Number of runs to perform' option in the hud.

Then switching to mode 1:
![3 mode1](https://user-images.githubusercontent.com/10248136/88191171-6fdb4800-cc3b-11ea-8fcf-c5bf39ef08de.jpg)
You see the 'Number of runs to perform' option in the hud.

Then switching to mode 2 (again):
![4 mode2](https://user-images.githubusercontent.com/10248136/88191223-7c5fa080-cc3b-11ea-8ddc-6273596f5f96.jpg)

Now mode 2 has the option 'Number of runs to perform'.

**Comment by Dennizzzzz** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4960689/log.txt)

**Comment by Tensuko** [comment]
We know this, but Mode2 has no option for number of runs so this is not a problem.
