### ISSUE TITLE
Field work: A lot of fertilizer/slurry wasted on turns and over headlands

### ISSUE THREAD

**Issue by Troopersan** [Courseplay/courseplay#5774]
Hi guys
I was playing on Lone Oak Farm and noticed that a lot of slurry was being wasted on a course generated with headlands on turns and with the tool being turned on too early during the turn and over the headland that was created at the beggining of the course.

I decided to do some tests on Felsbrunn, field 21, area 2.40 ha, using the ingame Bredal fertilizer with the spreader disks (30 metres).

1 - Courseplay with headland, 1 pass, short edges. Used 922 L of fertilizer

2 - Manual drive with GPS simulating the same CP course. 540 L of fertilizer

3 - Hired worker, normal up and down and no help needed. 541 L of fertilizer

4 - Courseplay, no headland, up and down course. Crashed on trees, needed help on north side of the field. 641 L of fertilizer.

I believe there is an issue with the headlands and how early the worker turns on the tool during turns as it is spreading over the areas that it had already passed earlier. I wouldn't mind a little wastage but it seems excessive as it uses 922 L for that field when you compare to the hired worker 541 L for the same job.

CP version: 6.02.00040

**Comment by Tensuko** [comment]
Can you make a Video of the parts where hs waste the slurry ?
I just took a look at the turns (180° and 90°) and haven't seen any waste of slurry.
Always starts exactly where he should.
Settings for Implement:
raise = early
lower = late

**Comment by Troopersan** [comment]
I made a video. Have a look. The implement settings were the default ones as you pointed out.

[https://youtu.be/HCiU7GcxuAc](url)

**Comment by Tensuko** [comment]
Link is not working

**Comment by Troopersan** [comment]
Just copy and paste. Couldn't figure out how to make the link work on this message.

**Comment by Tensuko** [comment]
How to make Links work:
Copy and paste the URL...

**Comment by Tensuko** [comment]
Do not start a Course with Headland on a Corner.
The Overlapping part is like it is, would happen with normal Helper as well.

@pvaiko 4:25 ( https://youtu.be/HCiU7GcxuAc?t=265 ) he starts spraying on the generated path to the end turn.

**Comment by Troopersan** [comment]
> How to make Links work:
Copy and paste the `URL...

Well there is an icon on the top of the message box that says "Add a link", which I used and it didn't work. Next time I'll do what you said and just ignore the icon. Sorry about that.  : )


> Do not start a Course with Headland on a Corner.

Not sure I understood what you meant. I assume you're saying that I should NOT start on the narrow edge with the headland first. That I should start on the long edge and let the helper do the headland his own way. Please correct me if I misunderstood you. I'll do a test later to see how it goes. If needed I'll do a video as well and report back to you.

**Comment by Tensuko** [comment]
good:
![fsScreen_2020_07_24_14_58_14](https://user-images.githubusercontent.com/27344744/88393716-69c1a480-cdbe-11ea-95f9-3e8cd996a598.png)
bad:
![fsScreen_2020_07_24_14_58_29](https://user-images.githubusercontent.com/27344744/88393739-72b27600-cdbe-11ea-8aa5-d9e7631a1445.png)

And as I said for the longer turns, that is becosue we gudie the tractor to the next line and somehow he turns on the tool before he reaches the line.

**Comment by Troopersan** [comment]
OK I think I get what you are saying. I did some more tests and there was a big improvement on the usage (688L compared to the first test 922L) doing the way you suggested.  Still the game hired worker would do it with 541L, so with a lot less overlap.

That is fine, I don't really mind paying more for the help but I think that there some areas that there is still too much overlap.
Look at minutes 4:41, 6:22 and specially 7:07 on the video bellow.

https://www.youtube.com/watch?v=KS7lf6UqFyk

**Comment by Tensuko** [comment]
4:41 is the switch to transition, that is not that much.
6:22 got something to do with the work area I would say.
7:02 again is the turn that gets a generated path on half way to the end turn point (or even a full generated path, depends on turn and settings). This would be something that could get improoved, the rest might be a mroe complex problem I would say.

**Comment by Troopersan** [comment]
OK I understand.
Improvements are always welcome of course.
Thank you for this great mod.

**Comment by Tensuko** [comment]
Should work better now, let us know it something happens where it gets wasted a lot more.

**Comment by Troopersan** [comment]
I did another test using the same settings as before and the fertilizer usage had an improvement of almost 30%. compared to the first test. Great job. Thank you for following up on that.
