### ISSUE TITLE
Mode10: Traktor fährt nur noch im Kreis

### ISSUE THREAD

**Issue by dennisblack777** [Courseplay/courseplay#5775]
Hallo Zusammen,

heute ist ein komisches Verhalten im Mode10 aufgetreten.

Traktor soll das Silo verteilen & verdichten und direkt nachdem der Traktor ins Silo fährt, will er sich die ganze Zeit im Kreis drehen und fährt nicht mehr hoch und zurück, wie es eigentlich sein sollte. (Gestern lief es im gleichen Silo ohne Probleme)

Hat jemand eine Idee woran es liegen könnte?

![mode10](https://user-images.githubusercontent.com/5053027/88362032-60fbaf00-cd7b-11ea-8cb1-812e34197641.png)

[log.txt](https://github.com/Courseplay/courseplay/files/4970248/log.txt)

**Comment by Tensuko** [comment]
Verteilen und verdichten funktioniert noch nicht so gut.
Ich würde dir dafür den Tipp geben, dass du einfach einen Kurs selber aufzeichnest, in dem du vor und zürück im Silo fährts.
Klappt dann zwar eher schlechte in Verbindung mit Abfahrern die etwas abkippen, aber leider ist der Stand so.
Oder du versuchst einen anderen Traktor.

**Comment by dennisblack777** [comment]
@Tensuko danke für die Info, gut zu wissen. Als ich die vordere Walze abgekoppelt habe, hat CP den Kurs wieder normal gefahren in meinem Fall.
