### ISSUE TITLE
courseplay unload combine small issue

### ISSUE THREAD

**Issue by Friendlyx** [Courseplay/courseplay#5777]
All in all it works for me with 6.02.00040.dev when the combine drives on during unloading everything is fine but when i select the combine to stop during unloading the tractor starts to drive backwards after unloading is finished and then it bushes the to dolly trailers into each other end gets stuck. May it be possible to let the tractor just stand still after unloading? Just as it does when the combine drives on during unloading?

**Comment by Tensuko** [comment]
Won't happen for now, as it depends on several situations and I think we have some kind of Issue for this.
It only works if you unload when pipe is not in the fruit and not the reverse out of fruit manuver.
