### ISSUE TITLE
Unloader don`t find combine on field

### ISSUE THREAD

**Issue by TobiHH78** [Courseplay/courseplay#5778]
I have the problem that my unloaders don`t find the combine on the field anymore.
I can`t choose a combine, but can only set "search it on field xx".

I set the correct field in the unloader menu, but nothing happens. The unloader don`t start to drive to the field.

![1](https://user-images.githubusercontent.com/56259322/88451012-b2776d00-ce53-11ea-9057-3841fd4dc530.JPG)

![2](https://user-images.githubusercontent.com/56259322/88451015-ba371180-ce53-11ea-8baf-337297439481.JPG)

[log.txt](https://github.com/Courseplay/courseplay/files/4975008/log.txt)

**Comment by Tensuko** [comment]
Search combine on field is a filter for the list......
Switch the mode to 5 and back to 2 then it should work.
For leased combine somehow nedd to save and restart game, not sure why...

**Comment by TobiHH78** [comment]
Hat funktioniert, vielen Dank

Interessanterweise werden beide Drescher auf Feld 1 angezeigt, obwohl einer eindeutig auf Feld 2 unterwegs ist, und die auch recht weit auseinander liegen.

Gibt es eigentlich einen Trick, um einem Drescher zwei Abfahrer zuzuordnen? Sobald ich bei zwei Abfahrern das Häkchen beim gleichen Drescher mache, fährt keiner der beiden zum Drescher, egal was ich einstelle.

**Comment by Tensuko** [comment]
2 Abfahrer geht leider noch nicht. Steht aber alles im Wiki und in #5272
