### ISSUE TITLE
Sähmaschine düngen?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#5779]
Hallo Leute
Die Sähmaschine düngefunktion aktivieren bzw deaktivieren ist nun ja bei den advanced Settings. Könnte man die nicht wieder in normale hud integrieren?
Hintergrund ist der, das man ja manchmal Feldmissionen erledigt,  wo düngen ausgeschaltet bzw nicht notwendig ist, und normale Säarbeiten, wo ich düngen möchte.
Da immer in die advanced Settings einzusehen ob aktiv oder inaktiv, ist halt umständlich.
Dieser Punkt inm normalen hud wäre leichter zu sehen bzw zu ändern.
Lg
Andreas

**Comment by Tensuko** [comment]
Wird so nicht passieren.
Diesbezüglich bitte abwarten.
