### ISSUE TITLE
Abfahrer Macht nichts, und kann auch keinem Dräscher zugewiesen werden

### ISSUE THREAD

**Issue by DaRkFeX** [Courseplay/courseplay#5780]
Hallo Leute!

Meine Abfahrer machen nach Auswahl der Dräscher nichts, genau so kann ich Dräscher im Menü zwar auswählen aber sie werden nicht übernommen, da steht dann: "Ausgewählter Dräscher: Keiner"

Version. 6.02 Dev 0.00040

**Comment by Tensuko** [comment]
#5272
