### ISSUE TITLE
Workings in the heads

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#5781]
Hi, I did various tests but, especially with the plows, since they have an oblique working area, during the work in the heads it leaves a small unworked piece. Is there already a way to eliminate even that small piece (I reduced, during the creation of the path, the working width of the plow)? Or can you devise a way to be able to go over the part already worked during the processing of the perimeter?

Log:[log.txt](https://github.com/Courseplay/courseplay/files/4975524/log.txt)

**Comment by 0Pietro20** [comment]
![Farming Simulator 19 25_07_2020 14_33_55](https://user-images.githubusercontent.com/59969508/88457254-4281da80-ce85-11ea-9d1e-bce7113b3878.png)
![Farming Simulator 19 25_07_2020 14_33_30](https://user-images.githubusercontent.com/59969508/88457272-54fc1400-ce85-11ea-9adc-dcb17341062a.png)

**Comment by Tensuko** [comment]
I would set a bit more Headland and do a overlay of at least 10% (that is only on Headland).
The left out patches comes from entering the next line after a turn.
Haven't done anything on it yet, but we have a lot to do and not much time for that right now.
But as I said, try to play arround with Headland a bit it might get reduced a bit.

**Comment by pvaiko** [comment]
Also in Advanced Settings you can set raise implement to late, lower implement to early.

**Comment by pvaiko** [comment]
(BTW, what's the point of one headland with a plow? Should be more like 5-6 to provide room for the tractor to turn on field)

**Comment by sharky98** [comment]
I can confirm I am having the same issue. I am using 5-6 headland runs. I tried lower and raise implements late and early, I played a bit with the vertical offset, to no avails. It always leave and untouched bit in the triangles of the plow (using the Agro Masz POH 5).

Any idea which logs, debug for a picture/video would help?

See below; in purple it's the incoming plow; green dot the rotation point and orange is the outgoing plow. It's a bit exagerated but it shows the point. Also note that on the rotation point, the purple stop at the front of the plow, while the orange one start in the middle of the plow. This add also the the missing bits.

![20200726_195028](https://user-images.githubusercontent.com/8150191/88492561-8eae4700-cf79-11ea-8d6d-3eb1662a2e93.jpg)

**Comment by pvaiko** [comment]
With smooth turns there's no guarantee for 100% coverage. That's just geometry.

**Comment by 0Pietro20** [comment]
I use the settings that allow you to raise late and lower early, but a small part still remains. I noticed the "Headland Overlap" setting but I didn't understand exactly what it does

**Comment by pvaiko** [comment]
#5097

**Comment by pvaiko** [comment]
should be fixed by 57
