### ISSUE TITLE
Multiple tools are not working headland as intended

### ISSUE THREAD

**Issue by 419054** [Courseplay/courseplay#5783]
The right one is not working as intended, It starts with headland on mark number two and after refill it goes for up and down rows. I tested it with center and left tool and it was working as it should. Im pretty sure i didnt have this problem on some of the previous versions. There is no starting spreading animation at position one with right tool. Last two lines are very close to each other dunno if that can cause issue
![1](https://user-images.githubusercontent.com/68528285/88469133-223a3600-ceee-11ea-936a-26c562dc0111.jpg)

**Comment by Tensuko** [comment]
Do not create a course with headland on a corner.

**Comment by 419054** [comment]
How do you mean on corner? Here are the course settings for the N - S direction and its the same. Right tool wont start on the north - west end. I need headland here because of the object on south east corner. Ok on short edges started ok, but im pretty sure i used around type before with no problems.
![3](https://user-images.githubusercontent.com/68528285/88474775-284e0800-cf2a-11ea-9659-3edce8aa6e09.jpg)

![2](https://user-images.githubusercontent.com/68528285/88474685-54b55480-cf29-11ea-9ab6-ba6789957d24.jpg)

**Comment by Tensuko** [comment]
![gen](https://user-images.githubusercontent.com/27344744/88475706-bf1ec280-cf32-11ea-86be-d2e007105283.jpg)

**Comment by 419054** [comment]
Its fine if i click on the middle of the map as starting point and automatic direction, ty.
