### ISSUE TITLE
Combine harvester unload not working

### ISSUE THREAD

**Issue by Flacwby** [Courseplay/courseplay#5784]
Has anyone gotten a simple tractor with tipper to unload in 6.2.xxxx? I've had to revert to 6.01.00399 as that's the last version I could get to work. 6.2.xxxx always says "No combine in reach". Surely in the last 7 months someone has gotten it working correctly? If so what's the secret?

**Comment by Tensuko** [comment]
The secret is to read #5272 and in the last few month I let all my combines unload by mode2 driver.... Just wow for this 'Issue'
