### ISSUE TITLE
Course Manager Delete Saved Course

### ISSUE THREAD

**Issue by Sim-ian** [Courseplay/courseplay#5785]
Hi

I don't know if i am being blind but i can't seem to find a way to delete saved courses in the course manager. I am sure there used to be a bin/trash icon you clicked to delete courses you no longer needed but i can't seem to find it. Is it missing or am i just being totally blind?

By the way great work on V6, it's been a while since i played and it seems to have come on immensely. Keep up the good work.

**Comment by Tensuko** [comment]
A logfile would help or better say I don't know what version you use.
Also don't know where you got your version from so do this:
Delete all courseplay related .zip files, download the official Version from here: https://github.com/Courseplay/courseplay/releases
And your delete course buttons should be where they are:
![delbuttn](https://user-images.githubusercontent.com/27344744/88476048-7ae0f180-cf35-11ea-92ff-b19f34e232c2.png)

**Comment by Sim-ian** [comment]
Its the latest version from github downloaded this morning.
![CP Manager](https://user-images.githubusercontent.com/26321894/88476433-28510680-cf30-11ea-9d57-5fecb131d10f.jpg)

**Comment by Tensuko** [comment]
Attach your logfile pls.
Do you play MP or SP ?

**Comment by Sim-ian** [comment]
I play MP on a dedicated server.

[log.txt](https://github.com/Courseplay/courseplay/files/4977500/log.txt)

**Comment by Satissis** [comment]
@Sim-ian check out latest version. Should be fixed so you can delete courses and folders again

**Comment by Tensuko** [comment]
Tested on Server and works just fine.
