### ISSUE TITLE
Manage Combine issue - not showing on current field

### ISSUE THREAD

**Issue by gachiemane** [Courseplay/courseplay#5786]
I've encountered an issue where the only combine I have on the manage combines screen is "stuck" on the last field it worked (15).  It is currently working another field, but the HUD filters show "Current: None" and "Search Combine On  Field" is blank for the actual field its working (17) and it still shows up on the field it is not on (15)

As such, tractors cannot find it to unload to it.

First time posting so if any log files or attachments are needed, please advise.  Thanks
![CP 6 issue](https://user-images.githubusercontent.com/68817865/88482779-921de000-cf31-11ea-83ea-764bbc5dc8e3.png)

**Comment by Tensuko** [comment]
Can you try switch Mode once. Like switch to Mode5 and back to Mode2, if it then gets noticed correctly.

**Comment by gachiemane** [comment]
Yes I tried that and no effect.  I also loaded a different map and experienced the same issues.

**Comment by TobiHH78** [comment]
I have a similar issue. I harvested on two different fields 1 & 2, but in the CP menu both combines were shown on field 1.

https://github.com/Courseplay/courseplay/issues/5778#issuecomment-663839044

**Comment by Tensuko** [comment]
Not very sure what this Issue is about...
The Combine is shown where it actually is, the Search Combine on Field is a Filtersystem for the list, to find your combine more easily.
We will have an eye on that in our tests, but closing this one for now, as we couldn't find a Problem.
