### ISSUE TITLE
Autdrive Setting setzt sich immer zurück

### ISSUE THREAD

**Issue by Clouseau219** [Courseplay/courseplay#5787]
Hi,
hat noch jemand das Problem dass gewisse Fahrzeugeinstellungen nach einem Neustart wieder auf default sind?
Mir ist es bei den Autodrive Settings aufgefallen. Wenn ich das Fahrzeug bei Autodrive auf be- und entladen stelle und dann das Spiel neu starte steht es wieder auf deaktiviert.

Ist dazu was bekannt?

Grüße,
Gobo

**Comment by John-Deere89** [comment]
Ab und zu ist das auch bei mir schon passiert
Kam ber nicht vor wenn du es aktualisiert hast ?

**Comment by John-Deere89** [comment]
so ist jetzt wider Passiert das in CP das AD deaktiviert wurde

**Comment by MatthiasRubin** [comment]
Ich habe ebenfalls festgestellt, dass die AD-Einstellung nach dem Neustart immer zurückgesetzt ist. Ich hatte jeweils unload, refill & park aktiviert. Ich versuche mal rauszufinden, ob ich das immer reproduzieren kann und werde noch ein paar Möglichkeiten ausprobieren. Selbst konnte ich den Fehler nicht finden, ich fürchte die Mod ist zu komplex um sie in ein paar Stunden zu verstehen. Ich habe grossen Respekt vor allen die da mitarbeiten. Ich hätte zwar Lust zu unterstützen, weiss aber nicht mal wie ich anfangen soll.

**Comment by 60erjonny** [comment]
Hallo CP-Team
Auch ich würde es sehr toll finden, wenn diese Problem jemand fixen könnte. Dabei ist mit nur diese Einstellung aufgefallen, die nicht übernommen und gespeichert wird. Alle anderen Fahrzeugeinstellungen von den "Erweiterten Einstellungen" bleiben erhalten. Vielen Dank für eure Mühen und Arbeit hier zu CP...!

**Comment by Tensuko** [comment]
@schwiti6190 eine Idee warum das so ist ?

**Comment by schwiti6190** [comment]
@Tensuko könnte damit zu tun haben das dieses setting bei laden zurückgesetzt wird um zu checken ob autodrive überhaupt vorhanden ist

**Comment by Tensuko** [comment]
Wird wohl daran liegen, aber was tun ?

**Comment by schwiti6190** [comment]
Hi @60erjonny oder @MatthiasRubin oder @John-Deere89 oder @Clouseau219, 
könnte mir einer von euch erklären wie das mit autodrive bis jetzt klappt bezogen auf das setting ?

**Comment by 60erjonny** [comment]
hi@schwiti6190
Soweit ich das so jetzt immer wieder beobachte, wird nur die Einstellung "entladen/auffüllen/parken" nicht gespeichert. Nun, hat wohl mit der Parkfunktion zu tun, die CP wohl immer hinterfragen will. Ob euch jetzt das so hilft...

**Comment by schwiti6190** [comment]
@60erjonny wie sieht das aus wenn du dein savegame ladest, sind dann alle konfiguration passend (sowohl CP seite als auch AD seite) bis auf das autodrive setting von CP ?

**Comment by 60erjonny** [comment]
Hi @schwiti6190 

Jeweils nach einen Savegame - Neustart erhalte ich unter der Einstellung AutoDrive...-->

Vor "Nicht benutzen"--> Danach "Nicht benutzen"
Vor "entladen/auffüllen" --> Danach "entladen/auffüllen" 
Vor "entladen/auffüllen/parken" -->Danach "Nicht benutzen"
Vor "parken(P)" -->Danach "Nicht benutzen"

Also hat es dann wohl mit der Parkeinstellung zu tun.
Ich habe den zugewiesenen Parkplatz aber  nicht verändert.
Fahrzeug und Anhänger haben den selben Parkplatz zu gewiesen bekommen, da ja man für jedes Teil einen Parklatz zu weisen kann.
Evtl. ist hier das Problem, das CP nicht damit klar kommt.
Hoffe es kam jetzt gut rüber...
mfg
jonny

**Comment by schwiti6190** [comment]
@60erjonny  Ah okay also nur die Parkpositionen, nach neu start kann man das dann direkt wieder auf parken ändern ?

**Comment by 60erjonny** [comment]
Hi

Richtig und im laufenden Speil bleibt es dann erhalten, nur bei einem Neustart...und das ist etwas lässtig...

**Comment by schwiti6190** [comment]
werds mir an schaun, kann aber noch etwas dauern :)

**Comment by schwiti6190** [comment]
@60erjonny Hättest du lust das mit dem Setting laden mal zu testen mit der branch "David", hab leider kein setup zum testen für AD :)

**Comment by 60erjonny** [comment]
Hallo, aber gerne mache ich das und helfe damit den CP-Team...!
Ich hoffe ich habe alles jetzt so richtig heruntergeladen und installiert.
Soweit ich das jetzt getestet habe, ist jetzt alles gut und i.O.
Der Fehler dürfte behoben sein...vielen Dank dir...!
mfg
jonny
