### ISSUE TITLE
Stop at Last Trigger

### ISSUE THREAD

**Issue by Catfisherman1978** [Courseplay/courseplay#5788]
The stop at Last Trigger is not working correctly. Sometimes it will stop when you select this option but most times it will not. The tractor just continues to run across the field or map before it hits something and then says it slipping. Thanks

**Comment by Tensuko** [comment]
In what mode do your have this happening ?
A logfile with debugchannel 12 and 14 might help.

**Comment by Catfisherman1978** [comment]
Work mode

**Comment by Catfisherman1978** [comment]
After playing a little longer, I believe it could be a mod issue. It doesn't happen on all maps.

**Comment by Tensuko** [comment]
I am closing this as we have made some changes and there will be more later.
Could change a lot.
