### ISSUE TITLE
Mode 3 Verschwindet und wechselt selber in mode 5 / Mode 3 Disappear and perceive yourself in Mode 5

### ISSUE THREAD

**Issue by John-Deere89** [Courseplay/courseplay#5790]
Kurs erstellt und wolte los legen da Wechselt er selber die Mode und dann wenn man ihn beendet kann man mode 3 nicht mehr aus wählen
Warum?
noch ein bug?
Falsche Einstellung?

Course created and wanted to get started because he changes the mode himself and then when you finish it you can no longer choose mode 3
Why?
another bug?
Incorrect adjustment?

[log.txt](https://github.com/Courseplay/courseplay/files/4986966/log.txt)

![20200728102834_1](https://user-images.githubusercontent.com/63151473/88639739-662f6580-d0bd-11ea-8b5e-0ece490cc5d3.jpg)

**Comment by Tensuko** [comment]
Welcher Überladewagen ist das ?

Ein ähnlichen Bug haben oder hatten wir auch im Mode1 für Gülletransporter.

**Comment by John-Deere89** [comment]
https://farming-simulator.com/mod.php?lang=de&country=be&mod_id=140029

**Comment by Tensuko** [comment]
Also ist das der mit 2 Kammern, hast du den auch so konfiguriert oder ist der immer mit 2 Kammern ?

**Comment by John-Deere89** [comment]
Also die Zwischenwand sind nicht drin bzw habe ich nicht ausgewählt
oder was meinst du?

**Comment by Tensuko** [comment]
Ja... ich guck mir den mal an und schau mal.
Bis dahin versuch mal einen anderen. Denke es wird an den konfigurationen liegen, mal schauen.

**Comment by John-Deere89** [comment]
jup liegt am mod  der Bergmann (mod) geht wieder 
Also liegt es teils auch an CPß
![20200728120020_1](https://user-images.githubusercontent.com/63151473/88651449-f1aef380-d0c9-11ea-92fe-24e92825e3f3.jpg)

**Comment by John-Deere89** [comment]
Normal das dass da steht?   (target)

![20200728120305_1](https://user-images.githubusercontent.com/63151473/88651942-7bf75780-d0ca-11ea-971a-f453edd022f9.jpg)

**Comment by Tensuko** [comment]
Wieder die Fruchtumfahrung für den Drescher aus gemacht.

Und was heist Standartfahrzeug funktioniert 'auch' nicht ? Was geht auch nicht ?

 Klar geht es, aber es fehlen wieder die debuginfos!

**Comment by John-Deere89** [comment]
Es ging doch auch mal ohne frucht umfahrung? da ist er abfahrer auch aus der frucht gefahren

naja das is ein standart ülw und dort fuhr er nicht los

**Comment by Tensuko** [comment]
Ok einmal die komplette Erklärung für Fruchtumfahrung:

Fruchtumfahrung beim Drescher aus -> Drescher baut keine Tasche, macht kein Manöver aus der Frucht, holt den Abfahrer auch wenn das Rohr in der Frucht ist.

Fruchtumfahrung beim Drescher an -> Drescher baut sich taschen wenn er voll wird bevor er bei 99% ist unddas Rohr außerhalb der Frucht ist und nur erst dann ruft er den Abfahrer.

Fruchtumfahrung beim Abfahrer aus -> Pathfinder ignoriert die Frucht und fährt auf direktem Weg zum Drescher, eben ohne Fruchtumfahrung.

Fruchtumfahrung beim Abfahrer an -> Pathfinder sucht den besten Weg zum Drescher und berücksichtigt die noch stehende Frucht und umfährt diese, allerdings wird es nach einigen Iterationen auch ignoriert, da es sonst zu lange dauern könnte.

Damit der Abfahrer also seinen Weg schnell zum Drescher findet, der Drescher aber nicht zu einem ungünstigen Zeitpunkt den Abfahrer ruft -> Drescher Fruchtumfahrung = an, Abfahrer Fruchtumfahrung = aus.

**Comment by John-Deere89** [comment]
Danke für die erklärung

Was mir aufgefallen ist das was zu Problemen führt oder kann  das einstellen des Rohres
Man kann dies ja in der Neigung anpassen, das problem es wird von Hause aus immer wieder zurück gesetzt wenn es ein fährt 
Meine frage könnte man eine Funktion änlich wie bei der Mulde  einstellen? das der Abfahrer weiß wie weit der das roh runter fahren soll?

**Comment by Tensuko** [comment]
> Meine frage könnte man eine Funktion änlich wie bei der Mulde einstellen? das der Abfahrer weiß wie weit der das roh runter fahren soll?

Könnte man, haben wir erst mal nicht gemacht. Ob und wann das passieren wird, kann ich nichts zu sagen.



> könnte man das mit dem target was die ganze zeit angezeigt wird und auf der ganzen karte sieht unsichbar machen? :)

Das geht bestimmt, wenn man das mit in den debugchannel 4 einfügt? @pvaiko bisher verschwindet es eher, wenn man channel 4 anmacht, bin ich der Meinung (mich stört sowas halt nicht...)

**Comment by pvaiko** [comment]
> und könnte man das mit dem target was die ganze zeit angezeigt wird und auf der ganzen karte sieht unsichbar machen? :)

Ja, wenn ich dann dieses Issue zumachen kann ...

**Comment by John-Deere89** [comment]
warum wird das an eine bedinung gesetzt?
ihr wolt doch feedback? 
warum solte sie dann geschlossen werden wenn das ein paat dinge aus stehn

`Könnte man, haben wir erst mal nicht gemacht. Ob und wann das passieren wird, kann ich nichts zu sagen.`
wäre ja schön wenn es ginge  is ja kein muss

**Comment by John-Deere89** [comment]
Ich habe noch ein Problem gefunden und zwar wenn der Abfahrer mit dem ÜLW an dem endlade punkt abgekommen ist bremst er nicht ab und läst sich aus rollen  da besteht das Problem das er dann denn anhänger verfehlt

könnte man das noch beheben?

**Comment by Tensuko** [comment]
Wie weit rollt er aus ? Immer gleich oder je nach Last ?
VCA mit drin ?

**Comment by John-Deere89** [comment]
3-5 m zu weit
Nein kein VCA mit dabei
![20200729132450_1](https://user-images.githubusercontent.com/63151473/88794555-eaa5e500-d19e-11ea-87f6-92a30da84765.jpg)

**Comment by John-Deere89** [comment]
Danke fürs fixen
