### ISSUE TITLE
Kein Problem, nur eine Frage

### ISSUE THREAD

**Issue by sepp1** [Courseplay/courseplay#5791]
Wie funktioniert es genau mit der Einstellung Strohablage im Vorgewende deaktiviert bzw aktiviert. Wenn ich auf aktiviert stelle legt er auf dem ganzen Feld Stroh ab so soll es ja denke ich mal auch sein. Wenn ich aber auf deaktiviert stelle häckselt er das ganze Feld und nicht nur das Vorgewende. 

Gruß Sebastian

**Comment by Tensuko** [comment]
Das soll so eigentlich nicht passieren.
Das Problem ist, dass wir damit eine GIANTS Funktion steuern.
Es müsste funktionieren, wenn du im Drescher die Strohablge einschaltest, in CP Strohablage im Vorgewende deaktivierst und den Drescher dann startest. Das Problem ist, wenn der Drescher dann einmal entlassen wird, bleibt die Einstellung im Drescher auf deaktiviert.
Ganz zufrieden sind wir mit der Funktion noch nicht, aber im Moment lässt sich das nicht anders realisieren.

**Comment by sepp1** [comment]
danke für die Hilfe. Werde es so mal versuchen
