### ISSUE TITLE
[Multiplayer Issue] Die Reihenfolge der Punkte wird nicht beachtet.

### ISSUE THREAD

**Issue by Haanneees** [Courseplay/courseplay#5792]
Fehler 1: Im angenommenem Falle, dass es eine Runde als Vorgewende gibt, folgend Bahnen und als erstes das Vorgewende gefahren werden soll:  Der CP Fahrer fährt an überlappenden Stellen, wo sich die Vorgewende Bahn und die Vorgewende Bahn nach der ersten Umrundung überlappen, da diese ja zur ersten Bahn führt, direkt die Bahn herunter. Das heißt, er missachtet die Reihenfolge der Punkte.
Der bekannte Fehler, dass die Auswahl des Punktes, welchen er als ersten anfahren soll, missachtet wird, besteht bei uns auch. Er fährt entweder immer den aktuellen oder den nächsten an, welche er Option er von denen nimmt, ist ja nicht zu erkennen. 
Daher vermute ich dies als Auslöser dafür. Morgen werde ich testen, ob man mit einem kleinen Kurs davor, erreichen kann, dass er immer am Anfang startet. Dann gibt es ein Update meinerseits, ob es am Startpunkt Fehler liegt. 
Ich möchte darauf hinweisen, dass es je nach Menge der betreffenden Spieler nicht unwichtig ist, als Fix für das nächste Update wahrgenommen zu werden. 

Ist dieses Problem auch in vorherigen Versionen bekannt? Falls nicht, würde ich für die Wartezeit zum Fix lieber downgraden.
Ich hab länger hier kein Auge mehr drauf gehabt, in welchen ungefähren Abständen kann man denn mit einer neuen Version rechnen? Zwei Wochen oder doch eher vier? 

Vielen Dank für den Mod und eure anhaltende Unterstützung und Verbesserung an Courseplay. 

Hannes

**Comment by Tensuko** [comment]
Wir werden kein Zeitpunkt nennen, an dem wir einen bestimmten bug gefixt haben.
Es kommt dann wenn es kommt.

Um das Problem mal genauer zu verstehen....
An der Stelle wo es vom ersten zum zweiten Vorgewende geht, fährt er statt des zweiten Vorgewendes in die erster hoch/runter Bahn ?
Helfen kann hier ein logfile mit debugchannel 12 und 14.

Außerdem weise ich auf #5484 hin.

**Comment by Tensuko** [comment]
Closed due to inactivity
