### ISSUE TITLE
Stop & Go Beladung Unterschied?

### ISSUE THREAD

**Issue by TobiHH78** [Courseplay/courseplay#5793]
Nur mal eine ganz blöde Frage. Was bedeutet der Punkt "Stop & Go Beladung"  beim Modus Schaufel befüllen?
Wenn ich in dem Modus z.B. die Mistplatte meines Kuhstalls säubere, merke ich keinen Unterscheid ob ich den Punkt Stop & Go aktiviere oder deaktiviere.

**Comment by Tensuko** [comment]
Die Option is noch garnicht aktiv.
An sich müsste es so sein, dass er nich wartet bis die Schaufel hoch gefahren ist, glaube ich jedenfals.... im grunde sollte es dafür da sein, den Vorgang zu beschleunigen.
