### ISSUE TITLE
Manure Driver is not stopping at reload point.

### ISSUE THREAD

**Issue by Friendlyx** [Courseplay/courseplay#5794]
![fsScreen_2020_07_29_15_41_06](https://user-images.githubusercontent.com/6493968/88829193-8f8ae700-d1cc-11ea-8788-45d1c1702cd9.png)
Why is it not stopping and waiting for refill? Or is the coursesystem changed from the description on the website? 
I have the field course plus the refill course added to the route and the driver does drive the course but does not wait at Waiting point until he is refilled.

<a href="https://abload.de/image.php?img=fsscreen_2020_07_29_1g9jka.png"><img src="https://abload.de/img/fsscreen_2020_07_29_1g9jka.png" /></a>

**Comment by Tensuko** [comment]
Can't see your pic as you not waited till it is uploaded.
So I don't know what refill point, how the course is set up and so on.

**Comment by Friendlyx** [comment]
Click on the broken symbol its a link.

I set the course up with A generated Fieldcourse and a manually driven course for refill which is set up as follows. In the Field the Startpoint and then it is leading to a "P" Waiting point for refill, from there back to the field. In the picture is the Waiting point.

**Comment by Tensuko** [comment]
Try it wit more distance between waitpoint and the 1st waypoint after it.

**Comment by Friendlyx** [comment]
wow what a nice little trick, it works there has to be a huge gap between the waiting point and the next point. Thx
