### ISSUE TITLE
[Suggestion] Mode 3; Add option to search for trailer to dump auger wagon

### ISSUE THREAD

**Issue by wyattdrew** [Courseplay/courseplay#5795]
I have noticed that when creating a course loop for my auger wagon that it is very picky on how close it is to the tractor trailer I am dumping into. Sometimes the tractor with auger wagon sees the tractor trailer as an obstacle even though they are next to each other.

If there is an option to "search for the trailer" like Courseplay does with a combine it may prevent these issues from happening.

**This may be user error but I have been making my auger wagon courses like I would with mode 2 but instead of dumping into a silo it dumps into a tractor trailer.

**Comment by Tensuko** [comment]
Way to complex for now.
The Problem will be more pathfinding that can lower your framerate (and more often) also Pathfinder is not able to handle trailers path.

Adjust your course and waitpoint with the ingame editor (default strg+NUM 0), move it to a better position and save it (default F6)
