### ISSUE TITLE
Mode 3, zu nahe an der Frucht / to close to the fruit

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#5797]
Hallo Leute,
 der mode 3 Abfahrer fährt - bei aktiver Fruchtumfahrung - zu nahe an der Frucht entlang.
könte der nicht 1 oder 2 meter mehr abstand lassen?
wenn ihm der Drescher entgegenkommt, kollidiert der Abfahrer mit dem Schneidwerk des Dreschers.

google translate:
the mode 3 driver - with active fruit experience - belongs too close to the fruit.
couldn't he leave 1 or 2 meters more space?
when the thresher comes towards him, the mode3 driver collides with the threshing unit's cutting unit.

ein Bild (zufällig in der ecke) man sieht aber das die blaue linie sehr knapp an der Frucht ist
a picture (randomly in the corner) but you can see that the blue line is very close to the fruit

![fsScreen_2020_07_30_06_40_59](https://user-images.githubusercontent.com/24860501/88883403-8c2b4600-d234-11ea-9a5c-73194eab8803.png)

![fsScreen_2020_07_30_06_41_04](https://user-images.githubusercontent.com/24860501/88883450-acf39b80-d234-11ea-9f49-bf974feec5d9.png)

lg
andreas

**Comment by Tensuko** [comment]
Ja das Problem ist, dass der Pathfinder den Weg von Trailern nicht berücksichtigt.
So ein angehangener Trailer zieht automatisch einen engeren Kreis, als die Zugmaschine (desshalb fahren LKWs auch immer einen sehr großen Bogen).

Aber ja natürlich, gerade für solch eine Situation, müsste der Bogen angepasst werden.

**Comment by andreasthu** [comment]
Ja stimmt,  in der Kurve läuft der Anhänger zusätzlich rein.
Passiert aber auch auf der geraden,  die CP KI fährt so nahe an der Frucht,  das ein entgegenkommender Drescher mit dem Schneidwerk an diesem hängenbleibt.
Ist mir vorgestern passiert, hab leider keinen Screenshot davon.
Da wäre es besser, wenn die KI ein paar Meter zusätzlich weiter weg bleiben würde.
Der Elmers haulmaster ist ja recht breit, und der Traktor hat ja doppelbereifung,  ist so aber genauso breit wie der elmers.
Lg
Andreas

**Comment by andreasthu** [comment]
ich hätte da noch zwei videos dazu:
https://www.youtube.com/watch?v=fxEXgBrxdE0
https://www.youtube.com/watch?v=Lycr4DpDik4
sehr nahe drann
lg
andreas

**Comment by archaoncze** [comment]
I actually doent understand comments following first issue description in german, but i have this issue with pathfinder in general. I dont know, how it work, but i imagine, that pathfinder take some number from model description to determine its width and based on this set distance from other objects (including fruit)... If that is true, cannot be added to script some another variable and add that number to current default value, to avoid hitting combines cutter, or wrap trailer around trees?

**Comment by andreasthu** [comment]
I Think the same  a value register the wide from the tractor, 
But i think,  cp should addet a pair meters to this value.
In the first video you can see, that the overloader drives near/on the fruit so he collide with the combine and push it out of his way.
In the 2nd video you can see, that the overloader drives too close to the fruit.
2 or 3m more distance were better?
Lg
Andreas

**Comment by Tensuko** [comment]
General Problem of Pathfinder: #5983
