### ISSUE TITLE
Schönheitsfehler 

### ISSUE THREAD

**Issue by John-Deere89** [Courseplay/courseplay#5798]
Leider wurde das mit dem target nicht behoben vlt könnte man das in der nächsten version machen :)

![20200730091917_1](https://user-images.githubusercontent.com/63151473/88896577-509b7680-d24a-11ea-8bfb-b8d0a054099b.jpg)

**Comment by Tensuko** [comment]
ja und welche Version hast du jetzt ?

**Comment by Lustiger-Hubi** [comment]
Seid Ihr eigentlich immer Nachts am arbeiten?

**Comment by Tensuko** [comment]
Und wen meinst du jetzt ?
Wenn du das CP Team meinst, nun ja.... nicht alle leben in Deutschlang und nahen Zeitzonen.

Im Fall von @John-Deere89 für dieses kleine Problem ist es relativ egal, aber ja ansonsten wäre ein gsSetDayTime 12 in der Konsole für ein bisschen mehr Licht schon gut gewesen.

**Comment by John-Deere89** [comment]
na v6.02.00044

**Comment by Tensuko** [comment]
Sollte weg sein.
