### ISSUE TITLE
LKW Anhänger wird nicht beladen!

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#5799]
LKW Anhänger wird nicht beladen!
Die Zugmaschine wird beladen der Anhänger leider nein!
![fsScreen_2020_07_30_11_21_20](https://user-images.githubusercontent.com/48583507/88907023-716ac880-d258-11ea-9097-696eb8302cf5.png)
![fsScreen_2020_07_30_11_29_01](https://user-images.githubusercontent.com/48583507/88907032-74fe4f80-d258-11ea-855c-42fb230f8794.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5000322/log.txt)

**Comment by Tensuko** [comment]
LKW steht ja auch schon am Startpunkt.
Versuch mal den Startpunkt so weit nach vorne zu legen, dass wenn der LKW am Start steht, der 2te Trailer unter dem Rohr vom ÜLW steht.

**Comment by Tensuko** [comment]
![loadonstart](https://user-images.githubusercontent.com/27344744/88909120-04a4fd80-d25b-11ea-8273-e8329000e0b4.png)

**Comment by Lustiger-Hubi** [comment]
Hab ich schon Versucht, geht aber auch nicht!

**Comment by Tensuko** [comment]
ok, notiert.

@schwiti6190 du weist ja nun bestens bescheid wie Mode1 läuft, meinst du man kann den Fahrer wenn er 'zwangsbeladen' wird (ÜLW oder Förderband, ohne das man eine Aktion tätigen muss) das Farhzeug anhält bis Trailer voll ? Sprechen sonst im DC noch mal drüber.

**Comment by Lustiger-Hubi** [comment]
@schwiti6190 meinst du man kann den Fahrer wenn er 'zwangsbeladen' 
                       ohne das man eine Aktion tätigen muss

Wenn du mich meinst, verstehe ich deine Frage nicht!

**Comment by Lustiger-Hubi** [comment]
Auch mit 6.02.00046 funktioniert das nicht!

**Comment by Tensuko** [comment]
Hat auch keiner behauptet.

**Comment by Lustiger-Hubi** [comment]
Ich dachte nur, weil ja jetzt zwei Frucht-Sorten Gerste/Hafer etz einzustellen sind!
Warum ist das dann so?

**Comment by Tensuko** [comment]
Weil es ein Feature Request war, ein Wunsch.
Im Grunde kannst du für den Mode1 jetzt (Beim beladen an einem Silo) eine Liste von Fruchtsorten reinpacken mit Anzahl wie oft die Sorte geladen wird. Wenn Counter auf 0 oder Frucht im Silo leer, wird das nächste genommen.

**Comment by Lustiger-Hubi** [comment]
Danke

**Comment by Lustiger-Hubi** [comment]
Tensuko Habe mal auf der FS19_DondiegoMap am HofSilo mit mein LKW (2 Anhänger) versucht ab zu tanken!
Hatte, ich glaube ich schon mal wo das funktionierte!
Bei den Überlader (siehe oben Bilder) geht das nicht!
Video dazu
https://youtu.be/hLF_yiCRXXQ
Auch auf der LS19_Yogiland_OY (HofSilo) geht das nicht!

Video von der FS19_DondiegoMap
https://youtu.be/LQ2aIBbPG0k
[log.txt](https://github.com/Courseplay/courseplay/files/5021680/log.txt)

**Comment by Tensuko** [comment]
Wir behandeln das Thema in #6046 weiter.

**Comment by Lustiger-Hubi** [comment]
Auch mit 6.02.00064 funktioniert das nicht!
