### ISSUE TITLE
Problem mit Übergabe mit CP & AD / Problem with handover with CP & AD

### ISSUE THREAD

**Issue by John-Deere89** [Courseplay/courseplay#5800]
Dieser Fehler kommt Sporalisch vor und zwar wenn wie man hier sieht der fahrer vom Kalk holen wieder kommt übergiebt er an CP und er solte ja dann an der stelle weiter machen wo er auf gehört hat macht er aber nicht er bleib einfach stehn. Das passierte mir auch schon mit dem Ladewgen  fuhr seine Runden dann bliebt er stehn. Weiß nicht ob es an der weg Berechnung liegt wenn es zu weit weg ist. Das passierte kommischerweiße nur größeren Feldern. Beim Spritzen ect. ist es noch nicht auf getreten.

Kann mir einer sagen warum das so ist? und kann ICH das beheben oder müsst ihr das machen? 

![20200730120052_1](https://user-images.githubusercontent.com/63151473/88911053-957cd880-d25d-11ea-95a5-350c1480c767.jpg)

**Comment by Tensuko** [comment]
Ok also das heist die Übergabe von AD zu CP klappt nicht richtig, aber nur bei großen Feldern ?
Könnte auch mit der Anzhal an Wegpunkten zusammen hängen....

Hmm glaub ein logfile mit channel 7, 12 und 14 könnte helfen. Ob 7 bei der Wegfindung arbeitet weis ich nicht, im zweifel noch 9 dazu, muss mal @pvaiko fragen, ob man generell die Beschreibung Channel 9 Path Finding für alle Pathfinder Dinge nehmen kann :) 

Fahrer kalken lassen bis leer, AD arbeiten lassen bis er zurück kommt und an CP übergibt, wenn der Fehler dann auftritt, mal das logfile posten.

**Comment by John-Deere89** [comment]
Ich schau mal ob ich es wieder Provozieren kann damit er wieder kommt habe mom kein feld zum Kalken 
Mal schauen ob ich im laufe des Tages was Berichten kann

**Comment by Tensuko** [comment]
Hat für uns keine Eile :)

**Comment by MatzeB62** [comment]
Das Probelm liegt nicht nur an der Übergabe von AD zu CP. 
Wenn man zu weit vom Startpunkt enfernt steht, und dann den Helfer/Abfahrer einstellen will am "ersten Wegpunkt" oder am "aktuellen Wegpunkt" schlägt das Fahzeug zwar die Lenkung in die Richtung ein, fährt aber nicht los. Außerdem brechen die FPS total ein.
Erst wenn man in unmittelbarer Nähe des Startpunktes steht, setzt sich der Abfahrer in Bewegung.
Getestet/festgetellt auf dem Dedi-Server mit v6.02.0044

**Comment by Tensuko** [comment]
@MatzeB62 dein Problem ist etwas völlig anderes.
Das zusmmenbrechen der FPS hängt mit dem Pathfinder zusammen, gerade wenn man in der Frucht steht oder durch die Frucht durch muss um zum ersten Wegpunkt zu kommen.
Und Dedi-Server ist noch mal eine ganze andere Baustelle.

**Comment by John-Deere89** [comment]
aber der @MatzeB62  hat schon irgenwie recht das is mir auch aufgegallen stellt man  "ersten Wegpunkt" ein giebt es mehr Probleme (schätze ich) als wenn man naheliegenster Wegpunkt einstellt

ich weiß nicht ob das zufall ist oder vlt damit zusammen hängen könnte (?)

**Comment by MatzeB62** [comment]
@Tensuko  Das das mit dem Dedi-Server eine ganz andere Baustelle ist, ist mir schon bewußt, allerdings gibt es diese Probleme auch im Singleplayer.

Auf dem Server haben wir noch die v6.02.00027 laufen, damit gibt es diese Probelme nicht.

**Comment by John-Deere89** [comment]
@Tensuko  Also nun ist es fast dauerhaft das er nicht Richtig übergiebt 
habt ihr denn was geändert mit der neuen version wo mit Mode 3 rein kann das es nun dazu kommt?
voher ging das bedeuten besser da kam es so gut wie nie vor

**Comment by Tensuko** [comment]
Da ich nicht genau weis was ihr da macht kann ich nicht sagen worann es liegt.
Wir haben da an sich nichts dran gemacht.

Schon mal mit einer älteren Version (1.1.0.4) von AD probiert ?

**Comment by John-Deere89** [comment]
@Tensuko Hast doch das video gesehn oder geht das nicht?
hier noch mal anders hoch geladen 
https://drive.google.com/file/d/1ymXf-Ht4sNO3gyTA_5-rdV7qNFVQCdQq/view?usp=sharing

**Comment by MatzeB62** [comment]
Also meine Vorgehensweise ist die gleiche.
Was in Version v6.02.00027 noch funktioniert hat, funktioniert in der aktuellen Version nicht mehr.
Und mit einer älteren Version von AD kann das ja nichts zu tun haben, wenn der Abfahrer nicht den "ersten Wegpunkt" oder den "aktuellen Wegpunkt" auf größerer Entfernung findet....

**Comment by Tensuko** [comment]
Könntet ihr mal .00056 probieren ? Ich habe Info, dass z.B. Stroh sammeln mit CP und Wegbringen mit AD problemlos läuft.

**Comment by Tensuko** [comment]
.00064 ?

**Comment by Tensuko** [comment]
Da ich hier keine neuen Infos kriege mache ich hier zu, sollte eigentlich laufen, ansonsten bitte bescheid geben.
