### ISSUE TITLE
Mode3 Überlader start mit 'Unloading' funktioniert nicht wie gewollt

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#5801]
Der Überlader fährt einfach grade aus!

**Comment by John-Deere89** [comment]
wie wärs mit mehr Beschreibung damit können die Jungs hier nichts anfangen

**Comment by Tensuko** [comment]
Da hat @John-Deere89 recht und du @Lustiger-Hubi solltest das mitlerweile wissen.... Versuch es noch mal richtig...

**Comment by Lustiger-Hubi** [comment]
Der Überlader im Video fährt einfach geradeaus!
https://youtu.be/15G2U_jDhOI  (anbei log)
[log.txt](https://github.com/Courseplay/courseplay/files/5000659/log.txt)
https://youtu.be/YsNtSuhH1eY (keine log)

**Comment by Tensuko** [comment]
![start](https://user-images.githubusercontent.com/27344744/88922831-05e12500-d271-11ea-8fb2-7f4437040c50.PNG)
Wenn man das genau betrachtet, sieht dein Startpunkt etwas komisch aus, er scheint ein Stück nach hinten zu zeigen und ein zweiter Wegpunkt direkt dahinter.
![wegpunkte](https://user-images.githubusercontent.com/27344744/88922995-4771d000-d271-11ea-8290-c4a68a1999c4.png)
mach mal den editor auf mit strg+num0 und schau ob da 2 wegpunkte übereinander liegen oder knapp hintereinander und dann entzerr das mal, so das der start vor dem zweiten Wegpunkt ist und in die gleiche Richtung zeigt.

**Comment by Lustiger-Hubi** [comment]
Nein! Der ÜL kommt vom Drescher und dreht sich um und fährt wie im Video gezeigt grade aus zu Hof!

**Comment by Tensuko** [comment]
Gib mir mal die Kursdaten.
Ordner Courseplay Kurse und dann MapName.Smaple oder sowas.

**Comment by Lustiger-Hubi** [comment]
Hilf mir Kursdaten?
Map ist LS19_Yogiland_OY
Ordner Courseplay Kurse kann ich doch hier nicht reinstellen, oder?

**Comment by Tensuko** [comment]
Im Ordner wo deine Savegames und auch der Mods Ordner liegt, gibt es einen Ordner für Courseplay Kurse und dort drin ist dann ein Ordner der müsste heißen LS19_Yogiland_OY.SampleMods oder so ähnlich. Den packst du in eine .zip Datei und lädst die hoch.
Oder alternativ aber komplizierter:
Es gibt eine Datei in dem Ordner, wo die Kurse drin verwaltet werden, da steht dann z.B. Feld 2 ÜLW und auch der Name der Datei, die den Kurs beinhaltet. Das ist im Grunde eine Textdatei (in dem Fall .xml) die müsstest du hier so hochladen können.

**Comment by Lustiger-Hubi** [comment]
[LS19_Yogiland_OY.Yogiland.zip](https://github.com/Courseplay/courseplay/files/5001926/LS19_Yogiland_OY.Yogiland.zip)
Geht doch!

**Comment by Tensuko** [comment]
Es ist so wie ich es dir gesagt habe:
<course>
    <waypoint1 speed="1" angle="0.00" pos="**-70.50 100.00 -793.48**" crossing="1"/>
    <waypoint2 **turnstart=**"1" speed="0" angle="**179.89" pos="-70.50 100.00 -793.48**"/>
    <waypoint3 speed="0" angle="179.88" pos="-70.46 100.00 -814.96" turnend="1"/>
    <waypoint4 speed="23" angle="179.90" pos="-70.44 100.00 -825.01"/>
    <waypoint5 speed="24" angle="179.90" pos="-70.42 100.00 -835.10"/>
    <waypoint6 speed="9" angle="179.97" pos="-70.40 100.00 -845.14"/>
    <waypoint7 speed="0" angle="179.89" pos="-70.40 100.00 -846.59" wait="1"/>
    <waypoint8 speed="23" angle="179.89" pos="-70.38 100.00 -856.69"/>
    <waypoint9 speed="32" angle="179.87" pos="-70.36 100.00 -866.81"/>
    <waypoint10 speed="37" angle="179.88" pos="-70.34 100.00 -876.83"/>
    <waypoint11 speed="42" angle="179.87" pos="-70.32 100.00 -886.99"/>
    <waypoint12 speed="45" angle="179.87" pos="-70.30 100.00 -897.02"/>
    <waypoint13 speed="48" angle="179.86" pos="-70.27 100.00 -907.10"/>
    <waypoint14 speed="50" angle="179.86" pos="-70.25 100.00 -917.23"/>
    <waypoint15 speed="49" angle="179.87" pos="-70.23 100.00 -927.41"/>
    <waypoint16 speed="43" angle="179.87" pos="-70.20 100.00 -937.58"/>
    <waypoint17 speed="37" angle="179.86" pos="-70.18 100.00 -947.66"/>
    <waypoint18 speed="30" angle="179.85" pos="-70.16 100.00 -957.67"/>
    <waypoint19 speed="6" angle="179.88" pos="-70.13 100.00 -967.67"/>
    <waypoint20 speed="0" angle="179.84" pos="-70.13 100.00 -968.28" crossing="1"/>
</course>
Du siehst es sind 2 mal die gleichen Koordinaten und das eine davon ist ein TurnStart, warum auch immer du den da eingebaut hast. Bist mit der Maus abgerutscht, kann ja mal passieren, aber es ist so wie ich es gesagt habe!

**Comment by Lustiger-Hubi** [comment]
Ich versuche es noch einmal

**Comment by Tensuko** [comment]
Hier das Video dazu: https://1drv.ms/v/s!ArGbP_j369r8lw_qc9j8hiIVDeG7?e=LhJF3L
- reproduziert
- Lösungsweg (strg+8 = Wegpunkt ändern)
- Und wie es denn funktioniert

Er bleibt am Wartepunkt natürlich nicht stehen, weil er leer ist, nur so als Info.

**Comment by Lustiger-Hubi** [comment]
Ja das weiß ich! Das war ja auch Manuel wie der ÜL fährt!
Er macht das ja nicht immer.
