### ISSUE TITLE
Wendemanöver funktioniert bei Spitzen fahrten nicht gut

### ISSUE THREAD

**Issue by John-Deere89** [Courseplay/courseplay#5802]
sry das ich so viele Issus schreibe   kommt halt irrgenwie immer alles wenn ich länger spiele :D +

Hab dafür ein Video gemacht dort sieht man gut das Problem mit dem Wenden (Natürlich mit Debug Channel)

https://drive.google.com/file/d/1zJNI1K86b-9Yo_4KkbEX6N1Cg1qBHITB/view?usp=sharing

[log.txt](https://github.com/Courseplay/courseplay/files/5001076/log.txt)

**Comment by andreasthu** [comment]
Eventuell wäre da die Option 1 Bahn überspringen eine mögliche Lösung.
Mach ich auch immer mit den 12 u 15m Sähmaschinen
Quasi, erstmal zwei Reihen rundum und dann nur jede 2. Bahn. So klappt das wendemanöver in einem Zug ohne zurückschieben.
Lg
Andreas

**Comment by John-Deere89** [comment]
Da is das Problem das er dann gerne mit der Außenseite der Maschiene egal welche über denn Feldrand kommt und an Bäumen oder änlicheres hängen bleibt

**Comment by Tensuko** [comment]
Konnte das Video noch nicht gugcken, lädt irgendwie nicht. Das Problem mit an Bäumen hängen bleiben kann man mit mehr Vorgewende lösen, oder wie @andreasthu schrieb hilft auch ab und zu eine oder 2 Bahnen zu überspringen im Kursgenerator.
Da das Wendemanöver dafür sorgen soll, dass er gerade in der nächsten Bahn anfängt, wird je nach Wenderadius eben ein großer Wendekreis gebraucht.
![turns](https://user-images.githubusercontent.com/27344744/88929005-cec34180-d279-11ea-933d-8847f786cbe6.png)

**Comment by John-Deere89** [comment]
Video solte jetzt kennn kannt es ja noch mal Probieren :) wenn nicht muss ich es neu hoch laden

**Comment by Tensuko** [comment]
Jetzt verstehe ich dein Problem.
Aber ja, das kannst du mit Überspringe Feldreihen ganz leicht lösen, weil er dann nicht rückwärts fahren muss.

@pvaiko das ist das gleiche Problem wie mit den Headland turns, der Weg wird zu kurz berechnet, somit wird er nicht weit genug gerade gezogen. Ja es kommt vom Tool, wie bei ein paar anderen gezogenen Saatmaschinen auch.

**Comment by pvaiko** [comment]
Für diese Probleme brauche ich Debug Channel 12. Oder am besten ein Savegame.

**Comment by John-Deere89** [comment]
mein Save
https://drive.google.com/drive/folders/15-ugvT8yKW4NMuZpuQTuUhZDC8UVzcpI?usp=sharing

**Comment by Tensuko** [comment]
Ich konnte es erst reproduzieren und nachdem ich das savegame neu geladen habe funktionierte zumindestens der 180° turn....das ist sehr merkwürdig.

**Comment by John-Deere89** [comment]
Danke fürs Fixen wenn es hofentlich kappt aber danke für die Mühe :)
