### ISSUE TITLE
combine unload ai driver keeps beside combine until the end of the field

### ISSUE THREAD

**Issue by Tkaag** [Courseplay/courseplay#5804]
Hey
i have tested this for CP because i have wounded the unloader to drive along side the combine until the end of the field if the start setting is set at 0%. I have addet this condission to the release of the unload driver in line 1802 of file combineUnloadAiDriver : self.vehicle.cp.followAtFillLevel >0 

[CombineUnloadAIDriver.zip](https://github.com/Courseplay/courseplay/files/5002822/CombineUnloadAIDriver.zip)

**Comment by pvaiko** [comment]
@Tkaag thanks for the contribution but we can only accept/review/discuss fixes as pull requests, not zip files.
