### ISSUE TITLE
mode3 issue - driver waits for 2nd traktor

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#5806]
Hallo Leute
ich hätte da noch ein issue für den mode 3:
und zwar fährt der ÜLW Fahrer zum Entladepunkt, lädt ab und wenn der Anhänger voll ist, klappt er zu und fährt zum Endpunkt, egal ob noch was im ÜLW ist oder nicht:
https://www.youtube.com/watch?v=BGxfxgSyGEo
leider zu schnell, da da hinten ein zweiter abfahrer (mit Autodrive) warten würde, das Getreide aufzunehmen.
könnte der ÜLW Fahrer nicht einige sekunden warten, ob noch einer kommt?
lg
andreas

**Comment by rohne83** [comment]
Für das Thema kann man eigentlich sogar jetzt schon einen "Workaround" nutzen in dem man einfach zwei Wartepunkte (halt beide auf Höhe des selben Abfahrers) setzt: 
wenn der ULW leer wird, wird der zweite Wartepunkt eh immer ignoriert (Code deutet schon darauf hin und mehrfaches ausprobieren hat dies bestätigt). Noch was drin haben kann der ULW aber eh ausschließlich dann, wenn der Abfahrer am ersten Punkt schon zu 100% vollgemacht wurde und - sofern man nicht vergessen hat den Abfahrhelfer einzustellen - wegfährt um Platz für den nächsten Abfahrer zu machen. In dem Fall würde der ULW ein kleines Stück nach vorne fahren und dann am zweiten Wartepunkt auf den nächsten Abfahrer zu warten. Mit der in https://github.com/Courseplay/courseplay/issues/6046 vorgeschlagenen Haltezeit könnte man dieses Warten dann sogar auf einen Maximalwert begrenzen, für den Fall dass gar kein weiterer Abfahrer bereitsteht.
Nicht ganz so elegant, wie wenn der ULW einfach an Ort und Stelle stehen bleibt, aber im Endeffekt fast das gleiche eigentlich.

**Comment by andreasthu** [comment]
Danke für die info. 
Werden ich mal probieren.
Btw, wie verhält sich der ÜLW Fahrer bei dir beim Haltepunkt?
Bei mir stoppt er meist, mit Einsatz der Bremsen,
Manchmal jedoch lässt er sich einfach ausrollen, was nicht so gut ist, da er dann über den Anhänger hinaus ausgerollt.
Hab aber noch kein Muster gefunden, kann es auch nicht gezielt reproduzieren.
Lg
Andreas

**Comment by rohne83** [comment]
Also ich geh beim Einfahren kurz vor Erreichen der Trailer ohnehin immer komplett vom Gas und fahr da nur sehr langsam ran, einfach schon um sicher zu gehen dass ich den ULW auch anständig positioniert bekomme. Mehr als 5km/h schafft der ULW-Fahrer daher bei mir bei den Wartepunkten eh nicht, und da hält er dann auch immer punktgenau an. Wie das bei größeren Geschwindigkeiten aussieht, kann ich daher nicht sagen.

**Comment by Tensuko** [comment]
Glaub das können wir allgemein da mit reinbringen als Mode3 Verbesserungen #6046
