### ISSUE TITLE
Overloader Mode

### ISSUE THREAD

**Issue by patch110** [Courseplay/courseplay#5808]
Hi i have setup my overloader course with start- wait-end points but courseplay keeps driving straight on past the trailer before unfoalding the overloader pipe. please see pic for a better explanation.
![fsScreen_2020_07_31_15_52_02](https://user-images.githubusercontent.com/32200890/89047399-4363b200-d346-11ea-8cb5-1ce048019a4e.png)
Is it something i am missing or is there a new way of setting up the course from CP in FS17?

**Comment by Tensuko** [comment]
The Course looks just fine to me.
It should actually stop at the waiting point.
Do you have V 00044 ? https://github.com/Courseplay/courseplay/releases/tag/6.02.00044
Else a logfile with channel 4 7 12 and 14 might help.

**Comment by patch110** [comment]
Hi yes im running the latest version.
Hadnt thought to check the log file would this error cause this issue
Error: addRequiredCropType foliage must match the size of the ground terrain detail.
If so sorry to of been a pain

**Comment by Tensuko** [comment]
logfile pls.

**Comment by patch110** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5007809/log.txt)

**Comment by Tensuko** [comment]
When you have that Error spaming in your logfile there is something wrong, any modconflict or something.
I would try to remove realdritcolor.
And yes if that is not helping I would need a logfile with the debugchannels.

**Comment by patch110** [comment]
Thanks will give that a go

**Comment by patch110** [comment]
hi i stripped back mods to just courseplay autodrive and vca and the terrain detail error is still filling the log. 
Sorry for wasting your timejust have to find another map i suppose.
The map in question is Taylors Farm 4x

**Comment by 419054** [comment]
Could be the tipper. You got two bins there and if one is full and wait point is over it, it will pass. I assume its cuz of that.

**Comment by Tensuko** [comment]
If you try it out on a vanilla map and still have Issues with this CP, we will have a closer look at it.

**Comment by FarmerMoe** [comment]
I am able to replicate this issue consistently when the course SPEED setting is "maximum speed".  When you set the SPEED to "from recording" the vehicle stops at the wait point correctly.

**Comment by Tensuko** [comment]
That is interesting!

**Comment by Tensuko** [comment]
How is it with .00064 ?

**Comment by patch110** [comment]
Hi seems to be working as expected now. Have graincart running with the double hopper trailer and he stops and fills both hoppers everytime.
Thank
Patch
