### ISSUE TITLE
V 6.0.2 Filling up combine harvester and selling yield driving does not work

### ISSUE THREAD

**Issue by ZEBj03rn** [Courseplay/courseplay#5809]
Hi,
I have looked at several tutorials on how the courseplay helper can unload the combine harvester and sell it to a Trigger has not worked for me under V 6.0.20044.dev.
A downgrade of the version to _6_01_00387 made it work.
(Ich kann auch Deutsch)

<script src="https://gist.github.com/ZEBj03rn/ebdf14f95a4c5f84a9c15769a5150412.js"></script>

**Comment by ZEBj03rn** [comment]
Okay, it worked on one field, but then he completely refused to work on the next one, even though the harvester was set manually.
Fruit breakdown off.

**Comment by Tensuko** [comment]
#5272 https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ
no Idea what you did, no Idea what was not working.
Without more information we can't help you.

**Comment by ZEBj03rn** [comment]
Hi,
I got it to work in the older version.
With the latest release version it does not work again.

https://drive.google.com/file/d/1-oV2YaPA8CFp-WfJNQzWXcAvblW6LEZ_/view?usp=sharing

**Comment by ZEBj03rn** [comment]
I have read the Mode2 FAQ five times and watched the video.
https://youtu.be/895zpaeE8iU

I don't understand what I'm doing wrong, it's too easy, isn't it?

**Comment by Tensuko** [comment]
Und wo sind die geforderten Infos ? Wenn du #5272 auch mal komplett gelesen hättest, wüsstest du was wir brauchen um zu sehen was da passiert oder eben nicht passiert.

**Comment by ZEBj03rn** [comment]
Die Logs mit Debug mach ich kurz fertig. ^^
