### ISSUE TITLE
No Reverse Turn on Field (differen round turn that stays on the field)

### ISSUE THREAD

**Issue by enderwiggin07** [Courseplay/courseplay#5812]
Obviously there are vehicles that are not good for reversing, air seeders as an obvious example but almost all trailed equipment doesn't really like being reversed that much.   So to deal with that right now the solution is usually to disable "turn on field" and make a huge headland.   But there is a real life turn maneuver that allows for a compressed headland turn without reversing.  I'm including a poor illustration plus a photo from real life to demonstrate what I mean.  
![no reverse](https://user-images.githubusercontent.com/50051834/89090954-d19e5f00-d36b-11ea-92f0-19f6cf4e83c8.png)

**Comment by Tensuko** [comment]
You dont have to disable turn on field if make a decent headland.... This doesnt help at all. Log and screenshots with debugchannel 12 and 14

**Comment by Tensuko** [comment]
Sry I got your Issue a bit wrong, it was early in the morning....
So this is more a suggestion, sounds interesting.

**Comment by qtbear** [comment]
+1 for this

**Comment by Dylan-M** [comment]
I would love to see this implemented

**Comment by Tensuko** [comment]
As we achieved this with Pathfinder turn active for FS22 CP Version, will close this.
