### ISSUE TITLE
Overloading problem in mode 3

### ISSUE THREAD

**Issue by 419054** [Courseplay/courseplay#5813]
I created this course (grain cart) with 59000 l Krampe. The wagon didnt want to unload. Then i switched to this trailer and it did performed one run, but after that it wont unload again.. 
![1](https://user-images.githubusercontent.com/68528285/89096051-80c25100-d3d3-11ea-9590-d8bf9c7ae44a.jpg)

**Comment by andreasthu** [comment]
try to fold out the upper tube with the left mouse button.
or turn the lower tube higher with the right mouse button.
the aperion is quite high.

I use the  same vehicles, elmers haulmaster, straitmann aperion and krampe sb II 30/1070.
It worked for me.
Lg
Andreas

**Comment by 419054** [comment]
Thanks ^^
