### ISSUE TITLE
Not recognizing combine  

### ISSUE THREAD

**Issue by LaggyLucas** [Courseplay/courseplay#5814]
I am driving the combine etc and have set courseplay to Come to the combine on the selected field at 70% to unload! 
But It does not recognize I own a combine. 

Is there any way to fix this? 

Kind regards, 

Lucas

**Comment by Tensuko** [comment]
Mode2 Driver only works when Combine is driven by CP.
Read #5272 and https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ
