### ISSUE TITLE
not starting the route 

### ISSUE THREAD

**Issue by evybart** [Courseplay/courseplay#5815]
good afternoon 
i have a route for emty a bunkersilo bud when i start
 the route he do's nothing i have the latest version and all vehicle's are ingame
i have the 0.44 version off cp

[log.txt](https://github.com/Courseplay/courseplay/files/5010458/log.txt)

![foto cp](https://user-images.githubusercontent.com/10274098/89102429-55f2ef80-d409-11ea-8281-53ccafba1241.PNG)

**Comment by Tensuko** [comment]
can't reproduce
sidenode: a brighter picture is always nice as we can't see kinda nothing.
