### ISSUE TITLE
CP Combine stop picking crop mid course

### ISSUE THREAD

**Issue by cosmin-margarit** [Courseplay/courseplay#5817]
Hi, I've noticed an issue that I can't pinpoint when it's occurring with a harvester. The harvester is a modded John Deere S680i, and I'm not sure if it's the combine or not because I don't have another one to test with. The issue is that the combine sometimes stops picking up crops usually after a turn and if I stop CP and do the harvest manual it works, and then works after I restart CP. So this is why I'm thinking is not a combine issue. So after it,s bugs out if I stop and and start again Cp it resets and works.

The logs are clean I'll attach 2 videos of the issue.:
Video1: https://drive.google.com/file/d/1VwneTsMDjPCCNaKjuIFNqdsfDxlk8UYi/view?usp=sharing
Video2: https://drive.google.com/file/d/1kTU3MsV7-zbuzuq3LEm4e7StCetjh9hj/view?usp=sharing

Thanks! :)

**Comment by Tensuko** [comment]
logfile ? Channel 12 and 14 for turn.
Actually this not picking up crops also happens when you drive combine on your own and happens if you touched any kind of wrong fruit...

**Comment by pvaiko** [comment]
No idea why is this happening, I know that if the combine partially drives on a field not owned by the player or over wrong type of crop it'll stop picking up crop. Could these be patches of different crop:
![image](https://user-images.githubusercontent.com/2379521/89109245-13c7af00-d405-11ea-952b-08a030c73589.png)
![image](https://user-images.githubusercontent.com/2379521/89109268-3a85e580-d405-11ea-9751-2874f9ab04d9.png)
Especially the top one on the second screenshot seems to remain there even after manual harvesting.

**Comment by cosmin-margarit** [comment]
I will test again and come back with the details on this one

**Comment by cosmin-margarit** [comment]
I've tested again with the ingame New Holland 10.90 and it seems that if it hits another type of crop it bugs out and doesn't pick up the rest. This happened on the corner right before the turn because the seeder could cover the corner.


This is the corner causing problems because the seeder doesn't cover it and the last seeded crop remains. Do you guys have a tip on how to configure the seeder course to cover these kinds of corners? It seems that the headland overlap settings doesn't;t apply to the first headland and the outer edge. I have the headland maneuver set to turn to better cover the corner but still doesn't cover it completely


![image](https://user-images.githubusercontent.com/32977353/89129051-c467a880-d502-11ea-9543-7d6c3fe1e6d9.png)

**Comment by Tensuko** [comment]
The Fieldcorner is realy a Problem here.
Sharp Edges could help in course generator but I know sometimes it doesn't notice it as a sharp corner.
Mostly what I do is expand or shrink my Field with Plow or ingame Paint tool to not have such corners.

**Comment by Tensuko** [comment]
Can't do anything here.
