### ISSUE TITLE
Help with shovel mode

### ISSUE THREAD

**Issue by 419054** [Courseplay/courseplay#5818]
What is wrong with this course so tractor just stops when it needs to go toward tipper?
![1](https://user-images.githubusercontent.com/68528285/89109111-9a4cb280-d43e-11ea-829b-ae3a08a3d532.jpg)

**Comment by Tensuko** [comment]
logfile ?

**Comment by 419054** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5011228/log.txt)
Here it did one run but stucked again on second.
![2](https://user-images.githubusercontent.com/68528285/89110181-67a7b780-d448-11ea-96dd-be38f9caf53b.jpg)

**Comment by Tensuko** [comment]
trailer must be in the wait point else he don't find the trailer correctly.

**Comment by 419054** [comment]
Thanks
