### ISSUE TITLE
Courseplay Problem!! Strohbergung: Krone BiGPack 1290 HDP II

### ISSUE THREAD

**Issue by TunikaTante3179** [Courseplay/courseplay#5819]
Guten Tag
Ich wollte mit Cp auf Hof Bergman mit der Ballenpresse KRONE BiGPack 1290 HDP II von Strohbergung Ballenpressen aber wenn ich Abfahrer einstelle bleibt der Traktor stehen die Ballenpresse läuft aber er fährt nicht. Pick-up ist oben. Wenn ich abfahrer entlasse muss ich die Ballenpresse Abkuppeln und Ankuppeln damit der Traktor wieder fährt!
Ich hoffe dass ich eine rasche Antwort bekomme!

**Comment by Tensuko** [comment]
logfile ?
Ballenpresse mit automatisch nachfüllung gekauft ?

**Comment by TunikaTante3179** [comment]
Ja...Kann sein wiso wass heisst Automatische nachfüllung

**Comment by Tensuko** [comment]
automatsch nachfüllen heist automatisch nachfüllen, das ist das gegenteil von manuell nachfüllen....
Und manuelles nachfüllen funktioniert mit CP mit StrohBergung nicht.

**Comment by TunikaTante3179** [comment]
Okey danke
