### ISSUE TITLE
[Question] Shovel mode and transporting course

### ISSUE THREAD

**Issue by 419054** [Courseplay/courseplay#5820]
Idea is basically that from silo i put silage on a tipper. Shovel mode here is fine but my question is how i get that tipper on farm (for mixing food for example) and back to bunker. Is smth like this possible?  Work around could be wait points of transfer course, but wish to know if its possible to be more automated.

**Comment by Tensuko** [comment]
mode1 load on start, I suggest you to watch some tutorials on youtube.
