### ISSUE TITLE
Update (11.09.20) Trigger Rework and MP Version: 6.02.00070

### ISSUE THREAD

**Issue by schwiti6190** [Courseplay/courseplay#5826]
**Update 11.09.20**
This update had a few MP fixes as well as a bit of restructuring with the Info texts at the bottom of the hud
and the global info texts on left of the screen for MP. 
Hopefully this update reduces a bit of unnecessary network load and so a bit less laggy with multiple CP Drivers.
I would welcome any issue report for muliplayer, but please keep in mind that  _logfiles of server and client_  , screenshots or videos and a small detailed description really helpful are at try to fix those problems :)

Sincerely,
David

**Update 19.08.20**

Once again I've restructured and rebuild a lot off code for loading/unloading and multiplayer, 
so I will be closing old issue that might be fixed.
If your Issue isn't fixed or you found a new one please submit a new Issue or reopen the old one :) .
The same goes for situations that might have worked before, just tell us nicely in the issues and We'll have a look.

Sincerely,
David

**Update 02.08.20**

Hi there,
the last couple of weeks I've been working on a rework for loading/unloading in mode 4/8 and partially mode 2.
This last update(v6.02.00046) might break a few scenarios, that were working before. So please be kind and send a detailed Issue report, with maybe a short explanation on how it worked before.
Also I've created a lot of new code that **might break MP**, as they might be missing some network stuff.
If I've closed your Issue and the same bug/error still exist, please create a new one or reopen the old Issue :)
Once I've got this Trigger Rework pretty stable, I will be looking at MP, but this one might take a bit longer.

Sincerely,
David

**Comment by Sim-ian** [comment]
"Also I've created a lot of new code that might break MP"

It certainly has broken MP, first noticed an issue trying to load milk into a tanker, I got the trigger when pressing R and could select milk and click the start button to begin filling, got the sound for the fill but nothing was going in the tanker. I assumed it was the tanker mod as it was new and the first time i used it. 

Before shutting down the dedicated server to remove the mod i had a seeder waiting to be refilled back at the main farm, so i went there expecting to just load it up with seed for after the restart and that would not fill either. Again could select seed from the silo and it played the seed dropping animation and sound but nothing was going in the seed hopper.

I shutdown the server and deselected the CP mod (which was updated this morning to v 6.02.00046) and after restarting the server and client both the seeder and tanker filed normally. 

The tanker i was using was the Drawbar Tanker mod from modhub and the seeder was the in game Khun BTF 4000 and it's associated hopper TF 1512.

If you need any logs or further info let me know.

Regards
Ian

**Comment by lcc1211** [comment]
Minor problem here with the new fill triggers. Some maps have triggers close together, or (in my case) I put seed, fertilizer silos next to a fuel tank. Now when my tractor drives by and fills with lime or seeds it stops at the fuel trigger with the message that the farm silo is empty. I think this needs at least a bit of tweeking here.

**Comment by Tensuko** [comment]
Updates comes step by step, we can't make a full 'MP is fixed' update.
