### ISSUE TITLE
vehicles do not start mission, yellow arrow and distance show up

### ISSUE THREAD

**Issue by alku50** [Courseplay/courseplay#5827]
Sorry, but I have to ask for help once more in this "old" matter. Tried to follow any advice I could find with no luck. Two recommendation I could not follow: FS would crash with Straw Harvest removed and there is no "Brake"- Key on iMac.
Updated many mods, tested with some vehicle mods removed, only updated Nebraska Lands Map in the mods file.... 
I'm more than 400 hrs in that game with a very effective result in the first year using CP and AD. 
I would very much appreciate advise. 

[log.txt](https://github.com/Courseplay/courseplay/files/5012316/log.txt)

**Comment by Tensuko** [comment]
Available mod: (Hash: d22b91ab8b399d815468276bf8d6e04e) (Version: 1.0.0.0) FS19_addon_strawHarvestBonus
Das hier musst du noch updaten.
Nur von der offiziellen Seite, dort sollte eine 1.0.1.0 sein.

Ansonsten mehr Infos was du versuchst wenn der Error auftaucht, Screenshots und vorallem das logfile dann posten, wenn der Fehler auftrat, weil ich in deinem logfile keinen Error sehe.

**Comment by alku50** [comment]
Dear Tensuko

Your advice did solv my problem. 

Tank you so much !!!!

Best regards Alex


> Am 02.08.2020 um 17:02 schrieb Tensuko <notifications@github.com>:
> 
> d22b91ab8b399d815468276bf8d6e04e

**Comment by alku50** [comment]
Thanks again. I did PayPal you EUR 50.00 trough your website.

**Comment by Tensuko** [comment]
Thank you :) We realy appreciate that.
