### ISSUE TITLE
Kann keine AD kurse generieren

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#5829]
Hallo Leite,
Ich kann irgendwie keine AD kurse generieren.
Ich habe den Autodrive Ordner in der ordnerliste und darinnen die ganzen zielpunkte mit (und zurück).
Wenn ich davon aber einen anklicken möchte, wird daraus kein CP kurs generiert.
Was läuft falsch?
LG
Andreas

**Comment by Tensuko** [comment]
logfile ?

**Comment by andreasthu** [comment]
ach sorry, habs hinbekommen
hatte einen denkfehler,
musste näher an eine AD linie ran
lg
andreas
