### ISSUE TITLE
CP Combine stops after unloading because of error

### ISSUE THREAD

**Issue by cosmin-margarit** [Courseplay/courseplay#5830]
I just bought the New holland combine and it seems that it throws an error after unloading the combine. This is the first time I'm seeing this issue before I was using a John Deere combine and this did not happen.  
Need to mention that it does not happen al the time, only happened once so I didn't see any pattern. Maybe you guys can figure something out from the logs

I've attached the log file and a video to exemplify the issue:
https://drive.google.com/file/d/1mLHZ8yVEbNxsCXVGG3P9r7Mnhu3XFLfU/view?usp=sharing
[CP_error_unloading_combine.txt](https://github.com/Courseplay/courseplay/files/5012497/CP_error_unloading_combine.txt)

**Comment by Tensuko** [comment]
Try Version .00053 or higher and report.

**Comment by Tensuko** [comment]
Closed due to inactivity, haven't noticed any Problem after unload with .00056
