### ISSUE TITLE
CP beginnt nicht beim 1. Wegpunkt

### ISSUE THREAD

**Issue by Wolle1976** [Courseplay/courseplay#5831]
Hallo, 
ich habe das Problem das ich beim CP nicht mehr den Wegpunkt wo er beginnen soll einstellen kann.
Egal was ich einstelle er beginnt immer beim nächsten Wegpunkt

Kann mir jemand helfen??

**Comment by Tensuko** [comment]
logfile ?

**Comment by Wolle1976** [comment]
wie bringe ich die hier rein??

**Comment by Wolle1976** [comment]
[log 2.8.2020.txt](https://github.com/Courseplay/courseplay/files/5012790/log.2.8.2020.txt)

**Comment by Wolle1976** [comment]
Habe nun festgestellt das es bei manchen geht, dort kann ich jedoch nicht einstellen das er wo anders beginnen soll,
Heist: die einen beginnen immer am nächstgelegenen punkt und die anderen immer beim 1. Wegpunkt?

Das entladen über AD geht beim einen und beim anderen nicht

Bin ratlos

**Comment by Tensuko** [comment]
Da schwiti MP General gemarket hat gehe ich davon aus, dass du auf einem Dedi Server spielst ? Wenn ja bitte solche Informationen mitteilen.

**Comment by Wolle1976** [comment]
o sorry,
ja dedi server bei bverygames

**Comment by Wolle1976** [comment]
das bedeutet??

**Comment by schwiti6190** [comment]
Hi,

Hattest du irgenwelche anderen auffälligkeit wie buttons im Hud sind bwi spielern unterschiedlich ? Dato: Spieler A drückt einen button zB. Automatisches öffnen der plane und anschließend schaut spieler B nach ob diese änderung auch bei im ankommt.

**Comment by Wolle1976** [comment]
ist mir nix aufgefallen, aber ich werde es mal testen!
