### ISSUE TITLE
Frage: mehrere Ladewagen bzw Ballensammelwagen kombinieren

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#5833]
Hallo Leute
kann man mehrere Ladewagen bzw Ballensammelwagen kombinieren?
folgende Situation:
![fsScreen_2020_08_02_22_21_57](https://user-images.githubusercontent.com/24860501/89132058-aa819200-d511-11ea-810d-d5f6e83f0778.png)
ich mähe mit dem BigM, Presse mit der Quaderballenpresse und fahre mit 3 Abfahrern mit dem Arcusin FSX63.72 die Ballen ab.
wenn der erste voll ist, fährt er abladen, der zweite bzw dritte machen derweil an der stelle weiter.
wenn nun der erste Ballenabfahrer wiederkommt, macht er dort weiter, wo er aufgehört hat.
da ist jede menge Leerweg dabei, da der 2. bzw 3. ja schon einiges weiter gemacht haben.
könnte man diese drei abfahrer nicht so kombinieren, das der erste dann dort weitermacht,  wo der dritte aufgehört hat zu sammeln.
ist bei Ladewagen und Schwadaufsammeln übrigens genauso
lg
andreas

**Comment by Tensuko** [comment]
Nein das ist nicht möglich.

**Comment by Tensuko** [comment]
@andreasthu 
Wir haben das eben im Team besprochen, wir werden das aber nicht umsetzen (jedenfals nicht für diesen LS).
Es wäre ein zu großer Aufwand da einiges angepasst werden muss, sry.

**Comment by andreasthu** [comment]
Ok, danke.
Ich habe für mich schon eine Lösung gefunden: ich setzte den ersten Ladewagen beim Start an, den zweiten ca in der Hälfte vom Sammelkurs. Oder ich Drittel denn Kurs gedanklich und setzte drei Abfahrer ein,...   dann hat jeder Ladewagen/ Ballensammler seinen eigenen Bereich. 
Lg
Andreas
