### ISSUE TITLE
Scanning hangs 40-60 seconds on Baltic Sea map 

### ISSUE THREAD

**Issue by dbump** [Courseplay/courseplay#5835]
Not sure if I should be opening a new issue; I commented on existing, closed issue #4844 last week.
I am seeing this issue on the Baltic Sea map from the official modhub.  CoursePlay takes about 40-60 seconds to scan fields 16 and 17.  The other 46 fields go by in a blur like normal.  I have tested this with only the three mods required by the map and CoursePlay active and visible to the game.  Is there any additional info I can provide?  Gist link to log file: 
https://gist.github.com/dbump/c24aa065b9e51d24ace6aae4291f3003

_Originally posted by @dbump in https://github.com/Courseplay/courseplay/issues/4844#issuecomment-665349753_

**Comment by Tensuko** [comment]
When it happens only on this map and itis just on scanning fieldsfor once at the start... Not sure wherethe problem in cp is, i rather think it is the map ?!

**Comment by pvaiko** [comment]
https://github.com/Courseplay/courseplay/wiki/Course-Generator-FAQ
