### ISSUE TITLE
offset does not work,and other problems

### ISSUE THREAD

**Issue by wertigoxxx** [Courseplay/courseplay#5836]
**Hi guys!**
There is another problem with the new version.
As I have experienced, the forward / backward shift does not work

It causes problems with silage because the pipe is set to the longest and thus detects an obstacle (the silo and the tractor also stop when it hits an obstacle) there is a distance of about 1-2 m between the 2 vehicles!

Problem 2:
When the AIDRIVER is switched on, vehicles roam.
(in case of several tractors when the forage harvester is waiting to go under the pipe!)

Problem 3:
The turn on ground feature is on, but when I turn it off, it doesn't detect!
There are times when there are no trees and it would be better if the tractor turned off the ground when it ranks back next to the silo!

Problem 4:
You won’t find a combine or a silo when you plan your route!
worked nicely in previous versions but unfortunately not good with the latest version!

![fsScreen_2020_08_02_19_29_32](https://user-images.githubusercontent.com/65092037/89151645-b85f0380-d561-11ea-8577-135d17ebaba7.png)

**Comment by Tensuko** [comment]
And no logfile at all...
Also I dont get any of your problems...
More Details like what you try to do, screenshots or better videos might help.

**Comment by Tensuko** [comment]
closed due to inactivity
