### ISSUE TITLE
unloading bales

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#5837]
I tried to use the CP for the collection and unloading of the bales and everything proceeds correctly, if it were not that when unloading it is too close to the previous unloading point going to interfere with the bales already present
![Farming Simulator 19 03_08_2020 08_40_13](https://user-images.githubusercontent.com/59969508/89153576-7768ee00-d565-11ea-8964-d94961372535.png)
![Farming Simulator 19 03_08_2020 08_40_09](https://user-images.githubusercontent.com/59969508/89153590-7afc7500-d565-11ea-8d10-9218d567926f.png)
![Farming Simulator 19 03_08_2020 08_40_04](https://user-images.githubusercontent.com/59969508/89153594-7cc63880-d565-11ea-9312-d1f6e6880c14.png)
![Farming Simulator 19 03_08_2020 08_40_02](https://user-images.githubusercontent.com/59969508/89153600-7f289280-d565-11ea-9723-536203b8100e.png)
![Farming Simulator 19 03_08_2020 08_39_58](https://user-images.githubusercontent.com/59969508/89153602-80f25600-d565-11ea-89ce-85e09a2d7124.png)
![Farming Simulator 19 03_08_2020 08_39_55](https://user-images.githubusercontent.com/59969508/89153605-82bc1980-d565-11ea-8396-a827b124bff8.png)
The log: [log.txt](https://github.com/Courseplay/courseplay/files/5014316/log.txt)

**Comment by 0Pietro20** [comment]
I also tried with square balls but it leaves a space. I tried, on another map and with the CP version from about a week ago, but it worked perfectly
![Farming Simulator 19 06_08_2020 10_55_38](https://user-images.githubusercontent.com/59969508/89580784-2d6a5b80-d836-11ea-80eb-b76168774315.png)
![Farming Simulator 19 06_08_2020 11_09_12](https://user-images.githubusercontent.com/59969508/89580791-2fccb580-d836-11ea-98a0-25afc8fabec9.png)

**Comment by Tensuko** [comment]
So round bale have no space but square does ?

**Comment by Tensuko** [comment]
Tested distance with round bales, it does ignore round bales somehow...
