### ISSUE TITLE
pick up objects that are in and by the field

### ISSUE THREAD

**Issue by ashleyp96** [Courseplay/courseplay#5838]
hi was just wounding if the is anything you can do to make course play pick up objects eg sandy bay field 1 hit the poles and things like that 
i hope you can help many thanks

**Comment by Tensuko** [comment]
I don't get what you mean pick up objects and hit the poles ?

**Comment by ashleyp96** [comment]
like hitting poles and tress in and by the fields

**Comment by excubated** [comment]
I think OP means "detect".

**Comment by ashleyp96** [comment]
yer is there any way to make it better and to go round them

**Comment by Tensuko** [comment]
Would need to know how your field looks like.
If that are some smal 'islands' use that option in course generator.

**Comment by andreasthu** [comment]
He mean maybe bales, palettes or such things?
Lg
Andreas

**Comment by ashleyp96** [comment]
![117223331_333163817706398_3236323274407545879_n](https://user-images.githubusercontent.com/69144727/89709315-a1ac1880-d976-11ea-92d2-d4611c61673f.jpg)
![117259809_841412896685815_7562458690434994523_n](https://user-images.githubusercontent.com/69144727/89709319-a83a9000-d976-11ea-8087-b55ea02679a7.jpg)

**Comment by ashleyp96** [comment]
thats what i mean it dont pick these up and when i change the settings it gose round the world is there anythink you would be able to do pleases

**Comment by Tensuko** [comment]
Sry for the late answer.
The only thing you can do here is, use the ingame paint tool and draw more grass arround the pole.
Then when you generate a course, turn of bypass islands, if the 'islands' are big enough, the generate will detect them and create the course arround them.

**Comment by Tensuko** [comment]
Can't do much, create bigger islands to create course that can work arround this.
