### ISSUE TITLE
[Feature request] Option to turn on/off Straw Swaths if fruit allows it

### ISSUE THREAD

**Issue by Dennizzzzz** [Courseplay/courseplay#5839]
It would be a nice feature to be able to set an options to turn on or off if you want the Straw Swaths option to be enabled or not. Now before I start CP, to harvest with a combine, I always need to check if the Combine has the right option for Straw Swaths.

And if you switch from to fields where one field with fruit that has no swaths, to a field with fruit that has swaths, you need to 're-enable' the swath option. So if CP will do this for me at start, i'll not forget it.

**Comment by Tensuko** [comment]
We basically have that for headlands. Not sure if we want to add something like that becouse 'so I won't forget it'... will dsicuss this...
