### ISSUE TITLE
CP ignores calls from harvesters controlled by player

### ISSUE THREAD

**Issue by Mantikor83** [Courseplay/courseplay#5840]
Hi CP Team,
actually the transports (normal trailer and augerwagon are effected) do ignore the "helper call" of any combine type when the combine is controlled by the player and not by CP or another type of AI helper. When I'm using the feature combined with any AI helper on the combine CP is working well. Maybe it is possible to fix it, so that player can drive the combine and just the transport is done by CP =)

Thanks in advance!

Henning

Hallo CP Team,
seit geraumer Zeit gibt es einen Bug in den Abfahrer-Modi. Wenn CP mit anderen Helfern zusammenarbeitet, also sowohl Abfahrer als auch Drescher/Häcksler AI gesteuert sind, läuft alles wunderbar. Steuert man aber als Spieler den Drescher oder Häcksler ignoriert CP den "Helfer ruf" völlig. Startet man dann einen CP auf dem Drescher/Häcksler, fährt der Abfahrer sofort los und findet sein Ziel, stellt man dann wieder auf manuelle Steuerung, bleibt der Abfahrer wieder stehen und macht nichts mehr.

Vielleicht könnt ihr das fixen, so dass die Steuerung der Drescher/Häcksler wieder vom Spieler übernommen werden kann =)

Danke und Grüße,

Henning

**Comment by Tensuko** [comment]
ja das ist so #5272

**Comment by Mantikor83** [comment]
Sry, das hatte ich übersehen. Es ging halt in früheren Versionen, deswegen hielt ich es für einen Bug. =)

**Comment by Tensuko** [comment]
Wir mussten den ganzen Modus komplett neu machen, daher blieb erstmal einiges auf der Strecke.
Einige Sachen kommen noch wieder, andere wie das manuelle fahren des Dreschers wird man siehe wie sich das umsetzen lässt, Ideen sind da, aber anderes ist erstmal wichtiger wie z.B. mehrere Abfahrer.
