### ISSUE TITLE
Bailer width with multiple tools

### ISSUE THREAD

**Issue by 419054** [Courseplay/courseplay#5844]
Its still recognized as original width 
![Course Generator](https://user-images.githubusercontent.com/68528285/89197887-afdfea80-d5ac-11ea-984f-4e421b2dcf96.png)
![Course Start](https://user-images.githubusercontent.com/68528285/89197898-b3737180-d5ac-11ea-822a-56dd47a0081c.jpg)
![Settings 1](https://user-images.githubusercontent.com/68528285/89197908-b53d3500-d5ac-11ea-9840-b634faf5b727.png)
![Settings 2](https://user-images.githubusercontent.com/68528285/89197919-ba9a7f80-d5ac-11ea-979e-781ae8dff66d.png)

**Comment by Tensuko** [comment]
No Comment.....

**Comment by Tensuko** [comment]
#5467
