### ISSUE TITLE
[Question] Possible to adapt CP course generator to IRL robotic lawn mowers?

### ISSUE THREAD

**Issue by excubated** [Courseplay/courseplay#5845]
After observing my step-mom's Gardena robotic lawn mower in action, I call the intelligence of the machine into question. Basically, the thing drives in more or less straight lines, turning apparently a random direction and angle when it reaches a boundary wire or crashes into something. 

I'm sure the mower has a buttload of in-house testing and number crunching hours in it to make sure this steering scheme is optimally used for what it is, but I can't for the life of me understand why there isn't a better algorithm in these really, really expensive machines (in Norway a 1000m² unit goes for about €2000 - €3000).

So, to the question at hand: is it technically feasible to adapt Courseplay's code for use in robotic mowers (and perhaps vacuums)? I'm thinking the machine could follow the boundary wire to make a field boundary, and use this data to generate a course that would more efficiently mow the lawn. What I'm mainly hoping to achieve with a Courseplay enabled mower, is prolonged battery lifetime - when the mower darts around randomly to eventually hit all the corners of a lawn, I feel like it wastes over half it's charge driving where it's already been. Furthermore, a more efficient coverage scheme would allow for larger maximum coverage with a given sized unit.

**Comment by polosubtil** [comment]
Hi @excubated 
This is an excellent question !!! The main issue you will find IRL is to get the accurate position of the machine. Even car GPS can't really get to a 50 cm accuracy, in farm machinery you can get to +-30cm but it's quite expensive and not repeatable (your position drift with time)
Only option for accuracy and repeatability is RTK but the cost is over the roof for that functionality.

I work in farm machinery electronics and I think the CP course generation could become something interesting for tractor consoles in the near future

**Comment by Tensuko** [comment]
As long the newspaper headlines won't be something like:
'Tractor crashed into house couse of computer game software' :)

**Comment by polosubtil** [comment]
Well, you're right, I meant something like the CP course generator.... :)

**Comment by pvaiko** [comment]
@polosubtil is right, the biggest problem would be determining the position of the mower, in the game it is not a problem as the position of any object is known to the millimeter.

Just like the field boundaries and islands, although the resolution is bigger there, but obtaining an accurate map of the environment for this use case would also be a challenge.

**Comment by excubated** [comment]
@polosubtil What about using GPS only as backup/calibration/secondary sensor, and instead utilizing a combination of accelerometer, compass, triangulation of boundary wire signal, and motor feedback? In my feeble mind there's enough data there to wave the magic programming wand and pop out centimeter-accurate 3D positioning 😅

Also, hope posting in a closed thread doesn't break anything 🤘

**Comment by pvaiko** [comment]
@excubated no problem, and if you got that positioning part done I'll be happy to help you with porting the course generator code...

**Comment by GeorgeEarslight** [comment]
@excubated apologies for jumping in the conversation, but there exist commercial GNSS modules that can use data from IMUs to enhance accuracy, mostly in degraded satellite signal reception situations. That being said, centimeter accuracy is the domain of RTK GNSS. Not trying to sound like a smartmass, but you can understand that this is a subject worth billions, so if it's not already out there, it's because it's either outside the scope of what you're looking at (commercial lawn care) or doesn't exist.
