### ISSUE TITLE
Fertilze not being used on a seeder. Bug when switching between mode 2 and mode 1

### ISSUE THREAD

**Issue by TinMen6** [Courseplay/courseplay#5846]
V 6.02.00046

Fertilze is not being used when seeding. But when i check the map it show that the field was fertilized. Game setting for fertilize is NOT set to buy.

When i use mode 2 to get the crop to silo and then i switch to mode one to sell the grain the tractor does not stop to fill the trailer. After i save the game go to main menu and go back to the game mode 1 works just fine

**Comment by Tensuko** [comment]
attach full logfile please

**Comment by schwiti6190** [comment]
Hi, 
It would be really helpful, if could post a screenshot of your hud setting and of the CP Driver in action. 
A video would be even more helpful.

**Comment by TinMen6** [comment]
> 
> 
> attach full logfile please

sorry i am kinda new to this. how do i do that?

**Comment by Tensuko** [comment]
In the same folder where your savegames or your mods folder is, you got a log.txt
That one you can drag and drop into the comment box on github.

**Comment by TinMen6** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5017338/log.txt)

**Comment by TinMen6** [comment]
working on the videos now if they are still needed?

**Comment by TinMen6** [comment]
Now in this video the seed is not being used.
https://streamable.com/jw7c7k

Mode 2 and mode 1 problem
https://streamable.com/eq1gj8

And another problem with refilling lime. The tractor stops at the wrong silo. I used the same courseplays for days without any problems until today
https://streamable.com/bme6af

**Comment by schwiti6190** [comment]
for the first video did you have a seeds and fertilizer selected in the hud ?
for the second video did the silo work once, if not might be mod related.
for the last one does the silo return lime ?

**Comment by schwiti6190** [comment]
nvm the first comment line, could try the same with selecting seeds, as this one was a try at creating a workaround for #5776

**Comment by TinMen6** [comment]
Yeah the silo worked fine before with the same tractor and trailer that is how i filled the trailer you see in the video.
Not sure what do you by "does silo return lime"? sorry english is my second language

**Comment by Tensuko** [comment]
First Video:
No Idea how you do this, I wasn't abele to reproduce this with all buyable stuff off.

Second Video:
The 2nd Waypoint is to close to the Start.
How to Mode1: Drive Trailer under pipe, start record, drive straight forward untill 1st waypoint after start appearch, then just normal drive the course. Stop the Course a few meters before the pipe.

Third Video:
You had 'Stop at last point or at next trigger' active, thats why he doesn't continue.

**Comment by TinMen6** [comment]
First Video. It looks like it happens on only one field which is wierd works fine on another field with same stuff. 
This is the message i get on that field.
![Screenshot_23](https://user-images.githubusercontent.com/24297065/89216308-74ecaf80-d5ca-11ea-9eee-5a7d65b59978.png)


žSecond video. why it happens only when i switch from mode 2 to mode 1 if i start the game and the tractor i allready set to mode 1 the courseplay works fine?

Third video. Tried it with another tractor and switched the stop at last point or next triger OFF and the tractor stop at the gas refill point. Does not refill fuel and it does not start to move

![Screenshot_24](https://user-images.githubusercontent.com/24297065/89216323-7918cd00-d5ca-11ea-9a39-5d3d6e1c9d47.png)

**Comment by Tensuko** [comment]
For First:
Well then this is a Map Issue or something like that

For second:
That is how it works, when it works like that right at gamestart, then that one is just a lucky situation.
If you make the course like I said, you should be all good.

Third:
The refill fuel could be the Issue here then.

**Comment by TinMen6** [comment]
I removed the fuel refill point stops at the fertilizer sile and does not move on. With previuse versions of courseplaye it moved to the third and refill the lime there without any problems and returned to the field.
![Screenshot_25](https://user-images.githubusercontent.com/24297065/89218385-39ec7b00-d5ce-11ea-8496-44f18adf39d2.png)
 
I downloaded the .00045 V and it works like normal. Goes to the third silo, refills, goes back to the field and the "stop at last point or next triger" is activated.

**Comment by Tensuko** [comment]
The Problem only appears when passing by at a gasstation.

**Comment by TinMen6** [comment]
No for me it does not happen like that.  Just tried it on the fresh new game and only mods that i used were CP and the placables refill tank and it and same thing happenes. I did the test with 2 sets of refill tanks and the tractor stops at the fertilize tank and opens the cover but nothing happens. If i want to refill with lets say lime and the tractor must drive past fertlizer tank first it stops there and does nothing but if the first tank is lime then it refills and goes back to the field. The seeds tank does not bother the courseplay at all the tractor drives past it ever timey i tested the CP.

**Comment by schwiti6190** [comment]
It's the same problem actually, might get it fixed in the next verison but not sure.
