### ISSUE TITLE
6.02.00046 Attempting to fill a feed mixer with the new filltype function grinds the FPS down to 0.01

### ISSUE THREAD

**Issue by excubated** [Courseplay/courseplay#5849]
Hi all, 

I noticed the filltype section in the GUI had some changes. I immediately thought the new function would allow CP to automagically mix silage, hay and straw to TMR, and decided to give it a try.

Firstly; I'm not sure if this is intended or not, but after adding the 3 filltypes they appeared in the GUI, but the amount only ranged 0-20, and the value selection wasn't scrollable so I had to use the +/- buttons. I set the hay/straw/silage ratio to 8/3/9, thinking this would amount to 8+3+9=20 --> 100%. 

I started mode1 on First waypoint, with the tractor approx. 3 waypoints behind the end point. Possibly unrelated, but CP seems to identify the entire unload trigger in the MF Shed Pack's MF Silo Multifruit, as a collision point. Can be seen in screenshots. No matter where inside the building I started the driver, it would not move and just report "is in traffic".

Anyways, manually driving the front wheels out the other side of the silo building took me out of the collision zone, and the feed mixer started filling up with the first filltype in the list. Immediately after starting the driver, however, my FPS plummeted to waaay below 1 (F2 just showed 0 FPS), and I think it took about 5 minutes IRL between pressing the "Start/stop driver" keybind and the driver actually stopping. My FPS went straight back up when the CP UI click sound played and the driver was stopped.

Logfile attached, the relevant session starts at line 122176.
I ran the reproduce attempt with a lot of debug flags, don't remember which ones tbh. I can see 1, 3, 12 and 19 scrolling through the log, 19 really spams tbh. I just checked whichever seemed relevant at the time. Hope it helps.

[log.txt](https://github.com/Courseplay/courseplay/files/5019540/log.txt)

![20200804022147_1](https://user-images.githubusercontent.com/1683752/89241409-12fa6d00-d5ff-11ea-9396-fe335657fec3.jpg)

**Comment by schwiti6190** [comment]
Hi,

Could you please tell us next time if your using multiplayer. The lua callstack seems to relate to giants code, so I can't really do much about this for now. If you want you can try to recreate this one with only the nesecessary mods, as of now there are a few mod errors already there.

**Comment by excubated** [comment]
Game session with reported bug is in single player. I've renamed the 00046 version's name in modDesc.xml to "no MP" to make it easier for myself activating the correct version for different maps. The 46 changelog said something about breaking MP so the map I'm playing with my GF would stay on 45.

I'll try to clone the save and strip it of all mods except the map and feed mixer. Do I need to disable DLCs as well or are they safe?

**Comment by Tensuko** [comment]
Still valid with .00064 ?

**Comment by Tensuko** [comment]
Closed due to inactivity
