### ISSUE TITLE
AiCollisionTrigger

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#5850]
Hallo Leute
bekomme bei der Horsch Leeb PT350 (aus dem Horsch pack von Giants) die meldung das kein ai kollisionstriigger gefunden wird:
z.b.:
2020-08-04 07:43 ## Courseplay: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work! vehicle Leeb PT 350 (#4)
habe in der i3d udn der xml nachgesehen, der eintrag ist i nder xml, und in der i3d ist der trigger auch drinnen

zusätzlich habe ich komische anfahrten wenn ich damit spritzen möchte:
![fsScreen_2020_08_04_07_43_24](https://user-images.githubusercontent.com/24860501/89257736-0d188200-d627-11ea-875c-504ba0ca85a0.png)
![fsScreen_2020_08_04_07_43_32](https://user-images.githubusercontent.com/24860501/89257738-0f7adc00-d627-11ea-9c66-b8e2324cade5.png)
![fsScreen_2020_08_04_07_43_55](https://user-images.githubusercontent.com/24860501/89257740-11dd3600-d627-11ea-9afa-cd7d66c7a93b.png)

das ist bei den anderen Selbsfahrspritzen auch, die ersuchen den ersten punkt im rückwärtsgang anzufahren, anstatt eine normale wende zu machen und ihn normal anzufahren
lg
andreas

**Comment by Tensuko** [comment]
Wie sieht das mit der aktuelle 6.03.00004 aus ?

**Comment by andreasthu** [comment]
Hallo Tensuko.
Werde ich demnächst mal ausprobieren.
Bin aber derzeit, wegen einer wirbelsäulen-op vor einigen Wochen, eher selten am pc. Kann max 30min sitzen, werden es aber bei Gelegenheit testen. 
Lg
andreas

**Comment by andreasthu** [comment]
das klappt nun viel besser
![fsScreen_2020_12_08_05_29_25](https://user-images.githubusercontent.com/24860501/101440274-b0034480-3916-11eb-8022-2ccdf92a9102.png)
![fsScreen_2020_12_08_05_29_36](https://user-images.githubusercontent.com/24860501/101440279-b1cd0800-3916-11eb-9ae1-d165900271dd.png)
version ist die v6.03.00012
schöne Anfahrt zum Startpunkt
lg
andreas

**Comment by Tensuko** [comment]
Alles klar, dann machen wir hier erstmal zu :)
