### ISSUE TITLE
Driver stops by courseplay lua error during liquid manure refill

### ISSUE THREAD

**Issue by Friendlyx** [Courseplay/courseplay#5851]
The Driver aborted the refill and I had to drive manually back to the field for continuing work via current route point. the picture shows the log.
![fsScreen_2020_08_04_09_31_56](https://user-images.githubusercontent.com/6493968/89266165-dd24ab00-d635-11ea-8db0-dfcb9fa5cd51.png)

**Comment by Tensuko** [comment]
Attach the logfile...

**Comment by schwiti6190** [comment]
I am guessing you were using Autodrive for your refill course, am I right ?

**Comment by Friendlyx** [comment]
yes I used the Autodrive course and added it

**Comment by Friendlyx** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5023921/log.txt)

**Comment by Tensuko** [comment]
Wait... I got a question...
Why the HUD doesn't say you 2 combinated course, but the PDA Map shows more then just the Fieldcourse ?
And if you have more then the Fieldcourse, why refill with AD ?
That doesn't make sence at all ?!
If you use AD to refill only load a simple Fieldwork Course.
If use CP to refill, load the Fiedlwork Course and only Add the Refillcourse with the Folder with the +

**Comment by Tensuko** [comment]
Oh and one addition....
stop make this:
Available mod: (Hash: 22f1ba368fe842040b1e324a0329fcab) (Version: 6.02.00046) zzz_Courseplay_6

Download the .zip File, place in fods folder, done, no packing and renameing or stuff like that.
https://github.com/Courseplay/courseplay/releases/tag/6.02.00046

**Comment by Friendlyx** [comment]
Hey you got it wrong with Autodrive. I made a field course and then I took from the Courseplay hud folder Autodrive the course slurry pond and return, combined both courses and saved for that field. So thats why there is no saying 2 combined courses anymore.
I did the same with the courseplay made refill course. I will try again without renaming the folder but i guess its the same result

**Comment by Tensuko** [comment]
Thats complete different then.
Anyway.
Add the Refillcourse with the + Folder and it should work just fine.
What you can try is, generate the Course with AD Lines (from the AD Folder) and save that Course, then use that saved course to add to your Fieldwork Course.

**Comment by Friendlyx** [comment]
will take the dev code and zip it but with original file name

**Comment by Tensuko** [comment]
you don't need to take the dev code, the release IS the dev code....

**Comment by Friendlyx** [comment]
just to make sure that the error is not caused by the error which occurs right after clicking start after map load please check picture
![fsScreen_2020_08_04_21_49_48](https://user-images.githubusercontent.com/6493968/89338285-a766dd00-d69c-11ea-8c7b-56790ff4bf7d.png)

**Comment by Friendlyx** [comment]
Fieldcourse
![fsScreen_2020_08_04_21_52_14](https://user-images.githubusercontent.com/6493968/89338512-f9a7fe00-d69c-11ea-9433-22833c3e278b.png)

Reload course
![fsScreen_2020_08_04_21_52_35](https://user-images.githubusercontent.com/6493968/89338577-0cbace00-d69d-11ea-9790-221582b43843.png)

both combined
![fsScreen_2020_08_04_21_52_44](https://user-images.githubusercontent.com/6493968/89338600-15130900-d69d-11ea-963a-22ed5c6b5254.png)

Error
![fsScreen_2020_08_04_21_53_24](https://user-images.githubusercontent.com/6493968/89338640-20fecb00-d69d-11ea-9171-407bcb176a73.png)

**Comment by Friendlyx** [comment]
do you need the logfile again?

**Comment by Friendlyx** [comment]
Same config working good with courseplay 6.02.00044

**Comment by Tensuko** [comment]
Basic refilling working just fine without Issue:
![fsScreen_2020_08_05_14_39_07](https://user-images.githubusercontent.com/27344744/89413702-90ba9780-d729-11ea-9ac4-b91b6efd8013.png)

![fsScreen_2020_08_05_14_39_39](https://user-images.githubusercontent.com/27344744/89413724-9a43ff80-d729-11ea-9e81-6d145ff4b146.png)

Same with a Fieldcontainer:
![fsScreen_2020_08_05_14_37_00](https://user-images.githubusercontent.com/27344744/89413786-adef6600-d729-11ea-8645-728bd88b0fbb.png)

**Comment by Friendlyx** [comment]
strange thing, Its the Gemeinde Rade map there is the slurry pit already in the map maybe thats a problem? I can't get it working with latest CP.

**Comment by Tensuko** [comment]
Can you try something ?
Remove FS19_manureSystem and try it again.
It might be that the fix that Wopster added for our old Trigger System now cause Problems.
If it does work without ManureSystem, will have to contact him again.

**Comment by Friendlyx** [comment]
ok i try

btw what is this error? it comes as the last line during map loading
Error: Running LUA method 'loadTriggerCallback'.
2020-08-05 17:07 mods/FS19_Courseplay/LoadingUnloading.lua:18: attempt to call method 'getRootVehicle' (a nil value)

**Comment by Friendlyx** [comment]
happens also without ManureSystem

**Comment by schwiti6190** [comment]
> 
> 
> ok i try
> 
> btw what is this error? it comes as the last line during map loading
> Error: Running LUA method 'loadTriggerCallback'.
> 2020-08-05 17:07 mods/FS19_Courseplay/LoadingUnloading.lua:18: attempt to call method 'getRootVehicle' (a nil value)
are you using Autodrive to drive to the trigger?

**Comment by Friendlyx** [comment]
> are you using Autodrive to drive to the trigger?

NO
