### ISSUE TITLE
the new version doesnt give me Course Generation tab its just the old one

### ISSUE THREAD

**Issue by CopCops** [Courseplay/courseplay#5853]
![image](https://user-images.githubusercontent.com/69196124/89283916-9eebb380-d656-11ea-9475-2bf74e478d2b.png)

**Comment by CopCops** [comment]
ik it says that the version is 6.01.00354 but it was the same with 6.02.00046

**Comment by Tensuko** [comment]
becosue you are on the total wrong page....
Page1 (2nd from the left)

**Comment by CopCops** [comment]
> becosue you are on the total wrong page....
> Page1 (2nd from the left)

Sorry but im so lost atm can you direct me to it please :(

**Comment by Tensuko** [comment]
same place where you start and stop the driver, but you got to be in Mode4 or Mode6 (Mode6 you got active on the screenshot so just click on the button where you start and stop the driver)

**Comment by CopCops** [comment]
ok thank you so much ima try

**Comment by CopCops** [comment]
> same place where you start and stop the driver, but you got to be in Mode4 or Mode6 (Mode6 you got active on the screenshot so just click on the button where you start and stop the driver)

im in mode 6 but its the same thingh 
![image](https://user-images.githubusercontent.com/69196124/89287226-3c95b180-d65c-11ea-8b0d-fb189bf95939.png)

**Comment by Tensuko** [comment]
Is that the place where you start and stop the driver ?!

This Button!
![89287226-3c95b180-d65c-11ea-8b0d-fb189bf95939](https://user-images.githubusercontent.com/27344744/89287837-f12bd500-d654-11ea-9f7c-391c307284a1.png)

**Comment by CopCops** [comment]
thanks now i got it
Sorry for wasting your time
