### ISSUE TITLE
CP do not work with RMT menu

### ISSUE THREAD

**Issue by Tavraczek** [Courseplay/courseplay#5854]
When I click on the special box in RMT menu (m) nothing happens

**Comment by Tensuko** [comment]
RMT ?
logfile ?
Screenshot ?

**Comment by Mannie313** [comment]
Meint er vielleicht Rechte maustaste und das CP manü?

**Comment by Tavraczek** [comment]
Okey,
The RMT is- real manual transmission for me a best gearbox mod in farming 19. The mod is work fine with courseplay but in menu (setting automatic clutch atd.) i click on button and nothing happens. I tried on lates version (CP very old) and it works.

![fsScreen_2020_08_04_23_00_33](https://user-images.githubusercontent.com/69218694/89344824-ca968a00-d6a6-11ea-9296-8dee8c887d28.png)

**Comment by Tavraczek** [comment]
(log is clear)

**Comment by Tavraczek** [comment]
and with mouse cursor it is possible to move normally but doesnt respond on click (rmt menu) CP is respond. Sorry for my english.

**Comment by Tensuko** [comment]
> 
> 
> (log is clear)

when I ask for logfile I want to see it, but anyway.
Won't do anything about it.
What you can try is go in adv setting and deactivate the mouse open menu for CP and use the key to open CP Menu.

**Comment by Tavraczek** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5024669/log.txt)
Okey sorry. There is. I try this hint and mores but not work.
