### ISSUE TITLE
turn on field not working for wide turns and for question mark turns

### ISSUE THREAD

**Issue by Phalanx380** [Courseplay/courseplay#5855]
turn on field is not working. no matter what tractor or implement i use they all go off the field to turn.
![download](https://user-images.githubusercontent.com/39988550/89369976-e93a6680-d722-11ea-96c8-3f297b3324eb.png)
![Screenshot_302](https://user-images.githubusercontent.com/39988550/89370074-328ab600-d723-11ea-87c7-b2fa1ede99c6.png)

**Comment by schwiti6190** [comment]
Hi,
 could you try the same with turn on field deactivated? I recently change the variable and might have mixed it up.

**Comment by Phalanx380** [comment]
first screen cap is on second is off. done in the same spot
![Screenshot_303](https://user-images.githubusercontent.com/39988550/89409740-e3b24000-d765-11ea-8716-57d55c2396ee.png)
![Screenshot_304](https://user-images.githubusercontent.com/39988550/89409799-f9276a00-d765-11ea-9e5b-71fb04fa5cde.png)

**Comment by schwiti6190** [comment]
Did this one work fine with v 6.02.00045 ?

**Comment by Phalanx380** [comment]
i only check in for Courseplay updates around once a month so i didn't get 6.02.00045 i think the last updated i had was 38 or 39 and it worked fine.

**Comment by pvaiko** [comment]
@Phalanx380 need a log with channels 12 and 14. Also, which map, which field is this?

**Comment by Tensuko** [comment]
@Phalanx380 We would still need a logfile for this one

**Comment by Crazysonoran** [comment]
I came here to start an issue about this same thing. Doesn't matter which tractor/combine/sprayer/etc or which tool, CP does not seem to recognize field edges. Posted a pic of one example with a headland and the option to stay on field enabled. Over the last few months I have tried many different turn modes as well. This started with the boom style liquid fertilizer tools, and the spreader types used to work fine, and as you can see from the picture I attached, it has stopped working. I just spread lime on 9 fields and never has it stayed on the field, regardless of collidables or headlands. Second and third picture have 12 and 14 enabled.
![image](https://user-images.githubusercontent.com/54956919/93023121-906fb080-f5a1-11ea-9665-aab1522a063b.png)
![image](https://user-images.githubusercontent.com/54956919/93023187-2277b900-f5a2-11ea-91b7-fe0a04572792.png)
![image](https://user-images.githubusercontent.com/54956919/93023263-a7fb6900-f5a2-11ea-9bc1-b6e6beee0ef1.png)

Log file is currently too big, I'll reload the game and recreate with a small one and post here when I get it.

**Comment by Tensuko** [comment]
What I can tell you is, that it does working.
You can see it when you have no headland and try to make turn with and without turn on field.

**Comment by Crazysonoran** [comment]
Tested on Felsbrunn, same issue, no other mods running except Easy Dev tools. First picture shows headland turns working properly, second is the turn around from the first to the second path in the middle, clearly goes way off the field. Third picture, the tractor has to make a really sharp turn around and it does in fact turn around on the field as it was told. Fourth picture shows 'on field' turning working properly with a small tool attached directly to the tractor, issue may be due to breadth of turns required.  Also, note the gaps in coverage where the course generator decided to put a little hook on the starter node and the implement did a smooth turn instead of the "Turn" option (which it did to properly on the other headland corners). Log file also attached, log is from right after the failure to turn on the field.
![image](https://user-images.githubusercontent.com/54956919/93023902-3a9e0700-f5a7-11ea-9433-246c68bc04a9.png)
![image](https://user-images.githubusercontent.com/54956919/93023913-44276f00-f5a7-11ea-919e-d6993d044522.png)
![image](https://user-images.githubusercontent.com/54956919/93024021-e6475700-f5a7-11ea-8160-f3a300bc82ee.png)
![image](https://user-images.githubusercontent.com/54956919/93024080-62da3580-f5a8-11ea-81e3-8dea6498c5b2.png)


[log.txt](https://github.com/Courseplay/courseplay/files/5214641/log.txt)

**Comment by Crazysonoran** [comment]
> What I can tell you is, that it does working.
> You can see it when you have no headland and try to make turn with and without turn on field.

Not sure what you mean by this, my tests have been with turn on field enabled and with a headland, which should give the tractor ample room to do its turn on the field which in multiple screenshots above it is clearly off the field, it only worked properly when the course had a return path that was close to the approach. and in 2 cases it is stuck on terrain outside the field boundary. Screenshot here is without headlands and the option to turn on fields on in the first picture and off in the second. 
![image](https://user-images.githubusercontent.com/54956919/93024232-b8fba880-f5a9-11ea-8a75-4e556ec656fd.png)
![image](https://user-images.githubusercontent.com/54956919/93024232-b8fba880-f5a9-11ea-8a75-4e556ec656fd.png)

**Comment by Tensuko** [comment]
Got it why it happens...
Turn on Field on: Distance between turn start and turn end is to smal for a simple 180° turn (or how we call it 'wide turn')
![fsScreen_2020_09_13_19_30_07](https://user-images.githubusercontent.com/27344744/93024560-c770b100-f5f7-11ea-95fd-60df7fc540f5.png)
Turn on Field off: To allign the Tool correctly to the next row, we make that huge turn, wich is also based on the turn radius
![fsScreen_2020_09_13_19_30_42](https://user-images.githubusercontent.com/27344744/93024607-00108a80-f5f8-11ea-96ed-9b7e22d72f64.png)
To show that it is true: Both, turn on field on and off will create this (I think Pathfinder based) 'wide turn' ?!
![fsScreen_2020_09_13_19_31_16](https://user-images.githubusercontent.com/27344744/93024641-20d8e000-f5f8-11ea-9aff-4e8522cc5f85.png)
I did make another test for this: This is even a slightly bigger width of the sprayer with the turn outside of the Field
![fsScreen_2020_09_13_19_37_15](https://user-images.githubusercontent.com/27344744/93024757-ffc4bf00-f5f8-11ea-9d79-bbff9e847427.png)
And where we have a smal distanc of the turn start to turn end with turn on field activated:
![fsScreen_2020_09_13_19_39_40](https://user-images.githubusercontent.com/27344744/93024767-1539e900-f5f9-11ea-9005-9c44ea0fb21c.png)

I also checked if we have a relation between turn radius and the actual generated course with smaler tool width.

@pvaiko I am not sure when CP decide to make that wide turn, if that is base on WP distance or work with or whats happening.
But I think, this shows whats going up here.

**Comment by pvaiko** [comment]
So, there are two different issues here:
1. the one reported by @Phalanx380 is not a wide turn, it is a normal question mark turn and with that specific tractor/implement combination and with an angled headland it drives off the field a bit.
2. wide turns where at the beginning of the turn the tractor is not on the field anymore
