### ISSUE TITLE
Vorgewende Felder mit Runden und Schrägen

### ISSUE THREAD

**Issue by Strawberry93** [Courseplay/courseplay#5856]
Hallo allerseits,

ich weiß nicht ob man hier auch Fragen stellen kann. Ich habe ein kleines Problem mit schrägen und Rundungen, bei nicht komplett Eckigen Feldern beim Vorgewende. Wie kann man dieses am besten Einstellen, damit die Maschinen dieses sehr Sauber abschließen.

Mein Englisch ist auch nicht grad das beste. xD

Gruß Strawberry93

**Comment by Tensuko** [comment]
Dafür gibt es die Option 'Überlappung' in %
Da kannst du nur mit experimentieren. Wenn dir die Rundungen wichtig sind, statt in den Gerade Arbeitsbreite zu verlieren, stelle es hoch.
Physikalisch ist das leider so in 'runden Ecken' :)
