### ISSUE TITLE
Unloader stops when i tries to unload combine on last row. 

### ISSUE THREAD

**Issue by Bobster82** [Courseplay/courseplay#5857]
Hello,

I had a problem where the unloader stops and throws a error while it should unload the combine on the last row.

error:
2020-08-05 11:45 :57 [info lp4400] 1042 (#2): Exception, stopping Courseplay driver, C:/Users/Bobster/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CombineAIDriver.lua:1422: attempt to compare nil with number

Solution:
The problem lies in the check if combine is too close to a turn. On the last row the combine has no 'next turn' , so the value to the next turn is 'nil' .

* CombineAIDriver.lua
-- from line 1422 I added a nil check, before comparing to a number, after this change the unloader worked and no errors
![fs19_checkNilToTurn](https://user-images.githubusercontent.com/47780758/89401197-3a435e00-d715-11ea-84d7-26b3b57d4549.JPG)

I hope i made the right correction, but it worked for me

**Comment by pvaiko** [comment]
@Bobster82 sorry, I missed this in August :) thanks, has been refactored since then and a nil check was added.
