### ISSUE TITLE
Issue filling water, Makes no sense.

### ISSUE THREAD

**Issue by CurtisFeatures** [Courseplay/courseplay#5862]
Hi, 

We have just switched maps and updated to the latest version of course play. 

When we try to fill a tank with water we are now seeing this error and the tank does not fill, either from a placable water source or a lake.

2020-08-06 09:07 Error: Running LUA method 'packetReceived'.
2020-08-06 09:07 C:/Users/Jamie/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/TriggerAIDriver.lua:559: attempt to index field 'validFillableObject' (a nil value)

**Comment by touzenesmy** [comment]
I have the same issue with a trailer I'm trying to fill with anything (silage, wheat, manure), the containers are not fillable anymore as soon as I installed the latest version v6.02.00047, also tried with Courseplay for FS19 v6.02.00046 and doesn't work either.

My last working update was Courseplay for FS19 v6.02.00043 if I remember correctly

I'm on a dedicated server and we actually will wait for patch as we basically cannot do farm work, however we still believe in you and thank you for those updates even if sometimes they can cause some issues.

You guys are the best, we will wait for you don't worry <3

**Comment by touzenesmy** [comment]
I can confirm, reverting to .00043 solved the issue

**Comment by Confusedman74** [comment]
Sorry, this hasn't been resolved :-(
For me it wasn't water, but diesel
Playing on Dedicated Server
Last working version .45
[log.txt](https://github.com/Courseplay/courseplay/files/5100648/log.txt)
