### ISSUE TITLE
Ist es möglich das er Feher von Cp kommt

### ISSUE THREAD

**Issue by RudiBergfeld** [Courseplay/courseplay#5864]
Hallo,
wenn ich eine gewisse Zeit Spiele ca 2 Std das ist immer unterschiedlich kann ich mit der taste R kein objekt mhe aktiviren (also Tanken oder den globalen Markt öffnen ) und habe dann diesen Lua fehler:=C:/Users/rudib/OneDrive/Dokumente/My Games/FarmingSimulator2019/mods/courseplay_047/course-generator/cp.lua (169) : printCallstack um 11:24 hab ich begonnen und um 11:55 hatte ich den Fehler . Siehe Log
Gruß Rudi Berfeld
[log.txt](https://github.com/Courseplay/courseplay/files/5034946/log.txt)

**Comment by Tensuko** [comment]
Und was hast du gemacht als der Fehler kam ?
Und die andere Frage ist: Warum diese benennung ?
https://github.com/Courseplay/courseplay/releases/tag/6.02.00047
.zip runterladen in den mods Ordner packen und fertig!

**Comment by RudiBergfeld** [comment]
Hallo Tensuko,
danke für die wicklich schnelle Andwort. 
1. Ich beende das Spiel und fange neu an ( zuletzt wolle ich ein Fahzeug Tanken).
2. Ich habe Überlegt op ich ein Mod habe der mit Cp nicht kompatibel ist wenn es das giebt.
Gruß Rudi

**Comment by Tensuko** [comment]
Sicher gibtes Mods die einen Conflict mit CP haben können, hab so aber keinen gesehen bei dir.
Es wurde einiges geändert bei Triggern und ein bug ist nicht auszuschließen, wir arbeiten weiter dran und schauen uns auch deinen Fehler an, aber je mehr Infos wir haben wo wie wann was umso mehr hilft uns das.

**Comment by RudiBergfeld** [comment]
Hallo Tensuko,
ich habe das noch eimal getestet ich kann nicht sagen wer den Fehler verursacht aber ich habe herrausgefunden wenn ich von AD den modus Abholen und Abliefern nicht verwende habe ich keine Probleme (ich verwende die Version 1.1.0.5 RCS von AD).Das ist die Log wo ich den Modus von AD Abholen und Abliefen verwndet habe.
[log.txt](https://github.com/Courseplay/courseplay/files/5045430/log.txt)
Und das ist die Log wo ich den Modus nicht verwendet habe.
[log1.txt](https://github.com/Courseplay/courseplay/files/5045431/log1.txt)
Ob nun CP oder AD den Lua fehler verursacht kann ich nicht sagen oder gar ein Mod?
Gruß
Rudi Bergfeld

**Comment by Tensuko** [comment]
Also ich kann über einen Fehler mit AD wenig sagen, kenne aber einige die CP+AD sogar problemlos im MP betreiben.
Welcher AD modus wann richtig ist, am besten bei AD (im Discord vlt) nachfragen.
