### ISSUE TITLE
Not stopping for loading

### ISSUE THREAD

**Issue by XavierDare** [Courseplay/courseplay#5865]
I have been trying to make courseplay work with this for a few hours now. I have it set up and it says loading 0/8000 but then it doesnt stop and just continues moving. I am using the latest dev build. 
![bug report](https://user-images.githubusercontent.com/64657541/89558784-b061c680-d7e2-11ea-8ba5-973b8d3fb315.png)

**Comment by XavierDare** [comment]
Note map is GreenRiver2019

**Comment by Tensuko** [comment]
Attach full logfile pls.
Record Course for Mode1:
Place Trailer under Pipe, start record the Course. Drive straight untill the 1st waypoint appears then normaly drive your course.
Everything else, read: https://github.com/Courseplay/courseplay/wiki/Mode-1-Changes

**Comment by XavierDare** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5037428/log.txt)
im guessing that is what you mean by log file

**Comment by XavierDare** [comment]
OH thanks driving straight till the 1st waypoint showed up made it work! Much appreciated for the quick response!
