### ISSUE TITLE
unloader drives into combine

### ISSUE THREAD

**Issue by markus372** [Courseplay/courseplay#5868]
Hi

since the combine always unloads on the left side it is better for the pathfinder to always start with a left turn when driving away from a combine because otherwise, the unloader will crash into the combine.

![combine unload error](https://user-images.githubusercontent.com/65828332/89581128-bb464680-d836-11ea-9753-534a0fac4cce.png)

**Comment by Tensuko** [comment]
We know and don't need 100 Issues about it, also read:
https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ
