### ISSUE TITLE
CP Fährt zu schnell durch Durchfahrsilo

### ISSUE THREAD

**Issue by RocknRolla1992** [Courseplay/courseplay#5870]
Hallo, Erstmal danke für Courseplay 👍 . ich weis nicht ob das mein Fehler ist oder eine Einstellungssache ist? Mein Abfahrer passt die Geschwindigkeit fürs die Silolange nicht richtig an, dadurch sieht immer noch was über den Hof.

CP erkennt auch das Silo

danke für die Hilfe  :=)

**Comment by Tensuko** [comment]
logfile mit debugchannel 1 und 2 glaube ich und screenshot bitte.

**Comment by RocknRolla1992** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5044831/log.txt)
[debug.log](https://github.com/Courseplay/courseplay/files/5044833/debug.log)
![20200808094524_1](https://user-images.githubusercontent.com/68074690/89705363-065a7980-d95d-11ea-91ff-1f249b0e07cc.jpg)
 ich hoffe, damit kann ich helfen

**Comment by RocknRolla1992** [comment]
hat sich was da ergeben ?

**Comment by Tensuko** [comment]
Nein noch nicht ich muss mir das noch an gucken, wir haben aktuell recht viele Baustellen daher dauert das etwas, sry.

**Comment by RocknRolla1992** [comment]
alles klar kein Problem. ich danke dir trotzdem:)

**Comment by Tensuko** [comment]
Die Durchfahrtsgeschwindigkeit wird berechnet anhand der länge des Silos und Füllstandsmenge des Trailers (glaub auch entladegeschwindigkeit, aber sicher bin ich mir nicht).
Muss das unbedingt noch mal testen im Mode6... er sollte das sogar automatisch in der Breite verteilen.

**Comment by RocknRolla1992** [comment]
in mode 6 konnte man die Überfahrgeschwindigkeit (CP Version 54 ) regeln indem man  im Feld Wendemanöver die Geschwindigkeit so  eingestellt hat das es passt.
in mode2 mit Häcksler klappte dann Garnichts mehr. der Abfahrer führ nicht nebenher  sondern nur hinter den Häcksler. im Silo passte er die Geschwindigkeit gar nicht mehr an.

**Comment by RocknRolla1992** [comment]
Courseplay deleted a comment from RocknRolla1992 5 hours ago
hab ich was falsches geschrieben?

**Comment by Tensuko** [comment]
War nicht hilfreich und hat mit dem Issue nichts zu tun, auch diese Kommentare werde ich wieder entfernen um die Issues übersichtlicher zu halten.

**Comment by Tensuko** [comment]
Passiert im Mode2 in ähnlicher Form, aber weil er zwischenzeitig nicht abladen konnte/durfte ?!
![fsScreen_2020_09_15_15_47_26](https://user-images.githubusercontent.com/27344744/93219262-71bd1580-f76b-11ea-973c-7c5a2226f665.png)

**Comment by Tensuko** [comment]
Sollte gefixt sein, da wir wieder die berechnete Geschwindigkeit verwenden.
