### ISSUE TITLE
Mode 3 Pipe position for unloading of cart

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#5871]
Hey,

In the old mode 3 it was possible to save the position of the graincarts pipe for unloading.
os it planned to reintroduce this feature, as currently the standart pipe position is too low for some trailers.

Greetings,
JDTiger

**Comment by schwiti6190** [comment]
@JDTiger could give me an example for this particular problem ?

**Comment by JDTiger** [comment]
Hey, the standart graincarts have high enough pip positions (and afaik non movable pipes) but for example JHHG's Brent cart (https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=164797&title=fs2019) can't unload into the standart large Krampe moving floor trailer
![20200922201756_1](https://user-images.githubusercontent.com/9157835/93921767-4d37df00-fd11-11ea-9937-998b5596902b.jpg)
