### ISSUE TITLE
Fehler auf dem Server

### ISSUE THREAD

**Issue by Easton97-Jens** [Courseplay/courseplay#5872]
Moin Cp Team ich habe gestern mir die Cp 6.02.0047 heruntergeladen für einen Server und habe probleme das mir sämliche Trigger auf der NF marsch 4fach nicht mehr fucktioniren ich habe Folgende Fehlere im Log drin 

1.  fehler taucht beimm mapstarten auf befor mann den server betreten kann
Error: Running LUA method 'loadTriggerCallback'.
C://gameservers//s1377789//ls2019//gameProfile/mods/FS19_Courseplay/LoadingUnloading.lua:18: attempt to call method 'getRootVehicle' (a nil value)

2. der Fehler taucht auf wenn eine Person den server Bertretten mochte dieser Fehler habe ich auch in andern version wie in der 6.02.0042
Error: Running LUA method 'packetReceived'.
dataS/scripts/vehicles/specializations/events/SetPipeStateEvent.lua(54) : attempt to index field 'object' (a nil value)

3. Bekomme ich immer wider warnungen rein
Warning (script): 'streamWriteIntN': Argument 1 has wrong type. Expected: Int. Actual: String 

4. dise fehler weiß ich nicht so genau wo er herkommt dise fehller habe sehr off im log auf dem eigenem rechner gehabt
Error: Running LUA method 'packetReceived'.
C://gameservers//s1377789//ls2019//gameProfile/mods/FS19_Courseplay/TriggerAIDriver.lua:559: attempt to index field 'validFillableObject' (a nil value)

das waren die fehler die mir offent sichtlich waren die ohne zutuhen entstaneden sind 

das sind beide logs 
[log vom PC.txt](https://github.com/Courseplay/courseplay/files/5045138/log.vom.PC.txt)
[log vom server.txt](https://github.com/Courseplay/courseplay/files/5045139/log.vom.server.txt)

ich würde mich um eine anwort Freuen
Gruß Jens

**Comment by Dwarfbare** [comment]
Wir haben das gleiche Problem, Courseplay als Mod Deaktivert schon gehts wider
