### ISSUE TITLE
 turn on field doesnt work when doing wide turn 

### ISSUE THREAD

**Issue by johans2pl** [Courseplay/courseplay#5873]
When distance between turning points is bigger than 2x turning radius turn waypoints are generated outside of field with "turn on field" option enabled
My settings. No mods. last ver of courseplay
![settings](https://user-images.githubusercontent.com/69396986/89716208-68da6680-d9ab-11ea-8866-20faff671dac.png)
Narrow turn. Works as expected
![narrow](https://user-images.githubusercontent.com/69396986/89716217-7bed3680-d9ab-11ea-8ea5-e88bd04bbd93.png)

And here wide turns
![wide1](https://user-images.githubusercontent.com/69396986/89716244-a7702100-d9ab-11ea-95cf-e1ca86a50e15.png)
![wide2](https://user-images.githubusercontent.com/69396986/89716246-aa6b1180-d9ab-11ea-865a-f9f0685cafc5.png)
Part of Log.txt when doing wide turn with debug channel 12 and 14 enabled
[https://pastebin.com/MTFUVesZ](url)

I changed these lines in AITurn.lua to always use calculated waypoints and it "fixed" issue with PathfinderTurn.

__function_ CourseTurn:startTurn()
--if self.turnContext:isPathfinderTurn(self.turningRadius * 2) then
--	self:generatePathfinderTurn()
--else
self:generateCalculatedTurn()
self.driver:startFieldworkCourseWithTemporaryCourse(self.turnCourse, self.turnContext.turnEndWpIx)
self.state = self.states.TURNING
--end
end_

![calculated](https://user-images.githubusercontent.com/69396986/89716581-734a2f80-d9ae-11ea-9a3a-56c1b3ff433e.png)

Ive tried changing settings Use AI, Use Pathfinding, Avoid Fruit and Reversing  for pathfinding. but turns always are generated same way. Same situation with towed tools.

BTW Lane offset doesnt work at all

**Comment by Tensuko** [comment]
Thats why there is headland for...

What do you mean with lane offset isn't working ?
I am sure it is, when you created a multitool course in course generator.

**Comment by Tensuko** [comment]
Also duplicate:  #5855
