### ISSUE TITLE
Mode 2/Mode 3 - CP stops when unable to finish unloading at end of field

### ISSUE THREAD

**Issue by WubbeOP** [Courseplay/courseplay#5878]
When the combine stops at the end of a field while unloading and is unable to emüty into the graincart completely because the cart is full both the combine and the cart driver will stop and don't move at all unless I reset one of them.
I have seen this in mode 3 as well as mode 2. 

[log.txt](https://github.com/Courseplay/courseplay/files/5046149/log.txt)

**Comment by Tensuko** [comment]
We need debugchannel 4 7 12 and 14, screenshots will also help.
Read #5272 and https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ

**Comment by WubbeOP** [comment]
sorry, I'm crap at this stuff. Will update the next time it happens.

**Comment by WubbeOP** [comment]
ok, this can be closed. It will move but it takes like a minute.
