### ISSUE TITLE
Loader / Unloader Lua Fehler

### ISSUE THREAD

**Issue by Berios** [Courseplay/courseplay#5881]
Hallo zusammen!

Erst einmal vielen dank für eure Mühe - CP wird von Release zu Release immer besser. :-)

Allerdings habe ich bei den letzten Versionen (geprüft habe ich 00045 + 00046 + 00047) direkt beim Start einen 
Lua Fehler in meiner Log. CP schreibt hier einen Fehler in Bezug auf Loading / Unloading raus, mit der Begründung (a nil index).
Momentan habe ich wieder Version 00038 laufen, bei welcher der Fehler nicht auftritt. 

Vielleicht könnt ihr euch das mal in Bezug auf das nächtse Release ansehen.

Vielen Dank für eure Mühe im Voraus. 

Berios

**Comment by Tensuko** [comment]
magst du trotzdem mal das logfile anhängen mit dem Fehler drin ?

**Comment by Berios** [comment]
Sorry, mußte es eben reproduzieren, da ich die alte Log nicht gesichert hatte.
Als Anlage jetzt die Log mit den Fehlern (sind die letzten beiden Einträge).

Danke,

Berios
[log.txt](https://github.com/Courseplay/courseplay/files/5046223/log.txt)

**Comment by Tensuko** [comment]
2020-08-08 23:24 Error: Running LUA method 'loadTriggerCallback'.
2020-08-08 23:24 D:/LS19/LS19 Modordner/FS19_Courseplay/LoadingUnloading.lua:18: attempt to call method 'getRootVehicle' (a nil value)
2020-08-08 23:24 Error: Running LUA method 'loadTriggerCallback'.
2020-08-08 23:24 D:/LS19/LS19 Modordner/FS19_Courseplay/LoadingUnloading.lua:18: attempt to call method 'getRootVehicle' (a nil value)

@schwiti6190 kannst du etwas damit anfangen ?

**Comment by schwiti6190** [comment]
@Tensuko @Berios Es wäre cool zuwissen in welche combination aus triggern und anhänger/gerätschaften dieser fehler auftritt.

**Comment by Berios** [comment]
Hallo schwiti6190!

Ich hatte zu dem Zeitpunkt die folgenden Kombinationen auf der Karte (der Fehler tritt allerdings bereits vor dem Betreten der Karte in der Log auf):

1.) Deutz Serie 9 (FSM) mit einem Joskin Dakkar by Alex
2.) MB Trac Pack - hier der 1800 BB mit 250 PS - ebenfalls mit Joskin Dakkar by Alex
3.) MB Track Pack - ebnefalls der 1800 BB mit 250 PS + Krone Lagewagen (Mod).
4.) SemiTruck 8x8 von Alfredix mit einem Kröger Belt Trailer (72.000 Liter)

Mehr Kombinationen hatte ich zu dem Zeitpunkt nicht auf der Karte (ich hatte noch Drescher fahren - Class 780 Mod Pack mit zugehörigem Schneidwerk).

Trigger Kombinationen kann ich Dir nicht genau sagen - da der Fehler bereits vor dem Kartenstart in der Log war, habe ich die Version direkt wieder rausgeschmissen und bin auf die alte Version zurück gegangen. 
Ich spiele die Oberthal - zu dem Zeotpunkt hatte ich die Düngerfrabrik, die Hofproduktionen (Fermenter + Grastrocker) in Besitz - da ich noch keinen Hof hatte, haben meine Abfahrer nur die Außenlager und die Verkaufspunkte angefahren.

Ich hoffe, daß du mit diesen Informationen etwas anfangen kannst. Ansonsten stehe ich gerne für Fragen zur Verfügung. Danke für Dein Engagement in dieser Angelegenheit.

Berios
