### ISSUE TITLE
when setting up course for multiple tools the right one stars in a different place

### ISSUE THREAD

**Issue by Randywes** [Courseplay/courseplay#5883]
I have a problem with multiple tools recently. I'm running the last update courseplay and i setup  like this

![Farming Simulator 19 Screenshot 2020 08 09 - 02 54 20 73](https://user-images.githubusercontent.com/54022592/89722393-c98c9200-d9f1-11ea-80b1-cac3ee650397.png)

2.the left tractor working in the correct line and the right tractor start in the different line(seems like skipping the 2 headland passes)

![Farming Simulator 19 Screenshot 2020 08 09 - 02 58 35 16](https://user-images.githubusercontent.com/54022592/89722219-ca242900-d9ef-11ea-95a2-e37f54367119.png)
![Farming Simulator 19 Screenshot 2020 08 09 - 02 59 50 88](https://user-images.githubusercontent.com/54022592/89722223-d14b3700-d9ef-11ea-8f50-ec44c43a4abe.png)

3.at the end. the last the tractors has reached trigger end point. The right one seems skip the 2 headland passes

![Desktop Screenshot 2020 08 09 - 03 26 31 48](https://user-images.githubusercontent.com/54022592/89722344-45d2a580-d9f1-11ea-9787-00c177ad0cf6.png)

I would be happy if you could help me.
Thank you

**Comment by SomeoneYouKnow2** [comment]
Don't start the course in a corner of a field if you're using multiple tools.

**Comment by Randywes** [comment]
I Don't understand. so I will start in the middle of the field. and generate field course?

**Comment by SomeoneYouKnow2** [comment]
No, you can start near a corner on the edge of the field but not directly on a corner. I had the same problem before and it fixed it for me (and others who reported the same thing).

**Comment by Randywes** [comment]
It seems work, but if it could be fixed it will be much better, without drive a few meters inside the field. like the old Courseplay version, 
Anyway thank you very much for helping me,

**Comment by Tensuko** [comment]
That won't be fixed as the egenerated course from corner on is not good anyway.
Start on the Side and it is all good.
