### ISSUE TITLE
Cant load equipment with seeds, slurry etc

### ISSUE THREAD

**Issue by RikkynatoR** [Courseplay/courseplay#5885]
HI, i use the latest version and now i cant fill my equipment with seeds, slurry etc, i need to turn courseplay off to make it work

**Comment by Tensuko** [comment]
full logfile and read https://github.com/Courseplay/courseplay/wiki/Mode-4-Changes

**Comment by GitTomahawk** [comment]
I'm playing on dedicated MP Server.
I cannot manually load anything from Silos when couseplay is loaded.
When I send Autodrive to load trailers it can be loaded.
Last working Version: 6.02.00045
