### ISSUE TITLE
 Courseplay  findet Drescher nicht.

### ISSUE THREAD

**Issue by lexion780** [Courseplay/courseplay#5886]
Guten tag 
Ich hab das problem das mein abfahren denn drescher nicht findet. Der bleibt einfach stehen. Hab es schon mit anderen drescher und abfahrer versucht da ist das selbe problem. Mit den Überladewagen ist das selbe. Ich hoffe das mir jemand helfen kann. Hab es auch schon mit einer anderen map versucht und mit mods und ohne. Coursplay v6.02.00047.dev
[log.txt](https://github.com/Courseplay/courseplay/files/5047630/log.txt)

![Screenshot (8)](https://user-images.githubusercontent.com/69424944/89733831-7ac61300-da58-11ea-88e9-6beeea8f1199.png)
![Screenshot (9)](https://user-images.githubusercontent.com/69424944/89733835-831e4e00-da58-11ea-9187-2f95bc0de61b.png)

**Comment by Tensuko** [comment]
#5272 logfile mit channel 4 7 12 und 14

**Comment by Lustiger-Hubi** [comment]
Also ich habe da kein Problem! 
Habe zb. auf der LS19_Yogiland_OY das Feld 8 mit einem Häcksler und 4 Abfahrer abgeerntet!
Ohne Probleme!

**Comment by wertigoxxx** [comment]
Unfortunately, this is all due to performance!

**Comment by Tensuko** [comment]
@wertigoxxx 
I never run into GPU Limits.
The Problem is the Engine with the LUA Based Pathfinder.
As the Pathfinder is not 100% doing the same all time, it is hard to say that the +200MHz GPU Frequenzy is helping here anything.
Also keep in mind, a FPS Drop is not always a sign of high use of a GPU.

**Comment by Tensuko** [comment]
Zu weil inaktiv/nicht die nötigen Infos. Issues dazu gibt es genug, aber nie die nötigen Infos :)
#5272 und Wiki lesen.

**Comment by schulzep16** [comment]
Hallo, ich habe aktuell auch dieses Problem. Man konnte sonst einfach das Feld auswählen, auf dem er nach dem Drescher oder Häcksler gesucht hat. Jetzt muss man den Drescher per Klick genau festlegen. Nur so wird der Drescher gefunden.

**Comment by Tensuko** [comment]
Das ist schon lange nicht mehr so das man das Feld auswählt sondern den Drescher direkt und das ist absicht!

**Comment by schulzep16** [comment]
Sorry, dann hatte ich das Release überlesen.
Habe den LS jetzt eine ganze Weile nicht genutzt. Wie mache ich das jetzt bei zwei Dreschern mit einem Abfahrer?

Mit freundlichen Grüßen 

Philipp

**Comment by Tensuko** [comment]
Einfach beide Drescher auswählen?

**Comment by schulzep16** [comment]
Okay, ich werde es probieren. 
Vielen Dank!

Mit freundlichen Grüßen 

Philipp
