### ISSUE TITLE
Tweeks Needed for Refill Triggers

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#5887]
The new refill trigger has a couple of things that are problematic. 

1. If I have a fertilizer spreader that is happens to drive close to a fuel trigger, CP stops and says the silo is empty and is waiting for more.
2. I can't use the same tractor to spread lime and refill and then switch to a fertilizer spreader without deleting that type from CP and setting it to fertilizer, because if I happen to use an all in one silo or drive by the wrong content first, I end up with a load of lime when I wanted fertilizer and vice versa.

**Comment by Tensuko** [comment]
>I can't use the same tractor to spread lime and refill and then switch to a fertilizer spreader without deleting that type from CP and setting it to fertilizer, because if I happen to use an all in one silo or drive by the wrong content first, I end up with a load of lime when I wanted fertilizer and vice versa.

even if you add both filltypes and switch the order ?
Basically that was one of the reasons we did it. That way you can tell what to load, when can load both.

>     1. If I have a fertilizer spreader that is happens to drive close to a fuel trigger, CP stops and says the silo is empty and is waiting for more.

that we know already and we are working on a better system for the Triggers.

**Comment by lcc1211** [comment]
Yes, I used the tractor with lime in the first position and fertilizer in the 2nd position. When the tractor went for a refill it added fertilizer instead of lime.
