### ISSUE TITLE
Fs19 combi mode issue

### ISSUE THREAD

**Issue by farmer1234567** [Courseplay/courseplay#5888]
When running a silage harvester, combi mode runs Perfect but the offset for the tractor and trailer to the harvester won’t work, I’ve tried +/- offsets of 7,8,9,10m and it just still drives behind the harvester and continues to fill the trailer, have tried it with a few tractors and a few forage harvesters, I’ve seen other YouTube videos of it working for others? is there something I’m missing?

**Comment by Tensuko** [comment]
On first Headland he will always drive behind Harvester.
If you collecting grass, there is a Problem with the fruit detection wich we know about.
As soon as he is on 2nd Headland or Center Part, he should drive beside the Harvester.
Screenshots and logfile with debugchalle 4, 7, 12 and 14 will help too.

**Comment by farmer1234567** [comment]
Even after the headlands it continues to drive behind the harvester, the harvestEr  seems to drive an stop every few seconds with the tractor behind flashing up “traffic”  every few seconds also 

I have tried the  +/- 7.00m offset and it Within the tractor Courseplay and it Dosent seem to work ? 

Kind Regards
Niall Armstrong

**Comment by farmer1234567** [comment]
I’m relatively new to this, how to I obtain the logfile for you to look at? Thanks

**Comment by Tensuko** [comment]
You go in the CP HUD on the Settings Page, there you make the Numbers green (klick them, got 2 pages).
Then you let the Driver run like you would expect it and that logfile will be at the same place where your savegames and mods folder is.
That log.txt you just drag and drop into the comment box and it will be uploaded here.
That is also the basic logfile if you have any other Issues with Mods and stuff.

**Comment by Tensuko** [comment]
With the actual Version we got the Harvester tweaked to be able to use in 1st Headland and they will throw far enough.
If you have one that doesn't work, make a new Issue with logfile with debugchannel 4 7 12 and14.
