### ISSUE TITLE
Trigger problem

### ISSUE THREAD

**Issue by Confusedman74** [Courseplay/courseplay#5889]
Like in #5885 and #5872 there are serious problems with the trigger handling. 

With .46 and .47 you cannot use any trigger on an dedicated server. See pictures and Logfiles 
The first picture is another problem. The same refill course from the singleplayer game anounces that no load is selected/refill course not supported. On singleplayer except of disableing the helper the same course works.
The second picture shows a problem with the trigger, it unloads but the storagelevel keeps the same and nothing will drop into the trailer.

In singleplayer you can use the triggers but when you use courseplay for ex. an refill course courseplay drives to the trigger, stops and disables the helper. You can fill your trailer by hand, drive a little ahead of the trigger an start courseplay again but when courseplay come back to refill it disables the helper again.

Hope that helps a littlebit.
cheers 
Confusedman

[Log Dedi-Server.txt](https://github.com/Courseplay/courseplay/files/5049969/Log.Dedi-Server.txt)
[Log PC Dedi-Server.txt](https://github.com/Courseplay/courseplay/files/5049970/Log.PC.Dedi-Server.txt)
[Log PC Singleplayer.txt](https://github.com/Courseplay/courseplay/files/5049971/Log.PC.Singleplayer.txt)
![Dedi-Server](https://user-images.githubusercontent.com/69455732/89769427-6b4cd580-dafd-11ea-9044-fb8d332c0c3c.png)
![Dedi-Server02](https://user-images.githubusercontent.com/69455732/89769421-6851e500-dafd-11ea-86ce-4d970574a41a.png)

**Comment by Tensuko** [comment]
It is being worked on already.

**Comment by Confusedman74** [comment]
> It is being worked on already.

Thanks for the info!

**Comment by Confusedman74** [comment]
@schwiti6190 
Sorry, this hasn't been resolved :-(
I was trying with water, diesel, seeds, fertilizer and nothing worked
Playing on Dedicated Server
Last working version .45
[log.txt](https://github.com/Courseplay/courseplay/files/5100721/log.txt)

**Comment by Tensuko** [comment]
More Information on 'can't unload anything'.

**Comment by Confusedman74** [comment]
ok sorry, when i drive with the fertilizerspreader under the fill trigger nothing will be filled. Also when i drive with a watertrailer to an waterdisposal (build in from giants) nothing will be transfered. So unload was maybe the false word, better load.
As i mentioned above in my starting posting about the second picture.
