### ISSUE TITLE
Grain Transport

### ISSUE THREAD

**Issue by markus372** [Courseplay/courseplay#5890]
When setting up a grain transport route, the automatic loading at the silo does only work if you are in the vehicle that CP is driving. If you are in any different vehicle the Grain Transport simply waits at the silo doing nothing. The second you switch to the CP-vehicle, the refill at the silo starts.

**Comment by Tensuko** [comment]
logfile, SP/MP ?

**Comment by markus372** [comment]
https://drive.google.com/file/d/11rc5GOu88DBMJwZXn1CzOkQOgJVJ92rj/view?usp=sharing

**Comment by Tensuko** [comment]
You should update Global Company.
Not sure what this is, but when it is a special modded Version of the 1.0 Manure System from Wopster then we have the problem right there.
ManureSystem needs to be the actual Version of ModHub (1.1.0.0)

Adn this is getting spamed into your logfile by a Mod Vehicle:
2020-08-11 17:16 ## Courseplay: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work! vehicle Cummins N14 (#1)

Beside that I haven't found the Error you mentioned in your 1st post.

**Comment by Tensuko** [comment]
Closed due to inactivity
