### ISSUE TITLE
FS19 Combi mode not working correctly

### ISSUE THREAD

**Issue by hell4copter** [Courseplay/courseplay#5893]
I cannot get the combi mode working. My tractor with a trailer is not going into the field to empty the combine. CP says that its triggering the "drive to combine" action but nothing is happening and the combine is getting filled. I have tried this scenario with the following versions:
Courseplay for FS19 v6.02.00047
Courseplay for FS19 v6.02.00046
Courseplay for FS19 v6.02.00045

The log file is from when I used the Courseplay for FS19 v6.02.00045 version. Then I just lost my nerve to try any more. 

[log.txt](https://github.com/Courseplay/courseplay/files/5060707/log.txt)

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ and #5272

**Comment by Tensuko** [comment]
Oh btw in 5272 got a Video that shows how it does work.
