### ISSUE TITLE
Create flipped copy of course. 

### ISSUE THREAD

**Issue by Marsfan** [Courseplay/courseplay#5894]
My apologies if this has been already asked, I cannot find it from some quick google-fu. 

Is there a way I can select a saved course and flip the direction of all of the waypoints?

As a simplified example, imagine I drove a course with only 4 waypoints: A->B->C->D. 
I would  want to make a new course for the tractor, that would instead drive D->C->B->A. 

Is there any way to do this without having to manually drive and record a new course?

**Comment by Tensuko** [comment]
We have a suggestion for this to load the course in reverse.
If you check the saved course, you could save the course you want to reverse with a new name, open the .xml and try a program to reverse the line order.

**Comment by Marsfan** [comment]
@Tensuko Cool. Glad to hear this suggestion is on your radar. 
I know that I can flip the course in the XML file, was just wondering if I somehow overlooked a in-game way.

**Comment by Tensuko** [comment]
Just combine Issues #4639
