### ISSUE TITLE
Connected Fields + combi mod

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/courseplay#5895]
Hello,

I notice that on the newest version, when you connect 3/4 fileds in one the combi mod has a problem with finding the harvester. You can choose the harvester but the tractor is all the time waiting in the "P" place and cant find the harvester.

**Comment by Tensuko** [comment]
What P place ?
I have 2 Fields connected and my Tractor finds my Harvester with no Problem...

**Comment by envikowaty** [comment]
"P" parking.

hmm Im try to download latest version but something is wrong - maybe thats my network problem. Would be possible to get an other link to download?

**Comment by Tensuko** [comment]
For a normal Mode2 (Combi Mode) Course you don't put any P position for anything.
Start and Stop are at the Field.
The only offizial downloadsource is here:
https://github.com/Courseplay/courseplay/releases/tag/6.02.00047
just download the .zip and place it into your Mods Folder.
It got 1MB is I haven't noticed any trouble to download it right now.

**Comment by envikowaty** [comment]
HMMM i dont need to put parking for Combi mode ? so looks like I read wrong guide ....

**Comment by Tensuko** [comment]
What guide did you read ?

**Comment by envikowaty** [comment]
hmm well i cant find a link now put it was made by one of polish youtubers. He use parking "P" as a place where the tractor is wating for the call

**Comment by Tensuko** [comment]
That won't work.
Tractor will wait at the Stop if you start it at a Waypoint or it will wait where it is if you start it with 'Unloading'.

**Comment by envikowaty** [comment]
yeah i notice that after your message. anyway all works fine without any problems, even with Harvesters downloaded from internet

**Comment by Tensuko** [comment]
Sounds good, closing this one then.
