### ISSUE TITLE
Cp mode 3 

### ISSUE THREAD

**Issue by donkey517** [Courseplay/courseplay#5896]
when setting up an overloader course after all is set the overloader does not recognize combine.  it shows combine in the list but just sits their with no active combine selected?

**Comment by Tensuko** [comment]
I don't get what you want so:
Same as Mode2, select a Combine in the List and start it (best with Unloading) and done...

**Comment by donkey517** [comment]
I do select a combine but nothing happens almost like it doesn't recognize I have tried 4 different combines 2 in game combines the overloader just sits there with no active combine even after I select it

**Comment by donkey517** [comment]
I guess you can not the drive the combine manually ill try that

**Comment by Tensuko** [comment]
Nope you can't.
Actual, the Combine must be driven by CP, else the Mode2 Driver doesn't know what to do.

**Comment by donkey517** [comment]
Gotcha yes that worked is there anything in the works to let the combine be driven manual that you know?

**Comment by Tensuko** [comment]
There was one who wanted to make it work but he kinda not done anything in the last 1-2 month so, no nothing in the work right now, sry.
Will close this one for now.
