### ISSUE TITLE
Köckerling Vector 460/620 

### ISSUE THREAD

**Issue by Flo1293** [Courseplay/courseplay#5897]
hallo Cp hat mit den Köckerling Vector 460/620 aus denn modehub ein Probleme  habe ein video das dass zeigt wer super wenn da ein fix kommt

https://youtu.be/9y2MT5Pc9Qw

**Comment by Tensuko** [comment]
Als aller erstes, neueste Version runterladen https://github.com/Courseplay/courseplay/releases

Wenn es dann nicht funktioniert:

logfile mit debugchannel 12 und 14.

Video mit den beiden channels wäre auch gut.

**Comment by Flo1293** [comment]
Hallo habe jetzt cp auf das aktuelle gebracht und der fehler ist noch da hir meine log und eine neues video mit debug 12 und 14 an 
[log.txt](https://github.com/Courseplay/courseplay/files/5078429/log.txt)
https://youtu.be/JthYtBVydEA

**Comment by Flo1293** [comment]
sorry war fehler

**Comment by Tensuko** [comment]
Was denn nun, was war der Fehler ?

**Comment by Flo1293** [comment]
das ich den bost geschlosen habe das meine ich

**Comment by Flo1293** [comment]
Kannts du schon was sagen zu den Fehler das Cp macht aus den neuen video ?

**Comment by Tensuko** [comment]
Nein, wird ein Problem mit dem Tool sein, ob wir da generell was machen können weis ich nicht.
So ein ähnliches Problem gab es schon mal, wundert mich das es hier wieder auftritt.

**Comment by RyanRoutine** [comment]
Ich habe das gleiche Problem, eigentlich ein wunderbarer Grubber. Als Laie gefragt, erkennt CP nicht das es ein gezogenes Tool ist ? Sieht so aus als wenn er damit umgehen will wie mit einem Anbaupflug.

**Comment by Omat1998** [comment]
Gibt es schon etwas neues? 
Ich habe das Problem leider auch

**Comment by Tensuko** [comment]
Mod Issue:
![fsScreen_2020_10_16_18_59_13](https://user-images.githubusercontent.com/27344744/96287103-b7c2fe80-0fe1-11eb-8652-630a47fe67fe.png)
Vanilla Grubber:
![fsScreen_2020_10_16_18_58_11](https://user-images.githubusercontent.com/27344744/96287118-be517600-0fe1-11eb-8703-feb0d557401f.png)

Müsst ihr den Modder mal kontaktieren, er soll sich an den Vanilla Grubbern orientieren.
