### ISSUE TITLE
edit the track

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/courseplay#5899]
Hello everyone,

just a question, is there any possibilty, to edit the route: for example from the silo to shop ? my tractor triggers the shop but some how drive little bit forward and miss the selling point/ramp

**Comment by andreasthu** [comment]
With the ingame course editor,
Press strg+e and edit it.
Look in the forum thread:
https://forum.giants-software.com/viewtopic.php?p=1283829
And the linked video:
https://m.youtube.com/watch?feature=youtu.be&v=ZC9jk23XVbM
Lg
Andreas
