### ISSUE TITLE
Drescher wird nicht angefahren beim Abtanken und man kann nicht mehr die Fahrzeuge auftanken.

### ISSUE THREAD

**Issue by GrabthorFS19** [Courseplay/courseplay#5900]
Hi,

Zum einen funktioniert das Abtanken der Drescher nicht (Abtanker fährt einfach nicht zum Drescher) und zum anderen kann man kein Fahrzeug (egal an welcher Tankstelle) auftanken. Nachdem man CP deaktiviert hat, kann man Volltanken und anschließend wieder CP aktivieren....geht, ist aber uncool. Es wird mit der neusten Version 6.02.00047 gespielt. Gespielt wird auf einem Server...

[log.txt](https://github.com/Courseplay/courseplay/files/5072173/log.txt)

Schonmal vielen Dank

MfG Grabthor

**Comment by Lustiger-Hubi** [comment]
Ich würde mal die Error´s aus deiner Log entfernen!

**Comment by GrabthorFS19** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5074335/log.txt)

Log-Update

**Comment by Tensuko** [comment]
Und sowas gehört nicht in den Mods Ordner:
Available mod: (Hash: 28fe290e7e5b703c651bbf0bb5870da7) (Version: 6.02.00047) FS19_Courseplay_6_02_47
Available mod: (Hash: a10ef755433521e99e4934f4ac9f3324) (Version: 6.02.00046) FS19_Courseplay_6_46

https://github.com/Courseplay/courseplay/releases
.zip Datei laden, nichts umbenennen oder umpacken, sondern nur in den Mods-Ordner und fertig.

**Comment by GrabthorFS19** [comment]
Schonmal vielen Dank für das Feedback. Habe jetzt die zip wie oben geschrieben im Modordner. Leider funktioniert beides trotzdem nicht. Hatte zum Test mal ein SP-Spiel nur mit CP aktiv gestartet. Dort ging das mit dem Abfahren. Demnach wird CP durch irgendein Mod gestört oder?

**Comment by Lustiger-Hubi** [comment]
Was verstehst du nicht unter ERROR??

Load mod: FS19_ROAD_TRAILER_massey_f
2020-08-14 13:02   Error: Specialization 'animatedVehicle' already exists for vehicle type 'FS19_ROAD_TRAILER_massey_f.kogelautoloadTrailer'!
Nimm den mal raus und das was Tensuko dir geschrieben hat!

**Comment by Tensuko** [comment]
Der Specialization Error stört CP herzlich wenig.
Es wird einfach daran liegen, dass es auf dem Dedi Server läuft.
Im Moment wird halt viel für den MP umgebaut und da kann es mal sein, dass eine Version nicht so richtig MP fähig ist...

**Comment by GrabthorFS19** [comment]
Dann warte ich einfach auf ein Update. Danke für Eure Mühen.

Hier nochmal ein Log, falls es hilft oder was auch immer. 

Danke

[log.txt](https://github.com/Courseplay/courseplay/files/5074721/log.txt)

**Comment by Tensuko** [comment]
Mode2 läuft auf Server.
