### ISSUE TITLE
Traktor wird immer langsamer

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#5902]
@Tensuko  
Wenn ich hier falsch bin bitte weiterleiten, Danke
Bitte auf die Uhrzeit achten!

Mein Traktor wird mit der Zeit immer langsamer von 18 km/h runter auf 13 km/h
Map: LS19_Yogiland_OY
Traktor: LS19_FendtPack_OY  1095 siehe Feld 17
mit Standard SeedHawk

[log.txt](https://github.com/Courseplay/courseplay/files/5075400/log.txt)
![18 Kmh](https://user-images.githubusercontent.com/48583507/90265721-42a54280-de53-11ea-95b6-c8a37a279231.png)
![16 Kmh](https://user-images.githubusercontent.com/48583507/90265740-49cc5080-de53-11ea-8253-7807ac1ccc13.png)
![14 Kmh](https://user-images.githubusercontent.com/48583507/90266331-1938e680-de54-11ea-80d7-a579220d13ba.png)
![13 Kmh](https://user-images.githubusercontent.com/48583507/90266157-de36b300-de53-11ea-9fd7-a50e0e4e3e1b.png)

Und sowas passiert auch schon mal öfter
![Screenshot (14)](https://user-images.githubusercontent.com/48583507/90265822-69637900-de53-11ea-9ae0-627e5f857a56.png)

**Comment by Tensuko** [comment]
Geschwindigkeitsverlust -> Traktor und vorallem den Pflug reparieren.
Und ich sag es gleich vorweg: JA der Gerätezustand HAT einfluss auf die Geschwindigkeit, wers nicht glaubt -> google GIANTS Forum. Die Diskussion hatte ich schon einmal gehabt.

Zu deinem letztes Bild:
Keine Ahnung was du da gemacht hast, Will der Drescher weiter arbeiten oder was hat der vor ?

**Comment by Lustiger-Hubi** [comment]
Schau auf dem Bild ist noch OK! Zumindest bei der Sähmaschine
Jetzt habe ich ja für die Log das Spiel speichern müssen und auch wieder neu gestartet!
Der Traktor läuft trotz allem mit 13 Km/h weiter!
Ich nicht CP lol 
Wenn ich den Drescher im laufendem Spiel, über die Option Garage Repariere, wird der Abfahrer andauert ausgeschaltet!
Und ich muss diesen immer wieder Starten (Abfahrer Starten) lustig

Ach noch was: Ich habe ja mal geschrieben, das der LKW mit Anhänger auf der FS19_DondiegoMap beides läd, wie ihr es jetzt zeigt, wie es geht! Auf der LS19_Yogiland_OY geht das nicht! Jetzt habe ich das Hofsilo der FS19_DondiegoMap in die LS19_Yogiland_OY eingebaut und siehe da funktioniert auch mit Anhänger!
Vielleicht schaut Ihr Euch das mal genauer an.
Danke

**Comment by Lustiger-Hubi** [comment]
Tensuko, 
Du hast recht! Der war ja Schrott!
Mach schnell zu hier, bevor ich mich hier blamiere!

**Comment by Tensuko** [comment]
Ok ich mach hier zu :) 
Zu deinen LKWs mit beladen etc, da wird es noch wieder ein update für geben, in der Hoffnung das wir es dann sauberer und zuverlässiger hinbekommen, bitte noch etwas geduld.
