### ISSUE TITLE
SimpleIC Frage

### ISSUE THREAD

**Issue by John-Deere89** [Courseplay/courseplay#5903]
Hallo 
wolte nur mal fragen ob nun CP mit SimpleIC kompatibel ist, da gabs ja früher Probleme und daher die frage ob das gefixt wurde.
Würde halt mods Probieren wollen die dies verlangen.
Wenn das nicht so ist auch kein Problem dann weis ich das aber wenigstens.

**Comment by Tensuko** [comment]
Das ist schon lange kompatibel, du musst nur die SimpleIC Funktion für außen und innen auf einer andere Taste legen, pro tipp: nimm die mittlere Maustaste. Nutze es schon lange.
