### ISSUE TITLE
Logfehler & Spielsbsturz

### ISSUE THREAD

**Issue by Vincent7991** [Courseplay/courseplay#5904]
Guten Abend,

bis gestern lief unser Spielstand reibungslos und ohne nennenswerte Logfehler. Heute hatte ich 3 neue Mods hinzugefügt:

- ReversingCamera (Möglichkeit, links aus dem Fenster nach hinten zu schauen)
- NMC_Griffin_UniversalPassenger (Griffin Scania)
- nmcModuleTrailer (Trailer passend zum Griffin Scania)

Und da begann der Wahnsinn. Aufeinmal Logfehler, Courseplay-Menü manchmal unsichtbar gewesen (Maus war sichtbar, aber man konnte nicht mehr auf das Menü zugreifen und ein Spielabsturz folgte (man selbst war quasi eingefroren aber der Traktor fuhr weiter gegen die nächste Wand, man konnte nicht mehr mit ESC in das Menü usw.).

Daraufhin die neu hinzugefügten Mods wieder deaktiviert aber die Logfehler bleiben. courseplaySettings.xml gelöscht aber Logfehler bleiben. Die neuste Version von CoursePlay runtergeladen aber da spielten die CP-Fahrer erst recht verrückt und deshalb wieder den 6.1 in das Spiel genommen.

Gespielt wird im MP, local gehostet. Bevor wir diese 3 Mods hinzugefügt hatten, lief alles Problemlos.

Liebe Grüße

[log.txt](https://github.com/Courseplay/courseplay/files/5077248/log.txt)

Edit:
Ich Trottel habe ganz vergessen, dass LS auch die Mods läd die zwar ingame deaktiviert sind aber trozdem noch im Ordner sind. Habe den ReversingCamera rausgenommen und ich habe keine LUA called stack errors. Wir zocken jetzt noch eine Runde und ich schaue mir die Log danach gleich an. Wenn sich das Problem erledigt hat, sage ich hier bescheid.

**Comment by Tensuko** [comment]
- MP
- alte nicht unterstützte Version

-> Geduld!

**Comment by Vincent7991** [comment]
Lag an den ReversingCamera Mod. Alles wieder gut!
