### ISSUE TITLE
Mode 3, overloaded waits at unload point

### ISSUE THREAD

**Issue by justushickey** [Courseplay/courseplay#5905]
Overloader driver waits at unload point indefinitely.  He will unload the combine fine, but sits at the waitpoint at the unload forever no matter what. Tried different cart, tractor, route. Nothing helps. Can you help me out?  Log below.

![courseplay](https://user-images.githubusercontent.com/69698954/90296429-69ff0e00-de59-11ea-9374-d5ad40e7c83b.png)

**Comment by justushickey** [comment]
I know the log is very messy, I was playing with things for over an hour to try and make something work.  I should add, I now have a highway tractor and the lead of a B-Train working flawlessly on mode 2.

**Comment by Tensuko** [comment]
1st: don't post a log like that, attach the log.txt anything else I kick out becouse it is unreadable and I don't want to scroll endless to read the comments.

About your Issue:
oh wow why do you use an Auger Wagon when you drive all the way to the silo ?
Not going to do anything about that, attach a normal trailer and use Mode2 or use Mode3 to overload into a Trailer wich then use Mode1 to bring it to the silo.
That what you want to do does not make any sence to me...

**Comment by justushickey** [comment]
On my phone it didnt give me the option to attach a file.  I will see about using a pc to attach next time. 

Also, I am combining on the same field as the silo is why I am not using a trailer to bring the grain from the field to the bin

Most importantly, it does the exact same thing whether it is a silo FillTrigger or a truck under the auger.  I will attach a log of when it is doing it over top of a trailer in the near future.
