### ISSUE TITLE
Köckerling Vector 460/620 

### ISSUE THREAD

**Issue by Flo1293** [Courseplay/courseplay#5906]
Hallo habe das schon mal gepostet habe aus versehen den alten  abschneit beendet sorry 

hallo Cp hat mit den Köckerling Vector 460/620 aus denn modehub ein Probleme habe ein video das dass zeigt wer super wenn da ein fix kommt

https://youtu.be/9y2MT5Pc9Qw  

habe jetzt cp auf das aktuelle gebracht und der Fehler ist noch da hier meine log und eine neues video mit debug 12 und 14 an
log.txt
https://youtu.be/JthYtBVydEA

**Comment by Tensuko** [comment]
#5897
mach im Original weiter.
