### ISSUE TITLE
Problem mit Beladung

### ISSUE THREAD

**Issue by TMac063** [Courseplay/courseplay#5907]
mein Kollege und ich spielen die Nordfriesische Marsch 4-fach Map mit Global Company- und Seasons-Mod im Multiplayer Modus mit dediziertem Server (Nitrado). (LS 19; V1.6.0.0)
Alles lief zufriedenstellend, bis plötzlich die Kipper/ Tankauflieger (Standard) keine Ladung mehr aus Silos bzw Tanks / Wasserschächten mehr annahmen.
Was drin ist lässt sich an den Silos abladen, aber Beladen funktioniert nicht. Optisch wird bei den Silos die Beladung angezeigt (Ladung fällt aus Rohr) aber der Kipper zeigt weder optisch eine steigende Ladung an, noch ändert sich die Ladungsanzeige (bleibt bei 0%).
Dies passierte sowohl in der V2.0, als auch in der neuen Version 2.1.
Wenn ich jedoch das aktuelle Savegame vom Server ziehe und als SP spiele, funktioniert alles einwandfrei. Daher vermute ich (als blutiger Laie), dass es nicht an der Karte selbst liegt.
Weitere Recherche ergab, dass die genutzte Version von CP (..000.47) wohl der Verursacher ist. Nach Rollback auf eine Vorgängerversion funktioniert es wieder.
[log.txt](https://github.com/Courseplay/courseplay/files/5078487/log.txt)

**Comment by Tensuko** [comment]
Es wird demnächst ein weiteres Update geben, dass die Trigger anpasst, bitte noch etwas geduld.
Wir hoffen das Problem damit in den Griff zu bekommen.

**Comment by arp77** [comment]
Schade, geht trotzdem nicht, muss ich mal alle Mods rausnehmen und gucken ob irgendeine die Lösung für dieses Problem verhindert.

**Comment by Tensuko** [comment]
Paar mehr Infos wären gut, Trigger, Kurs, Tools, Screenshots.

Sowas ist ein NoGo:
Available mod: (Hash: 462f6d11aa92c3928580b5af07e96f2f) (Version: 6.02.00016) FS19_courseplay
Available mod: (Hash: e69f025b79ca1a259281d47bc0eb468e) (Version: 6.02.00032) FS19_Courseplay32
Available mod: (Hash: d6f5fe8e3aa605dbce6cea0a6d70fb61) (Version: 6.01.00399) LS19_courseplay

Genauso wie mehr als eine Map im Modsordner, gerade wenn Maps voller Scripte sind:
Available mod: (Hash: a4c9fa2dbf74baf0745e50d41147f164) (Version: 2.1) FS19_NF_Marsch_4fach
Available mod: (Hash: c462f47ea112c7fb55ff8f4d651fe4db) (Version: 1.8) FS19_NF_Marsch_4fach_oG

Da ist ganz klar aufräumen angesagt!

**Comment by Stelli2k** [comment]
Hallo Leute, ich habe den selben Fehler wie TMac063.
Ich habe so etwas noch nicht gemacht, hoffe aber das die Bilder helfen. Spiele das Game erst 3 Tage.

![CP1](https://user-images.githubusercontent.com/69963419/90752513-c63db400-e2d7-11ea-963c-63a0f36ee660.JPG)
![cp2](https://user-images.githubusercontent.com/69963419/90752515-c76ee100-e2d7-11ea-9118-5a30f024f14c.jpg)

Ich finde die Mod echt klasse! Lob und Anerkennung von meiner Seite.
Wenn ihr noch etwas benötigt, gerne melden....

**Comment by Tensuko** [comment]
log.txt in die kommentarbox ziehen.
Am besten auch die vom Server.

**Comment by arp77** [comment]
Wir spielen auf der NF Marsch 2.8 mit Gräben.

[log server.txt](https://github.com/Courseplay/courseplay/files/5103030/log.server.txt)
[log client.txt](https://github.com/Courseplay/courseplay/files/5103031/log.client.txt)

**Comment by Tensuko** [comment]
@arp77 
ok deine log sieht nicht problematisch aus.
Das Problem mit CP im MP ist eben, dass nicht alles direkt funktioniert.
Wir müssen sehr viel umbauen und es wurde auch schon viel gemacht.

Das tritt nur im MP auf dem Dedi Server auf und nicht im SP sehe ich das richtig ?
Kannst du sonst testweise mal die Mod (Version: 1.0.0.0) FS19_fillTypeMassAdjustmentRealistic raus nehmen ?

**Comment by arp77** [comment]
@Tensuko 
Danke für Deine Antwort. Ich habe jetzt rausgefunden, das es den Dedi Server betrifft, hoste ich ein MP Game von meinem Rechner aus, mit allen Mods auf der NF Marsch 2.8, geht auch die Befüllung. Im SP gibt es auch keine Probleme. Habe auch die Mod mal rausgenommen, die Du meintest, aber hat nix gebracht.

**Comment by Tensuko** [comment]
Ok danke dir für die Rückmeldung.

**Comment by TMac063** [comment]
Oh ich werde aufräumen.
Danke für den Hinweis.
Auch wenn es evtl nur Kosmetik ist, da es momentan ja läuft.
Werde mich melden, wenn wir das Update probiert haben.
Vielen Dank für die Info und Antworten

LG
TMac063

**Comment by arp77** [comment]
@Tensuko 
Habe mir mal die Log von @TMac063 angeguckt und dann mal die .32 Version von Courseplay installiert, damit funktioniert es auch auf dem Dedi Server. Weil er ja was von Rollback schrieb, weiß zwar nicht genau, welche er jetzt drauf hat, aber nahm mal an,das es die letzt höhere aus der Log war.

**Comment by TMac063** [comment]
Jup das ist richtig,
wir nutzen momentan die ...000.32

**Comment by Tensuko** [comment]
Hilft aber nicht bei der Fehlersuche.

**Comment by TMac063** [comment]
Wie kann ich helfen?
hier die aktuelle log.txt
[log.txt](https://github.com/Courseplay/courseplay/files/5107716/log.txt)
