### ISSUE TITLE
Combi mode + unload grain

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/courseplay#5910]
Hello everybody, 

Hope you doing well,

Please find attached log.txt file with a bug (i think) for unloading grain in to silo.... the tractor is not stoping even it has a unload stop set up.

<script src="https://gist.github.com/envikowaty/e311319b411ee26bac930fb04f448875.js"></script>

hmm thats the link i think. Im using the last version of courseplay

**Comment by envikowaty** [comment]
ok i found the problem, trailer HW 80 has only left or right unload option = this options creat that the tractor is not stopping, with the trailer SEK802 all is ok.

**Comment by Tensuko** [comment]
side unload does work, not sure what you did there and how your course looks like and your link is not working.

**Comment by envikowaty** [comment]
> side unload does work, not sure what you did there and how your course looks like and your link is not working.

https://gist.github.com/envikowaty/e311319b411ee26bac930fb04f448875 here you go,

I also notice that the range of combi mode is hmmm small, on the bigger field like for example no. 20 Felsobrom (somethign like that) if you set up tractor just on the right and the combine is on the lef end there is a problem

**Comment by Tensuko** [comment]
Can you try V49 ?
https://github.com/Courseplay/courseplay/releases/tag/6.02.00049

**Comment by envikowaty** [comment]
> Can you try V49 ?
> https://github.com/Courseplay/courseplay/releases/tag/6.02.00049

Well or works fine on very very big field, now i will test a truck with the trailer ( if loading and unloading works )

**Comment by Tensuko** [comment]
Still improving loading and unloading, but basically it should work right now with .00055

Will close for now.
