### ISSUE TITLE
Savere lag when harvester calls vehicle on combine unload course

### ISSUE THREAD

**Issue by SlavaAlexeev** [Courseplay/courseplay#5913]
Lately my CP has been lagging on the combine unload course when the combine calls a vehicle.
It will lag down to like 5 FPS and the vehicle wont move to the combine and the lag stops if I stop the CP driver.
Is anyone else having issues like this and does anyone know a mod or something that can cause this???

**Comment by Tensuko** [comment]
That is Pathfinder calculation, thats normal.
The more complex the course the longer it takes.

**Comment by SlavaAlexeev** [comment]
Why is it sometimes only happening right as the vehicle gets to the
harvester?
