### ISSUE TITLE
Radladerkurs Fahr-/Keilsilos

### ISSUE THREAD

**Issue by BastiHRO** [Courseplay/courseplay#5914]
Hallo,
ich nutze das ClaasDLC und daraus die Radlader um meine Silos direkt in die BGA zu verbringen. Mit der Version "44" war noch alles gut. Ab der version "45" bis hin zu der aktuellen Version wartet der Radlader nicht mehr, um die BGA weiter zu befüllen. Der Radlader fährt immer weiter. Ich glaube dies ist ein Bug. Könnt ihr das bitte mal prüfen ;)
Die Log ist sauber, demnach keine ahnung was das ist...
Vielen Dank ;)

**Comment by Tensuko** [comment]
Genauer erklären bitte... was meinst du mit er fährt immer weiter ?
Er wartet nicht auf freie Kapazität bei der BGA oder ist das Silo leer ?
Details sind wichtig!

**Comment by BastiHRO** [comment]
Er wartet nicht, wenn der Füllstand der BGA erreicht ist. Er überfüllt die BGA, da er immer weiter den geladenen Kurs abfährt. Normalerweise wartet er vor der BGA, wenn diese befüllt ist, bis er wieder abladen kann.

**Comment by Tensuko** [comment]
@schwiti6190 Füllstandscheck ?

**Comment by schwiti6190** [comment]
@BastiHRO Könntest du mir ein Bild von der situation schicken. Ich kann mir darunter gerade nix vorstellen?

**Comment by BastiHRO** [comment]
Anbei die gewünschten Bilder zzgl. eines Videos. Er belädt die BGA (100.000 Liter) einfach immer weiter! In früheren Versionen wartete der Radlader immer vor dem Trigger, bis er die BGA wieder beladen konnte...

![fsScreen_2020_08_18_17_28_20](https://user-images.githubusercontent.com/63298481/90533195-74cae300-e178-11ea-908f-62c5a5421c1c.png)

**Comment by BastiHRO** [comment]
Hier noch das Video

https://1drv.ms/v/s!AnaXua95ccavfVuWgRLp6FNV1ug

**Comment by Tensuko** [comment]
Muss ich mir mal angucken. Das ist so eher auf den Boden gezielt und landet eher zufällig im Trigger und wenn der nichts mehr annimmt landet es halt auf den Boden.

**Comment by Tensuko** [comment]
Bei mir fällt nichts auf den Boden, aber ich ziele eben auch auf den Trichter wie es sich gehört.

**Comment by BastiHRO** [comment]
Der Trigger ist gross genug angelegt. Hat ja sonst auch funktioniert!

**Comment by schwiti6190** [comment]
Es wurde einiges an den Trigger bzw. mode 9 gemacht (siehe die Nutzung der Global Company Triggers), so dass leider nicht immer alles so klappt wie vorher. Es besteht die möglichkeit dieses anzupassen, ist aber mit Zeitaufwand verbunden und leider gerade nicht meine Priorität (MP, Triggers in mode 1,4,8 ...), also würde ich jetzt erstmal empfehlen gerade auf den Trigger zu zufahren oder eine ältere Version zu benutzen.

**Comment by Tensuko** [comment]
Combine Issues:  #6133
