### ISSUE TITLE
[function request] progress in first round with silage harvester

### ISSUE THREAD

**Issue by wertigoxxx** [Courseplay/courseplay#5915]
**There would be a function for the tractor to go next to the forage harvester, not behind it in the first round!
same as for the combine: off and on

picture attached!
thank you for your work!**

![InkedfsScreen_2020_08_16_08_48_02_LI](https://user-images.githubusercontent.com/65092037/90328960-fe27bd00-dfa0-11ea-82a2-ec96e9eea0f2.jpg)

**Comment by Tensuko** [comment]
Err yea there you go.. Reopen if there is a Issue...

**Comment by wertigoxxx** [comment]
you misunderstood something! this is not a working feature yet!
it was just a suggestion that pvaiko could do that too! :)

**Comment by Tensuko** [comment]
Will discuss this first, as it wont help on anything
