### ISSUE TITLE
Course with tractor and trailer for silage harvester not working

### ISSUE THREAD

**Issue by SPLESHER1** [Courseplay/courseplay#5916]
Hi!, i created course for driving with silage harvester then unloading it into bunker, and i cant even start created course, thats what log says
[log.txt](https://github.com/Courseplay/courseplay/files/5080185/log.txt)

**Comment by Tensuko** [comment]
Your FS19_Milchhof does some very weird entry in the logfile.

Beside that I have no real Idea, you could try throw out RealDirtColor

Else we would need more Information about the used Tools.

Also I don't know that this is:
2020-08-16 09:36 Error: Running LUA method 'mouseEvent'.
2020-08-16 09:36 AIMaxToolRadiusFix.lua(27) : attempt to index field 'spec_aiImplement' (a nil value)

@pvaiko is that something about your fix ?

**Comment by pvaiko** [comment]
That's not even in the Courseplay code, that must be coming from another mod, also the standard Giants code throws an exception:
dataS/scripts/vehicles/ai/AIVehicleUtil.lua(305) : attempt to call method 'getAIToolReverserDirectionNode' (a nil value)

Don't think this has anything to do with Courseplay.

**Comment by SPLESHER1** [comment]
Found fix, issue was making mod called Bemu front weight [https://kutt.it/BEMU](url)
