### ISSUE TITLE
mode 2

### ISSUE THREAD

**Issue by Tocik** [Courseplay/courseplay#5917]
The unloader can not drive up, stops in front of the combine.
![2](https://user-images.githubusercontent.com/65189100/90331221-7a2efe80-dfbb-11ea-8c9b-e9c0815b2599.jpg)
![1](https://user-images.githubusercontent.com/65189100/90331223-7bf8c200-dfbb-11ea-9dcc-df3c43b29b2d.jpg)

[log.zip](https://github.com/Courseplay/courseplay/files/5080362/log.zip)

**Comment by Tocik** [comment]
Another "mistake"
A truck drives up to a standing combine, but the trailer is at an angle. After filling, the truck drives back and tries to align the trailer. As a result, he crashes into the combine.
I tried to put the unloading on the go, that's what came of it.

![3](https://user-images.githubusercontent.com/65189100/90332079-8b2f3e00-dfc2-11ea-87f5-c3481cb7ac1a.jpg)

**Comment by Rocksteady27** [comment]
Yeah I have the same problem that the unloader stops in front of the combine. But it just happens with 1 combine the other one works fine.

**Comment by Rocksteady27** [comment]
Hey guys,
I am new in this forum nad I wanted to thank you at first for this great mod and your great work.
I have the same issue as Tocik reported. I tried a few things and found out, when the fruit destruction is turned off the unloader stops in front of the combine like in Tociks first pic. When the fruit destruction is on it works fine.
But I have the problem just on one specific field the other ones work fine.

Thnaks for your help and have a nice sunday.

**Comment by Tocik** [comment]
There is also such a problem...
The game log is the same.

![4](https://user-images.githubusercontent.com/65189100/91064797-67aa6a00-e638-11ea-89ab-e32424b012b8.jpg)

**Comment by pvaiko** [comment]
Will be resolved by #5985 and #5986.
