### ISSUE TITLE
uloading two trailers on left or right course play

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/courseplay#5921]
Hello everyone,

Could anyone help me with seting up the CP for two trailers (unloading lef or right) maybe any youtube move ?

**Comment by Tensuko** [comment]
No Idea what you want....
More details pls

**Comment by envikowaty** [comment]
Right.

When you start your game you have a green trailer which has a few unloading. If you unload the grain from the trailer through  Back the course play works perfect, but if you choose left or right option to unload the CP sometimes stop bigote unload point or just starts to unload and drives though the point. The biggest problem is when you have 2 trailers ( the green once) and you setup them unload through the side

**Comment by Tensuko** [comment]
oh I thhink I get it.
You mean the 'tipside' of the trailer.
Unload to the left/right/back to set it up.

Actually CP can't decide the Position, but you get teach it before start CP.
If you don't hit the Trailer, there is an offsetoption in the Menu with the Tractor Symbol. (8th Symbol).
You can try that one.

If that was not the case, a Video might be helpful on whats going on :)

**Comment by Tensuko** [comment]
Sry but we won't add control over the tipside.
