### ISSUE TITLE
Side and vertical corrections in mode 2 not working

### ISSUE THREAD

**Issue by SPLESHER1** [Courseplay/courseplay#5923]
Hi, i fixed non starting course, but now side and vertical corrections are not working in mode 2, i can adjust them but nothing happens, tractor with trailer is still too far from silage harvester pipe and all the time blocking

**Comment by schwiti6190** [comment]
Which harvester, where you using ? For now only the ones with a high reach are working, like the big Krone harvester.

**Comment by SPLESHER1** [comment]
i used Claas Jaguar from Claas DLC with "extra-long" pipe, but still my Fendt 724 with Strautmann trailer was stopping all the time, i tried setting vertical correction either on + and on - but nothing changed

**Comment by Tensuko** [comment]
Offset got no effect on those Harvester.
Only Krone BigX and RM from ModHub (GIANTS one) are working good.
I think I wrote it also in Wiki.

**Comment by SPLESHER1** [comment]
@Tensuko how about JD 9000 from Kemper pack by Giants? does it work with that silage harvester?

**Comment by Tensuko** [comment]
That is something special.... it can throw far enough, but they did something wrong or different on the Model itself so our ProximitySensor sits to far in the back.... this is rly frustating, not only to you but to us as well, as we have to deal with several problems even on GIANTS Vehicles...
But we are already trying to figure out how to make them all work (except the JD9000, wich is another case...)

**Comment by SPLESHER1** [comment]
@Tensuko one more question, how about stock ingame silage harvesters? are all 3 of them working fine with that offset thingy?

**Comment by Tensuko** [comment]
No.
Just the Ingame Krone BigX and this ModHub one:
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=126256&title=fs2019
