### ISSUE TITLE
Mode 2. Tractor dont drive to  combine

### ISSUE THREAD

**Issue by Flicher** [Courseplay/courseplay#5927]
Hey There.

I have been away from courseplay for awhile.

But i tried using Mode 2 for unloading the combine, where the combine was run by me also I tried when the combine was run by courseplay or the game helper

But the same result, the tracktor dont drive to the combine.

I can see the combine the i combine search menu, and I have set and X in the combine

But when I push drive course on the tractor, it's blinks in the buttom with, "No combine in reach" 

I tried i mod map and felsburn

I have followed guids on youtube and on forums.

Im using version 6.02.00048

Log:
https://gist.github.com/Flicher/d978441943a96a8f3ab96fbe11d026e3

**Comment by Tensuko** [comment]
#5272 https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ
only read those and watch the YT Movie linked in the Issue.
Only real 'how to Mode2' source.

**Comment by Flicher** [comment]
Thats the guide and video i have followed

**Comment by Zarkov2** [comment]
I was having this problem and removing the front loader (with a log fork) from the tractor solved it. Using the debug modes I could see it created a path to the combine, but never started driving. Without a front loader attached, it worked. This was with version 6.02.00047.

**Comment by Flicher** [comment]
> I was having this problem and removing the front loader (with a log fork) from the tractor solved it. Using the debug modes I could see it created a path to the combine, but never started driving. Without a front loader attached, it worked. This was with version 6.02.00047.

I only have tractor and trailer

**Comment by AndersMish** [comment]
Im having the same problem. On multiplayer tho. Haven't tried it on SP. Tried different tractors and different trailers..

**Comment by Flicher** [comment]
> Im having the same problem. On multiplayer tho. Haven't tried it on SP. Tried different tractors and different trailers.. 

I have only tried SP

**Comment by Dirk78** [comment]
Hi Guys,

I also have this problem, but only when I drive the harvester myself.
When I click "Request driver", there is also no reaction and at the buttom of the CP-Display "No combine in reach" flashes.

If both vehicles are running with CP, it works without problems, just like in the YT video linked by Tensuko.

**Comment by AndersMish** [comment]
I have both harvesters and tractors running with CP. Two different fields. I got it to work on one of them now. Don't know how.. But as Im trying to set up the other one, same thing happen..

**Comment by Tensuko** [comment]
To all of you, mixing SP and MP is problematic, also we don't know what Version you all use...
Did anyone trie the new V49 ?

@Dirk78 
Becouse it only works with CP driven Combine for now.
We know you all want it to work with manuel drive Combine too, but the priority right now is to get mode unloaders per Combine working without Crashing, we have something for it on the way, but it takes time.

@AndersMish 
The question is always, why it is not working.
There are some settings, but basically if you keep all settings on default, all you got to do is select the combine to unload and maybe wait untill the Pathfinder found a way, wich is a different Problem, but it gets less as soon as the Field is more empty.

**Comment by AndersMish** [comment]
Yup, Im using V49. Uploaded it to my server about 3 hours ago. 

My settings are on default. Except "stop during unloading" - ACTIVATE , "covers" - DEACTIVATE (because that was a bug aswell.) and "avoid fruit" - NO.

Now, all of a sudden, none of them are working. It worked fine on one of them for about 10-15 minutes..

**Comment by Tensuko** [comment]
Avoid Fruit off on Combine or Tractor ?
I would always keep it on for Combine to prevent Unloaders stop in the Fruit.
Now I would need the debuginfos why it is not working.
Channel 4 7 12 and 14 and maybe a Screenshot.

**Comment by AndersMish** [comment]
I've tried with fruit on for combine.

Channel 4: (TX 32)      leftOK: false; rightOK:false numUnloaders:0
                 (RSM 161) leftOK: true; rightOK:true numUnloaders:0

There's no info on any of the other channels..

**Comment by Tensuko** [comment]
Channels on, start drivers, let it run for a while, attach logfile.

**Comment by Tensuko** [comment]
Closed due to inactivity. There are several Issues for this, don't need so many...
