### ISSUE TITLE
Kollisionserkennung CP

### ISSUE THREAD

**Issue by BastiHRO** [Courseplay/courseplay#5928]
Hallo,
vielleicht kommt es mir nur so vor, aber hat CP keine Kollisionserkennung mehr? Vermehrt fällt auf, das Fahrzeuge, die einen CP-Feldkurs oder einen Silokurs fahren, absolut gar keine Kollisionserkennung mehr haben. In frühreren Versionen war dies nicht so schlimm. Vielleicht kann man dieses Problem ja nochmals angehen ;)

Vielen Dank für Eure tolle Arbeit!
LG Basti
- - - 
Hello,
maybe it just seems to me, but does CP no longer have collision detection? It is increasingly noticeable that vehicles driving a CP field course or a silo course have absolutely no collision detection at all. In previous versions this wasn't too bad. Maybe you can tackle this problem again;)

Thank you for your great work!
LG Basti

**Comment by Tensuko** [comment]
Keine Ahnung was genau du meinst in welcher Situation etc.
Mit so einer Aussage können wir nichts anfangen...

**Comment by BastiHRO** [comment]
Es fehlt einfach die Kollisionserkennung, egal welche Situation

**Comment by Tensuko** [comment]
Genauere Situation und vorallem welches Fahrzeug und Screenshot mit F5 oder ich mach hier zu, so hilft das kein Stück.

**Comment by Tensuko** [comment]
So das Thema wird woanders behandelt also mache ich hier zu.
