### ISSUE TITLE
mode3, bremst nicht mehr v 6.02.00048

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#5929]
hallo leute
der Überladewagen Fahrer bremst nun nicht mehr beim Haltepunkt zum Überladen, sodern läßt sich wieder ausrollen.
somit verpasst er den zu füllenden Kipper und rollt zu weit nach vorn.
ÜLW kurse funktionieren nun nichtmehr.
bei der vorigen version hat das noch gepasst.
lg
andreas

**Comment by Tensuko** [comment]
Kann nicht sein, da ich den ÜLW Modus im Moment ziemlich viel Teste im zusammenhang mit Triggerrework!
Logfile ?!

**Comment by andreasthu** [comment]
Mit welchen channels?
Bekommst du heute Nachmittag.
Fahrzeuge waren der claas axion960 (dlc) bzw der case magnum 380, beide  mit dem elmers haulmaster. 
Zielfahrzeuge der MAN mit dem Krampe SB II und der NH T8 mit dem Strautmann APERION 3401.
Klappte ja seit Version 0044 super.
Gestern jedoch, mit v 0048 fuhren (rollten) beide traktoren immer zuweit vor und verpassten den Anhänger.
Lg
Andreas

**Comment by andreasthu** [comment]
hatte vor der arbeit doch noch etwas zeit:
![fsScreen_2020_08_19_08_21_06](https://user-images.githubusercontent.com/24860501/90599983-15abb380-e1f6-11ea-8637-71f07b434142.png)
![fsScreen_2020_08_19_08_24_37](https://user-images.githubusercontent.com/24860501/90599997-1a706780-e1f6-11ea-842e-96f17f91b4ed.png)
beim T8 rollt er aus, beim MAN sogar noch weiter
die log mit channel 4,7,2u14:
[log.txt](https://github.com/Courseplay/courseplay/files/5094414/log.txt)

vor der 0048 hat alles gepasst
lg
andreas

**Comment by andreasthu** [comment]
sorry,
hab den fehler gefunden:
<useRecordingSpeed active="false"
scheint so, das sich das bei allen fahrzeugen beim update eingeschlichen hatte.
hab normal bei allen fahrzeugen "Geschwindigkeit wie beim einfahren eingestellt.
hab jetzt alle wieder auf
<useRecordingSpeed active="true" 
und nun klappt das Überladen wieder.
(war ja klar, wenn der ÜLW Fahrer mit 53km/h anrauscht kann er sich nicht rechtzeitig einbremsen)
lg
andreas

**Comment by Tensuko** [comment]
Ja das sollte eigentlich wieder auf default sein für wie aufgezeichnet und nicht max.
Da hatten wir den falschen default wert drin.
Ich mach hier zu, wenn noch was ist, meldest dich :)
