### ISSUE TITLE
Wendemanöver vor Feldinseln. / Turning manoeuvre off field islands.

### ISSUE THREAD

**Issue by RyanRoutine** [Courseplay/courseplay#5930]
Hallo, 

ich bin gerade im SP auf der MVP19 unterwegs. Wie werden die 3 Bahnen um Feldinseln fest gelegt ? Ein standard Fendt der 1000er Serie mit dem 7.7m Grubber aus dem Kverneland pack kommt mit den 5 Bahnen am Vorgewende gut zurecht. An Feldinseln aber hängt sich alles auf weil es immer nur drei Reihen sind. Kann ich dort auch 5 Bahnen festlegen oder das Wendemanöver verbessern ? 

![grafik](https://user-images.githubusercontent.com/69876306/90573386-a367ae80-e1b6-11ea-9b87-144d63926a45.png)

Hello,

I'm on my way to SP on MVP19 right now. How are the 3 lanes around field islands determined ? A standard Fendt 1000 series with the 7.7m cultivator from the Kverneland pack can cope well with the 5 lanes around headlands. But on field islands everything hangs up because there are only three rows. Is it possible to set up 5 lanes there or improve the turning manoeuvre ?

**Comment by Tensuko** [comment]
Man kann wieder schlecht was sehen.... Warum denn immer bei Nacht ?
Log mit channel 12 und 14, Situation nachstellen.
Screenshot mit Channel 12 und 14 bei Tag!

**Comment by RyanRoutine** [comment]
Ich habe mit dem Wendekreis und der Geschwindigkeit beim Wendemanöver ganz gut hin bekommen.
