### ISSUE TITLE
Manually driving combine

### ISSUE THREAD

**Issue by je700arel** [Courseplay/courseplay#5931]
Hello everyone, 
I love driving combine by myself but putting courseplay for the unloader. I just dowloaded version .xxxx48 and figured that the unloader only go to the combine when it's a courseplay driver and not when I call it. 
A while ago, I was using the .xxxx31 and it was working fine, but now it gets my game to crash. 
So I was wondering if there was a way to set the unloader to come to the combine with the .xxxx48 or what is the last version that let you do that(It doesnt bother me if there is no mode 3 on the version).

**Comment by Tensuko** [comment]
Only Versions before 6.02.X was possible to drive combine on your own, when you can live with several bugs of the old Mode2 driver, but that Version gets no more support from us!
Manually driven combine might come back later, but that is not a high priority rigth now.

**Comment by je700arel** [comment]
All right thank you
