### ISSUE TITLE
Pathfinder stay on own Field

### ISSUE THREAD

**Issue by hlwilly27** [Courseplay/courseplay#5932]
Guten Tag.
Bitte verzeit mir wenn ich Fehler mach bin als Schreiber neu hier.
Zum Problem.
Courseplay fährt einen Güllekurs (Dungen und Sähen) ab. Aufgefüllt wird mit Autodrive.
Die fahrt vom Feld wird von Autodrive übernommen und funktioniert einwandfrei.
Die Rückkehr aufs Feld wird von Courseplay übernommen. Dieser fährt einfach nur Geradlienig zum Punkt, wo die Arbeit unterbrochen wurde.

MFG Daniel

**Comment by hlwilly27** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/69896665/90623453-c45fec00-e216-11ea-822b-f9a1e4e3c8d8.png)
![Screenshot (2)](https://user-images.githubusercontent.com/69896665/90623580-f6714e00-e216-11ea-8c8b-7b9b0293a1b2.png)

**Comment by Tensuko** [comment]
Fruchtumfahrung aktiv ?

@pvaiko soll er nicht versuchen auf dem Feld zu bleiben ?

**Comment by hlwilly27** [comment]
Fruchtumfahrung ist aktiv.

**Comment by hlwilly27** [comment]
Beim Ladewagen ist es übrigens das selbe.
Habe schon mehrere Einsellungen versucht. Alles ohne Erfolg.

![Screenshot (4)](https://user-images.githubusercontent.com/69896665/90756198-5d0c6f80-e2dc-11ea-8eaa-501c84616b2b.png)
![Screenshot (3)](https://user-images.githubusercontent.com/69896665/90756439-ac52a000-e2dc-11ea-976d-0eb10e91d115.png)

**Comment by Tensuko** [comment]
Hast du mal ein logfile für uns ?

**Comment by hlwilly27** [comment]
Ich hab es jetzt noch mal mit sehr stark reduzierten Modordner versucht und jetzt funktionierts einwandfrei. Dann wieder alle Mods rein und wieder versucht. Funktionierte wieder einwandfrei.
Hier di Log. Weis aber nicht obs noch was bringt da hats ja wieder funktioniert.
[log.txt](https://github.com/Courseplay/courseplay/files/5105472/log.txt)

**Comment by hlwilly27** [comment]
Jetzt noch ein Versuch mit dem Ladewagen. Dann wieder das selbe Problem.
Modkonflikt? Wenn je welcher?

Hier noch mal di Log
[log.txt](https://github.com/Courseplay/courseplay/files/5105568/log.txt)

**Comment by Tensuko** [comment]
Ladewagen anderer Traktor als dein vorheriger test ?

**Comment by hlwilly27** [comment]
Erster Test war mit Güllefass und anderem Traktor.
Zweiter Testversuch War Ladewagen mit Traktor.

**Comment by pvaiko** [comment]
Ohne ein Log mit channels 7, 12, 14 können wir nix machen.

**Comment by hlwilly27** [comment]
Sry für die Verspätung.
Hier die log mit Aktiven Chanells 7, 12 und 14

[log.txt](https://github.com/Courseplay/courseplay/files/5142908/log.txt)

**Comment by hlwilly27** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/69896665/91586143-4063dd80-e955-11ea-8d4f-1219e067ffb6.png)

**Comment by Tensuko** [comment]
#5982

**Comment by Tensuko** [comment]
This should work in most cases now.
Closing this.
