### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by touzenesmy** [Courseplay/courseplay#5933]
Hello everyone,

Thank you all developers for the immense amount of time and work you put into this.

I saw this line with the latest update, sady I don't speak german and I used a translator to understand a bit

Drescher wird nicht angefahren beim Abtanken und man kann nicht mehr die Fahrzeuge auftanken. [#5900](https://github.com/Courseplay/courseplay/issues/5900)

Does that mean that combine auto unload works now in MP ? because it was never working for me

Thank you very much

**Comment by schwiti6190** [comment]
Hi,
I've changed a few things for mode 2, but I am not sure if it is completly working right now. I've done some basic tests on a local server. Give it a try and let me now if something still isn't working.

David
