### ISSUE TITLE
Strange behavior mode 2

### ISSUE THREAD

**Issue by touzenesmy** [Courseplay/courseplay#5935]
Hello,

I'm testing out new courseplay version with the MP fixes, first of all thank you very much because overall a bunch of things are working now <3

I will record one by one all strange behavior/remaining bugs I see and report them as good as I can.

Here is the first one, the tractor stops when the combine is empty, doesn't follow up anymore,

https://youtu.be/DngMODHV7nk

Then when the combi is full, it goes to unload it but does not move when the combi is at 50% as intended 

https://youtu.be/7xN86aU6_DQ

There is not much on the logs
```
2020-08-20 00:44 Game saved successfully.
2020-08-20 00:49 Game saved successfully.
2020-08-20 00:51 :09 [info lp382179] 8400 R (#2): Waypoint index 3421 reset to 6
2020-08-20 00:51 :09 [info lp382179] 8400 R (#2): AI driver in mode 3 starting at 5/6 waypoints (COURSEPLAY_NEAREST_POINT)
2020-08-20 00:54 Game saved successfully.
```

Also, you can see the combine did not reset the driver even if I stopped the driver for the Warrior & the combine and started again with the tractor

Any ideas ?

**Comment by Tensuko** [comment]
> Here is the first one, the tractor stops when the combine is empty, doesn't follow up anymore,

This is working as it should! We have a PR in the Line but that needs more tweaks. So this one is not an Issue!



> Then when the combi is full, it goes to unload it but does not move when the combi is at 50% as intended

Same for this, working as intended.
Combine Pipe was in the Fruit when reach 50% so it waits to make a pocket or likei n Video reverse out of Fruit.

Also I noticed you did a wrong course for Auger Wagons, the Waitpoint to tell where to unload into trailer is missing.

Overall, nice to see it is working as it should but not a single Issue here.

**Comment by Tensuko** [comment]
> Also, you can see the combine did not reset the driver even if I stopped the driver for the Warrior & the combine and started again with the tractor

What should be resettet, I don't get it.

**Comment by touzenesmy** [comment]
When I remove the courseplay for the warrior, the combine still see the warrior as it's driver

Can you please help, I do not understand this
`Combine Pipe was in the Fruit when reach 50% so it waits to make a pocket or likei n Video reverse out of Fruit.`

Thank you for your help !

**Comment by Tensuko** [comment]
Doesn't matter that Combine still see it as the driver.
When there is a new one rdy it will call the new one.

What you don't understand about this ?
Combine call Driver when at set % AND pipe is NOT in the fruit.
When pipe is in the fruit, it won't call the driver becouse obviously reasons.

**Comment by touzenesmy** [comment]
Alright, thank you very much
