### ISSUE TITLE
mode 10 - only left side bunker is filled

### ISSUE THREAD

**Issue by Veraseca** [Courseplay/courseplay#5936]
Hello,

During the filling of bunker containing two parts, I noticed that mode 10 only can work with the left side of the bunker.
When the route for the right side is ran, the tractor tries to go to the left side.

![fsScreen_2020_08_20_02_51_56](https://user-images.githubusercontent.com/57765427/90704318-74be0680-e290-11ea-9f36-8ffb54f0db6e.png)
[log - Copy (3).txt](https://github.com/Courseplay/courseplay/files/5100040/log.-.Copy.3.txt)

**Comment by Tensuko** [comment]
Yea it detects the left side.
What if you fill up the right side too and test it again ?

**Comment by Veraseca** [comment]
@Tensuko same issue happens when i filled the second bunker

![fsScreen_2020_08_20_11_04_51](https://user-images.githubusercontent.com/57765427/90750578-4e6e8a00-e2d5-11ea-90eb-cb98fe765b66.png)
[log - Copy (4).txt](https://github.com/Courseplay/courseplay/files/5101918/log.-.Copy.4.txt)

**Comment by Crinouche** [comment]
it is normal that he only goes to the left, because the tractor is going towards the silage pile closest to him.
In order for it to go to the right, the silage pile must be at the same level as the left side.
But you will always have the problem of the central wall which will block the tractor ...

**Comment by Tensuko** [comment]
Should be fixed as it didn't recheck for new silo, tested with same silo and worked fine.
