### ISSUE TITLE
I cannot change any settings in CP

### ISSUE THREAD

**Issue by Posmatrac** [Courseplay/courseplay#5939]
Hello, community,

i've been using CP for a while now and it's really a great script, but after a while i have to change some advanced settings here and there and it doesn't work for me now! Not since the beginning! But until now I didn't have to change anything in CP. The reason is probably my VGA monitor with a resolution of 1280 x 1024 (5:4). My FullHD monitor is unfortunately broken at the moment, so I use an old replacement monitor. The CP settings are all moved (see screenshots). Log is also included. I tested it on a new profile with Felsbrunn without other mods.

Is there a solution for this? or how can I adjust the window size myself? Autodrive and other scripts adapt to my monitor without problems.

Best regards.
Posmatrac

[log.txt](https://github.com/Courseplay/courseplay/files/5102307/log.txt)

![fsScreen_2020_08_20_12_00_31](https://user-images.githubusercontent.com/27627014/90759070-3819fb80-e2e0-11ea-8b34-56471e5b896b.png)

**Comment by Tensuko** [comment]
Weche Auflösung hast du im LS eingestellt ?

**Comment by Posmatrac** [comment]
Genau die Auflösung die Oben steht 1280 x 1024 (5:4) so steht es auch in den Grafik einstellungen im LS19. Sorry hatte nicht dazu geschrieben, das ich es aus dem LS fenster abgeschrieben habe. Und das ist auch die Tatsächliche einstellung die mein jetziger Monitor unterstützt.

**Comment by Tensuko** [comment]
Hmm muss ich mir dann mal angucken...

**Comment by Posmatrac** [comment]
Okay, alles Klar! Hast du schonmal für mich einen Tipp in welcher Datei zum beispiel die einstellungen gespeichert werden damit ich dort meine einstellungen vornhemen kann. Weil über den HUD klappt dies ja nicht bei mir. Alles drunter oder Drüber kann einstellen aber alles was im grauen bereich ist wo Links und rechts Q und E am ende steht, da kann ich nix anklicken. Seit dem ich gestern ein Update durchgeführt habe ist ja eine zeile neu hinzugekommen und seidem kann ich auch das zahnrad nicht mehr anklicken oben neben dem Trecker symbol.

**Comment by Tensuko** [comment]
Die Datei ist im savegame mit drin, aber die optionen tauchen erst auf wenn Änderungen gemacht worden sind bin ich der Meinung.
Könnte etwas komplizierter werden.

**Comment by Posmatrac** [comment]
Hi,

hast du dir das Problem schon anschauen können bzw. lösen können? Ich habe gestern die version 51 geladen, aber dort ist das problem immernoch vorhanden.

**Comment by Tensuko** [comment]
Nein habe ich noch nicht lösen können, viel Zeit habe ich dafür gerade nicht.
Du sagst du hast in anderen Mods diese Probleme nicht, z.B. AD, GPS, VCA ?

**Comment by Posmatrac** [comment]
Ja, genau AD, TSX, GPS, alles wunderbar. VCA habe ich nicht dort konnte ich es nicht testen. Guck einfach ab wie die Jungs dort es bei Ihren Mods mit der Auflösung geregelt haben :-D

**Comment by Posmatrac** [comment]
Hallo Tensuko,

na wie schaut es aus? Hast du schon was machen können bezüglich meines Problems? Habe mir die neuste version gerade gezogen und das Problem ist immer noch present ....

Würde mich über eine Antwort freuen.

**Comment by Tensuko** [comment]
Sry bin noch nicht dazu gekommen, ich muss mich da erst einarbeiten.
Gibt leider keine Dokumentation über diese GUIs...

**Comment by Posmatrac** [comment]
Ok, alles Klaro. Danke für deine Antwort.

**Comment by pvaiko** [comment]
@Posmatrac habe mit deiner Auflösung ausprobiert, sieht komisch aus aber ich kann es bedienen, alles funktioniert mit dem Maus ausser die in dem grauen Bereich aber wenn du eine Einstellung darüber anklickst kannst mit der Pfeiletasten auch hin. Wenn fertig auf Ok clicken (oder Enter), dann muss es funktionieren.

**Comment by Tensuko** [comment]
Ich bin bei etwas bei und hoffe das es damit besser wird, das dauert aber noch etwas.

**Comment by Tensuko** [comment]
So ich habe jetzt einiges angepasst und verschiedene Auflösungen getestet, es hat damit alles soweit geklappt, ich hoffe, dass es mit dem nächsten Release für dich dann endlich besser wird. Tut mir echt leid, dass es so lange gedauert hat...

**Comment by Posmatrac** [comment]
@pvaiko 
Danke dir für den tipp mit dem Pfeiltasten scheint zu klappen. Ich habe den LS lange nicht gezockt und auf der aktuellsten version bei mir v6.03.00016 sind neue einstellungen hinzugekommen und blöderweise ist die funktion Abschalten der Dügerfunktion der Sämaschine jezt im Grauen bereich da wo ich nicht klicken kann. Diese funktion ist mir aber wichtig weil meine felder bereits auf 100% gedüngt sind d.h. CP würde unnötig düngerstreuen. Aber mit der Pfeiltaste dadrüber gehen und dann nach unten schon konnte ich es abschalten. Scheint so das CP nun gespeichert hat nachdem ich mit enter bestätigt habe.

@Tensuko 
Kein Problem digga. Ich habe soweiso nicht lange gespielt von dem her habe ich auch nicht mehr drauf geachtet, aber wie oben beschrieben ist eine funktion in den Grauen bereich geruscht die ich benötige, deshalb habe ich mich nochmal gemeldet. Mit nächster version meinst du dann die nach 00017 kommt? weil die ist schon 6 tage alt und dein Post 3 tage.

**Comment by Tensuko** [comment]
Try with Version 6.03.00018 and report
https://github.com/Courseplay/courseplay/releases

**Comment by Posmatrac** [comment]
@Tensuko 
Unfortunately, it still does not work. I also noticed that there are much less settings now in the window (see screenshots). I have tested the version 00018 as well as 00019 but with both the same.

![fsScreen_2021_01_02_12_54_47](https://user-images.githubusercontent.com/27627014/103456853-5b2ad200-4cfa-11eb-8fbb-f1142ace8829.png)
![fsScreen_2021_01_02_12_54_53](https://user-images.githubusercontent.com/27627014/103456854-5bc36880-4cfa-11eb-9ba0-d454715c7ad9.png)

**Comment by Tensuko** [comment]
Less settings is correct, but I don't get why you settings keep jump up that high, I moved them lower to prevent this to happen and also tested some Resolutions.... Unbelievable....

Try this (you should get 7zip to do this the easy way):
- Open the .zip file
- go into the folder gui
- open the file guiProfiles.xml
- in Line 213 -> change it to <Value name="size" value="1800px **1000**px" />

It will increase the hight of the Box, but won't move anything else (wich would have been corrected too) but this should help you then... get Version .00020 first.

Test and report pls so I can figure something out that fits for all...

**Comment by Posmatrac** [comment]
Hello ,

I have changed the file you mentioned from 1800 to 1280px 1024px in the value area, It has already done a bit, but the lines are still over it. See screenshot. Do I have to change 1800px in every line where it appears?

Tested in a new clean MyGames folder without other mods or maps. Version .00022

![fsScreen_2021_01_05_16_39_19](https://user-images.githubusercontent.com/27627014/103666876-7c4b2700-4f75-11eb-914d-b3dcb1db5017.png)

**Comment by Tensuko** [comment]
No do not change it to your resolution...
I will give you the changed file tmr.

**Comment by Posmatrac** [comment]
Ok then I wait for the file

**Comment by Tensuko** [comment]
Ups my Comment was hiding the actual Line information, I edited it in the comment but anyway, here is the file:

[guiProfiles.txt](https://github.com/Courseplay/courseplay/files/5775947/guiProfiles.txt)

you got to load it 1st and save it as a new file with .XML at the end.
Or do the change as in my comment (now that you see what to change...)
If this works for you I will bringt it into master.

**Comment by Posmatrac** [comment]
Unfortunately, it still does not work... I would also have been happy if this was the solution ... I suppose I have to change in each file in the GUI folder the occurrence 1800 x 720 or 1800 x 800 to my resolution then it might work.

I have compared several times it looks exactly as you specified.

![fsScreen_2021_01_06_17_01_05](https://user-images.githubusercontent.com/27627014/103790688-d5808c80-5041-11eb-8fef-ac3bbd79b802.png)

**Comment by Tensuko** [comment]
Why on earth do your Buttons keep moving up ? This is insane...
I will try something else...

**Comment by Tensuko** [comment]
I did some other changes, replace the whole gui folder in your CP Version:
[gui.zip](https://github.com/Courseplay/courseplay/files/5777171/gui.zip)
Start to understand this a bit, but the template we had for this is hard to understand.
There are some 'containers' who gets moved arround and stick to each other.
I tried not to anchor the settings at the bottom left, adjusted some positions and hope they don't move to far up for your now.
Fingers crossed :)

**Comment by Posmatrac** [comment]
Something is happening ... but unfortunately in the wrong direction. Instead of sliding downwards. They slide further higher. Here is a new screen.

![fsScreen_2021_01_06_20_30_44](https://user-images.githubusercontent.com/27627014/103812222-7aa95e00-505e-11eb-82e7-67cc1e15e28d.png)

**Comment by Tensuko** [comment]
Thanks for your testing and patience...
If you don't mind to try out more, here is another try, I changed the origin again and moved the containers again in hope he find the center correct.
[gui.zip](https://github.com/Courseplay/courseplay/files/5781008/gui.zip)
Just an example how it looks on my page now:
![fsScreen_2021_01_07_11_27_36](https://user-images.githubusercontent.com/27344744/103881933-68b9d080-50db-11eb-9d01-47eb656517a3.png)

Btw wir können auch wieder zu deutsch wechseln, das mit try again war nur copy and pase Info von mir hehe :)

**Comment by Posmatrac** [comment]
Ob wir in Deutsch oder Englisch reden das relativ. Ich kann beides sehr gut. Ich hab auf Englisch gesprochen, weil du alles auf EN geschrieben hast. Es schien mir bisschen unhöflich dir auf DE zu antworten, wenn du auf EN schreibst. Und bezüglich des Danks: Ich habe zu danken das du dich meinem Thema angenommen hast und versuchst es zu regeln.

So wie es bei dir aussieht wäre auch mein traum hehe 

Aber mit dem aktuellen GUI order sind die zeilen weiter nach oben gerucht statt nach unden hin.
![fsScreen_2021_01_07_12_18_58](https://user-images.githubusercontent.com/27627014/103887687-c9e5a200-50e3-11eb-822f-c2d78fe7fab6.png)

**Comment by Tensuko** [comment]
Ich krieg das noch hin... irgendwann..... ich bleib dran!

**Comment by Tensuko** [comment]
Mal alles auf mitte gesetzt, bei mir siehts unverändert aus, ich hoffe bei dir zentriert er das nun auch alles richtig...
[gui.zip](https://github.com/Courseplay/courseplay/files/5781373/gui.zip)

**Comment by Posmatrac** [comment]
Na ja zumindest hat er jezt angefangen sich wider runter zu bewegen ein paar milimeter noch dann sollte es passen.

Hier der aktuelle stand:

![fsScreen_2021_01_07_14_03_39](https://user-images.githubusercontent.com/27627014/103895995-8c881100-50f1-11eb-84e9-eaf53380f4e2.png)

**Comment by Tensuko** [comment]
Kannst du noch mal in Zeile 213 in guiProfiles.xml auf das hier setzen:
Value name="size" value="1800px 1000px"
Da sollten die Settings und Buttons nicht wandern, aber der Background größer werden.

**Comment by Posmatrac** [comment]
So läuft es schonmal .. zwar kleben die Buttons direkt drunter ist nicht ganz Zentriert, aber dafür kann man mit der maus alles anklicken nur nicht mit Q und E auf der tastatur zwischen Trekker Einstellungen und Allgemeine Einstellungen Switchen, aber dafür läuft alles mit maus Prima.

Hier Screenshot
![fsScreen_2021_01_07_18_25_47](https://user-images.githubusercontent.com/27627014/103924367-34173a80-5116-11eb-9f84-58ea3807f8ff.png)

**Comment by Tensuko** [comment]
[gui.zip](https://github.com/Courseplay/courseplay/files/5783136/gui.zip)

**Comment by Tensuko** [comment]
Ich kann an sich ändern was ich will, ich hab die immer schön mittig.
Das muss halt an dem Format liegen, anders kann ich mir das bald nicht mehr erklären.

**Comment by Posmatrac** [comment]
Also im Prinzip sieht es bei mir jetzt mit dem neuen gui ordner so aus wie bei dir. Nur das OK und Zurück bei mir etwas höher liegt als bei dir, aber sollte denke ich nicht das problem sein alles ist wunderbar anklickbar. 

Nur Q und E zum umschalten funktioniert nicht. Für mich kein problem, aber ist es so gewollt? oder ist da was kaputt gegangen durch die änderungen?

Hier mal ein Aktueller Screenshot:
![fsScreen_2021_01_07_19_13_58](https://user-images.githubusercontent.com/27627014/103929436-9e7fa900-511d-11eb-9f3b-0023ecca05fb.png)

**Comment by Tensuko** [comment]
Q und E gingen noch nie, wenn das so passt ist super.

**Comment by Posmatrac** [comment]
Was mich persönlich betrifft funktioniert alles wunderbar. Sicher. muss man das mit der zeit beobachten wie sich das entwicklet, wenn immer meher funktion im menü hinzukommen. Aber ich denke das ist zukunftsmusik. Jetzt läuft alles. Großen Dank an dich, das du dich da reingehängt hast.

Wirst du das nun auch im Master übernhemen? Sodass ich nicht immer diese Änderungen manuell übernhemen muss.

**Comment by Tensuko** [comment]
Ja kommt mit auf Master und so viele neue Settings werden nicht mehr kommen, jedenfals sind keine geplant

**Comment by Tensuko** [comment]
Ist auf Master und sollte im nächsten Release mit drin sein.
Ich mache hier schon mal zu.
