### ISSUE TITLE
Hello, a problem with CoursePlay and Fuel, on server Dedi

### ISSUE THREAD

**Issue by purel81** [Courseplay/courseplay#5940]
greetings to all!
first I want to thank you for this mod! great helper!
now my problem: with this mod, I can not refuel at the gas station, I drive up, the inscription is that you can refuel, press R, the inscription changes to stop refueling, the sound of fuel sounds, but the fuel is not collected in the tank, the money is not removed.
server description: dedicated, 24/7.
mods cost season, autodrive, courseplay, dadisave (from modhab, for saving).
I tried to disable all the mods except for couseplay that works, it does not.
maybe there is a mode to check, there is nothing similar in the log now.

**Comment by Tensuko** [comment]
logfile from client and server pls

**Comment by Bandesss** [comment]
Hallo wir haben den selbern fehler seit der 49
[gamelog.txt](https://github.com/Courseplay/courseplay/files/5103588/gamelog.txt)

Auch ein Silo das alles kann, ladet seit dem nicht mehr richtig.
gruß

**Comment by samsunix** [comment]
Having exactly same issue with :Courseplay for FS19 v6.02.00049 / Courseplay for FS19 v6.02.00048

https://pastebin.com/ag4x8qtu

**Comment by Bandesss** [comment]
Hallo gerade beim Tanken komm das
[Time1903gamelog.txt](https://github.com/Courseplay/courseplay/files/5104406/Time1903gamelog.txt)
Hoffe das Hilft

**Comment by purel81** [comment]
Hello!
Here is my log, as they said, made.
with the same set of mods.

With CoursePlay:
[with_client.txt](https://github.com/Courseplay/courseplay/files/5104456/with_client.txt)
[with_server.txt](https://github.com/Courseplay/courseplay/files/5104457/with_server.txt)
Without CoursePlay:
[without_client.txt](https://github.com/Courseplay/courseplay/files/5104459/without_client.txt)
[without_server.txt](https://github.com/Courseplay/courseplay/files/5104460/without_server.txt)

**Comment by Tensuko** [comment]
@Bandesss da wir keinen Server haben können wir das nicht selber überprüfen.
Hier wurden einige Punkte angesprochen, was davon nun alles funktioniert, wissen wir nicht.
Wenn die Release Version da ist, würden wir uns über feedback freuen.

**Comment by Bandesss** [comment]
Ich kann euch gern einen Server zur Verfügung stellen ....

**Comment by Tensuko** [comment]
Naja wir pushen mal Wochenlang nichts und dann am Tag vlt 5 oder 6 mal und mal komplett ohne Mods und mal brauchen wir bestimmte Mods zum ausprobieren.
Wie würdest du dir das vorstellen ?

**Comment by Tensuko** [comment]
Du kannst aber auch die neue Version 50 jetzt selber ausprobieren und berichten, bitte neues Issue mit den gewohnten Infos :)

**Comment by Bandesss** [comment]
Danken das Tanken geht einwandfrei normales Diesel und Adblue

**Comment by purel81** [comment]
Thanks! The gas station is working!
