### ISSUE TITLE
Mode1, Load on Startpoint not working

### ISSUE THREAD

**Issue by smelborp-erom** [Courseplay/courseplay#5941]
I'm using a mode 3 driver to unload a combine harvesting on the field and then overload it onto a mode 1 driver waiting at the field edge that transports it into a silo. However the Mode 1 driver no longer waits at the start of the course like it used to, instead it drives the course like a mode 5 driver would without waiting to be filled, Now my question is am i doing something wrong setting up the mode 1 course or is this a known issue?

**Comment by Tensuko** [comment]
The 1st Waypoint after start must have some distanc.
So you press Record Course and drive straight before drive any turn.
Also you need to set any Fruit to load. I know its a bit unlogic but thats it for now, not rly a problem.

To be honest I haven't tested the load on start, but will do later.

**Comment by smelborp-erom** [comment]
So i need to set the same fruit i am harvesting, because i did that? I'll test again if it was me not driving straight in a minute, but i think i was. Thanks anyways.

**Comment by Tensuko** [comment]
You don't have to set the same fruit, but any.
I will have a check on that one later.
We been focused a bit more on the Trigger in the last tests, so missed to test that load on start...

**Comment by smelborp-erom** [comment]
Seems to be a problem with the mode 1 driver, just did a quick test, Ive got some screenshots here for you. Let me know if you need a log and wich debug channels should be activated.
Thanks for the quick help!
![20200820155016_1](https://user-images.githubusercontent.com/67479572/90778934-87baf000-e2fd-11ea-9c86-857ab4b07e2e.jpg)
![20200820155024_1](https://user-images.githubusercontent.com/67479572/90778938-88538680-e2fd-11ea-9860-380b09bf9dd2.jpg)

**Comment by Tensuko** [comment]
Confirmed, Mode1 Load on 1st Waypoint is broken, we check on that one.
