### ISSUE TITLE
Mist laden CP Fahrer wartet nicht auf 100% Füllung

### ISSUE THREAD

**Issue by Friendlyx** [Courseplay/courseplay#5945]
Ich habe einen Mistfeldkurs + einen Aufladekurs eingefahren, das funktioniert dieses mal auch alles aber der CP Fahrer fährt bereits los nach nur einer Schaufel Mist obwohl er bis 100% auffüllen soll. 

Log ist sauber CP Ver 6.02.00049
[log.txt](https://github.com/Courseplay/courseplay/files/5105861/log.txt)

**Comment by Tensuko** [comment]
Also Mode9 + einen Mode1 fahrer ?

**Comment by Friendlyx** [comment]
Es fährt ein Fahrer mit dem Miststreuer vom Feld zum aufladen zum Hof und hält an einem Wartepunkt an zum Auffüllen. Jetzt ist es egal ob ich einen CP Schaufelkurs fahren lasse, der eine Schaufel reinfüllt oder ob ich das selber mache. Nach der ersten Schaufel Mist im Streuer fährt der Fahrer wieder zum Feld und macht dort weiter. Dieses wiederholt sich auch immer bis er mit dem Feld fertig ist. Also funktioniert allles bis auf die filllevel Abfrage .

**Comment by Friendlyx** [comment]
wegen der Modes, da weiß ich immernoch nicht welcher welcher ist.

**Comment by Tensuko** [comment]
Stell bei deinem Miststreuer mal Mist laden ein und den min Wert auf 99%

**Comment by Friendlyx** [comment]
auch schon probiert und hilft nicht. Bei mir haben übrigens die beiden Pfeile zum einstellen der % keine Funktion. Geht nur mit dem Mausrad.
