### ISSUE TITLE
New Errors with v6.02.00049

### ISSUE THREAD

**Issue by SEETechWolf** [Courseplay/courseplay#5950]
Hello since we installed v6.02.00049 on MP Server we habe problems with:
- Manual Loading: Pressing R starts the loading animation but nothing is loaded -> Loading with Autodrive works as workaround
- The normal Helper is random available and not available.
- While Cureplay is active help menu shows H for deaktivating the Helper
- While driving on a Feld the help menue shows the option R for loading

I have the impression that I see options vom other mashines in the menu mixed with the maishin I'm using.
[log.txt](https://github.com/Courseplay/courseplay/files/5112192/log.txt)

**Comment by Tensuko** [comment]
Try https://github.com/Courseplay/courseplay/releases/tag/6.02.00051
And before make new Issues pls check if there are already existing one.
