### ISSUE TITLE
Nach "Beladung am Startpunkt" sofort wieder Entladung?

### ISSUE THREAD

**Issue by Oberlump** [Courseplay/courseplay#5952]
In der aktuellsten 00049 Version ist mir folgendes aufgefallen:

Ein Kurs, der Stroh aus einem Silo ins Strohkraftwerk bringt, funktionierte mit der vorherigen Version (Juni download) perfekt.

Jetzt ist es so, das er am Silo-Trigger belädt, ein kleines Stück weiter fährt und sofort entlädt (der Trigger be/entladen ist übereinander bzw. ist der Entladetrigger direkt hinter dem Beladetrigger). Es erscheint dann unten die Meldung "COURSEPLAY_UNLOADING_AMOUNT".

Einstellungen (NEU, gab es vorher so nicht) sind gesetzt auf:
Ladegut Stroh
count 20/20 (hier fehlt unendlich?)
max 100%
min 100%

**Comment by Oberlump** [comment]
Tritt leider in der aktuellsten Version (00065) wieder auf, kann nicht sagen seit wann wieder (oder obs überhaupt gefixt war).

Mode 1, am Startpunkt wird Stroh beladen...
![beladen](https://user-images.githubusercontent.com/70055950/95002802-6de91a00-05d8-11eb-9c69-a64a1a280b32.png)

...dann fährt er los und entlädt sofort wieder (mit dem gleichen Kurs der Strohverkauf zuvor).
![abladen](https://user-images.githubusercontent.com/70055950/95002803-6f1a4700-05d8-11eb-84d4-8995342a4d2d.png)

**Comment by Tensuko** [comment]
Abladetrigger ist zu weit weg vom Start, Bau den Kurs anders rum dann gehts.
Das wäre auch in der alten Version so gewesen.

**Comment by Oberlump** [comment]
Zu weit weg kann nicht sein, denn er ist (auch) genau UNTER dem Beladetrigger. So ging es bis vor einigen Versionen problemlos, habe mit der Route 3x das gesamte Strohlager verkaufen lassen. Hängt ggf. mit den neuen Triggern zusammen!?

Neue Route (genau anders herum) geht auch nicht. Er belädt, fährt ein kleines (!) Stück und entlädt sofort wieder. Das Problem ist halt, das der "Abladetrigger" bis fast ans Gebäudeende geht, und seit neuestem halt (wieso auch immer) direkt nach dem beladen wieder entladen wird, obwohl ich dort schon mehrfach das komplette Strohlager mit Courseplay habe verkaufen lassen.

Ich kann halt auch nichts am Start/Endpunkt ändern. Egal wie weit der Startpunkt ist, er belädt trotzdem in der mitte des Anhängers, auch wenn ich den Startpunkt weiter weg setze.

**Comment by Oberlump** [comment]
Kleines Update:

SO schräg startend klappt es dann wunderbar, weil der Trigger zum abladen dann wohl nur ganz kurz noch greift. Alles in allem etwas doof, ggf. könnt ihr ja grundsätzlich nach dem beladen eine gewisse Zeit (oder Meter?) definieren, die nicht direkt wieder abgeladen werden darf (was ja auch keinen wirklichen Sinn macht direkt nach dem beladen).

![abladenklappt](https://user-images.githubusercontent.com/70055950/95026376-3db18200-0691-11eb-8f47-7a479854205b.png)
