### ISSUE TITLE
LS19 Stürtzt ab bei Kursgenerierung

### ISSUE THREAD

**Issue by Speedyls19** [Courseplay/courseplay#5953]
Hat von euch schonmal jemand das problem gehabt wenn man ziemlich große Felder zbsp auf Kandelin map, einen Kurs erstellen  bzw einen Kurs generieren möchte das das spiel abstürtzt, bei kleineren Feldern funktioniert es einwandfrei aber bei größeren dauert es entweder ewig oder das süiel stürtzt komplett ab

**Comment by Tensuko** [comment]
Also ich mache hier erstmal zu, weil inaktiv.
Eigentlich sollte kein Absturtz passieren, wenn dann ist das Map/Feld bedingt.
