### ISSUE TITLE
zweiter Anhänger wird nicht beladen

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#5954]

**Comment by schwiti6190** [comment]
@Lustiger-Hubi Die sache ist ganz einfach willst du einen Anhänger der optisch richtig beladen wird oder einen Anhänger der so zuverläßig, wie möglich beladen wird. Ich bevorzuge das letztere, wobei das erstere nur ein Boni wäre der vlt. noch irgendwann kommen könnte aber für uns keine Priorität hat. Also nicht zu viel verlangen und abwarten oder sich selber mit der Lösung beschäftigen :)

**Comment by Lustiger-Hubi** [comment]
@schwiti6190 
Zitat: "oder einen Anhänger der so zuverläßig, wie möglich beladen wird. Ich bevorzuge das letztere"

Wenn du das letztere bevorzugt, dann ist das eben so! Ich kann es nicht ändern.
Dann kann auch auf dem Dach entladen werden!
Wie hier zwischen Führerhaus und Ladefläche:
![Original Map mit Zugmaschine](https://user-images.githubusercontent.com/48583507/90958847-27f84c80-e497-11ea-8928-fb8798108762.png)
Wobei der Anhänger wird gar nicht erst beladen wird, was sonst funktionierte!
![Original Map mit Anhänger](https://user-images.githubusercontent.com/48583507/90958816-f1bacd00-e496-11ea-8480-9b2c6f03f83c.png)
Auch lässt sich die Menge (Schieberegler 01-20 ) nicht mehr mit den hoch runter Pfeilen einstellen, nur mit der Mouse!
Ihr habt das Thema ja geschlossen, warum auch immer!
Ihr macht das schon.
Gruß Hubi

**Comment by schwiti6190** [comment]
@Lustiger-Hubi Also wird der zweite Anhänger gar nicht beladen, da haben wir dich falsch verstanden. Demnächst kommt ein Update dann kannst du am besten nochmal schaun ob es dann klappt. Was die Maximal, Minimal, runCounter regler angehn werden die nur noch mit der maus verstellbar sein. Wir haben schlicht keinen platz bzw. optionen mit unserem Hud da was anderes einzubauen.

**Comment by schwiti6190** [comment]
Ps. die Pfeil hoch und runter sind für die priorität bei mehereren Fruchtsorten.

**Comment by Lustiger-Hubi** [comment]
Und zwischen Zugmaschine und Ladefläche ist auch nicht der Hit
Gruß

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/releases/tag/6.02.00051
https://github.com/Courseplay/courseplay/wiki/Mode-1-Changes

**Comment by Lustiger-Hubi** [comment]
Funktioniert wieder.
Danke
Close
