### ISSUE TITLE
John Deere S700 Series Mouse Jumping

### ISSUE THREAD

**Issue by cinciforthewin** [Courseplay/courseplay#5955]
Whenever using courseplay with the S700 from this mod:
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=154287&title=fs2019

Whenever I try to use the gui for courseplay and this vehicle (or the S600 by the same maker), it jumps the mouse back to center screen.

**Comment by envikowaty** [comment]
Also there is few Fendt tractors (the big ones) which has same problem. - mod hub

**Comment by Tensuko** [comment]
If you know how to do this, do you mind open a new Issue with a Tutorial on how to do it ?
I will put it as sticky then.

**Comment by Bobster82** [comment]
> If you know how to do this, do you mind open a new Issue with a Tutorial on how to do it ?
> I will put it as sticky then.

It was discussed a while back: #4185

**Comment by NicholasSoares** [comment]
Here are the JHHG combines without IC and reworked animations to work with courseplay, and also some of the SIID old combines fixed also, its only the fix files to avoid any complications for me with the owners.

https://github.com/NicholasSoares/Courseplay-vehicles-incompatibility-fix

**Comment by cinciforthewin** [comment]
Others already answered it, but it does look like it does.  Looking at #4185 (which I missed when i tried searching for previous issues), the answer has been said and I understand why.

**Comment by Tensuko** [comment]
I guess can close this...
