### ISSUE TITLE
Drescher wird nicht angefahren beim Abtanken

### ISSUE THREAD

**Issue by JayT40** [Courseplay/courseplay#5957]
Courseplay for FS19 v6.02.00049
@pvaiko pvaiko released this 3 days ago

6.02.00049 Trigger and multiplayer fixes
Drescher wird nicht angefahren beim Abtanken ....... #5900

Funktioniert leider auf einem Dedi-Server nach wie vor nicht.  Man stellt den Abfahrer auf das Feld ein, wählt den Drescher aus , doch er fährt leider nicht los wenn der Drescher den Füllstand erreicht hat.

**Comment by Tensuko** [comment]
So bevor fragen kommen:
Die Beiträge habe ich gelöscht weil wir so mit den logdaten nichts anfangen können.
Debugchannel 4 7 12 und 14 einschalten, Farhzeuge starten und erstmal laufen lassen.
Dann die logdateien hier per drag and drop reinschieben, also anhängen als Datei.

**Comment by JayT40** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5146846/log.txt)

**Comment by JayT40** [comment]
[serverLog.txt](https://github.com/Courseplay/courseplay/files/5146848/serverLog.txt)

**Comment by Tensuko** [comment]
Gerade mit 00056 probiert und es funktioniert. Bitte selber mal testen.

**Comment by JayT40** [comment]
Auf dem DEDI SERVER getestet auch ? Weil bei mir geht es nach wie vor nicht, habe den Abfahrer alles eingestellt , also Feld ausgewählt Drescher ausgewählt. Dann setz ich mich in den Drescher, fange an und ab 50 % sollte der Abfahrer kommen wo aber keinen Meter zuckt. Wie gesagt, es nützt nix , wenn du selbst local auf deinem Rechner ein MP game startest, das ist am Ende es gleiche wie wenn du SP spielst, weil du auf deinem Rechner der Host bist, es muss auf einem dedi getestet werden wo man sich als client anmeldet. Ich kanns auch gern mit fraps mal Filmen, map ist felsenbrunn, Null mods im game, nur CP. Die einzige version wo noch läuft ist die 6.01.00399 und abwärts bis .... 396 ...aber eben auch mit Fehlern behaftet, aber da fährt der Abfahrer noch zum Drescher, diese spielen wir ja nun auch nach wie vor und warten immernoch, dass es irgendwann eine version wieder geben wird, wo der Abfahrer auf dem dedi server wieder läuft.

**Comment by JayT40** [comment]
[serverLogText.txt](https://github.com/Courseplay/courseplay/files/5241350/serverLogText.txt)

**Comment by Tensuko** [comment]
Ja Dedi Server

**Comment by JayT40** [comment]
Und den Drescher fährst du selber auch ?

**Comment by Tensuko** [comment]
Nein, das geht auch nicht im Mode2! Steht alles in #5272 und im Wiki.

**Comment by JayT40** [comment]
Ok, dann müssen wir bei der alten Version vorerst bleiben und können nur hoffen dass es eventuell wieder mit geplant wird und geht wenn Zeit dafür ist es umzusetzen ;- ) . Dankeschön für Zeit und Hilfe hier. Kann dann geschlossen werden dieser Beitrag.
