### ISSUE TITLE
Not able to unload silo at farm. 

### ISSUE THREAD

**Issue by blankmaster0** [Courseplay/courseplay#5958]
Modded map Lakeland Vale 3 by Stevie of Farming simulator mods.

After removing CP6.02.00047 issue resolved. Seems to happen with most other silos that arent base game silos.

Thanks for all the great work yall are doing!!!

https://i.imgur.com/XxgKx2X.jpg

**Comment by blankmaster0** [comment]
You can unload just fine. The numbers go up but when trying to unload you
get the animation and the sound but no material is added to the trailer.

**Comment by Tensuko** [comment]
MP Server ?

**Comment by blankmaster0** [comment]
> MP Server ?

yes

**Comment by Tensuko** [comment]
#5950
