### ISSUE TITLE
Im Verband Dreschen auf Dedi

### ISSUE THREAD

**Issue by Madox61** [Courseplay/courseplay#5961]
Nabend Zusammen!!

Sind auf nen Dedi Server unterwegs und möchten gern im die Drescher im Verband fahren lassen zwar wird der Kurs errechnet aber die Dreschen fahren trotz Einteilung mit Links und Rechts immer nur auf einer Linie. Bestimmen wir den Kurs für einen Dreschen muss der 2. Drescher an einen anderen Punkt angesetzt werden was mit der Zeit echt lästig wird und bei Feldern der größe von 20 - 56 HA ( Map Kandelin) nur noch nervt.

**Comment by Obsiana2019** [comment]
Moin @Madox61 

Habt ihr den Kurs auch gespeichert und beim 2. Drescher geladen?, wichtig wäre auch noch die Einstellung im Verband fahren. Auf dem Dedi konnte ich noch nicht testen weil die Aktuelle CP Version das Generieren von Kursen nicht zulässt bzw. ein Bug hat.

**Comment by Madox61** [comment]
Ja sicher sind das gespeicherte Kurse und beim 2. Drescher auch geladen beide Drescher sind auf 9m Schneidwerken unterwegs und sämtliche Einstellungen für den Verband wurden auch vorgenommen ( Fahrzeugverband aktiv und Entfernung zwischen den Dreschen auf 200-300m) und trotzdem folgt der 1. dem 2. Drescher statt auf die rechte Seite zu gehen. Generieren wir die Kurse für einen Dreschen und speichern sie funzt alles wunderbar.

**Comment by Tensuko** [comment]
Also im Kurseditor umstellen auf 'Fahrzeuge auf Kurs: 2' und wenn ihr einen Drescher startet geht nur der Versatz links oder rechts ?
Wie fährt er ?
Logfile mit channel 7 12 und 14 sollten hilfreich sein.

**Comment by Madox61** [comment]
Ok Danke werden das mal versuchen

**Comment by Nekromonger** [comment]
Haben genau die gleichen PRobleme. Alles eingestellt aber der Kursgenerator berechnet für beide Drescher die gleiche Linie. Der 2te fährt genau dem 1sten hinterher. Obwohl einer nach rechts und einer links eingestellt ist

**Comment by Nekromonger** [comment]
Also er legt bei der Kursgenerierung die beiden kurse genau übereinander.
![image](https://user-images.githubusercontent.com/53903203/91653216-db1c0380-ea9e-11ea-95cf-29f0def5bcf0.png)

das nächste problem; bei der version 52 kann man auf abfahrer starten klicken passiert aber nichts.

[log.txt](https://github.com/Courseplay/courseplay/files/5146425/log.txt)

**Comment by Nekromonger** [comment]
hier das log ich hoffe man kann was damit anfangen

**Comment by Tensuko** [comment]
Kurs nicht von der Ecke aus generieren!
Dann wird es auch gehen...

**Comment by Nekromonger** [comment]
Hallo, das versteh ich nicht ich geh einfach auf kursgenerator und klicke generieren. Der nimmt immer eine Ecke und Startet von dort.

Grüsse

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by Tensuko** [comment]
Multitool geht nun auch auf Dedi. Server.

Von der Ecke aus kann man ändern ingame man an eine andere Stelle fährt oder die Position auf der karte wählt (2te option von oben auf der linken Seite). Der neue Kursgenerator sollte damit aber auch anders umgehen.
