### ISSUE TITLE
CP editor not working in my game

### ISSUE THREAD

**Issue by romiadam1** [Courseplay/courseplay#5962]
Hi, I have a course play v6.01.00376. FS19 game version is 1.6.0.0(22022/30268).
If I open the control setup, there are mapped keys for course play editor commands except _**"Toggle CP Editor"**_ and **_"Undo last course edit"_**. So it looks that CP Editor is in the CP. When I click on the Toggle CP editor (to assign the key) the following message popup: _**"Axes to map must have been in the neutral/centered position before ths dialog was opened. If this was not the case, pres ESC, adjust the axis and strt the mapping again"**_
I do nott understand this dialog. What is it about? 
Whatever key I map to "Toggle CP editor", it is not worikng. 
 I have  mapped to _**"Toggle CP Editor"**_  CTLR+E keys. If I pres CTRL+E, nothing happen. If I press only E, the vehicle driver (player) get out from vehicle, because E is mapped for Enter/Exit the vehicle.  I have tried different key combinations and letters, still not working. ?  ?  ? I have tried even the CP version v6.01.00355. Still not working. The driver is in the vehicle, course is loaded and it is not in drive mode or record mode. It is exactly as it stated in the video.
Any sugestions what might be wrong? Thank you.

**Comment by Tensuko** [comment]
Actual Version:
https://github.com/Courseplay/courseplay/releases/tag/6.02.00049

**Comment by romiadam1** [comment]
Sorry for my late response. I was on holiday.
Tensuko, that was the problem. After replacing the course play by version 6.02.00049 the courseplay editor works well. Thank you very much for help.

**Comment by romiadam1** [comment]
Issue has been sorted out.
