### ISSUE TITLE
Frage

### ISSUE THREAD

**Issue by RudiBergfeld** [Courseplay/courseplay#5963]
Hallo,
was muss ich tun das der Abfahrer Vo Cp Wartet bis ihn der Frondlader befüllt hat? Ich habe den Abfahrer auf beladen am Startpunkt gestellt und das Ladegut ausgewält er fährt einfach weiter ohne sich zu befüllen lassen was mache ich falsch?

[log.txt](https://github.com/Courseplay/courseplay/files/5117201/log.txt)

**Comment by Tensuko** [comment]
Der Frontlader ?
Was möchtest du machen, welchen Modus benutzt du und am besten mal Screenshots anhängen von dem was du aufgebaut hast.

**Comment by RudiBergfeld** [comment]
Ich lade mit mit dem Radlader auf (was auch gutklapt). Ich möchte den Mist abfahren dann Abfahren mit CP, habe eine Strecke eingefahren und benutze den modus Beladen am Startpunkt. Habe das Ladegut mit hinzugefügt, der Fahrer hält aber am Startpunkt nicht sondern fährt weiter.
![fsScreen_2020_08_24_13_41_12](https://user-images.githubusercontent.com/10323527/91041701-c2c86680-e610-11ea-9638-ca90fe5697c8.png)

**Comment by Tensuko** [comment]
Ist mit der nächsten Version gefixt.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/releases/tag/6.02.00051
kein ladegut eintragen und den Wert wann er los fahren soll einstellen.
