### ISSUE TITLE
setttings.lua problem

### ISSUE THREAD

**Issue by wertigoxxx** [Courseplay/courseplay#5965]
there is a problem with the new version, clicking on the tractor settings the lua freezes! LOG attached!

[log.txt](https://github.com/Courseplay/courseplay/files/5118827/log.txt)

**Comment by Tensuko** [comment]
SP or MP ?

**Comment by wertigoxxx** [comment]
SP

**Comment by Tensuko** [comment]
Then I need more Details when that happened and what exact tractor settings you clicked.

**Comment by Tensuko** [comment]
For me only happens when on Mode2 or Mode3 then switch to Page for Offsets.

**Comment by wertigoxxx** [comment]
Yes, I have this mistake.  I experienced it in Mode 2.

**Comment by SevenFifty1996** [comment]
Hallo,
dann ist das Problem also schon bekannt. Sobald ich, egal bei was für einem Fahrzeug , die Einstellungen im Mode 2 veränder, stützt für das Fahrzeug Courseplay ab. Die Eingabemaske verschwindet. Auch beim Spiel ändert sich etwas . Dann ist plötzlich das Fenster links nicht mehr über die F Taste zu ändern, sondern über die Entfernentaste.
