### ISSUE TITLE
v6.02.00050 mode 2

### ISSUE THREAD

**Issue by Tocik** [Courseplay/courseplay#5968]
during operation mode 2 when you select specific settings of the courseplay mode disappears.
blindly choose other settings, it appears.
Perhaps this problem is just me?

**Comment by polosubtil** [comment]
@Tocik, just try new version, it was fixed https://github.com/Courseplay/courseplay/releases/tag/6.02.00051

**Comment by Tocik** [comment]
ОТЛИЧНО, СПАСИБО
