### ISSUE TITLE
Questions for translation

### ISSUE THREAD

**Issue by polosubtil** [Courseplay/courseplay#5969]
Hi guys,

Terrific work so far guys, I really enjoy following your progress !!! And your success. And I am quite glad @schwiti6190 joined your team :)

I have a few questions about some translations, as I don't understand the functions for some of them, or what they are suppose to describe

1. New thing since last released, in Mode1, when a trailer reaches a manual loading point (first point), I have now appearing "COURSEPLAY_REACHED_OVERLOADING_POINT"
=> Does that mean "Reach the loading point" ??? I suppose it does but I want to confirm, as overloading means other stuff too

2. With Mode1, in the driving settings (COURSEPLAY_PAGE_TITLE_DRIVING_SETTINGS), what is the purpose of these 2 settings ? I tried to play with them without understanding the point (the offset X only works on loading for example)
"COURSEPLAY_LOAD_UNLOAD_OFFSET_X"
"COURSEPLAY_LOAD_UNLOAD_OFFSET_Z"
![fsScreen_2020_08_25_00_08_13](https://user-images.githubusercontent.com/60451845/91102023-a7894580-e668-11ea-933b-ec0069545952.png)

3. Straw discharge on headland : Can you explain how it is supposed to work ? I though it was suppose to stop keeping the straw on headlands to avoid the baler to hit the bales once in the up and down rows. But it doesn't work like that when I try ;)

4. Mode10. Silo filling mode => Again, I have a few ideas but I can't be sure, can you explain what is the difference of behavior between those 2 :
"COURSEPLAY_MODE10_DRIVINGTHROUGH"
"COURSEPLAY_MODE10_REVERSE_UNLOADING"

**Comment by Tensuko** [comment]
COURSEPLAY_REACHED_OVERLOADING_POINT -> At this point something can overload into Mode1 Driver

COURSEPLAY_PAGE_TITLE_DRIVING_SETTINGS -> Not much to say, it is settings for Driving...

COURSEPLAY_LOAD_UNLOAD_OFFSET_X -> Adjust the X Offset to unload
COURSEPLAY_LOAD_UNLOAD_OFFSET_Z -> Adjust the Y Offset to unload
(never rly used those 2 Settings...)

COURSEPLAY_MODE10_DRIVINGTHROUGH / COURSEPLAY_MODE10_REVERSE_UNLOADING
 -> That is a setting to inform Mode10 Driver if a Mode2/Mode1 Driver fill the Silo by driving through or unload it in reverse

Starw discharge on headland:
You can turn on the straw discharge on the combine but have it off in CP so he won't turn it on when on headland but will turn on when on center part. That option should be expanded later for more control (on/only headland/off).

**Comment by polosubtil** [comment]
Thanks @Tensuko 
About the Offset, from what I tried, it only work for loading, not unloading (at least unloading with a trigger, maybe it works if you set a tip point)
