### ISSUE TITLE
Abfahrer bleibt nach Abladen an Abladestelle stehen

### ISSUE THREAD

**Issue by Oberlump** [Courseplay/courseplay#5971]
Folgendes Problem:

Gärreste laden an der BGA, Abladen am Klärwerk. Soweit sogut.

Leider bleibt der Abfahrer am Klärwerk nach dem Abladen stehen. Egal ob ich die Route mit "Abladepunkt setzen" erstellt habe oder ohne. Abladen klappt in beiden Fällen, aber der Abfahrer bleibt stehen.

Map: Südhemmern.

"Menge entladen" steht unten permanent, auch wenn Füllstand 0% erreicht hat.

Das einzige was hilft ist ein manuelles "Sofort abfahren".

Sowas schon bekannt oder bin ich einfach zu doof?

https://gist.github.com/Oberlump/c730f8bea72abedc4272cbd14a99879e

**Comment by Tensuko** [comment]
Welchen Mode benutzt du ?

**Comment by Tensuko** [comment]
(Version: 6.0.0) Suedhemmern_LS19
(Version: 2.8) FS19_NF_Marsch

Bitte nur eine Map im mods Ordner!

**Comment by Oberlump** [comment]
> Welchen Mode benutzt du ?

Den "ersten" - also Typ: Abfahrer (Beladung am Startpunkt). Hat bisher immer gut geklappt, habe so z. B. auch das Strohlager automatisiert leeren/verkaufen lassen.



> (Version: 6.0.0) Suedhemmern_LS19
> (Version: 2.8) FS19_NF_Marsch
> 
> Bitte nur eine Map im mods Ordner!

Okay, aber wieso? Ist doch die Regel, das man mehrere Maps (in verschiedenen Spielständen) spielt, sehe ich überall!?

**Comment by Tensuko** [comment]
Ich nehme an das Klärwerk ist fest verbaut auf der Map.
Das mit dem Strohlager klappt nach wie vor ohne Probleme ?



> Okay, aber wieso? Ist doch die Regel, das man mehrere Maps (in verschiedenen Spielständen) spielt, sehe ich überall!?

Nur weil man das überall sieht, heist es nicht, dass es keine Probleme machen kann und gerade die LetsPlayer die sich auskennen haben für jedes Projekt einen eigenen mods Ordner, und schieben die Dateien hin und her oder benennen die Ordner um.
Einige benutzen einen gut funktionierenden (nicht jeden X beliebigen) mods Switcher dier die Pfade zu den jeweiligen mods Ordnern ändert.

Grundsätzlich gillt: Nur eine Mod Map im Ordner, gerade wenn man Maps mit verschiedenen Scripten drin hat wie in deinem Fall.

**Comment by Oberlump** [comment]
Danke für die Aufklärung zum Thema Map!

> Ich nehme an das Klärwerk ist fest verbaut auf der Map.
> Das mit dem Strohlager klappt nach wie vor ohne Probleme ?

Ja, fest verbaut -Rest klappt nach wie vor, manchmal bleibt der Abfahrer etwas lange stehen nach dem Abladen, aber es klappt. Könnte mir vielleicht vorstellen, das es am Tanktrailer liegt, das Courseplay da irgendwie nicht erkennt das dieser leer ist?

**Comment by Tensuko** [comment]
Das etwas lange stehen bleiben kann am 'warten bis Trailer zugeklappt' liegen.
Welcher Trailer ist das genau ?
Kannst sonst auch mal einen anderen testen das wäre auch interessant.
Ein logfile mit debugchannel 2 an (Channel 2 an, Fahrer laufen lasse) sollte mehr Information bringen.

**Comment by Oberlump** [comment]
Trailer ist ein "Lizard MKS 32 MULTITrans" (war bei der Map dabei).

Hatte eben die neueste Courseplay installiert (6.02.00052), damit funktioniert auch das BELADEN an der BGA nun gar nicht mehr. Er fährt einfach durch (Log [hier](https://gist.github.com/Oberlump/d41cccab0444131d51c25b479a3f8d3f)). Ggf. könnt ihr damit ja etwas anfangen!?

Mit der 6.02.00051 Version geht das BELADEN aber wieder :-) Er fährt aber nach wie vor nicht weiter nach dem Abladen.

Habe ihn einmal mit "Sofort abfahren" nach dem Abladen weitergeschickt, er hat wieder beladen (war nicht voll, daher manuell "Sofort abfahren" gewählt), ist wieder zum abladen gefahren und dann wieder stehen geblieben nachdem er leer war.

Dazu habe ich [hier mal den Log](https://gist.github.com/Oberlump/850a5b904c1177df28e4a9e88dbdb683) mit Channel 2 an, hoffe das ist so richtig!

**Comment by Tensuko** [comment]
Wenn ihr eine log mit debugchannel postet (was ich gut finde) dann benutzt doch bitte die aktuellste Version.
Es hilft uns wenig zu wissen, wie es in einer alten Version abläuft...

Aber ich werd mir die Suedhemmern noch mal laden und ein paar Dinge ausprobieren.
Wichtig wäre was ihr eingestellt habe in den Ladeeinstellungen (der Button mit den 3 Schieberegler)

**Comment by Oberlump** [comment]
> Wenn ihr eine log mit debugchannel postet (was ich gut finde) dann benutzt doch bitte die aktuellste Version.
> Es hilft uns wenig zu wissen, wie es in einer alten Version abläuft...

Wollte ich, allerdings funktioniert dort ja schon das Beladen nicht. Teste aber gleich noch einmal ob das Abladen in der neuesten Version funktioniert (nachdem ich manuell beladen habe).

**Comment by Tensuko** [comment]
Ja wenn ich dazu komme werde ich mir die map laden und selber mal schauen was da los ist.
Frage: Warum min auf 20% ? Das heist er soll mindistens 20% laden bevor er los fährt ?
Ansonsten min mal auf 0% stellen und schauen was er dann macht.
Solange das nur bei der BGA so ist und alles andere funktioniert ist das schon mal sehr beruhigend :) 
Es kann sein, dass die BGA uns die gefragten Informationen nicht richtig meldet, dass müsste man noch ergänzen.

@schwiti6190 ich organisiere die Map und mach ein savegame fertig, fals du dann mal Zeit hast zu schauen.

**Comment by Oberlump** [comment]
> Frage: Warum min auf 20% ? Das heist er soll mindistens 20% laden bevor er los fährt ?
> Ansonsten min mal auf 0% stellen und schauen was er dann macht.
Der Wert hat keinen Einfluss auf die genannten Fehler. Auf 20% mindestens habe ich das mal testweise gestellt, auch falls das Silo fast leer ist, würde er das letzte mal (z. B. mit 30%) trotzdem automatisch abfahren. Aber war wie gesagt auch nur ein Test, mit 0% gehts auch nicht.

Wie gesagt, noch mal damit es nicht falsch verstanden wurde:

In Version 6.02.00051 funktioniert das Beladen am start, in Version 6.02.00052 nicht mehr (er fährt einfach durch). In beiden Versionen fährt er am Klärwerk nicht weiter nach fertiger Entladung.

**Comment by Tensuko** [comment]
Beladen am Start ist nicht das gleiche wie beladen am Trigger.
Beladen am Start geht nur wenn kein fillType eingetragen ist.
Beladen am Trigger nur wenn einer eingetragen ist.

Das heist in 52 kannst du an der BGA nicht mehr laden, aber in 51 ging es noch.
Wie gesagt, lass mich erstmal gucken...

**Comment by Oberlump** [comment]
> Beladen am Start ist nicht das gleiche wie beladen am Trigger.

Okay? Aber wenn START der Route = der Trigger (hier: BGA-Gärreste) ist, sollte es ja gehen. Nur: Was ist dann "Beladen am Start", wenn dort kein Trigger ist? Und wie soll ich denn an dem Trigger (= Start) laden, es gibt ja nur eine Möglichkeit den Abladepunkt zu setzen, aber nicht den Ladepunkt. Jetzt bin ich verwirrt.

> Beladen am Start geht nur wenn kein fillType eingetragen ist.

Ging aber wie gesagt bis zur Version 51 noch.

> Das heist in 52 kannst du an der BGA nicht mehr laden, aber in 51 ging es noch.

Genau.

**Comment by Tensuko** [comment]
Mode1:
Zwischen Stop und Start, wird ein Trigger gesucht, ist keiner vorhanden, wird am Startpunkt gewartet bis er durch Radlader, Drescher oder sonst was beladen wird (ohne aktives laden des Fahrers selber).

Die Regel die wir hinzugefügt haben ist:
Sind fillTypes eingetragen, suche den Trigger mit den fillTypes
Sind keine fillTypes eingetragen, fahre zum Start und warte dort bis du den eingestellten Füllstand erreicht hast.

Deswegen heist der Mode auch so wie er er immer hieß:
Beladen am ersten Wegpunkt **ODER** Trigger.

Du kannst mir schon mal nen Screenshot schicken wie dein Kurs beim beladen aussieht.

**Comment by Oberlump** [comment]
> Mode1:
> Zwischen Stop und Start, wird ein Trigger gesucht, ist keiner vorhanden, wird am Startpunkt gewartet bis er durch Radlader, Drescher oder sonst was beladen wird (ohne aktives laden des Fahrers selber).

Bei mir ist STOP kurz vor START, und bei START ist auch gleichzeitig der Trigger zum Beladen.

> Die Regel die wir hinzugefügt haben ist:
> Sind fillTypes eingetragen, suche den Trigger mit den fillTypes
> Sind keine fillTypes eingetragen, fahre zum Start und warte dort bis du den eingestellten Füllstand erreicht hast.

Okay, aber das sollte ja trotzdem so funktionieren, allerdings fährt er in 52 eben einfach am Start weiter anstatt anzuhalten (und wie in 51 den eingestellten fillType zu beladen).

> Deswegen heist der Mode auch so wie er er immer hieß:
> Beladen am ersten Wegpunkt **ODER** Trigger.

Also bei mir heisst Mode1 anders, nämlich: Abfahrer (Beladung am Startpunkt)

Und das suggeriert mir eben, das es, wie es schon immer so funktioniert hat und wie bisher immer genutzt: Man startet eine Kursaufzeichnung (= Start) und dort wird beladen (Beladung am Startpunkt).

> Du kannst mir schon mal nen Screenshot schicken wie dein Kurs beim beladen aussieht.

Okay, hier:

**Comment by Tensuko** [comment]
Ich sehe das Problem. Dein Kurs kann so nicht klappen....
Fahre deinen Trailer so hin, dass er mindestens mittig unter dem Trigger steht.
Starte die Aufnahme und dann fahre so, dass du erstmal nur gerade aus fährst, also am besten schräg in die BGA, bis der erste Wegpunkt nach dem Start erscheint, dann fahre deinen Kurs ab und stopp weit genug vor dem Trigger (so wie im Bild ist ok), aber so, dass wenn er zum Start fährt er auch durch den Trigger fahren würde.

Das Problem hier ist:
Du bist schon zu viele Wegpunkt weg vom Start, bevor der Trailer richtig laden kann.
Also kein CP Problem, sondern 'User Error', Kurs passt nicht :)
Ist ja nicht schlimm, muss man nur den Kurs etwas anpassen.
Kannst auch mit dem Editor (strg+numpad 0) hinschieben und WP löschen und mit F6 speichern.

**Comment by Oberlump** [comment]
Er steht MITTIG unter dem Trigger, wenn er auf der Route ist. Die Route ist im Grunde genau so, wie du sie beschrieben hast. Auf dem Screenshot bin ich nur manuell zur Route gefahren (für den Screenshot).

Und wie gesagt: Es hat ja auch immer prima funktioniert (Beladen bis 51).

**Comment by Tensuko** [comment]
Es ist nicht wie ich gesagt habe:
Die ersten Wegpunkte nach dem Start sind zu dicht am Start. Wenn er geladen hat, lag es daran, dass wir nicht mittig vom trailer geladen haben sondern am anfang.

Ich hab auch keine Lust auf weitere Diskussionen hier, es ist so, ich weis was wir gebaut haben da ich das Stunden lang immer wieder durchteste, ich kenne die Änderungen und weis wie der Modus funktioniert.

Ich kann dir noch anvieten, dass du mit deine Kursdaten schickst und ich das mit deinen Kurs probiere und zur not anpasse, aver einen Fehler von CP sehe ich hier nicht!

**Comment by Oberlump** [comment]
Wow, das scheint ja eine sehr sachliche, erwachsene Unterhaltung zu werden - Glückwunsch. ;)

Aber spaß bei Seite und damit du dir nicht auf den Schlipps getreten fühlen musst (wieso auch immer), und wir (bzw ihr) weiter kommen, denn nur das ist mein Ziel gewesen, hier gerne noch mal mit neuem Kurs. Startposition sieht jetzt SO aus:

SCREEN


Im Überblick sieht das fertige Werk am Ende so aus:

SCREEN


Er belädt nun allerdings den Trailer erst am ENDE des Trailers, nicht in der Mitte. Das ist schon etwas unglücklich (im Vergleich zur Version 51, wo er MITTIG geladen hat).

Übrigens nicht wundern, man sieht die Wegpunkte nicht (richtig) am Start (und im Gebäude), die gehen irgendwie beim Gebäude unter dem Gebäude weiter, aber das ist nur ein optisches Problem, vermutlich wegen dem Gebäude.

Das Problem mit dem nicht weiterfahren löst das natürlich nicht, das sieht übrigens so aus (nachdem er fertig entladen hat):

SCREEN

**Comment by Tensuko** [comment]
> Wow, das scheint ja eine sehr sachliche, erwachsene Unterhaltung zu werden - Glückwunsch. ;)

Weist du das Problem ist einfach, dass ich das schon eine ganze Weile mache hier und weis wie die Modi funktionieren, was wir gebaut haben und auch was wir geändert haben, auch der Unterschied zwischen V51 und V52 und den Grund warum es in V51 bei dir ging und in V52 nicht. :) 

Zur Erklärung:
Mode1 in V51, es wurde geladen, sobald er laden kann, sieht man an diesem Bild und ist auch in einigen Issues bemängelt worden.
Mode1 in V52 wurde so angepasst, dass wir bis zur mitte des Trailers fahren, nur wenn der Kurs so aufgebaut ist wie deiner, dann ist das Zugfahrzeug bereits zu weit raus in weiteren Wegpunkten und lädt nicht mehr sondern fährt durch.

Nun muss man etwas genauer sein was deinen Trailer betrifft, der Trigger in deinem Trailer scheint offensichtlich erst in der mitte an zu fangen, was das Problem noch verstärkt mit dem 'zu weit fahren' (hast es ja jetzt selber fest gestellt). Da wir nach erreichen des Trailer Triggers weiter fahren, wird bei em nun hinten geladen, solange es geht ist es gut und es gibt ja auch Tanktrailer, die ihre öffnung hinten haben, also ist das nicht so verkehrt.

![mode1diff](https://user-images.githubusercontent.com/27344744/91425078-f5fe3600-e85a-11ea-9ee2-66766aa516e7.png)



> Aber spaß bei Seite und damit du dir nicht auf den Schlipps getreten fühlen musst (wieso auch immer)

Nein auf den Schlipps getreten fühle ich mich nicht, aber ich diese Diskussionen echt nervig.
Wenn ich eben sage was nicht passt oder nicht richtig ist, bzw was ist gewollt und was nicht usw usw, warum immer gegen an gegangen wird. Ich teste jede Änderung immer und immer wieder durch, bin mit meinen Kollegen im direkten Kontakt.
Und wie du ja siehst hatte ich recht mit dem Wegpunkt und dem Trigger, das laden funktioniert ja nun, also glaub mir einfach :)





> Das Problem mit dem nicht weiterfahren löst das natürlich nicht, das sieht übrigens so aus (nachdem er fertig entladen hat):

Mich wundert, dass du da überhaupt entladen kannst, eigentlich ist dieser Trigger nur für Schüttgut und nicht für Flüssigkeiten.

**Comment by Oberlump** [comment]
Das "Problem" ist eher, das du hier (mit mir) eine Diskussion siehst, wo keine da ist: Ich versuche nur aufzuzeigen, was ich mache, wie ich vorgehe etc... Ich kenne weder den Code dahinter, noch eure Änderungen und sage auch gar nicht, was richtig und falsch ist. Ich versuche nur auf sachlicher und normaler Ebene etwas zur Lösung beizutragen, alles weitere könnt ihr ja einfach ignorieren. Aber nun sind wir ja schonmal weitergekommen.

> Zur Erklärung:
> Mode1 in V51, es wurde geladen, sobald er laden kann, sieht man an diesem Bild und ist auch in einigen Issues bemängelt worden.
> Mode1 in V52 wurde so angepasst, dass wir bis zur mitte des Trailers fahren, nur wenn der Kurs so aufgebaut ist wie deiner, dann ist das Zugfahrzeug bereits zu weit raus in weiteren Wegpunkten und lädt nicht mehr sondern fährt durch.

Okay, weiss natürlich nicht, wieso das wichtig ist, aber wenn das wichtig ist, das mittig beladen wird (und nicht am Anfang) dann wird das wohl gut so sein. Könnte mir nur bei verschiedenen Maps vorstellen, das es auf Grund der (engen) Bauweise manchmal nicht klappt. Hier ist es z. B. auch so, das meine Variante noch nicht immer klappt, weil der Trailer manchmal zu schräg ankommt bei der 2. 3. 4. x. Runde. Aber das wird am Ende vielleicht auch nur Übung sein.

> Nun muss man etwas genauer sein was deinen Trailer betrifft, der Trigger in deinem Trailer scheint offensichtlich erst in der mitte an zu fangen, was das Problem noch verstärkt mit dem 'zu weit fahren' (hast es ja jetzt selber fest gestellt). Da wir nach erreichen des Trailer Triggers weiter fahren, wird bei em nun hinten geladen, solange es geht ist es gut und es gibt ja auch Tanktrailer, die ihre öffnung hinten haben, also ist das nicht so verkehrt.

Hab mal geschaut, ich kann auch ganz am Anfang des Trailers schon beladen.

> Mich wundert, dass du da überhaupt entladen kannst, eigentlich ist dieser Trigger nur für Schüttgut und nicht für Flüssigkeiten.

Oookay - habe noch mal kurz geschaut: Einen anderen Trigger zum Abladen gibt es dort nicht :-O

Ich habe auch noch mal eine Testrunde aufgenommen und bin ganz mittig und anders herum über den Abladetrigger gefahren - mit gleichem Ergebnis: Er entlädt komplett (Entladen 0 of 38000) und bleibt stehen.

Übrigens wird der Trigger ganz normal vom Spiel ("Überladen starten" + Hinweis unten) erkannt.

**Comment by Tensuko** [comment]
> Das "Problem" ist eher, das du hier (mit mir) eine Diskussion siehst, wo keine da ist: Ich versuche nur aufzuzeigen, was ich mache, wie ich vorgehe etc... Ich kenne weder den Code dahinter, noch eure Änderungen und sage auch gar nicht, was richtig und falsch ist. Ich versuche nur auf sachlicher und normaler Ebene etwas zur Lösung beizutragen, alles weitere könnt ihr ja einfach ignorieren. Aber nun sind wir ja schonmal weitergekommen.

Ich hatte dir dein Problem mit dem Kurs beschrieben und deine Antwort darauf war eben das es bereits richtig ist und nein war es nicht und genau dort beginnen in den meisten fällen hier auf GitHub die Diskussionen mit diversen Usern, bis sie einfach mal selber das machen was ich ihnen gesagt habe und dann feststellen, dass es so ja klappt. Das ist leider meine negative Erfahrung hier. Aber gut lassen wir das.
Zum laden mit dem Trailer interessiert mich nur noch eins, denn:


> Hab mal geschaut, ich kann auch ganz am Anfang des Trailers schon beladen.

Mach mal bitte folgendes:
Fahre mit dem Trailer zum Trigger und fahre so weit drunter, dass du gerade so laden könntest. Bleib dort stehen und drücke mal F5, dann sollten viele Kästchen und Striche auftauchen, davon bitte mal einen Screenshot machen und hier posten.



> Okay, weiss natürlich nicht, wieso das wichtig ist, aber wenn das wichtig ist, das mittig beladen wird (und nicht am Anfang) dann wird das wohl gut so sein.

Es gab (oder gibt ?) ein Issue, in dem es hieß das nicht richt geladen wird usw und auch da war zu sehen, DASS geladen wird, also was war das Problem ? Es sah nicht hübsch genug aus... Uns war auch ganz klar die Funktion wichtiger, so wie du es in V51 hattest, aber ja es gibt Leuten denen ist es wichtiger das es gut aussieht... Nun fahren wir eben weiter richtung mitte (bzw einen Node vom Fahrzeug) und laden dann erst...


So zum abladen, wie gesagt, ich weis nicht in wie weit dort getrickst wird mit Trigger Überlappung usw, das ist etwas das ich mir dann angucken werde. Die Map habe ich schon, bin aber noch auf Arbeit.
Wenn dort noch andere fillTypes angenommen werden, die normal abgekippt werden, dann versuch bitte mal einen Kurs der dort was anderes abkippt, ob das so funktioniert wie es soll.

Es gibt auch einen GIANTS Bug der hier das Problem sein könnte(?):

Neues Savegame, stell ein normales Hofsilo für Weizen etc von GIANTS auf.
Hole dir einen Traktor mit Trailer, fülle über das EasyDevTool Zuckerrüben rein und versuch die in das Silo ab zu laden.
Es sollte nicht gehen und die Meldung 'x wird hier nicht angekommen' kommt.
Dann stell mal eine Siloerweiterung daneben, für Weizen usw, eben Getreide.
Tada, auf einmal kann man auch Zuckerrüben abladen ?
(Ich wüsste nicht das der bug mitlerweile gefixt wurde).

Also möglichkeiten zum 'manuellen Abladen' gibt es genug, ob das dann auch 'AI Driver' koform ist, ist eine andere Sache.

**Comment by Oberlump** [comment]
> Mach mal bitte folgendes:
> Fahre mit dem Trailer zum Trigger und fahre so weit drunter, dass du gerade so laden könntest. Bleib dort stehen und drücke mal F5, dann sollten viele Kästchen und Striche auftauchen, davon bitte mal einen Screenshot machen und hier posten.

Okay, hab mal "development" aktiviert und mit F5 sieht das dann so aus:

SCREEN


> Wenn dort noch andere fillTypes angenommen werden, die normal abgekippt werden, dann versuch bitte mal einen Kurs der dort was anderes abkippt, ob das so funktioniert wie es soll.

Leider nur zwei: Gärreste und den anderen Typen kenne ich gar nicht:

SCREEN


> Also möglichkeiten zum 'manuellen Abladen' gibt es genug, ob das dann auch 'AI Driver' koform ist, ist eine andere Sache.

Abladen klappt ja, nur das weiterfahren irgendwie nicht (automatisch).

**Comment by Oberlump** [comment]
So, ich wollte den Gülle Test wie von dir schon mal vorgeschlagen mal mit einem anderen Trailer testen, allerdings scheiterte das im ersten Versuch daran, das der mit dem Spiel original enthaltenen "garant Kotte TSA 30000" Trailer/Güllefaß nicht den Modus1 in Courseplay auswählen kann. Merkwürdig.

Mit dem Lizard Trailer + Gülle gehts dann wieder mit Modus1, allerdings fährt er auch mit Gülle nach dem Abladen nicht weiter.

**Comment by Tensuko** [comment]
> geht das mit einem kurzen dann vermutlich nicht. Oder?

Doch das ist kein Problem da er ja zwischen stop und start sucht und nicht nur am start lädt, vorraussetzung der filltype ist eingetragen.



> So, ich wollte den Gülle Test wie von dir schon mal vorgeschlagen mal mit einem anderen Trailer testen, allerdings scheiterte das im ersten Versuch daran, das der mit dem Spiel original enthaltenen "garant Kotte TSA 30000" Trailer/Güllefaß nicht den Modus1 in Courseplay auswählen kann. Merkwürdig.
> 
> Mit dem Lizard Trailer + Gülle gehts dann wieder mit Modus1, allerdings fährt er auch mit Gülle nach dem Abladen nicht weiter.

Kann sein das dem die nötigen specialisations fehlen.

**Comment by schwiti6190** [comment]
@Oberlump  ist dieses Problem noch aktuell ?

**Comment by Oberlump** [comment]
@schwiti6190 Teste später und gebe dann Rückmeldung.

**Comment by Oberlump** [comment]
DANKE: Das Abladen scheint nun mit der aktuellsten Version (00063) zu klappen, aber irgendwie ist nun das BEladen noch schwieriger geworden, klappt jedenfalls nicht mehr so wie oben mit @Tensuko abgestimmt (mit den Routen, die vorher funktioniert haben), aber da muss ich die Strecke noch mal neu einfahren, da hat sich scheinbar wieder etwas geändert.

**Comment by Tensuko** [comment]
Beladen klappt nach wie vor so:
- Trigger muss zwischen stop und start sein
- erste WP nach Start muss abstand zum Startpunkt haben

Viel genutzt und verschiedenen Stellen, klappt soweit gut und mache hier zu.
