### ISSUE TITLE
Progress along Silo Combine and not behind it

### ISSUE THREAD

**Issue by wertigoxxx** [Courseplay/courseplay#5972]
Hy guys! 

I would have a request that I would like to be able to stop progress along the forage harvester.  This would be a novelty! 🙂 In the first round, go by the ground if there are no trees.  I made a picture of what I mean!  Thanks in advance!

-

Ich hätte die Bitte, den Fortschritt entlang des Feldhäckslers stoppen zu können.  Dies wäre eine Neuheit! 🙂 Gehen Sie in der ersten Runde am Boden vorbei, wenn es keine Bäume gibt.  Ich habe ein Bild von dem gemacht, was ich meine!  Danke im Voraus!

![InkedfsScreen_2020_08_16_08_48_02_LI](https://user-images.githubusercontent.com/65092037/90328960-fe27bd00-dfa0-11ea-82a2-ec96e9eea0f2.jpg)

**Comment by Tensuko** [comment]
Won't do that as it won't solve the Problem we have right now with the low throw distance.
You will have the same Problem on more Situations.
