### ISSUE TITLE
Unload Combine on combined fields

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/courseplay#5977]
Hello guys,

After new update 051 i notice that the tractor has a problem to pick up grain from the harvester, please check the log:

https://gist.github.com/envikowaty/9d0e459eb9e8a08a2c018798d2a82e7e

**Comment by Tensuko** [comment]
And what Problem ?
Can you pls give a bit more detail ?

**Comment by envikowaty** [comment]
> And what Problem ?
> Can you pls give a bit more detail ?

The problem is, that when you start the CP straight after that CP stop working, no reaction from the tractor, but when the harvester is reached 100% then the tractor drives to it. I will try to test it with different trailer ( maybe that’s the problem)

**Comment by Tensuko** [comment]
So the Harvester is working and when you start Mode2 Driver, it stops again.
When the Harvester is full and you start it, then it is all fine ?

**Comment by envikowaty** [comment]
> So the Harvester is working and when you start Mode2 Driver, it stops again.
> When the Harvester is full and you start it, then it is all fine ?

Harvester works all the time, the problem is with the tractor and trailer. I just checked and the problem is on every trailer now. 
When I start mode 2 tractor is reaching the STOP point and that’s all, before it was driving to harvester to pick up grain. I also noticed that if the field is very big the harvester stops somewhere on the field and when it should drive to harvester the mode 2 is off - you need to press start again

**Comment by Misamangame** [comment]
I had similar issue with mode 3 on 48/49 version. Tractor worked fine but CP randomly shut off itself on stop sign, on the way to combine, even during unloading of combine.  I have to jump in and start CP again. It happened really randomly sometimes I started it and it stopped immedietely, but on other try it worked another half hour without any problems. I thought it was when I went to version 49, so I went back to 48 but problem was still there. At that time there was Global company and Additional field info mods update so I was a suspicious it might be because of it. Haven't played since last week but I can try to reproduce it tomorow. I'm playing on Wild west map and this was happening on field 56 which is about 75HA, but I guess size has nothing to do with it.

**Comment by Tensuko** [comment]
Are you playing on a MP Server or in SP ?

**Comment by envikowaty** [comment]
Ok, I run some test and I’m pretty sure that’s not a problem with addons/mods - I also went back to version 047 and the same problem is there. I remember that o that version there was no problem at all, so maybe my save game is some how corrupted ??

**Comment by Tensuko** [comment]
I would try to remove some script mods or get the EasyDevAddon from ModHub and go on the Vehicle Page and try Reload Vehicle.
Maybe something got stuck on the Vehicles.
If you find out if that is any settings from CP let us know.

**Comment by envikowaty** [comment]
Ok, i thnik i found the problem, when you creating a connected field i dont know why yet but some filed has a numer and (user) name; this fields looks like are corrupted and CP has a problem with the courses, check the screen:


fileds without this (user) works fine, so my question is how to delete that ?

**Comment by Tensuko** [comment]
That won't be the Problem, but I think what it is then, will check on that.
The (user) is just a textfile with field border coordinates that gets saved as a selected Number and will just add (user) behind it for Information that this is a custom Field.
But the Combinemanager might get a Problem if the Combine moves from the original Field to anotehr one, that would explain some problems. But I will try that one out.

**Comment by envikowaty** [comment]
> That won't be the Problem, but I think what it is then, will check on that.
> The (user) is just a textfile with field border coordinates that gets saved as a selected Number and will just add (user) behind it for Information that this is a custom Field.
> But the Combinemanager might get a Problem if the Combine moves from the original Field to anotehr one, that would explain some problems. But I will try that one out.

Is it possible to delete that ?

**Comment by Tensuko** [comment]
What do you want to delete there ?
There is nothing to delete....
Just wait me check on that and when we find the Issue we try to fix it.....

**Comment by Tensuko** [comment]
courseplayCustomFields.xml contains all User generated Fields if you was refering to that one.
Won't solve the Problem tho...

**Comment by Roma-85** [comment]
Good evening. I have a similar situation, the tractor does not see the combine in the custom fields. Have you found a cocooeto solution?

**Comment by Tensuko** [comment]
I do have custom Fields and no Issue in unloading them.
Remember that the List in your HUD is only a filtersystem, nothing to adjust there to get the Combine, especially not on custom Fields (we take a pure Fielddata for this iirc).
So no Issue here with actual Version 6.03.00003
