### ISSUE TITLE
Feldinseln in selbst eingefahrenen Feldrandkursen

### ISSUE THREAD

**Issue by RyanRoutine** [Courseplay/courseplay#5978]
Hallo,

ich versuche gerade auf der MVP19 die schwierigen Felder in etwas kleinere Stücke zu teilen. Dabei fahre ich den gewünschten Teil des Feldes ab und speichere ihn ab. Dann gehe ich in die Kursgenerierung und möchte daraus einen Kurs errechnen lassen. Soweit so gut, aber er erkennt die Inseln so nicht. Soll das so sein oder nicht ? 

Wenn ich auf dem Feld stehe und den Aktuelen Feldrandkurs berechnen lasse findet er alle Inseln problemlos. Auch im Autoscan funktioniert alles.

Das bild ist nur ein beispiel weil ich schon einige Stunden versuche das Problem zu finden. Ich habe auch schon zwei versionen des CP getestet. mit dem Aktuellen CPv6.02.00051 komme ich aber zum gleichen ergebnis.
[log.txt](https://github.com/Courseplay/courseplay/files/5124997/log.txt)

![grafik](https://user-images.githubusercontent.com/69876306/91199845-b589a580-e6fe-11ea-9ae6-d81b6f4fd1c0.png)

**Comment by Tensuko** [comment]
Das funktioniert auch nicht.
Mit dem Feld 16 kommt der Generator auch an seine Grenzen.
Du könntest hächstens das Feld richtig aufteilen mit einer Walze oder dem Maltool von GIANTS, dann den Feldrandkurs berechnen (im Menü wo man Abfahrer einstellt usw) und eine beliebige Nummer zuordnet. Dann kannst du die Nummer(User) ganz normal auswählen und einen Kurs generieren.

**Comment by RyanRoutine** [comment]
Okay vielen Dank. Dann sind wir hier fertig.

**Comment by Tensuko** [comment]
Okay. Eventuell krigt man das irgendwann nochmal anders hin :)
