### ISSUE TITLE
Is Courseplay release v6.02.00050 fixes this?

### ISSUE THREAD

**Issue by reanorius** [Courseplay/courseplay#5980]
Its hard to understand from the release notes if this release fixes the issue where I can't load anything into my trailers, refill the seeders/planters or refuel the vehicles. Is that issue fixed in MP in this release?

-added SeperateFillTypeLoadingSetting
-some more Trigger improvemts
-added some seperate MP Events

- Load one fillType in all Trailer
- Load different fillTypes in up to 3 Trailer/1 doublebin Trailer + normal Trailer
- Should wait at a Waitpoint to be fileld up (e.g. manurespreader)

**Comment by polosubtil** [comment]
Try v6.02.00051 I think most of it is fixed
https://github.com/Courseplay/courseplay/releases

**Comment by reanorius** [comment]
Sorry, are the issues I described fixed, or the ones I provided from the 6.02.00050 release notes are fixed? I was wondering about the issues I described:  **can't load anything into my trailers, refill the seeders/planters or refuel the vehicles.**

**Comment by polosubtil** [comment]
For me the first 2 are working now with v6.02.00051 (can't load anything into my trailers, refill the seeders/planters)
I haven't tried refueling yet, I noticed it was broken in the previous versions though

**Comment by reanorius** [comment]
Ok thanks much for verifying, I'll try tonight. CoursePlay rocks, was waiting for this for 2 weeks.

**Comment by Tensuko** [comment]
Well, those things take time especialy if ppl do it on their free time.
