### ISSUE TITLE
Kein Problem sondern Frage

### ISSUE THREAD

**Issue by Baker79** [Courseplay/courseplay#5981]
Hallo 

Cp funktioniert echt gut bis auf kleinere Sachen. DANKE

Meine Frage.
Ich möchte ein Course erstellen. Flüssigkeiten Gärreste.
Start BGA Gärreste beladen und weiter zu Gärrestelager abladen und wieder zum Start an der BGA.
beladen geht .
Aber das abladen will er nicht. Hab es mit abkipppunkt versucht und auch ohne. 
Hab ich ein denkfehler ?
Für eine erläuterung wäre ich Dankbar.
Map Schwarzepumpe.

MFG

**Comment by Tensuko** [comment]
Schau mal hier, ähnliches Problem. Hab da Anweisungen für Logfile hinterlegt:
#5971
