### ISSUE TITLE
Buy herbicide from the tank

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/courseplay#5984]
I notice that when you connect 2 course: 1 for spraying the field and  second to buy herbicide from the tank, the CP has a problem with buying. truck, tractor etc., drives to the tank but you get a message that is empty...., when you press manualy "R" it start to refill.

**Comment by schwiti6190** [comment]
Hi, could you post a logfile and a video or a picture of the situation you have described ?

**Comment by envikowaty** [comment]
I can post the logfile and some screen shots, well looks like my save game is coruppted because on the second field sprayer has a field working course and go to buy herbicide but doesnt want drive.

**Comment by envikowaty** [comment]
Link to course play save and savegame1

**Comment by Tensuko** [comment]
logfile is still requierd, best with debugchannel 2 active, let the Driver run the refillcourse and post that logfile.

**Comment by envikowaty** [comment]
> logfile is still requierd, best with debugchannel 2 active, let the Driver run the refillcourse and post that logfile.

well i tryed to make a nwe game and everything works perfect so looks like the old save is coruppted some how.

**Comment by Tensuko** [comment]
Hmm you could also try to reset your vehicles and try again.

**Comment by envikowaty** [comment]
> Hmm you could also try to reset your vehicles and try again.

ok, so i finished all my tests and still i see the same problem: see screenshot and log:
https://gist.github.com/envikowaty/28f199f122e5d1e4c63b4dab1dea9532

**Comment by Tensuko** [comment]
> logfile is still requierd, best with debugchannel 2 active, let the Driver run the refillcourse and post that logfile.

**Comment by Tensuko** [comment]
Your screenshot is not herbicide, it is fking dark ingame, a screenshot you do with a key on your keyboard and it will be in the screenshots folder of your FS, what kind of silo is this ?

**Comment by envikowaty** [comment]
Well I have problem with doing screen shots, check the link, that is the set of placeable refill stations which I’m using: https://www.farming-simulator.com/mod.php?lang=pl&country=pl&mod_id=125329&title=fs2019

**Comment by Tensuko** [comment]
I just tried the herbicide one and that one works just fine, just noticed that sprayer only refill front tank.
But I don't know what you try to refill there, it should work fine.
Try to set min on 0%

**Comment by envikowaty** [comment]
> I just tried the herbicide one and that one works just fine, just noticed that sprayer only refill front tank.
> But I don't know what you try to refill there, it should work fine.
> Try to set min on 0%

well it sometimes works sometimes not, when you start a game all works fine, after playing few hours it stops working.

**Comment by envikowaty** [comment]
@Tensuko  here you go: debug 2 ON

https://gist.github.com/envikowaty/2e39e4e6b8d4d610d1a5f3f05b7b868a

**Comment by Tensuko** [comment]
Can you try it again with .00053 and scroll down your min value to 0% ?

**Comment by envikowaty** [comment]
> Can you try it again with .00053 and scroll down your min value to 0% ?

With version 051 and 053 works perfect

**Comment by schwiti6190** [comment]
@envikowaty if this one ist still not working, pls create a new one.
