### ISSUE TITLE
Sehr unsauberes Arbeiten des Dreschers im Vorgewende

### ISSUE THREAD

**Issue by Strawberry93** [Courseplay/courseplay#5988]
Hallo Allerseits,

Ich weiß nicht ob dieses schon gemeldet worden ist, aber die Drescher bei Engen Vorgewenden Arbeiten die Ecken sehr Unsauber aus. Sie fahren nicht bis zum Feldrand sondern bleiben Vorher Stehen.Dieser müsste nach meinen Beobachtungen nur bis zum Feldrand fahren um die Ecken sauber Abzuschließen. Erweiter Einstellung des Tools Anheben ist auf Spät sowie Senken auf früh. 

Wenn ihr ein log Fail haben möchtet müsst ihr mir bitte sagen in Welchen Debug Modus ihr das haben möchtet.

**Comment by Tensuko** [comment]
Screenshots vom 'sehr unsauberen Arbeiten'....

**Comment by Strawberry93** [comment]
Also das ist nur beim Mais Aufsatz so. Beim normalen Schneidegerät passiert dies nicht.
![20200826194241_1](https://user-images.githubusercontent.com/16910900/91338240-ecca8600-e7d4-11ea-846c-38121de31ac1.jpg)
![20200826194146_1](https://user-images.githubusercontent.com/16910900/91338244-edfbb300-e7d4-11ea-877f-a642ab2b307f.jpg)
![20200826194224_1](https://user-images.githubusercontent.com/16910900/91338246-ee944980-e7d4-11ea-88c7-a346ece72ab2.jpg)

**Comment by Tensuko** [comment]
Was ist daran 'sehr unsauberes Arbeiten' ??
Stell die Überlappung fürs Vorgewende etwas größer und dann hat sich das.

**Comment by Strawberry93** [comment]
Habe ich alles Eingestellt. Aber Danke das man mich so abweist

**Comment by Strawberry93** [comment]
Der erste Screen zeigt es doch aber naja. Wenn man das nicht sieht und es direkt einfach Schließt

**Comment by Tensuko** [comment]
> 
> 
> Habe ich alles Eingestellt. Aber Danke das man mich so abweist

Und welche Einstellungen ? Wo ? Wieviel % ?

> 
> 
> Der erste Screen zeigt es doch aber naja. Wenn man das nicht sieht und es direkt einfach Schließt

Der erste Screen zeigt einen kleinen Witzel am Feldrand, welcher auch ein anderes Problem sein kann, z.B. eine unsaubere Feldecke, was ich hier vermute, da eine andere Ecke scheinbar sauber abgearbeitet wird.
Deine Aussage 'sehr unsauberes Arbeiten' ist schon ziemlich hart gewählt für so ein fitzel.

**Comment by Strawberry93** [comment]
Ich habe doch geschrieben, dass das Schneidwerk es sauber macht beim gleichen Feld und das der Maisplücker dieses Problem nur hat. Dieser fährt einstechen nicht bis zum Feldrand (Bild 3). Dadurch bleibt das Stückchen übrig (Bild 1). Ich stelle meine Course immer mit 20% ein sowie Tool Spät anheben sowie Früh Senken damit er das Ordentlich macht. Nur der Maisplücker hat dieses Problem.
