### ISSUE TITLE
Mod. 1 Traktor fährt nicht vor 

### ISSUE THREAD

**Issue by LamaiK** [Courseplay/courseplay#5990]
Beladung am Startpunkt mit Radlader z.b. BGA, Silage Laden auf Traktor mit zwei Anhänger.
Beim Beladen am Startpunkt ist nur ein Anhänger möglich der Traktor fährt nach Beladung des ersten Anhängers nicht vor damit der zweite Anhänger beladen werden kann.
Der Traktoren bleibt einfach stehen weil das Füllvolumen nicht erreicht ist.
Test habe ich mit der 6.02.00040 gemacht bei den beiden neuen 6.02.00051 + 52 hält der Traktor gar nicht erst an beim ersten Punkt.
Test mit Kalk im  Video zu [sehen.]([url=https://filehorst.de/d/dttlpoEr]Datei von filehorst.de laden[/url])
Log.txt mit Mod1

**Comment by Tensuko** [comment]
2 Traile beladen mit Mode9 ging auch noch nie, da wie der Name schon sagt, beladen am ersten Wegpunkt, der einzige Halt am Startpunkt ist. Wieviel Meter soll er vorfahren, damit der 2te Trailer richtig steht ?! Werden wir erstmal nichts dran machen.

Zwischen Version 40 und 52 ist ein riesen großer Unterschied und die Funktion ist komplett anders.
Damit am ersten Wegpunkt stehen geblieben wird, darf keine Frucht ausgewählt sein, dort steht dann oben 'Warten bis Füllstand erreicht' und das musst du eben so einstellen, wann er los fahren soll.

Wenn das in Version 52 nicht funktioniert, davon bräuchten wir dann logfile mit channel 2 und ein Video hilft auch immer.

**Comment by Tensuko** [comment]
Und eben noch einmal überprüft. Funktioniert problemlos.
![fsScreen_2020_08_26_20_57_26](https://user-images.githubusercontent.com/27344744/91344887-daede080-e7de-11ea-92f2-597320928708.png)

**Comment by LamaiK** [comment]
Danke für die Antwort.
Ja da habe ich etwas nicht Verstanden, dachte bei den neuen Einstellungen muss das Ladegut angewählt werden.  Hätte ich besser vorher gelesen, Sorry. 
Es funktioniert jetzt auch bei mir das er anhält.
Halt wie du Schreibst nur ein Anhänger, dachte hier es sei wie im CP 5, wo noch zwei Anhänger beladen werden konnten.
Und riesiges Dankeschön das ihr euch die Arbeit macht CP zu programmieren, ich liebe dieses Tool.

**Comment by LamaiK** [comment]
Danke für die Antwort.
Ja da habe ich etwas nicht Verstanden, dachte bei den neuen Einstellungen muss das Ladegut angewählt werden.  Hätte ich besser vorher gelesen, Sorry. 
Es funktioniert jetzt auch bei mir das er anhält.
Halt wie du Schreibst nur ein Anhänger, dachte hier es sei wie im CP 5, wo noch zwei Anhänger beladen werden konnten.
Und riesiges Dankeschön das ihr euch die Arbeit macht CP zu programmieren, ich liebe dieses Tool.

**Comment by Tensuko** [comment]
Kein Problem, ist ja auch ganz neu die Funktion.
Das man 2 Traile beladen konnte in CP5 da kann ich mich garnicht dran erinnern.
Erstmal ist der MP jetzt wieder mehr im Fokus, aber am Mode9 wollten wir auch noch mal dran rum schrauben, eventuell kann man in dem Zusammenhang was machen für 2 Trailer, aber das ist erste mal sehr neidrige Priorität.
