### ISSUE TITLE
mode 1 loading water doesnt work anymore.

### ISSUE THREAD

**Issue by candymant** [Courseplay/courseplay#5991]
mode 1 the driver doesn't stop to load water from the water tower. only if I press the loading key manually it stops and loads.
then it drives to my liquid silo it unloads but when it's empty he doesn't drive away again.
[log.txt](https://github.com/Courseplay/courseplay/files/5135986/log.txt)

**Comment by Tensuko** [comment]
Screenshot of your course pls.

**Comment by candymant** [comment]
![load](https://user-images.githubusercontent.com/47895720/91444537-2bb01880-e875-11ea-94e6-26f684016019.png)
![unload](https://user-images.githubusercontent.com/47895720/91444547-2f439f80-e875-11ea-8ecb-881a0b5ff5a1.png)

**Comment by Tensuko** [comment]
Same Problem as in the other Issue.
Place Trailer in the Trigger, start record and drive forwar untill the 1st waypoint appears, then drive the course normaly, or use the editor to get more distance between start and the 1st waypoint.
Also did you add the filltype into the filltype list ?
On your 2nd screenshot you choosed mode5, was that accidently or just to show course ?

**Comment by candymant** [comment]
Mode 5 is accidentel for showing course.

**Comment by candymant** [comment]
i have tried but it failed again.
![new load](https://user-images.githubusercontent.com/47895720/91479435-b575db00-e8a1-11ea-974b-6f920c0c7c2a.png)

**Comment by Tensuko** [comment]
I am sure you are not in the trigger yet. move start also a bit more forward and press F5 to check where the trigger is to load water.

**Comment by candymant** [comment]
starting point a little further.
![new load](https://user-images.githubusercontent.com/47895720/91490342-93d11f80-e8b2-11ea-9708-acd27b1a9244.png)

**Comment by Tensuko** [comment]
ok this is strange, that should work....
Sry to keep ask your for information step by step...
Can you make a logfile with debugchannel 2 active ?
Turn on channel 2 and start it before the tower, so it enters the silo, then attach the logfile.

**Comment by candymant** [comment]
here the log with debug channel 2
[log.txt](https://github.com/Courseplay/courseplay/files/5140517/log.txt)

**Comment by Tensuko** [comment]
Ok got the Problem.
Should be fixed with the next Version.

**Comment by Lustiger-Hubi** [comment]
Funktioniert bei mir auch nicht mehr!
Hat mal funktioniert.
