### ISSUE TITLE
 Refuel and drive off, the tractor does not start moving

### ISSUE THREAD

**Issue by ms96sc** [Courseplay/courseplay#5992]
Hello,

I have the problem that the tractor recognizes the Harvester but does not move to refuel when it is requested,

i play on the map durango

Thanks in advance

[log.txt](https://github.com/Courseplay/courseplay/files/5137896/log.txt)

(with the help of google translated)

**Comment by Tensuko** [comment]
Du darfst auch deutsch schreiben.
Also das heist Drescher abtanken klappt soweit, aber wenn er an einer Tankstelle vorbei kommt ?
Oder meinst du das 'rufen' vom Abfahrer wenn du einen Drescher fährst ?

**Comment by ms96sc** [comment]
Also ich Spiele auf der Map Durango, und die Funktion mit Drescher abtanken und abfahren funktioniert nicht entweder erkennt ehr den Drescher nicht oder er erkennt ihn fährt aber nicht los wenn er vom Drescher zum abtanken angefordert wird.Bei den Drescher handelt es sich um den Standart New Holland CR 10.90 mit den Quasar HS16.

**Comment by Tensuko** [comment]
Hast du den Drescher bei deinem Abfahrer ausgewählt, in #5272 und im Wiki sollte ein Video verlinkt sein wo man das sieht.
Ansonsten helfen screenshots und logfile mit den debuginfos 4 7 12 und 14.

**Comment by ms96sc** [comment]
Den Drescher habe ich wie im Video ausgewählt nur der Traktor bewegt sich leider immer noch nicht im Anhang sind die Gewünschten datein.
![Screenshot 2](https://user-images.githubusercontent.com/56652046/91598728-be2fe500-e965-11ea-8338-967f4e6f709f.PNG)
![Screenshot 1](https://user-images.githubusercontent.com/56652046/91598781-c12ad580-e965-11ea-8fe5-0812c7f9c48e.PNG)
[log.txt](https://github.com/Courseplay/courseplay/files/5143404/log.txt)

**Comment by Tensuko** [comment]
Das Issue ist recht alt und naja was soll ich sagen bisher hat es immer gut funktioniert, wir sind auch ständig dabei etwas dran zu verbessern.
Mache hier erst mal zu.
