### ISSUE TITLE
Vehicle speed setting is not used.

### ISSUE THREAD

**Issue by VergylTantor** [Courseplay/courseplay#5994]
When the vehicle is traveling in the field it is not using the Field Speed setting and travels at 14 mph. This happens in Mode 2 and normal field work.
[log.txt](https://github.com/Courseplay/courseplay/files/5143232/log.txt)

**Comment by Tensuko** [comment]
cruise control on max ?

**Comment by VergylTantor** [comment]
Yes
![Screenshot (6)](https://user-images.githubusercontent.com/39446775/91592629-7046bd00-e924-11ea-9bbe-17328acbc701.png)

**Comment by bjt3833** [comment]
From my experience, at least when set to MPH, it is does somewhere close to half of that as the max. To go 25mph in the field I have to set it to 49mph. At first I thought it was just using KPH still but the math doesn't check out there for it to be.

**Comment by VergylTantor** [comment]
I noticed that as well. I forgot to add it to the the issue report.

**Comment by Tensuko** [comment]
I think this one is kph/mph Error, as in #6041
Will close this one as duplicate.
