### ISSUE TITLE
Reverse Bunker Unloading Issue

### ISSUE THREAD

**Issue by GeorgeEarslight** [Courseplay/courseplay#5995]
Issue when reverse unloading chaff.

- The driver correctly figures out he needs to move forward a bit and calls `driveInDirection` with the correct forward waypoint in front of the tractor
  - https://github.com/Courseplay/courseplay/blob/91b83fbf15e39e39f4dd6c218dae7e95e949d9ae/AIDriver.lua#L1073-L1079
- Does its callculations and calls `updateWheelsPhysics `with `self.lastSpeedReal=0,  acc=1, allowedToDrive=true`
  - Giants scripts, AIVehicleUtil:163
  - `WheelsUtil.updateWheelsPhysics(self, dt, self.lastSpeedReal*self.movingDirection, acc, not allowedToDrive, true)`
- Runs a bunch of checks on `updateWheelsPhysics` and returns nil
  - Giants scripts, TSX_EnhancedVehicle:1436
- Gets stuck there waiting?

![image](https://user-images.githubusercontent.com/30686125/91593396-bc1b5580-e968-11ea-85b8-579fb59c5376.png)

**Comment by Tensuko** [comment]
Same Issue with 'unload here' waypoint ?

**Comment by GeorgeEarslight** [comment]
Can you tell me the issue #number so I can check and tell you?

**Comment by Tensuko** [comment]
Not rly an Issue, I am just asking if you have the same problem if palce an unload here waypoint :)

**Comment by GeorgeEarslight** [comment]
Ah OK let me check

**Comment by GeorgeEarslight** [comment]
It works fine with the unloading point, seems like I've forgotten the correct course for bunker unloading.
Thanks, @Tensuko!

**Comment by Tensuko** [comment]
Well, you are half correct with that one :)
It was working without the unload here point at least in FS19, why I don't know but I was also used to use the unload here point.
It could be not working now couse of the new triggerHandler.
But I would like to keep it as 'works with unload here' for now, as we have other stuff to fix 1st :)
when it does work fine for you its good 👍

**Comment by GeorgeEarslight** [comment]
The only problem is that if the silo is too short, the tractor will leave a small trail of grass while driving away.
But I don't think that's worth raising an issue, there are more important stuff to solve :)
