### ISSUE TITLE
working width setting not accurate enough (HUD)

### ISSUE THREAD

**Issue by CmdrTiri** [Courseplay/courseplay#5997]
If I set CP up to calculate a course with 2 combines (Lexion 8900) with 13.7m (Case 3162 TerraFlex Draper 45ft) my combines collide when they should pass each other on facing directions.
When looking into the settings after engaging CP on the course the width is set to 13.5m instead of 13.7 like set up in the "generate course" window...
Width is automatically set to 13.5 instead of 13.7
Trying to adjust the width manually is not possible in such fine steps, only in 0.5m? Can you rework this in a future version?

Wenn ich CP einen Kurs für  2 Drescher (Lexion 8900) mit 13,7m Mähwerken (Case 3162 TerraFlex Draper 45ft) generieren lasse kollidieren die Fahrzeuge, wenn sie sich auf entgegengesetzen Bahnen befinden. Hierbei ist mir aufgefallen, dass in den CP-Einstellungen die Arbeitsbreite auf 13,5m gestellt wird anstelle von 13,7 wie ich sie im Kursgenerator-Fenster eingestellt habe...
Die Breite wird auch automatisch immer mit 13,5 statt 13,7 ermittelt.
Die manuelle Einstellung ist nicht in feinen Schritten möglich, nur in Schritten von 0,5m?
Lässt sich das in einer zukünftigen Version überarbeiten?

Danke und viele Grüße
thanks and kind regards

Tiri

**Comment by Tensuko** [comment]
strg+scrollrad probiert ?
Der Kurs ist definitiv für 2 mal 13,7m generiert, dass problem werden die 'on the fly' generierten offsetkurse für die Drescher sein, stell mal den 'symetrischen Bahnenwechsel' um, dann sollten die sich eigentlich nicht mehr begegnen.
Das gleiche Problem haben wir mit Ballenwagen, welche ihre echte Arbeitsbreite für den Kurs offsetkurs nutzen statt der im HUD.

Wie geschrieben, 2 Wege es zu versuchen erstmal so hin zu kriegen.

**Comment by CmdrTiri** [comment]
strg Scrollrad scollt nur im 1,0m Schritten. Im Kursgenerator klappt die Feineinstellung und die 00052.dev scheint die Einstellung auch ins CP-Fenster zu übernehmen, aber bei symmetrischem Bahnwechsel rumst es. Ich versuche jetzt mal ohne den symmetrischen Bahnversatz zu fahren!
![fsScreen_2020_08_28_23_43_41](https://user-images.githubusercontent.com/70349981/91619011-46c17c00-e98c-11ea-8777-63aba9c3e7dd.png)

**Comment by bjt3833** [comment]
IIRC, even in fs17, I always had to manually adjust the 13.5m header widths to 13.7m manually. Since the change whenever that wouldn't let you do fine tune adjustments in the small menu, I have just been doing it in the course generation full screen UI that was added whenever.

**Comment by Misamangame** [comment]
You can set 14m for those headers, they will still harvest whole field.  But best way to deal with this is by my opinion to skip lanes or change middle part to Lands which works is much better then Up/down
