### ISSUE TITLE
Harvesters will not work on dedicated server

### ISSUE THREAD

**Issue by Sgt-Christ** [Courseplay/courseplay#5999]
v6.02.00052 on a dedicated server. Using John Deere s790 harvester, lizard 3162 draper 45ft header, John Deere 8r, and avalanche 1596 auger wagon. current maps I have tried are the MVP19, and wild west 16x map by cazz64. If I generate a course on any field with the harvester, the harvester will not start the course. If I start the course with the harvester on the field instead of the edge of the field, the harvester turns in circles, backs off the field, and stops. If I do the same thing on a single player or a multiplayer everything works fine to include the emptying of the harvester. It only happens when I load into the dedicated server. Also have several other issues on a dedicated server with many different features but figured I would start with this one.

https://gist.github.com/Sgt-Christ/4b83b286e94df5e7a4fc1d3eb31cefc2#file-server-game-log

**Comment by Tensuko** [comment]
Should work with 00056 (tested it)
