### ISSUE TITLE
the vehicles do not automatically load seeds, fertilizer and lime

### ISSUE THREAD

**Issue by ontot** [Courseplay/courseplay#6001]
good morning everyone ... I don't know what I'm wrong, surely it's my mistake ... but I don't understand why it doesn't automatically load the lime ... the same problem is with the seeder ... version 2.00052
![fsScreen_2020_08_29_12_30_36](https://user-images.githubusercontent.com/26443217/91634867-14e40000-e9f4-11ea-9ace-343ab9c65a2c.png)

**Comment by Tensuko** [comment]
try scroll down the min to 0%
also logfile with debugchannel 2 active will help as well as the course shown (the 3 Dots in the HUD)
Also:
Load the Fieldwork Course and only ADD (the folder with the +) to the Fieldwork course.

**Comment by ontot** [comment]
even with the min at 0 it is the same. it doesn't load anything. I am attaching the log file with debug 2 turned on. thanks Tensuko 

[log.txt](https://github.com/Courseplay/courseplay/files/5145260/log.txt)

**Comment by archaoncze** [comment]
Hi. I had same problem with lime. Driver open cover, slow down, but doesnt start byuing it. Maybe problem with buying stuff? As refill digestate at BGA works fine. I have set minimum at 0%, and also tryied with 50% and i always combine courses by using ADD.

**Comment by Tensuko** [comment]
Buying stuff is not the Issue.
From log I can see it is the same Issue as #5991 and should be fixed with the next version.

**Comment by ontot** [comment]
thanks tensuko ... i will wait for the next version.

**Comment by Tensuko** [comment]
Combine Issues: #5991
