### ISSUE TITLE
Warning: Tried reverting to input context [] which is not defined.

### ISSUE THREAD

**Issue by ClassifiedDuck** [Courseplay/courseplay#6004]
When I play a map all of a sudden It freezes but trees are still swaying! I can't move or do anything! I thought it may have something to do with the combination of CP and DevControls but I don't know. In some other maps everything works fine!

**Comment by ClassifiedDuck** [comment]
BTW The map that I find not working is Medicine Creek Farms
--
Definatle a Courseplay issue, as soon as I removed it, my map worked! The only problem is that I really want/need Courseplay

**Comment by Tensuko** [comment]
logfiles ?!

**Comment by ClassifiedDuck** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5145753/log.txt)

**Comment by ClassifiedDuck** [comment]
btw at the end it will say Force Quit, I had to because there was no way to leave the game.

**Comment by Tensuko** [comment]
This is not a CP Error in your logfile:
2020-08-29 13:37 Error: Running LUA method 'mouseEvent'.
2020-08-29 13:37 /Users/cameronreina/Library/Application Support/FarmingSimulator2019/mods/FS19_EasyDevControls/scripts/gui/EasyDevControlsFieldFrame.lua:169: attempt to compare number with nil

You got more then one Map in your mods folder wich is a no-go. Only one at the time.

**Comment by ClassifiedDuck** [comment]
Thanks man
