### ISSUE TITLE
CP Dedi startet nicht mehr

### ISSUE THREAD

**Issue by Bandesss** [Courseplay/courseplay#6005]
Hallo zusammen
neuste Version von Github
Der Drescher startet nicht mehr auf dem Dedi
es kommt siehe log
[Gamelog.txt](https://github.com/Courseplay/courseplay/files/5145675/Gamelog.txt)
[log.txt](https://github.com/Courseplay/courseplay/files/5145676/log.txt)

**Comment by Tensuko** [comment]
Duplicate #5999
