### ISSUE TITLE
Q: Mode1 How to adjust count setting of Filltype?

### ISSUE THREAD

**Issue by AgroWillem** [Courseplay/courseplay#6007]
Q: Mode1
V6.0200052
In Vehicle Specific Settings: how do i change the Count value of the Filltype?
I keeps standing on 20/20 and how to change this?
In V6.02.00047 i can adjust it with the "-" and "+" on screen.

Thx.

**Comment by Tensuko** [comment]
Scrollwheel on the mouse.
No Space on HUD for +/- for everything so we removed them.
