### ISSUE TITLE
CP zeigt die Wegpunkte nicht mehr an

### ISSUE THREAD

**Issue by Wolle1976** [Courseplay/courseplay#6008]
Hallo, mich habe heute den neuen CP (52) auf meinen Server Hochgeladen und musste feststellen das wenn ich im CP Menü auf das "Auge" gehe zeigt er die Strecken nicht mehr an, dafür verschwindet das Seuerungs-Kästchen und der Tacho?
Mudd ich was umstellen???

**Comment by Wolle1976** [comment]
Ach ja DEDI-MP

**Comment by Tensuko** [comment]
Das Auge ist auch nicht dafür da um Wegpunkte anzuzeigen, das ist die kleine übersicht + debug.
Das Anzeigen alle Wegpunkte ist und war schon immer im HUD unter Settings die 3 Punkte!

**Comment by Wolle1976** [comment]
Aber selbst dort zeigt er mir keine Punkte, nicht mal den Start-oder-Endpunkt

**Comment by Wolle1976** [comment]
Es wird auch nicht mehr angezeigt wenn ein Drescher entladen werden muss

**Comment by Tensuko** [comment]
Dann ist bei dir noch mehr verkehrt und ich brauch ein logfile.

**Comment by Wolle1976** [comment]
[game log 30.8.2020.txt](https://github.com/Courseplay/courseplay/files/5146769/game.log.30.8.2020.txt)

**Comment by Wolle1976** [comment]
Konntest du einen Fehler finden??

**Comment by Tensuko** [comment]
Bin gerade nicht am PC ich gucke mir das nachher an.

**Comment by Tensuko** [comment]
Du hast scheinbar einen Konflikt mit einem Farhzeug, eventuell Drescher oder Überladewagen.
2020-08-30 10:35 Error: Running LUA method 'packetReceived'.
2020-08-30 10:35 dataS/scripts/vehicles/specializations/events/SetPipeStateEvent.lua(54) : attempt to index field 'object' (a nil value)
Und da du im MP spielst, wird das auch noch ein Problem sein.
Ich mach den mal wieder auf als Info für uns.

**Comment by Wolle1976** [comment]
OKAY 
Dankeschön
Der Rest läuft super, Klasse Arbeit
