### ISSUE TITLE
Mode1 When emptied on trigger. Vehicle stops.

### ISSUE THREAD

**Issue by AgroWillem** [Courseplay/courseplay#6009]
V.6.0200052
Mode1
Transporting Digestate
After emptying the vehicle stops with "Unloading Amount" still on screen and doesn't go further.

![2020-08-30 14_31_53-Greenshot](https://user-images.githubusercontent.com/23076511/91659221-facb2000-eace-11ea-996e-c86529919b11.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/5146786/log.txt)

**Comment by Tensuko** [comment]
Duplicate #5991
