### ISSUE TITLE
Pick up Slurry

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/courseplay#6010]
Hello,

I created to courses to provied slurry for the field, first course is for spraying and second for picking up the slurry from original big cow house.  The Course Play dont want to load the slurry.

PS: I tryined also to use mod tank for slurry and everything works perfect:

https://gist.github.com/envikowaty/ac47197e31dae5e7987ff55119dd35d0

**Comment by Tensuko** [comment]
Same Problem as in #5991 fix is on the way.
