### ISSUE TITLE
Convoy distance gets wrong on big fiels with headland

### ISSUE THREAD

**Issue by ole22143** [Courseplay/courseplay#6011]
Habe das Problem wenn ich 2 Drescher im verband fahren lasse und auf 100m Abstand einstelle nähern sich beide mit jedem Mode 3/2 ablade Manöver an wenn der Vordere langsamer wird um den Rüssel raus zu fahren um die Distanz die Theoretisch mit 10 kmh zurückgelegt wird da nur 5kmh gefahren wird der hintere Drescher holt auf sagt aber nach wie vor er ist 100m entfernt das ganze geht sogar so weit das der eine den anderen überholt. 
![image](https://user-images.githubusercontent.com/5673152/91754459-b7a1a780-ebc9-11ea-8c22-9f50b27ea969.png)

version 6.02.00052

**Comment by Tensuko** [comment]
oh okay das hat bisher niemand getestet und ist auch recht merkwürdig, weil die Distanz eigentlich über den Fortschritt gemessen wird.... hmm müssen wir schauen.

**Comment by ole22143** [comment]
Ich habe nochmal weiter Ergiebig Getestet und ich kann den fehler meines Erachtens nur im Vorgewende Reproduzieren.

**Comment by pvaiko** [comment]
Das ist schon komisch. Haben wir ein Log mit Channel 14?

**Comment by ole22143** [comment]
Also auf ein zweites ich denke das der Abfahrer nichts damit zu tun hat sondern es müsste ein fehler im Vorgewende sein denn die Distanz nimmt komischer weise in jeder Ecke auffallend zu 
![image](https://user-images.githubusercontent.com/5673152/91838803-5b349b80-ec4e-11ea-9661-56e86f083a3c.png)
Log ist hier zu finden https://pastebin.com/TarSNyDH
