### ISSUE TITLE
Abfahrer findet Drescher nicht 

### ISSUE THREAD

**Issue by acton59** [Courseplay/courseplay#6012]
Hallo,
Abfahrer findet Drescher nicht auf Feld.
schreibt: kein Drescher in Reichweite.
Debugchannel 4 7 12 und 14.
funktionierte bei mir nur bis Courseplay_6_01_00399.
Keine Mods außer Courseplay.

[log.txt](https://github.com/Courseplay/courseplay/files/5155151/log.txt)

**Comment by Tensuko** [comment]
Drescher läuft mit CP ?
Hast du dem Abfahrer einen Drescher zugeordnet ?

**Comment by acton59** [comment]
Gesendet: Dienstag, 01. September 2020 um 14:02 Uhr
Von: "Tensuko" <notifications@github.com>
An: "Courseplay/courseplay" <courseplay@noreply.github.com>
Cc: "acton59" <aldo.ackermann@online.de>, "Author" <author@noreply.github.com>
Betreff: Re: [Courseplay/courseplay] Abfahrer findet Drescher nicht (#6012)


 

Drescher läuft mit CP ?
Hast du dem Abfahrer einen Drescher zugeordnet ?.

 

Danke für die Antwort.

Hatte überlesen daß Abfahrer nicht mehr mit Ai funktioniert, sonde nur noch mit CFP Drescher.

**Comment by Tensuko** [comment]
Ja im Moment klappt das nur mit CP als Fahrer, eventuell später mal mit manuellem Drescher fahren, geht aktuell aber noch nicht.
