### ISSUE TITLE
Mode-2 Not working with 6.02.0053 Beta

### ISSUE THREAD

**Issue by aresq** [Courseplay/courseplay#6013]
Hello, made a mode-2 with a track to unload at silo, return and wait for Combine to call, unload and loop this...

I see this error in de log: 2020-09-01 16:43 :21 [info lp17438] T8.435 (#2): Exception, stopping Courseplay driver, [string "dataS/scripts/network/Object.lua"]:148: Object:getNextDirtyFlag(), too many dirty flags

What i did was program the combine and let it run full, it is at 100%... it called the Tractor for unloading, it started to go to the combine but then stopped, when i press the Drive Course, it doesn't doe anything but repeat that error in the log with stacktrace.

Any more info needed?

[log.txt](https://github.com/Courseplay/courseplay/files/5157117/log.txt)
![fs19cp](https://user-images.githubusercontent.com/3012150/91868437-022c2e00-ec75-11ea-9b8b-1d17592ef7a2.jpg)

**Comment by pvaiko** [comment]
Sorry, version is not ready for use, I removed it. Use 52 instead.

**Comment by schwiti6190** [comment]
please try the new relase as you got a beta release here
