### ISSUE TITLE
CP legt Server lahm (MP)

### ISSUE THREAD

**Issue by Obsiana2019** [Courseplay/courseplay#6014]
Nach Installation von CP neuste Version (0053) kann ich auf dem Server nichts mehr machen. Was genau da schief läuft kann ich nicht sagen.

Hatte die Version nur installiert um evtl für euch ein Aussagekräftiges Logfile zu bekommen.

Hier das Logfile:

[GIANTS Engine Runtime 8.0.0 (22022) 64bit.txt](https://github.com/Courseplay/courseplay/files/5157200/GIANTS.Engine.Runtime.8.0.0.22022.64bit.txt)

**Comment by Tensuko** [comment]
Bitte zurück auf die Version 52 gehen.

**Comment by Obsiana2019** [comment]
Würde ich gerne aber die Funktioniert ja derzeit zumindest im Multiplayer nicht, das Problem mit Abfahrer einstellen und das nichts passiert.  Aber alles gut ich habe Geduld irgendwanm wird es ja im Multiplayer besser :-)
