### ISSUE TITLE
Mode 2

### ISSUE THREAD

**Issue by Tocik** [Courseplay/courseplay#6015]
What am I doing wrong?
In mode 2, the tarktor will either not be able to correctly drive up to the combine, or cannot leave it. The photo shows the progress of harvesting the field in 8 hours.
![1](https://user-images.githubusercontent.com/65189100/91871117-d19dc180-ec7f-11ea-81a3-81ce4f945dc0.jpg)
![2](https://user-images.githubusercontent.com/65189100/91871179-d5c9df00-ec7f-11ea-8a08-9e691f6ffad1.jpg)
[log.zip](https://github.com/Courseplay/courseplay/files/5157227/log.zip)

**Comment by schwiti6190** [comment]
please try the new relase as you got a beta release here
