### ISSUE TITLE
Mode 1 plus transport belt

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/courseplay#6019]
Hello guys,

I’ve notice that the transport belt is not triggering up the tractor in mode 1 to stop and waiting for loading. I’m using transport belt to load manure on the trailer

**Comment by Tensuko** [comment]
How did you set up the course ?
Where do you load ?
How do you load ?
Screenshots ?

**Comment by envikowaty** [comment]
Im not sure how to show you the trigger point with F%5 button

ok thats the log: https://gist.github.com/envikowaty/0e23d7e235f689107c8c6a5b14e36afa1

![Bez tytułu](https://user-images.githubusercontent.com/69640077/91940318-8a531780-ecf7-11ea-9253-9c7e44f94974.png)

**Comment by andreasthu** [comment]
The First waypoint shoult not be under the belt.
When the traktor stops at wp1 then the tipper should be under the belt. Push the wp1 in editor mode closer to wp2.
Lg
Andreas

**Comment by Tensuko** [comment]
Not to close to WP it could be the tractor not stopping couse of PPC.
Also make sure you have no filltype selected, as the load on start doesn't need a filltype and only then the % of wanted fillvolume will get displayed.
Should be all written down on wiki page:
https://github.com/Courseplay/courseplay/wiki/Mode-1-Changes

**Comment by envikowaty** [comment]
Ok, I will do some changes and post back ASAP

**Comment by Tensuko** [comment]
.00055 no Problem:
![fsScreen_2020_09_11_15_06_05](https://user-images.githubusercontent.com/27344744/92929174-6b176100-f440-11ea-8dc2-cc22a6eb688f.png)
Also tested when to start:
![fsScreen_2020_09_11_15_06_16](https://user-images.githubusercontent.com/27344744/92929189-6f437e80-f440-11ea-8c3f-b71eeec61160.png)
Should be jsut your course and make sure if you want to load on 1st waypoint to no add a fillType.
