### ISSUE TITLE
Probleme mit MP 

### ISSUE THREAD

**Issue by KeineEndeDerLegende** [Courseplay/courseplay#6020]
Hallo, zwischen beiden Versionen funzt im MP nicht.. CP version 49 funzt der Trigger nicht aber Abfahrer fehlerfrei und bei neueste  Version 53 funzt abfahrer nicht aber Trigger funzt top.. bei SP läuft alles super nur bei MP (Server) funzt nicht.. Säen/Düngen oder Feldarbeit macht Abfahrer nicht. Ich drück abfahrer einstellen und passiert nix.. er bleibt stehn und CP macht garnix.. 

Habt ihr auch bekannte Problem?

LG Chris

**Comment by Tensuko** [comment]
Das reicht nicht an Infos... https://github.com/Courseplay/courseplay/wiki

**Comment by wisco01** [comment]
also wenn ich mit dem häcksler oder dem drescher auf dem feld stehe und abfahrer einstellen geht nichts kann da drauf hämmern wie ich will es wird kein fahrer eingestellt das ist ab version 6.02.00050 so. 6.02.00049 läuft alles super. spiele auf dedi. im singleplayer hab ich es nicht wirklich getestet

**Comment by Tensuko** [comment]
Du meinst aber schon wenn CP den Drescher/Häckslwr fährt ?

**Comment by wisco01** [comment]
> Du meinst aber schon wenn CP den Drescher/Häckslwr fährt ?

ich möchte ja das cp den Drescher/Häcksler fährt allerdings lässt sich kein fahrer einstellen

**Comment by KeineEndeDerLegende** [comment]
So ging mir genauso.. in 30 min werde ich mal Log datei von server posten!

**Comment by KeineEndeDerLegende** [comment]
[Server-log.txt](https://github.com/Courseplay/courseplay/files/5168747/Server-log.txt)
[log.txt](https://github.com/Courseplay/courseplay/files/5168749/log.txt)
so das sind 2 logs. einmal beim server und einmal eigene log.

**Comment by andremeyer123** [comment]
@Tensuko    #5975 dort ist es sehr schön beschrieben mit video bei helfer einstellen löscht er alle courspunkte die er generiert hat und stellt niemanden ein (alles mp server   ) sp nicht getestet
https://www.youtube.com/watch?v=N408pT0WxOg

**Comment by wisco01** [comment]
> @Tensuko #5975 dort ist es sehr schön beschrieben mit video bei helfer einstellen löscht er alle courspunkte die er generiert hat und stellt niemanden ein (alles mp server ) sp nicht getestet
> https://www.youtube.com/watch?v=N408pT0WxOg

Genau wie in dem Video

**Comment by KeineEndeDerLegende** [comment]
@Tensuko Sie müssen mal den Video genauer angucken und den Klicks hören.. Sobald vor dem Abfahrer einstellen steht die Modul auf 3 oder 5 je nach Maschinen und Kurse generieren. Dann drücke ich 5-6 mal Abfahrer einstellen und passiert nicht aber der modul wechselt nach den 5. klickt auf Modul 4 und wegpunkte auf 1/1.. Diese Problem ist genauso wie im Video im Dedi Server(MP).. im SP läuft fehlerfrei.

**Comment by andremeyer123** [comment]
in version 050 wurde zu sehr aufgeräumt @KeineEndeDerLegende

**Comment by KeineEndeDerLegende** [comment]
@andremeyer123 ab version 050 bis 053 geht bei mir garnix. Nur Version 049 funzt perfekt aber dann hab ich ein problem beim Saatgut und Dünger zu befüllen. nur Manuell mit Palette befüllen kein problem aber aus dem Silo geht nix. drum hab ich jetzt CP rausgelöscht und warten bis nächsten Version.

**Comment by Tensuko** [comment]
> 
> 
> ab version 050 wurde zu sehr aufgeräumt @KeineEndeDerLegende

Aha... und das machst du wo dran fest ? Was wurde denn 'zu sehr aufgeräumt' ?

Und Leute jetzt mal ohne Witz.... gsSetDayTime 12 ist kein schwerer Befehl, diese Videos und Bilder bei tiefster Nacht bringen nichts wenn man sich was angucken soll. Mag in dem Fall nicht so das Problem sein, aber es ist einfach mist wenn man nicht sieht was da passiert, wie und wo der Drescher steht usw usw je nach Problemmeldung....

**Comment by andremeyer123** [comment]
@Tensuko  es ist doch kein vorwurf 
-few changes and a few MP fixes
-code cleanup
in den video geht es doch nur um die sache klicke auf helfer einstellen und cp löscht alles 
weitere fehler im mp 
- Düngefunktion bei sähmaschinen lassen sich nicht abschalten ohne dünger fährt er dann nicht 
- speichert keine neuen Kurse und einstellungen

**Comment by Tensuko** [comment]
Ich hab auch nicht gesagt, dass es ein Vorwurf ist...

Aber was sollen wir mit der Aussage 'Es wurde zu viel Aufgeräumt' anfangen ?
Kennst du dich mit dem Code aus ?
Weist du was zu viel rausgeflogen ist ?
Weist du, dass die Fehler die jetzt auftauchen, durch das aufräumen entstanden sind ?

So entstehen Gerüchte und falsche Infos die ich dann wieder in irgendwelchen Foren lese, glaub mir ich kenne das schon...

MP ist und bleibt ein Problem und es wird dauern bis alles läuft, ist halt so...

**Comment by KeineEndeDerLegende** [comment]
@andremeyer123  immer ruhig bleiben.. wenn Probleme hat mit CP einmal beschwerden.. Wenn einer sagt er braucht mehr information dann braucht er halt damit er weiter helfen kann.. gibt nicht immer die schuld.. MP macht immer probleme das kenn ich seit jahren schon.. die Video war nicht von mir aber diese problem hab ich auch aber wenn er sagt er kann nur am Tag sehen statt nacht dann mach ich heute nachmittag ein video für Tag damit er weiter helfen kann.. Ohne Weitere Information kann er nix tun.. ende..ich gebe niemanden schuld. Man muss immer Geduld haben.. bei SP kann ganz schnell fixen als MP weil der Server immer zu dumm ist und spuckt nur fehler. Also bitte wenn er mehr info braucht dann sollen wir tun oder Lass es bleiben und warten bis neue Version kommt..  Wünsche euch ein schönen tag noch.

**Comment by andremeyer123** [comment]
@Tensuko MP ist ein fall für sich 
ich weiss das du dein bestes gibst um jeden zuhelfen 
was ich mir wünschen würde eine Bugliste für MP wo alle fehler zusammen gefasst werden z.b. #5975  und dieser ist ja der selbe Problem dadurch wären vieleicht weniger offene issues

**Comment by Tensuko** [comment]
Ja das wäre total super, aber weist du was es so schwer macht sowas zu erstellen ?
Weil pausenlos doppelte Issues aufgemacht werden, oder Issues mit sinnlosen Kommentaren wie 'ich hab das gleiche Problem' zugetextet werden und man so nichts mehr findet....
Zu wenig Leute suchen erst mal ob das Issue schon existiert, ob das Problem bei ihnen selber liegt und dann auch noch ein richtigen Bugreport schreibe, tja davon träumen wir....

**Comment by KeineEndeDerLegende** [comment]
https://youtu.be/sY4oV9eawY8

so hab mal video gemacht.. hab vergessen den Maschinen lautstärke runterstellen aber ich hoffe du hast bessere sichtbar als wie im dunkel. falls noch mehr brauchst meld dich @Tensuko

**Comment by KeineEndeDerLegende** [comment]
@Tensuko  passt das mit dem Video?

**Comment by Tensuko** [comment]
Ja passt schon. Wir haben jetzt einen server dank @andremeyer123 undbkonnten uns das da angucken, aber dauert halt.

**Comment by KeineEndeDerLegende** [comment]
@Tensuko  Perfekt dann warte ich auf den nächsten Version.
