### ISSUE TITLE
mode 1 loading water doesnt work anymore.

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#6021]
Nur eine Info!
Die jetzt neuste Version CoursePlay6_600053 (Update) funktioniert auch nicht!
Die letzte Funktion war mit der CoursePlay6_600048

Danke

**Comment by Tensuko** [comment]
Logfile channel 2.

**Comment by Lustiger-Hubi** [comment]
![Screenshot (62)](https://user-images.githubusercontent.com/48583507/91961771-efb10380-ed0b-11ea-8305-499c614938de.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5161174/log.txt)

Bitte

**Comment by Tensuko** [comment]
Kann auch nicht gehen,aus 2 Gründen:
Dein Start ist so platziert, das wenn der Truck da ankommt, dein Trailer noch nicht im Trigger ist. Kann klappen, kann auch nicht klappen.
Der andere Grund steht da in weis mit blauem Hintergrund geschrieben. Zählerstand ist auf 0. Dreh den wieder hoch auf 20 oder wie hoch du den haben willst.

**Comment by Lustiger-Hubi** [comment]
OK habe ich jetzt nicht darauf geachtet!
Aber siehe Bilder
Er schreibt, Tank ist leer!
![Screenshot (62)](https://user-images.githubusercontent.com/48583507/91969325-3277d900-ed16-11ea-88a5-be79f7e01fbe.png)

Hier kann ich aber mit der R taste befüllen
![Screenshot (63)](https://user-images.githubusercontent.com/48583507/91969412-59cea600-ed16-11ea-869c-f6f7fb0d5270.png)

**Comment by Tensuko** [comment]
Auf was ist dein min Wert gesetzt ?

**Comment by Lustiger-Hubi** [comment]
Habe jetzt mal mit den Giantis Wassertank probiert!
Er schreibt, Farmsilo ist leer, aber ich kann auch hier mit der R taste laden!
Auch die Version CoursePlay6_600048 läd den Tanker voll!

![Screenshot (65)](https://user-images.githubusercontent.com/48583507/91971623-cc8d5080-ed19-11ea-9346-0d04aa5400f7.png)
![Screenshot (66)](https://user-images.githubusercontent.com/48583507/91971638-d1ea9b00-ed19-11ea-9cde-b6e32265c4ef.png)

**Comment by Tensuko** [comment]
Dein min Wert steht auf 1%
Das Problem ist das diese Silos uns 0 Inhalt mitteilen.
Min auf 0% stellen dann sollte es gehen.
Da müssen wir noch etwas in die Logik einbauen fals das machbar ist.
Fürs nächste mal: Die Seite mit den FillTypes bitte mitposten was eingestellt ist.

**Comment by Lustiger-Hubi** [comment]
Ok hat funktioniert!
Danke dir!

Kann geschlossen werden!
Danke nochmal!
