### ISSUE TITLE
Verschiedene Startposition der Fahrer

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#6022]
Wenn ich mit zwei Fahrer auf ein Feld drillen will, dann fängt der erste Fahrer am Vorgewende an wie auch eingestellt ist und der zweite Fahrer fängt mitten auf den Feld auf der 1 Feldreihe an. Beide Fahrer auf den selben Kurs eingestellt.

**Comment by Tensuko** [comment]
Keine log, keine Bilder vom Kurs, keine Info über Einstellung....

2 Fahrer auf einem Feld:
- Kurs generieren mit 2 Geräten
- Kurs mit Vorgewende IMMER weg von der Ecke generieren, sonst gibt es Probleme
- Einen Abfahrer im Offsetmenü auf links und den anderen auf rechts stellen

**Comment by rohne83** [comment]
Das Problem kenne ich auch und hat mir auch schon Kopfschmerzen bereitet. Tritt auch häufig auf, wenn man einen Kurs mit scharfen Ecken für das Vorgewende generiert. Das mit dem weg von der Ecke generieren ist aber ein guter Hinweis. Kann gut sein, dass das schon die Lösung ist.
Ansonsten hilft es mitunter, den zweiten Drescher erstmal soweit manuell zu fahren, dass sich eindeutig nur noch ein einziger Wegpunkt in seiner Nähe befindet, und man ihn mit "starten am naheliegendsten Wegpunkt" weiter auf die Reise schicken kann.

**Comment by rohne83** [comment]
Ich kann natürlich nur für mich sprechen, aber es scheint tatsächlich davon abzuhängen, wo der erste Startpunkt des generierten Kurses ist. Zur Ecke hin, passiert das was Hendirk beschrieben hat. Von der Ecke weg, klappt es wunderbar. Läuft dann sogar mit scharfen Ecken.

**Comment by Tensuko** [comment]
Ich mach hier zu, wie @rohne83 auch festgestellt hat, es hängt viel von der Position des Start ab, an der Ecke vom Feld sorgt für mehrere Probleme, daher weg von der Ecke zum Kurs bauen, dann sollte es gehen.
