### ISSUE TITLE
courseplay driver refuce to start

### ISSUE THREAD

**Issue by Tommyaleks** [Courseplay/courseplay#6023]
Hi guys`s, this is for the latest release v6.02.00053

I running my own fs19 dedicated server on a windows 7 computer.

The problem is, the driver wont start to drive. it just sit`s there. no other issues that I have seen.

There is no mods on the server. The version v6.02.00051 did work on driver but not on seed filler. seed filler fixed in v6.02.00052 but no driver worked. Version  v6.02.00053 still no driver works.

Read logfiles from server down below.

Server log file:

Hope this will be fixed soon, thank you.

**Comment by Tensuko** [comment]
Logfiles only attached as .txt ! https://github.com/Courseplay/courseplay/wiki

**Comment by jspring0811** [comment]
See issue #5975 (fix is being tested)

**Comment by Tensuko** [comment]
Closing as duplicate.
