### ISSUE TITLE
How to switch off the sign

### ISSUE THREAD

**Issue by Kalio91** [Courseplay/courseplay#6024]
Hi,

When I adjust width of work in courseplay appear sign (look on the photo below). How to switch off it after I set machine?
![Przechwytywanie](https://user-images.githubusercontent.com/70664852/92032789-f58a0180-ed6a-11ea-96e5-69a5003e3fca.PNG)

**Comment by Tensuko** [comment]
That comes from REA Mod.
When REA is activated, those rays don't disappear.
No Idea how REA is tricking arround with their overlay stuff.
