### ISSUE TITLE
Es Können keine Kurse mehr generiert werden

### ISSUE THREAD

**Issue by Wolle1976** [Courseplay/courseplay#6026]
Hallo, ich habe heute Festgestellt das im 052 die neu generierten kurse nicht geladen werden können, nach einem neustart sind sie weg und wieder einen neustart später sind ca 10 stück da die alle nicht angewählt werden können. 053 ist auch nicht besser, sorry

MP dedi

**Comment by Wolle1976** [comment]
[game log 3.9.20.txt](https://github.com/Courseplay/courseplay/files/5170900/game.log.3.9.20.txt)

**Comment by Wolle1976** [comment]
Wie kann ich eigentlich im MP die Course wieder löschen??

**Comment by Tensuko** [comment]
#5785

**Comment by andremeyer123** [comment]
Wie kann ich eigentlich im MP die Course wieder löschen??
nur im sp und wieder neu auf den serverladen mfg

**Comment by Wolle1976** [comment]
hinter welcher datei verstecken sich die course??

**Comment by Tensuko** [comment]
..\Dokumente\My Games\FarmingSimulator2019\CoursePlay_Courses\...

**Comment by Wolle1976** [comment]
der ist lehr

**Comment by Tensuko** [comment]
Für den Server weis ich das nicht, da ich CP noch nie im MP benutzt habe... wir haben halt keinen Server mit dem wir rumspielen und experimentieren können wie wir Lustig sind.

**Comment by schwiti6190** [comment]
diese ist da selbe https://github.com/Courseplay/courseplay/issues/5975, aber es wäre intressant zu wissen wo der her kommt:
2020-09-03 20:30 Error: Running LUA method 'packetReceived'.
2020-09-03 20:30 dataS/scripts/vehicles/specializations/events/SetPipeStateEvent.lua(54) : attempt to index field 'object' (a nil value)
zufällig ÜLW oder Drescher benutzt mit CP ?

**Comment by Wolle1976** [comment]
nein

**Comment by schwiti6190** [comment]
global company silosystem genutzt ?

**Comment by andremeyer123** [comment]
@Tensuko  schreibe mich privat an ich unterstütze euch gerne mit 1 server für MP

**Comment by andremeyer123** [comment]
@Wolle1976  bei gamed  ist es im web FTP  Ls19 / Gameprofile   (nicht im savegame )

**Comment by Wolle1976** [comment]
Tensuko  wie kann ich dich privat anschreiben??

**Comment by Tensuko** [comment]
Nur per Discord:
Tensuko # 2300
