### ISSUE TITLE
mode 1 digestaat pop up window

### ISSUE THREAD

**Issue by candymant** [Courseplay/courseplay#6027]
hello
when I load digestaat and I stop while loading there is a pop-up window to choose the filltype.
but I already selected digestaat as filltype.
but the window doesn't want to go away ESC does nothing and start than a little amount gets loaded but the window doesn't go away.
my route is a GC trigger to a liquid silo of missy B. the starting point I have already made it better but the popup window is the worst.
![stop course when loading](https://user-images.githubusercontent.com/47895720/92164236-5251ee80-ee35-11ea-8adc-8be52f06e15e.png)

2020-09-03 18:17 :57 [info lp6199] Roadrunner (#1): AI driver in mode 1 starting at 242/424 waypoints (COURSEPLAY_NEAREST_POINT)
2020-09-03 18:21 :08 [info lp15517] Roadrunner (#1): AI driver in mode 1 starting at 1/416 waypoints (COURSEPLAY_NEAREST_POINT)
2020-09-03 18:23 :40 [info lp19510] Roadrunner (#1): AI driver in mode 1 starting at 216/416 waypoints (COURSEPLAY_NEAREST_POINT)
2020-09-03 18:24 :34 [info lp20820] Roadrunner (#1): AI driver in mode 1 starting at 215/416 waypoints (COURSEPLAY_NEAREST_POINT)
2020-09-03 18:27 :04 [info lp24730] Roadrunner (#3): AI driver in mode 1 starting at 31/134 waypoints (COURSEPLAY_NEXT_POINT)
2020-09-03 18:27 :16 [info lp25282] C15 KOTH Super (#4): AI driver in mode 1 starting at 230/230 waypoints (COURSEPLAY_NEAREST_POINT)
2020-09-03 18:32 Application exit request forced.
2020-09-03 18:32 Application exit request forced.
this is all I get in my log file.

**Comment by candymant** [comment]
hello 
I used the course with debug mode 2 and the digestaat popup is only when I stop the loading if the second coursplayer with a different course is loading water. with other filltypes, I have not tested.
[log.txt](https://github.com/Courseplay/courseplay/files/5175206/log.txt) debug 2

**Comment by Tensuko** [comment]
So when the driver is loading and you stop the driver, the popup window appears ?

**Comment by candymant** [comment]
sometimes it appears if they both are loading. but then I can select esc and they go on with loading but sometimes it get stuck and I have to close with alt+F4.
[log.txt](https://github.com/Courseplay/courseplay/files/5175267/log.txt)
in this log there are XXXXXXXXX in front of the problem I think.

**Comment by candymant** [comment]
i think the problem is that de TSA30000 its a trailer but the other trailer is also a TSA30000
but it can only load water en the first can only load digestaat.

**Comment by candymant** [comment]
And another problem is that, when the water trailer is in the loading trigger just standing there. And the digestaat driver leave the unloading trigger the driver gets back to the loading trigger on 10 km/h.

**Comment by andreasthu** [comment]
(Version: 1.7.1.0) FS19_GlobalCompany
Available mod: (Hash: b22311961db1db792e9a88e5744e6066) 
Has same issues when i use global company 1.7.1, 
Since i gone back to version 1.6 global company, it works as it should. 
Lg
Andreas

**Comment by candymant** [comment]
but I want to use the animal feeder system.

**Comment by Tensuko** [comment]
I had no Issues with the 1.7.1 so far

**Comment by andreasthu** [comment]
@Tensuko 
Athen a rother mod maybee ?
Testet it niw again.
With globalcompany 1.7 i had same problems.
When the driver will fill by a global company filltrigger ( egal ob digestate, biogas, compost, hopfen,.... i play donDiego map) the screen apears, push ESC dows not work, 
And it makes no difference if i drive with courseplay or autodrive. The game hangs and is only closeable with the strg+alt+entf key, 
With globalcompany 1.6.0.1 it works normal.
Lg
Andreas

**Comment by Tensuko** [comment]
@andreasthu 
Can you try it with GC 1.7.1.0 but remove AD from save and test it ? Save your AD Network file 1st! 
#6018

**Comment by candymant** [comment]
@ tensuko
I dont use AD and i still have this isseu.

**Comment by andreasthu** [comment]
> @andreasthu
> Can you try it with GC 1.7.1.0 but remove AD from save and test it ? Save your AD Network file 1st!
> #6018

Mach ich ab morgen, dann hab ich wieder Zeit.
Lg
Andreas

**Comment by candymant** [comment]
I have tried global company 1.6.1 but I got the same problem.

**Comment by candymant** [comment]
hello, again I found the problem. the popup doesn't show if I don't use global company triggers that are implemented on the map.
if I use silos from other mods then it doesn't happen.

**Comment by candymant** [comment]
> @andreasthu
> Can you try it with GC 1.7.1.0 but remove AD from saving and test it? Save your AD Network file 1st!
> #6018

this is another problem and I don't use AD so this doesn't belong here. why not report an issue yourself.

**Comment by candymant** [comment]
> @andreasthu
> Can you try it with GC 1.7.1.0 but remove AD from save and test it ? Save your AD Network file 1st!
> #6018

I don't use AD so my problem is with the GC triggers not AD.

**Comment by andreasthu** [comment]
> @andreasthu
> Can you try it with GC 1.7.1.0 but remove AD from save and test it ? Save your AD Network file 1st!
> #6018

Sorry, i testet it today,  no time before.
1st Test with
Courseplay 6.02.000057
Autodrive 1.1.0.5-rc5
Global company 1.7.1.0
Egal ob die Kurse mit AD oder CP gefahren werden, beim Füllen von GC triggern bleibt das Spiel hängen, muss den Computer neu starten.
Ändere ich die GC Version auf 1.6.0.1 funktioniert es.
Habe dann mit der neuen CP 6.02.00060 getestet.
Da funktioniert es auch mit GC v1.7.1.0
Sowohl CP als auch AD erkennen den trigger und füllen normal auf.

**Comment by schwiti6190** [comment]
Seems like @andreasthu got it to work, so @candymant could you try it again with the newest verison ?

**Comment by candymant** [comment]
i will try be back in a minute

**Comment by candymant** [comment]
I still have the problem !!!!!

**Comment by Tensuko** [comment]
> 
> 
> I still have the problem !!!!! only in gc triggers not in giants triggers.

shouting arround help less then a logfile with channel 2 active...

**Comment by candymant** [comment]
here log with channel 2 active
[log.txt](https://github.com/Courseplay/courseplay/files/5247742/log.txt)

first picture mode 1 driver in gc trigger.
![fsScreen_2020_09_18_21_17_21](https://user-images.githubusercontent.com/47895720/93637347-c07de000-f9f5-11ea-9466-043a7990b7c5.png)


second picture other mode 1 driver in giants trigger.
![fsScreen_2020_09_18_21_16_48](https://user-images.githubusercontent.com/47895720/93637436-e905da00-f9f5-11ea-80c5-00cb0efc483a.png)


third picture driver out of giants trigger.
![fsScreen_2020_09_18_21_16_56](https://user-images.githubusercontent.com/47895720/93637496-fe7b0400-f9f5-11ea-9ed1-f592f2c4f537.png)


fourth picture is when other driver is in giants trigger to load then in this picture you see the pop up on the driver just staying in the gc trigger.
![fsScreen_2020_09_18_21_17_35](https://user-images.githubusercontent.com/47895720/93637670-3bdf9180-f9f6-11ea-9022-d953e3d14d05.png)

**Comment by candymant** [comment]
I tried it with the latest version and it works now.
thanks!
