### ISSUE TITLE
Silage verdichten geht nicht mehr

### ISSUE THREAD

**Issue by xerion8300** [Courseplay/courseplay#6029]
Silage verdichten geht nicht mehr, Traktor fährt nur im Kreis.
Habe die neuste Version aber auch bei der 49 Version geht es nicht.
[log.txt](https://github.com/Courseplay/courseplay/files/5175220/log.txt)

**Comment by Tensuko** [comment]
Wie sieht dein Kurs aus ? Screenshot ?

**Comment by xerion8300** [comment]
Nochmals ein Bild und die Log

![2020-09-04 17_25_06-Farming Simulator 19 2020 09 04 - 16 52 22 01 mp4 - VLC media player](https://user-images.githubusercontent.com/25564472/92256221-bd520280-eed3-11ea-8238-83efeee1df32.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5175687/log.txt)

**Comment by polosubtil** [comment]
Not sure it's related, but for me the only way to make it work is to start in front of the silo and select start at first point
Ich bin mir nicht sicher, ob es damit zusammenhängt, aber für mich besteht die einzige Möglichkeit, es zum Laufen zu bringen, darin, vor dem Silo zu beginnen und Start am ersten Punkt auszuwählen

**Comment by Tensuko** [comment]
Auf jeden Fall zu weit im Bunker gestartet mit dem Kurs und ich hab das lange nicht mehr probiert aber eigentlich sollte nur Modus aufschütten gehen und das mit einem Schild.
Verteilen und Verdichten muss ich mal wieder probieren...

@polosubtil 
thats interesting, he doesn't tell you 'no bunker found' ?

**Comment by Tensuko** [comment]
Try version .00055 and report

**Comment by xerion8300** [comment]
Funktioniert einwandfrei mit der Version .00055.
Danke
