### ISSUE TITLE
Nur eine Technische Frage

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#6030]
Ich möchte mit einer Ballenpresse Strohballen herstellen
und dann mit dem AutoStrack FSX 63.72 einsammeln 
und neben dem Kögel Flatbed abladen.
Dieser soll durch autoloade laden!
Bis dahin so weit so gut!
Jetzt mein Problem: Der Kögel Flatbed kann nicht auf
Beladen am Startpunkt eingestellt werden!
Besteht die Möglichkeit dieses zu ändern?
Bilder hierzu
![Screenshot (68)](https://user-images.githubusercontent.com/48583507/92303522-e6c36a80-ef75-11ea-9cca-08a55ccfbe75.png)
![Screenshot (69)](https://user-images.githubusercontent.com/48583507/92303523-e88d2e00-ef75-11ea-83c2-a4697735b5b7.png)
![Screenshot (70)](https://user-images.githubusercontent.com/48583507/92303524-ea56f180-ef75-11ea-8421-10918a5655bb.png)
Danke

**Comment by Tensuko** [comment]
Selbst wenn wir den Mode1 für die Art Trailer freischalten würde, käme als nächstes das entladen vom Trailer und wir werden das AutoLoad erst einmal nicht unterstützen.
Vorschlag für dich: https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=147304&title=fs2019
Diese Trailer basieren auf den normalen Ballensammelwagen und haben kein extra AutoLoad Script verbaut.
Du kannst mit denen mit einem Offset über das Feld fahren und direkt zum Ort der Bestimmung bringen und dort abladen, ohne den Zwischenschritt mit dem LKW+Trailer.
Ist nur ein alternativer Vorschlag, aber das andere wird erst einmal nicht gemacht!

**Comment by Lustiger-Hubi** [comment]
Ok, Danke
