### ISSUE TITLE
Incorrect convoy distance with different tractors and implements

### ISSUE THREAD

**Issue by uded** [Courseplay/courseplay#6032]
Tractors Claas Axion 960 (Giants) and Claas Axion 960 TerraTrac (Giants again).

When I make the two-tractor cultivator pass on a field I have a problem with the minimum distance in a convoy. I made it to 50m, but clearly the tractor thinks it's not the case.

![2020-09-05 (1)](https://user-images.githubusercontent.com/218623/92314079-6c293800-efd3-11ea-978d-0f6b9751eba4.png)

Here it said I am 100m+, but clearly that was not the case. I am not sure which channel should be enabled to debug this...

**Comment by Tensuko** [comment]
logfile with debugchannel 14 and I would like to see your course (the 3 dots in HUD Settings) and the Offset Settings.

**Comment by uded** [comment]
Got it. I will try to reenact this situation with the same machinery. Shouldn't be a huge issue, but give me a moment.

**Comment by uded** [comment]
I was able to, kind of, reenact the situation by accident with different tractors and implements. Please, take a look at this video:

https://youtu.be/H1TKI-rOtww

Also, log channel 14:

[log_cp.txt](https://github.com/Courseplay/courseplay/files/5204955/log_cp.txt)

**Comment by Tensuko** [comment]
Still valid for .00064 ?
I did some convoy Course and so far all was fine...

**Comment by Tensuko** [comment]
Could be the same as  #6011

**Comment by uded** [comment]
@Tensuko I haven't had any need for a bigger convoy in last couple of days and I was debugging a different issue as well (#6017), so give me a moment and I will try again - maybe even with the same equipment actually...

**Comment by uded** [comment]
Yes, the problem definitely is still there. This time I had this with two Fend Ideal combines - 100m was more like 10m. Do you want me to update the logs and/or video?

**Comment by Tensuko** [comment]
Might help with new log and video with channel 12 and 14 (I think 7 might help too).
Also how does your main course look like ? Sharp Corners ?

**Comment by pvaiko** [comment]
This is a known problem especially for bigger fields with wide implements, can we close all the duplicates and leave just one open?

**Comment by Tensuko** [comment]
#6011
