### ISSUE TITLE
self-propelled sprayers miss a lot of spots when turning

### ISSUE THREAD

**Issue by NicholasSoares** [Courseplay/courseplay#6034]
Hi, i have and old issue but just got worse in the last versions, basically the self-propelled sprayers wont turn with enough room and turn into the field sideways missing a lot of spots.
I tried many things like IA turns (almost no diference, same result), use paths, tool offsets, but nothing helps with the short turn into the field.

I only have good results with back mounted self-propelled like the horsh one.

How to recreate the scenario:
With any front or middle (Stara) mounted self-propelled sprayer in almost any field in any map.

Using now v6.02.00054.

![fsScreen_2020_09_06_03_42_41](https://user-images.githubusercontent.com/42093631/92320103-43b23580-eff5-11ea-8960-92103c3d571e.png)
![fsScreen_2020_09_06_03_43_38](https://user-images.githubusercontent.com/42093631/92320435-e966a400-eff7-11ea-9fba-b3163ac0f3eb.png)

**Comment by Tensuko** [comment]
Lower tool early in adv settings ?
Same for raise late.

**Comment by NicholasSoares** [comment]
Yes, lower tool early is set, but at least 10% of the sprayer is in the field when it turn on making it miss a large spots in sprayers like the rubicon.

![fsScreen_2020_09_06_05_03_33](https://user-images.githubusercontent.com/42093631/92321180-6c8af880-effe-11ea-893e-e3ff6b03789d.png)
![fsScreen_2020_09_06_05_03_36](https://user-images.githubusercontent.com/42093631/92321187-73b20680-effe-11ea-9caa-470e4658e0cc.png)
![fsScreen_2020_09_06_05_04_00](https://user-images.githubusercontent.com/42093631/92321184-714fac80-effe-11ea-89c3-5e2cfcfc2219.png)
![fsScreen_2020_09_06_05_04_07](https://user-images.githubusercontent.com/42093631/92321186-73197000-effe-11ea-89dc-31453686232c.png)
![fsScreen_2020_09_06_05_10_54](https://user-images.githubusercontent.com/42093631/92321328-75c89500-efff-11ea-8389-3145338f31c0.png)
![fsScreen_2020_09_06_05_11_24](https://user-images.githubusercontent.com/42093631/92321331-7bbe7600-efff-11ea-95cf-8882e4eb2e96.png)

**Comment by Tensuko** [comment]
Ok I see whats going on.
How does he do the work with at least one Headland ?

**Comment by NicholasSoares** [comment]
they get really crazy on turns in this mode, spins like 2 times before along the edge, and still miss the turn when they get to the center lines.

![fsScreen_2020_09_10_20_48_44](https://user-images.githubusercontent.com/42093631/92827838-b54d0380-f3a8-11ea-8935-28892bf785ce.png)
![fsScreen_2020_09_10_21_03_52](https://user-images.githubusercontent.com/42093631/92828240-30161e80-f3a9-11ea-9571-754dfba339e5.png)
![fsScreen_2020_09_10_21_04_06](https://user-images.githubusercontent.com/42093631/92828258-373d2c80-f3a9-11ea-9b76-10bdd51aab69.png)

**Comment by Tensuko** [comment]
@pvaiko 
Looks like the same Issue we had on the seeder when we start it folded.

**Comment by pvaiko** [comment]
Don't we have an issue like this already? (also there were no changes in this area in the last few months or so, don't think it got worse now.)

**Comment by pvaiko** [comment]
> Looks like the same Issue we had on the seeder when we start it folded.
which issue is that?

**Comment by pvaiko** [comment]
should be fixed by 57
