### ISSUE TITLE
Mode 3 problem

### ISSUE THREAD

**Issue by krookoo** [Courseplay/courseplay#6035]
Hi!

I have problem with mode 3 from much last versions.
From versions ~.43 to .52 tractor with overloader vagon didnt start drive.
In last version (.54) tractor move, but missing pipe position?

Link to short YT movie :)
https://youtu.be/4DwW9RGH-TY

**Comment by Tensuko** [comment]
logfile with debugchannel 4 7 12 and 14 pls

**Comment by krookoo** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5179625/log.txt)

You want see log from 2020-09-06 14:19  i think.

I make new video for this debug:
https://youtu.be/lcT81ID1n9Y

**Comment by pvaiko** [comment]
![image](https://user-images.githubusercontent.com/2379521/92329321-5ac04a00-f02c-11ea-8043-240cb0e06ab5.png)
Your multitool settings are weird, you are running the center combine with a manual offset to move it to the left side. Set up your multitools correctly and it'll work fine.

**Comment by krookoo** [comment]
I know that, but much times if i try use first harverster left, 2nd center, and 3rd right, last harvester dont work. I later make you wideo... I test it in version .04x.

**Comment by Tensuko** [comment]
Becouse you didn't start the headland on the side of the field, but on the corner, wich won't work.

**Comment by krookoo** [comment]
> Becouse you didn't start the headland on the side of the field, but on the corner, wich won't work.

Thanks for answer, but i didnt understand this. Can you explain?
There is any manual? I use CP from fs 13 and maybe my knowledge about CP is old :D

**Comment by Tensuko** [comment]
![coursegen](https://user-images.githubusercontent.com/27344744/92329739-dab8d500-f069-11ea-8509-a075759e0cc1.png)
you will get much better results when start calculate on the side.
You can switch to 'choose position on map' for the starting point (just click on the map in the course gen when selected the position)

**Comment by pvaiko** [comment]
@krookoo you can also set the same manual side offset for the unloader but then you have to assign it to that combine only.
