### ISSUE TITLE
Mode9/10 Bunker Division

### ISSUE THREAD

**Issue by enderwiggin07** [Courseplay/courseplay#6037]
Currently you set your tool width and CP calculates how many rows should be made through the bunker, I think.  From experience and from reading, everyone is setting their tool width extra high to keep the driver off the walls.   It seems the game tells CP something about the size of the silo, but it's not perfect info and obviously very hard to teach a robot to work very close to walls without hitting them.  

Would it be possible to let the user set how many rows the bunker should be split into?  For example right now with a Mode9 driver set with a work width of 7m, he doesn't hit the wall but only shovels 75% of the bunker.  The right side is clean but the left side is ignored.  What I would like to see instead is for CP to continue to calculate the size of the bunker, but let the user pick how many paths the tool takes through the bunker, rather than just say how wide the tool is.   So with my silage fork which is actually maybe 5-6m, i can say "do 2 passes" and it will have a left and right and catch everything without catching the walls.  

I appreciate how well courseplay silage modes work in general btw, using them for the first time and very impressed by how smooth it works. 

Image for small example of how it's working now.  
![image](https://user-images.githubusercontent.com/50051834/92329591-f7371c00-f02d-11ea-8d78-a26b0850bdbe.png)

**Comment by Tensuko** [comment]
And why set the work width so high?! 0.1m can already make a difference...

**Comment by enderwiggin07** [comment]
In reality the fork is about 6m, I set it at 7m.  If you set it at 6m or even lower to try to get it to use a second row in the bunker, the loader drives the fork into the wall and gets stuck.  Everything I've read about how to use mode 9/10 suggested to set the width higher and in experience it does work.

**Comment by enderwiggin07** [comment]
That's why I'm saying wouldn't it be easier for me to just say "do one pass down the middle" or "do two passes evenly split" the forks really grab a bigger area than their actual width which is why it works to set their width high.  But instead of you guys having to try to program it to be both effective but also not get into the walls, wouldn't it be easier to have a setting I can just pick based on what's working on my particular tool and bunker?

**Comment by Tensuko** [comment]
Why do you make such a big change ?
Why not try it with 6.5m or 6.7 or whatever....

**Comment by enderwiggin07** [comment]
So, example.  On this particular fork, on this particular loader, on this particular silo, I can set it at 5.6m and it will take 2 passes clearing the whole bunker, but every maybe 10 runs it hits the wall and sticks.  At a bigger number it takes just pass on the right side.  Since it's a DLC loader and a mod fork and a mod map, I don't really think you are going to be that interested in the specifics of why that is the case.  I'm not asking for CP to work perfect under every single circumstance, my suggestion is just to say, let me override the CP math and tell it "split the bunker into 2" or "split the bunker into 3" in situations where I can see it would work better than the automatic.

**Comment by enderwiggin07** [comment]
Right now a lot of settings have "auto" or manual, and I read CP is calculating the number of paths anyway.  So it would be cool to have "auto" paths, or manual.

**Comment by Tensuko** [comment]
The overall Problem with those sticking in walls got actually not much to do with the rows and it would be just a work arround.
We know it needs to be improoved, but a manual setting is to much change for this....

**Comment by enderwiggin07** [comment]
Understood.  And again I appreciate how well these modes already work since large-scale silage would be unenjoyable without CP.

**Comment by Tensuko** [comment]
I hope this somehow explains the Problem that we have with walls...
We are getting close and try not to scratch it while turning straight.
Thats why I also say, make the Start point more far away so the angle is not that high when going to the side.
No matter of rows, the result for the row near the wall will stay the same.
To solve that we would beed to go straight at the very beginning of the Bunker, wich need more space, but we haven't touch Mode9 yet since we have other stuff to do and somehow bring it into a at least half way finished state.
![Bunkerproblem](https://user-images.githubusercontent.com/27344744/92330654-cb895580-f070-11ea-9c90-
d093b397eca4.png)

**Comment by enderwiggin07** [comment]
![image](https://user-images.githubusercontent.com/50051834/92331051-4767ab80-f039-11ea-9210-154899baec66.png)

Even despite the difficulties of pathing and dealing with Giants collisions, shouldn't it be more normal for the "rows" right now to be figured like this? With overlap in the center rather than just skip if we can't fit two width of the tool?

**Comment by Tensuko** [comment]
The problem stays, nearing the walls with an angle...
if we don't have that, the rows are no problem at all.
