### ISSUE TITLE
Kein AdBlue(DEF) mehr

### ISSUE THREAD

**Issue by LamaiK** [Courseplay/courseplay#6039]
AdBlue (DEF) fehlt in der Flüssigkeitsauswahl beim Transport ab erste Punkt.
Fehlt seit man mehrere Anhänger mit verschiedenen Gütern beladen kann.  v6.02.00046 

Lamai

**Comment by Tensuko** [comment]
Und kann dein Trailer AdBlue laden ?
Für Traktoren zum Tanken gibt es so noch keine Unterstützung für mehrere fillTypes!

**Comment by LamaiK** [comment]
Hallo Tensuko
Sorry wollte nicht unhöflich sein, ist ja auch kein Fehler. Wir benutzten das bis jetzt um AdBlue und Biodiesel aus der Raffinerie zu holen.
Ja, mein Trailer kann AdBlue (DEF) laden. (lsfmUniversalTankPack)
Wir Spielen seit einigen Monaten auf der Map Helvetia, mit dem AdBlue mod.
Da haben wir eine fest verbaute Raffinerie die Biodiesel und AdBlue herstellt welches wir an Tankstellen Verkaufen können oder in unsere Hoftankstelle liefern und so unsere Maschinen Tanken können, Biodiesel und AdBlue. 
Manuell beladen geht ja auch, fehlt halt jetzt in den neuen CP Versionen. 
Danke euch für eure Arbeit.
Grüsse Lamai

**Comment by Tensuko** [comment]
Ok dann schauen wir uns das an, kann aber dauern.

**Comment by LamaiK** [comment]
Danke schön.

**Comment by schwiti6190** [comment]
@LamaiK in which CP mode do you need access to adblue loading, only in mode 1(GrainTransport A to B) ?

**Comment by LamaiK** [comment]
Yes exactly, mod 1 loading at the first point. Thank you for your efforts.
