### ISSUE TITLE
CP Speed Setting Conversion & other Speed setting issues

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#6041]
So the text of the unit says CP is converting from KPH to MPH. But the values are still represented as KPH. 12 KPH is ~ 6 MPH this tractor is currently reversing. Also theses settings are no longer representing the value that they should be. I adjusted turn speed on headlands and it went faster. I was using turn for headland setting but it was on a straight after turning.

FS 17 Courseplay speeds
Field Speed was any non turn segment of a generated course and Mode 2 when not on the user course. FS 19 seems to be the turn speed

Turn Speed was any generated turn when traveling in the forward direction. FS19 doesn't seem to do anything

Reversing Speed still seems to work as it did in 17.

Street Speed. Was only ever used for user recorded courses. FS19 it seems to represent field speed and the max shouldn't be set at 6kph it was set at the max KPH of the tractor

Would be nice to see theses values resorted as the current way of displaying them makes it anyone's guess at which value to adjust to make your tractor go faster or slower depending on how CP is handling driving the tractor.

![fsScreen_2020_09_07_23_39_43](https://user-images.githubusercontent.com/10678220/92430751-acb7bb80-f163-11ea-9769-a3b2e8eda558.png)

**Comment by VergylTantor** [comment]
Also reported as Issue #5994

**Comment by pops64** [comment]
Sorry been out the loop. Just breaking into what has been changed in FS19 CP but it looks like what handles driving only has one speed setting that would apply to this when driving the course(Not Turning or Unloading). Maybe there should be added if statements depending on the mode that is calling AI Driver or how ever the CP code is handled

https://github.com/Courseplay/courseplay/blob/e28884e2bcdb3c36dba9ac9bb5e846a21d7e5014/AIDriver.lua#L406-L449

**Comment by pops64** [comment]
Sorry for the double post. Has for the conversion issue. I went through past releases of CP 6 and 5 and I am pretty sure this is the code that did it for us. We let Giants do the conversion through the `g_i18n:getSpeed` function not sure if this still available in 19 or if you still want to do it this way. Just putting it out there

https://github.com/Courseplay/courseplay/blob/b720cca0994f591124f65cad7a20bb1f0a6879df/hud.lua#L831-L852

**Comment by Tensuko** [comment]
fixed with 6.03.00060
