### ISSUE TITLE
Suggestion: Update default scan step

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#6042]
I experienced a similar issue to #5604 and this seems to be a reoccurring problem in 19 but I know from my skim through of 5604  and other related issues it suffers from the fact that the scan step is set at 5(I believe the units are meters but unsure).  Which in old FS version would been fine seeing how the fields where spaced out farther but with FS19 the fields are too close even on vanilla maps. Setting this to 2 would seem to resolve all the weird issues that pop up from fields being combined by the field scanner. Has this resolved my problem right way. 

The con to a smaller scan step is the CPU usage required to do field boundaries which should not suffer unless playing on a 4x map with 100+ fields. I know the field scanner is one of the oldest remaining parts of CP which I believe was written in FS13 so I think we have more than enough CPU power now so 2 should be fine.

**Comment by pvaiko** [comment]
I think it's more complicated than that, it is certainly not 5 m, that is the starting value but as far as I remember it changes dynamically going down to a few centimeters.

**Comment by pops64** [comment]
So I have reviewed the code for the scanner. The problem with the scanner's dynamic system is that it doesn't work for box shaped fields that are close together. The more complex the field shape is the more accurate the field scanner gets. But if all the scanner is doing are boxes it will never have a need to reduce the scan step to increase precision.  Which is pretty ingenious by Jacob. This saves CPU power when not needed and only increases it has needed. The referenced code is what makes 99% of the field edge path. Has you can see 187 to 201 this while loop is what increases its precision. After the probe leaves the field the probe will rotate back by .57 degrees until the probe is back on the field. If it can't do this with in 5.7 degrees than it increases precision which for 90 degree fields will never happen. 

The few centimeters you reference is to determine the first field edge point and direction which has to be super accurate in order for this while loop to work as efficiently as possible for 90 degree fields.

https://github.com/Courseplay/courseplay/blob/e28884e2bcdb3c36dba9ac9bb5e846a21d7e5014/fields.lua#L159-L206

**Comment by pops64** [comment]
Sorry for the double post. Has for the conversion issue. I went through past releases of CP 6 and 5 and I am pretty sure this is the code that did it for us. We let Giants do the conversion through the `g_i18n:getSpeed` function not sure if this still available in 19 or if you still want to do it this way. Just putting it out there

https://github.com/Courseplay/courseplay/blob/b720cca0994f591124f65cad7a20bb1f0a6879df/hud.lua#L831-L852

**Comment by Tensuko** [comment]
Soo.... what is this Issue about now ?
Any enhancements comeing for this one ?
Just a Question ?

**Comment by pops64** [comment]
It is up to Peter. But I would at the very least make a note of this somewhere in the official docs on how to change this in the setting xml file if people run into this. I wouldn't recommend much below 2 tho.

**Comment by pvaiko** [comment]
We keep this open in case we want to refine (or rewrite) that algorithm, I'd certainly add checking the field number to detect when we end up on a different field, similar to what our PathfinderUtil.getFieldIdAtWorldPosition(posX, posZ) does.

**Comment by Tensuko** [comment]
> 
> 
> We keep this open in case we want to refine (or rewrite) that algorithm, I'd certainly add checking the field number to detect when we end up on a different field, similar to what our PathfinderUtil.getFieldIdAtWorldPosition(posX, posZ) does.

This indeed happens on some maps. Should consider reworking it...
