### ISSUE TITLE
Geschwindigkeit

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#6044]
Hallo
Nach einer kurzen Zeit geht der Abfahrer mit der Geschwindigkeit von 17 km/h  beim Gülle fahren auf 10 km/h runter
Was könnte es sein, habe an der Einstellung nix verändert
![Jd7310 1](https://user-images.githubusercontent.com/47453761/92514024-894b4a00-f211-11ea-8774-20995f6c36f4.png)
![Jd7310](https://user-images.githubusercontent.com/47453761/92514033-8d776780-f211-11ea-9a95-a72aee130b4e.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5190327/log.txt)

**Comment by Kobra299** [comment]
Es kann sein, dass das Feld abfällt, um die Geschwindigkeit zu verringern

**Comment by Hendirk** [comment]
Ich spiele die Nordfriesland Map --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 08.09.20, 20:47 schrieb Kobra299 <notifications@github.com>:

   
  Es kann sein, dass das Feld abfällt, um die Geschwindigkeit zu verringern

**Comment by Tensuko** [comment]
Das Verblüffende an deinen Screenshots ist, das wenn die Geschwindigkeit abfällt, also zu einem späteren Zeitpunkt auf 10km/h ist, dass die 21km/h um ingame 10:26 (also später) ist und die 10km/h um ingame 10:25 (früher)...

**Comment by Tensuko** [comment]
Ganz wichtig, updaten!
(Version: 1.0.0.0) FS19_manureSystem
Hat im mods Ordner nichts zu suchen:
Error: Invalid mod name 'LS19_courseplay-master'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
Bitte aufhören mit diesem zzz_ krams:
(Version: 6.02.00054) zzz_courseplay

.zip Datei laden, in den mods Ordner schieben, fertig!
https://github.com/Courseplay/courseplay/releases

**Comment by GeorgeEarslight** [comment]
@Tensuko @schwiti6190 
This is the issue I was trying to solve when I make the wrong edit on 
https://github.com/Courseplay/courseplay/blob/e28884e2bcdb3c36dba9ac9bb5e846a21d7e5014/AIDriver.lua#L425-L426
The strange thing was that if you restart the driver (stop-start) it's fixed, so it could be an issue of clearing something.

**Comment by Tensuko** [comment]
Yea we have that one still on the Water Tailers in Mode1 too.
It is a bit strange...

**Comment by Hendirk** [comment]
Das liegt daran weil ich den Abfahrer entlassen und dann noch mal eingestellt habe--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 09.09.20, 06:53 schrieb Tensuko <notifications@github.com>:

   
  Das Verblüffende an deinen Screenshots ist, das wenn die Geschwindigkeit abfällt, also zu einem späteren Zeitpunkt auf 10km/h ist, dass die 21km/h um ingame 10:26 (also später) ist und die 10km/h um ingame 10:25 (früher)...

**Comment by schwiti6190** [comment]
@Hendirk  could  you try this again with the newest verison (same as  #6061)
