### ISSUE TITLE
Delete waypoint

### ISSUE THREAD

**Issue by Step72** [Courseplay/courseplay#6045]
Hello
I just found out that with CoursePlay you can move points along a path just how do you remove a point? Because I pressed CRTL + 5 but it doesn't work.
Do we need an editor?
Thank you
<img width="600" alt="Capture d’écran 2020-09-09 à 16 56 55" src="https://user-images.githubusercontent.com/18511992/92622949-f1f3fe80-f2c5-11ea-8a51-264c29e741a0.png">

**Comment by Tensuko** [comment]
You got to set your own keys in keysettings to make it work.
The one shown in F1 are a bit confusing I know...
