### ISSUE TITLE
combine unloading AutoDrive

### ISSUE THREAD

**Issue by michal44001** [Courseplay/courseplay#6047]
I have a problem with this mod , when I am harvesting the field the worker with AD don't see the combine  he won't go to unload it , I made the point for example field 17 on the field not on road but it 's the same problem he's staying and still see waiting for call

**Comment by Tensuko** [comment]
No Idea how AD works for this.
Baiscally when AD is waiting for a combine, our Combine will open pipe when it needs to be unloaded and will call AD with this.
But about AD settings I have no Idea, you should ask in AD GitHub. If there is a Problem with our Combine, make a new Issue with the details that we need (logfile with I would say debug 4 7 12 and 14)
