### ISSUE TITLE
Legacy 13 & 15 Branches Missing

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#6048]
**********EDIT linked the wrong version is now correct***********************

I was feeling nostalgia for FS15 and I went looking  for CP. Unfortunately, I am not sure where the FS13 or the FS15 legacy branches disappeared too but they are. I know the first stable release versions are tagged under the release system for Github if you want to scroll back through ~350 v6 releases(May be a faster way didn't feel like finding it out). But the problem is for 15 there where about 120 changes done after the stable release which was never tagged.  ~I was able to find version 119. Sadly it looks like version 120 is lost as this commit was made to the FS15 legacy branch which appears to be gone.~ I was able to find the last commit. I am pretty sure my first push to CP was the last update version of v4. v1-119 are important commits as well as they include stability updates for when the expansion was released for 15. I don't have 13 so I am not bothering with finding it.

https://github.com/Courseplay/courseplay/tree/c20d751613f8c91df9896d57fa1cf3152af35ee1

Mabye we could redo the branch for 15? Thanks

**Comment by pvaiko** [comment]
I'd suggest creating your own fork where you can create any branch or tag you like.

**Comment by pops64** [comment]
I only put it out there that other users might need FS15 or 13 CP. I know there were a few that never converted to 17 and if they didn't convert to 17 they probably haven't gone to 19 either.
