### ISSUE TITLE
Grayed out options on HUD and adv settings.

### ISSUE THREAD

**Issue by kfullmer95** [Courseplay/courseplay#6049]
When using courseplay certain options on the bottoms are greyed out. when i am in a combine i can't use self unload. wondering if i need to use an older version of courseplay to get it to work.

**Comment by Tensuko** [comment]
Wow....
you must had a very long break:
https://github.com/Courseplay/courseplay/issues/3882

self unload combine:
HUD Settings -> adv settings, activate self unload, done.
Just start Combine with a normale Mode6 Fieldwork Course and place a Trailer within 20m near your Field or on the Field and watch it working.

**Comment by kfullmer95** [comment]
I can’t. That option is greyed out as well. Cant change to activated

**Comment by Tensuko** [comment]
Logfile and screenshots pls.

**Comment by Tensuko** [comment]
Closed due to inactivity, guess wrong CP Version or something.
Only download .zip from here:
https://github.com/Courseplay/courseplay/releases
just copy .zip file into mods Folder, nothing more.
