### ISSUE TITLE
menu issue

### ISSUE THREAD

**Issue by areid0403** [Courseplay/courseplay#6050]
when I'm in one of my combine mods I can open up the menu but the mouse cursor freezes and stutters really bad. it's done this in some other mods but I really like this mod and I want it to work with corseplay

**Comment by Tensuko** [comment]
logfile and do those mods have IC ?
If so then you need to build it out of your mods, we are not supporting normal IC Controls, only simpleIC, wich is basically the same and in a much better shape then all the random IC out there.

**Comment by Tensuko** [comment]
Guess it is IC Problem (NOT simpleIC), closing...
