### ISSUE TITLE
Curseplay lässt sich nicht aktivieren

### ISSUE THREAD

**Issue by Ronny-1982** [Courseplay/courseplay#6052]
Hallo 

seit ein paar Tagen kann ich den Cursplayfahrer nicht mehr aktivieren. Wenn ich ein Kurs erstellt habe klicke ich auf Abfahrer einstellen. Aber nichts passiert. Es schaltet nicht mal um auf Abfahrer entlassen. 

Habe es mit der Version 0053 und 0054 probiert

**Comment by Ronny-1982** [comment]
Ach und die Räder lenken danach auch nicht mehr. Man fährt kurven aber die Achse bewegt sich nicht. Man muss das Fahrzeug erst zurücksetzen

**Comment by Tensuko** [comment]
logfile ?

**Comment by Ronny-1982** [comment]
> logfile ?

http://94.250.220.81:9460/logs.html?lang=de

**Comment by Ronny-1982** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5211374/log.txt)

**Comment by Tensuko** [comment]
Lade mal bitte die neueste Version runter, nur .zip laden und in den mods Ordner packen, kein umbenennen etc.
https://github.com/Courseplay/courseplay/releases

**Comment by Ronny-1982** [comment]
Guten Morgen Tensuko
Hat funktioniert! Läuft wieder. 
Konnte aber kein Kurs mehr abspeichern. 
Kurse löschen ist auch ein Problem. Der Müllbutton fehlt.

**Comment by Tensuko** [comment]
Genetelles MP Problem.
