### ISSUE TITLE
zurücksetzen von versatz normal oder fehler?

### ISSUE THREAD

**Issue by Playlord75** [Courseplay/courseplay#6054]
der versatz setzt sich immer wieder automatisch zurück obwohl ich einen anderen benutzen möchste ist das gewollt oder ein fehler von cp 
![fsScreen_2020_09_10_23_05_06](https://user-images.githubusercontent.com/71101944/92806256-1d581580-f3ba-11ea-8fc1-a15d24f7c5d3.png)
![fsScreen_2020_09_10_23_05_13](https://user-images.githubusercontent.com/71101944/92806270-1fba6f80-f3ba-11ea-8506-7605f3f04d88.png)
![fsScreen_2020_09_10_23_05_15](https://user-images.githubusercontent.com/71101944/92806280-20eb9c80-f3ba-11ea-9b5c-cc532942254f.png)
![fsScreen_2020_09_10_23_05_16](https://user-images.githubusercontent.com/71101944/92806287-234df680-f3ba-11ea-868b-7b6ff95a5457.png)

**Comment by Tensuko** [comment]
Naja warum willst du den ändern wenn es so gut aussieht?
CP kennt den richtigen Vetsatz.

**Comment by Playlord75** [comment]
Weil er am Anfang nach dem wenden immer ca 30 bis 50 cm abstehen lädt und erst nach ca 10 gefahrenen Metern auf seinen Versatz wechselt also er bleibt mit seinem Versatz Erst auf der linken Seite bis er dann auf die rechte wechselt

**Comment by Playlord75** [comment]
Und durch den Versatz verkleinern blödes Beispiel mit vergrößern wollte ich dies verhindern

**Comment by Tensuko** [comment]
Das ist dieses issue #5097 und deine Sache wäre nur ein workarround, wir würden das wenn dann lieber richtig fixen.
