### ISSUE TITLE
speed regulation problem

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#6057]
I am using the latest version courseplay (.54) and during a course of field slurry and barrel filling, during the road part of the road at some point, passing by another tractor on the side lane and with a path similar to both tractors, the maximum speed of 10 km / h was set and they continued all the way up to the field. It is not the first time this has happened, but it had occurred on other occasions that I do not remember in detail. I attach photos and logs
![Farming Simulator 19 11_09_2020 21_39_44](https://user-images.githubusercontent.com/59969508/92967121-fc0a2e80-f478-11ea-8b40-3098a2c3ef1a.png)

![Farming Simulator 19 11_09_2020 21_39_55](https://user-images.githubusercontent.com/59969508/92967129-00364c00-f479-11ea-9ca6-21bd646ab091.png)

[log.txt](https://github.com/Courseplay/courseplay/files/5211275/log.txt)

**Comment by Tensuko** [comment]
Latest Version is .00056
We know about the Speedproblems and working on it already.

**Comment by Tensuko** [comment]
Same Issue, continue there #6061
