### ISSUE TITLE
Mode 2: Cart goes into wall of Bunker

### ISSUE THREAD

**Issue by enderwiggin07** [Courseplay/courseplay#6060]
Using mode 2 to fill the silo bunker Placeable Large Single, from standard game. 

Here is his course:
![20200911232915_1](https://user-images.githubusercontent.com/50051834/92987354-53af9680-f487-11ea-9c14-6db084812c79.jpg)

He chooses left lane, doing fine: 
![20200911232924_1](https://user-images.githubusercontent.com/50051834/92987359-5dd19500-f487-11ea-82d5-f642570b8ef4.jpg)

He steers hard into the wall (if he chooses right lane he steers into right wall):
![20200911232931_1](https://user-images.githubusercontent.com/50051834/92987364-6c1fb100-f487-11ea-83bf-fa44e90bfa67.jpg)

He eventually recovers but leaves a huge pile while he was stuck: 
![20200911232934_1](https://user-images.githubusercontent.com/50051834/92987373-7641af80-f487-11ea-848e-aee87f5b4421.jpg)

**Comment by enderwiggin07** [comment]
From testing it looks like the courseplay course should have a lot of straight waypoints after the bunker to prevent this issue.   So it is preventable.   But a little frustrating that mode2 needs a long straight exiting the bunker and mode 10 needs a long straight going into it for everything to work.  We need the space of an airport to make silage work

**Comment by Tensuko** [comment]
I don't use long straight way out of the Bunker and it works (or worked) fine. Got to test it.
This looks a bit strange what happens there.

**Comment by enderwiggin07** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5212676/log.txt)

Here is the log, if it helps.  This was a pretty long gaming session so it's a big log, but the issue reported here will be the first 10+ times the fasttrac goes to unload in the bunker.   

Later I recorded the course backwards, so that he drives next to the silo and does the 180 degree turn, then drive through the bunker.  I did this to give it a nice straight exit and the problem went away, either by coincidence or not.  At that point I did assign a 2nd mode2 driver to the same course which I realize isn't very supported, just letting you know if you see weirdness in the logs toward the end, not to worry about that.

**Comment by Tensuko** [comment]
Could you try our newest release ? https://github.com/Courseplay/courseplay/releases
You got (Version: 6.02.00053) FS19_Courseplay.
I just did try it and the Bunker is nicely filled

![fsScreen_2020_09_12_15_13_08](https://user-images.githubusercontent.com/27344744/92996241-8353b280-f50a-11ea-9a4c-b136974f4775.png)

**Comment by enderwiggin07** [comment]
Thanks, will test this afternoon.

**Comment by enderwiggin07** [comment]
This seems fixed, the update broke the leveler course so I gave up using courseplay for silage but the problematic mode2 course was no longer having problems.

**Comment by Tensuko** [comment]
Leveling does work... Using it, whats not working for you ?

**Comment by enderwiggin07** [comment]
I don't want to make it a big report because I had settings configured for
pre-update.  I never tried a new course with default settings after the
update, I trust you that it worked.

The mode2 unload course definitely worked fine after update.

**Comment by Tensuko** [comment]
So as this one seems fixed, will close it.
