### ISSUE TITLE
Field Supply mode Truck Speed Not Return to Street Speed After offloding Liquid

### ISSUE THREAD

**Issue by betrox007** [Courseplay/courseplay#6061]
Dear All.. first of all Thanks for the effort for develop this mod, its highly appreciated..
i just want report the problem i got when using course play field supply mode for transporting slurry from Slurry Pit to the portable slurry tank at field, after offloading Slurry to the portable tank at field the downhiller speed not return to maximum speed but it's maintain speed at 10 km/h.
i'm sorry if i'm wrong to understand this function, but basically i set up course with start point at slurry pit then add waiting point aside of portable slurry tank at field and the end point before the slurry pit, also i'm sorry if this issue maybe duplicated with the another early issue, I've search entire open issue but can't find similar issue. 

map Green River 2019 map, and Vehicle all using vanila vehicle

Log attached and some screen capture.

This Picture show the field worker can't do refill while the downhiller offloading to the tank
![fsScreen_2020_09_12_14_32_16](https://user-images.githubusercontent.com/56646850/92990749-0aa02680-f509-11ea-99c2-e3dc4c8823f9.png)

This Picture is the waiting point for offloding
![fsScreen_2020_09_12_14_07_17](https://user-images.githubusercontent.com/56646850/92990735-ee9c8500-f508-11ea-82ee-4303d11e5871.png)

This picture is when i stop the downhiller cause its speed only 10 km/h after offloding to the tank in field
![fsScreen_2020_09_12_14_10_20](https://user-images.githubusercontent.com/56646850/92990744-007e2800-f509-11ea-9293-ee4ba2c5737a.png)

This Picture is the downhiller speed return to maximum after restart the course play
![fsScreen_2020_09_12_14_10_32](https://user-images.githubusercontent.com/56646850/92990745-04aa4580-f509-11ea-89ce-e12039015554.png)

This Picture is the field work course setting with refill course 
![fsScreen_2020_09_12_14_07_50](https://user-images.githubusercontent.com/56646850/92990738-f4926600-f508-11ea-9ac0-8eb9726df832.png)

This Picture is the downhiller full course preview
![fsScreen_2020_09_12_14_06_39](https://user-images.githubusercontent.com/56646850/92990731-e7757700-f508-11ea-9bc5-9324ca7aa703.png)

[
[log.txt](https://github.com/Courseplay/courseplay/files/5212378/log.txt)
](url)
thank's and best regards

**Comment by Tensuko** [comment]
Yea we have some problems with the speed but we working on it, still a bit problematic but I hope we can fix it with the next version.

**Comment by betrox007** [comment]
@Tensuko  Thanks for the explanation so this is a known bug right?, so i think for a while if we use this mode, what we do is restarting the driver once he finish offloading and do  a loop..
hopefully the team can solve this...

**Comment by schwiti6190** [comment]
@betrox007 is this one fixed with the newest verison ?

**Comment by betrox007** [comment]
@schwiti6190 thanks my man.. i will try it to night, and see it...
