### ISSUE TITLE
Tractor doesn't find combine on the field

### ISSUE THREAD

**Issue by fabiancolfarming** [Courseplay/courseplay#6062]
Dear All,

I found this problem in the pacific northwest - when I activate courseplay to unload the combine everything looks ok - courseplay find combine on choosen field but tractor with trailer not... It's shown, that non cobine is founded. Could you please help?
What more info do you need?

**Comment by Tensuko** [comment]
Did you check #5272 and wiki on how it works ? There is also needed information.

**Comment by fabiancolfarming** [comment]
Ahh yes - sorry for my stupid question. When I use Courseplay also in Combine everything is ok. Thanks a lot!
