### ISSUE TITLE
Couseplay findet keinen Drescher egal welche Map

### ISSUE THREAD

**Issue by Scoocker1988** [Courseplay/courseplay#6063]
Guten Tag
Der Couseplay findet wenn man tanken und abfahren möchte keinen Drescher mehr. Früher konnte man auf manuell schalten und es ging.
Können Sie sich das mal ankucken?
Vielen dank log ist dabei.
[log.txt](https://github.com/Courseplay/courseplay/files/5212711/log.txt)
![IMG_20200912_150804](https://user-images.githubusercontent.com/70837189/92996361-49cf7700-f50b-11ea-9641-4d5b41867e71.jpg)
![IMG_20200912_151057](https://user-images.githubusercontent.com/70837189/92996363-4b993a80-f50b-11ea-8df3-dc464234a62d.jpg)

**Comment by Tensuko** [comment]
#5272 und Wiki lesen https://github.com/Courseplay/courseplay/wiki

**Comment by Blumi39** [comment]
Versuch mal dein Course auf dem Vorgewende starten und enden zulassen....nicht neben den Feld hatte ich auch mal und da gab es Probleme...

**Comment by Tensuko** [comment]
Hat damit nichts zu tun.

**Comment by Scoocker1988** [comment]
Habew soweit alle mods rausgelöscht damit es keinen Konflikt gibt.

**Comment by lexion780** [comment]
ich hab auch das selbe problem.

**Comment by lexion780** [comment]
ich benutze weiter denn Courseplay  v6.01.00399 damit geht das noch.

**Comment by Tensuko** [comment]
Arbeitet dein Drescher mit CP ?

**Comment by Scoocker1988** [comment]
Nein habe ich nicht eingestellt. Ich benutze den Courseplay nur zum ab tanken und abfahren.

**Comment by Tensuko** [comment]
Dann wird es auch nicht gehen, siehe #5272 und WikiPage!

**Comment by Scoocker1988** [comment]
Habe den Mähdrescher Kurs aufgezeichnet, gespeichert. Dann Trecker kursaufgezeichnet und findet immer noch nichts.

**Comment by Tensuko** [comment]
'findet immer noch nichts' wer findet was nicht...

- Drescher mit CP Kurs starten

- Mode2 im Abfahrer auswählen, sollte kein Drescher in der Liste auftauchen, einmal den Modus zu Mode5 und wieder zu Mode2 wechseln (sowas wie aktualisieren) dann sollte er auftauchen.

**Comment by Scoocker1988** [comment]
Danke für die Hilfe, ich gebe es auf, findet trotzdem nichts. bleibe bei 6.01.399 der geht wenigstens.
