### ISSUE TITLE
Re-fulling in mode 2

### ISSUE THREAD

**Issue by polosubtil** [Courseplay/courseplay#6064]
Hi guys,

A small thing I wanted to report, not sure about what is happening here and it's not major at all.

When running a course back to the farm for refilling drills, fertilizers, etc. and emptying trailer in the silo, I always use the same route going next to a fuel tanks. All my tractors are usually set to fill up fuel every time.
Now, for refilling courses (with mode 6), it works fine.
But with Mode 2, for some reason the course stop (like I click on "Stop course") as soon as the tractor reach the trigger.

See my log with some debug channels, I didn't which one so I took a guess. I can do it again if you want with the ones you need
[log.txt](https://github.com/Courseplay/courseplay/files/5213239/log.txt)

First picture right before the fuel tank, everything works fine.
![InkedfsScreen_2020_09_12_22_56_13_LI](https://user-images.githubusercontent.com/60451845/93004926-3b557f80-f54c-11ea-8ff0-8ece233e915d.jpg)

Right after hitting the trigger, the Course is stopped and the tractor goes straight for a few meters before stopping.
![fsScreen_2020_09_12_22_57_02](https://user-images.githubusercontent.com/60451845/93004934-46101480-f54c-11ea-9372-50e1a06de966.png)

Not an emergency at all ;)

**Comment by candymant** [comment]
for me is also a problem if my tractor is out of fuel before. I drive to the tractor with a fuel tank then the tractor automatically gets fueled up. but with the newest version, it doesn't. the tractor stops with what he's doing and doesn't refuel but also doesn't start anymore.

**Comment by polosubtil** [comment]
After a few other tries, it actually doesn't work either with Mode 4 + unload course.
So I am not sure anymore it works with Mode 6 + refill course :)

**Comment by schwiti6190** [comment]
@polosubtil could you give a status on this, as I am not sure what this one is about ?

**Comment by polosubtil** [comment]
Hi @schwiti6190 
I just tried with Version 6.02.00063 => Same status, when the tractor is reaching the refuel trigger with Mode 2, it stops the course

**Comment by schwiti6190** [comment]
@polosubtil could you try this problem with the branch "David" ? In my safe game I got it working with this one "https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=124123&title=fs2019".

**Comment by polosubtil** [comment]
I will try again this evening, thanks @schwiti6190

**Comment by polosubtil** [comment]
Great work @schwiti6190 it works now. Thanks a lot mate, CP rocks !!!!!!!!!!!!!!!!!!!
