### ISSUE TITLE
Düngen, Problem beim übergang "Rundherum" zu "Hoch/Runter" (Multitool)

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#6067]
Hallo Leute
wenn ich einen Düngerkurs abfahre,
1x Rundherum, Scharfe Ecken, dann hoch/runter hat der cp fahrer probleme beim übergang dazu
das ist der Kurs:
![fsScreen_2020_09_13_08_48_28](https://user-images.githubusercontent.com/24860501/93012528-89e13900-f5a1-11ea-9abd-f95a6a104a59.png)

wenn es zum Übergang kommt fährt der Fahrer (Fendt939 mit Bredal Düngerstreuer - Giants Fahrzeuge) einen kompletten unsinn zusammen:
![fsScreen_2020_09_13_09_00_18](https://user-images.githubusercontent.com/24860501/93012551-b5642380-f5a1-11ea-90b7-f43cd10aef86.png)
![fsScreen_2020_09_13_09_00_24](https://user-images.githubusercontent.com/24860501/93012554-b8f7aa80-f5a1-11ea-825e-9b88a8afae48.png)
![fsScreen_2020_09_13_09_00_29](https://user-images.githubusercontent.com/24860501/93012556-bac16e00-f5a1-11ea-8dda-f78cccefb626.png)
![fsScreen_2020_09_13_09_00_32](https://user-images.githubusercontent.com/24860501/93012557-bd23c800-f5a1-11ea-87ca-41e60db837c0.png)
![fsScreen_2020_09_13_09_00_41](https://user-images.githubusercontent.com/24860501/93012559-beed8b80-f5a1-11ea-9644-f036e6a065c7.png)
![fsScreen_2020_09_13_09_00_45](https://user-images.githubusercontent.com/24860501/93012563-c2811280-f5a1-11ea-93f3-ab1f2deb9f0e.png)
![fsScreen_2020_09_13_09_00_50](https://user-images.githubusercontent.com/24860501/93012565-c4e36c80-f5a1-11ea-9ea9-87756d81988b.png)
![fsScreen_2020_09_13_09_00_53](https://user-images.githubusercontent.com/24860501/93012567-c6ad3000-f5a1-11ea-8f60-19401173c87f.png)
![fsScreen_2020_09_13_09_00_59](https://user-images.githubusercontent.com/24860501/93012569-c90f8a00-f5a1-11ea-9a4c-423a17263159.png)

d.h. er fährt etliche male vor - zurück, schlägt links rechts ein, ...
manchmal fängt er sich wieder und setzt den kurs fort, manchmal verfranzt er sich und bleibt dann hängen 

bei den Scharfen Ecken funktioneirt es Wunderbar:
![fsScreen_2020_09_13_08_59_31](https://user-images.githubusercontent.com/24860501/93012595-feb47300-f5a1-11ea-89c0-1bd5ad5c2189.png)
![fsScreen_2020_09_13_08_59_43](https://user-images.githubusercontent.com/24860501/93012549-b2693300-f5a1-11ea-8480-dddf21fa7b03.png)

generiere ich den kurs mit weichen Ecken hab ich an der stelle auch kein problem, dann fährt der cp fahrer einen normalen bogen beim übergang

lg
andreas

**Comment by Tensuko** [comment]
Setze den Startpunkt für den Kurs mal an die obere akante mittig. Ich meine dann ist der Übergang anders, oder es liegt daran das es nur ein Vorgewende ist.

**Comment by pvaiko** [comment]
@andreasthu ist das neu ab 57?

**Comment by Tensuko** [comment]
Der Kurs sah schon immer so aus wenn man von einem Headland in den Centerpart einen turn hat, geht meistens besser wenn der Start seitlich zu den up/down Linien ist.

**Comment by pvaiko** [comment]
Nicht der Kurs, das Turnmanöver, wie wir alle wissen, es war eine Änderung in Turnmanövers in 57.

**Comment by andreasthu** [comment]
K.a. hab ich heute erst bemerkt.
Meinst du an der langen Seite an der NW Ecke?
Weil dann fährt der cp diese eine Seite quasi doppelt,  d.h. 1x leer.
Oder meinst du an der lange Seite, nahe der SW Ecke?
Ist halt blöd, weil meine AD kurse alle so angelegt sind, das die Feldzufahrt an der Stirnseite des Feldes liegt, damit die CP kurse eben stirnseitig beginnen.
Muss mal testen ob das beim grubbern bzw säen,  (angehängt oder dreipunkt) und bei selbstfahrspritzen ebenso ist.
Lg
Andreas

**Comment by Tensuko** [comment]
Mach es lieber so:
![fsScreen_2020_09_13_17_50_03](https://user-images.githubusercontent.com/27344744/93022615-7a3a1280-f5ea-11ea-95cd-6752df13666f.png)

**Comment by andreasthu** [comment]
> Mach es lieber so:
> ![fsScreen_2020_09_13_17_50_03](https://user-images.githubusercontent.com/27344744/93022615-7a3a1280-f5ea-11ea-95cd-6752df13666f.png)

Ja, so funktioniert es.
Kann man das courseplay beibringen,  damit man die Änderung nicht bei jeder kursgeneriering machen muss?
Lg
Andreas

**Comment by pvaiko** [comment]
@andreasthu klar das ist ein Bug

**Comment by andreasthu** [comment]
> Mach es lieber so:
> ![fsScreen_2020_09_13_17_50_03](https://user-images.githubusercontent.com/27344744/93022615-7a3a1280-f5ea-11ea-95cd-6752df13666f.png)

ich hab da nochmal einen versuch gemacht
und zwar hab ich die punkte auf der position gelassen und nicht verschoben,
dafür aber aus "TurnStart" und "TurnEnd" zwei normale wegpunkte gemacht
(mit dem ingame editor)
das ergebnis sah so aus:
![fsScreen_2020_09_15_00_51_38](https://user-images.githubusercontent.com/24860501/93146000-0d0fa580-f6ee-11ea-9951-0d04f666a4e7.png)
so funktioniert das auch, deine methode des wegpunkt verchiebens ist aber schneller
lg
andreas

**Comment by rohne83** [comment]
Mit der manuellen Kursbearbeitung bekommt man es durch Ausnutzung des Vorgewendes auch hin, das Feld auch just bei diesem Übergang Feldreihe->Vorgewende bzw Gegenrichtung, sauber abarbeiten zu lassen. Das war ja bei bei https://github.com/Courseplay/courseplay/issues/6330 noch offen, aber ist dann wohl tatsächlich hier besser aufgehoben. In den Screenshots mal der Übergang in beiden Richtungen, also Ernte vom Vorgewende auf die Feldreihen, und umgekehrt bei der Bodenbearbeitung von den Feldreihen zum Vorgewende:
![fsScreen_2020_11_23_18_28_26](https://user-images.githubusercontent.com/71030138/99995649-f1dea780-2dba-11eb-9cc5-dc22ff7a2a62.png)
![fsScreen_2020_11_23_17_06_07](https://user-images.githubusercontent.com/71030138/99995152-46cdee00-2dba-11eb-8e57-fbc5ff649023.png)
Und das ganze ohne jegliche Rückwärtsfahrt. Wäre in meinen Augen wünschenswert wenn der Kursgenerator oder der Pathfinder das irgendwann selbst so hinbekommt. Klappt ohne Rückwärtsfahrt und Feld zu verlassen natürlich nur wenn man zumindest zwei Bahnen fürs Vorgewende hat (kann man ja vielleicht ebenfalls abhängig von der Einstellung "Wende auf dem Feld" machen).

**Comment by Tensuko** [comment]
Der Bogen den du da eingebaut hast, das soll an sich der generieter turn erledigen.
Das Problem hier ist nun mal, du hast es jetzt für die Maschine, für den Arbeitsbreite so hingekrigt.
Versuch das mal mit nur 2M Arbeitsbreite. Da wird der Bogen schon wieder anders aussehen, das heist der Kursgenerator müsste das berücksichtigen, statt dass der turn entsprechend der Arbeitsbreite generiert wird. :)

**Comment by pvaiko** [comment]
>  Wäre in meinen Augen wünschenswert wenn der Kursgenerator oder der Pathfinder das irgendwann selbst so hinbekommt

Ja, wir arbeiten dran.

**Comment by rohne83** [comment]
Also in meinen Augen sieht das mittlerweile schon sehr sehr gut aus. Nicht alle mögliche Varianten durchprobiert, aber zumindest bei meinen Standard-Arbeitsmustern wurde bisher alles sauber bearbeitet, ohne dass er sich irgendwo verheddert. Also der Übergang vom Vorgewende zu den Feldreihen (meistens Lands oder spiralförmig) beim Dreschen/Häckseln, bzw in der Gegenrichtung bei der Bodenbearbeitung (oftmals mit Reihen überspringen oder kreisförmig).
Nur bei Verbänden hatte es noch nicht geklappt, da war noch das alte Verhalten, dass genau in der Bahn geblieben und ohne auszuholen in die Feldreihen gestochen wurde. Wobei ich grad aber nicht weiß mit welcher Version das war.
Gepflügt hab ich seitdem auch noch nicht, daher kann ich dazu noch nix sagen. Aber wie gesagt, sieht auf jeden Fall schonmal gut aus.

**Comment by Tensuko** [comment]
Wie ist der Stand hier ?

**Comment by andreasthu** [comment]
Klappt wunderbar.
Kann von mir aus geschlossen werden. 
Lg
Andreas

**Comment by rohne83** [comment]
bei einzelnen Maschinen funktioniert es gut, ja. Probleme machen noch die Fahrzeugverbände. Zumindest beim Dreschen bekommt der Drescher auf der innersten Vorgewendebahn (also in der Regel der letzte des Verbandes) seine Kurve in die Feldreihen noch nicht anständig hin, sondern lässt dann just dort ein recht großes Stück Frucht übrig bis er richtig in seine Spur gefunden hat:
![fsScreen_2021_01_16_17_23_04](https://user-images.githubusercontent.com/71030138/105626681-98820b80-5e31-11eb-8801-38a3a9038115.png)
![fsScreen_2021_01_17_14_29_57](https://user-images.githubusercontent.com/71030138/105626696-b94a6100-5e31-11eb-911b-92ea1987609a.png)

**Comment by pvaiko** [comment]
See also #6629

**Comment by Tensuko** [comment]
Wurde das Problem noch weiterhin beobachtet, oder können wir das als erledigt betrachten? :)

**Comment by rohne83** [comment]
Es ist noch nicht ganz perfekt, der Letzte im Verband lässt immer noch einen kleinen Rest stehen, aber bei weitem nicht mehr so viel wie in den letzten Screenshots. Ich denk mal damit kann man leben und der Issue hier kann zu.
