### ISSUE TITLE
Using multiple tools on a field

### ISSUE THREAD

**Issue by Sgt-Christ** [Courseplay/courseplay#6068]
v6.02.00056 
using JD 8R 410, and JD 915 9 shank plow.
on a dedicated server
Setting up a course to plow a field using multiple tools. Lane offset does not work, and tool offset does not work. No errors on the game log or server log.

**Comment by Sgt-Christ** [comment]
![fsScreen_2020_09_13_02_35_10](https://user-images.githubusercontent.com/70423797/93012982-2982d500-f56a-11ea-98a7-e54734b5f2b6.png)

**Comment by Tensuko** [comment]
#5961

**Comment by Tensuko** [comment]
Closing couse of Duplicate
