### ISSUE TITLE
Ich habe ein Problem mit CP

### ISSUE THREAD

**Issue by RudiBergfeld** [Courseplay/courseplay#6070]
oft wenn ich eine Zeit Spiele kommt dieses Fenster,  wenn ein Fahrzeug unterm Trigger steht,
![Fenster 1](https://user-images.githubusercontent.com/10323527/93022944-10bb0380-f5ec-11ea-986a-47326b7a38f8.png)ich habe schon alle mods aus dem ordner verbannt  wenn Cp dazu kommt habe ich dieses Probem. Ich hoffe ihr könnt mir weiter helfen
[log.txt](https://github.com/Courseplay/courseplay/files/5214525/log.txt)

**Comment by eric4072** [comment]
Hallo!

same here...

mir ist aufgefallen dass man, wenn CP von einem Silo belädt, man das Beladen mit "R" beenden kann, auch wenn man nicht in dem Fahrzeug ist. Wenn du selber mit einem Fahrzeug fährst kannst du genau in diesem Moment nichts aus einem Silo laden. bin auch schon mehrmals darauf reingefallen....

**Comment by Tensuko** [comment]
Ist bereits bekannt.
Könnte an AD liegen, kann an GC liegen, auf alle Fälle ist das etws tricky mit GC Triggern.
Könnte mit dem nächsten Update für Trigger gelöst sein, auf alle Fälle, hier gehts weiter: #6027
