### ISSUE TITLE
BOURGAULT seeder dosen't work with augerwagon refill

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/courseplay#6072]
Hello everyone,

Well I'm not sure if it's a issue or problem but I'm just trying to set up a course for BOURGAULT tools. We all know that the seeders have a arm which needs to be first extended to load anything. Can anyone help me how to set up a course that when the tank is empty the tractor will drive to the seed tank/shop and load ? 

Regards

**Comment by Tensuko** [comment]
That one cant be auto refilled yet.
With the big seeder it will be almost impossible to drive by at any trigger or auger wagon.
I don't think we can do here anything but I will have a look...

**Comment by schwiti6190** [comment]
@Tensuko We could make it possible to work with augerwagons refilling, just have to make sure that the seeder gets unfolded before it reaches the augerwagon and the course is correctly setup with enough distance to the augerwagon.

**Comment by Tensuko** [comment]
@schwiti6190 
actually would just need to unfold early enough and the course must be 100% correct as we just have a very smal target area + a big seeder behind is that also have to bypass the auger wagon with its pipe unfolded.

**Comment by Twetch** [comment]
I don't see any duplication between this and my suggestion just about option to extend auger ,when driver stop in the field and want refill, to let you manually refill seed cart without stopping cp.
