### ISSUE TITLE
Warning lights alway on and unloading problem.

### ISSUE THREAD

**Issue by SirAdams** [Courseplay/courseplay#6073]
I have set Warining lights on road but W.L. is alway on. 
v6.02.00058

**Comment by SirAdams** [comment]
No unloading occurs if the vehicle becomes full after turning.
![20200914011929_1](https://user-images.githubusercontent.com/2748305/93031073-5bf30780-f628-11ea-9097-1a028fd38d33.jpg)

**Comment by SirAdams** [comment]
When Ropa Keiler 2 drives too close to the trailer while harvesting potatoes, the harvesting of potatoes is stopped and it is not resumed until the end of the field. Potatoes cannot be harvested during the unloading mode.

**Comment by SirAdams** [comment]
Error after complete order. 
File with debug mode. 
[log.txt](https://github.com/Courseplay/courseplay/files/5215537/log.txt)

**Comment by SirAdams** [comment]
First, I deleted the route from the tractor and then finished the contact. Even though now I managed to save the game progress, the game got stuck and the game logs were growing.
[log.txt](https://github.com/Courseplay/courseplay/files/5215762/log.txt)
Debug mode with work on field.

**Comment by Tensuko** [comment]
To many Problems in one Issue, this is to chaotic.
First check if there is an Issue with your Problem or Error msg and only then make a new Issue with a proper discription.
