### ISSUE TITLE
Kurse löschen im MP geht nicht warum ?

### ISSUE THREAD

**Issue by supertramper1961** [Courseplay/courseplay#6074]
Hallo

wie oben geschrieben lassen sich keine Kurse im Multiplayer löschen warum eigentlich nicht geht im Singleplayer auch ?

Spiele auf eine 4 Fachmap Svapa Agro alleine und verwende Courseplay eigentlich ein tolles Programm nur was sehr schade ist man kann keine Kurse löschen??

Bitte liebe Entwickler schaut euch das mal an da ich es sehr gerne weiter verwenden würde :-)

Danke und LG...supertramper1961

**Comment by Tensuko** [comment]
Wir wissen das, wir wissen nicht warum, mal eben fixen geht nicht.
Duplicate, closed.
