### ISSUE TITLE
Drescherverband wird bei Kursgenerieren immer auf gleichen Kurs geschickt

### ISSUE THREAD

**Issue by Nekromonger** [Courseplay/courseplay#6075]
Wenn ich einen neuen Kurs generiere werden beide Drescher auf den Selben Kurs übereinander gelegt. Sie erkennen sich zwar aber sie fahren exaxt hintereinander anstatt versetzt

**Comment by Obsiana2019** [comment]
Verband aktiviert, einen auf links und den anderen auf rechts gestellt?

Lg Obsiana

**Comment by Nekromonger** [comment]
Ja gemacht ändert aber nichts an der kurswahl

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by andremeyer123** [comment]
Bei einem 15 meter schneidwerk noch einstellen 7.5 nach rechts und den anderen nach links 
weil nur nach links und rechts einstellen bringt nix da ja 0 eingestellt ist jedenfals bei mir

**Comment by Tensuko** [comment]
Das ist wieder nur halbwissen hier....
Als aller erstes:
Welche Version ?
SP oder MP ?

MP -> funktioniert noch nicht!
SP -> Kurs generieren mit 2 Geräten, wenn der Kurs im Drescher geladen ist, lässt sich in Bahnversatz links und rechts einstellen, da wird nichts mit Metern eingestellt! Wichtig: Man sollte den Kurs nicht an einer Ecke starten lassen.

**Comment by Tensuko** [comment]
Da wir keine Infos bekommen, mache ich hier zu...
