### ISSUE TITLE
Mode 2 and 3 won't work with combines used by players

### ISSUE THREAD

**Issue by Xosk00** [Courseplay/courseplay#6077]
I updated Courseplay to the latest released version (I believe it is version v6.02.00058). I created a new save and also deleted any files I can find related to Courseplay and restarted my computer. After all of that I still have the issue.

The mode works flawlessly with a combine using Courseplay. But when I use the combine personally, the tractor with mode 2 or 3 stops working as well.

Please let me know if I missed something or what I can do to help fix this issue.

Thank you in advanced.
[log.txt](https://github.com/Courseplay/courseplay/files/5222591/log.txt)

**Comment by GeorgeEarslight** [comment]
In FS19 it works only when both combine and unloader are controlled by CP.

**Comment by Tensuko** [comment]
#5272 and Wiki.
As we dont know about this...
