### ISSUE TITLE
Mode 3: Problem mit Annaburger ULW

### ISSUE THREAD

**Issue by rohne83** [Courseplay/courseplay#6080]
Ich habe ein Problem mit dem Annaburger HTS 34.16 (Überladewagen, ist ein Mod vom offiziellen ModHub):
wenn ich ihn am Zugfahrzeug angekuppelt habe, kann ich erstmal ganz normal den Mode 3 einfahren und konfigurieren. Wenn ich dann aber 'Abfahrer einstellen' auswähle, wechselt er von selbst in den Überführungsmodus. ULW-Modus wird ausgegraut und auch nach Entlassen des Abfahrers ist er erstmal nicht mehr verfügbar, sondern erst wenn man ihn ab- und wieder ankuppelt.
Ist bisher der einzige ULW bei dem ich dieses Problem habe. Kann also auch am Mod liegen, aber vielleicht ist tatsächlich auch irgendwo ein sonst kaum auffallender Bug im CP-Code. Eine Idee woran das liegen könnte?
CP Version ist 6.02.00054
Log hab ich erstmal mit Channels 1, 4, 6, 11, 12 angefügt

![annaburger 2](https://user-images.githubusercontent.com/71030138/93261115-8f59a180-f7a2-11ea-8ebb-350073fd3170.jpg)
Zunächst lässt sich alles ganz normal für Mode 3 einstellen.

![annaburger 5](https://user-images.githubusercontent.com/71030138/93261178-a8fae900-f7a2-11ea-9c27-37adaab09639.jpg)
Wenn man dann den Abfahrer startet, wechselt er automatisch in den Überführungsmodus. Mode 3 steht auch nach entlassen des Abfahrers erstmal nicht mehr zur Verfügung

[log_annaburger.txt](https://github.com/Courseplay/courseplay/files/5228141/log_annaburger.txt)

**Comment by Tensuko** [comment]
Alte CP Version (neu .00059) und der ÜLW ist der mit den 2 Kammern, der macht Probleme das kennen wir schon.

**Comment by rohne83** [comment]
Ok. Interessanterweise macht er das Problem auch wenn keine Trennwand konfiguriert, also nur eine Kammer vorhanden ist. Gibts da schon nen Issue zu? Wenn das damit doppelt ist, kann der hier ja eigentlich zu...

**Comment by rohne83** [comment]
Wow, der Fix kam echt schnell. Grad getestet mit dem Branch und funktioniert jetzt wunderbar. Sowohl mit als auch ohne Trennwand. Wenn mit Trennwand, dann merkt er sich sogar welche Kammer man ausgewählt hat, und selbige lässt sich wie es scheint sogar bei aktivem Abfahrer noch umschalten.
Super Arbeit, vielen Dank!
Der Issue hier kann dann mE jetzt wirklich zu.

**Comment by Tensuko** [comment]
Machen wir zu wenn es im Release ist.

**Comment by Lustiger-Hubi** [comment]
@rohne83
Funktioniert überhaupt nicht!
Was schreibst du hier?

**Comment by Lustiger-Hubi** [comment]
@Courseplay Courseplay deleted a comment from Lustiger-Hubi 22 hours ago

Passt euch mein Kommentar nicht? 
Muss ich nur wissen!

**Comment by Tensuko** [comment]
Lieber Hubi, dein Kommentar war, dass rohne offenbar 'Mist' erzählen würde, weil es nicht funktioniert!
Dazu muss ich dir 2 Dinge sagen:
1) Dieser fix ist noch nicht im Release, desshalb ist dieses Issue auch noch offen!
2) Wenn der fix im Release ist und es bei dir noch immer nicht klappt, ist es wenig hilfreich, anderen zu sagen sie würden 'Mist' erzählen, statt selber die nötigen Infos zu geben wie logfile, screenshot etc... Kennst du doch mitlerweile :)

Lass es gut sein, beim nächste mal bitte vorher genau lesen :) Fix kommt mit der hoffentlich nächsten Version! Bis dahin bitte noch etwas Geduld.
