### ISSUE TITLE
Issue with multiple tools and convoy

### ISSUE THREAD

**Issue by haberkornsam** [Courseplay/courseplay#6081]
I am trying to have 6 cotton harvesters running one the same course. When generating the course I set the `Multiple Tools` value to 6. I lined set all the harvesters up on the same course with the following lettings changed
- lane offset (3 Right to 3 Left)
- Symmetric lane change: Activated
- Vehicle Convoy: activated
-- Maximum distance: 50m

The first 5 harvesters all worked perfectly. But the 6th one seems to have a mind of its own. This harvester is set to `3 Right`. It does not want to harvest any of the headlands. Once the headlands are complete, it works fine in the middle of the field.

The same thing happened when I tried to plant using 3 planters. But everything worked perfectly with 2 planters

I know this is a feature not commonly used, but it feels like it should be an easy fix.

Thanks for all you do. I love using CP

**Comment by Tensuko** [comment]
Can you make a screenshot of your course ?
Also when you start the Harvester, I think debugchannel 7 active and then start them and post that logfile.

**Comment by haberkornsam** [comment]
Course Generation:
![20200916111414_1](https://user-images.githubusercontent.com/24964365/93370847-ad5ceb80-f80e-11ea-8996-f06f69b21d01.jpg)

Issue with last vehicle in convoy (this was set to start at first waypoint):
![20200916111803_1](https://user-images.githubusercontent.com/24964365/93370889-ba79da80-f80e-11ea-9276-a88dcbbadfcc.jpg)

Log File:
[log.txt](https://github.com/Courseplay/courseplay/files/5233820/log.txt)

**Comment by envikowaty** [comment]
Btw: that is really nice mod map, could I get the link to it ?

**Comment by haberkornsam** [comment]
@envikowaty Its GreenRiver2019 from modhub

**Comment by game455** [comment]
It is recommended to start course generation of courses with headlands not at corners, specially with more than 1 vehicles

**Comment by pvaiko** [comment]
@haberkornsam I think the problem is the shape of this field, combined with the total width of your tools. The north end narrows quite a bit and it is quite possible that the inner headlands overlap there, in that case the innermost vehicles will have a problem.

Try generating the same course with the same width, but instead of setting the multitool to 3 or 6, set it to 1 and set the number of headlands to 3 or 6 to see how the course of the vehicles looks like.

**Comment by Tensuko** [comment]
Closed due to inactivity, reopen when we got the needed informations.
