### ISSUE TITLE
Fruchtauswahlfenster geht auf und dann geht nix mehr

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#6084]
Hallo liebes CP team. Ich habe da ein kleines problem wurde auch schon bei Autodrive angesprochen aber ich schätze das dieser fehler vom CP kommt.

Mit der version 6.02.00048 kann ich stundenlang spielen ohne das dieser fehler auftritt

Ab der Version 6.02.00049 kommt dieser fehler mit jeder neueren version.

![fsScreen_2020_09_18_00_19_46](https://user-images.githubusercontent.com/3021040/93534429-5ad21b00-f945-11ea-819b-07c8e7e3965a.png)

hier meine LOG: [log.txt](https://github.com/Courseplay/courseplay/files/5242234/log.txt)

MFG Mannie313

**Comment by andreasthu** [comment]
Du hast Global Company 1.7.1
Dasselbe hatte ich auch,
Probier mal, ob das mit der Global Company 1.6.0.1 funktioniert.
Lg
Andreas

**Comment by candymant** [comment]
I used GC 1.6.0.1 and i have still this isseu. And i dont use AD.

**Comment by Mannie313** [comment]
@andreasthu Die felder werden von Cp bearbeitet (grubbern/säen/düngen/pflanzenschutz) und AD nehme ich nur zum abholen.

Die Trigger sind originale und keine vom GC.

MFG Mannie313

**Comment by andreasthu** [comment]
Probier mal die neue v6.02.00060.
Ich habe heute getestet und mit der hast funktioniert:
https://github.com/Courseplay/courseplay/issues/6027
Btw, ich mach es genauso, auf der Karte rumfahren mit AD, Feldbearbeitung mit CP.
Beim dreschen drischt der CP, dann hab ich einen ÜLW Fahrer mit CP, der an einen am feldrand wartenden AD fahrer befüllt, vom Feldrand zum Silo und zurück geht's da mit AD.
Beim Häckseln hab ich einen CP Fahrer, und die Abfahrer fahren mit CP aber auf einem von AD generierten Kurs, dann brauch ich die selber nicht einfahren
Lg
Andreas

**Comment by Mannie313** [comment]
bei mir net. düngen mit Fischmehl und nach ca. 20-30 minuten kommt der fehler.

@pvaiko oder @Tensuko was braucht ihr für debugchannels um das nachzuvollziehen.

MFG Mannie313

**Comment by schwiti6190** [comment]
Also mal einen Schritt zurück geht es um einen GlobalCompany Silo ?, falls ja bitte einmal nen link zu dem Silo.
Zweites falls es an Autodrive, liegt einmal nur mit CP testen.

@andreasthu wenn ich das richtig versteh klappt es bei dir ?

@Mannie313 wobei genau tritt der fehler auf, auf dem Bild kann leider nichts erkennen alternativ ein save game mit Kursen würde helfen das problem nachzuvollziehen.

**Comment by Mannie313** [comment]
ich mach feld 58 Düngen mit Fischmehl. AD nehme ich um wieder aufzufüllen (abholen) und die silos sind Standartsilos vom spiel.

Der fehler kommt nach einer zeit beim nachfüllen.

MFG Mannie313

**Comment by schwiti6190** [comment]
Kannst du bitt einmal in der Konsole: "printDriverVariable state" machen wenn autodrive auf dem nach lade kurse ist ? anschließend ein screenshot (beim eintippen kein leertaste drücken wird automatisch gemacht)

**Comment by Mannie313** [comment]
ok kann ich machen dauert nur etwas.

MFG Mannie313

**Comment by andreasthu** [comment]
@schwiti6190 
Ja bei mir funktioniert es nun, alle drei neueste Version, wie ich in 
#6027 
Geschrieben habe.
Lg
Andreas

**Comment by Mannie313** [comment]
@andreasthu ich habe AD 1.1.0.5 RC6

MFG Mannie313

**Comment by schwiti6190** [comment]
Singleplayer oder Muliplayer ?

**Comment by Tensuko** [comment]
@Mannie313 und RC5 ?

**Comment by Mannie313** [comment]
Multiplayer aber kein Dediserver.

@Tensuko RC5 hat probleme mit dem abladen im MP und Dediserver.

MFG Mannie313

**Comment by Tensuko** [comment]
So ich möchte bitte das einmal forlgendes Versucht wird, was das laden mit GC Triggern an geht:
Nur CP .00060
CP .00060 + RC5
CP .00060 + RC6 (bzw das ist Beta, ein neues Releasecandidate gibt es bei AD noch nicht!)

Wenn es mit der neuesten AD Version zusammen nicht klappt, müssen wir mit den Jungs mal reden ob wir da zusammen eine Lösung finden.

**Comment by Mannie313** [comment]
@Tensuko aktuell habe ich
GC 1.7.1.0
CP 6.02.00048
AD 1.1.0.5 RC6

Ich melde mich nachher nochmal mit der gleichen aufstellung und werde CP und Ad mal Tauschen und meine log anhängen.

MFG Mannie313

**Comment by Tensuko** [comment]
> Always update to the latest build and check if the problem really still exists before reporting issues.

https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
Ich konnte das vorhin reproduzieren, aber auf anderen Weg.
Wenn ein Mode1 Fahrer am GC Silo steht und meldet 'Silo leer, warten auf mehr' und man den Abfahrer entlässt, dann taucht das Fenster auf.

**Comment by candymant** [comment]
My stands in an gc trigger en another mode 1 driver drive in a trigger. Then the pop up appears on the driver that is in de gc trigger. And i can only esc if the other driver leave the gc trigger .

**Comment by Tensuko** [comment]
> 
> 
> My stands in an gc trigger en another mode 1 driver drive in a trigger. Then the pop up appears on the driver that is in de gc trigger. And i can only esc if the other driver leave the gc trigger .

What Version are you using now ?

**Comment by candymant** [comment]
Cp ver 61 the latest
Gc 1.7.1.0

**Comment by Mannie313** [comment]
@Tensuko aktuell habe ich
GC 1.7.1.0
CP 6.02.00061
AD 1.1.0.5 RC6

wen ich esc drücke und das wiederholt das sich das fenster schliesst kommt folgende meldung:
Warning: Tried reverting to input context [] which is not defined.

[log.txt](https://github.com/Courseplay/courseplay/files/5248201/log.txt)

MFG Mannie313

**Comment by Tensuko** [comment]
Bitte mal mit der neuesten Version testen. Ich konnte das nicht mehr provozieren auch nicht mit AD zusammen.

**Comment by candymant** [comment]
for me it works fine now.

**Comment by Mannie313** [comment]
ok teste ich heute mittag

MFG Mannie313

**Comment by schwiti6190** [comment]
Ich schließe das hier mal, sollte der fehler wieder auftauchen einfach wieder öffnen :)
