### ISSUE TITLE
Silo aufschütten

### ISSUE THREAD

**Issue by rellek010682** [Courseplay/courseplay#6086]
Das Silo aufschütten geht ja nur mit Schiebeschild im Heck. Kann man das programmieren, dass das Schild auch an die Front kann?

**Comment by Tensuko** [comment]
Was spricht dagegen das am Heck zu montieren ?

**Comment by rellek010682** [comment]
Ich würde CP gerne realer fahren lassen.
Ich arbeite im realen Leben während der Maisernte nebenher bei einem Lohnunternehmen. Wir schieben mit Xerion 3800VC mit Schiebeschild in der Heckhydraulik und knapp 5 Tonnen Gewicht in der Front. Bei gedrehter Kabine hat man so eine bessere Übersicht.

**Comment by Tensuko** [comment]
Ah okay verstehe, ja das könnte schwer werden weil der kurs ja extra fürs rückwärts fahren aufgezeichnet wird.

**Comment by rellek010682** [comment]
Schade. Naja, dann schließen wir das Thema an dieser Stelle.
