### ISSUE TITLE
Abfahrer finden Drescher nicht

### ISSUE THREAD

**Issue by Phips99** [Courseplay/courseplay#6087]
Hallo,

ich spiele auf der MVP 19 und dresche Feld 3 mit einem John Deere Drescher und John Deere 7r 350. Ich hab den Kurs eingefahren und den Drescher gestartet. Den Abfahrer gestartet und er findet den Drescher nicht. Da kommt eine Meldung "Kein Drescher in Reichweite" obwohl ich das Kreuz bei dem Drescher aktiviert habe.
[log.txt](https://github.com/Courseplay/courseplay/files/5246532/log.txt)

**Comment by Tensuko** [comment]
Fahren deine Drescher denn mit CP ?

**Comment by Phips99** [comment]
Ja der Drescher fährt mit Cp im Modus 6 und generiert wurde der Kurs über die Map (ohne Feldrandkurs).

Die Abfahrer sind im Modus 2 und der Kurs ist von mir eingefahren.

**Comment by Tensuko** [comment]
Drescher voll ?
Ansonsten logfile mit debugchannel 4 7 12 und 14 bitte (#5272 [Wiki] )

**Comment by Phips99** [comment]
also:
Ich hab den Drescher gestartet. Er ist 100 % voll. Danach den Abfahrer gestartet. Er fährt zuerst die Route zum Abladeort ab und danach zum Ausgangspunkt. Er findet den Drescher und fährt hin, doch er hält 50 m davor an. Warum auch immer. 


![20200918203043_1](https://user-images.githubusercontent.com/49783287/93633242-efdd1e80-f9ee-11ea-9c49-d7cab90d5b17.jpg)
Das zweite Mal fuhr er vom Feld zum Ausgangspunkt und hat den Drescher wieder gefunden. Er fährt zu ihm dreht hinter ihm um und fährt in Schlangenlinien an ihm vorbei.
![20200918203352_1](https://user-images.githubusercontent.com/49783287/93633322-126f3780-f9ef-11ea-8df0-01084e551af5.jpg)


[log.txt](https://github.com/Courseplay/courseplay/files/5247576/log.txt)

**Comment by Tensuko** [comment]
Bitte noch mal mit .00061 probieren, da im .00060 Verbesserungen im Mode2/Mode3 vorgenommen wurden.
https://github.com/Courseplay/courseplay/releases
Wenn es wieder so aussieht, noch mal logfile mit channel 4 7 12 und 14 bitte.

**Comment by Phips99** [comment]
Ich habs mit der 00061 ausprobiert. Hab zuerst den Drescher gestartet, alles normal. Bin in den Abfahrer gesprungen und hab ihn auch gestartet. Plötzlich spamt Cp in die Konsole einen Fehler und ich kann die Kamera nicht mehr bewegen. Der Abfahrer fährt auch nicht mehr los. Spiel ist somit freezed.

![20200919163552_1](https://user-images.githubusercontent.com/49783287/93669987-f96e9100-fa97-11ea-8b40-61696ad751a0.jpg)

[log.txt](https://github.com/Courseplay/courseplay/files/5250032/log.txt)

**Comment by Tensuko** [comment]
@schwiti6190 was könnte das denn jetzt noch sein ?

**Comment by Tensuko** [comment]
@Phips99 die .00062 probieren, da sind auch wieder einiges an Änderungen und fixes drin.

**Comment by Phips99** [comment]
Immer noch die Fehler und die Probleme. Keine Veränderung.

[log.txt](https://github.com/Courseplay/courseplay/files/5250204/log.txt)

**Comment by Tensuko** [comment]
Also was ich in deiner log sehe ist, dass du 4 Maps drin hast, wobei eine voll mit Scripten ist.
Das ist eigentlich ein NoGo. Immer nur eine Map im mods Ordner.

@schwiti6190 in der log geht der Fehler so los:
2020-09-19 18:56 :54 [info lp4926] 350 (#2): AI driver in mode 2 starting at 200/222 waypoints (COURSEPLAY_NEAREST_POINT)
2020-09-19 18:56 Error: Running LUA method 'update'.
2020-09-19 18:56 C:/Users/Philipp/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/TriggerHandler.lua:1226: attempt to index local 'currentDischargeNode' (a nil value)

**Comment by schwiti6190** [comment]
Ich kann den lua fehler morgen weg machen aber am problem wirds nicht liegen mit dem drescher, eher am mod

**Comment by Tensuko** [comment]
Das ist Kaweco Pullbox 8000H, der soll mit allen fillTypes funktionieren.
Im ersten Screenshot ist wieder mal ein Traffic Conflict, weil er die Spur vom Drescher kreuzt.
Im zweiten Screenshot scheint was mit dem Ziel nicht gestimmt zu haben, weil er weiter vorne ist (vorrausgesagte Position wo Drescher ankommen soll) trotzdem will er zu UNLOADING_STOPPED_COMBINE und dann kam der LUA Error wo ich keine Ahnung habe.

**Comment by schwiti6190** [comment]
@Phips99 kannst du es mal mit nem standart giants anhänger probieren sieh nach einem Mod problem aus ?

**Comment by Phips99** [comment]
gleiche Problem

[log.txt](https://github.com/Courseplay/courseplay/files/5251582/log.txt)


Vielleicht liegt es am Drescher oder am John Deere? Meine Vermutung

**Comment by Phips99** [comment]
Schon irgendwas rausbekommen an was es liegt?

**Comment by Tensuko** [comment]
Nein.
Welchen JD Drescher hast du denn da ?
Den Trailer habe ich....

**Comment by Phips99** [comment]
Den John Deere STS Serie 2007-2010 von Siid Modding.

https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=173234&title=fs2019

**Comment by Tensuko** [comment]
Ich schau mal ob ich morgen dazu komme den zu testen :)

**Comment by Phips99** [comment]
ok danke für die Mühe

**Comment by Scoocker1988** [comment]
Seit 6.02 kann man das mit dem Drescher vergessen wenn er findet, fährt er nicht los. gleiches 6.03. Letzte gute Version ist die 6.01.399.ng

**Comment by Tensuko** [comment]
Ich mach hier zu weil es funktioniert...
