### ISSUE TITLE
Mehrere Trigger anfahren

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#6089]
Guten Morgen! Hab eigentlich nur eine Frage! Was muss ich machen damit Coureseplay z.B. bei mehreren Tierställen alle Futter trigger befüllt?? Jetzt befüllt er nur einen und schreibt dann "Farmsilo ist voll fahr mit den nächsten fort" und macht nichst mehr! LG

**Comment by Tensuko** [comment]
Er bleibt also beim vollen Trigger stehen ?

**Comment by LamaiK** [comment]
Ja bleibt am vollen Trigger stehen. Hab das gleiche. Lässt sich dann auch nicht mehr weg bewegen, muss entlassen werden.

**Comment by Paul2510** [comment]
Ja befüllt den Trigger beim Stall und wenn voll ist meldet er "Farmsilo ist voll fahr mit den nächsten fort" und bleibt stehen! mann muss ihn entlassen
