### ISSUE TITLE
2 Fehler beim Gülle düngen

### ISSUE THREAD

**Issue by Schlabbeseppel** [Courseplay/courseplay#6092]
Setup: Gülledünger Samson PG II 35 mit SBH4 36 an Fendt 1050, das Ganze zweimal, Courseplay 6.02.00060
Kombinierter Kurs: 1x Gülle tanken an ISS Modell, 1x Gülle ausbringen auf dem Feld
Die beiden Kurse werden sauber abgefahren, allerdings passiert folgendes:
Der Gülledünger fährt die ganze Zeit max. 10 km/h beim düngen und auftanken, obwohl ich am Fahrzeug höhere Geschwindigkeiten eingestellt hab. Max. Arbeitsgeschwindigkeit sollte eigentlich 17 km/h und beim auftanken full speed sein.
Zweites Problem: wenn diese beiden Kurse mit den beiden Fahrzeugen aktiv sind, kann ich mit anderen Fahrzeugen keine Früchte tanken. Das Fenster "Befüllung starten" öffnet sich", aber dann passiert nichts mehr. Paletten aufladen geht.
Wenn die beiden Kurse beendet sind, ist dieses Problem wieder behoben.

**Comment by Tensuko** [comment]
Sollte mit der nächsten Version behoben sein.
Wenn eines davon noch mal auftritt, bitt die Prbleme in einzelne Issues packen.
