### ISSUE TITLE
Question about mode 3

### ISSUE THREAD

**Issue by Horozor** [Courseplay/courseplay#6093]
Can someone explain me how the fk this mode working? 
Situation. I have truck near the large field with semitrailer. It wait for augerwagon, which work with harvester.
When i record course i start at field, go to semitrailer set parking point where augerwagon must unload in the future and go forward a couple meters, stop.
BUT this is dont working correct.
Augerwagon go to harvester, unload it and go to semitrailer. It work only 1 time.
Next time wagon go to harvester then go to unload course, and it stay near start point. So what i did wrong? 
Also i use autodrive for truck which waiting near field, but same problem without autodrive
[Video](https://youtu.be/VnQ0Z9JDowI)
[Log](https://gist.github.com/Horozor/f0ced02781d4bafd32af09ba68cd4059)
Today I decided to play the farm after a long vacation and immediately a bunch of bugs in the new version.😒

**Comment by Tensuko** [comment]
debugchannel 4 7 12 and 14

**Comment by Horozor** [comment]
@Tensuko 
[log](https://gist.github.com/Horozor/fcbefe833359612a93f3fdcab556f748)

**Comment by pvaiko** [comment]
@Horozor this last log seems to be fine, it says:
2020-09-19 23:30 :03 [dbg4 lp21056] 6195 M (#2):  -> N/A: Wait point reached, wait for trailer.
2020-09-19 23:30 :03 [dbg4 lp21057] 6195 M (#2):  -> N/A: Trailer is here, opening pipe

Do you have a log with 4, 7, 12 and 14 when the problem occurs?

**Comment by Horozor** [comment]
@Tensuko 
In Previous log problem occurs
and in this.
There were also several collisions as usual
I shot video for show you how this is work. Enjoy
[Video](https://youtu.be/_8aJ_DV2nm8)
[Log](https://gist.github.com/Horozor/590c865aaa14b0c777f94ea6037dc89e)

**Comment by Tensuko** [comment]
I guess we miss a reset or something... IS_UNLOADING ?
![fsScreen_2020_09_20_12_05_23](https://user-images.githubusercontent.com/27344744/93708816-9cc3b280-fb39-11ea-957c-2724f90c60f1.png)

**Comment by pvaiko** [comment]
I may be missing something but what exactly is the problem now? @Horozor that video is 20 minutes, can you please get me when exactly the problem is happening there (I'm not interested in the collisions, the other problem)

**Comment by Horozor** [comment]
@pvaiko 
7:20-11:10 1st unload, pass
16:20 to the end 2nd try and fail

**Comment by Horozor** [comment]
@pvaiko 
Try using these keys
![03-b](https://user-images.githubusercontent.com/37561569/93710731-7f9ade00-fb51-11ea-9e22-cefa7df090e6.jpg)

**Comment by pvaiko** [comment]
No need to be an asshole. I asked you for additional information so I don't have to spend 20 minutes to find your problem.

**Comment by pvaiko** [comment]
7:20 is two problems all known, we are working on it, but I have to tell you, the way you are trying to resolve that collision manually isn't much smarter than CP's driver... 

I'll look into the other one.

**Comment by pvaiko** [comment]
@Horozor so I don't know why it did not open the pipe when it got there first, but when you stop and restart it make sure you select 'first waypoint' or 'nearest waypoint', not 'unloading'.

**Comment by Horozor** [comment]
@pvaiko 
Restart method in this case doesn't matter. So i got it, mode 3 don't work at this time. And sorry if my previous post hurt your feelings, it was just a joke

**Comment by Horozor** [comment]
@pvaiko 
Here is short video (2 mins) where i easily reproduce problem. At 2nd try traktor stop near Strat point and you can see loadingState: IS_UNLOADING just like on @Tensuko's scrennshot above
[Video](https://youtu.be/9qzIRVlACPo)
[Log](https://gist.github.com/Horozor/3848c75cf458bb6d655bd7d328a9f7a3)
