### ISSUE TITLE
mode 1 driver slow approach gc trigger.

### ISSUE THREAD

**Issue by candymant** [Courseplay/courseplay#6095]
hi,
mode 1 driver approach the GC trigger to 0-1 km/u when another mode 1 driver is waiting for more to load on a GC trigger.
I use the latest version and here is the log with debugging channel 2.
[log.txt](https://github.com/Courseplay/courseplay/files/5250710/log.txt)

1e mode 1 driver slowly approach the gc trigger while other mode 1 driver is waiting for more in another gc trigger.
![fsScreen_2020_09_19_23_45_12](https://user-images.githubusercontent.com/47895720/93690290-e62ee600-fad6-11ea-8e8c-4804ab279bf8.png)
![fsScreen_2020_09_19_23_44_56](https://user-images.githubusercontent.com/47895720/93690297-f2b33e80-fad6-11ea-9eb0-18bc0b44997e.png)

**Comment by schwiti6190** [comment]
Thanks for the issue replay, sadly I have now idea how this one would be related to gc_trigger, so if you could try the same with non gc_triggers that would be helpfull to check, if it is really only with gc_triggers.

**Comment by candymant** [comment]
I will do that. and I reply shortly.

**Comment by candymant** [comment]
here is the log with the giants triggers only.
[log.txt](https://github.com/Courseplay/courseplay/files/5251333/log.txt)

1st driver is waiting for more en 2cnd driver is approaching the trigger.
![fsScreen_2020_09_20_10_53_39](https://user-images.githubusercontent.com/47895720/93707620-7f3e1b00-fb30-11ea-890e-9a08bef9a0f5.png)

![fsScreen_2020_09_20_10_55_44](https://user-images.githubusercontent.com/47895720/93707634-9aa92600-fb30-11ea-842d-40f8e9060f93.png)

**Comment by candymant** [comment]
so it is only with GC triggers.

**Comment by schwiti6190** [comment]
@candymant This problem is quite specific, so I would appricate if you could create a savegame with the gc_triggers + mod links and post it here with your courses. Then I can have a look at the problem :)

**Comment by candymant** [comment]
apparently, the slow approach is away but I have other issues.
if a mode 1 driver is in a GC trigger like this.
![fsScreen_2020_09_22_23_07_16](https://user-images.githubusercontent.com/47895720/93937873-b7a84980-fd28-11ea-8252-c92f8a41e2b7.png)

then the other mode 1 driver will not load on the GC trigger if there is not enough but there is still in it. he says that the farm silo is empty and waiting for more.
![fsScreen_2020_09_22_23_07_02](https://user-images.githubusercontent.com/47895720/93938177-284f6600-fd29-11ea-9d73-07ab564fe8f8.png)

and if the first mode 1 driver is in a GC trigger waiting for more then de second mode 1 driver doesn't load but keep driving around
![fsScreen_2020_09_22_23_03_07](https://user-images.githubusercontent.com/47895720/93938942-571a0c00-fd2a-11ea-8d2b-f3aeae7bb240.png)

here is also the log with channel 2 active
[log.txt](https://github.com/Courseplay/courseplay/files/5264075/log.txt)

**Comment by schwiti6190** [comment]
@candymant Thx for the repeated feedback and testing :) It would be nice if you could reduce your mods to the minimum, let's say only the global comany triggers and one of the default maps. The links to the mod triggers and I will have a look at this problem :)

**Comment by candymant** [comment]
this is for the diesel tank.[http://www.farmingsimulator19mods.com/global-company-remote-diesel-storage-fixed-by-stevie-fs19/](url)
en this is the liquid silo mod.[https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=157277&title=fs2019](url)

i try it on the standard map felsbrunn.
here is the log.
[log.txt](https://github.com/Courseplay/courseplay/files/5299341/log.txt)

**Comment by candymant** [comment]
the problem is if the one driver is waiting for more as the diesel tank is empty than the second driver just keeps circling.

**Comment by candymant** [comment]
the problem is solved with the latest version.
for me this issue is solved.

**Comment by schwiti6190** [comment]
Seems like a nice coincidence that I got to solve this one :) If there are any more problems then feel free to create a new issue and thanks for your help :)

**Comment by candymant** [comment]
No problem.
