### ISSUE TITLE
Multiple harvester don't work in MP

### ISSUE THREAD

**Issue by Kaquaoify** [Courseplay/courseplay#6098]
Hi

If I try to make a multi-harvester in MP, the combines don't follow the left or right side, they go both on the middle.
In SP it works. 

I see that this issue is reported, but my question is:
Is there any version of CP6 that works with multi-harvester in MP ? or it never works since the beginning ?

_Thanks :-)

**Comment by Tensuko** [comment]
Yes don't work and we know this and there should be an Issue already.
