### ISSUE TITLE
Feldmodus: Drescher "muss entladen werden" obwohl leer

### ISSUE THREAD

**Issue by rohne83** [Courseplay/courseplay#6101]
Hi,

mit der neuen CP Version 6.02.00063 von gestern lässt sich zur Zeit nicht mehr dreschen. Die Fahrer bleiben selbst bei Korntank-Füllstand von 0% stehen, fahren das Rohr aus und melden "Gerät muss entladen werden" (siehe Screenshot). Scheint ein generelles Problem zu sein, Auf unterschiedlichen Maps mit unterschiedlichen Dreschern probiert und immer das selbe.
Der Fehler muss sich bei einem der letzten Releases eingeschlichen haben, bei der 6.02.00060 funktioniert alles noch wie es soll.
Beispiel-Log im Anhang. Falls zusätzliche Channels benötigt, bitte Bescheid geben. Werdet ihr aber wahrscheinlich auch bei euch nachstellen können.
![fsScreen_2020_09_20_11_27_35](https://user-images.githubusercontent.com/71030138/93708218-c3cbb580-fb34-11ea-8c8f-d17452a8562f.png)

[log.txt](https://github.com/Courseplay/courseplay/files/5251387/log.txt)

**Comment by Tensuko** [comment]
Kann ich nicht nachvollziehen, bin gerade am Dreschen und hab 0 Probleme.

**Comment by rohne83** [comment]
Sehr seltsam. Wenn ich mit den selben Dreschern ein komplett neues Feld anfange, auf dem ich noch gar nichts gemacht habe, gehts auch bei mir. Wenn ich dann aber wieder auf das Feld zurückkehre, wo sie beim Speichern standen, kommt wieder die gleiche Meldung...
Aber wie gesagt, erst jetzt mit der 00063

**Comment by Tensuko** [comment]
Ein Drescher, Feld A arbeiten, speichern, game laden, Meldung kommt.
Gleicher Drescher zu Feld B, arbeiten, läuft.
Wieder gleicher Drescher zurück auf Feld A und weiter arbeiten, Meldung kommt.
So in etwar ?

**Comment by rohne83** [comment]
Ja, genau. Wobei bei dem savegame wo ich den Screenshot gemacht hab, die Drescher auf dem Feld noch gar nicht angefangen haben zu arbeiten als ich gespeichert hatte. Sie standen nur am Feldrand, und der Kurs für dieses Feld war der letzte den ich generiert habe.

Ich hab nochmal die letzten Versionen vom Wochenende alle durchprobiert. Es ist konkret das Release 00061 seit dem das Problem auftritt.
Werd mal noch weiter schauen ob ich die genaue Situation wann das auftritt und wann nicht genauer eingrenzen kann. Scheint aber bisher irgendwie mit den Savegames zusammen zu hängen.

**Comment by schwiti6190** [comment]
@rohne83 sollte der fehler nochmal auftauchen einmal debug channel 2 und evtl. noch weitere die helfen könnten @Tensuko ? :)

**Comment by Tensuko** [comment]
12 und 14 kommen immer gut :)

**Comment by rohne83** [comment]
Log mit Channels 2, 12, 14 für die beiden Savegames wo ich das ohne großartig Vorarbeiten nachstellen kann. Vielleicht dazu zu sagen, dass beide savegames schon ein paar Tage älter sind (Ende August / Anfang September) und gemacht wurden, als die Courseplay Version noch bei paar-und-40 oder 50 lag.

[log.txt](https://github.com/Courseplay/courseplay/files/5255416/log.txt)
![fsScreen_2020_09_21_14_42_09](https://user-images.githubusercontent.com/71030138/93768507-c6eca180-fc19-11ea-9735-bfd76fc471d4.png)
![fsScreen_2020_09_21_14_44_48](https://user-images.githubusercontent.com/71030138/93768579-e257ac80-fc19-11ea-9252-ad6f4145d9b2.png)

**Comment by schwiti6190** [comment]
@rohne83 kannst einmal versuchen die drescher zurückzusetzen und die neuste version testen :)
Ansonsten haben wir nen problem: 
2020-09-21 14:41 :52 [dbg14 lp2800] S790i (#1): Fill levels: UNKNOWN: 0.00
2020-09-21 14:41 :52 [dbg14 lp2800] S790i (#1): Full: DIESEL: 99.36
das ist schlecht hm

**Comment by rohne83** [comment]
Was genau meinst du mit zurücksetzen genau? Eben mal mit der 64 versucht: Kurs rausgeschmissen, Drescher paar Meter herumgefahren, Kurs geladen (und auch mal mit komplett neu generiertem Kurs versucht). Funktioniert leider trotztem nicht...

**Comment by Playlord75** [comment]
Also ich kann das Problem mit denn 790i nicht nachvollziehen bin momentan auf der Türinger höhe mit dem 790i am Sonnenblumen Ernten auf einem 45ha Feld und es sind noch keine Probleme aufgetreten

**Comment by rohne83** [comment]
Ist erstens völllig unabhängig von der Marke der Drescher. Das tritt offensichtlich bei allen auf.
Zweitens, wie ich oben schon schrieb, tritt das soweit nur auf Feldern auf, auf/an denen die Drescher sich beim Spielstand speichern mit einem bereits generierten Feldkurs befanden. Konkret zumindest in dem Fall wo beim Spielstand speichern die CP Version noch unterhalb der 60 war, und der Spielstand dann mit CP Version 61/aufwärts wieder geladen wird. Die Drescher dreschen da gar nicht erst los, sondern senken nur ihr Schneidwerk und behaupten direkt dass sie entleert werden müssten, unabhängig vom tatsächlichen Füllstand.

**Comment by Playlord75** [comment]
Hast du denn einfach Mal versucht einen neuen Kurs zu generieren und denn alten zu Löschen 🤔

**Comment by rohne83** [comment]
Ja natürlich. Alles schon probiert.
Glücklicherweise hab ich das bisher nur bei den zwei Spielständen von oben. Der Workaround ist jetzt der, einfach die beiden Drescher zu verkaufen, und jeweils genau die gleichen Modelle neu zu kaufen (Schneidwerke können vor Ort bleiben). Das scheint nämlich interessanterweise zu funktionieren.

**Comment by schwiti6190** [comment]
> Ja natürlich. Alles schon probiert.
> Glücklicherweise hab ich das bisher nur bei den zwei Spielständen von oben. Der Workaround ist jetzt der, einfach die beiden Drescher zu verkaufen, und jeweils genau die gleichen Modelle neu zu kaufen (Schneidwerke können vor Ort bleiben). Das scheint nämlich interessanterweise zu funktionieren.

Evtl. Könnte es daran gelegen haben das noch alte fahrzeug variablen gespeichert waren. Sollte dieses nochmal auftreten, einmal versuchen über die karte "fahrzeug zurücksetzen", sollte den gleichen effekt haben wie neu kaufen :)

**Comment by rohne83** [comment]
Ok. Jedenfalls hab ich das Problem damit behoben bekommen, und keine savegames mehr wo das jetzt noch auftritt. Von daher können wir den hier eigentlich zumachen.
