### ISSUE TITLE
Abfahrer rammt Drescher leicht.

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#6102]
Hallo Freunde,
Mein Abfahrer Fendt mit dem FS19_AnnaburgerHTS3416 (was jetzt funktioniert)
Rammt oder besser gesagt streift mein Drescher!
Frage ist es möglich, das der Abfahrer erst dann startet, wenn der Drescher wieder in der Frucht ist?

![Screenshot (98)](https://user-images.githubusercontent.com/48583507/93709454-76ecdc80-fb3e-11ea-9d92-eb7420b6f5db.png)
![Screenshot (99)](https://user-images.githubusercontent.com/48583507/93709455-79e7cd00-fb3e-11ea-8a33-d31dda1ba1ad.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5251481/log.txt)

mit freundlichem Gruß

**Comment by Tensuko** [comment]
Should not happen anymore, as we changed a lot of traffic behaviour in Version 6.03.00001
Closing for now and waiting for new Mode2 adventures to see :)
