### ISSUE TITLE
Problem mit Silage ÜLW 

### ISSUE THREAD

**Issue by Playlord75** [Courseplay/courseplay#6104]
Hab ein Problem mit einem eigenen ÜLW er funtioniert problemlos mit autodrive jetzt wollte ich es mit Cp ausprobieren dabei kommt das raus: 
![fsScreen_2020_09_20_14_43_23](https://user-images.githubusercontent.com/71101944/93711698-942aa680-fb50-11ea-9339-451210cc0f69.png)
![fsScreen_2020_09_20_14_43_47](https://user-images.githubusercontent.com/71101944/93711708-b7edec80-fb50-11ea-8ad8-06bdf04277cd.png)

Ich kann denn Abfahrer ganz normal auswählen wie man sieht hat er auch alle sachen die ein ÜLW brauch rohr ausfahren trailer triger etc Nur Sobald ich ihn einstelle verschwinden die anzeigen oben für wendekreis und welchen drescher er abfahren soll und setzt ihn automatisch auf route abfahren um: 
![fsScreen_2020_09_20_14_44_06](https://user-images.githubusercontent.com/71101944/93711730-ea97e500-fb50-11ea-8234-9ece81a6fe01.png)
![fsScreen_2020_09_20_14_44_12](https://user-images.githubusercontent.com/71101944/93711734-ef5c9900-fb50-11ea-8ce6-0b6db1e1f8df.png) Abfahren muss er rückwerts heist rückwerts an denn zielpunkt fahren wenn diese frage kommen sollte

**Comment by Tensuko** [comment]
Das ist ein selbst gemoddeter ?
Weil der von GIANTS wird mit der Maus kontrolliert!

**Comment by Playlord75** [comment]
Ja ich hab denn so umgeschrieben das er wie ein Überladewagen funktioniert mit Autodrive funktioniert er auch ohne Probleme nur bei CP möchte er nicht

**Comment by Playlord75** [comment]
Normalerweise sollte er ja das Rohr in der Nähe vom Wartepunkt ausfahren heißt Heck Anheben Macht er aber nicht

**Comment by Tensuko** [comment]
Gibt es den irgendwo zum runter laden?
Wir müssten uns den halt mal anschauen, schwierig ist natürlich auf einzelne Mods ein zu gehen, weil sonst jeder gleich an kommt.

Das Problem was du aber nur hast ist scheinbar, dass er dir den Mode rausschmeißt...
Das könnte man eventuell recht einfach beheben.

**Comment by Playlord75** [comment]
Ja denn gibt es zum Download warte ich schicke denn Link hier rein

**Comment by Playlord75** [comment]
https://www.modhoster.de/mods/fieldliner-hts-31-06

**Comment by Playlord75** [comment]
Ist das Problem mit dem Überlademodus schon behoben das er nach dem ersten Mal Abfahren nichts mehr macht

**Comment by Tensuko** [comment]
So ich bin nun endlich mal dazu gekommen mir deinen ÜLW an zu gucken und es sind ein paar Probleme aufgetaucht.
Das größe Problem ist, dass bei deinem ÜLW scheinbar ein Node fehlt oder sowas, weil der kann nicht rückwärts geschoben werden.
Schafft CP es dennoch am Wartepunkt an zu kommen, wird er auch aufgeklappt, aber dann.... nichts ?
Hier ein Bild wie ich selber an einen Trailer rückwärts drangefahren bin, was muss ich denn jetzt machen ?
Ich kann keine Aktion finden mit dem ich den Trailer nun auskippen kann, oder übersehe ich da etwas ?
Ich bin mir auch recht sicher, dass wir das mit dem original Trailer hinbekommen, da wird die Achse die er anfahren muss einfach speichern können, nur muss der für den Mode3 freigeschaltet werden, das könnte etwas tricky werden.
![fsScreen_2020_12_11_11_55_30](https://user-images.githubusercontent.com/27344744/101895451-d7247500-3ba7-11eb-8309-63b76a54fb0e.png)
