### ISSUE TITLE
Pathfinder (Hybrid A*) maneuvering :suggestion:

### ISSUE THREAD

**Issue by GeorgeEarslight** [Courseplay/courseplay#6105]
I'm haven't been able to enable full pathfinding maneuvers between row transitions with the options available.
It seems that the pathfinder is starting the maneuver up to a precalculated connecting path.
This generated a collision in the following case. 

![image](https://user-images.githubusercontent.com/30686125/93713822-1920ba80-fb67-11ea-82d3-b612d3608a62.png)

I understand ofcourse that adding an extra headland pass would solve this, but I don't think it seems realistic given that the headland is already 18m.
Hopefully, a full pathfinder maneuver constrained to the field boundary would avoid that.

So the actual question is, is there a way to enable full pathfinding?
The suggestion if there's not, is it an easy addition to the options?

**Comment by Tensuko** [comment]
Did you turn on Pathinder in turn under adv Settings ?
Turn on Field on ? @pvaiko did some changes to turns in V .00063

**Comment by GeorgeEarslight** [comment]
Yes, all Pathfinder, AI and Rurn on Field options are activated.

**Comment by pvaiko** [comment]
@GeorgeEarslight what if you disable the AI turns?

**Comment by GeorgeEarslight** [comment]
@pvaiko 

It generated a perfect connecting maneuver.
I think I'm having confused about what those 3 advanced options do.
Could you please explain what they enable?

![image](https://user-images.githubusercontent.com/30686125/93789843-08417900-fc3b-11ea-8c8f-d75e84b4598c.png)

**Comment by wertigoxxx** [comment]
It would be great if we could set it to just rotate on the ground.  This would avoid collisions with trees.  There are often cases when there is not enough space in this case, do not roam between the trees because in this case the trailer will also stand up, even if you set the turning radius.

**Comment by pvaiko** [comment]
@GeorgeEarslight I know it is confusing a bit, sometimes for me too.

AI Turn: this works only for very simple cases with tools which are not towed. This is just a simple 3 point turn, no trajectory is calculated (except the one into the next row), we just do what a human would do to turn around. This does not take into account any obstacles but if it hits one, it backs up a bit and tries again. I implemented this to work on fields with trees and fences close to the field edge.

Pathfinding in turn: this is for the case when the turn end is somewhere far away (very wide turn or there's a concave corner between the turn start and end and uses the pathfinder (A* restricted to the headland) to find the way to the end of the turn. Works only if your course has headlands. For this, you can also turn on the reversing option so it'll also consider driving sections in reverse.

**Comment by GeorgeEarslight** [comment]
@pvaiko Thanks for the explanation.
