### ISSUE TITLE
Digestat spreading is freezing my game with V6.02.00063

### ISSUE THREAD

**Issue by polosubtil** [Courseplay/courseplay#6107]
Hi guys,

Not sure since when this is happening (I can find out if you  want me to) but as soon as I start my slurry tanker to spread + refill course (I haven't tried without the refill course), my game freeze and I get a massive log file in a few seconds. I am trying to work with mode 8 for the first time so I might do something wrong here. But the log file here has only the slurry tanker started, I didn't start the mode 8 tanker
[log.txt](https://github.com/Courseplay/courseplay/files/5252168/log.txt)
![fsScreen_2020_09_20_19_13_16](https://user-images.githubusercontent.com/60451845/93717506-8f78e900-fb76-11ea-8c64-0c1847dd502b.png)

I just realized I made the log with David fork ;)
But it was doing the same with V6.02.00063

**Comment by Tensuko** [comment]
Strange... I have that one running for test with refill course.

**Comment by schwiti6190** [comment]
this one is probably the cause 
`2020-09-20 19:13 Error: Running LUA method 'mouseEvent'.
2020-09-20 19:13 C:/Users/Paul/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/Generic/LinkedList.lua:64: attempt to index local 'node' (a nil value)`
unfortunatly I don't really have a clue why this happend. It seems like one element of the fillType list got removed, but not sure if you've done it or code internally.

**Comment by polosubtil** [comment]
Let me try without a refill course then, I didn't so far

**Comment by Tensuko** [comment]
With David Branch, refill course on a container...
![fsScreen_2020_09_20_19_42_32](https://user-images.githubusercontent.com/27344744/93717997-889fa580-fb79-11ea-963d-399359eed7ec.png)

**Comment by polosubtil** [comment]
Ok guys, really sorry about that, my bad.
I forget to remove seeds and fertilizer in the list of products to refill, if I put digestat it works fine now

**Comment by Tensuko** [comment]
That is a good point, we might need to make the check more safe.

**Comment by schwiti6190** [comment]
@Tensuko Could you try this one with my current branch, might be improved?

**Comment by polosubtil** [comment]
Hi @schwiti6190 
I am using your branch since you mentioned it in that post and it works pretty well. As soon as the tractor is detached from the implement, the list of products is reset to none
No problems so far in my game
