### ISSUE TITLE
pathfinder problem and thresher discharge maneuver

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#6108]
I was threshing and I noticed some small problems. Unfortunately I was not able to document everything with photos but, in case it happens again, I will get ready to screen and activate all the necessary debug channels. I noticed that during the unloading sometimes the tractor gets stuck and checking the log (which I attach) I noticed that the pathfinder does not find the path to move the tractor from its position to the thresher (in the attached photo it would be the path in blue). I solved it by sending the tractor home and using another one for unloading. When maneuvering near the thresher, some trailers (especially the 3-axle ones) get stuck on the harvester bar of the combine. In the case of the photo the trailer passed very very close but without touching, but with longer wagons they fit together. The red mark indicates the point where the collision occurs which unfortunately is only resolved manually

![Farming Simulator 19 20_09_2020 23_12_32_LI](https://user-images.githubusercontent.com/59969508/93722567-14c0c580-fb98-11ea-8b7d-00deed554620.jpg)

[log.txt](https://github.com/Courseplay/courseplay/files/5252678/log.txt)

**Comment by Tensuko** [comment]
#6102 and  #5983
