### ISSUE TITLE
Automatic CP stop at the end of course

### ISSUE THREAD

**Issue by Dzarin** [Courseplay/courseplay#6111]
Hello, is it possible to add an option, so that the Courseplay would stop itself, when the helper finishes the work at the field/ drives to the end of course?

**Comment by Tensuko** [comment]
Already on the list....
Stop at end/Stop at start/Stop at end and stop CP/Stop at start and stop CP.
But it will only be stopped when you jump into the vehicle so you will have to notification untill you jump in.

**Comment by Dzarin** [comment]
In that case would it be possible for helpers to not take wages when they complete the course? 
Problem that I have is that i run on multiple servers, I turn on the CP, go to another server and so on. And before i come back to the first server (or dont have time to join back), the CP will make my farm bankrupt.

**Comment by Tensuko** [comment]
Will check if can stop earn wages when work is done, but won't add an auto stop CP option when work is done, as some ppl want to have that msg still going... will figure something out...

**Comment by Tensuko** [comment]
Can change now between stop at start deactivated, activated, deactivated and release driver, activated and release driver.
