### ISSUE TITLE
Felder zu Groß? Game Crash

### ISSUE THREAD

**Issue by HansGeorg95** [Courseplay/courseplay#6113]
MVP 19 Feld 13
Course Play erkennt Feld 13 auf dieser Map nicht.
Wenn der Feldkurs Manuell generiert wird alles kein Problem. Da wird das Feld sofort richtig erkannt.
Jedoch wenn man jetzt ein Kurs generieren möchte hängt sich das Spiel immer auf und reagiert gar nichts mehr.
Auch auf dem Desktop funktioniert nichts mehr.
Bei allen anderen Feldern hackt es einmal kurz und dann ist der Kurs generiert.

**Comment by Tensuko** [comment]
logfile mit debugchannel 7 aktiv, dann Kurs generieren.
Glaub kaum das es zu groß ist, eher zu wenig Geduld :) WildWildWest hast größere Felder und hab schon Kurse mit 64.000 Wegpunkten gesehen, hat halt 10min gedauert.

**Comment by Playlord75** [comment]
Tensuko da kann ich dir nur recht geben das ist einfach ungedult ich muste schonmal 18 min auf der kandelin warten bis der cours endlich generiert war :D

**Comment by HansGeorg95** [comment]
So nach 28 Minuten hat's denn endlich geklappt ich bedanke mich Jungs

**Comment by Tensuko** [comment]
28 Minuten, oha...
Vlt solltest du über Geräte mit mehr Arbeitsbreite nachdenken :)
Aber ich mach hier dann mal zu, schön speichern den Kurs (mit Geduld :) )
