### ISSUE TITLE
Hemp on Pleasant Valley 4x 

### ISSUE THREAD

**Issue by Unknownt** [Courseplay/courseplay#6115]
it seems like hemp is not picked up by the mod as something to unload. The harvesters will harvest and when they are full will not drive to self unload or have a truck/tractor come and unload I've tried 3 different harvesters and 3 different unloaders and countless numbers of different courses but nothing works.

**Comment by Tensuko** [comment]
What about giving us more information ?
If you have Tactors with Trailers within 20m of the Field parking and waiting there and you turn on 'Self Unload' for the Harvester (adv Settings page) they should find the way to the trailer.
For Mode2, check #5272 and our Wiki Page.

**Comment by Unknownt** [comment]
I've tried that. I have 2 other fields with different crops and mode 2 works fine just seems like with hemp it has the problem.

**Comment by Tensuko** [comment]
Can the Trailer load hemp ?
What Combine you use for it ?

**Comment by Unknownt** [comment]
Yes I just have to manually do it. I've tested it with the John Deere T560 and S790 aswell as the Axial-flow 9240.

**Comment by Tensuko** [comment]
Pretty sure it was some weird Mod Issue.
Should work now or Mod Issue still.
