### ISSUE TITLE
Other Funcstions

### ISSUE THREAD

**Issue by perrycampbell456** [Courseplay/courseplay#6116]
Hello I have an issue I will post a screenshot of my Issue and why its not work.

![Screenshot (113)_LI](https://user-images.githubusercontent.com/35439473/93838291-07cbd100-fc81-11ea-95fe-376a10215891.jpg)
I cant get the refill or combie to work in V6.02 

Please help is there a bug report about this if its a bug in itself.

**Comment by perrycampbell456** [comment]
I can`t even get it to work with the seeder neither. I don`t know what wrong with the mod or anything.

**Comment by Tensuko** [comment]
Becouse those Modes are not for a Seeder... you can't Transport Seed from A to B and you can't unload a Harvester with a Seeder......
Not an Issue.

**Comment by perrycampbell456** [comment]
That's not a seeder thats a fertilizer tank and there have been videos about auto refill.

**Comment by perrycampbell456** [comment]
Most recent video about auto refill of the seeder and Furtilizer the tanks that will be in the video I already placed down please watch the video and tell me how he is managing to set a refill course with CoursePlay Link: https://www.youtube.com/watch?v=l7UaFrySrzI

**Comment by Tensuko** [comment]
Ofc not with mode1 or mode2.
You just record a course from field to your seed source or whatever you want to refill and back to the field. Save that course as e.g. F20_Refill. Then first load your Field work course and then use the + folder and add your refill course, thats all.
