### ISSUE TITLE
CP + Autodrive question

### ISSUE THREAD

**Issue by Horozor** [Courseplay/courseplay#6117]
Hi there, its me again ))
Some months ago i asked you about hardi rubicon 9000, it stuck near objects and vehicles on refilling course.  You said that it is giants issue. Very wide ai collision marker or something else. But now i tried CP on field + autodrive for refilling course and it works perfectly. is it possible teach CP aidriver use same method of driving like autodrive. 
I hope you understand what I mean.

**Comment by Tensuko** [comment]
The Problems stays, it is a GIANTS Problem becouse we use GIANTS collission Mask for driving and collission detection.
AD did create their own and we would have to do the same...
See the GIANTS Problem here: #3239
