### ISSUE TITLE
Slurry Spreader Stop After Refill Tank..

### ISSUE THREAD

**Issue by betrox007** [Courseplay/courseplay#6118]
Dear All.. Thanks for the all Hard work for this mod, so today i try to use Field support Mode to supply Slurry from Slurry pit to field,
Recording course like usually, start point at slurry pit then add wait point at the side of field and then end point a few meter before start point at slurry pit, set the fill type to slurry, and run course.
and then recording refill course for field worker start at field, add waiting point aside of transporter and end at field, then generate field course and add the refill course was recorded, set the fill type to slurry and the run course.
The transporter is working great, load at slurry pit and then at waiting point (Offloading point) he standby there wait for field worker to approach for refill,
when the field worker's tank empty he approach the transporter and the transporter doing overloading to field worker, once the field worker tank full the transporter continue moving return to pit, and the field worker stop not return to last point when he run out slurry at field.

Map Ravenport vanila map, all implement vanila implement

log attached with channel 12, 14 and 23 debug

thanks and best regards
[log.txt](https://github.com/Courseplay/courseplay/files/5262594/log.txt)

and here some screen capture
My Start and end point for Transporter
![fsScreen_2020_09_22_22_24_54](https://user-images.githubusercontent.com/56646850/93906791-d1e12800-fd26-11ea-8868-84faf09cf7e9.png)

Recording Refill course for Field worker
![fsScreen_2020_09_22_22_28_23](https://user-images.githubusercontent.com/56646850/93906805-d574af00-fd26-11ea-9101-bccf9f5e13ba.png)

Field work Course with Refill course
![fsScreen_2020_09_22_22_29_34](https://user-images.githubusercontent.com/56646850/93906810-d73e7280-fd26-11ea-84fc-6d081f6f181a.png)

Transporter course
![fsScreen_2020_09_22_22_34_19](https://user-images.githubusercontent.com/56646850/93906829-dd345380-fd26-11ea-8907-702640c7caba.png)

Field Worker on action
![fsScreen_2020_09_22_22_35_31](https://user-images.githubusercontent.com/56646850/93906856-e4f3f800-fd26-11ea-98c4-f61c5e2c4798.png)
![fsScreen_2020_09_22_22_36_21](https://user-images.githubusercontent.com/56646850/93906868-e7565200-fd26-11ea-9a68-7c3500fb1a32.png)

Field worker Arrive at refill point and stop engine
![fsScreen_2020_09_22_22_37_16](https://user-images.githubusercontent.com/56646850/93906875-e9b8ac00-fd26-11ea-8d1a-a2481d5fb366.png)

The transporter return to pit although his tank didn't empty yet.
![fsScreen_2020_09_22_22_37_34](https://user-images.githubusercontent.com/56646850/93906891-ec1b0600-fd26-11ea-80ad-154bddce1aa6.png)

**Comment by polosubtil** [comment]
I think you have to change the first value in that screen to decide at what % the tank needs to be refilled
1% seems like the minimum value
![image](https://user-images.githubusercontent.com/60451845/93908210-a9ddce80-fcfe-11ea-8f61-d3d6450bb0ba.png)

**Comment by betrox007** [comment]
opps.. okay thanks for the information i'll check it out...

**Comment by Tensuko** [comment]
(Version: 6.02.00063) FS19_Courseplay

> Always update to the latest build and check if the problem really still exists before reporting issues.

https://github.com/Courseplay/courseplay/wiki

https://github.com/Courseplay/courseplay/releases

For refill course, no waitpoint! Only for Mode8 Driver!

**Comment by betrox007** [comment]
thanks for reply.. i think this problem fix with (Version: 6.02.00064) and setting minimum value above 0 for fill type..

thank you all
