### ISSUE TITLE
Automatic field scan locks up Riccis Hollow map

### ISSUE THREAD

**Issue by kjetilverkethansen** [Courseplay/courseplay#6119]
When loading up Riccis Hollow map, the game freezes up when CP is trying to scan the fields. I tried to download the newest verion of CP and reinstalled the game, but getting the same problems. CP worked fine last week.

**Comment by kjetilverkethansen** [comment]
[log.txt.zip](https://github.com/Courseplay/courseplay/files/5263688/log.txt.zip)

**Comment by Tensuko** [comment]
(Version: 6.02.00059) FS19_Courseplay_6

> Always update to the latest build and check if the problem really still exists before reporting issues.

https://github.com/Courseplay/courseplay/wiki

https://github.com/Courseplay/courseplay/releases

download the .zip, place it in mods Folder, done! No Renameing or anything!

You should have more patience, I doubt your PC freeze...

**Comment by kjetilverkethansen** [comment]
There seems to be a mod conflict with RM seasons downloaded from modhub.

**Comment by Tensuko** [comment]
I had Seasons running too with some maps and was not a problem.

**Comment by kjetilverkethansen** [comment]
When removing seasons from mod folder it scanned fields within seconds after map loaded. With seasons in mod folder, the game freezes before it scans fields. No controls are working in game. Can't move crusor or enter any menus. The same happens with Candian Production Map v.4,1.
But I rather play with a working CP than have seasons in game.
