### ISSUE TITLE
PC freeze

### ISSUE THREAD

**Issue by Gravitysux** [Courseplay/courseplay#6120]
Hello.
I'm a newbie when it comes to gaming and programming.
The game i have started gaming is FS19, and i have a problem. The computer freezes after i have played for a while. I have tried to remove very mod downloaded and only use CP. And after a while the computer freeze.
Not sure but suspect that the CP is the problem.
[log fs 19 22.09.20.txt](https://github.com/Courseplay/courseplay/files/5263703/log.fs.19.22.09.20.txt)

Can someone please look at the log and see if there is a problem.

PS: This gamelog do have a few mods.

Thanks.

**Comment by candymant** [comment]
if you use global company then the placeanyware mod must be deleted. you can turn this on in the global company options.

the second is that there is a mod that keeps trowing lua errors.
remove every mod out of the mod map and try again. then ad every mod 1 by one to your mod folder until the error appears then delet the last mod you added.

**Comment by Tensuko** [comment]
(Version: 1.0.0.2) FS19_waitingWorkers
(Version: 1.0.0.0) FS19_HorseHelper (should be in GC too ?)
(Version: 1.3) FS19PlaceAnywhere (is in GC)

But for sure this is not a CP Error.

**Comment by Gravitysux** [comment]
Thank you very much!
