### ISSUE TITLE
Trailer can not be loaded

### ISSUE THREAD

**Issue by Evolution120** [Courseplay/courseplay#6122]
Hello everyone,

i have noticed, that trailers can not be filled up manualy, without using CP.
If i remove CP from the mod-folder, everything works fine.
Used ver. ***64
previous Versions: 
***52: same problem
***46: same problem
***42: works without any errors

Problem:
- Placing Trailer under FillTrigger
- [1] Press "R" to start loading process
- [2] Choose fruit type and press "start"
- [3] nothing happens / situations switches back to [1]

Extended Information:
- Trailer is able to carry the fruit type
- there is enough fruit stored in the silo
- this happens when trying to load: everything at the usual farmsilo | milk | lime 

Let me know how i can help to fix this problem.

![fsScreen_2020_09_23_10_16_48](https://user-images.githubusercontent.com/71757583/93992785-44d1b980-fd8e-11ea-8922-19bbb4b9f605.jpg)

![fsScreen_2020_09_23_10_16_41](https://user-images.githubusercontent.com/71757583/93992723-2cfa3580-fd8e-11ea-8034-27ad625cd97e.jpg)

![fsScreen_2020_09_23_10_30_35](https://user-images.githubusercontent.com/71757583/93992895-63d04b80-fd8e-11ea-9ee6-154777da71cd.jpg)

![fsScreen_2020_09_23_10_30_39](https://user-images.githubusercontent.com/71757583/93993002-84000a80-fd8e-11ea-9260-645c57ddd69a.jpg)

**Comment by Tensuko** [comment]
logfile ?
SP/MP ?

**Comment by Evolution120** [comment]
Hello,

- SP
- I started the savegame again, to get a shorter log file.
After restarting the loading process worked once, but after I tried to load the same trailer again, the described problem occured. Milk could not be loaded either. 

[log.txt](https://github.com/Courseplay/courseplay/files/5267199/log.txt)

**Comment by Tensuko** [comment]
Hierzu mal die Anleitung lesen:
Error: Failed to open xml file 'C:/Users/AikoDemandt/Documents/My Games/FarmingSimulator2019/mods/Tools_Frucht_Symbole/modDesc.xml'.
Available mod: (Hash: 2032ae631018b7ac8319cac9a1e525ba) Tools_Frucht_Symbole
Error: Missing descVersion attribute in mod Tools_Frucht_Symbole


Was soll eigentlich die Benennung der Mods ?
Ich wäre mit sowas vorsichtig...

Und nur mal so:
(Version: 1.0.0.0) Objekte_GC_baleStorage
Dafür brauchst du GlobalCompany, wie es im Name schon drin steht.

**Comment by Tensuko** [comment]
Can't reproduce and I can't see any reason why it should not work....

**Comment by schwiti6190** [comment]
@Evolution120 If you could post a savegame with your course and mods, we could have a look, but without them it's kind of hard and taxing to find the bug/problem unfortunatly :)

**Comment by Tensuko** [comment]
I think you experienced this one: #6147

**Comment by schwiti6190** [comment]
@Evolution120 What's the status on this one with the newest version ? :)

**Comment by Tensuko** [comment]
Should work fine now when no one says anything...
