### ISSUE TITLE
LKW bleibt nicht im Mod 1 am Startpunkt stehen.

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#6123]
LKW bleibt nicht im Mod 1 am Startpunkt stehen und wartet auf den Überlader, 
Er fährt wie im MOD 5 Überführung eine Endlosschleife.
Log mit 4-7-12-14
[log.txt](https://github.com/Courseplay/courseplay/files/5267074/log.txt)

![Screenshot (104)](https://user-images.githubusercontent.com/48583507/93994218-f1606b00-fd8f-11ea-81ed-4ea5295c6a0c.png)
![Screenshot (105)](https://user-images.githubusercontent.com/48583507/93994228-f45b5b80-fd8f-11ea-93c2-363d69b0a593.png)
![Screenshot (106)](https://user-images.githubusercontent.com/48583507/93994239-f6bdb580-fd8f-11ea-9b42-a0edda6d041d.png)
![Screenshot (107)](https://user-images.githubusercontent.com/48583507/93994250-f9200f80-fd8f-11ea-8206-2b19ac08a9df.png)
![Screenshot (108)](https://user-images.githubusercontent.com/48583507/93995634-8f086a00-fd91-11ea-9dda-9eadd4e488c2.png)

MfG

**Comment by Tensuko** [comment]
> If you don't add any FillType, Mode1 Driver will wait at Start untill the set % is reached

https://github.com/Courseplay/courseplay/wiki/Mode-1-Changes
