### ISSUE TITLE
Probleme bei Kursgenerierung mit Vorgewende Rundherum

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#6125]
Hallo Leute,
bekomme ganz komische Kursberechnungen (mit v6.02.00064) wenn ich beim Vorgewende 1 oder 2 runden Rundherum machen möchte:
![fsScreen_2020_09_23_23_56_42](https://user-images.githubusercontent.com/24860501/94074227-2bb22280-fdf9-11ea-8fa0-91acabc020b3.png)
![fsScreen_2020_09_23_23_57_16](https://user-images.githubusercontent.com/24860501/94074232-2d7be600-fdf9-11ea-8a73-43d468971b49.png)
![fsScreen_2020_09_23_23_57_25](https://user-images.githubusercontent.com/24860501/94074236-2fde4000-fdf9-11ea-87e7-f10404e65776.png)
![fsScreen_2020_09_23_23_57_39](https://user-images.githubusercontent.com/24860501/94074240-32409a00-fdf9-11ea-9701-7de7ad3d4f5c.png)
hab da mal ein paar Beispiele mit 1 oder 2 Runden, verschiedene Startpunkte,...

wenn ich den Kurs nur mit hinundher berechnen lasse klappt es 
![fsScreen_2020_09_23_23_58_01](https://user-images.githubusercontent.com/24860501/94074333-5ac89400-fdf9-11ea-8626-876a252a30ef.png)

lg
andreas

**Comment by Tensuko** [comment]
Das müsste an skip lanes liegen.

**Comment by pvaiko** [comment]
Duplicate of #6079
