### ISSUE TITLE
Suggestion for field work with combine.

### ISSUE THREAD

**Issue by Phalanx380** [Courseplay/courseplay#6126]
i have Suggestion for field work with combines add a unfold pipe at a preset fill level as sometimes AutoDrive wont move on the combine till the pipe is out with out this it causes the combine to fill up to full and come to a stop and then unfold the pipe. another Suggestion for mode 2 add a stay on filed function and smooth out avoid fruit it has a habit of bouncing of the fruit area causing it to slow down a lot.

**Comment by Tensuko** [comment]
Working combine with pipe out was discussed in another feature and won't happen.
Smoothing out fruit avoide is not a mode2 Issue, it is the Pathfinder and won't change something on it yet.
