### ISSUE TITLE
LKW-Anhänger wird nicht beladen

### ISSUE THREAD

**Issue by Lustiger-Hubi** [Courseplay/courseplay#6127]
1. Startpunkt am Anhänger
LKW fährt den Anhänger unter der Pipe Zugmaschine wird nicht beladen!

2. Startpunkt am  LKW
LKW steht am Startpunkt, wird beladen und fährt ohne Beladung des Anhängers weite zum Silo.
Bei Einstellung 100% bleibt der LKW stehen fährt nicht weiter vor!

[log.txt](https://github.com/Courseplay/courseplay/files/5275763/log.txt)

![Screenshot (109)](https://user-images.githubusercontent.com/48583507/94141931-c9dfd000-fe6d-11ea-92f0-12cbfee9b1c5.png)
![Screenshot (110)](https://user-images.githubusercontent.com/48583507/94141938-ccdac080-fe6d-11ea-95a4-8887b64aac83.png)
![Screenshot (111)](https://user-images.githubusercontent.com/48583507/94141954-cf3d1a80-fe6d-11ea-9a4b-c5955e889106.png)
![Screenshot (112)](https://user-images.githubusercontent.com/48583507/94141966-d19f7480-fe6d-11ea-8ee3-61ed7a38f207.png)
![Screenshot (113)](https://user-images.githubusercontent.com/48583507/94141971-d401ce80-fe6d-11ea-8922-bc0152da543e.png)
![Screenshot (115)](https://user-images.githubusercontent.com/48583507/94141981-d5cb9200-fe6d-11ea-8418-5629b3fe2859.png)
Bei 100% bleibt der LKW stehen!
![Screenshot (116)](https://user-images.githubusercontent.com/48583507/94141988-d82dec00-fe6d-11ea-806f-2a9dfc004705.png)

**Comment by Tensuko** [comment]
Lösung ist in Arbeit #6046
