### ISSUE TITLE
Hide the Hud but not the mouse

### ISSUE THREAD

**Issue by Step72** [Courseplay/courseplay#6128]
I'm posting this message for the developers of Course.
I am disabled and have motor problems.
To play FS19 I use a ps4 controller plugged into my computer like this

https://www.youtube.com/watch?v=Gv9RkBC_EVk
I play with my chin because my hands are not working.

To be able to use my onscreen virtual keyboard I leave courseplay open because I have to use my mouse cursor to press the keys on the onscreen keyboard.

Only a few times do I not use court play but I have to leave it on so that my computer mouse is visible.

My question is: Would it be to develop a system to hide cour play while having the mouse cursor visible and usable for my virtual keyboard?

Thank you

**Comment by Tensuko** [comment]
Hi Step,

sadly our Mousecurser use is a real mess, we have a very old system for it.
But I did try something out for you.
There is a mod called AutoDrive. AutoDrive can hide the HUD and with e.g. middle Mouse Button (that is the standart config) you can have a mouse on screen without any HUD open (no AD and no CP HUD).

You can download it from here:
https://github.com/Stephan-S/FS19_AutoDrive
Direct downloadlink from GitHub:
https://host-my-bits.com/cdn/files/1/FS19_AutoDrive.zip 

I hope this will help you to enjoy play FS19 more easy :)
We might try to make mosue work better with CP too, but right now we have not much time for this, so I hope the soultion with AD helps you for now :)

**Comment by Step72** [comment]
Unfortunately that is not possible.
If courseplay is not enabled (Closed from Cross HUB) and there is just AutoDrive enabled, the mouse cursor is not visible and usable.


Do you think that one day we will be able to see and use the mouse cursor with the Courseplay HUB shut down?

**Comment by Tensuko** [comment]
Hmm but I had CP and AD active, closed both HUD and then pressed middle mouse button and mouse was there.

I will check CP mouse later maybe I can find abtweak for it.

**Comment by Step72** [comment]
I think I found it. In the keyboard settings I set to show / hide the keyboard right click.
<img width="2213" alt="Capture d’écran 2020-09-26 à 09 29 56" src="https://user-images.githubusercontent.com/18511992/94335404-beaab280-ffdb-11ea-8d46-8ca7b912de6a.png">


On the other hand, I have deactivated the display of the Courseplay Hub in the settings, but how do I display it now?

**Comment by Step72** [comment]
I found :)
<img width="2185" alt="Capture d’écran 2020-09-26 à 09 39 48" src="https://user-images.githubusercontent.com/18511992/94335533-72ac3d80-ffdc-11ea-9db8-c5ef7eb365a4.png">

**Comment by schwiti6190** [comment]
@Step72 if you still need any help or there is something that could help you, feel free to tell us and we will have a look :)

**Comment by Step72** [comment]
Ok thank you Tensuko

**Comment by Tensuko** [comment]
@Step72 
did you find a working solution for you now ?
I did try some things in CP Code to just get the Mouse to show up, but sadly I had no success yet...

**Comment by Step72** [comment]
Hello Tensuko
I managed to get my mouse to appear with courseplay and autodrive by setting as below
<img width="1821" alt="Capture d’écran 2020-10-17 à 09 00 36" src="https://user-images.githubusercontent.com/18511992/96330695-9a307c00-1057-11eb-8666-4bc64c103624.png">
<img width="1837" alt="Capture d’écran 2020-10-17 à 09 01 01" src="https://user-images.githubusercontent.com/18511992/96330699-a4527a80-1057-11eb-9eea-41e62125ecd9.png">
