### ISSUE TITLE
Fehler? oder gewollt? 

### ISSUE THREAD

**Issue by Playlord75** [Courseplay/courseplay#6130]
ich weiß jetzt nicht ob das ein fehler ist das der teleskoparm beim silo entleren nicht wieder mit eingefahren/ ausgefahren wird oder ist das extra so? 
![fsScreen_2020_09_24_21_51_45](https://user-images.githubusercontent.com/71101944/94193334-85c1ef00-feb0-11ea-866f-6645eca99c9d.png)
und wenn die frage kommen solte ja ich hab denn teleskop arm ausgefahren/ eingefahren wehrend ich die schaufel stelung eingestelt habe

**Comment by Tensuko** [comment]
Problem mit Claas Scorpion, ist bekannt
