### ISSUE TITLE
Problem Whit Mode 1 

### ISSUE THREAD

**Issue by Thomasrev** [Courseplay/courseplay#6132]
The course works regularly, except that the filling of the trailer at the beginning of the race only happens if I am in the tractor ... if I let the courseplay work alone and I go on another vehicle it does not fill up, it passes under the trigger and starts without load

**Comment by Tensuko** [comment]
Logfile with debugchannel 2 and a screenshot with all wp on (3 dots in hud settings) at your loading area.

**Comment by Thomasrev** [comment]
Ecco qua 
[log.txt](https://github.com/Courseplay/courseplay/files/5280981/log.txt)
![SnapCrab_NoName_2020-9-25_8-26-50_No-00](https://user-images.githubusercontent.com/64921465/94234118-54294200-ff09-11ea-8365-c76261427b63.jpg)
![SnapCrab_NoName_2020-9-25_8-26-51_No-00](https://user-images.githubusercontent.com/64921465/94234120-555a6f00-ff09-11ea-8535-254e64a9d8aa.jpg)

**Comment by Tensuko** [comment]
For the next time:

> 
> 
> Logfile with debugchannel 2 and a screenshot with all wp on (3 dots in hud settings) at your loading area.

![94234118-54294200-ff09-11ea-8365-c76261427b63](https://user-images.githubusercontent.com/27344744/94250416-7cbd3600-ff21-11ea-9540-22f25d9789b1.jpg)

Your 1st WP after start WP is to close, use Editor to move it more far away and try again.

**Comment by Thomasrev** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5281879/log.txt)
![Screem](https://user-images.githubusercontent.com/64921465/94251557-f99cdf80-ff22-11ea-9150-fffd1c8a3817.jpg)

**Comment by Tensuko** [comment]
> Your 1st WP after start WP is to close, use Editor to move it more far away and try again.

**Comment by Tensuko** [comment]
![Uploading 94251557-f99cdf80-ff22-11ea-9150-fffd1c8a3817.jpg…]()

**Comment by candymant** [comment]
you have to update manuresystem to version 1.1.0 on the github.
[https://github.com/stijnwop/manureSystem](url)

**Comment by Tensuko** [comment]
Version 1.1 is also on ModHub.
But yes you are right, I must have overseen it :)

**Comment by Tensuko** [comment]
Closed due to inactivity
