### ISSUE TITLE
Problem with Mode 9 // The capacity of the BGA bunker is full

### ISSUE THREAD

**Issue by Lars-LS17** [Courseplay/courseplay#6133]
Hallo Zusammen,

ich habe die Courseplay V6.02.00064.
Ich spiele auf der NF-Marsch 4x. Wenn ich mit Courseplay die BGA-Bunker befülle, hören die Radlader nicht auf, wenn der Bunker voll ist. 
Hier ein Screenshot:
![fsScreen_2020_09_25_15_49_45](https://user-images.githubusercontent.com/31773176/94275324-1d721c80-ff47-11ea-9241-cb184faac0a8.png)

Kann man da etwas gegen machen?

**Comment by Lars-LS17** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5283283/log.txt)
 Hier noch die Log mit Debug-Channel 10

**Comment by Horozor** [comment]
I had the same problem yesterday. When the 50,000 limit was reached, the loader put the silage onto the ground. I accelerated the time to x15, so that the silage would have time to be processed. No logs, just to let you know

**Comment by leo32128fs** [comment]
mine has the same problem, but in my case it unloads little by little, without dumping it on the floor

**Comment by Lars-LS17** [comment]
Gibt es bei dem Mode9 bekannte Probleme, wenn man zwei Radlader gleichzeitig zwei verschiedene BGAs aus 2 verschiedene Fahrsilos auffüllen lässt?
Den ersten den ich aktiviere, funktioniert immer super. Wenn ich dann den zweiten Radlader starte, dann bekomme ich immer Probleme, dass der das BGA-Silo gar nicht reinfährt, sondern am Anfang direkt stehen bleibt und wieder rückwärts fährt.

**Comment by Kartracer390** [comment]
Hallo Lars-LS17 habe das gleiche Problem mit 2 Radladern dachte schon nur ich hab das
