### ISSUE TITLE
Most recent video for the Refill course of Courseplay

### ISSUE THREAD

**Issue by perrycampbell456** [Courseplay/courseplay#6134]
Hey about that last issue that was closed 4 Days ago please watch this video and exsplaine how he is managing to use CoursePlay and setting up Refill points the tanks that are in this video are the tanks I use. Before jumping to conclusions saying that its not an issue watch the Tutorial video below.

Video : https://www.youtube.com/watch?v=l7UaFrySrzI

**Comment by Tensuko** [comment]
He is exactly doing what I said in your other Issue, you dont need other modes, you only need mode4 for this!

**Comment by perrycampbell456** [comment]
he has V6.01 I have the V6.02

**Comment by Tensuko** [comment]
That doesnt matter at all, why you dont do it as in the video ? All you need is mode4 for this !!!

**Comment by Tensuko** [comment]
![refill](https://user-images.githubusercontent.com/27344744/94342338-b325ae80-0010-11eb-9b6e-f9abb2abd8e5.png)

**Comment by perrycampbell456** [comment]
@Tensuko Thank you I did not think that would have worked I will try it out if it does not work what would you like me to do?

**Comment by Tensuko** [comment]
Create a Video where I can see what you do, so I can tell you missing.
