### ISSUE TITLE
Problem or not?

### ISSUE THREAD

**Issue by galicije83** [Courseplay/courseplay#6136]
Hi there, i use a lot of CP in game and for me its necessary mod in game and because of that i have to report maybe problem with it when i use it in mode overload combine. CP work perfectly in this mode when he drives tractor with Over Loader and combine in same field, but when i want to drive combine manually mod dosnt work at all. Tractor and OL just standing in field and do not move at all, but when i set CP to drive combine again all is fine. 

So my question is it normal for CP to do that or it have problem. I tested game with another modes and with out and its a same?

**Comment by Tensuko** [comment]
Read #5272 and Wiki
