### ISSUE TITLE
Courseplay Driving Speed

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#6137]
I think the settings for CP speed are obeying only KPH even when MPH is selected. So to get my tractor to drive on the field at 19 MPH for offloading, I have to set CP to 31 MPH.
Using version 63 of CP.
![20200926101018_1](https://user-images.githubusercontent.com/24764870/94342676-95405580-ffe0-11ea-92a4-a77cdc397b8e.jpg)
![20200926100831_1](https://user-images.githubusercontent.com/24764870/94342678-970a1900-ffe0-11ea-8295-db18b18a4e4c.jpg)

**Comment by Tensuko** [comment]
Yea we would have to make a calculation to display the correct speed.
Add it as Enhancement.

**Comment by lcc1211** [comment]
This is a fairly recent change, though. Can you see what version 50 had? I think that was the last version I had before going to 63.

**Comment by VergylTantor** [comment]
Duplicate of issues #6041 and #5994
