### ISSUE TITLE
Turn on field not working as axpected on sprayer

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#6138]
Hi,
have another issue with turn on field activated because there is not enough space at the field end for turning outside. But with the Hardi 24m sprayer it drives to far outside to succeed the turn, see pics attached
![fsScreen_2020_09_26_22_12_31](https://user-images.githubusercontent.com/21023840/94349567-d6b71c00-0045-11eb-8177-7ee18fe3b4d4.png)
![fsScreen_2020_09_26_22_12_41](https://user-images.githubusercontent.com/21023840/94349569-d7e84900-0045-11eb-932d-9cf9f022024e.png)
![fsScreen_2020_09_26_22_12_52](https://user-images.githubusercontent.com/21023840/94349570-d9197600-0045-11eb-9e9a-0fa5efda4b80.png)
![fsScreen_2020_09_26_22_12_59](https://user-images.githubusercontent.com/21023840/94349571-da4aa300-0045-11eb-876e-c6fbe3e8ee76.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5287278/log.txt)

**Comment by Tensuko** [comment]
Duplicate #6129

**Comment by iljarogoff** [comment]
this is not a duplicate. in #6129 i had turn on field deactivated, the tractor did not move backward before turn. in this issue, i had turn on field active, the tractor moved a bit back before turn, then did the turn but gets out of the field too far.

**Comment by enderwiggin07** [comment]
It seems to me the version 63 update made sprayers/spreaders not work right without headlands.  If you do a headland pass they work as you would expect
