### ISSUE TITLE
Unloading dump truck and trailer Mode 1 problem

### ISSUE THREAD

**Issue by Misamangame** [Courseplay/courseplay#6139]
Hello guys,
sorry if it was stated before didn't see it. I started using version 0064 and my truck/trailer combo is no longer unloading both. Basically truck will unload, trailer will start unloading too, but when truck dump basket is set back to traveling position, truck will start going without paying atention to the trailer so it will unload only few liters. I think before I was on version 0061 don't remember, but I'm using this truck/trailer combo since you updated Mode 1 for unloading more trailers and it worked well till now. I tried tractor and same 2 trailers and it was working well without issues. Maybe I just overlooked something in newest version? Map is Wild West. I can provide a log, just let me know which debug you need if any... 

video : 
https://youtu.be/fzf9UfrEGJU

**Comment by Tensuko** [comment]
logfile with debugchannel 2

**Comment by Misamangame** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5288513/log.txt)

Log file with debug 2

**Comment by Tensuko** [comment]
That is a Mod Issue.
I think the Problem is, that the Trailer can be configurated as an AugerWagon.

**Comment by Misamangame** [comment]
Hello Tensuko, this trailer have no option to be configured as auger wagon (https://www.farming-simulator.com/mod.php?lang=en&country=cz&mod_id=156592&title=fs2019) LIZARD TA 18. But I tried to change the course a bit, also sometimes I change side of unloading of truck/trailer and sometimes it works sometimes not also some other unloading place working perfectly some not so I think it might be also triggers map issue.  Probably not something what you can fine tune because all maps and mods are different.

**Comment by Tensuko** [comment]
Tested with 6.04
If this doesn't work with the mentioned Vehicle, it is a Mod Issue.
![fsScreen_2021_05_19_08_31_36](https://user-images.githubusercontent.com/27344744/118766505-cc6bbb80-b87c-11eb-9676-e0244a3f4094.png)
![fsScreen_2021_05_19_08_32_21](https://user-images.githubusercontent.com/27344744/118766508-cd9ce880-b87c-11eb-962c-c16d673f5721.png)
