### ISSUE TITLE
Bug, Combine does not return to work after unloading.

### ISSUE THREAD

**Issue by SirAdams** [Courseplay/courseplay#6140]
Available mod: (Hash: 2fe086f31acc074acbcb58525f99bf2b) (Version: 6.02.00064) FS19_Courseplay
020-09-27 01:55 ### Courseplay: initialized 87/87 files (v6.02.00064)
I drive up alone with the vehicle to unload the combine and after unloading the combine does not return to work and there is a problem in the logs.
Contract work.
I provide logs and game save.
[log.txt](https://github.com/Courseplay/courseplay/files/5287569/log.txt)

[savegame1.zip](https://github.com/Courseplay/courseplay/files/5287571/savegame1.zip)

**Comment by Tensuko** [comment]
So Combine runs with CP and you manually drive to Combine and unload it, when you are done with unloading, Combine won't continue to work ? (Doubt it, works for me just fine...)

**Comment by Tensuko** [comment]
Just tried and had no problem, closing...
