### ISSUE TITLE
Feldhäcksler kann nicht gekauft werden.

### ISSUE THREAD

**Issue by xerion8300** [Courseplay/courseplay#6141]
Hallo Wenn ich den Feldhäcksler vom Modhub lade kann ich ihn nicht kaufen Spiel lädt und lädt.
Wenn ich CP deaktiviere kann ich ihn Laden.
Die Fehlermeldung lautet:
FS19_Courseplay/toolManager.lua:189: attempt to compare number with nil

[log.txt](https://github.com/Courseplay/courseplay/files/5288088/log.txt)

**Comment by Tensuko** [comment]
Welchen Feldhäcksler ? Und CP auf .00064 Updaten:
https://github.com/Courseplay/courseplay/releases

**Comment by xerion8300** [comment]
Werde ich machen und mich wieder melden
[Feldhäcksler](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=179845&title=fs2019)

**Comment by andremeyer123** [comment]
Moin @xerion8300  mit diesen hier geht alles auch im Mp 
https://www.modhoster.de/mods/krone-pack-oy

**Comment by xerion8300** [comment]
Danke für die Antwort
