### ISSUE TITLE
BGA verdichten

### ISSUE THREAD

**Issue by acton59** [Courseplay/courseplay#6142]
![fsScreen_2020_09_27_17_53_38](https://user-images.githubusercontent.com/59387744/94369857-834bd900-00ec-11eb-877d-548fc9e3edd6.png)
Hallo,
erstmal Danke sagen.
BGA befüllen funktioniert ja hervorragend. Einfach einen Kurs durch die Mitte vom Silo, Courseplay schickt die Fahrer auf verschiedene Bahnen.
Verdichten bei Durchfahrsilo geht mit Walze  auch gut, nur ist der Fahrer zu schnell und man kann die Geschwindigkeit nicht einstellen. sieh Bild
![fsScreen_2020_09_27_17_52_56](https://user-images.githubusercontent.com/59387744/94369832-5b5c7580-00ec-11eb-961a-838d85929d68.png)

**Comment by andremeyer123** [comment]
@acton59  schau dir das an ab minute 15 gehts los habs 8 kmh gemacht und es geht 
https://www.youtube.com/watch?v=5Kw2P0vxPeQ&feature=youtu.be
![fsScreen_2020_09_28_17_19_34](https://user-images.githubusercontent.com/70706468/94452785-316c8700-01b0-11eb-8db5-28923243ef6d.png)

**Comment by acton59** [comment]
Hallo,
habe Video geschaut, aber der fährt nur vorwärts in verschiedenen Bahnen ins Silo und rundherum.
Ich verdichte mit Schiebekurs mit Parkfunktion.
welche Version hast du? und wie hast du die Geschwindigkeit von Automatik umgestellt?

**Comment by Tensuko** [comment]
Speeds usw fehlen im HUD, siehe #4130 sollte früher oder später wieder eingebaut sein, wann dazu kann ich nichts sagen.
