### ISSUE TITLE
Baler is not turning on

### ISSUE THREAD

**Issue by america19999** [Courseplay/courseplay#6143]
My baker will not turn on after I start my route? I tried looking in settings and could not find anything to fix

**Comment by Tensuko** [comment]
What about more Information ?! XY doesn't work is not enough...
Screenshots of your Course and Settings etc also a full logfile attached!
https://github.com/Courseplay/courseplay/wiki

**Comment by america19999** [comment]
Alrighty i just some screenshots of my settings 

[log.txt](https://github.com/Courseplay/courseplay/files/5290173/log.txt)
![20200927235051_1](https://user-images.githubusercontent.com/71999460/94395835-c8d4ca00-011d-11eb-8dc4-0bf38aafa3ff.jpg)
![20200927235104_1](https://user-images.githubusercontent.com/71999460/94395837-c8d4ca00-011d-11eb-8c7a-38e9725e09e6.jpg)
![20200927234850_1](https://user-images.githubusercontent.com/71999460/94395839-c96d6080-011d-11eb-84dc-f8993e297692.jpg)
![20200927235042_1](https://user-images.githubusercontent.com/71999460/94395840-c96d6080-011d-11eb-85f3-27453c8b2f96.jpg)
![20200927235048_1](https://user-images.githubusercontent.com/71999460/94395841-c96d6080-011d-11eb-86ea-8e40cb086712.jpg)

I hope that is the right log file. Let me know if there is anything else you need.
I tried again but instead with my windrower and it would turn on for about the first 20 feet then would lift itself and wouldnt re-lower itself.

**Comment by Tensuko** [comment]
Even this is not the baler, I already know whats going on...
When you have only one Headland, we have a transition lane from headland to center, wich won't turn on and lift tools.
You should else have 2 headland (wich I recomment you) or to not hit the transition lane when use start at nearest waypoint, use start at 1st waypoint to make sure it works propper.

Also you should rly update to .00064
https://github.com/Courseplay/courseplay/releases

**Comment by america19999** [comment]
Alrighty I will give it a shot and let you know!

**Comment by Tensuko** [comment]
Closed due to inactivity
