### ISSUE TITLE
Lua Error when tried to add 5th out of 6 Combines to Course

### ISSUE THREAD

**Issue by Nem0x3** [Courseplay/courseplay#6145]
So, i got a huge field to harvest and i wanna do it in a good time. 357ha with 6 combines (would still take 5 hours).
I added 4 Combines and they are fine (on Row Left 3, 2, 1, Right 1) but once i try to add Combine#5 on either Right 2 or 3 (its fine with Row L3/2/1 and R1), the game stutters, spits out the small error and keep going with 10-15 fps (from 55-60) until i release the helper. Is it not possible to get more than 4 combines working? Btw all of them are Lexion 8900 with a 13.7m Cutter from the "Lizard Cutter Set" (FS19_cutterSet.zip). 4 Combines are bought, 2 are leased.

Log; https://pastebin.com/GMBhSVek
The Error is on Line 749-751, if im not wrong
Yes its not the newest version in the log, but the same error occurs with 6.02.00064

**Comment by Tensuko** [comment]
Screenshot of your Course pls, I already have a guess about your Issue.

**Comment by Nem0x3** [comment]
![image](https://user-images.githubusercontent.com/72033753/94459691-0423d700-01b8-11eb-9ad5-cb5d7a155d21.png)
Like this?

**Comment by Tensuko** [comment]
Genau das was ich vermutet habe... Das ist dein Problem:
![Multitool](https://user-images.githubusercontent.com/27344744/94461717-caa09b00-01ba-11eb-8b12-23274be9d18b.png)
Wenn du den Kurs generierst, wähle bei Startposition, Position auf Karte und click dann weiter links auf deinem Feldrand, so das du von der Ecke weg kommst, dann sollt es kein Problem sein.

**Comment by Nem0x3** [comment]
Apparently changed the corners to curved/rund and/or setting the width to the recommended and from overlap 3% to 7% fixes it.

![image](https://user-images.githubusercontent.com/72033753/94461883-00de1a80-01bb-11eb-8cc3-1cdb723873dd.png)

**Comment by Tensuko** [comment]
Das ist auch kein Wunder, weil wir jetzt keine Ecke mehr drin habe...

**Comment by Tensuko** [comment]
Sollte klar sein wo es klemmt.
