### ISSUE TITLE
Problem mit Fahrzeuge durchtabben seit der Courseplay v6.02.00064

### ISSUE THREAD

**Issue by rellek010682** [Courseplay/courseplay#6146]
Seit der v6.02.00064 passiert es immer wieder, dass sich meine Fahrzeuge nicht mehr durchtabben lassen. Es tritt aber nur auf, wenn ich bei einem Fahrzeug den "Silo aufschieben"-Modus benutze. Ich heabe es jetzt mit verschiedenen Fahrzeugen auf diversen Karten probiert. Leider tritt dieser Fehler immer wieder auf. Bei den vorherigen Versionen hatte ich das Problem nicht. Werde vorerst eine ältere Version von CP nutzen.

**Comment by Tensuko** [comment]
logfile ?!
