### ISSUE TITLE
CP on Load Trigger, Player can't load manualy

### ISSUE THREAD

**Issue by VergylTantor** [Courseplay/courseplay#6147]
Vehicle #1 is using a refill route to refill a planter or fertilizer spreader.
Vehicle #2 attempts to manually load from grain storage cannot load.
If #1 is then stopped #2 loads successfully. Note: This part will not show in log file but this happened on another map.
Related to #6122?
[log.txt](https://github.com/Courseplay/courseplay/files/5295381/log.txt)

**Comment by VergylTantor** [comment]
I have added courses and saved game to aid in recreation.
Rename xm_ files to xml in CoursePlay_Courses\MapUS
Load Savegame 2 with Courseplay 6.02.00064.
Enter JCB Tractor
  Load course F26 3.0
  Load course F26 Refill
Start JCB on course.
Use Case tractor and try to load grain from storage.

**Comment by VergylTantor** [comment]
I have added courses and saved game to aid in recreation.
Load Savegame 2 with Courseplay 6.02.00064.
Enter JCB Tractor
  Load course F26 3.0
  Load course F26 Refill
Start JCB on course.
Use Case tractor and try to load grain from storage.

[savegame2 and Courses.zip](https://github.com/Courseplay/courseplay/files/5295981/savegame2.and.Courses.zip)

**Comment by VergylTantor** [comment]
After further investigation it looks like the issue began with v 6.02.00046 as ...45 worked normally and ...46 did not.

**Comment by Tensuko** [comment]
When CP is on a Trigger to refill, you can't manualy load a Trailer.
