### ISSUE TITLE
400 Lines of the same Error spams Log and lags game

### ISSUE THREAD

**Issue by Nem0x3** [Courseplay/courseplay#6150]
I'm back with another issue, this Error
`2020-09-29 13:40 Error: Running LUA method 'update'.
2020-09-29 13:40 dataS/scripts/fieldJobs/FieldManager.lua(564) : attempt to index a nil value`
Starts spamming almost as soon as I have all 6 combines working (thanks for the fix in #6145!), lags my game down to 20 fps and sometimes prevents the combine from unloading into a trailer for simetimes a few secs, to until i saved the game, which at that point takes 10x longer than usual/soft-freezes the game.
[log.txt](https://github.com/Courseplay/courseplay/files/5298707/log.txt)
i slimmed to log down from a few thousand error keybinds. i believe they arent the problem (but a seperate one for me personally)

**Comment by GeorgeEarslight** [comment]
Are you trying to play _FS19_Peasantville2_alfalfa_strawHarvest_ map without the Straw Harvest mod?

**Comment by Nem0x3** [comment]
@GeorgeEarslight Yes, cause the first time i tried to boot the map with it, the loading process freezed and showed errors in log with the strawharvest

**Comment by GeorgeEarslight** [comment]
I'm not sure if this map is even meant to be played without Straw Harvest.
There's a bunch of warnings indicating that it needs it and I don't see Courseplay having anything to do with the FieldManager error flood later. 

```
2020-09-29 13:39 Warning: 'placeable.storages.storage(0)' has invalid fillType 'STRAWPELLETS'.
2020-09-29 13:39 Warning: 'placeable.storages.storage(0)' has invalid fillType 'HAYPELLETS'.
```
FieldManager.lua is a base game script from Giants.

**Comment by Nem0x3** [comment]
As i said, i cant run the map with the strawharvest mod active. its not loading anymore after that error. Works without it tho.

Either way, it seems CP isnt the issue, if Fieldmanager.lua is from Giants itself. and i cant reproduce the errors consistently...guess ill move on from this here :D
