### ISSUE TITLE
Turn Calc Question

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#6154]
I was wondering not sure if this is a bug. So it seems CP turn's function is recalculating the turn while turning ... I was wondering if this was intended behavior or a bug. This is causing the turn speed to drop to zero then back to turn speed for the brief nano second it takes to recalculate the turn. I only noticed this cause I turned on the temp waypoints setting and this course would increase or decrease in radius as the speed dropped. Not sure why the TR would adjust for every turn. This why I bring up the question. I know in 17 the TR was set and forget and the turn calc only occurred once each turn. I was using this with a Deere 6m and Spirit R 300 but I think this cropped up when using another tool. Can provide any logs or video needed.

**Comment by pops64** [comment]
It seems that pathfinding is doing the turning instead of 17's turn code. And for what ever reason pathfinding doesn't use TR when calculating its turn it relies on the using the smallest circle and increase it if it can't make the turn. Yes I tried with the pathfinding setting on and off. It must default to this state when using skip row in course generation.

Mabye we could get pathfinding to use the the TR of the vehicle and adjust after the completion of the turn for the next call case instead of in the middle of the turn. Or some how make this a fluid movement. Cause this stop start movement is very annoying to watch

https://youtu.be/z_WDhTRTpw8

**Comment by pvaiko** [comment]
That is the tight turn offset at work, I'm sure you know that a towed implement travels on a smaller radius than the tractor itself so we are compensating for that here, making sure the implement end up where it should be.

17 was three years ago, things changed, nothing is going to be the same anymore...

**Comment by pops64** [comment]
I understand that but there isn't a way to smooth out this function? The implement doesn't end up where it should be either. The tool is usually slightly off parallel to the row causing a gap at the end of the field. And sprayers are horrible inefficient due to theses changes and the slow avg turn speed. Also, there are somethings CP has never changed and that is the smoothness at which the tractor operates at.
