### ISSUE TITLE
Bahnversatz bei mehreren Erntemaschinen (MP rental server)

### ISSUE THREAD

**Issue by CmdrTiri** [Courseplay/courseplay#6155]
Hallo zusammen,

zuerst einmal DANKE dafür, dass Ihr so tolle Arbeit macht und Eure Mod inzwischen recht gut auf serverbasierten Multiplayer-Spielen läuft!

Gestern wollte ich zwei Rübenernter als Kolonne über ein Feld schicken. Den Kurs berechnet CP auch wunderbar, jedoch ignorieren die Ernter die Einstellung "rechts" bzw. "links" und fahren beide in der Mitte. Auch ein Deaktivieren des Fahrzeugverbandes und eine manueller seitlicher Versatz wird nicht angenommen.
Heute habe ich das selbe Problem mit meinen Mähdreschern von Claas erlebt. Der Bahnversatz wird komplett ignoriert.

Liegt das am MP-Server, oder ist da im Code vielleicht irgendwas verrutscht?
Hab das leider noch nicht bei nem offline-Spiel probiert, kann ich aber gerne noch ausprobieren, wenn es nötig ist.

LG Tiri

**Comment by Tensuko** [comment]
MP Issue, ist bekannt.
