### ISSUE TITLE
Bunkersilo befüllen/ Verdichten

### ISSUE THREAD

**Issue by 3lronMcBong** [Courseplay/courseplay#6156]
Hallo,

hab das Problem das beim Mode Bunkersilo Verdichten/Befüllen manchmal der CP Fahrer auf seinem Wartepunkt stehen bleibt und nichts mehr macht. Muss ihn manuell wieder einstellen.
Wenn dann der AD Fahrer kommt bekommt er ein Signal zum halten das macht er auch aber dann bleiben alle stehen....
Vielleicht nach 2-4 Fuhren vom AD Fahrer dann passiert es.

![fsScreen_2020_09_30_19_10_53](https://user-images.githubusercontent.com/5399009/94842656-f078aa80-041b-11eb-9890-43bef0ca4416.png)
![fsScreen_2020_10_01_19_08_35](https://user-images.githubusercontent.com/5399009/94842689-fc646c80-041b-11eb-8075-8d7010a549e0.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5313817/log.txt)

**Comment by Tensuko** [comment]
Duplicate  #6151
