### ISSUE TITLE
Course generation problem 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#6159]
Hello I’m on the new holm wold farm map and I’m try to generate a course for a field but it’s saying cannot generate course please move the vehicle or change settings I ran debug 7 and couldn’t see any problems in the log. Matt

**Comment by Tensuko** [comment]
When you already turned on channel 7 to generate, why not attch the logfile ?!

**Comment by matty2123** [comment]
Shall produce one tomorrow

**Comment by polosubtil** [comment]
Hi @matty2123 
I just started playing on this map and I had this issue for field 50. If it is the same field you are talking about, you can solve the issue by painting the north west corner of the field (connection with field 49) using the landscape tool with a bit of grass or anything else really.
![image](https://user-images.githubusercontent.com/60451845/94976005-cdc9bd00-0513-11eb-801a-f3200f31316d.png)

**Comment by GeorgeEarslight** [comment]
Can confirm that the fields are connected and @polosubtil solution works.
The map author is aware and will solve the problem by their side.

**Comment by matty2123** [comment]
I’m on f54 which ain’t nothing to do with these fields?

Sent from my iPhone

On 3 Oct 2020, at 08:29, GeorgeEarslight <notifications@github.com> wrote:

﻿

Can confirm that the fields are connected and @polosubtil<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpolosubtil&data=02%7C01%7C%7Cf5b44224c7424883413c08d8676e0e3b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637373069658221963&sdata=BDJ%2FnMqUJxWfhf%2FsmTX3wh1XOBs8WJ6ycvN62raQb3Y%3D&reserved=0> solution works.
The map author is aware and will solve the problem by their side.

**Comment by VergylTantor** [comment]
I used the terrain panting tool to place some long grass between Field 54 & Field 55 in the Northern opening in the hedge to fix this.

**Comment by matty2123** [comment]
Oh ok thanks seems it’s not cp friendly

Sent from my iPhone

On 3 Oct 2020, at 09:38, VergylTantor <notifications@github.com> wrote:

﻿

I used the terrain panting tool to place some long grass between Field 54 & Field 55 in the Northern opening in the hedge to fix this.

**Comment by VergylTantor** [comment]
Can This be closed?
