### ISSUE TITLE
Kaufen von Krone big X (Mod) nicht möglich wegen coursplay 

### ISSUE THREAD

**Issue by Playlord75** [Courseplay/courseplay#6161]
![image](https://user-images.githubusercontent.com/71101944/94986979-650a3100-0563-11eb-9e31-e9c793d8fb50.png)
ein krne big x mod häcksler will sich wegen cp nicht öfnen lassen es kommt immer deiser lua fehler

**Comment by Tensuko** [comment]
Mod Issue

**Comment by andremeyer123** [comment]
Link zum Mod bitte

**Comment by Playlord75** [comment]
also fehler von cp ist es nicht habe ich jetzt festgestelt hab mir eine ältere version von dem besorgt und damit trit der fehler nicht mehr auf anscheindend hat der moder irgendwas verhauen
