### ISSUE TITLE
Combine Scanning for Dedicated Server

### ISSUE THREAD

**Issue by Dukefarming** [Courseplay/courseplay#6162]
Hi I am Dukefarming and I am having trouble on my server with course play scanning for the combine. Below is the server game log. I hope this helps.
[server log.txt](https://github.com/Courseplay/courseplay/files/5321366/server.log.txt)

**Comment by Tensuko** [comment]
And what Problem ? ...

**Comment by Dukefarming** [comment]
Overloader is not wanting to go to unload the combines
[server log2.txt](https://github.com/Courseplay/courseplay/files/5321410/server.log2.txt)
![fsScreen_2020_10_03_06_04_59](https://user-images.githubusercontent.com/72299339/94989116-58c0ac80-0540-11eb-8d8d-c893da4ffa26.png)
![fsScreen_2020_10_03_06_10_48](https://user-images.githubusercontent.com/72299339/94989118-59f1d980-0540-11eb-928b-8035c6d9346f.png)
![fsScreen_2020_10_03_06_10_53](https://user-images.githubusercontent.com/72299339/94989119-5bbb9d00-0540-11eb-8aa8-8f4d6919d806.png)
![fsScreen_2020_10_03_06_11_05](https://user-images.githubusercontent.com/72299339/94989120-5e1df700-0540-11eb-9c53-95aedf9b5e87.png)
![fsScreen_2020_10_03_06_11_20](https://user-images.githubusercontent.com/72299339/94989124-6118e780-0540-11eb-9b8d-368d30dcda28.png)
![fsScreen_2020_10_03_06_13_52](https://user-images.githubusercontent.com/72299339/94989127-637b4180-0540-11eb-98bc-8b3f9384ec81.png)
![fsScreen_2020_10_03_06_14_23](https://user-images.githubusercontent.com/72299339/94989129-64ac6e80-0540-11eb-9c3d-b3f901819b2b.png)

**Comment by Tensuko** [comment]
Did you rly start the Overloader in Mode5 and not Mode3 ?

**Comment by Dukefarming** [comment]
no mode 3

**Comment by Tensuko** [comment]
Started with 'unloading' ?

**Comment by Dukefarming** [comment]
I don't know what you mean

**Comment by Tensuko** [comment]
![unloading](https://user-images.githubusercontent.com/27344744/94990973-351d5680-0580-11eb-90bc-6bcde3ee365d.png)

Drive in circle mostly means he can't hit the waypoint, I wonder what happens when you start at 'unloading'

**Comment by Dukefarming** [comment]
Tractor just stays will not go unload ether combine
 ![fsScreen_2020_10_03_18_27_33](https://user-images.githubusercontent.com/72299339/95002823-4ed19480-05a6-11eb-9125-e2dcaa4f5fda.png)
![fsScreen_2020_10_03_18_30_05](https://user-images.githubusercontent.com/72299339/95002899-141c2c00-05a7-11eb-95ad-23ccd864b4aa.png)
![fsScreen_2020_10_03_18_30_09](https://user-images.githubusercontent.com/72299339/95002901-154d5900-05a7-11eb-883d-9c1aff8d0dd9.png)
![fsScreen_2020_10_03_18_30_19](https://user-images.githubusercontent.com/72299339/95002902-154d5900-05a7-11eb-8de6-c8368a402b86.png)
![fsScreen_2020_10_03_18_32_44](https://user-images.githubusercontent.com/72299339/95002903-15e5ef80-05a7-11eb-88ed-07cc309a5715.png)
![fsScreen_2020_10_03_18_32_52](https://user-images.githubusercontent.com/72299339/95002904-167e8600-05a7-11eb-9113-741ba5062ec1.png)

**Comment by Tensuko** [comment]
Do you drive the Combine by yourself ?
That is not possible yet, read #5272 and WIki

**Comment by Dukefarming** [comment]
Hired help doesn't work ether

**Comment by Tensuko** [comment]
Only CP driven Combine does

**Comment by Dukefarming** [comment]
ok
