### ISSUE TITLE
Error: Running LUA method 

### ISSUE THREAD

**Issue by Pioner912** [Courseplay/courseplay#6163]
Hallo zusammen, 

Ich habe gestern schon einmal einen Issue gemeldet und heute wollte ich beim zuletzt gespeicherten punkt weiter machen (Link zeigt die dazu gehörige Meldung von Gestern worauf diese ggf. aufbaut.) 
https://github.com/Courseplay/courseplay/issues/6158

Heute wollte Ich nachdem alle Abfahrer gestartet wurden und es zunächst auch gut lief 
einen weiteren Abfahrer Mit AD etwas abholen und liefern lassen! 
Als dann dieser Fehler wieder alles zum Stillstand gebarcht hat, das Koriose ist eigentlich das Ich einen weiteren Fendt 939 + Kröger Anhänger etwas transportieren lassen wollte. 

Zum Hergang Ich stiegt an einem Unterstand in den 939 ein dieser war zu der Zeit mit einer Amazone Sämaschine noch verbunden ich trennte die Verbindung und wollte an den Kröger Anhänger ankuppeln, bevor ich dies schaffen konnte trat der Fehler ein und nichts ging mehr. 
Die Tachoanzeige sowie das über ESC erreichbare Menü ließen sich nicht mehr öffnen aber durch die Mod "FS19_EasyDevControls" und das ewige Öffnen und schließen per F11 konnte ich durch die Fahrzeuge Tabben bis mir auffiel das nur der Fendt 939 welchen ich mit einem Anhänger zum Ab/Beladen schicken wollte keinen Tacho mehr hatte alle anderen Fahrzeuge gingen weiter ihrer Arbeit nach, auch wenn im Coureplay menü stand "Arbeiter einstellen". 

Den Fehler konnte ich dardurch resetten das ich den Fendt am Fahrzeughändler im Menü (ging ebenfalls nur mit EasyDevControls zu öffnen) um konfiguriert habe ,Motor auf 9.. geändert. Tractor ist original Giants der Anhänger ebenfalls.

Was mir noch auffällt ist das ich irgendwann in der Konsole "hallo" geschrieben habe um zu überprüfen ob der Fehler sich noch immer dubliziert diese Einträge fehlen in der Log komplett und sind von mir nicht gelöscht worden.

Link zu der Sämaschine : 
http://www.farmingsimulator19mods.com/amazone-condor-15001-nf-marsch-multifruit-v2-5-fs19/

[log.txt](https://github.com/Courseplay/courseplay/files/5321653/log.txt)

**Comment by Tensuko** [comment]
Dinge die man Ingame in die logdatei schreibt, werden im logfile nicht angezeigt, das ist normal!

Errors:
2020-10-03 11:54 Error: Running LUA method 'update'.
2020-10-03 11:54 C:/Users/manue/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CombineUnloadManager.lua:57: attempt to call method 'is_a' (a nil value)

2020-10-03 11:54 Error: Running LUA method 'draw'.
2020-10-03 11:54 C:/Users/manue/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/base.lua:608: attempt to index field 'triggerHandler' (a nil value)

**Comment by Pioner912** [comment]
Okay das wusste ich nicht wieder etwas gelernt danke habe gerade wieder versucht das Spiel zu starten und es lädt direkt wieder mit diesem Fehler, hast du einen Tipp was ich dagegen machen kann @Tensuko ?

**Comment by Tensuko** [comment]
Oha hmm schwierig, kannst du ingame irgend etwas machen ?

**Comment by Pioner912** [comment]
Ja ziemlich alles aber immer nur in Verbindung mit Devcontrols weil ansonsten mein Avatar einmal über die Map rennen möchte das kann ich damit dann immer stoppen.

**Comment by Tensuko** [comment]
ok fals du in die Fahrzeuge die mit CP liefen rein kommst, starte da mal Devcontrols und Setze die Fahrzeuge zurück (letzter Reiter, Fahrzeug neu Laden -> Standart). Es kann sein das dann noch mal Errors auftauchen, aber wenn du das gemacht hast, speichern und savegame neu laden und dann mal schauen ob der error noch immer kommt.

**Comment by Pioner912** [comment]
@Tensuko habe ich probiert aber das Spiel hat sich geschlossen kein neuer Fehler in der Log habe das Spiel nochmal neu gestartet und sobald ich in den Xerrion steige welcher Gras gesammelt hat und den neu laden lasse schließt sich das Spiel erneut.

**Comment by Tensuko** [comment]
CP mal raus nehmen, savegame laden, speichern, CP wieder rein ?

**Comment by Pioner912** [comment]
@Tensuko das habe ich soweit gemacht und bekomme folgende Meldung Warning: Could Not add Shape 'tensionBeltNode' (tensionBeltNodeshape) to tension belts due to the missing CPU mesh flag. 

Dieser Fehler kommt nach dem neu Laden (wieder mit courseplay) immer noch aber der Courseplay Fehler ist erstmal weg.

**Comment by Tensuko** [comment]
tensionBeltNode hat mit CP aber nicht wirklich was zu tun.
Hauptsache du kommst erst mal wieder ins Savegame ohne die CP Error.

**Comment by Pioner912** [comment]
@Tensuko Weißt du woher so ein Fehler denn kommen kann dann würde ich ggf. die entsprechende Mod tauschen wollen. 

Erstmal vielen Dank für die Hilfe ist nicht selbstverständlich.

**Comment by Tensuko** [comment]
Interessanter weise ist heir der gleiche Error ohne Mods:
#6164
Wie der zu stande kommt ist mir ein Rätzel...

**Comment by Tensuko** [comment]
Hast du Discord?
Tensuko # 2300

**Comment by Tensuko** [comment]
Ok ich glaub ich hab den Error....

**Comment by Tensuko** [comment]
Hattest du im Fenster wo man die Nachfüllsachen Einträgt Saatgut + Dünger drin ?

**Comment by Pioner912** [comment]
@Tensuko Normaler weise ja denn der Tractor ist nur für das ansäen gedacht gewesen ich stelle das bei euch ein und sage AD zusätzlich auch er soll Dünger bzw. Saatgut auffüllen, wieso habe ich einen Fehler gemacht?

**Comment by Tensuko** [comment]
Nein du nicht, aber wir :) 
Kann man selber ganz leicht probieren:
Neue savegame, nur CP, Traktor + Saatmaschine kaufen, anhängen
Mode4 anmachen, saatgut + dünger eintragen, gerät abkuppeln.

Warum das nich aufgefallen ist:
#6107 hier war der Fehler schon einmal, das ist auch gefixt, allerdings nur, wenn man nur ein filltype eingetragen hat.

**Comment by Tensuko** [comment]
Achso ich mach hier zu nicht wundern, weil wir den gleichen Fehler noch mal haben.

**Comment by Pioner912** [comment]
Habe dir bei Discord eine Anfrage gestellt Manuel91 #4170
