### ISSUE TITLE
Mode 9 2.ter Radlader funktioniert nicht

### ISSUE THREAD

**Issue by Kartracer390** [Courseplay/courseplay#6165]
Gibt es bei dem Mode9 bekannte Probleme, wenn man zwei Radlader gleichzeitig zwei verschiedene BGAs aus 2 verschiedene Fahrsilos auffüllen lässt?
Den ersten den ich aktiviere, funktioniert immer super. Wenn ich dann den zweiten Radlader starte, dann bekomme ich immer Probleme, dass der das BGA-Silo gar nicht reinfährt, sondern am Anfang direkt stehen bleibt und wieder rückwärts fährt.

_Originally posted by @Lars-LS17 in https://github.com/Courseplay/courseplay/issues/6133#issuecomment-702761821_

**Comment by Tensuko** [comment]
Hab mal bisschen rumprobiert und ja irgendwie arbeiten die nicht sauber wenn es 2 gleichzeitig sind, aber ich kann mich auch nicht daran erinnern das jemals getan zu haben.
Wird aber erstmal nach hinten verschoben.

**Comment by Crinouche** [comment]
Hello,
I also have this problem.
What I don't understand is that mode 9 worked fine until version 6.02.0045. But since the following versions, this mode 9 has become hell  :(
We can no longer empty 2 silos at the same time, impossible to load a trailer. The shovel does not recognize them ... etc.

**Comment by Tensuko** [comment]
@Crinouche that are different problems and the mode9 will get maybe a rework, but we had to care for otehr things too like shovel empty into full BGA Bunker and throws all on the ground and stuff like that.
We will care for this one later.

**Comment by Crinouche** [comment]
thank you for your answer, I can't wait for it to work again as before!

**Comment by Dennis42g** [comment]
Guten Tag !  spiele LS19 habe jetzt die neuste Version von CP drauf die Radlader die an zwei verschiedende stellen an BGA s fahren machen es jetzt gar nicht mehr und wenn nur einer wenn man glück hat am sonsten bleiben sie nur stehen oder machen misst ! es hatte vor her super geklappt ! selbst bei anderen hatte es super geklappt  !hatte es auch bei dem Youtuber Fed gesehen da lief es auch ! nur jetzt nicht mehr ! wird sich das noch mal wieder ändern wieder !? 

und danke für so eine super Arbeit !

mit freundlichen grüßen dennis .

**Comment by Lars-LS17** [comment]
@Dennis42g 
Moin Dennis,

hier musst du aber auch unterscheiden. Der Youtube Fed hat gestern auf die neuste Version upgedatet und hat nun auch die Probleme. 
Vorher hatte er immer eine Uralt Version. Da gab es das Problem noch nicht. Durch neuen Code und Anpassungen ist leider dieser Fehler aufgetreten. Ich gehe davon aus, dass die Moder von CP dies beheben werden, wenn die Zeit dazu finden.

Solange immer nur ein Radlader an der BGA nutzen.
Wenn du zwei BGA hast, dann erst an der ersten den Bunker auffüllen und danach zur anderen BGA fahren und dort den Radlader einstellen.

**Comment by Dennis42g** [comment]
@Lars-LS17 
Hallo Lars

ich hatte schon früher das problem wusste nur nicht wie und wo ich bescheid geben muss war von 074 nach der neuseten CP version gesprungen da ging es nicht mehr und zurück auf 074 da ging es hinter her auch nicht mehr  ! 

Der die Modder machen echt geile Arbeit ich schätze es was sie für uns tun da zu sage ich auch herzlich dank und daumen hoch ! wäre cool würden die radlader das demnächtest es wieder können !

und danke das ihr eure freitzeit für uns opfert danke 

und schöne feier tage !
mit freutlichen güßen Dennis

**Comment by schwiti6190** [comment]
@Dennis42g , @Lars-LS17 könntet ihr mal diese alte version v6.02.00045 auf genau das problem testen bzw. Falls möglich die letzt mögliche version wo es klappt heraus finden ?  Das wäre echt hilfreich bei der fehler suche :)

**Comment by Dennis42g** [comment]
@schwiti6190 Guten Tag !

Ich hatte es mit 6.02.00074 Version die Radlader die Fahrsilos leer fahren lassen ! dann hatte ich die 6.03.00001 Version da ging gar nicht s mehr dann bin ich noch mal auf 6.02.00074 Version ZURÜCK  da wollten die Radlader es auch nicht mehr machen ! 

Mehr Versionen von CP hatte ich auch nicht benutzt da ich erst ca. Halbes Jahr bei Ls19 bin 

Mit freundlichen Grüßen Dennis

**Comment by Dennis42g** [comment]
@schwiti6190 ja ich kann die alte Version mal testen weiß nur nicht ob ich es heute noch schaffe aber gebe schnell Bescheid

**Comment by Tensuko** [comment]
Wichtig ist: alte Version heist altes Toolpositionssystem, also immer die Positionen neu einteachen!

**Comment by Dennis42g** [comment]
@Tensuko hallo 

Sorry das ich frage das heisst im klar text !?

**Comment by Tensuko** [comment]
Deine Schaufelpositionen wirst du beim wechsel zu einer alten Version wieder neu machen müssen, auch wenn du dann wieder auf die neueste gehst, wieder neu, weil wir das System zwischenzeitig geändert haben.

**Comment by Dennis42g** [comment]
@Tensuko 

Alles klar also hatte ich es doch richtig verstanden danke das noch mal geschrieben hast ! 

Bei 6.02.00074 sind bei mir zwei Radlader gefahren nur das funkt jetzt nicht mehr leider irgendwie klappt es nicht bei der neuen Version

**Comment by Tensuko** [comment]
Naja wir haben nicht umsonst Änderungen vorgenommen.
Versuch es sonst mal mit Fahrzeug resetten oder schaut doch mal mit welcher Version FedAction gearbeitet hat, als bei ihm 2 Radlader liefen.

**Comment by schwiti6190** [comment]
in der version 6.02.0045 wurden änderungen für den mode vorgenommen nur kann ich nicht nachvollziehen wie sich das problem nur bei mehreren mode 9 driver bemerkbar macht und ein einzelner klappt. Ein genaue beschreibung was die probleme sind und wann diese genau auftauchen (position der driver auf dem kurs etc.) am besten mit bildern/videos und einen log file mit debug channel 10 aktiv würde aufjedenfall helfen. 
Eine weitere sache wäre ob das problem auch bei mehreren mode 10 (silo verdichten etc.) gleichzeitig auch auftritt da diese vom code her ähnlichkeiten aufweisen wäre ebenfalls hilfreich.

**Comment by Lars-LS17** [comment]
Hallo,

ich habe jetzt mal ein Test gemacht mit den Mode 9.
Einmal mit der CP Version 6.02.0045 und 6.03.0008

Dazu habe ich Videos mitgeschnitten und die Log zwischen gespeichert.
Hier die Version 6.02.0045:
[log_CP-Version 6.02.0045.txt](https://github.com/Courseplay/courseplay/files/5674629/log_CP-Version.6.02.0045.txt)
https://youtu.be/lwTvwY9e-bs

HIer die Version 6.03.0008:
https://youtu.be/sryTFJxQiYE
[log_CP-Version 6.03.0008.txt](https://github.com/Courseplay/courseplay/files/5674630/log_CP-Version.6.03.0008.txt)


Ich hoffe das ist das, was du haben wolltest, um dir bei der Fehlersuche zuhelfen.

**Comment by Lars-LS17** [comment]
Kurze Zusammenfassung als Nachtrag:
Mit der Version 6.02.00045 hat es perfekt funktioniert. 
Mit der Version 6.03.00008 ging es gut, bis der zweite Radlader beim Bunker abladen angekommen ist. Dann ist der einfach stehen geblieben und hat nicht mehr abgekippt. 
Ich habe bei beiden Videos die exakten Kurse genommen. Diese wurden nicht verändert. Nur die Schaufel Einstellung musste ich natürlich neu machen.

**Comment by Tensuko** [comment]
Fehler gefunden, update kommt bald.

**Comment by Tensuko** [comment]
Fixed with .00015
