### ISSUE TITLE
Fahrzeugverband macht was er will

### ISSUE THREAD

**Issue by bauerwilhelm** [Courseplay/courseplay#6168]
Wenn ich einen Drescherverband (2 Stück) starten lassen möchte, fährt - wenn überhaupt - nur der erste Drescher vernünftig durch das Feld. Der zweite Drescher fährt, ohne den Arbeitsmodus einzuschalten, mit der erlaubten Feld-Höchstgeschwindigkeit durch die Botanik und macht sonst nichts. Wenn ich selbst vorher den Arbeitsmodus einschalte und das Schneidwerk senke, fährt er ebenfalls mit der Höchstgeschwindigkeit (meistens 40 km/h) **erntend** durchs Feld. Manchmal macht der erste das auch. Allerdings springt die Anzeige für die Verbandfahrt unten in der CP-Anzeige auch nie um.

Getestet mit den Mods: Annaburger HTS 34.16, Claas Pack und Easy Developement Tools auf den Maps Oberthal und Goldcrest Valley. Zuerst mit dem Lizard 13,7 m Schneidwerk getestet, dann mit dem Original Claas Convio 1230.

**Comment by Tensuko** [comment]
logfile, screenshots ?

**Comment by bauerwilhelm** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5322403/log.txt)
Ich hoffe, dass ist so richtig mit der log. Da stehen auch die Sachen aus den anderen Spielständen drin, oder?
![20201004010318_1](https://user-images.githubusercontent.com/63925638/95003364-eeab1480-05de-11eb-8918-519f5e330db4.jpg)
![20201004010502_1](https://user-images.githubusercontent.com/63925638/95003368-f36fc880-05de-11eb-8428-17218e463aff.jpg)
![20201004010510_1](https://user-images.githubusercontent.com/63925638/95003371-f7034f80-05de-11eb-8b65-39daabcd9bad.jpg)
![20201004010715_1](https://user-images.githubusercontent.com/63925638/95003372-fa96d680-05de-11eb-8edf-839ad13bd07f.jpg)
![20201004010738_1](https://user-images.githubusercontent.com/63925638/95003374-fd91c700-05de-11eb-9607-6414ea6be0d5.jpg)
![20201004010825_1](https://user-images.githubusercontent.com/63925638/95003379-0387a800-05df-11eb-8308-4ced0eb5f207.jpg)

**Comment by andremeyer123** [comment]
Moin  
versuche es bitte mal mit  fruchtumfahrung deaktiviert kurz nicht in der ecke starten lassen 
C:/Users/torbe/Documents/My Games/FarmingSimulator2019/mods/FS19_VehicleExplorer/VehicleSort.lua:1591: attempt to index field 'mapHotspot' dieser Mod verursacht auch schon fehler bei dir 
![1](https://user-images.githubusercontent.com/70706468/95008240-621d4800-0618-11eb-8d69-975a3f29dea0.png)
![2](https://user-images.githubusercontent.com/70706468/95008241-634e7500-0618-11eb-8795-3d428a579dee.png)
![3](https://user-images.githubusercontent.com/70706468/95008242-63e70b80-0618-11eb-8054-76c0e055f7cd.png)
![4](https://user-images.githubusercontent.com/70706468/95008243-647fa200-0618-11eb-90ff-21ae625fb845.png)

**Comment by Tensuko** [comment]
Drescherverband aktiviert ? (Seite 4)
Ersten Drescher im Bahnversatz auf 'links' ? (Seite 9)
Zweiten auf 'rechts' ?
Geht eigentlich ohne Probleme.

**Comment by bauerwilhelm** [comment]
@andremeyer123 An der Fruchtumfahrung kann es nicht liegen, jeder Drescher fährt bei mir ganz normal an den Startpunkt, geht in den Arbeitsmodus und drischt wie ein Profi. Bei Feld 27 gibt es doch gar keine richtigen Ecken (davon abgesehen passiert das bei anderen Maps ja auch, trotz Start an der langen Kante haha). Und der Vehicle Explorer ist bei den entsprechend ausgelegten Tests immer deaktiviert gewesen.

@Tensuko Jap, genau das sind meine Einstellungen. Trotzdem passiert das Geschilderte.

**Comment by andremeyer123** [comment]
naja du siehst ja das es geht mit 80 mods und 4 fachkarte versuche es mal nur mit cp und ad und mods die du dringend brauchst für die karte wenns geht die anderen mods nach und nach mit rein nehmen ins spiel 
wenn fehler auftauchen spiel ganz aus machen und neustarten

**Comment by bauerwilhelm** [comment]
Okay also: Es scheint tatsächlich ausschließlich an der Fruchtumfahrung zu liegen, diese muss wirklich ausgeschaltet sein. Weil ich damit bei einzeln fahrenden Dreschern nie Probleme hatte, hab ich mir nicht vorstellen können, dass es daran liegt. Nicht einmal der Vehicle Explorer mit dem lua-Fehler scheint Schuld gehabt zu haben...

Kann man, während der Helfer eingestellt ist, die Fruchtumfahrung wieder einschalten, sodass der/die Drescher im Fall der Fälle wie bekannt zurückfahren, wenn das Rohr in der Frucht und der Tank voll ist, oder muss man den Helfer entlassen, das umstellen und dann wiedereinstellen, damit das erkannt wird?

**Comment by Tensuko** [comment]
Sollte gehen, da in dem moment geprüft wird, was sie tun sollen.

Ich kann mir das mit Fruchtumfahrung deaktiviert nicht erklären.
Meine Drescher fahren immer mit aktiver Fruchtumfahrung...

**Comment by andremeyer123** [comment]
Ist ja Top wenn es jetzt geht umstellen geht während der fahrt

**Comment by bauerwilhelm** [comment]
Noch ein Zusatz: Wenn ich selbst den Weg bis zum Startpunkt freidresche und dann von dort aus den Helfer einstelle, wo ich ursprünglich starten wollte, geht es genau so, als hätte ich die Fruchtumfahrung aus. Also es muss ja tatsächlich irgendwas mit der Fruchtumfahrung zu tun haben. Wenn ich noch irgendwas zur Verfügung stellen soll, teilt es gerne mit.

**Comment by Tensuko** [comment]
Es hat nichts mit der Fruchtumfahrung zu tun!
Ist die Fruchtumfahrung aktiviert, versucht der Pathfinder einen Weg zum Start zu finden (wenn man starten am ersten Wegpunkt nutzt), der Pfad kann auch mal etwas merkwürdig aussehen. Fährt man einfach so in die nähe vom Start in der Frucht, geht es so wie es soll.
https://1drv.ms/v/s!ArGbP_j369r8mDDlTQWgXPCQn-H-?e=D2Nc9y

**Comment by bauerwilhelm** [comment]
Also bei mir hat es halt geholfen, ich hab es auch nochmal nach deinen Einstellungen gerichtet. Dennoch macht CP dann komische Dinge. Aber naja, bei mir läufts und andere Leute scheinen das Problem nicht zu haben, oder?

**Comment by Tensuko** [comment]
Da es so für dich klappt ist ja okay, auch wenn ich das nicht nachvollziehen kann.... Mache hier zu
