### ISSUE TITLE
ÜLW fährt an stehendem Drescher und am Abladeort vorbei (VCA ursächlich)

### ISSUE THREAD

**Issue by bauerwilhelm** [Courseplay/courseplay#6169]
Beide getesteten ÜLW (Elmer's und Horsch (aus dem Horsch-Pack) fahren mit den entsprechenden Zugmaschinen an den o.g. Stationen vorbei, WENN in den Einstellungen _Getriebe und Helfer_ nicht auf _aus_ gestellt wird (so zumindest mein Ergebnis nach etwas "Ermittlungsarbeit"/Herumprobieren. 

Vielleicht ist das nicht unbedingt ein issue, aber zumindest ein Tipp, falls es anderen Leuten auch so geht. :)

**Comment by Tensuko** [comment]
Nich auf aus, doppelte Verneinung aber okay.
Natürlich muss das auf aus... aber kein CP Fehler.
