### ISSUE TITLE
Combine Swather Error with Courseplay (.63-.65)

### ISSUE THREAD

**Issue by Turk-WLF** [Courseplay/courseplay#6170]
Since version (6.02.00063) I have had an error, where Courseplay automatically engages the swather on a Combine even when it was disengage at the start. Instead of the Combine spreading out the chaff, the combine drops it in rows.

I’ve tried on both Ravenport and Welker Farms Map & with default (New Holland TX32) & modded Combines (Case IH Axial-Flow 240, AGCO Ideal). 

My normal Courseplay Harvesting course is 

Headland: Around
Headland Pass: Max for the Field
Headland Counter-/Clockwise: Clockwise
Headland Corners: Turn

The rest are the standard settings depending on the Field/Map/Combine.

**Comment by Tensuko** [comment]
Did you check the Settings in adv Settings ?!
Also no logfile....

**Comment by andremeyer123** [comment]
hello
![fsScreen_2020_10_04_07_45_51](https://user-images.githubusercontent.com/70706468/95008349-701f9880-0619-11eb-9aa9-67102d2cbc0d.png)
![fsScreen_2020_10_04_07_45_55](https://user-images.githubusercontent.com/70706468/95008350-7150c580-0619-11eb-9d0c-9cc88cba57c0.png)

**Comment by Tensuko** [comment]
Muss an deinen Mods oder so liegen, bei mir läuft es so wie es soll.
Aus ist aus egal ob Vorgewende oder Zentrum.

**Comment by Turk-WLF** [comment]
I’m sorry but I can’t find my log.txt file at all in my FS19 folder, however somehow I accidentially changed the “Harvester Straw Discharge” setting within the Advance settings to “Actived”.  When I changed the Setting to “Deactived” it started doing what I wanted.
