### ISSUE TITLE
Silo aufschieben oder Silo walzen inkonsistent (leicht buggy)

### ISSUE THREAD

**Issue by ChilliPommes** [Courseplay/courseplay#6172]
Moin moin,
mir ist in den letzten Tagen aufgefallen, dass das Silo walzen / verteilen leider immer mal wieder etwas inkonsistent ist.
Der Helfer schafft es nur in seltenen Fällen innerhalb des Silos zu bleiben oder was deutlich öfter auftritt, er fährt einfach direkt nach links oder rechts gegen die Wand.

Ich habe mich dann mal auf die Suche nach einer Ursache gemacht.
Gerade bei grösseren Silos hat der Helfer schnell das Problem, dass er als Initialpunkt die falsche Col, Row Kombi wählt und dann kein Wendemanöver ausführen kann.

Visuell dargestellt:
x -> Quadrat der Silo Aufteilung
o -> Wegpunkt der angefahren werden soll
p -> Position des Fahrzeugs

x x x x x
x x x x x
x x x x x
x x x x x
x x p x o

![screen1](https://user-images.githubusercontent.com/66549361/95011160-03af9400-062f-11eb-8fd6-718db3920f5d.png)

Das Bild veranschaulicht die Situation nochmal im Spiel selbst.
Enden tut die Situation dann immer so:

![screen2](https://user-images.githubusercontent.com/66549361/95011178-1fb33580-062f-11eb-8eef-7621a1c117d5.png)

Wenn ich es recht überblicke, gäbe es hier 2 schnelle und sauberer Lösungen.
1. Das Fahrzeug fährt nach erreichen des TipTriggers immer ein Stück nach hinten und kann so auch sehr breite Silos immer optimal anfahren.
2. Das Fahrzeug startet immer mit einem Quadrant der direkt am Fahrzeug ist und geht dann von dort aus weiter.

Courseplay Version ist : 6.02.00064

Logfile:
[log.txt](https://github.com/Courseplay/courseplay/files/5322883/log.txt)

Ich weiss nicht ob dieses Problem schonmal getracked wurde, falls ja entschuldige ich mich für ein Duplikat,
ich konnte zumindest nichts finden in den Issues die offen sind.

Ich hatte schonmal versucht mich durch den Quellcode zu wälzen, um eine meiner Ideen umzusetzen, suche aber derzeit noch die ganzen Stellen raus, wo es im Endeffekt ausgeführt wird.
Zugrunde liegenden Stellen sind:
BunkerSiloManager:getBestColumnToFill(siloMap)
BunkerSiloManager:setOffsetsPerWayPoint(course,siloMap,bestColumn,ix)

Dort drinne oder nach dem Aufruf passiert das Unglück dann.
Wenn ich hier vllt. einen guten Tip bekommen würde, könnte ich eventuell was machen :)

Ich hoffe ich konnte die Situation recht gut beschreiben.

Liebe Grüsse
Chillipommes

**Comment by Tensuko** [comment]
Stoppunkt weiter weg vom Bunker und es passt.
Dein Winkel vom Stop zur Ecke ist einfach zu klein, das sind ja fast 2mal 90° die er fahren müsste.

**Comment by 3lronMcBong** [comment]
wie Tensuko schon sagte, Stop Punkt zu dicht am Silo.
Du musst dem Fahrer auch ein bisschen abstand lassen, somit kann er besser das ziel erreichen.
Am besten zwei Fahrzeuglängen Abstand vom Stoppunkt bis zum Silo dann geht es auch besser.
Gerade bei sehr breiten Silo´s angenehmer.

**Comment by ChilliPommes** [comment]
So geht es natürlich auch 👍 

Vllt. ist es ja eine Anregung für ein kommendes Feature :D

LG

**Comment by Tensuko** [comment]
Kombiniere mal die Issues, sind ziemlich ähnlich...  #6174
