### ISSUE TITLE
Sprayer cars/trucks

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/courseplay#6173]
Hello everybody,

I hope you doing well !

I just notice that after playing a bit on new version of course play, the sprayer trucks are blocking when passing close to other equipment, tractors, harvesters etc. Anybody had this problem ? Latter on I will put my log, but my question is which debug option I must use to check what is wrong ?

**Comment by Tensuko** [comment]
logfile, screenshot with F5 on...

**Comment by envikowaty** [comment]
log.txt
https://gist.github.com/envikowaty/743b2c5b25f14d2f7a9d4da8204de337

**Comment by envikowaty** [comment]
![Uploading 23BC1979-8C67-4CC2-B7BA-D64E8809C191.jpeg…]()

**Comment by envikowaty** [comment]
![06E50105-ADEC-4300-92FC-735CD567BF2E](https://user-images.githubusercontent.com/69640077/95097180-186e5380-0725-11eb-95eb-87350f3bf2a3.jpeg)
![46B549E4-A0BC-48A6-9A08-0C1B84DDB0FA](https://user-images.githubusercontent.com/69640077/95097230-26bc6f80-0725-11eb-9fb5-e9c7a628076e.jpeg)

**Comment by Tensuko** [comment]
Realy ?!
You can drag and drop files and pictures into the comment box and not make a photo of it from screen with your phone..... and then attach it.... or how ever you did it now....

**Comment by envikowaty** [comment]
So ehh... now I need to write a story...


I’m a officer working on the vessel in a middle of North Sea where weather is not great as the internet... if I connect the wifi ship signal to the laptop I have a lot of things blocked; but if I connect the wifi to my phone and and VPN app I have little bit more options to do...

**Comment by Tensuko** [comment]
I guess it is the same as in #3239
You can see the big orange GIANTS collision box when you press F5 ingame.

**Comment by envikowaty** [comment]
> I guess it is the same as in #3239
> You can see the big orange GIANTS collision box when you press F5 ingame.

Yeah that’s the same problem , it’s on every self driving sprayer
