### ISSUE TITLE
Silo Walzen (Funktion 10) Traktor verkeilt sich.

### ISSUE THREAD

**Issue by nick90A** [Courseplay/courseplay#6174]
Hallo,
bei mir läuft ebenfalls das Silo Walzen nicht durch.
In der Mitte klappt alles wunderbar, nur an den Randbahen stößt er immer gegen die Bunker-Wände.
Verschiedene Einstellungen & Fahrzeuge habe ich bereits getestet, sowie verscheiden weit entfernte Stop Punkte (bis zu 3 Fahrzeuglängen aus dem Bunker) immer das selbe ergebnis.

![Bunker](https://user-images.githubusercontent.com/70608026/95016259-299a6000-0652-11eb-8be4-2a47a71b5793.png)
![Einstellungen 1](https://user-images.githubusercontent.com/70608026/95016292-6d8d6500-0652-11eb-9cca-4ae57fd4582c.png)
![Einstellungen 2](https://user-images.githubusercontent.com/70608026/95016312-99104f80-0652-11eb-8323-5660bd713c19.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5323244/log.txt)

Ich vermute mal das ich einfach irgendwas falsch eingestellt oder übersehen habe ... aber ich finde nirgendswo eine Löseung im Internet & habe selbst alles ausprobiert ...

**Comment by 3lronMcBong** [comment]
Versuche mal die Schildbreite zu erhöhen, irgendwie passt es nicht zu der tatsächlichen Schildbreite.
Habe bei meinem 5m Schild knappe 11m drin, so funktioniert es.
Müsste bei der Walze ähnlich sein.

**Comment by Tensuko** [comment]
Dein Kurs sieht auch Käse aus.... Der Wartepunkt muss natürlich nicht gerade zu erreichen sein, aber der weg zum bunker und dann zum stop das ist irgendwie mist.
![bunker](https://user-images.githubusercontent.com/27344744/95017935-813dc900-065c-11eb-917e-0ab5fb38aef3.png)

**Comment by nick90A** [comment]
Ich habe jetzt beides ausprobiert, ohne erfolg. Bin bis 20m breite gegangen, schrittweise.
Der Kurs ist jetzt so richtig oder?

![Bunker 2](https://user-images.githubusercontent.com/70608026/95019393-66238700-0665-11eb-9ad3-13826c7041d9.png)
![Bunker 3](https://user-images.githubusercontent.com/70608026/95019392-66238700-0665-11eb-88b7-06f3049d21a2.png)
![Bunker 4](https://user-images.githubusercontent.com/70608026/95019403-73d90c80-0665-11eb-805d-f040c9af5ddd.png)

**Comment by nick90A** [comment]
Mir kommt es eher so vor als ob die Bunker-Breite falsch ist & bis zur Mitte der Wand geht (Laternen). 
Das ist der BGA Bunker der Oberthal Map.
kann man die Breite irgendwie überprüfen bzw. ändern?

**Comment by Tensuko** [comment]
Kannst dir sonst mit Debugchannel 10 mal anzeigen lassen wo er hin will und welchen Bereich er überprüft.

**Comment by nick90A** [comment]
Wie geht das denn? bin grade erst von der Playstation zum PC gewechselt ...

**Comment by Tensuko** [comment]
Im HUD bei Settings die 10 grün machen.

**Comment by nick90A** [comment]
Ja der bereich den er überprüft ist zu Breit. d.h. nun das Problem liegt am Bunker oder an Corseplay?

![Bunker 5](https://user-images.githubusercontent.com/70608026/95023529-da6a2480-067d-11eb-951c-5de421dcfd4a.png)

**Comment by Tensuko** [comment]
Sieht nach Bunkerproblem aus.... weis nicht ob wir da was machen können...

**Comment by nick90A** [comment]
okay ... mich wundert es nur das ich auf der Felsbrunn dasselbe Problem hatte & dass dann das Problem nicht bekannt ist ...

aber schonmal Danke :)

**Comment by psoppa** [comment]
Also die Map ist schonmal die Oberthal und die BGA ist die Standard BGA der Felsbrunnen. Von daher wird das ein Giants ding sein. Ich versuche mal die BGA dahin zu ändern das der Bunkerbereich kleiner wird und teste das dann mal.

**Comment by nick90A** [comment]
Ich hab das heute auch versucht, hab erstmal nur eine Seite angepasst aber die passt dafür jetzt auch. 
Er fährt schon nicht mehr so doll auf die Wand zu, trotzdem bleibt er noch so grade hängen ... aber ich denke das ist jetzt eher einstellungssache ... hab die breite daher bewusst auf 11m gemacht.

![Bunker 6](https://user-images.githubusercontent.com/70608026/95082780-df7db100-071b-11eb-8b1c-89a5a0325f6a.png)

**Comment by nick90A** [comment]
Ich habe es den bereich selber kleiner bekommen. trotzdem bleibt man immer an der Mauer hängen, obwohl es schon besser aussieht. Damit ist meiner Meinung nach das Problem von Bunker eite her behoben.
Nunhabe ich den bereich so klein gemacht, dass er da nicht mehr hängen bleibt. 

Jedoch verstehe ich nicht mit welcher breite Courseplay rechnet. 
-Ich habe verschiedene Trecker getestet, die Treckerbreite (äußeres Reifenmaß) ist es damit nicht.
-Die Anbaugeräte-breite ist es auch nicht egal ob ein- oder auseinander geklappte Walze (siehe Bild).
-Die einstellbare breite (Schildbreite) ist es auch nicht, jedenfalls fährt er immer gleich egal ob 2 m oder 15 m eingestellt sind.

![Bereich Klein](https://user-images.githubusercontent.com/70608026/95108085-13b49a00-073b-11eb-8b37-0bb908b768f5.png)

**Comment by Tensuko** [comment]
Könnte sein, dass die Breite nicht richtig ist, muss ich bei gelegenheit mal ausprobieren...

**Comment by MilanCZ93** [comment]
Hi,
I have same problem as Nick90A mode 10, crashing to walls and doesn´t react to width change.
Any help Thanks Milan

**Comment by Yasp0** [comment]
I am having the same issues. The first run is ok, because  then the tractor runs through the middle of the bunker. But after that it runs into the wall. Tried multiple default ingame bunkers.

Adjusting the shield width has no impact.

**Comment by xerion8300** [comment]
Bei mir funktioniert es auch nicht. Auch wenn ich das Schild auf 12m mache  Weiter weg vom Silo usw.
![fsScreen_2020_10_11_16_55_44](https://user-images.githubusercontent.com/25564472/95762858-92b35080-0cae-11eb-9108-1f78831a61c3.png)
![fsScreen_2020_10_11_16_56_16](https://user-images.githubusercontent.com/25564472/95762880-9b0b8b80-0cae-11eb-81a2-67f7ff34c1db.png)

**Comment by Tensuko** [comment]
Breitenberechnung scheint da nicht zu klappen für Verteilen und Verdichten...

**Comment by Bond109** [comment]
I am also having these issues with the width adjustment not having any effect in mode 10. Has this setting been disabled for some reason?

**Comment by Tensuko** [comment]
It is simply not working right now.

**Comment by Bond109** [comment]
Thank you for the quick reply. Is there anything i can do to help fix this issue?

**Comment by Baker79** [comment]
Kann ich alles so bestätigen. Bleibt erstmal nur selber machen. wird bestimmt behoben

**Comment by Oberlump** [comment]
Das selbe auch bei der kleinen/schmalen BGA auf der Südhemmern Map, aber erst seit 2-3 CP Versionen so. Vorher klappte es mit dem Kurs noch (er eckte zwar auch vorher schon stark an, aber seit 2-3 CP Versionen verkeilt er sich komplett und egal was man einstellt bei der Breite des Schildes/Walze, es ändert nichts.).

**Comment by nick90A** [comment]
Gibt es Mittlerweile neue Erkenntnisse? ich bin wie hier schon beschrieben zur Version v6.02.00054 zurück gekehrt, da funktioniert es ... in der Folge Version wurde übrigens auch was an dem Modus 10 geändert. 

Wenn ich mir die neusten Fehlermeldungen anschaue haben sehr viele dieses Problem.

**Comment by Tensuko** [comment]
Nein gibt es noch nicht. Wir haben ja nicht die Zeit um uns um alles gleichzeitig zu kümmern.

**Comment by Martin190606** [comment]
> Hallo,
> bei mir läuft ebenfalls das Silo Walzen nicht durch.
> In der Mitte klappt alles wunderbar, nur an den Randbahen stößt er immer gegen die Bunker-Wände.
> Verschiedene Einstellungen & Fahrzeuge habe ich bereits getestet, sowie verscheiden weit entfernte Stop Punkte (bis zu 3 Fahrzeuglängen aus dem Bunker) immer das selbe ergebnis.
> 
> ![Bunker](https://user-images.githubusercontent.com/70608026/95016259-299a6000-0652-11eb-8be4-2a47a71b5793.png)
> ![Einstellungen 1](https://user-images.githubusercontent.com/70608026/95016292-6d8d6500-0652-11eb-9cca-4ae57fd4582c.png)
> ![Einstellungen 2](https://user-images.githubusercontent.com/70608026/95016312-99104f80-0652-11eb-8323-5660bd713c19.png)
> [log.txt](https://github.com/Courseplay/courseplay/files/5323244/log.txt)
> 
> Ich vermute mal das ich einfach irgendwas falsch eingestellt oder übersehen habe ... aber ich finde nirgendswo eine Löseung im Internet & habe selbst alles ausprobiert ...

**Comment by Tensuko** [comment]
Sollte mit der .00015 besser klappen, Schildbreite wird benutzt und es wird parallel zur Wand gefahren.
Bitte ausprobieren und melden, danke.

**Comment by xerion8300** [comment]
So habe mal getestet Schildbreite geht, doch ganz funktioniert es nicht mit dem Schieben wenn ich umstelle auf abladen durchfahren schalte.

https://www.youtube.com/watch?v=1yN9st3Ca3Y
https://www.youtube.com/watch?v=yANKvuZ1wQ0

**Comment by Tensuko** [comment]
Das Verteilen und verdichten nicht geht wissen wir, da arbeiten wir noch dran.
Das mit dem einmal im Kreis drehen liegt am Kurs, wie der Endpunkt gesetzt wurde.
Wie das mit abladen durch läuft werden wir auch noch mal schauen, der ganze Mode müsste noch etwas bearbeitet werden daher abwarten... aber da sich der Traktor so nicht mehr verkeielt, ist dieses Issue erst einmal erledigt.

**Comment by xerion8300** [comment]
Ja passt, und Danke  ist schon mal ein großer Vorteil das er nicht mehr anstößt.
Danke für eure Bemühungen. Und das andere kommt auch noch.
