### ISSUE TITLE
Gerade am ersten Punkt anfahren

### ISSUE THREAD

**Issue by Daniel78-art** [Courseplay/courseplay#6175]
Hallo, 
wäre es möglich dass das Fahrzeug plus das Gerät gerade am 1. Punkt anfahrt?
Der Grund ist ich anfange den Feldreihen an.
![fsScreen_2020_10_04_16_48_05](https://user-images.githubusercontent.com/72348662/95019730-615fd280-0667-11eb-8b03-1831257bd2f4.png)
![fsScreen_2020_10_04_16_49_29](https://user-images.githubusercontent.com/72348662/95019734-645ac300-0667-11eb-8358-9c27c63ea950.png)
![fsScreen_2020_10_04_16_49_35](https://user-images.githubusercontent.com/72348662/95019736-6755b380-0667-11eb-82fd-3c91ace41dfe.png)
 Gruß Daniel

**Comment by Tensuko** [comment]
Tut er auch, er fängt nur vor dem Startpunkt an, aber da Tool kommt genau richtig am Start an wo es soll.
