### ISSUE TITLE
Issue with Offloading a Loading Wagon into Silage Bunker

### ISSUE THREAD

**Issue by testcommit** [Courseplay/courseplay#6176]
Trying to use CP mode 6 to collect grass off of cut field, and then dump it in silage bunker, which I've seen done before. Problem is, I set the collection course, attach the course that runs through the bunker to dump it, but when the loading wagon gets full, it doesn't continue on to the unloading course, it just stops. I've also tried just running the unloading course with an already full trailer, and unless I put that course in mode 1 (which in the combine course scenario wouldn't allow it to collect off the field), it will either stop the course saying the trailer is full, or just drive through the bunker silo without dumping anything

**Comment by Tensuko** [comment]
logfile, screenshot ?
MP/SP ?
I can guarantee you that it is working without any Problem, as I did that many many times the last days on my own savegame, so there is something wrong on your side...

**Comment by testcommit** [comment]
I have no doubt it's something on my end, just really cannot figure out the issue, was hoping someone here could offer some suggestions haha. Its in single player, I'm grab some screenshots and the log once I'm back at my pc

**Comment by testcommit** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5325021/log.txt)
![combined route](https://user-images.githubusercontent.com/21369457/95036748-e2828e00-0696-11eb-94af-3e8555f3ab51.PNG)
![offload course](https://user-images.githubusercontent.com/21369457/95036749-e31b2480-0696-11eb-95ad-07c72bb0e7aa.PNG)
![stopped worker](https://user-images.githubusercontent.com/21369457/95036751-e31b2480-0696-11eb-859c-b04833acd8f7.PNG)

Here's the logfile and a few screenshots. Wasn't doing the "tool needs to be unloaded" thing this time for some reason, but it would jump to the offload course, start to drive it, then cancel the worker just before entering the bunker.

I have a decent bit of mods downloaded, but below are the ones that directly pertain to the operation:
Map: Green River 2019 (but also tried on Ravenport and was having the same types of problems)
Bunker: Lighted Bunker Silo (but also tried with the basegame placeable bunkers)
Tractor: JD 2020 Series - US (but also tried with basegame tractors)

Thanks again for the help, this mod is a gamechanger and makes this game so much more fun to play

**Comment by Tensuko** [comment]
Why did you place a Waitpoint inside the Bunker ?
You need a unload here point....

**Comment by testcommit** [comment]
Tried an unload point there too, it would consistently either not jump to the unload route, or drive the unload route without unloading at the unload point (have also had that problem either auger wagons offloading to trucks). Had seen other people get it to work successfully by using a wait point there instead.

**Comment by Tensuko** [comment]
Mode3 for auger wagon use waitpoint for overloading.
But you want to unload on the ground in the bunker so unload waypoint and it works just fine.

**Comment by testcommit** [comment]
Thanks for the clarification. I updated the unload path to have an unload waypoint instead of waitpoint, but it's still doing the same thing. I have gif of unload path running and kicking out helper at the same point, but it's too large to upload

**Comment by testcommit** [comment]
[
![updated route](https://user-images.githubusercontent.com/21369457/95131994-098b9f00-072d-11eb-888f-0447ace917f2.PNG)
](url)

Aplogies for the delay, busy day at work. Here's a screenshot of the updated unload path but same problem. Also have gif/mp4 of it running the path that I can't upload here due to size, if there is somewhere else you would like me to upload/share them let me know!

**Comment by Tensuko** [comment]
I would als make the way out more straight, before drive into corner, that might help too.

**Comment by Tensuko** [comment]
No Problem at all...
![fsScreen_2020_10_23_18_50_19](https://user-images.githubusercontent.com/27344744/97031462-a0938c00-1560-11eb-8b1a-bbd4734cb7d1.png)

**Comment by testcommit** [comment]
Hmm well ok then. Guess I'll have to try updating Courseplay and retrying with different equipment/bunker or something. Thanks anyway for the help
