### ISSUE TITLE
Abfahrer leert Silo nicht

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#6177]
Hallo 
Der Abfahrer soll im Modus (Beladung am Startpunkt) den Silo leer fahren, er hält aber nicht am Startpunkt an sondern er fährt durch
![Kartoffel](https://user-images.githubusercontent.com/47453761/95023910-fb337980-067f-11eb-89c9-03fd17f392d3.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5324052/log.txt)

**Comment by Tensuko** [comment]
Bild vom Kurs da wo er laden soll, so bringt es nicht viel...

**Comment by Tensuko** [comment]
Du musst diese Mod updaten:
(Version: 1.0.0.0) FS19_manureSystem

Außerdem diese Mod raus nehmen, da sie schon im GlobalCompany drin ist:
(Version: 1.2) FS19PlaceAnywhere

Auch wichtig:
Immer nur eine Map im mods Ordner!
