### ISSUE TITLE
CP 65 Claas Jaguar not recognizes

### ISSUE THREAD

**Issue by BR1991** [Courseplay/courseplay#6178]
Hi All,

I try to make silage off maiz. I have always used mode "Unload combine and unload at silo". I select the forager harverster claas jaguar (980) and the tractor automaticly drive to de claas. But whit the new version i can not select the claas jaguar. How can this be solved? My previos version was V6.01.00364.

BR1991

**Comment by Tensuko** [comment]
Read #5272 and Wiki page. It does work as I did it today. There is also a Video for it.

**Comment by Tensuko** [comment]
Closed due to inactivity.
