### ISSUE TITLE
Combine not acknowledged

### ISSUE THREAD

**Issue by KimGo** [Courseplay/courseplay#6179]
Using the JD S790 and trying to set up an overloader plan, the combine is not visible for the tractor (that is, it does not show up in CP to assign a tractor to, nor does a search on the field work) also, in the combine itself, the option to request a tractor is greyed out as is the self unload option for the combine. It is as though CP does not recognize this model as a combine at all.

**Comment by KimGo** [comment]
Eventually I found a solution, by manually emptying the combine into the overloader, the program came to life for both the tractor and the combine. All is now working as it should.

**Comment by Tensuko** [comment]
That is not a search on Field, it is a simple filter for the list.

Next time read #5272 and provide the needed information.
