### ISSUE TITLE
LUA call stack: dataS/scripts/misc/TreePlantManager.lua

### ISSUE THREAD

**Issue by Pioner912** [Courseplay/courseplay#6181]
Hallo zusammen, 

Heute trat ein neuer Fehler in verbindung mit Courseplay auf, siehe Log vielleicht auch noch ein paar Fehler mehr als der welcher im Titel steht. 

Was habe Ich gemacht: 
Gras Gesammelt per Ladewagen auf 2 unterschidelichen Feldern. 
mit AD Getreide Transportiert hier war ein Mod Tractor im Spiel 
auf einem Feld mit Dreschen geerntet mit AD abgefahren mit Schwader Stroh zusammen gelegt und mit Ballenpresse (Quaderballen) gesammelt. 

Mit einem LKW Wasser Transportiert ebenfalls mit AD    
Das Spiel ist beim Starten eines weitern LKW mit Autoloadanhänger welcher die Quaderballen sammeln sollte eingefrohren, als ich in der Console den Fehler nachschauen wollte sah ich den im Titel genannten welcher für mich ein neuer Fehler ist, falls ihr diesen schon einmal hattet bitte Closen.  

Karte NF- Marsch 
AD sowie Courseplay aktuelle Versionen 

 Schönen Montag euch :-)  

[log.txt](https://github.com/Courseplay/courseplay/files/5326289/log.txt)

**Comment by Tensuko** [comment]
Sieht mir nach einem Mod-Issue aus.
Autoload Anhänger werden von CP nicht unterstützt, außer welche, die mit dem Standart Script arbeiten.
Müssten die hier sein https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=147304&title=fs2019

**Comment by Pioner912** [comment]
Das kann schon sein meiner ist von Crower CZ dann werde ich umsteigen danke für den Tipp @Tensuko 

Kann ich den dann als "Feldarbeit" laufen lassen oder nur Kurs folgen?

**Comment by Tensuko** [comment]
Ja, weil er genau so wie die normalen richtigen Ballensammelwagen funktioniert mit Arbeitsstellung, Ablademodus, Abladen usw.
Musst du dir mal angucken, die sind echt gut. Und wie gesagt, selber schon benutzt und kenne auch jemanden der damit erfolgreich Ballen vom Feld gesammelt hat. Du musst nur einen Geräteversatz selber einstellen, dass er links oder rechts neben deinem Feldkurs fährt.

**Comment by Pioner912** [comment]
@Tensuko das mit dem Geräteversatz ist so richtig und habe ich auch immer so gemacht aber in früheren CP Versionen ging das mit dem Autoloader von Crower CZ auch! Habe auch schon 2 hintereinander gehabt da war es aber egal ob feldarbeitsmodus oder Kurs folgen.

**Comment by Tensuko** [comment]
Hmm dann kann ich dir so nicht sagen was es ist....

**Comment by Tensuko** [comment]
Es geht halt los mit:
2020-10-05 09:43 Error: Running LUA method 'update'.
2020-10-05 09:43 dataS/scripts/vehicles/Vehicle.lua(2920) : attempt to index a nil value

Dann:
2020-10-05 09:49 Error: Running LUA method 'mouseEvent'.
2020-10-05 09:49 C:/Users/manue/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/settings.lua:2732: attempt to index field 'currentHelper' (a nil value)

Dann die callstacks.... das kann von sosnt was kommen...

**Comment by Pioner912** [comment]
Würde es euch helfen wenn ich heraus finde bei welcher Courseplay Version das mit dem Autoloader noch ging oder sagt ihr das ist ein Fehler welcher nicht oben auf der Prioritätenliste steht? 

Dann würde ich beide Autoloader und CP-Version hier verlinken.

**Comment by Pioner912** [comment]
Also habe nochmal ein bisschen nachgeschaut und getestet 

Wenn ich AD deaktiviere und dann das Savegame starte und dann einen Kurs Lade und diesen als Feldarbeit mit Versatz etc. laufen lasse dann bekomme ich keinen Error Callstack oder Ähnliches. 

Wenn ich AD dann aber wieder aktiviere gibt es plötzlich auch keinen mehr 🤔 

Es scheint doch kein Mod Fehler zu sein.

Courseplay Version 064!

**Comment by Pioner912** [comment]
Hier die Videos welche ich gemacht habe im ersten sieht man keinen Fehler mehr!! 
Bitte bis zu ende schauen denn ich hatte vergessen den Autoloader anzuschalten. 
Mit AD
https://youtu.be/ZUr-xRTrr5w 

und einmal wieder ohne AD
https://youtu.be/G2WgbKuqtnI 

Ich bin allerdings wieder auf version 064 gewchselt da 65 mir andauern den Spielstand zerschossen hat.
