### ISSUE TITLE
Small issue with TriggerHandler.lua

### ISSUE THREAD

**Issue by alfalfa6945** [Courseplay/courseplay#6184]
There is a slight issue with the TriggerHandler.lua in the latest master (6.02.00065):

  In the setFillUnitIsFilling() overwrite, starting on line 893, there exists an issue that if the line is true and "trigger" is a nil value the code after this line will still run. In single player, the issue is made aware to the player by a fill sound from a fillTrigger (if exists) will not stop playing after the courseplay vehicle has filled up and left the trigger.

This issue can be witnessed, for example, by using default Giant's slurry equipment and driving a spread/refill course. When empty, the spreader will refill from a Kotte FRC (which has a fill sound) and upon finishing the refill and driving away, the Kotte FRC will continue to play its fill sound indefinitely.

**Comment by schwiti6190** [comment]
@alfalfa6945 thanks for the great help, if you like you can give my branch a shot as I tried to fix this one :)

**Comment by alfalfa6945** [comment]
Hi schwiti6190! Sorry about that, I should have tried your branch before reporting this issue, knowing that you're working on the triggerHandler (won't happen again!)

 Ok, after trying your changes using the setup described in the first post (Samson PGii35, Samson SBH4 36, Kotte FRC), there is one small issue on line 923:

TriggerHandler.lua:923: attempt to index field 'currentTrigger' (a boolean value)

What appears to be happening is that the equipment enters the FRC trigger normally, begins filling, and when finished filling the trigger is again "activated" once more time (at least) prior to the equipment driving off. It is at this point that spec.fillTrigger.currentTrigger has become a boolean value ("false" in this test), and thus the error.

Hope that helps!

**Comment by schwiti6190** [comment]
@alfalfa6945 should be fixed now on my branch thx alot for the great help :)

**Comment by alfalfa6945** [comment]
Thank you for the quick fix! But a bit of bad news... Testing the latest fix still has the original issue of the sound not stopping on the Kotte FRC upon the equipment finishing its refill and driving off. 

Out of curiosity, if "trigger" is a nil value in the setFillUnitIsFilling() overwite, would it break things to use the superFunc instead? For example (and only tested with the scenario described in this thread), I've instituted a check on line 909:

if trigger ~= nil and courseplay:isAIDriverActive(rootVehicle) then

This allows the overwite to make use of the "trigger" value while allowing the original (superFunc) function to handle the lack of the "trigger" value. While testing the setup described, I'm noticing that the setFillUnitIsFilling() overwite is being used when the equipment first enters the FRC trigger (of course), then the setFillUnitIsFilling() superFunc is used immediately after the equipment is done filling (it is at this point that the sound on the FRC is turned off), and the setFillUnitIsFilling() superFunc is called once again as the Samson equipment exits the FRC trigger. 

Granted, I have not followed the code to see what breaks by making the change I've described, but I hope it may help in your own troubleshooting!

**Comment by schwiti6190** [comment]
@alfalfa6945  ist dieses noch aktuell ?

**Comment by alfalfa6945** [comment]
@schwiti6190 after testing using the exact setup I described in my first post, you have corrected the issue. Thank you very much!

As a side note, in the past there were issues with regards to using a front mounted tank (slurry, mod) along with the setup described in my fist post. Those issues are gone as well, your triggerHandler seems to work flawlessly with a front mounted tank as well.
