### ISSUE TITLE
Tractor not unloading the bucket

### ISSUE THREAD

**Issue by pxxle** [Courseplay/courseplay#6185]
Here is the screenshot of the course
![fsScreen_2020_10_07_19_08_46](https://user-images.githubusercontent.com/72500686/95324347-2f05dd80-08d2-11eb-8144-a7ecbc7629ab.png)
The worker will fill the bucket but will not unload it.
here is the logfile attached
[log.txt](https://github.com/Courseplay/courseplay/files/5340208/log.txt)

**Comment by Tensuko** [comment]
#5998
