### ISSUE TITLE
Mode 2: Unable to cross the path of stationary combine

### ISSUE THREAD

**Issue by Jaiimez** [Courseplay/courseplay#6187]
Hey, Whenever pathfinder tries to cross infront of a stationary combine that's waiting to be unloaded, it gets stuck, almost asif there is a traffic conflict even though the two would not collide, see images. Both vehicles in these images are just sat stuck unable to move.
![Screenshot_1](https://user-images.githubusercontent.com/47074193/95382336-66c85180-08e1-11eb-943a-96dff6bbf5e9.png)

![Screenshot_2](https://user-images.githubusercontent.com/47074193/95382288-53b58180-08e1-11eb-8646-fb6d37237c59.png)

**Comment by Tensuko** [comment]
We know about that one.
It will create a traffic conflict.
Working on it already.

**Comment by Jaiimez** [comment]
> We know about that one.
> It will create a traffic conflict.
> Working on it already.

Is there a bypass to force it to ignore traffic conflicts until the fix it released or not?

**Comment by Tensuko** [comment]
Move it to a better position and start it at 'Unloading'.

**Comment by pvaiko** [comment]
#5987
