### ISSUE TITLE
Abfahrer lädt Rübenroder nicht ab

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#6188]
Moin
Wenn ich den Abfahrer im Modus (Abfahrer ab tanken und abfahren) eingestellt habe, lädt er den Mähdrescher ab und fährt dann auch ab, aber beim Rübenroder klappt es nicht, der Rübenroder ist voll wird aber vom Abfahrer nicht abgetankt. 
Was mache ich falsch ?
![Rüben roden](https://user-images.githubusercontent.com/47453761/95449373-f5ca7d80-0964-11eb-9a57-defe0e36aaec.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5347280/log.txt)

**Comment by Tensuko** [comment]
Kleiner Hinweis am Rande: Raus damit, weil ist in GC enthalten.
Error: Invalid mod name 'FS19PlaceAnywhere-master'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

Ansonsten: Situation mit debugchannel 4 7 12 und 14 nachstellen und die log Datei dann anhängen (wie oben auch).
Voll ist er auf deinem Bild ja aber nicht.... Der Abfahrer wird gestartet wenn die eingestellten % erreicht werden, oder wenn du 'Abfahrer starten' anklickst (ich meine das sollte funktionieren).

Das ist doch der Mod Roder für MultiFruit oder ?
Ich meine ich habe ein ähnliches Problem bei mir gemerkt, hab aber noch nicht weiter nachgeforscht.

**Comment by Tensuko** [comment]
Da keine Info und logfiles kommen mache ich hier zu.
Vor wenigen Tagen den Ropa Multifruit Roder benutzt und hat wunderbar geklappt....
