### ISSUE TITLE
Hedges 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#6190]
Hello not really an issue but on the Holme wold map with the hedges surrounding the fields is there an option to help avoid them I want to use the turn feature so it don’t round the corner but it’s just driving into them any help appreciated

**Comment by Tensuko** [comment]
Screenshots might help.

**Comment by GeorgeEarslight** [comment]
@Tensuko I'm also playing on that map at the moment.

The fields have very small headlands and hedges with collision (you can see with F5).
When generating courses with _Turn_ option, the vehicle hits the hedge when backing.
This is because the field is not exactly rectangular with right angles, so it backs up on an angle.
I'll add a screenshot when I get home.

**Comment by Tensuko** [comment]
Then we can't do much about it.
If we change the bahavior the next issue will be something like 'CP doesn't work clear enough' or something like that.
The Only chanze I see here is to make round turns and increase the overlap so you have less missed part in the turns.

**Comment by matty2123** [comment]
Shame it’s a nice map but not a courseplay friendly map mine is hitting the hedge going forward too

Sent from my iPhone

On 9 Oct 2020, at 11:07, Tensuko <notifications@github.com> wrote:

﻿

Then we can't do much about it.
If we change the bahavior the next issue will be something like 'CP doesn't work clear enough' or something like that.
The Only chanze I see here is to make round turns and increase the overlap so you have less missed part in the turns.

**Comment by matty2123** [comment]
I watched on YouTube a video with a farmer he went down the headland waited till the weight touched the fence reversed backwards on to unploughed land and went back up like that so technically no hit the hedge https://youtu.be/6xzb9aj8LV8 video of it

Sent from my iPhone

On 9 Oct 2020, at 11:56, matthew knowles <matty.knowles@hotmail.co.uk> wrote:

﻿ Shame it’s a nice map but not a courseplay friendly map mine is hitting the hedge going forward too

Sent from my iPhone

On 9 Oct 2020, at 11:07, Tensuko <notifications@github.com> wrote:

﻿

Then we can't do much about it.
If we change the bahavior the next issue will be something like 'CP doesn't work clear enough' or something like that.
The Only chanze I see here is to make round turns and increase the overlap so you have less missed part in the turns.

**Comment by Tensuko** [comment]
at what min ?

**Comment by matty2123** [comment]
4.53

Sent from my iPhone

On 9 Oct 2020, at 17:15, Tensuko <notifications@github.com> wrote:

﻿

at what min ?

**Comment by Tensuko** [comment]
That only works for this type of plough, no pulled one....

**Comment by GeorgeEarslight** [comment]
Here's the course. Just adding it for reference.
I've tried AI, pathfinding, no pathfinding (3 cases) and all generate the same turn.
It seems to be very hard to generate a proper reversing maneuver considering the field angle, implement markers, etc.
It could be easier to check collision (the hedges do have collision boxes) or just change direction when it detects sliding.

![path_en](https://user-images.githubusercontent.com/30686125/95610730-6c50a380-0a69-11eb-8972-812172ba442e.png)

**Comment by matty2123** [comment]
I’m not using a pulled one

Sent from my iPhone

On 9 Oct 2020, at 18:00, GeorgeEarslight <notifications@github.com> wrote:

﻿

Here's the course. Just adding it for reference.
I've tried AI, pathfinding, no pathfinding (3 cases) and all generate the same turn.
It seems to be very hard to generate a proper reversing maneuver considering the field angle, implement markers, etc.
It could be easier to check collision (the hedges do have collision boxes) or just change direction when it detects sliding.

[path_en]<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F30686125%2F95610730-6c50a380-0a69-11eb-8972-812172ba442e.png&data=02%7C01%7C%7C6bf91afaff244194086708d86c74c4d3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637378596049683096&sdata=rxDAWJj%2BMaxUa7F7uLHWSEHJ35YD3f3XL1%2BckHlq0uY%3D&reserved=0>

**Comment by Tensuko** [comment]
Thats the Problem @GeorgeEarslight 
What could we adjust there ? If we stop them more early, you will have an uncovered Edge on other Fields and we get again Issues about this.
Not sure if we can make a reverse parallel towars the Field Border....

**Comment by GeorgeEarslight** [comment]
@Tensuko the problem with the parallel reverse (if that's possible) is that the other side is not at a 90deg angle, so in the general case, you might miss some part of the field or hit another edge, depending on the angle, as you already mentioned.

Personally, I just take a look at the machines and help them when they need it. 
Even the 2020 John Deeres don't have totally autonomous maneuvering, I don't understand why people expect CP to do everything.

**Comment by matty2123** [comment]
I know it’s never gonna be perfect like it’s it’s reversing Shame it couldn’t have a time then it goes forward automatically so it knows it’s in a problem

Sent from my iPhone

On 9 Oct 2020, at 18:28, GeorgeEarslight <notifications@github.com> wrote:

﻿

@Tensuko<https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTensuko&data=02%7C01%7C%7C19755e21a0b84e10c26d08d86c78ccd0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637378613380019396&sdata=u6TXv9Xy0o551CO4SMXdnoUsrFLWMuyv10%2BaxxAHtD8%3D&reserved=0> the problem with the parallel reverse (if that's possible) is that the other side is not at a 90deg angle, so in the general case, you might miss some part of the field or hit another edge, depending on the angle, as you already mentioned.

Personally, I just take a look at the machines and help them when they need it.
Even the 2020 John Deeres don't have totally autonomous maneuvering, I don't understand why people expect CP to do everything.
