### ISSUE TITLE
MP Server Issue: no one can join after starting a Mode 1 route

### ISSUE THREAD

**Issue by Aiden-Lilley** [Courseplay/courseplay#6192]
Any players trying to join the server become stuck at loading after a tractor/trailer with a Mode 1 route has been started with no FillType (Players using mode 1 as a generic field to silo route or just forgetting).

This may be due to player error, but if anyone forgets it breaks the server for others, and if the player logs out, the server has to be restarted.

Steps to reproduce:
- log into the server
- create any Mode 1 route without setting a FillType
- leave server
- attempt to rejoin

Seen a few different places this causes errors, was originally
/FS19_Courseplay/settings.lua:2895:attempt to compare number with nil 
( This occasionally happened even when there was a FillType set)
but as of the latest patch the trace error has moved to
/FS19_Courseplay/CpManager.lua:474: table index is nil

Version: v6.02.00066
Map: Ravenport
serve is 100% vanilla other than CP
there are Mods on the client but not used

attached Client and Server Log
[Client log.txt](https://github.com/Courseplay/courseplay/files/5354319/Client.log.txt)
[Server Log.txt](https://github.com/Courseplay/courseplay/files/5354315/Server.Log.txt)

**Comment by Tensuko** [comment]
2020-10-09 11:15 Error: Running LUA method 'packetReceived'.
2020-10-09 11:15 C:/Users/Lilolil31/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CpManager.lua:474: table index is nil

**Comment by Aiden-Lilley** [comment]
applying this fix causes a different error
2020-10-09 13:06 Error: Running LUA method 'packetReceived'.
2020-10-09 13:06 C:/Users/Lilolil31/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/settings.lua:2732: attempt to index field 'currentHelper' (a nil value)

log:
[log.txt](https://github.com/Courseplay/courseplay/files/5354824/log.txt)

**Comment by schwiti6190** [comment]
@Aiden-Lilley thanks alot for your test, might be fixed now :)

**Comment by Aiden-Lilley** [comment]
@schwiti6190 Awesome! Yeah, that's fixed it! thank's man for such a quick fix :)
