### ISSUE TITLE
Server läd mit CP und CR10.90 Extended Hud Savegame nicht mehr

### ISSUE THREAD

**Issue by BLACKOUT-Z0ck3R** [Courseplay/courseplay#6194]
Hallo.
Unser Server läd das Savegame nicht mehr, wenn ich den gesagten Drescher gekauft habe.... woran könnt das liegen?
Wenn der Drescher gekauft ist und ich CP mit lade kommt folgender Fehler:

2020-10-09 18:07 Error: Running LUA method 'loadSharedI3DFileFinished'.
2020-10-09 18:07 d:/servers/service15216/home/games/FarmingSimulator19/mods/FS19_Courseplay/toolManager.lua:189: attempt to compare number with nil

Wenn ich CP entlade, oder den Drescher über die Items auskommentiere geht alles wieder

**Comment by Tensuko** [comment]
Am Drescher ?

**Comment by BLACKOUT-Z0ck3R** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5356759/log.txt)
Server Log
dass das am Drescher liegen wird, ist mir klar... aber an was am Drescher?

**Comment by BLACKOUT-Z0ck3R** [comment]
der selbe Fehler kommt auch, wenn man im SP sich den Drescher im Shop angucken möchte...

**Comment by BLACKOUT-Z0ck3R** [comment]
Drescher : https://sharemods.com/djgak3a7hcpf/FS19_CR1090_extendedhud.zip.html
