### ISSUE TITLE
Mode4 not responding to turn settings

### ISSUE THREAD

**Issue by enderwiggin07** [Courseplay/courseplay#6196]
On this field I have established a headland about 60m.  Also have turned "turn on field" off to ensure no backing up with air cart system.  The auto turn radius calculated an 18m turn, which was unsatisfactory and I changed to 30m radius to make a nice smooth turn on my large headland into the next row with ~32m implement.   

In reality no matter if I set the turn radius to auto(18), manual(30), or even manual(50) the AI does exactly the same turn very sharp and ugly and missing area.  "Turn on field" off and on also makes no difference.  I can replicate this problem with sprayers but have screenshots for seeding.   This is a problem since version 57.  

![20201009221522_1](https://user-images.githubusercontent.com/50051834/95644574-2c93b700-0a7d-11eb-975f-fb90f50b4285.jpg)
![20201009221531_1](https://user-images.githubusercontent.com/50051834/95644575-2dc4e400-0a7d-11eb-8859-f65a1598dd15.jpg)
![20201009221542_1](https://user-images.githubusercontent.com/50051834/95644576-2e5d7a80-0a7d-11eb-99b1-dd5435162d90.jpg)

**Comment by Tensuko** [comment]
Depends on type of turn.
This is a wide rurn and is not working like it should right now. See #6129

**Comment by enderwiggin07** [comment]
I just want to make sure that it's clear that this is a new issue since version 57, I saw that marked as enhancement but it's definitely a bug introduced since that version.  I saw that #6129 and decided to make my own to demonstrate the problem can be reproduced even with generous headlands
