### ISSUE TITLE
flashing light

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#6197]
While using mode 1 I noticed this small purely aesthetic defect: even if the "flashing lights on the road" setting is active, the tractor never turns them on. Did I do something wrong in planning the route?

[Farming Simulator 19 2020-10-10 10-27-38.zip](https://github.com/Courseplay/courseplay/files/5358661/Farming.Simulator.19.2020-10-10.10-27-38.zip)

[log.txt](https://github.com/Courseplay/courseplay/files/5358659/log.txt)

**Comment by Tensuko** [comment]
RUL Setting does work, how did  you set it and whats the actual problem ?

**Comment by 0Pietro20** [comment]
In these days I will do a test again and, if it does not work, I will post photos and logs

**Comment by Tensuko** [comment]
Not sure how this is supposed to work correctly...
Try version 6.03.00060 or higher and report pls.

**Comment by 0Pietro20** [comment]
Okay, as soon as I have a second free I'll try and give feedback

**Comment by 0Pietro20** [comment]
Now it works, thank you very much

**Comment by Tensuko** [comment]
Thanks for your feedback.
