### ISSUE TITLE
Interface refuses to recognize any combine when in mode 2

### ISSUE THREAD

**Issue by daveyboy94** [Courseplay/courseplay#6198]
I'm not sure if anyone else is having this issue, but my Courseplay interface refuses to recognize any combines for off-loading. I go to the combine selection screen only to be met with a blank roster. Really strange. I never saw this in the older versions.

**Comment by Tensuko** [comment]
Change mode once maybe it shows up.

**Comment by CHARGERMAN2016** [comment]
Im having the same annoying issue. Please help

**Comment by Tensuko** [comment]
> Change mode once maybe it shows up.

**Comment by daveyboy94** [comment]
> Change mode once maybe it shows up.
 I was finally able to deduce what was really going on through trial and error. For some reason, this Courseplay version only registers combines and trailers bought from the store. If you start on "New Farmer" mode with pre-existing vehicles, Courseplay simply doesn't scan them. However, after I sold my combine and bought another one it immediately appeared for selection. This isn't an issue of simply switching back and forth between modes as that does nothing. This is highly detrimental to people who like to play on that mode. It means that your starting combine and trailer are useless for creating courses. The Courseplay of old never did this. It must be something in the code that changes the way vehicles are scanned.

**Comment by Tensuko** [comment]
Even when you save game and restart the savegame ? Still no active in CP ?

**Comment by GeorgeEarslight** [comment]
-Enable debug channel 4
-Go to combine change mode to Type: transfer, then to Type: fieldwork
-Go to tractor with trailer, change mode to Type: transfer, then to Type: Combi
If the combine doesn't show on the list, post log.

**Comment by Tensuko** [comment]
Closed due to inactivity, had no Problems with Combine select screen.
Only Combine that is already bought when start a new savegame.
Might have an update soon that fix those Issues.
