### ISSUE TITLE
Mode 3 Auger Wagon not overloading.

### ISSUE THREAD

**Issue by Jaiimez** [Courseplay/courseplay#6199]
Hey I am unsure if i've set this up incorrectly or if it is an issue, but i've got the Ninja Auger Wagon, and a mode 3 route that has it drive alongside a semi trailer, I've tried setting the route in the picture up with it set as a wait point and unload point, but on both it just pauses on the spot then continues on, rather than completely unloading.

Am I doing this wrong?

Is there a way to change the wait point so it forces a wait for x seconds?
![Screenshot_1](https://user-images.githubusercontent.com/47074193/95662663-8bfecf00-0b30-11eb-9386-fc8838f95905.png)

**Comment by Tensuko** [comment]
Waitpoint, not  'unload here'...

**Comment by Jaiimez** [comment]
> Waitpoint, not 'unload here'...

Yeah I needed to change the start at percentage, I figured it out, thanks for your help though.
