### ISSUE TITLE
Auger Wagons

### ISSUE THREAD

**Issue by jusceliop** [Courseplay/courseplay#6200]
In FS17, the bazooka worked, turn this option back on fs19
![bazuca](https://user-images.githubusercontent.com/16738224/95674304-aa42ea00-0b85-11eb-9111-bdda62b12cfe.jpg)

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ

**Comment by jusceliop** [comment]
I did not understand

**Comment by Tensuko** [comment]
Read, it is already in CP for FS19... https://github.com/Courseplay/courseplay/releases

**Comment by jusceliop** [comment]
When we start the bazooka, the PC freezes

**Comment by Tensuko** [comment]
We would need a logfile with debugchannel 4 7 12 and 14 active.
I don't think it is freeze, it is just the Pathfinder working on finding a way to the Combine.

**Comment by Tensuko** [comment]
Closed due to inactvity, no Problem at all.
