### ISSUE TITLE
Connecting turn has wrong alignment

### ISSUE THREAD

**Issue by GeorgeEarslight** [Courseplay/courseplay#6201]
Seems that the calculation for the row connecting turn is set at 2 waypoints forward.
The course is 12m wide, 2 headlands, skip 1 row.
Pathfinding activated.

![image](https://user-images.githubusercontent.com/30686125/95676379-5e646500-0bc6-11eb-96b3-e13c0325aa76.png)

**Comment by Tensuko** [comment]
#6129 :)

**Comment by GeorgeEarslight** [comment]
Sorry!

**Comment by Tensuko** [comment]
No Problem budddy! :)
