### ISSUE TITLE
Drescherverband funktioniert auf Dedi Server nicht

### ISSUE THREAD

**Issue by BLACKOUT-Z0ck3R** [Courseplay/courseplay#6203]
Hallo
leider funktioniert der Drescherverband auf einem Dedi Server nicht... die Drescher fahren mittig der Linie nach, anstatt links und rechts davon
LG

**Comment by Tensuko** [comment]
Kein logfile, nicht geschaut ob ein Issue existiert und Info das hat mit drescherverbamd nichts zu tun, das ist multitool mit laneoffset was nicht geht, fix ist auf dem weg weilbgestern fertig geworden.
