### ISSUE TITLE
Frage: Wird es wieder einen Standalone Kurs Generator geben?

### ISSUE THREAD

**Issue by SeriouZ12** [Courseplay/courseplay#6207]
Frage steht oben. Ich fände das sehr gut, da bei großen verwinkelten Feldern das Generieren mit Inseln mal länger dauert und ich das Gefühl habe der Generator kann nicht die volle Leistung vom Rechner nutzen.

**Comment by pvaiko** [comment]
Den gibt es eigentlich immer noch (https://github.com/pvaiko/course-generator), ich benutze ihn für die Entwicklung/Bug Fixing, ist aber nicht mehr gepflegt, und unsauber.

Bräuchte ein wenig Aufräumung um es wieder für alle benutzerfreundlich zu machen.

**Comment by SeriouZ12** [comment]
Ist der denn auch auf dem aktuellen Stand was Möglichkeiten angeht? Oder kann man den Course Generator Ordner aus der aktuellen Version rauskopieren?

**Comment by pvaiko** [comment]
Der verwendet den aktuellen CP Code, also, ja, auf den aktuellen Stand, du musst also courseplay repo unter course-generator clonen:

"Standalone mode requires that you embed the Courseplay repository under the courseplay folder."

**Comment by Tensuko** [comment]
Gibt es noch was zu klären oder weitere fragen ?

**Comment by SeriouZ12** [comment]
Nein vielen Dank!
