### ISSUE TITLE
getCurrentHelper LUA error with REA mod

### ISSUE THREAD

**Issue by mrPassion78** [Courseplay/courseplay#6209]
hi guys, first thnx for making the mod, and working on it so hard.

I found an issue with CP and REA..
i`ll add 2 log files 
1> log essentails.txt is with all the script i really want in the game, and on custom map
2> log.txt is the felsbrunn basegame map with only claasDLC / CP6 version 6.02.00066 and REA version 1.3.1.0
the error occurs when the implement was lowered and/or lifted for turning the plow.

I tried a rollback of CP and the problem stayed the same.
i used only the base valtra and base plow in the log.txt no mods

in both log files you will see that the problem only reoccurs when Rea is active.
if you need more info or prints in the log, just tell me witch debug to turn on, and i`ll report back here.

thnx in advance Pascal

*edit* when this error occurs, it disables the use of the direction shift in the VCA mod, so i cant backup or go forward anymore without exit the game and restart.
i.e. the tractor was plowing and throws the LUA error, and on the other side of the map is a telehandler that i use via VCA, and i lost the forward/backward function on this one.

[log.txt](https://github.com/Courseplay/courseplay/files/5363827/log.txt)
[log essentials.txt](https://github.com/Courseplay/courseplay/files/5363828/log.essentials.txt)

**Comment by Tensuko** [comment]
No Idea what we can do about that....

@pvaiko any Idea ? I think this is a job for REA Team ?
2020-10-12 09:59 Error: Running LUA method 'update'.
2020-10-12 09:59 dataS/scripts/vehicles/Vehicle.lua(2920) : attempt to call method 'getCurrentHelper' (a nil value)

**Comment by pvaiko** [comment]
That is not even a CP script, that is standard Giant code.
