### ISSUE TITLE
game crash CP issue

### ISSUE THREAD

**Issue by answermanitou** [Courseplay/courseplay#6217]
hello
Just now loaded new version of CP
When i disconnect wagon from tractor the game is crashed down
Before it I use CP ver 44 and receive strange bug. When i disconnect wagon and then attach lime spreader I delete filltype in settings seeds than i add new fill type - lime and game imidiatly crash. After this moment I install new version

[log.txt](https://github.com/Courseplay/courseplay/files/5372284/log.txt)

**Comment by Tensuko** [comment]
#6164
