### ISSUE TITLE
Abfahrer für selbstständige Drescher- und Häckslerfahrer

### ISSUE THREAD

**Issue by KingNoerb** [Courseplay/courseplay#6218]
Hallo,
ich kann mich nicht mehr so richtig an den CP im LS 17 erinnern, doch glaube ich das es dort möglich war, selbstständig einen Drescher zu fahren und zu ernten, der CP gesteuerte Abfahrer kam zum abbunkern und nach erreichen des eingestellten Füllstandes fuhr dieser die Ernte ohne Probleme ins Silo.? Bin mir aber nicht mehr ganz sicher.

Wenn ich aber richtig liege, wird das in den zukünftigen Versionen wieder möglich sein?
Oder funktioniert der Abfahrer nur wenn ein Helfer den Drescher fährt?

Gruß

**Comment by Tensuko** [comment]
Im Moment nur wenn CP den Drescher fährt, an einer Lösung wird gearbeitet.
