### ISSUE TITLE
CP issue 

### ISSUE THREAD

**Issue by answermanitou** [Courseplay/courseplay#6220]
hello
when launching for plowing two CP helpers the game is freeze after second AI started
[log.txt](https://github.com/Courseplay/courseplay/files/5380034/log.txt)

**Comment by answermanitou** [comment]
just again
but simle I attach for single tractor a plow. open CP hud. When I select different works> game crash
see new log bellow
[log.txt](https://github.com/Courseplay/courseplay/files/5380260/log.txt)

**Comment by Tensuko** [comment]
Pics of course and somehow you discripe 2 different Errors....
We need more details and step by step and I can tell you I used 2 plows already and I also changed mode, so what are you doing, what tools whats going on etc etc.....

Beside that your Seasons produce a Callstack already before anything with CP happens!

(Version: 1.3) FS19PlaceAnywhere is in GC so throw that single mod out...

**Comment by answermanitou** [comment]
I dont no. in this moment all already worked.
I add few screenshots 
2 CP helpers on f27-28 is working properly
next 2 helpers with xerion should be work on f26
in my previous post second log contains error when i attach the plow to one of xerion and than in CP hud select Different works
I try to play and looking for malfunktion if it cause i give info
pls dont close this for a while
![fsScreen_2020_10_14_23_02_25](https://user-images.githubusercontent.com/64743178/96039902-136e7a00-0e72-11eb-974b-07172dccf55e.png)
![fsScreen_2020_10_14_23_00_39](https://user-images.githubusercontent.com/64743178/96039907-15d0d400-0e72-11eb-81d5-596f72e6bcdc.png)

**Comment by Tensuko** [comment]
So what is this Issue about now ?

**Comment by Tensuko** [comment]
Closed due to inactivity
