### ISSUE TITLE
Pathfinder not using headland even though initially pathing through it

### ISSUE THREAD

**Issue by GeorgeEarslight** [Courseplay/courseplay#6221]
The pathfinder is using `HybridAStarWithPathInTheMiddle` and has already found a `headlandPath` with 7 points, but for some reason decides to follow a new path.
The other lane transitions on this course generate and follow headland connections, as preferred. 

![turn](https://user-images.githubusercontent.com/30686125/96030230-6b9e7f80-0e64-11eb-9324-791326b7785e.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5380165/log.txt)

**Comment by GeorgeEarslight** [comment]
@Tensuko @pvaiko 
Fixed with 6.02.00067

**Comment by Tensuko** [comment]
@pvaiko forgot in the changelog or is this accidently fixed ?
