### ISSUE TITLE
Mode 2/3 small adjustment

### ISSUE THREAD

**Issue by polosubtil** [Courseplay/courseplay#6222]
Hey guys,

Just coming back to you about a last twick for mode 2/3 I found playing a big map with small equipment.
I guess this is related to an issue you solved a month ago (#6065). You did great on improving unloader behavior regarding the combine when reaching the end of a row => amazing work. With that + land mode, you get a great harvest (as IRL) almost without any "issues".

One thing could also get this twick I think => When unloading a full combine on the first headland (not moving) or in the first row of a land, if the unloader gets full before the combine was able to get fully empty, it doesn't reverse to give the combine some space to get back to work. And after that, it just go through the crop as it doesn't really have a choice.

So my point would be:
- if possible, reverse when full to give the combine some space (as you did for the end of the row). That's really the main thing.
- And in a perfect world (**but absolutely not essential**), the unloader could reverse all the way down the 1st row (probably a bit crazy but that's how we do IRL) or just go through the crop to turn around and then come back in the 1st row already harvested.

My log with a few channels on in the first row of a land (I have saved my game right before it so I can reproduce, I might be able to find a backup somewhere with a first headland but it could take a while
[log.txt](https://github.com/Courseplay/courseplay/files/5381095/log.txt)

Combine waiting for the unloader
![fsScreen_2020_10_14_23_59_07](https://user-images.githubusercontent.com/60451845/96051280-74e71680-0e7b-11eb-8b43-83c432bb4c48.png)

Unloading in progress
![fsScreen_2020_10_14_23_59_48](https://user-images.githubusercontent.com/60451845/96051314-87f9e680-0e7b-11eb-973d-b2cf0c4e3a54.png)

Unloader is full
![fsScreen_2020_10_15_00_00_14](https://user-images.githubusercontent.com/60451845/96051340-947e3f00-0e7b-11eb-93db-5e7ceb08f51a.png)

Combine starts moving again pretty close to the unloader as it didn't reverse a bit as it does when no full
![fsScreen_2020_10_15_00_00_21](https://user-images.githubusercontent.com/60451845/96051351-9a742000-0e7b-11eb-82fd-9c8ff8fd131e.png)

Unloader going away to unload course
![fsScreen_2020_10_15_00_00_37](https://user-images.githubusercontent.com/60451845/96051390-b2e43a80-0e7b-11eb-9d14-09dad2449c5d.png)

**Comment by Misamangame** [comment]
"And in a perfect world (but absolutely not essential), the unloader could reverse all the way down the 1st row (probably a bit crazy but that's how we do IRL) or just go through the crop to turn around and then come back in the 1st row already harvested."

Yes this will be nice but if you have really big field that tractor will be reversing for hours and because more unloaders not working perfectly yet it will take ages to unload combine again. I'm for reversing a bit but then find the way either through crops or in cutted pass, but not reversing all the way.
