### ISSUE TITLE
Courseplay Course löschen im Multiplayer

### ISSUE THREAD

**Issue by Blumi39** [Courseplay/courseplay#6223]
Ich hab eine Frage!Ich hab ein Course eingefahren allerdings im Multiplayer nun wollte ich den wieder löschen das geht aber nicht....im singelplayer ist hinter jedem Course ein Papierkorb wo man den Course löschen kann...
weiß einer wie man den Course wieder löschen kann im Multiplayer?

**Comment by Tensuko** [comment]
Glaub das ging über savegame runter laden, kurse löschen und wieder hochladen, hab ich selber noch nie gemacht, probiers mal aus.

**Comment by Blumi39** [comment]
nein über das Savegame geht es auch nicht die Course bleiben drin...aber das ist nur wenn ich im Multiplayer spiele hab nebenbei noch ein Server mit zwei weiteren Spielern

 
 

Gesendet: Donnerstag, 15. Oktober 2020 um 21:50 Uhr
Von: "Tensuko" <notifications@github.com>
An: "Courseplay/courseplay" <courseplay@noreply.github.com>
Cc: "Blumi39" <Danny36@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [Courseplay/courseplay] Courseplay Course löschen im Multiplayer (#6223)


 

Glaub das ging über savegame runter laden, kurse löschen und wieder hochladen, hab ich selber noch nie gemacht, probiers mal aus.
