### ISSUE TITLE
Overloader not working

### ISSUE THREAD

**Issue by jj8230** [Courseplay/courseplay#6224]
Overloader tractor just flashes no combine in reach. Requesting a tractor from the combine doesnt work either. I have everything set up right< been using CP since fs 17. I tried to attach the video in here but its not letting me

**Comment by Tensuko** [comment]
> I have everything set up right

no you did not



> been using CP since fs 17

won't help you at all

Read #5272 and Wiki page https://github.com/Courseplay/courseplay/wiki

And for once: It does work!
