### ISSUE TITLE
Deleting Routes Dedicated Server

### ISSUE THREAD

**Issue by jusceliop** [Courseplay/courseplay#6225]
CoursePlay does not allow deleting routes on a dedicated server, follows screenshot ...
![CP_17-10](https://user-images.githubusercontent.com/16738224/96333578-2aaf9200-1041-11eb-96ec-41f5ef86133b.jpeg)

**Comment by Tensuko** [comment]
Yes, we know, you can only delete them on ftp server directly.

**Comment by jusceliop** [comment]
Servers like GameServer and VeryGames, do not provide FTP access, thanks for the quick response, your work is perfect
