### ISSUE TITLE
Probable mod incompatibility..?

### ISSUE THREAD

**Issue by Steven2327** [Courseplay/courseplay#6227]
It seems that when I use Courseplay in conjunction with Custom Modding's CR9000 Series combines and/or with KMN Modding & NEFG's New Holland CR Series combines, I get a number of strange issues. A common denominator with those two combine mods that I've found is that they're using a custom vehicleType (combineDrivableAnimated). The log reports errors in toolManager.lua relating to function courseplay:isChopper. It also causes header animations not to show even though the machine is running and working (although the animations are visible through the translucent store overlay when the store is open) and the help window is not visible even though it is turned on. Not sure if it is permissible/acceptable to attach the specific .zip files that I'm using..?

**Comment by Tensuko** [comment]
ModIssue, when they keep create custum vehicle types for no reason we cant add all...

**Comment by Steven2327** [comment]
Thanks for the response. I suspected that was likely the case and just wanted to confirm.
