### ISSUE TITLE
Mode1 Beacon Lights and Cover

### ISSUE THREAD

**Issue by MSclimenti** [Courseplay/courseplay#6228]
Grain Transport Mod load at start....... the beacon lights wont come on and cover wont close after loading from auger when it starts it's rout to the silo

**Comment by MSclimenti** [comment]
Is it posable to get this to work now when we are play the game now  later we may not be paying as much we are into the game now and this would make the game so much better but I understand if you can't and have more pressing thing to fix then we will just have to wait and I apologies for asking and try to push you to do this now again I apologies don't be angary with us

**Comment by Tensuko** [comment]
Duplicate and splitting Issue
#6197 and #6547
