### ISSUE TITLE
Course generator does not want to create course

### ISSUE THREAD

**Issue by DriftPulsan** [Courseplay/courseplay#6229]
I am trying to create two courses. 
The field edge path is custom for both of them.
One is for a fertilizer with a 28m working width.

![2020-10-18 (2)](https://user-images.githubusercontent.com/73076609/96377191-6185c500-1173-11eb-91d1-738bd1f72be2.png)

The other one is for a subsoiler with a 5.8m working width.

![2020-10-18 (4)](https://user-images.githubusercontent.com/73076609/96377343-c5f55400-1174-11eb-9d97-c6dacb014660.png)

When I press "generate field course" nothing happens. When press back I can see on the bottom of the CoursePlay menu that there is no longer a course loaded.

![image](https://user-images.githubusercontent.com/73076609/96377599-2a64e300-1176-11eb-80fb-1b86674aeda7.png)

So the CoursePlay has got rid of the "field edge path" but has not made any new course, which should be  a "fieldwork course".

Do you have any idea why that could be?

**Comment by Tensuko** [comment]
Waaaay to old Version....
https://github.com/Courseplay/courseplay/wiki
https://github.com/Courseplay/courseplay/releases

download .zip and place in mods Folder, done (ofc throw the old one out)

**Comment by DriftPulsan** [comment]
Yup, I thought so after thinking about it for a while.
Thanks for the help :D

**Comment by Tensuko** [comment]
If can create a couse with those settings then it will throw out those 'custom drawn course'.
Load the Custom drawn course again and try with other settings. normal behaviour. Also make the CP Update...
