### ISSUE TITLE
CP fährt außen 1x zuviel Rundherum, Mode6, Dreschen

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#6230]
Hallo Leute,
mit v  6.02.00068 fährt der Drescher das Vorgewende doppelt ab:
Einstellungen vom Kursgenerator:
![fsScreen_2020_10_19_00_36_37](https://user-images.githubusercontent.com/24860501/96387623-c22cf600-11a3-11eb-9eb3-02bde6149d29.png)
und hier ein screenshot vom Kurs:
![fsScreen_2020_10_19_00_41_50](https://user-images.githubusercontent.com/24860501/96387652-f9030c00-11a3-11eb-9198-d75655f429d3.png)
(den Startpunkt hab ich nur manuell aus dem Feld gelegt, damit der Drescher besser starten kann.)

in der kurs-xml sind jede menge
 isconnectingtrack="true"/>
drinnen:
[courseStorage0022.txt](https://github.com/Courseplay/courseplay/files/5398303/courseStorage0022.txt)

was läuft da schief?

lg
andreas

**Comment by Tensuko** [comment]
Kann ich dir genau sagen was da läuft.
Das ist nichts neues...
Das ist die Transition zum Übergang.
Da dein Übergang vor dem Start liegt, macht er eine Runde ohne Schneidwerk an.
Das war aber schon immer so....
Mach deinen Startpunkt weiter nach rechts (unteres Bild) dann ist der Start vor dem Übergang (hoffentlich) und er hat eine so kurze Trastion, dass du das gar nicht mitbekommst :)

Er arbeitet der schwarzen Linie entlang, arbeitet dann so weit, dass er hinter den Übergang zu den Lands fährt (blaue Linie in der 'Vergrößerung') und muss dann den weg bis zum Übergang fahren (rote Linie).
![transition](https://user-images.githubusercontent.com/27344744/96406009-d17d6500-11de-11eb-9b3a-c95e07517497.png)

Wie gesagt, ist nichts neues, fällt in der Situation nur besonders auf.
Wäre dein Start an der rechten langen Kante, hättest du auch nur eine kurze Strecke als Transition.

**Comment by pvaiko** [comment]
Das Problem wurde hier diskutiert: https://github.com/Courseplay/courseplay/issues/6079#issuecomment-711351632

**Comment by andreasthu** [comment]
Hallo Leute
habe jetzt auch die v69 probiert:
![fsScreen_2020_10_20_08_29_22](https://user-images.githubusercontent.com/24860501/96549588-f7bf0580-12af-11eb-943d-b9ca893f9b53.png)
man sieht hier, oberhalb des Mähdreschers, cp macht wieder eine unnötige ganze runde ums Feld, obwohl das nicht nötig wäre.
die schräge zur feldbearbeitung ist auch unnötig lang
wenn ich den startpunkt ein ganzes stück weiter nach hinten verlege funktioniert es:
![fsScreen_2020_10_20_08_30_05](https://user-images.githubusercontent.com/24860501/96549752-3359cf80-12b0-11eb-9005-01f56a834182.png)
ihr seht hier auch, die schräge zum übergang vom Vorgewende zur Feldbearbeitung ist annähernd 45grad, also nicht so steil wie am oberen Bild. wenn sie am oberen bild auch 45grad wäre, würde es da auch passen
noch zwei bilder:
![fsScreen_2020_10_20_08_37_44](https://user-images.githubusercontent.com/24860501/96550302-f9d59400-12b0-11eb-8116-38ed919a30ff.png)
![fsScreen_2020_10_20_08_37_55](https://user-images.githubusercontent.com/24860501/96550309-fc37ee00-12b0-11eb-9cff-e03d543609d5.png)
oben links in der Nordwestecke macht CP einen komischen übergang zur 2. Reihe,
und da ist es auch egal, ob an einer langen oder einer kurzen Feldseite der Kurs beginnt.
bei v67 hatte  ich solche probleme noch nicht
lg
andreas

**Comment by Tensuko** [comment]
> man sieht hier, oberhalb des Mähdreschers, cp macht wieder eine unnötige ganze runde ums Feld, obwohl das nicht nötig wäre.

Transition... wie ich es dir beschrieben habe... Unnötig ist dies nicht, es ist der weg vom ende des letzten Vorgewende zum Übergang in die Feldreihen. Er ist eben nur so lang, weil das Ende des letzten Vorgewende knapp hinter dem Übergang ist.
Wäre das Ende einige Meter davor und wir würden die Strecke ohne Abschalten der Geräte fahren, wird da wieder gemosert :)

> wenn ich den startpunkt ein ganzes stück weiter nach hinten verlege funktioniert es:

und die Lösung hast du hiermit selber erkannt :)

> die schräge zur feldbearbeitung ist auch unnötig lang

Das kommt drauf an, wo das erste Vorgewende endet und wie die Feldreihen beginnen... Dramatisch ist das nicht gerade...

> ihr seht hier auch, die schräge zum übergang vom Vorgewende zur Feldbearbeitung ist annähernd 45grad, also nicht so steil wie am oberen Bild.

Da du den startpunkt verschoben hast, ist auch das ende des ersten Vorgewendes an eine andere Stelle gerückt, bei gleicher Aufteilung der Feldreihen, logisch, dass die Schräge anders ist.

**Comment by pvaiko** [comment]
Der "komische Übergang" ist ein Bug, das dürfte nicht passieren.

**Comment by andreasthu** [comment]
![fsScreen_2020_10_20_08_29_22](https://user-images.githubusercontent.com/24860501/96587561-c27fdb00-12e2-11eb-8b39-890dc1432fcf.png)
> Transition... wie ich es dir beschrieben habe... Unnötig ist dies nicht, es ist der weg vom ende des letzten Vorgewende zum Übergang in die Feldreihen. Er ist eben nur so lang, weil das Ende des letzten Vorgewende knapp hinter dem Übergang ist.
> Wäre das Ende einige Meter davor und wir würden die Strecke ohne Abschalten der Geräte fahren, wird da wieder gemosert :) 

> > wenn ich den startpunkt ein ganzes stück weiter nach hinten verlege funktioniert es:
> 
> und die Lösung hast du hiermit selber erkannt :)
> 
ja schon aber den startpunkt kann man in cp nicht beliebig setzen er springt auch einige meter, 20 oder, so dann nach links oder rechts

> > die schräge zur feldbearbeitung ist auch unnötig lang
> 
> Das kommt drauf an, wo das erste Vorgewende endet und wie die Feldreihen beginnen... Dramatisch ist das nicht gerade...
> 
> > ihr seht hier auch, die schräge zum übergang vom Vorgewende zur Feldbearbeitung ist annähernd 45grad, also nicht so steil wie am oberen Bild.
> 
> Da du den startpunkt verschoben hast, ist auch das ende des ersten Vorgewendes an eine andere Stelle gerückt, bei gleicher Aufteilung der Feldreihen, logisch, dass die Schräge anders ist.
ja, aber wenn hier die schräge auch näher wäre, wäre die transition unnötig

und sorry ich wollte nicht mosern, wollte nur einige mir aufgefallene fehler melden
lg
andreas

**Comment by Tensuko** [comment]
> und sorry ich wollte nicht mosern, wollte nur einige mir aufgefallene fehler melden

Das war auch so nicht gemeint, nur eben das man es nicht allen immer recht machen kann. Einer muss immer mit Einschränkungen leben (zumindestens erstmal) und wie gesagt, man krigt es ja umgangen und der Startpunkt ist schon recht präzise, wenn man rein zoomt. Klar 100% wird es nie passen :)

**Comment by andreasthu** [comment]
sorry aber ich habe nachwievor massive probleme mit der Transition, wo sie nicht nötig wäre
diesmal mit v071
![fsScreen_2020_10_22_08_52_15](https://user-images.githubusercontent.com/24860501/96835915-882e4f00-1444-11eb-8c0d-f4bef1886c67.png)
![fsScreen_2020_10_22_08_52_24](https://user-images.githubusercontent.com/24860501/96835925-8a90a900-1444-11eb-9b71-6ea96fe59516.png)
am ersten screen die Kurseinstellungen
am zweiten das ergebniss (wp 2 und 3 hab ich mit dem ingame editor rausgezogen,
so sieht man die transition besser)

und so sieht  es aus wenn ich den startpunkt weiter mittig setze:
![fsScreen_2020_10_22_08_52_37](https://user-images.githubusercontent.com/24860501/96836100-c6c40980-1444-11eb-89fd-49f5e3611ae6.png)
![fsScreen_2020_10_22_08_52_59](https://user-images.githubusercontent.com/24860501/96836106-c9266380-1444-11eb-86d8-7dcd0cda730d.png)
die schräge zu Übergang zur feldbearbeitung ist nun viel flacher und cp berechnet wieder eine zusätzliche leerrunde (wp2 u 3 weider etwas rausgezogen zur besseren übersicht)

und so schauts aus wenn ich den startpunkt ziemlich zum ende setze:
![fsScreen_2020_10_22_08_53_57](https://user-images.githubusercontent.com/24860501/96836329-1c98b180-1445-11eb-9072-f0f194e374cf.png)
![fsScreen_2020_10_22_08_54_10](https://user-images.githubusercontent.com/24860501/96836332-1e627500-1445-11eb-9919-2e450f3eac35.png)

lg
andreas
