### ISSUE TITLE
fs19 CoursePlay Sound Bug?

### ISSUE THREAD

**Issue by Rifzyt** [Courseplay/courseplay#6231]
While using course play I'm having an issue when using the combined unload option, where it makes every vehicle in the map, have an annoying sound with the RPMs go up or down. It disrupts the sound and makes it Go up or Go down in skips and makes it sound not smooth at all

**Comment by Tensuko** [comment]
No Idea what you talking about.
Logfile ?

**Comment by Tensuko** [comment]
No Idea what you have for mods running and stuff.
Never had and don't have any sound bug. For sure not a CP Issue.
