### ISSUE TITLE
In vain the round, if not on the ground. v6.02.00069

### ISSUE THREAD

**Issue by wertigoxxx** [Courseplay/courseplay#6234]
**Hy!**
_The problem is this: the tractor is not driving in the round!_

He can go to the building, to the trees. :(
Unfortunately, the CP is getting worse! Not to be enjoyed like this, I’m starting to give up my CP trials, in vain for newer releases!

It would be worth considering the incorporation of a function so that if anything goes to him, then push back and plan again !!!

Thoughtfully:
When the tractor is looking for a route and the harvester is far away, it will take several minutes to find it! (if you find it)
Do less pre-planning with your pathfinder! Take note of the position of the combine, but don’t plan so far, because by the time you get there, the harvester will no longer be there!
You need to replan your route !! Which results in a lot of FPS loads!
Fruit bypass on!
==============
It was just a suggestion if it can’t be solved, I understand, but it’s going to get on the nerves of a lot of players, which will sooner or later make the use of CP pointless!
==============

Sorry for the English!

Picture and LOG attached!

=======================
**Through the building, is it normal?**
=======================
![fsScreen_2020_10_19_17_29_37](https://user-images.githubusercontent.com/65092037/96473772-547bdb00-1232-11eb-9040-2c43865a2305.png)

==============================================
**there is already a turn on the ground and yet it does not travel there!**
==============================================
![Farming Simulator 19 Screenshot 2020 10 19 - 17 30 09 17](https://user-images.githubusercontent.com/65092037/96473819-62316080-1232-11eb-9c4d-40afb2b14a0e.png)

LOG:

[log.txt](https://github.com/Courseplay/courseplay/files/5403026/log.txt)

**Comment by pvaiko** [comment]
# =================================================================================
# We can't see the mode 2 course start waypoint!! Especially in which direction it is pointing!! And therefore can't tell why exactly the pathfinder fails!!
# ==================================================================================
# And as always! Contributions are welcome!!! If you can fix the pathfinder, please go ahead and issue a pull request !!!

**Comment by wertigoxxx** [comment]
....
