### ISSUE TITLE
Mode 3 - Auger wagon doesn't pause at same point

### ISSUE THREAD

**Issue by Clipless** [Courseplay/courseplay#6237]
When running in Mode 3 I have set course and established a pause point for overloading to occur. If there is no tipper/ trailer present for the cart to overload into then tractor will stop at pause point as recorded. If the tipper/ trailer is present then the tractor will randomly drive past the pause point by several feet, but not always. I end up having to move the tipper wagon about 75% of the time to align with the auger. It will also randomly stop pausing to overload all together and run right through the pause with full auger wagon and sit at the stop point until I manually unload.

**Comment by Tensuko** [comment]
Screenshot of how you position the Waitpoint, that thing is, that the record position is not the same as the driver/stop position!

**Comment by andreasthu** [comment]
Same here,
The drive with the Sauger Wagon Stöpsel randomly not at the wait-waipoint.
Sometimes he drive 0 to 10m before he Stöpsel.
Sometime tue pipe is always over the unloading Trailer, sometimes he drive out of the Trailer.
When there is no Trailer to unload the augerwagon stops always by the waitpoint.
Lg
Andreas

**Comment by Tensuko** [comment]
Hmm I think I have to try this one out a bit more, to find whats going on, will have a look at this.

**Comment by andreasthu** [comment]
ich kann da  jetzt noch zwei Überladeorgnge beisteuern.
gleiches Feld, gleiche Fahrzeuge, gleicher Spielstand
1.Abtanken:
![fsScreen_2020_10_25_09_51_49](https://user-images.githubusercontent.com/24860501/97103762-d21a6d80-16ae-11eb-83fb-5946c3e398ef.png)
![fsScreen_2020_10_25_09_52_00](https://user-images.githubusercontent.com/24860501/97103766-d777b800-16ae-11eb-8d8c-e180e4f4ef3a.png)
der ÜLW bleibt VOR dem Haltepunkt stehen und tankt im hinteren Teil des Hängers ab

2.Abtanken:
![fsScreen_2020_10_25_10_39_51](https://user-images.githubusercontent.com/24860501/97103774-f118ff80-16ae-11eb-8e6e-e1115af06677.png)
![fsScreen_2020_10_25_10_39_58](https://user-images.githubusercontent.com/24860501/97103778-f4ac8680-16ae-11eb-945a-4664c9858fe3.png)
hier rollt der Traktor über den Haltepunkt hinaus der Anhänger ist aber lang genug und er kann überladen.
lg
andreas

**Comment by PhotoshopLOL** [comment]
Hi!

Updating from 6.02.00068 to 6.02.00076 fixed this for me

**Comment by Tensuko** [comment]
Hab am Wochenende knapp 200k Raps vom Feld geholt mit ÜLW und brauchte mich nie um den Überladepunkt kümmern.

I harvested arround 200k Liter fruit on Weekend and never had to care for the auger wagon to overload in the Trailer.

6.03.00003
