### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by tailos2015** [Courseplay/courseplay#6239]
How to use translation

**Comment by Tensuko** [comment]
Set your game language to the one you want to have ?

**Comment by tailos2015** [comment]
Courseplay

**Comment by Tensuko** [comment]
What do you want ??

**Comment by tailos2015** [comment]
I don't know how to use

**Comment by tailos2015** [comment]
How to use translation

**Comment by Tensuko** [comment]
What do you want to use there ?
If you game is in english, CP will be in english too, is your game in polish, CP will be in polish too ?!
and so on.... so what do you want to use ?! Just set your game to the translation you want to have.......
If you have a translation missing, let us know and you can translate it then...

**Comment by tailos2015** [comment]
Do you have Traditional Chinese

**Comment by Tensuko** [comment]
Is it this ? https://github.com/Courseplay/courseplay/blob/master/translations/translation_cs.xml

**Comment by tailos2015** [comment]
我試試看

**Comment by Tensuko** [comment]
Not sure whats up about this.
If need a translation let us know, but also check if the game itself got it or whatever.
