### ISSUE TITLE
More of a question on HOW-TO than an issue...

### ISSUE THREAD

**Issue by MadOtis** [Courseplay/courseplay#6240]
I'm using CP 6.02.00064.dev on the Stone Valley map.  I'm not sure if I set up multi-harvester correctly or not, but running into issues with an unload course.  And most likely, I've simply done it wrong, so any insights might help.

Step 1) Multi-harvester CP course (2 same harvesters that come with the map starting point: John Deere S790 w/ 618C headers)
- Create new course on Field 20
- set tools to 2
- 1 headland
- save course
Step 2) 1st JD Harvester where course was generated from
- Set to LEFT side
- manually adjust offset to 4.5m left
- set convoy mode on
Step 3) 2nd JD Harvester
- load saved course
- set to RIGHT side
- manually adjust offset to 4.5m right
- set convoy mode on
Step 4) Start both harvesters from first waypoint and they both do what is expected.
Step 5) Create a harvester unload path to use a Claas Axion 960 pulling an Elmer's HaulMaster with appropriate start, unload, and stop points.
- Set the harvesters to watch for either manually (putting an X in both listed harvesters, or simply selecting field 20)
Step 6) Start the unload course on the Axion.

What I'm seeing is:
The Axion will wait, as expected, then move onto field when the first harvester gets beyond 50% full and the Axion starts tracking towards it.
As the Axion gets closer, the pipe extends on the harvester as expected, but the Axion basically drives into the back of the harvester instead of off to the pipe-side.

Experimentation:
I set an offset of 4.5m to the left on the Axion's course, and it successfully unloads the 1st harvester (the LEFT one).  However, when the 2nd harvester (the RIGHT one), it offsets an additional 4.5m (equalling 9m to the left of the 2nd harvester), and will never unload it.

What might I be doing incorrectly?  And, yes, I'm mostly new to using CP, which is a FANTASTIC mod, even with the multi-player issues!!!!

So, feel free to point me to where this sort of question SHOULD be asked if I've put it in the wrong place by posting it here.

Cheers!

**Comment by Tensuko** [comment]
I will do some tests on this one.
What I don't understand is, why you set an 4.5m offset to anything ?
All offsetvalues are actually self calculated. if you have a 9m wide harvester, then left/right will have its own generated course with 4.5m offsetcourse...

**Comment by MadOtis** [comment]
> I will do some tests on this one.
> What I don't understand is, why you set an 4.5m offset to anything ?
> All offsetvalues are actually self calculated. if you have a 9m wide harvester, then left/right will have its own generated course with 4.5m offsetcourse...

I tried to create courses several times without setting manual offsets and each time, If I don't set an offset on each harvester, they both follow the CP generated course in the center (right along the path) with a 4.5 swath of unharvested crop on each side.  They would still follow each other in convoy, but would stay in the center.

**Comment by Tensuko** [comment]
![fsScreen_2020_10_21_17_34_52](https://user-images.githubusercontent.com/27344744/96743252-131b3500-13c4-11eb-960b-bcf0ba438c89.png)
![fsScreen_2020_10_21_17_33_17](https://user-images.githubusercontent.com/27344744/96743257-144c6200-13c4-11eb-90a6-311bd9307222.png)

For MP make sure you use the newest Version!

**Comment by MadOtis** [comment]
![image](https://user-images.githubusercontent.com/3913270/96820836-a1e77c00-13db-11eb-8f1a-c8301a1b7bb7.png)
![image](https://user-images.githubusercontent.com/3913270/96820943-d5c2a180-13db-11eb-8635-52eacea98efe.png)
![image](https://user-images.githubusercontent.com/3913270/96821132-2b974980-13dc-11eb-8556-e712a03148c9.png)

Yeah, I tried that a few times, here is what I get when not using the manual offsets

**Comment by Tensuko** [comment]
Dedicated Server ?
If so update to .00071

**Comment by MadOtis** [comment]
Yes, a dedicated server.  I'll update to 00071 and retry.  Should I also re-record the CP?

**Comment by Tensuko** [comment]
Yea you should make a new course.

**Comment by MadOtis** [comment]
Upgrading to 6.02.00071 and re-recording the harvester course did indeed fix the multi-harvester issue and I no longer have to set manual offsets per harvester.  However, now a new course generated to unload the harvesters doesn't run at all; the tractor and auger wagon just sit and do nothing when either harvester needs to be unloaded; it just sits there with no trigger to drive onto the field.  I tried setting it to simply monitor field 20, and explicitly looking for the two harvesters on that field, and it still refuses to do anything but wait.

**Comment by Tensuko** [comment]
Did you mark the Harvester with an X ?
Also I am not sure if Mode2 is working on MP Server yet, selfunload does but is a bit slow sometimes.

Anyway original issue is cleared and the Mode 2 Issue comes up again and again and all I can say is in SP it is working, also check #5272 and wiki for debugging and giving information and stuff.
It is easy to see in the log if he find the harvester or not.
