### ISSUE TITLE
Unoffical FS17 CP support

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#6241]
As a former developer of CP during FS17. I will be extending **unofficial** support to CP v5(FS17 version). This can be found on my fork of CP at https://github.com/pops64/courseplay. I will primarily be focused on fixing bugs and improving current features. I have no plans to add new features.

Just to be clear this is unofficial and I have received no permission to provide such support as always the last official version of CP can be found in this repository. To the CP team I apologize in advanced if this is in poor form.

**Comment by pvaiko** [comment]
Sure, good idea. We can include a link to it in our README if you create a pull request for it (text should only contain facts, no opinions).
