### ISSUE TITLE
Unschöner Übergang vom Vorgewende zu Feldreihen

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#6243]
sorry aber ich habe nachwievor massive probleme mit der Transition, wo sie nicht nötig wäre
diesmal mit v071
(Ich weiß leider nicht wie ich ein closed thread wieder öffne, früher ging es noch)
![fsScreen_2020_10_22_08_52_15](https://user-images.githubusercontent.com/24860501/96835915-882e4f00-1444-11eb-8c0d-f4bef1886c67.png)
![fsScreen_2020_10_22_08_52_24](https://user-images.githubusercontent.com/24860501/96835925-8a90a900-1444-11eb-9b71-6ea96fe59516.png)
am ersten screen die Kurseinstellungen
am zweiten das ergebniss (wp 2 und 3 hab ich mit dem ingame editor rausgezogen,
so sieht man die transition besser)

und so sieht  es aus wenn ich den startpunkt weiter mittig setze:
![fsScreen_2020_10_22_08_52_37](https://user-images.githubusercontent.com/24860501/96836100-c6c40980-1444-11eb-89fd-49f5e3611ae6.png)
![fsScreen_2020_10_22_08_52_59](https://user-images.githubusercontent.com/24860501/96836106-c9266380-1444-11eb-86d8-7dcd0cda730d.png)
die schräge zu Übergang zur feldbearbeitung ist nun viel flacher und cp berechnet wieder eine zusätzliche leerrunde (wp2 u 3 weider etwas rausgezogen zur besseren übersicht)

und so schauts aus wenn ich den startpunkt ziemlich zum ende setze:
![fsScreen_2020_10_22_08_53_57](https://user-images.githubusercontent.com/24860501/96836329-1c98b180-1445-11eb-9072-f0f194e374cf.png)
![fsScreen_2020_10_22_08_54_10](https://user-images.githubusercontent.com/24860501/96836332-1e627500-1445-11eb-9919-2e450f3eac35.png)

edit
selbst wenn ich seitlich starte:
![fsScreen_2020_10_22_09_08_14](https://user-images.githubusercontent.com/24860501/96837139-3ab2e180-1446-11eb-8195-7888ee43e5cb.png)
![fsScreen_2020_10_22_09_07_55](https://user-images.githubusercontent.com/24860501/96837147-3dadd200-1446-11eb-9edd-da60583af28b.png)

lg
andreas

_Originally posted by @andreasthu in https://github.com/Courseplay/courseplay/issues/6230#issuecomment-714277992_

**Comment by Tensuko** [comment]
Das ist echt strange was du da hast... Ich würde mal versuchen bisschen mit den Einstellungen zu experimentieren, weil das was du da hast schaffe ich garnicht. Hab diverse Einstellungen probiert und verschiedene Startpositionen.

![fsScreen_2020_10_22_18_46_58](https://user-images.githubusercontent.com/27344744/96904137-fdc30b00-1496-11eb-9c12-b26e9ecaf4a3.png)
![fsScreen_2020_10_22_18_53_19](https://user-images.githubusercontent.com/27344744/96904804-dfa9da80-1497-11eb-9888-1b23cf0657a8.png)
![fsScreen_2020_10_22_18_52_28](https://user-images.githubusercontent.com/27344744/96904815-e2a4cb00-1497-11eb-97b0-1f08145c9ac3.png)

Und diverse andere Beispiele (werden aber zu viele Bilder...)

**Comment by andreasthu** [comment]
hallo tensuko
ja schon strange
btw1: zum "Tensuko changed the title" --->>> + merkwürdiges ausweichen
beziehst du dich auf die ingame bilder?
dazu hab ich ja geschrieben das ich den 2. und 3. wegpunkt mit dem ingame editor etwas rausgezogen habe damit man am bild sieht das da eine zusätzliche "ehrenrunde" berechnet wird

btw2:
auf deinen zwei letzten Bildern sieht man auch wieder den komischen Übergang (rehts unten) vom Vorgewende zu den Feldreihen. sollte das pvaiko nicht mit v071 gefixt haben?

ich kann mir nicht helfen, die letzte version wo das bei mir noch gut funktioniert ist v067

lg
andreas

**Comment by Tensuko** [comment]
> btw1: zum "Tensuko changed the title" --->>> + merkwürdiges ausweichen

Oh ja das habe ich dann wohl geschickt überlesen :) 



> auf deinen zwei letzten Bildern sieht man auch wieder den komischen Übergang (rehts unten) vom Vorgewende zu den Feldreihen.

Hmm dann müssen wir mal über die definition komischen Übergang sprechen... weil ich finde nicht das dieser komisch ist, solange ich damit das Feld abgedeckt kriege und er keine unnötigen Kreisel dreht.
Kannst du sonst mal ein Video davon drehen, wenn er an diesem Übergang sich komisch verhält ?

**Comment by pvaiko** [comment]
@andreasthu naja, ich habe es nicht mit den weichen Ecken getestet.. Sorry, deshalb hast du den komischen Übergang. Die ersten zwei Bilder kann ich nicht erklären, muss reinschauen.

**Comment by andreasthu** [comment]
@Tensuko 
diese ecke meinte ich
![96904815-e2a4cb00-1497-11eb-97b0-1f08145c9ac3](https://user-images.githubusercontent.com/24860501/96910803-4b904100-14a0-11eb-9110-3e953cc09899.png)
![96904804-dfa9da80-1497-11eb-9888-1b23cf0657a8](https://user-images.githubusercontent.com/24860501/96910828-521eb880-14a0-11eb-9e1c-150a44aa0554.png)

@pvaiko 
feldmissionen bearbeite ich grundsätzlich mit weichen ecken, geht schneller, und die 90% kriegt man auch so voll
eigene Felder bearbeite ich mit scharfen ecken, dann ist das ganze Feld bearbeitet
werde das auch mal mit scharfen ecken testen

lg
andreas

**Comment by andreasthu** [comment]
Hallo @pvaiko 
Hallo @Tensuko 

hab da jetzt nochmal ein paar tests gemacht, soweit klappt es mit der v0072 ganz gut.
kann das jetzt schon im kursgenerator sehen:
![fsScreen_2020_10_25_09_53_16](https://user-images.githubusercontent.com/24860501/97102795-b0b68300-16a8-11eb-853a-b0bec9af5179.png)
wenn ich einen kurs generiere und der übergang ist eher Lang und Flach (siehe weisser Kreis), dann berechnet cp eine ungewollte transition-runde ums Feld,
setzte ich dann den startpunkt etwas zurück, und sehe a übergang das er eher kurz und Steil ist (weisser kreis):
![fsScreen_2020_10_25_09_54_27](https://user-images.githubusercontent.com/24860501/97102835-0a1eb200-16a9-11eb-9128-92850e24ee7d.png)
dann passt mir die kursberechnung so damit kann ich gut leben.
danke dafür
lg
andreas

**Comment by andreasthu** [comment]
@pvaiko 
@Tensuko 
hallo ihr zwei
tut mir leid, mir ist gerade aufgefallen das der übergang vom Vorgewende zu den Feldreihen bei scharfen Ecken wieder problee macht, wegen der position der "turn start" und "turn end" punkte
ausgangsbasis:
![fsScreen_2020_10_25_15_29_18](https://user-images.githubusercontent.com/24860501/97110206-33a30200-16d8-11eb-9a11-ed9b1337e4c5.png)
so schaut der übergang aus:
![fsScreen_2020_10_25_15_27_42](https://user-images.githubusercontent.com/24860501/97110217-40275a80-16d8-11eb-9a36-7de5e44cc0df.png)
![fsScreen_2020_10_25_15_27_50](https://user-images.githubusercontent.com/24860501/97110223-4584a500-16d8-11eb-8745-898d3da391d4.png)
![fsScreen_2020_10_25_15_27_56](https://user-images.githubusercontent.com/24860501/97110227-49182c00-16d8-11eb-9b26-e0c371f45b4c.png)
![fsScreen_2020_10_25_15_28_02](https://user-images.githubusercontent.com/24860501/97110238-4c131c80-16d8-11eb-873c-cf490f6578f5.png)
![fsScreen_2020_10_25_15_28_14](https://user-images.githubusercontent.com/24860501/97110240-4f0e0d00-16d8-11eb-9e42-f4870378d279.png)
der fahrer fährt einige male vor bzw zurück bevor er mit der Feldbearbeitung geginnen kann.
meiner meinung nach sollte die Turn Start bzw Turn end jeweils eine position nach vor rücken:
![fsScreen_2020_10_25_15_28_58](https://user-images.githubusercontent.com/24860501/97110269-8da3c780-16d8-11eb-8cc2-3a115dd53dba.png)
![fsScreen_2020_10_25_15_29_00](https://user-images.githubusercontent.com/24860501/97110270-909eb800-16d8-11eb-8ddc-74cb67320fdf.png)
dann funktioniert es reibungslos.
ist bei dreschen genauso hab das nur beim Dreschen am vormiittag übersehen.


wenn man weiche ecken einstellt anstatt scharfe funktioniert es besser da dann keine turn start bzw turn end punkte generiert werden:
![fsScreen_2020_10_25_15_30_17](https://user-images.githubusercontent.com/24860501/97110335-f25f2200-16d8-11eb-8b34-c937898bf391.png)
![fsScreen_2020_10_25_15_30_21](https://user-images.githubusercontent.com/24860501/97110340-fab75d00-16d8-11eb-9308-ec00d40d96ad.png)
![fsScreen_2020_10_25_15_30_28](https://user-images.githubusercontent.com/24860501/97110345-ff7c1100-16d8-11eb-98e6-9a38d2ff37a1.png)

lg
andreas
