### ISSUE TITLE
Tool starts before aligning to target WP

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#6244]
Hello why does the tractor kind of curl after refilling seed and returning to the point that it left off if it’s on a straight why can’t it line up and go forward see pic to see what I’m on about it’s cut into previous lane and cut out tramline 
![467E711D-8DC9-4093-969D-14ED5EF81D48](https://user-images.githubusercontent.com/27097241/96933835-1b08d100-14b9-11eb-8a44-4a354943a0c4.png)

**Comment by pvaiko** [comment]
Sorry, don't understand the problem, do you have a video?

**Comment by matty2123** [comment]
Sorry should of explained a bit better on my new pic if you see the red line that’s where the seeder ran out and of course you start again after refilling right obviously it should line up straight it a straight section. In my diagram that’s how it’s going starting the seeder in lane 2 and then into lane 1 which it’s working on. I’ll get a video if needs be 
![Uploading 8A81922F-E05E-436C-A5D1-A1A0E8580384.jpeg…]()

**Comment by matty2123** [comment]
![FE635A9D-7231-4A52-9C69-B038BE62FEE7](https://user-images.githubusercontent.com/27097241/97033902-f580d380-155b-11eb-96da-686f0d760f74.png)

**Comment by matty2123** [comment]
![AE68712D-2482-4119-AF6C-F83CE1318345](https://user-images.githubusercontent.com/27097241/97033935-016c9580-155c-11eb-9b69-a980cbf38c1c.jpeg)

**Comment by matty2123** [comment]
https://vimeo.com/471512869?ref=em-share

**Comment by Tensuko** [comment]
This is just starting the tools to leary before aligning to the waypoint it wants to continue.
