### ISSUE TITLE
Frage zum Abtanken vom Drescher

### ISSUE THREAD

**Issue by Steela133** [Courseplay/courseplay#6245]
Hallo zusammen

Erstmal vorweg, Ohne euch täte es das Spiel nicht für mich geben! Seid Jahren(LS15-19) seid ihr meine Ls Götter und ich bin euch zutiefst dem Dank verpflichtet für die ganze Arbeit die ihr investiert! Nur durch euch ist für mich als Singleplayer das Spiel erst möglich geworden bzw. bringt mir den waren Spaß.

Ich habe jetzt seid ca. einem 3/4 Jahr Pause wieder richtig Lust darauf. Und musste feststellen das Der Modus2 zum Abtanken nur noch mit Courseplay funktioniert. Und ja ich habe gelesen das ihr das wegen Problemen so gemacht habt (Ihr werdet eure Gründe haben!) 
Aber selber nicht mehr Drescher/Roder/Häcksler (Mit Gps) fahren ohne abgetankt zu werden, war jetzt irgendwie ein Stich in mein LS Herz :(

Daher meine Frage/Bitte die ihr euch sicher denken könnt....Soll das wieder kommen das Courseplay alles abtankt( Helfer, AI Vehicle) und vor allem mich selber? Das hat ja Jahrelange finde ich Bombe funktioniert.

Falls dieser Post unter die Kategorie nerven oder gab es schon geht. Könnt ihr ihn gern wieder löschen. Ich weiß ihr arbeitet hart an den gefühlt 1Mio. anderen Aufgaben für Courseplay.

Liebe Grüße

**Comment by Tensuko** [comment]
Wenn etwas wieder kommen wird, dann nur, dass der Player abgetankt wird, das ist mehr oder weniger in Arbeit von einem aus der Community, wann da was kommen wird, kann ich dir leider nicht sagen.

**Comment by Steela133** [comment]
Vielen Dank mit der Antwort kann man denk ich leben
