### ISSUE TITLE
Creat or delete point

### ISSUE THREAD

**Issue by Step72** [Courseplay/courseplay#6246]
Hello
I had asked a question concerning the deletion of the points [here](https://github.com/Courseplay/courseplay/issues/6045) but it was closed without my answering.
I am relaunching this subject because despite having performed the parameter commands, I am unable to create or delete a point.

<img width="600" alt="Capture d’écran 2020-10-23 à 11 52 39" src="https://user-images.githubusercontent.com/18511992/96990653-acaf2780-1527-11eb-9cae-64dc1eeb2077.png">

The commands below does not work.
<img width="600" alt="Capture d’écran 2020-10-23 à 10 52 14" src="https://user-images.githubusercontent.com/18511992/96990733-c5b7d880-1527-11eb-8e92-f2b987bf2970.png">

Why?
Thank you

**Comment by Tensuko** [comment]
Sry but I did answer you your question:

> You got to set your own keys in keysettings to make it work.
> The one shown in F1 are a bit confusing I know...

Basically rebind the keys, then ir works just fine.
You got to hover over the waypoint you want to delete or hover over a waypoint and when you press the combination to add a qaypoint, it will be added 'behind' the waypoint.

**Comment by Step72** [comment]
Hello  Tensuko 
Look this image.I placed my cursor on the point below then I pressed the right button of my mouse but it did not remove the point
<img width="600" alt="Capture d’écran 2020-10-23 à 14 57 18" src="https://user-images.githubusercontent.com/18511992/97006945-e8a2b680-1540-11eb-9ed4-3bb8e3d31d11.png">

**Comment by Tensuko** [comment]
Mouse Buttons can't use for Course Editor.

**Comment by Step72** [comment]
Ok nice
Thank you Tensuko

**Comment by Tensuko** [comment]
Does it work for you now so I can take this as done ?

**Comment by Step72** [comment]
Hello Tensuko,
It is impossible for me to let the cursor position on a point and then press keys on the keyboard because, being quadriplegic, I use my mouse cursor to be able to type the keys on my virtual keyboard on the screen.
<img width="600" alt="Capture d’écran 2020-10-26 à 09 09 15" src="https://user-images.githubusercontent.com/18511992/97148304-313db800-176b-11eb-90be-9a4acb2b4e24.png">
Wouldn't it be possible rather than to position the cursor on a point to select the point and then to use a keyboard command to delete, add as Auto drive?

Thank you

**Comment by Tensuko** [comment]
Hmm will see if we can figure something out for this one. Or I find a better way.
What options do you have on your 'mouse joystick' ?

**Comment by Step72** [comment]
To play farming I use a ps4 controller that I plugged into my computer. I play with this controller with my chin because I am quadriplegic ([See here](https://youtu.be/Gv9RkBC_EVk))
The left joystick of my controller allows me: To move forward, backward, turn right and left

The right joystick is used to move the camera under courseplay.

Then, my on-screen keyboard allows me to perform all the combinations of the games but coursplay must be open because if courplay is closed the mouse cursor is not displayed and therefore I cannot click on the keys of the visual keyboard.

**Comment by Tensuko** [comment]
Yes I know about this, the question is, is there any other buttons our stuff you can use beside the sticks, just to map a button on it to do some click actions ?

**Comment by Step72** [comment]
Yes I have free buttons on my ps4 controller

**Comment by Tensuko** [comment]
Can you try to use them for the Editor or do mapping like 'X Button is ctrl+5' ?
I wrote the creater of the Editor if he knows a way to change it like you suggested but he is rarely online.

**Comment by Step72** [comment]
sorry but i can't press the button on ps4 controller and keyboard at the same time, that's why it would be nice to be able to select the point and not keep the cursor on the point, like on Auto drive.

With Auto drive we add a point by doing crtl then we click where we want to put the point.

And to delete a point, we do Alt then we click on the point to be deleted

**Comment by Step72** [comment]
Watch [my video](https://we.tl/t-vc0lTCRHMc)
Are there any plans to be able to create points and relay them to one another like Autodrive?

**Comment by Mike1977** [comment]
> 
> 
> Watch [my video](https://we.tl/t-vc0lTCRHMc)
> Are there any plans to be able to create points and relay them to one another like Autodrive?

I would like to see that too. In my view it's way easier to handle and more intuitive in autodrive and i don't think it would be hard to change the current way how the courseplay editor is doing it, into that system.

**Comment by Tensuko** [comment]
> Are there any plans to be able to create points and relay them to one another like Autodrive?

No plans to do it like that.



> I would like to see that too. In my view it's way easier to handle and more intuitive in autodrive and i don't think it would be hard to change the current way how the courseplay editor is doing it, into that system.

We wait for your pullrequest to those changes :) Be aware, CP waypoint system is different then AD one.
We don't make relations to each other WP, we have an order of waypoints...

**Comment by Step72** [comment]
> We wait for your pullrequest to those changes :) 

sorry I didn't understand your answer

**Comment by Tensuko** [comment]
> sorry I didn't understand your answer

this wasn't for you, it was for @Mike1977 



> Yes but this will allow you to travel without taking a tractor for example

Our Waypointsystem it completly different, just don't compare this with AD, if you like how AD course are handled more, then use AD for travel and CP for field.

Compare those 2 total different system and ask us to change it is no help at all....

**Comment by rohne83** [comment]
If this issue really causes troubles for you, but if your course is not too long as a workaround you might instead edit your Courseplay courses with Autodrive.
So sth like the following:
1. load respective courseplay course, drive on it with AutoDrive in recording mode
2. at the end of the course do in AutoDrive: stop recording and give a name to the current waypoint
3. you can now edit all waypoints normally with AutoDrive
4. move vehicle to start of the course, open CP again and refresh the list with your saved courses
5. there should be a directory named 'Autodrive' from where you can now load respective course to the waypoint created in step 2, the waypoints of this course are exactly the same as for the AutoDrive course.
Of course it will only work with normal waypoints. If you need to set crossings, wait points etc you have to edit the waypoints again (not sure whether this works for you). Or you record a new Courseplay course while your vehicle is driven by AutoDrive to the destination.
Afterwards you can delete the AutoDrive waypoints again (or just save your CP course and reload the game without saving, so that the last AD waypoints aren't saved).
Quite time consuming and not really comfortable, but at least it should work ;)
