### ISSUE TITLE
CP is not checking for additional tank (Seedhawk)

### ISSUE THREAD

**Issue by Phil7789** [Courseplay/courseplay#6247]
**Current behaviour:**
When not buying the seeds (menu setting) but having a filled up additional tank e.g. for the Seedhawk CP states that the seeder needs to be filled first.

**Expected behaviour:**
CP checks for additional tanks and uses them for seeding.

currently tested with v6.02 (.00071.dev)

If any additional information is needed please let me know (I couldn't find any similar bug report)

**Comment by Tensuko** [comment]
If you don't want to fertilize, then turn off the fertilizer option in the advaced settings.

**Comment by Tensuko** [comment]
fertilizer on:
![Uploading fsScreen_2020_10_23_18_20_11.png…]()
fertilizer off: (it is unfolding and rdy to go)
![fsScreen_2020_10_23_18_20_20](https://user-images.githubusercontent.com/27344744/97028511-88217280-155c-11eb-8986-5176c971e75a.png)

All done with not buy anything in the ingame menu....

So whats the Problem ?

**Comment by VergylTantor** [comment]
Have you tried this?
Open Courseplay HUD then click on:
Settings
Advanced Settings
Change "Use fertilizer of seeder" to Deactivated.

**Comment by Tensuko** [comment]
It is just working as it should I don't see a CP Issue here.
No Seed, no seeding, if not want to fertilize, deactivated it in the adv settings.
