### ISSUE TITLE
it does not come back from the combine and other problem

### ISSUE THREAD

**Issue by wertigoxxx** [Courseplay/courseplay#6250]
only reverse the tractor from the combine if the trailer is not full!

Once full it doesn't do that!
what can i set up?

there may be some problem with the encoding
please review!!

I don’t want to open a new topic, but I thought I’d share another issue here!

-------------------
**the pathfinder plans the route very close to the edge of the crop!
The round is cut by the combine, they collide!
In practice, this is what it looks like!
![fsScreen_2020_10_21_07_26_30](https://user-images.githubusercontent.com/65092037/97070610-f8220e00-15d9-11eb-9b4d-7b853921b540.png)

thank you for dealing with this problem!

**Comment by Tensuko** [comment]
#5987

**Comment by wertigoxxx** [comment]
Wann kann diese Entwicklung geplant werden?🙂

**Comment by Tensuko** [comment]
Wenn genug Zeit dafür ist :)
When there is enough time for this :)

Actually working on some stuff parallel, improoving it step by step.

**Comment by wertigoxxx** [comment]
Danke für die Auskunft!  Sie können den Mähdrescher auch reparieren, da Sie bei vollem Anhänger nicht warten müssen, bis der Traktor abfährt.  Bis jetzt funktionierte es so, dass der Traktor, wenn er voll war, umgekehrt wurde und der Mähdrescher die Arbeit ersticken konnte.
