### ISSUE TITLE
Abfahrer folgt Drescher, wenn er eine Tasche erstellen wird.

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#6253]
folgendes:
wenn man einen Kurs drischt, z.b.
Vorgewende und Feldmitte "Lands" dann ruft der Drescher den abfahrer erst wenn er eine Tasche "freigedroschen" hat
obwohl der abfahrer füllstand 60% als start eingestellt hat:
![fsScreen_2020_10_25_10_11_55](https://user-images.githubusercontent.com/24860501/97103355-23752d80-16ac-11eb-9281-0eb275da7a88.png)
![fsScreen_2020_10_25_10_11_59](https://user-images.githubusercontent.com/24860501/97103359-2839e180-16ac-11eb-9047-fa2bfdb56dc5.png)
![fsScreen_2020_10_25_10_13_38](https://user-images.githubusercontent.com/24860501/97103361-2c65ff00-16ac-11eb-95db-897d3771462b.png)
![fsScreen_2020_10_25_10_15_28](https://user-images.githubusercontent.com/24860501/97103364-32f47680-16ac-11eb-9cae-410f132a5e02.png)
![fsScreen_2020_10_25_10_15_31](https://user-images.githubusercontent.com/24860501/97103369-3982ee00-16ac-11eb-90ad-22f06a20625c.png)
![fsScreen_2020_10_25_10_16_00](https://user-images.githubusercontent.com/24860501/97103374-4273bf80-16ac-11eb-82b1-ef95cd070b5b.png)
was dann manchmal sehr lange dauert
normal, also wenn der Drescher die pipe nicht in der frucht hat wird der abfahrer bei der % einstellung des abfahrers gerufen.
könnte an das bei den Taschen nicht auch so machen das der abfahrer früher gerufen wird und dann dem Drescher mit etwas abstand folgt bis die Tasche fertig ist?  
lg
andreas

**Comment by Tensuko** [comment]
Sowas in der Art stellen wir uns in Zukunft vor...
Wann und wie das klappen wird, steht aber in den Sternen.

**Comment by Mike1977** [comment]
Aber das gab es doch früher schonmal. Da wurde der Abfahrer bei einer bestimmten einstellbaren Przentzahl gerufen und ist dann richtung drescher gefahren und hat den Drescher während der Fahrt abgetankt. Ich weis allerdings nicht wie lange das nicht mehr geht, denn ich habe CP zum abtanken zuletzt beim 13er genutzt...

**Comment by Tensuko** [comment]
@Mike1977 #5272 und Wiki lesen...

**Comment by wertigoxxx** [comment]
Ich finde das so normal und echt!
Wenn Sie darüber nachdenken, warum sollten Sie dann in die Vegetation gehen?

**Comment by rohne83** [comment]
@Mike1977 das geht jetzt auch immer noch, Fruchtumfahrung ausschalten bei Abfahrer und Drescher und es wird keine Rücksicht auf das Getreide genommen, sondern immer quer durch. Sieht halt alles andere als schön aus und realistisch erst recht nicht. Deswegen gibts ja zum Glück die Fruchtumfahrung, die bis auf ein paar kleine Sachen auch ziemlich gut funktioniert mittlerweile.
Das was andreasthu hier vorschlägt ist ja dann letztlich nur eine "Verbesserung" dieser Fruchtumfahrung, ist aber was völlig anderes als das was "früher" bzw ohne Fruchtumfahrung gemacht wird.

**Comment by andreasthu** [comment]
@wertigoxxx 
Ich meine, der abfahrer soll dem Drescher in dessen Spur folgen, also in dem abgedroschene Streifen, warten derweil der Drescher die Tasche drischt, und dann Vorfahren zum abtanken.
Tensuko hat ja geantwortet, das sie das so vorhaben.
Ich möchte das Getreide nicht wiederfahren.
Lg
Andreas
