### ISSUE TITLE
LUA Fehler - was bedeuten Sie ?

### ISSUE THREAD

**Issue by Makaay1307** [Courseplay/courseplay#6254]
Hallo liebes Team ,
ich hab folgendes Problem ....
ich hab 3 LUA Call Stack Fehler in der LOG und weiß nicht was sie bedeuten . 
Vielleicht können sie mir weiterhelfen, anbei sende ich ihnen die Log.
Für eine Antwort wäre ich sehr Dankbar.
Gruß Chris 
[log.txt](https://github.com/Courseplay/courseplay/files/5434590/log.txt)

**Comment by Tensuko** [comment]
Das könnte ich dir besser erklären, wenn du mir sagst was du gemacht hast, als das auftrat :) 

Aber ich gebe mal eine Vermutung ab:
Hast du an einem Traktor einen Plattformwagen angekuppelt, oder ist sogar eine angekuppelt, als du das savegame geladen hast ?

**Comment by Makaay1307** [comment]
ich hab gestern die neue Version von der Hof Bergmann auf den Server geladen, seitdem besteht der Fehler. 
Ja es stimmt, mein Mitspieler hat einen Plattformwagen am Shop angekoppelt . 
Ich probiere es mal aus und koppel ihn ab 
Danke für die schnelle Antwort

**Comment by Tensuko** [comment]
Dann kommt der Callstack daher, ist aber nicht schlimm, der hat keine Auswirkung.

**Comment by Makaay1307** [comment]
Hab es Probiert, Plattformwagen abgekoppelt....Spiel neu gestartet, und der Fehler ist weg 
Tausend Dank für die schnelle Hilfe 
Gruß Chris
