### ISSUE TITLE
Kurse auf Dedicated Server löschen

### ISSUE THREAD

**Issue by dominik3e** [Courseplay/courseplay#6255]
Moin.
Hab seit gestern nen dedi Server, kann aber ingame keine Kurse mehr löschen. (egal ob Admin oder nicht).

Gibt es dafür eine Lösung außer sie in der xml datei zulöschen?

**Comment by Tensuko** [comment]
Das geht nur wenn du einen FTP zugriff auf deinen Server hast, die Kurse sind dann im gleichen Ordner wie die Savegames (so wie unter \Dokumente\My Games\FarmingSimulator2019\... anders geht as im Moment nicht.
