### ISSUE TITLE
Subsoiler not turning on field when setting is activated.

### ISSUE THREAD

**Issue by Fogest** [Courseplay/courseplay#6256]
I did two headlands around  a wonky field I have. My tractor with a subsoiler kept getting stuck on trees and light posts on the edge of the field as it kept driving off the field trying to turn around instead of turning on the field. A workaround for now will be creating more "around"s on the headland.

Here is a video showing the problem:
https://streamable.com/hibncz

*As a side note, I used the mega strength mod to drag the tractor away from the tree and allow it to resume driving the path it was trying to get to*

**Comment by Fogest** [comment]
For reference I am using the latest release Courseplay for FS19 v6.02.00072.

**Comment by Tensuko** [comment]
logfile with debugchannel 12 and 14 pls.

**Comment by VergylTantor** [comment]
This issue can be helped by going to:
Settings
Advanced settings
Use pathfinding in turns "Activate"
Reversing for pathfinding in turns "Activate"

**Comment by Fogest** [comment]
@VergylTantor Great next time it is time to harvest or something on this field I will give these a shot. 

@Tensuko Would you like the logfile with or without the settings mentioned above turned on? I assume you'd like it with whatever my settings were when I made this report?

**Comment by Tensuko** [comment]
Exact same situation on when it is not happening as you would expect it.

**Comment by Dennizzzzz** [comment]
@VergylTantor I tried the settings you indicate (see #6262) unfortunately without the expected result.

**Comment by masneoquil** [comment]
@Dennizzzzz also make sure "Use AI maneuvers" is deactivated. I had the same issues and deactivating that option solved the problem of the workers turning off field.
With this option deactivated and the 2 option that Tensuko told you to activate, they will start using the headlands to reach the next turn.

**Comment by Tensuko** [comment]
closed due to inactivity
