### ISSUE TITLE
Problem mit Überladewagen 

### ISSUE THREAD

**Issue by Playlord75** [Courseplay/courseplay#6257]
der überladewagen fahrer fährt jetzt zwar immer denn kurs ab heist der alte fehler ist weg aber es gibt ein neues problem der abfahrer hällt nicht mehr am wartepunkt sondern fährt einfach duich

**Comment by Tensuko** [comment]
Mal bitte genauer beschreiben mit Screenshots am besten...

**Comment by Playlord75** [comment]
![fsScreen_2020_10_25_22_40_34](https://user-images.githubusercontent.com/71101944/97119828-222b1b80-1713-11eb-9d8c-111f6a033963.png)
ich glaub das zeigt es am besten das er einfach stumpf weiter fährt ohne langsamer zu werden und zu warten

**Comment by Tensuko** [comment]
#6237
