### ISSUE TITLE
CP/AutoDrive MP - Sprayer does not start to refill after emptying. 

### ISSUE THREAD

**Issue by Pinqdev** [Courseplay/courseplay#6258]
Hi all!

So i used the newest xxxx0072 version yesterday and the sprayer did not attempt to go to the fill point after it was completely empty. 
He was trying to finish his course with a empty tank but the sprayer kept working.. 

Maybe useful info:
- I was host of this mp game
- There was no error log

I'm not sure which debug channel i need to use to give you a nice report log.

Kind Regards

**Comment by Tensuko** [comment]
Did you set the adv. settings to use AD for refill ?
For debug log, channel 6 and 17 might help, not sure.

**Comment by Pinqdev** [comment]
Yes i did set AD. It just keeps spraying not stopping at all when empty. 
Thanks for the debug channels i'm posting a log later.

**Comment by Anonymous-any** [comment]
Got same issue ye refill liquid fertilizer, empty hay, I tried to move AD point destination but unknown to say who of both is implicated for this issue

**Comment by Tensuko** [comment]
closed due to inactivity, also try it out with CP refill, inforum is if that isn't working.
