### ISSUE TITLE
Mode 10 scheint eingestellte Schildbreite zu ignorieren

### ISSUE THREAD

**Issue by ralfmuehle** [Courseplay/courseplay#6260]
Wenn ich in Mode 10 die Schildbreite auf z.B. 10m stelle scheint diese ignoriert zu werden. 
Ausgabe vom Log-Channel:
` [dbg10 lp44504] 1165 MT (#2): Bunker width 26.0, working width 5.8 (passed in)`
eingestellt habe ich 10m

**Comment by Tensuko** [comment]
logfile ?!

**Comment by ralfmuehle** [comment]
[log.zip](https://github.com/Courseplay/courseplay/files/5449710/log.zip)

**Comment by Tensuko** [comment]
Verteilen und verdichten ?
Oder Aufschütten ?

**Comment by ralfmuehle** [comment]
beides, Log-Ausgabe ist die selbe und für beides ein Beispiel im log

**Comment by xerion8300** [comment]
Hab meine Log auch mal dazu gehängt da ich das gleiche Problem beim verdichten habe
[log.txt](https://github.com/Courseplay/courseplay/files/5459868/log.txt)

**Comment by Tensuko** [comment]
Try with Version 6.03.00018 and report 
https://github.com/Courseplay/courseplay/releases

**Comment by Tensuko** [comment]
Schildbreite wird nun koorekt verwendet.
