### ISSUE TITLE
Turn on field not respected with windrowers

### ISSUE THREAD

**Issue by Dennizzzzz** [Courseplay/courseplay#6262]
Using v6.02.00072.dev I still get into trouble when using a windrower on a field that has not much room on the side. 
I do not want to use headlands, and I set the 'turn on field' to 'Activated'.

But still the tractor with windrower is turning outside the field:

![image](https://user-images.githubusercontent.com/10248136/97301466-17c66a00-1858-11eb-84a4-574f4d006666.png)

![image](https://user-images.githubusercontent.com/10248136/97301745-71c72f80-1858-11eb-9dcd-2b22ea34da3c.png)

If I use a seeder, it works how it supposed to work, the tractor will turn on the field.

Used vehicles:
![image](https://user-images.githubusercontent.com/10248136/97301622-46444500-1858-11eb-881b-8efd3b48bf09.png)
![image](https://user-images.githubusercontent.com/10248136/97301636-49d7cc00-1858-11eb-9313-71231756c807.png)
![image](https://user-images.githubusercontent.com/10248136/97301651-4f351680-1858-11eb-87bd-11ce7096227b.png)

Log file:
[log.txt](https://github.com/Courseplay/courseplay/files/5445270/log.txt)

**Comment by Tensuko** [comment]
Guess same Problem here: #6256

**Comment by Dennizzzzz** [comment]
In the related post #6256 @VergylTantor wrote:

> This issue can be helped by going to:
> Settings
> Advanced settings
> Use pathfinding in turns "Activate"
> Reversing for pathfinding in turns "Activate"

I tried this, with no better result:
At the end of the line it does this:
![2020-10-28 12_41_33-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/97431973-87515d80-191b-11eb-8b6b-bf1459393ac7.jpg)

Then for a short moment I see this:
![2020-10-28 12_42_46-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/97432036-a0f2a500-191b-11eb-9615-c73ad50f3c9f.jpg)

After that this:
![2020-10-28 12_42_53-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/97432058-a7811c80-191b-11eb-9de2-cfe69e2bcb22.jpg)

My advanced settings are:
![2020-10-28 12_43_09-Farming Simulator 19](https://user-images.githubusercontent.com/10248136/97432090-b23bb180-191b-11eb-9fb2-9b8b16e03f3a.jpg)

**Comment by Tensuko** [comment]
Closing as duplicate
