### ISSUE TITLE
MP: Arbeitsdauer Anzeige 

### ISSUE THREAD

**Issue by KeineEndeDerLegende** [Courseplay/courseplay#6263]
Wollte nur kurze Frage.
 Im SP kann man sehen wenn Kurse eingestellt ist wie lange der Helfer braucht bis er fertig is mit dem Feldarbeit.. Bei MP zeigt das nicht an wie lang er braucht.. ist das so das er im MP nicht anzeigt nur SP?

LG Chris

**Comment by Tensuko** [comment]
Bin mir gerade nicht sicher warum das so ist.
@schwiti6190 weist du das ?

**Comment by KeineEndeDerLegende** [comment]
wenn kein antwort gibt ist auch nicht schlimm da könnt ihr thema schliessen sogar löschen!

**Comment by Obsiana2019** [comment]
@KeineEndeDerLegende nur Geduld, eine Antwort dauert halt ab und an @schwiti6190 hat sicherlich auch noch mehr zu tun. Aber dennoch würde mich das Thema und eine Antwort auch interessieren. Glaube aber das Autodrive auch keine berechnete Zeit im MP anzeigt. Daher vermute ich mal das das auf einem Server nicht so einfach ist.

lg Obsiana

**Comment by KeineEndeDerLegende** [comment]
ist okay dann lass ma thema offen bis einer was sagt warum so ist dann ist halt so.. es ist ja keine Beschwerde sondern mir ist aufgefallen😅

**Comment by schwiti6190** [comment]
@KeineEndeDerLegende Erstmal danke für das Feedback. Es fehlt offensichtlich die synchronisation vom server zu client.

Dieses ist aber aktuell keine Priorität also kann es dauern bis ich mir das mal genauer anschau. 

David

**Comment by KeineEndeDerLegende** [comment]
@schwiti6190  alles klar kein ding.. mach ruhig.
