### ISSUE TITLE
Combi button not avaliable with trailers

### ISSUE THREAD

**Issue by DrssaFerri** [Courseplay/courseplay#6265]
I have a lot of trilers and all my mod once, that are not able to Combi. The Driving mode is not avaliable or lighted so i cannot use it!

**Comment by Tensuko** [comment]
Mod Issue.

**Comment by DrssaFerri** [comment]
sorry mod witch mode? courseplay or my trilers mods?

**Comment by Tensuko** [comment]
Your Trailers. Check Vanilla one and compare whats needed.
I use several Mod Trailer with CP and have no problem at all.

**Comment by DrssaFerri** [comment]
i just made a test, i modify an ingame vanilla trailer increasing just the capacity. When i started the game it was ok, after exit the game once and reentering again no Comby option.... so the courseplay app looks for capacity and if it is high it disable it?
________________________________
De: Tensuko <notifications@github.com>
Enviado: jueves, 29 de octubre de 2020 08:07
Para: Courseplay/courseplay <courseplay@noreply.github.com>
Cc: DrssaFerri <lorebacca@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [Courseplay/courseplay] Combi button not avaliable with trailers (#6265)


Your Trailers. Check Vanilla one and compare whats needed.
I use several Mod Trailer with CP and have no problem at all.

**Comment by Tensuko** [comment]
What means high capacity ?

**Comment by DrssaFerri** [comment]
just increased the capacity of a trailer from 21.000lt to 50.000lt
________________________________
De: Tensuko <notifications@github.com>
Enviado: jueves, 29 de octubre de 2020 10:08
Para: Courseplay/courseplay <courseplay@noreply.github.com>
Cc: DrssaFerri <lorebacca@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [Courseplay/courseplay] Combi button not avaliable with trailers (#6265)


What means high capacity ?

**Comment by Tensuko** [comment]
There must be more wrong then just this, maybe reload vehicle can help (easydevtools just do a normal reload)
