### ISSUE TITLE
Offloading Comines Issues

### ISSUE THREAD

**Issue by TDFS19** [Courseplay/courseplay#6267]
Hi
I have found a few problems with offloading combines both in Mode 2 & Mode 3
If I am doing something wrong, I would appreciate some advice.

**Mode 2** 
1.	When harvesting a big field with several combines and several Tractors
The harvester request driver but the tractor just stands still and will not start 
Both are set to avoid fruit and it seems the tractor does not find a valid path?
I have tried both Distance and fill level on the Combine driver priority but see no difference
It behaves slightly better when switching off avoid fruit, but that usually ends up with the tractor crashing front to front with the selected combine. 
 
2.	When a combine unloads while driving and the tractor gets full, the tractor does not wait until the combine is gone, but takes a wide turn into the combine and crashes with the combine.

3.	If 2 combines call the same tractor simultaneously and the tractor gets full after combine no.1 the combine No.2 still waits for the same tractor and does not call for a new and available tractor. The tractor goes away to empty then come back in the que behind the other tractors and can’t get free until the tractor in front gets called out.

**Mode 3**
1.	The overloading is difficult because the tractor keeps overshooting it’s waiting point for the waiting truck, only way to solve is to have a rally long trailer on the truck.

2.	If the receiving truck is full and drive off, the tractor continues its route to get ready for combines again even with an almost full overload trailer. It would be more realistic if the tractor could wait for the next truck to totally empty before continuing.

3.	If the receiving truck have a setting to Drive on at: 85% it drives off even before the loading operation is finished.
In CP 5 (FS2017) it always waited until the loading operation was finished even if reaching its % level

**Comment by Tensuko** [comment]
All known problems and already have Issues for those.
Beside that, not a single logfile... #5272
