### ISSUE TITLE
übergang vom Vorgewende zu den feldreihen - leider immer noch

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#6268]
Hallo leute
leider klappt das selbst mit  v073 immer noch nicht reibungslos:
ausgangslage: 1x rundum + scharfe kanten
![fsScreen_2020_10_30_13_42_06](https://user-images.githubusercontent.com/24860501/97707540-b7cdfe80-1ab7-11eb-8477-c5df9596bc79.png)

anfahrt zum Übergang:
![fsScreen_2020_10_30_13_49_30](https://user-images.githubusercontent.com/24860501/97707674-e9df6080-1ab7-11eb-8837-513deaa0cd0b.png)

die rechtskurve sieht gut aus:
![fsScreen_2020_10_30_13_49_35](https://user-images.githubusercontent.com/24860501/97707730-febbf400-1ab7-11eb-82c9-02cca249812e.png)
![fsScreen_2020_10_30_13_49_37](https://user-images.githubusercontent.com/24860501/97707762-0d0a1000-1ab8-11eb-87f9-574ff228fa6d.png)

aber dann: (schwenk nach links)
![fsScreen_2020_10_30_13_49_42](https://user-images.githubusercontent.com/24860501/97707904-43e02600-1ab8-11eb-90ff-a0ed00b9008a.png)
![fsScreen_2020_10_30_13_49_46](https://user-images.githubusercontent.com/24860501/97707915-46428000-1ab8-11eb-9001-7a496da8b31d.png)

ein stück rückwärtsfahren:
![fsScreen_2020_10_30_13_50_08](https://user-images.githubusercontent.com/24860501/97708027-67a36c00-1ab8-11eb-95dc-7b4e187a4468.png)
![fsScreen_2020_10_30_13_50_18](https://user-images.githubusercontent.com/24860501/97708035-6bcf8980-1ab8-11eb-8813-e5a176542a6c.png)

und wieder nach vorne:
![fsScreen_2020_10_30_13_50_24](https://user-images.githubusercontent.com/24860501/97708106-8c97df00-1ab8-11eb-9d09-1ce3270a39f9.png)
![fsScreen_2020_10_30_13_50_28](https://user-images.githubusercontent.com/24860501/97708116-90c3fc80-1ab8-11eb-84ca-3ac4477ce691.png)
![fsScreen_2020_10_30_13_50_31](https://user-images.githubusercontent.com/24860501/97708128-94578380-1ab8-11eb-9dbe-2423a2ab9d9e.png)
![fsScreen_2020_10_30_13_50_36](https://user-images.githubusercontent.com/24860501/97708142-9883a100-1ab8-11eb-9e6a-8e173848b068.png)
![fsScreen_2020_10_30_13_50_42](https://user-images.githubusercontent.com/24860501/97708153-9c172800-1ab8-11eb-9e17-a0688133c522.png)

diesmal hat es sogar geklappt und er kann weitersäen
![fsScreen_2020_10_30_13_51_02](https://user-images.githubusercontent.com/24860501/97708159-a0434580-1ab8-11eb-848b-92ae5bbba018.png)

meist verfranzt er sich aber und fährt endlose kreise
das selbe bei düngen, grubbern,..
Dreschen geht halbwegs da der Drescher ja kein angehängtes Gerät zieht 

bei Kursen mit weichen Ecken geht es problemlos
lg
andreas

**Comment by Roby1164** [comment]
I think the problem is in the tractor, I with another model, and the same seeder, I have never had this problem, with or without perimeter. That's an articulated tractor, and a lot of problems, even with Autodrive and other automatic guides.

**Comment by Tullsa** [comment]
> 
> 
> Hallo leute
> leider klappt das selbst mit v073 immer noch nicht reibungslos:
> ausgangslage: 1x rundum + scharfe kanten
> ![fsScreen_2020_10_30_13_42_06](https://user-images.githubusercontent.com/24860501/97707540-b7cdfe80-1ab7-11eb-8477-c5df9596bc79.png)
> 
> anfahrt zum Übergang:
> ![fsScreen_2020_10_30_13_49_30](https://user-images.githubusercontent.com/24860501/97707674-e9df6080-1ab7-11eb-8837-513deaa0cd0b.png)
> 
> die rechtskurve sieht gut aus:
> ![fsScreen_2020_10_30_13_49_35](https://user-images.githubusercontent.com/24860501/97707730-febbf400-1ab7-11eb-82c9-02cca249812e.png)
> ![fsScreen_2020_10_30_13_49_37](https://user-images.githubusercontent.com/24860501/97707762-0d0a1000-1ab8-11eb-87f9-574ff228fa6d.png)
> 
> aber dann: (schwenk nach links)
> ![fsScreen_2020_10_30_13_49_42](https://user-images.githubusercontent.com/24860501/97707904-43e02600-1ab8-11eb-90ff-a0ed00b9008a.png)
> ![fsScreen_2020_10_30_13_49_46](https://user-images.githubusercontent.com/24860501/97707915-46428000-1ab8-11eb-9001-7a496da8b31d.png)
> 
> ein stück rückwärtsfahren:
> ![fsScreen_2020_10_30_13_50_08](https://user-images.githubusercontent.com/24860501/97708027-67a36c00-1ab8-11eb-95dc-7b4e187a4468.png)
> ![fsScreen_2020_10_30_13_50_18](https://user-images.githubusercontent.com/24860501/97708035-6bcf8980-1ab8-11eb-8813-e5a176542a6c.png)
> 
> und wieder nach vorne:
> ![fsScreen_2020_10_30_13_50_24](https://user-images.githubusercontent.com/24860501/97708106-8c97df00-1ab8-11eb-9d09-1ce3270a39f9.png)
> ![fsScreen_2020_10_30_13_50_28](https://user-images.githubusercontent.com/24860501/97708116-90c3fc80-1ab8-11eb-84ca-3ac4477ce691.png)
> ![fsScreen_2020_10_30_13_50_31](https://user-images.githubusercontent.com/24860501/97708128-94578380-1ab8-11eb-9dbe-2423a2ab9d9e.png)
> ![fsScreen_2020_10_30_13_50_36](https://user-images.githubusercontent.com/24860501/97708142-9883a100-1ab8-11eb-9e6a-8e173848b068.png)
> ![fsScreen_2020_10_30_13_50_42](https://user-images.githubusercontent.com/24860501/97708153-9c172800-1ab8-11eb-9e17-a0688133c522.png)
> 
> diesmal hat es sogar geklappt und er kann weitersäen
> ![fsScreen_2020_10_30_13_51_02](https://user-images.githubusercontent.com/24860501/97708159-a0434580-1ab8-11eb-848b-92ae5bbba018.png)
> 
> meist verfranzt er sich aber und fährt endlose kreise
> das selbe bei düngen, grubbern,..
> Dreschen geht halbwegs da der Drescher ja kein angehängtes Gerät zieht
> 
> bei Kursen mit weichen Ecken geht es problemlos

Hallo Andreas habe mir deinen Eintrag durch gelesen, zu den Probleme mit der Feldarbeit.
Nach dem lesen sind mir mehre Punkte eingefallen.
1. Verwende mal 2 Vorgewende oder mehr.  Ist auch von den Leuten von Courseplay empfohlen worden.
2. Ist der Traktor aus dem Modhup also von Giants freigeben? ( Fehlerfrei) Oder ein Mod ? Nicht jeder Mod kann auch mit Courseplay arbeiten Das war schon im LS17 so.  Traktoren mit Knicklenkung sind auch nicht immer die erste Wahl.
3. Auch das Sägerät ist das von Giants frei geben( Fehlerfrei) oder wieder ein Mod. Auch hier nur weil es gut aus sieht muss es nicht 100% mit Courseplay arbeiten können.
Wenn Arbeitsgreäte nicht mit 100% mit Courseplay arbeiten können musst du den Modder fragen wieso es nicht läuft, es muss nicht an Courseplay liegen. Da andere Arbeitsgreäte ja ohne Probleme ja laufen.

Zu deinen Bildern es wäre Klasse gewesen wenn du  das Problem mit verschieden Arbeitsgeräten( Traktoren/ Sägeräten) uns gezeigt hättest. Um zu sehen ob es immer vorkommt oder nur bei dieser Geräte wahl.

**Comment by andreasthu** [comment]
@Tullsa 
haben wir doch schon:
https://github.com/Courseplay/courseplay/issues/6067
https://github.com/Courseplay/courseplay/issues/6243

**Comment by pvaiko** [comment]
So, wie sieht es mit 74 aus?

**Comment by andreasthu** [comment]
hallo pvaiko
es klappt nun, habe keine gröberen fehlfahrten gefunden.
werde es aber heute und morgen noch genauer testen
(bitte noch nicht schliessen)
lg
andreas

**Comment by Tensuko** [comment]
@andreasthu 
Konntest du schon weitere tests machen, so das wir dieses Issue zu machen können ?
#6067 bleibt weiterhin auf wegen eventuellen Verbesserungen, aber wir brauchen ja keine 2 Issues, wichtig ist, dass es erstmal klappt :)

**Comment by andreasthu** [comment]
Ach mist da war doch noch was....
Sorry @Tensuko 
Bin diese Woche in Krankenhaus, hatte Dienstag eine Wirbelsäulen OP und liege seitdem flach.
Werde die nächsten Tage nicht mehr zum spielen und Testen kommen.
Aber ja, vorige Woche hat es grundsätzlich funktioniert.
Danke.
Lg
Andreas

**Comment by Tensuko** [comment]
@andreasthu 
Ok dann mache ich hier erst mal zu und wünsche dir alles Gute für deine Genesung :)
