### ISSUE TITLE
CP bei Gamestart nicht finden

### ISSUE THREAD

**Issue by BaWi1404** [Courseplay/courseplay#6269]
Hallo zusammen,

seit der V6.02.00069 und auch in der Vxx.xxx70 kann ich beim Spielstart egal, ob SP oder MP, CP nicht mehr finden. Es wird in der Liste nicht mehr angezeigt.

Ich habe in dem My Games\mods ALLE Mods entfernt, bis auf CP. Nach wie vor ist CP nicht in der Modauswahl zu finden.

Wenn ich jedoch über ModHub bei installierten Mods nachschaue, steht CP V6 drin in der oben genannten Versionsnummer.

Grüße BaWi1404

**Comment by Tensuko** [comment]
logfile ?! (und wieder muss ich erst danach fragen...)

**Comment by BaWi1404** [comment]
Ich glaube habe es selber gesehen. Habe es um es vergleichen zu können die Versionssnummer hinter geschrieben
Ich teste mal

**Comment by BaWi1404** [comment]
Es war der Fehler, meine eigene Dummheit. Sorry

**Comment by Tensuko** [comment]
Erstmal, log.txt einfach mit der Maus in die Kommentarbox ziehen, bitte nicht den Inhalt kopieren.
Und zum .zip file...
Mach es dir nicht zu kompliziert:
https://github.com/Courseplay/courseplay/releases

.zip Runter laden, in den mods Ordner, fertig.
Kein Entpacken, kein umbenennen.
