### ISSUE TITLE
Mode 1 infinite route.

### ISSUE THREAD

**Issue by stevewarshaw** [Courseplay/courseplay#6271]
I am not sure this is the right place. I've searched Google for the answer but cannot seem to find it. Is there a way to make mode 1 load and unload a fill type more than 20 times. Ideally Infinite until the silo is empty?

Sorry if this is the wrong place to ask.

**Comment by Tensuko** [comment]
Right place, but we decided to put ti to 20 for now as maximum to not make things to complicated.
You can scroll the number up again any time while it is running, or take a bigger trailer.
