### ISSUE TITLE
Erntemaschinen im Fahrverband

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#6272]
Ich habe im Arbeitsmodus 3 Drescher im Fahrzeugverband. Beim Verband stelle ich beim 1 Drescher: ein in Fahrtrichtung auf der Linie links, beim 2 Drescher hinten und beim 3 Drescher rechts. Der 1 und 2 Drescher fährt die Bahn längst nur der 3 bleibt stehen und macht nichts mehr.
Hat in den vorigen Versionen immer sehr gut funktioniert nur jetzt nicht mehr
[log.txt](https://github.com/Courseplay/courseplay/files/5463674/log.txt)
![Unbenannt](https://user-images.githubusercontent.com/47453761/97732410-c841a180-1ad6-11eb-92ae-d5ec3ed355ce.png)

**Comment by Tensuko** [comment]
Kurs nicht an der Ecke starten...

**Comment by Hendirk** [comment]
Alles klar danke für die Info

**Comment by Tensuko** [comment]
Bitte ausprobieren (gerne noch mal den Kurs zeigen) und rückmelden, sonst müssen wir schauen was los ist und dann brauchen wir nen logfile mit debugchannel 7, wenn du den Fahrer startest.

**Comment by Hendirk** [comment]
Frage: Was heißt Debugchannel 7

**Comment by Tensuko** [comment]
CP HUD Settings unten die 7 grün machen.

**Comment by Tensuko** [comment]
Closed due to inactivity.
