### ISSUE TITLE
Courseplay on Mac Won't Load At All!

### ISSUE THREAD

**Issue by RADICALAdrift** [Courseplay/courseplay#6273]
Hi There, my friend has an issue with courseplay and the fact it just doesn't show up in-game as an installed mod and can't select it on the select mods screen he has tried versions 6.02.00070, 00071, 00072, 00073, and of course the current latest version 00074 just none of them will load on the latest game version (1.6.0.0), i can share the mod list as i use the same ones as he does if need be, i could see if he can pass me a game log if that's more help?

**Comment by Tensuko** [comment]
Always need a logfile...

**Comment by RADICALAdrift** [comment]
i'll post a logfile here as soon as i can since my friend is over in America

**Comment by RADICALAdrift** [comment]
here's the log file https://pastebin.com/quiGh3w3, had a look through and i can't see it mentioned in the log anywhere, they have also tried the mod on it's own and named FS19_Courseplay.zip

**Comment by RADICALAdrift** [comment]
Here's the log file: [log.txt](https://github.com/Courseplay/courseplay/files/5469885/log.txt)
had a look through and i can't see it mentioned in the log anywhere, they have also tried the mod on it's own also named it FS19_Courseplay.zip

**Comment by Tensuko** [comment]
Version: 1.5.2.0 b7027

Update the game maybe ?!

Also I don't see courseplay in mod list....

download .zip only from here and only place the .zip file in mods folder, done, nothing more!
https://github.com/Courseplay/courseplay/releases

**Comment by RADICALAdrift** [comment]
forgot to mention version in the log is wrong, their game is on 1.6.0.0 ill tell them to try the latest update if still doesn't load then im lost
