### ISSUE TITLE
Mode 9 mit Frontlader geht nicht

### ISSUE THREAD

**Issue by tomy852** [Courseplay/courseplay#6274]
Hi, Ich kann das Fahrsilo nicht mit dem Frontlader entleeren. Er fährt los, füllt die Schaufel aber erkennt scheinbar nicht wenn Sie voll ist. Er fährt einfach gerade weiter bis ans Siloende und meldet das Silo sei leer.
Mit einem Radlader geht es problemlos. 
Ich hab den Debug Chanel 10 laufen lassen.

[log.txt](https://github.com/Courseplay/courseplay/files/5469362/log.txt)

Mfg

**Comment by Tensuko** [comment]
Du hast nen Callstack in deiner LOG, irgendwas mit Seasons.

Wegen Schaufelmodus, butte einmal debugchannel 1 2 und 10 und den Frontlader laufen lassen.

**Comment by tomy852** [comment]
Danke für deine Antwort,
tja wie soll ich sagen, einmal Spiel neu gestartet und plötzlich funktioniert es. Ich kann den Fehler nicht mehr herbeiführen... 
Das einzige seltsame ist das der Frontlader extrem ruckelig zum Silo fährt aber sonst läuft es.

Seasons hab ich zwar im Modordner aber nicht aktiv auf diesem Spielstand. 

[log.txt](https://github.com/Courseplay/courseplay/files/5469640/log.txt)

**Comment by Tensuko** [comment]
Nun ist der Callstack mit GC, also das hat wenig mit CP zu tun, wüsste nicht warum das nicht klappen sollte, aber da der Fehler nun weg ist mache ich hier wieder zu.
