### ISSUE TITLE
Round baller  and 2 courses issue (2 separate problems)

### ISSUE THREAD

**Issue by Miketeg** [Courseplay/courseplay#6275]
Hi, was playing yesterday and I ran into 2 problems : 

1 : When using a roundbaler, CP will accelerate forward (+ around 5 mph) and will drop the bale without stopping. It leaves long stretch of straw on the ground. It should stop, reverse a little, open the door, drop, close the door, continue.

2 : When using a forage Wagon in a field on a course + having another course linker to dump straw to the farm, CP will restart course in the field at point 1, instead of continuing where it was before leaving to go to the farm. 

Hope the second point is clear...english isn't my first language, doing my best here.

Thanks
[log.txt](https://github.com/Courseplay/courseplay/files/5469443/log.txt)

**Comment by Tensuko** [comment]
Both Issues should have been solved already, I have no Idea why you got them now, my driver continue where it left the course.
Baler haven't left anything behind.
Would have to chack all your mods that modifie driving or baler handling.
Try it out without mods and report.

**Comment by Miketeg** [comment]
You're right, it seems to be caused by a mod. Will try to find it. No issue when playing vanilla + CP + vehicule control addon. So it's something else.

You can close it / delete it.
