### ISSUE TITLE
Problem mode 9

### ISSUE THREAD

**Issue by iEBPO** [Courseplay/courseplay#6277]
Hello! I just can’t make me thrombus normally in the silo. Any technique constantly collides with the walls of the bunker. Maybe I missed something when setting up?

ver. 6.02.00075

![Farming Simulator 19 Screenshot 2020 11 01 - 11 01 58 32](https://user-images.githubusercontent.com/60730333/97795658-c260d300-1c32-11eb-9139-b5b70b3002d2.png)
![Farming Simulator 19 Screenshot 2020 11 01 - 11 04 33 25](https://user-images.githubusercontent.com/60730333/97795661-cdb3fe80-1c32-11eb-9feb-4bdd554d86f9.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5470240/log.txt)

**Comment by Tensuko** [comment]
#6174
