### ISSUE TITLE
Feldhäcksler von ITS -Coursplay 6.02.00074

### ISSUE THREAD

**Issue by robjana** [Courseplay/courseplay#6278]
Guten Tag zusammen,
ich wollte in LS 19 den Feldhäcksler von ITS einsetzen, wenn ich Coursplay installiert habe, funktioniert es leider nicht, nehme ich Courseplay heraus, kann ich den ITS Häcksler istallieren.

Kann mir vielleicht jemand helfen, wäre sehr nett.

**Comment by Tensuko** [comment]
Was auch immer der ITS ist, was auch immer nicht funktioniert, wie auch immer dein logfile aussieht...
Mehr Information wäre hilfreich, obwohl ich dir schon gleich sagen kann, dass wir nicht jede Mod unterstützen...

**Comment by TobiHH78** [comment]
Gehe mal davon aus, dass er den meint. Von ITS gibt es jedenfalls nur einen...

https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=151783&title=fs2019

**Comment by Tensuko** [comment]
Wenn es mal genauere Infos geben würde.... mods installiert man nicht wirklich, entweder sie sind da oder nicht....

**Comment by robjana** [comment]
Guten Abend,
danke für die Rückinfo, leider bin ein Amateur und Sorry für meine Erklärung, muss leider zugeben das ich nicht weis wie ich an die Protokolldatei komme.
TobiHH78 hat den Mod gefunden ist im Modhub. Der Mod ist im Shop verfügbar, lädt aber nicht wenn Coursplay 6.02.00074 installiert ist. Habe mal eine ältere Version genommen Bsp. 6.01.xxxx da hat es funktioniert.

**Comment by Tensuko** [comment]
Das nützt aber auch nichts, ich brauche die logdaten.
Am besten wenn du versuchst hast ihn zu kaufen im shop oder wie auch immer, aber mit aktueller Version, damit ich den Fehler sehe.
Logdatei (log.txt) ist hier:
...\My Games\FarmingSimulator2019
und die Datei per drag and drop in die Kommentarbox ziehen.

**Comment by robjana** [comment]
Hallo zusammen,
anbei Logdatei, habe mal den letzten Stand genommen, habe auch schon getestet mit vielen oder wenige
Mods mit dem gleichem Ergebnis
[log.txt](https://github.com/Courseplay/courseplay/files/5483222/log.txt)

Danke für die Hilfe.

**Comment by Tensuko** [comment]
Updaten, die Version hat nen bug:
(Version: 1.0.0.0) FS19_addon_strawHarvestBonus

Und die goldene Regel:
Immer nur eine Map im mods-Ordner.

Trotzdem sehe ich hier kein Error wenn versucht wird das Fahrzeug zu lden/kaufen...

**Comment by robjana** [comment]
Hallo Tensuko, danke für deine Rückinfo und Hilfe, werde den Tip beherzigen und werde updaten.

**Comment by robjana** [comment]
Hallo Tensuko, danke für deinen Tip, benötige aber noch den Tip wo kann ich den Update herunterladen. Für das Strohbergung Addon habe ich den Update gefunden für den Bonus nicht. Habe heute das addon Stroh Harvest und Bonus entfernt, leider hat sich  nichts verändert, nur wenn ich Coursplay im Spiel deaktiviere, wird er hochgeladen,

**Comment by robjana** [comment]
Hallo Tensuko, Habe heute das Addon Stroh Bergung und Bonus aus dem Mod Ordner herausgenommen, der ITS Häcksler ist auswählbar aber er lädt nicht hoch im Shop, deaktiviere ich Coursplay lädt der ITS Häcksler im Shop hoch.

**Comment by robjana** [comment]
Hallo Tensuko,
Sorry habe den Update für Bonus Straw Harvest gefunden, dank dem Hinweis von Tensuko. Habe den Test mit dem Häcksler von ITS mit einer älteren Coursplay Version gemacht, mit Version 6.01.000397 wurde dieser auch im Shop hochgeladen. Vielleicht kann mir jemand helfen an wenn ich  mich wenden kann, danke vorab.

**Comment by Tensuko** [comment]
Das Problem ist einfach das manuelle Rohr bei dem ITS Häcksler.
Wir modifizieren Häcksler, damit diese weiter wergen können und das könnte im Konflikt mit dem stehen.
Daher werde ich das hier als Mod Issue zu machen, wir werden kaum Probleme erstellen, nur damit ein Häcksler funktioniert.
Nimm sonst den normale JD Häcksler, statt den ITS.

Und klar das es mit der alten Version geht, mit der Version gab es die Änderung für Häcksler noch nicht.
