### ISSUE TITLE
Abfahrer vom Feldhäcksler fährt ein Stück zurück wenn voll

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#6280]
Abfahrer vom Feldhäcksler fährt ein Stück zurück wenn voll,
daher kollidiert er manchmal mit dem folgenden Abfahrer:
![fsScreen_2020_11_01_14_28_41](https://user-images.githubusercontent.com/24860501/97804279-1083cf80-1c4f-11eb-927f-3ca5dffd5ba4.png)
![fsScreen_2020_11_01_14_28_43](https://user-images.githubusercontent.com/24860501/97804281-14afed00-1c4f-11eb-9bc8-a5ba740d7bc3.png)
![fsScreen_2020_11_01_14_28_47](https://user-images.githubusercontent.com/24860501/97804283-18437400-1c4f-11eb-93ea-849c6df1ba3d.png)
![fsScreen_2020_11_01_14_28_51](https://user-images.githubusercontent.com/24860501/97804285-1c6f9180-1c4f-11eb-8739-af57568586bd.png)
![fsScreen_2020_11_01_14_28_55](https://user-images.githubusercontent.com/24860501/97804289-21ccdc00-1c4f-11eb-83ef-ab88c20c1de8.png)
![fsScreen_2020_11_01_14_28_58](https://user-images.githubusercontent.com/24860501/97804291-285b5380-1c4f-11eb-8a6b-138b786a6d0d.png)
![fsScreen_2020_11_01_14_29_00](https://user-images.githubusercontent.com/24860501/97804295-2d200780-1c4f-11eb-8052-987652ab0830.png)
![fsScreen_2020_11_01_14_29_04](https://user-images.githubusercontent.com/24860501/97804304-34dfac00-1c4f-11eb-9f4c-1ba50374f6e6.png)
![fsScreen_2020_11_01_14_29_09](https://user-images.githubusercontent.com/24860501/97804309-39a46000-1c4f-11eb-835f-cb14a4beec29.png)
![fsScreen_2020_11_01_14_29_12](https://user-images.githubusercontent.com/24860501/97804317-3e691400-1c4f-11eb-9590-881c7c167a92.png)

meiner meinung nach könnte der häcksler abfahrer normal nach vorne wegfahren.
lg
andreas

**Comment by Tensuko** [comment]
Das ist auch richtig so und 2 Abfahrer werden noch nicht unterstützt.

Das Rückwärts fahren ist in einigen Situationen nötig, das haben wir nicht umsonst eingebaut.
