### ISSUE TITLE
Compacting and Leveling: Wrong Tool for this mode

### ISSUE THREAD

**Issue by gSe7eN** [Courseplay/courseplay#6283]
See issue  #5612

When setting up a leveling and compacting path and executing, at times I get "wrong tool for this mode" error. I've used multiple tractors. I'm using the 5 meter leveling blade trying on front and back and changing many parameters in CP.

Additionally, I've set up my paths exactly as I've seen on YouTube and I get completely unexpected results which may or may not be included in this issue. I've yet to successfully get leveling and compacting working.

I'm on CP ver 6.x.75.dev released about 4 days ago from GitHub.

**Comment by Tensuko** [comment]
Blades and Shields are not use for leveling and compacting as right now.
Shields are only used at the back of a tractor and only used for 'filling up' mode of mode10.

**Comment by gSe7eN** [comment]
What is a "blade and shield" because I'm fairly sure I didn't know my tractors needed a shield or sword as I don't play PVP.

**Comment by Tensuko** [comment]
Blades are some kind of thing metal plate as well.
Not those RPG Blades :p 

But still, those Shields to push the chaff is right now only for filling up (mostly used in U shaped silos).
Those Rolls and spreaders should work for compacting and leveling.

We will have to do some more work on Mode10 later and then we will see if we can manage the Tools better for this mode.
