### ISSUE TITLE
un and uploading issues with double trailer

### ISSUE THREAD

**Issue by Thermodynamicus** [Courseplay/courseplay#6284]
Hey,

so my problem is that I used CP on fs17 and it all worked fine even with double, triple and quad trailers but I realised that this isnt working in fs19. I'm currently using CP V 6.01.00397.dev. I'm using some mods but none trailer mods at least I haven't bought one in the shop. I know there is a file to show what is not working etc but I don't know where I can find it.

And all my respect to the makers of CP. It helps a lot playing by myself. Thanks a lot. And thanks to those who help me with my problem.

**Comment by Thermodynamicus** [comment]
I also tried the newest version of CP but it didnt work either.

**Comment by Tensuko** [comment]
Depends what loading and unloading you talk about...
But I guess Mode2, for that, read Wiki Page and #5272 
Only one Trailer to unload any kind of combine.
