### ISSUE TITLE
:57: attempt to call method 'is_a' (a nil value) Error running LUA method 'update' 

### ISSUE THREAD

**Issue by jsteph262** [Courseplay/courseplay#6285]
After purchasing a vehicle on the modded map podnoszenie, I get the error in the title repeatedly. I also lose control of any keyboard function. Ive tried it on a few different versions of courseplay and they all had the issue. I am playing with other mods as well but I was able to replicate with only courseplay enabled with no other mods.

[log.txt](https://github.com/Courseplay/courseplay/files/5490783/log.txt)

**Comment by jsteph262** [comment]
I deleted my course folder for the map after seeing issue #6281  and the issue was resolved so I would assume its something similar.

**Comment by enderwiggin07** [comment]
My issue was similar, bought a new vehicle (official DLC mod), controls messed up trying to load the road course to drive it home, had to force quit the game then couldn't load back into the save until deleting the courses.

**Comment by Tensuko** [comment]
When this happens with other Version it is not related with #6281 

What about .00075 ?

(Version: 6.02.00072) FS19_Courseplay

**Comment by jsteph262** [comment]
Yep, still happened on .0075. I initially had the issue with that version then changed versions to see if it had any affect. Im 90% sure the error that came up in the log was identical.

**Comment by Tensuko** [comment]
I rly have no Idea what happens here.
I will have to make some more tests with Version .00075 and see whats going up.

**Comment by Tensuko** [comment]
Can you try the exact same thing with Version .00074 ?

**Comment by jsteph262** [comment]
Yea, I'll restore my old course folder and try to reproduce with .00074 after work later today.

**Comment by Tensuko** [comment]
I rly have no clue why it should be related, but try it with .00076 pls

**Comment by jsteph262** [comment]
Had the issue on both .00074 and .00076. Same error, both logs attached. I also attached my course folder for the map in case that would at all be helpful

[.00076 log.txt](https://github.com/Courseplay/courseplay/files/5497744/log.txt)

[.00074 log.txt](https://github.com/Courseplay/courseplay/files/5497750/log.txt)

[FS19_Przemasowo.SampleModMap.zip](https://github.com/Courseplay/courseplay/files/5497754/FS19_Przemasowo.SampleModMap.zip)

**Comment by Tensuko** [comment]
If this happens with 00074 or 00076 it is not a course Issue.

**Comment by jsteph262** [comment]
If there's something else you want me to try or if you need some more info on something let me know. I just thought it would be course related since the issue went away once I deleted the course folder and started making new courses. Not really sure what else it could be related to.

**Comment by enderwiggin07** [comment]
Version 76 fixed the issue of saving the coursemanager xml, but it can't rehabilitate the broken xml file.  You've got 4 folders that aren't saved in your coursemanager.xml file.  

You have a couple of options, you can dump your course files again and start with new courses on version 76, or you can make the references to the folders in the xml file yourself if you want to keep your saved courses.  

If you make your coursemanager.xml file look like this, you should be fine to load your save and with version 76 will not experience the same error again.  I made some assumptions about what your folders would be called but you can change that 

![image](https://user-images.githubusercontent.com/50051834/98318627-a0ee4700-1fa4-11eb-872b-7d25241e4784.png)

**Comment by enderwiggin07** [comment]
Sorry I missed one, you actually also have 5 folders, so make another folder id="5" for your field 22 courses.

Another option you could do is to remove the "parent="?"" from every line and this would have the effect of dumping all your courses to the top level and you can make new folders in game.

**Comment by jsteph262** [comment]
I didn't have anything special in those courses so I'll just end up dumping them and making new ones. Thanks for the fix though, appreciate it.

**Comment by Tensuko** [comment]
Ok nice so this is fixed.
