### ISSUE TITLE
Kursverwaltung - Ordner werden nicht gespeichert

### ISSUE THREAD

**Issue by alfahundert** [Courseplay/courseplay#6290]
Ich habe mit der letzten Version (v6.02.00075) festgestellt, dass nach einem Neustart des Spiels, meine angelegten Ordner alle gelöscht sind.
Die Kurse werden dann zwar noch angezeigt auf Ebene 0, sind aber teilweise dann "corrupted".
Im Log taucht auch kein Fehler oder Ähnliches auf.
In der courseManager.xml werden auch die Elemente für die Folder nicht geschrieben. Die Zuordnungen von Kursen zu den Ordnern werden jedoch eingetragen via ID, Parent und Level.

Spieltand wurde neu begonnen mit dem neuesten Release (v6.02.00075).
Funktioniert hat es bei mir zuletzt mit Version v6.02.00072

**Comment by Tensuko** [comment]
Was heist zuletzt mit 00072 ?
00073 und 00074 gehen nicht ?
logfile will ich trotzdem sehen!

**Comment by alfahundert** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5493526/log.txt)

Ist das Log nach dem Restart, bei dem die Ordner dann gelöscht sind und alle in Ordnern befindlichen Kurse als corrupted angezeigt werden.

Als ich zuletzt mit 00072 gespielt habe, hatte dies funktioniert. Als ich dann auf Version 00075 gegangen bin, nicht mehr.

Ich teste mal die Zwischenreleases auch noch.

**Comment by alfahundert** [comment]
mit der Version 00074 geht alles problemlos

**Comment by Tensuko** [comment]
Ok das scheint das gleiche Problem wie hier zu sein:
#6281
