### ISSUE TITLE
pacesetter not loading both bins/sections in mode 1

### ISSUE THREAD

**Issue by dmt116** [Courseplay/courseplay#6291]
Unloading a Coolamon 200T Field Bin in Mode 1 Grain Transport, the first section of Pacesetter trailer fills, then the truck does not move forward to the second bin fill point.

This works perfectly and loads both bins when unloading from a silo and continues loops until reaching amount of trips specified.

 Map: Ravenport
Courseplay v6.02.00075
Mods:
           CP
           Coolamon Bins 200T
Equipment used to reproduce:
           Default Vehicles on new savegame
           Hulk
           Wilson Pacesetter

 log:   https://gist.github.com/dmt116/8b4b0469a20292ab57c862ad40c348eb

**Comment by Tensuko** [comment]
Update:
Farming Simulator 19
  Version: 1.5.1.0 b6729 (1.6.x.x) actually 1.7.1.0 is out already...

https://github.com/Courseplay/courseplay/wiki

Also why rename CP ?
Download .zip and place in mods folder, done.

https://github.com/Courseplay/courseplay/releases

**Comment by dmt116** [comment]
Thank you for your promptness and directions.

Update to 1.7.1.0 completed 

Have always renamed courseplay so I can keep track of version that is loaded without opening game or checking modDesc. Have complied with your direction and is in mod folder.

Re simulated a new game save and still same issue as mentioned in earlier post.
log: https://gist.github.com/dmt116/fe1e3a6a020672d5bae70fca723006c7

**Comment by rohne83** [comment]
This is a duplicate.
Right now CP is not able to unload automatically into more than one trailer/bin. It will only work with fixed loading triggers like silos, but not with grain carts, mother bins, etc.
Feature to make this possible has been requested before already as of https://github.com/Courseplay/courseplay/issues/5799
Afaik this topic is handled together with the auger wagons in https://github.com/Courseplay/courseplay/issues/6046

**Comment by Tensuko** [comment]
Ok wait, what kind of unloading are we talking about right now ?
Unloading into a Silo when the Motherbin is full, or unload a Combine or another Auger wagon ?

**Comment by dmt116** [comment]
thanks rohne83 for for translating #5799 

combine unloads into augerwagon--- augerwagon unloads into motherbin (another augerwagon) then mother bin into pacesetter.

thanks for your time and attendance.

**Comment by Tensuko** [comment]
ok so since it is a duplicate then. closing here.
