### ISSUE TITLE
overloader not compensating for combine head

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/courseplay#6293]
overloader ignores any obstructions, including the combine head, often running into it headlong. 
![20201105125053_1](https://user-images.githubusercontent.com/5993529/98283813-d0319380-1f65-11eb-9520-d34c10d43266.jpg)
![20201105101313_1](https://user-images.githubusercontent.com/5993529/98283840-dde71900-1f65-11eb-87d0-0c1b6d973e9f.jpg)

**Comment by Tensuko** [comment]
Already working on that stuff and Issues exists for that one.
