### ISSUE TITLE
Corn harvester

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/courseplay#6295]
Hello everybody,

I'm not sure if it's a issue or just wrong setup on my side. I've notice when the corn harvester is doing first round run; the tractor with the trailer drives all the time behind him - there is no chance to change that or adjust. 

When the tractor is a long one the shooting arm can't reach the trailer.

**Comment by Tensuko** [comment]
#5272 working as intended.
Throw distance is already extended with CP, won't make it even further.

**Comment by NKESSEL560** [comment]
Same thing for me.  I have tried multiple setups and constantly have to come back to the truck or tractor and just run it myself next to the forage harvester because after every dump it just sits there saying its in traffic.

**Comment by Tensuko** [comment]
#5272 simply read it and you will understand why I keep close those kind of Issues... If not well I can't help you

**Comment by NKESSEL560** [comment]
I have read it and well if you can't understand that it doesn't work then i can't help you

**Comment by Tensuko** [comment]
First at all, it does work as I use it on server and sp!
Second, you did not read it, else you would now post a logfile with debugchannel 4 7 12 and 14 like it was written in #5272 

So tell me again I do not understand whats happening. Same for the throw distance as I made it work with the help of GIANTS.
 
Also I got not even a screenshot from you of the situation.

Again: It does work! If not on your side -> Info so we can check why it is not working for you, else closed and done for us.

**Comment by NKESSEL560** [comment]
I just told you what was happening.  After every dump the tractor or truck comes back and doesn't get close enough to the "harvester" aka CHOPPER and puts up a in traffic warning and the course does not restart.  I stripped all mods and used complete vanilla and still the same issue.  And now after research on Youtube people are saying the only way they can get it to work is to use harvesters with chute extensions.

**Comment by Tensuko** [comment]
Thats nonsence.
All Choppers gets modified when running with CP to throw further.
If those YT people keep use old CP Versions we can't help them beside telling them to update CP!
it is fact that the only Chopper that is able to throw far enough for turns and to drive behind it is the Krone Big X all other need changed values and MAYBE the update fixed the other 2 Vanilla Chopper. For mods we can't tell you that everyone use the right values and for that reason we modifie those needed values that it works!

And still no logfile and not even version information...

**Comment by NKESSEL560** [comment]
YES nonsense....... complete nonsense.  That is why I take time out of my day to try and help........ which turned into you telling me it was impossible.  And you think I didn't think to DL the latest CP lol.  I went through all the trouble to remove mods and try different choppers and search what other people were doing to try and help which equals me being full of nonsense.   And I don't care enough to give you a log anymore.  Even if it did work it is the most unrealistic way of chopping I have ever seen.
