### ISSUE TITLE
CP Editor Wegpunkte löschen bis Anfang geht nicht mehr, fix geht nur im SP.

### ISSUE THREAD

**Issue by BauerNepo** [Courseplay/courseplay#6297]
Hallo,
ich nutze ausgiebig den CP Editor. Schönes Ding ;-)
Heute habe ich mir die neueste CP Version  6.02.00076 geladen, nun geht die Funktion "Wegpunkte löschen bis Start" nicht mehr. Löschen bis Ende funktioniert weiterhin. Versuchsweise habe ich mir mehrfach die Tastenbelegung geändert, keine Besserung. Leider weiss ich nicht, welche Version ich vorher benutzt habe als es noch ging.
Ist das nur bei mir so oder liegt das an CP?

Gruss
Bauer Nepo

**Comment by Tensuko** [comment]
Jup, da hast du recht, das scheint kaputt zu sein.
Müssen wir uns bei Gelegenheit anschauen, aber da man sonst problemlos löschen kann usw wird das eher niedrige Priorität haben.

**Comment by BauerNepo** [comment]
Ok, liegt also nicht an mir...
Schade dass die Priorität niedrig ist, diese Funktion ist für mich sehr nützlich. Damit kann ich auf einfache weise Kurse abändern, so muss ich halt jeweils hundert und mehr Wegpunkte löschen. Aber Ihr habt halt auch so genug zu tun :-). Danke für Eure tolle Arbeit.

**Comment by BauerNepo** [comment]
Also um es etwas einzugrenzen: Version.xxx74 klappt  das mit dem löschen bis Start, mit Version .xxx75 geht es nicht mehr. Vieleicht hilft Euch ja diese Information...

**Comment by SavageMkII** [comment]
I noticed this today as well. I did some testing with only CP in the mod folder, and it seems you can't make any changes to the first point of the course other than moving it. I also noticed that sometimes the "undo last course change" function doesn't work.

**Comment by BauerNepo** [comment]
Hallo, ich habe bei mir diese Funktion wieder zum arbeiten gebracht. Da ich aber keine LUA Kentnisse habe, kann ich nicht sagen ob das auch korrekt ist so. Aber es funktioniert nun bei mir, und in der Log erscheinen erstmal keine Meldungen nach meiner Anpassung ;-) . 

In der courseeditor.lua habe ich geändert:

1.
Zeile 726 von:
CourseEditorEvent.sendEvent(vehicle,"DeleteToStart", self.guiWpSelected);
zu:
courseEditor:doDeleteToStartAction(vehicle,"DeleteToStart", self.guiWpSelected);

2.
Zeile 925 von:
for _ = 1,guiWpSelected - 1 do
zu:
for _ = 1,self.guiWpSelected - 1 do   

(Diese Zeile stammt aus Version 6.2.00074, habe ich einfach mal kopiert und ausprobiert)

Alles ohne Gewähr auf Richtigkeit, aber so kann ich nun endlich wieder meine Kurse nach Herzenslust abändern und neu zusammenfügen.

Gruss vom BauerNepo

**Comment by Tensuko** [comment]
Try Version 6.03.00041 or higher and report.

**Comment by BauerNepo** [comment]
Hallo, danke sehr, funktioniert jetzt wieder einwandfrei (soweit ich das beurteilen kann). 

Gruss BauerNepo
