### ISSUE TITLE
Courseplay Abfahrer rufen

### ISSUE THREAD

**Issue by Thermodynamicus** [Courseplay/courseplay#6298]
Da meine Tickets ohne weitere Fragen immer mitten im Problem nur halb beantwortet geschlossen werden mache ich wieder ein neus auf. Jetzt habe ich das Problem dass mein Abfahrer nicht mehr abfährt bzw von seinen Endpunkt aus nicht losfährt wenn der Drescher den entsprechenden Füllstand hat. Der Abfahrer kommt auch nicht wenn ich ihn über den Drescher rufe. Dort steht erst abfahrer gerufen und dann muss ich nocheinmal draufklicken damit bei dem Drescher der Abfahrer steht und bei dem Abfahrer der aktuelle Drescher drinnen steht, welcher sich jedoch nicht von dem Endpunkt des Courses bewegt.

**Comment by Thermodynamicus** [comment]
Ich muss mich korrigieren der Abfahrer fährt jetzt nur noch wenn der Füllstand erreicht ist.
[log.txt](https://github.com/Courseplay/courseplay/files/5505386/log.txt)

**Comment by Tensuko** [comment]
Ja und wann soll der Abfahrer kommen ? Wo steht der Drescher ? Fruchtumfahrung ja oder nein ? usw usw

Wenn Fruchtumfahrung an -> Abfahrer kommt erst wenn Rohr nicht in der Frucht.

Mehr Infos und vorallem #5272 lesen...

**Comment by Thermodynamicus** [comment]
Der Abfahrer soll kommen wenn der Drescher bei 50% ist.  Fruchtumfahrung ist bei beiden deaktiviert. Der Abfahrer kommt erst wenn der Drescher zu 100 bzw 99% voll ist und steht. Ich kann den Abfahrer auch nicht per Abfahrer menu rufen. Der Drescher steht immer in der Reihe die er grade am Dreschen ist also fährt er nicht aus der Reihe raus. Ich habe es mit Fruchtumfahrung bei beiden aktiviert und deaktiviert getestet jedoch passiert jedesmal das gleiche.

**Comment by Thermodynamicus** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5506479/log.txt)

**Comment by Thermodynamicus** [comment]
Mir ist jedoch aufgefallen dass sich dieser Fehler oder die komische Verhaltensweise auflöst wenn er 1 mal den Drescher abgetankt hat. Sprich der Abhfahrer wartet am Endpunkt bis der Drescher 100% hat tankt er diesen ab jedoch danach triggert er ab den gewünschten 50%

**Comment by Tensuko** [comment]
Also erstmal kann ich dir versichern, das zwischen Fruchtumfahrung an und aus ein riesen Unterschied besteht.
Auch ob er im ersten Vorgewende ist oder nicht und ob das Rohr in der Frucht ist oder nicht.

**Comment by Thermodynamicus** [comment]
ok also so wie es jetzt aussieht habe ich den trick raus. Falls was ist melde ich mich nochmal danke für die Hilfe. Das mit dem Ticket schließen sollte nicht böse gemeint sein tut mir leid.
