### ISSUE TITLE
convoy right laneskips headland

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/courseplay#6300]
![20201107153523_1](https://user-images.githubusercontent.com/5993529/98451814-f3e40d80-210e-11eb-8dfb-f2f7e9845c5b.jpg)
when i set a three vehicle convoy, the right lane tractor skips the headland

![20201107153753_1](https://user-images.githubusercontent.com/5993529/98451840-55a47780-210f-11eb-8ec0-981faf914bb1.jpg)

**Comment by Tensuko** [comment]
Course start at Corner ?
Screenshot of complete course ?
Version Update to .00076!

**Comment by Commissar0617** [comment]
yes, at the corner. ill try and get the update

**Comment by Commissar0617** [comment]
updated... now it's  just gone off course completely
![20201107155504_1](https://user-images.githubusercontent.com/5993529/98452177-876b0d80-2112-11eb-8092-34328d6422ed.jpg)
![20201107160114_1](https://user-images.githubusercontent.com/5993529/98452178-8803a400-2112-11eb-9bc0-62387464a96b.jpg)

**Comment by Commissar0617** [comment]
yhup, still gone to the middle fo field and working the up/down

**Comment by Tensuko** [comment]
Jupp, still start in corner. Start more far away from corner and it does work fine.

**Comment by Commissar0617** [comment]
![20201107161157_1](https://user-images.githubusercontent.com/5993529/98452357-4f64ca00-2114-11eb-8cfc-bc3ea0569f1e.jpg)
![20201107161412_1](https://user-images.githubusercontent.com/5993529/98452358-512e8d80-2114-11eb-9397-f3248929bd2c.jpg)


nope. still just drives straight to the center of the field
![20201107161539_1](https://user-images.githubusercontent.com/5993529/98452371-7e7b3b80-2114-11eb-9d5b-dea150ffe9c0.jpg)

**Comment by Tensuko** [comment]
You don't understand it.
The Startpoint should not be at a corner when you use Multitool.....

**Comment by Commissar0617** [comment]
yeah, i regenerated the course, away from the corner, and that worked. thanks

**Comment by Tensuko** [comment]
Ok good :)
