### ISSUE TITLE
Keine Kreuzungspunkt-Dreiecke mehr

### ISSUE THREAD

**Issue by r00mm4n** [Courseplay/courseplay#6301]
Ich habe heute Nachmittag begonnen mir auf Kernstadt Hauptkurse einzufahren, mit Kreuzungspunkten um daraus dann die weiterführenden Wege anzuhängen. Hier ist es ja unbedingt nötig die Kreuzungspunkte anzuzeigen (das Achtung Verkehrszeichen Dreieck) um die Folgekurse korrekt zu starten. 
Als ich jetzt weiter machen wollte, zeigt mir kein Fahrzeug mehr die Kreuzungspunkte an wenn ausgewählt. Auch wenn ich zusätzlich noch alle Punkte anzeigen lasse erscheinen keine Kreuzungspunkte. In der Anzeige des geladenen Kurses zeigt er aber die Anzahl der Kreuzungspunkte an. Fahre ich neue Kurse ein mit Kreuzungspunkten erscheinen die Symbole für den neuen Kurs, teilweise kommen dann auch die Symbole der eingefahrenen Kurse wieder, aber nicht alle. 
Die Kreuzungspunkte sind aber noch vorhanden, da ich die Kurse trotzdem korrekt kombinieren kann. Im Log ist kein Fehler. Hatte vorher die 6.02.00069 und jetzt auch mal die 6.02.00076 versucht -> bei beiden Versionen ist das Problem.
Wäre super wenn sich das jemand anschauen kann, danke.

**Comment by r00mm4n** [comment]
![20201107230041_1](https://user-images.githubusercontent.com/74117823/98452294-2c570c00-214e-11eb-8a3d-ebbd5061aa80.jpg)

**Comment by Tensuko** [comment]
HUD Settings Kreuzungspunkte aktiviert ?!

**Comment by r00mm4n** [comment]
Ja, wollte eigentlich den Screenshot so mit den Settings machen

**Comment by r00mm4n** [comment]
Habe das Problem identifiziert:
die Einstellung unter "Allgemeine Einstellungen"-> "Erweiterte Einstellungen" -> ein Reiter nach rechts -> "lade Kurse beim Start" war/ist deaktiviert, nach aktivieren sind jetzt die Kreuzungspunkte wieder da.
Ich bin mir jetzt nicht sicher aber die Einstellung war wohl standardmäßig deaktiviert da ich in diesem Menü nicht umgestellt hatte.

**Comment by Tensuko** [comment]
Ja das ist normal deaktiviert wegen ladezeiten, warum das die kreuzungspunkte ausknipst weis ich aber auch nicht, müssen wir schauen.

**Comment by r00mm4n** [comment]
Ok danke.

Ich bin eigentlich nur per Zufall dann darauf gekommen, weil ich einen alten Kurs geladen hatte um die gesetzte Kreuzung zu "erschätzen". Nachdem ich dann einen neuen Kurs gefahren bin, mit Kreuzungspunkten, erschienen dann die Kreuzungspunkte des zuvor geladenen Kurses wieder.
