### ISSUE TITLE
harvester and backmarker

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#6304]
I have tried using forage harvesters other than the Krone Big X 1180 and it doesn't work (I used the John Deere), because the backmarker is too far away for the forage harvester to throw silage onto the trailer. Pending corrections (if it is possible to do them) could you put a manual regulator that allows you to change the position of the backmarker? Unfortunately I don't have any logs and photos while using the John Deere but I have one while testing the forage harvester attached to the tractor. If other photos and logs are useful, I will be happy to take them

![Farming Simulator 19 08_11_2020 11_23_17](https://user-images.githubusercontent.com/59969508/98462610-d28a2c80-21b5-11eb-8673-29fab50eeb98.png)

[log.txt](https://github.com/Courseplay/courseplay/files/5506164/log.txt)

**Comment by Tensuko** [comment]
That one isn't supported yet.
That one is more complicated to reverse as well.
We are working on other stuff right now for Mode2 Chopping.

For other Choppers:
Most should work already, since we modify some values that make them throw far enough.
