### ISSUE TITLE
Problem mit direkt saat maschiene

### ISSUE THREAD

**Issue by Playlord75** [Courseplay/courseplay#6305]
moin hab ein kleines probolem mit der neusten cp version bei einer sähmaschiene (Mod) weil ich kein ladegut beim feldarbeitsmodus mehr hinzufügen kann sagt er mir das das gerät endladen werden muss
![fsScreen_2020_11_08_14_09_52](https://user-images.githubusercontent.com/71101944/98465845-20119400-21cc-11eb-82c9-0d99dc8f98e3.png)
![fsScreen_2020_11_08_14_10_03](https://user-images.githubusercontent.com/71101944/98465848-21db5780-21cc-11eb-90ec-328e3d95f6bc.png) 
in der vorherigen version die ich hatte funtionierte es noch einbanfrei nur finde die version leider nicht wieder wo man noch das ladegut hinzufügen konnte

**Comment by Tensuko** [comment]
Das ist ja auch der komplett falsche Modus....
Mode6 ist NICHT zum ansäen.
Warum bei dir der Modus 4 ausgegraut ist wundert mich allerdings gerade.

Welche Saatmaschine ist das ?

**Comment by Playlord75** [comment]
die sähmschiene besteht aus 2 teilen 
![fsScreen_2020_11_08_15_12_32](https://user-images.githubusercontent.com/71101944/98467299-d6797700-21d4-11eb-92bc-8b5882e54ab5.png)

**Comment by Playlord75** [comment]
und vorher ging es ja auch damit zu sähen auch im mode6 nur seit dem
 man jetzt kein ladegut mehr auswählen kann funtioniert es nicht mehr

**Comment by Playlord75** [comment]
ich könnte natürlich auch versuchen die sähmschiene zu einem teil zusammen zu bauen im ge aber das wahre ja nicht die lösung dafür warum der mode4 nicht geht

**Comment by Tensuko** [comment]
- Das es im Mode6 geht ging ist zufall aber komplett falsch!
- Ich will noch immer wissen, welche Saatmaschine das ist...

**Comment by Playlord75** [comment]
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=155181&title=fs2019

**Comment by Playlord75** [comment]
ich glaub ich habe das problem gefunden
![image](https://user-images.githubusercontent.com/71101944/98467706-06297e80-21d7-11eb-957d-0f41d4ee4cea.png)

**Comment by Tensuko** [comment]
Nichts angekoppelt
![fsScreen_2020_11_08_15_24_06](https://user-images.githubusercontent.com/27344744/98467589-84395580-21d6-11eb-9cf7-a10fdfa1e47c.png)
Nur vorderer Teil angekoppelt
![fsScreen_2020_11_08_15_24_13](https://user-images.githubusercontent.com/27344744/98467590-86031900-21d6-11eb-830a-718f1e687a6d.png)
Direktsaatgerät angekoppelt
![fsScreen_2020_11_08_15_24_19](https://user-images.githubusercontent.com/27344744/98467592-87344600-21d6-11eb-8c56-050e53fb9f33.png)
Einmal komplett ab und wieder dran gekoppelt
![fsScreen_2020_11_08_15_24_25](https://user-images.githubusercontent.com/27344744/98467594-88fe0980-21d6-11eb-84a6-18d27b3f5033.png)

Funktioniert, kein CP Bug, ABER versuch mal das:

![pronto](https://user-images.githubusercontent.com/27344744/98467737-3ec95800-21d7-11eb-9c08-0e0d07e44fd9.png)

**Comment by Playlord75** [comment]
ah ok danke

**Comment by Tensuko** [comment]
Nein das ist schon richtig, sonst wird die Direktsaat nicht mehr gehen und das ist auch ok das Mode6 auch funktioniert.
Nur normal sollte Mode6 und Mode4 verfügbar sein, jedenfals bei dieser Saatmaschine.
Korrekt wäre eben Mode4 zum ansäen und das klappt auch, nur habe ich meine mal modifiziert, weil der AI Driver die nicht aufklappen konnte. Vlt liegt es daran.

**Comment by Playlord75** [comment]
ok danke für die schnelle hilfe

**Comment by Tensuko** [comment]
Ja sag bitte ob es geklappt hat, ich bin mir nicht sicher, dass es daran liegt, aber das ist der bisher einzige unterschied soweit ich weis.

**Comment by Playlord75** [comment]
ja ich gibt natürlich bescheid wenn es immer noch nicht klappen sollte

**Comment by Playlord75** [comment]
![image](https://user-images.githubusercontent.com/71101944/98468210-ba2c0900-21d9-11eb-92ba-c881562d8d89.png)
hat geklappt

**Comment by Tensuko** [comment]
Unglaublich :)
Wenn du noch mal richtig was tun willst, dann kannst du mit der Änderungsinfo zu dem Club auf den Discordserver gehen und denen das noch mal sagen... wir waren schon mit 2 Leuten da und die haben das ignoriert mit den Worten 'naja klappt bei dir ja jetzt' aber wie man sieht, stolpern mehrere dadrüber...

**Comment by Playlord75** [comment]
wie komme ich auf denn sicord server

**Comment by Playlord75** [comment]
ich hab denn richtigen fehler gefunden es ist nicht die sähmschiene es ist der john deere 6m Mod xD
![fsScreen_2020_11_08_16_00_29](https://user-images.githubusercontent.com/71101944/98468644-b13c3700-21db-11eb-932b-b1aec88f3f1e.png)
![fsScreen_2020_11_08_16_00_52](https://user-images.githubusercontent.com/71101944/98468645-b305fa80-21db-11eb-8fab-2ff6a406f58b.png)

**Comment by Playlord75** [comment]
aber wie kann ein traktor denn mode4 mainpoliern

**Comment by Tensuko** [comment]
oh okay.... hatte mich auch etwas gewundert mit dem unfold...
Ja hmm das ist eine gute Frage, kommt drauf an wie der gebaut ist.
Welcher JD ist denn das ?

**Comment by Playlord75** [comment]
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=157691&title=fs2019 der john deere ist es

**Comment by Tensuko** [comment]
Hast du noch andere Traktoren von dem Modder und würdest du noch welche ausprobieren ob wir da das gleiche Problem haben ?
Wenn es sich nur um den einen handelt, werden wir da nichts dran ändern, das könnte zu viel Aufwand sein wegen einem Traktor...

**Comment by Playlord75** [comment]
ja ich hab noch einen traktor von dem moder werde es mal ausprobieren aber jetzt kommt aber ein anderes problem an die reihe unzwar macht cp fahrgassen 
1 wenn ich fahre
![fsScreen_2020_11_08_16_29_28](https://user-images.githubusercontent.com/71101944/98469426-bdc28e80-21df-11eb-83ea-a85c88f01099.png)
2 wenn cp eingeschaltet ist 
![fsScreen_2020_11_08_16_29_39](https://user-images.githubusercontent.com/71101944/98469428-c024e880-21df-11eb-963f-55586187f728.png)

**Comment by Playlord75** [comment]
ehm ja es hat nen guten grund warum das unfolding für ai aus ist er macht sonsr fahrgassen

**Comment by Playlord75** [comment]
![image](https://user-images.githubusercontent.com/71101944/98469690-73daa800-21e1-11eb-887e-a73538390da1.png)
die hat eingabute drive lains drin

**Comment by Playlord75** [comment]
ich lösche die mal für mich raus dann sollte es auch kein problem mit fahrgassen übers ganze feld verteilt geben

**Comment by Tensuko** [comment]
Ach na toll.... aber das hatte ich doch noch nicht gehabt.... ok muss ich später mal schauen. Sag ruhig bescheid wenn du was raus findest :)

**Comment by Playlord75** [comment]
ja hab sie jetzt rausgelöscht denn xml eintrag entfernt jetzt sollte sie ohne probleme laufen

**Comment by Playlord75** [comment]
so muste etwas mehr umschreiben jetzt klappt es aber denke du kannst die issue schlie?en wenn du nichts mehr hast :)

**Comment by Tensuko** [comment]
ok super :)
