### ISSUE TITLE
LUA call stack 

### ISSUE THREAD

**Issue by Zockeronkel** [Courseplay/courseplay#6306]
[log.txt](https://github.com/Courseplay/courseplay/files/5507221/log.txt)
it is with the version 6.02.00076
I cannot open a saved game, doesen't matter if single or multiplayer

**Comment by Tensuko** [comment]
Müsste das hier sein: #6281
courseManager.xml in den Kursen den parent Wert auf 0 setzen dann sollte es wieder gehen

**Comment by Zockeronkel** [comment]
Hatte es versucht den parent Wert auf 0 zu setzten, funktionierte nicht, da das Spiel dem letzten Kurs in der Liste wieder auf 3 gesetzt hat. Habe jetzt alle gespeicherten Kurse gesichert und danach im Map-Ordner gelöscht, jetzt läuft das Spiel wieder. Soll ich noch versuchen jeden Kurs einzeln einzufügen und schauen welcher Kurs mit welchen Fahrzeugen Probleme macht?
Lg

**Comment by Tensuko** [comment]
Du könntest starten, speichern und dann die Kurse wieder einfügen probieren.
Aber uns hilft es nichts, es war ein bug und der ist behoben, allerdings sind eben alte Kurse eventuell kaputt gegangen.
