### ISSUE TITLE
Convoy first - last check distance

### ISSUE THREAD

**Issue by Misamangame** [Courseplay/courseplay#6307]
Hello guys,

is it possible implement function in convoy, no matter what and how many machines running in it that first in a line will keep distance from the last so there is no danger he will try overtake him or usually crash him and simply stay in desired distance from last machine? When I have big field especially harvesters are the problem because 1st one usuallly goes a bit faster then others and catching with last one, yes you can reduce his speed but sometimes even that will not help and they will just tangle into each other and start wrestling match.  Would be nice if first keep same minimum desired distance from last like others do.
![20201108224149_1](https://user-images.githubusercontent.com/33344465/98486023-12372f80-221b-11eb-9300-49249ca5721e.jpg)

**Comment by Tensuko** [comment]
you mean something like a max distance so he doesn't drive to far away ?

**Comment by Misamangame** [comment]
I meant if that first one will have distance set for example 200m and he will catch up with last one he will be still keepeing max 200m behind him and did not get closer to him like others in convoy do normally.
But if you can set maximum distance from first to last that will be also good solution

**Comment by Tensuko** [comment]
oh that way.... that won't work at all... We have not a Plan for 'overtake' and won't add. #4121

The only chanze is a max distance that the 1st one slow down.

![grafik](https://user-images.githubusercontent.com/27344744/98517300-fd37bc00-226d-11eb-8092-4329041a3a3a.png)
