### ISSUE TITLE
CP Unloader not responding in MP (v6.02.00076)

### ISSUE THREAD

**Issue by PioneerX** [Courseplay/courseplay#6308]
We are experiancing an issue were often an unloader is assigned to a harvester but does respond when called. Other players on the server have reported that it works occasionally but not most of the time.

FS19 Version : 1.7.1
CP Version : v6.02.00076
Map : Lawfolds, Aberdeenshire

Client Log : https://pastebin.com/u2N8gtEK
Server Log : https://pastebin.com/f85aCmTs

Process used:

1. Stopped server & changed password to prevent others from joining and keep the logs clean
2. Started server and client fresh
3. Enabled debug modes 4,7,14
4. Placed combine on course and started in 'field work' mode - combine starts harvesting
5. Place tractor (T7.313) with trailer (Joskin) on field, select 'combi mode', select 'Start course at' as 'Unloading', select correct combine from search panel and click Drive Course - tractor waiting
6. Combine fills to 100% but tractor remains unresponsive.

Throughout the log there are no direct error messages but debug mode4 constantly reports.....
CombineUnloadManager: Combine with most fill level is N/A

....and client log reports the following each time the harvester reaches near full or if you manaully select 'Request Driver'
g_combineUnloadManager:getHasUnloaders(vehicle):false

If we are doing something wrong then please advise, if not then I hope this information helps resolve the issue.

**Comment by bumbalaga** [comment]
Hi,

I have the exact same issue. It seems to work on random. Tried using modded and unmodded combines/tractors. 

Can provide some logs myself if requested.

**Comment by Tensuko** [comment]
> 
> 
> Hi,
> 
> I have the exact same issue. It seems to work on random. Tried using modded and unmodded combines/tractors.
> 
> Can provide some logs myself if requested.

It is always better to bring the needed information in the first post you do instead of asking if you should... it makes Issues much more cleaner to read and to follow...

**Comment by JarlHulsman** [comment]
we have exactly the same issue, it does not auto unload the combine, we've tried going back to older versions of CP but that does not help, at first it worked all great but all off the sudden it stopped driving to the combines. can some kind of mod do this to courseplay? i've checked 2231 but we don't have any of the mods in that list, not even downloaded.

we are playing the pure Netherlands map, after over a week of playing this issue occured,

If you need more explanation or logs please ask.
![mods fs 19 1](https://user-images.githubusercontent.com/75091106/100381795-0d93b900-301a-11eb-9f2f-d19a22d96c7d.png)
![mods fs 19 2](https://user-images.githubusercontent.com/75091106/100381801-0ff61300-301a-11eb-8b56-fffd4b88eecc.png)
![mods fs 19 3](https://user-images.githubusercontent.com/75091106/100381804-12f10380-301a-11eb-9e21-ba5529d4d307.png)
![mods fs 19 4](https://user-images.githubusercontent.com/75091106/100381809-14bac700-301a-11eb-9266-16becf42bddd.png)


https://gist.github.com/JarlHulsman/bf9edf0b53a1026c1b954bc995ab1fbe#file-log-txt


[bf9edf0b53a1026c1b954bc995ab1fbe-3808a65509c798b5c628833e2d61a5d4c1a99623.zip](https://github.com/Courseplay/courseplay/files/5604476/bf9edf0b53a1026c1b954bc995ab1fbe-3808a65509c798b5c628833e2d61a5d4c1a99623.zip)

Thanks guys for developing course play! This defenitely makes the game better 3x.

greetings
Jarl

**Comment by Tensuko** [comment]
Fix is on the way, just wait a bit more :)

**Comment by JarlHulsman** [comment]
Thanks for the quick response! We will be patient.
