### ISSUE TITLE
CombineUnloadManager.lua:57: attempt to call method 'is_a' (a nil value)

### ISSUE THREAD

**Issue by Magge2005** [Courseplay/courseplay#6310]
Hallo liebes Courseplayteam,
ich habe ein Problem mit der neusten Courseplayversion wenn ich einen Spielstand auf dem neusten Patch der Hof Bergmann Map im LS19 und mein Log schmeißt mir immer den "CombineUnloadManager.lua:57: attempt to call method 'is_a' (a nil value)" fehler durch den ich den Spielstand nicht mit Courseplay spielen. Das Problem hab ich sowohl bei bestehenden als auch bei neuen Spielständen. Ich hoffe ihr könnt mir in diesem Punkt helfen, da ich sehr gerne Courseplay verwende und das auf anderen Maps sehr gut funktioniert.

![Logfehler](https://user-images.githubusercontent.com/74217261/98702319-863c1980-237a-11eb-8e5e-06b0c446c42a.png)

**Comment by Tensuko** [comment]
komplettes logfile bitte als .txt anhängen.
Bzw mal dieses Issue anschauen, recht weit unten steht was das Problem sein könnte.
#6281

**Comment by Magge2005** [comment]
Hab 
[log.txt](https://github.com/Courseplay/courseplay/files/5519458/log.txt)
hier den Log in einem neuen Savegame ohne andere Mods nur mit den für die  Hof Bergmann nötigen

**Comment by Tensuko** [comment]
Und ? #6281 gelesen ? Und das gemacht was da steht mit der courseManager.xml ? :)

**Comment by Magge2005** [comment]
in meinem Courseplayordner ist keine courseManager.xml vorhanden ich lade mal den Mod frisch runter und schau dann nochmal

**Comment by Tensuko** [comment]
Welcher courseplay ordner.....

**Comment by Magge2005** [comment]
Der im Modordner

**Comment by Magge2005** [comment]
sorry ich bin was das angeht echt nicht gut :)

**Comment by Tensuko** [comment]
Komplett falsch.
Im Ordner wo auch deine savegame liegen (FarmingSimulator 2019) gibt es einen Ordner CourseplayCourses und dort gibt es einen Ordner für die Hof Bergmann und da drin befinden sich alle deine CP Kurse inklusive the courseManager.xml welche deine Kurse verwaltet. Hänge die Datei sosnt mal hier an dann schau ich kurz drüber.

**Comment by Magge2005** [comment]
[courseManager.zip](https://github.com/Courseplay/courseplay/files/5522158/courseManager.zip)
 hier die Datei jetzt schonmal danke für deine Hilfe :)e

**Comment by Tensuko** [comment]
[courseManager.zip](https://github.com/Courseplay/courseplay/files/5522266/courseManager.zip)

tausch die Datei mal aus und versuch es dann noch mal.

**Comment by Magge2005** [comment]
Habs getauscht und alles funktioniert. Vielen Dank

**Comment by Tensuko** [comment]
Super :)
