### ISSUE TITLE
fertilizer/herbicide cost money

### ISSUE THREAD

**Issue by Ringkeeper** [Courseplay/courseplay#6311]
If you use CP for spraying herbicide the money for the herbicide ticks down while CP drives over the field, even if you bought the (in my case liquid) herbicide before and filled the tool.

If the tool is empty CP stops working.

So you pay twice for the herbicide. Same for the fertilizer.

**Comment by Tensuko** [comment]
You didn't turn off 'buy herbicide' in the ingame settings.......... not all thing are CP fault!
