### ISSUE TITLE
Häckseln auf mehrere FillUnits

### ISSUE THREAD

**Issue by rohne83** [Courseplay/courseplay#6312]
Ist vielleicht gar nicht vorgesehen, dass das funktioniert, aber grundsätzlich kommt Courseplay beim Häckseln auch recht gut mit Abfahrern mit mehreren FillUnits zurecht (LKW mit Anhänger, oder Traktor mit zwei Anhängern). Allerdings fährt da mittlerweile der Mode2-Abfahrer nicht mehr ab wenn er 100% voll ist. Wie im Screenshot zu sehen, steht er dann vollgeladen neben dem Häcksler, immer noch mit Status "FOLLOW_CHOPPER". Bis vor ein paar Versionen (so ca v60) funktionierte das allerdings noch, wenn ich mich recht erinnere.
![fsScreen_2020_11_04_19_20_41](https://user-images.githubusercontent.com/71030138/98834680-c6190480-243f-11eb-912b-d69f119b56d1.png)

Bei dem obigen Abfahrgespann kommt als weiteres Problem noch hinzu, dass beim Häckseln auf den HW80-Anhänger der Abfahrer zu weit nach vorne fährt, so dass irgendwann das Häcksler-Rohr keine Chance mehr hat den Anhänger zu treffen. Einzige Möglichkeit das zu verhindern ist, die Feldgeschwindigkeit des Abfahrers herunterzusetzen auf den gleichen Wert wie für den Häcksler. Passiert allerdings nur beim HW80. Dürfte also am Mod liegen. Und egal, ob ich diesen Anhänger an Traktoren oder LKWs hänge, es ist immer dasselbe Problem. Aber halt auch nur mit Courseplay, bei AutoDrive-Abfahrern wird auch auf den HW80 problemlos gehäckselt. Eine Idee woran das liegen könnte? Screenshot von nem anderen Feld, das Problem sieht man aber auch hier:
![fsScreen_2020_11_11_14_45_43](https://user-images.githubusercontent.com/71030138/98834846-f8c2fd00-243f-11eb-91a3-a9602f7a3fdc.png)

**Comment by Tensuko** [comment]
2 fillunits sind nicht untetstützt und werden wir auch nicht machen.

**Comment by rohne83** [comment]
Naja, also 2 FillUnits hat man ja wie in den Screenshots bereits bei LKW mit Anhänger. Und das ist bezüglich der Anzahl der Lenkachsen nichts anderes als Traktor mit Anhänger. Sehe da keinen Grund weswegen man sich dem verweigern sollte. Zumal es ja auch läuft, außer seit ein paar Releases eben das Abfahren bei 100% Füllstand.
Zu dem Problem mit dem HW80 wäre es trotzdem ganz hilfreich, ein Feedback zu bekommen.

**Comment by Tensuko** [comment]
Wir werden 2 befüllbare Trailer oder was auch immer nicht extra unterstützen, machen wir das so wie du das hast kommt der nächste mit ähnlichen Argumenten für 2 Trailer.

Der HW80 wird einen komischen fillnode haben der nur von der einen seite kommt. Mod issue.

**Comment by rohne83** [comment]
Von ner extra Unterstützung hab ich auch nichts gesagt. Sieht für mich halt eher nach nem Bug aus wenn er trotz 100% Füllstand nicht erkennt, dass er voll ist. Eure CombineUnloadAIDriver.lua scheint ja auch auf alle FillUnits zu prüfen, aber kommt hier halt nicht zum richtigen Ergebnis.
Der HW80 lässt sich von allen Seiten beladen, manuell und mit AD gibts auch keinerlei Probleme. Nur bei CP fährt er zu weit vor, egal auf welcher Seite vom Häcksler er sich grad befindet. So lange er noch hinter oder neben dem Häcklser ist, wird auch normal gehäckselt. Nur irgendwann ist der Mode2-Fahrer halt soweit nach vorn gefahren, dass er aus dem Zielbereich des Häckslers raus ist.

**Comment by rohne83** [comment]
wegen dem HW 80: ich vermute mittlerweile, dass evtl einfach der vertikale Abstand falsch berechnet wird. Probleme macht der nämlich auch beim Dreschen (wobei da nicht zu weit, sondern nicht nah genug herangefahren wird). Am Ende vielleicht nur ein simples Vorzeichne-Problem. Wenn ich wüsste anhand welcher Parameter oder wo im Code ihr das berechnet, könnt ich das vielleicht auch selbst im Mod direkt beheben.

**Comment by rohne83** [comment]
Hi @Tensuko,

also ich hab nochmal etwas weiter durchprobiert, und es hat sich herausgestellt, dass die Probleme gar nicht von der Anzahl der FillUnits abhängen. Es ist eher so, dass generell bei LKWs mit fest verbauter Pritsche das Abfahren bei 100% Füllstand nicht funktioniert, auch wenn gar kein Anhänger angehängt ist. Der W50 aus den Screenshots oben zeigt das Verhalten, bei 100% Füllstand nicht abzufahren, nämlich auch ohne Anhänger. Ebenso zB der MAN TGS. Nicht zu beobachten ist es dagegen wenn die Trailer nur angehängt sind, also zB bei Traktoren, oder auch beim L60 Mod - bei letzterem ist der Häckselaufbau eine austauschbare Wechselbrücke die genau wie ein Anhänger erst "angekuppelt" werden muss. Das würde ich insofern dann definitiv als Courseplay-Bug einstufen, und somit in meinen Augen Grund genug den Issue wieder zu öffnen, halt mit anderer Überschrift.
