### ISSUE TITLE
overloader not going to the pipe end, combine not going off the lane as far as it should

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/courseplay#6314]
![20201111195106_1](https://user-images.githubusercontent.com/5993529/98886357-88c17080-2459-11eb-984e-4cadeb3c4cab.jpg)
![20201111195153_1](https://user-images.githubusercontent.com/5993529/98886358-895a0700-2459-11eb-9934-27c4a50bfab5.jpg)
![20201111192936_1](https://user-images.githubusercontent.com/5993529/98886387-95de5f80-2459-11eb-87dc-fadc83f1cc18.jpg)
i think too, the combine is supposed to be like 50% more off the lane, i've seen ti do it right, but for some reason, sometimes, it doesn't. CP appears to be detecting the pipe end fine, but the pathfinding doesn't drive under it.

**Comment by Tensuko** [comment]
Vanilla Combine or Modded one ?
The target for unloader should be right under the pipe.
Do you hve any offset setting for your Mode3 driver ? (3rd page from the right)

**Comment by Commissar0617** [comment]
modded combine. https://fs19.lt/case-ih-axial-flow-v-1-0/
stock draper head

it's in a 3 lane setup that is functioning properly otherwise. im basing how far it should go, off the stock axial flow, and the space in the lane. iirc, it's usually like ~60%ish of the head into the crop

if you look at the 2nd screenshot, it looks like CP is seeing the end of the pipe just fine, it just won't drive under it. 

the third tab doesn't have an option for offset for this driver.

**Comment by Tensuko** [comment]
Thrid tab from the right!
9th from the left!

And the 2nd pic shoes clearly, that he could not find the pipe correctly else the blue target line for the unloader would be under the pipe unless you have any offset on that offset page for the unloader.

**Comment by Commissar0617** [comment]
yeah, i dunno what was going on, but i loaded the game up again, and it was working just fine again. pathfinder wasn't even sending my tractors through the river and into the trees anymore...
vOv

**Comment by Tensuko** [comment]
Maybe some hickup :) Will close then for now.
