### ISSUE TITLE
Why can some vehicles be used in carting mode and others cannot

### ISSUE THREAD

**Issue by taffybach** [Courseplay/courseplay#6316]
HI,

I have been using CP for quite some time now in FS17 and currently FS19, I am currently using it in the pleasant valley county mod, but I have noticed that when I want to use some vehicles to cart materials to silos, on some the "Carting" icon is available but on others it is not. Is there a command line in the vehicles .xml file that determines whether CP can use it in "carting" mode?

**Comment by Tensuko** [comment]
Sure there is but the most easy way for mods is to stick to GIANTS Vanilla Trailers in terms of XML.
Try to compare GIANTS Trailers with the one you use to see whats wrong.
