### ISSUE TITLE
bunkersilo overflow 

### ISSUE THREAD

**Issue by evybart** [Courseplay/courseplay#6319]
a question is there a way for this not happening every time i know its dificult with square fill boxes bud perhaps let the filler 2 a 3 m before the end off the bunkersilo stop push the silage 
![bunkersilo_overflow](https://user-images.githubusercontent.com/10274098/98980547-0306f900-251d-11eb-9c5b-46c3aee1cd1f.PNG)

**Comment by Tensuko** [comment]
What Map is this ?

**Comment by evybart** [comment]
nf marsch the bunkersilo's are ingame

**Comment by Playlord75** [comment]
Tensuko ich glaube ich kann dir das Problem sagen um damit ist Ender hier und du kannst diese ISSUE schließen er benutzt zum Silo schieben ein Fahrsilos ist doch Klar das es dann hinten rausgedrückt wird so ich glaube mehr brauchen man nicht sagen 😂

**Comment by Tensuko** [comment]
Hmm najaa ich meine das es nicht passieren sollte :) ich hab aber noch nie ein Fahrsilo aufgeschüttet, jedenfals nicht im 19er

**Comment by Playlord75** [comment]
Der Name verrät doch schon  alles Fahrsilos auch als duichfahr Silo bezeichnet der name sagt doch schon alleine wie es gefüllt werden soll  und für Fahrsilos gibt es ja Extra denn Modus Verteilern und verdichten duichfahren also verstehe ich nicht ganz warum man das Silo duichs schieben befüllt 😂

**Comment by Playlord75** [comment]
Also ich würde sagen das ist kein Fehler von CP sondern da fehlt das logische denken 😂

**Comment by andremeyer123** [comment]
Moin beim durchfahrsilo schiebt er solange hoch bis die hinteren Trigger voll sind .

**Comment by Tensuko** [comment]
@Playlord75 
Könnte man so deklarieren ja, Idee find ich gut :)

@andremeyer123
Ja so soll es halt sein, aber die funktion von Schüttgut scheint im 19er so zu sein, dass es sich über all hinquetscht wo es nur hin kann :)

@evybart
The sence of that drive through silo is not rly to push everything to the end... we know the other Mode10 (compacting) isn't working correct right now, but I wouldn't take that Issue as a real Issue as we don't have an option to stop the chaff from moveing out of the silo.
