### ISSUE TITLE
Bunekrsilo Mode issue

### ISSUE THREAD

**Issue by Natervater** [Courseplay/courseplay#6320]
Hello everyone. I have noticed that when you have a tractor set up for the leveling and compacting, if the worker detects an engine running, it moves to its pause point as intended. But it will not return to work, and, stopping and starting the route only moves it back to its wait point regardless of settings. The only way to get it working again is to quit game and reload. Any help is appreciated.

**Comment by Tensuko** [comment]
What happens if you reduce the detection range ?

**Comment by rohne83** [comment]
@Natervater: is the detected vehicle driven by AutoDrive? I just experienced similar behaviour, when that's the case: it will stop before the silo, silo leveller moves to save waiting position and will not continue its course afterwards. But I could get the leveller starting to work again, when also hiring (and directly firing again) a CP helper for the other vehicle. Doesn't even matter which course you load for this, and don't have to fire the AD helper.
But issue seems to appear only for some vehicles, not all. Need to test more to find out, when exactly the issue occurs and when not.

**Comment by Misamangame** [comment]
@Natervater I had completely same problem with AD drivers only solution I found is to set compacting tractors to detect only CP drivers.  Maybe what @rohne83 suggest works but who has time to do that. If you have AD drivers filling bunker and you make sure compacting tractor will not collide with them they can work together without problems as compacting tractor don't mind it if they are next to him at all, but setting must be CP only.

**Comment by envikowaty** [comment]
Hmm I even tried to change the course play version to 6.1.292 and still getting problem that I have wrong tool

**Comment by Tensuko** [comment]
Try with Version 6.03.00018 and report
https://github.com/Courseplay/courseplay/releases

**Comment by Tensuko** [comment]
Works just fine.
