### ISSUE TITLE
U-turn on the island.

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Courseplay/courseplay#6321]
On some islands, this does not happen, but on some it always does.
![fsScreen_2020_11_14_11_32_08](https://user-images.githubusercontent.com/8200153/99144328-8cc5dc00-266d-11eb-98fa-66ef3fbb0714.png)
![fsScreen_2020_11_14_11_31_39](https://user-images.githubusercontent.com/8200153/99144329-8df70900-266d-11eb-89dc-a9b3773555d0.png)

**Comment by Tensuko** [comment]
I think this is not easy to fix...
I would suggest you to do one more Headland and see what happens.
Or you use the Editor and you shorten the Fieldlines so they stop in front of the Island.

**Comment by pvaiko** [comment]
yeah, that's a difficult situation for the generator. As @Tensuko said, add a few headlands.

**Comment by Gonimy-Vetrom** [comment]
![fsScreen_2020_11_14_18_07_48](https://user-images.githubusercontent.com/8200153/99154350-bc013b00-26b7-11eb-9f64-25fd2ac0d301.png)
I've already come to terms with this. : )


PS. Once I got a different effect with an island: in the "ISLAND_BYPASS_MODE_CIRCLE" option, the course was built without the island accounting, as if it were not there. But when choosing "ISLAND_BYPASS_MODE_SIMPLE" is built correctly. I forgot to take a screenshot of this.
