### ISSUE TITLE
Filling lime on field 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#6323]
Hello I’ve been loading lime into trailer from the field and if I set a course so the spreader returns to the refill point it waits I put a shovel load in roughly 4500L in and it drives off how do I change it so it goes to 100%?

**Comment by Tensuko** [comment]
I think you have to add Lime into the refill-List and set it to 100% it should work.
Let us know if it doesn't then we have a look.

**Comment by matty2123** [comment]
Yeah I’m doing that can get a screenshot to confirm it but it’s saying 100%

Sent from my iPhone

On 15 Nov 2020, at 12:18, Tensuko <notifications@github.com> wrote:

﻿

I think you have to add Lime into the refill-List and set it to 100% it should work.
Let us know if it doesn't then we have a look.

**Comment by matty2123** [comment]
[cid:8CD8FDC8-DC9C-4AC6-A5A3-5AC96E6DF42A-L0-001]

Sent from my iPhone

On 15 Nov 2020, at 12:22, matthew knowles <matty.knowles@hotmail.co.uk> wrote:

﻿ Yeah I’m doing that can get a screenshot to confirm it but it’s saying 100%

Sent from my iPhone

On 15 Nov 2020, at 12:18, Tensuko <notifications@github.com> wrote:

﻿

I think you have to add Lime into the refill-List and set it to 100% it should work.
Let us know if it doesn't then we have a look.

**Comment by matty2123** [comment]
![Uploading 716D8770-0010-4C6B-ABCE-1FF10AE83D29.png…]()

**Comment by Tensuko** [comment]
Screenshot upload needs more patience :)

**Comment by matty2123** [comment]
Patience with what?

Sent from my iPhone

On 15 Nov 2020, at 15:38, Tensuko <notifications@github.com> wrote:

﻿

Screenshot upload needs more patience :)

**Comment by matty2123** [comment]
![Uploading 0186AF9A-26A1-4D7D-9BE1-417916C556BE.png…]()

**Comment by matty2123** [comment]
![09E7184F-CF93-4B4A-80D4-838CF5F92387](https://user-images.githubusercontent.com/27097241/99189931-a9d8d880-275b-11eb-9ee0-b33a9aff37bc.png)

**Comment by Tensuko** [comment]
This is where you have your refillpoint, or do you refill it right on the Fieldcourse ?!

**Comment by matty2123** [comment]
That’s where I added the refill point.

Sent from my iPhone

On 16 Nov 2020, at 07:02, Tensuko <notifications@github.com> wrote:

﻿

This is where you have your refillpoint, or do you refill it right on the Fieldcourse ?!

**Comment by schwiti6190** [comment]
@matty2123 Have you tried to set min fillLevel up to 99% ?

**Comment by matty2123** [comment]
It wouldn’t let me change it from 100% to 99

**Comment by schwiti6190** [comment]
![grafik](https://user-images.githubusercontent.com/58079399/100615727-4d0f1d80-3318-11eb-8606-6e3b9a205b7c.png)

**Comment by schwiti6190** [comment]
@matty2123  you would have to hover over the right number for min and use your scroll wheel :)

**Comment by schwiti6190** [comment]
this one should work, if it isn't working feel to tell us and we will have another look :)
