### ISSUE TITLE
Courseplay not showing up in my mods

### ISSUE THREAD

**Issue by Matt-14** [Courseplay/courseplay#6325]
I downloaded the latest version this morning, I copied the files inside and put them in a zipped folder called FS19_CourseplayBeta. When I went into the game, I selected the save game I wanted to play and said that Courseplay Six was no longer in my mods

**Comment by Tensuko** [comment]
Remove everything from CP from your mods folder.
Download the .zip from here and place it inside of mods folder, done!
Nothing more no packing or anything...
https://github.com/Courseplay/courseplay/releases
