### ISSUE TITLE
Entgegen kommende Abfahrer

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#6326]
Im Modus Abfahrer entleert Erntemaschine, kommen sich der leere und der volle Abfahrer entgegen und bleiben dann stehen und fahren nicht weiter. Was muss ich ändern ?
![Abfahrer](https://user-images.githubusercontent.com/47453761/99190733-9a13c100-2768-11eb-9d3e-5f2743996600.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5542724/log.txt)

**Comment by Tensuko** [comment]
2 Abfahrer noch nicht unterstützt
