### ISSUE TITLE
Unloading harvesters using multiple tool collisions

### ISSUE THREAD

**Issue by Doczott** [Courseplay/courseplay#6328]
When unloading harvester using them with multiple tools, the unloading vehicle will quite often turn into or in front of the harvester it just unloaded.

![fsScreen_2020_11_15_15_34_56](https://user-images.githubusercontent.com/4211286/99198827-4a2cfe00-2758-11eb-8279-d6c8e8a159fd.png)

ver 6.02.00077

**Comment by Tensuko** [comment]
Already working on this.
I hope I can give more Information soon.

**Comment by Doczott** [comment]
Just a suggestion, but maybe you could make the unloading vehicle wait 15 seconds after unloading is done. It would give the harvester time to get clear.

**Comment by Tensuko** [comment]
No, we already have other methodes on the way :)

**Comment by Doczott** [comment]
Cool. Thanks for your hard work.
