### ISSUE TITLE
Mode 2 beim Häckseln: LKW fahren nicht ab

### ISSUE THREAD

**Issue by rohne83** [Courseplay/courseplay#6329]
Leider wurde der https://github.com/Courseplay/courseplay/issues/6312 zugemacht, und gab keine Reaktionen mehr auf meine letzten Kommentare. Deswegen nochmal neu: wie sich herausgestellt hat, sind das Problem nicht die mehreren FillUnits (die funktionieren ansonsten nämlich doch ziemlich gut). Stattdessen ist es so, dass sämtliche LKW mit fest verbautem Häckselaufbau auch bei 100% Füllstand nicht abfahren. Also solche wo die entsprechende FillUnit zum LKW selbst gehört (wie auch die FillUnit für den Sprit), und nicht angekuppelt ist.
Nur wenn "Abfahren bei" niedriger ist als der Füllstand den sie an einer Feldreihenwende oder 90Grad-Kurve haben (wo ja auch aus aus dem Status FOLLOW_CHOPPER rausgesprungen wird), fahren sie auf ihren Abladekurs. Wenn sie aber mitten in einer Feldreihe die 100% erreichen kommen sie aus FOLLOW_CHOPPER eben nicht mehr raus, und dann steht alles. Passiert wie gesagt bei sämtlichen LKW mit fest verbautem Häckselaufbau (oder welcher Aufbau auch immer für Häckselgut geeignet ist). Getestet mit W50 und MAN. Passiert aber ziemlich sicher auch bei anderen derartigen LKW (zB Unimog). Von daher höchstwahrscheinlich ein Courseplay-Problem.
![fsScreen_2020_11_14_15_50_03](https://user-images.githubusercontent.com/71030138/99285258-9a2ec200-2837-11eb-80f4-d04ec50f640e.png)

**Comment by Tensuko** [comment]
log mit channel 4 7 12 und 14

**Comment by rohne83** [comment]
Fill levels: CHAFF: 0.00  <-- das ist natürlich nicht korrekt, und wundert mich dann auch nicht weshalb er nicht abfährt
[log.txt](https://github.com/Courseplay/courseplay/files/5553971/log.txt)

**Comment by Tensuko** [comment]
@rohne83 
Könntest du das noch mal mit der aktuellen Version probieren ?
Ist relativ viel geändert seit der Version auf dem Screenshot.

**Comment by rohne83** [comment]
Hi, mal grad schnell nebenher ausprobiert. Aber ja, ist ist leider immer noch das selbe. Logfile sieht noch ziemlich genauso aus wie das vom November.

Sobald der LKW voll ist steht da diese Meldung:
TGS 18.500 4x4 (#2): Can't find trailer target node

[log.txt](https://github.com/Courseplay/courseplay/files/5893264/log.txt)

**Comment by Tensuko** [comment]
ok, danke dir für das Update.

**Comment by rohne83** [comment]
Habs gestern mal getestet, funktioniert mit dem Fix für #7074 jetzt einwandfrei. Ich denke dieser Issue hier kann damit auch zu.
