### ISSUE TITLE
Feldreihen-Wende mit gezogenem Arbeitsgerät

### ISSUE THREAD

**Issue by rohne83** [Courseplay/courseplay#6330]
Bei der Wende am Ende der Feldreihen wird auch von Fahrzeugen mit gezogenen Arbeitsgeräten (Grubber, Sämaschine, etc) der erste Punkt jeder neuen Feldreihe vielfach nicht gerade sondern schräg angefahren, was dazu führt an den Außenseiten der dort entstehenden Kurven immer einige Teile des Feldes unbearbeitet bleiben. Das selbe auch wenn der erste Kurs-Wegpunkt von der Feldeinfahrt aus nicht genau gerade angefahren werden kann. Und das selbe in Grün passiert dann auch beim Übergang von der letzten Feldreihe zum Vorgewende: da wird am letzten Punkt die Feldreihe nicht gerade zu Ende bearbeitet sondern in einer oftmals recht scharfen Kurve direkt ins Vorgewende übergegangen, womit auch hier Teile des Feldes unbearbeitet bleiben.
Wie es aussieht ist der einzige Modus wo der erste Punkt gerade angefahren und damit alles sauber abgearbeitet wird, normal hoch/runter ohne Reihen zu überspringen. Gerade bei größeren Arbeitsgeräten mit großem Wendekreis wäre aber eigentlich das Reihen überspringen oder der kreisförmige Modus das Mittel der Wahl. Für Verbände sowieso am besten kreisförmig.
Man müsste wohl noch irgendwie dafür sorgen, dass das Arbeitsgerät zu Beginn jeder Feldreihe geradesteht, bevor losgearbeitet wird. Und am allerletzten Feldreihenpunkt ebenfalls geradeaus bis ans Ende arbeiten, bevor zum Vorgewende gewechselt wird. Auch mit ca 15% Vorgewendeüberlappung, Heruntersetzen der Arbeitsbreite um einen halben bis ganzen Meter, Arbeitsgerät heben spät und senken früh, bekomme ich da keine sauber bearbeiteten Felder hin. Die Kurven bleiben immer gleich eng, egal wieviel Vorgewende ich mache. Gibt es da noch irgendwelche weiteren Tricks?
Auf die Spitze getrieben wird das dann bei großen Pflügen, wo auch noch der dauernd wechselnde Geräteversatz dazukommt, was ebenfalls Probleme zu machen scheint. Letzteres muss ich mir aber erst nochmal genauer anschauen.
![fsScreen_2020_11_16_19_01_31](https://user-images.githubusercontent.com/71030138/99291020-74a5b680-283f-11eb-99dc-ec7af826176d.png)

**Comment by Tensuko** [comment]
Ähnlich zu #6244

**Comment by rohne83** [comment]
Habs mir grad angeschaut mit der 79. Sieht soweit super aus. Probleme macht aber noch der Übergang von den Feldreihen zum Vorgewende. Die Zugmaschine fährt immer noch in einer direkten Kurve zum ersten Vorgewendepunkt, und reißt damit das Arbeitsgerät kurz vor dem Ende der Reihe aus der Bahn. Damit bleibt dort noch ein Stück übrig, das man selbst bei 15% Vorgewende-Überlappung nicht wegbekommt
![fsScreen_2020_11_18_18_10_26](https://user-images.githubusercontent.com/71030138/99564263-7fd91d80-29ca-11eb-824b-0fe229d76db1.png)

**Comment by pvaiko** [comment]
Ich dachte dafür gibt es schon ein Issue.

**Comment by Tensuko** [comment]
@rohne83 
https://github.com/Courseplay/courseplay/releases/tag/6.02.00074


6.02.00074 Temporary fix for #6268

Do not add a turn waypoint for the headland-center
transition, instead, rely on the FieldworkAIDriver
to generate an alignment course there.

**Comment by rohne83** [comment]
Da steh ich grad auf dem Schlauch. Also mir gehts nicht darum, dass er bei dieser Lage der Übergänge Feldreihe->Vorgewende und Vorgewende->Vorgewende noch eine Ehrenrunde ums Feld dreht. Und verheddern tut er sich auch nirgends.
Sondern ich meinte dass er die letzte Feldreihe nicht richtig zu Ende fährt. Ich hab hier Arbeit beginnen auf Feldreihen, das Vorgewende wird als letztes gemacht. Wie man oben im Screenshot sieht, biegt der Traktor am Ende der Feldreihe aber schon ein paar Meter zu früh ins Vorgewende ab, obwohl der Grubber noch nicht ganz am Ende eben jener Feldreihe angekommen ist. Durch dieses zu frühe Abbiegen wird das Arbeitsgerät aus der Bahn gezogen und es bleiben ein paar Flecken unbearbeitet zurück.
Im Prinzip müsste man dafür sorgen, dass auch die letzte Bahn soweit geradeaus gearbeitet wird wie bei den anderen Feldreihen, also dass das Arbeitsgerät schnurgerade am letzten Feldreihenpunkt ankommt. Und erst ab dann per Pathfinder oder wie auch immer den ersten Punkt des Vorgewendes anfahren, um dort weiter zu machen.

**Comment by pvaiko** [comment]
#6067
