### ISSUE TITLE
Frage: Silo leeren und BGA befüllen mit Radlader

### ISSUE THREAD

**Issue by N3kr0E** [Courseplay/courseplay#6331]
Hallo zusammen,

habe mich gestern mal die Kursgestaltung zum Befüllen meiner BGA aus dem anliegenden Keilsilo beschäftigt.
Ansich klappt es alles gut, Radlader fährt rein, befüllt die Schaufel, fährt rückwärts wieder raus und befüllt die BGA. Auch die Stop&Go Befüllung klappt super.
Allerdings ist mir aufgefallen, dass der Radlader in den Kurven die Lenkung viel zu hart einschlägt und somit Zick-Zack fährt.
Beim Einfahren der Kurse habe ich eigentlich versucht darauf zu achten, möglichst grade Strecken zu fahren, allerdings muss man natürlich etwas wenden und drehen.
Der Radlader ist eine Mod (Claas Torion 1912).
Gibt es da einen Trick, dass er dieses Zick-Zack fahren nicht mehr macht?

Gruß N3kr0E

**Comment by Tensuko** [comment]
Welcher Mod genau ?
Bilder vom Kurs bitte.
Ich Arbeite auf meinem Save seit etlichen Stunden mit dem großen Claas Radlader und der hat 0 Probleme bei den Kursen.

**Comment by N3kr0E** [comment]
Einmal die Log:
[log.txt](https://github.com/Courseplay/courseplay/files/5552860/log.txt)

Hier ein Screenshot vom Kurs: 
![fsScreen_2020_11_17_11_29_10](https://user-images.githubusercontent.com/74174135/99379073-7bc4d700-28c8-11eb-8b61-81a2461c0eaa.png)

Und der Link zum Mod Raldader:
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=138645&title=fs2019

Leider ist das Silo mittlerweile leer, daher wird die Log wohl nichts anzeigen

CP Version:
6.02 (Siehe Screenshot)

**Comment by Tensuko** [comment]
> CP Version:
> 6.02 (Siehe Screenshot)

Wir haben aktuell 78 Versionen vo 6.02....
Aber ja im log und screenshot sieht man du hast die .00076

Wenn der Mod den Kurs nicht fahren kann guck ich mir bei gelgenheit an) dann ist das ein Modproblem.

**Comment by N3kr0E** [comment]
Also wie gesagt, prinzipiell funktioniert der Kurs, er macht, was er soll.
Aber gerade in den Wendemanövern schlägt er die Lenkung erst voll nach links, dann nach rechts usw. ein. Also er schlingelt sich da links an der BGA durch die Kurve.
Wäre super, wenn Du dir das mal anschauen könntest :)

**Comment by Playlord75** [comment]
Also ich wüste wo das problem liegt es ist der class radlader der fuhr bei mir au stendig zick zack mit denn standart radlader funtioniert es problemlos

**Comment by Tensuko** [comment]
Der Claas Radlader aus dem DLC funktioniert bei mir einwandfrei

**Comment by Playlord75** [comment]
Jagut lese Grade erst das es ein Mod Radlader ist 1 bei mir könnte es dran liegen weil ich VCA benutze und bei seinem Mod Radlader kann es dran liegen das die Lenk Geschwindigkeit zu hoch ist so das er schneller lenkt als CP gegen rechnen kann

**Comment by N3kr0E** [comment]
> Jagut lese Grade erst das es ein Mod Radlader ist 1 bei mir könnte es dran liegen weil ich VCA benutze und bei seinem Mod Radlader kann es dran liegen das die Lenk Geschwindigkeit zu hoch ist so das er schneller lenkt als CP gegen rechnen kann

Erstmal vielen Dank für die Rückmeldungen.
Wo kann ich denn die Lenkgeschwindigkeit einstellen?
Spiele das Spiel mit Maus und Tastatur

**Comment by Tensuko** [comment]
Sonst teste doch mal einen anderen Radlader auf dem gleichen Kurs.

**Comment by N3kr0E** [comment]
> Sonst teste doch mal einen anderen Radlader auf dem gleichen Kurs.

Jap, sobald das eine Silo fertig ist, werde ich mal den Standard Radlader nutzen bzw. erstmal schauen, ob sich der Class ist zweiten Silo ebenso verhält.
Werde aber wohl heute und morgen nicht an den Rechner kommen, berichte aber im Anschluss

**Comment by Playlord75** [comment]
Und sonst kann man das in der XML eintragen muss ich aber selbst nochmal nachschauen wo man die Geschwindigkeit zum lenken ändert ich bastel Nehmlich ehr an Anhänger etc rum als an Fahrzeugen

**Comment by N3kr0E** [comment]
Hallo zusammen,

konnte nun am Wochenende endlich mal die Kurse (bzw. einen Kurs) testen.
Es scheint hier tatsächlich am Radlader gelegen zu haben. Habe den Claas durch einen New Holland (der Standard Radlader) ersetzt und dieser fährt die Kurse super ab.

**Comment by Tensuko** [comment]
Ok, dann ist das hier Mod Issue und für uns abgehakt :)
