### ISSUE TITLE
Baling w/ Baler Addon

### ISSUE THREAD

**Issue by Jaiimez** [Courseplay/courseplay#6334]
Courseplay does not stop to unload the baler when Baler Addon is installed (it does unload, but continues to drive over material whilst unloading meaning large amounts of windrows left uncollected.

**Comment by Miketeg** [comment]
It also won't stop when spline is empty on the baller. So it will continu course without mentioning "XX needs to be refilled" and won't bale. So it will just drive over the material without picking it, without advising.

**Comment by Commissar0617** [comment]
i too experience the first issue. seems that followme handles it nicely, stops and unloads. that's the only issue i experience regarding the baler addon with CP.

**Comment by schwiti6190** [comment]
@Jaiimez, @Commissar0617  könntest ihr dieses nochmal mit der aktuellen version testen ? :)

**Comment by Commissar0617** [comment]
sure. ill just have to readd baler addon to the save. ill give it a go in the morning :)

**Comment by Commissar0617** [comment]
yep, looks good. will it notify when out of net wrap?

**Comment by schwiti6190** [comment]
@Commissar0617 could you try it I haven't testet it.

**Comment by Commissar0617** [comment]
The baling is working.  Not sure about netting yet. Ill have to try it sometime.

**Comment by Tensuko** [comment]
@Commissar0617 a feedback would be very welcome, if I can close this Issue...

**Comment by Tensuko** [comment]
Will close this one for now, let us know if something is wrong.

**Comment by Commissar0617** [comment]
i have yet to run out of the netting/twine. ill let you know if i run into an issue. tbh, there's probably bigger fish to fry

**Comment by Miketeg** [comment]
I confirm that when round baler (did not test square yet) ran out of net, worker stops with a "xxx needs to be refilled"

Good job team!

**Comment by Tensuko** [comment]
Awesome, thx for your feedback
