### ISSUE TITLE
Courseplay Unloader Option Not Available

### ISSUE THREAD

**Issue by WampusCatOG** [Courseplay/courseplay#6335]
I have been researching this issue and trouble shooting for 8hrs plus as Preface...

CP seems to not allow the "unloader/combine unload" option to be accessible while using trailers that are modded.  I have narrowed  it down to the "updatemass="false" command in the trailer .xml files.  I have tried this with multiple high capacity/modded trailers and the result seems to be consistent.

Hope this is helpful!

PS I have also found that the collision avoidance is not working when using multiple vehicles to unload a single forage harvester amongst themselfs.  All other vehicles are untouched

**Comment by Tensuko** [comment]
high capacity ?
Also I can tell you I use a lot of Trailer Mods and all work just fine.
Not going to support random Modded Trailers from everywhere, espacialy 'high capacity'

your PS.... well check #5272
