### ISSUE TITLE
LUA call stack:

### ISSUE THREAD

**Issue by Racker2409** [Courseplay/courseplay#6336]
Translated with DeepL

Hello dear team. 
I'm playing the current version 6.02.00078 and since today I get this error.
I haven't added new mods to the mods folder for days.

Maybe someone can help me.

Greeting Manni 

[log.txt](https://github.com/Courseplay/courseplay/files/5560013/log.txt)

**Comment by Tensuko** [comment]
Do you have a Platformtrailer attached on any Tractor when loading the game ?

**Comment by Racker2409** [comment]
Ja ist einer aus dem grundspiel

**Comment by Racker2409** [comment]
ich werde diesem Löschen und noch einmal Probieren.

**Comment by Racker2409** [comment]
Es könnte soooo einfach sein, wenn das Problem nicht direkt vorm Monitor sitzen würde.

Vielen dank Tensuko für den wink und die wirklich schnelle Hilfe.

Gruß Manni

**Comment by Tensuko** [comment]
Kleine Info am Rande:
Der Callstack ist in dem Fall harmlos, da er (bisher) keine Auswirkungen hatte.
