### ISSUE TITLE
Problem beim Silo modus Aufschütten 

### ISSUE THREAD

**Issue by Playlord75** [Courseplay/courseplay#6337]
ich habe das problem das mein CP fahrer nach ein paar mal schieben nurnoch in die wand fahren will was kann ich dageen machen 
![fsScreen_2020_11_19_00_33_38](https://user-images.githubusercontent.com/71101944/99601208-3820b900-29ff-11eb-8ef4-1c3486dbca1e.png) und fängt danach hier wieder an 
![fsScreen_2020_11_19_00_37_18](https://user-images.githubusercontent.com/71101944/99601304-728a5600-29ff-11eb-9eb1-962adbb62fd1.png)

**Comment by Playlord75** [comment]
was noch beim fehler suchen helfen könnte wehre trit auch auf sobald das silo fertig geschoben ist im 17 wahr es ja so sobald vorne im silo nichts liegt fährt er auf seine warte position im 19 macht er ja einfach weiter wie man auf diesem bild sieht 
![fsScreen_2020_11_19_00_47_31](https://user-images.githubusercontent.com/71101944/99602042-027ccf80-2a01-11eb-8a33-684b2155dca4.png)

**Comment by Tensuko** [comment]
100%ig gut läuft der Modus noch nicht.
Müssen wir uns anschauen, aber zur Zeit haben wir andere Dinge zu tun.

**Comment by Playlord75** [comment]
Halb Wegs gut laufen tut er ja mit der 076 wieder nur halt diese Aussetzer zwischendrin dass er gerne Mal in eine Wand fährt oder hatte gestern auch eine Situation wo er links in die Wand gefahren ist wie bleibt mir ein Rätsel (ich glaube er mag es nicht wenn ich weg bin weil er hat komischerweise nur Probleme wenn ich nicht zuschaue 😂)

**Comment by Tensuko** [comment]
Schildbreite anpassen ?

**Comment by Playlord75** [comment]
Hab ich schon probiert egal ob 4 oder 8m hat immer die selben Probleme aber ist ja auch nicht so schlimm Mal kurz eingreifen geht ja

**Comment by Playlord75** [comment]
Ich glaube die Schild breite anzupassen bringt nichts weil in der log wenn ich die 10 an hab sagt er mir egal ob ich 4oder 8 Meter eingestellt hat irgendwas mit ( eigene Übersetzung) schiebe mit 5,8m breite frischmais im Raster 4 9 kann dir nacher wenn ich Zuhause bin einmal denn richtigen Log Eintrag davon schicken

**Comment by Playlord75** [comment]
2020-11-19 12:32 :14 [dbg10 lp3229] 1050 (#1): Bunker width 19.5, working width 5.8 (passed in)
2020-11-19 12:32 :14 [dbg10 lp3229] 1050 (#1): Bunkersilo filled with CHOPPEDMAIZE(106) will be devided in 9 lines and 4 columns
2020-11-19 12:32 :14 [dbg10 lp3231] 1050 (#1): Stopped slipping
2020-11-19 12:32 :14 [dbg10 lp3233] 1050 (#1): Unblocked...
2020-11-19 12:32 :31 [dbg10 lp3721] 1050 (#1): dropout fillLevel das ist der log Eintrag vom schieben und da steht der Bunker ist 19,5 m und er versucht dieses mit 5,8 m anzugleichen obwohl ich 5m eingestellt hab sieht so aus als würde sich CP die breite vom Schild selber berechnen

**Comment by Tensuko** [comment]
Wenn wir ein Breiteres Schild berechnen als wir haben ist das um so besser!
Besser als wenn wir nur mit 4,5m rechnen aber 5m haben...

Ich muss mir das anschauen, an sich ging es die letzten male bei mir.

**Comment by kallitaxi** [comment]
Das mit dem links in die Mauer fahren habe ich auch. Sobald der Silo anfängt sich ze füllen passiert das bei mir.

**Comment by Tensuko** [comment]
Sollte mit .00015 passen, bitte einmal ausprobieren.
Die Schildbreite wird nun richtig genutzt und er fährt parallel zur Wand.
Es kann an gewissen Stellen natürlich dazu kommen, dass er beim reindrehen die Wand etwa streift.

**Comment by kallitaxi** [comment]
Das funktioniert bei mir jetzt einwandfrei.

**Comment by Tensuko** [comment]
Ok ich mache hier erst einmal zu, es wird noch weitere Anpassungen geben für den Mode10, aber gegen die Wand fahren sollte so erstmal weniger bis ganz weg sein, da man die Breite ggf anpassen kann.
