### ISSUE TITLE
Häcksler verbraucht beim warten ganzen Sprit

### ISSUE THREAD

**Issue by Rumspringa90** [Courseplay/courseplay#6338]
Moin,
mir ist eben beim häckseln aufgefallen, das der Häcksler, wenn er auf einen Abfahrer wartet, den ganzen Sprit verbraucht da er mit voller Drehzahl stehen bleibt und dabei 260l/h verbraucht. Habt das eben nochmal mit der aktuellsten Version getestet.

![Unbenannt](https://user-images.githubusercontent.com/50840355/99671498-67bcd900-2a72-11eb-818c-60f3239323e6.jpg)

**Comment by Tensuko** [comment]
Das sind 2 unterschiedliche Situationen!

Drescher/Roder schalten die Geräte nach einiger Zeit ab, wenn sie voll sind, das klappt auch. Man könnte eventuell die Zeit kürzen, aber erst einmal werden wir das so lassen.

Was hier passiert ist, er kann ja theoretisch arbeiten, aber nicht abladen.
Und so wie das für mich aussieht ist das nur ein Wendemanöver, da werden wir bestimmt nicht abschalten.

Lange Wartezeiten von Häckslern bis der Abfahrer wieder da ist, sollte hoffentlich bald erledigt sein, wenn wir mehrere Abfaher nutzen können, das befindet sich aktuell in Entwicklung.
