### ISSUE TITLE
Field Generation starting in wrong place

### ISSUE THREAD

**Issue by Thorn177** [Courseplay/courseplay#6340]
When generating course for fieldwork and seeding fertilizing, after a while of game play, the course begins starting in the wrong corner.  I have been noticing this behavior since around build 6.02.0076 across a few maps.  
I typically start in the SW corner of a field with a plain up and down route, with no headlands, and adjust the working width to the minimum that does not add an extra lane.  Once the bug starts occurring, it starts from the NW corner.  Adjusting the working width incrementally in either direction will eventually flip it back to the SW corner, and then back to NW.  Not all fields are affected, only a few.  The other three starting points work properly.  
The first map this occurred on has 95 fields, so I switched to a Ravenswood map with little game play on it and did some further testing.  Bug was present form the start.  I bought all the fields and tested each field with all four corners as starting points.  Fields 4, 14 and 15 bugged on SW, 6, 10, 13 bugged on NW, 8 on NE and 6, 12 and 17 on SE.  Switching tools produces a similar, but not identical list.  
I started a new game on Fellsbrunn with just the Anderson DLC, the Mahindra vehicles, Money tool and CP.  I took the following actions before the bug showed up.  Each time I generated a course it was from SW corner and cycled through all the fields before setting to either Field 19 or 20 and adjusting the working width.  Field 33 always started from NW corner due to shape.  All work was with CP generated routes, as I normally set up: SW corner and adjusted width.
	Activated Money Tool a few times.
	Bought all the fields.
	Harvested Field 19.
	Cultivated Field 20. (All Field 20 work was while Field 19 was being harvested)
	Bought a fertilizer spreader, tractor, weight and 14 fertilizer pallets.
	Fertilized Field 20.
	Seeded Field 20.
	Bought a windrower, weight and tractor.
	Bug showed up on Field 1 with the windrower. (Harvester had finished, seeder still going)
	Saved the game.  Collected the CP field data on a restart after activating Developer Console.

![fsScreen_2020_11_19_21_54_32](https://user-images.githubusercontent.com/57279160/99695723-daf13a00-2ac8-11eb-9067-7283df4ac351.png)

log file
[log.txt](https://github.com/Courseplay/courseplay/files/5568424/log.txt)

CP field data file
https://gist.github.com/Thorn177/8f51f9c8923930cf2de0748fd73d864f

Fellsbrun save game
[savegame3.zip](https://github.com/Courseplay/courseplay/files/5568386/savegame3.zip)

**Comment by Tensuko** [comment]
debugchannel7 active when generate fieldcourse, then post logfile so we can see whats going up.

**Comment by Thorn177** [comment]
Oops.  Try this one.
[log.txt](https://github.com/Courseplay/courseplay/files/5573154/log.txt)
