### ISSUE TITLE
Course generator extra Headland round

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#6341]
Hey,

When i generate a course, with two headlands, to be worked at teh end, the sprayer drives to the start of the inner headland and driver around the whole field not sprayin, before beginnig to work the headlands.

Regards,
JDTiger

**Comment by Tensuko** [comment]
Not a bug, thats transition to fieldrows.
Try out to generate it a differen way and I think we have a similar Issue somewhere.
