### ISSUE TITLE
Mode 3 multiple graincarts

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#6342]
hey,
If i understood the mode 2/3 post correctly, it should be possible to have multiple graincarts on the field at the same time.

My problem is, that even though both carts have the combines assigned, only one cart is going around unloading the combines at a time.

Or were the conflicts mentioned assignment conflicts (one cart blocks all combines)?

Regards,
JDTiger

**Comment by Tensuko** [comment]
> If i understood the mode 2/3 post correctly, it should be possible to have multiple graincarts on the field at the same time.

No. Why should 2 unloader drive to one combine to unload it ?!
Doesn't make sence... If you have more Combines, assign one cart to each one if you want to do it like that, but keep in mind that conflcits between unloaders are not solved yet.
