### ISSUE TITLE
Mode3 graincarts circling behind combines

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#6343]
Hey,

When the combines are standing, i often have the problem, that the graincart is just driving circles behind the combine, but not emptying it.

When activating the temporary waupoint display, i can see, that the route is a 3/4 circle, ending in a straight line to the combinem, but everytime the cart tries to exit the circle, it resets the route and continues to circle.

Regards,
JDTiger

**Comment by Tensuko** [comment]
#5272 
Also use offsets to adjust things.

**Comment by JDTiger** [comment]
Sorry,
I should have taken more tome before filing the issues.

here is a video of the situation:
https://youtu.be/6qBQegJbqoY

And here is the Log with Channels 4,7 and 14:
[log.txt](https://github.com/Courseplay/courseplay/files/5574943/log.txt)

I vow to do better in the future

Best Regards,
JDTiger

**Comment by Tensuko** [comment]
Do you have a manual offset for your driver ?

**Comment by JDTiger** [comment]
No, it was set to auto, but moving the offsets did not stop the circeling.

As seen in the vid, enlarging the turn radius just made the circle larger and the other offests did not change anything in the circeling behaviour.

**Comment by JDTiger** [comment]
Soo, i mus once again state how sorry i am...

The problem was indeed caused by a offset, not on the graincart but on the combine. This was set to continue harvest with all of my combines, while under the influence of  #6345 .

Because the rightmost combine would not have the same Waypoints as the other two, combine convoy did not work, so i just set combine three (the one, where the unloaders would later drive circles) to run center lane with an header offset of one lane.

This offset seems to have caused the issues with the unloaders driving circles.

**Comment by Tensuko** [comment]
oh okay, well thats nice to know that this happens, won't do anything about it but when stuff like that happens again I can at least check for this :) closing now then if it works fine now :)
