### ISSUE TITLE
Mode 6 Lands  combine convoy

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#6344]
Hey, 
I ma harvesting with 3 combines in Lands mode with combine convoy enabled.

If the third combine in the comvoy gets stuck, becaus the unloaders are too slow, it sometimes happens, that the first combine tries to lap No.3.

is it possible to extend the combine convoy mode, to look ahead for combines, that are stuck on the previous lap?

Regards,
JDTiger

**Comment by Tensuko** [comment]
Thats a problem of convoy on big fields... #6011

**Comment by JDTiger** [comment]
Edited the first post and title to better show what i mean, this is a problem different from the one in the linked issue.
It is not one combine overtaking a leading one, it is the leading one lapping the trailing one.

this results in the leading combine always having the pipe inside the fruit

**Comment by Tensuko** [comment]
We have that Issue and suggestion already anyway...
