### ISSUE TITLE
Mode 6 Course generator 3 combines

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#6345]
Hey, 
I am harvesting with 3 combines in Lands mode with combine convoy enabled.

I have generated the course with 1 round of headlands, to be harvested, before the inner parts.
Combines one (Offset 1 left) and two (offset center) use the start Flag as WP1. Combine three (Offset 1 right) uses the First pass of the inner portion as WP1 and can not be started to work the headlands at all, it always goes the the nearest innerfield track.

Regards,
JDTiger

**Comment by Tensuko** [comment]
I bet you have the 1st WP at a corner, thats why it is not working correctly.

And by all your Issues I just closed, what about more details like pics and logfiles and also search github for existing problems before post a wall of new Issues...

**Comment by JDTiger** [comment]
Yes, definitivly was the issue, though it is interesting, that thisphenomenon appears

**Comment by Tensuko** [comment]
That is becouse the offsetcourse will get generated but that doesn't work if the start is to close to the corner.
