### ISSUE TITLE
Can't see the harvester in the combined fields

### ISSUE THREAD

**Issue by Roma-85** [Courseplay/courseplay#6347]
Hello. Thank you so much for your work. I would be grateful for your help. I've been suffering for a week now. When I combine 2 fields, then when generating a route, I choose to define the boundaries of the field and save. Then the tractor does not see the harvester in this field. Or maybe there is a cocoito option to get around it?

**Comment by Tensuko** [comment]
#5977 Duplicate.

Still have to check on this one, sry but super busy with so many stuff (private and CP).
