### ISSUE TITLE
The tractor does not see the combine

### ISSUE THREAD

**Issue by Roma-85** [Courseplay/courseplay#6348]
Hello. Thank you so much for your work. I would be grateful for your help. I've been suffering for a week now. When I combine 2 fields, then when generating a route, I choose to define the boundaries of the field and save the new field. Then the tractor does not see the harvester in this field. Or maybe there is a cocoito option to get around it?

**Comment by Tensuko** [comment]
Are you kidding me ?
#5977 Duplicate.
#6347 Duplicate!

**Comment by Roma-85** [comment]
извените пожалуйста, я впервые на етом сайте. Подумал что вы просто удалили мое сообщение. А оно оказывается в закрытых. Перешел на вашу ссылку. Огромное спасибо.

**Comment by Tensuko** [comment]
okay, but don't worry I read all but duplicate means we have an Issue about that. :)
