### ISSUE TITLE
.79 Client Crash during field scan after entering a save

### ISSUE THREAD

**Issue by Jaiimez** [Courseplay/courseplay#6350]
As titled says, updated to .79, attempted to load the save, it starts scanning fields, then the giants client goes not responding, it loads fine with courseplay disabled.

See log.

https://pastebin.com/9Dr498RK

**Comment by Tensuko** [comment]
On what Map are you playing ?

**Comment by Jaiimez** [comment]
Eiersholt, however, I think it's a corruped save, as I tried a few other bits and pieces, disabling some other new mods, the only thing that helped was going to a savegame backup.
