### ISSUE TITLE
No collision detection/Keine Kollisionserkennung

### ISSUE THREAD

**Issue by DerBauer2** [Courseplay/courseplay#6352]
CP Version: 6.02.00079
Map: Nordfriesische Marsch 4fach 

EN:
For me it was the case that the vehicles did not recognize each other. Therefore I started a save with only necessary mods. The result was that the error persisted. Since the card is used by many, the error is probably in the detail. Question is why it doesn't work? How can you continue to test there? Or does it have to be fixed by CP?

DE:
Bei mir war der Fall das die Fahrzeuge sich nicht erkannten. Daher hatte ich ein Save gestartet nur mit Notwenigen Mods. Resultat war das der Fehler weiterhin bestanden. Da die Karte ja von vielen genutz wird liegt der Fehler wohl im Detail. Frage ist warum es nicht geht? Wie kann man dort weiter testen? Oder muss er von CP gefixt werden? 
Paar bilder :
![20201121135059_1](https://user-images.githubusercontent.com/60297613/99877931-e7c57900-2c01-11eb-9dd9-94ebdfe2e24d.jpg)
![20201121125441_1](https://user-images.githubusercontent.com/60297613/99877932-e8f6a600-2c01-11eb-8091-9d1ab8d56082.jpg)
![20201121130402_1](https://user-images.githubusercontent.com/60297613/99877933-e98f3c80-2c01-11eb-83a0-b3d748813e27.jpg)
![20201121130713_1](https://user-images.githubusercontent.com/60297613/99877934-e98f3c80-2c01-11eb-8450-dcc1e516e33a.jpg)
![20201121132044_1](https://user-images.githubusercontent.com/60297613/99877935-ea27d300-2c01-11eb-9a3c-6d5bdc7cc096.jpg)

Log:
[log.txt](https://github.com/Courseplay/courseplay/files/5577648/log.txt)

Log Channel 4,7,14
[log.txt](https://github.com/Courseplay/courseplay/files/5577656/log.txt)

**Comment by DerBauer2** [comment]
Log Channel 4,7,14
[log.txt](https://github.com/Courseplay/courseplay/files/5577654/log.txt)

**Comment by Tensuko** [comment]
2 Abfahrer sind noch nicht unterstützt, allerdings wundert mich, dass auf den normalen Kurs so ein Konflikt entsteht, allerdings ist das ein Mod und da können wir nichts machen. Abwarten bis unser neues Trafficsystem fertig ist vlt klappt es dann.

**Comment by DerBauer2** [comment]
okay danke für die Info

**Comment by DerBauer2** [comment]
kann ich wo erlesen was alles unterstütz wird und was nicht? damit man nicht überflüssige issus schreibt? Fals das hir noch gelsen wird

**Comment by Tensuko** [comment]
#5272
