### ISSUE TITLE
Abfahrer genariert strecke duich fluss und kann nicht mehr benutzt werden 

### ISSUE THREAD

**Issue by Playlord75** [Courseplay/courseplay#6353]
hab ein preoblem mein abfahrer generiert sogut wie edesmal wenn er auf dem feld 18 oben links steht einen weg duich denn fluss 
![fsScreen_2020_11_22_00_19_31](https://user-images.githubusercontent.com/71101944/99889845-3f430380-2c59-11eb-8959-8b98ce86bb35.png)
um denn drescher zu finden und wie man ls kennt kann man nicht mehr einsteigen solange man sie nicht zurück setzt
![fsScreen_2020_11_22_00_19_40](https://user-images.githubusercontent.com/71101944/99889787-cf347d80-2c58-11eb-9936-0036ea592e33.png)
wie kommt cp auf die idee denn kurs nicht übers feld zu generieren? gäbe es eine möglichkeit cp zu sagen du suchst denn weg übers feld und nicht quer über die map oder wehre das zuviel arbeit dieses einzubauen ? oder gibt es dafür schon eine möglichkeit

**Comment by Tensuko** [comment]
#5982
