### ISSUE TITLE
right hand discharge combine pulls to the right to discharge

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/courseplay#6354]
![20201121234945_1](https://user-images.githubusercontent.com/5993529/99896272-8d093d00-2c54-11eb-996f-34b958ee82c1.jpg)
instead of chopping into the field as combines nornally would, it drives off the field.
course is set for counter-clockwise headland due to the right hand discharge

**Comment by Commissar0617** [comment]
this is also an issue with the grimme potato harvester

**Comment by Tensuko** [comment]
#5012 combine the Issues, could be the same case, yes.
