### ISSUE TITLE
Overload mode crash my game

### ISSUE THREAD

**Issue by Venca03** [Courseplay/courseplay#6355]
Everytime I try to set up an overload plan, HUD completely disappears and the game stops to react to my keyboard. The only thing I can do is rotate the camera with my mouse... logfile attached.
[log.txt](https://github.com/Courseplay/courseplay/files/5579406/log.txt)

**Comment by Tensuko** [comment]
(Version: 6.02.00077) FS19_Courseplay
-> https://github.com/Courseplay/courseplay/wiki
-> https://github.com/Courseplay/courseplay/releases
-> 6.02.00078 Fixes #6327
