### ISSUE TITLE
Wie kann ich die Silobreite manuell einstellen

### ISSUE THREAD

**Issue by Martin190606** [Courseplay/courseplay#6358]
Mein Traktor fährt immer gegen die Silowand, ich wollte nur kurz fragen, ob es eine Methode gibt wie man die Silobreite manuell einstellen kann. Ich würde mich sehr über eine Antwort freuen.

Mit freundlichen Grüßen.

**Comment by Tensuko** [comment]
Geht nicht, wird es nicht geben.
Silo verteilen und verdichten ? Gibts nen Issue zu.
Aufschütten mit Schild ? Schildbreite einstellen.
