### ISSUE TITLE
Combine wont self unload

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#6359]
I use Claas Lexion 6700 mod.
https://www.modhoster.com/mods/claas-lexion-6700-pack

It wont self unload.
I tested with default combines from base game and they work fine.
log file says "
g_combineUnloadManager:getHasUnloaders(vehicle):false"
Here is log file.
[log.txt](https://github.com/Courseplay/courseplay/files/5580070/log.txt)

**Comment by Tensuko** [comment]
g_combineUnloadManager:getHasUnloaders(vehicle):false"

That got nothing to do with selfunloading...

Selfunloading must be activated in adv. settings and is looking for a trailer 20m within the Fieldborder.

**Comment by Tensuko** [comment]
Tested and it does what it should do.
![fsScreen_2020_11_22_21_26_53](https://user-images.githubusercontent.com/27344744/99916276-7c66ce80-2d09-11eb-9e9a-3c92c2968f1a.png)

**Comment by bojanh66** [comment]
Yes, i have activated it in CP options.
With Lexion 6700 mod, it doesnt work.
But when i tried some other harvester from base game, it works perfect.
Could it be mod problem ?
I can make video and upload if it helps.

**Comment by pvaiko** [comment]
That would help. Or if you told us what exactly 'does not work' mean.

**Comment by bojanh66** [comment]
I dont know how, but it started to work somehow.
Here is the video, you can see that combine would not unload at first, but then at second try, it started to unload...dont understand what happened.
i'm sorry for inconvenience caused.

https://youtu.be/bqXUlyN9Aj0
