### ISSUE TITLE
Drescher wartet nicht bis Schneidwerk ausgeklappt ist

### ISSUE THREAD

**Issue by Rumspringa90** [Courseplay/courseplay#6360]
Nabend,

ich hab ein Problem mit den [Cressoni CRX](https://www.farming-simulator.com/mod.php?lang=de&country=at&mod_id=146008) Schneidwerken. 
Und zwar wartet CP nicht darauf bis es ganz ausgeklappt ist sondern schaltet es schon 2-3 Sekunden bevor es ganz ausgeklappt ist ein. Dadurch wird aber der Drescher nicht eingeschaltet und das Schneidwerk auch nicht gesenkt. 
Hier ein Video dazu: https://youtu.be/S7GGKgkR110

Ich denke das es ein Fehler im Mod sein müsste, da es sich zu früh einschalten lässt. Habe das dem Modder auch schon mitgeteilt. Das ist aber nur eine Vermutung meinerseits. 

Gruß Henne

Edit:
Antwort vom Modder: 
"It starts before the unfolding animation, cause it's an complicate system of unfolding I think Is better to open It manually and then start the courseplay, I no have idea on how to fix that."

**Comment by Tensuko** [comment]
I wonder a bit about that, as I used those too.
I will have a look maybe I figure something out.

**Comment by Rumspringa90** [comment]
Moin Tensuko,
erstmal das wichtigste zuerst: Alles Gute noch nachträglich zum Geburtstag.

Da du sagtest das das bei dir nicht so ist, habe ich mal nur mit CP und Cressoni versucht auf der Standard Map. Und ich stimme dir zu es funktioniert einwandfrei. 
Ich habe auch den Mod gefunden der den Fehler verursacht. Und zwar ist das die HoT online F4rm 21.
Das Problem scheint hier zu sein, dass nicht wie bei der Standardkarte eine Meldung kommt "Schneidwerk erst ausklappen" wenn man den Drescher einschalten will.

Ich werde mich mal mit denen in Verbindung setzen.

**Comment by Tensuko** [comment]
Das macht die Sache noch merkwürdiger, warum das an der Map liegen sollte.
Was du bitte mal probieren kannst ist, in wie weit die Position des Dreschers entscheident ist.
Also wie weit weg sind wir vom Startpunkt, wenn man CP startet.
Ich positioniere den Drescher ausgewohnheit schon immer recht dicht an den ersten Wegpunkte.

**Comment by Rumspringa90** [comment]
Ob man am Startpunkt startet oder mitten drin an einem beliebigen Punkt macht kein unterschied. Einzig das manuelle ausklappen des Schneidwerkes funktioniert. 

Habe aber möglicherweise den Verursacher in der Map gefunden.

Dort gibt es ein Script:
```
function changeaddFillUnitFillLevel(vehicle, superFunc, farmId, fillUnitIndex, fillLevelDelta, fillTypeIndex, toolType, fillPositionData)
    if fillTypeIndex == FillType.CORN2 then
        fillTypeIndex = FillType.MAIZE
    end

    return superFunc(vehicle, farmId, fillUnitIndex, fillLevelDelta, fillTypeIndex, toolType, fillPositionData)
end

function changeverifyCombine(vehicle, superFunc, fruitType, outputFillType)
    if outputFillType == FillType.CORN2 then
        outputFillType = FillType.MAIZE
    end
    return superFunc(vehicle,fruitType, outputFillType)
end

function combine_registerOverwrittenFunctions(vehicleType)
    SpecializationUtil.registerOverwrittenFunction(vehicleType, "addFillUnitFillLevel", changeaddFillUnitFillLevel)
    SpecializationUtil.registerOverwrittenFunction(vehicleType, "verifyCombine", changeverifyCombine)
end


Combine.registerOverwrittenFunctions=Utils.overwrittenFunction(Combine.registerOverwrittenFunctions, combine_registerOverwrittenFunctions)
```

Wenn dies nicht geladen wird, funktioniert es. 
Versuche das grad zu verstehen

**Comment by Tensuko** [comment]
Kannst du mal schauen was der normale Helfer mit dem Schneidwerk auf der Map mit dem Script macht ?

**Comment by Rumspringa90** [comment]
der normale Helfer versucht ihn direkt einzuschalten und abzusenken und fängt dann an es auszuklappen. Schaltet sich direkt wieder aus und wird wieder angehoben. Das wiederholt sich solange, bis das Schneidwerk ausgeklappt ist und beginnt dann mit der Arbeit ganz normal.

**Comment by Tensuko** [comment]
Ok aber läuft also auch nicht richtig, im Grunde gleiches Problem, das wollte ich nur wissen :)
Dann ist das ein Problem der Map bzw vom Script und nicht CP.

Ich mache dies Issue dann zu, weil das ist eine Sache der Mapper :)
