### ISSUE TITLE
sell courses

### ISSUE THREAD

**Issue by thomas877** [Courseplay/courseplay#6362]
when i set up a course to sell grain it fill up with grain but tip bk into the silo it just took it out form not to sure what it is is me not doing something right or is it just a bug

**Comment by Tensuko** [comment]
logfile with debugchannel 1 and 2 active and a screenshot of your course.

**Comment by thomas877** [comment]
![fsScreen_2020_11_23_18_54_46](https://user-images.githubusercontent.com/70026937/100003193-97931600-2dbd-11eb-8d90-850b067718a2.png)
![fsScreen_2020_11_23_18_55_02](https://user-images.githubusercontent.com/70026937/100003202-995cd980-2dbd-11eb-9c92-08319b374357.png)
t
![fsScreen_2020_11_23_18_56_33](https://user-images.githubusercontent.com/70026937/100003205-9b269d00-2dbd-11eb-8fa1-bc8a41f30c1b.png)
There you going

**Comment by Tensuko** [comment]
Hmm maybe the problem is, that you go to early in the corner after the Start WP.
We allow the driver to unload into trigger a few WP after the 1st one.
Would you have enough space to drive more straight out of your silo in the other way ?

@schwiti6190 how far do we drive before we unload into a trigger again ?

**Comment by thomas877** [comment]
iam try to fill up the trailer with grain to sell but soon as it fill it empty straight away

**Comment by Tensuko** [comment]
your stop point is also totaly out of place....
![Mode1](https://user-images.githubusercontent.com/27344744/100020690-84de0880-2de0-11eb-9f51-5ac9ab7a3d3a.png)
Your 1st WP after start must be more far away from trigger.
Thats why I say if you don't have enough place in that one direction, try it in the other direction, if you got more space to drive the 1st few meters in a straight line.

**Comment by thomas877** [comment]
i try that  and it still doing it i think it pick both trigger up the tip trigger  and the refill trigger i think

**Comment by Tensuko** [comment]
If you do it correct with the course, it just does it correct...
![fsScreen_2020_11_24_11_13_22](https://user-images.githubusercontent.com/27344744/100080536-3cf1cc80-2e46-11eb-8870-5938df43c1c6.png)
![fsScreen_2020_11_24_11_13_34](https://user-images.githubusercontent.com/27344744/100080552-411dea00-2e46-11eb-9710-13944272dece.png)


Like I said, more straight after the 1st WP.
Sure we know about those doubletrigger Silos and sure we did something so they don't unload again directly.
