### ISSUE TITLE
Filling seeds with an auger trailer 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#6370]
Hello I’m trying to fill seeds with an auger trailer which I dunno if it is possible but if the courseplay machine approaches the auger it’s fails to open the lid preventing the seeds from being loaded. Big bags opens it as you approach it

**Comment by Tensuko** [comment]
The AugerWagon must be driven by a Mode8 Driver, then it will also open the Lids.
But I just found a problem with our new swerve system for this, we kinda dodge the auger wagon, will check for a fix and also if we can refill on a standing auger wagon.

**Comment by matty2123** [comment]
I’m just leaving the auger static not using it on courseplay so I want the machine seeding to drive to the auger open cover and refill and resume if that makes sense

**Comment by Tensuko** [comment]
![fsScreen_2020_11_24_18_05_09](https://user-images.githubusercontent.com/27344744/100127702-a93cf200-2e7f-11eb-8b81-a1833b1da68d.png)
Just tried with active Mode8 driver, it works just fine.
For Standing Auger Wagon, as I said, we will see if we can do something.

**Comment by Tensuko** [comment]
@schwiti6190 told me it should work if you place a waitpoint, not sure if the lids will open and it is a bit tricky to place the wait point at the right spot, but you can give it a try :)

**Comment by Tensuko** [comment]
Set the min Value for your Seeder for Seed up to 99% min value and use a waitpoint, then it should reload seed :)

**Comment by matty2123** [comment]
How do I change it to 99 it won’t change from 100?

**Comment by Tensuko** [comment]
Try with 100, try with 98, doesn't matter for the function itself.

**Comment by matty2123** [comment]
So If I press the arrow it should change it up and down right?

**Comment by Tensuko** [comment]
No, scroll wheel. Up down is for order change.

**Comment by matty2123** [comment]
Will try tomorrow and report back
