### ISSUE TITLE
Sprayer speed limited to 3 MPH

### ISSUE THREAD

**Issue by jspring0811** [Courseplay/courseplay#6374]
Hello,  I have just noticed since a recent release of Courseplay (I have 6.03.00001 currently installed) that this self-propelled sprayer (KMN Modding R4045) will now only go 3 MPH under courseplay.   It goes 19 MPH manually and also with a regular helper activated.  A few days ago it was working with Courseplay (but I'm not exactly sure with which CP version it was working).

Might be seeing this issue with some other implements too (default Challenger pulling default cultivator is slower under CP).

What info/channels would help to debug?

Thanks!
Jason

**Comment by Tensuko** [comment]
What cultivator are you talking about ?

**Comment by ontot** [comment]
have you tried to increase the speed with key 2?

**Comment by jspring0811** [comment]
> 
> 
> have you tried to increase the speed with key 2?

Yes, cruise control is set at max (37 MPH) for this vehicle.  I have also tried variations in CP speed limits.  Still no change.

Jason

**Comment by VergylTantor** [comment]
I think this might be a mod issue. I had this mod and the issue began for me with the 6.03 update. My best guess is that CP is seeing the sprayer attachment as a separate object and is slowing down to avoid a "collision." I changed to the John Deere 4940 mod by Custom Modding that is available on the mod hub and the issue went away.

**Comment by Tensuko** [comment]
So the ModHub Version does work fine, but the (whatever source) of the other KMN R4045 doesn't work ?

**Comment by VergylTantor** [comment]
Correct

**Comment by VergylTantor** [comment]
I was using an older version of the R4045 mod and found the latest version on what appears to be the mod authors Facebook page. https://www.facebook.com/permasmodding/posts/2741670775886257
The vehicle type has been changed to "manuresystemR4045Spray" but the problem is still there so it looks like there are other problems with R4045/CP compatibility.

**Comment by jspring0811** [comment]
I do have the Custom Modding 4940 to use as a replacement.  The only benefit the R4045 had was, in tight spaces, the boom arms are collision-free.  The CM 4940 is also a nice model.

**Comment by Tensuko** [comment]
Can we close this then as a Mod Issue ?

**Comment by VergylTantor** [comment]
jspring, I contacted the mod author and he says he will take a look at it so watch for an update.

**Comment by VergylTantor** [comment]
jspring
I contacted the mod author and he/she said that they will take a look at the issue with the R4045 mod so watch for and update.

out

**Comment by jspring0811** [comment]
Yes, I'm fine with closing the CP issue.
