### ISSUE TITLE
Grass unloading.

### ISSUE THREAD

**Issue by Shalda** [Courseplay/courseplay#6375]
Hello. I am trying to collect grass with a loading wagon, have two courses for collecting and unloading, but after wagon completely filled, I only see the message:  “work tool needs to be unloaded”, and it’s doesn’t go to unload course. At the same time, the same course works fine with straw. 
![20201125120304_1](https://user-images.githubusercontent.com/22412765/100217072-b90a1400-2f1b-11eb-81ab-7fee29d38ca4.jpg)

**Comment by Shalda** [comment]
My  problem was with waiting points.
As I understand, when we auto-generate the course, the courseplay itself inserts waiting points at the beginning and at the end of the path. But if I do it manually, the vehicle, after has filled, will pass all the remaining points on the field. How to make it immediately turn to unloading course?

**Comment by Tensuko** [comment]
We don't insert waiting points anywhere.

**Comment by Shalda** [comment]
At the beginning and end of the course I saw this points. After I added them to my route, the vehicle began to switch to the unloading course, but not immediately
![waiting](https://user-images.githubusercontent.com/22412765/100229693-502b9780-2f2d-11eb-9558-b905ae5a6bfd.jpg)

**Comment by Tensuko** [comment]
Okay this is even new to me that those start and stop points for a generated fieldworkcourse are set as waitpoints...

Is your course working now then ?

What are you mean with 'not immediately' as it should generate a course to the unload course to get a way.
Wich is problematic as mowed grass fields are basically still fruit.

**Comment by Shalda** [comment]
Not exactly.
Courses generated by CP: after filling the trailer, doesn’t matter with grass or straw, the vehicle switches from the main to the unload course.
Courses that I created: when the vehicle is full, it goes to the last point of the main course and only then switches to unload.

**Comment by Misamangame** [comment]
This always worked only on generated courses. It never worked on manually created courses. What you can do is to plow the meadow you working on the edges, make new field like that. manually scan field save it under some number and then you can generate courses for cutting/balling swathing and unloading course like from any other field.  You can reseed plowed part with grass as well and unless you owerwrite that number you saved it will stays within the borders you saved.

**Comment by Tensuko** [comment]
@Misamangame 
yes, this would be the actualy right way to do it :) 

But I sure do understand the problem for this one, what he could also do ist make a Custom Fieldborder by recording a Course arround the Grasfield and Save that as e.g. GrassfieldBorder, then load that Border Course and generate a Course (but you can only press calculate once with that methode).
I got something in mind to make it a bit easier, but that got a lower priority.

**Comment by Shalda** [comment]
Ok thanks, now I get it.
The “P” points, at the start and at the end, were the most unobvious part for me here.
Just checked, with those waiting points. When the vehicle is completely filled, it follows the shortest way to the endpoint, of the main route.
So, if I want that the manual course works like a generated one, the end of the first course should be set as close as possible to the second(unload), that’s it.
