### ISSUE TITLE
Pesticide and Fertilizer don't decrease

### ISSUE THREAD

**Issue by rolthof89** [Courseplay/courseplay#6376]
Since the last version I notice that my pesticide and fertilizer don't decrease, see screenshots.
The settings for helper refill are turned off. When I turn on the settings I see my money decreasing, when I turn them off again there is no money spent but also the level doesn't go down.
![pest](https://user-images.githubusercontent.com/26250742/100234153-f5913c00-2f2a-11eb-857e-e29ba199c814.jpg)
![fert](https://user-images.githubusercontent.com/26250742/100234155-f629d280-2f2a-11eb-86af-23dc71425998.jpg)
![settings](https://user-images.githubusercontent.com/26250742/100234151-f4600f00-2f2a-11eb-8703-f3aa8f958060.jpg)

**Comment by rolthof89** [comment]
The seeds do decrease and need to be refilled.

**Comment by Tensuko** [comment]
logfile ?

**Comment by rolthof89** [comment]
> logfile ?

Where?

**Comment by Tensuko** [comment]
\My Games\FarmingSimulator2019

and drag and drop the log.txt into comment box

**Comment by rolthof89** [comment]
Seems to be a bug together with Variable Spray rate. I've uninstalled this mod and now all is fine.
https://www.farming-simulator.com/mod.php?mod_id=124018.
