### ISSUE TITLE
Mode 3 issue

### ISSUE THREAD

**Issue by Nealswiss96** [Courseplay/courseplay#6377]
Hi Everyone,
I have a litte issue with mode 3 in the new version. It seems to always drive to far away from the trailer. Is there something I can change in the settings? 

![7E802330-42D3-45EF-929B-00E89168289E](https://user-images.githubusercontent.com/66141267/100247812-6b090680-2f43-11eb-8d2d-23f5f52edac7.jpeg)

**Comment by Tensuko** [comment]
I already know whats the Issue here..
No you can't, we will have to adjust this, but to let you know, you just have to press print on your keyboard to make a screenshot and that you will find in \My Games\FarmingSimulator2019\screenshots

**Comment by Tensuko** [comment]
@pvaiko when approach a waitpoint, deactivate sensor/swerve ?

**Comment by Nealswiss96** [comment]
I have an other question regarding the auger pipe? Is there a setting for which position the auger pipe unloads? Would be nice if it unloads in the furthest setting, then you wouldn’t have to drive so close to the trailer. 
<img width="801" alt="5F665DDA-EE2F-40A9-A538-51E381D26B48" src="https://user-images.githubusercontent.com/66141267/100274847-c5b45980-2f67-11eb-9637-d5249f1df86e.png">
<img width="801" alt="ED9209EE-5336-401D-8FC4-F10796A14714" src="https://user-images.githubusercontent.com/66141267/100274863-cc42d100-2f67-11eb-803f-be10395535a6.png">

**Comment by Tensuko** [comment]
Not yet, but we will add this later.

**Comment by Nealswiss96** [comment]
Cool thank you guys very much for the amazing work!!
