### ISSUE TITLE
Horsch Mod

### ISSUE THREAD

**Issue by knoxville73** [Courseplay/courseplay#6378]
With the Horsch Mod (HORSCH PRONTO 6AS / MAESTRO 8RC ), we have a problem.  If the seeder is empty or if the field seeding is finished, the first element of the Horsch assembly is not folded (see pictures).
![Horsch_Mod](https://user-images.githubusercontent.com/23388102/100258095-ed46fa00-2f46-11eb-9f4f-8a2846402953.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/5598125/log.txt)

**Comment by Tensuko** [comment]
We already told that to the Modder and even provided a (at least half way) fix for this, but it seems they don't care, pls contact the Modder, as they added a line to now allow any AI Driver Tractor to unfold this tool.
