### ISSUE TITLE
Helfer verlässt Feld beim wenden

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#6383]
Hallo 
Folgendes Problem: Wenn der Abfahrer beim Düngen ist egal ob Gülle fahren oder Düngertreuen fährt er immer Feldreihen wechsel bzw. holt soweit aus dass er das Feld verlässt bis er zur nächste Feldreihe rein fährt
![Feld](https://user-images.githubusercontent.com/47453761/100387827-4ab37780-3029-11eb-8d7a-80098cfd0e5d.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5604767/log.txt)
![Unbenannt](https://user-images.githubusercontent.com/47453761/100387910-79315280-3029-11eb-9b14-862fdc54ca1a.png)

**Comment by rohne83** [comment]
Ausholen ist doch normal. Bei einem Güllefass hast du nunmal zwangsläufig einen größeren Wendekreis als bei zB einem Grubber. Und wenn du dann solche Arme dran hast und sogar noch eine 180Grad-Wende machen willst, ist es klar dass es schwierig wird mit dem Platz. Verlassen des Feldes kannst du mittlerweile ziemlich gut unterbinden in dem du mehr Vorgewende machst oder die Einstellung Wende auf dem Feld aktivierst. Oder du generierst den Kurs mit Reihen überspringen oder kreisförmig. Halt die gleichen Tricks zu denen man auch in der Realität greift. Physik und Geometrie außer Kraft zu setzen wäre ja witzlos ;)

**Comment by DerBauer2** [comment]
ist mir auch aufgefallen die spritze hatte voher besser gefahren und blieb im feld mit denn neuen Patches hat sich das leider wieder verschlechtert :/

**Comment by Tensuko** [comment]
@rohne83 alles soweit richtig.
Ich hab neulich selber mit einer Spritze ein Feld bearbeiten lassen und es kam tatsächlich ein turn zustande, der unnötig weit aus dem Feld raus ging, aber eben nur ein mal.
Warum er das macht, ist nicht ganz klar.
Rückwärts fahren im turn macht er nur, wenn er wegen des Wenderadius die nächste Reihe nicht sauber erreichen kann.
Jede 2te Feldreihe, könnte das Problem tatsächlich erst mal lösen.

Unser Ziel ist eigentlich, mit dem Pathfinder die Turns so zu bauen, dass er mit seiner Arbeitsbreite auf dem Feld bleibt, aber mit gezogenen Geräten ist das noch nicht machbar.
Wir schauen uns das auf jeden Fall weiter an.

**Comment by pvaiko** [comment]
Einen Fehler habe ich in 21 behoben, sollte jetzt mit Vorgewende gut funktionieren. Ohne Vorgewende ist es jetzt auch besser, nicht perfekt aber das werden wir nicht ändern, siehe oben was @rohne83 auch gesagt hat.
