### ISSUE TITLE
Seit v6.02.00072 Probleme mit Wegfindung bei Kursen mit mehreren Fahrzeugen

### ISSUE THREAD

**Issue by mtibke** [Courseplay/courseplay#6385]
Ich habe seit der Version v6.02.00072 das folgende Problem:

Wenn ich versuche ein Feldkurs für mehrere Fahrzeuge abzufahren, startet CP die Arbeit an völlig unerwarteten Stellen. Statt am "nächsten passenden Wegpunkt" loszufahren, generiert es einen Pfad und startet dann die Arbeit dort (siehe Screenshot 1, eingestellt ist Bahnversatz = rechts). Bei Kursen mit nur einem Fahrzeug passiert das nicht.

![cp_issue_1](https://user-images.githubusercontent.com/5798184/100430352-f810a480-3096-11eb-9679-f85cdeaa031b.png)

Die Einstellungen für die Kursgenerierung:
![cp_issue_2](https://user-images.githubusercontent.com/5798184/100430436-14acdc80-3097-11eb-9473-d0ee864a52b8.png)

Wechsle ich im selben Spielstand mit dem selben Kurs und CP-Einstellungen auf eine frühere Version (hier v6.02.00071) funkioniert es wie gewohnt.

Anbei noch die beiden Logfiles:
[log_v6.02.00071.txt](https://github.com/Courseplay/courseplay/files/5606883/log_v6.02.00071.txt)
[log_v6.02.00072.txt](https://github.com/Courseplay/courseplay/files/5606885/log_v6.02.00072.txt)

**Comment by Tensuko** [comment]
Das liegt daran das du deinen startpunkt in der Ecke hast.

**Comment by mtibke** [comment]
Was ist denn jetzt die richtige Vorgehensweise bei Kursen mit mehreren Fahrzeugen?

**Comment by Tensuko** [comment]
Startposition an der Kante. Das war schon lange bekannt das ein Kurs an der Ecke startend für mehrere Fahrzeuge probleme macht.

Zur Info es gib bereits 6.03.00002 und mit der fahre ich selber Multitool Kurse.

**Comment by mtibke** [comment]
Wie gesagt: das Problem tritt bei mir **seit der Version** v6.02.00072 auf - also auch in der aktuellen v6.03.00002. Davor ist es mir noch nicht aufgefallen. Wird das denn noch aktiv in einem offenen Issue verfolgt?

P.s.: Ich habe es jetzt noch einmal mit einer manuellen Startposition probiert und damit funktioniert es für mich als Workaround.

**Comment by Tensuko** [comment]
Das ist kein workarround das ist die regel das problem gab es auch schon weit vor 00072...

**Comment by mtibke** [comment]
Nein, eine Umgehungslösung bei einem bekannten Problem nennt man Workaround: [https://wiki.en.it-processmaps.com/index.php/ITIL_Glossary/_ITIL_Terms_W](url)

Wenn CP mit dieser Kombination von Einstellungen: "Fahrzeuge auf selbem Kurs > 1" mit Startposition "Ecke" (hier Süd-West) nicht richtig funktioniert, würde man daher erwarten, dass es dazu entweder einen offenen Issue oder einen "Known Error"-Eintrag im Github-Readme gibt.
