### ISSUE TITLE
Error: Running LUA method 'packetReceived' - settings.lua:694: attempt to index a nil value

### ISSUE THREAD

**Issue by Bandesss** [Courseplay/courseplay#6386]
Hallo neueste Version CP auf der Hot Online.
Sobald man Dreschen will kommt der Fehler
Siehe Log
[log.txt](https://github.com/Courseplay/courseplay/files/5608239/log.txt)

**Comment by Tensuko** [comment]
Könnte das auch mit diesem Script zusammen hängen, der hier erwähnt wird ?
#6360

**Comment by Bandesss** [comment]
Welches script?
Wir nutzen ja verschiedene und aus deinem Link werde ich nicht schlau
Danke für die Hilfe

**Comment by Tensuko** [comment]
Es gibt in der Map ein Script das bei einem anderen Schneidwerk ein Problem verursacht und der LUA Error ist uns vorher noch nie untergekommen.
Desshalb die Vermutung und wenn du in dem Link mal runter scrolls findest du eine Antwort von @Rumspringa90

**Comment by Bandesss** [comment]
Hmm ok, darum habe ich die Map dazu geschrieben
Hot Online, soll ich da mal fragen ?

**Comment by Tensuko** [comment]
Naja warte mal noch wir schauen erst mal ob das was bei uns sein kann, eventuell finden wir da was.

**Comment by Rumspringa90** [comment]
Tritt das nur auf wenn man mit CP dreschen will oder auch wenn man manuell dreschen möchte? Mit verschiedenen Dreschern mal getestet? Original Drescher und Schneidwerk? 
Die Jungs von Hot Online sind leider nicht so Hilfsbereit wenn man mit CP spielt da ihre Karte dafür nicht ausgelegt ist heißt es dann.

**Comment by Bandesss** [comment]
Wohl war 
Dreschen mit dem Claas von Claas addon
Kam nur beim dreschen

**Comment by Rumspringa90** [comment]
Hab das eben mal bei mir getestet Lokal im Singleplayer mit den Claas Dreschern und den originalen Hot Mods. Ich bekam da den Fehler nicht. Kann natürlich auch sein, das ein andere Mod in Kombination diesen Fehler verursacht.

**Comment by Bandesss** [comment]
Also wieder was neues gerade auf dem Server
[log.txt](https://github.com/Courseplay/courseplay/files/5609234/log.txt)
Glaube Server und SP kannst nicht vergleichen oder

**Comment by Bandesss** [comment]
Und nun auch bei der Karte Grünfelder Land, der Auftrag war Grubbern
[Grünfelderlog.txt](https://github.com/Courseplay/courseplay/files/5610218/Grunfelderlog.txt)
2 Vorgewinde , Scharf 12 % Überlappung.

**Comment by schwiti6190** [comment]
@Bandesss die fehler die bei dir auf tauchen hängen mit deinen gespeichterten kursen zusammen, hast du noch irgendeine idee was du zur zeit der fehler gemacht hast, bzw  davor.

**Comment by Bandesss** [comment]
Ja stimmt tatsächlich habe jeden Mitspieler als Admin einen Ordner Erstellt

**Comment by Bandesss** [comment]
Mal eine Frage die warnings auf dem Server 10-12 Stück sind die schlimm ?

**Comment by Tensuko** [comment]
Warnings sind meistens unproblematisch, die weisen nur auf etwas hin :)

**Comment by Bandesss** [comment]
> Warnings sind meistens unproblematisch, die weisen nur auf etwas hin :)

Vielen Dank auf dem Server immer doof 🙂

**Comment by Tensuko** [comment]
Konnten so einen Fehler nicht mehr feststellen.
