### ISSUE TITLE
Patreon

### ISSUE THREAD

**Issue by tanordheim** [Courseplay/courseplay#6390]
Hi! Have you guys considered setting up a Patreon or something similar (outside of the current PayPal option) to support the project on a more steady basis? I appreciate the work you put into this project and would love to support it in some form.

**Comment by Tensuko** [comment]
Where would be the difference in Patreaon and Paypal ?
I know Patreon from other things, but sometimes get something for spending there.

What could be the benefid it we set up a Patreon ? :)

**Comment by tanordheim** [comment]
I was more thinking about the ability to pay a little monthly to keep things going but maybe i can do that with paypal too and i just didn't check properly? :|

**Comment by tanordheim** [comment]
And yeah Patreon has the reward tiers but I have no idea what could be offered - I'd be happy it things kept rolling along like they do :)

**Comment by tanordheim** [comment]
> ... but maybe i can do that with paypal too and i just didn't check properly? :|

Apparently that big "make this a monthly payment" checkbox was possible to miss - sorry about that, feel free to close this unless you actually want to pursuit the patreon option and want people to suggest reward tiers

**Comment by Tensuko** [comment]
As we have nothing else to offer then our CP Releases, I don't think Patreon would make a lot of sence as someone would have to care for this one too :) 
Anyway, thank you for your Idea and your interest in Courseplay :)
We appreciate that :)
