### ISSUE TITLE
IC

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/courseplay#6396]
Hello guys,

Could you please tell me why in some vehicles there is a option IC and you can only disable/enable it, plus if this is enabled you can’t use properly CP hmm.... 

Is there any chance to delete this IC so CP works without any problem ?

**Comment by pvaiko** [comment]
Guess everyone knows what IC is except me...

**Comment by Tensuko** [comment]
IC control to open windows and doors and stuff, there are 3 versions
- animated axes controlled with mouse
- controlled by mouse (conflict with CP)
- simpleIC also controlled by mouse but without the courser and works perfect with CP

I have no Idea why ppl not use simple IC couse it just works awesome. Aim, click, done.

Normal IC we always said we are not supporting this.

You can deactivate it in your vehicle but how that works you got to google it.
