### ISSUE TITLE
Traffic collision Mode10

### ISSUE THREAD

**Issue by polosubtil** [Courseplay/courseplay#6397]
Hi guys,

Great work with this new traffic collision detector, works really well.

I just have a small problem with Mode10 doing silage. Which isn't a real issue in the end as CP solves it eventually

When my forage wagon gets to the bunker it stops (70m away as set), the tractor with the blade goes in its corner as usual and then the forage wagon starts again to unload. But it stops again due to the new traffic collision boxes because even if the tractor with the blade is stopped, it has boxes for the course. So they both stop. The forage wagon starts again after 30 secondes saying it "solved" the issue I think. So absolutely not major, it works in the end ;)
[log.txt](https://github.com/Courseplay/courseplay/files/5611949/log.txt)
Position where they are both stopped
![fsScreen_2020_11_29_10_28_09](https://user-images.githubusercontent.com/60451845/100538240-d3e7cb80-322e-11eb-895e-a473e5aaafdf.png)

Blade course
![fsScreen_2020_11_28_22_58_38](https://user-images.githubusercontent.com/60451845/100538253-eb26b900-322e-11eb-9f93-accfe716bf89.png)

Forage wagon course
![fsScreen_2020_11_28_23_27_42](https://user-images.githubusercontent.com/60451845/100538263-00034c80-322f-11eb-8d54-8c1dfae5f5e1.png)

Here you can see the traffic boxes of the tractor with the blade, even if it is stopped by CP
![fsScreen_2020_11_28_22_58_50](https://user-images.githubusercontent.com/60451845/100538288-20330b80-322f-11eb-92d2-3302da7b2df0.png)
![fsScreen_2020_11_28_23_27_02](https://user-images.githubusercontent.com/60451845/100538431-1362e780-3230-11eb-89cb-c0e21fe581dc.png)

I guess it really depends on the courses in the end, this probably happens because I don't have much space for turns.

**Comment by Tensuko** [comment]
@pvaiko deactivate traffic when Mode10 driver sits on waitingpoint.

**Comment by Tensuko** [comment]
Try with Version 6.03.00018 and report
https://github.com/Courseplay/courseplay/releases

**Comment by polosubtil** [comment]
Hi @Tensuko,

Sorry about the delay ;)
I just tried with version 6.03.00019, it now works really well. Thanks guys :)
