### ISSUE TITLE
Error: Running LUA method 'draw'

### ISSUE THREAD

**Issue by Easton97-Jens** [Courseplay/courseplay#6399]
Hallo Courseplay Teem

wir spielen auf der Hot 21 ver. 2.0.2.1a und haben standig den Fehler Error: Running LUA method 'draw' wenn wir Misssionen annehmen und wenn einer im shop ein Fahrzeug kauft oder es um Konfiguriert oder es zurücksetzt ensteht der Fehler. Wenn der Fehler auftaucht haben es fast alle spieler auf dem server und es hilft nur ein Spiel neustart. Das ganze ist bei de CoursePlay ver. 6.03.00003 extrem auf gefallen und bei der 6.03.00001 ist der Fehler auch sehr oft vorgekommen. Ich würde mich um eine Antwort freuen

mit Freunlichen Grüßen Jens 

[server log.txt](https://github.com/Courseplay/courseplay/files/5612128/server.log.txt)
[spieler log von mir.txt](https://github.com/Courseplay/courseplay/files/5612129/spieler.log.von.mir.txt)

**Comment by Tensuko** [comment]
Ihr habt noch diverse andere LUA Errors in der log, schwer zu sagen wer da welches Problem macht....

In der Spielerlog erstmal nen callstack der auch nichts mit CP zu tun hat...

Da hilft nur mods aufräumen bzw den schuldigen finden der euch die Errors da rein haut.
