### ISSUE TITLE
Courseplay wont unload the combine

### ISSUE THREAD

**Issue by farmerjosh** [Courseplay/courseplay#6400]
I have the newest version of couseplay and have a combine setup on courseplay but the trailers wont go and unload the combine at all they wont leave the wait point ( i have set a waiting time up)

**Comment by Tensuko** [comment]
Why did you set waitpoints in the Mode2 Driver Course ? There is not need for that.

**Comment by Tensuko** [comment]
Closing this, no Waitpoint is used in Mode2 Course, also we think aboute removing any waittime use as we don't see a use in it, see #6402 and let us know what you use it for.
