### ISSUE TITLE
Unloading front loader on v6.03.0003

### ISSUE THREAD

**Issue by Misamangame** [Courseplay/courseplay#6401]
Hello guys, since last version I have problems with front loader unloading on desired point. He either goes a bit right from unloading point or completely off. No matter where I will try to put trailer for unloading. This course was saved during CP v6.02. and it worked good, that unloader emptyied  three quarters of those bunkers.  I had problem even before on v6.02. with going a bit right off course on first run after loading a game, but on other runs it worked just fine. Trailers for unloading were always on AD course.  video : https://youtu.be/G4pbhwT476o
log without any debug channel
[log.txt](https://github.com/Courseplay/courseplay/files/5612373/log.txt)

I see there is some improvement stated on Mode 9 in lateast version, maybe saving new course will help?

**Comment by Tensuko** [comment]
Should be fixed with 6.03.00004
