### ISSUE TITLE
WE ask YOU: Question about Waitpoint and Wait Time use

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/courseplay#6402]
Hello Community,

we often read Issues and Questions about the waittime in few Modes and we ask ourself, what are you guys use it for?

What comes up in our mind is:
- Trafficcontrol: Delaying some Drivers to not crash into each other, wich should be mostly solved with our TrafficController introduced in 6.03.xxxx1 and higher
- Mode1: Wait under a conveyor belt to load something, wich should just work fine when you set a min value what you want to load (or even just stay under it)

So we don't rly see a need of this, so we would like to know, what you use it for and is this rly a needed feature.

Greetings,
Dev. Team

**Comment by andreasthu** [comment]
Hello guys.
I use the waitpoint only with zero stop time.
In combination with AD, with CP i work most fieldwork, auger Wagon, shovel and Silo.
For the most transportways i use autodrive.
And for thresher, rootcrops and forageharvesting drive off, i use courseplay with generator course from the AD network.
Lg
Andreas

**Comment by Tensuko** [comment]
So you don't use any Waitpoint to make the Driver wait at that point ?

**Comment by andreasthu** [comment]
Normally no.
Only when waitpoints needed,  auger trailer, shovelmode,..
Lg
Andreas

**Comment by Misamangame** [comment]
I was using waiting time only in Mode3 when I had trailers coming under auger trailers, but it is not necessary at all, because when trailer is not there driver with auger wagon just make another round.  I never used it for anything else as I can remember.  Don't see any need in Mode 1 or any other.

**Comment by rohne83** [comment]
using it in Mode1 for forced waits (i.e. to simulate weighing). And in Mode3 (together with the code amendmend I posted in https://github.com/Courseplay/courseplay/issues/6046) to be able to use more than one waitpoint for overloading into more than one trailer already now and if the trailers are driven by AutoDrive.

**Comment by Tensuko** [comment]
@rohne83 the first point could be implemented in a different way (weightstation) the 2nd for your Mode3, well we sure have an eye on that but that got not much to do with waittime. It wouldn't matter if we call the points waitpoints or actionpoints to overload.

**Comment by DDenloza** [comment]
Good afternoon. I WOULD LIKE to use the waiting point in front of the gate when you need to unload at the factory, and there is a gate! If not used, then the transport crashes into a barrier or gate! "I WOULD LIKE" - because this function does not work in courseplay!!!

**Comment by Tensuko** [comment]
Won't add stuff like that... There are Scripts to open gates when a vehicle arrives as long as it is implemented, this 'issue' is not about what you would like to have...

**Comment by DDenloza** [comment]
The gates and barriers open naturally themselves, but very slowly and the transport does not stop crashes into them!

**Comment by Tensuko** [comment]
That would be a traffic thing and got nothing to do with this issue, deleting comments to keep this one clean.....

**Comment by DDenloza** [comment]
Why have you deleted my comments/questions? Did I ask the wrong thing? On the topic wrote your errors courseplay. Strange...

**Comment by Tensuko** [comment]
The answer is in your mail, pls stop spam this issue with offtopic stuff, thanks....

**Comment by archaoncze** [comment]
i dont use this setings at all

**Comment by SteelRodent** [comment]
I've only ever used the waitpoints for mode 3 and 9 (mostly because the old instructions say to use it), but in both cases I like that CP waits for the next trailer when one is full. Other than that I've never used it or wait time, nor do I see a need for it in any other mode.

**Comment by JDTiger** [comment]
Hey, i use the waitpoints in mode one, to ensure overloading graincarts are fully emptied, before driving off.

Yes, i can set a min drive off value, but the truck will drive off, once the value is reached and not wait until the graincart has finished unloading.

Also the value can't be set precicesly, since the carts are sometimes laden 100% and other times only 80%.

Setting a min drive off value in combination with a waitpoint just after the startpoint, ensures that the truck drives off, when it is beeing loaded and the waitpoint ensures the grtaincart is empty.

**Comment by Tensuko** [comment]
> Yes, i can set a min drive off value, but the truck will drive off, once the value is reached and not wait until the graincart has finished unloading.

That we can change to: drive off at set % but not while still loading something.

For the overloader, drive off when lower then set % value will only do when there is no more trailer next to it.
Just tried it:
![fsScreen_2020_12_17_10_51_57](https://user-images.githubusercontent.com/27344744/102472383-8d7bd480-4056-11eb-8a23-05f3c8844758.png)
It should drive off at lower then 50% but as it still can unload, it will continue.
My Trailer ist set to 99% and works just fine, but sure as I said we can change that he will wait untill nothing is loading anymore.

**Comment by JDTiger** [comment]
For Mode1: that would be ideal, thank you

For Mode3: i meant driving off of the field, towards the unloading course, so, if the Combine is empty&the overloader is at 80% it drives off to the waiting trailer.

**Comment by lcc1211** [comment]
I can't remember ever using wait time for anything.

**Comment by EddieGrouch** [comment]
I'd like a wait for use in role play vlog videos to simulate a cab ride or similar using a passenger mod.
As is, when the car stops, I have to turn the UI back on, jump to drivers seat, tell driver to go on, hop back, turn off UI, then exit the passenger door.

I know it's a weenie use of Courseplay but it's the only way I know to get the scene made when playing alone.  If anything it would be great to know what to edit to stop the on-screen alerts like "Driver has reached the wait point." as they bypass the UI hide mod I use.

**Comment by Tensuko** [comment]
@EddieGrouch 
There is already an Issue about turn off the CP notifications, but not sure when we are up to add a setting for this.

About your wait time use, well.... not sure yet if we rly will keep the waittime.... Still thinking about it.

**Comment by AUZ001** [comment]
I would use it daily if it worked, 
an example, After setting up CP on each vehicle with the start point and offset etc, I send all 5 cotton pickers down to field 8 via Auto Drive, once they arrive, Auto Drive automatically starts CP on each vehicle and off they go.
If "Wait Time" would work, I would set a 1min start delay on each vehicle behind the 1st so they can be better spread out in the field.

**Comment by Ernesto-bf** [comment]
I have thought about using wait times but only as a workaround for traffic problems. I think it would be very useful if the user could manually set a reserve zone (start and finish waypoints), aside from what the TrafficController does automatically. This would allow multiple vehicles in courses that cross themselves, reverse sections for unloading, etc without having to know the aprox time it needs to go through.

**Comment by Tensuko** [comment]
> I have thought about using wait times but only as a workaround for traffic problems

For this we have the TrafficController.



> I think it would be very useful if the user could manually set a reserve zone (start and finish waypoints), aside from what the TrafficController does automatically. This would allow multiple vehicles in courses that cross themselves, reverse sections for unloading, etc without having to know the aprox time it needs to go through.

Could you open a topic for this under discussion and discripe it more precise where to use this ? I don't see the benefit right now.
An example could help more.

https://github.com/Courseplay/courseplay/discussions

**Comment by zsorra** [comment]
Ich benutze früher immer eine Pause von ca. 3 Minuten beim befüllen der Silagebunker um dem Arbeiter Zeit zu lassen im Silo zu verdichten und zu verteilen, leider funktioniert das ja jetzt nicht mehr und man muß den Abfahrer immer manuell nach bestimmter Zeit abfahren lassen. 
Es wäre schön wenn das wieder implementiert werden würde, den meine ganzen aufgezeichneten Kurse sind mit dieser Pause versehen und funktionieren jetzt nur mehr bedingt.

**Comment by Tensuko** [comment]
@zsorra 
Also Wartepunkt im Mode2.
Deine Kurse kannst du mit dem Editor erstmal umbauen indem du den wartepunkt zu einem manuellen Punkt änderst. 
Ansonsten guter Punkt mit dem Siloarbeiter.

**Comment by djnekkid** [comment]
In Mode1, i dont find any way to add a wait time.
But what about, if you add a waypoint/P-point on an 'unloading area', it will completly empty the trailer?

Example:
A trailer with straw has a CP1 track to fill a cowshed with straw.
Without any P-spots, it will unload "as much as needed", but with a P-point, it would 'stay in the unload area' untill its empty.

**Comment by TinyCrocodile** [comment]
Recently I thought that wait time would be nice to use in mode 9 to synchronize two M9 Loaders on the same course. 
Im pretty shure that is not your primary goal but who knows what will be when it is reworked.

**Comment by Tensuko** [comment]
> 
> 
> In Mode1, i dont find any way to add a wait time.
> But what about, if you add a waypoint/P-point on an 'unloading area', it will completly empty the trailer?
> 
> Example:
> A trailer with straw has a CP1 track to fill a cowshed with straw.
> Without any P-spots, it will unload "as much as needed", but with a P-point, it would 'stay in the unload area' untill its empty.

Doesn't make any sence, we unload as much as we can, trailer empty or silo full. We won't touch this.

**Comment by Tensuko** [comment]
> 
> 
> Recently I thought that wait time would be nice to use in mode 9 to synchronize two M9 Loaders on the same course.
> Im pretty shure that is not your primary goal but who knows what will be when it is reworked.

Thats a cool Idea, the Problem here is, that we use Waitpoints as 'Actionpoints' to tell where to load and where to unload.
The long time goal would be to add another type of Waypoint (e.g. Actionpoint) instead of all the Waitpoints we use right now, so we can then use Waitpoints for real Waiting, and not start any interaction, but this is rly far away...  First we would like to get the Waittime working again in a proper way, as there are some useful cases for this (thats why I made this Issue here)

**Comment by djnekkid** [comment]
> Doesn't make any sence, we unload as much as we can, trailer empty or silo full. We won't touch this.

Im not saying it should be default behavior, but if we add a 'P' in an unload zone, it could be an mark for 'unload until empty'.


![image](https://user-images.githubusercontent.com/65364380/110215737-aa80b080-7eab-11eb-96d9-2a99d470e8b4.png)

**Comment by Tensuko** [comment]
Won't happen. As I said, we already unload untill empty or target full.
