### ISSUE TITLE
Ich muss doch mal.........

### ISSUE THREAD

**Issue by Mapela80** [Courseplay/courseplay#6403]
GANZGANZ DOLL und LAUT DANKE sagen.

Dem ganzen Team von Courseplay: Ihr macht so fantastische Arbeit und euer Support is richtig klasse. Danke dass ihr uns Gamern das Spiel versüsst. DANK DANKE DANKE

wünsch Euch auch eine ruhige und schöne Votweihnachtszeit.

Liebe Grüße vom Gemueseschaf AKA Marion ;)

**Comment by Lustiger-Hubi** [comment]
![Gott-zäppfchen](https://user-images.githubusercontent.com/48583507/100872584-4e6c5180-34a2-11eb-8d9f-b11c2fa97376.jpg)

**Comment by Lustiger-Hubi** [comment]
Ich mag trotzdem keine Arschkriecher !!

**Comment by Tensuko** [comment]
Du wolltest trotzdem nicht wieder her kommen und etwas schreiben und dann gehst du Leute an, die einfach nur nett danke sagen, wenn du ein Problem damit hast, dann geh...
