### ISSUE TITLE
Tractor Light Bug

### ISSUE THREAD

**Issue by lightbulb751** [Courseplay/courseplay#6404]
When I turn on all the lights and am in the tractor while courseplay helper is activated the lights stay on, however as soon as I leave the tractor then enter again some of the light gets turned off? Not sure if it's coruseplay or the tractors fault. Here's a video of the bug in action:

https://streamable.com/zpw0ai

**Comment by Tensuko** [comment]
dramatical Issue, duplicate anyway #5542
