### ISSUE TITLE
Attached harvester cant unload after 6.03.00003

### ISSUE THREAD

**Issue by Tkaag** [Courseplay/courseplay#6405]

**Comment by Tkaag** [comment]
Hey there 
cp cant unload attached harvester after the newest update. log with debug channel 4
[log.txt](https://github.com/Courseplay/courseplay/files/5615163/log.txt)

![image](https://user-images.githubusercontent.com/4026751/100595096-c435b900-32fa-11eb-9798-be875a61bb27.png)

**Comment by Tensuko** [comment]
More details...
How you want to unload it?
CP ? AD ? Selfunload ?
What is not working... ?

**Comment by Tkaag** [comment]
the problem is when unloading with CP. the fieldwork driver stops from this error: CombineAIDriver.lua:1139: attempt to call method 'getPipeDischargeNodeIndex' (a nil value)

**Comment by Quintto** [comment]
I just got the same issue with the Krone premos 
[log.txt](https://github.com/Courseplay/courseplay/files/5616796/log.txt)

I have the courseplay driver working the field, and when I get close with my trailer to unload him, he won't open his pipe and courseplay stops

**Comment by schwiti6190** [comment]
@Tkaag, @Quintto einmal bitte mit der neuesten version testen :)

**Comment by Quintto** [comment]
that was quick, but unfortunately I'm still getting the same error
[log.txt](https://github.com/Courseplay/courseplay/files/5618771/log.txt)
