### ISSUE TITLE
Speicherort CP in Multiplayer / Storage location CP in multiplayer

### ISSUE THREAD

**Issue by BastiHRO** [Courseplay/courseplay#6406]
**_Deutsch:_**
Hallo liebe Entwickler,
ich habe kein richtiges Problem, eher eine Anregung!
Wäre es möglich die Speicherorte für CP-Einstellungen und CP-Kurse im jeweiligen Savegame-Ordner zu speichern?
Manche MP-Server lassen es nicht zu die Kurse wieder zu löschen, da der Speicherort sich nicht im Savegameordner befindet. Das macht die Nutzung von CP auf manchen Servern echt unattraktiv. Wäre schön, wenn man sowas eventuell ändern könnte.
Ansonsten liebe ich CP und werde es immer wieder nutzen.

Beste Grüße
Basti

**_Englisch:_**
Hello dear developers,
I don't have a real problem, more of a suggestion!
Would it be possible to save the storage locations for CP settings and CP courses in the respective savegame folder?
Some MP servers do not allow the courses to be deleted because the storage location is not in the savegame folder. This makes the use of CP on some servers really unattractive. It would be nice if something could be changed.
Otherwise, I love CP and will use it again and again.

Best regards
Basti

**Comment by Tensuko** [comment]
Wenn du die aktuelle CP Version hast, kannst du Kurse ganz normal im HUD löschen.
Du musst auf dem Server als Admin eingeloggt sein!

**Comment by Tensuko** [comment]
Wie oben gesagt, Kurse löschen kein Thema, solange man als Admin angemdlet ist.
