### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by gent19** [Courseplay/courseplay#6407]
When I automatic generate field course, then click start course. Game froze and crash.
Here is a Log file.
[log.txt](https://github.com/Courseplay/courseplay/files/5617041/log.txt)

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki
https://github.com/Courseplay/courseplay/releases
What Tools did you use ?
Screenshots ?

**Comment by Tensuko** [comment]
BTW.....
Update your FS:
Version: 1.5.1.0 b6732

**Comment by gent19** [comment]
Ok, I will update my FS and try it again.

**Comment by Tensuko** [comment]
Not sure how to crash the game, a bit patience is needed then it is all fine and as I said, update the Game.
Will close this one.
