### ISSUE TITLE
Vorschlag: Abfahrer nur "pausieren" statt "entlassen"

### ISSUE THREAD

**Issue by rohne83** [Courseplay/courseplay#6408]
Hi, wäre es möglich in der Abfahrhelfer Steuerung den Mode2/3-Abfahrer auch so zu entlassen, dass die Zuweisung zum Drescher/Häcksler erhalten bleibt, also den Abfahrer quasi nur zu "pausieren"? Oder zumindest so, dass eben erstmal kein neuer Abfahrer an seiner Stelle gerufen wird.
Es kommt ja doch immer mal wieder vor, und wird sich wohl auch nie völlig vermeiden lassen, dass der Abfahrer irgendwo hängen bleibt oder grad eine so ungünstige Position hat, dass es ewig dauert bis der Pathfinder einen Weg zum Drescher gefunden hat. Wenn man dann den Abfahrer entlässt - und sei es nur für ein paar Sekunden - um manuell eingreifen und den Abfahrer an eine bessere Stelle maneuvrieren zu können, wird derzeit aber auch unweigerlich die Zuweisung zum Drescher/Häcksler aufgehoben und stattdessen direkt der nächste Abfahrer aufs Feld gerufen. Genau letzteres will man bei solchen "Babysitting"-Eingriffen aber eigentlich gar nicht haben.

**Comment by Tensuko** [comment]
Das wäre eine extra Implementierung um ein anderes Problem zu umgehen und noch dazu recht kompliziert...
Das werden wir nicht umsetzen, sry.
