### ISSUE TITLE
Vorschlag: weitere AD-Nutzung durch CP

### ISSUE THREAD

**Issue by rohne83** [Courseplay/courseplay#6409]
Noch einen Vorschlag, diesmal bezüglich der bereits ziemlich gut laufenden Zusammenarbeit mit AutoDrive, so dass die jeweiligen Stärken der beiden Mods noch besser ausgenutzt werden können.
1. CP hat unter den gespeicherten Kursen ja auch den Autodrive-Ordner, wo dann ein Kurs zu jedem beliebigen Autodrive-Ziel in CP geladen werden kann. Wäre es auch möglich zumindest bei den "und zurück"-Kursen den benannten Zielpunkt auf Wunsch automatisch zB als CP-Ablade- oder Wartepunkt setzen zu lassen? Nutzbar sicherlich auch in Mode 1, 2 und 5. Aber wäre auf jeden Fall extrem hilfreich für Mode 8, der ja immer einen Wartepunkt als Überladepunkt braucht. Besonders wenn der Weg vom Silo bis zum zu versorgenden Feld recht weit ist, würde das viel Aufwand ersparen - und mir auch weniger Kopfschmerzen bereiten weil ich beim Einfahren mal wieder im Gegenverkehr hängen geblieben oder in ein Hindernis geknallt bin :D
2. Man kann AutoDrive ja bereits zum Entladen/Befüllen im Mode 4 und 6 nutzen. Ich fände es ganz praktisch das gleiche auch im Mode 2 machen zu können. So kann man auf dem Feld selbst allein CP mit UnloadManager und Pathfinder arbeiten lassen. Und sobald der Abfahrer den eingestellten Abfahr-Füllstand erreicht hat, wird halt nicht zum CP-Abfahrkurs gefahren sondern genau wie beim Mode 6 dann AutoDrive im Modus Abholen+Abliefern aktiviert, um über das bereits eingefahrene AD-Streckennetz die Ladung zum Silo zu bringen. Zurück am Feld lässt man AD dann wieder an CP übergeben. Macht natürlich nur Sinn wenn man "Kurs beginnen am" auf "Unloading" hat, so dass CP direkt wieder den Pathfinder nutzt.

**Comment by Tensuko** [comment]
Punkt2: #5284

**Comment by pvaiko** [comment]
2 wäre relativ einfach.
1 weiss ich nicht wie die GUI dafür aussehen soll, wir wollen ja nicht  _immer_ einen Ablade/Wartepunkt setzen, oder? Übrigens, geht es nicht mit dem Kurseditor?

**Comment by Tensuko** [comment]
Editorproblem mit AD Kursen:
#4955 keine Ahnung ob das noch immer ein Problem ist, aber die Editorlösung wäre am besten weil das GUI das nicht hergibt.

**Comment by rohne83** [comment]
ah, ja, das ist genau das was ich auch vorschlug :D Dann kann Punkt 2 hier raus, bleibt nur noch die Idee mit dem Wartepunkt

**Comment by rohne83** [comment]
Bezüglich GUI: wäre dann vielleicht bei den Erweiterten Einstellungen für das Fahrzeug gut aufgehoben. Also zusätzliches Auswahlfeld zu was der Punkt gesetzt werden soll, und je nachdem was da grad gesetzt ist, wird der Punkt dann eben als normaler Wegpunkt gelassen oder als Wartepunkt eingestellt.

**Comment by Tensuko** [comment]
Punkt 1 sollte mit Kurs laden und Editor möglich sein mitlerweile.

Punkt 2 ist implementiert und kommt mit 6.4.0.3
