### ISSUE TITLE
Wages when using CP

### ISSUE THREAD

**Issue by LordKena** [Courseplay/courseplay#6410]
When I use CP money starts to drop from wages. Ive tried in advanced settings to change it and even tried to manually changed it. How to fix this

**Comment by Tensuko** [comment]
Change it the correct way...
Switch to deactivated and its working, if not then you got some modconflict.

**Comment by LordKena** [comment]
It doesnt, Ive tried that. But it dont work. Ive looked att recent issues with the same problem. But nothing helped. I hhavent installed any mods, it just started doing that
Med vänliga hälsningar
Kennert Ottosson

On mån, nov 30, 2020 at 18:07, Tensuko  wrote: 
	Change it the correct way...
 Switch to deactivated and its working, if not then you got some modconflict.

**Comment by Tensuko** [comment]
logfiel, what mode, what tools and so on...

**Comment by LordKena** [comment]
It was when I updated CP yesterday it al started

**Comment by LordKena** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5617887/log.txt)

**Comment by Tensuko** [comment]
I just tried it again, this is not a CP Issue, that must be any of your Mods in your mods folder or check your ingame Settings for automatic seed or fertilizer or even fuel....
