### ISSUE TITLE
various errors

### ISSUE THREAD

**Issue by steve0562** [Courseplay/courseplay#6411]
I have encountered some errors
1 - activated avoids crops but does not work, error 1.jpg
2 - when unloading the combine, the tractor collides, error 2.jpg
thanks
![error 1](https://user-images.githubusercontent.com/72933866/100660462-587f3a80-3352-11eb-9f93-7ae3e18b5923.JPG)
![error 2](https://user-images.githubusercontent.com/72933866/100660465-5a48fe00-3352-11eb-8ee3-270104c6adc0.JPG)

**Comment by Tensuko** [comment]
#5272 and read Wiki for how to provide bug reports....

**Comment by Tensuko** [comment]
Avoid Fruit does work, that I can tell you for sure after several hours of testing.
Your situation I don't rly understand.

**Comment by Tensuko** [comment]
Improovements will come step by step, also check what issues does exists already.
For the next time pls give better Informations.
Closing this for now.
