### ISSUE TITLE
Dynamic storages question, suggestion? 

### ISSUE THREAD

**Issue by MAOGAMI** [Courseplay/courseplay#6413]
G'day.

Quick question, do courseplay supports dynamic objects from global company like dynamic grain storages available on official modhub?

For now when I record a course from silo to store the driver drives under unloading pipe, tries to get load from silo but instead of load the GC "pick a box" pops up on my screen and the driver drives to the store with empty trailer, and of course he repeats that (if set to do X courses).

Is CP compatibile with that and I just can't find that option, or it isn't?

Similar thing happens to Auto drive, except that the driver just stops under unloading pipe waiting for load.

**Comment by Tensuko** [comment]
Is not compatible and won't be for now as we have other things to do and who knows how it will be in the next FS Version. Sry.
