### ISSUE TITLE
Dankeschön an das Team von Courseplay

### ISSUE THREAD

**Issue by Martin190606** [Courseplay/courseplay#6414]
#Liebes Course Play Team ich schreibe es jetzt in die Probleme, weil ich nicht weiß wie ich euch sonst erreichen sollte. Ich wollte mich einfach einmal bei euch bedanken. Ihr habt Ls 19 mit diesem Mod. einfach komplett verändert und es viel attraktiver gemacht. Ihr werdet wahrscheinlich alle neben zu noch einen Job haben und dann noch diese Herausforderung zu meistern. Einfach Respekt. Ich ziehe meinen Hut vor euch. Bitte macht weiter so.

**Comment by Lustiger-Hubi** [comment]
![Gott-zäppfchen](https://user-images.githubusercontent.com/48583507/100872478-2b41a200-34a2-11eb-8c93-64b5266f631e.jpg)

**Comment by Tensuko** [comment]
Damit hast du dich gerade komplett ins aus geschossen.
Von jemanden älteren hätte ich mehr geistige Reife erwartet.

**Comment by Lustiger-Hubi** [comment]
Ich mag keine Arschkriecher!

 

Von: Tensuko <notifications@github.com> 
Gesendet: Mittwoch, 2. Dezember 2020 15:03
An: Courseplay/courseplay <courseplay@noreply.github.com>
Cc: Lustiger-Hubi <m-leufke@t-online.de>; Comment <comment@noreply.github.com>
Betreff: Re: [Courseplay/courseplay] Dankeschön an das Team von Courseplay (#6414)

 

Damit hast du dich gerade komplett ins aus geschossen.
Von jemanden älteren hätte ich mehr geistige Reife erwartet.

**Comment by SevenFifty1996** [comment]
Dem kann ich mir nur anschließen. Bringen wir es mal auf den Punkt. Für Leute die gern allein spielen, wäre LS ohne CP nicht so interessant. Und, CP macht LS so komplex und komplett. Macht weiter so. Vor soviel Ehrgeiz ziehe ich auch meinen Hut. Einfach toll. Gemeckert und gemault wird ja oft, und ein Dankeschön und macht weiter so, dass hört Ihr sicherlich viel zu selten. Ich sage nur, Daumen hoch und macht im nächsten Jahr weiter so einen tollen Job.

**Comment by Tensuko** [comment]
Ich danke euch für die netten Worte.
Das motiviert uns doch immer sehr, auch weiter zu machen.

Ich werde dieses 'Issue' jetzt aber zu machen, um die Übersicht zu behalten :)
Noch mals Danke schön und ein frohes neues Jahr.
