### ISSUE TITLE
CP Editor

### ISSUE THREAD

**Issue by DerBauer2** [Courseplay/courseplay#6415]
Nur kurze frage geht der Editor noch nicht da ich ihn bei mir nicht Aktivieren kann ? :) Tasten sind Belegt   Danke schon mal

**Comment by Tensuko** [comment]
Doch der funktioniert.
Strg+Numpad0 (oder was man einstellt)
Bedingung: Ein gespeicherter Kurs.

Getestet im SP also auch MP.

**Comment by DerBauer2** [comment]
Danke für die Info :)  noch eine frage hätte ich   geht es noch nicht richtig das CP seine eigenen Fahrer ausweichen kann? 
![20201201135511_1](https://user-images.githubusercontent.com/60297613/100744733-8ca03d00-33de-11eb-8778-c7353519a4c7.jpg)
