### ISSUE TITLE
Error CP Editor

### ISSUE THREAD

**Issue by DerBauer2** [Courseplay/courseplay#6416]
Ich kann im Editor nichts bearbeiten da er Errors schmeißt :/
v6.03.00004
[log.txt](https://github.com/Courseplay/courseplay/files/5622819/log.txt)

Edit: mit neustart war der Fehler weg. Ist was bekannt wie der auftritt? oder was denn Auslöst? 
Edit 2.0: Bei mir Tritt der Fehler auf wenn ich ein Kurs gespeichert habe und dann bearbeiten möchte.

**Comment by Tensuko** [comment]
AutoDrive Course ?
Oder was für einen Kurs bearbeitest du ?
Werds nachher mal anschauen...

**Comment by DerBauer2** [comment]
ähm der Kurs is von AD ja und CP kann ja mit drauf zugreifen also denn von AD erstellt und von CP übernommen wie z.B. Abfahrer vom feld zum silo und zurück. Hatte es nun nicht getestet ob es auch auftritt mir selber erstellten CP kurs.

**Comment by Tensuko** [comment]
Siehe #4955

**Comment by DerBauer2** [comment]
kurs kann aber nicht Editiert werden wenn er neu erstelt wurde ??

**Comment by Tensuko** [comment]
Lies einfach mal das Issue durch dann solltest du verstehen was das problem ist...
Das hat nichts mit neu erstellt oder sonst was zu tun...

**Comment by DerBauer2** [comment]
oke Danke
