### ISSUE TITLE
Fahrzeugverband - Spurfindungsproblem

### ISSUE THREAD

**Issue by DennisKraemer** [Courseplay/courseplay#6417]
Hallo,

Habe bei dem aktuellen File festgestellt, dass wenn man einen Kurs mit mehreren Fahrzeugen erstellt und jedem Fahrzeug eine Position zuweist (2 Fahrzeuge; Schlepper 1 = links; Schlepper 2 = rechts) fahren die die ersten 2-3 Punkte einer Feldreihe (nach dem wenden) in der Mitte und wechseln erst dann auf ihre Spur.

Dadurch hat man lange Lücken nach von Vorgewende aus in die Feldreihen hinein (Richtung Feldreihen). Getestet mit originalfahrzeugen und zwei identischen Anbaugeräten (Lemken Titan 18).

Hat bei einer älteren Version von Curseplay noch wunderbar funktioniert (auch mit genau diesen Pflügen)  ;)
![fsScreen_2020_12_01_15_45_31](https://user-images.githubusercontent.com/66392848/100755652-b6606080-33ec-11eb-90cd-9f6f72b951ec.jpeg)
![fsScreen_2020_12_01_15_45_41](https://user-images.githubusercontent.com/66392848/100755672-ba8c7e00-33ec-11eb-8e56-aac7e448acb7.jpeg)

**Comment by Tensuko** [comment]
Das ist bekannt und schon länger so, finde nur das Issue gerade nicht...

**Comment by DennisKraemer** [comment]
Ok, sry hatte keinen Threat dazu gefunden, deswegen hatte ich einen neuen eröffnet.
Jedenfalls danke für die Antwort ^^

Habe lange nicht mehr gespielt XD
