### ISSUE TITLE
Cp fieldwork issues

### ISSUE THREAD

**Issue by juhku666** [Courseplay/courseplay#6418]
Hi!
I have had a lot of issues since version 6.03.00001 when cp worker should make a turn he instead goes straight or sometimes quit working. I have a lot of mods so mod conflict is possible but it haven't happened before that version.

https://gist.github.com/juhku666/b8a5d23ebc2c0015561edaacaad0016a

**Comment by Tensuko** [comment]
This is not the complete logfile, we don't see Errors.
This must be a problem on your side, all tools working just fine so far...
And what ever you mean with 'have had a lot of issues' since I know several ppl (include me) who don't have 'lot of issues' ...

**Comment by juhku666** [comment]
https://gist.githubusercontent.com/juhku666/b8a5d23ebc2c0015561edaacaad0016a/raw/9c89fdf6cff92e6d56b0feae42d618bbcf68d9d4/gistfile1.txt

**Comment by Tensuko** [comment]
Not going to support this...
Clean your mods folder, this is insane.... check what is unzip, what means prefab, and savegames do not belong into mods folder....

Oh and I didn't check but just in case:
Only one Map in mods folder.

If you still have a real issue (one !) then show us what Tool you used in what Mode and what exactly is not working....

**Comment by juhku666** [comment]
ok thanks for being asshole
