### ISSUE TITLE
MP Error: attempt to index field 'currentHelper' (a nil value)

### ISSUE THREAD

**Issue by Alexander21039** [Courseplay/courseplay#6419]
See below for the English version.

----------------------------- German version ---------------------------------------------
Der Fehler aus der Issue #6384 ist weiterhin aktuell und wurde nicht durch das Update auf CP v6.03.00003 behoben. 
Auch unter CP v6.03.00004 tritt nach einer gewissen Zeit weiterhin das in #6384 beschriebene Problem auf.

----------------------------- English version ---------------------------------------------
The bug from issue #6384 is still active and was not fixed by the update to CP v6.03.00003.
The the problem described in issue #6384 also continues to occur after a certain time even under CP v6.03.00004.

----------------------------- Log ---------------------------------------------
[Log.txt](https://github.com/Courseplay/courseplay/files/5623491/Log.txt)
[Log2.txt](https://github.com/Courseplay/courseplay/files/5636209/Log2.txt)

**Comment by Alexander21039** [comment]
See below for the English version.

----------------------------- German version ---------------------------------------------
Update: Der Fehler tritt auch nach einem Update auf CP v6.03.00006 auf.

----------------------------- English version ---------------------------------------------
Update: The error still occurs after an update to CP v6.03.00006

----------------------------- Log ---------------------------------------------
[Log2.txt](https://github.com/Courseplay/courseplay/files/5636243/Log2.txt)

**Comment by Tensuko** [comment]
Steht auch nichts davon, dass er diesen Fehler behebt. Das werden wir schon irgendwie mitteilen.

**Comment by Tensuko** [comment]
Wir können so leider nicht viel damit anfangen..
Wir müssen wissen wann und wie der Fehler auftritt.

**Comment by Tensuko** [comment]
Ohne weitere Infos können wir hier nicht viel machen.
