### ISSUE TITLE
Häckseln mit HW80 - solved

### ISSUE THREAD

**Issue by rohne83** [Courseplay/courseplay#6420]
Kein Issue mehr, könnte aber wohl auch für die Devs ganz interessant zu wissen sein.
Ich weiß grad nicht ob ihr über comments in Issues benachrichtigt werdet, die bereits geschlossen sind, deshalb mal schnell einen neuen. Es geht um das Problem beim Häckseln mit dem HW80-Mod (siehe https://github.com/Courseplay/courseplay/issues/6312), wo der Abfahrer immer zu weit vorfährt. Und auch beim Dreschen wurde der Abstand nicht korrekt ermittelt. Beides trat wohlgemerkt nur bei Coursplay-Abfahrern auf, nicht bei AutoDrive. Des Problems Lösung habe ich mittlerweile selbst gefunden:
Es lag mal wieder am autoAimTargetNode. Dem seine z-Achse hat nicht zur Front sondern zum Heck gezeigt. Ich hatte dann einfach mal die x-rotation des Nodes von 0 auf 180 gesetzt, so dass seine z-Achse ganz normal nach vorne zeigt. Und tadaa: seitdem berechnet auch Courseplay den vertikalen Abstand wieder korrekt.

**Comment by Tensuko** [comment]
Ok, danke für den Hinweis :) 
Ja normal kriegen wir Mails wenn wir subscribed sind.

Es liegt leider oft an 'nicht ganz richtig' gebauten Mods... Ja teils sogar an GIANTS Fahrzeugen, aber das ist eher die Ausnahme :)

Mache hier dann wieder zu und danke noch mal :)
