### ISSUE TITLE
Can't unload attached harvester (reopened)

### ISSUE THREAD

**Issue by Quintto** [Courseplay/courseplay#6421]
Yesterday issue #6405 was mentioned in an update, but I'm still getting the same error message as before the fix.

So when I try to unload my krone premos, it stops the courseplay driver as soon as my trailer enters the pipe unfold trigger area.

(new issuetopic because I can't reopen the old one)

link to the original issue report which includes a log.txt with a test in the latest update: https://github.com/Courseplay/courseplay/issues/6405

**Comment by Quintto** [comment]
the newest update V6.03.00006 of today seems to have fixed it.

but the tractor slows way down when I have my trailer beside it. (says something about slowing down for trafic, can this be disabled in the settings?)

**Comment by Tensuko** [comment]
Not in Settings.
We have to decide if the Vehicle is driven by CP or Player.
We have that on our list.
