### ISSUE TITLE
Two versions of Courseplay

### ISSUE THREAD

**Issue by wakka79** [Courseplay/courseplay#6423]
I play a couple of different maps routinely. 

I have one map (Western Australia) that plays really badly with courseplay after version 400. 

Is there a way of managing two versions of courseplay in the mods folder without corruption so that I can select the version that I want to use for different maps?

Thanks in advance

**Comment by candymant** [comment]
No problem because you may not have 2 Maps in your mod folder  at the same time.

**Comment by wakka79** [comment]
> No problem because you may not have 2 Maps in your mod folder at the same time.

Usually I would get that. But I generally have few issues with other maps in the folder. 

I was wondering if there was a way to keep two coursplay's in the mods folder. Maybe a way of renaming?

I dont usually have problems running the maps. I just have problems with courseplay after version 399 with a certain map.

**Comment by Tensuko** [comment]
There is no problem on maps and no, 2 Versions at the same time won't work.
