### ISSUE TITLE
Combine Issue

### ISSUE THREAD

**Issue by KennyB2** [Courseplay/courseplay#6424]
I'm trying to use three combines. The firs two work fine but then when I try and get the third one going on the headlands it lags my game and then goes into the field a bit and starts harvesting there. No matter what amount of combines I use, the last one will not work. While doing this I saw that vehicle convoy mode didn't work with more then two combines. Even if I had four combines it would only show for example 1/2 or 2/2. This only started to happen when I updated Courseplay to the newest version so maybe there is something I have to do with the new version that I don't know yet. Any thoughts of what I might be missing or doing wrong.

**Comment by Tensuko** [comment]
Becouse your startpoint is in the corner.... don't do that.
Start on the side of a field and it works fine...

And no this doesn't happen to start with newest Version, this is a rule since forever!
