### ISSUE TITLE
Übergang von Feldreihe zum Nachgewende

### ISSUE THREAD

**Issue by 60erjonny** [Courseplay/courseplay#6425]
Hallo

Karte: NFM 2.4
Benutze zum grubbern ,pflügen ,düngen und sähen dazu Feldkurse ( gespeichert sind ) , die mit Anfang Feldreihe und dann mit Nachgewede generiert sind.
Mit Version: 6.02.00073 geht noch alles gut.
Mit der neuen Version: 6.03.00005 übergibt CP die Übergabe von Feldreihe [ 1. ]  zum Nachgewede [ 2. ] nicht sauber.
Er arbeitet die innere Bahn nicht ab und fährt stattdessen , zum außeren Nachgewende [ 3. ] zur weiteren Abarbeitung.
Somit ist das Feld nicht vollständig bearbeitet.

![fsScreen_2020_12_02_09_30_14](https://user-images.githubusercontent.com/63659182/100849961-65e81200-3483-11eb-9c1a-5ed11797afcc.png)

**Comment by Tensuko** [comment]
Hast du den Kurs mal komplett laufen lassen ?
Was heist die innere Bahn und was ist für dich das äußere Nachgewende...

Kann ich nicht nachvollziehen...

**Comment by Tensuko** [comment]
Gleiches Issue aber besser dokumentiert  #6426
