### ISSUE TITLE
Fahrer fährt Vorgewende falsch an

### ISSUE THREAD

**Issue by DerBauer2** [Courseplay/courseplay#6426]
v6.03.00004

Folgendes:
 
Modus Feldreihen zu erst dann Vorgewede

Dort ist das Problem das er wenn er mit denn Feldreien fertig ist irgendwo im vorgewedende der Äußeren Bahn anfängt und die Innen liegende nicht Bearbeitet.

![20201202100036_1](https://user-images.githubusercontent.com/60297613/100851934-2111aa80-3486-11eb-929d-dc6e409d6a85.jpg)
![20201202100058_1](https://user-images.githubusercontent.com/60297613/100851935-21aa4100-3486-11eb-9610-bbba9836b940.jpg)
![20201202100536_1](https://user-images.githubusercontent.com/60297613/100851937-21aa4100-3486-11eb-9d4f-ed153ac0e759.jpg)
![20201202100557_1](https://user-images.githubusercontent.com/60297613/100851938-2242d780-3486-11eb-9436-2ca7a434b1ea.jpg)
![20201202100607_1](https://user-images.githubusercontent.com/60297613/100851940-22db6e00-3486-11eb-91a3-7faac9fabf6e.jpg)
![20201202100623_1](https://user-images.githubusercontent.com/60297613/100851933-20791400-3486-11eb-87fe-fedf7b742ce4.jpg)

Log mit Debug Channel 4-7-12-14
[log.txt](https://github.com/Courseplay/courseplay/files/5628079/log.txt)

Bei weiteren Fragen oder Test´s stehe ich gerne zur verfügung :)

**Comment by pvaiko** [comment]
Sorry, wollte nicht zumachen.

@DerBauer2 kannst du bitte mit dem letzten Stand auf Master testen, wenn's geht mache ich ein neues Release daraus.

Danke.

**Comment by DerBauer2** [comment]
weiß jetzt nicht genau was du mit Master meinst? sry

**Comment by DerBauer2** [comment]
Kurzer Test  fehler trat dabei nicht auf.

**Comment by 60erjonny** [comment]
Hallo

Ja, ich teste...

**Comment by 60erjonny** [comment]
Hallo

Soweit, wie ich es getestet habe ( 10 Missionen ) ist alles weider gut.
Gearbeitet wurde mit Striegel, Sähmaschine, Dügerstreuer und Grubber...
Macht weiter so...:-)

**Comment by Tensuko** [comment]
Super! Danke für deine Rückmeldung.

**Comment by Dennis42g** [comment]
Guten Tag ich weiß nicht ob ich hier richtig bin spiele LS19 habe die neuste Version von CP drauf die radlader die an zwei verschiedende stellen an BGA s fahren machen es jetzt gar nicht mehr und wenn nur einer wenn man glück hat am sonsten bleiben sie nur stehen oder machen misst 

mit freundlichen grüßen dennis .

**Comment by Tensuko** [comment]
Leider falsch, hier geht es um Feldkurse, nicht um Radlader.
Zum Thema 2 Radlader: #6165

**Comment by Dennis42g** [comment]
danke für die info
