### ISSUE TITLE
Abfahrer Fährt nicht Korekt ab

### ISSUE THREAD

**Issue by DerBauer2** [Courseplay/courseplay#6427]
Erstes Problem der Abfahrer Stockt hinter dem Hächsler und dieser muss Ständig Abbremsen 

![20201202171224_1](https://user-images.githubusercontent.com/60297613/100899937-a31fc480-34c2-11eb-9937-4c3533bdafae.jpg)
![20201202171300_1](https://user-images.githubusercontent.com/60297613/100899941-a3b85b00-34c2-11eb-9d40-70d3910a8e7e.jpg)
![20201202171600_1](https://user-images.githubusercontent.com/60297613/100899945-a450f180-34c2-11eb-902c-a8ce234d17da.jpg)
![20201202171708_1](https://user-images.githubusercontent.com/60297613/100899948-a450f180-34c2-11eb-9d7d-5d8c81436d62.jpg)
![20201202171724_1](https://user-images.githubusercontent.com/60297613/100899935-a2872e00-34c2-11eb-9c5f-d77c51e98431.jpg)

Zweite Problem er Fährt nicht weit  genug zur seite um am Hächsler vorbei zu kommen 

![20201202171029_1](https://user-images.githubusercontent.com/60297613/100900051-ba5eb200-34c2-11eb-94f9-2a478af24571.jpg)
![20201202171754_1](https://user-images.githubusercontent.com/60297613/100900055-bc287580-34c2-11eb-94f3-c5f1ca175271.jpg)

[log.txt](https://github.com/Courseplay/courseplay/files/5630603/log.txt)

**Comment by Tensuko** [comment]
Das Problem ist bekannt: #5470

**Comment by DerBauer2** [comment]
@Tensuko und das mit den das er denn Hächsler zu lagsam folgt das dieser immer wieder abbremsen muss?
