### ISSUE TITLE
using shovel (mode 9?) when lifting to pre unload position causes vehicle to be stuck in traffic

### ISSUE THREAD

**Issue by JennyD73** [Courseplay/courseplay#6430]
using shovel (mode 9?) when lifting to preload position causes vehicle to be stuck in traffic

**Comment by Tensuko** [comment]
Screenshot, logfile, debugchannel 12 and 14

**Comment by JennyD73** [comment]
![fsScreen_2020_12_03_19_19_19](https://user-images.githubusercontent.com/75444078/101077438-bf902f80-359c-11eb-941a-053f722915d7.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5638458/log.txt)
i think thats them

**Comment by Tensuko** [comment]
Should be fixed, pls try and report.

**Comment by JennyD73** [comment]
perfect, thank you so much , it works great
