### ISSUE TITLE
FS19 frozen when i start drive course

### ISSUE THREAD

**Issue by GoelaJowo** [Courseplay/courseplay#6432]
Hello Guys, I'm new to this courseplay mod and this is my first time using it. At first there's no problem at all, but after I generate the course and press drive course my game just froze and I can't do anything but restart my computer. Is there any mod conflict here or my computer just isn't strong enough?

**Comment by Tensuko** [comment]
Your computer won't freeze from CP use.
Post your logfile and tell us more what you did.

**Comment by GoelaJowo** [comment]
Well I didn't do much, at first I opened the CP HUD and then proceed to jump into my combine and then start to generate course with first headland option then I clicked drive course and the game start frozen when the combine start drove forward then I was forced to restart the computer because I am unable to alt+f4 the game nor do I able to operate any app. Anyway here's the logfile.
[log.txt](https://github.com/Courseplay/courseplay/files/5642803/log.txt)

**Comment by Tensuko** [comment]
Update your FS Version:
Farming Simulator 19 (Steam)
  Version: 1.3.0.1 b4007

As you use Steam, you got to turn off the Beta Program for Version 1.3.0.1 and Update to 1.7.0.1 (iirc)

I wonder what that Error is....
2020-12-04 19:32 Error: Running LUA method 'onCollision'.
2020-12-04 19:32 C:/Users/Home/Documents/My Games/FarmingSimulator2019/mods/FS19_CoursePlay/Conflict.lua:141: attempt to index field 'otherVehicle' (a nil value)

Do you have a screenshot of the exact situation where that happens ?

**Comment by GoelaJowo** [comment]
Here's the screenshot
![FarmingSimulator2019 64bit 04_12_2020 19_53_54](https://user-images.githubusercontent.com/75479536/101167324-524bcf80-366c-11eb-8f87-47165d945aae.png)
And I am currently updating the game and I will let you know if something change.

**Comment by GoelaJowo** [comment]
Hey, I've just updated the game and it seems to work now. Thank you for your help!
