### ISSUE TITLE
Abfahrer kommt nich wenn ich denn drescher selber fahre 

### ISSUE THREAD

**Issue by Playlord75** [Courseplay/courseplay#6433]
hab ein kleines problem vieleicht auch keins aber vieleicht auch einen vorschlag unzwar bin ich momentan am feld drschen und möchte mit einem überladewagen abtanken lassen nuh ist mein problem dsa der abfahrer bei der gewünschten füll menge nicht kommt ich weiß nicht ob es noch ein fehler ist oder noch etwas fehlt das man ihn per tastendruck rufen könnte 
![fsScreen_2020_12_04_14_14_53](https://user-images.githubusercontent.com/71101944/101168081-37ad3280-363b-11eb-8e09-929da58093fb.png)
![fsScreen_2020_12_04_14_13_09](https://user-images.githubusercontent.com/71101944/101168108-3c71e680-363b-11eb-845e-0a68c2452e43.png)
![fsScreen_2020_12_04_14_13_04](https://user-images.githubusercontent.com/71101944/101168119-3e3baa00-363b-11eb-929b-072a26fc1304.png)
![fsScreen_2020_12_04_14_12_58](https://user-images.githubusercontent.com/71101944/101168125-40056d80-363b-11eb-83ed-e24542ca92c7.png)

Sobald ich cp einstelle kommt er aber auch nur solange bis ich cp wieder entlasse
![fsScreen_2020_12_04_14_16_59](https://user-images.githubusercontent.com/71101944/101168376-a8544f00-363b-11eb-9a72-e25a72bcccc1.png)

**Comment by andreasthu** [comment]
Schau mal hier:
https://github.com/Courseplay/courseplay/issues/5272
Da steht:
What is deactivated/doesn't work for now:
Multiple unloaders. You can assign more than one, but they may not be able to handle conflicts in a civilized manner.
Combines/choppers have to be driven by a Courseplay helper. We aren't sure yet if we want to allow other (or manual) drivers, we'll see.


D.h. selberfahren funktioniert nicht. 
Der abfahrer kommt nur, wenn auch cp den Drescher fährt.
Lg
Andreas

**Comment by Mike1977** [comment]
Nimm Autodrive als Abfaher... Der kommt auch wenn du selber fährst oder den Ingamehelfer nimmst.
