### ISSUE TITLE
[question] Autodrive option in settings

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/courseplay#6436]
Hello everybody I would like to ask you how to use the setting option autodrive refill and unload in CP. I have already network of route in autodrive, I'm not sure what I'm missing here

**Comment by Tensuko** [comment]
Make a normal Fieldworkcourse and start CP and in advaced Setting you got to turn on use autodrive to refill and unload.
Then Start CP.
What you got to do on AD I got no Idea. Best is if you look for Tutorials.
