### ISSUE TITLE
Mode3 Error ?

### ISSUE THREAD

**Issue by WillT7** [Courseplay/courseplay#6438]
When I set up coureplay to use the overloader course, the menu for courseplay will disappear then i will loose control of the game the camera will room out and the vehicle will turn to one side and will drive at full speed. I have taken out all my mods and left only coureplay in but it still happens.

**Comment by Tensuko** [comment]
logfile ?

**Comment by WillT7** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5647129/log.txt)

**Comment by Tensuko** [comment]
Available mod: (Hash: 3d13a2a4ed7716b0cddaf31baf678c0f) (Version: 6.02.00077) FS19_Courseplay
https://github.com/Courseplay/courseplay/wiki
https://github.com/Courseplay/courseplay/releases

Update CP!

2 GEO is not good:
Available mod: (Hash: 890950e08af98c939e11844cc538255e) (Version: 1.0.0.0) FS19_Geo_scotland
Available mod: (Hash: 26334e244c57543f90e95651cf7ce4b4) (Version: 1.0.0.0) FS19_Geo_Yorkshire

This mod can make trouble:
(Version: 1.4.0.0) FS19_REA

And just in case:
only one map in mods folder.

**Comment by WillT7** [comment]
Whats the latest version if you know?

**Comment by Tensuko** [comment]
Just check the link I posted.... 6.03.00008
