### ISSUE TITLE
Courseplay Overloader

### ISSUE THREAD

**Issue by WillT7** [Courseplay/courseplay#6439]
I have set up coursepaly on the overloader option but it wont go to the combine it just sits at the stop point
![fsScreen_2020_12_05_14_40_18](https://user-images.githubusercontent.com/75526222/101245881-d3a47000-3707-11eb-8e2b-38f156341daa.png)
![fsScreen_2020_12_05_14_40_12](https://user-images.githubusercontent.com/75526222/101245902-e454e600-3707-11eb-8b4f-303eb095f50b.png)

**Comment by Tensuko** [comment]
#5272

**Comment by jonfive** [comment]
i had the same problem, i was using start point - specifically from the mentioned #5272 this worked for me: 

- Select 'Unload' as a starting point to wait for the combine requesting an unloader, any of the other option will make you start on the unload course

**Comment by Guilerbom** [comment]
after version 6.03.00005 when I use mode 3, the tractor goes to the waiting point, unloads on the trailer and no longer leaves the waiting point!

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/releases update to .00008 ?

**Comment by bkoster** [comment]
After version 6.03.00003 when i use mode 3 tractor goes to the waiting point, unloads on the trailer and no longen leave waiting point.
Also 6.03.0008 has the same problem.
By version 6.03.00002 it works fine.

**Comment by Tensuko** [comment]
![mode3](https://user-images.githubusercontent.com/27344744/101260103-aa96d600-372d-11eb-88a7-732447da85ba.png)
Adjust this Value that got added for say when to stay and when it is allowed to drive on.

**Comment by bkoster** [comment]
Ok i wil test it out
Thank you for youre quick reaction.

Op 5 dec. 2020 om 19:11 heeft Tensuko <notifications@github.com> het volgende geschreven:

﻿

[mode3]<https://user-images.githubusercontent.com/27344744/101260103-aa96d600-372d-11eb-88a7-732447da85ba.png>
Adjust this Value that got added for say when to stay and when it is allowed to drive on.

**Comment by Guilerbom** [comment]
using exactly this configuration, and the .0008 version, happens the same situation, the trailer unloads the entire product, but does not continue the course

**Comment by Guilerbom** [comment]
Sorry, first i wanted to congratulate you for the work that you develop this courseplay, no doubt for me, is by far the best mod

**Comment by bkoster** [comment]
V6.3.0008 doesn’t work the overloader not leaving waitpoint after unloading.
V6.3.0002 there it works fine

**Comment by Tensuko** [comment]
Read #5272 https://github.com/Courseplay/courseplay/wiki

**Comment by bkoster** [comment]
Sorry i read the wiki but if something is not working and there were more players with the same problem than i am not gonna copy and paste log files because the problem is not out problem it is courseplay.
So i give you the information what works and what not now is up to you.
Have a Nice weekend

**Comment by schwiti6190** [comment]
@WillT7, @bkoster, @Guilerbom could you try this again with the newest version ?

**Comment by bkoster** [comment]
Thank you now it worked fine

Op 6 dec. 2020 om 13:17 heeft schwiti6190 <notifications@github.com> het volgende geschreven:

﻿

@WillT7<https://github.com/WillT7>, @bkoster<https://github.com/bkoster>, @Guilerbom<https://github.com/Guilerbom> could you try this again with the newest version ?

**Comment by Guilerbom** [comment]
> @WillT7, @bkoster, @Guilerbom você poderia tentar isso novamente com a versão mais recente ?

I just tested with the new version, it worked very well, thank you and congratulations for the work
