### ISSUE TITLE
Eine Frage zum Schaufelmodus

### ISSUE THREAD

**Issue by sepp1** [Courseplay/courseplay#6440]
Nur erstmal eine Frage. Geht es nicht das man zwei Radlader auf dem Schaufelmodus fahren hat. Also einen pro BGA. Ich spiele die NF Marsch 4fach 2.4  CP ist die aktuelle Version.

MfG Sebastian

**Comment by Tensuko** [comment]
Einmal vorher suchen hätte gereicht.... #6165
