### ISSUE TITLE
Vorgewende wird 2 mal umfahren

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#6441]
Moin
Kurze Frage: Warum wird das Vorgewende 2 mal umfahren und nach den 2mal fährt der Helfer dann in die Feldreihe rein
![Vorgewende](https://user-images.githubusercontent.com/47453761/101247556-8382d900-371a-11eb-9a11-baef62b8c6ba.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5647324/log.txt)

**Comment by Tensuko** [comment]
Transition vom Vorgewende zur ersten Feldreihe, je nachdem wo dein Start ist und wo deine erste Feldreihe beginnt kann das auch mal ein längerer weg sein.
