### ISSUE TITLE
Slow moving tractor with various tools

### ISSUE THREAD

**Issue by dankellys112** [Courseplay/courseplay#6444]
Video example

 of issue: https://imgur.com/a/YUfGxcO

I set up 2 courses on 2 of my fields 1 course on each field is for lime spreading, the other is for spraying. However when I run them the tractor will only run at 1-2mph, instead of the 12mph it should run it with the spreader or 7mph as it should run with the sprayer.

When I hire a Worker to do the same task, it runs at 12mph/7mph respectively.

Some details below:

**System**: PC
**Map**: Felsbrunn
**Fields**: 21 and 12
**Tractor**: Case 240 CVX
**Spreader**: Bredal K105
**Sprayer**: Hardi Navigator 6000

**Courseplay version**: v6.03.00007 - Updated yesterday 05/12/2020
**Course Setup:** Auto Generated Course
**Courseplay Speed Settings (maxed them all out to test)**:
**Turn Speed**: 52mph
**Field Speed**: 52mph
**Reversing Speed**: 52mph
**Street Speed**: 52mph
**Speed**: Maximum Speed

Some extra info:
Both tractors have Front Loaders attached too.
Cruise control is set correctly when Courseplay is driving, but it never gets close to that speed.
Sometimes, the vehicle will just come to a complete stop in the middle of the course but continue spreading/spraying.
Tractor and tools all repaired to 100%.
No new mods have been installed prior to the issue starting.
Was working fine after updating Courseplay yesterday, issue only started occuring today.
Tried saving and restarting, to no avail.

![dankellys_modslist](https://user-images.githubusercontent.com/75572683/101282091-db791880-37ca-11eb-8fb4-f43c587ba025.PNG)
[dankellys_savegame1.zip](https://github.com/Courseplay/courseplay/files/5648849/dankellys_savegame1.zip)
[dankellys_CoursePlay_Courses.zip](https://github.com/Courseplay/courseplay/files/5648851/dankellys_CoursePlay_Courses.zip)

**Comment by dankellys112** [comment]
UPDATE: It seems to be linked to having the Front Loader attached at the same time. Tried spraying the same fields without the Front Loader attached, and the courses ran without issue. So, a slight inconvenience but an easy workaround.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/releases
https://github.com/Courseplay/courseplay/wiki

Beside that you didn't check releases, a nice bug report, but it should be fixed with Version .00008

**Comment by dankellys112** [comment]
Will give it a try tomorrow with the latest release. Thank you!

**Comment by dankellys112** [comment]
Confirmed fixed in .00008, thanks again!
