### ISSUE TITLE
Mod not installing (nevermind user error)

### ISSUE THREAD

**Issue by Peridactite** [Courseplay/courseplay#6446]
I've rezipped the file and everything, but it still doesn't show up under installed mods ever after rebooting. Did I do something wrong?

**Comment by Tensuko** [comment]
Why rezip ?
Download .zip and place in mods Folder, Done.
https://github.com/Courseplay/courseplay/releases

**Comment by Peridactite** [comment]
https://www.yesmods.com/courseplay-fs19-downloads-tips-tricks/
Because of this ^
By the way I was just afk for a while and then checked back and somehow it's installed now. User error oops.

**Comment by Tensuko** [comment]
Then let this Modpage know, that they write nonsence.
We throw out normal release Versions since more then 1,5 years now, as you can see on Release Page, we have several releases.

Only official source is here on GitHub.
