### ISSUE TITLE
Multi-tool setups 3+ not aligning properly to lanes

### ISSUE THREAD

**Issue by Doczott** [Courseplay/courseplay#6450]
When running multi tools, It seems to align new rows to the waypoint and then aligns to the proper lane once it begins the row. This also affects the TURN settings for the corners. This is illustrated in the attached link.

https://youtu.be/CbWANs7UXLw

Courseplay ver 6.03.00009.dev Multiplayer server

**Comment by Tensuko** [comment]
Not a MP bug, it is the plow Driver.
