### ISSUE TITLE
Courseplay workers being paid when use 'Better Contracts 1.0.0.0' - Mod Issue

### ISSUE THREAD

**Issue by dragon1220** [Courseplay/courseplay#6453]
Hi Guys
Firstly, thank you for all your hard work with this.

Ive noticed on the last two of my save games, Bucks County PA and The Homestead V2,1 that courseplay workers namely those running combines and grain carts are being paid wages and so reducing my money despite the option being switched off. Workers on courseplay for plowing/seeding/fertilising etc dont seem to charge worker wages.

I am using the latest Dev version as downloaded from here
Anyone have any ideas?

Please let me know if you need logs and with what specific debug channels

Many thanks
G

**Comment by Tensuko** [comment]
So it is just Combines and the Mode2 Drivers ?

**Comment by dragon1220** [comment]
hi yes, it would appear so yes. i will do some more testing tonight after work and get back to you. thnks

**Comment by Misamangame** [comment]
Must be a map issue, they are american maps and nobody works in America for free :) But seriously I just finished long harvest with 5 combines and 5 unloaders with no wages taken from me.

**Comment by Tensuko** [comment]
Well it is a bit strange, as I had the same issue once and last time it wasn't there too.
What Version did you had when that was running ?

**Comment by Misamangame** [comment]
If that question is on me I have latest 0.12 version, 5 unloaders on Mode 2 didn't take penny for 4 hrs and now I'm running 3 unloaders on Mode 3 for about hour also without any money beiing taken out. I'm on Wild west map.

**Comment by dragon1220** [comment]
I was using v00011, and then dropped down to 0009 to check that one out, I’ve been working all day today so haven’t been able to check any other versions or maps.

**Comment by jspring0811** [comment]
Are you using FollowMe or AutoDrive or any other mods that could be invoking a helper?

**Comment by dragon1220** [comment]
No and no. It did occur to me earlier that I was doing harvesting contracts at the time, and I have A couple of contract mods I’m using, so could it possibly be that?

**Comment by dragon1220** [comment]
Hi guys, so after much messing about and testing, I think I have found the culprit to be the "Better Contracts" mod. I tested different save games both with it in and without it, and it seems to me that the mod forces the combine drivers only to charge the wage payments, overriding CP

**Comment by Lusankya** [comment]
Can replicate the issue with Better Contracts 1.0.0.0 and Courseplay 6.03.00012.

I'm not familiar with CP's code, but it appears that CP credits the player to offset combine wages.  Better Contracts doubles wages to prevent using helpers on contracts from being a source of income, and CP doesn't consider this.

Adjusting Better Contract's betterContracts.lua resolves the issue:

`function BetterContracts:loadMap()
    [...]

    MissionManager.AI_PRICE_MULTIPLIER = 2 --adjust to 1.  Set to 0 and CP combines will pay you.

    [...]
end`

**Comment by Tensuko** [comment]
@Lusankya thats awesome!
Thank you for figure it out :)
Well thats weird stuff he added there, follow server rules oder use a script to deactivate Helpers if not want that, why hide it in a contract mod ? ...

Anyway thx for let us know.

**Comment by Lusankya** [comment]
Happy to help!

I agree, it's a bit presumptuous by Better Contracts to play around with costs and balancing like that.  I wouldn't consider it CP's problem to fix, especially since there's plenty more important stuff on the tracker.

**Comment by Tensuko** [comment]
Exactly. Will mark it this way so ppl can see it.

**Comment by dragon1220** [comment]
Thank you for finding that! Least it explains why.

**Comment by Tensuko** [comment]
Try with Version 6.03.00018 and report
https://github.com/Courseplay/courseplay/releases

**Comment by Tensuko** [comment]
Tested and it is working.
