### ISSUE TITLE
5 Harvesters issue?

### ISSUE THREAD

**Issue by Misamangame** [Courseplay/courseplay#6455]
Hello guys, I was just running a course with 5 harvesters and there was an issue with rightest one. No matter what course I created with 1,2 or 5 headlands (did not tried without) harvester 2Right never started from first point. At first I thought he just went somewhere randomly but found out he always started from the point where transition from headlands to middle part of the field was. When he finished I tried to start him again from start it did not worked, but when first 2Left harvester finished course this one could start on that right position without any problems. It is actually not an issue just info, maybe it is related to some mistake or I don't know.
All were stock game combines
Quick solution is to buy 6 harvesters and they run like a swiss watch....

**Comment by Tensuko** [comment]
Did you create the course with the 1st point to much in a corner ?
Maybe a screenshot helps.

**Comment by amillio24** [comment]
I'm having issues with 2 combines I get one working but the other just turns off and sits there

**Comment by Tensuko** [comment]
My Combines are all just working fine....
Now we sit here with the Information that for one it does not work and for one it doesn't...

Do you guys think that it could be any helpful to give more information then just 'it doesn't work' ?

**Comment by Misamangame** [comment]
Hello Tensuko, no I always starting course in the middle of the longest side of the field.  In this case field is about 2 km long.  Unfortunately I have no screenshot of course only combine making his way totally offcourse since starting point. Later I found out he is going to that transition point. 
![20201206154939_1](https://user-images.githubusercontent.com/33344465/101605522-8de6f080-3a02-11eb-853a-9dbf3e6d93b1.jpg)

**Comment by Tensuko** [comment]
Ok so I will have a look how it is doing with uneven amount of Combines.

**Comment by Tensuko** [comment]
Can't reproduce
![fsScreen_2020_12_11_10_16_36](https://user-images.githubusercontent.com/27344744/101885128-00d69f80-3b9a-11eb-81fd-f72d7ecda018.png)

**Comment by cyberndj** [comment]
Hi @Misamangame, I've had the same issue before. I've had the issue where the combine was too far away from the starting point and would start at a different section of the course. I was aligning the combine close to the lane that it was configured for (farthest right in my case).

I would you suggest that you move the combine closer to the start node and try again--like start it directly on the start node. See how it goes.

**Comment by Tensuko** [comment]
Closed due to inactivity, like I already said, stay away from corner with the start when use headland and it should work.
