### ISSUE TITLE
[question]Precision DLC fs19

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/courseplay#6456]
Would be possible to add analysis tool to the course play ? Looks like this tool work something like bale roller

**Comment by MarckAmorim** [comment]
Man, this impossibleEm 8 de dez de 2020 17:02, envikowaty <notifications@github.com> escreveu:
Would be possible to add analysis tool to the course play ? Looks like this tool work something like bale roller

**Comment by Tensuko** [comment]
Wont happen.

**Comment by envikowaty** [comment]
Why imposible? If this equipment can work like bale roller should be all fine, we can always on end of field send the analysis files on our own. Looking on the tool there range of it approx 20-25m, it is possible

**Comment by uded** [comment]
Theoretically, it is possible, but I am uncertain whether there is a way to control the probe via normal API. From a purely geometric standpoint you can easily calculate a path that will cover 100% of the field with those probe circles. But this is a task on its own as none of the current logic - AFAIK - is nowhere near that...

**Comment by Tensuko** [comment]
Everything is possible...
The Question is do we want that and is it worth implementing something totaly new while we got other things to do and to fix first, while not even sure if this system is used in the next fs ? It could be a total waste of time so we dicided to not implement new features like this into CP for now.

**Comment by uded** [comment]
I would say that greatly depends. Again, the logic for calculating the path of the vehicle with the probe is really simple. But, as you mentioned, other things come first. And it would, IMHO, require a new mode in the CP with a completely new calculation base. I think it is worth considering, but with a lower priority.

Above I have answered a question from @envikowaty - it's not impossible. But is it worth it right now - I have my doubts. Still, I would like to have it in CP.

**Comment by pvaiko** [comment]
Folks, no one is stopping you from implementing it and create a pull request for CP :)

**Comment by uded** [comment]
Yes, so many people - my clients, my wife, my kids. Plenty of people stopping me :-)
