### ISSUE TITLE
have a series of tractors and equipment forcing about a 1m offset one way or other

### ISSUE THREAD

**Issue by prjndigo** [Courseplay/courseplay#6457]
Ford series TW 25/30 etc. http://www.modhub.us/farming-simulator-2019-mods/ford-pack-1-0/

Not all the tractors are doing it, the TW-10 tracks fine.  Don't know where to look to fix it.  (am still learning the finer points of fucked-up models, more errors you learn the less frustrating compound mistakes you make)

The in-game helper doesn't read them wrong, they track fine for it and they track fine for GuidanceSteering, when they follow a CP track they drive about a meter to the right of it.

Appreciate any guidance.  Additional Stara seeders also causing the offset track and refuse to respond to manual adjustment in-game courseplay track offsets http://www.modhub.us/farming-simulator-2019-mods/stara-prima-4590-v1/  (no matter what side-offset I use it goes right back to the same wrong track)

**Comment by Tensuko** [comment]
Why you don't stick to GIANTS Models as a Reference ?

Just check their XML files and compare then with yours ?!

Also we are not at .00006 we are at .00012

**Comment by pvaiko** [comment]
In general, tractors should not have an offset as long as their root node is in the middle of the vehicle. Same goes for all implements except plows, plows have an auto offset in CP.

**Comment by Tensuko** [comment]
This Information might help you as well https://github.com/Courseplay/courseplay/issues/4595#issuecomment-739723986

**Comment by prjndigo** [comment]
I'm going through other people's mods and seeing if I can fix strange bugs as a learning exercise.  Same thing I did in Trainz 2004.

Looking into the truck and channel 12.
