### ISSUE TITLE
Precision Farming DLC Support

### ISSUE THREAD

**Issue by masneoquil** [Courseplay/courseplay#6458]
Hello Everyone.

I would like to do a request, if it is possible.
With the new DLC, there is a new tool to take soil samples. The tool has a 15m diameter circle (approx.), and by doing a course and setting up the width at 7m wide, CP could take the samples automatically.
Of course I tried, but CP doesn't know how to use the tool.
It would be nice, if possible, that CP start at WP 1, and then, use the tool every 7m. It also needs to send the collected sample to the lab, but this archived by pressing a button.
So, it would be nice, cause on big fields, doing it by hand could be a little too much
Thanks so much!!

**Comment by Tensuko** [comment]
No... #6456
