### ISSUE TITLE
Yellow arrow comes up when i press "Drive course" and nothing happens

### ISSUE THREAD

**Issue by Erlull** [Courseplay/courseplay#6459]
Hi,

When I press "Drive course" I just get this yellow arrow and a distance to the start waypoint. 

I have tried recording new courses as well, but I get the same problem there. And I have deleted all previous courses and tried to start over, but still the same issue.
Any reason why? 

I'm using v6.03.00013

Someone please help me 💯 

Logfile:

https://gist.github.com/Erlull/263258a9497ced77c5f94a2fc54d623d#file-gistfile1-txt

**Comment by Tensuko** [comment]
Mode used ?

**Comment by Tensuko** [comment]
nevermind, I am very sure you placed this one ?
Available mod: (Hash: d22b91ab8b399d815468276bf8d6e04e) (Version: 1.0.0.0) FS19_addon_strawHarvestBonus
You got to download the newest Version from official side, wich should be 1.0.1.0 iirc.

**Comment by Erlull** [comment]
Thank you Sir! When I removed the FS19_addon_strawHarvestBonus it works. Do you have any idea where I can find the 1.0.1.0 version by any chance? Tried to find it, but no luck so far.

**Comment by Tensuko** [comment]
QR Code on the Pellet Packages (ingame), check Creative Mesh for more Details.
