### ISSUE TITLE
Advanced Settings

### ISSUE THREAD

**Issue by Th301** [Courseplay/courseplay#6462]
Hey together,

it's not an issue but a question.

after being away from LS for at least one year, I startet to play again.
Still CP and AD are the most valuable mods ever and I am very happy to see, that you are still doing such a great job on developing this for the community!!

I have a perhaps stupid question but I seem to be "blind".

Where can I find the "Advanced Settings" for Courseplay? I haven't found any key binding to open it.
There seem to be some interesting settings I read about in some Issues but nowhere I found the hint, how to open these settings.

Thank you in advance! :)

**Comment by Tensuko** [comment]
In the CP Hud there is a text named 'advaced settings' for german 'erweiterte einstellung' then you will end up on that page.

**Comment by Th301** [comment]
I was really blind, sorry ^^
