### ISSUE TITLE
Feldgrenzen anzeigen bei erweiterten Kursgenerator?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#6463]
Hallo Leute
speziell in Erlengrat - bei den Wiesen - wäre es im erweiterten Kursgenerator gut, wenn man die Feldgrenzen angezeigt bekäme, wenn man auf ein Feld klickt:
![fsScreen_2020_12_10_09_41_50](https://user-images.githubusercontent.com/24860501/101764660-97df2100-3ae0-11eb-8249-5724f679ca8f.png)
da sind sie ja, weil man bei der Feldgrenzen-Erkennung ja die blaue umrandung angezeigt bekommt.
im pda sind die wiesen ja nicht speziell eingezeichnet, und es würde die kursgenerierung erheblich erleichtern weil man sieht, wo Felder definiert sind.
lg
andreas

**Comment by Tensuko** [comment]
Also das es die Kursgenerierung erheblich erleichtert kann ich nicht ganz nachvollziehen.

Weil letzten Endes baust du ja so wie du es gemacht hast mit Feldgrenzen deine eigenen User Felder, die eine Nummer kriegen.
Auf der PDA Map klickst du auf der Map auf das Feld, bzw die Fläche und egal welche Nummer du da mal vergeben hast, die taucht ja oben rechts dann auch auf...
Generiere den Kurs und los gehts, ich verstehe daher nicht so ganz wofür man vorher noch eine visuelle Markierung vom Feld braucht ?

**Comment by andreasthu** [comment]
hallo tensuko
erstmal als hilfe, ob das ganze Feld gescannt wurde, ob noch wo ecken drinnen sind oder was fehlt,
aber auch für die Kursgenerierung, da die Wiesen in erlengrat so unförmig sind und man in der übersicht eben keine grenzen sieht wie bei den angelegten Feldern in der Ebene, wäre es (für mich) hilfreich um den Kurs zu planen (idealer Startpunkt, Bearbeitungsrichtung, Vorgewende,...)
lg
andreas

**Comment by Tensuko** [comment]
Also ob das Feld richtig gescannt wurde ja das könnte helfen gerade bei Maps wo die Felder manchmal nicht ganz richtig sind.
Zum planen bei Wiesen oder unförmigen Feldern auch.

So leuchtet mir das dann auch ein :) 
Mach ich mal als Suggestion.

**Comment by andreasthu** [comment]
Danke

**Comment by Tensuko** [comment]
Kommt in FS22
