### ISSUE TITLE
Courseplay crashes in multiplayer game

### ISSUE THREAD

**Issue by SgtParalta** [Courseplay/courseplay#6464]
My courseplay has been crashing in various multiplayer games, different maps etc. It only crashes when I generate courses, everytime. How do I solve this issue?
[log.txt](https://github.com/Courseplay/courseplay/files/5672868/log.txt)

**Comment by Tensuko** [comment]
Remove this one:
Error: Failed to open xml file 'D:/mods/FS19PlaceAnywhere/modDesc.xml'.
Available mod: (Hash: d8d1b5e68fbea2a6469d5817b87b1d0a) FS19PlaceAnywhere
Error: Missing descVersion attribute in mod FS19PlaceAnywhere

and this:
Error: Invalid mod name 'FS19_GlobalCompanyPlaceable_DynamicStorageHall (1)'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit

and this:
Error: Failed to open xml file 'D:/mods/mi_tip/modDesc.xml'.
Available mod: (Hash: 86473378d847fb1400df00891da92f86) mi_tip
Error: Missing descVersion attribute in mod mi_tip

You should only have one Map in mods folder at the same time, as well as only one GEO file for Seasons, not several at the same time.

And as I don't see what Error is comeing, I would need the complete logfile and the logfile of the Server.

**Comment by Tensuko** [comment]
Closed due to inactivity.
I mentioned the stuff that needs to be fixed and more details are also needed, read Wiki for how to provide BugReport.
