### ISSUE TITLE
Frage: Drescherverband Ballenpressen

### ISSUE THREAD

**Issue by Tom20214** [Courseplay/courseplay#6466]
Moin Wie kann man im Drescherverband Ballenpressen so das der Kurs passt?

**Comment by Tensuko** [comment]
Also das sind 2 verschiedene Dinge:
Drescherverband ist rein dafür da um auf dem gleichen Kurs den Abstand zu halten.

Aber damit deine Ballenpressen die gleiche Spur benutzen wie deine Drescher, musst du im HUD die Arbeitsbreite auf die gleiche wie die Drescher stellen, geht aktuell nicht anders.

**Comment by Tom20214** [comment]
Danke für die info.
