### ISSUE TITLE
Vehicles drive in kpm instead of mph when units are changed

### ISSUE THREAD

**Issue by ScootersWorkbench** [Courseplay/courseplay#6469]
In the UI, I have to set the street speed to 100(mph) but the vehicle will only drive 62mph.
![Farming Simulator 19 12_10_2020 4_20_26 PM](https://user-images.githubusercontent.com/75384460/101836947-e520ba00-3b03-11eb-9683-fc1e8d5585f3.png)

**Comment by Tensuko** [comment]
Next time check for existing Issues pls #6041
