### ISSUE TITLE
Semi Doesnt Stop at 

### ISSUE THREAD

**Issue by moose31608** [Courseplay/courseplay#6470]
![fsScreen_2020_12_10_17_43_33](https://user-images.githubusercontent.com/53488388/101839281-169f8280-3b10-11eb-8796-0e4dc94d564e.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5676074/log.txt)

**Comment by Tensuko** [comment]
Can't reproduce
![fsScreen_2020_12_11_09_59_16](https://user-images.githubusercontent.com/27344744/101883489-9cb2dc00-3b97-11eb-9b59-58c9caa941f1.png)

**Comment by moose31608** [comment]
In 6.03.00004 the semi use to stop right at the blue start arrow not passed it like it’s doing now

**Comment by Tensuko** [comment]
It does stop exaclty where it should.
What is the actual problem now ?
Like in your Screenshot, that he skips the first bin, I can't reproduce.

**Comment by moose31608** [comment]
When I get back home from work later today I put 6.03.00004 back in and take a picture of what I’m talking about

**Comment by Tensuko** [comment]
That the Truck stops at start, yeah but what is the Problem that he doesn't stop exactly at the stop, but all our trailers stop now exactly at 1st WP ?
I don't get it.

**Comment by moose31608** [comment]
In the earlier version the truck stopped at the first way point not the trailer. Did all the change in the newer version?

**Comment by Tensuko** [comment]
All I can tell you is, that it is working as it should.
It will also move forward if the first bin or trailer is full and always stops at the exact same position (1st WP) so it is basically an advantage, as you can stop more precise to load your Trailer with Convayer, Wheelloader, Overloader and stuff.
You might have to adjust your course a bit, but for that we have the Course Editor.

**Comment by moose31608** [comment]
![fsScreen_2020_12_11_17_21_00](https://user-images.githubusercontent.com/53488388/101960531-a0655380-3bd5-11eb-841f-b7c6284df08a.png)
is there a way that it doesn't pull up so far.

**Comment by Tensuko** [comment]
No, it will stay as it is now and I still dont get your problem for this ?! If it stops in a wrong position for your existing course then use the editor to change it.
It is so simple now to place 1st WP where your trailer got to stop and it is fine.
