### ISSUE TITLE
CP wont start sprayer when additional tank is empty

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#6471]
CP wont start work if main sprayer is empty, but i still have herbicide in additional front tank.
If i load only few liters in main sprayer, 30-40 litres, then CP will start work.
If i stop CP and start it again, it will work just fine.
So, the problem is, CP wont start work with empty main sprayer only on newly loaded game.
https://youtu.be/dHDYdORiF4Y

**Comment by Tensuko** [comment]
Logfile ?

**Comment by bojanh66** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5678002/log.txt)

**Comment by Tensuko** [comment]
What is this ?
(Version: 1.0) FS19SprayUsage

**Comment by bojanh66** [comment]
Its this mod:
https://www.modhoster.com/mods/geschwindigkeitsabhangiger-dungerverbrauch

Here is another video, as you can see, there is definitely some problem with front tank.

https://youtu.be/HDZO98D32LA

**Comment by rohne83** [comment]
Always experiencing such behaviour with the Stara Imperador (the vanilla mod from Giants). For that vehicle, it always wants to just fertilize using the small sprayer on its back, and not the arms, and never got it to spray herbicides. Is CP compatible with such kind of vehicles atm?

**Comment by Lusankya** [comment]
> Always experiencing such behaviour with the Stara Imperador (the vanilla mod from Giants). For that vehicle, it always wants to just fertilize using the small sprayer on its back, and not the arms, and never got it to spray herbicides. Is CP compatible with such kind of vehicles atm?

I can't replicate this issue on Courseplay 6.03.00015.  The Imperador selects which sprayer to use based on whether the arms are extended or not when the course is started.  Are you sure you're extending the arms before starting the course?

An easy test to see which mode CP is preparing to use with the Imperador is to click the calculator icon to auto-set the working width.  If it's showing 28m, it's going to use the spreader.  If it's showing 27m, it's going to use the arms.

**Comment by rohne83** [comment]
> I can't replicate this issue on Courseplay 6.03.00015. The Imperador selects which sprayer to use based on whether the arms are extended or not when the course is started. Are you sure you're extending the arms before starting the course?

Yes, I did. But this only helps when you start the course with a full tank. Once the tank is empty and the Imperador went to the refill course, it will not unfold the arms itself again. Instead it will try to spray solid fertilizer again.

**Comment by Tensuko** [comment]
Try with Version 6.03.00018 and report
https://github.com/Courseplay/courseplay/releases

**Comment by bojanh66** [comment]
Works perfect, issue from 1st post is fixed, great work.
