### ISSUE TITLE
attempt to call method 'getAITurnRadiusLimitation' (a nil value)

### ISSUE THREAD

**Issue by nonya0992** [Courseplay/courseplay#6472]
[log.txt](https://github.com/Courseplay/courseplay/files/5676882/log.txt)

While trying to initiate a course I get an error that causes the controls to freeze and the game to go haywire. Log attached.

**Comment by Tensuko** [comment]
More Information is needed...
What Mode, what Tool etc, screenshots might help as well.

**Comment by pvaiko** [comment]
That error is not in the Courseplay code, that is in the Giants code, not much we can do here. Is the Giants helper working with this setup? I

**Comment by nonya0992** [comment]
Yep, I figured that out too. Thanks for making an awesome mod!
