### ISSUE TITLE
[Question]bunker silo

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/courseplay#6473]
Hello everybody, is there any guide how to run the course play in the bunker for compacting (Mode 10) 

Regards

**Comment by Tensuko** [comment]
Correct compacting is not working as it should right now.
The only thing that rly works is buildup with a shield.

Start the course inside the Bunker and drive to a save spot, place a pause WP and switch to reverse, drive in reverse back to the front of the silo and stop the recording. Thats basically the course for all Modes that you will need for the Bunker.

**Comment by envikowaty** [comment]
Ok @Tensuko I will try to do that, hope it will work. Thank you !
