### ISSUE TITLE
Drescher in "traffic"

### ISSUE THREAD

**Issue by Yonas1050** [Courseplay/courseplay#6474]
Der Drescher zeigt bei dem Manuellen nebenher fahren immer "slowing down for traffic"an, gibt es die möglichkeit dieses abzustellen?

Mfg Yonas

**Comment by Tensuko** [comment]
Im Moment nicht, Änderung kommt noch...

**Comment by pvaiko** [comment]
Fährt der auch langsamer oder ist es nur die Anzeige die stört?

**Comment by HeavensBlade** [comment]
Kann ich bestätigen.

Er fährt auch langsamer.
v6.03.00015

**Comment by PATR10T-SE** [comment]
on 6.03.00016 still dosnt work when driving next to a forage harvester

**Comment by Tensuko** [comment]
screenshot and logfile ?!

**Comment by PATR10T-SE** [comment]
https://abload.de/img/20201222123912_109jcn.jpg

john deere from kemper pack and maragon foldbar, both from modhub

server log https://mega.nz/file/WkxRHQpb#RKdTZTIDfV7-9cY37zrYRTy45hwDw2ZXzYRp6MlxpOc
