### ISSUE TITLE
Holmer Overloader does not stopping at overloading point

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/courseplay#6476]
![20201211185116_1](https://user-images.githubusercontent.com/5993529/101968250-c4c82c80-3be3-11eb-83a8-08c4f2dfadbb.jpg)

drives past the unload point.

**Comment by Tensuko** [comment]
Using one specific overloader kind of tool and saying 'overloaders wont stop' without posting a logfile is wrong...
Overloaders DOES stop at the point, but that one doesnt wich is a huge difference...

**Comment by Commissar0617** [comment]
fair enough. lemme get you that log.
[log.txt](https://github.com/Courseplay/courseplay/files/5683337/log.txt)

**Comment by Tensuko** [comment]
Let me give you some hinds...
When a mod is named with 'unzip me' you should do it (and throw the files out of modfolder then)
General job for you: clean your mods folder.
We will have a look at the Holmer Overloader.

**Comment by envikowaty** [comment]
> Let me give you some hinds...
> 
> When a mod is named with 'unzip me' you should do it (and throw the files out of modfolder then)
> 
> General job for you: clean your mods folder.
> 
> We will have a look at the Holmer Overloader.

So @Tensuko to be clear, there is a option to set up that holmer when is full goes to the P point and waits for the trailer to unload itself and then go back on the field ?

**Comment by Tensuko** [comment]
General yes, but it seems like not working with Holmer, but with other overloader.

**Comment by envikowaty** [comment]
So the first course must be harvest course and second with P point ?

**Comment by Tensuko** [comment]
Nono, thats a completly other thing!
We talk about the overloader, not the Holmmer Harvester!
If you want that one to unload into a trailer, you will have to activate the selfunload at the Harvester.

But again, this topic is about Holmer Overloader!
