### ISSUE TITLE
Holmer overloader not going to combine

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/courseplay#6479]
[log.txt](https://github.com/Courseplay/courseplay/files/5683368/log.txt)

![20201211190301_1](https://user-images.githubusercontent.com/5993529/101988874-3050df00-3c62-11eb-991b-a15144b03933.jpg)
![20201212100521_1](https://user-images.githubusercontent.com/5993529/101988876-30e97580-3c62-11eb-96b9-fca46deb8cc4.jpg)
![20201212100524_1](https://user-images.githubusercontent.com/5993529/101988878-31820c00-3c62-11eb-992b-1c47ea74f73b.jpg)
![20201212100724_1](https://user-images.githubusercontent.com/5993529/101988879-321aa280-3c62-11eb-843d-22da3e43a8f6.jpg)

i've noticed this a few times before, with regular overloaders (i use the coolamon pack for my grain overloaders), but usually restarting the combine will get them started. not so in this case. i don't think there's a fruit issue, as the harvesters' pipes should be well clear of the fruit. 

yes, there's mutiple combines, and multiple unloaders, but i've assigned each unloader to one harvester, and each overloader has a different course.

**Comment by pvaiko** [comment]
Not sure what exactly you were doing but on the last three screenshots (numUnloaders=0) and in the log it is pretty clear that no unloaders were assigned to an combine.

The log does not seem to contain the time period on the first screenshot.

There's not much we can do with this, unless you have a case where there are unloaders assigned and you have the corresponding log with 7, 12 and 14.

**Comment by Commissar0617** [comment]
they are assigned. log corresponds to the bottom three, the top was from an earlier posting about this issue that was closed because i didn't provide the needed details. but in any case, i went back and reproduced the issue again.
![20201212100724_1](https://user-images.githubusercontent.com/5993529/102017096-5e99f180-3d2a-11eb-8e04-53bd2c6fd584.jpg)
![20201213095238_1](https://user-images.githubusercontent.com/5993529/102017097-6063b500-3d2a-11eb-937f-c87a684ec238.jpg)
![20201213095308_1](https://user-images.githubusercontent.com/5993529/102017098-60fc4b80-3d2a-11eb-93a8-4bf251390522.jpg)
![20201213095340_1](https://user-images.githubusercontent.com/5993529/102017099-6194e200-3d2a-11eb-9899-63002b504b87.jpg)
![20201213095407_1](https://user-images.githubusercontent.com/5993529/102017100-622d7880-3d2a-11eb-84ed-f899435617bf.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/5684925/log.txt)

**Comment by pvaiko** [comment]
Ok, thanks. We have an upcoming pathfinder update which should fix at least one of the issues I see here.

**Comment by Commissar0617** [comment]
this might be a more general issue. im getting the same problem with the haulmaster doing chaff, on a different save (haulmaster slightly modified to do bulk)


![20201219114150_1](https://user-images.githubusercontent.com/5993529/102696067-378f6400-41f1-11eb-9f86-ea0018337fd8.jpg)
![20201219114935_1](https://user-images.githubusercontent.com/5993529/102696068-3827fa80-41f1-11eb-9214-422e296cdec6.jpg)
![20201219114943_1](https://user-images.githubusercontent.com/5993529/102696069-3827fa80-41f1-11eb-8907-ef30e8142f47.jpg)
![20201219115020_1](https://user-images.githubusercontent.com/5993529/102696070-38c09100-41f1-11eb-9ed6-7732d9985582.jpg)
![20201219115046_1](https://user-images.githubusercontent.com/5993529/102696071-38c09100-41f1-11eb-9cba-5f90ba30fb3c.jpg)
![20201219115111_1](https://user-images.githubusercontent.com/5993529/102696072-39592780-41f1-11eb-8211-9bb66a95c100.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/5719927/log.txt)

lmk if you need the file for the modded combine
