### ISSUE TITLE
Und wieder ein Problem mit Silo und Radlader

### ISSUE THREAD

**Issue by N3kr0E** [Courseplay/courseplay#6480]
Hallo,

habe leider wieder ein Problem mit meinem Radlader.
Im Screenshot zu sehen, habe ich einen Kurs zum entleeren des Silos in die BGA eingefahren.
Nun gibt es beim Ablauf verschiedene Szenarien:

1. Radlader fährt los, senkt die Schaufel vor dem ersten "P", hebt sie wieder an und dreht um
2. Radlader fährt mit gesenkter Schaufel ins Silo, füllt die Schaufel, versucht dann aber, weiter nach vorne zu fahren
3. Wenn er sich aus Szenario 2 befreien konnte (irgendwann fährt er dann rückwärts), bleibt er kurz vorm Trigger an der BGA stehen und kippt alles davor. 

Als Hinweis: Es fährt nebenbei noch ein 2. Radlader mit CP (habe mal gehört, dass es wohl mal eine Version mit Problemen gab).

Map: NF Marsch 4-fach
CP Version: 6.02 Rev. 00076,dev

Als Radlader fungiert hier ein ganz normaler New Holland.

Hat jemand ne Idee?

Gruß N3kr0e
![20201212183743_1](https://user-images.githubusercontent.com/74174135/101991022-4b474180-3caa-11eb-84a2-313a6476f8bc.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/5683514/log.txt)

**Comment by Tensuko** [comment]
CP Version: 6.02 Rev. 00076,dev ->
https://github.com/Courseplay/courseplay/wiki
https://github.com/Courseplay/courseplay/releases

**Comment by N3kr0E** [comment]
Habe jetzt die neuste Version geladen.

Nun fährt zwar dieser Radlader, dafür bleibt der andere an der zweiten BGA mit voller Schaufel vor dem Einfülltrigger stehen. Vorher hat der Kurs super funktioniert

**Comment by Tensuko** [comment]
Welche version ?
Was genau geht nicht ?
Ist die BGA vlt zu voll ?

**Comment by N3kr0E** [comment]
Version: v6.03.00015
Radlader steht mit voller Schaufel vor der Einfülltrigger der BGA und lädt nicht ab.
Die BGA ist leer, hat eine Kapazität von 100000L.

**Comment by Tensuko** [comment]
dann bitte mal ein logfile mit debugchannel 1 + 2 + 10 posten

**Comment by N3kr0E** [comment]
Erledigt. 
Interessanterweise laufen nun beide Radlader, wenn ich die Debugchannels an habe.
Hier nun aber erstmal die LOG
[log.txt](https://github.com/Courseplay/courseplay/files/5684626/log.txt)

**Comment by Tensuko** [comment]
Try with Version 6.03.00018 and report
https://github.com/Courseplay/courseplay/releases

**Comment by Tensuko** [comment]
Closed due to inactivity.
Use existing Issues in case you still have problems.
