### ISSUE TITLE
MP CP6 - CVX 380 + Ripetide 8400w - Courses not loading correctly / driving

### ISSUE THREAD

**Issue by majora15** [Courseplay/courseplay#6482]
[game.log](https://github.com/Courseplay/courseplay/files/5683921/game.log)
Version Running: FS19 v6.03.00015
Map: Map_FS19_WildWest_16x

For a while the courses will load in fine, however after playing for several hours, or having CP running multiple paths with different vehicles, loading existing courses seems to not load correctly.  In the below game.log I loaded a path that went to the west end of the map, however the vehicle started going to the east of the map.  This issues will appear after playing multiple hours in MP or while connected to the server and having multiple courses running and nothing else.

Workaround: Either reset both vehicle and attachment or restart the server.

**Comment by Tensuko** [comment]
Well, a logfile with only a few lines with random debugchannel doesn't help much.
Also that 16x Map I am sure the course are very hughe....

**Comment by majora15** [comment]
First of all don't ever assume something, the course is only 450 dots.  I was capturing what I thought was the exact event (from the selection of the course to telling it to drive course), thus saving time.
