### ISSUE TITLE
SIlowalzen

### ISSUE THREAD

**Issue by MaxlLS** [Courseplay/courseplay#6485]
Gibts irgendeine änderung beim modus silowalzen mit einer walze weil bei mir fährt der immer am ende des silos nen kreis und weis nich mehr was er machen soll irgendwelche ideen?

**Comment by Tensuko** [comment]
Den Modus werden wir noch anpassen und umbauen, so dass auch Verdichten richtig funktioniert, im Moment wüsste ich keine CP Lösung dafür, sry.

Was ich aber mache ist, das Silo per durchfahren füllen lassen und ab und zu mit einem Traktor durch fahren der hinten diese Walze hat und vorne das hier:
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=124478&title=fs2019

Bisher sehr gute Ergebnisse mit erreicht und durch das befüllen per durchfahren mit CP ist schon sehr viel verdichtet, also habe ich nicht mal viel Arbeit.

**Comment by MaxlLS** [comment]
problem an der sache ist nur einfahren muss ich selbst mit nem ladewagen und wollte eig cp verdichten lassen was mich wundert mit ner älteren CP version hats ja auch geklappt

**Comment by Tensuko** [comment]
'Mit eienr alten CP version hat es geklappt'
Das ist eine sehr gewagte aussage, war es der gleiche Kurs, waren es die gleichen Tools usw usw.
Wie gesagt, wir arbeiten dran.

Warum musst du das Zeug selber in das Silo kippen ?
Aber selbst da kannst du doch schon mal verteilen und bereits über altes material drüber fahren damit das verdichten später schneller geht.

**Comment by stivi83it** [comment]
Bei mir das gleiche. Gleiches Savegame, gleicher kurs. Nur fährt er in die falsch Richtung beim Start dess Kurses. Er fährt einfach bis zum Ende dess Silos und fährt gegen die Wand

**Comment by Tensuko** [comment]
@stivi83it 
Screenshots ?
Kurs ?
Weil der Grund bei dir müsste ein Kursproblem sein, aber bitte wartet doch noch ab wir arbeiten dran.....
Und jetzt bitte keine weiteren Kommentare wie 'ich auch' ohne Infos.... wirklich bitte....

**Comment by Aichinto** [comment]
Als Tipp zum verdichten, ich verwende immer den "Standart" Überführung Modus (modus5) und lass dann einen Traktor vor und zurück fahren, sprich ich fahr das dann so ein , CP fährt das dann punkt für punkt ab und verdichted so, funktioniert eigentlich ganz gut, nur wenn dann der abfahrer kommt muss man den Walztraktor auf seite fahren

**Comment by MaxlLS** [comment]
Jap war der selbe kurs und selbes anbaugerät aber is ja auch nich so die tragödie jetz hat mich nur irgendwie gewundert

**Comment by Tensuko** [comment]
Ja wie gesagt, der Mode ist bei uns auf der Liste zum anpassen, es war uns erst mal wichtig, dass man mit dem Schild richtig Aufschütten kann mit den Einstellungen der Arbeitsbreite.

**Comment by MaxlLS** [comment]
ja hab das jetz auch so gemacht mit schild klappt auf jeden schon viele male besser wie früher

**Comment by stivi83it** [comment]
Also es ist der gleiche Kurs wie bei der 0014, nur bei der 0015 fährt er in die falsche Richtung. 🤷‍♂️ Bin bis zur 002.00069 runter und hab mich langsam rauf bis zur 003.00016 probiert, und bei der letzten tritt dieses Problem dannn auf.
Will euch da auch nicht auf die Nerven gehen, wollte es nur gesagt haben. Wirklich ganz grosse Klasse was ihr
![21D6A3EC-3481-472A-B5DA-FE8BA597FEA1](https://user-images.githubusercontent.com/75932496/102021785-b06e6600-3d82-11eb-9b76-1e3ff618cf66.jpeg)
 mit Courseplay auf die Beine gestellt habt 😍

**Comment by Tensuko** [comment]
Try with Version 6.03.00018 and report
https://github.com/Courseplay/courseplay/releases

**Comment by DonBolli** [comment]
Bei mir geht es super, danke.
Die Neuerung mit der automatischen Reparatur finde ich genial.

**Comment by Tensuko** [comment]
Danke für die Rückmeldung, dann kann hier schon mal zu :)
