### ISSUE TITLE
Wieder Abfahrer Problem

### ISSUE THREAD

**Issue by Blumi39** [Courseplay/courseplay#6487]
So der Drescher dreht wie gewohnt seine Runden...
Aber nun hab ich wieder das Problem das der Abfahrer das erste mal den Drescher Abtankt so wie es sein soll.aber sobald er das zweite mal den Drescher abtanken soll hackt es gewaltig....hab mal paar Bilder mit angehangen und die log Beim Ersten Bild fährt der Abfahrer an eine ganz andere Stelle und bleibt dann da stehen ewig und es passiert nichts....
Beim Dritten Bild fährt er den Drescher das erste mal ganz vernünftig ab aber dann hackt es siehe erstes und zweites Bild was mache ich falsch....

[log.txt](https://github.com/Courseplay/courseplay/files/5684698/log.txt)
![20201213145440_1](https://user-images.githubusercontent.com/66549698/102014525-b5b5bb80-3d56-11eb-9c4a-8b2715f31197.jpg)
![20201213145341_1](https://user-images.githubusercontent.com/66549698/102014535-c1a17d80-3d56-11eb-9fab-ebed5ba9549d.jpg)
![20201213144944_1](https://user-images.githubusercontent.com/66549698/102014537-c5350480-3d56-11eb-84b2-7293136d989e.jpg)
![20201213144910_1](https://user-images.githubusercontent.com/66549698/102014538-c8c88b80-3d56-11eb-94e9-4908595fd6c8.jpg)
![20201213144845_1](https://user-images.githubusercontent.com/66549698/102014542-cc5c1280-3d56-11eb-9cf5-0dbc4b31a9cb.jpg)
![20201213144838_1](https://user-images.githubusercontent.com/66549698/102014545-cfef9980-3d56-11eb-991a-87eb7f6f2324.jpg)

**Comment by Tensuko** [comment]
Nächste Version abwarten...
Mein Abfahrer läuft gerade auf eienr 4fach Map ganz munter.

**Comment by Tensuko** [comment]
Das erste Bild sollte so nicht mehr passieren, das Ziel ist ein Punkt an dem sich Abfahrer und Drescher verabredet haben, ist keine exakte Wissenschaft...
Im 2ten Bild sieht man wegn fehlender Debuginfos nicht was er macht, aber ich vermute mal auf den Pathfinder warten.

**Comment by Blumi39** [comment]
ok da warte ich mal...ich glaub auch in der log steht was von Patfinder nicht finden....trotzdem vielen Dank für deine Arbeit

**Comment by Blumi39** [comment]
wann wird es denn mit der nächsten Version soweit sein?
