### ISSUE TITLE
mode9 schaufelmodus irgendwo abkippen?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#6488]
Hallo 
kann man mit dem mode9 irgendwo in der Pampa abkippen, oder muss da zwingend ein Trigger, Anhänger,.. darunter sein?
wie mach ich das (waitpoint, dumppoint,..) ?
lg
andreas

**Comment by Tensuko** [comment]
Nein, nur in Trigger oder Trailer.

**Comment by Tensuko** [comment]
Das werden wir auch erst mal nicht anders machen, wir sind auf einem recht guten Weg, das was funktionieren soll hin zu bekommen.
Ich behalte das aber für später mal im Hinterkopf.

**Comment by andreasthu** [comment]
Ok, danke
