### ISSUE TITLE
bug arbeitsbreite bei Vorgewende "Kurze Seiten" stimmt nicht

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#6489]
hier die Kursgenerator einstellungen:
![fsScreen_2020_12_13_15_38_46](https://user-images.githubusercontent.com/24860501/102015092-be5bc100-3d59-11eb-8019-94bdaa337686.png)

bei vorgewende passt es noch mit der arbeitsbreite:
![fsScreen_2020_12_13_15_38_56](https://user-images.githubusercontent.com/24860501/102015102-d16e9100-3d59-11eb-855d-b62a174552b6.png)

bei Hoch/Runter hat er nurmehr die halbe breite d.h. er überlappt um die halbe arbeitsbreite
![fsScreen_2020_12_13_15_39_34](https://user-images.githubusercontent.com/24860501/102015116-ed723280-3d59-11eb-9002-fa73e682e881.png)

lg
andreas

**Comment by andreasthu** [comment]
Hallo @Tensuko , @pvaiko 
ich habe das nun noch mit verschiedenen Geräten getestet,
diese Situation tritt nur mit Düngerstreuern auf.
bei Spritzen, Grubbern,.. funtioniert das einwandfrei.
kann es sein, da bei düngerstreuern der "workAreaStart" (x=0) in der mitte beginnt, und die  "workAreaEnd" (x=9) bzw  "workAreaHeight" (x=-9) links und rechts dahinter sind die Fehlerquelle ist?
bei allen anderen Geräten sind ja "workAreaStart" und "workAreaEnd" vom X wert gleich, abgesehen von + bzw - davor.
lg
andreas

**Comment by tomy852** [comment]
Hallo, 
also bei mir hab ich das gleiche Problem mit Grubber und Sämaschine und nicht nur beim Düngen.

![kurzeSeiten](https://user-images.githubusercontent.com/51209411/103216465-6e165e80-4916-11eb-8765-989cf778d331.jpg)

**Comment by Ulanawius** [comment]
Hallo und vielen Dank für die tolle Arbeit an der Weiterentwicklung von Courseplay!

Der hier beschriebene Fehler tritt bei mir mir immer auf - egal ob Grubber, Sämaschine oder Mähdrescher - wenn ich   Vorgewende "kurze Seite" auswähle. Die Screenshots habe ich auf der Felsbrunn in einem neuen Spielstand mit CP (6.03.00017) als einzigem Mod erstellt. Auf anderen Karten tritt der Fehler aber auch auf (z.B. Ravensberg, MVP19).

Grubber - 2,9m
![Farming Simulator 19 Screenshot 2020 12 29 - 16 48 12 71](https://user-images.githubusercontent.com/76711921/103298613-0259f180-49fb-11eb-83e0-0d6011e83eba.jpg)
Sämaschine 3m
![Farming Simulator 19 Screenshot 2020 12 29 - 16 51 11 11](https://user-images.githubusercontent.com/76711921/103298615-02f28800-49fb-11eb-87d0-70b120dfb907.jpg)
Mähdrescher 4m
![Farming Simulator 19 Screenshot 2020 12 29 - 16 52 31 39](https://user-images.githubusercontent.com/76711921/103298619-038b1e80-49fb-11eb-8137-aac952ebdf79.jpg)
Scheibenegge 16m
![Farming Simulator 19 Screenshot 2020 12 29 - 16 56 48 64](https://user-images.githubusercontent.com/76711921/103298620-0423b500-49fb-11eb-8d67-e98079ee2d74.jpg)

Vielleicht hilft das bei der Fehlersuche.
VG!

**Comment by pvaiko** [comment]
Should be fixed in 19

**Comment by andreasthu** [comment]
Danke für die info,
Werden ich das nächste mal gleich versuchen. 
Lg
Andreas
