### ISSUE TITLE
Mist laden mit Radlader klappt nicht

### ISSUE THREAD

**Issue by Friendlyx** [Courseplay/courseplay#6492]
moin, ich weiß wir hatten dieses Thema schon sehr oft aber nun geht es wieder mal nicht nachdem alles beim letzten Mistfahren alles super funtioniert hat. Die damalige CP version weiß ich nicht mehr aber nun ist es die aktuelle dev version.
Alle Kurse sind unverändert geblieben, genau so hatte es letztes mal geklappt.
Jetzt hält der Schaufelkurs immer dort an.
![fsScreen_2020_12_14_11_43_38](https://user-images.githubusercontent.com/6493968/102073871-3a124800-3e04-11eb-9f6d-81ce925a1f35.jpg)
dieser eintrag betrifft einen anderen helfer den ich gestartet habe, also nicht zusammenhängend mit dem F

ehler
2020-12-14 11:59 :06 [info lp16754] 1600 Turbo (#3): AI driver in mode 5 starting at 1/634 waypoints (COURSEPLAY_FIRST_POINT)

[log.txt](https://github.com/Courseplay/courseplay/files/5688329/log.txt)

**Comment by Tensuko** [comment]
Das ist auch keiner Fehler das ist ein einfacher Logeintrag.

Dein Kurs am dritten Wartepunkt sitzt nicht richtig. Es mag sein, dass es so mal funktioniert hat, aber nur weil etwas funktioniert hat heist es eben nicht, dass es so richtig war, desshalb haben wir das noch mal angepasst und korrigiert.


![fsScreen_2020_12_14_12_34_21](https://user-images.githubusercontent.com/27344744/102076947-d2123080-3e08-11eb-9d19-f34f74a2588c.png)

Der markierte Wegpunkt ist der, der die Richtung bestimmt in die wir gucken ob da ein Trailer ist.
Rot ist, wie mein Kurs jetzt nach einem Trailer schaut, blau wäre es, wenn ich den Wegpunkt zum blauen Strich ziehen würde.
Man sieht es auf deinem Bild schlecht, aber scheinbar ist bei deinem Wartepunkt noch ein Wegpunkt, der die Richtung zum gucken versaut + der Wartepunkt muss (wie auch in FS17 Zeiten) vor dem Trailer sein.

![fsScreen_2020_12_14_12_34_41](https://user-images.githubusercontent.com/27344744/102077112-143b7200-3e09-11eb-9379-34db2a187655.png)


Ich hoffe, dass ich es bald mal schaffe ein Tutorial dazu zu machen, weil eigentlich ist der Modus echt leicht einzurichten...

**Comment by Friendlyx** [comment]
gut neuer Kurs mit Wartepunkt#3 vorm Trailer läuft.
Danke für die Erklärung!
Ps: irgendwie wäre ein neues Manual schon mal sinnvoll, hoffe du schaffst das irgendwann, denke dann kommen auch weniger issues die keine sind

**Comment by Tensuko** [comment]
Ja ich bin schon am aufschreiben wie doof neben den GitHub und Testaktivitäten.... Aber ich bin dran! :)
