### ISSUE TITLE
Drescher wird nicht mehr abgetankt

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#6494]
Der Drescher wird mit mal vom Abfahrer nicht mehr abgetankt, hat auf den vorigen Feld noch sehr gut funktioniert
[log.txt](https://github.com/Courseplay/courseplay/files/5690154/log.txt)
![Abfahrer](https://user-images.githubusercontent.com/47453761/102107166-b8d1aa00-3e31-11eb-85a7-717defae16ce.png)
![Drescher](https://user-images.githubusercontent.com/47453761/102107179-bbcc9a80-3e31-11eb-9b4f-4b1521a01ebd.png)

**Comment by Tensuko** [comment]
Update ist schon auf dem Weg, abwarten bitte.
