### ISSUE TITLE
Sugg.  "current waypoint" and "work tool needs emptied"

### ISSUE THREAD

**Issue by prjndigo** [Courseplay/courseplay#6495]
Using forage wagon on field it consistently ignores about 8 to 10 meters of windrowed crop (immaterial of forage wagon) when told to return to current waypoint, possibly 'active' waypoint is being pointered as the destination instead of the stopping waypoint?  Easiest work-around would be to go about 2 waypoints back from "current"

Using forage wagon needing to be unloaded should possibly obey "deactivated and release CP driver" selection so that I don't have to do clicking to switch to vehicle and choose it *if* I have not arranged an unload loop for said equipment?

Additonally possibly a bug found on the "Fendt 250 GT" mod, it comes with options for front-loader mount and box body but when an actual front-loader bucket/tool or the box body are not installed it *CP* refuses to do fieldwork with the tractor because "work tool must be unloaded".  It appears that the front loader and/or box body are fill volume number 2 on the mod.  Is there any way to make *CP* sense that there's no need to unload a missing fill unit if a tractor is being used with a cultivator or tool that has its own fill volumes?

thx

**Comment by Tensuko** [comment]
The first point I understand, but about the 2nd I have no Idea what you try to do... 

About the mod, we wont do anything for that right now, as there are more important things to do now.

**Comment by Tensuko** [comment]
Not very clear what is the Issue, as I said the 1st point is unclear. Collecting Straw from Field works like a charm, deactivate and release CP driver is on purpose only when you enter the driver and won't get changed.
The 2nd point I already explained.
