### ISSUE TITLE
Headlands when Harvesting Hay with chopper

### ISSUE THREAD

**Issue by DaToastVan** [Courseplay/courseplay#6498]
Currently I am having issues using a courseplay chopper with either courseplay or autodrive dumpers. It seems that courseplay chopper stops once it starts to pick up a windrow, but it has not sent its finished turn signal to the dumper, leaving the dumper sitting still waiting for the chopper to finish its turn, and the chopper is not moving.
Can you make it so when the chopper collects some product it sends the finished turn signal to the dumpers.
I had some screen shots but they were too big to add.
Using latest version of courseplay
Have some other issues too, but I should be able to make it work with just this fixed.
Thanks

**Comment by Tensuko** [comment]
logfile with debugchannel 4 7 12 and 14

We don't have to make something like this, it should already do it, but it seems to be another problem that you have there so make screenshots and maybe make them smaler but most important is a logfile.

**Comment by DaToastVan** [comment]
I am trying to make a lil vidoe explain the problom, not working great but should be a help.
[log.txt](https://github.com/Courseplay/courseplay/files/5705363/log.txt)

**Comment by DaToastVan** [comment]
Heres my log with autodrive, mght be a bit cleaner then befor.
Note i always play in mp, not singleplayer.
Also, have you made some changes since .15, with .16 I still have issues, but I can seem to recreate the issues I was having befor. Now it seems to work alright with auto drive with SOME harvestors, very slow going tough.
[log.txt](https://github.com/Courseplay/courseplay/files/5705487/log.txt)

**Comment by DaToastVan** [comment]
![delete](https://user-images.githubusercontent.com/66755855/102407874-c9615c00-3fba-11eb-99ef-02800620213a.jpg)

**Comment by Tensuko** [comment]
Well I need it more in detail to understand whats happening here.

We know that CP unloader will follow the chopper as in the screenshot when pick up hay or gras like that, but what does it have to do with AutoDrive ? What is not working with CP Driver ? We don't send any command to AD Drivers.

**Comment by DaToastVan** [comment]
Okay, Thats the wrong screen shot, Ill try an update it with a better one. But at the headllands sometimes there is hay a little befor you would expect it at the row. When the harvestor hits this it stops, and the dumper also stops but too far away. Then the whole show sits still because the harvestor has some in its spout to get rid of and the dumper isnt close enough. Hopefuly I didnt compcate it.

**Comment by DaToastVan** [comment]
![delete](https://user-images.githubusercontent.com/66755855/102719154-5c9bd980-42ba-11eb-9476-421d144f9517.png)

**Comment by Tensuko** [comment]
Duplicate #5470
