### ISSUE TITLE
grain transport

### ISSUE THREAD

**Issue by CUOGER14** [Courseplay/courseplay#6499]
when i create a grain transport loop i start where i want my over loader to empty. then tractor drives to the silo and back to about 10m before the start point to end the course. i have read grain transport several times, the manual states that the grain transporter is suppose to load at start. when the tractor makes the loop, it will continue to drive, and will not stop to refill. i have remade the course, put in wait points (then i have to tell them to "drive now"). everything i could think of. 

[log.txt](https://github.com/Courseplay/courseplay/files/5692982/log.txt)

**Comment by VergylTantor** [comment]
You should start recording at the silo where you are loading (I load it with crop to avoid problems with the extra weight) then drive over the sale point and unload then back to loading point stopping 10m from where you started.

**Comment by Tensuko** [comment]
@VergylTantor thats for loading a filltype

@CUOGER14 
When you want to unload an overloader, you have to place the startpoint where the pipe of overloader is, drive your course and stop few meters befor start, but as this is loading at a startpoint, you do NOT add any filltype in the list, as it doesn't matter what gets filled into the trailer. This is only important if you want to load some specific filltype from a grain silo.

**Comment by CUOGER14** [comment]
I'm using an grain transport to empty an auger cart that's emptying my combine. So I set a path for the auger cart. That works fine. Fills from combine and goes to over load point. Then I set the path for the grain transport. Starting where the auger is going to empty going to silo and back to just before the start point. From here,  the grain transport just drives in circles.

**Comment by Tensuko** [comment]
Maybe this will help you: https://github.com/Courseplay/courseplay/wiki/Mode-1-Changes

**Comment by VergylTantor** [comment]
My mistake, fill % could be set to 0%

**Comment by Tensuko** [comment]
I also updated the webside for this.
Did Harvest a Field for about 10 hourse useing an auger wagon and grain cart in mode1, worked like a charm when follow the instructions.
