### ISSUE TITLE
Precision farming - fertilizing nitrogen issue/bug

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#6500]
Take a look at video.
https://youtu.be/Y5pLs_4aUig 

As you can see, nitrogen level is 80.
After seeding, it is 200, but seeder didnt use any fertilizer (nitrogen) and it is also deactivated in CP options.
Is this a new issue/bug?
Basically, we are getting free perfect fertilization.
I tried seeder without any fertilizer, but then CP worker wont start, it says Needs to refill, so i added only 27 fertilizer to be able to start CP work, but i dont like that it fertilizes ground for FREE.

I think somehow Precision Farming fertilize system is overwriting CP or conflicting.

Can someone confirm this issue ?

here is also log
[log.txt](https://github.com/Courseplay/courseplay/files/5695488/log.txt)

**Comment by Tensuko** [comment]
Before I do anything here I want to know exactly what is this mod:
FS19_GetFullVersion

**Comment by bojanh66** [comment]
Its a fix to not get annoying message Buy Full game version which happens very often.
https://steamcommunity.com/app/787860/discussions/0/1742227898970175092/

I think its because i use Reshade for better colors.

**Comment by Tensuko** [comment]
I don't find any source to this 'mod'

**Comment by bojanh66** [comment]
Yea, its very hard to find.
I have tested now game without any mods, except Money Tool and Precision Farming DLC.
Same issue as above.

**Comment by rmn18** [comment]
er spielt mit ner cracked Version ,daher behaupted er das der Mod schwer zu finden ist ,loool da würd ich keinen Support drauf geben.

**Comment by rmn18** [comment]
> 
> 
> Before I do anything here I want to know exactly what is this mod:
> FS19_GetFullVersion

FS19_GetFullVersion.zip 11.43Kb  10sek to search , etc. Cracked FS Vers. Just a guess

**Comment by KITT3000** [comment]
All script content in this mod:
```lua
-- Blokowanie okna o zakupie pełnej wersji w Farming Simulator 19 --
-- 16.09.2019 --
-- Rockstar94 --

Gui.showInfoDialog = function(self, args)
    local dialog = g_gui:showDialog("InfoDialog")
    if dialog ~= nil and args ~= nil then
		if args.text == g_i18n:getText("dialog_getFullVersion") then
			g_gui:closeAllDialogs()
			print("otóż nie tym razem")
		else
			dialog.target:setDialogType(Utils.getNoNil(args.dialogType, DialogElement.TYPE_WARNING))
			dialog.target:setText(args.text)
			dialog.target:setCallback(args.callback, args.target, args.args);
			dialog.target:setButtonTexts(args.okText);
		end
    end
end;
```

**Comment by Tensuko** [comment]
@KITT3000 thanks for clearing this up.
Already having a look at precision farming...

**Comment by Tensuko** [comment]
Throw out the fertilizer and it should work.
Somehow, even CP is not using fertilizer and texture is looking bright as it is without fertilizer, that DLC think fertilizer is used, just when you have it inside your seeder.

**Comment by bojanh66** [comment]
I found the problem.
Its this mod:
https://www.lsfarming-mods.com/filebase/file/37-realistic-seeder/

It is in conflict with Precision Farming or CP.
If i use basegame seeds, it works fine, but once i put different seeds from that mod, it will either fertilize ground to perfect levels (even if it doesnt use any fertilizer) or if i remove fertilizer from seeder, it wont allow CP to start worker (says something like "Please refill the tool")
Once i used normal basegame seeds, everything was perfect, CP worker starts work without fertilizer and doesnt put any fertilizer into the ground.

**Comment by bojanh66** [comment]
I found the problem, it is Realistic Seeder mod.
Take a look at video:
https://youtu.be/-ccC8in135Q 

- with basegame seeds, there is no problem, CP worker will start to seed with deactivated fertilizer
- but with Realistic Seeder seeds, there is a problem, CP worker doesnt want to start even with deactivated fertilizer...if i put only 10-20 fertilizer, then it will work , but it will fertilize to Perfect Level, same like in 1st video from 1st post.

[log.txt](https://github.com/Courseplay/courseplay/files/5699004/log.txt)

**Comment by Tensuko** [comment]
I don't have realistic seeder and it is very simple:
Put fertilizer in the seeder and deactivate fertilizer, it will make perfect level anyway, throw fertilizer out and it works as it should.

It is just the DLC itself.
What other mods do I don't rly care, especialy in combination with each other, we can't fix other mods problems. This one is about DLC now

**Comment by Gariot** [comment]
Hi

i have the same bug now since i updated from v6.03.00029 to v6.03.00047. I also dont use realistic seeder mod. I will try and throw out the fertilizer as Tensuko mentioned and try again.

**Comment by Tensuko** [comment]
Works good with precisition farming now.
Ofc it will use auto spray and will end up in the best result.
