### ISSUE TITLE
Vorschlag/Anregung: Überführen 

### ISSUE THREAD

**Issue by Aichinto** [Courseplay/courseplay#6501]
Hallo zusammen,  
Ich verwende CP schon ziemlich lange und das teil is einfach klasse, möchte es nicht mehr missen.
Allerdings hätte ich noch eine kleine Anregung bzw. einen Vorschlag zum Modus 5 (Überführen):
Wäre es hier möglich die Einstellung "Am letzten Wegpunkt o. Trigger warten" standardmäßig auf aktiviert zu stellen?

Ich verwende diesen Modus oft un z.b zu meinen Felder oder zum Händler zu kommen, vergess aber dann machmal das "Warten" auf aktiv zustellen, was dazu führt das meine Fahrzeuge versuchen zurück Startpunkt zum Startpunkt zu gelangen.

**Comment by Tensuko** [comment]
#5476
