### ISSUE TITLE
Problem mit Traktoren mit Ladefläche (Unimog, Geräteträger...)

### ISSUE THREAD

**Issue by Alkoholix** [Courseplay/courseplay#6502]
Guten Tag, ich habe ein kleines Problem mit Traktoren mit Ladefläche. Wenn ich einen Düngerstreuer an einen der besagten Traktoren mit leerer Ladefläche hänge, möchte CP den Kurs nicht abfahren und meldet: Gerät muss aufgefüllt werden.  
Besteht die Möglichkeit dieses zu umgehen?

Grüße und vielen Dank ans Team

Edit: Und lässt sich eventuell der Isaria Scout CP-fähig machen um die Bodenproben zu automatisieren?

**Comment by Tensuko** [comment]
Mit Traktoren die eine Ladefläche haben scheint das ja ein generelles Problem zu sein, dann werden wir uns das anschauen.
@schwiti6190 meinst du das ist möglich ? Problem sind natürlich selbst fahrende Feldspritzen...



> Edit: Und lässt sich eventuell der Isaria Scout CP-fähig machen um die Bodenproben zu automatisieren?

Nein, das wird nicht passieren.

**Comment by Alkoholix** [comment]
Danke für die schnelle Rückmeldung. Bevor es Ärger mit Selbstfahrern gibt, darf es auch gerne so bleiben wie es ist.

**Comment by schwiti6190** [comment]
@Alkoholix Leider ist dieses nicht ganz so einfach zu bewerkstelling, da wir zum beispiel wissen müssten wann dieser tank relevant ist oder nicht, d.h. aktuell könn wir schwer unterscheiden ob der tank leer sein darf oder vlt. sogar wichtig ist und voll sein sollte.
Trotzdem Danke für die Rückmeldungen :)

**Comment by Tensuko** [comment]
Tested with 2 different vehicles and somehow it does work with V 6.03.00037
![fsScreen_2021_02_08_07_12_58](https://user-images.githubusercontent.com/27344744/107182466-17a04380-69dd-11eb-83c9-302db056ad02.png)
![fsScreen_2021_02_08_06_58_49](https://user-images.githubusercontent.com/27344744/107182471-1a9b3400-69dd-11eb-876c-191eb653fbc7.png)
