### ISSUE TITLE
small problem with 3x unloaders and 1 harvester (potato)

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/courseplay#6505]
ok so small problem with 3x unloaders and 1 harvester (potato)

3x unloaders has setting to approach around 30% of load but it does not work always...

sometimes harvester is full and its not calling the unloader (maybe to far) or sometimes I need to switch off CP on harvester and start again to sent signal to unloader.

regards

https://gist.github.com/envikowaty/710b361a3ee27a743490d6a3fa15863b

@pvaiko I will add screens letter

**Comment by Tensuko** [comment]
No Screenshots and the Version is also old, we have added a lot of improovement for Mode2 lately, it should work better now.
