### ISSUE TITLE
Axial Flow 240 with tracks has off set on trasfert courseplay

### ISSUE THREAD

**Issue by Vincentfag** [Courseplay/courseplay#6506]
Hi all,

I searched for this kind of topic already open but didn't find anything.

Actualy, i use the 240 axial flow v2.0 combine mods on the western australia map, with two combine : 
One with wheel and the other with tracks configuration.

When i use courseplay for road transfert, the combine with wheel follow well the path while the one with tracks is following the path with an off set of 2 meters which cause collision with other vehicles.

Did you experienced that kind of issue? 
And the best of your help would be how to fix it?
Thank you
[axial9240.txt](https://github.com/Courseplay/courseplay/files/5704969/axial9240.txt)
[modDesc.txt](https://github.com/Courseplay/courseplay/files/5704970/modDesc.txt)

![fsScreen_2020_12_15_21_09_53](https://user-images.githubusercontent.com/76124416/102393655-f58bd580-3fd8-11eb-8845-24ea31cd1bf3.png)

**Comment by Tensuko** [comment]
Mod Issue and nothing we will work on.
Check this for information: https://github.com/Courseplay/courseplay/issues/4595#issuecomment-739723986
