### ISSUE TITLE
1 of 6) CoursePlay on map MVP19, attempts to generate course Field 15 generates error message

### ISSUE THREAD

**Issue by MisterFister2016** [Courseplay/courseplay#6507]
First of all, thank you for this wonderful mod, it has really expanded my interest for the base game.

Map MVP19 (full list of mods available) Field 15, does not seem to allow any course generation.  On this map, Fields 2, 13, and 15 are all ignored by the game-start field autoscanner.  With Field 2, generating with an auto-outline is typically all that is needed.  At Field 13, the field default-state at game start is that Field 13 is planted with alfalfa, and I presume that CP cannot autoscan such a field because alfalfa is a type of "grass."

No such excuse seems to exist for Field 15, or at least not any that I can think of.  See image of error message below, "Course generated successfully but due to the current direction settings it may cause issues when driving."  This creates a headland-only course, which I have not yet attempted to use.

I've attempted to instruct counter-clockwise instead of my preferred-default of clockwise, as well as repositioning the vehicle's starting point.  I suppose that I might not be entirely clear on what "direction settings" might even refer to.

Thank you for your work!  I'll be asking other questions in separate posts.

**Comment by SeriouZ12** [comment]
HI there, 
i also play on the MVP and i made the same discoveries. 

First of all, you should disable the automatic Field Scanner. It just does not work automatically.  (I read that on an older Post here). Also disable load courses at Startup. Safes me about 15 minutes on the game load ;)

Second you can get the field borders by Hand. It works great and on Field 2 and 13 the Generation worked afterwards. Tho i dont recommend it on 13. 

The thing on 13 & 15 is that there are really small parts in the headland. I slightly modified 15 and i get great results from the generator. It takes a loong time, but it does. 

The Red Boxes are where i separated it with the Landscapng tool. The lower left wasnt neccessary but with huge work widths the Headland doesnt work that well. Also the Graincart had trouble going around the Pond blablabla
![image](https://user-images.githubusercontent.com/63880274/102405826-fc6f1400-3fe9-11eb-8133-78308d027218.png)

Field 15 is the same story. Initially i made it three parts but i had to change courses to much,
![image](https://user-images.githubusercontent.com/63880274/102406416-d138f480-3fea-11eb-9dc6-385618e700d6.png)


I attached you my custom fields. They go in your savegame folder. Hope it helps
[CustomFields.zip](https://github.com/Courseplay/courseplay/files/5705488/CustomFields.zip)

**Comment by Tensuko** [comment]
This is a Map Issue.
Thanks @SeriouZ12 for your explanation and customField files.

**Comment by MisterFister2016** [comment]
> This is a Map Issue.

Is there any way to learn past this explanation?  I.e., what "issue" is this?  What might be constructively communicated to a mapmaker to reduce this from happening again?  When browsing for modded maps, is there any way to identify this issue other than with gameplay?

Also, while I've purchased FS22, my concerns here remain in FS19.
