### ISSUE TITLE
2 of 6) CoursePlay on map MVP19, autoscanned fields go missing from CP after several gameplay sessions

### ISSUE THREAD

**Issue by MisterFister2016** [Courseplay/courseplay#6508]
Map MVP19.  When creating a new save, Fields 2, 13, and 15 are the only ones that fail to autoscan.  After approx 10-15 hours of gameplay (across several real-life days) more and more Field numbers become missing, thus requiring the use of generate field-boundary outlines where the Field number is listed as "User Generated."

Full mod list is available, but the standouts are ManureSystem and GuidanceSteering (hard-requirements for the map itself) plus Seasons and AutoDrive, plus many others.  AutoDrive has problems where I have to reload the save once without AutoDrive installed, enter the game, save the map in that state with AutoDrive removed, and then reload the save a second time this time with AutoDrive enabled.  Is it possible that this might be causing some sort of "decay" of CoursePlay field scanning data?

**Comment by Tensuko** [comment]
Same Issue as the other one you created.....
