### ISSUE TITLE
3 of 6) CoursePlay with Seasons?

### ISSUE THREAD

**Issue by MisterFister2016** [Courseplay/courseplay#6509]
I seem to recall being once told that if I want to run CP with Seasons, that it would first be necessary to create the save without CP enabled first, save from within the game at start, then reload the save with CP enabled.  Is this still true?

**Comment by SeriouZ12** [comment]
From my experience it works fine when you start a game with both mods at the same time.

**Comment by Tensuko** [comment]
There is no problem with seasons... Just start your game and done.
