### ISSUE TITLE
4 of 6) Is it possible to manually tweak CoursePlay courses?

### ISSUE THREAD

**Issue by MisterFister2016** [Courseplay/courseplay#6510]
Even when settings for the course indicate circling around obstacles and islands during fieldwork, there are nevertheless a lot of times when CoursePlay simply tries to run a tractor through a very small patch of impassable terrain.  I hope to build up a library of CoursePlay courses that I can select from in future saves on the same map.  Is there anyway to correct a course that doesn't involve deleting it entirely and then generating a new one -- especially when the newly generated version contains the same problem?

**Comment by polosubtil** [comment]
You can do that with the Course Editor.
- Select your course, not sure it works with a temporary course (only one course I think, if you have multiple course like refill, it's messy)
- Press left CTRL + E
- You should see all course point and you should be able to move them with your mouse
- left CTRL + Z to cancel
- left CTRL + F6 to save
There is a bunch of other stuff you can do but that should be enought to avoid obstacles in your saved courses
https://www.youtube.com/watch?v=ZC9jk23XVbM

**Comment by Tensuko** [comment]
Start Editor default is CTRL + Num0

@polosubtil thanks for the explanation :)
