### ISSUE TITLE
5 of 6) How would CoursePlay and AutoDrive be used in combination instead of one or the other?

### ISSUE THREAD

**Issue by MisterFister2016** [Courseplay/courseplay#6511]
I have both mods installed.  For moving vehicles and equipment between locations on the map, I use AutoDrive.  For fieldwork, I use CoursePlay.  Is there any way to design with CoursePlay an assignment for something like carting a harvest to another location without having to manually do so repetitively?  I.e., is there a way to design "[a regular course] and then use AutoDrive to [destination] and return via AutoDrive"?  (I am not extremely versed on either mod -- I know that each mod mentions the other, but I've never had good examples within my experimentation so far.)

**Comment by polosubtil** [comment]
There are a lot of tutorials for that I think :
This one for example : https://www.youtube.com/watch?v=3pZUDxecNLI

**Comment by SeriouZ12** [comment]
Missing in the Video from polo: If you set a parking destination for your vehicle the "use for unload/refill" menue gets the entry "parking" (or something like that). If you enable that you can send it to the field via autodrive, check the start course at destination and have it return to its parking position.
