### ISSUE TITLE
6 of 6) CoursePlay, resuming fieldwork after an interruption

### ISSUE THREAD

**Issue by MisterFister2016** [Courseplay/courseplay#6512]
Sometimes after getting a fieldwork vehicle unstuck, it becomes very difficult to distinguish by the teeny tiny minimap exactly where to place the vehicle to resume -- especially when a course crosses through a field location several times (i.e. while transitioning or transferring between headlands or peninsula-bulges of irregular-shaped fields.

Using the DBG display mode carries an extremely severe performance and FPS hit.  The minimap is very small, and when a course is pegged to equipment-widths of less than 25 meters, it can be essentially impossible to visually check where a vehicle's progress was interrupted.  Can we please have greater minimap-zoom levels to compensate for this?  And what about making overlapping-connections more easily dis-entangled?  How about using a harsher color scheme for the grean-yellow-orange-red indication of course length and progress -- i.e. for someone who might be color blind, or even something user selectable on the fly to help with the problem I mention at the top of this post?

Thank you for this mod!

**Comment by SeriouZ12** [comment]
You can activate that in the Settings Menue. It will then show you every waypoint without lags.
![2020-12-16_22h15_39](https://user-images.githubusercontent.com/63880274/102407438-6a1c3f80-3fec-11eb-8cc6-1a0bc1d5f4f1.png)

**Comment by Tensuko** [comment]
@SeriouZ12 your HUD looks a bit old :)

@MisterFister2016
HUD, Settings, those 3 dots and then start dirver on actual or best fitting (?) waypoint... something like that.

For your general information, GitHub is not a forum to ask any questions, it is a bugtracking platform where you can post bugs and help us to find Problems, wich will also require more Informations, logfiles, screenshots and stuff.... anyway you got all your questions answered, next time do some research on your own on youtube tutorials or real forums.

I am on it to make a new Manuel for CP as well...
