### ISSUE TITLE
Mode 2 the unloader doesn't go to the combine

### ISSUE THREAD

**Issue by willrh2** [Courseplay/courseplay#6513]
When using mode 2 on the latest update the combine sometimes doesn't call the unloader and sometimes the unloader is called but doesn't move. on the odd occasion that it does move the unloader rams thee combine from behind rather than driving along side to empty. trying using the combine on course play and without doesn't make any difference.
![Screenshot 2020-12-16 at 18 24 51](https://user-images.githubusercontent.com/76132412/102411109-61763a00-3fe9-11eb-90d5-adb753dc984c.png)
![Screenshot 2020-12-16 at 20 37 31](https://user-images.githubusercontent.com/76132412/102411126-689d4800-3fe9-11eb-9e4a-26aed97e8e69.png)
![Screenshot 2020-12-13 at 17 58 54](https://user-images.githubusercontent.com/76132412/102411149-6cc96580-3fe9-11eb-93a2-2f5fc99baab6.png)
![Screenshot 2020-12-16 at 18 01 30](https://user-images.githubusercontent.com/76132412/102411167-7226b000-3fe9-11eb-9506-82cba3e8100a.png)
![Screenshot 2020-12-13 at 17 59 01](https://user-images.githubusercontent.com/76132412/102411180-7521a080-3fe9-11eb-9b20-690cc403cc6a.png)
![Screenshot 2020-12-13 at 17 59 38](https://user-images.githubusercontent.com/76132412/102411200-79e65480-3fe9-11eb-9ed6-7bd7c424f78a.png)

**Comment by envikowaty** [comment]
Looks like 👍 the same problem which I posted but lower 

https://github.com/Courseplay/courseplay/issues/6505

**Comment by SeriouZ12** [comment]
From what i know the unloader only works with Courseplay Combine Drivers. It needs to, because it generates  markers for its position as you can see on your last Screenshot (Back Marker).
Also try to reproduce it and enable debug channels 4, 7, 12, 14 and post the log here. This makes Pvaikos life a lot easier

**Comment by envikowaty** [comment]
I've run few test and this problem not appear in version 11.

**Comment by willrh2** [comment]
how do I find the log file? previous versions of the mod have worked using a hired work on the combine and forager.

**Comment by Tensuko** [comment]
My Games\FarmingSimulator2019 log.txt drag and drop it here, but don't forget the activate channel 4 7 12 and 14 and let it run.

**Comment by willrh2** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5710403/log.txt)
w
![Screenshot 2020-12-17 at 15 37 44](https://user-images.githubusercontent.com/76132412/102533026-c2ab1580-409c-11eb-9463-51781ca77f96.png)
![Screenshot 2020-12-17 at 15 37 57](https://user-images.githubusercontent.com/76132412/102533048-c9398d00-409c-11eb-833c-5cf4b1b1c132.png)
![Screenshot 2020-12-17 at 15 38 16](https://user-images.githubusercontent.com/76132412/102533067-cdfe4100-409c-11eb-9599-2b6fcbfa8ede.png)

**Comment by Tensuko** [comment]
> but don't forget the activate channel 4 7 12 and 14 and let it run

you actually have the channels on, but I don't see the debuginfo in your logfile...

**Comment by willrh2** [comment]
![Screenshot 2020-12-17 at 20 25 34](https://user-images.githubusercontent.com/76132412/102551915-34dd2380-40b8-11eb-9e72-b3b8e82a68d9.png)
![Screenshot 2020-12-17 at 20 51 05](https://user-images.githubusercontent.com/76132412/102551928-3c043180-40b8-11eb-9377-d38a6e035fc1.png)
![Screenshot 2020-12-17 at 20 53 03](https://user-images.githubusercontent.com/76132412/102551944-40c8e580-40b8-11eb-981d-4cf3d0d822f3.png)
![Screenshot 2020-12-17 at 20 56 25](https://user-images.githubusercontent.com/76132412/102551955-458d9980-40b8-11eb-9864-e99f7b529dca.png)
![Screenshot 2020-12-17 at 20 56 33](https://user-images.githubusercontent.com/76132412/102551960-48888a00-40b8-11eb-9a91-10e61f2fd4a6.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5712506/log.txt)
![Screenshot 2020-12-17 at 20 50 38](https://user-images.githubusercontent.com/76132412/102551965-4b837a80-40b8-11eb-82d1-60ee54ce0770.png)
![Screenshot 2020-12-17 at 20 50 51](https://user-images.githubusercontent.com/76132412/102551975-4de5d480-40b8-11eb-961f-d594fc70ce0c.png)
![Screenshot 2020-12-17 at 20 50 55](https://user-images.githubusercontent.com/76132412/102551986-5211f200-40b8-11eb-9f41-ca24d330b914.png)

**Comment by pvaiko** [comment]
@willrh2 you posted 8 screenshots, a log file with 18000 lines, zero explanation, what do you expect me to do? Trying to match these screenshots to one of the 18k lines?

Your screenshots 1, 3, 4 and 5 really look like you set a combine offset which you should not do, ever.

**Comment by willrh2** [comment]
I haven't set an offset and I did exactly as asked to do. I dragged and dropped the log file and posted it

**Comment by Tensuko** [comment]
@pvaiko the log.txt was in the middle of the screenshots, I also haven't seen it just randomly found it...

**Comment by Tensuko** [comment]
Try version .00022

**Comment by Tensuko** [comment]
There will be also another Version with some more fixes and updates for Mode2, try that on, will close due to inactivity.
Reopen if still have Problems with Version 25 (soon) and the required debuginformations.
