### ISSUE TITLE
Menu dosnt work

### ISSUE THREAD

**Issue by CarlXVIGustav** [Courseplay/courseplay#6514]
I had this problem where I can open the menu but I cannot click on anything in it. What should I do to fix it?

**Comment by Tensuko** [comment]
logfile ?!

**Comment by CarlXVIGustav** [comment]
> logfile ?!

Where do I find the logfile?

**Comment by Tensuko** [comment]
My Games\FarmingSimulator2019

**Comment by CarlXVIGustav** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5709598/log.txt)

**Comment by Tensuko** [comment]
Sry buddy, but I highly suggest you do read your own logfile and check all you Errors.
You got so many mods to unzip, prefabs that doesn't belong in your mods folder and stuff.... it is even hard to read.

Solve all this, post a new logfile with cleaner modlist and I will have a look again...

**Comment by CarlXVIGustav** [comment]
Okey
