### ISSUE TITLE
BGA Silo Dumping

### ISSUE THREAD

**Issue by mricher-git** [Courseplay/courseplay#6515]
The other day I used autodrive through CP to setup a couse to unload chaff into a bunker. To my pleasant surprise, the tractor appeared to change its offset for each run down the bunker, distributing the chaff across the bunker. When I did the same for bunker two, the offloaders just went straight down the middle, building a bigger and bigger stripe down the center. Can someone tell me when I did differently the first time around and how to properly set that up. TIA.

**Comment by Tensuko** [comment]
No Idea as I don't know your course and not what you try to do with AD.

> The other day I used autodrive through CP to setup a couse to unload chaff into a bunker.

you got to explain this in more detail...

**Comment by mricher-git** [comment]
I'm on Felsbrunn, I have two autodrive locations right at the beginning of both silage bunkers.

I put the offload tractor near the edge of my field and then from CP selected "BGA Bunker 1 and return". Course was created and when the tractors entered the bunker to offload, they started from the right and then each pass progressively went to the left to put an even carpet of chaff across the pit.

Next day I did the same except select BGA Bunker 2 and return, instead of 1, and they just kept going straight down the centerline of the bunker, building a bigger and bigger pile. I tried moving my AD location just inside and then outside of the bunker but I haven't yet determine what caused the nice progressive swaths across the bunker on the first day,

**Comment by mricher-git** [comment]
Since no one comment yet, I'll add more info. I guess what I'm asking is, for this to work:
Automatic distribution in drive through silos (record a straight line in the middle

If I use autodrive to create the course, does it matter where the autodrive destination is? At the beginning of bunker, in the bunker, after the bunker? Because for one of my bunkers it works, for the other, it doesn't distribute and I'm trying to understand why. I'll try more tests using dev tools to fill a trailer and play around, but if anyone knows, would be appreciated.

**Comment by Th301** [comment]
I can't explain why it worked with silo 1.

As far as I know, you have to record different routes through the silo with autodrive and add a seperate waypoint on each of this recorded routes right behind the silo. These routes have to be placed in a folder within autodrive course-manager. Than choose "use folders" in the autodrive settings of that tractor. It will than alternate between all these routes in that folder.

Example of the route manager:

BGA-Silo 1 (This is a folder!)
- Left
- Middle
- Right

Choose "Left" as destination for unload. The first run will go to "Left". The second run will go to "Middle" the 3rd run will go to "Right" and than it starts from the beginning.

**Comment by mricher-git** [comment]
Sounds like a lot of work mate. I have a single destination at the entrance to silo 1, and just like last time, getting CP to load that destination+return, it is definitely swathing right to left, here's some screenshots.

![BGA1](https://user-images.githubusercontent.com/65866023/102662379-afda3300-41b9-11eb-8a31-da9866f58fd2.jpg)
![bga2](https://user-images.githubusercontent.com/65866023/102662384-b23c8d00-41b9-11eb-8a02-4375b561b7d7.jpg)

**Comment by envikowaty** [comment]
@mricher-git  Could you be so kind and tell what two mods you use ? This one I top left corner with some kind of list and the second one, the sexi phone I left bottom corner.

**Comment by mricher-git** [comment]
Top left is Vehicle Inspector mod: https://www.yesmods.com/fs19-mods/scripts/vehicle-inspector-mod-hl/
Second one is my mod, VG PDA, which I just re-wrote for FS19 and I'm just testing it. Should release soon.

**Comment by envikowaty** [comment]
> Top left is Vehicle Inspector mod: https://www.yesmods.com/fs19-mods/scripts/vehicle-inspector-mod-hl/
> 
> Second one is my mod, VG PDA, which I just re-wrote for FS19 and I'm just testing it. Should release soon.

Both of them look crazy cool ! Thank you Mate

**Comment by schwiti6190** [comment]
Could someone please explain to me what exactly you were trying to do with both autodrive and courseplay ? I don't really see the ussage of both here but to be fair I don't really know a lot about autodrive :)

**Comment by envikowaty** [comment]
> Could someone please explain to me what exactly you were trying to do with both autodrive and courseplay ? I don't really see the usage of both here but to be fair I don't really know a lot about autodrive :)

After few test based on what is written here, the bunker silo 2 has some kind of glitch and Cp when passing through is not changing the lane, but when it's going through silo 1 every time change the route (middle,left,right) I think it's a map problem or the bunker

**Comment by Th301** [comment]
I am now interested.
Is Autodrive driving trough the silo or courseplay?

Is it an official feature of cp? The reason why I ask  is, that Tensuko did not mention it in his reply.

**Comment by envikowaty** [comment]
Yes Ad & CP goes without any problem through the silo, just put waypoint behind it - regarding CP just crear route through the silo

**Comment by mricher-git** [comment]
Beyond frustrating... Forget AD, I just recorded a simple straight line through the bunker using CP. Tested it. First run, the truck offset itself. I stopped it, returned it to the start, and every subsequent time, it just went straight down the pipe. It's clearly a bug. I miss the good ol' days ;) Devs, while I absolutely admire your work, I sincerely can't wrap my head around how you can invest hours of your life into coding this thing daily, but no one will spend 5 minutes to explain how it works. The manual on the website is desperately outdated. We really need a more community driven wiki to drive the documentation. It pains me to spend hours to "reverse engineer" how something works when 5 lines of bullets explaining how things are meant to operate would be enough for the community to whip up some diagrams and instructions, and hopefully some translations too. I just tried compacting and leveling mode, I pulled the eject handle after watching my tractor relentlessly drive itself into a wall, and 2 pages of google results of nothing but people experiencing the same problem. Sugar cane chaser drives behind, not next to harvested, so it won't even begin to drive. Even after headland it's pointless. My forage harvester offloaders love to drive through fruit like its hot, if they aren't already too busy turning directly into the harvester and spinning it 180 degrees. My plough leaves V cuts at the end of each strip, and won't use the full length of the tool. Every time I load CP, half my drivers have a 2.5m left tool offset for some reason, driving me nuts. I had to manually patch the Tatra Agro Tuck 6x6, sure it was a small bug in XML under Ackermann steering, but other mods such as AD had no issue identifying the center of the vehicle. Turn on field maneuver is so slow, I may need to have grandchildren to finish the field. Maybe I've just been away too long to remember, but, I don't recall this drama before.

> Could someone please explain to me what exactly you were trying to do with both autodrive and courseplay ? I don't really see the usage of both here but to be fair I don't really know a lot about autodrive :)

Pretty difficult without instructions. They work quite beautifully together if you invest hours understand how they work. I.e. To go X and return really means to from where I am to where I want and return to the next closest AD marked location, not actually back to where I am. 



> > Could someone please explain to me what exactly you were trying to do with both autodrive and courseplay ? I don't really see the usage of both here but to be fair I don't really know a lot about autodrive :)
> 
> After few test based on what is written here, the bunker silo 2 has some kind of glitch and Cp when passing through is not changing the lane, but when it's going through silo 1 every time change the route (middle,left,right) I think it's a map problem or the bunker

Perhaps, but I turned on debug, a BGA bunker is pretty simple in Giants terms, it's just a blank piece of land marked by 3 transforms: location, width, length, and they are in the right place, and CP sees it clearly. But when a tractor in offload of leveling reaches the south side of bunker 2 (the east one) it doesn't recognize the end (or beginning) of it, yet it's smart enough to start dumping its load??

**Comment by Gibbanator** [comment]
sure this CP has errors that do not allow you to use it as attended but adding auto drive was genius. Adding the maps saved courses you had spent so much time on gives a path to and from the field your working on without having to do a new course with CP. 

Sure playing CP in FS17 seemed to run without any errors I am sure the devs working on this will one day get it working to where you can actually let CP do a field without having to baby sit it. That day will be one to celebrate.

**Comment by Tensuko** [comment]
> The manual on the website is desperately outdated. We really need a more community driven wiki to drive the documentation.

I would have less Issues if the community wouldn't spread wrong information, I am fighting this kinda every day... So a Community driven Wiki is not the way to go... and we are working on Website too...

> I just tried compacting and leveling mode, I pulled the eject handle after watching my tractor relentlessly drive itself into a wall, and 2 pages of google results of nothing but people experiencing the same problem

Mode10 is getting a rework as well, almost done, so read the Issues and wait for it


> I had to manually patch the Tatra Agro Tuck 6x6, sure it was a small bug in XML under Ackermann steering, but other mods such as AD had no issue identifying the center of the vehicle.

This is a confirmed bug by GIANTS Converter, and this is just how CP works, we won't change anything on CP when there are just TWO vehicles not working correctly.


> My plough leaves V cuts at the end of each strip, and won't use the full length of the tool.

raise and lower implement settings on adv settings page ?


> Turn on field maneuver is so slow, I may need to have grandchildren to finish the field. Maybe I've just been away too long to remember, but, I don't recall this drama before.

There is no drama, if you find CP doing its job to slow, do it on your own (or create a course with skipping lines ?!)

For the whole Bunker Mode stuff:
It is a CP feature that it will automatically spread the chaff into the Bunker when drive through, got nothing to do with AD.

**Comment by pvaiko** [comment]
@mricher-git 

> We really need a more community driven wiki to drive the documentation. It pains me to spend hours to "reverse engineer" how something works when 5 lines of bullets explaining how things are meant to operate would be enough for the community to whip up some diagrams and instructions, and hopefully some translations too.

We all know we need the manual updated, and there is no need for any new wiki site I think, since anyone can create pull requests here on GitHub to update the existing manual (http://courseplay.github.io/courseplay/en/index.html), including you.

Not sure if you consider yourself part of the community, but since you already spent those painful hours, have you thought about whipping up those diagrams and instructions yourself? We could really use some help there, as your own example with the plow shows, many problems people complaining about already have a solution, they just don't know about it.

> I had to manually patch the Tatra Agro Tuck 6x6, sure it was a small bug in XML under Ackermann steering

Awesome, so you seem to know what the problem with that truck is, instead of this rant here, how about helping us to resolve that issue by explaining what the problem is?

> Turn on field maneuver is so slow, I may need to have grandchildren to finish the field

Nothing changed there since FS17, if you don't like them, add headlands and experiment with different patterns and skipping rows, and if you find that CP is slow performing a _realistic_ turn maneuver, let us know.

**Comment by mricher-git** [comment]
@pvaiko @Tensuko First off, I'm not looking to piss you guys off, I very much appreciate the effort you put into this, and indeed I am willing to help if I can. But it is frustrating, this issue I have raised here for example:

> For the whole Bunker Mode stuff:
> It is a CP feature that it will automatically spread the chaff into the Bunker when drive through, got nothing to do with AD.

Yes I realize that, I said:
> Forget AD, I just recorded a simple straight line through the bunker using CP. Tested it. First run, the truck offset itself. I stopped it, returned it to the start, and every subsequent time, it just went straight down the pipe. It's clearly a bug.

In regards to helping with the website/instructions. Like I said, if you want to give me/the community a few bullets points that would take about 5 minutes to explain how it should work, I'd be more than happy to whip up some accompanying diagrams and push a pull request through. If you're expecting me to continue to spend hours banging it with a hammer until I finally figure it out, well, probably not. Seems @Tensuko would prefer I didn't.
> I would have less Issues if the community wouldn't spread wrong information, I am fighting this kinda every day... So a Community driven Wiki is not the way to go... and we are working on Website too...

Where as you're asking me to... Is this a community driven webpage/wiki or not? It's a bit hypocritical that you're building essentially an automation tool, and even though you're "fighting this everyday", it's on the back burner to address even though it's costing you time and frustration.

Boys, hours upon hours you invest in here, I don't think you realize the sheer number of man hours "the community" puts into to trying to figure things out. There are hundreds/thousands? out there, and many of them aren't savvy millennials smashing refresh on the CP issues page to figure out where things are at, or conversing in a language like "mode 10", especially considering the number of foreign languages out there. They grab it through Modhub and watch endless youtube videos filled with disinformation and stale data, frustrated and trying to figure it out by trial and error. I spent 4 hours myself and browsed a few forums/vids to understand what I was doing wrong in "Mode 10". Apparently the leveling mode just doesn't work. Would have been nice to know. CP6 is I believe literally 2 years old and with all that effort, there's only a couple of lines of text in the Change/FAQ on the wiki to describe the whole thing.
> Mode10 is getting a rework as well, almost done, so read the Issues and wait for it
Where am I to find this information?

>I had to manually patch the Tatra Agro Tuck 6x6, sure it was a small bug in XML under Ackermann steering

> > Awesome, so you seem to know what the problem with that truck is, instead of this rant here, how about helping us to resolve that issue by explaining what the problem is?

For the record... I did: #4595 
> This is a confirmed bug by GIANTS Converter, and this is just how CP works, we won't change anything on CP when there are just TWO vehicles not working correctly.

Sounds like you have different opinions again. If there are only two, and they are base game vehicles used commonly, it would be nice. @pvaiko You ask me to comment on the issue so you can fix it, and I did, @Tensuko says you won't fix it because it's not your fault. I understand it's not a CP issue, but, 2 core vehicles might be worth it.

> Nothing changed there since FS17, if you don't like them, add headlands and experiment with different patterns and skipping rows, and if you find that CP is slow performing a realistic turn maneuver, let us know.
I tried lower early, raise late, headlands, the works. It's a massive implement, it's a problem for anyone don't get me wrong, including manually. The reason the turns are so slow is because it's so big, the tractor drives quite a ways on the field, and then reverses, which takes awhile given it's length. Yes I can work around it, just though you'd like to know it's lifting early at the end of the field and there might be a fix to calculate it's end point. Both of you mentioned creating a course with skipping lines, but I'm not sure I understand. If you wouldn't mind to explain, it would be appreciated.

**Comment by pvaiko** [comment]
> Boys, hours upon hours you invest in here, I don't think you realize the sheer number of man hours "the community" puts into to trying to figure things out.

I'm perfectly aware of this. I don't know how many times in the last few years I asked people (especially the ones complaining) to help updating the manual. They say ok, sure, why not and then I never hear back from them. 

I enjoy working on algorithms but do not enjoy writing manuals (well, if I didn't have a family and a full time job, I'd probably do it). So the manual is hopelessly out of date. If you mean it, let me know, we already have a Discord channel for the manual update, I send you an invite and can get you those bullet points (provided we remember how it should work:). And yes, there may be disagreement in the CP dev team, that's fine, some of us are more relaxed than others :)

> I tried lower early, raise late, headlands, the works. It's a massive implement, it's a problem for anyone don't get me wrong, including manually.

That lower early/raise late combination should work, if it does not, its a bug, open an issue. The point however is that you should avoid this situation altogether, if you add enough headlands there shouldn't be a need to reverse. 

Skipping rows is just what it says, instead of continuing on the adjacent row, we skip one or more rows, that way a simple U turn can work (provided the headland is wide enough). Same is true for the lands and racetrack patterns.

**Comment by mricher-git** [comment]
> I enjoy working on algorithms but do not enjoy writing manuals (well, if I didn't have a family and a full time job, I'd probably do it). So the manual is hopelessly out of date. If you mean it, let me know, we already have a Discord channel for the manual update, I send you an invite and can get you those bullet points (provided we remember how it should work:). And yes, there may be disagreement in the CP dev team, that's fine, some of us are more relaxed than others :)

I totally understand. Nobody likes documentation, myself included, but in this case, I'll make an exception to pay back to the community for all the hard work here. I'll pop by on discord next week after the Christmas rush settles down.

> That lower early/raise late combination should work, if it does not, its a bug, open an issue. The point however is that you should avoid this situation altogether, if you add enough headlands there shouldn't be a need to reverse.
> 
> Skipping rows is just what it says, instead of continuing on the adjacent row, we skip one or more rows, that way a simple U turn can work (provided the headland is wide enough). Same is true for the lands and racetrack patterns.

This is gold, thank you. I never understood what the racetrack and lands patterns were for, and now it totally makes sense. Broader turns and less 3 point tight turns backing up. Duh. I tested it out, including raise late, and it's working. Big thanks!

**Comment by Tensuko** [comment]
Already working on updating the webside and did the first pushes for the english one.
Once I am done I will open an Issue here to ask what you would miss or if you find any mistakes.

**Comment by Tensuko** [comment]
Website is updated (english) and maybe some stuff is missing, but thats another topic.
Bunker distrubution with automatic offset works as intended. Even if start the driver several times regardless of 1st, next, or unloading on field. It gets auto offset.
