### ISSUE TITLE
Issues of loading saved courses

### ISSUE THREAD

**Issue by JarlHulsman** [Courseplay/courseplay#6516]
We are playing multiplayer with the latest courseplay version. Now when i try to load a course. It load's a different course. It looks like it swaps all the courses around. Is this a problem in some kind of cache memory in my computer? I'm the only one having this issue the other 3 guys it just works 100%

**Comment by Tensuko** [comment]
Without a logfile we can't say anything.
Also you might have to reload the Coursepage or reload the course itself if the button is active in MP, that I don't know right now.
Anything else, Coursehandeling in Multiplayer is a problem.

**Comment by PeanutthaKid** [comment]
What debug modes do you need? We've had this issue on dedicated server as well

**Comment by Tensuko** [comment]
channel 5 is for MP actions, but not sure if course loading will be shown correclty.

**Comment by PeanutthaKid** [comment]
So I was unable to see anything in the log about loading courses, however I can recreate the bug by using multiple appended courses as non host.  On MP Dedicated Server, any player can load a course and append another, then the second tool that uses an appended course (example of this is a seeder/planter with an appended refill course) will cause the bug. It then persists until the server is restarted.

**Comment by Tensuko** [comment]
That might be a general Problem with Course on MP.
However we won't work on Coursemanagement for now, this would be a very big Project and there is no time for it right now.
Try newest Version and see if you can manage course somehow and not append any course randomly.
