### ISSUE TITLE
Bunker Silo Levelling Issue

### ISSUE THREAD

**Issue by patch110** [Courseplay/courseplay#6517]
Hi i have an issue where the the levelling tractor basically reverses along the bunker and right out the other end and turns and becomes stuck on the opposite side of the bunker wall. i have included a few pics to show the situation better.
![fsScreen_2020_12_18_11_14_51](https://user-images.githubusercontent.com/32200890/102609609-b027ef00-4123-11eb-9a99-06b962be41ac.png)
![fsScreen_2020_12_18_11_15_36](https://user-images.githubusercontent.com/32200890/102609618-b4eca300-4123-11eb-9528-63e88359bce4.png)
![fsScreen_2020_12_18_11_15_49](https://user-images.githubusercontent.com/32200890/102609632-b9b15700-4123-11eb-9071-d66f082a9f61.png)

**Comment by enderwiggin07** [comment]
You have to use leveler for level&compact in a drive-through bunker, the blade is only for filling up mode in a bunker with a back wall. 

That said I retested mode10 after the recent update using the leveler and it did the same thing, I didn't really do any further testing just not doing silage for now.

**Comment by patch110** [comment]
I have just tried it with the compactor tool and basically its the same result

**Comment by Tensuko** [comment]
Change to mode build-up and it should work better.
We currently working on that Mode10 to improove exactly this kind of behaviour and make it more stable.
Pls stick to other Mode10 related issues, wich is kinda the same.

**Comment by patch110** [comment]
Sorry but i dont understand what you mean by Build up?

**Comment by Tensuko** [comment]
You have now the mode leveling and compacting, click on the text, it will change to a different mode for silos.

**Comment by patch110** [comment]
Filling up?
Thanks
