### ISSUE TITLE
Combine Self Unload - Not available? 

### ISSUE THREAD

**Issue by enderwiggin07** [Courseplay/courseplay#6518]
I must be missing something obvious but I can't get an option to go to Self Unload mode in any harvester, either in modded or clean game.  I tried having the course already saved, hiriing an AI helper like the manual suggests, several different combines.  In the youtube videos I see they can just switch straight to that mode right away from their combine.   Not sure what I've got wrong.

Thanks

![image](https://user-images.githubusercontent.com/50051834/102615362-65927c80-40fb-11eb-8bc5-b7fecdf3a516.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5715664/log.txt)

**Comment by Tensuko** [comment]
selfunload is under adv settings, just turn it on and place a trailer near the Field, then just start a normal work course.

#3882
