### ISSUE TITLE
Mode 10 Bunker Silo Felsbrunn

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/courseplay#6519]
Ok so new version of CP and we have a problem with standard operation in the bunker:

https://gist.github.com/envikowaty/c768b7ab71fe1f434316c8859198c64e

not sure if I run on all the debug options.

on the screen: I use wrong tool:

![image](https://user-images.githubusercontent.com/69640077/102623330-9e097900-4142-11eb-9faf-2d2f6a47554e.jpeg)

**Comment by Tensuko** [comment]
We already have enough Issues of this, pls use the search function to find similar issues.

**Comment by envikowaty** [comment]
I even tried to move back to version 6.1.292 and still getting error that I use wrong tool 😑
