### ISSUE TITLE
Mini-Hud Zeitanzeige

### ISSUE THREAD

**Issue by OGW-LBO** [Courseplay/courseplay#6521]
Hallo,
mir ist aufgefallen das nicht immer die Zeit angezeit wird, wie lange der Helfer noch benötigt.
Mal ist diese da mal nicht, warum auch immer. Das einzige was er immer im Mini-Hud anzeigt ist die Punkte die er noch abfahren muss.
Hab ich hier was falsch eingestellt?
![courseplay](https://user-images.githubusercontent.com/76265133/102700280-5707aa80-424c-11eb-86da-3ad97a62494e.jpg)

**Comment by resultwrap** [comment]
I can confirm. My wife plays with me in multiplayer and her hud doesn't show the remaining time at all.

**Comment by Tensuko** [comment]
Modi, gespeicherte Kurse, oder nur temporäre Kurse ?

**Comment by OGW-LBO** [comment]
gespeicherte sowie auch temporäre Kurse

**Comment by OGW-LBO** [comment]
Nochmal getestet und folgendes Festgestellt:
Der erste Spieler der auf der Map den Courseplay nutzt sieht die Zeit, alle weiteren nicht.
