### ISSUE TITLE
Overloader Mode not working

### ISSUE THREAD

**Issue by GriffinFarms** [Courseplay/courseplay#6523]
I am having trouble making the overloader go to the combine. After I make the course it just sits there. I request it from the combine and still nothing. Any ideas?

**Comment by Tensuko** [comment]
#5272 and WIki

**Comment by GriffinFarms** [comment]
So your saying to use mode 2? It is not an option on a grain cart currently?

**Comment by Tensuko** [comment]
Sure you can use overloader, but how it works and how to provide  Bug Report is written there
