### ISSUE TITLE
Problem with 2x workers with plow/subsoiler not lifting tool

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#6524]
I create course for 2x workers on same field with subsoilers.
2 headlands and up/down rows.
Once they finish 2nd headland and continue to 1st up/down row, they wont lift tool, but continue driving with lowered tool, which can take few minutes until they reach 1st up/down row, especially on big fields.
I tested with only 1 worker and it works good, so problem is with 2x workers.

**Comment by Tensuko** [comment]
logfile with channel 6 12 and 14

**Comment by bojanh66** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5724215/log.txt)

**Comment by bojanh66** [comment]
Also here is another "issue" which happens with 2x tools and Activated Use pathfinding in turns.

https://youtu.be/zsbQaf5-tEE 

With deactivated , it works fine...but i prefer to have this option activated because it helps with sprayers when going from one to another row, but in this case with 2x tools, it is causing an small issue where worker goes whole circle around the field for the next row.

![Untitled](https://user-images.githubusercontent.com/32069662/102778542-0c447a80-4393-11eb-8065-42ff7bd14176.jpg)

**Comment by magicmana** [comment]
if  can help  i have the same problem  with 2 combine using convoy : https://www.youtube.com/watch?v=tgxvjV3nyoI
at  one moment the right  combine start   to use headland for go to next point.

**Comment by Tensuko** [comment]
> 
> 
> logfile with channel 6 12 and 14

@magicmana

**Comment by magicmana** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5738173/log.txt)
done

**Comment by magicmana** [comment]
had  the  bug  again on a combine  and  with a  tractor with a plow too ,  each   time was the vehicle who are define  to work at right (asymetric)
i tryed to edit the course and  is appear that  moving the  green point  reproduce  the bug  made some try with  some other green point , and   when you move a lot the  position of the green  point ,  the  vehicle start to chose  the wrong direction.

**Comment by Tensuko** [comment]
Should be fixed long ago.
If not make a new Issue with new logfiles pls.
