### ISSUE TITLE
When request driver and pipe is in fruit, reverse out of fruit before actually call the driver

### ISSUE THREAD

**Issue by BejanCorneliu** [Courseplay/courseplay#6525]
Howdy,

I have 1 combine + 1 auger with a bigbud + 1 tractor with trialer.

When the weather gets worse, my combine stops for a better weather. It was 60% full and with a pipe on the fruit side. I was thinking of using this time to unload, so I push the "driver request"

Because the pipe was on the side with the fruit and below 95% load, the combine made no room for auger. When the auger aligns with the combiner, my combine start lateral maneuvers and took the lateral distance from the auger. Then I picked up the auger and aligned myself with the combine. Again combine start side maneuver

**Comment by Tensuko** [comment]
Sry but I don't know what happens there.
Screenshots or even a Video will help more.
Also a logfile with channel 4 7 12 and 14.

It sounds a bit like the pipe was in the fruit, thats why it will reverse out of fruit and won't call unloader even when over set start %.

**Comment by BejanCorneliu** [comment]
Yes. The pipe was in the fruit but the combine below 100% load and did not reverse out. The combine remains in the line. When the combine stops due to soil wet the load was 60%. 

In first i push "request driver" from combine. When the auger align with the combine... the combine start to reverse out.  Second and third time i was driving myself the auger and realign. Same. After 3 atempt of the auger to align to combine the combine was 3 lines side out of the main line course.

Screenshots i don't have ; And i don't know how to find logs

**Comment by Tensuko** [comment]
But this only happened when it started to rain ?

**Comment by BejanCorneliu** [comment]
It was not raining. Evening came and the soil got to wet for harvesting

**Comment by Tensuko** [comment]
So it is a Season problem ?

**Comment by Gibbanator** [comment]
it is called moisture... you can get that without rain.

**Comment by Tensuko** [comment]
Moisture is not a part of vanilla game, what are you talking about exactly ?!

**Comment by BejanCorneliu** [comment]
I don't think it is a Season problem.

The problem is : combine stops at 60% load because evening came and the soil get wet. A text recomending not to harverst apears. 
Because the load was below 95% the combine stops in line of the course without making side reverse. The pipe point to the fruit. 
So ... i was thinking to empty the combine.  I push "request driver" and the auger came and align.  As soon as the auger align with the combine and combine stats to pipe out... the combine trigger the reverse out manouver. In the next 2 attempts to realign myself the auger... as soon as the auger was align with the combine... the combine start reverse manouvers

I think the problem is : because the pipe was pointing  the fruit and was below 95% load ( the 95% point load where i see that the combine start side reverse manouver) , the combine did not make this manouver. But when the bigbudy with my auger finish aligning with the combine pipe.... the combine start side reverse...over... and over for each align retrys

**Comment by Tensuko** [comment]
Got it, but that got not even anything to do with rain or moisture.....
Will see if we can handle it like that I wrote in the Headline.

**Comment by BejanCorneliu** [comment]
Yes. I did not say anything about rain. The combine just stop at 60% when the evening came and the soil get wet ( because of the evening ? )

**Comment by pvaiko** [comment]
@BejanCorneliu If you have a savegame (with vanilla vehicles and map, and Seasons of course) where I only have to start to combine to reproduce this, I'll take look at it. 

Otherwise please understand, we can't spend hours trying to reproduce a scenario like this.

**Comment by Tensuko** [comment]
Closed due to inactivity.
