### ISSUE TITLE
field work mode suggestion

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#6527]
I very often use the courseplay to perform practically all the jobs in my farm and I wanted to know if it was possible (I don't know about codes and programming) to add various paths of various fields by interposing a path that involves moving from one field to another. For example: I have to plow fields 1,2 and 3. Now I have to load the plowing path of field 1, wait for it to finish, move the vehicle manually, load the path of field 2, and repeat for field 3. It would not be possible instead load the plowing path of field 1, add the path from field 1 to field 2, add the plowing path of field 2, add the path from field 2 to field 3 and finally add the working path to field 3, in so that the CP manages the processing on all fields without close interventions (especially for small fields it would be useful)

**Comment by Tensuko** [comment]
Doesn't work and won't happen.
