### ISSUE TITLE
Not able to set offset on combi mode

### ISSUE THREAD

**Issue by S4TTO** [Courseplay/courseplay#6528]
Hi

I'm trying to use combi mode to unload a chopper for silage, however the offsets on 'mode specific settings' don't work and therefore the tractor + trailer are just sat behind the forage harvester and won't unload it.

Any help would be appreciated :)

**Comment by Tensuko** [comment]
#5470

**Comment by Tensuko** [comment]
if you chopp maize, the drive behind the harvester only on 1st headland

**Comment by S4TTO** [comment]
> 
> 
> if you chopp maize, the drive behind the harvester only on 1st headland

No, it does it for the entire field
