### ISSUE TITLE
Was mache ich falsch

### ISSUE THREAD

**Issue by RudiBergfeld** [Courseplay/courseplay#6529]
Ich habe versucht einen Kurs automatisch zu erstellen auf der NF Marsch version 2.4 og die bilder zeigen was ich gemach habe 
![fsScreen_2020_12_21_19_23_17](https://user-images.githubusercontent.com/10323527/102810305-c3f18080-43c3-11eb-822e-4c6f05519893.png)

und ich bekam diese antwort

im zeifel habe ich noch die Log angehangen
[log.txt](https://github.com/Courseplay/courseplay/files/5725909/log.txt)

**Comment by RudiBergfeld** [comment]
Sorry diese natürlich
![fsScreen_2020_12_21_19_41_17](https://user-images.githubusercontent.com/10323527/102811006-fe0f5200-43c4-11eb-99ef-97d44cd9fdfe.png)

**Comment by Tensuko** [comment]
Startposition mal auf aktuelle Fahrzeugposition stellen und nicht letzte Fahrzeugposition.

**Comment by RudiBergfeld** [comment]
Hab ich schon gemacht bring nichts

**Comment by schwiti6190** [comment]
@RudiBergfeld einmal bitte mit der neuen version testen "Courseplay for FS19 v6.03.00017" :)

**Comment by RudiBergfeld** [comment]
Die neue Version geht auch nicht  die leste Version wo es ging ist 6.03.00016

**Comment by RudiBergfeld** [comment]
oh sorry mein fehler die neue Version geht doch. Bitte das Problem schließen

**Comment by schwiti6190** [comment]
okay :)
