### ISSUE TITLE
max  distance for convoy

### ISSUE THREAD

**Issue by magicmana** [Courseplay/courseplay#6531]
hello 
on big  field in 4x map  , with combine ,with the time and the work of  trailer who empty  all combine , the  first  combine can be at a long distance on the rest of the convoy. that can  increase a lot  the  pathfinding difficult  on  trailer when the  field  start to like to an zebra  and  increase a lot  the  time   on transborder  who start  make the yo-yo  in 2   far  position on the field.

it  is possible  to and a option  who limit the distance  on  convoy .
an  idea  i  have is tu use the  minimal  value on  first combine  who is actually  not  used  for  know  when  first  combine   need to stop.  like on this sample  : 
 combine1_min_distance set to 301
 combine2_min_distance set to 302
 combine3_min_distance set to 303

max_distance = 301+302+303
when  first_to_last combine_distance  >  max_distance  then  first combine  stop

**Comment by Tensuko** [comment]
#4121
