### ISSUE TITLE
Maschine fährt beim umdrehen über das Feld hinaus

### ISSUE THREAD

**Issue by Ostfriese76** [Courseplay/courseplay#6534]
Beim Kalkstreuen wendet der das Gespann auf der Straße bzw. in den Büschen oder Gräben. Auch fängt der Kalkstreuer viel zu früh an 
Screenshots sind vorhanden, weiß nur nicht ob und wie man die einfügen kann.

**Comment by Tensuko** [comment]
Es gibt bereits ein Issue über das Problem, bitte erst suchen, dann neues Issue.
https://github.com/Courseplay/courseplay/wiki
