### ISSUE TITLE
Website is out of date

### ISSUE THREAD

**Issue by thomasedwards** [Courseplay/courseplay#6535]
I’m loving Courseplay, and I’m a web developer – is there anyway I can help with updating the website?

**Comment by Tensuko** [comment]
Yea it is very outdated in terms of how everything works.
I started to update all the Informations 2 days ago.

Can you do graphic disigns ? The Pictures we have that explain the courses are outdated as well and we could need someone who can update them. For Informations on how everything should work we can invite you to Discord and talk about that if you want.

**Comment by pvaiko** [comment]
@thomasedwards yes we badly need that site updated, people sometimes volunteer but then all disappeared so far :)

**Comment by thomasedwards** [comment]
@Tensuko Ah great! I do have experience with various graphic programs, so yes let’s chat!

@pvaiko Yeah it’s always tricky, life finds a way to take over often!

I made this site a while back to compare the default tractors and trailers:
https://farmsimtrader.netlify.app

**Comment by Tensuko** [comment]
Tensuko # 2300
Contact me on Discord :)

**Comment by envikowaty** [comment]
> @Tensuko Ah great! I do have experience with various graphic programs, so yes let’s chat!
> 
> 
> 
> @pvaiko Yeah it’s always tricky, life finds a way to take over often!
> 
> 
> 
> I made this site a while back to compare the default tractors and trailers:
> 
> https://farmsimtrader.netlify.app

That's really good job 👏

**Comment by thomasedwards** [comment]
Thanks @envikowaty! Styling is a bit rushed but it does the job
