### ISSUE TITLE
Harvestor slowing down for wagons operated by MP Clients

### ISSUE THREAD

**Issue by DaToastVan** [Courseplay/courseplay#6536]
In a recent update you fixed it so when running a dumper beside the harvestor it dose not "Slow down for traffic". It seems that when playing MP, it works for the server host but not the cleints. Please see attached picture.
![delete](https://user-images.githubusercontent.com/66755855/102943616-902b5f00-4486-11eb-853c-31a01821fdbb.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5732490/log.txt)

**Comment by pvaiko** [comment]
Should work in 19.

**Comment by SplinterCurty** [comment]
![grafik](https://user-images.githubusercontent.com/42349036/103414348-df0b7f80-4b7d-11eb-8eed-fd69d487d2e8.png)
SP Last Version

**Comment by SplinterCurty** [comment]
^
![grafik](https://user-images.githubusercontent.com/42349036/103414399-0cf0c400-4b7e-11eb-9564-94f24b112532.png)
