### ISSUE TITLE
MP dedicated server - Fields won't scan

### ISSUE THREAD

**Issue by nikieboys231** [Courseplay/courseplay#6537]
In the CP scanner tab, I can't select any fields. When I hosted the server on my computer via FS19 it did work for me but not for my friends. Then we uploaded the save to a dedicated server and now all of us can't scan any fields.

There are some strange things, some fields do show up but glitched. 

It is a custom map: Ravensberg

**Comment by armorium** [comment]
I have same problem here.
I can't select fields in Scanner tap in MP-Sessions (SP work fine). The host of the game can select fields.
Only the "missions fields" can selected from client and host.

Courseplay: initialized 88/88 files (v6.03.00017)
Map: Alpine

**Comment by EisenbahnTommy** [comment]
Good morning, is there already a solution for this problem ?

**Comment by EisenbahnTommy** [comment]
Good morning, is there already a solution for this problem ?

**Comment by nikieboys231** [comment]
nope

**Comment by Tensuko** [comment]
Actually we can only select bought fields and not mission fields.
Will continue here #6530
