### ISSUE TITLE
CP- ausfall

### ISSUE THREAD

**Issue by Wolle1976** [Courseplay/courseplay#6538]
Hallo, ich habe stellenweise das Problem das sich, wenn ich course in ordner verschiebe, verschwindet der CP.
ich kann dann mit diesem Fahrzeug keine course mehr auswählen und wenn ich einen neuen generiere lässt er sich nicht einschalten.
kennt ihr das Problem?

**Comment by Tensuko** [comment]
logfile ?

**Comment by Wolle1976** [comment]
wie??

**Comment by Wolle1976** [comment]
wie kann ich die hochladen??

**Comment by Tensuko** [comment]
Steht im Wiki bzw einfach die log.txt in die Kommentarbox ziehen.

**Comment by Wolle1976** [comment]
[log 24.12.20.txt](https://github.com/Courseplay/courseplay/files/5737128/log.24.12.20.txt)

**Comment by Wolle1976** [comment]
[log 23.12.20. 2.txt](https://github.com/Courseplay/courseplay/files/5737178/log.23.12.20.2.txt)
eftl. ist die Übersichtlicher

**Comment by Tensuko** [comment]
Haben deine Kurse Kreuzungspunkte ?

**Comment by Wolle1976** [comment]
eigentlich nicht

**Comment by Tensuko** [comment]
Hmm, müssen wir uns anschauen was das ist, bisher noch nicht aufgetreten.

**Comment by Tensuko** [comment]
War nicht in der lage das zu reproduzieren, auch ist das hier eine mitlerweile alte CP Version. Es kann gut sein, dass das Problem erledigt ist, daher erst mal zu hier.
