### ISSUE TITLE
Combine and auger colision

### ISSUE THREAD

**Issue by BejanCorneliu** [Courseplay/courseplay#6539]
![t1](https://user-images.githubusercontent.com/10681553/103032590-17e99a00-4569-11eb-9e20-2a483980a34f.png)

The image above is a reproduction!!

In the image above the data were : 
- auger at 100% full load ( not half as it is in the image )
- combine at ~20% ( not empty as in the image ) after unloading to auger
- red X the point where the auger unload the grain  ( there is a ramp and trailler )

After unloading the combine continued on its way and it was expected that in the end she would turn righ. to continue. In the same time auger started its way to the unloading point. Collision happend. 

Same thing happends in other situation when auger start to follow the combine before the combine gets 100% load ( if i modify "start at" ); If in the chase ( auger following combine ) the combine start a turn  ( 180 ) as in the image a collision appears.

Maybe the auger should "know" the active path of the combine and keep a safe distance ( radius ) until the combine request diver

Or better maybe all the active vehicles in courseplay should "know" about each other and keep a safe distance ( new setting ; radius ).  It happened to me in another situation as 2 vehicles with different work to collide

Also ( 4 th ) : if the vehicle is not able to recognize things ( buildings, bales, trees.....) and get stuck and start slippering to be able to stop itself and not continue slippering ( after x seconds ? or something... )

**Comment by Tensuko** [comment]
#5272

**Comment by BejanCorneliu** [comment]
don't understand. Did something wrong ?

**Comment by Tensuko** [comment]
logfile with debugchannels as written in the Issue and wiki

**Comment by rohne83** [comment]
which CP version are you using? With the latest versions there have been very huge improvements to the pathfinder which avoids such traffic conflicts pretty well in most cases now.

**Comment by BejanCorneliu** [comment]
V6.03.00016.dev

**Comment by Tensuko** [comment]
@rohne83 generally you are right, but somehow in some situations, the pathfinder doesn't seem to work at all and a direct path will be created without even trying another path.
That is the case whenver you see a straight path like this.

Ofc the Fruitbypass have to be activated to get nice Pathgenerator Pathes!

**Comment by Tensuko** [comment]
Try version .00022 and keep avoid frui on, this should not happen anymore or just in some rare special cases.
