### ISSUE TITLE
CP editor Lua error

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#6540]
I have a problem with CP editor.
Whenever i edit my course, CP editor automatically save it even without pressing F6 Save changes.
[log.txt](https://github.com/Courseplay/courseplay/files/5737376/log.txt)

**Comment by Tensuko** [comment]
Maybe you should check your game about keybind problems or modconflicts.
Or discribe step by step what you do, make a video or rell us more about what course and stuff.

I edit course kinda daily for testsaves and stuff, no Issue so far.

**Comment by bojanh66** [comment]
I have activated for testing only CP, Seasons and Precision Farming, all other mods removed.
Problem is still here, take a look at video.
https://youtu.be/PrA6iurzQCM 

So even if i move waypoint and exit course without pressing F6 (Save course changes), CP Editor save changes to all courses.
As you can see, i have made windrow 9m and windrow 9m backup and it saved changes to both...am i doing something wrong ?

**Comment by Tensuko** [comment]
Try the reload Button in the HUD to update course, before loading.

Not rly an Error just a weird behaviour that is hard to fix.

It is like a temporary thing and well not all course are changed else you would have several course with several waypoints all arround the map.

**Comment by bojanh66** [comment]
Hm, yea it is indeed very weird behaviour.
Only solution is to save game and quit game, then load again....my original course will still be untouched, but my new edited saved course will be just like i want.
Such a shame it cant be fixed without quiting game and reloading.

**Comment by Tensuko** [comment]
There ist a reload Button in the course Manager Hund Page... Die you try that ?

**Comment by bojanh66** [comment]
Do you mean on Undo ? Yes, i tried that, but it doesnt help if i use option "Delete waypoints to End".
What am i trying to do is this:
i have course for mower, 3 headlands and up/down rows.
then i load that course, delete up/down rows and leave only 3 headlands for windrower (to make it nicer, so baler doesnt miss anything) and save that course as windrow/baler.
Then if i load my course for mower, it is same exactly as windrow/baler course...to fix this, i have to exit game and load game again, then its all good. Hope you can understand me.
![FarmingSimulator2019Game 2020-12-24 00-58-20](https://user-images.githubusercontent.com/32069662/103045187-cc90b500-4583-11eb-9ea2-48876f5f6ef1.jpg)

**Comment by Tensuko** [comment]
Not the undo...
Reload Button - those 2 round arrows in a circle...after remove course from Driver   it shows Up at the Same place where the remove course from Driver Button is

**Comment by bojanh66** [comment]
Can you make me a screenshot and point where is Reload Button, because i cant find it...and i will test tomorrow.

**Comment by Tensuko** [comment]
- load Course
- editor on
- move waypoint
- remove course ( X )
- load course again (change is still there)
- remove course ( X )
- press reload button (see picture)
- load course gain
- course is back to normal (unless you saved editor change with F6)

![fsScreen_2020_12_24_12_16_38](https://user-images.githubusercontent.com/27344744/103085489-1c9e6480-45e2-11eb-84ee-f8bf803b52c3.png)

**Comment by bojanh66** [comment]
Yes, it works perfect, ty for this explanation.
I am using Courseplay for years (playing fs 17 and 19) and i have never seen this "Reload" button and never used it, until now.
This issue can be closed.

**Comment by Tensuko** [comment]
Great :)
The whole course manage system is a bit unstable but we won't change anything on that, rather find a way arround such problems.
