### ISSUE TITLE
Creating path on Fields to shorten the ways for unloaders

### ISSUE THREAD

**Issue by magicmana** [Courseplay/courseplay#6542]
hello  not really an emergency to  devellop  
but  i made some test for create road  on field big  field (30 hectare or more and specially on field with a complex  form )  when  "avoid  fruit" is enable  and  "pathfinding"  enable too it's to create some "road"  to start point/autodrive field entrance  (i put an arrrow as the screnshot )  only 3 or 4 road cutting  the  field  greatly reduce the    idle  time on combine and the number of trailer used  in combi or overloading  driving  mode  

some sample on kanderlin map :

100ha field  :  2claas  lexion 9m maize cutter combine  , and only one transborder needed  (40000l )
![fsScreen_2020_12_23_04_11_08](https://user-images.githubusercontent.com/32802279/103061052-5a7f9680-45aa-11eb-9d94-0fa2fa3b8d65.png)

60ha  field   2 claas  jaguar  silage combine , with maize cutter 9m , and only 3 trailer  (2working , one moving)  with an accectable  idle time
![fsScreen_2020_12_22_10_29_57](https://user-images.githubusercontent.com/32802279/103061163-b77b4c80-45aa-11eb-9f37-ec94b81b7a1b.png)
![fsScreen_2020_12_22_11_55_38](https://user-images.githubusercontent.com/32802279/103061633-43da3f00-45ac-11eb-9530-631898c62ae9.png)

should  be  in the futur an intessesting option   when generating  field course  specially for combine  , to   create some  road   during  first  headland

**Comment by Tensuko** [comment]
I dont rly understand what you talking about....
Can you discribe it in more detail pls ?

**Comment by rohne83** [comment]
Tensuko, I think he's referring to the paths through the field (the narrow violet lines on the maps), which he created himself. Of course this can help the unloaders getting a fruit avoiding path generated more quickly. But in reality I've never seen anything comparable before.

**Comment by Misamangame** [comment]
Yes this will be great help, but don't really see how it will be possible to implement...

**Comment by magicmana** [comment]
![Screenshot_20201224_141014](https://user-images.githubusercontent.com/32802279/103090725-2b8d1300-45f2-11eb-9e8e-efd37386bda3.png)
after   headland    the  first  thing  they  do  is to  make a  "road"   in the   field  they  don't start near the  border of  field ;-)

**Comment by Tensuko** [comment]
That you can get with a different center pattern in the course generator.
Try out lands or racetrack if that is what you are looking for.

So baiscally it is about creating drive path for the unloaders to shorten the way.
Nice Idea.
