### ISSUE TITLE
Course generator and circle obstacle avoidance

### ISSUE THREAD

**Issue by MartinGrisotto** [Courseplay/courseplay#6543]
Hi

sometimes, when obstacle is close to the headland / end of the field, the turning point is generated inside of circled area, thus machine is driving thru obstacle anyway

![image](https://user-images.githubusercontent.com/10392883/103073108-4dbd6b80-45c7-11eb-84e3-a8b2555bad8f.png)

**Comment by bojanh66** [comment]
Same problem for me on Marwell Manor farm with poles in the field.
I used ingame CP editor to move turn waypoint outside of circle and thats how i fixed it.

**Comment by rohne83** [comment]
There already was an issue for this recently: https://github.com/Courseplay/courseplay/issues/6543
They said this won't be easy to fix. Currently workaround would be to add more headlands or edit the course manually with course editor.

**Comment by Tensuko** [comment]
Like @rohne83 said got Issue for this already, so it is a duplicate.
