### ISSUE TITLE
Viele Einträge in der log-Datei durch course generator

### ISSUE THREAD

**Issue by roland45** [Courseplay/courseplay#6544]
Hallo CoursePlay Team!
Habe seit einiger Zeit eine Menge Einträge (keine Errors) von CP in der log.Datei. Bis zu 2500 Zeilen die anscheinend nur vom course generator eingetragen werden. Habe auch wissentlich keinen Debugger eingeschaltet (sind alle grau). Sind diese Einträge gewünscht, kann ich sie ausschalten, oder werden sie durch einen anderen Fehler verursacht. Anbei meine log.txt
[log.txt](https://github.com/Courseplay/courseplay/files/5739169/log.txt)

**Comment by Tensuko** [comment]
Das sind nur harmlose prints, ich schau mal, dass ich sie für eine der nächsten versionen weg bekomme.
