### ISSUE TITLE
Bunkersilo verdichten

### ISSUE THREAD

**Issue by DonBolli** [Courseplay/courseplay#6546]
Hello

Somehow this doesn't work for me. My Course is follwing the instructions in this [Document](https://github.com/Courseplay/courseplay/files/679279/setup_mode10_course.pdf). It drives the first row perfect, but at the end, instead of driving back, it tries to turn.

Map: Multimap
Place: BGA Bunkersilo, from Field 10, on the left side.

**Comment by Tensuko** [comment]
Read existing Issues, there is being worked on.
