### ISSUE TITLE
Mod hangs when loading fields

### ISSUE THREAD

**Issue by marek1505** [Courseplay/courseplay#6548]
Yesterday I downloaded the mod's courseplay for the first time and installed it right away in the mods folder, then I started the game save on which I have over 60h and suddenly the game crashed (while loading the fields), I couldn't even press alt + f4, the only thing that helped was logging out of the system . I restarted the game on the same map without any other mods except courspley and it was possible to play normally, I checked my save again later with all mods and read that it might help to turn off the automatic loading of fields so when the game loaded quickly I clicked Esc and it worked, but when I tried to press Tab to get into the tractor quickly, so I couldn't try to approach it and press E, but it was also impossible for that tractor had bugged textures and no tires. Please help

Log.txt: https://github.com/Courseplay/courseplay/files/5740858/log.txt
Screenshot: https://user-images.githubusercontent.com/76574195/103113902-fb2e8e80-465c-11eb-91ff-611e0ff1c9e2.png

**Comment by Tensuko** [comment]
First at all, you should read your own logfile and see all the Errors your got in your mods.

Then, there is one rule: only one mod map in mods folder.

The Reason why your game stops loading is this:
2020-12-25 02:56 Error: Running LUA method 'onSaveStartComplete'.
2020-12-25 02:56 dataS/scripts/vehicles/specializations/Baler.lua(340) : attempt to get length of field 'bales' (a nil value)

And when you download CP, only from here:
https://github.com/Courseplay/courseplay/releases
Download the .zip and place it in mods folder, nothing more, no rename or anything.

**Comment by marek1505** [comment]
I've deleted all the other maps except the one I'm using on this save and it's all working, thank you for your quick reply
