### ISSUE TITLE
mismatch with the convoy distance and the  real distance on 2 combine ,and  pipe problem

### ISSUE THREAD

**Issue by magicmana** [Courseplay/courseplay#6554]
i made a video  
https://youtu.be/T52r_NIb9tE
  have a mismatch of 100m  less   to  the convoy  value and the real  distance. and    combine with a long pipe , and some time  have "battle" of  pipe   when  the two combine are near   the second consider the first like a  trailer.

**Comment by Tensuko** [comment]
duplicate #6011
