### ISSUE TITLE
Rubicon 9000 einklappen

### ISSUE THREAD

**Issue by WoodyLetsCode** [Courseplay/courseplay#6556]
Hallo,
kannst du machen, dass der Rubicon 9000 sich beim Wenden einklappt. Der ist so groß und bleibt überall hängen.
![grafik](https://user-images.githubusercontent.com/27882680/103157822-6e4c1800-47b7-11eb-8a52-714ff8968505.png)

**Comment by Tensuko** [comment]
Das ist ein generelles Problem beim turn und hat nicht direkt etwas mit der Rubicon zu tun.
Wird in einem anderen Issue bereits behandelt.
