### ISSUE TITLE
Slowing down for traffic Problem

### ISSUE THREAD

**Issue by WoodyLetsCode** [Courseplay/courseplay#6557]
Hallo,
hier kommt immer slowing down for traffic:
![grafik](https://user-images.githubusercontent.com/27882680/103157874-ec102380-47b7-11eb-8400-eee02f026dc5.png)
Die berühren sich aber gar nicht.
Die werden bloß unnötig langsam.

**Comment by Tensuko** [comment]
Warum fahren 2 Rubicon hintereinander auf dem gleichen Kurs ?
Und das problem ist auch hier die Rubicon, weil die Colli von GIANTS zu groß ist.

**Comment by WoodyLetsCode** [comment]
Einmal mit Planzenschutz und einmal mit Dünger.
Könnt ihr die Colli im Mod anpassen? 😄

**Comment by Tensuko** [comment]
Das ist kein Mod das ist ein GIANTS Fahrzeug....

**Comment by WoodyLetsCode** [comment]
Das ist mir schon klar. Ich meine ob sich da in Courseplay was machen lässt?

**Comment by Tensuko** [comment]
Nein, wenn wir den Trafficcheck da ausstellen gibts wieder Probleme mit anderen Fahrzeugen und Kollisionen, es liegt halt an der Feldspritze und das Problem existiert seit beginn des LS19.
Du kannst höchstes die Geräte in einem größeren Abstand voneinander starten lassen, dann begegnen die sich gar nicht erst.

**Comment by WoodyLetsCode** [comment]
Wenn ihr mal Lust habt, könnt ihr ja eine Option hinzufügen, dass man das gegebenfalls für Fahrzeuge ausschalten kann. :-)


Am 27.12.2020 13:28 schrieb Tensuko <notifications@github.com>:
Nein, wenn wir den Trafficcheck da ausstellen gibts wieder Probleme mit anderen Fahrzeugen und Kollisionen, es liegt halt an der Feldspritze und das Problem existiert seit beginn des LS19.

Du kannst höchstes die Geräte in einem größeren Abstand voneinander starten lassen, dann begegnen die sich gar nicht erst.
