### ISSUE TITLE
I can't select curseplay to create a game

### ISSUE THREAD

**Issue by fede633** [Courseplay/courseplay#6558]
**this text is made with a translator**

I have the problem that the game recognizes courseplay but does not appear in the start menu.
I attach images below

![explicacion curse](https://user-images.githubusercontent.com/76633559/103161059-465eb380-47bb-11eb-9611-4c025c3ae424.png)

in the mod menu appears the mod

![explicacion curse 2](https://user-images.githubusercontent.com/76633559/103161080-b836fd00-47bb-11eb-9340-88953f39ed73.png)

but not in this section

**I clarify that this began to happen to me a short time ago.
before I could use the mod perfectly**

**Comment by Tensuko** [comment]
First at all, you didnt post a logfile.
From your pic I can already see, that you must have several cp versions in your modsfolder.
Delete ALL cp Mods from your mods folder and ONLY download the .zip from here https://github.com/Courseplay/courseplay/releases and all you do is place this .zip file in your mods folder. No unzipping, rezipping or rename!

**Comment by 60erjonny** [comment]
i there
Download CP only here from the Git Hub page.
Delete all files in the mod folder that have to do with CP.
Then add the new CP file to the mod folder.
Reload the game ...

**Comment by fede633** [comment]
I have solved it!
my problem was
I downloaded it several times then my pc named them as:
FS19_Courseplay (1) .... or 2 or 3 etc
just deleting that number from the file solves
