### ISSUE TITLE
[Suggestion] mode2/3 follow to the end of the row

### ISSUE THREAD

**Issue by djnekkid** [Courseplay/courseplay#6560]
Hello there you awesome devs!

I've been playing alot of FS19/CP6 this xmas, and the mode3 works near flawless now. And when it doesnt, it usually my fault for setting up the course in a dumb way.

However, I got a suggetion:
When a harvester have the 'Stop during unload' option 'disabled' the cart follows the harvester until the harvester is empty, and then stops in the 'middle of the field'.
Would it be possible to add a 2nd option 'Disabled until end of row'. Where the cart follows the harvester until the end of the row, even if the harvester is empty?

Cheers, DJ

**Comment by Gibbanator** [comment]
where is that "Stop during unload option at? under settings? can't find it at all

**Comment by djnekkid** [comment]
> where is that "Stop during unload option at? under settings? can't find it at all

on the combine:
![image](https://user-images.githubusercontent.com/65364380/103174227-b2dfbe00-4860-11eb-9ce0-521320b5f1da.png)

**Comment by Tensuko** [comment]
Basically we should stay under the pipe untill the end of the row without any extra setting, not sure why it is not always working, maybe the flow of fruit is to low ? I am not sure.

**Comment by djnekkid** [comment]
@Tensuko i dont think ive ever seen that happen before.
The harvester is a (modded, on modhub) JD 790 with 18meter/60feet header (not on modhub), and on soybeans. So the flow should be enough?

**Comment by pvaiko** [comment]
@djnekkid thanks for the positive feedback, we really need it :) 

What would be the purpose of following the harvester to the end of the row?

**Comment by TobiHH78** [comment]
That would be helpful for larger fields. If the combine is empty when he starts the row where the pipe is in the fruit, than the chance is bigger that he finishes that row before he get`s full again. And he can get unloadad again the next row when the pipe is not in the fruit anymore.

**Comment by djnekkid** [comment]
@pvaiko : i know how it can be to work on stuff, and while you usually do good work, everybody and their grandma makes demands ;)

The purpose is probably more a plural then a single one:
1. The cart will be fuller, and possibly/probably (depending on sizes) be fuller then its "drive back" threshold.
2. The cart wont stop in the middle of a field, and probbly be in the way of something else
3. The cart probably needs less path calculations as it will be of a fuller state more ofen, and back to point 1.

Here is a picture
![image](https://user-images.githubusercontent.com/65364380/103213505-2ab7f200-490e-11eb-9ec7-0f0c766f9cdd.png)

**Comment by rohne83** [comment]
Don't think that would make sense. If the overloader is always following the combine until the end of the row (receiving just a few liters most of the time), it cannot serve other combines which got full in the meantime and need to unload more urgently than your already emptied combine.
You will have much less situations where leading combine has fruit on both sides if you are using lands or spiral pattern which are much more suitable for active unloading combines than up/down. With spiral pattern the pipe will always be free. And for lands, I have an eye on my combines, and use the button to call unloader manually when I see leading combine is approaching end of the land. That way you don't have problems with combines getting full in a new row.

**Comment by djnekkid** [comment]
@rohne83 :
im not sure how "aware" the different vehicles are of eachother, but there could be some 'setting', if its on the last x% (perhaps 25% default?) part of the row, and it can be released if another combine needs unloading above a certain %. Say you have set the cart to:
Start: 50%
Drive on: 90%
Start while unloading: 80%

And i ment this as an option, not default behavior.

**Comment by pvaiko** [comment]
@djnekkid thanks, I see now what you mean.

The combine **does** know a lot, for instance, how long each row is, when it will be full at the current fill rate and also if the pipe will be in the fruit at any waypoint, and so on, and the unloader and the combine talk to each other, so if we can come up with something useful, it should not be a problem to implement. 

Currently the unloader stops when the combine is empty (looks like they do get empty at least for a moment even if they keep harvesting). We can change this to stay with the combine as long as it is discharging (could be an advanced setting). Question is, when or where should the unloader stop following the combine.

**Comment by djnekkid** [comment]
"Question is, when or where should the unloader stop following the combine"

Somewhere "safe", a couple of "lenghts" from the end of the row?
What's a length? Combine length, header width, cart+puller length? Something like that.

That might be a good place to stop either way probably, as every so often I have to "save" a combine/cart at the end of a row, especially if the row isn't on a "proper" 0/90/180/270 degree heading.

**Comment by pvaiko** [comment]
>  every so often I have to "save" a combine/cart at the end of a row, especially if the row isn't on a "proper" 0/90/180/270 degree heading.

There's a fix for that (and many others) coming on the Mode2 branch.

**Comment by n4396t** [comment]
I think what the OP is saying is that he starts a row with the pipe out of the fruit, by the time he unloads into the cart he is just about ready to turn onto a new row with the pipe in the fruit.  At this point the following cart stops either because the combine is empty or the pipe has been retracted close to the end of the row and the cart just waits there.  By the time the combine gets to the other end and is ready to start another new row the combine is nearly full again, after the turn the combine, with the pipe out of the fruit is ready to unload but the cart is all the way at the other end of the field. Because of this the combine has to stop and wait for the cart to travel all the way from the other end of the field.
 I think what is needed is a way for the cart to follow behind the combine after it pulls in behind it.  That way the cart is close to the combine all the time hence less stopping for the harvester
