### ISSUE TITLE
Combine Glitching out 

### ISSUE THREAD

**Issue by Rman88** [Courseplay/courseplay#6561]
Hey, i ran into this issue with the Nova 330 combine. Now i will say it only affects the nova 330 as i was using the bison with no major issues. Granted i haven't tested the other combines due to playing on a limited budget and not wanting to mess up my farm. still it seems like this is a bit of a game breaking bug for me. 

Long story short, the combine glitches out when it reaches the end or beginning of the row if it was doing a headland. It ends up puling out of the feild or turning to soon into my crops. Only to then stop and idle as it claims that the hopper is full. And i wont lie i am purely stumped on this. i don't know what could be causing the issue. as like i said before i was using the bison and the same exact pattern without any issue. 
![bug](https://user-images.githubusercontent.com/33971169/103175203-d1789180-482d-11eb-9503-d3c26c533b9b.png)
Any idea how to fix this?

Just a note it is not an issue with headlands. As they are the only thing that works right now.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki
https://github.com/Courseplay/courseplay/releases

**Comment by Rman88** [comment]
Ehh, you going to help me or what? as i don't know how the wiki or release notes will help me fix this Glitch. as i clearly stated that what i did was no different from what i did with another combine. As it worked fine with the Bison Super Z056. Only to now run into this issue with the with the Nova 330. Hell i even tested the headers as both the Corn Champion 5R and Helianthus 5700 both faced the same issue. 

The issue clearly as the image shows revolves around course play thinking that the harvester is Full. As the image clearly shows a pop up that the work tool needs to be unloaded. Even thou the harvester is at 0% full. I don't really know how i can be more clear about the glitch then this. 

Likewise i have no idea where the log file is. Their is no setting to create a log file nor did course play suffer a fatal error. Likewise this is not an issue with me messing up course generation. As i got it to work before without any issue. As going from one combine to the next shouldn't cause any problems as they are essentially the same machine. 

So please give me a real answer or assistance rather then linking me to two very unhelpful things. as i don't even know how the patch notes could help me in this situation.

**Comment by Tensuko** [comment]
Why I have to help you read whats written there ?
Wiki Page is the most helpful page that we have!
It will answer some of your questions and will help us to find whats wrong!

**Comment by Rman88** [comment]
i told you what is wrong....the combine is running into the issue where it thinks its Full so it stops and waits to be unloaded. even thou it is empty. That is clearly what the image shows.

**Comment by Tensuko** [comment]
Your CP Version is outdated -> Wiki tells you to update first, I even gave you a link to the newest Version
You didn't post a logfile -> Wiki tells you where to find and how to post the logfile

**Comment by Rman88** [comment]
you know your really not that good at this are you? Tech support goes this is pretty poor and unhelpful. Most of which you are implying that i should "fix it myself". And while i will admit i didn't have it updated. Granted most mods don't update on a weekly basis so it can't really be helped. You should have just opened up and said. Hey try updating course play and get back to me. 

As this was very unhelpful and you never even addressed the issue. Just telling me to figure it out on my own.

**Comment by candymant** [comment]
If you dont like it play without courseplay en stop wining.
They do much more then they   shout do en of they refer to the wiki they have a reason. If they every time must do the same explenation then they were all stopt by now.
Do apriciate what they do for bring us a helpfull tool for the game.

**Comment by Tensuko** [comment]
> 
> 
> you know your really not that good at this are you? As tech support, this is pretty poor and unhelpful. Most of which you are implying that i should "fix it myself". And while i will admit i didn't have it updated. Granted most mods don't update on a weekly basis so it can't really be helped. You should have just opened up and said. Hey try updating course play and get back to me.
> 
> As this was very unhelpful and you never even addressed the issue. Just telling me to figure it out on my own.
> 
> And yes updating it seemed to fix the issue. Thou you really do need to work on your tech support skills.

I don't need to work on anything here, this is all in my free time, whil you enjoy playing I have to handle some Issues and other stuff, when I provide you all the information that you need to handle this and not even want to read what I post you there, I can't help it!
It might even happen that we even ask for a second logfile with debugchannels active! That all depends on the situation, but as written in Wiki, 1st step do an update and see if your Issue is already solved, as you see, it seems to be solved! So this was a waste of time for both of us, if you just would read the Wiki page, that we didn't wrote for nothing...

That got nothing to do with asking your to fix yourself, rather see if the Problem is already solved!
