### ISSUE TITLE
CourseGeneratorScreen:onCreate() Lua Callstack

### ISSUE THREAD

**Issue by Riarboba** [Courseplay/courseplay#6563]
Guten Tag,

ich wollte mit Courseplay ein Kurz generieren (Striegeln standart), leider zeigt er mir an, dass ich die Einstellung ändern soll aber leider bringt es nicht. 
[log.txt](https://github.com/Courseplay/courseplay/files/5744826/log.txt)

mfg

**Comment by Tensuko** [comment]
Kannst du mal ein Screenshot machen von den Einstellungen die du benutzt hast ?

**Comment by Riarboba** [comment]
![fsScreen_2020_12_27_19_12_43](https://user-images.githubusercontent.com/76658999/103177087-a3b83a80-4877-11eb-80cc-b4ef18f77bc1.png)
Das Zeigt er mir an, ich habe Feldarbeit gewählt.

**Comment by Tensuko** [comment]
Ja das Fenster kenne ich, aber das ist nicht das was ich sehen wollte... ich will die Settings sehen und gut wäre auch was von der Map zu sehen....

**Comment by Riarboba** [comment]
![Unbenannt](https://user-images.githubusercontent.com/76658999/103177724-3d361b00-487d-11eb-96e8-9be6177b0fe1.png)
![fsScreen_2020_12_27_19_49_27](https://user-images.githubusercontent.com/76658999/103177727-41facf00-487d-11eb-9748-5226d3eac3b7.png)
![fsScreen_2020_12_27_19_49_24](https://user-images.githubusercontent.com/76658999/103177732-47581980-487d-11eb-9d15-fafc1de013d3.png)
Ich habe nichts eingestellt, ich habe mir die letzte Version heruntergeladen und wollte es benutzen. Das ist die Oberbayern man, der generiert nur ein 1 Feld 34 glaube ich, vielleicht liegt das an der Map. Ich hoffe es ist dabei, was du sehen möchtest.

**Comment by Tensuko** [comment]
@Riarboba wir sprechen hier doch gerade von deinem Kursgenerator richtig ?
Also das du kein Kurs generieren konntest...
Wenn ich dich nun frage, welche Einstellungen du benutzt hast, könnte ich damit vlt die Einstellungen im Generator auf der rechten Seite meinen?
Nicht sämtliche CP Einstellungen, die mit dem Generator nichts zu tun haben und auch keine Fehlermeldung die mir ins Gesicht springt...
Nur für dich, hier ein Beispiel:
![fsScreen_2020_12_27_20_02_54](https://user-images.githubusercontent.com/27344744/103177896-98b4d880-487e-11eb-8e9c-c0504c3120db.png)

**Comment by Riarboba** [comment]
![fsScreen_2020_12_27_20_08_40](https://user-images.githubusercontent.com/76658999/103178002-72436d00-487f-11eb-95ae-aa71c5d0f89d.png)
Ja genau, hier sind meine Einstellungen. Ich hab es nicht richtig verstanden was genau du meintest.

**Comment by Tensuko** [comment]
Ok ich gehe mal davon aus, dass du bei Feld 34 unten getstanden hast.
Ich würde mal versuchen die Startposition auf aktuelle Fahrzeugposition zu stellen, normalerweise klappt das am besten.
Ansonsten, kannst du mir verraten welche Map das ist ? Dann probiere ich das auch mal.

**Comment by Riarboba** [comment]
![fsScreen_2020_12_27_20_20_52](https://user-images.githubusercontent.com/76658999/103178220-31e4ee80-4881-11eb-90f3-508b40646f00.png)
So ich stand auf dem Feld und ich habe Startposition auf aktuelle Fahrzeugposition gewählt leider kein Erfolg. Das ist Oberbayern Map (Modhub)

**Comment by 60erjonny** [comment]
Hallo
Habe mich mal auch daran "versucht" und gesehen, das die Karte noch ganz neu ( 23.12.2020 - 1.0.0.0 ) ist.
Nun für mich, ist die Map nicht spielbar, konnte nicht zwischenspeichern, warum auch immer.
Versuchte ebenfalls eine Kurs hier auf Feld 34 zu generieren.
Dabei viel mir auf, das der Feldrand nicht genau abgrenzt ist. Daher erkennt CP wohl Feld 35 mit.
Laut meine bescheidenen Test`s weiter, kann CP deswegen auch nur Kurse mit Vorgewende auf diesen erzeugen. 
Kaufte dann auch 36, wird aber von CP nicht als mein Feld erkannt ???
Weitere Versuche, habe ich dann doch gelassen.
Nun, ich denke daß da CP nicht die Ursache sein kann.
Hier sollte wohl, doch die Map nochmal überarbeitet werden...

mfg
jonny
![fsScreen_2020_12_28_11_28_08](https://user-images.githubusercontent.com/63659182/103208830-e4f52c80-4901-11eb-8ac5-28abe79bece6.png)

**Comment by Riarboba** [comment]
Hallo 60erJonny,

Also lag es nicht an CP, ich bedanke mich für eure Hilfe. Die Map läuft bei mir fehlerfrei, wahrscheinlich liegt das an Mods, die dir gefehlt haben. Den muss ich die Felder ohne CP arbeiten. noch mal Danke.

MFG

**Comment by 60erjonny** [comment]
Hallo @Riarboba 

Nein, musst du nicht...!
Fahr rund um das Feld 34 am Feldrand genau einen Kurs ein und diesen speicherst du ab.
Die Karte hat 95 Felder...? Benenne diesen Kures dann, mit Feld 96.
Wähle diessen Rund-Kurs bei der Feldgenerierung aus und erzeuge damit deinen Feldarbeitskurs.
Somit sollte für dieses Feld jetzt auch ein eigener Kurs entstehen.
Verfahre so auch mit anderen Feldern, wo es Probleme git.
Versuch es mal...
mfg
jonny

PPS.: Ja kann sein, das die Karte deswegen nicht bei mir fehlerfrei lauft...

**Comment by betrox007** [comment]
@Riarboba You Should try CP Custom field course, record the course along the edge of field where not detected as field by CP, then generated field course from recorded course, cause same case was happen to me at Green river 2019 map, for Field no 12, this field not recognized by CP, and this not CP Fault, but maybe some minor bug from map maker, so I'm tricking it with CP Custom field, just record the course around the edge of field then generated course from that recorded course.. it is simple.

thanks'

**Comment by Tensuko** [comment]
@60erjonny das geht viel einfacher.
Just as @betrox007 wrote, custom field.

@Riarboba mit dem ingame Mal tool das Gras zwischen den Feldern sauber ausmalen.
Stell dich auf das Feld und klicke auf Feldrandkurs berechnen, überscheibe die entsprechende Nummer und fertig.

Aber da muss ich mal wieder sagen, da hat der Mapper gepfuscht...

Kein CP Issue, mache hier zu.
