### ISSUE TITLE
Frage zu einem Error in der Log

### ISSUE THREAD

**Issue by Makaay1307** [Courseplay/courseplay#6564]
Hallo, ich hätte eine Frage 
Ich spiele im MP auf einen Server , sobald ich ein Fahrzeug kaufe und dann Courseplay aktiviere kommt folgender Fehler in der Log:

2020-12-27 19:04 Error: Running LUA method 'draw'.
2020-12-27 19:04 C:/Users/Chris/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/hud.lua:706: attempt to call method 'getName' (a nil value)

an meinen vorhandenen Fahrzeuge funktioniert alles tadellos, der Fehler kommt immer nur wenn ich ein Fahrzeug neu kaufe und dann CP aktivieren möchte. Es geht auch dann der Hud vom CP nicht auf.
Ich hoffe ich bekomme eine Antwort von Ihnen,
Als Anhang sende ich noch die ganze Log mit
mit freundlichen Grüßen , Chris

**Comment by Tensuko** [comment]
logfile ?

**Comment by Makaay1307** [comment]
[log.zip](https://github.com/Courseplay/courseplay/files/5745042/log.zip)

Sorry

**Comment by Tensuko** [comment]
Hattest du andere Fahrzeuge stehen die einen Kurs geladen haben ?

**Comment by Makaay1307** [comment]
Nein, habe ich mehrmals überprüft.
Der Fehler ist seitdem ich einen Claas Mega  Drescher verkauft habe und mir einen neuen Drescher gekauft habe. 
Seitdem tritt der Fehler bei jedem neuen Fahrzeugkauf auf .

**Comment by Tensuko** [comment]
Ist der neue Drescher ein Mod Drescher ?

**Comment by Makaay1307** [comment]
Nein, Standart Drescher.
Der Fehler kommt auch wenn ich mir einen Traktor oder Häcksler kaufen möchte

**Comment by Makaay1307** [comment]
Den Drescher , den ich verkauft habe war ein Mod Drescher, der Claas Maga, vielleicht hatte der noch einen Kurs geladen.
Das kann ich aber nicht mehr nachvollziehen. Mein Mitspieler hat übrigens den gleichen Mod Drescher, hat aber CP nicht in Gebrauch und auch keinen Kurs geladen.
Aber wie kann ich das Problem jetzt beheben ?

**Comment by Tensuko** [comment]
Versuch mal CP runter schemeißen, Server starten und speichern, CP wieder drauf.

**Comment by Makaay1307** [comment]
ok, ich versuche es und geb dann Bescheid

**Comment by Makaay1307** [comment]
Habe es nun so gemacht und jetzt funktioniert wieder alles wie es soll .
Log ist sauber und ich kann wieder in jedem neuen Fahrzeug CP aktivieren.
Danke für deine Hilfe, Thema kann geschlossen werden.

**Comment by Tensuko** [comment]
Ok super, wenn das noch mal auftreten sollte, bitte sag mal genau wie es zustand gekommen ist, dann müssen wir da mal schauen.
