### ISSUE TITLE
Courseplay Helper uses money -> Setting off - 6.03.00017

### ISSUE THREAD

**Issue by ElfVierzehn** [Courseplay/courseplay#6569]
Hey there,

I have a little issue with version 6.03.00017. After updating to this version (at least I didn't notice in a previous one) the combine driver uses money, although helper payment is disabled. There's no followme, ai vehicle extension, or similar mods installed that also uses helpers. Is there any mod conflict known? With only CP enabled it only uses 1€ once and afterward no more money it seems. 

Thanks a lot!

**Comment by Tensuko** [comment]
Better Contracts got a hidden function:
#6453
