### ISSUE TITLE
Kuhn Discolander XM52

### ISSUE THREAD

**Issue by Quintto** [Courseplay/courseplay#6570]
Hello,

I just tried using the Kuhn Discolander XD 52 with courseplay and found out that it would only work with mode 4 (seeding) 
a quick search on github showed that thats because back in october 2019 that was because even the giants worker wouldn't work without seed in the seeder part of the cultivator (#4357) 

But right now in the current version of the game the ingame worker does use the cultivator as a cultivator when there is no seed in the tank. so would it be possible to add this functionality in Courseplay?

**Comment by Tensuko** [comment]
I am not sure if this was working before, but you can use that tool on Mode4 and Mode6 (green button in this screenshot).
However, I am ofc on the newest State. Will push the next Release soon and then it should work just like on my screenshot.
![fsScreen_2020_12_28_17_37_50](https://user-images.githubusercontent.com/27344744/103229536-82b51f80-4933-11eb-9c37-b8a2df515e55.png)

Keep in mind that there are a few modded tractors out there that always requier some fillunit wich can cause similar problems like you got.
Give us a bit more time and it should working for you, or in case you familiar with github, download the branch, unzip the .zip and rezip the files inside the master folder and name it to FS19_Courseplay, then you should be rdy to go.
