### ISSUE TITLE
Courseplay with proseed

### ISSUE THREAD

**Issue by Andystrong8484** [Courseplay/courseplay#6571]
So, 

I use proseed for putting in the tramlines after sowing 

When the tractor running on cp is doing its ins and out it sometimes starts out at the edge and not where it should inside the outside run 

Any idea why this has changed since .00007 version?

Doesn't matter which drill is used either btw it all is the same regardless 

![fsScreen_2020_12_28_16_17_40](https://user-images.githubusercontent.com/75746655/103228395-a45cd980-4928-11eb-989f-fa188474f24e.png)

![fsScreen_2020_12_28_16_16_44](https://user-images.githubusercontent.com/75746655/103228390-a1fa7f80-4928-11eb-843b-eb2b31924a87.png)

**Comment by Tensuko** [comment]
What is the .7 Version ?
Logfile ?
Try to explain it in more detail what you want to do, I don't get it.

**Comment by Andystrong8484** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5748045/log.txt)

**Comment by Andystrong8484** [comment]
So

What is the .7 Version ? this was cp version 16.07 after this version it started to change. 

I am trying to get courseplay to set the tramlines in the crop using proseed 

As you can see in the image below the tramlines are within the outside tramline but the images at the top the tramline starts nearly at the edge of the field 

![fsScreen_2020_12_28_16_28_39](https://user-images.githubusercontent.com/75746655/103228996-0964ff00-492a-11eb-8d91-f700cc5e6075.png)

**Comment by Tensuko** [comment]
This is the Version: (Version: 6.03.00017) FS19_Courseplay
6.03.00017
If your refer now to (Version: 1.0.0.1) proSeed #5721 
I don't know if @stijnwop noticed this Issue.

**Comment by Tensuko** [comment]
I do some cleanup here...

**Comment by Andystrong8484** [comment]
Ah not so bad, only started after cp 6.03.0007 but thought it was just a positioning issue

**Comment by stijnwop** [comment]
You should be able to use ProSeed with CP.. as the only issue was the HUD not being displayed.

It's a matter of setup. Headlands is a manual operation and it's easier to do it afterwards.

**Comment by Andystrong8484** [comment]
Yea they work, but since going to the newer version of course play the hired worker is now starting the tramlines at the edge instead of inside the outside run this is what I'm meaning 

Another example... as you can see the centre of the field tramline runs are past the outside run...

Both options are used from headland run and centre being completed first 

![fsScreen_2020_12_09_20_49_47](https://user-images.githubusercontent.com/75746655/103232597-c4919600-4932-11eb-909a-355f02669280.png)
![fsScreen_2020_12_28_16_16_44](https://user-images.githubusercontent.com/75746655/103232645-ea1e9f80-4932-11eb-9f56-e608e878b993.png)

**Comment by Andystrong8484** [comment]
Also iv changed the lowering and raising tools to raise early and lower late as well

**Comment by Tensuko** [comment]
I also have no Idea what could have changed about this...

**Comment by Andystrong8484** [comment]
Yea same, but thought id let you know about it.

**Comment by Andystrong8484** [comment]
Downloaded the dev version of CP this morning for an experiment and so far it seems to be working properly with the helper lifting at the end row
![fsScreen_2020_12_29_11_19_36](https://user-images.githubusercontent.com/75746655/103280234-ca858680-49c7-11eb-8171-b70d9e1b4a8a.png)
![fsScreen_2020_12_29_11_19_38](https://user-images.githubusercontent.com/75746655/103280238-cf4a3a80-49c7-11eb-98e5-3584a07f4ea7.png)
![fsScreen_2020_12_29_11_19_49](https://user-images.githubusercontent.com/75746655/103280243-d1ac9480-49c7-11eb-9afd-22a7735a9398.png)
