### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by WillT7** [Courseplay/courseplay#6572]
[log.txt](https://github.com/Courseplay/courseplay/files/5748439/log.txt)
It may not be courseplay  related but any help would be appreciated.

**Comment by Tensuko** [comment]
(Version: 6.03.00012) FS19_Courseplay
-> https://github.com/Courseplay/courseplay/wiki
-> https://github.com/Courseplay/courseplay/releases
And more details are always welcome for the next time...
