### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by WillT7** [Courseplay/courseplay#6573]
Well i open my game and set off my course play courses 2 sprayers and 2 trucks when I get out the games freezes and this comes up it happens every time i have used the latest version of courseplay v6.07 

[log.txt](https://github.com/Courseplay/courseplay/files/5748613/log.txt)

**Comment by schwiti6190** [comment]
"Error: C:/Users/12zea/OneDrive/Documents/My Games/FarmingSimulator2019/mods/FS19_AIVehicleExtensionV2/register.lua:8: attempt to index field 'specializations' (a nil value)"
Could you please test this again with the most recent cp version an without this mode above, as this one produces an error :)

**Comment by WillT7** [comment]
Hello, yes  I did remove that mod however the same thing still happens. 
[log.txt](https://github.com/Courseplay/courseplay/files/5748723/log.txt)

**Comment by schwiti6190** [comment]
@WillT7 Hi, I would need your help identifying the problem more closely. Could you do a test without this mod: " (Version: 1.4.0.0) FS19_REA" as this one seems to cause errors in combination with cp. If this mod is the problem and if your up to the task, then would it be nice for you to do some tests to determine the excat setup, that causes the errors.

**Comment by WillT7** [comment]
Hello, I did find the cause the problem was the "towing chain" mod once this was removed it worked fine.
