### ISSUE TITLE
precision farming helper

### ISSUE THREAD

**Issue by andycr13** [Courseplay/courseplay#6576]
when using precision farming you can track the cost of helper for each field. courseplay helper is not showing up as a helper being used nor the cost. hopefully this can benefit the mod for the future. thanks love the mod

**Comment by Tensuko** [comment]
You talk about this ?
![fsScreen_2021_02_01_19_04_52](https://user-images.githubusercontent.com/27344744/106499159-869f0900-64c0-11eb-9bd2-930b5f82b3de.png)

**Comment by andycr13** [comment]
Yes when I was using courseplay that would stay at 0

**Comment by Tensuko** [comment]
CP is running and it is going up.
Maybe DLC Update fixed it.
So basically it works, can't do more then that.
