### ISSUE TITLE
can someone expain this to me

### ISSUE THREAD

**Issue by farming2020** [Courseplay/courseplay#6577]
> `[](url)`
![20201229125855_1](https://user-images.githubusercontent.com/65118090/103285381-e98b1500-49d5-11eb-90aa-d73c42813a52.jpg) i getting this everytime i using courseplay when using the unload combine with trailer

**Comment by Tensuko** [comment]
just a harmless print, will be removed soon...

**Comment by farming2020** [comment]
ok thank you
