### ISSUE TITLE
Courseplay multi combine with PW8 pickup 

### ISSUE THREAD

**Issue by mudball66** [Courseplay/courseplay#6579]
Hey I am trying to run two combines with pickup headers behind the swather. The swather header is 14.4M so I set courseplay to that width on the combines with two implements. So it puts the line between the first two swaths. How ever when I set combine #1 one left of the line he only goes left of the line far enough to the edge of the pickup. I assume cause he is still reading the pickup width is only 5.5M instead of 14.4 like I set CP to.. thanks hope someone can help me!

**Comment by Tensuko** [comment]
You have a multi tool course with Tool and each is 14.4 so the course is generated with a width of 14.4m.
That course is loaded on all 4 Drivers (2x swather 2x pickup).
To have the pickup run exactly behind the swather, you got to change the work width of the pickups to 14.4m in the HUD.
Ofc you have to use the actual CP Version for this to work.

**Comment by mudball66** [comment]
I use the official CP from the download site. And I change the implement width to 14.4M when in course generation HUD to match the swather width. So when I set combine#1 to 1 left. It should be on the left swath but the combine only goes over a couple meters. So it lines the edge of the pickup up witb the generated CP line

**Comment by mudball66** [comment]
You meant change the working width of the pickups to 14.4M in the HUD in the courseplay course generator correct? Thanks

**Comment by Tensuko** [comment]
No not in course generator... in the HUD.
![fsScreen_2020_12_29_16_38_21](https://user-images.githubusercontent.com/27344744/103295488-58776680-49f4-11eb-90b9-7a0bed8df66b.png)

**Comment by Tensuko** [comment]
1 Course:
Tools on course: 2
work width 14.4m
1 swath left, 1 swath right
1 pickup left, 1 pickup right
all on the exact same course BUT to allign the pickup to swather, change the work width in the HUD to the same as the swater.
Activate convoy for all 4 drivers and you are fine.

**Comment by mudball66** [comment]
Ok I tried doing that as well changing that width to 14.4 M and still doesn’t seem to work. I am wondering if maybe my CP needs updating I haven’t done it for a couple months now

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/releases

**Comment by mudball66** [comment]
Ok I appreciate your help. I am assuming I am just doing something stupid that’s wrong.

**Comment by Tensuko** [comment]
Well, I don't know wich version you have for now.
But in any case, remove all courseplay stuff from mods folder, download the .zip file from the release side (currently 6.03.00017) and place this in your mods folder, nothing more and you got the newest Version.

**Comment by mudball66** [comment]
You bet. I am hoping that fixes it, I like the idea of swathing and using pickup headers. But it’s aggravating me.using the pickup at 14.4m works fine witb just one combine

**Comment by Tensuko** [comment]
Just tested it and well there seems to be a bug somewhere, will have a closer look.

**Comment by Tensuko** [comment]
There is just an autocalculate button bug.
Load course, set work width to 14.4m, choose the side and start and it works fine:
![fsScreen_2020_12_29_18_21_38](https://user-images.githubusercontent.com/27344744/103301912-b448ec00-4a02-11eb-8654-2470843e0fcf.png)

**Comment by mudball66** [comment]
What do you mean a auto calculate button bug? And do you mean load the course from the swather to the combines? I am only using one swather and two combines though. Do I need to run two swathers as well? You said you tested it and there seems to be a bug. The bug in the auto calculate?

**Comment by Tensuko** [comment]
The button next work the + and - will do some weird thing... ignore it...
What kind of swather do you have, if you use 2 pickups ?!
My swather will always create one line, if you don't use 2 swather, why do you use 2 pickups and why do you want and offset ? I don't get it....
Screenshots of your setup might help.

**Comment by mudball66** [comment]
What do you mean a auto calculate button bug? And do you mean load the course from the swather to the combines? I am only using one swather and two combines though. Do I need to run two swathers as well? You said your

**Comment by mudball66** [comment]
Well I live in Canada so I want to farm like we do here. So I am we going to Swath canola ahead of the combines then use the pickups to combine it cause that’s what we do on our farm. I have the Macdon m1170 mod and the honeybee swather header for it

**Comment by Tensuko** [comment]
I would still need to see your setup I can't imagine how you try to get it working ingame.
Or what you basically want to do.

**Comment by mudball66** [comment]
So yes my swather leave one straight line but I want to use it combines. So essentially one pass with the combines will be two passes for the swather

**Comment by mudball66** [comment]
I will try to get a picture tonight too you

**Comment by Tensuko** [comment]
Now it gets more clear...
1 swather do 2 up/down rows and those 2 rows should be picked up by 2 combines (wich will be one line with offset lef/right)

**Comment by mudball66** [comment]
Yes sir that’s my goal. I have done it before with other things like cutting and baling hay on the game. I will use one mower and make it into wind rows and then two balers to get it bailed up quick when it’s dry. So essentially same thing witb this. Which should theoretically work because the swather is 14.4m. So if I set the combine courseplay to 14.4m and set it to 2 machines. Then that should set the CP line. Between the two swather rows. And the “left” combine should take the swather pass to the left of the CP line and the “right” combine should take the right swather pass.. in my head anyway

**Comment by mudball66** [comment]
https://mega.nz/folder/kcdykaqS#cZ0SRhb8Me81sFHNqqhLIA

**Comment by mudball66** [comment]
This is the mods I am using for the swather pickup. And crop extension. Maybe you can put it on your game and see what I mean kinda?

**Comment by Tensuko** [comment]
ok uhm let me try to explain this, I think I get it now.
See this picture:
![2CourseSetup](https://user-images.githubusercontent.com/27344744/103307384-2a078480-4a10-11eb-9232-5564a5f4aecb.png)
The top should be the workflow if your swath who is doing it up and down rows.
This have to be a simple course with a work width of 14.4m.
Now to your pick up harvester.
Those rly need a 2nd course, the setting for it would be 14.4m but 2 tools on the same course (so it get to 28.8m, the total of 2 up/down rows if your swather).
If you load that course for your 2 pick ups, you are right, they normaly do would run to close to the line now, but when you change the work width on the HUD (the one I marked red some posts ago) to 14.4m you are in the same line as the 2 swather.

There might be 2 problems:
- the course won't overlap how you would like it (a manual offset could help).
- if your pickup are 2 fast, they will catch your swather, the convoy function only works on the same course.

I hope I could help you with this after I finaly got what you try to do :) never heard of this way, rly interesting!

**Comment by mudball66** [comment]
Yes you are correct with what I am saying now. The first problem you stated about not lining up correctly I can’t comment on that yet cause I haven’t been able to run the combines yet. The second the combines go 6mph with the pickup header And the swather travels at 14 so shouldn’t be a issue. And I agree it should work. I tried changing my width in the HUD to 14.4 on the combines to match the swather width and when I generate the course it places the line for the CP correctly between the two swather rows so it mimickes 28.8m like you said with two combines. But then when I start combines it goes left of the line but only 5.5m roughly. It acts like it doesn’t recognize that it’s set to 14.4m per machine and thinks it is only 5.5m... I am wondering if updating my courseplay will help

**Comment by mudball66** [comment]
I sure appreciate your patience trying to help me

**Comment by Tensuko** [comment]
Well ofc you need the actual version.
When your Tools get to close tp the middle line.
Change the work width in the HUD, not the course generator setting.
You got your course with 14.4m for 2 tools, more you don't have to do there.
When your driver don't listen to your setting in your HUD, you need to update your CP Version.
https://github.com/Courseplay/courseplay/releases

**Comment by Tensuko** [comment]
@mudball66 
does it work like you expect it ? I would like to close this Issue then.

**Comment by mudball66** [comment]
Hey! Sorry. Yes it does! I updated to the current version of CP and it works flawlessly now. Thanks so much for your help
