### ISSUE TITLE
Speed Issue with JD 4940 Spreader

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#6581]
Hello I’m on the very latest version and I’m running the John Deere 4940 spreading lime well the speeds start at 15 and then will drop to 6mph also doing these speeds across to fill up too. If I stop the driver and start again it will go to 15 and then eventually back to 6

**Comment by Tensuko** [comment]
logfile ?
What exact spreader is this ?

**Comment by matty2123** [comment]
https://www.farming-simulator.com/mod.php?lang=en&country=it&mod_id=179136&title=fs2019 This is the spreader with a drybox

**Comment by matty2123** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5751470/log.txt)

**Comment by Tensuko** [comment]
#6374
and I don't have any Issue with it
![fsScreen_2020_12_29_18_08_22](https://user-images.githubusercontent.com/27344744/103301184-1274cf80-4a01-11eb-870e-a090194c9c17.png)

**Comment by matty2123** [comment]
Can you report back with spreading lime?

**Comment by matty2123** [comment]
Could it be precision farming? If the auto is activated on the spreader?

**Comment by Tensuko** [comment]
No Idea. You have to try it out...

**Comment by betrox007** [comment]
you not using season geo mod?, try use one geo mod

**Comment by Tensuko** [comment]
@betrox007 and then ?
What does this have to do with the Issue here ?

**Comment by betrox007** [comment]
@Tensuko by mistake i figure out this case, a few day's ago i create new save game and i'm forget to delete Geo mod so my game load 3 geo Mod in same time, and the case when doing field work CP only run with the speed bellow 10 km/h, and there's no error messages on log, after delete the other two geo mod from mod folder, and restart game, cp driver return to normal, i didn't try yet how if only season mod to load without geo mod.. maybe i will try it when return to my computer

**Comment by NicholasSoares** [comment]
![fsScreen_2020_12_24_00_01_13](https://user-images.githubusercontent.com/42093631/103363252-63d09d80-4a99-11eb-93ba-f5a7768d3506.png)
You need to rise the field work speed from 24 to 35 that will fix the low working speed, also rise turn and back speed to something like 20 at least, running 3 of these for 49 hours each without issues, also beside that the DEF level is only 5 on this mod and will cause engine shutdown on long run (need to be changed to 29.5)

**Comment by Tensuko** [comment]
Well as I tried it works fine with and must be some Mod Conflict or something. Cant do much here.
