### ISSUE TITLE
Courseplay v 6.03.00016. Lohnkosten Helfer

### ISSUE THREAD

**Issue by xXSyyDXx** [Courseplay/courseplay#6582]
Hallo zusammen,

ich habe das Problem das bei mir die Lohnkosten des Helfers trotz Deaktivierung berechnet werden. 

In der XML steht ebenfalls das die Helferkosten auf false gestellt sind.

Kann ich da noch was machen das die Kosten nicht mehr abgezogen werden? 

Spiele aktuell auf Erlengrat.

**Comment by Tensuko** [comment]
Erst suchen, dann neues Issue aufmachen...
#6453

**Comment by xXSyyDXx** [comment]
Sorry da haben Sie Recht.

Danke für die schnelle Hilfe.

Tensuko <notifications@github.com> schrieb am Di., 29. Dez. 2020, 17:57:
