### ISSUE TITLE
Gülle lager

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#6586]
Moin
Ich habe den Mod Güllelager hinzugefügt, wenn ich jetzt über Courseplay das Lager leerfahren möchte passiert folgendes: die Strecke ist frei und der Abfahrer bleibt vor den Lager stehen und meldet Abfahrer steckt im Verkehr fest
![Lager](https://user-images.githubusercontent.com/47453761/103338482-db450380-4a7e-11eb-9a4a-a8415bb19bd9.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5753464/log.txt)

**Comment by Tensuko** [comment]
Du hast einiges an Errors in deiner log, die solltest du erst mal bereinigen.

Welches Güllelager genau ist das ?

**Comment by Hendirk** [comment]
Ich habe folgendes Güllelager

FS19_SlurryTradingSystem
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=129174&title=fs2019

**Comment by Tensuko** [comment]
Ok muss ich mir später anschauen.

**Comment by Tensuko** [comment]
Dürfte am Sprayer Arm liegen #6685
