### ISSUE TITLE
Silo Verdichten Modus 10 Courseplay

### ISSUE THREAD

**Issue by Partyborner** [Courseplay/courseplay#6587]
Hallo , seit 3 Tagen habe ich folgendes Problem, der Traktor beim Verdichten fährt nicht mehr auf die Parkposition wenn der Ablader mit Autodrive zum Silo fährt.
Beide halten nicht an.
Er hält nur noch an wenn ich Manuell dort hin fahre "Vom Spieler Kontrolliert".
Gibt es dazu schon erkenntnisse? 
Logfile : https://pastebin.com/xA5qAwBQ

Mfg Partyborner

**Comment by Tensuko** [comment]
Was ist mit der Einstellung anhalten für Courseplay/Autodrive ? schon versucht ?

**Comment by Crinouche** [comment]
I have the same problem.

**Comment by Tensuko** [comment]
> 
> 
> I have the same problem.

If you have the exact same problem, then here is the same question for you:
what about the setting stop for courseplay/autodrive ?

**Comment by Partyborner** [comment]
> Was ist mit der Einstellung anhalten für Courseplay/Autodrive ? schon versucht ?
Ja , kein Erfolg.

**Comment by Tensuko** [comment]
Ok dann müssen wir uns das anschauen.

**Comment by Gibbanator** [comment]
Just to add I am also having this problem. I posted in the AutoDrive bug area and was told issue is with CP. Tractor with Blade will go out of bunker in time if I set it for All and at 100m detection but will not stay at park area once the trailer starts to dump.

Can't leave it unattended for semi will run into tractor still. I get no errors on the command prompt when the semi runs into the tractor. 
not sure what file to load here.

**Comment by Mannie313** [comment]
Ich spiel zur zeit deswegen mit der version 06.02.00079 von CP da hält AD automisch an.

MFG Mannie313

**Comment by Gibbanator** [comment]
Was thinking this was corrected with what I read on 21 and 22 updates but still the same.. Im afraid to go to 00079 because there were other issues not corrected there that devs have corrected with newer versions..

**Comment by Tensuko** [comment]
Well, dont be afraid to use CP as unloader, it doesnt hurt :)

**Comment by Tom20214** [comment]
@Tensuko  nur CP erkennt die Rückwärtslinien von AD als Vorwärtslinien und fährt Vorwärts in das Silo statt Rückwärts.

**Comment by Tom20214** [comment]
Kann geschlossen werden funktioniert in der neusten Version wieder.

**Comment by Tensuko** [comment]
Super.
