### ISSUE TITLE
[Bug] Mode5 Am letzten Wegpunkt o Trigger Warten einstellung

### ISSUE THREAD

**Issue by Tom20214** [Courseplay/courseplay#6588]
![InkedfsScreen_2020_12_30_14_42_49_LI](https://user-images.githubusercontent.com/50717293/103355329-42c67780-4aae-11eb-8767-6adf2b902301.jpg)

[log.txt](https://github.com/Courseplay/courseplay/files/5754378/log.txt)

Moin Tensuko in der neuen CP Version fehlt der Button Am letzten Wegpunkt o Trigger Warten im modus 5.

**Comment by Tensuko** [comment]
Das ist kein Bug, das ist so gewollt.
Er wird immer am letzten Wegpunkt warten in diesem Modus.

**Comment by Tom20214** [comment]
Es ging darum wenn er im kreis fahren soll das er nicht am letzen Wegpunkt hält.

**Comment by Tensuko** [comment]
Wofür braucht man das ?

**Comment by Tom20214** [comment]
zum Bunkersilo verdichten

**Comment by Tensuko** [comment]
Dafür ist Modus 10 da und der hat auch ein Update gekrigt dafür.
http://courseplay.github.io/courseplay/en/manual/index.html#driveMode10
http://courseplay.github.io/courseplay/en/manual/index.html#hud_levelingSettings
