### ISSUE TITLE
[Suggestion] CP  Graben Erkennung 

### ISSUE THREAD

**Issue by Tom20214** [Courseplay/courseplay#6594]
Ist es möglich das CP vor Gräben oder Flüsse anhält wie im ls17?

**Comment by Tensuko** [comment]
Sowas gab es nie und wird es auch nicht geben.
Der Pathfinder bleibt bereits auf dem Feld und was du eher meinst ist die Anpassung an turns, dass diese nicht außerhalb des Feldes gemacht werden -> Vorgewende vergrößern, alles weitere kommt vlt später.
