### ISSUE TITLE
Happy New Year!

### ISSUE THREAD

**Issue by pvaiko** [Courseplay/courseplay#6596]
Happy New Year  to all Courseplay users, thank you for your support and patience!

Many thanks for our translators and to the few who helped us fixing bugs, remember, the most valuable contribution is a pull request!

Last, but not least, very special thanks to those wo chose to donate us to keep up our motivation.

Courseplay Dev Team

**Comment by Misamangame** [comment]
Happy New Year to all developers!!! Thank you for still supporting this mode and adding new and improve features all the time.

**Comment by knoxville73** [comment]
Happy New Year to the great and most important team for this game

**Comment by polosubtil** [comment]
Happy new year everyone 
And thank you so much for your work, you rock guys !!!!!!!!!
