### ISSUE TITLE
Speicherort der Kurse auf einem dedi server

### ISSUE THREAD

**Issue by firefightgamer13** [Courseplay/courseplay#6597]
hi
Ich würde gerne wissen wo der Speicherort der Kurse die man auf einem Dedi-Server erstellt sind, um diese aauch im Singleplayer nutzen zu können. Ich habe diese leider nicht finden können. In der savegame datei vom server ist leider auch nichts zu finden.

**Comment by Tensuko** [comment]
Genau an der gleichen Stelle wie im SP:
...\FarmingSimulator2019\CoursePlay_Courses
Oder anders gesagt, wo auch der mods Ordner liegt.
Man kommt da aber nur mit FTP Zugang ran.
