### ISSUE TITLE
Problem mit selbst erstelltem Multiplayer-Spiel

### ISSUE THREAD

**Issue by rellek010682** [Courseplay/courseplay#6598]
[Logs+savegame.zip](https://github.com/Courseplay/courseplay/files/5757405/Logs%2Bsavegame.zip)
Hallo.
Ich habe im selbst erstellten Multiplayer-Spiel das Problem, dass mir das CP-Hud nicht angezeigt wird. Beim Rechtsklick auf die Maus wird mir zwar der Mauszeiger angezeigt, aber das Hud wird nicht eingeblendet.
Spiele ich den gleichen Spielstand auf unserem Dedi-Server, funktioniert alles normal.
System: Mac
Karte: Felsbrunn
Mods im Ordner: NUR Courseplay v6.03.00019

Gibt es da ein Lösung, oder ist das ein neue Fehler?

**Comment by Tensuko** [comment]
Hast du das Savegame vom Server runter gezogen und dann gestartet oder ein neues Spiel gestartet ?

**Comment by rellek010682** [comment]
Beide Varianten: 1. Savegame als Multiplayer auf dem eigenen Rechner erstellt -> CP funktioniert nicht
                             2. Savegame vom Rechner auf den Server hochgeladen -> CP funktioniert sauber

**Comment by Tensuko** [comment]
Ok ich meinte zwar vom Server auf Rechenr und dann gestartet, aber ok wenn es neues savegame als MP nicht geht, muss ich mal gucken.

**Comment by rellek010682** [comment]
Das habe ich auch schon gemacht. Leider hatte ich da auch kein Erfolg.

**Comment by Tensuko** [comment]
Also ich hab eben mal gestartet und keine Probleme gehabt, HUD ist da.
[log.txt](https://github.com/Courseplay/courseplay/files/5757547/log.txt)

**Comment by rellek010682** [comment]
Oh. Dann  muss ich jetzt nochmal auf die Suche gehen.  Hattest du mit meinem Savegame gestartet?

**Comment by Tensuko** [comment]
Habs gefunden...
courseplaySettings.xml
Dein savegame: `<courseplayHud posX="1.000000" posY="0.000000" hudScale="1.000000" uiScale="1.000000">`
Mein savegame: `<courseplayHud posX="0.335938" posY="0.029861" hudScale="1.000000" uiScale="1.000000">`
Infotext:
`	NOTE 1: Do not change the uiScale Manually.
	NOTE 2: If you change the hudScale and you haven't changed the posX and posY manually,
			then you need to delete the posX and posY section to center the hud again.`

Das kommt normal nur vor, wenn man das savegame von einem dediserver runter lädt.
Ich hab das selbst erstellte savegame noch nicht gespeichert zum zu schauen, ob das auch passiert, wenn man selber ein MP aufmacht und nicht mit Dedi Server.

**Comment by rellek010682** [comment]
Habe grade mal meine courseplaySettings.xml  auf deine Werte verändert, und es funktioniert direkt. Danke schonmal für deine Hilfe. 
Wie kann sich sowas verstellen?
Ich hätte aber leider noch eine kurze Frage: Kann man in den erweiterten Einstellungen den Punkt "Klick zum einsteigen" irgendwie standardmässig auf "deaktiviert" stellen. Da ich auch mit AD spiele, ist es mir schon öfter passiert, dass ich beim Anklicken der Zielpunkte in ein anderes, benachbartes Fahrzeug gestiegen bin.

**Comment by Tensuko** [comment]
Das ist reine Servergeschichte und nein das stellen wir nicht auf normal deaktiviert nur wegen AD, wir haben das extra für AD mit verfügbar gemacht und da wir das ständig nutzen bleibt es bei default aktiviert. Stell es für dich halt um auf deaktiviert, dann ist es in deinem Save auch aus :)

**Comment by rellek010682** [comment]
Ok, danke.

Trotzdem nochmals Danke für deine Zeit für mein Anliegen.

Wünsche dir einen guten Rutsch ins neue Jahr.

Ich schließe dann mal hier ab.

**Comment by Tensuko** [comment]
Danke gleichfals :)
