### ISSUE TITLE
Sprayer impound problem

### ISSUE THREAD

**Issue by taz-87** [Courseplay/courseplay#6599]
For a while now, the maneuvers of the sprayers have left the field. The driver does not take into account the width of the tool which leads to collisions

Same thing with pathfinding and IA maneuver

![courseplay](https://user-images.githubusercontent.com/76821124/103420156-459c9780-4b96-11eb-96e1-b8f431c35b04.png)

**Comment by Tensuko** [comment]
Already got Issues for this, pls search for similar before open a new one...
