### ISSUE TITLE
Gülle lager

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#6600]
Moin
Was muss ich einstellen damit der Abfahrer die Gülle von beiden Ställen zum Güllelager fährt, Ich den Start am ersten Kuhstall gesetzt bin dann zum Güllelager gefahren und dann zum zweiten Stall dort weiter aufzufüllen, aber er hält beim zweiten nicht an, oder muss ich dort ein Wartepunkt setzen
![Gülle lager](https://user-images.githubusercontent.com/47453761/103420297-ca87b100-4b96-11eb-9b9e-6f4e0c0f063b.png)

**Comment by Tensuko** [comment]
Du kannst nur von einer Station zur Zeit auffüllen.
