### ISSUE TITLE
Slowing Down  cause Traffic 

### ISSUE THREAD

**Issue by SplinterCurty** [Courseplay/courseplay#6601]
![grafik](https://user-images.githubusercontent.com/42349036/103420598-6665ec80-4b98-11eb-858c-b042824af29c.png)

**Comment by SplinterCurty** [comment]
Single Player...
![Uploading grafik.png…]()

**Comment by SplinterCurty** [comment]
Only in Combi with AD, Moving down manually is not possible with slow down

**Comment by Tensuko** [comment]
So we have to ignore AD drivers too @pvaiko

**Comment by pvaiko** [comment]
Yeah, I had this comment in there a while ago:

```
	-- TODO: maybe check for AutoDrive? Or better provide and interface to AutoDrive to disable the proximity sensor?
```
