### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Guilerbom** [Courseplay/courseplay#6602]
after the last update, .000019 the translation to Brazilian was like this

![image](https://user-images.githubusercontent.com/64747606/103421257-1841f080-4b7a-11eb-9435-c08ad1a150c5.png)

**Comment by Tensuko** [comment]
Yeah that was an upsi by myself, sry for that, update soon!
Thanks @KITT3000 for PR !

**Comment by pvaiko** [comment]
should be fixed in 20
