### ISSUE TITLE
Übergang Vorgewende zu Feldreihen

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#6605]
Hallo Leute
zuersteinmal:

PROSIT 2021

ihr habt 2020 einen tollen job gemacht, ich freu mich schon auf 2021 mit CP

zum anderen, ihr habt mir ja immer zugehört und Fehler, Wünsche und Anregungen umgesetzt.
der übergang vom Vorgewende zu den Feldreihen ist aber noch immer ziemlich "ungewöhnlich umgesetzt.
hier die ausgangsbasis:
![fsScreen_2021_01_01_15_28_11](https://user-images.githubusercontent.com/24860501/103440542-d468ed00-4c46-11eb-994c-8930aa3a9359.png)
Erlengrat, kleine Wiese
Zetter mit 8,7m Arbeitsbreite
2x rundherum
hier der Überblick ingame:
![fsScreen_2021_01_01_15_29_38](https://user-images.githubusercontent.com/24860501/103440570-0e39f380-4c47-11eb-979d-3f4e833eaaaa.png)
das erste und zweite Vorgewende macht er anstandslos,
jedoch fährt er die zweite vorgewenderunde nochmal mit gehobenem schwader und beginnt dann in der Süd-West Ecke mit den Feldreihen.
wieweit vorne kann/soll/muss man den startpunkt denn noch setzen? damit diese unnötige 1x ums Feld fahren verschwindet.
besonders auf kleinen Feldern ist das sehr schwer umzusetzen
bei großen xx-ha Feldern ist das kein problem den startpunkt etwas zu verschieben, damit der CP-Fahrer einige punkte die reihen doppelt abfahren kann, bei kleineren Feldern wird es da schon kompliziert einen anständigen startpunkt zu finden.

lg
andreas

**Comment by Tensuko** [comment]
Häng heir bitte mal die Kursdaten an.

**Comment by andreasthu** [comment]
ja klar, hier ist er:
[courseStorage0006.zip](https://github.com/Courseplay/courseplay/files/5759772/courseStorage0006.zip)

und hier nochmal die aktuellen Kursgenerator Einstellungen:
![fsScreen_2021_01_02_05_42_13](https://user-images.githubusercontent.com/24860501/103450908-5eec3380-4cbd-11eb-81d4-8058362df635.png)
(der Kurs gestern war ein temporärer. den hatte ich nicht gespeichert)

lg
andreas

**Comment by pvaiko** [comment]
mit 21 ist es jetzt behoben.

**Comment by andreasthu** [comment]
danke sehr
lg
andreas
