### ISSUE TITLE
Falsche Geschwindigkeiten bei verschiedenen Arbeiten

### ISSUE THREAD

**Issue by SplinterCurty** [Courseplay/courseplay#6606]
![grafik](https://user-images.githubusercontent.com/42349036/103444031-14d76380-4c65-11eb-8abb-547299fb5cf9.png)

Ich verstelle die Arbeitsgeschwindigkeit über den Eintrag Auf der Straße

**Comment by Tensuko** [comment]
Ja und ?
Was genau ist jetzt der Anzeigefehler ?
Du musst schon mehr erzähl was du willst, was du machst und was passiert als nur das...

**Comment by SplinterCurty** [comment]
Wenn ich die geschwindigkeit Auf dem Feld verstelle. Passiert nix mit der Arbeitsgeschwindigkeit.

Aber die Arbeitsgeschwindigkeit ist doch auf dem Feld oder sehe ich das falsch. 
Auf der Straße heisst für mich, es betrifft die Geschwindigkeit auf der Straße.

Auf dem Feld, Geschwindigkeit die das Fahrzeug auf dem Feld nutzt inklusive Arbeitsgerät / Arbeitsgeschwindigkeit.

Die Arbeitsgeschwindigkeit beim Dreschen konnte ich aber nur über den Eintrag "Auf der Straße" verändern

**Comment by Tensuko** [comment]
So das heist also es werden falsche Geschwindigkeiten bei einigen Arbeiten verwendet und kein einfacher Anzeigefehler.

**Comment by SplinterCurty** [comment]
Ist vll einfach die Zuordnung von den Geschwindigkeiten falsch ?   Straße mit Feld vertauscht ?

**Comment by andreasthu** [comment]
Also ich habe das immer anders verstanden.
Arbeitsgeschwindigkeit ist bei mir immer, was in der xml des Gerätes definiert ist.
Geschwindigkeit am Feld 24km/h war immer mit
# mit welcher Geschwindigkeit der Abfahrer zum Drescher fährt. 
# mit welcher Geschwindigkeit der Ladewagenfahrer mit vollem Ladewagen zum abfahrkurs fährt oder vom Abfahrkurs zum Punkt wo er am Feld vorher aufgehört hat.
Detto der Fahrer mit Feldspritze / Düngerstreuer / Sähmaschine.... 
So hab ich das zumindest beobachtet.
Lg
andreas

**Comment by Tensuko** [comment]
@andreasthu ist es auch eigentlich...

**Comment by SplinterCurty** [comment]
Extra noch einmal getestet auf langen geraden strecke
![grafik](https://user-images.githubusercontent.com/42349036/103456626-3df50400-4cf8-11eb-9d42-12f103408068.png)

"Auf der Straße" beeinflusst eindeutig die Arbeitsgeschwindigkeit beim Weizen dreschen

**Comment by 60erjonny** [comment]
Hallo

Ist dieses Schneidwerk ein Mod...? 
Evtl. hier mal nachschauen, welche Arbeitsgeschwindigkeit möglich ist.
Tritt dieses Problem bei einem andern Werkzeug auch auf...?
mfg
jonny

**Comment by SplinterCurty** [comment]
Morgen, hab nun mit der Amazone Condor 15001 getestet. Gleiche Darstellung. Mir ist dabei aufgefallen, wenn ich die Geschwindigkeit "Auf der Straße" ändere, geht diese nicht unter die eingestellte Geschwindigkeit bei "Wendemanöver".
![grafik](https://user-images.githubusercontent.com/42349036/103474107-db0b7780-4da0-11eb-8df4-55f1be85cdab.png)

**Comment by 60erjonny** [comment]
Hallo
Dieses Script das dir, den Tankinhalt anzeigt kenne ich nicht.
Teste mal ohne diesen Mod...
Oder noch besser, starte das Spiel ohne alle Mod´s nur die nötigsten und teste.
Bei mir kann ich, dieses Problem nicht erkennen.
mfg
jonny

**Comment by Tensuko** [comment]
Mal eine ganz einfache Frage in die Runde:
Wo ist hier das Problem ?
Ist es nicht Banane wenn ich dem Drescher erlaube auf der Straße 30 zu fahren, dass er ganz normal mit seiner maximalen Arbeitsgeschwindigkeit arbeitet ?
Ich verstehe das eigentliche Problem hier nicht ?!
In wie weit behindert das irgend eine Funktion die ihr nutzen wollt ?
Ich wüsste nicht was...

**Comment by rondo24xx** [comment]
Hallo zusammen,...

@Tensuko Es war mal folgende "Kombination" mit den Geschwindigkeiten möglich.
Bsp. Gülleausbringung auf dem Feld mit diesen Geschwindigkeitseinstellungen...

Wendemanöver   : 10 km/h (erklärt sich von selber)
Auf dem Feld   : 25 km/h
Rückwärts      : xy km/h (spielt hierbei keine Rolle)
Auf der Strasse: 50 km/h
Geschwindigkeit: max.

Ein Gespann fährt zum Befüllen auf der Strasse mit 50 km/h und anschließend zum 
"Arbeisbeginn" auf dem Feld mit der max. Geschwindigkeit Arbeitsgerätes (Bsp. 17 km/h).
Wenn der Gülletank leer ist, wird die Strecke auf dem Feld mit (Auf dem Feld = 25 km/h)
bis zum Anfang des Befüllkurses gefahren. Dann geht es wieder mit (Auf der Strasse: 50 km/h)
weiter zum Befüllen.

Also... die Geschwindigkeit "auf dem Feld" habe ich für Transportfahrten auf dem Feld genutzt
und nicht als Arbeitsgeschwindigkeit. Dafür wurde die max. Arbeitsgeschwindigkeit vom Gerät genutzt.

Ist zwar mehr eine "optische" Sache, sieht aber schon nice aus wenn die Gespanne nicht mit 50 km/h auf dem Acker rumheizen sondern "vernünftig" unterwegs sind ;-)
Denke das dafür auch mal die unterschiedlichen Geschwindigkeitseinstellungen vorgesehen waren.

P.S. war nur als Bsp. zur Verdeutlichung des Anliegens von "SplinterCurty". 
Trotzdem möchte ich mich für die unermüdliche Arbeit des gesamten CP-Teams recht herzlich bedanken.
Ihr macht einen tollen Job. 

VG Rondo

**Comment by Tensuko** [comment]
@rondo24xx 
Wenn du zum Abfahren AD nutzt, dann ist das schon die AD Geschwindigkeit.
Aber so wie von dir beschrieben läuft es dann doch ?
Arbeit mit max Arbeitsgeschwindigkeit, fahren auf Feld von A nach B (nicht Arbeiten) mit Feldgeschwindigkeit und auf der Straße mit Geschwindigkeit auf der Straße... Frage bleibt: Wo ist das Problem ?

**Comment by rondo24xx** [comment]
@Tensuko... Erstmal vielen Dank für Deine schnelle Info. Habe heute dazu auch noch einmal mit der jetzigen Vers. xxx22
einige Testläufe gestartet.

1. Test)  In  Kombination mit AD ist es dann so wie von Dir beschrieben ... nachdem  z.Bsp. das Güllefass leer ist wird an AD "übergeben" und von dem Zeitpunkt an wird auch die Geschwindigkeit von AD gesteuert. Es wedren dann also nicht mehr die Einstellungen von CP für die Feldgeschwindigkeiten genutzt. War bislang der Meinung, dass CP für Fahrt auf dem Feld bis zum "Zielpunkt" vom AD für die Fahrgeschwindigkeit zuständig ist. Danke für die Info.

2. Test) Mit kompletter Helferunterstützung von CP (sowohl Arbeitskurs ... als auch anschließendem Zubringerkurs) werden alle Geschwindigkeiten so gefahren wie in den Einstellungsvorgang vorbelegt wurden. Also wie von Dir vermutet sollte alles i.O. sein. Gestestet wurde nicht mit Mods sondern mit den Standardgeräten vom Vanilla- Fuhrpark.

Falls es von jemandem anders festgestellt wurde, habe ich es dann auch nicht reproduzieren können.

Nochmals vielen Dank, macht weiter so und für mich soweit alles i.O. 

VG Rondo
