### ISSUE TITLE
combine/overloder  not like merged  field 

### ISSUE THREAD

**Issue by magicmana** [Courseplay/courseplay#6609]
hello  and happy   new  year .
on  the map i play actually (kanderlin) i have a  field  who have a really strange form  (field 41 on screenshot) 
![fsScreen_2021_01_02_21_57_01](https://user-images.githubusercontent.com/32802279/103466765-19287d00-4d48-11eb-9e30-e21e2c89902a.png)

not easy to  use courseplay on  it ,  i  had cut tree and merged   with the field who are near  (field 15):   
![fsScreen_2021_01_02_21_57_13](https://user-images.githubusercontent.com/32802279/103466835-082c3b80-4d49-11eb-9917-15716148c969.png)

when   plow , seeder , sprayer , have no problem with that ; all see only one field    ,  but  with  combine/overloader  with the detect by field  , they consider the area as 2 distinct  field ,  and  when the combine and the overloder  are not in the same (original)   field   the call from combine  not work .
i tryed on overloader,  to not specify the  field  (like on the screenshot) , and select the two combine   , but  don't work.  for sample  if the overloader  wait a call in field 41.  i need to stop  his course ,   move  it  in the field 15 and restart the course. 
![fsScreen_2021_01_02_17_41_08](https://user-images.githubusercontent.com/32802279/103467051-462a5f00-4d4b-11eb-8ee4-8850411e796c.png)

**Comment by Tensuko** [comment]
#5272 and also read Wiki...

**Comment by magicmana** [comment]
no log  sorry ,  need replay  5h  for the last savegame ,for reproduce...

**Comment by Tensuko** [comment]
I can't rly replicate this, I have some combined fields and no Issue by unloading my combine.

**Comment by magicmana** [comment]
ok , thanks  for anwser . 
the field i  had used is a big nightware for CP.  100 ha  a lot of  electric pole , and a very strange field geometry....   
(the next time i use plow on it ,  i will split  it , in 2 different field ) 
should be something else  the  vehicle  not  like ( had the same  bug  7 or  8  time on this part of  field) .

ps.  i  tested to enlage a lot the turn  circle  on my  transborder (who  drive a 50km/h) and that reduce a lot the  collision with combine  who not stopping for unload (when then combine configured to stop   ,that reduce the  collision  to 0) .  indexing  the  turn circle with  speed   , should be perhups a  thing  to study .

**Comment by Tensuko** [comment]
Update to Version .00022 and it should work a lot better.
