### ISSUE TITLE
Silo verdichten

### ISSUE THREAD

**Issue by DonBolli** [Courseplay/courseplay#6610]
Seit dem Fix funktioniert dieser Modus zwar wieder, mir ist aber aufgefallen das links vom Traktor am Anfang nicht verteilt wird. Am Ende perfekt.
Ein Detail, aber es ist mir aufgefallen.

**Comment by Tensuko** [comment]
Ohne Bilder, logfile und nähere Infos nützt das nichts...

**Comment by DonBolli** [comment]
Log: [log.txt](https://gist.github.com/DonBolli/dfc941bd444b52f0597b59c89abbdc09)
CP Version: 6.03.00018 updated to  6.03.000190

![image](https://user-images.githubusercontent.com/43571844/103474738-10b35f00-4da7-11eb-87ba-ec89ea4be783.png)

**Comment by Tensuko** [comment]
Das wird daran liegen, dass vorne so viel zeugs liegt.
DIe Rolle läuft auch mit dem modus verdichten, welcher einfach nur die Bahnen rauf und runter fährt.
Versuch mal den Fliegel Duo oder ein Schild zum verteilen.

**Comment by xerion8300** [comment]
Habe es jetzt ausprobiert, mit einem Schild, es schiebt nur die linke Seite.
Version ist die 19

https://www.youtube.com/watch?v=7Yy6pwuOdRI&feature=youtu.be

**Comment by Tensuko** [comment]
Das ist auch kein Wunder.
Da liegt ja auch das meiste rum und ist am weitesten vorne.

**Comment by xerion8300** [comment]
Habe jetzt das Material weiter hinein geschoben, nun geht es.
Problem ist das der Abfahrer nicht weit genug zum abladen in das Silo fährt.
Trotzdem Top Arbeit und schnelle Antworten.
Danke

**Comment by DonBolli** [comment]
Ich habe es mal ausprobiert, das Ergebnis ist nicht wirklich besser.

![image](https://user-images.githubusercontent.com/43571844/103537411-a4af2480-4e94-11eb-96d0-f678e7a40d77.png)

Dies ist jetzt mit dem Fliegel Duo, auf verteilen wie du im Bild sehen kannst. Da es ein Durchfahrsilo ist, ist ein Schild keine Option.

**Comment by Tensuko** [comment]
Bei einem durchfahrtssilo kippt er genau IM Silo ab, was auch immer das Zeug vor dem Silo ist, er nimmt das was er zu erst sieht, nicht den größten Haufen.

**Comment by DonBolli** [comment]
Das ist korrekt, aber er kippt es immer in der gleichen Spur ab, desshalb ist das verteilen so wichtig. Ich würde gerne mit AD abfahren, aber dies ist zur Zeit leider nicht möglich mit einem CP verdichter. Vielleicht kann man da etwas machen.

**Comment by Tensuko** [comment]
Also der CP abfahrer legt anhand dessen was im Silo ist ab und verteielt auch entsprechend, das mit AD ist ein bug und bereits ein Issue, wann dafür ein fix kommt kann ich dir nicht sagen.

Ich werde aber mal das ganze nachspielen mit Häckslen und Silo füllen und schauen was so aufrtitt, im einzelnen und beim testen war das alles kein Problem.

**Comment by DonBolli** [comment]
Ja kein Problem. Ist mir nur aufgefallen. Das mit verteilt abladen hat bei mir immer perfekt funktioniert, seit dem Upddate auf 6.3.00018 ging dies nicht mehr, ich verwende jetzt 6.3.00019. Ich würde  es nicht als Bug oder dringend bezeichnen, ist einfach etwas was mir aufgefallen ist.

**Comment by DonBolli** [comment]
Heute, in der Version 6.3.00023, waren die Ablader bereit das ganze Silo zu nutzen, da der "Verdichter" vorne links jedoch nicht arbeitet, blieb der Ablader jedoch stecken Somit ist es ein Problem, da es massiven Einfluss auf das Spiel hat.

**Comment by xerion8300** [comment]
Welche Version 23

**Comment by DonBolli** [comment]
Genau, brauchst du noch weiter Infos?

**Comment by Tensuko** [comment]
Hast du denn die Breite von der Walze angepasst ?
Oder benutze den Fliegel Duo aus dem ModHub und verwende verteilen.
Ich weis halt nicht wann und wo bei dir was Stecken bleibt.
Man muss eben schon das richtige benutzen um ein Ergebnis zu erreichen.

**Comment by DonBolli** [comment]
Gerät: Walze
Modus: verdichten
Breite: 4,0m

Wenn ich was falsch mache tut es mir leid

**Comment by Tensuko** [comment]
Hat die Walze denn 4m ?
Mal zu meinem Setting:
![fsScreen_2021_01_09_16_43_03](https://user-images.githubusercontent.com/27344744/104095922-c5fb8080-5299-11eb-93c6-074318416125.png)

**Comment by Lars-LS17** [comment]
Hallo Zusammen,

ich habe mal kurz eine Frage. 
Ich habe die CP-Version xx22. Der Modus 10 erkennt keine AutoDrive Fahrer. 
Etwas weiter oben habe ich gelesen, dass das schon bekannt ist und eine Lösung wird kommen.
Habe ich das richtig verstanden oder braucht Ihr nochmal eine Log inkl. Video für die Fehlersuche?

Modus10-aufschütten.

**Comment by Tensuko** [comment]
@Lars-LS17 
Versuch es mal mit Version .00023 (ganz neu) da sollte das gefixt sein.

**Comment by Lars-LS17** [comment]
@Tensuko 
ich habe gerade mal die neuste Version ausgetestet. 
Der erkennt jetzt auf jeden Fall die AutoDrive Fahrer. 
Jedoch fährt der beim Verdichten nur noch exakt in der Mitte, obwohl klar auf der REchten oder Linken Seite Häckselgut "Weiter Vorne liegt".

Ich hab mal die Log angehangen und ein Video gemacht. Video wird gerade noch hoch geladen:
https://youtu.be/11FFlUIYp0c
[log.txt](https://github.com/Courseplay/courseplay/files/5797714/log.txt)

**Comment by Lars-LS17** [comment]
Nachtrag: 
Erst wenn man CP deaktiviert und wieder aktiviert, prüft er im Silo, wo das Häckselgut am nahesten dran ist und bleibt dann auf der Bahn.

**Comment by Tensuko** [comment]
Try .00026 or higher and report

**Comment by DonBolli** [comment]
![image](https://user-images.githubusercontent.com/43571844/105578818-2a7f0b00-5d83-11eb-9463-9fbda94015f9.png)

Courseplay: 6.3.00026

Einstellungen und Gerät identisch wie bei dir, funktioniert trotudem nicht richtig

Welche Infos benötigst du noch?

**Comment by kallitaxi** [comment]
https://youtu.be/hyS6CCoKLkk

Geht mir genau so und Frage : wiese fährt de Traktor keine gerade Linie wenn er am Haltepunkt angekommen ist. 

Auch im Video zu sehen

**Comment by Lars-LS17** [comment]
Meine Erfahrung dabei ist, das der letzte wegpunkt "stopp" nicht so nah am fahrsilo sein sollte. Wenn der letzte wegpunkt weiter vom fahrsilo weg ist, muss der CP nicht so stark einlenken, um am Anfang ganz links hinzukommen. 

Kannst du ja mal ausprobieren, ob das hilft..

**Comment by Quintto** [comment]
I've just tested mode 10 again today (didn't get time for it earlier) 
and it's working now,  it drives over different lanes on the pit and levels it with the Fliegl Duo, but about 5% of the passes it still tries to drive into the wall and get stuck.  like in this screenshot
![20210125194101_1](https://user-images.githubusercontent.com/21219044/105750651-4df1b380-5f45-11eb-975d-9e7d611e81e1.jpg)
![20210125194801_1](https://user-images.githubusercontent.com/21219044/105751564-77f7a580-5f46-11eb-8243-867282bbec94.jpg)

Log with debug channel 10 and 12 
[log.txt](https://github.com/Courseplay/courseplay/files/5868906/log.txt)

**Comment by DonBolli** [comment]
> Meine Erfahrung dabei ist, das der letzte wegpunkt "stopp" nicht so nah am fahrsilo sein sollte. Wenn der letzte wegpunkt weiter vom fahrsilo weg ist, muss der CP nicht so stark einlenken, um am Anfang ganz links hinzukommen.
> 
> Kannst du ja mal ausprobieren, ob das hilft..

Welche Version von CP hast du? Bei mir will das nicht funktionieren

**Comment by Tensuko** [comment]
@Quintto 
stoppoint way to close to Bunker....

How do you guys think we can reach that paint in straight line infront of the Bunker ?
Try it on your own, place tractor at the stop and try to drive only reverse straight next to the wall.....



Zum Rest: Problem an sich behoben, Verbesserungen werden weiterhin kommen.

**Comment by DonBolli** [comment]
Ich habe es heute und gestern getestet, es funktioniert zum Grossteil, der Traktor fährt aber immer wieder in die Wand. Ich habe extra keine Abfahrer genommen, so dass er das Silo in aller Ruhe verdichten kann. Ich habe gehofft dadurch wird es besser, wenn das Material besser verteilt ist. Dies brachte leider auch nichts.

Hier noch ein Bild mit meinen Einstellungen
![image](https://user-images.githubusercontent.com/43571844/106134241-8a502a00-6166-11eb-8f60-a74f04c8b3e9.png)

Und noch ein Video dazu
https://www.youtube.com/watch?v=EkPxRZG2ZHM

Falls du noch weitere Informationen benötigen solltest, lass es mich wissen, ich helfe wo ich kann.

**Comment by Lars-LS17** [comment]
@DonBolli 
Auch hier kann ich nur mein Beitrag wiederholen. 

Es ist wichtig das der stopp Punkt weiter vom fahrsilo entfernt ist. Dann muss der abfahren keine scharfen kurven mehr machen und dann passiert solch ein Problem wie bei dir im Video nicht mehr.

Die Version ist mit Sicherheit nicht zu 100% Perfekt, aber es funktioniert jetzt schon sehr gut.
