### ISSUE TITLE
Mode 3 : Overloader does not brake at the overload point (to high speed when approach waitpoint ?)

### ISSUE THREAD

**Issue by badfly** [Courseplay/courseplay#6611]
Good day! Apologies for my english, using google translate. When using 3 modes, the tractor passes the unloading point without braking, but simply coasting, so it will responsibly drive away from the reloading point. Attaching photo.
![2021-01-03_08-41-57](https://user-images.githubusercontent.com/9772203/103472521-a64af080-4d9f-11eb-9ade-48a8ae0529dc.png)

**Comment by NicholasSoares** [comment]
try putting a stop marker on the exact point where you expect the pipe to be on unload, only work this way here

**Comment by NicholasSoares** [comment]
this auger wagon is known to have some issues as far as i remember, try with another one and probably will work, also check if manually driving you can really unload on this stop position

**Comment by Tensuko** [comment]
![fsScreen_2021_01_03_12_39_24](https://user-images.githubusercontent.com/27344744/103477604-c939cc80-4dc0-11eb-94b4-6eeb188bf826.png)
![fsScreen_2021_01_03_12_39_30](https://user-images.githubusercontent.com/27344744/103477605-ca6af980-4dc0-11eb-9a57-87e3e876538d.png)

Try to set a pipeposition anyway, even if the doesn't have a moving axies, it does work :)

**Comment by archaoncze** [comment]
i had similar problem - it can be easy solved by editing course - move wait pont a bit back and reduce speed for nearest points - i use 15-10-5-0(wait point)-5-10-15 km/h and it works fine.

**Comment by Tensuko** [comment]
maybe the wait point have to be more 'alone' means the WP before and after need more distance to waitpoint. Try that one.
About speed not sure, I maybe drove slow enough while recording.

**Comment by caseguy15** [comment]
The issue I am having is not the course itself.  It is finding the combine on the actual field.

**Comment by badfly** [comment]
> i had similar problem - it can be easy solved by editing course - move wait pont a bit back and reduce speed for nearest points - i use 15-10-5-0(wait point)-5-10-15 km/h and it works fine.

Это помогло.  Без костылей не работает, так же едет мимо.

That helped.
Doesn't work without crutches. It also passes the point.

**Comment by badfly** [comment]
It seems to me that the kursplay simply does not press the brake at the unload point. When you enter the hill, everything is ok, when you descend it leaves.

**Comment by Tensuko** [comment]
So we get to the Waitpoint with too high speed ?
That could be, will have to check this.

**Comment by badfly** [comment]
Курсплей просто не тормозит в точке ожидания. Не нажимает на тормоз. И с тяжелым прицепом прокатывается дальше.

The course play simply does not slow down at the waiting point. Doesn't apply the brake. And with a heavy trailer it rolls on.

**Comment by Tensuko** [comment]
Then something on your side must be wrong, it just works fine with 6.03.00022
We slow down to 10km/h before reach waitpoint so we stop at waitpoint.
![fsScreen_2021_01_09_19_39_44](https://user-images.githubusercontent.com/27344744/104105994-9147f300-52b2-11eb-9391-0b2487ef48cb.png)
Settings I use:
![fsScreen_2021_01_09_19_41_11](https://user-images.githubusercontent.com/27344744/104106015-bb99b080-52b2-11eb-92ec-b71481d45d99.png)

**Comment by badfly** [comment]
https://www.youtube.com/watch?v=SUsKIuyi8ww

**Comment by badfly** [comment]
На видео видно что трактор не тормозит. Не загораются стоп сигналы.

The video shows that the tractor does not slow down. Stop lights do not come on.

**Comment by badfly** [comment]
Настройки скорости в редакторе

Speed settings in the editor
![FarmingSimulator2019Game 2021-01-11 14-45-48-421](https://user-images.githubusercontent.com/9772203/104179259-9d4fc400-541c-11eb-9748-5bb3d47090af.jpg)
![FarmingSimulator2019Game 2021-01-11 14-46-16-787](https://user-images.githubusercontent.com/9772203/104179281-a2147800-541c-11eb-9f0d-9dcd6b0cac0e.jpg)
![FarmingSimulator2019Game 2021-01-11 14-46-19-413](https://user-images.githubusercontent.com/9772203/104179284-a345a500-541c-11eb-916a-2105f299ff98.jpg)
![FarmingSimulator2019Game 2021-01-11 14-46-24-255](https://user-images.githubusercontent.com/9772203/104179287-a3de3b80-541c-11eb-90ea-4d5c56cc1cd3.jpg)
![FarmingSimulator2019Game 2021-01-11 14-46-25-943](https://user-images.githubusercontent.com/9772203/104179288-a3de3b80-541c-11eb-8453-44af34a9c40e.jpg)
![FarmingSimulator2019Game 2021-01-11 14-46-26-907](https://user-images.githubusercontent.com/9772203/104179289-a476d200-541c-11eb-9e8a-4e953028d6df.jpg)

**Comment by Tensuko** [comment]
> maybe the wait point have to be more 'alone' means the WP before and after need more distance to waitpoint

**Comment by badfly** [comment]
ok, i try it.

**Comment by Tensuko** [comment]
before I forget it, have a look, maybe it helps you https://www.youtube.com/watch?v=YhB5EXQfqIE
