### ISSUE TITLE
Gülle Ausbringung läuft nie

### ISSUE THREAD

**Issue by dicktimmerman** [Courseplay/courseplay#6613]
Gülle Ausbringung wirkt nie, entweder mit Schleppslauch entweder mir z.B. Catros 6002-2 und mit der Modus für Sähen/Düngen. Nütze ich den falschen modus? Oder?

**Comment by Tensuko** [comment]
Tja, kannst du denn manuell Gülle ausbringen ? logfile ?

**Comment by dicktimmerman** [comment]
Manuell geht das, Logfile, wie mache ich einen Logfile und welche Kanale muß ich nützen?

**Comment by Tensuko** [comment]
Steht im Wiki https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
Klappt ohne Probleme:
![fsScreen_2021_01_05_11_04_44](https://user-images.githubusercontent.com/27344744/103633328-e1872400-4f45-11eb-829d-2be03f3ca77f.png)
Ergebnis sieht man auf der Karte:
![fsScreen_2021_01_05_11_05_30](https://user-images.githubusercontent.com/27344744/103633375-ee0b7c80-4f45-11eb-80fd-259c7460ab4a.png)

**Comment by SeriouZ12** [comment]
Vielleicht auch einfach schon davor gedüngt gewesen?

**Comment by Tensuko** [comment]
Ich mach hier zu, weil es läuft definitiv und liegt nicht an CP.
