### ISSUE TITLE
Park - Funktion von AutoDrive ist nicht vorhanden

### ISSUE THREAD

**Issue by Liam-0408** [Courseplay/courseplay#6614]
Version: 6.03.00020

Wenn ich bei Feldarbeit bin, kann ich zwar entladen/auffüllen auswählen, aber eben nicht Parken. Kann jemand bitte helfen?

**Comment by Tom20214** [comment]
Hast du den Fahrzeug ein Parkplatz zugeordnet?

**Comment by Liam-0408** [comment]
Ja habe ich gemacht

**Comment by Tensuko** [comment]
Keine Ahnung wie und wann diese Parkfunktion von AutoDrive funktionieren soll...

**Comment by Tom20214** [comment]
Bei funktioniert das

**Comment by Tom20214** [comment]
@Liam-0408 hast du ein Fahrzeug oder ein Gerät ein Parkplatz zugeordnet? Es funktioniert nur bei Fahrzeugen nicht mit Geräten.

**Comment by Tom20214** [comment]
Logfile?

**Comment by 60erjonny** [comment]
Hallo
Zitat: Es funktioniert nur bei Fahrzeugen nicht mit Geräten. ---> Falsch...!
Wenn ein Fahrzeug mit einem Gerät ein Parkplatz zugewiesen wird, kann auch CP dann an ihn übergeben.
Habe ich schon oft getestet und es funktioniert.
Wenn ein Fahrzeug ohne Gerät ein Parkplatz zugewiesen bekommen wird, kann CP wohl nicht übergeben, weil CP nur das Gerät an sich erkennt und dann von keinen Parkplatz weiß.
Also nochmal bei dieser Funktion ist immer wichtig, das das Fahrzeug mit einem Gerät einen Parklplatz hat.

mfg
jonny

**Comment by Tensuko** [comment]
@60erjonny 
Danke für die Aufklärung und testen.
