### ISSUE TITLE
Menu doesn't open

### ISSUE THREAD

**Issue by blackhawk08X** [Courseplay/courseplay#6616]
When I host a multiplayer game, or port a multiplayer game to single player, I can no longer open the CP menu. The shortcuts all work but I can't get the keybinds to open the menu. I've tried changing the keybinds, tried buying new vehicles, fresh install of CP... no luck. Friend is having an identical problem.

**Comment by Tensuko** [comment]
logfile ?! .....................

**Comment by blackhawk08X** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5797839/log.txt)

**Comment by Tensuko** [comment]
Moving Savegame arround between SP and MP will couse the HUD to offset.
In your savegame is a courseplaysettings.xml file.
Delete this line and try again:
<courseplayHud posX="0.335938" posY="0.029861" hudScale="1.000000" uiScale="1.000000">

**Comment by Tensuko** [comment]
Did you try this out ?

**Comment by Tensuko** [comment]
Closed due to inactivity.
