### ISSUE TITLE
[Suggestion] Mode 2 new rules

### ISSUE THREAD

**Issue by vonbarky** [Courseplay/courseplay#6619]
Hello, first time posting here.  For both these items, I've run two combines, one Mode 2 assigned to each, and also one combine, one Mode 2 assigned to test the theory.  All have been run with no headland, or with headland.  Turn on Field is off, avoid fruit is off.  My crop destruction is turned off so I don't care about running over the fruit.  I am playing on PV County, mostly harvesting Hemp and Coffee, which are very high yield items, 3.3L/sq mt. and 3.1L/sq mt, so I'm sure this is happening a lot more to me just because of the volume of fruit coming from the combine, but good for testing :)

Issue 1: End of field - Mode 2 stays in fruit.

At the end of the field, if it was unloading all the way to the end, the Mode 2 tractor will just sit in the fruit, causing a collision when the combine pulls away from the field, turns around and starts harvesting the fruit that the Mode 2 tractor is sitting in.  It would be better if after the combine had pulled away, it got off the fruit.  OR, back up as soon as offloading is done and move.

Issue 2: Mode 2 gets full during offload OR is the quantity held is over the Drive on at % after an offload when combine is stopped

It appears that the default choice for the Mode 2 tractor in either of these instances is to turn directly in front of the combine that is about to start harvesting again, causing a collision.  If he waited, backed up and then drove on, that would be ok, or if he turned to the left away from the harvester, that would be ok too.

If Mode 2 gets full during a offload while the combine is still moving, everything works as planned - Mode 2 stops, waits for the combine to pass, then turns behind him.  No collision

If wanted/needed I can support with screenshots and logs, but thought I would put this out here first before going through all that work to see if it's needed.

As an aside, the new version is a HUGE upgrade in pathfinding and behavior from 6.02  Great job!

**Comment by Tensuko** [comment]
>  Turn on Field is off

Got no impact on combines



> avoid fruit is off

you should not do this, unless you want unloader to park in your crops.



> Issue 1: End of field - Mode 2 stays in fruit.

keep avoid fruit on, and its fine.

Screenshots and logfiles with channel 4 7 12 and 14 are always requered.
For all your stuff you mentioned here, what version do you even use ?!
We are at 6.03.00020 and had a hughe update for Mode2 with .00020....

**Comment by pvaiko** [comment]
> We don't need new rules for this Mode.

Well, why not if they make sense. However, currently we only have very limited support for Mode 2 with fruit avoidance disabled, and don't think we'll have time to work on that any time soon.

@vonbarky please reopen if you have issues or suggestions regarding Mode 2/3 with fruit avoidance enabled.
