### ISSUE TITLE
Lenkungsart beibehalten

### ISSUE THREAD

**Issue by 60erjonny** [Courseplay/courseplay#6620]
Hallo

![fsScreen_2021_01_04_19_07_20](https://user-images.githubusercontent.com/63659182/103565303-6b8ca980-4ec0-11eb-94ac-d77efc0fc605.png)
Was genau kann diese Einstellung bewirken...?

mfg
jonny

**Comment by Tensuko** [comment]
Genau das was da steht.
Wenn du Hundegang drin hast, bleibt diese auch drin, oder eben Allradlenkung.
