### ISSUE TITLE
Platform trailers

### ISSUE THREAD

**Issue by Alex83fs** [Courseplay/courseplay#6621]
Hi! When the modifications included a **"Courseplay"** all platform trailers are in conflict with the **"Courseplay"**, tell me how to fix it. Log and screenshots are attached.
![FarmingSimulator2019Game 2021-01-04 22-14-01](https://user-images.githubusercontent.com/76746340/103566259-25910f00-4edb-11eb-9248-0776f123b106.png)

![FarmingSimulator2019Game 2021-01-04 22-14-06](https://user-images.githubusercontent.com/76746340/103566274-2c1f8680-4edb-11eb-8f71-d4f0048fdc56.png)

[log.txt](https://github.com/Courseplay/courseplay/files/5766191/log.txt)

**Comment by Tensuko** [comment]
Harmless Callstack that appears. we never did anything about it, just ignore it.

**Comment by Alex83fs** [comment]
> Harmless Callstack that appears. we never did anything about it, just ignore it.

In general, do you plan to fix it?
