### ISSUE TITLE
Mode 5

### ISSUE THREAD

**Issue by Alwisbraun** [Courseplay/courseplay#6622]
Erstmal vor weg ich find es echt toll das es wieder Updates gibt weiter toll Arbeit

Im Mode 5 / Überführung Fahren die Helfer leider nicht mehr von alleine am ersten Wegpunkt an so bald sie am letzten vorbei sind so wie es früher war 

ich haben denn Mode 5 immer genutzt um vom Händler zum Hof zufahren und habe die Fahrzeuge immer mit einem parken Schild am ende anhalten lassen 
denn Mode 5 habe ich aber auch genutzt um verkehr zu Simulieren und um Silos bis 100% zu Verdichten das hat immer super Funktionier da die fahrzeuge ja immer wieder am ersten Wegpunkt angefangen haben und das unendlos !
leider tuen sie das nicht mehr wird das noch mal kommen ? vielleicht als extra Funktion im Mode 5

MFG Alwis Braun

**Comment by Tensuko** [comment]
> genutzt um vom Händler zum Hof zufahren

Genau für so ein A nach B Strecke ist der Mode da.
2 Kurse, einen von A nach B und einen von B nach A, fertig.

> denn Mode 5 habe ich aber auch genutzt um verkehr zu Simulieren

Sry aber das ist halt kein Stück wofür CP da ist und auch ganz klar ein Einzelfall...

> um Silos bis 100% zu Verdichten

Dafür ist Mode10 da!

Also nein, das wird nicht wieder kommen, da es einfach keinen wirklichen nutzen für eine Endlosschleife gibt.
