### ISSUE TITLE
mode 10 driver driving into silo wall

### ISSUE THREAD

**Issue by Quintto** [Courseplay/courseplay#6623]
Hello,

I just set up a mode 10 course in the BGA of Untergriesbach (drive through pit). and set up a tractor with a frontweight and the Fliegl Duo to level the silage. 

At first it was working great, but after the first field was done I stopped the driver to record an unload course for the second field. and when I restarted the driver all he does after reaching the starting point in the silo is drive into the silo walls.
but when I disconnect the fliegl duo and set it to just compacting it's working as it should untill it reaches the end of the silo where the tractor starts driving circles.

courseplay version v6.03.00020 
the course:
![20210104213800_1](https://user-images.githubusercontent.com/21219044/103577821-c2e94480-4ed5-11eb-853f-4dd05f38d076.jpg)
also when I restarted the game to get a clean log, it shows an error when I start the mode 10 driver the first time I click start
[log.txt](https://github.com/Courseplay/courseplay/files/5766730/log.txt)

**Comment by Quintto** [comment]
So here is an update from me
I tried some stuff, I cleared the first part of the silo of silage (with a shield) and it still drove into the wall after that I tried to record a course for a different empty silo and even in that silo it runs into the wall
(one thing to note is that it keeps driving into the wall on the right) 
So I gave up for now and did the rest of the compacting by hand

when the time came to sell the silage I made an unloading course 
![20210106170242_1](https://user-images.githubusercontent.com/21219044/103790408-73278c00-5041-11eb-81ce-9d00dc9bc1ef.jpg)
and even that tractor started driving into the same wall, but after a few restarts of the driver its working (for now)

**Comment by Tensuko** [comment]
For Mode9 I would always start on first waypoint, as you can't rly know where he wants to start either.
Debugchannel 10 and 12 would help as well on those situations.

**Comment by schwiti6190** [comment]
@Quintto could you please try this with the new version ? :)
You would  have to make sure the starting point is in the bunker and the stop point is a bit infront of the bunker :)

**Comment by Bugatti461** [comment]
I tried this with debug channel 10 and 12 but unfortunately it still goes to the right side I can do what I want. What else can I do now lift the 6.03.00025.

**Comment by Quintto** [comment]
I just tried it on version 6.03.00025 too and for me it's not driving into the same wall it sometimes taps the silage and goes to the front again and other times he drive into the wall (at different angles everytime)

**Comment by Tensuko** [comment]
> 
> 
> I tried this with debug channel 10 and 12 but unfortunately it still goes to the right side I can do what I want. What else can I do now lift the 6.03.00025.

what mode in mode10 ?
log with channel 10 and 12 + screenshots.

**Comment by Tensuko** [comment]
> 
> 
> I just tried it on version 6.03.00025 too and for me it's not driving into the same wall it sometimes taps the silage and goes to the front again and other times he drive into the wall (at different angles everytime)

Same for you, what mode10 mode, shield ? got the correct shield width ?
log with channel 10 and 12 + screenshots

**Comment by Tensuko** [comment]
In addition, more Updates on Mode10 are already on the way.

**Comment by Quintto** [comment]
![20210120183929_1](https://user-images.githubusercontent.com/21219044/105213367-e7d4ed00-5b4e-11eb-8abd-61f1a09d798b.jpg)
![20210120183953_1](https://user-images.githubusercontent.com/21219044/105213372-e9061a00-5b4e-11eb-910e-bc4c16a3ccf0.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/5844226/log.txt)
Here you go, the mode was set to leveling with the fliegl duo on the back of the tractor

**Comment by Tensuko** [comment]
Your stoppoint is way to close to the Bunker.... How can he be able to hit that white point you see there.....

**Comment by Tensuko** [comment]
Try .00026 or higher and report

**Comment by Lars-LS17** [comment]
Ich habe es gerade mal für 20 min ausgetestet. Sieht erstmal sehr gut aus. 
Langzeit Tests werden noch folgen.
Der fährt jetzt schön von Links nach Rechts und schüttet das Silo auf. 
Er wartet immer auf seiner Parkposition, wenn ein Abfahrer sich nähert.

**Comment by Tensuko** [comment]
Ok, ich mache das Issue hier zu, weil es noch ähnliche Issues gibt, wo man sonst weiter drüber reden kann #6610
