### ISSUE TITLE
Pathfinder Bug: No path found to combine mode 3

### ISSUE THREAD

**Issue by Marv63** [Courseplay/courseplay#6626]
Hi, 
I got courseplay master version: ffc85cbbb7b98ca7d3777bc83da2d2bda66f026e
I use the biggest vanilla game standart auger wagon and a Modded John deere 8410R and S790 Harvester.
I am on flint Hills: https://jsmapping.itch.io/flint-hills field 6 (quite Big on headlands atm) but he doesn´t even finds a path to harverster if harvester is right next to augerwagon. 
here is log with debug modes: 4 7 12 14 : https://pastebin.com/S0HawEeC

there are some screenshots taken while the log was created: 
![fsScreen_2021_01_05_11_24_15](https://user-images.githubusercontent.com/15062841/103636431-40e73300-4f4a-11eb-9e9e-fe866b1ff3c0.png)
![fsScreen_2021_01_05_11_24_38](https://user-images.githubusercontent.com/15062841/103636512-6116f200-4f4a-11eb-93cc-0b2c5ca193f4.png)
![fsScreen_2021_01_05_11_25_13](https://user-images.githubusercontent.com/15062841/103636520-64aa7900-4f4a-11eb-8945-eba5d64f6b69.png)

Hope you can figure it out 
I will be here for further questions.
Greetings Marv63

**Comment by pvaiko** [comment]
Did you happen to have the offset changed for the unloader? The log shows a side offset of 20 cm:
2021-01-05 11:24 :32 [dbg4 lp27400] 410 (#1):  -> S790 (#2): Finding path to S790, xOffset = 0.2, zOffset = -7.0

That is certainly wrong, it should be approximately the pipe length, like 8 or 9 meters. Make sure the offset is set to 'auto'.

**Comment by Marv63** [comment]
how to set it back to auto? 
I changed it since the trailer collided with the header ...

**Comment by Marv63** [comment]
Ok, so with an other bigger tractor finding a combine and a path to it works. I use the offset too! The tractor from this issue doesn´t work with auto or the same offset as the offset of the bigger tractor. IDK. Its a bit anoying but ok. 
You can close this if you want, the tractor still doesn´t work, maybe i could rebuy it. IDK resetting didn´t work.

**Comment by pvaiko** [comment]
Remember the manual offset is relative to the calculated pipe offset, so if you have a problem hitting the pipe and want to move 0.5 meters then set it to 0.5 in HUD.
