### ISSUE TITLE
Error: Running LUA method 'update'.

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#6628]
Hallo liebes CP Team. seit der neuesten Version 06.03.00022 bekomme ich folgenden Logfehler beim Fahrzeugwechseln mit tab oder beim aussteigen von einem fahrzeug.

Error: Running LUA method 'update'.
2021-01-05 15:10 dataS/scripts/vehicles/Vehicle.lua(2920) : attempt to call method 'getCurrentHelper' (a nil value)

Ich bin grad auf der umgebauten kernstadt unterwegs und mache das BGAsilo leer

Hier die log:[log.txt](https://github.com/Courseplay/courseplay/files/5770726/log.txt)

MFG Mannie313

**Comment by Tensuko** [comment]
Kein CP Error, muss von einem Modfahrzeug kommen.
Da ich auf meinem gemoddeten Save das nicht habe wirds Mod Issue sein.

**Comment by Mannie313** [comment]
@Tensuko das passiert auch mit dem original New Holland Radlader.
Das liegt nicht an einem Mod Radlader.

MFG Mannie313

**Comment by Tensuko** [comment]
Der LUA Error Pfad ist trotzdem kein CP Fehler sondern GIANTS script.
Du hast auch 2 mal Strohbergung drin und ich kenne kein strawharvest v 1.6 und in wie weit deine map umgebaut ist weis ich auch nicht. Versuch es auf einer vanilla map nur mit cp wenn du das da auch hast müssen wir schauen. Ich konnte heute keinen Fehler feststellen.

**Comment by Mannie313** [comment]
FS19_addon_strawHarvest2 sind nur gebäude drin wo für das FS19_addon_strawHarvest sind. und die 1.6 ist immer die spielversion wo ich aktuell hallte.

Probier ich später mal aus.

MFG Mannie313

**Comment by Mannie313** [comment]
Hallo @Tensuko ich hab den Übeltäter gefunden.

https://www.farming-simulator.com/mod.php?lang=de&country=at&mod_id=159410

Das ist der mod wo den fehler verursacht.

MFG Mannie313

**Comment by Tensuko** [comment]
Ah gut zu wissen.
