### ISSUE TITLE
Weird turn behaviour from row to row - enhancement ?

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#6629]
Take a look at video.
https://youtu.be/JMFqH3kPIo8 

Is it normal that worker make such weird turns from row to row ? Most of the options are on default as you can see.
Would it be possible to make a bit better round turn from row to row like he does with other implements ?

**Comment by Tensuko** [comment]
logfile with debugchannel 12 and 14

**Comment by bojanh66** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5771907/log.txt)

**Comment by polosubtil** [comment]
Did you try with Pathfinder activated ?

**Comment by bojanh66** [comment]
No i didnt.
I will test more tomorrow if needed.
On some other fields i also had weird turn from row to row, so i tried to activate "Use AI turns in maneuvers" and it helped.

**Comment by polosubtil** [comment]
I don't use that one much, I usually use pathfinder as it works quite well in most situations

**Comment by bojanh66** [comment]
Here is another problem from row to row with activated Pathfinder.
https://youtu.be/HTKbxLfOLYE

**Comment by pvaiko** [comment]
Was the course in your last video generated with version 20 or before? If yes, can you regenerate that course with the current version and see if it is still a problem? If not can you post that course XML here?

**Comment by bojanh66** [comment]
I cant remember which version created that course, i can only see that i was using version 22 in that video.
Does it matter with which version we have created course? Because i save course for each field work and i dont know should i recreate all those courses with new CP version or not ?
Since that video, i have moved that turn waypoint a bit, so tractor now turns like it should.
But i will try to recreate the exact course with new version and see how it goes.

**Comment by pvaiko** [comment]
Yes 21 had a bug fixed which may be causing this.

**Comment by bojanh66** [comment]
Yes, it is fixed, works nice now.
But would you please take a look at video and see this, there is still some weird behaviour around eletric poles or when two rows are not in exact same line?
It is not a problem, because i can easily edit the course with CP editor and make it work perfect, but maybe it will help you guys.
https://youtu.be/IJkHPVK4_nE

**Comment by pvaiko** [comment]
For the record, in this last video there are two issues:
1. due to the island a regular 180 turn is detected as a headland turn because the section leading into the turn start waypoint is significantly less than 180 degrees from the section leading out of the turn end WP. This cause the wrong type of turn to be generated (headland instead of a 180)
2. when pathfinding on the headland, we use the waypoints of the first headland. The transition from headland 1 to headland 2 is also marked as 1st headland and causing this edge case issue. I think it would be safe to mark the transition as headland 2.

**Comment by bojanh66** [comment]
Course is generated with 2x tools, started doing from up/down rows.
Worker is doing again big circle around the field.
I have activated pathfinding on headland in advanced options.
CP is latest version 25.
if you need log with some debug channel, let me know.
![FarmingSimulator2019Game 2021-01-20 15-21-43](https://user-images.githubusercontent.com/32069662/105188569-548ebe00-5b34-11eb-90e4-cdb8b31db322.jpg)

**Comment by pvaiko** [comment]
Point 2 in https://github.com/Courseplay/courseplay/issues/6629#issuecomment-760956519 is fixed in the above push, point 1 remains as it is until we refactor the course storage/management.
