### ISSUE TITLE
Komische Abfahrermethode

### ISSUE THREAD

**Issue by MaxlLS** [Courseplay/courseplay#6630]
Tagchen wollte mal testen wie das mit dem graßhäckseln funktioniert im mais klappts ja ziemlich gut da fährt der abfahrer ja am vorgewände schön hinter dem häcksler und bei den feldreihen daneben nur beim gras fährt der bei mir perma hinter dem häcksler is das normal ?
![fsScreen_2021_01_05_19_28_18](https://user-images.githubusercontent.com/24233055/103684804-757bde80-4f8c-11eb-825f-80a1b26722fb.png)

**Comment by 60erjonny** [comment]
Hallo
Ich glaube und meine ja...weil da CP "Wiesen" nicht im Sinne als ein Feld erkennt oder erkennen kann.
Liegt wohl auch an GIANTS...
mfg
jonny

**Comment by Tensuko** [comment]
#5470

**Comment by Tensuko** [comment]
Liegt daran das Gemähtes Gras bereits wieder als Frucht erkannt wird.
