### ISSUE TITLE
assorted combine and carting bugs

### ISSUE THREAD

**Issue by djnekkid** [Courseplay/courseplay#6632]
Hello Awesome devs!

There seem to be some bugs on the new harvester-cart interactions:

with the combines on the headland, the cart seems to overshoot
![image](https://user-images.githubusercontent.com/65364380/103707519-0bc0fc00-4faf-11eb-96bf-55acd29f1532.png)

all of them have convoy on, default 100m, but they also wants to overtake
![image](https://user-images.githubusercontent.com/65364380/103707606-3ad76d80-4faf-11eb-9087-5bac8f0ce391.png)
![image](https://user-images.githubusercontent.com/65364380/103707751-8722ad80-4faf-11eb-9422-c4835c6790eb.png)

known bugs, or do you wany any logs

**Comment by djnekkid** [comment]
![image](https://user-images.githubusercontent.com/65364380/103709138-38c2de00-4fb2-11eb-9c4c-b40cebf6f3c0.png)

no way this is 160meters...

**Comment by Tensuko** [comment]
convoy distacne issue #6011
