### ISSUE TITLE
tractor wont unload the combine 

### ISSUE THREAD

**Issue by devilboy123** [Courseplay/courseplay#6635]
hi just wont toknow why when iam driving the combine the tractor wont come and empty  me

**Comment by TobiHH78** [comment]
https://github.com/Courseplay/courseplay/issues/5272

What is deactivated/doesn't work for now:
Multiple unloaders. You can assign more than one, but they may not be able to handle conflicts in a civilized manner.
**Combines/choppers have to be driven by a Courseplay helper. We aren't sure yet if we want to allow other (or manual) drivers, we'll see.**

**Comment by devilboy123** [comment]
ok thank u just want to check i was not miss anything
