### ISSUE TITLE
Leveler doesn't change columns in silo bunker?

### ISSUE THREAD

**Issue by MedicalMajor** [Courseplay/courseplay#6640]
Is there something I'm not understanding about why this tractor won't change lanes in this bunker? I'm trying to get it to work. Any help would be much appreciated! Thank you so much.

**Comment by MedicalMajor** [comment]
![image](https://user-images.githubusercontent.com/15276241/103836317-f519b400-5045-11eb-950f-2f3e834e3c50.png)

**Comment by MedicalMajor** [comment]
![image](https://user-images.githubusercontent.com/15276241/103836332-082c8400-5046-11eb-9500-55624639020e.png)

**Comment by MedicalMajor** [comment]
I've tried on another silo on another map. It seems to do the same thing.
![image](https://user-images.githubusercontent.com/15276241/103836919-aa00a080-5047-11eb-9d27-79bc8eb5d88d.png)

**Comment by zsorra** [comment]
I have the same problem Sorry for writing the rest in german, my english ist not that good enough to describe the problem.

Wie erwähnt, bei mir besteht das selbe Problem, allerdings betrifft das nur wenn man den Mode "aufschütten" wählt.
Der Traktor fährt immer die selbe Bahn ab, erst wenn man ihn stoppt und neu fahren läßt, oder wenn er in die Parkposition fährt, wechselt er die Bahn, fährt diese dann aber ständig auf und ab.
Zudem werden alle Geschwindigkeitseinstellungen ignoriert, beim verteilen fährt der Traktor mit 10 km/h, beim aufschütten mit 20, was eindeutig zu schnell ist.
Das Ignorieren der Geschwindigkeitseinstellung scheint aber allgemein zu sein, glaube ich, den heute habe ich beobachtet das ein Abfahrer mit 60 übers Feld geschossen ist, obwohl eigentlich nur 24 eingestellt sind,
Außerdem fehlt im Mode 1 wieder die Möglichkeit die Haltezeit für für Pausen einzustellen.

Nebenbei will ich noch Danke sagen für die tolle Arbeit die ihr leistet, den trotz der kleinen Problemchen  und Fehler ist Courseplay für mich das wichtigste und beste Addon das mir an LS den meisten Spass bereitet, also Danke und allen ein gutes und gesundes neues 2021.

mfG

**Comment by Mannie313** [comment]
Das gleiche problem habe ich auch mit der Version: 6.03.00022 Hab zwei bilder gemacht das erste wen er anfängt links reinfährt und beim zweiten fährt er nach dem entlassen und neueinstellen rechts rein.

![fsScreen_2021_01_09_10_41_24](https://user-images.githubusercontent.com/3021040/104088546-06daa180-5268-11eb-8501-516db2c46e1c.png)

![fsScreen_2021_01_09_10_42_36](https://user-images.githubusercontent.com/3021040/104088540-fde9d000-5267-11eb-8f67-d8468570d075.png)

MFG Mannie313

**Comment by Tensuko** [comment]
Try Version 6.03.00023 or higher and report.

**Comment by Mannie313** [comment]
https://youtu.be/ZKaJqExms-4

Hallo Leute beim Aufschütten stimmt irgendwas net. CP ist die neueste Betaversion

MFG Mannie313

**Comment by Tensuko** [comment]
Kannst du auch genau sagen was ? Ich wollte mir nicht 10min lang das Video angucken...

**Comment by Mannie313** [comment]
Er fährt nur in der mitte. Nach entlasen fährt er Links oder Rechts rein.

Und den Haufen macht er auch nicht richtig weg weil das schild zu hoch ist.

**Comment by Mannie313** [comment]
@Tensuko hier kannst du es live verfolgen was der CP fahrer grad Macht
https://www.twitch.tv/mannie313

**Comment by Tensuko** [comment]
Try .00026 or higher and report

**Comment by Mannie313** [comment]
Mach ich später Danke

MFG Mannie313

**Comment by Mannie313** [comment]
Kann man das schiebeschild ein wenig nach oben machen beim aufschütten. der Fahrer bleibt ständig am boden irgendwo hängen ohne ersichtlichen grund.

Im speil selber kann ich nix einstellen. ansonsten läuft es soweit tadellos.

MFG Mannie313

**Comment by Tensuko** [comment]
@Mannie313 genau das habe ich intern auch schon angesprochen :)
Im Grunde wollen wir das so machen, wenn er anfängt nach oben zu schieben, dass er dann das Schild hebt, so dass das Häckselgut am Hang abrieselt.
Jedenfals klappt es so am besten wenn ich selber fahre.

Wie sind deine Erfahrungen diesbezüglich ?

**Comment by Mannie313** [comment]
er lässt das schild am anfang zu weit ab so das er immer irgendwo am boden hängen bleibt. ansonsten ist alles soweit gut nur das er manchmal noch gegen die wand fährt oder ein gutes stück von der wand weg bleibt aber nur auf der (rückwärts fahren gesehen) Rechts .

MFG Mannie313

**Comment by Tensuko** [comment]
Ja die Schildbreite muss man selber einstellen, dann hat man aber keine Probleme mehr mit der Wand.
Zu weit runter das Problem hatte ich bisher nicht, das liegt aber auch etwas an der Map.
Über ein Offset für Schildhöhe kann man aber sprechen :)

**Comment by Mannie313** [comment]
![fsScreen_2021_01_25_15_06_32](https://user-images.githubusercontent.com/3021040/105716386-06f0c780-5f1f-11eb-85db-aad0875236ae.png)
So siehts bei mir aus

**Comment by Mannie313** [comment]
@Tensuko und @schwiti6190 schaut euch mal das Video an. Ich habe genau die mitte vom kleinsten silo abgekippt und schaut mal wie der Aufschütter fährt.

@Tensuko and @schwiti6190 look at the video. I have dumped exactly the middle of the smallest silo and look how the Aufschütter drives.

https://youtu.be/GML9OFbR7qM

Ganz rechts und links fängt er nicht vorne an sondern hinten. in der mitte und eine links und rechts daneben fängt er im zweiten feld vorne an. kann er nicht immer vorne anfangen. wäre besser glaub ich.

In the middle and one to the left and right of it, it starts in the second field in front. it can't always start in front. it would be better, I think.

MFG Mannie313

**Comment by Tensuko** [comment]
Ja da muss noch bisschen feinjustiert werden, aber im großen und ganzen sah das ja schon gut aus.

**Comment by Mannie313** [comment]
Hallo CP Team bis jetzt mit der aktuellsten version geht es jetzt gut das siloschieben. ich hab nur ein problem.

Wen bei dem siloarbeiter kommt muß betankt werden und fährt dann zu halteposition um dem ablader platz zu machen tankt der Siloarbeiter nicht .

MFG Mannie313

**Comment by Tensuko** [comment]
Das war so nie vorgesehen.
Könnte man drüber nachdenken, aber da wird es erstmal kein Update zu geben.

**Comment by Mannie313** [comment]
es ging ja mit der vorherigen versionen. Deshalb wundere ich mich ja deswegen.

Wäre net wen man es wieder oder neu mit reinnimmt. 

MFG Mannie313

**Comment by Tensuko** [comment]
Und wofür ?
Bitte hier: https://github.com/Courseplay/courseplay/issues/6402

**Comment by Tensuko** [comment]
Try Version 6.03.00059 or higher and report.

**Comment by Tensuko** [comment]
Closed due to inactivity, should be solved anyway as 2 other Issues reported with success.
