### ISSUE TITLE
Mode 3: Unloader cuts way of Combine 

### ISSUE THREAD

**Issue by Marv63** [Courseplay/courseplay#6641]
Hi. So I read a bit here. So i shouldn´t have this problem since i run: ffc85cbbb7b98ca7d3777bc83da2d2bda66f026e
Firstly the unloader stands in the field when the combine is done unloading and doesn´t move to the old combine position. 
Secondly when the unloder min percentage for unloading is hit and the Combine is done unloading the tractor instantly cuts hard into the header of the combine if the combine is on the way to the Unloading course. I seen turorials and it normaly would wait first. I use Courseplay since fs13. Maybe I missed a configuration somewhere but i think i need help... 
I use the biggest vanilla game standart auger wagon and a Modded John deere 8410R and S790 Harvester with 60ft midwest header.
I do not have log atm. Can send it if you need it. maybe im just stupid. 
Greetings and keep up the good work

**Comment by Tensuko** [comment]
#5272 and Read Wiki page.
Sry but when you did read arround here, why you don't see the existing Issues and Informations for Issue reports like this ?
We ALWAYS need a logfile with channel 4, 7, 12 and 14 and screenshost will help a lot to see whats going on.

**Comment by Tensuko** [comment]
Closed due to inactivity.
