### ISSUE TITLE
Mode 3: Grain cart wont move after first waypoint

### ISSUE THREAD

**Issue by AdamLundberg** [Courseplay/courseplay#6642]
I have been having issus with the grain cart wont move after the first waypoint. I have tried vanilla xerion, custom modding 9rt and siid 8rx and still the same. I have the latest courseplay v6.03.00022.

![Screenshot (5)](https://user-images.githubusercontent.com/60877124/103909282-cc57f400-5103-11eb-9195-78f97113b25c.png)

[Log](https://gist.github.com/AdamLundberg/78fb3c03c34c916c01da656122e6430al)

**Comment by Tensuko** [comment]
To many waitpoints.
Place only one for the 1st bin, then run your truck with Mode1 and it will move forward if the 1st bin is full.
In case your Truck runs with AD, the same feature is requested on AD GitHub, so that AD drives drive forward if the 1st trailer or in this case bin is full.

**Comment by AdamLundberg** [comment]
I have placed two waitpoints for the grain cart before with no problem, Is this something you have changed?

[Like this!](https://youtu.be/42WTOyw12KM?t=145)

**Comment by AdamLundberg** [comment]
I tried v6.02.00064 and it now works as in [the link](https://www.youtube.com/watch?t=145&v=42WTOyw12KM&feature=youtu.be&ab_channel=KederkFarms). Now it continues to the next wait point and empties the rest.

**Comment by Tensuko** [comment]
It was never intended to work like that and not in the manual.
One waitpoint and thats it.

**Comment by betrox007** [comment]
try to Increase **Drive on at less then** Value... i am using multiple wait point also and this work for me.
![Setting](https://user-images.githubusercontent.com/56646850/103961109-59439180-5186-11eb-8dc5-3eb3a54688d3.jpg)
when the remain of load on grain chart bellow that value, off loader will move to next wait point when the first Hooper full (in my experience).
