### ISSUE TITLE
Verbesserung Vorschlag für den Drescher Fahrer

### ISSUE THREAD

**Issue by Daniel78-art** [Courseplay/courseplay#6643]
![fsScreen_2021_01_06_21_10_49](https://user-images.githubusercontent.com/72348662/103919426-4b532980-5110-11eb-8c10-910d5ee1cba0.png)

Wäre es möglich den Drescher Fahrer zu erst das ganze Stroh raus zu blassen lassen und dann erst rückwärts fahren zulassen, und sich denn abzutanken lassen und dann wieder seine Arbeit weiter zu machen?

**Comment by Daniel78-art** [comment]
Hallo ich wollte mal Fragen ob sie es schon geändert haben? Wenn ja denn geht es noch nicht.

![fsScreen_2021_01_11_12_12_32](https://user-images.githubusercontent.com/72348662/104174884-ec8afa00-5406-11eb-935b-cbd8017231c7.png)

**Comment by Tensuko** [comment]
Nein haben wir nicht, ansonsten würde die Info hier stehen und das Issue wäre zu.
Denkt doch bitte mal dran, dass wir das hier als Hobby nebenbei machen und nicht Hauptberuflich!
Wir arbeiten das ab nach der Reihnfolge die wir für wichtig halten und dann muss man auch mal Geduld aufbringen.
