### ISSUE TITLE
TATRA Phoenix 6x6 off course

### ISSUE THREAD

**Issue by dete96** [Courseplay/courseplay#6648]
Hi!
I have a problem with the TATRA Phoenix 6x6 Agro Truck. It seems to be driving about two meters off the pre recorded course which leads to some crashes with eg. powerlines or railroad crossings and stuff. It is the only vehicle so far that behaves that way. Every other vehicle is perfectly on course.

![Tatra Phoenix 6x6](https://user-images.githubusercontent.com/77003672/104095903-a6fcee80-5299-11eb-9cce-8d0a71106f07.jpg)

**Comment by Tensuko** [comment]
That is a GIANTS Problem.
Vehicle got an offset,  #4595

**Comment by dete96** [comment]
Sorry mate, didn't know that. Thank you for your quick response!
