### ISSUE TITLE
Custom field boundary lines

### ISSUE THREAD

**Issue by MtBakerScum** [Courseplay/courseplay#6649]
Not really an issue, just an inquiry

Did the option to overwrite field boundary lines with a custom field edge course get removed? Or is it just not available for contract field work?  I find this option incredibly useful for working on weird fields.

Thanks

**Comment by Tensuko** [comment]
Nothing about custom Field got removed.

Tell me exactly what you want to do and if SP or MP, maybe I can help you.

**Comment by MtBakerScum** [comment]
I figured it out, I forgot I have to plow in a fresh field boundary using my custom boundary line, and then get courseplay to scan the new field edge and overwrite the old boundary line from there.

So I guess if I change this to a feature request, it'd be nice to overwrite the field edge boundary line with a custom course without have to plow in the new field edge. 

Otherwise sorry for wasting your time but being an idiot haha.

**Comment by Tensuko** [comment]
No Idea what you try to do but ofc CP Field boundry scanner can only scan Fields, if you have to plow them for yourself first, then there is nothing we can do about it.
