### ISSUE TITLE
Loading wagon wont go to silo to unload when full

### ISSUE THREAD

**Issue by genslavick** [Courseplay/courseplay#6651]
While playing on Raven port, I have a combined course to use loading wagon to pick up grass from fields 21 and 22 (which I combined), then unlade it in a silo on the farm (near field 26) I own Fields 21,22,24,25,26. but when my loading wagon gets 99% full it stops on loading route and will not continue. I have a similar setup loading from Fields 24-26 (which I combined) and dumping in same silo. my Fields 24-26 combined course works flawlessly. I have tried switching the unload route from the public road spanning between 21-22 to the silo; to taking a back route through the barn/ biomass sell points area to my land. No visible affect. my thinking is that because I don't own the land in between Field 22 and the silo (fd23 and another slice) the offload route gets confused.

**Comment by Tensuko** [comment]
The route don't care about owned lands, but ofc you have to own the land, where you want to unload. Thats basic game.
Can you show us screenshots or a Video about your situation ?

**Comment by Tensuko** [comment]
Closed due to inactivity, reopen when we have more information, screenshot, video, logfile
