### ISSUE TITLE
Combine wont back off for unload if too close from headland start (pipe on fruit)

### ISSUE THREAD

**Issue by NicholasSoares** [Courseplay/courseplay#6653]
Separated issue of combine not backing off when too close from headland, avoid fruit is on and turn on field also on.
Only vanilla vehicles and 2 very basic mods to facilitate this scenario creation, i can upload the save game if needed to recreate the issue.

Also i a senior software engineer, i  dont have much experience with lua this days but if it is somewhere documented i can fix it, and i notice a big lack of documentation in some points of the code, maybe if add some details it will attract more people to collaborate, for example the last issue #6633 i was able to fix, but required a long reading due to lack of comment about the function getDistanceToNextTurn return type(s) in this case, a treat in this function will be a better choice to avoid null returns maybe.
I there is something i can help just let me know.

![fsScreen_2021_01_10_00_23_39](https://user-images.githubusercontent.com/42093631/104113642-58237900-52da-11eb-89a7-ac9775902cfe.png)
![fsScreen_2021_01_10_00_23_46](https://user-images.githubusercontent.com/42093631/104113643-5a85d300-52da-11eb-8fab-8f33be23f55c.png)
![fsScreen_2021_01_10_00_23_48](https://user-images.githubusercontent.com/42093631/104113644-5ce82d00-52da-11eb-9eb6-c330667e9fc4.png)
![fsScreen_2021_01_10_00_23_08](https://user-images.githubusercontent.com/42093631/104113647-5f4a8700-52da-11eb-8e92-d243a6313d99.png)
[Log here](https://drive.google.com/file/d/1Q0EKwEPZta4Zk_DCQa-hfC2lB6VMef2g/view?usp=sharing) (too big for upload on github)

**Comment by Mannie313** [comment]
Lösch mal deine inputbindings und schmeiß mal die mods mit fehler raus hasate dann nicht so ne lange LOG.

Hast nen haufen fehler drin.

MFG Mannie313

**Comment by Tensuko** [comment]
Combine Avoid Fruit = on ?

**Comment by NicholasSoares** [comment]
@Tensuko yes avoid fruit is on in the combine and in the tractor

**Comment by Tensuko** [comment]
You got a Callstack from a Mod.

**Comment by NicholasSoares** [comment]
@Tensuko not a mod issue, my log was just going crazy on size for some reason even before i clean all mods, here is from a vanilla installation with only course play, also the proof of yes the fruit avoid is really on.

![fsScreen_2021_01_10_17_22_33](https://user-images.githubusercontent.com/42093631/104134501-b26b1b00-5368-11eb-885c-8e8802bf6cf8.png)
![fsScreen_2021_01_10_17_20_51](https://user-images.githubusercontent.com/42093631/104134503-b4cd7500-5368-11eb-867c-cc0c2fa20aa4.png)
![fsScreen_2021_01_10_17_22_02](https://user-images.githubusercontent.com/42093631/104134504-b5660b80-5368-11eb-843d-9657320b750d.png)
![fsScreen_2021_01_10_17_22_29](https://user-images.githubusercontent.com/42093631/104134505-b6973880-5368-11eb-96a4-8f90c71d36c4.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5793264/log.txt)

**Comment by pvaiko** [comment]
@NicholasSoares if you had debug channel 14 on you would have seen the message "Pull back course would be outside of the field", look at function CombineAIDriver:createPullBackCourse()

So this is a feature, not a bug. If you have a good idea how to resolve this situation, you are more than welcome go ahead and implement it, I think CombineAIDriver has ok comments but if you have any questions, just let me know.

**Comment by NicholasSoares** [comment]
@pvaiko way not just let it go outside if needed? just out of curiosity as you have seen alot more than me.
I have a possible fix for it, if we cannot have it manuvering afther in some cases, we can just make it stop before it turns when allmost full like 97% and avoid some trouble with that.

i made this code and worked just fine for this case, not really any 10/10 code but does the job.

```
function CombineAIDriver:onWaypointPassed(ix)
....

	 -- Make sure to not turn if almost full to avoid pipe getting stuck on fruit in some cases
	 -- Stop the combine unless we have self unload turned on
	if self:shouldUnloadBeforeTurn() and self.vehicle.cp.settings.selfUnload:is(false) then
		self.fillLevelFullPercentage = self.pocketFillLevelFullPercentage
	end
  
....
end

```
```
function CombineAIDriver:shouldUnloadBeforeTurn()
	local currentIx = self.fieldworkCourse:getCurrentWaypointIx()
	local dToTurn = self.fieldworkCourse:getDistanceToNextTurn(currentIx) or math.huge
	local fillLevel = self.vehicle:getFillUnitFillLevel(self.combine.fillUnitIndex)
	local capacity = self.vehicle:getFillUnitCapacity(self.combine.fillUnitIndex)
	local spaceRemaningPercent = (capacity / fillLevel) * 100
	if dToTurn < 10 and spaceRemaningPercent >= 97 then
		self:debug('Stoping combine to unload before turn as it is allmost full')
		return true
	else
		return false
	end
end
```


![fsScreen_2021_01_11_04_04_15](https://user-images.githubusercontent.com/42093631/104154217-1f130380-53c3-11eb-8e7e-402e2bf002be.png)
![fsScreen_2021_01_11_04_11_28](https://user-images.githubusercontent.com/42093631/104154218-20dcc700-53c3-11eb-9365-b3e0e4b82a91.png)
![fsScreen_2021_01_11_04_01_05](https://user-images.githubusercontent.com/42093631/104154220-21755d80-53c3-11eb-97e7-64178256126a.png)

**Comment by NicholasSoares** [comment]
making a little better version of the code i can also avoid problem with very small fields, i just have only one issue that is the unload driver wont drive to combine if set to 100% fill target on it, any sugestion? manualy calling the driver works and if i set a lower level on it also works, any way to call it manualy on code?

the only changes i made so far:

```
CombineAIDriver.shortRowFillLevelFullPercentage = 80

...
function CombineAIDriver:onWaypointPassed(ix)
....
	self:shouldUnloadBeforeTurn()
....
end
...

function CombineAIDriver:shouldUnloadBeforeTurn()
	-- If self Unload is On no need to make any operation here
	if self.vehicle.cp.settings.selfUnload:is(false) then
		local currentIx = self.fieldworkCourse:getCurrentWaypointIx()
		local dToTurn = self.fieldworkCourse:getDistanceToNextTurn(currentIx) or math.huge
		local fillLevel = self.vehicle:getFillUnitFillLevel(self.combine.fillUnitIndex)
		local capacity = self.vehicle:getFillUnitCapacity(self.combine.fillUnitIndex)
		local capacityUsedPercent = (fillLevel / capacity) * 100
		local rowLength, lastRowWaypoint = self.fieldworkCourse:getRowLength(currentIx)
		local pipeNotOnFruit = not self:isPipeInFruit()
		-- If the field is large enough set the fill target about 95% for unload before a turn
		-- If the field is short set the target to 80%  when pipe is out of fruit to avoid reverse problem 
		if dToTurn < 10 and capacityUsedPercent > self.pocketFillLevelFullPercentage then
			self:debug('Stoping combine to unload before turn as it is allmost full')
			self.fillLevelFullPercentage = self.pocketFillLevelFullPercentage
		elseif dToTurn < 10 and rowLength > 0 and rowLength <= 95 and capacityUsedPercent > self.shortRowFillLevelFullPercentage and pipeNotOnFruit then
			self:debug('Stoping combine to unload before turn as it is allmost full in short row')
			self.fillLevelFullPercentage = self.shortRowFillLevelFullPercentage
		end
	end
end
```

![fsScreen_2021_01_11_07_56_00](https://user-images.githubusercontent.com/42093631/104178586-5c8a8780-53e9-11eb-87ef-73a02faabc94.png)
![fsScreen_2021_01_11_08_36_12](https://user-images.githubusercontent.com/42093631/104178599-63b19580-53e9-11eb-8c1f-287740fe5a41.png)

**Comment by pvaiko** [comment]
@NicholasSoares sorry, I should have mentioned, you'll probably want to look at the Mode2 branch where we already trying to handle this situation:
https://github.com/Courseplay/courseplay/blob/e21c718bde4c27cec71c4b8a7661a1b79f937ad3/CombineAIDriver.lua#L611

Combine unloading is probably is the most complex function in CP, a solution for a specific case may cause issues in other situtation.
