### ISSUE TITLE
Run Lua Error with Helycopter and Courseplay

### ISSUE THREAD

**Issue by TunikaTante3179** [Courseplay/courseplay#6655]
Wenn man **Courseplay** und einen **Helicopter** mod hinzufügt gibt es einen Lua Error meldung und dass wiederholend!
Wer kann mir Helfen?
Ich Danke schon voraus

If you add **courseplay** and a **helicopter** mod, you get a Lua error message and repeat that!
Who can help me?
Thank you for Help
English by Google Translate

**Comment by Mannie313** [comment]
Please LOG File.

MFG Mannie313

**Comment by TunikaTante3179** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5792799/log.txt)
Here the Log

**Comment by Tensuko** [comment]
Sry, aber für solche Mods geben wir keine Unterstützung.

**Comment by TunikaTante3179** [comment]
Wie meinen sie?

**Comment by Mannie313** [comment]
ganz einfach. Tracktoren LKW's und Autos Fahren. Der Heli fliegt und wird von CP nicht unterstützt. Entweder Heli selber fliegen oder Tracktoren usw nehmen.

MFG Mannie313

**Comment by TunikaTante3179** [comment]
Ich habe es falsch geschrieben.
1. Wenn man ein Heli mod rein tut und Cp rein tut und dass Savegame startet und ins spiel gehe dann gibt es Errors und man kann im Spiel nichts mehr machen.
2. Gibts ne möglichkeit dies umgehen?
Sorry für meine blöde Frage am Anfang
Gruss Tunika

**Comment by Mannie313** [comment]
https://mega.nz/file/hN9WVT6R#ZsTAOfPCfZxlqMMHzpfhcKXQDlkBT7Y1sCl1ptL56Lo

Probier mal den aus.

**Comment by TunikaTante3179** [comment]
Mit diesem Heli habe ich es ausprobiert!
Geht jetzt aber immer noch nicht.
Vlt. mache ich so dass ich cp rausnehme wenn ich den Heli rein nehme die kürse sollten immer noch gespeichert werden.
Danke für die Hilfe
Vlt. find eich einen ausweg
Gruss Tunika
