### ISSUE TITLE
toolManager.lua:97: attempt to compare number with nil

### ISSUE THREAD

**Issue by lavatan05** [Courseplay/courseplay#6658]
I know this is kind of a known issue but I'm having it when the Krone BigX pack from the Modhub is installed.  I have gone all the way back to version 6.03.00003 and the issue persists.  When I unload either CoursePlay or the BigX pack the save game loads normally.  If they are activated together the loading screen stops and I get the error at the end of the log file "toolManager.lua:97: attempt to compare number with nil".  Just wanted to make you aware of this issue.
[log.txt](https://github.com/Courseplay/courseplay/files/5793433/log.txt)

**Comment by Tensuko** [comment]
Mod Issue.
