### ISSUE TITLE
[Enhancement] Lands for Racetrack/Spiral

### ISSUE THREAD

**Issue by mricher-git** [Courseplay/courseplay#6659]
Hi team, you gave me some really good advice a few weeks ago to use "skip lanes" or racetrack to optimize the turning at the end of a lane, which has really helped. I like to start my sowing machine before the combine has finished to get things done quicker, but the problem is, if I use racetrack for example, the sowing machine needs most, if not all of the field harvested before it can start, because of it's pattern, it will come very far over where the combine is still working.

That would make "lands" the best choice, but the issue is, unlike racetrack, it still does some tight turns (the first one of each land), since it's basically "reverse spiral. 

My enhancement request is: Can you add the "Number of rows per land" for all of the patterns: racetrack, spiral and "lands". I noticed they already use lands anyway, a racetrack pattern for example will create "lands" at 8 rows. This would then make the pattern "lands" a confusing name, so perhaps rename lands to "Reverse Spiral", and have the Number of Rows per land available to all patterns (except up/down of course where it would be pointless).

I'm sure this would be useful in many cases and hopefully not hard to implement since they all seem to use some form of lands internally anyway. My use case would be, I could slice my field up into 2 or 3 lands, and using racetrack, have nice wide turns as well. Once the combine or any fieldwork has completed the land, the next one behind it can start the next job without collision.

Thanks!

**Comment by pvaiko** [comment]
It's a bit more complicated than that, but makes sense, don't hold our breath.

**Comment by mricher-git** [comment]
Thanks for having a look, understandably nothing is as easy at it looks in course generation, every small job is a big job ;) *fingers-crossed*
