### ISSUE TITLE
[BUG] Mode 10 Modus Verdichten Funktioniert nicht

### ISSUE THREAD

**Issue by Tom20214** [Courseplay/courseplay#6661]
Moin! Seit der neusten Version funktioniert im mode 10 der Verdichten modus nicht es kommt ein LUA call stack  wenn man den Fahrer einstellen möchte.
![fsScreen_2021_01_11_13_30_59](https://user-images.githubusercontent.com/50717293/104182824-4f818e80-5411-11eb-902a-6a911608bfa1.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5795725/log.txt)

**Comment by Mannie313** [comment]
Geht das so ohne Schiebeschild.

MFG Mannie313

**Comment by Tom20214** [comment]
Der Modus Verdichten geht nur ohne Schiebeschild

**Comment by Tom20214** [comment]
http://courseplay.github.io/courseplay/en/manual/index.html#driveMode10
http://courseplay.github.io/courseplay/en/manual/index.html#hud_levelingSettings

**Comment by Tom20214** [comment]
@Tensuko  Da es in der neusten Version wieder funktioniert mach ich die issue jetzt zu.

**Comment by Tensuko** [comment]
TOP! Danke für die Rückmeldung :)
