### ISSUE TITLE
Silo bug. Blade taps all areas but does not level.

### ISSUE THREAD

**Issue by Gibbanator** [Courseplay/courseplay#6664]
here is a video on the problem.
https://youtu.be/wI9m0eCfQsQ

Taps all areas but does not level the chaff. Bunker is at 83%

It is set for leveling. If I change it to filling up than it taps left side constantly.

tried mannally moving chaff around but get same problems when I activate the course again.

**Comment by schwiti6190** [comment]
@Gibbanator First of all thanks for creating a video this is always the most helpfull option for us :) 
Sadly without the correct debug channel I will miss alot of necessary information, so if I could trouble you again with creating the video again, but with debug channel 10 activated and the console open, so I can see it live would be really helpfull for me :)

**Comment by Tensuko** [comment]
Try .00026 or higher and report

**Comment by Tensuko** [comment]
This one is fixed as we simply drive till the end.
