### ISSUE TITLE
CP findet den Weg unter Brücken nicht.

### ISSUE THREAD

**Issue by LamaiK** [Courseplay/courseplay#6665]
Bei normalem Strecken abfahren findet CP den Kurs unter Brücken nicht mehr. Sobald der Kurs wieder auf normalem Niveau ist funktioniert es wieder normal. Ist in SP und MP genau gleich.
Kurzes Video zum veranschaulichen des Problems. 
[Hier ist das Video etwas grösser.](https://workupload.com/file/rfYX9uJ7ppZ)

https://user-images.githubusercontent.com/70286270/104235231-fcc9c600-5454-11eb-9806-4cdbd9e83090.mp4

**Comment by Tensuko** [comment]
logfile ?
#5272

**Comment by LamaiK** [comment]
Hier die Log.
[log.txt](https://github.com/Courseplay/courseplay/files/5799611/log.txt)

**Comment by pvaiko** [comment]
"Nicht mehr"? Ist das neu? War das vorher kein Problem?

**Comment by LamaiK** [comment]
Vorher war das nicht so. Habe das in der 22 zum ersten Mal gesehen. 
Werde noch weitere Versionen testen und dann bescheid geben.

**Comment by pvaiko** [comment]
Welche Karte ist das?

**Comment by andreasthu** [comment]
Icg weiß das cp schon immer seine Linien nach dem Terrain ausrichtet.
Wäre das ein Problem wenn sie sich, ähnlich wie in autodrive, auch über Objekten mit Kollisionen ausrichten würden?
Lg
andreas

**Comment by LamaiK** [comment]
Ich musste weit zurück um die richtige Version zu finden.
Das Phänomen tritt erst ab denn Versionen v6.02.00004 auf. [Video](https://workupload.com/file/hsruY8kjCVL)
Bis zu Version v6.01.00399 tut es dies nicht. [Video](https://workupload.com/file/ZqHSrjmzyZT)
Auch ist der Effekt nur bei Bergfahrt so stark, bei Talfahrt ist es fast nicht zu sehen.
Betroffen scheinen nur die kleinen Traktoren zu sein Tests mit grösseren Traktoren ergaben das dies dort nicht zu sehen ist. [Video](https://workupload.com/file/RkGJD9n8pNq)
Das Ganze ist auf der Map LS19_Helvetia gemacht. DL [Hier](https://workupload.com/file/jQnSMjxye98). 
Alle [Logfiles](https://workupload.com/file/8ep38Yk6zRP).

**Comment by pvaiko** [comment]
LS19_Helvetia DL ist passwortgeschuetzt.

**Comment by LamaiK** [comment]
Sorry, hab ich vergessen PW ist [hier](https://forbidden-mods.de/filebase/file/16277-helvetia/).

**Comment by pvaiko** [comment]
Oh mann, das ist riesig, hast du ein savegame, habe keine Lust da hinzufahren :)

**Comment by andreasthu** [comment]
@pvaiko 
Ev hilft das hier:
https://github.com/sperrgebiet/FS19_Tardis
Einfach minimap mit 9 vergrößern,
Dann alt+T drücken und auf der minimap hinklicken. Schon ist man dort.
Lg
Andreas

**Comment by pvaiko** [comment]
Oh, und das ist nur bei Mode 2?

**Comment by andreasthu** [comment]
> @andreasthu super, danke.

kein problem, der mod ist zum Testen Gold wert
benutze auch den vehicleexplorer zum sortieren und parken, ebenfalls von sperrgebiet
https://github.com/sperrgebiet/FS19_VehicleExplorer
und wenn man beide verwendet, wird tardis in den vehicleexplorer integriert
lg
andreas

**Comment by Mike1977** [comment]
> 
> 
> Icg weiß das cp schon immer seine Linien nach dem Terrain ausrichtet.
> Wäre das ein Problem wenn sie sich, ähnlich wie in autodrive, auch über Objekten mit Kollisionen ausrichten würden?
> Lg
> andreas

Da es hier keine Antwort gab, würde ich das gerne nochmal anstoßen. Vor allem wenn man die Punkte nachbearbeiten möchte, ist das so ja extrem schwierig...

**Comment by pvaiko** [comment]
Sorry, mir ist es nicht ganz klar was das Problem ist, Kurse auf der Brücke zu editieren? Was heisst "über Objekten mit Kollisionen ausrichten"? Wir wollen nicht Kurse über Objekten haben oder?

**Comment by LamaiK** [comment]
@pvaiko
mod2 ist der Transport von A nach B oder? Kennte die mod nummern leider nicht.
Ich habe dies bei allen Fahrmodi gesehen, Drescher abtanken, nur Fahren, und beladen am Startpunkt.

**Comment by pvaiko** [comment]
@LamaiK hat sich inzwischen erledigt, ich pushe gleich ein neues Release

**Comment by LamaiK** [comment]
@pvaiko Danke dir, und dazu noch ein richtig dickes Dankeschön für CP ist für mich das Mastertool im LS. DANKE

**Comment by Mike1977** [comment]
> 
> 
> Sorry, mir ist es nicht ganz klar was das Problem ist, Kurse auf der Brücke zu editieren? 

Die Wegpunkte sollten auf der Straßenoberfläche sein, und nicht auf dem Terrain unter der Brücke. Zum einen wegen der übersichtlichkeit und zum anderen damit man die Wegpunkte auch bearbeiten kann. Wird ein Wegpunkt in einem Brückenpfeiler positioniert, kommt man nicht an ihn ran um ihn zu verschieben. Und davon abgesehen lassen sich die Punkte kaum verschieben, wenn man die Linie nicht auf der Straße sieht, sondern eben unter ihr auf dem Terrain.

>Was heisst "über Objekten mit Kollisionen ausrichten"? Wir wollen nicht Kurse über Objekten haben oder?

Doch, genau das sollte das Ziel sein. Wenn ich das richtig verstehe, muss man beim setzen der Punkte die Collision Mask der Objekte beachten. Hier ein Link der weiterhelfen könnte: https://github.com/Stephan-S/FS19_AutoDrive/pull/1753

**Comment by pvaiko** [comment]
> Doch, genau das sollte das Ziel sein.

Wenn du mit Objekte die Strasse meinst, ja, vielleicht. Ich weiss dass man es raycasten kann wie AD das macht, aber selbst das würde an diese Brücke nicht funktionieren (soweit ich das beurteilen kann) weil der Code die Strasse von 9 m über Grund nach unten sucht, was mit Objekten höher als 9 m nicht funktioniert. Weiss auch nicht was passiert wenn die Brücke über eine andere Strasse (und nicht die Bahn wie hier) führt.

Das Originalproblem sollte in dem näschsten Release behoben sein. Das Kurseditieren auf der Brücke ist momentan sehr niedrige Prio.

**Comment by andreasthu** [comment]
Super, danke, werde es auch mal testen
@pvaiko mit collisionen der objekte hab ich es eigentlich eh so gemeint, das die kurspunkte quasi auf der Strasse gesetzt werden sollten, und nicht unten am Terrain. Das mit den Kollisionen war von mir blöd ausgedrückt.
In Erlengrat z.b. gibt es viele solcher "Gebirgsstrassen" am Hang, wo das Terrain tiefer liegt. Da setzt CP die punkte eben unter Strasse und wenn man mit dem ingame Editor was ändern möchte findet man den Wegpunkt sehr schwer da er nicht sichtbar ist.
Genauso wenn die Brücke oben ist und man quasi unter der Brücke die punkte verschiebt.
Aber wenn das jetzt passt mit 0024 ist das eine Erleichterung beim ändern.
Lg
Andreas

**Comment by LamaiK** [comment]
Die Problematik wurde von @pvaiko gelöst somit könntet ihr dieses issu als gelöst markieren.
