### ISSUE TITLE
ClicktoSwitch ignores AutoDrive hud

### ISSUE THREAD

**Issue by mricher-git** [Courseplay/courseplay#6666]
Hi, thanks for the recent fix to clickToSwitch for MP and the addition of being able to click on trailers/attachments.

Quality of life, mod interoperability request. It's amazing how often I'm clicking to select something in the AutoDrive hud and there is a vehicle underneath the AD hud which then activates clickToSwitch. I'm not sure how much you are willing to go for mod interoperability, but it would be a nice QoL enhancement if you could occlude the area of the AutoDrive hud from activating the clickToSwitch.

I just noticed this comment in the code:
```
-- should we switch vehicles? Removed condition: vehicle.cp.mouseCursorActive <- is it important that it have to be CP mouseCursor ?
if courseplay.globalSettings.clickToSwitch:is(true) and vehicle:getIsEntered() and not mouseIsInHudArea and
mouseButton == courseplay.inputBindings.mouse.primaryButtonId then
	clickToSwitch:updateMouseState(vehicle, posX, posY, isDown, isUp, mouseButton)
end
```

I would say yes, either check for vehicle.cp.mouseCursorActive or add a new mouseIsInHudArea for AD ;) I have CP on right mouse, AD on middle mouse like most people by default, adding vehicle.cp.mouseCursorActive would certainly solve the issue but a special mouseIsInHudArea for AD would be even better, because it is becoming annoying when we see the mouse cursor but we forget if we are in CP or AD context.

**Comment by Tensuko** [comment]
Not going to do this for some reasons.
