### ISSUE TITLE
how to fix error code

### ISSUE THREAD

**Issue by CarlXVIGustav** [Courseplay/courseplay#6671]
How do I fix the error code that says (Missing descVersion attribute) for example and how do I fix (Failed to open xml file)

**Comment by candymant** [comment]
failed to open the XML file. this is when the path to the XML file mentioned in the error is not correct.
missing desc version is probably the moddesc.xml is missing or the zip file that contains a map before the actual files. if you open the zip file then you must see the moddesc.xml directly and not a file map.

**Comment by Tensuko** [comment]
No idea what you talking about... logfile ? is there even a CP Error ?

**Comment by CarlXVIGustav** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5814272/log.txt)

**Comment by Tensuko** [comment]
You are wrong here, this is only Courseplay related GitHub Side and I haven't even found 'courseplay' in your log.
This attribute is simple wrong mods, like not unpacked, wrong created and stuff.
Delete them or google for it on what to do.
