### ISSUE TITLE
Harvester missing target on trailer

### ISSUE THREAD

**Issue by MartinGrisotto** [Courseplay/courseplay#6673]
For some reason harvester is missing the trailer, i have to manually correct vertical position to +0,5m

![image](https://user-images.githubusercontent.com/10392883/104583602-9c5ba400-5661-11eb-9c9a-31596363bf5b.png)

**Comment by candymant** [comment]
why double issue.

**Comment by MartinGrisotto** [comment]
> why double issue.

I got 404 when submitting, didn't know it was posted

**Comment by MartinGrisotto** [comment]
[log.zip](https://github.com/Courseplay/courseplay/files/5814064/log.zip)

**Comment by Tensuko** [comment]
Thats why we have offsets to correct position.
