### ISSUE TITLE
Course Editor "Delete to Start" funktioniert nicht mehr

### ISSUE THREAD

**Issue by LamaiK** [Courseplay/courseplay#6675]
Seit der v6.02.00075 funktioniert im Course Editor das Löchen von Wegpunkte zum Start nicht mehr. 
Standart Tasten sind lctrl+ü. auch dass umlegen auf andere Tasten bleibt wirkungslos.
Bei den v6.02.00074 und älter funktioniert es einwandfrei.
Der Fehler tritt bei jeder Karte auf, Vanilla und Modmaps.

[log.txt](https://github.com/Courseplay/courseplay/files/5816691/log.txt)

**Comment by Tensuko** [comment]
Bitte suche benutzen, danke #6297
