### ISSUE TITLE
CombineUnloadManager.lua

### ISSUE THREAD

**Issue by KOTOGATO** [Courseplay/courseplay#6678]
[log.txt](https://github.com/Courseplay/courseplay/files/5822199/log.txt)
Error: Running LUA method 'update'.
D:/FS19MODS/FS19_Courseplay/CombineUnloadManager.lua:57: attempt to index field 'cp' (a nil value)
I try to start game without other scripts which I added recently but the effect was the same that is, the entire log strewn with this error, in addition, it is impossible to do anything in the game because once the button is clicked it locks up and stops working and the only option is to turn off the game using the console

**Comment by Tensuko** [comment]
attach complete logfile pls https://github.com/Courseplay/courseplay/wiki

**Comment by KOTOGATO** [comment]
[Uploading log.txt…]()

**Comment by KOTOGATO** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5823363/log.txt)

**Comment by Tensuko** [comment]
How did you test it without any script ?
All mods removed from mods Folder + new savegame ?
Doubt it will have the same Error.

But it might be couse of bulkbuy, did you try to buy something in bulk in the shop ?

**Comment by KOTOGATO** [comment]
yes I buy with bulk buy but I test without and i get the same problem

**Comment by KOTOGATO** [comment]
when I select only courseplay i don't have this problem
