### ISSUE TITLE
mode 3

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/courseplay#6681]
Hello,

I have been using mode 3 for a few days for all my harvests (cereals, alfalfa silage, grass silage, corn silage ...) but I am having some problems:
1) In grass and alfalfa fields, the tractor follows the forage harvester behind. He never puts himself on the side (photo1) (I know the problem is known). But when the tractor is loaded, it does not back up enough and gets stuck behind the forage harvester. (photo 2)
2) If I activate the option "avoid crops" I have a big drop in FPS (photo 3 and 4). if I deactivate this option, I have less drop in FPS, but the tractor will not stay in the field and above all, it systematically rushes into the forage harvester to leave to unload, once it is full (photo 5 and 6 )
Ideally, if the "avoid crops" option is deactivated, the tractor should start to the left and not to the right, or else it should move back several meters.
[log.txt](https://github.com/Courseplay/courseplay/files/5822394/log.txt)

![image](https://user-images.githubusercontent.com/36656729/104765907-f6e02780-5769-11eb-83e2-c09fb9a56471.png)
![image](https://user-images.githubusercontent.com/36656729/104765924-fcd60880-5769-11eb-9f6e-dddb863fce19.png)
![image](https://user-images.githubusercontent.com/36656729/104765978-111a0580-576a-11eb-8e8e-02ae64e7cc20.png)
![image](https://user-images.githubusercontent.com/36656729/104766007-2000b800-576a-11eb-8177-c7a0ac63b08c.png)
![image](https://user-images.githubusercontent.com/36656729/104766074-3e66b380-576a-11eb-8657-9de4913d01b9.png)
![image](https://user-images.githubusercontent.com/36656729/104766090-44f52b00-576a-11eb-8795-a6199c24d42e.png)

**Comment by Tensuko** [comment]
You have 2 total different things here, keep avoid fruit on and chopping grass is another problem, #5470

**Comment by Crinouche** [comment]
@Tensuko you close the post, but you don't answer the question, especially problem 2, and that's a shame. I deduce that it is useless to inform you of the problems which one meets!

**Comment by Tensuko** [comment]
> keep avoid fruit on

I did answer the question! The 'FPS' drop is Pathfinder working on getting a path, nothing new.

**Comment by Tensuko** [comment]
> I deduce that it is useless to inform you of the problems which one meets!

You report 2 things:
- One is a known Issue and a Duplicate, use the search function.
- You expect a direct path to consider Objects without the Pathfinder, won't work. Thats why we have the Pathfinder.

A bit of yearch and you would know that this is all nothing new to us.
