### ISSUE TITLE
Bunker tractors slipping issue

### ISSUE THREAD

**Issue by Gibbanator** [Courseplay/courseplay#6682]
With the new update with the bunker leveling the bunker leveling is so much better. No more tapping but a new issue has occurred. CoursePlay Bunker Leveling, Tractor with blade, the constant slipping of Tractor with blade. Does not correct or move forward when unable to move back any further. 

Looks as if the blade stops raising, not allowing continuing leveling.  Happens each attempt and does not correct when restarting course.

Video:
https://youtu.be/mTQR1udGyCk

**Comment by Tensuko** [comment]
Video not available and more updates soon.

**Comment by Gibbanator** [comment]
https://www.youtube.com/watch?v=mTQR1udGyCk&feature=youtu.be

**Comment by Tensuko** [comment]
Video is Private...
You have to set it on 'not listed' and not more :)

**Comment by Gibbanator** [comment]
Looks like I did not finish the process of publishing the video.. It should work now.

**Comment by Tensuko** [comment]
Will have a fix for this soon.

**Comment by Tensuko** [comment]
Try .00026 or higher and report

**Comment by Tensuko** [comment]
Fixed and will have some more improovement.
