### ISSUE TITLE
3 or more combines not work in convoy

### ISSUE THREAD

**Issue by garo73** [Courseplay/courseplay#6686]
First of all, thanks for the work you are doing and I apologize if this question has already been raised but I have not found anything! The problem: when I try to make 3 or more combines work in convoy, only the first 2 follow the path, the others run randomly in the field and start from random points. I have done several tests and I have the same effect with various combines, various maps, various settings and even with only the game and no mods installed! p.s. sorry my english, i'm italian and i use google translate!

**Comment by Tensuko** [comment]
Your course startpoint is in Corner, this won't work.
Place your start point away from the Corner and it should run smoothly.

**Comment by garo73** [comment]
Thanks, i try it!
