### ISSUE TITLE
[question] Do the forage harvesters now work on grass?

### ISSUE THREAD

**Issue by djnekkid** [Courseplay/courseplay#6687]
The last time i tested, did the forage harvester not work with grass fields. Atleast not properly, as the carts simply wanted to follow the harvester behind, and not from the side properly.

Or are there some 'tricks' to get them to work?

**Comment by Tensuko** [comment]
A simple search and you could answer it yourself.... #5470

**Comment by djnekkid** [comment]
I did a search, and #5470 is "a year old" :)
Perhaps there were an update to that :)
