### ISSUE TITLE
Spritze/Tieflockerer Problem

### ISSUE THREAD

**Issue by KeineEndeDerLegende** [Courseplay/courseplay#6690]
Also wir spielen auf Bergisch Land Map und folgende Problem egal wie ich einstelle und er wendet nicht im Feld und er steckt mit seiner Spritze am Baum fest genauso mit 8m Tieflockerer (Agrisem Cultiplown Platinum 8m). 
Pathfinder darf Rückwärts fahren ist aktiv und passiert nix.. Nur normale Grubber und Sähmaschine ist alles super.. es wäre super wenn der Spritze und 8m Tieflockerer auch im Feld wenden statt aus dem Feld wendet..

Lg Chris

**Comment by Tensuko** [comment]
> egal wie ich einstelle und er wendet nicht im Feld

Das ist immer eine gewagte Aussage. Es gibt viele Faktorne, Feld, Feldkurs, das Gerät selber...

Und Spritzen und Tiefenlockerer werden auf dem Feld, es liegt aber an den einzelnen Modellen.
Bilder und logfile mit debugchannel 12 und 14 helfen.

**Comment by KeineEndeDerLegende** [comment]
Hier ist logdatei: [log.txt](https://github.com/Courseplay/courseplay/files/5831948/log.txt)
 Hier sind paar Bilder 
![fsScreen_2021_01_18_17_33_27](https://user-images.githubusercontent.com/70626116/104952604-1cb53880-59c5-11eb-9cae-52ef587bfd64.png)
![fsScreen_2021_01_18_19_39_19](https://user-images.githubusercontent.com/70626116/104952629-276fcd80-59c5-11eb-9c02-02dc47f248e7.png) 

Er wendet trotzdem zu weit nach außen das er den Arm am Baum hängen bleibt..

**Comment by KeineEndeDerLegende** [comment]
Tieflockerer nur diese!
Weitere Logdatei: 
[log.txt](https://github.com/Courseplay/courseplay/files/5831958/log.txt)

Bilder: 
![fsScreen_2021_01_18_19_46_28](https://user-images.githubusercontent.com/70626116/104953091-0cea2400-59c6-11eb-8d28-710f47228c7b.png)

![fsScreen_2021_01_18_19_46_41](https://user-images.githubusercontent.com/70626116/104953115-1a9fa980-59c6-11eb-8ff9-144492cfc110.png)
 
Das gleiche Nur diese Lockerer wendet nicht im Feld..

**Comment by 60erjonny** [comment]
Hallo

Wie beginnst du die Kurse , mit dem Vorgewende?
Bei manchen Felden, sind da min. 3 nötig.
Ich fange aber bei solchen Arbeiten, immer mit den Feldreihen an...

**Comment by KeineEndeDerLegende** [comment]
In Realität bei Düngen und spritzen fängt immer mit Vorgewende an! Mein Bruder ist selber Bauer und er sagt auch. Beim ansäen oder Grubber oder Pflügen immer zuerst feldreihen und dann vorgewende wegen bodenverdichtung. Drum spiele ich auch so wie möglich Realität zu halten

**Comment by 60erjonny** [comment]
Hallo

Arbeitest du beim Dünger und Spritzen mit Fahrgassen...?

**Comment by KeineEndeDerLegende** [comment]
Ja wenn ich alleine mache ohne Courseplay. Courseplay nutze ich beim spritzen und düngen für Verträge wenn ich mal Geld brauche oder Arbeit brauche

**Comment by KeineEndeDerLegende** [comment]
Aber mein Kollege schimpft immer wenn der Spritze immer am Baum hängen bleiben. Er nutzt viel Courseplay.

**Comment by 60erjonny** [comment]
Ok, jeder soll so spielen wie er will, meinte ja nur.
Sorry, ist hier jetzt wohl zuviel OT...

**Comment by Tensuko** [comment]
Gut damit wäre das geklärt, ich räume hier eben auf.

**Comment by pvaiko** [comment]
Der Tieflockerer wird mit #6684 behoben, der ist extra als non-reversible konfiguriert, aber jetzt scheint es zu funktionieren.

**Comment by KeineEndeDerLegende** [comment]
Okay perfekt.

**Comment by pvaiko** [comment]
Das mit dem Sprayer ist ein Bug, aber dürfte nicht passieren wenn du keine Turns auf dem Vorgewende verwendest (oder vernünftig in der Feldmitte anfängst statt auf dem Vorgewende)

**Comment by KeineEndeDerLegende** [comment]
okayy wir sind halt gewohnt das wir erst vorgewende und dann feldreihen.. wenn nicht hilft ist auch nicht schlimm da ich anderen Mods des Spritzes die Arme Kollision entfernen kann..

**Comment by KeineEndeDerLegende** [comment]
Mach dir keinen Druck und lass dir zeit den Bug zu beheben.. 👍
