### ISSUE TITLE
Issue with modhubs Big X forage harvester

### ISSUE THREAD

**Issue by AdamLundberg** [Courseplay/courseplay#6691]
[Log](https://gist.github.com/AdamLundberg/37c81850a05fe05f26354b505490215f)

There is an issue with courseplay v6.03.00025 and the [Big X](https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=179845&title=fs2019) on the modhub. When courseplay is enabled the Big X 3D model won't show up in the shop.

The log throws these errors:
- Error: Running LUA method 'loadSharedI3DFileFinished'
- FarmingSimulator2019/mods/FS19_Courseplay/toolManager.lua:110: attempt to compare number with nil

![Screenshot (7)](https://user-images.githubusercontent.com/60877124/104943026-71e94e00-59b5-11eb-8922-06f08c8882c6.png)

**Comment by Tensuko** [comment]
I know this Mod.
It is a Mod Issue.
