### ISSUE TITLE
ingame editor - how to move bottom point ?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#6692]
Hallo
manchmal habe ich bei Feldbearbeitungskursen die Situation, das zwei Kurspunkte übereinander sind:
![fsScreen_2021_01_19_11_13_33](https://user-images.githubusercontent.com/24860501/105020779-0a301300-5a48-11eb-90a9-4188f4c1929a.png)
wie verschiebe ich nun ingame im editor den untersten Punkt?
wenn ich mit der Maus drübergehe, wird mir nur der Punkt angezeigt der die niedrigste Nummer hat.
ja klar, den kann ich verschieben, dann den unteren kurspunkt verschieben und den "oberen" wieder an die vorherige Stelle zurückschieben.
geht das auch anders?
lg
andreas
[courseStorage0006.txt](https://github.com/Courseplay/courseplay/files/5835222/courseStorage0006.txt)

**Comment by Tensuko** [comment]
Nein, geht nicht anders.
