### ISSUE TITLE
Compas degrees issue

### ISSUE THREAD

**Issue by mathat121** [Courseplay/courseplay#6693]
When generating field work paths and using the compas degrees for the starting point. When selecting to start the path in the north east corner of the field. course play actually starts the path in the south west corner. Is there anything i am doing wrong or can do to solve this?
using FS19 playing on the giants Felsbrunn map

**Comment by Tensuko** [comment]
logfile with channel 7 active when start create the course and a screenshot of your settings pls.

**Comment by Tensuko** [comment]
Working as intended, keep in mind that those options can be overwritten when use some other options like headland, start on headland or up/down rows and stuff like that.
![fsScreen_2021_01_27_15_21_20](https://user-images.githubusercontent.com/27344744/106004312-6089fb00-60b3-11eb-8dbe-a1f55db472fa.png)
![fsScreen_2021_01_27_15_21_17](https://user-images.githubusercontent.com/27344744/106004319-62ec5500-60b3-11eb-8021-8864d74fe2bf.png)
![fsScreen_2021_01_27_15_21_15](https://user-images.githubusercontent.com/27344744/106004327-64b61880-60b3-11eb-8102-5ba7b45e4ae6.png)
![fsScreen_2021_01_27_15_21_08](https://user-images.githubusercontent.com/27344744/106004331-667fdc00-60b3-11eb-8248-ddca5e559a71.png)
