### ISSUE TITLE
Zig Zag driving

### ISSUE THREAD

**Issue by hottheadliberty** [Courseplay/courseplay#6696]
So after I generate a course on my field everything runs fine after it does the headlands and the first row, but after making the turn at the end of the first row it makes it wide and then starts to zig-zag slowly across the field and then just takes off in a straight line in whatever direction it happens to be facing.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by hottheadliberty** [comment]
https://pastebin.com/4T0HFEcY 

CP version: 6.03.00025

**Comment by Tensuko** [comment]
This is not a complete logfile and screenshots might help too

**Comment by hottheadliberty** [comment]
with the instructions that you pointed me to, that is the only log file I found, I will try to get pictures but a video might be better. is a youtube link ok?

**Comment by Tensuko** [comment]
YT Video is even better so yes :)

**Comment by hottheadliberty** [comment]
I have no idea what happened but it started working on its own out of nowhere. i do have a new issue but i will open another issue for that since it is very different from this one.

**Comment by Tensuko** [comment]
Closing this one then
