### ISSUE TITLE
Convoy between two different courses

### ISSUE THREAD

**Issue by xavierdemoor** [Courseplay/courseplay#6698]
Hi,

I would like to know if, and how, it's possible to make a convoy between two different courses. I already had this working but without knowing how I did it. It just happened.

What I would like to do, is having a course with combines, followed by a course with seeders, with a minimal convoy distance between the last combine and the first seeder.

Like I said, I already had that between a fertlize course (in front, single vehicle) and a weed course (3 vehicles), but I didn't find what I did to have this result.

Thank you in advance.

**Comment by Tensuko** [comment]
That is not possible, as convoy check if got same course.
