### ISSUE TITLE
Allgemeine Hilfe und Fragen

### ISSUE THREAD

**Issue by Topper-86** [Courseplay/courseplay#6702]
Guten Tag,

ich hab mich vor kurzem für LS19 endschieden da ich gesehen habe das auch CP verfügbar ist.
Da ich sehr viel LS17 mit CP gespielt habe und dort alleine eine 4fach Map bewirtschaftet habe wollte ich das bei LS19 auch so machen, musste aber feststellen das mir dafür bei CP6 einige Funktionen fehlen.

Bei LS17 waren meine Course für's Drillen und Düngen so angelegt das der CP-Fahrer selbstständig Saatgut und Dünger am Hof auffüllt und dann am Feld weiter macht bis er das Ende des Courses erreicht hat, danach habe ich den CP-Fahrer über die Schaltfläche "sofort abfahren" über den Nachfüllcourse zum Hof zurückfahren lassen und habe ihm gesagt es soll "am nächsten Trigger warten", so das er direkt am Hof bereitsteht und zum nächsten Feld fahren kann.

Bei LS19 gibt es zwar noch die Schaltfläche "Sofort abfahren" allergings fährt der Fahrer nach anklicken nur noch ziellos in der Gegend rum und fährt nicht zum Nachfüllcourse, die Schaltfläche warten am Wegpunkt o. Trigger ist garnicht mehr da.

Meine Frage dazu ist ob diese Funktion wieder reinkommt da ich in alten Videos zu CP6 gesehen habe das es dass gab das der Fahrer an einem Trigger warten soll.

Desweitern ist mir aufgefallen das Fahrzeuge die Drescher abtanken sollen den Dreschen nicht finden wenn der Gaintshelfer oder der Spieler selber den Drescher fahren und sich teilweise (nicht immer) Kauderwelsch zusammenfahren und auch nicht darauf reagiert wenn man ihnen aus dem Dreschen heraus sagt er soll "Sofort abfahren" wenn sie z.B. im Weg des Dreschers stehen.

Mir ist bewusst das CP6 wohl noch ne Beta ist allerdings hat bei CP5 super funktioniert.

MfG Topper

**Comment by Tensuko** [comment]
> Bei LS19 gibt es zwar noch die Schaltfläche "Sofort abfahren" allergings fährt der Fahrer nach anklicken nur noch ziellos in der Gegend rum und fährt nicht zum Nachfüllcourse, die Schaltfläche warten am Wegpunkt o. Trigger ist garnicht mehr da.

Ziellos umher fährt kein Fahrer. Die funktion warten am letzten Wegpunkt oder Trigger ist nicht mehr wählbar sondern festgelegt, damit wir genau sagen können wie welcher Mode funktionieren soll und uns keine ungewöhnlichen Probleme dazwischen funken.

> Meine Frage dazu ist ob diese Funktion wieder reinkommt da ich in alten Videos zu CP6 gesehen habe das es dass gab das der Fahrer an einem Trigger warten soll.

Ist bisher nicht geplant, damit wir weniger Probleme haben.

> Desweitern ist mir aufgefallen das Fahrzeuge die Drescher abtanken sollen den Dreschen nicht finden wenn der Gaintshelfer oder der Spieler selber den Drescher fahren

Das geht auch nicht mehr, siehe #5272 und Wiki Page.


> und sich teilweise (nicht immer) Kauderwelsch zusammenfahren und auch nicht darauf reagiert wenn man ihnen aus dem Dreschen heraus sagt er soll "Sofort abfahren" wenn sie z.B. im Weg des Dreschers stehen.

Das kommt jetzt auf die Version und deine Einstellungen drauf an, was und warum das passiert. Sofort Abfahren funktioniert nach wie vor, hilft aber kaum wenn sie sich bereits verknotet haben. Auch hier #5272 und Wiki Page.


> Mir ist bewusst das CP6 wohl noch ne Beta ist allerdings hat bei CP5 super funktioniert.

Ich bin kein Freund von Vergleichen wie 'aber früher ging das doch'...
Früher hatten wir einen anderen LS...
Früher hatten wir andere Funktionen...

CP Entwickelt sich, wir räumen CP vom Code her auf und das manches dann mal nicht so funktioniert wie früher ist dann so.
Dafür hatten wir früher auch einige andere Funktionen nicht, die wir nun haben + diverse neue Möglichkeiten.

Die englische Seite sollte recht aktuell sein:
http://courseplay.github.io/courseplay/en/index.html

**Comment by Topper-86** [comment]
Danke für die schnelle Antwort und ich wollte nicht den Eindruck erwecken das "früher alles besser war". Die neuen Funktionen das ein Drescher so anhält das der Abtanker nicht mehr ins Getreide fahren muss oder die vielen Möglichkeiten ein Feldkurs zu erstellen sind echt Top.
Allerdings steh ich grad etwas auf dem Schlauch... ich hab das jetzt so verstanden das ich alle CP-Fahrer die mit nem Feld fertig sind manuell zum Hof zurückfahren muss?

**Comment by Tensuko** [comment]
Wenn du so fragst: Nein :)
Solange du einen Kurs vom Feld zum Hof hast, brauchst du doch nur deinen Fahrer stoppen, Kurs rauswerfen, den Kurs vom Feld zum Hof laden und los schicken mit dem Modus 5 (welcher IMMER am letzten Wegpunkt stoppt).
Es mag für dein Vorhaben etwas aufwendiger sein als damals einfach einen klick zu tätigen, aber es ist nach wie vor möglich.

Wenn dir das zu Problematisch ist, dann schau mal bei den Kollegen von AutoDrive vorbei.
Hast du ein AD Netzwerk und entsprechende Ziele, kannst du AD dazu nutzen einen Fahrer zu einem Feld zu schicken und CP dort automatisch mit der Arbeit beginnen lassen und auch nach getaner Arbeit wieder zurück zu einem Parkplatz (damit kenne ich mich allerdings nicht aus).

Tutorials dazu findest du bei Mario Hirschfeld:
https://www.youtube.com/channel/UCz68SqJWpicCddxl5gZzVNQ

**Comment by Topper-86** [comment]
Danke nochmal... bin auch schon auf AD gekommen und bin schon Tutorial gucken.

PS: macht weiter so... ohne CP wäre ich wahrscheinlich nie so lange beim LS geblieben. ;)

**Comment by Tensuko** [comment]
Danke und ja wir arbeiten auch weiter an CP :)
Wer weis was die Zukunft noch so mit sich bringt ;)
