### ISSUE TITLE
Überführung Permanent fahren lassen

### ISSUE THREAD

**Issue by Lars-LS17** [Courseplay/courseplay#6703]
Hallo Zusammen,

ich habe die aktuelle Version 6.xx.00025. 
Ich nutze die Überführung immer, um das Silo zu verdichten.
Mit dieser Version fährt der den Kurs aber nur noch einmal und bleibt dann beim letzten WegPunkt stehen.
Hat sich da etwas geändert und kann man das wieder rückgänig machen?
![fsScreen_2021_01_21_20_40_56](https://user-images.githubusercontent.com/31773176/105403587-35258d00-5c29-11eb-9b82-88522be93a94.png)

Oder gibt es von CP jetzt eine Alternative, wie ich mein Fahrsilo am Ende verdichten kann?

**Comment by Tensuko** [comment]
Modus 10 http://courseplay.github.io/courseplay/en/manual/index.html#driveMode10

**Comment by Tensuko** [comment]
> Hat sich da etwas geändert und kann man das wieder rückgänig machen?

Es hat sich was geändert und nein das machen wir nicht rückgängig, da wir für sowas einen Modus haben.
