### ISSUE TITLE
Issue without any useful description

### ISSUE THREAD

**Issue by honza1231** [Courseplay/courseplay#6706]
when I open courseplay it cuts me off and I can't do anything to turn off or switch bookmarks

**Comment by Tensuko** [comment]
logfile ?

**Comment by honza1231** [comment]
and where can i find the log

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by honza1231** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5860308/log.txt)

**Comment by Tensuko** [comment]
Well, your logfile just tells you you should update: (Version: 6.03.00024) FS19_Courseplay
https://github.com/Courseplay/courseplay/releases

I can only guess what you try to say, but when you open CP and your game hangs up, it might be a mod Issue of one of your Vehicles.
Else I would need the logfile when the Error happens. Your logfile is Error free (as far as I can tell)

**Comment by honza1231** [comment]
but i have version 6.03.00027 
and i have video : https://ctrlv.tv/hJF6

**Comment by pvaiko** [comment]
There's nothing wrong with Courseplay, you'll have to attach an implement if you want to use it. 

Also recommend looking at the manual or search for videos explaining how to use it.

**Comment by honza1231** [comment]
I still can't use it even if I have something connected
