### ISSUE TITLE
lagg issue

### ISSUE THREAD

**Issue by hackerstbernard** [Courseplay/courseplay#6709]
im haveing lagg issue when combine fills up and need to be unloaded fps drops down to 3-2fps have tried diff combines and maps same issues I'm also running i9 5gz 80gb memory with geforce 2070super so my specs aren't to shabby

**Comment by Tensuko** [comment]
This is not a lag, that is an fps drop due ti limited Engine. You can have the best machine, the Engine is the limit.
We know this and can't disable this, just improove the Pathinfer.
