### ISSUE TITLE
Abbruch Feldarbeit

### ISSUE THREAD

**Issue by Kartracer390** [Courseplay/courseplay#6713]
Hallo,
Courseplay bricht das Sähen ab, wenn der Punkt erreicht ist, wo der Wechsel von Feldreihen auf Vorgewenden ist.(6.03.00027 )
Mit 6.03.00026 funktioniert der gleich Kurs noch.
Auch neu erstellen hilft nichts.

**Comment by pvaiko** [comment]
Meinst du ein Log würde helfen?

**Comment by Kartracer390** [comment]
https://gist.github.com/Kartracer390/3ba8b3258504d3c59e87f7d8d8f7f3ed

**Comment by Kartracer390** [comment]
Hoffe es passt wie ich es reingestellt habe
Müsste der letzte Eintrag sein

**Comment by 60erjonny** [comment]
Hallo
habe ich auch so festgestellt, so ähnlich wie bei #6245/#6246...
