### ISSUE TITLE
Mehrere Fehler, Fruchtumfahrung wird ignoriert und ...

### ISSUE THREAD

**Issue by TommyGFX** [Courseplay/courseplay#6714]
![fsScreen_2021_01_23_20_30_25](https://user-images.githubusercontent.com/492001/105612552-41425380-5dbd-11eb-9637-040edc4ea9d6.png)
Hier fährt er durchs Feld trotz aktivierter Fruchtumfahrung.

![fsScreen_2021_01_23_20_39_06](https://user-images.githubusercontent.com/492001/105612560-4b645200-5dbd-11eb-948b-653b508fe68b.png)
Vom Drescher der Arm wird nicht komplett ausgefahren.

![fsScreen_2021_01_23_20_40_25](https://user-images.githubusercontent.com/492001/105612573-5b7c3180-5dbd-11eb-9a03-e65f7ddbaac2.png)
Hier steht er rum obwohl ja zusehen ist, das der andere Drescher voll ist.
Man sieht auch das er am berechnen ist.
Die Frames gehen in den Keller.

Hier die Log dazu:
[log.txt](https://github.com/Courseplay/courseplay/files/5860952/log.txt)

Und nun noch eine kleine Anregung:
Wenn man Fruchtumfahrung aus hat, wäre es schon wenn der Abfahrer nach dem abtanken beim Drescher nicht in der Frucht stehen bleibt.
Und die Abfahrer fahren ob sofort rechts vom Drescher weg, so das sie den Drescher rumziehen.

**Comment by Tensuko** [comment]
> Und nun noch eine kleine Anregung:
> Wenn man Fruchtumfahrung aus hat, wäre es schon wenn der Abfahrer nach dem abtanken beim Drescher nicht in der Frucht stehen bleibt.
> Und die Abfahrer fahren ob sofort rechts vom Drescher weg, so das sie den Drescher rumziehen.

Deswegen Fruchtumfahrung an.



> Hier steht er rum obwohl ja zusehen ist, das der andere Drescher voll ist.
> Man sieht auch das er am berechnen ist.

Hast es dir selbst beantwortet, er berechent den Weg.



> Vom Drescher der Arm wird nicht komplett ausgefahren.

Original Claas DLC ? Mod ?

**Comment by pvaiko** [comment]
Wenn CP nach 40000 Iterationen keinen Pfad findet dann fährt er durch die Frucht. 

Welche Map ist das? Wie gross ist dieser Feld?

**Comment by pvaiko** [comment]
Andere Frage: hat dieser Kurs einen Vorgewende?

**Comment by rohne83** [comment]
> Vom Drescher der Arm wird nicht komplett ausgefahren.

das Rohr wird zusammen mit dem Drescher und dem Korntank ausgeklappt, bevor überhaupt mit der Arbeit begonnen wird. Ein- und Ausfahren des Rohres zum Abtanken hat darauf keinen Einfluss mehr. Frage mich eher, wie er es überhaupt hinbekommen hat, dass der Drescher quasi im Straßenmodus auf dem Feld arbeitet...

**Comment by Dan-Gecko** [comment]
> > Wenn man Fruchtumfahrung aus hat, wäre es schon wenn der Abfahrer nach dem abtanken beim Drescher nicht in der Frucht stehen bleibt.
> > Und die Abfahrer fahren ob sofort rechts vom Drescher weg, so das sie den Drescher rumziehen.
> 
> Deswegen Fruchtumfahrung an.

Hierzu habe ich auch grundsätzlich schlechte Erfahrungen gemacht. Bei der Ernte mit geringer Arbeitsbreite, zb. Rüben oder Kartoffeln bleibt der Transporter/LKW beim abtanken GRUNDSÄTZLICH im Feld stehen (wenn er auf der Fruchtseite abgetankt hat) und blockiert den ankommenden Ernter bei dessen nächster Runde. Also muss der Transporter/LKW jedes mal manuell aus der Route des Ernters gefahren werden. Der einzige (aber doch recht unschöne) Work around den ich gefunden habe, ist das Feld alle 3 Linie bearbeiten zu lassen. So ist genug Platz für den blockierenden Transporter/LKW.

**Comment by Tensuko** [comment]
Was ist der Status hier?
Vermehrt genutzt auf großen Maps, das Rohr wurde immer ausgefahren, Fruchtumfahrung ist geklärt.

Warum er da so lange berechnet, da hilft nur ein logfile mit channel 4, 7, 12 und 14.

**Comment by Tensuko** [comment]
Besteht noch Interesse daran, den Fall weiter zu untersuchen ? Wenn ja logfile, mit den genannten channels, ansonsten würde ich das Issue gerne zu machen...

**Comment by TommyGFX** [comment]
habe die map leider nicht mehr so.

mein PC war abgestürtzt und ich hatte keine sicherung von der Map

Kann also erstmal zu

**Comment by Tensuko** [comment]
ok
