### ISSUE TITLE
Abfahrer findet Weg aus Keilsilo nicht

### ISSUE THREAD

**Issue by Kartracer390** [Courseplay/courseplay#6716]
Hallo,
wie auf dem Video zu sehen fährt der Abfahrer nicht den vorgegebenen Weg aus den Silo raus sondern möchte einen Kreis zu einem  weiter hinten liegenden Wegpunkt fahren.
Falls ich einen Fehler beim Kurs gemacht habe freue ich mich über Tipps.
[log.txt](https://github.com/Courseplay/courseplay/files/5861211/log.txt)

https://www.youtube.com/watch?v=vGa2ZlocCgw

Edit: Das Problem tritt vermehrt auf, seit dem das Silo zur Hälfte voll ist. Als das Silo leer war lief alles perfekt

Version:6.03.00028

**Comment by Tensuko** [comment]
Da ich leider nicht sehe was für Wegpunkte du gesetzt hast (WP Anzeigen istn icht das Auge, sondern im HUD die 3 Punkte unter Settings).
Korrekt ist, als letzten WP 'Hier abladen' und dann Rückwärts wieder ausschalten. Sollte das dann noch passieren, Editor an und schau ob bei dem hier abladen WP noch ein andere WP ist und den dann löschen.

**Comment by Kartracer390** [comment]
Aktuell fahre ich nur rückwärts rein am ende des Silos schalte ich dann wieder auf vorwärts um.
Probiere es nochmal wie du gemeint hast mit dem Ablade Punkt

**Comment by Kartracer390** [comment]
Scheint zu funktionieren schließe den Fehler dann mal und teste morgen nochmal ausgiebig 
Danke für deine Hilfe
