### ISSUE TITLE
game wont load with cp installed

### ISSUE THREAD

**Issue by hackerstbernard** [Courseplay/courseplay#6718]
ive updated to the latest cp and game wont load any more have taking it back out and it loads 
![20210123_234806 jpgcp](https://user-images.githubusercontent.com/25061165/105617400-e49f6280-5dd5-11eb-818e-823c0db77fc1.jpg)

**Comment by Tensuko** [comment]
logfile ?!?!?!?!?!?!?

**Comment by hackerstbernard** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5861382/log.txt)

**Comment by Tensuko** [comment]
In your logfile is not even courseplay installed and it is full of callstacks.
I would say you clean up your mods folder 1st
