### ISSUE TITLE
issue: Wendefahrt bei Feldbearbeitung

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#6720]
Hallo Leute
derzeit wendet CP bei Feldern mit Schrägem Vorgewende ja im 0/90/180/270 grad Muster:
(dabei ergeben sich manchmal brenzlige Situationen)
![fsScreen_2021_01_24_08_53_44](https://user-images.githubusercontent.com/24860501/105624640-b6487400-5e23-11eb-847d-e023cfb81e77.png)
![fsScreen_2021_01_24_08_53_52](https://user-images.githubusercontent.com/24860501/105624642-b9436480-5e23-11eb-8607-e52ede381cf5.png)
![fsScreen_2021_01_24_08_53_58](https://user-images.githubusercontent.com/24860501/105624646-bcd6eb80-5e23-11eb-93a6-431c9e83f789.png)
![fsScreen_2021_01_24_08_54_05](https://user-images.githubusercontent.com/24860501/105624650-c06a7280-5e23-11eb-8a0c-fc7dc4cb5165.png)
![fsScreen_2021_01_24_08_54_13](https://user-images.githubusercontent.com/24860501/105624655-c5c7bd00-5e23-11eb-816a-16c29651193c.png)
![fsScreen_2021_01_24_08_54_19](https://user-images.githubusercontent.com/24860501/105624656-c9f3da80-5e23-11eb-8736-e1e1567cc242.png)

so sieht die Kursgenerierung aus:
![fsScreen_2021_01_24_08_58_23](https://user-images.githubusercontent.com/24860501/105624660-d710c980-5e23-11eb-86ab-98a0dd0e6782.png)

wäre es möglich, den Drescher parallel zu der Linie zw WendeStart und WendeEnde fahren zu lassen:
![pic01](https://user-images.githubusercontent.com/24860501/105624682-f4de2e80-5e23-11eb-96d1-fbfc9908b6b3.png)

es muss ja nicht immer nur ne Strasse sein, manchmal ist auch ein Wald am Feldende (und Bäume fahren nicht weg).
lg
andreas

**Comment by candymant** [comment]
You start the course generation on a corner. You have   to start your course in the middle of the long side of the field.
And try again then or more headlands.

**Comment by Tensuko** [comment]
Das ist so nichts neues. Ein Vorgewende mehr und welche turn settings ? Probiere mal AI Turn oder Pathfinder.

**Comment by andreasthu** [comment]
Hallo tensuko,
Ai turn, pathfinder und Ai rückwärts,.. sind alle aktiv. Ein, oder zwei Vorgewende mehr dann fährt der Drescher nichtmehr auf die Strasse stimmt, ich versuche aber generell eher mit weniger vorgewenden auszukommen.
Erlengrat hat hier eher mehrere Felder ( z.b. 5, 6, 7, 8, 9, 10,..) die Spitz zulaufen, da ist mir dieses Problem schon häufiger begegnet, poste später noch eine andere Situation.

Was meinst du mit turn Settings?
Lg
Andreas

**Comment by Tensuko** [comment]
AI turn usw, aber die ofizielle Lösung hier ist, mehr Vorgewende, dafür ist das da.

**Comment by rohne83** [comment]
> You start the course generation on a corner. You have to start your course in the middle of the long side of the field.
> And try again then or more headlands.

He's using spirals mode. At the moment spiral courses are only generated properly if starting point is along the first half of one of the short edges of the field (there's an issue already where this is handled). So this wouldn't help him.

@andreasthu wie sieht das denn aus, wenn du das Feld auch richtig bearbeiten lässt? Ich meine es gab auch eine Einstellung, die dafür sorgt, dass mittlerweile die Drescher bei der Wende im Feld bleiben. Halt nur insofern auch möglich. Nur ein Vorgewende ist bei deinem Schneidwerk tatsächlich etwas wenig. Da passt der Drescher allein ja so schon kaum drauf, geschweige denn dass er darauf eine ordentliche Wende hinbekommen könnte.

**Comment by pvaiko** [comment]
Setting AI turn is not a good idea for this use case. AI Turn is there for making 3 point turns more compact, for normal up-down rows. It also has some capability to recover from collisions with trees or fences during the turn.

Unselect AI turn.

**Comment by andreasthu** [comment]
> Setting AI turn is not a good idea for this use case....
> 
> Unselect AI turn.

Thanks, Danke das war es.
Wenn ich "Benutze AI-Wendemanöver" deaktiviere wendet der cp helfer genauso wie ich es brauche.
lg
andreas
