### ISSUE TITLE
Fahrer läd im Fahrsilo nicht ab.

### ISSUE THREAD

**Issue by Namajo** [Courseplay/courseplay#6722]
Hallo,

ich habe ein Problem beim Abfahren der Häcksler in ein Fahrsilo von BGAs.

Der Häcksler wird ordnungsgemäß abgefahren und der WEG zum Fahrsilo wird problemlos gefunden. Aber dann geht es los:

Das Silo wird angefahren.
![20210124131115_1](https://user-images.githubusercontent.com/64135697/105630045-e05f5d80-5e46-11eb-87de-18a0c4335b1d.jpg)

Die Plane wird geöffnet.
![20210124131119_1](https://user-images.githubusercontent.com/64135697/105630048-e5bca800-5e46-11eb-9eb5-409f383deb48.jpg)

Es wird in die richtige Bahn eingeschwenkt.
![20210124131128_1](https://user-images.githubusercontent.com/64135697/105630233-45678300-5e48-11eb-9f50-f9dce1bdc647.jpg)

Der Fahrer fährtmit offenen Hänger durch das Silo entlädt aber nicht.
![20210124131135_1](https://user-images.githubusercontent.com/64135697/105630258-6039f780-5e48-11eb-8686-c26162e8b18e.jpg)

Es wird zurück zum Feld gefahren.
![20210124131147_1](https://user-images.githubusercontent.com/64135697/105630264-70ea6d80-5e48-11eb-912c-6c843b9de94e.jpg)

Und der Inhalt des Hängers vor das Feld gekippt.
![20210124131222_1](https://user-images.githubusercontent.com/64135697/105630270-7d6ec600-5e48-11eb-93ec-546586b72585.jpg)

[Hier](https://gist.github.com/Namajo/d8f654e13e8ab5cff0d2f55b2e1deb5e) ist das Log dazu.

Ich habe das bereits mit verschiedenen Tracktoren/LKWs und unterschiedlichen Hängern auf verschiedenen Karten versucht. Das Problem bleibt das gleiche. Mache ich etwas falsch?

MfG, Namajo

**Comment by Namajo** [comment]
PS: Courseplay und FS19 sind auf den jeweils aktuellesten Release-Versionen.

**Comment by Tensuko** [comment]
Die BGA hast du aber gekauft ? Das Gelände ?

**Comment by Namajo** [comment]
Generell ja. Möglicher weise habe ich das in diesem (für das Ticket erstellte) Savegame vergessen. Das checke ich sofort.

**Comment by Namajo** [comment]
Schande auf mein Haupt. Ich habe es tatsächlich vergessen. Und anscheinend nicht nur in diesem Savegame. Man ist das peinlich. Ich bitte um Entschuldigung. Das Thema ist dann wohl erledigt...

**Comment by Tensuko** [comment]
Kein Problem :)
