### ISSUE TITLE
Mode6 Self-Unloading Fails While Approaching

### ISSUE THREAD

**Issue by Fully-git** [Courseplay/courseplay#6724]
The Self-Unloading-Feature integrated in mode 6 fails smart while approaching a trailer. Probably the collision prevention or the new  proximity sensor bahaviour made the difference.
Last working version was 6.03.00018, latest tested 6.03.00028.

Problem:
Self unloading starts as expected, path seems correct, but no slow down, pipe-opening or "Self unloading point reached"
Instead, nice smart fail: "Exception, stopping Courseplay driver, C:/users/fully-git/Meine Dokumente/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CombineAIDriver.lua:1771: attempt to call method 'getIsEntered' (a nil value)"
"Ending work: turn off and raise implements."

FS 19 is almost vanilla; only Claas DLC and Courseplay.

Examples: TX32 combine on field 19 at Felsbrunn map with nearby HW 80 trailer.
log 6.03.00018 self unloading starts and stops as expected
[SelfUnloading_ok_6.03.00018.log](https://github.com/Courseplay/courseplay/files/5863120/SelfUnloading_ok_6.03.00018.log)

log 6.03.00028 self unloading nice smart fail
[SelfUnloading_fails_6.03.00028.log](https://github.com/Courseplay/courseplay/files/5863125/SelfUnloading_fails_6.03.00028.log)

Do you need more debug levels or pictures? Many thanks for reading an hopefully fixing, Courseplay is really great.

**Comment by Tensuko** [comment]
Screenshots are always welcome, best is ofc Videos.
