### ISSUE TITLE
Status/chance for courseplay to work with "manual" driven combine

### ISSUE THREAD

**Issue by NicoOv96** [Courseplay/courseplay#6725]
Hello

I hope this topic doesn’t come too often, but the only topic i could find on this is from spring 2020.

But what are your thoughts on allowing the “courseplay-trailer” / ”courseplay-overloader” to work with the manual driven combine, etc. the player driving the combine and courseplay driving the overloader in field to a truck also operated by courseplay?

I am asking because this is the way (the only way) I am using courseplay and therefore I am still using courseplay v6.01.00399, which can’t handle the overloader but only the “normal” trailers.

Thanks in advance

**Comment by pvaiko** [comment]
@NicoOv96 this request comes up once in a while and we also had someone volunteering to implement it but we haven't heard from him for a while.

Sorry to say that but the current CP dev team won't do this anytime soon. Not sure if AutoDrive can do what you need, you may want to give that a try.
