### ISSUE TITLE
Driver wont turn in field on headland corner set to turn

### ISSUE THREAD

**Issue by Siginek** [Courseplay/courseplay#6726]
Hello, I have been lately experiencing quite weird behavior in my courseplay
I have few courses that worked perfectly, but for some reason, courseplay started to mess up lately (first time i noticed was yesterday) - basically i have fertilizing course with vanilla tractor, and vanilla spreader with setting "Headland turn = turn", but when my tractor comes to this turn, it cannot make it, it starts spinning and if i leave it for some time, it just ends up somewhere in the middle of field as it keeps spinning around. All the courses that do this worked perfectly few days ago with same tractor.
I have been adding some mods over the time of playing, but i dont recall any mod, that would change game behaviour i would add in time, i started noticing problems - i have added mods like shovel, egg and wool pallets, realistic cab view etc.
I have tried to mess up with settings, but nothing helped.
As i am not sure if i didnt do something with settings, that causes this behavior, and also it is quite hard to describe, i have attached video of this behaviour where i also show my course and CP settings.

Map i am using is Eielshort

CP version: 6.03.00029.dev

https://gist.github.com/Siginek/0e8041fc3bd5169cf251bd9f251d58e1
https://www.youtube.com/watch?v=t5xzKrRc7ZI

Edit: I have disable all mods except courseplay and problem still remains so i guess it somethign with settings, as i have not changes courses or update map or courseplay lately, so i hope, someone will be able to help me

**Comment by Tensuko** [comment]
logfile with debugchannel 12 and 14 active pls.
Turn on debugchannels, then let the driver perform the turn and post that logfile.

To your logfile:
You should clean up a bit anyway...
You got GlobalCompany so you don't need Place Anywhere, one mod need to be unzipped and your VehicleExtension is not original https://github.com/Mogli12/AIVehicleExtension

**Comment by Siginek** [comment]
Here is new log with 12 and 14, also deleted old one, so this is "clear"

by the way - i also noticed, that when my tractor drives from end of line (green point) to start of new (red), it quite a lot gets stuck on trees by the field, as the field does not have straight edge - is there any option to fold all the tools when driving from end of one line to start of another?

**Comment by pvaiko** [comment]
That logfile does not have the debug channels on.

**Comment by pvaiko** [comment]
As for the getting stuck problem, try enabling pathfinding in turns in the advanced options that should keep the vehicle on the field.

**Comment by Siginek** [comment]
https://gist.github.com/Siginek/9afaed69c09e856163c1f79534fa7146

is this one correct? it was kinda weird, i deleted old one, started debug channels and than copied it ... i guess some weird problem with windows saving open files

**Comment by Siginek** [comment]
Is there any way, i could reset courseplay to "factory" settings? i dont mind losing all courses, i can just generate them again, but if it might help with this issue as well as with the one i described in comments, its worth a shot imho

**Comment by pvaiko** [comment]
For now, just stop the driver, select a different mode, then reselect mode 4 and it is going to be fine.

**Comment by Siginek** [comment]
OK, thanks for help ... btw - i just realized that i noticed few times that no mode was selected, but i forgot that when i wrote this bug report - i think it might have something to do with Autodrive start of CP at the destination - hope that helps

**Comment by pvaiko** [comment]
![image](https://user-images.githubusercontent.com/2379521/105738189-6093ca80-5efc-11eb-95d5-1034dd2e2660.png)
@schwiti6190 This is how it looks like after the savegame is loaded. For whatever reason the vehicle has mode 6 saved in the savegame but that mode isn't allowed with this spreader.

**Comment by lionking2890** [comment]
Ich weiß nicht, ob es euch bei der Fehlersuche hilft. Ich hatte den Bug gestern auch. Mir fehlte nur die Zeit bisher es genauer zu untersuchen. Als ich es in einem neuen Spielstand versuchte nachzustellen um Modkonfilikte auszuschließen lief alles.
Danach habe ich das Gespann einmal auf den Hof zurückgesetzt und es lief auch alles.
Ob ich damit unbewusst den Modus umgeschaltet habe, kann ich nicht sagen. Vermutlich jedoch ja.
Bei mir war jedoch auch ein Traktor mit Allradlenkung im Einsatz. Ich dachte es läge vielleicht daran, dass er in die falsche Richtung oder zu viel lenkt. Es scheint aber ja wohl auch mit anderen Traktoren der Fall zu sein.
Einen Logfile habe ich bisher leider nicht, da das Problem nach dem zurücksetzen nicht mehr auftrat.
Ein neuladen des Spiels brachte erst keine Verbesserung. Dies hatte ich zuerst versucht, weil ich dachte es hätte sich einfach nach 4 Stunden spielen etwas "verschluckt".

**Comment by pvaiko** [comment]
#6728 seems to be related to this one as looks like the CP mode saved in the savegame is empty.

**Comment by pvaiko** [comment]
should now be fixed by v32
