### ISSUE TITLE
v6.03.00028 Seeders "Tool need to be unloaded"

### ISSUE THREAD

**Issue by daver18qc** [Courseplay/courseplay#6727]
So i went to start a seeder course with my seeder full, it said "please unload work tool" like it was a trailer. I manually planted a couple meters to get to 98% full and now the course works as intended.

PS.: Used v6.03.00026 on the same map, same course and worked fine then, so bug has appeared between 26 and 28

**Comment by Mannie313** [comment]
wir haben v6.03.00029

**Comment by daver18qc** [comment]
> wir haben v6.03.00029

I didn't see anything in the notes that said they fixed that in 29 but i'm gonna try it soon just in case!
Can you confirm it's fixed in 29?

**Comment by Tensuko** [comment]
What Tractor did you use ? What Mode ?

**Comment by daver18qc** [comment]
> What Tractor did you use ? What Mode ?

Fendt 515c vanilla
Stara Ceres Master 3570 vanilla

The only mode that allows you to seed a field (i think?), not sure of the numbering, it's the "Type: Fieldwork" one.
Although i didn't try the latest version 00029 so maybe it was a fluke, i will get the latest version and try again and report back later tonight!

**Comment by Tensuko** [comment]
4th Button from the left (Mode4) Seeding and Fertilizing.
Fieldwork would be wrong and no wonder about that message.

**Comment by daver18qc** [comment]
> 4th Button from the left (Mode4) Seeding and Fertilizing.
> Fieldwork would be wrong and no wonder about that message.

Oh my bad it was Mode4 yes (can't even select Fieldwork with a seeder, it was from my bad memory)

BUT testing latest version 00029 right now and it works, so it's fixed, you can close this thread i guess!
