### ISSUE TITLE
Game freezes when loading (toolManager.lua: 141)

### ISSUE THREAD

**Issue by BlazeRGamin** [Courseplay/courseplay#6728]
hey, my save on fs19 won't open when using version 6.03.00027 and up to 29.
I get this massage in the log file: 2021-01-25 19:25 C:/Users/tyren/OneDrive/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/toolManager.lua:141: bad argument #4 to 'format' (number expected, got nil)

Version 6.03.00026 works fine so im using that for now, but just used subsoiler on the game and would like the updated subsoiler thing

here is my log file if it helps
[log.txt](https://github.com/Courseplay/courseplay/files/5868895/log.txt)

**Comment by pvaiko** [comment]
@BlazeRGamin could you post here the vehicles.xml file from your savegame folder?

**Comment by 0Pietro20** [comment]
Hi, I encountered a similar problem: I tried to open farming (until yesterday I used 026 as a version, today I updated it to 029) and after entering the loading screen the game freezes and continues to load indefinitely
[log.txt](https://github.com/Courseplay/courseplay/files/5869633/log.txt)

**Comment by Tensuko** [comment]
@0Pietro20 you log doesn't contain the Error when you have 'endless loading'

**Comment by pvaiko** [comment]
@0Pietro20 also, same as above: could you post here the vehicles.xml file from your savegame folder?

**Comment by 0Pietro20** [comment]
Ok, I can post it. I don't know the file and I don't know what it contains so I have a question: to be able to play or put back version 026, do I have to put back 029, open the game and then post the XML file or does it make no difference? For now given this, in case you need that after I have re-entered the 029 I will provide

[vehicles.zip](https://github.com/Courseplay/courseplay/files/5869719/vehicles.zip)

**Comment by 0Pietro20** [comment]
I used the compressed folder because the system did not allow me to directly upload the file

**Comment by pvaiko** [comment]
@0Pietro20 no, this XML is fine, thanks.

**Comment by 0Pietro20** [comment]
Perfect. If you need more files or tests, please ask

**Comment by pvaiko** [comment]
@0Pietro20 but the logfile you posted does not even load Courseplay.

**Comment by 0Pietro20** [comment]
Oh ... I didn't know. I tried to start a game without mod and it worked, then I tried to start only one without courseplay (only change from yesterday) and it started without problems

**Comment by pvaiko** [comment]
well, if you want this fixed we need a logfile with CP enabled, v29, you know, when the game is not loading.

**Comment by 0Pietro20** [comment]
Ok, I'll try to download the latest version and give it a try

**Comment by BlazeRGamin** [comment]
> @BlazeRGamin could you post here the vehicles.xml file from your savegame folder?

yes can do

**Comment by BlazeRGamin** [comment]
[vehicles.zip](https://github.com/Courseplay/courseplay/files/5869988/vehicles.zip)

**Comment by 0Pietro20** [comment]
I tried with the 029 and after 15 minutes of loading the game always remained at that point (on the screen it seems loaded because the suggestions written change). Usually to process objects and career does not take more than 1 maximum 2 minutes

[log.txt](https://github.com/Courseplay/courseplay/files/5869987/log.txt)

**Comment by pvaiko** [comment]
Can you guys test it with 6.03.00030 and post the log here no matter if works or not. Should at least show some additional info to help finding the root cause.

**Comment by 0Pietro20** [comment]
I tried with the 030, but it gives the same result, infinite loading

[log.txt](https://github.com/Courseplay/courseplay/files/5872060/log.txt)

**Comment by Tensuko** [comment]
Remove this Mod and try again: (Version: 1.0.0.0) FS19_MerloP417

**Comment by 0Pietro20** [comment]
I just encountered an anomaly: the game I was using as a test does not start the game. Having a that game bought the mod in question, I wanted to give it a try by starting a new career and the game loaded without problems

[log.txt](https://github.com/Courseplay/courseplay/files/5872119/log.txt)

**Comment by Tensuko** [comment]
That is not a surprize, as the new career doesn't contain the vehicle, or any vehicle with any setting...

**Comment by 0Pietro20** [comment]
Ah OK. I take off that mod and try to start the usual game

**Comment by 0Pietro20** [comment]
It works

[log.txt](https://github.com/Courseplay/courseplay/files/5872149/log.txt)

**Comment by 0Pietro20** [comment]
But what would be the problem with that mod?

**Comment by Tensuko** [comment]
He was loading the vehicle and then got this Error:
2021-01-26 09:12 :02 [info lp2826] P41.7:  no CP mode set, worktool P41.7, forcing mode 5
2021-01-26 09:12 Error: Running LUA method 'update'.
2021-01-26 09:12 C:/Users/Primo/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/toolManager.lua:357: attempt to perform arithmetic on field 'vehicleTurnRadius' (a nil value)

Guess we don't get a turnRadius of this Mod, could solve this with the VehicleConfigurations.xml but I just noticed we don't have a copy of it in modsSettings yet.

If you know how to replace a file inside your CP file, try to replace this .xml it is in config folder.
Then add back your Merlo Mod and load your savegame again.
[VehicleConfigurations.zip](https://github.com/Courseplay/courseplay/files/5872222/VehicleConfigurations.zip)

Btw I woull combine some of your Answers...

**Comment by 0Pietro20** [comment]
Even with the modified file it produces the same problem

[log.txt](https://github.com/Courseplay/courseplay/files/5872316/log.txt)

**Comment by Mannie313** [comment]
@pvaiko ich hab dieses problem nicht mit der v6.03.00029 bei mir lädt das spiel. 

Fals das hilft hier meine Log:

[log.txt](https://github.com/Courseplay/courseplay/files/5872581/log.txt)

MFG Mannie313

**Comment by pvaiko** [comment]
@0Pietro20 don't think it is a problem with vehicle. Let me check something.

**Comment by pvaiko** [comment]
6.03.00031 should have fixed this. 

There is indeed a problem with the vehicle as described in the commit message.

**Comment by BlazeRGamin** [comment]
> Can you guys test it with 6.03.00030 and post the log here no matter if works or not. Should at least show some additional info to help finding the root cause.

sorry i didnt respond and test version 30 bc i was asleep and on work

**Comment by 0Pietro20** [comment]
i tried version 031 and it didn't give me any problem

**Comment by BlazeRGamin** [comment]
> i tried version 031 and it didn't give me any problem

i will try it now but if i have to i can remove the merlo mod, its weird they didnt make it so i can use courseplay or follow me on it

**Comment by pvaiko** [comment]
@BlazeRGamin you don't have to remove it if you are using 31. It just won't work with CP.

**Comment by BlazeRGamin** [comment]
ik but still, but it worked. My game is fine now so thx developer, can turn this issue to solved now ig
