### ISSUE TITLE
Problem beim pflügen?

### ISSUE THREAD

**Issue by ElKayEss** [Courseplay/courseplay#6731]
Vielleicht bin ich hier richtig. Ich hab ein Problem beim pflügen mit Courseplay auf der Map Gemeinde Rade Feld 1. Kursgenerierung usw. klappt gut, aber wenn er für eine neu Reihe ansetzt, fährt der Helfer eine Weile gerade, bearbeitet aber einen kleinen Streifen Land nicht, lenkt dann später ein und schließt diese Lücke, nur halt zu spät. Ist das ein Fehler oder hab ich den Kurs einfach schlecht eingestellt?

**Comment by Tensuko** [comment]
Ohne ein paar Bilder, kann ich mir nichts dadrunter vorstellen.

**Comment by ElKayEss** [comment]
Ich weiß nicht warum, ich wollte gerade paar Bilder machen, jetzt klappt es wie gewünscht.
