### ISSUE TITLE
Problem beim rückwärts fahren

### ISSUE THREAD

**Issue by OGW-LBO** [Courseplay/courseplay#6732]
Beim rückwärts fahren schiebt er das Gerät einfach hinter sich her, ohne richtig den Anbau auszulenken.
Fährt dann auch ewig rückwärts, stellenweise auf andere Felder, zerstört dabei die Frucht und dann hab ich dadurch teilweise andere Frucht auf dem Feld. Entweder er schafft es dann mal und bleibt weit nach der Begenzung irgendwo rückwärts hängen.

**Comment by Tensuko** [comment]
Keine Ahnung wovon du da sprichst.
https://github.com/Courseplay/courseplay/wiki

**Comment by pvaiko** [comment]
#6726 wahrscheinlich, vor dem Starten prüfen ob das richtige CP Mode ausgewählt ist (taste ist grün)
