### ISSUE TITLE
Mode9 does not continue load on heap

### ISSUE THREAD

**Issue by JennyD73** [Courseplay/courseplay#6734]
after reaching the first wait point and filling shovel course stops like its finished
![fsScreen_2021_01_26_20_05_04](https://user-images.githubusercontent.com/75444078/105899180-3d5b3f00-6012-11eb-9c99-1e5bf7b7ffe4.png)

**Comment by Tensuko** [comment]
Can't reproduce this.
logfile with channel 10 and 12 and also screenshot with logfiles on at the same situation.

**Comment by JennyD73** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5876330/log.txt)
knew i forgot something

**Comment by JennyD73** [comment]
ok its not trying to load on heap its trying to move that heap to a trailer but it goes to the heap then stops the course

**Comment by JennyD73** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5876517/log.txt)
![fsScreen_2021_01_26_22_23_01](https://user-images.githubusercontent.com/75444078/105913806-4dc8e500-6025-11eb-9012-b8c28ce43afb.png)
![fsScreen_2021_01_26_22_23_11](https://user-images.githubusercontent.com/75444078/105913815-51f50280-6025-11eb-8380-d67dc95f9337.png)

**Comment by Tensuko** [comment]
Only one GEO at the time:
Available mod: (Hash: 4b42604d36a2b81e0c61a7cfd6b3756f) (Version: 1.0.0.0) FS19_GEO_Brazil
Available mod: (Hash: a7c8161bc93776bbca5a8919e5e33e4f) (Version: 1.0.0.2) FS19_GEO_Northern_Ireland
Available mod: (Hash: c3c295e91a3cf48d04ce3c79563883a7) (Version: 1.0.0.0) FS19_Geo_Oxforshire
Available mod: (Hash: b71a4e29edd5edf2a95ed26c8bb08038) (Version: 1.1.0.0) FS19_Geo_UK_Devonshire_Exmouth

Not sure about this mod, it might make problems:
Available mod: (Hash: 14a10cd0f899959a837eafa09dc31426) (Version: 1.0.0.9) FS19_ContractorMod

Only one Map in Mods folder allowed.

And I can't preproduce this on .00032
![fsScreen_2021_01_27_07_32_44](https://user-images.githubusercontent.com/27344744/105952719-41b74480-6072-11eb-8609-143280f2fe8b.png)
![fsScreen_2021_01_27_07_32_49](https://user-images.githubusercontent.com/27344744/105952732-454acb80-6072-11eb-8eae-4e40cf3cb076.png)

**Comment by Tensuko** [comment]
@schwiti6190 I guess it is the same Callstack that I had, no sure how this comes up

**Comment by JennyD73** [comment]
ok i have some more information on this .. i tested with earlier versions of courseplay and on another map the issue i posted here where it just stops has gone so this must be map related .. but its back to being stuck in traffic when approaching the trailer as it was in version 007 i tested this with 0026 and 0033. i cant remember the debug channels i can do the log file and screenshots again if you remind me

**Comment by Tensuko** [comment]
Can you try 6.03.00043 ?

**Comment by JennyD73** [comment]
Hi yes the original issue has gone now did a test on one map and had a trailer issue where it just kept driving into the trailer ( have seen the other post regarding this) but on another map with a different trailer it worked fine

**Comment by Tensuko** [comment]
Waitpoint not to close to trailer and it should work. Strange mods ofc excluded.
Generaly we check distance to trailer.
Take this as solved.

**Comment by JennyD73** [comment]
changed trailer and it worked fine
