### ISSUE TITLE
Camera Hopping Bug

### ISSUE THREAD

**Issue by BoostedCanuck** [Courseplay/courseplay#6735]
I've encountered a very annoying and very strange bug whilst playing on Chellington Valley on a friend's dedicated server. We keep mods up to date and we are on the current build of Courseplay as of today (v6.03.00031).

If I pan out while in a vehicle (in third person) and I rotate the camera inside the cab of another vehicle, regardless of who it belongs to, I then jump into the driver seat of said vehicle. I have conducted several tests and I have determined it is definitely Courseplay causing the issue, however nobody else in the server reports the same problem. I have verified this by starting multiplayer games with only Courseplay enabled, and the problem persists. This has been an issue since starting this save, and we have wiped it clean several times with no effect.

Any help would be appreciated. I would offer my game log however upon further inspection, no messages or errors are thrown when the problem occurs. I simply hop in while panning the camera around, and that's it.

**Comment by Tensuko** [comment]
I want to see logfiles anyway.

**Comment by Tensuko** [comment]
> however nobody else in the server reports the same problem

There must be something active on your side, as I noticed, that when you are inside a tractor and look at another tractor, you can click with mouse (without mouse active). That is also happening in SP. So somehow your mouse click stays active or you do any clicking. Without clicking the mouse, he won't jump into another vehicle.

**Comment by Tensuko** [comment]
Will be fixed in the next Release. But you should check your input Binding anyway, as perma clicking mousebutton is not normal.

**Comment by BoostedCanuck** [comment]
Log file, as requested. Fresh server restart running Courseplay Build 031 (27/01/21)
[log.txt](https://github.com/Courseplay/courseplay/files/5883616/log.txt)

**Comment by BoostedCanuck** [comment]
I would like to note that I have disabled all key bindings related to 'LEFT' mouse click, and the problem persists. I will continue trying to ascertain if it's a key binding I have set up. I have reset all bindings to default and it continues.

**Comment by Tensuko** [comment]
Not sure what those are for:
Available mod: (Hash: efd147bff725d0c85e85053c5b8f46b7) (Version: 1.0.0.0) FS19_Camara
Available mod: (Hash: 05cab92d50b7a91172ba685edae069e1) (Version: 1.1.0.0) FS19_CameraSuspension

You should rly check if you rly need all those mods...

Anyway, fix is on the way, at least it should fix it, as you need a cursor active.
For anything else, you have to check it on your side, as I did many tests while changing this and there is nothing that make some kind of auto jump. Maybe any joystick axis that are out of the deadzone or something....
