### ISSUE TITLE
Slow Leveling :(

### ISSUE THREAD

**Issue by Gibbanator** [Courseplay/courseplay#6736]
With each update of CP you Devs seem to have perfected the leveling of a bunker. I no longer have to put houses at the end of my bunker to stop the tractor from turning out of the back of the bunker.

With that said do we have to have CP set the speed for only 6 MPH? I mean it not only goes backwards at that speed it goes forward also at that speed. Can we be allowed to adjust the speed? If problems occur we can always turn it back down to a speed that works. Maybe CP can put a suggested speed instead of making it only one speed allowed.

https://youtu.be/CybxWvgMQuI

Leveler only does about 3 swipes before the semi comes with next load and I am only using one trailer to unload and load.

**Comment by Tensuko** [comment]
This Setting is working ?!
![fsScreen_2021_01_27_07_12_29](https://user-images.githubusercontent.com/27344744/105950760-39a9d580-606f-11eb-8e87-7b7c481a1565.png)

**Comment by Gibbanator** [comment]
[https://i.gyazo.com/df254766cf5ea937afe47ea292861d09.jpg](url)
https://i.gyazo.com/df254766cf5ea937afe47ea292861d09.jpg
it is set for 10 MPH but tractor only goes 6 MPH back and forth as in video so I think it is not working properly.

**Comment by Tensuko** [comment]
becosue the calculation on the HUD is still for km/h but it is max speed, won't get more, that is a calculated speed.

**Comment by Gibbanator** [comment]
Is that a CP HUD calculation? Can that be adjusted for a bit more? or is that something not possible or not recommended?

**Comment by Tensuko** [comment]
Won't get more.

**Comment by Gibbanator** [comment]
Okay Tensuko Thank You for the help and all you do..
