### ISSUE TITLE
Tractor trailer wont unload at any silo after the 1st unload 

### ISSUE THREAD

**Issue by MSclimenti** [Courseplay/courseplay#6737]
Tractor trailer wont unload at any silo....  the 1st unload works ok then the 2nd and all unload after  just go's over the unload trigger at the silo and keeps going  back to the field I am using courseplay 6030000.25

**Comment by Tensuko** [comment]
I have no Issue at all with unloading, my unloader runs for about 2 hours now.
Also:
https://github.com/Courseplay/courseplay/wiki

**Comment by MSclimenti** [comment]
So Sorry!!..... STUPID ME I did not have the tractor trailer set correctly to offload at the silo please forgive me for sending in a trouble issue you can close this case and Thank you for your response

**Comment by Tensuko** [comment]
Relax, but when you post screenshots of your situation directly, I can often help you out on whats wrong.
For the next time then :)

**Comment by MSclimenti** [comment]
thank you
