### ISSUE TITLE
Grégoir-Besson SPSL9 Plow wrong working width

### ISSUE THREAD

**Issue by haba1376** [Courseplay/courseplay#6738]
Версия курсплей 6.03.0029 не определяет прикрепленное устройство ( плуг шириной 10,5 м) из  стартового набора оборудования. Курсплей определяет рабочую ширину как 0,1 м. В версии курсплей 6.03.0025 такого не замечено.

**Comment by Tensuko** [comment]
@Gonimy-Vetrom
may I ask your for some assistance here ?

**Comment by Bobster82** [comment]
@Tensuko ,


Course version version 6.03.0029 does not identify the attached device (10.5 m wide plow) from the starter kit. The courseplay defines the working width as 0.1 m. In the courseplay version 6.03.0025 this is not noticed.

A simple google translate from russian to english ;)

**Comment by Tensuko** [comment]
@Bobster82 
well thank you but mostly this will get back and forward and I don't always trust google translater :)

@haba1376

What Plow is it ?
Also try 6.03.00032

**Comment by Bobster82** [comment]
@Tensuko , NP, was just scrolling by ;)
Most of the time google translate can point out the "problem" 

He said the vanilla plow 10,5m wide, thats the spsl 9 ingame.

**Comment by haba1376** [comment]
Сейчас сказать модель не могу, но скорее всего SPSL 9/, Он один с параметрами на 10,5 м. В стартовом наборе, без модов.

**Comment by haba1376** [comment]
![d0b3d180d0b5d0b3d183d0b0d180-d0b1d0b5d181d181d0bed0bd-d0bfd0b0d0ba-v1-0-fs19](https://user-images.githubusercontent.com/78074184/105984817-b5297800-60ab-11eb-8264-bad1970df9fa.jpg)
Выглядит так.

**Comment by Mannie313** [comment]
Übersetzung Deepl Translater

Jetzt kann ich nicht sagen, das Modell, aber höchstwahrscheinlich SPSL 9 /, Er ist einer mit den Parametern bei 10,5 m. Im Starterset, ohne Modifikationen.

Была ли у вас белая вешалка для 3-х точечных устройств.

Hast du den weißen Hänger für 3punkt geräte drangehabt.

MFG Mannie313

**Comment by Tensuko** [comment]
@Mannie313 nein, der Pflug meldet wirklich die falsche Arbeitsbreite.

**Comment by haba1376** [comment]
Нет, не было. Только плуг. При прикреплении плуга параметр рабочей ширины в панели 
Courseplay, оставался 0,1 м. А радиус поворота достигал показателя 423. поэтому сгенерировать маршрут не получалось.     
>Среда, 27 января 2021, 15:00 +03:00 от Manfred Merkle <notifications@github.com>:
> 
> 
>Übersetzung Deepl Translater
>Jetzt kann ich nicht sagen, das Modell, aber höchstwahrscheinlich SPSL 9 /, Er ist einer mit den Parametern bei 10,5 m. Im Starterset, ohne Modifikationen.
>Была ли у вас белая вешалка для 3-х точечных устройств.
>Hast du den weißen Hänger für 3punkt geräte drangehabt.
>MFG Mannie313
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Михаил Шмелев

**Comment by haba1376** [comment]
могу ошибаться, но это появилось скорее после версии когда поменялись в настройках 
Courseplay папки, примерно с 6.03.0027.

  
>Среда, 27 января 2021, 15:06 +03:00 от Tensuko <notifications@github.com>:
> 
> 
>@ Mannie313 нет, плуг действительно сообщает неправильную  ширину захвата .
>- 
>Вы получили это, потому что вас упомянули. 
>Ответьте на это письмо напрямую,  просмотрите его на GitHub или  откажитесь от подписки . 
 
 
--
Михаил Шмелев

**Comment by pvaiko** [comment]
I'm having a hard time here motivating myself to help someone who does not even bother to translate his issue description himself.

**Comment by haba1376** [comment]
Я имею возможность перевести с помощью переводчика. Но так как сам не владею языком. может получится еще хуже. Ранее данные ответы на вопрос, поняли проблему.

**Comment by Bobster82** [comment]
> Я имею возможность перевести с помощью переводчика. Но так как сам не владею языком. может получится еще хуже. Ранее данные ответы на вопрос, поняли проблему.

At least use google translate ;) No need for a tolk
