### ISSUE TITLE
Ladeprobleme Irgendwo in Thüringen II

### ISSUE THREAD

**Issue by konk1980** [Courseplay/courseplay#6739]
servus. hab auf der thüringen 2 (3.1.0.1) folgendes problem. nachdem ich eine zuckerrübenmission mit der tiger xl angenommen habe, kann ich das spiel nur noch starten, wenn ich courseplay aus dem modordner nehme. gibt es eine möglichkeit das problem zu beheben oder gibt es eine ältere version von cp mit der es funktionieren sollte? hab cp 6.03.00032, 6.03.00022 und 6.03.00016 probiert. Laut Mapper kann das Problem nur an CP liegen ;-)
[log.txt](https://github.com/Courseplay/courseplay/files/5878736/log.txt)

**Comment by Tensuko** [comment]
Die Map spiele ich auch und muss diverse Testversionen über sich ergehen lassen und habe keinerlei Probleme.
Mal davon abgesehen, dass deine log bei 2021-01-27 09:34 SelectedCombineToUnloadSetting:init() endet und nicht mit einem LUA Error kann ich dir nur sagen: GEDULD!
Du hast mit sicherheit Kurse in Fahrzeuge die relativ groß sind, Ich hatte mal 3 Kurse auf Feld 11, Feld 13 und Feld 29 die alle weit über 10.000 Wegpunkte hatte, und solange die Kurse im Fahrzeug sind, werden die immer geladen. Das kann auch mal 15 Minuten dauern!
