### ISSUE TITLE
problem with bying forage harvesters in shop

### ISSUE THREAD

**Issue by candymant** [Courseplay/courseplay#6740]
hello,
if I want to buy these forage harvesters then they don't show up in the shop preview
if I don't load course play .32 then I can buy these. here is the log file.
[log.txt](https://github.com/Courseplay/courseplay/files/5880798/log.txt)
These are the 2 mods from the mod hub on a standard map.
https://www.farming-simulator.com/mod.php?lang=en&country=nl&mod_id=179845&title=fs2019
https://www.farming-simulator.com/mod.php?lang=en&country=nl&mod_id=151783&title=fs2019
![fsScreen_2021_01_27_15_18_07](https://user-images.githubusercontent.com/47895720/106005076-240acf00-60b4-11eb-9f8e-abf95a48112d.png)
![fsScreen_2021_01_27_15_18_17](https://user-images.githubusercontent.com/47895720/106005153-35ec7200-60b4-11eb-98bf-155fc5686d07.png)

**Comment by Tensuko** [comment]
Both Mod Issues.

The Krone one is a Mod Issue (bad convert).

The JD should be the one with manual pipe, wich we don't support. (get the alternative JD 9000, maybe the JD Pack from Ifko)
