### ISSUE TITLE
Pathfinding ignores trees when changing rows

### ISSUE THREAD

**Issue by Siginek** [Courseplay/courseplay#6741]
Hello, I have encountered problem, where my implement ignores trees when calculating path on row change, which leads to said implement getting stuck on that tree. In this video its vanilla tractor with modded seeder, but i encountered similar problem with various equipments (vanilla tractor + vanilla spreader/sprayer etc). In the vide below, there is also part where i show my CP settings.

CP Version: 6.03.0032

Equipment - vanila fendt 500 with agco 650 weight and modded Vaderstadt rapid 600-800 seeder
Map: Eielshort

https://www.youtube.com/watch?v=3Uqh4sOcgNE
https://gist.github.com/Siginek/58f88eedf5dd660615b595e9e9648188

**Comment by pvaiko** [comment]
This is not a pathfinding turn, this is just a simple generated Ohm turn. CP works as designed.

Try activating stay on field or add more headlands.

If you use a different pattern or skipping rows, so the next row is further away, only then will CP use pathfinding turn (when enabled).

**Comment by Siginek** [comment]
I have turn on fields active, but ill try more headlands ... anyway - there are still some fields which has place for one headland and my implements gets stuck there quite a lot - would it be possible ,to get option to use pathfinding even for turns when activated?

**Comment by pvaiko** [comment]
If you really have turn on field active then it is a bug, it should reverse before turning, reopen if that's the case.

**Comment by Siginek** [comment]
Well ... here i have another example - in this case there was no tree in the way, but 2 turns before this one it was and it got stuck, but as it was "on the edge" i would say, i wasnt sure if that would eb case enough - one wheel was in field, one was not so half of my spreader was outside and got stuck.

If this doesnt meet requirements to be concidered as bug, i can try to replicate this on another field with different implement, but i had this one ready, so i thought it might be.

https://gist.github.com/Siginek/f4f000cf1b089d59f3fb18d44c89e79a
https://www.youtube.com/watch?v=agAGXvalA3A

btw - can i reopen this issue? i dont see any button there as you closed it already

**Comment by Siginek** [comment]
![image](https://user-images.githubusercontent.com/77811548/106057049-b41a3a00-60ef-11eb-92f4-391394624dbb.png)
same course with one minor edit, Turn on field still active

**Comment by Mannie313** [comment]
mach mal Pathfinder darf rückwärts fahren aus.

Das geht nur bei nichtgezogenen geräte.

MFG Mannie313

**Comment by pvaiko** [comment]
So, in your video, you should deactivate AI turns and activate the pathfinding for turns, and it'll work, see https://github.com/Courseplay/courseplay/issues/6720#issuecomment-766340081

This is a good example where enabling pathfinding for turns is a good idea, because this is a wide, long turn.

**Comment by pvaiko** [comment]
See https://github.com/Courseplay/courseplay/wiki/Which-turn-to-use%3F
