### ISSUE TITLE
Turn on field - reopen another issue please

### ISSUE THREAD

**Issue by Siginek** [Courseplay/courseplay#6742]
Hi, i have added another log and video to issue https://github.com/Courseplay/courseplay/issues/6741 - could you reopen as pvaiko wrote, it as it seems to me, that there might be bug?

I dont see any option from my interface to reopen that issue so i created this one instead

**Comment by pvaiko** [comment]
See https://github.com/Courseplay/courseplay/wiki/Which-turn-to-use%3F
