### ISSUE TITLE
Vicon FastBale skips a lot of grass

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#6743]
https://youtu.be/eRJu5jXeoKU 

Is it possible to fix this?
I have made big swath windrow (19 meters) instead of usual 10 meters to finish the job quicker (less up/down rows), but baler now skips a lot of swath grass (same happens with hay and straw, but in smaller ammount because there is no wrapping which takes few seconds).
It seems that only solution is to use normal round baler with stop/go while unloading and in this case FastBale is useless...it is only useful if swath is smaller, like 10 meters.

**Comment by Tensuko** [comment]
Won't touch this.
We use GIANTS Baler functions, you might try it without REA.
