### ISSUE TITLE
Translation IT

### ISSUE THREAD

**Issue by garo73** [Courseplay/courseplay#6744]
Sorry if it is not the right section but I did not know where to write, I ask you to change an Italian translation, precisely "sul primo promontorio" in "sulla prima testata" on lines 490 & 491 of the translation_it.xml file
Thanks!

**Comment by Tensuko** [comment]
@Roby1164
you did most of the translation, can you check/discuss this and if need make a pull reuqest for the change ?
Thank you :)

**Comment by garo73** [comment]
Excuse me again! I didn't see that in the latest version (6.03.00033) the translation is correct!

**Comment by Tensuko** [comment]
No Problem buddy, thank you for correction :)
