### ISSUE TITLE
Work mode und Geräteversatz seitlich - geht nicht mehr

### ISSUE THREAD

**Issue by BrunoMoser13** [Courseplay/courseplay#6746]
Hallo ! Ich habe festgestellt, dass der Workmode z.B. beim Pickup nicht mehr geht. Damit verbunden ist auch der Geräteversatz seitlich nicht mehr möglich. 
Ich benutze das um z.B. die Strohballen aufzusammen indem ich den Fahrer versetzt fahren lasse. 
Was kann ich tun?

![image](https://user-images.githubusercontent.com/62007756/106152159-677d4000-617d-11eb-9d8e-f04956df07c6.png)

**Comment by Tensuko** [comment]
Was ist das für ein Trailer ?

**Comment by BrunoMoser13** [comment]
DPW 180 - mit Autoload.
Früher konnte ich mit dem Pickup und dem DPW 180 im Arbeitsmodus und dem Geräteversatz die Ballen einsammeln.

**Comment by Tensuko** [comment]
Wenn das ein normaler Autoload Script ist, dann ist dieser nicht unterstützt.

Die Trailer in diesem Pack haben quasie auch 'AutoLoad' basiert aber komplett auf der Lademechanik von normalen Ballensammelwagen (Tasten B und Z für die Kontrolle).
Diese funkionieren mit CP. https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=176857&title=fs2019
![fsScreen_2021_01_28_16_33_48](https://user-images.githubusercontent.com/27344744/106161175-f17dd680-6186-11eb-90a2-89db59f3d0c0.png)

**Comment by BrunoMoser13** [comment]
Aber es hat doch immer funktioniert. 
Seit ein paar Wochen tut es das nicht mehr.
Warum soll ich einen anderen Mod-Pack installieren?

**Comment by Tensuko** [comment]
Link zum Mod ?!

**Comment by BrunoMoser13** [comment]
Das Problem mit dem Arbeits-Modus habe ich auch mit dem LKW TGX. Dieser ist ebenfalls zum Ballensammeln mit Autoload und kann auch keinen Arbeitsmodus und Geräteversatz mehr. Konnte es aber früher einmal.

**Comment by BrunoMoser13** [comment]
Hier der link zum Trailer pack https://www.modhoster.de/mods/bdm-autoload-pack-hof-bergmann-version [https://www.modhoster.de/mods/bdm-autoload-pack-hof-bergmann-version ](url)

**Comment by Tensuko** [comment]
Ja wie ich gedacht habe, AutoLoad Script, nicht das GIANTS BaleLoad System.
Das wird nicht unterstützt und nur weil es mal ging heist es nicht, dass wir es supporten.
Es funktioniert eben nicht zusammen mit CP.

**Comment by BrunoMoser13** [comment]
Schade 😢

**Comment by Tensuko** [comment]
Überrede die Modder ein einheitliches Script zu nutzen (bevorzugt EasyAutoLoad), überzeuge den Modder von EasyAutoLoad Kontakt mit uns auf zu nehmen und dann können wir schauen, dass wir das EasyAutoLoad Script unterstützen, aber so wie es im 19er aktuell läuft das jeder sein eigens Script bastelt wird das nichts, sry.

**Comment by BrunoMoser13** [comment]
Der Mod - arbeitet aber mit dem easy auto load !?

**Comment by Tensuko** [comment]
Ja und ?
Habe ich gesagt, dass wir Easy Auto Load unterstützen ?

Lies mal meinen Satz richtig, solange sich nicht ALLE einig sind und der Modder von EasyAutoLoad dann auch mit uns arbeiten würde machen wir da GAR nichts. Sonst kommen alle an und sagen aber warum geht nur das AutoLoad und nicht das etc.

**Comment by BrunoMoser13** [comment]
Dann habe ich das falsch verstanden .... sry

Habe den Modder von EasyAutoLoad -alfalfa6945 kontaktiert und wg  der Kompatibilität mit CP gefragt.
Halte dich am Laufenden...
Lg
