### ISSUE TITLE
Combine approaching results in loop

### ISSUE THREAD

**Issue by thobck** [Courseplay/courseplay#6747]
Description:

I noticed an undesired behavior of the tractor when approaching the combine to load. The tractor arrives very close to the combine 
and the expected behavior would be that it would stop in line with the pipe to start loading. 
But instead of stopping the tractor, it accelerates and ends up losing the loading point and then the tractor starts a left turn 
to try again to approach the harvester. This results in loop and the tractor never loads the harvester.

The tractor's unwanted behavior can easily be seen when the tractor approaches the already stopped harvester (grain tank is full) 
from the front left of the harvester and needs to turn 180 degrees to the left to align with the harvester barrel.

Version:
CoursePlay SIX 6.03.00032

Map:
Big Fields Farm - NinjaCurt - version 1.0.0.0 (mod: yes)

Vehicles in use:
CASE IH 9240 (mod: no)
CASE IH OPTUM 270 CVZ (mod: no)
ELMER´S MANUFACTURING HAULMASTER (mod: no)

**Comment by Tensuko** [comment]
#5272 https://github.com/Courseplay/courseplay/wiki

**Comment by thobck** [comment]
log file
<script src="https://gist.github.com/thobck/3e77008097d2f176030f1d059ddd89c3.js"></script>

**Comment by Tensuko** [comment]
That didn't work

**Comment by thobck** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5889006/log.txt)

**Comment by thobck** [comment]
Please see this video
https://drive.google.com/file/d/1Ga0oE3rHmkix6rxSan8T906QYwRUsNMd/view?usp=sharing

**Comment by pvaiko** [comment]
@thobck you should either turn fruit avoidance *on* for the combine or *off* for the unloader, see also https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ#how-avoid-fruit-works

**Comment by thobck** [comment]
It works fine to me now.
Thank you very much for your prompt reply.
Congratulations for your great work on improving CoursePlay.

Em qui., 28 de jan. de 2021 às 15:12, Peter Vaiko <notifications@github.com>
escreveu:
