### ISSUE TITLE
Driver with forage wagon will not pull forward in bunker after initial tip

### ISSUE THREAD

**Issue by windy1664** [Courseplay/courseplay#6748]
[log.txt](https://github.com/Courseplay/courseplay/files/5888847/log.txt)

Driver will not pull forward in bunker after tipping, trailer still half full but he wont move forward

**Comment by Tensuko** [comment]
Screenshot?
It does work, place unload here WP at the back, also keep in mind, that any trailer will perform the full unload animation (a pusher will move the pusher untill the end) before he drive forward to unload.

**Comment by windy1664** [comment]
![fsScreen_2021_01_28_19_20_44](https://user-images.githubusercontent.com/60709362/106187871-1fbae080-619e-11eb-925c-81f9b90b0766.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5889572/log.txt)

**Comment by windy1664** [comment]
![Uploading fsScreen_2021_01_28_19_31_07.png…]()

**Comment by kaddyuk** [comment]
Regular trailers work okay, this particluar wagon won't.

**Comment by windy1664** [comment]
Hi, thanks for the reply, does this mean any forage wagon will not work?

**Comment by polosubtil** [comment]
I haven't tried different forage wagons, but I have the same issue you have with the vanilla BERGMANN REPEX 34S.
But in my case, it's not a major issue as usually there is enough space to unload without moving forward, I only get stuck when the bunker is almost full.

**Comment by polosubtil** [comment]
Ok I have run some tests, it works with a forage wagon using mode 2, it move forward when it needs more space to unload.
So it's not really related to the equipment but to the mode you use

**Comment by Tensuko** [comment]
@polosubtil thank you for checking this, will have a look at this!

**Comment by Tensuko** [comment]
@schwiti6190 the function gets called at line 127, but somehow it does not work ?

**Comment by Tensuko** [comment]
Fixed with 6.03.00042
