### ISSUE TITLE
The game freezes when switching to the completing assistant 

### ISSUE THREAD

**Issue by vitalii2011** [Courseplay/courseplay#6750]
This route  https://i.imgur.com/MjSGW6b.png 
Equipment leased by contract https://i.imgur.com/D5PuRoE.png 
When a message appears about the arrival of an assistant at the trigger point and an attempt is made to switch to him https://i.imgur.com/lIqQdV0.png
log: https://gist.github.com/vitalii2011/76f58ff512996887cb37e55f11581e68

**Comment by Tensuko** [comment]
Wasn't able to reproduce this.
This is also a Callstack of GIANTS Script.
Did you finish the mission before click on the message ?

**Comment by Tensuko** [comment]
Did try it again and I can't reprodice this.
Sry buddy but that must be some kind of mod Issue or Mod conflict on your side...

Closing, reopen if you find out something.

**Comment by vitalii2011** [comment]
> 
> 
> Did try it again and I can't reprodice this.
> Sry buddy but that must be some kind of mod Issue or Mod conflict on your side...
> 
> Closing, reopen if you find out something.

I tried it from 6.03.00032 - it was repeated. I don't use Courseplay often, and with which version this problem appeared, I can't say for sure, this was not the case before. Anyway - thanks for your tool, now I'll just save before moving around the technique.
