### ISSUE TITLE
Aladen am Feldrand mit Rübenernter nicht mehr Möglich ?

### ISSUE THREAD

**Issue by Playlord75** [Courseplay/courseplay#6752]
Moin ich hätte mal eine frage ist es im ls19 nicht mehr möglich wie im ls17 zuckerüben am feldrand per cp abzuladen 
![fsScreen_2021_01_29_12_44_16](https://user-images.githubusercontent.com/71101944/106272044-b0420100-6230-11eb-9aa7-1deeacbd28e5.png)
hab es schon mit einigen sachen probiert 1 abladepunkt,  2abladepunkte oder eien warte punkt er fährt kurz das rohr aus sagt abladepunkt ereicht fährt weiter und fährt das rohr wieder ein und fährt weiter aber lädt nicht ab

**Comment by Tensuko** [comment]
Nein, das geht mit dem Rübenernter nicht mehr.
Wenn wir uns mit dem Überlader beschäftigen, dann sollte das mit dem wieder gehen, ansonsten normale Abfahrer benutzen.
