### ISSUE TITLE
Fruchtzerstörung

### ISSUE THREAD

**Issue by hemker500** [Courseplay/courseplay#6753]
Hallo zusammen,
Wäre es eventuell möglich über einen Menü punkt die Fruchtzerstörung des CP Ein oder Auszustellen?
Falls dies nicht möglich ist,in welcher lua kann man dies sich selber aktivieren,hatte dies damals mal gefunden nur jetzt leider nicht mehr.

Mit Freundlich Grüßen :)

**Comment by Tensuko** [comment]
Wollen wir erst mal nicht. #5541
