### ISSUE TITLE
BUG: "Lösche Wegpunkte bis Start" funktioniert nicht

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#6754]
Hallo Leute
habe heute festgestellt das der Befehl
"Lösche Wegpunkte bis Start"
im CP-ingame Editor nicht funktioniert, "Lösche Wegpunkte bis Ende" funktioniert hingegen
v 6.03.00033
lg
andreas

**Comment by Tensuko** [comment]
Interessant... #6297

**Comment by andreasthu** [comment]
ok, blöd von mir,
hab zwar alle 4 seiten durchgesehen, aber den Beitrag auf der 2. seite wohl übersehen
sorry
habe diese funktion aber bisher nicht gebraucht.
wollte einen CP kurs mähen, 3x rundherum und dann hoch-runter für den Schwader quasi umdrehen,
also das erst hoch runter geschwadet wird und dann 3x rundum weil der Schwader beim Wenden immer soviel Heu aus den Rundherumbahnen wegschwadet.
lg
andreas

**Comment by Tensuko** [comment]
Nutze die Suche oben, `Editor is:open ` dann findest du alle offenen Issues die was mit dem Editor zu tun haben :)

**Comment by andreasthu** [comment]
Ok, danke
Lg
Andreas
