### ISSUE TITLE
End at the endpoint or trigger function

### ISSUE THREAD

**Issue by themicki** [Courseplay/courseplay#6755]
Hello this is not really an issue, more like a question.
I always had a good use from the fact that CP drivers don't stop automaticaly at the end of the course, but instead go back to the start point and start all over again.
This feature has been removed and now the driver always stopps at the end of the course.
Is it still possible to create "infinite" courses that will always start over again? Or if not could you please make this possible again.
Greetings Micki
P.S. thanks for your amazing work!

**Comment by Tensuko** [comment]
Nope. Becouse it got no real use.
