### ISSUE TITLE
Cp auf dem dedi Server

### ISSUE THREAD

**Issue by Reiko40** [Courseplay/courseplay#6757]
Hallo
Ich hatte heute folgendes Problem auf meinem Server: Ich habe einen Drescherkurs mit 2 Drescher im Verbant generiert und gespeichert.Musst dann den Server neustarten da ich in einem anderen Fahrzeug den Standarthelfer nicht aktivieren konnte. Nach dem Neustart konnte ich nicht mehr auf dem Server als ich den Kurs mit den 2 Drescher gelöscht habe konnte ich wieder rauf. Nur habe ich jetzt das Problem das ich Cp nicht mehr öffnen kann. Ich habe die Tastenbelegung schon geändert nur ohne Erfolg. Ich spiele auf der aktuellen Irgendwo in Thüringen und habe Cp die Version 33.
MfG
Reiko

**Comment by Tensuko** [comment]
logfile? Server und Client.
Hattest du das Savegame mal runter geladen und wieder rauf geladen ?

**Comment by Reiko40** [comment]
Sorry log hatte ich vor Neustart gelöscht. Habe den Spielstand mal ohne Cp gestartet und gespeichert  dann Cp wieder aktiviert und gestartet und jetzt habe ich den Hud wieder und lässt sich problemlos öffnen. Mein Server läuft bei Gamed und heist Reikos Welt

**Comment by Tensuko** [comment]
Ja wenn es nun wieder geht ist ja gut.
