### ISSUE TITLE
Stuck on synchronizing with other players on MP server

### ISSUE THREAD

**Issue by pitcrew48** [Courseplay/courseplay#6758]
Join a server, then synchronizing with other players shows up with a frozen loading wheel. Shortly after, loading wheel will spin but no options appear. Hitting the A button on my controller (same as start game key on keyboard, using Xbox controller), I hear a click but no response. Hitting the B button places me under the map and game freezes. Thanks!
[log.txt](https://github.com/Courseplay/courseplay/files/5899019/log.txt)

**Comment by Tensuko** [comment]
You should rly question yourself, if you need all those Mods.... I mean it is like 20 (?) different JDs ?
Also some of your Mods throw Errors in .lua files, that should be fixed or removed.

**Comment by andremeyer123** [comment]
Delete  inputBinding 
DDM_HarvesterPack_v1_2_FJ 
delete all mods to me this error then test again
Error: Can't load resource

**Comment by Tensuko** [comment]
Rly sure this is becouse of Mod Chaos.
Clean it up.
If you find a real LUA Error with CP let us know.
