### ISSUE TITLE
CP and AD in combi mode

### ISSUE THREAD

**Issue by ninjayx02** [Courseplay/courseplay#6759]
Well,  It must be me,  but since updating both CP and AD I cannot fathom out how to use the CP combi mode with AD.  Granted,  I haven't used it for a while, but last time I used it was on the Western Australia map and had no problems at all.  Pointers on how to resolve this would be greatly appreciated as CP and AD are 2 of the best mods available

**Comment by Tensuko** [comment]
#5284 pls use the search function.

**Comment by ninjayx02** [comment]
I've used the search function and found nothing that helps

![image](https://user-images.githubusercontent.com/49168998/106391795-fe990080-63e6-11eb-979b-a9645a0b9a61.png)
I get that in the log

**Comment by Tensuko** [comment]
I even marked you the Issue: #5284 and I just searched for 'AutoDrive' and directly found it!
