### ISSUE TITLE
Bearbeitung Feldrandkurs

### ISSUE THREAD

**Issue by MarkusRost** [Courseplay/courseplay#6760]
Hallo,

vermutlich einfach ein ziemlicher Benutzerfehler aber vielleicht könnt ihr mir ja trotzdem weiterhelfen.

Ich habe zwei Felder, die ich zusammengelegt habe mit dem Pflug, die eigentlich noch durch eine Straße getrennt sind. Nun habe ich vermutlich mit dem Pflug im Modus "Felder erstellen zulassen" einfach zu stark die Straße erwischt. Auf jeden Fall berechnet mir Courseplay nun den Feldrandkurs über beide Felder.

Kann ich den Feldrankurs irgendwie an meine Felder anpassen?

Danke

Gruß
Markus

**Comment by Tensuko** [comment]
> Ich habe zwei Felder, die ich zusammengelegt habe mit dem Pflug, die eigentlich noch durch eine Straße getrennt sind.

Also entweder du hast das Feld zusammen gelegt oder es ist getrennt...



> Auf jeden Fall berechnet mir Courseplay nun den Feldrandkurs über beide Felder.

Wie oben gesagt, entweder zusammen gelegt, oder getrennt.

Der Feldrandkurs der berechnet wird, orientiert sich an der Feldgrenze. Wenn du einen Übergang von Feld zu Feld geschaffen hast, dann sind die auch zusammen gelegt.

Aber ich weis halt nicht was genau du jetzt willst.

**Comment by MarkusRost** [comment]
Ok, danke für die Antwort.

Kann ich den Feldrandkurs bearbeiten so dass ich die Felder für cp wieder getrennt hab?

Ansonsten ich schauen wie ich sie ansonsten wieder getrennt bekomme.

**Comment by 60erjonny** [comment]
Hallo
In LS gibt es eine Walze, die den ursprünglichen Feldzustand wieder herstellt.
Das Spiel dann neu starten und CP berechnet die Felder dann wieder neu...

**Comment by dete96** [comment]
Hi!
Oder du fährst den Feldrandkurs manuell so ein, wie du ihn gern hättest. Das ginge auch...
Viel Erfolg!

**Comment by Tensuko** [comment]
Ich würde mit dem Ingame 'Maltool' einfach gras zwischen die Felder malen, da wo du sie getrennt haben willst, dann wieder jedes einzelne Feld den Feldrandkurs berechnen lassen und die Nummer hinzufügen.

@dete96 viel zu Aufwendig.

**Comment by MarkusRost** [comment]
Danke!

Und sehr cooler mod!
