### ISSUE TITLE
Delete waypoints to start issue ?

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#6761]
I can delete waypoints to end, but i cant delete waypoints to start...i even tried remapping key to LCTRL + 3 or 4 or something different, but it doesnt work.
Is this maybe the issue, wrong name, it says Wayoints instead of Waypoints ?
![FarmingSimulator2019Game 2021-01-31 22-55-12](https://user-images.githubusercontent.com/32069662/106399247-c78f1300-6417-11eb-991c-5c17b3673a7c.jpg)

**Comment by Tensuko** [comment]
#6297
