### ISSUE TITLE
Worker skips parts of the field with plow

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#6762]
If you need any debug channel, let me know.
I am using latest version of CP.
Course is created with 5 headlands, started working from up/down, then headlands.

The white part of the field is unplowed, worker simply skips it.
![FarmingSimulator2019Game 2021-02-01 12-55-38](https://user-images.githubusercontent.com/32069662/106455965-39557400-648d-11eb-97ae-9ff2ff07cd12.jpg)

**Comment by pvaiko** [comment]
I need your field definitions (https://github.com/Courseplay/courseplay/wiki#how-to-post-your-field-definitions) and a screenshot of the course generator when you created this course.

**Comment by bojanh66** [comment]
[cpFields.zip](https://github.com/Courseplay/courseplay/files/5904958/cpFields.zip)
![FarmingSimulator2019Game 2021-02-01 16-50-37](https://user-images.githubusercontent.com/32069662/106482994-551d4200-64ae-11eb-9476-f8a51b64510b.jpg)

**Comment by Commissar0617** [comment]
does it look similar to #6652 ??

**Comment by bojanh66** [comment]
I dont think so, because i am using small plow and only 1 worker and it happens only on headland which is cutting up/down rows in half (take a look at Start position and next 4-5 rows)
If you see on the picture the limed part of the field is skipped by worker, only because headland is cutting those up/down rows.
I think worker should continue over the headland and finish the up/down row, but instead of that, once he reach headland that is cutting up/down row, he turns around and continue doing next row, so the other half of up/down rows stay unplowed.
