### ISSUE TITLE
"Release CP Worker" Dedicated Server

### ISSUE THREAD

**Issue by daver18qc** [Courseplay/courseplay#6763]
The option to release the worker after the job is done works in solo but not on my rented dedicated server.
Just wanted to let you guys know! (love this option and wish this will work on my server eventually :D )

![fsScreen_2021_02_01_14_58_40](https://user-images.githubusercontent.com/6185896/106515668-01a5f680-64a4-11eb-8926-bd27da0f7d4f.jpg)

**Comment by andremeyer123** [comment]
yes that's missing for mp
