### ISSUE TITLE
log error

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#6765]
I tried to start my career on FS as usual, after loading I got on the John Deere 7250R with the Valzelli slurry tank to slurry the field but I noticed that as soon as I moved the tractor manually the fps dropped drastically. I switched to the John Deere 8295R with the Moro plow and also there same thing (both tractors I manually moved them for a few minutes but I had used them yesterday with the CP). Suspicious, I checked the game log and noticed that it gave some particular errors (which I think are attributable to the CP)

[log.txt](https://github.com/Courseplay/courseplay/files/5910651/log.txt)

**Comment by 0Pietro20** [comment]
I also tried with a new game and I noticed that the drastic drop in fps only occurs if as soon as any vehicle is put in motion, as soon as it stops the fps return stable

**Comment by pvaiko** [comment]
I see a few error messages from CP but those are when attaching an implement at game load, indicating problems with some mods.

Other than that, I see no error message in there, also, if I understand it correctly, you are seeing the FPS drop when manually moving the vehicle which is highly unlikely if it is a CP problem.

**Comment by 0Pietro20** [comment]
I understand, thanks for the help. At this point I have no idea what it could be since when I move the character or use the train it does not give any problems, when I get on a vehicle everything is ok, but as soon as I move it the fps collapse

**Comment by 0Pietro20** [comment]
I believe the problem lies with the video card. It is probably the updated drivers that give these problems. Because I tried to lower the graphics details of the game to a minimum and it runs without frame drops. The problem is that without saturating neither the ram nor the Vram it goes to 20 fps. I was playing in high details (custom) and, while saturating the ram and Vram, the game kept 40/50 fps. I don't have a very performing hardware (Intel i5-7500 @ 3.4 Ghz, 8gb of ram at 2400Mhz (yes I know I should bring to 16gb for a smoother game) and a Gigabyte Windforce 3x r9 280 OC) but for FS without particular pretended I'm satisfied

**Comment by 0Pietro20** [comment]
I restored old versions of the Radeon Software and the game is back to working perfectly
