### ISSUE TITLE
problem with mode 1

### ISSUE THREAD

**Issue by ice81rm** [Courseplay/courseplay#6766]
Hello everyone!
I have a problem with mode 1

When I activate it to take from a silo and unload to the animals, no problem ...

The problem arises when I want to start it from the sidelines or when I empty a trench. The tractor continues to drive without waiting for it to be full
![Screenshot (278)](https://user-images.githubusercontent.com/39805100/106627587-3b94fc80-6579-11eb-8df9-d3a89b7ecc20.png)

**Comment by Tensuko** [comment]
Remove the filltype, when you load on start, it gets loaded and it doesn't matter what you put into it.
https://github.com/Courseplay/courseplay/wiki/Mode-1-Changes
