### ISSUE TITLE
Auto drive and courseplay 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#6767]
Hello I’m on the very latest version of courseplay and I’ve noticed in advanced settings tbe autodrive option has gone to say wether to unload etc. Is this not needed now? I’m trying to get tbe hang of using both auto drive and. Courseplay and noticed in videos tbe old settings were there

**Comment by Tensuko** [comment]
As some ppl wished, it is now on the Page1 on the HUD. Where you also start and stop CP driver.

**Comment by matty2123** [comment]
Have you got a picture I can’t find it on my hud?
