### ISSUE TITLE
Feature Request: "Pause Time" to hand off to AutoDrive

### ISSUE THREAD

**Issue by jtsage** [Courseplay/courseplay#6768]
Apologies if there is already a good way to do this, but I have not found it - the mod is incredible by the way.

Part of my usual workflow is to set an AutoDrive "Load" route with the work field as the destination, and the implement refill point at the load (seed, fertilizer, etc) Then, load the field work course in CP, toggle the AD "toggle CP at destination", and let the vehicle drive itself to the buy point, load up, go to the field, work while refilling as necessary, and for those vehicles that currently support it, return to it's parking space (via CP).

The problem I have on a few vehicles is that the handoff to AutoDrive happens too fast at the end of the fieldwork course - the implement or machine is still in the process of folding, and promptly runs into everything - the most obvious is the Hardi Rubicon with it's giant, slow folding booms.  It would be great to have a gui option to just have CP wait a few (configurable) seconds before handing off control. (Alternatively, knowing when the implement has folded, but as this isn't the current behavior, my guess is that it isn't an option)

Thanks for your hard work.

**Comment by envikowaty** [comment]
To sort out this situation I'm using simple trick: I always setup start point CP at least while Wilson A train length, so when for example I want to use rubicon:

1 from parking drive to refill point using AD
2 after refill go to target ( filed for example no 2) and start CP
3 drive goes to the field no 3 using AD and starts the CP ON THE END.


The trick is to always make a gab between AD Target point and CD start point

**Comment by Gibbanator** [comment]
I'm so confused
