### ISSUE TITLE
All Tools in a convoy are 1/x if course got no headland (.00034 and lower)

### ISSUE THREAD

**Issue by Thorn177** [Courseplay/courseplay#6769]
Version 6.03.00033
When setting up multi vehicle routes across modes 4 and 6, all the vehicles are the lead one.  As you add them, the number of vehicles in the convoy increments, but they all set themselves as the lead vehicle.  

Flow on effects from this cause the minimum distancing between vehicles to be ignored when vehicles stop for unloading or refilling.

The actual lead vehicle runs the course to the end.  Subsequent vehicles announce they have finished about a vehicles length back from the one in front of them, leaving an increasing amount of unfinished work in each subsequent lane.

The course appears in the "copy course" option the same number of times as vehicles already setup in the convoy rather than once.

**Comment by Tensuko** [comment]
No Idea what you did, but this is definitly not happening.
If you want 2 or more Vehicles to run one course, you do the following:
Open the Course Generator and tell it how many Tools run on one Course (lets say, 3).
Generate the Course and save it.
Load THAT course on each of the Vehicle you want to drive on that course.
Each Vehicle will have the offset options Left/Front(or Mid?)/Right.
Put each Vehicle on one Offset and start the course.

The only problem we have right now is, that the distance gets not calculated correctly, when you use Headland on very big fields, a patch for this is on the way.

**Comment by Thorn177** [comment]
Three vehicle simple up and down route.  !st vehicle right, 2nd center, 3rd left.
![fsScreen_2021_02_04_01_15_36](https://user-images.githubusercontent.com/57279160/106785488-691c9b80-6688-11eb-8775-54dc33980e1d.png)
Vehicle one on initial setup.  Convoy 1/1
![fsScreen_2021_02_04_01_16_31](https://user-images.githubusercontent.com/57279160/106785664-99fcd080-6688-11eb-816a-d4746f68d436.png)
Vehicle two on initial setup.  Convoy 1/2
![fsScreen_2021_02_04_01_20_08](https://user-images.githubusercontent.com/57279160/106785788-c3b5f780-6688-11eb-989b-47912a301277.png)
Vehicle three on initial setup.  Convoy 1/1 (First time I've had that - was expecting 1/3)
![fsScreen_2021_02_04_01_22_16](https://user-images.githubusercontent.com/57279160/106786172-37f09b00-6689-11eb-8adf-c09346615972.png)
Vehicle one on the course with all three active.  Convoy 1/3
![fsScreen_2021_02_04_01_22_22](https://user-images.githubusercontent.com/57279160/106786479-8bfb7f80-6689-11eb-8845-2da316f3faff.png)
Vehicle two on the course with all three active.  Convoy 1/3
![fsScreen_2021_02_04_01_22_29](https://user-images.githubusercontent.com/57279160/106786643-bcdbb480-6689-11eb-8949-dbeb794ba2e4.png)
Vehicle three on the course with all three active.  Convoy 1/3

**Comment by Tensuko** [comment]
Will check this, give me some time pls.

**Comment by Tensuko** [comment]
Damn, this is a bug in 33 and 34 too.
But it only happens if you have a course without headlands.

**Comment by pvaiko** [comment]
Logfile with channel 14, anyone?

**Comment by pvaiko** [comment]
Oh, sorry, I'll also need channel 7 activated before starting the vehicles on the course.
