### ISSUE TITLE
Time Out bei Kurs Generierung 

### ISSUE THREAD

**Issue by TinoBlack** [Courseplay/courseplay#6770]
Jedes mal wenn ich auf meinem Dedi Server Versuche einen Kurs zu generieren Fliege ich vom Server. Mein Kollege kann alle Kurse Problemlos für mich generieren. Wenn ich im Singelplayer bin oder selber einen Server Hoste habe ich das Problem nicht

**Comment by Tensuko** [comment]
logfile ?!

**Comment by TinoBlack** [comment]
Wo bekomme ich den her?

**Comment by Tensuko** [comment]
Das ist das richtige file.
Aber sowas gehört schon mal nicht in den Mods Ordner:
Error: Failed to open xml file 'C:/Users/Maik/Documents/My Games/FarmingSimulator2019/mods/FS19CheatsTool/modDesc.xml'.
Available mod: (Hash: 52f5e39518653e0d53e2c249445bf18f) FS19CheatsTool
Error: Missing descVersion attribute in mod FS19CheatsTool

Oder sowas:
Error: Failed to open xml file 'C:/Users/Maik/Documents/My Games/FarmingSimulator2019/mods/UnzipMe/modDesc.xml'.
Available mod: (Hash: 892d646bc38b537829247254f13fb259) UnzipMe
Error: Missing descVersion attribute in mod UnzipMe


Ich seh in der log auch keinen Error von CP und du solltest dir vlt überlegen, ob du all diese Mod brauchst.... ich habe auch relativ viele aber du hast fast 3 mal so viel.
Nach Maps habe ich jetzt nicht weiter geguckt, aber wichtige Regel: nur eine Map im mods Ordner!

Debugchannel 7 einschalten, Kurs versuchen zu generieren, dann das logfile chicken.

**Comment by TinoBlack** [comment]
Habe besagte mods entfernt und auch alle maps rausgeschmissen. Dann gestartet und den channel aktiviert. Das ist ganz am ende vom log aber schlau werde ich daraus auch nicht [log.txt](https://github.com/Courseplay/courseplay/files/5936589/log.txt)

**Comment by Tensuko** [comment]
Sah jetzt nicht danach aus, dass es nicht geklappt hat, hat er in dem Fall einen Kurs generiert ?

**Comment by TinoBlack** [comment]
Ja der Generiert den Kurs und zeigt mir den im Menu auch an. Aber sobald ich das Fenster Verlasse fliege ich vom Server. Ich hänge einfach mal ein Video an  ( https://youtu.be/dwkcNteXDv0 )

**Comment by Tensuko** [comment]
Und wenn genau DAS passiert, DAVON brauchen wir das logfile, es muss ja ein Error kommen.
log.txt und log vom Server. Alles andere hilft nicht.

**Comment by TinoBlack** [comment]
Der Logfile ist der letzte den ich gepostet habe ist ja genau von diesem Moment. Das ist jetzt der Server Log da steht aber auch nur das ich geleavt bin 
[Game.log Server.txt](https://github.com/Courseplay/courseplay/files/5937860/Game.log.Server.txt)

**Comment by Tensuko** [comment]
Ich kann damit aber nichts anfangen.
Ohne Error oder Beschreibung wann bei was der Timeout kommt, können wir rein gar nichts machen.
Welche Map, welches Feld, welche Einstellungen...
Ich spiele ja selber auf nem MP Server und da gab es noch keinen Timeout, die Warscheinlichkeit, dass es an CP liegt ist gering und wenn, dann müssten wir überhaupt erst mal einen Fehler sehen und gesagt bekommen, wie der entsteht.

**Comment by TinoBlack** [comment]
Das ist ja das Problem was ich habe ich weiß nicht woran es liegen könnte. Es war von jetzt auf gleich so. Haben dann auch mal nen neues Safe game gemacht und den Server neu aufgesetzt aber es hilft alles nicht. Sobald ich einen Kurs Generiere , egal auf welcher map, für welches Feld, für Welche Maschine oder Anbaugerät ich Fliege immer vom Server

**Comment by Tensuko** [comment]
Welche Map spielt ihr denn und welches Feld und welche Einstellungen vom Editor ? (Screenshot)

**Comment by TinoBlack** [comment]
Map ist Niedersachsen 21, das passiert bei jedem Feld auch unabhängig von den Einstellungen

**Comment by Tensuko** [comment]
Also das hier muss auf jeden Fall raus, weil das wird euch das wird euch Probleme machen:
(Version: 1.0.0.0) FS19_TowingChain


Aber ansonsten kann ich dir da kaum weiterhelfen, wenn kein Fehler kommt und das nur bei dir passiert....

Was du noch mal machen könntest, wäre dein Shader Cache leeren (weis nicht warum da ein Zusammenhang sein sollte, aber man weis ja nie...).

Oder was komplizierter wäre, Script Mods nach und nach raus nehmen, REA, RealDirt.... irgendwas bei dir muss ja die Synchronisation killen in dem Moment, aber ich weis nicht warum das durch CP Kurs generieren passiert...

**Comment by TinoBlack** [comment]
Habe den mod gelöscht und den Cache gelehrt. Das bringt leider auch nichts. Ich denke mal es ist ein lokales Problem bei mir. Meine Kollegen können auf dem Server ja auch alle Kurse generieren. Ich habe nur leider nicht so viel Ahnung, ich denke ich werde einfach mal das spiel neu installieren und die Mods mal alle runterschmeißen

**Comment by Tensuko** [comment]
Ja wenn es bei den anderen geht, dann muss es irgendwas bei dir sein. Tut mir leid wenn ich dir da nicht weiter helfen kann.

Aber es scheint ja kein CP Problem zu sein, ich mache daher hier zu.

Fals dann noch immer Probleme sind, versuchs mal in einem Discord, ob jemand anderes ähnliche Probleme hatte oder weis was das Problem ist, ich bin da leider Ratlos...
