### ISSUE TITLE
Autodrive hud 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#6771]
Hello further on to my last issue about autodrive and the issue being closed you said tbe autodrive is on page 1 of tbe hud I’m on tbe latest version and I can’t see no option can you put a picture so I can see if I’m looking right?

**Comment by Tensuko** [comment]
becouse I rly got no mood to restart my save to add autodrive jsut to show you this I copy the pic from a YT Video.
Also see this: http://courseplay.github.io/courseplay/en/manual/index.html#hud_driverControls
![ad on cp](https://user-images.githubusercontent.com/27344744/106788248-01972980-6651-11eb-9b19-d13fff91b56e.PNG)
