### ISSUE TITLE
Autodrive hud

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#6772]
Jeez what’s happened to support here I use to donate for courseplay and that’s how you speak to people. Instead of closing can I not ask why my hud is not showing the autodrive option? See pic as this is what is happening 
![B3CFE126-10DD-432B-B6E7-6CDB6EDC8B5B](https://user-images.githubusercontent.com/27097241/106791447-d3174f80-664c-11eb-961b-0e673db3dcac.jpeg)

**Comment by Tensuko** [comment]
1st) stop open new Issues, closed is NOT the same as on Forums, you can still post there and have more patience I can't answer all of you at the same time.
2nd) What about read the manual ? I did post you the link to it!
Read it:
![AD](https://user-images.githubusercontent.com/27344744/106795695-aec26f80-665a-11eb-8c32-2bea27ce5b41.PNG)

How much more do I have to show you ?!
You are not even on a AutoDrive Supported Mode, like Fieldwork or Fertilizing and Seeding.
And even then you need a course, that option is only there when you actually CAN use AutoDrive.....

**Comment by Gibbanator** [comment]
you need to add an attachment to your tractor like a trailer, plow etc... Once  you do that than click the fieldwork area that is available than the Autodrive area will be there.
https://i.gyazo.com/d7d8d682865ad4d651955d6ec9d0b377.png
https://i.gyazo.com/d7d8d682865ad4d651955d6ec9d0b377.png
