### ISSUE TITLE
Grain Cart Not Stopping At The Same spot to unload and Combines not keeping distance 

### ISSUE THREAD

**Issue by Iam74Niner** [Courseplay/courseplay#6773]
I have v6.03.00033 i set up the grain cart to unload 2 combines and unload to a truck on the side of the field it has no issues with the combine unload however when it come to unload to the truck it will not stop in the same place one time it may be before the truck the next time it will be after even though the path tell it to stop at the 1st bin of the truck.   aslo not a big deal i just keep speed down on the trailing combine but when i have convoy activated and set to 100 150 200 it don't matter it wont stop it will run straight into the front tool   any help will be greatly appreciated .

Thanks - Mike

**Comment by SteveMcAus** [comment]
I have experienced the same issue with the grain cart not stopping in the same location, i haven’t tried with the latest build  is I tried it a few months ago and had the same problem

**Comment by Mannie313** [comment]
Hast du einen wartepunkt gesetzt wo er überladen soll.

MFG Mannie313

**Comment by Tensuko** [comment]
> it will not stop in the same place

That place have to be a waitpoint and the augerwagon driver have to be used in Mode3.



>  aslo not a big deal i just keep speed down on the trailing combine but when i have convoy activated and set to 100 150 200 it don't matter it wont stop it will run straight into the front tool any help will be greatly appreciated .

This I don't understand and is a complete drifferen problem.
Where do you set Convoy, for what Tools, and where does it run into ?
Convoy is for Fieldwork Tools to keep distance. There just came out a fix for the distance.

But what  do you actually try to do ?

**Comment by Iam74Niner** [comment]
That place have to be a waitpoint and the augerwagon driver have to be used in Mode3.
It is used in mode 3 and wait point is set for 1 min   it will overshoot or undershoot the wait point 

Where do you set Convoy, for what Tools, and where does it run into ?
Convoy is for Fieldwork Tools to keep distance. There just came out a fix for the distance.

I set convoy for the 2 combines    combine 1 will run into combine 2 and it will not keep the distance away from hitting it

**Comment by Tensuko** [comment]
Waitpoint in that case have nothing to do with minutes. It is just a point where we overload, maybe you should try to remove the waittime.

There is another fix for Convoy in Version 6.03.00035 when not use Headland.
Tested and it does work just fine. Try it out.

**Comment by Tensuko** [comment]
This should help for Overloader. If that is the Problem here...
https://www.youtube.com/watch?v=YhB5EXQfqIE

**Comment by Tensuko** [comment]
Status ?
Showed in the Video how to and that it does work, did you manage to get it working and found whats wrong ?

**Comment by Iam74Niner** [comment]
Nope you guys did do a update. That should of fixed it but by then I was just running truck straight to the combines

**Comment by Tensuko** [comment]
Well I guess I can close this, it should work now if not you know the Informations that we need.
