### ISSUE TITLE
Unterschiedliche Warteposition Drescher beim entladen.

### ISSUE THREAD

**Issue by Alaxsxag** [Courseplay/courseplay#6774]
Beim entladen des Dreschers bleibt der Drescher unterschiedlich stehen. Einmal bleibt er  stehen und fährt etwas zurück. Das ist O.K. Beim nächsten Abladen fährt er zurück, dann vorwärts 90 Grad rechts und bleibt quer zur Spur stehen. Ein entladen durch den Abfahrer schlägt dann fehl. Dass passiert öfter, aber nicht regelmässig.

**Comment by Tensuko** [comment]
Ohne logfile mit channel 4 7 12 und 14 und ohne Bilder nützt diese Information nichts.

**Comment by Tensuko** [comment]
Closed due to inactivity.
Reopen if getting requested informations.
