### ISSUE TITLE
Speicherprobleme Feldkurse.

### ISSUE THREAD

**Issue by Alaxsxag** [Courseplay/courseplay#6775]
Je mehr und vor allem grössere Feldkurse ich abspeichere, um so länger dauert das Laden und speichern der Kurse (bis zu 2 Minuten und mehr).
z.B. Map Wild West.
82 Felder gesamt. Davon habe ich 22 Felder (17ha bis 820ha Feldgrösse). Vor allem bei Feldern ab 100 ha aufwärts dauert das anlegen der Feldkurse sehr lange und manchmal hämgt sich dabei auch das Spiel auf.

Ich habe also 22 Felder und 10 unterschiedliche Arbeitsbreiten = 220 Kurse. Mit jedem neuen Kurs den ich anlege, wird CP immer langsamer.

**Comment by RalfGorden** [comment]
ist doch auch logisch

**Comment by Tensuko** [comment]
CP HUD, erweiterte Einstellungen, Kurse laden am start deaktivieren. Dann werden nur die geladen, die beim speichern in Maschinen geladen waren. Dann dauert es aber, wenn man dann einen Kurs aus der Liste lädt.

Ansonsten ist das ist normal, war schon immer so und wird sich auch nicht ändern.

**Comment by Alaxsxag** [comment]
Na wenn das normal ist und das auch so hingenommen wird, habe ich aber erhebliche Zweifel an den Entwicklern.
Da hat man fetzen Rechner mit superschnellen SSD und dann bremst einen das Speichern und Laden so eines Progrämmchens einen aus. Es ist ja nicht so, dass alle Kurse im RAM gehalten werden müssen.
Und ja -Kurse beim Start laden habe ich bereits deaktiviert. Es liegt definitiv an CP Speicherverhalten, dass eher an Diskettengeschwindigkeit rankommt als an modernen Speichermedien. Lege ich die Kurse temporär an (über aktuellen Feldrand ermitteln), geht das wesentlich schneller. Widerspricht dann aber dem Versuch Arbeitsabläufe zu automatisieren.

**Comment by Tensuko** [comment]
Das ist ein Kommentar frei nach dem Motto: Ich habe keine Ahnung, also hau ich mal einen raus!

CP ist kein Programm, es ist eine Mod basierend auf der LUA Scriptsprache in einem Simulator, der eine etwas alte Engine hat, die in mehreren Punkten limitiert ist! Ein Punkt davon ist die CPU ich sag nur single core!

**Comment by pvaiko** [comment]
@Alaxsxag danke für den Hinweis. Du scheinst dich sehr gut mit Speicher und Resourcemanagement und Performanceoptimierung in Lua auszukennen, glücklicherweise Courseplay ist ein Community Projekt mit offenen Quellen, jeder, auch du, kann mit einem Pull Request dazu beitragen.

Wir sind auch offen für Ideen wie man die Einschränkungen der Giants Game Engine umgehen kann, File Access ist nämlich nur durch die von Giants bereitgestellte XML Funktionen möglich.

Übrigens, hätte ich keinen Job und Familie, hätte ich schon längst die Feldwegkurse überarbeitet indem wir die Wegpunkte zwischen reihen start und ende dynamisch generieren und nicht speichern. Kannst auch gerne machen, siehe oben.

**Comment by Alaxsxag** [comment]
Ich weiss sehr wohl dass ihr das in euerer Freizeit macht und es dementsprechend auch Einschränkungen gibt. Ich schätze die Arbeit aller Beteiligten sehr.
CP ist für den Feldscan und auch einige Arbeiten recht toll und funktional obendrein.
Etwas sauer aufgestossen ist mir nur die Aussage "das war schon immer so und wird auch so bleiben."
Solche Sprüche habe ich schon oft gehört und sind für mich ein Zeichen von Ignoranz und Abgehobenheit.

Nichts desto trotz - müsste es doch beim Speichern und Laden der Kurse eine andere Lösung geben. Ich komme mir vor als würde ich an einem Rechner mit Diskettenlaufwerk aus den 1970ern sitzen.

Bevor ich CP benuztz habe, habe ich auch mal mit AD versucht Feldkurse einzufahren. Und da kannst hunderte von Kursen über hunderte von Kilometern anlegen - ganz ohne Probleme. Aber halt nicht mit den Funktionen von CP.
Es kann auch durchaus möglich sein, dass die meisten anderen Nutzer diese Probleme erst gar nicht haben. Denn auf Standard und x4 Karten funktioniert das alles prächtig. Vor allem weil die Felder schon mal nicht so gross sind wie auf der Wild West (16x).
Ich nutze den LS19 und mods wie AD und CP nun mal exzessiv und reize das Game mit allen Möglichkeiten voll aus.
Und gerade wegen CP und AD traue ich mich auch an eine 16x Map ran und spiele die komplett alleine mit allen Feldern. Ohne dies Tools AD und CP ist diese Map solo gar nicht zu bewältigen.

Wenn das natürlich an der Engine liegt oder der begrenzten Möglichkeiten des scriptens, hätte man das einfach nur kommunizieren müssen. Also werde ich mal bei Giants nachhaken und dort meinen "Frust" kundtun.

Danke für eure Antworten und damit ist das Thema für mich erst mal erledigt.

**Comment by pvaiko** [comment]
Geb dir recht, 'war schon immer so' ist natürlich kein Argument. AD macht es anders, die schreiben alle Wegpunkte in ein (eigentlich 3 o. 4, egal) XML Strings, bei uns ist es ein Wegpunkt ein XML Element. Das hat historische Gründe, erstens gab es damals keine 16x Maps, zweitens hatte CP kein eingebauter Kurseditor nur einige externe Projekte für Kurseditieren die von diesem XML format abhänging waren. 

Ob das immer noch der Fall ist weiss ich nicht, wenn's genug nachfragen gibt, werden wir bestimmt ändern.

**Comment by Tensuko** [comment]
> Etwas sauer aufgestossen ist mir nur die Aussage "das war schon immer so und wird auch so bleiben."
> Solche Sprüche habe ich schon oft gehört und sind für mich ein Zeichen von Ignoranz und Abgehobenheit.

Das hat weder was mit Ignoranz noch mit Abgehobenheit zu tun...
Schlichtweg mit dem Punkt, dass es jemand machen muss.

Wir haben ein System das Funktioniert und diverse andere Baustellen an denen wir eher arbeiten müssen/wollen.

Das System ist eben schon älter und demnach ist an der Aussage 'das war schon immer so' (bis auf die Tatsache, dass x4 und x16 Maps größere Kurse und damit längere Ladezeiten verursacht) halt korrekt. Weil es nie geändert wurde (Gab bis auf längere Ladezeiten durch größere Maps eben auch kein Grund dafür).

Wird sich auch nicht änder bezieht sich eben darauf, wer soll das machen ?
Bzw was sollen wir noch alles machen. Die Zeit ist nun mal begrenzt und wann der nächste LS kommt, wie der aussieht, wie unsere Pläne für den nächsten LS aussehen, steht in den Sternen. Warum bis dahin ein System anfassen, was funktioniert (wenn auch nicht optimal).


> Na wenn das normal ist und das auch so hingenommen wird, habe ich aber erhebliche Zweifel an den Entwicklern.

Solch ein Satz, stößt uns übrigens sauer auf, gerade weil wir in unserer Freizeit arbeiten und für euch kostenlos etwas zur Verfügung stellen. Nur mal so zum nachdenken.


So, das wollte ich noch mal dazu los werden...

**Comment by Alaxsxag** [comment]
@Tensuko

Also ohne jemanden hier auf die Füsse treten zu wollen. Aber ich kann dieses Gerede von "Wir machen das in unserer Freizeit" oder "dafür ist es kostenlos" nicht mehr hören.
Ich mache auch viel in meiner Freizeit für andere (engagiere mich u.a. im sozialen Bereich) und mache das trotzdem so gut ich kann. Da habe ich schon persönlich den Ehrgeiz, dass alles so funktioniert wie es soll. Und rechne auch nicht auf was ich alles kostenlos bewerkstellige.
Aber das ist ein anderes Thema.
Davon ab, macht CP beim speichern und laden schon auf Standardkarten Probleme. Es liegt also nicht nur an der grösse der Kurse, sondern wohl auch an der Anzahl dieser. Und ich kann mir nicht vorstellen, dass andere Spieler das nicht auch bemerken.
Über die Funktionalität von CP gibts für mich ansonsten keine Diskussion. Funzt bestens - und manche Probleme die andere immer wieder mit CP in den Foren beschreiben habe ich gar nicht weil ich einfach deren Arbeitsschritte nicht habe.
Ich betreibe überwiegend Feldwirtschaft (mit allen Feldern einer Karte) und "nebenbei" Viehhaltung.
Das ganze Ballengedöns, sowohl Stroh als auch Heu betreibe ich gar nicht, weil es einfach unwirtschaftlich und damit unsinnig ist. Alles nur Schüttgut das in Silos gebunkert wird.
Für mich ist die Lösung halt momnetan, dass ich die CP-Kurse nur temporär anlege. Das ist immer noch schneller als die Kurse zuladen. Dann ist halt nichts mehr mit Drescher am Hof (Parkplatz) mit AD und CP zu füttern und ihn wegzuschicken und die Arbeit komplett autonom zu machen. Ist kein Weltuntergang, sondern einfach nur ein "Schönheitsfehler".
Bin zwar nicht der ausgebuffte Programmierer, habe aber in 15 Jahren IT (Technischer Service, Netzwerkplanung und Realisierung im drucktechnischen und grafischen Bereich) gelernt - geht nicht, gibts nicht.
Ich habe hier nur ein Symptom von CP beschrieben und wollte nur wissen, ob es von Seiten der Entwickler da eine Lösung geben könnte. Und gerade weil es ein Freizeitprojekt ist und andere Prioritäten vorstehen, dann ist das auch o.K.

Also locker bleiben und nicht verkrampfen ;-)
