### ISSUE TITLE
Mode 5: Viehtransport/Rückwärtsfahren

### ISSUE THREAD

**Issue by Schorlensteve** [Courseplay/courseplay#6777]
Hi, mir ist seit längerem ein Problem aufgefallen (kann leider nicht mehr sagen bei welcher Version es noch funktioniert hat):
Ich habe eine Strecke erstellt die der Traktor mit dem Viehanhänger abfährt, am Stall und beim Viehhändler muss er dann ein paar Meter rückwärts fahren, um die richtige Ladeposition zu erreichen bzw. wieder vom Gelände zu kommen. 
Wie bereits beschrieben ist das bereits seit längerem so, am Kurs habe ich nichts geändert, da er ursprünglich so einwandfrei funktioniert hat und an den Wartepunkten darauf gewartet hat das ich manuell Tiere geladen/entladen habe und ihn dann weitergeschickt habe.
Anbei zwei Bilder und die log Datei

![Farming Simulator 19 05 02 2021 17_34_52](https://user-images.githubusercontent.com/62563289/107062104-37ffb080-67d9-11eb-81da-96ac93ec8f8d.png)

![Farming Simulator 19 05 02 2021 17_35_16](https://user-images.githubusercontent.com/62563289/107062122-3d5cfb00-67d9-11eb-8a29-9b3232ab913d.png)

[log.txt](https://github.com/Courseplay/courseplay/files/5933962/log.txt)

**Comment by Tensuko** [comment]
Dafür musst du mal erklären, was genau das Problem ist.
Wenn du willst, dass er nach dem rückwärts fahren am Wartepunkt steht, dann hast du da was falsch gemacht, für mich ist der Wartepunkt auf der geraden Strecke.

**Comment by Schorlensteve** [comment]
Ach so klar, sieht man auf Bildern ja ned, sorry!
Der Helfer fährt den Kurs solange es vorwärts geht so wie er soll und bleibt beim Viehhändler auch am Wartepunkt stehen. Dann entlade ich und schicke ihn weiter; daraufhin sollte er erst noch ein stück vorfahren um gerade zu ziehen und dann rückwärtsstoßen. Und da liegt der Hund begraben: der Traktor lenkt immer leicht ein und ändert seine Lenkung dann nicht mehr, drum knickt dann der Zug immer ein und er bleibt wie auf dem unteren Bild hängen, weil er nicht mehr fahren kann.

**Comment by Schorlensteve** [comment]
https://user-images.githubusercontent.com/62563289/107065104-aeea7880-67dc-11eb-92be-547eacc51327.mp4

**Comment by Tensuko** [comment]
Welcher Trailer und Traktor ist das ?
Und kannst du mir den Kurs mal schicken ?
Zu finden unter: \My Games\FarmingSimulator2019\CoursePlay_Courses\MapDE

Sieht mir nach der Felsbrunnen Karte aus, Original oder Mod ?

**Comment by Schorlensteve** [comment]
Trailer und Traktor sind beide aus dem original Spiel, Map ist ebenfalls Original (Felsbrunn). Wie finde ich denn heraus welcher der richtige Kurs ist? In dem Ordner sind alle Kurse nur nach Nummern benannt.

**Comment by Schorlensteve** [comment]
Ah ich denke ich hab ihn, wie schicke ich den?

**Comment by Tensuko** [comment]
Einfach den Ordner 'MapsDE' als .zip packen und das kannst du hier einfach anhängen.

**Comment by Schorlensteve** [comment]
[MapDE.zip](https://github.com/Courseplay/courseplay/files/5936550/MapDE.zip)

**Comment by Schorlensteve** [comment]
Vielen Dank für die prompte Bearbeitung! 
Sehr schön das man sich auch mit solchen Kleinigkeiten immer an euch wenden kann und ihr versucht schnelle Lösungen dafür zu erarbeiten! Ihr macht wirklich eine super Arbeit!

**Comment by pvaiko** [comment]
vergiss nicht dass wir es selbst kaputtgemacht haben :)
