### ISSUE TITLE
Unloading beet harvesters causes speeding up when under the unloader of the beet harvester

### ISSUE THREAD

**Issue by McLovinnitre** [Courseplay/courseplay#6778]
On the new version, *.35, i have unloaders set up to unload the beet harvesters. But when the beet harvesters are standing still the unloader tractor lines up with the unload point of the beet harvester and then speeds up to the field speed and shoots away from the beet harvester. It will then brake, and drive back and the issue repeats itself. I am using the ROPA Tiger 6xl as the beet harvestor.

**Comment by Tensuko** [comment]
Logfile with debugchannel 4, 7, 12 and 14 active.

**Comment by Gibbanator** [comment]
do you have avoid fruit on?

**Comment by McLovinnitre** [comment]
yes i do have avoid fruit on. here is the logfile
https://gist.github.com/McLovinnitre/11a8eec39b3bea1d05afeca7e9f697f4
Now it did that while unloading on the headlands

**Comment by Gibbanator** [comment]
if your unload is over fruit than  the tractor will just pass by and do that in a loop. You either have to have the beet harvester on to avoid fruit or turn off the avoid fruit on the tractor. sometimes the Harvester wont pull out to avoid fruit depending on where  you are on the field. Just my experience.
