### ISSUE TITLE
CP schaltet nach getaner Arbeit nicht mehr ab

### ISSUE THREAD

**Issue by ArnoKister** [Courseplay/courseplay#6780]
Hallo, mir ist auf meinem Dedi Server ein kleiner Fehler aufgefallen. 
Es gibt ja die Möglichkeit den CP nach getaner Arbeit zu Entlassen. 
Diese Option finde ich super, leider Funktioniert sie bei mir auf dem Dedi Server nicht. Mein Plan war es ein Feld mit dem Pflug zu bearbeiten und sobald er damit fertig ist sollte CP nicht zum Start fahren und CP Entlassen. Anschließend sollte er auf dem AD zugewiesenen Parkplatz fahren. 
Das ging alles schon mal. Leider kann ich Einstellen was ich möchte er bleibt immer am Ende des Kurses, bis ich eingreife, stehen.
Allerdings muss ich sagen ich weiß nicht ob das auf dem Dedi oder im normalen MP funktioniert hat.

Folgendes wurde eingestellt.
-mit AD Parkplatz zugewiesen (sämtliche Geräte auch wenn die Anbauteile im MP keinen eigenen Parkplatz haben können)
-im AD die Option am Ende Parken aktiviert
-CP Eingestellt das AD verwendet wird und anschließend geparkt wird. entladen/auffüllen/P
-CP Feldkurs geladen
-CP auf Feldarbeit geschaltet.
-Mit AD zum Feld fahren lassen
-Bei Ankunft CP am ersten Wegpunkt starten
bis hier hin alles super. Fahrzeug fährt zum Feld und aktiviert CP. CP bearbeitet das Feld. Das funktioniert alles Prima.
Beim beenden der Arbeit allerdings Läuft der Motor weiter und CP wird nicht entlassen. Somit kann er nicht zu AD wechseln und ihn auf seinen Parkplatz führen.

Vielleicht könnt ihr mir ja ohne LOG und Savegame schon weiter helfen. 
Die Mods die ich im Game habe waren auch drin womit es schon Funktioniert hat. 
Es sind nur Mods im Ordner die ich auch verwende. Eine Karte (Untergriesbach) und etliche Mods.

Eben nochmal getestet. Im SP geht alles reibungslos. Gleiche Mods, selbe Einstellungen. CP wird entlassen und alles ist gut. 

CP Version ist v6.03.00035
AD Version ist 1.1.0.7

Ich war der Meinung das es mit Version v6.03.00026 noch Funktionierte.

Ich bedanke mich bei den Modern mit dem größten Respekt für diese gute Arbeit, ohne Mods wäre das Game nicht das was es ist. 
Ihr macht echt super Arbeit. Dankeschön.

Mit freundlichen Grüßen
Wasserbüffel

**Comment by Tensuko** [comment]
Eine einfache Suche hätte dir viel Arbeit erspart..duplicate #6763
