### ISSUE TITLE
Offset cleared when starting a CP driver

### ISSUE THREAD

**Issue by knoxville73** [Courseplay/courseplay#6781]
Hi,
If I set an offset (left or rigth) for a special tools, it's only possible to make this after the begin of the course.
If you set this before the course, this setting is reset to 0.
![Offset](https://user-images.githubusercontent.com/23388102/107114935-b73cc500-6869-11eb-94dd-95ecc0aa267f.jpg)

**Comment by Tensuko** [comment]
Becouse of the tool.

**Comment by knoxville73** [comment]
This was perfectly running with the same tools and a previous version of CP

**Comment by Tensuko** [comment]
What previous Version ?

**Comment by knoxville73** [comment]
Sorry, I don't remember the version (because I install always the last version before beginning) but I'm sure december 2020 this worked perfectly

**Comment by pvaiko** [comment]
I think a manual offset should not be reset when starting the vehicle.
