### ISSUE TITLE
Neue Einstellung umsetzbar?

### ISSUE THREAD

**Issue by 60erjonny** [Courseplay/courseplay#6783]
Hallo

Es gibt ja die Einstellung "Am Startpunkt enden".
Hier gibt es ja: "Aktiviert" , "Deaktiviert" , "aktiviert und entlasse CP Fahrer", "deaktiviert und entlasse CP Fahrer"
Könnte man hier noch einbauen, das der gerade geladene Kurs auch mit geschlossen wird.
Aber nicht generell, sondern als mögliche Einstellung bei einem Fahrzeug.
Somit wäre bei den möglichen vielen Fahrzeugen die große Menge an geladenen Kursen, dann nicht mehr das Problem beim Spielneustart.

**Comment by Tensuko** [comment]
So viel trauen wir unseren Usern zu, dass sie in der Lage sind ein X m HUD zu drücken. Also nein.

**Comment by 60erjonny** [comment]
Hallo @Tensuko 

Ja schon, aber wenn man vieleicht 30 Fahrzeuge hat, ich das schon etwas heftig oder...?

Vieleicht hätte so mancher ( denen du es ja auch zutraust ) auch diese Einstellung sich gewünscht oder brauchen können...aber OK
Vieleicht hätte es CP noch auch besser machen können...aber OK


Aber aber ich weiß, das es vermessen war hier was von euch zu verlangen oder zu wünschen...also sorry...!

P.S.: Ihr macht hier einen tollen Jop und ich brauch dafür nicht`s zu bezahlen trotzdem vielen Dank ...!

**Comment by Tensuko** [comment]
Wir können CP einfach nicht mehr endlos Optionen zuballern, es ist eigentlich jetzt schon zu viel und da muss man eben mal abstriche machen.
Vorschläge und Ideen sind gern gesehen, aber bitte um Verständnis, das wir nicht jede kleinigkeit umsetzen werden.
