### ISSUE TITLE
Can't unload with Truck with tipper.

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#6784]
Hello I’m using a tipper mod and I’m getting an error in the log I noticed that the tipper is not reversing back to the unload point but unloading about 50 feet in front of it not sure if this is related to the error. Error is at the bottom of the log 

https://pastebin.com/raw/m7vpyteT

**Comment by Tensuko** [comment]
What tipper ?
We need more information then just an Error in the log.
https://github.com/Courseplay/courseplay/wiki

**Comment by matty2123** [comment]
Sorry it’s this one FS 19: MERCEDES AROCS v 1.0.0.0 Mercedes Benz Mod für Farming Simulator 19

https://www.modhoster.com/mods/mercedes-arocs

**Comment by Tensuko** [comment]
That should be the same as #6502
All Trucks with Platforms seems to have this problem.
Will try it out anyway when I have time for this.

**Comment by Tensuko** [comment]
Can't reproduce with a similar Truck from ModHub.
So it is a Mod Issue where we can't do anything.
![fsScreen_2021_02_08_06_57_55](https://user-images.githubusercontent.com/27344744/107181462-30a7f500-69db-11eb-9355-6d694d91bbcc.png)
![fsScreen_2021_02_08_06_58_49](https://user-images.githubusercontent.com/27344744/107181470-3271b880-69db-11eb-992b-bdef25a2b164.png)
