### ISSUE TITLE
Courseplay tab not working 

### ISSUE THREAD

**Issue by SpaceScooter1209** [Courseplay/courseplay#6786]
When I open my Courseplay to make my worker work the buttons on the tab do nothing when you click on them

**Comment by Tensuko** [comment]
logfile ? (why I still have to ask for this every time ?)
https://github.com/Courseplay/courseplay/wiki

**Comment by SpaceScooter1209** [comment]
What's a logfile

**Comment by SpaceScooter1209** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5938944/log.txt)

**Comment by Tensuko** [comment]
Ok and now to your Problem:
What is actual the problem ? What do you expect to happen and what does not work ?

**Comment by SpaceScooter1209** [comment]
So when I bring up the Courseplay tab I go to click on the button to make my worker start working but when I click it, it doesn't register that I clicked it.   

I expect that it should register that I clicked it.

**Comment by Tensuko** [comment]
.......
What button, what do you click, what do you want to start.... screenshots ?

**Comment by pvaiko** [comment]
Not sure what you are doing but your log does not show the Courseplay startup message. 

We can only help you if you are using a Courseplay version downloaded from here (https://github.com/Courseplay/courseplay/releases)
