### ISSUE TITLE
Can’t merge autodrive and cp

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#6790]
Hello I’m trying to merge courseplay with autodrive to refill the seeder but I’m using a premade autodrive course and if I try and merge the courseplay with the autodrive in manage course it won’t select it ie I have f22 and return but no merge will happen any help appreciated

**Comment by Tensuko** [comment]
What do you mean by merge ? Load AD course with CP ?

**Comment by matty2123** [comment]
This is the first time I’ve tried it but I watched a video and I’m sure he merged the two courses so when the seeder had run out it went to the autodrive start and went to the refill bit via autodrive and back to cp for fieldwork do I need to merge tbe auto with courseplay if so that’s where I run in to the problems

**Comment by matty2123** [comment]
https://youtu.be/3pZUDxecNLI Video I watched

**Comment by Tensuko** [comment]
That Video is to old.
You start CP with for seeding as usual and on the page where you star the cp driver you got AutoDrive option that you can activate for refill, then you have to set up AutoDrive options where to refill and stuff.

So CP side is:
Load Fieldcourse, start driver, activate ad use.

**Comment by matty2123** [comment]
Many thanks will try tomorrow
