### ISSUE TITLE
Mode 1 with multiple trailer compartments - Suggestion

### ISSUE THREAD

**Issue by ninjayx02** [Courseplay/courseplay#6792]
Hi.
Using the mode 1 with the wilson multi compartment trailers, or multiple trailers, all good for unload, but either the front or rear compartment fills. Is it possible to have a timer on a wait point, so when generating the course, start course recording at the front compartment of the trailer, move forward to the second compartment, add a wait point with an adjustable timer, so when the timer expires the truck drives on? I tried adjusting the speed to 1 kmh, but still not long enough to fill the rear compartment.
By the way, CP is one of the best mods available

**Comment by Tensuko** [comment]
Won't add something spezial like that, it would be just a workarround.
Does this happen in loading at a trigger or manual loading ?

**Comment by envikowaty** [comment]
All works fine for the silos, I've notice that this problem pop ups when we use auger wagon

**Comment by ninjayx02** [comment]
It's more for field work, when using multiple compartments/trailers with mother bins

**Comment by Tensuko** [comment]
Fieldwork with Trailers ?!
If you talk about unloading Combine, thats not supported.

For fill them up with Auger Wagons, it should drive up when the 1st part is filled, that would be if the Trailer is used in Mode1 with manual fill (no filltype selected).

**Comment by Tensuko** [comment]
In any case you want this to work... This is how... Else I need more Informations what you try to do.
https://www.youtube.com/watch?v=YhB5EXQfqIE

**Comment by ninjayx02** [comment]
Just tried this with the motherbin and the latest edition of CP. Works brilliantly.  Thanks


![Farming Simulator 19 Screenshot 2021 02 12 - 15 03 39 20](https://user-images.githubusercontent.com/49168998/107786460-d9d94d00-6d45-11eb-9408-978c22f26a2b.png)
![Farming Simulator 19 Screenshot 2021 02 12 - 15 03 14 95](https://user-images.githubusercontent.com/49168998/107786469-dcd43d80-6d45-11eb-80e9-d6ca1eada205.png)

**Comment by Tensuko** [comment]
As it seems there are some ways to do this, I would like to close this Issue.
Multi Unites is getting handeld in Mode1 so it should work just fine, see Video and Pics from ninjayx02
