### ISSUE TITLE
[MODE2] Distance limit

### ISSUE THREAD

**Issue by MartinGrisotto** [Courseplay/courseplay#6793]
Is there a distance limit for pathfinder to find a combine? It seems like the CP can't see beyond certain distance....

![image](https://user-images.githubusercontent.com/10392883/107223031-f90a6e80-6a15-11eb-953c-6c0243d3a566.png)

![image](https://user-images.githubusercontent.com/10392883/107223066-07f12100-6a16-11eb-84c3-6ba3e75ee5c3.png)

LOG:
https://pastebin.pl/view/94c9377d

EDIT:

If i drive the unloader little by little into the field, it will eventually find the combine, suggesting a threshold beyond wich the path cannot be generated.

**Comment by 60erjonny** [comment]
Hallo

If you put the start and end point a little further into the field, what changes in the thresher recognition ...?

**Comment by MartinGrisotto** [comment]
> Hallo
> 
> If you put the start and end point a little further into the field, what changes in the thresher recognition ...?

Nothing. I still have to drive to ca 25% of field lenght to make the pathfinder plot a course to combine. Then, the course is plotted outside of the field - despite not fruit between unloader and harvester

![image](https://user-images.githubusercontent.com/10392883/107237152-b604c700-6a26-11eb-8511-59cd845d0ee8.png)

**Comment by Tensuko** [comment]
Can't open your logfile and no there is no distance limit.

**Comment by MartinGrisotto** [comment]
> Can't open your logfile and no there is no distance limit.

Corrected the link, should be OK

**Comment by pvaiko** [comment]
On which field was the combine when you created the logs? Because on the screenshot it seems to be on field 60, but in the logs it reports 59.

**Comment by MartinGrisotto** [comment]
> On which field was the combine when you created the logs? Because on the screenshot it seems to be on field 60, but in the logs it reports 59.

On 59. The latter screenchot was done later on.

**Comment by pvaiko** [comment]
What map is this? How big is this field?

**Comment by MartinGrisotto** [comment]
No Man's Land, 28.26 HA

I'm doing another harvest and some time after the harvester enters field 59, unloader has to be moved more into the field to connect with harvester. 

![image](https://user-images.githubusercontent.com/10392883/107285379-5971ce00-6a5f-11eb-891b-2ec845b779c2.png)

**Comment by pvaiko** [comment]
So that's a custom field you created from 56-60?

**Comment by MartinGrisotto** [comment]
> So that's a custom field you created from 56-60?

Yes. They are scanned for field borders and stored under proper field number just in case, but that doesn't change anything anyway. As soon the unloader detects the harvester, it is working fine, just when it comes back to silo and back to field, i have to manually drive into the field to be close enough for pathfinder to calculate path. 

I doesn't work even though harvester is detected properly, as shown below. It keeps blinking "no harvester in range" for split of a second and course is not calculated.

![image](https://user-images.githubusercontent.com/10392883/107331336-0aee1f00-6ab3-11eb-81ab-308cd42ac3be.png)

**Comment by MartinGrisotto** [comment]
I created another course that ends in field 58 (ends closer to the harvester) and CP was able to finish off the field no problem.

**Comment by pvaiko** [comment]
Should work fine with 45
