### ISSUE TITLE
Mode 4: Rückwärtsfahrt bei Wenden auf dem Feld

### ISSUE THREAD

**Issue by Schorlensteve** [Courseplay/courseplay#6794]
Hi, habe seit kurzem ein Problem, dass mir hauptsächlich beim Güllefahren auffällt:
Wenn "wenden auf dem Feld" aktiviert ist und der Helfer das Ende einer Reihe erreicht, versucht er Rückwärts zu fahren und ein paar Meter in die Bahn zurückzustoßen. Dabei stellt er jedoch automatisch eine Höchstgeschwindigkeit von 1 km/h ein und kommt entsprechend nicht voran. Von mir eingestellt ist bei Rückwärtsfahrt 8 km/h, das wird ignoriert. 

Zur verwendeten Kombi: Fendt 800, Zunhammer SKE 18.500 und Zunhammer Verteiler 15m aus dem Holmer Addon, alles aus dem Modhub von Giants.

![Farming Simulator 19 08 02 2021 15_21_04](https://user-images.githubusercontent.com/62563289/107234668-30801780-6a24-11eb-8aa7-bb9c06673c2a.png)

[log.txt](https://github.com/Courseplay/courseplay/files/5944358/log.txt)

**Comment by Schorlensteve** [comment]
https://user-images.githubusercontent.com/62563289/107235052-94a2db80-6a24-11eb-9745-c0152f165c22.mp4

**Comment by Schorlensteve** [comment]
Außerdem verwende ich "added realism for vehicles", ebenfalls aus dem Modhub

**Comment by Tensuko** [comment]
kann ich nicht reproduzieren
Hab beide 15m Geräte probiert, klappt wie es soll.
logfile mit channel 12 und 14 mal anhängen.
https://github.com/Courseplay/courseplay/wiki

![fsScreen_2021_02_08_18_58_29](https://user-images.githubusercontent.com/27344744/107261872-2835d580-6a40-11eb-91d0-a7d42ea5b8a4.png)

![fsScreen_2021_02_08_19_00_58](https://user-images.githubusercontent.com/27344744/107261861-25d37b80-6a40-11eb-93f9-ecf6983c920f.png)

**Comment by Schorlensteve** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5966392/log.txt)

**Comment by Schorlensteve** [comment]
Habe immer erst einmal ein Vorgewende rundherum und dann die Feldreiehen. Passiert sowohl an den Ecken, als auch auf dem Feld beim wenden

**Comment by Schorlensteve** [comment]
Das von mir verwendete Fass ist das SKE aus dem Modhub, nicht aus dem original (wegen Manure System)

**Comment by Tensuko** [comment]
Auch damit (aber Gestänge ist Vanilla) kein Problem.
Anderen Traktor mal versucht ?
![fsScreen_2021_02_12_08_27_23](https://user-images.githubusercontent.com/27344744/107740774-30299a00-6d0c-11eb-907c-61326a42618e.png)

**Comment by Schorlensteve** [comment]
Habe es mit einem anderen Zugfahrzeug in einem neuen Spielstand versucht, da ging es. Im alten SPielstand funktioniert es auch mit anderen Traktoren (Originale) nicht...
Ich werde jetzt mal noch nach und nach alle Mods zu bzw. wegschalten und versuchen ob es dann klappt...

**Comment by Tensuko** [comment]
Dann hast du da irgend ein Modconflict oder eine Mod die Probleme macht.

Daher kein CP Issue.

**Comment by Schorlensteve** [comment]
Habe den Fehler gefunden. Auf der Seite war noch ein Gülleschlauch festgemacht, sobald der weg war ging alles problemlos....

**Comment by Tensuko** [comment]
Alles klar.
