### ISSUE TITLE
Mode 3 Offloader rams combine

### ISSUE THREAD

**Issue by Siginek** [Courseplay/courseplay#6796]
Hi, I have been encountering problem with overloader in CP for quite some time now - sometimes it happens, that overloader comes to combine from behind and instead of recalculating path to pipe when its close, it just rams combine form behind and pushes it forward (had to stop him manually, it wasnt just push and wait, but continuous push of combine).
AS this seemingly happens randomly, I was not able to reproduce it, but i managed to reset log once few seconds before it happened, turn on debug 12 and 14 and get screenshot - hopefully it will help.

All vehicles are from various mods - Combine is lexion 780, tractor is Fendt vario 930 gen6 and auger is Horsch Titan UW 34

Map is Eielshort

![image](https://user-images.githubusercontent.com/77811548/107293893-b45df200-6a6c-11eb-9214-371cf5a5d19c.png)

https://gist.github.com/Siginek/ad205e3c0395936086976c61b898e3ff

**Comment by pvaiko** [comment]
Not sure what's going on there, but it is really strange. I see some of these errors:

2021-02-09 00:13 Error: Running LUA method 'mouseEvent'.                                                                                                                                                2021-02-09 00:13 dataS/scripts/vehicles/Vehicle.lua(2920) : attempt to index a nil value    

Also, debug channel 4 (mode 2/3) is not activated so it is difficult to tell what was going on.

**Comment by Tensuko** [comment]
No complete logfile, but I am sure that is a Mod issue from the 780 wich doesn't report correct pipe position.

**Comment by Siginek** [comment]
it was probably problem of 780. I removed that mod for some other reasons, and it didnt happen to me anymore with lexion 8900 from claas dlc
