### ISSUE TITLE
Unable to regenerate course after rejoining MP session

### ISSUE THREAD

**Issue by rotornut44** [Courseplay/courseplay#6797]
I play online with a friend, who is the host of the session. If I accept a contract, generate and tell Courseplay to drive the course, it will do so, no problem. However, if I leave the session and come back in, or we shut it down and continue playing the next day without Courseplay finishing the field, I am unable to select that field to regenerate and continue the course. This issue is not present for the server host, just anyone else who joins.

If I accept a new contract, I can generate a course. The issue only occurs on contracts that were already present before rejoining.

Any ideas? Thanks!

**Comment by Tensuko** [comment]
#6530 duplicate
