### ISSUE TITLE
Mode 3 FSM_Ropa_BigBear

### ISSUE THREAD

**Issue by Fawkes10** [Courseplay/courseplay#6799]
Hallo. Als erstes möchte ich mich bei Euch für diesen tollen Mod bedanken. LS ohne Coureplay hat für mich keinen Sinn oder ich habe mich die letzen Jahre zu sehr an diesen Mod gewöhnt.

Mein Problem: Ich versuche gerade ein Kartoffelfeld abzuernten und habe jetzt den Erdfrucht Überladewagen vom FSM Team gefunden. Leider funktioniert dieser nur bedingt bei mir.

Ich benutze die neuerste Version Eures Mods Courseplay for FS19 v6.03.00038
Roder fährt mit CP
Abfahrer fährt mit CP.

Der Abfahrer läd die Kartoffel in den LKW klappt aber dann die Überladerampe wieder ein.  Mit eingeklappter Rampe lässt sich aber der Überlader nicht beladen.
Meine Frage mache Ich etwas falsch oder ist der BigBear einfach nicht mit CP kompatibel?
Da dies mein erster Eintrag hier ist bitte ich euch mit bescheid zugeben falls Ihr meine Log oder irgendeine Debug datei benötigt.

Vielen Dank schon mal

**Comment by Tensuko** [comment]
Hast du mal einen Link zu der Mod ? Sagt mir gerade gar nichts, muss mal gucken was das ist.

**Comment by Fawkes10** [comment]
Ja natürlich.
Habe ich vergessen
https://forbidden-mods.de/filebase/file/9021-ropa-big-bear/

**Comment by Tensuko** [comment]
Ok muss ich mir anschauen, kann aber etwas dauern (am Wochenende vlt wenn ich Zeit habe)

**Comment by andreasthu** [comment]
Hallo
Ich hatte früher auch schon mal mit diesem ÜLW gespielt.
Meines Wissens nach verschiebt dieser beim einklappen des Überladebandes den cube des filltriggers, so das er für den kartoffelernter nicht mehr zu erreichen ist.
Ich habe mir damit geholfen, beim bigbear diese animation des filltriggers in der xml auszukommentieren.
Das funktionierte dann, der bigbear konnte somit auch bei eingeklapptem überladeband befüllt werden.
Lg
Andreas

**Comment by Tensuko** [comment]
@andreasthu 
Oh, ich danke dir Andreas, damit hast du mir gerade viel Arbeit erspart :)


Dann machen wir das hier zu als Mod Issue, weil da können wir wirklich nichts dran ändern, sry!
