### ISSUE TITLE
Mode 5

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/courseplay#6802]
Hello,

Since the last Courseplay versions, we can no longer use mode 5 to do loop courses. In my case, I used this mode to go back and forth in the bunker and tamp the silage. (photo 1) Now the vehicle makes a round trip and stops. (photo 2)
I know that we can now use mode 10 to tamp the silo, but some vehicles struggle to get on the pile and in addition, by dint of going up and down, they bring out the silage from the bunker. (photo 3) In addition, if I fill another silo, not far from this location (it is my case, but we do not see it in the photos) All the vehicles that will pass by this bunker will be stopped.
Is it not possible to go back for the mode 5?
Thank you
![image](https://user-images.githubusercontent.com/36656729/107483604-9afa9a00-6b81-11eb-93ea-e2914479c694.png)
![image](https://user-images.githubusercontent.com/36656729/107483658-ac43a680-6b81-11eb-97b1-e558197fe1ed.png)
![image](https://user-images.githubusercontent.com/36656729/107483696-b665a500-6b81-11eb-8024-80f471e42694.png)

**Comment by Tensuko** [comment]
You can always use compacting in mode 10 it should work with all vehicles, so no. wont add it back.

**Comment by Crinouche** [comment]
it has the merit of being clear, and in addition, without diplomacy :(

**Comment by Tensuko** [comment]
Don't understand.
Why is so bad about just use Mode10 ?
Record Course, start driver in compacting mode, done.

**Comment by Crinouche** [comment]
> Je ne comprends pas.
> Pourquoi est-ce si mauvais d'utiliser simplement Mode10?
> Enregistrez le cours, démarrez le pilote en mode compactage, c'est fait.

So you didn't read until the end (and / or) didn't understand my request ...

**Comment by Tensuko** [comment]
Answer is the same, won't add it back for now.

**Comment by Tensuko** [comment]
And for the drivers that pass by, reduce the distance.
It won't take long to compact a silo as well.

**Comment by Crinouche** [comment]
Hello,

Here is the whole point of having restored this functionality:
-Several tractors can tamp with a tool intended for this. This is faster than with mode 10.
-This does not lower the silage at the end of the silo. (photo2)

Thank you.

![image](https://user-images.githubusercontent.com/36656729/108589445-98a4f680-735e-11eb-8d22-e2be093f8ae5.png)
![image](https://user-images.githubusercontent.com/36656729/108589472-b07c7a80-735e-11eb-9e4c-c4322fab08c5.png)

**Comment by TinyCrocodile** [comment]
It is already added back. Just update cp.

**Comment by Tensuko** [comment]
@Crinouche 
you can tell me as much as you want.
There was a reason for this removed setting.
We brought it back becouse someone gave a good reason where it is useful, so we took our time to change the whole function.
It is back now, so be happy now :)
