### ISSUE TITLE
Unloading backwards into the silo

### ISSUE THREAD

**Issue by LEGAMINGDE** [Courseplay/courseplay#6807]
when CP is unloading backwards into a silo for making silage and he cant empty the full trailer on one spot he keeps staying there basiccaly forever instead of starting slowly moving forward and sometimes he just stops infront of the silo and does nothing

![Screenshot 2021-02-10 180822](https://user-images.githubusercontent.com/23504996/107545955-26991880-6bcc-11eb-8adb-58442d8e8a8a.png)
![Screenshot 2021-02-10 180627](https://user-images.githubusercontent.com/23504996/107545976-2a2c9f80-6bcc-11eb-9ab7-0f1e5ac45ae5.png)

tested with:
-Pöttinger Boss Alpin 251
-Pöttinger Euroboss 330 D-T

**Comment by Tensuko** [comment]
GitHub got a search function:
#6748 duplicate
Updates for this should come soon.
