### ISSUE TITLE
Option for drive in circle for mode5 (drive settings?)

### ISSUE THREAD

**Issue by Yboux** [Courseplay/courseplay#6808]
In FS 17 when driving a course created using "drive from start to finish" we had the option "stop at last point or at next trigger". Cannot find the same option with courseplay in FS 19? Is it possible to have it again?
Thanks

**Comment by Yboux** [comment]
![Couseplay option](https://user-images.githubusercontent.com/25300651/107567613-e62da080-6bb3-11eb-9e05-d4d8ecba6f4d.jpg)

**Comment by Tensuko** [comment]
No

**Comment by Tensuko** [comment]
You can tell me a very good reason what you would need this for.

**Comment by Yboux** [comment]
It is to run a sweeper to clean pigs or cows

**Comment by Tensuko** [comment]
Gratulation. First reasonable action where I would say okay we dont have another option to do this task :) 
Pls give me some time to think how to integrate that option in another way then it was. As I removed it from HUD for a specific reason.

**Comment by Yboux** [comment]
Thank you very much...

**Comment by Crinouche** [comment]
It's crazy!
I asked the same yesterday to be able to pack bunkers # 6802 and the answer was a big: NO ...

**Comment by Tensuko** [comment]
It wasn't the same! You ask for a workarround for Mode10!

**Comment by Yboux** [comment]
Thank you :)
