### ISSUE TITLE
Mode 3 Save pipe position

### ISSUE THREAD

**Issue by dragon1220** [Courseplay/courseplay#6810]
Hi Guys
Using the latest version (.38), just wondering was the option to save pipe position removed from the specific tool page for mode three overloaders? If it has been, has it been by mistake?

![fsScreen_2021_02_11_00_53_13](https://user-images.githubusercontent.com/75646825/107592260-73004a80-6c04-11eb-8ee7-ea5129a8c636.png)

Thanks guys
G

**Comment by Tensuko** [comment]
Is not removed.
Try to make a modechange. Maybe is another problem with this hud.

**Comment by dragon1220** [comment]
sorry for the late reply, had to work today.

So if I change into mode 5 and then back into mode 3, the save pipe position option reappears...

Thanks

**Comment by Tensuko** [comment]
Okay so this is HUD Issue.
