### ISSUE TITLE
Lindner Unitrack 

### ISSUE THREAD

**Issue by LEGAMINGDE** [Courseplay/courseplay#6811]

**Comment by LEGAMINGDE** [comment]
the linder unitrac 122 LDrive with the Swiss - Elite S31 is driving trugh silos but doesent unload

**Comment by Tensuko** [comment]
More Info....
https://github.com/Courseplay/courseplay/wiki
Mode ? Mod or DLC ? and so on...

**Comment by LEGAMINGDE** [comment]
![image](https://user-images.githubusercontent.com/23504996/107617172-ae743680-6c4f-11eb-883d-98ec85eb3f40.png)
![image](https://user-images.githubusercontent.com/23504996/107617186-baf88f00-6c4f-11eb-8794-7ee29be3240a.png)
![image](https://user-images.githubusercontent.com/23504996/107617195-bf24ac80-6c4f-11eb-8b08-e1d9db66f160.png)
https://youtu.be/VAwb_VLAhKM

**Comment by Tensuko** [comment]
It isn't the Lindner ( I guess ).
Your course is wrong.
You need an unload here waypoint to do proper unloading in a silo bunker.
I know it is somehow working at some point (due to a trigger callback I guess), but to have correct unloading in silo bunker, you need the unload here waypoint.
Lead the unload course only, open editor and and change the last waypoint and save it. Then load your course again and try it out.
If the Lindner then still doesn't unload, we have to take a look at the Tool whats wrong.

**Comment by LEGAMINGDE** [comment]
Hm, I'll test that, but normal loadingwagons dont need a unload here waypoint 🤔

**Comment by Tensuko** [comment]
For Bunker they do, if you want to have it working correct.
As I said, they can unload as they see the unload area of the Bunker, but it not always work correctly.
Thats why place unload here WP and it should work fine.

**Comment by LEGAMINGDE** [comment]
i placed an unload waypoint and its still not working :(

https://youtu.be/4KBRhUn1Hpg

**Comment by Tensuko** [comment]
oh, okay....
Will have a look but I must see when I got time for this, maybe on weekend.

**Comment by andreasthu** [comment]
Hello
Is the dump point before or after the change direction point? the dump point should be before.
I always set the dump point in the middle from the silo (not at the end) drive back a little bit, 1-2m, set the change direction point and drive forward out of the silo. The leveler push the chaff to the end, so it works for me.
Lg
Andreas

**Comment by Tensuko** [comment]
Works:
![fsScreen_2021_02_12_09_55_27](https://user-images.githubusercontent.com/27344744/107747891-7dac0400-6d18-11eb-9141-b872e0c68a92.png)
Switch in Reverse, drive reverse into Bunker, set an Unload here Waypoint, switch back to forward and drive out of the bunker.
Works just fine.
