### ISSUE TITLE
Headlands mode for the entire field?

### ISSUE THREAD

**Issue by Kingdud** [Courseplay/courseplay#6815]
Using a combine I have an option to do 'headlands mode', which generates a path where the pipe is always facing to the outside of the field, so that a grain cart can always pull along side to overload. The problem is that I can't find a way to keep this driving path selected for the entire field. There's no reason why I should have to switch to lands/spiral/etc for the 'center' of the field. I don't really want that. Just keep doing the spiral for headlands all the way until there's only a single stripe left, then do it. In this way, I can always overload.

Right now, I end up recording that exact course by hand, but it'd be nice to have courseplay just automatically generate that route. Am I an idiot and this is already an option? Is there a technical reason this isn't offered? Did it just never occur to anyone? I'm curious, not malicious. I know how much of a PITA it is supporting user requests from my Factorio mods.

**Comment by Tensuko** [comment]
Did you try to use 2 Headlands and at the mid part 'Lands' ? It should do what you are looking for. Just in a bit different way.
We also have other Patterns like spiral, give give it a try.

**Comment by Kingdud** [comment]
Yes, I've used lands, spiral, and all the other patterns available. Lands ends up causing the harvester to stop harvesting at the western side of the field, drive allll the way to the eastern side, and then resume harvesting, once it finishes a 'land'. The field is quite large, so this ends up wasting around 1-2 minutes per run.

Spiral operates the same way as lands, except that it actually will keep the boom on the outside, except for the first cut in. Given how big my fields are, that ends up meaning the harvester has to stop, create a cut in, and wait for the overloader to pull along side before finishing the field. Even with spiral, you end up wasting a lot of time driving around not harvesting between spiral lands (same East/west driving problem that lands has).

These problems persist no matter which corner of the field I start on, and what direction I order it to use. I didn't imagine it would be that hard to just have whatever algorithm you use for the headlands pathing to just be allowed to run all the way until there was only a single width-strip of field left in the center. The headland course generates exactly what I want, I just want to do that for the *entirety* of the field, not switch to a different algo once the headlands are cleared.

**Comment by pvaiko** [comment]
@Kingdud this request came up multiple times and yes, we can do it, what folks tend to forget is that not all fields are rectangular, and the moment the field has a little irregular shape things can get very complex very soon. 

We'll probably add that as an option.

In the meantime, you may want to check out AI Vehicle Extension mod, I think that does exactly what you want.

**Comment by Kingdud** [comment]
I looked in to AI VE prior to selecting this mod. But you are right, there are a lot of nasty corner cases with fields that lack exactly 4 90 degree corners. I've done enough CNC machining to know that sometimes mastercam will spew out completely dumb tool paths that spend a lot of time not machining when there is a totally obvious way to do it more efficiently, so...I get the dilemma. There's not really a difference between a CNC toolpath and what you are doing here.

Personally I'd be totally ok with the option to just use the 'headland forever' method and have a note that 'selecting this toolpath will not work on fields that are oddly shaped.' (the path should work fine for squares, rectangles, and circles. It would probably break with something that had a an 'appendage' or U-shaped field. Or anytime the path between remaining fields went to nothing. Mastercam costs 10s of thousands of dollars for a reason. Those path-creation algorithms are a huge pain!

**Comment by rohne83** [comment]
@Kingdud I think we should rather hope for a fix of the spirals mode, so that the pipe always remains outside the crop, no matter where your starting point is. As Tensuko already said, AIVE does exactly what you wanted initially and in this specific case it does it even better than CP (of course you'd have to use AD for your unloaders or overloaders then). But as soon as your fields are shaped irregularly it can get very painful if you're just circling around forever. Latest then it's good to stop just circling and start working proper field rows - with spirals mode it's still the same direction, just cleaner.
In the end, as long as you're not trying to harvest the largest field on Wild West map with just a single Bizon, CP allows for more than enough numbers of headlands already now ;)
