### ISSUE TITLE
Courseplay can't find combine

### ISSUE THREAD

**Issue by krzysiek94725** [Courseplay/courseplay#6816]
Courseplay does not display to me any combine, although I bought. I have this problem in any version above 6.02. Without any mods, this happens too. When I'm looking for it on the field with the combine can not find. 
here I attach a photo: https://ibb.co/tz7dGSj

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki
https://github.com/Courseplay/courseplay/releases
