### ISSUE TITLE
Courseplay does not show any combine

### ISSUE THREAD

**Issue by krzysiek94725** [Courseplay/courseplay#6817]
I use the latest version. After generating a course, no combine is displayed in courseplay. I play only with autodrive and courseplay.
![Farming Simulator 19 Screenshot 2021 02 11 - 22 50 34 78](https://user-images.githubusercontent.com/78935096/107704149-16149b00-6cbd-11eb-91df-540e553d3a7e.png)

**Comment by Tensuko** [comment]
Is the Combine running with AutoDrive ?

**Comment by Tensuko** [comment]
Started Combine with CP, switched to Mode2 on the Tractor and directly saw the Combine.
![fsScreen_2021_02_12_11_06_58](https://user-images.githubusercontent.com/27344744/107754947-7be73e00-6d22-11eb-8a7e-af08b38790c6.png)

**Comment by Tensuko** [comment]
Logfile maybe ?
