### ISSUE TITLE
refill planter

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#6818]
I tried to create a path that would allow plants (or poplars) to be planted with the CP. The bug that kept the path going even if the seedlings were finished did not show up, the tractor stopped and went to the charging path correctly, but I was not able to understand how to position the pallets to make them enter the load trigger (manually makes me reload the car, but the CP doesn't). I hope I have made myself clear. I attach screen and log (the screens were taken during the execution of the path, to make it clear that the proximity is there but the CP does not load)

![Farming Simulator 19 11_02_2021 23_44_42 (1)](https://user-images.githubusercontent.com/59969508/107708667-267c4400-6cc4-11eb-87bd-c9cd8f958582.png)
![Farming Simulator 19 11_02_2021 23_45_24](https://user-images.githubusercontent.com/59969508/107708679-2c722500-6cc4-11eb-91b4-2b3c48c93d87.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5968847/log.txt)

**Comment by Tensuko** [comment]
Will have to take a closer look. But it won't be on priority.
What is if you place a waitpoint and refill it manually (with a frontloader or something)?

**Comment by 0Pietro20** [comment]
Sorry but I've been very busy. If I remember tonight I try to put a waiting point and approach the pallet manually, perhaps placing it on the tool the trigger takes it

**Comment by 0Pietro20** [comment]
I also tried a manual approach from all directions but nothing worked
