### ISSUE TITLE
Mode9 unload into Trailer only when Trailer reaches position (not moving anymore)

### ISSUE THREAD

**Issue by LEGAMINGDE** [Courseplay/courseplay#6820]
https://youtu.be/TOhGXfIcItg

**Comment by Tensuko** [comment]
Your Trailer doesn't even stop at the correct position... what did you expect to happen ?

**Comment by LEGAMINGDE** [comment]
he drives a vew meters more backwards and then forward again to park exactly @ the startingpoint
![image](https://user-images.githubusercontent.com/23504996/107781709-7dc3f800-6d48-11eb-9a5e-d98c1302b513.png)

**Comment by LEGAMINGDE** [comment]
the mode 9 also ramms the trailer while the trailer  parking but he stops when the shovel starts unloading into the trailer

**Comment by Tensuko** [comment]
> 
> 
> the mode 9 also ramms the trailer while the trailer parking but he stops when the shovel starts unloading into the trailer

-> #6447
