### ISSUE TITLE
Lindner Unitrack is not unloading into trigger

### ISSUE THREAD

**Issue by LEGAMINGDE** [Courseplay/courseplay#6822]
https://youtu.be/9S8b4D7T3kg

**Comment by 60erjonny** [comment]
Hallo

Is there no waiting point to be set on the trigger ...?

**Comment by LEGAMINGDE** [comment]
usually not

**Comment by Tensuko** [comment]
No Waitpoint, no unload ehre for trigger, will try it out tmr maybe...

**Comment by Tensuko** [comment]
It can unload... even reverse, maybe you should check your trigger if it can take the stuff you try to unload.
![fsScreen_2021_02_13_01_27_06](https://user-images.githubusercontent.com/27344744/107835684-a7a60a80-6d9a-11eb-9d9c-aaa61b5e01d6.png)

**Comment by LEGAMINGDE** [comment]
🤔 I tried to unload there manualy, that did work

**Comment by LEGAMINGDE** [comment]
hm idk why but now it works
