### ISSUE TITLE
Köckerling Vector 460/620 von Agrartechnik Nordeifel

### ISSUE THREAD

**Issue by 0scarZulu** [Courseplay/courseplay#6823]
Keine Wendungen mit CP möglich. Laut Rückmeldung AN kann das Problem nur von euch gefixt werden:

Das Problem ist dass courseplay den grubber nicht als gezogen erkennt weil der ja nen zugkraftverstärker hat, also der oberlenker angeschlossen ist. D.h. Es kann nicht mit courseplay funktionieren
Ist also eher nen courseplay fehler

Bitte fixt den Fehler :)

**Comment by Tensuko** [comment]
#5897 Mod Issue

**Comment by pvaiko** [comment]
@0scarZulu du kannst den auf jeden Fall konfigurieren damit CP nicht rückwärts fährt, siehe: https://github.com/Courseplay/courseplay/blob/3f64862808b7185b8ea8763ba3aeffbe8c4ae7a5/config/VehicleConfigurations.xml#L33

**Comment by pvaiko** [comment]
@0scarZulu weisst ob es mit dem Game Helper funktioniert?

**Comment by Tensuko** [comment]
Der normale Helfer macht nen turn außerhalb vom Feld.

**Comment by 0scarZulu** [comment]
Also der normale Helfer fährt ein sauberes O beim wenden. Auch mit Vorgewende.

**Comment by 0scarZulu** [comment]
> @0scarZulu du kannst den auf jeden Fall konfigurieren damit CP nicht rückwärts fährt, siehe:
> 
> https://github.com/Courseplay/courseplay/blob/3f64862808b7185b8ea8763ba3aeffbe8c4ae7a5/config/VehicleConfigurations.xml#L33

Okay danke. :) Und was muss ich da eintragen und wo kommt die XML hin?

**Comment by pvaiko** [comment]
Kannst noch ` implementWheelAlwaysOnGround="true"` hinfügen?

**Comment by frm274** [comment]
Funktioniert korrekt mit folgendem Eintrag:
(er darf ja Rückwärts, muss eben nur wie ein Trailer behandelt werden, obwohl er im Dreipunkt attached ist.)


`    
    <Vehicle name="vector460.xml"
             implementWheelAlwaysOnGround = "true"           
			 noReverse="false"
    />` 

` 
    <Vehicle name="vector620.xml"
             implementWheelAlwaysOnGround = "true"            
			 noReverse="false"
    />`

![turn](https://user-images.githubusercontent.com/24813263/107872026-78c98a80-6ea7-11eb-8665-2b6722db085b.jpg)

**Comment by rohne83** [comment]
> 
> 
> @0scarZulu du kannst den auf jeden Fall konfigurieren damit CP nicht rückwärts fährt, siehe:
> 
> https://github.com/Courseplay/courseplay/blob/3f64862808b7185b8ea8763ba3aeffbe8c4ae7a5/config/VehicleConfigurations.xml#L33

@pvaiko hat sowas nur Effekt auf Feldreihenwende oder funtioniert das auch für zB den Pathfinder von Abfahrern? Ich hab zur Zeit das Problem, dass LKWs mit Wechselbrücke beim Ernte abfahren extrem viele Rückwärtsfahrten auf dem Feld machen, egal ob noch ein Anhänger dran hängt oder nicht. Während normale Traktoren und LKWs da schon jetzt versuchen möglichst ohne Rückwärtsfahrten auszukommen. Wenn das Setting da auch wirkt, wäre das klasse.

**Comment by pvaiko** [comment]
@frm274 noReverse = false brauchst du dann nicht, wir werden dann die zwei Tools standardmaessig so konfigurieren.

**Comment by pvaiko** [comment]
@rohne83 nein, das ermittelt CP automatisch, unter anderem beinflusst `implementWheelAlwaysOnGround ` es auch.

**Comment by rohne83** [comment]
@pvaiko heißt das, ich muss den anderen Parameter ebenfalls setzen, oder bringen diese Settings diesbezüglich im Mode 2 zur Zeit generell noch nichts?

**Comment by pvaiko** [comment]
hilft mit Mode 2 nicht

**Comment by pvaiko** [comment]
#5985
