### ISSUE TITLE
Can not Stop Driver using DLC Grimme Pack

### ISSUE THREAD

**Issue by jspring0811** [Courseplay/courseplay#6824]
I can not Stop Driver after starting a course with one of the 3-point connected potato diggers (harvesters) in the DLC Grimme Pack.

WH 200 Eco
WH 200 S
and towed WR 200 CDW

**Comment by Tensuko** [comment]
2021-02-13 01:31 Error: Running LUA method 'mouseEvent'.
2021-02-13 01:31 I:/Dokumente/My Games/FarmingSimulator2019/mods/courseplay/CombineAIDriver.lua:1511: attempt to index field 'pipe' (a nil value)

**Comment by d0x7** [comment]
Can confirm. Same thing happend yesterday and just right now again. I cannot cancel/stop courseplay in any way (expect for reloading the game). Error in the log is the same as above.

The steering from CP is also very strange, it's driving in reverse like it was a e.g. D8 30 (direct attach and not axle with own wheels, etc.).
