### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by LEGAMINGDE** [Courseplay/courseplay#6825]
![image](https://user-images.githubusercontent.com/23504996/107845481-02138b00-6ddc-11eb-9c3b-ac49bb476395.png)
2021-02-13 09:13 Error: Running LUA method 'update'.
2021-02-13 09:13 dataS/scripts/vehicles/Vehicle.lua(2920) : attempt to call method 'getCurrentHelper' (a nil value)
2021-02-13 09:13 Error: Running LUA method 'update'.
2021-02-13 09:13 dataS/scripts/vehicles/Vehicle.lua(2920) : attempt to call method 'getCurrentHelper' (a nil value)

**Comment by Tensuko** [comment]
This is not a CP Error.
If you would attach a complete logfile and give more details in your reports then just post pics, errors or videos it would be more helpful.

**Comment by LEGAMINGDE** [comment]
is anywhere a folder where i can find older log files or do i have to wait untill its getting triggered again?

**Comment by Tensuko** [comment]
there are no old logfiles.

**Comment by LEGAMINGDE** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/5975472/log.txt)

**Comment by LEGAMINGDE** [comment]
this time its something else 🤔 i dont even have headtracking activated rn

**Comment by Tensuko** [comment]
Prefabs are no mods:
Error: Failed to open xml file 'C:/Users/lpilg/Documents/My Games/FarmingSimulator2019/mods/FS19_concreteBlocks_prefab/modDesc.xml'.
Available mod: (Hash: ac067e904c1898c7ee94c097f00d72db) FS19_concreteBlocks_prefab
Error: Missing descVersion attribute in mod FS19_concreteBlocks_prefab

This also doesn't belong into a mods folder:
Error: Failed to open xml file 'C:/Users/lpilg/Documents/My Games/FarmingSimulator2019/mods/mods/modDesc.xml'.
Available mod: (Hash: f1674f003d2daa67a9a473d252c7dad1) mods
Error: Missing descVersion attribute in mod mods

And not a single Error that leads to CP path (all just GIANTS path) so you have any Mod Issue or Mod Conflict but nothing CP related...
