### ISSUE TITLE
Game Lag unplayable Mode 2  

### ISSUE THREAD

**Issue by Iam74Niner** [Courseplay/courseplay#6829]
Using wild west map and V.00039 the game becomes unplayable in mode 2 we have by process of elimination found that when the truck is looking for a path to combine it lags the server. we also found if we deactivate avoid fruit it eliminates the lags and the trucks move better how ever the truck now will run into a combine, park in a combines path  on in general not avoid a collision at all.  any help would greatly be apricated

**Comment by Tensuko** [comment]
#5272
