### ISSUE TITLE
Conflict with helicopter mods

### ISSUE THREAD

**Issue by MoonDragon-MD** [Courseplay/courseplay#6831]
Hello I wanted to report that with all the helicopter mods (fly) conflict with courseplay, you see the screen as if it had a dark semi-transparent layer, and in the consoll come out many errors.
Here are the mods i tried:
- http://www.farmingsimulator19mods.com/ec145-gendarmerie-v2-0-fs19/
- http://www.farmingsimulator19mods.com/supercopter-airwolf-v2-0-fs19/
- http://www.farmingsimulator19mods.com/bell-uh-1-iroquois-v1-0-fs19/
- https://fs19.net/farming-simulator-2019-mods/vehicles/helicopter-v1-0/
Can you find a way to avoid this? 
Thanks

**Comment by Tensuko** [comment]
Not going to support those kind of mods.
