### ISSUE TITLE
Mode 2: Probleme mit IFA Wechselbrücken-LKWs

### ISSUE THREAD

**Issue by rohne83** [Courseplay/courseplay#6832]
Hi,
es gibt ja mittlerweile so einige LKWs wo die Kipppritsche nicht fest verbaut ist, sondern separat und mittels attacherjoint angekuppelt werden kann (die haben übrigens nicht das Problem aus https://github.com/Courseplay/courseplay/issues/6329). CP-spezifische Probleme sind mir da in der letzten Zeit beim Dreschen aufgefallen:
1. will der Pathfinder auf dem Feld sehr oft rückwärtsfahren (egal ob mit Anhänger oder ohne), auch noch direkt am Rendezvouspoint und stellt sich da mitunter dem Drescher in den Weg. Das wäre gut wenn man das ausstellen kann. Das habe ich aber schon bei https://github.com/Courseplay/courseplay/issues/6823 erwähnt und kann vielleicht auch dort behandelt werden.
2. wenn das Abtanken beendet und der Abfahrfüllstand erreicht ist, wird trotz aktivierter Fruchtumfahrung versucht auf direktem Weg zum Abladekurs zu fahren, querfeldein und andere Fahrzeuge ignorierend. Er knallt dann oft auch direkt erstmal mit dem gerade abgetankten Drescher zusammen (siehe Screenshots). Etwas auffällig, dass dieser Kurs auch extrem schnell generiert wird, während es bei anderen Fahrzeugen immer erstmal eine zeitlang dauert, bis der Pathfinder einen Kurs generiert hat. Passiert auch egal ob mit oder ohne Anhänger. Ist mir erst bei den letzten Versionen aufgefallen, davor kann ich mich an keine Probleme erinnern. Die Situation hab ich für das Logfile zweimal herbeigeführt (Debugchannels 2, 4, 12 und 14 waren das glaube ich).
![fsScreen_2021_02_14_11_32_08](https://user-images.githubusercontent.com/71030138/107881704-db417b80-6ee5-11eb-8d35-bca48997b653.png)
![fsScreen_2021_02_14_11_19_31](https://user-images.githubusercontent.com/71030138/107881891-a71a8a80-6ee6-11eb-9e09-9b52ea3a7632.png)

[log.txt](https://github.com/Courseplay/courseplay/files/5978013/log.txt)

**Comment by pvaiko** [comment]
Channel 7 wäre ganz wichtig damit wir wissen woran der Pathfinder scheitert.

**Comment by rohne83** [comment]
ist aus nem Test- und Fummelei-Savegame, deswegen die Warnings wegen der ungezippten Mods. Verhalten ist aber das gleiche wie bei den normalen Spielständen und den Screenshots oben.

[log.txt](https://github.com/Courseplay/courseplay/files/5981444/log.txt)

**Comment by pvaiko** [comment]
Das sieht aus als hätte der Pathfinder gleich bei der ersten Iteration Probleme:
```
2021-02-15 13:06 :10 [dbg7 lp5492] No path found: iterations 1, yields 0, cost inf - -inf, deltaTheta 180.0
2021-02-15 13:06 :10 [dbg7 lp5492] Nodes: 0, Penalties: fruit: 0, off-field: 0, collisions: 8
2021-02-15 13:06 :10 [dbg7 lp5492]   max fruit 50.0 %, off-field penalty: 7.5
```
und zwar mit Collisions, es ist also irgendwas da, in alle möglichen Richtungen, was aber nicht in der Liste weiter oben auftaucht. 

Wahrscheinlich ein Mod Konflikt, kann nicht sagen was genau, ich sehe auch keine zuverlässige Download Link für den IFA. Kannst vielleicht ein Screenshot posten, mit Konsolenkommando `gsVehicleDebugAttributes` und dann F5 zweimal drücken.

**Comment by rohne83** [comment]
Der W50 ist noch nicht offiziell draußen, beim modhoster gibts zumindest den L60 mit dem sich das 1:1 reproduzieren lässt (https://www.modhoster.de/mods/ifa-l60-wechselbruckenpaket). Könnte das an den sich überschneidenden blauen Quadraten liegen? Die Wechselbrücken sind ja nicht fest verbaut, sondern separat im Shop zu kaufende Objekte (also eigene xml und i3d), und auch mit eigenen Kollisionen.
Interessanterweise tritt das aber nur auf beim Abfahren zum Unload-Kurs. Beim Anfahren der Drescher auf dem Feld arbeitet der Pathfinder ja problemlos, abgesehen von dem übertrieben häufigen rückwärtsfahren.

![fsScreen_2021_02_15_15_10_08](https://user-images.githubusercontent.com/71030138/107972373-07c3c900-6fb4-11eb-80bd-1f719cb03b11.png)
![fsScreen_2021_02_15_15_17_54](https://user-images.githubusercontent.com/71030138/107972376-098d8c80-6fb4-11eb-8782-95912911b020.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5982840/log.txt)

**Comment by pvaiko** [comment]
Die Absatzrahmen sind zu gross:
![image](https://user-images.githubusercontent.com/2379521/107976184-c82eba00-6f7e-11eb-90c8-323be03be036.png)
Bei den Rahmen fehlen die Grössenangaben, deshalb nimmt Wahrscheinlich FS19 irgendein default Wert (sieht nach 8x8 m aus). Ich glaube da fehlt ein Eintrag in XML, wie z.B. bei dem LKW:
`<size width="3.5" length="7"/>`

**Comment by rohne83** [comment]
ah, super, vielen Dank! Daran scheint es tatsächlich gelegen zu haben. Mal fix eingetragen, und auf einmal wird der Kurs ums Feld herum generiert. Punkt 2 war dann also wohl eindeutig ein Mod Issue.

**Comment by pvaiko** [comment]
Für Punkt 1 wir haben #5985 schon.
