### ISSUE TITLE
Game freezes when I start generating field course

### ISSUE THREAD

**Issue by elkatronas** [Courseplay/courseplay#6834]
I'm using Medicine Creek map. And when I do field 27 (image of that field: https://i.ytimg.com/vi/_hAFm4oslJY/maxresdefault.jpg) I click on generate field course and the game freezes forever. Only killing with task manager ends that misery. How can I fix that?

**Comment by Tensuko** [comment]
logfile with debugchannel 7 active, then try generate that course.

Btw, 'freeze forver' never happened. Patience is the key.

**Comment by elkatronas** [comment]
Here is that logfile with channel 7.
[log.txt](https://github.com/Courseplay/courseplay/files/5980396/log.txt)

**Comment by elkatronas** [comment]
After 30 minutes course was generated eventually. Thanks for the help.
