### ISSUE TITLE
Overloader unloads as expected, but sits in fruit which leads to traffic collisions with other harvesters

### ISSUE THREAD

**Issue by AUZ001** [Courseplay/courseplay#6835]
As the title says, unfortunately, once the overloaders have finished unloading a harvester, it will back up a little and either sit or move onto the lane of fruit next to it and then just sit waiting, meanwhile, the other harvesters are fast approaching and cannot continue because the overloader won't move.

Is there a way to get around this issue?

**Comment by Tensuko** [comment]
Keep avoid fruit on on unloader and combine.
