### ISSUE TITLE
baler with bale wrapper is not unloading 

### ISSUE THREAD

**Issue by LEGAMINGDE** [Courseplay/courseplay#6837]
![image](https://user-images.githubusercontent.com/23504996/107932081-72a5dd80-6f7d-11eb-9489-4288c5268cc6.png)

https://youtu.be/GRI-VOuOKz8

**Comment by LEGAMINGDE** [comment]
![image](https://user-images.githubusercontent.com/23504996/107935363-966b2280-6f81-11eb-98ee-bd4260bf6c29.png)
and why does he want to get refilled

**Comment by 60erjonny** [comment]
Hallo
Welcher Mod ist das...?

**Comment by LEGAMINGDE** [comment]
alpine dlc

**Comment by 60erjonny** [comment]
Ich habe das DLC nicht, deswegen kann ich es nicht testen...sorry
Du willst Silageballen erzeugen...? 
Muss man hierfür, manuell die Wickelfolie evtl. auffüllen...?

**Comment by LEGAMINGDE** [comment]
nö sowas gibts eigentlich nur in mods

**Comment by Tensuko** [comment]
Funktioniert wie es soll:
![fsScreen_2021_02_15_13_45_05](https://user-images.githubusercontent.com/27344744/107948400-0edadf00-6f94-11eb-8aba-2803406c8eb3.png)
