### ISSUE TITLE
Stop am Endpunkt setzt sich auf deaktiviert, wenn Abfahrer entlassen wird

### ISSUE THREAD

**Issue by BauerNepo** [Courseplay/courseplay#6845]
Hallo, erstmal wieder ein herzliches Dankeschön für eure unermüdliche Arbeit an Courseplay. 

Da nun bei Mode 5 wieder die Auswahlmöglichkeit besteht für das Stoppen am letzten Wegpunkt, hat das für mich ein altes Problem zurückgebracht:
Wenn mein Fahrzeug sich unterwegs festfährt, stoppe ich per Gamepadbefehl den Fahrer, fahre das Fahrzeug wieder in eine korrekte Position und aktiviere Courseplay wieder. Dabei stellt sich jedoch die Funktion "Halten am letzten Wegpunkt" automatisch wieder auf deaktiviert, was dann dazu führt dass mein Fahrzeug nicht dort stoppt wo ich es brauche. Leider geht das wieder aktivieren bei mir schnell vergessen, da ich ja nur kurz eine Korrektur vornehme ohne dass ich dabei das HUD öffne.
Nun wäre dafür für mich die beste Lösung, dass standardmässig Halten am letzten Puntk aktiv wäre und man es deaktivieren müsste, da für mich in fast allen Fällen ein Halten am letzten Punkt sinvoll ist. Bei mir ist es einzig zum festfahren eines Fahrsilos, wo ich einen Kurs erstelle der immer wieder von neuem abgefahren werden soll.

Besten Dank fürs anschauen.

Gruss vom BauerNepo

PS: Ich habe in meinem Issue (https://github.com/Courseplay/courseplay/issues/6297) eine für mich passende Lösung gefunden, habt Ihr das gesehen?

**Comment by Tensuko** [comment]
Muss am Tastenbefehl liegen oder so.
Muss ich mir mal angucken.

**Comment by Tensuko** [comment]
Passiert wenn man den Abfahrer entlässt

**Comment by BauerNepo** [comment]
Ja, war aber glaub auch schon im 17er so. Wenn jedoch die Funktion standartmässig aktiviert wäre, und ich es bei bedarf deaktivieren müsste wäre das für mich perfekt. Denn wenn ich das deaktivieren vergessen würde, käme ja eine Meldung dass der Abfahrer steht, da merke ich dann schon dass die falsche Einstellung gewählt ist. So jedoch fährt der Abfahrer irgendwohin, wo ich ihn gar nicht brauche :-)

**Comment by Tensuko** [comment]
Das soll auch so sein, bzw ist auch so, aber warum er es umstellt beim entlassen weis ich gerade nicht.

**Comment by BauerNepo** [comment]
Ok, bei mir ist es jedenfalls nicht so. Wenn ich nichts im HUD anklicke, stoppen meine abfahrer nie am Ende der Strecke. Das muss ich jedesmal noch zusätzlich anwählen.

**Comment by andremeyer123** [comment]
Er ist immer auf deaktiviert , wenn du es bei einer tour brauchst das er anhält must du es einstellen ,Courseplay speichert es nicht ab als standart einstellung.

**Comment by Tensuko** [comment]
@andremeyer123 
Die Einstellung ist default = true
Das Problem lag darin, dass beim stoppen des Fahrers das Setting umgeschaltet wurde.

Zitat aus dem push:
"Never set or reset stop at end automatically."

**Comment by andremeyer123** [comment]
Wenn der fahrer entlassen wird ist für cp die tour beendet  daher geht er auf deaktiviert .  Sagte ja schon öfters wäre schön wenn cp ein pausen modus hätte dann bräuchte man viele sachen nicht andauernt einstellen wie z.b. beim sähen hängt am baum mus ihm entlassen mus dann einstellen  am nächstgelegenen sonst fängt er von vorne an .

**Comment by Tensuko** [comment]
> Wenn der fahrer entlassen wird ist für cp die tour beendet daher geht er auf deaktiviert

Hat damit rein gar nichts zu tun. Wie gesagt, lies die Push Message, es bleibt nun so wie man es eingestellt hat.
Neues Fahrzeug = default Setting Stop at End = true.


> Sagte ja schon öfters wäre schön wenn cp ein pausen modus hätte dann bräuchte man viele sachen nicht andauernt einstellen wie z.b. beim sähen hängt am baum mus ihm entlassen mus dann einstellen am nächstgelegenen sonst fängt er von vorne an .

User Problem, ich habe meine Fahrer immer auf nächsten passenden Wegpunkt.

**Comment by andremeyer123** [comment]
Ich nehm immer den starken bauern und schmeiss ihn aufs feld dann brauch ich ihm nicht entlassen :D

**Comment by Tensuko** [comment]
Try Version 6.03.00041 or higher and report.

**Comment by BauerNepo** [comment]
Hallo, funktioniert zwar nicht exakt so, wie ich mir das gewünscht hätte, aber trotzdem viel besser als vorher. Nun bleibt die Einstellung so angewählt, wie zuletzt eingestellt wurde ohne dass sich etwas umstellt. Für mich perfekt wäre halt, dass die Einstellung automatisch auf "aktiv" gesetzt würde und ich jedesmal selber auf "deaktiviert" stellen muss wenn das gebraucht wird. Also exakt umgekehrt, wie es vor diesem Update war. Jedoch ist mir bewusst, dass ihr nicht auf jeden Userwunsch eingehen könnt, da jeder seine eigenen Vorstellungen davon hat wie Courseplay funktionieren soll. Also trotzdem ein herzliches Dankeschön für diese Änderung.
Gruss Bauer Nepo

**Comment by Tensuko** [comment]
Nein, es wird auf aktiv gestellt bleiben, weil das dei Hauptfunktion ist und ein Wunsch war von einigen Usern. Eben damit man nicht immer aus machen muss, wenn man von A nach B fahren will.

Wenn er nicht an B stoppt, weil man es vergessen hat, sit die Katastrophe größer, als wenn man vergessen hat, es aus zu machen.

Stehen bleiben statt weiter fahren ist eben nicht so schlimm wie sonst wo hin fahren (zum start) obwohl er stehen bleiben sollte.

**Comment by BauerNepo** [comment]
Ich sehe schon, wir missverstehen uns. Das was ich oben geschrieben habe würde genau das machen was du gerade geschrieben hast. So wie es nun ist, kann es eben gerade passieren, dass das Fahrzeug nicht bei B stoppt, weil man vorher vielleicht einen Kurs benutzt hat der nicht halten soll. Wenn man nun vergisst die Funktion wieder abzuschalten (gerade weil es eben **nicht** so ist, dass das halten am letzten Punkt **automatisch ** auf aktiv steht), passiert dann genau die von Dir  bezeichnete grössere Katastrophe. Würde die Funktion automatisch auf Aktiviert stehen, wäre der maximal mögliche Schaden dass mein Rundkurs unterbrochen wird und ich dann einmalig umstellen muss, und dann der Abfahrer weiter seine Kreise ziehen könnte. Aber wie schon gesagt, so wie es jetzt ist, ist es wesentlich besser als vorher.

**Comment by Tensuko** [comment]
Natürlich speichern wir die Option so wie sie ist.
Gedanken lesen können wir nicht.
Wenn man es umstellt, muss man sich im klaren sein, das auch wieder zurück zu schalten.
