### ISSUE TITLE
Probleme beim Drescher abtanken

### ISSUE THREAD

**Issue by Risca81** [Courseplay/courseplay#6846]
Guten Morgen!

Zuerst einmal vielen Dank für dieses tolle Script für den LS!

Ich habe seit kurzem festgestellt, dass beim Abtanken des Dreschers der Abfahrer des Öfteren in den Drescher fährt, also stumpf nach rechts abbiegt, sobald der Abtankvorgang abgeschlossen ist. Ganz oft passiert es, wenn der Drescher beim Abtanken weiter fährt..aber auch, wenn er anhält.

Das Problem habe ich bei Abtanken mit Anhänger und Überladewagen. 

Ich habe Fruchtumfahrung und Wenden im Feld deaktiviert. 

Meine Version ist:  6.03.00040

Was benötigt ihr noch für Informationen?

Grüße

_Originally posted by @Risca81 in https://github.com/Courseplay/courseplay/discussions/6844_

**Comment by Tensuko** [comment]
Fruchtumfahrung auf aktiviert schalten! Wenden auf dem Feld hat eh keinen Einfluss auf den Mode2, das wäre egal.

**Comment by Risca81** [comment]
Hallo.
Danke für den Hinweis.
Ich werde es testen. 
Grüße
--
Gesendet über myMail für Android Dienstag, 16 Februar 2021, 09:28AM +01:00 von Tensuko  notifications@github.com :
