### ISSUE TITLE
Problem bei der Vorgewendeberechnung

### ISSUE THREAD

**Issue by rellek82** [Courseplay/courseplay#6847]
Hallo.  
Seit der v6.03.00035 kann bei mir bei der Vorgewendeberechnung mit "Kurze Seite" kein Kurs mehr berechnet werden, bzw. berechnet er mir denn den Kurse wie bei " Rundherum". 
Mit der v6.03.00034 funktioniert das noch alles normal.

- Modus: Feldarbeit
- Karte: Ravenport
- Feld 19
- Fahrzeug: Rotselmash RSM 161 mit Rotselmash Draper Stream 900

Gibt es da spezielle Einstellungen? Ich habe es schon mit diversen Anzahlen der Vorgewendebahnen probiert, hatte aber kein Erfolg.

**Comment by Tensuko** [comment]
Bitte einmal ein Bild davon, welche Einstellungen du gemacht hast.

**Comment by rellek82** [comment]
![fsScreen_2021_02_16_13_18_36](https://user-images.githubusercontent.com/57573110/108062557-41e7a600-705a-11eb-9250-c000838af1e3.png)  
Erstes Bild ist mit der v6.03.00034

![fsScreen_2021_02_16_13_22_32](https://user-images.githubusercontent.com/57573110/108062627-5b88ed80-705a-11eb-9301-bfdb4403ecbd.png)
Zweites Bild zeigt den Versuch mit der v6.03.00035

**Comment by Tensuko** [comment]
Im Bild der aktuelle Version kommt die Meldung weil du kein Feld ausgewählt hast...
Und bitte, die Meldung kennen wir, das ist es nicht was uns interessiert :)


@pvaiko Log mit channel 7
[logdbg7.txt](https://github.com/Courseplay/courseplay/files/5988544/logdbg7.txt)

**Comment by rellek82** [comment]
![fsScreen_2021_02_16_13_34_43](https://user-images.githubusercontent.com/57573110/108063650-d3a3e300-705b-11eb-9e05-ebc8a9dc9b0a.png)
Das mit der vergessenen Feldauswahl war natürlich mein Fehler, aber auch mit dem richtigen Feld funktioniert es nicht.

![fsScreen_2021_02_16_13_35_00](https://user-images.githubusercontent.com/57573110/108063723-f0401b00-705b-11eb-963f-4cd6ede7a8a4.png)
Die Option mit "Enges Feld" funktioniert.
Mich wundert es halt, dass es in der älteren Version funktionierte, in den neueren aber nicht mehr.

**Comment by Tensuko** [comment]
Try Version 6.03.00041 or higher and report.

**Comment by rellek82** [comment]
Danke, werde ich heute Abend gleich probieren und euch dann mein Ergebnis mitteilen.

**Comment by rellek82** [comment]
Habe jetzt die Kursberechnung getestet und es funktioniert mit der neuen CP-Version wieder alles.   Vielen Dank für die schnelle Bearbeitung.
Danke auf für eure Arbeit für dieses tolle Script. In Verbindung mit Autodrive lasssen sich auch große Karten alleine bewirtschaften.
