### ISSUE TITLE
Cant get it to unload into Overload Station

### ISSUE THREAD

**Issue by BlackHawk2211** [Courseplay/courseplay#6848]
I am just tring to get course play to unload into this https://www.youtube.com/watch?v=LX6GBXtnjxI before I have a semi and trailer take it half way across the map to unload into bunker if that is possible. I dont know if it stops before it enters in due to it being a trailer or collision setting I would just like some simple help on how to get it to work if I can.

**Comment by Tensuko** [comment]
Tested with Overloading Station 1.1.0.2 and CP 6.03.00046
Works perfectly, you also see the course how it should look like.
![fsScreen_2021_02_27_09_53_00](https://user-images.githubusercontent.com/27344744/109382585-9c49f780-78e1-11eb-8273-ac7ebfbc1f2f.png)
