### ISSUE TITLE
CoursePlay (.00041) forgetting set waypoints

### ISSUE THREAD

**Issue by 75jmo93** [Courseplay/courseplay#6852]
Record simple course for auger cart unload. Park cart next to unload point (another auger cart on edge of field) and set the "wait" waypoint so it will unload. Drive away and stop the recording. As soon as I click "drive course" the waypoints disappear in the control menu, but still appear along the waypoint lines on the map. Tractor just drives through like the waypoint isn't even there.

No issues unloading the combine.

**Comment by Tensuko** [comment]
And again.... logfile ?
https://github.com/Courseplay/courseplay/wiki
Screenshots ?
