### ISSUE TITLE
Courseplay v6.03.00041 Turns too narrow

### ISSUE THREAD

**Issue by harleymac** [Courseplay/courseplay#6854]
Hi, 
with v6.03.00041 the problem of too narrow turn is back. This causes a problem especially for trucks with trailers that get stuck on obstacles at the roadside.
Best regards

**Comment by Tensuko** [comment]
'Too Narrow turn is back' -> https://github.com/Courseplay/courseplay/wiki

**Comment by harleymac** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6004253/log.txt)

**Comment by Tensuko** [comment]
log is nice but I still don't know what you talk about.
Maybe some screenshots ? Whats the actual problem ?

**Comment by harleymac** [comment]
Hi Tensuko, problem found in another mod. 
Thanks, issue can be closed.

**Comment by Tensuko** [comment]
Okay, thanks for info!
