### ISSUE TITLE
Frage: Precision Farming DLC

### ISSUE THREAD

**Issue by Aichinto** [Courseplay/courseplay#6855]
Hallo Zusammen, 
ich hätte mal eine Frage zum Precision Farming DLC bzw zur Kombination mit CoursePlay.

Ist geplant das man die Bodensonde oder das Teil von Claas (Vertexdesign) demnächst auch in CP verwenden kann ? 
Oder gibt es hier bereits eine Lösung  ? 

Habe leider noch nichts dazu gefunden. 

beste grüße 
und gern immer weiter so! 
Ihr macht einfach echt ne klasse Arbeit

**Comment by Tensuko** [comment]
Bodensonde -> nein

Das Teil von Class -> geht doch.
Du musst der Einfachheithalber ein weiteres Gerät anhängen (Grubber oder sowas), aufklappen, starten, mit laufen lassen.

Ansonsten habe ich weitere Anpassungen bereits vorbereitet, nur brauchen wir noch eine Änderung seitens Vertex Design, da bin ich mit denen in Kontakt.

Btw das wäre was für Discussions gewesen:
https://github.com/Courseplay/courseplay/discussions

**Comment by Aichinto** [comment]
ja "mitfahren" geht, aber nur direkt am feld, wenn man z.b. einen streuer hat und den gleich per kurs nachfüllen lassen will wirds wieder problematisch.

Aber danke 

und sorry das mit Disscussions hab ich garned gesehen

**Comment by Tensuko** [comment]
Discussions ist auch neu, aber wie gesagt, das wird noch irgendwie kommen mit dem Claas Scanner.
