### ISSUE TITLE
Mode9, unload into some trailers doesn't work.

### ISSUE THREAD

**Issue by ice81rm** [Courseplay/courseplay#6856]
Hi guys! As always thanks for the great work ...
After the last update, the loader stops and does not unload into the trailer.
I have tried with the previous version and it is fine
![Screenshot (281)](https://user-images.githubusercontent.com/39805100/108433297-0c071500-7246-11eb-850e-0f3cba5e5d73.png)

**Comment by Tensuko** [comment]
Your waitpoint is way to close to the trailer.

**Comment by ice81rm** [comment]
I recorded the path of the shovel with the trailer already in place.
The same path with the previous version works fine.

**Comment by Tensuko** [comment]
> 
> 
> Your waitpoint is way to close to the trailer.

Do this (move Waitpoint more far away) and try it out....

**Comment by Tensuko** [comment]
Next Version will also have a better Trailer approch for Mode9 wich will also requier a bit more distance to the trailer. But then the approach is much more smoother.

**Comment by Tensuko** [comment]
Can you try if it is working for you now with Version 6.03.00042 ? The Driver will slow down when approaching the trailer.

**Comment by Albatrozs112** [comment]
I have the same problem,with new version @Tensuko

**Comment by Tensuko** [comment]
> 
> 
> I have the same problem,with new version @Tensuko

Informations guys.... Informations...
Screenshots, with Course shown and stuff, where is it stuck..... I can't help without Informations....

**Comment by ice81rm** [comment]
Even with the latest version the problem continues to arise ....

I repeat that with version 6.03.00041 I have NO problems
![Screenshot (282)](https://user-images.githubusercontent.com/39805100/108706808-70a8c500-750f-11eb-8ab8-d61d71c202b0.png)

**Comment by Tensuko** [comment]
> Next Version will also have a better Trailer approch for Mode9 wich will also requier a bit more distance to the trailer. But then the approach is much more smoother.

**Comment by Tensuko** [comment]
The Problem I see on the screenshots here it the waitpoint too close to trailers.
As I did test arround it is working.
But another problem showed up with different kind of trailers (doesn't matter if mod or vanilla).
We already have a look.
But no matter about that, give the driver some distance...

**Comment by Tensuko** [comment]
Just that you guys have an example of what I am doing...
Those 2 trailers at the right (+ the current one) is working and those on the left (truck + Trailer from Roland) are not working.

![fsScreen_2021_02_22_15_25_32](https://user-images.githubusercontent.com/27344744/108721410-414f8380-7522-11eb-90cc-f7d9d7c4e79c.png)

There is a difference in 'it doesn't work' and 'it doesn't work with some trailers' as I usual not testing all trailers (ofc...).

**Comment by Albatrozs112** [comment]
In my case, he find trailer and 0.5m befor him just unload bucket on the ground

**Comment by Tensuko** [comment]
> 
> 
> In my case, he find trailer and 0.5m befor him just unload bucket on the ground



> 
> 
> > I have the same problem,with new version @Tensuko
> 
> Informations guys.... Informations...
> Screenshots, with Course shown and stuff, where is it stuck..... I can't help without Informations....

**Comment by ice81rm** [comment]
Con l'ultimo aggiornamento NON ho riscontrato problemi
Grazie

**Comment by Tensuko** [comment]
Ok I guess you got the version with fix as direct download, becouse it is not on release yet.

**Comment by ice81rm** [comment]
si ho scaricato l'ultima versione qui in questo "forum"
