### ISSUE TITLE
Multiplayer issues

### ISSUE THREAD

**Issue by shambala12** [Courseplay/courseplay#6857]
Has anyone been getting issues with courseplay on a dedi server. In the last two weeks, ive been having lots of performance and saving issues on my server. Ive removed quite a few mods which i added recently to work out what the issue is but am forced to believe its cp. cp pretty much always throws errors from what ive seen but i keep getting "connection manager" errors and causes the game to be stuck on requesting access from host or whatever that message is when joining the server. Thanks

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/issues?q=is%3Aopen+is%3Aissue+label%3A%22MP+General%22
