### ISSUE TITLE
New Bale Collector Mode 

### ISSUE THREAD

**Issue by pvaiko** [Courseplay/courseplay#6859]
Just added a new mode for collecting bales, replacing the old, unused mode 7.  With this mode you don't need a fieldwork course to collect bales from a field with a bale loader, it'll scan the field for bales and automatically load them.

You still need an unload course (just like when using a bale loader in mode 6), to unload the bales at a sell point or anywhere else.

Select Mode 7, select a field, then 'Collect bales' 

![image](https://user-images.githubusercontent.com/2379521/108576315-bd5b8880-72e2-11eb-8492-74174a452a6d.png)

**Comment by jspring0811** [comment]
We are so excited to try this :)   Have been thinking this would be an awesome feature.

**Comment by Misamangame** [comment]
Wow what a surprise. Great work guys!

**Comment by Lars-LS17** [comment]
I am so excited to try this :). But Why, why am I currently in winter :-D

Great Work! Thank you!

**Comment by andreasthu** [comment]
Super, danke
Hab es gerade ausprobiert. Funktioniert sehr gut.
Lg
Andreas

**Comment by 60erjonny** [comment]
Hallo
Bei mir geht es leider nicht, kann ich was zur Fehlerursache beitragen...?

**Comment by ct177mak** [comment]
Many thanks to Dev :)

**Comment by Tensuko** [comment]
> 
> 
> Hallo
> Bei mir geht es leider nicht, kann ich was zur Fehlerursache beitragen...?
> Karte: NFM 4fach o.G.
> Würde Log hier reinstellen, welchen Debugchannels muss ich hier aktivieren...

Du könntest erst mal sagen, was genau du gemacht hast und wo es hängt.

**Comment by 60erjonny** [comment]
Hallo

Also, ich habe auf der NFM auf Feld 28 ( Wiese ) mit einem Big M gemäht und mit einer Wickelkombi ( Kuhn FBP 3135 WW -Mod ) dann daraus Silageballen gepresst. Nun versuche ich, mit einem Fendt 313 Vario und einen Ursus T-127 die Ballen einzusammeln. Dazu habe ich einen Abfahrkurs zur Gärtnerei mit dortigen Pausepunkt und wieder zurück zur Wiese 28.
jetzt steht das Gespann auf dieser Wiese mit einstellten "Modus 7" und Kurse beginnen am "Collect bales " CP und wartet.
Ich ich irgentwas noch vergessen...?

**Comment by dederpt** [comment]
Great Work! Thank you!

**Comment by Tensuko** [comment]
> Dazu habe ich einen Abfahrkurs von der Wiese zur Gärtnerei mit dortigen Pausepunkt und wieder zurück zur Wiese 28.

Kein Wartepunkt, ein hier abladen WP wird benötigt.
Ansonsten nur den einen Kurs geladen und keinen Feldkurs oder sonstiges?
Ansosnten versuch mal am Kurs zu starten mit nächsten passenden Wegpunkt.

**Comment by andreasthu** [comment]
> Hallo
> 
> Also, ich habe auf der NFM auf Feld 28 ( Wiese ) mit einem Big M gemäht und mit einer Wickelkombi ( Kuhn FBP 3135 WW -Mod ) dann daraus Silageballen gepresst. Nun versuche ich, mit einem Fendt 313 Vario und einen ( Ursus T-127 - Mod ) die Ballen einzusammeln. Dazu habe ich einen Abfahrkurs von der Wiese zur Gärtnerei mit dortigen Pausepunkt und wieder zurück zur Wiese 28. Jetzt steht das Gespann auf dieser Wiese ( 28 ) mit einstellten "Modus 7" / Kurse beginnen am "Collect bales " CP / Feld 28 und wartet.
> Habe ich irgentwas noch vergessen...?

Du hast aber schon von Wiese 31 einen Feldrandkurs generiert und diese nummer im CP hud eingestellt?
Bild im 1. Beitrag, 2. Rote Kringel.
Lg
Andreas

**Comment by Tensuko** [comment]
Feldrandkurs nur nötig, wenn die Wiese kein Feld ist und wenn dann sollte man das über den Feldrandscanner mit einer User nummer verstehen (in dem Fall würde es ja die 28 sein)

**Comment by 60erjonny** [comment]
Hallo
Geht nicht...
Versuch mein Glück jetzt auf Feld 42 , das gepresste Stroh ein zu sammeln...
Feldrand wird angezeigt und ist auch geladen, aber er fährt einfach nicht los...
![Screenshot (39)](https://user-images.githubusercontent.com/63659182/108605375-ffa0ca80-73b3-11eb-8789-c82a4a6ffa8d.png)

**Comment by pvaiko** [comment]
@60erjonny logfile mit channel 7 und 14

**Comment by 60erjonny** [comment]
Hallo

Bitte schön...
[log.txt](https://github.com/Courseplay/courseplay/files/6016256/log.txt)

**Comment by pvaiko** [comment]
Diese Ballen haben kein Node ID, komisch, wie genau hast du die erstellt?

**Comment by 60erjonny** [comment]
Hallo
Mit der LSB 1290 B und den Fendt 313...keine Mod`s...
Habe nochmal rum probiert...nach Neustart habe ich eine Tour los fahren lassen können...wenn er aber wieder erneut, zurück auf das Feld kommt bleidt er stehen...

**Comment by pvaiko** [comment]
@60erjonny ok, hast du ein Savegame? Und welche Map ist das, NFM sagt mir nix.

**Comment by 60erjonny** [comment]
Hallo

Nordfriesische Marsch ohne Gräben...2.6...
[Uploading savegame1.zip…]()

**Comment by pvaiko** [comment]
irgendwas mit dem upload ist schiefgegangen

**Comment by 60erjonny** [comment]
Hi 2. Versuch...
[savegame1.zip](https://github.com/Courseplay/courseplay/files/6016597/savegame1.zip)

**Comment by pvaiko** [comment]
Kann nur angucken wenn du eine Saubere Link zu diese Map hast. Also ohne Malware und Adware usw.

**Comment by 60erjonny** [comment]
https://www.fedaction-letsplay.de/ls19/4fach-nf-marsch/

**Comment by betrox007** [comment]
Nice Improvement...wanna try this one..

**Comment by Partyborner** [comment]
Habe nochmal rum probiert...nach Neustart habe ich eine Tour los fahren lassen können...wenn er aber wieder erneut, zurück auf das Feld kommt bleibt er stehen...

Das gleiche Problem habe ich auch

**Comment by Tensuko** [comment]
> Habe nochmal rum probiert...nach Neustart habe ich eine Tour los fahren lassen können...wenn er aber wieder erneut, zurück auf das Feld kommt bleibt er stehen...
> 
> Das gleiche Problem habe ich auch

Es wäre 100mal hilfreicher, wenn wir statt 'habe ich auch' entsprechend Hilfreiche infos bekommen könnten. Wie oben geschrieben: logfile mit channel 7 und 14

**Comment by Vama1965** [comment]
Tach
Habe mal versucht mit den channels 7 und 14  ne Log zu machen
Ich habe auch das problem mit dem stehenbleiben.
MfG
Torsten
[Log Nf Marsch 4Fach 2.5 Ballen sammeln Courseplay Bug.txt](https://github.com/Courseplay/courseplay/files/6018063/Log.Nf.Marsch.4Fach.2.5.Ballen.sammeln.Courseplay.Bug.txt)

**Comment by Partyborner** [comment]
https://pastebin.com/eaPBWnJM

**Comment by Partyborner** [comment]
die komplette log nochmal
[log.txt](https://github.com/Courseplay/courseplay/files/6018091/log.txt)

**Comment by pvaiko** [comment]
Give it a try with 44.

**Comment by CaptSully** [comment]
Just used the new bailing mode 7 to clear a field of 176 bales of hay. Successfully picked up every bale on the field (even a few off the field) and stored them in my hay bale storage shed without a single hiccup. Very impressive. Great job to all the developers! Excellent enhancement to CP. Thanks.

**Comment by 60erjonny** [comment]
Hallo

Nach einigen Test`s...
Kann ich jetzt auch bestätigen, bei mir funktioniert es auch zuverlässig...!
Tolle Arbeit und noch dazu für uns, auf die schnelle gefixt...!

**Comment by Vama1965** [comment]
Tach
Jetzt klappt's auch bei mir.
Vielen Dank :)
MfG
Torsten

**Comment by Paul2510** [comment]
Hallo ich weis es passt nicht hier her aber was muss ich machen das der Mod arbeitet?? LG

**Comment by Tensuko** [comment]
Naja meinst du jetzt Mod = Modification = CP oder Mode = Modus ?
Ich sag mal Modus:
- Mindestens Version 6.03.00044 von hier haben: https://github.com/Courseplay/courseplay/releases
- Ballensammelwagen hinter Traktor hängen
- Modus 7 aktivieren (kleiner Ballen als Symbol)
- Kurs vom Feld zum Platz wo du abladen wills aufnehmen (mit Abladepunkt wo du abladen willst, fals Stapel stehen sollen, bitte rückwärts) und zurück zum Feld
- Feld auswählen und Abfahrer starten

**Comment by Paul2510** [comment]
Vielen Dank! Das hab ich gemeint! Mit Auto Drive gehts noch nicht oder?? LG

**Comment by AUZ001** [comment]
I used to use a road train with an offset of 2.5m using Easy Auto Lader to automatically pick up all the bales using the same CP course the Header is using, but for some reason, this is now disabled for trucks ? Using the same equipment, all I can do now the mode 10 leveling/compacting. 
Is this intentional ?

**Comment by pvaiko** [comment]
@AUZ001 you still should be able to do that in Mode 6 as before, this is a new mode. If it isn't working now it isn't because of this change.

**Comment by pvaiko** [comment]
@Paul2510 does not yet work with AutoDrive, shouldn't be a big deal to make it work.

**Comment by Paul2510** [comment]
OK! Many thanks for you work!

**Comment by lcc1211** [comment]
Excellent!

**Comment by djnekkid** [comment]
This is awesome you guys, but I can't get it to work 100%.

I've made a field of silage bales, and while it mostly picks them up without any problems, the dropping off part is, atlast for me, not working.
Fendt Vario 900 with an anderson RBM2000 bale trailer

I use theese bale sheds:
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=150708&title=fs2019

If i have a flatbed with strapped on bales, they get picked up by the shed without any problems at all.

Do i need any unload or P-markers?
Optionally any known good sheds?

ps. Devs: you rock

**Comment by CaptSully** [comment]
@djnekkid - I use the same bale sheds. You need to put an unload mark (the icon that looks like a dump truck in the course generator)  where you need to unload in front of the shed as part of your unload course from the field. Hope this helps.

**Comment by betrox007** [comment]
Try This Mode on v6.03.00044 and it is work nicely, just set course for unload and no need to set field course... Thank's to Devs for all Effort and hard work..

**Comment by Tensuko** [comment]
@djnekkid 
When I find some time I will make a How to Video (at least visual) like I did with Mode3.
But it takes some time like prepare everything and stuff...

**Comment by djnekkid** [comment]
@Tensuko : i can possibly do that myself if u want me to.
I've not yet tested this feature with the 'unload', but i assume it works as @CaptSully saies :)

**Comment by Autobosl** [comment]
bei mir funktionierte der neue Modus nicht,
bis ich den lsfm stätionäre Presse mod von Farmer Andy als Übeltäter ausfindig gemacht habe. Presse verkauft jetzt läuft alles prima.
Was mir noch fehlen würde ist, das verbundene Felder erkannt werden. Hier sammelt er bei mir nur das genannte Feld ein.

**Comment by 60erjonny** [comment]
@Autobosl ...versuche mal bei einen neu erstellten Feld den neu gescannten Feldrandkurs eine neue Nummer zu vergeben...dann sollte es gehen...

**Comment by jspring0811** [comment]
Question:  It appears that the location of the bales is mapped out at the start (I threw a runaway bale back onto the field after starting the collector and this bale was skipped).  So, does this mean we can not run 2 bale collectors on the same field at the same time?  (I guess collisions also may be a problem).

**Comment by pvaiko** [comment]
Field is scanned at start, when returning from the unload course or when we miss a bale (drove to the bale but did not pick up anything).

And yes, only one bale collector per field is allowed, currently there's nothing in the code to share the bales between multiple drivers. Also, we don't remember which bales we already collected, so if you wanted to put the collected bales on the same field that would also be a problem. 

May add this latter one but sure don't want to open a can of worms with multiple drivers on the same field.

**Comment by Tensuko** [comment]
@Autobosl 
Zusammen gelegte Felder immer mit dem Feldrandscanner einmal Scannen und einer Nummer zuweisen, so dass diesers Feld als (User) auftaucht. Dann geht es.

**Comment by Autobosl** [comment]
Ok Danke. Dann liegt der Fehler bei mir. Feldkurs ist eigentlich angelegt. Da der Mäher, Wender und Schwader ja auch auf dem verbundenen Feld arbeiten.
Werde das heute nochmal testen.

**Comment by Tensuko** [comment]
https://youtu.be/98TIUAgazZg

**Comment by betrox007** [comment]
it is also work perfectly with unload course to bale storage.. khttps://youtu.be/aY3wUPHxD8M

**Comment by Tensuko** [comment]
Thats nice! :)

**Comment by TyKonKet** [comment]
Does it also works on dedicated servers?

**Comment by Gonimy-Vetrom** [comment]
@pvaiko Hello. Made the picture a little sharper. Maybe you will like it. Take a look. At the end of the name file, delete the .zip. :)
[iconSprite.dds.zip](https://github.com/Courseplay/courseplay/files/6045357/iconSprite.dds.zip)

**Comment by Tensuko** [comment]
@Gonimy-Vetrom 
Can't open the .zip file, can you add that file in a pullrequest ?
It works a bit like the translations you do.
Or try to .zip it again and upload again, not sure what went wrong.
But thank you for the effort :)

**Comment by Gonimy-Vetrom** [comment]
This is not an archive. I just added (.zip) to make the github accept the format. You only need to delete (.zip)

**Comment by Tensuko** [comment]
alright! got it :)

**Comment by Tensuko** [comment]
Looks very good, thank you! I am very new to .dds files with Paint.net only playing arround :)
Will be in the next Version.

**Comment by Rumspringa90** [comment]
Wäre nice, wenn man in dem Modus auch die Ballenwickler benutzen könnte.

**Comment by Tensuko** [comment]
Ist schon als Discussion vorhanden und ja ist in Planung.

**Comment by Reiko40** [comment]
Ich spiele auf Nordfriesischen Marsch auf einem Nitrato Server, habe die neueste Cp Version ( 47) auf dem Server. Wenn ich den Kurz zur Mischfutterfabrik ( nimmt Ballen an) einfahre und zurück . Ich habe verschieden Start und Endpunkte gewählt, auch von der Mitte vom Feld. Es handelt sich hierbei um Quaderballen ( Stroh) mit Standartpresse gepresst. Wenn ich Cp aktiviere kommt die Meldung Arbeit erledigt. In der log habe ich keine Fehler gefunden. Vieleicht bin ich der Fehler. Habe richtige Feld ausgewählt und auch den richtigen Modus.

**Comment by 60erjonny** [comment]
Hallo @Reiko40 
Wechsel kurz den Modus und gehe dann wieder auf Ballensammeln, dann müsste es gehen...

**Comment by Paul2510** [comment]
Was muss ich machen das die Ballen auf einen Platz ohne trigger bageladen werden?? LG

**Comment by 60erjonny** [comment]
Hi @Paul2510 

weiter oben ist ein Video dafür...: https://github.com/Courseplay/courseplay/issues/6859#issuecomment-784974835

**Comment by Lars-LS17** [comment]
Ich habe auch mal eine kurze Frage. 
Ich habe den neuen Modus noch nicht getestet. 
Kann bzw. darf ich den Abladepunkt auf dem Feld machen, sodass der mir alle Ballen an der Feldseite lagert?
Vermutlich wird es dann zu Problemen kommen, weil er diese Ballen dann ja wieder "sammeln" will, weil die auf dem Feld liegen.

Kurze Info über eurer Erfahrung wäre klasse.

**Comment by Reiko40** [comment]
Danke jonny. Werde ich beim nächsten mal machen.

**Comment by pvaiko** [comment]
@Lars-LS17 das ist noch nicht implementiert, wird aber kommen.

**Comment by lcc1211** [comment]
Mit diesem Kurs bin ich sehr zufrieden. On Hobbs Farm Feld nummer 13 habe ich mehr als 200 balen gemacht und habe fast alle gesammelt. I glaube 2 or 3 warren liegengelassen.

**Comment by McGyver-LP** [comment]
We have a problem do, with anderson dlc and bale loader it runs a lua error on it, by removing the anderson dlc it is gone. Tried it on PC County and Chellington

**Comment by Gariot** [comment]
Pretty amazing so far, it works pretty great. One question - does it work with the cotton bales and the cottonbale collector from the John Deere Cotton DLC?

**Comment by Tensuko** [comment]
That does not work.

**Comment by dragon1220** [comment]
Heya, with the bale wrapper function now included, how does that function exactly? do you just position it on the field and start it or does it require the course used to bale as well? if you could do a video like you did with the collection mode that would be great. thanks for this mode though, it a great enhancement

**Comment by Tensuko** [comment]
Smal Course is needed to start the driver, but you can just stay on field and press record course, stop record and then just start it.

**Comment by dragon1220** [comment]
Oh thats awesome... so like three or 4 way points is enough? many thanks

**Comment by Tensuko** [comment]
not even that, start stop and you are ready, just try it out.

**Comment by Gariot** [comment]
> 
> 
> That does not work.

Oh, okay. Thats sad. maybe in the future? :) 

And one thing - the pathfinding is sometimes a little bit weird. When turning, the CP driver always finds the nearest tree to get stuck on. Or when driving over the field to start the unload route, he definetely will find a bale to kick around or get stuck on.


But all in all already pretty amazing new mode, thank you!

**Comment by pvaiko** [comment]
> When turning, the CP driver always finds the nearest tree to get stuck on. Or when driving over the field to start the unload route, he definetely will find a bale to kick around or get stuck on.

If that's really the case we'd definitely like to see a log with channels 7 and 11.

**Comment by AUZ001** [comment]
very innovative idea, but the path finding to new bales can be extremeley taxing on the game (FPS drops to 4fps) for up to 20 secs making the game unusuable and thats just to find one bale... we all dont have 2 acre fields with 15 bales, I work with 100+ acre fields with 250+ bales..

Instead of searching for the bales, wouldnt it make more sence to have the bale collector follow the hay baler's CP course with an offset of 2m and collect the bales that way?

This is all I had to do with my truck and trailer before you disabled its function without reason ... thanks by the way :(

Anyways, great function, not very usuable

**Comment by pvaiko** [comment]
>very innovative idea, but the path finding to new bales can be extremeley taxing on the game (FPS drops to 4fps) for up to 20 secs making the game unusuable and thats just to find one bale... we all dont have 2 acre fields with 15 bales, I work with 100+ acre fields with 250+ bales..

The pathfinding should not take 20 seconds, if that's what you see then there is an issue, see above, log file with channels 7 and 11. For the pathfinder it really does not matter how big the field is, what matters is how far the next bale is and what obstacles are around the vehicle and the target. In 99 percent of the cases the pathfinder on an empty fields (with only bales on it) should be done in a few milliseconds.

I was not aware of your other issue (#6912) will take a look at it.

**Comment by Gariot** [comment]
> 
> 
> > When turning, the CP driver always finds the nearest tree to get stuck on. Or when driving over the field to start the unload route, he definetely will find a bale to kick around or get stuck on.
> 
> If that's really the case we'd definitely like to see a log with channels 7 and 11.

Pathfinder is not literally finding the nearest tree, it just feels like it sometimes ;) In summary i just wanted to say that the pathfinder needs some love - especially with collision detecting.

**Comment by pvaiko** [comment]
I got that it is not literally doing it, and we all love our pathfinder but again, it should avoid trees and if it does not do it, that's an issue which, in turn, we can only fix if people post their logs...

**Comment by dete96** [comment]
Really? I don't know how many trees I had to cut, just to free a vehicle that drove directly into it with pathfinder. For me it's not a big problem, but if pathfinder is intended to avoid trees, then this doesn't work sometimes, especially on headlands. I will try to post a video or something next time it happens. 
By the way, I love pathfinder too ;-)

**Comment by Gariot** [comment]
I dont do bales that often and i cut all trees near my fiels, just because i know they are in the way anyway. But if i do them again i try to run it with logs and hope he will find one of the trees i left :D

Till then - stay healthy everyone

**Comment by pvaiko** [comment]
@dete96 No video. Log with debug channel 11 and the channel for the corresponding mode.

**Comment by AUZ001** [comment]
> The pathfinding should not take 20 seconds, if that's what you see then there is an issue, see above, log file with channels 7 and 11. For the pathfinder it really does not matter how big the field is, what matters is how far the next bale is and what obstacles are around the vehicle and the target. In 99 percent of the cases the pathfinder on an empty fields (with only bales on it) should be done in a few milliseconds.
> 
> I was not aware of your other issue ( [# 6912](https://github.com/Courseplay/courseplay/issues/6912) ) will take a look at it.

Interesting, thanks, I will set up a field and send through the log with 7 and 11.

Thanks for taking a look at the other thread I posted.

**Comment by Tensuko** [comment]
> but if pathfinder is intended to avoid trees, then this doesn't work sometimes, especially on headlands

Driving on Headland is not driving with pathfinder!
If the Field is to close to a Tree, it will get stuck there.

**Comment by Lars-LS17** [comment]
Hallo Zusammen,

ich habe heute den ersten Test gemacht, mit den neuen Modus. 
Das Ballen Sammeln auf den Feld läuft nahezu perfekt. Super Arbeit dafür!!

Ich nutze dieses Sammeln nur, um die Ballen am "Feldrand" abzustellen und dann mit einem Auflieger wegzufahren. 
Wenn ich die Ballen in Reihe ablade, dann klappt das die ersten ungefähr 5x Perfekt. Danach will der immer im Kreiß fahren. 
Wie auf den Foto zusehen, will er Rechts rum ein Kreis drehen.
![fsScreen_2021_03_20_16_01_57](https://user-images.githubusercontent.com/31773176/111874457-a9647e80-8995-11eb-9674-1985b222bd3b.png)

**Comment by pvaiko** [comment]
Ja, momentan funktioniert es nur wenn der Traktor nicht weiter als 50 m vom Abladepunkt ist.

**Comment by Lars-LS17** [comment]
Ah okay. 
Ist aber geplant, dass es bald mehr ist? Das wäre für mich ein Super Erweiterung Feature. 
Ansonsten kann ich nur loben. Der Modus funktioniert wirklich sehr gut und er findet richtig gut alle Ballen auf dem Feld.

**Comment by pvaiko** [comment]
Ja, wollte ich schon ändern, aber es ist ein wenig komplizierter weil wir auch auf die Richtungswechsel aufpassen müssen, aber irgendwann kommt es schon...

**Comment by rellek82** [comment]
Ich finde den neuen Modus auch super. Mit den Ballensammelwagen aus dem orginal Spiel funktioniert es auch, nur habe ich Probleme mit den Sammelwagen aus dem Anderson-DLC. Diese sammeln die Balken sauber auf dem Feld auf. Leider kippen diese ja nicht nach hinten ab, sondern schieben die Ballen nach hinten vom Anhänger. Ist dieses Problem bekannt, oder gibt es da schon eine Lösung dazu?

**Comment by Tensuko** [comment]
Das 'Problem' ist bekannt. Die funktionieren halt anders und wir müssten das verhalten für die Sammelwagen eben anpassen.
Das gehen sollte ist, mit den Sammelwagen in ein Ballenlager (Trigger) abladen.

**Comment by iljarogoff** [comment]
Toller Modus, funktioniert super, nur die Anderson-Rundballensammelwagen sind schwierig. Durch das nach-hinten-Wegschieben der Ballen schiebt es gleichzeitig das ganze Gespann nach vorne und irgendwann verlässt man dadurch den Trigger. Der Traktor müsste irgendwie auf der Bremse bleiben, damit man Position hält

**Comment by vitalii2011** [comment]
Great mode! Probably the only one where I'm faster and more efficient than Courseplay. ) 
It works for me even without: "You still need an unload course ...", but only with AutoDrive points.

**Comment by andreasthu** [comment]
Hallo CP-Team
seit der V 60300053 lädt der Ursus Rundballensammler nicht mehr am Abladepunkt Scheune ( Map Erlengrat - alpine dlc) automatisch ab.
selbst wenn ich dort einen Abladepunkt ODER Haltepunkt setze.
mit v60300052 ging es super
lg
andreas

**Comment by andreasthu** [comment]
zu meinem post darüber:
habe gerade mit der v6.03.0058 Ballen abgeliefert, 
funktioniert wieder super.
lg
andreas

**Comment by Thorn177** [comment]
Used this mode for the first time today.  Mission was to mow, bale, wrap and transport on a fairly large field.  As usual, the programming to solve all the various problems I observed while it was at work was to your normal high standard.  

I do however have a question.  Why did you implement it to go searching for the next bale in the field, rather than along the route the baler took?  Doing this would eliminate the pathfinding needing to solve a more complicated problem as often.  

Bales would mostly be met along the short edge (this would reduce the number of times "wrapping" would bunch up wrapped and unwrapped bales when meeting long edge gets pushed till it eventually gets picked up).  It would mostly be a straight path to the next bale, except where the baler chucks it out sideways (from what I observed, it can clearly handle that well).  Being a straighter path would mostly eliminate the "ran over the previous bale due to a sharp turn" problem. 

It might also allow you to start collecting silage bales while still wrapping grass bales because the bales are still reasonably orderly, rather than the interesting scatter pattern where areas got done, rather than straight lines.  Might have the benefit of less bales for the wrapper to "look" at when picking next bale.

**Comment by pvaiko** [comment]
> I do however have a question. Why did you implement it to go searching for the next bale in the field, rather than along the route the baler took? Doing this would eliminate the pathfinding needing to solve a more complicated problem as often.

For that, why don't you just load the baler course and run your bale loader/wrapper in Mode 6? This worked before the new bale collector mode already. The purpose of this new mode is to more efficiently collect bales when there aren't so many so driving the baler course would result in a lot of overhead.

**Comment by pvaiko** [comment]
Well, that's a bug then, would you mind opening an issue for it?

**Comment by Thorn177** [comment]
Okay.  Will check if it's just the wrapper, or collector as well.  Can manually set tool offset to get it working mode 6

**Comment by Tensuko** [comment]
Still works like a charm:
![fsScreen_2021_05_09_10_38_00](https://user-images.githubusercontent.com/27344744/117565711-fa017980-b0b2-11eb-8de0-8a7b3c2f5303.png)

Most tools get their offset already set when attached and running with it (also with auto calculate button, wich I did here after try of manual set).
![fsScreen_2021_05_09_10_38_05](https://user-images.githubusercontent.com/27344744/117565690-d807f700-b0b2-11eb-9463-00bd1aabe3aa.png)

**Comment by Thorn177** [comment]
Done a bit of experimenting to get the problem to occur again. If you use (not just switch into, then out of) mode 7, then switch to mode 6, the automatic tool offset no longer activates.  Disconnecting the tool, and reattaching will not activate the automatic tool offset.  Attaching to a different type of tool, then back does activate it again. (it works on the new tool and the original).  I have not checked the behavior for the exact same type of tool but two different units of.

**Comment by Rumspringa90** [comment]
Hey,
bei mir funktioniert komischerweise das Ballen wickeln nicht mehr. Habe mit CP und der Claas DLC Quaderballenpresse Grasballen gepresst und wollte dann mit CP Wickeln lassen. Aber er findet keine Ballen auf dem Feld.

Hier die [log.txt](https://github.com/Courseplay/courseplay/files/6457483/log.txt) mit dbg ch 7

**Comment by Tensuko** [comment]
Ich lasse auch gerade eine Mission laufen, sieht sogar nach dem gleichen Wickler mit fast dem gleichen Traktor aus :)

![fsScreen_2021_05_11_11_38_24](https://user-images.githubusercontent.com/27344744/117794382-7af47880-b24d-11eb-960d-608483d0c1ee.png)

**Comment by Rumspringa90** [comment]
auch mit der Claas Quadrant 5300 FC gepresst worden?

**Comment by Tensuko** [comment]
Nein, mit der Kuhn Vanilla Presse.
Aber eigentlich sollten da die gleichen Ballentypen rauskommen, oder hatte GIANTS bei der Claas Presse was gemacht ?

Kurze zwischenfrage: Hast du in ...\My Games\FarmingSimulator2019\modsSettings\Courseplay eine eigene VehicleConfigurations.xml mit einträgen angelegt ? Frage nur, fals sich da was beist.

**Comment by Rumspringa90** [comment]
Ich habe den fehler scheinbar gefunden, ich habe wohl das letzte mal den Feldrandkurs manuell gesetzt und anstatt unter 95 als feld 2 gespeichert. Wenn ich ihn jetzt Feld 2 vorgebe findet er die Ballen auf dem Feld 95. 

Kann man das Feld 2 irgendwie zurücksetzen?

**Comment by Rumspringa90** [comment]
Hab in der Datei einfach die Feldnummer geändert. Funktioniert jetzt wieder einwandfrei. Danke dir :)

**Comment by Thorn177** [comment]
Entweder rauslöschen, oder die Felder noch mal neu berechnen und
entsprechend richtig abspeichern.
Either delete them or recalculate the fields and save them correctly.
They are old files associated with issue #6340, which has since been
closed.  Is it okay to delete them?RegardsThorn

----- Original Message -----

**Comment by P4sc4lBr** [comment]
Hallo

Ich probiere auch gerade den Modus 7 (Ballen wickeln und aufsammeln) aus. Das mit dem Aufsammeln bekomme ich ja hin jedoch habe ich beim wickeln folgendes Problem:
Ich habe die Maschine "Kuhn SW4014" stelle mich mit der auf das Feld, wähle den Modus 7 stelle das richtige Feld ein, erstelle einen kleinen Kurs mit 3 Wegpunkten auf den Feld und starte dann den Abfahrer. Ingame bekomme ich die Meldung 
"(#0) hat die Aufgabe erledigt",
im Server log bekomme ich folgende Meldungen 
"2021-05-19 18:45 :21 [info lp3555] 1050 (#1): No bales found, scan the field once more before leaving for the unload course.
2021-05-19 18:45 :21 [info lp3555] 1050 (#1): There really are no more bales on the field"
Es liegen Grasballen auf dem Feld und auch wenn ich neue presse ändert sich nichts. 

Ich bedanke mich jetzt schon mal für die Hilfe

**Comment by Tensuko** [comment]
Missions Feld ? Feld ausgewählt ?

**Comment by Tensuko** [comment]
Warst du die ganze Zeit auf dem Server ?
Also von Mission annehmen bis hin zum jetzigen Problem ?
Ansonsten mach mal bitte ein Issue auf und poste ein logfile mit debugchannel 7 und 11 active wenn du den Fahrer startest.

**Comment by P4sc4lBr** [comment]
Nein der Server hat dazwischen einmal neugestartet
Kann dass das Problem sein?

**Comment by Tensuko** [comment]
Ja, weil die Missionsfelder nicht neu synchronisiert werden, wenn man erneut connected.
Das ist ein bekannter Fehler.

**Comment by P4sc4lBr** [comment]
okay kenne mich aus danke für die Info

**Comment by Nad42** [comment]
Firstly, this mode is pretty damn good.. I just have two comments from my experience (I'm not sure if anyone has already highlighted these in German):
1. The bale searching sometimes freezes my whole game for a good minute or 2, it seems like however you are searching is very processor heavy.
2. I'm not sure if its a bug but I cannot adjust tool offset when in this mode.. the bale wrapper is not at the correct offset so it ends up pushing bales out of the field all the time.

Otherwise top job, its an ace addition!
