### ISSUE TITLE
Gras Häckseln

### ISSUE THREAD

**Issue by newtec9** [Courseplay/courseplay#6864]
Moin ich habe das Problem beim Gras Häckseln mit Coursplay das die Abfahrer immer hinter dem Häcksler fahren wie kann ich das umstellen das die neben den Häcksler fahren ?

**Comment by Tensuko** [comment]
Gar nicht.
Das liegt daran, dass gemähtes oder gehäckseltes Gras als Frucht zählt.
 #5470
