### ISSUE TITLE
Mode 9 showel,stuck in wall.

### ISSUE THREAD

**Issue by Albatrozs112** [Courseplay/courseplay#6867]
![fsScreen_2021_02_20_16_30_44](https://user-images.githubusercontent.com/79331061/108599290-ffdf9c80-7398-11eb-9314-f7fcba9e1afc.png)
All time the showel stuck in the bunkur walls.

There is no difference between Mod silos or orginal.

Is it passible to change work place?

[log.txt](https://github.com/Courseplay/courseplay/files/6015189/log.txt)

**Comment by 60erjonny** [comment]
Increase the setting at Working width once...

**Comment by Tensuko** [comment]
Work width is the key.
