### ISSUE TITLE
MP issue with v6.03.00043: Failed to create new object with class id 34001 in initial object array

### ISSUE THREAD

**Issue by mricher-git** [Courseplay/courseplay#6871]
Just upgraded to v6.03.00043 and clients cannot connect to multiplayer. Downgraded to v42 and the issue went away. I received this portion of the log from one of the clients:

[message.txt](https://github.com/Courseplay/courseplay/files/6016775/message.txt)

2021-02-20 13:57 Error: Failed to create new object with class id 34001 in initial object array
Start never appears for client and syncing with client just blips

**Comment by Tensuko** [comment]
full logfile

**Comment by mricher-git** [comment]
Here it is:
[message (1).txt](https://github.com/Courseplay/courseplay/files/6017989/message.1.txt)

**Comment by jspring0811** [comment]
We have also reverted to CP v41 because clients get stuck at Loading 29%.   I did not see any message with "class id 34001" in my log but I assume these client Loading issues may be related.   Interestingly as a side note, I was able to connect once by myself on the newest v44 with bale collecting.  No one else was able to join after me (they were stuck with Loading 29%).   Then when I clicked on the CP bale collecting icon my client froze immediately.

I'll wait to see if this #6871 here also fixes my connection issues.

**Comment by Tensuko** [comment]
>  Then when I clicked on the CP bale collecting icon my client froze immediately.

When this happens, logfile! Server and Client.

**Comment by Nicknamekiller** [comment]
Tensuko ich habe genau das selbe problem ab v6.03.00043 . 42 läuft noch aber bei v 43 lädt es nur bis 29% und dann ist ende im gelände. Mir wird der gleiche fehler wie dem kollegen oben angezeigt. 
Irgendwas stimmt nicht.

**Comment by Tensuko** [comment]
Könnt ihr bitte die Bilder hier direkt hoch laden ? Einfach mit der Maus hier rein ziehen, ich will nicht immer auf dubiosen Bilder Uploadportalen landen, danke.

Und dein Error kommt doch ganz klar von GlobalCompany!

**Comment by Nicknamekiller** [comment]
Tensuko 
Das er von GP kommt sehe ich aber
der error kommt erst ab CP version 43. Davor kam er noch nie. Und wir haben schon seit über einem jahr cp drauf. 
Also hat eure neuste version damit auch etwas zutun!

Ihr gebt immer anderen Mods die schuld kann das sein?
Langsam verstehe ich wieso viele modder ihr zeug nicht cp fähig machen. So oft wie ihr an CP rumbastelt ist klar das die Mods dann probleme machen weil die modder nicht jede woche dran rumbasteln wollen wie ihr. 

Komischerweise hat Autodrive keinerlei probleme mit fahrzeugen und anderen Mods. CP hat es so häufig...
Ihr solltet euch mal den Mods anpassen und nicht die Mods an CP. 

zudem zeigt der server 10 fehler von CP an :
Unknown file type '__Attributions.md'
Unknown file type 'course-generator/README.md'
Unknown file type 'course-generator/LICENSE'
Unknown file type 'course-generator/.editorconfig'
Unknown file type 'course-generator/README'
Unknown file type 'LICENSE'
Unknown file type 'readme.md'
Unknown file type 'reloadAIDriver.bat'
Unknown file type 'reload.bat'
File count per store item too high. 174 found (max. 128)

wie wäre es mal diese zu beheben statt immer neue sachen hinzufügen die probleme machen???

CP ist wirklich gut aber kann viele probleme machen gerade im MP.

**Comment by mricher-git** [comment]
Global Company and other mods are throwing errors because CP is messing up the network sync, after which player and many other objects don't exist for the client.

**Comment by pvaiko** [comment]
@mricher-git I understand your frustration, but that's why have these the big bold letters here: https://github.com/Courseplay/courseplay#note-that-the-current-version-has-limited-multiplayer-support.

One of the issues is that I personally have no interest in multiplayer, so you'll have to wait until the other devs have time to look at this. Until then just keep using 42. 

Regarding the problems with mods and AD, it has two reasons:
1. Field work modes depend a lot more on the exact mod configuration, specializations, AI markers, work areas, etc. 
2. Code quality of AD is much better than CP, some of CP's code base is from 2012 and in retrospect, it would have probably been better to throw the whole thing out and rewrite instead of trying to incrementally refactor things.

**Comment by Nicknamekiller** [comment]
@ pvaiko
better new write. Its the best. 

CP have many problems in MP and with other Mods. AD can ignore faulty mods. Thats good but CP make many problems with 
faulty mods

**Comment by mricher-git** [comment]
@pvaiko I'm not frustrated mate, that would be Nicknamekiller by the looks of things ;)
I'm just providing a friendly heads up and a follow up comment to address the comment that other mods were throwing errors in the log.

**Comment by andremeyer123** [comment]
die 10 fehler sind sowas von unwichtig
wir spielen die hopfach mit genügend gc objekten und haben die fehler nicht ad und cp vorhanden und weiter 89 mods

**Comment by pvaiko** [comment]
> @pvaiko I'm not frustrated mate, that would be Nicknamekiller by the looks of things ;)

Oops, sorry, my bad.

**Comment by Nicknamekiller** [comment]
@andremeyer123 
auch wenn die fehler keine probleme machen könnte man sie trotzdem mal beheben :)
darf man fragen welche CP und GP version ihr draufhabt?

**Comment by andremeyer123** [comment]
[LSMC - GlobalCompany] - Loading Version: 1.7.1.0 (01.08.2020) 
Courseplay: initialized 94/94 files (v6.03.00044)
bei der 43 hatten wir den fehler im mp auch nicht

**Comment by andremeyer123** [comment]
Das cp Team hat in den letzten 4 Monaten sehr viel für MP gemacht damit es im MP funktioniert, dann vorzuwerfen sie sollen sich an den Mods von anderen anpassen finde ich nicht gut. Cp ändert ja nichts an Gebäuden usw. nur am Helferlein :D
Testet mal ein neues Savegame ob es dann geht vielleicht ist irgend ein Eintrag im alten Savgame nicht in Ordnung.
wir haben mal spiel gestartet ohne cp abgespeichert neugeladen mit cp vieleicht auch mal testen .

**Comment by jason0611** [comment]
Die 10 aufgeführten Fehler kommen nicht aus dem Serverlog, sondern werden auf der Webseite angezeigt. Hierbei handelt es sich um "Fehler" in Form von nicht erwarteten Dateien im ZIP-Archiv, etc. Alles ohne Auswirkungen auf das Spiel.

Das Serverlog erhaltet Ihr über Einstellungen/Log-Dateien, aber auch nur, wenn Ihr bei den Servereinstellungen auf Providerseite das Logging überhaupt aktiviert habt. Genau dieses ist für eine Fehlersuche unerlässlich.

**Comment by Tensuko** [comment]
> Ihr gebt immer anderen Mods die schuld kann das sein?
> Langsam verstehe ich wieso viele modder ihr zeug nicht cp fähig machen. So oft wie ihr an CP rumbastelt ist klar das die Mods dann probleme machen weil die modder nicht jede woche dran rumbasteln wollen wie ihr.

Achso, wenn wir sagen, repariert eure Mods, dann bauen sie die extra 'schlecht' damit sie noch schlechter mit CP laufen ?
Mir fehlt da die Logik. Wir kommunizieren mit Moddern (ich zumindestens) um einiges zum laufen zu bringen. Das Problem ist das viel getrickst wird und sich nicht an GIANTS Standart gehalten wird.
Wir haben bereits viele Möglichkeiten auf Mods ein zu gehen und das tun wir auch, aber zaubern können wir auch nur bedingt...



> @ pvaiko
> better new write. Its the best.

Ok next FS Version, no CP for you guys, untill we are done with rewriting ;)

**Comment by Nicknamekiller** [comment]
@andremeyer123 
die GP version hab ich auch drauf aber sobald ich die cp version 43 drauf mache gibts errors in der console von GP.. und spiel lädt nur bis 29%. Andere savegames hab ich auch schon getestet das problem bleibt aber.
An gebäude geht es nicht aber in alle fahrzeuge die drauf sind. Und wenn man viele drauf hat gibts gerne mal probleme :( AD ignoriert diese Probleme bei fahrzeugen die fehler haben einfach und man kann sie problemlos nutzen. So sollte es auch bei CP sein :) Er soll die fehlerhaften Mods einfach ignorieren oder villeicht könnte man auch eine neue funktion hinzufügen das CP fahrzeuge/MODs die probleme mit CP haben erkennt und diese dann von CP ausschließt zB kann man dann in diesen fahrzeugen kein CP menü öffnen . Da lässt sich bestimmt noch was dran machen :) 
Natürlich haben die Herren viel gemacht ist ja auch top. 
Man sieht ja wie gut CP im SP läuft :) aber im MP ist es leider noch nicht so...

@Tensuko 
beruihg dich ;D Davon war nie die rede. 
Es gibt halt viele fahrzeuge/mods die probleme haben mit CP. Ich hab jetzt scho 7 drescher durch und keiner kam so wirklich mit CP klar xD wobei ich dazu sagen muss alle waren XL drescher aber drescher ist drescher.. 
Ich denke das jeder cp nutzer sehr dankbar ist für eure arbeite (ich eingeschlossen! :D ) 
Aber hier und da harperts halt. Vorallem bei Mods,deren modder nicht mehr modden und somit nichts mehr dran ändern. Oder Generell Modder die ihr zeug nicht CP fähig machen und es nirgends in die info schreiben.
AD juckt es nicht ob das fahrzeug ihn mag oder nicht. Klappt trotzdem einwandfrei. CP wirft hingegen fehler raus was sehr schade ist :( wie ich etwas weiter oben schon schrieb -> 
Könnt ihr es nicht so machen das CP  die fehlerhaften Mods einfach ignoriert und/oder villeicht könnte man auch eine neue funktion hinzufügen das CP fahrzeuge/MODs die probleme mit CP haben automatisch erkennt und diese dann von CP ausschließt zB kann man dann in diesen fahrzeugen kein CP menü mehr öffnen . Da lässt sich bestimmt noch was dran machen :)

**Comment by Tensuko** [comment]
@Nicknamekiller 


> Es gibt halt viele fahrzeuge/mods die probleme haben mit CP

Richtig, und es gäbe noch mehr, wenn wir nicht vorher checks machen würden, dann gäbes es auch kaputte saves.
Es ist nicht so als ob wir hier gar nichts machen für mods, aber einige Modder müssen sich eben mal an die eigene Nase fassen und sich einfach mal an den GIANTS standart halten, dann gibt es sowas wie kompatiblitätsprobleme erst gar nicht.



> drescher ist drescher

Optisch vlt, aber was drin ist (in dem fall in der .XML) ist das was zählt...



> Aber hier und da harperts halt. Vorallem bei Mods,deren modder nicht mehr modden und somit nichts mehr dran ändern. Oder Generell Modder die ihr zeug nicht CP fähig machen und es nirgends in die info schreiben.

Das kann dann aber nicht unser Problem sein, gerade dann, wenn wir, nachdem wir nun schon arbeit in 'Code Cleanup' reingesteckt haben, wieder alles mögliche tun müssen, tricksen und umpfuschen, nur damit irgend so eine Mods wieder funktioniert. Das wiederspricht dem, was wir gerade tun und das ist CP sauber zu bekommen und stabliere und das kann man nur erreichen mit sauberen Code.



> AD juckt es nicht ob das fahrzeug ihn mag oder nicht. Klappt trotzdem einwandfrei.

Hat @pvaiko schon geschrieben, alles was AD macht, ist fahren, laden, leeren.
AD macht keine Wendemanöver, klappt Geräte auf und zu, weis wann es voll wird usw usw, das kann man nicht vergleichen.
Ein Fahrzeug einfach fahren zu lassen, ist relativ einfach im vergleich zu anderen Aktionen, die man mit CP machen kann und auch dafür haben wir eine Basis geschaffen, Mods einfacher kompatibel zu machen (ein .XML file in dem man Geräte konfigurieren kann, auch als User ohne sie extra ins CP archiv zu schreiben, siehe https://github.com/Courseplay/courseplay/releases/tag/6.03.00027).



> du kennst nicht zufällig einen XL drescher

Was ist ein XL Drescher für dich ? Von Unrealistischen Mods halte ich mal gar nichts...

**Comment by Nicknamekiller** [comment]
@Tensuko 
Wäre es denn nicht möglich und auch einfacher es so zu machen das CP fehlerhafte Mods bzw Mods die mit CP nicht klar kommen automatisch bemerkt und diese dann automatisch ausschließt? zB Kann man dann im Fahrzeug das CP menü nicht mehr öffnen und CP nutzen + villeicht noch eine consolen benachrichtigung das der und der MOD nicht CP fähig ist und nicht mit CP helfern genutzt werden kann. So weiß jeder direkt welche Mods nicht CP fähig sind + man kann die MODS trotzdem nutzen aber dann kann man halt kein CP helfer rein machen + fehler/callstacks die in kombination mit CP und dem mod stehen würden ignoriert werden,da CP nicht in diese fahrzeuge/geräte reingeht bzw die fehlerhaften Mods blockiert. 

Villeicht auch noch eine MOD liste mit MODs die im MP und mit CP einwandfrei funktionieren,irgendwo machen. Das würde bestimmt helfen. (Villeicht gibts sie ja auch schon ich weiß es nich ;D )  

zum thema mods kompatibel machen:
Das ist nichts für anfänger da muss man scho ein wenig ahnung haben und die meisten Spieler wollen einfach nur das Spiel spielen und nicht an Mods rum basteln .

XL Drescher: einfach einen mit ladevolumen 50.000 bis max. 100.000L . Wir spielen auf einer 4fach map da is mehr füllvolumen hilfreich :) breite vom schneidewerk ist egal kann auch einer sein wo keins dabei is

mfg

**Comment by Tensuko** [comment]
Sicher kann man diverse Checks noch einbauen und die dann ausschließen, aber ich kann dir jetzt schon sagen, dass wir dadurch noch mehr Issues bekommen mit 'kann kein CP Menü öffnen' (egal ob es in der log steht oder nicht).

Fahrzeuge erst selber auswählen welche mit CP laufen sollen, das geht gar nicht, denn der größte Teil läuft ja mit CP und es würden nicht nur Fahrzeuge, sondern diverse Geräte mit dabei sein, viel zu viel Aufwand was dem 'Spieler wollen einfach nur spielen' wiederspricht.

Mods kompatibel machen, das sollen auch nicht die Spieler, das sollten dann wie gesagt die Modder tun, wenn sie es wollen. Wenn sie das nicht wollen, warum sollen wir unseren Code ständig anpassen, weil ein Modder das so macht und der nächste macht es wieder anderes, da fehlt auch uns vollkommen das Verständnis für, aber dann ist das eben so!

Kein User hat das RECHT auf eine Mod oder das Recht auf vollständige kompatiblität. Das ist übrigens die Einstellung von einigen Usern, die andere Modder dazu gebracht haben komplett auf zu hören, oder nur noch Privat Mods zu verteilen. Dieses ständige fordern und 'ich will das aber so' wird irgendwann Lästig, dennoch sind wir hier, hören uns eure Probleme an und versuchen euch zu helfen es zu lösen und manchmal ist eben die Lösung -> Mod Problem.

Wir können vieles für Mods tun und haben auch schon, wie ich bereits sagte, aber alles können und werden wir nicht machen, dafür haben wir weder die Zeit (und jetzt bin ich mal ganz ehrlich) noch die Lust zu, die Fehler andere auszubügeln (Fehler im Sinne von kein GIANTS Standart).

Ich schaue da einfach mal in Richtung Kastor, Vertex Design, BlackSheepModding, CreativeMesh, LSMC die alle super Mods raus hauen und die auch laufen, von den ganzen ScriptMods ganz zu schweigen und auch da haben wir bisher gute Zusammenarbeit gehabt, ManureSystem ging auch nicht von Anfang an...

In deinem Fall ist es irgend ein Mod, der in Verbindung mit GC einen Error raus haut, ohne Error Message, die auf CP verweist, können wir da auch nichts machen, wo sollen wir anfangen zu suchen?

**Comment by Nicknamekiller** [comment]
@Tensuko 
oh ne dann lasst das lieber.. wenn zusätzliche fehler dazu kommen kann man gut drauf verzichten.
Das es viel arbeit wäre glaub ich dir ;D 

Dann stellt doch wenigstens mal eine liste zusammen mit mods / moddern deren Mods man im MP und mit CP einwandfrei nutzen kann. Das wäre sehr hilfreich

von CreativeMesh hatte ich auch schon einen mod der nicht mit cp klar kam. Ist aber schon ein weilchen her. Die anderen Modder muss ich mir mal anschauen.

mir wird auch der error den der kollege ganz oben hat ( Error: Failed to create new object with class id 34001 in initial object array) angezeigt. Das ist der erste error der kommt,er ist nur nicht auf dem screen zu sehen da sich die errors von GC zichfach dupliziert haben. Das komische mit dem GC error ist er kam vor v...43 noch nie. Hab ja jetzt wieder 42 drauf und er ist noch nicht aufgetaucht. Generell ist es der erste GC error in der console denn ich sehe. Haben auch nicht viele sachen von GC drauf..

wir bleiben erstmal bei v....42 mit der läuft es ja. 

kannst du denn einen drescher empfehlen?

**Comment by Tensuko** [comment]
Claas Lexion 8600 und das 3 mal im Convoy mit einem Mode3 Abfahrer :)

Nein eine Liste werde ich nicht zusammen stellen, das meiste wie gesagt funkioniert!
Man kann eher mal eine Liste machen, in dem User reporten, was Probleme macht und nicht behebbar ist und damit meine ich jetzt nicht GC, weil wir NIE gesagt haben, dass wir uns das nicht angucken werden, aber so lange wir keinen Error Pfad zu CP bekommen, wird es schwer werden zu sehen was da falsch ist.

**Comment by Nicknamekiller** [comment]
@Tensuko 

3x den Claas Lexion mit Abfahrer ist MP nicht so der bringer. Wenn Mehrere spieler drauf sind und jeder lässt auf seinen feldern soviele helfer laufen + noch abfahrer laggt es deutlich mehr als wenn man nur 1 drescher pro feld arbeiten lässt. 

Kennst denn einen normalen der um die 17k füllvolumen hat und einwandfrei mit CP klar kommt ?( nicht der aus dem claas pack oder die standart drescher) . Füllvolumen kann ich ja immernoch erhöhen.. 

im SP klappt v...43 & 44 einwandfrei mit exakt den selben MODs... Im MP kommt stattdessen der class id 34001 error und der GC error... 
Ist aber auch egal bleiben bei v...42 und gud.. Ballen aufsammeln machen wir sowieso selbst.

**Comment by andremeyer123** [comment]
@Nicknamekiller 
wir benutzen diesen im mp bis 100000 liter auswählbar für grosse karten

**Comment by Nicknamekiller** [comment]
@andremeyer123 
danke dir :D

**Comment by Tensuko** [comment]
I did some cleanup to keep the original Issue clean.

**Comment by Grasigruen** [comment]
Hi,
I try any Version on MP. But it doesn't work. Every Version got a problem with "Maize Plus". Version 42 runs stabel and we are very happy but we miss the new functions. :-) 

Here is the log File from me. 
[05.03.2021log.txt](https://github.com/Courseplay/courseplay/files/6090996/05.03.2021log.txt)

**Comment by jason0611** [comment]
This is a known issue of MaizePlus. On their Discord is an Update available: https://discord.com/channels/699589863996915713/699590403111911454/814114376512176179

**Comment by Tensuko** [comment]
Can you pls try 6.03.00049 or higher and report ?

**Comment by Tensuko** [comment]
And yes, Maize Plus got an Beta Update for MP (wich isn't related to CP)

**Comment by Grasigruen** [comment]
Hi,
the test with 6.03.00049 was without success.
The test was without the MaizePluse Beta update.

Here is the log file:
[log.txt](https://github.com/Courseplay/courseplay/files/6095164/log.txt)

Next step is the try out with the MaizePlus Update from Discord.

**Comment by pvaiko** [comment]
So it is still not clear if 49 works or not, as long as we have a million errors from MaizePlus like in the log above. Still waiting for a conclusive test.

**Comment by andremeyer123** [comment]
delete: error mods 
inputbindings delete  
only let zip files in the mods folder

**Comment by Tensuko** [comment]
And use MaizePlus Beta to prevent Errors!

**Comment by mricher-git** [comment]
I tried .50 today and it is back to working in MP

**Comment by jspring0811** [comment]
Yes, we have been using .050 for several days with no issues connecting.

There is still one error during connection, but it does not prevent the user from connecting.  These messages appear just after the Synchronizing message and before the Synchronizing x% messages.   I have no idea if these are related to CP at all, and they don't appear to be causing any issue:

![image](https://user-images.githubusercontent.com/48362683/111344871-266cbc80-8653-11eb-8fef-b02dc651e7f1.png)

-- Thanks, I think the original issue can be marked as resolved in .050.

**Comment by mricher-git** [comment]
Sadly it just failed to connect again. My guess is that it's a race condition, and there is just less of a chance of it appearing. In fact, my friend shows all courses as temporary courses unless I activate a driver, and on my screen its start at unload, for him it's start at nearest but behaving as it shows for me. Also, the cover is on the trailer but they can't see it. It's really messy,

**Comment by mricher-git** [comment]
I upgraded AD to 1.1.0.8 so perhaps the .50 CP and 1108 AD combo have a new issue, both appear in the latest log so not sure.

2021-03-17 00:51 	### CourseplayMultiplayer: writing 201 courses 
2021-03-17 00:51 	### CourseplayMultiplayer: writing 11 folders 
2021-03-17 00:51 	### CourseplayMultiplayer: writing 3 custom fields 
2021-03-17 00:51 Warning (script): 'streamWriteUIntN': Argument 1 has wrong type. Expected: UInt. Actual: Nil 
2021-03-17 00:51   ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (882): expectedType == Value::VoidType || expectedType == Value::ClassType
2021-03-17 00:51 LUA call stack:
2021-03-17 00:51   dataS/scripts/vehicles/specializations/AIVehicle.lua (241) : streamWriteUIntN
2021-03-17 00:51   =D:/Users/Xxx/Documents/My Games/FarmingSimulator2019/mods/FS19_FollowMe/AIVehicle_Override.lua (78) : superFunc
2021-03-17 00:51   dataS/scripts/vehicles/SpecializationUtil.lua (30)
2021-03-17 00:51   dataS/scripts/vehicles/Vehicle.lua (1094) : raiseEvent
2021-03-17 00:51   dataS/scripts/network/Server.lua (608) : writeStream
2021-03-17 00:51   =D:/Users/Mike/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/courseplay_event.lua (160) : Server_sendObjects_old
2021-03-17 00:51   dataS/scripts/FSBaseMission.lua (946) : sendObjects
2021-03-17 00:51   dataS/scripts/utils/Utils.lua (393) : oldFunc
2021-03-17 00:51   dataS/scripts/utils/Utils.lua (393) : oldFunc
2021-03-17 00:51   dataS/scripts/events/BaseMissionFinishedLoadingEvent.lua (38) : onConnectionFinishedLoading
2021-03-17 00:51   dataS/scripts/events/BaseMissionFinishedLoadingEvent.lua (27) : run
2021-03-17 00:51   dataS/scripts/network/Server.lua (440) : readStream
2021-03-17 00:51   dataS/scripts/network/ConnectionManager.lua (28) : func
2021-03-17 00:51 Error: Running LUA method 'packetReceived'.
2021-03-17 00:51 dataS/scripts/vehicles/specializations/events/SetPipeStateEvent.lua(54) : attempt to index field 'object' (a nil value)
2021-03-17 00:51 Error: Running LUA method 'packetReceived'.
2021-03-17 00:51 dataS/scripts/vehicles/specializations/events/SetPipeStateEvent.lua(54)

Downgrading back to 1.1.0.7 with .042CP and giving up for awhile ;)

**Comment by Tensuko** [comment]
My test with Version 50 went well for the 1st 3 ppl, then after I did a 4th reconenct I run into Errors with GC as well.
No idea whats going up... 

That callstack is not complete like that. Always post full logfile pls.

**Comment by Tensuko** [comment]
So what is going on here now ?
Played wtih 00052 on a Server with Mods, tested without and our Testteam also confirms it does work.
Can those who had that Class ID Error pls test the 00052 and see if it still exists ?

**Comment by Tensuko** [comment]
Closed due to inactivity.
I haven't heard anything about this Error happening with Versin 6.03.00052 the last weeks and also play with that Version in MP on my own.
When this Error happens again, reopen with needed information on where it come from.
