### ISSUE TITLE
Leveling bunker tractor gets stuck

### ISSUE THREAD

**Issue by FuturisticMC** [Courseplay/courseplay#6872]
The recent update helped with the problem but when using the leveling or filling up mode the tractor will sometimes start slipping or turn sideways inside the bunker.
![20210220211155_1](https://user-images.githubusercontent.com/46466204/108613529-f10ce000-73c0-11eb-990d-d48c9958cb6a.jpg)
I also suggest in a future update to make the tractor pause its work once its leveled as much as it can

**Comment by Tensuko** [comment]
How does yourcourse look like ?

**Comment by FuturisticMC** [comment]
![20210221100628_1](https://user-images.githubusercontent.com/46466204/108629221-f43db580-742c-11eb-91a1-591707b6f508.jpg)

**Comment by Tensuko** [comment]
Hard to see but I would move the stop point more far away from Bunker. Looks a bit close.

**Comment by FuturisticMC** [comment]
ok I will try that, what do I do about it getting stuck when pushing?

**Comment by Tensuko** [comment]
It should drop out by itself. The move of stoppoint should help with run into wall. Maybe increase the working width a bit.

**Comment by FuturisticMC** [comment]
I just did multiple test runs and it still turned sideways in the bunker

**Comment by Tensuko** [comment]
Can you make a video with debugchannel 10 and 12 active ? (+add the logfile)

**Comment by FuturisticMC** [comment]
https://youtu.be/H_WukcmHFKs
<script src="https://gist.github.com/FuturisticMC/849f72235397c4bcc49e938bcbd7e61d.js"></script>
Do you know what the  Error: addRequiredCropType foliage must match the size of the ground terrain detail. Is about?

**Comment by Tensuko** [comment]
No sry I have no Idea what that message means.

Did you increase your working width ? Doesn't look like that. It is on the last page in the HUD, Guess something like 5,5m is needed here, but you will see the red line that shows the width.

**Comment by Tensuko** [comment]
Oh and maybe your 1st Waypoint shouldn't be so deep inside the Bunker.
This is how the course is designed to be:
![Bunker](https://user-images.githubusercontent.com/27344744/108636024-06e2d980-7483-11eb-867b-c2bb1dc25e58.png)

The 1st WP must be just inside the Bunker, as we check if we have a Bunker at the 1st WP.

**Comment by FuturisticMC** [comment]
yeah it looks like my first waypoint was too far in because its working now

**Comment by Tensuko** [comment]
Ok can we close this Issue then ?
I know its a bit tricky and I want to make Video to every mode but I have limited time too :)

**Comment by FuturisticMC** [comment]
Yeah A video for every mode would be awesome
