### ISSUE TITLE
Problem mit Feldkursen seit der v6.03.00043

### ISSUE THREAD

**Issue by rellek82** [Courseplay/courseplay#6873]
Seit dem Update auf die v6.03.00043 findet der Helfer auf dem Feld den ersten Feldarbeitskurspunkt nicht mehr. Ich muss dann immer manuell bis kurz vor den ersten Feldarbeitskurspunkt fahren und kann dann erst den Helfer starten. In der v6.03.00042 hat das bei mir noch alles funktioniert.
Auch bei der Kombination mit Autodrive habe ich ein neues Problem seit der v6.03.00043. Z.B. wird nach dem Gras einsammeln mit dem Ladewagen und Rückkehr durch AD vom Abladepunkt zum Feld am Feld nicht mehr zu CP übergeben. Statt dessen bleiben beide Scripte aktiv und der Helfer kriecht langsam quer über das Feld. Mit der v6.03.00042 lief das alles problemlos. Ich spiele jetzt erstmal mit der älteren v6.03.00042 und hoffe, dass man das Problem beheben kann.  Ich habe in meinem Spielstand und Modordner zwischendurch nur CP aktualisiert und habe seit dem diese Probleme.  Das ganze passiert mit alten, wie auch mit neu berechneten Feldkursen.
Vielleicht hat noch jemand diese Probleme seit der neusten Version von CP.

**Comment by pvaiko** [comment]
Log mit channel 14
