### ISSUE TITLE
Probleme beim Drescher & Abfahrer (.00043)

### ISSUE THREAD

**Issue by valtramartin** [Courseplay/courseplay#6874]
Der Abfahrer findet kein Pfad zum Drescher abtanken, außerdem fägt ein Drescher nicht wie gewünscht am naheliegensten Wegpunkt an, sondern irgendwo im Feld.
[log.txt](https://github.com/Courseplay/courseplay/files/6017774/log.txt)

**Comment by pvaiko** [comment]
Ein Screenshot mit einer Map wäre hilfreich. Was klar ist, multitool Kurs klappt nicht, wahrscheinlich einfach zu viele zu breite Drescher fuer dasFeld, daher dein "irgendwo im Feld" Problem.

Das mit dem Abfahrer, schwer zu sagen, es sieht so aus als stünde der nicht in der nähe des Feldes, jeder Punkt der Pathfinder probiert hat, hat ein Field Penalty. Also wieder, Screenshot mit Map (F9)

**Comment by valtramartin** [comment]
![Farming Simulator 19 21 02 2021 14_57_11](https://user-images.githubusercontent.com/79406842/108627526-5d85ee80-7456-11eb-9f7e-5b935c417c17.png)
![Farming Simulator 19 21 02 2021 14_57_57](https://user-images.githubusercontent.com/79406842/108627529-5eb71b80-7456-11eb-8a42-13d3c25863a1.png)
![Farming Simulator 19 21 02 2021 14_58_27](https://user-images.githubusercontent.com/79406842/108627533-62e33900-7456-11eb-98d1-0b87d9343981.png)
![Farming Simulator 19 21 02 2021 15_05_56](https://user-images.githubusercontent.com/79406842/108627534-64146600-7456-11eb-9872-df17c6a8a14b.png)

**Comment by 60erjonny** [comment]
Hallo
Auf dem letzten Bild, steht dein Abfahrer aber auf Überführungskurs und nicht auf Abfahrkurs...

**Comment by valtramartin** [comment]
Der Abfahrer war auch nicht eingestellt, das Bild ist nur um zu zeigen, dass der Abfahrer am Feldrand steht, normalerweise läuft der natürlich über Mode 2
