### ISSUE TITLE
Courseplay folders end up disorganised for some users on dedicated server

### ISSUE THREAD

**Issue by rf152** [Courseplay/courseplay#6877]
After playing for a while some users find that the course plays end up in different folders. This only happens for some users. 

This happened this evening. Logs in https://gist.github.com/rf152/e33d7f3c79f63371322aa3a08a087738. Clients 1 and 2 had the issue, client 3 didn't.

**Comment by Tensuko** [comment]
Thats a general problem on MP Server and hard to fix with the current course management.
Similar to #6779
