### ISSUE TITLE
Ausbringen von Mist und/oder Gülle mit CP im Multiplayer mit Precision Farming DLC - Problems spreading manure / liquidmanure on MP with Precision Farming DLC

### ISSUE THREAD

**Issue by altbier1** [Courseplay/courseplay#6878]
Hallo,
 wir haben ein Problem beim Ausbringen von Gülle oder Mist. Wir spielen Multiplayer haben das Precision Farming DLC und Precision Farming Addon auf dem Server. Modus 4 ist aktiv, die Fahrer fahren los, bringen jedoch kein Mist oder Gülle auf dem Feld aus, fahre ich selbst wird Mist oder Gülle Problemlos ausgebracht. Handelt es sich hier um ein Problem/Konflikt  mit Precision Farming DLC

Hi,
we have a problem when we try to spread manure or liquidmanure. We play Multiplayer, use Precision Farming DLC and Precision Farming Addon. Mode 4 is active, the  driver start but they don´t spread manure or liquidmanure, if we drive the vehicles we can spread manure or liquidmanure. May be it is an conflict or an issue with Precision Farming DLC

**Comment by Tensuko** [comment]
Keine Ahnung.
Preci Farming hat im SP kein Konflikt, wüsste nicht wieso es im MP nicht gehen soll.
