### ISSUE TITLE
DEDI SERVER BUG

### ISSUE THREAD

**Issue by CalangoLango** [Courseplay/courseplay#6879]
hello, I'm using it on a dedicated server, before it doesn't solve this problem, but when I put it on the server it sometimes bug the map taking all the information from the map.

**Comment by Tensuko** [comment]
No Idea what you talking about...
logfile ?
More Informations ?
https://github.com/Courseplay/courseplay/wiki

**Comment by CalangoLango** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6022249/log.txt)
At certain times the mod bug, it causes the map information to disappear as sales locations, the number of fields.

**Comment by Tensuko** [comment]
Long ago I have seen such an old CP Version: (Version: 6.02.00078) FS19_Courseplay
https://github.com/Courseplay/courseplay/wiki
https://github.com/Courseplay/courseplay/releases

You got also Callstacks that leads to GIANTS Code and I guess they come from other Mods. (something with tension belt).

Not a CP Issue or better say, way to old CP Version + Other Errors from any other Mod.
