### ISSUE TITLE
Combi mode with forage harvester

### ISSUE THREAD

**Issue by FuturisticMC** [Courseplay/courseplay#6880]
I was using a tractor and a semi to haul silage with combi mode, the problem was in the field when making turns. Sometimes the semi would not turn correctly and it would run into the chopper or it would stop behind it just far away enough the chopper wouldn't detect the trailer. Also the tractor and semi would run into each other and "fight" for the chopper.

**Comment by Tensuko** [comment]
Screenshots and logfile with debugchannel 4, 7, 12 and 14

**Comment by FuturisticMC** [comment]
https://gist.github.com/FuturisticMC/e93af8dd44484f036e14f95d77d66537
![20210222210406_1](https://user-images.githubusercontent.com/46466204/108794461-c43d0200-7553-11eb-8240-f4336a613484.jpg)
![20210222210536_1](https://user-images.githubusercontent.com/46466204/108794465-c56e2f00-7553-11eb-900e-a951a8290dd5.jpg)
![20210222210547_1](https://user-images.githubusercontent.com/46466204/108794468-c69f5c00-7553-11eb-841b-70d9594e2b8f.jpg)
![20210222210602_1](https://user-images.githubusercontent.com/46466204/108794471-c737f280-7553-11eb-98d6-230bcdaccc4a.jpg)
![20210222210653_1](https://user-images.githubusercontent.com/46466204/108794474-c7d08900-7553-11eb-90f1-cf2280441e03.jpg)
![20210222210655_1](https://user-images.githubusercontent.com/46466204/108794478-c901b600-7553-11eb-830c-6d2bb6737dad.jpg)
![20210222210658_1](https://user-images.githubusercontent.com/46466204/108794480-c99a4c80-7553-11eb-84f9-828be1792a4d.jpg)
![20210222210706_1](https://user-images.githubusercontent.com/46466204/108794481-cacb7980-7553-11eb-9f17-baefdb8e55c4.jpg)
![20210222211000_1](https://user-images.githubusercontent.com/46466204/108794485-cb641000-7553-11eb-9540-ab0cd7f50acc.jpg)
![20210222211219_1](https://user-images.githubusercontent.com/46466204/108794488-cbfca680-7553-11eb-98a9-f38f41dbe6ca.jpg)
![20210222211323_1](https://user-images.githubusercontent.com/46466204/108794491-cd2dd380-7553-11eb-807c-2cf147102877.jpg)
![20210222211337_1](https://user-images.githubusercontent.com/46466204/108794495-cdc66a00-7553-11eb-815a-fc20a30517c1.jpg)
![20210222210357_1](https://user-images.githubusercontent.com/46466204/108794497-cdc66a00-7553-11eb-8bbf-530846b4664d.jpg)
![20210222211351_1](https://user-images.githubusercontent.com/46466204/108794505-cef79700-7553-11eb-8aa4-4ad3e6042d5f.jpg)
![20210221113108_1](https://user-images.githubusercontent.com/46466204/108794507-cf902d80-7553-11eb-88b5-bd22a9628359.jpg)
![20210222210207_1](https://user-images.githubusercontent.com/46466204/108794510-d0c15a80-7553-11eb-9804-89b437cb5faa.jpg)
![20210222210216_1](https://user-images.githubusercontent.com/46466204/108794513-d159f100-7553-11eb-92ca-c03c37530320.jpg)

**Comment by Tensuko** [comment]
- One Headland is not enough
- Don't use trucks for unloading
- Start and Stop for Unloadcourse does NOT belong on the field

**Comment by TinyCrocodile** [comment]
What is the turn radius setting of the truck? It seems he tries to make verry narrow turns. Try to increase the turnradius then pathfinder will try to find a different solution. 
Btw it is best, to make a clean harvest of the headland. This helps the pathfinder to find a way to the combine.

**Comment by FuturisticMC** [comment]
When I harvest the field properly I will get better info

**Comment by Tensuko** [comment]
Closing this for now.
As mentioned, more headlands and trucks like that are realy not made for unloading like this...
