### ISSUE TITLE
Attachable head pull type forager harvester

### ISSUE THREAD

**Issue by jobyrns72** [Courseplay/courseplay#6883]
Hello me and a friend have been working getting a pull type forage harvester to work correctly with being recorgnized with combine calling. Since the cutter and pick up is separate we made the lua recognize the full combine specialization. Didn't know if y'all would like to incorporate it or not. Works so far dont yet if it will mess with others yet since we left the calling for pickup and cutter in the fieldworkAIDriver.lua

[SpecializationUtil.hasSpecialization(BaleWrapper, self.specializations) then
				return true
			elseif SpecializationUtil.hasSpecialization(Combine, self.specializations) then
				return true
			elseif SpecializationUtil.hasSpecialization(Pickup, self.specializations) then
				return true
			elseif SpecializationUtil.hasSpecialization(Cutter, self.specializations) then]()

**Comment by Tensuko** [comment]
Where did you do what in what version and what did you try to get working ?

**Comment by jobyrns72** [comment]
Newest version I added a call for the specialization combine to recognized as an ai implement in the fieldworkAIDriver.lua bc I have a pull type harvest that has attachable pick up header and cutter. 

SpecializationUtil.hasSpecialization(BaleLoader, self.specializations) then
				return true
			elseif SpecializationUtil.hasSpecialization(BaleWrapper, self.specializations) then
				return true
			elseif SpecializationUtil.hasSpecialization(Combine, self.specializations) then
				return true
			elseif SpecializationUtil.hasSpecialization(Pickup, self.specializations) then
				return true
			elseif SpecializationUtil.hasSpecialization(Cutter, self.specializations) then


We added the call for combine spec that's in that piece of code and now works

**Comment by pvaiko** [comment]
@jobyrns72 please create a pull request and we can discuss it there.
