### ISSUE TITLE
Wilson Pacesetter second hopper won't load

### ISSUE THREAD

**Issue by elkatronas** [Courseplay/courseplay#6886]
Hi, 

Like I said in the title, second hopper doesn't load, it just squirts a little of grain and the truck just drives away from the auger. When I unload a grain cart, it works fine. 

P.S. log looks clean, no errors or crashes.

**Comment by Tensuko** [comment]
screenshot ? version ?
You may have a look here:
https://youtu.be/YhB5EXQfqIE

**Comment by elkatronas** [comment]
This mode works perfect to me. I'm talking about mode 1. I want to deliver grain from bins to selling point.

**Comment by Tensuko** [comment]
Screenshot ?!

**Comment by elkatronas** [comment]
Let me just check that, and here is a screenshot of trailer settings https://ibb.co/9c2Kqnr

**Comment by Tensuko** [comment]
You can just drag and drop screenshots there, we like that more then random websites full of stuff where my Virusscanner starts ticking...
You got 6.03.00043 written in the bottom right corner of your HUD screenshot.
And I would rather like to see the course, but anyway.
What you mean with bins ? If Auger Wagons, you should check my Video anyway, since you see there how to set up the Mode1 too.
If you want to load from an Auger Wagon, you don't add the fillType that you want to load, as it is no active loading.
Active loading =means, you have to choose a filltype when start loading
Load on start is jsut passive, you stand there and anything gets into your trailer. Doesn't matter what.

**Comment by elkatronas** [comment]
![fsScreen_2021_02_22_20_03_10](https://user-images.githubusercontent.com/79064028/108749885-0b71c580-7549-11eb-9ef0-706544169403.png)
![fsScreen_2021_02_22_20_03_12](https://user-images.githubusercontent.com/79064028/108749901-0f9de300-7549-11eb-9404-b9662b12588f.png)
![fsScreen_2021_02_22_20_02_44](https://user-images.githubusercontent.com/79064028/108749911-12003d00-7549-11eb-8331-3bbcb0b578b6.png)

**Comment by Tensuko** [comment]
So loading from a normal silo, will have a look.

**Comment by elkatronas** [comment]
Let's hope it's not a big deal.

**Comment by elkatronas** [comment]
Addition to this: changed to single hopper trailer to transport grain, everything works with single bin. BUT if two trucks are in same route they try to push each other away from bin when first one is loading. Example: Truck is loading itself, second one comes back to load it too, and he pushes the first truck forward, he doesn't stop.

**Comment by lcc1211** [comment]
Does your also fail to unload the 2nd one? I can't get a CP controlled combine to unload into both of them either.

**Comment by elkatronas** [comment]
> Does your also fail to unload the 2nd one? I can't get a CP controlled combine to unload into both of them either.

In a field I load these trailers manually with a grain cart. But when I need to transport them CP skips second hopper. It squirts like 100-150 liters and truck just keeps driving.

**Comment by Tensuko** [comment]
> 
> 
> Does your also fail to unload the 2nd one? I can't get a CP controlled combine to unload into both of them either.

No Idea what you mean.



> In a field I load these trailers manually with a grain cart. But when I need to transport them CP skips second hopper. It squirts like 100-150 liters and truck just keeps driving.

Same for you... More details...

You guys mix up stuff here.
What Trailers, what Mode, what you try to do....
The Base Issue is about the Wilson Trailers...

**Comment by elkatronas** [comment]
I'll make a video later. Stand by.

**Comment by Tensuko** [comment]
Loading is a known Issue, it did sound like unload is a problem too, wich isn't.

**Comment by elkatronas** [comment]
> Loading is a known Issue, it did sound like unload is a problem too, wich isn't.

Yeah, unloading works good.

**Comment by elkatronas** [comment]
Is this going to be reviewed anytime? 🤔

**Comment by Tensuko** [comment]
Not high priority, as it only is for one vehicle (Wilson Pacesetter) and only when loading from a trigger.
Loading at start (manual load) works fine.

**Comment by nolan771234** [comment]
Get the pacesetter by bobby mod, with a single hopper. Looks the same, just fills both hoppers together.

**Comment by Tensuko** [comment]
fixed with the next version, but can't load 2 seperate filltypes, that is due to how the Wilson is build.

**Comment by elkatronas** [comment]
> fixed with the next version, but can't load 2 seperate filltypes, that is due to how the Wilson is build.

Thanks!
