### ISSUE TITLE
Icons on Hud are blurry since newer versions

### ISSUE THREAD

**Issue by Friendlyx** [Courseplay/courseplay#6891]
The Headline says it all

**Comment by Tensuko** [comment]
Dramatic....
Will see if I can do anything about that...

**Comment by Friendlyx** [comment]
I have a fix for it. Its a wrong chanel in the dds file of the icons. here it is correct again
[iconSprite.zip](https://github.com/Courseplay/courseplay/files/6037843/iconSprite.zip)

**Comment by Tensuko** [comment]
@Friendlyx 
sry I haven't seen your msg. Well I am new to .dds only working with Paint.net
Someone else fixed this and I added it to the new PR for next Version, but sure thank you for your effort! Appreciate it.
