### ISSUE TITLE
Don't Work on Game Server! FS19 v6.03.00044 & FS19 v6.03.00043

### ISSUE THREAD

**Issue by Grasigruen** [Courseplay/courseplay#6892]
Hi,
 
I try this morning to implement the new version of Courseplay for FS19 v6.03.00044 and Courseplay for FS19 v6.03.00043.
We use a Nitrado game server.

Both versions disrupt the syncronization process. The player does not come to the game on the sever because the synchronization process is not completed.

**Not** Running Version  FS19 v6.03.00044:
Unknown file type '__Attributions.md'
Unknown file type 'course-generator/README.md'
Unknown file type 'course-generator/LICENSE'
Unknown file type 'course-generator/.editorconfig'
Unknown file type 'course-generator/README'
Unknown file type 'LICENSE'
Unknown file type 'readme.md'
Unknown file type 'reloadAIDriver.bat'
Unknown file type 'reload.bat'
File count per store item too high. 176 found (max. 128)

**Running** Version FS19 v6.03.00042 Server error list:
Unknown file type '__Attributions.md'
Unknown file type 'course-generator/README.md'
Unknown file type 'course-generator/LICENSE'
Unknown file type 'course-generator/.editorconfig'
Unknown file type 'course-generator/README'
Unknown file type 'LICENSE'
Unknown file type 'readme.md'
Unknown file type 'reloadAIDriver.bat'
Unknown file type 'reload.bat'
File count per store item too high. 174 found (max. 128)

We have no Logfile from the server there show us some trouble. 

Best regards

**Comment by jason0611** [comment]
That's strange. Version v6.03.00044 works fine for here on a Nitrado Dedi-Server. 
Doesn't  the server create logs, or are they just showing no errors?

**Comment by Tensuko** [comment]
#6884
#6871

**Comment by Grasigruen** [comment]
The Server doesn't shows logs or failures. You can't enter the game. 
Maybe it is nessarry to clear all courses before update. 

We will wait for the next development steps of CP. 

We had this problems a lot of versions before on the same way. 
We use cp currently more than 1600h on the map HOT2021 and server.
