### ISSUE TITLE
MP dedicated server loads wrong course

### ISSUE THREAD

**Issue by rf152** [Courseplay/courseplay#6893]
When clicking on a course it loads the correct course (the waypoints flash up), but then the waypoints disappear and it has loaded a different course. As soon as you click Drive Now the name of the course at the bottom changes to the one it has actually loaded rather than the one you clicked on.

[server-log.txt](https://github.com/Courseplay/courseplay/files/6027813/server-log.txt)
[client-log.txt](https://github.com/Courseplay/courseplay/files/6027816/client-log.txt)

A restart of the server usually fixes it.

**Comment by Tensuko** [comment]
You got a Callstack and this is a general MP Problem that we have.
#6779
