### ISSUE TITLE
vehicle setting: automatically release unloader after a specific time without waiting for a player in the vehicle

### ISSUE THREAD

**Issue by andremeyer123** [Courseplay/courseplay#6897]
(Wunsch ) Hallo was haltet ihr davon den cp Fahrer nach beendigung der Arbeit (ende der route) nach 3 minuten automatisch zuentlassen ohne extra in den Schlepper zuspringen da der helfer ja weiter geld kostet bis er entlassen wird .
Schreibt eure Meinungen rein.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/discussions

**Comment by andreasthu** [comment]
Täuschen ich mich, oder gibt es diese Funktion nicht schon?
Bei Feldarbeit hab ich die Möglichkeit "deaktiviert und entlasse CP Fahrer" anzugeben.
Oder ist da was anderes gemeint?
Lg
Andreas

**Comment by Tensuko** [comment]
Das ist diese Funktion, nur haben wir das mit absicht (!!) so gemacht, dass man einsteigen muss in das Fahrzeug und dann wird es automatisch entlassen.
Grund: Damit die Meldung da ist und man weis, dass dieser fertig ist. Was entfällt ist das klicken auf 'Abfahrer entlassen' (Man kann also reinspringen und direkt los fahren).
Ganz happy über das wie es einstellbar ist usw bin ich noch nicht, aber das war erst mal die Beste Lösung.

**Comment by andremeyer123** [comment]
> Grund: Damit die Meldung da ist und man weis, dass dieser fertig ist

Wie wäre es dann, den Fahrer zu entlassen und meldung bleibt stehen bis man reinspringt .
