### ISSUE TITLE
Grain cart not loading second hopper on mode 3

### ISSUE THREAD

**Issue by smithit2708** [Courseplay/courseplay#6898]
I create course for mode 3 like i normally have but i use 2 pause points. It will fill first hopper just fine but will not move to second hopper. i have tried everything i could think of including changing wait times on tractor. as well as trying different carts & tractors, different maps, tried running only necessary mods and reloading previous versions of courseplay nothing has changed. I originally ran across this on the welker farms map nbut had the same problem on stock map with stock equipment and only mod was courseplay.  i have the 6.3.44dev version I am also not completely sure how to use the debug channels or take screen shots. thanks in advance and i will try to provide any further information that is needed.

[log.txt](https://github.com/Courseplay/courseplay/files/6031071/log.txt)

**Comment by Tensuko** [comment]
This is how we designed it and this is how it does work:
https://www.youtube.com/watch?v=YhB5EXQfqIE&feature=youtu.be

**Comment by smithit2708** [comment]
I seen that video but how do you get the truck to only pull up a little bit without apause point? Do I have to set the pause point for the front hopper then the truck will pull up on its own to fill  the rear hopper?

**Comment by Tensuko** [comment]
The Truck will always place the bin (1st then 2nd or even 3rd) at the 1st Waypoint. Thats the for 'manual loading' when no filltype is selected. Same for more then 1 Trailer.

**Comment by smithit2708** [comment]
Thanks a bunch. That worked perfectly just lining up the front hopper/trailer with the auger.
