### ISSUE TITLE
When copy single tool course from other vehicle, left/right offset stays, when had a multi tool course loaded before

### ISSUE THREAD

**Issue by djnekkid** [Courseplay/courseplay#6899]
Hello dear Farm Manager devs!

I just noticed something wierd.
If a tractor have been used in a course where multiple tools have been used, say for instance there have been two tractors with mowers attached, and they are beeing run in a "left"/"Right" fashion.
Later i switch both tractors over to for instance a windrower and baler.
The windrowing tractor is OK, as i need to generate a new course for it.
On the baling tractor, i use the copy function from the windroing one, but its sort of stuck thinking it part of a double setup, with the left/right buttons visible, and i cant change it over to 'center' or just '---'

Is this known?

-DJ-

**Comment by Tensuko** [comment]
Try a mode change and see if it stays like that.

**Comment by djnekkid** [comment]
i'll test, but I imagine it wont? as when i change gear it goes into transport and then i needs to reset field-work, but i'll test :D

**Comment by Tensuko** [comment]
What if you just load and not copy the new course for windrower ?
As that course shouldn't have any offset information (but I will give it a try).

**Comment by djnekkid** [comment]
Okei. My grass have regrown, and I've re-tested this.

Step1:
Two tractors with front attached mowers. Pottinger Novacats, and rear attached tedder, Kuhn GF812.
Did a "multiple tools: 2" course, mowed and tedded the grass.

Step2: Removed the saied tools on one traktor, attached a windrower, and generated a new course, and sent it on its way to create a swath.

Step3: Removed the saied tools on the other, and attached a baler, copied the course, selcted the 'field work' mode, and the 'left' is still applied in the "settings" part.

Going into 'transport' mode and back to field work does nothing to help.

To remove the 'multi tool tag', i need to generate a 'single' course, and when I now copy over the course from the winrower, its OK.

Here are some screenshots on the baling tractor.
![image](https://user-images.githubusercontent.com/65364380/109390272-ee564180-7910-11eb-907b-69dcfba1ae2b.png)

**Comment by Tensuko** [comment]
Ofc you need to load a single course to NOT have left/right.


> Step2: Removed the saied tools on one traktor, attached a windrower, and generated a new course, and sent it on its way to create a swath.

This already sounds like you generate a single course here, why not load that one ?

**Comment by djnekkid** [comment]
The winrower course is generated as a single.

Its not saved tho, i just copy it via the copy-interface.

"With load" you mean a saved course?

**Comment by Tensuko** [comment]
Yes, a saved course.

**Comment by djnekkid** [comment]
Grass have regrown and mowed.

If i load a saved 'single course' when the traktor previously had a 'double course' removes the 'double course' as you suspected.

But this is more a workaround then anything?

**Comment by Tensuko** [comment]
This is more a bug of 'copy course' to not notice that you have single course loaded now.
But you delete the multi course before anyway, even if you copy the course ?

**Comment by djnekkid** [comment]
Yes, I do delete it. Or atleast i think i do, can you even copy over a course when another one is loaded?

**Comment by Tensuko** [comment]
Uhm no you are right that is not possible hehe :)
Ok we have a look then if we can do anything about that :)
