### ISSUE TITLE
Bale collector mode and combined fields

### ISSUE THREAD

**Issue by djnekkid** [Courseplay/courseplay#6901]
Hi Devs!

Sick of me yet? :)

The new mode is just awesome! Works like a charm!!

Well, mostly :D On combined fields it will not pick up on 'the other fields'.

F2 and F6 is combined, and F6 have been overwritten with 'both'. My combines and everything else works as intended.
But as you can see from the picture, when the collector is set to F6, it will not pick up from the F2-part.
I've tested with both version .44 and .45

![image](https://user-images.githubusercontent.com/65364380/109062236-f67f6880-76e7-11eb-81d6-b9333f3b33c1.png)

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/discussions/6882
