### ISSUE TITLE
Sugar cane equipment

### ISSUE THREAD

**Issue by D21041995** [Courseplay/courseplay#6902]
When you are going to give extra attention to the sugar cane equipment, CP does not recognize the transshipment the carts do not sell alone, we do not have the option of transshipment, in FS17 it worked until agr doesn’t work, please pay attention to them
thanks
this fuç is forgotten until agr

When we are harvesting with the harvester the 2/3 mode does not recognize only if the harvester is in the CP, this is horrible because we cannot harvest manually and use the CP in the 2/3 mode

**Comment by Tensuko** [comment]
#6660
#4021
