### ISSUE TITLE
It would seem, updating courseplay makes it it impossible for players to sync during loading

### ISSUE THREAD

**Issue by rento112** [Courseplay/courseplay#6906]
Happens if I'm hosting or using a dedicated server. But it happens specifically on my current save. Works fine if I start a new save. Is there a way to like refresh the courseplay files that it probably makes in my save game or something?

I can load the game save just fine when I host it, but it seems to make it where connecting players remain stuck i nthe syncing portion of loadding

**Comment by Tensuko** [comment]
#6884
#6871
next time with logs or better search before post Issue, thx

**Comment by rento112** [comment]
> 
> 
> #6884
> #6871
> next time with logs or better search before post Issue, thx

It appears that the the branch doesnt fix my issue. But the issues you linked both do apply to my problem. I recently tried starting a fresh save, which allow me to load into the server, but once I started interacting with the bale collector, it would freeze my game as described in #6871, thenn it went back to the syncing problem.
