### ISSUE TITLE
Course Play keeps stopping when there is a turn

### ISSUE THREAD

**Issue by Rehab44** [Courseplay/courseplay#6907]
Every time I create a course with any vehicle it stops whenever there is a turn at the end of a row

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by BauerNepo** [comment]
Ich habe wohl das selbe Problem. Courseplay beendet bei erreichen des Turns seine Arbeit, ohne eine Meldung auszugeben. Dabei wird der Helfer entlassen. Da ich mit VCA spiele, fährt der Traktor dann einfach unkontrolliert weiter, da mit VCA das Fahrzeug nicht automatisch hält wenn man aussteigt. 
[log.txt](https://gist.github.com/BauerNepo/9276082f187f393dfcba4d430104c11d#file-log-txt)
So habe ich das Fahrzeug vorgefunden (wie man sieht, hat sich der Fahrer selbstständig entlassen):
![fsScreen_2021_02_27_06_24_03](https://user-images.githubusercontent.com/62202689/109376893-c8587f00-78c7-11eb-805e-c0694b92c08a.png)
Hier hat er aufgehört zu arbeiten:
![fsScreen_2021_02_27_06_25_40](https://user-images.githubusercontent.com/62202689/109376895-cabad900-78c7-11eb-87b3-c4d7edbd237a.png)

Wenn ich nun den Helfer wieder einstelle, fährt er eine Bahn hoch und wieder runter, und dann entlässt er sich erneut.
Mit 6.03.00041 arbeitete er noch auf dem selben Feld ohne Probleme.

Gruss BauerNepo

**Comment by Tensuko** [comment]
Welcher Traktor, welches Gerät (genau).
Log mit channel 12 und 14 bitte.

**Comment by BauerNepo** [comment]
Also, Map ist die Eiersholt vom Modhub. Feld 36, Mission Säen (Raps). 
Traktor ist der originale Fendt Vario 1000 mit der originalen Great Plains YP 2425A Einzelkorndrille. (Damit habe ich schon 91 Stunden mit säen verbracht, bisher ohne Probleme). Genutzt mit der Anhängekupplung, nicht mit der optionalen Dreipunktkupplung.
Kurs wurde neu generiert.
[log.txt](https://github.com/Courseplay/courseplay/files/6054192/log.txt)
![fsScreen_2021_02_27_11_24_18](https://user-images.githubusercontent.com/62202689/109384832-c4d8ee00-78ef-11eb-8f8d-100fbc05a707.png)

Einstellungen:

![fsScreen_2021_02_27_11_23_02](https://user-images.githubusercontent.com/62202689/109384899-416bcc80-78f0-11eb-9c25-be7b6818ca12.png)
![fsScreen_2021_02_27_11_23_03](https://user-images.githubusercontent.com/62202689/109384900-429cf980-78f0-11eb-982f-159a2f1d1a79.png)
![fsScreen_2021_02_27_11_23_15](https://user-images.githubusercontent.com/62202689/109384902-4466bd00-78f0-11eb-983f-0e9c895296b6.png)
![fsScreen_2021_02_27_11_23_24](https://user-images.githubusercontent.com/62202689/109384903-4597ea00-78f0-11eb-8b7c-634821cd01d4.png)

Nach diesem Bild hat sich CP entlassen:
![fsScreen_2021_02_27_11_29_04](https://user-images.githubusercontent.com/62202689/109384975-af17f880-78f0-11eb-8490-eb3038b929d6.png)

**Comment by pvaiko** [comment]
```
LUA call stack:
2021-02-27 05:57   =C:/Users/Arbeit/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/base.lua (708) : printCallstack
2021-02-27 05:57   AIMaxToolRadiusFix.lua (27) : __index
2021-02-27 05:57   =C:/Users/Arbeit/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/vehicles.lua (1577) : getMaxToolRadius
```
Das sieht nach einem Mod Konflikt aus, diese AIMaxToolRadius wo der Fehler auftritt, ist nicht von uns. Irgendein Mod hat die Giants AIVehicleUtil.getMaxToolRadius() anscheinend überschrieben.

Welche Mods hast du neulich installiert/updated?

**Comment by BauerNepo** [comment]
Also ich habe gestern noch ohne probleme gesäht. Erst heute morgen habe ich dann die neuste CP Version geladen, und dann kam das Problem. Muss ich wohl mal ein paar mods rausnehmen und weiter testen...
Hier siehst du, welche mods neu sind (CP habe ich wieder eine ältere version drinn, da ich noch ein paar probleme mehr habe mit der aktuellsten...)
![Modliste](https://user-images.githubusercontent.com/62202689/109390803-f5328380-7913-11eb-8208-7bdc91641a9d.PNG)

**Comment by pvaiko** [comment]
Seit welche CP Version hast du das Problem?

**Comment by BauerNepo** [comment]
der gestrige release, 6.03.00046 müsste das dann sein. (Habs bei mir wieder gelöscht)

**Comment by pvaiko** [comment]
Dieser Unimog wäre interessant, da stimmt was nicht. Ich kann ein Workaround einbauen aber möchte wirklich gerne wissen was genau das ist. Könntest du nochmal das mit debug channel 6 testen? 

Oder wenigstens mir diesen Unimog zeigen, welches Mod ist es genau und in welche Konfiguration, ist irgendwas noch dran?

**Comment by pvaiko** [comment]
Just for the record here, AIMaxToolRadiusFix.lua is part of the Kverneland & Vicon Equipment Pack DLC and CP is calling AIVehicleUtil.getMaxToolRadius() with an implement which does not have the AIImplement specialization.

**Comment by BauerNepo** [comment]
Der Unimog macht manchmal einige Probleme mit CP, da er eine Pritsche hat die sowohl als Kipper sowie auch als Ballenpritsche gekauft werden kann. Da gibt es manchmal probleme dass CP darauf besteht, die Ballenpritsche mit Ladegut zu befüllen...
Der [Unimog](url) ist von FBM, und halt ansonsten ein tolles Teil.
Was den Fehler betrifft, nach umfangreichem Testen ist es so, dass CP beim wenden stoppt sobald ich den Global Company Mod drinnen habe. Und das auch nur in der Version 00046, mit Version .00041 ist alles gut.

**Comment by BauerNepo** [comment]
Hallo, ich habe nun Zeit gefunden um die Änderung zu testen. Bei mir funktioniert es jetzt wieder, besten Dank für die tolle Arbeit die Ihr da leistet.

Gruss BauerNepo

**Comment by Tensuko** [comment]
Super, danke fürs feedback.
