### ISSUE TITLE
Motor abschaltet

### ISSUE THREAD

**Issue by Daniel78-art** [Courseplay/courseplay#6910]
Halllo,
gibt es die Möglichkeit dass der Verlader den Motor abschaltet
![fsScreen_2021_02_25_16_12_51](https://user-images.githubusercontent.com/72348662/109175350-0057a900-7786-11eb-8416-361d4d305009.png)
 solange bis sein Abfahrer wieder da ist?

Gruß Daniel

**Comment by Tensuko** [comment]
#3933
