### ISSUE TITLE
[Suggestion] New Default setting on Mode1 (and refill courses)

### ISSUE THREAD

**Issue by djnekkid** [Courseplay/courseplay#6911]
Hi, Again, Awesome Farmining Manager 19 devs! :D ;D

Take a look at this snip:
![image](https://user-images.githubusercontent.com/65364380/109224352-2009c400-77bc-11eb-8f6b-2aefd2ad0df8.png)
In my experience, the minimum is set to 0% in all cases, but in most cases the player probably want it set to "something high".
It be an automated selling or 'fill food to animals' course in mode1, or any sort of fertilizer/lime/seed refill.
We, or atleast I, mostly want it to be 'filled to the brim', and thus need to change the minimum to >90% every time.

So, if i can suggest that the default value here is 90% or something similar? Or a setting to set 'default refil level minimum'.

I know there are some edge cases where you dont want it to be this high, but thats more edge cases imho.

Thanx again for a GREAT mod!

**Comment by Tensuko** [comment]
Won't do this.
Default is 0% = load as much as you can.

**Comment by djnekkid** [comment]
Yes, I know, and that is exactly the problem. If you use for instance the "milling Machine" to load manure from a manurepit, the sprayer will drive on if the Machine stops, and it regularly do. Needs a slight adjust ment, and then carry on...

Inguess i need to look into some sort of belt system or something then :)
