### ISSUE TITLE
Something removed in v6.03.00018, my FS19 KÖGEL (AUTOLOAD) FLATBED trailer can no longer follow field courses

### ISSUE THREAD

**Issue by AUZ001** [Courseplay/courseplay#6912]
Hello Dev's,

As I mentioned recently, the trailers I use to collect bales are no longer able to use the same courses as the headers.

After doing some investigating, I think I have narrowed it down to something being removed or replaced in CP version 6.03.00018

The truck/trailer combo works fine in v6.03.00017 and earlier, but from v...18 onwards, mode 6 is no longer available for field work.

Version v6.03.00017

![17](https://user-images.githubusercontent.com/3432623/109253141-39098800-7843-11eb-9ef8-2139c70ffb70.png)

Version v6.03.00018

![18](https://user-images.githubusercontent.com/3432623/109253152-3dce3c00-7843-11eb-9cb8-163a6644c1b6.png)

Trailer:
http://www.farmingsimulator19mods.com/kogel-autoloader-fs19-supports-more-palets-v2-1-fs19/

Is there any chance you can take a look and see if you can get these trailers to work in the field once again please?

Thanks in advance,

**Comment by Tensuko** [comment]
Those AutoLoad Trailers are not supported anyway.

**Comment by AUZ001** [comment]
I understand they were not supported, but they could be used in a certain way that was beneficial to the end-user.

I was just hoping whatever was removed, be put back so they can be used the same way prior to build v6.03.00018

**Comment by AUZ001** [comment]
Thank you Peter
