### ISSUE TITLE
English translation word choice mistake.

### ISSUE THREAD

**Issue by gfrantz** [Courseplay/courseplay#6914]
The English translation file has a word choice mistake on line 36 of the "translation_en.xml" file.  

It reads:

		<text name="COURSEPLAY_MOVE_ON_AT" 									text="Drive on at less then:" />

and it should read:

		<text name="COURSEPLAY_MOVE_ON_AT" 									text="Drive on at less than:" />

The correct word is THAN not THEN.  Not a terrible mistake, and I see it all the time incorrectly used on the internet, but technically it is incorrect.

**Comment by Tensuko** [comment]
Done, thanks for correction.

**Comment by gfrantz** [comment]
You are so welcome!  And thanks for a FANTASTIC mod for FS19!
