### ISSUE TITLE
Pfad Finder Findet kein weg

### ISSUE THREAD

**Issue by BlackStar153** [Courseplay/courseplay#6917]
Bei mir is das Problem das der Wegfinder wenn der Hächsler etwas zu weit weg ist kein weg mehr findet egal wechle Machiene.
Könnte ihr mir weiter helfen? 

[log.txt](https://github.com/Courseplay/courseplay/files/6052521/log.txt)

**Comment by Tensuko** [comment]
logfile mit debugchannel 4, 7, 12 und 14

**Comment by BlackStar153** [comment]
Bitte

[log.txt](https://github.com/Courseplay/courseplay/files/6052565/log.txt)

**Comment by pvaiko** [comment]
Und das ging mit v45?

**Comment by BlackStar153** [comment]
kann ich dir nicht sagen hab ne weile nicht gespielt und heute erst wieder angefangen und die neuste version gezogen aber das hatte er schon zig versionen voher denke ich wenn ich mich recht erinnere

**Comment by BlackStar153** [comment]
Also der Abfahrer rammt ja alles nur noch da is keine kolisiosn kontrolle mehr dabei?

**Comment by pvaiko** [comment]
duerfte nicht machen. Hast du zufaellig ein Offset eingestellt?

**Comment by BlackStar153** [comment]
![20210227000541_1](https://user-images.githubusercontent.com/79724679/109364686-a04d2980-788f-11eb-8c22-231f427768df.jpg)

**Comment by BlackStar153** [comment]
> duerfte nicht machen. Hast du zufaellig ein Offset eingestellt?

Was meinst du?

**Comment by pvaiko** [comment]
Gerät-Versatz (seitlich) in HUD

**Comment by BlackStar153** [comment]
nein da habe ich nichts eingestellt ist auf standart (Auto)

**Comment by BlackStar153** [comment]
weiß jetz nicht ob ich das noch dazu schreiben darf

Beim Dreschen Koliedert der Abfahrer Ständig mit denn Drescher weil er ständig vor denn Dresher fahren will was früher noch nicht war ?

**Comment by SeriouZ12** [comment]
Bei dem Häcksler Problem könnte es die Fruchtumfahrung sein. Mach die mal aus. Gras kann man leider nicht auslesen wo das ist.

**Comment by 60erjonny** [comment]
Hallo

Falls ich hier, auch was dazu beitragen könnte...

Habe das gleiche Problem, aber mit einem Drescher.
Mit Version CP 6.03.00043 geht das abfahren des Dreschers noch, ab 6.03.00044 gibt es Probleme.

Hänge hier mal, verschiedene Logs an.

[6.03.00042 log.txt](https://github.com/Courseplay/courseplay/files/6054379/6.03.00042.log.txt)
[6.03.00043log.txt](https://github.com/Courseplay/courseplay/files/6054380/6.03.00043log.txt)
[6.03.00044log.txt](https://github.com/Courseplay/courseplay/files/6054381/6.03.00044log.txt)
[6.03.00045 log.txt](https://github.com/Courseplay/courseplay/files/6054382/6.03.00045.log.txt)
[6.03.00046log.txt](https://github.com/Courseplay/courseplay/files/6054383/6.03.00046log.txt)

mfg Jonny

**Comment by pvaiko** [comment]
@60erjonny bist du sicher dass es mit 43 noch ging? 42 wuerde ich noch verstehen. Ist das Feld komplett flach oder eher hügelig?

**Comment by pvaiko** [comment]
Oder ist das ein Mission und nicht deine eigene Felder?

**Comment by BlackStar153** [comment]
@pvaiko  bei sind die Felder Alle Flach

**Comment by Tensuko** [comment]
6.03.00046
Map: Irgendwo in Thüringen V2 (x4 Map)
Klappt soweit alles gut, paar spezielle Situationen wo ich mal eingreifen muss, aber der Pathfinder läuft, auch wenn er manchmal abkürzen muss, bei dem großen Feld aber auch kein Wunder...
![fsScreen_2021_02_27_14_16_22](https://user-images.githubusercontent.com/27344744/109388370-f315f800-7906-11eb-8986-08a0447663f0.png)
![fsScreen_2021_02_27_14_16_16](https://user-images.githubusercontent.com/27344744/109388374-f5785200-7906-11eb-8c3b-a6c5869c0577.png)

**Comment by 60erjonny** [comment]
@pvaiko 
Es war eine Mission, aber ich kann es nochmal testen...dann kauf ich das Feld...

**Comment by pvaiko** [comment]
habe gerade ein Fix fuer missions (2084e76685c710e8ebac5c4ecf3c8672631de08b) auf master gepusht, wenn du weisst wie es geht kannst auch damit testen.

**Comment by 60erjonny** [comment]
@pvaiko ja weiß ich, ich teste es mal...!

**Comment by BlackStar153** [comment]
was ar eigl mit denn das der Helfer ständig vor dem Ernter fährt? war das noch in planung zu fixen bzw is das bekannt?

**Comment by Tensuko** [comment]
@BlackStar153 
Fruchtumfahrung aktivieren!

**Comment by pvaiko** [comment]
> was war eigl. mit denn das der Helfer ständig vor dem Ernter fährt? war das noch in zu fixen bzw is das bekannt?

Nein, so was ist nicht bekannt. Wenn's bei dir ein Problem ist dann mach bitte eine neue Issue auf mit einer vernünftigen Beschreibung, debug channels 7, 12 und 14 und Screenshot, noch besser Video. 

Übrigens weiss nicht ob und wie es mit Gras funktioniert, wie @SeriouZ12 schon erwähnt hat.

**Comment by 60erjonny** [comment]
Hallo @pvaiko 

Zu eurer Info.

Ich habe es jetzt getestet, mit immer wieder den selben Spielstand und der Mission von Beginn an.
Die neue Version funktioniert einwandfrei...!
Aber...
Habe auch nochmal mit der CP 43 es getestet, hier war noch alles gut und ging wieder alles gut.
Neugierg wie ich war, habe ich es aber, mit der CP 44 auch nochmal versucht und siehe da es ging plötzlich alles einwandfrei...
Keine Ahnung warum das so war und ist...sorry...!!!
Vielen Dank aber, für eure Arbeit hier...!!!

**Comment by Tensuko** [comment]
Ist dieses Issue mit der neuesten Version nun gefixt ?
@BlackStar153 bei dir auch so wie bei @60erjonny ?

**Comment by BlackStar153** [comment]
Teste ich Wochenende mal :)

**Comment by BlackStar153** [comment]
Bug besteht immer noch 
[log.txt](https://github.com/Courseplay/courseplay/files/6192384/log.txt)

**Comment by Tensuko** [comment]
V 00051 ?
debugchannel 2, 3 und 11 ?
