### ISSUE TITLE
ÜLW Fährt zu weit bzw Rollt zu weit 

### ISSUE THREAD

**Issue by BlackStar153** [Courseplay/courseplay#6920]
[log.txt](https://github.com/Courseplay/courseplay/files/6053906/log.txt)

![20210227084648_1](https://user-images.githubusercontent.com/79724679/109381086-69e7cc80-78d8-11eb-9f22-8b67ea6e868d.jpg)

**Comment by Tensuko** [comment]
Passiert bei mir nur beim ersten mal, beim 2ten run fuhr er so wie hier zu sehen:
 #6894

Eine Einheitliche Verbesserung fürs Anhalten an Wartepunkte ist in Planung.
Tip: verschiebe mit dem Editor den Wartepunkt weiter nach hinten.
