### ISSUE TITLE
(FRAGE) Warum belibt der Helfer vor dem Schwad stehen?

### ISSUE THREAD

**Issue by BlackStar153** [Courseplay/courseplay#6921]
und fährt dann nach 1 minute erst weiter? :)
![20210227145825_1](https://user-images.githubusercontent.com/79724679/109389306-548c9580-790c-11eb-9378-03537dbb1796.jpg)

**Comment by Tensuko** [comment]
Keine Ahnung ?
Kann diverse Gründe haben...
