### ISSUE TITLE
Gras Silage

### ISSUE THREAD

**Issue by Kartracer390** [Courseplay/courseplay#6922]
Hallo,

mein "Problem" ist, dass der Abfahrer immer nur hinter dem Häcksler fährt, wenn ich Gras mit dem Pickup häcksle. Gibt es eine Möglichkeit, dass der Abfahrer seitlich vom Häcksler fährt, wie beim Maishäckseln ?

**Comment by Tensuko** [comment]
Nein, weil gemähtes Gras als Frucht erkannt wird.
#5470
