### ISSUE TITLE
Syncronisations Problem

### ISSUE THREAD

**Issue by Easton97-Jens** [Courseplay/courseplay#6923]
Hallo alle zusammen. Wir haben auf unserem Server ein Problem. Jedes mal wenn wir eine Mod entfernen vom Server haben wir das Problem das anschließend niemand mehr Joinen kann. Es hängt sich immer auf bei der Syncronisieren 29%. 
Fehlermeldung:
Error: Failed to create new object with class id 5632 in initial object array
und class id 2478

Mit der CP 45 und 47 haben wir das Problem das, nach dem entfernen von Mods bzw anpassung der Modliste, wir nicht mehr auf dem Server Joinen können. Wechseln wir auf Version 42 wechseln funktioniert es wieder mit dem Joinen.
Anbei eine SpielerLog wegen dem Fehler.
[SpielerLog.txt](https://github.com/Courseplay/courseplay/files/6055394/SpielerLog.txt)

**Comment by Tensuko** [comment]
Wir haben auch eine Suchfunktion... #6871
