### ISSUE TITLE
Overloader mode  issue 

### ISSUE THREAD

**Issue by spitfire12** [Courseplay/courseplay#6926]
Sorry if this is a know issues (I looked didn't find anything) But I cant get Overload mode to work have tried a few different things (different tractor and grain cart, different combine updating to the latest version of courseplay). Or if this is a mod conflict.
https://youtu.be/neF4DvOM_C4

**Comment by 60erjonny** [comment]
Hallo
The way I see it, you haven't set a break point for overloading.
And a tip from me:
Is that a Knicklencker ...?
I use standard vehicles for bunkering and I have achieved very good results with the Annaburger HTS 34.16.
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=140029&title=fs2019

**Comment by Tensuko** [comment]
This is how you set up the Course (or better say the whole prozess):
https://youtu.be/YhB5EXQfqIE

No idea whats the callstack about, always attach a logfile!
https://github.com/Courseplay/courseplay/wiki

**Comment by spitfire12** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6057354/log.txt)

**Comment by dozerjz** [comment]
I had the same issue!  I worked my way back to version 3.42 and it works again.

**Comment by Tensuko** [comment]
Well I used 3 Combine, 2 Overloader and one Mode1 Driver in 6.03.00046
Works like a charm.

**Comment by spitfire12** [comment]
I just tried on different map and works fine so it must a issue with the map
