### ISSUE TITLE
Suggested Option: Wait Until Full Before Leaving Grain Silo

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#6927]
I would like to have the option for vehicles hauling crops from the silo to a sell point wait until 100% full before leaving. This used to be an option, but it seems to have been either disabled or removed.

**Comment by elkatronas** [comment]
> I would like to have the option for vehicles hauling crops from the silo to a sell point wait until 100% full before leaving. This used to be an option, but it seems to have been either disabled or removed.

That option is still available in Mode 1.

**Comment by Tensuko** [comment]
Just raise min value to how much you want before the driver drives off and ofc the normal vale is by default on 100% as you added the filltype.

**Comment by lcc1211** [comment]
I have tried to figure out how to do that but there doesn't seem to be a button or anything to let me set values. Am I just overlooking something?

**Comment by elkatronas** [comment]
> I have tried to figure out how to do that but there doesn't seem to be a button or anything to let me set values. Am I just overlooking something?

Make sure you have mode 1 selected, sometimes it automatically selects mode 5.

**Comment by Tensuko** [comment]
Mode5 is default but you won't be able to load anything.
Select the filltypes you want to load and normaly it is enough that you say load 100%, but he will also load if got only 30% left and drive off, or you tell him only load if you got enough to loead 100% (min value).
![fsScreen_2021_02_28_19_11_09](https://user-images.githubusercontent.com/27344744/109428776-e1ad1880-79f8-11eb-9c50-bfe275d56ca0.png)
No filltype selected = load at start = wait untill you got loaded by wheelloader or anything like that.
![fsScreen_2021_02_28_19_11_38](https://user-images.githubusercontent.com/27344744/109428773-deb22800-79f8-11eb-8c94-3978cc9964b4.png)

**Comment by lcc1211** [comment]
I think I may know my issue. I am on mode 1, but I use a trackball without a scroll wheel. So I am unable to adjust using that.

**Comment by Tensuko** [comment]
That is something we can't change, as there is no space for the Values...
