### ISSUE TITLE
Déplacement du HUD

### ISSUE THREAD

**Issue by PapyFaitMumuse** [Courseplay/courseplay#6930]
Bonjour à tous,
Peut-on déplacer le HUD sur l'écran?

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by dete96** [comment]
Er hat gefragt, ob es nicht möglich zu machen sei, das HUD zu verschieben. 
Viele Grüße

**Comment by Tensuko** [comment]
Dieses HUD nicht, nein.
