### ISSUE TITLE
Mode 9 Manitou MLA-T 533 does not Start course

### ISSUE THREAD

**Issue by TinyCrocodile** [Courseplay/courseplay#6933]
Today i was trying to get mode 9 working.

Because it did not work with the Valtra T234 i decided to try with a telehandler. 
I choose standard Manitou MLA-T 533. He refuses to even start the course.
Switched back to Valtra and got it working but the Manitou still wont start. 

Here is my log with debug chanel 10
[log.txt](https://github.com/Courseplay/courseplay/files/6064794/log.txt)

Here a Screenshot of the Situation. 
![20210301222237_1](https://user-images.githubusercontent.com/34377785/109566142-bce19f80-7ae3-11eb-8e7a-196a0289dfd5.jpg)

Am i missing something?
Ah i did only rent the manitou ... does that matter?

**Comment by Tensuko** [comment]
Renting a Vehicle should not have an impact I think.
Where is that Manitou from ?

**Comment by TinyCrocodile** [comment]
It is the vanilla manitou from the Game.

**Comment by TinyCrocodile** [comment]
There were multiple Rasons why the Valtra with frontloader did not work at first. 
1. I had too few waypoints on the trailer aproach.
2. I had the trailer too close to the unload waitpoint. 
After several tys i sorted out this issues and got it working with the valtra but not with the manitou

**Comment by Tensuko** [comment]
ok, I will have a look and see whats wrong with the Manitou, but when there is time for this.
If you find out more, let us know :)

**Comment by TinyCrocodile** [comment]
Ok good news i did try again today i got it working. 
First it did not work then i sold everything else and did buy the manitou.  
Now it is working even if i rent a second manitou this works as well. 
Must be some conflict from my side or just bad luck. 
I always struggle a bit setting up mode 9

Sorry for wasting your time

**Comment by TinyCrocodile** [comment]
After some more testing i found the problem. Changing the transport position a tiny bit made it work. Never expected that to be the problem.

**Comment by Tensuko** [comment]
Ok, thank you for your investigation :)
