### ISSUE TITLE
Error on Dedi keeping the server in a boot loop

### ISSUE THREAD

**Issue by ShermyPermy** [Courseplay/courseplay#6935]
Hi guys,

I just downloaded the latest CP Version v6.03.00047
when booting my dedi server i get this error in the log.

2021-03-02 15:54 Error: Running LUA method 'loadSharedI3DFileFinished'.
2021-03-02 15:54 C://gameservers//s1389189//ls2019//gameProfile/mods/FS19_Courseplay/toolManager.lua:92: attempt to compare number with nil

It keeps the DediServer in a bootloop and doesnt allowe me to join it.
when i remove the CP it doesnt do this and boots up allowing me to join.
I hope you can fix this error.

Best Regards,

Shermy

**Comment by Tensuko** [comment]
full logfile client and server

**Comment by Tensuko** [comment]
Try 6.03.00048 or higher and report.

**Comment by ShermyPermy** [comment]
[PC log V00047.txt](https://github.com/Courseplay/courseplay/files/6096824/PC.log.V00047.txt)
[Server Log V00047.txt](https://github.com/Courseplay/courseplay/files/6096825/Server.Log.V00047.txt)

Sorry for the late response guys. Here are my logs. il update to the version you suggest and il repost those logs too. Best regards Shermy

**Comment by ShermyPermy** [comment]
[PC log V00049.txt](https://github.com/Courseplay/courseplay/files/6096831/PC.log.V00049.txt)
[Server Log V00049.txt](https://github.com/Courseplay/courseplay/files/6096832/Server.Log.V00049.txt)

After updating to V00049 the issues seems to be resolved. 
Thanks you guys for the continued work you put into this great mod.

If I find any new problems Il let you know.

Best regards,
Shermy

**Comment by Tensuko** [comment]
Thanks for feedback.
This can be closed then.
