### ISSUE TITLE
[info ip207326] 8650 : has no Courseplay installed, not adding Courseplay data to savegame.

### ISSUE THREAD

**Issue by Willie4440** [Courseplay/courseplay#6939]
Getting this line when trying to use CP with the Modhub John Deere 8650.

[FS19_JohnDeere_8650.zip](https://github.com/Courseplay/courseplay/files/6074412/FS19_JohnDeere_8650.zip)

**Comment by Tensuko** [comment]
Mod Issue.

**Comment by Willie4440** [comment]
Any idea how to make it compatible with courseplay?

**Comment by pvaiko** [comment]
Not sure about this one, you may try to change the vehicle type to tractor in the XML.
