### ISSUE TITLE
LuaScriptSystem.cpp (dedicated server)

### ISSUE THREAD

**Issue by Nisfeer** [Courseplay/courseplay#6942]
Hey,

I got lately 3 warnings and I'm not sure if this may cause some serious problems later on so I'd like to report it and get an answer so I don't ruin my save game (using 6.03.00045). I never had it, can it be caused by some mods or it's from CP? I will download latest version but not sure if it helps.

Log file from dedi: https://zerobin.net/?4e98804a2cd5d382#3tojMw4OUibXkz8+wkXQq0kzALUWKqAyvS+LQXZ0IbI=

**Comment by Tensuko** [comment]
#6871
https://github.com/Courseplay/courseplay/wiki
https://github.com/Courseplay/courseplay/releases
