### ISSUE TITLE
Wendekreis nicht mehr Einstellbar ab v6.03.00042 bis 47

### ISSUE THREAD

**Issue by regs1980** [Courseplay/courseplay#6944]
Bis zur v6.03.00041 konnte man den Wendekreis für den Abfahrer noch Manuell einstellen und er hat den Wendekreis übernommen, ab Version 42 - 47 nicht mehr, siehe Bilder.

v41
![2021-03-03 16_30_07-Greenshot](https://user-images.githubusercontent.com/13314443/109830521-db0fe280-7c3e-11eb-9ad4-dc1905e7e246.png)

v47

![2021-03-03 16_35_17-Greenshot](https://user-images.githubusercontent.com/13314443/109830617-f37ffd00-7c3e-11eb-87ea-b8b6844624fa.png)

Die Fahrzeuge sind die Originalen aus LS19, keine sonder Mods.

**Comment by regs1980** [comment]
Danke schön mit der überarbeiteten vehicles.lua funktioniert das ganze jetzt wieder.

**Comment by Tensuko** [comment]
Ist aber noch nicht Final soweit ich weis und wird dann entsprechend ins Release kommen.
