### ISSUE TITLE
Traktor verliert seinen Kurs beim Silageschieben.

### ISSUE THREAD

**Issue by xerion8300** [Courseplay/courseplay#6949]
Beim Silageschieben verliert der Fahrer seinen Kurs. Er fährt ein paar mal an die Endposition und dann fährt er einfach weiter.
Habe es schon mit verschiedenen Traktoren und Schildern probiert
aber immer irgend wann fährt er übers Silo hinaus.

[log.txt](https://github.com/Courseplay/courseplay/files/6090594/log.txt)
https://www.youtube.com/watch?v=YcrLeFhI9cQ

**Comment by Tensuko** [comment]
Kann ich dir gerade nicht genau sagen warum das passiert.
Ich habe das aufschütten nie in einem Durchfahrtssilo getestet, da ich das dort recht überflüssig fand.
Müssen wir schauen was das ist.

**Comment by TinyCrocodile** [comment]
Das ist bei mir ähnlich gewesen. Allerdings war er bei mir nie hintem raus gefahren. Trotzdem fuhr er zu weit und hat ca. 45000l hinten aus dem silo geschoben. Ich verwende das so, weil ich finde es geht besser und wird schöner als mit durchfahren. Es wird auch durch rückwärts abkippen befüllt. Habe aber gerade kein logfile oder screenshots zur hand.

**Comment by Tensuko** [comment]
Okay, müssen wir schauen, aber gerade keine Zeit für.
Muss etwas warten, sry.

**Comment by Tensuko** [comment]
Try Version 6.03.00059 or higher and report.

**Comment by xerion8300** [comment]
Hallo,
ich habe jetzt diese Silo ausgiebig getestet. Funktioniert einwandfrei bis jetzt.
Besten Dank für eurer schnellen Reaktion und euren tollen Mod.

**Comment by Tensuko** [comment]
Alles klar auch hier danke für die Rückmeldung.
