### ISSUE TITLE
Kühe fütter

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#6950]
Moin 
Ich will mit den selbst fahrenden Futtermischwagen die Kühe füttern, der Mischwagen soll über ein Hochsilo mit Stroh, Heu und Silage aufgefüllt werden, ich habe bei Courseplay Beladung am Startpunkt eingestellt und die drei Ladentypen zugefügt: 40 % Silage, 40 % Heu und 20 % Stroh.
Es werden aber jetzt nur 40 % Silage reingefüllt und nicht Heu und Stroh
Kann mir einer Helfen !

**Comment by Tensuko** [comment]
So funktioniert das auch nicht.
Es wird nacheinander abgearbeitet, bei jedem neuen anfahren wird die Liste von oben nach unten gecheckt.
Mehrere FillTypes klappen nur, wenn man auch mehrere Trailer oder Behälter hat.
