### ISSUE TITLE
Mode 2 handoff to autodrive

### ISSUE THREAD

**Issue by jspring0811** [Courseplay/courseplay#6951]
I thought mode 2 had an option to use autodrive for the road course.  I don't see the option under control, settings, or advanced settings.  Did mode 2 never offer autodrive?  -Thanks

![image](https://user-images.githubusercontent.com/48362683/110165527-0de1e400-7dc1-11eb-96c8-ed01bfa1b52c.png)

**Comment by Tensuko** [comment]
#6409
#5284
