### ISSUE TITLE
No bales found log flood

### ISSUE THREAD

**Issue by jspring0811** [Courseplay/courseplay#6952]
A couple of minor items...

If there are no bales left to be collected on a field and you restart the bale-collect Drive course, then the log is flooded with "No bales found." messages and the game lags. (I know, "don't start the bale-collect on an empty field").  This was observed on Dedi MP but might be career also:
:39 [info lp426701] Puma 240 CVX (#8): No bales found.
:40 [info lp426703] Puma 240 CVX (#8): No bales found.
:40 [info lp426705] Puma 240 CVX (#8): No bales found.
:40 [info lp426707] Puma 240 CVX (#8): No bales found.
:40 [info lp426709] Puma 240 CVX (#8): No bales found.
:40 [info lp426711] Puma 240 CVX (#8): No bales found.
:40 [info lp426713] Puma 240 CVX (#8): No bales found.
...
... about 20 lines logged per second
...

Also I noticed that the bale-collect mode icon has an incorrect mouse hover description "Type: Combine self-unloading"
![image](https://user-images.githubusercontent.com/48362683/110180810-74bec780-7dd8-11eb-929a-f05f9dd214e4.png)

**Comment by pvaiko** [comment]
The tooltip is fixed, the other one, I have no idea it certainly does not happen in SP mode and don't see how it can in MP, is it still doing it with the latest version?

**Comment by jspring0811** [comment]
@pvaiko This appears to be **fixed** now in v050.  Since you have added "one more scan"...

![image](https://user-images.githubusercontent.com/48362683/110725437-9c9d9900-81e5-11eb-8447-5daefe83532d.png)

**Comment by pvaiko** [comment]
You mean still flooding but different text or no more flooding?

**Comment by jspring0811** [comment]
No more flooding.  The issue appears to be fixed.  -- Thanks
