### ISSUE TITLE
Ballen sammeln und abladen

### ISSUE THREAD

**Issue by rellek82** [Courseplay/courseplay#6953]
Mir ist aufgefallen, dass CP v6.03.00049 nach dem Ballen sammeln die Ballen ja sauber am Abladepunkte abstellt. 
Nachdem die Ladefläche die Ballen freigegeben hat, fährt der Abfahrer ja ein kleines Stück vor und kippt dann die Ladefläche erst wieder runter, was ja auch gut ist ja, damit der Ballenstapel nicht umgestoßen wird. 
Wenn der zweite oder dritte Stapel vor den ersten gesetzt werden, hält der Abfahrer beim Absetzen ja etwas Abstand zum vorherigen Stapel, jedoch fährt er dann zum runter kippen der Ladefläche nicht mehr das kleine Stückchen vor und stößt mit dem hinteren Teil des Anhängers den Ballenstapel um. 
Das Problem hatte "Holger70" in seinem Youtube-Video vom 28.02.21 auch schon entdeckt. 
Hat noch jemand diesen Problem, oder gibt es dazu schon eine Lösung?
Getestet auf diversen Karten mit Fendt 724 und dem Quaderballensammelwagen (Keine Mod-Fahrzeuge)

**Comment by Tensuko** [comment]
Ja das ist wirklich so, mal sehen ob es dafür eine Lösung gibt.

**Comment by rellek82** [comment]
Ok, danke für die schnelle Antwort.

**Comment by rellek82** [comment]
Super, es funktioniert.
Vielen Dank.
