### ISSUE TITLE
Mode 2 kommt nicht zum drescher wenn man selber fährt + ST hangausgleich

### ISSUE THREAD

**Issue by LEGAMINGDE** [Courseplay/courseplay#6955]
- Wenn ich selber den dresche bediene kommt der abfahrer nicht zum abtanken
- cp aktiviert den hangausgleich des Syn track by ImpTS automatisch wenn man den cp helfer einstellt 

https://youtu.be/6sXAO7JdB1A

**Comment by Tensuko** [comment]
- Bekannt und wirds sich auch erst mal nichts dran ändenr (siehe Wiki)
- Müssen wir irgendwann mal gucken, weis nicht mal was das ist.

**Comment by LEGAMINGDE** [comment]
https://farming-simulator.com/mod.php?lang=de&country=be&mod_id=135147
