### ISSUE TITLE
Probleme mit der Geschwindigkeit

### ISSUE THREAD

**Issue by SevenFifty1996** [Courseplay/courseplay#6956]
Hallo,
ich habe da ein kleines Problem. Immer wenn der Drescher voll ist, fängst das Spiel an zu stottern. Bisweilen bleicht es auch stehen, bis die Meldung kommt , dass das Gerät ab getankt werden soll. Was für ein Drescher, Anhänger oder Traktor dabei verwendet wird, spielt dabei keine Rolle. Zum Abfahrer selber muss ich sagen, er findet recht lange den Drescher. Ab und an verhaspeln sich die beiden noch. Anbei muss ich da sagen, dass man mit den Einstellungen viel machen kann. Vielleicht habe ich noch nicht die perfekte Einstellung dafür gefunden. Ansonsten....weiter so...ihr macht einen tollen Job.
ServenF

**Comment by Tensuko** [comment]
Das stottern kommt vom Pathfinder, wenn der Abfahrer einen Weg sucht.
Was meinst du mit 'er findet recht lange den Drescher' ?
' Ab und an verhaspeln sich die beiden noch.' Screenshot ?
Wichtig wäre, Fruchtumfahrung bei beiden an und keine bis maximal +-2m offset einstellen.
Sicher gibt es Situationen die nicht optimal sind, aber da spielen so viele Faktoren eine Rolle, die kann man kaum alle abdecken (Form des Feldes, wo will der Drescher abgetankt werden, an welcher Stelle im Kurse, usw).

**Comment by SevenFifty1996** [comment]
Hi. Das ging ja fix mit der Antwort.  Also...mit lange meine ich....das es oft recht lange läuft...bis die beiden Fahrzeuge sich verknoten. Die Felder sind Rechteckig. Es passiert an keiner typischen Stelle. Mal am Anfang, mal mittendrin. Das spielt keine Rolle. Mal wird ein Feld auch komplett gedroschen, ohne das ein Fehler passiert. Oft ist es so, dass der Drescher die fahrt beendet, rückwärts setzt, in Warteposition geht. Der Trecker kommt, fährt sehr nah ran....und dann kann es passieren das er stehen bleibt oder das sie sich verknoten.

**Comment by Tensuko** [comment]
Ist alles zu allgemein gehalten.
Gerade das letzte passiert nur, wenn er genau dann zum Abfahren fährt.
Und es ist Situationsbedingt.
Wichtig ist Fruchtumfahrung an und offset maximal 2m zu korrektur.
Wenderadius eventuell noch etwas erhöhen.

Wenn du etwas hast, was ständig passiert, bitte Bilder davon machen.

**Comment by SevenFifty1996** [comment]
Hi..
werde ich machen. Ich werde Bilder von verschiedenen Situationen sammeln und dann posten. Mir war noch etwas aufgefallen. CP behält die Einstellung der Feldarbeit nicht. Er springt immer auf den Punkt Überführung. 
Gruss Sevenf

**Comment by 60erjonny** [comment]
Hallo
@SevenFifty1996 Zitat: Er springt immer auf den Punkt Überführung.
Das ist aber normal das passiert, wenn du das Werkzeug ab.- und wieder anhängst...

**Comment by Tensuko** [comment]
Und solltest du auf einem Server spielen ist es nur die Anzeige, der Modus wird beibehalten.

**Comment by SevenFifty1996** [comment]
Hi,
stimmt schon. Mir ist nur nichts anderes eingefallen. Wenn der Drescher voll ist, dann wird es erst langsamer, dann fängt das Spiel an zu hängen, bewegen ist nicht möglich.....wenn der Pfad gefunden ist....läuft es wieder. Ich denke daher habe ich Geschwindigkeit in den Titel genommen. Wie oben geschrieben, trage ich noch Bilder vom Crash zusammen.

**Comment by Tensuko** [comment]
Kommen jetzt noch Bilder von den Problemen ?
Sonst mach ich hier zu, weil ich nicht weis, was das eigentliche Problem ist.

**Comment by SevenFifty1996** [comment]
Hi,
leider komme ich im Mom nicht zum spielen. Wenn ich mich recht erinnere, passiert der Unfall immer in der ersten oder zweiten Bahn die der Drescher zieht. Dann bleibt der Abfahrer im Korn stehen und der Drescher fährt in ihn rein. Wenn die ersten Bahnen gemäht sind, meist sind sie kleiner als der Drescher mähen kann, läuft alles nahezu problemlos. Wenn ich wieder zum spielen komme, werde ich Bilder vom Unfall sowie von dem Kurs machen...Du kannst hier also ruhig schließen.

**Comment by SevenFifty1996** [comment]
![fsScreen_2021_03_07_09_58_06](https://user-images.githubusercontent.com/32055129/111495487-b5570300-873f-11eb-839c-ee8494446e69.png)

**Comment by Tensuko** [comment]
Ein einzelnes Screenshot hilft Null.
Fruchtumfahrung an ?
Wie sieht der Pfad aus ?

**Comment by TinyCrocodile** [comment]
Ist ein offset eingestellt?

**Comment by SevenFifty1996** [comment]
![fsScreen_2021_03_18_16_52_53](https://user-images.githubusercontent.com/32055129/111656861-33cca700-880b-11eb-9639-e0c8242c5e19.png)
![fsScreen_2021_03_18_16_53_05](https://user-images.githubusercontent.com/32055129/111656873-362f0100-880b-11eb-93d7-f9b487508f93.png)
![fsScreen_2021_03_18_16_55_22](https://user-images.githubusercontent.com/32055129/111656879-37602e00-880b-11eb-87d5-451d958bb690.png)
![fsScreen_2021_03_18_16_55_26](https://user-images.githubusercontent.com/32055129/111656883-38915b00-880b-11eb-824b-b0e88a695425.png)
![fsScreen_2021_03_18_16_55_34](https://user-images.githubusercontent.com/32055129/111656892-3a5b1e80-880b-11eb-87b4-3b8147fb42bc.png)
 Ich hoffe das diese Bilder weiterhelfen...

**Comment by Tensuko** [comment]
Wenn das wieder passiert wie auf dem ersten Bild, dann logfile mit channel 2 und 11.
Aber ich weis noch immer nicht was das Ursprüngliche Problem hier war...
Sicher gibt es komplizierte Situationen wo es nicht immer 100% klappt, aber ohne genaue Infos zu der Situation hilft das alles nichts......

**Comment by SevenFifty1996** [comment]
Das ursprüngliche Problem war, dass das Spiel langsamer wurde. Wo das dran liegt, wurde mir ja erklärt. Wenn der Pfad gesucht wird, kann das Spiel etwas ruckeln. Ich hatte mich, in der Überschrift, nicht richtig ausgedrückt. Zu meinem Problem zu kommen, wenn ich den Wendekreis auf 40 m stelle, kommt es fast zu keinem Unfall mehr. Nur in den ersten 2 Reihen, dort steht der Trecker im Korn und der Drescher fährt in ihn rein. Wie in meinem ersten Bild zu sehen. Ich denke, wir können hier erstmal schließen. Spielen ist leider im Moment nicht ...leider.

**Comment by Tensuko** [comment]
Ok danke für die Zusammenfassung.
Ja es ist und bleibt schwierig, Drescher und Abfahrer sauber zusammen zu bringen, in vielen Fällen klappt es, bei einigen Kombinationen in bestimmten Situationen eher nicht, dafür sind es aber auch zu viele Variabelen.

Mache hier dann erst mal zu.
