### ISSUE TITLE
For some reason, ever since the bale collector update, I havent been able to set off sets. It's now beecome a problem for me since i cant get a tractor and trailer to follow my sugarcanne harvester from the side.

### ISSUE THREAD

**Issue by rento112** [Courseplay/courseplay#6958]
Having the trailer follow behind is impossible becausse the harvester's unloading "tube" isnt long enough.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by rento112** [comment]
> 
> 
> https://github.com/Courseplay/courseplay/wiki

If you needed a log or something just say so, as for what version I'm using, i used multiple versions ever ever sicne the bale collector mode was added, currently now using version 49.

[log.txt](https://github.com/Courseplay/courseplay/files/6096119/log.txt)
