### ISSUE TITLE
Abfahrer fährt Ernter Falsch an und fährt zu enge kurven mit ÜLW

### ISSUE THREAD

**Issue by BlackStar153** [Courseplay/courseplay#6959]
![20210306222822_1](https://user-images.githubusercontent.com/79724679/110221313-ddd33780-7ecb-11eb-8f85-94e8aa2c290a.jpg)
![20210306223138_1](https://user-images.githubusercontent.com/79724679/110221311-dca20a80-7ecb-11eb-849d-437c092bdf2c.jpg)

[log.txt](https://github.com/Courseplay/courseplay/files/6096131/log.txt)

![20210306224017_1](https://user-images.githubusercontent.com/79724679/110221514-fa23a400-7ecc-11eb-8937-375daa221d2b.jpg)
![20210306223138_1](https://user-images.githubusercontent.com/79724679/110221515-fb54d100-7ecc-11eb-89fe-e0c4dd937308.jpg)
![20210306223913_1](https://user-images.githubusercontent.com/79724679/110221516-fbed6780-7ecc-11eb-998a-b4f8c4835ac6.jpg)
![20210306223934_1](https://user-images.githubusercontent.com/79724679/110221517-fc85fe00-7ecc-11eb-87c9-ed8171436386.jpg)
![20210306223948_1](https://user-images.githubusercontent.com/79724679/110221518-fc85fe00-7ecc-11eb-84d4-987718e9b426.jpg)

[log.txt](https://github.com/Courseplay/courseplay/files/6096144/log.txt)

**Comment by Tensuko** [comment]
Wenderadius ?
Offset ?
Fruchtumfahrung ?

**Comment by BlackStar153** [comment]
Wenderadius           Weiß ich nicht kann ich nicht einstellen
Offset                      keine ahnug was du damit meinst
Fruchtumfahrung    Ist Deaktiviert

**Comment by Tensuko** [comment]
Wenderadius kannst du einstellen, ist die Seite mit den Schiebereglern.
Offset links/rechts in metern, kann man auch einstellen.
Fruchtumfahrung bei beiden aktivieren!

**Comment by Tensuko** [comment]
Offset (ist nur für minimale Anpassung!)
![fsScreen_2021_03_07_09_48_16](https://user-images.githubusercontent.com/27344744/110234432-b65f8780-7f2a-11eb-8c8a-f25840904c4f.png)
Wendekreis:
![fsScreen_2021_03_07_09_48_12](https://user-images.githubusercontent.com/27344744/110234441-c5463a00-7f2a-11eb-9943-425847196d23.png)

**Comment by BlackStar153** [comment]
> Wenderadius kannst du einstellen, ist die Seite mit den Schiebereglern.
Wendekreis habe ich hin bekommen

> Offset links/rechts in metern, kann man auch einstellen.
das geht auch
> Fruchtumfahrung bei beiden aktivieren!
dann haben die Probleme 

Und noch ein Problem wenn er voll ist donnert er in denn Havister rein 
![20210307105511_1](https://user-images.githubusercontent.com/79724679/110236020-e2cbd180-7f33-11eb-800f-938e6e9e037f.jpg)

**Comment by Tensuko** [comment]
Fruchtumfahrung aktivieren!!

**Comment by BlackStar153** [comment]
die wahr beim Abfahrer an :)

**Comment by Tensuko** [comment]
Und beim Ernter ?
