### ISSUE TITLE
New changes to debug channels

### ISSUE THREAD

**Issue by dragon1220** [Courseplay/courseplay#6961]
Hi Guys

Firstly, love the bale collector mode, and cant wait for the stacking on the field function to be added...

but as in the title, thanks for updating the debug channels to make more sense... However, I used to use the old channel 14 to show where the vehicle was heading, especially when turning, if it was guna do a ? turn, and to see where it was guna be reversing or maneuvering to. 

With the new allocation of the debug channels, which channel would I need for that now?

Hope that makes sense

Keep up the great work

G

**Comment by Tensuko** [comment]
Go into advanced settings and turn on the pathfinder lines or howecer we called it. This is per vehicle and doesnt spam the log.
