### ISSUE TITLE
Spritze springt auf Überführung (Button bleibt auf Mode4) 

### ISSUE THREAD

**Issue by Tom20214** [Courseplay/courseplay#6964]
Moin,
![fsScreen_2021_03_07_20_18_52](https://user-images.githubusercontent.com/50717293/110251810-9c519380-7f82-11eb-8da9-5c6106061fc2.png)
 bei mir springt die Spritze nach Spielneustart auf Überführung

[log.txt](https://github.com/Courseplay/courseplay/files/6097794/log.txt)

**Comment by Tensuko** [comment]
Ist das so kompliziert, nach dem Spielstart noch mal auf den richtigen Knopf zu drücken ?

**Comment by Tensuko** [comment]
Hab es gerade ausprobiert.
Mode bleibt ausgewählt nach saveneustart.
Bitte einmal die genauen Schritt nennen.

**Comment by Tensuko** [comment]
Und da zeigt es sich wieder...
Genauer erklären dann versteht man auch was los ist!

So:
Feldspritze, Mode Button bleibt nach Saverestart auf Mode4, aber Mode5 wird gestartet.

**Comment by Tom20214** [comment]
@Tensuko ich hab ein bisschen gestestet und herausgefunden bei das es auch im Modus 6 bei Selbstfahrern besteht.

**Comment by Tensuko** [comment]
Welche Selbstfahrer hast du zum testen benutzt ?
Weil mit dem Krone BigM z.B. war das kein Problem.

**Comment by Tom20214** [comment]
Mit dem Standard New Holland  CR 10.90 und denn Bigm 500 (Mod)

**Comment by pvaiko** [comment]
Fixed in v50

**Comment by Tom20214** [comment]
@pvaiko Dankeschön fürs fixen
