### ISSUE TITLE
automatische Motor Abschaltung nach der Ernte/Arbeit

### ISSUE THREAD

**Issue by KeineEndeDerLegende** [Courseplay/courseplay#6965]
Grüss dich,

Was mir aufgefallen und bissl genervt und zwar mein Server läuft 24/7 ohne leere Spieler pausieren.. fallst ich den CP einstelle egal ob dreschen oder düngen oder sonstiges. Sobald seine Arbeit fertig schaltet er die Motor nicht ab. 
Es wäre super wenn ein einstellbare Motor abschaltung eintrage oder dauerhafte abschaltung nach der Ernte/Arbeit.. 
Jedes mal wenn wir die felder nicht fertig werden lass ich immer AD und CP laufen damit die alleine fertig machen und am nächsten tag wenn ich wieder online gehe steht er fertig und der Diesel ist leer weil er nach der ernte/ arbeit einfach motor laufen lässt statt abschalten.. bei AD macht immer wenn er keine ladung oder drescher ruft nicht schaltet er nach 5-10sek motor aus bis er gerufen wird oder so..

danke LG Chris

**Comment by Tensuko** [comment]
#3933
