### ISSUE TITLE
Only showing yellow arrow when starting course.

### ISSUE THREAD

**Issue by marci8500** [Courseplay/courseplay#6966]
Only showing yellow arrow when starting the course.
I'm playing on No man's land, I completely reinstalled the mod. When I first started the map, it worked completely.
[FS 19 log](https://pastebin.com/CetgkuBQ)

**Comment by Tensuko** [comment]
Error: Failed to open xml file 'C:/Users/Marci/Documents/My Games/FarmingSimulator2019/mods/FS19_fillLevelDashboard_Prefab/modDesc.xml'.
Available mod: (Hash: 91c9b6467ee30a6e4ae82d36e4ac42c5) FS19_fillLevelDashboard_Prefab
Error: Missing descVersion attribute in mod FS19_fillLevelDashboard_Prefab
Available mod: (Hash: b3525c23578b6d76d2196236b16a0c76) (Version: 1.0.1.0) FS19_FillLevelLimiter
Available mod: (Hash: 6afc538986d23a105df4ad7dba544da7) (Version: 1.5.0.0) Bigger_BigBags_Bigger_Tanks_ModLandNet
Error: Invalid mod name 'FS19PlaceAnywhere-master'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit


LUA Error:
2021-03-08 18:08 Error: Running LUA method 'mouseEvent'.
2021-03-08 18:08 C:/Users/Marci/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/triggers.lua:416: attempt to index a nil value

Not sure what trigger causes this.

**Comment by Tensuko** [comment]
> Only showing yellow arrow when starting the course.

What course, what you try to do, etc

**Comment by marci8500** [comment]
> > Only showing yellow arrow when starting the course.
> 
> What course, what you try to do, etc

Just a simple move from A to B course but if I would try like a harvest that wouldn't work as well. There are no working courses.

**Comment by Tensuko** [comment]
Does this happen on other maps too (like Basegame one) ?

**Comment by marci8500** [comment]
@Tensuko I'll check it tomorrow.
> Does this happen on other maps too (like Basegame one) ?

**Comment by marci8500** [comment]
@Tensuko The issue was being present because of the [racking storage mod](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=180132&title=fs2019). I think it is easily reproducible. As soon as I removed the mod from the game it started working in the same savegame! Thank you for the help! I would suggest to reproduce the problem and put it in the incompatible mods list as I haven't seen it there.

**Comment by Tensuko** [comment]
Alright! Thank you for the feedback!
