### ISSUE TITLE
Vorschlag: Kann der Verdichter auf den Silo bleiben?

### ISSUE THREAD

**Issue by Tom20214** [Courseplay/courseplay#6975]
Ist es möglich das der CP Fahrer im modus 10 beim Verdichten nicht vom Fahrsilo runterfährt, da er sehr viel Häckselgut aus dem Keilsilo rausdrückt.

**Comment by Tensuko** [comment]
Womit verdichtest du denn ?

**Comment by Tom20214** [comment]
Mit einen Xerion 5000 ohne Schild  aus dem Claas DLC

**Comment by Tensuko** [comment]
Zeig mal bitte ein Bild, wie weit er vom SIlo runter fährt.

**Comment by SeriouZ12** [comment]
Das kann ein Vor- oder Nachteil sein. Er baut damit nämlich auch eine Rampe wodurch die Abfahrer gut aufs Silo kommen. Ich mag das tatsächlich. Am Ende einfach paar mal drauf schieben und gut

**Comment by SeriouZ12** [comment]
Das kann ein Vor- oder Nachteil sein. Er baut damit nämlich auch eine Rampe wodurch die Abfahrer gut aufs Silo kommen. Ich mag das tatsächlich. Am Ende einfach paar mal drauf schieben und gut

**Comment by Tom20214** [comment]
eine option wäre geil wo man es aktivieren oder deaktivieren könnte

**Comment by Tensuko** [comment]
Nicht noch eine option.....
Es ist zwar schön sowas umschalten zu können, aber die Vergangenheit hat uns gezeigt, je mehr optionen um so öffter wird etwas falsch eingestellt und hier als Issue aufgemacht...
Wir werden daran erst einmal nichts machen.
Du kannst das gerne als Idee unter Discussions reinsetzen: https://github.com/Courseplay/courseplay/discussions
