### ISSUE TITLE
Mode 1 Grain Transport issue,  Unloading unwantedly in modded Silo

### ISSUE THREAD

**Issue by rento112** [Courseplay/courseplay#6979]
I'm using a silo that has its overhead loading area in the same area that has trailers/tippers unload their contents.
After it loads my  traiiler, it has the trailer unload.

https://youtu.be/RDiJ4GVp57s

Edit: I forgot to mention. It seems to work okay if it recognises a second unloading point after this silo, but I guess it doesnt recognise  selling as an unloading point. Which is the Sawmill. non-vanilla map.

**Comment by Tensuko** [comment]
Move your start point more far away from the silo...

**Comment by rento112** [comment]
> 
> 
> Move your start point more far away from the silo...

You dont think I didnt try that? I did get manage to work by havng it turn away from the silo before the unload trigger could be set off, _but_ this would not work for a silo I've been wanting to use that has building around it's loading and unloading area. 

I tried moving the starting point further down the silo, but the trailer would still load at the same point as usuual. So, moving the starting point does nothing.

**Comment by rento112** [comment]
Maybe make  it where there's a delay in the search for an unloading "i" prompt so that it doesnt unload right after loading the trailer?

**Comment by rento112** [comment]
> 
> 
> When i had this problem, i have to move second poit further away, so trailer is not in reach of unload point when get at this position (as I udenrstand, CP startr looking for unload point as soon as he move away from start point)

What do you mean? It doesnt search for the unloading point until the second waypoint, is that what you're saying?

**Comment by archaoncze** [comment]
> > When i had this problem, i have to move second poit further away, so trailer is not in reach of unload point when get at this position (as I udenrstand, CP startr looking for unload point as soon as he move away from start point)
> 
> What do you mean? It doesnt search for the unloading point until the second waypoint, is that what you're saying?

Yes, that is what i try to say

**Comment by rento112** [comment]
> 
> 
> > > When i had this problem, i have to move second poit further away, so trailer is not in reach of unload point when get at this position (as I udenrstand, CP startr looking for unload point as soon as he move away from start point)
> > 
> > 
> > What do you mean? It doesnt search for the unloading point until the second waypoint, is that what you're saying?
> 
> Yes, that is what i try to say

interesting, I'll have to test that when I get the chance

**Comment by rento112** [comment]
> 
> 
> > > When i had this problem, i have to move second poit further away, so trailer is not in reach of unload point when get at this position (as I udenrstand, CP startr looking for unload point as soon as he move away from start point)
> > 
> > 
> > What do you mean? It doesnt search for the unloading point until the second waypoint, is that what you're saying?
> 
> Yes, that is what i try to say

THANK YOU!!! I'll use this for whenver I have an overhead silo that has its unloading point under it.

**Comment by Tensuko** [comment]
Guys, if you look at my drawing, this is exactly what I showed you....
1st WP more far away and ofc the 2nd WP will be more far away too.....

And yes we start to look for unload point when 2nd WP is reached.

> We are looking for an UNLOAD point on the whole course, starting with the 2nd waypoint!

Anyway, closing this now.
