### ISSUE TITLE
the tractor stops behind the thresher

### ISSUE THREAD

**Issue by ice81rm** [Courseplay/courseplay#6983]
hi guys, the tractor gets stuck behind the thresher instead of joining it ...

Version 00050
Mappa : Svapa Agro 
mod used: John Deere 9000i 
[log.txt](https://github.com/Courseplay/courseplay/files/6115941/log.txt)
Pack

**Comment by Tensuko** [comment]
2021-03-10 13:50 Error: No depth map available, but shape 'drivingDust' (emitter1Ref) with material 'fx_smoke01_mat' uses a custom shader which requires reading depth data.
2021-03-10 13:51 :43 [info lp64143] CR10.90 847 (#5): Found no trailer to unload to.

Is selfunload activated on the combine ?

**Comment by ice81rm** [comment]
![Uploading Screenshot (284).png…]()

**Comment by ice81rm** [comment]
screen 
![Screenshot (284)](https://user-images.githubusercontent.com/39805100/110665361-964cf400-81c8-11eb-9a4a-87a2e5aea773.png)

**Comment by Tensuko** [comment]
This got nothing to do with an offset!
Check this Issue  #5470

iF this is the JD from the JD Pack, switch to the short pipe and not the long.
