### ISSUE TITLE
Düngerfunktion beim Drillen

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#6984]
hallo
Ich habe bei Courseplay die Düngefunktion beim Säen ausgestellt, es wird aber trotzdem weiter Dünger mit ausgebracht. 
[log.txt](https://github.com/Courseplay/courseplay/files/6123128/log.txt)

**Comment by Tensuko** [comment]
Das ist ein bekanntes problem beim FS19_precisionFarming
Dünger aus der maschiene holen (strg+i) und fertig. Geht nicht anders.
