### ISSUE TITLE
Not all fields are available for other players.

### ISSUE THREAD

**Issue by simon9000** [Courseplay/courseplay#6985]
I play with my friend with courseplay mod(newest update) and now we have this bug. I, as an admin, when generating courses for combine or bale collecting can select everyones field number, but my friend, for some reason, can't select some of his fields. For example, my friend has fields: 6,7,9,10,11 and he can only select fields 9,10, but I can select all of them + my own. Also, if he sells and buys them again, he can pick them, but after the server restart, he cannot pick them again.

**Comment by Tensuko** [comment]
He should scan the Fieldborder and add them as a custom Field.
Why this happens after restart, we don't know.
But custom Fields stays.
