### ISSUE TITLE
Quaderballen pressen abfaher wird langsamer wenn 99% ereicht, dann wieder normal

### ISSUE THREAD

**Issue by Playlord75** [Courseplay/courseplay#6986]
Moin hab ein kleines problem beim Ballen pressen der abfahrer presst im ganz normalen tempo die ballen nur immer wenn er 99 % ereicht bremmst er auf 5 khm ab gewollt oder fehler 
Ballen presse: Claas Quadrant aus dem Claas dlc
![fsScreen_2021_03_12_01_21_34](https://user-images.githubusercontent.com/71101944/110873314-c502c180-82d1-11eb-9e05-97fabe7b8df0.png)
![fsScreen_2021_03_12_01_21_40](https://user-images.githubusercontent.com/71101944/110873322-c7651b80-82d1-11eb-95b3-494854910493.png)

**Comment by Tensuko** [comment]
Das ist mit allen Pressen so, warum das so ist keine Ahnung.

**Comment by andremeyer123** [comment]
log bitte schicken

**Comment by Tensuko** [comment]
Ich glaub das war gewollt, weil wir bei Pressen bei denen man anhalten muss sonst drüber rutschen und was liegen lassen.

**Comment by Playlord75** [comment]
Gibt es dort dann aber nicht ne Möglichkeit mit dem anhalten das in eine Kategorie zu unterteilen heißt wenn eine Rundballen Presse angehangen wird das Abremsen bei 99% geschieht und wenn eine Quaderballen Presse angehangen wird das nicht passiert. Möglich sollte sowas doch sein das cp erkennt ob er eine Quaderballen Presse Grade dran hat oder eine Rundballen Presse
