### ISSUE TITLE
Drescher/ Häcksler abfahren 

### ISSUE THREAD

**Issue by leddl1** [Courseplay/courseplay#6987]
Liebes Team von Courseplay,
ich möchte einProblem? melden.
Unzwar: Wenn ich in einem Drescher/ Häcksler sitze und ernte aber zum Abfahren einen oder mehrere Courseplay-Helfer aktiviert habe, dann erkennen diese Abfahrer den Drescher/ Häcksler bei mir nicht mehr. Und fahren diesen demzufolge auch nicht ab,... 
Ich habe dieses Problem bereits länger und wollte mal fragen, ob Ihr das änderen könnt. 
MfG Lukas

**Comment by TobiHH78** [comment]
Siehe hier:

https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ

What is deactivated/doesn't work for now:
•	Combines/choppers have to be driven by a Courseplay helper. We aren't sure yet if we want to allow other (or manual) drivers, we'll see.
