### ISSUE TITLE
Field sprayer crashes game when entering course

### ISSUE THREAD

**Issue by nanoBit93** [Courseplay/courseplay#6989]
Hi,
using the field sprayer on the Ravenport map is suddenly not possible anymore. When the sprayer is reaching the first waypoint it does not turn on the sprayer but it randomly starts driving circles without a possibility to stop the driver. Seems like courseplay is constantly giving some input to the game since if I go to the map it zooms out without any input from me. It's a bit hard to decribe, which is why I recorded a video to show.
Link to vid: https://www.dropbox.com/s/16kbhxi7f7vn8dq/Farming%20Simulator%2019%202021.03.13%20-%2009.49.00.01.mp4?dl=0

Also it's not possible to give the game any input, mouse or keyboard. Only thing possible is pressing Esc one time, afterwards no user input is recognized anymore.

The error was not caused by a courseplay update (happened randomly at some time) and it is occurring on any field. Even courses which have worked previously with the same field sprayer show the same issue now. 
Link to log: https://gist.github.com/nanoBit93/ade26454ae06b6f6ce516847fc6de338

**Comment by pvaiko** [comment]
That is very weird. This error is coming when we loop through the attached implements and sending the standard Giants onAiImplementStartLine event, which should unfold and turn on the sprayer. Which it does on my system nicely, and has been doing forever. There were zero changes in that area.

Your log shows that it is looking for an Attachable specialization which my Rubicon does not have (since there's nothing attachable on it). Is this a plain vanilla vehicle?

**Comment by pvaiko** [comment]
And, does this work with the built-in helper?

**Comment by nanoBit93** [comment]
The Rubicon field sprayer is a vanilla vehicle, yes. I think the error is in FS19 itself and courseplay is just "making it worse". I tried to use the normal helper. It worked well at the beginning but for some reason it's not possible to stop the helper. Releasing the helper doesn't work. Nevertheless, I still have control over the rest of the game (can switch to other vehicles and use them for instance).

**Comment by pvaiko** [comment]
I checked your game version, I have the same, Rubicon works fine with both CP and the game helper. This must be something specific to your setup. Reopen if you can confirm it is a Courseplay problem.
