### ISSUE TITLE
Häcksler mit Feldarbeitsmodus, Richtung der Lands (Feldmitte) einstellen

### ISSUE THREAD

**Issue by Eric270698** [Courseplay/courseplay#6990]
Ich möchte meinen Häcksler mit dem Feldarbeitsmodus häckseln lassen, dabei fahre ich selber mit nem Gespann mit HW80 ab mit Überblasschutz, sprich es muss immer nach Rechts gehäckselt werden. Ich benutze deswegen in der Feldmitte die Einstellung  "Lands" mit so 10 bis 14 Reihen. Nun ist mir aufgefallen das es von den Gegebenheiten (spiele auf Kandelin) des Feldes abhängt, wie rum der Häcksler dann in den Lands fährt, leider kann man das nicht einstellen, manchmal kann man das mit Vorgewendeeinstellungen, wie im oder gegen Uhrzeigersinn usw einstellen aber ich bin jetzt an nem Feld, bei dem es egal mit welchen Einstellungen immer die Lands (für mich) falschrum fährt, sprich ich immer in der Frucht fahren müsste. Könnt Ihr mir da weiter helfen? LG

**Comment by Tensuko** [comment]
Ändert sich denn die Richtung vom Vorgewende ?

**Comment by Eric270698** [comment]
Ja das ändert sich normal von im Uhrzeigersinn zu gegen Uhrzeigersinn, auch ob man erst Feldreihen oder Vorgewende macht kann man ändern, die Richtung der Lands bleibt gleich falsch, bei anderen Feldern wiederum hat es sich mit diesen Einstellungen verändern lassen, nur bei einem Feld jetzt nicht mehr. Es müsste einfach so sein, dass wenn ich das Vorgewende gegen den Uhrzeigersinn fahre, das dann auch die Lands gegen den Uhrzeigersinn gefahren werden aber das tut es nicht. Auch muss man einen 2. Kurs generieren, da sonst die 12 oder 14 Reihen von innen nach außen gehäckselt werden, was ja wenig sinn macht, sprich man muss dann einen kurs machen, der mit den Feldreihen beginnt und nicht mit dem Vorgewende, was ich sehr umständlich finde.

**Comment by Tensuko** [comment]
Ich glaube du hast nur die falsche Option für dein vorhaben.
Stell die mitte mal auf Kreisförmig und schau dir das an.

**Comment by rellek82** [comment]
Kann die Richtung evtl. Durch den Startpunkt beeinflusst werden?

**Comment by Eric270698** [comment]
@Tensuko Nein, das Problem ist ja ich will immer rechts vom Häcksler fahren, zwecks Überblasschutz, bei kreisförmig ist man einmal rechts und auf der Bahn zurück links. Das funktioniert nur mit Lands.
@rellek82 Ja bei einigen Feldern kann auch dies die Fahrtrichtung verändern, nur eben bin ich jetzt an dem Punkt, dass wahrscheinlich dieses Feld von der Form so ist, das es für CP beim berechnen immer einfacher/sinnvoller ist, die Lands sorum anzufahren und nicht anders herum, sprich man hat ja an sich keinen Einfluss darauf. Dies müsste es einfach als Einstellungsauswahl geben, genau so wie im Vorgewende wo ich auswählen kann ob mit oder gegen dem Uhrzeigersinn.

**Comment by Eric270698** [comment]
Es sollte ja auch realistisch sein das ich nur da fahren kann, wo schon abgeerntet ist und ich nicht im Bestand fahren muss, aber auch nicht gegen den Überblasschutz des HW80 häckseln muss.

**Comment by pvaiko** [comment]
@Eric270698 Die Richtung bei Lands ist theoretisch nur von der Seite des Rohrs abhängig, daher ist es merkwürdig dass es nur auf einem bestimmten Feld anders ist. Die Seite ist beim Wechsel auf Mode 6 ermittelt. Keine Ahnung was das mit einem Häcksler ergibt, weil dort ist die Seite eigentlich egal, kann sein dass CP mit der momentane Rohrichtung kalkuliert.

Ein log mit debug channels 6 und 19 würde helfen, am besten gleich mit zwei Beispiele, ein guter und ein schlechter Fall, mit Kursgenerierung und Modewechsel zu Mode 6 beim Häcksler.

**Comment by rohne83** [comment]
> @Tensuko Nein, das Problem ist ja ich will immer rechts vom Häcksler fahren, zwecks Überblasschutz, bei kreisförmig ist man einmal rechts und auf der Bahn zurück links. Das funktioniert nur mit Lands.

Ich glaube Tensuko meinte eher spiralförmig, auch dort bleibt die Abladeseite immer die gleiche. Ist praktisch das gleiche wie Lands, nur rückwärts, und anstatt dass eine maximale Anzahl von Reihen vorgegeben ist zur Zeit immer die gesamte Feldbreite umfassend. Auf relativ schmalen Feldern ist das tatsächlich eine Alternative grade auch mit HW80. Musst nur etwas rumprobieren mit dem Startpunkt, weil da aktuell noch gerne mal bei den Feldreihen die Abladerichtung gegensätzlich zu der beim Vorgewende ist, da gibts aber schon Issues für.
Das wäre zumindest ein Workaround.

**Comment by Eric270698** [comment]
@pvaiko Vielen Dank, genau so ist es, bin mit dem Häcksler neben den Hänger gefahren, so das der Turm nach rechts gedreht ist, Mode hin und her gewechselt, wieder auf Mode 6 und siehe da, es funktioniert, die "Runde" geht anders herum, wie ich es will.
