### ISSUE TITLE
Radlader Schaufel befüllen und entleeren

### ISSUE THREAD

**Issue by fabio0397** [Courseplay/courseplay#6992]
Im Modus Schaufel befüllen und entleeren kann Courseplay den Radlader Arm nicht bewegen. Wenn ich im HUD die Positionen zuweise und diese dann mittels den Pfeilen abrufen will passiert nichts. Aus diesem Grund startet der Helfer nicht wenn ich ihn einstelle. Ebenfalls kann ich die Schaufel und den Arm auch bei eingestelltem Helfer bewegen.

**Comment by Tom20214** [comment]
logfile?

**Comment by fabio0397** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6135476/log.txt)

**Comment by Tom20214** [comment]
kannst du es mal nur mit dem nötigsten mods testen und gucken ob es dann funktioniert

**Comment by Tensuko** [comment]
Also ich habe vor 15min mein BGA Silo entleert, klappte sehr gut.
Und zu deiner log:
A) Warum dieses umbenenne.... FS19_Courseplay.zip lasst die 6 endlich mal weg, das ist einfach nur quatsch.
https://github.com/Courseplay/courseplay/releases .zip laden, in den mods Ordner, fertig!
B) Warum alle mods entpackt ?!
Deine Log von den mods ist so schwer zu lesen, da habe ich echt keine Lust auf Mod-Konflikte zu schauen...

Aber noch mal, an CP wird es nicht liegen, weil bei mir klappte es sehr gut!
Und noch mal extra probiert: Alles kein Problem (es muss überall ok stehen!)
![fsScreen_2021_03_13_22_46_37](https://user-images.githubusercontent.com/27344744/111050051-fe603c00-844d-11eb-8843-e794706fb293.png)

**Comment by fabio0397** [comment]
Danke zuerst mal für die schnellen Antworten. Das mit dem Umbenennen mache ich schon immer so, habe das aus einem Instalations-Tutorial. Werde dies in diesem Fall ab jetzt lassen.
[log.txt](https://github.com/Courseplay/courseplay/files/6135820/log.txt)

Mein Mac entpackt die ZIP-Dateien automatisch beim herunterladen. Als ich dann mal alle mods gezippt habe, hat das Spiel gar nicht mehr gestartet.

Zu meinem Problem: Habe jetzt nochmals Courseplay als einzigen Mod getestet, was nichts gebracht hat. Das einzige was sich bewegt ist die Hochkippschaufel, wenn sich ihre Position ändern soll. Der Arm und der Schaufelzylinder des Radladers bleiben statisch.

**Comment by flattergaul** [comment]
Das gleiche Problem hab ich auch bei einem meiner Spielstände mit dem Vanilla New Holland Radlader.
Allerdings fängt CP dann irgendwann an, den Kurs abzufahren und arbeitet dann auch korrekt.
Bis CP aber startete, dauert es manchmal recht lange.

Werde es im Laufe des Tages mal testen. Braucht ihr irgendeinen Debug-Channel im Log?

**Comment by flattergaul** [comment]
Ich habe es jetzt mal getestet:
Karte: Ravenport
Radlader: New Holland W190D + Vanilla Lizard Silagegabel
Frontlader: Vanilla Fendt Favorit 511c + Stoll FZ30 + Stoll Universalschaufel
Teleskoplader: Vanilla Manitou MLA-T 533 + Magsi Universalschaufel
Aktive Mods: CP, Easy Development Controls

### Radlader & Frontlader
Testen der gespeicherten Positionen entspricht dem, was fabio0397 gesagt hat: nur die Schaufel selber bewegt sich
Der Rest bewegt sich, wenn ich aus dem Fahrzeug aussteige

Wenn ich den Kurs dann starte, passiert folgendes:

- CP stellt die Schaufel (nicht den Baggerarm!) in die Stellung "Transport"
- ist er in der gespeicherten "Transport"-Position, fährt er los
- Ist er **NICHT** in der als "Transport" gespeicherten Position, muss ich aussteigen. Dann bewegt er den Baggerarm in die Position "Transport" und fährt anschließend los


### Teleskoplader
Beim Testen der gespeicherten Positionen bewegt sich die Schaufel **UND** der Teleskoparm wird ein/ausgefahren.
Der Arm wird aber nicht gehoben, das passiert erst beim Aussteigen aus dem Fahrzeug

Wenn ich den Kurs dann starte, passiert gar nichts:

- ist er in der Position "Transport" fährt er nicht los
- ist er nicht in der Position "Transport" und ich steige aus, geht er in die "Transport"-Position, fährt aber nicht los.

[log.txt](https://github.com/Courseplay/courseplay/files/6136311/log.txt)

**Comment by Tensuko** [comment]
Ich kann euch nur sagen, dass das Problem bei euch liegen muss.
Es funktioniert alles so wie es soll.
Ich habe aktuell 433 Mods im Ordner, darunter diverse Scripte, manual attach, manure, vca, bettercontracts, etc, etc und keine Probleme was die achsen angeht. Video ?

BTW: (Version: 1.0) MultipleMissions <- das kannst du rausschmeißen, wenn du better contracts drin hast.

**Comment by flattergaul** [comment]
@Tensuko: Ja, danke, das mit MultipleMissions weiß ich -. hab es nur noch nicht gelöscht sondern nur deaktiviert ;-)

So, ich habe weiter geforscht:

Es hat mit meine Eingabegeräten (Lenkrad G29, Joystick T.16000) zu tun.
Sobald ich einer Funktion des Frontladers eine **Achse** des Joysticks zuordne, tritt das Phänomen auf, dass genau diese Bewegung, der ich eine Joystickachse zugeordnet habe, erst erfolgt, wenn ich aus dem Fahrzeug aussteige.

Wenn ich die Funktion einer Joysticktasten zuordne bzw. keine Zuordnung mache, klappt es.

Ausnahme: der Manitou - der beginnt einfach nicht, die Route zu fahren, aber das Positions-Testen klappt.

**Comment by Tensuko** [comment]
Mit dem Joystick, das kann sein sobald eine Eingabe erfolgt, arbeitet CP gegenan und wird nie die Stellung erreichen.
Mit dem Manitou, da weis ich nicht warum das nun nicht geht.
Welcher ist das ?

**Comment by flattergaul** [comment]
Ist der Vanilla MLA-T 533-145 V+ mit der Vanilla Magsi Universalschaufel.

Das mit dem Joystick klingt mal logisch - aber auch irgendwie nicht ganz:
Das muss irgendwas mit dem Start der Bewegung zu tun haben:
Ist der Frontlader nicht in der richtigen Position und ich steige aus, dann fängt er die Bewegung an und führt die Bewegung auch weiter, wenn ich sofort wieder einsteige. 
Und dann kann ich am Joystick machen was ich will, er macht weiter.

**Comment by Tensuko** [comment]
Ok dann müssten wir schauen, dass wir den input vom Joystick blockieren, wenn der CP fahrer eingestellt ist.
@schwiti6190 ne Idee ?

**Comment by Tensuko** [comment]
Wir machen hier weiter:  #7051

Problem scheint das gleiche zu sein. Input vom Spieler, auch wenn minimal, verhindert starten vom Fahrer.
