### ISSUE TITLE
FS19 Courseplay doesn't use any slurry

### ISSUE THREAD

**Issue by AMG65** [Courseplay/courseplay#6994]
Hallo,

If I set up courseplay te spray slurry on a field, it doesn't use any slurry. It sprays it but on the map, the menu and field it is not visibel. In the menu I select my cow stable as slurry storage. This cow stable is the standard one from the map. 

If I spray manually slurry on the field, every thing works as it should. 

Does anybody have the same problem or knows how to fix it? I have the latest Courseplay version .... 50 at the and.

Thank you !

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by AUZ001** [comment]
Sounds like you have your game settings set to BUY under Helper refill - fertilizer, switch it off and CP will use what's in the tank and run out.

**Comment by Tensuko** [comment]
Closed due to inactivity.
Couldn't find any Issue as well. and I guess AUZ001 is right.
