### ISSUE TITLE
Probably a bug with collision detection

### ISSUE THREAD

**Issue by TyKonKet** [Courseplay/courseplay#6995]
Why does CP creates some kind of "sky ladder" while working on fields?
Some times it gets even more high, I'm in SP.

![](https://user-images.githubusercontent.com/7534621/111071255-92291b00-84d5-11eb-8ed3-875b7e91b2da.jpeg)

**Comment by Tensuko** [comment]
Not a Colli Issue, this is our traffic system, what is the problem with this ?

**Comment by TyKonKet** [comment]
It's just strange that they are floating in the sky...
I've never seen tools working at that altitude 😄 
No seriously, I thought it was a problem with the algorithm that positions them, I saw that they move in order to "predict" the path that the tractor will take.

**Comment by pvaiko** [comment]
This is to take into account the time, the altitude depends the predicted time when the vehicle gets there.
