### ISSUE TITLE
problem with sugar cane harvesting

### ISSUE THREAD

**Issue by ontot** [Courseplay/courseplay#6996]
Goodmorning everyone. I don't know if I'm wrong in some setting, but I can't harvest sugarcane. The tractor doesn't set off to go next to the Austoft 8800 multi-raw thresher for sugar cane harvesting. Can you help me out, please?

this is the log file

[log.txt](https://github.com/Courseplay/courseplay/files/6137056/log.txt)

**Comment by Tensuko** [comment]
#6960
