### ISSUE TITLE
Enhancement: Bale wrapper works like bale loading trailer

### ISSUE THREAD

**Issue by tn4799** [Courseplay/courseplay#6997]
Hello. 
I have an suggestion for bale wrappers. It would be great if they would work like bale loading trailers. 
What exactly I mean is the ability to search for bales themself on the field instead of just driving around a course and wrapping only the bales on the course. 

I wish everyone a nice day
tn4799

**Comment by suchna** [comment]
Have you tryed latest release? 050 seem to already have, what you are suggesting:


6.03.00050 Bale improvements and initialization fixes

    Vehicle initialization after load fixed for #6964 (also made
    it more resilient)

Bale collector/wrapper improvements

    Enabled bale wrapper for Mode 7
    Look for bales once more before leaving for the unload course.

Bale unload fix for #6953

    When moving forward after unloading, use the position where we
    actually unloaded the bales instead of the unload waypoint.

**Comment by tn4799** [comment]
ok, that was something I didn't notice
