### ISSUE TITLE
MP: Mode1 verschiedene Probleme

### ISSUE THREAD

**Issue by LamaiK** [Courseplay/courseplay#6998]
Beim Beladen darf die Plane nicht aktiv sein, funktioniert sonst nur beim ersten Mal, beim nächsten Umgang fährt der Traktor ohne zu laden durch. (Sieht aus als ob er die Plane noch hat welche aber nicht sichtbar ist.)

Nach dem Laden Fährt der Traktor zum Abladepunkt (in diesem Fall ist es der Kuhstall welcher er mit Futter versorgen soll)

Beim Abladen im Stall Kippt er zwar das Futter in den Trog zeigt aber die Kippanimation am Anhänger nicht. Nach dem Abkippen bleibt er einige Sek. Stehen (wahrscheinlich hat er die Kippanimation schon durchgeführt hat sie uns aber nicht gezeigt)

Nach dem Abkippen fährt er weiter zum nächsten Abladepunkt, was richtig ist. Zwischen dem ersten und dem zweiten ablade erscheint die Meldung das er mit dem ersten ablade fertig ist und jetzt mit dem nächsten fortfahren wird. Diese Meldung wird nur blinkend ausgegeben und der Kurs so wie das ganze Spiel wird ruckelnd aus gebremst bis er den Anhänger ganz geleert hat.

Wenn ich Stroh als eines der zu ladenden Güter auswähle wird dieses nicht abgezählt, der Counter steht immer auf 1/20 und er wiederholt den Stroh Transport unendlich.

Das Spiel läuft auf Dedi Server mit Seasons.   

Log vom [Server ](https://workupload.com/file/67swhyFkszm)
Log vom [Player](https://workupload.com/file/rRpCrBpME7R)
Link zum [Video](https://workupload.com/file/TSuuTR5Jdk2)

**Comment by Tensuko** [comment]
Du vermischst hier mehrere Dinge...
Beladen am Startpunkt funktioniert sehr gut!
Was du hier beschreibst ist:
A) Die Planen werden nicht richting gehändelt (bekannt, Planen handling muss überarbeitet werden)
B) Die Animation nicht richtig läuft (sollte mit CP nichts zu tun haben)
C) Ein zweiter Abladepunkt wird nicht richtig angefahren -> Abladestelle voll, fahre vort zur nächsten (ist auch bekannt)
D) Counter wird nicht runter gezählt auf Dedi Server (nie probiert, müssen wir schauen)

Wichtig ist auch die Info: MP
Wie du an einigen Issues siehst, haben wir im MP gerade ein Problem,  wesshalb wir für den MP die Version 00042 empfehlen.

Zu deinen Logs:
Warum so ein komischer extra Service ?!
GitHub bietet die möglichkeit, Textdateien hier direkt anzuhängen, per drag and drop...

**Comment by LamaiK** [comment]
Mag sein das es mehrere Dinge sind, werden aber alle im Mod1 zusammen benötigt.

Beladen am Startpunkt funktioniert eben nur richtig wenn man die Planen abschaltet.

A) Planen Problem ist ja auch bekannt. Danke für die Info.
B) Die Animation funktioniert ohne CP richtig, ergo muss CP an der fehlenden Animation schuld sein,
korrigiere mich wenn ich falsch liege.
C) Ist auch bekannt. Danke für die Info.
D) Der Counter zählt nur mit dem Stroh nicht runter, bei meinen Versuchen, vielleicht gibt’s ja noch andere.

Denn MP Hinweis hatte ich vergessen. Sorry.

Extra Service: Da Videos nur in geringer Grösse auf GitHub geladen werden können verlinke ich diese  natürlich auf einen File Hoster, naheliegend ist dann auch gleich die Logfiles mit zu verlinken. Wenn du das aber nicht wünscht kann ich das in Zukunft ändern.

Und ja ich berichte sehr gerne über gefundene Fehler in CP, ich liebe diese Tool und bin froh das ihr dieses für uns Programmiert.  Danke schön an dieser Stelle. :-)

**Comment by LamaiK** [comment]
Nachtrag zu D) Es ist immer das letzte in der Reihe. Hatte bis jetzt immer das Stroh zu letzt eingetragen, ändere ich die Reihenfolge geht es mit Stroh aber dann ist es halt die Silage oder das Gras usw. Hat also nichts mit dem Filltyp zutun.

**Comment by Tensuko** [comment]
ok, danke fürs feedback
