### ISSUE TITLE
Radlader

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#6999]
Moin
Ich fahre den Radlader mit Courseplay, hab die Strecke eingefahren und hat alles gut funktioniert, Silage aus dem Silo nehmen und in ein anderen Silo rein fahren, jetzt fährt der Radlader gerade in Silo rein lässt die Schaufel runter und fährt dann gegen die Wand 
![Radlader](https://user-images.githubusercontent.com/47453761/111211994-5d998a00-85cf-11eb-85bf-20c594520f72.png)

**Comment by Tensuko** [comment]
Weil er vorne rechts was haben will und da nicht hin kommt.
 nimm das zeug vorne rechts manuell weg, dann sollte es wieder gehen, ist halt ein Probelm von kleinen silo, großen radlader, schelchter winkel.
