### ISSUE TITLE
Leeb PT 350 In Traffic Error

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#7001]
I am using the Leeb PT 350 to fertilize. I have a refill course running that works on other vehicles, but this one is too sensitive and thinks traffic is blocking it when the path is completely clear. This is the sprayer form Modhub's Horsch DLC.
![20210317120003_1](https://user-images.githubusercontent.com/24764870/111499516-6ac29000-8719-11eb-945b-ac549a03e6bf.jpg)

**Comment by Tensuko** [comment]
Duplicate and working on a fix right now #6685
