### ISSUE TITLE
freezes game

### ISSUE THREAD

**Issue by Carlgoodram** [Courseplay/courseplay#7007]
hi i downloaded the latest version of courseplay today and when ever i load it into my savegame on welcome to oakhill it freezes the game and i cant even exit the game i have to restart my whole computer to sort it this has happened the whole day can anyone advise how to sort this

**Comment by Tensuko** [comment]
I have hight doubt you have to restart your computer, as there is still a task manager.
Anyway: https://github.com/Courseplay/courseplay/wiki

**Comment by Carlgoodram** [comment]
ive just started a new save game and it works fine on that so i will delete the save from before and start a new save as i only started it this morning so not losing anything
