### ISSUE TITLE
freezing when a tractor has to go to the combine to unload

### ISSUE THREAD

**Issue by landtools** [Courseplay/courseplay#7008]
hi all friends, I'm having a problem on the latest versions released. after starting the combine and reaching the max level to be unloaded, the game freezes until the tractor with the trailer starts its run towards the combine. Do you have solutions or show me a way to solve the problem? Thanks so much :)

**Comment by Tensuko** [comment]
Sounds not like a freeze, but the Pathfinder running.

**Comment by pvaiko** [comment]
As we all know very well, even @Tensuko  :) that we need a log with debug channels 2, 3 and 11 to be able to say anything useful about your problem.

**Comment by landtools** [comment]
> As we all know very well, even @Tensuko :) that we need a log with debug channels 2, 3 and 11 to be able to say anything useful about your problem.

ok fine ... how do you enable the log generator?

**Comment by Tensuko** [comment]
pls just drag and drop your txt into comment box, no need to use any upload pages...

**Comment by landtools** [comment]
@Tensuko 
[log.txt](https://github.com/Courseplay/courseplay/files/6175958/log.txt)   sorry Whrong upload... correct now ;)

**Comment by landtools** [comment]
@pvaiko OT : 2021-03-20 16:48 Error: addRequiredCropType foliage must match the size of the ground terrain detail. ???????

**Comment by pvaiko** [comment]
@landtools no idea that's not from us, some other mod. And you don't have the debug channels turned on as Tensuko explained, so no use of the logfile.

**Comment by landtools** [comment]
@pvaiko I activated channels 2-3-11 in the HUD CP ....

**Comment by pvaiko** [comment]
@landtools oh sorry, they were buried under the other errors. 

Looks like the vehicle size may be too big, not sure what tractor/trailer you are using, maybe a mod?

You can check the size with the console command gsVehicleDebugAttributes and then pressing F5 twice. Then make a screenshot for us, there should be some blue rectangles around the tractor and the trailer, that's what we want to see.

**Comment by landtools** [comment]
sorry, how do I start this console command ???

**Comment by pvaiko** [comment]
https://idownblog.com/farming-simulator-19-console-commands-developer-console/

**Comment by landtools** [comment]
@pvaiko @Tensuko Hello, out of curiosity I tried the 00022 version and there are no obstacles .. so it is not something that has to do with vehicles but with cp releases

**Comment by landtools** [comment]
![20210322_213208](https://user-images.githubusercontent.com/71590173/112054790-4b32c980-8b56-11eb-9868-da1c4388cc59.jpg)

Done @pvaiko @Tensuko

**Comment by Tensuko** [comment]
logfile with channel 2, 3 and 11

**Comment by pvaiko** [comment]
Should be fixed by 6.03.00052
