### ISSUE TITLE
I know its a known issue but i really would like it to be fixed:

### ISSUE THREAD

**Issue by Rocky1308** [Courseplay/courseplay#7011]
So when you have CP activated for a tractor with a trailer and his job is it to unload a combine the combine needs to be steered by CP as well. Otherwise the combine wont be unloaded. 

And i would really appreciate it if in some of the next versions it would be possible to drive the combine on your own and you will be unloaded by CP, because i like just chilling in the combine lul :D

**Comment by pvaiko** [comment]
We understand many want this but the current devs have no motivation spending time on it. We are still waiting for someone volunteering...

**Comment by Rocky1308** [comment]
But why dont they add this function when so many want it?

Am Sa., 20. März 2021 um 12:35 Uhr schrieb Peter Vaiko <
***@***.***>:
