### ISSUE TITLE
Overloader tractor dont stop at unloading point

### ISSUE THREAD

**Issue by Melegari** [Courseplay/courseplay#7013]
https://youtu.be/fb_PtrXM0D0

The tractor never stops exactly at the unloading point , it simply stops accelerating and keeps moving slowly until it stops
would be nice, if the tractor simply full stoped precisely at the unloading point,  or im doing something wrong?

**Comment by Tensuko** [comment]
There must be something wrong on your side, we slow down before the waitpoint.
Have a look: https://youtu.be/YhB5EXQfqIE

**Comment by Matt-14** [comment]
What I have done to stop this is edit the speed of the points around the overloading point. I count like 5 points both directions and change the speed down to 5 mph. Also, it seems the points after the overloading point causes the tractor to overrun the overload point. The points after the overloading point need to be slowed way down using the editor.

**Comment by Tensuko** [comment]
Record it slower next time, just as I did on the Video.
We have Plans to make the stopping for loading, unloading and also overloading more comfortable, but that is a bigger project.

For now it is like it is and it does work if don't drive to fast.
