### ISSUE TITLE
Forage harvesting 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#7020]
Hello I’m trying to use the forage harvester and if I call a trailer up why is getting right up the backside of the forager and not beside it can’t find an option to change it

**Comment by Tensuko** [comment]
1st Headland always behind forage harvester and if grass field also becouse that is reported as fruit.

**Comment by matty2123** [comment]
So it failed to move and tractor just sat there am I doing something wrong

**Comment by Tensuko** [comment]
Harvester must be running with CP

**Comment by matty2123** [comment]
It’s not working I’m not headland number 4 and it just sits up the rear of the harvester and the harvester won’t move

**Comment by TinyCrocodile** [comment]
What harvester are you using. Maybe it can not reach the trailer.

**Comment by matty2123** [comment]
Krone big x long reach pipe

**Comment by TinyCrocodile** [comment]
@Tensuko is that the one where short pipe is better?

**Comment by matty2123** [comment]
Any feedback to this
