### ISSUE TITLE
A slurry tanker refills automatically on field

### ISSUE THREAD

**Issue by zwieback666** [Courseplay/courseplay#7021]
Hi Guys, 

I started using Courseplay quite recently, seemingly my slurry tanker, that was set to bring slurry to field and go back, stays all the time on the field and just takes the slurry from the storage it was tanked from. The setting to buy slurry is set to OFF. Did I do something wrong or is it a bug?

**Comment by Tensuko** [comment]
When gamesetting is set to off, it won't buy slurry.
Must be something on your side.
