### ISSUE TITLE
only mode 4 available for the Kuhn discolander

### ISSUE THREAD

**Issue by Quintto** [Courseplay/courseplay#7023]
Hello all,

I just updated courseplay to version v6.03.00051 and I found that now my discolander can only be used in mode 4 (fertilizing and spraying) and not on mode 6 (normal fieldwork) 
so in other words I can't use it anymore to do my cultivation without is being filled with seed. 
It was working in the previous versions

I would upload a log and screenshot but it's not letting me at the moment. but the log is clean

**Comment by Tensuko** [comment]
What exact Tool ?

**Comment by Quintto** [comment]
the ingame Kuhn discolander XM52
