### ISSUE TITLE
Is this possible 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#7024]
Hello sorry to open an issue I want cp to collect grass from field using the forager then dump it in to trailer when trailer is full I want auto drive to deliver it to bga I have a network setup for ad just wondering if this is possible ie when seeding etc Once seeder is empty it will drive and ad will take over if you get what I’m saying

**Comment by JDTiger** [comment]
If you send the forager on the same course as the swather, it should work.

The forager obiously does not see the swath, it is supposed to collcet.

apart from that, it is exactly as if you were foraging corn.

**Comment by matty2123** [comment]
Yeah I got that I wanna send the tractor trailer to collect the grass and use ad to deliver to bga cp for collecting and ad for driving to bga

**Comment by Tensuko** [comment]
Mode2 is not working with AD yet.
