### ISSUE TITLE
loading autdrive course to CP

### ISSUE THREAD

**Issue by Gibbanator** [Courseplay/courseplay#7025]
I may of missed something with this last update. I am unable to load any of my autodrive courses to CP. It shows all my course locations but they do not load do I need to turn something on or something off for this to work?

I do not see the use autodrive line on the hud

**Comment by Tensuko** [comment]
logfile ?

**Comment by Gibbanator** [comment]
sure.. what was I thinking here you go.
[log.txt](https://github.com/Courseplay/courseplay/files/6185242/log.txt)

**Comment by Tensuko** [comment]
I guess that is an AutoDrive Problem:
2021-03-22 16:55 :30 [info lp4330] IDEAL 9T: AutoDrive could not give us a course from the current position to 8a
2021-03-22 16:55 :30 [info lp4330] IDEAL 9T: id 10076 -> course not found, return

**Comment by Gibbanator** [comment]
Was working great before.. Don't know of any autodrive updates... But I will try there

**Comment by pvaiko** [comment]
We haven't changed anything there, don't think it's our fault, really looks like AD does not want to give us a course.

**Comment by Gibbanator** [comment]
Okay I posted in autodrive and added a video with it along with the log
 https://github.com/Stephan-S/FS19_AutoDrive/issues/1854

it could be just turning something on but I can't find it if there is.

**Comment by Tensuko** [comment]
Just saw it working with CP 00052 and AD  1.0.0.8 even on a Server.
