### ISSUE TITLE
Courseplay Autodrive kurse rückwärts erkennung

### ISSUE THREAD

**Issue by Tom20214** [Courseplay/courseplay#7026]
Ist es möglich das Courseplay auch die Rückwärtskurse von Autodrive erkennt? momentan erkennt er die Rückwärtskurse als Vorwärtskurse und fährt z.b vorwärts in das Keilsilo rein

**Comment by pvaiko** [comment]
@Stephan-S we call GetPath() which returns a list of waypoints, how do we know if a waypoint is reverse? CP currently recognizes .rev or .reverse being true.

**Comment by Tensuko** [comment]
@Axel32019

**Comment by SeriouZ12** [comment]
Ich kann dir hier raten den Kurs einmal aus Autodrive zu erstellen, abzuspeichern und dann mit dem CP Editor die Wegpunkte zu ändern. Damit kann man z.B. auch einen Ballen Sammel Kurs erstellen und ihn irgendwo auf der Strecke abladen lassen.

**Comment by pvaiko** [comment]
@Tom20214 hast du AD Kurse mit rückwärtsfahren?

**Comment by Axel32019** [comment]
Hello Peter @pvaiko, @Tensuko,
AD returns a list of waypoints only, there is no explicite information in this table if forward or reverse direction, but:
- each waypoint contain an .incoming table (if not empty) for previous waypoints
- each waypoint contain an .out table (if not empty) for next waypoints

To get the start and end of a reverse part of the waypoints table the following snippet might help:

function ADDrivePathModule:checkForReverseSection()
    local reverseStart = false
    local reverseEnd = false
    if self.wayPoints ~= nil and #self.wayPoints > self:getCurrentWayPointIndex() + 1 and self:getCurrentWayPointIndex() > 1 then
        local wp_ahead = self.wayPoints[self:getCurrentWayPointIndex() + 1]
        local wp_current = self.wayPoints[self:getCurrentWayPointIndex() - 0]
        local wp_ref = self.wayPoints[self:getCurrentWayPointIndex() - 1]
        local isReverseStart = wp_ahead.incoming ~= nil and (not table.contains(wp_ahead.incoming, wp_current.id))
        local isReverseEnd = wp_ahead.incoming ~= nil and wp_current.incoming ~= nil and table.contains(wp_ahead.incoming, wp_current.id) and not table.contains(wp_current.incoming, wp_ref.id)
        local angle = AutoDrive.angleBetween({x = wp_ahead.x - wp_current.x, z = wp_ahead.z - wp_current.z}, {x = wp_current.x - wp_ref.x, z = wp_current.z - wp_ref.z})
        angle = math.abs(angle)
        if angle > 100 and isReverseStart then
            reverseStart = true
        end
        if angle > 100 and isReverseEnd then
            reverseEnd = true
        end
    end
    return reverseStart, reverseEnd
end

**Comment by pvaiko** [comment]
@Axel32019 thanks, not sure I understand what exactly the meaning of the incoming and out parts is, are these tables (and not a single reference to the next/previous point) because the course is forking/merging? 

I could just look at the angle (which we have in our course anyway) and that could probably work fine, as long as an AD course never starts in reverse.

**Comment by Axel32019** [comment]
@pvaiko Hallo Peter, You got it - incoming and out are tables. They keep the point(s) to the previous/next point, but for reverse "coding" the incoming will not have the previous point, the previous will have this point in out. Special way to store the points without the need for additional information if it is reverse direction.
For the reverse end seee above.
The approach to look at the angle might be a good first step.

**Comment by pvaiko** [comment]
@Tom20214 da du keine AD Kurse zum testen gepostet hast musst jetzt selber auf dem issue-7026 testen :)

**Comment by Tom20214** [comment]
@pvaiko Meine AD Kurse sind zu schlecht zum Testen 😂😂

**Comment by Tom20214** [comment]
https://www.youtube.com/watch?v=QUCMvf2lr_I

**Comment by Tom20214** [comment]
@pvaiko https://youtu.be/QUCMvf2lr_I

**Comment by Tensuko** [comment]
Was soll uns das 2te Video sagen ?
Wenn der Kurs den wir von AD bekommen nicht richtig passt und wir den Trailer nicht anständig rückwärts schieben könnne, weil er vorher nicht gerade genug in die Richtung stand, ist das ein Problem vom erstellten AD Netzwerk :)

**Comment by Tom20214** [comment]
@Tensuko Das soll zeigen das auch mit Anhänger funktioniert.

**Comment by Tom20214** [comment]
@Tensuko Da es nun einwandfrei funktioniert mach ich die issue jetzt zu.
