### ISSUE TITLE
Mode 2 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#7029]
I’m having trouble with mode 2 I’m on the latest dev version and using a krone big x to collect grass the problem is the tractor reaches the harvester on the 3 headland and it proceeds to sit behind the harvester Nothing moves etc can include a log of needs be

**Comment by Tensuko** [comment]
On Grassfield we always stay behind harvester becouse mowed grass is reported as fruit.
Why stuck I have no Idea, Screenshot and logfile with channel 2, 3 and 11 I would say.

**Comment by matty2123** [comment]
It’s working on a different trailer but there is something wrong with Mode 2 one when it hits the stop and then the start it should turn off the beacon lights as they are on street only and two the harvester hit the corner and the tractor didn’t wait it just drove off and decided to drive the course I’ve not used mode 2 since update from old system seems a few problems

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ

**Comment by rohne83** [comment]
I can second the issue with the beacon lights. If you set it to street only it remains activitated all the time, even if the vehicle is driven by pathfinder on the field around the harvesters. That seems to be the case for longer now. Noticed several months ago alread but always was too lazy to open an issue just for that one ;)
Not sure though, what exactly his second point is about.

**Comment by Tensuko** [comment]
Closed due to inactivity.
Not sure what is the real Case here, Beacon Lights are rly not that high priority and sure is in any other Issue too.
