### ISSUE TITLE
Tractor not unloading Combine (CombiCourse)

### ISSUE THREAD

**Issue by Xerbarus** [Courseplay/courseplay#7032]
[Hey] everyone I know there was a similar issue in the past which I already tried to read through but couldn't seem to fix it. The Combi Course simply won't unload the Combine when in a waiting position I have already assigned the specific combine and but no matter the fill level the tractor will not unload the combine.

I've updated to the latest version of Courseplay already still no change hope someone can help me out thanks :)

https://i.imgur.com/RolVcfg.jpeg
https://i.imgur.com/RolVcfg.jpeg
https://i.imgur.com/RolVcfg.jpeg

[log.txt](https://github.com/Courseplay/courseplay/files/6204469/log.txt)

EDIT: Maybe just to clarify I'd like to drive the combine myself and have CP unload and transport to the silo.
EDIT 2: Just tried it with a unmodded combine issue seems to persist

**Comment by Tensuko** [comment]
Combine must be driven be Courseplay. 
https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ
