### ISSUE TITLE
Map : Kandelin. Issue : Harverster not beign unloaded.

### ISSUE THREAD

**Issue by LindavK1972** [Courseplay/courseplay#7037]
Hi there.

So, i'm on Kandelin, worked out a nice route from the field to my silo and back, activate mode 2 and nothing happens. In the Console it said : g_combineUnloadManager:getHasUnloaders(vehicle)False.

I'm using the Claas DLC, with the sTV Joskin Tipper.

Any idea's?

**Comment by Tensuko** [comment]
logfile ?
Combine must be driven my CP.
https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ

**Comment by LindavK1972** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6214218/log.txt)

**Comment by LindavK1972** [comment]
CP drives both unloading vehicle as combine.

**Comment by Tensuko** [comment]
Then we need a logfile with debugchannel 2, 3 and 11 active, start your combine and unloader (ofc assign the unloader to the combine) and let it run. If nothing happens, attach sceenshots and logfiles.

**Comment by LindavK1972** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6214337/log.txt)
I did what you asked of me and the tractor drove straight off the field.

It doesn't seem to assign a combine, even when i select field and then the combine.
Ran it with debugchannels 2,3 and 11. Logfile included, plus screenshot.
![FarmingSimulator2019Game 2021-03-26 21-53-20](https://user-images.githubusercontent.com/15148234/112691983-73843600-8e7e-11eb-9cac-4b378a6da2b4.png)

**Comment by Tensuko** [comment]
You did start it at nearest and first waypoint, if you on field, you can start it with 'unloading'.
Or what is not working exactly ?

**Comment by pvaiko** [comment]
You should set up an unloader course, seems like you are trying to use the harvester's course for the unloader?

**Comment by LindavK1972** [comment]
It works fine on Hopfach? But i'll try it on Kandelin again.

**Comment by LindavK1972** [comment]
Ow, and they are two different courses.

**Comment by Tensuko** [comment]
Try to remove all maps except the one you play and try again.
This is a Rule for mods folder: Only one map at the time!

**Comment by LindavK1972** [comment]
Copy... Will do!

________________________________
Van: Tensuko ***@***.***>
Verzonden: zaterdag 27 maart 2021 13:31
Aan: Courseplay/courseplay ***@***.***>
CC: LindavK1972 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Courseplay/courseplay] Map : Kandelin. Issue : Harverster not beign unloaded. (#7037)


Try to remove all maps except the one you play and try again.
This is a Rule for mods folder: Only one map at the time!

**Comment by Tensuko** [comment]
How is the status ?

**Comment by LindavK1972** [comment]
It works perfectly on Hopfach, just not on Kandelin.
________________________________
Van: Tensuko ***@***.***>
Verzonden: zondag 4 april 2021 19:00
Aan: Courseplay/courseplay ***@***.***>
CC: LindavK1972 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Courseplay/courseplay] Map : Kandelin. Issue : Harverster not beign unloaded. (#7037)


How is the status ?

**Comment by Tensuko** [comment]
That is strange...
Not sure why Kandelin make such trouble.
No Field is working or just a specific one ?

**Comment by Tensuko** [comment]
Closed due to inactivity.
Guess there is some Problem with the Map. -> Mod Issue.
