### ISSUE TITLE
Mode2 with "side offset" drives with an offset on the unload course

### ISSUE THREAD

**Issue by djnekkid** [Courseplay/courseplay#7038]
Hi AWESOME devs!

My mode2 unloaders seemed to way-to-often get stuck, while the mode1 (with a mode3 friend) never gets stuck.

With some investigation, it seems like the mode2 variant seems to drive with the same offset on its unload course.
The vehicles in this case is the stock Phenix 6x6 with the stock 59000L Krampe SB30/1070 trailer.

Is this a known problem, or is it just me?

The reason I use an offset, is that more often then not, the 'cart' seems to be too close to the combine. Atleast the ones I use, thats usually the 'top end' ones with 13m header.

ps. It also seems like the mode3 'cart' behave the same way.

![image](https://user-images.githubusercontent.com/65364380/112688125-b5aa7900-8e78-11eb-8dd6-01f92aa71de5.png)

**Comment by Tensuko** [comment]
Got nothing to do with offset setting.
Read here: #4595

**Comment by djnekkid** [comment]
Oh ...

I was just gonna add another picture here, so all in all, "Dont use this effin' thing" ? :)

![image](https://user-images.githubusercontent.com/65364380/112689505-b3491e80-8e7a-11eb-939e-6b048395ad45.png)

**Comment by Tensuko** [comment]
Or you try to fix it in your game files like written in the comment.
But I can tell you, there are better Trucks out there on the ModHub :)

**Comment by djnekkid** [comment]
The NMC Griffin have been a staple in my games as a "long haul" truck, but this map had a Phoenix, so i've used it as "field truck". Partially M2 and M3, so ... yea :D
