### ISSUE TITLE
Bale Collecting

### ISSUE THREAD

**Issue by patch110** [Courseplay/courseplay#7039]
Hi i have an issue where the vehicle collects a random amount of bales then just stops and i get an error in the log. im using ingame valtra n174 and anderson dlc trailer for round bales. Map is Four lakes farm by Stevie
[log.txt](https://github.com/Courseplay/courseplay/files/6215496/log.txt)

**Comment by Tensuko** [comment]
(Version: 6.03.00050) FS19_Courseplay
https://github.com/Courseplay/courseplay/releases/tag/6.03.00051
and should be duplicate, will be fixed in the next version #7014
