### ISSUE TITLE
Eine Kleine Frage...

### ISSUE THREAD

**Issue by Blumi39** [Courseplay/courseplay#7044]
HEY...Ich hab mal einer Frage bei was für einer Version ging das,das man den Drescher selber fährt und man den Courseplay Fahrer rufen kann nach dem man einen Course eingefahren hat für den Abfahrer?weiß das hier einer?

**Comment by Tensuko** [comment]
6.01.xxxxxx

**Comment by Blumi39** [comment]
6.01.00399 geht die?

 

Gesendet: Montag, 29. März 2021 um 16:36 Uhr
Von: "Tensuko" ***@***.***>
An: "Courseplay/courseplay" ***@***.***>
Cc: "Blumi39" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [Courseplay/courseplay] Eine Kleine Frage... (#7044)


 

6.01.xxxxxx
