### ISSUE TITLE
Kursgenerator erkennt die Hälfte der Felder nicht mehr

### ISSUE THREAD

**Issue by Mike1977** [Courseplay/courseplay#7048]
Für den neuen Mode 7 habe ich mir das letzte Update herunter geladen und wollte das gerade testen. Problem ist nur das der Kursgenerator jetzt die meisten der Felder nicht mehr erkennt wenn man sie anklickt und das das mit den Ballen laden auch nicht so funktioniert wie im entsprechenden Post beschrieben. Da sieht das Menü schon ganz anders aus...
![Mode7bug](https://user-images.githubusercontent.com/5852750/112903025-471f2280-90e7-11eb-8786-5ec1c2568eb5.jpg)

[log.zip](https://github.com/Courseplay/courseplay/files/6224742/log.zip)
[savegame2.zip](https://github.com/Courseplay/courseplay/files/6224749/savegame2.zip)

**Comment by Tensuko** [comment]
Keine Ahnung was du meinst.
Mit dem Kursgenerator hat der Mode7 nichts zu tun.
Aktueller Feldrand ist zum hinzufügen von Feldern, wenn du den Randkurs berechnet hast.
Eine Auswahl des Feldes wo du sammeln kannst, kommt erst, wenn du einen Abfahrkurs geladen hast (was hier im Bild nicht der Fall ist).
Eine log.txt brauchst du nicht zippen!

**Comment by Mike1977** [comment]
Danke für die Antwort erstmal... 
Also die log ging nicht hier her zu schieben, da stand was von "format wird nicht unterstützt" oder so ähnlich. Als Zip ging das dan problemlos.
Ich weis das der Kursgenerator nichts mit Mode 7 zu tun hat, das sind aber zwei Sachen die mir gleichzeitig nach dem letzten Update aufgefallen sind.
Was ich mit dem Kursgenerator meine, kann ich leider nicht auf dem Screenshot zeigen, denn wenn ich die Felder in der Map anklicke, passiert bei manchen nichts, und bei anderen wird die jeeilige Feld ID in den Generator übernommen. Wenn ich die Felder per Hand mit den Pfeilen oder dem Mausrad auswählen will, geht das dann hier erst bei feld 13 los und auch zwischendrin werden welche übersprungen. Das war vor dem Upfdate noch normal, und etwas anderes hat sich seit dem nicht geändert.
Und da mit dem Mode 7 war mein Fehler, ich hatte keinen Abfahrkurs geladen, deshalb konnte ich da auch nicht auswählen das er die Ballen sammeln soll.  Hinzu kommt, das ich bei "Feld" eben nicht die feldnummer auswählen kann, von dem Feld aus dem die Ballen liegen.

**Comment by Tensuko** [comment]
Mit dem Feld auswählen das kann am scrollen liege, versuch mal in verschiedene Richtungen zu scrollen. Rückwärts springt er bei mir auch um 2 manchmal und vorwärts gehts dann wieder.

Mit Felder auswählen im Generator da müssen wir mal schauen.
Felder Scannen am Start ist aktiv ?

**Comment by Mike1977** [comment]
Das liegt leider nicht am scrollen, denn ich kann ja in beide richtriungen scrollen, nur geht das bei 13 los und hört bei 32 auf. Danach kommt wieder 13. Außerdem kommt nach Feld 16 das Feld 18. Also überspringt er auch die 17. Feldscan am Start ist an wie bisher auch immer. Kannst du meinen Spielstand laden den ich gepostet habe und das verifizieren?

**Comment by Tensuko** [comment]
Schau ich mir morgen mal an.

**Comment by polosubtil** [comment]
Isn't it just because it displays your own fields ? Is that a mission or is it your field ?

**Comment by Tensuko** [comment]
Nicht dein Feld, also kannst du da auch keine Ballen sammeln.
Ansonsten funktioniert alles so wie es soll. (Auch im Kursgenerator).
Dein Save kann ich nicht probieren, da ich die Karte nicht habe (scheint eine modifizierte Felsbrunnen zu sein).

**Comment by Mike1977** [comment]
Ich habe den Spielstand jetzt mal kopiert und etwas herumprobiert. Tatsächlich kann man nur die Felder auswählen, die man besitzt, oder für die aktive Missionen laufen. Entweder war das vorher nicht so, oder es ist mir nicht aufgefallen, da ich außerhalb der Missionen nichts auf den Feldern zu suchen hatte. 
Nun habe ich allerdings einen Mod installiert, der es mir erlaubt auch das Stroh auf den Missionsfeldern zu sammeln, bzw zu pressen und dann die Ballen zu sammeln. Wie es aussieht erkennt Courseplay die Felder nicht mehr, sobald die Mission abgeschlossen ist, selbst wenn sie noch nicht bestätigt wurde, was dann ja die Felder zurücksetzt bzw alles löscht was drauf liegt. 
Wäre es möglich das soweit zu ermöglichen das man Courseplay (bzw den Kursgenerator) auf diesen Feldern noch so lange nutzen kann, bis man die Mission tatsächlich Abgeschlossen hat? (siehe Screenshot)
![sceen02](https://user-images.githubusercontent.com/5852750/113416140-f5b1b480-93c0-11eb-84bf-8901cec92241.jpg)

**Comment by Mike1977** [comment]
@Tensuko ich weis nicht ob dir das überhaupt noch angezeigt wird weil du es geschlossen hast, aber falls doch, wäre ich über eine Antwort sehr dankbar. :)
