### ISSUE TITLE
Overloader Issue

### ISSUE THREAD

**Issue by AussieFarmer70** [Courseplay/courseplay#7049]
My CoursePlay Overloader course is not unloading combines. I have set it all up with the overloader with a course the only issue I have is the only combine I have working is in Field 7 is only listed in Courseplay as being in Field 1 which it is no where near field 2 so the overloader isn't finding the combine. HELP PLEASE.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki
Try it again
