### ISSUE TITLE
The problem with the tractor for unloading the combine

### ISSUE THREAD

**Issue by SereshaMinasyan** [Courseplay/courseplay#7050]
Hello everyone, I apologize for my poor English. I have a problem with unloading the combine, namely, when a tractor or truck unloads the combine, they go into standby mode and wait for the combine to fill up, and they stop in the field, is it possible to change the waiting place? I will be very grateful for your help!

**Comment by Tensuko** [comment]
Screenshot ?
And have Avoid Fruit active on both, Combine AND Unloader!

**Comment by SereshaMinasyan** [comment]
> Screenshot ?
> And have Avoid Fruit active on both, Combine AND Unloader!

Here is a complete video of how I make the route. The problem is that the truck goes to a temporary parking lot (Еду на временную стоянку) and stops on the field, I need it to stop at a specific place behind the field and wait for the combine to fill up (Жду заполнения бункера)[https://youtu.be/_nKNl6rDkvg](url)

**Comment by Tensuko** [comment]
Sry buddy but that is FS17, wich we don't support anymore. You may try your luck here: https://github.com/pops64/courseplay/issues
@pops64 may have a look on that.
