### ISSUE TITLE
Question: Shovel Mode

### ISSUE THREAD

**Issue by DonBolli** [Courseplay/courseplay#7051]
I use this mode with a "Radlader" in the BGA with out any problems. I did exact the same thing for the manure at the cow pasture, from the documentation it should work, but it doesn't. The filling of the shovel works like a charm, but it doesen't do the unloading. What is diffrent to the BGA? I use a "Teleskiplader" instead of a "Radlader" and there is no trigger. But in both cases I don't use triggers, instead i use the parking position.

Any ideas? I couldn't get it to work just by reading the documentation.

**Comment by Tensuko** [comment]
Beide Varianten nutzen 3 Wartepunkte:
Wartepunkt 1: Start der Ladezone/Bunker
Wartepunkt 2: Ende der Ladezone/Bunker
Wartepunkt 3: Check für Trigger oder Trailer/fillNode
Der Abstand zwischen Wartepunkt 3 und deinem Ziel wird das Problem sein.
Wir brauchen einen gewissen Abstand, da wir mit der aktuellen Version uns zunehmend langsamer dem Trailer nähern.
Sollte das gleiche für Trigger sein.
Es bedarf meistens ein wenig probieren (am besten mit dem Editor) um das einmal rauszugfinden, später hat man den ungefähren Abstand raus (er muss nicht immer gleich sein).

Ansonsten bitte mal einen Screenshot machen und hier anhängen (drag and drop).

I hope german was ok due to your Word 'Radlader' :)

**Comment by DonBolli** [comment]
Deutsch geht auch, ich dachte englisch wäre einfacher für euch.

Ich habe es hingekriegt. Eine Frage noch, wenn ich ein Gerät in den Schaufelmodus nehme, funktioniert es erst wenn ich den Helfer einstelle und dann das Fahrzeug wechsle, wieso ist dies so?

**Comment by Tensuko** [comment]
Sry das verstehe ich nicht ganz.
Wann funktioniert was ?
Du hast also einen Radlader, Telelader oder Frontlader, wählst den Modus aus und was funktioniert erst wenn du den einstellst und Fahrzeug wechselst ?
Schreib uns bitte was du machst, was du erwartest, was du machen willst und was nicht funktioniert, so ist das leider nur Raten...

**Comment by DonBolli** [comment]
Ich wähle den Kurs, den Modus und stelle den Abfahrer ein, jetzt erwarte ich, dass er anfängt seine Arbeit zu erledigen - er macht jedoch nichts. Wenn ich jetzt jedoch das Fahrzeug wechsle, nimmt der Helfer seine Arbeit auf, ich kann danach auch wieder zurück wechseln.

**Comment by Tensuko** [comment]
Okay... logfile ?
Regnet es gerade ?

**Comment by DonBolli** [comment]
Nein es regnet nicht, das Wetter macht keinen Unterschied. Ich das ganze mal aufgenommen, vielleicht hilft es ja.

[Video](https://youtu.be/QrY3q38DirE)

[log.txt](https://github.com/Courseplay/courseplay/files/6254327/log.txt)

**Comment by Tensuko** [comment]
Update bitte mal auf die Version 00052 
https://github.com/Courseplay/courseplay/releases

**Comment by DonBolli** [comment]
Update gemacht, "Problem" noch vorhanden.

**Comment by Tom20214** [comment]
Duplicate #6992

**Comment by DonBolli** [comment]
Ich habe es heute nochmals gecheckt, weil ich die anderen "Problem" noch gar nicht bewusst kannte. Ist bei mir ebenfalls so, sobald ich das Fahrzeug gewechselt habe, kann ich die Schaufel nicht mehr manuell verstellen, ich nehme an dies ist identisch.

**Comment by Tensuko** [comment]
> 
> 
> Duplicate #6992

nicht wirklich...



> 
> 
> Ich habe es heute nochmals gecheckt, weil ich die anderen "Problem" noch gar nicht bewusst kannte. Ist bei mir ebenfalls so, sobald ich das Fahrzeug gewechselt habe, kann ich die Schaufel nicht mehr manuell verstellen, ich nehme an dies ist identisch.

Kannstdu genauer sagen, wann das sein soll ?
Weil ich kann es halt nicht nachvollziehen, meine Radlader arbeiten wie sie sollen und auch wenn ich sie entlasse kann ich danach alles selber machen.
Genauere Step by Step Anleitung mit welchem Gerät bitte.

**Comment by DonBolli** [comment]
[Video](https://www.youtube.com/watch?v=QwdIPv26Y8c)

**Comment by Tensuko** [comment]
Hmm so leider nicht, wie sieht der Kurs aus etc ?
Wie ist das also du kannst den Fahrer starten und dann die Schaufelpositionen so frei bewegen, ohne das der Abfahrer startet ?

**Comment by Tom20214** [comment]
@Tensuko  ich hab mal ein bisschen getestet und herausgefunden, das man die schaufel frei bewegen kann bei aktivierten CP Fahrer bis man aussteigt und wieder einsteigt dann läuft der Fahrer und man kann die Schaufelpositionen nicht frei bewegen.

**Comment by Tensuko** [comment]
@Tom20214 
Ok danke das könnte helfen.

**Comment by Tensuko** [comment]
@Tom20214 du könntest mit dem Duplicate sogar recht haben.
Scheint so als ob in beiden Fällen ein minimaler Input vom Spieler das losfahren vom Fahrer verhindert und das ist warscheinlich das Grundproblem in beiden Issues.
