### ISSUE TITLE
Deactivate Fertilizer Usage requires some fertilizer in tank for course to be run by helper

### ISSUE THREAD

**Issue by RonchiDonkey** [Courseplay/courseplay#7053]
As it says above, although it doesn't use the fert, it needs some present otherwise it will error with the work tool requires refill message. Not a big problem but something to look into if this isn't your intention.

![image](https://user-images.githubusercontent.com/81764868/113315656-008d2a80-936a-11eb-8910-64aac02a5f5f.png)

**Comment by Tensuko** [comment]
That means if there is no fert in the machine and you set the use of fert do deactivted, it still ask to fill up ?

**Comment by RonchiDonkey** [comment]
That is correct, if you have no fert even when fert is deactivated it will not run. So it checks to see if it is empty even if fert is deactivated.

**Comment by Tensuko** [comment]
Then I would like to see a logfile (attached)

**Comment by Tensuko** [comment]
Works like a charm.
![fsScreen_2021_04_04_18_47_24](https://user-images.githubusercontent.com/27344744/113515761-c0e75e00-9576-11eb-912e-74fe97925324.png)
And Settings off.
![fsScreen_2021_04_04_18_47_29](https://user-images.githubusercontent.com/27344744/113515777-d0ff3d80-9576-11eb-9848-c180d970e852.png)

**Comment by Tensuko** [comment]
Closed due to inactivity.
As I said it works like it should.
Buy the stuff is off, 0 fertilizer in machine, deactivated the function in CP Hud and done.
Tested also with precision farming.
