### ISSUE TITLE
Using semi trucks for silage

### ISSUE THREAD

**Issue by FuturisticMC** [Courseplay/courseplay#7054]
Why do trucks not work for silage? Whenever it is time to turn around the truck doesnt make a wide turn and gets stuck in traffic with harvester. Also the truck does not seem to avoid fruit when that is enabled.
Using latest version of cp
On the MIG map
https://gist.github.com/FuturisticMC/5e86eab3eb20ec7163f3c79e6b34d3e9

**Comment by Tensuko** [comment]
What Truck is it ?
Screenshot of the situation ?

**Comment by FuturisticMC** [comment]
Im using the lizard road runner. Should I use a cabover truck? I am trying to recreate the problem right now

**Comment by FuturisticMC** [comment]
For some reason on the first load it made 2 turn arounds not perfect but good enough that it wasnt a problem but on the second load the first turn around did this.
![20210401225237_1](https://user-images.githubusercontent.com/46466204/113375313-1afcdf00-933d-11eb-9de0-9484a5376cc0.jpg)

**Comment by Tensuko** [comment]
Ehm, sry buddy but thise sure can't work and we won't make this work.
That is some very special and mostly unrealistic scenario.
All you can do is try increase the turn radius and use another pattern for center part of the chopper course.
