### ISSUE TITLE
Unloader stopping when approaching Harrvester

### ISSUE THREAD

**Issue by wakka79** [Courseplay/courseplay#7055]
Hi all, 

I seem to have a new problem that happens to all my harvesters and unloaders.

Heres what seems to happen when the unloader is in front of the Harverster when called
1. Harvester stops and calls unloader
2. Unloader approaches, turns.....
3. And stops.... 

Happens multiple times, requires manual intervention and it only seems when the unloader is in front of the harvester. I.e. the unloader has to turn to come under the pipe. 

Thanks for the greatest mod for FS.

![20210402081306_1](https://user-images.githubusercontent.com/13468157/113366577-30e5c080-938c-11eb-86e5-878618fa93b8.jpg)

**Comment by Tensuko** [comment]
The combine does not continue, correct ?

**Comment by pvaiko** [comment]
And make sure you don't have any offset set. Log with channels 2, 11 and 21 and screenshot from behind the combine so we can see if the generated course is incorrect or it is fine just the truck is unable to follow it.

**Comment by wakka79** [comment]
I think that I solved it. In the Advanced Settings I turned on AI Turn Manouvers, Pathfinding in turns and Reversing for Pathfinding in Reverse. I will monitor and see how it goes. 

Thanks for the assistance.

**Comment by Tensuko** [comment]
Those turns have nothing to do with the Unloader.

**Comment by Tensuko** [comment]
When this is working for you now I think its okay.
There might be situations where the combine and truck stand on an edge case and getting stucked like that.
If this happens very often, I would also try to change the turn radius to have a smoother approach to the combine.
