### ISSUE TITLE
Game Controls Freezing when starting course then exiting vehicle.

### ISSUE THREAD

**Issue by Triplel40** [Courseplay/courseplay#7058]
Hello, I just started running into an issue where my controls freeze if I start driver on a course then leave the vehicle. The vehicle keeps driving, but I cannot move or do anything. If I open the pause menu I can't get out of the pause menu except by selecting the Courseplay vehicle on the map and getting back into it. If the driver is performing an action such as spraying, it stops spraying when the freeze happens, but keeps driving the course. Once the course finishes my controls come back again. 

I'm 2 seasons in on this save and haven't added or removed any mods lately, and this issue seems to have just popped up overnight. I've started removing mods to see if I might have an issue, but so far no luck. 

Log is showing this repeating while the error is happening:
2021-04-02 12:04 Error: Running LUA method 'update'.
2021-04-02 12:04 dataS/scripts/vehicles/Vehicle.lua(2920) : attempt to call method 'getCurrentHelper' (a nil value)

Anybody know where to start fixing this issue?

[log.txt](https://github.com/Courseplay/courseplay/files/6250786/log.txt)

**Comment by Tensuko** [comment]
You have several mods with Errors and some mods are not needed, like place anywhere can be thrown out when you have Global Company.
That is for sure a Modded Vehicle. That Error leads to GIANTS script and does not lead to CP.
