### ISSUE TITLE
Fahrer einstellen nach Fahrt mit AD funktioniert nicht

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#7062]
Hallo CP Team. Ich hab mir die neueste Version von Cp runtergeladen. Und dann stelle ich fest das ich bei der Feldarbeit keinen fahrer Einstellen kann. 

Version 6.03.00052

[log.txt](https://github.com/Courseplay/courseplay/files/6254083/log.txt)

MFG Mannie313

**Comment by Tensuko** [comment]
Schmeiß hiredhelper mal raus. Außerdem hast du strohbergung 2 mal drin

**Comment by Mannie313** [comment]
strohbergung hab ich nur einmal und nen mod der zusatzgebäude hat der genauso heist nur mit ner 2 dran. alles gut.

Hiredhelper kann ich mal testen.

MFG Mannie313

**Comment by Mannie313** [comment]
@Tensuko modus 4 düngen und säen geht trotzdem nicht nen Fahrer Einzustellen.

MFG Mannie313

**Comment by Tensuko** [comment]
Also ohne Error in der log können wir auch nichts machen.
Bei mir geht es jedenfals.

**Comment by Tensuko** [comment]
Hmm mach mal channel 4 und 15 an. Vlt sagen die warum er nicht fährt.

**Comment by Mannie313** [comment]
Ok kann ich dann machen

**Comment by Mannie313** [comment]
https://www.youtube.com/watch?v=u2MnPP7DKKk

[log.txt](https://github.com/Courseplay/courseplay/files/6254458/log.txt)

Bitte Sehr

**Comment by Tensuko** [comment]
Ist das ein 313 Vario ?
Wenn ja:
2021-04-04 13:27 :56 [dbg4 lp8595] 313 Vario: Finding AI markers of 313 Vario
2021-04-04 13:27 :56 [dbg4 lp8595] 313 Vario: 313 Vario has no AI markers, try work areas
2021-04-04 13:27 :56 [dbg4 lp8595] 313 Vario: 313 Vario has no work areas, giving up

Welches Tool ist das was du da dran hast ?

**Comment by Mannie313** [comment]
Was meinst du welches Tool

**Comment by Mannie313** [comment]
Das gleiche verhalten wie bei #7063 @Tensuko

**Comment by Tensuko** [comment]
Das ist kein Tool, das ist das Material.
Mod ja nein, was für ein streuer, welcher ist das.
Welcher Traktor usw...

**Comment by Mannie313** [comment]
Alles originale als mod.

Fendt300 und superfex800 miststreuer und ein justierbares gewicht.

**Comment by Tensuko** [comment]
Und geht es mit Vanilla Geräten ?

**Comment by Mannie313** [comment]
Nein ging nicht aber jetzt hab ich nen lua error drin.

Error: Running LUA method 'onCollision'.
F:/LS19_Mods/mods/FS19_Courseplay/Conflict.lua:111: attempt to compare nil with number

[log.txt](https://github.com/Courseplay/courseplay/files/6254966/log.txt)

**Comment by Tensuko** [comment]
Ist der gleiche wie in #7063

**Comment by Mannie313** [comment]
Dann nehm ich solange die vorgänger version bis die hier läuft. 

Ich hoffe ihr findet den fehler. wäre schade um die ganzen updates bisher.

MFG Mannie313.

PS: Fals ihr noch was braucht einfach schreiben.

**Comment by SebStu** [comment]
Hallo,

das Problem habe ich auch:
- der Traktor fährt durch Autodrive zum Feld mit aktivierter Übergabefunktion an Courseplay
- am Feld angekommen deaktiviert sich Autodrive, aber Courseplay wird nicht automatisch aktiviert
- der Courseplay Helfer lässt sich manuell nicht aktivieren. Erst nachdem Autodrive kurzeitig an und wieder ausgeschaltet wurde, kann man den Courseplay Helfer aktivieren und er verrichtet wie üblich seine Arbeit.

Bis jetzt konnte ich eingrenzen, dass das Zusammenspiel mit Autodrive bis zu eurem Update vom 27.3.2021 "Working width setting by 0.1 increments fixes #5997" bei mir auf jeden Fall funktioniert.
Bei Autodrive nutze ich die aktuelle Beta-Version vom 19.3.2021.

**Comment by Mannie313** [comment]
@Tensuko und @pvaiko Cp funktioniert nur nicht mit ad sondern ich kann auch mit der maussteuerung keinen fahrer einstellen und auch auf der num7 geht es auch nicht. Das es allgemein nur an AD hängt glaub ich ich net.

MFG Mannie313

**Comment by pvaiko** [comment]
@Mannie313 Cool, wenn du Schritt für Schritt beschreiben kannst wie man es ohne AD reproduziert, umso besser.

**Comment by pvaiko** [comment]
AutoDrive pull request created for this issue:
https://github.com/Stephan-S/FS19_AutoDrive/pull/1872

**Comment by Mannie313** [comment]
> @ Mannie313 Cool, wenn du Schritt für Schritt Schritte kannst du wie man es ohne AD reproduziert, besser.

So hab es nochmal probiert. Wen ich mit AD zum feld Fahre übergibt er nicht an CP. Drücke ich aber auf Abfahrer Einstellen mit der Maus passiert nix Drücke ich num7 Passiert nix. Lasse ich ihn durch AD ein stück nach vorne fahrer kann ich den Abfahrer mit der maus und der num7 einstellen.

Test Heute Mit dem Aktuellen CP 06.03.00052 d849d17 vor 3 stunden

[log mit Modfahrzeugen.txt](https://github.com/Courseplay/courseplay/files/6259840/log.mit.Modfahrzeugen.txt)
Fendt300 + Justierbares Geweicht + superfex800 alles mods. Mit AD Holzaschedünger (düngen) geholt zum feld gefahren AD schaltet ab und übergibt nicht an CP. Aber ich kann CP sofort starten nicht so wie gestern.

[log mit Originalfahrzeugen.txt](https://github.com/Courseplay/courseplay/files/6259842/log.mit.Originalfahrzeugen.txt)
Fendt300 + Justierbares Geweicht + superfex800 alles Originalfahrzeuge. Mit AD Holzaschedünger (düngen) geholt zum feld gefahren AD schaltet ab und übergibt nicht an CP. Aber ich kann CP sofort starten nicht so wie gestern.

Channel 4 +15 habe ich angemacht.

**Comment by pvaiko** [comment]
@Mannie313 ja, mehr können wir momentan nicht machen, ihr musst warten bis die AD devs mein Pull Request mergen.

**Comment by Mannie313** [comment]
ist ok wollte nur bescheid geben.

**Comment by pvaiko** [comment]
AD beta-testing branch hat den Pull Request gemerged: https://github.com/Stephan-S/FS19_AutoDrive/compare/beta-testing

**Comment by Mannie313** [comment]
Teste ich morgen mal. Danke
