### ISSUE TITLE
Cursplay läst sich nicht mit AD einstellen

### ISSUE THREAD

**Issue by RudiBergfeld** [Courseplay/courseplay#7063]
Das neuste Update Von CP läst sich nicht mit AD eistellen,
ich kann nicht mit Autodrive den Abfahrer zum Feld fahren und dann  von ad automatisch einstellen. Mit der Version 51 war das noch möglich.
[log.txt](https://github.com/Courseplay/courseplay/files/6254680/log.txt)

**Comment by Tensuko** [comment]
Habe ich gestern erst im Stream gesehen das es geht!

**Comment by RudiBergfeld** [comment]
ok was mache ich falsch ich habe das auf Vielen 4 fach maps gestestet es war immer so  mit gleichen Mods

**Comment by RudiBergfeld** [comment]
im Sp hab ich vergessen

**Comment by Tensuko** [comment]
Erst mal die Frage ist das v52 oder Master Branch was du da hast. Und du hast nen LUA Error drin.

**Comment by RudiBergfeld** [comment]
das ist die v 52 was kann ich gegen den Lua Error tun

**Comment by Tensuko** [comment]
Mehr Info, welches Fahrzeug, welches Gerät, welcher Modus.
Schon mit anderen Geräten und Fahrzeugen versucht in der 52

**Comment by RudiBergfeld** [comment]
op ich Gatis Trecker nehme oder mods  beides hab ich versucht Der modus war Feldarbeit, Düngen , Kalken, Spritzen und pflügen ich werde nun V51 mit gleichen mods Testen

**Comment by RudiBergfeld** [comment]
Ich habe das nochmal mit v 51 getestet mit den gleichen Mods  diesmal geht es  der Lua Error ist auch nicht da siehe log
[log.txt](https://github.com/Courseplay/courseplay/files/6254789/log.txt)

**Comment by Tensuko** [comment]
Uns interessiert nicht welche version geht, sondern womit und warum die 52 bei dir nicht geht.

**Comment by Tensuko** [comment]
2 mal gleiches Issue, mache hier zu. #7062
