### ISSUE TITLE
Helfer per Tastatur Start/Stop funktioniert nicht

### ISSUE THREAD

**Issue by IcemanGSXR** [Courseplay/courseplay#7064]
Seit der letzten Developer Version kann ich den Helfer nicht mehr per Tastatur Starten/Stoppen. Ich muß nun das HUD öffnen und kann dann den Helfer Starten/Stoppen. Gemäß Input Bindings ist der Key richtig zugeordnet.

**Comment by Tensuko** [comment]
Einmal mit neu zuordnen versuchen, ansonsten abwarten, wir überarbeiten gerade die keybinds, dann sollte das zuverlässiger laufen.
