### ISSUE TITLE
Question: mode 1 driver unload but dont leave automaticly.

### ISSUE THREAD

**Issue by candymant** [Courseplay/courseplay#7065]
If i do a transport with mode 1 de driver fill up and drive to the unloading trigger. Unloads and then i have to press continue driver before he leaves.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

I have high doubt that it is a cp error

**Comment by Tensuko** [comment]
Can't reproduce, works like a charm.

**Comment by candymant** [comment]
In earlyer versions this worked and now anymore. Can it be the vehicle than?

**Comment by candymant** [comment]
It is a concrete mixer that is provided with the map.

**Comment by candymant** [comment]
Or can it be the trigger anyone a idee.

**Comment by Tensuko** [comment]
Read the Wiki page.
