### ISSUE TITLE
Frage: Bahnversatz

### ISSUE THREAD

**Issue by DonBolli** [Courseplay/courseplay#7069]
Hallo
Ich verwende CP v 6.3.00052 und habe das Problem, das der Bahnversatz nicht funktioniert, habe ich etwas vergessen zu aktivieren?
Doku und Google haben mir nicht geholfen.

[Video](https://www.youtube.com/watch?v=piCB8Cy8j8M)

[log.txt](https://github.com/Courseplay/courseplay/files/6263872/log.txt)

**Comment by Tensuko** [comment]
Bahnversatz ist dafür auch nicht da.
Geräteversatz musst du nehmen, deine Geräteaufnahme ist schließlich links bzw rechts.
