### ISSUE TITLE
Frage wegen performance

### ISSUE THREAD

**Issue by BlackStar153** [Courseplay/courseplay#7070]
ist es möglich bzw ist was geplant das CP weniger performance frisst so das mehr fps möglich sind? auf einigen karten gerade unebenen flächen zeiht CP ein wenig leistung mehr  
Freu mich via feadbeck

**Comment by pvaiko** [comment]
Ich nehme an du meinst wenn der Pathfinder arbeitet; leider erlaubt uns der Game Engine keine multithreading, daher sind die möglichkeiten begrenzt, mit vertretbaren Aufwand ist keine signifikante besserung ist zu erwarten.
