### ISSUE TITLE
Problem with Courseplay in MP

### ISSUE THREAD

**Issue by Andriy52522** [Courseplay/courseplay#7072]
I wish you a good time of day, I want to inform you about the problem with the courseplay, namely: when using it in multiplayer, it works fine for me, but my partner just opens the menu and everything, further actions such as clicking something in this menu , and so on, not available to him, please fix this problem.
Thanks in advance for the reply.

**Comment by Mannie313** [comment]
ist er Farmmanager.

MFG Mannie313

**Comment by Tensuko** [comment]
'pls fix this problem'
We don't even know what exact Problem and have no logfile or anything.

https://github.com/Courseplay/courseplay/wiki

Also keep this in mind:
Note that the current version has limited multiplayer support!

**Comment by Tensuko** [comment]
Closed due to inactivity.
Reopen if we get the Requested Informations, pls read Wiki Page!
