### ISSUE TITLE
Abladepunkt funktioniert nicht

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#7073]
Hallo,
Ich lasse mit CP Ballen vom Feld sammeln, dazu habe ich mit CP einen Kurs vom Feld zu einem Ballenverkaufspunkt erstellt. Funktioniert erstmal. Am Verkaufspunkt habe ich einen "Hier-Abladen" Punkt erstellt. Leider lädt CP viel zu früh ab, ca. 3-4 Fahrzeuglängen zu früh. Habe es mit mehreren Verkaufspunkten probiert.
![fsScreen_2021_04_07_05_26_12](https://user-images.githubusercontent.com/21023840/113806960-8db5f200-9763-11eb-9c1f-81268e89d0f3.png)
[log.txt](https://github.com/Courseplay/courseplay/files/6268815/log.txt)
Woran kann das liegen?

**Comment by Tensuko** [comment]
Am 'hier abladen' Wegpunkt.
Der Muss weg.
