### ISSUE TITLE
CP Abfahrer Abstand

### ISSUE THREAD

**Issue by BlackStar153** [Courseplay/courseplay#7076]
Es wäre toll wenn CP fahrer mehr abstand zu einnader halten könnten wenn sie auflaufen 
![20210410183452_1](https://user-images.githubusercontent.com/79724679/114277465-98a2a800-9a2b-11eb-8520-b9537920fb5a.jpg)
![20210410182418_1](https://user-images.githubusercontent.com/79724679/114277466-99d3d500-9a2b-11eb-9c95-10b4ee291f2c.jpg)

**Comment by Tom20214** [comment]
logfile?

**Comment by Tensuko** [comment]
Sry, aber das ist zu unwichtig um dafür wieder extra Anpassungen zu machen...
