### ISSUE TITLE
Frage zu den Einstellungen des Abfahrers

### ISSUE THREAD

**Issue by SevenFifty1996** [Courseplay/courseplay#7079]
Hallo,
ich habe da eine Frage bezüglich Einstellungen des Abfahrers. Wenn ich einen Kurs erstelle zum verkaufen, dann steht dort immer 20 Wiederholungen.  Habe ich es nur noch nicht rausbekommen wie ich das ändern kann, oder lässt sich diese Anzahl nicht verändern? Es wäre ja schön, wenn ich das begrenzen könnte. Wenn ich z.B nur 5 Fuhren haben möchte. 
SevenF

**Comment by Tensuko** [comment]
Mausrad wenn Mauszeiger auf der Zahl.

**Comment by SevenFifty1996** [comment]
Danke für die schnelle Antwort. Auf die Idee bin ich nun wirklich nicht gekommen. Danke.....und weiter so. Ihr macht da echt einen tollen Job. Enorm was sich beim Abfahrer zwischen LS 15 und LS 19 getan hat. Klasse Jungs.
