### ISSUE TITLE
Pfad Finder Findet kein weg

### ISSUE THREAD

**Issue by BlackStar153** [Courseplay/courseplay#7081]
Problem besteht weiter hin #6917

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by BlackStar153** [comment]
was soll mit der wiki sein?

**Comment by BlackStar153** [comment]
@Tensuko  es hieß ich soll bescheid geben ob es gefixt ist und nein ist es nicht warum is die issu dann geschlossen???

**Comment by Tom20214** [comment]
> 
> 
> V 00051 ?
> debugchannel 2, 3 und 11 ?

**Comment by Tom20214** [comment]
https://github.com/Courseplay/courseplay/issues/6917#issuecomment-806466381
