### ISSUE TITLE
Frozen Courseplay HUD.

### ISSUE THREAD

**Issue by FriendlyMalana86** [Courseplay/courseplay#7086]
When I came back from a trip, I tried to get courseplay to run my sprayer. When I opened the hub I could hover over items but could not click them. I tried loading the My Courses page but that was frozen as well. I was soon to realize that every vehicle had this bug. I tried to reinstall courseplay but it did not seem to do anything. Before i left on my trip, I did not stop Courseplay before I exited the save game. If you know how to fix this I would be very grateful. I just bought FS19 for PC just to use this mod. Thank you, FriendlyMalana86.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

and what Sprayer.

**Comment by FriendlyMalana86** [comment]
The John Deere 4940 Self-Propelled Sprayer By Custom Modding. I was using the liquid fertilizer option from the mod.

**Comment by FriendlyMalana86** [comment]
Hello Tensuko, I will have to get back to you tomorrow due to the fact that I have work. I will find my logfile tomorrow, but I don't think I can activate a Debug Channel because the Courseplay HUD is completely frozen, other than i can hover over items and it will tell me what they are in the bottom left. For example, when I hover over the fieldwork icon, it says "Fieldwork" in the bottom left but I cant change modes when I click on it.Thanks for the help, FriendlyMalana86

**Comment by FriendlyMalana86** [comment]
Hello Tensuko, I have found my logfile and have uploaded it in Gist. Here is the link https://gist.github.com/FriendlyMalana86/af828a269d43b6080b619fec52b51101
I think this is what you are looking for. Thanks for the help, FriendlyMalana86

**Comment by Akita83** [comment]
I also have the problem that this error occurs all of a sudden #
[log.txt](https://github.com/Courseplay/courseplay/files/6304020/log.txt)

**Comment by Tensuko** [comment]
@FriendlyMalana86 
FS19_ClickToSwitch -> Is only needed if not use Courseplay Main Mod, as it is included.

Available mod: (Hash: 1123cb7ce142ddf82629a10715d60090) (Version: 6.03.00052) FS19_CourseplayBeta
Why renamed it to Beta ?!
If you just download it from here you have no need to rename something:
https://github.com/Courseplay/courseplay/releases
If you download the Branch at any unknown time, you may get into Issue and need more detailed testing.

Also I found this Errors:
2021-04-12 13:30 Error: Vehicle type 'FS19_X_BoniRob.boniRobSrpay' has unknown specialization 'FS19_X_BoniRob.FS19_precisionFarming.precisionFarmingStatistic'!

Beside that I haven't found any Error in your log that leads to a CP Error.

@Akita83 
Duplicate #7087

**Comment by Akita83** [comment]
sry for the double entry what can I do now against it have no mods in it that could cause problems

**Comment by FriendlyMalana86** [comment]
@Tensuko 
Thanks for the help. I was told to download it, extract it, and rename it FS19_Courseplay. This is the video link: https://www.youtube.com/watch?v=-7aovd8g8dI&list=PLNzbnKDWu5VOZXSi-TGu2Ls04wo7Ktvey&index=2&t=161s
The vehicle type BoniRob is a new PC only mod, it has a precision farming add on to take soil samples, but i do not have Precision farming installed. Thank you for all the help if will try to reinstall it without the beta name. Thanks for the help! Have a great rest of your day, FriendlyMalana86.

**Comment by Tensuko** [comment]
This is not the good way, stick to Release if you don't know about the Branches and the states.

**Comment by Tensuko** [comment]
@FriendlyMalana86 
is it working now ?
Or still have frozen HUD, when use that Sprayer ?
If so, logfile with that LUA Error.

**Comment by FriendlyMalana86** [comment]
Hello @Tensuko! Sorry I have not been able to get back to you, but I have some great news! I downloaded and enabled the latest release of Courseplay, 6.03.00053. I went into game an it is now running as intended. I have no clue what was going on, I guess I not installing it correctly. It works swimmingly now. I would like to thank you for the help because I'm new to the PC addition of farm sim and its very nice of you to help me. I did recorded a video of Courseplay a couple days ago, when it was still glitched. Would you like me to give you that video, if it could be helpful in any way?
Thanks a bunch,
FriendlyMalana86.

**Comment by Tensuko** [comment]
When it is working now it is fine :)
Thanks for the feedback.
