### ISSUE TITLE
Error: Running LUA method 'draw' - hud.lua:708: attempt to call method 'getName' (a nil value)

### ISSUE THREAD

**Issue by Sadbraiin** [Courseplay/courseplay#7087]
[log.txt](https://github.com/Courseplay/courseplay/files/6299037/log.txt)

Yeah I know we have Mods, perhaps too many but we try to play with them and out of nowhere came this.
We could speak german aswell.

**Comment by Tensuko** [comment]
BetterContracts und MoreMissionAllowed drin...
MoreMissionAllowed -> raus damit.

Wann genau tritt der Fehler auf ?
Würde mal versuchen ohne das zu spielen:
(Version: 1.0.2.0) FS19_BulkBuy 

Außerdem immer wichtig: nur eine Map im mods Ordner.

Die korrekte Fehlerbeschreibung ist:
2021-04-12 20:01 Error: Running LUA method 'draw'.
2021-04-12 20:01 D:/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/hud.lua:708: attempt to call method 'getName' (a nil value)

Nur lua:708 zu schreiben nützt nichts.

Außerdem hast du noch weitere Errors von anderen Mods drin, die solltest du erst mal aufräumen.

**Comment by andremeyer123** [comment]
delete inputbindings ,FS19_JohnDeere_8R_Series_Custom,FS19_johnDeerePack dann noch einmal neue log bitte

**Comment by andremeyer123** [comment]
delete FS19_manTGS41500HKL  ,  FS19_Volvo_FH16_750_Pack , mods/Holmerpack , ScaniaR730_8x4_fs19_COLAS , mods/FS19_Weba_6M  alle löschen

**Comment by Akita83** [comment]
have removed mods please see new log
[log.txt](https://github.com/Courseplay/courseplay/files/6310953/log.txt)

**Comment by andremeyer123** [comment]
versuch einmal Spiel starten ohne cp  und speichern dann wieder cp rein starten 
ist der fehler sofort da oder erst wenn du in ein vehicle gehst

**Comment by andremeyer123** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6311412/log.txt)
![fsScreen_2021_04_14_16_12_50](https://user-images.githubusercontent.com/70706468/114725213-9cd90900-9d3c-11eb-9b4c-70a354815b25.png)

**Comment by andremeyer123** [comment]
testing neues savgame

**Comment by Akita83** [comment]
As soon as I get in and press the right mouse button, the error appears

**Comment by andremeyer123** [comment]
test with map and urgently mods
new savegame please

**Comment by Akita83** [comment]
With a new savegame it works but if I go down memory and on it again it comes back error

**Comment by andremeyer123** [comment]
das ist ein mod bei dir , wir spielen auch auf eine server ohne fehler

**Comment by Tensuko** [comment]
I think your vehicles.xml still contains the information of one of the corrupted mods in your savegame.
You could try and check that file for missing information or remove the vehicles that you also removed from mods folder.

**Comment by Akita83** [comment]
I've done everything, but the error remains in the log

**Comment by andremeyer123** [comment]
log

**Comment by Akita83** [comment]
[Uploading log.txt…]()

**Comment by Akita83** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6313031/log.txt)

**Comment by Sadbraiin** [comment]
I just deleted all Courseplay courses and settings, reinstalled CP and now its running. i Think i deleted Towing chain with Hook aswell even i didnt used it.

**Comment by Akita83** [comment]
I noticed that I don't have a Cp folder in the directory, this is normal?

**Comment by Sadbraiin** [comment]
So normaly should there be a "CoursePlay_Courses" folder

**Comment by Akita83** [comment]
I don't have this one

**Comment by Tensuko** [comment]
I am sure that towing chain was the problem then.
Course don't do such stuff. No reason to delete them.

**Comment by Akita83** [comment]
I started a new savegame and again the same problem with the same entry

**Comment by andremeyer123** [comment]
log

**Comment by Akita83** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6318314/log.txt)

**Comment by Akita83** [comment]
Started yesterday

**Comment by andremeyer123** [comment]
das ist aber kein neues savegame da sind schon heuballen auf der karte  und fahrzeuge 
teste mal nur mit der karte  ad und cp alle anderen mods erstmal weg

**Comment by andremeyer123** [comment]
FS19_AutoIndicatorStopMod   
wo gibts diesen mod und was macht der
Test   : mods/GoldenSpike
          mods/FS19_AutoDrive
          mod: FS19_Courseplay     new savegame      log dann bitte

**Comment by Akita83** [comment]
This mod ensures that the turn signal goes off automatically
FS19_AutoIndicatorStopMod

**Comment by Akita83** [comment]
With a new savegame it works so far but I hope that it will still be caught so that I can use my old savegame

**Comment by andremeyer123** [comment]
log bitte

**Comment by Akita83** [comment]
from which savegame from the old or new

The new one goes so far

**Comment by andremeyer123** [comment]
of the new

**Comment by Akita83** [comment]
Das neue Savegame hat kein Fehler nur das alte

**Comment by andremeyer123** [comment]
Dort sieht man was für Mods geladen wurde und was schon auf der Karte ist . Um den Fehler weiter eingrenzen zukönnen.

**Comment by Akita83** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6336341/log.txt)

das Savegame läuft noch

**Comment by Akita83** [comment]
Das Savegame läuft ist aber ziemlich wieder am Anfang
[log.txt](https://github.com/Courseplay/courseplay/files/6336458/log.txt)

**Comment by Tensuko** [comment]
Du hast immer noch irgend eine Mod drin, die Errors schmeißt und somit diese HUD name Errors entstehen...

**Comment by Tensuko** [comment]
das kannst du mal machen

**Comment by Akita83** [comment]
[savegame1.zip](https://github.com/Courseplay/courseplay/files/6344191/savegame1.zip)

**Comment by Akita83** [comment]
https://filehorst.de/d/divCenoF

Das ist der Link zum Savegame vielen Dank schon mal

**Comment by Tensuko** [comment]
Ersetze mal die .xml in deinem savegame.
Außerdem schmeiß die CourseplaySettings.xml raus.
Starte dann mal ohne CP und wenn das geht, speicher und lade dann die neueste 00054 runter und pack die ins savegame.
[vehicles.zip](https://github.com/Courseplay/courseplay/files/6353228/vehicles.zip)

**Comment by Akita83** [comment]
Habe ich gemacht trotzdem der Fehler hier mal die Log
[log.txt](https://github.com/Courseplay/courseplay/files/6353411/log.txt)

**Comment by Akita83** [comment]
Error: Running LUA method 'packetReceived'.
2021-04-21 21:27 D:/home/sid_2520926/farmingSim_2019/profile/mods/FS19_Courseplay/courseplay_event.lua:105: attempt to index field 'vehicle' (a nil value)
2021-04-21 21:27 Error: Running LUA method 'packetReceived'.
2021-04-21 21:27 D:/home/sid_2520926/farmingSim_2019/profile/mods/FS19_Courseplay/courseplay_event.lua:105: attempt to index field 'vehicle' (a nil value)
2021-04-21 21:27 Error: Running LUA method 'packetReceived'.
2021-04-21 21:27 D:/home/sid_2520926/farmingSim_2019/profile/mods/FS19_Courseplay/courseplay_event.lua:105: attempt to index field 'vehicle' (a nil value)
2021-04-21 21:27 Error: Running LUA method 'packetReceived'.
2021-04-21 21:27 D:/home/sid_2520926/farmingSim_2019/profile/mods/FS19_Courseplay/courseplay_event.lua:105: attempt to index field 'vehicle' (a nil value)
Das sind die Logeinträge vom Dedi-Server

**Comment by Tensuko** [comment]
Das ist doch wieder ein anderer Fehler.
Hast du wirklich erstmal ohne cp gestartet ? Ich hätte auch mal Fahrzeuge verkauft, cp rein, fahrzeuge kaufen, um zu gucken, worann es liegt

**Comment by Akita83** [comment]
Habe die Mods raus gestartet alles Fahrzeuge verkauft, neues Gekauft rein gesetzt rechte Maustaste gedrückt und wieder der selber Fehler siehe Log
[log.txt](https://github.com/Courseplay/courseplay/files/6359332/log.txt)

**Comment by andremeyer123** [comment]
hast du discord

**Comment by Akita83** [comment]
Name:Akita #6938

**Comment by Tensuko** [comment]
So wie ist der Status hier ?

**Comment by andremeyer123** [comment]
Liegt wohl an seine Karte (close )
