### ISSUE TITLE
Grain Cart Issues

### ISSUE THREAD

**Issue by randalll375** [Courseplay/courseplay#7092]
The grain cart at times is all over the place - not following any type of "route" to get to a combine.  

The biggest problem is I use tandem trailers, and no matter what I do he is just stuck on the first P - he won't advance so for every truck I have to manually bring him up so he can finish emptying his cart.  Very annoying.  But thanks guys for the great product and your efforts, they are appreciated. 

-Randall375

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki
https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ
