### ISSUE TITLE
Eckverhalten bei ScharfenEcken?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#7097]
Hallo CP Team
Mit diesen CP einstellungen hier generiert cp ja scharfe Ecken mit turnstart und turnstop an 90grad Ecken:
![fsScreen_2021_04_18_09_39_53](https://user-images.githubusercontent.com/24860501/115138146-bcb54900-a02a-11eb-9c95-4f8d524cf59e.png)

auch bei stumpfen Ecken etwas über 90grad:
![fsScreen_2021_04_18_09_40_40](https://user-images.githubusercontent.com/24860501/115138218-2afa0b80-a02b-11eb-924a-640862b714fe.png)

sind diese Ecken aber noch stumpfer, generiert CP aber anstelle scharfer Ecken aber weiche Vorgewende Ecken:
![fsScreen_2021_04_18_09_39_36](https://user-images.githubusercontent.com/24860501/115138290-701e3d80-a02b-11eb-895b-281b749250f3.png)

mich würde interessieren, ab wieviel grad die umstellung erfolgt,und wo ich die für mich persönlich ändern kann.
ich möchte quasi bis 135grad scharfe Ecken und darüber erst weiche Ecken.
in welcher Datei und wo kann ich diese Grenze umstellen?

lg
andreas

**Comment by pvaiko** [comment]
Das ist leider nicht so einfach. Ob CP ein Turn generiert hängt davon ab, ob das Feldpolygon ein Vertex in der Ecke hat so dass die Edges minimum 60 Grad Winkel haben. Das ist nicht immer der Fall, manchmal scannt CP das Feld so dass es zwei Punkte nah an der Ecke entstehen, dann bleibt der Winkel unter 60. 

Darüber hinaus gibt es noch ein smoothing Algorithmus, aber wenn du Lust hast kannst damit hier rumspielen:
https://github.com/Courseplay/courseplay/blob/7c2e1460a2a73d2c313498346062965c141d279f/course-generator/cp.lua#L149
https://github.com/Courseplay/courseplay/blob/7c2e1460a2a73d2c313498346062965c141d279f/course-generator/cp.lua#L151
(Kommentare sind nicht aktuell, meine Schuld...)

**Comment by andreasthu** [comment]
Danke, @pvaiko 
habe nun die werte auf 
`		-- generate turns over 75 degrees
		headlandSettings.minHeadlandTurnAngleDeg = 35
		-- smooth only below 75 degrees
		minSmoothAngle, maxSmoothAngle = math.rad( 25 ), math.rad( 35 )
	end
`
eingestellt, scheint zu klappen.
wenn es eine Ecke trotzdem noch abrundet,  generiere ich einfach den Feldkurs solange bis dort eine ecke entsteht.
dann sind dort auch scharfe ecken.
lg und danke für die info
andreas
