### ISSUE TITLE
Abfahrer fährt ins Wasser und Häcksler macht nicht da weiter wo er aufgehört hat. 

### ISSUE THREAD

**Issue by Rykia101** [Courseplay/courseplay#7098]
![image](https://user-images.githubusercontent.com/82677051/115142793-f34b8d80-a043-11eb-94ee-cff9359a6f0c.png)
![image](https://user-images.githubusercontent.com/82677051/115142806-0c543e80-a044-11eb-8d29-e244ec4503e7.png)
![image](https://user-images.githubusercontent.com/82677051/115142839-2aba3a00-a044-11eb-8a53-0d4c643ec73f.png)
![image](https://user-images.githubusercontent.com/82677051/115142935-98fefc80-a044-11eb-9a25-ea46acd7e2a1.png)

Habe zwei Probleme. Zum einen ist ein Abfahrer nur noch gerade aus gefahren und somit letztendlich in den Fluss gefahren und der Mähdrescher ist nach dem wiedereinstellen des Abfahrers nicht da weiter gemacht wo er aufgehört hat sondern ist irgendwo in die Mitte vom Feld gefahren.

Beides ist passiert nachdem ich das Spiel gespeichert habe und neu gestartet habe. 

[CoursePlay_Courses.zip](https://github.com/netjungle/courseplay/files/6331054/CoursePlay_Courses.zip)
[log.txt](https://github.com/Courseplay/courseplay/files/6331072/log.txt)

**Comment by 60erjonny** [comment]
Hallo

Dein Abfahrer stand aber auf Überführungskurs und nicht auf Drescher abtanken...???
Und wie wieder der Drescher gestartet ist, sieht man in den Bild leider nicht...
Erster Wegpunkt, aktuellen Wegpunkt, nachsten passenden Wegpunkt,, naheliegendesten Wegpunkt...???

**Comment by Tensuko** [comment]
Video gucken:
https://youtu.be/sT3fKcI6wqw

**Comment by Tensuko** [comment]
Ein Daumen runter bringt dir auch nichts, wenn du Grundlegende Dinge verkehrt machst und ich dir ein Video zeige wo man sieht wie es geht.

**Comment by Rykia101** [comment]
Ein Daumen runter ist genau dafür da, eine Antwort, die nicht hilfreich ist als nicht hilfreich zu markieren. Aber mir ist das egal ob ihr jetzt eure Bugs fixen wollt oder nicht.
