### ISSUE TITLE
Tipper Can't Line Up with Combine

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#7099]
CP Version: 52
Map Hobbs Farm (not from Modhub)
Equipment: Generic Tata truck with Blacksheep Modding tipper, Modded Tiger 6L

See the video for how the truck can't get lined up. I think it is due to the angle the combine moved into. I think a tweak in how the combine stops would fix the issue. Making sure the entire combine is straight instead of crooked.

Video link: https://youtu.be/avDqGslBuTk

**Comment by Tensuko** [comment]
This is becouse of reverse of the Combine failed and not end up in a straight line.

What Truck is used, what is the offset for the unloader ?
Logfile with channel 2 and 11.

**Comment by lcc1211** [comment]
The truck is the in game Tata. I had to manually offset the truck because the default of CP had it driving directly into the side of the combine, so I moved it over to -2.0. For this log, I had to stop the truck so I could get the pipe in the fruit. I was running out of it and it wouldn't repeat.
[log.txt](https://github.com/Courseplay/courseplay/files/6331246/log.txt)

**Comment by Tensuko** [comment]
The Tatra got a general offset, wich is a failure in the vehicle. We told GIANTS but nothing happened so far.
That might be the reason of this bad driving to combine.

**Comment by lcc1211** [comment]
I switched the MAN truck and the issue didn't crop up again. I want to try it with a tractor and a tipper tomorrow on the same field and see how it does. Either the combine is making an error in how it moves away from the fruit, or the truck is attempting to align itself with the cab of the combine instead of driving under the pipe.

**Comment by Tensuko** [comment]
> or the truck is attempting to align itself with the cab of the combine instead of driving under the pipe.

No, it is simply a problem with the vehicle: https://github.com/Courseplay/courseplay/issues/4595

**Comment by Tensuko** [comment]
Issue of Vehicle, others works fine.
Ask GIANTS to fix it, they should already know whats wrong and how to fix it (linked in the Issue).
