### ISSUE TITLE
CP Hud öffnen mit Taste geht nicht (MP)

### ISSUE THREAD

**Issue by Easton97-Jens** [Courseplay/courseplay#7100]
Hallo CP Team,
wir haben heute auf die 6.3.53 geupdatet und kriegen seitdem das hatt nur noch über Rechtsklick auf wohl in den Einstellungen eine andere Taste hinterlegt ist. Wir kriegen das hatt auch ab und zu bei einigen Fahrzeugen erst gar nicht mehr auf außer wenn man es zurück gesetzt hat dann geht es wieder. Das ganze scheint ein MP Problem zu sein da ein Spieler das im SP ausbrobirt hat und es da funktioniert in der log sind keine Fehler zu sehen und es tauchen auch keine auf

Ich schätze eure Arbeit an diesem Mod.
Mit Freundlichen Grüßen 
Jens

**Comment by Tensuko** [comment]
logfile ?
Und was heist in den Einstellungen eine andere Taste ?
Die Maustasten sollten unangetasten bleiben, wer das nicht mit der Maus aufmachen will, deaktiviert das bei seinem Fahrzeug.
Die andere möglichkeit ist normalerweise die entf Taste, die sollte beliebig belegt werden können.

**Comment by Easton97-Jens** [comment]
Wir haben in im Menü die Taste Löschen drin stehen wenn wir jetzt auf Entf drücke passiert gar nichts und wenn ich da eine andere Taste hinterlege geht das auch nicht er akzeptiert keine andere belegung der Taste in den Einstellungsmenü.

**Comment by Tensuko** [comment]
Im SP ist alles so wie es soll, ja.
Müssen wir uns im MP anschauen, was da los ist.

**Comment by Bocephus717** [comment]
Hallo,

ich habe genau das gleiche Problem. Habe kürzlich und zum allerersten Mal Courseplay (Version 6.03.00053) auf meinen gemieteten Dedicated-Server (gamed!de) geladen, zusammen mit Autodrive. Im SP ist alles wunderbar, im MP werden mir jedoch keine CP-Funktionen im F1-Menü angezeigt und auch das Öffnen des CP-HUD per Tastendruck funktioniert nicht. Habe versucht dem HUD eine andere Taste zuzuweisen, ohne Erfolg. Hab dann versuchsweise Autodrive auf dem Server deaktiviert um einen möglichen Konflikt zwischen beiden Mods auszuschließen - auch ohne Auswirkung. Nur das Öffnen des HUD per rechter Maustaste funktioniert.

Vielleicht hilft euch ja ein zweites Log bei der Fehlersuche.

Gruß
Michael
[log.txt](https://github.com/Courseplay/courseplay/files/6361516/log.txt)

**Comment by Tensuko** [comment]
Fehler ist gefunden, sollte mit der näcshten Version gefixt sein.

**Comment by Dragonfly1982** [comment]
Besteht die möglichkeit das mal zu testen?

**Comment by filonb** [comment]
There's still a problem in v6.03.00056. Actions are getting triggered on the wrong player. When I click a button, my friends ui opens. When he opens the ui, my cursor gets unlocked, etc.
