### ISSUE TITLE
The tractor and its tipper want to pass in front of the harvester

### ISSUE THREAD

**Issue by sikiang** [Courseplay/courseplay#7102]
Hello Everyone,

I have install the last version (53) and too many time, harvest is stoped because tje tractor want to pass in front of the harvester

![image](https://user-images.githubusercontent.com/49972601/115250230-aa6e0480-a129-11eb-8445-46af486755b2.png)

with version 52, there was no this problem and the vehicle passed behind the harvester

![image](https://user-images.githubusercontent.com/49972601/115251045-70e9c900-a12a-11eb-835e-1e5d97a9b5af.png)

**Comment by sikiang** [comment]
And second problem : 
![image](https://user-images.githubusercontent.com/49972601/115252956-38e38580-a12c-11eb-9497-bec9fed2de76.png)

![image](https://user-images.githubusercontent.com/49972601/115253004-4436b100-a12c-11eb-8821-e5f7607b4f29.png)


When it's the start of the row the truck cannot align correctly whith harvester

**Comment by Tensuko** [comment]
Your first Problem was also with 52 and happens becouse we have a lot of space between fruit and combine. Should have a look if we can improove this anyway. ( @pvaiko I still got that sticky in DC )

Your second Problem is the too big Truck, but this MAYBE could work when you increase the turn radius (even I don't see why ppl unload with such a big truck...).

**Comment by sikiang** [comment]
Ok thanks for the answer.

**Comment by mdano01** [comment]
I also have noticed the issue of the tractor wanting to turn in front of the combine. Would it be possible to tell the tractor to turn to the opposite side that it's unloading on? so if it's unloading on the right, turn left when starting to pull away to allow path finding to route behind the combine or allow the combine to pull forward enough that the tractors detects it enough to route around? Just a though I had while trying to figure a way around the issue.

**Comment by Tensuko** [comment]
Should not happen anymore, tested some unloading and provoked this.
