### ISSUE TITLE
Module Express harvester recognised as combine harvester

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#7103]
Hi,
having the problem with CP6 6.03.0053 that it seems to recognise the Module Express cotton harvester as a combine harvester. Stops the vehicle at 95% and waiting for a unloader instead of pulling out the cotton bale at 100%.
Look at last line of log:

> 2021-04-19 17:38 :20 [info lp1797] Module Express 635 (#1): Could not find implement with pipe

[log.txt](https://github.com/Courseplay/courseplay/files/6337321/log.txt)

![fsScreen_2021_04_19_17_53_55](https://user-images.githubusercontent.com/21023840/115266179-469f0800-a138-11eb-9f1d-4464ac1f5bea.png)

**Comment by Tensuko** [comment]
[log combine.txt](https://github.com/Courseplay/courseplay/files/6337853/log.combine.txt)

**Comment by Tensuko** [comment]
Fixed with 00054.
