### ISSUE TITLE
 Error: Running LUA method 'draw'.FS19_Courseplay/hud.lua:723: attempt to call method 'getName' (a nil value) 

### ISSUE THREAD

**Issue by Akita83** [Courseplay/courseplay#7107]
[log.txt](https://github.com/Courseplay/courseplay/files/6338221/log.txt)

**Comment by Tensuko** [comment]
Wie wäre es mal mit etwas mehr Info ?
https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
Das klären wir dort: #7087
