### ISSUE TITLE
Grimme Varitron 470 funktioniert nicht.

### ISSUE THREAD

**Issue by Strawberry93** [Courseplay/courseplay#7110]
Hallo allerseits,

ich wollte den Grimme Varitron 470 für mein Kartoffelfeld benutzen, nur funktioniert die Maschine nicht. Der Kartoffelvollernter schaltet sich zwar an nur senkt sie sich nicht.

Mfg  Strawberry93

**Comment by Tom20214** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
Mode6 und Implement
[log combine.txt](https://github.com/Courseplay/courseplay/files/6340956/log.combine.txt)

**Comment by pvaiko** [comment]
@Tensuko seems to be the wrong logfile.

**Comment by Tensuko** [comment]
Fixed with 00054.
