### ISSUE TITLE
Big M 450 doesn't work with v6.03.00053

### ISSUE THREAD

**Issue by BlueElement2** [Courseplay/courseplay#7112]
Hi,

first of all, i like your program and use it in my private sessions.

One step to move from courses in the savegame to central saved courses, caused a bit work, since no saved way was found anymore. I think it's good if you want to start with the same map once again and with a different savegame. 
But it is work if you need to build your buildings on the same position to work.

**Bug:**
When you use the BIG M 450 for gras with version v6.03.00053, the tools doesn't go down to the earth anymore.
It drives with the tools, in a bad position:
![Course Big M 450 doesn't work](https://user-images.githubusercontent.com/82874172/115374588-47ce4480-a1cd-11eb-9bee-6c0d694c8afc.JPG)

This worked well with v6.03.00052, so i went back to this version. 
![Course Good](https://user-images.githubusercontent.com/82874172/115374627-50267f80-a1cd-11eb-9cfd-486e2cd3179c.JPG)

Please try to fix it.

Best regards

BlueElement 2

**Comment by Tensuko** [comment]
#7110
Same Problem, I think I know the Problem.

**Comment by Tensuko** [comment]
Fixed with 00054.
