### ISSUE TITLE
Shovel Mode

### ISSUE THREAD

**Issue by DonBolli** [Courseplay/courseplay#7116]
Ich habe den Helfer mit diesem Kurs schon mehrfach arbeiten lassen, ohne Probleme. Er hat diesmal ca. 50% weggeschaufelt, perfekt. Jetzt nur noch die mitte. Was ist hier falsch?

![image](https://user-images.githubusercontent.com/43571844/115587359-e4780b80-a2cd-11eb-993c-65b7aaf9d9bd.png)

**Comment by huffert** [comment]
@DonBolli: das ist die NF Marsch, oder?
könntest du mal deinen Kurs hier zeigen?

ich versuche das jetzt schon seit Tagen an der BGA Süd mit dem gleichen Radlader und Magsi Schaufel, 
bei mir will der partout nicht abkippen, bleibt immer paar Meter zuvor stehen.

Danke und Grüße

**Comment by Tensuko** [comment]
Bitte mehr Überblick über den Bunker und Kurs WP anzeigen (und bitte nicht die dbg, sondern die 3 Punkte aktivieren!)
Meistens liegt der Grund darin, dass er versucht in der Linie einen Teil auf zu nehmen was am weitesten vorne ist, aber nicht aufgenommen kriegt, dann versucht er es halt immer wieder.

Schaufel weiter runter, oder es ist ein Problem vom Bunker.

**Comment by DonBolli** [comment]
Wie gesagt, Kurs hat schon mehrmals funktioniert. Die Schaufel habe ich zu beginn einaml gemacht, danach nie mehr.

![1](https://user-images.githubusercontent.com/43571844/115606880-90c4ec80-a2e4-11eb-959f-c0e76102f362.png)

-----------------

Ja ist die NF Marsch, 4 fach OG v2.6

![image](https://user-images.githubusercontent.com/43571844/115607033-bc47d700-a2e4-11eb-8595-a27fd2a47ee3.png)

**Comment by Tensuko** [comment]
Wir haben daran nichts geändert in den letzten Versionen und wie ich sagte, es ist genau dieser markierte Bereich, den wir als den ersten Haufen erkennen (er ist am dichtesten an uns dran) und der ist im Boden oder die Schaufel kann das Zeug aus anderen Gründen nicht aufnehmen. Somit ist das aber immer wieder das Ziel, was zu diesem 'Canyon' führt.
Schauflhöhe anpassen, selber probieren ob man das überhaupt wegnehmen kann. An CP liegt es aber nicht.
![schaufel](https://user-images.githubusercontent.com/27344744/115673001-6c045f80-a34c-11eb-97c3-11bbac6003da.png)

**Comment by DonBolli** [comment]
Verstanden. Ich verwende CP v6.03.00054, welche Schritte könntest du mir empfehlen, bisher hat es ja auch funktioniert mit genau diesem Kurs und diesen Einstellungen. @Tensuko

**Comment by huffert** [comment]
@DonBolli: dein Kurs vor der Abladung würde mich als Screenshot noch interessieren.
machst du mir dazu noch einen? will mal gucken, wo du deinen P -Punkt gesetzt hast.

Danke

**Comment by Tensuko** [comment]
@DonBolli es ist keine exakte Wissenschaft, da kann sonst was passiert sein warum das Zeug nicht aufgenommen werden kann.
Wie gesagt, schau an ob du es aufnehmen kannst, wenn ja, Schaufelposition anpassen.
Fahrzeuge reparieren, was macht der Füllstand vom Diesel, hat sich das Gewicht beim Fahrzeug also verändert ?
Man kann das tatsächlich sehen, dass die Schaufel nicht immer 100% an die gleiche Stelle kommt und das hat einfach viele EInflüsse.

**Comment by DonBolli** [comment]
@huffert 
![2](https://user-images.githubusercontent.com/43571844/115781364-90972080-a3ba-11eb-8542-c23bdc3b53ff.png)

@Tensuko 
Danke, ich achte mal auf alles, ich habe gesehen, das der Tank bald leer ist. Das dies auch Einfluss haben kann wusste ich nicht.
