### ISSUE TITLE
Fuel and DEF no being consumed

### ISSUE THREAD

**Issue by Kevoman** [Courseplay/courseplay#7118]
I'm not seeing the fuel or DEF being used . Have only done field work so far. But the stats show fuel is being consumed.
![Farming Simulator 19 4_21_2021 1_19_17 PM](https://user-images.githubusercontent.com/45241108/115623978-cea71e00-a2ae-11eb-84db-0ca831129faa.png)
![Farming Simulator 19 4_21_2021 2_34_00 PM](https://user-images.githubusercontent.com/45241108/115623988-d1a20e80-a2ae-11eb-9ea3-a1e05fa75309.png)

**Comment by Tensuko** [comment]
Game options for Helper Fuel use ?!
That is not about CP...
