### ISSUE TITLE
Vehicle collisions on field.

### ISSUE THREAD

**Issue by Kiraxon** [Courseplay/courseplay#7119]
Hi,

First I want to say I think Course play is amazing and I commend you for implementing this as an option to Farm Sim players. 

I feel the combine unload option might need a bit a love. The tipper or seems to stop and gets in the way. As an example lets say it unloads the first combine on the course, it will sit and it waits for another call. The issue is that it will sit in one spot and as the next combine approaches it will block the oncoming combine and cause a colision or a stop. As a suggestion, maybe it can detect other oncoming vehicles and move to the side. It's not an easy task to solve as just thinking about it I could see how it could impact other courseplay pathing options.

The other concern, is the offload for combines. It will pull out in another field area and an oncoming combine will run into it while the offload is happening. The minimum distance option that is available, could you change this to detect what's in front help this scenario?

Here is an image

![image_2021-04-21_185901](https://user-images.githubusercontent.com/82987665/115644548-a2ea5f00-a2d3-11eb-9622-7492e1935980.png)

I am new to CoursePlay so I will keep playing around to see if find a sweet spot.

**Comment by Tensuko** [comment]
Activate avoid fruit.

**Comment by Kiraxon** [comment]
@Tensuko Using symmetric lane change option seems to help. with the combine collisions thank you for mentioning that. I'll continue to use that option and hopefully my combines will continue to behave themselves.

**Comment by Tensuko** [comment]
Good.
And as I said, avoid fruit must be one for propper unloading.
Headlands (at least 2) should help as well.
Will close this one, as it is not a real error, more a how to set it up.
