### ISSUE TITLE
CP loads courses by itself, although <loadCoursesAtStartup active="false"/> is set.

### ISSUE THREAD

**Issue by TheMoadip** [Courseplay/courseplay#7123]
Hello.
The current release is installed. However, I also had the problem under the previous versions. I have read the listings here in Github with the incompatible mods. I don't have any of these in my mod folders. 
I have a separate mod folder for each map and use the ModFolderManager.

Short explanation:
When I end a savegame, I stop still active CP helpers, delete the course and close the HUD.
When I open the savegame again, the courses are loaded again in most CP helpers (with the HUD still closed). I have this on all the maps I play. 

This is particularly annoying on the Wild West as there are a lot of CP helpers running there. The start of the Wild West is always a matter of luck for me. Most of the time the whole game crashes and can only be ended via the TaskManager. When it does start, it usually takes more than 30 minutes.

I would be very happy about any support in this matter, as I would like to play WW again.
If you need any further information, I would be happy to help.

Many thanks in advance.

PS: This text was translated by a programme, as I normally speak German and the English from my school days is a long time ago.

**Comment by Tensuko** [comment]
Schreibe lieber in Deutsch.
Und als aller erstes: logfile ?

**Comment by TheMoadip** [comment]
Danke für Deine Antwort.
In den Hinweisen stand, dass es besser ist in englisch zu schreiben - darum mein Text. 😇😉
Wovon möchtest Du ein Logfile? Von einem erfolgreichen Start mit einer beliebigen Karte, oder von dem erfolglosen Start der WW?

Ich spiele derzeit die Italy Light, die Giants Island 2011, die Irgendwo in Thüringen und die WW.

**Comment by Tensuko** [comment]
Egal wovon.
Info zum Setting: Lade kurse bei Spielstart ist nur, dass die Kurse die du gespeichert hast nicht geladen werden, das hat nichts mit den Kursen zu tun, die im Fahrzeug sind.

Wichtig wäre zu wissen, wenn du die Kurse aus den Fahrzeugen raus nimmst, speicherst du dann noch mal bevor du das savegame aus machst ?

Weil speichern und dann die Kurse raus nehmen sollte gar nicht gehen.

**Comment by TheMoadip** [comment]
Ich habe gerade noch ein neues Logfile erstellt. 
Vor beenden des aktuellen Spiels stoppe ich CP-Helfer auf dem Feld, damit ich den Punkt habe, an dem beim nächsten Start weitergearbeitet werden soll. Beim Drescher ist das ja noch egal, aber wenn ich dünge oder Stroh abfahre, dann nutze ich auf der Straße AD. Dann wird in dem betreffenden Gerät auf der Registerkarte "Abfahrhelfer Steuerung" mit dem kleinen x im Kreis der Kurs gelöscht und das CP HUD mit der Taste Entf geschlossen. Das geschieht mit allen CP-Helfern. Auch AD-Helfer werden gestoppt. Dann erst speichere ich das Spiel und beende es.
Beim nächsten Spielstart  ist bei allen CP-Geräten das HUD zu. Wenn ich das HUD öffne, ich bei manchen Geräten der Kurs von dem Feld wieder drin, bei manchen nicht. Es kommt auch vor, dass der Kurs von einem anderen Feld geladen ist. Siehe Screenshots in der Anlage. Bei jpg-01 stand der Drescher auf F12, welches ich mit AIVE gedroschen habe. Und in CP war F39 geöffnet, welches ich vor F12 gemacht hatte. Bei jpg-02 stand der Trecker auf F23, welches fertig gepflügt war, CP hat beim Neustart aber F45 geladen, welches vorher dran war.

Für einen Test-Start der WW hatte ich gerade keine Zeit.

Ich hoffe, die Angaben helfen Dir weiter.

![01 Drescher steht F12 - CP auf F39](https://user-images.githubusercontent.com/83033560/115958380-8df61180-a507-11eb-8695-49d2097358a5.JPG)
![02 Trecker steht F23 - CP auf F45](https://user-images.githubusercontent.com/83033560/115958381-8e8ea800-a507-11eb-9edb-2f502c27a4ce.JPG)
[log.txt](https://github.com/Courseplay/courseplay/files/6369552/log.txt)

**Comment by Tensuko** [comment]
Dezenter Hinweis:
https://github.com/Courseplay/courseplay/releases
Wird das Problem warscheinlich nicht lösen, aber:
https://github.com/Courseplay/courseplay/wiki

**Comment by pvaiko** [comment]
(One of the reasons we prefer to use English is that users who do not speak German can look up old issues and we can link issues with explanations)

So for this problem I need a simple, step-by-step description of how to reproduce the issue.

**Comment by TheMoadip** [comment]
Because of the hint in the wiki, I had written my first text in English. It was only when Tensuko pointed it out that I wrote in German.

Reproducing the error is a little difficult because it never occurs exactly the same way. 

I first noticed it on the map WildWest. The further I got in the game, i.e. the more fields were being worked on at the same time by CP helpers, the longer the game took to start. 
Thanks to a hint from Mario Hirschfeld in one of his WW videos, I then took the following steps on WildWest and all other maps before ending the game:
- dismiss the CP helper on the field,
- clear the course,
- close the HUD.
If, for example, a tractor with a fertiliser spreader is on its way to refuel via AD, I wait until it is back on the field at the last point worked on, so that when I restart the game I still know where it last left off.

Before saving, I jump through all the vehicles again to make sure that all the courses in the vehicles concerned have really been deleted. I then see the message "No course loaded" in the activated mini-display.

Then I save the game and quit it.

If I then restart the game and load the last score, there are three variants:
1) No course is loaded, as it should be. This happens with some of the machines, but repeatedly with others. 
2) Picture 1 above concerns a combine harvester that is on field 12 of the map Italy Light, and that previously worked there with AIVE. Now it has loaded the course from field 39. I had worked on field 39 before field 12 and was already finished. And when I changed the fields, the course was deleted.
Similar to a tractor with a plough in picture 2.
3) Some of the machines then loaded the course from the field they were on by themselves. So the course that I took out before I quit, and that I then want to continue to use.

I sent the log file from the Italy Light because I only have max. 2 CP helpers and 1 AD helper running there and the map still loads in a "normal" time.

The last but one time I started the WW, it took about an hour. Last time I aborted the start attempt after 20 minutes because I didn't feel like waiting that long.
When starting the WW, it can also happen that the entire game freezes and I have to end it via the task manager.

I experienced something similar with Landownunda. I don't play it any more because the loading time got longer and longer, even if I deleted the courses in the helper before the end.

----

To test the whole thing again and reproduce the error, I have just tried something.

From the Courseplay courses folder in the MyGames folder, I tried saving all the saved courses in the WW and also the courseManager.xml in another folder and deleting them.
The subsequent start of the WW went smoothly and very quickly.

Then I copied the courses and the courseManager.xml file back into the original folder.
To my surprise, the WW now started as quickly as without the courses. 
And there was no course loaded in any of the vehicles.

At first I thought, why did I write the whole thing now, I didn't just dream this after all.
However, I know this kind of demonstration effect very well. Whenever I have had an IT problem at work, it has never occurred when the technician was on site to look at the fault.

So next I started the map Irgendwo in Thüringen. There are numerous helpers there too. In three out of 10 vehicles the last used course was loaded, the others were without course. Nevertheless, the start went much faster than at the last attempt.

----

That's as far as I can report on this.
It has become a long text, but I don't know how to make it shorter.


I will now follow up on Tensuko's nice hint that I do not have the very latest version on my computer in order to update CP.

The new log file in the attachment is from the last three start-up attempts mentioned earlier.

[log_WW.txt](https://github.com/Courseplay/courseplay/files/6370292/log_WW.txt)

**Comment by pvaiko** [comment]
> PS: This text was translated by a programme, as I normally speak German and the English from my school days is a long time ago.

Sorry, das habe ich vorhin nicht gesehen.

Mittlefristig ist https://github.com/Courseplay/courseplay/projects/14 die Lösung für dieses Problem, mal sehen ob wir da eine Möglichkeit haben mit geringem Aufwand eine signifikante Besserung erreichen.

Dein Log hat nur ein Startversuch.

**Comment by TheMoadip** [comment]
Es ist für mich "mehr Aufwand" die Texte hier in englisch einzustellen, allerdings kann ich verstehen, dass für andere User einfacher ist.
Projekt 14 lies sich gut, bin mal gespannt.

Ich habe dann noch mal die WW gestartet (3. Versuch nach der Aktion mit dem Ordner). Der Start lief wieder normal. 
2 Geräte hatten wieder einen Kurs drin, obwohl ich bei den 2 vorherigen Starts keinen einzigen geladen hatte.
Das anschließende laden der Kurse war schwierig. Ich habe Feld 17 (das größte auf der WW) mit Feldrandkursen in 5 Teilbereiche aufgeteilt, da ich weiß, dass CP das gesamte Feld nicht berechnen kann. Das laden des 1. Teilkurses (Drescher) dauerte gut 5 Minuten. Im Task-Manager wurde schon angezeigt, dass das Programm nicht reagiert. Ich wollte gerade den Task abbrechen, da lief es wieder und der Kurs war drin. Dann habe ich Feld 60 einen Drescher angestellt, das dauerte "nur" rund 3 Minuten. Als ich dann im zweiten Drescher auf Feld 17 einen weiteren Teilkurs laden wollte, habe ich 10 Minuten nachdem der Task-Manager wieder "keine Reaktion" zeigte, den Task und damit das Spiel beendet.

Sorry wegen dem Log. Ist mir schon ein paar mal aufgefallen, dass das Log nicht vollständig ist. Die hochgeladenen Datei extra zu prüfen habe ich versäumt.

Derzeit bereite ich auf der Feldbrunn mit Standartmaschinen einen Test vor, um zu sehen, ob dann die Kurse auch wieder geladen werden. Laut dem Wiki würde ich den Debug-Cannel 19 aktivieren. Habt ihr sonst noch einen Channel, der aktiviert werden sollte, oder andere Hinweise, wie ich das so einrichten kann, dass Ihr nützliche Infos daraus erhalten könnt?

**Comment by Tensuko** [comment]
Versuch mal die neueste Version und führe den Command aus.
Das wird zwar eine ganze Zeit dauern, aber danach sollte das laden des Spielstandes um ein vielfaches schneller gehen:
https://github.com/Courseplay/courseplay/releases/tag/6.03.00057

**Comment by pvaiko** [comment]
Oder alte Feldkurse löschen, neu generieren und speichern, das dauer vielleicht nicht so lange ist aber mehr arbeit.

**Comment by TheMoadip** [comment]
Vielen Dank für Eure Hilfe!!
Ich hatte mit der v6.03.00055 nach meinem letzten Post gearbeitet, jedoch auch wieder die Probleme.

Jetzt werde ich es mal mit der v6.03.00057 versuchen. Vielen Dank dafür.
Allerdings werde ich es nicht mit dem Command machen, sondern alle alten Kurse löschen und jeweils neu erstellen.
Errscheint mir sicherer. Und da sich auf einigen Karten eh die Arbeitsbreiten von ein paar Maschinen ändern, weil ich andere Maschinen verwenden will, müsste ich diese Kurse eh neu machen.
