### ISSUE TITLE
AD->CP handoff not working

### ISSUE THREAD

**Issue by crcarmichael** [Courseplay/courseplay#7125]
I recently updated both Courseplay and Autodrive to the latest available versions... now the handoff from AD to CP doesn't work at all. Vehicle gets to the AD target and nothing happens. If I click Drive Course, off he goes.
Any way to figure out if this is a CP or AD issue?

**Comment by leo32128fs** [comment]
same thing here

**Comment by Tensuko** [comment]
What part exactly ?
When AD reaches Field Waypoint and should hand over to CP ?
Is AD still running, or no Driver active at all ?

I know that our addition for AD is working fine, as we tested it in Version 1.0.0.7 of AD (self modified).

logfile ?

**Comment by crcarmichael** [comment]
> What part exactly ?
> 
> When AD reaches Field Waypoint and should hand over to CP ?

Yes.

> Is AD still running, or no Driver active at all ?

Well, I can click on Drive Course and it goes, so I assume AD has released.
> 
> I know that our addition for AD is working fine, as we tested it in Version 1.0.0.7 of AD (self modified).
> 
I'm using 1.0.0.8 of Autodrive.
> 
> logfile ?

I'll grab it next time.

**Comment by andremeyer123** [comment]
hast du diese version ?       https://github.com/Stephan-S/FS19_AutoDrive/tree/beta-testing

**Comment by BlueElement2** [comment]
Same issue, the Amazone opens, sinks to the ground and nothing else happens.
You can't drive the vehicle manually, you need to click on cp to start.
![CP doesn't start working](https://user-images.githubusercontent.com/82874172/115838649-3332bc00-a41a-11eb-802d-4ba34ad5294c.JPG)

Do you have any options to setup those option entries in the control menu?
I can't see the washing mod anymore but it works.

**Comment by andremeyer123** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/tree/beta-testing

**Comment by Tensuko** [comment]
When you say you can't drive it manualy, but have to click on start CP, then CP isn't started -> AD Problem.
As @andremeyer123 said, Beta Version of AD !
We made a push for AD a while ago to get this working again. (Wich is the Beta Version).

For the Action Binding, yes we plan to make an option to show/hide the keybinds.

**Comment by crcarmichael** [comment]
> For the Action Binding, yes we plan to make an option to show/hide the keybinds.

Great news!

Thanks for the help everyone. I'll have to go see if I can grab the AD Beta.  I downgraded to 1.0.0.7 (ModHub version) with the same results, but the path finding is MUCH better.

**Comment by crcarmichael** [comment]
I just noticed that the AD->CP handoff seems to be working when refilling seeds/fert... but I suspect that's because CP stays engaged during the refill process.

**Comment by leo32128fs** [comment]
> https://github.com/Stephan-S/FS19_AutoDrive/tree/beta-testing anúncio iniciar cp apenas com o beta

does not appear to activate in mods

**Comment by leo32128fs** [comment]
> https://github.com/Stephan-S/FS19_AutoDrive/tree/beta-testing anúncio iniciar cp apenas com o beta



> https://github.com/Stephan-S/FS19_AutoDrive/tree/beta-testing anúncio iniciar cp apenas com o beta

appears in mods but when you open a game it does not appear to activate

**Comment by Tensuko** [comment]
> 
> 
> > For the Action Binding, yes we plan to make an option to show/hide the keybinds.
> 
> Great news!
> 
> Thanks for the help everyone. I'll have to go see if I can grab the AD Beta. I downgraded to 1.1.0.7 (ModHub version) with the same results, but the path finding is MUCH better.

Hide Keybinds is now in new Version 00055.

**Comment by Helego** [comment]
Seit der Version 56 habe ich das gleiche Problem. Die Übergabe von AD (1.0.0.8) an CP funktioniert nicht. Die letzte funktionierende Übergabe erfolgte mit der Version 52 (53-55 habe ich nicht übernommen).
Das Fahrzeug fährt mit AD zum angegebenen Übergabepunkt; das Zeichen zur Übergabe erlischt und das Fahrzeug bleibt stehen und muss manuel gestartet werden (Abfahrer einstellen).

**Comment by andremeyer123** [comment]
https://github.com/Stephan-S/FS19_AutoDrive/tree/beta-testing
lesen hilft

**Comment by pvaiko** [comment]
This is because a change in CP. We then created a pull request for AD to fix that:
https://github.com/Stephan-S/FS19_AutoDrive/pull/1872

The pull request has been merged into the AD beta branch in these two commits on Apr 6:
https://github.com/Stephan-S/FS19_AutoDrive/commit/2b9a65458866f60ced0febfa7683174fdf476503
https://github.com/Stephan-S/FS19_AutoDrive/commit/2d9b66ebe019873530df44c5b142ad23e37f0bb2

Now you have to either use AD Beta or just wait until they release this change.
