### ISSUE TITLE
Kurseditor funktioniert in MP nicht mehr (Tastenbelegung)

### ISSUE THREAD

**Issue by LamaiK** [Courseplay/courseplay#7127]
Seit der v53 funktioniert der Kurs Editor nicht mehr im MP mod, lässt sich nicht Starten. Und in SP funktionieren nicht alle befehle. 
Auch das umlegen der Tastenfolge bringt nichts.

[log - Server.txt](https://github.com/Courseplay/courseplay/files/6366990/log.-.Server.txt)
[log.txt](https://github.com/Courseplay/courseplay/files/6366991/log.txt)

**Comment by Tensuko** [comment]
Tastenbelegung im MP kann ich bestätigen, aber im SP läuft alles wie es soll.

Was genau funktioniert nicht ?

**Comment by LamaiK** [comment]
Kann es jetzt nicht mehr nachvollziehen, konnte erst die Punkte bis Start Löschen aber nicht die Punkte bis Ende. Habe es jetzt extra noch einmal gemacht und jetzt funktioniert es aber. War dann wohl bei mir etwas nicht in Ordnung.
Sorry kannst diesen issue in dem Fall löschen das MP Problem ist ja schon im ( #7100 ) beschrieben.

**Comment by Tensuko** [comment]
Alles klar, danke für die schnelle Rückmeldung.
