### ISSUE TITLE
Grass unloading for silage doesn't recognize established pile.

### ISSUE THREAD

**Issue by Noix64** [Courseplay/courseplay#7129]
When collecting and reverse unloading grass CP always tries reversing all the way to the designated tipping point which leads to it getting stuck as soon as the pile starts getting big. I guess because the existing pile has been converted to chaff it isn't recognized as the loading wagon contains grass.

**Comment by Tensuko** [comment]
Logfile, screenshot, did you place an unload here waypoint ? Wich mode ?

**Comment by Noix64** [comment]
I'll provide screenshots and logfile as soon as possible. But I think cp is acting correctly for the most part. I'm using mode 6 with a forage wagon and have an unload point at the end of a bunker. Reversing and unloading works perfectly when the bunker is empty but as soon as a pile starts building up the driver doesn't recognize it as a pile and keeps trying to go all the way to the set unload here waypoint. Note this only happens when unloading grass, when unloading chaff the nearest pile is detected and the driver unloads correctly.

**Comment by Noix64** [comment]
![Farming Simulator 19 Screenshot 2021 05 03 - 22 13 42 26](https://user-images.githubusercontent.com/83098350/116929921-5e5dac80-ac5f-11eb-8453-bf29d8a6ee89.png)
[log.txt](https://github.com/Courseplay/courseplay/files/6417526/log.txt)

Here's the logfile and screenshot of the issue.

**Comment by Tensuko** [comment]
@Noix64 this is not a complete logfile

@pvaiko is there a distance limit to the unload WP ?

**Comment by pvaiko** [comment]
@Tensuko don't know but we have a debug channel 16 for loading/unloading, that and the 12 for the triggers should be on.

**Comment by Tensuko** [comment]
@Noix64 log with channel 12 and 16 active when try to unlaodt into Bunker.

**Comment by Tensuko** [comment]
Closed due to inactivity.
Reopen with the required informations.
