### ISSUE TITLE
Keybinds don't work in multiplayer

### ISSUE THREAD

**Issue by filonb** [Courseplay/courseplay#7130]
Keybinds don't work when joining multiplayer games. 
Right click to open ui works, but none of the keybinds do anything. The mod otherwise works correctly, but it's hard to use without keybinds. Only happens when joining a multiplayer game, works fine in single player and when hosting a multiplayer game. 

Works correctly in version v6.03.00052, issue occurs in versions v6.03.00053, v6.03.00054 and v6.03.00055.

Tested on a fresh map, with courseplay as the only mod.

logfile ('ui' and 'other' debug channels turned on in the last test): 
https://gist.github.com/filonb/5b2fa29e5f489b3a9c90fcc4f5297d30

**Comment by Tensuko** [comment]
#7100
