### ISSUE TITLE
No fill trigger inn bunkersilo

### ISSUE THREAD

**Issue by Ludvir** [Courseplay/courseplay#7131]
Hvem running a courseplay empty combine course from a field to bunker the cp driver dont unload inn bunker silo. 
Can't find filltrigger. Drive drives out again without unloading.

**Comment by Tensuko** [comment]
Missing unload WP.
Watch Video https://youtu.be/sT3fKcI6wqw
And for the next time: https://github.com/Courseplay/courseplay/wiki

**Comment by Ludvir** [comment]
Test
