### ISSUE TITLE
No filltrigger inn bunkersilo. 

### ISSUE THREAD

**Issue by Ludvir** [Courseplay/courseplay#7132]
Hvem running a courseplay empty combine course from a field to bunker the cp driver dont unload inn bunker silo. 
Can't find filltrigger. Drive drives out again without unloading.

This worked before last patch

**Comment by Tensuko** [comment]
Missing unload WP.
Watch Video https://youtu.be/sT3fKcI6wqw
And for the next time: https://github.com/Courseplay/courseplay/wiki

Do not open another issue, watch video, read the articele!

**Comment by Ludvir** [comment]
I found the problem.
It was running  the mods more bunker silo and maize plus on the same save game. 
When doing that you can't unload in you bunkers. 


That was not in you video.

**Comment by Tensuko** [comment]
More bunker silo and maize plus on the same save game is a ModConflict wich is written on the Maiz Plus Discord.

For your next report:
Logfile! We can read a lot of stuff in it even if there is no 'Error' and also Modconflicts can be detected.
