### ISSUE TITLE
CP Hud opening F1 menu doesn't get refreshed(MP only)

### ISSUE THREAD

**Issue by Dragonfly1982** [Courseplay/courseplay#7143]
Hallo, haben die Version 56 aufgespielt und Festgestellt das wir uns gegenseitig das Hud öffnen bzw die Maus triggern. Wenn mein Kollege das Hud bei sich öffnet, schaltet er bei mir die Maus frei. Wenn ich bei mir das Hud öffne schalte ich bei im die Maus frei und das Hud (nicht immer), im F1 Menü tauchen andere Optionen vom Cp auf obwohl es beim Spieler nicht geöffnet ist.
LOG Fehler frei
Wenn weitere Informationen nötig sind bitte DebugChannel nennen.

Es wurde auch schon in einem Geschlossenen Beitrag gemeldet, (#7100)

**Comment by Tensuko** [comment]
bitte trotzdem logfile...

**Comment by Dragonfly1982** [comment]
Hier die Log mit debug 18 und 20

[Server Log.txt](https://github.com/Courseplay/courseplay/files/6372012/Server.Log.txt)
[Spieler log 1.txt](https://github.com/Courseplay/courseplay/files/6372013/Spieler.log.1.txt)
[Spieler Log2.txt](https://github.com/Courseplay/courseplay/files/6372014/Spieler.Log2.txt)

**Comment by schwiti6190** [comment]
@Dragonfly1982

Hi, du könntest einmal versuchen folgendes im ActionEventLoader.lua (Zeile 363) zu ändern: 
`function ActionEventCallbacks.actionEventOpenCloseHud(vehicle, actionName, inputValue, callbackState, isAnalog)
	vehicle:setCourseplayFunc('openCloseHud', not vehicle.cp.hud.show,true);
end`
Es könnte sein das dort das `,true` am ende fehlt :)

**Comment by Dragonfly1982** [comment]
Werden es mal morgen Testen da wir gerade mit unserem Server in Wartung sind. Sind morgen wieder online

**Comment by Dragonfly1982** [comment]
Hi alle zusammen, 
haben das Getestet mit dem true. Es hat funktioniert(Maus wird nichtmehr getriggert), aber es gibt noch zwei weitere Fehler.

1. Wenn einer im Drescher sitzt und ein zweiter Spieler in einen anderen Drescher (und auch bei anderen Maschinen) einsteigt und da den CP öffnet, kann der erste Spieler das Hud nicht mehr öffnen. Er muss dafür aussteigen und wieder Einsteigen, dann ist das Spiel nur anders rum.

2. Wenn ein Spieler dreimal das Hud öffnen möchte(im gleichen Fahrzeug) funktioniert beim erstenmal alles normal. Sobald ein anderer Spieler in ein Fahrzeug einsteigt bzw wechselt bekommt er das Hud nur noch über denn Rechtsklick auf und nicht mehr über die Umgelegte Taste. Beim drittenmal werden nur die Befehle angezeigt im F1 Menü und das Hud bleibt geschlossen.

3. Habe da noch eine Frage:
  ActionEventsLoader.lua in der zeile 426 bis 428 
Kann es sein das da etwas Fehlt? Oder was Bewirken diese Zeilen.

Mit freundlichem Gruß

**Comment by schwiti6190** [comment]
Hi erstmal danke für die Hilfe :)

1/2) Ich glaube jetzt habe ich den Fehler gefunden, sieht so aus als ob was synchronisiert wird zum Server aber es nur auf dem Client laufen solte: `vehicle:setCourseplayFunc('openCloseHud', not vehicle.cp.hud.show,true);` diese Zeile könntest du einmal gegen dies hier austauschen: `courseplay:openCloseHud(vehicle, not vehicle.cp.hud.show)`. Ich hoffe jetzt klappt es, damn MP... :D

3) Die Zeile haben keine Funktion, da sie nur der vollständigkeit halber da sind. Erstmal ein Kommentar da hinschreiben :)

**Comment by Tensuko** [comment]
Try Version 00058 or higher and report

**Comment by Spiitfire** [comment]
> Try Version 00058 or higher and report

it works

**Comment by Dragonfly1982** [comment]
Funktioniert, ausser das das F1 Menü offen bleibt wenn man es mit der Taste( in meinem Fall die ENTF) auf und zu macht. Es verschwindet wenn man es über das x schliesst.

**Comment by Tensuko** [comment]
Try version 6.03.00060 or higher and report pls.

**Comment by Dragonfly1982** [comment]
Ist es gewollt das im F1 Menü die Cp Kurs aufzeichnung dauerhaft zu sehen ist?

**Comment by Tensuko** [comment]
Wann genau ? Wenn kein Kurs geladen ja.
Erweiterte Einstellung die Tastenbelegung aus ?

**Comment by Dragonfly1982** [comment]
Hat sich geklärt mit dem CP Kurs aufzeichnung und der Fehler mit dem F1 Menü ist behoben. Sollte uns noch etwas auffallen werden wir es melden.

**Comment by Tensuko** [comment]
Super, ich mach dann erstmal zu hier.
