### ISSUE TITLE
Courseplay not recognizing any keybinding to open the hud

### ISSUE THREAD

**Issue by TheWendigoAlpha** [Courseplay/courseplay#7145]
Im having an issue right now where im on a server and courseplay isnt recognizing any keybinding i set to it either in the game's options or the inputbinding.xml file. I have reset both of these to default and it still isnt even recognizing the default keybinds
here is also my log file
[log.txt](https://github.com/Courseplay/courseplay/files/6372761/log.txt)

**Comment by andremeyer123** [comment]
https://github.com/Courseplay/courseplay/releases/tag/6.03.00056
new version

**Comment by TheWendigoAlpha** [comment]
> https://github.com/Courseplay/courseplay/releases/tag/6.03.00056
> new version

thanks once the dude who owns the server gets back on well see if it works

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki
