### ISSUE TITLE
CP Hud Disabled after click to switch or map switch on vehicles running CP

### ISSUE THREAD

**Issue by MtBakerScum** [Courseplay/courseplay#7146]
The HUD is disabled after using click to switch or map teleport to switch until I exit the vehicle and reenter vehicle. 

Only effects vehicles that are currently running courseplay or autodrive

[log.txt](https://github.com/Courseplay/courseplay/files/6374008/log.txt)

**Comment by jtsage** [comment]
Seeing the same here, "delete" to pull up the HUD only works after jumping out and back in to the vehicle. 

I re-enabled right click, that works as expected. (I typically globally disable right click to bring up the HUD)

**Comment by Tensuko** [comment]
I can't reproduce this guys.
Maybe rebind the keys or reset the keybind to default ?
Need better steps how thos should happen.
As I always get the HUD open for click to switch, or when I disable right click, jump into vehilce by map, I still can open HUD with delete.

**Comment by MtBakerScum** [comment]
It's a problem with this latest version, it was working fine one version previous. 

I made a video earlier, but it showcased it not working between any click to shift, not just from those running active courses. After I deleted a 200mb log.txt it started only not working when switching to a vehicle running an active course with CP or driving via AD.

https://drive.google.com/file/d/1vqi8RoArkl1GB2lORUBPaQke4qPIDohB/view?usp=drivesdk

I'll try rebinding tomorrow night.

**Comment by Tensuko** [comment]
Also on running CP Driver, can't reproduce.

**Comment by jtsage** [comment]
Heading off in the real world, but when I have a moment, I'll backtrack through the last few versions and make sure it's narrowed down to when this happened (didn't notice with 55, but I also don't think I was running any courses for those few days)

**Comment by jtsage** [comment]
Reproducible - started a new game with only courseplay, autodrive, and money tool mods active.

New farmer, grabbed the first tractor and implement available (no sow seeder of some variety).  Generated a course on my one field, started the driver.  Switched to the next available tractor, delete will not bring up the hud.  Right click still works.  Going back to the courseplay running worker, delete will show/hide the hud.  Exiting/Entering the second tractor makes it work again until a switch.

Tried with autodrive disabled as well, same behavior.

Including log for completeness, although nothing stood out to me.

[log.txt](https://github.com/Courseplay/courseplay/files/6379746/log.txt)

**Comment by Tensuko** [comment]
@schwiti6190 related to  #7143 as well ?

**Comment by leo32128fs** [comment]
this problem has already been solved, because for me even in version - 6.03.00057 it still occurs on some machines

**Comment by Tensuko** [comment]
If this would be solved, it would be mentioned here...

**Comment by schwiti6190** [comment]
@jtsage Hi,
Seems like your right with your last edit. I changed it for MP,  but it seems like I made a mistake. :)

Thx for the help :)

**Comment by Tensuko** [comment]
Try Version 00058 or higher and report

**Comment by jtsage** [comment]
Only had a few minutes before $real_life this morning, but duplicating my test from above, everything appears to work as expected.  Fixed, thanks!  As always, awesome work!
