### ISSUE TITLE
Blade jumps up and will not lower during leveling/compacting mode

### ISSUE THREAD

**Issue by Fightin108** [Courseplay/courseplay#7147]
So I have followed the instructions on setting up a courseplay course and ensuring my blade is on the back of my tractor. However once I hit "start course" my blade tilts all the way back and all the way up, which is not helpful in levelling or moving chaff in my bunker. I have tried many different things, but to no avail 
[log.txt](https://github.com/Courseplay/courseplay/files/6375128/log.txt)

**Comment by Tensuko** [comment]
Screenshots of course, what tool and stuff ?

**Comment by Fightin108** [comment]
The tractor I am using is the 7310 R with the MES 500 blade
![farm sim](https://user-images.githubusercontent.com/83207543/116047284-2936d600-a631-11eb-9ca8-81e954942c5d.png)

**Comment by Fightin108** [comment]
I am using the 7310 R tractor and a MES 500 Blade
![farm sim](https://user-images.githubusercontent.com/83207543/116047784-b0844980-a631-11eb-91c5-347dffcd515e.jpg)

**Comment by Tensuko** [comment]
But this is not leveling.
If you want to do leveling, your unloader have to spread the chaff evenly.
Thats why the blade jumps up.
Switch to Compacting without a blade or build up.

**Comment by Fightin108** [comment]
Ok so I cant really use Autodrive for unloading then if I wish to use the levelling feature? And sorry, what do you mean by "build up"?

**Comment by Fightin108** [comment]
I just made another course after I levelled out my bunker on my own. This time I tried both level and fill up modes and as you can see my blade is still in the air. Not sure if this adds any more info to my problem. I also attached my logs again and a screen shot of my new course
![farm sim 2](https://user-images.githubusercontent.com/83207543/116156831-3db6b500-a6a9-11eb-9f6c-8cd2db32aea4.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/6380624/log.txt)

**Comment by Tensuko** [comment]
> 
> 
> Ok so I cant really use Autodrive for unloading then if I wish to use the levelling feature? And sorry, what do you mean by "build up"? I also try using the "fill-up" mode and I have the same issue with the blade.

Yes I mean fill-up and sure you can use AD for fill up your Bunker.

Sry but that course is total nonsence...

It works just fine:
![fsScreen_2021_04_27_07_18_02](https://user-images.githubusercontent.com/27344744/116189129-cb85b500-a728-11eb-9059-1e4223257e73.png)

**Comment by Fightin108** [comment]
I will try on my next empty bunker to have the course set prior to starting to fill to see if I can correct my issue. As for the last course, I was testing a video i had seen on youtube. Again even if i make a simple course (like my first screen shot) and set to mode to fill up my blade jumps up. Would it be possible that having my AD drivers backing into the bunker and dumping in a single mound rather then spreading it evenly is causing the issue? And if this is the case, are you aware of any settings on AD that I can change to allow dumping evenly?

**Comment by Tensuko** [comment]
I have no Idea about AD and we don't care about how the stuff is in there.
FillUp works just fine.
I don't know what is the problem on your side.
A savegame might help.

**Comment by Fightin108** [comment]
Ohh sorry, I always thought AD was developed by the same folks that made CP. Ill attach my save game file when I get home in the morning. Thanks for all your help by the way.

**Comment by Fightin108** [comment]
Here is my current savegame

[savegame1.zip](https://github.com/Courseplay/courseplay/files/6398586/savegame1.zip)

**Comment by Fightin108** [comment]
Hey so I noticed after i ran my course, and my tractor hit the trigger end point, there were words at the bottom of the screen that said no bunker silo detected at start point. So I had my actual start point at the end of my bunker in the tall chaff pile. It runs through the course with the blade up, but once it hit the trigger end point, the blade finally went down and the driver started pushing chaff! Now it would appear that my issue is the tractor keeps trying to turn around in the bunker.

**Comment by Tensuko** [comment]
![bunkercourse](https://user-images.githubusercontent.com/27344744/116703633-c9db1c00-a9ca-11eb-9361-fda8331350d5.png)

**Comment by Fightin108** [comment]
Everything is working pretty good now. The odd time my tractor takes a nose dive off the pit, but otherwise things are working. Thanks again!
