### ISSUE TITLE
Problem after looading maure/compost from overloader

### ISSUE THREAD

**Issue by patch110** [Courseplay/courseplay#7148]
I have a tractor and manure spreader setup on a field and have another tractor and overload trailer running from the farm to said field so compost can be loaded at the field which does work. problem being that after reloading the tractor and manure spreader resorts to a constant 6mph even on the fieldwork course although i have that set to 20mph unless i stop and restart the course. I have tried both CP and AD on the manure spreader refill route and both give the same result.
[log.txt](https://github.com/Courseplay/courseplay/files/6376807/log.txt)
![fsScreen_2021_04_26_12_10_24](https://user-images.githubusercontent.com/32200890/116078454-88770380-a68e-11eb-9e28-bfd9c03e4505.png)

**Comment by Tensuko** [comment]
Duplicate #6925
