### ISSUE TITLE
CP startet nicht wenn AD Fahrzeug am Ziel ankommt.

### ISSUE THREAD

**Issue by webwibo** [Courseplay/courseplay#7151]
Zuerst muss ich sagen, das hier einte tolle Arbeit geleistet wird,. Ich benutze CP seit Anfang an.
Ich kann  mir LS ohne CP nicht mehr vorstellen.

Nun habe ich ein kleines Problem festgestellt:

Bis Version .0052 konnte ich z.B. einen Feldarbeitskurs starten, (Düngen oder Säen) nach dem ein AD gesteuertes Fahrzeug am entsprechenden Ziel angekommen ist. In AD wurde der Button für die Übergabe an CP eingeschaltet. 
Das Fahrzeug kam am Zielpunkt an, dann wurde nach einem kurzen Moment der Feldarbeitskurs abgefahren.

Dieses Vorgehen scheint ab Version .0053 nicht mehr zu funktionieren. 
Das Fahrzeug kommt an. die Meldung von AD erscheint, AD schaltet ab, aber CP startet den Feldkurs nicht.
Hat sich hier etwas geändert  was ich nicht mitbekommen habe?

In der Log habe ich keine Fehlermeldungen feststellen können.
Getestet auf Felsbrunn mit Vanilla Gerät.

![Problem_Cp_AD](https://user-images.githubusercontent.com/61359685/116279661-17b41200-a788-11eb-909f-4648656689db.png)

**Comment by leo32128fs** [comment]
Gehen Sie zu dem Thema, das Ihr Problem löst >>>>>> AD->CP handoff not working #7125

**Comment by leo32128fs** [comment]
Ich hatte das gleiche Problem und er ging

**Comment by Tensuko** [comment]
Duplicate
