### ISSUE TITLE
Courseplay causes freeze on 64X map

### ISSUE THREAD

**Issue by rar314** [Courseplay/courseplay#7155]
Courseplay freezes the game when playing West End 64x by Levis v1.0.0.0.
Map author acknowledges this issue and the issue is listed on all download sites.
If there was ever a map that needs courseplay it is a mega-sized map

https://www.modhub.us/farming-simulator-2019-mods/west-end-64x-by-levis-fs19-10

**Comment by Tensuko** [comment]
1st at all, there is a point where the game is rly not made for.
x16 Maps are already extremly big.
x64 is simply oversize.
Try newest Version for loading and saveing course time improovement but all generation stuff take time and there is no way to improove this.
We won't do anything for this.
