### ISSUE TITLE
mod anpassen an CP ?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#7156]
Hallo Leute
ich verwende den Grimme FT300 Schlegler aus diesem modpack hier:
https://ls-modcompany.com/filebase/file/736-multifruit-harvester-pack/

jedoch kann ich für diesen Schlegler keinen CP-Feldkurs generieren, ich habe nur Fahren oder Schieben zur auswahl:
![fsScreen_2021_04_29_15_02_26](https://user-images.githubusercontent.com/24860501/116555031-31766600-a8fc-11eb-9ace-d99e6c23f510.png)

kann es damit zusammenhängen das der FT300 in der xml den
`<vehicle type="fruitPreparerMultiFruit">`
hat?
in der moddesc.xml wird der typ so definiert:
```
		<type name="fruitPreparerMultiFruit" parent="baseGroundTool" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
			<specialization name="turnOnVehicle" />
			<specialization name="FruitPreparerMultiFruit"/>
		</type>
```
löst es das problem, wenn ich in der moddesc.xml noch eine 
<specialization name="...."
dazuzugeben?
wenn ja welche, damit cp das als Arbeitsgerät erkennt?
lg
andreas

**Comment by Tensuko** [comment]
Ich guck mir das nachher mal an, könnte man vlt in der Mode Config mit einbringen.
Was sagen die Vanilla Krautschläger ?

**Comment by andreasthu** [comment]
Der vanilla krautschläger FT300 funktioniert auch nicht. 
Hab ich soeben ausprobiert. Vanilla auch nur fahren oder schieben zur Auswahl.
Btw, der grimme rootster 604 rübenroder, und da jetzt egal ob aus der mod oder vanilla, kann zwar feldkurs auswählen und einen feldkurs generieren  aber wenn ich dann den abfahrer einstellen will, wird er gleich wieder entlassen.
Version von CP ist 60300057.
Lg
Andreas

**Comment by Tensuko** [comment]
Ok ich schau gleich mal.

**Comment by pvaiko** [comment]
Dafuer haben wir unser Config File https://github.com/Courseplay/courseplay/blob/master/config/ValidModeSetup.xml

**Comment by Tensuko** [comment]
Vanilla geht, schade, dass die Mod wieder was spezielles haben 'muss'...
![fsScreen_2021_04_29_17_28_32](https://user-images.githubusercontent.com/27344744/116577214-90de7100-a910-11eb-9fb0-5f7d5c9ee11c.png)

**Comment by Tensuko** [comment]
Vanilla ernten geht auch.
![fsScreen_2021_04_29_17_33_13](https://user-images.githubusercontent.com/27344744/116577688-fe8a9d00-a910-11eb-9d13-782afbefe10d.png)

**Comment by andreasthu** [comment]
@Tensuko 
sorry, bei mir gehts nicht, weder der vanilla noch der mod FT300
den rootster 604 roder hab ich allein im einsatz, nicht so wie du den FT300 in der front und den roder hinten.
ich schlegle vorher, und rode später, das ist bei den Wenden und Ecken platzsparender
werde aber am abend mal die front-heck-kombi versuchen
oder es schießt noch ein anderer mod dazwischen.

btw, hab den multifruit Selbstfahr roder aus dem modpack ropa panther mit dem RRxL9 schneidwerk probiert, dieses funktioniert problemlos mit cp

@pvaiko 
hab mir die ValidModeSetup.xml mal angesehen, 
ich muss da bei
```
	<!--UnloadableFieldWorkAIDriver(6)-->
	<Mode>
		<AllowedSetups>
```
also quasi nach dem claas crop sensor
```
			<Setup>
				<Specialization name="spec_fruitPreparerMultiFruit"/>
			</Setup>
```
dazu miteintragen?

lg
andreas

**Comment by Tensuko** [comment]
Einfach machen und schauen ob er dann funktioniert.
Aber mit dem Ernter da muss bei dir ein Problem sein wie es aussieht, oder es tritt nur auf, wenn man ohne den Krautschläger arbeitet ?

**Comment by pvaiko** [comment]
> also quasi nach dem claas crop sensor
> 
> ```
> 			<Setup>
> 				<Specialization name="spec_fruitPreparerMultiFruit"/>
> 			</Setup>
> ```
> 
> dazu miteintragen?

Genau.

**Comment by andreasthu** [comment]
hallo Leute
habe nun bei der ValidModeSetup.xml folgendes eingetragen:
```
	<!--UnloadableFieldWorkAIDriver(6)-->
	<Mode>
...
			<!--Claas Crop Sensor [Mod/VertexDesign]-->
			<Setup>
				<Specialization name="spec_liveCropScanner"/>
			</Setup>
			<Setup>
				<!-- catch all for everything with tension belts, like some auto bale loaders -->
				<Specialization name="spec_tensionBelts"/>
			</Setup>
			<!--Grimme Multifruit Roder FT300-->
			<Setup>
				<Specialization name="spec_fruitPreparerMultiFruit"/>
			</Setup>
			<!--Grimme Multifruit Roder Rootster604-->
			<Setup>
				<Specialization name="spec_attachableCombineMultiFruit"/>
			</Setup>
		</AllowedSetups>
```
also die specs für den FT-300 und auch gleich für den Rootster604.
es funktioniert nicht beim FT-300:
![fsScreen_2021_04_30_09_46_09](https://user-images.githubusercontent.com/24860501/116664983-7b615980-a999-11eb-9ab4-1b5cff93e5ec.png)

und beim Rootster604 kann ich den CP-Fahrer nicht einstellen:
![fsScreen_2021_04_30_09_45_49](https://user-images.githubusercontent.com/24860501/116665100-9e8c0900-a999-11eb-8e73-74e4a7c8fe8f.png)
und da ist esegal, ob vorne der FT-300 hängt oder nicht.
mit dem original gehts, hab ich nun wieder versucht.
komischerweise schreibt cp einige errors in die log wenn ich den cp-fahrer einstelle:
z.b.:
```
2021-04-30 09:43 LUA call stack:
2021-04-30 09:43   =C:/Users/athum/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/base.lua (613) : printCallstack
2021-04-30 09:43   =C:/Users/athum/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/Manager/HarvestManager.lua (329) : getCurrentDischargeNode
2021-04-30 09:43   =C:/Users/athum/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/ExternalInterface.lua (201) : getOpenPipePercent
2021-04-30 09:43   =C:/Users/athum/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CombineAIDriver.lua (1087) : combineIsCallingDriver
2021-04-30 09:43   =C:/Users/athum/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CombineAIDriver.lua (1071) : isAutoDriveWaitingForPipe
2021-04-30 09:43   =C:/Users/athum/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CombineAIDriver.lua (1064) : handleCombinePipe
2021-04-30 09:43   =C:/Users/athum/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CombineAIDriver.lua (215) : handlePipe
2021-04-30 09:43   =C:/Users/athum/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/AIDriver.lua (413) : drive
2021-04-30 09:43   =[C] (4294967295)
2021-04-30 09:43   =C:/Users/athum/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/base.lua (613) : xpcall
2021-04-30 09:43   dataS/scripts/vehicles/SpecializationUtil.lua (30)
2021-04-30 09:43   dataS/scripts/vehicles/Vehicle.lua (1306) : raiseEvent
2021-04-30 09:43   dataS/scripts/network/NetworkNode.lua (98) : update
2021-04-30 09:43   dataS/scripts/network/Server.lua (58) : updateActiveObjects
2021-04-30 09:43   dataS/scripts/BaseMission.lua (1500) : update
2021-04-30 09:43   dataS/scripts/FSBaseMission.lua (1979) : update
2021-04-30 09:43   dataS/scripts/missions/mission00.lua (469) : update
2021-04-30 09:43   dataS/scripts/main.lua (1944) : update
2021-04-30 09:43 :48 [info lp38045] ARION 660 (#1): Exception, stopping Courseplay driver, C:/Users/athum/Documents/My Games/FarmingSimulator2019/mods/FS19_AutoDrive/scripts/Manager/HarvestManager.lua:329: attempt to call method 'getCurrentDischargeNode' (a nil value)
```
ganze log hier:
[log.txt](https://github.com/Courseplay/courseplay/files/6403735/log.txt)

komisch deshalb, weil cp anscheinend an Autodrive übergeben möchte.
am 2. bild oben sieht man im cp hud aber das ich AD auf "nicht benutzen" stehen habe.

ich wollte das nur anmerken, werde es irgendwann später wieder mal versuchen,
habe mir in der zwischenzeit aber kredit aufgenommen und den Ropa Panther2 mit dem RR-xL9x45 Rodeaggreagat aus demselben Multifruit Pack gekauft und ernet damit.
der funktioniert:
![fsScreen_2021_04_30_09_57_07](https://user-images.githubusercontent.com/24860501/116665909-a0a29780-a99a-11eb-8950-d502ead6ff2d.png)
(da sind die kartoffeln schon geschlegelt, weil ich dieses Feld mit dem 604 ernten wollte)

lg
andreas

**Comment by pvaiko** [comment]
Das ist wenn CP checkt ob ein AD Abfahrer wartet. AD kann nicht mit diesem Ernter (ohne DischargeNode) umgehen. Bitte bei AD melden.

**Comment by Tensuko** [comment]
Hab mir das mit den Specialisations auch noch mal angeschaut, das scheint bisschen chaotisch zu sein bei der Mod.
Jedenfals funktioniert das nicht mal so eben.

Aber wie auch immer.
Benutzt man beiden zusammen, geht es ohne Probleme, auch ohne weitere Eintragungen.
![fsScreen_2021_04_30_14_43_07](https://user-images.githubusercontent.com/27344744/116696632-74027600-a9c2-11eb-99a0-1ca4b4368d8b.png)

**Comment by Tensuko** [comment]
@andreasthu 
abgesehen von dem Callstack der von AD kommt, ist das Thema für dich soweit erledigt ?
Ich weis, dass der Krautschläger alleine nicht mit CP läuft, aber ich kann dir auch nicht sagen, warum die specialisation nicht funktioniert.
Allerdings konnte ich keinen Unterschied zwischen Vanilla und Mod feststellen.

**Comment by andreasthu** [comment]
achja, sorry,
das Thema ist für mich erledigt.
benutze nun ja den ropa panther aus demselbem mod, und dieser funktioniert problemlos mit cp.
lg
andreas
