### ISSUE TITLE
Working with a combine

### ISSUE THREAD

**Issue by Tocik** [Courseplay/courseplay#7157]
![1](https://user-images.githubusercontent.com/65189100/116592320-8cbe4d80-a928-11eb-825f-57e56558dca4.jpg)

for 18 hours I could not remove a small field.
The tractor constantly rests against the combine on the way to unload or load.
Perhaps I am doing something wrong? ..
[log.txt](https://github.com/Courseplay/courseplay/files/6400465/log.txt)

**Comment by Tensuko** [comment]
Can't reproduce this.
Logfile with debugchannel 2 and 11 might help.
Do you have set any offset ?
![fsScreen_2021_04_29_19_54_53](https://user-images.githubusercontent.com/27344744/116596572-d2791700-a924-11eb-93d5-4747100ec09c.png)

**Comment by Tocik** [comment]
Everything is by default.
On the approach to unloading, it sometimes rests against the header.

**Comment by Tensuko** [comment]
Hmm wasn't happening.
Did the unloader came from the front when that happened ?

**Comment by Tocik** [comment]
I do not know, I was absent at this moment

**Comment by pvaiko** [comment]
As we all know :) debug channel 2 is what we need.

**Comment by pvaiko** [comment]
@Tensuko as you can see the unloader is in MOVING_OUT_OF_WAY state so it most likely got to the combine while the combine was still reversing.
