### ISSUE TITLE
grain cart drives straight into combine

### ISSUE THREAD

**Issue by nolan771234** [Courseplay/courseplay#7158]
my grain cart is driving straight into the combine, like in its header. I'ts happened 3 times. I've attached my log.txt and an image.
[log.txt](https://github.com/Courseplay/courseplay/files/6401005/log.txt)
![Screenshot (130)](https://user-images.githubusercontent.com/83425942/116604746-87e3a480-a8fc-11eb-9a15-3f9b1abd48da.png)

**Comment by Tensuko** [comment]
A detail picture of the 'accident' isn't helping.
Overview with debugchannels and course helps a lot more...

**Comment by Misamangame** [comment]
This is definitely gender issue. Man driving the combine forgot to wash the dishes so woman in tractor is very angry with him.

**Comment by RayzerSharpe** [comment]
This is happening to me several times too.. i will try and get a log file together but as far as i can see its the loop that gets created to line up tractor with the combine... and more often than not the loop includes a path to the combine. See attached screenshot. 

![image](https://user-images.githubusercontent.com/25461795/116789011-a2588200-aaa4-11eb-991b-ab81d5307e12.png)

**Comment by Tensuko** [comment]
@RayzerSharpe 
https://github.com/Courseplay/courseplay/wiki
https://github.com/Courseplay/courseplay/releases

**Comment by RayzerSharpe** [comment]
Ok i have a savegame and courses that should reproduce this and I have put up the log too. The only mod need to run is courseplay. It uses the stock Ravenport (MapUS) and stock vechicles.

[MapUS.zip](https://github.com/Courseplay/courseplay/files/6417861/MapUS.zip)
[savegame4.zip](https://github.com/Courseplay/courseplay/files/6417862/savegame4.zip)
[log.txt](https://github.com/Courseplay/courseplay/files/6417863/log.txt)

Instructions to reproduce. 
1. Load the map and go the the Case Axial-flow Harvester
2. Start its on it course at Next closest waypoint (already set) and wait for it to get to 100% full
3. Go to the MF8727 and mark the Case Axial-flow under Manage Combines. 
4. Set the MF8727 on it way..

I have set the MF to avoid fruits and for me it drives to the front of the the combine and stops saying its in traffic. This is shown in the screenshot below. Hope you can reproduce it

![image](https://user-images.githubusercontent.com/25461795/116937437-1d669780-ac61-11eb-9613-24d6d22b92cc.png)

**Comment by Tensuko** [comment]
You did NOT set it to avoid fruit:
![fsScreen_2021_05_04_06_47_03](https://user-images.githubusercontent.com/27344744/116961812-9a673080-aca4-11eb-8cca-b43b73d9857c.png)

This is how it looks like if it is actiavated and the course got generated within seconds.
![fsScreen_2021_05_04_06_48_26](https://user-images.githubusercontent.com/27344744/116961869-c4b8ee00-aca4-11eb-915e-692d0993b32a.png)

**Comment by RayzerSharpe** [comment]
ok.. bad english. 

I deactivated Avoid Fruits.. try it with it deactivated

**Comment by Tensuko** [comment]
> please try it with it deactivated...

deactivated is a simple way and will not generate a course to avoid any collission.

**Comment by Tensuko** [comment]
Can't do much there, we highly suggest you to turn on avoid fruit, thats what we made the Pathfinder for, as you can see in my picture.

**Comment by RayzerSharpe** [comment]
hhmmm.. ok i'll turn on avoid fruit... but i remember turning it before for a reason.. I'll see how it goes
