### ISSUE TITLE
Silage verdichten bei großen Silo

### ISSUE THREAD

**Issue by xerion8300** [Courseplay/courseplay#7161]
Wenn ich den Coursplay starte fährt er die erste Bahn richtig ein aber dann dreht er sich immer nur noch im Kreis.
Ist das Silo zu groß, oder was mach ich für einen Fehler.

https://www.youtube.com/watch?v=I7EIAX4lu58
[log.txt](https://github.com/Courseplay/courseplay/files/6405974/log.txt)

**Comment by Tensuko** [comment]
Spontan würde ich sagen, erster Wegpunkt viel zu weit im Silo und Stoppunkt zu dicht.

**Comment by xerion8300** [comment]
Gut werde ich mal ändern.
Melde mich wieder. 
Danke

**Comment by xerion8300** [comment]
So erster Wegpunkt nach außen gesetzt, und Stoppunkt nicht mehr so dicht gesetzt.
Resultat: Erste Bahn fährt er exakt, dann zweite Bahn ein Stück ok dann dreht er sich .
[log.txt](https://github.com/Courseplay/courseplay/files/6406256/log.txt)

**Comment by ct177mak** [comment]
Wo liegen denn die Unterschiede beim festen Silo oder plazierbarem Silo ??

**Comment by xerion8300** [comment]
Es ist ein Platzierbares Silo

**Comment by Tensuko** [comment]
Wenn es platzierbar ist, dann kannst du mir einen link zum download geben und wir können uns das relativ einfach anschauen.

**Comment by xerion8300** [comment]
Hier der Link. Das gleiche Problem ist dann auch beim entladen des Silos.

https://www.farming-simulator.com/mod.php?lang=de&country=at&mod_id=133019&title=fs2019

**Comment by xerion8300** [comment]
So noch Infos für euch.
Erstes Bild Start rechts, Fährt seinen Kurs ab bis er auf das Linke Feld kommt, dann dreht er sich.
![fsScreen_2021_05_04_16_07_47](https://user-images.githubusercontent.com/25564472/117018082-792e3080-acf4-11eb-8f17-b09f04a9b626.png)

Kurs von der Anderen Seite des Silos gestartet, er fährt nach rechts und dreht sich sofort.

Das wäre jetzt auch wieder von Bild 1 die Linke Position.

![fsScreen_2021_05_04_16_11_13](https://user-images.githubusercontent.com/25564472/117018363-b5fa2780-acf4-11eb-9d6f-7a2e1fb90995.png)

**Comment by Tensuko** [comment]
Die log dazu wäre auch noch super gewesen :)

**Comment by lionking2890** [comment]
Mir fällt gerade auf dem letzten Bild auf, dass Häckselgut an der Seite des Silos durch die Wand kommt. Vielleicht versucht er deshalb auch immer dort zu verdichten und kommt nicht dran.

**Comment by xerion8300** [comment]
Hab noch mal die Log mit Video angehängt.Ist schon komisch Erste Bahn macht er dann bei der Zweiten Bahn dreht er sich.
Fahre ich schneller wie 10 Km/h also zb. 13Km/h dann dreht er sich auch sofort.
@lionking2890 macht das gleiche auch wenn keine Silage nach außen drückt, aber Danke für die Info.
Vielleicht  hilft das weiter.
[log.txt](https://github.com/Courseplay/courseplay/files/6427519/log.txt)
https://www.youtube.com/watch?v=8pMWIR0aQvg

**Comment by Tensuko** [comment]
Also ich wollte mir das gerade anschauen, aber das verlinkte Silo ist nicht das große in dem Bild...

**Comment by xerion8300** [comment]
[lizardbunkersilo.zip](https://github.com/Courseplay/courseplay/files/6445892/lizardbunkersilo.zip)
Das ist es blöd wenn man zu viel hat.

**Comment by Tensuko** [comment]
Try Version 6.03.00059 or higher and report.

**Comment by xerion8300** [comment]
Hallo,
ich habe jetzt diese Silo ausgiebig getestet. Funktioniert einwandfrei bis jetzt.
Besten Dank für eurer schnellen Reaktion und euren tollen Mod.

**Comment by Tensuko** [comment]
Alles klar, danke fürs feedback.
Diese Probleme sollten jetzt auch nicht wieder auftreten.
