### ISSUE TITLE
Courseplay Problem 6.03.00058

### ISSUE THREAD

**Issue by EisenbahnTommy** [Courseplay/courseplay#7162]
Hello everyone, I have a question about Courseplay. When I want to play with Courseplay in multiplayer, CP does not recognise the courses of the fields on the map. Sometimes it works when I sell the field and buy it again. Then I can sometimes select the field in the course generation. I did not have such a problem before. Even when I have managed it, at the latest after restarting the game or loading the score, I cannot select any fields again. Does anyone have any ideas? LG

[log.txt](https://github.com/Courseplay/courseplay/files/6408749/log.txt)

**Comment by Tensuko** [comment]
#6537
