### ISSUE TITLE
Helfer wartet nicht beim verdichten im MP

### ISSUE THREAD

**Issue by Chissel** [Courseplay/courseplay#7163]
Ich weiß, dass Courseplay aktuell nicht komplett den MP unterstützt, aber eventuell mache ich ja auch nur etwas falsch.

Beim verdichten hält der Helfer nicht am Wartepunkt bzw. bewegt sich nicht einmal dahin, wenn ich in der Nähe bin mit einem Traktor, obwohl es so in den Einstellungen eingestellt ist. Im Singleplayer funktioniert dieses tadellos. Ist dies einfach noch nicht implementiert oder habe ich etwas übersehen?

Ansonsten geile Arbeit und weiter so!

**Comment by Tensuko** [comment]
Das hat bisher noch niemand ausprobiert denke ich mal.
Aber kann man sich bestimmt mal anschauen, wenn Zeit ist oder die Gelegenheit sich ergibt.

**Comment by leo32128fs** [comment]
in my case it's giving a pretty funny error I don't know what the cause , my friend got on the server and it worked, but after a few minutes of playing, he started to crash the game and decided to log out and log in again and was unable to log into the server

**Comment by leo32128fs** [comment]
If you want the full log I can send you

**Comment by Tensuko** [comment]
> 
> 
> If you want the full log I can send you

always need the full logfile.

**Comment by schwiti6190** [comment]
@Chissel , @leo32128fs Could you try this with the newest version: 6.03.00059 or higher ?

**Comment by Chissel** [comment]
For sure. Will Upload the 6.03.00059 to our server in the next days and test it.

**Comment by Chissel** [comment]
I have test it with the 6.03.00060 on our server but the helper still not wait on waitpoint, when i am in the near with another tractor with trailer. In singleplayer the message appear that the helper will wait, but not in multiplayer. I think the helper did not detect me as an tractor in his team and so he will not wait.

**Comment by schwiti6190** [comment]
Hi there,
could you try this out: https://github.com/Courseplay/courseplay/commit/faeae973b4204618bfa1e8a2a32fd291fec08b30 :)?

**Comment by Chissel** [comment]
Works perfect! Thanks a lot 😍
