### ISSUE TITLE
Krone Big M

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#7164]
Hallo
Ich wollte über Courseplay mit den Krone Big X das Stroh aufnehmen. Wenn ich dann auf Helfer einstellen drücke bleibt der Häcksler stehen und der Helfer geht wieder raus
![Stroh](https://user-images.githubusercontent.com/47453761/116792636-3127c780-aac2-11eb-8812-eeba5586e9ae.png)
[log.txt](https://github.com/Courseplay/courseplay/files/6410154/log.txt)

**Comment by Tensuko** [comment]
Kann ich nicht reproduzieren.
![fsScreen_2021_05_01_21_27_14](https://user-images.githubusercontent.com/27344744/116792949-13f3f880-aac4-11eb-9649-0b2dc2410e08.png)

**Comment by Tensuko** [comment]
Closed due to inactivity.
Wasn't able to reproduce this, not sure whats the problem here.
