### ISSUE TITLE
Hardi Rubicon 9000 bug/glitch

### ISSUE THREAD

**Issue by WolfMan0702** [Courseplay/courseplay#7165]
When trying to set the in-game Hardi Rubicon 9000 on a coursplay course, it stops, "fires the worker", I start it back up again, but only goes 3/4 km/h, with both herbicide and liquid fertilizer. I have tried changing settings in the "speed" tab of the coursplay hud, but with no success. Also if this problem was mentioned before, and solved, please sent a link, I, unfortunately, don't have enough time on my hands to search for it. Edit: CP version is v6.03.00058 (latest at this moment)

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by WolfMan0702** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6411737/log.txt)

**Comment by Tensuko** [comment]
Can you do a quick test ?
Remove manure system and see if it works then, so we know where this comes from.

**Comment by WolfMan0702** [comment]
After a quick test, I removed the ManureSystem from my mods folder, and it now works fine, but, I do want to use manure system on all my maps, so what should I do?

**Comment by Tensuko** [comment]
Wait untill we fix it, now that we know it is this.
