### ISSUE TITLE
Bug or Intended

### ISSUE THREAD

**Issue by patch110** [Courseplay/courseplay#7166]
Hi i seem to be getting blue debug lines at every turn while spreading Lime. Have a seeder running at the same time but its not happening with that. 
[log.txt](https://github.com/Courseplay/courseplay/files/6411706/log.txt)
![fsScreen_2021_05_02_16_32_31](https://user-images.githubusercontent.com/32200890/116818702-9d5b0780-ab64-11eb-892b-fb21331f7c89.png)
![fsScreen_2021_05_02_16_32_34](https://user-images.githubusercontent.com/32200890/116818709-a0ee8e80-ab64-11eb-96b2-bac9bd7e6974.png)

**Comment by polosubtil** [comment]
Open CP Hud on this tractor
=> Settings => Advanced settings => Turn off "Show temporary waypoints"
