### ISSUE TITLE
Keil Silo verdichten

### ISSUE THREAD

**Issue by DonBolli** [Courseplay/courseplay#7167]
Ich spiele auf der NF Marsch 4fach OG das Keilsilo welches ich verwende ist das grosse Doppelsilo von Fed. Beim verdichten habe ich das Problem, je nach Befüllung dreht er immer nur im Kreis. Ich habe auch schon mit Start und Endpunkt experimentiert, leider ohne Erfolg.

**Comment by Tensuko** [comment]
Du kennst das doch, Bilder sagen mehr als tausend Worte.

**Comment by DonBolli** [comment]
Klar kenn ich, von was benötigst du Bilder? Video wird schwer, da es meist erst nach einer Zeit auftritt

**Comment by Tensuko** [comment]
Bilder wo er anfängt blödsinn zu machen, ich denke mal wenn er nicht viel im Schild hat und dann zum ende des Silos fährt, da fehlt der drop out of silo irgendwie...

**Comment by DonBolli** [comment]
Es hat zwar etwas gedauert (Aufzeichnen&Schneiden)
Hier auf diesem Video hast den Kurs und das Drehen, ich hoffe das hilft.
[Video](https://www.youtube.com/watch?v=zREn_NvSA68 )

**Comment by Tensuko** [comment]
Mit debug channel 10 im Video hätte man noch mehr sehen können, aber das ist schon mal etwas hilfreicher.
Kannst du mal versuchen was er macht, wenn man mit dem Stoppunkt gerade vor das Silo fährt ? Er kommt da recht schräge an, weis nicht ob das Einfluss hat.

**Comment by DonBolli** [comment]
Gemacht. Hat leider nichts gebracht.

![image](https://user-images.githubusercontent.com/43571844/116911509-3febb700-ac47-11eb-8c00-f4a8f9d6f31c.png)

**Comment by matzeh72** [comment]
Ich benutze courseplay gern für feldarbeit, das klappt sehr gut!
Aber bei den Keil und Bunkersilos gibt es immer probleme! 
Gibt es eine anleitung wie man die kurse einfährt? ich finde nichts!

**Comment by ct177mak** [comment]
Vllt hilft das hier https://www.youtube.com/watch?v=0vZoiS_H65o

**Comment by matzeh72** [comment]
ok ich versuch es mal so. Leider sieht man in dem Video nicht ob es da klappt.
Aber eine Anleitung /Dokumentation  zu CP wäre schon nicht schlecht!
Danke

**Comment by Tensuko** [comment]
Try Version 6.03.00059 or higher and report.

**Comment by DonBolli** [comment]
Danke. Leider sind alle Keilsilos frisch gefüllt. So bald ich kann werde ich es teste und euch Feedback geben.

**Comment by Tensuko** [comment]
Also die meisten Issues die darauf abzielen zeigen, dass es nun funktioniert.
Ich mache hier mal zu, wenn noch was ist, melden bitte (mit den gewohnten Infos!)
