### ISSUE TITLE
Autodrive mit CoursePlay

### ISSUE THREAD

**Issue by 4styler** [Courseplay/courseplay#7168]
Sehr geehrte Damen und Herren,
als erste vielen Dank für Ihre wirklich gute und harte Arbeit. Es geht um folgendes. Wenn ich mit Autodrive zu einem Punkt in der Nähe eines Feldes fahre und die Übergabe funktion in Autodrive einschalte wird das Fahrzeug gelockt. Es lässt sich nicht bewegen bis ich den CoursePlay fahrer per Hand einschalte.
Ich war der Meinung das dass automatisch gehen sollte.
Version AD: 1.1.0.8
Version CP: 6.03.00058

Ich hoffe Sie haben eine Idee
Viele Grüße

4styler

**Comment by Tensuko** [comment]
#7125
#7151
Ad Beta laden und nächstes mal bitte erst suchen.
