### ISSUE TITLE
Überladewagen ladet nicht über

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#7171]
Hallo 
Hab das Problem das der Überladewagen nach Kurseinzeichnung das erste mal überladet dann nur noch vorbei fährt! Was mach ich falsch hab mit mehreren  ÜL Wagen getestet und Anhängern und Traktoren! Map Wild West
LG

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki
