### ISSUE TITLE
Can not open HUD in multiplayer

### ISSUE THREAD

**Issue by ClemensMoosbrugger** [Courseplay/courseplay#7172]
Hey there, I wanted to play in a multiplatyer session with my friend. My friend is the host of the session, he can open the HUD, but I as a participant can not open the HUD. Are there any solutions for this?

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by ClemensMoosbrugger** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6417230/log.txt)

**Comment by ClemensMoosbrugger** [comment]
Courseplay version (v6.03.00054)

**Comment by ClemensMoosbrugger** [comment]
Map: Felsbrunn

**Comment by ClemensMoosbrugger** [comment]
[savegame8.zip](https://github.com/Courseplay/courseplay/files/6417261/savegame8.zip)

**Comment by Tensuko** [comment]
> Courseplay version (v6.03.00054)

So you did not read the wiki. Try it again.

**Comment by ClemensMoosbrugger** [comment]
Here we go again:

I have the problem, that i can not open the HUD in a multiplayer sessseion.
I am a participant at a multiplayer session.
The host can open the HUD but but no one else.
Map: Felsbrunnn
The error occurs with any vehicle
[log.txt](https://github.com/Courseplay/courseplay/files/6419592/log.txt)
[gamelog.txt](https://github.com/Courseplay/courseplay/files/6419613/gamelog.txt)

**Comment by Tensuko** [comment]
Dude, how much more do I have to tell you:
Courseplay version (v6.03.00054)
https://github.com/Courseplay/courseplay/releases

Part of 00058 Release note:
- might fix mp hud open/close action event #7143
- might fix action event bug #7146

READ the Wiki, this is the 1st line:
- Always update to the latest build and check if the problem really still exists before reporting issues.

and you ignored that, now twice...
