### ISSUE TITLE
Courseplay sometimes doesn't fill the trailer at the farmsilo.

### ISSUE THREAD

**Issue by Tim321123** [Courseplay/courseplay#7173]
When I want courseplay to empty my farmsilo or feed my animals, it sometimes just drives through the trigger where it should fill up the trailer. I already tried to make new courses but it didn't work out. The destinationtrigger always works.
Thanks for helping out. Kind regards Tim

**Comment by Tensuko** [comment]
logfile, pics of your course...
https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
Closed due to inactivity
