### ISSUE TITLE
Abfahrer bleibt an dem Punk stehen und ist Ernter im Weg

### ISSUE THREAD

**Issue by Drayorb** [Courseplay/courseplay#7174]
Der Combine Abfahrer bleibt direkt nach dem Überfüllen stehen und ist dem Drescher nach dem Wenden im Weg und bewegt sich nciht weg

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Drayorb** [comment]
![image](https://user-images.githubusercontent.com/83674412/117071759-cda2d180-ad2f-11eb-84eb-00183bdf3d02.png)
[log.txt](https://github.com/Courseplay/courseplay/files/6424041/log.txt)

The tractor keeps standing right in front of the Harvester
