### ISSUE TITLE
Tractor keeps standing after loadoff from harvester

### ISSUE THREAD

**Issue by Drayorb** [Courseplay/courseplay#7175]
![image](https://user-images.githubusercontent.com/83674412/117071990-19ee1180-ad30-11eb-8205-043488145b79.png)
[log.txt](https://github.com/Courseplay/courseplay/files/6424057/log.txt)
the tractor keeps standing right in front of the harvester and says "traffic"
version v6.03.00058
map suedhemmern no not supported mods

**Comment by Tensuko** [comment]
Und mir springt direkt etwas ins Gesicht:
Fruchtumfahrung deaktiviert -> aktivieren!!

**Comment by Drayorb** [comment]
Same result with our without it. Without it the tractor keeps getting the fruits at the 50% and with it it drove only at 100% on the fruits. With it the problem happens a lot of more. Only tested it on tractor with the parameter because only the tractor was on the fruits. Will try it with the rest of the field.

__________________________

Weiß nun nicht in welcher Sprache. Tritt bei beiden Parametern (Traktor) auf. Die Fruchtumfahrung beim Traktor habe ich umgestellt und es trat immer wieder auf. Bei beiden hab ich es nicht probiert, da für mich nur der Traktor auf dem Feld stand. Ich werde es mit dem Rest des Feldes versuchen.

**Comment by Tensuko** [comment]
Wenn der Ernter mit dem Rohr zur Frucht zeigt und Fruchtumfahrung aus ist, dann wird der Abfahrer auch in die Frucht gerufen.
Das am Ende der Bahn wenn der Ernter wendet, was erwartest du da.

Fruchtumfahrung an bei BEIDEN.
