### ISSUE TITLE
Poplar Bale Collect Mode

### ISSUE THREAD

**Issue by jspring0811** [Courseplay/courseplay#7176]
It looks like poplar bales are not detected by the bale collect mode.   Enhancement?

**Comment by Tensuko** [comment]
Working as intended. Logfile ?
![fsScreen_2021_05_05_11_18_27](https://user-images.githubusercontent.com/27344744/117120502-b3024400-ad93-11eb-9933-e8fffd971d03.png)

**Comment by jspring0811** [comment]
For poplar, the driver immediately drives back to the starting point in a continuous loop.  In the example below, I first manually loaded 1 bale to test the trailer and then started the CP driver.  Collecting wrapped silage is working fine on another field.

https://youtu.be/TGS5Ss8_lMM

[client_log.zip](https://github.com/Courseplay/courseplay/files/6427549/client_log.zip)
[server_log.zip](https://github.com/Courseplay/courseplay/files/6427550/server_log.zip)

**Comment by Tensuko** [comment]
Will have to try this on an actual poplar field, that will take some time.
Don't see a reason why he doesn't find bales.
Logfile with channel 7 could help here.

**Comment by jspring0811** [comment]
Logs with debug channel 7...

[client_log_dbg7.zip](https://github.com/Courseplay/courseplay/files/6438507/client_log_dbg7.zip)
[server_log_dbg7.zip](https://github.com/Courseplay/courseplay/files/6438508/server_log_dbg7.zip)

Thanks.

**Comment by pvaiko** [comment]
I need a save game for this because the round bales I place from the console with gsAddBale POPLAR TRUE (have fillType wood chips) work just fine.

**Comment by Tensuko** [comment]
Closed due to inactivity.
If you have a savegame with fresh created bales on a poplar field, pls attach it here and reopen the Issue.
