### ISSUE TITLE
 Kursgenerierung

### ISSUE THREAD

**Issue by DonBolli** [Courseplay/courseplay#7177]
Ich habe festgestellt, dass bei der Kursgenerierung etwas schiefläuft.
Bei der Option Kurve scharf, scheint er dies auf der ersten Vorgewende Bahn falsch zu machen,

![image](https://user-images.githubusercontent.com/43571844/117132297-f2845c80-ada2-11eb-9858-38072ed3ca05.png)

Ich verwende v6.03.00058, weiss aber nicht wie lange dieses Problem schon existiert.

**Comment by Tensuko** [comment]
Ja weist du es gibt im HUD so eine Funktion mit der man alle Wegpunkte anzeigen kann, das hilft 100 mal mehr als rote Kästchen in einem Bild.
Auch die genutzten Einstellungen im Generator verraten oft etwas und ganz verrückt wird es mit einem logfile mit debugchannel 19.
Debug channel 19 = course save/load/generation
https://github.com/Courseplay/courseplay/wiki/Debug-Channels

**Comment by pvaiko** [comment]
Siehe auch https://github.com/Courseplay/courseplay/issues/7097#issuecomment-821984452

**Comment by DonBolli** [comment]
![image](https://user-images.githubusercontent.com/43571844/117186106-ce447200-adda-11eb-9e13-5bbbef078929.png)

[log.txt](https://github.com/Courseplay/courseplay/files/6429180/log.txt)

**Comment by Tensuko** [comment]
So wir haben die Scharfe Ecke bei deinem großen roten Kasten und die wurde offenbar auch bearbeitet und hinten die runde Ecke, weil das Feld da auch so ein bisschen Rund ist, siehe #7097 wie pvaiko geschrieben hat.

**Comment by DonBolli** [comment]
D.h.: um das Problem zu lösen müsste ich das Feld anpassen? Ich habe nichts bearbeitet - das wurde so generiert.

**Comment by Tensuko** [comment]
Das wurde so generiert, weil, siehe anderes Issue, da ist es erklärt.

**Comment by pvaiko** [comment]
Kannst im Hud Feldrandkurs einschalten dann siehst du wie er aussieht.

**Comment by DonBolli** [comment]
Danke. Habe die cp.lua angepasst, mal sehen ob es nun "funktioniert"

**Comment by DonBolli** [comment]
Dass die Felder nicht immer gut angelegt sind für CP verstehe ich ja. Das ist auch okay. Was ich aber nicht verstehe, warum macht er es das zweite Mal korrekt?

**Comment by pvaiko** [comment]
was meinst du mit zweites Mal?

**Comment by DonBolli** [comment]
Erstes Vorgewende rund, zweits Vorgewende scharf

**Comment by pvaiko** [comment]
Ach so, das ist wie der Algorithmus (grass fire) funktioniert, wenn er die Seiten richtung Feldmitte schiebt eliminiert er auch die Punkte draussen um der Ecke und berechnet einen Schnittpunkt. Wir könnten so etwas theoretisch beim ersten Vorgewende auch machen, aber war nicht die Prioritaet.

**Comment by DonBolli** [comment]
Kann geschlossen werden
