### ISSUE TITLE
Error: Running LUA method 'update'.

### ISSUE THREAD

**Issue by carlstery** [Courseplay/courseplay#7178]
so i was playing on my server on lone oak with about 312 mods. And i was harvesting a field with the help of courseplay and such i had made a grain sellign route too (where i loaded the truck up with a grain cart) and then when i was loading the truck up with barley. I went out my tractor and was running to the side of the truck to look at it, but then my character stops moving. I could not move at all and i was like wtf is going on, it ruin the vibe for me. i tried everything like unpluging my keyboard and such but nothing happened i checked my log and saw this.

2021-05-05 13:39 dataS/scripts/vehicles/Vehicle.lua(2920) : attempt to call method 'getCurrentHelper' (a nil value)
2021-05-05 13:39 Error: Running LUA method 'update'.
2021-05-05 13:39 dataS/scripts/vehicles/Vehicle.lua(2920) : attempt to call method 'getCurrentHelper' (a nil value)
2021-05-05 13:39 Error: Running LUA method 'update'.

millions of those errors. I tried deleting some stuff but it didnt help. So i thought this was my last resort so i hope i can get some help. (i can post my full log if you want me to theres a lot of warning and errors:()

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by carlstery** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6427416/log.txt)

**Comment by carlstery** [comment]
> https://github.com/Courseplay/courseplay/wiki

[log.txt](https://github.com/Courseplay/courseplay/files/6427426/log.txt)

**Comment by carlstery** [comment]
> https://github.com/Courseplay/courseplay/wiki

im using the latest version of courseplay. Courseplay six

**Comment by Tensuko** [comment]
Available mod: (Hash: 6948ae53cfe0f77b18ba0840a0107d07) (Version: 1.0.0.0) ChevroletC70tipper
Error: Unsupported mod description version in mod ChevroletC70tipper

Error: Failed to open xml file 'C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods/exp19_international_4900_pack_unzip_me/modDesc.xml'.
Available mod: (Hash: fbb529d5314389b2cf952e37e7a94adf) exp19_international_4900_pack_unzip_me
Error: Missing descVersion attribute in mod exp19_international_4900_pack_unzip_me

Error: Failed to open xml file 'C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods/Flags_pack/modDesc.xml'.
Available mod:  Flags_pack
Error: Missing descVersion attribute in mod Flags_pack

2021-05-05 13:38 Error: Can't load resource 'C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods/DT275bEdit/dataS/scripts/vehicles/Vehicle.lua'.

2021-05-05 13:38 Error: Vehicle type 'FM_DodgeCrewCab.SuperDuty' has unknown specialization 'FM_DodgeCrewCab.steerable'!

2021-05-05 13:38 Error: Can't load resource 'C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods/FS19_Farmall_460_560_FL/scr/engineSounds.lua'.

2021-05-05 13:38 Error: Can't load resource 'C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods/FS19_JohnDeere_7R/scripts/AddConfig.lua'.
2021-05-05 13:38 Error: Vehicle type 'FS19_JohnDeere_7R.series7R' has unknown specialization 'FS19_JohnDeere_7R.addConfig'!
(looks like our famous JD7R who produces a lot or Errors?)

This is GIANTS Code, smells like Mos Issue:
2021-05-05 13:39 Error: Running LUA method 'update'.
2021-05-05 13:39 dataS/scripts/vehicles/Vehicle.lua(2920) : attempt to call method 'getCurrentHelper' (a nil value)

Might be the "PT 474".

**Comment by Tensuko** [comment]
> 
> 
> > https://github.com/Courseplay/courseplay/wiki
> 
> im using the latest version of courseplay. Courseplay six

Courseplay six is not the Version.
6.03.00058 <- Thats the Version of Courseplay.

**Comment by carlstery** [comment]
> > > https://github.com/Courseplay/courseplay/wiki
> > 
> > 
> > im using the latest version of courseplay. Courseplay six
> 
> Courseplay six is not the Version.
> 6.03.00058 <- Thats the Version of Courseplay.

alright i will try using anothere semi for my grain selling. I will comment what happened.

**Comment by carlstery** [comment]
> Available mod: (Hash: 6948ae53cfe0f77b18ba0840a0107d07) (Version: 1.0.0.0) ChevroletC70tipper
> Error: Unsupported mod description version in mod ChevroletC70tipper
> 
> Error: Failed to open xml file 'C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods/exp19_international_4900_pack_unzip_me/modDesc.xml'.
> Available mod: (Hash: fbb529d5314389b2cf952e37e7a94adf) exp19_international_4900_pack_unzip_me
> Error: Missing descVersion attribute in mod exp19_international_4900_pack_unzip_me
> 
> Error: Failed to open xml file 'C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods/Flags_pack/modDesc.xml'.
> Available mod: Flags_pack
> Error: Missing descVersion attribute in mod Flags_pack
> 
> 2021-05-05 13:38 Error: Can't load resource 'C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods/DT275bEdit/dataS/scripts/vehicles/Vehicle.lua'.
> 
> 2021-05-05 13:38 Error: Vehicle type 'FM_DodgeCrewCab.SuperDuty' has unknown specialization 'FM_DodgeCrewCab.steerable'!
> 
> 2021-05-05 13:38 Error: Can't load resource 'C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods/FS19_Farmall_460_560_FL/scr/engineSounds.lua'.
> 
> 2021-05-05 13:38 Error: Can't load resource 'C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods/FS19_JohnDeere_7R/scripts/AddConfig.lua'.
> 2021-05-05 13:38 Error: Vehicle type 'FS19_JohnDeere_7R.series7R' has unknown specialization 'FS19_JohnDeere_7R.addConfig'!
> (looks like our famous JD7R who produces a lot or Errors?)
> 
> This is GIANTS Code, smells like Mos Issue:
> 2021-05-05 13:39 Error: Running LUA method 'update'.
> 2021-05-05 13:39 dataS/scripts/vehicles/Vehicle.lua(2920) : attempt to call method 'getCurrentHelper' (a nil value)
> 
> Might be the "PT 474".

i tried it with a vinnila truck and it still happens the exact same thing.

**Comment by carlstery** [comment]
> Available mod: (Hash: 6948ae53cfe0f77b18ba0840a0107d07) (Version: 1.0.0.0) ChevroletC70tipper
> Error: Unsupported mod description version in mod ChevroletC70tipper
> 
> Error: Failed to open xml file 'C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods/exp19_international_4900_pack_unzip_me/modDesc.xml'.
> Available mod: (Hash: fbb529d5314389b2cf952e37e7a94adf) exp19_international_4900_pack_unzip_me
> Error: Missing descVersion attribute in mod exp19_international_4900_pack_unzip_me
> 
> Error: Failed to open xml file 'C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods/Flags_pack/modDesc.xml'.
> Available mod: Flags_pack
> Error: Missing descVersion attribute in mod Flags_pack
> 
> 2021-05-05 13:38 Error: Can't load resource 'C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods/DT275bEdit/dataS/scripts/vehicles/Vehicle.lua'.
> 
> 2021-05-05 13:38 Error: Vehicle type 'FM_DodgeCrewCab.SuperDuty' has unknown specialization 'FM_DodgeCrewCab.steerable'!
> 
> 2021-05-05 13:38 Error: Can't load resource 'C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods/FS19_Farmall_460_560_FL/scr/engineSounds.lua'.
> 
> 2021-05-05 13:38 Error: Can't load resource 'C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods/FS19_JohnDeere_7R/scripts/AddConfig.lua'.
> 2021-05-05 13:38 Error: Vehicle type 'FS19_JohnDeere_7R.series7R' has unknown specialization 'FS19_JohnDeere_7R.addConfig'!
> (looks like our famous JD7R who produces a lot or Errors?)
> 
> This is GIANTS Code, smells like Mos Issue:
> 2021-05-05 13:39 Error: Running LUA method 'update'.
> 2021-05-05 13:39 dataS/scripts/vehicles/Vehicle.lua(2920) : attempt to call method 'getCurrentHelper' (a nil value)
> 
> Might be the "PT 474".

so the problem is still a thing sadly.

**Comment by andremeyer123** [comment]
just garbage in the mods folder , delete all mods with error, then new log

**Comment by carlstery** [comment]
> just garbage in the mods folder , delete all mods with error, then new log

Will do

**Comment by andremeyer123** [comment]
Load mod: magnum7200Series
2021-05-05 13:38   Error: Specialization     34 error

**Comment by andremeyer123** [comment]
is my log 
[log.txt](https://github.com/Courseplay/courseplay/files/6432162/log.txt)

**Comment by carlstery** [comment]
im just gonna stop playing tbh and delete it. Ive tried deleting all the mods with errors to no fix it still happens 24/7.

**Comment by andremeyer123** [comment]
log

**Comment by carlstery** [comment]
> log

[log.txt](https://github.com/Courseplay/courseplay/files/6436506/log.txt)

**Comment by andremeyer123** [comment]
Error: Can't load resource 'C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods/Allis_Chalmers_8550_B
Error: Can't load resource 'C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods/FS19_Platte_Valley_JD
delete all mods  error

**Comment by andremeyer123** [comment]
My Games/FarmingSimulator2019/mods/IHC_3588_1981/      delete
My Games/FarmingSimulator2019/mods/FS19_IH_5488_FWA/    delete
My Games/FarmingSimulator2019/mods/EXP19_GMCSierraClassic_K3500   delete 
new log

**Comment by carlstery** [comment]
> My Games/FarmingSimulator2019/mods/IHC_3588_1981/ delete
> My Games/FarmingSimulator2019/mods/FS19_IH_5488_FWA/ delete
> My Games/FarmingSimulator2019/mods/EXP19_GMCSierraClassic_K3500 delete
> new log

ive deleted them all but my game still freezes.

**Comment by andremeyer123** [comment]
always look in the log which mods have to get out

**Comment by carlstery** [comment]
> always look in the log which mods have to get out

yes ik but my log does not update for some reason. because all the errors about mods it says i have deleted but it still says the mod i just deleted is still a error.

**Comment by andremeyer123** [comment]
rename the mods folder in modsss then start the game log then post

**Comment by carlstery** [comment]
> rename the mods folder in modsss then start the game log then post

[log.txt](https://github.com/Courseplay/courseplay/files/6436843/log.txt)

here it again still happens...

**Comment by andremeyer123** [comment]
steam backup function on?

**Comment by andremeyer123** [comment]
![tt](https://user-images.githubusercontent.com/70706468/117347598-92c4a900-aea9-11eb-8b5d-941b1066edb0.PNG)

**Comment by carlstery** [comment]
> steam backup function on?

yes its on

**Comment by andremeyer123** [comment]
test off

**Comment by andremeyer123** [comment]
rename the mods folder in modsss then start the game log then post

**Comment by andremeyer123** [comment]
C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods   
delete mods folder

**Comment by carlstery** [comment]
> C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods
> delete mods folder delete log

whole folder?

**Comment by carlstery** [comment]
> C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods
> delete mods folder delete log

cant i just delete my mods then?

**Comment by andremeyer123** [comment]
they are then in the trash

**Comment by carlstery** [comment]
> they are then in the trash

alright i will just delete the game anyway i dont feel like playing

**Comment by andremeyer123** [comment]
you don't want to and don't do what they say then delete your issus

**Comment by carlstery** [comment]
> you want help
> don't do what we say
> delete your issues

What

> you want help
> don't do what we say
> delete your issues

I do everything you have said what are you on about

**Comment by Tensuko** [comment]
> 
> 
> > C:/Users/carl sterum/Documents/My Games/FarmingSimulator2019/mods
> > delete mods folder delete log
> 
> whole folder?

Why so complicated ?
rename your modsfolder to mods_all
the game will generate a new folder named mods (you can also create a new folder with the same name).

Copy ONLY CP in the folder.
Start your game and try it (also on server, just make a new savegame) see if the Error still comes up.
Start adding mods, in packs with 5 mods per pack maybe, see if you can get error to happen again.
Then one of the mods cause it.
Remove that Mod from your normal savegame.
If Error happens again, check the vehicles.xml from your corrupted savegame and delete the entry of that mod vehicle.

If it is not a vehicle issue, loading the save without CP, save the game and add CP back, can help as well.
Also deleting all CP settings from savegame.

If you not interested anymore, close the issue, if you want the help, then pls do what we say, or ask if you don't know how to to a specific step.

But telling us you did something and the log shows us that you have not done it, is frustating and we loose our mood to help you. Keep that in mind pls.

**Comment by Tensuko** [comment]
Looks like he lost interest.
Anyway, if willed to solve the problem, reopen with required informations.
