### ISSUE TITLE
Slurry tanker not putting down clurry in conjuction with cultivator.

### ISSUE THREAD

**Issue by Flum91** [Courseplay/courseplay#7181]
Im using a zunhammer sk mod with a zunidisc and courseplay to inject slurry. The worker is coupled to the cow barn slurry tank. But when i activate the worker i can hear him switching on the machine but he is not putting down any slurry cause the soil is not changing color and the nitrogen levels stay the same.

[log.txt](https://github.com/Courseplay/courseplay/files/6441686/log.txt)

Edit: It seems to work now all of a sudden...

**Comment by Flum91** [comment]
Mode 5 would be field work yes? I noticed that and changed to mode 4 (slurry/manure/fertilizer)

**Comment by Tensuko** [comment]
Mode5 is simple simple drive from A to B.
Not for Working on the Field.

**Comment by Tensuko** [comment]
Does it work for you now ?
If yes, can we close this ?

**Comment by Tensuko** [comment]
As I guess this was just used wrong mode and not a real Issue, will close this...
