### ISSUE TITLE
CP field identification issue

### ISSUE THREAD

**Issue by gfrantz** [Courseplay/courseplay#7182]
When I'm first setting up a field (let's say field 10) for harvest, everything goes fine.  Harvester is running fine, pickup wagon is working fine and semi transport is as well.  HOWEVER when I go to set up a new field, while field 10 is being worked, (say field 11), I bring a new harvester to field 11 and start it working.  However, when I try to get the pickup wagon and tractor to begin "watching" for the specific harvester in field 11, the harvester is listed as being in field 10 along with all other equipment I have that can harvest, including sub-surface equipment.  If I select the correct harvester, the pickup wagon and tractor do not pick up the harvest in field 11.  Instead, they head off to field 10 to the wrong harvester and the wrong crop.

**Comment by Tensuko** [comment]
logfile ? MP ? SP ? Screenshots ? https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
Alright, thanks for report.
