### ISSUE TITLE
Courseplay won't recognize created fields and crashes computer

### ISSUE THREAD

**Issue by Bananero83** [Courseplay/courseplay#7184]
I loaded a save game with newly created fields (joining of several fields) and the Course Generator stops midway and crashes the game/computer. Won't let me close the game, even through task manager and eventually I just have to restart my computer using they keyboard since the mouse does not work. CP was working great until I created fields. Before I shut down the game before CP was working fine, even on the newly created fields.

**Comment by Tensuko** [comment]
1st, patient is the key.
2nd, logfile ?
https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
closed due to inactivity.
