### ISSUE TITLE
Abfahrer platziert sich falsch neben Drescher

### ISSUE THREAD

**Issue by zJanny** [Courseplay/courseplay#7186]
![20210509134252_1](https://user-images.githubusercontent.com/48256174/117570897-94ba8200-b0cc-11eb-9b53-a64db9c87ab4.jpg)

Wie man hier sieht, der Abfahrer stellt sich falsch neben den Drescher und somit wird der nicht abgetankt

**Comment by Tensuko** [comment]
Und wie man sieht kein logfile, keine Bild vom HUD ob eventuell ein offset eingestellt wurde oder gar ein logfile mit debugchannel 2...

**Comment by zJanny** [comment]
Okay gut mir leid, 
Es funktioniert jetzt alles wieder, es lag wahrscheinlich dran, dass der Drescher in einer Kurve stand.

Ich habe leider kein Logfile von diesem Vorfall
