### ISSUE TITLE
Automatic tool offset not activating after switching from mode 7 to mode 6

### ISSUE THREAD

**Issue by Thorn177** [Courseplay/courseplay#7190]
As requested in the discussion for the New Bale Collector Mode, I have recreated the issue on a smaller field.
Mission to mow, bale, wrap, and deliver a grass field.
!st screenshot shows the mode 6 course I'll use for the wrapper. It has simply being made on the windrower, and copied to the baler, then wrapper.

![fsScreen_2021_05_11_20_09_48](https://user-images.githubusercontent.com/57279160/117819675-5e336180-b29c-11eb-9a76-e60a6983470c.png)

The wrapper has the automatic tool offset as per normal, and quite happily goes along wrapping bales.  I've let it do about 10, before stopping it, clearing the course, driving back into the SW corner of the field, switching to mode 7, making a little Start Stop course, and sending it on its very merry way.

![fsScreen_2021_05_11_20_17_25](https://user-images.githubusercontent.com/57279160/117820893-92f3e880-b29d-11eb-9747-22aafa7d9771.png)

I let it do another 10 or so bales. I had to intervene at one stage when it pushed 3 bales completely 
out of the field without "catching" one, and coming to a complete stop (crazy path finding after restarting, but separate issue).  I've then cleared the mode 7 course, switched back to mode 6, at which stage, the automatic tool offset does not activate.

![fsScreen_2021_05_11_20_24_57](https://user-images.githubusercontent.com/57279160/117822193-e9155b80-b29e-11eb-8a11-deaa9871092b.png)

Disconnecting, and reconnecting to the same tool does not activate it.  You can set it manually.  Connecting to any other tool, including one of the exact same type, activates the automatic offset again, and it keeps working when you attach back to the original unit.

![fsScreen_2021_05_11_20_35_53](https://user-images.githubusercontent.com/57279160/117823270-dea79180-b29f-11eb-9b3f-828373b26337.png)

I get the same behavior from a bale collector.

I do have a log file with channel 6,7, and 18 as requested.  Gist does not like the size of it.....

**Comment by Tensuko** [comment]
Did you click on the smal calculator ?
I was able to simply start mode7, stop it, switch to mode6 and click the calculator to get the offset back.
![fsScreen_2021_05_11_16_59_13](https://user-images.githubusercontent.com/27344744/117838127-5793f280-b27a-11eb-8ed6-1dd36fc39294.png)

**Comment by Thorn177** [comment]
As I said, you can set it manually. So either the calculate button, or the left / right buttons.  

Do you still want a log file?  I can generate another where it doesn't do about 10 bales in mode 7 and make a log file around a 100 000KB in size.  Gist did not like that.

**Comment by Tensuko** [comment]
Don't need a logfile for Mode7 in this Issue.
