### ISSUE TITLE
Manure spreader continues on after source is empty

### ISSUE THREAD

**Issue by crcarmichael** [Courseplay/courseplay#7193]
When using a manure spreader where the helper is automatically pulling from an animal pen, the usual AI helpers stop when the source is empty and a notification appears.  A CP driver in this situation just continues on... the spreading animation also continues but no manure is applied (obviously).

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by leo32128fs** [comment]
> Ao usar um espalhador de estrume onde o ajudante está automaticamente puxando de uma caneta animal, os auxiliares de IA habituais param quando a fonte está vazia e uma notificação aparece. Um driver de PC nesta situação continua... a animação disseminável também continua, mas nenhum estrume é aplicado (obviamente).

I also had this problem and I realized that mode 4 and 6 on seeders or spreaders c activate and I marked mode 6 that was when the problem arose, after realizing the error I went back to mode 4 and it worked perfectly

**Comment by Tensuko** [comment]
Closed due to inactivity.
As a reason test showed, it does work without any Issue.
Guess its the wrong mode.
