### ISSUE TITLE
Not saving mode after restart

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#7195]
Hi,
haven't found anything if it's a feature... after restarting game, CP doesn't remind the mode on which the vehicle was left when exited the game, e.g. i've done field working (mode4 or mode6), and after restarting the game, before it still had this mode active. Now it is always on mode5. Is this wanted? Or a bug? I'm on v6.03.00060

**Comment by Tensuko** [comment]
logfile ?!
https://github.com/Courseplay/courseplay/wiki

**Comment by iljarogoff** [comment]
Was just a question if it's an intended behaviour, but here we go...
[log.txt](https://github.com/Courseplay/courseplay/files/6487576/log.txt)

**Comment by Tensuko** [comment]
From my testing, it depends on what tool gets loaded 1st.
On some I have the correct mode saved, on same it is set to mode5.
