### ISSUE TITLE
Drescher bleibt nicht stehen

### ISSUE THREAD

**Issue by IcemanGSXR** [Courseplay/courseplay#7196]
Mein Drescher ist mit CP am Feld unterwegs, ein hügeliges Feld, als der Tank voll war blieb er nicht stehen sondern rollte solange weiter bis er alleine zum stehen kommt. Das gleiche ist mir beim ULW aufgefallen auch dieser bleibt nicht am Haltepunkt stehen sondern rollt einfach weiter.
CP-Version: letzte Release und auch die Dev-Version probiert. Dieses nicht stehen bleiben tritt bei beiden Versionen auf.
Karte ist die Oberthal und die Steffishausen

**Comment by Tensuko** [comment]
logfile ?
Weis überhaupt nicht was du meinst mit rollt weiter.
Wann genau soll das passieren ?

**Comment by IcemanGSXR** [comment]
Wenn der Drescher bergab fährt und sein Tank voll ist sollte er doch stehen bleiben zum Abtanken! Er hört auf zum dreschen, hebt sein Schneidwerk aber der Drescher selbst rollt weiter bis er dann von alleine stehen bleibt, sprich, mir kommt es so vor das er nicht bremst. Ist mir so ähnlich auch beim Traktor aufgefallen. Erster Wegpunkt geht bergab, er fährt hin, und während des absenkens vom Grubber rollt er weiter und wird dann vom Grubber gebremst und dann nimmt er seine Arbeit auf.

[log.txt](https://github.com/Courseplay/courseplay/files/6487144/log.txt)

**Comment by Tensuko** [comment]
Mit Traktoren konnte ich das nicht reproduzieren (bisher) und Drescher nur am Ende des Kurses.
Hast du vlt Bilder oder ein Video davon, wann es passiert ?

**Comment by IcemanGSXR** [comment]
Mal sehen, ich werde es versuchen

**Comment by IcemanGSXR** [comment]
Bilder habe ich geschafft. Video muß ich mich erst einlesen wie und womit dies funktioniert.

![fsScreen_2021_05_15_20_55_50](https://user-images.githubusercontent.com/6430509/118375334-61429080-b5c1-11eb-96b9-d39841c29355.png)
![fsScreen_2021_05_15_20_55_52](https://user-images.githubusercontent.com/6430509/118375336-643d8100-b5c1-11eb-9d30-d34c948e71e4.png)
![fsScreen_2021_05_15_20_55_53](https://user-images.githubusercontent.com/6430509/118375339-669fdb00-b5c1-11eb-93ba-731d0fa66aa4.png)
![fsScreen_2021_05_15_20_55_56](https://user-images.githubusercontent.com/6430509/118375341-69023500-b5c1-11eb-84de-46f66fe7f7b9.png)
![fsScreen_2021_05_15_20_55_58](https://user-images.githubusercontent.com/6430509/118375344-6b648f00-b5c1-11eb-85e1-85bc5d18e4e6.png)
![fsScreen_2021_05_15_20_56_00](https://user-images.githubusercontent.com/6430509/118375346-6dc6e900-b5c1-11eb-862f-134cf34d322f.png)
![fsScreen_2021_05_15_20_56_02](https://user-images.githubusercontent.com/6430509/118375349-70c1d980-b5c1-11eb-9756-27b0e299b7d3.png)
![fsScreen_2021_05_15_20_56_04](https://user-images.githubusercontent.com/6430509/118375350-73243380-b5c1-11eb-9d91-99cf157907b4.png)
![fsScreen_2021_05_15_20_56_06](https://user-images.githubusercontent.com/6430509/118375354-75868d80-b5c1-11eb-8f3f-b3ee2af19e2e.png)
![fsScreen_2021_05_15_20_56_09](https://user-images.githubusercontent.com/6430509/118375356-77e8e780-b5c1-11eb-95b2-2a125c1b2ee0.png)
![fsScreen_2021_05_15_20_56_12](https://user-images.githubusercontent.com/6430509/118375362-7d463200-b5c1-11eb-98bc-4c768932e2bc.png)
![fsScreen_2021_05_15_20_56_15](https://user-images.githubusercontent.com/6430509/118375366-80412280-b5c1-11eb-82f9-f8cadd5d9d15.png)
![fsScreen_2021_05_15_20_56_18](https://user-images.githubusercontent.com/6430509/118375367-82a37c80-b5c1-11eb-8730-58cbe11497ae.png)
![fsScreen_2021_05_15_20_56_21](https://user-images.githubusercontent.com/6430509/118375371-859e6d00-b5c1-11eb-96a9-602e13da844f.png)

**Comment by Tensuko** [comment]
Also eine DIA-Show musste das nicht werden, es reicht zu sehen welche Situation.

**Comment by andremeyer123** [comment]
40 tonnen schieben den drescher schon mal weiter den berg runter
 teste mal bitte ohne diesen real kram ob es dann immer noch ist danke

**Comment by andremeyer123** [comment]
( bleibt nicht am Haltepunkt stehen sondern rollt einfach weiter.   )   Bremsen mal einstellen hast ja dafür ein mod im ordner der die standart werte aushebelt  
![fsScreen_2021_05_16_12_41_14](https://user-images.githubusercontent.com/70706468/118395242-8f6bb300-b649-11eb-95db-19104a9f09b1.png)

**Comment by Tensuko** [comment]
Wir haben den Fehler schon gefunden, nur müssen wir schauen wie wir den am besten beheben, Geduld ist angesagt.

**Comment by moose31608** [comment]
When I install this update then go to play my game it says that course play is not there
