### ISSUE TITLE
V6.03.00060 Crash on save of route

### ISSUE THREAD

**Issue by a1elecGreg** [Courseplay/courseplay#7197]
After creating a route then save it the hud dissapears and you are left with a blank screen after pressing the right mouse key the page dose not reapear also pressing DEL only toggels the normal help and instrument screen not the courseplae hud you have to exit the game and return to the game to activate it again. It however saves the new course yet to try amenments to a cours and save will however be rolling back to a previous version

**Comment by Tensuko** [comment]
logfile when this happens ?!
https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
Closed due to inactivity.
