### ISSUE TITLE
maybe Problme with CP and AD

### ISSUE THREAD

**Issue by geka79** [Courseplay/courseplay#7198]
Hello

I play this Setting a few month without problems or Freezes.
I only update the AD und CP files.

Now i had the problem by switches the vehicles with TAP, the System frezzes and produce a huge LOG.file.  (1gb)

This problme is happen after a playing some minutes 30-40min.

in the LOG file I deleted the repaeting entrys.

[log_bereinigt.txt](https://github.com/Courseplay/courseplay/files/6487501/log_bereinigt.txt)

**Comment by Tensuko** [comment]
No Idea what this can be.
Need to know more about when this happened.

**Comment by geka79** [comment]
at the last one, i played Hof Bergman, 3 fields harvesting via CP und deliver via AD.
One field "grubber" and one field "düngen"

**Comment by andremeyer123** [comment]
alle mods mit error löschen  . inputbinding auch erstellt das spiel neu 
Error: Index not found: gridLeft
2021-05-15 12:37   Warning (C:/Users/Gerhard/Documents/My Games/FarmingSimulator2019/mods/FS19_MP_Horsch_Pronto9DC
Error: Failed to open xml file 'C:/Users/Gerhard/Documents/My Games/FarmingSimulator2019/mods/IndividualHudFiles/modDesc.xml'.
Available mod: (Hash: 9039a9a61cffb582fec464cb17a2ff04) IndividualHudFiles
Error: Missing descVersion attribute in mod IndividualHudFiles

Warning: Performing emergency garbage collection pass - memory went from 201240 KB to 659539 KB in less than one frame
2021-05-15 12:46 Usage is now 185252 KB; full GC took 164.971200ms    
dein rechner hat soviel im speicher das er beim generieren von kursen abkackt

**Comment by andremeyer123** [comment]
wenn du das gemacht hast bitte einmal eine log bevor du mit cp was machst

**Comment by geka79** [comment]
das der Speicher abkackt: AI Helper ( bei kolli mit umgebeung)

den Rest muss ich ausprobieren

**Comment by Bobster82** [comment]
Hello,
I just started with FS again and this problem happend to me too... I cant find where its from. It can happen when im 5min in the game or 30 min. It happens with "TAB", "CP click to switch", "click on the map to switch" ... so when switching to other vehicles...

I dont know if its CP related or AD or completely something else....
What can we do to get more info in the log about this problem? Any ideas? I keep testing things, but takes time. lol

p.s. can we continue in english here, so its easier to follow ;)

**Comment by andremeyer123** [comment]
Log ?

**Comment by Bobster82** [comment]
> Log ?

Didnt save my log from yesterday. Will drop my log today. Just wanted to say that he wasnt the only one :P
Any usefull debug settings maybe?

**Comment by andremeyer123** [comment]
My Games\FarmingSimulator2019       there the log please

**Comment by Bobster82** [comment]
> My Games\FarmingSimulator2019 there the log please

I know ;) But my log was overwritten with a new one when i closed the game and started again.
So I need to "get the game crash again" to get the log needed here ;)

**Comment by Tensuko** [comment]
I had no Issues with only CP on over 1 hour server time and also not over 2 hours SP time.

**Comment by Bobster82** [comment]
Here is my log:
[log.txt](https://github.com/Courseplay/courseplay/files/6488974/log.txt)

**Comment by andremeyer123** [comment]
Error: Farmland-Id 77 not defined in farmland xml file!
Error: Can't load resource 'C:/Users/Bobster/Documents/My Games/FarmingSimulator2019/mods/FS19_usalegend/newFruits/huds/hud_fill_soybean.png'. 
map the errors must be corrected

**Comment by Bobster82** [comment]
> Error: Farmland-Id 77 not defined in farmland xml file!
> Error: Can't load resource 'C:/Users/Bobster/Documents/My Games/FarmingSimulator2019/mods/FS19_usalegend/newFruits/huds/hud_fill_soybean.png'.
> map the errors must be corrected

I cant understand this is the problem... I played this map before whitout any problems. (few months back)
But if u want, I can open that map and edit it to solve those problems ;)

**Comment by Tensuko** [comment]
Try to remove (Version: 1.0.2.0) FS19_BulkBuy

**Comment by Bobster82** [comment]
Im playing with the same settings and mods but whitout AD ... now 1 hour into the game and no crashes yet... will keep playing until it crashes or the next hour...
Then i will remove all other mods and only AD, maybe its an AD issue.. keep u informed

**Comment by andremeyer123** [comment]
[FS19_AutoDrive.zip](https://github.com/Courseplay/courseplay/files/6489097/FS19_AutoDrive.zip)
test this ad version thanks

**Comment by Bobster82** [comment]
> [FS19_AutoDrive.zip](https://github.com/Courseplay/courseplay/files/6489097/FS19_AutoDrive.zip)
> test this ad version thanks

Is it the official 1.1.0.7 version or did you change something in it?
And I was going to test 1.1.0.8 (1.1.1.0 is the latest AD, and that was a version prior to that) after my CP test where im in now. (1.1.1.0 is the latest AD)

**Comment by andremeyer123** [comment]
is changed for new cp version

**Comment by Bobster82** [comment]
Update:
2 hours ingame without AD, no crashes.
Reloading game with AD version from @andremeyer123

**Comment by Tensuko** [comment]
If you are done with the next hour, can you close this here and go over to AD ? You can also link this Issue so they can check it out.

**Comment by Bobster82** [comment]
Im done with my testing. No more crashes here, so the problem must be AD related.
I cant close this, as this isnt my thread. @geka79  ?
@andremeyer123  thanks for the updated "old AD" , this one doesnt crash.

**Comment by Tensuko** [comment]
@geka79 
ich denke das Problem ist gefunden, du kannst dir ja auch die abgeänderte 1.1.0.7 von AD hier laden.
Ansonsten bei AD melden mit Verweis auf dieses Issue.
Wenn die Kollegen sonst mehr dazu wissen, gerne wieder hier melden.
Erstmal du damit.

**Comment by Stephan-S** [comment]
Hello,
@Bobster82 did some more analysis and narrowed the error down to the moment where CP passes control to AD for parking the vehicle.
Would you mind looking into this again on your side? Is it possible that CP is skipping some event to disable  'something' :D
Given the error messages it sounds like some possible hierarchy issue with the vehicle's root node.

If you can't find something with that info, I will start looking into it more deeply on the AD side, but for now I see it as more likely that this is a CP issue. But please let me know if I should start looking again.

**Comment by andremeyer123** [comment]
Fehler kommt erst ab der version  1.1.1.0) FS19_AutoDrive alle anderen ad versionen  
https://github.com/Stephan-S/FS19_AutoDrive/pull/1872   mit dieser version war der fehler auch nicht .
mfg

**Comment by Bobster82** [comment]
I think CP needs to call stopdriver(whatever the method is called) before it hands over to AD to park (end of the course)
This sounds most likely to me, as CP is done before handing over to AD, why does AD needs to shutdown CP ?
Or AD needs to call stopdriver 1st before it gets the park call

**Comment by andremeyer123** [comment]
aber irgent etwas war doch das man von cp nur in 1 oder 2 modis zum parken schicken kann wenn ich mich nicht täusche.

**Comment by Bobster82** [comment]
I tried to re-create the crash again, but I can't... suddenly the game doesnt crash, but I get an error (where normal the game would crash)
Maybe this is some info that could help? (or getting more confused, I dont know anymore :P )

2021-05-21 17:49   Info: 9340 TTV Warrior: AutoDrive:StartDrivingWithPathFinder(6, -3, nil, nil, nil)
2021-05-21 17:49   Info: 9340 TTV Warrior: AutoDrive:StartDriving(6, -3, nil, nil, nil)
2021-05-21 17:49   Error: [AutoDrive] Could not calculate path - shutting down
2021-05-21 17:49   Error (data/vehicles/deutz/series9/series9.xml): Failed to update suspension node 228652. Node does not exist anymore!
2021-05-21 17:49   Info: 9340 TTV Warrior: AutoDrive:GetParkDestination()
