### ISSUE TITLE
Manure spreader and convoys

### ISSUE THREAD

**Issue by djnekkid** [Courseplay/courseplay#7199]
Hi Awesome devs!

This is probably not just with manure spreaders, but:
I made a 12m wide course with a seeder (18kmh) and a manure spreader (20kmh). I started the seeder a few minutes before the manure spreader. They both had convoy activated, so they dont crash into eachother (hopefully).
But when there were a couple of rows left, the manure spreader cought up, and had to wait a few seconds to make sure the >100m separation kicked in again. However, the spreader were still spraying, and thus wasting muck. 
I'd suspect this is a thing with 'regular' fertilizers, limers and probably liquid sprayers as well.

Known bug?

Need more info?

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by djnekkid** [comment]
yes they do :) Generated with the seeder, copied into the muck spreader

**Comment by Tensuko** [comment]
will have a look later

**Comment by Tensuko** [comment]
works just fine
![fsScreen_2021_05_17_19_23_53](https://user-images.githubusercontent.com/27344744/118530887-78aa8680-b745-11eb-9c55-b67433ab87fb.png)

**Comment by djnekkid** [comment]
could slurry injectors work different then the "shoot stuff out from the back" type of gear?

**Comment by Tensuko** [comment]
no

**Comment by Tensuko** [comment]
Could be that you copy the course, not sure if there is a difference.
Save your seeder course and load it with the manure spreader.

**Comment by djnekkid** [comment]
im in seasons in that game, but i'll run a few tests on a 'fresh' map with no mods

**Comment by djnekkid** [comment]
With a copied course, i still observe the same with manure spreaders:
![image](https://user-images.githubusercontent.com/65364380/118627040-aa663080-b7cb-11eb-894c-059e0a70c71f.png)

Same with the Axis 'back of the tractor attached' solid spreader:
![image](https://user-images.githubusercontent.com/65364380/118627572-22ccf180-b7cc-11eb-9248-9cdfbcaed601.png)


I saved the 'front' course, and loaded it on the spreader, and still the same:
![image](https://user-images.githubusercontent.com/65364380/118627786-4e4fdc00-b7cc-11eb-99ad-441f30c5ccae.png)

In theese cases the seeder were at the end of the course, just to 'provoke' the stopping of the spreader, but i do observe the same with the spreader 'catching up' to the seeder.

**Comment by Tensuko** [comment]
(Version: 6.03.00059) FS19_Courseplay
https://github.com/Courseplay/courseplay/releases/tag/6.03.00061

I still can't follow what you are doing.
Temp course, test sprea, weird position where manure spreader continues, how to figure out whats going on...

If I start my worker one after the other on the same course and have convoy on on both, it works just fine.

**Comment by djnekkid** [comment]
i'll try to record a video then :)

**Comment by djnekkid** [comment]
Video time.

https://youtu.be/BETPyjWwxDE

Do you understand the issue now?
(updated to the most recent, not just "1 off" :) )

**Comment by Tensuko** [comment]
Aaahhh NOW I got it.
So it sprays even if he is not driving becouse he have to wait for the Driver in front of it!
Okay sry maybe I missed that point, thanks for make that more clear :)

I am not sure if we will change that, as it would mean we have to turn the tool off and on again for a few meters untill he catched up again and this is a mostly unrealistic scenario...

I would rather suggest you to wait untill the 1st one is finished or (if that does work, not sure) slow the sprayer down so he is at least 1km/h slower then the seeder.

**Comment by djnekkid** [comment]
this was an extreme case tho.
in the original case it was about 30minutes of work to sow, and about 5 minutes in i started the muck spreader, but it cought up in the end.

It might not be super realistic, but when playing on seasons with CP, its quite the waitinggame, so getting two things done more or less at once when you are on 1x anyway, seems to be a timesaver.

However, lets say i've put something in the field to store over winter, and forgotten to move it, the first vehicle stops, and the second one can stay there for possibly minutes filling the field with a 30cm layer of muck ;)
Sure, i'd get a 'vehicle 1 is slowing down for traffic' message, but I might be busy saving the overfilled bunkersilo or something at the time, so it might take a minute or two 'rescueing' the stranded vehicle1.

So its mainly not the second or two thats the kicker, but the more lenghty ones.

Another example might be if you have a multi-tool setup, where i perhaps use two muck sprayers, and the 2nd one have a quicker change-of-lanes, and when they come to the end of that lane, it will stand there pushing a 10cm layer of muck.

I guess i could turn off convoys, but that seem to create more problems, as vehicles tend to crash into eachother more. Atleast it have in the past :)

Anyway, thanx again for a great mod. Its keeping me comeing back to "Farming simulator tycoon" :)

**Comment by polosubtil** [comment]
Hi @djnekkid 
In that case, why don't you put your muck spreader before the drill ? That would be even more realistic as you would normally spread before drilling

**Comment by djnekkid** [comment]
because it was already plowed or cultivated and muck spread before. Adding a drill with fert + post-muck and all 3 states of seasons fert-states are done :)

**Comment by djnekkid** [comment]
another usecase, you put out your cultivator and muck spreader, and run them one after another, and when the first one, but its a somewhat large field, so you go and do the dishes or watch some youtube, and then the first one have come to the end, and the 2nd one is filling the field.

Something like:
do a framecount if the vehiclespeed is 0, if more then 120 frames (2 seconds worth), then 'do the same as when you turn'. But im no programmer, just a general nerd ;)
