### ISSUE TITLE
Not installed 

### ISSUE THREAD

**Issue by moose31608** [Courseplay/courseplay#7201]
Once I install courseplay into my mod folder and then I start the map I’m playing it says no courseplay found

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki !!!!

**Comment by moose31608** [comment]
That fixed it. Thanks

**Comment by andresmit1984** [comment]
I don't know what Moose31608 has done, but it's not working here.
[log.txt](https://github.com/Courseplay/courseplay/files/6490175/log.txt)

**Comment by andresmit1984** [comment]
Well i don't know if the file has been re-uploaded but after downloading Courseplay again, the savegame loads fine.
