### ISSUE TITLE
issue clarification. right click hud will not turn off and stay off

### ISSUE THREAD

**Issue by randogaming6252** [Courseplay/courseplay#7206]
so to clarify my issue, i have been experiencing a weird little bug/glitch where even after disabling right click Hud, if I hold down the right click on my mouse to use a front loader bucket, the second i release it the menu pops back up instantly and refuses to disable, even after disabling it in the settings. this has occurred with every vehicle in the game and has been happening for a little bit now.
the disable right click Hud option is not functioning on the vehicle level or global level as I have tried both.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki !!!

**Comment by randogaming6252** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6496453/log.txt)

**Comment by randogaming6252** [comment]
issue is no longer an issue, at least at this moment. it appears that courseplay can be affected by subtle lag. upon updating the glitch/bug has stopped persisting on every map except chellington farm. on chellington this glitch still does persist, primarily when there's manure in the cow pen. that whole area seems to bring out the worst of mods and ui's.
