### ISSUE TITLE
Slight issue in UI logic with CP Editor

### ISSUE THREAD

**Issue by Imsvale** [Courseplay/courseplay#7212]
**Steps to reproduce**
1. Create a new course (2-3 waypoints will do)
2. Save course as A
3. Using [the in-game course editor](https://github.com/Courseplay/courseplay/issues/4735), change the course in some obvious way (e.g. move the end point)
4. Save changed course as B
5. Clear current course, and load A
6. Repeat with B
7. Observe that A and B are identical
8. Clear current course and reload course list
9. Load A and observe that it is now unaltered from the originally saved A.
10. Load B and observe that the change has been applied.

This might be clearer if you save as A, then immediately save as B (so now B is a copy of A, and changes to B should not affect A). Only _then_ alter the course and save as C. Clear course and reload A, B and C in turn. Observe that they are initially all identical until the course list is reloaded, at which point only C reflects the change. This to demonstrate that the editor does not change the previously saved course A, even while A is still the loaded course, unless you use the save hotkey associated with the editor (or the normal save button). However if you play on without reloading the course list, you will be led to believe that A was also changed. This got me quite confused on a number of occasions, and can lead to a lot of inconsistencies down the line. You thought you had a course set up a certain way, and the next time you start the game, it's entirely different. Or, as me, you might create one course, then derive a second course from it with some small additions or changes, then note that the original course was also changed and all my efforts to preserve the original were in vain (and maybe I'll delete it because now it's just a duplicate) -- except it was actually just fine in the background and all I had to do was reload the course list.

I believe this issue just stems from the fact that the UI was not originally designed with live editing in mind, so it doesn't update the courses and their waypoints when they are changed by the editor. As such there seems to be some confusion as to which waypoint belongs to which course, until the course list is reloaded, which requires conscious effort on the player's part (and therefore knowledge of the problem). Probably has something to do with caching of waypoints in the currently loaded course list, or something like that.

Suggested rudimentary fix: Reload the course list whenever something is changed/committed by the editor. Until something more clever and efficient can be cooked together, unless it can be done right away.

Lastly, perhaps an even simpler demonstration of the problem:
1. Create a new course
2. Save as A
3. Make a simple change using the editor, but then immediately clear current course (especially no save hotkey, no toggle editor hotkey, and no normal CP save button, nothing).
4. Load course A and observe that it seems to have been changed and saved.
5. Reload the course list and load A again.
6. Observe that A was not changed after all.

**Summary**
Despite appearances, the editor does not commit changes to a course unless you explicitly save them using either the save hotkey for the editor, or the normal Courseplay save button (which is good and correct). However, the cached(?) course waypoints _are_ changed, and so the player is led to believe their course has been altered, even without actively saving it in any way.

On a separate note, thank you very much to @russbeuker for sharing his creation. I have been in desperate need of such an editor since I first tried Courseplay.

**Comment by Tensuko** [comment]
> **Summary**
> Despite appearances, the editor does not commit changes to a course unless you explicitly save them using either the save hotkey for the editor, or the normal Courseplay save button (which is good and correct). However, the cached(?) course waypoints _are_ changed, and so the player is led to believe their course has been altered, even without actively saving it in any way.

There is no way arround it. Thats how it works and how it is discribed.


> Suggested rudimentary fix: Reload the course list whenever something is changed/committed by the editor. Until something more clever and efficient can be cooked together, unless it can be done right away.

That might be an Idea, will have a look but thats rly not on our todolist right now.
