### ISSUE TITLE
6.4.0.0-Version is incompatible with Seasons 1.3.2.0

### ISSUE THREAD

**Issue by Chiller2019** [Courseplay/courseplay#7217]
Hey Guys,

CoursePlay-Version: v6.4.0.0
Seasons-Version: 1.3.2.0

The Game is freezed (only Mouse and Keyboard, Vegetation its ok) when you start a new Savegame.

The Problem is only the Seasons-Mod.

I dont have a Log-File because I was triggerd and installed the v6.04.

**Comment by Tensuko** [comment]
Without logfile we can't do anything.
https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
Beside that, just started a map with seasons and CP so it works just fine.

**Comment by Tensuko** [comment]
![fsScreen_2021_05_23_18_02_54](https://user-images.githubusercontent.com/27344744/119267977-24921d00-bbf1-11eb-8858-b6144b240f38.png)
