### ISSUE TITLE
just want some info 

### ISSUE THREAD

**Issue by devilboy123** [Courseplay/courseplay#7218]
hi just wordering if couseplay and pro seed would work togeter e,g will couseplay put tram line in thank you

**Comment by Tensuko** [comment]
#6571

**Comment by marc950** [comment]
ich würde mir auch wünschen das cp und proseed zusammen arbeiten würden

**Comment by KITT3000** [comment]
@marc950 use the latest version of CP and PS from the author's github (on MH there is an old version)
