### ISSUE TITLE
Rückwärtsfahrt mit Great Plains Y2425A

### ISSUE THREAD

**Issue by BauerNepo** [Courseplay/courseplay#7221]
Hallo zusammen,
wie immer erstmal ein grosses Dankeschön für eure tolle Arbeit. Ohne Euch wäre LS nur halb so gut :-) .

Ich habe leider regelmässig ein Problem beim säen mit der originalen Einzelkornsähmaschine Great Plains Y2425A. CP ignoriert beim Rückwärtsfahren die besagte Sähmaschine komplett, so dass sich CP festfährt. Hier ein Video https://youtu.be/dAPKRG9djvQ.

Das passiert beim wenden, wenn der Wenderadius am ersten oder letzten streifen wegen der Überlappung zu gross ist oder beim Übergang von Vorgewende zu Feldreihen, sowie gelegentlich bei Nachfüllkursen. Halt jedes mal, wenn CP zurücksetzten will. Da sich CP jedoch nicht völlig festfährt, sondern halt einfach nicht auf der geplanten Route rückwärts fährt, kommt auch keine Meldung dass der Abfahrer feststeckt. Also ist es manchmal ärgerlich, wenn man feststellt das CP schon länger am rückwärtsfahren ist ohne sein Ziel zu erreichen.
Ich nutze die Sähmaschine mit der Dreipunktaufnahme, sie lässt sich aber auch mit Kugelkupplung konfigurieren.
Könnt Ihr euch das bei Gelegenheit mal ansehen?
Besten Dank.
Hier noch meine Log:
[log.txt](https://github.com/Courseplay/courseplay/files/6533013/log.txt)

Gruss BauerNepo

**Comment by Tensuko** [comment]
Kupplungsart ändern, wurde hier schon oft besprochen. (ist konfigurierbar bei der Saatmaschine).
