### ISSUE TITLE
La Coronella 

### ISSUE THREAD

**Issue by Meeckle** [Courseplay/courseplay#7230]
When Courseplay is used on La Coronella, the info display box, and the Courseplay box, don't appear.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Meeckle** [comment]
I cannot open the Courseplay HUD to do this, I'm afraid.

**Comment by Tensuko** [comment]
But what you can do is add a logfile ?!

**Comment by Meeckle** [comment]
Ok, I will try this.  Sorry, I should have said, I have brain damage, I get confused easily.

**Comment by Tensuko** [comment]
Did you find the logfile ?

**Comment by Tensuko** [comment]
Closed due to inactivity. Reopen with requested information.
