### ISSUE TITLE
[Frage] Ballen sammeln

### ISSUE THREAD

**Issue by DonBolli** [Courseplay/courseplay#7231]
Es gibt bei CP die möglichkeit Ballen zu sammeln und dann an AD zu übergeben für das Entladen. Dies funktioniert bei mir nicht, da AD nie läuft. CP braucht einen Kurs um zu starten, also habe ich neben dem Feld 3m grade aufgezeichnet, jetzt fährt er nur Strecke - Feld - Strecke, dies obwohl ich ihm gesagt habe AD nehmen zum entladen.
Ich wurde auf eurer Homepage und bei Youtube leider nicht fündig.
Wie muss ich den Kurs korrekt aufzeichnen bzw. was muss ich einstellen/beachten?

**Comment by 60erjonny** [comment]
Hallo

Bitte sieh dir dieses Video an...https://www.youtube.com/watch?v=98TIUAgazZg&t=115s
Zur Ergänzung: Das Ganze geht nur ohne AD...!

**Comment by DonBolli** [comment]
Danke mit CP weiss ich wie,das es mit AD nicht geht wusste ich nicht. Dachte wenn es die Funktion gibt im HUD gibt, muss es gehen 🙈

**Comment by 60erjonny** [comment]
Hallo
Ist vieleicht irgend wann Mal vorgesehen...!?!

**Comment by Tensuko** [comment]
Nein das geht noch nicht mit AutoDrive!
