### ISSUE TITLE
Course generator 

### ISSUE THREAD

**Issue by BejanCorneliu** [Courseplay/courseplay#7235]
![bug2](https://user-images.githubusercontent.com/10681553/120666897-a3127880-c495-11eb-917c-d77d47d91b9d.PNG)
![bug1](https://user-images.githubusercontent.com/10681553/120666956-b1609480-c495-11eb-8fb7-bdfc87bdc140.PNG)
I have 4 fields united and extended as log as borders let me.
When i added the last field ( 17 ) the course generator give me on all tools a longer path.
v6.4.0

**Comment by andreasthu** [comment]
In the Southampton of field 17 there is a grass field.
Maybe you are plowing to much and connect field 17 with the grassfield.
Lg
Andreas

**Comment by Tensuko** [comment]
Jep, your broke the border so you got the next field too.
