### ISSUE TITLE
Kurse Generator funktioniert nicht mehr 

### ISSUE THREAD

**Issue by Playlord75** [Courseplay/courseplay#7237]
hey hab mir vor ein paar minuten die neuen CP version heruntergeladen nun hab ich aber das Problem das der kurz Generator nicht mehr funktioniert  und er schmeißt auch Fehler 
![fsScreen_2021_06_04_12_48_05](https://user-images.githubusercontent.com/71101944/120790355-22a25500-c533-11eb-9c08-a67c0300e183.png)
wehre nett wenn man mir sagen kann woran das liegt

hier noch die log 
[log.txt](https://github.com/Courseplay/courseplay/files/6597873/log.txt)

**Comment by Tensuko** [comment]
Welche Einstellungen hast du gemacht ?
Bzw wenn er nicht mal mehr auf geht, kannst du mal die vehicles.xml aus deinem savegame hier anhängen ?

**Comment by Playlord75** [comment]
[vehicles.txt](https://github.com/Courseplay/courseplay/files/6597926/vehicles.txt)

**Comment by Playlord75** [comment]
dazu er lies sich von anfang an garnicht erst öfnen ist der standart 900 vario aus dem spiel

**Comment by Playlord75** [comment]
ok hat sich erledigt hab einmal gespeichert und das save game neu geladen und jetzt geht es komisch xD

**Comment by Tensuko** [comment]
Hast du zufällig vorher eine Mission gemacht, also einen Kurs auf einem Missionsfeld generiert ?

**Comment by Playlord75** [comment]
ne war kommplet neues savegame
