### ISSUE TITLE
Schaufelmodus

### ISSUE THREAD

**Issue by DonBolli** [Courseplay/courseplay#7238]
Hallo

Ich verwende CP 6.4  dabei ist mir aufgefallen, das neue Kurse für den Schaufelmodus nicht richtig funktioniert. Kurse von früher funktionieren einwandfrei. Leider konnte ich die Debug Channels nicht aktivieren, Das Problem ist er lädt einen Teil vor dem Trigger ab.

[https://www.youtube.com/watch?v=nM4NhXZDaWg](https://www.youtube.com/watch?v=nM4NhXZDaWg)
[log.txt](https://github.com/Courseplay/courseplay/files/6600593/log.txt)

**Comment by Tensuko** [comment]
ModHub Version ?
GitHub Version ?

**Comment by DonBolli** [comment]
CP version, gezogen auf GitHub

**Comment by Tensuko** [comment]
Bleib bei der ModHub Version.
Ich mach später noch ein Video, wie der neue Kurs funktioniert.

**Comment by DonBolli** [comment]
Sollte GitHub 6..4 nicht gleich sein wie ModHub 6.4? Ich probiere es nochmals mit der ModHub Version

**Comment by Tensuko** [comment]
Und 6.04 das ist auch nicht die ModHub Version.
Korrekt ist 6.4.0.0 (wir mussten das so anpassen)
