### ISSUE TITLE
[Frage] Schaufelmodus

### ISSUE THREAD

**Issue by DonBolli** [Courseplay/courseplay#7240]
Hallo

Ich habe mir CP aus dem ModHub geladen, was mir noch fehlt ist die Anleitung, diese kann auch schriftlich sein.

Was ich jedoch nicht begreife, warum meine alte Kurse noch einwandfrei funktionieren, diese wurden ja auch nach dem alten Muster aufgezeichnet.

**Comment by Tensuko** [comment]
Das kann ich dir nicht sagen, da ich nicht weis wie die aussehen....

**Comment by Tensuko** [comment]
Video zum alten Kurs hier: https://youtu.be/er2QKoOKkxk (das editieren am letzten Wartepunkt würde ich nicht machen).

Schriftliche Infos hier: http://courseplay.github.io/courseplay/en/index.html (nicht 100% aktuell).

**Comment by DonBolli** [comment]
Kenne ich beides, beides entspricht dem was ich gemacht habe (alte Variante)

**Comment by Tensuko** [comment]
Warte bitte auf das nächste Update.

**Comment by Tensuko** [comment]
Siehe #7239
