### ISSUE TITLE
Nochmal ne wiederhohlung zum Kursgenerator funtioniert nicht ( warum hab ich warscheinlich rausgefunden )

### ISSUE THREAD

**Issue by Playlord75** [Courseplay/courseplay#7241]
Hey ich hab schon wieder das problem das der Kurs generator in der version von gestern nicht richtig funtioniert ich bin dem problem aber jetzt auf die spur gekommen anscheinend Funtioniert er nicht wenn man das fahrzeug neu gekauft hat wenn ich einmal speicher und bende funtoiniert es hier das beispiel

Fendt war gekauft hab einmal gespeichert und spiel bendet dann funtioniert der kurs generator 
![fsScreen_2021_06_05_13_59_09](https://user-images.githubusercontent.com/71101944/120890968-4d111280-c606-11eb-9c3f-8827dd5fdc65.png)
![fsScreen_2021_06_05_13_59_07](https://user-images.githubusercontent.com/71101944/120891034-ab3df580-c606-11eb-9286-51d761320cc3.png)

Claas neu gekauft ohne speichern und ohne spiel neu laden kurs generator funtioniert nicht
![fsScreen_2021_06_05_13_59_32](https://user-images.githubusercontent.com/71101944/120891003-7c278400-c606-11eb-9c15-48821907125e.png)

so einmal gespeichert und neu geladen schon geht es 
![fsScreen_2021_06_05_14_06_39](https://user-images.githubusercontent.com/71101944/120891198-8f871f00-c607-11eb-91b1-b7894ab78d83.png)
![fsScreen_2021_06_05_14_06_44](https://user-images.githubusercontent.com/71101944/120891201-9150e280-c607-11eb-80c3-34a772c334c8.png)

anscheinend hat cp irgendein problem mit neu gekauften fahrzeugen keine ahnung ob ihr das nachfolziehen könnt

**Comment by Tensuko** [comment]
Wenn du schon auf unserem Master Branch unterwegs bist, statt die ModHub Version, dann zieh dir bitte auch die neuesten Commits:
https://github.com/Courseplay/courseplay/commit/6aa019bafb8b250a26ede458d5511e4b6d3ff57b

Branch neu laden!
