### ISSUE TITLE
Fehler mit Fahrzeug verband 

### ISSUE THREAD

**Issue by Playlord75** [Courseplay/courseplay#7244]
es gibt ein problem mit dem fahrzeug verband modus unzwar kann man nicht mehr einstellen wo die helfer fahren sollen sonder man kann nurnoch hinten auswählen Fahrzeuge auf dem selben kurs 2 
![fsScreen_2021_06_06_15_32_23](https://user-images.githubusercontent.com/71101944/120926352-bfecbd00-c6dc-11eb-9a0d-1cbd7e815a6c.png)

und wenn man hinten ausgewählt hat fährt er links

**Comment by Tensuko** [comment]
ModHub Version, oder aktueller Branch ?

**Comment by Playlord75** [comment]
aktuel

**Comment by Tensuko** [comment]
2021-06-06 16:15 Error: Running LUA method 'mouseEvent'.
2021-06-06 16:15 I:/Dokumente/My Games/FarmingSimulator2019/mods/courseplay/settings.lua:180: attempt to perform arithmetic on field 'multiTools' (a nil value)

**Comment by leo32128fs** [comment]
I also have problems with making the machines work in convoy, one always stays in the center and the other doesn't even have to configure

**Comment by leo32128fs** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6605205/log.txt)

**Comment by Tensuko** [comment]
Could you try the latest push and report ? (download the branch).

**Comment by Tensuko** [comment]
Just tested, is fixed on master branch.
