### ISSUE TITLE
Ladewagen: angehängter Abfahr Kurs wird nicht ausgeführt.

### ISSUE THREAD

**Issue by Foss-ops** [Courseplay/courseplay#7245]
Ich probier schon seit 2 Tagen, aber ich kriege es nicht hin, ,das der Ladewagen mit gemähten Gras zum Silobunker fährt.
Kurs 1 Feldarbeit Gras sammeln mit Ladewagen funktioniert, dann bleibt er einfach voll stehen trotz angehängtem Abfahrkurs in den  Hofsilobunker.
Bei Dreschern abtanken und bei Stroh sammeln funktioniert alles einwandfrei.
Verschiedene Ladewagen hab ich ausprobiert, das war es nicht.
Verschiedene Modi hab ich getestet aber ohne Feldarbeit Modus sammelt er halt  kein  Gras.
https://youtu.be/aFzivuKU8ig  Kurz das Problem aufgenommen.

**Comment by Tensuko** [comment]
Kurs angefügt mit + Ordner oder normalen Ordner ?
Ansonsten -> logfile ( https://github.com/Courseplay/courseplay/wiki )

**Comment by Foss-ops** [comment]
Beides probiert, 
Kurs 1 normal kurs 2+
kurs 1+ Kurs 2 +
Kurs 1 und 2 Normal

Hier die Log von der heutigen Session: 
https://pastebin.com/ZM7PVX0S

Der Error am Schluss kam von einem Game Absturz als ich den BigM500 Kurs pausiert hatte um einen Fahrfehler zu korrigieren.
Das Unload Kurs Problem war Stunden vorher.

**Comment by rellek82** [comment]
Hast du evtl. bei AD "Abfahren bei" auf 100% stehen? Wenn ja, ändere das mal auf 80% runter. CP füllt die Anhänger meist nur bis 95 oder 99%, und dann fährt AD nicht weiter.

**Comment by Tensuko** [comment]
Ok muss ich mir anschauen.
ModHub Version oder aktuellen Branch?

**Comment by Foss-ops** [comment]
> 
> 
> Ok muss ich mir anschauen.
> ModHub Version oder aktuellen Branch?

Immer von hier, 6.4.0 stand da glaub ich

**Comment by Tensuko** [comment]
Was heist immer von hier ?
Branch oder Release ? Bitte genauer angeben oder einfach im ModHub laden!

**Comment by Foss-ops** [comment]
Sorry, Hier auf Github auf latest Release geclickt und runtergeladen. 
https://youtu.be/5r2sHm7ZAB4
Hier ist ein Clip  wie es bei Stroh einwandfrei tadellos funktioniert, ein anderes Feld und Stroh statt Gras. Falls  das was hilft.
Ich werde bei dem  Stroh Feld ebenfalls  Gras anpflanzen und dann nochmal Testen. Ladewagen ist derselbe,, Also hab ich Feldfrucht und  Feld  als Variablen.

**Comment by Tensuko** [comment]
Für eine Lösung müssten wir erst mal das Problem eingrenzen.
Was mich halt wunder ist, dass es auf deinem Strohfeld funktioniert.
Ich wüsste keinen Grund, warum es bei Gras nicht klappen sollte.

Wo es abgeladen wird, spielt beim losfahren vom aktuellen WP zum Abladekurs erst einmal keine Rolle.
Teile uns gerne weitere Beobachtungen mit, ich muss sehen wann ich Zeit finde mir das selber mal anzuschauen, daher wäre ich dir dankbar wenn du weiter berichtest (Bilder, Videos). Eventuell logfile mit debugchannel 6, 11, 15

**Comment by Foss-ops** [comment]
Gebe mein Bestes hier =)
weitere Beobachtung, HEU hat dasselbe Problem auf dem Feld, wo das Gras auch nicht abgefahren werden wollte. Anderes Feld noch nicht getestet. Arbeite dran.
Weitere Tests folgen.  Debugchannel Knöpfe hab ich schon gesehen,  muss mich erst schlau machen wie ich das verwende.

**Comment by Tensuko** [comment]
> Weitere Tests folgen. Debugchannel Knöpfe hab ich schon gesehen, muss mich erst schlau machen wie ich das verwende.

Am besten den neuesten Stand vom Master Branch laden, aktivieren und dann einfach CP laufen lassen, dann wird alles in die log.txt geschrieben.

**Comment by Foss-ops** [comment]
Da bin ich wieder. 
-Master Branch von Github runtergeladen, die Dateien neu gezippt und in den Mods Ordner gepackt.
-Neues Feld, (frisch gepflügt, keine Vermischung von altem Heu/Gras) abgemäht und wie üblich Abfahrkurs eingefahren.
-Großes Durchfahrsilo gelöscht (kein Mod Silo) aus Angst wegen Trigger des angrenzenden Hofsilos, und einen Medium Durchfahrsilo (kein Mod) woanders hingestellt.
- Abfahr- Fahrzeuge sind dieselben
- Kurs mit + an den Mähkurs angehängt, wie immer.
- Debugchannel Aktiviert
Und es funktioniert https://youtu.be/KNZ8773kaJo

Was es war kann ich jetzt nicht sagen...
Log:  zu groß für Pastebin, stattdessen mein Googledrive https://drive.google.com/file/d/1_c1XcaLkjFtzCapo7nfUxK-KT38S-17U/view?usp=sharing

**Comment by Tensuko** [comment]
Bei einem Durchfahrssilo (wenn man zum abladen auch durchfährt) braucht man kein Abladepunkt, da wir das Häckselgut auch seber verteilen.
Einzig beim Rückwärts abladen, wird ein Abladepunkt benötigt.

**Comment by Foss-ops** [comment]
Danke für die Klarstellung. :top:

Zum Problem: 1x hat es funktioniert, siehe mein letztes Posting. Gestern und heute wieder nicht, es springt einfach nicht auf den angehängten Kurs, owohl da dick und fett steht "2kombinerte Kurse". Ist auch egal welche Füllmenge zum Abfahren ich einstelle.
Gras/Heu sammeln im Feldarbeitsmodus springt bei mir nicht auf den mit "+" angehängten Abfahrkurs. Ich mach es doch genau so wie vor 3 Tagen. Ich komm einfach nicht drauf.

Ich muss wohl mal eine Testreihe ohne Mods machen auf Felsbrunn oder so.. auf der Marsch komm ich so nicht weiter.

**Comment by Tensuko** [comment]
Danke dir für dein Feedback.
Es kann durchaus ein Modkonflikt sein.

**Comment by SevenFifty1996** [comment]
Ich hatte so ein Problem. Ich hatte das Silo nicht gekauft. Ich habe da den Fehler gesucht....und hatte nicht daran gedacht das mit das Gebiet auch gehören muss...nur so ein Gedanke.

**Comment by Foss-ops** [comment]
> 
> 
> Ich hatte so ein Problem. Ich hatte das Silo nicht gekauft. Ich habe da den Fehler gesucht....und hatte nicht daran gedacht das mit das Gebiet auch gehören muss...nur so ein Gedanke.

Guter Gedanke, hatte ich schonmal als Tip in Youtube gehört, hier ist es aber mein Hof und mein Silo.

**Comment by Tensuko** [comment]
Also in ein Durchfahrtssilo hatte ich zwar noch nicht wieder gekippt, aber diverse Fahrten vom Feld in die BGA (Sojastroh auf der IIT).
Von daher kann es nicht an CP liegen.
