### ISSUE TITLE
Mouse doesn’t work 

### ISSUE THREAD

**Issue by oliverbosslol** [Courseplay/courseplay#7251]
So when I open the hud using del key and try to click the buttons, nothing works. Why’s that?

**Comment by oliverbosslol** [comment]
wait where do i put the logfile? do i send the link to u?

**Comment by Tensuko** [comment]
Read the Wiki page...

**Comment by oliverbosslol** [comment]
where then?

**Comment by Tensuko** [comment]
Do I rly have to quote myself now ? ... Read the 2nd post... you already did that, there is a link... guess where it leads to....

**Comment by tn4799** [comment]
Just drag and drop the logfile onto the answer-field in this issue. Thats the easiest way as far as i know. @oliverbosslol

**Comment by oliverbosslol** [comment]
It works now not sure whta happened

**Comment by Tensuko** [comment]
ok I will close this then
