### ISSUE TITLE
Drescher manuell fahren

### ISSUE THREAD

**Issue by Olaff1234** [Courseplay/courseplay#7252]
Ich wollte mal fragen ob es mittlerweile möglich ist selber zu dreschen(kein CP) und CP nur als Abfahrer (um genau zu sein als Überlader) zu verwenden?
Denn immer wenn ich es auf es auf die bekannte weise versucht habe (Kurs einfahren, Drescher auswählen und los gehts)bleibt der Abfahrer einfach stehen und macht nix.
Oder funktioniert das mittlerweile anders und ich stell mich einfach nur blöd an? ^^

**Comment by Tensuko** [comment]
Nein geht nicht.
