### ISSUE TITLE
Abfahrer funktioniert nicht

### ISSUE THREAD

**Issue by TJ6215** [Courseplay/courseplay#7253]
Moin ich habe folgendes Problem. Ich habe einen Kurs gefahren für die Abfahrer um Gras Silage zu transportieren und um abzuladen. Den Häcksler haben sie auch gefunden jedoch fangen sie nicht zu dem Häcksler hinzufahren. Meine Frage ist jetzt kann ich den Häcksler selber fahren oder muss das unbedingt der Course Play Helfer machen?
LG

**Comment by Tensuko** [comment]
CP muss den Häcksler fahren https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ

**Comment by Tom20214** [comment]
#5272 https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ
