### ISSUE TITLE
lost control character

### ISSUE THREAD

**Issue by carly933** [Courseplay/courseplay#7255]
2021-06-09 17:45 dataS/scripts/vehicles/Vehicle.lua(2920) : attempt to call method 'getCurrentHelper' (a nil value)

Until I turn off the helper, nothing can be done to completely freeze the keyboard

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki !!

**Comment by Martin-L45** [comment]
I think this problem is from autodrive and is mentioned is this post
[https://github.com/Stephan-S/FS19_AutoDrive/issues/1934](url)
