### ISSUE TITLE
Bourgault air cart refilling question

### ISSUE THREAD

**Issue by Twetch** [Courseplay/courseplay#7262]
Hi,is it possible to add option for BOURGAULT AIR CART and similar big planters, to open his conveyor when is empty and switch between tanks ,untill they are full, while he waiting for seed and fertilizer on field when cp is still active?

**Comment by Tensuko** [comment]
duplicate #6072

**Comment by Twetch** [comment]
This is not duplicate at all...i want only to extend auger not autorefill , so i can drive with truck to it and fiill it manualy but whatever..

**Comment by Tensuko** [comment]
The problems stays the same, control over the BOURGAULT AIR CART, it IS the same.

**Comment by Twetch** [comment]
Sorry, i had ask adding that option for all planters with lid and covers not just for Bourgault,because it works same for all of them.
