### ISSUE TITLE
Question about Advanced settings.

### ISSUE THREAD

**Issue by Raints** [Courseplay/courseplay#7263]
If I select **When to raise implements** to Early and **When to lower implements** to Late it's not saving anymore that. Is that turned off now? <version>6.4.0.0</version>

**Comment by Tensuko** [comment]
Master Branch or ModHub ?

**Comment by Tensuko** [comment]
On my quick test with Master Branch state.
It is working just fine.
You got to click ok and not exit with esc!

Else -> logfile: https://github.com/Courseplay/courseplay/wiki
