### ISSUE TITLE
Drescher eiert rum beim erstellen und verlassen der Abladebucht

### ISSUE THREAD

**Issue by Clouseau219** [Courseplay/courseplay#7264]
Hi,
irgendwie eiert der Drescher extrem rum, wenn er die Abladebucht erstellt und wieder verlässt. Oft steht er dann so quer, dass er beim verlassen der Bucht am Abfahrer hängen bleibt.

https://youtu.be/WrntzE08yrw
https://youtu.be/7RZolDLEcF4

Jemand eine Idee an was es liegen könnte?

Schon mal Danke !

Grüße,
Gobo

**Comment by Tensuko** [comment]
Kann ich auf dem Master Branch nicht reproduzieren.
Logfile ?

**Comment by Clouseau219** [comment]
Hier das Log File
[log.zip](https://github.com/Courseplay/courseplay/files/6641372/log.zip)

**Comment by pvaiko** [comment]
Was machst du mit AutoDrive? Ist AD an?

**Comment by Clouseau219** [comment]
AD nutze ich bei Drescher nur um sie vom Hof zum Feld fahren zu lassen. Am Feld ist AD bei den Drescher ausgeschaltet. AD nutze ich beim Abfahrer.

**Comment by Tensuko** [comment]
Bitte hänge das logfile nicht als .zip an.... einfach drag and drop die textdatei hier rein schieben....

Zu deiner log:
das raus: (Version: 1.0.0.0) FS19_MoreMissionsAllowed
weil es hier enthalten ist: (Version: 1.1.0.0) FS19_BetterContracts

Ansonsten schwer zu sagen, was den Drescher so rumeiern lässt.
Ist es das Claas Schneidwerk was du da benutzt ?

**Comment by Clouseau219** [comment]
Es ist das Lizard Cutter Set vom Mod Hub
[https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=151423&title=fs2019](url)
Danke schon mal für eure Bemühungen und den Tip mit MoreMissions

**Comment by pvaiko** [comment]
wie üblich, debug channel 6 und show temporary course einschalten in settings.

**Comment by Clouseau219** [comment]
Wie kann ich denn die Debug Channels auswählen, bei mir sind die seit der V6.4.0 schwarz und nicht aus wählbar.
![2021-06-12 13_19_47-Farming Simulator 19](https://user-images.githubusercontent.com/16350763/121774126-0d57a700-cb81-11eb-9889-ba760dfb3ac0.png)

**Comment by Tensuko** [comment]
Master Branch laden

**Comment by Tensuko** [comment]
Kannst du mal testweise AIVehicleExtension raus nehmen ?

**Comment by Clouseau219** [comment]
Sorry für die wahrscheinlich blöde Frage, bin nicht so firm mit github, was ist der Master Branch. Ich habe die Version genommen: [https://github.com/Courseplay/courseplay/releases/download/6.4.0.0/FS19_Courseplay.zip](url)
Das mit dem AIVE werde ich mal testen.

**Comment by Tensuko** [comment]
Master Branch ist wenn du auf der Seite ( https://github.com/Courseplay/courseplay ) mit dem grünen Button ein .zip runter lädst, dass musst du entpacken und den inhalten des Ordners dann in FS19_Courseplay.zip packen.

**Comment by Clouseau219** [comment]
Scheint wohl am AIVE gelegen zu haben, ich werde es mal weiter beobachten und ihn mal testweise nachher wieder rein nehmen. Mal schauen ob es dann wieder auftritt. Nochmals Danke für eure Hilfe.
