### ISSUE TITLE
Courseplay wont plant potatoes without having fertilizer despite having 'deactivate use fertilizer of seeder' option on/off

### ISSUE THREAD

**Issue by sta777ic** [Courseplay/courseplay#7266]
Using the Grimme GL 860 compactica provided by normal game an no mod attachment. I took a contract job to seed potatoes and it wont let me seed/plant without fertilizer even though the contract is just to plant. So basically I am losing money I wont be reimbursed for. I tried uncheck/checking "Deactive utilizer fertilizer of seeder" but couldnt get it to start unless I turned on "helper refill fertilizer" and then it worked.

**Comment by Tensuko** [comment]
Can't reproduce, logfile ? https://github.com/Courseplay/courseplay/wiki
![fsScreen_2021_06_12_20_07_45](https://user-images.githubusercontent.com/27344744/121785423-04cf9280-cbba-11eb-9a47-c3e75e4d9012.png)

**Comment by sta777ic** [comment]
Hello Tensuko, thank you for the quick reply. Your reply was faster than our engineering department at current job and they get paid! So I see you could not reproduce and I suspect the reason for getting this issue has to do with the mod: 

Precision Farming mod where fields pH and nitrogen levels and soil types are different. 

https://farming-simulator.com/mod.php?mod_id=188882

If that is the case and this mod is hindering courseplay, what logs could I be collecting to paste or is that even in scope for Courseplay? 

Regards,
sta777ic

**Comment by Tensuko** [comment]
You might be right, I think I don't have loaded Precision Farming in this savegame.

Now I remember this. You need a tiny bit of fertilizer in your machine, but then you can still turn it off in the HUD and nothing will be consumed. Can you try this out ? (Maybe automatic fertilizer in Precision Farming Options must be turned off ?)

GIANTS announced an Update for that Mod, if that is still not fixed then, I will get in contact with them to see what we can do.

**Comment by sta777ic** [comment]
So I tested with a little bit of dry fertilizer and yes it now works without actually using any dry fert. Thanks for the idea.

Cheers
