### ISSUE TITLE
potential problem 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#7267]
hey im using the latest version of courseplay i downloaded the dev version on the 10/06/2021 but I've come across a problem when i send a machine to a field via autodrive it arrives at the field and i try to generate a course in this case liming the field using the terragator it wont let me select course generation just spits an error out ive included log..
[courseplay.txt](https://github.com/Courseplay/courseplay/files/6642728/courseplay.txt)

**Comment by Tensuko** [comment]
Your discription is very confusing...
Why you send the Driver with AD to the field, when you not even generated a course ?

You have to load a course in CP and make all the needed settings (mostly start at startpoint), then you can send the driver with AD to the field so CP just need to be turned on (wich AD does).

Else the information that you used AD to send it to the field doesn't make any sense...

**Comment by matty2123** [comment]
forget the autodrive bit i use it to drive to next field im working. just saying when i arrived at the new field to start liming obviously i need to make a course but my problem is cp wouldnt show the course generator till i restarted

**Comment by Tensuko** [comment]
logfile ? (maybe with the Error ?)
Screenshot of the tools ?
What actual tools ?

**Comment by matty2123** [comment]
Log file is in original post and I used the terragator from guy on fb Karl’s modding

**Comment by Tensuko** [comment]
> 
> 
> Log file is in original post and I used the terragator from guy on fb Karl’s modding

yea I forgot about the logfile but the mod is unknown to us and it seemed to be 'special modded' and not on modhub, then it is a mod issue.

**Comment by matty2123** [comment]
Ok will monitor but must add was alright before I updated used this mod plenty of times

**Comment by Tensuko** [comment]
https://www.farming-simulator.com/mod.php?lang=en&country=cz&mod_id=122024 ???

**Comment by matty2123** [comment]
![73196A96-B243-49A9-AA7B-04BB37A282E7](https://user-images.githubusercontent.com/27097241/121787324-57f71480-cbbd-11eb-867c-d6d161d5484d.png) there’s issues with ai workers but as I have said worked ok with previous version of cp

**Comment by Tensuko** [comment]
Just noticed a bug on the hud for selfdriven combines (also with the terragator from modhub) else we have to see if there is still a problem after that fix.
