### ISSUE TITLE
Error in logfile with mouse key [Courseplay 6.4.0.0] modHub

### ISSUE THREAD

**Issue by giantswamp** [Courseplay/courseplay#7268]
Hi,

i ve got some errors in log.txt

> Warning: Tried assigning the binding [(MOUSE_BUTTON_LEFT), deviceId: KB_MOUSE_DEFAULT, axisComponent: +, index: 3, isActive: true, isShadowed: false isInverted: nil, isDown: false, isUp: false, inputValue: 0] to COURSEPLAY_MOUSEACTION_PRIMARY to an occupied slot. The new binding has been ignored
>   Warning: Tried assigning the binding [(MOUSE_BUTTON_RIGHT), deviceId: KB_MOUSE_DEFAULT, axisComponent: +, index: 3, isActive: true, isShadowed: false isInverted: nil, isDown: false, isUp: false, inputValue: 0] to COURSEPLAY_MOUSEACTION_SECONDARY to an occupied slot. The new binding has been ignored

Of course i tested with all mods and only Courseplay.

I put you the log.txt

[
[log.txt](https://github.com/Courseplay/courseplay/files/6643370/log.txt)
](url)

**Comment by Tensuko** [comment]
That is a warning and only happens becouse your keybind is messed up.
Nothing we have to fix or we can fix.
