### ISSUE TITLE
Game stuck

### ISSUE THREAD

**Issue by KrucifikX** [Courseplay/courseplay#7270]
Hello
I love so much cureseplay and and how it makes my job easier :) my problem is that the game gets stuck after switching to a CP controlled worker. In the attachment I send log, the problem is visible but I don't know which mod can be in conflict with CP.
[log1.txt](https://github.com/Courseplay/courseplay/files/6643732/log1.txt)

**Comment by Tensuko** [comment]
You should remove those Mods that produce 'Error:' in your log (the AD config also not belongs into the mods Folder!).

Remove '(Version: 1.0.0.3) FS19_waitingWorkers' and try it again.

**Comment by KrucifikX** [comment]
Thank you for your advice. I removed the mod “FS19_waitingWorkers“ and everything else. Now it seems to be in order.

**Comment by Tensuko** [comment]
Okay. That is a modconflict where we can't do much. Will close this then.
