### ISSUE TITLE
Kreuzungspunkte 

### ISSUE THREAD

**Issue by SevenFifty1996** [Courseplay/courseplay#7271]
Hallo,
ich fahre gerade Kurse ein . Jetzt möchte ich, Kurse über Kreuzungspunkte verbinden. Mein Problem ist, trotz dessen das die Punkte angezeigt werden sollen, keine mehr sichtbar sind wenn ich das Spiel neu lade. Ich habe den Kurs abgespeichert. Dann sind sie noch zu ersehen. Wenn ich dann das Spiel neu lade, sind sie weg. Muss ich da noch was einstellen (Kreuzungspunkte anzeigen), oder liegt hier vielleicht ein Fehler vor.

**Comment by Tensuko** [comment]
Suchfunktion bitte nutzen: #6301
