### ISSUE TITLE
Mod not loading on dedicated server - File count per store too high. 155 found (max 128)

### ISSUE THREAD

**Issue by ronaldvdmeer** [Courseplay/courseplay#7273]
When i'm trying to use this mod on a dedicated server I get the message `file count per store too high. 155 found (max 128)`. It seems that the amount of files in the zipfile is causing this issue. Is there a way around this or can this MOD not be used on a server?

**Comment by ronaldvdmeer** [comment]
I tested it with 2 seperated hosting providers. Both show the same error

**Comment by Tensuko** [comment]
Stick to ModHub Version:
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=209361&title=fs2019
And we play with Courseplay on dedi server, so it is working.
Else you did .zip it wrong or something else on your side is wrong.

**Comment by ronaldvdmeer** [comment]
I've downloaded that version as well. Still it has 155 files in it while the dedicated server says it only wants 128 max.

**Comment by Tensuko** [comment]
We use the same version and don't have any Errors...

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by ronaldvdmeer** [comment]
Apparantly you can activate the mod but it does give an error

![image](https://user-images.githubusercontent.com/19911658/121817096-8dfccd00-cc7f-11eb-9d8e-9f5f069bac42.png)
