### ISSUE TITLE
Multiplayer Probleme

### ISSUE THREAD

**Issue by Dragonfly1982** [Courseplay/courseplay#7275]
Hallo,
wir haben auf unserem Server das Problem das wir bei Kauf eines neuen Traktor bzw Zugmaschine das Hud nicht öffnen können ohne etwas dahinter zu hängen. Sobald wir etwas anhängen funktioniert es und wenn wir es wieder abhängen funktioniert es anschliessend auch wieder. Ich sende euch mal die Server und Spieler Log von mir.
Wir haben auch den AD aktualiesiert gehabt, vielleicht ist dadurch ein Fehler entstanden.

Mit freundlichem Gruss

[Server LOG.txt](https://github.com/Courseplay/courseplay/files/6644260/Server.LOG.txt)
[SpielerLOG.txt](https://github.com/Courseplay/courseplay/files/6644261/SpielerLOG.txt)

**Comment by Tensuko** [comment]
Der fehler ist bekannt und wird mit der nächsten Version gefixt. #7267
Das sollte dann hier auf GitHub die 6.4.0.1 sein.
Alternativ auf die ModHub Version zurückgreifen, da sollte das eigentlich nicht vorkommen.
