### ISSUE TITLE
Mode 9 (Shovel driver) / 10 (Bunker silo compacting/shield driver) changes

### ISSUE THREAD

**Issue by schwiti6190** [Courseplay/courseplay#7276]
Hi there,

With the latest version were a lot of changes to these two modes relativ to the gameplay and the code behind it.
It might be possible that your current course setups are no longer viable compared to the modhub release.
For any question feel free to ask and also a bit of patience, as there are probably still bugs in this version.

Thanks for your help :)

**Comment by Tensuko** [comment]
Thats my 1st english voiced video. Pls bare with me, my voice is a bit silent and unclear sometimes. I hope you get how everything should work anyway. The stuttering is also a bit unexplainable to me. I work on that and hope the next kind of those videos are better.
https://youtu.be/qCBUuo6Z2e8

**Comment by FReaXit** [comment]
Hello, 

the Fliegl Dou Leveler is working in mode 10. 
The Holaras Viking Leveler (also from modhub) doesn't work for me. 
The mode 10 button is grey, instead of this the mode 9 button is white, which isn't the right mode for that tool.

**Comment by Tensuko** [comment]
Will have to test that, I guess it got some weird specialisation....

**Comment by envikowaty** [comment]
So based on the video to create a route bunker silo -> loading truck, what points I must choose ?
For loading from bunker silo I go:

Start point -> parking point

To unload on the truck:
Parking point -> discharged point 

??

**Comment by Tensuko** [comment]
No.... did you even watch the Video ?
Where you unload, doesn't matter, it is ALWAYS, like it have ever been, a single waitpoint.

The only thing that have changed, is the way of how you load from the bunker:
Start, drive in, switch to reverse and the rest is as always.
For both, normale heap loading and trigger mode, with the difference, that trigger mode is only used if load from a trigger, like in the video.

**Comment by envikowaty** [comment]
> No.... did you even watch the Video ?
> Where you unload, doesn't matter, it is ALWAYS, like it have ever been, a single waitpoint.
> 
> The only thing that have changed, is the way of how you load from the bunker:
> Start, drive in, switch to reverse and the rest is as always.
> For both, normale heap loading and trigger mode, with the difference, that trigger mode is only used if load from a trigger, like in the video.

Right ! but what about if the trailer is full and the loader has still some siliage ? will it stop loading while the trailer is on the way to another point ?

**Comment by Tocik** [comment]
The latest versions seem to work with the silo.
I decided to try mode 9 on a quarry, faced the same problem as in earlier versions. Before reaching the truck, the loader starts to drive in a circle. I put the P point in different places (next to the truck as in the photo, I put it further from the truck, but the result is the same).
![1](https://user-images.githubusercontent.com/65189100/124422433-f1a08480-dd6b-11eb-9a31-5488c14f70b3.jpg)
![2](https://user-images.githubusercontent.com/65189100/124422434-f2d1b180-dd6b-11eb-8c67-d70ba482c498.jpg)

**Comment by Tensuko** [comment]
The P is to close to the target and does not point in the right direction.
I explained that in the Video.
Basically it will work if you drive to your target, stop move, place the waitpoint and then switch to reverse, then do the rest as usual, the Waitpoint should look in the right direction. I see if I can get you a close up screenshot.
If you want to edit it, it is enough if you use one waypoint AFTER the waitpoint and move it arround, you will see where the little orange arrow look.

**Comment by Tocik** [comment]
If it's not difficult to take a picture, I would be grateful to understand it more clearly

**Comment by envikowaty** [comment]
> If it's not difficult to take a picture, I would be grateful to understand it more clear

I have the same problem , heh still - im doing everything like is on the video and still getting problem to setup the course:

![Schowek01](https://user-images.githubusercontent.com/69640077/124686068-570a8780-deca-11eb-9e3f-4d0d8447f87e.jpg)

<script src="https://gist.github.com/envikowaty/e85fbe09374b246e818d234334917aea.js"></script>

**Comment by Tocik** [comment]
There is an extra Waiting point in the bunker.
On this version of the courseplay, only one waiting point is placed directly in front of the unloading point.

**Comment by envikowaty** [comment]
> There is an extra Waiting point in the bunker.
> 
> On this version of the courseplay, only one waiting point is placed directly in front of the unloading point.

Thank you ! I still can't find out why loader is not unloading for example to the fermenting silo by global company, I've tried to use P waypoint and unload waypoint and still it only goes to it and the goes back.

**Comment by Tocik** [comment]
There is an extra Waiting point in the bunker.
On this version of the courseplay, only one waiting point is placed directly in front of the unloading point.

**Comment by Tocik** [comment]
> Спасибо ! Я до сих пор не могу понять, почему загрузчик не выгружается, например, в бункер для брожения глобальной компанией, я пытался использовать путевую точку P и разгрузить путевую точку, но все равно он идет только к ней, а затем возвращается.

Try to set a waiting point (P) in front of the bunker a few meters away

**Comment by bionade24** [comment]
Even after >20 attempts I can't get it unload properly at the cowshed. After the parking position marker, the tractor accelerates into the shed.

**Comment by bionade24** [comment]
Additionally, it doesn't wait until the shovel is empty when loading into the manure spreader.

**Comment by Tensuko** [comment]
@bionade24 
can't reproduce your Issue. A Video with channel 9 and 10 on to see whats going up there might help.

**Comment by envikowaty** [comment]
> There is an extra Waiting point in the bunker.
> 
> On this version of the courseplay, only one waiting point is placed directly in front of the unloading point.

All setup but ...
Even though if you set up everything ok for the bunker, the loader will load and start driving... the problem is With unloading:
For example if I want to unload to the global company building I just make a P waiting just before the building = the loader drives there but only stop for a second and drives back.

This problem is basically with any building. Only based on the video made by @Tensuko all works fine with the silo.

**Comment by bionade24** [comment]
> @bionade24
> can't reproduce your Issue. A Video with channel 9 and 10 on to see whats going up there might help.
 
Will do it.
Another observation/bug: If I have a smalle double bunker silo. A game bug there lets the material sometimes visibly, most times invisibly glitch through the beton wall. So if the first silo is empty but the second is still full at the wall next to silo 1, silo one still show a fill level around 2500, even though you can't see anything. With the new mode, courseplay will decide to go into the empty part of the double silo but it doesn't get close enough to the wall to collect the invisible material, thus always having an empty shovel until you remove the glitching material manually.

I know it's a game bug but I'm unsure if Giants will fix this, so maybe a workaround is the better solution ?

**Comment by envikowaty** [comment]
> > @bionade24
> 
> > can't reproduce your Issue. A Video with channel 9 and 10 on to see whats going up there might help.
> 
>  
> 
> Will do it.
> 
> Another observation/bug: If I have a smalle double bunker silo. A game bug there lets the material sometimes visibly, most times invisibly glitch through the beton wall. So if the first silo is empty but the second is still full at the wall next to silo 1, silo one still show a fill level around 2500, even though you can't see anything. With the new mode, courseplay will decide to go into the empty part of the double silo but it doesn't get close enough to the wall to collect the invisible material, thus always having an empty shovel until you remove the glitching material manually.
> 
> 
> 
> I know it's a game bug but I'm unsure if Giants will fix this, so maybe a workaround is the better solution ?

I manage to repair that with changing the shovel to Iconik XL

**Comment by bionade24** [comment]
> This problem is basically with any building. Only based on the video made by @Tensuko all works fine with the silo.

You have to try hard to get it working if the angles are bad, see my hidden comment for that. And don't place the waiting point to near.

**Comment by bionade24** [comment]
@Tensuko Here is a video if the front loader issue.  Until I made it, the problem got worse. In the beginning it were 7 liters, then 1, now 0. Emptying into the feeding trough of the cows works fine.

**Comment by bionade24** [comment]
Also another Bug of the new Bunker silo detection: In the Felsbrunn map, the BGA filling point is on the ground of the double bunker silo, I didn't manage to not confuse the silo detection.

**Comment by Yasp0** [comment]
If you have a 'drive through' bunker you can only unload with the wheel loader from one side? For me it works only on 1 side. Tried on the BGA in the Bucks County map.

**Comment by Tensuko** [comment]
> 
> 
> If you have a 'drive through' bunker you can only unload with the wheel loader from one side? For me it works only on 1 side. Tried on the BGA in the Bucks County map. Is that intentionally?
> 


> On the side which doesnt work the debug mode says startBunkerNode and widthBunkerNode. On the side that works it says heightBunkerNode.

Will see if we could turn that arround when we come from the other side.

> 
> 
> @Tensuko Here is a video if the front loader issue. Until I made it, the problem got worse. In the beginning it were 7 liters, then 1, now 0. (Edit: Now I got 485 or 4%) Emptying into the feeding trough of the cows works fine.
> https://oscloud.info/f/aed5ee0e2db14443a4b6/
> 
> Edit: Same problem with the other tractor carrying the manure spreader in the video.

could be a shovel position error, as I could not see it from the side, maybe you tip to much.


> Also another Bug of the new Bunker silo detection: In the Felsbrunn map, the BGA filling point is on the ground of the double bunker silo, I didn't manage to not confuse the silo detection.

Load silo, oder unload into BGA ? What you talk about now ?
Unload BGA it doesn't matter where the trigger is, the waitppoint must be in front of the trigger, thats all.

**Comment by alepinci** [comment]
![immagine](https://user-images.githubusercontent.com/38883600/131842671-b6c8e1b0-5493-4cc8-830b-83bf0509060d.png)
Hi, the driver of the wheel loader stops too early and doesn't load any more silage when the bunker silo is almost empty. Is there any solution?

**Comment by James31283** [comment]
Quick update, I have reviewed all of the messages and videos on how to use the shovel mode, and no matter what I change or edit with the course, it does not work. I see the hurdle that the bucket never raises to empty to content to a trailer or a silo. I resolved the issue by using the Mod in the mod shop/mod store and making two wait points in the bunker for pickup. Let me know if I can help troubleshoot this issue, as I can't wait to only drive to the front of the bunker every time I make a course.

**Comment by Tensuko** [comment]
The Issue in unloading is the waypoint before the Waitpoint at the target.
It must be close enough to the waitpoint, no Idea why.
I try to make that clear somewhere...

**Comment by envikowaty** [comment]
> Quick update, I have reviewed all of the messages and videos on how to use the shovel mode, and no matter what I change or edit with the course, it does not work. I see the hurdle that the bucket never raises to empty to content to a trailer or a silo. I resolved the issue by using the Mod in the mod shop/mod store and making two wait points in the bunker for pickup. Let me know if I can help troubleshoot this issue, as I can't wait to only drive to the front of the bunker every time I make a course. 

Based on new version of CP I've tried to use mode9 for load silage from the bunker and empty it in TMR mixer G2-456, but if I put waiting point or unload point in the unloading place the u loader just drive through and go back to the first point

**Comment by Tensuko** [comment]
You have to use a waitpoint. The wp before waitpoint got to be close enough. It is a bit complicated and we try to make it more simple for fs22

**Comment by landtools** [comment]
> Devi usare un punto di attesa. Il wp prima di waitpoint doveva essere abbastanza vicino. È un po' complicato e cerchiamo di renderlo più semplice per fs22

Ciao, anche io dopo l'ultimo aggiornamento non riesco piu a far scaricare la pala.... è cambiato qualcosa oppure sbaglio io ??
Hello, I too after the last update I can no longer download the shovel .... has something changed or am I wrong?
![Senza titolo](https://user-images.githubusercontent.com/71590173/144711277-bb6bd51a-f9e9-4b50-8ae1-45870d98a25c.png)

**Comment by landtools** [comment]
Risolto.... alla fine, ho tolto la P dal bunker e ora è ritornato a funzionare il tutto... ho preso spunto dal video 
Solved .... in the end, I removed the P from the bunker and now everything is back to work ... I took a cue from the video
https://oscloud.info/f/aed5ee0e2db14443a4b6/
![image](https://user-images.githubusercontent.com/71590173/144711720-8f51c029-19fb-4f73-b925-ad10fab134c2.png)

**Comment by 1972yra** [comment]
Ich habe es wie auf dem Video gemacht, aber seit der Version 6.4.0.6 funktioniert der Loader nicht gut. 6.4.0.6 funktioniert perfekt.

https://user-images.githubusercontent.com/28957570/146637699-d6df2438-7b59-49fc-a162-4bbcc3351b84.mp4

**Comment by Tensuko** [comment]
Einfach mal das issue durchlesen, hab diverse sachen dazu geschrieben
