### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by Stephan3188** [Courseplay/courseplay#7278]
Bei welcher Version vom CP war es möglich Drescher und Häcksler noch selber zu fahren und CP nur abfahren zu lassen? Hab mir grad mein altes CP geschrottet.UND NEIN ich möchte nicht alles über helfer regeln.

**Comment by Tensuko** [comment]
6.01.xxx könnte es gehen.

> UND NEIN ich möchte nicht alles über helfer regeln.
