### ISSUE TITLE
Überladewagen funktioniert nicht mehr mit der Version 6.4.0.1 und 6.4.0.2

### ISSUE THREAD

**Issue by regs1980** [Courseplay/courseplay#7279]
Der Überladewagen lädt zwar ab aber er bleibt einfach stehen nach dem Überladen, Weiterfahren unterhalb der eingestellten Prozentzahl funktioniert nicht, so wie es aussieht, da man einstellen kann was man will, es kommt keine Reaktion, in der Version 6.4.0.0 funktioniert alles so wie es sein soll, getestet wurde mit Standard Überladewagen.

Ich schätze mal bei der Veränderung am Mod2 in der Version 6.4.0.1, haben sich leichte Fehler eingeschlichen.

Danke für die Behebung des Fehlers, im voraus.

**Comment by franky-bb** [comment]
Leider funktioniert in beiden Versionen das Ausschaufeln des Bunkersilos in der BGA auch nicht mehr. Selbst dann nicht, wenn ein neuer Kurs eingefahren wird.

**Comment by franky-bb** [comment]
Sorry. Hab nicht mitbekommen, dass sich das Einfahren geändert hat. Jetzt geht es.

**Comment by DonBolli** [comment]
Du musst die ablade Position einstellen, ich hatte das "Problem" auch.

**Comment by regs1980** [comment]
Hat mit der Position gar nichts zu tun.
Habe mich jetzt noch mal zwei Tage intensive mit beschäftigt, mehr als 30 Kurse erstellt mit verschiedenen Version und Einstellung.
Genaue Schilderung des Fehlers, in den beiden Versionen nach 6.4.0:

Bei 6.4.0 hat der ÜLW auf mehrere Abfahrer reagiert, bei den Versionen 6.4.0.1 und 6.4.0.2 macht CP es nicht mehr, einfach gesagt 6.4.0.1 und 6.4.0.2 kann nur einen Abfahrer beladen, dann muss er weiter fahren, sobald auf einen zweiten gewartet wird, lädt der ÜLW ab und dann passiert gar nichts mehr. 
Stellt man den ÜLW auf mehr als 50% ein, so das er nur einen Abfahrer befüllt und dann weiter fährt, klappt das auch mit dem überladen.

**Comment by Tensuko** [comment]
Aha okay.
Das heist er klappt die Pipe nicht mehr aus, wenn der eine Mode1 Driver weggefahren ist und ein neuer kommt ?

**Comment by regs1980** [comment]
Doch er lädt den zweiten Abfahrer auch über, nur wenn dieser nicht los fährt, daher nicht Vollbeladen ist, bleibt der CP ÜLW einfach stehen, obwohl er komplett leer ist.

**Comment by DonBolli** [comment]
![5](https://user-images.githubusercontent.com/43571844/122672395-95662e00-d1cb-11eb-8793-fef16fac70cb.png)

Ich kenne dein Problem nicht genau, diese Funktion/Einstellung ist jedoch neu. Zumindest in 6.4.0.2 bei 6.4.0.1 weiss ich es nicht0.

**Comment by Tensuko** [comment]
Die ist nicht neu in der 6.4.0.2 und auch nicht in der 6.4.0.1..........

**Comment by Tensuko** [comment]
> 
> 
> Doch er lädt den zweiten Abfahrer auch über, nur wenn dieser nicht los fährt, da er nicht Vollbeladen ist, bleibt der CP ÜLW einfach stehen, obwohl er komplett leer ist.

Ok danke das könnte helfen. Ich schau mal das ich das nachgebaut kriege.
Könnte aber wirklich der Wert sein dann.

**Comment by DonBolli** [comment]
> Die ist nicht neu in der 6.4.0.2 und auch nicht in der 6.4.0.1..........

Gut zu wissen, war der Grund das er bei mir nicht weiterfuhr

**Comment by regs1980** [comment]
@DonBolli Position "Beladen" damit stellt du die Abladeposition vom Entladerohr ein, man konnte den HaulMaster ÜLW bevor es die Einstellung gab, nicht mit dem Krampe SB II 30/1070 benutzen, da das Rohr beim entladen mit dem Anhänger kollidierte an der Seitenwand, jetzt ist es möglich die Rohrposition zu speichern mit dem Eintrag.

**Comment by DonBolli** [comment]
@regs1980 okay ich sehe, dachte vielleicht hilft dir meine Erfahrung.

**Comment by Tensuko** [comment]
Also ich konnte das nicht reproduzieren auf unserem Testbranch, 2 mal mit einem Abfahrer am ÜLW gewesen und beim 2ten mal kam er unter die 40% und ist dann losgefahren, so wie es sein soll.

**Comment by rohne83** [comment]
@regs1980 was für einen ULW nutzt du denn und mit welchen Einstellungen? Wenn der ULW leer ist, geht dann die Motordrehzahl des Traktors wieder runter und die Entladeschnecke hört auf sich zu bewegen (insofern animiert)?
Es gab nämlich mal den Fall, dass nach dem Abladen einfach öfter nicht erkannt wurde dass der ULW leer ist und die Entladeschnecke weitergelaufen lassen wurde. Hatte ich einige Zeit nach dem Fix ganz sporadisch mal beim Brent Avalanche wieder beobachtet, ohne es aber wirklich reproduzieren zu können.

**Comment by Tensuko** [comment]
@rohne83 
So wie ich es verstanden habe, soll das überladen usw problemlos gehen.
Auch in mehrere Durchgänge (hatte in meinen tests auch geklappt).
Was nicht gehen soll ist, dass wenn er nicht mehr überlädt und unter X% 'Abfahren bei weniger als' ist, dass er dann auch los fährt.
Allerdings konnte ich den immer unter z.B. 40% bringen bei eingestellten 40% und er ist abgefahren.
Verschiedene ÜLW habe ich nicht probiert.
So ein 2 Kammer ÜLW z.B. ist für sowas überhaupt nicht geeignet (und ergibt auch keinen Sinn).
Wie das mit diversen großen ÜLW ist (habe nur den Stara benutzt) habe ich noch nicht ausprobiert...
Wäre schon komische, wenn es Zusammenhänge gibt, zwischen dem abfahren des ÜLW und den 10km/h bug...
Eventuell weil das Rohr nicht wirklich eingeklappt ist und er weiterhin 'entlädt' ?

**Comment by regs1980** [comment]
Habe mal einen neuen Spielstand erstellt und zwei ÜLW aus Modhub noch probiert die realitätsnah sind, mit denen läuft das überladen so wie es in der 6.4.0 Version auch war, also liegt es nicht an CP nur an manche ÜLW Mods, auch der Standard HaulMaster mit 70000L funktioniert mit dem neuen Spielstand jetzt auch. 
Danke für die Mühe, macht weiter so, Super Mod.
