### ISSUE TITLE
shovel trigger mode

### ISSUE THREAD

**Issue by leo32128fs** [Courseplay/courseplay#7280]
Good morning , I would like to know how I make a route to this mode , [ shovel trigger mode ]

![Captura de Tela (19)](https://user-images.githubusercontent.com/69097102/122070944-be05b680-cdcc-11eb-9ce5-6f4344df51e7.png)

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/issues/7276
Watch the Video...
