### ISSUE TITLE
Does not Dump

### ISSUE THREAD

**Issue by Gibbanator** [Courseplay/courseplay#7284]
Been running this Bunker course for a long time now and it worked great but today it stopped after the update for CP. Now it does not raise the bucket or dump at the BGA.

Here is a video:
https://youtu.be/PzLRgZtxzC4
[log.txt](https://github.com/Courseplay/courseplay/files/6659420/log.txt)

If I use AD to unload the bunker it works and finds the trigger on the BGA but AD is so slow lol.

**Comment by Tensuko** [comment]
Read #7276

**Comment by Gibbanator** [comment]
Why change it? Now everyone has to change there course with no warning with update. CP needs to not just say what fixes they do with new release but also you have to redo your courses. It was working just fine new way does the same thing practically.

**Comment by schwiti6190** [comment]
@Gibbanator Hi there, 

1) The idee was to make cp easier to use, especially for first time users and so on, a lot easier new course setup.
2) Second with this update came a great change in the code basis, to improve maintance and flexibility for different possibilities.

You can still use the modhub version as this is relative stable :)
