### ISSUE TITLE
Sugarcane harvesting with Austoft 8800 with tractor and trailer does not seem to work

### ISSUE THREAD

**Issue by ronaldvdmeer** [Courseplay/courseplay#7290]
I'm trying to use the austoft 8800 with a tractor and trailer with the combi mode selected. However, instead of driving next to the austoft the tractor will place itself behind the austoft. By now i've tried almost all settings but cant seem to figure out how this works. Is this a bug or am I doing something wrong?

Installed the latest courseplay 6.4.0.2 as well as tried the modhub version 6.4.0. Both seem to have the same problem. 

![image](https://user-images.githubusercontent.com/19911658/122458521-311b5280-cfb0-11eb-8860-787dc75c0c5c.png)

**Comment by Tensuko** [comment]
#6960
