### ISSUE TITLE
Suggestion: Right Click Hud as vehicle setting 

### ISSUE THREAD

**Issue by enderwiggin07** [Courseplay/courseplay#7292]
I like right click HUD, except on vehicles where I use right click a lot.  
For a big tractor for plowing or a truck for grain hauling I like right click hud.
For the telehandler or log crane I don't like right click hud.  

It would be cool if this setting was for each vehicle rather than for all vehicles.  

Thanks for your time. _

**Comment by Tensuko** [comment]
That is already implemented since ages...
Page one = vehicle, page two = global.
Check it up...
