### ISSUE TITLE
Mode 9 = silo bunker (grassilage) -> loading truck

### ISSUE THREAD

**Issue by envikowaty** [Courseplay/courseplay#7298]
Ok at the moment everything is working fine but i'm interested how to record the course silo bunker (grassilage) -> loading truck.

some screens:

![image](https://user-images.githubusercontent.com/69640077/122765249-9c12a500-d2a0-11eb-8724-2ada42f41ec0.png)

![image](https://user-images.githubusercontent.com/69640077/122765379-bc426400-d2a0-11eb-923b-d84adc30f777.png)
 
if i change the mode 9 to loading option:

![image](https://user-images.githubusercontent.com/69640077/122765794-2529dc00-d2a1-11eb-82fd-8f5e7ed1fdd2.png)

Still it shows me that the course is wrong. Probably i'm recording the course wrong

log file: 
[log.txt](https://github.com/Courseplay/courseplay/files/6686800/log.txt)

**Comment by Tensuko** [comment]
That mode is only when you lead from a silo with a pipe or anything with a loadtrigger.
Course works the same but must have a trigger after the start point.

-> https://github.com/Courseplay/courseplay/issues/7276
