### ISSUE TITLE
Kalkstreuer fährt nach dem auffüllen mit Überlader langsam

### ISSUE THREAD

**Issue by lionking2890** [Courseplay/courseplay#7299]
Mit der aktuellen Version 6.4.0.2 scheint das Problem mit den zu langsamen Kalkstreuer wieder aufzutreten.
Das Problem trat unter dem Ticket schon mal auf. #6925 
Ich habe 2 Kurse und lasse den Kalkstreuer automatisch an einem Überladewagen auffüllen. Anschließend fährt der Kalkstreuer nur noch mit maximal 10 km/h weiter. Obwohl die Geschwindigkeit auf dem Feld 30km/h eingestellt ist.
Auf dem Weg zum Überladewagen fährt er mit den 30km/h.
![fsScreen_2021_06_21_20_28_59](https://user-images.githubusercontent.com/77986412/122811555-ef045080-d2d0-11eb-91d2-21f25646937d.png)
Nach dem aufladen (hatte beim nachstellen nicht aufgeladen, weil das Rohr falsch stand) Gestern hatte ich jedoch das gleiche Problem auch, wenn er korrekt nachfüllte. Dann machte er auf dem Feld beim Streuen aber auch nur mit 10 km/h  #weiter
![fsScreen_2021_06_21_20_30_35](https://user-images.githubusercontent.com/77986412/122811562-f166aa80-d2d0-11eb-9db2-a0ae0d70556f.png)
[log.txt](https://github.com/Courseplay/courseplay/files/6688808/log.txt)

**Comment by Tensuko** [comment]
schau mal bitte hier #7282

**Comment by lionking2890** [comment]
Sorry, die Diskussion hatte ich übersehen. Bei mir war es auch der Bergmann aus dem Modhub. Mit anderen hatte ich es noch nicht versucht.

**Comment by lionking2890** [comment]
Wobei mir gerade noch auffällt, dass das Problem auch auftritt, wenn man während dem Kalken ihn befüllt. Es scheint also nichts mit dem Ladekurs zu tun zu haben.
