### ISSUE TITLE
question new mode 9

### ISSUE THREAD

**Issue by evybart** [Courseplay/courseplay#7300]
Is it possible load from the silobunker with silage to a trailer because i do the same from the video bud the loader dont unload in to the trailer 
![github cp](https://user-images.githubusercontent.com/10274098/122823743-05fe6f00-d2e0-11eb-9a1b-d1e35900a7b2.PNG)

**Comment by Tensuko** [comment]
becosue you did it wrong...
where is the wait point at the target ?

#7276 watch the video...
