### ISSUE TITLE
Strohsammler und Abfahrer bleiben bei der Arbeit stehen

### ISSUE THREAD

**Issue by chroboss** [Courseplay/courseplay#7301]
Hallo, ich habe immer wieder das gleiche Problem, insbesondere auf grossen Maps mit vielen AD und CP-Helfern.
Die Gras/- Strohsammler bleiben in ihrer Bahn stehen, nichts geht weiter, ausser ich beende den CP-Auftrag und starte diesen erneut.  Gleichzeitig fahren die Abfahrt nicht vom Abfahrpunkt zum Drescher ab. Hin und wieder findet sich ein CP Fahrer an einem anderen Ende der Karte wieder, weit weg vom eigentlichen Einsatzort. Ein Blick ind die Log zeigte mir reihenweise diesen Fehler:  _dataS/scripts/vehicles/Vehicle.lua(2920) : attempt to index a nil value._
Habe geggoogelt, aber nichts greifbares gefunden, das mir wenigstens einen Ansatz bietet.
Zur Fehlersuche habe ich alle Mods entfernt, 3er weise wieder zurück in den Ordner, 15 min gespielt, dann die nächsten 3 Mods. Ich konnte den Fehler nicht reproduzieren. Nächter Ansatz:  habe ich das gleiche erneut gemacht, alle Fahrzeug-Mods weggelassen und mit Vanilla gespielt.  Nächter Ansatz: Nur die Fahrzeuge belassen und alle anderen Mods rausgenommen
Nach einer Weile war der Fehler in allen Fällen wieder da. Ich weiss nun nicht mehr weiter ??
Log an bei, wenn mehr benötigt wird, liefere ich das gerne hinterher. Danke.
Ich würde mich freuen, wenn ich der Lösung ein wenig näher kommen kann. 
[log-rr.txt](https://github.com/Courseplay/courseplay/files/6694566/log-rr.txt)

**Comment by Tensuko** [comment]
Mit den Infos können wir so nichts anfangen...
Wer (AD/CP) fährt wann und in welchem Modus wo und soll was machen....

Gras oder Stroh sammeln -> fährst du da komplett mit CP oder willst du AD nutzen zum wegfahren ?

> Gleichzeitig fahren die Abfahrt nicht vom Abfahrpunkt zum Drescher ab.

Was ? Wer fährt die Abfahrerer (CP oder AD) ?

> Hin und wieder findet sich ein CP Fahrer an einem anderen Ende der Karte wieder, weit weg vom eigentlichen Einsatzort.

Was für ein Abfahrer, welcher Modus, usw usw....

> Ein Blick ind die Log zeigte mir reihenweise diesen Fehler: dataS/scripts/vehicles/Vehicle.lua(2920) : attempt to index a nil value.

Das kann von sosnt was kommen, auch einer deiner Mods und da hilft auch nur mehr Infos...

Deine Fehlersuche war schon mal der richtige Ansatz, allerdings, wie oben geschrieben, fehlen entscheidende Infos.

**Comment by chroboss** [comment]
Hallo Tensuko. 
Danke für Deine Antwort. Sorry, wusste halt nicht, was Du genau benötigst, mache ich auch nicht jeden Tag :)
Ich habe mich nochmals an die Fehlersuche gemacht, einen neuen Spielstand begonnen, nur mit AutoDrive, Courseplay und dem GlobalCompany Grundmod, und siehe da, der Fehler hat sich nach ca 30 min gezeigt.  
Spielsituation: 4 Drescher im Verbund mit CP (Modus dreschen), 6 Abfahrer mit AD unterwegs (Modus Drescher abtanken), 1 Fahrzeug von mir per Hand gesteuert. Alles Vanilla Fahrzeuge.
Zeitpunkt des Fehlers :  AD Abfaher ist dem CP Drescher in die Bahn gefahren und hat diesen blockiert, es kam zum Stillstand beider Fahrzeuge (Fahrer). Das hat nach einigen Sekunden die Fehlermeldung ausgelöst. 
Es ist also keine Mod, wie ich bisher stets vermutet habe, sondern AD oder CP, oder ein nicht funktionierendes Zusammenspiel beider.  (obwohl beide auch eine Mod sind, oder liege ich da falsch?)  GC,  so möchte ich meinen,  kann man hier als Ursache ausschliessen.
Nun bin ich mit jedoch nicht sicher, wer nun genau der "Übeltäter" und Auslöser dur Fehlermeldung ist.
Macht es Sinn, das Problem ebenfalls an das AD Team zu melden? 
Ich hoffe, das hilft euch weiter und führt zur Ursache des Problems.
Anbei nochmals die letzte Log.  Schreibt CP eigentlich eine eigene Log ?
Danke. Gruß Charlie
[log.txt](https://github.com/Courseplay/courseplay/files/6696582/log.txt)

**Comment by Tensuko** [comment]
> Spielsituation: 4 Drescher im Verbund mit CP (Modus dreschen), 6 Abfahrer mit AD unterwegs (Modus Drescher abtanken), 1 Fahrzeug von mir per Hand gesteuert. Alles Vanilla Fahrzeuge.
> Zeitpunkt des Fehlers : AD Abfaher ist dem CP Drescher in die Bahn gefahren und hat diesen blockiert, es kam zum Stillstand beider Fahrzeuge (Fahrer). Das hat nach einigen Sekunden die Fehlermeldung ausgelöst.

AD Problem -> dort melden.



> Schreibt CP eigentlich eine eigene Log ?

Nein und der Fehler ist GIANTS Code, ich würde da mal bei AD schauen nach dem Error.
