### ISSUE TITLE
Abfahrer Füllstand Problem

### ISSUE THREAD

**Issue by Thermodynamicus** [Courseplay/courseplay#7302]
Hallo,
ich habe das Problem, dass mein Abfahrer erst meinen Drescher abtankt, wenn er komplett voll ist. Egal auf wie viel Prozent er abtanken sollte tut er das nicht. Ich habe zwar paar Mods installiert benutze derzeit aber nur CP. Die mods sind nur 1 Map auf der ich spiele sonst Fahrzeuge. Am Anfang hat es noch funktioniert. Es ist auch nichts dringendes um ehrlich zu sein wollte nur bescheid geben. Mir müsste jemand sagen wo ich die Log datei finde.

MfG Thermodynamicus

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

Und vorallem mal Mode2 Wiki Seite lesen und genauer sagen, wo der Drescher ist... wenn Rohr in der Frucht, dann tanken wir auch nicht ab, bis er aus der Frucht raus ist.

**Comment by Thermodynamicus** [comment]
Es passiert Hauptsächlich wenn er sehr weit weg ist sprich am anderen Ende des Feldes. Fruchtumfahrung ist bei beiden aus. 
[log.txt](https://github.com/Courseplay/courseplay/files/6702075/log.txt)
Jedoch ist es dann aber auch egal wo das Rohr sich befindet. Inzwischen funktionierts wieder bzw nur teilweise. Der Abfahrer ist sehr Launisch. Ich hatte zugegebener Maßen auch zwischendurch wieder das Problem, dass das Spiel nach dem Abfahrer einschalten aber egal welchen Punkt sei es Unloading oder erster Punkt, praktisch zu einem Stillstand gekommen ist. Der Abfahrer hat sich nicht bewegt und das Spiel lief dann auf 5 fps anstatt von den 60.

**Comment by Thermodynamicus** [comment]
Ich habe jetzt noch einmal drauf geachtet. Es scheint so zu sein, dass er nachdem er das erste mal den vollen Anhänger weggebracht hat wieder die Grenze einhält, sprich wenn er schon einmal 100% hatte und wieder vom ausgangspunkt aus fährt (nicht bezogen auf den Ausgangspunkt) nimmt er die Vorgegebene Grenze wieder wahr.

**Comment by Tensuko** [comment]
> und das Spiel lief dann auf 5 fps anstatt von den 60

Das heist aber ganz klar, dass er einen Weg zum Drescher sucht, somit funktioniert alles, nur eben die gewohnten Performance Probleme und dazu gibt es bereits genug Issues.

**Comment by Tensuko** [comment]
Es kann natürlich sein, dass er keinen weg findet, aber das ist dann wieder ein anderes Problem als 'ruft keinen Abfahrer'.

**Comment by Thermodynamicus** [comment]
Also was ich beobachte ist, dass es wirklich zufällig ist und nicht kontrolliert mit dem abfahren. Es lief vorhin nur einfach gut für eine Zeit. Was ich jedoch komisch finde ist, dass der Abfahrer ganz unten sagt "kein Drescher in Reichweite", jedoch nur für sehr kurze Zeit so, dass man es fast nicht lesen kann.

**Comment by Tensuko** [comment]
Das hat nichts zu sagen.
Logfile mit debugchannel 2 und 11.

**Comment by Thermodynamicus** [comment]
Du müsstest mir leider erklären wie ich in diese reinkomme bzw wo diese sind. ^^

**Comment by Tensuko** [comment]
6.4.0.2 von der Release Seite laden und das hier mal lesen:
https://github.com/Courseplay/courseplay/wiki

**Comment by Thermodynamicus** [comment]
ich habe jetzt den code bzw CP von hier heruntergeladen und komm immernoch nicht weiter.
![CP](https://user-images.githubusercontent.com/73956577/123283327-97055e00-d50b-11eb-89a0-8deaba514ce8.png)

**Comment by Thermodynamicus** [comment]
das sollten meiner Meinung nach die Debug channels sein und ich habe nicht der Seite wo Infos über CP stehen keine Informationen darüber entnommen wie ich in die Debugchannels komme. Vorher stand zudem auch V.6.4.0. Ich habe CP jetzt runtergeworfen (natürlich nur den mod und nicht die Routen) und den nocheinmal da eingefügt und CP wird mir nicht mehr angezeigt als Mod. Ich weiss ehrlich gesagt nicht mehr was ich tun soll. Ich wollte auch nur dadrüber bescheid geben das es das problem ist und nicht alles machen und tun müssen bzw mir alles selber aneignen müssen. Ich brauche einfach eine Anleitung für dumme um dir das zu geben was du brauchst.

**Comment by Thermodynamicus** [comment]
das sollten meiner Meinung nach die Debug channels sein und ich habe nicht der Seite wo Infos über CP stehen keine Informationen darüber entnommen wie ich in die Debugchannels komme. Vorher stand zudem auch V.6.4.0. Ich habe CP jetzt runtergeworfen (natürlich nur den mod und nicht die Routen) und den nocheinmal da eingefügt und CP wird mir nicht mehr angezeigt als Mod. Ich weiss ehrlich gesagt nicht mehr was ich tun soll. LS19 sagt der Mod existiert nicht wenn ich in die Mod auswahl komme.

**Comment by Thermodynamicus** [comment]
das sollten meiner Meinung nach die Debug channels sein und ich habe nicht der Seite wo Infos über CP stehen keine Informationen darüber entnommen wie ich in die Debugchannels komme. Ich habe CP jetzt runtergeworfen (natürlich nur den mod und nicht die Routen) und den nocheinmal da eingefügt und CP wird mir nicht mehr angezeigt als Mod. Ich weiss ehrlich gesagt nicht mehr was ich tun soll. LS19 sagt der Mod existiert nicht wenn ich in die Mod auswahl komme. Ich brauche eine Anleitung für dumme mehr nicht. Auf der Seite zu den Debug channels steht das man die in der HUD aktivieren muss. Stellt sich mir die frage was und wo ist die HUD?

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/releases

**Comment by Thermodynamicus** [comment]
[Uploading log.txt…]()

**Comment by Thermodynamicus** [comment]
seitdem ich die version hab ist das spiel "eingefroren" im sinne von ich setze einen fahrer ein und das spiel reagiert nicht mehr aber läuft weiter. Damit meine ich, dass ich nicht Esc drücken, kann aussteigen kann oder aussteigen kann etc. Das sollte auch in der Logfile sein

**Comment by Tensuko** [comment]
Du hast zu schnell gepostet, die log ist nicht hochgeladen...

**Comment by Thermodynamicus** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6721443/log.txt)

**Comment by Tensuko** [comment]
> Logfile mit debugchannel 2 und 11.

Wenn du das jetzt noch gemacht hättest, hätte man auch mehr sagen können...
Und das auch öffter und mit Bilder, am besten wenn er mitten auf dem Feld ist.
