### ISSUE TITLE
[Feature Request] Kursgeneriergungserweiterung

### ISSUE THREAD

**Issue by DonBolli** [Courseplay/courseplay#7303]
Hallo
Es wäre cool wenn man den Kurs des Mähers nehmen könnte und dann parallel zwei Sammler haben. Selber Kurs aber mehrere Fahrzeuge.

**Comment by Tensuko** [comment]
Kurs vom Mäher laden, Fahrzeugverband, Geräteversatz, fertig....

Oder einfach hinter dem Mäher mit Schwadfunktion nen Sammelwagen hinterher schicken.
Gar kein Problem...

**Comment by DonBolli** [comment]
Okay dann bin ich wohl dumm. Hab's nicht hingekriegt 2 Sammelwagen auf den Kurs zu bringen
 Probieren es zuhause.
