### ISSUE TITLE
6.4.0.2 any unknown Error...

### ISSUE THREAD

**Issue by MadDuck52** [Courseplay/courseplay#7304]
Just d/l and installed 6.4.0.2 into PV County. install stopped with the following;
dataS/scripts/vehicles/specializations/sprayer.lua (497): bad argument #1 to ipairs (table expected, got nil).
when i reverted to 6.0.0.0 map loaded just fine. No other changes were made to mods folder. Thank you

**Comment by Tensuko** [comment]
6.0.0.0 does not exist.
need always a logfile and details on what you did.
That Error ist GIANTS Scripts, that does not help us at all.

**Comment by MadDuck52** [comment]
Last working version is 6.4.0.0.    6.4.0.3 and no 6.4.0.4, both are sending this error
[log.txt](https://github.com/Courseplay/courseplay/files/6757895/log.txt)

**Comment by Tensuko** [comment]
6.4.0.6 soon, some changes where made there. Try it out when its out.

This issue doesn't tell us much so closeing it.
