### ISSUE TITLE
CombineUnloadAIDriver total crash when following chopper

### ISSUE THREAD

**Issue by MddMBorg** [Courseplay/courseplay#7307]
Hi devs,

Just got the latest version to see if it fixed an issue with levelling bunkers piling up at the end.

I noticed when my combine unloader is set to follow a chopper, I get an exception that causes the helper to crash/die on lines 527 and 535 of CombineUnloadAIDriver. This is a call to renderText in the driveBesiderChopper and driveBehindChopper methods. If I replace the text parameters with a static string "test", it runs fine, but I can't figure out exactly what parameter is causing the issue. I think it is the `tostring(self.setting.combineOffsetX:get())` parameter, but I'm not familiar enough with lua to tell why exactly.

![image](https://user-images.githubusercontent.com/49454254/123271394-afb84880-d4f8-11eb-8edf-cf2d297e92b2.png)

**Comment by Tensuko** [comment]
always post the full logfile...
https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
@schwiti6190 
Mode2 when unloader approaches chopper, path untill the there is working fine, see log with debugchannels.
[Mode2Chopping.txt](https://github.com/Courseplay/courseplay/files/6709672/Mode2Chopping.txt)

**Comment by ct177mak** [comment]
Have same as @MddMBorg Krone Big X with John Deere und Trailer AnnaBurger ,my Logfile reportet same LUA Error.
[log.txt](https://github.com/Courseplay/courseplay/files/6715249/log.txt)

**Comment by Tensuko** [comment]
fixed on master, will be in next version, thanks for finding and reporting.
