### ISSUE TITLE
Problems with refuelling

### ISSUE THREAD

**Issue by Mannie313** [Courseplay/courseplay#7308]
CP Version: 6.4.0.3
AD Version: 1.1.1.2

Hallo Liebes CP Team. Mit der neuesten version wen ich CP auf dem feld verwende und AD sagt fahre tanken kann er nicht tanken.

Fahre ich nur mit AD fährt er tanken. Kann es ein problem bei CP sein oder Liegt es an AD.

Wen es nicht an CP liegt frage ich bei AD nach.

MFG Mannie313

**Comment by Tensuko** [comment]
Ich weis nicht was genau du willst.
CP fährt mit welchem Modus auf dem Feld ?
AD soll tanken fahren ? Ist das denn in CP eingestellt ?
Ging das in einer vorherigen version ?
logfile ?

**Comment by Mannie313** [comment]
Cp fährt mit dem modus 4 und 6 auf dem feld.
bei CP ist eingestell soll auffüllen.
ja es ging vorher.
wen ich AD ohne cp nen leeren tank fast hab geht er tanken. 
[log.txt](https://github.com/Courseplay/courseplay/files/6714370/log.txt)

MFG Mannie313

**Comment by Tensuko** [comment]
Wenn CP fährt, kann AD nicht sagen fahre tanken.
Wenn dann sagt CP fahre tanken und übergibt dafür an AD.
Betrifft also Mode4 und Mode6.
Wenn AD fährt hat es ja auch nichts mit CP zu tun, ob er dann tankt oder nicht ist Banane.
CP kann auch von alleine tanken.
Es geht hier also rein um die übergabe von CP zu AD wenn CP meldet, dass er tanken sollte.

**Comment by Mannie313** [comment]
ja genau so ist es. Ich hab jetzt auch nochmal die version von modhub getestet das gleiche problem. aber das kuriose an dem ganzen ist schicke ich AD von alleine zum tanken tankt er auf. Gibt CP an AD weiter geh tanken passiert nix.

MFG Mannie313

**Comment by Tensuko** [comment]
Das heist AD fährt -> kann tanken
CP übergibt an AD und dann fährt AD -> kann nicht tanken ?
Hat dann aber wenig mit CP zu tun...

**Comment by Tensuko** [comment]
Lade bitte mal den Branch runter (wie früher, entpacken, Ordner Inhalt neu packen usw) und probiere es noch mal:
https://github.com/Courseplay/courseplay/tree/issue-7308

**Comment by Mannie313** [comment]
CP übergibt an AD und dann fährt AD -> Tankt nur 3 euro tankt er und dann ist es vorbei. stelle ich CP und AD ab und fahr neu in den trigger kann ich selber tanken.

**Comment by schwiti6190** [comment]
@Mannie313 
Auch mit der branch ?
Kannst du vlt. mal bei CP die debug channel 12 u. 16 vorher anschalten und dann die log posten?

**Comment by Mannie313** [comment]
ja kann ich machen ich teste grad auch noch was mit der branch

**Comment by Mannie313** [comment]
![fsScreen_2021_06_25_13_35_59](https://user-images.githubusercontent.com/3021040/123419293-5a447000-d5ba-11eb-9a58-114c04dfc9f2.png)
[log.txt](https://github.com/Courseplay/courseplay/files/6715860/log.txt)
zum einen ein screenshort wegen dem trigger und die Log mit debug 12+16

**Comment by schwiti6190** [comment]
Hm komisch ich weiß nicht ob AD irgendwelche nützliche Debugs hat, aus der log kann ich nichts problematisches von CP erkennen.

**Comment by Mannie313** [comment]
wen ich nur mit AD fahre von a nach b und er muß tanken geht es.
Wen ich jetzt zum beispiel auf dem feld bin am düngen und er muß tanken geht es nicht. Auch wen ich nur grubbere tankt er nicht.

Schalte ich jetzt CP und AD aus fahre aus den trigger und dann wieder hinein kann ich tanken.

während CP und AD aktiv sind kann ich an der Tankstelle kein "R" zum nachfüllen drücken.

**Comment by Mannie313** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6716305/log.txt)
hier nochmal ne log.

**Comment by jala15** [comment]
I have done a bit of trial and error investigation and found out that:
- When you are inside a fuel trigger, start CP, CP starts refuelling (because of `fuel < 20%` or `always` refill setting), and stop CP (not full tank), you can't press "R" to refill again [Video here.](https://youtu.be/jsVV4-1EyTo) 
- CP refuels properly if alone, AD refuels properly if alone, AD starts but stops (and can't start again, like upper point) if CP is also on.
- Changing code to get `searchForFuel = false` in next line "fixes" this issue and AD refuels properly even with CP on, but of course it is not a real solution because it breaks CP refuelling function. https://github.com/Courseplay/courseplay/blob/240e8d85f3bb3742b6992c8886fd249dd370adf6/TriggerHandler.lua#L423

Possible solutions you could implement (or not, you are free 😉 I'm only trying to help): 
- CP should not be expecting to find and refill in a trigger if is not CP but AD who is driving.
- If the bug I showed in the video were fixed, this issue would get fixed too.

**Comment by Mannie313** [comment]
danke @jala15 der tipp hat geholfen.

MFG Mannie313

**Comment by schwiti6190** [comment]
@Mannie313 Thanks alot, that really helped :) . This recent fix might help to have both working.

**Comment by Mannie313** [comment]
in der TriggerHandler.lua
Zeile 423 das eretzen
local searchForFuel = self.alwaysSearchFuel:is(true) and currentFuelPercentage <99 or currentFuelPercentage < 20

mit
--local searchForFuel = self.alwaysSearchFuel:is(true) and currentFuelPercentage <99 or currentFuelPercentage < 20
local searchForFuel = false

so geht das dann alles wieder.

MFG Mannie313

**Comment by Tensuko** [comment]
> 
> 
> in der TriggerHandler.lua
> Zeile 423 das eretzen
> local searchForFuel = self.alwaysSearchFuel:is(true) and currentFuelPercentage <99 or currentFuelPercentage < 20
> 
> mit
> --local searchForFuel = self.alwaysSearchFuel:is(true) and currentFuelPercentage <99 or currentFuelPercentage < 20
> local searchForFuel = false
> 
> so geht das dann alles wieder.
> 
> MFG Mannie313

Das ist aber pfusch und macht das fuel refill von CP kaputt.

**Comment by schwiti6190** [comment]
@Mannie313 On this branch was another push: https://github.com/Courseplay/courseplay/tree/issue-7308 which you could check out. Hopefully it fixes this bug without breaking cp stuff :)

**Comment by Mannie313** [comment]
@schwiti6190 es funktioniert wieder danke.

MFG Mannie313

**Comment by Mannie313** [comment]
@schwiti6190 
ich bekomme jetzt folgenden fehler wen ich nen grubber dranhänge:

LUA call stack:
=F:/Spiele/Landwirtschaftssimulator 19/mods_MP/FS19_Courseplay/base.lua (525) : printCallstack
=F:/Spiele/Landwirtschaftssimulator 19/mods_MP/FS19_Courseplay/TriggerHandler.lua (460) : __index
=F:/Spiele/Landwirtschaftssimulator 19/mods_MP/FS19_Courseplay/FieldworkAIDriver.lua (501) : disableFillTypeLoading
=F:/Spiele/Landwirtschaftssimulator 19/mods_MP/FS19_Courseplay/FieldworkAIDriver.lua (487) : stopAndRefuel
=F:/Spiele/Landwirtschaftssimulator 19/mods_MP/FS19_Courseplay/AIDriver.lua (498) : isFuelLevelOk
=F:/Spiele/Landwirtschaftssimulator 19/mods_MP/FS19_Courseplay/AIDriver.lua (488) : driveCourse
=F:/Spiele/Landwirtschaftssimulator 19/mods_MP/FS19_Courseplay/FieldworkAIDriver.lua (376) : drive
=F:/Spiele/Landwirtschaftssimulator 19/mods_MP/FS19_Courseplay/AIDriver.lua (434) : drive
=[C] (4294967295)
=F:/Spiele/Landwirtschaftssimulator 19/mods_MP/FS19_Courseplay/base.lua (525) : xpcall
dataS/scripts/vehicles/SpecializationUtil.lua (30)
dataS/scripts/vehicles/Vehicle.lua (1306) : raiseEvent
dataS/scripts/network/NetworkNode.lua (98) : update
dataS/scripts/network/Server.lua (58) : updateActiveObjects
dataS/scripts/BaseMission.lua (1500) : update
dataS/scripts/FSBaseMission.lua (1979) : update
dataS/scripts/missions/mission00.lua (469) : update
dataS/scripts/main.lua (1944) : update
:03 [info lp477798] 313 Vario (#4): Exception, stopping Courseplay driver, F:/Spiele/Landwirtschaftssimulator 19/mods_MP/FS19_Courseplay/TriggerHandler.lua:460: attempt to index field 'siloSelectedFillTypeSetting' (a nil value)

und der wiederholt ssich jedesmal wen ich den CP Fahrer einstellen will.

MFG Mannie313
