### ISSUE TITLE
Possible cruise control issue in latest version 6.4.0.3

### ISSUE THREAD

**Issue by MddMBorg** [Courseplay/courseplay#7309]
On the latest version, I've noticed some issues with cruise control.

First, I noticed that as the worker is running a course, the CC speed is changing to match the implement speed/turn speed etc. I can't change the CC speed during the course. I can set the CC speed before starting the course, but during the course the speed is not limited to the speed I set the vehicle to.

Additionally, if I stop the helper during the course, the CC is set back to what it was before. However, if I save the game mid course and then exit the game, when I load back, my vehicle will have the same cruise control speed that it was set to by courseplay. For instance, if the implement has max speed = 15, the vehicle will load in with this speed as the cruise control.

I have a log but I don't think there's much useful information in it (no mention of cruise control speed or anything of the sort).

**Comment by Tensuko** [comment]
> First, I noticed that as the worker is running a course, the CC speed is changing to match the implement speed/turn speed etc. I can't change the CC speed during the course. I can set the CC speed before starting the course, but during the course the speed is not limited to the speed I set the vehicle to.

That part is working correct.



> Additionally, if I stop the helper during the course, the CC is set back to what it was before. However, if I save the game mid course and then exit the game, when I load back, my vehicle will have the same cruise control speed that it was set to by courseplay. For instance, if the implement has max speed = 15, the vehicle will load in with this speed as the cruise control.

That I will check when I have some time... Not that important as it is not rly gamebreaking.



> I have a log but I don't think there's much useful information in it (no mention of cruise control speed or anything of the sort).

Always post a logfile, there is more in it then you think!

**Comment by MddMBorg** [comment]
[gist ](https://gist.github.com/MddMBorg/92b6e898efe07d7ccf0b3f5f14543f40) for the log

as for the first part, i thought that the cruise control should be able to limit the courseplay course speed? was this changed?

**Comment by Tensuko** [comment]
The problem was, when you set your CC, CP will kinda delete this and you have to change it back.
Use the speed on field to control your worktool speed.

log is not complete

**Comment by MddMBorg** [comment]
Ah, okay. I had thought the field speed was for when moving between say the combi and the unload course when using mode 2. In that case, I'm happy for the issue to be closed.

As for the log, I had removed some personal info re. pc details and directories but other than that I think it's all there.

**Comment by Tensuko** [comment]
> Ah, okay. I had thought the field speed was for when moving between say the combi and the unload course when using mode 2. In that case, I'm happy for the issue to be closed.

That one as well.



> As for the log, I had removed some personal info re. pc details and directories but other than that I think it's all there.

Well, that is not much information we can do anything with...
