### ISSUE TITLE
Düngerstreuer schaltet in Mode 4 nicht mehr ab

### ISSUE THREAD

**Issue by rellek82** [Courseplay/courseplay#7312]
Hallo.
Mein Courseplayhelfer schaltet nach beendeter Arbeit auf dem Feld den Düngerstreuer nicht mehr ab und verbraucht weiterhin Dünger.
Courseplay: V 6.2.0.3
Karte: Steffishausen
Trakror: Claas Axion 870 (DLC)
Streuer: Kverneland Exacta (Kverneland&Vicon Equipment Pack)

In der Log konnte ich kein Error entdecken, kann diese aber nachher noch anhängen, wenn ich wieder am PC bin

**Comment by Tensuko** [comment]
IMMER das logfile anhängen.... https://github.com/Courseplay/courseplay/wiki

**Comment by rellek82** [comment]
Ja sorry, kommt so gegen 13 Uhr dazu. Ich bin noch unterwegs.

**Comment by rellek82** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6721517/log.txt)

**Comment by rellek82** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6721536/log.txt)

**Comment by Tensuko** [comment]
Was ist mit deiner Modliste los ?
Total unsortiert, wie soll man sich da zurecht finden ?

Wenn du better contracts hast -> MultiMissions raus

Das hier rausschmeißen:
Available mod: (Hash: dc50da9000f5e0307de7073619ade414) (Version: 0.51 Beta) AAA_HiredHelperTool

Also du musst dringend mal deine Mods aufräumen...

BTW: SP oder MP ?

**Comment by rellek82** [comment]
Ok, werd da mal aufräumen.
Spiele SP

**Comment by rellek82** [comment]
Hab das jetzt mal mit reduzierter Mod-Anzahl im Ordner probiert.
Die Log 1 stammt von einem Spielstand mit der Courseplay V6.4.0.3, wo es Probleme gibt.
Die Log 2 stammt von einem Spielstand mit der Courseplay V6.4.0.2, wo aber alles normal funktioniert.

[log1.txt](https://github.com/Courseplay/courseplay/files/6721875/log1.txt)
[log2.txt](https://github.com/Courseplay/courseplay/files/6721876/log2.txt)

**Comment by franky-bb** [comment]
Der Fehler tritt zB auch beim Güllefass auf. (Courseplay: V 6.2.0.3) Noch komischer wird es, wenn ich danach mit dem Güllefass manuell ohne CP zum Auftanken zum Kuhstall oder Schweinestall fahre. Will mit 'R' das Fass aufladen und es passiert nichts. Kein Auffüllen vom Fass. In der Courseplay: V 6.2.0.2 funktioniert es.

**Comment by rellek82** [comment]
Ok, dann bin ich ja schonmal nicht alleine mit dem Problem. 
Bei mir läuft das Auffüllen aber normal. Kann aber auch dran liegen, dass ich nur die Plane öffne und mit dem BigPack drüber fahre.

**Comment by Tensuko** [comment]
> 
> 
> Der Fehler tritt zB auch beim Güllefass auf. (Courseplay: V 6.2.0.3) Noch komischer wird es, wenn ich danach mit dem Güllefass manuell ohne CP zum Auftanken zum Kuhstall oder Schweinestall fahre. Will mit 'R' das Fass aufladen und es passiert nichts. Kein Auffüllen vom Fass. In der Courseplay: V 6.2.0.2 funktioniert es.

logfile ?

**Comment by Tensuko** [comment]
will be fixed in 6.4.0.4

**Comment by rellek82** [comment]
Danke
