### ISSUE TITLE
Coursplay Menu Fehler

### ISSUE THREAD

**Issue by Simsonfanatiker** [Courseplay/courseplay#7313]
Seitdem ich mit Coursplay spiele, bleibe ich nach wenigen Stunden in jeglichen Menü stecken. Egal ob es nun das vom Hühnerstall ist, von einer Produktion oder  der Schlaftrigger. 
Nur Spiel Neustarten bringt etwas. 
Log ist bei. 
Danke schonmal im Voraus.
[log.txt](https://github.com/Courseplay/courseplay/files/6722101/log.txt)

**Comment by Tensuko** [comment]
SP/MP ?
Sehe kein Error in der log an der es hängen könnte.

**Comment by Simsonfanatiker** [comment]
> SP/MP ?
> Sehe kein Error in der log an der es hängen könnte.

SingelPlayer... Der Fehler tritt nur auf wenn ich Coursplay aktiviert habe.

**Comment by Easton97-Jens** [comment]
@Simsonfanatiker du hast viele Mods die Fehler schmeißen wie der von der hot und hast ein nicht ls 19 mod drin. @Tensuko muss Der Courseplay   mod nicht FS19_Courseplay heißen wenn ich das richtig mit bekommen hab heißt er bei ihn nur Courseplay

**Comment by Tensuko** [comment]
Mal von da die neueste laden und nicht umbenennen etc...
https://github.com/Courseplay/courseplay/releases

**Comment by Hurri85** [comment]
Hallo,

Ich habe das selbe Problem seit ein paar Tagen das ich immer im Menü stecken bleiben. Wenn man auf einen Triggerpunkt zu geht wird wie automatisch "R" gedrückt. Habe jetzt schon ein paar Tage schon rumprobiert, wann genau der Fehler auftritt( Mods gelöscht oder Geräte getauscht etc.).

Also bei mir tritt der Fehler auf, wenn man mit dem Güllefass mit 2 kombinierte Kurse arbeitet. Und genau dann wenn CP auf den zweiten Kurs springt um das Güllefass aufzufüllen. Ob da jetzt ein Fahrzeug am Zielort steht oder nicht spielt keine Rolle.

Das ganze Problem ging mit Version 6.4.0.3 los. Gerade nochmal getestet mit Version 6.4.0.0 ist alles supi.
![Fehler_CP_6 4](https://user-images.githubusercontent.com/86884885/124359660-37ebcb80-dc26-11eb-8375-9348ff7bca6f.jpg)

**Comment by Simsonfanatiker** [comment]
> Hallo,
> 
> Ich habe das selbe Problem seit ein paar Tagen das ich immer im Menü stecken bleiben. Wenn man auf einen Triggerpunkt zu geht wird wie automatisch "R" gedrückt. Habe jetzt schon ein paar Tage schon rumprobiert, wann genau der Fehler auftritt( Mods gelöscht oder Geräte getauscht etc.).
> 
> Also bei mir tritt der Fehler auf, wenn man mit dem Güllefass mit 2 kombinierte Kurse arbeitet. Und genau dann wenn CP auf den zweiten Kurs springt um das Güllefass aufzufüllen. Ob da jetzt ein Fahrzeug am Zielort steht oder nicht spielt keine Rolle.
> 
> Das ganze Problem ging mit Version 6.4.0.3 los. Gerade nochmal getestet mit Version 6.4.0.0 ist alles supi.
> ![Fehler_CP_6 4](https://user-images.githubusercontent.com/86884885/124359660-37ebcb80-dc26-11eb-8375-9348ff7bca6f.jpg)
> 
> Der Name meiner CP-Datei (Zip) ist nicht umbenannt, also genauso wie ihr es immer frei gibt.

Also ich habe bei mir ein paar Mods raus gelöscht und die neuste Version genommen und es funktioniert wieder alles super

**Comment by Hurri85** [comment]
Ich hatte natürlich die Version 6.4.0.4 drauf und meinen Mod-Ordner habe ich auch mal richtig aufgeräumt. Die Frage ist ja was hat sich zwischen 6.4 und 6.4.04 geändert bei der Arbeit?

**Comment by Tensuko** [comment]
Fix dafür ist schon auf dem Weg.
Es sind GC Trigger, wenn man einen Refillkurs im Mode4 benutzt.

**Comment by Hurri85** [comment]
Danke

**Comment by schwiti6190** [comment]
Should be fixed with the newest version :)
