### ISSUE TITLE
Tasche / keine Tasche bei 1.Runde dreschen?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#7314]
Hallo cp Team
beim cp gabs in den (erweiterten)optionen doch die Möglichkeit das ausdreschen einer Tasche in der 1. Runde ums Feld aus- bzw einzustellen.
gibt es diese Option nichtmehr? ich finde sie nicht.
lg
andreas

**Comment by Tensuko** [comment]
Nein, das gab es nie.
Du kannst dies nur ausstellen, indem du den Drescher auf Fruchtumfahrung deaktiviert stellst.
Dann werden diese Manöver nicht mehr gemacht.

Es gibt noch das Abtanken im ersten Vorgewende, dann wird der Abfahrer auch beim Fahren vom Drescher gerufen.

**Comment by andreasthu** [comment]
Hallo Tensuko
Abtanken im Vorgewende habe ich aktiviert.
Trotzdem wird eine Tasche ausgedroschen,
Claas Lexion, capello quasar 16R, Mais.
Der Abfahrer fährt ab 66% Dtescherfüllstand zum Drescher (so eingestellt), fährt eine Weile hinterher aber nicht zum Rohr um abzutanken. Der Drescher stoppt bei 95%, drischt eine Tasche aus, der Abfahrer kommt zum Aufladen, dann drischt der Drescher weiter.
Lg
Andreas

**Comment by Tensuko** [comment]
Welche Version hast du ?

**Comment by andreasthu** [comment]
Die 6.4.0.3 hier vom github, zwei Tage alt, die neueste von gestern konnte ich mangels Internet am pc noch nicht downloaden.
Kann ich heute Abend machen, dann mit Bildern.
Brauchst du auch einen debug channel? 
Lg
Andreas

**Comment by Tensuko** [comment]
Mich würde es eher interessieren, seit wann das ist.
Also vergleich zur ModHub Version.

**Comment by andreasthu** [comment]
Hallo Tensuko
seit welcher version das so ist, keine ahnung, spiele mit seasons, 9 tage pro jahreszeit und meine letzte ernte ist schon ein paar realtime wochen her.
hier mal meine settings, diesmal mit dem rostelmash Drescher:
![fsScreen_2021_06_28_12_47_29](https://user-images.githubusercontent.com/24860501/123673159-6fcacb80-d840-11eb-9279-d44da4657aec.png)
![fsScreen_2021_06_28_12_47_50](https://user-images.githubusercontent.com/24860501/123673171-72c5bc00-d840-11eb-9445-93d33f88c88e.png)
![fsScreen_2021_06_28_12_47_56](https://user-images.githubusercontent.com/24860501/123673189-78230680-d840-11eb-9576-83aea93f074a.png)

der Abfahrer wird gerufen:
![fsScreen_2021_06_28_12_50_14](https://user-images.githubusercontent.com/24860501/123673239-88d37c80-d840-11eb-858b-3b9ae0c7bc1b.png)
![fsScreen_2021_06_28_12_50_17](https://user-images.githubusercontent.com/24860501/123673251-8bce6d00-d840-11eb-86a8-1a881f5995d3.png)
![fsScreen_2021_06_28_12_50_24](https://user-images.githubusercontent.com/24860501/123673279-92f57b00-d840-11eb-86cf-46a8d95fea5e.png)
![fsScreen_2021_06_28_12_50_26](https://user-images.githubusercontent.com/24860501/123673291-95f06b80-d840-11eb-8a07-002822362462.png)
![fsScreen_2021_06_28_12_50_59](https://user-images.githubusercontent.com/24860501/123673308-9a1c8900-d840-11eb-9df5-c95eeb0a1de9.png)

der Abfahrer fährt hinter dem Drescher her, aber nicht zum Rohr:
![fsScreen_2021_06_28_12_51_08](https://user-images.githubusercontent.com/24860501/123673359-a99bd200-d840-11eb-9553-fb0bba42532f.png)

der Drescher bleibt stehen und fährt zurück:
![fsScreen_2021_06_28_12_51_20](https://user-images.githubusercontent.com/24860501/123673395-b28ca380-d840-11eb-8e79-df37e8a04834.png)

drischt die Tasche aus
![fsScreen_2021_06_28_12_51_24](https://user-images.githubusercontent.com/24860501/123673425-be786580-d840-11eb-89f6-70fd45492d36.png)
![fsScreen_2021_06_28_12_51_38](https://user-images.githubusercontent.com/24860501/123673435-c0dabf80-d840-11eb-9425-700d20e6f665.png)


manchmal klappt es jedoch:
![fsScreen_2021_06_28_12_53_43](https://user-images.githubusercontent.com/24860501/123673559-e8318c80-d840-11eb-9fc4-9e836bfd95b0.png)
![fsScreen_2021_06_28_12_54_03](https://user-images.githubusercontent.com/24860501/123673570-ea93e680-d840-11eb-876b-c990c6d01672.png)

der Drescher bleibt bei 90% stehen und wartet auf den Abfahrer
![fsScreen_2021_06_28_12_54_16](https://user-images.githubusercontent.com/24860501/123673660-04352e00-d841-11eb-99cd-1d31aec4cd1a.png)
ohne eine Tasche auszudreschen

lg
andreas

**Comment by rohne83** [comment]
Wie Tensuko schon schrieb, die Einstellung Abtanken im Vorgewende hat nichts mit dem Taschen ausdreschen zu tun. Ersteres sorgt nur dafür, dass überhaupt auch im ersten Vorgewende die Abfahrer noch während der Fahrt zum Drescher gerufen werden, und nicht erst wenn der Drescher bereits voll ist. Das Taschen dreschen hängt mW soweit allein an der Fruchtumfahrung.
Auf deinen Screenshots hat der Abfahrer ja eigentlich immer ein deutlich höheres Tempo als der Drescher (21km/h kurz bevor der Drescher stoppt und die Tasche ausdrischt), was zumindest darauf hindeutet dass er gerade dabei ist unter das Rohr zu fahren, es nur nicht rechtzeitig schafft (DebugChannel 2 könnte da erhellend sein). Um das zu vermeiden müsstest du den Abfahrer halt schon bei niedrigerem Füllstand rufen lassen.
Dass das Verhalten mit dem Taschen Dreschen selbst an manchen Stellen des Feldes dann wieder abweicht, ist erstmal etwas seltsam, da kann Tensuko vielleicht mehr dazu sagen. Könnte aber evtl auch an der Map liegen (unsaubere Feldgrenzen, unsichtbare Kollisionen, etc).

**Comment by andreasthu** [comment]
Das ist es ja was mich irritiert.
Bei der ersten bilderserie, mit der Tasche, folgt der abfahrer ja einige Sekunden dem Drescher, ohne ihn einzuholen. Es ist auch keine collision in der Nähe, nur wiese, strand und Meer.
Und der andere Fall:
Bei den letzten drei Bildern sind am Feldrand Bäume (weger deiner erwähnten colli),  trotzdem bleibt der Drescher bei 90% Füllstand stehen (letztes Bild), sieht man an der 0 am Tacho und wartet auf den Abfahrer, der ist da sogar noch unterwegs zum Drescher,  ohne eine Tasche zu machen.
Werd das beim nächsten Feld mit debugchannel 2 beobachten 
Lg
andreas

**Comment by lxfTTjek** [comment]
Mode 8 will cause the game to freeze

**Comment by Tensuko** [comment]
Er bleibt mit 90% da stehen, weil der Abfahrer bereits gerufen wurde.
Normal sollte er ihn erst rufen, wenn er die Tasche geamcht hat -> Abtanken im ersten Vorgewende aus.

Ich behaupte mal, dass ist wieder eine spezielle Situation in die man da rein gerät.
Wir haben und können nicht von vorne rein alle Konstellationen abdecken.

Warum das mit der Tasche bei der anderen Situation geklappt hat ? Naja... alles eine Frage welchen STATE wir da hatten.
Wie @rohne83 sagte. Debugchannel 2 bzw 11 dazu könnte helfen.

**Comment by Tensuko** [comment]
Ende vom Lied, er macht die Tasche weil der Abfahrer nicht schnll genug ankam, ist halt so.
Man könnte die % zu los fahren runter drehen...
Letzten Endes ist es nur das erste Vorgewende und daher kein großes Drama.
Die Funktionen klappen so wie sie sollen.
