### ISSUE TITLE
Game wont load

### ISSUE THREAD

**Issue by ExploringAussie** [Courseplay/courseplay#7315]
So I added courseplay into my mod list and everything was fine, then I went to restart my game and the game wont load it just gets stuck on loading, soon as I remove courseplay the game loads fine, any ideas? Using modhub version of 6.4.0.0.

Ive attached the log file as well.

[log.txt](https://github.com/Courseplay/courseplay/files/6731410/log.txt)

**Comment by Mannie313** [comment]
mach mal den mod Boss_trailedLifter raus und teste bitte erneut.

**Comment by ExploringAussie** [comment]
Same thing, I also went and removed the item that was using courseplay (there was a harvester currently doing a job using courseplay when I turned the server off) and it booted fine, is this a thing? Can you not turn the server off whilst courseplay is doing a job?

**Comment by Tensuko** [comment]
2021-06-29 17:12 Error: Running LUA method 'loadSharedI3DFileFinished'.
2021-06-29 17:12 dataS/scripts/vehicles/specializations/Foldable.lua(1189) : attempt to perform arithmetic on field 'foldAnimTime' (a nil value)

mod Issue, any of your mods missis 'foldAnimTime'

Not a CP Issue. Closed.
