### ISSUE TITLE
Header's Lagging Behind

### ISSUE THREAD

**Issue by unfoldedcheese** [Courseplay/courseplay#7322]
Having an issue on a dedicated server. I had a harvester complete a course. All went well but once the course was complete, it bugged out the headers for the combine. The header attached to it will randomly stop moving and lag behind the combine and catch up a short time later. The other header which is on a trailer has a attach point, but when it gets attached it doesn't move. When its unattached, I can no clip through it.
![20210630203431_1](https://user-images.githubusercontent.com/86752098/124047989-5910aa00-d9e3-11eb-832d-34265972bba9.jpg)
![20210630203438_1](https://user-images.githubusercontent.com/86752098/124047990-5910aa00-d9e3-11eb-938e-4dd33500ab34.jpg)

**Comment by Tensuko** [comment]
#7285
and not even a logfile
