### ISSUE TITLE
Wie kann ich Cp davon überzeugen das er nicht die kolision überprüft.

### ISSUE THREAD

**Issue by RudiBergfeld** [Courseplay/courseplay#7329]
Hallo.
ich hbe die version 6.4.0.4 von cp wie kann ich ihn davon überzeugen das er bei der Fondlader arbeit nicht die kolision überprüft?
das ist bei mir so. Wenn ich Cp mit einem  Telelader und volle Schaufel  an eimem Trailer fahren lasse  sagt er mir" das er von einem Fahrzeug Blockkiert wird.
[log.txt](https://github.com/Courseplay/courseplay/files/6760276/log.txt)

**Comment by Tensuko** [comment]
Screenshot ?!

**Comment by RudiBergfeld** [comment]
Hallo Tensuko
![fsScreen_2021_07_05_11_02_19](https://user-images.githubusercontent.com/10323527/124447734-f40dd900-dd81-11eb-872a-e26c730d75e9.png)
![fsScreen_2021_07_05_11_03_52](https://user-images.githubusercontent.com/10323527/124447786-ff610480-dd81-11eb-8e81-d1241b40f341.png)

**Comment by TobiHH78** [comment]
Mit der neueren Version benötigt man doch nur noch einen Wartepunkt. Ist das evtl. ein alter Kurs?? Vielleicht mal neu einfahren mit nur einem Wartepunkt. Ob das das Problem ist weiß ich nicht, aber bei mir funktioniert es so ohne Probleme.

https://github.com/Courseplay/courseplay/issues/7276#issuecomment-861317582

**Comment by RudiBergfeld** [comment]
Hallo TobiHH78,
das habe ich nicht gewusst Danke für den hinweiss nun klabt es.
Das Tehma kann geschlossen werden
