### ISSUE TITLE
Mode 3: Driver will almost always do a right turn into the combine when it's graincart reaches 100%

### ISSUE THREAD

**Issue by WubbeOP** [Courseplay/courseplay#7332]
![fsScreen_2021_06_25_09_53_48](https://user-images.githubusercontent.com/58829804/124501865-a1084600-ddc2-11eb-94ac-9e0ce73b964f.png)

Title basically says it all. when a graincart reaches 100% while unloading a combine, the driver will always go straight for the start  point of the unloading course. more often than not this will result in the driver turning right into the combine it was unloading. It will also drive straight through crops (see screenshot).

I apologize if this was already posted. I didn't find a similar post.

**Comment by Tensuko** [comment]
Thrown on all debugchannels for no reason, not a single logfile and most important no setting informations... read the wiki page!!! https://github.com/Courseplay/courseplay/wiki

**Comment by leo32128fs** [comment]
I also have the same problem , I will upload a video and log later

**Comment by Tensuko** [comment]
Ok I ask that for both of you now:
Avoid Fruit on or off at the Mode3 Driver ?

**Comment by Tensuko** [comment]
What most ppl STILL don't understand, what it means when Avoid Fruit is off, or the Pathfinder does notfind a way (we currently working on improoving the pathfinder), is that it will create a direct path to the start when full.
So like on A, the direct path will be crossing the Combine.
So you are left with 2 options:
- B you set the start/stop on the other side or
- C your Combine work the Fieldlines away from the start/stop (thats what ppl used to do with the super old Mode2).
![AvoidFruit](https://user-images.githubusercontent.com/27344744/124560719-6abbdc80-de3d-11eb-8b0c-eb068130d84d.png)

**Comment by WubbeOP** [comment]
sorry, will upload logfile later when I'm at my PC again. 

Avoid Fruit is on. I will always have headlands all the way around a field so there should be a way to find a path around the fruit. Interstingly enough, if I turn the driver off when it wants to collide with the combine and then turn it back on again it will actually often take a path around the fruit.

**Comment by leo32128fs** [comment]
> O que a maioria ppl AINDA não entende, o que significa quando Evitar Frutas está desligado, ou o Pathfinder não encontra uma maneira (atualmente trabalhando em improoving o desbravador), é que ele vai criar um caminho direto para o início quando cheio.
> Assim como em A, o caminho direto será cruzando o Combine.
> Então você fica com 2 opções:
> 
> * B você definir o start/stop do outro lado ou
> * C seu Combine trabalhar as linhas de campo longe do início/stop (isso é o que ppl costumava fazer com o mode2 super antigo).
>   ![AvoidFruit](https://user-images.githubusercontent.com/27344744/124560719-6abbdc80-de3d-11eb-8b0c-eb068130d84d.png)

Yes I did that and it worked perfectly , for me there are no more doubts ok , thanks for the tip

**Comment by rohne83** [comment]
This looks like the issue I had with #6832. That one was caused by the size of the trailer (in your case the grain cart) being set to too huge values. To check whether this is the case, type in console _gsVehicleDebugAttributes_ and press F5 twice.

**Comment by WubbeOP** [comment]
![fsScreen_2021_07_07_19_14_47](https://user-images.githubusercontent.com/58829804/124801960-be224d80-df57-11eb-9ae3-cd4f99e8b170.png)

Doesn't look too bad here.
Also, I had this issue with stock as well as modded graincarts.

**Comment by theSwed506** [comment]
This issue is occuring quite often when you use multiple combines and lands.
Couldnt it be a solution to make the grain cart driver stop or slow down for x seconds when it is full?
Just to let the combine get some distance?

**Comment by rohne83** [comment]
It's doing that already. The last weeks I was working quite often with grain carts, lands and multiple combines, and never had this issue. For me, when the cart was full, it stopped, calculated a path and went to the unloading point avoiding any crops or other obstacles. Seems for any reason the pathfinder is failing in your case. @Tensuko correct me, but I guess debug channel 11 (plus 3 for the overloader itself) might help to find out why.

**Comment by pvaiko** [comment]
I don't remember what our manual says, but a common problem is the set up of the unload course. In case A on that picture for instance if the course end/start waypoints are too close to the fruit for the tractor to turn into the direction of the unload course without going through the fruit, the pathfinder may fail.

You should really never have your unload course ending/starting on the field, it should always be plenty of room for the tractor to turn into the first waypoint's direction without going through the fruit.

**Comment by WubbeOP** [comment]
that might actually be a good tip @pvaiko, i will try that
