### ISSUE TITLE
Multiple Combine Issue - pathfinder drive to close to fruit, so will get stopped by combine

### ISSUE THREAD

**Issue by Bobster82** [Courseplay/courseplay#7333]
Hello CP team,

When I use multiple combines on a field and the 1st or 2nd combine calls a unloader, the unloader gets hold back due the 3rd combine... Its slowing down when it gets close to the 3rd one, so it can never reach the others...
So can de unloader get a diff path to the other combines a little further from the fruit? Or the unloader not slowing down if its not next to the combine its need to be?
Or its there something else i need to set-up? 

Thanks in advance!

![fs19_cp](https://user-images.githubusercontent.com/47780758/124514742-09b0ec00-ddde-11eb-9540-b7da343dea9b.png)

**Comment by Tensuko** [comment]
The path would be interesting at this situation, it looks like it turned towards the combine.

**Comment by Bobster82** [comment]
> The path would be interesting at this situation, it looks like it turned towards the combine.

Maybe this video wil help to see the 'issue'

https://www.youtube.com/watch?v=kAosuis8na4

**Comment by Tensuko** [comment]
As I guessed, we drive to close to the fruit and so we get blocked.
Will have this as enhancement.
