### ISSUE TITLE
Since 6.4.0.4(probably), some equipment has become impossible to configure for purchase

### ISSUE THREAD

**Issue by vitalii2011** [Courseplay/courseplay#7334]
Video: https://drive.google.com/file/d/1rW6cNcjrMSSy3lidqVX9H07q0olGIcK4/view?usp=sharing 
log_CP_6.4.0.4_FS19_lsfmStationaryBalerPack: https://gist.github.com/vitalii2011/733624206528b2cd6a4c05644b778194 
log_CP_6.4.0.0_FS19_lsfmStationaryBalerPack(no Error): https://gist.github.com/vitalii2011/7d2d93eaf56fd8ae967a67421d0a7f61

log_CP_6.4.0.4_FS19_ITS_SynTrac: https://gist.github.com/vitalii2011/570dac5dee95445c07227ac06f5a264e
log_CP_6.4.0.0_FS19_ITS_SynTrac(no Error): https://gist.github.com/vitalii2011/095427fbbae65d086d698e95c642a035

**Comment by Tensuko** [comment]
Error WorkArea, Duplcate of #7324
