### ISSUE TITLE
maximum allowed workers?

### ISSUE THREAD

**Issue by Martin-L45** [Courseplay/courseplay#7335]
when using more than 10 workers i get the following lua error
2021-07-06 16:52 Error: Running LUA method 'update'.
2021-07-06 16:52 dataS/scripts/vehicles/Vehicle.lua(2920) : attempt to index a nil value

In #7255 i thought this was caused by autodrive. but a test on ravenport with only Courseplay in the modfolder i get the error.
The error reappears every time i tap into the tractor with the 11th Courseplay driver.

[log.txt](https://github.com/Courseplay/courseplay/files/6770993/log.txt)

**Comment by Tensuko** [comment]
We don't have created a limit actually...
I don't know if there is a limit by GIANTS.
Will have to test that.

**Comment by Tensuko** [comment]
I found this interesting topic to that Error:
http://www.blackpanthergroup.de/forum/viewtopic.php?t=993&start=100

**Comment by Martin-L45** [comment]
I´ll take a look. but my German is very bad. (google translate)
Don´t know if it is useful. But i tried running 11 tractors with autodrive and i did not get the error. Maybe the fix Stephan used in Autodrive can be used?

**Comment by Tensuko** [comment]
We will have a look, weird that it comes up suddenly...

**Comment by Martin-L45** [comment]
Maybe there is not many people that use more than 10 drivers?
I just tried with V6.02.00079 and did not get any error
But with V6.03.00058 the error is there. You want me to try to pin down the version where it started?

**Comment by Tensuko** [comment]
No, since those Versions are way to old...

**Comment by Martin-L45** [comment]
Ok. Let me know if you need me to try anything

**Comment by jala15** [comment]
FS19 has an implicit limit of 10 (Letters A-J) helpers, counting vanilla AI drivers, CP drivers, AD drivers, AIVE drivers...
It runs out of helper names. More about this here: https://github.com/Stephan-S/FS19_AutoDrive/issues/1910
Maybe having 11 CP helpers does not cause an issue but 11 CP helpers + pressing 'H' does.
AD fix: https://github.com/Stephan-S/FS19_AutoDrive/commit/f472f5d6d69a82f56d3bb6e3ba3495388712386e

**Comment by Tensuko** [comment]
I might guess this is becouse we changed all our Drivers to GIANTS AI Drivers.

**Comment by Martin-L45** [comment]
i tried jala15´s fix and added the "maps_helpers.xml" with 20 helpers to my modmap this solved the issue for me. 
But changing basegame files usually breaks multiplayer. So this fix is only for modmaps... Right?

**Comment by jala15** [comment]
> i tried jala15´s fix and added the "maps_helpers.xml" with 20 helpers to my modmap this solved the issue for me.
> But changing basegame files usually breaks multiplayer. So this fix is only for modmaps... Right?

Yes, changing files breaks multiplayer. I'd recommend to not change anything and wait for a fix, but if you managed to change it in your mod map and it works fine that's ok 👌 
That modified mod map will not be MP ready anymore, but you can always redownload it

**Comment by Martin-L45** [comment]
Just did a test with your fix. 12 tractors running and no error. This is pretty awesome...

Thanks for your hard work

**Comment by Bobster82** [comment]
Great, thanks!
I thought it was my own mod generating this lua error. lol
Its just too many workers hehe.

Thanks for the fix cp team!

**Comment by schwiti6190** [comment]
Should be fixes with the newest version :)

**Comment by dete96** [comment]
I still have the problem, that I can´t have more than 10 helpers. When I try to employ the 11th, I get this error:

2021-09-09 14:29 Error: Running LUA method 'mouseEvent'.
2021-09-09 14:29 C:/Users/Nutzer/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/base.lua:1247: attempt to index local 'currentHelper' (a nil value)

I use version 6.4.0.6.

**Comment by Tensuko** [comment]
Next Version will have this fixed.

**Comment by dete96** [comment]
Ah! Sorry mate. I thought it should already be in the actual version and for some reason doesn't work for me. Thank you for your work!
