### ISSUE TITLE
[feature request] Anfahrt 1.Punkt nur vorwärts?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#7338]
Hallo Leute
manchmal fahren Traktore den ersten Punkt nMn relativ umständlich an.
so z.b.:
![fsScreen_2021_07_07_08_56_20](https://user-images.githubusercontent.com/24860501/124714346-f303b580-df01-11eb-8b70-18792d91f595.png)
ich hab dazu mal einen relativ unkomlizierten möglichen Kurs in gelb dazugezeichnet, ohne Rückwärtsfahrt.
oder kann man das in cp jetzt schon so einstellen, das der erste punkt nur in Vorwärtsfahrt angefahren wird?
lg
andreas

**Comment by Tensuko** [comment]
#5985
