### ISSUE TITLE
suggest : adjusting the global parameters to change the driving style, depending on the map , in mode 2 / 3

### ISSUE THREAD

**Issue by magicmana** [Courseplay/courseplay#7339]
about the problem in  few  issues  like  : 
https://github.com/Courseplay/courseplay/issues/7333
https://github.com/Courseplay/courseplay/issues/7332

on  0,5 ha  with auger wagon  default value :   Field speed at  24 km/h   and  Turning circle at  11 meter is  fine
on 100 ha  with  auger wagon  :  Field speed at  24 km/h   and  Turning circle at  11 meter , (exept on first  headland)   very not interresting .
  

why  not creating a  global  parameter   who multiply ,  default   speed and    Turning circle   ,  for all  vehicle in the  map   by 1 ,2 or 3  (when mode 2 or  3  used)

 like   :

1X :  Field speed  : 24  (X1)= 24 km/h    Turning circle at  11(X1) = 11  meter
2X :  Field speed  : 24  (X2)= 48 km/h    Turning circle at  11(X2) = 22  meter
3X :  Field speed  : 24  (X3)= 72 km/h    Turning circle at  11(X3) = 33  meter

should  be  correct a lot of  problem  in  2/3 mode  with  big material  like  :  
-   tractor   turn  to short  with combine with 13 m  cutter 
-   truck arrive at 70km/h    to  potato combine  ,  try to turn   at 180° on only 11 meter and miss the trigger
-  combine combine with 13 m  cutter , have not  time to  detect collision  , with   tractor  with a   11m Turning circle
-  etc...

and  finally  with  Avoid Fruit on  , an waypath enable   ;  for  the rare case  when the  tractor  haven't   enouth   free area   for  turn  : 

 you  should   make some rules    like  : 

if  10 fail  when 3X selected >>  try with 2X  value
if  10 fail  when 2X selected >>  try with 1X  value

**Comment by magicmana** [comment]
i'm  agree with the rest of  your responce  but  : 


72km/h Field speed is super unrealsitic!

"The UK is not able to register trailers or trucks with tyres fitted with anything other than high speed ratings. Large flotation tyres are often designed for the agricultural market with 65 kph max speed and load ratings. As such UK operators have to make the choice between road going units, specified on road tyres, or agricultural units on flotation tyres."

source :  (https://www.continentalsoiltechnology.com/silage-trailers-bergmann/)


and   is  currently  my   usage in fs19   :  make sillage on 4X maps with maize plus . :-)

**Comment by Tensuko** [comment]
Well for the speed you should be able to easy set the speed to the value that you want.
But getting that to default 'just becouse you play like that' is not the right way.
You are always free to copy the repository and keep it up to date + your changes on the code.
