### ISSUE TITLE
Mode 8 Water und diesel ?

### ISSUE THREAD

**Issue by JanZacher** [Courseplay/courseplay#734]
hi once asked who it possible that you can add in mode8 zurbring mode water and diesel fuel up a the one of the diesel bring to the Court because waiting until the diesel trailer is empty and water-holding can lead to animals who it possible that because of to build a?

MFG

**Comment by JakobTischler** [comment]
Added support for fuel and water transport in mode 8 in build 0152.

**Comment by sootysax** [comment]
does this also work with milk sales?

**Comment by JakobTischler** [comment]
Nope.

**Comment by Maxcdr** [comment]
@JakobTischler : Is it your last Nope? :)
It works very well with water but not with milk: I use MilkTruckTrigger (http://www.modhoster.com/mods/milktrucktrigger). Any chance to get it works with milk? Thanks a lot.
