### ISSUE TITLE
Vehicle moves in a different direction for no reason instead of following course - Fahrzeug fährt ohne Grund in eine andere Richtung, anstatt Kurs zu folgen

### ISSUE THREAD

**Issue by haamic** [Courseplay/courseplay#7340]
Hello,
I am now using version 6.4.0.4, since some versions I have the following error. 
I create a field course to collect e.g. grass. I attach a course to an Autodrive unloading destination.
The vehicle should collect everything and then drive to the unloading destination with the last grass. This always worked before, but now the vehicle drives approx. 3-5 waypoints shortly before the destination in a different direction instead of following the course.
What could be causing this behaviour? The courseplay course actually ends at the actual destination, but the vehicle steers in an unknown direction shortly beforehand and then drives until it bumps into something.
If I use the course in the autodrive to the destination, it works.
Greetings Micha
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Hallo,
ich nutze jetzt version 6.4.0.4, seit einigen Versionen habe ich folgenden Fehler. 
Ich erstelle einen Feldkurs zum Sammeln von z.b. Gras. Hänge daran einen Kurs zu einem Autodrive-Entladeziel.
Das Fahrzeug soll also alles aufsammeln und dann mit dem letzten Rest zum Entladeziel fahren. Das klappte sonst immer, nur jetzt fährt das Fahrzeug ca. 3-5 Wegpunkte kurz vor dem Ziel, in eine andere Richtung, anstatt dem Kurs zu folgen.
Wodurch könnte dieses Verhalten verursacht werden? Der Courseplay Kurs endet tatsächlich am eigentlichen Ziel, nur lenkt das Fahrzeug kurz vorher in eine unbekannte Richtung und fährt dann solange, bis es irgendwo dagegen stößt.
Nutze ich den Kurs im Autodrive zum Ziel, funktioniert das.
Gruss Micha

**Comment by Tensuko** [comment]
logfile, screenshot vom Kurs mit WEGPUNKTEN an und nicht das dbg Auge...
Ich kann mir vorstellen, dass je nach dem wie der AD Kurs gebaut ist, wir falsche Wegpunkte bekommen.

**Comment by haamic** [comment]
Nach mehrfachen Tests, konnte ich keine Fehler feststellen auf Original-Maps. Nur auf (einigen) Mod-Maps scheint es nicht so zu funktionieren, wie es sollte. Darum schliesse ich hier.
