### ISSUE TITLE
[Feature Request] - Option to do 'center' on a 2-track course

### ISSUE THREAD

**Issue by djnekkid** [Courseplay/courseplay#7348]
Hello AWESOME Farm Sim Tycoon devs!

Its me again, with some more or less dumb request 😄 

As you know, there are alot of implements that are typically "heavy and not so wide", and "light but wide AF", and there are usually quite easy to find multple-of-two's.

Say, for instance, the 12m JD plow from modhub, but also the 24m cultivator or fertilizer spreader.

So, in this case, i would make a "2 wide" course for the plows, and a new 'single' course for the fert spreader.

Would it be possible to add a 'center' option even on 'non-odd' number of multi-tool courses?
This so i can use the same course for multiple things, where you have two narrow implements, and one wide one

**Comment by Tensuko** [comment]
You talk about a course for 2x 12m and 1x 24m for example and just want to use the same course for both ?

**Comment by djnekkid** [comment]
The reason I ask, i could then do the 'convoy', and the would not crash into eachother (probably)

![image](https://user-images.githubusercontent.com/65364380/125202524-406e8280-e274-11eb-8311-6656ff2d7781.png)

**Comment by Tensuko** [comment]
Got it!
Should work with the suggested workarround, but we will see if we can do something there.

**Comment by lxfTTjek** [comment]
Can the rutting be added again

**Comment by Tensuko** [comment]
> 
> 
> Can the rutting be added again

???

**Comment by lxfTTjek** [comment]
Can the vehicle leave wheel marks when the vehicle is running

**Comment by lxfTTjek** [comment]
![fsScreen_2021_07_13_13_58_53](https://user-images.githubusercontent.com/24203150/125400290-4c795200-e3e4-11eb-8674-8c9f1bc60e0d.png)
