### ISSUE TITLE
Combine keeps resting after unloading

### ISSUE THREAD

**Issue by LasseLandmand** [Courseplay/courseplay#7349]
Tested on version v6.4.0.4 and v6.4.0.3
This is a recurring issue, that I cannot seem to solve, or find a good workaround
[log.txt](https://github.com/Courseplay/courseplay/files/6797038/log.txt)

issue: Combine is resting and doesn't start combining again after unloading, it just sits and burns fuel  

all settings are default except for:
- stop when unloading is enabled
- Avoid fruit is enabled for combine and tractor
-
I reproduced the issue and described it with the screenshots and text. 
![Skærmbillede 2021-07-11 153827](https://user-images.githubusercontent.com/68656400/125197664-f4fda980-e25e-11eb-8204-d1810a06d900.png)
Full combine, waiting for unload

![Skærmbillede 2021-07-11 153842](https://user-images.githubusercontent.com/68656400/125197670-f929c700-e25e-11eb-97c7-38abe20cedb1.png)
Tractor driving to unload the combine

![Skærmbillede 2021-07-11 153912](https://user-images.githubusercontent.com/68656400/125197683-021a9880-e25f-11eb-90eb-fbd13fd79a1a.png)
Combine unloading into trailer

![Skærmbillede 2021-07-11 153945](https://user-images.githubusercontent.com/68656400/125197679-ffb83e80-e25e-11eb-9ea0-48e8673745a7.png)
Tractor moves away from the combine

![Skærmbillede 2021-07-11 154023](https://user-images.githubusercontent.com/68656400/125197686-0646b600-e25f-11eb-8f60-fc487be92ec5.png)
In this case the trailer is full so the tractor drives to the silo. 
The issue also happens when the trailer isn't full and the tractor simply moves back out of the way. 
![Skærmbillede 2021-07-11 154537](https://user-images.githubusercontent.com/68656400/125197704-1494d200-e25f-11eb-8362-8d5621acced9.png)
The combine is still resting and doesn't start combining again after unloading

**Comment by Tensuko** [comment]
Ok I will have a look at this. Mostly I had only the pocket or unload while pipe is on the correct side to test this.

For your log, Channel 6 (Combine is driven in Mode6) would be more interesting :)

Also you should remove this from your mods Folder:
Error: Failed to open xml file 'C:/Users/Lasse/OneDrive/privat/Dokumenter/My Games/FarmingSimulator2019/mods/UnpackFuelUsage/modDesc.xml'.
Available mod: (Hash: e30889c77908e9d2018149fd044244fa) UnpackFuelUsage
Error: Missing descVersion attribute in mod UnpackFuelUsage
Error: Failed to open xml file 'C:/Users/Lasse/OneDrive/privat/Dokumenter/My Games/FarmingSimulator2019/mods/UNZIP_ME_DFMEP_GC_BINS/modDesc.xml'.
Available mod: (Hash: dee3558d1fe245b151841d28f155cdcb) UNZIP_ME_DFMEP_GC_BINS
Error: Missing descVersion attribute in mod UNZIP_ME_DFMEP_GC_BINS

Also I am not sure if this Mod creates a conflict:
(Version: 1.3.1.0) dxm_lua_fuelusage

**Comment by LasseLandmand** [comment]
Okay, I will recreate the issue with channel 6 enabled, and removing those mods

**Comment by Misamangame** [comment]
@LasseLandmand Did you tried to reproduce this not sitting directly in combine? I know I had same problem long time ago when combine finished unloading and just sit still not continuing the course. Found out that simply not beiing in a combine, be in tractor or somewhere else helped. Haven't tried it since though.

**Comment by LasseLandmand** [comment]
@Misamangame Holy shit that works, I just harvested 20 acres, where it drove forward and starting combining again after unloading into the trailer. 

Conclusion: Not being in the combine while unloading solves the issue.

**Comment by Tensuko** [comment]
> Conclusion: Not being in the combine while unloading solves the issue.

Thats interesting, will have a look on that too.
