### ISSUE TITLE
Pushing outside of the bunker 

### ISSUE THREAD

**Issue by Andystrong8484** [Courseplay/courseplay#7350]
So i deleted the old route and setup a new one for using the shield to buckrake the bunker put it seems that the worker is pushing a of out side of the pic 

![fsScreen_2021_07_11_17_41_21](https://user-images.githubusercontent.com/75746655/125203151-3e55f500-e26f-11eb-9108-ac1d5f1be830.png)
![fsScreen_2021_07_11_17_41_46](https://user-images.githubusercontent.com/75746655/125203169-4ca41100-e26f-11eb-8f68-9babc21cc89c.png)

**Comment by Tensuko** [comment]
logfile ?
Also we had some tweaks by @MddMBorg in #7320 who make sure it won't push out so far.
So else you have an old version (logfile...) or your silo is some special one... debugchannel 9 and 10 + temporary course lines active should help to see more.

**Comment by Andystrong8484** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6797480/log.txt)

**Comment by Andystrong8484** [comment]
TBH i cant get it to replicate 
![fsScreen_2021_07_11_19_46_10](https://user-images.githubusercontent.com/75746655/125206754-c1337b80-e280-11eb-90c7-5e30b9c11eeb.png)
![fsScreen_2021_07_11_19_46_23](https://user-images.githubusercontent.com/75746655/125206757-c395d580-e280-11eb-94be-7a428de87404.png)

This is the Maize pit above 


Now the Grass pit
![fsScreen_2021_07_11_19_50_33](https://user-images.githubusercontent.com/75746655/125206900-62223680-e281-11eb-8ad5-7b226250e839.png)
![fsScreen_2021_07_11_19_50_53](https://user-images.githubusercontent.com/75746655/125206901-64849080-e281-11eb-8338-475c89a51b9e.png)

**Comment by Tensuko** [comment]
Available mod: (Hash: 38aa1fb1f887eabed3318753b003cf9e) (Version: 6.4.0.3) FS19_Courseplay
->
https://github.com/Courseplay/courseplay/releases
->
Modified the SiloDriver to drive back less to prevent pushing chaff out of bunker as much with shield.
