### ISSUE TITLE
Courseplay worker kicking out when harvesting maize

### ISSUE THREAD

**Issue by Andystrong8484** [Courseplay/courseplay#7351]
So have a programmed route for the worker for carting away from the chopper but it keeps kicking out tried with mods and base game kit
![fsScreen_2021_07_12_13_14_56](https://user-images.githubusercontent.com/75746655/125286906-369c5c00-e314-11eb-87f0-d85a24771114.png)

**Comment by Andystrong8484** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6801297/log.txt)

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki 
->
https://github.com/Courseplay/courseplay/releases
-> fixes #7307 

Why Channel 10 and 12 active, it would have been channel 2, but anyway, read Wiki first...
https://github.com/Courseplay/courseplay/wiki/Debug-Channels
