### ISSUE TITLE
Combines all appearing as in same field when setting up grain carts

### ISSUE THREAD

**Issue by LivinOnAPlayer** [Courseplay/courseplay#7352]
I have two combines in each field in my current save game. 17 and 18 in my case, but all combines are appearing in the menu where you can select which combine the grain cart looks for as being in field 3.

**Comment by Tensuko** [comment]
logfile, screenshot, are combines set to mode6 and started ?

**Comment by LivinOnAPlayer** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6803093/log.txt)

Yes, combines are in mode6 and started. 
![Screenshot 2021-07-12 142730](https://user-images.githubusercontent.com/29064715/125327144-5d12c500-e31d-11eb-9665-e6e4180a4b2f.jpg)

Thank you!

**Comment by Tensuko** [comment]
You got Callstacks in your log, that does show some Errors about the Map and other stuff.
Not sure if this is the Issue here for the wrong Field.
I will keep an eye on the Field Informations, but on my side everything is working just fine.

**Comment by LivinOnAPlayer** [comment]
Yeah. I noticed that. I haven't had issues on other maps up to this point, so I kind of guessed it was map related. But didn't know if there was a workaround or anything. Thanks for the response.
