### ISSUE TITLE
Combine drives to wrong point when starting

### ISSUE THREAD

**Issue by nolan771234** [Courseplay/courseplay#7353]
When i start my combine i tell it to go to the first point, it goes to some random arbitrary point it made up. I have a new holland cr10 with a 45 foot draper in big fields farm that i plowed so that it only has 8 fields. the top left field created is the only one with this problem. All other fields work on this map, although having to fix some collision issues because i run 2 fields with 2 combines, 1 grain cart, and 2 trucks each, and 2 pickup wagons with autodrive to unload. I understand i push courseplay to the max, but this is just weird. I attached my log, a screen recording as well as my savegame and courseplay courses for reference. (i used mediafire because it wouldn't upload). https://www.mediafire.com/file/maigjqhc0gepqww/Combine+goes+to+wrong+point.zip/file
Also, i have an issue with this map where it will act like it's combining with the header down, going through the field etc. and it will just not put any grain in the tank or delete any crop or put straw swath out the back. This is fixed by restarting the course, but is just annoying. I don't have logs or screen recording of this, but can get if you like.

**Comment by Tensuko** [comment]
Why did you throw on all debugchannels that you could find?...

You should stay in front of the start WP and also I would select choose startpoint on map and put it more to the left at the edge.

When combine does not pick up anything, it had wrong fruit on its way and this is a known Issue from FS.

**Comment by nolan771234** [comment]
Hello, I turned all the debug channels because i didn't know which ones to put on. Choosing the start point worked, and it just works like normal. I guess i need to fix the patches of different crop types in my fields that happen when you use the largest equipment in the game.
