### ISSUE TITLE
Ballen Sammeln per Courseplay und abfahren per AutoDrive

### ISSUE THREAD

**Issue by regs1980** [Courseplay/courseplay#7356]
Besteht die Möglichkeit das selbe wie ihr in Mode 2 gemacht habt, auch für die Ballen Sektion zu machen, mit CP sammeln und an AD übergeben.

**Comment by Playlord75** [comment]
Soweit ich das weis wird das nicht funtionieren bzw per ad seite nich funtionieren weil die dem abfahrer nicht noch die funtion einbauen wollen das er denn ballen stacker entladen kann weiß nicht bei welchem stand sie zur zeit stehen aber es hieß vor ein paar monaten wo ich das schon einmal nachgefagt habe das sie der KI nicht auch noch die ballen auto stacker entlade funtion verbauen wollen weil das zu viel arbeit wehre, keine ahnung wie es jetzt ausieht aber ich denke er weniger das sich was dran geändert hat

**Comment by regs1980** [comment]
Leider hat sich da auch nicht viel getan, von daher kann man auch das ganze hier schließen, da haben sie sich lieber auf das falsche Fixiert als diese Funktion mit einzubauen, den Radlader Modus hätten sie sich schenken können, der taugt nicht viel.

**Comment by Tensuko** [comment]
> nur halt wenn das Silo leer ist erkennt CP in der neuen Version das nicht mehr und man muss von Hand abstellen.

So weit habe ich das noch nie getestet, aber guter Hinweis.
