### ISSUE TITLE
Courseplay findet mich nicht, wenn ich mit der Ropa ernte

### ISSUE THREAD

**Issue by domijo98** [Courseplay/courseplay#7357]
Halihalo liebes Courseplay Team!

Ich möchte dass, Coursplay mich erkennt und abbunkert am Feld wenn ich mit, in meinem Fall mit der Ropa fahre. Aber das funktioniert nicht, auch nicht bei einem Drescher, habs gerade ausprobiert, das geht nur wenn die Maschine ebenfalls mit Courseplay am Feld arbeitet. Könnt ihr mir helfen und falls möglich das bitte ändern, das ginge ja früher auch, dass man selber ernten konnte und dann rief man Courseplay und somit war man gut unterwegs. Genauso ist es im Vorhinein mit der Erkennung des Dreschers, die funktioniert auch nur dann, wenn schon ein Feldkurs für den Drescher erstellt wurde. Ich schätze den Mod und eure Arbeit dazu sehr. Bitte um Rückmeldung
lg. domijo98

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ

**Comment by domijo98** [comment]
Sehr geehrtes Courseplay Team! Ich verstehe jetzt nicht was ich tun soll. Ich verstehe natürlich Englisch, aber ich bevorzuge Deutsch bitte helfen Sie mir auf Deutsch weiter. LG. domijo98Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Tensuko ***@***.***> Datum: 15.07.21  21:32  (GMT+01:00) An: Courseplay/courseplay ***@***.***> Cc: domijo98 ***@***.***>, Author ***@***.***> Betreff: Re: [Courseplay/courseplay] Courseplay findet mich nicht, wenn ich mit der Ropa ernte (#7357) 
Closed #7357.

**Comment by dete96** [comment]
Hi!

Zitat aus den FAQ:

"What is deactivated/doesn't work for now:

Combines/choppers have to be driven by a Courseplay helper. We aren't sure yet if we want to allow other (or manual) drivers, we'll see."

Das soll wohl heißen, dass dein Plan nicht funktionieren kann. Du musst einen CP Fahrer im Drescher oder im Roder haben.

**Comment by domijo98** [comment]
Hi date96! Und warum geh das nicht (mehr)? Das konnte man ja früher auch. Dann kann ich ja selber garnichts mehr machen in diesem Bereich. Mfg. domijo98 Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: dete96 ***@***.***> Datum: 15.07.21  22:30  (GMT+01:00) An: Courseplay/courseplay ***@***.***> Cc: domijo98 ***@***.***>, Author ***@***.***> Betreff: Re: [Courseplay/courseplay] Courseplay findet mich nicht, wenn ich mit der Ropa ernte (#7357) 

Hi!

Zitat aus den FAQ:

"What is deactivated/doesn't work for now:

Combines/choppers have to be driven by a Courseplay helper. We aren't sure yet if we want to allow other (or manual) drivers, we'll see."

Das soll wohl heißen, dass dein Plan nicht funktionieren kann. Du musst einen CP Fahrer im Drescher oder im Roder haben.

**Comment by regs1980** [comment]
Wenn du selber Fahren willst und dein Abfahrer Automatisiert sein soll, dann geht das nur mit AutoDrive, CP ist für die komplette Automatisierung auf einem Feld zuständig und das ist auch gut so wie es funktioniert.

**Comment by domijo98** [comment]
Hallo regs1908! Ok dass das nicht geht, weiß ich schon, aber meine Frage war warum??? Warum ist das eben nicht mehr im Spiel wie es schon mal war? LG. domijo98 Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: regs1980 ***@***.***> Datum: 16.07.21  08:40  (GMT+01:00) An: Courseplay/courseplay ***@***.***> Cc: domijo98 ***@***.***>, Author ***@***.***> Betreff: Re: [Courseplay/courseplay] Courseplay findet mich nicht, wenn ich mit der Ropa ernte (#7357) 

Wenn du selber Fahren willst und dein Abfahrer Automatisiert sein soll, dann geht das nur mit AutoDrive, CP ist für die komplette Automatisierung auf einem Feld zuständig und das ist auch gut so wie es funktioniert.

**Comment by Tensuko** [comment]
Weil der Modus 2 komplett neu gebaut wurde, so wie viele andere Teile von CP.

Es ist so wie es ist, dafür haben wir das ins Wiki geschrieben.
Ständigs fragen warum hilft da auch nicht.
Wenn wir die Zeit und Lust haben, werden wir uns das noch mal anschauen ob wir das wieder einbauen könnne.

**Comment by domijo98** [comment]
Ok passt dankeVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Tensuko ***@***.***> Datum: 16.07.21  10:44  (GMT+01:00) An: Courseplay/courseplay ***@***.***> Cc: domijo98 ***@***.***>, Author ***@***.***> Betreff: Re: [Courseplay/courseplay] Courseplay findet mich nicht, wenn ich mit der Ropa ernte (#7357) 

Weil der Modus 2 komplett neu gebaut wurde, so wie viele andere Teile von CP.

Es ist so wie es ist, dafür haben wir das ins Wiki geschrieben.

Ständigs fragen warum hilft da auch nicht.

Wenn wir die Zeit und Lust haben, werden wir uns das noch mal anschauen ob wir das wieder einbauen könnne.
