### ISSUE TITLE
Schaufel Modus entleert nicht

### ISSUE THREAD

**Issue by DonBolli** [Courseplay/courseplay#7359]
Ich habe einen neuen Kurs eingefahren für den Schaufelmodus, jedoch entleert er die Schaufel nie.

[Video](https://www.youtube.com/watch?v=jsRgCdK2g8o)
[log.txt](https://github.com/Courseplay/courseplay/files/6830714/log.txt)

Ich verwende den Github Release 6.4.0.4

**Comment by Tensuko** [comment]
Weil dein Wartepunkt nicht Richtung Bunker schaut und warscheinlich auch zu dicht vor, oder bereits im Trigger ist...

Welche Map ist das ?

**Comment by DonBolli** [comment]
NF Marsch 4 fach OG 2.8

**Comment by regs1980** [comment]
Der Kurse ist Mist sorry, die Radien sind zu klein und du musst dem Lader etwas mehr Auslauf geben das er sich gerade stellen kann, außerdem kann der Startpunkt im Silo sein oder Kantennähe nicht so weit weg, wie du den hast.

kleines Beispiel
Rückwertspur schwarz, Vorwärtsspur rot

<img width="1539" alt="2021-07-16 16_35_31-Farming Simulator 19 2021 07 16 14 38 55 01 - YouTube" src="https://user-images.githubusercontent.com/13314443/125965223-0de57e0a-c138-48a1-a318-a90d7ef087a1.png">

**Comment by DonBolli** [comment]
Ich habe mehrere Kurse eingefahren und editiert, ich habe vor allem mit dem Triggerpunkt für das abladen herumgespielt. Jetzt funktioniert es. Danke für die Tipps.
