### ISSUE TITLE
CP-HUD öffnet nicht/ doesn't open

### ISSUE THREAD

**Issue by TMac063** [Courseplay/courseplay#7363]
Moin zusammen,
auch bei mir funktioniert nach dem Umstieg auf 6.4.0.4 und dem Vehicle Swap Extended Mod das CP HUD nicht mehr.
Nach Tastenbelegung soll die Taste Löschen (=Entf) das CP_HUD öffnen. Es tut sich aber nichts.
Spielen normalerweise im MP-Modus mit Dedi Server. Auch ein Wechsel in den SP Modus mit Savegame vom Server ändert nichts.
Habe im SP auf CP 6.4.0.3 gewechselt und auch den Vehicle Swap Extended Mod deinstalliert. Kein Erfolg.
Bin ich gedanklich irgendwo falsch abgebogen?
LG und Danke im Voraus
TMac063
[log.txt](https://github.com/Courseplay/courseplay/files/6836212/log.txt)

**Comment by Tensuko** [comment]
Man beachte dieses Sticky: #7285
Auch Savegames aus dem MP in den SP bringen ist so eine sache.
Es kann sein, dass dein HUD offen ist, du das aber nicht siehst (geht der Mauszeiger denn an ?)

Ich vermute hier aber eine Doppelbelegung der Taste.

**Comment by TMac063** [comment]
Der Mauszeiger ist an und es wird bei der Tastaturbelegung auch keine Doppelbelegung angezeigt. Doppelbelegung hatte ich auch vermutet.

**Comment by Tensuko** [comment]
Für den SP, geh mal in die courseplaySettings.xml (im savegame) und entferne diese Zeile:
<courseplayHud posX="0.335938" posY="0.029861" hudScale="1.000000" uiScale="1.000000">
Speichern und save neu laden, ob dann das HUD wieder auf geht wie gewohnt.
Es kann sein, dass dies in einer älteren CP Version bei dir auf dem Server noch so gespeichert wurde.

Für den MP gilt: ModHub Version verwenden!

**Comment by audhen** [comment]
Ich hab das gleiche Problem.
Einen Schlepper mit offenem HUD zurückgesetzt -> Kaputt.
Verkaufen und neukaufen -> kein HUD mehr für diese Fahrzeuge.

Die Fahrzeuge, welche nicht zurückgesetzt oder neugekauft wurden, haben nicht das Problem...

**Comment by TMac063** [comment]
Wir haben die CP Version gewechselt auf 6.4.0.0. und einen früheren Spielstand geladen.
Hope this helps..
LG
TMac063

**Comment by Tensuko** [comment]
@audhen immer das logfile mit posten...
Same to you @TMac063

**Comment by TMac063** [comment]
@Tensuko:
Das habe ich bereits.
Siehe erster Post im Thread.
Mein Post von heute war unser Lösungsvorschlag für @auden

**Comment by audhen** [comment]
Moin!
Ein Neustart des Dedicated Servers hat Abhilfe geschaffen.
Übrigens ist mir aufgefallen, dass die Formatierung in der vehicles.xml nicht passt. Da sind teils bei den Attributen mehr als 1 Leerzeichen zwischen selbigen. Sollte den Parser nicht stören, aber...

Ich habe übrigens die Vermutung, dass es ein Netzwerkproblem ist. Meist wenn der Server laggt, tritt das ganze auf - also ob nicht die Info beim Client ankam, dass die GUI bereits geöffnet ist/war. Und dann hat man einen undefinierten Zustand. Bei mir bspw. war die GUI weg, beim Kollegen aber noch da.

Log ist leider schon überschrieben. Beim nächsten Auftreten werde ich es aber nachliefern!
