### ISSUE TITLE
Courseplay 6.4.0.4 causes use/Fill tool to rapidly flip on and off

### ISSUE THREAD

**Issue by Oph5pr1n6** [Courseplay/courseplay#7364]
When a worker is following a course, player is unable to fill tools, use items such as power washer, and chainsaws. The Fill/Unload, Turn on/Turn off buttons flip back and forth rapidly. Playing on PC with a controller. I have tried unplugging the controller and still get the issue. I stop the worker and the issue is resolved, until I start the worker again. I've recorded the issue, but the video is 30fps so you can't see how fast it is flipping, but you can hear it. https://youtu.be/MKvtinyt8VM

**Comment by Tensuko** [comment]
Could be the same Problem as in #7313
Fix is on the way, you can test the Branch in this PR #7331

**Comment by Oph5pr1n6** [comment]
Yes, it looks the same. Can't tell you how many times I got stuck in sleep or repair menus. I'll check the fix. Thanks.

**Comment by answermanitou** [comment]
Just now played with fresh 6.4.0.4 CP
and had same issue 
when AI drivers in work I cant did anything which have menu via R button such as kaercher, global company factories, shop etc.
This issue also was in version before 6.4.xx but in 6.4.0.0 all works properly
Console is clear

**Comment by Tensuko** [comment]
@answermanitou same for you, try the branch...

**Comment by Oph5pr1n6** [comment]
I've tried the new branch. It resolves the problem of getting stuck in the menus and not being able to use hand tools, but after accessing loading stations, seed, lime, fert, even grain from silos, will not load. just clicks of and never loads the tool. Again this only occurs while a courseplay worker is working. stopping the worker fixes the issue.

**Comment by Tensuko** [comment]
> I've tried the new branch. It resolves the problem of getting stuck in the menus and not being able to use hand tools, but after accessing loading stations, seed, lime, fert, even grain from silos, will not load. just clicks off and never loads the tool. Again this only occurs while a courseplay worker is working. stopping the worker fixes the issue.

I will check that...

**Comment by Tensuko** [comment]
2x Mode2 + 2x Mode6 and I can just load fine.
What Mode is working when that happens and do you have any refill course running.
![fsScreen_2021_07_22_21_37_53](https://user-images.githubusercontent.com/27344744/126699391-5b777f2c-2272-4d21-a271-299c55c8d27e.png)

**Comment by CaseFan** [comment]
Hello. I have same issue. I noticed that this appears for me then i select the CP driver who ended the course (drive from farm to animals dealer for example). After that, next trigger (buy animals, workshop, high preasure washer, big bags and etc) it starts rapidly engaging R button (assigned in controls for activate, refill). For example if I reach buy animals trigger, it rapidly opens purchase window, and you cannot close it, if you drive near bigbag it starts filling up. If i cancel CP driver before trigger, sometimes this 'bug' activates itself. Then this happened I used 2 CP courses: 1st. Fertilizing/seeding mode with refill route, 2nd simple drive course from farm to animals dealer. Log clear. Map Midwest Horizons 4x. Later i will try only with 1 CP driver.

**Comment by shadow250** [comment]
i also have this issue with 6.4.04  i was running a fert spreader with lime and a sprayer with herbicide. it seemed to glitch when i added the second driver. i keep getting stuck on an menu thats activated with R

[log.txt](https://github.com/Courseplay/courseplay/files/6914033/log.txt)

**Comment by Tensuko** [comment]
@CaseFan should be fixed wih 6.4.0.5

@shadow250 read what CaseFan wrote....

> Edit: haven't noticed new update. So far running good without any gliches on 6.4.0.5
