### ISSUE TITLE
Keyboard freezes after accepting a new contract.

### ISSUE THREAD

**Issue by sirDVD** [Courseplay/courseplay#7366]
After accepting a new contract, my keyboard will freeze. It only allows me to press each key once.
[log.txt](https://github.com/Courseplay/courseplay/files/6838381/log.txt)

**Comment by Tensuko** [comment]
Error: Shader archive 'C:/Users/Polar Bear/Documents/My Games/FarmingSimulator2019/shader_cache/shader_E1ACD26722C08EBB693C59F5D1ED3F18_3_16_1_7_182.sharc' is of an old incompatible type which does not contain a version number.

And what mission type?
What tools ?

**Comment by Tensuko** [comment]
Closed due to inactivity
