### ISSUE TITLE
Field tool does not wait until fully filled!

### ISSUE THREAD

**Issue by Dan-Gecko** [Courseplay/courseplay#7368]
Setting:
CP v6.4.0.4 + latest FS19
other mods are present (i.e. auger wagon accept lime, Coolamon chaser bins set)
most Giants DLCs are present and activated

Issue:
When driving a tractor with an auger wagon attachment to refill a course play driven tractor with a fertilizer/limewagon/planter/seeder shortly after filling starts the tractor being filled continues fieldwork without a full tank.

Expected behavior:
The expected (and in previous versions present) behavior for the tractor being filled would be to wait until full before continuing fieldwork.

Workaround:
I recall there being an option to customize that behavior in earlier builds (earlier in '2 years ago' earlier). But I searched the latest documentation and there seems to be none. 
So unless I am blind the only (and obvious) workaround I found is: Get in with the course play driver, deactivate the course, get in the filler, refill, get back in with the course play driver and start the course back up. Annoying for what course play is AND in considerations it did work as expected at some point.

Screenshots:
![000059_20210719 2031_Farming Simulator 19](https://user-images.githubusercontent.com/12811310/126210147-b0f242da-a3fa-4767-bf43-63a031e0d7f5.png)
![000060_20210719 2032_Farming Simulator 19](https://user-images.githubusercontent.com/12811310/126210155-8433710c-f154-49f4-9e5e-e8ae8931a9dc.png)
![000061_20210719 2033_Farming Simulator 19](https://user-images.githubusercontent.com/12811310/126210165-a62b24c8-d4d0-4500-b852-28c122f0a26b.png)

**Comment by Tensuko** [comment]
I am sure that it depends on the tool that is being refilled.
But yea we should take a look at that.
Not very high priority...

**Comment by rswyatt** [comment]
For me, it works every other trip. Generally it won't work the first time, will work the second trip to refill, and then works every other from there. 

To add to this, I'm using John Deere equipment, The DB90 planter with JD tractor. After a partial/successful refill it will go back to where it left off in the field, and then the engine shuts down while it waits for unfold... You have to "stop driver" and then start CP again with "nearest waypoint" - kind of annoying when you have multiple fields going on simultaneously.
