### ISSUE TITLE
Probleme mit verschiedene Spritzen bei CP (z.B. FENDT ROGATOR 6x5)

### ISSUE THREAD

**Issue by kopf-kind** [Courseplay/courseplay#7370]
Servus zusammen,
ich hoffe, dass mir hier wer weiterhelfen kann. Ein wenig am verzweifeln bin ich ja schon mittlerweile. 
Ich spiele seit neustem die Map "Gut Hohen Luckow". Es funktioniert rund um CoursePlay alles einwandfrei bis auf heute. Ich habe bereits auf anderen Maps Spritzen ohne Probleme einsetzen können. Bei dieser Map funktioniert auf einmal mit dem FENDT ROGATOR 6x5 nichts mehr bei CoursPlay.
Ich fahr ans Feld -> erstell den Kurs -> der Fendt fährt zum Startpunkt -> klappt alles aus und dann nichts ... Er bleibt einfach stehen und das obwohl er noch einen "Abfahrer" eingestellt hat.
Mit ein wenig hin und her bring ich Ihn anschließend zum fahren bis zum ersten Wendepunkt. Er beginnt nicht mal zum wenden und hört stattdessen davor auf. Ich habe bereits vieles probiert (z.B. den Fendt neu geladen und andere Spritzen ausprobiert) aber immer habe ich das selbe Problem. Auch der Horsch Leeb PT 350 funktioniert nicht.
Meine log.txt habe ich angefügt.
Ich hoffe irgendwer kann helfen.
Vorab vielen Dank!!!
[log.txt](https://github.com/Courseplay/courseplay/files/6850979/log.txt)

**Comment by Tensuko** [comment]
Nimm mal testweise (Version: 1.2.0.0) FS19_manureSystem raus. #7165

**Comment by kopf-kind** [comment]
Vorab Danke für die schnelle Antwort. Habe die Mod soeben rausgenommen. Leider ohne Erfolg ... Anbei der neue log.txt 

Ich hoffe wir kommen der Lösung näher ;)
[log.txt](https://github.com/Courseplay/courseplay/files/6857863/log.txt)

**Comment by Tensuko** [comment]
Hm dann muss ich mal schauen.
Nicht viel mit Spritzen gearbeitet die letzten Wochen.

**Comment by kopf-kind** [comment]
Kein stress. Bin ja froh wenn mir jemand hilf. Bin ja selber verwundert, dass es auf dieser Map nicht funktioniert und die Spritzen als Anhänger schon.

**Comment by kopf-kind** [comment]
Also ich habe nun Mod für Mod durchforstet und siehe da. Eine Mod die ich nie gedacht hätte war das Problem. Die "Abschleppstange" hat alles blockiert. Nachdem ich diese entfernt habe funktioniert wieder alles einwandfrei. 

Nochmals vielen Dank für die Hilfe!!! 
Ihr machts ne super Arbeit - weiter so :)
