### ISSUE TITLE
Digestate/Slurry CP course with AD refill  not working

### ISSUE THREAD

**Issue by Yasp0** [Courseplay/courseplay#7371]
I have a simple course for fertlizing the field. I use AD to refill at a slurry container.

When the tractor is heading for the container to refill and is near the container I can hear the refill sound, but the refilling does not start. As seen in the screenshot the CP course is still 'active'. When I click on 'Stop driver' it starts refilling.

- When I only use an AD course it does start refilling, so I think it has to do with CP.
- When I only use CP, so add a fertilize course and a refill course it does work. But I prefer to combine CP and AD :) Refilling with seeds or lime at a silo works fine.

Am I doing something wrong? I also tried to set the fillType ( 2nd screenshot), but does not helps.

![fs19-refill](https://user-images.githubusercontent.com/5689226/126470147-1b2c2774-45d2-4a1c-bb55-a25dc0c23cea.jpg)

![fs19-filltype](https://user-images.githubusercontent.com/5689226/126470791-c3f84087-b41f-418d-a99e-84f96e415b53.jpg)

**Comment by Tensuko** [comment]
logfile ?

**Comment by Yasp0** [comment]
The logfile:

[log.txt](https://github.com/Courseplay/courseplay/files/6855120/log.txt)

**Comment by Tensuko** [comment]
Error: Invalid mod name 'course-generator'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit
?????
Available mod: (Hash: ffde8fcd0e15a1091939cc7e788e2782) (Version: 1.0.0.17) FS17_DCK_QuickCamera
Error: Unsupported mod description version in mod FS17_DCK_QuickCamera
?????
(Version: 6.4.0.4) ZZZ_Courseplay
grrrr

-> https://github.com/Courseplay/courseplay/releases
download, copy into mods folder, done!

Mode4 with no refill info and refill course, set to use AD for refill in CP HUD.
Make sure you did configure AD correct.

@rohne83 you know AD better then me, did I miss anything ?

**Comment by Yasp0** [comment]
A new logfile with clean mods folder and properly used CP zip file: 
[log.txt](https://github.com/Courseplay/courseplay/files/6856333/log.txt)

CP: I use mode 4 and select to use AD for refill 
AD: I select Pickup method: select the field, container en 'filltype' (as seen in previous screenshot)

**Comment by rohne83** [comment]
@Tensuko settings look correct. I just tried myself and got the same issue. @Yasp0 does this only happen when refilling at those containers or also at fixed triggers like slurry pits?

**Comment by Tensuko** [comment]
But was it always like that, when CP gives over to AD, that CP keeps 'active' ? I thought that is normal...

**Comment by Yasp0** [comment]
@rohne83 It works fine when I set the BGA as a refill point. So yes, it happens 'only' with the container.  Also tried the Garant TSA trailer but that doesnt work.

**Comment by rohne83** [comment]
> 
> 
> But was it always like that, when CP gives over to AD, that CP keeps 'active' ? I thought that is normal...

As far as I remember, yes. CP helper always stayed engaged, although the vehicle is controlled by AD (you can even control it yourself if you switch off AD in that situation). Cannot remember this being different anytime before.
