### ISSUE TITLE
CP HUD lässt sich bei Saatmaschinen nicht mehr ausblenden

### ISSUE THREAD

**Issue by Cassy-Blair** [Courseplay/courseplay#7372]
So lange der Abfahrer aktiv ist, lässt sich das CP HUD bei Saatmaschinen (und wirklich nur bei Saatmaschinen) nicht mehr ausblenden, erst nachdem ich den Abfahrer entlassen habe, kann man es wieder ausblenden.  Egal ob ich Vanilla oder mit Mods spiele.

![grafik](https://user-images.githubusercontent.com/87262647/126595899-da0b6f30-efd9-4434-bdbf-408ae0faf21e.png)

![grafik](https://user-images.githubusercontent.com/87262647/126595932-fa1d016c-cff0-44d7-9971-07ec744bfae6.png)

**Comment by Tensuko** [comment]
Und wo ist hier wieder das logfile ?
https://github.com/Courseplay/courseplay/wiki

Klingt aber nach #7313

**Comment by Cassy-Blair** [comment]
In der Log war nichts zu sehen zu dem Problem. Aber werde eine neue Log erstellen, da seit den Screenshots das Spiel schon wieder neu gestartet wurde und eine neue Log ohne Aussaat erstellt wurde

**Comment by Tensuko** [comment]
> In der Log war nichts zu sehen zu dem Problem

Interessiert mich nicht, was du siehst.
Ich brauche Infos und die stehen in der log, nicht umsonst schreiben wir das ins wiki rein.
Es ist aber nervig immer wieder danach zu fragen...

Da du die ModHub Version hast (auch sowas sieht man in der log, die Version...) gehe ich nicht von dem einen bug aus den wir in der aktuellen 6.4.0.4 haben.
Daher vermute ich ein Modconflict.
Du könntest mal versuchen ob es geht wenn du diese Mods einzelnd raus nimmst und noch mal probierst:
(Version: 1.6.0.0) FS19_hudSmartShade
(Version: 1.0.0.0) FS19_hudToggle
(Version: 1.0.0.0) FS19_fillableVehicleInfo
(Version: 1.0.0.2) FS19_FilllevelWarning

Die hier solltest du raus nehmen, weil das bereits in better contracts enthalten ist:
(Version: 1.0.0.0) FS19_MoreMissionsAllowed

Das hier unktioniert eh nicht mehr, also raus damit:
(Version: 1.1.0.0) FS19_PrecisionFarmingAddon

Andere scriptmods musst du mal schauen.
Sind einige die ich nicht benutze und daher nichts zu sagen kann.
BulkBuy z.B. ist auch sehr Fehleranfällig.
ShopDelivery weis ich nicht.

**Comment by Cassy-Blair** [comment]
> Da du die ModHub Version hast (auch sowas sieht man in der log, die Version...)

Nein es ist eigentlich nicht die Modhub Version, hatte mir die zum release hier aus dem Github geladen.


> Die hier solltest du raus nehmen, weil das bereits in better contracts enthalten ist:
(Version: 1.0.0.0) FS19_MoreMissionsAllowed

Ohne MoreMissionsAllowed kann ich leider nur eine Mission annehmen, trotz Better Contracts

> Das hier unktioniert eh nicht mehr, also raus damit:
(Version: 1.1.0.0) FS19_PrecisionFarmingAddon

Habe ich in der PrecisionFarmingAddon.lua bereits gefixt und funktioniert wieder 
`Zeile 29         requiredVersion = "1.0.2.1"`

Werde mir dann mal die neue Version wieder direkt hier aus dem Github laden und testen

**Comment by Tensuko** [comment]
> Nein es ist eigentlich nicht die Modhub Version, hatte mir die zum release hier aus dem Github geladen.

Doch, ist es, steht doch in deiner log!
Available mod: (Hash: eb13ae431dd319fdc85f3df655ef24df) (Version: 6.4.0.0) FS19_Courseplay



> Ohne MoreMissionsAllowed kann ich leider nur eine Mission annehmen, trotz Better Contracts

Das ist quatsch! Ich habe keine More Mission Allowed und auch in unserem MP Projekt nicht und wir können diverse Missionen annehmen, auch ohne MoreMissionAllowed!


Neueste Version mit bekannten bus (siehe issues) von hier https://github.com/Courseplay/courseplay/releases
6.4.0.4

**Comment by Cassy-Blair** [comment]
Ja klar ist es Version 6.4.0.0 aber die habe ich im Mai hier im Github runtergeladen, bevor sie überhaupt im ModHub war. Den Link hatte ich damals von [HIP] Williwillswissen

Ich hab den Fehler gefunden, anscheinend gibt es einen Konflikt zwischen CP und dem Cover Addon Mod
https://farming-simulator.com/mod.php?lang=de&country=de&mod_id=148738&title=fs2019

Hab nun mittlerweile die neue 6.4.0.4

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/issues/3882

> covers addon ( Infopanel flickers when a course is running with an implement that has a cover. #4976 )

**Comment by Cassy-Blair** [comment]
Mein Download von 6.4.0.0
![grafik](https://user-images.githubusercontent.com/87262647/126767259-0f8779a9-fdf5-43c9-838b-9834cf8ecc81.png)
 
Und Veröffentlichung im Modhub
![grafik](https://user-images.githubusercontent.com/87262647/126767305-3e835369-2ceb-4c50-a679-0bf328c059bc.png)

**Comment by Tensuko** [comment]
Das Spielt überhaupt keine Rolle.
6.4.0.0 egal ob im ModHub oder von der Release Seite bei uns geladen, es ist und bleibt die 6.4.0.0 und ist damit unsere ModHub Version!

**Comment by Cassy-Blair** [comment]
Gibt es eigentlich eine deutsche leicht verständliche Anleitung was diese Debug Einstellungen 1-24 sind?

**Comment by Tensuko** [comment]
Das sind keine Einstellungen, dass sind Channels die gesetzt werden und dann nichts anderes machen als Informationen in die log schreiben:
https://github.com/Courseplay/courseplay/wiki/Debug-Channels

**Comment by Cassy-Blair** [comment]
> 
> 
> Das sind keine Einstellungen, dass sind Channels die gesetzt werden und dann nichts anderes machen als Informationen in die log schreiben:
> https://github.com/Courseplay/courseplay/wiki/Debug-Channels

Ahhh das heißt mein Mod Konflikt hätte ich mit 
**Debug channel 4 = Mode4 - fertilizing and seeding + Debug channel 18 = HUD action**
besser finden können?

**Comment by Tensuko** [comment]
Nicht unbedingt, weil wir ja nicht wissen was das cover addon macht damit es nicht geht.
Das ist try and error.
