### ISSUE TITLE
Cousreplay Won't you tab Via controller or Keyboard and mouse.

### ISSUE THREAD

**Issue by Rockythelover22** [Courseplay/courseplay#7374]
I'm Currently playing the millennial farmer map Ver1.0 From the mod hub after some time made a couple jobs for it do and for reason I can't change vehicles.

Cousreplay Ver: 6.03
Map of issue: Millennial Farms 1.0 
Author of map: Mappers Paradise/The Subbie

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki
