### ISSUE TITLE
Schaufelmodus

### ISSUE THREAD

**Issue by DonBolli** [Courseplay/courseplay#7376]
Hallo

Ich ein Problem mit dem Schaufelmodus, was könnte die ursache sein?
[Video](https://www.youtube.com/watch?v=Wy9QnfrouK4)
[log.txt](https://github.com/Courseplay/courseplay/files/6877488/log.txt)

Er scheint die Silage im Silo nicht zu erkennen.

Ich verwende CP Release 6.4.0.4

**Comment by zinni97** [comment]
@DonBolli Dein Video ist noch auf privat gestellt.

**Comment by Tensuko** [comment]
Doch, er erkennt die Silage, es ist aber immer wieder das gleiche und ich habe das hier auch schon ein paar mal erwähnt:
![silo](https://user-images.githubusercontent.com/27344744/127017522-c2cad49e-4b32-4834-bb27-cbe4765e880c.png)

Die Silage ist am weitesten vorne und ist sein Ziel und wenn er die nicht kriegen kann weil entweder die Arbeitsbreite zu hoch ist, oder die Silage im Boden buggt, oder die Schaufel zu hoch ist für den Beladezustand, bleibt das für immer da liegen.
