### ISSUE TITLE
attempt to call method 'getAttachedImplements' (a nil value) in v6.4.0.5

### ISSUE THREAD

**Issue by onyxsakura** [Courseplay/courseplay#7377]
Error: Running LUA method 'update'.
2021-07-27 01:11 D:/home/sid_2850991/farmingSim_2019/profile/mods/FS19_Courseplay/toolManager.lua:224: attempt to call method 'getAttachedImplements' (a nil value)

We got this error on our server a couple of times in v6.4.0.5 it causes the server to lock up and prevent players from syncing after saving the game. I can't post the full server log since it is rented and I don't have access to the log file.
However I listed all of the mods we use in [this pastebin](https://pastebin.com/MVpsEUYB).

**Comment by Tensuko** [comment]
1st #7285
2nd even a rent server you can check the logfile.
Reopen if you can reproduce this in SP and post a logfile.
