### ISSUE TITLE
Suggestion: Add option to disable predictive turn speed

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#7379]
Would love to see an option where we could choose to use the predictive speed function. IMO I think it is way too conservative and would rather just go with the speed I recorded the course at or the default course generator speed.

**Comment by Tensuko** [comment]
You know how PR works. :)

**Comment by pops64** [comment]
? Sorry I have been out of the loop are we now making suggestions in the Discussions Tab?
