### ISSUE TITLE
Game freezes on course generation w/ Bypass Islands, No Man's Land, custom field

### ISSUE THREAD

**Issue by Arn241976** [Courseplay/courseplay#7382]
I created a field outline using a Case 7250 Pro and the Lizard Tetra 4 plow, mostly on section 46 but overlapping into section 45.  I then detected the field outline and stored it as Field 4.  I then generated a course to plow the field, but I forgot to set the 'Bypass Islands' feature to avoid the rocks.  The tractor plowed a dozen or so rows until it got stuck on a rock.  I then started over; detected the field edge (overwrote Field 4) and tried to generate a new course using the Bypass Island feature.  The game then acts like it's generating a course, but it freezes.  I waited 4 or 5 minutes before I killed the game via task manager.  I have since tried both Simple and Circle Islands, and creating a new field outline inside the original outline (leaving some un-plowed area around it) (which worked) but still hangs when trying to generate a new course.  I also noticed that when I start the game and CoursePlay scans the fields, it hangs for a few seconds when it scans sections 44-46.  I can, however, generate a new course if I turn off the Bypass Islands feature.
I have used this technique to create new fields several times before with success, although I can't remember if I had to use the Islands feature.

Thanks.

P.S.  I wasn't using the latest CP, but I got the most recent version and the issue still exists.

https://pastebin.com/RYW9REp7

**Comment by Tensuko** [comment]
What do you mean with freeze ?
Screenshot of your Field, Generator Settings and logfile with the Error.

If there is no Error, it is only unpatience...

>  I waited 4 or 5 minutes before I killed the game via task manager.

Depending of the complexity, the working width, etc it can take longer!

**Comment by Arn241976** [comment]
Looks like it was, indeed, unpatience....  After 15 minutes, it did generate a course.

By plowing the outline of the new field first, CP basically treated the interior un-plowed portion as a giant island and avoided it completely.

I also tried just driving the outline of the new field (no plowing) and generated a course using the Bypass Islands feature.  It generated a course quickly, but it made no attempt to avoid the obstacles (rocks).

You can close this thread, conclusion being that CP can't handle obstacle avoidance while creating new fields at this point.

Hope this makes sense, and thanks for your help.

**Comment by Tensuko** [comment]
Avoid Rocks at border is field edge buffer, we have an open Issue for this.
If islands are to smal, we will ignore them too, due to too low radius.
