### ISSUE TITLE
Version Number not appearing well

### ISSUE THREAD

**Issue by yann-mrt** [Courseplay/courseplay#7384]
Good day,
I notice than since V6.4.0.4 (i think) the version number is not appearing well. It is appearing in 2 line and not showing the last digit.
![fsScreen_2021_07_29_11_20_48](https://user-images.githubusercontent.com/74056604/127486210-f26ad7eb-d179-4fd5-8516-306c08ed8bec.png)

Thanks

**Comment by Tensuko** [comment]
Doesn't matter, it is in the logfile wich we need anyway.

**Comment by yann-mrt** [comment]
If you tell me which log you need I can send it.

**Comment by Tensuko** [comment]
I don't need a log to see it, but when you have an Issue I can clearly see in the log wich version exactly you got.
So this display is NOT an Issue at all.
If you want to know it on your own... look in the logfile!
