### ISSUE TITLE
[Feature Request] Reverse when straw discharge is enabled

### ISSUE THREAD

**Issue by MLGPR0GAM3R** [Courseplay/courseplay#7385]
Is it possible to have the harvester reverse at the end of the row and before headland turn (if headland is in turn mode) to prevent a large pile of straw from forming.  This would keep the straw swath more uniform so it can be picked up with a baler or wagon in one pass. If this is already possible I cannot figure out how to do it.

**Comment by Tensuko** [comment]
I add this into a similar Issue... #6643
