### ISSUE TITLE
Mode10:compacter-Mode - CP starts with a new (internal) Silo-Course after pausing for a AD-Driver

### ISSUE THREAD

**Issue by DancerVlt69** [Courseplay/courseplay#7386]
First: I don't know if it is a real issue, sorry if not.

Da mein EN nicht sonderlich gut ist, die detaillierte Beschreibung in DE

Wenn der CP-Verdichter einen AD-Abfahrer stoppt, und nach dem Passieren des AD-Abfahrers wieder los fährt, scheint es so, als würde CP den gerade genutzten ('internen') Silo-Kurs löschen, einen neuen generieren und diesen dann, korrekterweise, von vorne beginnen. 
Im Code des Compacters scheint aber eine Routine für das Fortsetzen vorhanden zu sein.

**Comment by Tensuko** [comment]
Ich hab keine Ahnung was du meinst...
Wir fahren immer einen neuen Kurs ab, Bahn für Bahn.
Wo ist jetzt das Problem ?

**Comment by DancerVlt69** [comment]
OK, dann noch mal die Details im Detail... nein, in Stichpunkten

- CP verdichtet, erkennt AD-Fahrzeug, ob Abfahrer oder vorbeifahrend bleibt sich gleich
- CP stoppt AD, fährt auf Parkposition, lässt AD seinen Job fortsetzen
und jetzt 'mein Problem'
- statt in der Bahn (Spalte),  oder gern auch der Nächsten, das Verdichten fortzusetzen, beginnt CP wieder in/mit der ersten Bahn

Warum? Beabsichtig oder Fehler? Es gibt doch die Variable 'lastDrivenColumn' in der BunkerSiloAIDriver.lua 
Und da fällt mir gleich noch was auf: In der CompactingAIDriver.lua gibst die lokale Variable 'onlyStopFilledDrivers'; scheint nicht zu klappen zumindest bei AD Fahrzeugen. Aber das wäre dann wohl ein neues 'Ticket' falls da nicht schon jemand was zu geschrieben haben sollte,

Falls ich mich jetzt immer noch nicht deutlich genug ausgedrückt haben sollte, hier ein kurzes Video, in dem ich das Thema aufgegriffen habe. Sry für die Eigenwerbung, falls unerwünscht, dann gern löschen. 

[https://youtu.be/fKUmWQi2alY?t=510]

**Comment by schwiti6190** [comment]
@DancerVlt69 Hi, Ist dieses Problem das gleiche wie bei #7422 nur mit nem AD abfahrer?

**Comment by DancerVlt69** [comment]
> @DancerVlt69 Hi, Ist dieses Problem das gleiche wie bei #7422 nur mit nem AD abfahrer?

Jep, ist es. nur dass CP bei 'DonBolli' auf der linken Seite startet. Das liegt aber einzig am Startpunkt der Silofläche. Schön, dass @Tensuko dort versteht worum es geht ;) ;)

**Comment by schwiti6190** [comment]
@DancerVlt69 Okay ich schließ das Issue dann da es das gleiche ist und schau mal was sich machen lässt :)
