### ISSUE TITLE
AI +AI Vehicle Extension

### ISSUE THREAD

**Issue by sesmo** [Courseplay/courseplay#7387]
Hello,

I come back to FS19 after 1 year absent.
I can´t setup mode 2 and mode 3 when I use hired woker or use the mod AI Vehicle Extension.
The tracto doesn´t find the combine on the field.
The reason is I use this mods is because I play on a Map with very huge fields, and the load of the courses at the begining of the game belog  over 15 minutes.

Is there some incompatability? or i´m doing something wrong?

Thank´s on advance.

**Comment by Tensuko** [comment]
Only works with CP https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ

**Comment by Tensuko** [comment]
> The reason is I use this mods is because I play on a Map with very huge fields, and the load of the courses at the begining of the game belog over 15 minutes.

It does not take 15min since our new course save format.
cpUpgradeAllCourses into console and they will be updated.

**Comment by sesmo** [comment]
Ok, thank´s,
I´m in process of upgrading all mods now.RP

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/releases

**Comment by sesmo** [comment]
Thanks. A huge improvement for me. My map is a 4x a only 3 fields...

Now take less than a 2 minutes...

RP
