### ISSUE TITLE
Suggestion: Option to save course as field border

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#7389]
hey,

It would be nice, to have the option, to save a course as a field border.

This is especially helpful, if you have very oddly shaped fields, wich need to be split up, to be able to generate fieldwork courses.

Kind regards,
JDTiger

**Comment by Tensuko** [comment]
Thats nothing new... 
You drive your border course and save it. Load that border course and start the generator with field 'currently loaded course' and generate it.

**Comment by JDTiger** [comment]
yes, thats how it can currently be done...

I'd like to save it like the Calculate current fields edge courses, to be able to easily select them in the course generator.

**Comment by Tensuko** [comment]
Won't implement that.
But you can check how the custom fields are saved and how you course looks like.
I think they are also just coordinates and that might work.
