### ISSUE TITLE
IDEE: CP Übersichtsmenü

### ISSUE THREAD

**Issue by ChrisBS91** [Courseplay/courseplay#7393]
HI 
Fände ein Übersichtsmenü über alle laufenden CP Aktionen ziemlich hilfreich. 
So muss man nicht immer von einem Fahrzeug ins nächste springen um zu gucken wie lange ein Kurs noch braucht, sondern hat das übersichtlich in einem Menü zusammengefasst:
Drescher XY Feld 11 noch 4:56 Min
Fendt ... auf Feld 32 noch 57:21 Min ... 

Das würde ein dauerndes Fahrzeugwechsel sparen und wäre übersichtlicher 

Gruß 
Chris

**Comment by Tensuko** [comment]
Nein, wird zu viel werden.
