### ISSUE TITLE
Empty bunker

### ISSUE THREAD

**Issue by Yboux** [Courseplay/courseplay#7395]
I do not know why but the tractor will only empty the left side of the bunker.
[log.txt](https://github.com/Courseplay/courseplay/files/6923804/log.txt)
![fsScreen_2021_08_03_07_48_19](https://user-images.githubusercontent.com/25300651/128010878-6bad3f02-6402-4013-9e0b-3a86aae4e2a5.png)

**Comment by Tensuko** [comment]
It is always the same reason....
Check your bunker for some smal heaps on that side.
The 1st heap is always our 1st target, if the 1st heap can't be taken, he will try it again and again!

![silo](https://user-images.githubusercontent.com/27344744/127017522-c2cad49e-4b32-4834-bb27-cbe4765e880c.png)

**Comment by Yboux** [comment]
I'm wondering why it tells me the bunker is empty.

**Comment by Tensuko** [comment]
Becouse he reached the end of the Bunker
