### ISSUE TITLE
Using Bredall 165 Crazy spreader

### ISSUE THREAD

**Issue by caracarn3** [Courseplay/courseplay#7397]
I know this is a unique piece but I have a few issues trying to use this mod with Courseplay and wondering if at min someone might know how to fix easily with XML changes or such.

The mod allows the Bredal K165 spreader to go out to 80m in working width so or very large maps tends to be the spreader I use.  CP only allow up to 50m and additionally the implement shows up as 24m so to even get up to 50 I need to manually click repeatedly to get it up to 50m.  I had changed the working width in the XML to no avail.

**Comment by Tensuko** [comment]
Not going to change anything for this. Sry. Use 2 spreader.
