### ISSUE TITLE
Mode 9 always wants to start at opposite side of bunker

### ISSUE THREAD

**Issue by pierrehicks** [Courseplay/courseplay#7402]
I have one of the vanilla bunkers the ones that are open on both ends and I was using mode 9 to successfully automate unloading silage into trailers and then the next time I needed to use it the tractor always want to drive around to the other side of the bunker and start unloading. So I tried creating a new course on the other side and guess what the tractor just want to go back to the other side to start. I dunno if this has been brought up before but i couldn't find anything so any help would be appreciated thanks

**Comment by Bobster82** [comment]
Same as: https://github.com/Courseplay/courseplay/issues/7386

**Comment by Tensuko** [comment]
No, it is not the same!

Logfile ?

**Comment by pierrehicks** [comment]
It seems to be an intermittent problem so I'll post it when it happens again cause smart person that I am didn't save it at the time. Also this problem happens with a one sided bunker as well. The path that it generates wants the tractor to back into the bunker and then try to turn around inside which it cant cause you know space and stuff

**Comment by Bobster82** [comment]
> No, it is not the same!

Whoops, sorry ... read too quick, thought I read the same as the other one. lol

**Comment by pierrehicks** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6950006/log.txt)
Here is the log after it just happened

**Comment by pierrehicks** [comment]
Update: After I manually empty out most of the bunker the course seems to populate correctly to unload the bunker however once that works it will no longer "see" the trailer that wants to be loaded which I understand is a different issue but I dunno if its related somehow cause sometimes the course does work completely with no issues

**Comment by Tensuko** [comment]
Waitpoint to close/to far. Finding the target is all related to the waitpoint.... I guess we have to increase the detection distance...

**Comment by pierrehicks** [comment]
I've seen that the waitpoint is usually the issue with finding the unloading trigger but would the distance of the start point from the bunker affect the detection of the bunker cause through some further trial and error I've noticed that if I move the start point further from the bunker it seems to have less issues but I dunno if that is actually correlated to the start point or just things working correctly. Perhaps the distance of the start point related to where the first pieces of silage in the bunker was the cause of the original issue. The further apart they were the better it seemed to work.

**Comment by Tensuko** [comment]
Start of the course is super simple....
Stay in Front of Bunker, start course, drive in a bit, switch to reverse and the rest is as normal.

**Comment by JDTiger** [comment]
Hey, have the same problem now.

here is the log and a vid of CP going for the wrong end of the silo:
https://youtu.be/Ih8CYcq2cts

[log.txt](https://github.com/Courseplay/courseplay/files/7002625/log.txt)

**Comment by pierrehicks** [comment]
So far the only thing that I’ve found that makes it work somewhat normally is to move the start point further away from the bunker. This fixes it most of the time but occasionally it still tries to go to the other side

**Comment by Tensuko** [comment]
Set the driver to start at 1st waypoint and try again.

**Comment by Tensuko** [comment]
Status ?
Also try 6.4.0.7

**Comment by Tensuko** [comment]
Closed due to inactivity
