### ISSUE TITLE
Vehicle randomly stops

### ISSUE THREAD

**Issue by Hpnotiq1** [Courseplay/courseplay#7403]
For a while now I have had an issue with my vehicle stopping while on route in the middle of the road causing a traffic jam. Sometimes I can get it to go if I go start and stop the course but most of the time I have to drive it myself for a few and then engage the course again. This makes it very irritating to have to babysit all my vehicles and I can't get my farm to be fully auto. If anyone has any suggestions to fix this issue or even if it's known and being worked on. Oh! Just to add in I have tried using other tractors and still the same thing will happen.

**Comment by Tensuko** [comment]
And why I have to keep ask for logfiles ?
https://github.com/Courseplay/courseplay/wiki

**Comment by Hpnotiq1** [comment]
Maybe because I wasn't aware I had to, just to ask a question...
Do I only send it when the issue occurs?

**Comment by Tensuko** [comment]
I need the occouring Error in that log...
You know what ? I don't have that Error so how to know whats happening ?
Thats what the log is for!
