### ISSUE TITLE
CP throws errors while in shop

### ISSUE THREAD

**Issue by WaaaghNL** [Courseplay/courseplay#7413]
When you are in the shop configurating a tractor like the Fendt 1000 you get the following event errors in CP. I'ts happening with every vehicle
`Error: Running LUA method 'packetReceived'.
C:/Users/Ronald/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/courseplay_event.lua:105: attempt to index field 'vehicle' (a nil value)
Error: Running LUA method 'packetReceived'.
C:/Users/Ronald/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/courseplay_event.lua:105: attempt to index field 'vehicle' (a nil value)
Error: Running LUA method 'packetReceived'.
C:/Users/Ronald/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/courseplay_event.lua:105: attempt to index field 'vehicle' (a nil value)
Error: Running LUA method 'packetReceived'.
C:/Users/Ronald/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/courseplay_event.lua:105: attempt to index field 'vehicle' (a nil value)
Error: Running LUA method 'packetReceived'.
C:/Users/Ronald/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/courseplay_event.lua:105: attempt to index field 'vehicle' (a nil value)
Error: Running LUA method 'packetReceived'.
C:/Users/Ronald/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/courseplay_event.lua:105: attempt to index field 'vehicle' (a nil value)
Error: Running LUA method 'packetReceived'.
C:/Users/Ronald/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/courseplay_event.lua:105: attempt to index field 'vehicle' (a nil value)
Error: Running LUA method 'packetReceived'.
C:/Users/Ronald/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/courseplay_event.lua:105: attempt to index field 'vehicle' (a nil value)
Error: Running LUA method 'packetReceived'.
C:/Users/Ronald/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/courseplay_event.lua:105: attempt to index field 'vehicle' (a nil value)`

**Comment by Tensuko** [comment]
complete logfile!!!!

https://github.com/Courseplay/courseplay/wiki

SP or MP ?
