### ISSUE TITLE
Mode 9 problems on Felsbrunn

### ISSUE THREAD

**Issue by Darwin1119** [Courseplay/courseplay#7414]
I'm trying to make a course to unload the bunker at the bga into the fermenter using mode 9 on a wheel loader. I have the course set up exactly as it should be, but it will stop before reaching the waitpoint and show vertical red lines on the mode 9 debug, and if I adjust the waypoints too close in a way that ensures the waitpoint is looking at the trigger, the loader simply drives to the point and reverses right back out without unloading its bucket
[log.txt](https://github.com/Courseplay/courseplay/files/6950537/log.txt)

I've attached the log file in case it is of use.

TIA

**Comment by Tensuko** [comment]
> I have the course set up exactly as it should be

You won't belive how many times I have read that sentence....

Screenshot of your course? All Waypoints on (NOT the dbg eye Icon).

Debugchannel 9 on would have been better for Mode9:
https://github.com/Courseplay/courseplay/wiki/Debug-Channels

**Comment by Darwin1119** [comment]
![image](https://user-images.githubusercontent.com/37225622/128642617-9a316fb6-a730-4140-b9a0-b81886fb6a4d.png)

Here is an image of my course. I followed the exact steps you used when creating the course in your video mentioned in the info thread. I am using debug channels 9 & 10 (as you did in the video)

**Comment by Tensuko** [comment]
Use the ingame Courseeditor and check if the waitpoint looks in the correct direction.
Looks a bit strange to me...

**Comment by Darwin1119** [comment]
I moved them a little further apart to ensure it is pointing towards the trigger, and am still receiving the same issue. I can record a video of this if it would be helpful.

![image](https://user-images.githubusercontent.com/37225622/128669135-8750703d-b52c-411d-8efd-53adf5a2aa89.png)

**Comment by Tensuko** [comment]
Very strange.... but the BGA is yours, isn't it ?
A Video with F5 and channel 9 and 10 active pls.

**Comment by Darwin1119** [comment]
I do own the BGA. Here's a video of the course looping itself a couple of times. Hopefully it is what you need.
https://youtu.be/7kzbnOXlTxk

**Comment by Tensuko** [comment]
Do you have the logfile when you recorded the Video ?
I miss some on screen informations...

Oh and I would try to move the waitpoint closer.
For me it looks a bit far away, it might be that we are just on the edge.
As I said somewhere, we should make the detection longer.

**Comment by Darwin1119** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6956791/log.txt)

Here's the logfile, I will try moving the point momentarily

**Comment by Darwin1119** [comment]
Moving the waitpoint closer so far that the shovel is already inside the trigger does not help, and moving it further away yields me this.

![image](https://user-images.githubusercontent.com/37225622/128765968-f5b7861f-77fa-4bf9-ab40-71543d5f8040.png)

**Comment by polosubtil** [comment]
Try to put your P closer and then keep moving forward a bit, and then put hit reverse.

**Comment by Darwin1119** [comment]
same problem. drives up to the first reverse point, and reverses immediately. almost acting as if the waitpoint doesn't exist. Have you successfully done this in felsbrunn with the updated mode 9?

**Comment by Darwin1119** [comment]
Out of curiosity, I tried making a course to unload the bunker from the opposite end of the bunker, and the issue remains. The driver can. however, unload the second (east) bunker just fine.

**Comment by Tensuko** [comment]
Normaly as we find the Trigger, it should have no Issue unloading...
Since this is Felsbrunn, can you give me all your course files ?
I want to tr that on my own later when I am at home.

**Comment by Darwin1119** [comment]
Heres my course folder for this map. I'm interested to see if you get the same result.

https://mega.nz/folder/VspT3Kgb#KGV3gvmUdr9smCEHgTTq5A

**Comment by Tensuko** [comment]
GitHub does not want my answer to this.... nice

**Comment by Darwin1119** [comment]
Well, finally got to try it after a long day of IRL farming, and it works perfectly now. Good work finding that! Also, very good support, better than some of the support that we get with our autosteer that we pay several thousands for every year at times...
