### ISSUE TITLE
Controls in the game do not work.

### ISSUE THREAD

**Issue by BGiPV** [Courseplay/courseplay#7417]
Controls in the game disappear from time to time. This happens very often in completely random moments of the game.
This doesn't happen without Courseplay.
[log.txt](https://github.com/Courseplay/courseplay/files/6951209/log.txt)

**Comment by Tensuko** [comment]
2021-08-08 20:30 Error: Running LUA method 'update'.
2021-08-08 20:30 dataS/scripts/fieldJobs/FieldManager.lua(564) : attempt to index a nil value

GIANTS script, Issue from the Map, can't do anything on CP side.
