### ISSUE TITLE
Mouse disabled when not in a vehicle

### ISSUE THREAD

**Issue by Bobster82** [Courseplay/courseplay#7419]
Hey CP team,

In my own mod, I use the mouse to select vehicles in the list to jump to. When I'm not in a vehicle, CP sets g_inputBinding:setShowMouseCursor(false) in a update loop. So I can't use the mouse when I'm not in a vehicle.
AD sets the mouse to false only once and so do I... 
Can u guys remove that from the loop and only set the mouse to false once?

![fs19_mouseissue](https://user-images.githubusercontent.com/47780758/128759064-b3dd5a1f-26e8-44f3-bd56-da81d87fe113.jpg)

**Comment by Tensuko** [comment]
Will have a look at that.
Not sure why we do that.
Can you try that out and check if there is any Issue when we not have it in a loop ?

BTW your mod looks interesting, any public release of it ?
Looks like an advanced Version of that one Mod from HappyLooser from ModHoster.

**Comment by Bobster82** [comment]
> Can you try that out and check if there is any Issue when we not have it in a loop ?

Will have a look at it today.
 
> BTW your mod looks interesting, any public release of it ?
> Looks like an advanced Version of that one Mod from HappyLooser from ModHoster.

Thanks. Yes it's based on the looks of that mod. I build my own version of it with some added features like tab order and selecting (switching vehicles) with mouse.
There is no public release of it (yet). I'm still learning lua and need to find out how to make a (orignal fs19) settings menu haha

**Comment by Bobster82** [comment]
> Can you try that out and check if there is any Issue when we not have it in a loop ?

It wasn't in a loop, but it disabled the mouse right after I enabled it ;) 
I made a pull request for a change. I tested it out and found not problems (that didnt already exist).
I hope I did it the right way.

**Comment by Tensuko** [comment]
> and found not problems (that didnt already exist).

All that matters is, that all mouse functions still working.
HUD Control, Click to Switch, swicht into Vehicle with Notifications, Course Editor stuff,...

**Comment by Tensuko** [comment]
Just a quick test...

**Comment by Bobster82** [comment]
> All that matters is, that all mouse functions still working.
> HUD Control, Click to Switch, swicht into Vehicle with Notifications, Course Editor stuff,...

All is working as before, no errors seen
