### ISSUE TITLE
Lose the ability to fill from Silo or other Triggers when need to refill something.

### ISSUE THREAD

**Issue by cwattyeso** [Courseplay/courseplay#7420]
Discovered a very strange behaviour this evening whilst playing FS19 and using Courseplay. I had a Courseplay driver running a Manure/Compost Spreading Course on a Field in the Fertiliser/Spreading/Seeding Mode and also attached a refill course so when driver ran out of manure/compost he would go and refill. This all worked brilliantly and as expected.

However whilst the driver was running the course, I lost the ability to fill anything from my silo or any other silo type objects on the map. I could go to the fill point, hit the button to start filling, the box would appear for me to select what I wanted, when I clicked okay, nothing happened no filling occurred.

As soon as I stopped the courseplay driver, I could fill again fine from my silos and other trigger points. Started the courseplay driver up again to resume his course, and again I could not access my silos and stuff then.

**Comment by Tensuko** [comment]
Dude, you are long eough here to know all this....
where is the logfile ?!

And yes I know this Issue already, as it appears when the driver gives out the message he need to be refueled.

**Comment by VergylTantor** [comment]
I have setup an example of when this issue will occur regardless of fuel status. If planting using a refill course, while the seeder is driving to refill point the silo fill point will be disabled. I have included a saved file to ease of recreation if you choose.

Start seeder. (it should be driving to refill point)
Attempt to load from Silo.

[Refill Save.zip](https://github.com/Courseplay/courseplay/files/6961513/Refill.Save.zip)
[log.txt](https://github.com/Courseplay/courseplay/files/6961517/log.txt)

**Comment by Tensuko** [comment]
So it is general when we try to load something, that is enough to know then.

**Comment by VergylTantor** [comment]
Yes, in my experience, any refill rout will disable any kind of fill trigger.

**Comment by cwattyeso** [comment]
My apologies for not providing a log with the initial post, but within the console as I was playing and experiencing the issue there were no errors being reported. I played for several hours working around the issue, and then ended up spending about four hours last night playing with and trying to work out how to use Modes 9 & 10 in my game. So if I had posted my log it would not have contained any information relevent to the issue, but instead loads of errors and debug stuff related to other mods and functions.

**Comment by Tensuko** [comment]
The most relevant thing you still not mentioned and I could have read all in the logfile is the Version!
ALWAYS give a logfile, no matter what!

It is exhausting to keep ask for this, jsut becouse you don't read any Error for CP in it, doesn't mean it does not contain any useful information.

If you want to discuss with me about post the log or not, rather spend your energy in just drag and drop it here. It takes less then 20 seconds...
