### ISSUE TITLE
[Praktische Verbesserung] Silo verdichten

### ISSUE THREAD

**Issue by DonBolli** [Courseplay/courseplay#7422]
Der Verdichter startet immer auf der linken Seite, nach jedem Abfahrer. Was resultiert draus? Das Silo wird nur links verdichtet. Wenn keinen Abfahrer komme, fährt er schön von links nach rechts seine Bahnen.

Meine Idee wäre es daher, dass er sich die Position der zuletzt verdichteten Bahn merkt und dort weitermacht wo er aufgehört hat. In der Theorie verdichtet er richtig, praktisch ist es leider nicht.

CP 6.4.0.5 Release version

**Comment by JDTiger** [comment]
Ich habe noch zei weitere vorschlaege:

1. Beim erkennen von Abfahrern sollte nicht nur der radius, sondern auch die Flaeche des Silos beruecksichtigt weredn (daraurch kann der radius massiv verkleinert werden, da dieser bei rueckwaerts abkippen nur den bereich der siloeinfahrt abdecken muss, und nicht zusaetzlich das gesamte silo)

2. Einstellen des Silotyps (mit oder ohne rueckwand), Mimentan wird bei silos mit rueckwand nicht das gesamte silo befuellt, sondern vor der rueckwand ca. 5-10m platz gelassen. die ist gut bei durchfahrsilos, bei silos mit rueckwand aber kontraproduktiv.

mit freundlichem Gruss,
JDTiger

**Comment by Tensuko** [comment]
- Silobahn merken -> könnte man schauen ob das machbar ist
- Fläche des Silos -> Radius + Silo Area wäre warscheinlich machbar, mehr ist nicht drin
- Silotyp -> Da werden wir nichts dran machen! Die Silo Area ist nicht immer gleich der Kollision und je nach Fahrzeug und Silo könnte es passieren das man in der Wand steckt, also nein, wird es nicht geben!

**Comment by DancerVlt69** [comment]
Dann mal noch 2 Vorschläge von mir @Tensuko , @schwiti6190 

- statt der Reihenfolge '1-2-3-4-5 -> 1-2-3-4-5 beim Abarbeiten der Silobahnen 1-2-3-4-5 -> 4-3-2-1 -> 2-3-4-5 
 in etwa so - Original-Code mit 'Erweiterung auf obige Äderung der abzuarbeitenden Bahnreihenfolge:

 `function BunkerSiloAIDriver:getBestTarget()
	if columnsUp == nil or columnsUp > 1 then columnsUp = 1 end
	if not self.lastDrivenColumn then 
		self:siloDebug("Starting a new approach at column 1.")
		return {line=1,column=1},1
	else
		if columnsUp == 1 then
			local numColumns = self.bunkerSiloManager:getNumberOfColumns()
			local nextColumn = self.lastDrivenColumn+1
			if nextColumn > numColumns then 
				nextColumn = numColumns - 1
				columnsUp = 0
			end
			self:siloDebug("Starting at column: %d, last column: %d",nextColumn,self.lastDrivenColumn)
			return {line=1,column=nextColumn},1

		elseif columnsUp == 0 then
			local numColumns = self.bunkerSiloManager:getNumberOfColumns()
			local nextColumn = self.lastDrivenColumn-1
			if nextColumn <= 0 then
				nextColumn = 2
				if nextColumn >= numColumns then nextColumn = 1 end
				columnsUp = 1
			end
			self:siloDebug("Starting at column: %d, last column: %d",nextColumn,self.lastDrivenColumn)
			return {line=1,column=nextColumn},1
		end
	end
end`

Hintergrund: bei mehr als 3-4 abzuarbeitenden Silobahnen ist der Winkel, den der Verdichter beim Wechsel aus der letzten zur ersten Bahn, beim Einlenken in die erste Bahn, so ungünstig, dass am rechten (bzw. linken) Rand vom Schild unnötig viel Häckselgut liegen bleibt. Wenn dann noch das Merken der letzten gefahrenen Bahn dazu kommt, sollte der Abkippbereich auch bei breiteren/längeren Silos meist schnell wieder frei für den/die nächsten Abfahrer sein.

So nebenbeo, der Code nutzt die Variable 'lastDrivenColumn' für's ''Merken'' ;)

- prüfen, ob ein AI-Driver kein Ladegut transportier, sondern nur vorbei will, und diesen dann nicht durch CP stoppen lassen wenn CP noch mehr als den Wert des eingestellten Überwachungsradius entfernt ist

**Comment by schwiti6190** [comment]
@JDTiger Top das scheint ne gute lösung zu sein habe versucht das so änlich einzubauen nur das er jetzt alternierend von der mitte links/rechts anfährt :)
Beim nächsten mal ruhig ne Pull request erstellen können alle hilfe gebrauchen die geht :)
Mit Autodrive bräuchte ich ne möglichkeit den füllstand zu erkennen, dass wird schon für CP abfahrer gemacht.

**Comment by DancerVlt69** [comment]
@schwiti6190 
Das CP in der Mitte, oder halt beinahe wenn die Bahnenanzahl gerade ist, wollte ich erst versuchen umzusetzen, wenn ich begriffen habe, wie man nen weiteren Menüpunkt ins HUD einbindet. Aber da ich dann doch zu doof bin, weil eigentlich gar keine Ahnung von Lua, wird das noch warten müssen. Weiteren Menüpunkt dafür, dass man evtl sogar wählen kann, ob der Verdichter von der Mitte oder einer der beiden Seiten anfangen soll. Das aber eher als 'Spielerei' ;)

Füllstand AD: wie gesagt, wirklich Ahnung von Lua und ich.... passt nicht. Aber hat AD nicht auch sowas wie nen spec für den Füllstand? Aber vielleicht ziehe ich mir den AD-Code doch noch mal zu Gemüte. Vllt. bringt's ja was.

Pull Request: falls du da doch eher mich statt JDTiger gemeint haben solltest; aus oben genanntem Grund eher nicht und so tief steck ich auch in der Materie GitHub nicht drin, dass ich darauf hätte kommen können.

**Comment by schwiti6190** [comment]
@DancerVlt69 Mein fehler wollte dich eigentlich verlinken :)
Kein problem das ist nur optimal mit der PR. Falls du mal Lust/ Zeit hast kannste ja mal schauen.
Jeder hat das Potential was bei zu tragen, wo ich angefangen bin habe ich auch nur eine Zeile damals für den MP geändert und hatte auch kaum ne Ahnung :D

**Comment by DancerVlt69** [comment]
> @DancerVlt69 Mein fehler wollte dich eigentlich verlinken :) 
Kein Ding...

> Kein problem das ist nur optimal mit der PR. Falls du mal Lust/ Zeit hast kannste ja mal schauen.
> Jeder hat das Potential was bei zu tragen, wo ich angefangen bin habe ich auch nur eine Zeile damals für den MP geändert und hatte auch kaum ne Ahnung :D
Na ja, ganz und gar unerfahren bin ich ja nun auch nicht... Ist eher metaphorisch gemeint. Sonst hätte ich ja auch nicht die paar Zeilen in den bestehende Code für den fließenden Bahnwechsel einbinden können ;)
Im Großen und Ganzen verstehe ich schon, was in den einzelnen Dateien und Funktionen passiert. Aber was komplett Eigenes schreiben, da fehlt definitiv das Detailwissen @schwiti6190 .

**Comment by Tensuko** [comment]
3 Dinge die man Einstellen muss:
- Verdichter reagiert auf (CP+AD oder Spieler)
- Verdichter schaut nach Abfahrer im Radius von
- Wie wir das Silo befüllt (durchfahren oder rückwärts abkippen)

**Comment by DonBolli** [comment]
Wo finde ich die Einstellung "Verdichter schaut nach Abfahrer im Radius von" ich habe die Einstellung "erkenne Fahrzeug im Umkreis von"
Wenn ich die Einstellung "erkenne Fahrzeug im Umkreis von" hochstelle,so dass er das ganze Silo abdeckt, fährt er zwar nicht in Silo wenn noch ein Abfahrer im Silo ist, jedoch hält er auch dann an wenn ein AD Fahrer auf der Strasse ausserhalb der BGA vorbei fährt. (Auftrag Abholen und Abladen)

**Comment by schwiti6190** [comment]
@DonBolli , @DancerVlt69
Könnt ihr ad mal laufen lassen mit dieser Branch und dem debug channel 10: https://github.com/Courseplay/courseplay/tree/Mode10AutoDrive
Das wäre sehr hilfreich :)
Nur zur Info es gibt ein einstellung im hud: "Silo is being filled by"/ "Silo wird befüllt durch", wo man einstellen kann ob der Verdichter warten muss bis der Abfahrer fertig abgeladen hat(Keil silo: https://www.google.com/search?q=keil+silo&client=firefox-b-d&sxsrf=AOaemvKsHX-8_ccK6SSC6DK2qMRX58jsvA:1634332046798&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjGjeCoqc3zAhWBOewKHTWoDR0Q_AUoAnoECAEQBA&biw=2144&bih=1110&dpr=0.9#imgrc=KlEjGKRDSqDmqM) oder den abfahrer quasi folgen kann, da es ein druchfahr silo ist(https://www.google.com/search?q=durchfahrsilo&tbm=isch&client=firefox-b-d&hl=de&sa=X&ved=2ahUKEwiP_87Qqc3zAhU04bsIHUyZBaQQBXoECAEQLg&biw=2125&bih=1110#imgrc=9FVkSlVoy7sPzM). Die Abfrage ob er stoppen soll ist abhängig vom Silo typ(durchfahr oder keil silo) und ob der abfahrer was geladen hat. Es kann sein das die Autodirve implementation nicht richtig geklappt hat, wäre aber cool wenn ihr das mit der version einmal testen könntet und ein video oder screenshots machen könntet um das Problem genaurer zu berschreiben.
