### ISSUE TITLE
Error loading courseplay on saved and new maps

### ISSUE THREAD

**Issue by Doc-Hobo** [Courseplay/courseplay#7424]
New and saved maps will not load when trying to use the latest modhub version of courseplay.  Here is the full attached log file.
EDIT: I have also tried using the latest version from github and get the same issue. 

[log.txt](https://github.com/Courseplay/courseplay/files/6970916/log.txt)

**Comment by Tensuko** [comment]
Ofc they do work else we would have a lot more Issues!

The Problem is a set setting somewhere on your side, maybe from a modconflict.
Seems to be some specialization.

Beside that, only one map in mods folder!

**Comment by Tensuko** [comment]
Ok schwitit found it.
Should be one or some of your course on that map.
You could get into your courseManager.xml and check for the part

<folders>
</folders>

The folders there change everything to parent ="0" and the same for your course.
It should work again then.

**Comment by Doc-Hobo** [comment]
I looked into those and even attempted to delete some, just to see if it would load.  Looks like it will load on new maps now but still can't get it to load on old maps.  Thank you for the assistance and yes I have more than one map downloaded haha.  I'm going to keep playing around with the mods and see if another is causing an issue.  But at least now I can start a new map with it.

**Comment by ninjayx02** [comment]
had the same issue. was on version 6_6.03.00060, I loaded the latest release and although I could see my routes, the game locked up when trying to start CP.  Loaded the CP versions manually one by one until I got to 6.4.  Tried the game each time, CP worked.  Uploaded to the latest release and this now works.
