### ISSUE TITLE
Do not swerve at overloading/unloading.

### ISSUE THREAD

**Issue by winkey24** [Courseplay/courseplay#7425]
This is not necessarily an issue, but is there anyway to select collision or have a harvestor silo/ blower set up work with a course? The collision detection makes the tractor pull away to far to unload in this situation. 
![FS Issue](https://user-images.githubusercontent.com/20340159/129116522-61ef7511-fe8f-4d31-b906-c03b2469562c.png)

**Comment by Tensuko** [comment]
What do you want to do there ?

**Comment by winkey24** [comment]
The wagon unloads from the blue circle into the green circle. Right now CP will not get close enough for the unload function to trigger. 
![129116522-61ef7511-fe8f-4d31-b906-c03b2469562c](https://user-images.githubusercontent.com/20340159/129175073-c46eed87-2f83-474a-9bfa-0a3b5171f5ce.png)

**Comment by Tensuko** [comment]
Ok got it.
Well thats a general Issue that we have at some situations.
It should work if you drive to it in reverse, or make the trigger of the green tool bigger.

We will think about a general solution for this.

**Comment by erksartori** [comment]
Estou com esse mesmo problema, quando se trata de cana de açucar, pois para descarregar na carreta, tem que estar proximo e ele se afasta e acaba nao descarregando . Não gravei o caso, pois aqui demonstra perfeitamente.
[log.txt](https://github.com/Courseplay/courseplay/files/6983801/log.txt)

**Comment by rohne83** [comment]
Similar situation also with other modes. I.e. with refill courses for mode 4 if they shall refill at a manually driven field supplier, they swerve a bit out of their course because they think they are too near to the other vehicle.
