### ISSUE TITLE
Kein Update auf 6.4.0.6 möglich

### ISSUE THREAD

**Issue by Micha4874** [Courseplay/courseplay#7426]
Hallo,
ich wollte mir die neueste Version von CP, 6.4.0.6, aufspielen. Jedoch sobald ich sie installiert habe funktioniert mein Savegame nicht mehr.

Benutze Autodrive Vers 1.1.1.4
 Log:
[log.txt](https://github.com/Courseplay/courseplay/files/6978861/log.txt)

Habe alle Versionen nach 6.4.0.0 Versucht aber nur mit der 6.4. funktioniert auch mein Savegame.

VG Micha

**Comment by Tensuko** [comment]
FS19_lsfmStationaryBalerPack
Der muss raus:
2021-08-13 00:20 Error: Running LUA method 'loadSharedI3DFileFinished'.
2021-08-13 00:20 dataS/scripts/vehicles/specializations/WorkArea.lua(356) : attempt to index field 'workAreas' (a nil value)

**Comment by Tensuko** [comment]
#7324
