### ISSUE TITLE
Question: Map does not start with CP - Map startet mit CP nicht

### ISSUE THREAD

**Issue by haamic** [Courseplay/courseplay#7427]
Hello,
some users, me too, have problems with the map " Mountain Hill 2021".
There are except AD and GC, no other mods / maps in the mod folder. As soon as I want to start the map with CP, it does not load.
One of the last log entries reads:
**Error: Running LUA method 'loadSharedI3DFileFinished'.**
see log

[Mountain Hill 2021-log.txt](https://github.com/Courseplay/courseplay/files/6979897/Mountain.Hill.2021-log.txt)

Without CP the map starts normally, what could be the reason?
Greetings Micha
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Hallo,
einige User, ich auch, haben Probleme mit der Map " Mountain Hill 2021".
Es sind ausser AD und GC, keine anderen Mods / Maps im Mod-Ordner. Sobald ich die Karte mit CP starten möchte, lädt sie nicht mehr.
Einer der letzten log-Einträge lautet:
**Error: Running LUA method 'loadSharedI3DFileFinished'.**
siehe log

[Mountain Hill 2021-log.txt](https://github.com/Courseplay/courseplay/files/6979896/Mountain.Hill.2021-log.txt)

Ohne CP startet die Karte ganz normal, woran könnte das liegen?
Gruss Micha

**Comment by Tensuko** [comment]
Der komplette Error ist:
2021-08-13 06:02 Error: Running LUA method 'loadSharedI3DFileFinished'.
2021-08-13 06:02 dataS/scripts/vehicles/specializations/WorkArea.lua(356) : attempt to index field 'workAreas' (a nil value)

Aber ich kann dir nicht sagen, welches deiner Geräte/Fahrzeuge jetzt ein Problem mit workAreas hat... Wir müssen da mal schauen ob wir generell was machen können...

**Comment by Tensuko** [comment]
#7324

**Comment by haamic** [comment]
> Der komplette Error ist:
> 2021-08-13 06:02 Error: Running LUA method 'loadSharedI3DFileFinished'.
> 2021-08-13 06:02 dataS/scripts/vehicles/specializations/WorkArea.lua(356) : attempt to index field 'workAreas' (a nil value)
> 
> Aber ich kann dir nicht sagen, welches deiner Geräte/Fahrzeuge jetzt ein Problem mit workAreas hat... Wir müssen da mal schauen ob wir generell was machen können...

ich habe keine Fahrzeuge, es sind nur die Standartfahrzeuge, bzw, die auf der Karte enthaltenen.

**Comment by Tensuko** [comment]
> bzw, die auf der Karte enthaltenen.

Da wird warscheinlich eins bei sein, was das Problem verursacht.
Wie gesagt wir müssen mal schauen woher das kommt... jetzt auf die Schnelle kann ich dir da aber leider nicht helfen, sry.

**Comment by haamic** [comment]
lt. Mapersteller soll es mit der V 6.0.0.0 gehen, werd es mal testen bei gelegenheit

**Comment by GE-Mapping** [comment]
Der Mod, der das Problem auf meiner Map (MountainHill2021) verursacht ist eine stationäre Ballenpresse SRBW 4K vom LSFM Team.
Die Version 6.4.0.0 läuft und es kommt dieser Fehler nicht. Ab Version 6.4.0.1 verursacht dieser Mod den Fehler
