### ISSUE TITLE
Pathfinding attempts to back up multi trailer on narrow angle waypoints

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/courseplay#7431]
![20210814223324_1](https://user-images.githubusercontent.com/5993529/129466223-c557ac28-f1ce-4580-ab73-3b40765f69f7.jpg)
this has cropped up in the past, but i think it was mostly fixed for regular lanes. in this case, it's doing it on the headland because of the angle created by the field, and the unusual waypoint geometry at that corner.  I am using a double implement route.  two of the big bourgalt seeders pulled by big bud 747's.

**Comment by Commissar0617** [comment]
also... debug is greyed out

**Comment by Tensuko** [comment]
No logfile, you use the modhub version and for this tool dont use sharp corners and turn on field off.

**Comment by Commissar0617** [comment]
> 
> 
> No logfile, you use the modhub version and for this tool dont use sharp corners and turn on field off.

this is the course generated by the "smooth corners" option.
