### ISSUE TITLE
Bale Stacker turns into stack

### ISSUE THREAD

**Issue by Matt-14** [Courseplay/courseplay#7433]
Hello, I am having a problem with the bale stacker. It does it normally at first (reverses, dumps, and then goes forwards) but after it drops 4-5 stacks the tractor starts to make a 360 turn for whatever reason rather than just going straight, if it was to drop another stack it seems that the tractor turns right into the stack causing a big mess. (My course is perfectly straight because I used GPS). I don't know if I set up the course incorrectly, I set it up the exact same way as before the bale collector mode. I am on version 6.4.06. Here are a couple pictures and my log (sorry for how messy it is). Let me know if you want any debugs on. Thanks for continuing to improve one of the best mods.
![Screenshot (22)](https://user-images.githubusercontent.com/56211682/129497910-aeac9725-e0c1-4e62-88b6-bded412cab32.png)
![Screenshot (23)](https://user-images.githubusercontent.com/56211682/129497911-17885881-ba26-4919-a638-3d007c95cffc.png)

[log.txt](https://github.com/Courseplay/courseplay/files/6989155/log.txt)

**Comment by Tensuko** [comment]
Use the Editor and move the forward waypoint far away from the steck.
Try it out.

**Comment by Matt-14** [comment]
Okay will try that. Unfortunately I might not be able to play for a couple of days but will let you know as soon as I try it. And to clarify, is the forward waypoint the waypoint that is put down when you select the start forward driving when creating the course? And when you say move it far away do you mean to move it to around where the start reverse driving point is? Sorry for the long comment but one last thing, not sure if you would want me to start a new issue but I notice when the square baler gets to 95% it slows down to 3mph till it passes 100%. I haven’t tried using another baler or an in-game one but here is a link to the one I used. https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=157617&title=fs2019
(Again sorry for the long comment)

**Comment by Matt-14** [comment]
So, I tried moving a couple points that I thought you might have meant but nothing is working. It either still went and made a 360, or when I moved a different point it just rammed into the stack without dropping the bales, so if you could somehow clarify to me the point I have to move that would help. I also tested the baler issue and even the in game Kuhn square baler slows down when it reaches 100%. Sorry I wouldn’t have opened this issue had I known it would take me a week till I could play.

**Comment by Tensuko** [comment]
Might be a distance Issue here
Will have to take a look.

**Comment by Matt-14** [comment]
Well, I figured it out. It was my own error… when recording the course I put the forward driving direction waypoint and then the dump waypoint. I figured why not try it the other way, so I put the dump point and then the forward driving direction waypoint and it works perfectly. I am still curious about the baler “issue” that I mentioned before, will that be fixed or because it isn’t that big of a deal you guys will just leave it. Once again, thanks for all the hard work improving one of the best mods in farm sim

**Comment by Kartracer390** [comment]
Hallo,
habe das gleiche Problem Courseplay schlägt nach dem abladen des ca. 7. Haufens voll ein, so dass der Helfer in die Ballen fährt.
Habe den Kurs nach Anleitung dieses Videos eingefahren [ https://www.youtube.com/watch?v=98TIUAgazZg&t=82s](url)
Hier noch ein Video von meinem Problem:[https://www.youtube.com/watch?v=qad3YlvWCm0](url)

**Comment by Tensuko** [comment]
@Matt-14 
The slow down will stay like that. We try to use as much GIANTS Code as possible.
Could tweak it I think but we don't want right now, as long as all balers works like they should.

@Kartracer390 
Hast du auch die Reihnfolge eingehalten, erst den Abladepunkt zu setzen und dann erst auf Vorwärts zu schalten ?

**Comment by Kartracer390** [comment]
Hallo ja nach der rückwärts Fahrt bleibe ich am Ende stehen setze den Abladepunkt anschließend schalte ich auf Vorwärts und fahre wieder los

**Comment by Tensuko** [comment]
Hm, weis nicht ob wir nach 7 Stacks die maximale Reichweite schon erreicht haben. Muss ich mal gucken... Irgendwo hatten wir schon mal so ein Issue.

**Comment by Evilbolzen** [comment]
Moinsen, habe das exakt gleiche wie Kartracer390 bei mir festgestellt, sobald 7 Quaderballenstapel stehen fährt der CP Fahrer in einer Kurve in den Stapel rein (bzw in meinem Falle verhindert eine Wand in der Nähe schlimmeres)
![20210905140651_1](https://user-images.githubusercontent.com/57069516/132126177-7cbc9f83-bfb9-4a4f-945c-78c174f505d6.jpg)
 
Debugchannel zeigt bei mir das gleiche wie bei ihm, einziger Unterschied ich hab den Kverneland Ballensammler und der Kurs führt vom Feld runter, ansonsten genau das gleiche Fehlerbild. Wird die maximale Reichweite durch die rote Linie gekennzeichnet im Bild?

**Comment by Kartracer390** [comment]
wäre schon super für mich wenn der abfahrer nach 7 Stapeln einfach stoppen würde.
Dann könnte man einen neuen Abladekurs zuweisen, ohne dass die Stapel umgefahren werden

**Comment by Tensuko** [comment]
Könnte man mal drüber nachdenken.
