### ISSUE TITLE
Mode9 wheelloader drives into wall

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#7440]
Hey,

i have the problem, that my loader in mode 9 detects the unload point, but before reaching it, goes into a circle and crashes into the handrail of the bunker ramp.

Vid of the incidient with debug 9&10 as well as the F5 view:
https://youtu.be/VGDllNpRYAI

I am running version 6.0.4.6

Kind regards,
JDTiger

**Comment by Tensuko** [comment]
To far away I would say, no Idea what he detected there.

**Comment by JDTiger** [comment]
maybe, though it might as well be the steering of the loader in combination with the tight pass...

i did not change anything in the course (though i restartet the loader and the game a few times) and suddently it started working.
