### ISSUE TITLE
Fahrer einstellen

### ISSUE THREAD

**Issue by DonBolli** [Courseplay/courseplay#7441]
Ich habe die CP version 6.4.0.6 installiert, soweit so gut, jetzt kann ich aber bei gewissen Kursen keinen Helfer einstellen, die Ursache dafür konnte ich nicht ausmachen.

[Video](https://youtu.be/YABI9ztq4rc)
[log.txt](https://github.com/Courseplay/courseplay/files/7006868/log.txt)

**Comment by Tensuko** [comment]
Hast du den Branch runtergeladen, oder Relase von hier ?
https://github.com/Courseplay/courseplay/releases

**Comment by DonBolli** [comment]
Release. Ich verwende nie den Branch

**Comment by Tensuko** [comment]
Wundert mich, weil im Branch war ein Commit drin, der sowas verursacht, ist aber nicht im Release drin.

**Comment by DonBolli** [comment]
Ich habe rausgefunden, wenn ich ein AD Helfer einstelle und gleich wieder entlasse, kann ich danach einen CP Helfer einstellen.

**Comment by Tensuko** [comment]
Dann geht wieder alles ganz normal ?
Oder wie ist das ?

**Comment by DonBolli** [comment]
Soweit ich das beurteilen kann ist dann wieder alles so wie es sein sollte

**Comment by Tensuko** [comment]
Könnte sein, dass sich eine Einstellung verschluck hat, wenn noch wieder was ist, bitte dieses Issue hier wieder aufmachen...

**Comment by DonBolli** [comment]
@Tensuko ; Jedes mal wenn ich das Spiel neu starte habe ich dieses Problem wieder, immer andere Fahrzeuge und andere Kurse. 
AD an und aus funktioniert jedoch immer.
