### ISSUE TITLE
Course Generation causes Game Freeze

### ISSUE THREAD

**Issue by mayvis1990** [Courseplay/courseplay#7443]
Title describes the issue.  Have to use Task Manager to End Task.  I am trying to generate combine paths across a field with islands.  It will generate a path if "island bypass" is off.  If it is set to Simple or Circle FS19 goes not responding.  Have tried on multiple fields in the map. 

Map: Australia 16x
Combine: Ideal 10T Mod
Header: Midwest Durus 60ft

Please let me know if more info is needed.

**Comment by Tensuko** [comment]
User Problem -> unpatient.

**Comment by mayvis1990** [comment]
> User Problem -> unpatient.

I have let the game sit for 30 minutes calculating, I doubt it is impatience.  The longest it has taken in the past is about 15 seconds.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki
