### ISSUE TITLE
only 9 Guides

### ISSUE THREAD

**Issue by landtools** [Courseplay/courseplay#7444]
How come it is no longer possible to take advantage of all the active paths and only 9 ?? practically, I can not turn no more than 9 tractors / combine harvesters ??

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by landtools** [comment]
https://gist.github.com/landtools/b2da7a39abe494fe75dcb5c7116c26f2

My log
