### ISSUE TITLE
Abfahrer wir rausgeschmissen sobald er BGA Silo Trigger erreicht 

### ISSUE THREAD

**Issue by steven1134** [Courseplay/courseplay#7446]
hallo hab ein problem unzwar möchte ich das der CP abfahrer in meinem BGA Silo in einer U Form ablädt und das gleichmäzig so das der CP schieber keinen fetten haufen weg schieben muss sondern eine gleichmäßige spur liegen hat die er wegschieben kann nun habe ich aber das problem das er cp sobald er denn Trigger ereicht cp rausgeworfen wird
![fsScreen_2021_08_20_13_29_11](https://user-images.githubusercontent.com/62439666/130227720-9cf1c3f1-0222-4f68-8ae6-29da2f0984eb.png)
![fsScreen_2021_08_20_13_29_13](https://user-images.githubusercontent.com/62439666/130227733-985510f4-3787-4956-9c55-81239b9168a8.png)
[log.txt](https://github.com/Courseplay/courseplay/files/7021245/log.txt)
kann man da irgenwas machen das er denn abfahrer nicht rauswirft ?

**Comment by Tensuko** [comment]
Das funktioniert so nicht, durchfahren lassen mit einem Kurs oder rückwärts hinten ablegen lassen.
blau oder rot, eines von beiden, wobei rot ein hier abladen Punkt braucht.
![unloadsilo](https://user-images.githubusercontent.com/27344744/130255160-4491ae29-8acb-4ac2-8d21-b8d287019aa6.png)
