### ISSUE TITLE
CoursePlay e Carreiras(Jogos Salvos)

### ISSUE THREAD

**Issue by erksartori** [Courseplay/courseplay#7451]
Boa, não sei se alguém já viu isso, ou não, mas estou aqui para passar um problema que tive, estou com duas carreiras de um mesmo mapa, onde um utilizo para jogar e outro pra fazer Lives no Youtube.
Bom quando eu criei uma nova carreira de um para  exemplo, Lapacho, eu já tinha em outra carreira já com as minhas configurações, e acabei apagando tudo, quando eu entrei na minha carreira antiga, ele apagou tudo. 

Seria possível, fazer a gravação do CP por carreira e não pelo nome do mapa. E se você for apagar aquela carreira poderia perguntar se gostaria de apagar a as Configurações do CP também, pois naquela carreira eu poderia utilizar o mesmo mapa ou não.  Excluído por alguma falha do mapa ou realmente estou trocando de mapa. 

Exemplo: "Jogo Salvo 1" estou com o mapa LAPACHO, "Jogo Salvo 2" estou com o mapa "MATOPIBA" e ai eu vejo que vou fazer uma Live no youtube sobre o mapa "Matopiba" e nao quero utilizar o que eu tenho no "Jogo Salvo 2", pois eu já estou com ele em utilização, entao quero iniciar um novo desde o zero, entao eu abro o "Jogo Salvo 3" e começo do zero, porem ele ja tras toda a configuração do CP da outra carreira, e eu nao quero, como eu disse vou começar do zero, porem se eu apagar ele apaga do "2", que é o que eu jogo offline.  

Acho que consegui explicar.

Abraços
[log.txt](https://github.com/Courseplay/courseplay/files/7025740/log.txt)

**Comment by erksartori** [comment]
Vim colocar imagens:

Carreira 2 - Mapa Lapacho, jogo offline:
![Carreira 1](https://user-images.githubusercontent.com/8292001/130327207-a7a3682f-035f-43e8-a8c1-af23c16182c8.png)
![Carreira 1a](https://user-images.githubusercontent.com/8292001/130327208-952fd82e-d39d-4766-829d-9946445672be.png)

Carreira 12 - Mapa Lapacho, Jogo online:
![Carreira 12](https://user-images.githubusercontent.com/8292001/130327229-88628457-5fad-4ef8-8f97-abcf31f803f3.png)
![Carreira 12a](https://user-images.githubusercontent.com/8292001/130327231-ad2bbaa5-a2dc-4526-83fd-c665283e79b2.png)

**Comment by tn4799** [comment]
Can you please rewrite the text in english so that we can understand what your problem is and then help you.

**Comment by erksartori** [comment]
I'm going to be short here. I have a map saved in career 2, to play offline. I opened the same map in career 12, to start a live from scratch. The courseplay it goes by the name of the map, so it takes all the settings to another save, and the right would not lead. so we can use it from scratch. depending on the images.

**Comment by tn4799** [comment]
So if I understand it correctly, you don't want to have your old courses and so on in a new savegame available?
If thats the case, a workaround would be that you just move the location of the folder with the courses to another location. The folder with all the courses is located in `Documents/My Games/FarmingSimulator19/CoursePlay_Courses`. There its the folder that is named after the map.

**Comment by erksartori** [comment]
I'm sorry, but you don't understand. as per the image I play save 2 offline, and there are my settings made for me to play. I opened a new save and la I'll make new settings, but as it is the same map, it tras all the settings of save 2, and if I delete something it deletes it too and I do not want it, I want it to be a courseplay for each save. and the way this is one for each map.

Is there any way to do that?

**Comment by Tensuko** [comment]
Course is always saved per map.
Settings are saved per Savegame in the folder as courseplaySettings.xml

What is the problem now ?!
