### ISSUE TITLE
Spiel friert bei Benutzung eines Ladewagen Kurses ein

### ISSUE THREAD

**Issue by Fruchtzwerg-De** [Courseplay/courseplay#7452]
Genutzte Version: v6.4.0.6
Karte: Project NDS
Verwendete Mods:
https://gist.github.com/Fruchtzwerg-De/7f74d38c7cc962f881b872c66e935311#file-gistfile1-txt

Meine Log-Datei konnte ich in beide Tools, die auf der Coursplay Seite verlinkt waren nicht hochladen.
Log:
https://workupload.com/file/w5dfz8vgM6L

Verwendete Geräte:
Case IH 380 CVX 
Schuitemaker Rapide 8400W
SUER SM 2400 
Alle Geräte unverändert aus dem Spiel.

Gebäude:
Heutrocknung aus dem FED-Pack.

Hallo, ich habe 2 Kurse miteinander verbunden. 1 Kurs der vom Big M 450 aus dem Spiel. 2 Kurs von der Mitte des Feldes aus zur Heutrocknung und wieder zurück. mit dem Case und dem Ladewagen. Wenn ich den Abfahrer einstelle, fährt er ganz normal los und macht seine Arbeit. Irgendwann friert das Spiel ein und ich muss es im Taskmanager, den LS schließen. Bei allen anderen Kursen passiert nichts, bis auf den einen Kurs. Bei den ersten 3 malen habe ich noch die Meldung bekommen, dass der eingestellte Courseplay Helfer die Arbeit aus unerklärlichen Gründen beendet hat. Während der Meldung ist das Spiel dann eingefroren. Bei den letzten 5 malen, kam die Meldung nicht mehr. 

Ich bitte um Hilfestellung,

MFG

Fruchtzwerg-De

**Comment by Tensuko** [comment]
Ich kann hier nur einen Modconflict vermuten.
Der Callstack führt nicht zurück auf CP.
Der LUA Error ja, aber das hat mit der Helferzahl zu tun, das sollte in der nächste Version gefixt sein.

**Comment by Fruchtzwerg-De** [comment]
Dankeschön. Kann ich CP mit GPS verwenden? Habe meine Mods schon deutlich Reduziert.

**Comment by Tensuko** [comment]
Was heist CP mit GPS verwenden.
Das eine hat mit dem anderen ja nichts zu tun.

Das GPS von Wobster macht keine Probleme.

**Comment by Fruchtzwerg-De** [comment]
Das meinte ich. Danke hat sich alles geklärt.

**Comment by Tensuko** [comment]
Das heist es funktioniert nun und ich kann das hier zu machen ?

**Comment by Fruchtzwerg-De** [comment]
Ja. Vielen Dank.
