### ISSUE TITLE
(unassigned): Check if there's a combine to unload, assigned combines: X9

### ISSUE THREAD

**Issue by MoslessNeo** [Courseplay/courseplay#7460]
**CoursePlay 6.4.0.6**

I'm having problems recently with "overloader" mode.
After the tractor makes the unloading route on the truck or mother bins, it is stopped at point "P" and does not leave. I made several adjustments and nothing seems to solve.

Mods:
FS19_JohnDeereX9_us
FS19_Coolamon_Chaser_Bins_60T
FS19_Coolamon_Mother_Bins_200T
FS19_AutoDrive

What I saw in the log is this:
_2021-08-26 23:49 :54 [info lp15600] 9620 RX (#4): No path found to X9 1100 (#2) in 0 ms, pathfinder failed at least twice, trying a path through crop and relaxing pathfinder field constraint..._

It appears that the tractor is losing its association with the combine
_2021-08-27 10:16 :09 [dbg3 lp680300] 9620 RX (#5): 60T Chaser Bin: Fill levels: SUNFLOWER: 55827.8/70000.0
2021-08-27 10:16 :09 [dbg3 lp680300] 9620 RX (#5): (unassigned): Check if there's a combine to unload, assigned combines: X9 1100 (#3),_

I am testing with the original vehicle FS19_elmersMFG_cutterTrailer

**Log file with debug channels 3 - Overloader**
[Log](https://gist.github.com/MoslessNeo/17bf23125b1239baa5665742c5bb39e7)

[Screenshot](https://1drv.ms/u/s!AteKuv2uUj5JgZDXTDIGbure5woCIzg?e=SoDfMO)

**Comment by Tensuko** [comment]
Yea its okay.
But I can't see what he is not driving.
Can you make a screenshot when he stays at the waitpoint with the course shown?
Did he overload then or not even that ?

**Comment by MoslessNeo** [comment]
The tractor unloads all the content and is stopped at point "P": 
See the highlighted points in the image [Screenshot](https://1drv.ms/u/s!AteKuv2uUj5JgZDXTDIGbure5woCIzg?e=SoDfMO)

If I get into the vehicle, stop and start the route, it immediately finds the combine and goes to it. Fills entire auger wagon, returns to unloading point, stops at point "P", unloads and stops again.

I've tested it with several other original auger wagons in the game and the only one that works is the Elmers Mfg Haul Master model.

Only with the Elmers Mfg Haul Master model this does not happen. The combines harvest for nearly 30 hours without interruption.

**Comment by MoslessNeo** [comment]
Maybe it is.
I tested it with DEMCO from Custom Modding and the same thing happened.
I thought they all used the same game engine.

**Comment by Tensuko** [comment]
CustomModding does a lot of changes wich in my eyes are not rly needed to bring out a coold mod.
But well when they don't stick to GIANTS Standart, we can't do much...
