### ISSUE TITLE
Problem mit Cp V 6.1.6

### ISSUE THREAD

**Issue by RudiBergfeld** [Courseplay/courseplay#7461]
immer wenn ich mehre  Abfahrer Starte trit dieses problem ich kann dann keinen weiteren abfahrer mehr starten. Siehe Log 
![Test](https://user-images.githubusercontent.com/10323527/131228323-f22f3b55-6bf0-445f-95bc-d8ee546340b7.png)

[log.txt](https://github.com/Courseplay/courseplay/files/7071310/log.txt)

**Comment by Tensuko** [comment]
Es gibt keine 6.1.6
6.4.0.6 -> https://github.com/Courseplay/courseplay/releases

Und das Problem mit mehreren Helfern wird noch gelöst. Sollte mit der nächsten Version drin sein.
