### ISSUE TITLE
wheelloader wont tip in the sell buker at bga 

### ISSUE THREAD

**Issue by devilboy123** [Courseplay/courseplay#7464]
hi i just post an essues and it been closed the problem i have i set up a course to emtpy the silage bunker it gose a fill up at the silage bunker drive round to sell and it dont tip it just going up to the p and just drive back with a full buck rake the couse i done is start and the front of the bunker start course then drive a little put a P then drive to the back of the bunker put another P  then back out the bunker then drive round to the sell bunker then put another P then going bk to the start to end the couse 
![fsScreen_2021_08_29_11_21_49](https://user-images.githubusercontent.com/13384366/131248265-52512daa-57d4-409d-9aa5-fdb5c9cabf0c.png)

**Comment by Tensuko** [comment]
I did write to you why I closed it and I will close this one too.
Guess what I found on the search: #7414
