### ISSUE TITLE
Grain Cart

### ISSUE THREAD

**Issue by Gerrit8691** [Courseplay/courseplay#7465]
When operating the combine myself the grain cart doesn't come when I call it. The grain cart is set up correctly and the correct combine is selected for the field I'm working. As soon as I put the combine back in courseplay drive the grain cart will come. Why is this so and how can I fix it.

**Comment by Tensuko** [comment]
Good Morning...
https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ
