### ISSUE TITLE
combine wonky headland turn.

### ISSUE THREAD

**Issue by Phalanx380** [Courseplay/courseplay#7466]
combine not turning properly on headland. i dont know how to put this in to words so here's a video of it in action https://1drv.ms/u/s!AhZRfbB8Fe4bgs9PGjj_vEZLwOZ79w?e=51rtsE
![Screenshot_329](https://user-images.githubusercontent.com/39988550/131348016-c1f720ce-8f75-4431-b543-889bda063cf9.png)

**Comment by Tensuko** [comment]
turn radius, maybe a weird mod combine, or try turn on use pathfinding in turns.
btw that is not headland turn, that is normal 180° turn.
