### ISSUE TITLE
courses deleting after loading save

### ISSUE THREAD

**Issue by jungleman153** [Courseplay/courseplay#7472]
all of my saeved courses delete after loaded save in i havent added or removed any mods and nothing is showing in log as far as i can tell

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

Course are saved per map.

**Comment by jungleman153** [comment]
Error: Invalid mod name 'courseplay-master'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit THIS IS THE ERROR I GOT

**Comment by Siwuees** [comment]
Error: Invalid mod name 'courseplay-master'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit 

Says everything or not?

**Comment by Tensuko** [comment]
Delete CP from your Mods Folder and ONLY download the relase and put it into your mods folder...
https://github.com/Courseplay/courseplay/releases
