### ISSUE TITLE
Vehicle convoy mode in weird order

### ISSUE THREAD

**Issue by Serfalon** [Courseplay/courseplay#7474]
Everytime i set up a course with more than 2 Vehicles and turn on Vehicle convoy mode, the vehicles will go into a Weird order.

Example: 6 combines on the same course. Instead of (from left to right): First Vehicle, Second Vehicle, Third vehicle, etc.

It will go something like: Third Vehicle, Fifth Vehicle, Second Vehicle, etc.

See examples
![whatiwant](https://user-images.githubusercontent.com/54803418/132583127-cf3de181-6bba-4f3e-8e7f-55e001a826cf.jpg)
![whatitdoes](https://user-images.githubusercontent.com/54803418/132583140-069e6865-a405-42b1-ac70-3ddc527671c5.jpg)

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Misamangame** [comment]
@Serfalon  do you have Convoy mode on when you starting the vehicles? Are you starting vehicles in desired order? I'm using 6 combines all the time without any problems. Convoy itself will not choose which vehicle is first or should be second, last etc...

**Comment by Tensuko** [comment]
Closed due to inactivity.
