### ISSUE TITLE
Course generating very odd shaped fields; doesnt work

### ISSUE THREAD

**Issue by Nad42** [Courseplay/courseplay#7478]
Hi as you see in the image I have some very odd shaped fields on the map I'm using... I think there is some overhaul in generation logic required to compensate for these... it would be great to be also able to have the "auto" start direction to automatically adjust for each part of an odd shaped field...
![image](https://user-images.githubusercontent.com/42980546/132999600-1e41c674-8333-452f-9b96-d716a10e2b64.png)

**Comment by Tensuko** [comment]
Try one less headland, but for real, what do you expect here ?
This is a 'field' with super narrow connections...

**Comment by pvaiko** [comment]
That's a tough one with those narrow parts, would be a lot of effort to implement with low benefit, but as always, pull requests are very welcome!

**Comment by Nad42** [comment]
> That's a tough one with those narrow parts, would be a lot of effort to implement with low benefit, but as always, pull requests are very welcome!

Ah man I would absolutely love to be able to help fixing this but I wouldnt have a clue where to start. I enjoy coding but diving into this kind of complicated stuff would need some serious training!! 😅 Ah well I thought it would be interesting for people to see the issue, I have a lot of fields like this so I have to manually edit the path into a logical pattern every time...

**Comment by Nad42** [comment]
> Try one less headland, but for real, what do you expect here ?
> This is a 'field' with super narrow connections...

Well as I real life I would expect to just do it in sections, and bypass headlands where the field is too narrow, I tried with single pass headlands but without fail everything; mower, baler, wrapper all get stuck in trees, on rocks, fences etc around the edge when they do any kind of manoeuvre.
