### ISSUE TITLE
wont let me hire workers after i have been in game for a bit

### ISSUE THREAD

**Issue by spitfire12** [Courseplay/courseplay#7481]
### Discussed in https://github.com/Courseplay/courseplay/discussions/7480

<div type='discussions-op-text'>

<sup>Originally posted by **spitfire12** September 12, 2021</sup>
I just downloaded the latest version and now i can only get 8 workers is this something new?</div>

**Comment by spitfire12** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/7150463/log.txt)

**Comment by Tensuko** [comment]
is fixed with the next version
