### ISSUE TITLE
combine unload

### ISSUE THREAD

**Issue by michal44001** [Courseplay/courseplay#7485]
Worker don't drive to combine , it does't care that I'm driving the combine or CP worker. he's stopping on last point and staying , I was making routes as on yt tutorials, ver6.4.0 downld from mod hub, but when I'm downld from github(6.4.0.6) , game want upgrade from modhub (6.4.0.0) this is weird.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ

**Comment by Tensuko** [comment]
> game want upgrade from modhub (6.4.0.0) this is weird.

ModHub doesn't care about Mod Version, it only checks the .zip hash.
