### ISSUE TITLE
Courseplay mit Manure system

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#7486]
Hallo 
Folgende Frage. Wenn der Fahrer mit Courseplay fährt und mit den Güllewagen am Behälter ran fährt wird dann der Schlauch automatisch am Güllewagen gekoppelt oder wie funktioniert dass

**Comment by Tensuko** [comment]
AI Driver brauchen keinen Schlauch, es funktioniert so wie sonst auch.
