### ISSUE TITLE
Driver Reversing at corners constantly

### ISSUE THREAD

**Issue by LeomatGIT** [Courseplay/courseplay#7487]
Hi there I create a course on a field and when the helper get to a corner it turns to try and get to next point but just makes micro adjustments in reverse for ever and end up in a right pickle. Am i missing a setting or something? 
![Screenshot 2021-09-15 172238](https://user-images.githubusercontent.com/90787508/133471694-a46392b1-a849-41ad-b478-3917a44f0acb.png)

**Comment by Tensuko** [comment]
Good that we can't rly see anything here again...
gsSetDayTime10

No Idea if turn Issue or tool can't be reversed, as I don't see whats the tool doing...

**Comment by Tensuko** [comment]
Also read Wiki, no logfile...
https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
After I brighten up the screenshit by myself I can tell you that you need to change the attacher of the seeder from 3 point to that other single one, that it works.....
next time logfile and better screenshots pls...
