### ISSUE TITLE
Micro adjustments fieldwork in a straight line and turning on up/downs

### ISSUE THREAD

**Issue by LeomatGIT** [Courseplay/courseplay#7488]
Hi im having a problem with micro adjustments using fieldwork in a straight line and turning on up/downs. Using custom modding John Deere 9RX and 2680H High Performance Disk Trailer hitch (however it happens with other tools as well). Didnt know how best to show so make a screenrecording ( https://youtu.be/bJAFv2pb2j4 ) And also attached some screengrabs.
![fsScreen_2021_09_16_14_12_55](https://user-images.githubusercontent.com/90787508/133620887-bcfae3cc-eae5-4cb9-90fb-f793de7701f3.png)
![fsScreen_2021_09_16_14_12_56](https://user-images.githubusercontent.com/90787508/133620897-305c49d5-b34e-4068-bd5b-ab636a6570c2.png)
![fsScreen_2021_09_16_14_13_09](https://user-images.githubusercontent.com/90787508/133620906-53f228f3-8fca-476b-b104-1c8248637d68.png)
![fsScreen_2021_09_16_14_13_10](https://user-images.githubusercontent.com/90787508/133620912-4231c8c2-4e23-4d76-b14a-4411a47902b8.png)
![fsScreen_2021_09_16_14_13_26](https://user-images.githubusercontent.com/90787508/133620920-2158e2ed-6bed-4ab9-b335-afd416a24065.png)

**Comment by tn4799** [comment]
First please send us your log.txt-file.

**Comment by LeomatGIT** [comment]
where can i find that?

**Comment by LeomatGIT** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/7179490/log.txt)
is this it?

**Comment by Tensuko** [comment]
Thats a Mod Issue of the JD.
Something with angle and nodes, not sure what was the problem exactly.
You can try adjust the turn radius.

**Comment by LeomatGIT** [comment]
I will test with both a different trailer and also tractor and get back to you.

**Comment by Tensuko** [comment]
Closed due toinactivity
