### ISSUE TITLE
Problem with discharge route 

### ISSUE THREAD

**Issue by Hrala** [Courseplay/courseplay#7489]
Good afternoon, I have trouble making silage,
I generate a route for harvesting and another for unloading, however, when the trailer fills 100%, the tractor does not continue alone for the unloading route, it simply stops 
https://i.imgur.com/LQovlDi.png

one more problem: when I click on 'Drive Now' it goes to the unload route, however, when the tractor arrives at the silo door to unload, CoursePlay simply shuts down and does not unload 
https://i.imgur.com/zdriGna.png

is it possible to fix these problems?

**Comment by Hrala** [comment]
I also tested it in some older versions of CoursePlay, in some, when the truck is filled it even automatically goes to the unloading route, but when it arrives at the silo entrance it stops !!

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Tensuko** [comment]
Also chopping that way is not supported.
