### ISSUE TITLE
How many Workers 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#7491]
Hello how many workers can cp handle I’m getting an error I’m nearly up to double figures can get a log when available

**Comment by Tensuko** [comment]
Issue Number 214312541245
Pls use the search, I answered this many times now, next Version it is fixed, thanks!

**Comment by tn4799** [comment]
@matty2123 in the latest release you could use at most 10 workers. But Like Tensuko said, this will be fixed in the next release-version so that you have an unlimited amount of workers
