### ISSUE TITLE
Hud problem

### ISSUE THREAD

**Issue by michal44001** [Courseplay/courseplay#7496]
The worker sometimes go wrong last issue was done but I see that the combine going first line around when it's full go back to next line and wait for driver. Second problem is in HUD I dont see the lines avoid fruits. version 6.4.0.6
![Farming Simulator 19 Screenshot 2021 09 18 - 20 01 54 14](https://user-images.githubusercontent.com/63665216/133898227-0591b747-70f4-487c-9178-bd3b66eb7581.png)

**Comment by Tensuko** [comment]
I rly don't know what you try to tell us here...

logfile ?

https://github.com/Courseplay/courseplay/wiki

Your Combine drive the wrong line, but when does this happen ?

What do you miss in the HUD ?
Avoid Fruit ?

BTW you have the wrong display to show waypoints, it is on the HUD Page the 3 Dots...

**Comment by michal44001** [comment]
Yes I miss Avoid fruit I can't see it, combine is going wrong line when it's full and wait for unload how you see on screenshot. What is wrong with dots I've just want to see the how combine is driving .

**Comment by Tensuko** [comment]
You have the debug for the lines on, not the course WP and debug takes performance.
Anyway, that is not 'the wrong line' that is just the Pocket then, it depends on the pipe lenght.

Still not logfile. The Avoid Fruit option is here:
![fsScreen_2021_09_18_21_01_04](https://user-images.githubusercontent.com/27344744/133905787-f283ba0a-3d41-487d-94dd-3679602d0e0d.png)

**Comment by Tensuko** [comment]
So, did you found it now ?

**Comment by Tensuko** [comment]
Closed due to inactivity
