### ISSUE TITLE
Courseplay Generator

### ISSUE THREAD

**Issue by tymtscm** [Courseplay/courseplay#7497]
The generator was working fine for almost 24 hours and then all of a sudden, i got hit with this generated course, also it isn't automatically detecting the width of the attached tool.  This also happened after i updated to the latest version. Currently going back to the last version to see if it's still happening

![courseplay](https://user-images.githubusercontent.com/90986736/133907535-e78f079d-16fa-4431-bac0-702bc5a479b8.jpg)

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by tymtscm** [comment]
> https://github.com/Courseplay/courseplay/wiki

[log.txt](https://github.com/Courseplay/courseplay/files/7190788/log.txt)

**Comment by tymtscm** [comment]
> https://github.com/Courseplay/courseplay/wiki

i also didn't add any mods to my folder when updating Courseplay. but that is a very helpful link, thank you

**Comment by Tensuko** [comment]
A simple question...
can you zoom in and out on that map and see if the displayed course changes ?
We know that sometimes at specific zoom steps we have visual bugs with some lines.

**Comment by tymtscm** [comment]
yes. zoomed all the way in and out, i still see the same course. although, upon further testing, they don't seem to be following the lines outside of the field.

**Comment by Tensuko** [comment]
Well I don't have that problem and I never saw this happening for real.
Can you save the course and give us the coursefile ?
What map is this ?

**Comment by tymtscm** [comment]
> Well I don't have that problem and I never saw this happening for real.
> Can you save the course and give us the coursefile ?
> What map is this ?

not sure how to give you the coursefile. Also, this map is called PV County or Pleasant Valley County

**Comment by tymtscm** [comment]
it worked fine for over a day on this map. the course i made before this one, was just fine. looked like a normal course.

**Comment by Tensuko** [comment]
I am sure it is the Field of the Map.
The generator sure does not have any problem.
Did you even try other settings ?

**Comment by Tensuko** [comment]
Closed due to inactivity.
Never had 'over shooting' of normal up/down happening on any map.
Guess if that happens it is the Field, wich is a bit weird...
