### ISSUE TITLE
CP 6.03.00049 - when loading into MP "table expected, got nil" - PLEASE HELP!

### ISSUE THREAD

**Issue by kf6shc** [Courseplay/courseplay#7498]
![CP - 6 03 00049 MP error ](https://user-images.githubusercontent.com/66832075/133941643-0eb5c0e2-060e-49f6-8434-cbcc7ea82241.PNG)

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by kf6shc** [comment]
what exactly am i looking for here? i am really at a loss. 

thank you !!

**Comment by Tensuko** [comment]
Download the modhub version for MP.
Your Version is outdated.
