### ISSUE TITLE
(Suggestion) Option for grain cart to park behind combine after unloading

### ISSUE THREAD

**Issue by SuperPyroManiac** [Courseplay/courseplay#7500]
I've been playing with some large fields using 2 to 3 combines and it works flawlessly! Seriously impressive. The biggest issue though is the automated grain cart. After unloading a combine it just stops dead in the field blocking other combines.

My thoughts on improving it is to have an option where it will reverse and park in the center of the strip behind the combine that it just unloaded. That way it is out of the way of all combines, and is still close by.

**Comment by Tensuko** [comment]
Can you give us an example where it blocks the combine ?
None of our unloadpositions does this, unless you unload in the fruit!

**Comment by SuperPyroManiac** [comment]
I have it set to true always and they don't really care and will still pickup and park in it.

https://i.imgur.com/qUwPTSC.jpeg


Another situation is with the headlands. An example: Say you have a rectangle field, and have a headland. If he finishes unloading on the short edge of the field where the harvesters turn, he will park there and when they turn there they crash into him.

**Comment by Tensuko** [comment]
It might be that it didn't detect the fruit becouse the width of the last row it too smal.
It happened to me too, but thats not a general problem.
No need to create an extra option for this.

Else we can adjust the fruit detection (I might know what happens here...) or need to think about an other solution.

**Comment by rohne83** [comment]
Do you have avoid fruit activated also for the combine? Normally in that case the combine should stop and unload from a pocket, so the unloader doesn't have to move into the fruit at all.
Btw, you can avoid situations like that nearly completely by using lands or spirals mode instead of normal up/down when you want to have your combines unloaded actively. With those two modes the pipe will stay outside the fruit nearly always.

**Comment by rohne83** [comment]
No the issue at least on your screenshot seems to be just that your combines are running in wrong order. The first one should work on the left lane and the second one on the right lane (for that to work perfectly with convoys in every row you have to deactivate the Symmetric lane change in the HUD - at least for lands and spirals). That way the pipe is always outside of the fruit, and in the rare cases it is not (can only for the leading combine in first headland and first row of a new land) the combine will always notice that it has fruit under the pipe and create a pocket.
