### ISSUE TITLE
accident with train barriers

### ISSUE THREAD

**Issue by landtools** [Courseplay/courseplay#7502]
hi, is there a way to prevent the tractor from ending up on the barriers so as to avoid an accident with barriers?

**Comment by Tensuko** [comment]
There is no train barriers integration.
It could just work with a collision detection but that would only work if the barriers are already closed.
The only chanze would be to look if a train will come and that is not integrated in the game.

**Comment by landtools** [comment]
correct .... when the barriers are closed, the tractor crashes into the barriers and rolls over....
