### ISSUE TITLE
Häcksler fährt erst schnell und dann langsam

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#7506]
Hallo 
Weiß jemand warum der Häcksler so langsam fährt
Mit Bild und Log
[log.txt](https://github.com/Courseplay/courseplay/files/7230249/log.txt)

![Häcksler](https://user-images.githubusercontent.com/47453761/134783689-c649d05f-646e-44a2-b6ed-e419d4a480eb.png)

**Comment by Tensuko** [comment]
Nö, kein Plan.
Mod Häcksler ?
Pickup ?
Warum kommt bei dir bei Stroh eigentlich Häckselgut raus ?

**Comment by Hendirk** [comment]
Ich benötige ein Mod der dazu passt --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 25.09.21, 21:51 schrieb Tensuko ***@***.***>:

   
  Nö, kein Plan. Mod Häcksler ? Pickup ? Warum kommt bei dir bei Stroh eigentlich Häckselgut raus ?
