### ISSUE TITLE
CP Generator not working [LUA Error] Multiplayer

### ISSUE THREAD

**Issue by Zoriot** [Courseplay/courseplay#7507]
Since the newest Release v6.4.0.7 i have the error that i cannot generate a course (the window doesnt show up) the problem was in the vanilla New Holland CR10.90 but in other Harvester too. 
 
Per click on the ``Kursgenerierung`` this error is shown in the log:
``2021-09-25 18:23 Error: Running LUA method 'mouseEvent'.
2021-09-25 18:23 dataS/scripts/gui/elements/MultiTextOptionElement.lua(129) : bad argument #1 to 'min' (number expected, got nil)``

Logs:
[FS19 Log [Courseplay]](https://gist.github.com/Zoriot/c0eb061a2ee7eace7236449d5da4acb0) 
[FS19 Log [Courseplay] mit Debug Channels 18, 19, 20](https://gist.github.com/Zoriot/aab74928adeb76edc9e5063f586b28e9)

2'nd Problem:
Sometimes the course lines aren't showing up on the screen even all lines are enabled. The Driver works normally.

Hope this is fixed soon, we'll Rollback to 6.4.0.6.

**Comment by Tensuko** [comment]
#7285
