### ISSUE TITLE
How do I turn off messages?

### ISSUE THREAD

**Issue by kamil1997rok1** [Courseplay/courseplay#7508]
In earlier versions, when you turned on the preview map and turned off the hud, everything disappeared, and now a message appears at the bottom of the screen. How do I turn it off? 

![FarmingSimulator2019Game 2021-09-26 10-56-40-23](https://user-images.githubusercontent.com/91410710/134800979-d25b97f9-140f-4fb0-8fd3-4e86600a149a.png)

**Comment by Tensuko** [comment]
This is not implemented yet.

**Comment by kamil1997rok1** [comment]
![FarmingSimulator2019Game 2021-09-26 11-13-57-60](https://user-images.githubusercontent.com/91410710/134803286-93bb05e1-a6b7-44c7-9e5b-6a3a47108337.png)
![FarmingSimulator2019Game 2021-09-26 11-14-01-14](https://user-images.githubusercontent.com/91410710/134803288-a1fee356-3075-41d5-ad24-c2b55cb764f7.png)
 
 
 Previously, I turned on a larger map window and it disappeared.


In that case, I am waiting for a correction.
