### ISSUE TITLE
CPU overload while trying to generate course 

### ISSUE THREAD

**Issue by emwedk** [Courseplay/courseplay#7515]
Generated a course with a normal trailer (testing things here and there)

since the "working width" is set to 0.0m, i believe that it will try to generate a course with a working width of either a very low number, or just a constant unbreakable loop.

you should probably check if working width is 0, and only generate if it's above

**Comment by Tensuko** [comment]
It will only take a while then it will notice the problem.
Nothing will overload your CPU, thats sounds like it is breaking stuff...

**Comment by emwedk** [comment]
it doesn't just "take a while" - i did it 2 times, and both times i had to force close with all my powers, almost had to reboot my pc - it literally LOCKED up my entire pc

**Comment by Tensuko** [comment]
so how long did you wait ?
logfile ?
what do you expect to change with min 0.1 it wiil take long anyway...

**Comment by emwedk** [comment]
i don't expect anything from 0.0m (not 0.1) - it was a mistake, but wouldn't it still be a bug, if i do something by mistake, and it crashes my pc, and makes it fully inoperable?

i waited for atleast 2min WITH huuuuge drag on ANY task i tried to do - like, couldn't even get task manager up, couldn't quit game, couldn't stop the task .... i mean - why u shrugging this off?


regards to log file, what types of debug do u need turned on to see what u need to see?

**Comment by emwedk** [comment]
8700K, geforce 1070, 16gb ram ...
