### ISSUE TITLE
courseplay upgrade

### ISSUE THREAD

**Issue by javier2728** [Courseplay/courseplay#7516]
hello I don't know where to raise this, I have a problem with the update of courseplay, I have installed the version of courseplay 6.4.0.0 and I want to take it to the current 6.0.0.7 and when I do it it does not open any game, someone knows how to solve it thanks

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki
with 6.4.0.7

**Comment by javier2728** [comment]
HELLO THANK YOU FOR THE PROMPT RESPONSE I TELL YOU TO START A NEW GAME AND PLACE THE COURSEPLAY THERE THE NEWEST VERSION AND ENABLE ALL THE MOD I HAVE IN WHICH I CURRENTLY USE ONE TO SEE IF IT FAILED WITH ANY ONE AND IT DIDN'T DO SO THAT WORKS WELL BUT I CANNOT OPEN THE GAME THAT I PLAY WITH THAT COURSEPLAY OR I HAVE TO KEEP USING THE OLD ONE, I DON'T KNOW IF I EXPLAIN IT WELL.
I REPEAT I AM NOT VERY ABLE WITH THIS (I'M BIG ALREADY HEH)
TRY TO OPEN THE LOG FILE AND DELETE ERROR MODES (MOST)
YOU CAN DO SOMETHING ELSE
I AM sorry IF THE TRANSLATION IS NOT GOOD BUT I ONLY SPEAK SPANISH AND I USE THE GOOGLE TRANSLATOR THANK YOU VERY MUCH

**Comment by javier2728** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/7246565/log.txt)

**Comment by javier2728** [comment]
Hello, how good could I solve the previous problem, update the version to improve the unloading of the silo in trailer with the shovel, I saw a video that you made explaining how it is done and I did it as you mentioned it, the problem is that it arrives to the trailer and the shovel lowers and goes back up, that is, it did not unload, I do not know if I am doing something wrong or there is something to change, I thank you for the answer since I have been trying for hours, thank you very much

**Comment by Tensuko** [comment]
To many Errors from other Mods.
Clean Mods folder.
Not a CP issue, sry.

**Comment by javier2728** [comment]
> A muchos Errores de otros Mods. Carpeta Limpiar Mods. No es un problema de PC, sry.

Thanks for the answer I could already solve it, removing the mod, I wanted to know if you could tell me two things
The first if there is any possibility of configuring the helpers so that they do not leave the fields, since my games are on large maps and there are many of different ways and when the hopper is full and goes to the trailer, it takes the shortest path and many Sometimes he leaves the field, and the issue of the shovel for the silo managed to work by following a video of yours but only the loader works, not the MANITOU Y CLASS, that is good or not, thank you very much and congratulations for your work is great
