### ISSUE TITLE
problems with shredded

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#7517]
I created two paths with the CP to be able to cut a cornfield. The unloading path is carried out by 4 tractors with trailers and the other is the path of the forage harvester. In the field and on the road, everything works perfectly, the problem is biogas. I use the Felsbrunn base map. When I get to biogas two things have happened in the tests I did:
1) the tractor starts to back up (I have created the path so that it goes back to the bottom of the trench, I have inserted an unloading point and then the exit from the trench and the re-entry into the road) but before entering the area of the trench unloads the trailer and then gets stuck.
2) When starting the maneuver to go back to the unloading point it does not maintain the trajectory and gets stuck

Unfortunately I don't have the log available now, but at the next test I will attach it with other reports in case
I have this photo
![Farming Simulator 19 29_09_2021 08_29_42](https://user-images.githubusercontent.com/59969508/135216130-7ae452cc-41c8-4e44-8dde-36399e7e2d54.png)
![Farming Simulator 19 29_09_2021 08_30_18](https://user-images.githubusercontent.com/59969508/135216162-54cafdf0-aa9e-4617-94b2-dc48d26ae8ee.png)
![Farming Simulator 19 29_09_2021 08_30_20](https://user-images.githubusercontent.com/59969508/135216177-a94ca9bf-1b94-4f09-b7fe-e49ddabc4912.png)
![Farming Simulator 19 29_09_2021 08_30_21](https://user-images.githubusercontent.com/59969508/135216199-6b03b455-c382-4511-b9ae-b7ec4771f57a.png)
![Farming Simulator 19 29_09_2021 08_30_23](https://user-images.githubusercontent.com/59969508/135216228-6a0c3e27-b737-4f2d-ba71-d40ce4414ff9.png)
![Farming Simulator 19 29_09_2021 08_30_24](https://user-images.githubusercontent.com/59969508/135216243-13dc55e2-9ad4-4168-bafd-f24ddcc8ffc3.png)
![Farming Simulator 19 29_09_2021 08_30_26](https://user-images.githubusercontent.com/59969508/135216263-817ce921-e4ab-40b4-865d-f3570069cf76.png)
![Farming Simulator 19 29_09_2021 08_30_27](https://user-images.githubusercontent.com/59969508/135216285-31eec46f-d344-4d5d-b106-bb400bbf75aa.png)
![Farming Simulator 19 29_09_2021 08_30_29](https://user-images.githubusercontent.com/59969508/135216307-1ca04de4-bb05-4536-abd0-3253749ba918.png)
![Farming Simulator 19 29_09_2021 08_30_31](https://user-images.githubusercontent.com/59969508/135216332-e7603131-97c8-4f63-87fd-cc6f1e8589a2.png)
![Farming Simulator 19 29_09_2021 08_30_32](https://user-images.githubusercontent.com/59969508/135216361-f6ba97fc-f342-4ca7-8b47-cfa4b262ad46.png)
![Farming Simulator 19 29_09_2021 08_30_34](https://user-images.githubusercontent.com/59969508/135216374-7802e3cb-a96c-44ac-bb11-0520c1cea5bb.png)
![Farming Simulator 19 29_09_2021 08_30_36](https://user-images.githubusercontent.com/59969508/135216402-2ba7adf2-9286-4356-84b4-578408163ff9.png)

**Comment by Tensuko** [comment]
I need the logfile, what trailer what tractor and the course files pls.

Also do you have placed the unload here waypoint at the end of the Bunker?

**Comment by 0Pietro20** [comment]
Log: [log.txt](https://github.com/Courseplay/courseplay/files/7250454/log.txt)
some photos of the maneuvers, a screen of where the unloading point is located and two showing the vehicles (Fendt 828 and Bossini RA 200/7 in particular)

![Farming Simulator 19 29_09_2021 10_57_57](https://user-images.githubusercontent.com/59969508/135237640-39564758-5fc7-4e28-9009-4ae3a1610144.png)
![Farming Simulator 19 29_09_2021 10_57_59](https://user-images.githubusercontent.com/59969508/135237661-177c4b86-2ed0-441f-b7b9-6d8eaa4b2633.png)
![Farming Simulator 19 29_09_2021 10_58_00](https://user-images.githubusercontent.com/59969508/135237684-5e9de42e-13b5-43d6-acaf-e31cd8837129.png)
![Farming Simulator 19 29_09_2021 10_58_01](https://user-images.githubusercontent.com/59969508/135237711-e40aeadc-1a38-48bb-bd96-6ae59addaf54.png)
![Farming Simulator 19 29_09_2021 10_58_02](https://user-images.githubusercontent.com/59969508/135237744-1aa0b8d7-e304-4d7c-b59a-72f6acd1f9a1.png)
![Farming Simulator 19 29_09_2021 10_58_32](https://user-images.githubusercontent.com/59969508/135237765-e8c58975-8914-4c59-8616-d5b70ebb841f.png)
![Farming Simulator 19 29_09_2021 10_58_47](https://user-images.githubusercontent.com/59969508/135237792-47793820-8096-4ee9-8833-f43e5b90e41f.png)
![Farming Simulator 19 29_09_2021 10_58_54](https://user-images.githubusercontent.com/59969508/135237803-17ed03b3-fadc-41ed-a5d1-f790a19b3448.png)



![Farming Simulator 19 29_09_2021 10_57_56](https://user-images.githubusercontent.com/59969508/135237608-9866db1c-9ace-416f-b2f9-ab9a861396a6.png)

**Comment by Tensuko** [comment]
Ok so what we can see is, that the ORM Trailer seems to be not able to get pushed back.
So the reverse Issue is the Mod Trailer -> Mod Issue.

About Unload, does the BGA belongs to you ?
Otherwise I will test it out...

**Comment by 0Pietro20** [comment]
Sisi, of course I bought the BGA before testing. I will try to run the same test but not including the mods (except the CP of course)

**Comment by 0Pietro20** [comment]
I have discovered that some trailers (mods), for some reason unknown to me, give problems with maneuvers and unloading the chopped. After some tests I have isolated the "faulty" trailers and with the others everything seems to work

**Comment by Tensuko** [comment]
ok thank you for the feedback.
Then it is a Mod Issue.
