### ISSUE TITLE
Sichtbarkeit der aktuellen CP Position

### ISSUE THREAD

**Issue by FreemanGER2021** [Courseplay/courseplay#7521]
Hello Supporter
V6.04.07
CP course display, in contrast to V x.x.06, the current position can no longer be made visible (active route section)

V6.04.07
CP Kurseinblendung, dabei kann im Gegensatz zur V x.x.06 die aktuelle Position nicht mehr sichtbar geschaltet werden (aktiver Streckenabschnitt)
thx Freeman

**Comment by Tensuko** [comment]
Was auch immer du meinst ?!
Wenn du von dem Auge im HUD sprichst um Linien an zu zeigen -> das war alter unnötiger debug was zu Performance Problemen führt.

**Comment by FreemanGER2021** [comment]
Ja genau, das meinte ich. sorry für meine undeutliche Erklärung. Schade das es diese Sichtbarkeit nicht mehr gibt, da ich CP auch "halbautomatisch" nutze. Es war für mich immer eine sehr gute Orientierung um wieder an dem Punkt die unterbrochene Tätigkeit wieder aufzunehmen. Bspw: Düngen stoppen, dann Düngerstreuer"manuell" auffüllen" zurück zu dem Punkt und die Arbeit weiter fortsetzen.
Verstehe das wegen der Performence. 
Vielen Dank für Deine schnelle Antwort und viele Grüße
thx Freeman

**Comment by Tensuko** [comment]
Naja, dafür haben wir die option 'starte am aktuellen Wegpunkt' ...
Wie gesagt, es war nie eine Anzeige der Sektion, mal davon abgesehen, dass beim ausschalten des Fahrers das auch nicht unbedingt ersichtlich war.
Wie auch immer, das kommt nicht wieder rein.
