### ISSUE TITLE
Ins and outs 

### ISSUE THREAD

**Issue by Andystrong8484** [Courseplay/courseplay#7522]
Since iv updated to the new version of CP i have noticed that all my tools are now missing a bit on the ins and outs 

Image attached 

For example this machine reads at 15.2 set at 14.5 and still has a miss
![fsScreen_2021_10_02_10_00_50](https://user-images.githubusercontent.com/75746655/135710208-24c7f0cb-4a3d-419a-9abe-ad0646c5d460.png)
[log.txt](https://github.com/Courseplay/courseplay/files/7271186/log.txt)

**Comment by Tensuko** [comment]
Advanced settings:
Set Raise tool to late and lower tool to early.
Thats nothing new and depends on the tool not on CP Version...
