### ISSUE TITLE
Problem with BGA courseplay v6.4.0.7

### ISSUE THREAD

**Issue by wariacik33** [Courseplay/courseplay#7524]
The driver crashes into the fence if another tractor is working in the bunker next door ... If I stop the ramming course, the problem disappears. The same happens if the tractor compacts the same bunker that is currently being refilled.

I hope it is understandable I write through the google translator
If I forgot something, I am sorry. :]
https://youtu.be/QZY4yvOJbms

**Comment by wariacik33** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/7271719/log.txt)

**Comment by Tensuko** [comment]
And what happens if the other Tractor is not working there ?
Still crashes into the fence ?

**Comment by wariacik33** [comment]
If I stop the silage compaction course, the problem disappears... He no longer hits the fence.

**Comment by Tensuko** [comment]
Can you post your savegame and the course files ?
I would like to have a look at this.

**Comment by wariacik33** [comment]
Sure.
[savegame, coursefiles.zip](https://github.com/Courseplay/courseplay/files/7273237/savegame.coursefiles.zip)
