### ISSUE TITLE
Zu lange Wartezeit bei Kursberechnungen?

### ISSUE THREAD

**Issue by BlackDragon075** [Courseplay/courseplay#7527]
Hallo zusammen,
wie der Titel schon erwarten lässt hab ich festgestellt das mein Rechner zu lange für die Kursberechnung braucht. In mehreren Videos hab ich das ganze schon wesentlich schneller gesehen. Mir ist klar das grössere Felder länger berechnet werden müssen aber zu dem was ich gesehen habe sind 10-15 Minuten Standbild dann doch etwas zu lang. 

Und noch was anderes. Da weiss ich allerdings nicht ob es an Courseplay oder AutoDrive liegt. Wenn der Drescher (mit Courseplay aktiv) den Abfahrer (mit Courseplay und AutoDrive aktiv) ruft laggt es bei mir ziemlich übel. Selten auch mal mehrere Minuten. 

Mehr Infos zu Specs, Mods etc in der Log
[log.txt](https://github.com/Courseplay/courseplay/files/7274653/log.txt)

**Comment by Tensuko** [comment]
Erstmal ist wie immer Geduld angesagt!
Zum zweiten, dass der Abfahrer aufgrund des Pathfinders beim berechnen für FPS einbrüche (das sind keine lags!) sorgt, ist bekannt, seit ewigkeiten.
Wenn ich das hier lese (Version: 6.4.0.7) FS19_CoursePlay6 kriege ich schon wieder nen Anfall....
https://github.com/Courseplay/courseplay/releases
.zip laden, rein in den mods Ordner FERTIG! Hört auf mit diesem neu packen und umbenennen und so einen Mist...

Dann gibt es bei dir Errors, die von ich weis nicht woher kommen, aber irgend ein Fahrzeug bei dir meldet wohl Radius 0 womit AD oder CP (nicht genau erkennbar, vermute aber AD) nichts anfangen kann.

Der CP Abfahrer macht nen Callstack, weil du scheinbar nur einen Wegpunkt im Kurs hast, das kann nicht klappen.

**Comment by BlackDragon075** [comment]
Wäre schön wenn man mal nicht gleich so angegangen werden würde! War von mir keineswegs irgendwie negativ gemeint oder mega kritisch... Mich würde nur mal interessieren wo diese langen standbilder herkommen bei der kursberechnung. In der zeit reagiert der ls ja auf garnichts. Aber ob da jetzt irgendwas im mod nicht stimmt oder mein rechner da irgendwo zu schwach ist kann ich ja schlecht beurteilen! Ich weiss ja auch nicht was diejenigen die videos aufnehmen für rechner zum zocken haben.. 

Und wegen der zip... Ich hätte es nicht selbst gepackt wenn es mir als originalldatei nigame bei den mods angezeigt worden wäre!  Denn das war  nicht der fall. Erst nachdem ich es selbst gepackt hatte konnte ich courseplay überhaupt aktivieren. 

Und das mit den FPS Einbrüchen hat sich mehr oder weniger selbst geklärt. Nach ner zockpause hat AD dann ganz ohne Einbrüche den abfahrer zum drescher geschickt. 

Alles aus dem Log sollte man auch nicht zu ernst nehmen. Meine finger sind gern mal schneller als der rest sodass ich ein fahrzeug losschicken will obwohl die hälfte noch fehlt.

**Comment by Tensuko** [comment]
Keines der offiziellen zip Files der Mods, heist so wie er bei dir im Ordner liegt.
Weder ModHub noch GitHub Release Seite.
Es ist kein entpacken oder sonstiges Notwendig!

Kursberechnung hängt von der Arbeitsbreite und der komplexität des Feldes ab.
Je nach dem gibt es auch entsprechende Anzahl an Wegpunkte, was eben etwas dauert.

FPS einbrüche kommen beim Pathfinder von CP vor.
AD benutzt eine andere Methode um zum Drescher zu fahren.

Sowohl der Pathfinder, als auch der Kursgenerator arbeiten so wie sie können, wie es die Endinge zu lässt. Ein stärkerer Rechner hilft irgendwann nicht mehr.

**Comment by Easton97-Jens** [comment]
Moin
Die AD Version würde ich aktuelle Version vom Github runter laden das es in der modhub Version Fehler gibt die schon korrigiert worden sind und ich würde auch den Grafiktreiber mal aktualisieren da du eine alte Version verwendest.

**Comment by Tensuko** [comment]
Pathfinder is always on our todo list, no need an extra Issue, closing...
