### ISSUE TITLE
Disconnect bei mobilem Hotspot

### ISSUE THREAD

**Issue by Bomisch** [Courseplay/courseplay#7528]
Ich habe folgendes Problem:
Wenn ich mit meinem Handy einen Hotspot aufmache und im Spiel versuche CoursePlay zu starten habe ich immer einen Verbindungsabbruch. Sonst funktioniert mit Latenz etc. das Spiel einwandfrei. Es ist nur sobald ich bei CoursePlay den Abfahrer einstellen will.
Bin ich daheim über meine normale Leitung am spielen habe ich dieses Problem nicht. Vielleicht hat ja von euch einer eine Idee woran es liegen kann.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by Bomisch** [comment]
https://gist.github.com/Bomisch/23e97f649573b8178455253df9acd827#file-gistfile1-txt

**Comment by Tensuko** [comment]
Das hat aber nichts direkt mit CP zu tun, da scheint irgend eine Mod von dir mir rein zu gretschen.

**Comment by Bomisch** [comment]
Hätte ich ja auch vermutet. Warum klappt es nur zuhause im WLAN und nicht über meinen mobilen Hotspot vom Handy. Es ist der selbe PC mit den selben mods. Somit kann es ja nicht an einem mod liegen

**Comment by Tensuko** [comment]
Dann aber auch nicht an CP, wenn es nur beim HotSpot passiert!
CP ist schließlich auch nur eine Mod.

Sry aber da können wir nichts machen.
