### ISSUE TITLE
DBG Linien in der v6.4.0.7 verschwunden

### ISSUE THREAD

**Issue by Cassy-Blair** [Courseplay/courseplay#7529]
Vermisse die DBG Linien in der neuen CP Version. Die DBG Linien waren durch die violette Markierung sehr hilfreich, wenn man einen Kurs kurzzeitig unterbrechen mußte und wieder den richtigen Anschlusspunkt finden wollte. Bin nun notgedrungen wieder zurück zur v6.4.0.6
Wäre schön, wenn die DBG Linien wieder reinkommen würden.
![grafik](https://user-images.githubusercontent.com/87262647/135993822-007de73c-6ebe-4b91-b045-6973e2d62b44.png)

**Comment by Tensuko** [comment]
Nein die kommen nicht wieder weil es unnötiger debug war der nur Performance frisst.
Es war nie für diesen Zweck geschaffen.
Wenn sowas benötigt wird, unter Discussion eine Idea aufmachen wo die NORMALE Wegpunkte aufleuchten um an zu zeigen wo man gerade ist.
Mal davon abgesehen, dass man anhand der Bearbeitung des Bodens sieht wo man zu letzt war und es auch die option gibt starten am aktuellen Wegpunkt.

**Comment by Cassy-Blair** [comment]
> 
> 
> Nein die kommen nicht wieder weil es unnötiger debug war der nur Performance frisst. Es war nie für diesen Zweck geschaffen. Wenn sowas benötigt wird, unter Discussion eine Idea aufmachen wo die NORMALE Wegpunkte aufleuchten um an zu zeigen wo man gerade ist. Mal davon abgesehen, dass man anhand der Bearbeitung des Bodens sieht wo man zu letzt war und es auch die option gibt starten am aktuellen Wegpunkt.

Ohne die violette Markierung erwische ich aber nie den richtigen Punkt, sondern erwische mehrfach den falschen Punkt. Aber ok, gut zu wissen, daß es nicht mehr kommen wird, dann werde ich beiu der v6.4.0.6 bleiben und die Updates in Zukunft vermeiden

**Comment by Tensuko** [comment]
Also erst mal ist das nicht gerade schwer, einfach kurz vorher starten und gut ist.
Wie gesagt, aktueller Wegpunkt.....
Und hast du meine komplette Antwort gelesen ?

Discussion, Idea, trag das ein was dir Fehlt und wir schauen ob wir den aktuellen WP vlt aufleuchten lassen oder anders einfärben oder whatever.... Nein eine Anleitung wird es nicht geben, da es viel zu komplex war. Wie gesagt, es war eine Reine debuginformation.... mehr nicht.

**Comment by Cassy-Blair** [comment]
> 
> 
> Also erst mal ist das nicht gerade schwer, einfach kurz vorher starten und gut ist. Wie gesagt, aktueller Wegpunkt..... Und hast du meine komplette Antwort gelesen ?
> 
> Discussion, Idea, trag das ein was dir Fehlt und wir schauen ob wir den aktuellen WP vlt aufleuchten lassen oder anders einfärben oder whatever.... Nein eine Anleitung wird es nicht geben, da es viel zu komplex war. Wie gesagt, es war eine Reine debuginformation.... mehr nicht.

Ist halt gerade bei Saatmaschinen, Kartoffel- und Rübenerntern mit 2-3m Breite ein Problem, wenn ich zum Wenden unterbrechen muß wegen Kollision mit einem Baum oder Zaun. Da findet er dann meist nicht mehr den richtigen Anschluss und mit den DBG Linien war das ganze besser und einfacher.

Zum Punkt "Discussion, Idea" kann man den Beitrag nicht einfach dorthin verschieben? Dann müßte ich nicht alles neu schreiben

**Comment by Tensuko** [comment]
Du sollst ja uach nicht das DBG neu beschreiben, sondern eine Idee zum wiederfinden des letzten Wegpunktes beschreiben...
Außerdem kannst du doch Copy and Paste machen ?!
