### ISSUE TITLE
Grain carting from field with multiple carters no traffic issue

### ISSUE THREAD

**Issue by McLovinnitre** [Courseplay/courseplay#7535]
i'm harvesting fields and using auger trailers on the field and a couple grain carting trucks. My issue is the two trucks on the grain carting course doesn't wait because of traffic. They don't stop at the stop point i have appointed and they just want to contiune on to the first point, even though another truck is already there, so the last truck ends up pushing the first truck, long enough that the first truck is way past the first point in the course. The trucks are on mode 1.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by candymant** [comment]
The truck drivers has to be in mode 8.

**Comment by Tensuko** [comment]
Screenshots ?

**Comment by McLovinnitre** [comment]
The issue is that on mode 1, there is no traffic collision it seems. And when i run multiple graincarters, the second grain cart drives into the first one because courseplay just shuts off the colision detection. This only happens when the second bay in the 1st grain trailer gets loaded because it moves ahead to have that bay under the starting point., and it's within the same trailer.
