### ISSUE TITLE
Radlader lädt in der BGA nicht ab

### ISSUE THREAD

**Issue by GulliGriff** [Courseplay/courseplay#7538]
Hallöchen, mit der Version 6.4.0.8 lädt mein Radlader nicht mehr ab :(
https://youtu.be/Rbgf3DO_yYk
ich habe alles mögliche ausprobiert, aber es ist immer das gleiche Ergebnis. Also egal ob mit Vanilla oder mit der benutzten Kombi, selbst mit neu eingefahrenem Kurs, er lädt nicht ab. Der Einfachheit halber habe ich den Kurs der mit 6.4.0.0 und 3 Haltepunkten tadellos funktioniert hat genommen und lediglich die 2 aus dem Silo entfernt.
Was mache ich nur falsch?
[log.txt](https://github.com/Courseplay/courseplay/files/7307817/log.txt)
Ich würde so gern mal ein update auf dem Server machen...

**Comment by Tensuko** [comment]
Tip am Rande:
So viele Wegpunkte in den Bunker rein, braucht man nicht.

Schiebe mit dem Editor den letzten WP vor dem Wartepunkt mal dichter an den Wartepunkt
![WP](https://user-images.githubusercontent.com/27344744/136506322-1ca981f9-26a9-4fb8-bc2c-8cde98072a0b.png)
.

**Comment by Tensuko** [comment]
> ich versteh das nicht mit der 6.4.0.0 hat alles bestens funktioniert.

-> #7276

Dann hast du deinen Kurs aber noch komplett anders aufgebaut mit der 6.4.0.0 !
Lies mal das Info Issue...

**Comment by GulliGriff** [comment]
naja, so komplett anders ist es ja nu auch nicht. ich habe ja schon geschrieben, dass ich den kurs auch komplett neu eingefahren hatte und immer das selbe problem... entweder bleibt er stehen oder fährt durch :(
hier habe ich mal nen kurs neu eingefahren... https://youtu.be/e7pSRwzvjPU und das ist am ende raus gekommen. mit der version 6.4.0.0 sieht das ganze so aus https://youtu.be/JFNY4h6znXM
bei dem ganzen geteste hat er 1 mal die schaufel vor dem trigger angehoben und ist dann aber mit "vor abkippen" wieder aus der bga gefahren... 
ich scheine wohl der einzige zu sein der das problem hat, wie nervig :(

**Comment by GulliGriff** [comment]
ich hab das ganze auf der felsbrunn ausprobiert und da funktioniert es zumindest in der BGA. vielleicht liegt es irgendwie an der map. hab das ganze heute auf dem MP ausprobiert und da liessen sich plötzlich die radlader nach dem positionsspeichern nicht mehr manuell bedienen. ich glaub ich lass das und lebe dann halt mit der 6.4.0.0 :(

**Comment by Tensuko** [comment]
Ja aber so ein feedback ist wichtig für uns.
Ich werde mir das Issue mal markieren und schauen ob ich da was finde...

**Comment by GulliGriff** [comment]
ich habe die map mal im sp komplett neu gestartet, alles kurse gelöscht usw. also jungfreulich sozusagen. jetzt passiert das
![20211010170015_1](https://user-images.githubusercontent.com/59224815/136701511-04bdbf55-ca48-414e-85fc-561b4aeb59b3.jpg)
sollte das nicht andersrum sein? der versucht jetzt immer zum 1. punkt zu kommen und dreh halt um da rückwärts da hin zu kommen. abgesehen davon funktioniert der kurs von der miste des kuhstalls zwar mit beladen aber wieder das gleiche, entweder er bleibt vor dem trigger stehen under er fährt drüber. leider nichts in der log :(
![20211010170833_1](https://user-images.githubusercontent.com/59224815/136701729-1ef2949c-2f3a-4577-bccd-7067dd45c7d3.jpg)
beim rückwärts fahren dreht er die lila linie um die dann verschwinden. ich denke so sollte es auch im silo sein. ist halt nicht uns und da ist es egal ob ich ne mod oder ein original silo ... ob es ein keil oder durchfahrsilo ist.
![20211010170912_1](https://user-images.githubusercontent.com/59224815/136701791-0d84e6bf-9027-4702-a560-359a260d136c.jpg)
nach wie vor bleibt er stehen, setze ich den wartepunkt näher an den trigger fährt er durch :(
naja, wie gesagt bei der bga funktioniert nu gar nix mehr, weder das beladen noch das entladen (wenn ich die schaufel manuell belade ist halt das gleiche wie vorher, entweder bleibt er stehen oder fährt durch (wenn der wartepunkt näher bzw. im trigger ist) durch.
im übrigen habe ich auf dem server ein neues feature, wenn ich die positionen der schaufel gespeichert habe lässt sich die nicht mehr manuell bedienen und ich habe ständig micro ruckler und wer hätte es gedacht in beiden logs nicht drin :(

**Comment by Tensuko** [comment]
Auch BGA funktioniert
![fsScreen_2021_11_03_08_53_24](https://user-images.githubusercontent.com/27344744/140025311-c00cbc42-23ff-4ee3-a729-f85fbd8897bd.png)

**Comment by timmi4026** [comment]
> Also mit der aktuelle Version Arbeite ich sogar im Kalkwerk auf der Irgendwo in Thüringen und es funktioniert. Ich kann mir das bei dir echt nur mit einem Problem beim Kurs, oder irgendwelche Besitzrechte erklären (vlt noch filltype Probleme). Selber etwas in die BGA kippen hattest du probiert ?
> 
> Hier mal mein Kurs: ![fsScreen_2021_10_27_15_46_53](https://user-images.githubusercontent.com/27344744/139078620-09fc3d51-8e98-450e-b3ca-c382e4e60dd6.png) ![fsScreen_2021_10_27_15_47_03](https://user-images.githubusercontent.com/27344744/139078630-801527fd-baea-4671-8448-91f9721f6f92.png)

Ja bis zur Version 6.4.0.6 geht alles problemlos. So wie das aussieht spielst Du im SP modus. Wir sind auf dem Server damit, und wenn ich das im SP testen möchte erscheint nicht mal das Hud. Ka warum aber es öffnet sich nicht. Naja lass ich eben die 06 laufen für die paar Tage.

**Comment by Tensuko** [comment]
Ja gut, ich meine aufm Server läuft es auch aber kann noch mal gucken...
