### ISSUE TITLE
Performance Problem Courseplay on a 16x Map

### ISSUE THREAD

**Issue by benkywenky** [Courseplay/courseplay#7540]
Hallo everyone,

we have built a real replica 16x map in the LS19. Everything works perfectly, both on the SP and on the MP. But as soon as Courseplay is activated in connection with Autodrive, every 20-30 minutes we have a huge load in the interface of the server. That is why we have strong jerks that calm down after about 50 seconds. Without courseplay we don't have these problems. Unfortunately, a few fields are so large that course play cannot calculate them (the largest field is over 600 hectares). We have switched off automatic scanning in the savegame. Courseplay is installed on the latest version. Can someone help us how we can fix this? Kind regards Benkywenky
[log_FS19.txt](https://github.com/Courseplay/courseplay/files/7313699/log_FS19.txt)
![Server_Performance](https://user-images.githubusercontent.com/92182223/136614357-0234dc74-0b20-4f24-82a1-d0553775997a.PNG)

[server_log.txt](https://github.com/Courseplay/courseplay/files/7313713/server_log.txt)

**Comment by Tensuko** [comment]
As long as no CP Driver is active, you can't do anything for this.
But you downloaded just the release ?

The only thing I read in the Serverlog is the multi tool course.

You can turn on debug channel 20 and see if CP keeps sending stuff wich the server doesn't like.
But for us we haven't seen any spikes in our MP tests.

**Comment by Tensuko** [comment]
As you can guess, we won't put any more effort in CP for FS19.
Since most stuff is working okayish. We won't focus on specific things.

For FS22, I plan to have a better look on MP from the start and performance. Lets see what we can do!
