### ISSUE TITLE
Grain transport auto find unload 

### ISSUE THREAD

**Issue by tjpegram** [Courseplay/courseplay#7543]
Please add an option to disable this at least. The bins on my map unload and load at the same point which disallows me from using courseplay to automatically sell my grain.

**Comment by tjpegram** [comment]
The bins on my map both load and unload at the same point. This is a fairly common setup in North America and I’m surprised it hasn’t been an issue yet. The bins load a trailer from the air via a grain leg with a downspout over the trailer, and the unload pit is directly underneath the downspout, putting the two triggers nearly on top of each other. Because the newest versions of courseplay automatically find an unload point when they drive over them creating a course to sell grain the driver will load at the start point and then immediately begin unloading and drive off empty. This was not a problem when one had to set the unload point manually. All I’m asking is for a toggle in the advanced settings to disable the automatic finding of unload triggers as the driver crosses them. That will prevent these kinds of issues. As it stands with the current release of courseplay it is impossible to use courseplay to sell grain on this map because it will load and unload at the same time because the driver thinks the unload point at the bins is the one they should unload at when in reality I want them to act properly and load, drive off, and unload elsewhere at a sell point.

**Comment by tjpegram** [comment]
Don’t have a computer available to take the screenshot right now. But I’m not so much providing a big as a feature request. I dunno why you need more info. I’m not asking you to debug a problem. I’ve done that already. I know what the issue is. It’s a corner case that was looked over during development. It’s a simple request. A toggle to return grain transport back to the way it used to work where it only unloads at marked points in the course rather than at any unload trigger it finds. The other option would be to find all triggers on a course and “disable” one of them for the courseplay driver.

**Comment by schwiti6190** [comment]
@tjpegram Hi there,
not sure if I've understood your problem completely. 
You could try the branch linked above with the fix and give it a try. 
I tried a silo with loading and unloading at the same point and it seems to work.
Next time it would be helpful to direct attach a screenshot, as this is almost always easier to describe a bug :)

**Comment by Tensuko** [comment]
should be fixed
