### ISSUE TITLE
CP 6.4.0.8 MP  Einstellung automatische Reparatur funktioniert nicht

### ISSUE THREAD

**Issue by Dragonfly1982** [Courseplay/courseplay#7545]
Einstellung automatische Reparatur funktioniert nicht. 
Wir haben festgestellt das die Funktion im MP nicht funktioniert, egal bei welcher Prozentzahl er ist.

Anbei senden wir die Log mit der Fehler aufzeichnung.
[Server_log.txt](https://github.com/Courseplay/courseplay/files/7317185/Server_log.txt)

**Comment by Tensuko** [comment]
GlobalSettings Bug.
Wird in der nächsten Version gefixt sein.

**Comment by schwiti6190** [comment]
Should be fixed with the latest version.
