### ISSUE TITLE
Sugar beet/potato harvesters will not reverse

### ISSUE THREAD

**Issue by Nad42** [Courseplay/courseplay#7548]
Ive had a go with both the types of tractor mount harvesters and they both will not reverse; they always result in jack-knifing 
![image](https://user-images.githubusercontent.com/42980546/136859260-69365f50-0507-4ac5-a304-d4dddb5b7a25.png)

**Comment by Nad42** [comment]
Nothing came up in log file or I would have added. 

Using latest.. its synced to github master.

**Comment by Nad42** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/7353910/log.txt)
Here's the log for good measure. I made a new game on default map using vanilla machines, just to make sure it wasn't a mod. (only mod I had loaded is easy development controls)

**Comment by blubstar86** [comment]
Hey, looks like i have the same reverse issue with the Krone Premos 5000 (for Pellets) from the Straw Harvesting addon.

**Comment by Nad42** [comment]
@Tensuko Do you want more info?

**Comment by Tensuko** [comment]
We just had no time to look into this.
Ofc we will make sure that for FS22 this will work correctly.
It is a bit strange, that this happens, as we have not changed much on turns.
It might be becouse it is set to a 'combine' and does the special combine turn...
Won't change anything to this anymore.
You may try to run it without sharp corners, sry.
