### ISSUE TITLE
FahrSilo entleeren, Radlader fährt nicht richtig

### ISSUE THREAD

**Issue by SBlack08** [Courseplay/courseplay#7555]
Moin zusammen, ich könnte einmal euer wissen gebrauchen... ich versuche mein fahr silo mit cp entleeren zu lassen, nur irgendwie läuft das komisch ab. als ob der CP Fahrer 3 Promille im Blut hat^^ ich habe mir auch schon etliche tutorial dazu angeguckt (https://youtu.be/HWkOWeZKRcw) ob sich evtl. was verändert hat, aber ich finde keinen Fehler. ich habe auch schon zwei Radlader und 3 anbauten getestet, leider gleiches Ergebnis habe dazu mal ein kleines video gemacht, hoffe ihr hab ne idee. karte ist die MVP 19
heute habe ich dann AD (1.1.1.8) und CP (6.4.0.8) beides auf neuste version, die strecke noch einmal neu aufgenommen und die ein wenig mit dem Editor Modus zu recht gerückt. Jedoch ohne Erfolg... trotzdem macht er immer noch das gleiche spiel... links, rechts, links, recht, links, rechts, links, recht...

Ich habe mich auch schon mit dem Willi über discord ausgetauscht und er hat mich schließlich an euch verwiesen...

In diesem video sieht man mein problem: https://www.youtube.com/watch?v=jM0D4GRzSE0

**Comment by Tensuko** [comment]
Neue Version ist unterwegs...

**Comment by Tensuko** [comment]
#7550
