### ISSUE TITLE
Abfahrer blockiert Drescher bei Wende

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#7560]
Hallo leute.
Habe seit neuestem das problem das der abfahrer den Drescher beim wenden blockiert.
Feldbearbeitung Dreschen ist Lands, 3-5 Runden. 
Der Drescher (Claas Lexion dlc) drischt die zweite Runde innen, der Abfahrer wird gleichzeitig gefüllt, 
Wenn der Drescher noch nicht leer, aber am Feldende ankommt, bleibt der Abfahrer kurz stehen, der Drescher beginnt die wende nach links,  gleichzeitig fährt der abfahrer aber etwas vor - in die wendebahn des Dreschers und die beiden kollidieren. Wenn der Abfahrer stehenbleiben oder etwas zurücksetzen würde wäre alles paletti.
Lg
Andreas

**Comment by andreasthu** [comment]
ja, klar
lg
andreas

**Comment by rohne83** [comment]
Zu diesem Thema hätte ich auch noch was. Und zwar wenn der Rendezvous-Point ziemlich am Beginn der nächsten Feldreihe liegt, kommt es nämlich ebenfalls recht oft vor, dass der Abfahrer sich dem Drescher in den Weg stellt:
![fsScreen_2021_10_14_16_09_40](https://user-images.githubusercontent.com/71030138/137491867-f04c0b0f-4587-466d-8566-4db084be6de6.png)
![fsScreen_2021_10_14_16_10_07](https://user-images.githubusercontent.com/71030138/137491917-a3801d73-e305-4134-9034-96f67a0e3b0d.png)
