### ISSUE TITLE
Combine running into overloaders

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/courseplay#7563]
updated to .09, issue persists. 
cannot ul log directly as txt, apparently is not allowed by github now? or too big? i put in zip.
[log.zip](https://github.com/Courseplay/courseplay/files/7356979/log.zip)
![20211015234940_1](https://user-images.githubusercontent.com/5993529/137574479-909dc42b-4c66-49e7-90f3-74d0ca3560b1.jpg)
![20211015234942_1](https://user-images.githubusercontent.com/5993529/137574480-a500b5d7-eb1f-40fb-a70f-77e98fe414fb.jpg)

**Comment by Tensuko** [comment]
I can't see what situation you are on....
Was it a pocket ?
Was it at the start or end of a turn ?

Just think about what ppl can see on your screenshots....

**Comment by Commissar0617** [comment]
ok, it's generally in a pocket. im not entirely sure why it's in a pocket in this situation, but basically, the over loader just doesn't back up far enough. in this case, the combine is set up for lands.

**Comment by Tensuko** [comment]
I am not sure how far we back up...
Also the check of there is still a driver missed.
Will have to investigate that.

**Comment by musicislife08** [comment]
Its usually not about how far they backup but how long the combine waits for the tractor to backup.  I found if you set the tractor to not shut off to save fuel its usually able to backup fast enough to get out of the way of the combine but only if its fairly empty.  the heavier the load the longer it takes to start backing up and the more likely the combine is to run into the tractor
