### ISSUE TITLE
Häcksler - Abfahrer

### ISSUE THREAD

**Issue by DrVirus666** [Courseplay/courseplay#7564]
Hallo Github-Team,

Ich habe mein AD auf Stand (1.1.1.8) gebracht. Und jetzt habe ich die ganze Zeit die Meldung "Big X 1180 Bremst ab auf Grund von Verkehr" stehen, er fährt zwar mit einem Abladefahrzeug weiter aber nur 5km/h statt 10. Wenn das Abladefahrzeug voll ist und wegfährt verschwindet die Meldung.
Vorher ist diese Meldung nur aufgekommen wenn der Abfahrer wirklich den Häcksler im Weg stand.
Habe mit Willi von AD schon geschrieben. Muss ich die Einstellungen jetzt ändern?
Grüße Mario

**Comment by DrVirus666** [comment]
![20211016185034_1](https://user-images.githubusercontent.com/76628989/137595842-b13e1cee-856c-472c-852e-669ff75de23f.jpg)

**Comment by Tensuko** [comment]
Und außerdem:
https://github.com/Courseplay/courseplay/releases

**Comment by DrVirus666** [comment]
Bei F5 passiert bei mir nichts.
Die Release-Datei hab ich jetzt runtergeladen und werde es aktualisieren.

**Comment by DrVirus666** [comment]
Ich habe wie immer den Häcksler per CP fahren und den Abfahrer per AD fahren. Bis Gestern hatte ich auch nie solche "Probleme".
Das eigenartige für mich ist ja, dass wenn ich im Häcksler der mit CP unterwegs ist langsamer fahre. Und wenn ich im Abfahrer sitze der mit AD fährt, ist die Geschwindigkeit normal. Fahre ich selber mit dem Häcksler und der Abfahrer ist mit AD unterwegs ist die Geschwindigkeit normal.
Hier die Abfahrer Kolli
![20211017175203_1](https://user-images.githubusercontent.com/76628989/137635036-28ddab53-e4d2-411e-b57a-6b95486488bf.jpg)
![20211017175208_1](https://user-images.githubusercontent.com/76628989/137635052-089bb2cd-1c86-4e2d-8a80-025c33a6d142.jpg)
![20211017175214_1](https://user-images.githubusercontent.com/76628989/137635054-e2e27e72-69bf-4b20-bd37-84da5a598553.jpg)

.

**Comment by Axel32019** [comment]
Hallo zusammen,
In AD hat sich da nichts geändert.
@Tensuko :
Bitte schaut Euch mal CombineAIDriver:isProximitySlowDownEnabled an:
--- Check the vehicle in the proximity sensor's range. If it is player driven, don't slow them down when hitting this
--- vehicle.
...
		self:debugSparse('human player in nearby %s not driven by CP so do not slow down for it', nameNum(vehicle))
		-- trust the player to avoid collisions
Ich beobachte die  Meldung nur wenn der Abfahrer nicht vom Anwender belegt ist.

**Comment by Tensuko** [comment]
Aber das haben wir auch ewigkeiten nicht angefasst, frag mich warum das nun auftaucht ?

**Comment by Tensuko** [comment]
Für den 19er nun nicht mehr...
22er wird dann um einiges anders werden gehe ich von aus...
