### ISSUE TITLE
Planen Funktionieren nicht auf Dedi-Server

### ISSUE THREAD

**Issue by LamaiK** [Courseplay/courseplay#7565]
V 6.4.0.9
Die im #7550 behobenen Probleme, welche im #6998 beschrieben wurden, funktionieren jetzt im SP  und MP spiel.
( SP hat ja auch schon vorher funktionert)
Spielt man auf einem Dedi-Server funktioniert auch alles bis auf die Planen, diese funktionieren nur bei einem Ladetrigger mit nur einem Filltype. Hat der Ladetrigger (z.B. Hofsilo) aber mehrere Filltypes zur auswahl funktioniert die Plane nicht mehr.
Die Planen der Anhänger öffnen sich korrekt unter dem Trigger nach der vorbeifahrt schliessen sie sich auch wieder, der Traktor bremst aber nicht ab und hält auch nicht an um das ladegut zu laden.
Ohne die Planen funktioniert der Verlad korrekt. (Die Planan, wie von Tensuko erwähnt,waren ja auch vorher schon ein Problem)

Es stehen jede menge Fehler in der Spieler-Log:
[info lp3409] Error: VehicleConfigurations:get() directionNodeOffsetZ
[info lp3409] Error: VehicleConfigurations:get() turnRadius

Scheinen aber von verschiedenen Fahrzeugen zu kommen.

Kann es sein das der Mod FS19_VehicleExplorer etwas damit zu tun hat?
Er wirft die Warnung in der ServerLog in Zeilen 636-638:
Warning (script): 'fileExists': Argument 1 has wrong type. Expected: String. Actual: Nil
..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (882): expectedType == Value::VoidType || expectedType == Value::ClassType
LUA call stack:

Hier beide Log Files.

[Server-log.txt](https://github.com/Courseplay/courseplay/files/7360209/Server-log.txt)
[Spieler-log.txt](https://github.com/Courseplay/courseplay/files/7360210/Spieler-log.txt)

**Comment by LamaiK** [comment]
Habe denn Startpunkt vorverlegt und denn Startpunkt weiter weg gesetzt, das Resultat ist aber das selbe.
[](https://workupload.com/start/VpGEnmKsX7V)
Auch mit dem Original Silo ist der Effekt der selbe.

**Comment by Tensuko** [comment]
Wir haben auf einem Dedi-Server probiert, das machen wir fast nur.

Und von Wegpunkte verschieben habe ich nichts gesagt.
Ich meinte den Traktor weiter weg vom Silo starten, so dass er ganz klar zum ersten mal zum Silo fährt.
Ansonsten mal eine Runde fahren lassen und schauen ob es dann geht.

**Comment by Tensuko** [comment]
Müsste eigentlich mit der aktuellen Version funktionieren.
Mache hier erstmal zu...

**Comment by LamaiK** [comment]
Hallo Tensuko, danke für deine/eure arbeit. Leider ist auf dem Server immer noch das gleiche Problem mit der Plane. 
Jetzt läd er zwar das Ladegut wenn die Plane zu beginn nicht zu ist, jedoch fährt er wieder durch (öffnen-schliessen der Plane ohne zu laden) wenn die Plane bei anfahrt geschlossen ist, gleich wie zuvor.
