### ISSUE TITLE
game freezes on CP start on some courses

### ISSUE THREAD

**Issue by dxcufgb** [Courseplay/courseplay#7566]
Sometimes when starting a generated course with multiple tools the entire game freezes.

Log Gist: https://gist.github.com/41a53d73a464cf81153cf647e48e0736

Course used to reproduce error: https://gist.github.com/dxcufgb/a838a5925b89b40e11bd895023558068

Recreated issue using the AGCO IDEAL 8T with the widest corn header (~12m) available in vanilla game.

map used:
https://www.modhoster.com/mods/project-niedersachsen-vierfach-map-fixed-final

courseplay (Version: 6.4.0.9)

**Comment by dxcufgb** [comment]
updated with entire logfile!

**Comment by Tensuko** [comment]
Game freeze is also unpatient sometimes.
But we also have a problem with workingWidth set to 0 at new Vehicles.
Might be the Issue here, but basically it does work fine.
