### ISSUE TITLE
Pa carregadeira nao descarrega no bga

### ISSUE THREAD

**Issue by Firmino1974** [Courseplay/courseplay#7567]
Nao estou conseguindo fazer a carregadeira descarregar no ponto de venda do BGA, coloquei a rota certa, ele vai carregado ate o local e nao descarrega, ja fiz igual ao post criado e nao deu certo, gostaria de ajuda. obrigado

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki
