### ISSUE TITLE
in a four-spreader route, 2 right skips the hadland land leaves area unworked

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/courseplay#7577]
[log.txt](https://github.com/Courseplay/courseplay/files/7406668/log.txt)
in a four-spreader route, 2 right skips the hadland and leaves areas unworked int he field. been doing this for a while.
it's weird tho, it works fine in a four course with my combines, just the spreaders ahve issues. 

![20211024202905_1](https://user-images.githubusercontent.com/5993529/138622095-a8015474-ec53-4f8c-b3bc-da94adcad39c.jpg)
![20211024203116_1](https://user-images.githubusercontent.com/5993529/138622099-a71dba44-2b7b-4e6b-a88e-4819195dc394.jpg)
![20211024204116_1](https://user-images.githubusercontent.com/5993529/138622484-584c9762-4e56-439b-b242-46151fce39b4.jpg)
![20211024204028_1](https://user-images.githubusercontent.com/5993529/138622486-6b728512-fda9-45d5-a350-e476abef79ca.jpg)

**Comment by Clipless** [comment]
Just FYI, I have seen same issue with combines on some (but not all) fields when running more than 3.

**Comment by Tensuko** [comment]
Reason here should be the course.
Try 2nd Headland.
3 Combines or more also does work fine, as I said, the course might be the Problem.

**Comment by Tensuko** [comment]
We try to make sure that it works better for FS22. Will see how we get it running for that.
