### ISSUE TITLE
'loadSharedI3DFileFinished' - toolManager.lua:570: attempt to index field 'shovelNodes' (a nil value)

### ISSUE THREAD

**Issue by CGPandaX** [Courseplay/courseplay#7578]
toolManager.lua:570: attempt to index field 'shovelNodes' (a nil value)
A new error field was rediscovered in version 6.4.10, which did not appear in the previous version. This error will lead to failure to load the archive[](url)
[log.txt](https://github.com/Courseplay/courseplay/files/7406732/log.txt)

**Comment by Gonimy-Vetrom** [comment]
Unfortunately, the problem remains. In my case, this is the FS19_lsfmFarmEquipmentPack. If I delete it, then there are no errors.

**Comment by Gonimy-Vetrom** [comment]
Oops. In the last update, for some reason, there is no this string again
569 `and object.spec_shovel.shovelNodes and object.spec_shovel.shovelNodes[1]`

And with this change works fine! Thanks.

**Comment by Tensuko** [comment]
Will add the fix to release soon.
Thanks for testing and feedback :)
