### ISSUE TITLE
Problem mit mode5

### ISSUE THREAD

**Issue by steven1134** [Courseplay/courseplay#7583]
hey hab ein Problem hab mir  die neuste Version von Cp runtergeladen nun habe ich nach einmalig speichern und das spiel neu laden das Problem das das savegame nicht mehr zu ende geladen wird und in log am ende steht das in mans/lkws mode5 geladen wird obwohl dies ja keine ernte Maschinen sind oder Geräte zur Feld Arbeit angekoppelt sind
![fsScreen_2021_10_28_14_49_47](https://user-images.githubusercontent.com/62439666/139258461-d9eefe8c-f8a1-47b0-8c00-03a7ff346f94.png)
 
[log.txt](https://github.com/Courseplay/courseplay/files/7434141/log.txt)

**Comment by Tensuko** [comment]
Sollte kein Problem sein, mache hier zu...
