### ISSUE TITLE
CP Fehler auf SERVER File count per store item too high. 155 found (max. 128)

### ISSUE THREAD

**Issue by Hackl90** [Courseplay/courseplay#7587]
Moin,

Ich versuche gerade CP auf einem Nitrado Server zum laufen zu bringen 
Ich lade die V 6.4.0.0 (oder die neueste ist egal selber Fehler) dann steht da der Mod hat einen Fehler : 
File count per store item too high. 155 found (max. 128)

Ich kann CP zwar aktivieren aber wenn ich das spiel lade wird CP nicht in der Modliste die man benötigt angezeigt obwohl der mod auf dem Server Aktiviert wurde.

Es wurden alle anderen Mods vom Server genommen der Fehler besteht leider weiterhin.

gibt es hierfür zufällig schon eine Lösung oder jemanden mit dem selben Problem ?

Schönen Gruß

![Screenshot 2021-10-29 215751](https://user-images.githubusercontent.com/57861614/139494649-b8c04091-af3a-4f4d-857d-f87ef1eb1ea7.png)

**Comment by Tensuko** [comment]
Wir haben CP auch auf Nitrado laufen und keine Probleme.
An CP liegt das jedenfals nicht!

Logfiles ?

**Comment by Hackl90** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/7446370/log.txt)
Das Ist die Log vom Spiel
Wenn ich ein Einzelspieler spiel starte geht CP ohne Probleme

Es ist  jetzt auf dem Spiel und dem Server nur noch CP drauf und das spiel auf der Ravenport gestartet also keinerlei mod's die Ärger machen könnten oder Übersehe ich das etwas ?
schon mal danke für die Hilfe

**Comment by Tensuko** [comment]
Ich verstehe nur nicht was jetzt nicht funktioniert ?
Weil den Bildschirm den du mir da zeigst, der macht halt nichts.... Jedenfals haben wir da nicht.

**Comment by Hackl90** [comment]
Wenn ich jetzt den LS starte und das spiel vom Server öffne erscheint kein CP obwohl es ja Aktiviert ist es erscheint nicht einmal in der liste der benötigten mods 
entpackt habe ich nichts so wie runtergeladen in den modordner geschoben 
wenn ich in das spiel reingehe ist es als wäre cp nicht installiert...

**Comment by jason0611** [comment]
CoursePlay ist auf dem Screenshot nicht aktiviert, daher kann es gar nicht im Spiel angezeigt werden. 
Die Aktivierung erfolgt auf der Seite "Home".

**Comment by LamaiK** [comment]
Das ist kein CP Fehler. So wie ich das Verstehe ist das bei allen Dedi-Server Spielen der fall, der Server hat eine limitierung von 128 Scripte pro Mod, er gibt dies zwar als Fehler aus macht aber nichts weiter damit. 
Wir haben das auf jedem Dedi-Server.

Eigentlich dachte ich dass das bei euch @Tensuko/ DevTeam bekannt sein müsste.

**Comment by Hackl90** [comment]
Ok vielen Dank für die Info dann liegt es also nicht an cp.
Nur leider noch nicht die Lösung aber echt gediegen, dass alle anderen mods die wir so drauf hatten gehen und nur cp tut so als wäre es gar nicht vorhanden obwohl ich auf dem server als auch im spiel genau die selben cp Versionen brav als zip verpackt so wie sie heruntergeladen wurden drauf habe und natürlich auch aktiviert 🤔
Aber trotzdem danke Fir die Infos
Gruß

**Comment by jason0611** [comment]
Wenn der Screenshot zu Beginn nicht lügt, ist es wirklich ein Fehler von CP.
<img width="776" alt="image" src="https://user-images.githubusercontent.com/12356451/139543673-8c29c537-5e19-4814-bb03-3a1ee0617a4a.png">

**Comment by Tensuko** [comment]
@jason0611 gut gesehen.

**Comment by Hackl90** [comment]
Moin also nochmal 
natürlich ist der Mod aktiviert
![aktiv1](https://user-images.githubusercontent.com/57861614/139581940-9648bb88-1f10-40ec-8c71-63c2990caf4c.PNG)
![aktiv2](https://user-images.githubusercontent.com/57861614/139581949-e535ea2b-f266-4388-a808-bd5f43b8d2f1.PNG)

unn der Server ist aktiviert 
dann gehe ich ins Spiel auf Multiplayer-> spiel Beitreten ->Deutschland-> dann sehe ich das Spiel gehe ich hier auf details werdne keinerlei mods angezeigt obwohl cp ja aktiv ist ... 
![aktiv3](https://user-images.githubusercontent.com/57861614/139582070-ff2af432-0b6b-428c-a6ad-34c203691cde.PNG)
ich hoffe ihr versteht jetzt was ich meine mit allen anderen mods funktioniert es.

**Comment by Hackl90** [comment]
Moin,
Ich habe jetzt mal ein normales Multiplayer spiel direkt vom Rechner aus gestartet, hier funktioniert CP ohne Probleme.
also wird es wohl an dem Nitrado Server liegen und nicht an CP.
Trotzdem danke an die ,die tipps gegeben haben.
