### ISSUE TITLE
Mode9 (and others) cause Memory Overflow when workWidth is 0

### ISSUE THREAD

**Issue by themgun** [Courseplay/courseplay#7588]
Whenever i start a course and get out of that tractor it freezes my player until i stop the driver, please help!
[log.txt](https://github.com/Courseplay/courseplay/files/7444900/log.txt)

All of the mods with errors i have had before this issue started.

**Comment by Papa-Scherzkeks** [comment]
take a look in the log, there are 17 error messages from mods that have either been given different names or are not compatible.

**Comment by themgun** [comment]
> take a look in the log, there are 17 error messages from mods that have either been given different names or are not compatible.

ok ill take a deeper look and see if it solves the problem

**Comment by themgun** [comment]
i got rid of all the mods i got since this issue started and its still doing it

**Comment by franky-bb** [comment]
Das habe ich auch. Liegt an v6.4.1.1. Bin wieder zurück auf v6.4.0.9 und siehe da, kein einfrieren mehr.

**Comment by Hurri85** [comment]
> Das habe ich auch. Liegt an v6.4.1.1. Bin wieder zurück auf v6.4.0.9 und siehe da, kein einfrieren mehr.

Ging mir am Donnerstag auch so. Immer wenn ich das Silo entladen wollte sofort Spiel eingefroren!

**Comment by Tensuko** [comment]
'Immer wenn ich das Silo entladen wollte'

Kann das mal jemand genauer beschreiben ?
Welches Silo ?
Welcher Modus ?
usw usw

Ansonsten kann man da auch nichts machen!

**Comment by Tensuko** [comment]
> Whenever i start a course and get out of that tractor it freezes my player until i stop the driver, please help!

'please help!'

That 2 words won't help you anything.
The only thing that helps is details!
What Course ? Any Course ?
What Tractos ?
Maybe a screenshot ?

Log is not complete!
If you start e.g. Mode6 far away from 1st Waypoint and want to start on 1st Waypoint that the Pathfinder is working!

**Comment by Hurri85** [comment]
Sry für die nicht sehr hilfreiche Antwort.

Also Mode 9 ( zweite von Rechts)
Fahrzeuge: JD 6R mit Frontlader und Claas Torion 1914
Map: County Line
Silos : große Keil Silos von Feds Mod mit 8 mio Fassungsvermögen und die fest verbauten Silos von der Karte mit 1.4 mio Fassungsvermögen.

Ls19 Version 1.7.1

Fehler Beschreibung: Den Silo Kurs zum entladen auswählen geht noch,. Soll bald man vor dem Startpunkt steht und Helfer einstellen drückt, steht alles und nichts geht mehr.

**Comment by Tensuko** [comment]
> Fehler Beschreibung: Den Silo Kurs zum entladen auswählen geht noch,. Soll bald man vor dem Startpunkt steht und Helfer einstellen drückt, steht alles und nichts geht mehr.

Davon das logfile um zu sehen ob da ein Error aufkommt. Das wäre wichtig.

**Comment by franky-bb** [comment]
Das Problem kann man nicht einer Map, einem Fahrzeug usw. zuordnen. Das das Spiel einfriert kommt spontan. Ich glaube, so ca. 5min nach dem Start, wenn man schon einige CP Fahrer eingestellt hat. Hatto sogar so einen Bing Ton mitbekommen, danach war s eingefroren. Der Taskmanager zeigt dann volle Speicherauslastung an. 95-98%. Man kann sich dann nur abmelden.

**Comment by Tensuko** [comment]
Ohne Error im Logfile, keine Chanze was dran zu machen.

**Comment by Hurri85** [comment]
Ich habe mal nur die letzten Zeile genommen. Weil darüber steht bloß der ganze Standard Kram von LS, GC etc...

2021-10-30 12:22   Info: [AD] Info: g_server table: 0x01c53fa9a430 g_client table: 0x01c53fa9c2b8 g_dedicatedServerInfo nil getUserProfileAppPath C:/Users/*****/Documents/my games/FarmingSimulator2019/ getIsClient true getIsServer true isMasterUser true
2021-10-30 12:22 Lua memory usage has reached 330101 KB; this is a dangerous level for consoles.
2021-10-30 12:23 data/shared/ai/trafficCollision.i3d (1.30 ms)
2021-10-30 12:23 :05 [info lp1869] CLAAS TORION 1914 (#1): AI driver in mode 9 starting at 168/168 waypoints (COURSEPLAY_FIRST_POINT)
2021-10-30 12:23 Warning: Performing emergency garbage collection pass - memory went from 227772 KB to 457284 KB in less than one frame
2021-10-30 12:23 Usage is now 457270 KB; full GC took 231.974400ms 
2021-10-30 12:23 Warning: Performing emergency garbage collection pass - memory went from 457270 KB to 914895 KB in less than one frame
2021-10-30 12:23 Usage is now 914894 KB; full GC took 375.002500ms 
2021-10-30 12:23 Warning: Performing emergency garbage collection pass - memory went from 914894 KB to 1830146 KB in less than one frame
2021-10-30 12:23 Usage is now 1830145 KB; full GC took 641.363900ms 
2021-10-30 12:23 Warning: Performing emergency garbage collection pass - memory went from 1830145 KB to 3660647 KB in less than one frame
2021-10-30 12:23 Usage is now 3660647 KB; full GC took 1188.931700ms 
2021-10-30 12:23 Warning: Performing emergency garbage collection pass - memory went from 3660647 KB to 7321652 KB in less than one frame
2021-10-30 12:23 Usage is now 7321652 KB; full GC took 2320.652200ms 
2021-10-30 12:24 Warning: Performing emergency garbage collection pass - memory went from 7321652 KB to 14643661 KB in less than one frame
2021-10-30 12:24 Usage is now 14643661 KB; full GC took   ##4552.837500ms

**Comment by Tensuko** [comment]
Ohne Error im Logfile, keine Chanze was dran zu machen.

**Comment by Hurri85** [comment]
> Ohne Error im Logfile, keine Chanze was dran zu machen.
[log.txt](https://github.com/Courseplay/courseplay/files/7446361/log.txt)

**Comment by franky-bb** [comment]
Hab eben mit nochmals die neueste CP Version rein gemacht. und siehe da, wieder eingefroren. In der Log ist kein ERROR Eintrag drin. Das sind die letzten Zeilen:

2021-10-30 13:23 Warning: Performing emergency garbage collection pass - memory went from 453799 KB to 907727 KB in less than one frame
2021-10-30 13:23 Usage is now 907726 KB; full GC took 488.020500ms 
2021-10-30 13:23 Warning: Performing emergency garbage collection pass - memory went from 907726 KB to 1815652 KB in less than one frame
2021-10-30 13:23 Usage is now 1815652 KB; full GC took 867.617300ms 
2021-10-30 13:23 Warning: Performing emergency garbage collection pass - memory went from 1815652 KB to 3631566 KB in less than one frame
2021-10-30 13:23 Usage is now 3631565 KB; full GC took 1557.896200ms 
2021-10-30 13:24 Warning: Performing emergency garbage collection pass - memory went from 3631565 KB to 7263392 KB in less than one frame
2021-10-30 13:24 Usage is now 7263392 KB; full GC took 2991.658600ms 
2021-10-30 13:25 Warning: Performing emergency garbage collection pass - memory went from 7263392 KB to 14527046 KB in less than one frame

**Comment by Tensuko** [comment]
@Hurri85 
Du hast Callstacks mit GlobalCompany und diversen anderen Mods.
Da wundert es micht nicht, wenn es Probleme gibt...

Was den Mode9 betrifft, kein Plan wie dein Kurs aussieht.
Wo er steht wenn die Meldung kommt.

@franky-bb 
auch für dich gillt, logfile!

**Comment by Tensuko** [comment]
Version könnt ihr selber sehen im HUD, läuft ohne die Meldung.
Was versucht ihr denn zu befüllen ?

![fsScreen_2021_10_30_14_00_57](https://user-images.githubusercontent.com/27344744/139532115-4c668602-4be6-4805-8605-45a779a9bb20.png)
![fsScreen_2021_10_30_14_01_23](https://user-images.githubusercontent.com/27344744/139532112-a788300a-dd24-4845-9414-d6f79f2e9705.png)
![fsScreen_2021_10_30_14_01_57](https://user-images.githubusercontent.com/27344744/139532109-c82dd437-fc09-4d9a-8614-6c95120e504f.png)

**Comment by Papa-Scherzkeks** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/7446602/log.txt)
ich gebe mal die log vom Server ,vielleicht hilft die ja.

**Comment by Tensuko** [comment]
Aha, Server! Das ist ja schon mal ein wichtiger Hinweis.

**Comment by Hurri85** [comment]
Also ich habe jetzt nochmal die letzten Stunden getestet. Zum Schluss habe ich mein Spielstand "nur" noch mit Courseplay gestartet und sofort Spiel eingefroren. 

Der Kurs ist wie Du es im Tutorial erklärt hast.

![fsScreen_2021_10_30_16_21_27](https://user-images.githubusercontent.com/86884885/139536978-95d341b7-6fd8-4c14-ac42-c4f11cdb3b2b.png)

**Comment by Tensuko** [comment]
@Hurri85 und das ist jetzt bei dir auf dem MP Server ?

**Comment by franky-bb** [comment]
Version 6.4.1.0 funktioniert. Bei Version 6.4.1.1 friert das Spiel ein. Für mich ist das eindeutig ein CP Problem. Wäre es nicht einfacher, die Änderungen, die man gemacht hat nochmals durchzuschauen. Bitte fühlt euch nicht auf den Schlips getreten. Ihr macht eine super Arbeit. Mittlerweile ist es das beste CP aller Zeiten.

**Comment by Tensuko** [comment]
Da, kannst du selber nachgucken, was die Änderung von 6.4.1.0 auf 6.4.1.1 ist:

https://github.com/Courseplay/courseplay/commit/901b6a6eea3bd825b510772ed6105da7ff4eaed2

Kleiner Hinweis, es hat etwas mit dem 90° Turn für Mode4 und Mode6 im Vorgewende zu tun, mehr nicht.

**Comment by Hurri85** [comment]
Bei mir ist es im Singleplay. Also mit sofort eingefroren meinte ich, wenn ich den Helfer einstelle.

Ich kann mich Franky nur anschließen. Zum Thema eure Arbeit und Bestes CP aller Zeiten. Kleine neben Frage wird eigentlich CP bei LS22 sofort verfügbar sein oder dürft ihr erst anfangen wenn es raus kommt? Weil wenn sowieso in 4 Wochen LS22 kommt und CP da ist. Dann spiele ich die nächsten Wochen einfach mit 6.4.0.9 weiter und gut ist. Und wir sparen und uns alles etwas Freizeit.  ;)

**Comment by Tensuko** [comment]
Wir wollen CP für den 22er bringen, nur wann steht in den Sternen, da wir auch nicht wissen, wie wo wann was im 22er mit Helfern passiert.

Und wenn es bei dir im SP ist, ist es also was allgemeinst, aber bei dem hin und her blickt man ja auch nicht mehr durch....
Bei dem einen gehts in der 6.4.0.9, beim nächsten in der 6.4.1.0 und bei mir in der 6.4.1.1 so damit können wir halt nichts anfangen....

Benutzen denn ALLE Mode9 wenn das passiert und ALLE einen Traktor mit Frontlader ?

**Comment by Hurri85** [comment]
Sry für das ganze Durcheinander, bin auch nicht ganzen Tag drauf gekommen die 6.4.1.0 zu testen. Die geht auch bei mir.
Also nochmal kurz und zusammengefasst:
- Singleplayer
- Mode 9
- Frontlader oder Radlader gleiches Problem
- 6.4.1.0 geht.

**Comment by Tensuko** [comment]
Ok Danke.
Warum die 6.4.1.1 nicht geht, kann ich mir aber Null erklären....
Müssen wir untersuchen.

**Comment by timmi4026** [comment]
> > Das habe ich auch. Liegt an v6.4.1.1. Bin wieder zurück auf v6.4.0.9 und siehe da, kein einfrieren mehr.
> 
> Ging mir am Donnerstag auch so. Immer wenn ich das Silo entladen wollte sofort Spiel eingefroren!

Hatte ich mit der 6.4.10 und 11 Speicherüberfüllung und der Server bleibt stehen.

**Comment by timmi4026** [comment]
> Wir wollen CP für den 22er bringen, nur wann steht in den Sternen, da wir auch nicht wissen, wie wo wann was im 22er mit Helfern passiert.
> 
> Und wenn es bei dir im SP ist, ist es also was allgemeinst, aber bei dem hin und her blickt man ja auch nicht mehr durch.... Bei dem einen gehts in der 6.4.0.9, beim nächsten in der 6.4.1.0 und bei mir in der 6.4.1.1 so damit können wir halt nichts anfangen....
> 
> Benutzen denn ALLE Mode9 wenn das passiert und ALLE einen Traktor mit Frontlader ?

Bei mir ist es passiert mit dem Radlader als ich testen wollte ob er diesmal geht, Hab Abfahrer eingestellt und alles ist stehen geblieben. Server Log hatte Speicher overflow in diversen Bereichen. musste den Dedic stoppen.

**Comment by timmi4026** [comment]
> Ich habe mal nur die letzten Zeile genommen. Weil darüber steht bloß der ganze Standard Kram von LS, GC etc...
> 
> 2021-10-30 12:22 Info: [AD] Info: g_server table: 0x01c53fa9a430 g_client table: 0x01c53fa9c2b8 g_dedicatedServerInfo nil getUserProfileAppPath C:/Users/*****/Documents/my games/FarmingSimulator2019/ getIsClient true getIsServer true isMasterUser true 2021-10-30 12:22 Lua memory usage has reached 330101 KB; this is a dangerous level for consoles. 2021-10-30 12:23 data/shared/ai/trafficCollision.i3d (1.30 ms) 2021-10-30 12:23 :05 [info lp1869] CLAAS TORION 1914 (#1): AI driver in mode 9 starting at 168/168 waypoints (COURSEPLAY_FIRST_POINT) 2021-10-30 12:23 Warning: Performing emergency garbage collection pass - memory went from 227772 KB to 457284 KB in less than one frame 2021-10-30 12:23 Usage is now 457270 KB; full GC took 231.974400ms 2021-10-30 12:23 Warning: Performing emergency garbage collection pass - memory went from 457270 KB to 914895 KB in less than one frame 2021-10-30 12:23 Usage is now 914894 KB; full GC took 375.002500ms 2021-10-30 12:23 Warning: Performing emergency garbage collection pass - memory went from 914894 KB to 1830146 KB in less than one frame 2021-10-30 12:23 Usage is now 1830145 KB; full GC took 641.363900ms 2021-10-30 12:23 Warning: Performing emergency garbage collection pass - memory went from 1830145 KB to 3660647 KB in less than one frame 2021-10-30 12:23 Usage is now 3660647 KB; full GC took 1188.931700ms 2021-10-30 12:23 Warning: Performing emergency garbage collection pass - memory went from 3660647 KB to 7321652 KB in less than one frame 2021-10-30 12:23 Usage is now 7321652 KB; full GC took 2320.652200ms 2021-10-30 12:24 Warning: Performing emergency garbage collection pass - memory went from 7321652 KB to 14643661 KB in less than one frame 2021-10-30 12:24 Usage is now 14643661 KB; full GC took ##4552.837500ms

Genau das steht bei mir auf dem Server auch und alle paar Sekunden kommt eine Zeile dazu mit höheren Werten

**Comment by lgxxxxx** [comment]
Hello and thank you for the amazing work you do. In the last three versions there is a problem with mode 10 similar to mode 9. In many cases, after starting the silage compactor, the game freezes and has to be closed with the task manager. Warning: Performing emergency garbage collection pass - memory went from ...
There is no such problem in version 6.4.0.9. I enclose two log files with version 6.4.0.9 and 6.4.1.2.
I also wanted to ask when moving in the silo whether it is possible for the instruments not to be lifted after reaching the end of the silo but when leaving the silo to wait for unloading.
Sorry for my bad English.
Thank you for your hard work once again
[log_last.txt](https://github.com/Courseplay/courseplay/files/7490544/log_last.txt)
.
[6.4.0.9.log](https://github.com/Courseplay/courseplay/files/7490545/6.4.0.9.log)
![1](https://user-images.githubusercontent.com/11899013/140611792-8a6fc51d-50e0-40e1-bf23-49f1cb9dd00d.jpg)

**Comment by Tensuko** [comment]
I am creating a testsave already to see if I can get that to reproduce it in any way...

**Comment by Tensuko** [comment]
I was able to reproduce it, the problem is, after game restart.... it simply does work....

**Comment by Tensuko** [comment]
I am pretty sure, the Problem comes from the workWidth, wich is 0 when you start the Driver for the 1st time.
We did some changes there, maybe missed that.
Try it by adjust your working width before start the driver.

**Comment by lgxxxxx** [comment]
After various tests, I confirm that this is the problem. Thanks for the quick response :)

**Comment by Hurri85** [comment]
Mit 6.4.1.2 scheint es wieder zu laufen. Und die Arbeitsbeite wird bis jetzt richtig angezeigt.
Danke

**Comment by Tensuko** [comment]
> 
> 
> Mit 6.4.1.2 scheint es wieder zu laufen. Und die Arbeitsbeite wird bis jetzt richtig angezeigt. Danke

Wie bereits gesagt, das hat nichts mit der 6.4.1.2 zu tun, es lag am einfachen neustart des spiels bei dem die Breite richtig inizialisiert wurde. Jetzt mit der 6.4.1.3 ist es gefixt.

**Comment by Achimobil** [comment]
Ich hab es bei mir getestet in dem Spielstand aus dem ich das gemeldet hatte und mit der 6.4.1.3 ist es bei mir gefixed. Danke
