### ISSUE TITLE
how do I empty the washing machine with courseplay ??

### ISSUE THREAD

**Issue by landtools** [Courseplay/courseplay#7590]
I have a question for you to understand how to set up the courseplay. Basically, I bought a potato washing machine and set the drain point of the washing machine .... up to this point it's ok ... now, how do I empty the washing machine with courseplay and go to unload at the point of sale ??

**Comment by Tensuko** [comment]
The trigger have to be between stop and start waypoint, just like every Mode1 course that unloads at a trigger.

**Comment by landtools** [comment]
![Senza titolo](https://user-images.githubusercontent.com/71590173/139651308-5bfd879c-45dd-47d3-a1e8-493d26ad9a01.png)  
Where am I doing wrong ??

**Comment by tn4799** [comment]
The trigger where you load your washed potatos has to be between the start and the stop point. Thats your mistake.

**Comment by Tensuko** [comment]
That is not working!
One Mashine at the time only and the start and stop must be at the loading, not unloadpoint.
Check regular Tutorials for Mode1 Basics.
