### ISSUE TITLE
Turns mit Drescher mit Lands

### ISSUE THREAD

**Issue by eric4072** [Courseplay/courseplay#7596]
Hallo! 

Wenn ich bei dem Drescher die Option Lands benutze, habe ich bei manchen Felder das Problem, dass der Drescher beim umsetzen in die nächste Reihe nicht den Kurs des Vorgewende benutzt sondern er mit zwei 90 Grad Drehungen auf die neue Reihe dreht. Bei "nicht rechtwinkligen Feldern" verlässt er dadurch teilweise das Feld und bleibt an Bäumen hängen. Stell ich hier was falsch ein?
beim wechseln von Reihen auf Vorgewende oder andersherum fährt er ja auch von alleine auf dem Vorgewendekurs...

LG Eric

translated via google:
Hello! If I use the Lands option on the thresher, I have the problem with some fields that the thresher does not use the course of the headland when it is transferred to the next row, but instead turns with two 90 degree turns to the new row. In the case of "non-rectangular fields", it partially leaves the field and gets stuck on trees. Am I setting something wrong here? when changing from rows to headlands or the other way around, it drives on its own on the headland course ... LG Eric

**Comment by Tensuko** [comment]
Erweiterte Optionen, Benutze Pathfinder im Wendemanöver auf aktiviert stellen.

**Comment by eric4072** [comment]
ist an...
