### ISSUE TITLE
Bourgeault Harrow XR770 bearbeitet Ecken nicht vollständig

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#7598]
Hallo Leute
habe gerade festgestellt das der Bourgeault 27m Striegel scharfe Ecken nicht vollständig bearbeitet:
der Kurs:
![fsScreen_2021_11_02_11_37_01](https://user-images.githubusercontent.com/24860501/139831721-52f892a7-ca62-4822-bd20-a554ee358cb9.png)

hier das Eckenverhalten:
![fsScreen_2021_11_02_11_30_54](https://user-images.githubusercontent.com/24860501/139831923-c2d7f9df-b157-4534-82e8-c1f1eac9bf73.png)
![fsScreen_2021_11_02_11_30_57](https://user-images.githubusercontent.com/24860501/139831937-31df878e-6224-430e-8b38-7755fa91456e.png)
![fsScreen_2021_11_02_11_31_00](https://user-images.githubusercontent.com/24860501/139831953-34ae54c0-e7b9-4f32-bbbe-1a197409ad81.png)
![fsScreen_2021_11_02_11_31_14](https://user-images.githubusercontent.com/24860501/139831988-67f81d1e-42a8-4609-b54b-5052501545de.png)
![fsScreen_2021_11_02_11_31_19](https://user-images.githubusercontent.com/24860501/139831999-8a6393f7-3938-493c-8995-616d4ea4c3d9.png)

![fsScreen_2021_11_02_11_31_24](https://user-images.githubusercontent.com/24860501/139832017-db1771cc-3db2-4dd9-877d-82c26b49b1ef.png)
hier sieht man das der Traktor nicht bis zum Feldrand zurücksetzt, sondern schon vorher stoppt, absenkt und das Eck damit nicht bearbeitet wird

![fsScreen_2021_11_02_11_33_55](https://user-images.githubusercontent.com/24860501/139832151-4fd0f188-1995-4322-99ff-10e6d85efd1b.png)
(pda map)

lg
andreas

**Comment by Tensuko** [comment]
log ?
Version ?
Tool anheben/senken Einstellung ?

**Comment by andreasthu** [comment]
hier die log:
[log.txt](https://github.com/Courseplay/courseplay/files/7460267/log.txt)

cp 6.4.1.1, die vom github hier.
anheben: spät,
absenken spät & früh - beides probiert immer dasselbe

hab gerade festgestellt, das es mit dem Bredal K165 Düngerstreuer dasselbe ist:
![fsScreen_2021_11_02_12_41_45](https://user-images.githubusercontent.com/24860501/139840140-41b957b3-fb16-4726-9e5c-8586a8fedd45.png)
![fsScreen_2021_11_02_12_42_03](https://user-images.githubusercontent.com/24860501/139840148-17eb59d9-2936-47b0-8230-52796082b4be.png)

und hier noch der Düngerkurs:
[courseStorage0015.xml.txt](https://github.com/Courseplay/courseplay/files/7460318/courseStorage0015.xml.txt)

lg
andreas

**Comment by Tensuko** [comment]
@schwiti6190 
workWidth Einfluss vlt ?
