### ISSUE TITLE
Bale Collector Mode Should Be Able to Use an Edge Path

### ISSUE THREAD

**Issue by KAmaia** [Courseplay/courseplay#7599]
I want to start this Feature Request by saying that I absolutely love the bale collector mode, not having to manually pickup bales from a field is a god send.  

That said, I also do a lot of wild-grass work, and unfortunately wildgrass does not have a field number that can be associated with it.  

As such, it would be super amazing if we could load a field edge path as an alternative method for loading a  'field', so that bale collection would work for both fields and wildgrass.  

I will post a screen shot of what I mean when I get back to my gaming rig after work tonight.  

Keep up the good work on this mod though guys, I love what we're able to do with it!

**Comment by Mike1977** [comment]
I would like to upvote this request, because its an issue that bothers me too.
