### ISSUE TITLE
Waypoints are invisible (complicated to make visible)

### ISSUE THREAD

**Issue by critterios** [Courseplay/courseplay#7600]
Since Version 6.4.0.6 i can't show the waypoints anymore with the "Eye"-Icon, only in the menu which is a bit complicated.
If there is an option to let the eye-icon not only show the "map" but also the waypoints, then that option is too hidden.

**Comment by TobiHH78** [comment]
https://github.com/Courseplay/courseplay/issues/7537

**Comment by Tensuko** [comment]
That eye was never ever at any time to show the course.
It have always been the 3 dots on the settings page!
Even back in the days of FS17!

**Comment by critterios** [comment]
Mhm, a pity. If that was never meant to be a feature, then it should be made into one.
Does not matter, i still use courseplay, just not anything over 6.4.0.6
