### ISSUE TITLE
Courseplay convertierer ? 

### ISSUE THREAD

**Issue by iceman234de** [Courseplay/courseplay#7601]
Hallo, 

Wollte mal fragen ob es ein convertierer gibt der alte kurformate in das neue format umwandelt ? 

Hatte bis vor kurzem noch mit der version 6.1.366 gespielt und gestern die aktuellste version geladen vom courseplay , ist ja schon einiges passiert seither , hut ab leute , macht nen super job , nur hab ich festegesrellt das die neuere version die kurse in einem anderen firmat abspeichert als die älteren versionen vom courseplay. 

Drum meine frage. 

Gruß und weiter so jungs 

iceman

**Comment by Tensuko** [comment]
Du musst in der Konsole cpUpgradeAllCourses eintippen.
Dann dauert es eine weile, je nach Anzahl der Kurse und Größe der Kurse.
Danach sind deine Kurs im neuen Format.
Neue Kurse werden natürlich gleich im neuen Format gespeichert.

**Comment by iceman234de** [comment]
Dankeeeeee😁😁👍👍🍻🍻-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 05.11.21, 19:38 schrieb Tensuko ***@***.***>:

   
  Du musst in der Konsole cpUpgradeAllCourses eintippen. Dann dauert es eine weile, je nach Anzahl der Kurse und Größe der Kurse. Danach sind deine Kurs im neuen Format. Neue Kurse werden natürlich gleich im neuen Format gespeichert.
