### ISSUE TITLE
Saatgut manuell befüllen geht nicht 

### ISSUE THREAD

**Issue by iceman234de** [Courseplay/courseplay#7605]
Hallo, 

Mir ist eben aufgefallen , das ich mein Saatgutanhänger  Meridian SeedExpress 1260 nicht mehr manuell befüllen kann , nur noch per CP ( ver 6.4.1.1) 

[log.txt](https://github.com/Courseplay/courseplay/files/7490824/log.txt)

Gruß Andy 

https://m.youtube.com/watch?v=vhYrsM-36Yg&t=6s

**Comment by Tensuko** [comment]
#7531

**Comment by iceman234de** [comment]
Ahm, will ja nicht meckern oder unhöflich sein , aber die verlinkung da schreibt der das es per CP nicht geht , bei mir ist es grad anderstrum  , will ja selbst den anhänger befüllen nicht mit CP
