### ISSUE TITLE
Issue with fields in bale collector mode

### ISSUE THREAD

**Issue by KAmaia** [Courseplay/courseplay#7613]
For starts, I use courseplay in conjunction with CollectStrawAtMissions to maximize mission profit.

The issue is that while the mission is in the active state the bale collector can see the field in it's field ID list.  However once the mission has gone to the complete state, but is NOT yet turned in/collected, the field ID is removed from the courseplay 'accessible fields' list.  Which prevents the auto collection of bales from that field. 

However, if bale collection is started *prior* to the change from the contract going from 'Active' to 'Complete' the field continues to show up in the selectable fields list unless you change the field.  

Can the field list be made to show all fields regardless of contract status, or some other fix be devised?   If you can give me an idea where in the code base to look, I'd be willing to take a peak and see what I can do.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by KAmaia** [comment]
As soon as I have a contract available I will post logfile and save games.

**Comment by KAmaia** [comment]
So here is the pre and post complete save games and log files.  If you load the pre-complete you'll see that the bale collector can access field 11, however, post completion, but pre-turn in, field 11 is no longer an option for Mode 7

**Comment by Tensuko** [comment]
Will have a look later.

**Comment by Tensuko** [comment]
Why on earth did you add also the mods ?
I don't load 2,6GB for nothing.
Post your logfile! And by that I mean drag and drop it here. or use pastebin.
