### ISSUE TITLE
Courseplay does not work

### ISSUE THREAD

**Issue by Jespertjuhhh** [Courseplay/courseplay#7618]
I can just start up a savegame normally, and when is press delete the menu pops up. But when I try to click any button in the Courseplay menu nothing happens, the only thing that happens is that the letters get blue when I go over them with my mouse. I have the latest version from github (6.4.1.3) Also no errors show up in the log.

**Comment by Tensuko** [comment]
Logfile!!!

**Comment by Jespertjuhhh** [comment]
Here it is, I know my specs are not so good, but I can play on medium graphics without shaders. Also, now the HUD doesn't even open anymore when i press delete, I checked if that was the key for opening the HUD and it was.
[log.txt](https://github.com/Courseplay/courseplay/files/7533778/log.txt)

**Comment by Jespertjuhhh** [comment]
Here it is, I know my specs are bad, but I can play medium graphics without shaders. Also the HUD now doesn't even open when I press delete, I checked if that was the right key in the esc menu and it was.
[log.txt](https://github.com/Courseplay/courseplay/files/7533784/log.txt)

**Comment by Jespertjuhhh** [comment]
Oh hello, I got it working again. Sorry for wasting your time, good luck with working on Courseplay.
Have a nice day!
