### ISSUE TITLE
Feature request: Pause driver - Fahrer pausieren

### ISSUE THREAD

**Issue by mwrsa** [Courseplay/courseplay#7619]
Hey there folks,
thank you for making and providing  courseplay, I can't play without it any more.

I'd wish for one more feature though, and I haven't found it yet so I am asking for it here.

Every once in a while I run into the issue of colliding vehicles in a field, e.g. using a rower and a loading wagon on the same course, but eventually they cross and collide.
I could often prevent this by using a simple "pause" button, resulting in one driver to just stop dead in its track without losing it. For now I have to stop the driver and then get it to resume in the same position, which is a pain in tight spaces or turning points.
Would that seem a good idea to you, and possible to do? Thank you.

Hallo Leute,

danke, dass ihr courseplay macht und einfach so anbietet. Ich spiele nicht mehr ohne!

Eine Option fehlt mir aber noch, und weil ich sie nirgends findenkonnte, schreibe ich euch hier.

Hin und wieder kollidieren bei mir Fahrzeuge auf dem Feld, bspw. ein Schwader und ein Ladewagen auf dem gleichen Kurs, aber irgendwann überschneiden sich die Fahrwege und die Fahrzeuge kollidoeren.
Ich könnte das manuell verhindern, wenn es einen simplen "Pause"-Knopf gäbe, der den entsprechenden Fahrer einfach an Ort und Stelle anhält, ohne dass er seinen Kusr verliert. Bisher muss ich immer den Fahrer stoppen und dann an der selben Stelle wieder aktivieren, das ist manchmal an engen Stellen oder Wendestellen ein elender Krampf.
Was haltet ihr von der Idee, wäre das umsetzbar? Danke.

Cheers, tc,
Liebe Grüße,
Martin

**Comment by Tensuko** [comment]
Schauen wir mal :)

**Comment by Tensuko** [comment]
Sollte mit dem proximitysensor automatisch verhindert werden.
Ob man sowieso immer im Fahrzeug sitzt um das zu verhindern ist fraglich.
