### ISSUE TITLE
Fold Implements at work end or for refilling

### ISSUE THREAD

**Issue by Ulanawius** [Courseplay/courseplay#7620]
Thanks for your fantastic work on the development of courseplay! I really enjoy using CP and trying different thinks.
Using the "Horsch SW3500S" in combination with the "Pronto 6AS" or the "Maestro 8RC" I realized, that at the end of work point the last implement (the seeder) is folded only. The same occurs when switching to the refill course, where it causes issues as the seeder cannot get close enough to the trailer/silo or the unfolded tools crash into something on the way there.
After finding this issue I tried it with different seeding combinations an tools attached to the tractor front. Always only the last implement is folded. Please see attached screenshots.
Would it be possible to change the code so that all attached implements will be folded?
Please let me know, if you need further information.
Cheers,
Christoph
![2021-11-14 20_58_54-Farming Simulator 19](https://user-images.githubusercontent.com/76711921/141698234-94b07052-507b-40d9-971e-9fad64289ddc.jpg)
![2021-11-14 21_29_15-Farming Simulator 19](https://user-images.githubusercontent.com/76711921/141698238-138848c8-fa4e-4cd2-b05c-8a66cc2a6641.jpg)
![2021-11-14 21_22_32-Farming Simulator 19](https://user-images.githubusercontent.com/76711921/141698239-c0e79c3b-c1f1-4002-adfa-4f4260e00649.jpg)
![2021-11-14 21_20_15-Farming Simulator 19](https://user-images.githubusercontent.com/76711921/141698240-918f89ff-08eb-4744-b8f2-81f31bb2d275.jpg)
![2021-11-14 21_05_01-Farming Simulator 19](https://user-images.githubusercontent.com/76711921/141698242-ce3b53b1-c4de-44a2-8ccb-7f14275a0ca5.jpg)

**Comment by Tensuko** [comment]
We make sure this does work in FS22
