### ISSUE TITLE
Falsche Versions Nummer in der V6.5.0.0

### ISSUE THREAD

**Issue by LamaiK** [Courseplay/courseplay#7623]
Wie im Titel geschrieben hat der DL der V6.5.0.0 noch die V6.4.1.3

Danke für eure Zeit die ihr für den CP und für uns geopfert habt.

Grüsse Kurth

**Comment by rellek82** [comment]
Mir war dieser kleine Fehler auch schon aufgefallen. Ich hab die Versionsnummer aber in der modDesc.xml selbst geändert und jetzt wird alles richtig angezeigt. Habe gestern und heute Nacht auch schon knapp 6 Stunden damit gespielt und es gab keine Probleme. Evtl. machen die Modder von CP ja ein kleines Update mit der Änderung.

**Comment by Tensuko** [comment]
Oh shit. Danke für die Info...

**Comment by Tensuko** [comment]
Sollte jetzt richtig sein...
