### ISSUE TITLE
Nur eine Frage

### ISSUE THREAD

**Issue by xerion8300** [Courseplay/courseplay#7625]
Wo finde ich die Anleitung, habt ihr einen Link.Finde keine Anleitung von der Änderung.

Mode9 course simplified, now only needs a wait point at the unload position.
For more details, check GitHub or website.

**Comment by Tensuko** [comment]
http://courseplay.github.io/courseplay/en/manual/index.html#driveMode9

**Comment by Tensuko** [comment]
#7276
