### ISSUE TITLE
issue launching gamesave

### ISSUE THREAD

**Issue by lhuckabee** [Courseplay/courseplay#7627]
Hey guys, I hardly know anything about game code, but Courseplay won't let my savegame load. I tried to use an older version of courseplay and no luck. Its not that I have too many mods, I only have about 50, any ideas?

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by lhuckabee** [comment]
https://gist.github.com/lhuckabee/ec70918f2b62bdf4e02692e10426afe4

**Comment by lhuckabee** [comment]
> https://github.com/Courseplay/courseplay/wiki

please let me know if that's what you need, I really miss using courseplay

**Comment by Tensuko** [comment]
You have the old version:
https://github.com/Courseplay/courseplay/releases

**Comment by lhuckabee** [comment]
I used the newest version after getting your response. Still having issues

https://gist.github.com/lhuckabee/2e6e33b8d3f7319521816997207395d1

**Comment by Tensuko** [comment]
That seems to be one of your vehicles.
I am not sure wich one, 
Try to remove FS19_CASE_Skidsteer_Pack and load your save again.
You can try to put it back in if your savegame loaded once and you saved it.

**Comment by lhuckabee** [comment]
removed the skidsteer and that didn't fix it

https://gist.github.com/lhuckabee/46349be7bd5e80bed2b65aa9f584b557

**Comment by Tensuko** [comment]
Load your savegame once without CP, save it and put CP back in.

**Comment by lhuckabee** [comment]
didn't work either

https://gist.github.com/lhuckabee/8c14a729f226571d5af5309e8326e7f6

**Comment by pops64** [comment]
I hate to say it but you have a lot of mods with errors. I would try just the map and CP. Then load additional mods one by one until you find the culprit.
