### ISSUE TITLE
Courseplay in FS22 

### ISSUE THREAD

**Issue by BoxerHUN** [Courseplay/courseplay#7633]
Hello.

CP cannot be run under Farming Simulator 22. In modDesc.xml, I rewrote the modDesc version to 61, so you can already see the mode manager, but it stops at 60% when loaded. I also attach the log file. Thanks for helping.
[log.txt](https://github.com/Courseplay/courseplay/files/7589589/log.txt)

**Comment by knoxville73** [comment]
Are you stupid or do you do it purposely ?

**Comment by BoxerHUN** [comment]
What and why?

**Comment by Tensuko** [comment]
Why on earth do you think that is all to do and why you open an Issue ?!

We do NOT have a version for FS22 yet! Closed!

**Comment by dete96** [comment]
Ironie an:
Release war gestern. Was macht ihr eigentlich den ganzen Tag? Seht mal zu!
Ironie aus!
Danke, dass ihr indirekt bestätigt habt, dass ihr an einer Version für FS22 arbeiten werdet. Das wird viele sicher sehr freuen. 
Viele Grüße!
