### ISSUE TITLE
Beet harvester fails to start after update

### ISSUE THREAD

**Issue by crcarmichael** [Courseplay/courseplay#7636]
I've just updated to 6.5 from 6.4.  In this savegame, I have two combines on a field I own, and two beet harvesters on a contract field.  The combines resumed their courses just fine.  The beet harvesters will not. I get the following in the log:

> 2021-11-25 19:17 LUA call stack:
> 2021-11-25 19:17   =P:/Carmichaels/Dropbox/FS19/mods/FS19_Courseplay/base.lua (422) : printCallstack
> 2021-11-25 19:17   =P:/Carmichaels/Dropbox/FS19/mods/FS19_Courseplay/AIDriver.lua (936) : __index
> 2021-11-25 19:17   =P:/Carmichaels/Dropbox/FS19/mods/FS19_Courseplay/AIDriver.lua (925) : getDefaultStreetSpeed
> 2021-11-25 19:17   =P:/Carmichaels/Dropbox/FS19/mods/FS19_Courseplay/AIDriver.lua (520) : getRecordedSpeed
> 2021-11-25 19:17   =P:/Carmichaels/Dropbox/FS19/mods/FS19_Courseplay/AIDriver.lua (496) : driveCourse
> 2021-11-25 19:17   =P:/Carmichaels/Dropbox/FS19/mods/FS19_Courseplay/FieldworkAIDriver.lua (403) : drive
> 2021-11-25 19:17   =P:/Carmichaels/Dropbox/FS19/mods/FS19_Courseplay/UnloadableFieldworkAIDriver.lua (90) : drive
> 2021-11-25 19:17   =P:/Carmichaels/Dropbox/FS19/mods/FS19_Courseplay/CombineAIDriver.lua (225) : drive
> 2021-11-25 19:17   =P:/Carmichaels/Dropbox/FS19/mods/FS19_Courseplay/AIDriver.lua (442) : drive
> 2021-11-25 19:17   =[C] (4294967295)
> 2021-11-25 19:17   =P:/Carmichaels/Dropbox/FS19/mods/FS19_Courseplay/base.lua (422) : xpcall
> 2021-11-25 19:17   dataS/scripts/vehicles/SpecializationUtil.lua (30)
> 2021-11-25 19:17   dataS/scripts/vehicles/Vehicle.lua (1306) : raiseEvent
> 2021-11-25 19:17   dataS/scripts/network/NetworkNode.lua (98) : update
> 2021-11-25 19:17   dataS/scripts/network/Server.lua (58) : updateActiveObjects
> 2021-11-25 19:17   dataS/scripts/BaseMission.lua (1500) : update
> 2021-11-25 19:17   dataS/scripts/FSBaseMission.lua (1979) : update
> 2021-11-25 19:17   dataS/scripts/missions/mission00.lua (469) : update
> 2021-11-25 19:17   dataS/scripts/main.lua (1944) : update
> 2021-11-25 19:17 :44 [info lp88910] HOLMER Terra Dos T4-40 (#4): Exception, stopping Courseplay driver, P:/Carmichaels/Dropbox/FS19/mods/FS19_Courseplay/AIDriver.lua:936: attempt to index field 'course' (a nil value)

I will go through my other in-progress games and see if I can find a pattern, but that's a slow and tedious process so I thought I'd start with this.

**Comment by crcarmichael** [comment]
Update:
I was able to start the beet harvester on a course on an owned field, so it's likely not just an issue with that vehicle. This leads to the contract status being the issue...  however, I have a sprayer on a contract in another field that starts its course with no problem.
I should note that I am using the "Better Contracts" mod to allow multiple active contracts.  If this is the issue, it was not with CP6.4.

**Comment by crcarmichael** [comment]
Update:
I was able to generate a course and start a cultivator on a contract field, so it seems not to be the Better Contracts mod. Also, I should note that the built-in AI is able to run the beet harvester on the contract field with no issues.

**Comment by Tensuko** [comment]
No clue whats happening there.
But we wont fix that for fs19.
I am sry.
We focus now on fs22 and we keep that in mind to make sure it will work correctly on fs22.

However, it is a bit strange since it should not matter what fieldstatus. Try a new course or start on a different position.
