### ISSUE TITLE
Grimme Varitron does not move unless a tipper is offloading the machine 

### ISSUE THREAD

**Issue by justinbey** [Courseplay/courseplay#7639]
i loaded a course with the Grimme Varitron potato harvester and when I go to start it, the machine starts but never moves an inch. I tried the "Drive Now" button and if you do it fast enough, the message that the harvester needs to be unloaded pops up for a second and then goes away. this is all happening with the harvester empty. When I move a trailer in position to unload, it unloads and moves, then once the trailer I removed the harvester stops again. A reminder that all this happens when the harvester has nowhere near that maximum fill. Any ideas?

**Comment by Tensuko** [comment]
I have no Idea and you didn't post a logfile so I know basically nothing.

**Comment by justinbey** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/7612518/log.txt)
Here is my game log. I am also running the latest version of CP, I think 6.5.0
[courseStorage0109.zip](https://github.com/Courseplay/courseplay/files/7612523/courseStorage0109.zip)
[terraDosT4_40.zip](https://github.com/Courseplay/courseplay/files/7612531/terraDosT4_40.zip)
Also attached is the course that is giving me the issue and the XML of the harvester used

**Comment by Tensuko** [comment]
???
(Hash: 41056ebff4f62cde35ab05829c86c31e) (Version: 6.4.0.5) FS19_Courseplay
->
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=209361&title=fs2019

**Comment by Tensuko** [comment]
nvm that was the 1st part of your log.
wonder why you try to do there:
2021-11-27 18:14 :11 [info lp17031] Grimme Varitron 470 Terra-Trac: Setting mode 5
2021-11-27 18:14 :14 [info lp17245] Grimme Varitron 470 Terra-Trac: Setting mode 5
2021-11-27 18:15 :05 [info lp19537] Grimme Varitron 470 Terra-Trac: Setting mode 6
2021-11-27 18:15 :52 [info lp21629] Grimme Varitron 470 Terra-Trac: Setting mode 5

**Comment by justinbey** [comment]
what's wrong?

**Comment by justinbey** [comment]
i don't have the modes memorized so I do not know what mode 5 and mode 6 are

**Comment by justinbey** [comment]
Ok i do not know what i did but I got it to work.

**Comment by Tensuko** [comment]
okay
