### ISSUE TITLE
Realese

### ISSUE THREAD

**Issue by Terrabey** [Courseplay/courseplay#7642]
Hallo Ich wollte mal fragen wie lange es dauert bis ihr die erste Version veröffentlicht?

**Comment by Terrabey** [comment]
Ok hoffe es geht schnell die LS22 Helfer sind nicht besser als wie die von LS15,17,19

**Comment by Hurri85** [comment]
Hat jemand was anders erwartet? Deswegen ärgert es mich mal wieder wie nach jedem Games Release das die Leute von CP und AD nicht vorab informiert werden.
