### ISSUE TITLE
Forage Harvester collision

### ISSUE THREAD

**Issue by joaoesp** [Courseplay/courseplay#7644]
Hello,
my forage harvester running CP slows down when unloading (unloader is using AD).
Am I doing something wrong or is there a setting I can play with to fix the distance between the 2 so it doesn't slow the harvester?

Im using CP 6.5 and AD 1.1.1.8

<img width="1916" alt="a" src="https://user-images.githubusercontent.com/5542656/144746777-9d43f9b5-2139-42d8-87d0-cc80f82fd2fb.png">

Thank you in advance

**Comment by Tensuko** [comment]
Maybe drive more behind the chopper and closer.
We check the front for other AI Driver, not sure why we have a problem with AD there.
Somewhere was an Issue about this already.

Will have to check when I got time.

**Comment by Farmer-Bene** [comment]
https://github.com/Courseplay/courseplay/issues/7564

MfG

**Comment by Tensuko** [comment]
Thank you :)

**Comment by joaoesp** [comment]
![b](https://user-images.githubusercontent.com/5542656/144920633-1862ee4b-f687-4f61-a7b9-35e968e68285.jpg)

So I tested with previous AD versions and it seems to fix it, clearly you can see in the new version the tractor unloads a bit further than previous 1.1.1.6 so the harvester is detecting a collision.

**Comment by Tensuko** [comment]
Thank you for testing and clearing this up.
Thats why it never appeared for us as an Issue.
Can't you adjust the unload position in AD ?

**Comment by joaoesp** [comment]
There's only a setting for when the tractor is unloading from the rear end. Can't change when it's on the side or choose the position to unload.

**Comment by Farmer-Bene** [comment]
Hallo bei mir passt es, wenn ABSTAND ZUM ROHR in AD bei den Abfahrern von Original 0,75m auf 1,75m gesetzt wird! Muss nur beim Drescher Abfahren wieder herabgesetzt werden,.. MfG

**Comment by Tensuko** [comment]
Super, danke dir für die Info.
