### ISSUE TITLE
Spiel friert ein beim Drescher einstellen

### ISSUE THREAD

**Issue by Icke09** [Courseplay/courseplay#7649]
Moinsen, beim Zocken auf der LS 19 MVP friert das Spiel beim Versuch den Helfers einstellen ein. Hierbei handelt es ich um eine Kursgenerierung in einer Mission, die in vorherigen Spielstunden schon etliche Male erfolgreich funktioniert hat. Verwendet wurde CP 6.4.0.5 und AD 1.1.14. Bei der CP 6.5.0 tritt das Problem auch auf. Zu beobachten war, dass nach einer vorangegangen Kursgenerierung auf einem anderen Acker (Mission), es wurde für einen Fahrzeugverband konfiguriert, das quasi " innerste Fahrzeug" im Vorgewende nicht am ersten Wegpunkt bzw. gar nicht auf einer Vorgewendespur eingestellt werden konnte. Beim aktiven Einstellen wird in der Log kein Fehler angezeigt. Die Aktivierung andere CP Helfer funktioniert jedoch. Diese wurden jedoch auch vorher konfiguriert. Gibt es ein Limit an maximal konfigurierbaren Punkten? Außerdem konnte man sich den Kurs zeitweise nur in 2D anschauen.
Wäre über jeden Tipp dankbar.[
[log.txt](https://github.com/Courseplay/courseplay/files/7697623/log.txt)
](url)

**Comment by Tensuko** [comment]
Ich weis nicht was du mit Limit an konfigurierbaren Punkten meinst ?
Kurs nur in 2D anschauen ist auch quatsch.
Wenn du die Wegpunkte angezeigt haben willst, war schon immer das einzig richtige im HUD unter settings die 3 Punkte aktivieren.
Beim Multitoolkursen kann es durchaus mal zu problemen kommen, aber beim starten von den Helfern, wird eben ein offsetkurs gebaut, das kann auch mal länger dauern und da ist Geduld angesagt.

**Comment by Icke09** [comment]
Vielen Dank für den schnellen Kommentar.
Nach mehreren Versuchen habe ich den vermeidlichen Fehler gefunden. Der Kurs bei dem dieses Problem wurde mithilfe einer manuell eingefahrenen Feldgrenze konfiguriert. Diese wurde jedoch durch frühere CP-Versionen aufgezeichnet. Bei der Konfiguration war am Startpunkt der Pfeil/ mehrere Pfeile "ineinander" was vllt. das Problem mit der Startrichtung verursacht hat. Mit einer aktuell eingefahrene Feldgrenze scheint es wieder ohne Probleme zu laufen. 
Großes Lob an euch Entwickler und Support von CP ihr macht echt einen super Job und macht den LS erst richtig spielenswert.

**Comment by Tensuko** [comment]
Freut mich zu hören, dass es nun doch läuft :)

**Comment by Icke09** [comment]
Leider war die Freude nur von kurzer Dauer. Gleiches Problem tritt wieder auf. AD 1.1.1.8, CP 6.5.
Vermutlich liegt die Ursache direkt am Startpunkt. Das kleine/n orangen Dreick/e zeigen in gegensätzliche Richtung. Ursache unbekannt..
Log weiterhin fehlerfrei...
![fsScreen_2021_12_12_16_16_26](https://user-images.githubusercontent.com/51198429/145718336-a10dc37b-ae9f-42f1-9b4f-19eed4687f7c.png)
MFG

**Comment by Tensuko** [comment]
Da ich nicht weis wie dein Kurs aussieht, schwer zu sagen. Auch wieder Multitool ?

**Comment by Icke09** [comment]
Haben den Fehler vermutlich gefunden. Die gezeigte Strecke auf dem Bild ist die Vorgewendebahn, die nur in eine Richtung befahren wird laut Konfiguration.
Dieser doppelte Pfeil tritt bei mir nur auf, wenn ich in der Konfiguration bei Startpunkt: aktuelle Fahrzeugposition auswähle. Mit Wähle Startpunkt auf der Karte aus klappt es.  Komisch..
