### ISSUE TITLE
News about Courseplay for FS22

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/courseplay#7653]
Hey everyone,

as requested, I made a Video with my semi english Knowledge. Hope it is understandable!
As I know not everyone reads the Information under the Video, I try it here as well:

As for the current state, for Plow the automatic workWidth and Offset calculation is not working correct. No guarantee it will work with the release.
About the Pipe, that seems to be a hick up at our side and I hope we get that fixed too very soon :)

I am rly not used to make Videos, so please bear with me about my bad english :) But at least I wanted to show you the current state of Courseplay and how it is working in the first Version.
Yes you have to get used to it, but that's with everything that is new.
Give it a chanze, no guarantee everything I have shown you will work 100% but we do our best! :)

And yes we want to release the 1st Version tomorrow. No Time given.

https://youtu.be/_kyAaN2r8Uk

Pls Read: https://github.com/Courseplay/courseplay/issues/7653#issuecomment-1000843281

**Comment by Markus33-ITA** [comment]
Hi Tensuko. You are a genius. I wish I was as good at programming as you are. you deserve every compliment.
Every day I read the new development messages and look forward to the release of the mod.
Good job to the whole team

**Comment by Tensuko** [comment]
> Hi Tensuko. You are a genius. I wish I was as good at programming as you are. you deserve every compliment. Every day I read the new development messages and look forward to the release of the mod. Good job to the whole team

The Programmers are @schwiti6190 and @pvaiko my programming skills are more like 'I know how to change this number' :D Well ok a bit more then that. But the one who puts all together are my 2 teammates :)

**Comment by bobdown14** [comment]
Awesome work cant wait to start using it and what a xmas present to get

**Comment by Bobster82** [comment]
I wish I had a team like that ;) They both deliver nice work.
And you Tensuko also doing great with handling everything around it.

**Comment by Redster999** [comment]
Thank you for the christmas gift. Love how you guys put this together.

**Comment by bojanh66** [comment]
Thank you guys for your hard work, we all appreciate it.

**Comment by TonyDespo** [comment]
This is the best Christmas present you guys give, I can only say top team and it's amazing so quickly, to the whole team, Merry Christmas

**Comment by Redster999** [comment]
News worthy another donation!

**Comment by StefanBraun2001** [comment]
Nice preview video. I'm exited to test it. Will the fertilizier function have affect on players, which drives the sowing machine theirself? I remember if you turn "Use fertilizer function of sowing machine" off, it also had effect on the player. TBH, it would be a good feature if it is in FS22 again, since the basegame has no function to disable the fertilizer function, so sometimes a lot of expensive fertilizer is wasted.

**Comment by Tensuko** [comment]
> Nice preview video. I'm exited to test it. Will the fertilizier function have affect on players, which drives the sowing machine theirself? I remember if you turn "Use fertilizer function of sowing machine" off, it also had effect on the player. TBH, it would be a good feature if it is in FS22 again, since the basegame has no function to disable the fertilizer function, so sometimes a lot of expensive fertilizer is wasted.

The Setting is not implemented yet as far as I know, but thats a good point. Will see if we can do that.

**Comment by Roby1164** [comment]
Will you create a new release page for FS22 or, will the FS19 present be updated ??

**Comment by Tensuko** [comment]
> Will you create a new release page for FS22 or, will the FS19 present be updated ??

Courseplay for FS22 is on a new repository and the link you will get soon. :)

**Comment by mulei2507** [comment]
I can barely wait for it. Have a nice Christmas everyone.

**Comment by ScurvyHaym** [comment]
Will be streaming FS22 soon, I hope I can show it off in stream today, thank you all for your hard work and Merry Christmas!!

**Comment by Redster999** [comment]
> I can barely wait for it. Have a nice Christmas everyone.

Looks like we will! ;) Merry Christmas right back at ya

**Comment by Corran1327** [comment]
> > Will you create a new release page for FS22 or, will the FS19 present be updated ??
> 
> Courseplay for FS22 is on a new repository and the link you will get soon. :)

Refresh...... Refresh.......... Refresh ............. Eat ........ repeat!!!!! <---what I will be doing today due to this announcement :)

**Comment by Knowen** [comment]
Looks awesome for the initial release. I can't wait to get my hands on it.

**Comment by TonyDespo** [comment]
Will it also be in German or in English for the time being ?

**Comment by knoxville73** [comment]
Fortunately, CP is not out yet, otherwise the Christmas dinner would never be ready for tonight.
Merry Christmas for all people and many thanks for your work.

**Comment by Tensuko** [comment]
> Will it also be in German or in English for the time being ?

English and German Translations are ready. The other languages we hope for our great translater to make PR so we can add all the languages back in :)

**Comment by Tensuko** [comment]
> Fortunately, CP is not out yet, otherwise the Christmas dinner would never be ready for tonight. Merry Christmas for all people and many thanks for your work.

Well for me it is 13:24 right now and we are still working on some preparations for the release, sry buddy.

**Comment by leo32128fs** [comment]
> > Fortunately, CP is not out yet, otherwise the Christmas dinner would never be ready for tonight. Merry Christmas for all people and many thanks for your work.
> 
> Well for me it is 13:24 right now and we are still working on some preparations for the release, sry buddy.

Nice how the time zone works , here for me in Brazil it 's still 10:00 , weird right haha

**Comment by AlexStephenLytton** [comment]
Yay, got it... Maybe first one? :D Happy to test it out ;)

**Comment by hunter30211** [comment]
Ich würde es auch gerne testen

**Comment by Tensuko** [comment]
> Ich würde es auch gerne testen

Geduld, info kommt in der nächsten halben Stunde ca :)

**Comment by hunter30211** [comment]
> > Ich würde es auch gerne testen
> 
> Geduld, Info kommt in der nächsten halben Stunde ca :)

oki Ich warte

**Comment by Beebtrek** [comment]
What a great Video. Thanks for sharing it. Yes like everyone else I want it now Bugs and all. <huge grin>
You guys as always do produce So looking forward to seeing it for real.
Well done and have a great Christmas, all of you.

**Comment by pvaiko** [comment]
The first beta version of Courseplay for FS22 is now available at https://github.com/Courseplay/Courseplay_FS22. 

Functionality is now limited to course generation and field work but we wanted to have this out to get early feedback. Please be kind to us, have patience, we'll be adding features regularly.

Thank you for all your support, especially to those of you who sent generous donations, we really appreciate it. 

Remember, you don't have to be a developer to contribute to Courseplay, there are a lot of other chores like updating the manual and writing HOWTOs!

Have a merry Christmas!

**Comment by Bobster82** [comment]
Thanks for all the hard work CP team! Im going to check it out ;)
Merry Chrismas to you too.

**Comment by Onkel2000** [comment]
> The first beta version of Courseplay for FS22 is now available at https://github.com/Courseplay/Courseplay_FS22.
> 
> Functionality is now limited to course generation and field work but we wanted to have this out to get early feedback. Please be kind to us, have patience, we'll be adding features regularly.
> 
> Thank you for all your support, especially to those of you who sent generous donations, we really appreciate it.
> 
> Remember, you don't have to be a developer to contribute to Courseplay, there are a lot of other chores like updating the manual and writing HOWTOs!
> 
> Have a merry Christmas!

Thank you and Merry Christmas too :)

**Comment by matthiasjost76** [comment]
Danke

**Comment by Exodos74** [comment]
Vielen Lieben Dank an euch.. Kann man nur den Hut ziehen. Macht weiter so. Schönes Weihnachtsfest an Euch.

**Comment by resultwrap** [comment]
Been trying it for a little bit now and it's pretty awesome. However, I don't think I'm really a fan of the built in UI from Giants. I'm having a really hard time navigating around and I don't like how I can't really see what's going on with the equipment while I'm trying to change settings because the UI is taking up the entire screen. Same with creating a course. I find it takes longer and is more difficult to do. Is there a possibility you would be able to bring back the old UI back as another option for users like me who would prefer that?

**Comment by Tensuko** [comment]
The old one not. But we see if we can get a new one up in the future. Functionalty for now is a bit more important. It takes a while to get used to it becouse it is new. If you can tell me what stuff you change arround and need to see it, it will help us.

**Comment by Vaupell** [comment]
Is there a "known issues" somewhere for the FS22, found some minor issues and won't just spam reports if already known.

**Comment by schwiti6190** [comment]
> Been trying it for a little bit now and it's pretty awesome. However, I don't think I'm really a fan of the built in UI from Giants. I'm having a really hard time navigating around and I don't like how I can't really see what's going on with the equipment while I'm trying to change settings because the UI is taking up the entire screen. Same with creating a course. I find it takes longer and is more difficult to do. Is there a possibility you would be able to bring back the old UI back as another option for users like me who would prefer that?

Hi there,

A small hud for workwidth, tooloffset is planned, but it's still WIP.

Small preview:
![grafik](https://user-images.githubusercontent.com/58079399/147363531-456dda13-5582-4012-be08-7c6d16e84c42.png)

**Comment by ice81rm** [comment]
Grande RAGAZZI!!! Davvero grazie grazie :)

Piccolo problema per me.... come devo nominare il file per poterlo vedere dentro il gioco?

**Comment by LindavK1972** [comment]
Question : I have all these numbers surrounding my vehicle. Any way to get rid of that?

Greets, many thanks for the Beta and i wish you all a Merry Christmas!

**Comment by mulei2507** [comment]
> Grande RAGAZZI!!! Davvero grazie grazie :)
> 
> Piccolo problema per me.... come devo nominare il file per poterlo vedere dentro il gioco?

https://github.com/Courseplay/Courseplay_FS22/releases/latest

This link is the File in zip

**Comment by DerKrunch** [comment]
Vielen Dank erstmal für die ganze Arbeit.

Bei mir der CP Fahrerlohn ganz normal vom Konto abgezogen, obwohl ich den Lohn auf 0% gesetzt habe.

**Comment by DerKrunch** [comment]
Vielen Dank erstmal an das ganze Team!

Gibt es eine Möglichkeit diese grüne Schrift wegzubekommen?

![Screenshot 2021-12-24 193944](https://user-images.githubusercontent.com/96632284/147369036-99ddaba9-2a7e-4df5-9829-5384307a913e.png)

**Comment by Tensuko** [comment]
> Question : I have all these numbers surrounding my vehicle. Any way to get rid of that?
> 
> Greets, many thanks for the Beta and i wish you all a Merry Christmas!

They should be gone in the newest Version 7.0.0.3

**Comment by Pappabig** [comment]
First of all great job on getting CP out so fast!! You guys really did a great job!!
Question: Having issue with workers speed that is limited to 5km/h? Is there a way to change this? Have been fiddling around with no success yet.

**Comment by Tensuko** [comment]
The speedproblem is under investigation. haven't figured it out yet.

**Comment by Spyrootjuh** [comment]
Hi All,
Any idea why CP is not working for me? Installed it via the link and playing solo.
Only got for options to togle between, but no option to activate CP itself.

![image](https://user-images.githubusercontent.com/46414198/147401730-2968496b-8702-4e2d-97ea-9369f5fe25c3.png)

**Comment by Tensuko** [comment]
Watch the Video.

**Comment by Pappabig** [comment]
> The speedproblem is under investigation. haven't figured it out yet.

Thank you for fixing the speed problem so fast. You and the team are doing a great job!! Keep up the good work!!

**Comment by DerKrunch** [comment]
Does anyone alese also has the a problem, when activating CP per H Button?
Sometimes The giants helper activates himself and not CP. 
Is that a known issue?

**Comment by dete96** [comment]
I also had it a few times and I saw someone else mention it earlier.

**Comment by Tensuko** [comment]
We have to start it once with Job Menu.
That is not the perfect solution for now, but it works better then what we had before.
We think about do our own command like ctrl+H (only default button) to always start CP...

**Comment by DerKrunch** [comment]
> You have to start it once with Job Menu. That is not the perfect solution for now, but it works better then what we had before. We think about do our own command like ctrl+H (only default button) to always start CP...

I tried it that way too. It works sometimes and sometimes not. Thats an good idea maybe then it will work better. Give it a try ;)

**Comment by Tensuko** [comment]
> New: I just found out, if you put your target position directly under your tractor and then press H it works fine.

Becouse the way is very shot then :)

**Comment by BullittRS** [comment]
Hey Tensuko,

First of all, great job on bringing back CP so quick. It's a mod I can't miss. Especially because of the ai that doesn't work right.

Just a small question though.

Are you planning on bringing back the record option so we can drive our own courses? Because whatever giants cooked up works like a pain in the but.

Not a request, just curiousity.

Keep up the good work.

**Comment by Tensuko** [comment]
Not planed.
For driving arround, use Giants (and hope they impoove this a lot) or use AD wich we work together with.

**Comment by Mike1977** [comment]
> Not planed.

So that means there will be no way to use courseplay on grassland?

**Comment by JDTiger** [comment]
> > Not planed.
> 
> So that means there will be no way to use courseplay on grassland?

Most grassland (should) be defined as crop on a field...

In this case, you can just use CP as you'd do for any other field task.

**Comment by pvaiko** [comment]
@Mike1977 we are currently working on recording custom fields by driving around them, These can later be selected to generate courses on:
![image](https://user-images.githubusercontent.com/2379521/151588878-a3098e74-be36-41bb-9dc2-109abc7e49c5.png)

**Comment by BullittRS** [comment]
Well I hope you guys reconsider and have time to build it back in.

i always used cp for unloading into the silo and selling my product. 

And indeed to make a course for a piece of grassland. 

Nothing worked as good as cp for this.

**Comment by Mike1977** [comment]
> Most grassland (should) be defined as crop on a field...
> 
> In this case, you can just use CP as you'd do for any other field task.

@JDTiger : Thats only the case for the alpine Map. For pretty much any other map including custom maps, there is just grassland and no field underneath them.


> i always used cp for unloading into the silo and selling my product.

@BullittRS : This is exactly what "autodrive" does almost perfectly. You should check it out. I actually share the devs opinion that it's a waste of time and resources on the devs side, if two mods that are used by most people simultaneously, can do the same things.
The only things thats missing for me right now is working on grasslands. 

> we are currently working on recording custom fields by driving around them, These can later be selected to generate courses on:

@pvaiko That looks pretty nice. I can't wait for it to be released. Thanx for your hard work.
