### ISSUE TITLE
Standard Helper Free Drive not working / Standard Helfer freie Fahrt geht nicht mehr 7.0.0.4

### ISSUE THREAD

**Issue by RealNeo80** [Courseplay/courseplay#7657]
Ich habe mir gerade das 7.0.0.4 installiert und festgestellt, dass der Standardhelfer nicht mehr funktioniert, wenn das CP aktiviert ist.
wenn ich den normalen Helfer für Freie Fahrt auswähle bleibt das Fahrzeug nur stehen und fährt nicht zum Zielpunkt.

Resume: 7.0.0.4 if CP is activeated Free Drive is not working, vehicle remains on place with activated Helper

**Comment by Tensuko** [comment]
Falsches Repo: https://github.com/Courseplay/Courseplay_FS22/issues
