### ISSUE TITLE
Multiple Combines/tools in same field

### ISSUE THREAD

**Issue by mpochylko** [Courseplay/courseplay#7659]
Is it possible yet to run 2 combines (or multiple) in the same field yet on fs22? I see options, bit not sure if it's active yet.

**Comment by Tensuko** [comment]
Wrong repository and that question have been answered already, will come later.

**Comment by mpochylko** [comment]
Thanks Tensuko and my apologies for the wrong repository. Is there a location with a development road map? Absolutely loving the progress so far.

**Comment by Tensuko** [comment]
There won't be a roadmap as we do what we can do when we want or need to do it.
Hard to give out a roadmap :)
