### ISSUE TITLE
Weird worker.

### ISSUE THREAD

**Issue by Kaaler05** [Courseplay/courseplay#7660]
Hi i was trying to use the new courseplay and wanted my worker to take the headland first, but instead he just ran cross over my field. I dont know what im doing wrong. Heres some pictures.
![20211228175032_1](https://user-images.githubusercontent.com/63968212/147613605-8ff8ee8a-fe00-4f0b-b729-d08cd63103d0.jpg)
![20211228175037_1](https://user-images.githubusercontent.com/63968212/147613606-36beb6ba-a7cf-405e-8661-57e82be2ceda.jpg)
![20211228175026_1](https://user-images.githubusercontent.com/63968212/147613607-86dbddb8-7777-4338-95c5-c2e584ffaa65.jpg)

**Comment by Tensuko** [comment]
Wrong repository
