### ISSUE TITLE
Feature request: Can a Collision investigation be turned on/off per machine

### ISSUE THREAD

**Issue by BoxerHUN** [Courseplay/courseplay#7662]
Hello.

I can’t empty the bunker silo because the loader wants to avoid the unloading point.
Can you help me in this? 

Thank You

https://www.youtube.com/watch?v=A3JpjMORYBE

**Comment by Tensuko** [comment]
Why do you have placed an 'unload here' waypoint ?

**Comment by BoxerHUN** [comment]
Hello.

The situation is no better without a 'fill in here' waypoint

So this is an idea, but it would be very useful ...
Placing a Collision investigation on / off switch in the settings would help a lot to allow the configured worker to approach his or her target. Of course per vehicle. 

https://www.youtube.com/watch?v=oHuNt7BSUX0

**Comment by Tensuko** [comment]
You can try move the waitpoint further away and the waypoint before the wait a bit closer.
Won't change anything on CP for FS19.
Yes this Mode isn't perfect, but you can get it to work with some effort.
Will be better for FS22.

**Comment by Crinouche** [comment]
Your course is the old process.
In the photos, here is the correct way to create a course in mode 9.
You should no longer put a "P" after the start. No longer cross the bunker and no longer put a "P" at the back of the bunker. You just have to enter in and reverse. A single "P" before the unloading point. Do not go too close to the unloading point (leave 1 meter or 2)
![image](https://user-images.githubusercontent.com/36656729/147851371-c063b19a-13e5-4762-be92-68996363cd7f.png)
![image](https://user-images.githubusercontent.com/36656729/147851392-351e8de6-f182-4b59-a0bd-0e09fead9c0c.png)
