### ISSUE TITLE
Issue with generating course

### ISSUE THREAD

**Issue by MrTrickyNick** [Courseplay/courseplay#7665]
I am using the Bredal K165 on a Fendt 1050 and when I generate a course for 18m it's not covering the entire field, it's missing a part of the edges.  

I have it set to do a headland first due to obstacles.

And, when I tell it to start from the first waypoint it'll activate the spreader and do a 360 then wander off the field while still spreading the lime.   The direction it wanders off is about the angle from the field to where the tractor is parked in the screenshot.

Edit: I did get it to cover the entire field, but had to set work width to 11m but the actual working width is 18m as it does have the extensions.  So it's wasting lime due to the 7m overlapping.

Edit 2: Odd, there wa just a slight overlapping once it was doing the rows.  Is the implement now doing 18m?

![Image of Course](https://user-images.githubusercontent.com/97145709/148164318-5f28924b-763e-48cc-85d2-8b3a34825958.png)
![Image of Merged fields 58 thru 63 with 1 headland of lime](https://user-images.githubusercontent.com/97145709/148164321-16f95781-ab4e-41ee-b7ee-902d56d79c43.png)

**Comment by MrTrickyNick** [comment]
I apologize, I attached the wrong screenshots.  Ignore the above images....I've put in the correct ones below.  I am newish to github (created account to post issue) I don't know how to edit my original post to remove the invalid images.

![Image of Course](https://user-images.githubusercontent.com/97145709/148164073-41f8c659-000c-4c7f-8df3-73ab56883c22.png)
![Image of Merged fields 58 thru 63 with 1 headland of lime](https://user-images.githubusercontent.com/97145709/148164075-2a7fb663-2145-415b-9fd6-eb98e88e6abb.png)

**Comment by MrTrickyNick** [comment]
I just did another course with a seeder that has a working width of 12m.   See screenshot of the results.  Seems the working width is not working correctly?

![image](https://user-images.githubusercontent.com/97145709/148170890-93970afc-6e36-4c36-b54d-c927763a46b3.png)

**Comment by Tensuko** [comment]
Wrong repository.
