### ISSUE TITLE
Locking up at %85 

### ISSUE THREAD

**Issue by muskrat2k9** [Courseplay/courseplay#7666]
Game locks up in loading at 85 percent whenever I try loading with Courseplay 1.0.0.13 with NO other mods.  Game loads fine when I create a new game. 

I checked the log and its has this error. 
2022-01-06 09:43 :13 [dbg20 lp696] Bruin 4200: getting working width...
2022-01-06 09:43 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
dataS/scripts/vehicles/specializations/VariableWorkWidth.lua(442) : attempt to get length of local 'sections' (a nil value)

Its referencing the Sprayer Bruin 4200. So, I removed that Vehicle from the Vehicle ini file in the save game folder and then reloaded. It loaded just fine.

**Comment by Tensuko** [comment]
Wrong repository!
