### ISSUE TITLE
Ok I found a bug

### ISSUE THREAD

**Issue by muskrat2k9** [Courseplay/courseplay#7667]
I  found a bug that  I  think  you quys would be interested  in seeing   but You  closed  it saying  Wrong  repository.  Do you care  to explain to me instead   where  to  post  this  then?  I am new to this  site. I don't understand where I am supposed to put this.

**Comment by Mike1977** [comment]
Here is the link to the right repository

https://github.com/Courseplay/Courseplay_FS22/issues
