### ISSUE TITLE
Problem when I arrive to turn

### ISSUE THREAD

**Issue by ice81rm** [Courseplay/courseplay#7672]
Hello everyone and THANK YOU again for the great work you do :)
with version 0.16 I encountered this ....
![Screenshot (375)](https://user-images.githubusercontent.com/39805100/148656017-8bc73e60-e464-4a32-be54-b30b43cd267c.png)

My game crashed

I attach my log file
[log.txt](https://github.com/Courseplay/courseplay/files/7833804/log.txt)

**Comment by Tensuko** [comment]
Wrong repository
