### ISSUE TITLE
problem with 2 piece seeder

### ISSUE THREAD

**Issue by gigiothegreat** [Courseplay/courseplay#7679]
Hi, i'm using version 7.0.0.22 on fs22 and i'm having an issue with a 2 piece seeder, the courseplay says that the seeder is empty although the cart is full, probly just a cp problem since it works fine with the default helper. also it works if i set the helper so that he buys seeds and fertilizer. apologies in advance for my bad english
P.S. this is the mod: https://farmingsimulator22mods.com/bourgault-pack-dlc-v1-0-fs22/

**Comment by Tensuko** [comment]
Wrong repository
