### ISSUE TITLE
Game keeps stuck on loading screen 85%

### ISSUE THREAD

**Issue by Suspect-byte** [Courseplay/courseplay#7683]
I turned already every mod off and deleted all mods.... I tried to load the game without any mods but it still get stuck on 85%. Btw when I hit on escape button is see the world glitchy and I cant move.

This is the error that I got. 
`2022-02-08 17:43 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
dataS/scripts/vehicles/specializations/Baler.lua(1207) : attempt to index local 'baleTypeDef' (a nil value)
`

Here is my complete log file.
[log.txt](https://github.com/Courseplay/courseplay/files/8025896/log.txt)

Thanks in advance hopefully you guys can help me. Because all my process is gone....

**Comment by Tensuko** [comment]
Did you download the branch and not the release ? ...

**Comment by Tensuko** [comment]
And you are on the complete wrong branch here....

And....

`2022-02-08 17:33 Started network game (10823)
2022-02-08 17:33 Error: Startup with port while already running`

???

**Comment by Tensuko** [comment]
And as you are wrong here, where did you download CP ?
