### ISSUE TITLE
Moving courses

### ISSUE THREAD

**Issue by ConstructionGamer** [Courseplay/courseplay#7686]
Apologies if this has already been raised or if it's my error. But tried to move a course and instead the folder that I try to move it into disappears. 

2 things seem to happen, 1 the folder I click on disappears, or the folder appears in the right hand side "Course Interaction" menu.

The second one I thought was random, but is my error. If you hit "Move entry", click on the course you want to move and then click on the folder you want to move it to, without hitting "Activate" first, then when you click the folder the entry was in, the folder you wanted to move to ends up in "Course Interaction". I understand now it's my error, but is an interesting quirk.

I've uploaded a brief clip to better explain. https://youtu.be/ZEZQj7s2sFQ

The other error I'm trying to replicate, but does seem to happen randomly.

**Comment by Tensuko** [comment]
What you do should not even work.
But will have a look.
But you are on the wrong repostiry here...
