### ISSUE TITLE
Courseplay cant detect my fields, even tho i turned on automatical field scan.

### ISSUE THREAD

**Issue by Trippy764** [Courseplay/courseplay#7690]
Hello. My problem is that what i wrote in title. Ill add screen shots too. Its my field and its ready to harvest.
![image](https://user-images.githubusercontent.com/101125653/157066280-6f02ffc4-f96e-4d49-81ea-64fdbbf54ae9.png)
![image](https://user-images.githubusercontent.com/101125653/157066392-7da9f6a6-7284-4761-9c3b-c09359da3d3c.png)
![image](https://user-images.githubusercontent.com/101125653/157066437-61593b65-a723-495c-a016-2a24bd65fe21.png)
![image](https://user-images.githubusercontent.com/101125653/157066570-9c55b012-34cc-4fcf-b749-3ae3696d92d3.png)

**Comment by Trippy764** [comment]
Its also just on that map, is it because author did something wrong with the fields ? If yes is there any way how to fix it ?

**Comment by Tensuko** [comment]
Try to scan the field manualy and add it as a number.
