### ISSUE TITLE
Seeder not fully planting edge of field

### ISSUE THREAD

**Issue by tfarmerjohn** [Courseplay/courseplay#7692]
I'm using the planter4900 seeder. On one end of the field, the seeder works just fine, detects end of field pathfinds around, reverses to proper point, then starts planting with no issues. On the other end, it does everything, starts its turn, but instead of reversing back to start planting with no gaps, it just starts immediately and misses a section of field unplanted. Using the latest version of Courseplay, no mods on seeder or tractor, issue happens the worst on the setting, stay in the field. The gap is better on the setting, deactivated on staying in the field. The first picture shows the problem, the second picture shows what its suppose to do when it reverses back to field start and plants properly.
![Field End 1](https://user-images.githubusercontent.com/102346525/160140100-78bc9a4f-a6e5-4e5c-a159-242a1604ee1b.jpg)
![Field End 2](https://user-images.githubusercontent.com/102346525/160140115-8d0f44e4-cfc3-472a-8d59-c7d907b2a4f6.png)

**Comment by Tensuko** [comment]
Wrong repository.
