### ISSUE TITLE
Equipment Not operating as set

### ISSUE THREAD

**Issue by Gibbanator** [Courseplay/courseplay#7695]
It seems that even with the Harvester on Avoid fruits and the Semi on avoid fruits that neither of them Avoid Fruits when it comes to unloading. The harvester does not pull away from the fruits so the semi has to unload sitting on the fruits. Than the semi makes a right turn into the semi and pulls in front of the Harvesters path and does not move. 
I have tried making a new course, detaching and reattaching the trailer than starting AD again. The AD settings are also on avoid fruits. Thing is it was working just fine on field 8 but on field 5 and 9 this hiccup happens and I can not correct it. I have also turned off the PC for a day and tried it all again to no success.

Here is a video on the matter https://youtu.be/4aUzRqfth74

**Comment by Tensuko** [comment]
Wrong repository
