### ISSUE TITLE
Game will not load 

### ISSUE THREAD

**Issue by Curry1313** [Courseplay/courseplay#7696]
I have used the power of deduction to determine that courseplay is the culprit to my game not loading. ( turned off every mod but it) loads just fine with all mods when CP is discluded. game will load to 85% and  then stop. I have allowed over 15 minutes for it to load with no avail I am running the most current available version posted 3 days ago and am running most updated game.

**Comment by MoslessNeo** [comment]
Giants on Twitter:
_We have identified the cause of an issue with scriptmods in Patch 1.4 and will deploy a hotfix as quickly as possible._

https://forum.giants-software.com/viewtopic.php?f=876&t=190708

**Comment by Curry1313** [comment]
> Giants on Twitter: _We have identified the cause of an issue with scriptmods in Patch 1.4 and will deploy a hotfix as quickly as possible._
> 
> https://forum.giants-software.com/viewtopic.php?f=876&t=190708

Thanks
sam
