### ISSUE TITLE
CoursePlay is not working on Farming Simulator 19.

### ISSUE THREAD

**Issue by TcharlesMichelin** [Courseplay/courseplay#7697]
CoursePlay version 6.5.0.0
Farming Simulator version 1.7.1.0 (22969/33263)

Source error: C:/Users/Tcharles/OneDrive/Documentos/My Games/FarmingSimulator2019/mods/FS19_Courseplay/settings.lua:241: bad argument #1 to 'pairs' (table expected, got nil)

When starting a new profile with the desired mods, including courseplay, the game enters the loading screen and crashes there.
Can anyone help me to solve the problem? Please I need help!

Attached is the "log.txt" file of my game.
[log.txt](https://github.com/Courseplay/courseplay/files/8536743/log.txt)

**Comment by Tensuko** [comment]
You should remove this old crap:
Available mod: (Hash: 0184d3c925fe273876d1a1719cac40cb) (Version: 6.01.00146) ZZZ_Courseplay_6_01_00146

And have only the correct Version in it (what you do have).

**Comment by TcharlesMichelin** [comment]
I put the ZZZ_Courseplay_6_01_00146 in the folder to test with it only and it worked.
Then I tested it with version 6.5.0.0 and it doesn't work, it crashes in the game loading window.
I didn't activate both at the same time.
The error appeared days before testing with version 6.01.00146.
And the error still persists even without Courseplay v.6.01.x. in the folder.
