### ISSUE TITLE
CoursePlay is not working on Farming Simulator 19.

### ISSUE THREAD

**Issue by TcharlesMichelin** [Courseplay/courseplay#7698]
You should remove this old crap:
Available mod: (Hash: 0184d3c925fe273876d1a1719cac40cb) (Version: 6.01.00146) ZZZ_Courseplay_6_01_00146

And have only the correct Version in it (what you do have).

_Originally posted by @Tensuko in https://github.com/Courseplay/courseplay/issues/7697#issuecomment-1106359327_
-------------------------------------------------------------------------------------------------
I put the ZZZ_Courseplay_6_01_00146 in the folder to test with it only and it worked.
Then I tested it with version 6.5.0.0 and it doesn't work, it crashes in the game loading window.
I didn't activate both at the same time.
The error appeared days before testing with version 6.01.00146.
And the error still persists even without Courseplay v.6.01.x. in the folder.

**Comment by Tensuko** [comment]
active or not, remove the old Version!
