### ISSUE TITLE
CousePlay is not working on FS19.

### ISSUE THREAD

**Issue by TcharlesMichelin** [Courseplay/courseplay#7699]
active or not, remove the old Version!

Edit:
And I can tell you is, 6.5.0.0 is working, else we would have not bringt it into ModHub.

_Originally posted by @Tensuko in https://github.com/Courseplay/courseplay/issues/7698#issuecomment-1107538048_
______________________________________________________________________________________________

I removed the old version.
And the error still persists.
Is there a mod conflict?

**Comment by Tensuko** [comment]
You can only try it out.
Clean mods folder, add mod by mod or small packs.
