### ISSUE TITLE
3x Drescher Kurs - einsammeln des Stroh's auf der links/mitte/rechts

### ISSUE THREAD

**Issue by Sirpoco** [Courseplay/courseplay#7700]
Hallo,
ich habe in Wild Westen einen Drescherkurs mit 3 Dreschern, diese laufen mit den Abfahrern optimal. Jetzt will ich 3 Verladewagen auf den jeweiligen Spuren fahren lassen, dass klappt 1te auf links(1), 2te auf Mitte, 3te auf rechts(1). Startpunkt klappt ohne Problem, alle fahren so wie Sie sollen. 

wenn der erste (z.B. Mitte) voll ist, wird er an Autoplay übergeben und fährt zum Silo, kommt dann zurück zum Feld. Dann findet er den letzten Punkt, geht jedoch nicht in die mittlere Spur, sondern in die Linke. Auch die anderen reihen sich dann in die Linke Spur ein.

Meine Sie sollen an den Punkt und Spur weiter machen, wo Sie aufgehört haben. Denn bei ein Feld von einer Größe von ca. 100 Ha, dauert es sonst sehr lange.

Wenn es so nicht funktioniert, brauche ich ja nur einen Verladewagen, anstatt 3 wie ich Spuren habe.

Vielleicht könnt Ihr mir ja Info geben, ob es nicht funktioniert oder ob ein Bug vorliegt.

Grüße Andy

**Comment by Tensuko** [comment]
Falsche repository und schau dich bitte mal selber um. Wichtig ist immer die neueste version

**Comment by Sirpoco** [comment]
Endschuldigung, aber iat die neuste, danke für Anwort.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Tensuko ***@***.***> Datum: 26.04.22  17:18  (GMT+01:00) An: Courseplay/courseplay ***@***.***> Cc: Sirpoco ***@***.***>, Author ***@***.***> Betreff: Re: [Courseplay/courseplay] 3x Drescher Kurs - einsammeln des Stroh's auf der links/mitte/rechts (Issue #7700) 
Falsche repository und schau dich bitte mal selber um. Wichtig ist immer die neueste version
