### ISSUE TITLE
lua1152 error

### ISSUE THREAD

**Issue by CrazySaft** [Courseplay/courseplay#7705]
2022-05-23 19:33 C:/Users/Tiger/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/TriggerHandler.lua:1152: attempt to index field 'cp' (a nil value)
2022-05-23 19:33 Error: Running LUA method 'update'.

I get this on and on (spammed in my log) and the game is blurred and nothing works.

**Comment by Tensuko** [comment]
There is no support anymore for FS19 CP Version.

Since most stuff was working, you may found something that does not.
You have to avoid it then, sry!

**Comment by CrazySaft** [comment]
> There is no support anymore for FS19 CP Version.
> 
> Since most stuff was working, you may found something that does not. You have to avoid it then, sry!

Ohh thats bad, cause i can't play with courseplay my screen stays dark and i can't move or interact, zhe HUD is also gone.

**Comment by Tensuko** [comment]
Try mod by mod wich one cause the Error

**Comment by CrazySaft** [comment]
Okay thanks, it was caused by the H160 Airbus helicopter, but it worked in another world with both the helicopter and courseplay.
So i really don't know what to do cause this mod would be really useful.
