### ISSUE TITLE
FS22 File count per store item too high. 213 found (max. 128)

### ISSUE THREAD

**Issue by DarkTiger512** [Courseplay/courseplay#7706]
FS22 courseplay gives this error when trying to load the mod.

**Comment by ThijmenGThN** [comment]
> FS22 courseplay gives this error when trying to load the mod.

I'm here to back-up @DarkTiger512, this is what the warning shows on the dedicated server.

![image](https://user-images.githubusercontent.com/54316157/169976085-ccbba26d-b36e-434b-b91c-49e291e7f371.png)

**Comment by ThijmenGThN** [comment]
It’s marked as active, however once joining the server it really isn’t.

It also only shows as an available mod in the dedi-console, whilst others are getting “added” this one does not.

**Comment by Tensuko** [comment]
I know some ppl play online on Dedi Server with CP so that Problem does not come from CP then.

**Comment by Tensuko** [comment]
Guess so.
Well patch 1.5 might be a reason too but that is to early to say that.
You should check your logfiles of the server.
