### ISSUE TITLE
Hud not showing when keybinds pressed.

### ISSUE THREAD

**Issue by halogan98** [Courseplay/courseplay#7707]
Its my fault, but I switched the setting for one of my tractors so right click doesn't work. Now that disabled my Hud completely for my tractor. I've reinstalled FS19. Uninstalled coarseplay completely. But I guess not fully. Where the hell do you store the secret file for the tractors for their coarseplay settings?!??!?!

**Comment by Tensuko** [comment]
The hud always turns on with del key unless you throw out the keybind.

**Comment by halogan98** [comment]
I still need help as I tried the del key multiple times. I just need to know where the file for each individual tractors are stored because its only happening with this one tractor.
