### ISSUE TITLE
Hud wont open when pressing del key. #2

### ISSUE THREAD

**Issue by halogan98** [Courseplay/courseplay#7708]
Hi, I tried your advice and it still didn't work and was wondering if you could help me fix it please. I've reset all of my key binds, nothing. Deleted Courseplay. Nothing. Deleted the tractor that wasn't pulling up the Hud. Nothing. If you can tell me where you store the file that has the advanced settings for each tractor that would be great.

**Comment by Tensuko** [comment]
Logfile

**Comment by Tensuko** [comment]
Can't help without a logfile.
