### ISSUE TITLE
need help with error attempt to index local 'xmlFile' (a nil value)

### ISSUE THREAD

**Issue by bigbear422** [Courseplay/courseplay#7709]
i dnt know what to do and it says this: Error: Failed to open xml file 'C:/Users/baile/OneDrive/Attachments/Documents/My Games/FarmingSimulator2022/mods/FS22_BigFieldsXXL10km_zoltanm/maps/BigFieldsXXL/map.xml'.
2022-05-29 15:15 Error: Running LUA method 'update'.
dataS/scripts/missions/mission00.lua(90) : attempt to index local 'xmlFile' (a nil value)
2022-05-29 15:15 Error: Running LUA method 'update'.
dataS/scripts/FSBaseMission.lua(691) : attempt to index field 'missionDynamicInfo' (a nil value)

**Comment by Tensuko** [comment]
Got nothing to do with CP.
