### ISSUE TITLE
Driver Tab disappears when scrolling through the Menu with a Controller

### ISSUE THREAD

**Issue by Roomzie** [Courseplay/courseplay#7710]
Hi there! 

First of all i want to thank you guys for doing this amazing Job with CP, for me it has become essential and i wouldnt be playing FS without your Mod, Awesome work! 

Now to the Problem: when i open the Escape Menu it starts at the normal Map View-Tab, using a Controller to switch tabs means i have to Press LB or RB to go down the Menu, however when im in a Vehicle so that it shows me the Route-Tab and Vehicle-Options-Tab and i press RB (now we´re on the Work tab with the Wheel as a Symbol) the Route- and Vehicle-Tabs just disappear. I have to close the Escape Menu and open it again for them to show up again. I can only access the 2 Tabs by clicking on them with the Mouse while on Map view Tab. 

It also puts out 2 Errors: 
Error running LUA method "update"
/FS22_Courseplay/scripts/gui/CpCoursemanagerFrame.lua:443:attemt to index field "currentVehicle" (a nil value)

Error running LUA method "update"
dataS/scripts/gui/base/TabbedMenu.lua(605) : attemt to perform arithmetic on local "oldIndex" (a nil value)

I hope the information given is helping you to understand my problem, it would be amazing if you guys could help me out resolving this issue. 

Thanks in advance! 
Roomz

**Comment by Tensuko** [comment]
Wrong repository and there we have a template what you should use pls.
https://github.com/Courseplay/Courseplay_FS22/issues
