### ISSUE TITLE
CP1 Kurs wird nicht gespeichert

### ISSUE THREAD

**Issue by GhostRat66** [Courseplay/courseplay#7711]
Ich fahre den ersten Kurs auf einem Feld ein. Nach Abschluss fragt Courseplay ob es den Kurs unter CP-1 Kurs speichern soll und ich bestätige mit ja.
Nun ist zwar der Kurse im FS22/Ordner zu sehen aber er wird mir nicht im CP Menü zur Auswahl angezeigt.
<img width="666" alt="Courseplay Problem CP-1" src="https://user-images.githubusercontent.com/106917815/172054466-19907ded-d43e-4a44-9353-f7cd6d0fd000.png">
[log.txt](https://github.com/Courseplay/courseplay/files/8840120/log.txt)
<img width="1687" alt="Courseplay Problem CP-1_ingame" src="https://user-images.githubusercontent.com/106917815/172054771-68531f6b-9bb1-4d5c-a5a8-edcd50bfade6.png">
.

**Comment by Tensuko** [comment]
Das sind auch Feldränder und keine Kurse!
Ingame Anleitung lesen und du bist in der falschen repo.
