### ISSUE TITLE
Unable to stop driver/worker in multiplayer

### ISSUE THREAD

**Issue by Krzd-OG** [Courseplay/courseplay#7716]
I often run into the issue that after starting a worker and tabbing into a different vehicle, I can't interact with the CS window at all, and can't open/close it again. Hotkeys also have no effect.
The only usable workaround I've found so far is (in multiplayer) to have a different player come in and dismiss them. Otherwise I have to restart the game for them to be dismissed.

**Comment by Tensuko** [comment]
Since you are in FS19 Repository.....
You use what game, what version, why no logfile...

**Comment by Tensuko** [comment]
closed due to inactivity
