### ISSUE TITLE
My people need me

### ISSUE THREAD

**Issue by ShaunTheBaa** [Courseplay/courseplay#7717]
I hadn't played FS19 for a long time and updated to the latest version. I'm having an issue where if I have 'Use AI turn maneuvers' Deactivated, on the end of a row on a field I have a headland on;
The tractor reverses, drives forward a little, turns slightly then continues to drive on in a straight line forever at a slow speed.
It keeps driving straight until it ends up stuck in a tree or on top of a mountain.
Also when starting a row on only 1 side of the field, it doesn't back up enough, so leaves a strip unseeded.

**Comment by Tensuko** [comment]
I can't help you with any of those informations.
logfile, screenshots and so on.
Sounds like Mod Issue.

**Comment by Tensuko** [comment]
closed due to inactivity
