### ISSUE TITLE
CP Proplem

### ISSUE THREAD

**Issue by Stev099** [Courseplay/courseplay#7718]
Hallo ich habe probleme auf dem dedi server   wenn ich ein kurs generiere und dann helfer einstetze dauert es erst mal 5min bis es geht 

in denen 5min ist standbild woran könnte es liegen 

der server hat wenn ich standbild habe 7% auslastung ?

**Comment by Tensuko** [comment]
Fs19? Fs22? Version? Logfile?

**Comment by Tensuko** [comment]
closed due to inactivity
