### ISSUE TITLE
Courseplay Problem mit 2 Anhängern

### ISSUE THREAD

**Issue by TheLuke06** [Courseplay/courseplay#7720]
[DE]
Moin,
und zwar will ich auf der MVP19 das Silo auf dem "haubt" Hof mit 3 Gespannen Abfahren, jedes hat 2 Anhänger. Mein Problem ist jetzt aber das Courseplay nur den ersten Anhänger befüllt und dann losfährt. Hat jemand eine Idee wie ich das beheben könnte.
Ich hoffe um schnelle Antwort
MFG Lukas

[ENG]
Hi,
on the MVP19 I want to drive down the silo in the "main "yard with 3 teams, each with 2 trailers. My problem now is that the courseplay only fills the first trailer and then drives off. Does anyone have an idea how I could fix this.
I hope for a quick answer

**Comment by Tensuko** [comment]
Puh lange ist es her...
Es gibt eine Liste wo was rein soll.
Wie genau wir das gelöst hatten weis ich nicht mehr.
Wichtig war auch wie start und stoppunkt gesetzt werden.
