### ISSUE TITLE
Why does it stop and not continue?

### ISSUE THREAD

**Issue by Gibbanator** [Courseplay/courseplay#7721]
Please excuse if I am putting this in the wrong area I see no but report area. Using CP 7.1.1.5 The Tractor stops and will not continue like there is a collision or something stopping it. It clearly has plenty of room to move forward. Here is a video on the problem. https://youtu.be/xpkfCA-EqlE I can repeat the action if needed so if you need me to do anything I can replicate it.
[log.txt](https://github.com/Courseplay/courseplay/files/9873313/log.txt)

**Comment by Tensuko** [comment]
Wrong repository

**Comment by Tensuko** [comment]
Also this is autodrive and not cp.
