### ISSUE TITLE
A combine does not find the center of the track

### ISSUE THREAD

**Issue by alvaz39** [Courseplay/courseplay#7722]
Hi, thanks for your help, ok, I have one mod, a CLAAS combine which does not find the center of the track, and it is an issue exclusively of this mod, I think that something is wrong on its XLM file, so my question is:

where inside the combine´s XLM file takes COURSEPLAY the center of the vehicle to lead the combine across the field?
Maybe this is solved changing one number.

Thanks
Kind Regards

**Comment by Tensuko** [comment]
Pls compare it with vanilla combines.

**Comment by alvaz39** [comment]
Hi, thanks, but any clue about what line should I check?, because I done that before posting this question, comparing against combines that work fine with courseplay, but nothing clear for me, keep in mind I discover Farming 2 moths ago, I am not an expert at all, but I thing that course play takes some data from the xlm to make the vehicle to follow the track.  I checked the lines relative to center of mass, but they are different in each combine (logically). For combines i did not see either an offset to correct that.
The mod that is not working is this: CLAAS_Lexion_8000, maybe someone want to check and discover the reason.

Thanks

**Comment by alvaz39** [comment]
Hi, thanks, too difiicult for me.
