### ISSUE TITLE
Courseplayer FS19 leitstreifen Schwarz 

### ISSUE THREAD

**Issue by Waldschrad1** [Courseplay/courseplay#7726]
Ich habe Problem das der courseplay 6.5 seit  3 Wochen habe ich ein Problem die blauen leitstreifen sind schwarz und die richtungs Pfeile sind garnicht sichtbar, mehrfach funktioniert der Abfahrt auch gar nicht. Habe das Spiel schon ganz neu installiert   den CP neu installiert 

In der Log steht der Warnhinweis der auch auf eure Seite steht kann das sein das ich die Entwickler Version habe wie kann man das feststellen 
Lg
Waldschrad1

**Comment by Tensuko** [comment]
Logfile?
Shader cache leeren kann auch helfen (google fragen)

**Comment by Waldschrad1** [comment]
Dankeschön hat funktioniert die Shader cache Datei ist im Mod Ortner
