### ISSUE TITLE
Kein Courseplay Hud

### ISSUE THREAD

**Issue by FarmerJosef** [Courseplay/courseplay#7728]
Mein Hud von courseolay lässt sich im LS22 nicht mehr öffnen habe alles neu Instaliert  Coursplay, Autodrive auch das Spiel schon 2mal 
inPut binding auch gelöscht geht nicht auf
# #

**Comment by Tensuko** [comment]
falsche repository und wo ist das logfile?

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki
