### ISSUE TITLE
Courseplay course 

### ISSUE THREAD

**Issue by Thorne9197** [Courseplay/courseplay#7730]
I added tracks to a combine now the course has to be offset -5.9ft to cut correct, while the same machine with tires cuts fine. Doesn’t matter which head is used.. my question is how is the course calculated in the aspect and is there a way to correct it? Thanks

**Comment by Tensuko** [comment]
I cant follow you.
What game version are you in and what tools you talk about exactly.
A screenshot of your problem might help.
Or maybe you explain what you want to do so I can show you a better way.

**Comment by Thorne9197** [comment]
![6647AB3F-62ED-4F5B-849D-847A069AA41B](https://user-images.githubusercontent.com/121476825/210025266-333393e8-f544-41df-ae45-249284960bfc.jpeg)
![C47C91B5-7C7D-47B6-899A-62F7F33ED6E5](https://user-images.githubusercontent.com/121476825/210025279-fbf1ba07-d40d-4ad4-a1b6-8c68d4a4319c.jpeg)

**Comment by Thorne9197** [comment]
The first one is the tracks I added.. create the course is off centered… same machine but with tires and same head  it’s perfectly centered

**Comment by Tensuko** [comment]
Then there is something wrong in the xml for the tiers.
You may compare it to vanilla combines.

**Comment by Tensuko** [comment]
You may have a look here 
#4595
