### ISSUE TITLE
Courses for custom fields

### ISSUE THREAD

**Issue by AgrarOekonom** [Courseplay/courseplay#7735]
Hello,
for a few days now I've had the Giants enging crash again and again when creating courses for self-created field borders. Alternatively, an error message appears with the information that no course could be created and information about this can be found in the log file. This happens in both single and multiplayer mode.
[log.txt](https://github.com/Courseplay/courseplay/files/11034736/log.txt)

**Comment by Tensuko** [comment]
You are at the wrong repository...
Correct one is here: https://github.com/Courseplay/Courseplay_FS22

And we always need your FULL logfile.
