### ISSUE TITLE
Autogen routes setting stop point before field edge (0221)

### ISSUE THREAD

**Issue by Torzi** [Courseplay/courseplay#791]
![farmingsimulator2015game_2014_12_15_08_24_56_770](https://cloud.githubusercontent.com/assets/9897849/5436730/e91cd582-8437-11e4-8267-d6d8bd705986.jpg)

Noticed the past couple of generated routes stop before the field edge. Not a huge deal, but I have to manually finish the last bit before moving on.

**Comment by AndyK70** [comment]
I think it has to do with the calculation done with dimensions.maxX which is the max of the field and not the lane. The lane dimension is much shorter than the field dimension and when it comes to 
``` lua
          local _, pointInPoly = courseplay.fields:getPolygonData(poly.points, curPoint.x, curPoint.z, true, true, true);
          if pointInPoly then
```
the point will always be outside and not generated.

**Comment by JakobTischler** [comment]
Yes, put that's why a last point in lane is generated.

**Comment by AndyK70** [comment]
yes, but the test if the last point is inside or not is after the last point is generated and that's why the condition never could be true. 
You should get the dimension of that lane (which is shorter) instead of the dimension of the field to generate that last point.

**Comment by Torzi** [comment]
Haven't had much time to play lately, but I did have a look this morning...

Line 683 of generateCourse.lua
`if cp.lastInLane and i ~= numPoints then`

this is for processing the last point in each lane, but the condition i ~= numPoints will never process the final point in the path. (since i == numPoints is the final point). looks like the rest of the code to handle the last point is already in place, just need to skip past turn direction assignment.

tested as follows and seems to produce the expected result:
```lua
683		if cp.lastInLane then
684			if i ~= numPoints then
				--North
				if cp.laneDir == "N" then
				--East
				elseif cp.laneDir == "E" then
				--South
				elseif cp.laneDir == "S" then
				--West
				elseif cp.laneDir == "W" then
				end;
705			end;
```

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
