### ISSUE TITLE
Bale loader

### ISSUE THREAD

**Issue by Karlshoj** [Courseplay/courseplay#793]
https://gist.github.com/Karlshoj/980148a0c07587da1b7a
dev. 0224

I´m running a combined route collecting bales and bring to sales spot.
Generated field route + recorded route to sales spot and back to field.
Case Puma CVX 230 (modded) + Arcusin Autostack FS 63-72 (default)
When job is done I get the message saying that Case Puma has finished work.
I press continue to make the tractor go unloading.
It doesn´t go unloading, but starts unloading at the waiting point at the end of the field - not my plan.
![fsscreen_2014_12_15_13_44_14](https://cloud.githubusercontent.com/assets/7414065/5438790/f8ee5e2a-8461-11e4-8575-4476672ac849.png)

**Comment by ThomasGaertner** [comment]
please ry again with v0051 or higher and give feedback whether its still valid or not Thanks

**Comment by JakobTischler** [comment]
Closed due to inactivity.
