### ISSUE TITLE
Course Play Problem

### ISSUE THREAD

**Issue by hackselgut** [Courseplay/courseplay#830]
Have just up graded to ver 248 from my last one Ver 236, Now I find that the overloader is not doing a final approach to the combine, It pulls in, slows down to ( zero ) speed and thus stopping short of being in filling location. Looks to be doing it not every time. Operation was OK before up grade to version 248. ( bob )

**Comment by hackselgut** [comment]
I am now using the Version 4.01.0013 and the problems I was having seem to be Ok now. But I would lik to ask 2 questions, 1..Where can I adjust the Default speed that comes up for "Street Speed ( value 50 ) as I find this to fast, for now I would like it at 30. 2. I record a course, set it`s mode and speeds etc.etc and then Name and save File,Later on I want to put a second Vehicle on that Course, so I line up the vehicle and click the Course to activate, ( 2 vehicles on same course ) I wold assume that the second Vehicle would pick up what ever was recorded and Saved,  But It does not use the same settings. Is this a Fault in the programming, I would think it should be the same  as to the first Vehicle?   Bob....Thanks

**Comment by Satissis** [comment]
1. You will have to set it to "Max Speed" -> Set the speed you want -> set it back to "From Recording"
2. I have seen others that are a bit confused about this like you, so here is the answer for that. When you record, it does not care what mode you are in or what speed settings you have set, it only record the route it self, so all the settings you will have to set manually your self and what mode. It's done like this, so you are able to use the same route for multi purpose.

Hope this answered your questions.

**Comment by hackselgut** [comment]
The answer to question 2 i will accept as answered thanks. As to question 1, In your file system there is a line that sets up the " max speed of "50" street speed, you are not telling me where this is, Why? All I would like to know is what "lua File" is it from or in. Thanks ( bob )

**Comment by delawarehunter** [comment]
You change the max street speed in the game.  It's on the tab with the Speedometer on it. You first have to change the Speed entry (last in the list) to "Maximum Speed" and then you can modify the Street Speed setting.  This is what Satis was talking about when he gave you an answer for #1
