### ISSUE TITLE
Idea: Backward harvest with Mex 5

### ISSUE THREAD

**Issue by DieWaage** [Courseplay/courseplay#840]
Hello Courseplay team,

This idea began while testing #832 "Mais harvesting with poetinger mex 5" and the provided fix. As this is a new question/idea/request I decided to open a new "Issue" instead of placing this in the other thread.

With Mex5 attached at tractor front and using Courseplay v256 works now perfect.

I did a little research and found at Mex5 manufacturer home page (Pöttinger, see also links at the end) that it is also/more common to attach a Mex5 at the back of a tractor and then driving backward at harvest. I tried this configuration in LS 15 together with Courseplay v256... 

Initial the transport tractor driven by Courseplay joins the harvester in the "wrong" direction (screenshot 1). So I stopped Courseplay at transport tractor. Then I drove the transport manually to the "right" direction.  After I start Coursplay again at transport tractor the transport follows my backward driving harvester (screenshot 2) very good/as expected ;-) ... 

So my question: Is there an easy way to implement something like a "default backward/forward driving" flag to indicate the normal driving direction for such a harvest combine? So the transport would be able to evaluate such a flag and already initially joins in the "right" driving direction... 

Or is this just a nut idea from my side as this is not a very common usage of CP in LS 15?

Screen1
![fsscreen_2014_12_22_12_38_03](https://cloud.githubusercontent.com/assets/5517105/5524609/1e2b3e44-89d8-11e4-9e7f-28a680940e8c.png)

Screen2
![fsscreen_2014_12_22_12_38_51](https://cloud.githubusercontent.com/assets/5517105/5524592/d48aa770-89d7-11e4-86ca-b9e57bbf9b5e.png)

Manufacturer info and movie:
http://www.poettinger.at/de_in/Produkte/Detail/420/mex-5-anbau-feldhacksler
http://www.poettinger.at/de_in/Newsroom/Video/hbk2sAEtbTI

Best Regards,
Martin

**Comment by JakobTischler** [comment]
Having discussed this, we've decided against implementing it as it would mean some rather big changes necessary in mode 6. Thanks for the suggestion though.
