### ISSUE TITLE
Always working on headland calculation...

### ISSUE THREAD

**Issue by fck54** [Courseplay/courseplay#844]
If the question was asked, Yes, I'm always working on the headland calculation, and I have come to a fast and somewhat accurate solution, will pull it tomorrow if i have got time.
here A picture of what result I obtain ... 
![fsscreen_2014_12_23_00_37_35](https://cloud.githubusercontent.com/assets/4034933/5532768/be4fb0ee-8a3c-11e4-9c9d-0661d72bbced.png)

**Comment by fck54** [comment]
Still at work and cleaning my code,  as I want the link between the lanes to be the best possible.

**Comment by fck54** [comment]
he last version is down on the request,
here the picture I just made 
![fsscreen_2015_01_09_20_51_21](https://cloud.githubusercontent.com/assets/4034933/5686303/125d2f0a-9842-11e4-8d3a-ef16b2dc169b.png)
![fsscreen_2015_01_09_20_51_08](https://cloud.githubusercontent.com/assets/4034933/5686304/125ef6d2-9842-11e4-9bb0-397e7ebb21bd.png)

calculation takes less than a second

**Comment by fck54** [comment]
some more picture for recorded fields 
![fsscreen_2015_01_09_21_02_28](https://cloud.githubusercontent.com/assets/4034933/5686408/e46aab30-9842-11e4-9270-b93510a2dfcf.png)
![fsscreen_2015_01_09_21_01_56](https://cloud.githubusercontent.com/assets/4034933/5686409/e46be8e2-9842-11e4-8203-0d6761c33846.png)
![fsscreen_2015_01_09_21_01_18](https://cloud.githubusercontent.com/assets/4034933/5686410/e4834c76-9842-11e4-8b3e-9e2458e9b92a.png)
this one took between 2 and 3 seconds calculation.
I have added an option to make a turnaround when choosing 6 headlanes.

**Comment by fck54** [comment]
have some ideas for the hud page 
- adding a turnaround option in headland line
 -> hide number off line if turnaround is selected
 -> hide before or after if turnaround
 -> no start direction if turnaround
 -> start near vehicle if turnaround
 -> to CW and CCW add first headlane CW and next CCW or inverted.

**Comment by JakobTischler** [comment]
Looks great. I still have some questions and comments though. Please check your email concerning Skype.

**Comment by fck54** [comment]
Have seen your request for Skype, it's ok for me . have sent informations too by email

**Comment by Torzi** [comment]
WOW! can't wait to test.

**Comment by Karlshoj** [comment]
In my opinion headland should  be applyed only at the end of the lanes. Dont really need headland at the sides of the field

**Comment by fck54** [comment]
That's in fact why they are cold Headland, but for the moment let us finish the current changes that are huge.  I keep this suggestion in mind for later....

**Comment by fck54** [comment]
Finally thinking about it a bit brings me to a conclusion : this would be a hard job.  Driving like IRL is not the finality of CP,  but to realise some tasks automatically getting as near as possible to reality...  Idea was interesting but really to complicated...

**Comment by sootysax** [comment]
did you abandon the advanced headland project altogether?   was looking forward to it

**Comment by AndyK70** [comment]
what gives you the sensation they would have abandoned it?

6 days ago @fck54 wrote
> let us finish the current changes that are huge.

**Comment by kwguk** [comment]
That great to hear

Im hopeing it'll be similar to the RTK guidance i have in my tractors at home. Not only do they do straight A-B lines buttyou can drive a course, usually the longest side of a field which is curvy then the RTK will generate a course across the field based on your course,

**Comment by Satissis** [comment]
@fck54 are you still with us ?

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
