### ISSUE TITLE
Combine is telling me to stop...

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#854]
![fsscreen_2014_12_24_14_02_14](https://cloud.githubusercontent.com/assets/6591048/5550540/bb51386a-8b75-11e4-8ad0-28925f44414f.png)

Combine is using Autocombine 3.2 - when ever it reaches a corner, the tractor will show combine is telling me to stop when it is away from the combine, and both vehicles will not proceed.

Version 266 (with edits from #851)

https://gist.github.com/sootysax/731ebcca99d7e534127d/ (with debug 4 active)

**Comment by sootysax** [comment]
So this continues to be a problem for me...   there seems to be a conflict with how the unloading tractor and the combine communicate.   This especially creates alot of sitting 'in traffic' in a standoff between the two vehicles when using Auto-Combine.

Sometimes when unloading is finished, the unloading tractor will immediately drive to the 'waiting waypoint' and the combine will wait until it reaches that point to continue it's turn.

Sometimes the unloading tractor will remain in its position - 'combine telling me to stop' and waits until the combine drives a few hundred feet until driving to its waiting waypoint.

This becomes a problem around the corners of an auto-combine course..  The unloading vehicle will be waiting for the combine to drive off - 'combine is telling me to stop' - but is too close to the combine and the combine sees that it is in traffic, and will not make its turn.

I don't know what the deciding factor is on when an unloading vehicle drives off immediately, or waits for the combine to distance itself before driving..  but I think the unloading vehicle needs to get out of the way of turning combines for reliable unloading to work.

**Comment by K-CMotors** [comment]
I have this issue too, after I'm done with unloading the combine (driven manually) the tractor keeps stopping while telling me "combine tells me to stop" and won't turn to an waiting point so I must restart the helper again after every unloading.

Is there any solution for it now?
