### ISSUE TITLE
Unloading Silo BUG

### ISSUE THREAD

**Issue by mroomman** [Courseplay/courseplay#871]
Hi,
ich habe einen BUG entdeckt. Ich lasse bei Hächseln mit Courseplay Abfahren auf den BGA Silos. Wenn ich hier einen Traktor während aktiver Abfahrer im selben Silo mittels Courseplay verdichten lasse, kennt der Abfahrer die Abladestelle nicht mehr und fährt mit vollen Anhänger ohne abzuladen durch die Silos (zeigt unten "Abladestelle erreicht" nicht mehr an).
Den Verdichter Courseplayer lasse ich mit Überführung einen Kurs vorwärts,rückwärts abfahren. Damit der Abfahrhelfer wieder funktioniert muss ich das Spiel neu starten alles andere hilft nicht. Lasse ich den CP-Verdichter in ein BGA-Silo daneben verdichten, welches nicht über den CP-Abfahrer befüllt wird funktionierts. Könnte sich bitte einer dem annehmen.
Ist mir in der letzten Beta erst aufgefallen und in der jetzigen Final 4.01

**Comment by Satissis** [comment]
I have tested this and I can't reproduce this.
Could you send me an savegame where this is happening and tell which vehicles that should run and what order to start them ?

**Comment by Satissis** [comment]
Closed due to inactivity.
Reopen if this is still and issue and have provided the requested
