### ISSUE TITLE
Vehicle Trying To Unload Combine On Turn

### ISSUE THREAD

**Issue by champ50** [Courseplay/courseplay#872]
Vehicle when unloading combine is trying to unload the combine when he is making the turn at the end of the pass instead of stopping and waiting until the turn is completed.  This usually results in the vehicle wrecking the combine.  This is in version 4.00.0268.  It did not happen with .00.247. 
   I don't know what version you're up to now since there's no version number on the outside of the download.  Or is there some way to tell before downloading?  If you need a log file let me know what number to punch and I'll send you one.

**Comment by ThomasGaertner** [comment]
would you please post me the link to this Truck and trailers ? Thanks...

**Comment by champ50** [comment]
Hello Thomas
Sorry for the delay.  Here is a link to the 10x10 tractor that I'm using and the trailers are the built in Krampe trailers and the fligel dollies are also built in.
http://www.farming2015mods.com/farming-simulator-2015/trucks/volvo-fh16-heavy-duty-10x10-8x8-pack-v-0-1-fs-15/

**Comment by ThomasGaertner** [comment]
and how did you connect the dolly to the trailer ?

**Comment by champ50** [comment]
OOPS sorry about that for the wrong info.  They are an adaptation of the originals with a coupling added to the rear.  Here's a link to them.
http://www.mods-2015.com/?s=LS2015_KrampeSB3060K

**Comment by ThomasGaertner** [comment]
try v .0040 and report.....

**Comment by ThomasGaertner** [comment]
closed due to inactivity
