### ISSUE TITLE
Wait time for bale autostacker? ?

### ISSUE THREAD

**Issue by jhomer** [Courseplay/courseplay#873]
Wondering if its possible for an autostacker bale trailer after it reaches 100% and heads to waiting point to unload- if after it tilts trailer up and releases bales if it could pause for like 5 seconds before it tilts trailer down and takes off again?
 
Close this whenever (I won't be offended) if your not taking any questions or suggestions.
Thanks for your time.

**Comment by JakobTischler** [comment]
I've added a timer to the unloading process in build 0015: after unloading, the vehicle will drive forward, after 2 seconds it will stop and fold the table, then continue.

Please test and report.

**Comment by jhomer** [comment]
Tested a few times so far,
The first time it dropped bales and drove ahead (then I had a traffic problem non-related which didn't allow it to play through)
Ran the unload 3 more times and each of these times it tilted up-dropped bales-tilted down-then drove off.
I think it was supposed to tilt up- drop bales- drive forward a bit- 2 seconds- tilt down and drive off.
I will test some more yet.

**Comment by JakobTischler** [comment]
So basically what you're saying is, it only works with the first unloading process, but not with the ones after that?

**Comment by jhomer** [comment]
That's what it seemed on the first trial. I see you updated so I'll run it again and report.

**Comment by jhomer** [comment]
Tested again:

Field course and unload course:
1- First run drove to wait point- unloaded- and drove ahead without tipping the bed down till it reached the end of the unload course.
2- Next few runs it unloaded- drove ahead a bit- then stopped and tilted bed down, and when bed was down it drove off again. 

Field course and unload on field (automatic):
3- First few runs it worked like number 2.
4- Last run I stopped tractor with 15 out of 16 bales loaded (was going to run into baler) 
Then started course again- picked up last bale then stopped- unloaded- tilted bed down- then drove off. It did not drive ahead at all in between unload and tilt bed down.

Not sure if you put the 2 second delay in but I think it could be right after it releases bales- then a few second wait- then drive ahead- stop- and tilt bed down.
As in the image: the action of the stacker drops bales then there's an animation of the top of the stacker that takes a couple seconds as the arms tilt up a bit.

Whatever you think to do, I'm good with, I know you guys got a lot of time in CP.
Thanks!
![tilt](https://cloud.githubusercontent.com/assets/7943994/5608190/f0464b36-9440-11e4-9f7f-1d2fe1a3dd5c.png)

**Comment by JakobTischler** [comment]
Can you try again with the latest build? The stopping inbetween and then continuing *should* work now.

**Comment by jhomer** [comment]
Ok, will do.

**Comment by jhomer** [comment]
Test with version .0047
Sorry for the delay but:

Ran with field course and unload course:
It would get to wait point- tilt for unloading- drop bales and immediately take off again and not tilt bed back down till it reached end of unload course. (ran a few times with this same result)

Ran with just field course (unload automatic):
tilt for unloading- drop bales and immediately drive forward 10 meters or so- stop and tilt bed down and continue.

**Comment by ThomasGaertner** [comment]
please try again with v0048 and report...

**Comment by jhomer** [comment]
Test with version .0050

For both instances Field course with unload course and Field course with unload automatic:

Tilt bed up- drop bales- immediately drive ahead 10 or so meters- stop and tilt bed back down- then continue. (no wait time in between "dropping bales" and "drive ahead to tilt bed back down")

**Comment by ThomasGaertner** [comment]
I will take this as an "OK" and close....
