### ISSUE TITLE
Unloading grass silage into a BGA silo

### ISSUE THREAD

**Issue by manni3477** [Courseplay/courseplay#876]
Hallo! 
bei mir ist das problem das wenn er durch ein fahrsilo fährt beim ladewagen (original strautmann )die klappe aufmacht, ne tonne abläd und dann ohne weiter abzuladen wieder weg fährt und die klappe bleibt offen und dosier walzen drehen weiter. und beim güllezubringer läd er nicht selbstandig am trigger auf.....
log ist sauber.
ihr macht ne sau geile arbeit, weiter so und guten rutsch. MFG. manni

spiele mig map region celle.

Hello!
for me it is a problem that if he hits a bunker silo during loading wagons (original strautmann ) the flap opens , ne tonne abläd and then unload without further moves away again and the flap remains open and rolling dosier turning. and when he invites manure feeder not selbstandig the trigger on .....
log is clean.
it makes ne geile sau work , keep it up and happy . MFG. manni

games mig map region celle .

---

_**Edit by Jakob:** proper translation_
> I have the problem that my trailer (default Strautmann), when trying to unload into the BGA silo, unloads 1 ton and then continues driving without unloading, leaving the flap open and the rollers running.

**Comment by Satissis** [comment]
What version of cp are you using ? and could you add the log to gist and add the link for it here.

**Comment by Satissis** [comment]
Closed due to inactivity.
Reopen it if still needed and providing the infos asked fore
