### ISSUE TITLE
Attempt to index field 'Band' (a nil value)

### ISSUE THREAD

**Issue by NOR3MSTI** [Courseplay/courseplay#881]
The game loads but courseplay freezes at scanning fields, then the game freezes. Here is a copy of the  error message, I looked all around the mod mapsiloband's lua file for the nil value, everything works fine with courseplay removed from mod folder. it may not be courseplay causing it but I wanted to give you guys a look at it before I start hacking at file scripts.
Error: Running LUA method 'update'.
C:/Users/NOR3MSTI/Documents/My Games/FarmingSimulator2015/mods//States/map/myobjects_/scripts/MapSiloBand.lua:116: attempt to index field 'Band' (a nil value)
im using courseplay v4.01 and it has the same error with previous version.

**Comment by ThomasGaertner** [comment]
closed due to inactivity
