### ISSUE TITLE
Unloading grass from frontloader shovel into trailer not possible

### ISSUE THREAD

**Issue by Granada123** [Courseplay/courseplay#885]
Hello,

first of all: Thank you for this great mod.
And now btt. When I start  mode 9 to fill the original kröger HKD302 or the KuhnProfile 1880 with grass
the tractor stops with a full shovel of grass in front of the trailer and doesn´t turn the shovel to unload it.
Manually you can unload the shovel and then the tractor drives correctly the course untill it stops again in front of the trailer. It is the same with the liebherrTL432.
To get grass in the shovel, I uses this mod: addFillTypes

Thank you in advance.

**Comment by ThomasGaertner** [comment]
please post your courseplay.xml to gist and deliver the link and tell me the name of the course you used...

**Comment by Granada123** [comment]
Hmmm, I tried to reconstruct it in a new savegame  with only three mods and now it works fine :(
That took me more than an hour....
Sorry for that.
