### ISSUE TITLE
Error crashes FS15 and deletes all saved courses

### ISSUE THREAD

**Issue by gnbrotz** [Courseplay/courseplay#886]
I've discovered that if one attempts to delete a particular course (clicking the trash can icon) while that course is in use, the whole game crashes, and all previously saved courses are deleted. This happened first thing this morning, and I wasn't quite sure what caused it, and then later today, I was able to replicate the issue, while paying close attention to what was going on when it occurred.

**Comment by JakobTischler** [comment]
Are you sure this only happens with currently active courses on your setup? Or maybe any course that's deleted? Please post the complete log of the crash.

**Comment by gnbrotz** [comment]
Jakob,

I am fairly certain it only happens with active courses. I have had this
problem three times now. The last time, I *thought* I had first reset the
route, but I may not have. I have successfully deleted inactive courses
without crashing the game, so if it is occurring then also, it does not
happen on every occasion.

I have attached my log file. I have continued to play the game since the
last crash, and I don't have a copy of the log from immediately following a
crash. I don't know if that info would be overwritten or not. If so, I can
again force the crash, and send the log immediately after the crash occurs.

Greg

On Thu, Jan 1, 2015 at 5:44 PM, Jakob Tischler <notifications@github.com>
wrote:

> Are you sure this only happens with currently active courses on your
> setup? Or maybe any course that's deleted? Please post the complete log of
> the crash.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Courseplay/courseplay/issues/886#issuecomment-68500962>
> .
>
GIANTS Engine Runtime 6.0.2 64bit (Build Date: Dec  8 2014)
Copyright (c) 2008-2014, GIANTS Software GmbH (giants-software.com), All Rights Reserved.
Copyright (c) 2003-2014, Christian Ammann and Stefan Geiger, All Rights Reserved.
Application: FarmingSimulator2015
Main System
  CPU: Intel(R) Core(TM) i7 CPU       Q 740  @ 1.73GHz
  Memory: 8115 MB
  OS: Windows NT 6.1 64-bit
Physics System
  Version: 5.9.4
  Thread(s): 2
Input System
  Keyboard enabled
  Mouse enabled
  Gamepad/Joystick disabled
  Force Feedback disabled
Sound System
  Driver: OpenAL
  Version: 1.1
  Device:  Generic Software
  Max. sources: 256
Render System
  Driver: OpenGL
  Card Vendor: NVIDIA Corporation
  Renderer: GeForce GT 425M/PCIe/SSE2
  Version: 4.4.0 NVIDIA 344.48
  Shader Version: 4.40 NVIDIA via Cg compiler
    max_texture_layers: 16
    OpenGL initialization successful
Hardware Profile
  Level: Medium (auto)
  View Distance Factor: 1.000000
  Shadow Quality: 1.000000
  Skip Mipmaps: 1
  LOD Distance Factor: 1.000000
  Terrain LOD Distance Factor: 1.000000
  Foliage View Distance Factor: 1.000000
  Volume Mesh Tessellation Factor: 1.000000
  Tyre Tracks Segments Factor: 1.000000
Farming Simulator 15
  Version: 1.2.0.0 1.2 RC6
  Available Languages: en fr es it nl pt
  Language: en
Game vehicle types loaded
Mod directory: C:/Users/User/Documents/My Games/FarmingSimulator2015/mods/
Load mod: FronloaderConveyor
Load mod: FS15_kroneBigM500_v1_01
Load mod: FSM_Fortuna_D2_LS15
Load mod: FSM_Fortuna_SA_560_LS15
Load mod: grimmeTectron415v1_2
Load mod: Horsch_Pronto18m
Load mod: Horsch_Pronto9m
Load mod: Huehnerstall
Load mod: MischStation
Load mod: mod_krampeBandit750
Warning: Only zip mods are supported in multiplayer. You need to zip the mod mod_krampeBandit750 to use it in multiplayer.
Load mod: placeable_fertilizerTank_LS15
Load mod: placeable_gasTank_LS15
Load mod: placeable_seedPallets_LS15
Load mod: placeable_strawPowerPlant
Load mod: Ramp
Load mod: SelfmadeConcreteWeights
Load mod: TelehandlerConveyor
Load mod: VehicleGroupsSwitcher
Load mod: ZZZ_courseplay
Load mod: ZZZ_GPS
  Register vehicle type: FronloaderConveyor.FConveyor
  Register vehicle type: FSM_Fortuna_D2_LS15.fD2LS15
  Register vehicle type: FSM_Fortuna_SA_560_LS15.fSA560LS15
  Register vehicle type: grimmeTectron415v1_2.grimmeMaxtron620
  Register vehicle type: grimmeTectron415v1_2.grimmeTectron415
Warning: missing category value in store item modDesc.storeItems.storeItem(0)
  Register vehicle type: SelfmadeConcreteWeights.Heckgewicht2
  Register vehicle type: TelehandlerConveyor.Conveyor
Script loaded: VehicleGroupsSwitcher.lua (v2.0.2)
Error: C:/Users/User/Documents/My Games/FarmingSimulator2015/savegame1/courseplay.xml(1702). Error reading end tag..
C:/Users/User/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/normal.i3d (0.78 ms)
C:/Users/User/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/cross.i3d (2.42 ms)
C:/Users/User/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/wait.i3d (3.27 ms)
C:/Users/User/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/start.i3d (2.90 ms)
C:/Users/User/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/stop.i3d (2.96 ms)
### Courseplay: initialized 36/36 files (v4.00.0147)
	*********************************************** WARNING ***********************************************
	* You are using a development version of Courseplay, which may and will contain errors, bugs,         *
	* mistakes and unfinished code. Chances are your computer will explode when using it. Twice.          *
	* If you have no idea what "beta", "alpha", or "developer" means and entails, remove this version     *
	* of Courseplay immediately. The Courseplay team will not take any responsibility for crop destroyed, *
	* savegames deleted or baby pandas killed.                                                            *
	*******************************************************************************************************
### Courseplay: installed into 22 vehicles
data/sky/sky_day_night.i3d (10.77 ms)
data/sky/rain.i3d (2.58 ms)
data/sky/hail.i3d (1.77 ms)
data/sky/dust.i3d (1.25 ms)
data/maps/map02.i3d (9475.90 ms)
Error: C:/Users/User/Documents/My Games/FarmingSimulator2015/savegame1/courseplay.xml(1702). Error reading end tag..
Error: C:/Users/User/Documents/My Games/FarmingSimulator2015/savegame1/courseplay.xml(1702). Error reading end tag..
--- loading GPS mod V4.0 --- (by upsidedown and gotchTOM)
Disabled withering for: wheat, barley, rape, maize, sugarBeet
data/vehicles/tools/poettinger/poettingerTop1252.i3d (49.04 ms)
data/vehicles/tools/suer/suerSB700.i3d (6.25 ms)
data/vehicles/frontLoaders/stoll/stollToolLogFork.i3d (19.14 ms)
data/vehicles/frontLoaders/stoll/stollToolShovel.i3d (2.39 ms)
C:/Users/User/Documents/My Games/FarmingSimulator2015/mods//FronloaderConveyor/FConveyor.i3d (36.73 ms)
data/vehicles/steerable/lamborghini/Mach230VRT.i3d (51.59 ms)
dataS2/character/player/player.i3d (454.61 ms)
GPS mod inserted into Drivable Specialization (should happen only once!)
GPS mod inserted into Vehicle Camera (should happen only once!)
data/vehicles/tools/suer/suerSB1000.i3d (2.41 ms)
data/vehicles/frontLoaders/stoll/stollToolPalletFork.i3d (2.24 ms)
data/vehicles/balers/newHolland/newHollandBB1290.i3d (27.96 ms)
data/maps/models/objects/squarebales/baleStraw240.i3d (7.30 ms)
data/vehicles/trailers/arcusin/arcusinAutostackFS63-72.i3d (29.30 ms)
data/vehicles/frontLoaders/stoll/stollToolBaleFork.i3d (2.41 ms)
C:/Users/User/Documents/My Games/FarmingSimulator2015/mods//Horsch_Pronto18m/pronto18DC.i3d (67.25 ms)
data/vehicles/tools/krone/kroneSwadro2000.i3d (44.90 ms)
data/vehicles/tools/kuhn/kuhnVariMaster153.i3d (29.47 ms)
data/vehicles/particleAnimations/kuhn/kuhnVariMaster153.i3d (7.86 ms)
data/vehicles/trailers/krampe/krampeBandit750.i3d (34.84 ms)
data/vehicles/cutters/caseIH/caseIH3412Corn.i3d (17.39 ms)
data/vehicles/trailers/amazone/amazoneZGB8200.i3d (25.48 ms)
data/vehicles/steerable/caseIH/caseIH9230.i3d (67.65 ms)
data/vehicles/cutters/caseIH/caseIH3162Cutter.i3d (41.86 ms)
data/vehicles/steerable/newHolland/newHollandT8320.i3d (58.70 ms)
data/vehicles/tools/suer/suerSB1600.i3d (2.39 ms)
data/vehicles/trailers/strautmann/strautmannTeraVitesse5201.i3d (34.79 ms)
data/vehicles/steerable/caseIH/caseIHQuadtrac620.i3d (45.95 ms)
data/vehicles/cutters/krone/kroneEasyCollect1053.i3d (36.01 ms)
data/vehicles/steerable/krone/kroneBigX1100.i3d (42.42 ms)
data/vehicles/steerable/newHolland/newHollandT6160.i3d (58.99 ms)
data/vehicles/frontLoaders/stoll/stollFrontLoaderFZ.i3d (4.90 ms)
data/vehicles/trailers/bergmann/bergmannHTW65.i3d (26.34 ms)
data/vehicles/cutters/capello/capelloQuasarHS16.i3d (34.48 ms)
C:/Users/User/Documents/My Games/FarmingSimulator2015/mods//grimmeTectron415v1_2/grimmeMaxtron620.i3d (621.26 ms)
C:/Users/User/Documents/My Games/FarmingSimulator2015/mods//FS15_kroneBigM500_v1_01/kroneBigM500.i3d (378.53 ms)
Warning: Invalid GroundReferenceNode '0' (vehicle.workAreas.workArea(0))! Indexing starts with 0
Warning: Invalid GroundReferenceNode '1' (vehicle.workAreas.workArea(1))! Indexing starts with 0
Warning: Invalid GroundReferenceNode '2' (vehicle.workAreas.workArea(2))! Indexing starts with 0
Warning: Invalid GroundReferenceNode '3' (vehicle.workAreas.workArea(3))! Indexing starts with 0
data/vehicles/steerable/man/man22s.i3d (60.85 ms)
data/vehicles/trailers/krampe/krampeSB3060.i3d (22.47 ms)
C:/Users/User/Documents/My Games/FarmingSimulator2015/mods//Ramp/ramp.i3d (16.56 ms)
C:/Users/User/Documents/My Games/FarmingSimulator2015/mods//placeable_gasTank_LS15/gasTankPlaceable.i3d (10.17 ms)
C:/Users/User/Documents/My Games/FarmingSimulator2015/mods//placeable_seedPallets_LS15/seedPalletsPlaceable.i3d (28.99 ms)
C:/Users/User/Documents/My Games/FarmingSimulator2015/mods//placeable_fertilizerTank_LS15/waterTankPlaceable.i3d (9.50 ms)
C:/Users/User/Documents/My Games/FarmingSimulator2015/mods//MischStation/MischStation.i3d (90.05 ms)
data/placeables/beehive/beehive.i3d (12.77 ms)
dataS/character/player/playerCCT.i3d (9.66 ms)
data/firstPerson/chainsaws/husqvarna/husqvarna550.i3d (19.00 ms)
Error: C:/Users/User/Documents/My Games/FarmingSimulator2015/savegame1/courseplay.xml(1702). Error reading end tag..
Error: C:/Users/User/Documents/My Games/FarmingSimulator2015/savegame1/courseplay.xml(1702). Error reading end tag..
Error: C:/Users/User/Documents/My Games/FarmingSimulator2015/savegame1/courseplay.xml(1702). Error reading end tag..
Error: C:/Users/User/Documents/My Games/FarmingSimulator2015/savegame1/courseplay.xml(1702). Error reading end tag..
Error: C:/Users/User/Documents/My Games/FarmingSimulator2015/savegame1/courseplay.xml(1702). Error reading end tag..

**Comment by Satissis** [comment]
First off, you are using an old version of cp (v4.00.0147) so could you try getting the released version from modhoster or fs-uk or the latest developing version and see it it still is an problem and if it is, then repost the log again.

**Comment by gnbrotz** [comment]
Obtaining a newer version has resolved this issue for me.
