### ISSUE TITLE
Slurry Sales

### ISSUE THREAD

**Issue by Llogeyr** [Courseplay/courseplay#887]
Is it possible to sell slurry using the method found in the manual. I have started my course on a straight away, ran it through the slurry fill trigger, ran down to the slurry sales point and to the stop point. (I have also included a wait point at the sales trigger. Same outcome with or without.) The slurry tanker will not load or unload at either trigger point. Runs the course like a champ though :) I am sure I am missing something.

**Comment by Raints** [comment]
I recommend you use for sale mode 2 and start from slurry fill trigger.

**Comment by JakobTischler** [comment]
> I recommend you use for sale mode 1 and start from slurry fill trigger.

Nope. Liquid manure transport is to be done in the liquid manure transport mode, as the name implies.

---

@Llogeyr: 

1. Which vehicles/tools are involved?
2. What type of trigger is the sales trigger? TipTrigger? SprayerFillTrigger? Another type?
3. Post the log.

**Comment by Llogeyr** [comment]
I was using a NH 8.435 and a Kotte Garant Slurry Tanker. The tanker is a mod of the original giants. Also was using version .005. I also found that with this new version the manure sale was not stopping at the tip points either, Was using a NH 8.435 and the Krampe BBS900 Tipper. I had it working with version .003

**Comment by JakobTischler** [comment]
Concerning the trigger: there is nothing (that I know of) like sales trigger. It could be a regular tip trigger with the `liquidManure` fillType, it could be a UPK fill trigger, a regular liquid manure fill trigger that relies on an unloading spec in the liquid manure transporter etc. Please check the trigger type in the map and report.

**Comment by Llogeyr** [comment]
The .i3d says it is a tip trigger. Could be something with that trailer.

**Comment by JakobTischler** [comment]
Mode 8 (liquid manure transport) doesn't support tipTriggers, only fillTriggers. And quite frankly, if a modder thinks unloading liquid manure with a tipTrigger would be a good idea, then something's gone wrong in my opinion. 

You (or the map's modder) should have a look at using UPK for stuff like that.

**Comment by Llogeyr** [comment]
Ok thank you. I will take a check out UPK. Thanks again for looking into this.
