### ISSUE TITLE
Text outside the screen

### ISSUE THREAD

**Issue by gui7545** [Courseplay/courseplay#890]
Hello,
I have test the last version today but some notification text ( vehicle is in traffic) appear outside the screen.
![fsscreen_2015_01_02_00_30_30](https://cloud.githubusercontent.com/assets/2854643/5593651/eb922b16-921d-11e4-8f9a-38c6060e9653.png)

Thanks

**Comment by JakobTischler** [comment]
99% sure that this is due to another mod not properly resetting the text rendering settings correctly (from what I'm seeing, that BGA silo amount hud). I'll implement a safety mechanism against faulty mods like that soon.

**Comment by gui7545** [comment]
Or you can ask the developer of this mod ( Silage Bunker HUb) to do it more properly ?
