### ISSUE TITLE
Error with fieldScanInfo.bgOverlay when switching map

### ISSUE THREAD

**Issue by Vanguard22** [Courseplay/courseplay#891]
If I play on a map with fieldscan enabled, then switch to a map that doesn't and exit, it bombs out in the log with fieldScanInfo.bgOverlay is a nil value.

The code @ CpManager.lua:176 checks for existence of self.fieldScanInfo, which could be leftover from previous map. Possible solution, add:
self.fieldScanInfo = nil;
to line 181

**Comment by JakobTischler** [comment]
When exactly does it crash? `loadMap()`? `update()`? `deleteMap()`? Can you post your log from when the crash happens, please?

**Comment by Vanguard22** [comment]
Just as I'm exiting the second map:
Error: Running LUA method 'mouseEvent'.
.../mods//ZZZ_courseplay/CpManager.lua:177: attempt to index field 'bgOverlay' (a nil value)
