### ISSUE TITLE
Mode 9 Fill and empty shovel jumps over waypoints

### ISSUE THREAD

**Issue by DieWaage** [Courseplay/courseplay#893]
Hello courseplay team,

happy new year!

I found following unexpected behavior while using Mode 9: Fill and empty shovel. The log doesn't show any error.

My environment:
- LS 15 v1.2
- CP 4.01.0010.dev
- Vehicle: NH T4 + Suer 1600kg weight + NH front loader + Stoll uni. shovel (all default Giants)
- Bjornholm map
- no other mods in mod folder

Log and used course are at https://gist.github.com/DieWaage/d0b0f8b436344feafe54

The tractor is leaving the BGA bunker silo in backward driving. Once he reach the turn point (which is waypoint 34 in my course) ...

![fsscreen_2015_01_02_14_48_14](https://cloud.githubusercontent.com/assets/5517105/5596627/8c9cc366-9293-11e4-8071-4e87d0958ecf.jpg)

to start forward driving to the unloading point CP "jumps" directly to waypoint 40 (in the UI it looks like CP counts through the WP 35-39) of my course

![fsscreen_2015_01_02_14_43_33](https://cloud.githubusercontent.com/assets/5517105/5596683/8dbd6538-9294-11e4-8b4a-cff7939bc503.jpg)

and cut off a part of the course (green is recorded part and red is the driven part). In my current case this still works as there is enough space around the course. But I believe in other maps this could lead to collisions with static objects especially if there is a need to drive in a turn to the unload trigger.

Best Regards

**Comment by JakobTischler** [comment]
Alright, so I've tested your setup (same vehicle and tools, same map, same course), and can confirm that what you describe is happening. But at the same time, I'm reluctant to call this a *big problem*, as 1) while it may look weird, the tractor still reaches its target and unloads successfully, and 2) the "next waypoint finding" is a rather delicate method. Touching and changing it would most likely cause problems with all other modes and situations, and probably also cause a rift in the space-time continuum.

Thanks for understanding.
