### ISSUE TITLE
V4.01 The need to remove assignment before combine can be unloaded

### ISSUE THREAD

**Issue by robbiewm** [Courseplay/courseplay#894]
I love courseplay to start with, but just started to use V4.01 and found when I set my empty combine away, I set up as normal but also as stated can't find combine automatically, but set all up and just adjust the start to 70, and move on by 90, this is all I change and find combine manually, then set away, I drive the combine and harvest the field and let courseplay do it's job, first pick up no problems second pick up tractor and trailer stay still, and don't come to me, so I looked in the tractors hud for courseplay to see a signal saying combine has told me to stop "remove combine assignment", so I did and courseplay started to work again, started harvesting again and the same thing happend, had to jump into the tractor and delete combine assignment to get it to work again. PS: this is only a minor thing guy's awesome work as always.

**Comment by PromGames** [comment]
You must be sure that your course for the truck, in mode2 to collect from combine, or Mode3 overloader (auger wagon) must be setup in some way that the start point and the last point of that course is placed inside the field, then automatic combine search is working.

**Comment by FSFiestel** [comment]
I have the exact same issue with V4.01 as robbiewm described.  The issue seems to be that after "the combine is telling me to stop", it won't reset itself to "waiting for fill level" until you "remove combine assignment".

**Comment by FSFiestel** [comment]
robbiewm - I might have discovered a work around until this issue is fixed.  I did some testing and the offloading tractor seemed to work like it should if you don't extend the combine auger pipe until the until the tractor/tipper is along side the combine.  I also changed the driver priority from "distance" to "fill level" (I think it was called) from the first tab in the courseplay window when in the combine, so I'm not sure if it was one or both of those things that made it work.  I did have to "remove combine assignment" at least once or twice and then it seemed to work properly after that.  I'll have to do some more testing, but I believe it may be a problem with the driver priority set to "distance".

**Comment by ThomasGaertner** [comment]
I did some changes in mode 2 would you please test again with v0051 or higher and confirm that the issue is still valid ?

**Comment by FSFiestel** [comment]
Please forgive me if I'm overstepping my bounds.  I'm not sure if robbiewm is monitoring this thread or not as I haven't seen any comments from him.  I've been testing and this issue with Mode 2 seems to be fixed I think as far back as v0047.  I'm using v0052 right now and Mode 2 works good.

However, the issue I'm seeing now is that after the combine is offloaded and the offloading vehicle stops and waits for the combine to clear the area (a new feature which is great, it won't run over the combine now :-) ), the offloading vehicle seems to do a clearing maneuver.  This is fine if you are halfway down the field, but if you are at the end of the field, the offloading vehicle drives past the field border and can get itself into trouble like getting stuck in trees, fences, rocks, or driving off cliffs, etc.  I think that the offloading vehicle should not go beyond the field border to prevent it from getting into trouble.  If it hits the end of the field, maybe make it do a 180 degree turn in the opposite direction to where the fruit is - ie. turn left 180 degrees if the fruit is on the right.  As long as it doesn't park in the fruit, I think that would probably work ok.

**Comment by ThomasGaertner** [comment]
I will take this Issue as solved. @FSFiestel : at the field edge we already make a 180 degree turn to the field so we try to get out of the field as less as possible. if its a continuous problem , please make a new issue , with screen shots or maybe a video of the case Thanks
