### ISSUE TITLE
Giants physics and CP's lockdown

### ISSUE THREAD

**Issue by Muaddib-1** [Courseplay/courseplay#895]
A little side effect of the lockdown CP places on vehicles until Giants gets their crap together and fixes their physics.  Haven't had this effect gameplay yet. I just find it rather amusing. 

Before and after stopping a driver after it had been sitting for a few moments at the end of it's course.
![2015-01-03_00001](https://cloud.githubusercontent.com/assets/5287689/5601952/b708a83e-92ef-11e4-96ff-5cfbf1a40387.jpg)
Back end of the tractor and attached equipment slide wherever they like.  

![2015-01-03_00002](https://cloud.githubusercontent.com/assets/5287689/5601949/b707551a-92ef-11e4-8f11-55262cd8a9e6.jpg)
When the course is stopped the front end pops over to where it would be if it hadn't been locked down.

![2015-01-03_00004](https://cloud.githubusercontent.com/assets/5287689/5601950/b7077b8a-92ef-11e4-9c2e-e6dc2f6fcd4d.jpg)
![2015-01-03_00005](https://cloud.githubusercontent.com/assets/5287689/5601951/b7088e6c-92ef-11e4-8336-1006ec7204f1.jpg)

**Comment by gui7545** [comment]
I have the same issue with a loader at the BGA. The loader is compressed as your first picture. It is maybe the result of the "anti-sliding " that tell to courseplay to fixed his position. Jakob explains it in https://github.com/Courseplay/courseplay/issues/851#issuecomment-68012315 .

**Comment by Muaddib-1** [comment]
It is absolutely caused be that. The thing that is happening now is that the equipment is still sliding and as soon as you release the vehicle it jumps to the equipment.  It's possible it could negate the "anti-sliding" code altogether depending on how you use CP.

**Comment by JakobTischler** [comment]
Just for shits and giggles, let's try the following: replace the `courseplay:getAndSetFixedWorldPosition()` function in `settings.lua` with:

```lua
function courseplay:getAndSetFixedWorldPosition(object, recursive, isImplement)
	if object.cp.fixedWorldPosition == nil then
		object.cp.fixedWorldPosition = {};
		local px,py,pz, rx,ry,rz;
		for i,comp in ipairs(object.components) do
			px,py,pz = getWorldTranslation(comp.node);
			rx,ry,rz = getWorldRotation(comp.node);
			object.cp.fixedWorldPosition[i] = {
				px = px,
				py = py,
				pz = pz,
				rx = rx,
				ry = ry,
				rz = rz
			};

			if isImplement and i == 1 then
				break; -- only component 1 for implements!
			end;
		end;
	end;

	for compIndex,data in ipairs(object.cp.fixedWorldPosition) do
		object:setWorldPosition(data.px,data.py,data.pz, data.rx,data.ry,data.rz, compIndex);
	end;

	if recursive and object.attachedImplements then
		for _,impl in pairs(object.attachedImplements) do
			courseplay:getAndSetFixedWorldPosition(impl.object, recursive, true);
		end;
	end;
end;
```

**Comment by Muaddib-1** [comment]
Well that fixed the tractor from playing accordion.  The implement still slides and the tractor teleports to it when you stop the driver/course.

![2015-01-04_00001](https://cloud.githubusercontent.com/assets/5287689/5606352/19d3a1ec-93f1-11e4-8594-ee10b69855c3.jpg)
![2015-01-04_00003](https://cloud.githubusercontent.com/assets/5287689/5606353/1d99d710-93f1-11e4-9e80-ee4fc79f01d6.jpg)
![2015-01-04_00004](https://cloud.githubusercontent.com/assets/5287689/5606354/1fd4c1c0-93f1-11e4-9461-e7ca86b0729f.jpg)

**Comment by JakobTischler** [comment]
Thanks for the report, that's exactly what I expected to happen - which is good. The bad part is: chaining down implements could result in other problems, first and foremost - if they are a trailer, for example - them not unloading, as they can't move the skip.

But there's no way around testing it: in `drive.lua`, replace the one occurrence of `courseplay:getAndSetFixedWorldPosition(self);` with
```lua
courseplay:getAndSetFixedWorldPosition(self, true);
```

and replace the one occurrence of `courseplay:deleteFixedWorldPosition(self);` with
```lua
courseplay:deleteFixedWorldPosition(self, true);
```

This tells the vehicle to also fix the implement's first component.

**Comment by Muaddib-1** [comment]
As expected, the implements first section locks down but the second still slides.
I made a little course around the farm to test loading and unloading.  The only anomaly I saw was am occasional vanishing act by the bandit 750 when loading, the krampe 900s didn't exhibit this though.  I'll try it without these modifications.
![2015-01-04_00005](https://cloud.githubusercontent.com/assets/5287689/5606486/379fc4de-93f7-11e4-829f-5ac580803bb6.jpg)
![2015-01-04_00006](https://cloud.githubusercontent.com/assets/5287689/5606488/3b417c86-93f7-11e4-8dae-19241373f536.jpg)
![2015-01-04_00008](https://cloud.githubusercontent.com/assets/5287689/5606489/4032b75a-93f7-11e4-9aa2-399ef30a58a8.jpg)
![2015-01-04_00009](https://cloud.githubusercontent.com/assets/5287689/5606491/44caaa7a-93f7-11e4-88f2-3318df0c70f8.jpg)
![2015-01-04_00010](https://cloud.githubusercontent.com/assets/5287689/5606492/471f0fa0-93f7-11e4-9c40-5c9f8c6db33c.jpg)

**Comment by JakobTischler** [comment]
Couple of thoughts here:

1. In theory, we should only apply the fixed position in modes 1, 2 and 3. The situations where the sliding really creates problems is when a trailer is to be filled. In the other modes, sliding vehicles are obviously bad, but not gameplay breaking.
2. Why are you using a waiting point in mode 1 for loading. Loading should *always* start at the course's first point. Only if people use the expected methods for the courses, we can apply proper anti-sliding functionality.

**Comment by Muaddib-1** [comment]
#2 thats actually a different vehicle in field testing the sliding, it's a t8.435, the vehicle pictured is a t9.560

**Comment by JakobTischler** [comment]
Oh, right, now that I've had a second look at the third picture I realize I was wrong. I don't really understand why the Krampe disappears (read: moves away) though in mode 1.

**Comment by Muaddib-1** [comment]
It did it a few times but I can't repeat it now. #shrug#

**Comment by Muaddib-1** [comment]
I broke it.....I started a test course around the farm again. Stopped it while loading when the first screenshot happened. Now when I start a course, any course, it teleports one or more trailers and the weight back to the filling point. 
![2015-01-04_00011](https://cloud.githubusercontent.com/assets/5287689/5606588/605d6292-93fb-11e4-9dc2-65ea6b9c8741.jpg)
![2015-01-04_00012](https://cloud.githubusercontent.com/assets/5287689/5606589/61cfc32c-93fb-11e4-9c80-d75db0006262.jpg)
![2015-01-04_00013](https://cloud.githubusercontent.com/assets/5287689/5606590/63742bbe-93fb-11e4-9ad5-9e12e8269f01.jpg)

**Comment by JakobTischler** [comment]
Am I right to assume that in your last post, in those three pictures, it is the tractor that is sliding away, not the trailers or front weight?

**Comment by Muaddib-1** [comment]
That was with the code to lock the 1st implement.  It was when it hit the fill or tip triggers the trailers and weight would teleport between the 2 triggers. There wasn't really any time to slide. I was seeing how it would react to 2 trailers when you had the 1st locking down. It didn't like it.

**Comment by Muaddib-1** [comment]
I don't know much about the way the games physics work but this has been bugging me. 
Why do the implements slide when the tractor is locked down? 
Does the game think the tractor is still moving even though it is not (the tractor teleporting to the implement suggests to me this is the case) or is the implement sliding as if it is not connected to a tractor?
If it thinks the tractor is moving isn't there a way to tell it otherwise. 
If the implements are sliding independently could you force it to periodically update it's connection to the tractor?

**Comment by JakobTischler** [comment]
Ok, so, while we fix the tractor's position, the physics engine is still moving it virtually. That's why, when our "chaining down" stops, the tractor "jumps" to a slightly different position - the position that the physics engine has moved the tractor to in the meantime.

The implements sliding separately from the tractor is because - as mentioned above - while we chain down the vehicle, the physics engine still slides the vehicles around. Since we don't chain down the implements, they move separately from the tractor. Meaning, in the end we'll have to set a fixed position for all components in all the vehicle's implements.

---

So, let's try something here:
Using build 0021, in `drive.lua`, replace [lines 487-489](https://github.com/Courseplay/courseplay/blob/29651bb8de2781deff57a8e0e37ce387af1fa319/drive.lua#L487-L489) with
```lua
		elseif self.cp.curSpeed < 0.2 and (self.cp.mode == courseplay.MODE_GRAIN_TRANSPORT or self.cp.mode == courseplay.MODE_OVERLOADER) and self.cp.currentTipTrigger == nil then
			-- ## The infamous "SUCK IT, GIANTS" fix, a.k.a "chain that fucker down, it ain't goin' nowhere!"
			courseplay:getAndSetFixedWorldPosition(self, true);
```

In `drive.lua`, replace [line 498](https://github.com/Courseplay/courseplay/blob/29651bb8de2781deff57a8e0e37ce387af1fa319/drive.lua#L498) with
```lua
		courseplay:deleteFixedWorldPosition(self, true);
```

In `settings.lua`, replace the `courseplay:getAndSetFixedWorldPosition()` function in [lines 1584-1598](https://github.com/Courseplay/courseplay/blob/29651bb8de2781deff57a8e0e37ce387af1fa319/settings.lua#L1584-L1598) with 
```lua
function courseplay:getAndSetFixedWorldPosition(object, recursive, isImplement)
	if object.cp.fixedWorldPosition == nil then
		print(('%s: getAndSetFixedWorldPosition()'):format(nameNum(object)));
		object.cp.fixedWorldPosition = {};
		local px,py,pz, rx,ry,rz, qx,qy,qz,qw;
		for i,comp in ipairs(object.components) do
			px,py,pz = getTranslation(comp.node);
			rx,ry,rz = getRotation(comp.node);
			qx,qy,qz,qw = getQuaternion(comp.node);

			print('    component ' .. i);
			print(('        px=%.1f, py=%.1f, pz=%.1f'):format(px,py,pz));
			print(('        rx=%.4f, ry=%.4f, rz=%.4f'):format(rx,ry,rz));
			print(('        qx=%.4f, qy=%.4f, qz=%.4f, qw=%.4f'):format(qx,qy,qz,qw));

			object.cp.fixedWorldPosition[i] = {
				translation = { px,py,pz },
				rotation = { rx,ry,rz },
				quaternion = { qx,qy,qz,qw }
			};

			--[[if isImplement and i == 1 then
				break; -- only component 1 for implements!
			end;]]
		end;
	end;

	local px,py,pz, rx,ry,rz, qx,qy,qz,qw;
	for compIndex,data in ipairs(object.cp.fixedWorldPosition) do
		local comp = object.components[compIndex];

		comp.lastTranslation = data.translation;
		comp.targetTranslation = data.translation;
		comp.curTranslation = data.translation;
		comp.sentTranslation = data.translation;

		comp.lastRotation = data.quaternion;
		comp.targetRotation = data.quaternion;
		comp.curRotation = data.quaternion;
		comp.sentRotation = data.rotation;

		px,py,pz = unpack(data.translation);
		qx,qy,qz,qw = unpack(data.quaternion);
		object:setWorldPositionQuaternion(px,py,pz, qx,qy,qz,qw, compIndex);
	end;


	if recursive and object.attachedImplements then
		for _,impl in pairs(object.attachedImplements) do
			courseplay:getAndSetFixedWorldPosition(impl.object, recursive, true);
		end;
	end;
end;
```

In `settings.lua`, replace the `courseplay:deleteFixedWorldPosition()` function in [lines 1638-1646](https://github.com/Courseplay/courseplay/blob/29651bb8de2781deff57a8e0e37ce387af1fa319/settings.lua#L1638-L1646) with 
```lua
function courseplay:deleteFixedWorldPosition(object, recursive)
	object.cp.fixedWorldPosition = nil;

	if recursive and object.attachedImplements then
		for _,impl in pairs(object.attachedImplements) do
			courseplay:deleteFixedWorldPosition(impl.object, recursive);
		end;
	end;
end;
```

---

What this effectively does is: In mode 1 when the vehicle isn't unloading, and in mode 3, of the vehicle and all its implements, get the translation, rotation and quaternion of all components [once]. Then until the vehicle is allowed to drive again, force set those values again and again.

There will be a few prints in the log (the values of the initial positions and rotations).

Let me know if it works better.

**Comment by Muaddib-1** [comment]
It seems to be working fairly well.  
A mode 1 tractor-tipper was sliding backwards while waiting for an overloader but it wasn't a problem because it kept pulling forward to the stop point again.  
There was one instance when I first started the course where the dolly and tipper rotated to face north when it reached the stop point and CP chained them down.  "Drive now" unchained and fixed them and it never happened again.

**Comment by JakobTischler** [comment]
> A mode 1 tractor-tipper was sliding backwards while waiting for an overloader 

This actually shouldn't happen. Can you post the log from that occurence please?

**Comment by Muaddib-1** [comment]
No, it's been overridden. I'll see if I can reproduce it. Any debug channel requests?

**Comment by JakobTischler** [comment]
> Any debug channel requests?

No, it's a regular print in the first call of the setter function.

**Comment by Muaddib-1** [comment]
Tractor, dolly, and tipper stopped on an incline waiting to be filled.
https://gist.github.com/Muaddib-1/35c011cb9a71b47276cb

**Comment by JakobTischler** [comment]
So even though the position is fixed it's still sliding away? And then driving forward again a little bit, stopping, fixing its position, sliding away again etc.? That is *very* weird.

Can you send me your savegame please, including the `courseplay.xml` file?

**Comment by Muaddib-1** [comment]
http://www.filedropper.com/savegame3

It's westbridge setup for testing mods.
"Testing inclined chaining" is the course I used, yes it is a weird place to wait but it's just for testing. 
Driving the overloader under the silo fill point seems to activate the Case's sliding for me.

Don't know how this could be related but this happened while I was cleaning up a little and testing again.  
https://gist.github.com/Muaddib-1/8400c371f07f8199d4a1
The collision triggers were going off when I manually drove the NH435 near the Case to overload into it.
Also the farm silo fill point was automatically filling the overloader when I drove under it.....

I'm beginning to think my game is just possessed.

**Comment by Maxcdr** [comment]
Here is what I get on my side: the frontloader is waiting for the tipper to unload silage. When the tipper arrives, the frontloader crashes in the tipper and do not unload.

![fsscreen_2015_01_29_11_39_05](https://cloud.githubusercontent.com/assets/10348839/5956581/9636dcd2-a7af-11e4-9258-8268edefcd9a.png)

**Comment by Satissis** [comment]
#1346
