### ISSUE TITLE
Manual - Fertilizing

### ISSUE THREAD

**Issue by JLWeich** [Courseplay/courseplay#897]
The manual description on how to combine the two courses is unclear. I can generate the course to fertilize the field but then I don't know how to add the second part where it has to go refill. Please help?

**Comment by gui7545** [comment]
The refilling course should be add to the fertilizing course with the "Load/Merge" or Append" buttons:
http://courseplay.github.io/courseplay/en/manual/index.html#hud_manageCourses
So you need to save the refilling course before generating the fertilize course

**Comment by JLWeich** [comment]
I tried it like this but when it ran out of fertilizer, it stopped and said it had to be refilled. I used the standard big slurry tanker and it had to refill from the big green rectangular tank standing next to the field. 

Should the refill course be added to the fertilize course or the other way round?

**Comment by JLWeich** [comment]
Oh, and what type should i use to generate the refill course?

**Comment by JakobTischler** [comment]
The refill course needs to be added *after* the field course, and it has to have at least 7 waypoints.

**Comment by JLWeich** [comment]
I will try it now and let you know.

**Comment by JLWeich** [comment]
Ok, it's working now thanks!
