### ISSUE TITLE
Suggestion: favourites

### ISSUE THREAD

**Issue by OldFisher** [Courseplay/courseplay#898]
Hi. The idea is to replace current course management tab with favourite courses tab. Favourite tab should display only those courses that are marked as favourite for current vehicle (i.e. each vehicle has its own favourite list). Course should be loaded (replacing current course) by clicking on its name, also with "join", "append" and "trashcan" button as well, "trashcan" meaning removing course from favourites, not delete. Of course, the new favourite tab should have access to good old course management tab. Course management should have "add to favourites" button or other control.

**Comment by AndyK70** [comment]
instead of trashcan, I would suggest to use a star, like we are all used to it in browsers for adding and removing to/from favorite list.

**Comment by OldFisher** [comment]
The star would be somewhat confusing too, when removing from favourites, methinks. Some kind of "arrow out" maybe?

**Comment by AndyK70** [comment]
I would think of a white star when not marked as favorite and a yellow star when marked as favorite.

That way, if the star is yellow and you click on it, it removes the course from favorites and the star becomes white.

**Comment by OldFisher** [comment]
The way I imagined it, in course management mode you would need only to be able to add course to favourites (duplicate additions could be just ignored). In favourite mode you would need only to be able  to remove a course from the list.

**Comment by JakobTischler** [comment]
I don't really see a reason for implementing something like this:

1. In my opinion it would have no real benefit - you can already find courses quickly with the folder system and the filter.
2. It would increase the clutter in the course tab, having more buttons and another sub-tab with yet more buttons.
3. The workload for implementing this is relatively high, and we have way more important bugs to fix and driving improvements to implement at the moment.

**Comment by OldFisher** [comment]
I'll answer in the same order.
1. In my opinion, the benefit would be noticeable enough: with only a few courses needed by each vehicle, the switching would be lightning-fast. No scrolling through folders and no filter sorcery can beat a single click.
2. Two modes of course management tab, with favourite mode being default and easy toggle doesn't seem to me that much of a clutter.
3. No argue here. The work is big, the bugs must be fixed, improvements made. I never meant favourites to be something of a high priority. Still, I would be glad to see this feature implemented at some point in the future.

**Comment by JakobTischler** [comment]
I've added the suggestion to the tracker so it won't get lost, but at the moment I have to admit I'm not too excited about the idea. Will let you know when there are updates on this.
