### ISSUE TITLE
Seeder/fertilizer refill

### ISSUE THREAD

**Issue by FyraDrake** [Courseplay/courseplay#900]
All i have found on auto-refill is the vague description on the official website.  For most seeders/fertilizer it isnt much off a problem because the amount held in each machine will provide for a single field with the exception with the potato seeder NEEDS to be filled many times per field.  Can you assist?

**Comment by JakobTischler** [comment]
I don't understand your problem and/or question. What exactly is it that you need? The manual describes [how to use a refill course in the fertilizer/seeding mode](http://courseplay.github.io/courseplay/en/manual/index.html#driveMode4).

**Comment by FyraDrake** [comment]
The question or problem is, if you generate the course, how do you add the refill.  The manual only describes (vaguely) how to use a refill course. 

--"The second part, the automatic refilling, is a regular "A to B" course. It should start at the second waiting point (so, the end of the field work course), then go through the fertilizer/liquid manure/seeding trigger, and back to the field, ending just before the first waiting point of the field work course."  

If you were to generate a field course for seeding, at the end of the course it will end. What would you use to add to the end of that course to make it go to the seed refill? transfer course?

So do you add the two courses together or leave them separate?  Because as i have found if you run two courses together it will only run one then the other no breaks.

**Comment by JakobTischler** [comment]
You have two courses: the field course, and the refilling course. In order to add the refill course to the field course, it needs to be saved first. You then load (or generate) the field course, and then [append the refill course to it](http://courseplay.github.io/courseplay/en/manual/index.html#hud_manageCourses). The new, combined course will be driven in the fertilizer/seeding mode.

**Comment by FyraDrake** [comment]
Ok, I have it figured out.  It is as you say two courses, but there is not a "refill" tab.  It is just two seeding courses appended together.  Thank you for the direction.
