### ISSUE TITLE
Mode 8 Truck don´t wait for Empty Trailer

### ISSUE THREAD

**Issue by Redman293** [Courseplay/courseplay#906]
I use the Field edge Container Kotte FRC and for Transport the MAN with the TSA30000 Liquid Manure Trailer. My Problem is: the MAN is coming Full and overload to the FRC at empty load he drives back to the BGA and refill. At the next round he  coming and overload but he is not empty and now he start a new Round for Refill. Now he´s coming Back the FRC is Full (100%) the MAN can´t overload (still 100%) but he starts after a small Waiting Time (~20 Sec.) a new Round for Refill.

**Comment by jhomer** [comment]
On the Man if you change the "start at" percentage down to "0" the Man should then wait at the overload (waiting point) until it can unload down to "0" capacity, then drive off to refill.

**Comment by Redman293** [comment]
I tried it yesterday evening and this Solution don`t work. It Drives everytime at a Waiting Time ~20 - 30Sec.

**Comment by jhomer** [comment]
I checked this again and is does work. The start at percentage needs to be at zero. Whatever this is set at is when the transporter is allowed to continue driving.
I did some checking and I think the issue your having is the "wait time"
The "wait time" needs to be set at "0" otherwise it will wait the "wait time" and drive off no matter what the "start at" percentage is at.
Try both of these set at "0"

**Comment by Redman293** [comment]
I checked it with the new version. it dosn´t work. Maybe it is a Problem with the Field edge Container Kotte FRC.

**Comment by JakobTischler** [comment]
Please test again with build 0152 or higher. Also make sure your wait time is set to 0.

**Comment by Redman293** [comment]
I checked this with the ver. 0152 in Game is the number 0052 writen.
It is realy better but, 
i use the seting 
"Start at" 50%, 
"drive on at" 0%, 
"REFILL UNTIL" 100%, 
"Waittime" 0Sec. 
First Time the Trailer was not Complettly Empty 16% Liquid Manure he starts and Drive a Round, 
But then he was Full, Ihave wait for 5 Minutes and he was Waiting.

**Comment by JakobTischler** [comment]
Well then everything works as it should. If the overloading trailer's fill level is under the "start at" setting and it doesn't overload anymore, it'll wait for 7 seconds and then continue. But if the fill level is above the "start at" setting, it will wait at that position until it's able to overload again.
