### ISSUE TITLE
Vehicle does not brake at combined courses crossing

### ISSUE THREAD

**Issue by Maxcdr** [Courseplay/courseplay#907]
At crossing of two combined courses, tractor does not brake and slip away from the course.
This occurs whatever speed mode is choosen (from recording or maximum).

![combined_courses](https://cloud.githubusercontent.com/assets/10348839/5626035/dfc65a1c-9585-11e4-8518-94b3e5847c48.png)

Log: https://gist.github.com/Maxcdr/aefc681428b71439bf18
Coursplay.xml: https://gist.github.com/Maxcdr/e32798ef497af71ec0ba

Map: Westbridge Hills
Mods used: none
Coursplay v4.01.0018.dev

**Comment by JakobTischler** [comment]
The main reason the vehicle is racing though is that the average speed at that waypoint is rather high (between 20 and 30 kph), as the last waypoints of course 1 and the first waypoints of course 2 have relatively high speeds.

I'd advise manually lowering the speeds of those waypoints in the `courseplay.xml` file.

**Comment by AndyK70** [comment]
Maybe it could be possible to let courseplay limiting the recorded speed from 1 waypoint before the combining until 1 waypoint after the combining to max 20?
I think, with 20 most normal turnoffs should be driven safely and it wouldn't be too slow if the junction is more straight.
Hmmm if you come along that straight in course 1 with a speed of lets say 50, it could be a hard job breaking down to 20 in 5m... :smile:  Maybe 2 waypoints before the junction point could be helpful.

**Comment by Maxcdr** [comment]
Thanks for your replies.
> I'd advise manually lowering the speeds of those waypoints in the courseplay.xml file.

Yes that will work. But if I want to use Course 1 only, vehicle will slow down at the crossing whereas it is not necessary.
> Maybe it could be possible to let courseplay limiting the recorded speed

This is more what I was thinking about. Could it be possible that Courseplay "automatically" reduce speed when a crossing is "detected"?

**Comment by JakobTischler** [comment]
> Maybe it could be possible to let courseplay limiting the recorded speed from 1 waypoint before the combining until 1 waypoint after the combining to max 20?
I think, with 20 most normal turnoffs should be driven safely and it wouldn't be too slow if the junction is more straight.

Not everything can be automated. Some responsibility still has to lie with the user. If you know you're gonna merge courses, then don't drive with 50 kph at crossing points.
