### ISSUE TITLE
reducing waypoints for generated fieldcourses, saving ressources in courseplay.xml

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#908]
FS15 V1.2, Courseplay 4.01.000

When I was generating a course for field 22 in standard map Björnholm I saw over 1200 generated waypoints. Most of them were on the straight line from one end to another.

I test a bit by manually removing points in the courseplay.xml (and adjusting the numbering of waypoints) and recognized, that there should be some points around the turns, and not only 1 or 2 until the combine is on lane and driving straight again. When the radius of the turn of that combine is a little larger than the working width, the combine has to align with the lane again while driving into it. (maybe this is another issue?)
When I removed all of the points but some around the turns, the lines (when all points are shown) between far away waypoints can sunk into the ground when crossing a hill or way up in the sky when going over a swale. Not very pretty.
![sunken lines](http://www11.pic-upload.de/06.01.15/5qc2u8ok1ws.jpg)

I then tested around with the generateCourse.lua and found a simple way, imho.
My editing let generate 5 waypoints (configurable in variable maxPointsAtTurn) around the turns with normal distance and then a waypoint only every 10th step (configurable in variable stepForPoints) of normal distance.
With my solution the same generated course for field 22 now has 251 waypoints.
![new logic](http://www11.pic-upload.de/06.01.15/73sr11wjyzup.jpg)

Sorry, if my programming is not really sofisticated. First time ever I have to do with Lua and first time ever I write such a long text with image and code on GitHub.

the edited portion: 
``` lua
	---#################################################################
	-- (3) DIMENSIONS, ALL PATH POINTS
	--------------------------------------------------------------------
	courseplay:debug('(3) DIMENSIONS, ALL PATH POINTS', 7);

	local _, _, dimensions = courseplay.fields:getPolygonData(poly.points, nil, nil, true, true);
	courseplay:debug(string.format('minX=%s, maxX=%s', tostring(dimensions.minX), tostring(dimensions.maxX)), 7); --WORKS
	courseplay:debug(string.format('minZ=%s, maxZ=%s', tostring(dimensions.minZ), tostring(dimensions.maxZ)), 7); --WORKS
	courseplay:debug(string.format('generateCourse(%i): width=%s, height=%s', debug.getinfo(1).currentline, tostring(dimensions.width), tostring(dimensions.height)), 7); --WORKS

	local numLanes, pointsPerLane = 0, 0;
	local curLaneDir;
	local pointDistance = 5;
	local pipSafety = 0.1;
	local pathPoints = {};
  ---##############
  -- Begin Edit ---
  local maxPointsAtTurn = 5; 
  local stepForPoints = 10;
  --  End Edit  --
  ---#############

	if dir == "N" or dir == "S" then --North or South
		numLanes = math.ceil(dimensions.width / workWidth);
		pointsPerLane = math.ceil(dimensions.height / pointDistance);
		if numLanes * workWidth < dimensions.width then
			numLanes = numLanes + 1;
		end;
		courseplay:debug(string.format('generateCourse(%i): numLanes=%s, pointsPerLane=%s', debug.getinfo(1).currentline, tostring(numLanes), tostring(pointsPerLane)), 7); --WORKS

		for curLane=1, numLanes do
			--Lane directions
			if dir == "S" then
				--NORTH->SOUTH, starting at NORTH
				if courseplay:isOdd(curLane) then
					curLaneDir = "S";
				elseif courseplay:isEven(curLane) then
					curLaneDir = "N";
				end;
			elseif dir == "N" then
				--SOUTH->NORTH, starting at SOUTH
				if courseplay:isOdd(curLane) then
					curLaneDir = "N";
				elseif courseplay:isEven(curLane) then
					curLaneDir = "S";
				end;
			end;
			courseplay:debug(string.format("curLane = %d, curLaneDir = %s", curLane, curLaneDir), 7); --WORKS

			for a=1, pointsPerLane do
        ---##############
        -- Begin Edit ---
        if a % stepForPoints == 0 or a < (maxPointsAtTurn + 1) or a > (pointsPerLane - maxPointsAtTurn + 1) then
          local curPoint = {
            num = a + ((curLane-1) * pointsPerLane);
            lane = curLane;
            laneDir = curLaneDir;
            x = dimensions.minX + (workWidth * curLane) - (workWidth/2);
            z = dimensions.minZ;
          };

          if crn == "NW" or crn == "SE" then
            if courseplay:isOdd(curLane) then
              curPoint.ridgeMarker = ridgeMarker["left"];
            elseif courseplay:isEven(curLane) then
              curPoint.ridgeMarker = ridgeMarker["right"];
            end;
          elseif crn == "SW" or crn == "NE" then
            if courseplay:isOdd(curLane) then
              curPoint.ridgeMarker = ridgeMarker["right"];
            elseif courseplay:isEven(curLane) then
              curPoint.ridgeMarker = ridgeMarker["left"];
            end;
          end;

          if crn == "NE" or crn == "SE" then
            curPoint.x = dimensions.maxX - (workWidth * curLane) + (workWidth/2);
          end;

          if curLaneDir == "S" then
            curPoint.z = dimensions.minZ + (pointDistance * (a-1));

            if curPoint.z >= dimensions.maxZ then
              curPoint.z = dimensions.maxZ - pipSafety;
            end;
          elseif curLaneDir == "N" then
            curPoint.z = dimensions.maxZ - (pointDistance * (a-1));

            if curPoint.z <= dimensions.minZ then
              curPoint.z = dimensions.minZ + pipSafety;
            end;
          end;

          --last lane
          curPoint.x = Utils.clamp(curPoint.x, dimensions.minX + (workWidth/2), dimensions.maxX - (workWidth/2));

          --is point in field?
          local _, pointInPoly = courseplay.fields:getPolygonData(poly.points, curPoint.x, curPoint.z, true, true, true);
          if pointInPoly then
            --courseplay:debug(string.format("Point %d (lane %d, point %d) - x=%.1f, z=%.1f - in Poly - adding to pathPoints", curPoint.num, curLane, a, curPoint.x, curPoint.z), 7);
            table.insert(pathPoints, curPoint);
          else
            --courseplay:debug(string.format("Point %d (lane %d, point %d) - x=%.1f, z=%.1f - not in Poly - not adding to pathPoints", curPoint.num, curLane, a, curPoint.x, curPoint.z), 7);
          end;
        end; --END für if maxPointsAtTurn
        --  End Edit  --
        ---#############
			end; --END for curPoint in pointsPerLane
		end; --END for curLane in numLanes
	--END North or South

	elseif dir == "E" or dir == "W" then --East or West
		numLanes = math.ceil(dimensions.height / workWidth);
		pointsPerLane = math.ceil(dimensions.width / pointDistance);
		if numLanes * workWidth < dimensions.height then
			numLanes = numLanes + 1;
		end;
		courseplay:debug(string.format("generateCourse(%i): numLanes = %s, pointsPerLane = %s", debug.getinfo(1).currentline, tostring(numLanes), tostring(pointsPerLane)), 7); --WORKS

		for curLane=1, numLanes do
			--Lane directions
			if dir == "E" then
				--WEST->EAST, starting at WEST
				if courseplay:isOdd(curLane) then
					curLaneDir = "E";
				elseif courseplay:isEven(curLane) then
					curLaneDir = "W";
				end;
			elseif dir == "W" then
				--EAST->WEST, starting at EAST
				if courseplay:isOdd(curLane) then
					curLaneDir = "W";
				elseif courseplay:isEven(curLane) then
					curLaneDir = "E";
				end;
			end;
			courseplay:debug(string.format("curLane = %d, curLaneDir = %s", curLane, curLaneDir), 7); --WORKS

			for a=1, pointsPerLane do
        ---##############
        -- Begin Edit ---
        if a % stepForPoints == 0 or a < (maxPointsAtTurn + 1) or a > (pointsPerLane - maxPointsAtTurn + 1) then
          local curPoint = {
            num = a + ((curLane-1) * pointsPerLane);
            lane = curLane;
            laneDir = curLaneDir;
            x = dimensions.minX;
            z = dimensions.minZ + (workWidth * curLane) - (workWidth/2);
          };

          if crn == "SW" or crn == "NE" then
            if courseplay:isOdd(curLane) then
              curPoint.ridgeMarker = ridgeMarker["left"];
            elseif courseplay:isEven(curLane) then
              curPoint.ridgeMarker = ridgeMarker["right"];
            end;
          elseif crn == "SE" or crn == "NW" then
            if courseplay:isOdd(curLane) then
              curPoint.ridgeMarker = ridgeMarker["right"];
            elseif courseplay:isEven(curLane) then
              curPoint.ridgeMarker = ridgeMarker["left"];
            end;
          end;

          if crn == "SW" or crn == "SE" then
            curPoint.z = dimensions.maxZ - (workWidth * curLane) + (workWidth/2);
          end;

          if curLaneDir == "E" then
            curPoint.x = dimensions.minX + (pointDistance * (a-1));

            if curPoint.x >= dimensions.maxX then
              curPoint.x = dimensions.maxX - pipSafety;
            end;
          elseif curLaneDir == "W" then
            curPoint.x = dimensions.maxX - (pointDistance * (a-1));

            if curPoint.x <= dimensions.minX then
              curPoint.x = dimensions.minX + pipSafety;
            end;
          end;

          --last lane
          curPoint.z = Utils.clamp(curPoint.z, dimensions.minZ + (workWidth/2), dimensions.maxZ - (workWidth/2));

          --is point in field?
          local _, pointInPoly = courseplay.fields:getPolygonData(poly.points, curPoint.x, curPoint.z, true, true, true);
              if pointInPoly then
            --courseplay:debug(string.format("Point %d (lane %d, point %d) - x=%.1f, z=%.1f - in Poly - adding to pathPoints", curPoint.num, curLane, a, curPoint.x, curPoint.z), 7);
            table.insert(pathPoints, curPoint);
          else
            --courseplay:debug(string.format("Point %d (lane %d, point %d) - x=%.1f, z=%.1f - not in Poly - not adding to pathPoints", curPoint.num, curLane, a, curPoint.x, curPoint.z), 7);
          end;
        end; --END für if maxPointsAtTurn
        --  End Edit  --
        ---#############
			end; --END for curPoint in pointsPerLane
		end; --END for curLane in numLanes
	end; --END East or West
```

The variables maxPointsAtTurn and stepForPoints could also be set, stored and fetched to/from courseplay.xml for easier configurability by users personal preferences.
Or maybe even as an option in the HUD?

What do you think of it?

**Comment by gui7545** [comment]
It will not be a problem with tool that need refilling (seeders, manure spreaders, ..) or unloading (straw trailer) ? Because after the refilling (or unloading ) courses, the vehicle will restart at its last point.
With your system, it will restart more behind its real stop point.

**Comment by AndyK70** [comment]
@gui7545 I don't think it will be a real problem. With my settings instead of 5m ahead it will start max. 50m ahead with fertilizing, or loading straw/grass. This thinking made me suggest the configurability for the user. Every user has his own preferences. If you don't want to have steps up to 50m, set it shorter, even down to 1 so every 5m as per now will be a waypoint.

@PromGames yes, you and a lot of advanced courseplay users will do that. There are a lot of feedbacks where users have saved every course they drove and or generated. I heared of someone with over 850 courses saved in the courseplay.xml.
For normal fields, where are no special traetments I generate fieldcourses as needed as well, but courses for some fields needs some traetment. When there are obstacles near by (house, garden, fencing) which can't be chopped like a tree. Those special courses I save as well.

**Comment by AndyK70** [comment]
I found an issue with this method when I have a field without rectangular shape.
Was just testing it on field 20 (still Björnholm) and in the NW corner the shape of the field is so much cut off, that there are not as much waypoints as needed to have a good turn.

Another issue (#791)  comes into count: the last waypoint of the lane isn't generated as supposed.

**Comment by JakobTischler** [comment]
Ok, so generally I like the suggestion, reducing overhead etc. At the same time, we're working on some major changes in the course generation, both with headland and the lane generation itself, so at the moment I won't implement any new stuff.

**Comment by AndyK70** [comment]
I'm fine with your decision.
Just want to point out, that if there would be only 50m steps, it comes to issues at the turn, as mentioned in the first post, when the combine isn't aligned at the lane while reentering the field.
That's the reason why I kept the 5m steps around the turnpoints.

**Comment by rkaerner** [comment]
It is just my personally cent, but: if I generate a course, it is just temporary. Who will be able to prevent a calculation after generating and before writing it to a xml file a course consider things like turning points, end of work points an such things like long straight paths on a road but the developers and their code? No one. So what about a - in my grenly thoughts easy - algorithm which works after any course generating to shorten the result that would be fixed in a xml file? If there is a long way in one direction, it should be possible to reduce it to the start point of the long line and the end point. If there is any deviation of more than x degrees, every way point will find its way into the course and also into the xml. End points of work and end points of a field and start points of a bend or a turn or a "wait a moment, I have to pee at the next tree" should be able to be recognized until generation and afterwards be calculated, before finding its way into any solid state within a file on the disk. Just to remember: my personally cent. It's not enough for my personally two cents ;-) And, please, pardon my bad english. I am old and I am german. But I have no problem if my computer will explode when using any beta code testing that new algorithm. Twice. Trust me, I am serious. :-D

**Comment by AndyK70** [comment]
@rkaerner 
>  If there is a long way in one direction, it should be possible to reduce it to the start point of the long line and the end point. 

And that's the only thing we are talking about. Reducing unnecessary points on a straight line. They will be just left out of generating process, no big optimizing algorithm  afterwards. :wink: 
And as you mentioned you are german and having some problems understanding englisch here it is same text in german for you:
Wir reden auch nur davon unnötige Wegpunkte auf einer geraden Linie zu reduzieren. Diese werden beim generieren einfach ausgelassen, da ist kein aufwendiger Algorithmus der alles im Nachhinein optimiert. :wink:

**Comment by JakobTischler** [comment]
Having discussed it, we've decided against it, as it would create more problems than benefits. Easiest solution: don't save generated courses in the xml.
