### ISSUE TITLE
Small correction to be done in website FAQ

### ISSUE THREAD

**Issue by Maxcdr** [Courseplay/courseplay#909]
FAQ on website (http://courseplay.github.io/courseplay/en/faq/index.html) about "How to provide a nice and sexy bug report" states Log.txt is to be found in C:\Users\[USER NAME]\My Documents\MyGames\FarmingSimulator2015\mods\log.txt in Windows case whereas it is in C:\Users\[USER NAME]\My Documents\MyGames\FarmingSimulator2015\log.txt (not in mods folder).

![sans titre](https://cloud.githubusercontent.com/assets/10348839/5636470/a85cc0c6-95f2-11e4-9452-ca2a36c4ab11.png)

**Comment by JakobTischler** [comment]
Thanks for the heads up. Fixed.
