### ISSUE TITLE
not restoring speed value for cruise control after stopping driver

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#915]
Could you please save the actual speed value of cruise control when "drive course" is clicked/used and after "stop driver" restore the saved value?

Everytime I drive a vehicle by myself after it was driven by CP, I have so set my cruise control speed again.

**Comment by JakobTischler** [comment]
Implemented in build 0019. Please report if it's not working as expected.

**Comment by AndyK70** [comment]
got v0020, works like a charm, tyvm. :+1:
