### ISSUE TITLE
Combine Names no longer showing in Manage Combines

### ISSUE THREAD

**Issue by Nebular64** [Courseplay/courseplay#927]
I'm currently running v.0029 and do not have any errors.  However, I have noted that when selecting Manage combines and setting the "Find combine" to manual, the name of the combines are no longer showing in the "Choose combine" field.  Only the distance to the combines is being shown as noted in the picture.

![combine](https://cloud.githubusercontent.com/assets/3781477/5693545/52146f02-98ef-11e4-9959-72241effc11e.jpg)

**Comment by gui7545** [comment]
Duplicate of #926

**Comment by Nebular64** [comment]
I just noticed someone else reported the issue while I was working on getting this submitted, so I'm closing it out.
