### ISSUE TITLE
Error: Running LUA method 'cpOnTrafficCollisionTrigger'.

### ISSUE THREAD

**Issue by Big81Bull** [Courseplay/courseplay#931]
Hallo,
hoffe mal das mir hier auch auf deutsch geholfen wird!?

Dieser Fehler oder was immer es ist, kenne mich da null aus, wird mir seit der Version 4.01 ständig ausgeworfen.
Er kommt ganz sporadisch ohne ersichtlichen Grund, auch wenn ich Courseplay gerade nicht nutze und auch wenn ich nichtmal in einem Fahrzeug sitze, also nur dumm rum stehe.
Er kommt auf Mod und standart Maps.
Im Log steht dann immer das:

Error: Running LUA method 'cpOnTrafficCollisionTrigger'.
E:/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/triggers.lua:110: attempt to index local 'veh1' (a nil value)

Hier der gesamte Log
https://gist.github.com/Big81Bull/b24ba1e6cffc45545a15

Gruß BigB

**Comment by AndyK70** [comment]
Ich denke, das hat mit einem nicht ganz konformen Modfahrzeug zu tun.
Entferne mal alle Modfahrzeuge und schau ob der Fehler immer noch kommt.
Dann packe immer eins nach dem anderen wieder rein und starte LS15 neu nachdem du jeweils ins Log geschaut hast.

**Comment by Big81Bull** [comment]
Thx for that very quick answer. I think i know witch mod it is!
Sry for that german post, but my english is so damn bad its a shame!

greetings BigB

**Comment by ThomasGaertner** [comment]
can you tell us the mod ?

**Comment by BlackWolve** [comment]
I have the same problem. the lua error comes 1st by closing any tool or machine. Yesterday i had the error by closing a harvester (original Giants) today the same error by closing a mod machine. After this error comes the 1st time, the error will come after every closing a machine or tool by pressing X.

I hope u understand me, and you can fix it.

**Comment by ThomasGaertner** [comment]
@BlackWolve : would you please test with debug channel 3 active and post the complete log if it happened again ?
i'm trying to catch this fault for a long time....Thanks

**Comment by AndyK70** [comment]
whoops, got the same error today.
Had installed the mods [LS 15: MilkTruckTrigger v 2.0](http://www.modhoster.de/mods/milktrucktrigger) and [LS 15: WaterMilkTrailer v 4.0.2](http://www.modhoster.de/mods/watermilktrailer).

CP Version 0032

Log: [logfile (2015-01-12 16:30)](https://gist.github.com/AndyK70/8698e4310c2e1da7256b)

**Comment by ThomasGaertner** [comment]
@AndyK70 : would you please test again with debug 3 active and post the log ?
@Big81Bull : as I understand it right , you are using v 4.01.0000 so I cant do anything for you, but when I can catch this **** fault it will be fixed in dev version and then also in the next official version...

**Comment by ThomasGaertner** [comment]
please try again with v0033 or higher and report....

**Comment by BlackWolve** [comment]
Thomas i tried it with debug 3 in dev 032 and the error don*t come again. I switched the debug off, and my game crashes 15 min later, without a log entry. Now i will going to try the new version this evening.

**Comment by AndyK70** [comment]
Did a first test with dev 0032 and debug 3 enabled.
There was something to expect, wasn't it?
Did some work, mowing, driving around, unfold and fold the Jenz HEM 583, drove the WaterMilk-Trailer, filled it with milk, drove to the sell-trigger, sold it and again... 4 times.
Not one error... :angry: 

[FS15 logfile (2015-01-12 22:03)](https://gist.github.com/AndyK70/2c1cf4b056b497f4957a#file-fs15-logfile-2015-01-12-22-03)

Will get the new dev version and will test again...

**Comment by BlackWolve** [comment]
i've testet the new version for more than 90 min. without an error. it look like that the error is history at this moment. I will test it tommorow again, but a little bit harder.

**Comment by AndyK70** [comment]
The second test, now with dev 0033 and debug 3 enabled.

Was driving one round loading and selling milk and then a great demand for woodchips startet. So I was working with the Jenz.... crash after a while, but not courseplay.

[FS15 logfile (2015-01-12 22:51)](https://gist.github.com/AndyK70/520d247ced0f94aaaf98#file-fs15-logfile-2015-01-12-22-51)

**Comment by Big81Bull** [comment]
@ThomasGaertner : it was the DeutzFahr7250_Special_Black_Edition mod, but i change the rpm in the deutzFahr7250.xml for my own from 2800 to 3200. Now i write it back to 2800 and the log is permanently clean. I think it was my own foult! Sry for the late reply.

**Comment by ThomasGaertner** [comment]
as far as i can see, the secondary issue seems to be solved, as I said, for @Big81Bull i cant do anything since you are using the default version. for the others : i will close here since i cant see any error concerning CP in the log files. if there is still a issue , please create a new one 
Thanks
