### ISSUE TITLE
shortcuts for buttons

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#932]
I'm using the keyboard a lot and would like to have some more shortcuts.

i.e:
- for switching drive modes i suggest the modifier key + page up/down to switch to last/next mode

- for start/stop recording and start/stop driver i would suggest one shortcut only, choice to the user no default bindung
- same goes for waitpoint, crossing, etc.
- the shortcut for "stop at last point or next trigger" seems to be bound to "continue" and not to "stop at last point or next trigger". Would like to have a shortcut for that option, too. Like "Numpad /", or "Numpad 4"

**Comment by JakobTischler** [comment]
The keyboard events for start/stop recording I will do, maybe the next/previous mode as well, the rest I won't.
