### ISSUE TITLE
option/button for "reload courseplay.xml"

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#933]
Now that there is a course editor to come (#903), I would like to have the possibility to reload the courses from file.
That way I wouldn't have to close and start the map again (time baby, I have no time! :grinning: ) and could see the difference just by a click of the mouse.

Maybe it could be placed in the general settings page?

**Comment by JakobTischler** [comment]
Not before the course management rework. Added to suggestion list.
