### ISSUE TITLE
Field course generation (start/stop) change Feature ?

### ISSUE THREAD

**Issue by D3ltorohd** [Courseplay/courseplay#934]
Hello guys i have a quest and i will try it that you understand what i would say you. What i will have is the following example. I play the mig map for example. Each fielf has his own entrance way. So then i will set the course work so, that he enter and leave the field over this way. But when i click manual on generate field course the start and end point (green and red point on the line) is not on the entrance of the field but somewhere else around the field frame. So is there i way you can change something that the green and red points for start and end of the field course is set there where my vehicle front is looking when i press generate field course ? I hope you can follow me :-)

Greet's D3ltoro

**Comment by AndyK70** [comment]
You could record a course from the entry point to the startpoint of the generated course

**Comment by JakobTischler** [comment]
1. What AndyK70 said.
2. Not possible. The start point is based on the shape of the field and your starting corner / starting direction selection.
