### ISSUE TITLE
wait before turn when combine is producing swath of straw

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#935]
When I want to collect the swathe of straw with a loader wagon following the same course as the combine there are a lot leftovers at the turns, because the combine isn't waiting to unload all straw before doing the turn, like the normal helper does.

Would be cool to have this functionality build in, not losing so much straw. (Or having to collect it manually.)

**Comment by ThomasGaertner** [comment]
try v0041 and report ...

**Comment by AndyK70** [comment]
tested with 0042, works very fine. Thank you
