### ISSUE TITLE
Out of Memory with extreme big Files

### ISSUE THREAD

**Issue by PromGames** [Courseplay/courseplay#936]
I have tried in MIGMap Celle 0,94 with big files 8-10 Mb (Newformat) (Few generated courses)  and there is no problem. Takes some time to load in a 4GB Ram computer, but it is OK and works fine. 

But when I try to load in the same map a __very__ big file of routes of courseplay (65 MB - 600K Lines) (Lot of  generated courses) with the actual save space format and after almost 20 minutes loading is giving me an error "not enough memory":

```
### Courseplay: initialized 38/38 files (v4.01.0032)
    ******************************************* WARNING *******************************************
    * You are using a development version of Courseplay, which may and will contain errors, bugs, *
    * mistakes and unfinished code. Chances are your computer will explode when using it. Twice.  *
    * If you have no idea what "beta", "alpha", or "developer" means and entails, remove this     *
    * version of Courseplay immediately. The Courseplay team will not take any responsibility for *
    * crop destroyed, savegames deleted or baby pandas killed.                                    *
    ***********************************************************************************************
### Courseplay: installed into 32 vehicles
.....
C:/Users/Alfredo/Documents/MyGames/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/normal.i3d (0.75 ms)
C:/Users/Alfredo/Documents/MyGames/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/cross.i3d (0.83 ms)
C:/Users/Alfredo/Documents/MyGames/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/wait.i3d (1.10 ms)
C:/Users/Alfredo/Documents/My Games/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/start.i3d (4.71 ms)
C:/Users/Alfredo/Documents/MyGames/FarmingSimulator2015/mods//ZZZ_courseplay/img/signs/stop.i3d (1.02 ms)
## Courseplay: setting up fields (basic)
## Courseplay: loading settings from "courseplay.xml"
## Courseplay: setting up hud
## Courseplay: setting up debug channels
## Courseplay: setting up globalInfoText
## Courseplay: setting up signs
## Courseplay: loading courses and folders from "courseplay.xml"
Error: Running LUA method 'loadMapFinished'.
not enough memory
```

And then the game crashed. 

It is possible to debug it? The I can provide more information.

My feeling is that the new system from Giants to manage memory produce this limitation.

**Comment by JakobTischler** [comment]
FS15 has a notoriously bad memory management. Way worse than FS13. Since all those courses need to be in the memory, there's nothing we can do at the moment. The amount of waypoints is simply too big.

We have thought about and discussed a possible method for faster loading - only loading the courses as references at the beginning of the savegame, and then only load the course's waypoints when they're actually needed - but this is still miles away, as we have some other big areas to deal with and finish first.

Until it comes to the point where we tackle this, I'll close this issue.
