### ISSUE TITLE
Course Generation Possibility?

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#937]
So I'm experimenting with MrLight - in lieu of Dural returning with a new official MR for 2015...  I like to play with hilly Alps maps, and am wondering how hard it would be to be able to generate a course that would only generate lanes that go in a certain direction (downhill) and then lift up the tool and go back to the other end and work again downhill?

I can see this being a practical solution if you don't have the hp to make it uphill while mowing, seeding or cultivating

**Comment by JakobTischler** [comment]
While technically maybe possible, it won't happen anytime soon. There's a bigger course generation update coming, so no new stuff will be added before that. Also, your suggestion would a require a much smarter turn maneuver.

Added to the suggestion list.
