### ISSUE TITLE
support for triggers with liquids other then liquid manure?

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#938]
Would it be possible to integrate support for milk, water, mobile fuel tank, for transportation and/or selling?

At the moment I'm fiddeling around with [LS 15: MilkTruckTrigger v 2.0](http://www.modhoster.de/mods/milktrucktrigger) and [LS 15: WaterMilkTrailer v 4.0.2](http://www.modhoster.de/mods/watermilktrailer). 
Other users in the official LS15 forum (german) are trying to transport water from a fill station to their planting houses and another one wants the mobile fuel tank to act as overloader. Getting the fuel at a gas station then drive to a specific point, wait there to be emptied by other vehicles which need fuel and then drive on the turn to get more fuel...

 For the milk I would say it is more or less like mode 1 (grain transport), get the stuff, drive to sellpoint and sell it. Well, milk is not to be tipped, but pumped by 'R', but I don't think that would be a showstopper.
Same goes for the water. Starting the course at the water filller, transport it to the planting house, pump it with R and go on your turn.

For the mobile fuel tank see above (overloder).

**Comment by JakobTischler** [comment]
Please check the previous issues and the bug tracker before opening new issues. This has already been dealt with in https://github.com/Courseplay/courseplay/issues/734.

**Comment by AndyK70** [comment]
is the treatment for the milk trigger the same as for water and diesel?
I'm unsure, because the milk trigger is from a mod and not build in, like the two mentioned in #734.

**Comment by JakobTischler** [comment]
It falls into the same category as it involves loading, transporting and unloading a liquid product.

If we are to support one of them, we might as well write a method that correctly handles all (or at least most) of the types mentioned. We will look into it, but no promises.

**Comment by AndyK70** [comment]
ok, thanks and I promise to look better for dupes before reporting sth.

**Comment by JakobTischler** [comment]
Added support for fuel and water transport in mode 8 in build 0152.
