### ISSUE TITLE
mouse dragging camera, while not supposed to after switching to another vehicle

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#939]
Dev version 0033 (seen this already at 0028 if I remember correctly)

When having the courseplay HUD open, the mouse cursor is visible and moving the mouse doesn't drag the camera.
Now switching to another vehicle the mouse cursor is still visible, but drags the camera. Regardless if the cp hud of  that vehicle is visible or not. But you can rotate them camera only until the mouse cursor hits the side of the screen.

Clicking the right mouse button to close the hud does not. But it restates the mouse in it's normal behavior. 
If the hud is open, the mouse won't drag the cam anymore, if the hud is closed, the hud will open and the mouse won't drag anymore.

nothing to see in the log, should I enable a debug channel?
[FS15 logfile (2015-01-12 22:57)](https://gist.github.com/AndyK70/9a2a3f6b09ad9be59b53#file-fs15-logfile-2015-01-12-22-57)

**Comment by JakobTischler** [comment]
Nah, we're already aware of this (read: already in the bug tracker). It's a side effect of an MP bug we're trying to fix.

**Comment by AndyK70** [comment]
testet and confirmed.
