### ISSUE TITLE
Multiplayer?

### ISSUE THREAD

**Issue by elsingaa93** [Courseplay/courseplay#940]
Hi,
I just installed this great mod but I can't find the mod when I'm trying to make a multiplayer game. Is it really singleplayer only, or am I doing something wrong? 

Thanks in advance.

**Comment by PTAzores** [comment]
Hi,

The multiplayer is currently disabled for bug tracking and solving. They are working hard to fix all for us.... let's wait. until there single player is what we have.

Regards,

PTAzores

**Comment by elsingaa93** [comment]
Ah okay :( Thanks.
