### ISSUE TITLE
Tracktor with trailer stands in field

### ISSUE THREAD

**Issue by elsingaa93** [Courseplay/courseplay#942]
Hi,

Everytime the trailer gets filled from the combine it just takes a place at the field instead of going back to the starting/stop point. How come?

**Comment by gui7545** [comment]
It is the normal way it sould work.
The trailer goes to the start point just when she is load over the "drive on" level.
In manual, it is writen: " >The tractor waits at the last waypoint until it has a combine, chopper or harvester in reach, and said combine's fill level is above the percentage (Start at %) set for the tractor. Then, the driver drives to the combine, comes from behind, and drives underneath the pipe, where the combine starts to unload into the tractor's trailer. If the trailer isn't full yet (Drive on at %), the tractor turns around and waits in the field for his next unloading operation. As soon as the trailer's fill level is above the Drive on at % percentage, the driver will drive to the course's second waypoint, and from there continue the course, unloading the trailer and returning to the field.

**Comment by elsingaa93** [comment]
Ah okay. Then my sowing machine has to wait. Thanks.
