### ISSUE TITLE
overloader will not dump at overload point

### ISSUE THREAD

**Issue by hackselgut** [Courseplay/courseplay#944]
My overloader will not dump at the overload point, if the Truck to be filled is there First, Waiting. If this happens the overloader carries on to the End point, Thus staying filled. If I set my operation to make sure that the Truck arrives after the overloader is in position ( shows blue bar ) everything is ok. But to do this I have to set a very long route to the Silos and back, ( waste of time ) If I set to have the truck there first I will get a good dump 2 out of 5 attempts, so I have to stay with the long long travel route. I am running version 4.01.0035, pictures included
![fsscreen_2015_01_14_08_21_51](https://cloud.githubusercontent.com/assets/10256656/5743429/50a104be-9be7-11e4-9051-a9b7dd6ebc95.png)
![fsscreen_2015_01_14_08_22_25](https://cloud.githubusercontent.com/assets/10256656/5743428/509dc920-9be7-11e4-970f-a9a1d3e008d7.png)
![fsscreen_2015_01_14_08_22_32](https://cloud.githubusercontent.com/assets/10256656/5743430/50a3ca3c-9be7-11e4-940b-5d3e75eec416.png)

**Comment by gui7545** [comment]
The course for the truck start at the loading point ? or it is just a waiting point ?

**Comment by hackselgut** [comment]
The truck has a mode "load at start" . The problem looks to be with the overloader not locking to its "overload point" ( I do not get the Blue Text line ( that tells me the overloader is in position))  If the truck is there first ( thus waiting ) and the overloader now comes a long side,, starts to dump, Blue text line comes on for a second then goes out, overloader carries on to end point. Still full....

**Comment by hackselgut** [comment]
time here is 6am thursday ...1/15/2015

**Comment by gui7545** [comment]
Strange, because i test with the same overloader and every thing is OK.
Can we have your log ?

**Comment by hackselgut** [comment]
Here is the log, Had 3 times the overloader did a start dump then carry on to end point.I need help sending the Log Text file How?

**Comment by gui7545** [comment]
Post it on https://gist.github.com/

**Comment by hackselgut** [comment]
I am trying to post my log file, but I have never don this before. i have opened the site and filled in some spots with info, opened my game clicked copy for the log file then gone baack to the web site and tried to paste file or click the add file box  but I see nothing happening. ( bob )

**Comment by hackselgut** [comment]
I ran my game for 3 hours this morning with the channel 15 active fo debugging. Not once in atleast 30 to 40 operations filling my truck to go to the silos did the operation fail everthing worked as it should. I am going to try again after I replant my field ( no debugg active. A sub question, The overloader Pipe, is it controlled by Course play as to when the pipe is extended, because there are times that because of Timming I will end up having 2 trucks in line to be filled, with the pipe of the overloader extended as it does I will partly fill the Fiest truck in line then go on to the next one to complete the empying of the overloader. Thus I have 2 trucks partially filled ( fill will complete next round of overloader) Can the pipe extending be made at a later time ( closer to the Waiting point )

**Comment by hackselgut** [comment]
Well I replanted my field again, and then set up my operation, the filling of the trucks was a hit and miss operation, not reliable. I then open the debug on the overloader  for channel 15, restarted operation and every dump from then on was a good one, no faults. ( bob )

**Comment by ThomasGaertner** [comment]
I did understand your last post that you have had still problems with the overloading but after activating debug15 , everything is fine. can you confirm ? And did you say, that the overloader did not overload if the truck is already in waiting position , but if the truck arrives later it worked properly ?

**Comment by hackselgut** [comment]
If I run The Debug channel 15 on the overloader in active mod everything works as it should do...With out the debug active my truck to go to silos has to arrive after the overloader is in position.for its unloading..If I do not set up this way the overloader will come up to the truck, make a small dump of crop then keep on going to its end point. Not Emptied.

**Comment by ThomasGaertner** [comment]
would you please make the test again with standard vehicles and report , just to prevent a failure in the mods you used...

**Comment by hackselgut** [comment]
Ok ....I will have to find equipment to do job and then set it up. Mat take a few days. ( bob )

**Comment by hackselgut** [comment]
Well I set up a game using default equipment as follows,Map Poebene15 Tractor T8.320  Trailer Krampi big boidy 900s Qty 46900  Overloader Titan 34 UW Qty 34000  Combine Axial-flow 7130 Qty 10570 Using field 18.  As you will notice above the quantities do not match, Because of Multi player we are not to make changes to default equipment.or Multi player may not function.Now I did notice something in that the overloader would not stop if it was not Full It would carry on to end point.Now I run with an unload value HIGH now is it possible that because the overloader hits a fill amount of 80% to 90% the overloader point will not Register to stop at the unload point, because I am wondering if it now registers Not Full.. Remember if not full it will not stop to unload.. I am going to try and set my unload value at a low amount for my next trial.Also I think if the unload pipe were to come out after the Pause point was set ( blue bar indicator ) tis would help a lot when we may have multiple Trucks or trailers in line to be filled.Version of Course play using is 4.01.0047.  (bob )

**Comment by hackselgut** [comment]
So I went back to my original farm and set up, but this time I set the unload Value of the overloader to 100 units. We know the overloader will not stop at the unload point if it is not Full. Now I am thinking that becaus4e the overloader pipe is extended prior to the set point being reached that we get a value in overloader being less than Full, therefore it will not stop.to unload. I will bet you that if we can get the overloader pipe to activate after the set point is reached, rather than as it is now. ( now activates as the overloader makes it`s turn towards the truck that is Waiting.)  (bob )

**Comment by hackselgut** [comment]
Well like I said above I set to a low amount,  100 units per second unloading. In most of the tries  to unload, it worked, but it takes to long to  unload set at that rate.So I went back to my sure thing. ( run with debug 15 active....No bad dumps.) I would like to ask if you can get Software group to change the point as to when the overloader pipe is extended, Have it extend when the overload point is mage ( blue bar indicator showing ) and not prior to reaching  the set point. ( bob )

**Comment by Karlshoj** [comment]
![fsscreen_2015_01_26_21_54_20](https://cloud.githubusercontent.com/assets/7414065/5910886/4580a85a-a5a6-11e4-97b0-4026feb28da3.png)
When recording the auger´s route I always make it a curve to avoid the pipe hitting the waiting trucks

**Comment by hackselgut** [comment]
Thanks I will give that  a try but I still think the pipe adjustment would help allot. ( bob )

**Comment by hackselgut** [comment]
Thanks My only resolve is to run with debug 15 active.
