### ISSUE TITLE
go on to work on more than only one field

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#945]
Is there a possibility for following scenario?

1. Sower is at parking position.
2. Sower gets course to go to field A.
3. Sower gets course to sow field A
4. Sower gets course appended to drive to field B (not merged)
5. Sower gets course appended to sow field B
6. Sower gets course appended to drive back to parking position via sow-trigger to fill up.

I'm trying to get it to work, but mostly when field B is about to be sowed the vehicle doesn't do what it should. It starts driving without sowing.

On standard Bjornhom there are often fields which could be worked on in a row without need to refill sower or fertilizer. Don't know if there are other maps too, just sticked to Bjornholm so far.

**Comment by JakobTischler** [comment]
Nope, won't work. See #750.
