### ISSUE TITLE
courseplay dosnt show up ingame

### ISSUE THREAD

**Issue by lazero1** [Courseplay/courseplay#946]
I do everything the way your instruction say but it does not show up in game can you please help? 
I tried release version and the developers version both does not show up

**Comment by ThomasGaertner** [comment]
please post your log to gist and deliver the link here 
Thanks

**Comment by lazero1** [comment]
how do I post my log to gist?

**Comment by lazero1** [comment]
https://github.com/Courseplay/courseplay this is what I used

**Comment by lazero1** [comment]
then I archived the courseplay-master folder to ZZZ_courseplay.zip

**Comment by lazero1** [comment]
and pasted it to C:\Users\USER\Documents\My Games\FarmingSimulator2015\mods

**Comment by lazero1** [comment]
btw just wondering how do I get log for courseplay or what is it? sorry not a software genius

**Comment by lazero1** [comment]
https://gist.github.com/lazero1/81663482b6251a59fcd2 this is my log file

**Comment by AndyK70** [comment]
you have to zip all files inside the folder coureplay-master, not the folder itself.

**Comment by lazero1** [comment]
yep the files I archived not the folder but still nothing

**Comment by ThomasGaertner** [comment]
Update to patch 1.2 and it works fine ...

**Comment by lazero1** [comment]
yep did that and works fine thanks :)
