### ISSUE TITLE
Reset vehicle or tool bug

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#947]
Just noticing a small bug -

If you reset a tool or vehicle that is in the way of your course (a header or weight that was left in a field or along your path), after you reset it to your farm, it will not actually disappear until you stop the course of the vehicle that is blocked..   when you hit stop, the tool resets, and you can restart your course.

**Comment by ThomasGaertner** [comment]
should be fixed in v0044.For the next time, please check your log and post it in your issue. I'm pretty sure, it was full of errors concerning his case. please test and report..

**Comment by sootysax** [comment]
yes, this is fixed now.
