### ISSUE TITLE
Mode 2 (Combi) driver "is in traffic" with his combine

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#948]
CP 0036

On Bjornholm (standard) field 38, got a Traffic warning for the driver (Deutz Fahr 7250 TTV, with Kroeger Agroliner HKD 302 and Suer Sb 1000) while approaching to his (manual set to) combine Sampo C6 for unloading.
Won't reach the combine due to these traffic warnings. 
Only if I stop driver and start again for two or three times he will crouch to the C6 to unload it.

After unloading the 7250 take a turn and waits for his next call to unload.
Then the story starts over again with those traffic warnings.

[FS15 logfile (2015-01-15 23:25)](https://gist.github.com/AndyK70/3d30db753085ed209aad#file-fs15-logfile-2015-01-15-23-25)

**Comment by ThomasGaertner** [comment]
yea that's because the tractor is higher than the pipe, what should we do ?

**Comment by Karlshoj** [comment]
Maybe deflate the tires ;-)

**Comment by AndyK70** [comment]
@Karlshoj  hmpf :grimacing: :grinning: 

@ThomasGaertner ok, if this is the cause could courseplay output this warning "tractor/trailer is too high for pipe" instead of that generic "is in traffic"?
A bit strange, because I can drive manually the 7250 under the pipe without touching it and courseplay can do the same with a bit of pricking.

**Comment by ThomasGaertner** [comment]
@AndyK70 : if you hit F5 in this situation , you will see how close it is with this tractor , but the fact is that the pipe is in the collision trigger and so it will be recognised ...

**Comment by AndyK70** [comment]
It's ok.
I don't mind if there is a tractor too big for the little C6, but would it be possible to detect, that it is the pipe of the combine which is colliding and print out the appropriate message?

**Comment by ThomasGaertner** [comment]
nope, that's not possible at the moment.
