### ISSUE TITLE
mode 9: after "work has finished" shovel stays at "loading position"

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#949]
Could you please add, that if work has finished the shovel is set to "transport position"?

**Comment by JakobTischler** [comment]
Why? Users can set it to the transport position manually. And if that is too difficult, they can use the "move to transport position" button.

**Comment by AndyK70** [comment]
because it's very unlikely to let the shovel stay at loading position after it has finished.
You'll normale drive to next silo or wherever you want to have it, therefor you have to lift up the shovel.
It's just a tiny thing, but it has to be done every time.
For convenience it could be automated. That's why I asked politly with a please. 

It's not a bug, nor could a bug arise from it, but it would be nice to have.

**Comment by JakobTischler** [comment]
You're gonna have to go to vehicle, open the CP hud and dismiss it anyway. One more click on a button is a lot easier than implementing another limited movement session.

**Comment by AndyK70** [comment]
Well, as I said, I prefer schortcuts and I won't open the HUD, because I press ctrl+[numpad 7].

Nevertheless of course I'll accept your decision and will do it by hand.
