### ISSUE TITLE
sower starts too late into lane...

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#950]
With a Lambo VRT 230 and a Väderstad Rapid A 600S on Field 38 of Bjornholm.

After I threshed that canola field I was sowing canola again.
After cp had finished I wanted to test something else. I switched the sower to wheat and let cp drive the same course again. It was still in memory of that Lambo. Did not delete that course from the vehicle.

As you can see on the picture, the first sowing with canola always left out a little bit when entering the field after a turn.
In the second run with wheat, the sowing is complete, without letting something out.
![Sower not to late with wheat](http://www11.pic-upload.de/16.01.15/78xnzpo7m4gc.jpg)

Will test again with barley tomorrow

PS: sorry, was late, forget the log (it's the same as in #948):
[FS15 logfile (2015-01-15 23:25)](https://gist.github.com/AndyK70/3d30db753085ed209aad#file-fs15-logfile-2015-01-15-23-25)

**Comment by AndyK70** [comment]
Almost forget to post the screen with barley.
With barley it is the same as with canola.
Hope it doesn't make a difference, that now I used 0071?

![sower too late with barley](http://www11.pic-upload.de/07.02.15/5b493uktvry4.jpg)

**Comment by ThomasGaertner** [comment]
at the moment we are working on a new turn procedure . after finishing that , this cases should be solved... I will close here and ask you to wait till its online....

**Comment by AndyK70** [comment]
ok, thanks
