### ISSUE TITLE
Translation not done 

### ISSUE THREAD

**Issue by PTAzores** [Courseplay/courseplay#954]
Hi Today i Saw this, it's as in code is normal?

![2015-01-16_00001](https://cloud.githubusercontent.com/assets/3687991/5774808/9661529e-9d61-11e4-870f-880cced31379.jpg)

**Comment by JakobTischler** [comment]
No, it isn't. I figured the game's translation system would fall back to the English terms if no translation for the current language is provided, but that doesn't seem to be the case.

**Comment by JakobTischler** [comment]
With the latest build, it should appear in English - until the text is translated to Portuguese.

**Comment by PTAzores** [comment]
Thanks :)
