### ISSUE TITLE
Failure to recognise farm silo load trigger in transport mode.

### ISSUE THREAD

**Issue by Sokonomi** [Courseplay/courseplay#966]
I have this neat little Unimog 400WB with a kipper on the back;
http://www.modhub.us/farming-simulator-2015-mods/unimog-u400-wb-v1-0-testfahrt/

It works quite nice with combines and auger wagons, so courseplay is able to load it up most of the time. Just the farm silo trigger doesn't seem to work. I am able to do it manually, but with CP it just breezes right past.

I have recorded a circuit that starts right where the silo gives me the option to load, and ended the recording a good 5 meters infront of the trigger and facing the same way. This is how you do it, right? The manual is a little confusing as it seems to instruct you to record the end point 10 meter PAST the starting point.

Farm sim 15 doesn't mark the kipper as a separate rear attachment, it just settles on the bed and becomes one with the vehicle, so is there perhaps a bug that fails to trigger loading in transport mode, for vehicles with a fixed "trailer" like that?

**Comment by JakobTischler** [comment]
Well, there seems to be some problems with the length and fill node calculation. But, at the same time I have to say: this mod is not really well done, many apparent errors (like material errors, unloading errors, ...). As such, we will not add support for it.
