### ISSUE TITLE
Circling

### ISSUE THREAD

**Issue by Muaddib-1** [Courseplay/courseplay#972]
I was starting to wonder what was taking my planter so long to finish a field so I went to check on it.
![2015-01-19_00001](https://cloud.githubusercontent.com/assets/5287689/5804338/c6cde9ea-9fca-11e4-94b7-5757197e71cb.jpg)
It left me a beautiful spirograph :)

https://gist.github.com/Muaddib-1/6eb39ce022b756b0cc25

I was running some trees through the woodchipper while the tractor was running the course.

**Comment by JakobTischler** [comment]
Well this is a very, very rare situation where the course ends in a field corner not orthogonal on the regular x/z axes. As we're working on a course generation update, there won't be an immediate fix for this.

**Comment by Muaddib-1** [comment]
That's cool, I thought it was more interesting than annoying with the tire tracks.
