### ISSUE TITLE
Suggestion: Chaff with Pöttinger MEX 5 reverse

### ISSUE THREAD

**Issue by MarcoT1** [Courseplay/courseplay#973]
Courseplay V4.01.0047.dev
Map: Bjoernholm
Mods: Autotractor V1.6.0.0, Autocombine V3.2.0.0
vehicles: only standard, no mods.

I think it's realistic to hang the Pottinger MEX 5 from the rear of a tractor and chop backwards.
This works fine with Autotractor (button working mode: reverse)
Now i want to control the Trailer driver (Abfahrer) by courseplay combi mode.
The problem ist now, the trailer driver departs from the rear next to the shredder -> in the wrong direction.

Probably the driver oriented to the direction of the tractor and not of the chopper.
If i let drive the chopper forward with autotractor, the driver of courseplay do the job right.
It would be very nice, if you could realize this.

Many thanks.

**Comment by JakobTischler** [comment]
Please check existing issues before creating a new one. This has already been suggested in https://github.com/Courseplay/courseplay/issues/840.
