### ISSUE TITLE
Bad calculated path on Knuston Farm

### ISSUE THREAD

**Issue by lansalot** [Courseplay/courseplay#975]
Although I see you're working on new fieldwork code (at https://github.com/Courseplay/courseplay/issues/844) , I thought I'd highlight an error in generation on  Knuston Farm, please see courseplay.xml/courseplayFields.xml at https://gist.github.com/lansalot/fa1149b99878ad598021

The path chosen with issues is "Seeing field 4", at the west side of the field, the path extends beyond the field's boundaries.

Courseplay 4v.01 .0047 (today's commits didn't seem like they would apply in this case)
Knuston farm mod at http://fs-uk.com/mods/view/35674

**Comment by JakobTischler** [comment]
Can you please post some screenshots? 

1. the field borders (course generation page -> select field 4 -> click the "eye" button)
2. the generated course (by showing all waypoints), especially the part where it extends over the field edge.

**Comment by lansalot** [comment]
Hi

Screenshots here: https://drive.google.com/folderview?id=0B8eys5FN_qZnLTV4aGlPZkdJaVU&usp=sharing

The field outline is spot on, by the look of it.

**Comment by JakobTischler** [comment]
If you don't use headland, the course will not take "holes" / "bulges" in the field edge into account. On the screenshot, you're looking at a point where both in the south and in the north there is part of the field - so what you see is the connection between those two parts.

By using headland you can avoid that.

**Comment by lansalot** [comment]
Ah sorry - that course, I didn't generate a headland; I just ran a quick one up to illustrate the problem. Here's one I actually used that has a headland and it still does it. (See the same shared folder please).

Does it with seeder, fertilizer and combine. All with a 4-lane headland.

**Comment by JakobTischler** [comment]
Yeah, at the moment not fixable.

**Comment by lansalot** [comment]
Ah OK, no worries.
