### ISSUE TITLE
Overloader to drive directly "next to combine"

### ISSUE THREAD

**Issue by Maxcdr** [Courseplay/courseplay#977]
When silaging with 2 overloaders, empty tractor is following working tractor:

![fsscreen_2015_01_20_17_55_33](https://cloud.githubusercontent.com/assets/10348839/5821766/d51d643a-a0ce-11e4-91b8-5cd7a0468f18.png)

Then full tractor is leaving, empty tractor drives to combine: in fact it drives first "behind combine" and then "next to combine":

![fsscreen_2015_01_20_17_56_15](https://cloud.githubusercontent.com/assets/10348839/5821806/2aeb9aee-a0cf-11e4-90c8-a99c22769dad.png)

It would be better if empty tractor drives directly "next to combine" without driving "behind combine":

![fsscreen_2015_01_20_17_56_22](https://cloud.githubusercontent.com/assets/10348839/5821884/a1ce096c-a0cf-11e4-801a-2e73a22d768f.png)

Courseplay v4.01.0047.dev

**Comment by ThomasGaertner** [comment]
this should have worked for a long time... thanks for the hint . try v0050 and report....

**Comment by Maxcdr** [comment]
That's okay now. Thanks !

![fsscreen_2015_01_20_22_31_37](https://cloud.githubusercontent.com/assets/10348839/5826620/55d805e2-a0f4-11e4-8ff9-b8b8969d583c.png)

**Comment by gui7545** [comment]
If the second tractor (2) is going to follow the current Tractor (1) .
When (1) is full, (2) will go directly to the state "Drive next to combine".
If (2) is not align with (1), 2 will go directly next to combine without turn around.
And (2) can go into the combine like in #1003.
In my case, (2) was on the wrong side of the combine and tried to go through it to reach the "Drive next to combine " position.
Maybe it is possible to keep the state "drive to combine" and skip it when (1) and (2) are align

**Comment by ThomasGaertner** [comment]
I decided to revert the feature because it had caused too much other issues....
so the second tractor will go now behind the copper and the to the correct side.
