### ISSUE TITLE
Mode 6: driver gets course copied from combine and in addition attached a course "drive to tip trigger and back to field"

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#978]
Searched for any issue with "copy" in it, but found nothing, so opening a new one.

Used CP 0044, sorry there is no log.txt anymore. Was deciding to post this, when video editing was done and the log was already written over.

When I have generated a field course, or recorded one and saved this, there is no problem when i load that course for a loading wagon to pick up the straw swath and attach a second course to drive to tip trigger to sell the straw and then drive back to field and continue to pick up straw.

I made a experiment recording a course driven by AutoCombine, (at the end stopped the recording, of course). Copied that temporary course from the combine to the loading wagon and attached the already saved course for selling the straw.
I expected to see the same behaviour as always when using two saved courses, but the driver was yelling "Trailer needs to be unloaded" instead of driving his unload course.
You can see it in the video [happening at 3.20](https://www.youtube.com/watch?v=nd7D58qeQL4&t=3m20s)
The recorded temporary course you can see right at the beginning of the video.
The procedure I used to copy and attach you can see [from 1:20 on](https://www.youtube.com/watch?v=nd7D58qeQL4&t=1m20s).

**Comment by JakobTischler** [comment]
The reason has nothing to do with the course being copied. Rather, you didn't set any waiting points at the beginning and end of the recording. Thus, there's no work area defined. When the unloading course is appended, CP will determine that since no waiting points exist, the *complete* course must be the work area. Hence, no unloading course is determined and the "needs to be unloaded" message appears.

**Comment by AndyK70** [comment]
Oh, ok.
So when recording I have to set waiting points manually for CP to know where field begins and ends.

got it

**Comment by JakobTischler** [comment]
> So when recording I have to set waiting points manually for CP to know where field begins and ends.

Not generally. If you only plan to have the field course, you don't need any manual waiting points, as CP will use the first and last ones as start and stop points, respectively. 
But when you plan to add an unloading/refilling course, the field area needs to be defined, and in that case you will need to set the waiting points manually.

**Comment by AndyK70** [comment]
thanks :)
