### ISSUE TITLE
Wrong trailer for this mode

### ISSUE THREAD

**Issue by Baldoius** [Courseplay/courseplay#982]
Hi!

I am using Courseplay 4.0.1 0051 dev (newest)
Used tools are: Horsch Maestro 12 SW and a New Holland T8.320

After generating a course (works), I want to start the helper.
If I try to start i became the error "Wrong trailer for this mode".

I'm using several mods, like:

• Real Night
• Inspector
• Drive Control

![fsscreen_2015_01_21_18_53_15](https://cloud.githubusercontent.com/assets/10405947/5841644/cc1e54fe-a19e-11e4-8662-65805d404781.png)

**Comment by JakobTischler** [comment]
You're trying to use a seeder in the field work mode instead of the fertilizing/seeding mode.

**Comment by Baldoius** [comment]
I'm very sorry. Thank you very much!
