### ISSUE TITLE
MEX 5 - which mode??

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#983]
Sorry if this has been covered, but I cannot figure out what mode I should use for the Mex-5 chaffer..

The only thing that seems to work is transfer mode..   fieldwork mode it just sits and waits, even when the other vehicle is pulled up next to it.

The only thing I have been able to do is use Auto-Tractor helper mode for the chaffer and CP for the unloading vehicle.

**Comment by Maxcdr** [comment]
Just tested and it works on my side with Field Work mode...

![fsscreen_2015_01_22_08_05_10](https://cloud.githubusercontent.com/assets/10348839/5851862/960744c4-a20d-11e4-8e9e-941a02993996.png)

**Comment by ThomasGaertner** [comment]
tested and made a minor change. it should work now in both ways, Maxcdr showed.
test v0061 or higher and confirm...

**Comment by Maxcdr** [comment]
Alright on my side in both ways now (v0063).

![fsscreen_2015_01_25_17_02_42](https://cloud.githubusercontent.com/assets/10348839/5892119/acc856e0-a4b4-11e4-8d78-bbf125670ece.png)

![fsscreen_2015_01_25_17_04_05](https://cloud.githubusercontent.com/assets/10348839/5892120/b103c9e2-a4b4-11e4-866c-61dd0efb3777.png)
