### ISSUE TITLE
Suggestion: show direction when recording course

### ISSUE THREAD

**Issue by OldFisher** [Courseplay/courseplay#985]
Would be nice to see a line showing current direction when recording a course. Maybe with on/off button or something.

**Comment by JakobTischler** [comment]
The current direction of ... what? The tractor? The last waypoint? The average angle?

**Comment by OldFisher** [comment]
The current direction of the tractor. Just to see exactly where it's going.

**Comment by AndyK70** [comment]
In that cases where I need it, I use to "activate" GPS mod, without locking steering. It shows me the center (green line) and lateral lines (width of tool) in red.

**Comment by OldFisher** [comment]
I strongly prefer to play without GPS mod, so it seems I need either separate line-helper mod or lines shown in courseplay. The time will show what it'll be.

**Comment by JakobTischler** [comment]
The orange arrow already shows the tractor's direction at that point.

**Comment by OldFisher** [comment]
Speaking of GPS mod: ![direction helper](http://i.ytimg.com/vi/YQTFXAc1npU/maxresdefault.jpg). That green line sticking out of the tractor is what I meant.

**Comment by JakobTischler** [comment]
Wait, so you want the tractor's direction? While watching the tractor? Where you can already see the direction, because you see the tractor and the way it's heading?

**Comment by OldFisher** [comment]
Yep. For extra-precise steering, because the tractor isn't exactly arrow-shaped.
Anyway, the introduction of "split points" makes this suggestion obsolete, because it does same thing better.

**Comment by JakobTischler** [comment]
If that is the case, I'll close this one.
