### ISSUE TITLE
request: change description "vertical offset" to "longitudinal offset"

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#987]
Vertical is from ground up, not in direction of movement.

In the manual it is described for example in HUD -> Mode 2 settings -> Pipe offset
> This value defines the vertical offset between the driver's trailer and the combine/chopper when unloading (ahead/behind).

To describe the offset of ahead/behind it is longitudinal offset, not vertical.
First I was thinking, this could be the solution for #948 but it has nothing to do with any vertical offset.

**Comment by Maxcdr** [comment]
In this case and to make it complete, horizontal should be changed by lateral :)

**Comment by Satissis** [comment]
You have to think like you are looking top down, which makes more sense when the coordinate system is also based on a top down view.

**Comment by AndyK70** [comment]
Makes sense in eyes of the developer/modder, but not for the user who is playing this in normal 3D view. Don't you think so?

**Comment by jhomer** [comment]
To be honest I understand it better with the horizontal/vertical offsets.
Horizontal- a line running side to side. 
Vertical- a line running front to back.

**Comment by AndyK70** [comment]
> Vertical- a line running front to back. 

sorry, if it sounds rude, but that is literally wrong.
vertical is something on a line up/down.
If you are in a normal 3D space like the user is in the game, vertical is something from ground up to the sky and not in front of you.

**Comment by jhomer** [comment]
I wasn't stating that horizontal/vertical are used in this case "by proper definition"
I was only saying it made sense to me how they were used. 
A few things could be used- longitudinal, fore/aft  
and as @Maxcdr said about lateral.

John Deere uses "inline" and "lateral" for their offsets.
![capture](https://cloud.githubusercontent.com/assets/7943994/5885201/13e5886c-a32e-11e4-8128-3682b81c396c.JPG)

**Comment by AndyK70** [comment]
Thanks for that sheet, as you can see in the lower description the use of vertical (c) is the same as normal understanding, from ground up. ;)

**Comment by Muaddib-1** [comment]
I suspect more people would be confused by long/lat than horz/vert.  I personally can never remember which is which when told longitude or latitude.  Horizontal and vertical I understood immediately. 
Despite vertical meaning perpendicular to the ground, in this instance there is nothing to adjust in that dimension.

I'm not against changing it from vertical but something other than longitudinal would probably be more easily understood.

**Comment by AndyK70** [comment]
I'm not bound to longitudinal, but which expression would you like to use?
* driving direction offset
* direction of train offset
* direction of motion offset
* direction of traffic offset
* travel direction offset
* heading offset
* yawning offset

any other suggestions?

My only concern is the wrong use of 'vertical'.

**Comment by JakobTischler** [comment]
"Wrong" is relative. I agree that in the technical sense you are correct - but technically only a small percentage of CP users cares about "technically". We've tried different descriptions before, and "vertical" is the one that stuck.

**Comment by Muaddib-1** [comment]
You can always change that word in translation_en.xml after you download. I might go with "linear"
