### ISSUE TITLE
BGA extension compatability

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#988]
Hey Guys,
I've encountered an incompatability between CP and upsidedown's BGA Extension (http://www.modhoster.de/mods/bgaextension--2).
If i load a manure transporter with manure from the BGA, a CP driver with a manurespreader will not drive away after being filled.
This happens because the mod includes a new "filltype", the Substrate so that you are able to fill a trailer with lq. manure from the cows, tip it into the BGA and get a little money, like in reallife.
To prevent using Biogas lq.manure, substrate was added.
It can be carried and spreaded with the standart lq.manure equiptment, but your vehicles will now only fill up to 99.9999999999999% of the fillevel, wich CP counts as vehicle not full...

Hope you understood my explanation
Greets JD_Tiger

**Comment by JakobTischler** [comment]
Please test with build 0152 or higher.

**Comment by JDTiger** [comment]
it works, BUT you have to manually switch fill to from 100 to 99 percent...

**Comment by Raints** [comment]
Somehow with 0052 automated overload stop worked with BGA extension. Have to manually hit "R" to start unload to bga.

**Comment by ThomasGaertner** [comment]
@JDTiger : @Raints : can you tell me please, which trailers you used ?

**Comment by Raints** [comment]
Tried in game kotte garant TSA 30000 and trailer from this pakage http://www.kyoshos-modfactory.de/MAN_TGS_AGRAR   Both not unloading at BGA. 
Also used this mod http://www.modhoster.com/mods/placeable-liquite-manure-lager
to collect slurry from bga. 
Now same problem, when tractor reaches bga tank or placeable manure tank it shows "....has reached overload point" but nothing happends. Have to manually hit "R" at BGA and "Z" at placeable manure tank.

**Comment by JakobTischler** [comment]
Try build 0054 and report.

**Comment by Raints** [comment]
Tested build 0054 and can confirm: All works again, with both trailers and both unload places, BGA and placeable manure tank.  

Thank you for quick respond!

**Comment by Raints** [comment]
I know its closed but when i tested with 0054 all worked, but today downloaded 0060 and in game kotte garant TSA 30000 stop working. It will load up at farm slurry tank and goes to BGA, shows "....has reached overload point" but nothing happened again, cant even hit "R". Just wont give me that option. So i tried to load up to 99% but same problem, wont give the option for "R" Kotte garant TSA 30000 working to fill up placeable slurry tank http://www.modhoster.com/mods/placeable-liquite-manure-lager
Trailer from this pack http://www.kyoshos-modfactory.de/MAN_TGS_AGRAR working in both modes- from farm to BGA and BGA to slurry tank. 
Didnt download any mods past few days so not sure what is the problem.

**Comment by JakobTischler** [comment]
Nothing changed concerning liquid manure overloading since 0054. If no "R" shows up, it means you can't even unload manually, so it's something that has nothing to do with CP. Are you sure that 1) the silo isn't full, and 2) the bonus capacity hasn't been reached?

**Comment by Raints** [comment]
Ohh, sorry about that. The silo was full, somehow moded trailer dont care about it, but ingame one dose. So moved some slurry out and all good. Sorry!
