### ISSUE TITLE
Zundisc

### ISSUE THREAD

**Issue by JDTiger** [Courseplay/courseplay#989]
Hey Guys,
its me again...
While testing the manure overloading problem, i've encourtered another problem:
CP, in fertilizermode wont start to use the Zundic on the PU18500, it folds it up and drives along the course without fertilizing the field...

Greets JD_Tiger

**Comment by Maxcdr** [comment]
Strange: it works fine for me... (v4.01.0052.dev)
Are you sure that you use driving mode 4 and not 5?

![fsscreen_2015_01_23_10_32_03](https://cloud.githubusercontent.com/assets/10348839/5872389/46c7cc6a-a2eb-11e4-8327-f6800284a1f1.png)

**Comment by JakobTischler** [comment]
I can not reproduce your problem. As Maxcdr stated, it should work as intended. Please repeat with debug channel 17 active. Then post the log.

**Comment by JakobTischler** [comment]
Closed due to inactivity.
