### ISSUE TITLE
CoursePlay ignores purchased fields after second game loading

### ISSUE THREAD

**Issue by VitaliySunny** [Courseplay/courseplay#992]
Hello.

Purchased fields w/ **crops grown**, after open CoursePlay not shows into select box (Path generation -> Select field option).

*My steps:*
1) Create second game (Westbridge hills map)
2) Purchase 9, 11, 14, 15 field
3) Seed and plant grass into 9 and 15 field w/ CoursePlay help's
4) Save, exit, next day load and got a bug

![sample](https://cloud.githubusercontent.com/assets/3903438/5875726/4b2671cc-a321-11e4-9990-849e78549c4c.png)

Edit save file not affected:
```xml
<courseplayFields automaticScan="true" onlyScanOwnedFields="false" debugScannedFields="true" debugCustomLoadedFields="true" scanStep="5" />
```

Thanks.

**Comment by JakobTischler** [comment]
During each savegame load, the fields are scanned anew. After you've seeded field 9 with grass, it will *not* be recognized as field anymore, as there's no *field terrain* anymore but only *grass terrain*. This is not a bug, but simply a limitation of how the terrain works.

The solution would be to *manually scan the field* __before__ seeding grass and then saving it. The field shape will then be loaded during the next savegame load.

This all is described in detail in our [manual](http://courseplay.github.io/courseplay/en/manual/index.html#fieldScanner).
