### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by Sage-45** [Courseplay/courseplay#993]
I downloaded the beta version and it worked great for awhile. But then for some reason the speed for everything would stay at 1mph at all times. I have tried getting the newer version(4 different sites this one included) and it wont even show up that i have it when i play the game. How do i fix it or how do i get a mod that will work.

**Comment by Satissis** [comment]
You can get the latest version here:
http://fs-uk.com/mods/view/35661/courseplay-v4-01
also make sure your game is updated to v1.2

**Comment by JakobTischler** [comment]
Closed due to inactivity.
