### ISSUE TITLE
Oscillating movement with 4wheel steering

### ISSUE THREAD

**Issue by schniedertoenz** [Courseplay/courseplay#999]
When using courseplay with 4wheel-steering tractors, the movement is oscillating
around the waypoint. It seems to be a question of damping or sensitivity of the steering.
I discovered the issue using Claas Xerion 3800 V2.

**Comment by Satissis** [comment]
Is this when driving fast or does it also apply on slow speeds ?

**Comment by Karlshoj** [comment]
Try to set the turning radius manual to say 20m

**Comment by Satissis** [comment]
@Karlshoj The turn diameter have nothing to do with the oscillating, since it's only used to calculate turn maneuvers ;)

I'm asking about the speed. since if it's only on highspeed, like over 20 kph then there is no need to dampen the steering angle at slow speed.

**Comment by Satissis** [comment]
I have added some dampening when driving faster than 20kph with 4WS vehicles.
Try out 0078 and report back.
Maybe there needs to be added a small tweak to it.

**Comment by schniedertoenz** [comment]
Hi again,

I've tried it the the recent version. It now works perfectly.
Thanks for solving!

**Comment by schniedertoenz** [comment]
P.S. I've tried it with the Claas Xerion 3300 VC V2
